### ISSUE TITLE
[New feature] Adding Space component

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#1000]
Per https://zhuanlan.zhihu.com/p/135446399 , `Space` could be a common component that we use frequently.

I think it's worthy adding to the component library.

**Comment by kooriookami** [comment]
awesome

**Comment by OneSeven** [comment]
Hope to make flex and grid compatible with each other ！

**Comment by JeremyWuuuuu** [comment]
> Hope to make flex and grid compatible with each other ！

Could you be more specific?

**Comment by OneSeven** [comment]
> > Hope to make flex and grid compatible with each other ！
> 
> Could you be more specific?

In element 2.x el-row turns on flex,'el-col span=24' will be invalid, there may be other problems, it can be realized similar to the grid in vuetify

**Comment by JeremyWuuuuu** [comment]
So, I'm going to ask you to open a new issue to track that. With detailed descriptions like `actual behaviors` `expected behaviors` etc. @OneSeven Could you do that for me?
