### ISSUE TITLE
[Component] [table] el-table自动计算宽度与flex-grow冲突

### ISSUE THREAD

**Issue by QUALIAZX** [element-plus/element-plus#10017]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 106.0.5249.61 / Windwos 10 20h2`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwid3JhcHBlclwiPlxuICAgIDxkaXYgY2xhc3M9XCJzaWRlYmFyXCI+5L6n6L655qCPPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRlbnRcIj5cbiAgICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi5ZCN56ewXCIgcHJvcD1cIm5hbWVcIiB3aWR0aD1cIjEyOFwiIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLkurrnialcIiBwcm9wPVwicGVvcGxlXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIuiBlOezu+eUteivnVwiIHByb3A9XCJ0ZWxcIiAvPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi55S15a2Q6YKu566xXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIui0puWPt+eKtuaAgVwiIC8+XG5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIuaTjeS9nFwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgICAgIDxlbC1idXR0b24gbGluayB0eXBlPVwicHJpbWFyeVwiPue8lui+kTwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgPGVsLWJ1dHRvbiBsaW5rIHR5cGU9XCJwcmltYXJ5XCI+56aB55SoPC9lbC1idXR0b24+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgICA8L2VsLXRhYmxlPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgdGFibGVEYXRhID0gcmVmKFtcbiAge1xuICAgIG5hbWU6ICdzc3MnLFxuICAgIHBlb3BsZTogJ+a1i+ivlScsXG4gICAgdGVsOiAxMjMxMjMsXG4gIH0sXG5dKTtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4ud3JhcHBlciB7XG4gIGRpc3BsYXk6IGZsZXg7XG59XG5cbi5zaWRlYmFyIHtcbiAgZmxleC1zaHJpbms6IDA7XG4gIHdpZHRoOiAxMDBweDtcbn1cblxuLmNvbnRlbnQge1xuICBmbGV4LWdyb3c6IDE7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

demo中 左右拉动代码编辑器中的宽度

### What is Expected?

向右拉动窗口宽度后table宽度正确计算

### What is actually happening?

可以发现table的宽度并不会触发自动计算。
而向左拉动时正常扩大table组件宽

### Additional comments

经排查表格组件宽度计算查与css - flex-grow属性发生冲突，外层容器中包含有该属性则宽度无法正确缩小

**Comment by wiidede** [comment]
可以在content上加个overflow: hidden吗

**Comment by QUALIAZX** [comment]
> 

这个方法有效，谢谢（不过目前改换用了计算宽度😂）

**Comment by QUALIAZX** [comment]
1.
