### ISSUE TITLE
El date picker cannot inherit class and style

### ISSUE THREAD

**Issue by chengaohe45** [element-plus/element-plus#1001]
版本：1.0.1-beta.8

例：
`
    <el-date-picker
        class="a12345"
        style="width: 300px;"
        v-model="dateValue"
        type="year"
        placeholder="选择日期">
     </el-date-picker>
`
class和style是失效的。
是故意这样设计的？
这样的设计只能做样式覆盖，体验有点不好

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz

**Comment by zazzaz** [comment]
this is a bug, will fix it soon
