### ISSUE TITLE
[Component] [tree] 【el-tree】组件的【current-change】事件参数有错误：两个参数是一样的

### ISSUE THREAD

**Issue by jesse51076008** [element-plus/element-plus#10016]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `edge 106`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtdLFxuICB9XG5dO1xuICBcbmNvbnN0IGN1cnJlbnRDaGFuZ2UgPSAoZGF0YSwgbm9kZSkgPT4ge1xuICBjb25zb2xlLmxvZyhkYXRhID09PSBub2RlKTsvLyB0cnVlIGhlcmVcbiAgYWxlcnQoZGF0YSA9PT0gbm9kZSlcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUgOmRhdGE9XCJkYXRhXCIgbm9kZS1rZXk9XCJ2YWx1ZVwiIGhpZ2hsaWdodC1jdXJyZW50IDpleHBhbmQtb24tY2xpY2stbm9kZT1cImZhbHNlXCIgQGN1cnJlbnQtY2hhbmdlPVwiY3VycmVudENoYW5nZVwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

【最小复现环境的链接】有代码

### What is Expected?

data 与 node 是不一样的对象

### What is actually happening?

data 与 node 是同一个对象

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
已经修复过了， 还没有发新版本，具体看这个https://github.com/element-plus/element-plus/issues/9869
