### ISSUE TITLE
[Component] [date-picker] DatePicker Range 选完结束时间 自动会光标选中结束时间

### ISSUE THREAD

**Issue by yzq777** [element-plus/element-plus#10024]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `103.0.5060.114`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html#%E6%97%A5%E6%9C%9F%E6%A0%BC%E5%BC%8F)

### Steps to reproduce

光标放在结束时间，然后选择开始时间和结束时间，结束时间就会呈现被光标选中的样式

### What is Expected?

没有这个被光标选中的样式

### What is actually happening?

呈现被光标选中的样式

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/40647769/194735090-fc60c2d0-7d76-4b2c-9e9b-56d3cd70ab2d.png)

**Comment by xq52301nzdm** [comment]
May be you should try find the input of DatePicker's component，and active triggering it's event of blur ! This is very useful to me !
It looks like this:
`  const DOM_LIST: any = document.querySelectorAll('.line-container-right')!;
  [...DOM_LIST].forEach(v => {
    const IPT = v.querySelector('input')
    IPT.blur()
  })`

**Comment by lydat** [comment]
Me too

**Comment by xq52301nzdm** [comment]
> 

其实我上面提到了一个解决方法，就是在组件的change事件的回调中，获取到对应的input元素，然后主动执行其失焦事件(blur())，可以达到比较完美的效果!

**Comment by chenxch** [comment]
fixed #10533
