### ISSUE TITLE
[TypeScript] [All] should we use dts file declare .vue file module?

### ISSUE THREAD

**Issue by weidehai** [element-plus/element-plus#10022]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

1.clone this repo
2.install dependencies
3.just open cascader-panel folder and open index.ts file,then can see vscode error tips(Cannot find module './src/index.vue' or its corresponding type declarations)

### What is Expected?

No errors

### What is actually happening?

Cannot find module './src/index.vue' or its corresponding type declarations

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
https://github.com/johnsoncodehk/volar/discussions/471
