### ISSUE TITLE
[Component] [dropdown] `dropdown` 按需引入没有 `el-button-group` 的样式

### ISSUE THREAD

**Issue by codesyofo** [element-plus/element-plus#10026]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `win10`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

![image](https://user-images.githubusercontent.com/49975575/194735645-d9e70d37-45dc-47e4-86cd-b9da87e2623b.png)

### Steps to reproduce

-

### What is Expected?

-

### What is actually happening?

没有

### Additional comments

_(empty)_

**Comment by codesyofo** [comment]
@chenxch [elementplus-dropdown](https://github.com/codesyofo/elementplus-dropdown)

**Comment by chenxch** [comment]
> @chenxch [elementplus-dropdown](https://github.com/codesyofo/elementplus-dropdown) 运行项目，点击 `about`

收到~
