### ISSUE TITLE
[Component] [tree-select] <el-tree-select>使用props改变label和value值后，不能选择节点

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#10043]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mac OS 12.4`
- Build Tool: `Webpack`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDxlbC10cmVlLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBjaGVjay1zdHJpY3RseVxuICAgIDpwcm9wcz1cInByb3BzXCJcbiAgICA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCJcbiAgICBzaG93LWNoZWNrYm94XG4gIC8+XG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3QgcHJvcHMgPSB7XG4gIGxhYmVsOiAnZGVwYXJ0bWVudF9uYW1lJyxcbiAgdmFsdWU6ICdkZXBhcnRtZW50X2lkJyxcbn1cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBkZXBhcnRtZW50X2lkOiAnMScsXG4gICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGRlcGFydG1lbnRfaWQ6ICcxLTEnLFxuICAgICAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBkZXBhcnRtZW50X2lkOiAnMS0xLTEnLFxuICAgICAgICAgICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBkZXBhcnRtZW50X2lkOiAnMicsXG4gICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGRlcGFydG1lbnRfaWQ6ICcyLTEnLFxuICAgICAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBkZXBhcnRtZW50X2lkOiAnMi0xLTEnLFxuICAgICAgICAgICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBkZXBhcnRtZW50X2lkOiAnMi0yJyxcbiAgICAgICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgZGVwYXJ0bWVudF9pZDogJzItMi0xJyxcbiAgICAgICAgICAgIGRlcGFydG1lbnRfbmFtZTogJ0xldmVsIHRocmVlIDItMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用了props属性，对value和label重新赋值后，任意一层级的节点都不能被选中

### What is Expected?

任意级别的节点都可以被选中

### What is actually happening?

不能选中任意层级的节点

### Additional comments

_(empty)_

**Comment by holazz** [comment]
`props` 里没有 value 的配置，你可以使用 `node-key` 来指定唯一标识属性 [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDxlbC10cmVlLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBub2RlLWtleT1cImRlcGFydG1lbnRfaWRcIlxuICAgIGNoZWNrLXN0cmljdGx5XG4gICAgOnByb3BzPVwicHJvcHNcIlxuICAgIDpyZW5kZXItYWZ0ZXItZXhwYW5kPVwiZmFsc2VcIlxuICAgIHNob3ctY2hlY2tib3hcbiAgLz5cblxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBwcm9wcyA9IHtcbiAgbGFiZWw6ICdkZXBhcnRtZW50X25hbWUnLFxufVxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIGRlcGFydG1lbnRfaWQ6ICcxJyxcbiAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgZGVwYXJ0bWVudF9pZDogJzEtMScsXG4gICAgICAgIGRlcGFydG1lbnRfbmFtZTogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGRlcGFydG1lbnRfaWQ6ICcxLTEtMScsXG4gICAgICAgICAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGRlcGFydG1lbnRfaWQ6ICcyJyxcbiAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgZGVwYXJ0bWVudF9pZDogJzItMScsXG4gICAgICAgIGRlcGFydG1lbnRfbmFtZTogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGRlcGFydG1lbnRfaWQ6ICcyLTEtMScsXG4gICAgICAgICAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGRlcGFydG1lbnRfaWQ6ICcyLTInLFxuICAgICAgICBkZXBhcnRtZW50X25hbWU6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBkZXBhcnRtZW50X2lkOiAnMi0yLTEnLFxuICAgICAgICAgICAgZGVwYXJ0bWVudF9uYW1lOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5cbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
