### ISSUE TITLE
[Component] [select] el-select with JSX not works well

### ISSUE THREAD

**Issue by lzr900515** [element-plus/element-plus#10045]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `chrome 版本 105.0.5195.125（正式版本） (x86_64)`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW4xXCI+RHluYW1pYyBwcm9wczwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94LCBFbFNlbGVjdCwgRWxPcHRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAnTWVzc2FnZScsXG4gICAgbWVzc2FnZTogaCgncCcsIG51bGwsIFtcbiAgICAgIGgoJ3NwYW4nLCBudWxsLCAnTWVzc2FnZSBjYW4gYmUgJyksXG4gICAgICBoKCdpJywgeyBzdHlsZTogJ2NvbG9yOiB0ZWFsJyB9LCAnVk5vZGUnKSxcbiAgICBdKSxcbiAgfSlcbn1cblxuY29uc3Qgb3BlbjEgPSAoKSA9PiB7XG4gIGNvbnN0IG5ld1BhZ2VTY2hlbWEgPSByZWY8c3RyaW5nPignMzMzMzQ0NCcpO1xuICBjb25zdCBwYWdlVGVtbGF0ZUxpc3QgPSByZWY8YW55W10+KFtcbiAgICB7XG4gICAgICBOYW1lOiAnbW9iYW4nLFxuICAgICAgU2NoZW1hOiAnMzMzMzQ0NCcsXG4gICAgfSxcbiAgXSk7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYTQxMmdlJyxcbiAgICAvLyBTaG91bGQgcGFzcyBhIGZ1bmN0aW9uIGlmIFZOb2RlIGNvbnRhaW5zIGR5bmFtaWMgcHJvcHNcbiAgICBtZXNzYWdlOiBoKFxuICAgICAgRWxTZWxlY3QsXG4gICAgICB7XG4gICAgICAgIG1vZGVsVmFsdWU6IG5ld1BhZ2VTY2hlbWEudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogc3RyaW5nKSA9PiB7XG4gICAgICAgICAgbmV3UGFnZVNjaGVtYS52YWx1ZSA9IHZhbDtcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICAoKSA9PiBbXG4gICAgICAgIHtcbiAgICAgICAgICBTY2hlbWE6ICcnLFxuICAgICAgICAgIE5hbWU6ICfnqbrpobXpnaLmqKHmnb8nLFxuICAgICAgICB9LFxuICAgICAgXVxuICAgICAgICAuY29uY2F0KHBhZ2VUZW1sYXRlTGlzdC52YWx1ZSlcbiAgICAgICAgLm1hcCgoeyBTY2hlbWEsIE5hbWUgfSkgPT4ge1xuICAgICAgICAgIHJldHVybiBoKEVsT3B0aW9uLCB7XG4gICAgICAgICAgICBsYWJlbDogTmFtZSxcbiAgICAgICAgICAgIHZhbHVlOiBTY2hlbWEsXG4gICAgICAgICAgICBrZXk6IFNjaGVtYSxcbiAgICAgICAgICB9KTtcbiAgICAgICAgfSlcbiAgICApLFxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击button 触发 messageBox弹窗，切换select选项，视图没有更新。

### What is Expected?

切换select选项，视图更新，选中选项

### What is actually happening?

切换选项，依然显示之前的值。

### Additional comments

_(empty)_

**Comment by lzr900515** [comment]
> 你这种情况需要给 `message` 选项传递一个函数 [文档](https://element-plus.org/en-US/component/message-box.html#use-vnode)
> 
> [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW4xXCI+RHluYW1pYyBwcm9wczwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94LCBFbFNlbGVjdCwgRWxPcHRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAnTWVzc2FnZScsXG4gICAgbWVzc2FnZTogaCgncCcsIG51bGwsIFtcbiAgICAgIGgoJ3NwYW4nLCBudWxsLCAnTWVzc2FnZSBjYW4gYmUgJyksXG4gICAgICBoKCdpJywgeyBzdHlsZTogJ2NvbG9yOiB0ZWFsJyB9LCAnVk5vZGUnKSxcbiAgICBdKSxcbiAgfSlcbn1cblxuY29uc3Qgb3BlbjEgPSAoKSA9PiB7XG4gIGNvbnN0IG5ld1BhZ2VTY2hlbWEgPSByZWY8c3RyaW5nPignMzMzMzQ0NCcpO1xuICBjb25zdCBwYWdlVGVtbGF0ZUxpc3QgPSByZWY8YW55W10+KFtcbiAgICB7XG4gICAgICBOYW1lOiAnbW9iYW4nLFxuICAgICAgU2NoZW1hOiAnMzMzMzQ0NCcsXG4gICAgfSxcbiAgXSk7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYTQxMmdlJyxcbiAgICAvLyBTaG91bGQgcGFzcyBhIGZ1bmN0aW9uIGlmIFZOb2RlIGNvbnRhaW5zIGR5bmFtaWMgcHJvcHNcbiAgICBtZXNzYWdlOiAoKSA9PiBoKFxuICAgICAgRWxTZWxlY3QsXG4gICAgICB7XG4gICAgICAgIG1vZGVsVmFsdWU6IG5ld1BhZ2VTY2hlbWEudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogc3RyaW5nKSA9PiB7XG4gICAgICAgICAgbmV3UGFnZVNjaGVtYS52YWx1ZSA9IHZhbDtcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICAoKSA9PiBbXG4gICAgICAgIHtcbiAgICAgICAgICBTY2hlbWE6ICcnLFxuICAgICAgICAgIE5hbWU6ICfnqbrpobXpnaLmqKHmnb8nLFxuICAgICAgICB9LFxuICAgICAgXVxuICAgICAgICAuY29uY2F0KHBhZ2VUZW1sYXRlTGlzdC52YWx1ZSlcbiAgICAgICAgLm1hcCgoeyBTY2hlbWEsIE5hbWUgfSkgPT4ge1xuICAgICAgICAgIHJldHVybiBoKEVsT3B0aW9uLCB7XG4gICAgICAgICAgICBsYWJlbDogTmFtZSxcbiAgICAgICAgICAgIHZhbHVlOiBTY2hlbWEsXG4gICAgICAgICAgICBrZXk6IFNjaGVtYSxcbiAgICAgICAgICB9KTtcbiAgICAgICAgfSlcbiAgICApLFxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

感谢，另外还有个类似的问题。如果我想根据用户的select选择结果，动态更新messageBox的title，应该如何实现呢？ 期待您的解答。

**Comment by holazz** [comment]
给 Select 一个 onChange 事件，在里面动态更改 title 的值。

**Comment by lzr900515** [comment]
> 给 Select 一个 onChange 事件，在里面动态更改 title 的值。

嗯嗯，可以了，不能直接用模板字符串拼接。 感谢~
