### ISSUE TITLE
[Docs] [All] 部署在 gitee的文档，切换时会报404，需要刷新后才能使用

### ISSUE THREAD

**Issue by lb091188** [element-plus/element-plus#10057]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `win10 Edge 106`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tooltip.html)

### Steps to reproduce

打开后，点击组件列表切换文档，内容不切换，会有404提示

### What is Expected?

点击组件列表切换文档

### What is actually happening?

点击后不文档没切换

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
same：https://github.com/element-plus/element-plus/issues/9196
