### ISSUE TITLE
[Component] [table] row-dblclick and disabled buttons

### ISSUE THREAD

**Issue by axel-iotify** [element-plus/element-plus#10056]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgQHJvdy1kYmxjbGljaz1cImRvU29tZXRoaW5nXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25zXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUVkaXQoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RWRpdDwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvblxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgICAgdHlwZT1cImRhbmdlclwiXG4gICAgICAgICAgQGNsaWNrLmNhcHR1cmUuc3RvcD1cImhhbmRsZURlbGV0ZShzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgIGRpc2FibGVkXG4gICAgICAgICAgPkRlbGV0ZTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5jb25zdCBoYW5kbGVFZGl0ID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuY29uc3QgaGFuZGxlRGVsZXRlID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbiAgXG5mdW5jdGlvbiBkb1NvbWV0aGluZyhyb3csIGNvbHVtbiwgZXZlbnQpIHtcbiAgY29uc29sZS5sb2coJ2hleSEnLCByb3csIGNvbHVtbiwgZXZlbnQpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup>

...

function doSomething(row, column, event) {
  console.log('hey!', row, column, event)
}
</script>

<template>
  <el-table :data="tableData" @row-dblclick="doSomething">
  ...
   <el-button
          size="small"
          type="danger"
          @click.stop="handleDelete(scope.$index, scope.row)"
          disabled
          >Delete</el-button
        >
</template>
```

### What is Expected?

Double clicking on the disabled "delete" button should not trigger the `doSomething` method on the row.

### What is actually happening?

You can see an output on the browser console with the execution of `doSomething`

### Additional comments

At least in my opinion it should be the case that disabled buttons shouldn't trigger the doubleclick. Makes for an unintuitive experience.

**Workaround:** 
Currently, I had to manually add and determine the `className` of the column provided in the handler after user double clicks and determine if I want to proceed or not but it feels too hacky.

![image](https://user-images.githubusercontent.com/84547321/195220781-17d9669c-6c68-4515-8bf7-33e687f48d0f.png)

**Comment by Simon-He95** [comment]
I think the disabled Button will not trigger events on it so you can't stop.
Maybe you can wrap it with `<div  @dblclick.stop="()=>{}">`

**Comment by axel-iotify** [comment]
Thanks for the response!
I haven't tried it yet, but I'd need to do that for each button I have in my cells. 
I don't think it is ideal.

**Comment by Simon-He95** [comment]
Maybe you can stop in top dblclick, return directly when e.srcElement or e.srcElement.parentNode has disabled attribute:)

**Comment by btea** [comment]
This should be a bug of chrome, it should be normal in firefox, you can refer to this [issue](https://github.com/whatwg/html/issues/5886).
