### ISSUE TITLE
[Component] [time-select] TimeSelect rang is 00:00 ~ 24:00, options list is  00:00 ~ 00:00

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#10064]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `macOS lasted / chrome  lasted`
- Build Tool: `Vite`

### Related Component

- `el-time-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGltZS1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHN0YXJ0PVwiMDA6MDBcIlxuICAgIHN0ZXA9XCIwMTowMFwiXG4gICAgZW5kPVwiMjQ6MDBcIlxuICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0IHRpbWVcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

See demo for Reproduction Link

### What is Expected?

rang is 00:00 ~ 24:00, options list is  00:00 ~ 24:00

### What is actually happening?

TimeSelect rang is 00:00 ~ 24:00, options list is  00:00 ~ 00:00

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Without the option 24, 24:00 = 00:00

**Comment by chenxch** [comment]
You can setting 00:00~23:59
