### ISSUE TITLE
[Component] [date-picker] el-date-picker 日期选择器，互相点击输入框不会出现 DatePicker 面板

### ISSUE THREAD

**Issue by thisKing** [element-plus/element-plus#10062]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.17`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 100.0.4896.127 x64`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker.html)

### Steps to reproduce

步骤
1、打开 element-plus 官网
2、找到 Date Picker 日期选择器
3、映入眼帘第一个例子，看见二个日期选择器，然后点击选择器输入框，弹窗一个日期面板
4、重点：别管那个面板，鼠标直接点击另外一个日期选择器输入框。发现选择器不会弹出日期面板
5、在点击会原来日期显示器输入框，也不会弹出日期面板

### What is Expected?

互相点击日期选择器(el-date-picker)会弹出日期选择面板

### What is actually happening?

互相点击日期选择器(el-date-picker)不会弹出日期选择面板

### Additional comments

_(empty)_

https://user-images.githubusercontent.com/22740226/195302823-257175ad-e6d1-484e-a833-ebe26f28b895.mp4

**Comment by chenxch** [comment]
fixed #9941
