### ISSUE TITLE
[Component] [date-picker] value-format not format initial modelValue

### ISSUE THREAD

**Issue by ChpShy** [element-plus/element-plus#10068]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkYXRlID0gcmVmKFwiMjAyMi0xMC0xMlwiKTtcbiAgXG5jb25zdCBvbkNsaWNrID0gKCkgPT4ge1xuICAvLyAxLiBpbml0aWFsIHZhbHVlOiBleHBlY3QgYWxlcnQgMTY2NTUzMjgwMDAwMFxuXHRjb25zb2xlLmxvZyhkYXRlLnZhbHVlKTtcbiAgXG4gIGRhdGUudmFsdWUgPSBcIjIwMjItMTAtMTNcIlxuICBcbiAgLy8gMi4gbmV3IHZhbHVlOiBleHBlY3QgYWxlcnQgMTY2NTYxOTIwMDAwMFxuICBuZXh0VGljaygoKSA9PiB7XG4gICAgY29uc29sZS5sb2coZGF0ZS52YWx1ZSk7XG4gIH0pXG59XG5cblxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDM+dnVlIHZlcnNpb246IHt7IHZ1ZVZlcnNpb24gfX08L2gzPlxuICA8aDM+ZWxlbWVudC1wbHVzIHZlcnNpb246IHt7IEVwVmVyc2lvbiB9fTwvaDM+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cImRhdGVcIlxuICAgICAgdmFsdWUtZm9ybWF0PVwieFwiXG4gICAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvbkNsaWNrXCIgdHlwZT1cInByaW1hcnlcIj5TdWJtaXQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click submit button

### What is Expected?

expect alert 1665532800000

### What is actually happening?

alert 2022-10-12

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment]
note： the update is asynchronous, pls replace alert with console and the second value need to wrap it with setTimeout

**Comment by ChpShy** [comment]
> note： the update is asynchronous, pls replace alert with console and the second value need to wrap it with setTimeout

thx, updated.
