### ISSUE TITLE
script website-build execution error

### ISSUE THREAD

**Issue by CocaColf** [element-plus/element-plus#1007]
when i clone the project and run the script `website-build`,there is an error :

![image](https://user-images.githubusercontent.com/25732253/102209946-821c9200-3f0c-11eb-8d29-403d1c2b803d.png)

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/102210101-b7c17b00-3f0c-11eb-8ad7-90c05b1f84d3.png)
We literally have this written in the `README.md`, please read it before getting started.

**Comment by CocaColf** [comment]
sorry, my bad.
