### ISSUE TITLE
[Component] [switch] [Component] [switch] 按钮内的文本超过3个中文后被直接截断，即使增加按钮的宽度也还是只显示3个中文

### ISSUE THREAD

**Issue by Fate-ui** [element-plus/element-plus#10075]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome/106 / Windows NT 10.0`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDM+XG4gICAgVnVlIFZlcnNpb246IHt7dnVlVmVyc2lvbn19XG4gIDwvaDM+XG4gIDxoMz5cbiAgICBFbGVtZW50LVBsdXMgVmVyc2lvbjoge3tFcFZlcnNpb259fVxuICA8L2gzPlxuICA8aDE+U3dpY3Ro57uE5Lu25rWL6K+VPC9oMT5cbiAgPHA+6Zeu6aKY5o+P6L+w77ya5oyJ6ZKu5YaF55qE5paH5pys5pi+56S65LiN5YWoPC9wPlxuXHQ8cD7lupTmmL7npLrvvJrkuIDplK7luIPpmLI8L3A+XG4gIDxwPiDlrp7pmYXmmL7npLrvvJrkuIDplK7luIM8L3A+XG4gIDxlbC1zd2l0Y2ggYWN0aXZlLXRleHQ9XCLkuIDplK7mkqTpmLJcIlxuICAgICAgICAgIFx0aW5hY3RpdmUtdGV4dD1cIuS4gOmUruW4g+mYslwiXG4gICAgICAgICAgICBpbmxpbmUtcHJvbXB0XG4gICAgICAgICAgICAgd2lkdGg9XCI4MHB4XCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

将switch的inactive-text设为：一键布防

### What is Expected?

按钮文本显示为：一键布防

### What is actually happening?

按钮文本显示为：一键布

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment]
I think that we can't remove the `substring(0,3)` directly, if the width is not enough the text will be obscured。
I add `textStyle` to handle this situation.
https://github.com/element-plus/element-plus/pull/10081

**Comment by Fate-ui** [comment]
> I think that we can't remove the `substring(0,3)` directly, if the width is not enough the text will be obscured。 I add `textStyle` to handle this situation. #10081

I agree with you! it is more rigorous.
