### ISSUE TITLE
[Component] [table] [Component] [table] 在table中展示树形数据，且添加多选框。在选择数据时，父级数据和子级数据之间没有联动

### ISSUE THREAD

**Issue by Fate-ui** [element-plus/element-plus#10080]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome/106 / Windows NT 10.0`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGlkOiAnMScsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAnMTEnLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6ICcxMicsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICAgIF1cbiAgfSxcbiAge1xuICAgIGlkOiAnMicsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgaWQ6ICczJyxcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICBcbiAgPGgxPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvaDE+XG48aDM+XG4gIOmXrumimOaPj+i/sO+8mnRhYmxl57uE5Lu25bGV56S65qCR5b2i5pWw5o2u5pe277yM5bm25LiU5re75Yqg5aSa6YCJ5qGG44CC54i257qn5pWw5o2u5ZKM5a2Q57qn5pWw5o2u5LmL6Ze05pyq6IGU5Yqo44CCXG4gIDwvaDM+XG4gIDxoMz5cbiAgICDmk43kvZzmraXpqqTvvJrpgInkuK3niLbnuqfmlbDmja7vvIjmiJbogIXnm7TmjqXlhajpgInvvIlcbiAgPC9oMz5cbiAgIDxoMz5cbiAgICDmnJ/lvoXvvJrlrZDnuqfmlbDmja7kuZ/lupTooqvpgInkuK1cbiAgPC9oMz5cbiAgPGgzPlxuICAgIOWunumZhe+8muWtkOe6p+aVsOaNruacquiiq+mAieS4rVxuICA8L2gzPlxuICBcbiAgPGVsLXRhYmxlXG4gICAgcmVmPVwibXVsdGlwbGVUYWJsZVJlZlwiXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgIHJvdy1rZXk9XCJpZFwiXG4gICAgQHNlbGVjdGlvbi1jaGFuZ2U9XCJoYW5kbGVTZWxlY3Rpb25DaGFuZ2VcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIHNob3ctb3ZlcmZsb3ctdG9vbHRpcCAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

选中父级数据（或者直接全选数据）

### What is Expected?

所有的子级数据也应被选中

### What is actually happening?

子级数据未被选中

### Additional comments

_(empty)_

**Comment by L1yp** [comment]
老BUG了 半年过去了0.0
