### ISSUE TITLE
[Component] [checkbox-group, checkbox] wrong checked status when label is Object

### ISSUE THREAD

**Issue by catkinmu** [element-plus/element-plus#10090]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.18`
- Browser / OS: `Microsoft Edge 版本 106.0.1370.42 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-checkbox-group`
- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2hlY2tib3gtZ3JvdXAgdi1tb2RlbD1cImNoZWNrTGlzdFwiPlxuICAgPGVsLWNoZWNrYm94XG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIGFyclwiXG4gICAgICAgICAgXG4gICAgICAgICAgOmxhYmVsPVwiaXRlbVwiXG4gICAgICAgID5cbiAgICAgICAgICB7eyBpdGVtLnRpdGxlIH19XG4gICAgICAgIDwvZWwtY2hlY2tib3g+XG4gIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBjaGVja0xpc3QgPSByZWYoW10pXG5cbmNvbnN0IGFyciA9cmVmKCBbe2lkOjAsdGl0bGU6XCIxMTExMTExMTFcIn0se2lkOjEsdGl0bGU6JzEyMyd9XSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<template>
  <el-checkbox-group v-model="checkList">
   <el-checkbox
          v-for="item in arr"
          :label="item"
        >
          {{ item.title }}
        </el-checkbox>
  </el-checkbox-group>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const checkList = ref([])

const arr =ref( [{id:0,title:"111111111"},{id:1,title:'123'}])
</script>

### What is Expected?

checkbox is checked properly

### What is actually happening?

The checkbox is not checked

### Additional comments

Hope to solve

**Comment by iDestin** [comment]
There is something wrong with the way you use it，You can modify the code as follows

```vue
<template>
  <el-checkbox-group v-model="checkList">
   <el-checkbox v-for="item in arr" :lable="item.title">
   </el-checkbox>
  </el-checkbox-group>
</template>
```

or

```vue
<template>
  <el-checkbox-group v-model="checkList">
   <el-checkbox v-for="item in arr">
     {{ item.title }}
   </el-checkbox>
  </el-checkbox-group>
</template>
```

**Comment by Simon-He95** [comment]
the label of the `el-checkbox` prop under `el-checkbox-group` should be a string. 
so you should replace ~item~ with  `item.title`
```
<el-checkbox v-for="item in arr" :label="item.title"></el-checkbox>
```

**Comment by catkinmu** [comment]
![image](https://user-images.githubusercontent.com/27178791/196069497-9e890d87-25c5-4771-92c3-ea6512192814.png)
