### ISSUE TITLE
### Message

### ISSUE THREAD

**Issue by SunLn** [element-plus/element-plus#101]

**Comment by JeremyWuuuuu** [comment]
@Bruno Santos hi, are you interested in this?

**Comment by bmfs** [comment]
Sure. I can give a try.

**Comment by JeremyWuuuuu** [comment]
@bmfs , nice! that'd be great, FYI, there is a component named `Notification` might share the same functionality with `Message`, you can take a look on that and also if you find any common logic in both case, it'd be a good idea if you extract them out

**Comment by zazzaz** [comment]
@bmfs   hi, please make a draft PR for us to track on the migration progress, if you have encountered any problem please contact us

**Comment by bmfs** [comment]
Noticed two bugs that also affect Notification:

 * When multiple Messages/Notifications that use a VNode are closed, the offset prop doesn't update.
 * When more than 2 Messages/Notifications that use a VNode are closed, I'm getting the following error: 
```Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at getId (runtime-core.esm-bundler.js:334)
    at runtime-core.esm-bundler.js:351
    at Array.sort (<anonymous>)
    at flushJobs (runtime-core.esm-bundler.js:351)
```

**Comment by bmfs** [comment]
The pull request https://github.com/element-plus/element-plus/pull/291 is ready to be reviewed.

Ended up not extracting any common logic with the Notification component, but I also agree that some can be shared.

Ended up finding a few bugs in the Notification component and I would be happy to prepare a pull request with fixes and also work on extracting the common code.

Should I open a ticket to be associated with the pull request?
