### ISSUE TITLE
[Component] [select] remote input and select with keyboard will lead to moving chaos

### ISSUE THREAD

**Issue by Simon-He95** [element-plus/element-plus#10107]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Chrome/105.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select.html#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2)

### Steps to reproduce

input `al` and use keyBoard choose one then backspace l then use keyBoard turn bottom turn top will lead to moving chaos

### What is Expected?

Move up and down correctly as expected

### What is actually happening?

move chaos

### Additional comments

在远程搜索组件种输入al,通过键盘上下来选择一项,然后删除l,再次通过键盘上下移动选择时候会发现上下移动,可能会颠倒可能会一下子移动很多步

**Comment by Simon-He95** [comment]
@baiwusanyu-c  it not works 
I find that the order of the options is the opposite of the option of component setup `log props.label`
But I didn't find anything causing this problem, which is maybe a bug with vue?
![cbb4dce4-055e-435d-8304-f0b3fb609a3b](https://user-images.githubusercontent.com/57086651/196142937-cd0cb83c-b544-4220-b526-6490c3333335.gif)

**Comment by baiwusanyu-c** [comment]
Yes, if you don't bind the key, this problem will not occur

**Comment by Little-Frog-233** [comment]
这个问题修复了么？

**Comment by baiwusanyu-c** [comment]
> 这个问题修复了么？

可以帮我试试 pr，但是绑定key的话需要绑定一个index来保证列表更新的顺序，否则的话不要给option绑key

**Comment by kooriookami** [comment]
Fixed now
