### ISSUE TITLE
Raise "Uncaught TypeError: Object(...) is not a function" error while importing components in nuxt.js plugin.

### ISSUE THREAD

**Issue by Bing573** [element-plus/element-plus#1010]
The plugin is as simple as below
```javascript
import { ElButton } from 'element-plus';

export default (ctx) => {
}
```
No matter what component is imported, it always raises  an error as follow
```
Uncaught TypeError: Object(...) is not a function
    at Module.eval (index.esm.js?3fd4:1)
    at eval (index.esm.js:138)
    at Module../node_modules/element-plus/lib/index.esm.js (app.js:886)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (ElementPlus.js:10)
    at Module../plugins/ElementPlus.js (app.js:637)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.js:36)
```

**Comment by zazzaz** [comment]
a reproduction demo please

**Comment by Bing573** [comment]
Wrong VUE version,  my mistake.

**Comment by QQhuan** [comment]
请问具体是什么问题，是怎么解决的？

**Comment by zazzaz** [comment]
@QQhuan you can try to use the latest version of vue

**Comment by Adasboy** [comment]
I'm rookie with VueJS. I'm gonna work with argon-templates.
Could you explain detail about how to fix?

**Comment by Bing573** [comment]
> I'm rookie with VueJS. I'm gonna work with argon-templates.
> Could you explain details about how to fix?

I doubt you are using incompatible libs, check your VUE and Element-UI version first.

**Comment by chenpenggood** [comment]
vue and elementPlus version not match, elementplus@1.0.2-beta.71 match Low version vue
