### ISSUE TITLE
[Feature Request] 如何正确引入picker组件（路径：element-plus/packages/components/time-picker/src/common/picker.vue）

### ISSUE THREAD

**Issue by Tiramisupxl** [element-plus/element-plus#10110]
### Existing Component
是

### Component Name
picker

### Description
如何引入element-plus/packages/components/time-picker/src/common/picker.vue这个组件。我在我的项目里通过@element-plus/components引入这个组件，但是样式和组件属性表现跟现有组件不一致

**Comment by gjfei** [comment]
https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

**Comment by Tiramisupxl** [comment]
> https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

你好，感觉回复。我引入的不是element-plus导出的组件哦。而是时间、日期选择器使用的公共组件picker：element-plus/packages/components/time-picker/src/common/picker.vue这

**Comment by gjfei** [comment]
> > https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5
> 
> 你好，感觉回复。我引入的不是element-plus导出的组件哦。而是时间、日期选择器使用的公共组件picker：element-plus/packages/components/time-picker/src/common/picker.vue这

不建议这样做，如果要这样做需要单独引入样式

**Comment by Tiramisupxl** [comment]
> 

因为想基于这个组件封装一个上下半年的时间选择器。
但是很奇怪，
1、引入后，el-input的html结果少了<div class="el-input__wrapper"></div>这一层；
2、想通过ref调用picker的handleClose方法，但是报错说该方法不存在

**Comment by xiaoxian521** [comment]
If there is no export, there will be problems when importing. In this case, it is recommended that you fully encapsulate it yourself
