### ISSUE TITLE
[Component] Form 表单 label 样式

### ISSUE THREAD

**Issue by q2419068625** [element-plus/element-plus#10111]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-form`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHNlYXJjaFBhcmFtID0gcmVhY3RpdmUoe1xuICB1aWQ6IFwiXCIsXG5cdHJlZ1RpbWU6IFwiXCJcbn0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1mb3JtIDppbmxpbmU9XCJ0cnVlXCIgOm1vZGVsPVwic2VhcmNoUGFyYW1cIiBsYWJlbC13aWR0aD1cIjExMHB4XCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi54mI5pys77yaXCI+XG4gICAgICAgIDxlbC1pbnB1dCBwbGFjZWhvbGRlcj1cIueJiOacrFwiIHYtbW9kZWw9XCJzZWFyY2hQYXJhbS5hcHBWZXJzaW9uQ29kZVwiIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cblxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuazqOWGjOaXtumXtO+8mlwiPlxuICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICB2LW1vZGVsPVwic2VhcmNoUGFyYW0ucmVnVGltZVwiXG4gICAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiIC0gXCJcbiAgICAgICAgICBzdGFydC1wbGFjZWhvbGRlcj1cIuW8gOWni+aXtumXtFwiXG4gICAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwi57uT5p2f5pe26Ze0XCJcbiAgICAgICAgICBmb3JtYXQ9XCJZWVlZLU1NLUREXCJcbiAgICAgICAgICB2YWx1ZS1mb3JtYXQ9XCJ4XCJcbiAgICAgICAgICBjbGFzcz1cInctMjEwcHhcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICA8L2VsLWZvcm0+XG4gICA8L3RlbXBsYXRlPlxuXG48c3R5bGU+XG5sYWJlbCB7XG4gIGZvbnQtd2VpZ2h0OiA3MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<template>
   <el-form :inline="true" :model="searchParam" label-width="110px">
      <el-form-item label="版本：">
        <el-input placeholder="版本" v-model="searchParam.appVersionCode" />
      </el-form-item>

      <el-form-item label="注册时间：">
        <el-date-picker
          v-model="searchParam.regTime"
          type="daterange"
          range-separator=" - "
          start-placeholder="开始时间"
          end-placeholder="结束时间"
          format="YYYY-MM-DD"
          value-format="x"
          class="w-210px"
        />
      </el-form-item>
   </el-form>
   </template>

<style>
label {
  font-weight: 700;
}
</style>

### What is Expected?

label font-weight 改变

### What is actually happening?

label 的 font-weight 没改变

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
```
<style>
:deep(.el-form-item__label) {
  font-weight: 700;
}
</style>
```

**Comment by kooriookami** [comment]
<style scoped>
::v-deep(.el-form-item__label) {
  font-weight: 700;
}
</style>
