### ISSUE TITLE
[Component] [dialog] 没有关闭Loading的时候，如果调用ElMessageBox，会导致消息框无法关闭

### ISSUE THREAD

**Issue by languanghao** [element-plus/element-plus#10126]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgICAgPGRpdiB2LWxvYWRpbmcubG9jay5mdWxsc2NyZWVuPVwiaXNMb2FkaW5nXCI+XG4gIDxlbC1kaWFsb2dcbiAgICB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiXG4gICAgdGl0bGU9XCJUaXBzXCJcbiAgICB3aWR0aD1cIjMwJVwiXG4gICAgOmJlZm9yZS1jbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgICBhcHBlbmQtdG8tYm9keVxuICAgIDpjbG9zZS1vbi1jbGljay1tb2RhbD1cImZhbHNlXCJcbiAgICA6Y2xvc2Utb24tcHJlc3MtZXNjYXBlPVwiZmFsc2VcIlxuICAgIG1vZGFsXG4gICAgZHJhZ2dhYmxlXG4gICAgOmxvYWRpbmc9XCJpc0xvYWRpbmdcIiAgICAgICAgIFxuICA+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoZWxsbygpXCI+VGhpcyBpcyBhIG1lc3NhZ2U8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCJcbiAgICAgICAgICA+Q29uZmlybTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgaXNMb2FkaW5nID0gcmVmKGZhbHNlKVxuXG5jb25zdCBoZWxsbyA9IGFzeW5jICgpID0+IHtcbiAgaXNMb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICBcbiAgd2luZG93LnNldFRpbWVvdXQoYXN5bmMgKCkgPT4ge1xuICAgIGF3YWl0IEVsTWVzc2FnZUJveC5hbGVydChcbiAgICAgICAgJ+i/memHjOacieS4quS4gOS4qumUmeivrycsXG4gICAgICAgICfplJnor68nLFxuICAgICAgICB7XG4gICAgICAgICAgICB0eXBlOiAnZXJyb3InLFxuICAgICAgICB9LFxuICAgIClcbiAgICAgaXNMb2FkaW5nLnZhbHVlID0gZmFsc2VcbiAgfSwgNTAwKVxuICBcbiAgICBcblxuICBcbn1cblxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoZG9uZTogKCkgPT4gdm9pZCkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybSgnQXJlIHlvdSBzdXJlIHRvIGNsb3NlIHRoaXMgZGlhbG9nPycpXG4gICAgLnRoZW4oKCkgPT4ge1xuICAgICAgZG9uZSgpXG4gICAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgICAgLy8gY2F0Y2ggZXJyb3JcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmRpYWxvZy1mb290ZXIgYnV0dG9uOmZpcnN0LWNoaWxkIHtcbiAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击按钮打开dialog
2. 点击dialog中的按钮
3. 等待1秒，弹出框出现，此时无法关闭弹出框

### What is Expected?

应该能够正确的关闭ElMessageBox

### What is actually happening?

无法点击到ElMessageBox

### Additional comments

这个应该是 #9630 造成的，目前可以通过增加下面的样式表应对这个bug

```
.el-loading-parent--relative {
    position: relative !important;
    pointer-events: all !important;
    user-select: all !important;
}
```

**Comment by holazz** [comment]
我觉得这不是 bug，而是使用上的问题。这个 demo 可以简化一下 [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHYtbG9hZGluZy5mdWxsc2NyZWVuPVwiaXNMb2FkaW5nXCIgQGNsaWNrPVwic2hvd0xvYWRpbmdcIlxuICAgID5CdXR0b248L2VsLWJ1dHRvblxuICA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpc0xvYWRpbmcgPSByZWYoZmFsc2UpXG5cbmNvbnN0IHNob3dMb2FkaW5nID0gKCkgPT4ge1xuICBpc0xvYWRpbmcudmFsdWUgPSB0cnVlXG4gIHdpbmRvdy5zZXRUaW1lb3V0KGFzeW5jICgpID0+IHtcbiAgICBhd2FpdCBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4ge30pXG4gICAgaXNMb2FkaW5nLnZhbHVlID0gZmFsc2VcbiAgfSwgNTAwKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)，由于 loading 一直没有关闭，所以不能进行任何操作。

**Comment by languanghao** [comment]
@holazz 一直以来这种做法都是没问题的，自从那个PR后就不支持了。loading就是一个遮罩层，对于后面出现的ElMessageBox，这种也自带一个遮罩层的，是不是应该默认在之前遮罩层之上

**Comment by ljf1834** [comment]
我觉得默认loading期间是不可以做任何操作的，尝试先关闭loading再触发MessageBox

**Comment by languanghao** [comment]
@ljf1834 element允许全局调用loading和ElMessageBox，因此有一种情况就是，loading是当前组件调起的，而ElMessageBox是全局调用的。

举例来说，对于ajax请求，我们会在axios上注册一个统一的错误处理拦截器，出现错误后，调用ElMessageBox进行错误提示。而发起ajax请求的组件在发起的时候，调用了loading进行加载提示。这个时候出错的话，ElMessageBox会先被调用，点击确定后，才会回到组件内的代码，关闭loading
