### ISSUE TITLE
[Component] [tree] tree 自定义节点 Using scoped slot，节点宽度未撑满导致效果和Using render-content不同

### ISSUE THREAD

**Issue by DoveAz** [element-plus/element-plus#10128]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Chrome/106.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E5%86%85%E5%AE%B9)

### Steps to reproduce

打开官方文档就能看到

### What is Expected?

两种自定义节点 实现同样的效果

### What is actually happening?

效果不同

### Additional comments

_(empty)_

**Comment by Little-Frog-233** [comment]
Using scoped slot要把.el-tree-node__label的width设置为100%才能和Using render-content效果一致

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/element-plus/element-plus/commit/fd711d5c0f953417e66de5d6c513aa1ab859bb12)
