### ISSUE TITLE
The loading component will mask the border of the table

### ISSUE THREAD

**Issue by garrettzxd** [element-plus/element-plus#1013]
`<el-tabel v-loading="false" border></el-table>`

在table存在border的情况下使用loading

table border-left border-top会被遮盖起来

受loading css影响
`.el-table--border.el-loading-parent--relative{
  border-color: transparent;
}`

注释该css工作正常

**Comment by justwiner** [comment]
Can you provide a screenshot or demo? @garrettzxd

**Comment by garrettzxd** [comment]
> Can you provide a screenshot or demo? @garrettzxd


![image](https://user-images.githubusercontent.com/13514116/102466967-af8f4a00-408a-11eb-92ac-92a44f535f1f.png)

![image](https://user-images.githubusercontent.com/13514116/102466899-97b7c600-408a-11eb-8fea-9f0621949126.png)
