### ISSUE TITLE
[Component] [button, button-group] Button在disabled的状态下，点击会有事件冒泡，并且使用vue事件修饰符无效

### ISSUE THREAD

**Issue by xiziliang** [element-plus/element-plus#10149]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.18`
- Browser / OS: `macOS 12.3`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-button-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2IEBjbGljaz1cIm9uQ2xpY2tcIj5cbiAgICAgIDxlbC1idXR0b24gOmljb249XCJTZWFyY2hcIiBjaXJjbGUgZGlzYWJsZWQgQGNsaWNrLnN0b3Auc2VsZi8+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgOmljb249XCJFZGl0XCIgY2lyY2xlIGRpc2FibGVkIEBjbGljay5zdG9wLz5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInN1Y2Nlc3NcIiA6aWNvbj1cIkNoZWNrXCIgY2lyY2xlIGRpc2FibGVkLz5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiA6aWNvbj1cIk1lc3NhZ2VcIiBjaXJjbGUgZGlzYWJsZWQvPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwid2FybmluZ1wiIDppY29uPVwiU3RhclwiIGNpcmNsZSBkaXNhYmxlZC8+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiA6aWNvbj1cIkRlbGV0ZVwiIGNpcmNsZSBkaXNhYmxlZC8+XG4gICAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBkaXNhYmxlZCBAY2xpY2suc3RvcD7mtYvor5UxPC9lbC1idXR0b24+XG4gICAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBAY2xpY2suc3RvcD7mtYvor5UyPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXHQgPGRpdj5cbiAgIHt7IGNvdW50IH19XG4gIDwvZGl2PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgQ2hlY2ssXG4gIERlbGV0ZSxcbiAgRWRpdCxcbiAgTWVzc2FnZSxcbiAgU2VhcmNoLFxuICBTdGFyLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuICBcbmNvbnN0IGNvdW50ID0gcmVmKDApXG4gIGZ1bmN0aW9uIG9uQ2xpY2soKSB7XG4gICAgY291bnQudmFsdWUrK1xuICB9XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

参考链接

### What is Expected?

希望能阻止事件冒泡

### What is actually happening?

发生事件冒泡

### Additional comments

_(empty)_

**Comment by holazz** [comment]
这应该不算是bug，和原生 button 表现一致。

**Comment by xiziliang** [comment]
没有呀，我在playground新添加了原生的button，表现是正常的。[新链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2IEBjbGljaz1cIm9uQ2xpY2tcIj5cbiAgICAgIDxlbC1idXR0b24gOmljb249XCJTZWFyY2hcIiBjaXJjbGUgZGlzYWJsZWQgQGNsaWNrLnN0b3Auc2VsZi8+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgOmljb249XCJFZGl0XCIgY2lyY2xlIGRpc2FibGVkIEBjbGljay5zdG9wLz5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInN1Y2Nlc3NcIiA6aWNvbj1cIkNoZWNrXCIgY2lyY2xlIGRpc2FibGVkLz5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiA6aWNvbj1cIk1lc3NhZ2VcIiBjaXJjbGUgZGlzYWJsZWQvPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwid2FybmluZ1wiIDppY29uPVwiU3RhclwiIGNpcmNsZSBkaXNhYmxlZC8+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiA6aWNvbj1cIkRlbGV0ZVwiIGNpcmNsZSBkaXNhYmxlZC8+XG4gICAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBkaXNhYmxlZCBAY2xpY2suc3RvcD7mtYvor5UxPC9lbC1idXR0b24+XG4gICAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBAY2xpY2suc3RvcD7mtYvor5UyPC9lbC1idXR0b24+XG4gICAgXHQ8YnV0dG9uIGRpc2FibGVkPua1i+ivlTM8L2J1dHRvbj5cbiAgICBcdDxidXR0b24+5rWL6K+VNDwvYnV0dG9uPlxuICA8L2Rpdj5cblx0IDxkaXY+XG4gICB7eyBjb3VudCB9fVxuICA8L2Rpdj5cblxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7XG4gIENoZWNrLFxuICBEZWxldGUsXG4gIEVkaXQsXG4gIE1lc3NhZ2UsXG4gIFNlYXJjaCxcbiAgU3Rhcixcbn0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcbiAgXG5jb25zdCBjb3VudCA9IHJlZigwKVxuICBmdW5jdGlvbiBvbkNsaWNrKCkge1xuICAgIGNvdW50LnZhbHVlKytcbiAgfVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by btea** [comment]
请参考[链接](https://github.com/whatwg/html/issues/5886)

**Comment by xiziliang** [comment]
多谢，已经了解了👏
