### ISSUE TITLE
[Bug Report] Upload - file-list attribute empty in >2.2.9

### ISSUE THREAD

**Issue by JackPGreen** [element-plus/element-plus#10142]
### Element Plus version
2.2.18

### OS/Browsers version
Windows / Chrome

### Vue version
3.2.41

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-frmljg?file=/src/App.vue

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIDpodHRwLXJlcXVlc3Q9XCJkb1VwbG9hZFwiXG4gID5cbiAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190ZXh0XCI RHJvcCBmaWxlIGhlcmU8L2Rpdj5cbiAgPC9lbC11cGxvYWQ XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuIFxuY29uc3QgZmlsZUxpc3QgPSByZWYoW10pXG5cbmFzeW5jIGZ1bmN0aW9uIGRvVXBsb2FkKCkge1xuICBjb25zb2xlLmxvZyhcImRvVXBsb2FkOiBcIiArIGZpbGVMaXN0LnZhbHVlKTtcbn1cblxuPC9zY3JpcHQ XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

For some reason the console output doesn't work on codesandbox, but does on Element Plus playground.

```
<template>
  <el-upload
    action="https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15"
    :file-list="fileList"
    :http-request="doUpload"
  >
    <div class="el-upload__text">Drop file here</div>
  </el-upload>
</template>

<script setup lang="ts">
import { ref } from 'vue'
 
const fileList = ref([])

async function doUpload() {
  console.log("doUpload: " + fileList.value);
}

</script>
```

### Steps to reproduce
Load a file,
Look in the console for the "doUpload: " message,
This prints the contents of "fileList" - which is empty.

### What is Expected?
In Element Plus <=2.2.9, fileList is populated and it prints data

### What is actually happening?
In Element Plus >2.2.9, fileList is empty and so it prints an empty array.

**Comment by sxzz** [comment]
`fileList` is uploaded files. For files that have not been uploaded yet, it will not add to `fileList`.

Please try to get file object from params.
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIDpodHRwLXJlcXVlc3Q9XCJkb1VwbG9hZFwiXG4gID5cbiAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190ZXh0XCI+RHJvcCBmaWxlIGhlcmU8L2Rpdj5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuIFxuY29uc3QgZmlsZUxpc3QgPSByZWYoW10pXG5cbmFzeW5jIGZ1bmN0aW9uIGRvVXBsb2FkKG9wdGlvbnMpIHtcbiAgY29uc29sZS5sb2coXCJkb1VwbG9hZDogXCIsIG9wdGlvbnMuZmlsZSk7XG59XG5cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by sxzz** [comment]
I think it's caused by PR #8877

**Comment by chenxch** [comment]
> It breaks on v2.2.10, I think it's caused by PR #8877
> 
> /cc @chenxch @Simon-He95

Received, I will assist in the investigation.

**Comment by chenxch** [comment]
It should be noted the difference between `:file-list` and `v-model:file-list`.

**Comment by chenxch** [comment]
Please use `v-model:file-list`.

**Comment by JackPGreen** [comment]
> Please use `v-model:file-list`.

Do you have an example, please?

**Comment by chenxch** [comment]
Just edit `:file-list` to `v-model:file-list`.

**Comment by JackPGreen** [comment]
> Just edit `:file-list` to `v-model:file-list`.

Thanks, that's worked for me :)
