### ISSUE TITLE
[Component] [popover] el-popover 组件、 effect="dark"属性，在自动引入的情况下样式异常（Style exception in case of automatic import）

### ISSUE THREAD

**Issue by ZHUYUANWEI** [element-plus/element-plus#10141]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Windows10    Chrome/107.0.5304.10`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPCEtLSDoh6rliqjlr7zlhaXvvIxlZmZlY3Q9XCJkYXJrXCIg6IOM5pmv5qC35byP5Lya5Y+R55Sf5byC5bi477yM546w5Zyo5piv5YWo5bGA5byV5YWl5LiN5a2Y5Zyo5byC5bi4IC0tPlxuICA8ZWwtcG9wb3ZlclxuICAgIGVmZmVjdD1cImRhcmtcIlxuICAgIHRpdGxlPVwiVGl0bGVcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、[自动导入](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)组件
2、vue文件中使用`el-popover`组件；
3、组件添加属性：effect="dark"
```vue
<template>
  <el-popover
    effect="dark"
    title="Title"
    content="this is content, this is content, this is content"
  >
    <template #reference>
      <el-button>Hover to activate</el-button>
    </template>
  </el-popover>
</template>
```

### What is Expected?

应该是箭头、内容背景应该都是黑色的

### What is actually happening?

现在箭头是黑色的，但是内容的背景是白色的

### Additional comments

1、经过尝试应该是因为自动导入引起的问题，引入如果单独引入组件样式、或者全局引入样式，显示正常。
2、应该是`自动导入`导致下图中的两个`class`顺序错误，导致样式异常;

![image](https://user-images.githubusercontent.com/26238890/196391980-148bb843-3f24-47de-9fb5-56acc81cea47.png)

**Comment by holazz** [comment]
希望能提供一个可复现的demo，可以是 git 仓库地址。

**Comment by ZHUYUANWEI** [comment]
> 希望能提供一个可复现的demo，可以是 git 仓库地址。

[git 仓库地址](https://github.com/ZHUYUANWEI/1019-0940)
1、`App.vue` 文件中的 `el-tooltip` 组件，注释与放开会影响 `el-popover effect="dark"` 样式；
2、当 `el-tooltip` 组件存在时，注释与放开 `vite.config.ts` 文件中的 `optimizeDeps` 属性会影响el-popover样式；
