### ISSUE TITLE
[Component] [upload] 上传Upload组件清除后并没有触发v-model的变化

### ISSUE THREAD

**Issue by HwuuF7** [element-plus/element-plus#10159]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome/105.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCBUZXN0IGZyb20gJy4vQ29tcC52dWUnO1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHBhcmVudEZpbGVzID0gcmVmKFtdKVxuXG53YXRjaChwYXJlbnRGaWxlcywgKG5WLCBvVikgPT4ge1xuICBjb25zb2xlLmxvZygn54i257uE5Lu255uR5ZCs5YC8LS0nLCBuVilcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICBcbiAgPFRlc3Qgdi1tb2RlbD1cInBhcmVudEZpbGVzXCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG5cdDxkaXY+XG4gICAgPGVsLXVwbG9hZFxuICAgICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgICBjbGFzcz1cInVwbG9hZC1kZW1vXCJcbiAgICAgIGFjdGlvbj1cImh0dHBzOi8vcnVuLm1vY2t5LmlvL3YzLzlkMDU5YmY5LTQ2NjAtNDVmMi05MjVkLWNlODBhZDZjNGQxNVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgOm9uLXJlbW92ZT1cImhhbmRsZVJlbW92ZVwiXG4gICAgICA6bGltaXQ9XCIzXCJcbiAgICA+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+Q2xpY2sgdG8gdXBsb2FkPC9lbC1idXR0b24+XG4gICAgICA8dGVtcGxhdGUgI3RpcD5cbiAgICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwS0IuXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXVwbG9hZD5cbiAgPC9kaXY+XG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5cdGV4cG9ydCBkZWZhdWx0IHtcbiAgICBpbmhlcml0QXR0cnM6IGZhbHNlLFxuICB9XG48L3NjcmlwdD5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIGNvbXB1dGVkLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSc7XG4gIFxuY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wcyh7XG4gIG1vZGVsVmFsdWU6IHtcbiAgICB0eXBlOiBBcnJheSxcbiAgICBkZWZhdWx0OiAoKSA9PiAoW10pXG4gIH1cbn0pXG5jb25zdCBlbWl0cyA9IGRlZmluZUVtaXRzKFsndXBkYXRlOm1vZGVsVmFsdWUnXSlcblxuY29uc3QgZmlsZUxpc3QgPSBjb21wdXRlZCh7XG4gIGdldCgpIHtcbiAgICByZXR1cm4gcHJvcHMubW9kZWxWYWx1ZVxuICB9LFxuICBzZXQobkYpIHtcbiAgXHRjb25zb2xlLmxvZygn6YeN5paw6K6+572u5YC8LS0nLCBuRilcbiAgICBlbWl0cygndXBkYXRlOm1vZGVsVmFsdWUnLCBuRilcblx0fVxufSlcblxuY29uc3QgaGFuZGxlUmVtb3ZlID0gKGZpbGUsIGZpbGVzKSA9PiB7XG4gIGNvbnNvbGUubG9nKCfliKDpmaTmlofku7YtLS0nLCBmaWxlLCBmaWxlcylcbiAgbmV4dFRpY2soKCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKCduZXh0VGlja+WQjueahOWAvC0tJywgZmlsZUxpc3QudmFsdWUpXG4gIH0pXG59XG48L3NjcmlwdD4iLCJfbyI6e319)

### Steps to reproduce

上传文件后，v-model的绑定值能实时监听到，但是点击组件内部的清除[X]按钮后，v-model却不能监听到

### What is Expected?

v-model绑定值能够监听到

### What is actually happening?

v-model绑定值丢失了监听

### Additional comments

_(empty)_

![1666279701524](https://user-images.githubusercontent.com/62701603/196992918-64d86733-46b6-4e70-928b-807c8cd9013e.jpg)

**Comment by Simon-He95** [comment]
Hi, @HwuuF7 
I can't reproduce this error. Maybe having been fixed. pls check it

**Comment by HwuuF7** [comment]
@Simon-He95 Do you have a try what I provide the example above? I try it again in my PC still not work expectedly. Or do you mean you fix it in next version?

**Comment by HeftyKoo** [comment]
Duplicate with #10295
