### ISSUE TITLE
[Component] [dialog, input] The input box component at the same level cannot obtain focus while the dialog is not closed -- 对话框未关闭时，同层输入框无法获取焦点

### ISSUE THREAD

**Issue by youcannot** [element-plus/element-plus#10154]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.18`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxEaWFsb2cgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKHRydWUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgYXBwZW5kLXRvLWJvZHk+XG4gICAgZGlhbG9n5by556qX5L2/55SoVGlueU1DReWvjOaWh+acrOe8lui+keWZqCzlvLnmoYbkuK3nmoRpbnB1dOaXoOazleiBmueEplxuICA8L2VsLWRpYWxvZz5cbiAgPGRpdiBjbGFzcz1cInBvcFwiPlxuICAgIDxpbnB1dCB0eXBlPVwidGV4dFwiIGNsYXNzPVwiaW5wXCIgcGxhY2Vob2xkZXI9XCLov5nph4zml6Dms5XogZrnhKZcIi8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAgLnBvcHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7IFxuICAgIHotaW5kZXg6IDMwMDA7XG4gIH1cbiAgLmlucHtcbiAgICBib3JkZXI6c29saWQgMXB4ICMzMzM7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、dialog box is not closed
2、same layer display opens the input box
3、input box cannot get focus

### What is Expected?

input box can get focus

### What is actually happening?

input box cannot get focus，can only put the input box inside the dialog box（只能把输入框放到对话框内部）

### Additional comments

Dialog boxes do not need to lock focus inside them ? or provides a props control

**Comment by iDestin** [comment]
我觉得你的写法不太好，可以放在对话框内部通过定位来实现你的需求

**Comment by chenxch** [comment]
It is convenient to tell what kind of scenarios have such needs, and I want to know more about them.

**Comment by youcannot** [comment]
> 我觉得你的写法不太好，可以放在对话框内部通过定位来实现你的需求

写在里面能解决，但是有时候有这种需求，不关闭弹窗，再打开一个全屏的页面，这时候几乎就会采用v-if再渲染一个界面出来，那这个组件为什么又必须放在dialog里面呢？所以我觉得官方还是可以看下种需求
