### ISSUE TITLE
[Component] [table-column] form表单点击下拉框的label，触发了打开，再次点击却不能收起，点击时候可以聚焦，但不希望打开，参考ant框架

### ISSUE THREAD

**Issue by fenghua123** [element-plus/element-plus#10169]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.16`
- Browser / OS: `99.0.4844.51`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJtdWx0aXBsZVRhYmxlUmVmXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgQHNlbGVjdGlvbi1jaGFuZ2U9XCJoYW5kbGVTZWxlY3Rpb25DaGFuZ2VcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiBzaG93LW92ZXJmbG93LXRvb2x0aXAgLz5cbiAgPC9lbC10YWJsZT5cbiAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDIwcHhcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInRvZ2dsZVNlbGVjdGlvbihbdGFibGVEYXRhWzFdLCB0YWJsZURhdGFbMl1dKVwiXG4gICAgICA+VG9nZ2xlIHNlbGVjdGlvbiBzdGF0dXMgb2Ygc2Vjb25kIGFuZCB0aGlyZCByb3dzPC9lbC1idXR0b25cbiAgICA+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0b2dnbGVTZWxlY3Rpb24oKVwiPkNsZWFyIHNlbGVjdGlvbjwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFRhYmxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYWRkcmVzczogc3RyaW5nXG59XG5cbmNvbnN0IG11bHRpcGxlVGFibGVSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbFRhYmxlPj4oKVxuY29uc3QgbXVsdGlwbGVTZWxlY3Rpb24gPSByZWY8VXNlcltdPihbXSlcbmNvbnN0IHRvZ2dsZVNlbGVjdGlvbiA9IChyb3dzPzogVXNlcltdKSA9PiB7XG4gIGlmIChyb3dzKSB7XG4gICAgcm93cy5mb3JFYWNoKChyb3cpID0+IHtcbiAgICAgIC8vIFRPRE86IGltcHJvdmVtZW50IHR5cGluZyB3aGVuIHJlZmFjdG9yIHRhYmxlXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50XG4gICAgICAvLyBAdHMtZXhwZWN0LWVycm9yXG4gICAgICBtdWx0aXBsZVRhYmxlUmVmLnZhbHVlIS50b2dnbGVSb3dTZWxlY3Rpb24ocm93LCB1bmRlZmluZWQpXG4gICAgfSlcbiAgfSBlbHNlIHtcbiAgICBtdWx0aXBsZVRhYmxlUmVmLnZhbHVlIS5jbGVhclNlbGVjdGlvbigpXG4gIH1cbn1cbmNvbnN0IGhhbmRsZVNlbGVjdGlvbkNoYW5nZSA9ICh2YWw6IFVzZXJbXSkgPT4ge1xuICBtdWx0aXBsZVNlbGVjdGlvbi52YWx1ZSA9IHZhbFxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA4JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA3JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIn0=)

### Steps to reproduce

树状表格带复选框，翻页记忆功能，来回翻页后，树状子集已勾选，打印勾选子集有，但是复选框没有勾上（即状态错误）

### What is Expected?

勾选数组有的，复选框状态希望正确

### What is actually happening?

翻页回来，子集是已勾选，但是复选框状态是未勾选

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
请修改正确标题和提供repo后重新打开改issue~
