### ISSUE TITLE
[Component] [cascader] use component to render cascader，the label disappears

### ISSUE THREAD

**Issue by yangliguo7** [element-plus/element-plus#10167]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjb21wID0ge1xuICBuYW1lOlwiZWwtY2FzY2FkZXJcIixcbiAgb3B0aW9uczp7XG4gICAgb3B0aW9uczpbe1xuICAgICAgdmFsdWU6ICdndWlkZScsXG4gICAgXHRsYWJlbDogJ0d1aWRlJyxcbiAgICAgIGNoaWxkcmVuOltcbiAgICAgICAge1xuICAgICAgICAgIHZhbHVlOiAnMScsXG4gICAgICAgICAgbGFiZWw6ICcxJyxcbiAgICAgICAgfVxuICAgICAgXVxuICAgIH1dXG4gIH1cbn1cbiAgXG4gIFxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGRpdj5cbiAgICA8Y29tcG9uZW50IDppcz1cImNvbXAubmFtZVwiIHYtYmluZD1cImNvbXAub3B0aW9uc1wiLz5cbiAgPC9kaXY+XG4gIDxoMT5cbiAgICBzcGxpdCBsaW5lIEUge3tFcFZlcnNpb259fSAgViB7e3Z1ZVZlcnNpb259fVxuICA8L2gxPlxuIDxkaXY+XG4gICA8Y29tcG9uZW50IDppcz1cImNvbXAubmFtZVwiIHYtYmluZD1cImNvbXAub3B0aW9uc1wiPlxuICAgXHQgPHRlbXBsYXRlIHYtaWY9XCJjb21wLm5hbWUgPT09ICdlbC1zZWxlY3QnXCI+XG4gICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwic2VsZWN0IGluIGNvbXAuc2VsZWN0T3B0aW9uXCIgOmtleT1cInNlbGVjdC52YWx1ZVwiIHYtYmluZD1cInNlbGVjdFwiLz5cbiAgICA8L3RlbXBsYXRlPlxuICAgPC9jb21wb25lbnQ+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

click cascader

### What is Expected?

Show the correct components

### What is actually happening?

the label disappears

### Additional comments

 we use `component` to repackage the UI library.

**Comment by init-qy** [comment]
I add the `#default` and it works.
`<template v-if="comp.name === 'el-select'" #default>`

**Comment by yangliguo7** [comment]
> I add the `#default` and it works. `<template v-if="comp.name === 'el-select'" #default>`

thank you for u help

**Comment by yangliguo7** [comment]
> I add the `#default` and it works. `<template v-if="comp.name === 'el-select'" #default>`

Thank you for your help
