### ISSUE TITLE
[Component] [select] [Component] [select] Select 为多选并且第一项文字过长时布局问题 

### ISSUE THREAD

**Issue by Wulakaka** [element-plus/element-plus#10179]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.19`
- Browser / OS: `Edg/106.0.1370.47`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoW1xuICAnMTAwMDAwNTYwMDA3cVAxeVY3azAnLFxuICAnMTAwMDAwNTYwMDA3MU45VGxHZHgnLFxuICAnMTAwMDAwNTYwMDA3NjY3S3FNd2QnLFxuICAnMTAwMDAwNTYwMDA3cTVBSzJhckcnLFxuICAnMTAwMDAwNTYwMDA3Rzg0M1NXTnEnLFxuICAnMTAwMDAwNTYwMDA3cTVBSzJhckcnLFxuICAnMTAwMDAwNTYwMDA3RmtPMDI0MUcnLFxuICAnMTAwMDAwNTYwMDA3dXU3ME8wMDYnLFxuICAnMTAwMDAwNTYwMDA3THRvZVkyd2gnLFxuICAnMTAwMDAwNTYwMDA3NnNOOVhzTDAnLFxuICAnMTAwMDAwNTYwMDA3WW9FQ2lGMTAnLFxuXSlcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIGVwaWRlbWljRGV2aWNlSWQ6ICcxMDAwMDA1NjAwMDdxUDF5VjdrMCcsXG4gICAgZXBpZGVtaWNEZXZpY2VJbmZvSWQ6ICcxNTU0Mzg5NDU2MjI1NTI1NzYxJyxcbiAgICBlcGlkZW1pY0RldmljZU5hbWU6ICfmnKzlnLDmtYvor5Xorr7lpIc3NzcnLFxuICB9LFxuICB7XG4gICAgZXBpZGVtaWNEZXZpY2VJZDogJzEwMDAwMDU2MDAwNzFOOVRsR2R4JyxcbiAgICBlcGlkZW1pY0RldmljZUluZm9JZDogJzE1NTQ3NzUwMjE5NzQ0MTMzMTMnLFxuICAgIGVwaWRlbWljRGV2aWNlTmFtZTogJ+acrOWcsOa1i+ivleiuvuWkhzk5OScsXG4gIH0sXG4gIHtcbiAgICBlcGlkZW1pY0RldmljZUlkOiAnMTAwMDAwNTYwMDA3NjY3S3FNd2QnLFxuICAgIGVwaWRlbWljRGV2aWNlSW5mb0lkOiAnMTU1NTQ1MDA4NTgzMzEzODE3NycsXG4gICAgZXBpZGVtaWNEZXZpY2VOYW1lOiAn5rWL6K+V6K6+5aSHMDAxJyxcbiAgfSxcbiAge1xuICAgIGVwaWRlbWljRGV2aWNlSWQ6ICcxMDAwMDA1NjAwMDdHODQzU1dOcScsXG4gICAgZXBpZGVtaWNEZXZpY2VJbmZvSWQ6ICcxNTU5NDI5MzYyNDgwMDEzMzEzJyxcbiAgICBlcGlkZW1pY0RldmljZU5hbWU6ICfmtqrpmbXovablnLrmtYvor5Xorr7lpIcnLFxuICB9LFxuICB7XG4gICAgZXBpZGVtaWNEZXZpY2VJZDogJzEwMDAwMDU2MDAwN3E1QUsyYXJHJyxcbiAgICBlcGlkZW1pY0RldmljZUluZm9JZDogJzE1NzIwNDg5NjMwMjU5ODU1MzgnLFxuICAgIGVwaWRlbWljRGV2aWNlTmFtZTogJ+a1iycsXG4gIH0sXG4gIHtcbiAgICBlcGlkZW1pY0RldmljZUlkOiAnMTAwMDAwNTYwMDA3RmtPMDI0MUcnLFxuICAgIGVwaWRlbWljRGV2aWNlSW5mb0lkOiAnMTU3MjA1MDA2OTgyMzExOTM2MicsXG4gICAgZXBpZGVtaWNEZXZpY2VOYW1lOiAn5LuN6Zu55qaUJyxcbiAgfSxcbiAge1xuICAgIGVwaWRlbWljRGV2aWNlSWQ6ICcxMDAwMDA1NjAwMDd1dTcwTzAwNicsXG4gICAgZXBpZGVtaWNEZXZpY2VJbmZvSWQ6ICcxNTcyNTI1Mjg3OTk3OTIzMzMwJyxcbiAgICBlcGlkZW1pY0RldmljZU5hbWU6ICfotJ7niLnmgbAnLFxuICB9LFxuICB7XG4gICAgZXBpZGVtaWNEZXZpY2VJZDogJzEwMDAwMDU2MDAwN0x0b2VZMndoJyxcbiAgICBlcGlkZW1pY0RldmljZUluZm9JZDogJzE1NzI1MjYxODYxNTc3OTMyODEnLFxuICAgIGVwaWRlbWljRGV2aWNlTmFtZTogJ+a1hembtuaDsCcsXG4gIH0sXG4gIHtcbiAgICBlcGlkZW1pY0RldmljZUlkOiAnMTAwMDAwNTYwMDA3NnNOOVhzTDAnLFxuICAgIGVwaWRlbWljRGV2aWNlSW5mb0lkOiAnMTU3MjUyNjM1NTc0NjA4NjkxMycsXG4gICAgZXBpZGVtaWNEZXZpY2VOYW1lOiAn56OK6buU5ruhJyxcbiAgfSxcbiAge1xuICAgIGVwaWRlbWljRGV2aWNlSWQ6ICcxMDAwMDA1NjAwMDdZb0VDaUYxMCcsXG4gICAgZXBpZGVtaWNEZXZpY2VJbmZvSWQ6ICcxNTcyNTI2OTgzNjUwMTcyOTI5JyxcbiAgICBlcGlkZW1pY0RldmljZU5hbWU6ICfmpoLokrLorrInLFxuICB9LFxuICB7XG4gICAgZXBpZGVtaWNEZXZpY2VJZDogJzEwMDAwMDU2MDAwNzNkbEFDSVBuJyxcbiAgICBlcGlkZW1pY0RldmljZUluZm9JZDogJzE1NzI1Mjg4NjI1ODUxMTg3MjEnLFxuICAgIGVwaWRlbWljRGV2aWNlTmFtZTogJ+S6p+WmkuWujCcsXG4gIH0sXG4gIHtcbiAgICBlcGlkZW1pY0RldmljZUlkOiAnMTAwMDAwNTYwMDA3NTAyOTBHMk8nLFxuICAgIGVwaWRlbWljRGV2aWNlSW5mb0lkOiAnMTU3MjUyOTA0NjA0Mzk3NTY4MScsXG4gICAgZXBpZGVtaWNEZXZpY2VOYW1lOiAn6YWj5Zej5LiDJyxcbiAgfSxcbiAge1xuICAgIGVwaWRlbWljRGV2aWNlSWQ6ICcxMDAwMDA1NjAwMDd1bzhCSjh2RicsXG4gICAgZXBpZGVtaWNEZXZpY2VJbmZvSWQ6ICcxNTcyNTI5MjQwNDM3MzgzMTY5JyxcbiAgICBlcGlkZW1pY0RldmljZU5hbWU6ICfmlLvmr4HnorAnLFxuICB9LFxuICB7XG4gICAgZXBpZGVtaWNEZXZpY2VJZDogJzEwMDAwMDU2MDAwN3g0TzNhOGwwJyxcbiAgICBlcGlkZW1pY0RldmljZUluZm9JZDogJzE1NzI1Mjk0Nzg2NTcwNzMxNTMnLFxuICAgIGVwaWRlbWljRGV2aWNlTmFtZTpcbiAgICAgICfnv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu7/nv6DonJXnu78nLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgbXVsdGlwbGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgY29sbGFwc2UtdGFncy10b29sdGlwXG4gICAgcGxhY2Vob2xkZXI9XCLor7fpgInmi6npmLLnlqvorr7lpIdcIlxuICAgIGNsZWFyYWJsZVxuICA+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0uZXBpZGVtaWNEZXZpY2VJZFwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmVwaWRlbWljRGV2aWNlTmFtZVwiXG4gICAgICA6dmFsdWU9XCJpdGVtLmVwaWRlbWljRGV2aWNlSWRcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup>
const options = ref([
{
			"epidemicDeviceId":"100000560007qP1yV7k0",
			"epidemicDeviceInfoId":"1554389456225525761",
			"epidemicDeviceName":"本地测试设备777"
		},
		{
			"epidemicDeviceId":"1000005600071N9TlGdx",
			"epidemicDeviceInfoId":"1554775021974413313",
			"epidemicDeviceName":"本地测试设备999"
		},
		{
			"epidemicDeviceId":"100000560007667KqMwd",
			"epidemicDeviceInfoId":"1555450085833138177",
			"epidemicDeviceName":"测试设备001"
		},
		{
			"epidemicDeviceId":"100000560007G843SWNq",
			"epidemicDeviceInfoId":"1559429362480013313",
			"epidemicDeviceName":"涪陵车场测试设备"
		},
		{
			"epidemicDeviceId":"100000560007q5AK2arG",
			"epidemicDeviceInfoId":"1572048963025985538",
			"epidemicDeviceName":"测"
		},
		{
			"epidemicDeviceId":"100000560007FkO0241G",
			"epidemicDeviceInfoId":"1572050069823119362",
			"epidemicDeviceName":"仍雹榔"
		},
		{
			"epidemicDeviceId":"100000560007uu70O006",
			"epidemicDeviceInfoId":"1572525287997923330",
			"epidemicDeviceName":"贞爹恰"
		},
		{
			"epidemicDeviceId":"100000560007LtoeY2wh",
			"epidemicDeviceInfoId":"1572526186157793281",
			"epidemicDeviceName":"浅零惰"
		},
		{
			"epidemicDeviceId":"1000005600076sN9XsL0",
			"epidemicDeviceInfoId":"1572526355746086913",
			"epidemicDeviceName":"磊黔满"
		},
		{
			"epidemicDeviceId":"100000560007YoECiF10",
			"epidemicDeviceInfoId":"1572526983650172929",
			"epidemicDeviceName":"概蒲讲"
		},
		{
			"epidemicDeviceId":"1000005600073dlACIPn",
			"epidemicDeviceInfoId":"1572528862585118721",
			"epidemicDeviceName":"产妒完"
		},
		{
			"epidemicDeviceId":"10000056000750290G2O",
			"epidemicDeviceInfoId":"1572529046043975681",
			"epidemicDeviceName":"酣嗣七"
		},
		{
			"epidemicDeviceId":"100000560007uo8BJ8vF",
			"epidemicDeviceInfoId":"1572529240437383169",
			"epidemicDeviceName":"攻毁碰"
		},
		{
			"epidemicDeviceId":"100000560007x4O3a8l0",
			"epidemicDeviceInfoId":"1572529478657073153",
			"epidemicDeviceName":"翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿翠蜕绿"
		}
])
</script>

<template>
    <el-select
    v-model="value"
    multiple
    collapse-tags
    collapse-tags-tooltip
    placeholder="请选择防疫设备"
    clearable
  >
    <el-option
      v-for="item in options"
      :key="item.epidemicDeviceId"
      :label="item.epidemicDeviceName"
      :value="item.epidemicDeviceId"
    />
  </el-select>
</template>
```

### What is Expected?

第一个已选项文字较长，收起的tag超过10项时，第二个tag不会换行

### What is actually happening?

第一个已选项文字较长，收起的tag超过10项时，第二个tag会换行

### Additional comments

相关issue #9633

**Comment by chenxch** [comment]
可以尝试临时给.el-select-tags-wrapper 加上display:flex

**Comment by Simon-He95** [comment]
> 可以尝试临时给.el-select-tags-wrapper 加上display:flex

Do you think we need to set a maximum width for the popper in select as input?

**Comment by Wulakaka** [comment]
最好是根据后一个tag的宽度，动态计算前一个的宽度

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Simon He ***@***.***>
发送时间: Saturday, October 22, 2022 4:07:14 AM
收件人: element-plus/element-plus ***@***.***>
抄送: weifeng.zhang ***@***.***>; Author ***@***.***>
主题: Re: [element-plus/element-plus] [Component] [select] [Component] [select] Select 为多选并且第一项文字过长时布局问题 (Issue #10179)


可以尝试临时给.el-select-tags-wrapper 加上display:flex

Do you think we need to set a maximum width for the popper in select as input?

―
