### ISSUE TITLE
[Component] [loading] loading组件不能实时刷新，希望加一个实时刷新的功能

### ISSUE THREAD

**Issue by zhangyr123** [element-plus/element-plus#10178]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `chrome `
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBjb21wdXRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKDEpXG5jb25zdCBtZXNzYWdlID0gcmVmKCdtZXNzYWdlJylcblxuc2V0SW50ZXJ2YWwoKCkgPT4ge1xuICBcbiAgbWVzc2FnZS52YWx1ZSA9ICdtZXNzYWdlJyArIE1hdGgucmFuZG9tKClcbn0sIDEwMDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICB7e21lc3NhZ2V9fVxuICA8ZGl2IHYtbG9hZGluZz1cInRydWVcIiBcbiAgICAgICAgZWxlbWVudC1sb2FkaW5nLXN2Zy12aWV3LWJveD1cIjAsIDAsIDcwLCA3MFwiXG4gICAgICAgIDplbGVtZW50LWxvYWRpbmctdGV4dD1cIm1lc3NhZ2VcIj5cbiAgICBsb2FkaW5n5rWL6K+VXG4gIDwvZGl2PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

组件开着的情况下，刷新绑定的svg和text，数据传进去了，组件没有重新加载。

### What is Expected?

组件视图可以实时刷新，传进去的文字和svg都可以实时刷新

### What is actually happening?

组件视图不能实时刷新，必须先关闭再打开才能刷新

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
参考 #9263
可以先搜索一下，可能可以快速解决你的问题哦~

**Comment by zhangyr123** [comment]
使用options的方式可以了，但是设置完svgViewBox和修改了样式之后，text的那个div不显示了

样式代码：
`.image-loading {
    >.el-loading-mask {
      .el-loading-spinner {
        .circular {
          width: 70px !important;
          height: 70px !important;
          animation: none !important;
          -webkit-animation: none !important;
        }
      }
    }
  }`
js部分：
`const imageLoadInfo = computed(() => useToolStore.imageLoadInfo)
    const imageLoading = computed(() => imageLoadInfo.value.barvalue > 0 && imageLoadInfo.value.barvalue < 100)
    const svg = computed(() => `
            <path d="M 35,35 m 0,-31
            a 31,31 0 1 1 0,62
            a 31,31 0 1 1 0,-62" stroke="#ccc" stroke-width="8" fill-opacity="0"></path> 
            <path d="M 35,35 m 0,-31
            a 31,31 0 1 1 0,62
            a 31,31 0 1 1 0,-62" stroke-linecap="round" stroke="#43a0c8" stroke-width="8" fill-opacity="0" style="stroke-dasharray: 194.779px, 194.779px; stroke-dashoffset: ${((100 - imageLoadInfo.value.barvalue) / 100 * 194.779)}px; transition: stroke-dashoffset 1s ease 0s;"></path>
            `)
    const imageLoadingOptions = computed(() => {
      return {visible: imageLoading, text: imageLoadInfo.value.message, spinner: svg, svgViewBox: `0, 0, 70, 70`, background: `rgba(122, 122, 122, 0.1)`}
    })`

**Comment by zhangyr123** [comment]
没事了，我写的有问题
