### ISSUE TITLE
[Component] [table-column] el-table-column 通过 template去插入#header的时候，修改header内容不会触发vite的热更新，需要手动刷新

### ISSUE THREAD

**Issue by cqiang1993** [element-plus/element-plus#10173]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome 106.0.5249.119 / MacOS 12.6`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGU+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIHdpZHRoPVwiMjAwXCI+XG4gICAgXHQ8dGVtcGxhdGUgI2hlYWRlcj5cbiAgICAgIFx0IOWQjeensC9JRFxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwhLS0g6YCa6L+HdGVtcGxhdGXljIXoo7nnmoTlhoXlrrnvvIzlnKh2aXRl5LiL5L+u5pS55LiN5Lya54Ot5pu05paw77yM6ZyA6KaB5omL5Yqo5Yi35paw5omN55Sf5pWILS0+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

使用<el-table-column>里面的<template #header>设置label的时候，并且修改

### What is Expected?

自动更新header内容

### What is actually happening?

没有变化

### Additional comments

需要手动刷新浏览器才行

**Comment by btea** [comment]
似乎是vite的问题 https://github.com/vitejs/vite/issues/10199

**Comment by cqiang1993** [comment]
> 似乎是vite的问题 [vitejs/vite#10199](https://github.com/vitejs/vite/issues/10199)

我试着自己实现的组件用具名插槽就没有问题是为啥？
