### ISSUE TITLE
[Style] [input-number] Input Number 组件，按钮边框显示异常

### ISSUE THREAD

**Issue by F5F5** [element-plus/element-plus#10177]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

MacBook Pro 13 外接1080P显示器上出现的，MBP上是正常的

### What is Expected?

正常显示边框

### What is actually happening?

左右按钮的，上边框丢失
按钮全部在右侧的，上边框丢失，两个按钮中间多了一条白线

![image](https://user-images.githubusercontent.com/15978277/197165533-34fa68a3-84e9-47fd-9c7a-97dcc110d48e.png)
![image](https://user-images.githubusercontent.com/15978277/197165605-af35ddd2-753a-46fa-b7fb-a100a74bd831.png)
![image](https://user-images.githubusercontent.com/15978277/197165658-d6e7548a-204c-4a99-9324-1bb762a387f4.png)

**Comment by jkwroi24io9342fsdjklAdf** [comment]
![image](https://user-images.githubusercontent.com/4435013/197324494-99294c6a-edd9-4b5e-b41d-9d5b28811da9.png)

我的也是显示异常
