### ISSUE TITLE
[Component] [select-v2] SelectV2 组件

### ISSUE THREAD

**Issue by RadiumAg** [element-plus/element-plus#10187]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.19`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4OyBtYXJnaW4tcmlnaHQ6IDE2cHg7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIlxuICAgIGNsZWFyYWJsZVxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZix3YXRjaCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cbmNvbnN0IHZhbHVlMSA9IHJlZigpXG4gICAgXG53YXRjaCh2YWx1ZTEsKHZhbCk9PnsgY29uc29sZS5sb2codmFsKX0pXG4gIFxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICBsYWJlbDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

当在`SelectV2`组件中开启`clearable`后，还没有任何选择， 就会出现`清空`标志

### What is Expected?

当有`内容`时，才会显示`清空`标志，没有`内容`时，显示`下拉`标志

### What is actually happening?

还没有`内容`，就出现`删除`标志，这是很`迷惑`的

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/48897151/197313101-8f25fb5c-2db4-48aa-a6a5-50500ec1790e.png)

**Comment by holazz** [comment]
你这是单选，不应该传递一个空数组作为初始值，而是应该传递 `null` 或 `undefined`

```ts
const value = ref()
```

**Comment by RadiumAg** [comment]
> 你这是单选，不应该传递一个空数组作为初始值，而是应该传递 `null` 或 `undefined`。参考[文档](https://element-plus.org/en-US/component/select-v2.html#clearable-selector)中的用法
> 
> ```ts
> const value = ref()
> ```
好的，确实没有注意到

**Comment by RadiumAg** [comment]
> 你这是单选，不应该传递一个空数组作为初始值，而是应该传递 `null` 或 `undefined`。参考[文档](https://element-plus.org/en-US/component/select-v2.html#clearable-selector)中的用法
> 
> ```ts
> const value = ref()
> ```

我已经改了`例子`，并且发现，选中之后`清空`，返回的时`空字符串`，这时依然会出现没有任何选中但是会出现`清空`的情况,
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4OyBtYXJnaW4tcmlnaHQ6IDE2cHg7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIlxuICAgIGNsZWFyYWJsZVxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZix3YXRjaCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cbmNvbnN0IHZhbHVlMSA9IHJlZigpXG4gICAgXG53YXRjaCh2YWx1ZTEsKHZhbCk9PnsgY29uc29sZS5sb2codmFsKX0pXG4gIFxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICBsYWJlbDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
