### ISSUE TITLE
Custom theme. After modifying the theme color, download the resource index.css  Some styles unrelated to the theme color are different from the default

### ISSUE THREAD

**Issue by sufengyong** [element-plus/element-plus#1018]
修改主题色后 index.css 中 
el-select-dropdown 类中包含 margin: 5px 0

官方文档中 el-select-dropdown 没有 margin: 5px 0；

导致下拉框弹出框三角形位置异常，脱离弹出框

**Comment by zazzaz** [comment]
Any more detail please, like how do you change the css in `index.css`?

**Comment by sufengyong** [comment]
> Any more detail please, like how do you change the css in `index.css`?

I only changed the theme color in your online theme generation tool page. After downloading the resource package, the main.ts file of the project refers to the index.css in the resource, without making any changes to index.css. However, it was found that the triangle position of the EL-select pop-up box was incorrect, and compared with the el-select-Dropdown class of the official document, more margin was found: 5px 0

**Comment by zazzaz** [comment]
I see, the 'online theme generation' tool needs to be updated. 

In the meantime, you can try the other way like update the sass var directly.

**Comment by iamkun** [comment]
fixed in #1861
