### ISSUE TITLE
[Docs] [table-column, pagination] Upgrading to 2.2.17 or later, IDEA will mark a lot of incorrect warnings

### ISSUE THREAD

**Issue by NXY666** [element-plus/element-plus#10192]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLnpLrkvotcIiBtaW4td2lkdGg9XCIxMjBcIiBwcm9wPVwiZXhhbXBsZVwiIHNvcnRhYmxlLz5cbiAgPC9lbC10YWJsZT5cbiAgPGVsLXBhZ2luYXRpb24gY3VycmVudC1wYWdlPVwiMVwiIHBhZ2Utc2l6ZT1cIjFcIiA6cGFnZXItY291bnQ9XCIxMVwiIDp0b3RhbD1cIjk5OVwiIGJhY2tncm91bmRcbiAgICAgICAgICAgICAgICAgbGF5b3V0PVwicHJldiwgcGFnZXIsIG5leHQsIC0+LCBzaXplc1wiIHNtYWxsIHN0eWxlPVwibWFyZ2luOiAxMHB4IGF1dG87XCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Copy the [code](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLnpLrkvotcIiBtaW4td2lkdGg9XCIxMjBcIiBwcm9wPVwiZXhhbXBsZVwiIHNvcnRhYmxlLz5cbiAgPC9lbC10YWJsZT5cbiAgPGVsLXBhZ2luYXRpb24gY3VycmVudC1wYWdlPVwiMVwiIHBhZ2Utc2l6ZT1cIjFcIiA6cGFnZXItY291bnQ9XCIxMVwiIDp0b3RhbD1cIjk5OVwiIGJhY2tncm91bmRcbiAgICAgICAgICAgICAgICAgbGF5b3V0PVwicHJldiwgcGFnZXIsIG5leHQsIC0+LCBzaXplc1wiIHNtYWxsIHN0eWxlPVwibWFyZ2luOiAxMHB4IGF1dG87XCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) to Idea.

### What is Expected?

No warnings. (Here is a screenshot of version 2.2.16)
![image](https://user-images.githubusercontent.com/62371554/197335792-c7110444-3713-4c2d-afeb-a7a740c3f47c.png)

### What is actually happening?

Prompt for many incorrect warnings.
![image](https://user-images.githubusercontent.com/62371554/197335326-98eb1c28-c2ea-47fe-a937-fc1c4441a1dc.png)
![image](https://user-images.githubusercontent.com/62371554/197335284-312bd7af-7890-46f1-83d3-cb4e0702efb2.png)

Not only that, but the updated document does not jump correctly to the document's declaration.
![image](https://user-images.githubusercontent.com/62371554/197335955-e98e8c51-0f61-4551-9df7-08a37763def3.png)

### Additional comments

I have tried every recent release and 2.2.16 was the last one that worked properly.

**Comment by Gaierte** [comment]
Why do you have such a prompt? Do you have some plug-in installed

**Comment by NXY666** [comment]
> Why do you have such a prompt? Do you have some plug-in installed

Non-Bundled Plugins:
    com.intellij.zh (222.202)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    com.github.copilot (1.1.34.2009)
    org.jetbrains.plugins.vue (222.4345.21)
    com.haulmont.jpab (2022.4.4-222)

我不觉得我使用了什么可疑的插件。
I don't think I'm using any suspicious plugins.

**Comment by tolking** [comment]
Maybe the generated `web-types.json` file be wrong. You can try to change all `enum` to `of-match` in the `web-types.json` file, then restart the IDE.

**Comment by NXY666** [comment]
> Maybe the generated `web-types.json` file be wrong. You can try to change all `enum` to `of-match` in the `web-types.json` file, then restart the IDE.

我修改后warning消失了，非常感谢。
I modified it and the warning disappeared, thank you very much.

IDEA仍然无法正确地跳转到文档声明，不过这不是很重要。
IDEA still does not jump to the documentation declaration correctly, but this is not very important.

我认为文档是需要更正的，总不能每个版本更新后都要我自己修改。
I think the documentation needs to be corrected, I can't be required to change it myself after every version update.

有一些比较明显的错误比如`el-table-column`的`fixed`属性，只列举了`true`、`'right'`、`'left'`，实际还可能出现`right`和`left`两个值。
There are some rather obvious errors like the `fixed` attribute of `el-table-column`, which only lists `true`, `'right'` and `'left'`, when in reality there could be two other values `right` and `left`.

**Comment by tolking** [comment]
We will fix this error as soon as possible.

There is a problem with the fixed `Accepted Values` in the document. It should be `left / right`. Maybe there are other similar problems, which need to take some time to deal with

**Comment by Gaierte** [comment]
Where is the web-types.json

**Comment by NXY666** [comment]
> Where is the web-types.json

./node_modules/element-plus/web-types.json

**Comment by NXY666** [comment]
> We will fix this error as soon as possible.
> 
> There is a problem with the fixed `Accepted Values` in the document. It should be `left / right`. Maybe there are other similar problems, which need to take some time to deal with

太好了！非常感谢！

**Comment by NXY666** [comment]
> We will fix this error as soon as possible.
> 
> There is a problem with the fixed `Accepted Values` in the document. It should be `left / right`. Maybe there are other similar problems, which need to take some time to deal with

经过更新后，现在就只剩下分页的layout仍然会报warning了
