### ISSUE TITLE
[Component] [popover, tooltip] el-popover 打开会立马关闭

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#10202]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHYtZm9yPVwiaXRlbSBpbiAzXCIgOmtleT1cIml0ZW1cIiBAY2xpY2s9XCJvbkNsaWNrXCI+XG4gICAgQ2xpY2sgbWVcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLXBvcG92ZXJcbiAgICA6dmlydHVhbC1yZWY9XCJidXR0b25SZWZcIlxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgdGl0bGU9XCJXaXRoIHRpdGxlXCJcbiAgICB2aXJ0dWFsLXRyaWdnZXJpbmdcbiAgPlxuICAgIDxzcGFuPiBTb21lIGNvbnRlbnQgPC9zcGFuPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgYnV0dG9uUmVmID0gcmVmKClcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBvbkNsaWNrID0gKGV2ZW50OiBNb3VzZUV2ZW50KSA9PiB7XG4gIGJ1dHRvblJlZi52YWx1ZSA9IGV2ZW50LmN1cnJlbnRUYXJnZXRcbiAgdmlzaWJsZS52YWx1ZSA9IHRydWVcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

第一次点击按钮会正常打开，第二次点击打开就立马关闭了

### What is Expected?

第二次点击会正常打开

### What is actually happening?

第二次打开会关闭

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
![image](https://user-images.githubusercontent.com/33827314/197457869-8aef97f2-7fb2-4763-beaa-cc13f767b890.png)
看起来是因为这里

**Comment by baiwusanyu-c** [comment]
When `v-model:visible` is in uncontrolled mode, it causes `trigger` to conflict with user control. When the user modifies `visible`, `trigger` will be triggered, resulting in the execution of the `onChange` method, causing an error @chenxch 
[#8762](https://github.com/element-plus/element-plus/pull/8762)

**Comment by baiwusanyu-c** [comment]
Maybe you can use `:visible` to make the component into controlled mode, so that the display control is completely controlled by yourself to temporarily circumvent this bug @gjfei

**Comment by chenxch** [comment]
> When `v-model:visible` is in uncontrolled mode, it causes `trigger` to conflict with user control. When the user modifies `visible`, `trigger` will be triggered, resulting in the execution of the `onChange` method, causing an error @chenxch [#8762](https://github.com/element-plus/element-plus/pull/8762)

Thanks for the positioning, I will look at the reason in detail tonight.

**Comment by Simon-He95** [comment]
#10246 I think this change can Solve problems related to components using teleport

**Comment by acyza** [comment]
可以选择其他的tigger，或者使用stopImmediatePropagation()阻止tigger通过click事件改变visible。[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHYtZm9yPVwiaXRlbSBpbiAzXCIgOmtleT1cIml0ZW1cIiBAY2xpY2s9XCJvbkNsaWNrXCI+XG4gICAgQ2xpY2sgbWVcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLXBvcG92ZXJcbiAgICA6dmlydHVhbC1yZWY9XCJidXR0b25SZWZcIlxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgdGl0bGU9XCJXaXRoIHRpdGxlXCJcbiAgICB2aXJ0dWFsLXRyaWdnZXJpbmdcbiAgPlxuICAgIDxzcGFuPiBTb21lIGNvbnRlbnQgPC9zcGFuPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgYnV0dG9uUmVmID0gcmVmKClcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBvbkNsaWNrID0gKGV2ZW50OiBNb3VzZUV2ZW50KSA9PiB7XG4gIGJ1dHRvblJlZi52YWx1ZSA9IGV2ZW50LmN1cnJlbnRUYXJnZXRcbiAgdmlzaWJsZS52YWx1ZSA9IHRydWVcbiAgZXZlbnQuc3RvcEltbWVkaWF0ZVByb3BhZ2F0aW9uKCk7XG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Simon-He95** [comment]
点击一个按钮到另一个按钮的时候是不是不应该再关闭了,就继续保持开启
