### ISSUE TITLE
[Component] [calendar] Calendar 日历 每周第一天始终是周日，修改语言环境无效

### ISSUE THREAD

**Issue by cjbtd** [element-plus/element-plus#10200]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-calendar`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/9285109a0cc0ea191af7804c0484ae9cf1cf505a/packages/components/calendar/src/use-date-table.ts#L24)

### Steps to reproduce

设置firstDayOfWeek值的代码，是否应该在dayjs().locale(lang.value)这行代码后面？

### What is Expected?

每周第一天是周一

### What is actually happening?

每周第一天是周日

### Additional comments

设置firstDayOfWeek值是否应该在dayjs().locale(lang.value)这行代码后面

**Comment by chenxch** [comment]
这个应该是计算机基础知识的问题了，程序上每周的第一天是默认周日的，如果你有需要设置为星期一可以加一天。至于为什么时候周日你可以查阅相关资料。

**Comment by cjbtd** [comment]
这不是代码BUG吗？我设置语言环境为中文应该默认每周第一天是周一，无需你说的【如果你有需要设置为星期一可以加一天】，日期选择组件显示是正常的，每周第一天是周一

**Comment by cjbtd** [comment]
这不是代码BUG吗？我设置语言环境为中文应该默认每周第一天是周一，无需你说的【如果你有需要设置为星期一可以加一天】，日期选择组件显示是正常的，每周第一天是周一 @chenxch 

> 这个应该是计算机基础知识的问题了，程序上每周的第一天是默认周日的，如果你有需要设置为星期一可以加一天。至于为什么时候周日你可以查阅相关资料。

这不是代码BUG吗？我设置语言环境为中文应该默认每周第一天是周一，无需你说的【如果你有需要设置为星期一可以加一天】，日期选择组件显示是正常的，每周第一天是周一

**Comment by cjbtd** [comment]
> 这个应该是计算机基础知识的问题了，程序上每周的第一天是默认周日的，如果你有需要设置为星期一可以加一天。至于为什么时候周日你可以查阅相关资料。

这不是代码BUG吗？我设置语言环境为中文应该默认每周第一天是周一，无需你说的【如果你有需要设置为星期一可以加一天】，日期选择组件显示是正常的，每周第一天是周一

**Comment by cjbtd** [comment]
@chenxch  这不是代码BUG吗？我设置语言环境为中文应该默认每周第一天是周一，无需你说的【如果你有需要设置为星期一可以加一天】，日期选择组件显示是正常的，每周第一天是周一

**Comment by tolking** [comment]
每周的第一天是周日，即使是设置中文环境。如果需要请自行修改 [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29uZmlnLXByb3ZpZGVyIDpsb2NhbGU9XCJ6aENuXCI+XG4gICAgPGVsLWNhbGVuZGFyIHYtbW9kZWw9XCJ2YWx1ZVwiIC8+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsQ29uZmlnUHJvdmlkZXIsIGRheWpzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcblxuZGF5anMuZW4ud2Vla1N0YXJ0ID0gMVxuY29uc3QgdmFsdWUgPSByZWYobmV3IERhdGUoKSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by cjbtd** [comment]
@tolking 我的项目是多语言切换的，英文每周第一天是周日，中文是周一，请先确认这行代码是否有问题[firstDayOfWeek](https://github.com/element-plus/element-plus/blob/9285109a0cc0ea191af7804c0484ae9cf1cf505a/packages/components/calendar/src/use-date-table.ts#L24)，是否应该在const now = dayjs().locale(lang.value)这行代码下面

**Comment by cjbtd** [comment]
问题能解决，但Bug依旧存在，设置dayjs.en.weekStart只是妥协方法
```
import "element-plus/theme-chalk/display.css";
import "element-plus/theme-chalk/index.css";
import "element-plus/theme-chalk/dark/css-vars.css";

import type { App } from "vue";

import * as ElIcons from "@element-plus/icons-vue";
import ElementPlus, { dayjs } from "element-plus";
import enEle from "element-plus/es/locale/lang/en";
import zhEle from "element-plus/es/locale/lang/zh-cn";

import { isZh } from "~/utils";

// @ts-ignore
dayjs.en.weekStart = isZh() ? 1 : 0;

export default function (app: App) {
  for (const name in ElIcons) {
    app.component(name, (ElIcons as any)[name]);
  }

  app.use(ElementPlus, { locale: isZh() ? zhEle : enEle });
}
```

**Comment by chenxch** [comment]
> @tolking 我的项目是多语言切换的，英文每周第一天是周日，中文是周一，请先确认这行代码是否有问题[firstDayOfWeek](https://github.com/element-plus/element-plus/blob/9285109a0cc0ea191af7804c0484ae9cf1cf505a/packages/components/calendar/src/use-date-table.ts#L24)，是否应该在const now = dayjs().locale(lang.value)这行代码下面

一样的，你也是要去修改weekStart的

**Comment by cjbtd** [comment]
> > @tolking 我的项目是多语言切换的，英文每周第一天是周日，中文是周一，请先确认这行代码是否有问题[firstDayOfWeek](https://github.com/element-plus/element-plus/blob/9285109a0cc0ea191af7804c0484ae9cf1cf505a/packages/components/calendar/src/use-date-table.ts#L24)，是否应该在const now = dayjs().locale(lang.value)这行代码下面
> 
> 一样的，你也是要去修改weekStart的

DatePicker 日期选择器 这个组件是无需修改weekStart的，它跟随locale，[文档](https://element-plus.org/zh-CN/component/calendar.html#%E5%9B%BD%E9%99%85%E5%8C%96)写的也是通过国际化来配置，我理解是无需设置weekStart

**Comment by chenxch** [comment]
导入这个即可
```
import 'dayjs/locale/zh-cn'
```

**Comment by martonx** [comment]
Hi, Could you summarize this thread in English please! I would like to set first day of week. Thank you very much!

**Comment by chenxch** [comment]
> Hi, Could you summarize this thread in English please! I would like to set first day of week. Thank you very much!

Option One:

main.js/ts

```
import 'dayjs/locale/hu'
```


Option Two:

[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29uZmlnLXByb3ZpZGVyIDpsb2NhbGU9XCJ6aENuXCI+XG4gICAgPGVsLWNhbGVuZGFyIHYtbW9kZWw9XCJ2YWx1ZVwiIC8+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsQ29uZmlnUHJvdmlkZXIsIGRheWpzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcblxuZGF5anMuZW4ud2Vla1N0YXJ0ID0gMVxuY29uc3QgdmFsdWUgPSByZWYobmV3IERhdGUoKSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
You can manually set `weekStart`.
