### ISSUE TITLE
How to deal with unknown tags in webstorm

### ISSUE THREAD

**Issue by meikang123** [element-plus/element-plus#1022]

**Comment by meikang123** [comment]
[
![image](https://user-images.githubusercontent.com/16129828/102346298-967a9080-3fd9-11eb-9ee7-8be65ece4fd0.png)
](url)
[
![image](https://user-images.githubusercontent.com/16129828/102346355-ac885100-3fd9-11eb-8e5e-2da436cc81eb.png)
](url)
![image](https://user-images.githubusercontent.com/16129828/102346409-bf9b2100-3fd9-11eb-9914-2034ba7bdcea.png)

**Comment by JeremyWuuuuu** [comment]
This is a plugin related issue, because the tag itself was a customized tag, you editor/IDE needs to know what that is, I personally suggest you to use `VSCode` with `Volar` plugin to support that, for WebStorm developers we cannot provide any help. You may raise the same issue to `Vue`
