### ISSUE TITLE
[Component] [table] 二次封装el-table，在使用拖拽时，table的列不会随之改变

### ISSUE THREAD

**Issue by zyftxdy** [element-plus/element-plus#10243]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.18`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBsaXN0ID0gcmVmPFJlY29yZGFibGVbXT4oW1xuICB7XG4gICAgYzE6ICfmtYvor5UxJyxcbiAgICBjMjogJ+a1i+ivlTInLFxuICAgIGMzOiAn5rWL6K+VMycsXG4gICAgYzQ6ICfmtYvor5U0JyxcbiAgICBjNTogJ+a1i+ivlTUnXG4gIH1cbl0pXG5jb25zdCBjb2x1bW4gPSByZWYoWydjMScsICdjMicsICdjMycsICdjNCcsICdjNSddKVxuY29uc3Qgd2FycFJlZiA9IHJlZigpXG5jb25zdCBvbkNsaWNrID0gKCkgPT4ge1xuICBjb2x1bW4udmFsdWUuc3BsaWNlKDAsIDAsIGNvbHVtbi52YWx1ZVs0XSlcbiAgY29sdW1uLnZhbHVlLnNwbGljZSg1LCAxKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvbkNsaWNrXCI+5qih5ouf5ouW5ou9PC9lbC1idXR0b24+XG4gICAgPGRpdj5cbiAgICAgIDxzcGFuPmNvbHVtbuaVsOaNru+8mjwvc3Bhbj5cbiAgICAgIDxzcGFuXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBjb2x1bW5cIlxuICAgICAgICA6a2V5PVwiaXRlbVwiPnt7aXRlbX19PC9zcGFuPlxuICAgIDwvZGl2PlxuICAgIDxkaXY+XG4gICAgICA8ZGl2PuWOn+Wni3RhYmxlOjwvZGl2PlxuICAgICAgPHRhYmxlIGJvcmRlcj1cIjFcIj5cbiAgICAgIDx0cj5cbiAgICAgICAgPHRoXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBjb2x1bW5cIlxuICAgICAgICA6a2V5PVwiaXRlbVwiPnt7IGl0ZW0gfX08L3RoPlxuICAgICAgPC90cj5cbiAgICAgIDx0cj5cbiAgICAgICAgPHRkXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBjb2x1bW5cIlxuICAgICAgICA6a2V5PVwiaXRlbVwiPnt7IGxpc3RbMF1baXRlbV0gfX08L3RkPlxuICAgICAgPC90cj5cbiAgICA8L3RhYmxlPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJwYi0yMFwiPlxuICAgICAgPGRpdj5lbC10YWJsZTo8L2Rpdj5cbiAgICAgIDxlbC10YWJsZSByZWY9XCJ3YXJwUmVmXCIgOmRhdGE9XCJsaXN0XCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIGNvbHVtblwiXG4gICAgICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgICAgIDpwcm9wPVwiaXRlbVwiXG4gICAgICAgICAgOmxhYmVsPVwiaXRlbVwiLz5cbiAgICAgIDwvZWwtdGFibGU+XG4gICAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

修改columns的列字段排序

### What is Expected?

el-table的列能够随着columns的拖拽新排序改变

### What is actually happening?

进行拖拽改变列排序时，el-table并未重新渲染

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
因为你只换了顺序，key没有改变
```
      <el-table-column
        v-for="(item,index) in column"
        :key="item+index"
        :prop="item"
        :label="item"/>
```

**Comment by Simon-He95** [comment]
是因为key的关系

**Comment by zyftxdy** [comment]
@init-qy  @Simon-He95 感谢，我尝试了，确实是这样，但在vue的角度来说，节点的key顺序应该是更改掉了，应该会触发diff的吧，是el-table针对column的key做了什么操作吗

**Comment by MrWeilian** [comment]
> @init-qy @Simon-He95 感谢，我尝试了，确实是这样，但在vue的角度来说，节点的key顺序应该是更改掉了，应该会触发diff的吧，是el-table针对column的key做了什么操作吗

感兴趣可以看一下详细的解析：[为什么v-for key导致table无法修改列顺序](https://juejin.cn/post/7168308855623909406/)

**Comment by MrWeilian** [comment]
> @init-qy @Simon-He95 感谢，我尝试了，确实是这样，但在vue的角度来说，节点的key顺序应该是更改掉了，应该会触发diff的吧，是el-table针对column的key做了什么操作吗

感兴趣可以看一下详细的解析：[为什么v-for key导致table无法修改列顺序](https://juejin.cn/post/7168308855623909406/)
