### ISSUE TITLE
Button size display error

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#1024]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/10731096/102364612-9edec580-3ff1-11eb-8aa1-e184423dc3b8.png">

bug in the new `el-row` style

**Comment by kooriookami** [comment]
I think we need to give each button size a specific height.
40px、36px、32px、28px.

**Comment by JeremyWuuuuu** [comment]
> I think we need to give each button size a specific height.
> 40px、36px、32px、28px.

Nope, the size of the button is derived from either the props or the global configs.

**Comment by kooriookami** [comment]
> > I think we need to give each button size a specific height.
> > 40px、36px、32px、28px.
> 
> Nope, the size of the button is derived from either the props or the global configs.

Just a default height of global configs or props, user can change props or global configs.
