### ISSUE TITLE
[Component] [popover] 【紧急】popover组件内使用v-model控制显示，点击内容区会自动收起

### ISSUE THREAD

**Issue by daisy0123** [element-plus/element-plus#10240]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.19`
- Browser / OS: `mac`
- Build Tool: `Vue CLI`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgPlxuICAgIDxkaXY+XG4gICAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZGl2PlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gIXZpc2libGVcIj5NYW51YWwgdG8gYWN0aXZhdGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击按钮后 选择选择器值

### What is Expected?

点击按钮后 选择选择器值 不会收起，只有改变visible才收起

### What is actually happening?

点击按钮后选择选择器值莫名收起

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
考虑根据情况使用受控模式 `:visible`

**Comment by jw-foss** [comment]
Try use 

`:visible="visible"` like this:

![CleanShot 2022-11-02 at 16 28 59@2x](https://user-images.githubusercontent.com/15975785/199438352-b2401482-010b-4d1e-961d-011150813889.png)

with `v-model:visible="visible"` visible will be set to `false` when certain event occurs.

**Comment by jw-foss** [comment]
@daisy0123 please try to solve your issue with the way I posted in the previous comment, going to close this issue, if you still suffer from this issue feel free to reopen it and ping me or others in the team for helping you :)
