### ISSUE TITLE
[Component] [cascader] ec-cascader multiple + filterable + show-all-levels 冲突，第二次过滤时无法过滤数据

### ISSUE THREAD

**Issue by arkfancy** [element-plus/element-plus#10251]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome/104.0.0.0`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcblxuY29uc3QgcHJvcHMgPSB7XG4gIG11bHRpcGxlOiB0cnVlXG59XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtsYWJlbDogJzEnLCB2YWx1ZTogJzEnLCBjaGlsZHJlbjogW1xuICAgIHtsYWJlbDogJzEtMScsIHZhbHVlOiAnMS0xJ30sXG4gICAge2xhYmVsOiAnMS0yJywgdmFsdWU6ICcxLTInfSxcbiAgICB7bGFiZWw6ICcxLTMnLCB2YWx1ZTogJzEtMyd9XG4gIF19LFxuICB7bGFiZWw6ICcyJywgdmFsdWU6ICcyJywgY2hpbGRyZW46IFtcbiAgICB7bGFiZWw6ICcyLTEnLCB2YWx1ZTogJzItMSd9LFxuICAgIHtsYWJlbDogJzItMicsIHZhbHVlOiAnMi0yJ30sXG4gICAge2xhYmVsOiAnMi0zJywgdmFsdWU6ICcyLTMnfVxuICBdfSxcbiAge2xhYmVsOiAnMycsIHZhbHVlOiAnMycsIGNoaWxkcmVuOiBbXG4gICAge2xhYmVsOiAnMy0xJywgdmFsdWU6ICczLTEnfSxcbiAgICB7bGFiZWw6ICczLTInLCB2YWx1ZTogJzMtMid9LFxuICAgIHtsYWJlbDogJzMtMycsIHZhbHVlOiAnMy0zJ31cbiAgXX0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtY2FzY2FkZXIgXG4gIFx0di1tb2RlbD0ndmFsdWUnXG4gICAgOnByb3BzPVwicHJvcHNcIlxuICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgZmlsdGVyYWJsZVxuICAgIDpzaG93LWFsbC1sZXZlbHM9XCJmYWxzZVwiXG4gICAgICAgICAgICAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.聚焦级联框，输入1-进行过滤，过滤出1-1，1-2，1-3
2.点击选择1-1，失焦级联框
3.再次聚焦级联框，重新输出1-进行过滤

### What is Expected?

此时应该依旧过滤出1-1，1-2，1-3 且其中1-1是已选择状态

### What is actually happening?

No matching data

### Additional comments

在:show-all-levels="false"的情况下会过滤不出数据，改成true时能正常过滤

![image](https://user-images.githubusercontent.com/30465365/197967277-681cd35a-f9c4-4a00-9f25-b7c6258316b2.png)

![image](https://user-images.githubusercontent.com/30465365/197967420-6f168027-b572-4e8c-ab0a-a12d3bb58eee.png)

**Comment by holazz** [comment]
Fixed via https://github.com/element-plus/element-plus/pull/10439
