### ISSUE TITLE
[Component] [select] el-select设置为remote时，选中某一个选项或失去焦点会触发remote-method

### ISSUE THREAD

**Issue by ainuo5213** [element-plus/element-plus#10283]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.19`
- Browser / OS: `Chrome 106.0.5249.119`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFtdKVxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5cbmZ1bmN0aW9uIGdldERhdGEocXVlcnkpIHtcbiAgYWxlcnQocXVlcnkpXG4gIGxpc3QudmFsdWUgPSBbJzEnLCAnMicsICczJ11cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHJlbW90ZSBmaWx0ZXJhYmxlIGNsZWFyYWJsZSA6cmVtb3RlLW1ldGhvZD1cImdldERhdGFcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgdi1mb3I9XCJpdGVtIGluIGxpc3RcIlxuICAgICAgIDprZXk9XCJpdGVtXCJcbiAgICAgICA6dmFsdWU9XCJpdGVtXCJcbiAgICAgICA6bGFiZWw9XCJpdGVtXCI+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

选中某一项，在对应的remote-method处打印参数

### What is Expected?

无打印

### What is actually happening?

打印undefined

### Additional comments

我认为在失去焦点的时候，如果没有数据的情况下才需要执行remote-method，如果本身有数据或者选中的情况下是不需要执行remote-method的

**Comment by Ryuuki6602** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFtcbiAgMSwyLDMsNCw1XG5dKVxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5cbmZ1bmN0aW9uIGdldERhdGEocXVlcnkpIHtcbiAgY29uc29sZS5sb2cocXVlcnkpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiByZW1vdGUgZmlsdGVyYWJsZSBjbGVhcmFibGUgOnJlbW90ZS1tZXRob2Q9XCJnZXREYXRhKHZhbHVlKVwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgICB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiXG4gICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgIDp2YWx1ZT1cIml0ZW1cIlxuICAgICAgIDpsYWJlbD1cIml0ZW1cIj5cbiAgICA8L2VsLW9wdGlvbj5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
这是你想要的效果吗

**Comment by btea** [comment]
可以参考一下 #9539 #9587

**Comment by ainuo5213** [comment]
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFtcbiAgMSwyLDMsNCw1XG5dKVxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5cbmZ1bmN0aW9uIGdldERhdGEocXVlcnkpIHtcbiAgYWxlcnQocXVlcnkpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiByZW1vdGUgZmlsdGVyYWJsZSBjbGVhcmFibGUgOnJlbW90ZS1tZXRob2Q9XCJnZXREYXRhKHZhbHVlKVwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgICB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiXG4gICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgIDp2YWx1ZT1cIml0ZW1cIlxuICAgICAgIDpsYWJlbD1cIml0ZW1cIj5cbiAgICA8L2VsLW9wdGlvbj5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319) 这是你想要的效果吗

我就是不想要这种，目前是在getData这个方法里面手动过滤了undefined，不过我觉得官方应该避免在选中时重新获取数据
