### ISSUE TITLE
[Component] [tab-pane, table] 2.2.18之后，el-tabs无法识别子组件的el-tab-pane

### ISSUE THREAD

**Issue by chenqixian** [element-plus/element-plus#10284]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.18`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZWwtdGFicyB0YWItcG9zaXRpb249XCJsZWZ0XCIgdHlwZT1cImNhcmRcIiAgc3R5bGU9XCJoZWlnaHQ6IDIwMHB4XCIgY2xhc3M9XCJkZW1vLXRhYnNcIj5cbiAgICA8Y29tcD48L2NvbXA+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQge2RlZmluZUNvbXBvbmVudH0gZnJvbSBcInZ1ZVwiO1xuaW1wb3J0IENvbXAgZnJvbSBcIi4vQ29tcC52dWVcIlxuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBjb21wb25lbnRzOiB7XG4gICAgQ29tcFxuICB9XG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIkNvbXAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZWwtdGFiLXBhbmUgbmFtZT1cInByZVNjcmlwdFwiIGxhYmVsPVwicHJlU2NyaXB0XCI+XG4gICAgdGFiIHBhbmVcbiAgPC9lbC10YWItcGFuZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIG5hbWU6IFwiY29tcFwiLFxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG5cbjwvc3R5bGU+IiwiX28iOnt9fQ==)

### Steps to reproduce

选择2.2.17版本，能渲染pane。
选择2.2.18或以后，无法渲染pane

### What is Expected?

可以渲染子组件里的pane

### What is actually happening?

无法识别pane

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/23447838/198240158-6723e6a3-2c53-43ac-b010-cf789d5f7c30.png)
![image](https://user-images.githubusercontent.com/23447838/198240009-699e3ce9-11a5-4881-b128-adef99dbb1a8.png)
![image](https://user-images.githubusercontent.com/23447838/198240048-d6862ca8-fd7b-4fbc-a309-561582eef600.png)

**Comment by chenxch** [comment]
#9785 应该是这次为了tab有序做的调整，导致嵌套模式下失效

**Comment by tolking** [comment]
新版本目前还不支持 `el-tabs` 中引用一个组件的情况

Link #9281

**Comment by chenxch** [comment]
> 新版本目前还不支持 `el-tabs` 中引用一个组件的情况
> 
> Link #9281

tabs我目前修改了扁平化函数后是可以了，menu等我吃饭试一下。

**Comment by chenxch** [comment]
menu测试发现目前实现方式和tabs有些差别
