### ISSUE TITLE
[Component] [dialog] closeOnPressEscape 变更时不生效

### ISSUE THREAD

**Issue by lacmo** [element-plus/element-plus#10296]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5sZXQgdmlzaWJsZSA9IHJlZihmYWxzZSlcblxubGV0IGNhbkNhbmNlbCA9IHJlZih0cnVlKVxuXG5jb25zdCBwd2RQYXJhbXMgPSByZWFjdGl2ZSh7XG4gIGNsb3NlT25DbGlja01vZGFsOiBjYW5DYW5jZWwsXG4gIGNsb3NlT25QcmVzc0VzY2FwZTogY2FuQ2FuY2VsLFxuICBzaG93Q2xvc2U6IGNhbkNhbmNlbCxcbiAgY2FuQ2FuY2VsOiBjYW5DYW5jZWxcbn0pXG5cbnNldFRpbWVvdXQoKCk9PntcbiAgdmlzaWJsZS52YWx1ZSA9IHRydWVcbiAgY2FuQ2FuY2VsLnZhbHVlID0gZmFsc2VcbiAgXG59LCA1MDAwKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwidmlzaWJsZVwiIHYtYmluZD1cInB3ZFBhcmFtc1wiPlxuXHRcdOS7hea1i+ivlVxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPHNwYW4+XG4gICAgICAgIDx0ZW1wbGF0ZSB2LWlmPVwiY2FuQ2FuY2VsXCI+XG4gICAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVDYW5jZWxcIj7lj5bmtog8L2VsLWJ1dHRvbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImhhbmRsZU9rXCI+56Gu6K6kPC9lbC1idXR0b24+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG4gIFxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

出现弹框后按 esc

### What is Expected?

出现弹框后按 esc 弹框不消失

### What is actually happening?

出现弹框后按 esc 弹框消失

### Additional comments

_(empty)_

**Comment by ntnyq** [comment]
Bump to version `>=2.2.1`
