### ISSUE TITLE
【BUG】Click scrollbar when mouseup still scroll by mousemove

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1029]
version：1.0.1-beta.9
https://element-plus.org/#/zh-CN/component/time-select
https://element-plus.org/#/zh-CN/component/select

Click scrollbar when mouseup still scroll by mousemove.

**Comment by JeremyWuuuuu** [comment]
Confirmed. By single click the scrollbar, it will be reproduced.

**Comment by edisonLzy** [comment]
this problem cause by popper component stop the bubbling , so the mouseup event on document can't be invoked

**Comment by bastarder** [comment]
popper stop MouseEvent, maybe need discuss
