### ISSUE TITLE
[Style] [image] Image 图片 或 dialog弹框图片展示问题

### ISSUE THREAD

**Issue by 1096396089** [element-plus/element-plus#10309]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.19`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/?file=http://wechat-admin.lonely.fyi)

### Steps to reproduce

```vue
<template>
    <div class="demo-image__preview">
      <el-image
        style="width: 48px; height: 48px"
        :src="modelValue"
        :preview-src-list="srcList"
        fit="cover"
        :hide-on-click-modal="true"
      />
    </div>
  </template>
<script setup lang="ts">
import { ref, reactive } from "vue";


const prop = defineProps({
  modelValue: {
    type: String,
    default: "",
  },
});


const srcList = [prop.modelValue]


const imageVisible = ref(false);
const image_url = ref("");
const prive_image = (url) => {
  (image_url.value = url), (imageVisible.value = true);
};
</script>


<style scoped>
.demo-image__error .image-slot {
  font-size: 30px;
}
.demo-image__error .image-slot .el-icon {
  font-size: 30px;
}
.demo-image__error .el-image {
  width: 100%;
  height: 200px;
}
</style>

```
```vue 
 <PriveImage v-model="row.url" ></PriveImage>
```

### What is Expected?

展示预览图片

### What is actually happening?

展示图片了，表格却也在上层

### Additional comments

file=后面地址可以查看

**Comment by 1096396089** [comment]
Image Viewer 图片预览组件放在表格使用就会出现这个问题
![image](https://user-images.githubusercontent.com/59545129/198856035-3c1d736b-95f1-4a57-af15-48b03590c08e.png)

**Comment by btea** [comment]
请参考[文档](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)
