### ISSUE TITLE
[Component] [icon] el-icon组件的size属性传入字符串 无效

### ISSUE THREAD

**Issue by cdbEvan** [element-plus/element-plus#10307]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Google Chrome 00.0.4896.60/ win10`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDwhLS0gIOS8oOWFpXN0cmluZ+aXoOaViCAgLS0+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiIHNpemU9XCI1NVwiID48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgPCEtLSAg5Lyg5YWlbnVtYmVy5pyJ5pWIIC0tPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIiA6c2l6ZT1cIjU1XCIgPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<el-icon size="55" ><ElementPlus /></el-icon>

### What is Expected?

size 传入字符串也可以改变大小

### What is actually happening?

传入字符串不能改变大小，只有传入数字才行

### Additional comments

/element-plus-dev/packages/utils/dom/style.ts中的addUnit方法有bug,80行的return value没有加上defaultUnit而导致的

**Comment by holazz** [comment]
传字符串需要自己处理单位，比如 `size="50px"`

**Comment by cdbEvan** [comment]
提完issue就想起来了。一时间没反应过来

大佬可否加个微信或者qq，有时候有些问题想咨询咨询




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月29日(星期六) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [icon] el-icon组件的size属性传入字符串 无效 (Issue #10307)





 
传字符串需要自己处理单位，比如 size="50px"

**Comment by holazz** [comment]
> 提完issue就想起来了。一时间没反应过来 大佬可否加个微信或者qq，有时候有些问题想咨询咨询
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月29日(星期六) 晚上6:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [element-plus/element-plus] [Component] [icon] el-icon组件的size属性传入字符串 无效 (Issue #10307) 传字符串需要自己处理单位，比如 size="50px" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以加入 [Discord](https://discord.link/ElementPlus)，有问题在这里讨论 😊

**Comment by Simon-He95** [comment]
> > 提完issue就想起来了。一时间没反应过来 大佬可否加个微信或者qq，有时候有些问题想咨询咨询
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年10月29日(星期六) 晚上6:39 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [element-plus/element-plus] [Component] [icon] el-icon组件的size属性传入字符串 无效 (Issue #10307) 传字符串需要自己处理单位，比如 size="50px" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 可以加入 [Discord](https://discord.link/ElementPlus)，有问题在这里讨论 😊

Discord link 是不是过期了

**Comment by holazz** [comment]
> > > 提完issue就想起来了。一时间没反应过来 大佬可否加个微信或者qq，有时候有些问题想咨询咨询
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年10月29日(星期六) 晚上6:39 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [element-plus/element-plus] [Component] [icon] el-icon组件的size属性传入字符串 无效 (Issue #10307) 传字符串需要自己处理单位，比如 size="50px" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 可以加入 [Discord](https://discord.link/ElementPlus)，有问题在这里讨论 😊
> 
> Discord link 是不是过期了

应该不会过期，或者可以试试这个 https://discord.gg/AgSjrmm8Mu

**Comment by Simon-He95** [comment]
> > > > 提完issue就想起来了。一时间没反应过来 大佬可否加个微信或者qq，有时候有些问题想咨询咨询
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年10月29日(星期六) 晚上6:39 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [element-plus/element-plus] [Component] [icon] el-icon组件的size属性传入字符串 无效 (Issue #10307) 传字符串需要自己处理单位，比如 size="50px" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > > 
> > > 
> > > 可以加入 [Discord](https://discord.link/ElementPlus)，有问题在这里讨论 😊
> > 
> > 
> > Discord link 是不是过期了
> 
> 应该不会过期，或者可以试试这个 https://discord.gg/AgSjrmm8Mu

这个link是好的:)

**Comment by kooriookami** [comment]
我给addUnit加上字符串数字的判断，应该可以一劳永逸了:D
