### ISSUE TITLE
API type = "datetimerange" in datetimepicker seems to be invalid

### ISSUE THREAD

**Issue by Bo-LiangD** [element-plus/element-plus#1030]
Api type="datetimerange" in DateTimePicker seems invalid. I check the 'date and time range with the shortcut option' in your Element-Plus. I see that the code has the latest week, month, and three months, but I don't see it in the example

em em  em  
![image](https://user-images.githubusercontent.com/29296518/102462124-591f0d00-4084-11eb-9636-4e29a7dc8153.png)  
Console information

![image](https://user-images.githubusercontent.com/29296518/102462241-7a7ff900-4084-11eb-8d88-3afde934c5ec.png)
This is the Plus website

**Comment by zazzaz** [comment]
this should be fixed in 1.0.1-beta.9

also, note, picker-option is removed and all the props are moved to the top-level

**Comment by Bo-LiangD** [comment]
My update is 1.0.1-beta.9. But still no date or time range to choose from.

What form are you saying the props are moved to the top-level '...

Is it possible for me to reprocess it so as to realize a week, January and March...

**Comment by JeremyWuuuuu** [comment]
Seems like we got this documentation forgotten. We need to update that one as well. `picker-options` had been deprecated.

**Comment by zazzaz** [comment]
Hi, you can check the demo code `shortcuts` in https://element-plus.org/#/en-US/component/date-picker

Doc will be updated soon.

**Comment by Bo-LiangD** [comment]
![image](https://user-images.githubusercontent.com/29296518/102564180-da72b000-4115-11eb-82c1-e63fa238d594.png)
The value of the selected date was not cleared when I cleared it
![image](https://user-images.githubusercontent.com/29296518/102564338-32a9b200-4116-11eb-8cec-7276225a9881.png)
It will come up when I reset it

**Comment by zazzaz** [comment]
fixed in #1033
