### ISSUE TITLE
[Component] [image] ElImage 无法设置 crossorigin 属性

### ISSUE THREAD

**Issue by DevDengChao** [element-plus/element-plus#10315]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW1hZ2Ugc3JjPVwiaHR0cHM6Ly93d3cud2Vic2VxdWVuY2VkaWFncmFtcy5jb20vY2dpLWJpbi9jZHJhdz9sej1kR2wwYkdVZ1ZXNEFBd1ZrQ2dwQmJHbGpaUzAtUW05aU9pQkJkWFJvWlc1MGFXTmhkR2x2YmlCU1pYRjFaWE4wQ201dmRHVWdjbWxuYUhRZ2IyWWdBQ1VGUW05aUlIUm9hVzVyY3lCaFltOTFkQ0JwZEFwQ2IySXRQZ0JLQlFBM0UzTndiMjV6WlFvSyZzPWRlZmF1bHRcIi8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在本地工程中预览上述代码片段时, 浏览器会提示存在 "Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute" 问题, 查阅文档后发现 img 标签支持设置 crossorigin 属性来避免发送 cookie.

参考: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img#attr-crossorigin

### What is Expected?

ElImage 支持设置 crossorigin 属性

### What is actually happening?

暂时不支持

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
是支持的，除了 `crossorigin` 之外，其他的所有属性都可以加在 `img` 里

[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW1hZ2Ugc3JjPVwiaHR0cHM6Ly9hdmF0YXJzMy5naXRodWJ1c2VyY29udGVudC5jb20vdS80OTYwNDg/cz0xMjAmdj00XCIgY3Jvc3NvcmlnaW49XCJhbm9ueW1vdXNcIiBhPVwiYlwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
