### ISSUE TITLE
When el-input set "value" attributes, it can't show this value in the input box. el-date-picker and el-radio-group maybe also have this problem.

### ISSUE THREAD

**Issue by HiWayne** [element-plus/element-plus#1031]
**version:  vue@3.0.2  &&  element-plus@1.0.1-beta.3**

**example:**
```
<template>
  <el-card>
    <el-input :value="12" @input="onInput"></el-input>
  </el-card>
</template>

<script>
export default {
  setup() {

    // set reactive state for input

    const onInput = value => {
      console.log(value)
      // modify reactive state...
    }
    
    // ignore reactive state no return
    return { onInput }
  }
}
</script>
```

**In my own project, first, i write a reactive state for ":value" in ElInput, value doesn't work.**

**Then, i write 12( :value="12" ) or "12"( value="12" ) for value directly. As shown in the code above.**

**They all can't show value in the input box.**

**\<el-date-picker\> and \<el-radio-group\> also have this problem. However, their links passed in my project are more complicated, i may not know why. Only \<el-input\> has been tested by my minimal demo**

**I also discovered a magical phenomenon: it will display value after webpack hot update and display nothing after refresh**

**Comment by JeremyWuuuuu** [comment]
Have you tried using `v-model` notation?

**Comment by Ryan2128** [comment]
Please check [migration/v-model](https://v3.vuejs.org/guide/migration/v-model.html#overview)

**Comment by JeremyWuuuuu** [comment]
> Please check [migration/v-model](https://v3.vuejs.org/guide/migration/v-model.html#overview)

The documentation ain't right, we need to update it. It still recommends `value` notation

**Comment by HiWayne** [comment]
> Have you tried using `v-model` notation?

"v-model" is right, but i need send value as prop to input component, so, v-model will prompt "Unexpected mutation of "value" prop"

**Comment by JeremyWuuuuu** [comment]
When you use v-model it updates the value for you. Could you send the errored version  for me to investifate? It is even better if you can send us a online version. Much appreciated.

**Comment by HiWayne** [comment]
> Have you tried using `v-model` notation?

I expect a config that type is "object[]" can be provided to a component, that it can be rendered to a form list. I am not particularly familiar with the new syntax of vue3. So, maybe i can only use value as prop, right ?

**Comment by HiWayne** [comment]
> When you use v-model it updates the value for you. Could you send the errored version for me to investifate? It is even better if you can send us a online version. Much appreciated.

element-plus@1.0.1-beta.3
How can i send you a online version ?

**Comment by JeremyWuuuuu** [comment]
There is a link(button) on the main page of our github you may find.

**Comment by JeremyWuuuuu** [comment]
As long as the binding is reactive. You can use it as v-model to get updates automatically

**Comment by JeremyWuuuuu** [comment]
If you find that value won't work. Use modelValue instead. This is a one way binding

**Comment by JeremyWuuuuu** [comment]
Passing the value like you did above with the name `:modelValue=binding`. You'll get the same behavior like `value`

**Comment by HiWayne** [comment]
> Passing the value like you did above with the name `:modelValue=binding`. You'll get the same behavior like `value`

Wow, it works magically! Thank you very much. I seem can't find the button about online version.

**Comment by JeremyWuuuuu** [comment]
Don't worry, thank you for raising this issue, we'll improve our documentations later

**Comment by HiWayne** [comment]
> Don't worry, thank you for raising this issue, we'll improve our documentations later

Ok. I'm in Shanghai too. Goodbye if fate.

**Comment by JeremyWuuuuu** [comment]
I'm closing this issue since it had been resolved.
