### ISSUE TITLE
[Component] [upload] File upload auto upload false then return in onchange simple object not file object

### ISSUE THREAD

**Issue by utsavsomaiya** [element-plus/element-plus#10331]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.13`
- Browser / OS: `Chrome Ubuntu/Linux - 22.04`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/upload.html#attributes)

### Steps to reproduce

- Return the file type object

### What is Expected?

Return the file type object

### What is actually happening?

Only Return Simple Object

**Comment by chenxch** [comment]
Maybe fix in #10220.

**Comment by utsavsomaiya** [comment]
> Maybe fix in #10220.

May be not because on change attribute simple object return that is my issue. :thinking:
