### ISSUE TITLE
[Component] [date-picker] 月度日期区间用户不能输入，输入会报错（se.value.parseUserInput is not a function），官网示例也可以看到报错，element-ui中用户可以输入

### ISSUE THREAD

**Issue by lijidong1234** [element-plus/element-plus#10347]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.19`
- Browser / OS: `Google Chrome 106.0.5249.119`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html)

### Steps to reproduce

官网中找到日期组件，找到月度区间选择日期示例，输入指定日期

### What is Expected?

日期可以由用户手动输入

### What is actually happening?

控台报错，用户输入无效

### Additional comments

_(empty)_

**Comment by tolking** [comment]
This issues has been fixed.
