### ISSUE TITLE
[Component] [select, select-v2] 【el-select】组件在v-model为null时，会报出警告

### ISSUE THREAD

**Issue by jesse51076008** [element-plus/element-plus#10352]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.19`
- Browser / OS: `edge 106`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0eXBlID0gcmVmKG51bGwpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGVsLXNlbGVjdCB2LW1vZGVsPVwidHlwZVwiPlxuICAgIDxlbC1vcHRpb24gOnZhbHVlPVwibnVsbFwiIGxhYmVsPVwiPG5vbmU+XCIgLz5cbiAgICA8ZWwtb3B0aW9uIDp2YWx1ZT1cIjFcIiBsYWJlbD1cIlR5cGUgMVwiIC8+XG4gICAgPGVsLW9wdGlvbiA6dmFsdWU9XCIyXCIgbGFiZWw9XCJUeXBlIDJcIiAvPlxuPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

【最小复现环境的链接】有代码

### What is Expected?

el-select可以选择【空】，代表不选择任何选项

### What is actually happening?

当el-select选择【空】时，报出一个警告

### Additional comments

有些时候，选择需要选择【空】，代表不选择任何项，性别可以选择【男】【女】和【未设置】，当【未设置】时，我希望用【null】而不是【0】或者【-1】代替

**Comment by holazz** [comment]
> 有些时候，选择需要选择【空】，代表不选择任何项

在 select 组件中，**不选择任何选项**意味着它不应该出现在 options 列表中，比如使用 `null` 或 `undefined` 初始化的时候就是不选择任何选项：
```ts
const value = ref(null) 
// or
const value = ref()
```
> 性别可以选择【男】【女】和【未设置】

你这里提到的【未设置】实际是 options 列表里的一项，所以它对应的 value 不能是 `null` 或 `undefined`，你可以使用其它值，比如空字符串

**Comment by jesse51076008** [comment]
@holazz 
多谢回答，这个【未设置】是列表中的一项，代表用户并不想透漏自己的性别信息，并且，当其选择【未设置】时对应的数据库会存储【NULL】，当从数据库读取此数据时，希望能够在界面上直接默认到【未设置】的option上，所以这里的【未设置】选项理当使用null作为其value而不是空字符串（''）。

**Comment by emojiiii** [comment]
> @holazz 多谢回答，这个【未设置】是列表中的一项，代表用户并不想透漏自己的性别信息，并且，当其选择【未设置】时对应的数据库会存储【NULL】，当从数据库读取此数据时，希望能够在界面上直接默认到【未设置】的option上，所以这里的【未设置】选项理当使用null作为其value而不是空字符串（''）。

这个请自行处理数据。
