### ISSUE TITLE
[Component] [descriptions-item] 给描述列表最后一个Descriptions Item设置的span属性不生效/The span attribute set for the last Descriptions Item in the Descriptions does not take effect

### ISSUE THREAD

**Issue by sq800** [element-plus/element-plus#10358]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `windows11 22H2`
- Build Tool: `Vite`

### Related Component

- `el-descriptions-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZGVzY3JpcHRpb25zIHRpdGxlPVwiVXNlciBJbmZvXCIgYm9yZGVyIGNvbHVtbj1cIjRcIj5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJVc2VybmFtZVwiPmtvb3Jpb29rYW1pPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJUZWxlcGhvbmVcIj4xODEwMDAwMDAwMDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiUGxhY2VcIj5TdXpob3U8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlJlbWFya3NcIj5cbiAgICAgIDxlbC10YWcgc2l6ZT1cInNtYWxsXCI+U2Nob29sPC9lbC10YWc+XG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gc3Bhbj1cIjRcIiBsYWJlbD1cIkFkZHJlc3NcIlxuICAgICAgPk5vLjExODgsIFd1emhvbmcgQXZlbnVlLCBXdXpob25nIERpc3RyaWN0LCBTdXpob3UsIEppYW5nc3VcbiAgICAgIFByb3ZpbmNlPC9lbC1kZXNjcmlwdGlvbnMtaXRlbVxuICAgID5cbiAgXG4gIFx0PGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVGVsZXBob25lXCI+MTgxMDAwMDAwMDA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICBcdDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlRlbGVwaG9uZVwiPjE4MTAwMDAwMDAwPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgXHQ8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJUZWxlcGhvbmVcIj4xODEwMDAwMDAwMDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gIFx0PGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVGVsZXBob25lXCI+MTgxMDAwMDAwMDA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICBcdDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlRlbGVwaG9uZVwiIHNwYW49XCI0XCI+MTgxMDAwMDAwMDA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgPC9lbC1kZXNjcmlwdGlvbnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

最后一个item设置的span属性不生效

### What is Expected?

最后一个item应该占满一行

### What is actually happening?

只占了一格

### Additional comments

![image](https://user-images.githubusercontent.com/63217984/199422369-f32f4911-4cff-4e34-8353-2a3575f33cd6.png)

**Comment by init-qy** [comment]
> Invalid prop: type check failed for prop "column". Expected Number with value 4, got String with value "4".
 at <ElDescriptionstitle="User Info"border=""column="4">

需要注意下传参的类型，如果类型不是字符串，需要在参数前加 `:`，否则可能会有问题。
这个例子中 需要改下 `:span="4"`

**Comment by Simon-He95** [comment]
> > Invalid prop: type check failed for prop "column". Expected Number with value 4, got String with value "4".
> > at <ElDescriptionstitle="User Info"border=""column="4">
> 
> 需要注意下传参的类型，如果类型不是字符串，需要在参数前加 `:`，否则可能会有问题。 这个例子中 需要改下 `:span="4"`

我认为我们可以支持一下字符串类型的数字

**Comment by sq800** [comment]
当上一行的items的span总数未占满column时，下一个item无论设置了多大的span，都不会再另起一行。不知道是否设计如此？
![4692717813c649819feb68ec01f005f](https://user-images.githubusercontent.com/63217984/199436219-608b77a7-f12a-4747-a474-cfa492a5dbd7.jpg)

**Comment by kooriookami** [comment]
> > > Invalid prop: type check failed for prop "column". Expected Number with value 4, got String with value "4".
> > > at <ElDescriptionstitle="User Info"border=""column="4">
> > 
> > 
> > 需要注意下传参的类型，如果类型不是字符串，需要在参数前加 `:`，否则可能会有问题。 这个例子中 需要改下 `:span="4"`
> 
> 我认为我们可以支持一下字符串类型的数字

我给addUnit方法加上了字符串数字的判断，这样应该可以一劳永逸了:D

**Comment by kooriookami** [comment]
我加错issue号了（

**Comment by init-qy** [comment]
> 我认为我们可以支持一下字符串类型的数字

我认为没有必要，如果这里支持了那其他组件是否需要跟进？比如 `el-row`，另外`string`类型在ide的提示上也会给用户带来困惑。

**Comment by init-qy** [comment]
> 当上一行的items的span总数未占满column时，下一个item无论设置了多大的span，都不会再另起一行。不知道是否设计如此？ ![4692717813c649819feb68ec01f005f](https://user-images.githubusercontent.com/63217984/199436219-608b77a7-f12a-4747-a474-cfa492a5dbd7.jpg)

这应该是一个bug

**Comment by Simon-He95** [comment]
> > 我认为我们可以支持一下字符串类型的数字
> 
> 我认为没有必要，如果这里支持了那其他组件是否需要跟进？比如 `el-row`，另外`string`类型在ide的提示上也会给用户带来困惑 @Simon-He95

其实现在的问题就是用户输入了字符串'4'，但是还是能正常渲染也没有错误和警告，但是表现的结果有问题，我觉得要么保持number，在el-description-item span如果是字符串的时候也同样抛出警告，要么就支持string

**Comment by init-qy** [comment]
> 当上一行的items的span总数未占满column时，下一个item无论设置了多大的span，都不会再另起一行。不知道是否设计如此？ ![4692717813c649819feb68ec01f005f](https://user-images.githubusercontent.com/63217984/199436219-608b77a7-f12a-4747-a474-cfa492a5dbd7.jpg)

https://github.com/element-plus/element-plus/blob/e7843c02c4d921e6dd0190c9bff0e35106589c9a/packages/components/descriptions/src/description.vue#L84

@sq800 我看了下源码，的确有这样的处理

**Comment by sq800** [comment]
在遍历渲染一个对象时，如果的确需要让某一个属性另起一行，有什么解决方法吗

**Comment by alicemw** [comment]
@init-qy 并不是啊，我设置的是数字类型，:span = 1 ,最后一个description-item还是给我生成的是 colspan = 2

**Comment by init-qy** [comment]
请不要在两年前的issue回复，现在版本有了新的变化，如有问题请新开一个issue，并提供对应的版本说明和playground

**Comment by yangbiao-ui** [comment]
这个问题怎么解决
