### ISSUE TITLE
[Component] [radio, radio-button] Why does el-radio use the label attribute instead of the value attribute to specify the value? el-radio 为何用 label 而不是 value 指定值呢？

### ISSUE THREAD

**Issue by JChehe** [element-plus/element-plus#10365]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-radio`
- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgbGFiZWw6ICfpgInpobkxJyxcbiAgICB2YWx1ZTogMFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICfpgInpobkyJyxcbiAgICB2YWx1ZTogMVxuICB9XG5dXG5jb25zdCB2YWx1ZSA9IHJlZihudWxsKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDM+5L2g5omA6YCJ5oup55qE5piv77yae3sgdmFsdWUgfX08L2gzPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInZhbHVlXCI+XG4gIFx0PGVsLXJhZGlvXG4gICAgICB2LWZvcj1cInsgbGFiZWwsIHZhbHVlIH0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwidmFsdWVcIlxuICAgICAgOmxhYmVsPVwidmFsdWVcIj57e2xhYmVsfX08L2VsLXJhZGlvPlxuICA8L2VsLXJhZGlvLWdyb3VwPlxuXHQ8cD5cbiAgICBgbGFiZWxgIOWxnuaAp+S4gOiIrOS9nOS4uuKAnOagh+etvuaWh+acrOKAne+8jOWFtuS7lue7hOS7tuS5n+Wkp+WkmuS9nOS4uuaWh+acrOivtOaYjueahOeUqOmAlOOAguS9hiBgZWwtcmFkaW9gIOeahCBgbGFiZWxgIOWxnuaAp+aXouS9nOS4uiBsYWJlbO+8jOWPiOS9nOS4uiB2YWx1ZeOAglxuICA8L3A+XG4gIDxwPlxuICAgIOWvueS6juS7peS4iiBvcHRpb25zIOeahOWumuS5ie+8jOS8muWHuueOsOi/meenjeeOsOixoe+8mmBlbC1yYWRpbyg6bGFiZWw9XCJ2YWx1ZVwiKSB7IHsgbGFiZWwgfSB9YOOAglxuICA8L3A+XG4gIDxwPuaDs+S6huino+S4gOS4i+S4uuS9leS4jemAmui/hyB2YWx1ZSDlsZ7mgKfmjIflrpogcmFkaW8g55qE5YC877yf6L+Z5Lmf5pu06LS06L+RIEhUTUwg55qEICZsdDtpbnB1dCB0eXBlPVwicmFkaW9cIiBuYW1lPVwieHhOYW1lXCIgdmFsdWU9XCJ4eFZhbHVlXCImZ3Q7IOagh+etvuOAgjwvcD5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
const options = [
  {
    label: '选项1',
    value: 0
  },
  {
    label: '选项2',
    value: 1
  }
]

<el-radio-group v-model="value">
  <el-radio
      v-for="{ label, value } in options"
      :key="value"
      :label="value">{{ label }}</el-radio>
</el-radio-group>
```

`label` 属性一般作为“标签文本”，其他组件也大多作为文本说明的用途。但 `el-radio` 的 `label` 属性既作为 label，又作为 value。

对于以上 options 的定义，会出现这种现象：`el-radio(:label="value") {{ label }}`。

想了解一下为何不通过 value 属性指定 radio 的值？这也更贴近 HTML 的 `<input type="radio" name="xxName" value="xxValue">` 标签。

### What is Expected?

通过 value 属性指定 el-radio 的值。

### What is actually happening?

通过 label 属性指定 el-radio 的值。

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
这是一个历史遗留问题。使用`label`绑定值确实有歧义，直接改动可能会造成挺大的影响，是否修改还需要进行讨论。

**Comment by RockyF** [comment]
好像从ElementUI开始就这样设定了，导致只能通过样式来隐藏标签文本了，难受

**Comment by CeremcoBarbe** [comment]
Are there any plans on changing this request?

**Comment by kooriookami** [comment]
> Are there any plans on changing this request?

Yes, please refer to the PR #15525
