### ISSUE TITLE
[Style] 在el-form中加样式display:flex时，input输入框出现删除图标会使输入框长度变化

### ISSUE THREAD

**Issue by wangsansi** [element-plus/element-plus#10372]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.19`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-form`
- `el-form-item`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1mb3JtPlxuICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXhcIj5cbiAgICAgICAgPGVsLWZvcm0taXRlbT5cbiAgICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0MVwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI3ByZXBlbmQ+SHR0cDovLzwvdGVtcGxhdGU+XG4gICAgICAgICAgPC9lbC1pbnB1dD5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dDJcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIGNsZWFyYWJsZT5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjYXBwZW5kPi5jb208L3RlbXBsYXRlPlxuICAgICAgICAgIDwvZWwtaW5wdXQ+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXQzXCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBjbGVhcmFibGU+XG4gICAgICAgICAgPC9lbC1pbnB1dD5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICA8L2Rpdj5cbiAgICA8L2VsLWZvcm0+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgaW5wdXQxID0gcmVmKCcnKVxuY29uc3QgaW5wdXQyID0gcmVmKCcnKVxuY29uc3QgaW5wdXQzID0gcmVmKCcnKVxuY29uc3Qgc2VsZWN0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5pbnB1dC13aXRoLXNlbGVjdCAuZWwtaW5wdXQtZ3JvdXBfX3ByZXBlbmQge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1lbC1maWxsLWNvbG9yLWJsYW5rKTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

当el-form中加样式display:flex时，点击输入框输入内容，鼠标hover，出现删除按钮，input长度会变化

### What is Expected?

input不变长

### What is actually happening?

input变长

### Additional comments

```vue
<template>
  <div>
    <el-form>
      <div style="display: flex">
        <el-form-item>
          <el-input v-model="input1" placeholder="Please input">
            <template #prepend>Http://</template>
          </el-input>
        </el-form-item>
        <el-form-item>
          <el-input v-model="input2" placeholder="Please input" clearable>
            <template #append>.com</template>
          </el-input>
        </el-form-item>
        <el-form-item>
          <el-input v-model="input3" placeholder="Please input" clearable>
          </el-input>
        </el-form-item>
      </div>
    </el-form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const input1 = ref('')
const input2 = ref('')
const input3 = ref('')

</script>

<style>

</style>
```

**Comment by charles-lpd** [comment]
在宽度不确定的情况下，盒子宽度是不固定的，所以icon的出现增加了宽度，并没有挤压input, 导致宽度增加。
给 el-form-item 添加默认宽度，可暂时解决问题。

**Comment by HeftyKoo** [comment]
Duplicate: #7287
