### ISSUE TITLE
[Style] [autocomplete] Autocomplete placement="top-start" 时 搜索之后 下拉列表 位置不正确

### ISSUE THREAD

**Issue by kai-silver** [element-plus/element-plus#10375]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Chrome/107.0.5304.87`
- Build Tool: `Other`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuaW50ZXJmYWNlIFJlc3RhdXJhbnRJdGVtIHtcbiAgdmFsdWU6IHN0cmluZ1xuICBsaW5rOiBzdHJpbmdcbn1cblxuY29uc3Qgc3RhdGUxID0gcmVmKCcnKVxuY29uc3QgcmVzdGF1cmFudHMgPSByZWY8UmVzdGF1cmFudEl0ZW1bXT4oW10pXG5cbmNvbnN0IHF1ZXJ5U2VhcmNoID0gKHF1ZXJ5U3RyaW5nOiBzdHJpbmcsIGNiOiBhbnkpID0+IHtcbiAgY29uc3QgcmVzdWx0cyA9IHF1ZXJ5U3RyaW5nXG4gICAgPyByZXN0YXVyYW50cy52YWx1ZS5maWx0ZXIoY3JlYXRlRmlsdGVyKHF1ZXJ5U3RyaW5nKSlcbiAgICA6IHJlc3RhdXJhbnRzLnZhbHVlXG4gIC8vIGNhbGwgY2FsbGJhY2sgZnVuY3Rpb24gdG8gcmV0dXJuIHN1Z2dlc3Rpb25zXG4gIGNiKHJlc3VsdHMpXG59XG5jb25zdCBjcmVhdGVGaWx0ZXIgPSAocXVlcnlTdHJpbmc6IHN0cmluZykgPT4ge1xuICByZXR1cm4gKHJlc3RhdXJhbnQ6IFJlc3RhdXJhbnRJdGVtKSA9PiB7XG4gICAgcmV0dXJuIChcbiAgICAgIHJlc3RhdXJhbnQudmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwXG4gICAgKVxuICB9XG59XG5jb25zdCBsb2FkQWxsID0gKCkgPT4ge1xuICByZXR1cm4gW1xuICAgIHsgdmFsdWU6ICd2dWUnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZScgfSxcbiAgICB7IHZhbHVlOiAnZWxlbWVudCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9lbGVtZW50JyB9LFxuICAgIHsgdmFsdWU6ICdjb29raW5nJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2Nvb2tpbmcnIH0sXG4gICAgeyB2YWx1ZTogJ21pbnQtdWknLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvbWludC11aScgfSxcbiAgICB7IHZhbHVlOiAndnVleCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVleCcgfSxcbiAgICB7IHZhbHVlOiAndnVlLXJvdXRlcicsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlLXJvdXRlcicgfSxcbiAgICB7IHZhbHVlOiAnYmFiZWwnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL2JhYmVsL2JhYmVsJyB9LFxuICBdXG59XG5cbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtOiBSZXN0YXVyYW50SXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZyhpdGVtKVxufVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICByZXN0YXVyYW50cy52YWx1ZSA9IGxvYWRBbGwoKVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1hdXRvY29tcGxldGVcbiAgICB2LW1vZGVsPVwic3RhdGUxXCJcbiAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaFwiXG4gICAgY2xlYXJhYmxlXG4gICAgY2xhc3M9XCJpbmxpbmUtaW5wdXQgdy01MFwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgSW5wdXRcIlxuICAgIEBzZWxlY3Q9XCJoYW5kbGVTZWxlY3RcIlxuICAgIHBsYWNlbWVudD1cInRvcC1zdGFydFwiXG4gICAgc3R5bGU9XCJtYXJnaW4tdG9wOiAzMDBweFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1、点击下拉框;
2、输入搜索的条件

### What is Expected?

下拉列表应该贴近 下拉框

### What is actually happening?

下拉列表 仍在 初始位置

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed by #10104
