### ISSUE TITLE
[Style] [select] el-select第一次选中某个值 ，第二次展开，在选中这个值，input框里面文字会出现一个背景颜色

### ISSUE THREAD

**Issue by ezewu** [element-plus/element-plus#10384]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html)

### Steps to reproduce

打开官网 el-select组件，二次打开都选中一个值

### What is Expected?

input文字 没有背景颜色

### What is actually happening?

input文字 文字有一个背景颜色

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
maybe fix in #10381

**Comment by xiaoxian521** [comment]
[fix](https://github.com/element-plus/element-plus/commit/f77716f1e83f578eb2913663acdafa9f5df62a32)
