### ISSUE TITLE
[Component] [switch] el-switch 组件 before-change 属性死循环

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#10385]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Microsoft Edge 107.0.1418.26`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbGlzdCA9IHJlYWN0aXZlKFtcbiAge1xuICAgIGlzRGlzYWJsZWQ6IGZhbHNlLFxuICAgIGxvYWRpbmc6IGZhbHNlLFxuICB9LFxuICB7XG4gICAgaXNEaXNhYmxlZDogZmFsc2UsXG4gICAgbG9hZGluZzogZmFsc2UsXG4gIH0sXG4gIHtcbiAgICBpc0Rpc2FibGVkOiBmYWxzZSxcbiAgICBsb2FkaW5nOiBmYWxzZSxcbiAgfSxcbl0pXG5cbmNvbnN0IGxvZ3MgPSByZWFjdGl2ZShbXSlcblxuY29uc3QgdXBkYXRlSXNEaXNhYmxlZCA9IChyb3cpID0+IHtcbiAgcm93LmxvYWRpbmcgPSB0cnVlXG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4ge1xuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgbG9ncy5wdXNoKCfllYrvvIHmiJHooqvosIPnlKjkuobllYrvvIHvvIHvvIEnKVxuICAgICAgcm93LmxvYWRpbmcgPSBmYWxzZVxuICAgICAgcmV0dXJuIHJlc29sdmUodHJ1ZSlcbiAgICB9LCAxMDAwKVxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiPlxuICAgIGxvYWRpbmc6IHt7IGl0ZW0ubG9hZGluZyB9fSB8IGlzRGlzYWJsZWQ6IHt7IGl0ZW0uaXNEaXNhYmxlZCB9fVxuICAgIDxlbC1zd2l0Y2hcbiAgICAgIHYtbW9kZWw9XCJpdGVtLmlzRGlzYWJsZWRcIlxuICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgIDpsb2FkaW5nPVwiaXRlbS5sb2FkaW5nXCJcbiAgICAgIDpiZWZvcmVjaGFuZ2U9XCJ1cGRhdGVJc0Rpc2FibGVkKGl0ZW0pXCJcbiAgICAvPlxuICA8L2Rpdj5cbiAgXG4gIDxkaXYgdi1mb3I9XCJpdGVtIGluIGxvZ3NcIj5cbiAgICB7e2l0ZW19fVxuICA8L2Rpdj5cbiAgXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce
```
<script setup lang="ts">
import { ref, reactive, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const list = reactive([
  {
    isDisabled: false,
    loading: false,
  },
  {
    isDisabled: false,
    loading: false,
  },
  {
    isDisabled: false,
    loading: false,
  },
])

const logs = reactive([])

const updateIsDisabled = (row) => {
  row.loading = true
  return new Promise((resolve) => {
    setTimeout(() => {
      logs.push('啊！我被调用了啊！！！')
      row.loading = false
      return resolve(true)
    }, 1000)
  })
}
</script>

<template>
  <div v-for="item in list">
    loading: {{ item.loading }} | isDisabled: {{ item.isDisabled }}
    <el-switch
      v-model="item.isDisabled"
      size="small"
      :loading="item.loading"
      :beforechange="updateIsDisabled(item)"
    />
  </div>
  
  <div v-for="item in logs">
    {{item}}
  </div>
  
</template>
```

### What is Expected?

可正常使用

### What is actually happening?

发生死循环

### Additional comments

_(empty)_

**Comment by WangJincheng4869** [comment]
在这里补充一下我对此功能的使用场景：

查询某个列表，列表中的数据可以启用或者禁用。会用到此功能，这个死循环的bug一直存在，过去都是使用change事件代替实现。但是change事件不会阻止切换状态，如果失败会闪一下....
![动画](https://user-images.githubusercontent.com/41162158/199674364-5a47420b-b71e-48b8-9078-6a3ddd2ca32b.gif)

**Comment by init-qy** [comment]
see #9692

**Comment by WangJincheng4869** [comment]
> see #9692

感谢，之前搜索关键字「el-switch before-change」竟然没有搜到。
