### ISSUE TITLE
Doc about space has inconsistency

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1040]
![image](https://user-images.githubusercontent.com/38392315/102584375-4b7b8d00-4141-11eb-8d03-795e19e62094.png)

**Comment by JeremyWuuuuu** [comment]
Sorry.. I've made some mistakes when writing docs, could you help with that?

**Comment by kooriookami** [comment]
> Sorry.. I've made some mistakes when writing docs, could you help with that?

Yes, which is correct?
`8px 12px 16px 20px` or `4px 8px 12px 16px`

**Comment by JeremyWuuuuu** [comment]
The last one.
