### ISSUE TITLE
El autocomplete does not work properly

### ISSUE THREAD

**Issue by gameruleCEO** [element-plus/element-plus#1041]
![image](https://user-images.githubusercontent.com/32796170/102588417-600f5380-4148-11eb-8542-319a46884c59.png)

**Comment by JeremyWuuuuu** [comment]
Could you provide us reproduce steps, also with actual behavior and expected behavior?

**Comment by gameruleCEO** [comment]
> Could you provide us reproduce steps, also with actual behavior and expected behavior?

就是官网例子，在线运行
![image](https://user-images.githubusercontent.com/32796170/102596829-b7b3bc00-4154-11eb-8f3b-18cc772d7c5b.png)

**Comment by bastarder** [comment]
thanks , i find that , demo work on `vue@3.0.3` bug not work on `vue@3.0.4`

**Comment by gameruleCEO** [comment]
> thanks , i find that , demo work on `vue@3.0.3` bug not work on `vue@3.0.4`

but my project use vue@3.0.4 has this bug too.
The code is given by the official website.
![image](https://user-images.githubusercontent.com/32796170/102756077-4ec58180-43aa-11eb-87ec-c0a5229fa394.png)

**Comment by JeremyWuuuuu** [comment]
https://github.com/vuejs/vue-next/issues/2737 check this out.

**Comment by JeremyWuuuuu** [comment]
They have had this issue for like 20days, and they didn't give a hotfix on this issue, so there is nothing we can do.

**Comment by muhammeddemir** [comment]
I downgrade from **vue@3.0.4** to **vue@3.0.3** it works now.

**Comment by gameruleCEO** [comment]
> I downgrade from **vue@3.0.4** to **vue@3.0.3** it works now.

ok,I try it

**Comment by zazzaz** [comment]
this should have been fixed in `vue@3.0.5` https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8

**Comment by 0x1af2aec8f957** [comment]
Personally, the framework should try to avoid using private APIs that Vue does not expose or disclose, and these APIs are very likely to change
