### ISSUE TITLE
[Component] [popover] el-popover中  visible 和v-model:visible 会有表现上的区别

### ISSUE THREAD

**Issue by cdbEvan** [element-plus/element-plus#10425]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `Google Chrome 00.0.4896.60/ win10`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgdmlzaWJsZTIgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+XG4gICAg5L2/55SodmlzaWJsZSAgPT09PT0+IOeCueWHu+aMiemSruaJjeaYvuekuu+8jOeCueWHu+WPlua2iOaJjea2iOWkse+8jOeCueWHu+epuueZveWkhOS4jeS8mua2iOWksVxuICA8L2gxPlxuICA8ZWwtcG9wb3ZlciA6dmlzaWJsZT1cInZpc2libGVcIiBwbGFjZW1lbnQ9XCJ0b3BcIiA6d2lkdGg9XCIxNjBcIj5cbiAgICA8cD5BcmUgeW91IHN1cmUgdG8gZGVsZXRlIHRoaXM/PC9wPlxuICAgIDxkaXYgc3R5bGU9XCJ0ZXh0LWFsaWduOiByaWdodDsgbWFyZ2luOiAwXCI+XG4gICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIHRleHQgQGNsaWNrPVwidmlzaWJsZSA9IGZhbHNlXCI+Y2FuY2VsPC9lbC1idXR0b24+XG4gICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwidmlzaWJsZSA9IGZhbHNlXCJcbiAgICAgICAgPmNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgPlxuICAgIDwvZGl2PlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gdHJ1ZVwiPkRlbGV0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbiAgPGRpdj5cbiAgICA9PT09PT09PT09PT09PT09PT09PT09PT09PVxuICA8L2Rpdj5cbiAgPGRpdj5cbiAgICA9PT09PT09PT09PT09PT09PT09PT09PT09PVxuICA8L2Rpdj5cbiAgPGRpdj5cbiAgICA9PT09PT09PT09PT09PT09PT09PT09PT09PVxuICA8L2Rpdj5cbiAgPGgxPlxuICAgIOS9v+eUqHYtbW9kZWw6IHZpc2libGUgID09PT09PiAg56e75YWl5oyJ6ZKu5bCx5pi+56S65LqG77yM56e75Ye65oyJ6ZKu5bCx6ZqQ6JeP5LqGXG4gIDwvaDE+XG4gIDxlbC1wb3BvdmVyIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGUyXCIgcGxhY2VtZW50PVwidG9wXCIgOndpZHRoPVwiMTYwXCI+XG4gICAgPHA+QXJlIHlvdSBzdXJlIHRvIGRlbGV0ZSB0aGlzPzwvcD5cbiAgICA8ZGl2IHN0eWxlPVwidGV4dC1hbGlnbjogcmlnaHQ7IG1hcmdpbjogMFwiPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0ZXh0IEBjbGljaz1cInZpc2libGUyID0gZmFsc2VcIj5jYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlID0gZmFsc2VcIlxuICAgICAgICA+Y29uZmlybTwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgPC9kaXY+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUyID0gdHJ1ZVwiPkRlbGV0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const visible = ref(false)
const visible2 = ref(false)
</script>

<template>
  <h1>
    使用visible  =====> 点击按钮才显示，点击取消才消失，点击空白处不会消失
  </h1>
  <el-popover :visible="visible" placement="top" :width="160">
    <p>Are you sure to delete this?</p>
    <div style="text-align: right; margin: 0">
      <el-button size="small" text @click="visible = false">cancel</el-button>
      <el-button size="small" type="primary" @click="visible = false"
        >confirm</el-button
      >
    </div>
    <template #reference>
      <el-button @click="visible = true">Delete</el-button>
    </template>
  </el-popover>
  <div>
    ==========================
  </div>
  <div>
    ==========================
  </div>
  <div>
    ==========================
  </div>
  <h1>
    使用v-model: visible  =====>  移入按钮就显示了，移出按钮就隐藏了
  </h1>
  <el-popover v-model:visible="visible2" placement="top" :width="160">
    <p>Are you sure to delete this?</p>
    <div style="text-align: right; margin: 0">
      <el-button size="small" text @click="visible2 = false">cancel</el-button>
      <el-button size="small" type="primary" @click="visible = false"
        >confirm</el-button
      >
    </div>
    <template #reference>
      <el-button @click="visible2 = true">Delete</el-button>
    </template>
  </el-popover>
</template>

### What is Expected?

visible 和v-model:visible 表现的效果是一致的

### What is actually happening?

实际上2种传参达到了不一样的效果，不知道是bug还是设计上刻意为了，还是说本来就是这样的，是我太菜了，望回复

### Additional comments

实际上2种传参达到了不一样的效果，不知道是bug还是设计上刻意为了，还是说本来就是这样的，是我太菜了，望回复

**Comment by init-qy** [comment]
受控模式与非受控模式
可以看这个例子 [tooltip](https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F)

这是native-ui的解释，原理是一样的 [native-ui](https://www.naiveui.com/zh-CN/light/docs/controlled-uncontrolled)

**Comment by chenxch** [comment]
@cdbEvan hello，对于visible是否还有不明白的地方哈

**Comment by cdbEvan** [comment]
懂了懂了，谢谢

**Comment by chenxch** [comment]
那我先关闭这个issue了哈~

**Comment by cdbEvan** [comment]
嗯呐
