### ISSUE TITLE
[Component] [select-v2] el-select-v2无法正常显示placeholder

### ISSUE THREAD

**Issue by kiisapo** [element-plus/element-plus#10447]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.19`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCBjcmVhdGVWTm9kZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCwgRWxTZWxlY3RWMiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgaWQ6IDxudW1iZXIgfCBzdHJpbmc+Jydcbn0pO1xuICBcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHsgdmFsdWU6IDEsIGxhYmVsOiAnb3B0aW9uczEnIH0sXG4gIHsgdmFsdWU6IDIsIGxhYmVsOiAnb3B0aW9uczInIH0sXG4gIHsgdmFsdWU6IDMsIGxhYmVsOiAnb3B0aW9uczMnIH1cbl07XG4gIFxuZnVuY3Rpb24gb25DbGljaygpe1xuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAndGVzdCcsXG4gICAgZHJhZ2dhYmxlOiB0cnVlLFxuICAgIHNob3dDbG9zZTogdHJ1ZSxcbiAgICBzaG93Q2FuY2VsQnV0dG9uOiB0cnVlLFxuICAgIGNhbmNlbEJ1dHRvblRleHQ6ICflj5Yg5raIJyxcbiAgICBjb25maXJtQnV0dG9uVGV4dDogJ+ehriDlrponLFxuICAgIG1lc3NhZ2U6ICgpID0+IHtcbiAgICAgIGNvbnN0IHJlbmRlciA9IGNyZWF0ZVZOb2RlKFxuICAgICAgICBFbFNlbGVjdFYyLCB7XG4gICAgICAgICAgY2xlYXJhYmxlOiB0cnVlLFxuICAgICAgICAgIGZpbHRlcmFibGU6IHRydWUsXG4gICAgICAgICAgb3B0aW9uczogb3B0aW9ucyxcbiAgICAgICAgICBhbGxvd0NyZWF0ZTogdHJ1ZSxcbiAgICAgICAgICBzdHlsZTogJ3dpZHRoOiAxMDAlJyxcbiAgICAgICAgICBwbGFjZWhvbGRlcjogJ+ivt+mAieaLqScsIC8v6L+Z6YeM5bey57uP6K6+572u5LqG6K+l5bGe5oCn77yM5L2G5piv5peg5rOV5pi+56S6XG4gICAgICAgICAgbW9kZWxWYWx1ZTogZm9ybS5pZCxcbiAgICAgICAgICBwb3BwZXJDbGFzczogJ2VsLXNlbGVjdC12Mi1jdXN0b20nLFxuICAgICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKCB2YWx1ZTogbnVtYmVyIHwgc3RyaW5nKSA9PiB7XG4gICAgICAgICAgICBmb3JtLmlkID0gdmFsdWU7XG4gICAgICAgICAgfVxuICAgICAgICB9KTtcbiAgICAgIFxuICAgICAgLyoqXG4gICAgICAvLyDop6PlhrNlbC1zZWxlY3QtdjLml6Dms5XmraPluLjmmL7npLpwbGFjZWhvbGRlcueahGJ1Z++8m1xuICAgICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIGNvbnN0IGVsID0gcmVuZGVyLmVsPy5xdWVyeVNlbGVjdG9yKCcuZWwtc2VsZWN0LXYyX19wbGFjZWhvbGRlcicpO1xuICAgICAgICAhZm9ybS5pZCAmJiBlbCAmJiAoZWwuaW5uZXJUZXh0ID0gJ+ivt+mAieaLqScpO1xuICAgICAgfSwgMCk7XG4gICAgICAqL1xuICAgICAgXG4gICAgICByZXR1cm4gcmVuZGVyO1xuICAgIH1cbiAgfSkuY2F0Y2goKCkgPT4gITEpO1xufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib25DbGlja1wiPuivt+eCueWHu+aIkTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

已提供复现环境，请参考：https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCBjcmVhdGVWTm9kZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCwgRWxTZWxlY3RWMiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgaWQ6IDxudW1iZXIgfCBzdHJpbmc+Jydcbn0pO1xuICBcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHsgdmFsdWU6IDEsIGxhYmVsOiAnb3B0aW9uczEnIH0sXG4gIHsgdmFsdWU6IDIsIGxhYmVsOiAnb3B0aW9uczInIH0sXG4gIHsgdmFsdWU6IDMsIGxhYmVsOiAnb3B0aW9uczMnIH1cbl07XG4gIFxuZnVuY3Rpb24gb25DbGljaygpe1xuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAndGVzdCcsXG4gICAgZHJhZ2dhYmxlOiB0cnVlLFxuICAgIHNob3dDbG9zZTogdHJ1ZSxcbiAgICBzaG93Q2FuY2VsQnV0dG9uOiB0cnVlLFxuICAgIGNhbmNlbEJ1dHRvblRleHQ6ICflj5Yg5raIJyxcbiAgICBjb25maXJtQnV0dG9uVGV4dDogJ+ehriDlrponLFxuICAgIG1lc3NhZ2U6ICgpID0+IHtcbiAgICAgIGNvbnN0IHJlbmRlciA9IGNyZWF0ZVZOb2RlKFxuICAgICAgICBFbFNlbGVjdFYyLCB7XG4gICAgICAgICAgY2xlYXJhYmxlOiB0cnVlLFxuICAgICAgICAgIGZpbHRlcmFibGU6IHRydWUsXG4gICAgICAgICAgb3B0aW9uczogb3B0aW9ucyxcbiAgICAgICAgICBhbGxvd0NyZWF0ZTogdHJ1ZSxcbiAgICAgICAgICBzdHlsZTogJ3dpZHRoOiAxMDAlJyxcbiAgICAgICAgICBwbGFjZWhvbGRlcjogJ+ivt+mAieaLqScsIC8v6L+Z6YeM5bey57uP6K6+572u5LqG6K+l5bGe5oCn77yM5L2G5piv5peg5rOV5pi+56S6XG4gICAgICAgICAgbW9kZWxWYWx1ZTogZm9ybS5pZCxcbiAgICAgICAgICBwb3BwZXJDbGFzczogJ2VsLXNlbGVjdC12Mi1jdXN0b20nLFxuICAgICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKCB2YWx1ZTogbnVtYmVyIHwgc3RyaW5nKSA9PiB7XG4gICAgICAgICAgICBmb3JtLmlkID0gdmFsdWU7XG4gICAgICAgICAgfVxuICAgICAgICB9KTtcbiAgICAgIFxuICAgICAgLyoqXG4gICAgICAvLyDop6PlhrNlbC1zZWxlY3QtdjLml6Dms5XmraPluLjmmL7npLpwbGFjZWhvbGRlcueahGJ1Z++8m1xuICAgICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIGNvbnN0IGVsID0gcmVuZGVyLmVsPy5xdWVyeVNlbGVjdG9yKCcuZWwtc2VsZWN0LXYyX19wbGFjZWhvbGRlcicpO1xuICAgICAgICAhZm9ybS5pZCAmJiBlbCAmJiAoZWwuaW5uZXJUZXh0ID0gJ+ivt+mAieaLqScpO1xuICAgICAgfSwgMCk7XG4gICAgICAqL1xuICAgICAgXG4gICAgICByZXR1cm4gcmVuZGVyO1xuICAgIH1cbiAgfSkuY2F0Y2goKCkgPT4gITEpO1xufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib25DbGlja1wiPuivt+eCueWHu+aIkTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

### What is Expected?

正常显示placeholder

### What is actually happening?

正常显示placeholder

### Additional comments

期望增加label-key属性，和value-key类似，3Q！

**Comment by holazz** [comment]
初始化时不要用空字符串

`const form = reactive({ id: '' })` => `const form = reactive({ id: undefined })`

参考 https://github.com/element-plus/element-plus/issues/10371

**Comment by kiisapo** [comment]
> 初始化时不要用空字符串
> 
> `const form = reactive({ id: '' })` => `const form = reactive({ id: undefined })`
> 
> 参考 #10371

确实有效，看来是我用法不对，3Q
