### ISSUE TITLE
How to carry out local development and debugging ?

### ISSUE THREAD

**Issue by cenmes** [element-plus/element-plus#1045]
"run website"  dose'nt work, it need to install element-plus, can't do local development and debugging

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/102595056-feec7d80-4151-11eb-9b03-5d29895e4ef7.png)
Please do read the `get started` section first. We have that written in the documentation.

**Comment by cenmes** [comment]
doc:  yarn website-dev:play
//source file: ./website/play/index.vue
 but don't have this file

> "run website" dose'nt work, it need to install element-plus, can't do local development and debugging

doc: yarn website-dev:play
//source file: ./website/play/index.vue
 but don't have this file

**Comment by JeremyWuuuuu** [comment]
We have remove the `play/index.vue` file in order to prevent user from submit that file in `git` objects. So you have to create that file yourself. If you can't find one, create one. That simple.
