### ISSUE TITLE
[Style] [table] 页面抖动问题[Page jitter]

### ISSUE THREAD

**Issue by k650dg4d2** [element-plus/element-plus#10481]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.20`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Link](本地实现官网样例)

### Steps to reproduce

一个控制弹窗的按钮，和一个宽度是全屏的表格。
[A button that controls the pop -up window, and a width is a full -screen table.]

### What is Expected?

元素和文字稳定不动[Elements and characters are stable]

### What is actually happening?

元素和页面抖动[Elements and Page Jitter]

### Additional comments

我没测试别的宽度是100%的组件，应该也会有这个问题。不只elmplus，还有arco design和naiveUI都有这个问题。都是vue3版本的。有没有一个统一解决方案呢。
[I did not test the other width of 100%, and I should have this problem.Not only Elmplus, but also Arco Design and Naiveui have this problem.They are all Vue3.Is there a unified solution?]

![VeryCapture_20221106231128](https://user-images.githubusercontent.com/32454224/200178855-804c8ce2-5eb8-428e-bf11-f16f523a665f.gif)

**Comment by Simon-He95** [comment]
这是因为滚动条出现消失导致的吧

**Comment by WangJincheng4869** [comment]
直接用滚动条插件，网页宽度不改变应该就没问题了。或者将dialog组件的`lock-scroll`属性设置为false试试

**Comment by k650dg4d2** [comment]
> 

html {
  width:100vw;
  overflow-x:hidden;
}
设置了这个属性，滚动条不消失也会颤抖。

**Comment by chenxch** [comment]
需要再次确认一下版本，之前特地针对lock-screen做了优化调整，目前ep官网稳定就不会出现抖动的情况。

**Comment by k650dg4d2** [comment]
> 

"vue": "^3.2.38" "element-plus": "^2.2.20", "@vitejs/plugin-vue": "^3.0.3",  "vite": "^3.0.9" 
这个lock-screen属性需要这么急添加才能防抖吗。我没添加。

**Comment by k650dg4d2** [comment]
> 



> 需要再次确认一下版本，之前特地针对lock-screen做了优化调整，目前ep官网稳定就不会出现抖动的情况。

![VeryCapture_20221109165216](https://user-images.githubusercontent.com/32454224/200784177-13ec82ff-2d67-4d8d-a2eb-dc0245360388.gif)

**Comment by chenxch** [comment]
lock-screen 是配合lock-scroll属性使用的，默认是已经在使用了，你方便提供个demo么

**Comment by chenxch** [comment]
> 可以直接看我的git仓库吗，我已经上传了一个elementplus的仓库。里面是我的demo。

找到了哈，进来把这个地址连接出来哈，我先看看

**Comment by chenxch** [comment]
加上以下样式即可
```css
html,body{
  width: 100%;
  height: 100%;
  margin: 0;
}
```

**Comment by chenxch** [comment]
在有滚动条的时候时候表格不会抖动了，其他还是有一些问题。

**Comment by chenxch** [comment]
修改的几个版本都会出现不满足其中一种的情况，如果不你介意将滚动条置于app内的话可以使用以下样式
```css
html,body{
  width: 100% !important;
  height: 100%;
  overflow: hidden;
  margin: 0;
}
#app{
  width: 100%;
  height: 100%;
  overflow-y: auto;
  max-width: none !important;
}
```

**Comment by k650dg4d2** [comment]
> 

这个设置可以完美解决。
