### ISSUE TITLE
[Component] [input] input框无法使用鼠标或者 ctrl + A 选中内容 / Input box cannot be selected with mouse or ctrl+A

### ISSUE THREAD

**Issue by code-xman** [element-plus/element-plus#10486]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.20`
- Browser / OS: `chrome 107.0.5304.88 / windows 21H2;  Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html)

### Steps to reproduce

creat an el-input;
start project;
You can enter content, but you can be selected with mouse or ctrl+A;

### What is Expected?

The input box can be selected with mouse or ctrl+A

### What is actually happening?

The input box cannot be selected with mouse or ctrl+A

### Additional comments

Link to minimal replication environment is the official website address.Because it can reproduce.
Besides, I didn't know it was a problem, or element did it on purpose. But I think someone might use this feature.

**Comment by init-qy** [comment]
Caused by #10390 

you can custom style by yourself

```
.el-input__inner::selection {
    background: #000
}
```

**Comment by geedys** [comment]
I also encountered the same problem. I could not use the mouse to select text content, nor could I double click to select it. Then I tried to go back to version 2.2.19, but there was no such problem. I did not know whether it was an official intention or a bug?

**Comment by MonkeyMaster** [comment]
input selection is misleading now, please fix it

**Comment by code-xman** [comment]
> Caused by #10390
> 
> you can custom style by yourself
> 
> ```
> .el-input__inner::selection {
>     background: #000
> }
> ```

You are right.  It solves the problem. 
But I think it's a little strange. We usually don't need to deal with it.

**Comment by lsguang0** [comment]
+ 1

**Comment by codingpp** [comment]
遇到了同样的问题

**Comment by chenxch** [comment]
fixed #10535
