### ISSUE TITLE
El-table bad display when i drag & drop headers column

### ISSUE THREAD

**Issue by BezMaster** [element-plus/element-plus#1048]
Hi,
I have an issue on my el-table. When i change the column width with my cursor by clicking in the el-table header.
Do you already know that ?

**Comment by justwiner** [comment]
Could you provide a demo by git repository? @BezMaster

**Comment by BezMaster** [comment]
In fact, i think this is due to width="200" on my columns. Cause, I want to lock the column width to 200px. 

When i change the column width with my cursor by clicking in the el-table header, the table try to keep column initial width to 200px and i think this is why a blank appears !

Sorry guys ;) My bad
