### ISSUE TITLE
[Component] [input] 【el-input】组件无法选择文字

### ISSUE THREAD

**Issue by jesse51076008** [element-plus/element-plus#10518]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.19`
- Browser / OS: `edge 106`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0IHZhbHVlPVwi6K+35bCd6K+V5L2/55So6byg5qCH5oiW6ZSu55uY6YCJ5oup6L+Z5Lqb5paH5a2XXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

【最小复现环境的链接】有代码

### What is Expected?

el-input可以选择文字

### What is actually happening?

el-input无法选择文字

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
It may be caused here https://github.com/element-plus/element-plus/commit/5830d0768386cf496cf7c414c7e86372ca60cae9

**Comment by chenxch** [comment]
same #10486
