### ISSUE TITLE
[Component] [tabs] tab v-model not correct

### ISSUE THREAD

**Issue by ac51300696** [element-plus/element-plus#10519]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.7`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHR5cGUgeyBUYWJzUGFuZUNvbnRleHQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG4gIGNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcblxuY29uc3QgaGFuZGxlQ2xpY2sgPSAodGFiOiBUYWJzUGFuZUNvbnRleHQsIGV2ZW50OiBFdmVudCkgPT4ge1xuICBtc2cudmFsdWUgPSBgYWN0aXZlTmFtZTogJHthY3RpdmVOYW1lLnZhbHVlfSwgY3VycnRhYjogJHt0YWIucGFuZU5hbWV9YFxufVxuY29uc3QgbXNnID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiBjbGFzcz1cImRlbW8tdGFic1wiIEB0YWItY2xpY2s9XCJoYW5kbGVDbGlja1wiIEB0YWJDaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+VXNlcjwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiQ29uZmlnXCIgbmFtZT1cInNlY29uZFwiPkNvbmZpZzwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiUm9sZVwiIG5hbWU9XCJ0aGlyZFwiPlJvbGU8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlRhc2tcIiBuYW1lPVwiZm91cnRoXCIgZGlzYWJsZWQ+VGFzazwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbiAgPGRpdj5cbiAgICB7e21zZ319XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

click tabs 

### What is Expected?

activeName equie currtab

### What is actually happening?

activeName not equie currtab

### Additional comments

_(empty)_

**Comment by tolking** [comment]
This is not a BUG, Because the `beforeLeave` attribute needs to be compatible, the value needs to be changed asynchronously

`tabClick` -> `update:modelValue` -> `tabChange`

Therefore, the value is old one in the tabClick event

**Comment by ac51300696** [comment]
I know why

But without the beforeLeave attribute, this looks like a bug

Considering that the vast majority of scenarios are without beforeLeave, why not wait beforeLeave and then emit update: modelValue

**Comment by ac51300696** [comment]
@tolking

**Comment by tolking** [comment]
This is the logic now, so as to ensure that the triggering sequence of events is consistent

**Comment by morance** [comment]
as above conversation i know the sequence of events is right， but  you should give the change log for everybody get know this change.

**Comment by ac51300696** [comment]
I still think this feature is counter intuitive, especially when there is no beforeLeave feature, can we discuss more about whether research can be handled better
@tolking
