### ISSUE TITLE
[Style] [dialog] el-dialog 组件使用class 自定义样式问题

### ISSUE THREAD

**Issue by trry-github** [element-plus/element-plus#10515]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `macOs 13.0`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Github Repo](https://github.com/trry-github/issue.git)

### Steps to reproduce

```vue
<script setup lang="ts">
import {ref} from 'vue'

const dialogVisible = ref<boolean>(false)
</script>

<template>
  <el-button @click="dialogVisible = true">open dialog</el-button>
  <el-dialog v-model="dialogVisible" class="custom-class" title="Tips">
    <span>It's a draggable Dialog</span>
    <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">Cancel</el-button>
        <el-button type="primary" @click="dialogVisible = false">
          Confirm
        </el-button>
      </span>
    </template>
  </el-dialog>
</template>

<style scoped>
.custom-class{
  background-color: #ff6700;
}
</style>

```

### What is Expected?

dialog 背景色应被改变

### What is actually happening?

样式无变化

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
由于dialog默认是挂在到body，所以`.custom-class`由于scoped的原因，无法在组件外生效，可以考虑将其写到全局

**Comment by trry-github** [comment]
> 由于dialog默认是挂在到body，所以`.custom-class`由于scoped的原因，无法在组件外生效，可以考虑将其写到全局

![image](https://user-images.githubusercontent.com/67309192/200457522-29ec2ab7-8827-435c-a364-d82895351f8d.png)
官方文档显示，并不是默认挂载到body上

**Comment by trry-github** [comment]
我的理解是，dialog 组件用到了 Teleport 组件，在使用时如果 template 多根元素中有 dialog 则 dialog 被当成单独组件挂载，跟当前组件是兄弟关系，故样式不能生效，但这样 自定义类名就失去了意义，建议官方重新解释 class 使用范围，或修复当前bug

**Comment by chenxch** [comment]
> > 由于dialog默认是挂在到body，所以`.custom-class`由于scoped的原因，无法在组件外生效，可以考虑将其写到全局
> 
> ![image](https://user-images.githubusercontent.com/67309192/200457522-29ec2ab7-8827-435c-a364-d82895351f8d.png) 官方文档显示，并不是默认挂载到body上

嗯， 也是要把样式写到全局哈，我认为这是一个使用vue的常识

**Comment by init-qy** [comment]
确切的说，scoped的作用是给css及dom加上一个唯一hash，以达到样式私有化的目的，这个过程发生在编译阶段。
el-dialog中，`.el-dialog`这个dom不会在编译阶段生成，而是后面动态添加的，因此没有这个hash，scoped样式会无法生效。可以说它类似与 v-html

>DOM content created with v-html **are not affected by scoped styles**, but you can still style them using deep selectors.
[vue docs](https://vuejs.org/api/sfc-css-features.html#scoped-css)

**Comment by trry-github** [comment]
> 确切的说，scoped的作用是给css及dom加上一个唯一hash，以达到样式私有化的目的，这个过程发生在编译阶段。 el-dialog中，`.el-dialog`这个dom不会在编译阶段生成，而是后面动态添加的，因此没有这个hash，scoped样式会无法生效。可以说它类似与 v-html
> 
> > DOM content created with v-html **are not affected by scoped styles**, but you can still style them using deep selectors.
> > [vue docs](https://vuejs.org/api/sfc-css-features.html#scoped-css)



如果是应为el-dialog 是编译后产生的为什么template 加一个根元素后，样式又可以生效呢

```vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
const dialogVisible = ref<boolean>(false)
</script>

<template>
  <div>
    <el-button @click="dialogVisible = true">open dialog</el-button>
    <el-dialog ref="dialog" v-model="dialogVisible" class="custom-class" title="Tips">
      <span>It's a draggable Dialog</span>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">Cancel</el-button>
          <el-button type="primary" @click="dialogVisible = false"> Confirm </el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
:deep(.custom-class) {
  background-color: #ff6700;
}
</style>

```

**Comment by chenxch** [comment]
你加了deep哦

**Comment by trry-github** [comment]
> > > 由于dialog默认是挂在到body，所以`.custom-class`由于scoped的原因，无法在组件外生效，可以考虑将其写到全局
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/67309192/200457522-29ec2ab7-8827-435c-a364-d82895351f8d.png) 官方文档显示，并不是默认挂载到body上
> 
> 嗯， 也是要把样式写到全局哈，我认为这是一个使用vue的常识

我不认为这是vue常识的问题，更像是 dialog 作者没有考虑到这个使用场景，虽然说放到全局可以正常使用

**Comment by trry-github** [comment]
> 你加了deep哦

el-dialog 如果放在template 下，使用 deep 也是无效的，你可以使用最小demo示例尝试下

**Comment by chenxch** [comment]
所以我一直在建议放在全局， 或许我们可以给dialog加个class的使用tips

**Comment by trry-github** [comment]
> 所以我一直在建议放在全局， 或许我们可以给dialog加个class的使用tips

这个回复，我是赞成的，全局是有效的，我只是对 Teleport 组件渲染有些疑惑

**Comment by chenxch** [comment]
> 这个回复，我是赞成的，全局是有效的，我只是对 Teleport 组件渲染有些疑惑

嗯，关于Teleport 组件的渲染目前vue参考那边也有一些讨论，例如cssvar等这些会失效的问题，目前似乎还一直没有进展

**Comment by trry-github** [comment]
> > 这个回复，我是赞成的，全局是有效的，我只是对 Teleport 组件渲染有些疑惑
> 
> 嗯，关于Teleport 组件的渲染目前vue仓库那边也有一些讨论，例如cssvar等这些会失效的问题，目前似乎还一直没有进展

感谢您的回复

**Comment by init-qy** [comment]
> el-dialog 如果放在template 下，使用 deep 也是无效的，你可以使用最小demo示例尝试下

这点可以很轻易地从编译后代码中看出来

css编译后
```
[data-v-472cff63] .custom-class {
  background-color: #ff6700;
}
```

加根节点后dom结构
![image](https://user-images.githubusercontent.com/59350883/200469893-33acdb05-2748-4a3d-b98a-c1ccf36b3240.png)

没有根节点后dom结构
![image](https://user-images.githubusercontent.com/59350883/200469785-d17ca0c5-907c-481b-8c83-5012830fe285.png)

**Comment by chenxch** [comment]
@trry-github @init-qy 感谢你们的反馈和回复科普，我相信加上tips后会帮助使用者减少很多不必要的困惑。🥰
