### ISSUE TITLE
[Bug Report] table column with v-for, the data changed, but the cols will not dispeared

### ISSUE THREAD

**Issue by ChainsDW** [element-plus/element-plus#1051]
### Element Plus version
1.0.1-beta.10

### OS/Browsers version
macOS big sur/ chrome

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/chainsdw/pen/YzGQJWq

### Steps to reproduce
example in this link u can see, press the button '-', the cols of table not be dispeared, so that, press the button ' ', the cols of table will appear repeated cols.

### What is Expected?
repair it

### What is actually happening?
like title

**Comment by Zhaocl1997** [comment]
yeah, i have met with this problem too

**Comment by JeremyWuuuuu** [comment]
cc @justwiner
