### ISSUE TITLE
[Component] [select] el-select 选择器使用 JSX 语法时，modelValue 未生效

### ISSUE THREAD

**Issue by rich1e** [element-plus/element-plus#10540]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.42`
- Element Plus Version: `2.2.20`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[线上示例](https://stackblitz.com/edit/vitejs-vite-ovwjkk?file=src/components/Select.vue)

[演示地址](https://vitejs-vite-ovwjkk--5173.local-credentialless.webcontainer.io/)

### Steps to reproduce

打开选择下拉框，选中其中一个值。

### What is Expected?

显示选中的值

### What is actually happening?

未显示选中的值

### Additional comments

element-plus 的组件能否编写一份 JSX 的使用文档？

https://github.com/element-plus/element-plus/blob/d72fd34b58632dc011749b9393d93e12a5e160d5/packages/components/select/src/select.vue#L316

**Comment by rich1e** [comment]
```vue
<script lang="tsx">
import { defineComponent, ref } from 'vue';
import { ElSelect,ElOption } from 'element-plus';

export default defineComponent({
  name: 'Select',
  setup() {
    const value = ref('');
    const options = [
      {
        value: 'Option1',
        label: 'Option1',
      },
      {
        value: 'Option2',
        label: 'Option2',
      },
      {
        value: 'Option3',
        label: 'Option3',
      },
    ];

    // 使用 modelValue 绑定后，下拉选择 option，没有获取到值
    // 请问这个问题要如何解决？
    return () => {
      return (
        <>
          <ElSelect
            placeholder={'please select your zone'}
            modelValue={value}
            onChange={($event) => {
              value.value = $event;
            }}
          >
            {options.map((item) => {
              return (
                <ElOption key={item.value} label={item.label} value={item} />
              );
            })}
          </ElSelect>
        </>
      )
    };
  }
})
</script>
```

**Comment by rich1e** [comment]
这个问题，看了下 `el-select` 的源码，modelValue，然后是通过 emit 触发更新。

https://github.com/element-plus/element-plus/blob/d72fd34b58632dc011749b9393d93e12a5e160d5/packages/components/select/src/select.vue#L575

但是如何转换成 `JSX` 语法，找了很久都不得解。
希望有人能解答，谢谢。

参考：
[Vue 3 Babel JSX 文档](https://github.com/vuejs/babel-plugin-jsx/blob/dev/packages/babel-plugin-jsx/README-zh_CN.md#v-model)

**Comment by chenxch** [comment]
[vue v-model](https://vuejs.org/guide/extras/render-function.html#v-model) JSX要自己写上update事件哦， 可以多了解一些JSX的使用方法。

**Comment by rich1e** [comment]
@chenxch 试了一下，修改成这样，组件可以工作，非常感谢🙏。

```vue
<ElSelect
  placeholder={'please select your zone'}
  modelValue={value}
  onChange={onChangeSelect}
  {...{
    'onUpdate:modelValue': ($event) => {
      value.value = $event.value;
    },
  }}
>
  {options.map((item) => {
    return (
      <ElOption key={item.value} label={item.label} value={item} />
    );
  })}
</ElSelect>
```
---

多问一句，`element-plus` 中，如果组件使用了 `v-model / modelValue` 属性，都可以通过触发 `update` 事件解决？
比如：`el-switch`

```vue
const value = ref(true);

const data = {
  disabled: false,
  activeText: 'switch',
  'onUpdate:modelValue': ($event: any) => {
    console.log('onUpdate 1#', $event);
    value.value = !$event.value;
  }
};

return <ElSwitch modelValue={value} {...data} />;
```

**结论：以上代码会报错，`el-switch` 的 `v-model / modelValue` 不能使用 ref 类型，默认为 `boolean`。**

---

看了下 `el-switch` 的源码，发现 `v-model / modelValue` 需要涉及以下参数和事件：

```vue
if (![props.activeValue, props.inactiveValue].includes(actualValue.value)) {
  emit(UPDATE_MODEL_EVENT, props.inactiveValue)
  emit(CHANGE_EVENT, props.inactiveValue)
  emit(INPUT_EVENT, props.inactiveValue)
}
```

```vue
const handleChange = () => {
  const val = checked.value ? props.inactiveValue : props.activeValue
  emit(UPDATE_MODEL_EVENT, val)
  emit(CHANGE_EVENT, val)
  emit(INPUT_EVENT, val)
  nextTick(() => {
    input.value!.checked = checked.value
  })
}
```

**所以，如果使用 `JSX` 语法编写逻辑，需要控制关联参数(inactiveValue / activeValue)和事件才能让组件正常工作？**

---

源码：

https://github.com/element-plus/element-plus/blob/d72fd34b58632dc011749b9393d93e12a5e160d5/packages/components/switch/src/switch.vue#L159~L163

https://github.com/element-plus/element-plus/blob/d72fd34b58632dc011749b9393d93e12a5e160d5/packages/components/switch/src/switch.vue#L174~L180

**Comment by chenxch** [comment]
按照vue的设计来说 `v-model` = `modelValue` + `onUpdate:modelValue`， 所以只有`modelValue`的时候，组件内部如何update都不会更新到modelValue。
- 结论：以上代码会报错，el-switch 的 v-model / modelValue 不能使用 ref 类型，默认为 boolean。
这个是你写错了，正确应该是
```
...
return <ElSwitch modelValue={value.value} {...data} />;
```

**Comment by chenxch** [comment]
```
if (![props.activeValue, props.inactiveValue].includes(actualValue.value)) {
  emit(UPDATE_MODEL_EVENT, props.inactiveValue)
  emit(CHANGE_EVENT, props.inactiveValue)
  emit(INPUT_EVENT, props.inactiveValue)
}
```
这段代码，阅读下来应该是重置不规范的modelValue

**Comment by rich1e** [comment]
So，`el-switch` 组件，应该如何使用 `JSX` 语法编写？
