### ISSUE TITLE
[Component] [input] 版本 >= 2.2.10  input框 里面输入的文本 鼠标 无法选中文本

### ISSUE THREAD

**Issue by mabaoq123456** [element-plus/element-plus#10542]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.42`
- Element Plus Version: `2.2.20`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

**Comment by chenxch** [comment]
fixed #10535, Try to search first before asking questions.

**Comment by ryuhangyeong** [comment]
When checked with Element Play Playground, it appears to be a phenomenon that appears from 2.2.20.

## 2.2.20

<img width="989" alt="image" src="https://user-images.githubusercontent.com/27342882/200842313-5a1b39cc-6542-4802-b890-b6cdb72e2e3b.png">

## 2.2.19

<img width="787" alt="image" src="https://user-images.githubusercontent.com/27342882/200842428-7c4d88b6-23ff-4706-8b0a-0fe0dd83c437.png">
