### ISSUE TITLE
Vite in vite.config.js  Configure base: "package after". "/", Font Icon 404

### ISSUE THREAD

**Issue by lyt-Top** [element-plus/element-plus#1054]
#### 一、vite.config.js
```js
module.exports = {
	base: './',
	outDir: 'dist',
	minify: 'esbuild',
}
```
#### 二、打包后，http-server 本地运行，路径多了 `/_assets`，所以字体图标报404

完整路径：http://127.0.0.1:8081/_assets/_assets/element-icons.0bf2ea75.woff

请问有啥解决办法嘛？谢谢！

**Comment by gow1080p** [comment]
我也碰到这个问题了，请问如何解决

**Comment by limin04551** [comment]
我也遇到了这个问题,把base: './' 改成 base:'/'就没问题了,这样会有什么其他隐患吗
