### ISSUE TITLE
[Component] [input, input-number] el-input输入内容无法选中

### ISSUE THREAD

**Issue by LYao0919** [element-plus/element-plus#10553]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-input-number`

### Reproduction Link
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+aW5wdXQ8L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIFxuICAgPGgxPmlucHV0LXRleHRhcmVhPC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiB0eXBlPSd0ZXh0YXJlYScgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

### Steps to reproduce

el-input无法选中输入的内容；
当我想复制/全选input输入框中的值时不管是用鼠标还是command+A 都不行（但是当input type=‘Textarea’的时候又是可以的）

### What is Expected?

el-input能够正常复制信息

### What is actually happening?

el-input能够正常复制信息

### Additional comments

_(empty)_

**Comment by LYao0919** [comment]
![20221028-173048](https://user-images.githubusercontent.com/39789970/201016321-a5ba04c0-2d63-428a-bbfc-9af7d62c9176.jpeg)
补充一张图片

![20221110142802](https://user-images.githubusercontent.com/39789970/201016752-9ba002f3-54bd-4d70-b4bf-15512cd31fd9.gif)


https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+aW5wdXQ8L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIFxuICAgPGgxPmlucHV0LXRleHRhcmVhPC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiB0eXBlPSd0ZXh0YXJlYScgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/element-plus/element-plus/commit/d72fd34b58632dc011749b9393d93e12a5e160d5)
