### ISSUE TITLE
Fail to find where to set the first day of week in date-picker component.

### ISSUE THREAD

**Issue by tbwork** [element-plus/element-plus#1055]
The options is deprecated, and nothing more is present in the document to set the firstDayOfWeek option.

**Comment by zazzaz** [comment]
We will update the doc soon.

Ref https://github.com/element-plus/element-plus/issues/162#issuecomment-694793880

remove first-day-of-week, use Day.js locale instead,

All you have to do is to import Day.js locale like
```
import 'dayjs/locale/en'
dayjs.locale('en')
```

**Comment by tbwork** [comment]
@zazzaz Would you like to give out more details? How to set the first day of week by dayjs?

**Comment by zazzaz** [comment]
You can check af Afrikaans loclae as a reference

https://github.com/iamkun/dayjs/blob/dev/src/locale/af.js#L8

`weekStart: 1,`

That is to say, the first day of week of this locale is Monday.

**Comment by tbwork** [comment]
Thanks very much! Hope this can be updated to the document!~

**Comment by zazzaz** [comment]
You’re most welcome. And the doc will be updated soon

**Comment by zazzaz** [comment]
doc updated https://element-plus.org/#/en-US/component/i18n#set-day.js-locale

**Comment by pk8848597** [comment]
> doc updated https://element-plus.org/#/en-US/component/i18n#set-day.js-locale

Excuse me, this link can't be accessed normally
