### ISSUE TITLE
[i18n] 按需加载, 设置中文失败

### ISSUE THREAD

**Issue by toplyb** [element-plus/element-plus#10552]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.20`
- Browser / OS: `Opera/macOS`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-pagination`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuIGltcG9ydCB6aENuIGZyb20gXCJlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvemgtY24ubWpzXCI7XG5cbmNvbnN0IGRhdGUgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOmxvY2FsPVwiemhDblwiPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgICAgdi1tb2RlbD1cImRhdGVcIlxuICAgICAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICAgIC8+XG4gICAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
import zhCn from "element-plus/dist/locale/zh-cn.mjs";

const date = ref('')
</script>

<template>
  <el-config-provider :local="zhCn">
    <el-date-picker v-model="date" type="datetime"/>
  </el-config-provider>
</template>

```
选择日期的时候, 提示仍然是英文的, 而且控制台提示警告

### What is Expected?

解决问题

### What is actually happening?

解决问题

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
<el-config-provider : locale ="zhCn"></el-config-provider>
