### ISSUE TITLE
[Component] [input] All contents of the Input cannot be selected - 输入框文本无法选中

### ISSUE THREAD

**Issue by IkaroInory** [element-plus/element-plus#10571]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.44`
- Element Plus Version: `2.2.20`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Github Repo](https://github.com/IkaroInory/DevTrack-Web/tree/develop)

### Steps to reproduce

We provide a GitHub repository, please clone the 'develop' branch and build the Vue project. After running, go to 'http://localhost:<port, default is 8080>/dashboard' and click the '+' at 'My Tasks'( New Task), a pop-up dialog will provide the component in question for testing.
我们提供了GitHub仓库链接，请克隆“develop”分支，并构建好vue项目，运行后，进入http://localhost:<端口号，默认值一般为8080>/dashboard，点击“我的任务”中的加号（新建任务），弹出的对话框将提供有问题的组件供测试。

### What is Expected?

I can select all contents of the Input whether using shortcut keys(CTRL + A) or mouse.
我希望可以选中输入框内文本，无论是用快捷键还是鼠标。

### What is actually happening?

I cannot select contents.
我无法选中文本。

### Additional comments

The 2.2.19 version does not have this problem, but the contents of the Select can be selected. I hope that the contents of the Input can be selected, but the contents of the Select cannot be selected.
2.2.19版本中没有此问题，但是选择器（Select）的内容允许选中。我希望输入框（Input）的内容允许选中但选择器（Select）的内容不允许选中。

![image](https://user-images.githubusercontent.com/87926516/201268375-e0529f9d-5d47-432a-8bdc-b896c5446169.png)

**Comment by IkaroInory** [comment]
Please release the hot fix version as soon as possible, which is very important for us!

**Comment by chenxch** [comment]
fixed #10535, Please try to search first before asking questions.

We will arrange the release of the fixed version as soon as possible. Before the fixed version is released, you can add the following styles first.

```css
.el-input__inner::selection {
    background-color: #3390ff;
    color: #fff;
}
```

**Comment by IkaroInory** [comment]
> fixed #10535, Please try to search first before asking questions.
> 
> We will arrange the release of the fixed version as soon as possible. Before the fixed version is released, you can add the following styles first.
> 
> ```css
> .el-input__inner::selection {
>     background-color: #3390ff;
>     color: #fff;
> }
> ```

Thank you for your help and time. :)

**Comment by chenxch** [comment]
@IkaroInory 修复版本已经发布了哈。

**Comment by IkaroInory** [comment]
> @IkaroInory 修复版本已经发布了哈。

依赖已更新，辛苦啦
