### ISSUE TITLE
[Component] [date-picker] DatePicker组件的change事件无法触发

### ISSUE THREAD

**Issue by didoee** [element-plus/element-plus#10576]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.20`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/didoee/Demo)

### Steps to reproduce

```
<script setup>
import { ref } from 'vue';
const value1 = ref('');

const hanleChange = (value) => {
	console.log(value);
	value1.value = value;
};
</script>

<template>
	<el-date-picker
		:value="value1"
		@change="hanleChange"
		type="daterange"
		range-separator="To"
		start-placeholder="Start date"
		end-placeholder="End date"
	/>
</template>

```

### What is Expected?

DatePicker组件的能够触发change事件

### What is actually happening?

DatePicker组件的change事件无法触发

### Additional comments

_(empty)_

**Comment by tinyfind** [comment]
v-model

**Comment by didoee** [comment]
> v-model

就需要使用change事件

**Comment by tinyfind** [comment]
数据没有变化，就不会触发

**Comment by didoee** [comment]
> 数据没有变化，就不会触发

你把代码拉下来，别云，谢谢

**Comment by sleepyShen1989** [comment]
> > 数据没有变化，就不会触发
> 
> 你把代码拉下来，别云，谢谢

el-date-picker 是用v-model来绑定值得，可以再看下文档，改了我这里就能触发事件了
```
<script setup>
import { ref } from 'vue';
const value1 = ref('');

const hanleChange = (value) => {
	console.log(value);
	value1.value = value;
};
</script>

<template>
	<el-date-picker
		v-model="value1"
		@change="hanleChange"
		type="daterange"
		range-separator="To"
		start-placeholder="Start date"
		end-placeholder="End date"
	/>
</template>
```
