### ISSUE TITLE
[Component] [table] el-table斑马纹当表格有子级行时，显示有误

### ISSUE THREAD

**Issue by wubianluoye** [element-plus/element-plus#10583]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.20`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sRWxUYWJsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHRhYmxlID0gcmVmKFtcbiAge1xuICAgIGlkOjEsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbiAge1xuICAgIGlkOjIsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbiAge1xuICAgIGlkOjMsXG4gICAgbmFtZTogJ+W8oOaXoOW/jCcsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6MjIsXG4gICBcdFx0XHRuYW1lOiAn546L5LqM5bCPJyxcbiAgICBcdFx0YWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDoyMyxcbiAgIFx0XHRcdG5hbWU6ICfnjovkuozlsI8nLFxuICAgIFx0XHRhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOjI0LFxuICAgXHRcdFx0bmFtZTogJ+eOi+S6jOWwjycsXG4gICAgXHRcdGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgICAgfVxuICAgIF1cbiAgfSxcbiAge1xuICAgIGlkOjQsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbl0pXG4gIFxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gIFx0PGVsLXRhYmxlXG4gICAgICAgIDpkYXRhPVwidGFibGVcIlxuICAgICAgICBib3JkZXJcbiAgICAgICAgc3RyaXBlXG4gICAgICAgIHJvdy1rZXk9XCJpZFwiXG4gICAgICAgIDp0cmVlLXByb3BzPVwieyBjaGlsZHJlbjogJ2NoaWxkcmVuJyB9XCJcbiAgICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIGFsaWduPVwiY2VudGVyXCIgd2lkdGg9XCI3MFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJuYW1lXCIgYWxpZ249XCJjZW50ZXJcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiYWRkcmVzc1wiIGFsaWduPVwiY2VudGVyXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

使用tree-props设置了子级时，渲染斑马纹会把子级行也计算进去，导致父行斑马纹显示问题

### What is Expected?

父级、子级应分开显示斑马纹样式

### What is actually happening?

父级、子级统一计算显示斑马纹样式

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sRWxUYWJsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHRhYmxlID0gcmVmKFtcbiAge1xuICAgIGlkOjEsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbiAge1xuICAgIGlkOjIsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbiAge1xuICAgIGlkOjMsXG4gICAgbmFtZTogJ+W8oOaXoOW/jCcsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6MjIsXG4gICBcdFx0XHRuYW1lOiAn546L5LqM5bCPJyxcbiAgICBcdFx0YWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDoyMyxcbiAgIFx0XHRcdG5hbWU6ICfnjovkuozlsI8nLFxuICAgIFx0XHRhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDoyMjIsXG4gICAgICAgICAgICBuYW1lOiAn546L5LqM5bCPJyxcbiAgICAgICAgICAgIGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6MjMyLFxuICAgICAgICAgICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgICAgICAgICBhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICAgICAgICB9XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOjI0LFxuICAgXHRcdFx0bmFtZTogJ+eOi+S6jOWwjycsXG4gICAgXHRcdGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgICAgfVxuICAgIF1cbiAgfSxcbiAge1xuICAgIGlkOjQsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkSdcbiAgfSxcbl0pXG4gIFxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gIFx0PGVsLXRhYmxlXG4gICAgICAgIDpkYXRhPVwidGFibGVcIlxuICAgICAgICBib3JkZXJcbiAgICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgYWxpZ249XCJjZW50ZXJcIiB3aWR0aD1cIjcwXCIgZml4ZWQgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIm5hbWVcIiBhbGlnbj1cImNlbnRlclwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJhZGRyZXNzXCIgYWxpZ249XCJjZW50ZXJcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSA+XG4gIC5lbC10YWJsZV9fcm93Om5vdCguZWwtdGFibGVfX3Jvdy0tbGV2ZWwtMSk6bnRoLWNoaWxkKDJuKzIpOm5vdChbY2xhc3MqPWVsLXRhYmxlX19yb3ctLWxldmVsLV0pID4gdGQge1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtZmlsbC1jb2xvci1saWdodGVyKTtcbn1cbi5lbC10YWJsZV9fcm93LS1sZXZlbC0xOm50aC1jaGlsZChvZGQpIH4gLmVsLXRhYmxlX19yb3c6bm90KC5lbC10YWJsZV9fcm93LS1sZXZlbC0xKTpub3QoLmVsLXRhYmxlX19yb3ctLWxldmVsLTIpOm50aC1jaGlsZCgybisxKSA+IHRkICB7XG4gIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWVsLWZpbGwtY29sb3ItbGlnaHRlcik7XG4gIH1cbiAgXG4gIC5lbC10YWJsZV9fcm93LS1sZXZlbC0xOm50aC1jaGlsZChvZGQpIH4gLmVsLXRhYmxlX19yb3c6bm90KC5lbC10YWJsZV9fcm93LS1sZXZlbC0xKTpudGgtY2hpbGQoMm4rMikgPiB0ZCAge1xuICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWVsLWZpbGwtY29sb3ItYmxhbmspO1xuICB9XG4gPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

临时解决方案，取消使用组件的stripe属性，通过以下样式实现，组件的修复要从js上面调整判断逻辑。
```css
.el-table__row:not(.el-table__row--level-1):nth-child(2n+2):not([class*=el-table__row--level-]) > td {
 background-color: var(--el-fill-color-lighter);
}

.el-table__row--level-1:nth-child(odd) ~ .el-table__row:not(.el-table__row--level-1):not(.el-table__row--level-2):nth-child(2n+1) > td  {
 background-color: var(--el-fill-color-lighter);
}
  
.el-table__row--level-1:nth-child(odd) ~ .el-table__row:not(.el-table__row--level-1):nth-child(2n+2) > td  {
 background-color: var(--el-fill-color-blank);
}

```

**Comment by wubianluoye** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sRWxUYWJsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHRhYmxlID0gcmVmKFtcbiAge1xuICAgIGlkOjEsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgY2hpbGRyZW46IFtdXG4gIH0sXG4gIHtcbiAgICBpZDoyLFxuICAgIG5hbWU6ICfnjovkuozlsI8nLFxuICAgIGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgIGNoaWxkcmVuOiBbXVxuICB9LFxuICB7XG4gICAgaWQ6MyxcbiAgICBuYW1lOiAn5byg5peg5b+MJyxcbiAgICBhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDoyMixcbiAgIFx0XHRcdG5hbWU6ICfnjovkuozlsI8nLFxuICAgIFx0XHRhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOjIzLFxuICAgXHRcdFx0bmFtZTogJ+eOi+S6jOWwjycsXG4gICAgXHRcdGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6MjMsXG4gICBcdFx0XHRuYW1lOiAn546L5LqM5bCPJyxcbiAgICBcdFx0YWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgICB9XG4gICAgXVxuXG4gIH0sXG4gIHtcbiAgICBpZDo0LFxuICAgIG5hbWU6ICfnjovkuozlsI8nLFxuICAgIGFkZHJlc3M6ICfmoYPlm63mnZEnLFxuICAgIGNoaWxkcmVuOiBbXVxuICB9LFxuICB7XG4gICAgaWQ6NSxcbiAgICBuYW1lOiAn546L5LqM5bCPJyxcbiAgICBhZGRyZXNzOiAn5qGD5Zut5p2RJyxcbiAgICBjaGlsZHJlbjogW11cbiAgfSxcbiAge1xuICAgIGlkOjYsXG4gICAgbmFtZTogJ+eOi+S6jOWwjycsXG4gICAgYWRkcmVzczogJ+ahg+WbreadkScsXG4gICAgY2hpbGRyZW46IFtdXG4gIH0sXG5dKVxuXG5jb25zdCBzZXRSb3dDbGFzc05hbWUgPSAoe3JvdyB9KSA9PiB7XG4gIGNvbnN0IGlkeCA9IHRhYmxlLnZhbHVlLmZpbmRJbmRleChpdGVtID0+IGl0ZW0uaWQgPT09IHJvdy5pZClcbiAgaWYoaWR4Pi0xICYmIGlkeCUyID09IDEpIHtcbiAgICByZXR1cm4gJ2lzLWV2ZW4nXG4gIH1cbiAgcmV0dXJuXG59XG5cbmNvbnN0IHNldFJvd0NsYXNzTmFtZTIgPSAoe3Jvd30pID0+IHtcbiAgaWYoT2JqZWN0Lmhhc093bihyb3csJ2NoaWxkcmVuJykpIHtcbiAgICByZXR1cm4gJ2lzLXBhcmVudCdcbiAgfVxuICByZXR1cm5cbn1cbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PiAgICBcbiAgICA8cD5zZWN0aW9uMSDkvb/nlKhjc3PpgInmi6nlmahudGgtb2YtdHlwZShldmVuKei/mOaYr+aciemXrumimDwvcD5cbiAgXHQ8ZWwtdGFibGVcbiAgICAgICAgOmRhdGE9XCJ0YWJsZVwiXG4gICAgICAgIGJvcmRlclxuICAgICAgICA6cm93LWNsYXNzLW5hbWU9XCJzZXRSb3dDbGFzc05hbWUyXCJcbiAgICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgICBjbGFzcz1cInB0YWJsZVwiXG4gICAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiBhbGlnbj1cImNlbnRlclwiIHdpZHRoPVwiNzBcIiBmaXhlZCAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwibmFtZVwiIGFsaWduPVwiY2VudGVyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cImFkZHJlc3NcIiBhbGlnbj1cImNlbnRlclwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgICA8YnIvPlxuICAgIDxoci8+XG4gICAgPHA+c2VjdGlvbjIg5L2/55SodGFibGXmlbDnu4Tplb/luqYs6YCa6L+HaWTljrvliKTmlq3ooYzmmK/lkKbkuLrlpI3mlbDooYzvvIzlj6/ku6XkuoY8L3A+XG4gIFx0PGVsLXRhYmxlXG4gICAgICAgIDpkYXRhPVwidGFibGVcIlxuICAgICAgICBib3JkZXJcbiAgICAgICAgOnJvdy1jbGFzcy1uYW1lPVwic2V0Um93Q2xhc3NOYW1lXCJcbiAgICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgICBjbGFzcz1cInB0YWJsZTJcIlxuICAgICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgYWxpZ249XCJjZW50ZXJcIiB3aWR0aD1cIjcwXCIgZml4ZWQgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIm5hbWVcIiBhbGlnbj1cImNlbnRlclwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJhZGRyZXNzXCIgYWxpZ249XCJjZW50ZXJcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSBzY29wZWQ+XG4gIC5wdGFibGU+Pj4uZWwtdGFibGVfX2JvZHkgdGJvZHkgLmVsLXRhYmxlX19yb3cuaXMtcGFyZW50Om50aC1vZi10eXBlKGV2ZW4pIHRke1xuICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWVsLWZpbGwtY29sb3ItbGlnaHRlcik7XG4gIH1cbiAgXG4gIC5wdGFibGUyPj4+LmVsLXRhYmxlX19ib2R5IHRib2R5IC5lbC10YWJsZV9fcm93LmlzLWV2ZW4gdGR7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtZmlsbC1jb2xvci1saWdodGVyKTtcbiAgfVxuICAucHRhYmxlMj4+Pi5lbC10YWJsZV9fYm9keSB0Ym9keSAuZWwtdGFibGVfX3Jvdy5pcy1ldmVuLmhvdmVyLXJvdyB0ZHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1lbC10YWJsZS1yb3ctaG92ZXItYmctY29sb3IpO1xuICB9XG4gIFxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

通过@chenxch 大佬给出的思路，写了个demo，第一次尝试使用的是row-class-name属性给父级行添加一个css，然后再通过样式选择器nth-of-type(even)去设置偶数行样式，这个方法还是有问题，见demo的第一个例子。
然后想到可以使用渲染table数据的数组长度来给偶数行设置样式，通过该样式就能设置行背景了。见demo的第二个例子。但是需要有个唯一id来判断该行在数组的下标。
暂时我的解决方案就是这样了。

**Comment by chenxch** [comment]
@wubianluoye 👍

很不错的解决方案哈，组件内部的问题我这边也会尽快想办法处理掉哈
