### ISSUE TITLE
[Bug Report] 执行pnpm t 许多测试用例fail

### ISSUE THREAD

**Issue by sleepyShen1989** [element-plus/element-plus#10584]
### Element Plus version
2.2.17

### OS/Browsers version
win10 / chrome 107.0.5304.107

### Vue version
3.2.37

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/CONTRIBUTING.md

### Steps to reproduce
1. git clone
2. cd $THE_PROJECT_PATH_YOU_DOWNLOADED 
3. pnpm install
4. pnpm t

- 系统：Win10 专业版 版本号21H2 64位
- node: 18.12.1
- git: 2.38.1.windows.1
- pnpm: 7.15.0
- vitest: 0.12.6
- 代码分支：dev分支

### What is Expected?
跑测试用例没有失败

### What is actually happening?
跑测试用例大量失败（有部分成功）

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/201370800-bbf62bca-b6d5-447f-b6c2-621a0f6fa41f.png)
我只有本地的time-picker存在问题，其他都没问题，获取你应该从报错信息上先排查下设备环境存在的问题，也可以把相关信息发出来。

**Comment by sleepyShen1989** [comment]
错误总结：
- TpyeError: SupportedEventInterface is not a constructor
- el.addEventListener is not a function
- window.clearTimeout is not a function
- cannot read properties of undefined(reading 'userAgent')
- cannot read properties of undefined(reading 'now')
- window.requestAnimationFrame is not a function
- expected 'spy' to be called at least once

![1](https://user-images.githubusercontent.com/109908413/201450594-ab92de1a-7162-4661-8fce-94bbea8dd344.png)
![2](https://user-images.githubusercontent.com/109908413/201450598-edb2fb19-8f51-4132-b296-de768616e278.png)
![3](https://user-images.githubusercontent.com/109908413/201450601-1e8e7ee7-99be-40e8-bd5d-6c54aafb0acd.png)

**Comment by chenxch** [comment]
尝试使用16版本的node看下

**Comment by sleepyShen1989** [comment]
> 尝试使用16版本的node看下

换成16果然好了，感谢

刚看了Vitest的文档，说需要 Vite >=v3.0.0，我本来是往这方面去想了。
当然现在package.json里Vitest版本是写死的，所以没关系，如果要升级可能会产生问题，望知晓

**Comment by chenxch** [comment]
好的哈，那我就关闭这个issue了哈
