### ISSUE TITLE
[Component] [upload] When drag a file into el-upload, it can not upload and not perform props on-success, on-error and before-upload.

### ISSUE THREAD

**Issue by 497363983** [element-plus/element-plus#10590]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IFVwbG9hZEZpbGxlZCB9IGZyb20gXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmFzeW5jIGZ1bmN0aW9uIGNoZWNrKGZpbGUpIHtcbiAgaWYgKGZpbGUuc2l6ZSA+IDUgKiAxMDI0ICogMTAyNCkge1xuICAgIEVsTWVzc2FnZSh7XG4gICAgICB0eXBlOiBcImVycm9yXCIsXG4gICAgICBtZXNzYWdlOiBcIuaWh+S7tuWkp+Wwj+S4jeiDvei2hei/hzVNYlwiLFxuICAgIH0pO1xuICAgIHJldHVybiBmYWxzZTtcbiAgfVxuICBpZiAoZmlsZS50eXBlICE9PSBcImFwcGxpY2F0aW9uL3BkZlwiKSB7XG4gICAgRWxNZXNzYWdlKHtcbiAgICAgIHR5cGU6IFwiZXJyb3JcIixcbiAgICAgIG1lc3NhZ2U6IFwi5Y+q6IO95LiK5LygcGRm5paH5Lu2XCIsXG4gICAgfSk7XG4gICAgcmV0dXJuIGZhbHNlXG4gIH1cblxuICByZXR1cm4gZmlsZTtcbn1cblxuZnVuY3Rpb24gdXBsb2FkU3VjY2VzcyhyZXNwb25zZSkge1xuICBjb25zb2xlLmxvZyhyZXNwb25zZSk7XG4gIEVsTWVzc2FnZSh7XG4gICAgdHlwZTogXCJzdWNjZXNzXCIsXG4gICAgbWVzc2FnZTogXCLmlofku7bkuIrkvKDmiJDlip9cIixcbiAgfSk7XG59XG5cbmZ1bmN0aW9uIHVwbG9hZEZhaWx1cmUoZXJyLCBmaWxlKSB7XG4gIGNvbnNvbGUubG9nKGVycik7XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXVwbG9hZFxuICAgICAgYWN0aW9uPVwiXCJcbiAgICAgIGRyYWdcbiAgICAgIG11bHRpcGxlXG4gICAgICBhY2NlcHQ9XCJwZGZcIlxuICAgICAgOmxpbWl0PVwiMVwiXG4gICAgICA6b24tc3VjY2Vzcz1cInVwbG9hZFN1Y2Nlc3NcIlxuICAgICAgOm9uLWVycm9yPVwidXBsb2FkRmFpbHVyZVwiXG4gICAgICA6YmVmb3JlLXVwbG9hZD1cImNoZWNrXCJcbiAgICA+XG4gICAgICA8ZWwtaWNvbiBjbGFzcz1cImVsLWljb24tLXVwbG9hZFwiPjx1cGxvYWQtZmlsbGVkIC8+PC9lbC1pY29uPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGV4dFwiPuaLluWKqOaWh+S7tuiHs+atpOaIljxlbT7ngrnlh7vkuIrkvKA8L2VtPjwvZGl2PlxuICAgICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RpcFwiPuS7heiDveS4iuS8oHBkZuaWh+S7tu+8jOS4lOWkp+Wwj+S4jeWkp+S6jjVNYjwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { UploadFilled } from "@element-plus/icons-vue"
import { ref } from 'vue'

async function check(file) {
  if (file.size > 5 * 1024 * 1024) {
    ElMessage({
      type: "error",
      message: "文件大小不能超过5Mb",
    });
    return false;
  }
  if (file.type !== "application/pdf") {
    ElMessage({
      type: "error",
      message: "只能上传pdf文件",
    });
    return false
  }

  return file;
}

function uploadSuccess(response) {
  console.log(response);
  ElMessage({
    type: "success",
    message: "文件上传成功",
  });
}

function uploadFailure(err, file) {
  console.log(err);
}
</script>

<template>
   <el-upload
      action=""
      drag
      multiple
      accept="pdf"
      :limit="1"
      :on-success="uploadSuccess"
      :on-error="uploadFailure"
      :before-upload="check"
    >
      <el-icon class="el-icon--upload"><upload-filled /></el-icon>
      <div class="el-upload__text">拖动文件至此或<em>点击上传</em></div>
      <template #tip>
        <div class="el-upload__tip">仅能上传pdf文件，且大小不大于5Mb</div>
      </template>
    </el-upload>
</template>
```

### What is Expected?

When you drag a file onto el-uplod, it performs on-success, on-error, and before-upload props and uploads the file.

### What is actually happening?

After you drag a file onto el-uplod, it doesn't perform the on-success, on-error, and before-upload props and even not upload the file like it does when you click.

### Additional comments

_(empty)_

**Comment by 497363983** [comment]
It seems that if you set the `accept` prop and the drag feature will be failure

**Comment by ljf1834** [comment]
Please enter a valid `accept` attribute.

A valid case-insensitive filename extension, starting with a period (".") character. For example: `.jpg`, `.pdf`, or `.doc`.

 refer to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

**Comment by 497363983** [comment]
Oh, thanks! That's my mistake.
