### ISSUE TITLE
[Docs] [upload] 自定义缩略图点击删除和下载没有效果

### ISSUE THREAD

**Issue by XiaoRIGE** [element-plus/element-plus#10599]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.7`
- Element Plus Version: `2.2.21`
- Browser / OS: `Chrome  107.0.5304.107`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/upload.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E7%95%A5%E5%9B%BE)

### Steps to reproduce

官网地址就可以复现

### What is Expected?

点击删除，删掉当前上传图片

### What is actually happening?

点击删除，没有任何交互效果

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
事件具体内容要自己实现哦，按钮只是demo为了演示效果做的功能，具体的操作要自己在click事件中处理。
