### ISSUE TITLE
[Component] [menu, aside] <el-aside style="width: auto;"> aside 宽度设置自适应，menu撑开宽度的情况下，菜单都折叠时，菜单右边的展开符号被隐藏了

### ISSUE THREAD

**Issue by zui-coding** [element-plus/element-plus#10591]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.19`
- Browser / OS: `Chrome 已是最新版本 版本 107.0.5304.107`
- Build Tool: `Webpack`

### Related Component

- `el-menu`
- `el-aside`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBpc0NvbGxhcHNlID0gcmVmKHRydWUpXG5jb25zdCBoYW5kbGVPcGVuID0gKGtleSwga2V5UGF0aCkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXksIGtleVBhdGgpID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJpc0NvbGxhcHNlXCIgc3R5bGU9XCJtYXJnaW4tYm90dG9tOiAyMHB4XCI+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCJmYWxzZVwiPmV4cGFuZDwvZWwtcmFkaW8tYnV0dG9uPlxuICAgIDxlbC1yYWRpby1idXR0b24gOmxhYmVsPVwidHJ1ZVwiPmNvbGxhcHNlPC9lbC1yYWRpby1idXR0b24+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG4gICAgPGRpdiBjbGFzcz1cImNvbW1vbi1sYXlvdXRcIj5cbiAgICA8ZWwtY29udGFpbmVyPlxuICAgICAgPGVsLWFzaWRlIHN0eWxlPVwid2lkdGg6IGF1dG87XCI+XG4gICAgICA8ZWwtbWVudVxuICAgIGRlZmF1bHQtYWN0aXZlPVwiMlwiXG4gICAgOmNvbGxhcHNlPVwiaXNDb2xsYXBzZVwiXG4gICAgQG9wZW49XCJoYW5kbGVPcGVuXCJcbiAgICBAY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIxXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICA8ZWwtaWNvbj48bG9jYXRpb24gLz48L2VsLWljb24+XG4gICAgICAgIDxzcGFuPk5hdmlnYXRvciBPbmU8L3NwYW4+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgIDxlbC1pY29uPjxsb2NhdGlvbiAvPjwvZWwtaWNvbj5cbiAgICAgICAgPHNwYW4+TmF2aWdhdG9yIE9uZTwvc3Bhbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgIDwvZWwtc3ViLW1lbnU+XG4gIDwvZWwtbWVudT5cbiAgICAgIDwvZWwtYXNpZGU+XG4gICAgICA8ZWwtbWFpbj4xMjMxMjM8L2VsLW1haW4+XG4gICAgPC9lbC1jb250YWluZXI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

见复现环境连接

### What is Expected?

左边的折叠符号展示出来

### What is actually happening?

左边的折叠符号隐藏了

### Additional comments

_(empty)_

**Comment by ryuhangyeong** [comment]
## Suggest

The min width of el-aside designed in ep is 300px. 

<img width="617" alt="image" src="https://user-images.githubusercontent.com/27342882/201558162-69134166-fd56-4c8f-8e2c-13c5833d77f6.png">

There is no handling for your use case, so the defaults we set will be ignored.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/27342882/201558316-2b4e1b62-7cc6-4813-a24c-52fd0b1055a9.png">

Considering the basic use case, I think it is designed like this because it is more common to fix the width value (ex. 200px).

How about setting a fixed size? Can't that be in your use case?

**Comment by heart-to-the-sea** [comment]
外层元素设置的展开按钮并没有被撑开，原因是标签设置了绝对定位，并不会自动撑开容器，此时展开内存元素时，由于子元素的宽度大于titlle,容器被展开
如果想解决这个问题只需要在title元素上添加padding-right,使其撑起图标占位
效果如下
![image](https://user-images.githubusercontent.com/59409148/201569616-6e6fcd4c-c7dd-428e-95f8-6fcabfc10e10.png)
![image](https://user-images.githubusercontent.com/59409148/201569646-1cda1cce-3fc1-422f-8f8f-5368ef20a36e.png)

**Comment by heart-to-the-sea** [comment]
> 

我认为这个不算是BUG也不算是缺陷，不需要任何修复，因为slot中的内容是不确定的，不可能在组件内部去限定，这个应该由使用者自己去思考如何布局和组织代码

**Comment by zui-coding** [comment]
> Considering the basic use case, I think it is designed like this because it is more common to fix the width value (ex. 200px).
> 
> How about setting a fixed size? Can't that be in your use case?

It may be a matter of my habits. I don’t like to set the width of the outer box. As for the width, it depends on the content inside.

**Comment by tolking** [comment]
It might be a good idea to add `padding-right` style for `el-sub-menu__title`.
