### ISSUE TITLE
Can [feature request] support dynamic topic switching

### ISSUE THREAD

**Issue by qiaozhu** [element-plus/element-plus#1060]
### Existing Component
否

### Component Name
无

### Description
import ElementPlus from 'element-plus' 默认把element-plus/lib/theme-chalk/index.css样式加载了。
能不能不要导入样式，我需要动态切换主题 ，自己覆盖默认样式。
在2.0版本是一直在用这个功能，项目升级改造导致这个功能无效了。

**Comment by zazzaz** [comment]
没太看明白 请问这是什么问题呢 ？

**Comment by qiaozhu** [comment]
> 没太看明白 请问这是什么问题呢 ？

不好意思，是我babel.config配置错误导致，已经解决了。谢谢😊

就是想要实现 官网的在线生成主题功能
https://elementui.github.io/theme-chalk-preview/#/zh-CN
