### ISSUE TITLE
[i18n] [date-picker] `format` attribute not work

### ISSUE THREAD

**Issue by haiya6** [element-plus/element-plus#10600]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/haiya6/element-plus-datepiker-i18n-issue)

### Steps to reproduce

git clone
npm i
npm run dev

open browser...

### What is Expected?

Display the day of week in Chinese.

### What is actually happening?

Display the day of week in English.

### Additional comments

Or do I have other sulution?

**Comment by chenxch** [comment]
```js
import 'dayjs/locale/zh-cn'
```
