### ISSUE TITLE
[Bug Report] A weird bug seems related to el-select

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1061]
### Element Plus version
1.0.1-beta.10

### OS/Browsers version
chrome 87

### Vue version
3.0.4

### Reproduction Link
None, It can't be reproducted simply.

### What is Expected?
No error

### What is actually happening?
The single code is running normal. In a complex project, It reports an error. When I delete the code of `el-select`, it's normal.
```
<el-select v-model="value">
    <el-option v-for="item in list" :key="item.id" :label="item.name" :value="item.id"></el-option>
</el-select>
```
![image](https://user-images.githubusercontent.com/38392315/102756228-816f7a00-43aa-11eb-8212-88fa9d7a1cf7.png)
It seems the problem with `el-select`, the dropdown shows none, and the route can't jump.
It stands alone with no problem. Can't see what's causing it at all. Could it be a bug in vue?

**Comment by bastarder** [comment]
did you try this on `vue@3.0.3`? is that work correctly, it looks like same with the autocomplete bug

**Comment by JeremyWuuuuu** [comment]
This is a bug caused by Vue, you can see https://github.com/vuejs/vue-next/issues/2737
