### ISSUE TITLE
[Style] [input-number, input] 【el-input-number】与【el-input】并排的话，两者无法对其，差一个像素

### ISSUE THREAD

**Issue by jesse51076008** [element-plus/element-plus#10616]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.44`
- Element Plus Version: `2.2.21`
- Browser / OS: `chrome 107`
- Build Tool: `Vite`

### Related Component

- `el-input-number`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxlbC1pbnB1dCBzdHlsZT1cIndpZHRoOiAxMDBweDtcIiAvPlxuPGVsLWlucHV0LW51bWJlciAvPlxuPGVsLWlucHV0IHN0eWxlPVwid2lkdGg6IDEwMHB4O1wiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

【最小复现环境的链接】有代码

### What is Expected?

【el-input-number】与【el-input】并排可以对其

### What is actually happening?

【el-input-number】与【el-input】并排，el-input-number会高一个像素

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBzdHlsZT1cImJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjY2NjXCI+XG4gIFx0PGVsLWJ1dHRvbj5CdXR0b248L2VsLWJ1dHRvbj5cbiAgXHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIHN0eWxlPVwid2lkdGg6MjAwcHhcIiAvPlxuICBcdDxlbC1zZWxlY3Q+PC9lbC1zZWxlY3Q+XG5cdCAgPGVsLWRhdGUtcGlja2VyPjwvZWwtZGF0ZS1waWNrZXI+XG4gICAgPGVsLWlucHV0LW51bWJlcj48L2VsLWlucHV0LW51bWJlcj5cbiAgPC9kaXY+XG5cbiAgPGRpdj5cbiAgXHQ8ZWwtc2VsZWN0PjwvZWwtc2VsZWN0PlxuICBcdDxlbC1idXR0b24+QnV0dG9uPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuICBcbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by 1120040377** [comment]
![image](https://user-images.githubusercontent.com/25653199/202076493-55c60549-9fe4-438a-867b-e2de20f4a60c.png)
> 试了一下如果去掉 `el-input` 的 `vertical-align: middle`，会导致和设置了 `inline-flex` 的元素无法对齐

![image](https://user-images.githubusercontent.com/25653199/202077502-0e87c2ef-1f34-4163-a413-f536eab5b6dc.png)
> 我把两个图标删掉之后还是没有对其，其他元素对其是因为最外层包裹的元素都有 `vertical-align: middle`

**Comment by chenxch** [comment]
@1120040377 有兴趣的话可以关注下pr那边的进展哈😉

**Comment by MARIOMARUI** [comment]
我提交了一个 #10622

**Comment by chenxch** [comment]
@MARIOMARUI 可以关注一下 #10617 ，已经有同学pr了哈，不过我们还在讨论如何才能正确解决这个问题。

**Comment by MARIOMARUI** [comment]
#10639
