### ISSUE TITLE
[Component] [table] table 组件当有固定列时 safari (版本14.0.3 (16610.4.3.1.7)) 会有黑线

### ISSUE THREAD

**Issue by ChangeZhang** [element-plus/element-plus#10625]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#%E5%9B%BA%E5%AE%9A%E5%88%97)

### Steps to reproduce

官网 table组件 有固定列时 会有黑线

### What is Expected?

没有黑线

### What is actually happening?

有黑线

### Additional comments

_(empty)_

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6948367/202119095-b177be04-315e-4bfb-b3bf-329ca43a9f98.png">

**Comment by tolking** [comment]
This is a BUG of Safari browser, Link #9373.
