### ISSUE TITLE
[Component] [date-picker] Default working for type year in datepicker

### ISSUE THREAD

**Issue by MarcDOLF** [element-plus/element-plus#10626]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.27`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla Firefox 106`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuXG5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgeWVhclwiXG4gICAgICAgICAgICAgICAgICAgIHR5cGU9XCJ5ZWFyXCJcbiAgICAgICAgICAgICAgICAgICAgOmRlZmF1bHQtdmFsdWU9XCJuZXcgRGF0ZSgyMDI1LCAxLCAxKVwiICAgXG4gICAgICAgICAgICAgICAgICAgIC8+XG5cbiAgXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Click on datepicker, year selection is showing

### What is Expected?

Year 2025 is selected

### What is actually happening?

Year 2022 is selected

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
This is correct, it will show the year range which has `default-value`, you can change to 2011 or 2031 to see the specific effect
As you say `Year 2022 is selected`, it is actually the component's own effect of highlighting now, not selected

**Comment by MarcDOLF** [comment]
Thanks for the answer. My expectation would have been, that the default value is also preselected.

In that case, my suggestion would be to use a seperate flag on the date picker component, to specify a preselected date.
