### ISSUE TITLE
[Style] [image] The el-image preview is blocked by the el-table | el-image预览时被el-table遮挡

### ISSUE THREAD

**Issue by aizela** [element-plus/element-plus#10634]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 107.0.5304.107(windows10 21H2)`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaW1hZ2U6e1xuICAgICAgZmlsZV91cmw6J2h0dHBzOi8vZmlsZXMtZGV2LmRlZXJjYWwuY29tL3VwbG9hZHMvcGxhdGZvcm1zL2xvZ29fY29kZS82Njk5MzNlMWI4NzNlNzk4LmpwZydcbiAgICB9LFxuICAgIG5hbWU6J+WktOWDjycsXG4gICAgc3RhdHVzX2kxOG46J+WQr+eUqCcsXG4gICAgY3JlYXRlZF9hdDonMjAyMi0xMC0xMCdcbiAgfVxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJkYXRhXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY29kZVwiIGxhYmVsPVwi57yp55Wl5Zu+XCIgYWxpZ249XCJjZW50ZXJcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInsgcm93IH1cIj5cbiAgICAgICAgPGVsLWltYWdlXG4gICAgICAgICAgOnNyYz1cInJvdy5pbWFnZT8uZmlsZV91cmxcIlxuICAgICAgICAgIDpwcmV2aWV3LXNyYy1saXN0PVwiW3Jvdy5pbWFnZT8uZmlsZV91cmxdXCJcbiAgICAgICAgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwi5ZCN56ewXCIgYWxpZ249XCJjZW50ZXJcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXR1c19pMThuXCIgbGFiZWw9XCLnirbmgIFcIiBhbGlnbj1cImNlbnRlclwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY3JlYXRlZF9hdFwiIGxhYmVsPVwi5Yib5bu65pe26Ze0XCIgYWxpZ249XCJjZW50ZXJcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开链接,点击图片,启用el-image的预览功能,即可看到
just open the url

```js

<el-table-column prop="code" label="缩略图" align="center">
        <template #default="{ row }">
          <el-image
            style="height: 60px; margin: 0 auto"
            :src="row.image?.file_url"
            :preview-src-list="[row.image?.file_url]"
          />
        </template>
      </el-table-column>
      <el-table-column prop="name" label="名称" align="center" />
      <el-table-column prop="status_i18n" label="状态" align="center">
```

### What is Expected?

el-image图片正常预览,mask将页面遮挡,显示预览图片

### What is actually happening?

table遮挡了mask,将Mask的z-index调至9999依然无法解决
The <el-table/> bolcked the preview of <el-image/>, Even though I adjusted the z-index of image to 9999

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/52120594/202368428-6907bb36-d7d9-4d3f-907c-26dd95dc21af.png)

**Comment by chenxch** [comment]
请查阅文档 [table fqa](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)
![image](https://user-images.githubusercontent.com/23251408/202371844-e15a4f4a-b36a-434a-b905-01d126e6df0c.png)  (这个布里茨不错😄

**Comment by aizela** [comment]
> 请查阅文档 [table fqa](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89) ![image](https://user-images.githubusercontent.com/23251408/202371844-e15a4f4a-b36a-434a-b905-01d126e6df0c.png) (这个布里茨不错😄


可以了!十分感谢 (是英雄联盟Q版图标,google识图一下有很多来源)
