### ISSUE TITLE
[Style] [date-picker, button] el-date-picker el-button无法对齐

### ISSUE THREAD

**Issue by hovees** [element-plus/element-plus#10631]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICAgICAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgICAgICAgICAgICByYW5nZS1zZXBhcmF0b3I9XCJUb1wiXG4gICAgICAgICAgICAgICAgICBzdGFydC1wbGFjZWhvbGRlcj1cIlN0YXJ0IGRhdGVcIlxuICAgICAgICAgICAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgICAgICAgICAgICAgICAgLz5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlNlYXJjaDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgdmFsdWUyID0gcmVmKCcnKVxuXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG5cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICAgICAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgICAgICAgICAgICByYW5nZS1zZXBhcmF0b3I9XCJUb1wiXG4gICAgICAgICAgICAgICAgICBzdGFydC1wbGFjZWhvbGRlcj1cIlN0YXJ0IGRhdGVcIlxuICAgICAgICAgICAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgICAgICAgICAgICAgICAgLz5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlNlYXJjaDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgdmFsdWUyID0gcmVmKCcnKVxuXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG5cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### What is Expected?

组件对齐

### What is actually happening?

组件没对齐

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/22854075/202339370-20e91e89-9fde-492e-8639-29ad924a604c.png)

**Comment by init-qy** [comment]
link #10616
可能是相同问题

**Comment by MARIOMARUI** [comment]
#10639

**Comment by tolking** [comment]
This issue has been fixed
