### ISSUE TITLE
[Component] [select-v2] el-select-v2在使用prefix插槽时样式不对

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#10644]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `版本 102.0.5005.115（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cImxhcmdlXCJcbiAgID5cbiAgPHRlbXBsYXRlICNwcmVmaXg+XG4gICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tcmlnaHQ6NnB4XCI+XG4gICAgICDliY3nvIAgXG4gICAgPC9zcGFuPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtc2VsZWN0LXYyPlxuICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbml0aWFscyA9IFsnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaiddXG5cbmNvbnN0IHZhbHVlID0gcmVmKClcbmNvbnN0IG9wdGlvbnMgPSBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICB2YWx1ZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5leGFtcGxlLXNob3djYXNlIC5lbC1zZWxlY3QtdjIge1xuICBtYXJnaW4tcmlnaHQ6IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在使用prefix插槽时的样式不对

### What is Expected?

在使用prefix插槽时的样式应该正确

### What is actually happening?

在使用prefix插槽时的样式不对

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/203710620-82de31e8-edb4-4dc6-bea8-445935602027.png)

**Comment by agrass-GitHub** [comment]
与 el-select prefix 样式不一致，而且与 value 重叠

**Comment by Lionad-Morotar** [comment]
补充一条，如果使用了 multiple 属性，#prefix 和内容会换行，看起来非常奇怪：

![image](https://github.com/element-plus/element-plus/assets/26913795/876e26b9-294a-42cc-ba74-bfbc26b1919d)
