### ISSUE TITLE
[Bug Report] The built-in transition animation component has no effect

### ISSUE THREAD

**Issue by hsiangleev** [element-plus/element-plus#1064]
### Element Plus version
1.0.1-beta.10

### OS/Browsers version
google

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/hsiangleev/pen/wvzqrNm

### Steps to reproduce
1. copy from https://element-plus.org/#/zh-CN/component/transition

### What is Expected?
dom hides or shows animation

### What is actually happening?
There is no animation when dom is hidden, but there is animation when displayed

**Comment by zazzaz** [comment]
Hi, I think this might be a bug in Vue `3.0.4`, you can try `3.0.3` at the moment

```
<script src="https://unpkg.com/vue@3.0.3/dist/vue.global.js"></script>
```

**Comment by hsiangleev** [comment]
@zazzaz I tried it and it is indeed, thank you
