### ISSUE TITLE
[Component] [tree-select] data绑定的ref值中有disabled:true属性，实际未禁用

### ISSUE THREAD

**Issue by QuietHear** [element-plus/element-plus#10648]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.21`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/Lsehf5p3/7/)

### Steps to reproduce

如代码，配置了props

### What is Expected?

正确的禁用选项

### What is actually happening?

未禁用

### Additional comments

希望可以补充props的完整性：
  其中value属性没有标出；
  disabled属性未与children属性保持默认一致，必须填

**Comment by iDestin** [comment]
i will fix it

**Comment by TLovers** [comment]
线上打包貌似是原来的代码
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/26561694/231727780-21b36466-dc85-4101-98ea-713267273156.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/26561694/231727838-50467455-318e-487f-a46a-160e9d626d27.png">

**Comment by tolking** [comment]
@TLovers ^2.2.29
