### ISSUE TITLE
[Bug Report] class an style Attributes does not work in datePicker

### ISSUE THREAD

**Issue by garrettzxd** [element-plus/element-plus#1065]
### Element Plus version
1.0.1-beta.10

### OS/Browsers version
chrome 87.0.4280.88

### Vue version
3.0.4

### Reproduction Link
https://jsfiddle.net/zu5pqLv4/1/

### Steps to reproduce
<el-date-picker v-model="value" style="width: 300px" class="test"></el-date-picker>
real width is not 300px and also do not have test class

### What is Expected?
style and calss can effect

### What is actually happening?
class an style Attributes does not work in datePicker

**Comment by wukang0718** [comment]
dialog is also
