### ISSUE TITLE
[Component] [select-v2] select-v2 选项文字显示不全

### ISSUE THREAD

**Issue by YornQiu** [element-plus/element-plus#10652]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Chrome 107.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link
[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyIHYtbW9kZWw9XCJ2YWx1ZVwiIDpvcHRpb25zPVwib3B0aW9uc1wiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+PC9lbC1zZWxlY3QtdjI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAndGVzdF9vcHRpb25faXRlbV8wMDAwMDEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ3Rlc3Rfb3B0aW9uX2l0ZW1fMDAwMDAyJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICd0ZXN0X29wdGlvbl9pdGVtXzAwMDAwMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAndGVzdF9vcHRpb25faXRlbV8wMDAwMDQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ3Rlc3Rfb3B0aW9uX2l0ZW1fMDAwMDA1JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<img width="218" alt="image" src="https://user-images.githubusercontent.com/13913084/202636913-db6208d0-c2b5-42d8-8b51-20367056ae0f.png">
下拉框的宽度是固定的200px，因此选项无法显示完整，无法确定应该是哪个选项。

### What is Expected?

将选项文字显示完整，或提供title等方式

### What is actually happening?

选项文字显示不完整

### Additional comments

_(empty)_

**Comment by 1120040377** [comment]
[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpkaXNhYmxlZD1cIml0ZW0uZGlzYWJsZWRcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgICBkaXNhYmxlZDogdHJ1ZSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

没有复现，可以放一些代码示例吗

**Comment by YornQiu** [comment]
> 

是select-v2哦，不是select

**Comment by ynb9870701** [comment]
[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPiAgXG5cdDxlbC1zZWxlY3QtdjJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgcGxhY2Vob2xkZXI9XCLovpPlhaVcIlxuICAgIHN0eWxlPVwid2lkdGg6IDIwMHB4XCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICA+XG4gICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBpdGVtIH1cIj5cbiAgICAgIDxzcGFuPnt7IGl0ZW0ubGFiZWwgfX08L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1zZWxlY3QtdjI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICAgIGRpc2FibGVkOiB0cnVlLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

同问，也遇到问题超出显示了省略号，但是看不到详情

**Comment by DXD2019** [comment]
建议与select组件一样 自动宽度 而不是省略。或者增加选项。

**Comment by imf7** [comment]
这个问题影响还是很大的（用户天天吐槽下拉框内容全都长一样，看不到完整文字，没法选择），官方想办法解决一下吧，el-select显示是没问题的，但无法承载大量数据。

**Comment by Ale6333499** [comment]
同问，建议添加一个是否省略的内容的开关

**Comment by handsomeCarl** [comment]
<template #default="{ item }">
          <div :title="item ">
            <p>
              {{ item }}
            </p>
          </div>
        </template>     title 属性了解一下 悬停可以解决这个问题
