### ISSUE TITLE
[Component] [table] el-table 多选children  勾选子级 父级选中样式不能正确展示

### ISSUE THREAD

**Issue by hugselina2019** [element-plus/element-plus#10654]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.21`
- Browser / OS: `chrome  107.0.5304.88 / win11`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5sZXQgbXVsdGlwbGVTZWxlY3Rpb24gPSByZWYoW10pXG5sZXQgdGFibGVEYXRhMiA9IHJlZihbXG4gIHtcbiAgICBpZDogMzg4LFxuICAgIHVwZGF0ZUF0OiAnMjAyMi0wOS0xNCAxNDo1MzowNicsXG4gICAgc3RhdGlvbklkOiAnMDE1MV8wMDAwMTAnLFxuICAgIHN0YXRpb25OYW1lOiAn5Y+M5YWD6Lev6LCD5Y6L56uZJyxcbiAgICBkb21haW5Db2RlOiAnTkdTLkdHUycsXG4gICAgZG9tYWluTmFtZTogJ+mXqOermScsXG4gICAgbmFtZTogJ+WPjOWFg+i3r+iwg+WOi+ermScsXG4gICAgdHlwZTogJ+mXqOermScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDIxNDc0NzM2NjAsXG4gICAgICAgIGRhdGFJZDogJ1M2Rlg4UTg4UlhSJyxcbiAgICAgICAgZGF0YU5hbWU6ICflvpDmsp/liqDmsJTnq5nov5vnq5nljovlipvlj5jpgIHlmagnLFxuICAgICAgICB1bml0OiAnS1BhJyxcbiAgICAgICAgZG9tYWluQ29kZTogJ05HUy5HR1MnLFxuICAgICAgICBkb21haW5OYW1lOiBudWxsLFxuICAgICAgICBzdGF0aW9uSWQ6ICcwNTMxXzAwMDAwOScsXG4gICAgICAgIHN0YXRpb25OYW1lOiAn5b6Q5rKf6Zeo56uZJyxcbiAgICAgICAgbmFtZTogJ+W+kOayn+WKoOawlOermei/m+ermeWOi+WKm+WPmOmAgeWZqCcsXG4gICAgICAgIHR5cGU6ICfljovlipvlj5jpgIHlmagnXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMjE0NzQ3MzcxOSxcbiAgICAgICAgZGF0YUlkOiAnU0RFV05YODhSWFInLFxuICAgICAgICBkYXRhTmFtZTogJ+W+kOayn+mXqOermeWHuuermea4qeW6puWPmOmAgeWZqCcsXG4gICAgICAgIHVuaXQ6ICfihIMnLFxuICAgICAgICBkb21haW5Db2RlOiAnTkdTLkdHUycsXG4gICAgICAgIGRvbWFpbk5hbWU6IG51bGwsXG4gICAgICAgIHN0YXRpb25JZDogJzA1MzFfMDAwMDA5JyxcbiAgICAgICAgc3RhdGlvbk5hbWU6ICflvpDmsp/pl6jnq5knLFxuICAgICAgICBuYW1lOiAn5b6Q5rKf6Zeo56uZ5Ye656uZ5rip5bqm5Y+Y6YCB5ZmoJyxcbiAgICAgICAgdHlwZTogJ+a4qeW6puWPmOmAgeWZqCdcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiAyMTQ3NDczNzU1LFxuICAgICAgICBkYXRhSWQ6ICdTUjE4R1g4OFJYUicsXG4gICAgICAgIGRhdGFOYW1lOiAn5b6Q5rKf56uZ6L+H5ruk5Zmo5beu5Y6L5Y6L5Yqb5Y+Y6YCB5ZmoMicsXG4gICAgICAgIHVuaXQ6ICdLUGEnLFxuICAgICAgICBkb21haW5Db2RlOiAnTkdTLkdHUycsXG4gICAgICAgIGRvbWFpbk5hbWU6IG51bGwsXG4gICAgICAgIHN0YXRpb25JZDogJzA1MzFfMDAwMDA5JyxcbiAgICAgICAgc3RhdGlvbk5hbWU6ICflvpDmsp/pl6jnq5knLFxuICAgICAgICBuYW1lOiAn5b6Q5rKf56uZ6L+H5ruk5Zmo5beu5Y6L5Y6L5Yqb5Y+Y6YCB5ZmoMicsXG4gICAgICAgIHR5cGU6ICfov4fmu6Tlmajljovlt64nXG4gICAgICB9XG4gICAgXVxuICB9LFxuICB7XG4gICAgaWQ6IDM4NyxcbiAgICB1cGRhdGVBdDogJzIwMjItMDktMTQgMTQ6NTM6MDUnLFxuICAgIHN0YXRpb25JZDogJzAxNjFfMDAwMDE5JyxcbiAgICBzdGF0aW9uTmFtZTogJ+a1t+WwlOWkp+mBk+iwg+WOi+ermScsXG4gICAgZG9tYWluQ29kZTogJ05HUy5HR1MnLFxuICAgIGRvbWFpbk5hbWU6ICfpl6jnq5knLFxuICAgIG5hbWU6ICfmtbflsJTlpKfpgZPosIPljovnq5knLFxuICAgIHR5cGU6ICfpl6jnq5knLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAyMTQ3NDczNjgwLFxuICAgICAgICBkYXRhSWQ6ICdTRjlXS0JEOFJYUicsXG4gICAgICAgIGRhdGFOYW1lOiAn5rSb6Ziz5bCP5bqE6Zeo56uZLeesrOS6jOi3r+i2heWjsOazouW3ruWOi+WPmOmAgeWZqCcsXG4gICAgICAgIHVuaXQ6ICdLUGEnLFxuICAgICAgICBkb21haW5Db2RlOiAnTkdTLkdHUycsXG4gICAgICAgIGRvbWFpbk5hbWU6IG51bGwsXG4gICAgICAgIHN0YXRpb25JZDogJzA1MzFfMDAwMDA4JyxcbiAgICAgICAgc3RhdGlvbk5hbWU6ICfmtJvpmLMt5Y6C56uZLeWwj+W6hOmXqOermScsXG4gICAgICAgIGRhdGFNYXJrOiAnUEQnLFxuICAgICAgICBkYXRhVHh0OiAn56ys5LqM6Lev6LaF5aOw5rOi5beu5Y6LJyxcbiAgICAgICAgZGF0YVR5cGVDb2RlOiAnWUxic3EnLFxuICAgICAgICBkYXRhVHlwZU5hbWU6ICfov4fmu6Tlmajljovlt64nLFxuICAgICAgICBkYXRhR3JvdXA6ICfmtJvpmLPlsI/luoTpl6jnq5kt56ys5LqM6Lev6LaF5aOw5rOi5beu5Y6L5Y+Y6YCB5ZmoJyxcbiAgICAgICAgbmFtZTogJ+a0m+mYs+Wwj+W6hOmXqOermS3nrKzkuozot6/otoXlo7Dms6Llt67ljovlj5jpgIHlmagnLFxuICAgICAgICB0eXBlOiAn6L+H5ruk5Zmo5Y6L5beuJ1xuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDIxNDc0NzM2OTQsXG4gICAgICAgIGRhdGFJZDogJ1M3WlVZV0Q4UlhSJyxcbiAgICAgICAgZGF0YU5hbWU6ICfmtJvpmLPlsI/luoTpl6jnq5kt55yB54Wk5rWB6YeP6K6hJyxcbiAgICAgICAgdW5pdDogJ05twrMvaCcsXG4gICAgICAgIGRvbWFpbkNvZGU6ICdOR1MuR0dTJyxcbiAgICAgICAgc3RhdGlvbklkOiAnMDUzMV8wMDAwMDgnLFxuICAgICAgICBzdGF0aW9uTmFtZTogJ+a0m+mYsy3ljoLnq5kt5bCP5bqE6Zeo56uZJyxcbiAgICAgICAgZGF0YU1hcms6ICdGc3RkQ0lGQScsXG4gICAgICAgIGRhdGFUeHQ6ICfnnIHnhaTotoXlo7Dms6LmoIflhrXnnqzml7bmtYHph48nLFxuICAgICAgICBpbk91dDogbnVsbCxcbiAgICAgICAgZGF0YVR5cGVDb2RlOiAnRkxXTScsXG4gICAgICAgIGRhdGFUeXBlTmFtZTogJ+a1gemHj+iuoScsXG4gICAgICAgIGRhdGFHcm91cDogJ+a0m+mYs+Wwj+W6hOmXqOermS3nnIHnhaTmtYHph4/orqEnLFxuICAgICAgICBzZXRTaG93OiAyLFxuICAgICAgICBjcG1vQ29wOiAnMTAwMDM0MDAnLFxuICAgICAgICBuYW1lOiAn5rSb6Ziz5bCP5bqE6Zeo56uZLeecgeeFpOa1gemHj+iuoScsXG4gICAgICAgIHR5cGU6ICfmtYHph4/orqEnXG4gICAgICB9XG4gICAgXVxuICB9LFxuICB7XG4gICAgaWQ6IDM4NixcbiAgICB1cGRhdGVBdDogJzIwMjItMDktMTQgMTQ6NTI6MDQnLFxuICAgIHN0YXRpb25JZDogJzAxNjFfMDAwMDAyJyxcbiAgICBzdGF0aW9uTmFtZTogJ+e6ouefs+W0lumXqOermScsXG4gICAgbmFtZTogJ+adjuWxr+mXqOermScsXG4gICAgdHlwZTogJ+e6ouefs+W0lumXqOermScsXG4gICAgY2hpbGRyZW46IFtdXG4gIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVTZWxlY3Rpb25DaGFuZ2UgPSAodmFsKSA9PiB7XG4gIG11bHRpcGxlU2VsZWN0aW9uLnZhbHVlID0gdmFsXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiIFxuICAgIDpkYXRhPVwidGFibGVEYXRhMlwiIFxuICAgIHJvdy1rZXk9XCJpZFwiIFxuICAgIHJlc2VydmUtc2VsZWN0aW9uXG4gICAgQHNlbGVjdGlvbi1jaGFuZ2U9XCJoYW5kbGVTZWxlY3Rpb25DaGFuZ2VcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwi5Zy656uZ5ZCN56ewXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRvbWFpbkNvZGVcIiBsYWJlbD1cIuaMh+agh+WQjeensFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhcHBseVNjZW5lXCIgbGFiZWw9XCLlupTnlKjlnLDngrlcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwidXBkYXRlQXRcIiBsYWJlbD1cIuabtOaWsOaXtumXtFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkb21haW5OYW1lXCIgbGFiZWw9XCLnsbvlnotcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用 el-table-column type="selection" 设置 row-key， tableData包含子集children, 勾选子集的checkbox 父级无法正确展示。 测试后发现 只有tableData的第一级数据可以与table-header的checkbox正确联动。 子集children勾选与父级无联动

### What is Expected?

children正确联动

### What is actually happening?

无法联动

### Additional comments

填完 Element Plus Playground  一直提示链接to long ... 挺无语的  只能把复现步骤缩减了 

<img width="1280" alt="328de9115b2d7e89d310875370b3497" src="https://user-images.githubusercontent.com/20763416/202651460-9c95b4fe-f083-4c35-9196-73c628a04693.png">
期待可以像最外层一样 选中子集可以父级改变checkbox为未全选，如下图：

![image](https://user-images.githubusercontent.com/20763416/202652075-0697bdd4-4fbf-4ca1-97fd-e4232065b45b.png)

**Comment by tolking** [comment]
每一条数据应该是相互独立的内容，为什么需要保持联动？

**Comment by tolking** [comment]
要实现这种功能可能需要增加一个配置，像是 Cascader 中的 props.checkStrictly 属性。

**Comment by lin-shaojie** [comment]
我正也需要这么一个功能。请问有对应的计划开发吗？ @tolking

**Comment by cn-troy** [comment]
啥时候能合并进去啊...着急得很...

**Comment by tolking** [comment]
Table的审核可能会很慢。如果急需可以考虑本地构建使用

**Comment by nineaiyu** [comment]
都已经2024年了，这个功能还没被合并
