### ISSUE TITLE
[Style] [pagination] el-pagination 设置 layout="total,-> ,sizes, prev, pager, next, jumper"时布局错误

### ISSUE THREAD

**Issue by falcon-jin** [element-plus/element-plus#10664]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `chrome 107.0.5304.110  Linux x86_64`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuPGVsLXBhZ2luYXRpb24gYmFja2dyb3VuZCBsYXlvdXQ9XCJ0b3RhbCwtPiAsc2l6ZXMsIHByZXYsIHBhZ2VyLCBuZXh0LCBqdW1wZXJcIiA6dG90YWw9XCIxMDAwXCIgLz5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<el-pagination background layout="total,-> ,sizes, prev, pager, next, jumper" :total="1000" />

### What is Expected?

布局正确

### What is actually happening?

布局错误

### Additional comments

![image](https://user-images.githubusercontent.com/48880836/202729435-9d6648c8-5206-4725-bd62-9c89690a7256.png)

**Comment by falcon-jin** [comment]
2.2.21版本正常

**Comment by chenxch** [comment]
`.el-pagination__rightwrapper` 样式丢失导致
