### ISSUE TITLE
[Component] [select] [el-select] clearable attribute triggering change event

### ISSUE THREAD

**Issue by caio-2k** [element-plus/element-plus#10665]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHN0eWxlPVwibWFyZ2luOiAxMHB4O1wiIHBsYWNlaG9sZGVyPVwiU2VsZWN0IGEgcHJvZHVjdFwiIHNpemU9XCJsYXJnZVwiIGNsZWFyYWJsZSBAY2hhbmdlPVwiZ2V0UHJvZHVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxkaXY+XG4gICAgPHByZT57eyBwcm9kdWN0cyB9fTwvcHJlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3QgcHJvZHVjdHMgPSByZWYoKVxuXG5jb25zdCBnZXRQcm9kdWN0ID0gYXN5bmMgKCkgPT4ge1xuICBmZXRjaChgaHR0cHM6Ly9kdW1teWpzb24uY29tL3Byb2R1Y3RzLyR7dmFsdWUudmFsdWV9YClcbiAgICAudGhlbihyZXNwb25zZSA9PiByZXNwb25zZS5qc29uKCkpXG4gICAgLnRoZW4oZGF0YSA9PiAocHJvZHVjdHMudmFsdWUgPSBkYXRhKSk7XG59XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJzEnLFxuICAgIGxhYmVsOiAnUHJvZHVjdCAxJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnMicsXG4gICAgbGFiZWw6ICdQcm9kdWN0IDInLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1 - Click and change select options to see the expected behaviour.
3 - Click on clear icon to clear the select and see the change event been triggered

### What is Expected?

The select component only being cleared.

### What is actually happening?

The selection component is being cleaned up AND the change event is being triggered.

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
This is a normal behavior. Clearing is also an action feedback of a change. You can use the `value` to judge whether the change is caused by the clearing operation.

**Comment by caio-2k** [comment]
> This is a normal behavior. Clearing is also an action feedback of a change. You can use the `value` to judge whether the change is caused by the clearing operation.

That's exactly it, I was believing that it was a strange behavior of the change event.
That was my bad xD
I'm closing this topic, appreciate your help @chenxch !!
