### ISSUE TITLE
[Docs] [All] 官方文档 - 组件，组件搜索功能，点击搜索结果跳转到对应组件文档后，需要手动切换为中文

### ISSUE THREAD

**Issue by Mr-Lixiaoqaing** [element-plus/element-plus#10672]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `e.g.`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](http://element-plus.org/zh-CN/component/button.html)

### Steps to reproduce

1、选择中文
2、搜索任意组件，并点击跳转
3、语言变为英文

### What is Expected?

保持中文

### What is actually happening?

变为英文

### Additional comments

_(empty)_

**Comment by tolking** [comment]
文档搜索基于 Algolia，目前 Algolia 暂不支持多语言搜索。
