### ISSUE TITLE
[Docs] [All] 文档页面经常性503

### ISSUE THREAD

**Issue by Roixy** [element-plus/element-plus#10688]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.22`
- Browser / OS: `107.0.5304.10`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

https://element-plus.gitee.io/zh-CN/component/button.html

### What is Expected?

修改下nginx参数

### What is actually happening?

1

### Additional comments

多刷几个页面就会报503，比较影响看文档的使用体验，建议修改下nginx参数

**Comment by chenxch** [comment]
same #9196
