### ISSUE TITLE
[Style] 在按需导入(auto-import)下 ElMessage ElNotification ElMessageBox 样式丢失解决办法

### ISSUE THREAD

**Issue by hdw0504** [element-plus/element-plus#10684]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Chrome/107.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-message-box`
- `el-notification`

### Reproduction Link

[Github Repo](https://github.com/hdw0504/el-plus-auto-import-solution)

### Steps to reproduce

删掉手动引入的element-plus组件，如果不删除则没有样式
eg: import { ElMessageBox, ElMessage } from 'element-plus

### What is Expected?

有样式
has style

### What is actually happening?

无样式
no style

### Additional comments

注释掉或者删除引入后需要重启项目

**Comment by chenxch** [comment]
link #9214
Wish I could do a search before asking the question for a quick fix.🤝
