### ISSUE TITLE
[Component] [form-item, form] 当我基于el-input 开发组件库my-ui-input时，在另一个项目使用我开发的组件my-ui-input，表单校验（失败）无效

### ISSUE THREAD

**Issue by xukaishan** [element-plus/element-plus#10690]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.22`
- Browser / OS: `Chrome latest`
- Build Tool: `Vite`

### Related Component

- `el-form-item`
- `el-form`

### Reproduction Link

[Github Repo](https://github.com/xukaishan/el-demo)

### Steps to reproduce

https://github.com/xukaishan/el-demo
打包基于el-input开发的组件库如（my-ui-input）
 cd my-ui-lib
 npm i
 npm run build;
在此项目中使用my-ui-input组件
 cd my-app
 npm i
 npm run dev
运行项目点击第一个输入框，正常触发表单的规则校验；
点击第二个输入框，表单校验失败

### What is Expected?

基于el-input开发的组件库如（my-ui-input）可以正常进行表单校验

### What is actually happening?

封装的el-input表单校验失败，没有触发表单校验

### Additional comments

_(empty)_

**Comment by xukaishan** [comment]
![image](https://user-images.githubusercontent.com/44866370/202973521-79493eac-864d-417c-b61d-81848532c301.png)

**Comment by xukaishan** [comment]
不同项目中的Symbol('formItemContextKey')不一样导致该问题；基于 el-input 封装的已经打包好的组件与宿主项目中的el-form-item中的Symbol('formItemContextKey')不是同一个引用

**Comment by hminghe** [comment]
这个应该是 A 和 B 共同依赖同一个 element-plus， 就好像你对于依赖 vue 就独立依赖了。

**Comment by chenxch** [comment]
> 这个应该是 A 和 B 共同依赖同一个 element-plus， 就好像你对于依赖 vue 就独立依赖了。

这种场景或许可以考虑不进行编译引用，编译的话等于是2个element-plus包。

**Comment by xukaishan** [comment]
> > 这个应该是 A 和 B 共同依赖同一个 element-plus， 就好像你对于依赖 vue 就独立依赖了。
> 
> 
> 
> 这种场景或许可以考虑不进行编译引用，编译的话等于是2个element-plus包。

其实就算是同一个项目 我把el-input打包一次 再将form-item打包一次 在该项目中使用打包后的组件也会出现此问题 这对插件库开发者来说是有问题 考虑symbol 改为symbol.for 也不是最优方案 因为可能会出现其他库与此key重复的问题 或者采用原element向上查找的方式

**Comment by hminghe** [comment]
> > > 这个应该是 A 和 B 共同依赖同一个 element-plus， 就好像你对于依赖 vue 就独立依赖了。
> > 
> > 
> > 这种场景或许可以考虑不进行编译引用，编译的话等于是2个element-plus包。
> 
> 其实就算是同一个项目 我把el-input打包一次 再将form-item打包一次 在该项目中使用打包后的组件也会出现此问题 这对插件库开发者来说是有问题 考虑symbol 改为symbol.for 也不是最优方案 因为可能会出现其他库与此key重复的问题 或者采用原element向上查找的方式

打包的时候不要打`element-plus`打包进去， 用的那个项目去依赖`element-plus`，你看那个 vue 第三库是打包的时候把 vue 打包进去了？

**Comment by tolking** [comment]
Symbol('formItemContextKey') 本身就是唯一值，不存在重复的情况。

> 打包的时候不要把element-plus打包进去， 用的那个项目去依赖element-plus，你看那个 vue 第三库是打包的时候把 vue 打包进去了？

我看了下你的代码，上面说的是对的
