### ISSUE TITLE
[Component] [scrollbar] el-scrollbar组件在父容器高度变化后滚动条未更新，显示异常

### ISSUE THREAD

**Issue by favorite58** [element-plus/element-plus#10700]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.5`
- Element Plus Version: `2.1.5`
- Browser / OS: `Chrome/107.0.0.0 Safari/537.36  /  Windows NT 10.0; Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-scrollbar`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/scrollbar.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

官网基础用法示例，手动改写父容器的高度，滚动条显示异常，未进行响应的更新

### What is Expected?

父容器高度变化后，滚动条高度正常显示

### What is actually happening?

父容器高度变化后，滚动条还是原父容器高度的配置，未针对父容器的高度自适应变化

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/25808314/203019523-cbb9ea24-a6db-4b76-a4e5-f5d88f893f9f.png)

**Comment by kooriookami** [comment]
请使用 update 方法手动更新滚动条
