### ISSUE TITLE
ElementLocale.i18n is not a function

### ISSUE THREAD

**Issue by chenweifang4** [element-plus/element-plus#1070]
根据 [按需加载里定制 i18n](https://element-plus.gitee.io/#/an-xu-jia-zai-li-ding-zhi-i18n) 里面的做法

```js
// ...
import ElementLocale from 'element-plus/lib/locale'

//...
ElementLocale.i18n((key, value) => i18n.t(key, value))
```

从源码位置 [packages/locale/index.ts](packages/locale/index.ts) ，并没有 `i18n` 的方法导出

```js
export default { use, t }
```

**Comment by zazzaz** [comment]
ElementLocale.i18n is not ready yet and will be avaliable soon after vue-i18n release it's first rc release.

Sorry for the inconvince.

**Comment by JeremyWuuuuu** [comment]
Track this in #1209 , closing this due to duplication
