### ISSUE TITLE
[Component] [select-v2] el-select-v2组件placeholder不显示

### ISSUE THREAD

**Issue by coder-cv** [element-plus/element-plus#10701]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgIFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24ke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

当使用el-select-v2 组件时，无multiple属性时，placeholder不生效

### What is Expected?

placeholder 可显示

### What is actually happening?

placeholder 不显示

### Additional comments

_(empty)_

**Comment by ljf1834** [comment]
同样的demo将组件替换为`el-select`并不存在这样的问题，期望这两个组件一些行为可以表现一致

**Comment by jw-foss** [comment]
Well, `isEmpty` definitely made sense to me, but I wonder when its not a multi-select why would we bind value in array instead of primitives?

**Comment by ljf1834** [comment]
这样做避免了用户对初始值赋予不正确的类型而引起bug

**Comment by holazz** [comment]
> 这样做避免了用户对初始值赋予不正确的类型而引起bug

你好，我没太理解你说的 bug 是什么，可以详细描述一下吗？或者提供一个 demo

**Comment by ljf1834** [comment]
select-v2组件单选模式，modelValue应该传递一个null or undefined, 当用户传递一个非nil的值，导致select-v2判断存在初始值而不显示placeholder。[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgIFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24ke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)，看了select组件源码，对初始值做了重新定义。

> > 这样做避免了用户对初始值赋予不正确的类型而引起bug
> 
> 你好，我没太理解你说的 bug 是什么，可以详细描述一下吗？或者提供一个 demo

**Comment by holazz** [comment]
@ljf1834 哦我理解了，但是这个组件就是这样设计的，只有 null 和 undefined 才显示 placeholder。你可能需要自行处理。

**Comment by coder-cv** [comment]
@holazz 那这设计显然不合理，你可以试试如果有multiple这个属性，而你的初值为null和undefined的话，整个组件就报错了，难道初始值我还要根据multiple来做个判断嘛？

**Comment by holazz** [comment]
> @holazz 那这设计显然不合理，你可以试试如果有multiple这个属性，而你的初值为null和undefined的话，整个组件就报错了，难道初始值我还要根据multiple来做个判断嘛？

单选初始值为 null 或 undefined， 多选初始值为空数组。

**Comment by coder-cv** [comment]
@holazz 不失为一种解决方式，但是还是期望和el-select组件保持一致

**Comment by holazz** [comment]
> @holazz 不失为一种解决方式，但是还是期望和el-select组件保持一致

做了一些调整，等下个版本发布😊
