### ISSUE TITLE
[Style] [pagination] in el-pagination, layout "->" element dose not work styling

### ISSUE THREAD

**Issue by yeonjulee1005** [element-plus/element-plus#10711]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cxID0gcmVmKCdlbC1wYWdpbmF0aW9uIGRvc2Ugbm90IHdvcmtpbmcgbGF5b3V0IFwiLT5cIiwnKVxuY29uc3QgbXNnMiA9IHJlZignd2l0aG91dCBcIi0+XCIsIGl0IHN0eWxpbmcgd29ya2luZycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGgyPnt7IG1zZzEgfX08L2gyPlxuPGVsLXBhZ2luYXRpb25cbiAgOnRvdGFsPVwiMjBcIlxuICA6cGFnZS1zaXplcz1cIlsyMCwgNTAsIDEwMF1cIlxuICBsYXlvdXQ9XCJ0b3RhbCwgLT4sIHNpemVzLCBwcmV2LCBwYWdlciwgbmV4dFwiXG4vPlxuICBcbjxoMj57eyBtc2cyIH19PC9oMj5cbjxlbC1wYWdpbmF0aW9uXG4gIDp0b3RhbD1cIjIwXCJcbiAgOnBhZ2Utc2l6ZXM9XCJbMjAsIDUwLCAxMDBdXCJcbi8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

bugReport

### What is Expected?

A gap must occur between total quantity and size.
Styles must be inline.

### What is actually happening?

Style is broken.

### Additional comments

_(empty)_

**Comment by yeonjulee1005** [comment]
I checked in Nuxt 3.0.0 framework.

**Comment by init-qy** [comment]
You can add style like this
```css
  .el-pagination__rightwrapper{
    display: flex
  }
```

the layout components after `->` will be added in a div wrapper, it looks like so by design

**Comment by HeftyKoo** [comment]
Duplicate: #10664

下个版本会修复

**Comment by yeonjulee1005** [comment]
@HeftyKoo Thank you!! :)

**Comment by yeonjulee1005** [comment]
@init-qy
yes!
Aready apply you told! 
However, I report it because the style should be applied automatically.
`->` 

thank you for helping me!:)
