### ISSUE TITLE
[Style] [tree] el-tree 自定义节点内容，官网文档上演示有问题

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#10718]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs](http://element-plus.org/zh-CN/component/tree.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E5%86%85%E5%AE%B9)

### Steps to reproduce

可以看到演示地址上，使用 render-content 和 scoped slot 最终展示效果不一致，render-content 是正确的。
使用 playground 测试，可追溯到 2.2.16 版本是正常的，之后就一直有这问题

### What is Expected?

/

### What is actually happening?

/

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
caused by #9613

加下面的样式可以解决
```css
  .el-tree-node__label {
    width: 100%
  }
```
