### ISSUE TITLE
[Component] [tab-pane, select] 在tab-pane下使用select，select在展开状态时切换tab，select会闪动

### ISSUE THREAD

**Issue by daiyuanhao** [element-plus/element-plus#10717]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-tab-pane`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwidGFibmFtZVwiPlxuICBcdDxlbC10YWItcGFuZSBuYW1lPSdhJyBsYWJlbD1cImFhYVwiPlxuICAgIFx0IDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHNpemU9XCJsYXJnZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgPC9lbC10YWItcGFuZT5cbiAgXHQ8ZWwtdGFiLXBhbmUgbmFtZT0nYicgbGFiZWw9XCJiYmJcIj5cbiAgICBcdFx0PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcblxuY29uc3QgdGFibmFtZSA9IHJlZignYScpXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

select展开切换tab会闪动

### What is Expected?

不发生闪动

### What is actually happening?

出现闪动

### Additional comments

_(empty)_

**Comment by acyza** [comment]
可以把teleported改成false
