### ISSUE TITLE
[Bug Report] Behavior about Popover

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1072]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
Chrome87

### Vue version
3.0.4

### Reproduction Link
https://element-plus.org/#/zh-CN/component/popover

### Steps to reproduce
![image](https://user-images.githubusercontent.com/38392315/102837106-19ff0c00-4436-11eb-955c-230452acc59b.png)
1. Click `click 激活`
2. Click other button like `hover 激活`
3. Click the popover of `hover 激活`

### What is Expected?
When executing step 2 or 3, the popover of `click 激活` should be closed.
Summary: When clicking on other places, the popover with `trigger="click"` should be close correctly.

### What is actually happening?
After executing the steps, the popover of `click 激活` still shows.

You can refer to antd vue:
https://2x.antdv.com/components/popover-cn/

**Comment by JeremyWuuuuu** [comment]
Seems `v-click-outside` isn't doing its job.
