### ISSUE TITLE
[Component] [table, table-column] el-table 存在内存泄露、和element-ui表现不一致问题

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#10739]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICA8Q29tcD5cbiAgICBcbiAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyAkaW5kZXggfVwiPlxuICAgICBcdDx0ZXN0IDppbmRleD1cIiRpbmRleFwiIC8+XG4gICAgIDwvdGVtcGxhdGU+XG4gICAgPC9Db21wPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgIFx0PENvbXAxIC8+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBcbiAgaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSc7XG4gIGltcG9ydCBDb21wMSBmcm9tICcuL0NvbXAxLnZ1ZSc7XG4gIGltcG9ydCBUZXN0IGZyb20gJy4vdGVzdC52dWUnO1xuICBpbXBvcnQgeyByZWYgfSBmcm9tJ3Z1ZSc7XG5jb25zdCB0YWJsZURhdGEgPXJlZihbXSk7XG4gIFxuIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgdGFibGVEYXRhLnZhbHVlID0gW1xuICAgICB7XG4gICAgICAgXG4gICAgIH0sXG4gICAgIHtcbiAgICAgICBcbiAgICAgfVxuICAgXVxuIH0pXG4gIFxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRlc3QudnVlIjoiPHRlbXBsYXRlPlxuPGRpdj5cbiAgXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiAgaW1wb3J0IHtvbk1vdW50ZWQsIG9uVW5tb3VudGVkIH0gZnJvbSAndnVlJ1xuICBcbiAgY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wcyh7XG4gICAgaW5kZXg6IE51bWJlclxuICB9KVxuXG4gIG9uTW91bnRlZCgoKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ29uTW91bnRlZCB0ZXN0JywgcHJvcHMuaW5kZXgpXG4gIH0pXG4gIFxuICBvblVubW91bnRlZCgoKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ29uVW5tb3VudGVkJylcbiAgfSlcbiAgXG48L3NjcmlwdD5cbiIsIkNvbXAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCI+XG4gIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlZFwiPlxuICAgIDxzbG90IHYtYmluZD1cInNjb3BlZFwiIC8+XG4gIDwvdGVtcGxhdGU+XG4gIDwvZWwtdGFibGUtY29sdW1uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiBpbXBvcnQgdGVzdCBmcm9tICcuL3Rlc3QudnVlJztcbjwvc2NyaXB0PlxuIiwiQ29tcDEudnVlIjoiPHRlbXBsYXRlPlxuPGRpdj5cbiAgXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiAgaW1wb3J0IHtvbk1vdW50ZWQsIG9uVW5tb3VudGVkIH0gZnJvbSAndnVlJ1xuICBcbiAgY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wcyh7XG4gICAgaW5kZXg6IE51bWJlclxuICB9KVxuICBjb25zb2xlLmxvZygnb25Nb3VudGVkIGNvbXAxJywgcHJvcHMuaW5kZXgpXG4gIG9uTW91bnRlZCgoKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ29uTW91bnRlZCcsIHByb3BzLmluZGV4KVxuICB9KVxuICBcbiAgb25Vbm1vdW50ZWQoKCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKCdvblVubW91bnRlZCcpXG4gIH0pXG4gIFxuPC9zY3JpcHQ+XG4iLCJfbyI6e319)

### Steps to reproduce

data 为空数组的时候test 组件不应该渲染出来, data 有数据的时候test 组件也没有被卸载， 初步定位问题是在el-table-column 的render 阶段执行了一次this.$slots.default
也不应该出现$index 为-1 的情况

### What is Expected?

和element-ui 表现一致

### What is actually happening?

和element-ui 表现不一致、出现了内存无法释放的问题

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
![image](https://user-images.githubusercontent.com/33827314/203553880-1f94dab3-46ae-4d53-9bf9-de0b43c325e0.png)
我一直很疑惑render 阶段为什么要这样做

**Comment by gjfei** [comment]
#9727 这个相关的PR也并没有解决这个问题

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/element-plus/element-plus/issues/4434)
