### ISSUE TITLE
[Feature Request] 除常规var.scss中的样式外，其它大部分的组件样式无法新增或修改

### ISSUE THREAD

**Issue by wushuang5112** [element-plus/element-plus#10756]
### Existing Component
Yes

### Component Name
Table, Empty

### Description
通过https://element-plus.gitee.io/zh-CN/guide/theming.html#%E6%9B%B4%E6%8D%A2%E4%B8%BB%E9%A2%98%E8%89%B2了解到Theme的模板可以替换的，但是除了common/var.scss的样式可以修改外，如果我想修改Table Header的文字大小或Empty组件默认的背景色，却不知道如何修改，请问哪里有相关资料或示例么？

**Comment by kooriookami** [comment]
可以使用 ::v-deep() 覆盖样式
