### ISSUE TITLE
[Component] [popconfirm] popconfirm 设置with 不生效

### ISSUE THREAD

**Issue by liuwei1992** [element-plus/element-plus#10766]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.22`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-popconfirm`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wY29uZmlybVxuICAgIGNvbmZpcm0tYnV0dG9uLXRleHQ9XCJZZXNcIlxuICAgIGNhbmNlbC1idXR0b24tdGV4dD1cIk5vXCJcbiAgICA6aWNvbj1cIkluZm9GaWxsZWRcIlxuICAgIGljb24tY29sb3I9XCIjNjI2QTAwXCJcbiAgICB0aXRsZT1cIkFyZSB5b3Ugc3VyZSB0byBkZWxldGUgdGhpcz9cIlxuICAgIEBjb25maXJtPVwiY29uZmlybUV2ZW50XCJcbiAgICBAY2FuY2VsPVwiY2FuY2VsRXZlbnRcIlxuICAgICAgICAgICAgICAgICBjYW5jZWwtYnV0dG9uLXR5cGU9XCJ0ZXh0XCJcbiAgICAgICAgICAgICAgICAgOndpdGg9XCIyNzBcIlxuICA+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPkRlbGV0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wY29uZmlybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBJbmZvRmlsbGVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGNvbmZpcm1FdmVudCA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2NvbmZpcm0hJylcbn1cbmNvbnN0IGNhbmNlbEV2ZW50ID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnY2FuY2VsIScpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<template>
  <el-popconfirm
    confirm-button-text="Yes"
    cancel-button-text="No"
    :icon="InfoFilled"
    icon-color="#626A00"
    title="Are you sure to delete this?"
    @confirm="confirmEvent"
    @cancel="cancelEvent"
    cancel-button-type="text"
    :with="270"
  >
    <template #reference>
      <el-button>Delete</el-button>
    </template>
  </el-popconfirm>
</template>

<script setup lang="ts">
import { InfoFilled } from '@element-plus/icons-vue'

const confirmEvent = () => {
  console.log('confirm!')
}
const cancelEvent = () => {
  console.log('cancel!')
}
</script>
```

设置with:270 

### What is Expected?

宽度展示为270px

### What is actually happening?

宽度依然是150px

### Additional comments

_(empty)_

**Comment by btea** [comment]
属性名应该是 `width`, 而不是 `with`。
