### ISSUE TITLE
[Bug Report] el-popover component's visible-arrow doesn't work

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1076]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
chrome

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr

### Steps to reproduce
set visible-arrow property in el-popover

### What is Expected?
el-popover component's visible-arrow doesn't work

### What is actually happening?
Modify the official document. The official document shows that the visible arrow can be used to modify whether the arrow is displayed. However, I found that the source code contains (packages\popper\src\use-popper\defaults.ts）Use show arrow to control. You need to revise the instructions here to avoid misunderstanding

**Comment by JeremyWuuuuu** [comment]
It's a documentation error, it should be `show-arrow` instead of `visible-arrow`, fixed in #1080
