### ISSUE TITLE
[Bug Report] Drag ColorPicker will select other elements

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1077]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
Chrome 87

### Vue version
3.0.4

### Reproduction Link
https://element-plus.org/#/zh-CN/component/color-picker

### Steps to reproduce
![Video_2020-12-22_123742](https://user-images.githubusercontent.com/38392315/102850003-568d3080-4453-11eb-97d3-c62c3ff54027.gif)

### What is Expected?
When dragging exceed the panel, the back elements shouldn't be selected.

### What is actually happening?
The back text was selected.

**Comment by JeremyWuuuuu** [comment]
I think it was caused by not preventing default dragging behavior. Want a fix?

**Comment by JeremyWuuuuu** [comment]
@kooriookami , you happen to have a personal email? Could you send me an email via the email address on my profile page?

**Comment by kooriookami** [comment]
> @kooriookami , you happen to have a personal email? Could you send me an email via the email address on my profile page?

I send you an email, and what is it used for?

**Comment by JeremyWuuuuu** [comment]
> > @kooriookami , you happen to have a personal email? Could you send me an email via the email address on my profile page?
> 
> I send you an email, and what is it used for?

Invitation of being a maintainer of this project.
