### ISSUE TITLE
[Style] [select] 在移动端页面利用JS跳转到PC页面时，日期组件与下拉框选择组件样式融合在一起bug

### ISSUE THREAD

**Issue by JanYork** [element-plus/element-plus#10797]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.21`
- Browser / OS: `Win11 Edge`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Github Repo](https://github.com/JanYork/ToTimeMail)

### Steps to reproduce

浏览器调试控制台，开启移动端调试，进入移动端页面，然后取消移动端，进入PC端页面，此时需要手动刷新一下，页面为PC，选择信件类型的下拉框点击会同时弹出日期选择框

### What is Expected?

正常状态

### What is actually happening?

弹出了日期选择框

### Additional comments

我们是线上项目，pc页面：https://mail.totime.cn/toemail.html，移动页面：https://mail.totime.cn/toemailh.html，使用js做了跳转，宽度>760px，移动端会强制跳转到PC。
注：https://mail.totime.cn 主页存在两个按钮，一个电脑写信，一个手机写信，PC端点击手机写信会强制跳转到PC端，此时就会出现信件类型下拉框点击弹出日期选择框，但是如果点击的是电脑写信进入，则无此情况

**Comment by loosheng** [comment]
https://github.com/JanYork/ToTimeMail/blob/main/docs/page/Email.vue#L94-L102

```diff
+ <client-only>
             <el-date-picker v-model="data.form.dataTime" type="date" placeholder="选择未来" format="YYYY-MM-DD"
                            value-format="YYYY-MM-DD">
              <template #default="cell">
                <div class="cell" :class="{ current: cell.isCurrent }">
                  <span class="text">{{ cell.text }}</span>
                  <span v-if="isHoliday(cell)" class="holiday"/>
                </div>
              </template>
            </el-date-picker>
+ </client-only>

```

**Comment by loosheng** [comment]
@tolking Answers have been adopted and can be closed.
