### ISSUE TITLE
build的时候，报TS2300: Duplicate identifier 'event'.

### ISSUE THREAD

**Issue by btea** [element-plus/element-plus#10794]
### Discussed in https://github.com/element-plus/element-plus/discussions/10721

<div type='discussions-op-text'>

<sup>Originally posted by **ibabamu** November 22, 2022</sup>
build的时候，报下面的错误，有遇到过的吗

node_modules/element-plus/es/components/tree-v2/index.d.ts:97:511 - error TS2300: Duplicate identifier 'event'

</div>

**Comment by xiaoxian521** [comment]
it is ok

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/44761321/205229334-04a76fbe-2cff-4725-9ba6-09c0750d41bc.png">

**Comment by btea** [comment]
This problem seems to appear after the package release
https://cdn.jsdelivr.net/npm/element-plus@2.2.19/es/components/tree-v2/index.d.ts
![image](https://user-images.githubusercontent.com/24516654/205417817-090906f4-bc04-4337-bc51-c3110b8fb6e2.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/207604444-90f0756f-856c-4e8e-ad41-0a57f666df3b.png)
build pass
