### ISSUE TITLE
[Feature Request] tabs能否增加鼠标滚动？

### ISSUE THREAD

**Issue by vual** [element-plus/element-plus#10801]
### Existing Component
是

### Component Name
tabs

### Description
tab很多时，只有按钮无法满足需求，tabs能否增加鼠标滚动？
或者暴露更多的属性或方法，方便自定义实现。

**Comment by vual** [comment]
> 
用你的方法，有滚动了，但是有个新问题，增加tab时，不会自动滚到最新的tab。

**Comment by chenxch** [comment]
Try to do it yourself, use `edit` event to scroll to the far right.

**Comment by vual** [comment]
> Try to do it yourself, use `edit` event to scroll to the far right.

![image](https://user-images.githubusercontent.com/25891219/204417410-0323a4df-7a0c-43d8-a275-709c58caa0d7.png)
我看这边有个这个方法，可以用吗？怎么用？

**Comment by chenxch** [comment]
You can try it.

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHJlZj1cInRhYnNSZWZcIlxuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYnNSZWYgPSByZWYobnVsbClcbmxldCB0YWJJbmRleCA9IDJcbmNvbnN0IGVkaXRhYmxlVGFic1ZhbHVlID0gcmVmKCcyJylcbmNvbnN0IGVkaXRhYmxlVGFicyA9IHJlZihbXG4gIHtcbiAgICB0aXRsZTogJ1RhYiAxJyxcbiAgICBuYW1lOiAnMScsXG4gICAgY29udGVudDogJ1RhYiAxIGNvbnRlbnQnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWIgMicsXG4gICAgbmFtZTogJzInLFxuICAgIGNvbnRlbnQ6ICdUYWIgMiBjb250ZW50JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnVGFiIDNUYWIgM1RhYiAzVGFiIDNUYWIgM1RhYiAzJyxcbiAgICBuYW1lOiAnMycsXG4gICAgY29udGVudDogJ1RhYiAzIGNvbnRlbnQnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWIgNFRhYiA0VGFiIDRUYWIgNFRhYiA0VGFiIDQnLFxuICAgIG5hbWU6ICc0JyxcbiAgICBjb250ZW50OiAnVGFiIDQgY29udGVudCcsXG4gIH0sXG4gIHtcbiAgICB0aXRsZTogJ1RhYiA1VGFiIDVUYWIgNVRhYiA1VGFiIDVUYWIgNScsXG4gICAgbmFtZTogJzUnLFxuICAgIGNvbnRlbnQ6ICdUYWIgNSBjb250ZW50JyxcbiAgfSxcbl0pXG5cbmNvbnN0IGhhbmRsZVRhYnNFZGl0ID0gKHRhcmdldE5hbWU6IHN0cmluZywgYWN0aW9uOiAncmVtb3ZlJyB8ICdhZGQnKSA9PiB7XG4gIGlmIChhY3Rpb24gPT09ICdhZGQnKSB7XG4gICAgY29uc3QgbmV3VGFiTmFtZSA9IGAkeysrdGFiSW5kZXh9YFxuICAgIGVkaXRhYmxlVGFicy52YWx1ZS5wdXNoKHtcbiAgICAgIHRpdGxlOiAnTmV3IFRhYicsXG4gICAgICBuYW1lOiBuZXdUYWJOYW1lLFxuICAgICAgY29udGVudDogJ05ldyBUYWIgY29udGVudCcsXG4gICAgfSlcbiAgICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IG5ld1RhYk5hbWVcbiAgICBuZXh0VGljaygoKT0+e1xuICAgICAgXHQgY29uc3QgbmF2RG9tID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLmVsLXRhYnNfX25hdicpXG4gICAgbmF2RG9tLnNjcm9sbExlZnQgPSBuYXZEb20uY2xpZW50V2lkdGhcbiAgICB9KVxuICAgXG4gIH0gZWxzZSBpZiAoYWN0aW9uID09PSAncmVtb3ZlJykge1xuICAgIGNvbnN0IHRhYnMgPSBlZGl0YWJsZVRhYnMudmFsdWVcbiAgICBsZXQgYWN0aXZlTmFtZSA9IGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlXG4gICAgaWYgKGFjdGl2ZU5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICAgIHRhYnMuZm9yRWFjaCgodGFiLCBpbmRleCkgPT4ge1xuICAgICAgICBpZiAodGFiLm5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICAgICAgICBjb25zdCBuZXh0VGFiID0gdGFic1tpbmRleCArIDFdIHx8IHRhYnNbaW5kZXggLSAxXVxuICAgICAgICAgIGlmIChuZXh0VGFiKSB7XG4gICAgICAgICAgICBhY3RpdmVOYW1lID0gbmV4dFRhYi5uYW1lXG4gICAgICAgICAgfVxuICAgICAgICB9XG4gICAgICB9KVxuICAgIH1cblxuICAgIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gYWN0aXZlTmFtZSBcbiAgICBlZGl0YWJsZVRhYnMudmFsdWUgPSB0YWJzLmZpbHRlcigodGFiKSA9PiB0YWIubmFtZSAhPT0gdGFyZ2V0TmFtZSlcbiAgfVxufVxuXG5vbk1vdW50ZWQoKCk9PntcbiAgY29uc3Qgc2Nyb2xsRG9tID0gdGFic1JlZi52YWx1ZS4kZWwucXVlcnlTZWxlY3RvcignLmVsLXRhYnNfX25hdicpXG4gIHNjcm9sbERvbS5hZGRFdmVudExpc3RlbmVyKFwid2hlZWxcIiwgKGV2ZW50KSA9PiB7IFxuICAgIGNvbnNvbGUubG9nKDEyMylcbiAgICBldmVudC5wcmV2ZW50RGVmYXVsdCgpOyAgIFxuICAgIHNjcm9sbERvbS5zY3JvbGxMZWZ0ICs9IGV2ZW50LmRlbHRhWTsgXG4gIH0pOyBcblxufSlcbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbiAgLmVsLXRhYnNfX25hdntcbiAgICB3aWR0aDoxMDAlO1xuICAgIG92ZXJmbG93LXg6IGF1dG87XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

`scrollToActiveTab`, 为tab-nav暴露给tabs用的，并未通过tabs暴露出来，可以考虑上面的方法先实现
