### ISSUE TITLE
[Component] [input-number] el-input-number，  If you enter 0 or 11- or 11-- , the change event can't be triggered

### ISSUE THREAD

**Issue by Dav6** [element-plus/element-plus#10800]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.25`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-input-number`

### Reproduction Link

[CodePen](https://codepen.io/Dav6/pen/PoaarRy)

### Steps to reproduce

enter 0 or 11-- 

### What is Expected?

@change="onChange" 
change event can triggered

### What is actually happening?

@change="onChange" 
change event can't be triggered

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
For 0 can not trigger change is definitely a problem, for illegal number input I think we need to discuss

By looking at the git history I found several problems.
1. in `v2.2.0` and before, inputting illegal numbers behaves like returning the previous number, but not after `v2.2.1`, refer to #7724

![2 2 0](https://user-images.githubusercontent.com/59350883/204491117-2880b3e0-cf5a-4e8d-987d-f331f8be7a24.gif)
![2 2 25](https://user-images.githubusercontent.com/59350883/204491174-a988174b-6c22-4634-a722-c3f6a721c0ee.gif)
`v2.2.0` is more in line with element-ui's interaction logic

2. `v2.2.1~v2.2.22`, inputting illegal numbers will trigger change with null value, `v2.2.23` and later will not trigger, refer to #10329

Personally, I think we should fix problem2 and set input empty when inputting illegal number

WDYT @element-plus/backers

**Comment by Dav6** [comment]
![2 2 0](https://user-images.githubusercontent.com/40747461/204685450-f7433536-4826-40b5-ae2c-354092dbfa0f.gif)
![2 2 25](https://user-images.githubusercontent.com/40747461/204685430-059c4c8b-790b-4c6d-9dc4-0aef17e101ff.gif)

My problem is event triggering, not value change
v2.2.25 when value is null, the   change event is not trigger

**Comment by chenxch** [comment]
I think it is first to add the judgment of character compliance, and secondly to improve the change feedback logic of null values.

**Comment by init-qy** [comment]
the demo can trigger change for null value and 0, [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiA6bWluPVwiLTFcIiA6bWF4PVwiMTBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgQGlucHV0PVwiaGFuZGxlSW5wdXRcIiAvPlxuICA8ZGl2IHYtZm9yPVwiaXRlbSBpbiBsb2dzXCI+XG4gICAge3tpdGVtfX1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMSlcbmNvbnN0IGxvZ3MgPSByZWYoW10pXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsdWU6IG51bWJlcikgPT4ge1xuICBjb25zb2xlLmxvZygnLS0tLS0tLS0tLS1AY2hhbmdlLS0tLS0tLS0nKTtcbiAgY29uc29sZS5sb2codmFsdWUpXG4gIGxvZ3MudmFsdWUucHVzaCgnY2hhbmdlICcrU3RyaW5nKHZhbHVlKSlcbn1cbmNvbnN0IGhhbmRsZUlucHV0ID0gdmFsdWUgPT4ge1xuICAgIGNvbnNvbGUubG9nKCctLS0tLS0tLS0tLUBpbnB1dC0tLS0tLS0tJyk7XG4gIGNvbnNvbGUubG9nKHZhbHVlKVxuICBsb2dzLnZhbHVlLnB1c2goJ2lucHV0ICcrU3RyaW5nKHZhbHVlKSlcbn1cbjwvc2NyaXB0PlxuXG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTA4MTgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMDgxOC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMDgxOC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMDgxOC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

**Comment by qq1063823095** [comment]
同样的问题，输入“-”符号后，不会触发onChang事件

![image](https://user-images.githubusercontent.com/39073123/206675419-377161c8-8fbc-4aea-85c6-c4b07ab7ab7c.png)

**Comment by StephenKe** [comment]
Base on official docs demo, input 0 can not trigger  change event [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiA6bWluPVwiLTFcIiA6bWF4PVwiMTBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgQGlucHV0PVwiaGFuZGxlSW5wdXRcIiAvPlxuICA8ZGl2IHYtZm9yPVwiaXRlbSBpbiBsb2dzXCI+XG4gICAge3tpdGVtfX1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMSlcbmNvbnN0IGxvZ3MgPSByZWYoW10pXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsdWU6IG51bWJlcikgPT4ge1xuICBjb25zb2xlLmxvZygnLS0tLS0tLS0tLS1AY2hhbmdlLS0tLS0tLS0nKTtcbiAgY29uc29sZS5sb2codmFsdWUpXG4gIGxvZ3MudmFsdWUucHVzaCgnY2hhbmdlICcrU3RyaW5nKHZhbHVlKSlcbn1cbmNvbnN0IGhhbmRsZUlucHV0ID0gdmFsdWUgPT4ge1xuICAgIGNvbnNvbGUubG9nKCctLS0tLS0tLS0tLUBpbnB1dC0tLS0tLS0tJyk7XG4gIGNvbnNvbGUubG9nKHZhbHVlKVxuICBsb2dzLnZhbHVlLnB1c2goJ2lucHV0ICcrU3RyaW5nKHZhbHVlKSlcbn1cbjwvc2NyaXB0PlxuXG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22910740/207534444-b5556418-71b1-44c2-bb47-f14384fc173f.png">

**Comment by StephenKe** [comment]
And I fixed it like this https://github.com/element-plus/element-plus/pull/10980
