### ISSUE TITLE
[Component] [input-number] Input Number 数字输入框 组件火狐浏览器可以输入数字外其他字符，比如字母

### ISSUE THREAD

**Issue by zpfZPFgithub** [element-plus/element-plus#10817]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.25`
- Browser / OS: `firefox 107.0 (32 位)`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

数字输入框可以直接输入中文，字母

### What is Expected?

数字输入框只允许输入对应数字

### What is actually happening?

数字输入框可以直接输入中文，字母或者min，max范围外的数字

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
link #10629
尽量先进行搜索看看是否有相同问题，或许能快速解决问题。
