### ISSUE TITLE
[Component] 在 inline 布局的 form 中使用 input 组件的 clearable 属性会导致 input 宽度抖动

### ISSUE THREAD

**Issue by cinsyk** [element-plus/element-plus#10815]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-input`
- `el-form`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBsYWJlbC13aWR0aD1cIjEyMHB4XCIgaW5saW5lPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLovpPlhaXmoYYxXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIGNsZWFyYWJsZS8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIui+k+WFpeahhjJcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgY2xlYXJhYmxlIHN0eWxlPVwid2lkdGg6IDI0MHB4XCIvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

鼠标移入输入款1

### What is Expected?

清空按钮出现在 input 尾部，且input组件宽度不变

### What is actually happening?

清空按钮出现在 input 尾部，且input组件宽度出现变化

### Additional comments

_(empty)_

**Comment by MrWeilian** [comment]
the same problem as [#7287](https://github.com/element-plus/element-plus/issues/7287)

**Comment by tolking** [comment]
Suggestions welcome in #7287
