### ISSUE TITLE
[Bug Report] when NavMenu's mode is vertical and collapse is true,It doesn't show animation.

### ISSUE THREAD

**Issue by erbaihuang** [element-plus/element-plus#1081]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
版本 87.0.4280.88（正式版本） (x86_64)

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/huangerbai/pen/XWjaLKW

### Steps to reproduce
when NavMenu's mode is vertical and collapse is true,It doesn't show animation.

### What is Expected?
it has animation

### What is actually happening?
It doesn't show animation.

**Comment by JeremyWuuuuu** [comment]
https://user-images.githubusercontent.com/15975785/102863856-269f5680-446e-11eb-88be-3178e23b9a58.mov
Do you mean not it wouldn't show the closing animation?

**Comment by erbaihuang** [comment]
> https://user-images.githubusercontent.com/15975785/102863856-269f5680-446e-11eb-88be-3178e23b9a58.mov
> Do you mean not it wouldn't show the closing animation?

I mean it would show the closing animation.

**Comment by erbaihuang** [comment]
when I switch the collapse's value, the el-menu seems to should show the animation？

**Comment by JeremyWuuuuu** [comment]
> when I switch the collapse's value, the el-menu seems to should show the animation？

When it collapsed, the behavior will be changed, no animation will be dispatched, the submenu will become something like an overflow menu, so it won't have the animation.

**Comment by erbaihuang** [comment]
But It doesn't look like the official demo.
https://element-plus.gitee.io/#/zh-CN/component/menu

**Comment by zazzaz** [comment]
Maybe it's related to vue `3.0.3` and `3.0.4` ? ref https://github.com/element-plus/element-plus/issues/1064

**Comment by Liiked** [comment]
I'll investigate it soon. It seems something goes wrong  when el-menu itself shows collapse animation of closing
For now, you could use `vue 3.0.3` as a workaround

**Comment by HakimLu** [comment]
I have the same problem, I am version 3.0.4

**Comment by zazzaz** [comment]
@HakimLu please downgrade to 3.0.3 until vue has a new release

**Comment by zazzaz** [comment]
this should have been fixed in `vue@3.0.5` https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8
