### ISSUE TITLE
[bug report] El input add ref, but the content cannot be obtained, and the initial value is null all the time. This problem also affects the timpicker time selector component

### ISSUE THREAD

**Issue by RenXusheng233** [element-plus/element-plus#1082]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
win10/chrome 80.0.3987.162

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/renxusheng233/pen/eYdEwLJ

### Steps to reproduce
在 el-input设置默认值123，并添加 ref="refContainer"，在 onMounted 中控制台打印 refContainer.value 的结果

### What is Expected?
refContainer.value有值

### What is actually happening?
refContainer为null

**Comment by BeADre** [comment]
you should return `refContainer `
