### ISSUE TITLE
[Component] [input] Cannot use el-input element as reusable component

### ISSUE THREAD

**Issue by bantawa04** [element-plus/element-plus#10823]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.25`
- Browser / OS: `Version 107.0.5304.110 (Official Build) (arm64) / macOS Monetary 12.4`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEJhc2VJbnB1dCBmcm9tIFwiLi9CYXNlSW5wdXQudnVlXCJcbmltcG9ydCBOb3JtYWxJbnB1dCBmcm9tIFwiLi9Ob3JtYWxJbnB1dC52dWVcIlxuY29uc3QgbXNnID0gcmVmKCdIb3VzZSBvZiB0aGUgZHJhZ29ucyEnKVxuY29uc3QgYXV0aG9yID0gcmVmKCdHZW9yZ2UgUlIgTWFydGluJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8QmFzZUlucHV0IDpsYWJlbD1cImBCb29rIFRpdGxlYFwiIHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8YnIvPlxuICA8aDE+e3thdXRob3J9fVxuICA8L2gxPlxuICA8Tm9ybWFsSW5wdXQgOmxhYmVsPVwiYEF1dGhvcmBcIiB2LW1vZGVsPVwiYXV0aG9yXCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiTm9ybWFsSW5wdXQudnVlIjoiPHRlbXBsYXRlPlxuICA8bGFiZWwgZm9yPVwiXCI+e3sgbGFiZWwgfX08L2xhYmVsPlxuICA8YnIvPlxuICA8aW5wdXRcbiAgICA6dmFsdWU9XCJtb2RlbFZhbHVlXCJcbiAgICBAaW5wdXQ9XCIkZW1pdCgndXBkYXRlOm1vZGVsVmFsdWUnLCBoYW5kbGVJbnB1dENoYW5nZSgkZXZlbnQpKVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW50ZXJmYWNlIElJbnB1dCB7XG4gICAgbGFiZWw6IHN0cmluZ1xuICAgIG1vZGVsVmFsdWU6IGFueVxuICB9XG4gIGNvbnN0IHsgbGFiZWwsIG1vZGVsVmFsdWUgfSA9IGRlZmluZVByb3BzPElJbnB1dD4oKVxuICBjb25zdCBoYW5kbGVJbnB1dENoYW5nZSA9IChldmVudDogRXZlbnQpID0+IHtcbiAgICByZXR1cm4gKGV2ZW50LnRhcmdldCBhcyBIVE1MSW5wdXRFbGVtZW50KS52YWx1ZVxuICB9XG48L3NjcmlwdD5cbiIsIkJhc2VJbnB1dC52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC1mb3JtLWl0ZW0gOmxhYmVsPVwibGFiZWxcIj5cbiAgICA8RWxJbnB1dFxuICAgICAgOmF1dG9mb2N1cz1cInRydWVcIlxuICAgICAgOnR5cGU9XCJ0eXBlXCJcbiAgICAgIDpwbGFjZWhvbGRlcj1cInBsYWNlaG9sZGVyXCJcbiAgICAgIDpzaG93LXdvcmQtbGltaXQ9XCJzaG93V29yZExpbWl0XCJcbiAgICAgIDpjbGVhcmFibGU9XCJjbGVhcmFibGVcIlxuICAgICAgOnNob3ctcGFzc3dvcmQ9XCJzaG93UGFzc3dvcmRcIlxuICAgICAgOnN1ZmZpeC1pY29uPVwic3VmZml4SWNvblwiXG4gICAgICA6cHJlZml4LWljb249XCJwcmVmaXhJY29uXCJcbiAgICAgIDpzaXplPVwic2l6ZVwiXG4gICAgICA6bWF4LWxlbmd0aD1cIm1heExlbmd0aFwiXG4gICAgICA6dmFsdWU9XCJtb2RlbFZhbHVlXCJcbiAgICAgIEBpbnB1dD1cIiRlbWl0KCd1cGRhdGU6bW9kZWxWYWx1ZScsIGhhbmRsZUlucHV0Q2hhbmdlKCRldmVudCkpXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgdi1pZj1cInByZXBlbmRcIiAjcHJlcGVuZD5IdHRwOi8vPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSB2LWlmPVwiYXBwZW5kXCIgI2FwcGVuZD4uY29tPC90ZW1wbGF0ZT5cbiAgICA8L0VsSW5wdXQ+XG4gIDwvZWwtZm9ybS1pdGVtPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG4gIGltcG9ydCB7IEVsSW5wdXQsIEVsRm9ybUl0ZW0gfSBmcm9tIFwiZWxlbWVudC1wbHVzXCJcbiAgaW50ZXJmYWNlIElJbnB1dCB7XG4gICAgbGFiZWw6IHN0cmluZ1xuICAgIHR5cGU/OiBzdHJpbmdcbiAgICBwbGFjZWhvbGRlcj86IHN0cmluZ1xuICAgIG1heExlbmd0aD86IG51bWJlclxuICAgIHNob3dXb3JkTGltaXQ/OiBib29sZWFuXG4gICAgY2xlYXJhYmxlPzogYm9vbGVhblxuICAgIHNob3dQYXNzd29yZD86IGJvb2xlYW5cbiAgICBzdWZmaXhJY29uPzogYW55XG4gICAgcHJlZml4SWNvbj86IGFueVxuICAgIHNpemU/OiBzdHJpbmdcbiAgICBwcmVwZW5kPzogYW55XG4gICAgYXBwZW5kPzogYW55XG4gICAgbW9kZWxWYWx1ZTogYW55XG4gIH1cbiAgY29uc3Qge1xuICAgIGxhYmVsLFxuICAgIHR5cGUsXG4gICAgcGxhY2Vob2xkZXIsXG4gICAgbWF4TGVuZ3RoLFxuICAgIHNob3dXb3JkTGltaXQsXG4gICAgY2xlYXJhYmxlLFxuICAgIHNob3dQYXNzd29yZCxcbiAgICBzdWZmaXhJY29uLFxuICAgIHByZWZpeEljb24sXG4gICAgc2l6ZSxcbiAgICBwcmVwZW5kLFxuICAgIGFwcGVuZCxcbiAgICBtb2RlbFZhbHVlLFxuICB9ID0gZGVmaW5lUHJvcHM8SUlucHV0PigpXG5cbiAgY29uc3QgaGFuZGxlSW5wdXRDaGFuZ2UgPSAodmFsdWU6IGFueSkgPT4ge1xuICAgIHJldHVybiB2YWx1ZVxuICB9XG5cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Create a reusable input component with element ui with props value and @input method and its body.

Import created component in any parent component

Type anything in the imported input component

### What is Expected?

Input should update the modelValue

### What is actually happening?

When typeing in the input field the first character is replaced by second character, second character is replaced by third and so on.

### Additional comments

I have also created normal input as reusable component to compare with element ui.

**Comment by plainheart** [comment]
This [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEJhc2VJbnB1dCBmcm9tIFwiLi9CYXNlSW5wdXQudnVlXCJcbmltcG9ydCBOb3JtYWxJbnB1dCBmcm9tIFwiLi9Ob3JtYWxJbnB1dC52dWVcIlxuY29uc3QgbXNnID0gcmVmKCdIb3VzZSBvZiB0aGUgZHJhZ29ucyEnKVxuY29uc3QgYXV0aG9yID0gcmVmKCdHZW9yZ2UgUlIgTWFydGluJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8QmFzZUlucHV0IDpsYWJlbD1cImBCb29rIFRpdGxlYFwiIHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8YnIvPlxuICA8aDE+e3thdXRob3J9fVxuICA8L2gxPlxuICA8Tm9ybWFsSW5wdXQgOmxhYmVsPVwiYEF1dGhvcmBcIiB2LW1vZGVsPVwiYXV0aG9yXCIvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiTm9ybWFsSW5wdXQudnVlIjoiPHRlbXBsYXRlPlxuICA8bGFiZWwgZm9yPVwiXCI+e3sgbGFiZWwgfX08L2xhYmVsPlxuICA8YnIvPlxuICA8aW5wdXRcbiAgICA6dmFsdWU9XCJtb2RlbFZhbHVlXCJcbiAgICBAaW5wdXQ9XCIkZW1pdCgndXBkYXRlOm1vZGVsVmFsdWUnLCBoYW5kbGVJbnB1dENoYW5nZSgkZXZlbnQpKVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW50ZXJmYWNlIElJbnB1dCB7XG4gICAgbGFiZWw6IHN0cmluZ1xuICAgIG1vZGVsVmFsdWU6IGFueVxuICB9XG4gIGNvbnN0IHsgbGFiZWwsIG1vZGVsVmFsdWUgfSA9IGRlZmluZVByb3BzPElJbnB1dD4oKVxuICBjb25zdCBoYW5kbGVJbnB1dENoYW5nZSA9IChldmVudDogRXZlbnQpID0+IHtcbiAgICByZXR1cm4gKGV2ZW50LnRhcmdldCBhcyBIVE1MSW5wdXRFbGVtZW50KS52YWx1ZVxuICB9XG48L3NjcmlwdD5cbiIsIkJhc2VJbnB1dC52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC1mb3JtLWl0ZW0gOmxhYmVsPVwibGFiZWxcIj5cbiAgICA8RWxJbnB1dFxuICAgICAgOmF1dG9mb2N1cz1cInRydWVcIlxuICAgICAgOnR5cGU9XCJ0eXBlXCJcbiAgICAgIDpwbGFjZWhvbGRlcj1cInBsYWNlaG9sZGVyXCJcbiAgICAgIDpzaG93LXdvcmQtbGltaXQ9XCJzaG93V29yZExpbWl0XCJcbiAgICAgIDpjbGVhcmFibGU9XCJjbGVhcmFibGVcIlxuICAgICAgOnNob3ctcGFzc3dvcmQ9XCJzaG93UGFzc3dvcmRcIlxuICAgICAgOnN1ZmZpeC1pY29uPVwic3VmZml4SWNvblwiXG4gICAgICA6cHJlZml4LWljb249XCJwcmVmaXhJY29uXCJcbiAgICAgIDpzaXplPVwic2l6ZVwiXG4gICAgICA6bWF4LWxlbmd0aD1cIm1heExlbmd0aFwiXG4gICAgICB2LW1vZGVsPVwidmFsXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgdi1pZj1cInByZXBlbmRcIiAjcHJlcGVuZD5IdHRwOi8vPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSB2LWlmPVwiYXBwZW5kXCIgI2FwcGVuZD4uY29tPC90ZW1wbGF0ZT5cbiAgICA8L0VsSW5wdXQ+XG4gIDwvZWwtZm9ybS1pdGVtPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG4gIGltcG9ydCB7IGNvbXB1dGVkLCB0b1JlZnMgfSBmcm9tICd2dWUnXG4gIGltcG9ydCB7IEVsSW5wdXQsIEVsRm9ybUl0ZW0gfSBmcm9tIFwiZWxlbWVudC1wbHVzXCJcbiAgaW50ZXJmYWNlIElJbnB1dCB7XG4gICAgbGFiZWw6IHN0cmluZ1xuICAgIHR5cGU/OiBzdHJpbmdcbiAgICBwbGFjZWhvbGRlcj86IHN0cmluZ1xuICAgIG1heExlbmd0aD86IG51bWJlclxuICAgIHNob3dXb3JkTGltaXQ/OiBib29sZWFuXG4gICAgY2xlYXJhYmxlPzogYm9vbGVhblxuICAgIHNob3dQYXNzd29yZD86IGJvb2xlYW5cbiAgICBzdWZmaXhJY29uPzogYW55XG4gICAgcHJlZml4SWNvbj86IGFueVxuICAgIHNpemU/OiBzdHJpbmdcbiAgICBwcmVwZW5kPzogYW55XG4gICAgYXBwZW5kPzogYW55XG4gICAgbW9kZWxWYWx1ZTogYW55XG4gIH1cbiBcbiAgY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wczxJSW5wdXQ+KClcbiAgY29uc3Qge1xuICAgIGxhYmVsLFxuICAgIHR5cGUsXG4gICAgcGxhY2Vob2xkZXIsXG4gICAgbWF4TGVuZ3RoLFxuICAgIHNob3dXb3JkTGltaXQsXG4gICAgY2xlYXJhYmxlLFxuICAgIHNob3dQYXNzd29yZCxcbiAgICBzdWZmaXhJY29uLFxuICAgIHByZWZpeEljb24sXG4gICAgc2l6ZSxcbiAgICBwcmVwZW5kLFxuICAgIGFwcGVuZCxcbiAgICBtb2RlbFZhbHVlLFxuICB9ID0gdG9SZWZzKHByb3BzKVxuICBcbiAgY29uc3QgZW1pdCA9IGRlZmluZUVtaXRzKFsndXBkYXRlOm1vZGVsVmFsdWUnXSlcblxuICBjb25zdCB2YWwgPSBjb21wdXRlZCh7XG4gICAgZ2V0KCkge1xuICAgICAgcmV0dXJuIG1vZGVsVmFsdWUudmFsdWVcbiAgICB9LFxuICAgIHNldCh2YWwpIHtcbiAgICAgIGVtaXQoJ3VwZGF0ZTptb2RlbFZhbHVlJywgdmFsKVxuICAgIH1cbiAgfSlcbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==) might be what you are looking for.
