### ISSUE TITLE
[Component] el-input 在输入内容后，要点击多次才会触发blur的事件,官网可复现。

### ISSUE THREAD

**Issue by Verdicts-ye** [element-plus/element-plus#10829]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.25`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`
- `el-input`
- `el-button`

### Reproduction Link

[[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVGFibGVWaXNpYmxlID0gdHJ1ZVwiPlxuICAgIG9wZW4gYSBUYWJsZSBuZXN0ZWQgRGlhbG9nXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cImRpYWxvZ1RhYmxlVmlzaWJsZVwiIHRpdGxlPVwiU2hpcHBpbmcgYWRkcmVzc1wiPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cImdyaWREYXRhXCI+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTUwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIyMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZWwtZGlhbG9nPlxuXG4gIDwhLS0gRm9ybSAtLT5cbiAgPGVsLWJ1dHRvbiB0ZXh0IEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gdHJ1ZVwiPlxuICAgIG9wZW4gYSBGb3JtIG5lc3RlZCBEaWFsb2dcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZGlhbG9nRm9ybVZpc2libGVcIiB0aXRsZT1cIlNoaXBwaW5nIGFkZHJlc3NcIj5cbiAgICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUHJvbW90aW9uIG5hbWVcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJab25lc1wiIDpsYWJlbC13aWR0aD1cImZvcm1MYWJlbFdpZHRoXCI+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0IGEgem9uZVwiPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIE5vLjFcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBOby4yXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dGb3JtVmlzaWJsZSA9IGZhbHNlXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dGb3JtVmlzaWJsZSA9IGZhbHNlXCI+XG4gICAgICAgICAgQ29uZmlybVxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkaWFsb2dUYWJsZVZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBkaWFsb2dGb3JtVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGZvcm1MYWJlbFdpZHRoID0gJzE0MHB4J1xuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnJyxcbiAgcmVnaW9uOiAnJyxcbiAgZGF0ZTE6ICcnLFxuICBkYXRlMjogJycsXG4gIGRlbGl2ZXJ5OiBmYWxzZSxcbiAgdHlwZTogW10sXG4gIHJlc291cmNlOiAnJyxcbiAgZGVzYzogJycsXG59KVxuXG5jb25zdCBncmlkRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG5dXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtYnV0dG9uLS10ZXh0IHtcbiAgbWFyZ2luLXJpZ2h0OiAxNXB4O1xufVxuLmVsLXNlbGVjdCB7XG4gIHdpZHRoOiAzMDBweDtcbn1cbi5lbC1pbnB1dCB7XG4gIHdpZHRoOiAzMDBweDtcbn1cbi5kaWFsb2ctZm9vdGVyIGJ1dHRvbjpmaXJzdC1jaGlsZCB7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxkaXY+XG4gICBcbiAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBAYmx1cj1cIm1zZz0n5aSx5Y6754Sm54K5J1wiIEBmb2N1cz1cIm1zZz3ojrflj5bnhKbngrlcIi8+XG4gIHt7bXNnfX1cbiAgPC9kaXY+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuY29uc3QgbXNnID0gcmVmKCcnKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### What is Expected?
输入内容后直接点击外部，没有触发input的blur事件，要过几秒在点击外部才会触发，

### What is actually happening?

需要点击多次才触发blur。

### Additional comments

_(empty)_

**Comment by lait233** [comment]
![iShot_2022-11-30_12 25 36](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif)
我这是正常的？
I‘m is ok

**Comment by Verdicts-ye** [comment]
应该是这个才对，不是dialog的问题，是input的问题

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBAYmx1cj0nYmx1cicvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuY29uc3QgYmx1cj0gKGUpPT57XG4gIGNvbnNvbGUubG9nKCflpLHljrvnhKbngrknKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by Verdicts-ye** [comment]
[> ![iShot_2022-11-30_12 25 36](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) [ ![iShot_2022-11-30_12 25 36](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) ](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) [ ](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) 我这是正常的？ I‘m is ok
](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxkaXY+XG4gICBcbiAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBAYmx1cj1cIm1zZz0n5aSx5Y6754Sm54K5J1wiIEBmb2N1cz1cIm1zZz3ojrflj5bnhKbngrlcIi8+XG4gIHt7bXNnfX1cbiAgPC9kaXY+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuY29uc3QgbXNnID0gcmVmKCcnKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Verdicts-ye** [comment]
> ![iShot_2022-11-30_12 25 36](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) [ ![iShot_2022-11-30_12 25 36](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) ](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) [ ](https://user-images.githubusercontent.com/31282366/204707460-1622b84e-e22f-46f4-9bec-a809ef94e099.gif) 我这是正常的？ I‘m is ok

就是不能在输入完后直接点击外部触发blur，要过一会才能点击触发，

**Comment by lait233** [comment]
![iShot_2022-11-30_17 52 57](https://user-images.githubusercontent.com/31282366/204764535-4e0767cb-6eec-4360-a458-5701f574a2bb.gif)
建议你上个gif截图。qq截图也能转换成gif的 我这测试都是ok的

**Comment by chenxch** [comment]
是不是点到label了？ 最好提供一个gif或者视频，或者是详细的操作步骤

**Comment by Verdicts-ye** [comment]
不是点到label ，把鼠标换成usb2.0的接口就可以在点击外层瞬间触发blur，应该是硬件问题，html 的input 标签也存在




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 晚上7:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] el-input 在输入内容后，要点击多次才会触发blur的事件,官网可复现。 (Issue #10829)





 
是不是点到label了？ 最好提供一个gif或者视频，或者是详细的操作步骤
