### ISSUE TITLE
[bug report] El scrollbar has style problems under MacOS, which is ugly, and there are obvious gaps on the right and bottom

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#1083]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
macOS 10.15.7 / Chrome 87.0.4280.67

### Vue version
3.0.4

### Reproduction Link
https://codesandbox.io/s/affectionate-joliot-mpo2i?file=/src/App.vue

### Steps to reproduce
在mac系统下，查看带有 el-scroll 滚动的下拉框，右边和下方存在明显的空隙，很丑，windows系统下正常，给el-scrollbar 设置 native 属性，可恢复正常

### What is Expected?
修复mac下的滚动条样式，和windows一样

### What is actually happening?
在macOS下，右边和下方存在明显的空隙，很丑

**Comment by kooriookami** [comment]
Does this look good?
https://deploy-preview-1042--element-plus.netlify.app/?utm_source=github&utm_campaign=bot_dp#/zh-CN

**Comment by TothingWay** [comment]
@kooriookami [in macOS image](https://i.postimg.cc/cHXdSy4B/6-F0077-C0-E307-4131-AB78-7627-A82-F9-CEC.jpg)，See the gap between the right and the bottom？

**Comment by kooriookami** [comment]
Will fix soon~
