### ISSUE TITLE
[Style] [menu] 深色模式的时候开启Affix固定 el-menu 就没有背景颜色了(也有可能是变成透明色了) 遮挡不了下层的元素

### ISSUE THREAD

**Issue by gjx2116557388** [element-plus/element-plus#10834]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.7`
- Element Plus Version: `2.2.25`
- Browser / OS: ` Chrome`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/menu.html)

### Steps to reproduce

```vue
<!-- 切换成暗黑模式后 el-menu 失去背景色无法遮挡下层的元素 -->
<div>
<el-affix :offset="0">
  <el-menu
          :default-active="activeIndex"
          mode="horizontal"
          @select="handleSelect"
          class="el-menu-demo"
        >
    <div class="flex-grow" /> 
    <el-menu-item index="1">首页</el-menu-item>
    <el-menu-item index="2">测试页</el-menu-item>
    <el-menu-item index="3">测试</el-menu-item>

  </el-menu>
</el-affix>
<div>
  我是测试用例
</div>
</div>
```

### What is Expected?

预期是固定在顶部 可以切换暗黑模式

### What is actually happening?

没有背景色(或者是透明色)遮挡不了下层的元素

### Additional comments

这或许是我自己的原因 也可能是bug吧 打扰了

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/204869053-9fbe6192-3bdc-4c44-ac95-c2271382a1e4.png)

最好提供一下demo和截图

**Comment by gjx2116557388** [comment]
> ![图片](https://user-images.githubusercontent.com/23251408/204869053-9fbe6192-3bdc-4c44-ac95-c2271382a1e4.png)
> 
> 最好提供一下demo和截图

你好 我这里截了个图 demo我直接在github仓库重现了代码
这是地址
https://github.com/gjx2116557388/demo.git
![image](https://user-images.githubusercontent.com/67618391/205429476-08fe5570-3f99-4d47-822a-93593772e4f9.png)
![image](https://user-images.githubusercontent.com/67618391/205429486-93aec0f9-1e81-4101-9151-ee64f89cb06f.png)

**Comment by jasonren0403** [comment]
我没用el-affix，仅仅是使用了fixed，也出现了类似于你这样的情况

**Comment by YunYouJun** [comment]
May be we need a solid color for it. Need a suggestion from designer. @huangzhongzhong
