### ISSUE TITLE
[Component] [tree] el-tree 组件设置了:check-strictly="true"后setChecked方法不可用

### ISSUE THREAD

**Issue by mcck** [element-plus/element-plus#10830]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.25`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIHJlZj1cInRyZWVcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIG5vZGUta2V5PVwiaWRcIlxuICAgIDpjaGVjay1zdHJpY3RseT1cInRydWVcIlxuICAgIDpkZWZhdWx0LWV4cGFuZGVkLWtleXM9XCJbMiwgM11cIlxuICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cIls1XVwiXG4gICAgOnByb3BzPVwiZGVmYXVsdFByb3BzXCJcbiAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZWxlY3RBbGxcIj7lhajpgIk8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJztcbmxldCB0cmVlID0gcmVmKG51bGwpXG5sZXQgZmxhZyA9IGZhbHNlO1xuZnVuY3Rpb24gc2VsZWN0QWxsKCl7XG4gIHRyZWUudmFsdWUuc2V0Q2hlY2tlZCgnMycsIGZsYWcgPSAhZmxhZywgdHJ1ZSk7XG59XG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBpZDogMSxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNCxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogOSxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDEwLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA1LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDYsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiA4LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```
<template>
  <el-tree
    ref="tree"
    :data="data"
    show-checkbox
    node-key="id"
    :check-strictly="true"
    :default-expanded-keys="[2, 3]"
    :default-checked-keys="[5]"
    :props="defaultProps"
  />
  <el-button @click="selectAll">全选</el-button>
</template>

<script lang="ts" setup>
import {ref} from 'vue';
let tree = ref(null)
let flag = false;
function selectAll(){
  tree.value.setChecked('3', flag = !flag, true);
}
const defaultProps = {
  children: 'children',
  label: 'label',
}
const data = [
  {
    id: 1,
    label: 'Level one 1',
    children: [
      {
        id: 4,
        label: 'Level two 1-1',
        children: [
          {
            id: 9,
            label: 'Level three 1-1-1',
          },
          {
            id: 10,
            label: 'Level three 1-1-2',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    label: 'Level one 2',
    children: [
      {
        id: 5,
        label: 'Level two 2-1',
      },
      {
        id: 6,
        label: 'Level two 2-2',
      },
    ],
  },
  {
    id: 3,
    label: 'Level one 3',
    children: [
      {
        id: 7,
        label: 'Level two 3-1',
      },
      {
        id: 8,
        label: 'Level two 3-2',
      },
    ],
  },
]
</script>

```

### What is Expected?

调用tree.setChecked('3', true, true)后应该可以勾选本生及子节点。

### What is actually happening?

只勾选了id为3的节点，去掉:check-strictly="true"后才能勾选全部。

### Additional comments

setChecked	(key/data, checked, deep) 接收三个参数: 1. 要选中的节点的 key 或者数据 2. 一个布尔类型参数表明是否选中. 3. 一个布尔类型参数表明是否递归选中子节点。
第三个参数（deep）设置了没有效果。

**Comment by Cenavy1019** [comment]
请仔细阅读[文档](https://element-plus.gitee.io/zh-CN/component/tree.html#%E5%B1%9E%E6%80%A7)，`check-strictly`设置为`true`即只选中本身节点，不做子节点关联

**Comment by Cenavy1019** [comment]
请仔细阅读[文档](https://element-plus.gitee.io/zh-CN/component/tree.html#%E5%B1%9E%E6%80%A7)，`check-strictly`设置为`true`即只选中本身节点，不做子节点关联

**Comment by mcck** [comment]
> @Cenavy1019 

但是看setChecked的文档，第三个参数，deep 一个布尔类型参数表明是否递归选中子节点，那他应该要递归选择所有子节点。

**Comment by Cenavy1019** [comment]
> > @Cenavy1019
> 
> 但是看setChecked的文档，第三个参数，deep 一个布尔类型参数表明是否递归选中子节点，那他应该要递归选择所有子节点。

这是在`check-strictly`为`false`的前提下才得以实现的，文档里关于事件描述的均未带前置条件，可能让你误解了

```
if (this.store.checkStrictly) return
```

**Comment by mcck** [comment]
> Cenavy1019

好吧，谢谢，但是我觉得他应该不受checkStrictly影响，否则它意义不大。
