### ISSUE TITLE
[Component] [checkbox] cdn方式使用时el-checkbox显示异常

### ISSUE THREAD

**Issue by tingfeng-key** [element-plus/element-plus#10831]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.25`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52`
- Build Tool: `CDN`

### Related Component

- `el-checkbox`

### Reproduction Link

[CodePen](https://codepen.io/tingfeng-key/pen/XWYPpMv)

### Steps to reproduce

如链接中代码所示

### What is Expected?

复选框中的label正常显示

### What is actually happening?

复选框中的label仅显示最后一个

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
cdn 模式记得写闭便签，否则会被当成自定义元素
```
<el-checkbox></el-checkbox>
```

**Comment by tingfeng-key** [comment]
感谢，是这个原因
