### ISSUE TITLE
[Component] [card, message] TSX 引入组件无样式

### ISSUE THREAD

**Issue by mz-dfhp** [element-plus/element-plus#10844]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.20`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-card`
- `el-message`

### Reproduction Link

[Github Repo](https://github.com/mz-dfhp/mz-vue3-admin/blob/main/src/views/demo/demo-two.tsx)

### Steps to reproduce

```vue
import { defineComponent } from 'vue'
const Demo = () => (
  <el-row class="mb-4">
    <el-button>Default</el-button>
    <el-button type="primary">Primary</el-button>
    <el-button type="success">Success</el-button>
    <el-button type="info">Info</el-button>
    <el-button type="warning">Warning</el-button>
    <el-button type="danger">Danger</el-button>
  </el-row>
)
export default defineComponent({
  props: {},
  name: 'Demo-two',
  setup() {
    const change = () => {
      console.log('我是通过jsx语法写的页面')
    }
    return () => (
      <el-card>
        <Demo />
        <el-button type="danger" onClick={change}>
          我是通过jsx语法写的页面
        </el-button>
      </el-card>
    )
  }
})
```

### What is Expected?

<el-card> 样式失效

### What is actually happening?

<el-card> <el-message> 样式失效

### Additional comments

_(empty)_

**Comment by loosheng** [comment]
unplugin-vue-components default include: `[/\.vue$/, /\.vue\?vue/, /\.vue\?v=/]`

You need to set up support for j(t)sx.
https://github.com/mz-dfhp/mz-vue3-admin/blob/d46650259335919efeef57576ad1dc8570bf4a16/vite.config.ts#L35-L37

```diff
 Components({
+  include: [/\.vue$/, /\.vue\?vue/, /\.vue\?v=/, /\.[jt]sx$/],
   resolvers: [ElementPlusResolver()]
 }),
```

**Comment by mz-dfhp** [comment]
> Unplugin-vue-components默认包括：`[/\.vue$/, /\.vue\?vue/, /\.vue\?v=/]`
> 
> 您需要在以下位置设置 j（t）sx 的支持： https://github.com/mz-dfhp/mz-vue3-admin/blob/d46650259335919efeef57576ad1dc8570bf4a16/vite.config.ts#L35-L37
> 
> ```diff
>  Components({
> +  include: [/\.vue$/, /\.vue\?vue/, /\.vue\?v=/, /\.[jt]sx$/],
>    resolvers: [ElementPlusResolver()]
>  }),
> ```
> 
> 堆栈闪电战：https://stackblitz.com/edit/github-mx3cva?file=src%2Fviews%2Fdemo%2Fdemo-two.tsx,vite.config.ts

That's taken care of. Thank you
