### ISSUE TITLE
[Bug Report] Error using ElButton in h function

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#1086]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
window10 / chrome / 76

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr

### Steps to reproduce
According to the need to introduce
Webpack project created by vue-cli
The link is invalid

### What is Expected?
Can be used normally

### What is actually happening?
```typescript
import { h } from 'vue';
import { ElButton, ElNotification } from 'element-plus';
import { INotificationOptions } from 'element-plus/lib/el-notification/src/notification.type';

export const showNotify = () => {
    const btn = ElButton;
    console.log(btn === ElButton); // 这里会报错
    const options: INotificationOptions = {
        title: '提示消息',
        message: h('div', [
            h('div', '消息内容'),
            h(
                btn, // 如果这里写ElButton也会报错
                {
                    type: 'danger',
                    class: 'mt-12',
                    style: {
                        float: 'right'
                    },
                    onClick: () => {
                        notify.close();
                    }
                },
                () => '立即处理'
            )
        ]),
        customClass: 'forbidden-words-notify',
        duration: 0,
        type: 'error'
    };
    const notify = ElNotification(options);
};

```

![image-20201223090633381](https://gitee.com/wu_kang0718/image/raw/master//20201223090637025.png)

**Comment by wukang0718** [comment]
version is  1.0.1-beta.10

**Comment by zazzaz** [comment]
a reproduction demo or repo, please?

**Comment by wukang0718** [comment]
repo: https://github.com/wukang0718/issues

**Comment by zazzaz** [comment]
I can't even run this project, could you please double-check the code?

**Comment by wukang0718** [comment]
```bash
npm i
npm run serve
```
I tested it once and it worked
![image](https://user-images.githubusercontent.com/42261663/102965634-35970f00-4529-11eb-9d28-ecd7c40238ac.png)
It's just an error in the console, that's the problem I'm talking about

**Comment by zazzaz** [comment]
I got ` Cannot find module 'babel-plugin-component'`, please delete your local node_modules and try again

**Comment by wukang0718** [comment]
You are correct, I resubmitted the package.json.
Trouble you to update

**Comment by JeremyWuuuuu** [comment]
For CommonJS users, add `.default` to get the component work. I have met this issue before using h function

**Comment by wukang0718** [comment]
I am not using ` CommonJS`, I imported it using `import`

**Comment by JeremyWuuuuu** [comment]
> I am not using ` CommonJS`, I imported it using `import`

That depends on your bundler, not you, if you are using `webpack` then you are likely using CommonJS, if you are using `Vite` then you are using `ESM`.

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/102976954-4fdae800-453d-11eb-8d56-42e6caf20732.png)

![image](https://user-images.githubusercontent.com/42261663/102976933-46ea1680-453d-11eb-9ca1-19f4498864c4.png)
I can output the content of the ElButton component, but when I use the h function or the createVNode function, an error occurs

**Comment by JeremyWuuuuu** [comment]
Not that `console.log` isn't synchronous.

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/102978194-13a88700-453f-11eb-9bed-b029b945e2ed.png)
![image](https://user-images.githubusercontent.com/42261663/102978210-1acf9500-453f-11eb-8770-b954611b8741.png)
I just save the ElButton with a variable again.

**Comment by wukang0718** [comment]
What should I do if I don’t use this constant

**Comment by JeremyWuuuuu** [comment]
> For CommonJS users, add `.default` to get the component work. I have met this issue before using h function

As I mentioned above, use `Button.default`.

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/102978912-41420000-4540-11eb-805c-d8fe9f255aeb.png)
![image](https://user-images.githubusercontent.com/42261663/102978934-4a32d180-4540-11eb-9601-c8ec6b2161ba.png)
He just generated an comment node，Did I write it wrong?

**Comment by JeremyWuuuuu** [comment]
May I ask what bundler you are currently using?

**Comment by JeremyWuuuuu** [comment]
We encourage our users to stick with `Vite` instead of `Webpack`, because that way you can get the best developing experience.

**Comment by wukang0718** [comment]
`webpack`
Because our project is coming online soon, we need a relatively stable Bundler

**Comment by JeremyWuuuuu** [comment]
The quick suggestion is that you might need to use `template` instead of `jsx`, because we are currently working on packaging/automation/bug-fixing at the same time, so the support for that might took a bit longer.
The way to enforce webpack to import it as `ESM` is to mark the package.json of `element-plus` with flag `type: module`.

**Comment by wukang0718** [comment]
ok, thank you

**Comment by JeremyWuuuuu** [comment]
Our packaging strategy certainly has some issues, so I think that will be my prioritized job to fix that.
