### ISSUE TITLE
[Bug Report] Last option in Select component is not rendered well in Firefox 84.0.1

### ISSUE THREAD

**Issue by mPyth** [element-plus/element-plus#1087]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
Windows 8.1 Pro 64bit / Firefox 84.0.1
### Vue version
3.0.4

### Reproduction Link
https://jsfiddle.net/zpq637rm/

### Steps to reproduce
Reproduction link has the same code as example on https://element-plus.org/#/en-US/component/select .
By clicking on Select component, a pop-up with options is shown, the last option is not rendered well in Firefox 84.0.1 . The bottom part of last option is cut.
Here is the screenshot:
![selectComponentInFirefox](https://user-images.githubusercontent.com/18519715/102949003-80803a80-44c7-11eb-8dc0-1a5320dbf178.png)

I've also noticed the components Cascader (bad rendered) and Backtop (not rendered) does not behave as expected in Firefox.

### What is Expected?
Last option of Select component should be rendered in Firefox as it is rendered in Chromium.

### What is actually happening?
The bottom part of last option in Select component is cut.

**Comment by kooriookami** [comment]
Does this look good?
https://deploy-preview-1042--element-plus.netlify.app

**Comment by kooriookami** [comment]
Will be fixed soon~ #1042

**Comment by mPyth** [comment]
I've just check #1042 - it works great, even Cascader is fixed. Only Backtop component is still not visible, but it is not so important.
Thanks for your effort !
