### ISSUE TITLE
[Component] [select] select multiple tags overflow

### ISSUE THREAD

**Issue by YornQiu** [element-plus/element-plus#10872]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.25`
- Browser / OS: `Chrome 107`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWY8bnVtYmVyW10+KFsxLDIsMyw0LDUsNiw3LDgsOSwxMCwxMV0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIG11bHRpcGxlIGNvbGxhcHNlLXRhZ3M+XG4gICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaSBpbiAyMDBcIiA6dmFsdWU9XCJpXCIgOmxhYmVsPVwiYE9wdGlvbiR7aX0ke2l9JHtpfSR7aX0ke2l9JHtpfWBcIj48L2VsLW9wdGlvbj5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

see reproduction

### What is Expected?
The tags shouldn't overflow

### What is actually happening?

<img width="248" alt="image" src="https://user-images.githubusercontent.com/13913084/205240709-01e28078-bd09-4bc2-923f-4d6cdc173e9a.png">

### Additional comments

In fact, if parent element has attribute `font-variant-numeric: tabular-nums` or selected tags number is too large(eg: 100+), the exception may also occured.

**Comment by YornQiu** [comment]
calculating the width of tags wrapper may be not a nice idea, is `flex` layout proper?

**Comment by ryuhangyeong** [comment]
It is not reproducible in my environment.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/27342882/205281293-2616f980-ffd1-4f2c-a5d1-f3e22790978e.png">

**Comment by MrWeilian** [comment]
> It is not reproducible in my environment. (window / Chrome 107.0.5304.122(64bit)
> 
> <img alt="image" width="947" src="https://user-images.githubusercontent.com/27342882/205281293-2616f980-ffd1-4f2c-a5d1-f3e22790978e.png">

Maybe this option's width is not enough, when options's content is long that trigger the style "text-overflow: ellipsis", this issue will recurrence

**Comment by YornQiu** [comment]
> It is not reproducible in my environment. (window / Chrome 107.0.5304.122(64bit)
> 
> <img alt="image" width="947" src="https://user-images.githubusercontent.com/27342882/205281293-2616f980-ffd1-4f2c-a5d1-f3e22790978e.png">

Maybe options' content didn't trigger "text-overflow" on windows platform because of different font family while my device is MBP.
Set the options' label longer to reproduce

**Comment by kooriookami** [comment]
Fixed
