### ISSUE TITLE
[cascader] 网站部分页面报错

### ISSUE THREAD

**Issue by HOUSHENGREN** [element-plus/element-plus#10873]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Chrome/107.0.0.0`
- Build Tool: `Other`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/calendar.html)

### Steps to reproduce

登录官方网站，点击cascader组件

### What is Expected?

能正常访问

### What is actually happening?

不能

### Additional comments

_(empty)_

**Comment by HOUSHENGREN** [comment]
上面提到的链接又可以了，但这个不行
![image](https://user-images.githubusercontent.com/48871516/205254649-15385fa9-ad2d-4c29-acb8-34038c802ca8.png)
![image](https://user-images.githubusercontent.com/48871516/205254726-d73d88ad-7c58-4414-b06a-0529618ed4d6.png)

**Comment by xiaoxian521** [comment]
Since it's just released, it's fine to refresh it now
