### ISSUE TITLE
[TypeScript] [popover] 模块 ""element-plus"" 没有导出的成员 "PopoverInstance"。你是想改用 "import PopoverInstance from "element-plus"" 吗?t

### ISSUE THREAD

**Issue by changk99** [element-plus/element-plus#10874]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHR5cGUgeyBQb3BvdmVySW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

import type { PopoverInstance } from 'element-plus';

### What is Expected?

PopoverInstance 该类型应该存在,这样可以为 popver 组件的方法调用提供类型支持

### What is actually happening?

模块 ""element-plus"" 没有导出的成员 "PopoverInstance"。你是想改用 "import PopoverInstance from "element-plus"" 吗?

### Additional comments

_(empty)_

**Comment by loosheng** [comment]
```ts
import type { PopoverInstance } from 'element-plus';

```

Supported from 2.2.7 onwards.
