### ISSUE TITLE
[Feature Request] I hope that the official can deal with the issue in time

### ISSUE THREAD

**Issue by tu6ge** [element-plus/element-plus#1088]
### Existing Component
No

### Component Name
Nothing

### Description
I hope that the official can deal with the issue in time, too much issues will lead to out of control, so that the official valuable bug has not been timely response. It is suggested that issue not related to the framework should be closed directly, or the proposer should be blackmailed

希望官方能够及时处理反馈信息，反馈信息太多会导致失控，以至于官方的有价值的bug没有得到及时的响应。建议把跟框架不相关的反馈直接关闭，或者拉黑提出者

**Comment by JeremyWuuuuu** [comment]
The truth is that people always raise questions which were not relative to this library itself, but they think that it is. You can't blame people for that, also, it certainly costs time of maintainers, so we need community power to do that.

**Comment by JeremyWuuuuu** [comment]
Blocking the users wasn't a good idea to me, you must leverage the so called "valuable", despite the fact that I always get headaches for issues like you mentioned, but that's some negative part we OSS developers need to face.

**Comment by tu6ge** [comment]
We can ban speech for a period of time, such as a week, a month. Many people ask questions without looking at the documents

**Comment by JeremyWuuuuu** [comment]
> We can ban speech for a period of time, such as a week, a month. Many people ask questions without looking at the documents

We certainly want every one of our issue makers to give us good feedback, you know that the fact is that some users are just so called "伸手党", they just want everything to be delivered into their mouth, you can see what Evan mentioned about the situation that we are currently experiencing. https://twitter.com/youyuxi/status/1337444366240133120

**Comment by tu6ge** [comment]
Yes, I quite agree with you.

**Comment by JeremyWuuuuu** [comment]
So I am closing this issue, I promise that we will do the best as we can. Also we need community support if you want to help us, you can join right away by starting to fix PR, documents, etc.
