### ISSUE TITLE
[TypeScript] [input-number] input-number组件displayValue中Ts报错

### ISSUE THREAD

**Issue by code-vincent** [element-plus/element-plus#10887]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkaXNwbGF5VmFsdWUgPSBjb21wdXRlZCgoKSA9PiB7XG4gIGlmIChkYXRhLnVzZXJJbnB1dCAhPT0gbnVsbCkge1xuICAgIHJldHVybiBkYXRhLnVzZXJJbnB1dFxuICB9XG4gIGxldCBjdXJyZW50VmFsdWU6IG51bWJlciB8IHN0cmluZyB8IHVuZGVmaW5lZCB8IG51bGwgPSBkYXRhLmN1cnJlbnRWYWx1ZVxuICBpZiAoaXNOaWwoY3VycmVudFZhbHVlKSkgcmV0dXJuICcnXG4gIGlmIChpc051bWJlcihjdXJyZW50VmFsdWUpKSB7XG4gICAgaWYgKE51bWJlci5pc05hTihjdXJyZW50VmFsdWUpKSByZXR1cm4gJydcbiAgICBpZiAoIWlzVW5kZWZpbmVkKHByb3BzLnByZWNpc2lvbikpIHtcbiAgICAgIGN1cnJlbnRWYWx1ZSA9IGN1cnJlbnRWYWx1ZS50b0ZpeGVkKHByb3BzLnByZWNpc2lvbilcbiAgICB9XG4gIH1cbiAgcmV0dXJuIGN1cnJlbnRWYWx1ZVxufSlcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script lang="ts" setup>
const displayValue = computed(() => {
  if (data.userInput !== null) {
    return data.userInput
  }
  let currentValue: number | string | undefined | null = data.currentValue
  if (isNil(currentValue)) return ''
  if (isNumber(currentValue)) {
    if (Number.isNaN(currentValue)) return ''
    if (!isUndefined(props.precision)) {
      currentValue = currentValue.toFixed(props.precision)
    }
  }
  return currentValue
})
</script>
```

### What is Expected?

```vue
<script lang="ts" setup>
const displayValue = computed(() => {
  if (data.userInput !== null) {
    return data.userInput
  }
  let currentValue: number | string | undefined | null = data.currentValue
  if (isNil(currentValue)) return ''
  if (isNumber(currentValue)) {
    if (Number.isNaN(currentValue)) return ''
    if (!isUndefined(props.precision)) {
      currentValue = Number(currentValue).toFixed(props.precision)
    }
  }
  return currentValue
})
</script>
```

### What is actually happening?

Property 'toFixed' does not exist on type 'string | number'.
  Property 'toFixed' does not exist on type 'string'.Vetur(2339)

### Additional comments

读源码看到的ts报错

**Comment by btea** [comment]
This seems to be correct, `isNumber` narrows the `currentValue` type to number
https://github.com/element-plus/element-plus/blob/151ebede93fc7a95a8aa388e2fb7c08ddbe63b47/packages/components/input-number/src/input-number.vue#L142

**Comment by code-vincent** [comment]
> This seems to be correct, `isNumber` narrows the `currentValue` type to number
> 
> https://github.com/element-plus/element-plus/blob/151ebede93fc7a95a8aa388e2fb7c08ddbe63b47/packages/components/input-number/src/input-number.vue#L142

是的，但是在vsCode里面确实是有这个提示。
![image](https://user-images.githubusercontent.com/41747764/205428269-8ecb2146-758c-4ed3-889e-dcf857dadc59.png)

**Comment by btea** [comment]
我这边是正常的
![image](https://user-images.githubusercontent.com/24516654/205428423-a835028e-17c8-458e-afa5-e59119fb77ec.png)

建议把 Vetur 换成 Volar 试试

**Comment by code-vincent** [comment]
> 我这边是正常的 ![image](https://user-images.githubusercontent.com/24516654/205428423-a835028e-17c8-458e-afa5-e59119fb77ec.png)
> 
> 建议把 Vetur 换成 Volar 试试
好的，感谢感谢。
