### ISSUE TITLE
[Component] [select, drawer] el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框会显示。

### ISSUE THREAD

**Issue by JChehe** [element-plus/element-plus#10893]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRyYXdlciA9IHJlZihmYWxzZSlcbmZ1bmN0aW9uIHRvZ2dsZSAoKSB7XG4gIGRyYXdlci52YWx1ZSA9IHRydWVcbn1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIGxhYmVsOiAnb3B0aW9uIDEnLFxuICAgIHZhbHVlOiAxXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ29wdGlvbiAyJyxcbiAgICB2YWx1ZTogMlxuICB9XG5dXG5cbmFzeW5jIGZ1bmN0aW9uIGJlZm9yZUNsb3NlKGRvbmUpIHtcbiAgdHJ5IHtcbiAgICBhd2FpdCBFbE1lc3NhZ2VCb3guY29uZmlybSgn56Gu5a6a5YWz6Zet77yfJylcblxuICAgIGRvbmUoKVxuICB9IGNhdGNoIChlcnJvcikge1xuICAgIGlmIChlcnJvciAhPT0gJ2NhbmNlbCcpIHtcbiAgICAgIHRocm93IGVycm9yXG4gICAgfVxuICB9XG59XG4gIFxuY29uc3Qgc3RlcHMgPSBbXG4gICfmiZPlvIAgZHJhd2Vy44CCJyxcbiAgJ+eCueWHuyBzZWxlY3Qg6K6p5YW26I635Y+W54Sm54K544CCJyxcbiAgJ+aMiSBFc2Mg5YWz6ZetIGRyYXdlcu+8iOatpOS4vuaYr+S4uuS6huiuqSBzZWxlY3Qg5L+d5oyB54Sm54K577yM6Iul6YCa6L+H6byg5qCH54K55Ye7IHgg5YWz6Zet5oyJ6ZKu5LiN5Y+v5aSN546w6Zeu6aKY77yJJyxcbiAgJ+atpOaXtiBkcmF3ZXIg5YWz6Zet77yM5L2GIG9wdGlvbnMg5LiL5ouJ5qGG6YCJ6aG55Y205pi+56S644CCJ1xuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgzPuWJjeaPkOadoeS7tu+8mmVsLXNlbGVjdFtmaWx0ZXJhYmxlXSDlnKggZWwtZHJhd2VyW2JlZm9yZS1jbG9zZV0g5YaFPC9oMz5cbiAgPGgzPlxuICAgIOWkjeeOsOatpemqpOWmguS4i++8mlxuICA8L2gzPlxuICA8b2w+XG4gICAgPGxpIHYtZm9yPVwiaXRlbSBpbiBzdGVwc1wiIDprZXk9XCJpdGVtXCI+e3tpdGVtfX08L2xpPlxuICA8L29sPlxuICBcbiAgXG4gIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlXCI+b3BlbiBkcmF3ZXI8L2VsLWJ1dHRvbj5cbiAgPGVsLWRyYXdlciB2LW1vZGVsPVwiZHJhd2VyXCIgOmJlZm9yZS1jbG9zZT1cImJlZm9yZUNsb3NlXCI+XG5cdFx0PGVsLXNlbGVjdCBmaWx0ZXJhYmxlPlxuICAgICAgPGVsLW9wdGlvbiBcbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiBcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICA8L2VsLWRyYXdlcj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion, ElMessageBox } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const drawer = ref(false)
function toggle () {
  drawer.value = true
}

const options = [
  {
    label: 'option 1',
    value: 1
  },
  {
    label: 'option 2',
    value: 2
  }
]

async function beforeClose(done) {
  try {
    await ElMessageBox.confirm('确定关闭？')

    done()
  } catch (error) {
    if (error !== 'cancel') {
      throw error
    }
  }
}
  
const steps = [
  '打开 drawer。',
  '点击 select 让其获取焦点。',
  '按 Esc 关闭 drawer（此举是为了让 select 保持焦点，若通过鼠标点击 x 关闭按钮不可复现问题）',
  '此时 drawer 关闭，但 options 下拉框选项却显示。'
]
</script>

<template>
  <h3>前提条件：el-select[filterable] 在 el-drawer[before-close] 内</h3>
  <h3>
    复现步骤如下：
  </h3>
  <ol>
    <li v-for="item in steps" :key="item">{{item}}</li>
  </ol>
  
  
  <el-button @click="toggle">open drawer</el-button>
  <el-drawer v-model="drawer" :before-close="beforeClose">
		<el-select filterable>
      <el-option 
        v-for="item in options" 
        :key="item.value" 
        :label="item.label"
        :value="item.value"></el-option>
      </el-select>
  </el-drawer>

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>
```

### What is Expected?

el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框不会显示。

### What is actually happening?

el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框会显示。

### Additional comments

除 drawer 外，不知道 dialog 否则存在同样的问题。
除 select 外，不知道其他拥有下拉框选项的组件是否有同样的问题。

**Comment by JChehe** [comment]
复现视频如下：

https://user-images.githubusercontent.com/8402442/205481394-9ecbd966-b612-49c2-b44b-4ecf7b07a89a.mp4

**Comment by acyza** [comment]
可以把teleported改成false
