### ISSUE TITLE
[bug report] upload displays the image by default, and the data transferred by file list through prop is not displayed

### ISSUE THREAD

**Issue by LYao0919** [element-plus/element-plus#1090]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
mac chrome

### Vue version
3.0.4

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
upload组件：
父组件透传 file-list  到子组件
子组件props接收，赋值给state.fileList 页面上并没有展示当前图片  打印发现数据正常

（因为包含子组件  codepen 无法渲染 ）

### What is Expected?
组件upload 可以接受动态数据

### What is actually happening?
组件upload 无法渲染动态数据

**Comment by JeremyWuuuuu** [comment]
Thank you for reporting this, I will investigate this ASAP.

**Comment by LYao0919** [comment]
setup(props: Props, context: SetupContext) {
      const bol = ref(true); //兼容上传 数据刷新页面不展示
     const state = reactive({
      fileList: props.uploadObj.defaultfilelist || [],
    });

    watch(props.uploadObj.defaultfilelist, (val) => {
      bol.value = false;
      nextTick(() => {
        state.fileList = val;
        bol.value = true;
      });
    });
 }

**Comment by JeremyWuuuuu** [comment]
Sorry for kept you waiting, I will fix this tomorrow.

**Comment by JeremyWuuuuu** [comment]
Hi, sorry for the staled response, could you give me a minimal reproducible version?

**Comment by LYao0919** [comment]
Hello, this problem no longer exists in the current version, thank you

**Comment by zazzaz** [comment]
cool, I'll close it then
