### ISSUE TITLE
[Component] [date-picker] [model-value] not trigger change event

### ISSUE THREAD

**Issue by lgting123** [element-plus/element-plus#10904]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEN1c3REYXRlUGljayBmcm9tICcuL0NvbXAudnVlJ1xuY29uc3QgZGF0ZVZhbHVlID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPm1vZGVsVmFsdWUgW2VsLWRhdGUtcGlja2VyXSBUaGUgY2hhbmdlIGV2ZW50IGlzIG5vdCB0cmlnZ2VyZWQ8L2gxPlxuICA8Q3VzdERhdGVQaWNrIHYtbW9kZWw9XCJkYXRlVmFsdWVcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICd5bi1kYXRlLXBpY2snIH07XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIG1vZGVsVmFsdWU6IHN0cmluZztcbn0+KCk7XG5jb25zdCBlbWl0cyA9IGRlZmluZUVtaXRzPHtcbiAgKGU6ICd1cGRhdGU6bW9kZWxWYWx1ZScsIHZhbHVlOiBhbnkpOiB2b2lkO1xufT4oKTtcblxuY29uc3QgY2hhbmdlID0gKHZhbHVlKSA9PiB7IC8vIG5vIHRyaWdnZXJcbiAgY29uc29sZS5sb2codmFsdWUpO1xuICBlbWl0cygndXBkYXRlOm1vZGVsVmFsdWUnLCB2YWx1ZSk7XG59O1xuY29uc3QgdmlzaWJsZSA9ICh2YWx1ZTogYm9vbGVhbikgPT4geyAvLyB0aGlzIG9rXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbn07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgICBAdmlzaWJsZS1jaGFuZ2U9XCJ2aXNpYmxlXCJcbiAgICA6bW9kZWxWYWx1ZT1cIm1vZGVsVmFsdWVcIi8+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkIGxhbmc9XCJzY3NzXCI+PC9zdHlsZT4iLCJfbyI6e319)

### Steps to reproduce

modelValue change事件无法触发。【The change event is not triggered】

### What is Expected?

trigger change event

### What is actually happening?

not trigger

### Additional comments

_(empty)_

**Comment by lgting123** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/95486647/205544340-4f5bdab7-97f0-487a-a48b-d5e7029b1b67.png">

**Comment by lgting123** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/95486647/205544381-43a7f1ee-019a-4c22-a374-6391e824a96c.png">
this ok

**Comment by itsalimanuel** [comment]
You mean like [that 🔗 ](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEN1c3REYXRlUGljayBmcm9tICcuL0NvbXAudnVlJ1xuY29uc3QgZGF0ZVZhbHVlID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgZGF0YUlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPm1vZGVsVmFsdWUgW2VsLWRhdGUtcGlja2VyXSBUaGUgY2hhbmdlIGV2ZW50IGlzIG5vdCB0cmlnZ2VyZWQ8L2gxPlxuICA8Q3VzdERhdGVQaWNrIHYtbW9kZWw9XCJkYXRhSW5wdXRcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICd5bi1kYXRlLXBpY2snIH07XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIGRhdGFJbnB1dDogc3RyaW5nO1xufT4oKTtcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHM8e1xuICAoZTogJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZTogYW55KTogdm9pZDtcbn0+KCk7XG5cbmNvbnN0IGNoYW5nZSA9ICh2YWx1ZSkgPT4geyAvLyBubyB0cmlnZ2VyXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbiAgZW1pdHMoJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZSk7XG59O1xuY29uc3QgdmlzaWJsZSA9ICh2YWx1ZTogYm9vbGVhbikgPT4geyAvLyB0aGlzIG9rXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbn07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgICBAdmlzaWJsZS1jaGFuZ2U9XCJ2aXNpYmxlXCJcbiAgICA6ZGF0YUlucHV0PVwiZGF0YUlucHV0XCIvPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZCBsYW5nPVwic2Nzc1wiPjwvc3R5bGU+IiwiX28iOnt9fQ==) ?

**Comment by lgting123** [comment]
> You mean like [that 🔗 ](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEN1c3REYXRlUGljayBmcm9tICcuL0NvbXAudnVlJ1xuY29uc3QgZGF0ZVZhbHVlID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgZGF0YUlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPm1vZGVsVmFsdWUgW2VsLWRhdGUtcGlja2VyXSBUaGUgY2hhbmdlIGV2ZW50IGlzIG5vdCB0cmlnZ2VyZWQ8L2gxPlxuICA8Q3VzdERhdGVQaWNrIHYtbW9kZWw9XCJkYXRhSW5wdXRcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICd5bi1kYXRlLXBpY2snIH07XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIGRhdGFJbnB1dDogc3RyaW5nO1xufT4oKTtcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHM8e1xuICAoZTogJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZTogYW55KTogdm9pZDtcbn0+KCk7XG5cbmNvbnN0IGNoYW5nZSA9ICh2YWx1ZSkgPT4geyAvLyBubyB0cmlnZ2VyXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbiAgZW1pdHMoJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZSk7XG59O1xuY29uc3QgdmlzaWJsZSA9ICh2YWx1ZTogYm9vbGVhbikgPT4geyAvLyB0aGlzIG9rXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbn07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgICBAdmlzaWJsZS1jaGFuZ2U9XCJ2aXNpYmxlXCJcbiAgICA6ZGF0YUlucHV0PVwiZGF0YUlucHV0XCIvPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZCBsYW5nPVwic2Nzc1wiPjwvc3R5bGU+IiwiX28iOnt9fQ==) ?

yes

**Comment by mccxiv** [comment]
> You mean like [that 🔗 ](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEN1c3REYXRlUGljayBmcm9tICcuL0NvbXAudnVlJ1xuY29uc3QgZGF0ZVZhbHVlID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgZGF0YUlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPm1vZGVsVmFsdWUgW2VsLWRhdGUtcGlja2VyXSBUaGUgY2hhbmdlIGV2ZW50IGlzIG5vdCB0cmlnZ2VyZWQ8L2gxPlxuICA8Q3VzdERhdGVQaWNrIHYtbW9kZWw9XCJkYXRhSW5wdXRcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICd5bi1kYXRlLXBpY2snIH07XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIGRhdGFJbnB1dDogc3RyaW5nO1xufT4oKTtcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHM8e1xuICAoZTogJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZTogYW55KTogdm9pZDtcbn0+KCk7XG5cbmNvbnN0IGNoYW5nZSA9ICh2YWx1ZSkgPT4geyAvLyBubyB0cmlnZ2VyXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbiAgZW1pdHMoJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZSk7XG59O1xuY29uc3QgdmlzaWJsZSA9ICh2YWx1ZTogYm9vbGVhbikgPT4geyAvLyB0aGlzIG9rXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbn07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgICBAdmlzaWJsZS1jaGFuZ2U9XCJ2aXNpYmxlXCJcbiAgICA6ZGF0YUlucHV0PVwiZGF0YUlucHV0XCIvPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZCBsYW5nPVwic2Nzc1wiPjwvc3R5bGU+IiwiX28iOnt9fQ==) ?

I'm so confused, what is `:dataInput=`? it's not documented anywhere? And it doesn't work when I try locally

**Comment by itsalimanuel** [comment]
> > You mean like [that 🔗 ](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IEN1c3REYXRlUGljayBmcm9tICcuL0NvbXAudnVlJ1xuY29uc3QgZGF0ZVZhbHVlID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgZGF0YUlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPm1vZGVsVmFsdWUgW2VsLWRhdGUtcGlja2VyXSBUaGUgY2hhbmdlIGV2ZW50IGlzIG5vdCB0cmlnZ2VyZWQ8L2gxPlxuICA8Q3VzdERhdGVQaWNrIHYtbW9kZWw9XCJkYXRhSW5wdXRcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICd5bi1kYXRlLXBpY2snIH07XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIGRhdGFJbnB1dDogc3RyaW5nO1xufT4oKTtcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHM8e1xuICAoZTogJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZTogYW55KTogdm9pZDtcbn0+KCk7XG5cbmNvbnN0IGNoYW5nZSA9ICh2YWx1ZSkgPT4geyAvLyBubyB0cmlnZ2VyXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbiAgZW1pdHMoJ3VwZGF0ZTpkYXRhSW5wdXQnLCB2YWx1ZSk7XG59O1xuY29uc3QgdmlzaWJsZSA9ICh2YWx1ZTogYm9vbGVhbikgPT4geyAvLyB0aGlzIG9rXG4gIGNvbnNvbGUubG9nKHZhbHVlKTtcbn07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgICBAdmlzaWJsZS1jaGFuZ2U9XCJ2aXNpYmxlXCJcbiAgICA6ZGF0YUlucHV0PVwiZGF0YUlucHV0XCIvPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZCBsYW5nPVwic2Nzc1wiPjwvc3R5bGU+IiwiX28iOnt9fQ==) ?
> 
> I'm so confused, what is `:dataInput=`? it's not documented anywhere? And it doesn't work when I try locally

it's an empty string ,share your code with us, then we can check the issue
