### ISSUE TITLE
[Component] [pagination] 切换每页展示数后，会触发了页码的变化

### ISSUE THREAD

**Issue by orochitian** [element-plus/element-plus#10916]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `chrome 107.0.5304.123（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5jb25zdCB0b3RhbCA9IHJlZigxMDApXG5jb25zdCBwYWdlU2l6ZSA9IHJlZigxMClcbmNvbnN0IHBhZ2VJbmRleCA9IHJlZigxKVxuXG5jb25zdCBwYWdlQ2hhbmdlID0gKHBhZ2UpID0+IHtcbiAgY29uc29sZS5sb2cocGFnZSlcbiAgcGFnZUluZGV4LnZhbHVlID0gcGFnZVxufVxuY29uc3Qgc2l6ZUNoYW5nZSA9IChzaXplKSA9PiB7XG4gIGNvbnNvbGUubG9nKHNpemUpXG4gIHBhZ2VTaXplLnZhbHVlID0gc2l6ZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXBhZ2luYXRpb24gYmFja2dyb3VuZCBsYXlvdXQ9XCJ0b3RhbCwgcHJldiwgcGFnZXIsIG5leHQsIHNpemVzXCIgOnBhZ2Utc2l6ZXM9XCJbMTAsIDIwLCAzMF1cIlxuICAgICAgc2l6ZT1cInNtYWxsXCIgOnRvdGFsPVwidG90YWxcIiA6cGFnZS1zaXplPVwicGFnZVNpemVcIiA6Y3VycmVudC1wYWdlPVwicGFnZUluZGV4XCIgQHVwZGF0ZTpjdXJyZW50LXBhZ2U9XCJwYWdlQ2hhbmdlXCIgQHVwZGF0ZTpwYWdlLXNpemU9XCJzaXplQ2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、分页跳转到最后一页
2、切换每页展示数量为30条
3、由于当前页码无效，自动变为最大有效页码，导致触发pageChange事件

### What is Expected?

只触发对应的sizeChange事件

### What is actually happening?

跳转第10页后，切换每页展示先触发了sizeChange后，由于分页已经不足10页，导致页码改变，触发了pageChange事件

### Additional comments

一般会根据具体事件回调，来通知父组件更新数据。理论上来说，应该对应的事件只有在用户操作的时候才被触发。否则在类似示例中这种被动触发的情况下，往往我只是切换了pageSize，却由于页码不匹配，导致pageChange也被调用。父组件会请求两次接口。

**Comment by orochitian** [comment]
我想要么消除类似切换分页展示数量后造成类似current-page改变的副作用。
要么提供一个类似 change 的公共事件。
在同一个事件中，提供page和size两个参数，用户自己处理相应逻辑。

**Comment by btea** [comment]
或许可以[这样](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7cmVmLCB3YXRjaH0gZnJvbSAndnVlJ1xuY29uc3QgdG90YWwgPSByZWYoMTAwKVxuY29uc3QgcGFnZVNpemUgPSByZWYoMTApXG5jb25zdCBwYWdlSW5kZXggPSByZWYoMSlcblxuY29uc3QgcGFnZUNoYW5nZSA9IChwYWdlKSA9PiB7XG4gIGNvbnNvbGUubG9nKHBhZ2UpXG4gIHBhZ2VJbmRleC52YWx1ZSA9IHBhZ2Vcbn1cbmNvbnN0IHNpemVDaGFuZ2UgPSAoc2l6ZSkgPT4ge1xuICBjb25zb2xlLmxvZyhzaXplKVxuICBwYWdlU2l6ZS52YWx1ZSA9IHNpemVcbiAgcGFnZUluZGV4LnZhbHVlID0gMVxufVxuXG53YXRjaChbcGFnZUluZGV4LCBwYWdlU2l6ZV0sICgpID0+IHtcbiAgY29uc29sZS5sb2coJ+ivt+axgicpXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXBhZ2luYXRpb24gYmFja2dyb3VuZCBsYXlvdXQ9XCJ0b3RhbCwgcHJldiwgcGFnZXIsIG5leHQsIHNpemVzXCIgOnBhZ2Utc2l6ZXM9XCJbMTAsIDIwLCAzMF1cIlxuICAgICAgc2l6ZT1cInNtYWxsXCIgOnRvdGFsPVwidG90YWxcIiA6cGFnZS1zaXplPVwicGFnZVNpemVcIiA6Y3VycmVudC1wYWdlPVwicGFnZUluZGV4XCIgQHVwZGF0ZTpjdXJyZW50LXBhZ2U9XCJwYWdlQ2hhbmdlXCIgQHVwZGF0ZTpwYWdlLXNpemU9XCJzaXplQ2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)写。

**Comment by orochitian** [comment]
@btea 非常感谢，这样看来确实可以解决我的问题。还是希望官方能从组件方面有更完善的功能。
