### ISSUE TITLE
[feature request] date selector V-model binding value formatting method

### ISSUE THREAD

**Issue by guagezuishuai** [element-plus/element-plus#1091]
### Existing Component
Yes

### Component Name
DatePicker

### Description
现在返回值是个date格式，我希望能像element一样有个value-formatter来格式化返回值的格式

**Comment by zazzaz** [comment]
Duplicate of #1068

https://github.com/element-plus/element-plus/issues/1068#issuecomment-748966501

**Comment by iamkun** [comment]
fixed in #2120
