### ISSUE TITLE
[Component] [upload] el-upload在list-type="picture-card"和使用limit属性时 上传按钮是否应该自动判断是否消失？

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#10920]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `版本 102.0.5005.115（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICBsaXN0LXR5cGU9XCJwaWN0dXJlLWNhcmRcIlxuICAgIDpvbi1wcmV2aWV3PVwiaGFuZGxlUGljdHVyZUNhcmRQcmV2aWV3XCJcbiAgICA6b24tcmVtb3ZlPVwiaGFuZGxlUmVtb3ZlXCJcbiAgICA6bGltaXQ9XCIzXCJcbiAgPlxuICAgIDxlbC1pY29uPjxQbHVzIC8+PC9lbC1pY29uPlxuICA8L2VsLXVwbG9hZD5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCI+XG4gICAgPGltZyB3LWZ1bGwgOnNyYz1cImRpYWxvZ0ltYWdlVXJsXCIgYWx0PVwiUHJldmlldyBJbWFnZVwiIC8+XG4gIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbiAge1xuICAgIG5hbWU6ICdmb29kLmpwZWcnLFxuICAgIHVybDogJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzYzLzRlN2YzYTE1NDI5YmZkYTk5YmNlNDJhMThjZGQxanBlZy5qcGVnP2ltYWdlTW9ncjIvdGh1bWJuYWlsLzM2MHgzNjAvZm9ybWF0L3dlYnAvcXVhbGl0eS8xMDAnLFxuICB9LFxuICB7XG4gICAgbmFtZTogJ3BsYW50LTEucG5nJyxcbiAgICB1cmw6ICcvaW1hZ2VzL3BsYW50LTEucG5nJyxcbiAgfSxcbiAge1xuICAgIG5hbWU6ICdmb29kLmpwZWcnLFxuICAgIHVybDogJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzYzLzRlN2YzYTE1NDI5YmZkYTk5YmNlNDJhMThjZGQxanBlZy5qcGVnP2ltYWdlTW9ncjIvdGh1bWJuYWlsLzM2MHgzNjAvZm9ybWF0L3dlYnAvcXVhbGl0eS8xMDAnLFxuICB9LFxuXG5dKVxuXG5jb25zdCBkaWFsb2dJbWFnZVVybCA9IHJlZignJylcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAodXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2codXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVBpY3R1cmVDYXJkUHJldmlldzogVXBsb2FkUHJvcHNbJ29uUHJldmlldyddID0gKHVwbG9hZEZpbGUpID0+IHtcbiAgZGlhbG9nSW1hZ2VVcmwudmFsdWUgPSB1cGxvYWRGaWxlLnVybCFcbiAgZGlhbG9nVmlzaWJsZS52YWx1ZSA9IHRydWVcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

当list-type="picture-card" 和:limit="3"时，上传3张图后上传按钮仍旧存在。

### What is Expected?

上传按钮应该消失

### What is actually happening?

上传按钮仍旧存在

### Additional comments

_(empty)_

**Comment by liufang8** [comment]
Can this problem be solved ?

**Comment by edwinhuish** [comment]
自己判断一下文件数量是否大于等于limit，写个css `display;none;` 就好了

**Comment by PeyFon** [comment]
> 自己判断一下文件数量是否大于等于limit，写个css `display;none;` 就好了

我只是单纯觉得这种事组件内部去处理，体验上会更好一些

**Comment by HeftyKoo** [comment]
> 

Issue 我先关了，我觉得这个可能还是使用方自己处理会比较好点，可能还需要配合一些提示，这样按钮消失的时候不会太突兀。

**Comment by HeftyKoo** [comment]
> > 自己判断一下文件数量是否大于等于limit，写个css `display;none;` 就好了
> 
> 我只是单纯觉得这种事组件内部去处理，体验上会更好一些

Issue 我先关了，我觉得这个可能还是使用方自己处理会比较好点，可能还需要配合一些提示，这样按钮消失的时候不会太突兀。
