### ISSUE TITLE
[Style] [autocomplete] ElAutocomplete clearable = true时样式抖动

### ISSUE THREAD

**Issue by hovees** [element-plus/element-plus#10924]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzdGF0ZTEgPSByZWYoJ2hlbGxvIHdvcmxkIScpXG5cbmNvbnN0IHF1ZXJ5U2VhcmNoID0gKHF1ZXJ5U3RyaW5nOiBzdHJpbmcsIGNiOiBhbnkpID0+IHtcbiAgY2IoW3sgdmFsdWU6IHF1ZXJ5U3RyaW5nIH1dKVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcm93PlxuICAgIDxlbC1jb2wgOnNwYW49XCIxMlwiPlxuICAgICAgPGVsLWF1dG9jb21wbGV0ZVxuICAgICAgICB2LW1vZGVsPVwic3RhdGUxXCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgOmZldGNoLXN1Z2dlc3Rpb25zPVwicXVlcnlTZWFyY2hcIlxuICAgICAgLz5cbiAgICAgIDxlbC1idXR0b24+QnV0dG9uPC9lbC1idXR0b24+XG4gICAgPC9lbC1jb2w+XG4gIDwvZWwtcm93PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

鼠标focus在input框，clear按钮出现时input会变长，导致同一行组件位置会抖动

### What is Expected?

input框长度不变，参考2.1.8版本

### What is actually happening?

input框长度变化

### Additional comments

_(empty)_

**Comment by yuniit** [comment]
I ran into this issue too, set width to component and it worked fine

**Comment by loosheng** [comment]
Related: #7287

**Comment by tolking** [comment]
Link #7287
