### ISSUE TITLE
[bug report] upload component 1. The limit (the maximum number of uploads) does not work. 2. The on exceeded event (hook when the number of files exceeds the limit) is not executed

### ISSUE THREAD

**Issue by LYao0919** [element-plus/element-plus#1093]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
mac chrome

### Vue version
3.0.4

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
upload 组件    
1、limit （最大允许上传个数 ）限制不起作用   
2、 on-exceed事件（文件超出个数限制时的钩子）不执行 

### What is Expected?
可以正常限制文件个数

### What is actually happening?
目前无法限制文件个数

**Comment by JeremyWuuuuu** [comment]
Got it, I'll go investigate it.

**Comment by JeremyWuuuuu** [comment]
Hi, sorry for the staled response, could you give me a minimal reproducible version? I have verified on the doc website. On exceed seemed to work.
![image](https://user-images.githubusercontent.com/15975785/104918518-da452900-59cf-11eb-9ae7-08c0fa951855.png)
![image](https://user-images.githubusercontent.com/15975785/104918532-e03b0a00-59cf-11eb-9d34-ef5f312dfec9.png)
