### ISSUE TITLE
[Component] [form-item, date-picker] <el-form-item label=""> + <el-date-picker>  date-picker的type值为daterange时，form-item内的label样式不会变（不会加粗）

### ISSUE THREAD

**Issue by ZeroStarkW** [element-plus/element-plus#10932]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome  108.0.5359.73`
- Build Tool: `Vite`

### Related Component

- `el-form-item`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1mb3JtPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWTiOWTiOWTiFwiPlxuICAgICAgICA8ZWwtaW5wdXQ+PC9lbC1pbnB1dD5cbiAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWYu+WYu+WTiOWTiFwiPlxuICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiPlxuXG4gICAgICAgIDwvZWwtZGF0ZS1waWNrZXI+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

date-picker 的type值改为daterange

### What is Expected?

form内的 form-item 的label样式一致

### What is actually happening?

date-picker 的 form-item 的label样式不一样(不加粗)

### Additional comments

element-plus 版本切回 2.1.x 就没问题

![image](https://user-images.githubusercontent.com/54435165/206403798-f2f0eb64-9e13-44e1-9cc9-2aced24e42e5.png)

**Comment by atJiangBei** [comment]
因为那个label  有时候是label标签  有时候会是div标签。确实是个问题，给那个标签都加上同样的字体font-weight

**Comment by init-qy** [comment]
`daterange`的实现是两个原生input，所以它不会被form认为需要换成label标签，
有个非常奇怪的做法是在之后加个不显示的`el-input`
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1mb3JtPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWTiOWTiOWTiFwiPlxuICAgICAgICA8ZWwtaW5wdXQ+PC9lbC1pbnB1dD5cbiAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5Zi75Zi75ZOI5ZOIXCI+XG4gICAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICB0eXBlPVwiZGF0ZXJhbmdlXCI+XG5cbiAgICAgICAgPC9lbC1kYXRlLXBpY2tlcj5cbiAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWYu+WYu+WTiOWTiFwiPlxuICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiPlxuXG4gICAgICAgIDwvZWwtZGF0ZS1waWNrZXI+XG4gICAgICAgIDxlbC1pbnB1dCB2LXNob3c9XCJmYWxzZVwiPjwvZWwtaW5wdXQ+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuICBsYWJlbHtcbiAgICBmb250LXdlaWdodDogNzAwXG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
