### ISSUE TITLE
[Component] [tree] el-tree拖拽Level three 3-1-1这一行不能拖拽

### ISSUE THREAD

**Issue by 634019392** [element-plus/element-plus#10941]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.26`
- Browser / OS: `Chrome108.0.5359.96/win10`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tree.html#%E5%8F%AF%E6%8B%96%E6%8B%BD%E8%8A%82%E7%82%B9)

### Steps to reproduce

el-tree拖拽Level three 3-1-1这一行不能拖拽

### What is Expected?

能够拖拽

### What is actually happening?

不能这样

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
![image](https://user-images.githubusercontent.com/59350883/206643778-279e25c9-6d1e-48c8-8b40-b42d24487b7a.png)
注意看文档

**Comment by 634019392** [comment]
@init-qy ok!ok!谢谢，没有注意到
