### ISSUE TITLE
[Style] 在 el-popover 里使用 el-tab ，当前激活的 tab-pane 下划线定位不准

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#10976]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46`
- Build Tool: `Vite`

### Related Component

- `el-tabs`
- `el-tab-pane`
- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHJlZj1cImJ1dHRvblJlZlwiIHYtY2xpY2stb3V0c2lkZT1cIm9uQ2xpY2tPdXRzaWRlXCJcbiAgICA+Q2xpY2sgbWU8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLXBvcG92ZXJcbiAgICByZWY9XCJwb3BvdmVyUmVmXCJcbiAgICA6dmlydHVhbC1yZWY9XCJidXR0b25SZWZcIlxuICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgdGl0bGU9XCJXaXRoIHRpdGxlXCJcbiAgICA6d2lkdGg9XCIzNTBcIlxuICAgIHZpcnR1YWwtdHJpZ2dlcmluZ1xuICA+XG4gICAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiBjbGFzcz1cImRlbW8tdGFic1wiIEB0YWItY2xpY2s9XCJoYW5kbGVDbGlja1wiPlxuICAgICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVXNlclwiIG5hbWU9XCJmaXJzdFwiPlVzZXI8L2VsLXRhYi1wYW5lPlxuICAgICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiQ29uZmlnXCIgbmFtZT1cInNlY29uZFwiPkNvbmZpZzwvZWwtdGFiLXBhbmU+XG4gICAgPC9lbC10YWJzPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB1bnJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENsaWNrT3V0c2lkZSBhcyB2Q2xpY2tPdXRzaWRlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuY29uc3QgYnV0dG9uUmVmID0gcmVmKClcbmNvbnN0IHBvcG92ZXJSZWYgPSByZWYoKVxuY29uc3Qgb25DbGlja091dHNpZGUgPSAoKSA9PiB7XG4gIHVucmVmKHBvcG92ZXJSZWYpLnBvcHBlclJlZj8uZGVsYXlIaWRlPy4oKVxufVxuXG5jb25zdCBhY3RpdmVOYW1lID0gcmVmKCdmaXJzdCcpXG5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKHRhYjogVGFic1BhbmVDb250ZXh0LCBldmVudDogRXZlbnQpID0+IHtcbiAgY29uc29sZS5sb2codGFiLCBldmVudClcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuLmRlbW8tdGFicyAuZWwtdGFic19fbmF2LXNjcm9sbCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xufVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

参考复现链接

### What is Expected?

经测试，EP版本在2.2.17时效果正常，之后的版本就一直都有这问题

### What is actually happening?

tab选项卡的激活下划线定位不准确

### Additional comments

_(empty)_

**Comment by btea** [comment]
Seems related to #9896

**Comment by chenxch** [comment]
@holazz Can you help me with this question?

**Comment by holazz** [comment]
> @holazz Can you help me with this question?

OK, I will investigate tomorrow.
