### ISSUE TITLE
[Component] [date-picker] el-date-picker

### ISSUE THREAD

**Issue by z100h100** [element-plus/element-plus#10990]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoJzE2NjcyMzIwMDAwMDAnKVxuY29uc3QgdmFsdWUyID0gcmVmKDE2NjcyMzIwMDAwMDApXG5jb25zdCBhYSA9IG5ldyBEYXRlKHZhbHVlMi52YWx1ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICAgICAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgICAgICAgICAgICB0eXBlPVwibW9udGhcIlxuICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgbW9udGhcIlxuICAgICAgICAgICAgICAgICAgLz5cbiAgPHA+XG4gIHt7YWF9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

see link

### What is Expected?

quick quick quick quick

### What is actually happening?

see link

### Additional comments

see link

**Comment by tolking** [comment]
Number string cannot be parsed

**Comment by z100h100** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
