### ISSUE TITLE
[bug report] for tree components, when dragtable is set, nodes cannot be added dynamically

### ISSUE THREAD

**Issue by qqqdu** [element-plus/element-plus#1099]
### Element Plus version
1.0.1-beta.11

### OS/Browsers version
chrome 任何版本

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/qqqdu/pen/yLazvez

### Steps to reproduce
- 给 el-tree 添加 draggable 属性
- 点击 Append 按钮添加子元素
- 点击子元素的 Delete 按钮

### What is Expected?
子元素应该如官网的预期被删除

### What is actually happening?
实际上什么也没有发生

**Comment by JeremyWuuuuu** [comment]
cc @bastarder

**Comment by JeremyWuuuuu** [comment]
Thank you, we will investigate the root cause!

**Comment by bastarder** [comment]
i open your reproduction link, every thing is ok, maybe you should look at `this.data = [...this.data]`, this is important for update tree, i think we can optimize this. you can try this first.

**Comment by qqqdu** [comment]
你可以clone下我创建的这个测试项目，复现路径和上面说的一样

https://github.com/qqqdu/element-tree-bug

> i open your reproduction link, every thing is ok, maybe you should look at `this.data = [...this.data]`, this is important for update tree, i think we can optimize this. you can try this first.

**Comment by JeremyWuuuuu** [comment]
See the screen recording below, seems the append operation has performed, but the UI didn't get updated at the same time, but until you fold the node, then expand it, it appears.
https://user-images.githubusercontent.com/15975785/103399405-f34e7d00-4b7b-11eb-850b-bb07d0065e2f.mov

**Comment by JeremyWuuuuu** [comment]
After I played the demo and made some modification against your code, I found out that, `tree-node` did not watch the children's length changing(it did watch the value change), when `tree-node`'s children length gets updated, UI did not get updated.

**Comment by JeremyWuuuuu** [comment]
But the way you use it is considered wrong, you do not have to do all the re-assignment to `:data`. Simply update the current layer will be just fine.

**Comment by JeremyWuuuuu** [comment]
So as it has been confirmed as a bug, then it needs to be fixed, thanks for the bug report.
