### ISSUE TITLE
[Component] [badge] 当badge组件的父元素为纵向弹性时，badge被迫宽度最大

### ISSUE THREAD

**Issue by dyggod** [element-plus/element-plus#11001]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.26`
- Browser / OS: `Edge/108.0.1462.46 （win11）`
- Build Tool: `Vite`

### Related Component

- `el-badge`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtblwiPlxuICAgICAgPGVsLWJhZGdlIDp2YWx1ZT1cIjI1XCI+XG4gICAgICAgIDxlbC1idXR0b24+YmFkZ2U8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtYmFkZ2U+XG4gICAgICA8ZWwtYmFkZ2UgOnZhbHVlPVwiMjVcIiA6bWF4PVwiMTBcIj5cbiAgICAgICAgPGVsLWJ1dHRvbj5iYWRnZTwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC1iYWRnZT5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. 引入el-badge组件
2. 在使用el-badge组件时设置其父组件样式为："display:flex;flex-direction:column"

### What is Expected?

徽章组件正常显示

### What is actually happening?

徽章组件的宽度被弹性影响，导致徽章数移位到最右边

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/49914353/207997931-8cbd0b06-e4fc-4188-96ee-b06b9b879ef8.png)

**Comment by ryuhangyeong** [comment]
Wouldn't using inline-flex help solve your problem?

[Element Plus Example(https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTppbmxpbmUtZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW5cIj5cbiAgICAgIDxlbC1iYWRnZSA6dmFsdWU9XCIyNVwiPlxuICAgICAgICA8ZWwtYnV0dG9uPmJhZGdlMTE8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtYmFkZ2U+XG4gICAgICA8ZWwtYmFkZ2UgOnZhbHVlPVwiMjVcIiA6bWF4PVwiMTBcIj5cbiAgICAgICAgPGVsLWJ1dHRvbj5iYWRnZTwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC1iYWRnZT5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by zhanggaodu1** [comment]
原因：设置flex-direction:column会更改主轴方向为垂直，主轴方向垂直内的子元素会垂直排列
解决办法：el-badge上套一层div

**Comment by acyza** [comment]
给el-badge加align-self: start
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICAuZWwtYmFkZ2Uge1xuICAgIGFsaWduLXNlbGY6IHN0YXJ0O1xuICB9XG48L3N0eWxlPlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OmZsZXg7ZmxleC1kaXJlY3Rpb246Y29sdW1uXCI+XG4gICAgICA8ZWwtYmFkZ2UgOnZhbHVlPVwiMjVcIj5cbiAgICAgICAgPGVsLWJ1dHRvbj5iYWRnZTwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC1iYWRnZT5cbiAgICAgIDxlbC1iYWRnZSA6dmFsdWU9XCIyNVwiIDptYXg9XCIxMFwiPlxuICAgICAgICA8ZWwtYnV0dG9uPmJhZGdlPC9lbC1idXR0b24+XG4gICAgICA8L2VsLWJhZGdlPlxuICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by dyggod** [comment]
> 给el-badge加align-self: start [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICAuZWwtYmFkZ2Uge1xuICAgIGFsaWduLXNlbGY6IHN0YXJ0O1xuICB9XG48L3N0eWxlPlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OmZsZXg7ZmxleC1kaXJlY3Rpb246Y29sdW1uXCI+XG4gICAgICA8ZWwtYmFkZ2UgOnZhbHVlPVwiMjVcIj5cbiAgICAgICAgPGVsLWJ1dHRvbj5iYWRnZTwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC1iYWRnZT5cbiAgICAgIDxlbC1iYWRnZSA6dmFsdWU9XCIyNVwiIDptYXg9XCIxMFwiPlxuICAgICAgICA8ZWwtYnV0dG9uPmJhZGdlPC9lbC1idXR0b24+XG4gICAgICA8L2VsLWJhZGdlPlxuICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

good！是临时解决办法，上面有个PR应该能解决这个问题。
