### ISSUE TITLE
[Style] 如果设置了img标签的width属性，会自动重置为width="0"

### ISSUE THREAD

**Issue by iquanxin** [element-plus/element-plus#11014]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXHQ8aW1nIHNyYz1cImh0dHBzOi8vcTQucWxvZ28uY24vZz9iPXFxJm5rPTU4MzA4MTcxM0BxcS5jb20mcz0zXCIgYWx0PVwiXCIgd2lkdGg9XCI1MCVcIj5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开链接，查看效果及源代码

### What is Expected?

图片属性width="50%"，不改变此属性

### What is actually happening?

图片属性width="0"

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这个是vue的表现哦，你可以看下以下两份资料。
[img width](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width)
[vue-sfc](https://sfc.vuejs.org/#eNp9UstOwzAQ/JXFEqQVJG5VKqoqKXCoxJFTueSSpm7q4ldspxWK8u+s00AviJx2Z3cm47Fb8mpMcmoYWZLUlZYbD475xqxyxaXR1kMLlu2hg73VEiJcjXKVq1Ir50G6CrIwH0VvTAgNH9qK3U00zlVKL3IohI1n0ojCM+wA0sN01bY9uetSil2PcmUaD6dY6h0TWU5wnpP/CEzEf3KAhp/6lMsKnC0RPnhv3JLS+jGpha50UipaPW+zur5Tn9l8MZsspk/T2UtdJ6WWdy6boUohPFKxOPOdP2A5n9z+GAr5AH69B8wCSi20xZ1TYUdxjGgPxMZyWdivMfLStWCSKf8uGocOUzpQB6VhCv0YD7s2G2YdR+mug3vYNCygGP8V7p3QYCWlvwGTB3K5uFgWJjk6rfBq27CaDwOXkyX0SMBQMfTXjNy+DA/i6BJtK4pVYhvluWQJczLeWn12zKIwRoMSaKIj3TeSE8Jt)

**Comment by chenxch** [comment]
link [vue issue](https://github.com/vuejs/core/issues/3545)
