### ISSUE TITLE
[Component] [message-box] 直接 ElMessageBox 设置 inputValidator 验证不生效

### ISSUE THREAD

**Issue by hwd-2020** [element-plus/element-plus#11027]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `windows10`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAnMjIyMjIyJyxcbiAgICBtZXNzYWdlOiAnMTExMTExJyxcbiAgICBzaG93SW5wdXQ6IHRydWUsXG4gICAgaW5wdXRWYWxpZGF0b3I6ICh2YWx1ZSkgPT4gdmFsdWUgPT0gMTIzNDU2LFxuICAgIGlucHV0RXJyb3JNZXNzYWdlOiAnZmZmZmZmZidcbiAgfSlcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

输入后不会验证

### What is Expected?

可以验证

### What is actually happening?

不验证

### Additional comments

_(empty)_

**Comment by btea** [comment]
You can add `boxType: 'prompt'`.

**Comment by hwd-2020** [comment]
> 

搞定！👍
