### ISSUE TITLE
Message and Notification is not showing up

### ISSUE THREAD

**Issue by martinsura** [element-plus/element-plus#1103]
Hello,
First thanks for working on this nice library.

I have problem with messege or notification component 

component.tsx
```
import { ElMessage } from "element-plus";
import { defineComponent } from "vue";

export const TestComponent = defineComponent({
  setup(props) {

    onMounted(() => {
      ElMessage({type:"success",message:"notification"});
    });
    return () => {
      return (
         <div>content</div>
      );
    };
  },
});
```

registration: (main.ts)

```
import ElementPlus from "element-plus";
App.use(ElementPlus);
App.mount("#app");
```

Apps works normally (no error), but message or notification not showing up.

![image](https://user-images.githubusercontent.com/333932/103040411-a236fb80-4573-11eb-9ea5-4ea5bfc7f21c.png)

Div is inserted to DOM and not deleted.

Versions:
```
"vue": "^3.0.4",
"element-plus": "^1.0.1-beta.14",
"@vue/babel-plugin-jsx": "^1.0.0-rc.5",
```

I am wrong or this is bug?

**Comment by zazzaz** [comment]
a reproduction demo, please?

**Comment by JeremyWuuuuu** [comment]
Have you configure your app with `JSX`?

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/103055829-4a7dac00-45d6-11eb-80a3-edc21c190e97.png)
You can see the image, that everything looks fine on codepen.

With code:

```html
<script src="//unpkg.com/vue@next"></script>
<script src="//unpkg.com/element-plus/lib/index.full.js"></script>
<div id="app">
  <div>content</div>
</div>
```

```css
@import url("//unpkg.com/element-plus/lib/theme-chalk/index.css");
```

```js
const { defineComponent, h, onMounted, onUpdated } = Vue;
const { ElMessage } = ElementPlus;
var Main = defineComponent({
  setup(props) {
    onMounted(() => {
      ElMessage({ type: "success", message: "notification" });
    });
    onUpdated(() => {
      ElMessage({ type: "success", message: "notification" });
    });
  }
  
});
const app = Vue.createApp(Main);
app.use(ElementPlus);
app.mount("#app");

```

**Comment by martinsura** [comment]
Yes, I use only jsx (tsx) in application. Transpile with babel via @vue/babel-plugin-jsx.
Maybe this is not bug in this library, but I have problem with transpile. When I will be around my dev pc, check it out. Thanks

**Comment by JeremyWuuuuu** [comment]
You may need to use @vue/jsx-next try to search it in there organization

**Comment by martinsura** [comment]
Sure, thanks for pointing. And sorry for wrong bug.

**Comment by JeremyWuuuuu** [comment]
No worries, glad we can help
