### ISSUE TITLE
[Docs] 执行 npm run docs:build 报错

### ISSUE THREAD

**Issue by odlnt** [element-plus/element-plus#11032]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/dev/docs/.vitepress/plugins/markdown-transform.ts)

### Steps to reproduce

1、MD文档二级标题使用中文
2、执行pnpm run docs:build

### What is Expected?

build成功

### What is actually happening?

出现报错信息，文档build失败。

### Additional comments

确认ElementPlus官方文档站点打包脚本两处比较隐蔽的正则表达式匹配bug，这个bug可导致站点打包报错。bug位于：docs\.vitepress\plugins\markdown-transform.ts。

bug 1：  const frontmatterEnds = code.indexOf('---\n\n') + 4
原因解释：此bug中，\n\n实际可能匹配到非预期位置，或匹配不到连续两个换行，因为code中，连续两行可能是\r\n\r\n
解决方案：对code作替换换行符预处理，code = code.replace(/\r\n/g, '\n')

bug2：  const firstSubheader = code.search(/\n## \w/)
原因解释：此行希望匹配md文档中的子标题，子标题预期是 ## \w，这意味着只能匹配到英文、数字或下划线开始的标题，如果是中文标题，会匹配失败。
解决方案：code.search(/## \w/) 正则表达式改为 code.search(/\n## [\w\u4e00-\u9fa5]/)

**Comment by init-qy** [comment]
我稍微解释下，不是官方，以下仅代表我个人观点，
1. `\r\n`不会被考虑在内，因为不管是git还是code规范，都是`lf`优先，即code以`\n`结尾，建议是把git的`autocrlf`关掉(`git config --global core.autocrlf false`)，我吃过几次亏
https://github.com/element-plus/element-plus/blob/74e6e8d105a475957e8b93b4b2f8c1e40f14c501/.editorconfig#L7
2. ep源码文档中就没有中文，默认就是以英文打包的，应该是考虑到编码问题或者可能带来的麻烦的正则匹配，不管怎么说，既然有预期就不能算问题
