### ISSUE TITLE
[Style] [popover] popover弹出框内嵌select选择器，会出现选择完select关闭popover的情况（请尽快回复）

### ISSUE THREAD

**Issue by laobieyi** [element-plus/element-plus#11040]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlclwiPlxuICAgIDxlbC1wb3BvdmVyIHBsYWNlbWVudD1cInJpZ2h0XCIgOndpZHRoPVwiNDAwXCIgdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgPGVsLWJ1dHRvbiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMTZweFwiPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwiZ3JpZFwiPlxuICAgICAgXHQ8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBncmlkRGF0YVwiIDpsYWJlbD1cIml0ZW0uZGF0ZVwiIDp2YWx1ZT1cIml0ZW0uZGF0ZVwiPjwvZWwtb3B0aW9uPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9lbC1wb3BvdmVyPlxuXG4gICAgPGVsLXBvcG92ZXJcbiAgICAgIDp3aWR0aD1cIjMwMFwiXG4gICAgICBwb3BwZXItc3R5bGU9XCJib3gtc2hhZG93OiByZ2IoMTQgMTggMjIgLyAzNSUpIDBweCAxMHB4IDM4cHggLTEwcHgsIHJnYigxNCAxOCAyMiAvIDIwJSkgMHB4IDEwcHggMjBweCAtMTVweDsgcGFkZGluZzogMjBweDtcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICA8ZWwtYXZhdGFyIHNyYz1cImh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS83MjAxNTg4Mz92PTRcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgPGRpdlxuICAgICAgICAgIGNsYXNzPVwiZGVtby1yaWNoLWNvbmVudFwiXG4gICAgICAgICAgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBnYXA6IDE2cHg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW5cIlxuICAgICAgICA+XG4gICAgICAgICAgPGVsLWF2YXRhclxuICAgICAgICAgICAgOnNpemU9XCI2MFwiXG4gICAgICAgICAgICBzcmM9XCJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvNzIwMTU4ODM/dj00XCJcbiAgICAgICAgICAgIHN0eWxlPVwibWFyZ2luLWJvdHRvbTogOHB4XCJcbiAgICAgICAgICAvPlxuICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgICA8cFxuICAgICAgICAgICAgICBjbGFzcz1cImRlbW8tcmljaC1jb250ZW50X19uYW1lXCJcbiAgICAgICAgICAgICAgc3R5bGU9XCJtYXJnaW46IDA7IGZvbnQtd2VpZ2h0OiA1MDBcIlxuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICBFbGVtZW50IFBsdXNcbiAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDxwXG4gICAgICAgICAgICAgIGNsYXNzPVwiZGVtby1yaWNoLWNvbnRlbnRfX21lbnRpb25cIlxuICAgICAgICAgICAgICBzdHlsZT1cIm1hcmdpbjogMDsgZm9udC1zaXplOiAxNHB4OyBjb2xvcjogdmFyKC0tZWwtY29sb3ItaW5mbylcIlxuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICBAZWxlbWVudC1wbHVzXG4gICAgICAgICAgICA8L3A+XG4gICAgICAgICAgPC9kaXY+XG5cbiAgICAgICAgICA8cCBjbGFzcz1cImRlbW8tcmljaC1jb250ZW50X19kZXNjXCIgc3R5bGU9XCJtYXJnaW46IDBcIj5cbiAgICAgICAgICAgIEVsZW1lbnQgUGx1cywgYSBWdWUgMyBiYXNlZCBjb21wb25lbnQgbGlicmFyeSBmb3IgZGV2ZWxvcGVycyxcbiAgICAgICAgICAgIGRlc2lnbmVycyBhbmQgcHJvZHVjdCBtYW5hZ2Vyc1xuICAgICAgICAgIDwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtcG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuICBjb25zdCBncmlkID0gcmVmKCcnKVxuY29uc3QgZ3JpZERhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ0phY2snLFxuICAgIGFkZHJlc3M6ICdOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnSmFjaycsXG4gICAgYWRkcmVzczogJ05ldyBZb3JrIENpdHknLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKYWNrJyxcbiAgICBhZGRyZXNzOiAnTmV3IFlvcmsgQ2l0eScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ0phY2snLFxuICAgIGFkZHJlc3M6ICdOZXcgWW9yayBDaXR5JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

如链接

### What is Expected?

选择完select之后不关闭popover

### What is actually happening?

选择完select之后关闭popover

### Additional comments

请尽快回复！感谢

**Comment by wen-lun** [comment]
我的解决方法是给select组件的teleported属性传递为false

**Comment by laobieyi** [comment]
> 

是可用的，已采纳！谢谢

**Comment by XiaoBaiClassmate** [comment]
Element Plus Version: 2.2.27 
也有这个问题。目前 采用 `wen-lun` 方案
