### ISSUE TITLE
[Component] [form] Nuxt 3 Compatibility

### ISSUE THREAD

**Issue by saddam-azad** [element-plus/element-plus#11043]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Firefox 107.0.1 (64-bit) / Windows 11`
- Build Tool: `Nuxt`

### Related Component

- `el-form`
- `el-form-item`
- `el-select`
- `el-option`

### Reproduction Link

[Github Repo](https://github.com/saddam-azad/nuxt3-element-plus)

### Steps to reproduce

Clone source and `npm install & npm run dev`

### What is Expected?

1. Dynamically hydrated `el-select` and `el-option` shows `[object Object]` as label. 

Expected behaviour: The `default-first-option` parameter should select the first option and display appropriate label.

### What is actually happening?

The first dropdown displays a list fetched from an endpoint. 
The user selects an item, it triggers another fetch request to another endpoint.
The data is supposed to hydrate the second dropdown.

Despite showing `[object Object]` as label, the second dropdown list does hydrate. Once you select and re-open the dropdown, the item labels become blank (bug).

### Additional comments

2. Form validation rules do not work. 

3. On Form Submit event, the `fields` property returns `undefined`.

![screenshot-localhost_3000-2022 12 16-21_51_39](https://user-images.githubusercontent.com/399195/208782509-b39471c8-0320-4e7f-80d5-9141d93a0a18.png)

**Comment by webvs2** [comment]
[](https://element-plus.run)  Please provide a duplicate code

**Comment by saddam-azad** [comment]
> Please provide a duplicate code：https://element-plus.run

@webvs2 Playground could not be used because this requires "nuxt": "3.0.0" in composer.json

Please clone repo in local drive to test code.

**Comment by tolking** [comment]
[L108](https://github.com/saddam-azad/nuxt3-element-plus/blob/main/app.vue#L108)
