### ISSUE TITLE
[bug report] component < El date picker / >, after clicking the clear button, the last selected state is not cleared in the drop-down list

### ISSUE THREAD

**Issue by Grubby520** [element-plus/element-plus#1105]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
Google chrome 版本 86.0.4240.111（正式版本)

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/Grubby520/pen/BaLwMEZ

### Steps to reproduce
1、<el-date-picker />，选中一个日期范围；
2、清除选中的值；
3、点击input框，下拉列表中上次选中的值未被清除掉；

### What is Expected?
未重置

### What is actually happening?
actually happened

**Comment by zazzaz** [comment]
Thanks, I tried to reproduce it according to your "Steps to reproduce", but seems everything works fine.

Can you please give us more detail or step to reproduce it?

**Comment by Grubby520** [comment]
> Thanks, I tried to reproduce it according to your "Steps to reproduce", but seems everything works fine.
> 
> Can you please give us more detail or step to reproduce it?
open link https://codepen.io/Grubby520/pen/BaLwMEZ, then you can be able to reproduce the problem.

**Comment by zazzaz** [comment]
Thanks, I do open the link you provided. And try to reproduce the bug.

However, after clicking `clear` button, the input is cleared as expected.

**Comment by bastarder** [comment]
> Thanks, I do open the link you provided. And try to reproduce the bug.
> 
> However, after clicking `clear` button, the input is cleared as expected.

![image](https://user-images.githubusercontent.com/16336681/103069141-b1f92300-45f9-11eb-995c-295da3ec4ea1.png)
i think， the inner input value should updated too~

**Comment by zazzaz** [comment]
bug confirmed, will fix soon
