### ISSUE TITLE
[Component] [input] input使用formatter光标位置错误

### ISSUE THREAD

**Issue by phm-front** [element-plus/element-plus#11059]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Chrome 108.0.5359.98/ macOS 13.1`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBmb3JtYXR0ZXIgPSAodmFsOiBzdHJpbmcgfCBudW1iZXIpID0+IHtcbiAgcmV0dXJuIGAke3ZhbH1gLnJlcGxhY2VBbGwoJzInLCAnIScpXG59XG5jb25zdCBtc2cgPSByZWYoJzIyMjIyMjIyJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIDpmb3JtYXR0ZXI9XCJmb3JtYXR0ZXJcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

input绑定初始值为'22222222'，formatter返回值为`${val}`.replaceAll('2', '!')，光标初始位置处于绑定值中间任意位置，输入字符2，光标会跳到最后位置

### What is Expected?

光标保持在输入位置

### What is actually happening?

光标跳到最后位置

### Additional comments

_(empty)_

**Comment by niuxinyu** [comment]
replaceAll 替换为了一个新的字符串，替换完成之后光标在字符串被顶到最后，感觉应该是正常行为

**Comment by volvachev** [comment]
Hi. The problem is that the formatter is not called during initialization. When this [pr](https://github.com/element-plus/element-plus/pull/10338) is merged, then the cursor will work correctly (the first time a number is entered)

**Comment by tolking** [comment]
This issue appears to have been fixed
