### ISSUE TITLE
[Bug Report] Using <el-select /> with bind value & handleChange method (kind of like controlled component in React), But failed

### ISSUE THREAD

**Issue by wanmaoor** [element-plus/element-plus#1106]
### Element Plus version
1.0.1-beta.6

### OS/Browsers version
Windows10 Google Chrome 87.0.4280.88

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/landvatter/pen/oNzGOzp?editors=1011

### Steps to reproduce
select an option randomly

### What is Expected?
The selected option should appear on the input field

### What is actually happening?
But none of them ever seems to appear on the input field. I know that is approachable by using `v-model`, However, me, a React user, was getting used to the controlled component...

**Comment by bastarder** [comment]
i think you should use `:model-value="value"`, in vue 3.0 the model default props is `modelValue`, try this again ~

**Comment by zouhangwithsweet** [comment]
> i think you should use `:model-value="value"`, in vue 3.0 the model default props is `modelValue`, try this again ~

https://v3.vuejs.org/guide/migration/v-model.html

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by wanmaoor** [comment]
Yes, It's works! So the docs may get an update.
