### ISSUE TITLE
[Component] [input, button] el-button可以改变localStorage的vueuse-color-scheme值为auto

### ISSUE THREAD

**Issue by QingboMa** [element-plus/element-plus#11066]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.19`
- Browser / OS: `Microsoft Edge   版本 108.0.1462.54 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgdXNlUm91dGVyLCB1c2VSb3V0ZSB9IGZyb20gJ3Z1ZS1yb3V0ZXInO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgOm9uY2hhbmdlPVwidG9nZ2xlRGFyaygpXCIgLz5cblx0XHQ8ZWwtbWVudS1pdGVtIGluZGV4PVwiMVwiPkphdmE8L2VsLW1lbnUtaXRlbT5cblx0PC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

   当在的input中输入任何数据，都会引起localStorage的vueuse-color-scheme值在light和auto两者之间变动。从而导致主题在黑白两个主题间改变

### What is Expected?

   当在的input中输入任何数据，不要引起localStorage的vueuse-color-scheme值的变动。不应该导致主题在黑白两个主题间改变

### What is actually happening?

   当在的input中输入任何数据，都会引起localStorage的vueuse-color-scheme值在light和auto两者之间变动。从而导致主题在黑白两个主题间改变

**Comment by acyza** [comment]
你这样例，一手老年disco给我浏览器干崩了😂  
这是修正后的样例[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgQGNoYW5nZT1cInRvZ2dsZURhcmsoIXZhbClcIiAvPlxuXHRcdDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+SmF2YTwvZWwtbWVudS1pdGVtPlxuXHQ8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuMTMuMTEvbGliL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkQDkuMC4wL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAOS4wLjAvaW5kZXgubWpzXCJcbiAgfVxufSIsIl9vIjp7fX0=)

**Comment by QingboMa** [comment]
我的样例就是个大概，主要的是我描述的问题😄> 你这样例，一手老年disco给我浏览器干崩了😂  
> 
> 这是修正后的样例[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgQGNoYW5nZT1cInRvZ2dsZURhcmsoIXZhbClcIiAvPlxuXHRcdDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+SmF2YTwvZWwtbWVudS1pdGVtPlxuXHQ8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuMTMuMTEvbGliL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkQDkuMC4wL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAOS4wLjAvaW5kZXgubWpzXCJcbiAgfVxufSIsIl9vIjp7fX0=)
> 
> 就是不知道它为啥改的不是preview的主题。

**Comment by acyza** [comment]
> 我的样例就是个大概，主要的是我描述的问题😄> 你这样例，一手老年disco给我浏览器干崩了😂
> 
> > 这是修正后的样例[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgQGNoYW5nZT1cInRvZ2dsZURhcmsoIXZhbClcIiAvPlxuXHRcdDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+SmF2YTwvZWwtbWVudS1pdGVtPlxuXHQ8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuMTMuMTEvbGliL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkQDkuMC4wL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAOS4wLjAvaW5kZXgubWpzXCJcbiAgfVxufSIsIl9vIjp7fX0=)
> > 就是不知道它为啥改的不是preview的主题。

我考到本地测了下



> 我的样例就是个大概，主要的是我描述的问题😄> 你这样例，一手老年disco给我浏览器干崩了😂
> 
> > 这是修正后的样例[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgQGNoYW5nZT1cInRvZ2dsZURhcmsoIXZhbClcIiAvPlxuXHRcdDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+SmF2YTwvZWwtbWVudS1pdGVtPlxuXHQ8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuMTMuMTEvbGliL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkQDkuMC4wL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAOS4wLjAvaW5kZXgubWpzXCJcbiAgfVxufSIsIl9vIjp7fX0=)
> > 就是不知道它为啥改的不是preview的主题。

你这样例我拷到本地测了下，明白了，这个29行应该是@change监听事件而不应该是:on-change https://element-plus.gitee.io/zh-CN/component/switch.html#%E4%BA%8B%E4%BB%B6

**Comment by QingboMa** [comment]
好的好的，谢谢呀> > 我的样例就是个大概，主要的是我描述的问题😄> 你这样例，一手老年disco给我浏览器干崩了😂
> 
> > 
> 
> > > 这是修正后的样例[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwID5cbmltcG9ydCB7IHVzZURhcmssIHVzZVRvZ2dsZSB9IGZyb20gJ0B2dWV1c2UvY29yZSc7XG5pbXBvcnQgeyByZWYsIHdhdGNoLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgU3VubnksIE1vb24sIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN3aXRjaFZhciA9IHJlZih0cnVlKVxuY29uc3Qgc2VhcmNoS2V5V29yZCA9IHJlZignJylcbmNvbnN0IGlzRGFyayA9IHVzZURhcmsoKVxuY29uc3QgdG9nZ2xlRGFyayA9IHVzZVRvZ2dsZShpc0RhcmspXG5jb25zdCBzZWFyY2hBbnlIYW5kbGVyID0gKHBhcmFtcykgPT4ge1xuXHRjb25zb2xlLmxvZyhwYXJhbXMpO1xufVxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cblx0PGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiIDplbGxpcHNpcz1cImZhbHNlXCI+XG5cdFx0PGRpdiBjbGFzcz1cImZsZXgtZ3Jvd1wiIC8+XG5cblx0XHQ8ZGl2IGNsYXNzPVwic2VhcmNoQW55XCI+XG5cdFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cInNlYXJjaEtleVdvcmRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgdi1vbjpjbGljaz1cInNlYXJjaEFueUhhbmRsZXIoc2VhcmNoS2V5V29yZClcIiBjbGFzcz1cInNlYXJjaC1sb2dvXCIgLz5cblx0XHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDwvZWwtaW5wdXQ+XG5cdFx0PC9kaXY+XG5cdFx0PGVsLXN3aXRjaCB2LW1vZGVsPVwic3dpdGNoVmFyXCIgY2xhc3M9XCJ0aGVtZS1zd2l0Y2hcIiBzaXplPVwibGFyZ2VcIiBpbmxpbmUtcHJvbXB0IGluYWN0aXZlLWNvbG9yPVwicmVkXCJcblx0XHRcdDphY3RpdmUtaWNvbj1cIlN1bm55XCIgOmluYWN0aXZlLWljb249XCJNb29uXCIgQGNoYW5nZT1cInRvZ2dsZURhcmsoIXZhbClcIiAvPlxuXHRcdDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+SmF2YTwvZWwtbWVudS1pdGVtPlxuXHQ8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuMTMuMTEvbGliL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9zaGFyZWRcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2Uvc2hhcmVkQDkuMC4wL2luZGV4Lm1qc1wiLFxuICAgIFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAOS4wLjAvaW5kZXgubWpzXCJcbiAgfVxufSIsIl9vIjp7fX0=)
> 
> > > 就是不知道它为啥改的不是preview的主题。
> 
> 
> 
> 你这样例我拷到本地测了下，明白了，这个29行应该用`@change`监听事件而不是`:on-change` https://element-plus.gitee.io/zh-CN/component/switch.html#%E4%BA%8B%E4%BB%B6

**Comment by acyza** [comment]
不客气！😊
