### ISSUE TITLE
[Bug Report] An error occurred when refreshing the page after clicking the anchor point on the official website

### ISSUE THREAD

**Issue by CitizenChaos** [element-plus/element-plus#1107]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
Windows 10 专业版 20H2 操作系统版本 19042.685 / Chrome 版本 87.0.4280.88（正式版本）（64 位）

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr

### Steps to reproduce
1. Open the official website like `https://element-plus.org/#/en-US/component/button`
2. Click any anchor like `Disabled Button`
3. Refresh page

### What is Expected?
Click on the anchor point and refresh to locate this anchor point

### What is actually happening?
Page is blank

**Comment by JeremyWuuuuu** [comment]
known issue, our routing gaurd didn't get called. Will fix soon
