### ISSUE TITLE
[Component] [table, table-column] “"element-plus"”没有导出的成员“TableColumnCtx”。你是否指的是“ElTableColumn”?

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#11087]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome100`
- Build Tool: `Webpack`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgOnNwYW4tbWV0aG9kPVwiYXJyYXlTcGFuTWV0aG9kXCJcbiAgICAgIGJvcmRlclxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMlwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgPC9lbC10YWJsZT5cblxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgOnNwYW4tbWV0aG9kPVwib2JqZWN0U3Bhbk1ldGhvZFwiXG4gICAgICBib3JkZXJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCU7IG1hcmdpbi10b3A6IDIwcHhcIlxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MlwiIGxhYmVsPVwiQW1vdW50IDJcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50M1wiIGxhYmVsPVwiQW1vdW50IDNcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIHsgVGFibGVDb2x1bW5DdHggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbn1cblxuaW50ZXJmYWNlIFNwYW5NZXRob2RQcm9wcyB7XG4gIHJvdzogVXNlclxuICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4gIHJvd0luZGV4OiBudW1iZXJcbiAgY29sdW1uSW5kZXg6IG51bWJlclxufVxuXG5jb25zdCBhcnJheVNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICAgIHJldHVybiBbMSwgMl1cbiAgICB9IGVsc2UgaWYgKGNvbHVtbkluZGV4ID09PSAxKSB7XG4gICAgICByZXR1cm4gWzAsIDBdXG4gICAgfVxuICB9XG59XG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDIsXG4gICAgICAgIGNvbHNwYW46IDEsXG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

别管上面的链接, 应该是2.2.12没有这个类import type { TableColumnCtx } from 'element-plus'

### What is Expected?

期待有

### What is actually happening?

没有

### Additional comments

_(empty)_

**Comment by btea** [comment]
已经添加了，更新版本就有了。参考 https://github.com/element-plus/element-plus/pull/10677
