### ISSUE TITLE
[Component] [select-v2] :options="options" 动态改变 options 数组内容时，数据内容发生了改变，下拉菜单却没有正常显示内容 No Data，通过vue工具查看 options 数据确实发生改变，但下拉框显示 No Data

### ISSUE THREAD

**Issue by ChaiMayor** [element-plus/element-plus#11088]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Github Repo](https://github.com/ChaiMayor/Packaging-ElementUI)

### Steps to reproduce

npm i 下载包，npm run dev 运行项目，左侧侧边栏选择城市选择器，在选择城市的下拉框中，分别输入中文城市名和英文城市名，打开控制台看输出内容，中文的内容可以正常显示，英文的不能正常显示

### What is Expected?

在选择城市下拉框，输入中文可以出现相关的城市信息，输入英文也可以出现相关的城市信息

### What is actually happening?

在选择城市下拉框，输入中文可以出现相关的城市信息，输入英文却出现了 No Data，通过查看数据确实存在，但显示出现了问题

### Additional comments

el-select-v2 希望可以增加两个自定义属性，value 和 label 可以自定义，而不是必须要 options 这个对象里面的属性名必须是 value 和 label

**Comment by tolking** [comment]
Maybe #9817 is the feature you are looking for, but you'll need to wait for v2.3 to be released.
