### ISSUE TITLE
[Component] [input] Input组件prefix或suffix slot里嵌入select等元素，无法正常使用

### ISSUE THREAD

**Issue by bitjjj** [element-plus/element-plus#11082]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.27`
- Browser / OS: `Chrome 99 / MacOS 11`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDxkaXYgY2xhc3M9XCJkZW1vLWlucHV0LXN1ZmZpeFwiPlxuICAgIDxlbC1yb3cgOmd1dHRlcj1cIjIwXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cIm1sLTMgdy0zNSB0ZXh0LWdyYXktNjAwIGlubGluZS1mbGV4IGl0ZW1zLWNlbnRlclwiXG4gICAgICAgID5Vc2luZyBzbG90czwvc3BhblxuICAgICAgPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dDNcIiBjbGFzcz1cInctNTAgbS0yXCIgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF0ZVwiPlxuICAgICAgICA8dGVtcGxhdGUgI3N1ZmZpeD5cbiAgICAgICAgICA8c2VsZWN0IGNsYXNzPVwiaGwtaW5wdXQgc20gdGhpblwiPlxuICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIlwiPmh0dHA6Ly88L29wdGlvbj5cbiAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9XCJcIj5odHRwczovLzwvb3B0aW9uPlxuICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIlwiPnNzaDo8L29wdGlvbj5cbiAgICAgICAgICA8L3NlbGVjdD5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtaW5wdXQ+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0NFwiIGNsYXNzPVwidy01MCBtLTJcIiBwbGFjZWhvbGRlcj1cIlR5cGUgc29tZXRoaW5nXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjcHJlZml4PlxuICAgICAgICAgIDxzZWxlY3QgY2xhc3M9XCJobC1pbnB1dCBzbSB0aGluXCI+XG4gICAgICAgICAgICA8b3B0aW9uIHZhbHVlPVwiXCI+aHR0cDovLzwvb3B0aW9uPlxuICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIlwiPmh0dHBzOi8vPC9vcHRpb24+XG4gICAgICAgICAgICA8b3B0aW9uIHZhbHVlPVwiXCI+c3NoOjwvb3B0aW9uPlxuICAgICAgICAgIDwvc2VsZWN0PlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC1pbnB1dD5cbiAgICA8L2VsLXJvdz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgQ2FsZW5kYXIsIFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgaW5wdXQxID0gcmVmKCcnKVxuY29uc3QgaW5wdXQyID0gcmVmKCcnKVxuY29uc3QgaW5wdXQzID0gcmVmKCcnKVxuY29uc3QgaW5wdXQ0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

选择prefix或者suffix中的select下拉元素，无法正常选择

### What is Expected?

正常选择prefix或者suffix中的select下拉元素

### What is actually happening?

点击prefix或者suffix中的select下拉元素，input输入部分会自动获取焦点，导致无法选择。

### Additional comments

prefix或者suffix的click事件会调用focus函数，导致此问题

**Comment by loosheng** [comment]
Related PR: #10674

**Comment by tolking** [comment]
现在 prefix、suffix 插槽属于 input 的一部分，用于聚焦。

你可以使用 prepend、append 替代，或者使用 `@click.stop`
