### ISSUE TITLE
[Style] [All] style scoped里的样式会对组件直接生效

### ISSUE THREAD

**Issue by xiaose-A** [element-plus/element-plus#11085]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.25`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLWJ1dHRvbj5hPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbj5iPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSBzY29wZWQ+XG4gIC5lbC1idXR0b257XG5cdG1hcmdpbi1yaWdodDoxMHB4O1xuICB9XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<script setup lang="ts">
</script>

<template>
  <div>
    <el-button>a</el-button>
    <el-button>b</el-button>
  </div>
</template>
<style scoped>
  .el-button{
	margin-right:10px;
  }
</style>

### What is Expected?

如何能避免scoped里的 .el-button对el-button生效

### What is actually happening?

子组件的根节点将同时受到父级作用域 CSS 和子级作用域 CSS 的影响

### Additional comments

vue2里的这样写的.el-button是不是不会生效的？

**Comment by btea** [comment]
可以给当前组件内的 `el-button` 添加新的class。

**Comment by tolking** [comment]
推荐你读下[官方文档](https://cn.vuejs.org/api/sfc-css-features.html#scoped-css)
