### ISSUE TITLE
[Component] [select] el-select的filter-method方法失焦时也触发了一次,并且值为空, 导致下拉框收起时的闪烁问题

### ISSUE THREAD

**Issue by abb-uu** [element-plus/element-plus#11095]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.19`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5cbmNvbnN0IHNlbGVjdFZhbHVlID0gcmVmKClcbmNvbnN0IHNlbGVjdE9wdGlvbnM9cmVmKFtcbiAge1xuICAgIGNvZGU6ICc4NicsXG4gICAgbGFiZWw6ICfkuK3lm70nLFxuICB9LFxuICB7XG4gICAgY29kZTogJzEnLFxuICAgIGxhYmVsOiAn576O5Zu9L+WKoOaLv+WkpycsXG4gIH0sXG4gIHtcbiAgICBjb2RlOiAnNTQnLFxuICAgIGxhYmVsOiAn6Zi/5qC55bu3JyxcbiAgfSxcbiAge1xuICAgIGNvZGU6ICc4MicsXG4gICAgbGFiZWw6ICfpn6nlm70nLFxuICB9LFxuXSlcbmNvbnN0IHNlbGVjdE9wdGlvbnNDb3B5ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShzZWxlY3RPcHRpb25zLnZhbHVlKSlcblxuY29uc3QgdGVzdGZpbHRlciA9ICh0ZXh0KSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzZWFyY2g6ICcgKyB0ZXh0KVxuXHRpZih0ZXh0KSB7XG4gICAgc2VsZWN0T3B0aW9ucy52YWx1ZSA9IHNlbGVjdE9wdGlvbnNDb3B5LmZpbHRlcigoaXRlbSkgPT4ge1xuICAgICAgcmV0dXJuIGl0ZW0ubGFiZWwuaW5jbHVkZXModGV4dCkgfHwgaXRlbS5jb2RlLmluY2x1ZGVzKHRleHQpXG4gICAgfSlcblx0fSBlbHNlIHtcblx0XHRzZWxlY3RPcHRpb25zLnZhbHVlID0gc2VsZWN0T3B0aW9uc0NvcHlcblx0fVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICAgPGI+RWxTZWxlY3Toh6rlrprkuYlmaWx0ZXItbWV0aG9k6Zeu6aKY77yaPC9iPjxicj48YnI+XG4gICAgKDEpIOeCueWHu+W5tuW9leWFpeS7u+aEj+aQnOe0ouWtl+espuS4sjxicj48YnI+XG4gICAgKDIpIOenu+WHuueEpueCuS/pgInmi6nmn5DkuIDpobnlkI5zZWxlY3TlpLHnhKbop6blj5FmaWx0ZXItbWV0aG9k5a+86Ie05LiL5ouJ6I+c5Y2V5pS26LW35pe26Zeq54OBPGJyPjxicj5cbiAgPC9kaXY+XG4gIDxlbC1zZWxlY3QgcmVmPVwidGVzdFwiIHYtbW9kZWw9XCJzZWxlY3RWYWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6ZmlsdGVyLW1ldGhvZD1cInRlc3RmaWx0ZXJcIj5cblx0XHRcdDxlbC1vcHRpb25cblx0XHRcdCAgdi1mb3I9XCJpdGVtIGluIHNlbGVjdE9wdGlvbnNcIlxuXHRcdFx0ICA6a2V5PVwiaXRlbS5jb2RlXCJcblx0XHRcdCAgOmxhYmVsPVwiJysnICsgaXRlbS5jb2RlXCJcblx0XHRcdCAgOnZhbHVlPVwiaXRlbS5jb2RlXCI+XG4gICAgICAgIDxzcGFuIHN0eWxlPVwiZmxvYXQ6IGxlZnRcIj57e2l0ZW0ubGFiZWx9fTwvc3Bhbj5cbiAgICAgICAgPHNwYW4gc3R5bGU9XCJmbG9hdDogcmlnaHRcIj4re3tpdGVtLmNvZGV9fTwvc3Bhbj5cbiAgICBcdDwvZWwtb3B0aW9uPlxuXHQ8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

鼠标移入select并输入检索字符, 当选中某一项或select失焦时触发了filter-method事件, 并且检索字符重置为空, 导致下拉菜单收起时重置为原始列表, 造成闪烁现象

### What is Expected?

失焦时不会触发filter-method事件, 或者在下拉框完全收起后再触发

### What is actually happening?

下拉框未收起时触发了filter-method事件到导致闪烁问题

### Additional comments

观察到element的el-select的filter-method在失焦时是不会触发的, 我可以通过visible-change事件, 在展开时重新赋值为原始列表, 但是element-plus目前的情况我不知道该如何处理

**Comment by acyza** [comment]
失去焦点时filterMethod的text为空字符串，只要这个时候不做筛选操作，等visible-change事件再以空字符串做一次筛选操作
```js
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'


const selectValue = ref()
const selectOptions=ref([
  {
    code: '86',
    label: '中国',
  },
  {
    code: '1',
    label: '美国/加拿大',
  },
  {
    code: '54',
    label: '阿根廷',
  },
  {
    code: '82',
    label: '韩国',
  },
])
const selectOptionsCopy = JSON.parse(JSON.stringify(selectOptions.value))

const testfilter = (text) => {
  console.log('search: ' + text)
  if(!text)return;
  if(text === true) text = ''
	if(text) {
    selectOptions.value = selectOptionsCopy.filter((item) => {
      return item.label.includes(text) || item.code.includes(text)
    })
	} else {
		selectOptions.value = selectOptionsCopy
	}
}
</script>

<template>
    <div>
      <b>ElSelect自定义filter-method问题：</b><br><br>
    (1) 点击并录入任意搜索字符串<br><br>
    (2) 移出焦点/选择某一项后select失焦触发filter-method导致下拉菜单收起时闪烁<br><br>
  </div>
  <el-select ref="test" v-model="selectValue" filterable placeholder="Select" :filter-method="testfilter" @visible-change="testfilter">
			<el-option
			  v-for="item in selectOptions"
			  :key="item.code"
			  :label="'+' + item.code"
			  :value="item.code">
        <span style="float: left">{{item.label}}</span>
        <span style="float: right">+{{item.code}}</span>
    	</el-option>
	</el-select>
</template>
```
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5cbmNvbnN0IHNlbGVjdFZhbHVlID0gcmVmKClcbmNvbnN0IHNlbGVjdE9wdGlvbnM9cmVmKFtcbiAge1xuICAgIGNvZGU6ICc4NicsXG4gICAgbGFiZWw6ICfkuK3lm70nLFxuICB9LFxuICB7XG4gICAgY29kZTogJzEnLFxuICAgIGxhYmVsOiAn576O5Zu9L+WKoOaLv+WkpycsXG4gIH0sXG4gIHtcbiAgICBjb2RlOiAnNTQnLFxuICAgIGxhYmVsOiAn6Zi/5qC55bu3JyxcbiAgfSxcbiAge1xuICAgIGNvZGU6ICc4MicsXG4gICAgbGFiZWw6ICfpn6nlm70nLFxuICB9LFxuXSlcbmNvbnN0IHNlbGVjdE9wdGlvbnNDb3B5ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShzZWxlY3RPcHRpb25zLnZhbHVlKSlcblxuY29uc3QgdGVzdGZpbHRlciA9ICh0ZXh0KSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzZWFyY2g6ICcgKyB0ZXh0KVxuICBpZighdGV4dClyZXR1cm47XG4gIGlmKHRleHQgPT09IHRydWUpIHRleHQgPSAnJ1xuXHRpZih0ZXh0KSB7XG4gICAgc2VsZWN0T3B0aW9ucy52YWx1ZSA9IHNlbGVjdE9wdGlvbnNDb3B5LmZpbHRlcigoaXRlbSkgPT4ge1xuICAgICAgcmV0dXJuIGl0ZW0ubGFiZWwuaW5jbHVkZXModGV4dCkgfHwgaXRlbS5jb2RlLmluY2x1ZGVzKHRleHQpXG4gICAgfSlcblx0fSBlbHNlIHtcblx0XHRzZWxlY3RPcHRpb25zLnZhbHVlID0gc2VsZWN0T3B0aW9uc0NvcHlcblx0fVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICAgPGI+RWxTZWxlY3Toh6rlrprkuYlmaWx0ZXItbWV0aG9k6Zeu6aKY77yaPC9iPjxicj48YnI+XG4gICAgKDEpIOeCueWHu+W5tuW9leWFpeS7u+aEj+aQnOe0ouWtl+espuS4sjxicj48YnI+XG4gICAgKDIpIOenu+WHuueEpueCuS/pgInmi6nmn5DkuIDpobnlkI5zZWxlY3TlpLHnhKbop6blj5FmaWx0ZXItbWV0aG9k5a+86Ie05LiL5ouJ6I+c5Y2V5pS26LW35pe26Zeq54OBPGJyPjxicj5cbiAgPC9kaXY+XG4gIDxlbC1zZWxlY3QgcmVmPVwidGVzdFwiIHYtbW9kZWw9XCJzZWxlY3RWYWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6ZmlsdGVyLW1ldGhvZD1cInRlc3RmaWx0ZXJcIiBAdmlzaWJsZS1jaGFuZ2U9XCJ0ZXN0ZmlsdGVyXCI+XG5cdFx0XHQ8ZWwtb3B0aW9uXG5cdFx0XHQgIHYtZm9yPVwiaXRlbSBpbiBzZWxlY3RPcHRpb25zXCJcblx0XHRcdCAgOmtleT1cIml0ZW0uY29kZVwiXG5cdFx0XHQgIDpsYWJlbD1cIicrJyArIGl0ZW0uY29kZVwiXG5cdFx0XHQgIDp2YWx1ZT1cIml0ZW0uY29kZVwiPlxuICAgICAgICA8c3BhbiBzdHlsZT1cImZsb2F0OiBsZWZ0XCI+e3tpdGVtLmxhYmVsfX08L3NwYW4+XG4gICAgICAgIDxzcGFuIHN0eWxlPVwiZmxvYXQ6IHJpZ2h0XCI+K3t7aXRlbS5jb2RlfX08L3NwYW4+XG4gICAgXHQ8L2VsLW9wdGlvbj5cblx0PC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by abb-uu** [comment]
> 

但是这样处理的话手动清空检索值时就没办法恢复为原始列表了

**Comment by woshidamaomao** [comment]
我也有这个问题。
