### ISSUE TITLE
### InfiniteScroll

### ISSUE THREAD

**Issue by SimonaliaChen** [element-plus/element-plus#111]

**Comment by bmfs** [comment]
@SimonaliaChen Is this available to work on? I wouldn't mind to pick this up.

**Comment by SimonaliaChen** [comment]
> @SimonaliaChen Is this available to work on? I wouldn't mind to pick this up.

Thanks for joining us ! I am working on it.  Maybe you can pick up `Loading` or `Message` if you don't mind.
