### ISSUE TITLE
[Component] [drawer] nuxt3 + ElementUI Plus, drawer component doesn't work

### ISSUE THREAD

**Issue by BSJJC** [element-plus/element-plus#11108]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.25`
- Browser / OS: `Chrome 108.0.5359.125`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Github Repo](https://github.com/BSJJC/nuxt-3-element-plus-starter)

### Steps to reproduce

Use the drawer + button component normally in nuxt3

### What is Expected?

drawer component run

### What is actually happening?

console error

### Additional comments

_(empty)_

**Comment by ryuhangyeong** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/27342882/210050101-86f5b198-0a5f-4469-a35d-4ded5248f5c2.png">

> This component requires the <client-only></client-only> wrap when used in SSR (eg: Nuxt) and SSG (eg: VitePress).

**Comment by BSJJC** [comment]
> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.2.40`
> * Element Plus Version: `2.2.25`
> * Browser / OS: `Chrome 108.0.5359.125`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `el-drawer`
> 
> ### Reproduction Link
> [Github Repo](https://github.com/BSJJC/nuxt-3-element-plus-starter)
> 
> ### Steps to reproduce
> Use the drawer + button component normally in nuxt3
> 
> ### What is Expected?
> drawer component run
> 
> ### What is actually happening?
> console error
> 
> ### Additional comments
> _(empty)_



> ## Suggest
> <img alt="image" width="613" src="https://user-images.githubusercontent.com/27342882/210050101-86f5b198-0a5f-4469-a35d-4ded5248f5c2.png">
> 
> > This component requires the  wrap when used in SSR (eg: Nuxt) and SSG (eg: VitePress).

oh...I might be blind... thanks, it works
