### ISSUE TITLE
[Component] [upload] upload上传组件上传数量限制展示无效

### ISSUE THREAD

**Issue by sdlddr** [element-plus/element-plus#11106]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/upload.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E7%95%A5%E5%9B%BE)

### Steps to reproduce

1、使用el-upload组件，设置list-type="picture-card"、:limit="5"。
2、运行后，上传5张图片。
3、但发现上传5张图片后，含有“+”加的块状上传按钮仍显示，只不过点击时无法再上传图片。

### What is Expected?

上传5张图片后，含有“+”加的块状上传按钮应消失。

### What is actually happening?

发现上传5张图片后，含有“+”加的块状上传按钮仍显示，只不过点击时无法再上传图片。

### Additional comments

_(empty)_

**Comment by acyza** [comment]
通常限制数量只需要在on-exceed钩子中提示一下，如果非要隐藏加号这是临时办法 [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICBsaXN0LXR5cGU9XCJwaWN0dXJlLWNhcmRcIlxuICAgIDpvbi1wcmV2aWV3PVwiaGFuZGxlUGljdHVyZUNhcmRQcmV2aWV3XCJcbiAgICA6b24tcmVtb3ZlPVwiaGFuZGxlUmVtb3ZlXCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImNoZWNrU2hvd1VwbG9hZCgxKVwiXG4gICAgOmJlZm9yZS1yZW1vdmU9XCJjaGVja1Nob3dVcGxvYWQoLTEpXCJcbiAgICA6bGltaXQ9XCI1XCJcbiAgPlxuICAgIDxlbC1pY29uPjxQbHVzIC8+PC9lbC1pY29uPlxuICA8L2VsLXVwbG9hZD5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCI+XG4gICAgPGltZyB3LWZ1bGwgOnNyYz1cImRpYWxvZ0ltYWdlVXJsXCIgYWx0PVwiUHJldmlldyBJbWFnZVwiIC8+XG4gIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuZWwtdXBsb2FkIHtcbiAgICB2aXNpYmlsaXR5OiB2LWJpbmQoc2hvd1VwbG9hZClcbiAgfVxuPC9zdHlsZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbiAge1xuICAgIG5hbWU6ICdmb29kLmpwZWcnLFxuICAgIHVybDogJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzYzLzRlN2YzYTE1NDI5YmZkYTk5YmNlNDJhMThjZGQxanBlZy5qcGVnP2ltYWdlTW9ncjIvdGh1bWJuYWlsLzM2MHgzNjAvZm9ybWF0L3dlYnAvcXVhbGl0eS8xMDAnLFxuICB9LFxuICB7XG4gICAgbmFtZTogJ2Zvb2QuanBlZycsXG4gICAgdXJsOiAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvNjMvNGU3ZjNhMTU0MjliZmRhOTliY2U0MmExOGNkZDFqcGVnLmpwZWc/aW1hZ2VNb2dyMi90aHVtYm5haWwvMzYweDM2MC9mb3JtYXQvd2VicC9xdWFsaXR5LzEwMCcsXG4gIH0sXG4gIHtcbiAgICBuYW1lOiAnZm9vZC5qcGVnJyxcbiAgICB1cmw6ICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy82My80ZTdmM2ExNTQyOWJmZGE5OWJjZTQyYTE4Y2RkMWpwZWcuanBlZz9pbWFnZU1vZ3IyL3RodW1ibmFpbC8zNjB4MzYwL2Zvcm1hdC93ZWJwL3F1YWxpdHkvMTAwJyxcbiAgfSxcbiAge1xuICAgIG5hbWU6ICdmb29kLmpwZWcnLFxuICAgIHVybDogJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzYzLzRlN2YzYTE1NDI5YmZkYTk5YmNlNDJhMThjZGQxanBlZy5qcGVnP2ltYWdlTW9ncjIvdGh1bWJuYWlsLzM2MHgzNjAvZm9ybWF0L3dlYnAvcXVhbGl0eS8xMDAnLFxuICB9XG5dKVxuXG5jb25zdCBkaWFsb2dJbWFnZVVybCA9IHJlZignJylcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBzaG93VXBsb2FkID0gcmVmKCd2aXNpYmxlJylcblxuY29uc3QgaGFuZGxlUmVtb3ZlOiBVcGxvYWRQcm9wc1snb25SZW1vdmUnXSA9ICh1cGxvYWRGaWxlLCB1cGxvYWRGaWxlcykgPT4ge1xuICBjb25zb2xlLmxvZyh1cGxvYWRGaWxlLCB1cGxvYWRGaWxlcylcbn1cblxuY29uc3QgaGFuZGxlUGljdHVyZUNhcmRQcmV2aWV3OiBVcGxvYWRQcm9wc1snb25QcmV2aWV3J10gPSAodXBsb2FkRmlsZSkgPT4ge1xuICBkaWFsb2dJbWFnZVVybC52YWx1ZSA9IHVwbG9hZEZpbGUudXJsIVxuICBkaWFsb2dWaXNpYmxlLnZhbHVlID0gdHJ1ZVxufVxuXG5jb25zdCBjaGVja1Nob3dVcGxvYWQgPSAodmFsKSA9PiB7XG4gIHNob3dVcGxvYWQudmFsdWUgPSAoZmlsZUxpc3QudmFsdWUubGVuZ3RoICsgdmFsKSA+PSA0ID8gJ2hpZGRlbic6J3Zpc2FibGUnXG4gIGNvbnNvbGUubG9nKHNob3dVcGxvYWQudmFsdWUpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by sdlddr** [comment]
谢谢，目前已经用上2楼的方法！

**Comment by HeftyKoo** [comment]
如果没有其他问题，我先把这个issue关了哈
