### ISSUE TITLE
[Bug Report] el-popover component's value/v-model doesn't work

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1110]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
chrome87

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr

### Steps to reproduce
set value/v-mode to el-popover

### What is Expected?
change value/v-model to visible

### What is actually happening?
value/v-model doesn't work

**Comment by Vgbire** [comment]
#1109

**Comment by bastarder** [comment]
did you try `v-model:visible` ?

**Comment by Vgbire** [comment]
> did you try `v-model:visible` ?

I try,It reported a mistake

**Comment by BeADre** [comment]
Can you provide a reproduction demo？

**Comment by Vgbire** [comment]
> Can you provide a reproduction demo？

sorry.,this is Reproduction Link https://codepen.io/vgbire/pen/MWjEMmR

**Comment by BeADre** [comment]
I think you should do it like this

![image](https://user-images.githubusercontent.com/34639100/103082061-440e2500-4614-11eb-86e8-188df4226e36.png)

**Comment by JeremyWuuuuu** [comment]
![04805BFE-1D2A-4663-830B-F235275110F5](https://user-images.githubusercontent.com/15975785/103082540-4cb32b00-4615-11eb-86f6-e1c7e99fb12f.png)
seems to me that the property `visible` Is working

**Comment by Vgbire** [comment]
> ![04805BFE-1D2A-4663-830B-F235275110F5](https://user-images.githubusercontent.com/15975785/103082540-4cb32b00-4615-11eb-86f6-e1c7e99fb12f.png)
> seems to me that the property `visible` Is working

![image](https://user-images.githubusercontent.com/32129111/103082967-4c675f80-4616-11eb-806c-2332ebc759c1.png)
yes， visible is working,value and v-model don't work

**Comment by JeremyWuuuuu** [comment]
You should combine it with v-model:visible instead of v-model or value

**Comment by Vgbire** [comment]
> I think you should do it like this
In fact,value  it doesn't work



> You should combine it with v-model:visible instead of v-model or value

I try,It reported a mistake

**Comment by JeremyWuuuuu** [comment]
Try not to use constants as v-model, it will refers to a variable for example
If you use 
v-model:visible="true"

It unwraps with syntax like this
:visible="true"
@updateModel:visible="value => true = val"

**Comment by JeremyWuuuuu** [comment]
![588DC5BE-7ED1-4CB7-A5A6-74546E715039](https://user-images.githubusercontent.com/15975785/103084040-f0520a80-4618-11eb-8671-b6376b433124.png)
See how I get it worked

**Comment by Vgbire** [comment]
yes,you are right,but :visible="visible" is easier than v-model:visible="visible"，and :visible="visible" can work too.The description of the official document still needs to be changed.because v-model/value don't work

**Comment by JeremyWuuuuu** [comment]
> yes,you are right,but :visible="visible" is easier than v-model:visible="visible"，and :visible="visible" can work too.The description of the official document still needs to be changed.because v-model/value don't work

Right, do you want to make a PR for this issue?

**Comment by JeremyWuuuuu** [comment]
The reason that we use `v-model:visible` is because that only use `v-model` is more like a form binding, with `visible` to decorate `v-model` would be much more semantic,  and `v-model` enables two way binding for the users so if our user want to use that with one way binding, then they should pass only `:visible`, if you do have the will to update the doc site, then you need to change it to `visible / v-model:visible`.

**Comment by Vgbire** [comment]
> The reason that we use `v-model:visible` is because that only use `v-model` is more like a form binding, with `visible` to decorate `v-model` would be much more semantic, and `v-model` enables two way binding for the users so if our user want to use that with one way binding, then they should pass only `:visible`, if you do have the will to update the doc site, then you need to change it to `visible / v-model:visible`.

ok I will make a pull request for it
