### ISSUE TITLE
[Style] [message-box] MessageBox无样式

### ISSUE THREAD

**Issue by WutangNailao** [element-plus/element-plus#11115]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.28`
- Browser / OS: `chrome/window11`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Github Repo](https://github.com/WutangNailao/ElementBugPush)

### Steps to reproduce

点击"Click to open the Message Box"按钮，即可复现

### What is Expected?

出现messageBox.alert弹出框

### What is actually happening?

出现了弹出框，但是没样式，全部堆积在视口左上角

### Additional comments

_(empty)_

**Comment by acyza** [comment]
没有样式可以手动引入一下样式
比如：ElMessage  `import 'element-plus/theme-chalk/el-message.css'`

**Comment by WutangNailao** [comment]
不起作用，引入了依旧没样式

**Comment by tolking** [comment]
同时使用 `unplugin-auto-import` `unplugin-vue-components`，不需要手动引入 ElMessage ElMessageBox。

如果手动引入需要自己引入样式

[Link](https://github.com/WutangNailao/ElementBugPush/blob/master/src/App.vue#L6)

```diff
- import { ElMessage, ElMessageBox } from 'element-plus'
```

**Comment by vela666** [comment]
> 同时使用 `unplugin-auto-import` `unplugin-vue-components`，不需要手动引入 ElMessage ElMessageBox。
> 
> 如果手动引入需要自己引入样式
> 
> [关联](https://github.com/WutangNailao/ElementBugPush/blob/master/src/App.vue#L6)
> 
> ```diff
> - import { ElMessage, ElMessageBox } from 'element-plus'
> ```
不手动引入 eslint报错 怎么解决的大佬

**Comment by tolking** [comment]
> 不手动引入 eslint报错 怎么解决的大佬

为什么不去看看 unplugin-auto-import 的文档

**Comment by WutangNailao** [comment]
最终用
import type { ElMessage } from 'element-plus'
解决，虽然报错，但效果正常，我更加坚信这个是个bug

**Comment by g8up** [comment]
> > 同时使用 `unplugin-auto-import` `unplugin-vue-components`，不需要手动引入 ElMessage ElMessageBox。
> > 如果手动引入需要自己引入样式
> > [关联](https://github.com/WutangNailao/ElementBugPush/blob/master/src/App.vue#L6)
> > ```diff
> > - import { ElMessage, ElMessageBox } from 'element-plus'
> > ```
> 
> 不手动引入 eslint报错 怎么解决的大佬

我尝试不手动引用，确实不报错。因为 auto-import 会自动生成一个 `auto-imports.d.ts` 的文件，里边自动声明了。

@WutangNailao

**Comment by liumang666** [comment]
> > 同时使用 `unplugin-auto-import` `unplugin-vue-components`，不需要手动引入 ElMessage ElMessageBox。
> > 如果手动引入需要自己引入样式
> > [关联](https://github.com/WutangNailao/ElementBugPush/blob/master/src/App.vue#L6)
> > ```diff
> > - import { ElMessage, ElMessageBox } from 'element-plus'
> > ```
> 
> 不手动引入 eslint报错 怎么解决的大佬

[unplugin-auto-import](https://github.com/antfu/unplugin-auto-import) 提供了ESLint解决方式
配置Enable  和 .eslintrc.js
