### ISSUE TITLE
[TypeScript] [card] Clicking on "Card" in the component gallery crashes the framework

### ISSUE THREAD

**Issue by jblachly** [element-plus/element-plus#11114]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome, Firefox, and Safari (all latest)`
- Build Tool: `Other`

### Related Component

- `el-card`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/card.html)

### Steps to reproduce

In the element plus component gallery (https://element-plus.org/en-US/component/button), visit any OTHER component(s) besides card. Everything operates properly. Then, navigate to Card (left hand menu). Not only is nothing displayed for the component, navigating to other components is also broken (no display) until the application is reset (e.g. through closing the browser)

### What is Expected?

No typescript error

### What is actually happening?

typescript errors and UI malfunctions

### Additional comments

locale: en-US

**Comment by tolking** [comment]
Fixed in #11282
