### ISSUE TITLE
[Component] [upload] [Vue warn]: <TransitionGroup> children must be keyed.

### ISSUE THREAD

**Issue by GuoJikun** [element-plus/element-plus#11125]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBmaWxlTGlzdCA9IHJlZihbe3VybDonaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvNjMvNGU3ZjNhMTU0MjliZmRhOTliY2U0MmExOGNkZDFqcGVnLmpwZWc/aW1hZ2VNb2dyMi90aHVtYm5haWwvMzYweDM2MC9mb3JtYXQvd2VicC9xdWFsaXR5LzEwMCd9XSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC11cGxvYWQgXG4gICAgICBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgICAgbGlzdC10eXBlPVwicGljdHVyZS1jYXJkXCJcbiAgICAgIDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

选择图片的时候就会有警告；
警告信息：
```
VM320 about:srcdoc:160 
        
       [Vue warn]: <TransitionGroup> children must be keyed. 
  at <TransitionGroup tag="ul" class="el-upload-list el-upload-list--picture-card" name="el-list" > 
  at <ElUploadList key=0 disabled=false list-type="picture-card"  ... > 
  at <ElUpload action="https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15" list-type="picture-card" file-list= [{…}] > 
  at <App> 
  at <Repl>
```

### What is Expected?

不显示警告

### What is actually happening?

有警告

**Comment by GuoJikun** [comment]
vue升级到3.2.45版本就不会有警告

**Comment by baiyuze** [comment]
> vue升级到3.2.45版本不会有警告
不应该这样哇，作为组件库，不应该要求用户该用哪个版本的主框架的Vue才对的

**Comment by GuoJikun** [comment]
> > vue升级到3.2.45版本不会有警告
> > 不应该这样哇，作为组件库，不应该要求用户该用哪个版本的主框架的Vue才对的

赞同
