### ISSUE TITLE
[Component] [date-time-range] 通过input修改rightDate 会导致leftDate被修改为rightDate 日期的前一个月， 同样修改leftDate也会导致rightDate 被修改

### ISSUE THREAD

**Issue by RichOvernigh** [element-plus/element-plus#11164]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Chrome 107.0.5304.110（正式版本） (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.org/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F)

### Steps to reproduce

通过input修改rightDate 会导向leftDate被修改为rightDate日期的前一个月，同样修改leftDate也会导向rightDate被修改### What is Expected?

不被改

### What is actually happening?

被改

### Additional comments

_(empty)_

**Comment by RichOvernigh** [comment]
![image](https://user-images.githubusercontent.com/73455910/210923284-5d4ca626-e482-4872-a639-155633e72c3a.png)

**Comment by tolking** [comment]
This issue has been fixed
