### ISSUE TITLE
[Docs] [All] ElementPlus官方组件说明网页bug

### ISSUE THREAD

**Issue by HZ2PP** [element-plus/element-plus#11163]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome 96.0.4664.110`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/layout.html#%E6%BA%90%E4%BB%A3%E7%A0%81)

### Steps to reproduce

左侧组件导航栏，点击任何一个都会报404，这让我怎么看文档。。。

### What is Expected?

正常返回文档说明页面

### What is actually happening?

404

### Additional comments

麻烦尽快修复，不然没法用

**Comment by btea** [comment]
可以用这个[地址](https://element-plus.org/zh-CN/)
