### ISSUE TITLE
[Bug Report] autofocus property on el-input doesn't work

### ISSUE THREAD

**Issue by fox-john** [element-plus/element-plus#11160]
### Element Plus version
2.2.12

### OS/Browsers version
Windows 11 / Firefox dev 109.0b8

### Vue version
3.2.25

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-7i2gct?file=/src/App.vue

### Steps to reproduce
create <el-input autofocus></el-input> and load your component.

### What is Expected?
focus is set to input when you load the component

### What is actually happening?
nothing

**Comment by itsalimanuel** [comment]
[like that?](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwidmFsdWVcIiBhdXRvZm9jdXM+PC9lbC1pbnB1dD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIGRhdGEoKXtcbiAgICByZXR1cm4ge1xuICAgICAgdmFsdWU6ICcnXG4gICAgfVxuICB9XG59O1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
