### ISSUE TITLE
[Component] [input] use v-if at el-input[textarea] will cause error

### ISSUE THREAD

**Issue by Inori-Lover** [element-plus/element-plus#11186]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `chrome`
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGJvb2wgPSByZWYoZmFsc2UpXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBib29sLnZhbHVlID0gdHJ1ZVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8c2VjdGlvbj5cbiAgICA8ZWwtaW5wdXQgdi1pZj1cImJvb2xcIiB0eXBlPVwidGV4dGFyZWFcIiB2LW1vZGVsPVwibXNnXCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAyLCBtYXhSb3dzOiAzIH1cIiAvPlxuICA8L3NlY3Rpb24+XG4gIDxzZWN0aW9uPlxuICAgIDxlbC1pbnB1dCB2LWlmPVwiIWJvb2xcIiB0eXBlPVwidGV4dGFyZWFcIiB2LW1vZGVsPVwibXNnXCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAyLCBtYXhSb3dzOiAzIH1cIiAvPlxuICA8L3NlY3Rpb24+XG4gIFxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

just open the link

### What is Expected?

not throw error

### What is actually happening?

throw error

### Additional comments

https://github.com/element-plus/element-plus/blob/dev/packages/components/input/src/input.vue#L492

**Comment by itsalimanuel** [comment]
you can use v-show to fix it
