### ISSUE TITLE
[bug report] after inputnumbe is cleared, the focus is lost and the value of V-model is not changed when the value of Min is changed

### ISSUE THREAD

**Issue by wzohxia** [element-plus/element-plus#1119]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
Google Chrome  87.0.4280.88

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/wzohxia/pen/MWjOKxp

### Steps to reproduce
1、清空input的值
2、input的值变成1
3、num的值是undefined

### What is Expected?
num的值也是1

### What is actually happening?
num的值是undefined

**Comment by zazzaz** [comment]
working on this via #1252
