### ISSUE TITLE
[Component] [card] V3版本 官网文档《Card 卡片》 页报错，导致页面无法正常访问  DOMException: Failed to execute 'setAttribute' on 'Element': '20px' is not a valid attribute name.  

### ISSUE THREAD

**Issue by Cooli-willson** [element-plus/element-plus#11197]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-card`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/card.html)

### Steps to reproduce

V3版本 官网文档《Card 卡片》 页报错

### What is Expected?

页面正常访问

### What is actually happening?

页面无法正常访问

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
尝试清理一下缓存哦

**Comment by acyza** [comment]
> 尝试清理一下缓存哦

它好像在card有事先加载过的情况下，从其他组件的文档通过侧边的目录路由进来必报错，然后再路由其他文档都是空的。
复现步骤：
1. 打开(docs)[https://element-plus.org/zh-CN/component/card.html]将card组件文档加载一遍
2. 通过侧边目录切到其他组件
3. 再通过侧边目录切回来
