### ISSUE TITLE
[Component] [menu] el-menu组件的@open事件错误触发@close事件无法触发

### ISSUE THREAD

**Issue by sgj123456** [element-plus/element-plus#11203]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Edg/108.0.1462.76/ Windows 11 22H2`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlzQ29sbGFwc2UgPSByZWYodHJ1ZSlcbmNvbnN0IGhhbmRsZU9wZW4gPSAoa2V5LCBrZXlQYXRoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdPcGVuJylcbiAgY29uc29sZS5sb2coJ09wZW4nLCBrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXksIGtleVBhdGgpID0+IHtcbiAgY29uc29sZS5sb2coJ0Nsb3NlJylcbiAgY29uc29sZS5sb2coJ0Nsb3NlJywga2V5LCBrZXlQYXRoKVxufVxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGtleSwga2V5UGF0aCkgPT4ge1xuICBjb25zb2xlLmxvZygnU2VsZWN0JylcbiAgY29uc29sZS5sb2coJ1NlbGVjdCcsIGtleSwga2V5UGF0aClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwiaXNDb2xsYXBzZVwiIHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMjBweFwiPlxuICAgIDxlbC1yYWRpby1idXR0b24gOmxhYmVsPVwiZmFsc2VcIj7lsZXlvIA8L2VsLXJhZGlvLWJ1dHRvbj5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIDpsYWJlbD1cInRydWVcIj7lhbPpl608L2VsLXJhZGlvLWJ1dHRvbj5cbiAgPC9lbC1yYWRpby1ncm91cD5cbiAgPGVsLW1lbnVcbiAgICBkZWZhdWx0LWFjdGl2ZT1cIjFcIlxuICAgIGNsYXNzPVwiZWwtbWVudS12ZXJ0aWNhbC1kZW1vXCJcbiAgICA6Y29sbGFwc2U9XCJpc0NvbGxhcHNlXCJcbiAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICAgIEBjbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgICBAc2VsZWN0PVwiaGFuZGxlU2VsZWN0XCJcbiAgPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPjE8L3RlbXBsYXRlPlxuICAgIDwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPjI8L3RlbXBsYXRlPlxuICAgIDwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPjM8L3RlbXBsYXRlPlxuICAgIDwvZWwtbWVudS1pdGVtPlxuICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLW1lbnUtdmVydGljYWwtZGVtbzpub3QoLmVsLW1lbnUtLWNvbGxhcHNlKSB7XG4gIHdpZHRoOiAyMDBweDtcbiAgbWluLWhlaWdodDogNDAwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup>
import { ref } from 'vue'
const isCollapse = ref(true)
const handleOpen = (key, keyPath) => {
  console.log('Open')
  console.log('Open', key, keyPath)
}
const handleClose = (key, keyPath) => {
  console.log('Close')
  console.log('Close', key, keyPath)
}
const handleSelect = (key, keyPath) => {
  console.log('Select')
  console.log('Select', key, keyPath)
}
</script>

<template>
  <el-radio-group v-model="isCollapse" style="margin-bottom: 20px">
    <el-radio-button :label="false">展开</el-radio-button>
    <el-radio-button :label="true">关闭</el-radio-button>
  </el-radio-group>
  <el-menu
    default-active="1"
    class="el-menu-vertical-demo"
    :collapse="isCollapse"
    @open="handleOpen"
    @close="handleClose"
    @select="handleSelect"
  >
    <el-menu-item index="1">
      <template #title>1</template>
    </el-menu-item>
    <el-menu-item index="2">
      <template #title>2</template>
    </el-menu-item>
    <el-menu-item index="3">
      <template #title>3</template>
    </el-menu-item>
  </el-menu>
</template>

<style scoped>
.el-menu-vertical-demo:not(.el-menu--collapse) {
  width: 200px;
  min-height: 400px;
}
</style>
```
## Bug1
@open事件触发异常，除了在展开el-manu组件时正常触发一次事件外，首次点击其他el-menu-item组件都可以触发一次@open事件，且再次关闭后展开都会如此
及该事件应当为每次展开el-menu组件全体子组件一共可以触发一次该事件，而不是每次展开el-menu组件每个子组件分别可以触发一次该事件
## Bug2
点击关闭按钮正常关闭el-menu组件但没有触发该组件的@close事件

### What is Expected?

1.每次展开el-menu组件当前活动子组件触发一次@open事件，在下次展开前不会再触发@open事件
2.点击关闭触发el-menu的@close事件

### What is actually happening?

1.每次展开el-menu组件除了正常触发一次@open事件外，其他子组件被首次点击也可以触发一次@open事件
2.没有触发@close事件

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
请勿重复提交issue
