### ISSUE TITLE
[Feature Request] Hope single/multi select of table can bind a object

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1121]
### Existing Component
Yes

### Component Name
Table

### Description
Now, single/multi select only has a selection-change event. Hope that select function of table can bind a object. 
Can you look at this? @justwiner

**Comment by justwiner** [comment]
Can you provide the code you expect? @kooriookami

**Comment by kooriookami** [comment]
props:
multiple-select: boolean (default: true)
v-model:selection / modelValue:selection : array (multiple-select: true) | string / number / boolean (multiple-select: false)

```html
<el-table :data="data" row-key="id" multiple-select v-model:selection="list">
    <el-table-column type="selection" reserve-selection></el-table-column>
    ...
</el-table>

<script>
export default {
    data() {
        return {
            data: [],
            list: []
        }
    }
}
</script>
```
@justwiner I think it could be like this. What do you think?

**Comment by justwiner** [comment]
I think that exposing all events and letting developers do what they want to do, this kind of scalability will be better. The table only needs to maintain the table data. What do you think? @kooriookami

**Comment by kooriookami** [comment]
@justwiner Yes. Is there any specific description or api?
@JeremyWuuuuu Ding~
