### ISSUE TITLE
[Component] [cascader] 使用组件的clearable属性，触发清空会警告

### ISSUE THREAD

**Issue by whidy** [element-plus/element-plus#11226]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome: 108.0.5359.124 / macOS 12.6.2 (21G320)`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2FzY2FkZXIgOm9wdGlvbnM9XCJvcHRpb25zXCIgY2xlYXJhYmxlIC8+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ2NvbXBvbmVudCcsXG4gICAgbGFiZWw6ICdDb21wb25lbnQnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbm90aWNlJyxcbiAgICAgICAgbGFiZWw6ICdOb3RpY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYWxlcnQnLFxuICAgICAgICAgICAgbGFiZWw6ICdBbGVydCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2xvYWRpbmcnLFxuICAgICAgICAgICAgbGFiZWw6ICdMb2FkaW5nJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZScsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdtZXNzYWdlLWJveCcsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2VCb3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdub3RpZmljYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdOb3RpZmljYXRpb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ3Jlc291cmNlJyxcbiAgICBsYWJlbDogJ1Jlc291cmNlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlJyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnc2tldGNoJyxcbiAgICAgICAgbGFiZWw6ICdTa2V0Y2ggVGVtcGxhdGVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZG9jcycsXG4gICAgICAgIGxhYmVsOiAnRGVzaWduIERvY3VtZW50YXRpb24nLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

打开官方的playground后，随便选择一个选项；
光标处于组件内部后可见到clearable的icon；
点击icon，会清空内容并出现警告信息。

### What is Expected?

不再出现警告信息，并保持原来初始状态的默认值，或许是空字符串。

### What is actually happening?

警告信息如下：

```
Invalid event arguments: event validation failed for event "change".
 at <ElInputref_key="input"ref=Ref<[object Object]>modelValue="" ...>
 at <ElOnlyChildkey=0class="el-tooltip__trigger"aria-controls=undefined ...>
 at <ElPopperTriggerid="el-id-4256-0"virtual-ref=undefinedopen=false ...>
 at <ElTooltipTriggerdisabled=falsetrigger="hover"trigger-keys=Enter,Space ...>
 at <ElPopperRootref_key="popperRef"ref=Ref<[object Object]>role="tooltip">
 at <ElTooltipref_key="tooltipRef"ref=Ref<[object Object]>visible=false ...>
 at <ElCascaderoptions=[object Object],[object Object],[object Object]clearable="">
 at <App>
 at <Repl>
```

### Additional comments

能不能优化下Element Plus Playground的URL，那么长，不方便提issues（提示链接过长）。

![image](https://user-images.githubusercontent.com/2074757/211479670-4430ba97-eba8-4d53-b329-d8c7c4a57a3b.png)

**Comment by sleepyShen1989** [comment]
将cascader.vue中defineEmits的参数从对象语法改成数组语法就没有警告了，但是不知道为什么，希望能有解答

```js
// cascader.ts
export const cascaderEmits = {
  [UPDATE_MODEL_EVENT]: (val: CascaderValue) => !!val,
  [CHANGE_EVENT]: (val: CascaderValue) => !!val,
  focus: (evt: FocusEvent) => evt instanceof FocusEvent,
  blur: (evt: FocusEvent) => evt instanceof FocusEvent,
  visibleChange: (val: boolean) => isBoolean(val),
  expandChange: (val: CascaderValue) => !!val,
  removeTag: (val: CascaderNode['valueByOption']) => !!val,
}

// cascader.vue
const emit = defineEmits(cascaderEmits)
// to
const emit = defineEmits([
  'blur',
  CHANGE_EVENT,
  UPDATE_MODEL_EVENT,
  'expandChange',
  'focus',
  'removeTag',
  'visibleChange',
])
```
