### ISSUE TITLE
[Component] [slider] 响应式控制滑块的值，当值设为最大值时会触发input事件 

### ISSUE THREAD

**Issue by LeoJ340** [element-plus/element-plus#11221]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzLCBWaWRlb1BsYXksIFZpZGVvUGF1c2UgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHNyY1RlbXAgPSAnaHR0cHM6Ly9tMTAubXVzaWMuMTI2Lm5ldC8yMDIzMDExMDExNTkyOS8zNjY5YjA2Y2M4MjBmYjZjZjU1ODEwNDg4ODExZDRhNi95eWFhYy8wNjVjLzA3MGYvMDAwZS8xNjkyYjBhYWE0MGVmOTZkODJlNTdkYjFjN2Y3MmE0My5tNGEnXG5jb25zdCBhdWRpbyA9IG5ldyBBdWRpbyhzcmNUZW1wKVxuXG5jb25zdCBwbGF5ZXIgPSByZWFjdGl2ZSh7XG4gIGN1cnJlbnRUaW1lOiAwLFxuICBkdXJhdGlvbjogMCxcbiAgZW5kZWQ6IGZhbHNlLFxuICBsb29wOiBhdWRpby5sb29wLC8vIGRlZmF1bHQgZmFsc2VcbiAgbXV0ZWQ6IGF1ZGlvLm11dGVkLFxuICBuZXR3b3JrU3RhdGU6IGF1ZGlvLm5ldHdvcmtTdGF0ZSxcbiAgcGF1c2VkOiBhdWRpby5wYXVzZWQsXG4gIHBsYXliYWNrUmF0ZTogYXVkaW8ucGxheWJhY2tSYXRlLFxuICByZWFkeVN0YXRlOiBhdWRpby5yZWFkeVN0YXRlLFxuICB2b2x1bWU6IGF1ZGlvLnZvbHVtZSxcbiAgc2xpZGVySW5wdXQ6IGZhbHNlXG59KVxuXG5mdW5jdGlvbiBpbnRlcnZhbCgpIHtcbiAgaWYgKCFwbGF5ZXIuc2xpZGVySW5wdXQpIHtcbiAgICBwbGF5ZXIuY3VycmVudFRpbWUgPSBhdWRpby5jdXJyZW50VGltZVxuICAgIHBsYXllci5lbmRlZCA9IGF1ZGlvLmVuZGVkXG4gIH1cbn1cblxuY29uc3QgdGltZXIgPSBzZXRJbnRlcnZhbChpbnRlcnZhbCwgMTAwMClcblxuZnVuY3Rpb24gcGxheSgpIHtcbiAgYXVkaW8ucGxheSgpLnRoZW4oXyA9PiB7XG4gICAgcGxheWVyLmR1cmF0aW9uID0gYXVkaW8uZHVyYXRpb25cbiAgICBwbGF5ZXIucGF1c2VkID0gYXVkaW8ucGF1c2VkXG4gICAgcGxheWVyLmVuZGVkID0gYXVkaW8uZW5kZWRcbiAgfSlcbn1cblxuZnVuY3Rpb24gcGF1c2UoKSB7XG4gIGF1ZGlvLnBhdXNlKClcbiAgcGxheWVyLnBhdXNlZCA9IGF1ZGlvLnBhdXNlZFxuICBwbGF5ZXIuY3VycmVudFRpbWUgPSBhdWRpby5jdXJyZW50VGltZVxufVxuXG5mdW5jdGlvbiBvblNsaWRlcklucHV0KCkge1xuICBwbGF5ZXIuc2xpZGVySW5wdXQgPSB0cnVlXG4gIGNvbnNvbGUubG9nKCfmiJHooqvop6blj5HkuoYnKVxufVxuXG5mdW5jdGlvbiBvblNsaWRlckNoYW5nZSh2YWw6IG51bWJlcikge1xuICBwbGF5ZXIuc2xpZGVySW5wdXQgPSBmYWxzZVxuICBwbGF5ZXIuY3VycmVudFRpbWUgPSB2YWxcbiAgYXVkaW8uY3VycmVudFRpbWUgPSB2YWxcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8ZWwtYnV0dG9uIGNpcmNsZSA6aWNvbj1cIlZpZGVvUGxheVwiIEBjbGljaz1cInBsYXkoKVwiIC8+XG4gIDxlbC1idXR0b24gY2lyY2xlIDppY29uPVwiVmlkZW9QYXVzZVwiIEBjbGljaz1cInBhdXNlKClcIiAvPlxuICA8ZWwtc2xpZGVyIDpzaG93LXRvb2x0aXA9XCJmYWxzZVwiIHYtbW9kZWw9XCJwbGF5ZXIuY3VycmVudFRpbWVcIiA6bWluPVwiMFwiIDptYXg9XCJwbGF5ZXIuZHVyYXRpb25cIlxuICAgICAgICAgICAgICAgICBAaW5wdXQ9XCJvblNsaWRlcklucHV0XCIgQGNoYW5nZT1cIm9uU2xpZGVyQ2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

当音乐播放结束时，自动触发了input事件

### What is Expected?

不触发input事件

### What is actually happening?

触发了input事件

### Additional comments

_(empty)_

**Comment by tetap** [comment]
我也遇到了一样的问题.

**Comment by warmthsea** [comment]
Please provide a minimal reproducible code that works, thanks!
请提供一个有效的可直接运行的最小复现，谢谢！

**Comment by warmthsea** [comment]
> 我也遇到了一样的问题.

Please provide a minimal reproducible code that works, thanks!
请提供一个有效的可直接运行的最小复现，谢谢！

**Comment by tetap** [comment]
> > 我也遇到了一样的问题.
> 
> Please provide a minimal reproducible code that works, thanks! 请提供一个有效的可直接运行的最小复现，谢谢！

经过的我重新修改后 发现，其实是超过的max的值，触发应当是合理的。

[https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzLCBWaWRlb1BsYXksIFZpZGVvUGF1c2UgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZHVyYXRpb24gPSA1XG5jb25zdCBwbGF5ZXIgPSByZWFjdGl2ZSh7XG4gIGN1cnJlbnRUaW1lOiAwLFxuICBkdXJhdGlvbjogZHVyYXRpb24sXG4gIGVuZGVkOiBmYWxzZSxcbiAgc2xpZGVySW5wdXQ6IGZhbHNlXG59KVxuXG5mdW5jdGlvbiBpbnRlcnZhbCgpIHtcbiAgLy8gcGxheWVyLmN1cnJlbnRUaW1lID0gTWF0aC5taW4ocGxheWVyLmN1cnJlbnRUaW1lICsgMSwgZHVyYXRpb24pO1xuICBwbGF5ZXIuY3VycmVudFRpbWUgPSBwbGF5ZXIuY3VycmVudFRpbWUgKyAxO1xufVxuXG5sZXQgdGltZXIgPSBudWxsO1xuXG5mdW5jdGlvbiBwbGF5KCkge1xuICBjb25zb2xlLmxvZygncGxheScpXG4gIHRpbWVyID0gc2V0SW50ZXJ2YWwoaW50ZXJ2YWwsIDEwMDApXG5cbn1cblxuZnVuY3Rpb24gcGF1c2UoKSB7XG4gIGNsZWFySW50ZXJ2YWwodGltZXIpXG59XG5cbmZ1bmN0aW9uIG9uU2xpZGVySW5wdXQoKSB7XG4gIHBsYXllci5zbGlkZXJJbnB1dCA9IHRydWVcbiAgY29uc29sZS5sb2coJ+aIkeiiq+inpuWPkeS6hicpXG59XG5cbmZ1bmN0aW9uIG9uU2xpZGVyQ2hhbmdlKHZhbDogbnVtYmVyKSB7XG4gIHBsYXllci5zbGlkZXJJbnB1dCA9IGZhbHNlXG4gIHBsYXllci5jdXJyZW50VGltZSA9IHZhbFxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1idXR0b24gY2lyY2xlIDppY29uPVwiVmlkZW9QbGF5XCIgQGNsaWNrPVwicGxheSgpXCIgLz5cbiAgPGVsLWJ1dHRvbiBjaXJjbGUgOmljb249XCJWaWRlb1BhdXNlXCIgQGNsaWNrPVwicGF1c2UoKVwiIC8+XG4gIDxlbC1zbGlkZXIgOnNob3ctdG9vbHRpcD1cImZhbHNlXCIgdi1tb2RlbD1cInBsYXllci5jdXJyZW50VGltZVwiIDptaW49XCIwXCIgOm1heD1cInBsYXllci5kdXJhdGlvblwiXG4gICAgICAgICAgICAgICAgIEBpbnB1dD1cIm9uU2xpZGVySW5wdXRcIiBAY2hhbmdlPVwib25TbGlkZXJDaGFuZ2VcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsIl9vIjp7fX0=](url)
