### ISSUE TITLE
[Style] [button] 为什么 MessageBox 的 button 默认是 hover 样式

### ISSUE THREAD

**Issue by jinyu2022** [element-plus/element-plus#11253]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gdGhlIE1lc3NhZ2UgQm94PC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSB7IEFjdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmFsZXJ0KCdUaGlzIGlzIGEgbWVzc2FnZScsICdUaXRsZScsIHtcbiAgICAvLyBpZiB5b3Ugd2FudCB0byBkaXNhYmxlIGl0cyBhdXRvZm9jdXNcbiAgICAvLyBhdXRvZm9jdXM6IGZhbHNlLFxuICAgIGNvbmZpcm1CdXR0b25UZXh0OiAnT0snLFxuICAgIGNhbGxiYWNrOiAoYWN0aW9uOiBBY3Rpb24pID0+IHtcbiAgICAgIEVsTWVzc2FnZSh7XG4gICAgICAgIHR5cGU6ICdpbmZvJyxcbiAgICAgICAgbWVzc2FnZTogYGFjdGlvbjogJHthY3Rpb259YCxcbiAgICAgIH0pXG4gICAgfSxcbiAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击button，跳出消息提示框，此时消息提示框里的OK按钮是hover样式

### What is Expected?

点击button，消息提示框的 OK 按钮应当不是 hover 
样式。点击 OK 按钮后。Button也不是 hover 样式

### What is actually happening?

点击button，消息提示框的 OK 按钮一开始就是是 hover 样式。点击 OK 按钮后。 button 没有变回一般样式，仍是 hover 样式

### Additional comments

_(empty)_

**Comment by MARIOMARUI** [comment]
确实有这个问题，可以设置box为选中状态el.focus()

**Comment by MARIOMARUI** [comment]
有个属性 autofocus = false

**Comment by jinyu2022** [comment]
> 有个属性 autofocus = false
看到了，那么普通的button呢，按下去后依然会自动对焦

**Comment by Zohar727** [comment]
我也遇到了这个问题，后来发现这个按钮默认其实就是 focus 态，只是按钮的focus 样式和 hover 样式相同，所以看起来是hover态。。
