### ISSUE TITLE
[Component] [input-number] value obtained by v-model  is not equal to e.target.value

### ISSUE THREAD

**Issue by wangyanweiie** [element-plus/element-plus#11259]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `e.g. Chrome 96.0.4664.45`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoMCk7XG5jb25zdCBuZXdtc2cgPSByZWYoMCk7XG4gIFxuZnVuY3Rpb24gaGFuZGxlQmx1cihlOiBhbnkpIHtcbiAgLy8gY29uc29sZS5sb2cobXNnKTtcbiAgLy8gY29uc29sZS5sb2coZS50YXJnZXQudmFsdWUpO1xuICBuZXdtc2cudmFsdWUgPSBlLnRhcmdldC52YWx1ZTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+5Y+M5ZCR57uR5a6a55qE5YC8OiB7eyBtc2cgfX08L2Rpdj5cbiAgPGRpdj5JbnB1dOahhuWGheeahOWAvDoge3sgbmV3bXNnIH19PC9kaXY+XG4gIDxlbC1pbnB1dC1udW1iZXJcbiAgICAgIHYtbW9kZWw9XCJtc2dcIlxuICAgICAgOmNvbnRyb2xzPVwiZmFsc2VcIlxuICAgICAgOnN0eWxlPVwieyB3aWR0aDogJzEwMCUnIH1cIlxuICAgICAgQGJsdXI9XCJoYW5kbGVCbHVyXCJcbiAgPlxuICA8L2VsLWlucHV0LW51bWJlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click -- enter any number --blur -- enter a bit -- delete a bit -- blur
【点击 -- 输入任意数字 -- 失焦得到当前值 -- 输入一位光标不移出输入框 -- 删除刚刚输入的一位 -- 失焦得到值】

### What is Expected?

value obtained by v-model === e.target.value
【双向绑定的值等于输入框内展示的值】

### What is actually happening?

value obtained by v-model !== e.target.value
【双向绑定的值不等于输入框内展示的值】

### Additional comments

_(empty)_

**Comment by acyza** [comment]
![a](https://user-images.githubusercontent.com/101238421/212033889-91bc0e4d-c6e9-4047-b1bf-6a7e403f2e5c.gif)
像这样？

**Comment by scjianlin** [comment]
我也遇到了这个问题，在el-form中使用el-input修改绑定的变量，但是实际上变量值并未修改。

**Comment by wangyanweiie** [comment]
> 像这样？ ![img](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) [ ![img](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) ](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) [ ](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif)

是的，就是这样，目前我只能通过在失焦事件获取 e.target.value 拿到页面显示的值。

**Comment by wangyanweiie** [comment]
> 像这样？ ![img](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) [ ![img](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) ](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif) [ ](https://user-images.githubusercontent.com/101238421/212035664-4489a21d-01a4-4152-9bc7-2f5fbfc87300.gif)

是的，就是这样，目前我只能通过在失焦事件获取 e.target.value 拿到页面显示的值。

**Comment by wangyanweiie** [comment]
> 我也遇到了这个问题，在el-form中使用el-input修改绑定的变量，但是实际上变量值并未修改。

我是失焦事件拿到 e.target.value 又去手动赋值了

**Comment by wangyanweiie** [comment]
@acyza 是的 就是这样

**Comment by wangyanweiie** [comment]
@scjianlin 我是暂时通过在失焦事件拿到了 e.target.value 去手动赋值的

**Comment by acyza** [comment]
v-model绑定的值的修改好像是这个change事件触发的，但它在值和上次完成修改后的值一样的时候不会触发。
https://github.com/element-plus/element-plus/blob/dev/packages/components/input-number/src/input-number.vue#L58

**Comment by Naeemo** [comment]
Looks like this behavior was introduced by https://github.com/element-plus/element-plus/pull/10980

**Comment by wangyanweiie** [comment]
@acyza 这里吗
![image](https://user-images.githubusercontent.com/88811564/212055190-fc24b011-bb75-403f-87c9-c471062fc3c3.png)

**Comment by acyza** [comment]
https://github.com/element-plus/element-plus/compare/dev...acyza:element-plus:fixInputNumber
这样子应该就好了。
![img](https://user-images.githubusercontent.com/101238421/212066916-b9d4cb7e-2167-492c-a0d0-2e4e358556d2.gif)

**Comment by acyza** [comment]
[commit](https://github.com/element-plus/element-plus/compare/dev...acyza:element-plus:fixInputNumber)
这样子应该就好了。
![a](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)

**Comment by Naeemo** [comment]
> [commit](https://github.com/element-plus/element-plus/compare/dev...acyza:element-plus:fixInputNumber)
> 
> 这样子应该就好了。
> 
> ![a](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)
> 
> 

单测能过吗？

**Comment by acyza** [comment]
> > [commit](https://github.com/element-plus/element-plus/compare/dev...acyza:element-plus:fixInputNumber)
> > 这样子应该就好了。
> > ![a](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)
> >       
> >         [
> >           
> >         
> >             ![a](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)
> >           ](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/101238421/212067134-53edfa00-41db-4935-9011-bd3a4d0f6994.gif)
> 
> 单测能过吗？

过不了，change事件好像不触发了
![图片](https://user-images.githubusercontent.com/101238421/212076057-5fbd48ac-5422-47a6-9ef9-06cba27a2a4e.png)

**Comment by acyza** [comment]
[commit](https://github.com/acyza/element-plus/commit/2ccac4589b192c0d6b56e2238d0668cb175d2c58)这样应该就可以了
![图片](https://user-images.githubusercontent.com/101238421/212076467-5b3f5d65-08f9-46f9-b252-c983b9366847.png)

**Comment by Naeemo** [comment]
@acyza time to open a PR 😊
