### ISSUE TITLE
[Docs] [All] （elementPlus文档）TreeSelect部门文档，属性部分显示异常

### ISSUE THREAD

**Issue by ArchieSean-YH** [element-plus/element-plus#11252]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/#%E5%B1%9E%E6%80%A7)

### Steps to reproduce

https://element-plus.gitee.io/zh-CN/#%E5%B1%9E%E6%80%A7

### What is Expected?

展示正常

### What is actually happening?

展示异常

### Additional comments

_(empty)_

**Comment by acyza** [comment]
已经修复了，等新版本吧！#11185
