### ISSUE TITLE
El-menu sidebar problem

### ISSUE THREAD

**Issue by readpage** [element-plus/element-plus#1125]
Element-plus'S EL-Menu sidebar closes with no transition animations, and the visual experience is jammed!Use the Element-UI sidebar to turn off smoothness,
Hope to fix the problem.

The first section of the video is Element-Plus and the second section is Element-UI
![4](https://user-images.githubusercontent.com/65387014/103138190-050ecb00-470b-11eb-80ae-c95a754fe46a.gif)

**Comment by readpage** [comment]
El - Menu folding function editor displays a problem, I did not change the editor code!
![) VZSN3)~50P$RH_2UKWPL4](https://user-images.githubusercontent.com/65387014/103138351-96327180-470c-11eb-8872-f65eab4464a0.png)

**Comment by readpage** [comment]
I changed the CND URL of Element-Plus and Vue3 into Element-UI and Vue2, Normal transition animation, no card phenomenon.
I checked it several times!

**Comment by readpage** [comment]
element-plus: https://codepen.io/readpage/pen/jOMaavX
element-ui:https://codepen.io/readpage/pen/MWjOOqd

**Comment by chinaapus** [comment]
新上的一个项目因为这个问题 ，改用 ANTD 了 。暂时放弃尝试VUE3 + PLUS

**Comment by Chris-Kin** [comment]
Seems to have been fixed.

**Comment by Ttou** [comment]
@chinaapus 关闭菜单无动画的问题，antd也存在，这是vue3.0.4的bug，退回vue3.0.3就正常了

**Comment by wxs77577** [comment]
https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md
vue 3.0.5 应该修复了

**Comment by JeremyWuuuuu** [comment]
See the attachment, I recorded it on our doc website.
https://user-images.githubusercontent.com/15975785/103509468-2f485180-4e9e-11eb-9deb-e01ba7950a3c.mov

**Comment by JeremyWuuuuu** [comment]
This is consider fixed due to the upgrade of `Vue` if you find your local version not woking, please try upgrade to Vue `3.0.5` first and retry, feel free to reopen this issue.
