### ISSUE TITLE
[Component] [message] Message 设置 offset，多条之间间隔会变成 offset

### ISSUE THREAD

**Issue by linxianxi** [element-plus/element-plus#11267]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIDpwbGFpbj1cInRydWVcIiBAY2xpY2s9XCJvcGVuXCI+U2hvdyBtZXNzYWdlPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlKHsgbWVzc2FnZTogJ3RoaXMgaXMgYSBtZXNzYWdlLicsIG9mZnNldDogMjAwIH0pXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

多次点击

### What is Expected?

间隔始终为 20

### What is actually happening?

间隔变大

### Additional comments

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/47104575/212216792-e48fefde-e803-4045-ba28-e139115443a2.png">

**Comment by btea** [comment]
This should be normal behavior, because you set the offset to 200.

**Comment by linxianxi** [comment]
> This should be normal behavior, because you set the offset to 200.

you can try notification offset.

**Comment by btea** [comment]
Ok, I get your point.
