### ISSUE TITLE
[Feature Request] Can support fixed scrolling of position: sticky; feature

### ISSUE THREAD

**Issue by yuenc** [element-plus/element-plus#1126]
### Existing Component
Yes

### Component Name
el-table

### Description
Whether it can support fixed scrolling of position: sticky; feature, which can avoid more rendering and improve performance

**Comment by justwiner** [comment]
Hey! @yuenc 
I don’t think this is a good way, `position: sticky` is not supported in IE browser  
  

![image](https://user-images.githubusercontent.com/30335393/103497885-e1235600-4e7d-11eb-8a40-07e7eb281869.png)
