### ISSUE TITLE
[Component] [form-item, checkbox] el-form-item required asterisk not shown for empty labels

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#11263]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-form-item`
- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnPDwtLSBhbGwgcmVxdWlyZWQhJyxcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIDptb2RlbD1cImZvcm1cIlxuICAgIDpsYWJlbC13aWR0aD1cIjE3MFwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwibXkgbGFiZWxcIiByZXF1aXJlZCBwcm9wPVwibmFtZVwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm5hbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gcmVxdWlyZWQgcHJvcD1cIm5hbWVcIj5cbiAgICAgIDxlbC1jaGVja2JveCB2LW1vZGVsPVwiZm9ybS5uYW1lXCI+dGhpcyBpcyByZXF1aXJlZCB0b28sIGJ1dCBubyBhc3RlcmlzayBpcyBzaG93bjwvZWwtY2hlY2tib3g+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGRpdiBjbGFzcz1cImZpeFwiPlxuICAgICAgPGVsLWZvcm0taXRlbSByZXF1aXJlZCBwcm9wPVwibmFtZVwiPlxuICAgICAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cImZvcm0ubmFtZVwiPmhlcmUgYSBjdXN0b20gY3NzIGZpeGVzIHRoaXM8L2VsLWNoZWNrYm94PlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9kaXY+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5maXggLmlzLXJlcXVpcmVkLmFzdGVyaXNrLWxlZnQgLmVsLWZvcm0taXRlbV9fY29udGVudDpmaXJzdC1jaGlsZDo6YmVmb3JlIHtcbiAgY29udGVudDogJyonO1xuICBjb2xvcjogdmFyKC0tZWwtY29sb3ItZGFuZ2VyKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBoZWlnaHQ6IDEwMCU7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGxlZnQ6IC0yMHB4O1xuICBmb250LXNpemU6IDE2cHg7XG59XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

I can leave the label blank, i.e. when I use a checkbox and only want to display the text on the right side.

### What is Expected?

The required asterisk should always be shown for required fields.

### What is actually happening?

It's not shown if the label is empty.

### Additional comments

Please have a look at the reproduction link for a demo.
There I also provided a "hacky" css fix for this.

**Comment by btea** [comment]
Perhaps you can provide a space for the label, [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnPDwtLSBhbGwgcmVxdWlyZWQhJyxcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIDptb2RlbD1cImZvcm1cIlxuICAgIDpsYWJlbC13aWR0aD1cIjE3MFwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwibXkgbGFiZWxcIiByZXF1aXJlZCBwcm9wPVwibmFtZVwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm5hbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gcmVxdWlyZWQgcHJvcD1cIm5hbWVcIj5cbiAgICAgIDxlbC1jaGVja2JveCB2LW1vZGVsPVwiZm9ybS5uYW1lXCI+dGhpcyBpcyByZXF1aXJlZCB0b28sIGJ1dCBubyBhc3RlcmlzayBpcyBzaG93bjwvZWwtY2hlY2tib3g+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGRpdiBjbGFzcz1cImZpeFwiPlxuICAgICAgPGVsLWZvcm0taXRlbSByZXF1aXJlZCBwcm9wPVwibmFtZVwiIGxhYmVsPVwiIFwiPlxuICAgICAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cImZvcm0ubmFtZVwiPmhlcmUgYSBjdXN0b20gY3NzIGZpeGVzIHRoaXM8L2VsLWNoZWNrYm94PlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9kaXY+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by plehnen** [comment]
@btea Hi, thanks for your feedback. I tried that first, but the position of the asterisk is not aligned with the remaining text and looks misplaced. (Our font size and type is larger and the gap is very much visible.)

If you toggle your demo with my demo you see the position jumping a little bit.
I think it would be nice if el-form-item would not hide the asterisk for required fields. Feels like a bug to me.

**Comment by chenxch** [comment]
It's designed like this, you can give the label a space string to make it render <label>.
