### ISSUE TITLE
[bug report] ele 3.0 V-IF when the expression does not hold, the compilation of the template is only abnormal in the ele component

### ISSUE THREAD

**Issue by laosandegudai** [element-plus/element-plus#1127]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
Chrome

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/laosandegudai/pen/eYdeyPg?editors=1111

### Steps to reproduce
声明空数组  menus: []
v-if 判断menus.length>0
异步填充menus

![ZDFT2) XKUV`${ZRJH54B~A](https://user-images.githubusercontent.com/17979159/103147765-595d8d80-4793-11eb-920b-7edee29cc6a5.png)

### What is Expected?
期望能找到原因，是我的用法不对吗？因为3.0之前是这样写的。

### What is actually happening?
当前操作实在模仿一个加载列表的业务场景，一个空的数组在异步加载数据后填充数组，出现了尽在ele控件内才出现的异常。
异常表现是，当数组被填充后，加了v-if的控件不能正常获取数据，这个异常仅在ele控件内才会出现，在ele控件外正常。

**Comment by SimonaliaChen** [comment]
This bug is caused by vue https://github.com/vuejs/vue-next/issues/2737 which has been fixed but not released. You can keep an eye on it.

**Comment by zazzaz** [comment]
You can downgrade to Vue@3.0.3 until Vue-next fixed this issue.
