### ISSUE TITLE
[Component] [All] el-form-item label click event will trigger el-switch change

### ISSUE THREAD

**Issue by roojay520** [element-plus/element-plus#11286]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome  98.0.4758.102 / macOS 10.14.6 `
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgXG5jb25zdCBmb3JtRGF0YSA9IHJlYWN0aXZlKHtcbiAgdGVzdDogZmFsc2Vcbn0pXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICA8ZWwtZm9ybSByZWY9XCJmb3JtUmVmXCIgOm1vZGVsPVwiZm9ybURhdGFcIiBsYWJlbC13aWR0aD1cIjE1MHB4XCI+XG4gICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJ0ZXN0IGxhYmVsXCI+XG4gICAgICA8ZWwtc3dpdGNoIHYtbW9kZWw9XCJmb3JtRGF0YS50ZXN0XCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup lang="ts">
import { reactive } from 'vue'
import { ElementPlus } from '@element-plus/icons-vue'
  
const formData = reactive({
  test: false
})

</script>

<template>
   <el-form ref="formRef" :model="formData" label-width="150px">
     <el-form-item label="test label">
      <el-switch v-model="formData.test" />
    </el-form-item>
  </el-form>
</template>
```

### What is Expected?

click switch element trigger change rather than click label

### What is actually happening?

click el-form-item label will trigger el-switch change

### Additional comments

How to disable this?

I try to use css disable this, but not trigger #label slot el-tooltip
```css
.el-form-item__label {
  pointer-events: none;
}
```

**Comment by chenxch** [comment]
#9752
Please search the question before asking, maybe you can solve your problem quickly.
