### ISSUE TITLE
[Bug Report]  [el-menu close the animation  bug] and[El - carouse translateX bug] 

### ISSUE THREAD

**Issue by readpage** [element-plus/element-plus#1128]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
win10/ Google Chrome	87.0.4280.88

### Vue version
3.0.4

### Reproduction Link
1.https://codepen.io/readpage/pen/jOMaavX   2.https://codepen.io/readpage/pen/jOMaKrV

### Steps to reproduce
The first link el-Menu opens by clicking the blue button, and then closes without the transition animation, which Element-UI has.

The second link is to initialize the maximum window of el-Carouse, and then to reduce the size of the window, you will find a gap between the images, because translateX maximizes the window by 1500px, and translateX does not change when it is reduced.Element-ui is normal translateX that changes depending on the screen size

### What is Expected?
Fixed el-Menu latching issue and fixed El-Carousel transitoinX miniaturization window without changing issue

### What is actually happening?
First bug:When element-plus's El-Carouse translateX plays in the full-screen browser, translateX of the reduced window does not change, resulting in a blank space between the switch.
Second bug:There is no transition animation when the Element-Plus EL-Menu sidebar closes, and the visual experience gets stuck!Use the Element-UI sidebar to turn it off smoothly and normally

This is not the case with Element-UI,Mainly because of using vue3 otherwise I would have wanted to go back to Element-UI
New project bugs are normal,Hope the developers fix it soon

**Comment by JeremyWuuuuu** [comment]
cc @Liiked

**Comment by JeremyWuuuuu** [comment]
I think the second bug you mentioned would be fixed if you upgrade your local `vue` version to `3.0.5` and also upgrade `element-plus` to the latest, could you verify that? Feel free to ping me.

**Comment by readpage** [comment]
Thank you very much!Upgrade version VUE and Element-Plus will not be compatible!
It needs the corresponding version, which is the latest version. It seems not possible.
As the version stabilizes, I'm updating,
I don't pay attention to these effects now and go in other directions!
@JeremyWuuuuu  Thank you very much!I have tried version 3.0.0, but there is still a problem when I press the release button quickly. Only by slowly clicking the release button can I make a normal transition animation!
