### ISSUE TITLE
[Component] [input, menu] menu 组件使用 mode 为 horizontal 情况下，加入 input 组件，input 中无法输入空格

### ISSUE THREAD

**Issue by senmu-a** [element-plus/element-plus#11292]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 titansx (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBoYW5kbGVJbnB1dCA9ICh2YWwpID0+IHtcbiAgY29uc29sZS5sb2codmFsKVxuICBtc2cudmFsdWUgPSB2YWxcbn1cblxuY29uc3QgYWN0aXZlSW5kZXggPSByZWYoJzEnKVxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgXG4gIDxlbC1tZW51XG4gICAgOmRlZmF1bHQtYWN0aXZlPVwiYWN0aXZlSW5kZXhcIlxuICAgIGNsYXNzPVwiZWwtbWVudS1kZW1vXCJcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gID5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMVwiPlByb2Nlc3NpbmcgQ2VudGVyPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjNcIiBkaXNhYmxlZD5JbmZvPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj48ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIEBpbnB1dD1cImhhbmRsZUlucHV0XCIgLz48L2VsLW1lbnUtaXRlbT5cbiAgPC9lbC1tZW51PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
const handleInput = (val) => {
  console.log(val)
  msg.value = val
}

const activeIndex = ref('1')
const handleSelect = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
</script>

<template>
  <el-menu
    :default-active="activeIndex"
    mode="horizontal"
    @select="handleSelect"
  >
    <el-menu-item index="1">Processing Center</el-menu-item>
    <el-menu-item index="4"><el-input v-model="msg" @input="handleInput" /></el-menu-item>
  </el-menu>
</template>
```

### What is Expected?

期望可以在 el-menu 设置 mode 为 horizontal 下 el-input 可以输入空格

### What is actually happening?

在 el-menu 设置 mode 为 horizontal 下 el-input 不可以输入空格

### Additional comments

_(empty)_

**Comment by senmu-a** [comment]
我知道可以通过阻止事件冒泡解决，但是 mode 属性 horizontal 和 vertical 行为不一致是设计时候就是这样吗？（望答复）

**Comment by btea** [comment]
cc @element-plus/backers

**Comment by tolking** [comment]
这属于无障碍相关设计，默认 Space 按键用于选取菜单。

目前菜单的无障碍还需要完善，horizontal 和 vertical 行为差异也是由于这个原因引起。

个人觉得在菜单中嵌套输入框不是属于菜单的标准使用方式，建议你自行处理。
