### ISSUE TITLE
### Cascader

### ISSUE THREAD

**Issue by SimonaliaChen** [element-plus/element-plus#113]

**Comment by g3r4n** [comment]
@SimonaliaChen are you working on this one ?

**Comment by g3r4n** [comment]
@JeremyWuuuuu , no one seems to take care of this one, can I do it ?

**Comment by SimonaliaChen** [comment]
> @SimonaliaChen are you working on this one ?

Sorry, I haven't checked messages lately. I'm already on it and almost done. Thanks for the help.
