### ISSUE TITLE
[All] Dynamic Component using auto import won't load the css or style

### ISSUE THREAD

**Issue by suryaadtmaja** [element-plus/element-plus#11316]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](https://stackblitz.com/edit/node-zkhoi9?file=src/components/HelloWorld.vue)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue';
import { ElDatePicker } from 'element-plus';

defineProps<{ msg: string }>();

const count = ref(0);
const input = ref('element-plus');

const curDate = ref('');
</script>

<template>
  <div>
    <h3>hello</h3>
    <component :is="ElDatePicker" />
    <ElInput />
  </div>
</template>

<style>
.ep-button {
  margin: 4px;
}
</style>
```

### What is Expected?

It rendered the style of the component

### What is actually happening?

It rendered fine for the first time and after refreshing the app it does not render with style or css

### Additional comments

I'm using element-plus with unplugin-vue-component like this one https://github.com/element-plus/element-plus-vite-starter

**Comment by filsuck** [comment]
I see that if i'm not using unplugin-vue-component, it works perfectly fine

[Reproduction Link
](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8Y29tcG9uZW50IDppcz1cIkVsRGF0ZVBpY2tlclwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

So, I guess it's not element-plus problem at all, but I still curious about what happens, I'm sorry if its not related at all to the element-plus

**Comment by btea** [comment]
You can refer to the [documentation](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5)

**Comment by tolking** [comment]
[Link](https://github.com/antfu/unplugin-vue-components/issues/11)
