### ISSUE TITLE
[Component] [row] 栅格系统中的栅格间隔gutter不支持水平、垂直间隔分开设置

### ISSUE THREAD

**Issue by PaulMing** [element-plus/element-plus#11315]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-row`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/layout.html#%E5%9F%BA%E4%BA%8E%E6%96%AD%E7%82%B9%E7%9A%84%E9%9A%90%E8%97%8F%E7%B1%BB)

### Steps to reproduce

不支持垂直间隔

### What is Expected?

支持

### What is actually happening?

支持

### Additional comments

栅格常常需要和间隔进行配合，你可以使用 Row 的 gutter 属性，我们推荐使用 (16+8n)px 作为栅格间隔(n 是自然数)。

如果要支持响应式，可以写成 { xs: 8, sm: 16, md: 24, lg: 32 }。

如果需要垂直间距，可以写成数组形式 [水平间距, 垂直间距] [16, { xs: 8, sm: 16, md: 24, lg: 32 }]。

**Comment by chenxch** [comment]
Support for this part is not currently considered, and you can implement it yourself through css.
