### ISSUE TITLE
[Component] [select] [el-select] Change event should also be triggered on keydown.tab and not only keydown.enter event

### ISSUE THREAD

**Issue by wldrve** [element-plus/element-plus#11327]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome 109.0.5414.75`
- Build Tool: `esbuild`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6ZGVmYXVsdC1maXJzdC1vcHRpb249XCJ0cnVlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

El-Select change trigger should also work on keydown.tab event and not only on keydown.enter. 

1. Create a simple el-select component with options array,
2. "Optional - QUICKER REPRODUCTION" - Set :default-first-value="true" and :filterable="true" (so you get first option selected and you can also filter to choose another option/or just use your up and down arrows).
3. Click on el-select to open the dropdown with options and press on TAB key on your keyboard

### What is Expected?

1. Expected is a change in v-model value (should be the selected option if one is selected).
2. If no option is selected, nothing changes (this works already) and dropdown closes. 
3. Focus on next html element.

### What is actually happening?

I presume change trigger is now only working on keydown.enter event and not also on keydown.tab event. Please add keydown.tab event to trigger el-select change as it is also working like so in native html select.

### Additional comments

If I am wrong and do not understand the usage of the component, please let me know how to change the el-select v-model or trigger change on keydown.tab in el-select component (I have tried already with @keydown.tab, but achived little success).

**Comment by wldrve** [comment]
Anybody?

**Comment by tolking** [comment]
I do not think this is a good idea. The Tab key should not be used to select option.

If you are sure to do this, perhaps you should bind the event to ElOption.

**Comment by wldrve** [comment]
@tolking And may I ask why not?

Every other UI framework for Vue 3 allows this (Primevue etc.) + native HTML select box allows this. I managed to do it, but it is a quick and dirty solution.

**Comment by tolking** [comment]
You can view the behavior of the native select.

[Link](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5mdW5jdGlvbiBsb2coZSkge1xuICBjb25zb2xlLmxvZyhlKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHNlbGVjdCBAY2hhbmdlPVwibG9nXCI+XG4gICAgPG9wdGlvbiB2YWx1ZT1cIjExMVwiPjExMTwvb3B0aW9uPlxuICAgIDxvcHRpb24gdmFsdWU9XCIyMjJcIj4yMjI8L29wdGlvbj5cbiAgICA8b3B0aW9uIHZhbHVlPVwiMzMzXCI+MzMzPC9vcHRpb24+XG4gICAgPG9wdGlvbiB2YWx1ZT1cIjQ0NFwiPjQ0NDwvb3B0aW9uPlxuICA8L3NlbGVjdD5cbiAgPGJ1dHRvbj5cbiAgICBidXR0b25cbiAgPC9idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by wldrve** [comment]
@tolking Still, no offense, but what do you want to say or what is your point? I know how the native select works and tab selection works in native select.
