### ISSUE TITLE
[Component] [input] el-input 的自定义指令中绑定的 focus 与 blur 事件不触发

### ISSUE THREAD

**Issue by fcl999** [element-plus/element-plus#11320]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgbGlzdCA9IHJlZihbXSlcbmZ1bmN0aW9uIGFkZCh0eXBlLCBlKSB7XG4gIGNvbnNvbGUubG9nKHR5cGUsIGUpXG4gIGxpc3QudmFsdWUucHVzaCh0eXBlKVxufVxuY29uc3QgdklucHV0TGltaXQgPSB7XG4gIG1vdW50ZWQoZWwpIHtcblx0XHRlbC5hZGRFdmVudExpc3RlbmVyKCdmb2N1cycsKGUpPT5hZGQoJ3YtZm9jdXMnLCBlKSlcblx0XHRlbC5hZGRFdmVudExpc3RlbmVyKCdpbnB1dCcsKGUpPT5hZGQoJ3YtaW5wdXQnLCBlKSlcblx0XHRlbC5hZGRFdmVudExpc3RlbmVyKCdibHVyJywoZSk9PmFkZCgndi1ibHVyJywgZSkpXG4gIH0sXG59XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgXG4gICAgdi1pbnB1dC1saW1pdCBcbiAgICB2LW1vZGVsPVwibXNnXCJcbiAgICBAaW5wdXQ9XCJhZGQoJ2lucHV0JyksICRldmVudFwiXG4gICAgQGZvY3VzPVwiYWRkKCdmb2N1cycpLCAkZXZlbnRcIlxuICAgIEBibHVyPVwiYWRkKCdibHVyJyksICRldmVudFwiLz5cbiAgPHAgdi1mb3I9XCJpdGVtIGluIGxpc3RcIj5cbiAgICB7e2l0ZW19fVxuICA8L3A+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

输入框聚焦，输入值，让输入框失焦

### What is Expected?

指令中的事件均触发

### What is actually happening?

指令中的除input事件均不触发

### Additional comments

删除模板中的@绑定 指令中的事件依旧不触发

**Comment by chenxch** [comment]
你或许需要查看一下组件的dom结构，根据这个优化一下你的指令,例如
```vue
const vInputLimit = {
  mounted(el) {
		el.querySelector('input').addEventListener('focus',(e)=>add('v-focus', e))
		el.querySelector('input').addEventListener('input',(e)=>add('v-input', e))
		el.querySelector('input').addEventListener('blur',(e)=>add('v-blur', e))
  },
}
```
