### ISSUE TITLE
[Component] [button] Loading状态的text/link el-button背景不透明

### ISSUE THREAD

**Issue by ZhouShuren1881** [element-plus/element-plus#11328]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome 109`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogYmxhY2tcIj5cbiAgICA8ZWwtYnV0dG9uIGxpbmsgbG9hZGluZyB0eXBlPVwicHJpbWFyeVwiPlxuICAgICAg5Yqg6L295Lit55qE5oyJ6ZKu77yM6IOM5pmv5Y+XIC5lbC1idXR0b24uaXMtbG9hZGluZzpiZWZvcmUg5b2x5ZONXG4gICAgPC9lbC1idXR0b24+XG4gICAgPGJyLz5cbiAgICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIj5cbiAgICAgIOaZrumAmueahOaWh+Wtl+aMiemSru+8jOiDjOaZr+aYr+mAj+aYjueahFxuICAgIDwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击最小复现环境的链接即可触发该BUG。
Click minimal reproduction link to trigger this bug.

### What is Expected?

loading状态下link/text的el-button背景透明。
&lt;el-button link loading/&gt; should be transparent.

### What is actually happening?

按钮受.el-button.is-loading:before选择器影响，背景不透明。
Buttons are css-selector affected and have an opaque background.

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/61644268/214490687-0036b722-239c-4abd-94a9-8909dc3d4406.png)

**Comment by holazz** [comment]
这里就是这样设计的，你可以通过覆盖 CSS 样式来修改背景色
