### ISSUE TITLE
[Component] [table] 当 table-layout 为 auto 时，固定表头失效

### ISSUE THREAD

**Issue by sakino1999** [element-plus/element-plus#11353]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Chrome 109.0.5414.120`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsVGFibGUsIEVsVGFibGVDb2x1bW4gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG4gY29uc3QgdGFibGVEYXRhID0gW1xuICAgICB7XG4gICAgICAgYTogJzEnLFxuICAgICAgIGI6ICcyJyxcbiAgICAgfSxcbiAgICAge1xuICAgICAgIGE6ICcxJyxcbiAgICAgICBiOiAnMicsXG4gICAgIH0sXG4gICAgIHtcbiAgICAgICBhOiAnMScsXG4gICAgICAgYjogJzInLFxuICAgICB9LFxuICAgICB7XG4gICAgICAgYTogJzEnLFxuICAgICAgIGI6ICcyJyxcbiAgICAgfSxcbiAgICAge1xuICAgICAgIGE6ICcxJyxcbiAgICAgICBiOiAnMicsXG4gICAgIH0sXG4gIF1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHRhYmxlLWxheW91dD1cImF1dG9cIiBoZWlnaHQ9XCIxMDBcIj5cbiAgXHQ8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhXCIgbGFiZWw9XCJBXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJiXCIgbGFiZWw9XCJCXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-table 的 table-layout 设为 auto , 并给予固定高度(设置 height 属性)

### What is Expected?

当给予固定高度时，并将 table-layout 设为 auto，上下滚动 table 时表头固定。

### What is actually happening?

当给予固定高度，将 table-layout 设为 auto时，表头没有固定。

### Additional comments

_(empty)_

**Comment by allonsmandy** [comment]
+1
