### ISSUE TITLE
[Component] ElPopper组件在原生dialog模态框打开时无法交互

### ISSUE THREAD

**Issue by shc0743** [element-plus/element-plus#11354]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-popper`
- `el-popover`
- `el-select`
- `el-select-v2`
- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGlhbG9nIHJlZj1kbGc+XG4gIDxlbC1wb3BvdmVyXG4gICAgd2lkdGg9MjAwXG4gICAgdHJpZ2dlcj1cImhvdmVyXCJcbiAgPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiJHJlZnMuZGxnLmNsb3NlKClcIj5DbGljayB0byBjbG9zZSBkaWFsb2c8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJtLTJcIj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbjwvZGlhbG9nPlxuICA8YnV0dG9uIEBjbGljaz1cIiRyZWZzLmRsZy5zaG93TW9kYWwoKVwiPlxuICAgIG9wZW4gZGlhbG9nXG4gIDwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<template>
  <dialog ref=dlg>
  <el-popover
    width=200
    trigger="hover"
  >
    <el-button @click="$refs.dlg.close()">Click to close dialog</el-button>
    <template #reference>
      <el-button class="m-2">Hover to activate</el-button>
    </template>
  </el-popover>
</dialog>
  <button @click="$refs.dlg.showModal()">
    open dialog
  </button>
</template>
```
Use HTMLDialogElement.prototype.showModal() in a native dialog element who includes a ElPopper component (includes some components used ElPopper, such as ElSelect)
在一个包含ElPopper（也包括内部使用ElPopper的组件，例如ElSelect）的原生dialog元素上使用showModal()方法

### What is Expected?

ElPopper is active (for example: I can select a item normally in ElSelect)
ElPopper 可以交互（例如：ElSelect可以正常进行选择）

### What is actually happening?

ElPopper is covered by modal dialog element (shown "#top-layer" in DevTools), it cause ElPopper be impossible to use

ElPopper 被模态dialog(DevTools显示为 #top-layer ) 盖住，导致添加到<body>的ElPopper(以及其中的任何内容)无法交互；在[这个例子](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGlhbG9nIHJlZj1kbGc+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgICA8cCB2LWZvcj1cInQgaW4gcFwiPlxuICAgICAge3t0fX1cbiAgICA8L3A+XG4gIDwvZGlhbG9nPlxuICA8YnV0dG9uIEBjbGljaz1cIiRyZWZzLmRsZy5zaG93TW9kYWwoKVwiPm9wZW4gZGlhbG9nPC9idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfVxuXVxuXG5jb25zdCBwID0gcmVmKCdoZWxsbyB3b3JsZCcucmVwZWF0KDEwKSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)中，对话框很高，直接盖住了ElPopper,不仅无法交互，甚至无法看见

### Additional comments

有很多使用ElPopper的组件在原生dialog中都无法使用，例如 ElSelect, ElPagination的sizes选择框，等

**Comment by CarlXu94** [comment]
原生dialog元素是top layer

**Comment by acyza** [comment]
link #11313 这两个issues或许可以一起修复。

**Comment by chenxch** [comment]
top layer > z-index, 所以尽量考虑搭配z-index模式实现的dialog组件一起使用吧。

**Comment by shc0743** [comment]
> 

这种情况应该可以有选项，设置ElPopper插入到dialog而不是body下面，就能解决吧，既然有了原生的dialog元素，理应可以直接使用，而不是继续叠z-index

**Comment by acyza** [comment]
ElPopper里的elTooltip组件有个append-to属性，我试过给他挂到兄弟节点的div里可行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [element-plus/element-plus] [Component] ElPopper组件在原生dialog模态框打开时无法交互 (Issue #11354)




   
这种情况应该可以有选项，设置ElPopper插入到dialog而不是body下面，就能解决吧，既然有了原生的dialog元素，理应可以直接使用，而不是继续叠z-index

**Comment by acyza** [comment]
> 这种情况应该可以有选项，设置ElPopper插入到dialog而不是body下面，就能解决吧，既然有了原生的dialog元素，理应可以直接使用，而不是继续叠z-index

ElPopper里的ElTooltip组件有个append-to属性，我试过给他挂到兄弟节点的div里可行。
![图片](https://user-images.githubusercontent.com/101238421/215394442-1c265f2b-9537-4313-82a8-4fa3feb7a10f.png)

**Comment by shc0743** [comment]
> > 这种情况应该可以有选项，设置ElPopper插入到dialog而不是body下面，就能解决吧，既然有了原生的dialog元素，理应可以直接使用，而不是继续叠z-index
> 
> ElPopper里的ElTooltip组件有个append-to属性，我试过给他挂到兄弟节点的div里可行。 ![图片](https://user-images.githubusercontent.com/101238421/215394442-1c265f2b-9537-4313-82a8-4fa3feb7a10f.png)

但是很多基于ElPopper的组件是没有这个选项的，例如ElSelect（只有一个[已废弃]的popper-append-to-body属性），以及el-pagination：
![image](https://user-images.githubusercontent.com/60457042/215396728-0da234d0-2cad-4c69-a817-17dc927114aa.png)

现在的应用场景是一个dialog里放了个ElTable，然后ElTable用el-pagination分页，所以除非ElPopper更改，根本无解

也许是ElPopper可以放到一个dialog里，然后::backdrop设为透明，这样就不会被前一个#top-layer盖住

**Comment by fyunfei** [comment]
我也遇到了这个问题，需求是局部全屏展示，最后发现就是top-layer导致的，而且组件不支持挂载到指定元素下，现在不知道该怎么办了

**Comment by gh2WHY** [comment]
有更好的解决方案了吗？我也遇到了这个问题

**Comment by shc0743** [comment]
inactive
