### ISSUE TITLE
[Feature Request] Tab pane visible event

### ISSUE THREAD

**Issue by hnviradiya** [element-plus/element-plus#11350]
### Existing Component
Yes

### Component Name
Tabs

### Description
Currently, we require to change things based on visibility of tab pane. 

So we have to add timeout after tab click to make sure tab pane is visible (otherwise it gives 0 height width of content).

It will be good if we can add/trigger 'pane-visible' like event once tab is visible after tab change.

**Comment by btea** [comment]
Maybe you can bind `vue:updated` event on `el-tabs` to achieve your effect. For [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCIgQHZ1ZTp1cGRhdGVkPVwidXBkYXRlXCI+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVXNlclwiIG5hbWU9XCJmaXJzdFwiPlVzZXI8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIkNvbmZpZ1wiIG5hbWU9XCJzZWNvbmRcIj5Db25maWc8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlJvbGVcIiBuYW1lPVwidGhpcmRcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCIgbmFtZT1cImZvdXJ0aFwiPlRhc2s8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgVGFic1BhbmVDb250ZXh0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBhY3RpdmVOYW1lID0gcmVmKCdmaXJzdCcpXG5cbmNvbnN0IHVwZGF0ZSA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ3VwZGF0ZScpXG4gIC8vIEdldCB3aWR0aCBhbmQgaGVpZ2h0IG9mIGB0YWIgcGFuZWAgY29udGVudCBoZXJlXG59XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319).

**Comment by btea** [comment]
I think the example I provided above can solve your problem, so I closed this issue, if you have any questions, please comment below.
