### ISSUE TITLE
[Bug Report] Can't find stylesheet to import: "~element-plus/packages/theme-chalk/src/index.scss"

### ISSUE THREAD

**Issue by smileShirmy** [element-plus/element-plus#1136]
### Element Plus version
1.0.1-beta.16

### OS/Browsers version
macOS 10.15.4 / Chrome 87

### Vue version
3.0.4

### Reproduction Link
https://github.com/smileShirmy/element-plus-issue-demo

### Steps to reproduce
just npm run serve

### What is Expected?
Can find the stylesheet because I want to customize the stylesheet. By the way, I can't find the variables scss in node_modules/element-plus

### What is actually happening?
stylesheet not found

**Comment by zazzaz** [comment]
relate to https://github.com/element-plus/element-plus/commit/d000dd7431012e8a70d5f5b16f8d7f5d4709e616#commitcomment-45449457

**Comment by zazzaz** [comment]
This is a release bug and will be fixed soon.

**Comment by zazzaz** [comment]
fixed in beta-17
