### ISSUE TITLE
[Component] [icon]<i class="el-icon-xxx"></i>不能正常显示

### ISSUE THREAD

**Issue by raochongmou** [element-plus/element-plus#11399]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `Chrome  108.0.5359.125`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues)

### Steps to reproduce

   <template v-for="item in menuList" :key="item.id">
        <el-submenu>
          <template #title>
            <i v-if="item.icon" :class="item.icon" class="icon-class"></i>
            
            <span>{{item.name}}</span>
          </template>
        </el-submenu>
      </template>

### What is Expected?

   图标可以正常显示

### What is actually happening?

   图标不显示 ，除非用el-icon的形式才显示

### Additional comments

   希望大佬们可以解答，本人系小白一个，第一次提问题  有点小紧张、激动

**Comment by btea** [comment]
一个图标是一个单独的组件，需要引入才能显示。

**Comment by raochongmou** [comment]
> 一个图标是一个单独的组件，需要引入才能显示。你提到的通过class使用的方式是 element-ui 的用法，element-plus为了方便图标按需引入，每个图标都是一个组件。

我应该没记错  我记得element-plus原来有几个版本还能用class的方式使用，但是我不记得那个版本了，不知道是不是原来的1.0.2-beta.62版本，这个版本我也安装试了   现在好像也不行   页面能显示i元素就是图标看不到
![image](https://user-images.githubusercontent.com/45557313/216500146-5a1a1f27-fe4a-463d-a155-38968c597843.png)

**Comment by btea** [comment]
可能是早期版本的实现方式，目前已经不支持，建议把 `i` 标签对应的图标都换成对应的组件图标。

**Comment by raochongmou** [comment]
> 可能是早期版本的实现方式，目前已经不支持，建议把 `i` 标签对应的图标都换成对应的组件图标。

好的  非常感谢你能抽出宝贵时间答复我的问题，感谢！

**Comment by btea** [comment]
不用客气。没什么问题的话，那这个issue我就关了。
