### ISSUE TITLE
[Docs] 官方文档 card 无内容

### ISSUE THREAD

**Issue by xiaochen0517** [element-plus/element-plus#11401]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0`
- Build Tool: `Vue CLI`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/card.html)

### Steps to reproduce

https://element-plus.org/zh-CN/component/card.html

### What is Expected?

有内容

### What is actually happening?

无内容

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/216518737-e0be3736-8d0b-4fc2-99b8-6757f654b6bc.png)
未复现哦

**Comment by chenxch** [comment]
定位到了，在 #11197 已修复，待下个版本发布。

**Comment by chenxch** [comment]
已发布修复
