### ISSUE TITLE
[Component] [date-picker] date-picker  type="date" 选择年份或月份时会立刻触发双向绑定的日期数据更新。导致禁用的日期被选中

### ISSUE THREAD

**Issue by xingyixiang** [element-plus/element-plus#11413]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.29`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJzIwMjMtMDItMDQnKVxuY29uc3QgZGF5VGltZSA9IG5ldyBEYXRlKCcyMDIzLTAyLTAzJykuZ2V0VGltZSgpXG5jb25zdCBkaXNhYmxlZERhdGUgPSAodGltZTogRGF0ZSkgPT4ge1xuICByZXR1cm4gdGltZS5nZXRUaW1lKCkgPCBkYXlUaW1lXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHR5cGU9XCJkYXRlXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIlxuICAgIDpkaXNhYmxlZC1kYXRlPVwiZGlzYWJsZWREYXRlXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-date-picker禁用2023/02/03之前的日期，当前的绑定的日期是2024/01/01，点击年份year-table弹框，选择2023年。绑定的时间更新并选中了禁用的日期

### What is Expected?

直到选中了具体的某一天时，绑定日期数据才进行更新

### What is actually happening?

选择年份或月份时，数据被立即更新

**Comment by ckangwen** [comment]
### Reproduction Link
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjdXJyZW50RGF0ZSA9IG5ldyBEYXRlKClcbmNvbnN0IGRlZmF1bHREYXRlID0gbmV3IERhdGUoKVxuZGVmYXVsdERhdGUuc2V0RnVsbFllYXIoY3VycmVudERhdGUuZ2V0RnVsbFllYXIoKSArIDEpXG5kZWZhdWx0RGF0ZS5zZXRNb250aChjdXJyZW50RGF0ZS5nZXRNb250aCgpICsgMSlcbmNvbnN0IHZhbHVlID0gcmVmKGRlZmF1bHREYXRlKVxuY29uc3QgZGlzYWJsZWREYXRlID0gKGRhdGU6IERhdGUpID0+IHtcbiAgcmV0dXJuIGRhdGUuZ2V0VGltZSgpIDwgRGF0ZS5ub3coKSAtIDguNjRlN1xufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICBcbiAgPGVsLWRhdGUtcGlja2VyIHYtbW9kZWw9XCJ2YWx1ZVwiIDpkaXNhYmxlZC1kYXRlPVwiZGlzYWJsZWREYXRlXCI+PC9lbC1kYXRlLXBpY2tlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Additional comments
![el-date-picker-demo.gif](https://s2.loli.net/2023/02/11/W7g6EXbyNVFq98M.gif)

**Comment by b564115824** [comment]
gkd
