### ISSUE TITLE
[Component] [input-number] update:modelValue event cannot be emitted when the value of input-number changes from 1 to 10 and back to 1 in the continuous focus input state

### ISSUE THREAD

**Issue by zh-lx** [element-plus/element-plus#11417]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `Chrome 107.0.5304.110 / MacOS BigSur 11.4 `
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiA6bWluPVwiMVwiIDptYXg9XCIyMDBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgLz5cbiAgPGRpdj5jb3VudDoge3sgbnVtIH19PC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Focus on the InputNumber component.(The following steps need to always be in the focus state)
2. input 0 (the value of InputNumber change from `1` to `10`)
3. delete 0 (the value of InputNumber change from `10` to `1`)

### What is Expected?

the count of the div is `1` after step 3

### What is actually happening?

the count of the div is `10` after step 3

### Additional comments

_(empty)_

![Feb-03-2023 19-19-06](https://user-images.githubusercontent.com/73059627/216592360-505683f7-b7b4-4d86-9614-21949a4e77ca.gif)

**Comment by acyza** [comment]
#11287

**Comment by HeftyKoo** [comment]
fixed by: #12007
