### ISSUE TITLE
[Component] [select, tree-select] EL-Select 不开多选，在IOS系统中获取焦点不会弹出软键盘

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#11415]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome 109.0.5414.120`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgOnJlc2VydmUta2V5d29yZD1cImZhbHNlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在IOS 手机上，点击select

### What is Expected?

弹出软键盘

### What is actually happening?

未弹出软键盘

### Additional comments

和多选属性有关，开启则正常，不开则不正常

**Comment by chenxch** [comment]
https://user-images.githubusercontent.com/23251408/216634399-23e352c2-38d2-428c-bae6-5e9f042ee2a9.mp4

未复现，请提供更多相关信息

**Comment by Edric-Li** [comment]
> 489d805735720197c4dfe959720d741b.mp4 
> 未复现，请提供更多相关信息

需要关闭多选选项

**Comment by chenxch** [comment]
> 需要关闭多选选项

你的demo里面本来就没有开启multiple哦

**Comment by Edric-Li** [comment]
> > 需要关闭多选选项
> 
> 你的demo里面本来就没有开启multiple哦

哦对，你这个复现了呀，我期待能弹开软键盘，你这只是把下拉选项打开了，也没弹出软键盘

**Comment by Edric-Li** [comment]
> > 需要关闭多选选项
> 
> 你的demo里面本来就没有开启multiple哦

我这个是可搜索的，是能输入的，但是它没弹开软键盘，我无法输入

**Comment by chenxch** [comment]
大致定位到readonly属性，可能要考虑优化一下

**Comment by 1061875478** [comment]
> 大致定位到readonly属性，可能要考虑优化一下

请问这个问题大概什么时候可以修复，我也遇到这个问题

**Comment by Edric-Li** [comment]
请问该问题有什么进展么？有修复么？
