### ISSUE TITLE
[i18n] [All] element-plus国际化

### ISSUE THREAD

**Issue by verybeautyTang** [element-plus/element-plus#11416]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.29`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/verybeautyTang/forge-vue-app/tree/main/vite-webpack-ts)

### Steps to reproduce

就是随便引入一个组件，然后它默认的有一个值【有占位符的那种组件哈

### What is Expected?

不操作的情况下显示默认的提示

### What is actually happening?

假设是select组件，默认的占位符会显示el.select.placeholder

### Additional comments

不知道是不是我国际化没做好的原因的导致的？

**Comment by btea** [comment]
你能提供一个最小的复现链接吗？

**Comment by verybeautyTang** [comment]
没有也～ 我也不知道为啥

**Comment by btea** [comment]
只在你本地复现吗？

**Comment by verybeautyTang** [comment]
是的 目前怀疑是因为添加了vi18的原因导致的

**Comment by btea** [comment]
能建一个仓库，保留你项目的配置，然后添加一个有问题的组件吗？
