### ISSUE TITLE
[Bug Report] In the case of on-demand loading, table data switching will cause deep Vue errors

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#1142]
### Element Plus version
1.0.1-beta.14-1.0.1-beta.17

### OS/Browsers version
chrome83

### Vue version
3.0.4

### Reproduction Link
https://github.com/ht-sauce/vuemini-test

### Steps to reproduce
What's wrong with the core is that the array is cleared and then assigned
code：
`data.tableData = []
        setTimeout(() => {
          data.tableData = listdata[e]
        }, 300)`
Clone project address:
Click the button: "form error 2"
Then click the paging function to see the error in the console
![image](https://user-images.githubusercontent.com/34828964/103192605-360e1c00-4914-11eb-8157-81274598ed5a.png)
![image](https://user-images.githubusercontent.com/34828964/103192610-3dcdc080-4914-11eb-9555-3c995fc8dea5.png)
我尝试的几种不会报错的方式，但是都和业务有所出入
1、每页数据少于10条似乎不会发生错误
2、把
`<el-table-column header-align="center" fixed="right" label="操作" width="220">
      <template #default="scope">
        <el-button type="warning">编辑</el-button>
      </template>
    </el-table-column>`
这段代码删除也不会发生错误
3、在el-table的开始去除这个样式class="custom-table"
`<el-table
    cell-class-name="custom-cell"
    size="small"
    class="custom-table"
    :data="tableData"
    border
  >`
也不会发生错误
### What is Expected?
There is no exception in version 1.0.1-beta.10

### What is actually happening?
发生异常

**Comment by martinsura** [comment]
Yup, same problem. 
```
"element-plus": "^1.0.1-beta.14",
```
Works normally.

**Comment by udoless** [comment]
Same problem.

**Comment by justwiner** [comment]
I think this is a duplicate issue, after the PR is merged, see if the issue recurs. 

PR: #1059 
issue: #1051

**Comment by JeremyWuuuuu** [comment]
Can you guys verify the bug is fixed or not? in `beta.19` @ht-sauce @martinsura

**Comment by martinsura** [comment]
Well beta.19 is not listed in npm. But i try install beta. 18:
```
"element-plus": "^1.0.1-beta.18",
```
And it looks like ok. No error, table works as expected.

**Comment by ht-sauce** [comment]
> Can you guys verify the bug is fixed or not? in `beta.19` @ht-sauce @martinsura

"element-plus": "^1.0.1-beta.19"
没有发生错误了
