### ISSUE TITLE
[Component] [cascader] cascader组件回显问题

### ISSUE THREAD

**Issue by wukong-c** [element-plus/element-plus#11435]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome109.0.0.0`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+RGlzcGxheSBhbGwgdGFncyAoZGVmYXVsdCk8L3A+XG4gICAgPGVsLWNhc2NhZGVyICB2LW1vZGVsPVwiYS5iXCIgY29sbGFwc2UtdGFncyA6b3B0aW9ucz1cIm9wdGlvbnNcIiA6cHJvcHM9XCJwcm9wc1wiIGZpbHRlcmFibGUgY2xlYXJhYmxlIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7cmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgcHJvcHMgPSB7IG11bHRpcGxlOiB0cnVlIH1cbmxldCBhID0gcmVmKHtcbiAgYjpbXVxufSlcbnNldFRpbWVvdXQoKCk9PntcbiAgYS52YWx1ZS5iID0gW1sxXSxbMTRdXVxufSwwKVxuXG5cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnQXNpYScsXG4gICAgY2hpbGRyZW46IFtcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDE0LFxuICAgIGxhYmVsOiAnRXVyb3BlJyxcbiAgICBjaGlsZHJlbjogW1xuXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAyMyxcbiAgICBsYWJlbDogJ05vcnRoIEFtZXJpY2EnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICBcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.cascader的options层级只有一层
2.异步为v-model的绑定值赋值

### What is Expected?

cascader的panel回显正常

### What is actually happening?

多选框未被选中，且点击无效

### Additional comments

_(empty)_

**Comment by acyza** [comment]
https://github.com/element-plus/element-plus/blob/dev/packages/components/cascader-panel/src/index.vue#L225
这里拿到的node不是响应式的
https://github.com/element-plus/element-plus/blob/dev/packages/components/cascader-panel/src/index.vue#L265
因此这里的doCheck不会引起checkBox的响应。
https://github.com/element-plus/element-plus/blob/dev/packages/components/cascader-panel/src/node.vue#L24
或许可以用watch来恢复响应式？
https://github.com/acyza/element-plus/commit/46591689b778f9c709657b10656c8743b5a6332d

**Comment by zhaozhiwei123** [comment]
这个问题还没有被解决，我看了最新的版本还是会有这个问题

**Comment by yx199912** [comment]
遇到这个问题的小伙伴可以更新版本试试，我刚更新的2.4.1，解决了这个问题
