### ISSUE TITLE
[Bug Report] Vue3 removed '.native', but I found it in element-plus.

### ISSUE THREAD

**Issue by fanhefeng** [element-plus/element-plus#1143]
Find code like '.native' that has been removed in Vue3.

**Comment by SimonaliaChen** [comment]
The migration of docs have not been compeleted yet, we will correct it soon.

**Comment by zazzaz** [comment]
@fanhefeng Fell free to make a pull request if you'd like to. that would be a great help

**Comment by hashkazi00** [comment]
Has this issue been taken up? If not assign it to me, I am willing to contribute.

**Comment by zazzaz** [comment]
@hashkazi00 that would be nice, assigned.
