### ISSUE TITLE
[Component] [message] Message pop-ups are disabled after changing the global language to Chinese / Message弹窗在全局语言修改成中文之后失效

### ISSUE THREAD

**Issue by RuoLv** [element-plus/element-plus#11430]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.29`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter)

### Steps to reproduce

main.ts changed
```
import ElementPlus from 'element-plus'
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'

app.use(ElementPlus, {
  locale: zhCn,
})
```
After refreshing, click the El Message button on the page

### What is Expected?

正常显示弹窗 / Normal display of pop-up windows

### What is actually happening?

弹窗为网页内容，显示在网页底部 / The pop-up window is the content of the page and is displayed at the bottom of the page

### Additional comments

_(empty)_
ERROR screenshot
![image](https://user-images.githubusercontent.com/40071018/216968932-d12c94c8-3679-41c0-8476-0b3ca84c57a4.png)
right screenshot
![image](https://user-images.githubusercontent.com/40071018/216968993-b82d346d-1c41-4f13-b979-a38005e5bec1.png)

**Comment by tolking** [comment]
same as #11290
