### ISSUE TITLE
[carousel-item] Cannot get the width and height of the subelement in el-carousel-item 不能获取Carousel中子元素的宽和高

### ISSUE THREAD

**Issue by AngleBeats147753** [element-plus/element-plus#11444]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome/107.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgaXRlbSA9IHJlZigpXG5jb25zdCBpdGVtcyA9IHJlZigpXG5jb25zdCBpdGVtSGVpZ2h0ID0gcmVmKClcbmNvbnN0IGl0ZW1zSGVpZ2h0ID0gcmVmKClcblxub25Nb3VudGVkKGFzeW5jICgpID0+IHtcbiAgaWYgKCFpdGVtcy52YWx1ZSkge1xuICAgIHJldHVyblxuICB9XG4gIGxldCBjbGllbnRXaWR0aFxuICBsZXQgY2xpZW50SGVpZ2h0IFxuICBcbiAgICBjbGllbnRXaWR0aCA9IGl0ZW0udmFsdWUhLmNsaWVudFdpZHRoXG4gIGNsaWVudEhlaWdodCA9IGl0ZW0udmFsdWUhLmNsaWVudEhlaWdodFxuICBjb25zb2xlLmxvZyhgXG4gICAgZWwtY2Fyb3VzZWwtaXRlbeWkluWFg+e0oOWuveW6pu+8miR7Y2xpZW50V2lkdGh9XFxuXG4gICAgZWwtY2Fyb3VzZWwtaXRlbeWkluWFg+e0oOmrmOW6pu+8miR7Y2xpZW50SGVpZ2h0fVxcblxuICAgIGApO1xuICBpdGVtSGVpZ2h0LnZhbHVlID0gY2xpZW50SGVpZ2h0XG4gIFxuICBjbGllbnRXaWR0aCA9IGl0ZW1zLnZhbHVlWzBdIS5jbGllbnRXaWR0aFxuICBjbGllbnRIZWlnaHQgPSBpdGVtcy52YWx1ZVswXSEuY2xpZW50SGVpZ2h0XG4gIGNvbnNvbGUubG9nKGBcbiAgICBlbC1jYXJvdXNlbC1pdGVt5YaF5YWD57Sg5a695bqm77yaJHtjbGllbnRXaWR0aH1cXG5cbiAgICBlbC1jYXJvdXNlbC1pdGVt5YaF5YWD57Sg6auY5bqm77yaJHtjbGllbnRIZWlnaHR9XFxuXG4gICAgYCk7XG4gIGl0ZW1zSGVpZ2h0LnZhbHVlID0gY2xpZW50SGVpZ2h0XG59KVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDMgdGV4dD1cIjJ4bFwiIGp1c3RpZnk9XCJjZW50ZXJcIiByZWY9XCJpdGVtXCI+MTIzMjE8L2gzPlxuICA8ZWwtY2Fyb3VzZWwgOmludGVydmFsPVwiNDAwMFwiIHR5cGU9XCJjYXJkXCIgaGVpZ2h0PVwiMjAwcHhcIiA+XG4gICAgPGVsLWNhcm91c2VsLWl0ZW0gdi1mb3I9XCJpdGVtIGluIDZcIiA6a2V5PVwiaXRlbVwiID5cbiAgICAgIDxoMyB0ZXh0PVwiMnhsXCIganVzdGlmeT1cImNlbnRlclwiIHJlZj1cIml0ZW1zXCI+MTIzMjE8L2gzPlxuICAgIDwvZWwtY2Fyb3VzZWwtaXRlbT5cbiAgPC9lbC1jYXJvdXNlbD5cbiAgPGRpdj5cbiAgICBlbC1jYXJvdXNlbC1pdGVt5aSW5YWD57Sg6auY5bqm77yae3tpdGVtSGVpZ2h0fX0gPGJyPlxuICAgIGVsLWNhcm91c2VsLWl0ZW3lhoXlhYPntKDpq5jluqbvvJp7e2l0ZW1zSGVpZ2h0fX1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNhcm91c2VsX19pdGVtIGgzIHtcbiAgY29sb3I6ICM0NzU2Njk7XG4gIG9wYWNpdHk6IDAuNzU7XG4gIGxpbmUtaGVpZ2h0OiAyMDBweDtcbiAgbWFyZ2luOiAwO1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG59XG5cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4pIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzk5YTliZjtcbn1cblxuLmVsLWNhcm91c2VsX19pdGVtOm50aC1jaGlsZCgybiArIDEpIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2QzZGNlNjtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Step 1: Use ref to reference any subelement in el-carousel-item.
Step 2: Obtain the clientWidth or clientHeight of the reference object in onMount
Step 3: Output clientWidth or clientHeight

步骤一：使用ref引用el-carousel-item中任意的子元素。
步骤二：在onMount中获取引用对象的clientWidth或者clientHeight
步骤三：输出clientWidth或者clientHeight

### What is Expected?

Gets the actual width and height of the referenced element

获取到引用元素经过渲染后的宽和高

### What is actually happening?

The width and height of the reference element are always 0

引用元素的宽和高始终为0

### Additional comments

_(empty)_

**Comment by xianyongwen** [comment]
你可以在nextTick里获取到正确的值
nextTick(() => {
    clientWidth = items.value[0]!.clientWidth
    clientHeight = items.value[0]!.clientHeight
    console.log(`
      el-carousel-item内元素宽度：${clientWidth}\n
      el-carousel-item内元素高度：${clientHeight}\n
      `);
    itemsHeight.value = clientHeight
  })
