### ISSUE TITLE
[Component] [select-v2] value是对象时 数据内无label字段选中后输入框内无内容

### ISSUE THREAD

**Issue by newz-max** [element-plus/element-plus#11441]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgdmFsdWUta2V5PVwidmFsdWUubmFtZVwiXG4gICAgICAgICAgICAgICAgPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cIntpdGVtfVwiPlxuICAgICAge3tpdGVtLnRlc3R9fVxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtc2VsZWN0LXYyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoKVxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiB7XG4gICAgbmFtZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgICB0ZXN0OiBgdGVzdCAke2lkeCAlIDN9YCxcbiAgfSxcbiAgdGVzdDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmV4YW1wbGUtc2hvd2Nhc2UgLmVsLXNlbGVjdC12MiB7XG4gIG1hcmdpbi1yaWdodDogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgdmFsdWUta2V5PVwidmFsdWUubmFtZVwiXG4gICAgICAgICAgICAgICAgPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cIntpdGVtfVwiPlxuICAgICAge3tpdGVtLnRlc3R9fVxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtc2VsZWN0LXYyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoKVxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiB7XG4gICAgbmFtZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgICB0ZXN0OiBgdGVzdCAke2lkeCAlIDN9YCxcbiAgfSxcbiAgdGVzdDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmV4YW1wbGUtc2hvd2Nhc2UgLmVsLXNlbGVjdC12MiB7XG4gIG1hcmdpbi1yaWdodDogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

### What is Expected?

可以自定义 label 的字段

### What is actually happening?

无法自定义 label 虽然有 自定义option选项的插槽 但是选中后输入框上无内容

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Fixed in #11441, wait for version 2.3
