### ISSUE TITLE
[Component] [table] table的单元格cell样式，在2.2.29版本后，如果不提供size属性，会导致每一格的cell样式丢失padding属性

### ISSUE THREAD

**Issue by kiddkyd1412** [element-plus/element-plus#11468]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.6`
- Element Plus Version: `2.2.29`
- Browser / OS: `edge109.0.1518.78/ win11`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](http://element-plus.org/zh-CN/component/table.html#%E6%A0%91%E5%BD%A2%E6%95%B0%E6%8D%AE%E4%B8%8E%E6%87%92%E5%8A%A0%E8%BD%BD)

### Steps to reproduce

直接看现在的官网table组件的效果就知道。

### What is Expected?

table不需要写size属性，默认触发size=default效果,从而实现每一格都有左右padding效果。

### What is actually happening?

如果不写size=default，则表格每一格的cell样式丢失padding效果

### Additional comments

_(empty)_

**Comment by Shenenkaka** [comment]
the same, make me confuse, thought vite packaging lost style :(

**Comment by longshihui** [comment]
I find the same problem #11434  and it is fixed in commit 3d747a0e56998ab89309e2a0601d5aa7590c2c22

**Comment by chenxch** [comment]
fixed #11456
