### ISSUE TITLE
[Build] [All] monorepo的一些包例如 @element-plus/hooks @element-plus/tokens 包长期不更新

### ISSUE THREAD

**Issue by xxholly32** [element-plus/element-plus#11473]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.29`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/dev/packages/hooks/package.json)

### Steps to reproduce

`npm view @element-plus/hooks version` 和 `npm view @element-plus/tokens version` 均为0.0.5

### What is Expected?

期望通过element-plus内置的一些包来完成自研组件开发，希望引用element-plus的最佳实践

### What is actually happening?

引入上述的包和现有的element-plus代码无法实现融合

### Additional comments

愿意贡献

**Comment by xxholly32** [comment]
又看了下，除了locale和utils包其他都放到了element-plus主包中，个人感觉不太解耦；如果不拆的话 另几个包和utils一样改成 `private: true` 防止开发误解

**Comment by sxzz** [comment]
track #5706 instead
