### ISSUE TITLE
[Performance] [date-picker] ElDatePicker 的 eltooltipcontent 在Dialog 中渲染速度远远慢于普通容器中

### ISSUE THREAD

**Issue by LeonChen1024** [element-plus/element-plus#11478]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.25`
- Browser / OS: `Chrome Version 109.0.5414.119 (Official Build) (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1kaWFsb2cgOm1vZGVsLXZhbHVlPVwidmlzaWJsZVwiICBzdHlsZT1cInRleHQtYWxpZ246IGxlZnQ7XCI+XG4gICAgICA8ZWwtZGF0ZS1waWNrZXIgdHlwZT1cImRhdGVcIiAvPlxuICA8L2VsLWRpYWxvZz5cblx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlPXRydWVcIj7miZPlvIDlvLnnqpc8L2VsLWJ1dHRvbj5cbiAgPGVsLWRhdGUtcGlja2VyIHR5cGU9XCJkYXRlXCIgLz5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

在基础容器中使用 el-date-picker , 并在一个dialog 中同样放置一个 el-date-picker, dialog 中渲染时间远远大于基础容器中

### What is Expected?

渲染时间应该相近

### What is actually happening?

渲染时间相差过多

### Additional comments

_(empty)_

**Comment by LeonChen1024** [comment]
多次测试后发现打开开发模式差异很多, 生产模式下差异较小

**Comment by chenxch** [comment]
能否提供更多信息，例如耗时打印（利用focus和visible-change 打印时间差

**Comment by chenxch** [comment]
注意一点，开发模式下打开控制台 vuedevtool是会影响速度
