### ISSUE TITLE
Can the big picture component be made into a component independently

### ISSUE THREAD

**Issue by zehuichan** [element-plus/element-plus#1147]
如题

**Comment by zazzaz** [comment]
Any more detail, please? What is a big picture component?

**Comment by zehuichan** [comment]
`packages/image/src/image-viewer.vue`

**Comment by JeremyWuuuuu** [comment]
Well I think it could.

**Comment by zehuichan** [comment]
@JeremyWuuuuu thx

**Comment by JeremyWuuuuu** [comment]
@zehuichan upgrade to beta.21, use it independently with `<el-image-viewer />`
