### ISSUE TITLE
[feature request] hopes to add virtual scrolling to El table to cope with a large amount of recorded data.

### ISSUE THREAD

**Issue by zychome** [element-plus/element-plus#1148]
### Existing Component
是

### Component Name
el-table

### Description
希望为el-table增加虚拟滚动，来应对大量的记录数据。

**Comment by justwiner** [comment]
This is a good idea! but in the implemented components, there is no `virtual scroll component`, we will try to optimize the `table component`.

**Comment by JeremyWuuuuu** [comment]
We are making progress step by step, for now even though I have made a virtual scroll component, but for integration it would take time. So it is really hard to say when this is going to be done. Also could you please move this issue to [ElementPlus Discussions](/element-plus/element-plus/discussions) to get tracked?
