### ISSUE TITLE
[Feature Request] Anchor  Component

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1149]
### Existing Component
No

### Component Name
2.7.13

### Description
win10

Currently, there is no component. Shall we consider adding new components

**Comment by zazzaz** [comment]
It nice to have this component 😬

**Comment by JeremyWuuuuu** [comment]
Would you mind be a little bit specific? And also please open a discussion under [ElementPlus Discussion](/element-plus/element-plus/discussions) in order for us to track.

**Comment by Eating-Eating** [comment]
I'm interested in this component.
If none's working on it,may I have a try? @zazzaz @JeremyWuuuuu @jahnli

**Comment by sxzz** [comment]
Sorry, we haven't responded to you for so long.
Feel free to open a PR please if you like.

**Comment by kooriookami** [comment]
#15670
