### ISSUE TITLE
[Docs] vitepress中配置了base，静态资源文件夹public和en-US文件夹打包后的文件没有加上base的url前缀

### ISSUE THREAD

**Issue by Thorne97** [element-plus/element-plus#11497]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

在docs/.vitepress/config.mts的UserConfig内增加了base: '/test/'，调用命令pnpm run build进行打包。

### What is Expected?

所有引用本地的资源路径都能以/test/作为前缀

### What is actually happening?

只有被webpack打包处理的资源有加上/test/前缀，位于docs/en-US和docs/public下的md文件和静态资源在打包后没有加上/test/前缀。
以docs/public/images/element-plus-logo-small.svg为例，期望打包后的引用路径为/test/images/element-plus-logo-small.svg，实际生成的引用路径为/images/element-plus-logo-small.svg

### Additional comments

_(empty)_

**Comment by Denghongjian233** [comment]
看不懂

**Comment by btea** [comment]
This seems to be a problem with vitepress.

**Comment by chenxch** [comment]
forward [vitepress](https://github.com/vuejs/vitepress/issues)
