### ISSUE TITLE
[Style] [input] 复合型输入框在 EDGE 浏览器中样式错误

### ISSUE THREAD

**Issue by name-xiaotao** [element-plus/element-plus#11533]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `Microsoft Edge 110.0.1587.41 / Windows11 22H2`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)

### Steps to reproduce

使用EDGE浏览器打开上述链接（官网示例），可发现复合型输入框的前缀、后缀、下拉框等等样式都有问题
在Chrome和Firefox中无该问题

### What is Expected?

正确的展示复合型输入框的样式

### What is actually happening?

样式出现错误

### Additional comments

尝试过升级浏览器版本、升级elementplus版本、vite版本等等，都没有解决该问题

![image](https://user-images.githubusercontent.com/30957584/218404052-ef6196ce-51ce-44f2-8811-08e1da028daf.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/218426633-9df7114a-db36-4ae6-b0d3-2dd5dea18d24.png)
未复现哦

**Comment by chenxch** [comment]
[link](https://element-plus.org/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)  访问一下这个链接看看

**Comment by name-xiaotao** [comment]
> 链接 访问一下这个[链接](https://element-plus.org/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)看看

通过你的链接访问之后，我自己的项目、以及官方文档均未出现问题了。

**Comment by name-xiaotao** [comment]
之前尝试过清理浏览器缓存，等操作，均无效果，现在其他几个样式问题也一并好了，其他几个样式问题如下，现在均未出现，感谢。
![`IP`F8CHM8W(2__YNY5 1](https://user-images.githubusercontent.com/30957584/218438672-9059f5af-ad69-4b8f-9c2c-3e152b6a2f31.jpg)
![B7AZ(ZXLAXF2@}3U)U(ADPM](https://user-images.githubusercontent.com/30957584/218438687-85e4458d-8962-469a-929f-f7982ddb36b7.jpg)
![@PHGEV28Y}(@0~K17 _X~RH](https://user-images.githubusercontent.com/30957584/218438706-108bf61f-024a-4e78-896b-80aff6a3fa3b.jpg)
