### ISSUE TITLE
[Component] [dialog] The watch inside the component cannot accurately capture every change of the v-model:props

### ISSUE THREAD

**Issue by Autumn-one** [element-plus/element-plus#11532]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `  Binaries:     Node: 18.13.0 - C:\Program Files\nodejs\node.EXE     npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: Spartan (44.22621.1194.0), Chromium (110.0.1587.41)     Internet Explorer: 11.0.22621.1   npmPackages:     vue: ^3.2.45 => 3.2.45`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-cr1nh2?file=src/App.vue)

### Steps to reproduce

打开浏览器控制台，点击触发按钮

### What is Expected?

输出 aaa 和 bbb

### What is actually happening?

输出了两次 aaa

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你可以写个带有插槽的组件，把你的内容套到插槽中试一下。

**Comment by Autumn-one** [comment]
> 你可以写个带有插槽的组件，把你的内容套到插槽中试一下。

我试了一下，这个确实根插槽的更新机制有关，与具体的dialog组件无关
