### ISSUE TITLE
[Feature Request] Can I specify a popper pop-up layer to render under an element（Not body element）?

### ISSUE THREAD

**Issue by sufengyong** [element-plus/element-plus#1156]
### Existing Component
Yes

### Component Name
Popper

### Description
Since I'm using a QianKun framework to build micro app, can I specify a popper pop-up layer to render under an element（Not body element）?

**Comment by zazzaz** [comment]
you can check the `appendToBody` prop

**Comment by sufengyong** [comment]
> you can check the `appendToBody` prop

But I don't want to mount it under the body element, I want to mount it to the specified element. My page structure looks like this, and I want the popper of my child application to mount to the specified element

<html>
    <body>
       main application

      <div>
             micro app which use ElementPlus
     </div>

  </body>
</html>

**Comment by JeremyWuuuuu** [comment]
Well, it can in theory, we just didn't make that as API.
In alternative, you can do something like, teleport `popper` element outside the current dom. then set `append-to-body` to false.

**Comment by Wise-Gorilla** [comment]
I think that should be the default behavior that the dropdown should be inside the select wrapper
