### ISSUE TITLE
Dialog close event is not working

### ISSUE THREAD

**Issue by khristinalukanets** [element-plus/element-plus#1157]
### Element Plus version
1.0.1-beta.17

### OS/Browsers version
chrome

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/khristinalukanets/pen/vYXdGgQ

### Steps to reproduce
1. create el-dialog with model-value attribute (not v-model)
2. open dialog
3. close the dialog
-  by press escape 
- or by clicking the mask 
- or by clicking on the close icon 
4. dialog will be closed but the "close" event was not triggered 
4. Could not open againe

please take look at the example

### What is Expected?
"close" event triggers when the Dialog closes

### What is actually happening?
"close" event is not triggered if you use model-value attribute

**Comment by wxs77577** [comment]
it works after I changed `:value` to `v-model`:
`v-model="centerDialogVisible"`

**Comment by JeremyWuuuuu** [comment]
I think that's one of our bug, glad that you have found it. So I am going to fix it in the next release, and you may stay the way how you wrote the code.

**Comment by JeremyWuuuuu** [comment]
BTW, if you wish to wait after the animation finished, you should bind listener to `@closed` event, instead of `@close` event, also, with `v-model` binding, it not suggested that you modify `modelValue` manually (but people have their special needs I suppose)

**Comment by Chris-Kin** [comment]
add `@update:model-value="centerDialogVisible = false"` to your `el-dialog`?

**Comment by Chris-Kin** [comment]
> add `@update:model-value="centerDialogVisible = false"` to your `el-dialog`?

It's better that `CLOSE_EVENT` emited in `doClose` method.
