### ISSUE TITLE
[Component] [table, table-column] table组件使用v-if控制列显隐, 表格崩溃(多级表头)

### ISSUE THREAD

**Issue by ly-chn** [element-plus/element-plus#11576]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.30`
- Browser / OS: `win10 firefox 109 / chrome 110`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJzaG93LmRhdGVcIj5zaG93IGRhdGU8L2VsLWNoZWNrYm94PlxuICAgIDxlbC1jaGVja2JveCB2LW1vZGVsPVwic2hvdy5uYW1lXCI+c2hvdyBuYW1lPC9lbC1jaGVja2JveD5cbiAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cInNob3cuaW5mb1wiPnNob3cgaW5mbzwvZWwtY2hlY2tib3g+XG4gICAgPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJzaG93LnN0YXRlXCI+c2hvdyBzdGF0ZTwvZWwtY2hlY2tib3g+XG4gICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIiNcIiB0eXBlPVwiaW5kZXhcIi8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHYtaWY9XCJzaG93LmRhdGVcIiBwcm9wPVwiZGF0ZVwiIHdpZHRoPVwiMTUwXCI+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgdi1pZj1cInNob3cubmFtZVwiIHByb3A9XCJuYW1lXCIgd2lkdGg9XCIxMjBcIi8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEZWxpdmVyeSBJbmZvXCIgdi1pZj1cInNob3cuaW5mb1wiPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTdGF0ZVwiIHYtaWY9XCJzaG93LnN0YXRlXCIgcHJvcD1cInN0YXRlXCIgd2lkdGg9XCIxMjBcIi8+XG4gICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG93ID0gcmVmKHtcbiAgZGF0ZTogdHJ1ZSxcbiAgbmFtZTogdHJ1ZSxcbiAgaW5mbzogdHJ1ZSxcbiAgc3RhdGU6IHRydWVcbn0pXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2J1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNidcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJzaG93LmRhdGVcIj5zaG93IGRhdGU8L2VsLWNoZWNrYm94PlxuICAgIDxlbC1jaGVja2JveCB2LW1vZGVsPVwic2hvdy5uYW1lXCI+c2hvdyBuYW1lPC9lbC1jaGVja2JveD5cbiAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cInNob3cuaW5mb1wiPnNob3cgaW5mbzwvZWwtY2hlY2tib3g+XG4gICAgPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJzaG93LnN0YXRlXCI+c2hvdyBzdGF0ZTwvZWwtY2hlY2tib3g+XG4gICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIiNcIiB0eXBlPVwiaW5kZXhcIi8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHYtaWY9XCJzaG93LmRhdGVcIiBwcm9wPVwiZGF0ZVwiIHdpZHRoPVwiMTUwXCI+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgdi1pZj1cInNob3cubmFtZVwiIHByb3A9XCJuYW1lXCIgd2lkdGg9XCIxMjBcIi8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEZWxpdmVyeSBJbmZvXCIgdi1pZj1cInNob3cuaW5mb1wiPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTdGF0ZVwiIHYtaWY9XCJzaG93LnN0YXRlXCIgcHJvcD1cInN0YXRlXCIgd2lkdGg9XCIxMjBcIi8+XG4gICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG93ID0gcmVmKHtcbiAgZGF0ZTogdHJ1ZSxcbiAgbmFtZTogdHJ1ZSxcbiAgaW5mbzogdHJ1ZSxcbiAgc3RhdGU6IHRydWVcbn0pXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2J1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNidcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

上方链接, 依次点击复选框`show state`-> `show info` -> `show info` -> `show state`

即先从左到右, 再从右到左, 全部点了之后会出现布局崩溃现象

布局崩溃后点击show name, 控制台将会出现报错信息(点击其他的复选框也会)

### What is Expected?

表格正常布局

### What is actually happening?

表格布局崩溃, 控制台有报错

### Additional comments

_(empty)_

**Comment by MrWeilian** [comment]
可能跟 [#9568](https://github.com/element-plus/element-plus/issues/9568) 是同一个问题

**Comment by ly-chn** [comment]
确实如此, 已解决
