### ISSUE TITLE
[Docs] [All] 国内element-plus.gitee.io网站经常加载错误

### ISSUE THREAD

**Issue by zhaozhenghao** [element-plus/element-plus#11587]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/)

### Steps to reproduce

随便点击某个组件，或者搜索都会很卡，甚至出现503问题
503 Service Temporarily Unavailable

### What is Expected?

国内静态网站修复一下，不再报错，页面加载速度提升下

### What is actually happening?

503 Service Temporarily Unavailable

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/32922591/218948040-c663630a-064a-4190-859b-f0b4f3071128.png)

**Comment by guodaStatham999** [comment]
+100000次, 每个页面都会卡  element2从来没这事

**Comment by East333** [comment]
+1 文档特别难用，几乎处于无法正常使用的情况

**Comment by tolking** [comment]
Recommended [element-plus.org](https://element-plus.org/)

**Comment by guodaStatham999** [comment]
大家直接访问这个路径,不卡的.  
https://element-plus.org/zh-CN/component/dropdown.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

**Comment by SweetyHH** [comment]
+10086

**Comment by chenxch** [comment]
国内站点已恢复。
