### ISSUE TITLE
[Component] [select-v2] The 'wheel' event needs to be marked as passive in the virtualized selector component

### ISSUE THREAD

**Issue by tsnoel** [element-plus/element-plus#11584]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `Chrome 109.0.5414.119`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/select-v2.html)

### Steps to reproduce

1) Open the attached documentation link (https://element-plus.org/en-US/component/select-v2.html) using a recent version of Chrome (arm64). 
2) Launch the developer console and refresh the page. 
3) Observe that there are over a dozen warnings indicating that the components on this page need passive tags.

### What is Expected?

No warnings should appear.

### What is actually happening?

At the time of writing, 17 warnings appear in the Chrome (arm64) developer console indicating that events related to el-select-v2 need the passive attribute on their 'wheel' events.

### Additional comments

This is related to another open issue in the project repository (https://github.com/element-plus/element-plus/issues/8123). 

That issue, however, doesn't mention el-select-v2 and doesn't mention that the bug is observable on the element-plus documentation site itself. 

<img width="1548" alt="Screen Shot 2023-02-14 at 10 46 43" src="https://user-images.githubusercontent.com/75534854/218787508-08c5add2-435b-4820-91e9-46cf28688e54.png">

**Comment by lzw-leaf** [comment]
I also encountered this problem

**Comment by YUN-RU-TSENG** [comment]
same problem

**Comment by wanting12345** [comment]
+1

**Comment by peng-xiao-shuai** [comment]
+1

**Comment by kooriookami** [comment]
It looks fixed now.
