### ISSUE TITLE
[Style] [image] if el-image has no width, then the error info will not display

### ISSUE THREAD

**Issue by wiidede** [element-plus/element-plus#11585]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `Chrome 104/ Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8c3Bhbj7mjIflrprlpKflsI88L3NwYW4+XG5cdDxlbC1pbWFnZSBzdHlsZT1cIndpZHRoOiAxMDBweDsgaGVpZ2h0OiAxMDBweFwiIDpzcmM9XCJ1cmxcIiAvPlxuXHQ8c3Bhbj7mjIflrprpq5jluqbvvIzkvYbmsqHmnInlrr3luqY8L3NwYW4+XG5cdDxlbC1pbWFnZSBzdHlsZT1cImhlaWdodDogMTAwcHhcIiA6c3JjPVwidXJsXCIgLz5cbiAgPGJyLz5cblx0PHNwYW4+5oyH5a6a5aSn5bCPPC9zcGFuPlxuXHQ8ZWwtaW1hZ2Ugc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIiBzcmM9XCJ1cmxcIiAvPlxuXHQ8c3Bhbj7mjIflrprpq5jluqbvvIzkvYbmsqHmnInlrr3luqY8L3NwYW4+XG5cdDxlbC1pbWFnZSBzdHlsZT1cImhlaWdodDogMTAwcHhcIiBzcmM9XCJ1cmxcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHVybCA9XG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZS81ZC80YTczMWE5MDU5NGE0YWY1NDRjMGMyNTk0MTE3MWpwZWcuanBlZydcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuXG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

do not give el-image width

### What is Expected?

has error/placeholder info

### What is actually happening?

no error info

### Additional comments

https://github.com/element-plus/element-plus/pull/8109
这个pr，改了样式，但我觉得修复那个bug不需要改样式，保证wrapper和img不会同时出现就好了吧。
现在wrapper是绝对定位，显示placeholder/error的时候，就wrapper一个绝对定位元素，如果el-image没有指定宽度，那么宽度就是0了。
虽然原来placeholder/error也是绝对定位，可能也不会有宽度……😂

**Comment by tolking** [comment]
确实存在问题，错误信息没有撑开宽度。或许 error 不应该放在 wrapper 里面？

img 是用来加载图片的，当加载时 img 和 wrapper 都需要存在。

**Comment by yyq-bit** [comment]
> 确实存在问题，错误信息没有撑开宽度。或许 error 不应该放在 wrapper 里面？
> 
> img 是用来加载图片的，当加载时 img 和 wrapper 都需要存在。

或许去掉 wrapper 的绝对定位呢，本身 wrapper 的宽高是父元素 `el-image` 的100%，为什么设置absolute呀？

![image](https://user-images.githubusercontent.com/74828263/218963859-ad65af78-7478-418f-8740-ca5207a8130b.png)

**Comment by acyza** [comment]
> > 确实存在问题，错误信息没有撑开宽度。或许 error 不应该放在 wrapper 里面？
> > img 是用来加载图片的，当加载时 img 和 wrapper 都需要存在。
> 
> 或许去掉 wrapper 的绝对定位呢，本身 wrapper 的宽高是父元素 `el-image` 的100%，为什么设置absolute呀？
> 
> ![image](https://user-images.githubusercontent.com/74828263/218963859-ad65af78-7478-418f-8740-ca5207a8130b.png)

可能是考虑img加载时img会影响placeholder的定位，placeholder也是放在这个wrapper里的。

**Comment by acyza** [comment]
或许img加载时给个`visibility: collapse;`?

**Comment by acyza** [comment]
或者宽高设为0？

**Comment by tolking** [comment]
> 或者宽高设为0？

会影响懒加载

**Comment by acyza** [comment]
> > 或者宽高设为0？
> 
> 会影响懒加载


wrapper存在时给img加`position: absolute;`和`opacity: 0;`，wrapper移除后再去掉？

**Comment by acyza** [comment]
好像也会影响懒加载，因为这时候的img尺寸又不对了

**Comment by wiidede** [comment]
我也感觉error不放wrapper里比较好？
img只有在`imageSrc !== undefined && !hasLoadError`才会存在，也就是说error时，只有wrapper一个绝对定位元素。wrapper既然是绝对定位的，那意思就是要和img一起出现，覆盖在img上。
error时没有img，所以error不应该是绝对定位的

**Comment by acyza** [comment]
这样子error算是解决了，但我总感觉pleaceholder的大小也有问题。

**Comment by wiidede** [comment]
有img标签的时候，会把el-image撑开吧，这时候wrapper、pleaceholder大小有`width: 100%;height: 100%;`，大小应该是正确的？
