### ISSUE TITLE
[Docs] 从crowdin引入zh-CN进行打包后报错

### ISSUE THREAD

**Issue by Thorne97** [element-plus/element-plus#11611]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

到crowdin上下载了zh-CN版本，将压缩包内的/.vitepress/crowdin/zh-CN复制到了代码中的/docs/.vitepress/crowdin/zh-CN，压缩包内的/zh-CN复制到了docs路径下。执行pnpm run docs:build进行打包后有了报错（在未引入zh-CN之前有跑过该打包命令，一切正常）

### What is Expected?

生成打包文件

### What is actually happening?

build error:
TypeError: Cannot read properties of undefined (reading 'docs')

at transformComponentMarkdown (D:\java code\element、vue官方文档\element-plus产品文档\element-plus\docs\vite.config.ts:129:40)
at Object.transform (D:\java code\element、vue官方文档\element-plus产品文档\element-plus\docs\vite.config.ts:90:16)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async transform (D:\java code\element、vue官方文档\element-plus产品文档\element-plus\node_modules\.pnpm\rollup@2.75.7\node_modules\rollup\dist\shared\rollup.js:22085:16)
at async ModuleLoader.addModuleSource (D:\java code\element、vue官方文档\element-plus产品文档\element-plus\node_modules\.pnpm\rollup@2.75.7\node_modules\rollup\dist\shared\rollup.js:22311:30) {
code: 'PLUGIN_ERROR',
plugin: 'element-plus-md-transform',
hook: 'transform',
id: 'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/zh-CN/component/affix.md',
watchFiles: [
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/node_modules/.pnpm/vitepress@0.22.4/node_modules/vitepress/dist/client/app/index.js',
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/en-US/component/affix.md',
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/en-US/component/alert.md',
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/en-US/component/autocomplete.md',
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/en-US/component/avatar.md',
'D:/java code/element、vue官方文档/element-plus产品文档/element-plus/docs/en-US/component/backtop.md',
... 548 more items

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你是想在本地部署一份文档么？

**Comment by Thorne97** [comment]
> 你是想在本地部署一份文档么？

是的

**Comment by Thorne97** [comment]
> 你是想在本地部署一份文档么？

官方提供的gh-pages里的文档用的是绝对路径，公司内网很多项目都部署在同一个服务器上，因此只能自己打包部署中文文档。

**Comment by chenxch** [comment]
看看能不能让运维给个单独的端口

**Comment by kaidiya** [comment]
没看懂，vitepress打包失败，跟端口有什么关系？

**Comment by chenxch** [comment]
> 没看懂，vitepress打包失败，跟端口有什么关系？

这句话是回复同一台服务器如何解决部署

**Comment by kaidiya** [comment]
现在是docs:build失败，他那个报错TypeError: Cannot read properties of undefined (reading 'docs')是咋解决的，我也遇到了，能请教一下吗

**Comment by chenxch** [comment]
[pr-docs-build](https://github.com/element-plus/element-plus/blob/dev/.github/workflows/pr-docs-build.yml) 参考一下这个步骤试试

**Comment by kaidiya** [comment]
感谢大佬，解决了，多运行了两个命令解决了
1、运行pnpm docs:gen-locale
2、pnpm build
3、pnpm docs:build

再次感谢

**Comment by qnone-x** [comment]
> 

请问你是下载的md吗 还是html

**Comment by BrysonLin** [comment]
> 

我也遇到同样的问题了，下载的是md文件

**Comment by Thorne97** [comment]
> 我也遇到同样的问题了，下载的是md文件

我用kaidiya的那三个命令解决了
