### ISSUE TITLE
[bug report] paging current change triggered twice emit

### ISSUE THREAD

**Issue by Gempty-lin** [element-plus/element-plus#1161]
### Element Plus version
1.0.1-beta.17

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
 <el-pagination background layout="prev, pager, next" :current-page="nowPage" @current-change="handleCurrentChange" :total="total" :page-size="15">
</el-pagination>

handleCurrentChange 触发了两次

### What is Expected?
只触发1次

### What is actually happening?
触发2次

**Comment by BeADre** [comment]
Can you provide a reproduction demo？

**Comment by Ryan2128** [comment]
Can you provide a reproduction demo ?

In my test, it work well.

```
<template>
  <el-pagination
    background
    layout="prev, pager, next"
    :current-page="nowPage"
    :total="total"
    :page-size="15"
    @current-change="handleCurrentChange"
  />
</template>

<script>
import {  defineComponent, ref } from 'vue'
export default defineComponent({
  name: 'Index',
  setup() {


    const nowPage = ref(1)
    const total = ref(300)
    const handleCurrentChange = (val) => {
      console.log(val)
    }
    return {
      nowPage,
      total,
      handleCurrentChange,
    }
  },
})
```

If there is still no reply, I will close the issue.

**Comment by Ryan2128** [comment]
There is no reply for too long, I will close the issue, if there is any problem, please open it again.

**Comment by mrqinbit** [comment]
确实出发了两次，求解？？？

**Comment by Gempty-lin** [comment]
<template>
    <div class="laytable__body">
        <el-row class="search__content" v-if="$slots.search">
            <slot name="search">
            </slot>
            <el-button @click="$emit('reset')">重置</el-button>
            <el-button type="primary" @click="$emit('refresh',1)">查询</el-button>
        </el-row>
        <el-row class="table__content">
            <el-row class="title">
                <el-col :span="12" class="font">{{title}}</el-col>
                <el-col :span="12" class="btn__content">
                    <slot name="btn"></slot>
                    <i class="el-icon-refresh-right" @click="$emit('refresh',nowPage)"></i>
                </el-col>
            </el-row>
            <el-row class="table">
                <slot name="table"></slot>

            </el-row>
            <el-row class="table__page">
                <div class="paging__content">
                    <el-pagination background layout="prev, pager, next" :current-page="nowPage" @current-change.sync="handleCurrentChange" :total="total" :page-size="15">
                    </el-pagination>
                </div>
            </el-row>
        </el-row>

    </div>
</template>
<script>
    import { reactive, toRefs } from 'vue';
    export default {
        name: 'tableTemp',
        props: {
            title: String,
            total: {
                type: Number,
                default: 15
            },
        },
        setup(props, { emit }) {
            let state = reactive({
                nowPage: 1
            })
            const handleCurrentChange = (e) => {
                console.log(e)
                // state.nowPage = e;
                // emit('cur-page',e);
            }
            return {
                handleCurrentChange,
                ...toRefs(state)
            }
        }
    }
</script>

**Comment by Ryan2128** [comment]
> 确实触发了两次，第二次index为null

Please use newest version.
