### ISSUE TITLE
[Component] [form] 表单点击回车键，会触发页面刷新

### ISSUE THREAD

**Issue by getElementBy1d** [element-plus/element-plus#11615]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.16`
- Browser / OS: `ozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIDptb2RlbD1cIm51bWJlclZhbGlkYXRlRm9ybVwiXG4gICAgbGFiZWwtd2lkdGg9XCIxMDBweFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwiYWdlXCJcbiAgICAgIHByb3A9XCJhZ2VcIlxuICAgICAgOnJ1bGVzPVwiW1xuICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAnYWdlIGlzIHJlcXVpcmVkJyB9LFxuICAgICAgICB7IHR5cGU6ICdudW1iZXInLCBtZXNzYWdlOiAnYWdlIG11c3QgYmUgYSBudW1iZXInIH0sXG4gICAgICBdXCJcbiAgICA+XG4gICAgICA8ZWwtaW5wdXRcbiAgICAgICAgdi1tb2RlbC5udW1iZXI9XCJudW1iZXJWYWxpZGF0ZUZvcm0uYWdlXCJcbiAgICAgICAgdHlwZT1cInRleHRcIlxuICAgICAgICBhdXRvY29tcGxldGU9XCJvZmZcIlxuICAgICAgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInN1Ym1pdEZvcm0oZm9ybVJlZilcIj5TdWJtaXQ8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVzZXRGb3JtKGZvcm1SZWYpXCI+UmVzZXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KClcblxuY29uc3QgbnVtYmVyVmFsaWRhdGVGb3JtID0gcmVhY3RpdmUoe1xuICBhZ2U6ICcnLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxud2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2JlZm9yZXVubG9hZCcsIChldmVudCkgPT4ge1xuICAvLyDmmL7npLrnoa7orqTlr7nor53moYZcbiAgZXZlbnQucHJldmVudERlZmF1bHQoKTtcbiAgLy8g5Li65LqG5YW85a655aSE55CG77yMQ2hyb21l6ZyA6KaB6K6+572ucmV0dXJuVmFsdWVcbiAgZXZlbnQucmV0dXJuVmFsdWUgPSAnJztcbn0pO1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <el-form
    ref="formRef"
    :model="numberValidateForm"
    label-width="100px"
    class="demo-ruleForm"
  >
    <el-form-item
      label="age"
      prop="age"
      :rules="[
        { required: true, message: 'age is required' },
        { type: 'number', message: 'age must be a number' },
      ]"
    >
      <el-input
        v-model.number="numberValidateForm.age"
        type="text"
        autocomplete="off"
      />
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="submitForm(formRef)">Submit</el-button>
      <el-button @click="resetForm(formRef)">Reset</el-button>
    </el-form-item>
  </el-form>
</template>

<script lang="ts" setup>
import { reactive, ref } from 'vue'
import type { FormInstance } from 'element-plus'

const formRef = ref<FormInstance>()

const numberValidateForm = reactive({
  age: '',
})

const submitForm = (formEl: FormInstance | undefined) => {
  if (!formEl) return
  formEl.validate((valid) => {
    if (valid) {
      console.log('submit!')
    } else {
      console.log('error submit!')
      return false
    }
  })
}

const resetForm = (formEl: FormInstance | undefined) => {
  if (!formEl) return
  formEl.resetFields()
}
window.addEventListener('beforeunload', (event) => {
  // 显示确认对话框
  event.preventDefault();
  // 为了兼容处理，Chrome需要设置returnValue
  event.returnValue = '';
});
</script>
```

输入完年龄后点击回车键

### What is Expected?

不弹出确认对话框

### What is actually happening?

会触发刷新，弹出确认对话框

### Additional comments

_(empty)_

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/219332555-e9892774-9619-4bd4-9f28-48a52efe05cb.png)
