### ISSUE TITLE
[Component] [tooltip, popper] Tooltip

### ISSUE THREAD

**Issue by teleskop150750** [element-plus/element-plus#11629]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `e.g Chrome 110 / Fedora 37`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`
- `el-popper`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/tooltip.html#basic-usage)

### Steps to reproduce

move the mouse
(top) (top-end)

https://user-images.githubusercontent.com/62594983/219367811-a9bcaa5c-d09b-47d3-9f2c-7787b62895cb.mp4

### What is Expected?

same offset

### What is actually happening?

different offset

### Additional comments

_(empty)_

**Comment by itsalimanuel** [comment]
@teleskop150750 ,
It is different offset.

"top" places the tooltip directly above the center of the element.
"top-start" places the tooltip above the element, but aligned with the start edge (left edge in LTR languages) of the element.
"top-end" places the tooltip above the element, but aligned with the end edge (right edge in LTR languages) of the element.

**Comment by teleskop150750** [comment]
@itsalimanuel ,

I mean that there is a different indentation in height.
It says it's fixed, but the problem persists.

[example](https://github.com/element-plus/element-plus/pull/11377)
