### ISSUE TITLE
[Docs] [All] 500 errors are often reported on the Chinese official website

### ISSUE THREAD

**Issue by han1822815550** [element-plus/element-plus#11632]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: ` System:  OS: Windows 10    Browsers: Chrome: 109.0.5414.122`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/)

### Steps to reproduce

Visit the Chinese official website  https://element-plus.gitee.io/zh-CN/

### What is Expected?

Normal access, no error reported

### What is actually happening?

Frequently 500 error reports

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
If you have a certain method, it is recommended to visit
https://element-plus.org/
or
https://cn.element-plus.org/

#9196

**Comment by han1822815550** [comment]
> If you have a certain method, it is recommended to visit https://element-plus.org/ or https://cn.element-plus.org/
> 
> #9196

How to search content from the Chinese website and open the jump to the English website? thank you

**Comment by han1822815550** [comment]
> > If you have a certain method, it is recommended to visit https://element-plus.org/ or https://cn.element-plus.org/
> > #9196
> 
> How to search content from the Chinese website and open the jump to the English website? thank you

**Comment by han1822815550** [comment]
> If you have a certain method, it is recommended to visit https://element-plus.org/ or https://cn.element-plus.org/
> 
> #9196

Search for content in the Chinese website, but it is the English website that jumps. How to solve it?

**Comment by chenxch** [comment]
We have encountered some problems in configuring `algolia` and have not yet solved it, so at present, we can only switch to the desired language by ourselves.

**Comment by han1822815550** [comment]
> We have encountered some problems in configuring `algolia` and have not yet solved it, so at present, we can only switch to the desired language by ourselves.

Well, thank you
