### ISSUE TITLE
https://element-plus.org  Hang up

### ISSUE THREAD

**Issue by DawnLou** [element-plus/element-plus#1165]

**Comment by JeremyWuuuuu** [comment]
Confirmed, caused by updating `VueRouter` will fix soon.

**Comment by wangz-code** [comment]
组件文档有备份地址吗?,  想看下文档

**Comment by JeremyWuuuuu** [comment]
> 组件文档有备份地址吗?, 想看下文档

Going to fix it in minutes. Don't worry.

**Comment by zazzaz** [comment]
fixed, thanks

**Comment by JeremyWuuuuu** [comment]
@DawnLou  @wangz-code use cmd(if you are Mac user) ctrl(if you are windows PC user) + R to hard reload the page

**Comment by wangz-code** [comment]
> @DawnLou @wangz代码使用cmd（如果您是Mac用户）ctrl（如果您是Windows PC用户）+ Shift + R来重新加载页面

It's ready. Thank you very much
