### ISSUE TITLE
[Component] [table, table-column] el-table-column中,当我设置filters要进行筛选并设置了中文语言,确认和重置按钮都为英文

### ISSUE THREAD

**Issue by fanwww** [element-plus/element-plus#11659]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0RGF0ZUZpbHRlclwiPnJlc2V0IGRhdGUgZmlsdGVyPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2xlYXJGaWx0ZXJcIj5yZXNldCBhbGwgZmlsdGVyczwvZWwtYnV0dG9uPlxuICA8ZWwtdGFibGUgcmVmPVwidGFibGVSZWZcIiByb3cta2V5PVwiZGF0ZVwiIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgIHByb3A9XCJkYXRlXCJcbiAgICAgIGxhYmVsPVwiRGF0ZVwiXG4gICAgICBzb3J0YWJsZVxuICAgICAgd2lkdGg9XCIxODBcIlxuICAgICAgY29sdW1uLWtleT1cImRhdGVcIlxuICAgICAgOmZpbHRlcnM9XCJbXG4gICAgICAgIHsgdGV4dDogJzIwMTYtMDUtMDEnLCB2YWx1ZTogJzIwMTYtMDUtMDEnIH0sXG4gICAgICAgIHsgdGV4dDogJzIwMTYtMDUtMDInLCB2YWx1ZTogJzIwMTYtMDUtMDInIH0sXG4gICAgICAgIHsgdGV4dDogJzIwMTYtMDUtMDMnLCB2YWx1ZTogJzIwMTYtMDUtMDMnIH0sXG4gICAgICAgIHsgdGV4dDogJzIwMTYtMDUtMDQnLCB2YWx1ZTogJzIwMTYtMDUtMDQnIH0sXG4gICAgICBdXCJcbiAgICAgIDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVySGFuZGxlclwiXG4gICAgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiA6Zm9ybWF0dGVyPVwiZm9ybWF0dGVyXCIgLz5cblxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgIHByb3A9XCJ0YWdcIlxuICAgICAgbGFiZWw9XCJUYWdcIlxuICAgICAgd2lkdGg9XCIxMDBcIlxuICAgICAgOmZpbHRlcnM9XCJbXG4gICAgICAgIHsgdGV4dDogJ0hvbWUnLCB2YWx1ZTogJ0hvbWUnIH0sXG4gICAgICAgIHsgdGV4dDogJ09mZmljZScsIHZhbHVlOiAnT2ZmaWNlJyB9LFxuICAgICAgXVwiXG4gICAgICA6ZmlsdGVyLW1ldGhvZD1cImZpbHRlclRhZ1wiXG4gICAgICBmaWx0ZXItcGxhY2VtZW50PVwiYm90dG9tLWVuZFwiXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXRhZ1xuICAgICAgICAgIDp0eXBlPVwic2NvcGUucm93LnRhZyA9PT0gJ0hvbWUnID8gJycgOiAnc3VjY2VzcydcIlxuICAgICAgICAgIGRpc2FibGUtdHJhbnNpdGlvbnNcbiAgICAgICAgICA+e3sgc2NvcGUucm93LnRhZyB9fTwvZWwtdGFnXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxUYWJsZSwgdHlwZSBUYWJsZUNvbHVtbkN0eCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xuICB0YWc6IHN0cmluZ1xufVxuXG5jb25zdCB0YWJsZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVGFibGU+PigpXG5cbmNvbnN0IHJlc2V0RGF0ZUZpbHRlciA9ICgpID0+IHtcbiAgdGFibGVSZWYudmFsdWUhLmNsZWFyRmlsdGVyKFsnZGF0ZSddKVxufVxuLy8gVE9ETzogaW1wcm92ZW1lbnQgdHlwaW5nIHdoZW4gcmVmYWN0b3IgdGFibGVcbmNvbnN0IGNsZWFyRmlsdGVyID0gKCkgPT4ge1xuICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50XG4gIC8vIEB0cy1leHBlY3QtZXJyb3JcbiAgdGFibGVSZWYudmFsdWUhLmNsZWFyRmlsdGVyKClcbn1cbmNvbnN0IGZvcm1hdHRlciA9IChyb3c6IFVzZXIsIGNvbHVtbjogVGFibGVDb2x1bW5DdHg8VXNlcj4pID0+IHtcbiAgcmV0dXJuIHJvdy5hZGRyZXNzXG59XG5jb25zdCBmaWx0ZXJUYWcgPSAodmFsdWU6IHN0cmluZywgcm93OiBVc2VyKSA9PiB7XG4gIHJldHVybiByb3cudGFnID09PSB2YWx1ZVxufVxuY29uc3QgZmlsdGVySGFuZGxlciA9IChcbiAgdmFsdWU6IHN0cmluZyxcbiAgcm93OiBVc2VyLFxuICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4pID0+IHtcbiAgY29uc3QgcHJvcGVydHkgPSBjb2x1bW5bJ3Byb3BlcnR5J11cbiAgcmV0dXJuIHJvd1twcm9wZXJ0eV0gPT09IHZhbHVlXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgdGFnOiAnSG9tZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```
<template>
  <el-table
    :data="tableData"
    :default-sort="{ prop: 'date', order: 'descending' }"
    style="width: 100%"
  >
    <el-table-column prop="date" label="Date" sortable width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" :formatter="formatter" />
  </el-table>
</template>

<script lang="ts" setup>
import type { TableColumnCtx } from 'element-plus'

interface User {
  date: string
  name: string
  address: string
}

const formatter = (row: User, column: TableColumnCtx<User>) => {
  return row.address
}

const tableData: User[] = [
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>
```

### What is Expected?

在配置中文选项后,设置filters要进行筛选,确认和重置按钮文字为中文,或者支持用户自定义

### What is actually happening?

在配置中文选项后,设置filters要进行筛选,确认和重置按钮文字为英文

### Additional comments

官方的tabel筛选例子中就有出现

![0C6HRW1G@R1BHG134K(65HE](https://user-images.githubusercontent.com/98572444/220037212-9bd6e671-f210-47f7-a398-1ce8305b7540.png)

**Comment by acyza** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIG1iLTIgQGNsaWNrPVwidG9nZ2xlXCI+U3dpdGNoIExhbmd1YWdlPC9lbC1idXR0b24+XG4gIOW9k+WJjeivreiogO+8mnt7bGFuZ3VhZ2V9fVxuICAgIDxiciAvPlxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOmxvY2FsZT1cImxvY2FsZVwiPlxuICBcdFx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldERhdGVGaWx0ZXJcIj5yZXNldCBkYXRlIGZpbHRlcjwvZWwtYnV0dG9uPlxuICBcdFx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJjbGVhckZpbHRlclwiPnJlc2V0IGFsbCBmaWx0ZXJzPC9lbC1idXR0b24+XG4gIFx0XHQ8ZWwtdGFibGUgcmVmPVwidGFibGVSZWZcIiByb3cta2V5PVwiZGF0ZVwiIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIFx0XHQ8ZWwtdGFibGUtY29sdW1uXG4gICAgICBcdFx0cHJvcD1cImRhdGVcIlxuICAgICAgXHRcdGxhYmVsPVwiRGF0ZVwiXG4gICAgICBcdFx0c29ydGFibGVcbiAgICAgXHRcdCBcdHdpZHRoPVwiMTgwXCJcbiAgICAgIFx0XHRjb2x1bW4ta2V5PVwiZGF0ZVwiXG4gICAgICBcdFx0OmZpbHRlcnM9XCJbXG4gICAgICAgIFx0XHR7IHRleHQ6ICcyMDE2LTA1LTAxJywgdmFsdWU6ICcyMDE2LTA1LTAxJyB9LFxuICAgICAgICBcdFx0eyB0ZXh0OiAnMjAxNi0wNS0wMicsIHZhbHVlOiAnMjAxNi0wNS0wMicgfSxcbiAgICAgICAgXHRcdHsgdGV4dDogJzIwMTYtMDUtMDMnLCB2YWx1ZTogJzIwMTYtMDUtMDMnIH0sXG4gICAgICAgIFx0XHR7IHRleHQ6ICcyMDE2LTA1LTA0JywgdmFsdWU6ICcyMDE2LTA1LTA0JyB9LFxuICAgICAgXHRcdF1cIlxuICAgICAgXHRcdDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVySGFuZGxlclwiXG4gICAgXHRcdC8+XG4gICAgXHRcdDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgXHRcdDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiA6Zm9ybWF0dGVyPVwiZm9ybWF0dGVyXCIgLz5cblxuICAgIFx0XHQ8ZWwtdGFibGUtY29sdW1uXG4gICAgICBcdFx0cHJvcD1cInRhZ1wiXG4gICAgICBcdFx0bGFiZWw9XCJUYWdcIlxuICAgICAgXHRcdHdpZHRoPVwiMTAwXCJcbiAgICAgIFx0XHQ6ZmlsdGVycz1cIltcbiAgICAgICAgXHRcdHsgdGV4dDogJ0hvbWUnLCB2YWx1ZTogJ0hvbWUnIH0sXG4gICAgICAgIFx0XHR7IHRleHQ6ICdPZmZpY2UnLCB2YWx1ZTogJ09mZmljZScgfSxcbiAgICAgIFx0XHRdXCJcbiAgICAgIFx0XHQ6ZmlsdGVyLW1ldGhvZD1cImZpbHRlclRhZ1wiXG4gICAgICBcdFx0ZmlsdGVyLXBsYWNlbWVudD1cImJvdHRvbS1lbmRcIlxuICAgIFx0XHQ+XG4gICAgICBcdFx0PHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgXHRcdDxlbC10YWdcbiAgICAgICAgICBcdFx0OnR5cGU9XCJzY29wZS5yb3cudGFnID09PSAnSG9tZScgPyAnJyA6ICdzdWNjZXNzJ1wiXG4gICAgICAgICAgXHRcdGRpc2FibGUtdHJhbnNpdGlvbnNcbiAgICAgICAgICBcdFx0Pnt7IHNjb3BlLnJvdy50YWcgfX08L2VsLXRhZ1xuICAgICAgICBcdFx0PlxuICAgICAgXHRcdDwvdGVtcGxhdGU+XG4gICAgXHRcdDwvZWwtdGFibGUtY29sdW1uPlxuICBcdFx0PC9lbC10YWJsZT5cbiAgPC9lbC1jb25maWctcHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxUYWJsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB0eXBlIHsgVGFibGVDb2x1bW5DdHggfSBmcm9tICdlbGVtZW50LXBsdXMnXG4gIFxuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcbmltcG9ydCBlbiBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvZW4ubWpzJ1xuXG5jb25zdCBsYW5ndWFnZSA9IHJlZignemgtY24nKVxuY29uc3QgbG9jYWxlID0gY29tcHV0ZWQoKCkgPT4gKGxhbmd1YWdlLnZhbHVlID09PSAnemgtY24nID8gemhDbiA6IGVuKSlcblxuY29uc3QgdG9nZ2xlID0gKCkgPT4ge1xuICBsYW5ndWFnZS52YWx1ZSA9IGxhbmd1YWdlLnZhbHVlID09PSAnemgtY24nID8gJ2VuJyA6ICd6aC1jbidcbn1cblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xuICB0YWc6IHN0cmluZ1xufVxuXG5jb25zdCB0YWJsZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVGFibGU+PigpXG5cbmNvbnN0IHJlc2V0RGF0ZUZpbHRlciA9ICgpID0+IHtcbiAgdGFibGVSZWYudmFsdWUhLmNsZWFyRmlsdGVyKFsnZGF0ZSddKVxufVxuLy8gVE9ETzogaW1wcm92ZW1lbnQgdHlwaW5nIHdoZW4gcmVmYWN0b3IgdGFibGVcbmNvbnN0IGNsZWFyRmlsdGVyID0gKCkgPT4ge1xuICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50XG4gIC8vIEB0cy1leHBlY3QtZXJyb3JcbiAgdGFibGVSZWYudmFsdWUhLmNsZWFyRmlsdGVyKClcbn1cbmNvbnN0IGZvcm1hdHRlciA9IChyb3c6IFVzZXIsIGNvbHVtbjogVGFibGVDb2x1bW5DdHg8VXNlcj4pID0+IHtcbiAgcmV0dXJuIHJvdy5hZGRyZXNzXG59XG5jb25zdCBmaWx0ZXJUYWcgPSAodmFsdWU6IHN0cmluZywgcm93OiBVc2VyKSA9PiB7XG4gIHJldHVybiByb3cudGFnID09PSB2YWx1ZVxufVxuY29uc3QgZmlsdGVySGFuZGxlciA9IChcbiAgdmFsdWU6IHN0cmluZyxcbiAgcm93OiBVc2VyLFxuICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4pID0+IHtcbiAgY29uc3QgcHJvcGVydHkgPSBjb2x1bW5bJ3Byb3BlcnR5J11cbiAgcmV0dXJuIHJvd1twcm9wZXJ0eV0gPT09IHZhbHVlXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgdGFnOiAnSG9tZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
好像没问题啊？
可以切换中文啊！
