### ISSUE TITLE
[Docs] [All] 文档的中文版翻译版本地址变为404

### ISSUE THREAD

**Issue by cyyspring** [element-plus/element-plus#11656]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.32`
- Browser / OS: ` UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

1.访问https://element-plus.org/zh-CN/ 404

### What is Expected?

可以访问

### What is actually happening?

404

### Additional comments

_(empty)_

**Comment by LiRongYou** [comment]
访问不了

**Comment by iamkun** [comment]
fixed, thanks

**Comment by muchen404** [comment]
@iamkun 又挂了
