### ISSUE TITLE
[Component] [input-number] input-number框设置step 属性后，填入非步进倍数的数据，展示错误提示 / Input-numbe box sets the step attribute，Fill in data of non-step multiple，display error prompt

### ISSUE THREAD

**Issue by code-xman** [element-plus/element-plus#11658]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.20`
- Browser / OS: `chrome 107.0.5304.88 / windows 21H2;  Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html#%E6%AD%A5%E8%BF%9B)

### Steps to reproduce

creat an el-input-number;
Set the step property to 2;
Set the step-strictly property to false;(Of course, the same is true by default);
start project;
If you enter 3, then hover the mouse over the el-input-number box;
You will be prompted: "Please enter valid values, the two closest valid values are 2 and 4";

### What is Expected?

Don't prompt or give a correct prompt.

### What is actually happening?

Shown an error prompt.

### Additional comments

Link to minimal replication environment is the official website address.Because it can reproduce.
I think the effective value should not be judged according to the step distance.After all, I can set smaller precision.

**Comment by holazz** [comment]
Hi, this is not a bug, but the behavior of the native input. Check here to get more information👇
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step

**Comment by code-xman** [comment]
@holazz 
But there is another attribute："step-strictly".  If you have this attribute，I can understand.  
Without this attribute, people will think that the input value is not valid.
But I already know that this is not element's problem.
Give an empty title to solve the problem.

**Comment by code-xman** [comment]
Give an empty title to solve the problem.
