### ISSUE TITLE
[i18n] [date-picker] 日期选择框澳大利亚英文版无法把第一天设置为 monday

### ISSUE THREAD

**Issue by wushangshang** [element-plus/element-plus#11666]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxkaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuXG4gICAgICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgICAgICAgICAgICB0eXBlPVwid2Vla1wiXG4gICAgICAgICAgICAgICAgOmZpcnN0RGF5T2ZXZWVrPVwiMVwiXG4gICAgICAgICAgICAgICBcbiAgICAgICAgICAgICAgICBmb3JtYXQ9XCJZWVlZIC1bV2Vla10gd3dcIlxuICAgICAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIHdlZWtcIlxuICAgICAgICAgICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIi8+XG4gICAgICAgIDwvZGl2PlxuXG4gICAgPC9kaXY+XG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5cbiAgICBleHBvcnQgZGVmYXVsdCB7XG4gICAgICAgIGRhdGEoKSB7XG4gICAgICAgICAgICByZXR1cm4ge1xuICAgICAgICAgICAgICAgIHZhbHVlMTogJycsXG4gICAgICAgICAgICAgICAgcGlja2VyT3B0aW9uczoge1xuICAgICAgICAgICAgICAgICAgICBmaXJzdERheU9mV2VlazogMSwgLy8g5bCG5LiA5ZGo55qE56ys5LiA5aSp6K6+572u5Li65ZGo5LiAXG4gICAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICBtZXRob2RzOiB7XG4gICAgICAgICAgICBoYW5kbGVDaGFuZ2UodmFsKSB7XG4gICAgICAgICAgICAgICAgLy8g5bCG6YCJ5Lit55qE5pel5pyf5L2c5Li65Y+C5pWw5Lyg6YCS57uZ54i257uE5Lu2XG4gICAgICAgICAgICAgICAgdGhpcy4kZW1pdCgnc2VsZWN0ZWQtZGF0ZScsIHZhbCk7XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9XG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

设置了firstDayOfWeek，但是无效

### What is Expected?

一周第一天为周一

### What is actually happening?

一周第一天为周日

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
ref to #11546

**Comment by wushangshang** [comment]
> ref to #11546

我当然知道设置海外会这样，我问的是为何无法修改 firstDayOfWeek。这边人家实际也是周一是开始的

**Comment by wushangshang** [comment]
设置英文的前提下，如何把每周第一天设置为周一？？？？？？？？

**Comment by chenxch** [comment]
动手点一下参看那边的demo看看
