### ISSUE TITLE
[Component] [menu] 调用el-menu的close方法时控制台报警告

### ISSUE THREAD

**Issue by geedys** [element-plus/element-plus#11673]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome 110`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Link]()

### Steps to reproduce
```js
<el-menu  ref="menuRef"  >
<el-sub-menu index="1-1">
<template #title>
    <span>示例菜单</span>
</template>
</el-sub-menu>
</el-menu>

<script setup>
const menuRef = ref();

onMounted(()=>{
const index = '1-1'//示例 
menuRef.value.close(index); //此处目前有警告 [Vue warn]: Invalid event arguments: event validation failed for event "close".
})
</script>
```
### What is Expected?

不要出现警告

### What is actually happening?

控制台出现警告:[Vue warn]: Invalid event arguments: event validation failed for event "close".
菜单也关闭了 

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
`(index: string, indexPath: string[]) => void`  还需要传递第二个参数，文档后续会更新这部分说明。

**Comment by geedys** [comment]
是不是可以按照open方法的实现方式, open只需要传递一个参数就可以了..

**Comment by chenxch** [comment]
> 是不是可以按照open方法的实现方式, open只需要传递一个参数就可以了..

关闭的话确实没必要传indexpath

**Comment by haoma2514** [comment]
> [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLW1lbnUgIHJlZj1cIm1lbnVSZWZcIiAgPlxuPGVsLXN1Yi1tZW51IGluZGV4PVwiMS0xXCI+XG48dGVtcGxhdGUgI3RpdGxlPlxuICAgIDxzcGFuPuekuuS+i+iPnOWNlTwvc3Bhbj5cbjwvdGVtcGxhdGU+XG48L2VsLXN1Yi1tZW51PlxuPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG4gIGltcG9ydCB7IHJlZixvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5jb25zdCBtZW51UmVmID0gcmVmKCk7XG5cbm9uTW91bnRlZCgoKT0+e1xuY29uc3QgaW5kZXggPSAnMS0xJy8v56S65L6LIFxubWVudVJlZi52YWx1ZS5jbG9zZShpbmRleCxbXSk7IC8v5q2k5aSE55uu5YmN5pyJ6K2m5ZGKIFtWdWUgd2Fybl06IEludmFsaWQgZXZlbnQgYXJndW1lbnRzOiBldmVudCB2YWxpZGF0aW9uIGZhaWxlZCBmb3IgZXZlbnQgXCJjbG9zZVwiLlxufSlcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) `(index: string, indexPath: string[]) => void` 还需要传递第二个参数，文档后续会更新这部分说明。

现在3月27了，文档还没更新。 其实很有必要加个全部折叠或展开的方法。
