### ISSUE TITLE
[Style] [table] cdn引入后表格样式不正确

### ISSUE THREAD

**Issue by wlf1995** [element-plus/element-plus#11671]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.32`
- Browser / OS: `Edg/110.0.1587.46`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/wlf1995/pen/eYLJQOe)

### Steps to reproduce

运行codepen示例

### What is Expected?

渲染3列数据

### What is actually happening?

每个表头单独占了一行

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
请查看[文档](https://element-plus.org/en-US/component/table.html#faq)
