### ISSUE TITLE
[Style] [breadcrumb-item] 弹性盒子布局影响了过渡效果

### ISSUE THREAD

**Issue by Lwenwu** [element-plus/element-plus#11679]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.8`
- Browser / OS: `Google Chrome版本 109.0.5414.120（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-breadcrumb-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGxpc3QgPSByZWFjdGl2ZShbJ2FhYScsJ2JiYicsJ2NjYyddKVxuY29uc3QgY2hhbmdlbGFzdCA9ICgpID0+IHtcbiAgbGlzdFsyXSA9IGxpc3RbMl09PT0nZGRkJz8nY2NjJzonZGRkJ1xufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGVsLWJyZWFkY3J1bWIgc2VwYXJhdG9yPVwiL1wiPlxuICAgIDx0cmFuc2l0aW9uLWdyb3VwIG5hbWU9XCJicmVhZGNydW1iXCI+XG4gICAgICA8ZWwtYnJlYWRjcnVtYi1pdGVtIHYtZm9yPVwiaXRlbSBpbiBsaXN0XCIgOmtleT1cIml0ZW1cIj5cbiAgICAgICAgPHNwYW4+XG4gICAgICAgICAge3sgaXRlbSB9fVxuICAgICAgICA8L3NwYW4+XG4gICAgICA8L2VsLWJyZWFkY3J1bWItaXRlbT5cbiAgICA8L3RyYW5zaXRpb24tZ3JvdXA+XG4gIDwvZWwtYnJlYWRjcnVtYj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VsYXN0XCI+5pS55Y+Y5pyA5ZCO5LiA6aG5PC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uYnJlYWRjcnVtYi1tb3ZlLFxuLmJyZWFkY3J1bWItZW50ZXItYWN0aXZlLFxuLmJyZWFkY3J1bWItbGVhdmUtYWN0aXZlIHtcbiAgdHJhbnNpdGlvbjogYWxsIC41cztcbn1cblxuLmJyZWFkY3J1bWItZW50ZXItZnJvbSxcbi5icmVhZGNydW1iLWxlYXZlLXRve1xuICBvcGFjaXR5OiAwO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoMjBweCk7XG59XG5cbi5icmVhZGNydW1iLWxlYXZlLWFjdGl2ZXtcbiAgcG9zaXRpb246IGFic29sdXRlO1xufVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击按钮，观察面包屑离开时的过渡效果。

### What is Expected?

离开时应向右移动

### What is actually happening?

离开时向左移动

### Additional comments

原因是：.el-breadcrumb__item拥有‘display: flex’样式，目的是让容器内元素居中。但是该样式导致过渡时添加的‘position: absolute’不能正确定位。
解决方案：.el-breadcrumb__item外层添加一个容器元素包裹。

**Comment by chenxch** [comment]
重写一下下面的样式
```css
.el-breadcrumb__item {
   display: inline-flex;
}
```
