### ISSUE TITLE
[Component] [dropdown] el-dropdown在2.2.31更新后，点击后hover会触发:focus-visible的状态，导致会有黑框，影响美观

### ISSUE THREAD

**Issue by u373693041** [element-plus/element-plus#11684]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.32`
- Browser / OS: `edge 104.0.1293.70`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24+XG4gICAgPHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+XG4gICAgICBEcm9wZG93biBMaXN0XG4gICAgICA8ZWwtaWNvbiBjbGFzcz1cImVsLWljb24tLXJpZ2h0XCI+XG4gICAgICAgIDxhcnJvdy1kb3duIC8+XG4gICAgICA8L2VsLWljb24+XG4gICAgPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5leGFtcGxlLXNob3djYXNlIC5lbC1kcm9wZG93bi1saW5rIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBjb2xvcjogdmFyKC0tZWwtY29sb3ItcHJpbWFyeSk7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.点击el-dropdown
2.然后hover再移出，返回操作查看效果

### What is Expected?

跟2.2.30及以前版本一样，没有黑框

### What is actually happening?

会有黑框影响美观

### Additional comments

经排查应该是触发了:focus-visible的状态，所以有了黑框，但是2.2.30及以前版本是没有这个问题，可能2.2.31的更改导致的
可以在上面playground的实例，切换到2.2.30版本，是没有这个问题

![0f2ec3c6-ef88-405f-8148-bd1b87f19b70](https://user-images.githubusercontent.com/48196776/220805184-bddde4af-4e21-4912-bd4f-1bdea88eef07.jpeg)
![20230223095830_rec_](https://user-images.githubusercontent.com/48196776/220805405-bc8b384f-cb00-4919-b9f9-3d9b4f171376.gif)

**Comment by MrWeilian** [comment]
已经有个issue啦 [#11662](https://github.com/element-plus/element-plus/issues/11662)
