### ISSUE TITLE
[Component] [select] Select not working when wrapped with label

### ISSUE THREAD

**Issue by p1xell0rd** [element-plus/element-plus#11680]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bGFiZWw+XG4gICAgVGVzdFxuICBcdDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiBtdWx0aXBsZT5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvbGFiZWw+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZihbJ09wdGlvbiAxJ10pXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH1cbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Try opening the select in the linked demo

### What is Expected?

The select dropdown should open when the select element is clicked

### What is actually happening?

The select dropdown isn't opening

### Additional comments

The bug only seems to occur with multi selects that have a selected value.
When the select is cleared it works again until a new value is selected.

**Comment by p1xell0rd** [comment]
Sorry about that, I updated the playground link, now you should be able to reproduce.

**Comment by wonderl17** [comment]
I have a question, why you use the 'label' tag instead of 'div' or any other tags?

**Comment by p1xell0rd** [comment]
Because it is the semantically correct element for that usage.

**Comment by itsalimanuel** [comment]
@p1xell0rd You can't use label tag instead of div in this situation.

The <label> tag can be used with input tag.

You can check the Definition and Usage of label tag:
https://www.w3schools.com/tags/tag_label.asp

**Comment by ac51300696** [comment]
> @p1xell0rd You can't use label tag instead of div in this situation.
> 
> The tag can be used with input tag.
> 
> You can check the Definition and Usage of label tag: https://www.w3schools.com/tags/tag_label.asp

why i see some Different views in mdn
https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#:~:text=%3Ctextarea%3E.-,labelable,-Elements%20that%20can

select is also labelable

**Comment by itsalimanuel** [comment]
@ac51300696 https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories
here they are talking about pure HTML , so easily you can use label with select.
here and example and as you see you are calling the select directly after the label
```
<label>
<select></select>
</label>
```

but with ElementPlus it's looks like: 
```
<div class="el-select">
 <div class="el-input">
  <div  class="el-input-*">
   <div  class="el-input-*-*">
     <input/>
   </div>
  </div>
 </div>
</div>
```

**Comment by ac51300696** [comment]
@itsalimanuel get it， tks

**Comment by itsalimanuel** [comment]
@ac51300696 No worries, good luck.

**Comment by p1xell0rd** [comment]
I know that the DOM of the el-select is completely different from a standard HTML select.
But imho wrapping it in a label still should absolutely not disrupt it's functionality.
Or is there actually a technical reason it behaves like this?

**Comment by itsalimanuel** [comment]
even in the pure HTML, the correct way to use label with select:
```
<label for="my-select">Select a fruit:</label>
<select id="my-select" name="fruits">
  <option value="apple">Apple</option>
  <option value="banana">Banana</option>
  <option value="orange">Orange</option>
</select>
```

**Comment by p1xell0rd** [comment]
I'm aware, however in plain old HTML the select also doesn't break when being wrapped in a label, and neither should the e+ select, that's my whole point here.

**Comment by itsalimanuel** [comment]
I know that you can , I just said the **Correct way**

**Comment by p1xell0rd** [comment]
Both ways are correct.

**Comment by p1xell0rd** [comment]
Please remove the `needs more info` label, as more info was already provided.

**Comment by chenxch** [comment]
I very much agree with @itsalimanuel  point of view, because el-select is not a native select, it is composed of div, input, etc., triggering depends on clicking on div, and then when using label wrapping, it triggers an implicit label, which is equal to When clicking, only the focus event of the label is triggered, but as for why it can be expanded normally when there is no option value, there is no time to troubleshoot. Then, you can add `@click.prevent` to `el-select`.
