### ISSUE TITLE
[Component] [date-picker] el-date-picker 当 type 属性 type="date" 时,  default-time 配置无效, 得到的日期时间部分总是 00:00:00

### ISSUE THREAD

**Issue by bywayboy** [element-plus/element-plus#11696]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `Edg/110.0.1587 / Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgZGF0ZSA9IHJlZihuZXcgRGF0ZSgpKSwgZGVmYXVsdFRpbWUgPSByZWYobmV3IERhdGUoKSk7XG5kZWZhdWx0VGltZS52YWx1ZS5zZXRIb3VycygxMiwwLDAsMCk7XG5jb25zdCBkYXRlMSA9IHJlZihuZXcgRGF0ZSgpKSwgZm9ybWF0PSdNTS1ERCDlhaXkvY8nO1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwibGluZS1oZWlnaHQ6MjAwJTtcIj5cbiAgICA8aDQ+5pe26Ze06YOo5YiG5Lii5aSx5ryU56S6PC9oND5cbiAgICA8ZGl2PumFjee9rueahOm7mOiupOaXtumXtOS4ujp7eyBkZWZhdWx0VGltZSB9fTwvZGl2PlxuICAgIDxkaXY+5b2T5YmN6YCJ5oup5pe26Ze05Li6Ont7IGRhdGUgfX08L2Rpdj5cbiAgICA8ZWwtZGF0ZS1waWNrZXIgdHlwZT1cImRhdGVcIiA6ZGVmYXVsdC10aW1lPVwiZGVmYXVsdFRpbWVcIiB2LW1vZGVsPVwiZGF0ZVwiID48L2VsLWRhdGUtcGlja2VyPlxuICA8L2Rpdj5cbiAgPGRpdiBzdHlsZT1cImxpbmUtaGVpZ2h0OjIwMCU7XCI+XG4gICAgPGg0PuaYvuekuuagvOW8j+W5suaJsOS4i+aLieaciOWOhua8lOekujwvaDQ+XG4gICAgPGRpdj7phY3nva7nmoTpu5jorqTml7bpl7TkuLo6IE1NLUREIOWFpeS9jzwvZGl2PlxuICAgIDxkaXY+5LiL5ouJ55qE5pyI5Y6GIOWwj+aXtumDqOWIhui+k+WFpeahhuWGheWuueWPmOaIkOS6huWFpeS9j+S4pOS4quWtlzwvZGl2PlxuICAgIDxlbC1kYXRlLXBpY2tlciB0eXBlPVwiZGF0ZXRpbWVcIiA6Zm9ybWF0PVwiZm9ybWF0XCIgOmRlZmF1bHQtdGltZT1cImRlZmF1bHRUaW1lXCIgdi1tb2RlbD1cImRhdGUxXCIgPjwvZWwtZGF0ZS1waWNrZXI+XG4gIDwvZGl2PlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIDxzdHlsZT5cbiAgIGRpdiB7bGluZS1oZWlnaHQ6MjAwJTt9XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 使用 date-picker组件 time-format设置为你期望得到的时间,  type 设置为 date.
2. 选择日期，时间部分和预期不符，总是 00:00:00

### What is Expected?

期望得到 time-format 所指定的时间

### What is actually happening?

时间部分和预期不符，总是 00:00:00

### Additional comments

_(empty)_

**Comment by godxiaoji** [comment]
这个组件没看到有提供 `time-format` 的参数设置，他就不支持设置时间部分。你自己设置的defaultTime不影响选择结果的时间部分。

**Comment by RicardoErii** [comment]
第二个问题 应该是由于传入的 `format` 属性，在展示小时部分的输入框时是根据 `format` 属性中  `HH-MM-SS` 等的来进行格式化的，由于传入的是 `MM-DD 入住`，小时部分输入框进行过滤后的 `format` 变为 `入住` ，因此显示的为入住

**Comment by bywayboy** [comment]
> 第二个问题 应该是由于传入的 `format` 属性，在展示小时部分的输入框时是根据 `format` 属性中 `HH-MM-SS` 等的来进行格式化的，由于传入的是 `MM-DD 入住`，小时部分输入框进行过滤后的 `format` 变为 `入住` ，因此显示的为入住

是的，我猜测到了是这样，但这样设计似乎并不符合数据和司徒分离逻辑?
就拿我现在的需求来说，我展示给操作员看的是 某月某如入住，实际上酒店配置的默认登记入住时间可能是 14:00 而这个时间是不需要在字段中展示出来的。

**Comment by tolking** [comment]
Fixed by #14330
