### ISSUE TITLE
[Component] [loading] v-loading directive 在作資料綁定的時候，如果是一般的 object 包裝 ref 資料，只會被判斷為 loading true 

### ISSUE THREAD

**Issue by BoYuanSu** [element-plus/element-plus#11704]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.29`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGlzTG9hZGluZyA9IHJlZihmYWxzZSlcbmNvbnN0IGRhdGEgPSB7aXNMb2FkaW5nfVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxIHYtbG9hZGluZz1cImRhdGEuaXNMb2FkaW5nXCI+e3sgbXNnIH19PC9oMT5cbiAgPGgxIHYtbG9hZGluZz1cImRhdGEuaXNMb2FkaW5nLnZhbHVlXCI+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

declare
const isLoading = ref(false)
const data = {isLoading}

template binding
v-loading="data.isLoading"

### What is Expected?

在榜定時，可以正常判斷 isLoading 狀態

### What is actually happening?

綁定後，isLoading 狀態不管是 true or false 都會被判斷為 true
因為程式讀取到的是 ref 物件，而不是 ref.value

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
v-loading收到的是一个ref对象，在if判断的时候就为true了哦，请正确使用vue以及v-loading。
