### ISSUE TITLE
[Style] [avatar] The size is not fit in el-avatar using a vertical photo

### ISSUE THREAD

**Issue by YQisme** [element-plus/element-plus#11717]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `110.0.1587.56 (Official build) (64-bit) /Windows 10 Version 22H2 (Build 19045.2604)`
- Build Tool: `Vite`

### Related Component

- `el-avatar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnMgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICAgIGZpdHM6IFsnZmlsbCcsICdjb250YWluJywgJ2NvdmVyJywgJ25vbmUnLCAnc2NhbGUtZG93biddLFxuICAgIHVybDogJ2h0dHBzOi8vaW1nLWJsb2cuY3NkbmltZy5jbi8xM2JkYWUwYWIwMjA0NmVjYmUwMjQ5ZWU5MDM0OGExNC5wbmcnLFxufSlcblxuY29uc3QgeyBmaXRzLCB1cmwgfSA9IHRvUmVmcyhzdGF0ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGRpdiBjbGFzcz1cImRlbW8tZml0XCI+XG4gICAgICA8ZGl2IHYtZm9yPVwiZml0IGluIGZpdHNcIiA6a2V5PVwiZml0XCIgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cInRpdGxlXCI+e3sgZml0IH19PC9zcGFuPlxuICAgICAgICA8ZWwtYXZhdGFyIHNoYXBlPVwic3F1YXJlXCIgOnNpemU9XCIxMDBcIiA6Zml0PVwiZml0XCIgOnNyYz1cInVybFwiIC8+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC90ZW1wbGF0ZT5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1maXQge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2Vlbjtcbn1cblxuLmRlbW8tZml0IC5ibG9jayB7XG4gICAgZmxleDogMTtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAgZmxleC1ncm93OiAwO1xufVxuXG4uZGVtby1maXQgLnRpdGxlIHtcbiAgICBtYXJnaW4tYm90dG9tOiAxMHB4O1xuICAgIGZvbnQtc2l6ZTogMTRweDtcbiAgICBjb2xvcjogdmFyKC0tZWwtdGV4dC1jb2xvci1zZWNvbmRhcnkpO1xufVxuPC9zdHlsZT5cbiAgIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

add a vertical photo to el-avatar

### What is Expected?

Fit the size, just like a horizontal photo.

### What is actually happening?

not fit the size,refer to the Element Plus Playground link above.

### Additional comments

_(empty)_

**Comment by ryuhangyeong** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/27342882/221330634-53d52b36-40f9-4d5c-872d-98a6ceeb9998.png">

Is the photo example correct what you want?

**Comment by ryuhangyeong** [comment]
[here](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnMgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICAgIGZpdHM6IFsnZmlsbCcsICdjb250YWluJywgJ2NvdmVyJywgJ25vbmUnLCAnc2NhbGUtZG93biddLFxuICAgIHVybDogJ2h0dHBzOi8vaW1nLWJsb2cuY3NkbmltZy5jbi8xM2JkYWUwYWIwMjA0NmVjYmUwMjQ5ZWU5MDM0OGExNC5wbmcnLFxufSlcblxuY29uc3QgeyBmaXRzLCB1cmwgfSA9IHRvUmVmcyhzdGF0ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGRpdiBjbGFzcz1cImRlbW8tZml0XCI+XG4gICAgICA8ZGl2IHYtZm9yPVwiZml0IGluIGZpdHNcIiA6a2V5PVwiZml0XCIgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cInRpdGxlXCI+e3sgZml0IH19PC9zcGFuPlxuICAgICAgICA8ZWwtYXZhdGFyIHNoYXBlPVwic3F1YXJlXCIgOnNpemU9XCIxMDBcIiA6Zml0PVwiZml0XCIgOnNyYz1cInVybFwiIC8+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi5kZW1vLWZpdCB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xufVxuXG4uZGVtby1maXQgLmJsb2NrIHtcbiAgICBmbGV4OiAxO1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICBmbGV4LWdyb3c6IDA7XG59XG5cbi5kZW1vLWZpdCAudGl0bGUge1xuICAgIG1hcmdpbi1ib3R0b206IDEwcHg7XG4gICAgZm9udC1zaXplOiAxNHB4O1xuICAgIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7XG59XG4uZWwtYXZhdGFyPmltZyB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gICAgaGVpZ2h0OiAxMDAlO1xuICB3aWR0aDogMTAwJTtcbn0gIFxuPC9zdHlsZT5cbiAgIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

this?

**Comment by ryuhangyeong** [comment]
@YQisme Thank you for using ep. If you have any other questions, please leave an issue.
