### ISSUE TITLE
[Build] [message, notification] 使用自动引入后，auto-imports.d.ts 文件每次项目启动会自动删除内容

### ISSUE THREAD

**Issue by ishowman** [element-plus/element-plus#11726]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome 102.0.5005.115`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-notification`

### Reproduction Link

[Github Repo](https://github.com/ishowman/vue3-ts-template-list/tree/element-plus   (element-plus 分支))

### Steps to reproduce

- Follow readme's steps to create project
- `auto-imports.d.ts` file will change unexpectly even no codes changed  after you input `pnpm dev`（components are used in src/components/HelloWorld.vue ）

### What is Expected?

在项目中引用了 ElMessage、ElNotification 组件后，启动项目后未删除ElMessage、ElNotification 组件的使用时，不会莫名其妙的删除了内容

### What is actually happening?

在项目中引用了 ElMessage、ElNotification 组件后，会莫名其妙的删除了内容

### Additional comments

This is the **diff screenshot** when you input `pnpm dev`.
![image](https://user-images.githubusercontent.com/16897283/221181947-3e911772-0b96-4332-82ac-5749b1667bd7.png)

**Comment by chenxch** [comment]
或许这个问题应该反馈先到auto import仓库中，你觉得呢？

**Comment by ishowman** [comment]
@chenxch 不清楚是那边导致的问题，都提 issue 了

**Comment by ishowman** [comment]
相关的 github repo 已经提供了，麻烦能先定位下是哪方面出问题了吗？

**Comment by ishowman** [comment]
[操作录屏.webm](https://github.com/element-plus/element-plus/assets/16897283/87e323ac-4b6d-4753-befa-5e049ca6c319)
