### ISSUE TITLE
[Component] [input] safari浏览器下el-input在英文括号里面输入中文时字母会重复

### ISSUE THREAD

**Issue by abb-uu** [element-plus/element-plus#11723]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

固定现象, 官网可复现

### What is Expected?

safari浏览器el-input组件英文括号中输入中文时拼音不会重复

### What is actually happening?

safari浏览器el-input组件英文括号中输入中文时拼音会重复

### Additional comments

_(empty)_

**Comment by mipawn** [comment]
看了一下，是因为 handleCompositionUpdate函数判断韩语的正则匹配到了 英文前括号，导致多余触发了setCursor ，但是谷歌没这个问题，看起来还是浏览器也有一定的兼容性
<img width="529" alt="image" src="https://user-images.githubusercontent.com/39559813/226334255-24fd9c7a-8fe0-4166-9421-f7d91df68fa1.png">
