### ISSUE TITLE
[bug report] El Popover label transition animation failure / exception

### ISSUE THREAD

**Issue by ll60** [element-plus/element-plus#1172]
### Element Plus version
1.0.1-beta.18

### OS/Browsers version
chrome

### Vue version
3.0.0

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
<el-popover>的transition属性失效，动画效果丢失，transition="el-zoom-in-left"时动画异常。可能是vue3版本的动画过渡周期class改变了，vue2时，进入动画是v-enter,而vue3是v-enter-from

### What is Expected?
希望修复动画丢失/异常的问题

### What is actually happening?
动画失效/异常

**Comment by JeremyWuuuuu** [comment]
Have you tried to upgrade your `vue` version? I saw you using `3.0.0`

**Comment by ll60** [comment]
> 您是否尝试升级您的`vue`版本？我看到你在用`3.0.0`

升级过了，也是一样的。

**Comment by JeremyWuuuuu** [comment]
Alright, just confirmed the on document site, transition for `leave` is missing which is a bug.

**Comment by ll60** [comment]
> 好吧，刚确认文档站点上，`leave`缺少用于的过渡，这是一个错误。

嗯，别的组件过渡动画是不是也有问题，暂时只用到这个。

**Comment by JeremyWuuuuu** [comment]
Some were fixed, some are still broken, we'll get this fixed soon

**Comment by ll60** [comment]
> Some were fixed, some are still broken, we'll get this fixed soon
👌辛苦了, 菜鸡表示,空有壮志，无力帮忙。
