### ISSUE TITLE
[Component] [color-picker] el-color-picker组件在v-model值为空的时候，刚渲染完成需要点击两次才能弹出取色面板

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#11725]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.30`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/GRXjKBG)

### Steps to reproduce

1.打开链接
2.点击取色器组件

### What is Expected?

只需点击一次

### What is actually happening?

需要点击两次

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
测试发现点击左侧部分区域需要点击2次，右侧只要一次就能弹出窗口，可能是点击区域问题

**Comment by chenxch** [comment]
问题原因应该是使用了`persistent`,至于这个属性能否去掉还需要看下是否会导致其他问题。

**Comment by tolking** [comment]
This issue has been fixed.
