### ISSUE TITLE
[Component] [autocomplete] el-autocomplete组件的某些属性无法生效，例如 disabled、clearable 等

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#11733]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.30`
- Browser / OS: `Chrome 104.0.5112.81`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/OJoRRag)

### Steps to reproduce

1.打开链接
2.可以看到disabled没有生效

### What is Expected?

属性可以按照官方文档生效

### What is actually happening?

没有生效

### Additional comments

问题可能是el-autocomplete组件有多个根节点，导致某些属性没能绑定上

**Comment by ryuhangyeong** [comment]
fixed #11714

thank you!

**Comment by linxiaodong0538** [comment]
我也遇到这个问题，官方文档上也没生效
