### ISSUE TITLE
[Component] [date-picker] DateTimePicker 日期时间选择器如何实现用户只选择不输入日期时间

### ISSUE THREAD

**Issue by CHN-STUDENT** [element-plus/element-plus#11736]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIFxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+VXNlIHZhbHVlLWZvcm1hdDwvc3Bhbj5cbiAgICAgIDxkaXYgY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+VmFsdWXvvJp7eyB2YWx1ZTIgfX08L2Rpdj5cbiAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICAgICAgdHlwZT1cImRhdGV0aW1lXCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgRGF0ZVwiXG4gICAgICAgIGZvcm1hdD1cIkhIOm1tXCIgXG4gICAgICAgICB2YWx1ZS1mb3JtYXQ9XCJZWVlZLU1NLUREVEhIOm1tOnNzWlwiXG4gICAgICAvPlxuICAgIDwvZGl2PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIHdpZHRoOiAxMDAlO1xuICBwYWRkaW5nOiAwO1xuICBmbGV4LXdyYXA6IHdyYXA7XG59XG4uZGVtby1kYXRldGltZS1waWNrZXIgLmJsb2NrIHtcbiAgcGFkZGluZzogMzBweCAwO1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIGJvcmRlci1yaWdodDogc29saWQgMXB4IHZhcigtLWVsLWJvcmRlci1jb2xvcik7XG4gIGZsZXg6IDE7XG59XG4uZGVtby1kYXRldGltZS1waWNrZXIgLmJsb2NrOmxhc3QtY2hpbGQge1xuICBib3JkZXItcmlnaHQ6IG5vbmU7XG59XG4uZGVtby1kYXRldGltZS1waWNrZXIgLmRlbW9uc3RyYXRpb24ge1xuICBkaXNwbGF5OiBibG9jaztcbiAgY29sb3I6IHZhcigtLWVsLXRleHQtY29sb3Itc2Vjb25kYXJ5KTtcbiAgZm9udC1zaXplOiAxNHB4O1xuICBtYXJnaW4tYm90dG9tOiAyMHB4O1xufVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

希望用戶只能選擇日期時間，而不要手工輸入，不然可能會對用戶造成困惑。

### What is Expected?

期望日期顯示：2023-02-01

### What is actually happening?

實際日期顯示：2023-02-08T00:00:00+08:00

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/21209416/221347496-ae7ea618-7e8f-4320-9694-cf3ac8bb5ea1.png)

**Comment by CHN-STUDENT** [comment]
duplicate #11465

**Comment by chenxch** [comment]
1. 控件目前不支持单独禁用日期部分的输入框，你看通过给其添加`pointer-event: none;`屏蔽点击focus事件
2. 你选择的是2月8日会什么会期望显示2月1日呢，然后你的format和value-format似乎不太对。

**Comment by CHN-STUDENT** [comment]
@chenxch 您好老师
![image](https://user-images.githubusercontent.com/21209416/221360409-fe969e1c-3f0b-4cf4-9189-2edbba33b344.png)
我想前端展示单纯的小时分钟，但是让用户可以选择其他日期；发给后端格式化的日期 2023-02-25T21:49:46+08:00 就是这样的。
只想询问左边那个日期部分的输入框显示非常奇怪，请您帮忙给给建议。

**Comment by CHN-STUDENT** [comment]
![image](https://user-images.githubusercontent.com/21209416/221360755-93e89de2-8def-4b74-908e-5b39c3af56a3.png)
上面是隔壁某家的效果，能不能我也改成类似这样的。

**Comment by chenxch** [comment]
datetimepicker作为一个日期+时间选择的控件，它是一个整体，有几个方案你看下
1、datepicker+timepicker组合，这样变成日期和时间是分开，一个是交互上变成要点击2次，一个是你传给服务端的数据还要自己拼接
2、利用基础控件自己构建出一个类似你发的这种控件也是可以，只不过成本比较大，交互逻辑部分都要自己写
3、利用input+datetimepicker ,隐藏datetimepicker的输入框，利用input框来做显示[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRldGltZS1waWNrZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiYmxvY2tcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPkVtaXRzIERhdGUgb2JqZWN0PC9zcGFuPlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5WYWx1ZToge3sgdmFsdWUxIH19PC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiY3VzdG9tX19waWNrZXJcIj5cbiAgICAgIDxlbC1pbnB1dCA6bW9kZWxWYWx1ZT1cInZhbHVlMlwiIGZvcm1hdD1cIlwiIHJlYWRvbmx5IEBjbGljaz1cImhhbmRsZUNsaWNrXCIvPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgICAgICAgICAgICAgICAgY2xhc3M9XCJlbC1kYXRlLWVkaXRvci0tZGF0ZXRpbWVcIlxuICAgICAgICByZWY9XCJkYXRlUmVmXCJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiIFxuICAgICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBEYXRlXCJcbiAgICAgICAgZm9ybWF0PVwiWVlZWS1NTS1ERCBISDptbVwiXG4gICAgICAvPlxuICAgICAgICBcbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsY29tcHV0ZWQgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgZGF5anMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbmNvbnN0IGRhdGVSZWYgPSByZWYobnVsbClcbmZ1bmN0aW9uIGhhbmRsZUNsaWNrKCl7XG4gIGRhdGVSZWYudmFsdWU/LmZvY3VzKClcbn1cblxuY29uc3QgdmFsdWUyID0gY29tcHV0ZWQoKCkgPT4ge1xuICByZXR1cm4gdmFsdWUxLnZhbHVlID8gZGF5anModmFsdWUxLnZhbHVlKS5mb3JtYXQoJ0hIOm1tJykgOiAnJ1xufSlcbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tZGF0ZXRpbWUtcGlja2VyIHtcbiAgZGlzcGxheTogZmxleDtcbiAgd2lkdGg6IDEwMCU7XG4gIHBhZGRpbmc6IDA7XG4gIGZsZXgtd3JhcDogd3JhcDtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuYmxvY2sge1xuICBwYWRkaW5nOiAzMHB4IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgYm9yZGVyLXJpZ2h0OiBzb2xpZCAxcHggdmFyKC0tZWwtYm9yZGVyLWNvbG9yKTtcbiAgZmxleDogMTtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuYmxvY2s6bGFzdC1jaGlsZCB7XG4gIGJvcmRlci1yaWdodDogbm9uZTtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuZGVtb25zdHJhdGlvbiB7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBjb2xvcjogdmFyKC0tZWwtdGV4dC1jb2xvci1zZWNvbmRhcnkpO1xuICBmb250LXNpemU6IDE0cHg7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG4gIC5jdXN0b21fX3BpY2tlciB7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlO1xuICB9XG4gIFxuICAuZWwtZGF0ZS1lZGl0b3ItLWRhdGV0aW1lIHsgXG4gICAgcG9zaXRpb246IGFic29sdXRlICFpbXBvcnRhbnQ7XG4gICAgbGVmdDogMDtcbiAgICB0b3A6IDA7XG4gICAgei1pbmRleDogLTE7XG4gIH1cbiAgXG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by tolking** [comment]
我觉得禁用输入是糟糕的行为。如果需要一个几十年前的时间，这时候选择就不如输入来的简便。

显示的问题被 #14330 修复
