### ISSUE TITLE
[Docs] [All] 为什么文档总是404,503,而且很频繁

### ISSUE THREAD

**Issue by huyuan9479** [element-plus/element-plus#11746]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.2.19`
- Browser / OS: `Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/)

### Steps to reproduce

无

### What is Expected?

优化文档浏览

### What is actually happening?

无

### Additional comments

_(empty)_

**Comment by lyric-zemin** [comment]
国内站点不太稳定
[访问这个](https://element-plus.org/zh-CN)
