### ISSUE TITLE
[Component] [All] element-plus source code components folder needs to use unplugin-vue-components, where to configure

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#11748]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.32`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/lixiaofa/fast-business)

### Steps to reproduce

pnpm docs:dev

### What is Expected?

正常引用<van-button type="primary" />

### What is actually happening?

Failed to resolve component: van-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

### Additional comments

_(empty)_

**Comment by btea** [comment]
You can refer to the [documentation](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5).

**Comment by lixiaofa** [comment]
> You can refer to the [documentation](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5).

I mean that the element-plus source code components folder needs to use unplugin-vue-components, where to configure

**Comment by btea** [comment]
It seems that there is no ready-made configuration plugin, maybe you have to write one yourself.

**Comment by lixiaofa** [comment]
> It seems that there is no ready-made configuration plugin, maybe you have to write one yourself.

Don't understand me
In the element-plus source code project, where should I configure the plug-in

**Comment by btea** [comment]
You mean to automatically import other components on demand in the element-plus source code, right?

**Comment by lixiaofa** [comment]
yes



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/28/2023 14:35 |
| To | ***@***.***> |
| Cc | Sima ***@***.***>***@***.***> |
| Subject | Re: [element-plus/element-plus] [Component] [All] element-plus source code components folder needs to use unplugin-vue-components, where to configure (Issue #11748) |

You mean to automatically import other components on demand in the element-plus source code, right?

**Comment by lixiaofa** [comment]
> You mean to automatically import other components on demand in the element-plus source code, right?

yes , 
e.g: unplugin-vue-components
Where to configure, there is no vite.config.ts file
@btea

**Comment by btea** [comment]
The element-plus source code does not use `unplugin-vue-components`, they are independent components, if there are references, they are also imported directly.

**Comment by lixiaofa** [comment]
> The element-plus source code does not use `unplugin-vue-components`, they are independent components, if there are references, they are also imported directly.

I want to add a component, but this component depends on vant components, so I want to use the unplugin-vue-components plug-in. Is there a location configuration
 @btea

**Comment by btea** [comment]
So, you want to automatically import the vant component in your new component?

**Comment by lixiaofa** [comment]
> So, you want to automatically import the vant component in your new component?

yes
@btea

**Comment by lixiaofa** [comment]
> So, you want to automatically import the vant component in your new component?



> So, you want to automatically import the vant component in your new component?

My other problem is that play doesn't seem to work

> The element-plus source code



> So, you want to automatically import the vant component in your new component?

**Comment by lixiaofa** [comment]
> So, you want to automatically import the vant component in your new component?

My other problem is that play doesn't seem to work in element plus
The following will appear:
![image](https://user-images.githubusercontent.com/23230215/221784927-0946f88e-f3a6-47f1-9b61-5eec284156b7.png)
@btea

**Comment by btea** [comment]
In your case, either put this new component directly in the project, use [vant resolver](https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/vant.ts) to automatically import the used components, or directly import the used component.

**Comment by lixiaofa** [comment]
> In your case, either put this new component directly in the project, use [vant resolver](https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/vant.ts) to automatically import the used components, or directly import the used component.

Didn't quite understand

We will discuss the method of on-demand import separately

Vant on-demand import needs to configure unplugin-vue-components. I just don't know where to configure

But direct import is a good way
@btea

**Comment by btea** [comment]
The configuration of automatic import is here, you can refer to it
https://github.com/element-plus/element-plus/blob/be0ed4de68967c87cffa76fc18f22b7dcb064497/play/vite.config.ts#L70-L73

**Comment by lixiaofa** [comment]
> 



> > > So, you want to automatically import the vant component in your new component?
> > 
> > 
> > My other problem is that play doesn't seem to work in element plus The following will appear: ![image](https://user-images.githubusercontent.com/23230215/221784927-0946f88e-f3a6-47f1-9b61-5eec284156b7.png) @btea
> 
> This seems normal, what's wrong?

How to use this? Do you have any documents
@btea

**Comment by btea** [comment]
Maybe you can refer to these two repositories.  
https://github.com/element-plus/element-plus-vite-starter
https://github.com/antfu/unplugin-vue-components

**Comment by lixiaofa** [comment]
> Maybe you can refer to these two repositories. https://github.com/element-plus/element-plus-vite-starter https://github.com/antfu/unplugin-vue-components

Don't understand me

the pnpm play doesn't seem to work in element plus source code 
How to use this?
How to test this component
![image](https://user-images.githubusercontent.com/23230215/221805699-788be1bb-370b-4379-adef-34e24918f957.png)

**Comment by lixiaofa** [comment]
> Maybe you can refer to these two repositories. https://github.com/element-plus/element-plus-vite-starter https://github.com/antfu/unplugin-vue-components

Don't understand me
In element plus, play is used to test components, how to use it, and nothing after running
![image](https://user-images.githubusercontent.com/23230215/221809251-26214559-6577-4292-b5f4-1fb4d3b0df60.png)

**Comment by btea** [comment]
Do you mean that after you execute `pnpm dev`, you open the page and there is no content?

**Comment by lixiaofa** [comment]
> Do you mean that after you execute `pnpm dev`, you open the page and there is no content?
yes

**Comment by lixiaofa** [comment]
> When executed for the first time, an App.vue file will be created, which will be displayed on the page. If there is no content, it may still be loading and you need to wait a while.

![image](https://user-images.githubusercontent.com/23230215/221814407-e445ed12-3a6d-477c-9919-207f11bef064.png)
Is this normal？

**Comment by btea** [comment]
Yes. And if you want to test other components you can use this component in App.vue.

**Comment by lixiaofa** [comment]
> Yes. And if you want to test other components you can use this component in App.vue.

Thank you very much for solving my problems

**Comment by btea** [comment]
If you have no other questions, I will close this issue. If you have other questions in the future, you can add them in the comments below.

**Comment by lixiaofa** [comment]
> If you have no other questions, I will close this issue. If you have other questions in the future, you can add them in the comments below.

okay, thank you
