### ISSUE TITLE
[Component] [All] element-plus source code ，How to use the play project? Nothing after running

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#11767]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.32`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/lixiaofa/fast-business)

### Steps to reproduce

pnpm dev

### What is Expected?

Something

### What is actually happening?

Nothing there?

### Additional comments

_(empty)_

**Comment by btea** [comment]
It's normal, you need to wait a while.
