### ISSUE TITLE
[Bug Report] can't change value in the form

### ISSUE THREAD

**Issue by jinjack33** [element-plus/element-plus#1176]
### Element Plus version
1.0.1-beta.18

### OS/Browsers version
win10

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/jinjack33/pen/abmqqQY

### Steps to reproduce
当form组件中的ref和model是相同时  没办法修改表单中的内容

### What is Expected?
可以修改表单中的内容

**Comment by JeremyWuuuuu** [comment]
of course you can't, please go see the documentation of `Vue` FYI [Special attributes](https://v3.vuejs.org/api/special-attributes.html#ref)

**Comment by ro-n** [comment]
For those who got a problem with `ref` in `<el-form>` (accessing form and using model), I solved by

```html
<el-form :model="formModel" ref="formRef">
</el-form>
```

with

```javascript
setup() {
  const state = reactive({
    formModel: { ... },
    formRef: null
  })

  const onSubmit = () => {
    // state.formRef
  }
}
```

Apparently docs were not fully adapted with Vue 3, snippet like

```html
<el-form :model="ruleForm" :rules="rules" ref="ruleForm" label-width="100px" class="demo-ruleForm">
```

never works at least for me.

**Comment by mikepxq** [comment]
只能用 vue2的语法
把 form 定义到 data 里面 比如 data(){return {form:{username:''}}}
定义到 setup 里面是无效 

或者直接使用 tsx 的语法
但 tsx，onClick 没有定义，会被ts提示报错。无法构建成功
