### ISSUE TITLE
[Style] [icon, cascader] 手动引入的组件中，自动引入的 `<el-icon>` 组件会覆盖页面中其他 el 组件的图标样式

### ISSUE THREAD

**Issue by wangxiaocuo** [element-plus/element-plus#11761]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `Microsoft Edge 110.0.1587.50`
- Build Tool: `Vite`

### Related Component

- `el-icon`
- `el-cascader`

### Reproduction Link

[Github Repo](https://github.com/wangxiaocuo/bugs-colllection/tree/main/vue3-element-plus-icon-style)

### Steps to reproduce

我在项目中只对 `src/components` 下的 `V` 开头直接子组件做了自动引入：

```js
// unplugin-vue-components/vite 配置

Components({
  globs: ['src/components/V*/*.vue']
})
```

在项目中有以下结构的组件嵌套：

```mermaid
graph LR
A[公用组件 VSearchTable] --> B[手动引入的公用组件 VForm]
A --> C[自动引入的 el-table]
C --> D[slot: 手动引入的 VTableCellContent]
D --> E[自动引入的 el-icon]
B --> F[手动引入的 VCascader]
F --> G[自动引入的 el-cascader]
```

`VTableCellContent` 由于是 `VSearchTable` 的子组件，是需要手动引入的，而 `VTableCellContent` 中有一个 自动引入的 `el-icon`

```html
<el-dropdown placement="bottom-end" @command="handleCommand">
  <el-button>
    操作
    <el-icon class="el-icon--right">
      <icon-ep-arrow-down />
    </el-icon>
  </el-button>
</el-dropdown>
```

`VTableCellContent` 中的 `el-icon` 的样式会覆盖掉 `el-cascader` 中 icon 的样式：
![image](https://user-images.githubusercontent.com/16472134/221745750-2a843093-4ed8-4126-aaad-04e4315973bb.png)

如果 `VTableCellContent` 中的 `el-icon` 改成手动引入，就不会覆盖 `el-cascader` 中 icon 的样式

```js
// src/components/VSearchTable/src/components/VTableCellContent.vue
// 如果手动引入没有问题
import { ElIcon } from 'element-plus'
```

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16472134/221745978-8650a496-51b3-4a0e-944e-215eee807ffe.png">

很明显是组件注册顺序的问题，但我不知道这个是属于 `unplugin-vue-components` 的 bug，还是 `element-plus` 的 bug。

### What is Expected?

自动引入和手动引入共存时， 手动引入的组件中自动引入的 `<el-icon>` 组件不要覆盖其他 el 组件的图标样式

### What is actually happening?

自动引入和手动引入共存时， 手动引入的组件中自动引入的 `<el-icon>` 组件会覆盖其他 el 组件的图标样式

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
我认为和注册顺序没关系哦，应该是`unplugin-vue-components`引用了两套el-icon的样式，如果取消你的V开头组件自动引入呢

**Comment by wangxiaocuo** [comment]
> 但我不知道这个是属于 `unplugin-vue-components` 的 bug，还是 `element-plus` 的 bug。

我试试

**Comment by wangxiaocuo** [comment]
@chenxch 取消 `src/components` 的自动引入改为手动引入，还是一样的问题。demo 也更新了下

<img width="758" alt="image" src="https://user-images.githubusercontent.com/16472134/221785921-dbff24d7-0c2f-49f9-9346-fa0f1520c6d7.png">

**Comment by chenxch** [comment]
晚上我一起看看。

**Comment by chenxch** [comment]
`ElementPlusResolver({exclude: ['ElIcon']})` 添加这个配置项，排除el-icon的加载，因为在其他组件内已经含有el-icon

**Comment by wangxiaocuo** [comment]
> `ElementPlusResolver({exclude: ['ElIcon']})` 添加这个配置项，排除el-icon的加载，因为在其他组件内已经含有el-icon

@chenxch `exclude` 需要是一个正则，从源码看，应该是这么配？但是好像不起作用（bug demo 更新了）

```ts
AutoImport({
  resolvers: [ElementPlusResolver({ exclude: /ElIcon/ })]
})
```

![image](https://user-images.githubusercontent.com/16472134/223345506-7fbda67b-3695-4f75-a5a0-cc640943e5f1.png)

![image](https://user-images.githubusercontent.com/16472134/223346256-906c7e13-3ed5-4116-ab6e-18d039477f41.png)

**Comment by chenxch** [comment]
这个我测试过了呀0 0，你试了么
![image](https://user-images.githubusercontent.com/23251408/223349091-b92ca962-383d-4815-a446-17fe4eb30e53.png)

**Comment by wangxiaocuo** [comment]
啊，不好意思，加错位置了，加到了 `AutoImport` 上......确实有效的。

不过 `exclude ` 写数组 ts 会报错，我还是写正则吧😂

![image](https://user-images.githubusercontent.com/16472134/223350298-4f0bdac1-2146-4e26-abbe-e36cac60cb9c.png)

**Comment by chenxch** [comment]
那我关闭这个问题了哈~~

**Comment by wangxiaocuo** [comment]
好的，感谢回复

**Comment by chenxch** [comment]
不客气

**Comment by wangxiaocuo** [comment]
如果某个页面比较简单，所用到其他 El 组件内没有 `el-icon`，就不会加载 ElIcon 组件：

![image](https://user-images.githubusercontent.com/16472134/227435974-a76eb264-c2a2-4de1-be11-5b22383e7e8f.png)

这种情况，还是需要手动引入一下

```js
import { ElIcon } from 'element-plus'
```
