### ISSUE TITLE
[Style] [select-v2] select-v2 tag悬浮index问题

### ISSUE THREAD

**Issue by CuiCuZn** [element-plus/element-plus#11774]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cbmNvbnN0IGNoZWNrZWQ6IGFueSA9IHJlZihbJzEnLCAnMiddKVxuY29uc3QgdHJlZTogYW55ID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGAke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICBcbiAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJjaGVja2VkXCJcbiAgICA6b3B0aW9ucz1cInRyZWVcIlxuICAgIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oupXCJcbiAgICBzdHlsZT1cIndpZHRoOiAyMjBweDttYXJnaW4tcmlnaHQ6IDEwcHg7XCJcbiAgICBtdWx0aXBsZVxuICAgIGNvbGxhcHNlLXRhZ3NcbiAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICBjbGVhcmFibGVcbiAgLz4gICAgICAgICAgXG4gIDxici8+XG4gIDxici8+XG4gIDxlbC1zZWxlY3QtdjJcbiAgICB2LW1vZGVsPVwiY2hlY2tlZFwiXG4gICAgOm9wdGlvbnM9XCJ0cmVlXCJcbiAgICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMjIwcHg7bWFyZ2luLXJpZ2h0OiAxMHB4O1wiXG4gICAgbXVsdGlwbGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgY29sbGFwc2UtdGFncy10b29sdGlwXG4gICAgY2xlYXJhYmxlXG4gIC8+IFxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

鼠标放到上面select的+1上 悬浮的tag被下面select的tag挡住了内容

### What is Expected?

不遮挡

### What is actually happening?

遮挡

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/103486905/222064275-a9cb2aa1-54c5-46d3-8c72-900ca017049f.png)

**Comment by acyza** [comment]
不是很明白这个地方搞个z-index是干嘛的 https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/select-v2.scss#L273

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

可以把tooltip挂载点移出来或者去掉[这里](https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/select-v2.scss#L273)的z-index。
