### ISSUE TITLE
[Style] $radio-height 设置失效

### ISSUE THREAD

**Issue by linkaiqiyi** [element-plus/element-plus#11770]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-radio-button`
- `el-radio`
- `el-radio-group`

### Reproduction Link

[Link]()

### Steps to reproduce

在 index.scss 中设置如下：
```scss
@forward "element-plus/theme-chalk/src/common/var.scss" with (
    $common-component-size: (
        "large": 40px,
        "default": 32px,
        "small": 28px,
    ),
    $radio-height: (
        "large": 40px,
        "default": 32px,
        "small": 28px,
    )
);

@use "element-plus/theme-chalk/src/index.scss";
```

```vue
<template>
    <el-radio-group v-model="showType" size="small">
        <el-radio-button label="图形"></el-radio-button>
        <el-radio-button label="列表"></el-radio-button>
    </el-radio-group>
</template>

<script setup>
import { ref } from 'vue;
const showType = '图形'
</script>
```

设置 common-component-size 后对于其他组件可以生效。但对 el-radio-button， 当 size="small" 时得到的组件的高度还是 24px，因此再设置了 $radio-height，依然没有生效。

### What is Expected?

设置了 size="small" 的 el-radio-group 的高度为 28px

### What is actually happening?

el-radio-group 的高度依然为 24px

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/87741822/221862675-0ee0b56f-9a0e-45a9-b646-2cabc3526d0d.png)
![image](https://user-images.githubusercontent.com/87741822/221863135-459ed6f3-107f-408c-b268-74b7c83b6f50.png)
![image](https://user-images.githubusercontent.com/87741822/221862919-82896053-1f49-4f9f-8de0-932e734eb823.png)

**Comment by RicardoErii** [comment]
好像radio-group并不是通过CSS变量控制的，是直接计算得出的

**Comment by linkaiqiyi** [comment]
> 好像radio-group并不是通过CSS变量控制的，是直接计算得出的。它是直接根据button设定好的padding值计算得出的，因此好像和button一样，都不支持CSS变量控制

好的，非常感谢，我通过设置 $button-padding-vertical 实现了想要的效果。
![image](https://user-images.githubusercontent.com/87741822/222023471-420e75a9-006e-405c-bcec-c079a7ddfefe.png)
