### ISSUE TITLE
[Docs] [All] 是否可以优化一下element-plus官网站点，十次有八次刷新不进去，得刷好几遍才能加载出来

### ISSUE THREAD

**Issue by SeaCui** [element-plus/element-plus#11789]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome 110.0.5481.177 / macOS 13.1`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

直接访问官网

### What is Expected?

十次成功五次都行，你这十次十次不行，

### What is actually happening?

3.2 15:55刷新十次 十次不行，刷新了十几分钟进不去，无法完全加载，之前也有这种话情况

### Additional comments

_(empty)_

**Comment by SeaCui** [comment]
![image](https://user-images.githubusercontent.com/57389734/222366274-113983e0-7a60-4937-bb9d-feff95b6bad7.png)
![image](https://user-images.githubusercontent.com/57389734/222366403-a33b0fe8-041a-4035-947e-84a26e8b2f34.png)

**Comment by chenxch** [comment]
Recommended [element-plus.org](https://element-plus.org/)
#9196
