### ISSUE TITLE
[Component] [tabs] el-tabs的动态增减标签页缺少添加按钮的插槽

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#11795]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `版本 110.0.5481.78（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmxldCB0YWJJbmRleCA9IDJcbmNvbnN0IGVkaXRhYmxlVGFic1ZhbHVlID0gcmVmKCcyJylcbmNvbnN0IGVkaXRhYmxlVGFicyA9IHJlZihbXG4gIHtcbiAgICB0aXRsZTogJ1RhYiAxJyxcbiAgICBuYW1lOiAnMScsXG4gICAgY29udGVudDogJ1RhYiAxIGNvbnRlbnQnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWIgMicsXG4gICAgbmFtZTogJzInLFxuICAgIGNvbnRlbnQ6ICdUYWIgMiBjb250ZW50JyxcbiAgfSxcbl0pXG5cbmNvbnN0IGhhbmRsZVRhYnNFZGl0ID0gKHRhcmdldE5hbWU6IHN0cmluZywgYWN0aW9uOiAncmVtb3ZlJyB8ICdhZGQnKSA9PiB7XG4gIGlmIChhY3Rpb24gPT09ICdhZGQnKSB7XG4gICAgY29uc3QgbmV3VGFiTmFtZSA9IGAkeysrdGFiSW5kZXh9YFxuICAgIGVkaXRhYmxlVGFicy52YWx1ZS5wdXNoKHtcbiAgICAgIHRpdGxlOiAnTmV3IFRhYicsXG4gICAgICBuYW1lOiBuZXdUYWJOYW1lLFxuICAgICAgY29udGVudDogJ05ldyBUYWIgY29udGVudCcsXG4gICAgfSlcbiAgICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IG5ld1RhYk5hbWVcbiAgfSBlbHNlIGlmIChhY3Rpb24gPT09ICdyZW1vdmUnKSB7XG4gICAgY29uc3QgdGFicyA9IGVkaXRhYmxlVGFicy52YWx1ZVxuICAgIGxldCBhY3RpdmVOYW1lID0gZWRpdGFibGVUYWJzVmFsdWUudmFsdWVcbiAgICBpZiAoYWN0aXZlTmFtZSA9PT0gdGFyZ2V0TmFtZSkge1xuICAgICAgdGFicy5mb3JFYWNoKCh0YWIsIGluZGV4KSA9PiB7XG4gICAgICAgIGlmICh0YWIubmFtZSA9PT0gdGFyZ2V0TmFtZSkge1xuICAgICAgICAgIGNvbnN0IG5leHRUYWIgPSB0YWJzW2luZGV4ICsgMV0gfHwgdGFic1tpbmRleCAtIDFdXG4gICAgICAgICAgaWYgKG5leHRUYWIpIHtcbiAgICAgICAgICAgIGFjdGl2ZU5hbWUgPSBuZXh0VGFiLm5hbWVcbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH0pXG4gICAgfVxuXG4gICAgZWRpdGFibGVUYWJzVmFsdWUudmFsdWUgPSBhY3RpdmVOYW1lXG4gICAgZWRpdGFibGVUYWJzLnZhbHVlID0gdGFicy5maWx0ZXIoKHRhYikgPT4gdGFiLm5hbWUgIT09IHRhcmdldE5hbWUpXG4gIH1cbn1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-tabs右侧的添加按钮不能自定义，缺少个插槽

### What is Expected?

让用户能够自定义右边的添加按钮样式，缺少个插槽

### What is actually happening?

不能自定义

### Additional comments

_(empty)_

**Comment by Denghongjian233** [comment]
没问题呀

**Comment by PeyFon** [comment]
> 没问题呀

![image](https://user-images.githubusercontent.com/60815493/222644525-1b5cd02d-0b80-4f1c-ac1d-d6286bb3f1b5.png)
我是指这个没有插槽让我自定义

**Comment by btea** [comment]
你想要的插槽是整个按钮替换掉还是只替换icon？

**Comment by PeyFon** [comment]
> 你想要的插槽是整个按钮替换掉还是只替换icon？

能替换整个按钮最好

**Comment by btea** [comment]
要整个替换的话，样式或许要大幅度调整。

**Comment by PeyFon** [comment]
> 要整个替换的话，样式或许要大幅度调整。

个人感觉这里能让我换个自定义的el-button按钮就够了，理论上这里的按钮不会也不应该很宽/很高，可能是个icon 又或者只是  添加  俩字，能做到这样就够了。

**Comment by shizhihuaxu** [comment]
同需，求加

**Comment by Hfutsora** [comment]
不如也把 prefix 和 suffix 的slot 一起加上吧。

**Comment by ahei** [comment]
那个按钮太小了, 而且靠那么后, 不容易看到, 能让它靠着前面的tab旁边吗?
