### ISSUE TITLE
[Component] [select-v2] el-select-v2 关闭持久化时动态设置options报错

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#11791]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgIG11bHRpcGxlXG4gICAgOnBlcnNpc3RlbnQ9XCJmYWxzZVwiXG4gICAgQGZvY3VzPVwiZm9jdXNFdmVudFwiXG4gID48L2VsLXNlbGVjdC12Mj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG4gIGNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ107XG5cbiAgY29uc3QgdmFsdWUgPSByZWYoW10pO1xuICBjb25zdCBvcHRpb25zID0gcmVmKFxuICAgIEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gICAgICB2YWx1ZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgICAgIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbiAgICB9KSlcbiAgKTtcblxuICBmdW5jdGlvbiBmb2N1c0V2ZW50KCkge1xuICAgIG9wdGlvbnMudmFsdWUgPSBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gICAgICB9LFxuICAgIF07XG4gIH1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

场景：selectV2的options会受到其他很多依赖的影响，如果使用 `watch`或`computed`去监听那些依赖改变会有性能问题（有很多依赖，每一个依赖更新一次就触发一次明显不好），所以我希望每次打开的时候才动态的去改变options，结果是现在监听focus或者visibleChange事件去动态改变options会报错
![1677750820880](https://user-images.githubusercontent.com/31055355/222394387-5b17adad-7304-42f5-8a19-6f38e9c169fe.jpg)

### What is Expected?

不报错

### What is actually happening?

报错 ： TypeError: Cannot read properties of null (reading 'resetScrollTop')

### Additional comments

顺便说一下希望暴露出 focus()事件或者增加一个show() hide()方法用于手动弹出

**Comment by MaxVilson** [comment]
I had the same problem on a project, did you manage to solve it?

**Comment by nicooprat** [comment]
I think this line should be: https://github.com/element-plus/element-plus/blob/dev/packages/components/select-v2/src/useSelect.ts#L758

```js
    return nextTick(menuRef.value?.resetScrollTop)
```

Because options can change while the menu is close, so the ref is missing (from my understanding of the code).

I think I temporarily fixed it by setting `persistent` prop to `<el-select-v2>` so the menu is always present.

**Comment by kooriookami** [comment]
Fixed
