### ISSUE TITLE
[bug report] when the El select value is empty, it shows true, and when the property clearable is cleared, the value becomes true

### ISSUE THREAD

**Issue by wzohxia** [element-plus/element-plus#1179]
### Element Plus version
1.0.1-beta.18

### OS/Browsers version
win10/Google Chrome 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/wzohxia/pen/VwKXYxb

### Steps to reproduce
1.选择下拉选择项
2.点击清空按钮
3.控件值显示为空

### What is Expected?
清空后为空

### What is actually happening?
清空后为true

**Comment by kooriookami** [comment]
Yes, it's a small bug and will be fixed soon.

**Comment by zazzaz** [comment]
fixed in https://github.com/element-plus/element-plus/pull/1168

**Comment by zazzaz** [comment]
released in 
1.0.1-beta.19
