### ISSUE TITLE
[Component] [tree-select] el-tree-select 筛选后输入框内容不自动清除

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#11794]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.26`
- Browser / OS: `chrome 109`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHZhbHVlID0gcmVmKClcblxuY29uc3Qgc291cmNlRGF0YSA9IFtcbiAge1xuICAgIHZhbHVlOiAnMScsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMS0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnMicsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcyLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMi0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMi0yJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzItMi0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzMnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMy0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzMtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzMtMicsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICczLTItMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuY29uc3QgZGF0YSA9IHJlZihzb3VyY2VEYXRhKTtcbiAgXG5jb25zdCBmaWx0ZXJNZXRob2QgPSAodmFsdWUpID0+IHtcbiAgZGF0YS52YWx1ZSA9IFsuLi5zb3VyY2VEYXRhXS5maWx0ZXIoKGl0ZW0pID0+IGl0ZW0ubGFiZWwuaW5jbHVkZXModmFsdWUpKVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXRyZWUtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIG11bHRpcGxlXG4gICAgOmZpbHRlci1tZXRob2Q9XCJmaWx0ZXJNZXRob2RcIlxuICAgIGZpbHRlcmFibGVcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

下拉列表输入2

### What is Expected?

选择一个选项后输入框的“2”会被清空

### What is actually happening?

搜索输入框“2”没有被清空

### Additional comments

el-select这个会清空的。

**Comment by godxiaoji** [comment]
没发现有啥问题，`el-tree-select` 和 `el-select` 都是在 "失焦" 的时候清空。

**Comment by chenxch** [comment]
可以看一下文档哦，有提供了reserve-keyword

**Comment by huzedong2015** [comment]
> 没发现有啥问题，`el-tree-select` 和 `el-select` 都是在 "失焦" 的时候清空。

就是选择一项后 要清空。@chenxch 回答了。

**Comment by huzedong2015** [comment]
> 可以看一下文档哦，有提供了reserve-keyword

是的。感谢

**Comment by huzedong2015** [comment]
不过刚好测出一个别的问题，链接还是上面那个
![image](https://user-images.githubusercontent.com/14806813/222640990-82051475-15a4-4a9a-974b-284e4a01c029.png)
1、打开下拉列表
2、依次选择第一个、第二个
