### ISSUE TITLE
[select] el-select v-model 给默认值时，组件无法回显 label

### ISSUE THREAD

**Issue by TheHumanLeader** [element-plus/element-plus#11800]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmNsYXNzIE1vZGVse1xuXHRzZWxlY3QgPSAwO1xufVxuICBcbiBjbGFzcyBPcHRpb257XG5cdHZhbHVlO1xuXHRuYW1lO1xuXHRjb25zdHJ1Y3Rvcih2YWx1ZSxuYW1lKXtcblx0XHR0aGlzLnZhbHVlID0gdmFsdWU7XG5cdFx0dGhpcy5uYW1lID0gbmFtZTtcblx0fVxufVxuICBcbmV4cG9ydCBkZWZhdWx0IHtcbiAgZGF0YSgpe1xuICAgIHJldHVybiB7XG4gICAgICBtb2RlbDogbmV3IE1vZGVsKCksXG4gICAgICBvcHRpb25zOltcbiAgICAgICAgbmV3IE9wdGlvbigwLCdBJyksXG4gICAgICAgIG5ldyBPcHRpb24oMSwnQicpLFxuICAgICAgICBuZXcgT3B0aW9uKDIsJ0MnKSxcbiAgICAgIF1cblxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwibW9kZWwuc2VsZWN0XCIgdmFsdWUta2V5PVwidmFsdWVcIj5cblx0XHQ8dGVtcGxhdGUgdi1zbG90OnByZWZpeD5cblx0XHRcdDxkaXYgY2xhc3M9XCJlbC1zZWxlY3QtcHJlcGVuZFwiPlxuXHRcdFx0XHTlrZfmrrXnsbvlnotcblx0XHRcdDwvZGl2PlxuXHRcdDwvdGVtcGxhdGU+XG5cdFx0PGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG5cdFx0XHQ6bGFiZWw9XCJpdGVtLm5hbWVcIiA6dmFsdWU9XCJpdGVtLm5hbWVcIi8+XG48L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

如链接所示，没有回显 label

### What is Expected?

回显 label，对 vue2 语法的支持。

### What is actually happening?

回显 label，对 vue2 语法的支持。

### Additional comments

vue3 setup 的确很方便，但是维护起来就像是曾经的 dom ， jq 时代一样，因为没有分离参数与函数反而乱糟糟的，所以vue3即便是有了 setup 语法糖也没有放弃 原来的灵魂结构。

**Comment by Dream552b** [comment]
请问下这个问题解决了么， 上面没看到解决方式。我现在遇到这个问题了。 求解

**Comment by Dream552b** [comment]
解决了， v-model绑定的值应该是字符串类型，Number类型会导致初始化el-select绑定label数据回显失败
