### ISSUE TITLE
[TypeScript] [message, message-box] when tsconfig.json set moduleResolution to nodenext or bundler, ElMessage can not be imported.

### ISSUE THREAD

**Issue by wangxdmm** [element-plus/element-plus#11818]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.33`
- Browser / OS: `110.0.5481.100（正式版本） (x86_64)/mac os 12.6.3 `
- Build Tool: `Other`

### Related Component

- `el-message`
- `el-message-box`

### Reproduction Link

[Github Repo](https://github.com/wangxdmm/el-exports-mini-rep)

### Steps to reproduce

```shell
# 1.
pnpm install

# I set tsconfig.json (moduleResolution to nodenext)
# open index.ts we can see:

# Module '"element-plus"' has no exported member 'ElMessage'. Did you mean to use 'import ElMessage from "element-plus"' instead?ts


# 2. replace by new exports content
pnpm replace

# the error will remove

# 3.

pnpm restore

# the error will show again

```

### What is Expected?

no error

### What is actually happening?

has error

### Additional comments

_(empty)_

**Comment by ModyQyW** [comment]
`el-notification` is also related.

**Comment by aknot242** [comment]
`el-button` and `el-dialog` also appear to be experiencing this error.

**Comment by FabianMontoya** [comment]
I should be realated with a break change into the TS versión of `TypeScript` or `vue-tsc` or `@vue/tsconfig`, I can run my project whit out error with the next versions:

```json
"dependencies": {
  "element-plus": "^2.2.27",
  "vue": "^3.2.45"
}
"devDependencies": {
  "@vue/tsconfig": "^0.1.3",
  "typescript": "~4.7.4",
  "vite": "^3.2.4",
  "vue-tsc": "^1.0.9"
}
```

**Comment by FabianMontoya** [comment]
The problem is with `typescript > 4.9.4`
for that reason we can not update `@vue/tsconfig` to an upper version than `0.1.3` and obviously `typescript` neither.

**Comment by ModyQyW** [comment]
> The problem is with `typescript > 4.9.4` for that reason we can not update `@vue/tsconfig` to an upper version than `0.1.3` and obviously `typescript` neither.

@FabianMontoya You can. But you have to set `compilerOptions.moduleResolution: "node"` in `tsconfig` yourself.

**Comment by aknot242** [comment]
> > The problem is with `typescript > 4.9.4` for that reason we can not update `@vue/tsconfig` to an upper version than `0.1.3` and obviously `typescript` neither.
> 
> @FabianMontoya You can.
> 
> This problem is caused by `compilerOptions.moduleResolution: "bundler"` and `element-plus` `exports` field in `package.json`.
> 
> If you want to use `typescript@5` and `@vue/tsconfig@0.3` you have to set `compilerOptions.moduleResolution: "node"` in `tsconfig.json` to override `@vue/tsconfig@0.3` config.

Thank you for posting this, @ModyQyW . This solution worked for me on TypeScript 5.04.

**Comment by toplinuxsir** [comment]
@aknot242 
I have use typescript@5 and @vue/tsconfig@0.3 
tsconfig.json
```
{
   "compilerOptions.moduleResolution": "node",

  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```
npm run build  error ,not working
```
src/App.vue:4:10 - error TS2614: Module '"element-plus"' has no exported member 'ElMenu'. Did you mean to use 'import ElMenu from "element-plus"'
```

How to resolve ? Thanks!

**Comment by xiefangqing** [comment]
src/utils/index.ts:1:10 - error TS2614: Module '"element-plus"' has no exported member 'ElMessage'. Did you mean to use 'import ElMessage from "element-plus"' instead?

1 import { ElMessage } from 'element-plus';

**Comment by xiefangqing** [comment]
依赖： 
```
 "dependencies": {
    "@element-plus/icons-vue": "^2.1.0",
    "element-plus": "^2.3.4",
    "vue": "^3.2.47",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@types/node": "^18.16.3",
    "@vitejs/plugin-vue": "^4.1.0",
    "sass": "^1.62.1",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vue-tsc": "^1.4.2"
  }
```

import { ElMessage } from 'element-plus';

报错：
error TS2614: Module '"element-plus"' has no exported member 'ElMessage'. Did you mean to use 'import ElMessage from "element-plus"' instead?

**Comment by aknot242** [comment]
> @aknot242 @ModyQyW I have use typescript@5 and @vue/tsconfig@0.3 tsconfig.json
> 
> ```
> {
>    "compilerOptions.moduleResolution": "node",
> 
>   "files": [],
>   "references": [
>     {
>       "path": "./tsconfig.node.json"
>     },
>     {
>       "path": "./tsconfig.app.json"
>     },
>     {
>       "path": "./tsconfig.vitest.json"
>     }
>   ]
> }
> ```
> 
> npm run build error ,not working
> 
> ```
> src/App.vue:4:10 - error TS2614: Module '"element-plus"' has no exported member 'ElMenu'. Did you mean to use 'import ElMenu from "element-plus"'
> ```
> 
> How to resolve ? Thanks!

Try putting the following in each of your tsconfig files (`tsconfig.node.json`, `tsconfig.app.json`, `tsconfig.vitest.json`)

```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  }
}
```

**Comment by toplinuxsir** [comment]
@aknot242 Thanks! It works!

**Comment by Sheepeer** [comment]
@aknot242  Sry the way not work for me, or could U pls help to see is there any error with my configration?
![image](https://github.com/element-plus/element-plus/assets/78125933/34cdc036-cee8-4417-9c23-d64f2a862365)
![image](https://github.com/element-plus/element-plus/assets/78125933/5f812597-bf4b-439e-a373-b9b918d5ccd9)

**Comment by ModyQyW** [comment]
> > @aknot242 @ModyQyW I have use typescript@5 and @vue/tsconfig@0.3 tsconfig.json
> > 
> > ```
> > {
> >    "compilerOptions.moduleResolution": "node",
> > 
> >   "files": [],
> >   "references": [
> >     {
> >       "path": "./tsconfig.node.json"
> >     },
> >     {
> >       "path": "./tsconfig.app.json"
> >     },
> >     {
> >       "path": "./tsconfig.vitest.json"
> >     }
> >   ]
> > }
> > ```
> > 
> > npm run build error ,not working
> > 
> > ```
> > src/App.vue:4:10 - error TS2614: Module '"element-plus"' has no exported member 'ElMenu'. Did you mean to use 'import ElMenu from "element-plus"'
> > ```
> > 
> > How to resolve ? Thanks!
> 
> @toplinuxsir try putting the following in each of your tsconfig files (`tsconfig.node.json`, `tsconfig.app.json`, `tsconfig.vitest.json`)
> 
> ```json
> {
>   "compilerOptions": {
>     "moduleResolution": "node"
>   }
> }
> ```

@Sheepeer Is it not worked for you？

**Comment by Sheepeer** [comment]
> 

Yes, I put it in all my three tsconfig files and there is no changement: 
![image](https://github.com/element-plus/element-plus/assets/78125933/fa70ca1d-cbb7-477e-a95a-6dabc6c4906e)
![image](https://github.com/element-plus/element-plus/assets/78125933/425986d8-d6f9-4d8f-8adc-3420b386198d)
![image](https://github.com/element-plus/element-plus/assets/78125933/7ce463c5-5ec3-496e-bd68-db97b5917101)
![image](https://github.com/element-plus/element-plus/assets/78125933/0cb99176-c3cb-48f7-880b-0366e7cf6594)
![image](https://github.com/element-plus/element-plus/assets/78125933/42863dc8-61da-4188-96d8-4be454a1022d)

**Comment by ModyQyW** [comment]
> Yes, I put it in all my three tsconfig files and there is no changement:

@Sheepeer Have you reloaded vscode window or restarted vscode?

**Comment by Sheepeer** [comment]
> > Yes, I put it in all my three tsconfig files and there is no changement:
> 
> @Sheepeer Have you reloaded vscode window or restarted vscode?

OHHH I forgot! So much Thx!!!

**Comment by Dreamacro** [comment]
Any progress?

Once `"moduleResolution": "node"` is used, `import ElementPlus from 'unplugin-element-plus/vite'` in `vite.config.ts` will report another import error.

**Comment by slimvan** [comment]
> 

Node

**Comment by slimvan** [comment]
> > 
> 
> Yes, I put it in all my three tsconfig files and there is no changement: ![image](https://user-images.githubusercontent.com/78125933/238851654-fa70ca1d-cbb7-477e-a95a-6dabc6c4906e.png) ![image](https://user-images.githubusercontent.com/78125933/238851908-425986d8-d6f9-4d8f-8adc-3420b386198d.png) ![image](https://user-images.githubusercontent.com/78125933/238851964-7ce463c5-5ec3-496e-bd68-db97b5917101.png) ![image](https://user-images.githubusercontent.com/78125933/238852086-0cb99176-c3cb-48f7-880b-0366e7cf6594.png) ![image](https://user-images.githubusercontent.com/78125933/238852128-42863dc8-61da-4188-96d8-4be454a1022d.png)

Node

**Comment by zhuying547** [comment]
#12602 问题解决了，但是你的pr怎么直接选择关闭的？

**Comment by adminChina** [comment]
> 

good, Simply modify tsconfig.app.json
