### ISSUE TITLE
[Component] [popover] el-popover组件的propper-style属性没有生效

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#11813]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/XWPgWMG)

### Steps to reproduce

1.打开链接
2.将鼠标移到按钮上，可以看到显示的popover背景颜色没有改为红色

### What is Expected?

propper-style属性生效

### What is actually happening?

propper-style属性没有生效

### Additional comments

_(empty)_

**Comment by godxiaoji** [comment]
属性翻译错误了，应为`popper-style`。  具体可以查看[英文文档](https://element-plus.org/en-US/component/popover.html#attributes)。

**Comment by hzf-666** [comment]
> 属性翻译错误了，应为`popper-style`。 具体可以查看[英文文档](https://element-plus.org/en-US/component/popover.html#attributes)。

好的，没注意到
