### ISSUE TITLE
[Component] [table-v2] Virtualized Table  Column  属性class  没有添加上

### ISSUE THREAD

**Issue by KanLai** [element-plus/element-plus#11810]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.33`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtdjJcbiAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOndpZHRoPVwiNzAwXCJcbiAgICA6aGVpZ2h0PVwiNDAwXCJcbiAgICBmaXhlZFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGdlbmVyYXRlQ29sdW1ucyA9IChsZW5ndGggPSAxMCwgcHJlZml4ID0gJ2NvbHVtbi0nLCBwcm9wcz86IGFueSkgPT5cbiAgQXJyYXkuZnJvbSh7IGxlbmd0aCB9KS5tYXAoKF8sIGNvbHVtbkluZGV4KSA9PiAoe1xuICAgIC4uLnByb3BzLFxuICAgIGtleTogYCR7cHJlZml4fSR7Y29sdW1uSW5kZXh9YCxcbiAgICBkYXRhS2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIHRpdGxlOiBgQ29sdW1uICR7Y29sdW1uSW5kZXh9YCxcbiAgICB3aWR0aDogMTUwLFxuICAgIGNsYXNzOlwidGVzdGJveFwiXG4gIH0pKVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoXG4gIGNvbHVtbnM6IFJldHVyblR5cGU8dHlwZW9mIGdlbmVyYXRlQ29sdW1ucz4sXG4gIGxlbmd0aCA9IDIwMCxcbiAgcHJlZml4ID0gJ3Jvdy0nXG4pID0+XG4gIEFycmF5LmZyb20oeyBsZW5ndGggfSkubWFwKChfLCByb3dJbmRleCkgPT4ge1xuICAgIHJldHVybiBjb2x1bW5zLnJlZHVjZShcbiAgICAgIChyb3dEYXRhLCBjb2x1bW4sIGNvbHVtbkluZGV4KSA9PiB7XG4gICAgICAgIHJvd0RhdGFbY29sdW1uLmRhdGFLZXldID0gYFJvdyAke3Jvd0luZGV4fSAtIENvbCAke2NvbHVtbkluZGV4fWBcbiAgICAgICAgcmV0dXJuIHJvd0RhdGFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiBgJHtwcmVmaXh9JHtyb3dJbmRleH1gLFxuICAgICAgICBwYXJlbnRJZDogbnVsbCxcbiAgICAgIH1cbiAgICApXG4gIH0pXG5cbmNvbnN0IGNvbHVtbnMgPSBnZW5lcmF0ZUNvbHVtbnMoMTApXG5jb25zdCBkYXRhID0gZ2VuZXJhdGVEYXRhKGNvbHVtbnMsIDEwMDApXG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Virtualized Table  Column  属性class  没有添加上

### What is Expected?

增加上啊

### What is actually happening?

Virtualized Table  Column  属性class  没有添加上

### Additional comments

_(empty)_

**Comment by ryuhangyeong** [comment]
Can't you solve your problem using `row-class` props?

https://element-plus.org/en-US/component/table-v2.html#table-with-status

**Comment by KanLai** [comment]
> Can't you solve your problem using `row-class` props?
> 
> https://element-plus.org/en-US/component/table-v2.html#table-with-status
> 
> or
> 
> https://element-plus.org/en-US/component/table-v2.html#table-with-status

这个属性 是 整个行的样式，可以生效。除非加上fixed  才会单独一个列生效。 Column[] 里面的style会生效。可以解决我的问题，但是会有很多重复样式代码。希望能加上

**Comment by KanLai** [comment]
![iShot_2023-03-04_11 31 13](https://user-images.githubusercontent.com/80996243/222873735-165ba0f1-58e6-4b4a-b13e-b95041602cb9.png)
