### ISSUE TITLE
[Component] [loading] 2.2.33版本v-loading使用时报inject warning

### ISSUE THREAD

**Issue by liijtedpibz0535** [element-plus/element-plus#11823]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.33`
- Browser / OS: `Chrome 110.0.5481.177 (Official Build) (arm64) / macOS 13.2.1 (22D68)`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBsb2FkaW5nID0gcmVmKHRydWUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiAzMDBweDsgd2lkdGg6IDMwMHB4OyBiYWNrZ3JvdW5kOiBncmVlblwiIHYtbG9hZGluZz1cImxvYWRpbmdcIj48L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue'
const loading = ref(true)
</script>

<template>
  <div style="height: 300px; width: 300px; background: green" v-loading="loading"></div>
</template>
```

### What is Expected?

正常loading

### What is actually happening?

console里面报warning：
inject() can only be used inside setup() or functional components.

### Additional comments

_(empty)_

**Comment by hansonfang** [comment]
same here

**Comment by TothingWay** [comment]
same here

**Comment by TothingWay** [comment]
@jw-foss

**Comment by WangJincheng4869** [comment]
我也遇到了同样的问题
![image](https://user-images.githubusercontent.com/41162158/223056117-c2b4b33e-f9fb-46b2-8ff1-3abd52fd8280.png)

**Comment by Vadizar** [comment]
same here

**Comment by jw-foss** [comment]
Noted, sorry for the buzz 🙇 I'll make a mend on this ASAP

**Comment by jw-foss** [comment]
A [fix](https://github.com/element-plus/element-plus/pull/11847) is on the way

**Comment by jw-foss** [comment]
Update the version to see if this problem remains, if so, please do not hesitate to reach out, sorry for the trouble.

**Comment by TothingWay** [comment]
The size attribute of el-config-provider does not take effect on Message Box. @jw-foss

**Comment by jw-foss** [comment]
> The size attribute of el-config-provider does not take effect on Message Box. @jw-foss

Oh, sorry I missed that one 😢 I'll fix it ASAP

**Comment by TothingWay** [comment]
And el-tree-select will throw a warning: [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by jw-foss** [comment]
@TothingWay noted, these are different issues, would you mind creating another one for tracking it? I saw them a lot in the tests, and we will make sure this will be fixed.

**Comment by TothingWay** [comment]
No problem
