### ISSUE TITLE
[Docs] [All] 文档网站太不稳定了

### ISSUE THREAD

**Issue by LiuXIn011** [element-plus/element-plus#11827]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.33`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/)

### Steps to reproduce

网站很卡，点击菜单很容易就卡死了，页面也经常pending。

### What is Expected?

流畅访问

### What is actually happening?

网站很卡，点击菜单很容易就卡死了，页面也经常pending。

### Additional comments

_(empty)_

**Comment by LiuXIn011** [comment]
好像没有配置try_file页面刷新就会404

**Comment by zoevie-cloud** [comment]
确实，他们的官网，动不动，就是打不开，然后经常报 404

![image](https://user-images.githubusercontent.com/29449862/223008264-aa8bc417-d06f-4c82-be96-8a7d9e906d8f.png)

**Comment by chenxch** [comment]
Recommended [element-plus.org](https://element-plus.org/)
https://github.com/element-plus/element-plus/issues/9196
