### ISSUE TITLE
[Component] [loading] el-loading 使用指令方式时，当绑定响应式值为true时，控制会报警告 vue@next:1616 [Vue warn]: inject() can only be used inside setup() or functional components.

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#11835]
![M_L7 M{S64J_Y{GSB94C}EO](https://user-images.githubusercontent.com/55825301/223052110-ddb89781-68f5-4760-904d-2ea311459d28.png)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.33`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/bGxrGmY)

### Steps to reproduce

1.打开链接
2.按F12打开控制台
3.点击切换按钮，发现控制台出现警告

### What is Expected?

不想出现警告信息

### What is actually happening?

控制台出现警告信息

### Additional comments

我想知道这个警告信息是否是正常的，虽然不影响使用功能

**Comment by chenxch** [comment]
induction #11823
