### ISSUE TITLE
[Component] [upload] upload accept 限制无效

### ISSUE THREAD

**Issue by daiyuelin** [element-plus/element-plus#11844]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.28`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICBtdWx0aXBsZVxuICAgIDpvbi1wcmV2aWV3PVwiaGFuZGxlUHJldmlld1wiXG4gICAgOm9uLXJlbW92ZT1cImhhbmRsZVJlbW92ZVwiXG4gICAgOmJlZm9yZS1yZW1vdmU9XCJiZWZvcmVSZW1vdmVcIlxuICAgIDpsaW1pdD1cIjNcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbXBvcnQgdHlwZSB7IFVwbG9hZFByb3BzLCBVcGxvYWRVc2VyRmlsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZmlsZUxpc3QgPSByZWY8VXBsb2FkVXNlckZpbGVbXT4oW1xuICB7XG4gICAgbmFtZTogJ2VsZW1lbnQtcGx1cy1sb2dvLnN2ZycsXG4gICAgdXJsOiAnaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmcnLFxuICB9LFxuICB7XG4gICAgbmFtZTogJ2VsZW1lbnQtcGx1cy1sb2dvMi5zdmcnLFxuICAgIHVybDogJ2h0dHBzOi8vZWxlbWVudC1wbHVzLm9yZy9pbWFnZXMvZWxlbWVudC1wbHVzLWxvZ28uc3ZnJyxcbiAgfSxcbl0pXG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAoZmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2coZmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9ICh1cGxvYWRGaWxlKSA9PiB7XG4gIGNvbnNvbGUubG9nKHVwbG9hZEZpbGUpXG59XG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIEVsTWVzc2FnZS53YXJuaW5nKFxuICAgIGBUaGUgbGltaXQgaXMgMywgeW91IHNlbGVjdGVkICR7ZmlsZXMubGVuZ3RofSBmaWxlcyB0aGlzIHRpbWUsIGFkZCB1cCB0byAke1xuICAgICAgZmlsZXMubGVuZ3RoICsgdXBsb2FkRmlsZXMubGVuZ3RoXG4gICAgfSB0b3RhbGx5YFxuICApXG59XG5cbmNvbnN0IGJlZm9yZVJlbW92ZTogVXBsb2FkUHJvcHNbJ2JlZm9yZVJlbW92ZSddID0gKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIHJldHVybiBFbE1lc3NhZ2VCb3guY29uZmlybShcbiAgICBgQ2FuY2VsIHRoZSB0cmFuc2ZlcnQgb2YgJHt1cGxvYWRGaWxlLm5hbWV9ID9gXG4gICkudGhlbihcbiAgICAoKSA9PiB0cnVlLFxuICAgICgpID0+IGZhbHNlXG4gIClcbn1cbjwvc2NyaXB0PlxuIn0=)

### Steps to reproduce

accept="image/png,image/jpg,image/jpeg" 无效

### What is Expected?

accept="image/png,image/jpg,image/jpeg"不能选择其他文件

### What is actually happening?

能选择其他文件

### Additional comments

_(empty)_

**Comment by co2color** [comment]
accept只是一个期望。。并不是严格限制你不能选。。你选svg当然是可以的，这个需要你自己写判断。

mdn：
accept 属性不验证所选文件的类型；它只是为浏览器提供提示来引导用户选择正确的文件类型。用户仍然可以（在大多数情况下）在文件选择器中切换一个选项，使其能够覆盖此选项并选择他们希望的任何文件，然后选择不正确的文件类型。

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/file#%E5%94%AF%E4%B8%80%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B%E8%AF%B4%E6%98%8E%E7%AC%A6
