### ISSUE TITLE
[i18n] [All] 官网zh-cn无法访问404-503

### ISSUE THREAD

**Issue by ottocsb** [element-plus/element-plus#11857]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.34`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/)

### Steps to reproduce

打开官网，zh-cn环境炸了

### What is Expected?

正常访问

### What is actually happening?

无法访问404

### Additional comments

不行租台便宜的，gitee的服务不敢恭维，不炸平时经常503加载慢批爆

**Comment by qiaozhu** [comment]
+1
gitee三天两头访问不到

**Comment by rftughniwwe** [comment]
+1 要么经常卡要么就是访问不到

**Comment by weiheli** [comment]
老毛病了，Resource not found，404，502，503，处处透露着不靠谱，Vue 3 很香，就是生态差了点

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/5600837/223301879-4805a0d4-28e8-496b-b56f-ab26fb8d2eba.png">
<img width="310" alt="image" src="https://user-images.githubusercontent.com/5600837/223301922-a427640b-8bac-4b9d-b49c-f4f197b94a9d.png">
<img width="304" alt="image" src="https://user-images.githubusercontent.com/5600837/223301986-2102569f-2232-4843-a0c3-92affa43fc38.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/5600837/223302016-e1b476d3-6735-46f1-92c2-2e3e9b700bb7.png">

**Comment by jw-foss** [comment]
部署的镜像正在 CDN 上预热，Gitee 的服务我们也没办法，实在抱歉。大概 10 - 30 分钟吧。

**Comment by kingzton** [comment]
貌似可以本地部署访问，我试了，使用gh-pages部署后能正常使用，参考 这个地址上的配置是可行的http://www.dtmao.cc/JavaScript/61660.html 科技改变生活

**Comment by kingzton** [comment]
这种方式貌似可以，使用本地部署访问，我试了，使用gh-pages分支部署后能正常使用，参考 这个地址上的配置是可行的http://www.dtmao.cc/JavaScript/61660.html 科技改变生活

**Comment by whj73996** [comment]
国内镜像节点好像不太行...用这个:
https://element-plus.org/

**Comment by ottocsb** [comment]
> 国内镜像节点好像不太行...用这个: https://element-plus.org/

上次出现的情况是```org```和```gitee```的中文页都无法访问
