### ISSUE TITLE
[bug report] tree: data cannot respond

### ISSUE THREAD

**Issue by UncleCarlos** [element-plus/element-plus#1185]
### Element Plus version
1.0.1-beta.19

### OS/Browsers version
Windows 10/ Chrome 87

### Vue version
3.0.5

### Reproduction Link
https://github.com/unclecarlos/ep-tree

### Steps to reproduce
```html
<el-button @click="fetchData">fetch data</el-button>
<el-tree :data="treeData"></el-tree>
```
```typescript
export default defineComponent({
  name: 'App',
  setup () {
    const treeData = reactive([{ label: 'origin0', id: 0 }])
    const fetchData = () => {
      const data = [
        { label: 'new label1', id: 1 },
        { label: 'new label2', id: 2 },
        { label: 'new label3', id: 3 }
      ]
      setTimeout(() => {
        treeData.splice(0, treeData.length, ...data)
        treeData.push({ label: 'push', id: 10 })
        console.log('App', treeData)
      }, 1000)
    }
    return {
      treeData,
      fetchData
    }
  }
})
```

### What is actually happening?
点button更新数组，Tree没响应

**Comment by UncleCarlos** [comment]
https://github.com/unclecarlos/ep-tree

![image](https://github.com/UncleCarlos/ep-tree/blob/master/demo.gif?raw=true)

更新到1.0.1-beta.20还是这样
@BeADre @JeremyWuuuuu

**Comment by BeADre** [comment]
> https://github.com/unclecarlos/ep-tree
> 
> ![image](https://github.com/UncleCarlos/ep-tree/blob/master/demo.gif?raw=true)
> 
> 更新到1.0.1-beta.20还是这样
> @BeADre @JeremyWuuuuu

This version does not contain the fixed code
