### ISSUE TITLE
[Docs] [All] gitee上Element-Plus官网文档时长崩溃打不开或404

### ISSUE THREAD

**Issue by tianzhihen121** [element-plus/element-plus#11855]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.34`
- Browser / OS: `Chrome 110.0.5481.96 / Windows 10`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/)

### Steps to reproduce

浏览器输入https://element-plus.gitee.io/，点击组件，刷新几次就会出现

### What is Expected?

文档正常显示

### What is actually happening?

文档常常崩溃看不了

### Additional comments

如果Gitee上不稳定，建议先移除

![image](https://user-images.githubusercontent.com/49887028/223294286-0079f269-5c34-4a07-a1c4-b91eba026030.png)

**Comment by WangJincheng4869** [comment]
哈哈哈哈！淡定，这不是经常会出现的事情吗？两个网站轮着用就行了。

**Comment by masual95** [comment]
> 哈哈哈哈！淡定，这不是经常会出现的事情吗？两个网站轮着用就行了。

两个网站都不行喽，新项目还是用别的框架吧

**Comment by WangJincheng4869** [comment]
@masual95 开源项目，很多人都是用爱发电，多多担待...

**Comment by masual95** [comment]
> @masual95 开源项目，很多人都是用爱发电，多多担待...
你说的没错，但是看不了文档这种事情还是蛮头疼的。
另外项目issue900+，PR200+，一度让人怀疑团队是不是仍然在维护。

**Comment by WangJincheng4869** [comment]
@masual95 项目比较活跃，closed 更多

**Comment by co2color** [comment]
> 

如果是10个open和40个close，还会怀疑吗？目前大概就是1:4，我觉得还好

**Comment by ddmy** [comment]
中文官方 文档是谁在维护，抱歉，这个项目的星星让我在浏览中文文档时，时常让我觉得elemeplus是一个玩具

**Comment by jw-foss** [comment]
部署的镜像正在 CDN 上预热，Gitee 的服务我们也没办法，实在抱歉。大概 10 - 30 分钟吧。

**Comment by jw-foss** [comment]
> 中文官方 文档是谁在维护，抱歉，这个项目的星星让我在浏览中文文档时，时常让我觉得elemeplus是一个玩具

给你带来不好的体验实在抱歉，我们目前人手比较有限，不知道您是否对维护文档这部分的内容感兴趣，如果感兴趣的话可以留一个联系方式 :bow:

**Comment by ST-log** [comment]
请问拉下仓库之后可以怎么配置中文文档

**Comment by co2color** [comment]
> 请问拉下仓库之后可以怎么配置中文文档

看package.json就有写。
`pnpm i`  `pnpm docs:dev`  `pnpm docs:build`

项目在根目录的docs内

**Comment by co2color** [comment]
> 你好，没有切换语言选项，只看到en-US这个文件夹，是因为仓库中没有加入吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月7日(星期二) 下午3:26 收件人: ***@***.***&gt;; 抄送: "@***@***.***&gt;; ***@***.***&gt;; 主题: Re: [element-plus/element-plus] [Docs] [All] gitee上Element-Plus官网文档时长崩溃打不开或404 (Issue #11855) 请问拉下仓库之后可以怎么配置中文文档 看package.json就有写。 pnpm i pnpm docs:dev pnpm docs:build 项目在根目录的docs内 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

切换gh-pages分支。
https://github.com/element-plus/element-plus/tree/gh-pages
