### ISSUE TITLE
[Component] [tree] el-dialog打开后，el-tree的ref值为null，close关闭后，第二次打开，el-tree的ref有值了，请看下咋回事

### ISSUE THREAD

**Issue by zhizaiyunxiao** [element-plus/element-plus#11867]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.28`
- Browser / OS: `Google Chrome	109.0.5414.120 (正式版本) （64 位） (cohort: Stable)/操作系统	Windows 10 Version 21H2 (Build 19044.2604)`
- Build Tool: `Vue CLI`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7ZGVmaW5lQ29tcG9uZW50LCByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHRyZWVSZWY9cmVmKClcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuICBleHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICAgIHNldHVwKHByb3BzLCB7IGVtaXQgfSkge1xuICAgICAgY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gICAgICAgIHRyZWVSZWY6IG51bGwsXG4gICAgICAgIGRhdGE6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMSxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIGlkOiA0LFxuICAgICAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgaWQ6IDksXG4gICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgaWQ6IDEwLFxuICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfSxcbiAgICAgICAgICBdLFxuICAgICAgICBkZWZhdWx0UHJvcHM6IHtcbiAgICAgICAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICAgICAgICBsYWJlbDogJ2xhYmVsJyxcbiAgICAgICAgfVxuICAgICAgfSlcbiAgICAgIFxuICAgICAgXG5cbiAgICAgIHJldHVybiB7XG4gICAgICAgIC4uLnRvUmVmcyhzdGF0ZSlcbiAgICAgIH1cbiAgICB9XG4gIH0pXG4gIGFsZXJ0KHRyZWVSZWYudmFsdWUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gICAgICAgICAgPGVsLXRyZWVcbiAgICAgICAgICAgIHJlZj1cInRyZWVSZWZcIlxuICAgICAgICAgICAgOmRhdGE9XCJkYXRhXCJcbiAgICAgICAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgICAgICAgICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cIltdXCJcbiAgICAgICAgICAgIG5vZGUta2V5PVwiZnVuY3Rpb25Db2RlXCJcbiAgICAgICAgICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gICAgICAgICAgICBzaG93LWNoZWNrYm94XG4gICAgICAgICAgLz5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

dd

### What is Expected?

el-dialog首次打开后，el-tree的ref值不能为空。

### What is actually happening?

首次el-dialog打开后，el-tree的ref值为空，无法setChecked选中。第二次或第三次el-dialog打开，ref值出来了。

### Additional comments

_(empty)_

**Comment by zhizaiyunxiao** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7ZGVmaW5lQ29tcG9uZW50LHJlYWN0aXZlLHRvUmVmcywgIHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgdHJlZVJlZj1yZWYoKVxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG4gIGV4cG9ydCBkZWZhdWx0IGRlZmluZUNvbXBvbmVudCh7XG4gICAgc2V0dXAocHJvcHMsIHsgZW1pdCB9KSB7XG4gICAgICBjb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgICAgICAgdHJlZVJlZjogbnVsbCxcbiAgICAgICAgZGF0YTogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAxLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgaWQ6IDQsXG4gICAgICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICBpZDogOSxcbiAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTInLFxuICAgICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgXSxcbiAgICAgICAgICB9LFxuICAgICAgICAgIF0sXG4gICAgICAgIGRlZmF1bHRQcm9wczoge1xuICAgICAgICAgIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICAgICAgICAgIGxhYmVsOiAnbGFiZWwnLFxuICAgICAgICB9XG4gICAgICB9KVxuICAgICAgXG4gICAgICBcblxuICAgICAgcmV0dXJuIHtcbiAgICAgICAgLi4udG9SZWZzKHN0YXRlKVxuICAgICAgfVxuICAgIH1cbiAgfSlcbiAgYWxlcnQodHJlZVJlZi52YWx1ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgICAgICAgICA8ZWwtdHJlZVxuICAgICAgICAgICAgcmVmPVwidHJlZVJlZlwiXG4gICAgICAgICAgICA6ZGF0YT1cImRhdGFcIlxuICAgICAgICAgICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgICAgICAgICA6ZGVmYXVsdC1leHBhbmRlZC1rZXlzPVwiW11cIlxuICAgICAgICAgICAgbm9kZS1rZXk9XCJmdW5jdGlvbkNvZGVcIlxuICAgICAgICAgICAgOnByb3BzPVwiZGVmYXVsdFByb3BzXCJcbiAgICAgICAgICAgIHNob3ctY2hlY2tib3hcbiAgICAgICAgICAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by co2color** [comment]
1.你提供的playground和你What is Expected?的不符。
2.在你的playground里，你是在setup中进行log的，此时无法拿到dom。可以在onMounted里面进行获取。

**Comment by Syt100** [comment]
参考https://cn.vuejs.org/guide/essentials/reactivity-fundamentals.html#dom-update-timing
请使用nextTick来访问treeRef.value，在模板渲染前，treeRef为undefined
```
nextTick(() => {
  // 访问更新后的 DOM
  console.log(treeRef.value)
})
```

**Comment by jw-foss** [comment]
Please go read Vue documentation properly before creating an issue.
