### ISSUE TITLE
[i18n] [All] 中文呢？

### ISSUE THREAD

**Issue by xiumubai** [element-plus/element-plus#11863]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.34`
- Browser / OS: `史蒂夫`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/en-US/guide/translation.html#background)

### Steps to reproduce

中文呢？现在文档连中文都不支持了嘛？国内镜像都404了

### What is Expected?

中文呢？

### What is actually happening?

中文呢？

### Additional comments

中文呢？

**Comment by jw-foss** [comment]
@xiumubai 镜像正在同步，可能还要花10-30分钟才能上他们的 CDN。
