### ISSUE TITLE
[Style] [message, message-box] unplugin-vue-componentss自动导入时 自定义命名空间 未能实现

### ISSUE THREAD

**Issue by envCode** [element-plus/element-plus#11877]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.34`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-message-box`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/releases/tag/2.2.34)

### Steps to reproduce

F12浏览器调试

### What is Expected?

el-overlay is-message-box

### What is actually happening?

env-overlay is-message-box

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/127196721/223394876-d94eec3a-c5fb-4153-8c1b-7c071ba6088d.png)

**Comment by mosquitozzy** [comment]
全量引入时也有这个问题

**Comment by jw-foss** [comment]
@mosquitozzy @envCode thank you for reporting this, I guess we did missed this one. I will make a patch for this.

**Comment by envCode** [comment]
![image](https://user-images.githubusercontent.com/127196721/223598742-4997a7cb-ca7f-417e-9ee2-ae461c43c590.png)
没有改完

**Comment by jw-foss** [comment]
> ![image](https://user-images.githubusercontent.com/127196721/223599576-dac79f85-0d5c-4e77-954a-c06548dbea73.png)
> 
> 新版本 sortColumn(newColumns)在报错

Please open another issue for this one, and please include at least one demo. Thanks.

**Comment by jw-foss** [comment]
> ![image](https://user-images.githubusercontent.com/127196721/223598742-4997a7cb-ca7f-417e-9ee2-ae461c43c590.png) 没有改完

Got it, reopening this one.

**Comment by mosquitozzy** [comment]
![error](https://user-images.githubusercontent.com/20468826/223600736-5a73be8b-95fd-43e8-80e9-13bb14de0051.png)

**Comment by jw-foss** [comment]
@mosquitozzy yeah, I think the fix I made yesterday only fixed part of it, I'll submit a new one to fix all. Sorry for that, could you guys wait for another release? Sincerely apologies.

**Comment by jw-foss** [comment]
Closed via #11899
