### ISSUE TITLE
[Component] [select, tree-select] [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#11878]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.34`
- Browser / OS: `chrome 100`
- Build Tool: `Webpack`

### Related Component

- `el-select`
- `el-tree-select`

### Steps to reproduce

以jsx的方式书写vue代码
<el-select>
  {itemList.value.map((x) => (<el-option key={x.value} label={x.text} value={x.value} />))}
</el-select>
![image](https://user-images.githubusercontent.com/22720488/223419609-f5fe12a3-aa77-4bc2-bc4c-33c815e1787d.png)

### What is Expected?

控制台不出现这个警告

### What is actually happening?

2.2.30 版本是没有这个问题的

### Additional comments

_(empty)_

**Comment by godxiaoji** [comment]
It has fixed.
Related: https://github.com/element-plus/element-plus/pull/11868
