### ISSUE TITLE
[bug report] There is a bug in the focus method of El input

### ISSUE THREAD

**Issue by hxyvipno1** [element-plus/element-plus#1187]
`<template>
    <el-input  :ref="inputref"/>
</template>
`

`
<script>
import { ref, onMounted } from 'vue';
   export default{
     setup(){
         const inputref = ref(null);
        onMounted(()=>{
            inputref.focus();
        })
        return{  inputref }
     }
  }
</script>
`
![image](https://user-images.githubusercontent.com/30286403/103474096-6144af80-4ddb-11eb-9cd5-9de2a7348999.png)
 #提示inputref.focus不是一个方法

- [ ]

**Comment by BeADre** [comment]
1. you should not use `v-bind` in template
2. you should use `inputref.value.focus()` in `onMounted ` Function

**Comment by hxyvipno1** [comment]
it looks like we can not get Dom via ref;  using callback functions worked
`<el-input :ref="dom" />
setup() {
    let refs: HTMLElement;
    const dom = (el: HTMLElement) => {
      refs = el;
    };
    onMounted(() => {
      refs.focus();
    });
    return {
      dom,
    };
  }`

**Comment by hxyvipno1** [comment]
it looks like we can not get Dom via ref; using functions worked
<el-input :ref="dom" /> setup() { let refs: HTMLElement; const dom = (el: HTMLElement) => { refs = el; }; onMounted(() => { refs.focus(); }); return { dom, }; }

**Comment by Ryan2128** [comment]
```
<template>
  <el-input ref="inputRef" v-model="value"></el-input>
</template>
<script>
import { defineComponent, ref, onMounted} from 'vue'

export default defineComponent({
  setup(){
    const inputRef = ref(null)
    const value = ref('')

    onMounted(() => {
      inputRef.value.focus()
    })

    return { inputRef, value }
  },
})
</script>
```
