### ISSUE TITLE
[Style] [message-box] Message Box Design: Button Color

### ISSUE THREAD

**Issue by SukkaW** [element-plus/element-plus#11888]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.35`
- Browser / OS: `Chrome 109`
- Build Tool: `Other`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/message-box.html)

### Steps to reproduce

Open the reproduction link above, then click the `Click to open the Message Box`.

### What is Expected?

The `OK` button should have a primary color.

### What is actually happening?

The `OK` button looks like it is disabled.

### Additional comments

![](https://user-images.githubusercontent.com/40715044/223610234-c7fa18ed-891d-4167-998d-acc75d93484c.png)

**Comment by wzc520pyfm** [comment]
The reason for this problem is that when the messagebox is open, the focus is on the button, so the user can click the button to confirm the messagebox, or press the enter key to confirm the messagebox, which is good design for accessibility.
Therefore, the button style is focus instead of disabled

**Comment by SukkaW** [comment]
> Therefore, the button style is focus instead of disabled

So you are saying that element-plus is using secondary color for the primary button here?

**Comment by wzc520pyfm** [comment]
It's not that the secondary color is used as the primary button color, it's just the color when the primary button is in focus, and if you take the button out of focus, it's the color you want it to be. But maybe we could redesign the focus color to make the button more visible.

**Comment by SukkaW** [comment]
> But maybe we could redesign the focus color to make the button more visible.

That's the point.

**Comment by tolking** [comment]
At present, the focus state of the ElButton is designed with this color, and you can modify the color yourself.

or add [autofocus](https://element-plus.org/en-US/component/message-box.html#options) to ElMessageBox
