### ISSUE TITLE
[Style] [cascader] el-cascader 多选功能 类名el-tag__content下多渲染一层span

### ISSUE THREAD

**Issue by ST-log** [element-plus/element-plus#11905]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.30`
- Browser / OS: `QQBrowser/11.5.5240.400`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgcHJvcHM0ID0geyAgIG11bHRpcGxlOiB0cnVlLCB9OyBjb25zdCBvcHRpb25zNCA9IFsgICB7ICAgICB2YWx1ZTogMSwgICAgIGxhYmVsOiAnQXNpYScsICAgICBjaGlsZHJlbjogWyAgICAgICB7ICAgICAgICAgdmFsdWU6IDIsICAgICAgICAgbGFiZWw6ICdDaGluYScsICAgICAgICAgY2hpbGRyZW46IFsgICAgICAgICAgIHsgdmFsdWU6IDMsIGxhYmVsOiAnQmVpamluZycgfSwgICAgICAgICAgIHsgdmFsdWU6IDQsIGxhYmVsOiAnU2hhbmdoYWknIH0sICAgICAgICAgICB7IHZhbHVlOiA1LCBsYWJlbDogJ0hhbmd6aG91JyB9LCAgICAgICAgIF0sICAgICAgIH0sICAgICAgIHsgICAgICAgICB2YWx1ZTogNiwgICAgICAgICBsYWJlbDogJ0phcGFuJywgICAgICAgICBjaGlsZHJlbjogWyAgICAgICAgICAgeyB2YWx1ZTogNywgbGFiZWw6ICdUb2t5bycgfSwgICAgICAgICAgIHsgdmFsdWU6IDgsIGxhYmVsOiAnT3Nha2EnIH0sICAgICAgICAgICB7IHZhbHVlOiA5LCBsYWJlbDogJ0t5b3RvJyB9LCAgICAgICAgIF0sICAgICAgIH0sICAgICAgIHsgICAgICAgICB2YWx1ZTogMTAsICAgICAgICAgbGFiZWw6ICdLb3JlYScsICAgICAgICAgY2hpbGRyZW46IFsgICAgICAgICAgIHsgdmFsdWU6IDExLCBsYWJlbDogJ1Nlb3VsJyB9LCAgICAgICAgICAgeyB2YWx1ZTogMTIsIGxhYmVsOiAnQnVzYW4nIH0sICAgICAgICAgICB7IHZhbHVlOiAxMywgbGFiZWw6ICdUYWVndScgfSwgICAgICAgICBdLCAgICAgICB9LCAgICAgXSwgICB9LCAgIHsgICAgIHZhbHVlOiAxNCwgICAgIGxhYmVsOiAnRXVyb3BlJywgICAgIGNoaWxkcmVuOiBbICAgICAgIHsgICAgICAgICB2YWx1ZTogMTUsICAgICAgICAgbGFiZWw6ICdGcmFuY2UnLCAgICAgICAgIGNoaWxkcmVuOiBbICAgICAgICAgICB7IHZhbHVlOiAxNiwgbGFiZWw6ICdQYXJpcycgfSwgICAgICAgICAgIHsgdmFsdWU6IDE3LCBsYWJlbDogJ01hcnNlaWxsZScgfSwgICAgICAgICAgIHsgdmFsdWU6IDE4LCBsYWJlbDogJ0x5b24nIH0sICAgICAgICAgXSwgICAgICAgfSwgICAgICAgeyAgICAgICAgIHZhbHVlOiAxOSwgICAgICAgICBsYWJlbDogJ1VLJywgICAgICAgICBjaGlsZHJlbjogWyAgICAgICAgICAgeyB2YWx1ZTogMjAsIGxhYmVsOiAnTG9uZG9uJyB9LCAgICAgICAgICAgeyB2YWx1ZTogMjEsIGxhYmVsOiAnQmlybWluZ2hhbScgfSwgICAgICAgICAgIHsgdmFsdWU6IDIyLCBsYWJlbDogJ01hbmNoZXN0ZXInIH0sICAgICAgICAgXSwgICAgICAgfSwgICAgIF0sICAgfSwgICB7ICAgICB2YWx1ZTogMjMsICAgICBsYWJlbDogJ05vcnRoIEFtZXJpY2EnLCAgICAgY2hpbGRyZW46IFsgICAgICAgeyAgICAgICAgIHZhbHVlOiAyNCwgICAgICAgICBsYWJlbDogJ1VTJywgICAgICAgICBjaGlsZHJlbjogWyAgICAgICAgICAgeyB2YWx1ZTogMjUsIGxhYmVsOiAnTmV3IFlvcmsnIH0sICAgICAgICAgICB7IHZhbHVlOiAyNiwgbGFiZWw6ICdMb3MgQW5nZWxlcycgfSwgICAgICAgICAgIHsgdmFsdWU6IDI3LCBsYWJlbDogJ1dhc2hpbmd0b24nIH0sICAgICAgICAgXSwgICAgICAgfSwgICAgICAgeyAgICAgICAgIHZhbHVlOiAyOCwgICAgICAgICBsYWJlbDogJ0NhbmFkYScsICAgICAgICAgY2hpbGRyZW46IFsgICAgICAgICAgIHsgdmFsdWU6IDI5LCBsYWJlbDogJ1Rvcm9udG8nIH0sICAgICAgICAgICB7IHZhbHVlOiAzMCwgbGFiZWw6ICdNb250cmVhbCcgfSwgICAgICAgICAgIHsgdmFsdWU6IDMxLCBsYWJlbDogJ090dGF3YScgfSwgICAgICAgICBdLCAgICAgICB9LCAgICAgXSwgICB9LCBdO1xuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+IDx0ZW1wbGF0ZT4gICAgPGVsLWNhc2NhZGVyIHBvcHBlci1jbGFzcz1cImRpeS1zdHlsZVwiIDpvcHRpb25zPVwib3B0aW9uczRcIiA6cHJvcHM9XCJwcm9wczRcIiBjbGVhcmFibGUgLz4gPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

只需要按照你这边官方文档使用

### What is Expected?

选择标签后显示

### What is actually happening?

只留有灰色背景标签， 里面多渲染了一个层span,导致嵌套高度为0

### Additional comments

_(empty)_
![image](https://user-images.githubusercontent.com/80268912/223679761-926474c3-86ee-4cee-910f-e7e8a7cc1d65.png)
![image](https://user-images.githubusercontent.com/80268912/223679943-8f42d588-85c6-4ad0-b2eb-3a35f62a1017.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/223682230-3b512882-e8cb-47a0-8267-a53031a7063f.png)
未复现，能提提供一下复现步骤

**Comment by ST-log** [comment]
当时我在你这界面操作使用一样的版本是没有问题的， 如果你这没有复现就算了，我只需要改动一下样式就好了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 下午5:59
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Style] [cascader] el-cascader 多选功能 类名el-tag__content下多渲染一层span (Issue #11905)





 

 未复现，能提提供一下复现步骤

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/223687663-0115d52e-a6a4-460e-b24d-daa1f0b7a153.png)
不客气，但是我感觉你这个好像有些样式丢失了，你可以比对下我这边的styles和你那边选中span节点的styles
