### ISSUE TITLE
[Feature Request] time-picker component align attributes support

### ISSUE THREAD

**Issue by garrettzxd** [element-plus/element-plus#1191]
### Existing Component
Yes

### Component Name
time-picker

### Description
<el-time-picker align='left' />
type align = 'left' | 'center' | 'right'; 
 documents include align attrbutes, but i can not find in source code
path is /packages/time-picker/src/common/props.ts

**Comment by zazzaz** [comment]
will fix

**Comment by 17biubiu** [comment]
it mat be support [https://github.com/element-plus/element-plus/pull/1560](https://github.com/element-plus/element-plus/pull/1560)
