### ISSUE TITLE
[Component] [table-v2] Virtualized Table 虚拟化表格end-reached事件触发两次

### ISSUE THREAD

**Issue by Arvin-Cui** [element-plus/element-plus#11914]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.22`
- Browser / OS: `110.0.5481.178（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Link]()

### Steps to reproduce

触底加载后执行两次输出

### What is Expected?

正常 执行一次

### What is actually happening?

执行两次

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment]
Please provide a minimal demo that can be reproduced, thank you
