### ISSUE TITLE
[Style] el-message/messageBox/v-loading 样式丢失

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#11936]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 110.0.5481.178 / Win 10`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-message-box`
- `el-loading`

### Reproduction Link

[Github Repo](https://github.com/vela666/demo2)

### Steps to reproduce

使用自定义命名空间

### What is Expected?

样式正常

### What is actually happening?

样式丢失

### Additional comments

使用unplugin-vue-components后
组件里以import {ElMessage, ElMessageBox,ElNotification } from 'element-plus' 方式导入  样式都没有
v-loading 类名没有变化

**Comment by Simon-He95** [comment]
the bug is due to [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components/issues/582). Temporarily it can be processed with import 'element-plus/es/loading/index'

**Comment by chenxch** [comment]
link #11886
