### ISSUE TITLE
[Component] [drawer] 抽屉和自定义弹窗同时出现时，自定义弹窗内的输入框无法聚焦

### ISSUE THREAD

**Issue by ubbcou** [element-plus/element-plus#11943]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.34`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8YnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgbGluayBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gIWRpYWxvZ1Zpc2libGVcIj5cblx0XHTmmL7npLrmir3lsYlcbiAgPC9idXR0b24+XG5cbiAgICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCI+XG4gICAgICDmraPluLjogZrnhKbvvJpcbiAgICAgIDxpbnB1dCB2LW1vZGVsPVwidGV4dFwiIC8+XG4gICAgPC9lbC1kcmF3ZXI+XG4gIFxuICAgIDxkaXYgY2xhc3M9XCJkaWFsb2dcIiB2LWlmPVwiZGlhbG9nVmlzaWJsZVwiPlxuICAgICAg5peg5rOV6IGa54Sm77yaXG4gICAgICA8aW5wdXQgdi1tb2RlbD1cInRleHRcIiAvPlxuICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IHRleHQgPSByZWYoJycpXG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmU6ICgpID0+IHZvaWQpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oJ0FyZSB5b3Ugc3VyZSB0byBjbG9zZSB0aGlzIGRpYWxvZz8nKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIGRvbmUoKVxuICAgIH0pXG4gICAgLmNhdGNoKCgpID0+IHtcbiAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgfSlcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kaWFsb2ctZm9vdGVyIGJ1dHRvbjpmaXJzdC1jaGlsZCB7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbiAgXG4gIC5kaWFsb2cge1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICBsZWZ0OiAxMCU7XG4gICAgdG9wOiAxMCU7XG4gICAgd2lkdGg6IDMwMHB4O1xuICAgIHBhZGRpbmc6IDMwcHg7XG4gICAgYm94LXNoYWRvdzogNnB4IDZweCAxMnB4ICM5OTk7XG4gICAgei1pbmRleDogMTAwMDAwMDtcbiAgICBiYWNrZ3JvdW5kOiAjZmZmO1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 同时开启抽屉 + 自定义弹窗
2. 直接点击自定义弹窗内的输入框

### What is Expected?

自定义弹窗内的输入框正常聚焦

### What is actually happening?

自定义弹窗内的输入框无法聚焦，但是抽屉内的可以正常聚焦。

另外点击自定义弹窗空白位置后，弹窗内的抽屉也能聚焦了。

### Additional comments

_(empty)_

**Comment by tolking** [comment]
组件内部弹窗使用 `ElFocusTrap` 将焦点困在弹窗内部，这属于 a11y 特性。你可以在打开弹窗后按 Tab 按键确认这种行为。

推荐你使用我们提供的弹窗组件，或者你可能需要自己参考 `ElDialog` 使用 `ElFocusTrap` 组件包裹自定义弹窗内容。

**Comment by ubbcou** [comment]
@tolking 与 `ElDrawer `不同的是，`ElDialog` 没有实现这个将焦点困在弹窗内部的特性，这是设计如此吗？

**Comment by tolking** [comment]
理论上 ElDrawer ElDialog 两者的行为是一样的

**Comment by CharlesLzo** [comment]
@tolking 现在我也遇到了类似情况：同时展示左右2个drawer时，会有以下问题出现：

1、打开抽屉后，在（左侧）抽屉组件里，“点击的 input 或 select 时”，问题出现：“均无法正常聚焦”。不过，若显点击空白处（抽屉组件内外均可）后，就可以正常聚焦了。期待：在打开抽屉后，点击 input 或 select 能正常聚焦。

2、打开抽屉后，在（右侧）抽屉组件里，“点击 input 聚焦，或点击 select 下拉菜单选中一项后，在不失焦的前提下”，马上点击（左侧）抽屉组件里的 input 或 select 下拉菜单时，问题出现：“（左侧）抽屉的 input 和 select 均无法正常聚焦，可是此时（右侧）抽屉的下拉菜单竟然再次触发了”。期待：各自的抽屉控制各自的下拉菜单，互不影响。

[问题示例请戳这里查看](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJkcmF3ZXJWaXNpYmxlID0gIWRyYXdlclZpc2libGVcIj7mmL7npLrmir3lsYk8L2J1dHRvbj5cblxuICA8ZWwtZHJhd2VyXG4gICAgcmVmPVwiZHJhd2VyTGVmdFwiXG4gICAgdi1tb2RlbD1cImRyYXdlclZpc2libGVcIlxuICAgIHRpdGxlPVwiSSBhbSBsZWZ0IGRyYXdlclwiXG4gICAgZGlyZWN0aW9uPVwibHRyXCJcbiAgICA6bW9kYWw9XCJmYWxzZVwiXG4gICAgOmJlZm9yZS1jbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICA+XG4gICAgPHNwYW4+SGksIGJveXMhPC9zcGFuPlxuICAgIDxPbmUgLz5cbiAgPC9lbC1kcmF3ZXI+XG5cbiAgPGVsLWRyYXdlclxuICAgIHJlZj1cImRyYXdlclJpZ2h0XCJcbiAgICB2LW1vZGVsPVwiZHJhd2VyVmlzaWJsZVwiXG4gICAgdGl0bGU9XCJJIGFtIHJpZ2h0IGRyYXdlclwiXG4gICAgZGlyZWN0aW9uPVwicnRsXCJcbiAgICA6bW9kYWw9XCJmYWxzZVwiXG4gICAgOmJlZm9yZS1jbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICA+XG4gICAgPHNwYW4+SGksIGdpcmxzITwvc3Bhbj5cbiAgICA8VHdvIC8+XG4gIDwvZWwtZHJhd2VyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCBPbmUgZnJvbSAnLi9Db21wLnZ1ZSdcbmltcG9ydCBUd28gZnJvbSAnLi9Db21wMS52dWUnXG5cbmNvbnN0IGRyYXdlclZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBkcmF3ZXJMZWZ0ID0gcmVmKG51bGwpXG5jb25zdCBkcmF3ZXJSaWdodCA9IHJlZihudWxsKVxuXG4vLyDlhbPpl63mir3lsYlcbmNvbnN0IGhhbmRsZUNsb3NlID0gKCkgPT4ge1xuICBkcmF3ZXJWaXNpYmxlLnZhbHVlID0gZmFsc2Vcbn1cblxuLy8g5omT5byA5oq95bGJXG5jb25zdCBoYW5kbGVPcGVuID0gKCkgPT4ge1xuICAgIHNldERlZXBEcmF3ZXJNb2RhbCgpXG59XG5cbi8qKlxuICog56m/6YCP6YGu572p5bGCXG4gKiAtIOiuvue9ruaKveWxieeahCBwb2ludGVyRXZlbnRzPSdhdXRvJywg5L2/5oq95bGJ5Y+v5Lul5q2j5bi45pON5L2cXG4gKiAtIOiuvue9ruaKveWxieeahOmBrue9qeWxgueahCBwb2ludGVyRXZlbnRzID0gJ25vbmUnLCDkvb/lhbbku5bljLrln5/lj6/mraPluLjmk43kvZxcbiAqL1xuIGNvbnN0IHNldERlZXBEcmF3ZXJNb2RhbCA9ICgpID0+IHtcbiAgICBjb25zdCBvdmVybGF5TGlzdCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJy5lbC1kcmF3ZXInKVxuICAgIG92ZXJsYXlMaXN0LmZvckVhY2goaXRlbSA9PiB7XG4gICAgICAgIGNvbnN0IGl0ZW1GYSA9IGl0ZW0ucGFyZW50Tm9kZTtcbiAgICAgICAgLy8g5oq95bGJXG4gICAgICAgIGl0ZW0uc3R5bGUucG9pbnRlckV2ZW50cyA9ICdhdXRvJ1xuICAgICAgICAvLyDmir3lsYnnmoTpga7nvanlsYJcbiAgICAgICAgaXRlbUZhLnN0eWxlLnBvaW50ZXJFdmVudHMgPSAnbm9uZSdcbiAgICB9KVxufVxuXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+PC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9Db21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0VmFsXCIgcGxhY2Vob2xkZXI9XCJcIi8+XG4gICAgPGVsLXNlbGVjdCByZWY9XCJzcGVjaWFsSW5wdXRcIiBjbGFzcz1cInNwZWNpYWwtaW5wdXRcIiB2LW1vZGVsPVwic2VsZWN0VmFsdWVcIiBwbGFjZWhvbGRlcj1cIlwiIGZpbHRlcmFibGUgY2xlYXJhYmxlPlxuICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBzZWxlY3RMaXN0XCIgOmtleT1cIml0ZW0/LnZhbHVlXCIgOmxhYmVsPVwiaXRlbT8ubGFiZWxcIiA6dmFsdWU9XCJpdGVtPy52YWx1ZVwiLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICBcbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuLy8g5py65Zy65L+h5oGvXG5pbXBvcnQgeyByZWYsIHJlYWN0aXZlLCB0b1JlZnMsIGNvbXB1dGVkLCBvbk1vdW50ZWQsIHdhdGNoRWZmZWN0LCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgaW5wdXRWYWwgPSByZWYoJycpXG5jb25zdCBzZWxlY3RWYWx1ZSA9IHJlZignJylcblxuXG5jb25zdCBzZWxlY3RMaXN0ID0gcmVmKFtcbiAgICB7XG4gICAgICAgIGxhYmVsOiAnQUFBJyxcbiAgICAgICAgdmFsdWU6ICcxJ1xuICAgIH0sXG4gICAge1xuICAgICAgICBsYWJlbDogJ0JCQicsXG4gICAgICAgIHZhbHVlOiAnMidcbiAgICB9XG5dKVxuPC9zY3JpcHQ+XG4iLCJzcmMvQ29tcDEudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxlbC1zZWxlY3QgcmVmPVwic3BlY2lhbElucHV0XCIgY2xhc3M9XCJzcGVjaWFsLWlucHV0XCIgdi1tb2RlbD1cInNlbGVjdFZhbHVlXCIgcGxhY2Vob2xkZXI9XCJcIiBmaWx0ZXJhYmxlIGNsZWFyYWJsZT5cbiAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gc2VsZWN0TGlzdFwiIDprZXk9XCJpdGVtPy52YWx1ZVwiIDpsYWJlbD1cIml0ZW0/LmxhYmVsXCIgOnZhbHVlPVwiaXRlbT8udmFsdWVcIi8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gICAgXG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFZhbFwiIHBsYWNlaG9sZGVyPVwiXCIvPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHJlYWN0aXZlLCB0b1JlZnMgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGlucHV0VmFsID0gcmVmKCcnKVxuY29uc3Qgc2VsZWN0VmFsdWUgPSByZWYoJycpXG5cblxuY29uc3Qgc2VsZWN0TGlzdCA9IHJlZihbXG4gICAge1xuICAgICAgICBsYWJlbDogJ29uZScsXG4gICAgICAgIHZhbHVlOiAnMSdcbiAgICB9LFxuICAgIHtcbiAgICAgICAgbGFiZWw6ICd0d28nLFxuICAgICAgICB2YWx1ZTogJzInXG4gICAgfVxuXSlcbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==)

**Comment by tolking** [comment]
审核PR的人手不足。如果急需可以自己参考 #11965 更新本地文件
