### ISSUE TITLE
[Component] [select] el-select option组件相同label导致上下方向控制失效

### ISSUE THREAD

**Issue by qjinle** [element-plus/element-plus#11953]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWwgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAgICB7XG4gICAgICBsYWJlbDogJ2EnLFxuICAgICAgdmFsdWU6ICdhJyxcbiAgICB9LFxuICAgIHtcbiAgICAgIGxhYmVsOiAnYScsXG4gICAgICB2YWx1ZTogJ2InLFxuICAgIH0sXG4gICAge1xuICAgICAgbGFiZWw6ICdhJyxcbiAgICAgIHZhbHVlOiAnYycsXG4gICAgfSxcbiAgICB7XG4gICAgICBsYWJlbDogJ2EnLFxuICAgICAgdmFsdWU6ICdkJyxcbiAgICB9XG4gIF0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWxcIiBmaWx0ZXJhYmxlIGRlZmF1bHQtZmlyc3Qtb3B0aW9uPlxuICBcdDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCI+XG4gICAgXHQ8c3Bhbj57e2l0ZW0udmFsdWV9fTwvc3Bhbj5cbiAgICA8L2VsLW9wdGlvbj5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 参考链接代码
2. 打开下拉框
3. 方向键上下选取目标

### What is Expected?

1. 按顺序上下hover目标

### What is actually happening?

1. 相同的label导致永远hover第一个

### Additional comments

方向键控制hover应该按照key/value来判断，而不是label

**Comment by chenxch** [comment]
cause #11909

**Comment by jw-foss** [comment]
Label 和 Value 都应该是独一无二的吧？我在想什么样的场景下需要 Label 一样但值不一样 😂

**Comment by jw-foss** [comment]
> > Label 和 Value 都应该是独一无二的吧？我在想什么样的场景下需要 Label 一样但值不一样 😂
> 
> 比如我通过 option 的 slot 自定义了选项的结构，但是需要某些 value 选中后在 input 框里显示一样的值，所以就需要一样的 label（我的 key 和 value 都是唯一的）

理解这个情况了，但是我在想这样不会让人觉得奇怪吗，显示一样的值 🤔 这确实是一个问题，我们可能得想一个比较好的方案来解决这个

**Comment by qjinle** [comment]
> 



> > > Label 和 Value 都应该是独一无二的吧？我在想什么样的场景下需要 Label 一样但值不一样 😂
> > 
> > 
> > 比如我通过 option 的 slot 自定义了选项的结构，但是需要某些 value 选中后在 input 框里显示一样的值，所以就需要一样的 label（我的 key 和 value 都是唯一的）
> 
> 理解这个情况了，但是我在想这样不会让人觉得奇怪吗，显示一样的值 🤔 这确实是一个问题，我们可能得想一个比较好的方案来解决这个

是的，这个场景确实奇怪，但确实存在。因为自定义 slot，所以用户在使用时知道自己选中的是什么选项。（比如通过 select 选择去触发搜索，所以 input 的显示只显示让用户明白的 label 就行，但很不幸这些 label 有重复的）
现在让开发者感觉是用 label 在控制 hoverIndex，如果通过 value 或者 key 都会好一点。

**Comment by jw-foss** [comment]
> 现在让开发者感觉是用 label 在控制 hoverIndex，如果通过 value 或者 key 都会好一点。

确实是这样的 😂

**Comment by acyza** [comment]
#11297 通过label值来重排optionsArray，或许换成dom或其他的具有标记性的字段作为重排的依据会更好些。
