### ISSUE TITLE
[Style] [loading] Use the namespace set by el-config-provider="ep", and the class name of v-loading/el-loading is still the class name of el -

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#11954]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 110.0.5481.178 / Win 10`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Github Repo](https://github.com/vela666/demo2)

### Steps to reproduce

Use v-loading/el-loading after setting namespace

### What is Expected?

className true

### What is actually happening?

className error

### Additional comments

![1678421779703](https://user-images.githubusercontent.com/69613314/224222433-e6d80dd1-d97f-4a8d-851e-8b627afad71e.jpg)

**Comment by chenxch** [comment]
link https://github.com/element-plus/element-plus/issues/11886
