### ISSUE TITLE
[Feature Request] when click the white space, close the image previewer

### ISSUE THREAD

**Issue by Akimotorakiyu** [element-plus/element-plus#1195]
### Existing Component
Yes

### Component Name
Image

### Description
when click   white space, close the image previewer

**Comment by JeremyWuuuuu** [comment]
@Akimotorakiyu is it ok that I add an event when clicking the wrapper? Because the wrapper's existence was controlled by the parent, so it is up to you that you can choose whether close it or not.

**Comment by Akimotorakiyu** [comment]
@JeremyWuuuuu 如果是可配置的那最好不过，空白处点击关闭 应该是一个合理的操作。

有些时候，这个关闭真的不好找。

![图片](https://user-images.githubusercontent.com/31165554/103605110-f7004c00-4f4d-11eb-85b5-a89dbbccdb77.png)

**Comment by JeremyWuuuuu** [comment]
@Akimotorakiyu  I'll adjust the close button's color as well.
