### ISSUE TITLE
[Component] [input-number] 使用el-input-number时，输入值然后将值删除，点击保存，校验失效

### ISSUE THREAD

**Issue by ouyangyyds33** [element-plus/element-plus#11963]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome；Win64`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsTWVzc2FnZSwgRm9ybUluc3RhbmNlLCBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGFkZEZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpO1xuIFxuY29uc3QgYWRkRm9ybSA9IHJlYWN0aXZlKHtcbiAgd2VpZ2h0OiB1bmRlZmluZWRcbn0pXG5cbmNvbnN0IG9uU2F2ZUZvcm1EYXRhID0gYXN5bmMgZnVuY3Rpb24gKCkge1xuICBhd2FpdCBhZGRGb3JtUmVmLnZhbHVlLnZhbGlkYXRlKCk7XG4gIEVsTWVzc2FnZShcIuS/neWtmOaIkOWKn1wiKVxufVxuXG5jb25zdCBydWxlczogRm9ybVJ1bGVzID0gcmVhY3RpdmUoe1xuICB3ZWlnaHQ6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiBcIumHjemHj+S4jeiDveS4uuepulwiLCB0cmlnZ2VyOiBcImNoYW5nZVwiIH1dLFxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4XCI+XG4gICAgPGVsLWZvcm1cbiAgICAgIHJlZj1cImFkZEZvcm1SZWZcIlxuICAgICAgOm1vZGVsPVwiYWRkRm9ybVwiXG4gICAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgICBsYWJlbC13aWR0aD1cIjEwMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtZm9ybS1pdGVtIFxuICAgICAgICBsYWJlbD1cIuaVsOWtl+i+k+WFpeahhlwiXG4gICAgICAgIHByb3A9XCJ3ZWlnaHRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtaW5wdXQtbnVtYmVyXG4gICAgICAgICAgdi1tb2RlbD1cImFkZEZvcm0ud2VpZ2h0XCJcbiAgICAgICAgICBjbGVhcmFibGVcbiAgICAgICAgICA6Y29udHJvbHM9XCJmYWxzZVwiXG4gICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMzAwcHhcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9lbC1mb3JtPlxuICAgIDxlbC1idXR0b25cbiAgICAgIHR5cGU9XCJwcmltYXJ5XCJcbiAgICAgIEBjbGljaz1cIm9uU2F2ZUZvcm1EYXRhXCJcbiAgICA+XG4gICAgICDkv53lrZhcbiAgICA8L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

使用el-input-number时，输入值然后将值删除，点击保存，触发校验，发现校验失效

### What is Expected?

输入值，将值删除后，点击保存，触发校验，校验还是正常的

### What is actually happening?

输入值，将值删除后，点击保存，触发校验，发现校验失效

### Additional comments

无

**Comment by ouyangyyds33** [comment]
在线重现实例：
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsTWVzc2FnZSwgRm9ybUluc3RhbmNlLCBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGFkZEZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpO1xuIFxuY29uc3QgYWRkRm9ybSA9IHJlYWN0aXZlKHtcbiAgd2VpZ2h0OiB1bmRlZmluZWRcbn0pXG5cbmNvbnN0IG9uU2F2ZUZvcm1EYXRhID0gYXN5bmMgZnVuY3Rpb24gKCkge1xuICBhd2FpdCBhZGRGb3JtUmVmLnZhbHVlLnZhbGlkYXRlKCk7XG4gIEVsTWVzc2FnZShcIuS/neWtmOaIkOWKn1wiKVxufVxuXG5jb25zdCBydWxlczogRm9ybVJ1bGVzID0gcmVhY3RpdmUoe1xuICB3ZWlnaHQ6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiBcIumHjemHj+S4jeiDveS4uuepulwiLCB0cmlnZ2VyOiBcImNoYW5nZVwiIH1dLFxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4XCI+XG4gICAgPGVsLWZvcm1cbiAgICAgIHJlZj1cImFkZEZvcm1SZWZcIlxuICAgICAgOm1vZGVsPVwiYWRkRm9ybVwiXG4gICAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgICBsYWJlbC13aWR0aD1cIjEwMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtZm9ybS1pdGVtIFxuICAgICAgICBsYWJlbD1cIuaVsOWtl+i+k+WFpeahhlwiXG4gICAgICAgIHByb3A9XCJ3ZWlnaHRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtaW5wdXQtbnVtYmVyXG4gICAgICAgICAgdi1tb2RlbD1cImFkZEZvcm0ud2VpZ2h0XCJcbiAgICAgICAgICBjbGVhcmFibGVcbiAgICAgICAgICA6Y29udHJvbHM9XCJmYWxzZVwiXG4gICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMzAwcHhcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9lbC1mb3JtPlxuICAgIDxlbC1idXR0b25cbiAgICAgIHR5cGU9XCJwcmltYXJ5XCJcbiAgICAgIEBjbGljaz1cIm9uU2F2ZUZvcm1EYXRhXCJcbiAgICA+XG4gICAgICDkv53lrZhcbiAgICA8L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by ouyangyyds33** [comment]
@emojiiii

**Comment by Mario34** [comment]
[补充了一个更简单的复现](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5jb25zdCB2YWx1ZSA9IHJlZigpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBjbGVhcmFibGVcbiAgLz5cbiAgPGRpdj5cbiAgICB2YWx1ZToge3sgdmFsdWUgfX1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

输入数字后，快速按 backspace ，直到文本框内数字被清空，实际绑定的值任然为清空前的最后一数字

我认为这个就是导致你校验结果不符合预期的原因 @ouyangyyds33

**Comment by ouyangyyds33** [comment]
是的，虽然界面上文本框内的数字被清空了，但是实际绑定的值任然为清空前的最后一数字，导致校验通过

**Comment by prettylikeme** [comment]
@ouyangyyds33 我也遇到了同样的问题，应该是个 **BUG**，监听一下 `input` 事件和 `update:modelValue` 事件对比一下就能发现，输入后的值如果和点击输入前的值一样时，就不会触发 `update:modelValue` 事件。例如：输入前的值是 `123` ，点击 `el-input-number` 输入框后输入 `4` ，然后再删除 `4`，此时的值应该是 `123`，正确触发了 `input` 事件，值为 `123` ，但是没有触发 `update:modelValue` 事件，所以绑定的值还是 `1234`。
