### ISSUE TITLE
[Component] [select] selsect

### ISSUE THREAD

**Issue by zhaoyunqi888** [element-plus/element-plus#11962]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 111`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/form.html#尺寸控制)

### Steps to reproduce

切换form尺寸时，el-select 的高度一直保持默认高度，不会随size 的改变而改变高度

### What is Expected?

根据size的切换 高边select 的高度

### What is actually happening?

切换form尺寸时，el-select 的高度一直保持默认高度

### Additional comments

_(empty)_

**Comment by jiaozhiye** [comment]
el-cascader 组件也有这个问题，希望官网能统一排查一下

**Comment by acyza** [comment]
#10847 的改动导致的尺寸无法切换。

**Comment by acyza** [comment]
#11973 的改动是有selectSize的优先使用selectSize。
