### ISSUE TITLE
[Style] [table] this column title will be in different row.

### ISSUE THREAD

**Issue by ramwin** [element-plus/element-plus#11978]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[Github Repo](https://github.com/ramwin/html-reference/blob/master/test/element-bug.html)

### Steps to reproduce

clone the project and open the file `element-bug.html`

### What is Expected?

the second table should show the header in one line

### What is actually happening?

the second table set three header as a group.

### Additional comments

_(empty)_

**Comment by ramwin** [comment]
![image](https://user-images.githubusercontent.com/17930851/224481587-3e0a5023-0c18-4275-ab26-ba89ac4335bc.png)

**Comment by tolking** [comment]
[the document about ElTable](https://element-plus.org/en-US/component/table.html#why-column-is-not-rendered-when-use-dom-templates)
