### ISSUE TITLE
[Bug Report] [el-table] 设置 height 和  keeplive 时 切换

### ISSUE THREAD

**Issue by xl495** [element-plus/element-plus#11971]
### Element Plus version
2.2.36

### OS/Browsers version
wn 10

### Vue version
3.2.45

### Reproduction Link
https://codesandbox.io/p/github/xl495/element-push-router-keep-live/master

### Steps to reproduce
第一步  滚动 table 到最底部
第二步 切换到 Home 页面 再切换回来
就会发现 table 滚动条是正确的 但是内容是不缺正确的

### What is Expected?
切换回来table的内容是正确的

### What is actually happening?
keeplive 可能会引起滚动丢失

**Comment by JackieCheung** [comment]
+1

**Comment by tolking** [comment]
Fixed by #11363
