### ISSUE TITLE
[Component] el-dialog  里面嵌套  el-drawer 的时候，el-select 组件如果是 filterable 的会出现点击任何地方都会展示下拉的情况

### ISSUE THREAD

**Issue by KnSup** [element-plus/element-plus#11974]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-drawer`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxlbC1idXR0b24gdGV4dCBAY2xpY2s9XCJ0YWJsZSA9IHRydWVcIlxuICAgID7miZPlvIDlvLnnqpc8L2VsLWJ1dHRvblxuICA+XG5cbjxlbC1kaWFsb2cgdi1tb2RlbD1cInRhYmxlXCI+XG4gICAgPGVsLWJ1dHRvbiB0ZXh0IEBjbGljaz1cImRpYWxvZyA9IHRydWVcIlxuICAgID7miZPlvIAgZHJhd2VyPC9lbC1idXR0b25cbiAgPlxuICAgIDxlbC1kcmF3ZXJcbiAgICByZWY9XCJkcmF3ZXJSZWZcIlxuICAgIHYtbW9kZWw9XCJkaWFsb2dcIlxuICAgIHRpdGxlPVwiSSBoYXZlIGEgbmVzdGVkIGZvcm0gaW5zaWRlIVwiXG4gICAgZGlyZWN0aW9uPVwiYnR0XCJcbiAgICBjbGFzcz1cImRlbW8tZHJhd2VyXCJcbiAgICBkZXN0cm95LW9uLWNsb3NlXG4gID5cbiAgICA8ZGl2IGNsYXNzPVwiZGVtby1kcmF3ZXJfX2NvbnRlbnRcIj5cbiAgICAgIDxlbC1mb3JtIDptb2RlbD1cImZvcm1cIj5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFyZWFcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICAgIDxlbC1zZWxlY3QgZmlsdGVyYWJsZVxuICAgICAgICAgICAgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCJcbiAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdCBhY3Rpdml0eSBhcmVhXCJcbiAgICAgICAgICA+XG4gICAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiQXJlYTFcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJBcmVhMlwiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPC9lbC1mb3JtPlxuICAgIDwvZGl2PlxuICA8L2VsLWRyYXdlcj5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsRHJhd2VyLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZvcm1MYWJlbFdpZHRoID0gJzgwcHgnXG5sZXQgdGltZXJcblxuY29uc3QgdGFibGUgPSByZWYoZmFsc2UpXG5jb25zdCBkaWFsb2cgPSByZWYoZmFsc2UpXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnJyxcbiAgcmVnaW9uOiAnJyxcbiAgZGF0ZTE6ICcnLFxuICBkYXRlMjogJycsXG4gIGRlbGl2ZXJ5OiBmYWxzZSxcbiAgdHlwZTogW10sXG4gIHJlc291cmNlOiAnJyxcbiAgZGVzYzogJycsXG59KVxuXG5jb25zdCBncmlkRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnUGV0ZXIgUGFya2VyJyxcbiAgICBhZGRyZXNzOiAnUXVlZW5zLCBOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnUGV0ZXIgUGFya2VyJyxcbiAgICBhZGRyZXNzOiAnUXVlZW5zLCBOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnUGV0ZXIgUGFya2VyJyxcbiAgICBhZGRyZXNzOiAnUXVlZW5zLCBOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnUGV0ZXIgUGFya2VyJyxcbiAgICBhZGRyZXNzOiAnUXVlZW5zLCBOZXcgWW9yayBDaXR5JyxcbiAgfSxcbl1cblxuY29uc3QgZHJhd2VyUmVmID0gcmVmPEluc3RhbmNlVHlwZTx0eXBlb2YgRWxEcmF3ZXI+PigpXG5jb25zdCBvbkNsaWNrID0gKCkgPT4ge1xuICBkcmF3ZXJSZWYudmFsdWUhLmNsb3NlKClcbn1cblxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoZG9uZSkgPT4ge1xuICBpZiAobG9hZGluZy52YWx1ZSkge1xuICAgIHJldHVyblxuICB9XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdEbyB5b3Ugd2FudCB0byBzdWJtaXQ/JylcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICAgICAgdGltZXIgPSBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgICAgZG9uZSgpXG4gICAgICAgIC8vIOWKqOeUu+WFs+mXremcgOimgeS4gOWumueahOaXtumXtFxuICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgICAgICBsb2FkaW5nLnZhbHVlID0gZmFsc2VcbiAgICAgICAgfSwgNDAwKVxuICAgICAgfSwgMjAwMClcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAvLyBjYXRjaCBlcnJvclxuICAgIH0pXG59XG5cbmNvbnN0IGNhbmNlbEZvcm0gPSAoKSA9PiB7XG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuICBkaWFsb2cudmFsdWUgPSBmYWxzZVxuICBjbGVhclRpbWVvdXQodGltZXIpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击按钮打开弹窗
2. 点击按钮打开 drawer
3. 点击一次select组件让其获得焦点
4. 点击 drawer 空白区域，发现select组件会自动展示下拉选项（最好是长按容易看出问题）

### What is Expected?

不会获取焦点，因为不嵌套在el-dialog中的时候是没有问题的

### What is actually happening?

会获取到焦点并且会展示下拉选项

### Additional comments

select 组件如果不设置 filterable 会获取焦点不展示下拉

**Comment by KnSup** [comment]
我又自己模仿 el-dialog 做了个简单的 dialog 组件，发现如果把 dialog 的 tabindex 设置为 -1 就会有上面问题，目前没看明白 el-focus-trap 跟 tabindex 什么关系，所以想不好解决方法

**Comment by liumangafei** [comment]
我也遇到了这个问题：
vue：3.2.47
element-plus：2.3.9

drawer + select + filterable 点击form-item的label文字就会复现这个问题

隔了几个月，是修复了还是没修复？

是怎么解决这个问题的？
