### ISSUE TITLE
[Component] [upload] Filelist of upload is not reacitve

### ISSUE THREAD

**Issue by capital-G** [element-plus/element-plus#11982]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.36`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHR5cGUgeyBVcGxvYWRVc2VyRmlsZSB9IGZyb20gXCJlbGVtZW50LXBsdXNcIjtcbiAgXG5jb25zdCBzdWJtaXRVcGxvYWQgPSAoKSA9PiB7XG59XG5jb25zdCBmaWxlTGlzdDogUmVmPFVwbG9hZFVzZXJGaWxlW10+ID0gcmVmKFtdKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIFxuICA8ZWwtdXBsb2FkIDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiIDphdXRvLXVwbG9hZD1cImZhbHNlXCI+XG4gICAgICAgPHRlbXBsYXRlICN0cmlnZ2VyPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgICAgc2VsZWN0IGZpbGVcbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuXG4gICAgICA8ZWwtYnV0dG9uXG4gICAgICAgIGNsYXNzPVwibWwtM1wiXG4gICAgICAgIHR5cGU9XCJzdWNjZXNzXCJcbiAgICAgICAgQGNsaWNrPVwic3VibWl0VXBsb2FkXCJcbiAgICAgID5cbiAgICAgICAgdXBsb2FkIHRvIHNlcnZlclxuICAgICAgPC9lbC1idXR0b24+XG4gIDwvZWwtdXBsb2FkPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

fileList is not reactive when one selects a file for upload. This makes implementing a custom upload procedure impossible as one can not obtain a handle to the upload candidates.

### What is Expected?

fileList should contain all candidates for upload

### What is actually happening?

fileList is/stays empty

### Additional comments

Filelist is also empty if one does not set it via a prop but instead try to access it via the a ref to the component (`ref="uploadRef"` and `uploadRef.value?.fileList` returns undefined)

Please allow to at least comment on issues, this is a duplicate of https://github.com/element-plus/element-plus/issues/6491 - this saves work on everyone's end

edit: it seems I am not the only one having the problem, see <https://stackoverflow.com/questions/75097079/the-file-list-attribute-of-the-el-upload-component-in-element-ui>

**Comment by cc-hearts** [comment]
can use the `on-change` and `on-remove` attributes to determine changes to the file, hope this helps you
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHR5cGUgeyBVcGxvYWRVc2VyRmlsZSB9IGZyb20gXCJlbGVtZW50LXBsdXNcIjtcbiAgXG5cbmNvbnN0IGZpbGVMaXN0OiBSZWY8VXBsb2FkVXNlckZpbGVbXT4gPSByZWYoW10pO1xuY29uc3QgdXBsb2FkUmVmID0gcmVmKClcbmNvbnN0IHN1Ym1pdFVwbG9hZCA9ICgpID0+IHtcbn1cbmNvbnN0IGhhbmRsZUNoYW5nZSA9IChfLGZpbGVMaXN0KSA9PiB7XG4gIGNvbnNvbGUubG9nKGZpbGVMaXN0KVxufVxuXG5jb25zdCBoYW5kbGVSZW1vdmUgPSAoXyxmaWxlTGlzdCkgPT4ge1xuICBjb25zb2xlLmxvZyhmaWxlTGlzdClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIFxuICA8ZWwtdXBsb2FkIHJlZj1cInVwbG9hZFJlZlwiIDpvbi1jaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiA6b24tcmVtb3ZlPVwiaGFuZGxlUmVtb3ZlXCIgOmZpbGUtbGlzdD1cImZpbGVMaXN0XCIgIDphdXRvLXVwbG9hZD1cImZhbHNlXCI+XG4gICAgICAgPHRlbXBsYXRlICN0cmlnZ2VyPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgICAgc2VsZWN0IGZpbGVcbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuXG4gICAgICA8ZWwtYnV0dG9uXG4gICAgICAgIGNsYXNzPVwibWwtM1wiXG4gICAgICAgIHR5cGU9XCJzdWNjZXNzXCJcbiAgICAgICAgQGNsaWNrPVwic3VibWl0VXBsb2FkXCJcbiAgICAgID5cbiAgICAgICAgdXBsb2FkIHRvIHNlcnZlclxuICAgICAgPC9lbC1idXR0b24+XG4gIDwvZWwtdXBsb2FkPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by chenxch** [comment]
use `v-model:file-list`

**Comment by capital-G** [comment]
> use `v-model:file-list`

Thank you for the quick solution, this was an error on my part, I was put off by this linter warning https://eslint.vuejs.org/rules/no-v-model-argument.html (but deactivated it now)
