### ISSUE TITLE
[Style] [popover] Popover的width不设置时，默认width:150

### ISSUE THREAD

**Issue by Jacqueline0905** [element-plus/element-plus#12008]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.4`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/popover.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

Popover的width不设置时，默认是150，但是elementui上默认不设置width,只有min-width

### What is Expected?

没有width:150的属性

### What is actually happening?

出现了width:150

### Additional comments

_(empty)_

**Comment by Jacqueline0905** [comment]
![image](https://user-images.githubusercontent.com/51223784/224670665-ed349601-018e-477c-a61f-3196ec950d31.png)

**Comment by Jacqueline0905** [comment]
elementui上无width
![image](https://user-images.githubusercontent.com/51223784/224670829-e9c75e0f-4089-4d40-a266-1a690e702f94.png)

**Comment by ryuhangyeong** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cInRvcC1zdGFydFwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgd2lkdGg9XCJhdXRvXCJcbiAgICB0cmlnZ2VyPVwiaG92ZXJcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBjbGFzcz1cIm0tMlwiPkhvdmVyIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWJ1dHRvbiArIC5lbC1idXR0b24ge1xuICBtYXJnaW4tbGVmdDogOHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

Is this the example you want?

The popover's width props default to 150px.

**Comment by Jacqueline0905** [comment]
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cInRvcC1zdGFydFwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgd2lkdGg9XCJhdXRvXCJcbiAgICB0cmlnZ2VyPVwiaG92ZXJcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBjbGFzcz1cIm0tMlwiPkhvdmVyIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWJ1dHRvbiArIC5lbC1idXR0b24ge1xuICBtYXJnaW4tbGVmdDogOHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> Is this the example you want?
> 
> The popover's width props default to 150px.
> 
> @Jacqueline0905 `auto`

yes

**Comment by ryuhangyeong** [comment]
@Jacqueline0905 Can I close this issue?
