### ISSUE TITLE
[Component] [upload] el-upload 上传多个文件 data 数据会被覆盖

### ISSUE THREAD

**Issue by mxismean** [element-plus/element-plus#12016]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIG11bHRpcGxlXG4gICAgOm9uLXByZXZpZXc9XCJoYW5kbGVQcmV2aWV3XCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yZVVwbG9hZFwiXG4gICAgOm9uLXJlbW92ZT1cImhhbmRsZVJlbW92ZVwiXG4gICAgOmJlZm9yZS1yZW1vdmU9XCJiZWZvcmVSZW1vdmVcIlxuICAgIDpsaW1pdD1cIjk5OTlcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UsIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbl0pXG5cbmNvbnN0IHVwbG9hZERhdGEgPSByZWFjdGl2ZTx7XG4gIGtleTogc3RyaW5nO1xufT4oe1xuICBrZXk6ICcnLFxufSk7XG5cbmNvbnN0IGJlZm9yZVVwbG9hZDogVXBsb2FkUHJvcHNbJ2JlZm9yZVVwbG9hZCddID0gKHJhd0ZpbGU6IFVwbG9hZFJhd0ZpbGUpID0+IHtcbiAgdXBsb2FkRGF0YS5rZXkgPSBgJHtyYXdGaWxlLm5hbWV9YDtcbn07XG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAoZmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2coZmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9ICh1cGxvYWRGaWxlKSA9PiB7XG4gIGNvbnNvbGUubG9nKHVwbG9hZEZpbGUpXG59XG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIEVsTWVzc2FnZS53YXJuaW5nKFxuICAgIGBUaGUgbGltaXQgaXMgMywgeW91IHNlbGVjdGVkICR7ZmlsZXMubGVuZ3RofSBmaWxlcyB0aGlzIHRpbWUsIGFkZCB1cCB0byAke1xuICAgICAgZmlsZXMubGVuZ3RoICsgdXBsb2FkRmlsZXMubGVuZ3RoXG4gICAgfSB0b3RhbGx5YFxuICApXG59XG5cbmNvbnN0IGJlZm9yZVJlbW92ZTogVXBsb2FkUHJvcHNbJ2JlZm9yZVJlbW92ZSddID0gKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIHJldHVybiBFbE1lc3NhZ2VCb3guY29uZmlybShcbiAgICBgQ2FuY2VsIHRoZSB0cmFuc2ZlcnQgb2YgJHt1cGxvYWRGaWxlLm5hbWV9ID9gXG4gICkudGhlbihcbiAgICAoKSA9PiB0cnVlLFxuICAgICgpID0+IGZhbHNlXG4gIClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

将文件名数据存储在上传组件的data数据中，在beforeUpload这个事件中修改data中的数据文件名，上传多个文件data数据会被覆盖，最后多个文件post的数据都是同一个文件名

### What is Expected?

期望每个文件返回不同的文件名

### What is actually happening?

多个文件是同一个名字

### Additional comments

这个bug之前就有人提过，你们看不看就给关了？？？
https://github.com/element-plus/element-plus/issues/6700
就是这个bug提的问题

**Comment by mxismean** [comment]
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/44690729/224888393-edd8f571-b268-474c-8fc5-badcd0b52e24.png">
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/44690729/224888576-e059862e-ac5b-4644-9e7a-40ef2cfa29fd.png">
同时上传 3个文件，命名分别是 50 ，70 ，90 。但是 上传的时候命名都会被最后的一个覆盖掉，导致前面俩的命名都变成了90

**Comment by chenxch** [comment]
@mxismean 并没有看不看就关闭了，那个issue标签来看当时是需要用户提供一个相关的repo，标记tag之后，用户没有提供而自动关闭，如果是想解决问题的话，我想自己应该也要重视issue上的反馈，和提供相关信息，这个东西是相互的，希望理解。

**Comment by mxismean** [comment]
> @mxismean 并没有看不看就关闭了，那个issue标签来看当时是需要用户提供一个相关的repo，标记tag之后，用户没有提供而自动关闭，如果是想解决问题的话，我想自己应该也要重视issue上的反馈，和提供相关信息，这个东西是相互的，希望理解。

好的 明白。 提供了一个简单的复现demo，麻烦看一下哦

**Comment by jianjunyuu** [comment]
主要的原因：修改data是同步的，upload 获取data是异步，导致获取的data是最后一次修改的
解决方案
1. 上传data在合适的时机备份（已经提pr）
2. 在创建上次任务的使用使用队列

具体方案得看组件设计的一个出发点
@chenxch

**Comment by mxismean** [comment]
我看昨天发布的 2.3.1 版本好像没有包含这个bug的修复，想了解一下这个bug大概会在 哪个版本？ 什么时候？ 发布呢。因为目前公司线上环境在使用中被这个问题带来了一些业务上的影响 @chenxch

**Comment by chenxch** [comment]
@mxismean 这个pr由于还缺少另一位reviewer的approve，所以目前还没merge在主分支，我cc一下小伙伴看看，如果通过的话，最快应该就是这周五会发布。

**Comment by mxismean** [comment]
> @mxismean 这个pr由于还缺少另一位reviewer的approve，所以目前还没merge在主分支，我cc一下小伙伴看看，如果通过的话，最快应该就是这周五会发布。

好的  谢谢
