### ISSUE TITLE
[Component] [cascader] cascader级联选择器，chrome和火狐等浏览器点击本身窗口隐藏掉当前窗口

### ISSUE THREAD

**Issue by zhugehanxin** [element-plus/element-plus#12013]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.0`
- Browser / OS: `chrome 109.0.5414.120`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html)

### Steps to reproduce

直接打开官网的cascader页面，点击一个级联选择器。点击当前级联弹框的选项，都会隐藏级联窗口。

### What is Expected?

点击级联窗口，窗口不会隐藏。

### What is actually happening?

点击级联窗口，窗口隐藏掉了。

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
fixed #11997
