### ISSUE TITLE
If the initial value of the switch initialization binding is not in active value or inactive value, the change event will be triggered

### ISSUE THREAD

**Issue by zcmk123** [element-plus/element-plus#1202]
不是很明白为什么要这么做？
我在change事件中有逻辑处理，是按钮触发的。这样导致我的事件被提前触发了

https://github.com/element-plus/element-plus/blob/c5fc8b4e9a98de4252c19fe9a653cfe9e977b4c5/packages/switch/src/index.vue#L167

**Comment by Ryan2128** [comment]
Because the accepted default value of the switch is `boolean`, if you want to expand to a `string` or `number` type value, you should use these two props to replace true and false.

**Comment by zcmk123** [comment]
> Because the accepted default value of the switch is `boolean`, if you want to expand to a `string` or `number` type value, you should use these two props to replace `true` and `false`. At this time, if the default value passed in is not in the two props, `inactiveValue` will be emitted by `change` event.
> 
> Therefore, the reason for emitting the `change` event is that your `modelValue` is not one of these two props.

我应该知道问题是出在哪了。。。我结合表格一起用的，在el-table-column的slot里面放了一个switch，然后slot里面返回的第一个index是-1，row是空的。switch绑定值也是空的，所以就触发了switch那个change逻辑
![image](https://user-images.githubusercontent.com/20919760/103727088-55443200-5015-11eb-926a-d69e2a57cfa6.png)

**Comment by JeremyWuuuuu** [comment]
@zcmk123 So the bug can be fixed by yourself right?

**Comment by zcmk123** [comment]
> @zcmk123 So the bug can be fixed by yourself right?

Yes.... but can you explain table column index = -1 ?

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by justwiner** [comment]
In `table-column`, the first rendering is to help construct the virtual structure of the table, the actual rendering is not in the render function. 
https://github.com/element-plus/element-plus/blob/e844ede9ce45a5c15357bcd3ebcf82afe3f07d67/packages/table/src/table-column/index.ts#L212-L227
In the current implementation, it is inevitable, i will try to optimize this code later, but it will take time because there are more places involved

**Comment by zcmk123** [comment]
> In `table-column`, the first rendering is to help construct the virtual structure of the table, the actual rendering is not in the render function.
> https://github.com/element-plus/element-plus/blob/e844ede9ce45a5c15357bcd3ebcf82afe3f07d67/packages/table/src/table-column/index.ts#L212-L227
> 
> 
> In the current implementation, it is inevitable, i will try to optimize this code later, but it will take time because there are more places involved

thx, currently i can just skip $index = -1

**Comment by zcmk123** [comment]
problem solved
