### ISSUE TITLE
[Component] [tree-select] treeSelect多选懒加载情况下，传参cacheData，并且设置了回显数据，打开选择节点后会清空之前回显的数据

### ISSUE THREAD

**Issue by liuyifan1** [element-plus/element-plus#12026]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.4`
- Element Plus Version: `2.2.27`
- Browser / OS: `e.g. Chrome 105.0.5195.127`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZVN0cmljdGx5ID0gcmVmKFs1LCAxMV0pXG5jb25zdCBjYWNoZURhdGEgPSBbeyB2YWx1ZTogNSwgbGFiZWw6ICdsYXp5IGxvYWQgbm9kZTUnIH0sIHsgdmFsdWU6IDExLCBsYWJlbDogJ2xhenkgbG9hZCBub2RlMTEnIH1dXG5cbmNvbnN0IHByb3BzID0ge1xuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGlzTGVhZjogJ2lzTGVhZicsXG59XG5cbmxldCBpZCA9IDBcblxuY29uc3QgbG9hZCA9IChub2RlOiBhbnksIHJlc29sdmU6IGFueSkgPT4ge1xuICBpZiAobm9kZS5pc0xlYWYpIHJldHVybiByZXNvbHZlKFtdKVxuXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIHJlc29sdmUoW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogKytpZCxcbiAgICAgICAgbGFiZWw6IGBsYXp5IGxvYWQgbm9kZSR7aWR9YCxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiArK2lkLFxuICAgICAgICBsYWJlbDogYGxhenkgbG9hZCBub2RlJHtpZH1gLFxuICAgICAgICBpc0xlYWY6IHRydWUsXG4gICAgICB9LFxuICAgIF0pXG4gIH0sIDQwMClcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVN0cmljdGx5XCIgbGF6eSA6bG9hZD1cImxvYWRcIiA6cHJvcHM9XCJwcm9wc1wiIDpjYWNoZS1kYXRhPVwiY2FjaGVEYXRhXCIgbXVsdGlwbGVcbiAgICAgICAgICAgICAgICA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCIgc2hvdy1jaGVja2JveCBjaGVjay1zdHJpY3RseSAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.点击出现下拉框
2.选择第一个节点

### What is Expected?

选择节点后不会清空回显数据

### What is actually happening?

如果已经展开的树节点中没有回显数据，选择节点后，就会清空回显数据

### Additional comments

_(empty)_

**Comment by xakoy** [comment]
同样的问题

**Comment by ZGH0717** [comment]
同样的问题
