### ISSUE TITLE
[Style] [tabs] el-tabs的添加标签页操作按钮图标颜色不对

### ISSUE THREAD

**Issue by FightingJane** [element-plus/element-plus#12028]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/111.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgIDxlbC10YWItcGFuZSBrZXk9XCJhZGRcIiBuYW1lPVwiYWRkXCI+XG4gICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICArICAgICAgICAgXG4gICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgICAgIDxlbC10YWItcGFuZSBrZXk9XCJhZGRcIiBuYW1lPVwiYWRkXCI+XG4gICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiA8RWRpdCBzdHlsZT1cIndpZHRoOiAxZW07IGhlaWdodDogMWVtOyBtYXJnaW4tcmlnaHQ6IDhweFwiIC8+XG4gICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFZGl0IH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdGFiSW5kZXggPSAyXG5jb25zdCBlZGl0YWJsZVRhYnNWYWx1ZSA9IHJlZignMicpXG5jb25zdCBlZGl0YWJsZVRhYnMgPSByZWYoW1xuICB7XG4gICAgdGl0bGU6ICdUYWIgMScsXG4gICAgbmFtZTogJzEnLFxuICAgIGNvbnRlbnQ6ICdUYWIgMSBjb250ZW50JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnVGFiIDInLFxuICAgIG5hbWU6ICcyJyxcbiAgICBjb250ZW50OiAnVGFiIDIgY29udGVudCcsXG4gIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVUYWJzRWRpdCA9ICh0YXJnZXROYW1lOiBzdHJpbmcsIGFjdGlvbjogJ3JlbW92ZScgfCAnYWRkJykgPT4ge1xuICBpZiAoYWN0aW9uID09PSAnYWRkJykge1xuICAgIGNvbnN0IG5ld1RhYk5hbWUgPSBgJHsrK3RhYkluZGV4fWBcbiAgICBlZGl0YWJsZVRhYnMudmFsdWUucHVzaCh7XG4gICAgICB0aXRsZTogJ05ldyBUYWInLFxuICAgICAgbmFtZTogbmV3VGFiTmFtZSxcbiAgICAgIGNvbnRlbnQ6ICdOZXcgVGFiIGNvbnRlbnQnLFxuICAgIH0pXG4gICAgZWRpdGFibGVUYWJzVmFsdWUudmFsdWUgPSBuZXdUYWJOYW1lXG4gIH0gZWxzZSBpZiAoYWN0aW9uID09PSAncmVtb3ZlJykge1xuICAgIGNvbnN0IHRhYnMgPSBlZGl0YWJsZVRhYnMudmFsdWVcbiAgICBsZXQgYWN0aXZlTmFtZSA9IGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlXG4gICAgaWYgKGFjdGl2ZU5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICAgIHRhYnMuZm9yRWFjaCgodGFiLCBpbmRleCkgPT4ge1xuICAgICAgICBpZiAodGFiLm5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICAgICAgICBjb25zdCBuZXh0VGFiID0gdGFic1tpbmRleCArIDFdIHx8IHRhYnNbaW5kZXggLSAxXVxuICAgICAgICAgIGlmIChuZXh0VGFiKSB7XG4gICAgICAgICAgICBhY3RpdmVOYW1lID0gbmV4dFRhYi5uYW1lXG4gICAgICAgICAgfVxuICAgICAgICB9XG4gICAgICB9KVxuICAgIH1cblxuICAgIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gYWN0aXZlTmFtZVxuICAgIGVkaXRhYmxlVGFicy52YWx1ZSA9IHRhYnMuZmlsdGVyKCh0YWIpID0+IHRhYi5uYW1lICE9PSB0YXJnZXROYW1lKVxuICB9XG59XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击链接就可以看到，最右侧点击加号的图标颜色和左边tab的字体颜色不一样，应该是缩放导致了图标模糊。
无论tab改什么颜色都是一样的效果。
浏览器放大到300%两边颜色才一样

### What is Expected?

加号的图标颜色和左边tab的字体颜色一样

### What is actually happening?

加号的图标颜色和左边tab的字体颜色不一样

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
其实颜色是一样的，可以把加号换成icon的<Plus>试试

**Comment by FightingJane** [comment]
![image](https://user-images.githubusercontent.com/13446642/225274302-574da690-b3ff-4e66-9505-e7221d16a90c.png)
怎么会一样呢，您看tab1的颜色和右边加号的颜色，明显失真了
![image](https://user-images.githubusercontent.com/13446642/225277167-5c1de88b-ed05-4320-885c-55ae24bc25f7.png)
hover 的颜色也更浅

**Comment by FightingJane** [comment]
> 其实颜色是一样的，可以把加号换成icon的试试，倒是图标与文字对齐是有点问题。

这个加号就是icon的，官网也不支持替换别的icon

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/225483198-2c257c6c-a95e-4712-b0b0-8d5ef3d12bfa.png)
哦哦，我理解错了，以为你说的第一个加号，第二个加号是颜色的固定的，可以通过样式覆盖。

**Comment by FightingJane** [comment]
对的，好像都存在这种问题，看了下官网的button按钮，也是这样子的。
![image](https://user-images.githubusercontent.com/13446642/225495301-99d83e97-be97-466c-a33e-48924a575cc0.png)
