### ISSUE TITLE
[Bug Report] select showing "No matching data" below options when modelValue doesn't match with any of the options

### ISSUE THREAD

**Issue by TMantas** [element-plus/element-plus#1203]
### Element Plus version
1.0.1-beta.20

### OS/Browsers version
any

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/mantas-t/pen/MWjGQqa

### Steps to reproduce
- create filterable select
- pass model-value something which if not in the options
- open select and you'll see "No matching data" (no-match-text) below options

### What is Expected?
it shouldn't show "No matching data" (no-match-text)

### What is actually happening?
it is shown

**Comment by Ryan2128** [comment]
It is a normal behavior, just a reminder, if you don’t want it, you can change it with `no-match-text`.

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/103734808-ab21d580-5027-11eb-9a69-053dbd59c86c.png)
Seems odd, when `model-value` was initially bound to some value, even though there were literally no match but the option still shows up

**Comment by JeremyWuuuuu** [comment]
@Ryan2128  You fine with this fix? I do think that the code didn't anticipate situations like this. We should check modelValue when `filter` is enabled.

**Comment by Ryan2128** [comment]
> @Ryan2128 You fine with this fix? I do think that the code didn't anticipate situations like this. We should check modelValue when `filter` is enabled.

OK.
