### ISSUE TITLE
[Component] [radio-button] el-radio-button设置值时的显示错误

### ISSUE THREAD

**Issue by ixifree** [element-plus/element-plus#12046]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41`
- Build Tool: `Vite`

### Related Component

- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW9cIiBzaXplPVwibGFyZ2VcIj5cbiAgICAgIDxlbC1yYWRpbyBsYWJlbD1cIk5ldyBZb3JrXCIgLz5cbiAgICAgIDxlbC1yYWRpbyBsYWJlbD1cIldhc2hpbmd0b25cIiAvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiTG9zIEFuZ2VsZXNcIiAvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiQ2hpY2Fnb1wiIC8+XG4gICAgPC9lbC1yYWRpby1ncm91cD5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvXCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiTmV3IFlvcmtcIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIldhc2hpbmd0b25cIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIkxvcyBBbmdlbGVzXCIgLz5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJDaGljYWdvXCIgLz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHJlYWwgPSByZWYoJ05ldyBZb3JrJylcbmNvbnN0IHJhZGlvID0gY29tcHV0ZWQoe1xuICBnZXQ6ICgpID0+IHJlYWwudmFsdWUsXG4gIHNldDogYXN5bmModmFsOiBhbnkpID0+IHtcbiAgICB0cnkge1xuICAgICAgYXdhaXQgRWxNZXNzYWdlQm94LmNvbmZpcm0oXG4gICAgICAgICdDb250aW51ZT8nLFxuICAgICAgICAnV2FybmluZycsXG4gICAgICAgIHtcbiAgICAgICAgICBjb25maXJtQnV0dG9uVGV4dDogJ09LJyxcbiAgICAgICAgICBjYW5jZWxCdXR0b25UZXh0OiAnQ2FuY2VsJyxcbiAgICAgICAgICB0eXBlOiAnd2FybmluZycsXG4gICAgICAgIH1cbiAgICAgIClcbiAgICAgIHJlYWwudmFsdWUgPSB2YWxcbiAgICAgIEVsTWVzc2FnZSh7XG4gICAgICAgIHR5cGU6ICdzdWNjZXNzJyxcbiAgICAgICAgbWVzc2FnZTogYGNvbXBsZXRlZCBzZXQgJHt2YWx9YCxcbiAgICAgIH0pXG4gICAgfSBjYXRjaCB7XG4gICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICB0eXBlOiAnaW5mbycsXG4gICAgICAgIG1lc3NhZ2U6IGBjYW5jZWxlZCBzZXQgJHt2YWx9YCxcbiAgICAgIH0pXG4gICAgfVxuXHR9XG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

使用computed控制el-radio-group，在set时发生操作中断，el-radio-button无法正确显示，而el-radio不会发生该错误。
点击第二个el-radio-group的某一个，弹出ElMessageBox后Cancel。

### What is Expected?

正确显示

### What is actually happening?

无法正确显示

### Additional comments

_(empty)_

**Comment by beikeliu** [comment]
ElMessageBox，Cancel事件，导致了el-radio-group组件丢失了model-value的绑定。

**Comment by beikeliu** [comment]
您好，我尝试在catch块添加以下代码，问题已进行解决。
```javascript
    const temp = real.value;
    real.value = undefined;
    setTimeout(() => {
      real.value = temp;
    })

**Comment by beikeliu** [comment]
发送失败！

**Comment by gimjin** [comment]
我感觉你这样写是有问题的，并不是element-plus的问题，而是你没有遵循vuejs的规范。

```javascript
// https://cn.vuejs.org/api/reactivity-core.html#computed
function computed<T>(
  options: {
    get: () => T
    set: (value: T) => void
  },
  debuggerOptions?: DebuggerOptions
): Ref<T>
```

set 返回值是 void，但是你返回的是 Promise，如果vue官方支持set异步的话返回值可能是多种类型而不会只用 viod.

**Comment by ixifree** [comment]
> 我感觉你这样写是有问题的，并不是element-plus的问题，而是你没有遵循vuejs的规范。
> 
> ```js
> // https://cn.vuejs.org/api/reactivity-core.html#computed
> function computed<T>(
>   options: {
>     get: () => T
>     set: (value: T) => void
>   },
>   debuggerOptions?: DebuggerOptions
> ): Ref<T>
> ```
> 
> set 返回值是 void，但是你返回的是 Promise，如果vue官方支持set异步的话返回值可能是多种类型而不会只用 viod.

感谢您的回复，我查看了vue的官方文档，按文档的说法set确实应当是同步操作。
这其实是这样的业务场景，当我选择某个radio的时候，我希望先检查是否可以设置为这个值，这个检查的过程我希望在触发变更时进行，而不是简单将该radio disable掉，恰巧这个检查的过程可能是异步的，也许用@change和watch()等组成的更复杂的逻辑也可以做到这件事，但它们也许需要先将绑定的值进行变更，接着再撤销变更。
我reopen的原因其实如我之前的回复所言，el-radio-button和el-radio对于显示状态的处理貌似是不同的，这导致了当el-radio-button在鼠标点击时就已经变成未选中的状态，虽然我可以修改修改我的程序以实现我的业务需求，但我希望element-plus可以将显示状态的处理统一化，#12050 看上去做的就是这样一件事，不过我不知道这是否会带来新的副作用。

**Comment by gimjin** [comment]
我看了[element-plus源码](https://github.com/element-plus/element-plus/blob/dev/packages/components/radio/src/radio-button.vue#L2) 其实 el-radio-group 也是受控组件。
你点击某个按钮时其实是点击了 label 标签，然后label触发让内部input修改了值，html radio标签的值已经发生变化，既定事实已经发生。

#12050 是想通过css效果上做了调整
#12052 是通过 changeEvent 发生时强行调整值来解决问题
的确上面的解决方案确实是改善了问题，不过 html 中radio的checked状态已经触发过，可能会存在隐患

我的看法是从 html input radio 与 el-radio-button 的状态应保持一致，html input radio 不应该只是作为傀儡存在，不然会加重代码可读性的问题导致很难维护。

从用户体验的角度，enable状态是标识用户可以选择，然后用户选择的时候告知不可选择，这种需求本身就是忽悠用户成分很多。 不能选择的按钮应该disable，然后需要提示可以加入 el-tooltip 提示用户为何不允许选择。
