### ISSUE TITLE
[Component] [select-v2] el-select-v2  点击选项 不回显

### ISSUE THREAD

**Issue by aBrightWorld** [element-plus/element-plus#12047]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `google`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxubGV0IGRhdGEgPSByZWFjdGl2ZSh7XG4gIGRhdGFObzE6IG51bGwsXG4gICAgICBkYXRhU291cmNlTGlzdDogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJzFhJyxcbiAgICAgICAgZmllbGQ6ICdhMSdcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMmEnLFxuICAgICAgICBmaWVsZDogJ2EyJ1xuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICczYScsXG4gICAgICAgIGZpZWxkOiAnYTMnXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzRhJyxcbiAgICAgICAgZmllbGQ6ICdhNCdcbiAgICAgIH0sXG4gICAgXVxufSlcbmxldCBkYXRhTm9DaGFuZ2UgPSAodmFsKSA9PiB7XG4gIGNvbnNvbGUubG9nKHZhbClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPnt7SlNPTi5zdHJpbmdpZnkoZGF0YS5kYXRhTm8xKSB9fTwvcD5cbiAgIDxlbC1zZWxlY3QtdjIgdi1tb2RlbD1cImRhdGEuZGF0YU5vMVwiXG4gICAgICAgICAgICAgICAgICAgICAgOm9wdGlvbnM9XCJkYXRhLmRhdGFTb3VyY2VMaXN0XCJcbiAgICAgICAgICAgICAgICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCLor7fpgInmi6nlrZfmrrXlkI3np7BcIlxuICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgICAgICAgICAgICAgICAgICBAY2hhbmdlPVwiZGF0YU5vQ2hhbmdlXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBpdGVtIH1cIj5cbiAgICAgICAgICAgIDxwPnt7aXRlbX19PC9wPlxuICAgICAgICAgICAgPHNwYW4+e3sgaXRlbS5maWVsZCB9fTwvc3Bhbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuXG48IS0tICAgICAgICAgIDxlbC1vcHRpb24tLT5cbjwhLS0gICAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gcHJvcHMuZGF0YVNvdXJjZUxpc3RcIi0tPlxuPCEtLSAgICAgICAgICAgIDprZXk9XCJpdGVtLmRhdGFOb1wiLS0+XG48IS0tICAgICAgICAgICAgOmxhYmVsPVwiaXRlbS5maWVsZFwiLS0+XG48IS0tICAgICAgICAgICAgOnZhbHVlPVwiaXRlbS5kYXRhTm9cIi0tPlxuPCEtLSAgICAgICAgICAvPi0tPlxuICAgICAgICA8L2VsLXNlbGVjdC12Mj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

  <el-select-v2 v-model="data.dataNo1"
                      :options="data.dataSourceList"
                      filterable
                      placeholder="请选择字段名称"
                      style="width: 240px"
                      @change="dataNoChange">
          <template #default="{ item }">
            <p>{{item}}</p>
            <span>{{ item.field }}</span>
          </template>

    dataSourceList: [
      {
        value: '1a',
        field: 'a1'
      },
      {
        value: '2a',
        field: 'a2'
      },
      {
        value: '3a',
        field: 'a3'
      },
      {
        value: '4a',
        field: 'a4'
      },
    ]

change事件正常调用，就是输入框显示任何东西

### What is Expected?

显示value

### What is actually happening?

不显示value

### Additional comments

_(empty)_

**Comment by Mario34** [comment]
```js
{
  value: '1a',
  label: 'a1'
}
```
options改下格式是不是就行了，默认使用对象label回显的

**Comment by aBrightWorld** [comment]
找到问题所在了，是因为字段必须使用label。我用的field
