### ISSUE TITLE
[Component] [input-number, dialog] 当数字输入框，遇到对话框，绑定的值会出现不正确的情况。

### ISSUE THREAD

**Issue by DXD2019** [element-plus/element-plus#12057]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76`
- Build Tool: `Vite`

### Related Component

- `el-input-number`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uICBAY2xpY2s9XCJ2ID0gdHJ1ZVwiPlxuICAg5omT5byAXG4gIDwvZWwtYnV0dG9uPlxuICBcbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCIgIEBpbnB1dD1cImhhbmRsZUNoYW5nZVwiIC8+ICAg5q2k5pe255qE5YC877yae3tudW19fVxuICBcbiAgIDxlbC1kaWFsb2cgdi1tb2RlbD1cInZcIiB0aXRsZT1cIlwiIHdpZHRoPVwiMzAlXCI+XG5cdFx0XHRcdHRlc3RcbiAgPC9lbC1kaWFsb2c+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgdj1yZWYoZmFsc2UpXG5cbmNvbnN0IG51bSA9IHJlZigxKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbHVlOiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG4gIC8vbnVtLnZhbHVlPXZhbHVlXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

先输入10，点击按钮打开对话框，关闭对话框。10后面再输入0，再退格键删除0。此时变量值仍为100，输入框的值为10。@input事件中的值正常。10=>打开对话框=>100=>10 全部删除后再输入又会正常，打开一次对话框后继续输入，退格删除就会不正常。
```vue
<template>
  <el-button  @click="v = true">
   test
  </el-button>
  <el-input-number v-model="num"  @input="handleChange" />  
  此时的值：{{num}}
  <el-dialog v-model="v" title="" width="30%">
  test
  </el-dialog>  
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const v=ref(false)
const num = ref(1)
const handleChange = (value: number) => {
  console.log(value)
  //num.value=value
}
</script>
```

### What is Expected?

正常更新变量的值

### What is actually happening?

双向绑定的值无法正常更新

### Additional comments

_(empty)_

**Comment by Mario34** [comment]
这个问题已经修复了[PR12007  Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uICBAY2xpY2s9XCJ2ID0gdHJ1ZVwiPlxuICAg5omT5byAXG4gIDwvZWwtYnV0dG9uPlxuICBcbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCIgIEBpbnB1dD1cImhhbmRsZUNoYW5nZVwiIC8+ICAg5q2k5pe255qE5YC877yae3tudW19fVxuICBcbiAgIDxlbC1kaWFsb2cgdi1tb2RlbD1cInZcIiB0aXRsZT1cIlwiIHdpZHRoPVwiMzAlXCI+XG5cdFx0XHRcdHRlc3RcbiAgPC9lbC1kaWFsb2c+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgdj1yZWYoZmFsc2UpXG5cbmNvbnN0IG51bSA9IHJlZigxKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbHVlOiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG4gIC8vbnVtLnZhbHVlPXZhbHVlXG59XG48L3NjcmlwdD5cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMjAwNy1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEyMDA3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTEyMDA3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ1xuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICB9KVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTEyMDA3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)，等发布新版本及时更新 @DXD2019

**Comment by HeftyKoo** [comment]
确认问题已经在 2.3.1 版本修复
