### ISSUE TITLE
[Bug Report] el-select is not as expected work

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#1205]
### Element Plus version
1.0.1-beta.20

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xingxiaowu/pen/jOMxJbb

### Steps to reproduce
1.change first select

2.change second select

3.select button

### What is Expected?
Q1: If select2 have value, when change select1's value I hope the select2's value can be ''

Q2: I hope the select1's show and select2's show can be '' when I click the button to set they value ''

### What is actually happening?
value changed but show is not work for expected

**Comment by JeremyWuuuuu** [comment]
。。
You just make ref to string...

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/103734274-942eb380-5026-11eb-84f7-1558327685f4.png)
I beg you guys, please do verify the code before submitting issue, this is simply waste of time.

**Comment by JeremyWuuuuu** [comment]
BTW, your code:
![image](https://user-images.githubusercontent.com/15975785/103734334-b88a9000-5026-11eb-960f-1354a09332d3.png)

![image](https://user-images.githubusercontent.com/15975785/103734319-b0caeb80-5026-11eb-8797-db8e8efb0c99.png)

Do you think that was legit?

**Comment by XingXiaoWu** [comment]
Sorry, I forgot to write  .value...

**Comment by JeremyWuuuuu** [comment]
Please double check if the error was caused by yourself, you are welcome to open issues, but issues like this is just waste of time.

**Comment by XingXiaoWu** [comment]
I'm sorry

**Comment by XingXiaoWu** [comment]
I left out some of the conditions so that when you refresh options and values at the same time, the show will not be cleared.
Please look at https://codepen.io/xingxiaowu/pen/jOMxJbb
thx

**Comment by JeremyWuuuuu** [comment]
Seems that's some sort of issue, temporary fix would be moving any one of that mutation inside a `nextTick`.
E.g.
![image](https://user-images.githubusercontent.com/15975785/103735790-c857a380-5029-11eb-901b-77a1520619c9.png)
or switch the position for the value mutation and option mutation.

**Comment by JeremyWuuuuu** [comment]
Even though I think operations like this won't happen that frequently, but it still needs to be fixed, could you open another issue for tracking this?

**Comment by XingXiaoWu** [comment]
OK

**Comment by JeremyWuuuuu** [comment]
You don't need to write all the issue text in English, translate bot translates that for you, write it in Chinese is fine.

**Comment by XingXiaoWu** [comment]
https://github.com/element-plus/element-plus/issues/1207

好吧，英语不太好，尴尬了😅我已经创建了新的
