### ISSUE TITLE
[Component] [date-picker] 日期问题  时间格式化 不对 差了 12个小时  type="datetimerange"

### ISSUE THREAD

**Issue by zhouyujie15014426398** [element-plus/element-plus#12055]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome 已是最新版本 版本 111.0.5563.65（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmxldCBlbmQgPSBuZXcgRGF0ZSgpXG5sZXQgeWVhciA9IGVuZC5nZXRGdWxsWWVhcigpXG5sZXQgbW9udGggPSBlbmQuZ2V0TW9udGgoKVxubGV0IGRheSA9IGVuZC5nZXREYXRlKClcbmxldCBzdGFydCA9IG5ldyBEYXRlKHllYXIsIG1vbnRoLCBkYXksIDAsIDAsIDApXG5lbmQgPSBuZXcgRGF0ZSh5ZWFyLCBtb250aCwgZGF5LCAyMywgNTksIDU5KVxuXG5jb25zdCB0aW1lQXJyID0gcmVmKFtdKVxuY29uc3QgdmFsdWVGb3JtYXQgPSAnWVlZWS1NTS1ERCBoaDptbTpzcydcbmNvbnN0IGRpc2FibGVkRGF0ZSA9IChkYXRlKSA9PiBkYXRlID4gZW5kXG5sZXQgZGVmYXVsdFRpbWVBcnIgPSByZWYoW3N0YXJ0LCBlbmRdKSAvLyDnm67liY3mnIlidWdcblxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+5pys5p2l5pyf5pyb6YCJ5Lit55qE5pe26Ze05qC85byP5Li6IDwvaDE+XG4gIDxoMT4yMDIzLTAzLTA1IDAwOjAwOjAwIOiHsyAyMDIzLTAzLTE1IDIzOjU5OjU5IDwvaDE+XG4gXG4gIDxlbC1kYXRlLXBpY2tlclxuICAgIHYtbW9kZWw9XCJ0aW1lQXJyXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgZW5kLXBsYWNlaG9sZGVyPVwi57uT5p2f5pe26Ze0XCJcblxuICAgIHJhbmdlLXNlcGFyYXRvcj1cIuiHs1wiXG4gICAgc3RhcnQtcGxhY2Vob2xkZXI9XCLlvIDlp4vml7bpl7RcIlxuICAgIGNsZWFyYWJsZVxuICAgIDp2YWx1ZS1mb3JtYXQ9XCJ2YWx1ZUZvcm1hdFwiXG4gICAgOmRpc2FibGVkLWRhdGU9XCJkaXNhYmxlZERhdGVcIlxuICAgIDpkZWZhdWx0LXRpbWU9XCJkZWZhdWx0VGltZUFyclwiXG4gIC8+XG4gPGgxPum7mOiupOW8gOWni+aXtumXtOWwseW4ruaIkemAieS4iiAwMDowMDowMCAgPC9oMT5cbiAgPGgxPum7mOiupOe7k+adn+aXtumXtOWwseW4ruaIkemAieS4iiAyMzo1OTo1OSAgPC9oMT5cbiAgPGgxPuWPr+aYr+mAieS6huS5i+WQjiAg5bGF54S25piv5Zu96ZmF5pe26Ze05beuIOW3ruS6hjEy5Liq5bCP5pe2IDwvaDE+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gICAgXG4gIDwvcD5cbiAgPHAgc3R5bGU9XCJmb250LXNpemU6IDMwcHg7IGZvbnQtd2VpZ2h0O1wiPui/memHjOaXtumXtOW3rui/nOS6hiDlj7PovrnnmoTmnpzlt67ov5zkuoYgPC9wPlxuICBcbiAgPGRpdiBzdHlsZT1cImZvbnQtc2l6ZTogNjBweDsgZm9udC13ZWlnaHQ7XCI+XG4gICAgXG4gICAgPHNwYW4gc3R5bGU9XCJjb2xvcjogI2Y0NFwiPnt7dGltZUFycn19PC9zcGFuPlxuICA8L2Rpdj5cbiAgPGhyPlxuICAgXG4gIDxkaXYgPlxuICAgXG4gIDwvZGl2PlxuIDwvdGVtcGxhdGU+XG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<script setup>
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

let end = new Date()
let year = end.getFullYear()
let month = end.getMonth()
let day = end.getDate()
let start = new Date(year, month, day, 0, 0, 0)
end = new Date(year, month, day, 23, 59, 59)

const timeArr = ref([])
const valueFormat = 'YYYY-MM-DD hh:mm:ss'
const disabledDate = (date) => date > end
let defaultTimeArr = ref([start, end]) // 目前有bug

</script>

<template>
  <h1>本来期望选中的时间格式为 </h1>
  <h1>2023-03-05 00:00:00 至 2023-03-15 23:59:59 </h1>
 
  <el-date-picker
    v-model="timeArr"
    type="datetimerange"
    end-placeholder="结束时间"

    range-separator="至"
    start-placeholder="开始时间"
    clearable
    :value-format="valueFormat"
    :disabled-date="disabledDate"
    :default-time="defaultTimeArr"
  />
 <h1>默认开始时间就帮我选上 00:00:00  </h1>
  <h1>默认结束时间就帮我选上 23:59:59  </h1>
  <h1>可是选了之后  居然是国际时间差 差了12个小时 </h1>
  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
    
  </p>
  <p style="font-size: 30px; font-weight;">这里时间差远了 右边的果差远了 </p>
  
  <div style="font-size: 60px; font-weight;">
    
    <span style="color: #f44">{{timeArr}}</span>
  </div>
  <hr>
   
  <div >
   
  </div>
![872EA87D-563E-400d-969B-450F8BFC7ACE](https://user-images.githubusercontent.com/29453185/225305385-f507162e-c356-4948-b569-19908335ccb7.png)
![E7196806-DEC4-4c1a-ADD4-E3AA7A344A74](https://user-images.githubusercontent.com/29453185/225305393-28d6c231-e268-4d37-8190-26c71824bbcb.png)

 </template>

### What is Expected?

2023-03-05 00:00:00 至 2023-03-15 23:59:59

### What is actually happening?

2023-03-05 12:00:00 至 2023-03-15 11:59:59

### Additional comments

就是加齐了参数就不行

**Comment by gyt95** [comment]
valueFormat错了，你想用24小时制就要用HH，而不是hh

参考：https://day.js.org/docs/en/display/format#list-of-all-available-formats
