### ISSUE TITLE
'"element-plus"' 沒有任何名稱為 'TableColumnCtx' 的已匯出成員。您是指 'ElTableColumn' 嗎?ts(2724)

### ISSUE THREAD

**Issue by mukiwu** [element-plus/element-plus#12069]
### Element Plus version
2.2.34

### OS/Browsers version
chrome 110.0.5481.177

### Vue version
3.2.41

### Steps to reproduce
import type { TableColumnCtx } from 'element-plus'

出現錯誤：
'"element-plus"' 沒有任何名稱為 'TableColumnCtx' 的已匯出成員。您是指 'ElTableColumn' 嗎?ts(2724)

### What is Expected?
修復

### What is actually happening?
無

**Comment by kooriookami** [comment]
在先前的PR中已经修复了此问题，#10677，尝试更新到最新版本试试呢。
