### ISSUE TITLE
[Component] [select, infinite-scroll] select组件为何使用不了 Infinite Scroll（无限滚动）

### ISSUE THREAD

**Issue by sanmuw** [element-plus/element-plus#12075]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/mac`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-infinite-scroll`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIFxuIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgdi1pZj1cImlzTW91bnRlZFwiPlxuICAgIDxkaXYgdi1pbmZpbml0ZS1zY3JvbGw9XCJsb2FkXCIgXG5pbmZpbml0ZS1zY3JvbGwtZGlzdGFuY2U9XCIyMFwiXG4gICAgICAgICBzdHlsZT1cImhlaWdodDoyMDBweDtcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgICAgICAgICAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmRpc2FibGVkPVwiaXRlbS5kaXNhYmxlZFwiXG4gICAgLz5cbiAgICA8L2Rpdj5cblxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbiAgXG4gIGNvbnN0IGlzTW91bnRlZCA9IHJlZihmYWxzZSlcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbiAgICB7XG4gICAgdmFsdWU6ICdPcHRpb242JyxcbiAgICBsYWJlbDogJ09wdGlvbjYnLFxuICB9LFxuICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uNycsXG4gICAgbGFiZWw6ICdPcHRpb243JyxcbiAgfSxcbiAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sXG4gICAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSwgICAgICB7XG4gICAgdmFsdWU6ICdPcHRpb244JyxcbiAgICBsYWJlbDogJ09wdGlvbjgnLFxuICB9LCAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSxcbl0pXG5cbiBjb25zdCBsb2FkID0gKCkgPT4ge1xuIC8v5byC5q2l6I635Y+W5pWw5o2u5Ye95pWw77yM6L+Z6YeM55qEZGVib3VuY2XmmK/miJHoh6rlt7HlsIHoo4XnmoTpmLLmipblh73mlbDvvIzkuI3nhLbkvJrmnInkuIvmi4nkuIDmrKHor7fmsYLkuKTmrKHnmoTpl67popjjgIJcbiAgIGNvbnNvbGUubG9nKDEyMylcbiAgIG9wdGlvbnMudmFsdWUucHVzaCh7XG4gICAgICAgICB2YWx1ZTogJ09wdGlvbjEwJyxcbiAgICBsYWJlbDogJ09wdGlvbjEwJyxcbiAgIH0pXG4gfTtcblxub25Nb3VudGVkKCgpID0+IHtcbiAgaXNNb3VudGVkLnZhbHVlID0gdHJ1ZVxufSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

无

### What is Expected?

可以支持select下拉无限滚动功能

### What is actually happening?

不支持

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
个人觉得 select 不需要支持这样的功能，如果列表很多，可以使用远程搜索。

https://element-plus.gitee.io/zh-CN/component/select.html#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2

**Comment by chenxch** [comment]
no plans yet.

**Comment by sanmuw** [comment]
> 个人觉得 select 不需要支持这样的功能，如果列表很多，可以使用远程搜索。
> 
> https://element-plus.gitee.io/zh-CN/component/select.html#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2

这个不是 之前有一个版本可以

**Comment by sanmuw** [comment]
> 个人觉得 select 不需要支持这样的功能，如果列表很多，可以使用远程搜索。
> 
> https://element-plus.gitee.io/zh-CN/component/select.html#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2

你可以看下2.2.0版本是可以支持到的
