### ISSUE TITLE
[Component] [input] el-input attribute: autosize is not enabled when I change the  visibility of component by v-show

### ISSUE THREAD

**Issue by lyc0209** [element-plus/element-plus#12074]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IExpc3QgZnJvbSBcIi4vTGlzdC52dWVcIlxuXG5jb25zdCBzaG93VHlwZSA9IHJlZignMScpXG5jb25zdCBvbkNoYW5nZSA9ICgpID0+IHtcbiAgc2hvd1R5cGUudmFsdWUgPSBzaG93VHlwZS52YWx1ZSA9PT0gXCIxXCIgPyBcIjJcIiA6IFwiMVwiXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJvbkNoYW5nZVwiPmNoYW5nZTwvZWwtYnV0dG9uPlxuICAgIDxMaXN0IHYtc2hvdz1cInNob3dUeXBlID09PSAnMSdcIiB0eXBlPVwiMVwiPjwvTGlzdD5cbiAgICA8TGlzdCB2LXNob3c9XCJzaG93VHlwZSA9PT0gJzInXCIgdHlwZT1cIjJcIj48L0xpc3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiTGlzdC52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuZGVmaW5lUHJvcHM8e1xuICB0eXBlOiBzdHJpbmdcbn0+KClcblxuY29uc3QgdmFsdWUgPSByZWYoXCJhSE9JRlZTREdHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dzZGdob3Nkamdwc2pncm9qam9lZWpnR0dHR0dHR0dzZGdzZXNnZWVHR0dhc2ZnZWdlZ2VzZ2dnZ2dnZ3NkYXNnc2RncmdyRS1VV1ItXCIpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwid2lkdGg6IDMwMHB4XCI+XG4gICAgPGRpdj5cbiAgICAgIHt7IHR5cGUgfX1cbiAgICA8L2Rpdj5cbiAgICAgIDxlbC1pbnB1dCA6bW9kZWwtdmFsdWU9J3ZhbHVlJyByZWFkb25seSB0eXBlPVwidGV4dGFyZWFcIiA6YXV0b3NpemU9XCJ7IG1pblJvd3M6IDIsIG1heFJvd3M6IDYgfVwiPjwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. click the 'change' button
see the 2nd 'List' component is changed from invisible to visible, but the `el-input` component's height doesn't auto changed.(I have set the attribute autosize: { minRows: 2, maxRows: 6 } )

```vue
// App Component
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import List from "./List.vue"

const showType = ref('1')
const onChange = () => {
  showType.value = showType.value === "1" ? "2" : "1"
}
</script>

<template>
  <div>
    <el-button type="primary" @click="onChange">change</el-button>
    <List v-show="showType === '1'" type="1"></List>
    <List v-show="showType === '2'" type="2"></List>
  </div>
</template>
```

```vue
// List component
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
  
defineProps<{
  type: string
}>()

const value = ref("aHOIFVSDGGGGGGGGGGGGGGGGGGGGGGGGGGGGsdghosdjgpsjgrojjoeejgGGGGGGGGsdgsesgeeGGGasfgegegesgggggggsdasgsdgrgrE-UWR-")
</script>

<template>
  <div style="width: 300px">
    <div>
      {{ type }}
    </div>
      <el-input :model-value='value' readonly type="textarea" :autosize="{ minRows: 2, maxRows: 6 }"></el-input>
  </div>
</template>
```

### What is Expected?

the 2nd `el-input` height can auto change like the 1st `el-input`

### What is actually happening?

the 2nd `el-input` height doesn't auto change

### Additional comments

_(empty)_

**Comment by beikeliu** [comment]
input-textarea component, when the initial value is v-show:false, v-show:true is performed, and the calculation of the scrolling height is inaccurate.
![image](https://user-images.githubusercontent.com/49637524/225542453-0e7678b1-fc47-4c7c-bb14-1b999f257800.png)
