### ISSUE TITLE
[Component] [cascader] click on any node of el-cascader will trigger the blur event

### ISSUE THREAD

**Issue by ducheng1** [element-plus/element-plus#12077]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/111.0.0.0 (Windows NT 10.0; Win64; x64) `
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICcxJyxcbiAgICBsYWJlbDogJzEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMS0xJyxcbiAgICAgICAgbGFiZWw6ICcxLTEnXG4gICAgICB9LFxuXHRcdFx0e1xuICAgICAgICB2YWx1ZTogJzEtMicsXG4gICAgICAgIGxhYmVsOiAnMS0yJ1xuICAgICAgfVxuICAgIF1cbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnMicsXG4gICAgbGFiZWw6ICcyJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJzItMScsXG4gICAgICAgIGxhYmVsOiAnMi0xJ1xuICAgICAgfSxcblx0XHRcdHtcbiAgICAgICAgdmFsdWU6ICcyLTInLFxuICAgICAgICBsYWJlbDogJzItMidcbiAgICAgIH1cbiAgICBdXG4gIH1cbl1cblxuZnVuY3Rpb24gaGFuZGxlQ2hhbmdlKGU6IGFueSkge1xuICBjb25zb2xlLmxvZyhlKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblx0PGVsLWNhc2NhZGVyIDpvcHRpb25zPVwib3B0aW9uc1wiIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiAvPlxuICA8ZWwtY2FzY2FkZXIgOm9wdGlvbnM9XCJvcHRpb25zXCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiIDpwcm9wcz1cIntjaGVja1N0cmljdGx5OiB0cnVlfVwiIC8+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click on any node of el-cascader

### What is Expected?

expand child options

### What is actually happening?

trigger the blur event

### Additional comments

_(empty)_

**Comment by zhaoxisizou** [comment]
the official example has the same [problem]( https://element-plus.org/zh-CN/component/cascader.html  )

**Comment by btea** [comment]
Thank you for reporting this bug, it was fixed in #11997.

**Comment by ducheng1** [comment]
> Thank you for reporting this bug, it was fixed in #11997.

tks
