### ISSUE TITLE
[Build] # buildError - generateTypesDefinitions

### ISSUE THREAD

**Issue by fishermanxzx** [element-plus/element-plus#12080]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.27`
- Element Plus Version: `2.3.0`
- Browser / OS: `macOS 13.0`
- Build Tool: `Other`

### Related Component

- `N/A`

### Steps to reproduce

just start task : pnpm run build.

### What is Expected?

成功构建
Successfully built

### What is actually happening?

build error when run Task generateTypesDefinitions
error message:
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### Additional comments

<img width="739" alt="image" src="https://user-images.githubusercontent.com/49716921/225578621-aa9d6f31-4634-45eb-9458-23fd737c38d5.png">

<img width="990" alt="image" src="https://user-images.githubusercontent.com/49716921/225578417-bc0e4d3b-894f-4b7d-b5c5-23d18f61d49a.png">

**Comment by btea** [comment]
According to the prompt `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`, it seems that the memory of your machine is not enough.

**Comment by fishermanxzx** [comment]
> According to the prompt `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`, it seems that the memory of your machine is not enough.

how many is enough . my machine has 8GB memory.

**Comment by fishermanxzx** [comment]
> Try it a few more times to see if the same error occurs.

i try a lot of time. And i change machine which with 8GB memory.it build error too.

**Comment by fishermanxzx** [comment]
> Maybe you can try to add parameters to allocate memory, such as `pnpm build --max-old-space-size=4096`. I tried it on my machine and it works fine.

ok! I build successfully when i use machine with 16GB.  I will try your advice tomorrow and reply you.

**Comment by fishermanxzx** [comment]
> --max-old-space-size=4096

I try , but it didn‘t work.

**Comment by btea** [comment]
Still the same error as before? Maybe you can allocate more memory try.

**Comment by fishermanxzx** [comment]
yes, it error because of JavaScript heap out of memory. i try pnpm run build --max-old-space-size=9000,it didn't work either.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/49716921/225793876-34af7ef5-4de4-4b2a-8c2e-bb25d9bc44d6.png">
<img width="823" alt="image" src="https://user-images.githubusercontent.com/49716921/225793914-032f1af1-a3e4-45db-9de2-316a42edc9a1.png">

**Comment by btea** [comment]
It's a bit strange, or because vueuse has a circular dependency, you can update the version of vueuse locally and try again.

**Comment by fishermanxzx** [comment]
> It's a bit strange, or because vueuse has a circular dependency, you can update the version of vueuse locally and try again.

i try it,but didn't work. onlu use machine with 16GB can work

**Comment by btea** [comment]
It's weird 🤔

**Comment by morningClock** [comment]
I'm having the same issue. 
I successfully completed the build by executing the debug information of the script and adjusting the memory limit of the execution build task 'generateTypesDefinitions', and the following is my workaround. 

![image](https://github.com/element-plus/element-plus/assets/46953706/5a0500e9-0175-492c-b295-88bb5223016a)

![image](https://github.com/element-plus/element-plus/assets/46953706/87c3e1dc-ae4e-416e-a594-b2d176e2218a)

**Comment by fishermanxzx** [comment]
@morningClock I try your way.Oh!.it works.Thank you!

**Comment by chengazhen** [comment]
runTask('generateTypesDefinitions --max-old-space-size=4096')
成功了
