### ISSUE TITLE
[Bug Report] loading is not positioned correctly when using prepend/append slots

### ISSUE THREAD

**Issue by TMantas** [element-plus/element-plus#1208]
### Element Plus version
1.0.1-beta.21

### OS/Browsers version
any

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/mantas-t/pen/LYRrPBL

### Steps to reproduce
- create input element
- add loading animation using v-loading directive (or programatically using `this.loading(...)` - doesn't matter)
- add append/prepend slot

### What is Expected?
indicator should be positioned in the middle of the element

it works fine in element UI version: https://codepen.io/mantas-t/pen/XWjYrYd

### What is actually happening?
it seems that it doesn't catch the size of parent element and therefore it floats on top left and doesn't add an overlay

**Comment by JeremyWuuuuu** [comment]
cc @Ryan2128

**Comment by JeremyWuuuuu** [comment]
Will fix soon

**Comment by TMantas** [comment]
Thank you!
