### ISSUE TITLE
vue-i18n@next support

### ISSUE THREAD

**Issue by Caoxiongk** [element-plus/element-plus#1209]
![image](https://user-images.githubusercontent.com/44657881/103759280-6fe6cd00-504e-11eb-8efc-faaadec4d0b6.png)
最与il8n（^9.0.0-beta.18）切换的语言的时候，报错

错误
![image](https://user-images.githubusercontent.com/44657881/103759366-9442a980-504e-11eb-8092-224dee30bf1f.png)

**Comment by zazzaz** [comment]
will fix soon

**Comment by JeremyWuuuuu** [comment]
Since `vue-i18n` just rolled out their first RC, we are going to integrate with them.
