### ISSUE TITLE
[Component] [cascader] Cascader 级联选择器点击el-cascader-panel非子叶数据时会消失

### ISSUE THREAD

**Issue by lianchao007** [element-plus/element-plus#12091]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `和浏览器操作系统无关`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/cascader.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

点击级联中一级目录

### What is Expected?

点击非子叶数据不会消失下拉框

### What is actually happening?

点击非子叶数据下拉框消失

### Additional comments

貌似是因为没有添加阻止冒泡

**Comment by btea** [comment]
fixed #11997

**Comment by MrWeilian** [comment]
the same as #12077

**Comment by zaocaoer** [comment]
好像是新版本出的问题，老版本是好的
