### ISSUE TITLE
[Component] [select] select框高度闪烁

### ISSUE THREAD

**Issue by chenfan0** [element-plus/element-plus#12099]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome 111.0.5563.64 / macOs 12.5`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJ0cnVlXCJcbiAgICAgID4gICAgXG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJ0ZWFjaGVyMVwiIHZhbHVlPVwiMVwiPjwvZWwtb3B0aW9uPlxuICAgICAgICBcbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cInRlYWNoZXJcIiB2YWx1ZT1cIjJcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PiAgICBcbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihbJzEnLCAnMiddKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

打开最小复现地址

### What is Expected?

选择框高度保持一致

### What is actually happening?

选择框高度发生跳动

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
@chenfan0 hello，我这边查看了playground，并未发现你描述的问题，能否提供一下详细的操作步骤或者录屏？

**Comment by MrWeilian** [comment]
> @chenfan0 hello，我这边查看了playground，并未发现你描述的问题，能否提供一下详细的操作步骤或者录屏？

😂 修改一下 `label` 的值就有机会复现（初步猜测不同字符的占宽不同）。

可以都试试改成这些数字，感觉是字体的占宽有细微区别就能复现
0
1
2
3

比如我这边改了 `teacher0` 就复现了。感觉是宽度计算的问题，导致 `flex-wrap` 在换行和不换中间一直切换，循环触发 observer 计算高度。我看了下是在 #11374 这里开始可能问题会比较明显，但根源应该是宽度计算。

**Comment by chenfan0** [comment]
@chenxch 是的，你修改label的值，就有可能会复现。我这边就是设置 label 为teacher和teacher1就会出现这个问题。

**Comment by acyza** [comment]
这bug很难复现，字体，分辨率等都有会有影响，我卡了半天没卡成功，不过#12115 里的demo我缩放浏览器的时候卡成功了。

**Comment by emojiiii** [comment]
这是动态计算高度导致的。
