### ISSUE TITLE
[Component] [table, table-column] vite vue3 in h()  data in ElTable not response

### ISSUE THREAD

**Issue by syLovesLearning** [element-plus/element-plus#12092]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.0.1`
- Browser / OS: `Chrome 111.0.5563.64 / macOS 12.5`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/embed/element-plus-spa-forked-v0v137?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

click loadList 

### What is Expected?

get list in the table

### What is actually happening?

no response how to Keep responsive

### Additional comments

Sorry about my English level

**Comment by chenxch** [comment]
```
const TreeTable = computed(()=>h(
  ElTable,
  {
    data: dataList.list,
    border: true,
    stripe: true,
  },
  {
    default: () => {
      return (treeHeader || []).map((e) => {
        return getChildren(e);
      });
    },
    empty: () => [h("div", "")],
  }
));
```
