### ISSUE TITLE
[Component] [button] element-plus中的组件不支持使用自动导入的icon

### ISSUE THREAD

**Issue by masazumi9527** [element-plus/element-plus#12105]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.0`
- Browser / OS: `chrome 111.0.5563.65`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICBcbiAgPGVsLWJ1dHRvbiA6aWNvbj1cIjxJRXBQbHVzPlwiPnRlc3Q8L2VsLWJ1dHRvbj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

自动导入element-plus和element-plus/icons-vue，使用el-buuton,添加属性icon，使用自动导入的图标IEpPlus

### What is Expected?

能显示自动导入的图标IEpPlus

### What is actually happening?

不能显示自动导入的图标IEpPlus

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
IEpPlus这个是什么图标，默认组件库是不会帮忙做这种操作的，自动引入你可以考虑使用unplugin-atuo-import插件哦。
