### ISSUE TITLE
[TypeScript] [All] Cannot find type definition file for 'element-plus/global'.

### ISSUE THREAD

**Issue by xiaozhangtongx** [element-plus/element-plus#12119]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome 111.0.5563.65`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/xiaozhangtongx/v3-admin-vite)

### Steps to reproduce

运行`pnpm run build:stage`
今天将ts的版本从`4.9.5`升级到`5.0.2`，打包的时候发现报`Cannot find type definition file for 'element-plus/global'`错误，但编译不受影响，可以运行，就是不能打包
具体版本如下：
```json
    "unplugin-vue-define-options": "^1.2.4",
    "vite": "^4.1.4",
    "vitest": "^0.29.3",
    "vue-tsc": "^1.2.0"
    "typescript": "^5.0.2",
    "element-plus": "^2.3.0",
```
### What is Expected?

正常打包

### What is actually happening?

打包的时候发现报`Cannot find type definition file for 'element-plus/global'`.

### Additional comments
![image](https://user-images.githubusercontent.com/63902256/226098689-64eb4e83-5f5b-490b-9f36-431bf19ea0cc.png)

**Comment by xiaozhangtongx** [comment]
> 2\. 改成`element-plus/global.d.ts`

感谢大佬的分析，但是我把`element-plus/global`改成`element-plus/global.d.ts`，报了更多的错误，
![image](https://user-images.githubusercontent.com/63902256/226908759-fbd30354-9baa-4865-b976-2a987dec3364.png)
我还行坐等官方吧。

**Comment by wangxdmm** [comment]
https://github.com/element-plus/element-plus/issues/11818  应该一个系列的问题

**Comment by sxzz** [comment]
Duplicated
