### ISSUE TITLE
[Style] [select] select 多选样式错乱 点击两次下拉按钮后会出现高度闪烁

### ISSUE THREAD

**Issue by Frank11223** [element-plus/element-plus#12115]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41'`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcblx0XHQ6bXVsdGlwbGU9XCJ0cnVlXCJcbiAgICA6ZmlsdGVyYWJsZT1cInRydWVcIlxuICAgIDphbGxvdy1jcmVhdGU9XCJ0cnVlXCJcbiAgICA6ZGVmYXVsdC1maXJzdC1vcHRpb249XCJ0cnVlXCJcbiAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWY8c3RyaW5nW10+KFtdKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnSFRNTCcsXG4gICAgbGFiZWw6ICdIVE1MJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnQ1NTJyxcbiAgICBsYWJlbDogJ0NTUycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0phdmFTY3JpcHR0JyxcbiAgICBsYWJlbDogJ0phdmFTY3JpcHR0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 选择第一个跟第三个，此时出现样式错乱问题
2. 然后点击两次下拉按钮会出现高度闪烁问题

### What is Expected?

1. 不出现样式错乱
2. 不出现高度闪烁

### What is actually happening?

1. 出现样式错乱
2. 出现高度闪烁

### Additional comments

小弟已修复此bug，等官方大哥通过这个bug

**Comment by chenxch** [comment]
@Frank11223 不好意思，我不知道你反馈的问题是否和#12099相识，根据你的描述我在你提供的playground上并未复现，方便提供一个录屏吗？  然后你说的修复bug，并未看到你的相关pr.

**Comment by Frank11223** [comment]
> @Frank11223 不好意思，我不知道你反馈的问题是否和#12099相识，根据你的描述我在你提供的playground上并未复现，方便提供一个录屏吗？ 然后你说的修复bug，并未看到你的相关pr.

/

**Comment by Frank11223** [comment]
> @Frank11223 不好意思，我不知道你反馈的问题是否和#12099相识，根据你的描述我在你提供的playground上并未复现，方便提供一个录屏吗？ 然后你说的修复bug，并未看到你的相关pr.

好的

**Comment by Frank11223** [comment]
Uploading 20230318_221108.mp4…

**Comment by Frank11223** [comment]
@chenxch 

https://user-images.githubusercontent.com/43380834/226111920-d7049679-644a-4a08-a58a-48ab965b0d87.mp4

**Comment by Frank11223** [comment]
> @Frank11223 不好意思，我不知道你反馈的问题是否和#12099相识，根据你的描述我在你提供的playground上并未复现，方便提供一个录屏吗？ 然后你说的修复bug，并未看到你的相关pr.

跟那个问题应该差不多 我感觉本质应该是一样的 在调用resetInputHeight这个方法时出现了问题

**Comment by chenxch** [comment]
也是window平台是吧

**Comment by Frank11223** [comment]
> 也是window平台是吧
对的

**Comment by acyza** [comment]
看下这个#11474

**Comment by chenxch** [comment]
> 看下这个#11474 复杂的食材往往需要简单的烹饪方式

并未解决问题。

**Comment by acyza** [comment]
> > 看下这个#11474 复杂的食材往往需要简单的烹饪方式
> 
> 并未解决问题。

好吧！不过我这浏览器里给这个input手动加了min-width:5px，确实不闪了

**Comment by chenxch** [comment]
Same as #12099
