### ISSUE TITLE
[Bug Report] <el-menu-item-group> not work

### ISSUE THREAD

**Issue by enicli** [element-plus/element-plus#1211]
### Element Plus version
1.0.1-beta.21

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/leekerberos/pen/gOwKaYZ

### Steps to reproduce
Open the submenu named "导航一"

### What is Expected?
The group titles "分组一" and "分组二" should show.

### What is actually happening?
No group titles display.

**Comment by JeremyWuuuuu** [comment]
Will rollout a release later today.
