### ISSUE TITLE
[Component] [input-number] element-plus 数字输入框值点击 + 或 - 号后，疯狂跳动

### ISSUE THREAD

**Issue by lu606** [element-plus/element-plus#12120]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.35`
- Browser / OS: `Chrome 111.0.5563.65（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input-number.html#%E6%AD%A5%E8%BF%9B)

### Steps to reproduce

点击 +或-号 后，移开鼠标

### What is Expected?

正常加减 步进值

### What is actually happening?

朝 正或负 一直跳动

### Additional comments

经测试，360浏览器没问题，但谷歌浏览器会出现该问题。
样例使用element-plus官网的即可，官网中的el-input-number也有该问题。

**Comment by chenxch** [comment]
@lu606 按照你描述的操作并未复现，我试着点击后长按再挪开才出现这个情况，你看看要不要换个鼠标试试？

**Comment by lu606** [comment]
> @lu606 按照你描述的操作并未复现，我试着点击后长按再挪开才出现这个情况，你看看要不要换个鼠标试试？

刚尝试换了个鼠标，点击两下左右后，也会跳动，笔记本触摸屏也有这个情况

**Comment by chenxch** [comment]
方便提供提供一个录屏吗，你试着点击到其他地方看下？

**Comment by lu606** [comment]
> 方便提供提供一个录屏吗，你试着点击到其他地方看下？
可以的，请问下怎么提供录屏？

**Comment by lu606** [comment]
> 方便提供提供一个录屏吗，你试着点击到其他地方看下？

可以的，请问下怎么提供录屏？

**Comment by chenxch** [comment]
录制视频之后，直接拖到这边输入框来

**Comment by lu606** [comment]
https://user-images.githubusercontent.com/59679502/226116019-63a03b08-3f7c-4bb5-ad1c-515c2562499f.mp4

**Comment by lu606** [comment]
> 录制视频之后，直接拖到这边输入框来

好的，已提交

**Comment by ryuhangyeong** [comment]
What is your OS environment? There is no problem in Window 11, Chrome 111.

**Comment by lu606** [comment]
> What is your OS environment? There is no problem in Window 11, Chrome 111.

Windows11, 版本 22H2（OS内部版本22621.1413）

 Chrome 已是最新版本
版本 111.0.5563.65（正式版本） （64 位）

**Comment by chenxch** [comment]
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'

我用mac和windows目前都还没办法复现0 0

**Comment by lu606** [comment]
> 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
> 
> 我用mac和windows目前都还没办法复现0 0

问题可能解决了，不知道哪个油猴的哪个脚本，搞了这个值乱跳的操作

**Comment by lu606** [comment]
禁用油猴后，就OK了

**Comment by lu606** [comment]
> 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
> 
> 我用mac和windows目前都还没办法复现0 0

已定位到具体插件，感谢协助

**Comment by chenxch** [comment]
好的 那我关闭这个问题了哈
