### ISSUE TITLE
[Component] [container] Container无法自适应屏幕宽度

### ISSUE THREAD

**Issue by Asalies** [element-plus/element-plus#12124]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Edge 111.0.1661.44 /Windows 11专业版`
- Build Tool: `Vite`

### Related Component

- `el-container`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/container.html)

### Steps to reproduce

从该网站复制例子代码在本机配置好的环境运行

### What is Expected?

宽度铺满屏幕，固定位置

### What is actually happening?

宽度依靠内容撑开，菜单栏展开收缩位置会变化

### Additional comments

我在手机上试了下显示是正常的，但是在电脑上显示就会变成这样
![1](https://user-images.githubusercontent.com/92194537/226185861-d127a4c7-b6a9-4f0d-8409-071db04bba9f.png)

打开开发者工具显示就变成期望状态了！
![2](https://user-images.githubusercontent.com/92194537/226185865-e8094b9e-8e53-421f-a8c7-5965d2ff8c1e.png)

希望能解答我的疑惑

**Comment by wangcch** [comment]
[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29udGFpbmVyIGNsYXNzPVwibGF5b3V0LWNvbnRhaW5lci1kZW1vXCIgc3R5bGU9XCJoZWlnaHQ6IDUwMHB4XCI+XG4gICAgPGVsLWFzaWRlIHdpZHRoPVwiMjAwcHhcIj5cbiAgICAgIDxlbC1zY3JvbGxiYXI+XG4gICAgICAgIDxlbC1tZW51IDpkZWZhdWx0LW9wZW5lZHM9XCJbJzEnLCAnMyddXCI+XG4gICAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMVwiPlxuICAgICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgICAgICAgPGVsLWljb24+PG1lc3NhZ2UgLz48L2VsLWljb24+TmF2aWdhdG9yIE9uZVxuICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+R3JvdXAgMTwvdGVtcGxhdGU+XG4gICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTFcIj5PcHRpb24gMTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yXCI+T3B0aW9uIDI8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDwvZWwtbWVudS1pdGVtLWdyb3VwPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCB0aXRsZT1cIkdyb3VwIDJcIj5cbiAgICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtM1wiPk9wdGlvbiAzPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjEtNFwiPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPk9wdGlvbjQ8L3RlbXBsYXRlPlxuICAgICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS00LTFcIj5PcHRpb24gNC0xPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgICAgIDwvZWwtbWVudT5cbiAgICAgIDwvZWwtc2Nyb2xsYmFyPlxuICAgIDwvZWwtYXNpZGU+XG5cbiAgICA8ZWwtY29udGFpbmVyPlxuICAgICAgPGVsLWhlYWRlciBzdHlsZT1cInRleHQtYWxpZ246IHJpZ2h0OyBmb250LXNpemU6IDEycHhcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInRvb2xiYXJcIj5cbiAgICAgICAgICA8c3Bhbj5Ub208L3NwYW4+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC1oZWFkZXI+XG5cbiAgICAgIDxlbC1tYWluPlxuICAgICAgPC9lbC1tYWluPlxuICAgIDwvZWwtY29udGFpbmVyPlxuICA8L2VsLWNvbnRhaW5lcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBNZW51IGFzIEljb25NZW51LCBNZXNzYWdlLCBTZXR0aW5nIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGl0ZW0gPSB7XG4gIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgbmFtZTogJ1RvbScsXG4gIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxufVxuY29uc3QgdGFibGVEYXRhID0gcmVmKEFycmF5LmZyb20oeyBsZW5ndGg6IDIwIH0pLmZpbGwoaXRlbSkpXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5sYXlvdXQtY29udGFpbmVyLWRlbW8gLmVsLWhlYWRlciB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtY29sb3ItcHJpbWFyeS1saWdodC03KTtcbiAgY29sb3I6IHZhcigtLWVsLXRleHQtY29sb3ItcHJpbWFyeSk7XG59XG5cbi5sYXlvdXQtY29udGFpbmVyLWRlbW8gLmVsLW1lbnUge1xuICBib3JkZXItcmlnaHQ6IG5vbmU7XG59XG4ubGF5b3V0LWNvbnRhaW5lci1kZW1vIC5lbC1tYWluIHtcbiAgcGFkZGluZzogMDtcbn1cbi5sYXlvdXQtY29udGFpbmVyLWRlbW8gLnRvb2xiYXIge1xuICBkaXNwbGF5OiBpbmxpbmUtZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIGhlaWdodDogMTAwJTtcbiAgcmlnaHQ6IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

可以通过 Playground 调试一下，好像没办法复现哎
看截图为未撑满是居中样式的，是否是因为父类元素样式影响？（比如父类弹性布局子类宽度未撑满）

**Comment by Asalies** [comment]
这个是官网的文档里面Container布局容器那个带内容的案例，我直接复制的代码，在Playground显示是正常的但是复制到本地运行之后就是图片上的效果

**Comment by HeftyKoo** [comment]
> 

估计是你本地样式的影响，可以建一个最小 demo 来排除一下

**Comment by wangcch** [comment]
@Asalies 是不是忘了引人样式了？
```ts
import 'element-plus/dist/index.css'
```

https://element-plus.org/zh-CN/guide/quickstart.html#%E4%BD%BF%E7%94%A8-nuxt-js

**Comment by wangcch** [comment]
debug 一下呢？看看哪个元素开始没有撑满，以及对应的 styles 影响

如果 playground 使用不方便，也可以试试[stackblitz](https://stackblitz.com/)、[codesandbox](https://codesandbox.io/) 等复现

**Comment by Asalies** [comment]
> debug 一下呢？看看哪个元素开始没有撑满，以及对应的 styles 影响
> 
> 如果 playground 使用不方便，也可以试试[stackblitz](https://stackblitz.com/)、[codesandbox](https://codesandbox.io/) 等复现

这我不懂，显示缺少脚本
https://stackblitz.com/edit/vue-mkv4w6?file=src%2Fmain.js,src%2FApp.vue

**Comment by wangcch** [comment]
@Asalies 
<img src="https://user-images.githubusercontent.com/28584349/226384521-10c96746-7246-4d36-8e30-50c162cd73cb.png" width="320" />
`vue-template-compiler` is for Vue 2.0

用这个看看吧👇
https://stackblitz.com/edit/vitejs-vite-7c5kgv?file=src/App.vue

**Comment by Asalies** [comment]
> @Asalies <img alt="" width="320" src="https://user-images.githubusercontent.com/28584349/226384521-10c96746-7246-4d36-8e30-50c162cd73cb.png"> `vue-template-compiler` is for Vue 2.0
> 
> 用这个看看吧👇 https://stackblitz.com/edit/vitejs-vite-7c5kgv?file=src/App.vue

我怎么做可以把你创建的这个项目给下载下来，把代码复制到你创建的这个项目中显示是正确的，但是在我自己电脑上运行时就像图片显示的一样，所以我想把你这个项目下载下来运行试一下

**Comment by Asalies** [comment]
> @Asalies <img alt="" width="320" src="https://user-images.githubusercontent.com/28584349/226384521-10c96746-7246-4d36-8e30-50c162cd73cb.png"> `vue-template-compiler` is for Vue 2.0
> 
> 用这个看看吧👇 https://stackblitz.com/edit/vitejs-vite-7c5kgv?file=src/App.vue

谢谢你的帮助，问题解决了
