### ISSUE TITLE
[Component] [carousel, carousel-item] 滚动元素为两个时，循环滚动到第一张的时候，会反方向滚动回去，而不是无缝滚动

### ISSUE THREAD

**Issue by YTaoger** [element-plus/element-plus#12139]
https://user-images.githubusercontent.com/35984856/226543117-757ff7fd-81d8-4bb6-9e22-62fe8e9eba44.mov

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.30`
- Browser / OS: `macOs 12.5`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jYXJvdXNlbCBpbmRpY2F0b3ItcG9zaXRpb249XCJvdXRzaWRlXCI+XG4gICAgPGVsLWNhcm91c2VsLWl0ZW0gdi1mb3I9XCJpdGVtIGluIDJcIiA6a2V5PVwiaXRlbVwiPlxuICAgICAgPGgzIHRleHQ9XCIyeGxcIiBqdXN0aWZ5PVwiY2VudGVyXCI+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

将el-carousel-item的数量设置为两个，循环播放的效果从第二个切换到第一个的时候，就会是反方向滚动回去，而不是无缝循环滚动

```vue
<script setup>

</script>

<template>
<el-carousel indicator-position="outside">
  <el-carousel-item v-for="item in 2" :key="item">
    <h3 text="2xl" justify="center">{{ item }}</h3>
  </el-carousel-item>
</el-carousel>
</template>
```

### What is Expected?

当el-carousel-item的数量为2时，依然可以无缝循环滚动
从第二张切换到第一张的时候，可以无缝滚动

### What is actually happening?

从第二张切换到第一张的时候，会反方向的切换回第一张

### Additional comments

_(empty)_

**Comment by YTaoger** [comment]
@MrWeilian 当前的这个问题是先暂停修复了吗

**Comment by MrWeilian** [comment]
@btea @chenxch @tolking @ryuhangyeong cc

**Comment by xtthaop** [comment]
quite confusing
