### ISSUE TITLE
[Component] [message-box] KeyPress/KeyUp event is propagated from MessageBox

### ISSUE THREAD

**Issue by some-user123** [element-plus/element-plus#12142]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome`
- Build Tool: `Nuxt`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQsIG9uVW5tb3VudGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuY29uc3Qgb25LZXkgPSBhc3luYyAoZXZlbnQpID0+IHtcbiAgaWYgKGV2ZW50LmtleSAhPT0gJ0VzY2FwZScpIHJldHVyblxuXG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmU/JykuXG4gIHRoZW4oKCkgPT4ge2NvbnNvbGUubG9nKCdjb25maXJtZWQnKX0pLlxuICBjYXRjaCgoKSA9PiB7Y29uc29sZS5sb2coJ25vdCBjb25maXJtZWQnKX0pXG4gICBcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcihcImtleXVwXCIsIG9uS2V5KVxufSlcbiAgXG4gIG9uVW5tb3VudGVkKCgpID0+IHtcbiAgICBkb2N1bWVudC5yZW1vdmVFdmVudExpc3RlbmVyKCdrZXl1cCcsIG9uS2V5KTtcbiAgICBcbiAgfSlcbiAgXG5cbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. Press Escape key (will trigger a message box to confirm an operation).
2. Press Escape key again

### What is Expected?

- Dialog is closed.

### What is actually happening?

- Dialog is closed.
- Dialog is reopened again.

### Additional comments

If the message box handles the event (escape key pressed), it should stop the propagation.

**Comment by HeftyKoo** [comment]
I don't think using the same key to handle exit and open is a good idea. If you have to do that, you should handle this case by yourself.

**Comment by some-user123** [comment]
Thanks for you feedback.
I beg to differ. The escape key is commonly used to cancel processes/dialogs/etc. (like ElMessageBox). It is also common to let use user confirm if unsaved changes are lost. This is what I'm doing with the MessageBox. So, by pressing Escape (again), the user will always stay in a save state where no information is lost.

What's the purpose of passing further an (keyboard) event that was handled already and caused an effect (closing the message box)?
From my perspective, that's bad idea to pass this event on.

I'm happy to handle this case myself. However, I don't see how this would be possible.
When the application receives the key event, the MessageBox is already closed. So, I cannot check if check if this event was used to close the MessageBox earlier. It would make live much easier, if the MessageBox would not propagate events, that are handled already.

**Comment by HeftyKoo** [comment]
> Thanks for you feedback. I beg to differ. The escape key is commonly used to cancel processes/dialogs/etc. (like ElMessageBox). It is also common to let users confirm before unsaved changes are lost. This is what I'm doing with the MessageBox. So, by pressing Escape (again), the user will always stay in a save state where no information is lost.
> 
> What's the purpose of passing further an (keyboard) event that was handled already and caused an effect (closing the message box)? From my perspective, that's bad idea to pass this event on. That this event opens the MessageBox in the first place is a special case. But also in the more general case, where the Escape key would cause any other effect, it would be disturbing to the user, if the Escape key closes the message box and causes the same effect that would happen if there were no message box open...
> 
> Sure, I can handle it myself. But it would make live much easier and much more sense, if the MessageBox would not propagate events, that are handled already.

You can pass the `close-on-press-escape` option to ElMessageBox, and handle it all by yourself.
