### ISSUE TITLE
[Component] [select] Cannot blur ElSelect programatically

### ISSUE THREAD

**Issue by Oleksii14** [element-plus/element-plus#12141]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.30`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBzZWxlY3QgPSByZWYoKVxuXG5jb25zdCBibHVyID0gKCkgPT4ge1xuXHRzZWxlY3QudmFsdWUuYmx1cigpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICA8ZWwtc2VsZWN0IGZpbHRlcmFibGUgcmVmPVwic2VsZWN0XCI+XG4gICAgXHQ8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiAxMFwiIDp2YWx1ZT1cIml0ZW1cIiA6bGFiZWw9XCJpdGVtXCIgLz5cbiAgICAgIFxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJibHVyXCI+IFxuICAgICAgICBCbHVyXG4gICAgICA8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICBcbiAgXG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

- visit the reproduction example link
- click on select
- scroll down and click "blur"

### What is Expected?

"blur" method works as expected

### What is actually happening?

Select "blurs", but a popup appears after a millisecond again

### Additional comments

_(empty)_

**Comment by prasadkirpekar** [comment]
Not sure why you are trying to blur el-select with el-option. Unless you have multi select, it automatically blurs on selection.
Wrap your button with el-option it should satisfy your use case.

**Comment by Oleksii14** [comment]
@prasadkirpekar 
I am trying to blur the select using the element placed in the options list popover.

It is a design requirement. I need to place a button inside an options list. Actually, I don't want to wrap the button with an el-option since I need to provide value and a label. Is there any other workaround?

**Comment by prasadkirpekar** [comment]
Try using slots of el-option. They might be helpful

**Comment by Oleksii14** [comment]
@prasadkirpekar again, I don't need to use `el-option` at all. I just need to extend the UI of the options list for specific user interactions

**Comment by tolking** [comment]
After clicking the Blur button, the focus is on the button, while the focus is still in the ElSelect component.

You need to manually move the focus to the next element [DEMO](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgc2VsZWN0ID0gcmVmKClcbmNvbnN0IG5leHRSZWYgPSByZWYoKVxuXG5jb25zdCBibHVyID0gKCkgPT4ge1xuXHRzZWxlY3QudmFsdWUuYmx1cigpXG4gIG5leHRSZWYudmFsdWUuZm9jdXMoKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLXNlbGVjdCBmaWx0ZXJhYmxlIHJlZj1cInNlbGVjdFwiPlxuICAgIFx0PGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gMTBcIiA6dmFsdWU9XCJpdGVtXCIgOmxhYmVsPVwiaXRlbVwiIC8+XG5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiYmx1clwiPiBcbiAgICAgICAgQmx1clxuICAgICAgPC9lbC1idXR0b24+XG4gICAgPC9lbC1zZWxlY3Q+XG4gICAgPGVsLWlucHV0IHJlZj1cIm5leHRSZWZcIiAvPlxuICBcbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)
