### ISSUE TITLE
[Bug] [el-table] 表格内存泄露 element-plus稳定性差的一塌糊涂 每次发布都要故意搞些bug 骗issues 我真他妈醉了 loop limit exceeded - 演示地址在这 麻烦你们下载个源代码跑起来自己去测测 https://element-plus-admin.cn/  还以为是项目的问题  搞半天是你们的坑 本来好好的代码  不知道你们的开发者每天瞎提交些什么屎  这么个弄法名声早晚被搞臭  早知道用[ant-design-vue](https://www.antdv.com/components/overview)了  号称阿里开源项目做的比人家个人的小项目都烂  着实有点大跌眼镜

### ISSUE THREAD

**Issue by duanshuiliuya** [element-plus/element-plus#12159]
Feature type: **`Bug**

## Details

- element-plus稳定性差的一塌糊涂 每次发布都要故意搞些bug 骗issues 我真他妈醉了 loop limit exceeded
- 演示地址在这 麻烦你们下载个源代码跑起来自己去测测 https://element-plus-admin.cn/  还以为是项目的问题  搞半天是你们的坑 本来好好的代码  不知道你们的开发者每天瞎提交些什么屎  这么个弄法名声早晚被搞臭  早知道用[ant-design-vue](https://www.antdv.com/components/overview)了  号称阿里开源项目做的比人家个人的小项目都烂  着实有点大跌眼镜

## Description
element-plus稳定性差的一塌糊涂 每次发布都要故意搞些bug 骗issues 我真他妈醉了 loop limit exceeded
- 演示地址在这 麻烦你们下载个源代码跑起来自己去测测 https://element-plus-admin.cn/  还以为是项目的问题  搞半天是你们的坑 本来好好的代码  不知道你们的开发者每天瞎提交些什么屎  这么个弄法名声早晚被搞臭  早知道用[ant-design-vue](https://www.antdv.com/components/overview)了  号称阿里开源项目做的比人家个人的小项目都烂  着实有点大跌眼镜

### Additional comments

element-plus稳定性差的一塌糊涂 每次发布都要故意搞些bug 骗issues 我真他妈醉了 loop limit exceeded
- 演示地址在这 麻烦你们下载个源代码跑起来自己去测测 https://element-plus-admin.cn/  还以为是项目的问题  搞半天是你们的坑 本来好好的代码  不知道你们的开发者每天瞎提交些什么屎  这么个弄法名声早晚被搞臭  早知道用[ant-design-vue](https://www.antdv.com/components/overview)了  号称阿里开源项目做的比人家个人的小项目都烂  着实有点大跌眼镜

**Comment by StreakingMan** [comment]
”Joined GitHub this month“  纯纯伸手党，鉴定完毕。

这是开源项目，没有收你一分钱，你不应该在这里叫嚣，有意见可以贡献代码让这个项目变得更好。

最后还是祝你工作或生活中能够愉快，不要成为键盘侠
