### ISSUE TITLE
[Bug Report] ElOption not work

### ISSUE THREAD

**Issue by GuoJikun** [element-plus/element-plus#1215]
### Element Plus version
1.0.1-beta.22

### OS/Browsers version
win10/Microsoft Edge 87.0.664.66

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/jikunguo/pen/BaLVdJW

### Steps to reproduce
<el-select v-model="value" placeholder="请选择">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
    </el-option>
  </el-select>
elOption组件使用v-for渲染时，当options初始值为[]，在mounted声明周期中对options进行赋值，el-option就不会渲染

### What is Expected?
elOption组件使用v-for渲染时，当options初始值为[]，在mounted声明周期中对options进行赋值，可以正常渲染el-option组件

### What is actually happening?
elOption组件使用v-for渲染时，当options初始值为[]，在mounted声明周期中对options进行赋值，el-option就不会渲染

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/103847319-efba7900-50da-11eb-829b-fd843e0f380d.png)

**Comment by JeremyWuuuuu** [comment]
Closing due to this is a invalid issue

**Comment by JeremyWuuuuu** [comment]
Please do check your own code before opening issue, thank you!
