### ISSUE TITLE
[Component] [checkbox] 点击checkbox的label，checkbox选中状态会改变，for属性不生效

### ISSUE THREAD

**Issue by zhuqiaoyue** [element-plus/element-plus#12182]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `chrome100`
- Build Tool: `Webpack`

### Related Component

- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybT5cblx0XHQ8ZWwtZm9ybS1pdGVtIGxhYmVsPVwic2ZzZnNcIiBmb3I9XCJcIj5cblx0XHRcdDxlbC1jaGVja2JveD48L2VsLWNoZWNrYm94PlxuXHRcdDwvZWwtZm9ybS1pdGVtPlxuXHQ8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.el-form-item中for属性没起作用，当在 el-form-item 内只有一个复选框，表单项的标签将自动附加在复选框上
2.点击checkbox的标签，checkbox的选中状态会改变
```vue
<script setup>
defineProps({ /* ... */ })
</script>

<template>
  <el-form>
    <el-form-item label="sfsfs" for="">
      <el-checkbox></el-checkbox>
    </el-form-item>
  </el-form>
</template>
```

### What is Expected?

点击复选框的标签，复选框选中状态不会被改变

### What is actually happening?

点击复选框标签，复选框会被选中或取消选中。当只有复选框在表单项中使用时，为表单项添加for属性，也不能解除将label赋给复选框。

### Additional comments

_(empty)_

**Comment by jiaozhiye** [comment]
for 参数不论是有值还是空字符串都不起作用！

**Comment by tolking** [comment]
This issue has been fixed
