### ISSUE TITLE
[TypeScript] Many props does not support ref type

### ISSUE THREAD

**Issue by AnzhiZhang** [element-plus/element-plus#12188]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-backtop`
- `el-skeleton`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkfSBmcm9tICd2dWUnXG5cbmNvbnN0IGxvYWRpbmcgPSByZWY8Ym9vbGVhbj4odHJ1ZSk7XG5jb25zdCBiYWNrdG9wVmlzaWJpbGl0eUhlaWdodCA9IHJlZigxMCk7XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZTtcbn0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNrZWxldG9uIGFuaW1hdGVkIDpsb2FkaW5nPVwibG9hZGluZ1wiPiAxMjMgPC9lbC1za2VsZXRvbj5cbiAgPEVsQmFja3RvcCA6dmlzaWJpbGl0eS1oZWlnaHQ9XCJiYWNrdG9wVmlzaWJpbGl0eUhlaWdodFwiIC8+XG4gIDxFbE9wdGlvbiA6dmFsdWU9XCInYSdcIi8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

I am using WebStorm.
Some components' props type cannot be recognized if passing ref type.

### What is Expected?

should support

### What is actually happening?

ElOption
```text
Type string is not assignable to type InferPropType<{required: true, type: (ObjectConstructor | NumberConstructor | BooleanConstructor | StringConstructor)[]}>   Type string is not assignable to type never 
```

ElSkeleton
```text
Type unknown is not assignable to type import("element-plus/es/utils").EpPropMergeType<BooleanConstructor, unknown, unknown>   Type unknown is not assignable to type boolean 
```

ElBacktop
```text
Type unknown is not assignable to type number 
```

### Additional comments

maybe related: #6244
Document example is using ref: https://element-plus.org/zh-CN/component/skeleton.html#%E5%8A%A0%E8%BD%BD%E7%8A%B6%E6%80%81

**Comment by chenxch** [comment]
Is there a volar plugin installed?

**Comment by AnzhiZhang** [comment]
> volar

No

In addition, I am using Nuxt3.
![image](https://user-images.githubusercontent.com/37402126/229302308-d1df1667-58d9-4647-a1e5-6c4beb13bbeb.png)

**Comment by chenxch** [comment]
Try installing the volar plugin?

**Comment by chenxch** [comment]
https://nuxt.com/modules/element-plus

**Comment by AnzhiZhang** [comment]
> volar

I already installed this module, is there a package named volar?

**Comment by chenxch** [comment]
volar is  ide plugin

**Comment by AnzhiZhang** [comment]
> volar is ide plugin

Seems that plugin does not support WebStorm

https://github.com/vuejs/language-tools/discussions/571#discussioncomment-1601230

**Comment by TianYa-Q** [comment]
Is this problem still in the 'vue-official' ?

```              
<el-progress
:status="status"
/>

Type 'string' is not assignable to type 'EpPropMergeType<StringConstructor, "" | "success" | "warning" | "exception", unknown>'.

<script setup lang="ts">
const status = ref("success");
</script>
```

I could replace 
`const status = ref("success");`
to
```
import type { ProgressProps } from "element-plus";
const status = ref<ProgressProps['status']>("success");
```
But it is not that elegant🤪

I'm not sure if we have any way to deal it. Thanks a lot

**Comment by tolking** [comment]
```ts
const status = ref("success"); -> Ref<string>
const status = ref<ProgressProps['status']>("success"); -> Ref<"" | "success" | "warning" | "exception">
```

They are different types

```ts
const status = ref("success" as const); -> Ref<"success">
```

**Comment by tolking** [comment]
webstorm [volar support for vue](https://blog.jetbrains.com/webstorm/2023/05/webstorm-2023-2-eap2/#volar_support_for_vue)
