### ISSUE TITLE
[Component] [select] el-select为什么不能显示绑定的数组数据？

### ISSUE THREAD

**Issue by wwwwhhhzzzccc** [element-plus/element-plus#12196]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.46`
- Element Plus Version: `2.3.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8c3Bhbj5cbiAgICA8ZGl2PlxuICAgICAg5Yid5aeL5pWw5o2u77yae3tkYXRhfX0g546w5Zyo5bem6L655piv56m655qE77yM5LiN5pi+56S65pWw5o2uXG4gICAgPC9kaXY+XG4gICAgPGRpdj5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJkYXRhXCI+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi56ysMemhuVwiIDp2YWx1ZT1cIlsxMjAsMTAwXVwiIC8+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi56ysMumhuVwiIDp2YWx1ZT1cIlsxMCwyMF1cIiAvPlxuICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuesrDPpoblcIiA6dmFsdWU9XCJbMzAsNTBdXCIgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2Rpdj5cbiAgICDlpoLmnpzmiJHmiorkuIrpnaLnmoRlbC1zZWxlY3Tms6jph4rmjonvvIzliJ3lp4vmlbDmja7lkI7pnaLlsLHkvJrmraPluLjmmL7npLpbMTAsMjBdXG4gIDwvc3Bhbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBkYXRhID0gcmVmKFsxMCwyMF0pXG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

刷新即可

### What is Expected?

在el-select组件上正常显示[10,20]选项

### What is actually happening?

实际是显示的为空

### Additional comments

_(empty)_

**Comment by wwwwhhhzzzccc** [comment]
非常恼火，为什么不能显示数组呢？

**Comment by emojiiii** [comment]
你可能改成这样

[例子](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8c3Bhbj5cbiAgICA8ZGl2PlxuICAgICAg5Yid5aeL5pWw5o2u77yae3tkYXRhfX0g546w5Zyo5bem6L655piv56m655qE77yM5LiN5pi+56S65pWw5o2uXG4gICAgPC9kaXY+XG4gICAgPGRpdj5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJkYXRhXCIgbXVsdGlwbGU+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi56ysMemhuVwiIDp2YWx1ZT1cIjEwXCIgLz5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLnrKwy6aG5XCIgOnZhbHVlPVwiMjBcIiAvPlxuICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuesrDPpoblcIiA6dmFsdWU9XCIzMFwiIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gICAg5aaC5p6c5oiR5oqK5LiK6Z2i55qEZWwtc2VsZWN05rOo6YeK5o6J77yM5Yid5aeL5pWw5o2u5ZCO6Z2i5bCx5Lya5q2j5bi45pi+56S6WzEwLDIwXVxuICA8L3NwYW4+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZGF0YSA9IHJlZihbMTAsMjBdKVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
