### ISSUE TITLE
[All] gitee.io站点503

### ISSUE THREAD

**Issue by Ricky816845** [element-plus/element-plus#12223]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Edge leatest ,windows 11`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/)

### Steps to reproduce

打开链接

### What is Expected?

正常访问

### What is actually happening?

503

### Additional comments

不是第一次了,还维护吗?

**Comment by mxdmly** [comment]
多刷新几次就好了， ElementUI 经常提示 400、500， 以前用 Antd 没遇过这个问题

**Comment by MrWeilian** [comment]
跟 org 的轮流试着用吧 [link](https://element-plus.org)

**Comment by lyxxxh** [comment]
官网文档访问真的难受  动不动404 503
