### ISSUE TITLE
[Style] [button, button-group] elementui中el-button点击后按钮颜色不变

### ISSUE THREAD

**Issue by gordon95** [element-plus/element-plus#12221]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-button-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cblx0PGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPuehruWumjwvZWwtYnV0dG9uPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击【确认】按钮，鼠标离开不会恢复原来的颜色。

### What is Expected?

鼠标悬停【确认】按钮才会触发按钮背景色，鼠标离开就没有背景色

### What is actually happening?

点击【确认】按钮会触发按钮背景色，鼠标离开按钮没有恢复原来的颜色

### Additional comments

讲真的，饿了么团队的大佬们，你们难道没注意到这个问题吗？官网button按钮的示例都是点击以后不会恢复原来的颜色，正常情况不应该是鼠标悬浮在按钮上的时候显示颜色，鼠标离开按钮就恢复原来的颜色吗？现在这种设计也太不人性化了吧，希望能修复。

**Comment by gimjin** [comment]
html \<button /> onmousedown的默认策略鼠标按下后处于 focus 状态，也就是看上去没有恢复成原来的颜色（此时是focus样式被激活）。 修改这个问题非常简单，不过不应该破坏w3标准的默认策略，因为网页访问者有正常人、残障人、机器人等，可能会破坏其他使用者的操作。


#### 我提供下面两种方案，快速解决你的问题
1. 阻止 mousedown 时 focus 请看 [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmZ1bmN0aW9uIGRvaW5nICgpIHtcbiAgY29uc29sZS5sb2coJ+WBmuS4gOS6m+S6i+aDhScpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuXHQ8ZWwtYnV0dG9uXG4gICAgdHlwZT1cInByaW1hcnlcIlxuICAgIEBtb3VzZWRvd249XCJlID0+IGUucHJldmVudERlZmF1bHQoKVwiXG4gICAgQGNsaWNrPVwiZG9pbmdcIlxuICA+XG4gICAg56Gu5a6aXG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
2. 你的应用场景并没有 focus 状态的话，可以在主题中把 focus 状态颜色改成normal状态。

**Comment by MrWeilian** [comment]
认同楼上大佬所说的，再补充一个场景：用户点击弹窗且操作完毕后，可以快速恢复到之前的浏览上下文。

而且这个issue在 [#8930](https://github.com/element-plus/element-plus/issues/8390) 有讨论，详细可以点进去看看。

**Comment by gimjin** [comment]
element-plus 维护者们对待 w3 标准我个人是非常认同的，比如
1. element-plus 支持 [a11y](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility), antdv 完全没有适配 aria-disabled 和 :focus-visible, 还有 #8930 讨论的 tdesign 直接把默认行为给干掉了；
2. 还是会引入 css 虽然是 scss 写出来的本质上还是 css，并没有像 naive-ui 那样全部用 js 写出来（虽然某种理念上可能这更高级，可是我不太认可 allin js 的行为）

不过我个人认为 focus 状态 **样式** 的确存在缺陷，focus 状态应该是基于normal状态下更突出视觉效果才对（类似bootstrap5的效果）。 会给最终网页预览者造成困惑和误解
1. 为什么messagebox Confirm 按钮是 disable 状态
2. 为什么点击按钮后，按钮没有恢复而是一直是按下去的状态

@MrWeilian 建议对 focus 状态的颜色、边框上做一些视觉优化。

**Comment by gordon95** [comment]
感谢大佬的指点

**Comment by 2414942130** [comment]
大佬，怎么处理的
