### ISSUE TITLE
[Bug Report] esm build el-select and el-option-group symbol is different

### ISSUE THREAD

**Issue by zcmk123** [element-plus/element-plus#1222]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
windows/chrome

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/full-build-js-can-not-reproduce

### Steps to reproduce
<el-select>
    <el-option-group>
        <el-option />
    </el-option-group>
</el-select>

use es module element-plus option group then get error
injection "Symbol(Select)" not found.
Cannot read property 'selectEmitter' of undefined

### What is Expected?
el-option-group work fine

### What is actually happening?
i clone the project to local, run playgroud, use source code is no problem.
in el-select.vue Symbol 'selectKey'  and el-option-group.vue Symbol 'selectKey' is the same Symbol.

but in es module build element-plus, el-select and el-option-group separate in two different js,

then i found in lib\el-select\index.js
line 22,23 declare these Symbol
const selectGroupKey = Symbol('SelectGroup');
const selectKey = Symbol('Select');

lib\el-option-group\index.js
line 3,4 also declare these two Symbol
const selectGroupKey = Symbol('SelectGroup');
const selectKey = Symbol('Select');

so in el-option-group injection key is a another Symbol, and el-option-group can not get correct injection from el-select

el-select.js
![image](https://user-images.githubusercontent.com/20919760/103870907-4b9af700-5107-11eb-9b07-8a3b10720dab.png)

el-option-group.js
![image](https://user-images.githubusercontent.com/20919760/103870951-5ce40380-5107-11eb-9b82-b9c4f9628ba6.png)

**Comment by JeremyWuuuuu** [comment]
Seems to be the same issue happened before, going to fix soon

**Comment by JeremyWuuuuu** [comment]
Because that individually built components gets a full build on its own, so they all got a `Symbol` but because of the nature of `Symbol` they are NOT THE SAME ONE.

**Comment by zcmk123** [comment]
> Because that individually built components gets a full build on its own, so they all got a `Symbol` but because of the nature of `Symbol` they are NOT THE SAME ONE.

that's what i'm talking about...

**Comment by JeremyWuuuuu** [comment]
I can think of 2 solutions
1. Bail on using `Symbol`
2. Using runtime symbol via object.

**Comment by JeremyWuuuuu** [comment]
For the simplest solution now, you might need to import them via `index.esm.js`, we'll fix this soon.

**Comment by zcmk123** [comment]
> For the simplest solution now, you might need to import them via `index.esm.js`, we'll fix this soon.

alright....
