### ISSUE TITLE
[Style] [notification] ElNotification  css 无法正常 加载 

### ISSUE THREAD

**Issue by icetech233** [element-plus/element-plus#12234]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBib3JkZXIgc2hvdy1zdW1tYXJ5IHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIHNvcnRhYmxlIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBzb3J0YWJsZSBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gIDwvZWwtdGFibGU+XG5cbiAgPGVsLXRhYmxlXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIGJvcmRlclxuICAgIGhlaWdodD1cIjIwMFwiXG4gICAgOnN1bW1hcnktbWV0aG9kPVwiZ2V0U3VtbWFyaWVzXCJcbiAgICBzaG93LXN1bW1hcnlcbiAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgbGFiZWw9XCJDb3N0IDEgKCQpXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgbGFiZWw9XCJDb3N0IDIgKCQpXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJDb3N0IDMgKCQpXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgUHJvZHVjdCB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTdW1tYXJ5TWV0aG9kUHJvcHM8VCA9IFByb2R1Y3Q+IHtcbiAgY29sdW1uczogVGFibGVDb2x1bW5DdHg8VD5bXVxuICBkYXRhOiBUW11cbn1cblxuY29uc3QgZ2V0U3VtbWFyaWVzID0gKHBhcmFtOiBTdW1tYXJ5TWV0aG9kUHJvcHMpID0+IHtcbiAgY29uc3QgeyBjb2x1bW5zLCBkYXRhIH0gPSBwYXJhbVxuICBjb25zdCBzdW1zOiBzdHJpbmdbXSA9IFtdXG4gIGNvbHVtbnMuZm9yRWFjaCgoY29sdW1uLCBpbmRleCkgPT4ge1xuICAgIGlmIChpbmRleCA9PT0gMCkge1xuICAgICAgc3Vtc1tpbmRleF0gPSAnVG90YWwgQ29zdCdcbiAgICAgIHJldHVyblxuICAgIH1cbiAgICBjb25zdCB2YWx1ZXMgPSBkYXRhLm1hcCgoaXRlbSkgPT4gTnVtYmVyKGl0ZW1bY29sdW1uLnByb3BlcnR5XSkpXG4gICAgaWYgKCF2YWx1ZXMuZXZlcnkoKHZhbHVlKSA9PiBOdW1iZXIuaXNOYU4odmFsdWUpKSkge1xuICAgICAgc3Vtc1tpbmRleF0gPSBgJCAke3ZhbHVlcy5yZWR1Y2UoKHByZXYsIGN1cnIpID0+IHtcbiAgICAgICAgY29uc3QgdmFsdWUgPSBOdW1iZXIoY3VycilcbiAgICAgICAgaWYgKCFOdW1iZXIuaXNOYU4odmFsdWUpKSB7XG4gICAgICAgICAgcmV0dXJuIHByZXYgKyBjdXJyXG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgcmV0dXJuIHByZXZcbiAgICAgICAgfVxuICAgICAgfSwgMCl9YFxuICAgIH0gZWxzZSB7XG4gICAgICBzdW1zW2luZGV4XSA9ICdOL0EnXG4gICAgfVxuICB9KVxuXG4gIHJldHVybiBzdW1zXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogUHJvZHVjdFtdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIn0=)

### Steps to reproduce

element.style {
    top: 16px;
    z-index: 2038;
}

这个 报错了

提示的是

position: static 属性可防止 top 产生影响。
不妨尝试将 position 设为除 static 之外的某个值。

### What is Expected?

UI 渲染

### What is actually happening?

通知跑 左下角  UI css 无法正常渲染

### Additional comments

_(empty)_

**Comment by icetech233** [comment]
style="top: 16px; z-index: 2025;"

主要是css  不生效

浏览器报错了

**Comment by icetech233** [comment]
table  上下 分曾了

我看了源码

上面的 标签没有   display: inline-block;   导致左对齐

下面 div  加了 display: inline-block;  导致居中

一个左对齐，
一个居中，


这个table 就不齐啊

**Comment by icetech233** [comment]
好端端的 一个table  为啥要分层 上下2个部分

**Comment by icetech233** [comment]
浏览器  右侧的滚动条 影响了 大部分UI

**Comment by icetech233** [comment]
调试

代码 对比 发现

.el-notification.right {

.el-notification {

少了，

css   没有加载出  这个class


.el-notification.right {

.el-notification {


问题  就在 这里

**Comment by icetech233** [comment]
css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

css

.el-notification.right {

.el-notification {




css

.el-notification.right {

.el-notification {

**Comment by icetech233** [comment]
> 刚刚也遇到类似的问题。使用自动引入组件后，函数调用的弹窗类组件样式失效了。 可能是element的文档没写这部分，vant3的文档在Toast部分有以下内容：
> 
> > 手动引入样式
> > Toast 组件是以函数形式提供的，如果项目中使用 unplugin-vue-components 插件来自动引入组件样式，则无法正确识别 Toast 组件，因此需要手动引入 Toast 组件的样式：
> > import 'vant/es/toast/style';
> > 你可以在项目的入口文件或公共模块中引入 Toast 组件的样式，这样在业务代码中使用 Toast 时，便不再需要重复引入样式了。
> 
> 所以除了这个notification之外其他所有函数式调用的组件应该都要手动引css。
> 
> 刚刚我尝试了另一个办法 虽然官方文档说unplugin-vue-component和unplugin-element-plus是选一个来用，但如果两个都配置，也可以解决这个问题。具体我也不知道什么原理。 不过感觉这样不太保险，还是手动引入函数式组件的css比较稳

最坑的就是 官方文档 不提   scss 要手动

**Comment by MrWeilian** [comment]
官方文档里面有提到以下这点：
![image](https://user-images.githubusercontent.com/30046649/229008620-178706d4-f67e-4f84-88ba-0ba00e5526ee.png)

个人感觉 `unplugin` 插件原理应该是对模板中用到的标签进行解析然后自动帮我们 `import` 进来，但是通过 js 调用 `API` 使用的组件解析不到，所以我个人使用 `unplugin` 插件的项目会在全局先引入这些可以通过 `API` 调用的插件样式，这样就不用担心后续开发中使用 `API` 调用时会漏引入样式的问题了。

希望对你有帮助。
