### ISSUE TITLE
[Component] [descriptions, descriptions-item] el-descriptions自定义类型class-name、label-class-name无效

### ISSUE THREAD

**Issue by TwistDing** [element-plus/element-plus#12235]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome 111.0.5563.65`
- Build Tool: `Vite`

### Related Component

- `el-descriptions`
- `el-descriptions-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGVzY3JpcHRpb25zIGJvcmRlciA6Y29sdW1uPVwiMlwiIGRpcmVjdGlvbj1cImhvcml6b250YWxcIj5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJVc2VybmFtZVwiIDpzcGFuPVwiMVwiIGNsYXNzLW5hbWU9XCJteS1jb250ZW50XCIgbGFiZWwtY2xhc3MtbmFtZT1cIm15LWxhYmVsXCI+a29vcmlvb2thbWk8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICBcdDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlRlbGVwaG9uZVwiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPjE4MTAwMDAwMDAwPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJQbGFjZVwiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPlN1emhvdTwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiUmVtYXJrc1wiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPlNjaG9vbDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiQWRkcmVzc1wiIDpzcGFuPVwiMlwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPk5vLjExODgsIFd1emhvbmcgQXZlbnVlLCBXdXpob25nIERpc3RyaWN0LCBTdXpob3UsIEppYW5nc3UgUHJvdmluY2U8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICA8L2VsLWRlc2NyaXB0aW9ucz5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4gIC5teS1sYWJlbCB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICB9XG4gIFxuICAubXktY29udGVudHtcbiAgICBiYWNrZ3JvdW5kOiAjZjAwO1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

el-descriptions-item配置class-name、label-class-name属性

### What is Expected?

class-name、label-class-name属性生效

### What is actually happening?

属性不生效

### Additional comments

_(empty)_

**Comment by btea** [comment]
This seems to work, but the style selector is not matched, you can refer to this [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGVzY3JpcHRpb25zIGJvcmRlciA6Y29sdW1uPVwiMlwiIGRpcmVjdGlvbj1cImhvcml6b250YWxcIj5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJVc2VybmFtZVwiIDpzcGFuPVwiMVwiIGNsYXNzLW5hbWU9XCJteS1jb250ZW50XCIgbGFiZWwtY2xhc3MtbmFtZT1cIm15LWxhYmVsXCI+a29vcmlvb2thbWk8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICBcdDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlRlbGVwaG9uZVwiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPjE4MTAwMDAwMDAwPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJQbGFjZVwiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPlN1emhvdTwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiUmVtYXJrc1wiIDpzcGFuPVwiMVwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPlNjaG9vbDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiQWRkcmVzc1wiIDpzcGFuPVwiMlwiIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiPk5vLjExODgsIFd1emhvbmcgQXZlbnVlLCBXdXpob25nIERpc3RyaWN0LCBTdXpob3UsIEppYW5nc3UgUHJvdmluY2U8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICA8L2VsLWRlc2NyaXB0aW9ucz5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4gIDpkZWVwKC5teS1sYWJlbCkge1xuICAgIHdpZHRoOiAxMDBweDtcbiAgfVxuICBcbiAgOmRlZXAoLm15LWNvbnRlbnQpIHtcbiAgICBiYWNrZ3JvdW5kOiAjZjAwO1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319).
