### ISSUE TITLE
[Bug Report] Message destroy bug

### ISSUE THREAD

**Issue by Chris-Kin** [element-plus/element-plus#1225]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
macOS/chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/yummy/pen/KKgeoNd

### Steps to reproduce
1. open https://element-plus.org/#/zh-CN/component/message
2. click success button quickly so that showing many message in the page
3. wait until these messages disappear in the page

### What is Expected?
when message disappear, it's dom should remove correctly.

### What is actually happening?
there will be some residual message dom in the page which should be removed.

**Comment by Chris-Kin** [comment]
Here is the video:
https://user-images.githubusercontent.com/10802869/103880236-d1bd3a80-5113-11eb-994b-e56dba042ba4.mov

if fall back to vue 3.0.3, it works fine. or, use after-leave on transition component instead of transitionend event on root dom can also resolve it.

**Comment by JeremyWuuuuu** [comment]
Hey, would you like to make a PR?

**Comment by Chris-Kin** [comment]
ok, I'll create a pr soon

**Comment by Ryan2128** [comment]
@Chris-Kin Hey guys, is there any progress? Why your pr was close by yourself?

**Comment by Chris-Kin** [comment]
> @Chris-Kin Hey guys, is there any progress? Why your pr was close by yourself?

hey there, my solution is replacing transitionend event listener by Transition Component's afterleave event listener, but I haven't found a matching test code of @vue/test-utils yet. And a more fundamental solution may be to find out why transitionend is not triggered in vue3.0.5. BTW, notification component has the same problem. do you hava any idea?

**Comment by Ryan2128** [comment]
OK, this error was fixed in #1270

**Comment by Ryan2128** [comment]
> BTW, notification component has the same problem. do you hava any idea?

Thank you for pointing this out, if you want to fix it, you can make a pr, if not, we will investigate it.

**Comment by Ryan2128** [comment]
If you want to fix the notification's bug, you can open a issue and make a PR. 

I will close this issue.

**Comment by Chris-Kin** [comment]
> If you want to fix the notification's bug, you can open a issue and make a PR.
> 
> I will close this issue.

I have created a [PR](https://github.com/element-plus/element-plus/pull/1378) for fixing notification and some mini optimization in form-item.
