### ISSUE TITLE
[Component] 对于开启多选模式的el-cascader与el-select，动态修改尺寸size失败

### ISSUE THREAD

**Issue by zhuqiaoyue** [element-plus/element-plus#12263]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `chrome100`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`
- `el-select`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHNpemUgPSByZWYoJ2RlZmF1bHQnKTtcbmNvbnN0IGNsaWNrSGFuZGxlID0gYXN5bmMgKCkgPT4ge1xuXHRzaXplLnZhbHVlID0gc2l6ZS52YWx1ZSA9PT0gJ2RlZmF1bHQnID8gJ3NtYWxsJyA6ICdkZWZhdWx0Jztcbn07XG5jb25zdCBvcHRpb25zID0gW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ+a1meaxn+ecgScsXG4gICAgICAgIHZhbHVlOiAnMzMwMDAwJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ+adreW3nuW4gicsXG4gICAgICAgICAgICB2YWx1ZTogJzMzMDEwMCcsXG4gICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICB7IGxhYmVsOiAn5riF5rKz5Yy6JywgdmFsdWU6ICczMzAyMDEnIH0sXG4gICAgICAgICAgICAgIHsgbGFiZWw6ICfpk7bmsrPljLonLCB2YWx1ZTogJzMzMDIwMicgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAn5rGf6IuP55yBJyxcbiAgICAgICAgdmFsdWU6ICczMjAwMDAnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAn6IuP5bee5biCJyxcbiAgICAgICAgICAgIHZhbHVlOiAnMzIwMTAxJyxcbiAgICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICAgIHsgbGFiZWw6ICfmsqfmtarljLonLCB2YWx1ZTogJzMyMDUwMicgfSxcbiAgICAgICAgICAgICAgeyBsYWJlbDogJ+WSjOW5s+WMuicsIHZhbHVlOiAnMzMwMjAzJyB9LFxuICAgICAgICAgICAgXSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdO1xuY29uc3QgY2FzY2FkZXJQcm9wcyA9IHtcblx0bXVsdGlwbGU6IHRydWUsXG59O1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6c2l6ZT1cInNpemVcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrSGFuZGxlXCI+5bC65a+45Y+Y5YyWPC9lbC1idXR0b24+XG4gICAgPGVsLWNhc2NhZGVyIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cImNhc2NhZGVyUHJvcHNcIiAvPlxuICAgIDxlbC1zZWxlY3QgbXVsdGlwbGU+PC9lbC1zZWxlY3Q+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.在全局配置config-provider中配置size
2.使用el-cascader与el-select的多选模式，multiple: true
3.动态改变size

### What is Expected?

动态修改全局配置中的size，多选级联选择器与多选选择器的size随之改变

### What is actually happening?

动态修改全局配置中的size，多选级联选择器与多选选择器的size仍为config-provider中配置的size的初始值

### Additional comments

_(empty)_

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by devie2020** [comment]
不开启多选也一样有问题，这个bug还没有人修复

**Comment by chenxch** [comment]
select fixed in #11973

**Comment by jswxwxf** [comment]
如果不指定 size，这个 bug 依然存在～
