### ISSUE TITLE
[Component] [tree-v2] tree v2 数据量庞大的时候，过滤器搜索不生效

### ISSUE THREAD

**Issue by dk1608735578** [element-plus/element-plus#12266]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

  <ElInput vModel={state.searchName} class="search_name" placeholder="搜索成员、部门" prefixIcon={Search} onInput={handleSearch} />
                <ElTreeV2
                  class="zw-tree-box"
                  vSlots={treeSlots}
                  ref={treeRef}
                  height={400}
                  nodeKey="id"
                  props={{
                    children: 'children',
                    label: 'name'
                  }}
                  filter-method={handleFilterMethod}
                />

### What is Expected?

数据量非常庞大的时候，搜索过滤器的时候，dom需要渲染

### What is actually happening?

大数据搜索的时候dom不渲染

### Additional comments

_(empty)_

**Comment by dk1608735578** [comment]
> 根据评论，这个功能是可以正常使用的，但是数据太多会导致页面卡住，也许你可以在搜索事件中添加一个`debounce`或。`throtte`

In fact, it has nothing to do with the search section. The child nodes below the parent node do not render.
比如，我有一万条数据，父节点A下面有B跟C，我搜索了B,  父节点A渲染了，但是子节点不渲染。但是，数据量少的情况下是可以渲染的

**Comment by btea** [comment]
请提供一个在线链接或者仓库地址方便排查。

**Comment by dk1608735578** [comment]
> 请提供一个在线链接或仓库地址方便排查。

https://stackblitz.com/edit/vue-elgmav?file=src/App.vue
您可以搜索一下“石磊”，结果就是父节点‘杭州直播客服组(80002045)’可以线上，它下面的子节点石磊显示不了

**Comment by btea** [comment]
我测试了一下，发现是数据问题，`石磊`的 id 为 `6315`，`潍坊市奎文区居然之家喜眠专卖店(NO06272)`的 id 也为 `6315`，所以导致过滤出现问题，我把 `石磊` id 改为 `66315`，再进行搜索就没问题。 其他的数据也有id重复的，请检查一下。

**Comment by btea** [comment]
这个问题似乎已经解决，我将关闭这个 issue，如果你还有问题的话，请在下面继续评论。
