### ISSUE TITLE
[Component] [message-box, message] FMessageBox，FMessage的ZIndex无法通过config-provider注入

### ISSUE THREAD

**Issue by dmy1016** [element-plus/element-plus#12264]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `window`
- Build Tool: `Vite`

### Related Component

- `el-message-box`
- `el-message`

### Reproduction Link

[Link]()

### Steps to reproduce

通过config-provider 注入zIndex 但是 FMessgae无法通过useGlobal拿到

### What is Expected?

希望能正常拿到

### What is actually happening?

无法拿到

### Additional comments

_(empty)_

**Comment by dmy1016** [comment]
> Hi, can you provide a link to reproduce it?

no reproduce，大概的意思是这样，我想通过config-provider注入zIndex控制组件的zIndex，但是我发现2.2.19版本注入这个zIndex的时候，message,messageBox无法拿到，还是拿到的初始化2000，但是对于dialog来说，zIndex就可以拿到

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/229000926-f0c13025-d84b-4b7a-9179-7329ff32f684.png)

[链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOm1lc3NhZ2U9XCJjb25maWdcIiA6ei1pbmRleD1cIjMwMDBcIj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwib3BlblwiPk9QRU48L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5jb25zdCBjb25maWcgPSByZWFjdGl2ZSh7XG4gIG1heDogMyxcbn0pXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2Uoe1xuICAgIG1lc3NhZ2U6ICdUaGlzIGlzIGEgbWVzc2FnZS4nLFxuICAgIGR1cmF0aW9uOiAzMDAwMFxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by dmy1016** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/229000926-f0c13025-d84b-4b7a-9179-7329ff32f684.png)
> 
> [链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOm1lc3NhZ2U9XCJjb25maWdcIiA6ei1pbmRleD1cIjMwMDBcIj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwib3BlblwiPk9QRU48L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5jb25zdCBjb25maWcgPSByZWFjdGl2ZSh7XG4gIG1heDogMyxcbn0pXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2Uoe1xuICAgIG1lc3NhZ2U6ICdUaGlzIGlzIGEgbWVzc2FnZS4nLFxuICAgIGR1cmF0aW9uOiAzMDAwMFxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)



> ![image](https://user-images.githubusercontent.com/24516654/229000926-f0c13025-d84b-4b7a-9179-7329ff32f684.png)
> 
> [链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOm1lc3NhZ2U9XCJjb25maWdcIiA6ei1pbmRleD1cIjMwMDBcIj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwib3BlblwiPk9QRU48L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5jb25zdCBjb25maWcgPSByZWFjdGl2ZSh7XG4gIG1heDogMyxcbn0pXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2Uoe1xuICAgIG1lc3NhZ2U6ICdUaGlzIGlzIGEgbWVzc2FnZS4nLFxuICAgIGR1cmF0aW9uOiAzMDAwMFxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by dmy1016** [comment]
change inject method
