### ISSUE TITLE
[Component] [dialog, select] el-dialog组件通过v-model绑定变量是否显示,有时无法通过修改变量关闭el-dialog

### ISSUE THREAD

**Issue by oxkser** [element-plus/element-plus#12261]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome 111.0.5563.65 / win10 20H2`
- Build Tool: `Vue CLI`

### Related Component

- `el-dialog`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBvcmdEaWFsb2dWaXNpYmxlID1yZWYoZmFsc2UpXG5jb25zdCBoYW5kbGVJdXB1dEZvY3VzID0oKT0+e1xuICBvcmdEaWFsb2dWaXNpYmxlLnZhbHVlID10cnVlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgcGxhY2Vob2xkZXI9J+ivt+eCueWHu+i+k+WFpeahhuiBmueEpicgIEBmb2N1cz1cImhhbmRsZUl1cHV0Rm9jdXMoaXRlbSlcIiAvPlxuICA8VGVsZXBvcnQgdG89XCJib2R5XCI+XG4gICAgICA8ZWwtZGlhbG9nXG4gICAgICAgIHYtbW9kZWw9XCJvcmdEaWFsb2dWaXNpYmxlXCJcbiAgICAgICAgdGl0bGU9XCLmtYvor5XlvLnnqpdcIlxuICAgICAgICBkZXN0cm95LW9uLWNsb3NlXG4gICAgICAgIGRyYWdnYWJsZVxuICAgICAgPlxuICAgICAgPHNwYW4+5rWL6K+VPC9zcGFuPlxuICAgICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwib3JnRGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+5Y+W5raIKOeCueWHu+i/memHjOWFs+mXrSk8L2VsLWJ1dHRvbj5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtZGlhbG9nPlxuICAgIDwvVGVsZXBvcnQ+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击el-input输入框使输入框聚焦,并弹出el-dialog组件,然后通过点击el-dialog中#footer中的取消按钮关闭弹窗.

### What is Expected?

弹窗被关闭

### What is actually happening?

弹窗关闭后,立刻被重新打开,因为弹窗被关闭时重新触发了el-input的focus事件,这并不是我们所期望的(点击右上角的关闭按钮时不存在这个问题),并且这在element-plus2.2.22版本中并不存在这个问题

### Additional comments

_(empty)_

**Comment by sleepyShen1989** [comment]
你可以试试在focus触发弹窗的时候让他失去焦点，他触发focus事件本来应该是想做体验优化的
```
const a = ref(null) // el-input ref="a"
const handleIuputFocus =()=>{
  a.value.input.blur()
  orgDialogVisible.value =true
}
```

**Comment by gimjin** [comment]
请使用 click 事件打开 dialog，focus 事件激活后 dialog 被打开，关闭 dialog 时会恢复原页面状态，即恢复 focus。
这是一种进步，《[用户点击弹窗且操作完毕后，可以快速恢复到之前的浏览上下文](https://github.com/element-plus/element-plus/issues/12221#issuecomment-1486328331)》

[快速恢复上下文例子](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCBvcmdEaWFsb2dWaXNpYmxlID1yZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZUl1cHV0Rm9jdXMgPSAoKSA9PiB7XG4gIC8vIOWPs+S4iuinknjlhbPpl63ml7bvvIzlkK/liqjkuoblhbPpl63liqjnlLvvvIzkvYblubbmsqHmnInmioogb3JnRGlhbG9nVmlzaWJsZSDorr7nva7miJBmYWxzZVxuICAvLyDngrnlh7vigJzngrnlh7vov5nph4zlhbPpl63igJ3ml7bpqazkuIrmioogb3JnRGlhbG9nVmlzaWJsZSDorr7nva7miJAgZmFsc2XvvIzmiYDku6XkuIvpnaLorr7nva7miJB0cnVl55Sf5pWIXG4gIGNvbnNvbGUubG9nKG9yZ0RpYWxvZ1Zpc2libGUudmFsdWUpXG4gIC8vIDUwMG1zIOaYryB2dWXlhoXnva7nu4Tku7YgPFRyYW5zaXRpb24gLz4gZHVyYXRpb24g6buY6K6k5YC877yMZWwtZGlhbG9nIOeUqOS6hui/meS4que7hOS7tuWBmuWKqOeUu1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBvcmdEaWFsb2dWaXNpYmxlLnZhbHVlID10cnVlXG4gIH0sIDUwMClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dCBwbGFjZWhvbGRlcj0n6K+354K55Ye76L6T5YWl5qGG6IGa54SmJyAgQGZvY3VzPVwiaGFuZGxlSXVwdXRGb2N1c1wiIC8+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cIm9yZ0RpYWxvZ1Zpc2libGVcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9yZ0RpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPueCueWHu+i/memHjOWFs+mXrTwvZWwtYnV0dG9uPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
