### ISSUE TITLE
[Component] [date-picker]  DateTimePicker组件，日期格式：YYYY年MM月DD日 HH时mm分ss秒，日历组件下拉中的顶部日期及时间input部位，显示错误

### ISSUE THREAD

**Issue by Only92916** [element-plus/element-plus#12275]
![217464134-3e30946a-c9be-4bd3-bc65-389ebdc61fb9](https://user-images.githubusercontent.com/124767639/229005753-dcaa38fe-f02d-449a-977e-140280c89ed9.png)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `win10`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YXVsZSA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICB2LW1vZGVsPVwidmF1bGVcIlxuICAgICAgICAgICAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICAgICAgICAgICAgZm9ybWF0PVwiWVlZWeW5tE1N5pyIRETml6UgSEjml7ZtbeWIhnNz56eSXCJcbiAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdCBkYXRlIGFuZCB0aW1lXCJcbiAgICAgICAgICAgIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

选择日期

### What is Expected?

请修复

### What is actually happening?

请修复

### Additional comments

_(empty)_

**Comment by xiterjia** [comment]
duplicate #11465

**Comment by tolking** [comment]
Fixed by #14330
