### ISSUE TITLE
[Component] [table-v2] table-v2 column.fixed 导致全量渲染

### ISSUE THREAD

**Issue by scvzerng** [element-plus/element-plus#12277]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiA0MDBweFwiPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY29sdW1uc1swXS5maXhlZCA9ICdsZWZ0J1wiPmNvbHVtbiAwIGZpeGVkPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjb2x1bW5zWzBdLmZpeGVkID0gbnVsbFwiPmNvbHVtbiAwIGNhbmNlbCBmaXhlZDwvZWwtYnV0dG9uPlxuICAgIDxlbC1hdXRvLXJlc2l6ZXI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IGhlaWdodCwgd2lkdGggfVwiPlxuICAgICAgICA8ZWwtdGFibGUtdjJcbiAgICAgICAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgICAgICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgICAgICAgOndpZHRoPVwid2lkdGhcIlxuICAgICAgICAgIDpoZWlnaHQ9XCJoZWlnaHRcIlxuICAgICAgICAgIGZpeGVkXG4gICAgICAgIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtYXV0by1yZXNpemVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSBcInZ1ZVwiO1xuIGxldCByZW5kZXJDZWxsQ291bnRVblJlZiA9IDA7XG4gIGNvbnN0IGNlbGxSZW5kZXJDb3VudHMgPSByZWYoMCk7XG4gIGxldCB0aW1lSGFuZGxlcjtcbmNvbnN0IGdlbmVyYXRlQ29sdW1ucyA9IChsZW5ndGggPSAxMCwgcHJlZml4ID0gJ2NvbHVtbi0nLCBwcm9wcz86IGFueSkgPT5cbiAgQXJyYXkuZnJvbSh7IGxlbmd0aCB9KS5tYXAoKF8sIGNvbHVtbkluZGV4KSA9PiAoe1xuICAgIC4uLnByb3BzLFxuICAgIGtleTogYCR7cHJlZml4fSR7Y29sdW1uSW5kZXh9YCxcbiAgICBkYXRhS2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIHRpdGxlOiBgQ29sdW1uICR7Y29sdW1uSW5kZXh9YCxcbiAgICBjZWxsUmVuZGVyZXIoe2NlbGxEYXRhLCByb3dEYXRhfSl7XG4gICAgICBjb25zb2xlLmxvZyhgcmVuZGVyLWNlbGxgKTtcbiAgICAgIHJldHVybiBjZWxsRGF0YVxuICAgIH0sXG4gICAgd2lkdGg6IDE1MCxcbiAgfSkpXG5cbmNvbnN0IGdlbmVyYXRlRGF0YSA9IChcbiAgY29sdW1uczogUmV0dXJuVHlwZTx0eXBlb2YgZ2VuZXJhdGVDb2x1bW5zPixcbiAgbGVuZ3RoID0gMjAwLFxuICBwcmVmaXggPSAncm93LSdcbikgPT5cbiAgQXJyYXkuZnJvbSh7IGxlbmd0aCB9KS5tYXAoKF8sIHJvd0luZGV4KSA9PiB7XG4gICAgcmV0dXJuIGNvbHVtbnMudmFsdWUucmVkdWNlKFxuICAgICAgKHJvd0RhdGEsIGNvbHVtbiwgY29sdW1uSW5kZXgpID0+IHtcbiAgICAgICAgcm93RGF0YVtjb2x1bW4uZGF0YUtleV0gPSBgUm93ICR7cm93SW5kZXh9IC0gQ29sICR7Y29sdW1uSW5kZXh9YFxuICAgICAgICByZXR1cm4gcm93RGF0YVxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IGAke3ByZWZpeH0ke3Jvd0luZGV4fWAsXG4gICAgICAgIHBhcmVudElkOiBudWxsLFxuICAgICAgfVxuICAgIClcbiAgfSlcblxuXG5jb25zdCBjb2x1bW5zID0gcmVmKGdlbmVyYXRlQ29sdW1ucygxMCkpXG5jb25zdCBkYXRhID0gZ2VuZXJhdGVEYXRhKGNvbHVtbnMsIDIwMDApXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

列设置fixed之后鼠标移动到任意行上都会导致所有行被渲染，没有设置fixed属性表现正常，打开控制台观察cellRenderer打印的日志

### What is Expected?

鼠标移动到指定行上不会触发其他行渲染

### What is actually happening?

触发其他行渲染

### Additional comments

查看了下源码 发现是`hoveringRowKey`导致的，
`RowRenderer`会重新计算kls不知道为什么没有`fixed`不会触发，尝试直接给rowData添加私有变量__hovering替换判断发现就不会出现这种问题

![1680236273046](https://user-images.githubusercontent.com/14892120/229021707-73a06be9-a168-489d-849d-1f997165bab6.png)

**Comment by makedopamine** [comment]
#11814或许可以改善这个问题

**Comment by chenxch** [comment]
> #11814 或许可以改善这个问题

和这个关系不大，主要是开启了fixed，需要计算hover同步到fixed列，导致了一直触发单元格的重绘

**Comment by scvzerng** [comment]
> > #11814 或许可以改善这个问题
> 
> 和这个关系不大，主要是开启了fixed，需要计算hover同步到fixed列，导致了一直触发单元格的重绘

是不是可以left和right table 不共享同一个hover变量改为各自独立然后在hover事件里面对这三个变量进行同步

**Comment by chenxch** [comment]
> 是不是可以left和right table 不共享同一个hover变量改为各自独立然后在hover事件里面对这三个变量进行同步

我试着把事件提升到table层代理处理，但是不确定是不是函数式组件的问题，值变化就rerender
