### ISSUE TITLE
[Performance] [select-v2] el-select-v2 组件下的collapse-tags 功能存在性能问题或是逻辑导致的页面卡顿

### ISSUE THREAD

**Issue by keroro-Jun** [element-plus/element-plus#12274]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/111.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIGNvbGxhcHNlLXRhZ3NcbiAgICA6bWF4LWNvbGxhcHNlLXRhZ3M9XCIwXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICBtdWx0aXBsZVxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3Qgb3B0aW9ucyA9IHJlZihcbiAgQXJyYXkuZnJvbSh7IGxlbmd0aDogNTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgICB2YWx1ZTogaWR4LFxuICAgIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbiAgfSkpXG4pXG5jb25zdCB2YWx1ZSA9IHJlZihvcHRpb25zLnZhbHVlLm1hcChyPT4gci52YWx1ZSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

el-select-v2 max-collapse-tags属性设置为0， 在大量数据下，全选或者是选择量过多，

### What is Expected?

在设置了max-collapse-tags = 0 渲染不应该存在卡顿

### What is actually happening?

max-collapse-tags = 0，页面渲染存在卡顿

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
不建议在勾选大量数据的情况下使用 `collapse-tags` 功能，这会导致页面卡顿。

**Comment by keroro-Jun** [comment]
> 不建议在勾选大量数据的情况下使用 `collapse-tags` 功能，这会导致页面卡顿。
但这就是虚拟化列表的其中一个使用场景，会有勾选大量数据。而且在max-collapse-tags = 1 下，性能日志上是看到一些函数好耗时过长，这应该是所有勾选的数据下的el-tag组件执行了把？？ 这需要优化吧

**Comment by emojiiii** [comment]
> 数好耗时过长，这应该是所有勾选的数据下的el-tag组件执行了把？？ 这需要优化吧

虚拟列表只是虚拟化列表，tag 如果你要全部显示，这并没有做虚拟化，所以最好不要试图全选列表的时候显示所有的tag

**Comment by keroro-Jun** [comment]
1

**Comment by keroro-Jun** [comment]
> > 数好耗时过长，这应该是所有勾选的数据下的el-tag组件执行了把？？ 这需要优化吧
> 
> 虚拟列表只是虚拟化列表，tag 如果你要全部显示，这并没有做虚拟化，所以最好不要试图全选列表的时候显示所有的tag

感谢你的回答，但我的设置是只显示一个tag，并没有显示所有tag，具体看[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIGNvbGxhcHNlLXRhZ3NcbiAgICA6bWF4LWNvbGxhcHNlLXRhZ3M9XCIwXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICBtdWx0aXBsZVxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3Qgb3B0aW9ucyA9IHJlZihcbiAgQXJyYXkuZnJvbSh7IGxlbmd0aDogNTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgICB2YWx1ZTogaWR4LFxuICAgIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbiAgfSkpXG4pXG5jb25zdCB2YWx1ZSA9IHJlZihvcHRpb25zLnZhbHVlLm1hcChyPT4gci52YWx1ZSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)， 在只有一个tag情况下，还是存在卡顿，所以我认为是存在不合理的。

**Comment by emojiiii** [comment]
> 在只有一个tag情况下，还是存在卡顿，所以我认为是存在不合理的。

很抱歉，误会你的意思，确实会卡顿
