### ISSUE TITLE
[Docs] [button, color-picker] IDEA prompts WeakWarning when using @click and @change

### ISSUE THREAD

**Issue by NXY666** [element-plus/element-plus#12280]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome 111.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInRlc3RDYWxsXCI+5rWL6K+VXG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cblxuZXhwb3J0IGRlZmF1bHQge1xuXHRuYW1lOiBcIkFwcFwiLFxuXHRkYXRhKCkge1xuXHRcdHJldHVybiB7XG5cdFx0fTtcblx0fSxcblx0bWV0aG9kczoge1xuICAgIHRlc3RDYWxsKCl7XG4gICAgICBcbiAgICB9XG5cdH1cbn07XG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

调用el-button的@click或el-color-picker的@change（目前只测试到这两个）

Call @click for el-button or @change for el-color-picker (only tested to these two so far)

### What is Expected?

通过检测，不提示WeakWarning。

Passes detection without prompting WeakWarning.

### What is actually happening?

提示WeakWarning。

Prompt WeakWarning.

### Additional comments

![image](https://user-images.githubusercontent.com/62371554/229060176-91a8c39f-dd09-4e1a-b86c-d386d18c972e.png)

el-color-picker和上面差不多，但是是不可分配给类型string。

el-color-picker is similar to the above, but is not assignable to type string.

**Comment by chenxch** [comment]
https://github.com/vuejs/language-tools/discussions/571

It is recommended to replace the development tools.

**Comment by tolking** [comment]
WebStorm 有自己的类型实现。目前我们无法修正这个问题

推荐使用 VSCode + Volar
