### ISSUE TITLE
[Component] [message-box] MessageBox在使用VNode时dangerouslyUseHTMLString功能无效

### ISSUE THREAD

**Issue by wwwwhhhzzzccc** [element-plus/element-plus#12286]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.3.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICAgIEVsTWVzc2FnZUJveCh7XG4gICAgICAgIG1lc3NhZ2U6IGgoJ3NwYW4nLCBudWxsLCAnPHA+6L+Z6YeM5pivaHRtbOagvOW8j+WGheWuuTwvcD4nKSxcbiAgICAgICAgZGFuZ2Vyb3VzbHlVc2VIVE1MU3RyaW5nOiB0cnVlLCAgLy8g6L+Z6YeMdHJ1ZeaXoOaViFxuICAgIH0pLmNhdGNoKCgpID0+IHsgfSkgLy8g5re75Yqg6ZSZ6K+v5o2V6I63XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCI+54K55Ye75oiRPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
import { h, ref } from 'vue'
import { ElMessageBox } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const handleClick = () => {
    ElMessageBox({
        message: h('span', null, '<p>这里是html格式内容</p>'),
        dangerouslyUseHTMLString: true,  // 这里true无效
    }).catch(() => { }) // 添加错误捕获
}
</script>

<template>
  <el-button @click="handleClick">点击我</el-button>
</template>

```

### What is Expected?

信息为html格式

### What is actually happening?

信息不为html格式

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Now that the rendering function is used, please use the rendering function correctly. If you want to convert the html text directly, please input the html text directly.
```js
ElMessageBox({
        message: '<span><p>这里是html格式内容</p></span>',
        dangerouslyUseHTMLString: true, 
    }).catch(() => { }) // 添加错误捕获
}
```

or

```js
ElMessageBox({
        message: h('span', null,  h('p', null, '这里是html格式内容<')),
        dangerouslyUseHTMLString: true, 
    }).catch(() => { }) // 添加错误捕获
}
```

**Comment by wwwwhhhzzzccc** [comment]
it's an useless method.


const message = '<p&gt;text1</p&gt;<p&gt;text2</p&gt;'&nbsp; &nbsp; // we need this way


(1)method&nbsp; 1:
ElMessageBox({
        message: message&nbsp;,
        dangerouslyUseHTMLString: true, 
    }).catch(() =&gt; { }) 
}


dangerouslyUseHTMLString:true can not work,


(2)method 2:
ElMessageBox({         message: h('span', null,  h('p', null, message)),         dangerouslyUseHTMLString: true,      }).catch(() =&gt; { })  }


can not work too.
Faied to execute 'createElement' On 'document': the tag name provided ..... is not a valid name




zhangcan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [message-box] MessageBox在使用VNode时dangerouslyUseHTMLString功能无效 (Issue #12286)





 
Now that the rendering function is used, please use the rendering function correctly. If you want to convert the html text directly, please input the html text directly.
 ElMessageBox({         message: '<span&gt;<p&gt;这里是html格式内容</p&gt;</span&gt;',         dangerouslyUseHTMLString: true,      }).catch(() =&gt; { }) // 添加错误捕获 }
 
or
 ElMessageBox({         message: h('span', null,  h('p', null, '这里是html格式内容<')),         dangerouslyUseHTMLString: true,      }).catch(() =&gt; { }) // 添加错误捕获 }
