### ISSUE TITLE
[Component] [statistic] el-statistic统计组件能否接受字符串作为值

### ISSUE THREAD

**Issue by Archieeeeee** [element-plus/element-plus#12303]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-statistic`

### Reproduction Link

[Link]( )

### Steps to reproduce

无

### What is Expected?

value可以接受字符串

### What is actually happening?

value只接受number

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
@Archieeeeee Hello, I am very glad to receive your feedback. At present, the string type is not considered to be supported. If the field is really a string type, try to do a number processing by yourself, for example
`:value="+val"`
