### ISSUE TITLE
[Performance] [menu] el-menu 存在内存泄漏

### ISSUE THREAD

**Issue by Alixhan** [element-plus/element-plus#12307]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Microsoft Edge 版本 111.0.1661.62 (正式版本) (64 位) / windows11`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/menu.html#collapse-%E6%8A%98%E5%8F%A0%E9%9D%A2%E6%9D%BF)

### Steps to reproduce

点击el-menu组件展开收起，收起后产生的内存没有回收
直接打开element-plus官网，el-menu点击展开收缩，查看浏览器内存情况，内存始终没有回收，每收缩一次就会增加大概1M的内存
没有开启Vue.js devtools工具！！！

### What is Expected?

正常GC回收内存

### What is actually happening?

GC后内存没有回收

### Additional comments

可以去官网点下el-menu展开收起看看，和我本地的项目一样不回收，

![image](https://user-images.githubusercontent.com/22884361/229561506-f14b3e70-1bef-48bc-86bf-929114c11554.png)

**Comment by CeceWall** [comment]
尝试分析了一下，可能是由于 ```useMenuCssVar```这个computed对象导致的
[sub-menu.ts#L356](https://github.com/element-plus/element-plus/blob/dev/packages/components/menu/src/sub-menu.ts#L356)
这次每次都生成一个新的computed对象
执行handleMouseleave方法后导致此依赖被错误收集

**Comment by Xdy1579883916** [comment]
据我观察，在菜单里面不使用icon的时候，不卡顿
