### ISSUE TITLE
[Component] icon与文字无法对齐 / el-row中el-switch与el-text也无法对齐

### ISSUE THREAD

**Issue by tjc0726** [element-plus/element-plus#12308]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-icon`
- `el-text`
- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5pbXBvcnQge1xuICBNZW51IGFzIEljb25NZW51XG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZWwtaWNvbj5cbiAgICA8SWNvbk1lbnUgLz5cbiAgICAgICAgPC9lbC1pY29uPlxuICA8ZWwtdGV4dCBzaXplPSdsYXJnZSc+6I+c5Y2VPC9lbC10ZXh0PlxuICA8ZWwtaWNvbiBzdHlsZT1cInZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIj5cbiAgICA8SWNvbk1lbnUgLz5cbiAgPC9lbC1pY29uPlxuICA8ZWwtcm93PlxuICAgICAgICA8ZWwtaWNvbj5cbiAgICA8SWNvbk1lbnUgLz5cbiAgICAgICAgPC9lbC1pY29uPlxuICA8ZWwtdGV4dCBzaXplPSdsYXJnZSc+6I+c5Y2VPC9lbC10ZXh0PlxuICA8ZWwtaWNvbiBzdHlsZT1cInZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIj5cbiAgICA8SWNvbk1lbnUgLz5cbiAgPC9lbC1pY29uPlxuICA8L2VsLXJvdz5cbiAgXG4gIDxlbC1yb3c+XG4gICAgPGVsLXRleHQgc2l6ZT0nbGFyZ2UnPuW8gOWFszwvZWwtdGV4dD48ZWwtc3dpdGNoPjwvZWwtc3dpdGNoPlxuICA8L2VsLXJvdz5cbiAgXG4gIDxlbC10ZXh0IHNpemU9J2xhcmdlJz7lvIDlhbM8L2VsLXRleHQ+PGVsLXN3aXRjaD48L2VsLXN3aXRjaD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

同时使用el-icon以及el-text时高度方向上不对齐
在el-row中使用el-text与el-switch时高度方向好像也没对齐，放在el-row外又是不一样的位置

### What is Expected?

高度方向上对齐

### What is actually happening?

高度方向上不对齐

### Additional comments

各位好，刚开始接触前端以及element ui，这个问题可能是个很蠢的问题，但是一直没研究明白，也不确定是不是bug，希望各位大佬提点，谢谢！

**Comment by kooriookami** [comment]
多个行内元素垂直居中，可以使用flex布局。推荐使用<el-space>组件

**Comment by chenxch** [comment]
你可以考虑把icon放到text标签内或者给row加上align-items:center，这种不同元素高度不同自然很难说默认对齐，所以还是要自己处理的。
