### ISSUE TITLE
[Component] [row] el-row gutter设置大于0的时候出现滚动条

### ISSUE THREAD

**Issue by zengjingke** [element-plus/element-plus#12309]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome 111.0.5563.147（正式版本）`
- Build Tool: `Vite`

### Related Component

- `el-row`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IDpndXR0ZXI9XCIyMFwiPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+MTwvZWwtY29sPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+MjwvZWwtY29sPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+MzwvZWwtY29sPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+NDwvZWwtY29sPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+NTwvZWwtY29sPlxuICAgIDxlbC1jb2wgOnNwYW49XCI0XCI+PGRpdi8+NjwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSA+XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

gutter设置大于0的值

### What is Expected?

不希望出现横向滚动条

### What is actually happening?

出现了横向滚动条

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3d64c78b0341459ebdd76d0a54ae7393~tplv-k3u1fbpfcp-watermark.image?)

这个可能是这种设计方式上的一个缺陷吧，因为利用padding，所以row需要margin 负数补齐首尾2个元素的左右padding丢失的空间，当content+(负margin)的宽度>容器的时候就会出现滚动条，看看先给容器加个overflow:hidden处理一下。

**Comment by zengjingke** [comment]
@chenxch 目前也只能这样处理了，感谢你的回复
