### ISSUE TITLE
[Component] [select] el-select throws error if you try to focus own created tag

### ISSUE THREAD

**Issue by MyNameIsNico** [element-plus/element-plus#12302]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome 111.0.5563.147/Windows`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICBhbGxvdy1jcmVhdGVcbiAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJDaG9vc2UgdGFncyBmb3IgeW91ciBhcnRpY2xlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Click on el-select to open its popper
2. Type in 'ht' to produce a new entry in popper list
3. Press key Arrow Up to focus new entry

### What is Expected?

New entry 'ht' will be focussed and have light gray background, so that you can press Enter to add 'ht' as new tag.

### What is actually happening?

An error occurs in console. It is not possible to focus the new entry 'ht'.

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
Fixed now.
