### ISSUE TITLE
[Component] [select] [Component] [el-select] When el-select enters the search keyword to trigger a line break, there will be abnormal jitter

### ISSUE THREAD

**Issue by leonlyle** [element-plus/element-plus#12301]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.46`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome/111.0.0.0 / Windows NT 10.0; Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHZhbHVlID0gcmVmKFtdKVxuICBcbmNvbnN0IHN0YXRlcyA9IFtcbiAgJ0FsYWJhJyxcbiAgJ0J1c3kxJyxcbiAgJ0J1c3knLFxuXVxuXG5jb25zdCByZW1vdGVNZXRob2QgPSAoKSA9PiB7XG4gIHJldHVybiBzdGF0ZXNcbn1cblxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+XG4gICAgc3RlcHM6IGZvY3VzIHRoZSBjb21wb25tZW50IGFuZCBzZWxlY3QgdGhlIGZpcnN0IGFuZCBzZWNvbmQgb3B0aW9uLCB0aGVuIGVudGVyIGEgbGV0dGVyXG4gIDwvaDE+XG4gIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgcmVtb3RlXG4gICAgICByZXNlcnZlLWtleXdvcmRcbiAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGVudGVyIGEga2V5d29yZFwiXG4gICAgICA6cmVtb3RlLW1ldGhvZD1cInJlbW90ZU1ldGhvZFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gc3RhdGVzXCJcbiAgICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgICA6bGFiZWw9XCJpdGVtXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. Focus the componment
2. Select the first and second option
3. Enter a letter

### What is Expected?

wrap normally

### What is actually happening?

non-stop jitter

### Additional comments

_(empty)_

![20230403143110_rec_](https://user-images.githubusercontent.com/48087835/229429102-9ce189e4-8d34-438b-948f-b56559a2378f.gif)

**Comment by chenxch** [comment]
Same as #12099
