### ISSUE TITLE
[Component] [select] [BUG] Select going crazy at a specific size (Mutliple + filterable)

### ISSUE THREAD

**Issue by Vicftz** [element-plus/element-plus#12315]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome 111.0.5563.146`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbJ09wdGlvbjEnXSlcbmNvbnN0IHBpeGVsID0gcmVmKDE5NylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnTG9uZG9uIC0gdGhlIHNoYXJkJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJtLTRcIj5cbiAgICA8cD5CdWcgbXVsdGlzZWxlY3Qgd2hlbiBtdXRsaXBsZSArIGZpbHRlcmFibGU8L3A+XG4gICAgPHA+RGVwZW5kaW5nIG9uIHRoZSBjb21wdXRlciwgZXJyb3IgbWF5IG9jY3VyZWQgYmV0d2VlbiAxODUgYW5kIDIwMCBweDwvcD5cbiAgICA8ZGl2PlxuICAgIDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cInBpeGVsXCIgOm1pbj1cIjEwMFwiIDptYXg9XCIyNTBcIiAvPlxuICAgIDwvZGl2PlxuICAgIDxwPlxuICAgICAgXG4gICAgPC9wPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIDpzdHlsZT1cIid3aWR0aDonICsgcGl4ZWwgKyAncHgnXCJcbiAgICAgIGZpbHRlcmFibGVcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Change the pixel width (occured at 197px on my example in MacOS)

### What is Expected?

Nothing

### What is actually happening?

Component going crazy

### Additional comments

_(empty)_

**Comment by itsalimanuel** [comment]
Hello @Vicftz , what means "Component going crazy" can you show us a screenshot

**Comment by chenxch** [comment]
same as #12099
