### ISSUE TITLE
[Component] [popover] Popover default trigger has changed from click to hover

### ISSUE THREAD

**Issue by funyapu** [element-plus/element-plus#12312]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gID5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6MjAwcHg7YmFja2dyb3VuZDogeWVsbG93XCI+d2lkZSBjb250ZW50PC9kaXY+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uIGNsYXNzPVwibS0yXCI+Q2xpY2sgdG8gYWN0aXZhdGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Create `el-popover` with no trigger prop.

### What is Expected?

The popped UI should be toggled by click

### What is actually happening?

The pop comes on hover

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
You can use the trigger attribute to specify a trigger method.
