### ISSUE TITLE
[Component] [table, table-column] el-table 列使用<template #default="scole">xxxx</template>的时候，鼠标 连续点击3次全选中之后，然后复制，粘贴出的文本后面带有空格

### ISSUE THREAD

**Issue by lsp27** [element-plus/element-plus#12313]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `任何系统都这样`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#%E5%A4%9A%E9%80%89)

### Steps to reproduce

官网上面的 el-table 
<el-table-column label="Date" width="120">
      <template #default="scope">{{ scope.row.date }}</template>
    </el-table-column>
类似这种 只要在 el-table-column 下面使用 <template #default="scope"，页面渲染之后，鼠标连续快速点击三次选中之后，粘贴出选中的内容，会发现内容后面带空格 window.getSelection().toString() 打印出来看的时候 会是: 'xxxxx\t\n', 会多出 \t

### What is Expected?

打印出来的是：xxxxx\n 或者 xxxxx

### What is actually happening?

打印出来的是：xxxxx\t\n

### Additional comments

_(empty)_

**Comment by MrWeilian** [comment]
好像连不是自定义内容的复制出来也会有换行符额。感觉如果当前有很强的复制需求的话，可以搞个 `v-copy` 的自定义指令，直接复制 `data` 吧，单击内容复制就好，开发成本也不高，体验也还行

**Comment by chenxch** [comment]
在复制 `<div>` 元素中的文本时，如果该元素内包含了多个子元素或者使用了换行符（`\n`）等特殊字符，那么在一些浏览器上会出现自带换行符的情况。这是因为浏览器会将 `<div>` 元素中包含的所有内容都当作纯文本进行处理，并在不同的子元素之间插入一个换行符。

**Comment by lsp27** [comment]
> 
![image](https://user-images.githubusercontent.com/30168530/230520207-3978b3ee-e233-49bc-b1d0-f3e356259656.png)
那怎么说。这个 date 就会出现 \t  而 name 不会呢
![image](https://user-images.githubusercontent.com/30168530/230520305-8730d0b1-2f93-47a6-94f2-d27b22eefa0d.png)

**Comment by lsp27** [comment]
> 在复制 `<div>` 元素中的文本时，如果该元素内包含了多个子元素或者使用了换行符（`\n`）等特殊字符，那么在一些浏览器上会出现自带换行符的情况。这是因为浏览器会将 `<div>` 元素中包含的所有内容都当作纯文本进行处理，并在不同的子元素之间插入一个换行符。

![image](https://user-images.githubusercontent.com/30168530/230520357-da921bf0-ee39-4bf0-83e2-2ea403798760.png)
那怎么说。这个 date 就会出现 \t 而 name 不会呢
![image](https://user-images.githubusercontent.com/30168530/230520383-c93d4b49-a0d9-4ffb-b99c-44192ac62437.png)

**Comment by lsp27** [comment]
> 好像连不是自定义内容的复制出来也会有换行符额。感觉如果当前有很强的复制需求的话，可以搞个 `v-copy` 的自定义指令，直接复制 `data` 吧，单击内容复制就好，开发成本也不高，体验也还行
是不高，但是这确实是个问题
![image](https://user-images.githubusercontent.com/30168530/230520495-736e8c55-6497-4210-a3af-b17b39a8b7ca.png)

![image](https://user-images.githubusercontent.com/30168530/230520505-baa3612e-ff9d-4df4-993a-13dcdd390c61.png)
这个 date 就会出现 \t 而 name 不会

**Comment by chenxch** [comment]
你给name那边换成2个单词看看

**Comment by chenxch** [comment]
你自己用原生代码写个demo看看吧

**Comment by lsp27** [comment]
> 



> 你给name那边换成2个单词看看

![image](https://user-images.githubusercontent.com/30168530/230581790-7f5cf872-cd3c-4247-9b89-3d420d53c374.png)
![image](https://user-images.githubusercontent.com/30168530/230581904-cf73b79c-9f70-44a0-b941-be1a6975ee7c.png)
不懂 为啥 dom 结构一模一样 会出现 \t

**Comment by lsp27** [comment]
> 你给name那边换成2个单词看看

![image](https://user-images.githubusercontent.com/30168530/230582665-4c15c81e-658e-4459-a1eb-e7e7d8f46c63.png)
他两 dom 结构也是一摸一样的
