### ISSUE TITLE
[Component] [table] When a max-height attribute is added to the table component, it constantly calculates the height, triggering page redrawing, jitter, and memory surge.（当Table组件添加max-height和show-summary属性后，它会不断计算高度，从而触发页面重绘、抖动和内存激增）

### ISSUE THREAD

**Issue by wp993080086** [element-plus/element-plus#12322]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.3.2`
- Browser / OS: `Microsoft Edge 111.0.1661.62 / Windows 10 Pro`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgbWF4LWhlaWdodD1cIjI1MFwiIHNob3ctc3VtbWFyeT5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGZpeGVkIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIyMDBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInNpemVcIiBsYWJlbD1cIlNpemVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTAyLTAzJyxcbiAgICBzaXplOiAxMDAwLFxuICAgIG5hbWU6ICdUb20xJ1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTctMDMtMDQnLFxuICAgIHNpemU6IDEwMDEsXG4gICAgbmFtZTogJ1RvbTInXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxOC0wNC0wNScsXG4gICAgc2l6ZTogMTAwMixcbiAgICBuYW1lOiAnVG9tMydcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE5LTA1LTA2JyxcbiAgICBzaXplOiAxMDAzLFxuICAgIG5hbWU6ICdUb200J1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMjAtMDYtMDcnLFxuICAgIHNpemU6IDEwMDQsXG4gICAgbmFtZTogJ1RvbTUnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAyMS0wNy0wOCcsXG4gICAgc2l6ZTogMTAwNSxcbiAgICBuYW1lOiAnVG9tNidcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

English：Using the Table component, after adding the max-height and show-summary attributes, add some data to make the height of the Table exceed the value of max-height. There's going to be a problem.（Bonus: A high-resolution screen is required. If you don't have a high resolution device, use your browser's zoom feature to scale up. You can also appear.）

中文：使用Table组件，添加max-height和show-summary属性后，并添加一些数据，使Table的高度超过max-height的值，就可以复现。（附加：需要高分辨率的屏幕。如果没有，使用浏览器的缩放功能，放大后也可以复现）

```vue
<template>
  <el-table :data="tableData" style="width: 100%" max-height="250" show-summary>
    <el-table-column fixed prop="date" label="Date" width="200" />
    <el-table-column prop="size" label="Size" />
    <el-table-column prop="name" label="Name" />
  </el-table>
</template>

<script lang="ts" setup>
import { onMounted } from 'vue'
const tableData = [
  {
    date: '2016-02-03',
    size: 1000,
    name: 'Tom1'
  },
  {
    date: '2017-03-04',
    size: 1001,
    name: 'Tom2'
  },
  {
    date: '2018-04-05',
    size: 1002,
    name: 'Tom3'
  },
  {
    date: '2019-05-06',
    size: 1003,
    name: 'Tom4'
  },
  {
    date: '2020-06-07',
    size: 1004,
    name: 'Tom5'
  },
  {
    date: '2021-07-08',
    size: 1005,
    name: 'Tom6'
  }
]
</script>
```

### What is Expected?

English：Hopefully the height will be calculated correctly and not cause memory surge.

中文：希望高度正常计算，没有内存激增。

### What is actually happening?

English：Height is constantly recomputed, pages are constantly redrawn, and memory is soaring.

中文：高度一直重复计算，页面不断重绘，内存飙升

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
@wp993080086 Hello, I am very happy to receive your feedback, but I have tested and checked the memory and other performance conditions in various ways, but I have not found the situation you mentioned. Can you provide more information?

**Comment by wp993080086** [comment]
> @wp993080086您好，我很高兴收到您的反馈，但是我已经通过各种方式测试和检查了内存和其他性能条件，但是我没有找到您提到的情况。你能提供更多信息吗？



> @wp993080086您好，我很高兴收到您的反馈，但是我已经通过各种方式测试和检查了内存和其他性能条件，但是我没有找到您提到的情况。你能提供更多信息吗？



>

**Comment by wp993080086** [comment]
> @wp993080086您好，我很高兴收到您的反馈，但是我已经通过各种方式测试和检查了内存和其他性能条件，但是我没有找到您提到的情况。你能提供更多信息吗？

**Comment by wp993080086** [comment]
> @wp993080086您好，我很高兴收到您的反馈，但是我已经通过各种方式测试和检查了内存和其他性能条件，但是我没有找到您提到的情况。你能提供更多信息吗？

This height recalculation will lead to constant redrawing of the page and memory consumption. You can see the sample link provided by me.

**Comment by chenxch** [comment]
![image.png](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2977da2a2909426abee90af933314030~tplv-k3u1fbpfcp-watermark.image?)

I've checked it out, here's my performance graph, you can see that he doesn't have any events happening during that time.

**Comment by wp993080086** [comment]
> ![image.png](https://camo.githubusercontent.com/3ac493d7b17e9a30c1f590376c3a5ff2fa0a5013e22228f18429e3e397a926b3/68747470733a2f2f70312d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f32393737646132613239303934323661626565393061663933333331343033307e74706c762d6b3375316662706663702d77617465726d61726b2e696d6167653f)
> 
> I've checked it out, here's my performance graph, you can see that he doesn't have any events happening during that time.

The point of this problem is the high computation bug. For performance issues, you can increase the amount of data, so far my list has 50 columns, 50 rows or so.

**Comment by chenxch** [comment]
With the example you provided, the problem of continuous redrawing and memory surge that you want to feedback does not occur. Is it an example problem? If yes, it is best to provide an example that can directly reproduce the problem.

**Comment by wp993080086** [comment]
> With the example you provided, the problem of continuous redrawing and memory surge that you want to feedback does not occur. Is it an example problem? If yes, it is best to provide an example that can directly reproduce the problem.

What I want to report back is that the list has been shaking. I find that the reason is that the height changes all the time. You can open the demo and see it on the 2640 resolution screen.

**Comment by chenxch** [comment]
You should describe it clearly. There is no device with this resolution at the moment. If possible, can you provide a screen recording?

**Comment by wp993080086** [comment]
![shake](https://user-images.githubusercontent.com/52116404/230142213-4803bdde-989c-42b8-b1be-f5a0b7989cd1.gif)

**Comment by chenxch** [comment]
@wp993080086 Thank you for the information you provided, I will try to reproduce this problem and locate it.

**Comment by chenxch** [comment]
> If you don't have a high resolution device, use your browser's zoom feature to scale up. You can also appear.

Thank you very much, I reproduced it through the method you said.

**Comment by CeceWall** [comment]
This bug is caused by high dpi rather than high resolution of screen, when the window.devicePixelRatio is a floating-point number, the value of offsetHeight will be a rounding number.
In some cases the ```scrollbarStyle``` will return an empty object rather than an object with maxHeight.
