### ISSUE TITLE
[Bug Report] <el-table-column> contains <el-checkbox-group> will report an error

### ISSUE THREAD

**Issue by CitizenChaos** [element-plus/element-plus#1232]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
win10 64bit 20H2 / Chrome 64bit 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/citizenchaos/pen/abmGmPz

### Steps to reproduce
1. Write the <el-checkbox-group> component in the slot of <el-table-column>
2. The binding value of <el-checkbox-group> is the data of the row
3. The console pannel will throw an error

### What is Expected?
Refer to the correct behavior in https://codepen.io/citizenchaos/pen/eYdMxrd

### What is actually happening?
The console pannel will throw an error

**Comment by JeremyWuuuuu** [comment]
I did a look through the source code. Seems the initial row data was `{}` so when checkbox tries to fetch the `modelValue` it returns `undefined` However, if you tries to solve this issue. you can do this: 

```vue

<script src="https://unpkg.com/vue@3.0.5"></script>
<script src="https://unpkg.com/element-plus@1.0.1-beta.23/lib/index.full.js"></script>
<link rel="stylesheet" href="https://unpkg.com/element-plus@1.0.1-beta.23/lib/theme-chalk/index.css">
<div id="app">
  <el-table :data="tableData">
    <el-table-column label="someLabel">
      <template #default="{ row }">
        <!-- Add v-if to guarantee the value is initialized` -->
        <el-checkbox-group v-if="row.checkList" v-model="row.checkList">
          <el-checkbox label="复选框 A"></el-checkbox>
          <el-checkbox label="复选框 B"></el-checkbox>
        </el-checkbox-group>
      </template>
    </el-table-column>
  </el-table>
</div>
```
Also cc @justwiner

**Comment by justwiner** [comment]
@JeremyWuuuuu @CitizenChaos 

Yes, this will lead to a lot of bugs. `antd/table` passes in the table structure when it is used.
```js
const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    children: [
        /**         sub-column          */
    ]
  }
]

...

<Table columns={columns} dataSource={data} />
```
While `element-plus/table` needs to be rendered to get the table structure, in the future, I will use the `antd/table` solution to solve this problem.

This work should start in three weeks.

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu @CitizenChaos
> 
> Yes, this will lead to a lot of bugs. `antd/table` passes in the table structure when it is used.
> 
> ```js
> const columns = [
>   {
>     title: 'Name',
>     dataIndex: 'name',
>   },
>   {
>     title: 'Age',
>     dataIndex: 'age',
>     children: [
>         /**         sub-column          */
>     ]
>   }
> ]
> 
> ...
> 
> <Table columns={columns} dataSource={data} />
> ```
> 
> While `element-plus/table` needs to be rendered to get the table structure, in the future, I will use the `antd/table` solution to solve this problem.
> 
> This work should start in three weeks.

The way that I proposed is a solution for users who uses `slots`, you might give an alternative solution but I think it is better we stay consistent with v2.
