### ISSUE TITLE
[Component] When using el-container, el-aside, and el-footer in Nuxt3 layouts/default.vue, they are rendered twice when SSG is performed.

### ISSUE THREAD

**Issue by SatoshiRoppongi** [element-plus/element-plus#12334]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `111.0.5563.146（Official Build） （arm64）`
- Build Tool: `Vite`

### Related Component

- `el-aside`
- `el-footer`
- `el-main`
- `el-container`

### Reproduction Link

[Github Repo](https://github.com/SatoshiRoppongi/roppong-blog2/blob/master/layouts/default.vue)

### Steps to reproduce

I am developing a blog using Nuxt3 and Element Plus. I am deploying it to Firebase Hosting by generating it with CircleCI. The blog is in Japanese and can be accessed at https://roppong.com/blog/.

While there are no issues when I run "yarn dev" locally and open it at localhost:3000, some parts of the layout are duplicated when I deploy it to the server. Please refer to the attached image for an example. (The header menu is not affected, but the sidebar, content area, and footer are duplicated.)

Although the blog page can be accessed without any problems by clicking on the link at https://roppong.com/, the issue occurs when accessing /blog directly.

### What is Expected?

render layouts only once

### What is actually happening?

render layouts twice

### Additional comments

Im not sure its nuxt3's problem or element plus problem

**Comment by SatoshiRoppongi** [comment]
look at the footer. Its double footer.
<img width="1665" alt="capture" src="https://user-images.githubusercontent.com/12537347/230076229-cfa15a99-ed6a-4efd-af50-b671be0ccdf8.png">

**Comment by kooriookami** [comment]
Hi there, I seem to have found the reason why `footer` rendered twice. At first, I visited https://roppong.com/blog/directly, my google chrome shown everything properly. Because I installed `Adblock Plus` plugin. When I closed the plugin, the `footer` rendered twice, many ads popped up on your page. So, I guess it's a bug caused by google ads. May be you can try to write a clean page and see if there are any problems.

**Comment by SatoshiRoppongi** [comment]
@kooriookami 

Thank you for your response.
I turned off the display of ads on Google AdSense, and the issue was resolved.
I have decided to give up on earning revenue through Google AdSense for a while!
