### ISSUE TITLE
[Component] [upload] [el-upload] 升级到2.3.2后，上传组件上传全线报错，无法使用

### ISSUE THREAD

**Issue by wanglong617** [element-plus/element-plus#12340]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome 96`
- Build Tool: `Webpack`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIG11bHRpcGxlXG4gICAgOm9uLXByZXZpZXc9XCJoYW5kbGVQcmV2aWV3XCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yZVVwbG9hZFwiXG4gICAgOm9uLXJlbW92ZT1cImhhbmRsZVJlbW92ZVwiXG4gICAgOmJlZm9yZS1yZW1vdmU9XCJiZWZvcmVSZW1vdmVcIlxuICAgIDpsaW1pdD1cIjk5OTlcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UsIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbl0pXG5cbmNvbnN0IHVwbG9hZERhdGEgPSByZWFjdGl2ZTx7XG4gIGtleTogc3RyaW5nO1xufT4oe1xuICBrZXk6ICcnLFxufSk7XG5cbi8vIOaooeaLn+WbvueJh+WOi+e8qeeoi+W6j1xuY29uc3QgY29tcHJlc3NJbWFnZSA9IChyYXdGaWxlLCBjYikgPT4ge1xuICAvLyDmraTlpITlupTosIPnlKggbmV3IEltYWdlQ29tcHJlc3NvcihvcHRpb25zKSDljovnvKnlupNcbiAgLy8g5qih5ouf5Y6L57yp5Zue6LCDXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNiKHJhd0ZpbGUpXG4gIH0sIDEwMDApXG59XG5cbmNvbnN0IGJlZm9yZVVwbG9hZDogVXBsb2FkUHJvcHNbJ2JlZm9yZVVwbG9hZCddID0gKHJhd0ZpbGU6IFVwbG9hZFJhd0ZpbGUpID0+IHtcbiAgLy8g5Y2H57qn5YiwIDIuMy4y54mI5pys5Lul5ZCO77yMYmVmb3JlVXBsb2Fk5aW95YOP5LiN6K+G5YircHJvbWlzZeS6hu+8jOWvvOiHtOS7peWJjeeahOWKn+iDveWFqOmDqOaKpemUme+8jOS4iuS8oE9TU+S5n+aKpemUmeS6hlxuICByZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XG4gICAgLy8g5qih5ouf5byC5q2l5aSE55CGXG4gICAgLy8gMS4g6K+35rGCYXBp5ou/b3Nz55qE6YWN572u5pWw5o2uXG4gICAgLy8gMi4g5qih5ouf56ys5LiJ5pa55Zu+54mH5aSE55CG5bqT55qE5byC5q2l5Zue6LCD5Ye95pWw77yM5aaC6LCD55SoIEltYWdlQ29tcHJlc3NvciDljovnvKnlm77niYfnrYlcbiAgICBzZXRUaW1vdXQoKCkgPT4ge1xuICAgICAgdXBsb2FkRGF0YS5rZXkgPSBgJHtyYXdGaWxlLm5hbWV9YDtcbiAgICAgIGNvbXByZXNzSW1hZ2UocmF3RmlsZSwgcmVzdWx0ID0+IHtcbiAgICAgICAgcmVzb2x2ZShyZXN1bHQpXG4gICAgICB9KVxuICAgIH0sIDIwMDApXG4gIH0pO1xuICBcbn07XG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAoZmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2coZmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9ICh1cGxvYWRGaWxlKSA9PiB7XG4gIGNvbnNvbGUubG9nKHVwbG9hZEZpbGUpXG59XG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIEVsTWVzc2FnZS53YXJuaW5nKFxuICAgIGBUaGUgbGltaXQgaXMgMywgeW91IHNlbGVjdGVkICR7ZmlsZXMubGVuZ3RofSBmaWxlcyB0aGlzIHRpbWUsIGFkZCB1cCB0byAke1xuICAgICAgZmlsZXMubGVuZ3RoICsgdXBsb2FkRmlsZXMubGVuZ3RoXG4gICAgfSB0b3RhbGx5YFxuICApXG59XG5cbmNvbnN0IGJlZm9yZVJlbW92ZTogVXBsb2FkUHJvcHNbJ2JlZm9yZVJlbW92ZSddID0gKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIHJldHVybiBFbE1lc3NhZ2VCb3guY29uZmlybShcbiAgICBgQ2FuY2VsIHRoZSB0cmFuc2ZlcnQgb2YgJHt1cGxvYWRGaWxlLm5hbWV9ID9gXG4gICkudGhlbihcbiAgICAoKSA9PiB0cnVlLFxuICAgICgpID0+IGZhbHNlXG4gIClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

const beforeUpload: UploadProps['beforeUpload'] = (rawFile: UploadRawFile) => {
  // 升级到 2.3.2版本以后，beforeUpload好像不识别promise了，导致以前的功能全部报错，上传OSS也报错了。
  return new Promise(resolve => {
    // 模拟异步处理
    // 1. 请求api拿oss的配置数据
    // 2. 模拟第三方图片处理库的异步回调函数，如调用 ImageCompressor 压缩图片等
    setTimout(() => {
      uploadData.key = `${rawFile.name}`;
      compressImage(rawFile, result => {
        resolve(result)
      })
    }, 2000)
  });
};

### What is Expected?

以前的逻辑是对的，beforeUpload会等待promise的返回，promise返回后，才会进行下一步的上传。

### What is actually happening?

新的2.3.2版本出大bug了，beforeUpload会直接同步执行，不支持promise等待了，导致所有在promise里的对data赋值的代码全部失效，在上传文件时并没有把有效的参数带上去，导致上传功能全崩了。。

### Additional comments

请开发团队仔细看一下，这个问题太严重了，整条生产线因为更新了2.3.2，所有上传不能用了。。。感谢。。

**Comment by btea** [comment]
It seems to be related to this pr  #12029  
cc @chenxch

**Comment by chenxch** [comment]
Received, @wanglong617  please roll back to version 2.3.1 to ensure the normal operation of your business, we will investigate this problem.

**Comment by chenxch** [comment]
@wanglong617 是key丢失是么？ 新版本是修复了一个多选上传key会变成最后一个文件触发beforeUpload的事件内设置的值的问题（例如用文件名做key，[1.txt,2.txt] 上传的时候key全是2.txt，我用2.3.1版本测试你的demo也是存在这个问题

**Comment by wanglong617** [comment]
其实准确的问题是，在beforeUpload钩子里，在Promise中的异步处理中（比如setTimeout这种）涉及到修改 data 的数据绑定操作，都不起作用，无法响应到 <el-upload :data="无法响应修改">，所以最终会导致key之类的丢失。

**Comment by chenxch** [comment]
因为之前的方式修改data是存在我上面说的问题，key全部变成最后一个文件beforeupload事件中修改的值了，你可以把data的修改代码从promise中移出来看看

**Comment by wanglong617** [comment]
这个问题上个版本也有的，我是生了一个大版本后发现不行了。不过我用其它方式做好了，我不在promise里做了。
不过这里还是要提一下这个问题，在beforeupload里的promise里的异步中处理data是不生效的。

**Comment by chenxch** [comment]
嗯 因为现在代码是在promise前缓存了一份data，所以出现了你说的情况，这块我们会考虑一下如何去保证2种方式的都能正常执行。

**Comment by Abernethy-BY** [comment]
Please ask when the new version will be updated @btea

**Comment by btea** [comment]
@Abernethy-BY We usually release a new version on Friday.
