### ISSUE TITLE
[Component] [tree-select] el-tree-select 的 clearable 功能失效

### ISSUE THREAD

**Issue by xjt610056371** [element-plus/element-plus#12347]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PnRyZWUx77yaY2xlYXJhYmxl5Yqf6IO95Y+v5Lul5q2j5bi45L2/55SoPC9kaXY+XG4gIDx0ZW1wbGF0ZSB2LWZvcj1cIm9wdGlvbiBpbiB0cmVlMVwiPlxuICAgIDxlbC10cmVlLXNlbGVjdFxuICAgICAgICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqemDqOmXqFwiXG4gICAgICAgIHYtbW9kZWw9XCJvcHRpb24udmFsdWVcIlxuICAgICAgICA6ZGF0YT1cImRlcGFydG1lbnRMaXN0XCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgIHNob3ctY2hlY2tib3hcbiAgICBcdFx0bXVsdGlwbGVcbiAgICBcdFx0bm9kZUtleT1cImlkXCJcbiAgICAgICAgICAgICAgICAgICAgLz5cbiAgPC90ZW1wbGF0ZT5cbiAgPGRpdj50cmVlMu+8mmNsZWFyYWJsZeWKn+iDveS4jeWPr+S7peS9v+eUqO+8iOWPquimgXRyZWUy5Zyo6K+35rGC5LmL5ZCO6YeN5paw6K6+572u77yMY2xlYXJhYmxl5Yqf6IO95bCx5peg5rOV5L2/55So77yJPC9kaXY+XG4gIDx0ZW1wbGF0ZSB2LWZvcj1cIm9wdGlvbiBpbiB0cmVlMlwiPlxuICAgIDxlbC10cmVlLXNlbGVjdFxuICAgICAgICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqemDqOmXqFwiXG4gICAgICAgIHYtbW9kZWw9XCJvcHRpb24udmFsdWVcIlxuICAgICAgICA6ZGF0YT1cImRlcGFydG1lbnRMaXN0XCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgIHNob3ctY2hlY2tib3hcbiAgICBcdFx0bXVsdGlwbGVcbiAgICBcdFx0bm9kZUtleT1cImlkXCJcbiAgICAgICAgICAgICAgICAgICAgLz5cbiAgPC90ZW1wbGF0ZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uQmVmb3JlTW91bnQgfSBmcm9tICd2dWUnXG5jb25zdCBkZXBhcnRtZW50TGlzdCA9IHJlZihbXG4gIHsgXG4gICAgaWQ6IDEsIFxuICAgIGxhYmVsOiAn5oqA5pyv6YOoJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAgeyBpZDogNCwgbGFiZWw6ICflkI7nq6/pg6gnIH0sXG4gICAgICB7IGlkOiA1LCBsYWJlbDogJ+WJjeerr+mDqCcgfSxcbiAgICBdXG4gIH0sXG4gIHsgXG4gICAgaWQ6IDIsIFxuICAgIGxhYmVsOiAn6KGM5pS/6YOoJywgXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHsgaWQ6IDYsIGxhYmVsOiAn566h55CG6YOoJyB9LFxuICAgICAgeyBpZDogNywgbGFiZWw6ICfljavnlJ/pg6gnIH0sXG4gICAgXVxuICB9LFxuICB7IFxuICAgIGlkOiAzLCBcbiAgICBsYWJlbDogJ+WuoeaJuemDqCcsIFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7IGlkOiA4LCBsYWJlbDogJ+S/oeWuoemDqCcgfSxcbiAgICAgIHsgaWQ6IDksIGxhYmVsOiAn5YKs5pS26YOoJyB9LFxuICAgIF1cbiAgfSxcbl0pXG5jb25zdCB0cmVlMSA9IHJlZihbXG4gIHt2YWx1ZTogW119LFxuICB7dmFsdWU6IFtdfSxcbl0pXG5jb25zdCB0cmVlMiA9IHJlZihbXG4gIHt2YWx1ZTogW119LFxuICB7dmFsdWU6IFtdfSxcbl0pXG5jb25zdCByZXNxdWVzdCA9ICgpID0+IHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7XG4gICAgc2V0VGltZW91dChyZXNvbHZlLCAxMDAwKVxuICB9KVxufVxub25CZWZvcmVNb3VudChhc3luYyAoKSA9PiB7XG4gIC8qdHJlZTIudmFsdWUgPSBbXG4gICAge3ZhbHVlOiBbXX0sXG4gICAge3ZhbHVlOiBbXX0sXG4gIF0qL1xuICBhd2FpdCByZXNxdWVzdCgpXG4gIHRyZWUyLnZhbHVlID0gW1xuICAgIHt2YWx1ZTogW119LFxuICAgIHt2YWx1ZTogW119LFxuICBdXG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、选中 tree1 的节点
2、点击 clearable 清除选中数据，清除成功
3、在请求之后重新设置 tree2 的数据
4、选中 tree2 的节点
5、点击 clearable 清除选中数据，清除失败

### What is Expected?

清除选中数据，清除成功

### What is actually happening?

清除选中数据，清除失败

### Additional comments

_(empty)_

**Comment by CeceWall** [comment]
I thought this bug is caused by the famous closure pitfall.

**Comment by kooriookami** [comment]
现在似乎没问题
