### ISSUE TITLE
[bug report] after the message component is triggered many times, if it is triggered again, its position will shift downward

### ISSUE THREAD

**Issue by allen-wIki** [element-plus/element-plus#1234]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
win10 / Google Chrome 版本 87.0.4280.88（正式版本）

### Vue version
3.0.5

### Reproduction Link
https : //elementui.github.io/issue-generator/#/zh-CN? repo = element- plus

### Steps to reproduce
触发ElMessage弹框,重复触发,等到所有的弹框关闭后,再次多次触发,再等待全部关闭,再次多次触发,Message出现的位置会随着触发的次数 位置不断的往下偏移

### What is Expected?
在初始位置

### What is actually happening?
出现的位置不对

**Comment by kooriookami** [comment]
Seems related to #1225

**Comment by Ryan2128** [comment]
This error might be fixed in #1270 , you can check if this problem still exists or not.

**Comment by Ryan2128** [comment]
I will close this issue, if this problem still exists, plrease reopen it.

**Comment by JeremyWuuuuu** [comment]
I confirmed this is not resolved. Will fix soon.
