### ISSUE TITLE
[Component] [dropdown-item, input] Lost focus on input in el-dropdown-item

### ISSUE THREAD

**Issue by ReWWeR** [element-plus/element-plus#12343]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-dropdown-item`
- `el-input`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/7kjrxchb/)

### Steps to reproduce

Create `el-dropdown` component with `el-input` inside of `el-dropdown-item`.
Something like that:
```vue
<el-dropdown trigger="click" :hide-on-click="false">
    <span class="el-dropdown-link">
      Dropdown List
    </span>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item>Action 1 <el-input v-model="message" /></el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
```

- Click on dropdown to open it
- Click on input to focus on it
- move mouse pointer out of the dropdown item
- Focus from input will be lost

### What is Expected?

Focus on input stay in place

### What is actually happening?

Focus moved from input somewhere else

### Additional comments

_(empty)_

**Comment by adrkn** [comment]
Any ideas?
