### ISSUE TITLE
[Docs] [select] select组件的teleported属性说明文案能否调整一下，会有歧义

### ISSUE THREAD

**Issue by saligia28** [element-plus/element-plus#12352]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.28`
- Browser / OS: `macOS 13`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E9%80%89%E9%A1%B9)

### Steps to reproduce

文案写的很涩

### What is Expected?

改成跟el-pop中teleported属性的说明一样

### What is actually happening?

写的有歧义

### Additional comments

popper-append-to-body这个属性在select组件中已经废弃，然后teleported属性中说明为是否绑定，我的理解就变成了teleported是一个自定义appendTo目标的开关，开就是能够指定绑定的dom，实际不是这样。

**Comment by iamkun** [comment]
Fixed, THX
