### ISSUE TITLE
[Component] [tooltip] v-model:visible和:visible表现不一致

### ISSUE THREAD

**Issue by 0xOK** [element-plus/element-plus#12361]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Google Chrome	111.0.5563.147 (正式版本) ；windows 10`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIDxlbC10b29sdGlwIHBsYWNlbWVudD1cInRvcFwiIHRyaWdnZXI9XCJjbGlja1wiPlxuICAgIDx0ZW1wbGF0ZSAjY29udGVudD4gbXVsdGlwbGUgbGluZXM8YnIgLz5zZWNvbmQgbGluZSA8L3RlbXBsYXRlPlxuICAgIDxlbC1idXR0b24+VG9wIGNlbnRlcjwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+IC0tPlxuXG5cbiAgPCEtLSB2LW1vZGVsOnZpc2libGUtLT5cbiAgPGVsLXRvb2x0aXAgdi1tb2RlbDp2aXNpYmxlPVwidmlzaWJsZTBcIiBjb250ZW50PVwiQm90dG9tIGNlbnRlclwiIHBsYWNlbWVudD1cImJvdHRvbVwiIHRyaWdnZXI9XCJjbGlja1wiPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZTAgPSAhdmlzaWJsZTBcIj50ZXN0MDwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+XG5cbiAgPCEtLSA6dmlzaWJsZS0tPlxuICA8ZWwtdG9vbHRpcCA6dmlzaWJsZT1cInZpc2libGUxXCIgY29udGVudD1cIkJvdHRvbSBjZW50ZXJcIiBwbGFjZW1lbnQ9XCJib3R0b21cIiB0cmlnZ2VyPVwiY2xpY2tcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUxID0gIXZpc2libGUxXCI+dGVzdDE8L2VsLWJ1dHRvbj5cbiAgPC9lbC10b29sdGlwPlxuICBcbiAgPCEtLSA6dmlzaWJsZS0tPlxuICA8ZWwtdG9vbHRpcCA6dmlzaWJsZT1cInZpc2libGUyXCIgY29udGVudD1cIkJvdHRvbSBjZW50ZXJcIiBwbGFjZW1lbnQ9XCJib3R0b21cIiB0cmlnZ2VyPVwiY2xpY2tcIj5cbiAgICA8ZWwtYnV0dG9uID50ZXN0MjwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+XG48L3RlbXBsYXRlPlxuXG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2aXNpYmxlMCA9IHJlZihmYWxzZSlcbmNvbnN0IHZpc2libGUxID0gcmVmKGZhbHNlKVxuY29uc3QgdmlzaWJsZTIgPSByZWYoZmFsc2UpXG5cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uc2luZ2xldG9uLXRvb2x0aXAge1xuICB0cmFuc2l0aW9uOiB0cmFuc2Zvcm0gMC4zcyB2YXIoLS1lbC10cmFuc2l0aW9uLWZ1bmN0aW9uLWZhc3QtYmV6aWVyKTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <!-- v-model:visible-->
  <el-tooltip v-model:visible="visible0" content="Bottom center" placement="bottom" trigger="click">
    <el-button @click="visible0 = !visible0">test0</el-button>
  </el-tooltip>

  <!-- :visible-->
  <el-tooltip :visible="visible1" content="Bottom center" placement="bottom" trigger="click">
    <el-button @click="visible1 = !visible1">test1</el-button>
  </el-tooltip>
  
  <!-- :visible-->
  <el-tooltip :visible="visible2" content="Bottom center" placement="bottom" trigger="click">
    <el-button >test2</el-button>
  </el-tooltip>
</template>


<script setup lang="ts">
import { ref } from 'vue'
const visible0 = ref(false)
const visible1 = ref(false)
const visible2 = ref(false)

</script>


```

### What is Expected?

trigger = 'click'中，
`v-model:visible`的组件，点击后不会展示popper，
或者`:visible`的组件，点击后展示popper，
或者不改代码，在文档中申明两者的区别。

### What is actually happening?

在本样例中，
`v-model:visible`的组件，点击后会立即打开，而后调用`@click="visible0 = !visible0"`，然后立即关闭。
`:visible`的不会打开，仅调用`@click="visible0 = !visible0"`,正常显示。

### Additional comments

Popover组件也有这个问题， 因为是用tooltip封装的。

**Comment by leaft** [comment]
在`el-tooltip`上使用`v-model:visible`会添加一个默认的`update:visible`事件，因而被误判为非受控组件（存在默认的updateHandler），导致问题的产生

https://github.com/element-plus/element-plus/blob/4a9397dd7e0ec1a7eec0bdba4ab99197ad3f50f5/packages/components/tooltip/src/tooltip.vue#L111-L113

直接修改判断逻辑为 `() => isBoolean(props.visible)` 可以解决问题，但不确定是否会引起其他问题

**Comment by chenxch** [comment]
@0xOK  正如 @leaft 所说，这个组件在设计上做了受控相关的设计，其实很好区分两者，默认情况下用v-model:visible+trigger去控制，当你有一些特殊需求的时候，需要全部由你的代码去控制它的显示和隐藏的时候就可以使用:visible.
