### ISSUE TITLE
[Component] [table-v2] el-table v2 的高度自适应在data更新后失效

### ISSUE THREAD

**Issue by tjc0726** [element-plus/element-plus#12376]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgICAgPGVsLXRhYmxlLXYyIDpjb2x1bW5zPVwiY29sdW1uc1wiIDpkYXRhPVwiZGF0YVwiIDp3aWR0aD1cIjQwMFwiIDpoZWlnaHQ9XCIyMDBcIlxuICAgICAgICA6ZXN0aW1hdGVkLXJvdy1oZWlnaHQ9XCI0MFwiIGZpeGVkLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0ZXN0XCI+5rWL6K+VXG48L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBDb2x1bW4gfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB0ZXN0ID0gKCkgPT4ge1xuICBkYXRhLnZhbHVlWzBdLmRlc2NyaXB0aW9uID0gJ0NOU09FREZFTlZTSU9OQ0RLVk5XT1JJTlZLQ0xERU9XSVZITkVPUk5LIEVPUlZFUklLTlYgTVdQS0lOVlBJS1dSJ1xufVxuXG5cbmNvbnN0IGNvbHVtbnM6IENvbHVtbjxhbnk+W10gPSBbXG4gIHtcbiAgICBrZXk6ICdpZCcsXG4gICAgZGF0YUtleTogJ2lkJyxcbiAgICB3aWR0aDogMTUwLFxuICB9LFxuICB7XG4gICAga2V5OiAnZGVzY3JpcHRpb24nLFxuICAgIHRpdGxlOiAnRGVzY3JpcHRpb24nLFxuICAgIGRhdGFLZXk6ICdkZXNjcmlwdGlvbicsXG4gICAgd2lkdGg6IDE1MFxuICB9LFxuXVxuY29uc3QgZGF0YSA9IHJlZihcbiAgW3tcbiAgICAgICAgXCJkZXNjcmlwdGlvblwiOiBcIlRFU1RcIixcbiAgICAgICAgXCJpZFwiOiA2LFxuICAgICAgICBcInBvaW50X2lkXCI6IDMwLFxuICAgICAgICBcImRpcmVjdGlvblwiOiAzXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZGVzY3JpcHRpb25cIjogXCJOREpBTkRKU05DRktGRUVcIixcbiAgICAgICAgXCJpZFwiOiAxMSxcbiAgICAgICAgXCJwb2ludF9pZFwiOiAzMSxcbiAgICAgICAgXCJkaXJlY3Rpb25cIjogMlxuICAgIH0sXG4gICAge1xuICAgICAgICBcImRlc2NyaXB0aW9uXCI6IFwiTkZVSlNIRlVKTkNLSiBEU0JGSVVXTkVDT0VGQ0hPSVwiLFxuICAgICAgICBcImlkXCI6IDE0LFxuICAgICAgICBcInBvaW50X2lkXCI6IDMxLFxuICAgICAgICBcImRpcmVjdGlvblwiOiAzXG4gICAgfV1cbilcblxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击测试按钮

### What is Expected?

第一行高度自适应变化

### What is actually happening?

未变化

### Additional comments

我不确定这是不是预期的行为，如果是预期行为，有更好的办法来让其自适应高度吗

**Comment by zhengbangbo** [comment]
在普通表格 `el-table` 中，实际情况是第一行高度自适应变化。

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTUwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXRlXCIgbGFiZWw9XCJTdGF0ZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJjaXR5XCIgbGFiZWw9XCJDaXR5XCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiB3aWR0aD1cIjYwMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiemlwXCIgbGFiZWw9XCJaaXBcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk9wZXJhdGlvbnNcIiB3aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PlxuICAgICAgICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBzaXplPVwic21hbGxcIiBAY2xpY2s9XCJoYW5kbGVDbGlja1wiXG4gICAgICAgICAgPkRldGFpbDwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbiBsaW5rIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCI+RWRpdDwvZWwtYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0ZXN0XCI+5rWL6K+VXG48L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnY2xpY2snKVxufVxuXG5jb25zdCB0ZXN0ID0gKCkgPT4ge1xuICB0YWJsZURhdGEudmFsdWVbMF0ubmFtZSA9ICfliIYnXG59XG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRtJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbl0pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

不确定虚拟化表格是否出于考虑超大数据渲染而特意保持了不变的表格结构。

**Comment by zhengbangbo** [comment]
Duplicate of https://github.com/element-plus/element-plus/issues/12382
