### ISSUE TITLE
[Bug Report] table 设置固定列后，safari浏览器不起作用，并出现错位

### ISSUE THREAD

**Issue by april-chen** [element-plus/element-plus#12374]
### Element Plus version
2.2.22

### OS/Browsers version
10.14.6/12.1.2

### Vue version
3.2.13

### Reproduction Link
https://codepen.io/april226/pen/oNagJLO

### Steps to reproduce
官网在safari中打开，示例可见问题，固定列无法定位，且会出现错位

### What is Expected?
官网在safari中打开，示例可见问题，固定列无法定位，且会出现错位

### What is actually happening?
官网在safari中打开，示例可见问题，固定列无法定位，且会出现错位

**Comment by chenxch** [comment]
抱歉，我目前展示无法上传录屏，我本地用safari查看了官网的fixed demo是正常的。你提供的repo是错误的，方便提供更多信息么？
