### ISSUE TITLE
[Component] [input] input输入框添加clearable属性，鼠标移入移出长度不固定会频繁闪动

### ISSUE THREAD

**Issue by njt1340953658** [element-plus/element-plus#12381]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: ` "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html)

### Steps to reproduce

input框添加clearable属性，宽度不固定，鼠标进入离开频繁闪动

### What is Expected?

清除icon固定在input框内部

### What is actually happening?

频繁删掉输入框宽度

### Additional comments

_(empty)_

**Comment by MrWeilian** [comment]
[# 7287](https://github.com/element-plus/element-plus/issues/7287)

**Comment by GuoJikun** [comment]
这个问题已经提了很久了，一直没有公认的很好的解决方案。

**Comment by tolking** [comment]
目前推荐为 Input 组件设置一个固定宽度，如果有更优雅的解决办法，欢迎在 #7287 提出
