### ISSUE TITLE
[Component] [select] select组件multiple为true时prefix插槽会被遮住

### ISSUE THREAD

**Issue by Jylzl** [element-plus/element-plus#12386]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome 111.0.5563.147 / windows 11`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG5cbmNvbnN0IGhhbmRsZU9wZW4gPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKDEyKTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyB2YWx1ZSB9fTwvaDE+XG4gIDxlbC1zZWxlY3RcbiAgICBzdHlsZT1cIndpZHRoOiAxMDAlXCJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIG11bHRpcGxlXG4gID5cbiAgICA8dGVtcGxhdGUgI3ByZWZpeD5cbiAgICAgIDxkaXYgQGNsaWNrPVwiaGFuZGxlT3BlblwiPlxuICAgICAgICDngrnmiJFcbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLW9wdGlvbiBsYWJlbD1cIjFcIiB2YWx1ZT1cIjFcIj48L2VsLW9wdGlvbj5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiMlwiIHZhbHVlPVwiMlwiPjwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-select  开启多选 multiple属性，prefix插槽 会被遮住且无法点击

### What is Expected?

开启多选 multiple属性，prefix插槽 可正常显示且可触发点击事件

### What is actually happening?

开启多选 multiple属性，prefix插槽 无法正常显示且无法触发点击事件

### Additional comments

el-select  开启多选 multiple属性，prefix插槽的点击事件失效

**Comment by Jylzl** [comment]
1.prefix插槽内的标签点击事件无法触发（原因：被遮盖住了）
2.选中值后prefix插槽被遮盖了

**Comment by Jylzl** [comment]
1.prefix插槽内的标签点击事件无法触发（原因：被遮盖住了）
2.选中值后prefix插槽被遮盖了

**Comment by MrWeilian** [comment]
#12106

**Comment by Lionad-Morotar** [comment]
目前最新版 2.3.6 仍未修复。[复现链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGNsYXNzPVwibS0yXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiBzaXplPVwibGFyZ2VcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gICAgPHRlbXBsYXRlICNwcmVmaXg+SGVsbG88L3RlbXBsYXRlPlxuICA8L2VsLXNlbGVjdD5cblxuICA8YnIgLz5cbiAgPGJyIC8+XG4gIDxiciAvPlxuICBcbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgbXVsdGlwbGU+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICAgIDx0ZW1wbGF0ZSAjcHJlZml4PkhlbGxvMjwvdGVtcGxhdGU+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)。

![image](https://github.com/element-plus/element-plus/assets/26913795/dd49dec5-8a76-47fd-8c31-25ef03d5d229)

**Comment by btea** [comment]
Fixed in version 2.3.7.
