### ISSUE TITLE
[Component] [slider] el-slider组件的 tooltip-class问题

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#12380]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.3`
- Browser / OS: `版本 110.0.5481.97（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHZlcnRpY2FsIGhlaWdodD1cIjIwMHB4XCIgcmFuZ2UgICBwbGFjZW1lbnQ9J3JpZ2h0JyB0b29sdGlwLWNsYXNzPSd0b29sdGlwMScvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDApXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbiAgLnRvb2x0aXAxe1xuICAgIGNvbG9yOiM2NEE5RkNcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

加入自定义tooltip-class没生效

### What is Expected?

tooltip-class应该生效

### What is actually happening?

tooltip-class未生效

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/230809751-d05ce967-8f6a-421a-a60b-a1350253bab3.png)
是我哪里写的不对吗

**Comment by MrWeilian** [comment]
1. 样式不要用 `css scope`，不然多了个属性选择器选不中的。
2. 增加 **`css` 权重** 覆盖原本 `dark` 的样式。
3. 参考 [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHZlcnRpY2FsIGhlaWdodD1cIjIwMHB4XCIgcmFuZ2UgICBwbGFjZW1lbnQ9J3JpZ2h0JyB0b29sdGlwLWNsYXNzPSd0b29sdGlwMScvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDApXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbjwvc3R5bGU+XG48c3R5bGU+XG4uZWwtcG9wcGVyLmlzLWRhcmsudG9vbHRpcDF7XG4gIGNvbG9yOiAjNjRBOUZDO1xufSAgXG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

希望能帮到你
