### ISSUE TITLE
[Component] [tabs]  TypeError: n.flatMap is not a function

### ISSUE THREAD

**Issue by zhhbinn** [element-plus/element-plus#12404]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.26`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.98 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0YWJMaXN0ID0gcmVmKFt7XG4gIGxhYmVsOlwi5rWL6K+V5LiAXCIsXG4gIG5hbWU6XCIxXCJcbn0se1xuICBsYWJlbDpcIua1i+ivleS6jFwiLFxuICBuYW1lOlwiMlwiXG59XSlcbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoXCIxXCIpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgICAgIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgdHlwZT1cImJvcmRlci1jYXJkXCI+XG4gICAgICAgIDxlbC10YWItcGFuZSB2LWZvcj1cIihpLCBpZHgpIGluIHRhYkxpc3RcIiA6a2V5PVwiaWR4XCIgOmxhYmVsPVwiaS5sYWJlbFwiIDpuYW1lPVwiaS5uYW1lXCI+IDwvZWwtdGFiLXBhbmU+XG4gICAgICAgXG4gICAgICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

根据错误日志，发现较低版本的浏览器会报`TypeError: n.flatMap is not a function`，目前看到的报错版本有69和83。根据sourcemap回溯，发现为`node_modules/element-plus/node_modules/@vueuse/core/index.mjs`的125行左右的`...events.flatMap`报错。

### What is Expected?

不再报错

### What is actually happening?

`TypeError: n.flatMap is not a function`

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
If the problem occurs only on these two versions of the browser, you can consider adding the corresponding polyfill to solve this problem.

**Comment by btea** [comment]
You can refer to this [link](https://github.com/vueuse/vueuse/issues/2642).
