### ISSUE TITLE
[Build] webpack配置，自动导入导致编译Compiled两次

### ISSUE THREAD

**Issue by jean-Val-jean-j** [element-plus/element-plus#12409]
Bug Type: **`Build`**

## Environment
![QQ截图20230412114353](https://user-images.githubusercontent.com/60576215/231343720-5cc6873a-84e7-4c55-b08f-05410e45ce3b.png)

- Vue Version: `3.2.23`
- Element Plus Version: `2.2.14`
- Browser / OS: `Google 107.0.5304.107`
- Build Tool: `Webpack`

### Related Component

- `N/A`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)

### Steps to reproduce

项目中只要按需引入就会出现编译两次，注释掉就不出现了

### What is Expected?

编译一次就行

### What is actually happening?

编译两次

### Additional comments

其他同事的电脑也出现这个问题，目前功能正常使用。如有其他问题需要解决，可跳过此问题，此问题对项目并没有多大影响

**Comment by chenxch** [comment]
插件问题建议优先反馈到插件对应的仓库
