### ISSUE TITLE
 Taking too long to install

### ISSUE THREAD

**Issue by apuatcfbd** [element-plus/element-plus#12400]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Linux`
- Build Tool: `Vue CLI`

### Related Component

- `N/A`

### Reproduction Link

[Link](http://NOT-APPLICABLE-IN-THIS-CASE)

### Steps to reproduce

1. USE PACKAGE JSON
"dependencies": {
    "@animxyz/vue3": "^0.6.7",
    "@casl/ability": "^6.3.3",
    "@casl/vue": "^2.2.1",
    "@fullcalendar/core": "^6.1.4",
    "@fullcalendar/daygrid": "^6.1.4",
    "@fullcalendar/interaction": "^6.1.4",
    "@fullcalendar/timegrid": "^6.1.4",
    "@fullcalendar/vue3": "^6.1.4",
    "@tkmam1x/vue3-treeselect": "^0.1.15",
    "@vuelidate/core": "^2.0.0",
    "@vuelidate/validators": "^2.0.0",
    "@vuepic/vue-datepicker": "^3.6.3",
    "axios": "^1.3.4",
    "bootstrap": "^5.1.3",
    "collect.js": "^4.34.3",
    "core-js": "^3.26.1",
    "element-plus": "2.2.27",
    "izitoast": "^1.4.0",
    "laravel-echo": "^1.14.2",
    "lodash": "^4.17.21",
    "luxon": "^2.4.0",
    "mobile-device-detect": "^0.4.3",
    "nprogress": "^0.2.0",
    "primeicons": "^6.0.1",
    "primevue": "^3.21.0",
    "pusher-js": "^8.0.0",
    "sweetalert2": "^11.6.16",
    "v-calendar": "^3.0.0-alpha.8",
    "vue": "^3.2.45",
    "vue-plyr": "^7.0.0",
    "vue-router": "^4.1.6",
    "vue-router-multiguard": "^1.0.3",
    "vue3-date-time-picker": "^2.8.3",
    "vue3-popper": "^1.5.0",
    "vue3-timepicker": "^1.0.0-beta.2",
    "vuex": "^4.1.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-vuex": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/compiler-sfc": "^3.2.45",
    "@vue/eslint-config-standard": "^8.0.1",
    "eslint": "^8.30.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-standard": "^5.0.0",
    "eslint-plugin-vue": "^9.8.0",
    "sass": "^1.57.1",
    "sass-loader": "^13.2.0"
  }

2. CHECKOUT THAT ONLY element-plus is taking time.

### What is Expected?

Faster install, A react project of this size takes 1 quarter to install it deps. so does vue without element plus.

### What is actually happening?

when installing deps using `npm i` the element-plus package takes too long time to install.

### Additional comments

This eats up server build time & potentially increases the cost of CICD server.

**Comment by chenxch** [comment]
If the installation time is too long, please check your network conditions or replace the npm source. For server construction issues, please consider using node_cache.

**Comment by apuatcfbd** [comment]
> If the installation time is too long, please check your network conditions or replace the npm source. For server construction issues, please consider using node_cache.

I've several projects on my machine, only this project takes time & more specifically this package takes time. I've checked it's not using the network when it takes time. I'm fully sure this issue has nothing to do with the network. So caching is not a solution too.

**Comment by truc0** [comment]
It does take a long time for `npm i` command for installing all packages.

However, I've tried to install other package first before installing `element-plus`, the result is as following.

```
time npm i
# omit warning and info related to npm audit
# npm i --no-cache  75.17s user 8.39s system 37% cpu 3:44.24 total

time npm i element-plus
# omit warning and info related to npm audit
# npm i element-plus@2.2.27  4.92s user 0.56s system 98% cpu 5.562 total
```

It seems that npm spend most of the time dealing with other packages, the installation of `element-plus` package actually takes little time.

**Comment by apudiu** [comment]
@truc0 it doesn't matter fo what time it takes, the fact is for other packages it's fast. 
Why are you guys taking this issue lightly? & you're telling facts so simple that almost everybody knows this. 
Check out this [screenshot ](https://prnt.sc/fmhGx35VGk22) this is where it takes time. This doesn't happen with any other package (I mean doesn't takes that much time). It's very weird.

& say what you've to say after checking this [screenshot ](https://prnt.sc/8kOzycO_EdEK)(left one is with `element-plus`)

**Comment by sxzz** [comment]
https://bundlephobia.com/package/element-plus@2.3.3
Your deps are too much. It's not the fault of Element Plus. Element Plus (only Element Plus) is expected to be downloaded in 397ms. There are lots of dep in your project that are larger than Element Plus, like `sass` (2.5MB).

Check your network and try a faster package manager (Yarn or pnpm)

**Comment by apudiu** [comment]
Good point, could you please tell me if I've lots of packages then why
other package doesn't take time (refer to 1st screenshot) but only element
plus?
Also what if my packages gets install lots faster if I remove element plus?

You're talking about network. I think you should get clear understanding of
my network if you've checked 2nd screenshot, specifically right side.

Thanks

**Comment by apuatcfbd** [comment]
Same project in my local machine
```
time npm I

real    4m2.532s
user    1m10.421s
sys     0m10.171s
```
After removing `element-plus`
```
real    0m33.842s
user    0m45.133s
sys     0m8.290s
```
You have the proof. Please don't try to defend a fault rather than try to fix it.
