### ISSUE TITLE
[Component] [button] 按钮默认的line-height是1显示中文内容偏上，不知道这是故意这样做的吗，大写英文字母也会偏上，line-height改为1.5就正常了，如果是故意这样做的话，有地方可以全局修改这个line-height吗

### ISSUE THREAD

**Issue by crazy-max-js** [element-plus/element-plus#12410]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

所有用到的地方都这样

### What is Expected?

文字可以垂直居中

### What is actually happening?

中文和大写英文字母文字偏上

### Additional comments

_(empty)_

**Comment by cvpv** [comment]
这和字体和浏览器有关

**Comment by crazy-max-js** [comment]
> 这和字体和浏览器有关

字体是默认字体，浏览器是google最新版 问题会出在这里面吗

**Comment by crazy-max-js** [comment]
补充一下 设置line-height为1.5效果不明显，把line-height设置为normal后是正好垂直居中的，也就是说el-button源码中设置的line-height去掉是正合适的，不知道是不是因为flex影响导致line-height 1偏上的问题

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/231708652-cdd0c4c3-c8c6-45cb-8c5b-d213098596c0.png)

方便提供一下截图看看效果么？

**Comment by crazy-max-js** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/231708652-cdd0c4c3-c8c6-45cb-8c5b-d213098596c0.png)
> 
> 方便提供一下截图看看效果么？
![image](https://user-images.githubusercontent.com/27037918/231710198-de32bfef-ab9f-49cd-8e29-968ff51bd7c9.png)
![image](https://user-images.githubusercontent.com/27037918/231710240-13cf8598-8a19-45e1-8ad1-3d464e8a1cc6.png)

难道只有我有这个问题吗

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/231710693-1a5f5dc2-b4ae-47d3-b36d-0b1784f1e904.png)

是不是系统字体不是100%

**Comment by crazy-max-js** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/231710693-1a5f5dc2-b4ae-47d3-b36d-0b1784f1e904.png)
> 
> 是不是系统字体不是100%
是指这里吗，这里一直是100%
![image](https://user-images.githubusercontent.com/27037918/231711395-ea656a89-7891-4a4c-aac4-5db8d9239204.png)

**Comment by chenxch** [comment]
浏览器有缩放么？

**Comment by crazy-max-js** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/231710693-1a5f5dc2-b4ae-47d3-b36d-0b1784f1e904.png)
> 
> 是不是系统字体不是100%

我找到了，确实是系统字体问题，修改为100%就好了，感谢

**Comment by chenxch** [comment]
好的，那我关闭这个issue了哈

**Comment by crazy-max-js** [comment]
> 浏览器有缩放么？

是不是可以考虑把line-height属性去掉，是留着有什么作用吗

**Comment by chenxch** [comment]
line-height: 1 的作用是将文本行高设置为其字体大小的一倍。这样可以使文本在行与行之间的间距最小化，从而使文本更加紧凑。此外，line-height: 1 还可以提高文本的可读性，因为它可以使文本更容易阅读和理解。
