### ISSUE TITLE
[Component] [upload] upload组件，在自定义http-request情况下，onSuccess函数只触发一次，导致最多只有一个文件能获取到上传后的状态

### ISSUE THREAD

**Issue by tianleiyiji123** [element-plus/element-plus#12427]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `macOS`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgZHJhZ1xuICAgIG11bHRpcGxlXG4gICAgOm9uU3VjY2Vzcz1cIm9uU3VjY2Vzc1wiXG4gICAgOmh0dHAtcmVxdWVzdD1cImh0dHBSZXF1ZXN0XCJcbiAgPlxuICAgIDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tdXBsb2FkXCI+PHVwbG9hZC1maWxsZWQgLz48L2VsLWljb24+XG4gICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGV4dFwiPlxuICAgICAgRHJvcCBmaWxlIGhlcmUgb3IgPGVtPmNsaWNrIHRvIHVwbG9hZDwvZW0+XG4gICAgPC9kaXY+XG4gICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwa2JcbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdXBsb2FkPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IFVwbG9hZEZpbGxlZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBjb25zdCBvblN1Y2Nlc3MgPSAoZSwgdXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgICAvLyDlnKjmiJDlip/lm57osIPlj6rkvJrmiafooYznrKzkuIDmrKHmiJDlip/nmoQo5Y+q5Lya5omn6KGM5LiA5qyhKVxuICAgIC8vIOaJgOS7pXVwbG9hZEZpbGVz6YeM6Z2i5LiN5Lya5rOo5YWl5Lik5Liq5paH5Lu255qE6L+U5Zue5pWw5o2uXG4gICAgY29uc29sZS5sb2codXBsb2FkRmlsZXMpXG4gIH1cbiAgY29uc3QgaHR0cFJlcXVlc3QgPSAoKSA9PiB7XG4gICAgLy8g6L+Z6YeM5aaC5p6c5oiR5LiK5Lyg5Lik5Liq5Lul5LiK55qE5paH5Lu2XG4gICAgLy8g6L+Z6YeM5Lya5omn6KGM5Lik5qyhXG4gICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZSh7fSlcbiAgfVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```
<template>
  <el-upload
    class="upload-demo"
    drag
    multiple
    :onSuccess="onSuccess"
    :http-request="httpRequest"
  >
    <el-icon class="el-icon--upload"><upload-filled /></el-icon>
    <div class="el-upload__text">
      Drop file here or <em>click to upload</em>
    </div>
    <template #tip>
      <div class="el-upload__tip">
        jpg/png files with a size less than 500kb
      </div>
    </template>
  </el-upload>
</template>

<script setup lang="ts">
import { UploadFilled } from '@element-plus/icons-vue'
  const onSuccess = (e, uploadFile, uploadFiles) => {
    // 在成功回调只会执行第一次成功的(只会执行一次)
    // 所以uploadFiles里面不会注入两个文件的返回数据
    console.log(uploadFiles)
  }
  const httpRequest = () => {
    // 这里如果我上传两个以上的文件
    // 这里会执行两次
    return Promise.resolve({})
  }
</script>
```

### What is Expected?

在onSuccess 里面能执行两次，能拿到两个自定义上传文件的返回值

### What is actually happening?

实际却是onSuccess只执行了一次，导致第二个文件，处于upload loading状态

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/d9a03d44eacf42449aaaf7cd77a3701b~tplv-k3u1fbpfcp-watermark.image?)

@tianleiyiji123 有没有什么地方不对

**Comment by HeftyKoo** [comment]
@tianleiyiji123 我试了一下，使用 2.3.3 版本和最新版本 2.3.9 都没有重现你所说的问题。issue 我先关了，如果后续再出现类似的问题，欢迎提供更详细的复现步骤和继续提issue。
