### ISSUE TITLE
[Build] [select] el-select组件报包后change事件失效

### ISSUE THREAD

**Issue by 303036710** [element-plus/element-plus#12421]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `windows`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

无

### What is Expected?

无

### What is actually happening?

无

### Additional comments

 <el-select  v-model="form.projectId" @change="changeProjectId">
 在开发工具中，change事件正常，通过npm run build 打包后的代码，change事件不生效
 当前使用的版本element-plus: 2.2.8, vue: 3.2.37,@element-plus/icons-vue：2.0.6
 麻烦排查一下，我的WX:hekf520

**Comment by btea** [comment]
你能提供一个最小的复现链接或者仓库地址吗？

**Comment by 303036710** [comment]
可以哈，我整理好了，邮件发送给你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 晚上6:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Build] [select] el-select组件报包后change事件失效 (Issue #12421)





 
你能提供一个最小的复现链接或者仓库地址吗？

**Comment by chenxch** [comment]
@303036710 最好使用github或者stackblitz、codesandbox提供复现demo

**Comment by 303036710** [comment]
问题已解决，找到原因了，谢谢，麻烦把github上的问题关闭吧，原因如下
这是一个二级联动的两个下拉列表，getProjectIdList()对应的下拉列表选中变化了，联动更新getModelIdList()这个方法的下拉列表的数组值
在setup中，getProjectIdList（）和getModelIdList()方法初始化的顺序问题，但为啥子要延迟200ms初始化两个方法，问题就解决，你们可以排查一下，原因可以告诉我，或者在新版本中修复掉吧
1、有问题的代码
/**projectId下拉列表改变事件*/
const changeProjectId =(val)=&gt;{
    proxy.param.projectId=val;
    proxy.form.modelId='';
    getModelIdList();
}
/**初始化操作*/
setTimeout(()=&gt;{
    proxy.form=props.rowData;
    
},200);getModelIdList();
getProjectIdList();
2、修改getModelIdList()和getProjectIdList（）这两个方法的位置，延迟加载200ms，问题就解决了


/**projectId下拉列表改变事件*/
const changeProjectId =(val)=&gt;{
    proxy.param.projectId=val;
    proxy.form.modelId='';
    getModelIdList();
}
/**初始化操作*/
setTimeout(()=&gt;{
    proxy.form=props.rowData;
    getModelIdList();
    getProjectIdList();
},200);


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 中午1:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Build] [select] el-select组件报包后change事件失效 (Issue #12421)





 
@303036710 最好使用github或者stackblitz、codesandbox提供复现demo
