### ISSUE TITLE
[Docs] [All] 辛苦优化下官网

### ISSUE THREAD

**Issue by Eviwang** [element-plus/element-plus#12430]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.0-alpha.9`
- Element Plus Version: `2.3.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html#%E5%B8%A6%E8%BE%B9%E6%A1%86%E8%A1%A8%E6%A0%BC)

### Steps to reproduce

经常性报错啊，卡顿

### What is Expected?

期望正常打开

### What is actually happening?

卡顿，报错

### Additional comments

_(empty)_

**Comment by gyt95** [comment]
只能说习惯就好...

**Comment by yj-liuzepeng** [comment]
哈哈哈

**Comment by wangcch** [comment]
还是建议使用 https://element-plus.org/ ，不要使用 gitee.io

**Comment by chenxch** [comment]
建议优先访问
https://element-plus.org
或者
https://cn.element-plus.org
