### ISSUE TITLE
[Component] [menu] el-menu ellipsis 超出隐藏失败BUG

### ISSUE THREAD

**Issue by shiwanmenghuxiahuashan** [element-plus/element-plus#12434]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-alpha.9`
- Element Plus Version: `2.3.3`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtbWVudVxuICAgIDpkZWZhdWx0LWFjdGl2ZT1cImFjdGl2ZUluZGV4XCJcbiAgICBjbGFzcz1cImVsLW1lbnUtZGVtb1wiXG4gICAgbW9kZT1cImhvcml6b250YWxcIlxuICAgIEBzZWxlY3Q9XCJoYW5kbGVTZWxlY3RcIlxuICA+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjFcIj5Qcm9jZXNzaW5nIENlbnRlcjwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+V29ya3NwYWNlPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMi00XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDwhLS0gaSdtIGNvbW1lbnQgLS0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjNcIiBkaXNhYmxlZD5JbmZvPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj40LWl0ZW08L2VsLW1lbnUtaXRlbT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNVwiPjUtaXRlbTwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI2XCI+Ni1pdGVtPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjdcIj43LWl0ZW08L2VsLW1lbnUtaXRlbT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiOFwiPjgtaXRlbTwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI5XCI+OS1pdGVtPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEwXCI+MTAtaXRlbTwvZWwtbWVudS1pdGVtPlxuICA8L2VsLW1lbnU+IFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYWN0aXZlSW5kZXggPSByZWYoJzEnKVxuY29uc3QgYWN0aXZlSW5kZXgyID0gcmVmKCcxJylcbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在 el-menu 子元素中存在 注释节点将导致计算item 位置失效，从而导致超出隐藏失败，原因时只判断 item.nodeName !== '#text' 文本，没判断是否存在注释，移除注释后即可正常使用

### What is Expected?

超出隐藏可以正常使用

### What is actually happening?

因添加注释导致超出隐藏不可用

### Additional comments

代码位置 https://github.com/element-plus/element-plus/blob/dev/packages/components/menu/src/menu.ts
```js
 const calcSliceIndex = () => {

      if (!menu.value) return -1
// item.nodeName !== '#text'  只判断了文本节点，注释节点未判断
      const items = Array.from(menu.value?.childNodes ?? []).filter(
        (item) => item.nodeName !== '#text' || item.nodeValue
      ) as HTMLElement[]
      const moreItemWidth = 64
      const paddingLeft = Number.parseInt(
        getComputedStyle(menu.value!).paddingLeft,
        10
      )
      const paddingRight = Number.parseInt(
        getComputedStyle(menu.value!).paddingRight,
        10
      )
      const menuWidth = menu.value!.clientWidth - paddingLeft - paddingRight
      let calcWidth = 0
      let sliceIndex = 0
      items.forEach((item, index) => {
        calcWidth += item.offsetWidth || 0
        if (calcWidth <= menuWidth - moreItemWidth) {
          sliceIndex = index + 1
        }
      })
// 数量对不上返回 -1 从而导致未触发 超出隐藏的判断
      return sliceIndex === items.length ? -1 : sliceIndex
    }
```

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/231951484-15575a65-8ca4-438b-95af-d74e706f5b25.png)

@shiwanmenghuxiahuashan 从你提供的repo来看，省略功能是正常的，如果是repo错误请提供正确可复现的repo。

**Comment by shiwanmenghuxiahuashan** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/231951484-15575a65-8ca4-438b-95af-d74e706f5b25.png)
> 
> @shiwanmenghuxiahuashan 从你提供的repo来看，省略功能是正常的，如果是repo错误请提供正确可复现的repo。


 以下是我封装的的 menu 其中引用了一个 subMenu
```vue

<template>
  <div style="width: 50%">
    <el-menu v-if="routeList" :unique-opened="true" :mode="'horizontal'" router>
      <SubMenu v-for="item in routeList" :key="item.id" :item="item" />
    </el-menu>
  </div>
</template>
<script>
import { defineComponent } from 'vue'
import SubMenu from './SubMenu'
export default defineComponent({
  name: 'Menu',
  components: { SubMenu },
  setup() {
    const routeList = [
      {
        path: '/test',
        meta: {
          label: '嵌套测试Root'
        },
        redirect: '/test/sales',
        children: [
          {
            path: 'sales',
            meta: {
              label: '销量测试'
            }
          },
          {
            path: 'hot',
            meta: {
              label: '热度测试'
            },
            children: [
              {
                path: 'test1',
                meta: {
                  label: '测试1'
                }
              },
              {
                path: 'test2',
                meta: {
                  label: '测试2'
                }
              },
              {
                path: 'test3',
                meta: {
                  label: '测试3'
                }
              }
            ]
          },
          {
            path: 'competitive',
            meta: {
              label: '竞争关系'
            }
          },
          {
            path: 'price',
            meta: {
              label: '价格'
            }
          },
          {
            path: 'paramconfig',
            meta: {
              label: '参数配置'
            }
          },
          {
            path: 'profile',
            meta: {
              label: '形象认知'
            }
          },
          {
            path: 'channel',
            meta: {
              label: '渠道'
            }
          },
          {
            path: 'prospect',
            meta: {
              label: '潜在客户'
            }
          }
        ]
      },
      {
        path: '/switch',
        meta: {
          label: 'switchPage'
        }
      },
      {
        path: '/about',
        meta: {
          label: '关于'
        }
      },
      {
        path: '/apiTest',
        meta: {
          label: 'api测试'
        }
      },
      {
        path: 'test3-1',
        meta: {
          label: '测试3-1'
        }
      },
      {
        path: 'test3-2',
        meta: {
          label: '测试3-2'
        }
      }
    ]
    return {
      routeList
    }
  }
})
</script>


```

submenu 中我添加了 注释
```vue
<template>
  <!-- 我是注释 -->
  <el-sub-menu v-if="item.children" :index="item.path">
    <template #title>
      <span>{{ item.meta.label }}</span>
    </template>
    <template v-for="child in item.children" :key="child.id">
      <SubMenu v-if="child.children" :item="child" />
      <el-menu-item v-else :index="item.path">
        {{ item.meta.label }}
      </el-menu-item>
    </template>
  </el-sub-menu>
  <el-menu-item v-else :index="item.path">
    {{ item.meta.label }}
  </el-menu-item>
</template>
<script>
import { defineComponent } from 'vue'
import SubMenu from './SubMenu'
export default defineComponent({
  name: 'SubMenu',
  components: { SubMenu },
  props: {
    item: {
      type: Object,
      required: true
    }
  }
})
</script>

```
分别输出了 sliceIndex items 
![image](https://user-images.githubusercontent.com/21036598/231987259-52f13ea9-605f-47e5-81dd-f77ea5c49cf9.png)

![1e4e97cd7ec13681e412051398f17dc](https://user-images.githubusercontent.com/21036598/231986934-7ecf40d5-268f-47fb-b25d-b27f77ba7acd.png)

可以在截图中看到输出items 与 sliceIndex  数量，不一致，我不确定是否是这影响的

**Comment by shiwanmenghuxiahuashan** [comment]
感谢大佬
