### ISSUE TITLE
[Component] [form-item, select] Using form components within ElFormItem slot in ElForm, enable the filterable property when using ElSelect. Clicking on the form label selection box always focuses and expands the options.

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#12433]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.3.3`
- Browser / OS: `macOS lasted / chrome  lasted`
- Build Tool: `Vite`

### Related Component

- `el-form-item`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCIgbGFiZWwtd2lkdGg9XCIxODBweFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJjbGljayBtZSBjaGFuZ2Ugc3RhdHVzXCI+XG4gICAgIDxlbC1zd2l0Y2ggdi1tb2RlbD1cImZvcm0uZGVsaXZlcnlcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY2xpY2sgbWUgZm9jdXNcIj5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cInBsZWFzZSBzZWxlY3QgeW91ciB6b25lXCI+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIG9uZVwiIHZhbHVlPVwic2hhbmdoYWlcIiAvPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSB0d29cIiB2YWx1ZT1cImJlaWppbmdcIiAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuLy8gZG8gbm90IHVzZSBzYW1lIG5hbWUgd2l0aCByZWZcbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7XG4gIGRlbGl2ZXJ5OiBmYWxzZSxcbiAgcmVnaW9uOiAnJyxcbn0pXG5cbmNvbnN0IG9uU3VibWl0ID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnc3VibWl0IScpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

See demo for Reproduction Link

### What is Expected?

Clicking on the form label does not trigger input box focus or toggle switch state.

### What is actually happening?

Clicking on the form label selection box always focuses and expands the options.

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/issues/9752
Please search the question before asking, maybe you can solve your problem quickly.
