### ISSUE TITLE
[Bug Report] Carousel don't update the indicator and items when data change

### ISSUE THREAD

**Issue by Hansuku** [element-plus/element-plus#1243]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
OSX BigSur 11.1 / Chrome 

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/hansuku/pen/mdrjLrN

### Steps to reproduce
click the add button, then click the reduce button

### What is Expected?
The number of dom elements "el-carousel__item" and "el-carousel__indicator" match

### What is actually happening?
The number of dom elements "el-carousel__item" and "el-carousel__indicator" isn't match

**Comment by Ryan2128** [comment]
Sorry to close this PR because @BeADre 's PR is earlier than your PR.

You are still welcome to open new issues and new PRs about other errors.

Thanks for your issue and help.
