### ISSUE TITLE
[Component] [sub-menu, table] Chrome/73.0.3683.7 以下版本界面显示问题

### ISSUE THREAD

**Issue by chaodiangen** [element-plus/element-plus#12440]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36"`
- Build Tool: `Vite`

### Related Component

- `el-sub-menu`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuXG5jb25zdCBhY3RpdmVJbmRleCA9IHJlZignMScpXG5jb25zdCBoYW5kbGVTZWxlY3QgPSAoa2V5OiBzdHJpbmcsIGtleVBhdGg6IHN0cmluZ1tdKSA9PiB7XG4gIGNvbnNvbGUubG9nKGtleSwga2V5UGF0aClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtbWVudVxuICAgIDpkZWZhdWx0LWFjdGl2ZT1cImFjdGl2ZUluZGV4XCJcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gID5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMVwiPlByb2Nlc3NpbmcgQ2VudGVyPC9lbC1tZW51LWl0ZW0+XG4gICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIyXCI+PC9lbC1zdWItbWVudT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiM1wiPkluZm88L2VsLW1lbnUtaXRlbT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNFwiPk9yZGVyczwvZWwtbWVudS1pdGVtPlxuICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

菜单栏 有时候能出来一个 有时候一个也不出来，表格也是，

### What is Expected?

提供解决问题

### What is actually happening?

给出回复

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/95576775/231969769-fbc7907f-7977-4461-b757-a9c68ef6960b.png)
![image](https://user-images.githubusercontent.com/95576775/231969820-59de21b9-50ad-496f-b171-11a991eee728.png)

**Comment by chenxch** [comment]
Is there any error message in the console?
