### ISSUE TITLE
[Component] [loading] 为什么我的 另一个老的github 账号无法提交, pr 也无法评论，是拉黑了么

### ISSUE THREAD

**Issue by pan2-2** [element-plus/element-plus#12443]
Bug Type: **`Component`**

**我的 另一个老的github 账号无法提交, pr 也无法评论，是拉黑了么**
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/130739557/231974324-74c441ca-140c-4678-a834-df13e53f71c2.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/130739557/231974610-79d8f7e6-2161-49d0-a7e7-f7c79765fbf0.png">

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6ekluZGV4PVwiOTk5OTk5OVwiPiBcbiAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib3BlbkZ1bGxTY3JlZW4yXCI+IFx0XHRcdOeCueWHu+WQr+WKqOWQjmVsLWxvYWRpbmctbWFza+eahCB6LWluZGV4IOi/mOaYryAyMDA077yM5LiN5LyaIDk5OTk5OTlcbiAgICA8L2VsLWJ1dHRvbj5cbiAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICBcbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxMb2FkaW5nIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5cblxuY29uc3Qgb3BlbkZ1bGxTY3JlZW4yID0gKCkgPT4ge1xuICBjb25zdCBsb2FkaW5nID0gRWxMb2FkaW5nLnNlcnZpY2Uoe1xuICAgIGxvY2s6IHRydWUsXG4gICAgdGV4dDogJ0xvYWRpbmcnLFxuICAgIGJhY2tncm91bmQ6ICdyZ2JhKDAsIDAsIDAsIDAuNyknLFxuICB9KVxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBsb2FkaW5nLmNsb3NlKClcbiAgfSwgMjAwMDApXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击代码即可复现，审核元素，就可以看到

```vue
<template>
  <el-config-provider :zIndex="9999999"> 
  	<el-button type="primary" @click="openFullScreen2"> 			点击启动后el-loading-mask的 z-index 还是 2004，不会 9999999
    </el-button>
   </el-config-provider>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { ElLoading } from 'element-plus'

const openFullScreen2 = () => {
  const loading = ElLoading.service({
    lock: true,
    text: 'Loading',
    background: 'rgba(0, 0, 0, 0.7)',
  })
  setTimeout(() => {
    loading.close()
  }, 20000)
}
</script>

```

### What is Expected?

z-index 需要全局，能根据传入的全局配置 ，会自动+1，因为有些弹出层上面，需要再次 loading

### What is actually happening?

总是 从 2000 开始

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
@pan2-2 非常抱歉，我们注意到您的账户被封禁了。我们发现您在其他仓库发布了一些不符合规范的issue，这可能会对其他用户造成困扰。我们希望您能够遵守我们的issue规范，以确保所有用户都能够愉快地使用我们的平台。如果您有任何疑问或需要帮助，请随时联系我们的支持团队。谢谢您的理解和合作。

**Comment by chenxch** [comment]
@pan2-2 请修改正确格式标题以及内容，删除无效内容后将会重新激活该issue。
