### ISSUE TITLE
[Bug Report] dialog inside click move to the outside will close

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1248]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/vgbire/pen/gOwdYLm

### Steps to reproduce
The pop-up example on the official website has this problem

### What is Expected?
When you click inside the pop-up window and release outside the pop-up window, it should not be closed. When you click inside the mask and release inside the pop-up window, it should not be closed

### What is actually happening?
In both cases, they shut down.The drawer has the same problem

**Comment by JeremyWuuuuu** [comment]
I believe this is duplicated with #1228. Closing it.
