### ISSUE TITLE
[Feature Request] offer tags and attributes completions with vetur

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#1251]
### Existing Component
Yes

### Component Name
-

### Description
`elment-ui` work with [element-helper-json](https://github.com/ElementUI/element-helper-json) (bundles in vetur), but `element-plus` maybe not suitable.

Maybe it should be adapted. eg: [component-data](https://vuejs.github.io/vetur/guide/component-data.html#adding-a-framework).

**Comment by zazzaz** [comment]
this will be a nice enhancement

**Comment by tolking** [comment]
I'd like to do this if I could

**Comment by zazzaz** [comment]
@tolking That would be great! I'll assign it to you then.

**Comment by JeremyWuuuuu** [comment]
What about supporting this?
![image](https://user-images.githubusercontent.com/15975785/104152298-1dc0f580-541a-11eb-8987-86e98d84463c.png)

**Comment by tolking** [comment]
I don't know this, But it looks like [element-helper-json](https://github.com/ElementUI/element-helper-json).

input

```vue
<el-time-picker picker-opt />
```

tip -> picker-options (picker-options is delete in element-plus)

**Comment by zazzaz** [comment]
We can support these plugins one by one, it should be the same, just offering the listed tags and attributes.

**Comment by tolking** [comment]
I will revise it according to the document and package
