### ISSUE TITLE
[TypeScript] [All] 所有element plus组件在vscode中template标签中都提示红线报错

### ISSUE THREAD

**Issue by zhangjinzhangjin** [element-plus/element-plus#12529]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.3`
- Browser / OS: `chrome 111.0.5563.147        win 10 64bit`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

不知道是volar的问题还是编译器的问题，现在所有的element plus组件在template中提示ts错误。实际项目支行正常，无警告无报错。
错误提示如下：
类型“{ type: "warning"; }”的参数不能赋给类型“App<any> & Record<string, unknown> & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "default" | "text" | "success" | "warning" | "info" | "primary" | "danger", unknown>; ... 12 more ...; readonly autofocus: boolean; }> & Omit<...>”的参数。
  类型“{ type: "warning"; }”缺少类型“App<any>”的以下属性: version, config, use, mixin 及其他 11 项。ts(2345)

### What is Expected?

vscode无报错

### What is actually happening?

vscode中element组件红线报错

### Additional comments

只要是写在template标签中的element组件，全部都报这个错误。虽然不影响项目正常支行，但编辑器一大堆的红线很难受，希望可以提供一个解决方案，谢谢~

![image](https://user-images.githubusercontent.com/42567006/233525530-495247ff-b891-4353-99e1-6b294f24495e.png)
![image](https://user-images.githubusercontent.com/42567006/233525590-653edaa4-77e4-4375-b67d-87a85c10d15e.png)

**Comment by zhuxiaoweb** [comment]
+1

**Comment by zhuxiaoweb** [comment]
今天升级了vite就这样了

**Comment by zhuxiaoweb** [comment]
类型“{ class: string; arrow: "never"; direction: "horizontal" | "vertical"; }”的参数不能赋给类型“App<any> & Record<string, unknown> & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "card", unknown>; readonly height: string; ... 8 more ...; readonly pauseOnHover: EpPropMergeType<...>; }> & Omit<...>”的参数。
  类型“{ class: string; arrow: "never"; direction: "horizontal" | "vertical"; }”缺少类型“App<any>”的以下属性: version, config, use, mixin 及其他 11 项。ts(2345)
(property) ElCarousel: SFCWithInstall<DefineComponent<{
    readonly initialIndex: EpPropFinalized<NumberConstructor, unknown, unknown, 0, boolean>;
    readonly height: EpPropFinalized<StringConstructor, unknown, unknown, "", boolean>;
    ... 8 more ...;
    readonly pauseOnHover: EpPropFinalized<...>;
}, ... 10 more ..., {

**Comment by zhangjinzhangjin** [comment]
我是什么都没升级，昨天还好好的。感觉有可能是volar的问题，但是降级了volar的版本还是同样的报错。希望有大神能给个解决方案吧。虽然不影响项目支行，但是满编辑器的红线太难受了

**Comment by zhangjinzhangjin** [comment]
> 类型“{ class: string; arrow: "never"; direction: "horizontal" | "vertical"; }”的参数不能赋给类型“App & Record<string, unknown> & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "card", unknown>; readonly height: string; ... 8 more ...; readonly pauseOnHover: EpPropMergeType<...>; }> & Omit<...>”的参数。 类型“{ class: string; arrow: "never"; direction: "horizontal" | "vertical"; }”缺少类型“App”的以下属性: version, config, use, mixin 及其他 11 项。ts(2345) (property) ElCarousel: SFCWithInstall<DefineComponent<{ readonly initialIndex: EpPropFinalized<NumberConstructor, unknown, unknown, 0, boolean>; readonly height: EpPropFinalized<StringConstructor, unknown, unknown, "", boolean>; ... 8 more ...; readonly pauseOnHover: EpPropFinalized<...>; }, ... 10 more ..., {

我们这妥妥的同一个问题~~T_T

**Comment by simmongod** [comment]
> 我是什么都没升级，昨天还好好的。感觉有可能是volar的问题，但是降级了volar的版本还是同样的报错。希望有大神能给个解决方案吧。虽然不影响项目运行，但是满编辑器的红线太难受了

同

**Comment by warmthsea** [comment]
![149f1c143438bb849fef8c042e45175](https://user-images.githubusercontent.com/45450994/233526926-c04802f4-2980-401c-afe2-bed3c82310fa.png)
me to

**Comment by warmthsea** [comment]
+1

**Comment by zhuxiaoweb** [comment]
我现在项目已经没法打包了..

**Comment by warmthsea** [comment]
> ![149f1c143438bb849fef8c042e45175](https://user-images.githubusercontent.com/45450994/233526926-c04802f4-2980-401c-afe2-bed3c82310fa.png) me to
> 
> I tried various dependency reloads, but couldn't solve them
> 
> https://github.com/warmthsea/element-plus-vite-starter But no such problem occurred

显然是 vite 4.3.1  引起的相关问题

**Comment by zhuxiaoweb** [comment]
> > ![149f1c143438bb849fef8c042e45175](https://user-images.githubusercontent.com/45450994/233526926-c04802f4-2980-401c-afe2-bed3c82310fa.png) me to
> > I tried various dependency reloads, but couldn't solve them
> > https://github.com/warmthsea/element-plus-vite-starter But no such problem occurred
> 
> 显然是 vite 4.3.1 引起的相关问题

但是我降级到4.2.2还是一样报错

**Comment by StormerZSha** [comment]
+1今天什么都没有做就这样了，尝试升级了Volar到pre-release没有任何变化，Element Plus原本不是最新版本升级到2.3.3没有任何变化，vite是比较老的版本2.9.15

**Comment by warmthsea** [comment]
> > > ![149f1c143438bb849fef8c042e45175](https://user-images.githubusercontent.com/45450994/233526926-c04802f4-2980-401c-afe2-bed3c82310fa.png)我对
> > > 我尝试了各种依赖重新加载，但无法解决它们
> > > https://github.com/warmthsea/element-plus-vite-starter但是没有出现这样的问题
> > 
> > 
> > 显然是vite 4.3.1 引起的相关问题
> 
> 但是我降级到4.2.2还是一样报错



> > > ![149f1c143438bb849fef8c042e45175](https://user-images.githubusercontent.com/45450994/233526926-c04802f4-2980-401c-afe2-bed3c82310fa.png) me to
> > > I tried various dependency reloads, but couldn't solve them
> > > https://github.com/warmthsea/element-plus-vite-starter But no such problem occurred
> > 
> > 
> > 显然是 vite 4.3.1 引起的相关问题
> 
> 但是我降级到4.2.2还是一样报错

因为相关的依赖用的 是 vite@last，降到了4.2，npm run 依旧是4.3

**Comment by warmthsea** [comment]
> 因为相关的依赖用的 是 vite@last，降到了4.2，npm run 依旧是4.3

因为相关的依赖用的 是 vite@last，降到了4.2，npm run 依旧是4.3

**Comment by zhuxiaoweb** [comment]
> > 因为相关的依赖用的 是 vite@last，降到了4.2，npm run 依旧是4.3
> 
> 因为相关的依赖用的 是 vite@last，降到了4.2，npm run 依旧是4.3

是的

**Comment by zhuxiaoweb** [comment]
去vite项目提issue？

**Comment by warmthsea** [comment]
> 



> 去vite项目提issue？

主要是新项目无法复现，很难找到问题，我去提一个

**Comment by miles66jhg** [comment]
现在有什么解决办法了吗

**Comment by warmthsea** [comment]
> 现在有什么解决办法了吗

没有，正在寻找最小复现

**Comment by emojiiii** [comment]
https://github.com/pure-admin/vue-pure-admin/issues/523

**Comment by zhuxiaoweb** [comment]
> [pure-admin/vue-pure-admin#523](https://github.com/pure-admin/vue-pure-admin/issues/523)
> 
> 请尝试把 volar降到 v1.2.0

我就是1.2.0，还是不行
![image](https://user-images.githubusercontent.com/32625924/233528821-0cdf41ca-c300-4e88-9365-d30e52638736.png)

**Comment by emojiiii** [comment]
> 我就是1.2.0，还是不行 ![image](https://user-images.githubusercontent.com/32625924/233528821-0cdf41ca-c300-4e88-9365-d30e52638736.png)

reload window了吗

**Comment by zhuxiaoweb** [comment]
> > 我就是1.2.0，还是不行 ![image](https://user-images.githubusercontent.com/32625924/233528821-0cdf41ca-c300-4e88-9365-d30e52638736.png)
> 
> reload window了吗

reload过了

**Comment by chenxch** [comment]
@zhuxiaoweb 考虑过你升级过vite，是否有vue相关的包也被升级了（我刚才用了一个几个月前的demo测试了一下，只是切换volar版本就行了）

**Comment by emojiiii** [comment]
https://github.com/vuejs/language-tools/issues/2641

**Comment by warmthsea** [comment]
> [vuejs/language-tools#2641](https://github.com/vuejs/language-tools/issues/2641)

![image](https://user-images.githubusercontent.com/45450994/233530193-84da2cc2-9e01-4d4b-9ea7-27fc1cb21bc8.png)
降到 1.2，volar 直接坏掉了

**Comment by Breathe97** [comment]
+1 我今天升级了ts 不知道是不是ts的原因

**Comment by zhuxiaoweb** [comment]
> 

我降级到1.2, vue-tsc版本锁死1.2.0，vite锁死4.2.2就正常了
@chenxch @emojiiii

**Comment by wangcheng1212** [comment]
一样遇到了, volar插件更新导致的, 可以选择将到1.2

**Comment by Jinzm** [comment]
+1

**Comment by StormerZSha** [comment]
问题没有解决的大家可能搞错Volar了，一个是TypeScript Vue Plugin (Volar)，另一个是Vue Language Features (Volar)都叫Volar，要降级是这个Vue Language Features (Volar)

**Comment by warmthsea** [comment]
> > 
> 
> 我降级到1.2, vue-tsc版本锁死1.2.0，vite锁死4.2.2就正常了 @chenxch @emojiiii

锁死了版本，依旧有这个问题

**Comment by Breathe97** [comment]
@StormerZSha 完全有可能 比如我

**Comment by zhangjinzhangjin** [comment]
应该实锤是volar1.4的锅了~

**Comment by zhangjinzhangjin** [comment]
先降到1.2，等volar作者更新吧。
1.2连接
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.2.0/vspackage

**Comment by warmthsea** [comment]
> 应该实锤是volar1.4的锅了~

额，不应该是锅，开源社区用这样的词不合适

**Comment by chenxch** [comment]
@all  正如 @StormerZSha 所说，如果有发现降级到1.2.0还不行的话请检查下插件名是否是`Vue Language Features (Volar)`  (TypeScript Vue Plugin (Volar) 我目前都是禁用的🙈

**Comment by zhangjinzhangjin** [comment]
> 

sorry sorry，口误口误~希望1.4.1早日到来~

**Comment by LQ6666666** [comment]
1.4.1 还是报错 @zhangjinzhangjin

**Comment by Breathe97** [comment]
1.4.1 已经到来可是还是不行

**Comment by zhangjinzhangjin** [comment]
> 1.4.1 还是报错 @zhangjinzhangjin

就是下个版本的意思~1.4.1没修复，1.4.2会解决的~

**Comment by UnknownX1** [comment]
> 先降到1.2，等volar作者更新吧。 1.2连接 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.2.0/vspackage

感谢，更新为1.2已解决

**Comment by Breathe97** [comment]
实测 回退到Vue Language Features (Volar) 1.2.0 正常，其余依赖均升级为最新。

**Comment by zhangjinzhangjin** [comment]
关了啊，大家先把volar降到1.2吧，后天等作者更新就好啦~

**Comment by Breathe97** [comment]
ok

**Comment by warmthsea** [comment]
复现 https://github.com/warmthsea/recurrent-volar-types-err

**Comment by Breathe97** [comment]
> 复现 https://github.com/warmthsea/recurrent-volar-types-err ![image](https://user-images.githubusercontent.com/45450994/233536293-b878ee96-c14d-44c9-aa9b-9f2fbaebae3d.png)

兄弟上面有对应的处理办法哦

**Comment by warmthsea** [comment]
> > 复现 https://github.com/warmthsea/recurrent-volar-types-err ![image](https://user-images.githubusercontent.com/45450994/233536293-b878ee96-c14d-44c9-aa9b-9f2fbaebae3d.png)
> 
> 兄弟上面有对应的处理办法哦

降到1.2在我的项目中 volar直接运行错误
![image](https://user-images.githubusercontent.com/45450994/233536917-ced46236-81d2-4e87-9583-63c9d183beca.png)

**Comment by warmthsea** [comment]
> 关了啊，大家先把volar降到1.2吧，后面等作者更新就好啦~

....降到1.2也不行，锁死版本，各种都尝试了，就差复制同事的依赖了

**Comment by Breathe97** [comment]
> > > 复现 https://github.com/warmthsea/recurrent-volar-types-err ![image](https://user-images.githubusercontent.com/45450994/233536293-b878ee96-c14d-44c9-aa9b-9f2fbaebae3d.png)
> > 
> > 
> > 兄弟上面有对应的处理办法哦
> 
> 降到1.2在我的项目中 volar直接运行错误 ![image](https://user-images.githubusercontent.com/45450994/233536917-ced46236-81d2-4e87-9583-63c9d183beca.png)
  "dependencies": {
    "axios": "^1.3.6",
    "element-plus": "^2.3.3",
    "pinia": "^2.0.35",
    "pinia-plugin-persistedstate": "^3.1.0",
    "vue": "^3.2.47",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.1.0",
    "sass": "^1.62.0",
    "typescript": "^5.0.4",
    "unplugin-auto-import": "^0.15.3",
    "unplugin-vue-components": "^0.24.1",
    "vite": "^4.3.1",
    "vue-tsc": "^1.4.1"
  }
我的依赖时最新的 用ncu更新的最新 没有问题 只需要降级Vue Language Features (Volar) 到1.2.0

**Comment by zhangjinzhangjin** [comment]
> > 关了啊，大家先把volar降到1.2吧，后面等作者更新就好啦~
> 
> ....降到1.2也不行，锁死版本，各种都尝试了，就差复制同事的依赖了

我这降完没报错~下载这个连接离线装一下试试。
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/1.2.0/vspackage

**Comment by warmthsea** [comment]
> > > > 复现 https://github.com/warmthsea/recurrent-volar-types-err ![image](https://user-images.githubusercontent.com/45450994/233536293-b878ee96-c14d-44c9-aa9b-9f2fbaebae3d.png)
> 
> > > 
> 
> > > 
> 
> > > 兄弟上面有对应的处理办法哦
> 
> > 
> 
> > 降到1.2在我的项目中 volar直接运行错误 ![image](https://user-images.githubusercontent.com/45450994/233536917-ced46236-81d2-4e87-9583-63c9d183beca.png)
> 
>   "dependencies": {
> 
>     "axios": "^1.3.6",
> 
>     "element-plus": "^2.3.3",
> 
>     "pinia": "^2.0.35",
> 
>     "pinia-plugin-persistedstate": "^3.1.0",
> 
>     "vue": "^3.2.47",
> 
>     "vue-router": "^4.1.6"
> 
>   },
> 
>   "devDependencies": {
> 
>     "@vitejs/plugin-vue": "^4.1.0",
> 
>     "sass": "^1.62.0",
> 
>     "typescript": "^5.0.4",
> 
>     "unplugin-auto-import": "^0.15.3",
> 
>     "unplugin-vue-components": "^0.24.1",
> 
>     "vite": "^4.3.1",
> 
>     "vue-tsc": "^1.4.1"
> 
>   }
> 
> 我的依赖时最新的 用ncu更新的最新 没有问题 只需要降级Vue Language Features (Volar) 到1.2.0
> 
> 

我不热太清楚到底怎么回事，我尝试了别人成功解决的任何方案依旧无法解决，除了copy旧依赖

**Comment by GMYXDS** [comment]
太可怕了

**Comment by warmthsea** [comment]
在使用了1.2依旧报错后，我把 Volar 降到了 1.1，正常工作了！

![image](https://user-images.githubusercontent.com/45450994/233558991-5d9b6c35-188e-4820-a8bf-51e006092d10.png)

**Comment by simmongod** [comment]
回退至1.2即可工作，不得不说这个安装另外一个版本的跳出速度很慢

**Comment by jsd100** [comment]
我也遇见了这个问题，不知道怎么回事

**Comment by warmthsea** [comment]
> 我也遇见了这个问题，不知道怎么回事

切换 Volar 版本即可工作，1.2不行切1.1

**Comment by lincenying** [comment]
Vue Language Features (Volar)
退回1.2后, 重启vscode可行

**Comment by William-J** [comment]
看到你们的评论，我把volar降级到了1.2.0版本，亲测可以，之前最新版本类型全部报错

**Comment by johnsoncodehk** [comment]
After Volar v1.4, if the component has a call signature, it will be recognized as a functional component for support generics. Excluding `import("vue").Plugin` in `GlobalComponents` can avoid problems, you can update `node_modules/element-plus/global.d.ts` to the following content to avoid the problem.

But this cannot solve the use case of explicit import components. Is `SFCWithInstall` necessary?

```ts
// GlobalComponents for Volar

type WithoutPlugin<T> = T extends import("vue").Plugin & infer R ? R : T;

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAffix: WithoutPlugin<typeof import('element-plus')['ElAffix']>
    ElAlert: WithoutPlugin<typeof import('element-plus')['ElAlert']>
    ElAside: WithoutPlugin<typeof import('element-plus')['ElAside']>
    ElAutocomplete: WithoutPlugin<typeof import('element-plus')['ElAutocomplete']>
    ElAvatar: WithoutPlugin<typeof import('element-plus')['ElAvatar']>
    ElBacktop: WithoutPlugin<typeof import('element-plus')['ElBacktop']>
    ElBadge: WithoutPlugin<typeof import('element-plus')['ElBadge']>
    ElBreadcrumb: WithoutPlugin<typeof import('element-plus')['ElBreadcrumb']>
    ElBreadcrumbItem: WithoutPlugin<typeof import('element-plus')['ElBreadcrumbItem']>
    ElButton: WithoutPlugin<typeof import('element-plus')['ElButton']>
    ElButtonGroup: WithoutPlugin<typeof import('element-plus')['ElButtonGroup']>
    ElCalendar: WithoutPlugin<typeof import('element-plus')['ElCalendar']>
    ElCard: WithoutPlugin<typeof import('element-plus')['ElCard']>
    ElCarousel: WithoutPlugin<typeof import('element-plus')['ElCarousel']>
    ElCarouselItem: WithoutPlugin<typeof import('element-plus')['ElCarouselItem']>
    ElCascader: WithoutPlugin<typeof import('element-plus')['ElCascader']>
    ElCascaderPanel: WithoutPlugin<typeof import('element-plus')['ElCascaderPanel']>
    ElCheckbox: WithoutPlugin<typeof import('element-plus')['ElCheckbox']>
    ElCheckboxButton: WithoutPlugin<typeof import('element-plus')['ElCheckboxButton']>
    ElCheckboxGroup: WithoutPlugin<typeof import('element-plus')['ElCheckboxGroup']>
    ElCol: WithoutPlugin<typeof import('element-plus')['ElCol']>
    ElCollapse: WithoutPlugin<typeof import('element-plus')['ElCollapse']>
    ElCollapseItem: WithoutPlugin<typeof import('element-plus')['ElCollapseItem']>
    ElCollapseTransition: WithoutPlugin<typeof import('element-plus')['ElCollapseTransition']>
    ElColorPicker: WithoutPlugin<typeof import('element-plus')['ElColorPicker']>
    ElContainer: WithoutPlugin<typeof import('element-plus')['ElContainer']>
    ElConfigProvider: WithoutPlugin<typeof import('element-plus')['ElConfigProvider']>
    ElDatePicker: WithoutPlugin<typeof import('element-plus')['ElDatePicker']>
    ElDialog: WithoutPlugin<typeof import('element-plus')['ElDialog']>
    ElDivider: WithoutPlugin<typeof import('element-plus')['ElDivider']>
    ElDrawer: WithoutPlugin<typeof import('element-plus')['ElDrawer']>
    ElDropdown: WithoutPlugin<typeof import('element-plus')['ElDropdown']>
    ElDropdownItem: WithoutPlugin<typeof import('element-plus')['ElDropdownItem']>
    ElDropdownMenu: WithoutPlugin<typeof import('element-plus')['ElDropdownMenu']>
    ElEmpty: WithoutPlugin<typeof import('element-plus')['ElEmpty']>
    ElFooter: WithoutPlugin<typeof import('element-plus')['ElFooter']>
    ElForm: WithoutPlugin<typeof import('element-plus')['ElForm']>
    ElFormItem: WithoutPlugin<typeof import('element-plus')['ElFormItem']>
    ElHeader: WithoutPlugin<typeof import('element-plus')['ElHeader']>
    ElIcon: WithoutPlugin<typeof import('element-plus')['ElIcon']>
    ElImage: WithoutPlugin<typeof import('element-plus')['ElImage']>
    ElImageViewer: WithoutPlugin<typeof import('element-plus')['ElImageViewer']>
    ElInput: WithoutPlugin<typeof import('element-plus')['ElInput']>
    ElInputNumber: WithoutPlugin<typeof import('element-plus')['ElInputNumber']>
    ElLink: WithoutPlugin<typeof import('element-plus')['ElLink']>
    ElMain: WithoutPlugin<typeof import('element-plus')['ElMain']>
    ElMenu: WithoutPlugin<typeof import('element-plus')['ElMenu']>
    ElMenuItem: WithoutPlugin<typeof import('element-plus')['ElMenuItem']>
    ElMenuItemGroup: WithoutPlugin<typeof import('element-plus')['ElMenuItemGroup']>
    ElOption: WithoutPlugin<typeof import('element-plus')['ElOption']>
    ElOptionGroup: WithoutPlugin<typeof import('element-plus')['ElOptionGroup']>
    ElPageHeader: WithoutPlugin<typeof import('element-plus')['ElPageHeader']>
    ElPagination: WithoutPlugin<typeof import('element-plus')['ElPagination']>
    ElPopconfirm: WithoutPlugin<typeof import('element-plus')['ElPopconfirm']>
    ElPopper: WithoutPlugin<typeof import('element-plus')['ElPopper']>
    ElPopover: WithoutPlugin<typeof import('element-plus')['ElPopover']>
    ElProgress: WithoutPlugin<typeof import('element-plus')['ElProgress']>
    ElRadio: WithoutPlugin<typeof import('element-plus')['ElRadio']>
    ElRadioButton: WithoutPlugin<typeof import('element-plus')['ElRadioButton']>
    ElRadioGroup: WithoutPlugin<typeof import('element-plus')['ElRadioGroup']>
    ElRate: WithoutPlugin<typeof import('element-plus')['ElRate']>
    ElRow: WithoutPlugin<typeof import('element-plus')['ElRow']>
    ElScrollbar: WithoutPlugin<typeof import('element-plus')['ElScrollbar']>
    ElSelect: WithoutPlugin<typeof import('element-plus')['ElSelect']>
    ElSlider: WithoutPlugin<typeof import('element-plus')['ElSlider']>
    ElStep: WithoutPlugin<typeof import('element-plus')['ElStep']>
    ElSteps: WithoutPlugin<typeof import('element-plus')['ElSteps']>
    ElSubMenu: WithoutPlugin<typeof import('element-plus')['ElSubMenu']>
    ElSwitch: WithoutPlugin<typeof import('element-plus')['ElSwitch']>
    ElTabPane: WithoutPlugin<typeof import('element-plus')['ElTabPane']>
    ElTable: WithoutPlugin<typeof import('element-plus')['ElTable']>
    ElTableColumn: WithoutPlugin<typeof import('element-plus')['ElTableColumn']>
    ElTabs: WithoutPlugin<typeof import('element-plus')['ElTabs']>
    ElTag: WithoutPlugin<typeof import('element-plus')['ElTag']>
    ElText: WithoutPlugin<typeof import('element-plus')['ElText']>
    ElTimePicker: WithoutPlugin<typeof import('element-plus')['ElTimePicker']>
    ElTimeSelect: WithoutPlugin<typeof import('element-plus')['ElTimeSelect']>
    ElTimeline: WithoutPlugin<typeof import('element-plus')['ElTimeline']>
    ElTimelineItem: WithoutPlugin<typeof import('element-plus')['ElTimelineItem']>
    ElTooltip: WithoutPlugin<typeof import('element-plus')['ElTooltip']>
    ElTransfer: WithoutPlugin<typeof import('element-plus')['ElTransfer']>
    ElTree: WithoutPlugin<typeof import('element-plus')['ElTree']>
    ElTreeV2: WithoutPlugin<typeof import('element-plus')['ElTreeV2']>
    ElTreeSelect: WithoutPlugin<typeof import('element-plus')['ElTreeSelect']>
    ElUpload: WithoutPlugin<typeof import('element-plus')['ElUpload']>
    ElSpace: WithoutPlugin<typeof import('element-plus')['ElSpace']>
    ElSkeleton: WithoutPlugin<typeof import('element-plus')['ElSkeleton']>
    ElSkeletonItem: WithoutPlugin<typeof import('element-plus')['ElSkeletonItem']>
    ElStatistic: WithoutPlugin<typeof import('element-plus')['ElStatistic']>
    ElCheckTag: WithoutPlugin<typeof import('element-plus')['ElCheckTag']>
    ElDescriptions: WithoutPlugin<typeof import('element-plus')['ElDescriptions']>
    ElDescriptionsItem: WithoutPlugin<typeof import('element-plus')['ElDescriptionsItem']>
    ElResult: WithoutPlugin<typeof import('element-plus')['ElResult']>
    ElSelectV2: WithoutPlugin<typeof import('element-plus')['ElSelectV2']>
  }

  interface ComponentCustomProperties {
    $message: typeof import('element-plus')['ElMessage']
    $notify: typeof import('element-plus')['ElNotification']
    $msgbox: typeof import('element-plus')['ElMessageBox']
    $messageBox: typeof import('element-plus')['ElMessageBox']
    $alert: typeof import('element-plus')['ElMessageBox']['alert']
    $confirm: typeof import('element-plus')['ElMessageBox']['confirm']
    $prompt: typeof import('element-plus')['ElMessageBox']['prompt']
    $loading: typeof import('element-plus')['ElLoadingService']
  }
}

export {}
```

**Comment by warmthsea** [comment]
> 

Use unplugin-vue-components， It is indeed possible to use it this way，But these files are all automatically generated, for users, other UI libraries also have this problem. Is there a better solution?

![image](https://user-images.githubusercontent.com/45450994/233601390-240fc595-4e1a-40f4-a2d2-b2373731f4d6.png)

**Comment by johnsoncodehk** [comment]
I made a workaround in https://github.com/vuejs/language-tools/commit/227bb3d4b6eda200f682b02c3694b76ec3426b3a, but this is not a documented behavior. It is best to avoid the presence of call signatures and constructor signatures at the same time for components.

**Comment by warmthsea** [comment]
**Thanks to @johnsoncodehk !  Volar1.4.2 everything is normal.**

![image](https://user-images.githubusercontent.com/45450994/233629736-4b93294c-3bb4-404b-938c-f2c49d33c1c2.png)

**Comment by zhangjinzhangjin** [comment]
@johnsoncodehk thanks

**Comment by Gengkaibo** [comment]
把两个volar插件降级到1.2.0就好了

**Comment by simmongod** [comment]
> 把两个volar插件降级到1.2.0就好了

不用降级了，1.4.2作者已经修复了这个问题
