### ISSUE TITLE
[Component] [select] 多次修改 ElConfigProvider 的 size ， ElSelect 高度不变

### ISSUE THREAD

**Issue by feiYouLian** [element-plus/element-plus#12526]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `112.0.5615.121 (正式版本) （64 位） (cohort: Stable)  / Windows 11 Version 22H2 (Build 22621.1555)`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzaXplID0gcmVmKFwiZGVmYXVsdFwiKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6c2l6ZT1cInNpemVcIj5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJzaXplXCIgPlxuICAgIFx0PGVsLW9wdGlvbiB2YWx1ZT0nc21hbGwnIGxhYmVsPSdzbWFsbCc+IDwvZWwtb3B0aW9uPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT0nZGVmYXVsdCcgbGFiZWw9J2RlZmF1bHQnPiA8L2VsLW9wdGlvbj5cbiAgICAgICA8ZWwtb3B0aW9uIHZhbHVlPSdsYXJnZScgbGFiZWw9J2xhcmdlJz4gPC9lbC1vcHRpb24+XG4gICAgPC9lbC1zZWxlY3Q+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const size = ref("default")
</script>

<template>
  <el-config-provider :size="size">
    <el-select v-model="size" >
    	<el-option value='small' label='small'> </el-option>
      <el-option value='default' label='default'> </el-option>
       <el-option value='large' label='large'> </el-option>
    </el-select>
  </el-config-provider>
</template>
```
切换多次 `size` , 只有第一次正确，以后组件的 `height` 都不会变化

### What is Expected?

多次切换size, 组件高度都会根据 size 变化

### What is actually happening?

 多次切换size, 组件高度只有第一次变化，后面修改不会变化

### Additional comments

_(empty)_

**Comment by btea** [comment]
It seems that #11973 fixes this issue.
