### ISSUE TITLE
[Component] [dialog] el-dialog打开的时候无法使用脚本为其他的input获取焦点，因为focusout事件绑定的存在

### ISSUE THREAD

**Issue by Autumn-one** [element-plus/element-plus#12525]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `  Binaries:     Node: 18.13.0 - C:\Program Files\nodejs\node.EXE     npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: Spartan (44.22621.1194.0), Chromium (110.0.1587.41)     Internet Explorer: 11.0.22621.1   npmPackages:     vue: ^3.2.45 => 3.2.45`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSwgbmV4dFRpY2ssIG9uTW91bnRlZCwgb25CZWZvcmVVbm1vdW50IH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuIFxuIGNvbnN0IHRlc3RfaW5wdXQgPSByZWYoKVxuY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gIHZpczogZmFsc2Vcbn0pO1xuICBcbiBcbiBjb25zdCBtZXRob2RzID0ge1xuICAgYXN5bmMgc2hvd19kaWFsb2dfYW5kX2ZvY3VzX2lucHV0ICgpIHtcbiAgICAgc3RhdGUudmlzID0gdHJ1ZTsgLy8g6L+Z5LiA6KGM5rOo6YeK5bCx5Y+v5Lul6IGa54Sm77yM5LiN5rOo6YeK5bCx5Lya5Zug5Li65pyJIGZvY3Vzb3V05LqL5Lu255qE5a2Y5Zyo6ICM6IGa54Sm5aSx6LSl44CCXG4gICAgIGF3YWl0IG5leHRUaWNrKCk7IC8vIOWKoOWkmuWwkemDveayoeeUqFxuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBcbiAgICAgdGVzdF9pbnB1dC52YWx1ZS5mb2N1cygpO1xuICAgfSxcbiAgIGtleXVwX2hhbmRsZSAoZSkge1xuICAgIGUucHJldmVudERlZmF1bHQoKTtcbiAgICBpZihlLmtleSA9PT0gXCJBbHRcIil7XG4gICAgICBtZXRob2RzLnNob3dfZGlhbG9nX2FuZF9mb2N1c19pbnB1dCgpXG4gICAgfVxuICB9XG4gfVxuIFxuIG9uTW91bnRlZCgoKSA9PiB7XG4gIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoXCJrZXl1cFwiLG1ldGhvZHMua2V5dXBfaGFuZGxlICwgZmFsc2UpXG59KVxub25CZWZvcmVVbm1vdW50KCgpID0+IGRvY3VtZW50LnJlbW92ZUV2ZW50TGlzdGVuZXIoXCJrZXl1cFwiLCBtZXRob2RzLmtleXVwX2hhbmRsZSwgZmFsc2UpKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJzdGF0ZS52aXNcIiA6bW9kYWw9XCJmYWxzZVwiPjwvZWwtZGlhbG9nPlxuICBcbiAgPGVsLWlucHV0IGNsYXNzPVwiaW5wdXQtdGVzdFwiIHJlZj1cInRlc3RfaW5wdXRcIiBwbGFjZWhvbGRlcj1cIuWcqOW8ueeql+aYvuekuueahOaXtuWAmeS8muiHquWKqOiOt+WPlueEpueCue+8jOS9huaYr+WunumZheS4iuiOt+WPluS4jeWIsFwiPjwvZWwtaW5wdXQ+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIC5pbnB1dC10ZXN0e1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICB3aWR0aDogMjAwcHg7XG4gICAgei1pbmRleDogOTk5OTtcbiAgICB0b3A6IDEwMHB4O1xuICAgIGxlZnQ6IDUwcHg7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

进去之后点击一下预览页面的非input部分，之后按alt键，input无法聚焦

### What is Expected?

input要聚焦

### What is actually happening?

input没有聚焦

### Additional comments

这个东西有什么临时的解决办法吗？

**Comment by Autumn-one** [comment]
> 

上面给出的案例有误，下面是新的案例。进入之后确保第一个input已经聚焦了，然后按 alt 键来显示弹窗，这个时候加多少nextTick都没有用。
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSwgbmV4dFRpY2ssIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IG9uZV9pbnB1dCA9ICByZWYoKVxuICBcbiBjb25zdCB0ZXN0X2lucHV0ID0gcmVmKClcbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICB2aXM6IGZhbHNlXG59KTtcbiAgXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBvbmVfaW5wdXQudmFsdWUuZm9jdXMoKTtcbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcihcImtleXVwXCIsIGZ1bmN0aW9uKGUpe1xuICAgIGUucHJldmVudERlZmF1bHQoKTtcbiAgICBpZihlLmtleSA9PT0gXCJBbHRcIil7XG4gICAgICBtZXRob2RzLnNob3dfZGlhbG9nX2FuZF9mb2N1c19pbnB1dCgpXG4gICAgfVxuICB9LCBmYWxzZSlcbn0pXG5cbiBcbiBjb25zdCBtZXRob2RzID0ge1xuICAgYXN5bmMgc2hvd19kaWFsb2dfYW5kX2ZvY3VzX2lucHV0ICgpIHtcbiAgICAgc3RhdGUudmlzID0gdHJ1ZTsgLy8g6L+Z5LiA6KGM5rOo6YeK5bCx5Y+v5Lul6IGa54Sm77yM5LiN5rOo6YeK5bCx5Lya5Zug5Li65pyJIGZvY3Vzb3V05LqL5Lu255qE5a2Y5Zyo6ICM6IGa54Sm5aSx6LSl44CCXG4gICAgIGF3YWl0IG5leHRUaWNrKCk7IC8vIOWKoOWkmuWwkemDveayoeeUqFxuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBcbiAgICAgdGVzdF9pbnB1dC52YWx1ZS5mb2N1cygpO1xuICAgfVxuIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cInN0YXRlLnZpc1wiIDptb2RhbD1cImZhbHNlXCI+XG4gIFxuICA8L2VsLWRpYWxvZz5cbiAgXG4gIDxlbC1pbnB1dCByZWY9XCJvbmVfaW5wdXRcIiBwbGFjZWhvbGRlcj1cIui/meS4qui+k+WFpeahhuS4gOW8gOWni+WwseiBmueEpuS6hlwiPjwvZWwtaW5wdXQ+XG4gIDxlbC1pbnB1dCBjbGFzcz1cImlucHV0LXRlc3RcIiByZWY9XCJ0ZXN0X2lucHV0XCIgcGxhY2Vob2xkZXI9XCLlnKjlvLnnqpfmmL7npLrnmoTml7blgJnkvJroh6rliqjojrflj5bnhKbngrnvvIzkvYbmmK/lrp7pmYXkuIrojrflj5bkuI3liLBcIj48L2VsLWlucHV0PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuaW5wdXQtdGVzdHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgd2lkdGg6IDIwMHB4O1xuICAgIHotaW5kZXg6IDk5OTk7XG4gICAgdG9wOiAxMDBweDtcbiAgICBsZWZ0OiA1MHB4O1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by Autumn-one** [comment]
> [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbiBjb25zdCB0ZXN0X2lucHV0ID0gcmVmKClcbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICB2aXM6IGZhbHNlXG59KTtcbiBcbiAgXG4gY29uc3QgbWV0aG9kcyA9IHtcbiAgIGFzeW5jIHNob3dfZGlhbG9nX2FuZF9mb2N1c19pbnB1dCAoKSB7XG4gICAgIHN0YXRlLnZpcyA9IHRydWU7IC8vIOi/meS4gOihjOazqOmHiuWwseWPr+S7peiBmueEpu+8jOS4jeazqOmHiuWwseS8muWboOS4uuaciSBmb2N1c291dOS6i+S7tueahOWtmOWcqOiAjOiBmueEpuWksei0peOAglxuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICAgIFx0dGVzdF9pbnB1dC52YWx1ZS5mb2N1cygpO1xuICAgICBcbiAgIH1cbiB9XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cIm1ldGhvZHMuc2hvd19kaWFsb2dfYW5kX2ZvY3VzX2lucHV0XCI+54K55Ye75pi+56S65by556qX5bm26IGa54SmPC9lbC1idXR0b24+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cInN0YXRlLnZpc1wiIDptb2RhbD1cImZhbHNlXCI+XG4gIFxuICA8L2VsLWRpYWxvZz5cbiAgXG4gIDxlbC1pbnB1dCBjbGFzcz1cImlucHV0LXRlc3RcIiByZWY9XCJ0ZXN0X2lucHV0XCIgcGxhY2Vob2xkZXI9XCLlnKjlvLnnqpfmmL7npLrnmoTml7blgJnkvJroh6rliqjojrflj5bnhKbngrnvvIzkvYbmmK/lrp7pmYXkuIrojrflj5bkuI3liLBcIj48L2VsLWlucHV0PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuaW5wdXQtdGVzdHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgd2lkdGg6IDIwMHB4O1xuICAgIHotaW5kZXg6IDk5OTk7XG4gICAgdG9wOiAxMDBweDtcbiAgICBsZWZ0OiA1MHB4O1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319) 再加一次nextTick即可。

上面的案例有误，更新了一下案例，进去之后点一下预览页面按alt键。 [新案例](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSwgbmV4dFRpY2ssIG9uTW91bnRlZCwgb25CZWZvcmVVbm1vdW50IH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuIFxuIGNvbnN0IHRlc3RfaW5wdXQgPSByZWYoKVxuY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gIHZpczogZmFsc2Vcbn0pO1xuICBcbiBcbiBjb25zdCBtZXRob2RzID0ge1xuICAgYXN5bmMgc2hvd19kaWFsb2dfYW5kX2ZvY3VzX2lucHV0ICgpIHtcbiAgICAgc3RhdGUudmlzID0gdHJ1ZTsgLy8g6L+Z5LiA6KGM5rOo6YeK5bCx5Y+v5Lul6IGa54Sm77yM5LiN5rOo6YeK5bCx5Lya5Zug5Li65pyJIGZvY3Vzb3V05LqL5Lu255qE5a2Y5Zyo6ICM6IGa54Sm5aSx6LSl44CCXG4gICAgIGF3YWl0IG5leHRUaWNrKCk7IC8vIOWKoOWkmuWwkemDveayoeeUqFxuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBhd2FpdCBuZXh0VGljaygpO1xuICAgICBcbiAgICAgdGVzdF9pbnB1dC52YWx1ZS5mb2N1cygpO1xuICAgfSxcbiAgIGtleXVwX2hhbmRsZSAoZSkge1xuICAgIGUucHJldmVudERlZmF1bHQoKTtcbiAgICBpZihlLmtleSA9PT0gXCJBbHRcIil7XG4gICAgICBtZXRob2RzLnNob3dfZGlhbG9nX2FuZF9mb2N1c19pbnB1dCgpXG4gICAgfVxuICB9XG4gfVxuIFxuIG9uTW91bnRlZCgoKSA9PiB7XG4gIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoXCJrZXl1cFwiLG1ldGhvZHMua2V5dXBfaGFuZGxlICwgZmFsc2UpXG59KVxub25CZWZvcmVVbm1vdW50KCgpID0+IGRvY3VtZW50LnJlbW92ZUV2ZW50TGlzdGVuZXIoXCJrZXl1cFwiLCBtZXRob2RzLmtleXVwX2hhbmRsZSwgZmFsc2UpKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJzdGF0ZS52aXNcIiA6bW9kYWw9XCJmYWxzZVwiPjwvZWwtZGlhbG9nPlxuICBcbiAgPGVsLWlucHV0IGNsYXNzPVwiaW5wdXQtdGVzdFwiIHJlZj1cInRlc3RfaW5wdXRcIiBwbGFjZWhvbGRlcj1cIuWcqOW8ueeql+aYvuekuueahOaXtuWAmeS8muiHquWKqOiOt+WPlueEpueCue+8jOS9huaYr+WunumZheS4iuiOt+WPluS4jeWIsFwiPjwvZWwtaW5wdXQ+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIC5pbnB1dC10ZXN0e1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICB3aWR0aDogMjAwcHg7XG4gICAgei1pbmRleDogOTk5OTtcbiAgICB0b3A6IDEwMHB4O1xuICAgIGxlZnQ6IDUwcHg7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by xiaokar** [comment]
![image](https://github.com/element-plus/element-plus/assets/40920747/4b4f1d63-ba5a-4931-9b81-7cb981b0ec79)
我这个都没法聚焦，可以点击

**Comment by Autumn-one** [comment]
> ![image](https://user-images.githubusercontent.com/40920747/243247913-4b4f1d63-ba5a-4931-9b81-7cb981b0ec79.png) 我这个都没法聚焦，可以点击

换ui框架，其他框架的弹窗可以，或者自己写个简易的了，这团队没把这问题当回事

**Comment by xiaokar** [comment]
> > ![图像](https://user-images.githubusercontent.com/40920747/243247913-4b4f1d63-ba5a-4931-9b81-7cb981b0ec79.png)我这个都没有法聚焦，可以点击
> 
> 换ui框，其他框的弹窗可以，或者自己写一个简单的了，这个团没有把这个问题当回事儿

噢谢谢，没其他解决方案的话只能这样了

**Comment by tolking** [comment]
为满足 A11y，组件库里面的所有弹窗在打开时都会困住焦点。[参考链接](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/)
