### ISSUE TITLE
[Component] [All] element-plus What are the functions and differences of css.ts index.ts in the component style folder

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#12521]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.32`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/lixiaofa/fast-business)

### Steps to reproduce

pnpm dev

### What is Expected?

Something

### What is actually happening?

Nothing there?

### Additional comments

_(empty)_

**Comment by lixiaofa** [comment]
element-plus 
What are the functions and differences of css.ts index.ts in the component style folder

![image](https://user-images.githubusercontent.com/23230215/233251603-97ee9f3e-e28f-488e-9690-80e5919cf4e4.png)

**Comment by chenxch** [comment]
@lixiaofa  I will close this issue, please go to the discussion area to open this topic.

**Comment by lixiaofa** [comment]
> @lixiaofa I will close this issue, please go to the discussion area to open this topic.
 @chenxch  #12516
