### ISSUE TITLE
[Component] [tree-select] 使用ThreeSelect组件无法正常绑定node-key

### ISSUE THREAD

**Issue by huazaiz** [element-plus/element-plus#12527]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome/windows11`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGJ1VHlwZU5hbWUgPSByZWYoW10pXG5sZXQgYnVUeXBlU2VsZWN0ID0gW3tuYW1lOlwi5YWo6YOoXCIsY29kZTpcIjMzM1wiLGNoaWxkcmVuOlt7bmFtZTpcIjMzMzNcIixjb2RlOlwiMVwifV19XVxuY29uc3QgdHJlZVNlbGVjdFByb3BzID0gcmVmKHtcbiAgICBsYWJlbDogJ25hbWUnLFxuICAgIGNoaWxkcmVuOiAnY2hpbGRyZW4nXG4gICAgXG59KVxuY29uc3QgY2hlY2sgPSAoKT0+e1xuICBjb25zb2xlLmxvZyhidVR5cGVOYW1lLnZhbHVlKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxlbC10cmVlLXNlbGVjdCB2LW1vZGVsPVwiYnVUeXBlTmFtZVwiIDpwcm9wcz1cInRyZWVTZWxlY3RQcm9wc1wiIG11bHRpcGxlIDpyZW5kZXItYWZ0ZXItZXhwYW5kPVwiZmFsc2VcIiBzaG93LWNoZWNrYm94ICBub2RlLWtleT1cImNvZGVcIiA6ZGF0YT1cImJ1VHlwZVNlbGVjdFwiICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeS4muWKoeexu+Wei1wiIC8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2hlY2tcIj7ngrnlh7s8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

我的vue版本是3.0.4

### What is Expected?

node-key失效

### What is actually happening?

node-key失效

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
哪里失效了请问，示例看不出问题
