### ISSUE TITLE
[Component] [upload] [upload]组件最新版本2.3.3会导致偶尔获取不到key,降到2.2.36版本可以解决

### ISSUE THREAD

**Issue by wangcheng1212** [element-plus/element-plus#12530]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome 110.0.5481.78`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues/12529)

### Steps to reproduce

no

### What is Expected?

no

### What is actually happening?

no

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/38998191/233535207-677df882-113a-49bf-a196-24107ddb8cbf.png)

**Comment by wangcheng1212** [comment]
before-upload中获取oss参数,怀疑是before-upload触发时机问题导致

**Comment by chenxch** [comment]
@wangcheng1212 请提供正确的repo

**Comment by chenxch** [comment]
same as #12340

**Comment by HeftyKoo** [comment]
Duplicate with #13925

**Comment by fangnuoyu** [comment]
不降版本怎么解决
