### ISSUE TITLE
[TypeScript] [table-column, table] vue-tsc 升级到 1.3.7 使用 el-table-column 的 template scope 时 打包时出现 error TS7006: Parameter 'scope' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [element-plus/element-plus#12531]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`

### Reproduction Link

[Github Repo](https://github.com/xuxiaowei-com-cn/my-vue-app.git)

### Steps to reproduce

运行打包，出现错误
```
"D:\Program Files\nodejs\npm.cmd" run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> my-vue-app@0.0.0 build        
> vue-tsc --noEmit && vite build

src/App.vue:78:33 - error TS7006: Parameter 'scope' implicitly has an 'any' type.

78             <template #default="scope">
                                   ~~~~~


Found 1 error in src/App.vue:78
```

### What is Expected?

正常打包

### What is actually happening?

打包失败

### Additional comments

开发运行不存在问题。
将 vue-tsc 降级到 1.3.6 不存在问题。

**Comment by xuxiaowei-com-cn** [comment]
目前测试了几个版本发现，vue-tsc 版本大于 1.3.6 后，运行测试没问题，打包均出现问题。

**Comment by uniquejava** [comment]
在 tsconfig.json 里 加上 `noImplicitAny: false` 就好了,但是解决不了根本问题, element plus 是否能给 scope 提供类型声明?

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1049271/233539985-cbf9aaf8-eed8-4b80-bffb-a0c53eaadfbf.png">


Set `noImplicitAny: false` in `tsconfig.json` can workaround this problem, but this does not solve the root problem.

**Comment by titxue** [comment]
<template #default="scope:any">

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/233545902-fdce933b-cc15-4a22-a65b-b71afaf94e9a.png)
![image](https://user-images.githubusercontent.com/46893436/233545905-eb43d2db-4e7e-462e-8b03-1d8ef7d21427.png)

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/233548791-4814fded-58b6-4f12-9651-d15c6b9e4623.png)

**Comment by xuxiaowei-com-cn** [comment]
改用h函数：https://github.com/xuxiaowei-com-cn/my-vue-app/pull/1

**Comment by titxue** [comment]
> ![图像](https://user-images.githubusercontent.com/46893436/233548791-4814fded-58b6-4f12-9651-d15c6b9e4623.png)

![image](https://user-images.githubusercontent.com/30921318/233551695-bdceac2b-39be-4b1a-9842-da465ede12f7.png)
![image](https://user-images.githubusercontent.com/30921318/233551763-c22db77a-ee9c-4597-a9e0-23ff44897c65.png)

**Comment by xuxiaowei-com-cn** [comment]
请查看：
1. https://github.com/xuxiaowei-com-cn/my-vue-app/tree/fix-1
2. https://github.com/xuxiaowei-com-cn/my-vue-app/tree/PR-1

**Comment by warmthsea** [comment]
原因是 Vue3.3 加入了Component泛型，插槽可以推导类型，可能是Vue3.3马上要发布其他工具类兼容的原因

**Comment by feianjun** [comment]
[dddd]([https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDtcIj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6IDkwcHg7IGZsZXgtc2hyaW5rOiAwOyBoZWlnaHQ6IDEwMHB4OyBiYWNrZ3JvdW5kOiByZWQ7XCI+MjwvZGl2PlxuICAgIDxkaXYgc3R5bGU9XCJmbGV4OiAxO1wiPlxuICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlO1wiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJzdGF0ZVwiIGxhYmVsPVwiU3RhdGVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY2l0eVwiIGxhYmVsPVwiQ2l0eVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCI2MDBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiWmlwXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQ9XCJyaWdodFwiIGxhYmVsPVwiT3BlcmF0aW9uc1wiIHdpZHRoPVwiMTIwXCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICAgIDxlbC1idXR0b24gbGluayB0eXBlPVwicHJpbWFyeVwiIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgICAgICAgICAgICAgICA+RGV0YWlsPC9lbC1idXR0b25cbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBzaXplPVwic21hbGxcIj5FZGl0PC9lbC1idXR0b24+XG4gICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICA8L2VsLXRhYmxlPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnY2xpY2snKVxufVxuXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==](https://github.com/element-plus/element-plus/issues/url))

**Comment by feianjun** [comment]
[[https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDtcIj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6IDkwcHg7IGZsZXgtc2hyaW5rOiAwOyBoZWlnaHQ6IDEwMHB4OyBiYWNrZ3JvdW5kOiByZWQ7XCI+MjwvZGl2PlxuICAgIDxkaXYgc3R5bGU9XCJmbGV4OiAxO1wiPlxuICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlO1wiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJzdGF0ZVwiIGxhYmVsPVwiU3RhdGVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY2l0eVwiIGxhYmVsPVwiQ2l0eVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCI2MDBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiWmlwXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQ9XCJyaWdodFwiIGxhYmVsPVwiT3BlcmF0aW9uc1wiIHdpZHRoPVwiMTIwXCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICAgIDxlbC1idXR0b24gbGluayB0eXBlPVwicHJpbWFyeVwiIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgICAgICAgICAgICAgICA+RGV0YWlsPC9lbC1idXR0b25cbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBzaXplPVwic21hbGxcIj5FZGl0PC9lbC1idXR0b24+XG4gICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICA8L2VsLXRhYmxlPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnY2xpY2snKVxufVxuXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==](https://github.com/element-plus/element-plus/issues/url)](111)

**Comment by pany-ang** [comment]
vue-tsc 1.4.2 已经修改该问题
