### ISSUE TITLE
[TypeScript] [table, table-column]   vue3+Ts   <template #default="scope"> 使用 scope.row 会报错  对象的类型为 "unknown"。 最近才出现

### ISSUE THREAD

**Issue by wangc19992711** [element-plus/element-plus#12555]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.2`
- Browser / OS: ` Google Chrome 112.0.5615.138`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5jb25zdCBoYW5kbGVFZGl0ID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuY29uc3QgaGFuZGxlRGVsZXRlID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlclwiPlxuICAgICAgICAgIDxlbC1pY29uPjx0aW1lciAvPjwvZWwtaWNvbj5cbiAgICAgICAgICA8c3BhbiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiAxMHB4XCI+e3sgc2NvcGUucm93LmRhdGUgfX08L3NwYW4+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtcG9wb3ZlciBlZmZlY3Q9XCJsaWdodFwiIHRyaWdnZXI9XCJob3ZlclwiIHBsYWNlbWVudD1cInRvcFwiIHdpZHRoPVwiYXV0b1wiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgICAgIDxkaXY+bmFtZToge3sgc2NvcGUucm93Lm5hbWUgfX08L2Rpdj5cbiAgICAgICAgICAgIDxkaXY+YWRkcmVzczoge3sgc2NvcGUucm93LmFkZHJlc3MgfX08L2Rpdj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICAgICAgPGVsLXRhZz57eyBzY29wZS5yb3cubmFtZSB9fTwvZWwtdGFnPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDwvZWwtcG9wb3Zlcj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk9wZXJhdGlvbnNcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiaGFuZGxlRWRpdChzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgID5FZGl0PC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICB0eXBlPVwiZGFuZ2VyXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVEZWxldGUoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RGVsZXRlPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<template>
  <el-table :data="tableData" style="width: 100%">
    <el-table-column label="Date" width="180">
      <template #default="scope">
        <div style="display: flex; align-items: center">
          <el-icon><timer /></el-icon>
          <span style="margin-left: 10px">{{ scope.row.date }}</span>
        </div>
      </template>
    </el-table-column>
    <el-table-column label="Name" width="180">
      <template #default="scope">
        <el-popover effect="light" trigger="hover" placement="top" width="auto">
          <template #default>
            <div>name: {{ scope.row.name }}</div>
            <div>address: {{ scope.row.address }}</div>
          </template>
          <template #reference>
            <el-tag>{{ scope.row.name }}</el-tag>
          </template>
        </el-popover>
      </template>
    </el-table-column>
    <el-table-column label="Operations">
      <template #default="scope">
        <el-button size="small" @click="handleEdit(scope.$index, scope.row)"
          >Edit</el-button
        >
        <el-button
          size="small"
          type="danger"
          @click="handleDelete(scope.$index, scope.row)"
          >Delete</el-button
        >
      </template>
    </el-table-column>
  </el-table>
</template>

<script lang="ts" setup>
import { Timer } from '@element-plus/icons-vue'

interface User {
  date: string
  name: string
  address: string
}

const handleEdit = (index: number, row: User) => {
  console.log(index, row)
}
const handleDelete = (index: number, row: User) => {
  console.log(index, row)
}

const tableData: User[] = [
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>

### What is Expected?

解决问题 修复

### What is actually happening?

解决问题 修复

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#12531

**Comment by haoma2514** [comment]
> #12531

在 tsconfig.json 里 加上 noImplicitAny: false 
升级 vue-tsc
问题和题主一样， 这个两个方式都没用。 也没有升级任何包，突然就出现这个问题了。 找了好久，还以为vscode出问题了，题主搞好了吗？

**Comment by ChristopherLyyy** [comment]
> #12531

运行和打包时不存在问题，只有ts报错
vue-tsc升级至v1.4.4无法解决

**Comment by Cxx0822** [comment]
重新安装下Vscode的Volar插件

**Comment by wangc19992711** [comment]
> > #12531
> 
> 在 tsconfig.json 里 加上 noImplicitAny: false 升级 vue-tsc 问题和题主一样， 这个两个方式都没用。 也没有升级任何包，突然就出现这个问题了。 找了好久，还以为vscode出问题了，题主搞好了吗？

没有  上面两种方法确实不好使用 ，而且值用Ts 才会有这个问题  <template #default="scope:any">  可以解决 但是每个都需要加 很麻烦 目前还在找解决方法

**Comment by wangc19992711** [comment]
> 重新安装下Vscode的Volar插件
重新安装下Vscode的Volar插件
在 tsconfig.json 里 加上 noImplicitAny: false 升级 vue-tsc 
运行时 还是会报错  对象的类型为 "unknown"

**Comment by ChristopherLyyy** [comment]
> 

非常感谢 解决了

**Comment by ChristopherLyyy** [comment]
> 重新安装下Vscode的Volar插件

非常感谢 解决了(●'◡'●)

**Comment by wangc19992711** [comment]
![uTools_1682325399842](https://user-images.githubusercontent.com/131564554/233948072-0d4dd48b-15a8-4e0b-be5a-eafae57d57da.png)
两种卸载 都重装一下 就可以了

**Comment by haoma2514** [comment]
> ![uTools_1682325399842](https://user-images.githubusercontent.com/131564554/233948072-0d4dd48b-15a8-4e0b-be5a-eafae57d57da.png) 两种卸载 都重装一下 就可以了


 确实可以，感谢！

**Comment by wangmeijian** [comment]
> ![uTools_1682325399842](https://user-images.githubusercontent.com/131564554/233948072-0d4dd48b-15a8-4e0b-be5a-eafae57d57da.png) 两种卸载 都重装一下 就可以了

可以
