### ISSUE TITLE
[Component] [select] el-select size change failed

### ISSUE THREAD

**Issue by uxc150023** [element-plus/element-plus#12557]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.3.1`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html)

### Steps to reproduce

change size

### What is Expected?

change size success

### What is actually happening?

change size failed

### Additional comments

_(empty)_

**Comment by uxc150023** [comment]
![image](https://user-images.githubusercontent.com/45356395/233818521-b4749a69-ab45-4922-9327-e49039e7c337.png)

**Comment by yj-liuzepeng** [comment]
It seems that https://github.com/element-plus/element-plus/pull/11973 has fixed this issue
