### ISSUE TITLE
[Bug Report] set locale failed when import element-plus on demand and set custom theme

### ISSUE THREAD

**Issue by huxianc** [element-plus/element-plus#1255]
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
Google Chrome  87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://github.com/huxianc/element-plus-locale

### Steps to reproduce
[preview](https://huxianc.github.io/element-plus-locale/dist/index.html)

### What is Expected?
 Import element-plus on demand ,set custom theme and set locale(zh-cn) successed

### What is actually happening?
element-plus use default locale - es,
but when I console the `$ELEMENT` settings , 'zh-cn' is the locale's name,but rendered in 'es'

**Comment by zazzaz** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/10731096/104153204-b0fb2a80-541c-11eb-8e16-465e3a1e5c19.png">

check from the preview link above, seem displaying in `zh-cn` locale as expected.

**Comment by huxianc** [comment]
Not label,I'm saying the locale in `element-plus`, the empty data in `transfer` and `table`  component is rendered `no data` instead of `无数据`，and the `el-pagination` component is all rendeded in `es`,that's why I opened the issue

**Comment by JeremyWuuuuu** [comment]
Seems like `no data` didn't get translated.

**Comment by huxianc** [comment]
Not just `no data`,seems like all components translate failed,all of them are rendeded in `es`.

**Comment by JeremyWuuuuu** [comment]
You need to use `use` from `locale.ts`

![image](https://user-images.githubusercontent.com/15975785/104160088-7baa0900-542b-11eb-9fb0-6a4db846a483.png)

See here: 
![image](https://user-images.githubusercontent.com/15975785/104160104-8795cb00-542b-11eb-82cb-a40dd54a9283.png)

The way you use it seems not right, since the config is not reactive.

**Comment by JeremyWuuuuu** [comment]
Try this:
![image](https://user-images.githubusercontent.com/15975785/104160788-ab0d4580-542c-11eb-941f-d2ac4e223a05.png)

**Comment by zazzaz** [comment]
According to the doc https://element-plus.org/#/en-US/component/i18n

```
import lang from 'element-plus/lib/locale/lang/zh-cn'
import 'dayjs/locale/zh-cn'
import locale from 'element-plus/lib/locale'

// configure language
locale.use(lang)
```

**Comment by JeremyWuuuuu** [comment]
Note that:

Setting the `globalConfig` is not a solution because `config.$ELEMENT` is not reactive, so that setting the value WILL NOT TRIGGER ANY EFFECT. You need to use the function from `element-plus/lib/locale` to set that.

**Comment by huxianc** [comment]
I see,thanks! Seems like I missed this line when I checked the doc.
