### ISSUE TITLE
[Component] [table] table组件，tooltipOptions.showAfter不生效

### ISSUE THREAD

**Issue by xingyixiang** [element-plus/element-plus#12564]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6dG9vbHRpcC1vcHRpb25zPVwie3Nob3dBZnRlcjogMTAwMH1cIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiBzaG93LW92ZXJmbG93LXRvb2x0aXAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

el-table 设置:tooltip-options="{ showAfter: 1000 }"，el-table-column 设置show-overflow-tooltip；文字超出时发现tooltip还是立即出现

### What is Expected?

希望延迟展示tooltip

### What is actually happening?

tooltip还是立即出现

**Comment by lcnsf18** [comment]
这个问题现在还没有修复吗

**Comment by PeiJM** [comment]
还是不管用啊 ~

**Comment by DagedaLin** [comment]
还没解决吗 o(╥﹏╥)o

**Comment by xingyixiang** [comment]
@DagedaLin 
[https://github.com/element-plus/element-plus/pull/13175](https://github.com/element-plus/element-plus/pull/13175)

**Comment by DagedaLin** [comment]
@xingyixiang 那就等更新版本了
