### ISSUE TITLE
[Component] [color-picker] ColorPicker panel cursor may have incorrect position

### ISSUE THREAD

**Issue by teslor** [element-plus/element-plus#12581]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 112 / Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjb2xvciA9IHJlZignIzU2NThBQycpXG5jb25zdCBwcmVkZWZpbmVDb2xvcnMgPSByZWYoWycjNTBENzU3JywnI0MyNEM1MiddKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbG9yLXBpY2tlciB2LW1vZGVsPVwiY29sb3JcIiA6cHJlZGVmaW5lPVwicHJlZGVmaW5lQ29sb3JzXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1) Click ColorPicker with some initial color -> see that panel cursor has left/top position which is incorrect.
2) Click ColorPicker -> select some color from the panel (not too dark) -> press OK -> reopen ColorPicker -> panel cursor has left/top position again.

### What is Expected?

The panel cursor is positioned according to the current selected color regardless how this color was set.

### What is actually happening?

The panel cursor can be placed in top left corner regardless the current color.

### Additional comments

This bug happens if a color is selected by clicking inside the panel. There are cases when the panel marker is correctly positioned after ColorPicker is reopened (however if the color is reset or set programmatically to another one the bug still exists):
1) Predefined color is selected.
2) Color is entered in the color input. Or the input just was selected/clicked before OK is pressed.
3) A color selected inside the panel is very dark (e.g. near left/right bottom corner).

The bug is also reproducible at official site usage samples - https://element-plus.org/en-US/component/color-picker.html

**Comment by yj-liuzepeng** [comment]
这样改有效果吗，我试了下，好像并没有效果  https://github.com/element-plus/element-plus/pull/12588

**Comment by h1dd3nsn1p3r** [comment]
+1 Following....

**Comment by wtjperi2003** [comment]
哪里有解决办法？到处没找到
