### ISSUE TITLE
[feature request] consider adding the usage of TSX to the sample

### ISSUE THREAD

**Issue by yangyin** [element-plus/element-plus#1258]
### Existing Component
是

### Component Name
所有组件

### Description
是否考虑在样例中加入tsx中的使用方式

**Comment by zazzaz** [comment]
What kind of demo are you looking for? All components or some specific one?

**Comment by yangyin** [comment]
现有组件中都是使用template写法，在转换到jsx写法时，比如有不同点可标注说明/或者需注意点提醒，可使开发更加流畅

**Comment by ht-sauce** [comment]
貌似没有必要，推广jsx主要取决于vue官方是否大力推广jsx

**Comment by zazzaz** [comment]
@ht-sauce Agreed. We could keep using the template syntax until Vue3.0 officially recommend JSX as their first choice.

**Comment by yangyin** [comment]
ts可以安排上撒

**Comment by zazzaz** [comment]
As a UI library, we intend to make the demo as easy as simple as it could. 

That would be much friendly to front-end beginners or backend engineers.

That's the reason we choose `Javascript` + `option API` + `template`.

For those who with high coding skills, it's nor hard for them to use the demo code in `Typescript` or `JSX`

**Comment by ht-sauce** [comment]
而且tsx或者jsx目前是阿里维护，说实在有点不太信赖。但是又别无选择。而且jsx对于vue来说，我想永远不会是主流。因为，这样会让vue走向灭亡。就像react推广者一样的，vue写jsx那我还不如用react，毕竟人家是鼻祖。

**Comment by JeremyWuuuuu** [comment]
Doesn't matter, `jsx` is just a type of template, it should be independent for projects. BUT it is still a nice to have.

**Comment by JeremyWuuuuu** [comment]
Ummm, we don't think that adding `jsx` has anything to do with any library, it should only be a choice for our users to use, the only thing we should do is that support `jsx` language feature. I didn't see any other library implemented this in their doc site. So I am closing this issue, feel free to reopen this.
