### ISSUE TITLE
[Component] [select-v2] el-select-v2 下拉面板宽度不能自适应内容宽度

### ISSUE THREAD

**Issue by wuxueqin** [element-plus/element-plus#12585]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.2`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+dXNlIGNvbGxhcHNlLXRhZ3M8L3A+XG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxwPnVzZSBjb2xsYXBzZS10YWdzLXRvb2x0aXA8L3A+XG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBjb2xsYXBzZS10YWdzXG4gICAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxwPnVzZSBtYXgtY29sbGFwc2UtdGFnczwvcD5cbiAgICA8ZWwtc2VsZWN0LXYyXG4gICAgICB2LW1vZGVsPVwidmFsdWUzXCJcbiAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgICAgOm1heC1jb2xsYXBzZS10YWdzPVwiM1wiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbJ2Fka3NhamFzaGRzYWhkanNhaGZqc2FoZmpzaGZqc2hmanNhaGZqc2FmaCcsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaiddXG5cbmNvbnN0IHZhbHVlID0gcmVmKFtdKVxuY29uc3QgdmFsdWUyID0gcmVmKFtdKVxuY29uc3QgdmFsdWUzID0gcmVmKFtdKVxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICBsYWJlbDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

下拉展示面板

### What is Expected?

内容宽度能自适应每项的宽度

### What is actually happening?

内容宽度能自适应每项的宽度

### Additional comments

_(empty)_

**Comment by songyuchen415** [comment]
希望可以支持

**Comment by wuxueqin** [comment]
收到谢谢、

**Comment by wanglyaaa** [comment]
请问这个问题解决了吗？

**Comment by wuxueqin** [comment]
收到谢谢、

**Comment by wuxueqin** [comment]
没有





------------------ 原始邮件 ------------------
发件人: wangly ***@***.***&gt;
发送时间: 2023年11月2日 14:11
收件人: element-plus/element-plus ***@***.***&gt;
抄送: wuxueqin ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [element-plus/element-plus] [Component] [select-v2] el-select-v2 下拉面板宽度不能自适应内容宽度 (Issue #12585)





 
请问这个问题解决了吗？

**Comment by kooriookami** [comment]
> 希望可以支持，不过看起来不好实现。v2是virtualized，只有显示范围内的元素被渲染了出来。如果随着上下滚动下拉面板宽度产生变化貌似也不是很友好

确实是这个原因，没办法计算一个合适的宽度。

**Comment by wuxueqin** [comment]
收到谢谢、

**Comment by Fraser818** [comment]
我也遇到这个问题了，输入框的宽度限制了下拉菜单的宽度，导致下拉选项不能展示完整。希望能加个配置项，感谢社区，感谢官方

**Comment by wuxueqin** [comment]
收到谢谢、
