### ISSUE TITLE
[Component] [form] Methods on ref are not callable in JavaScript

### ISSUE THREAD

**Issue by Astrisle** [element-plus/element-plus#12590]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome/112.0.0.0 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIHN0YXR1cy1pY29uXG4gICAgOnJ1bGVzPVwicnVsZXNcIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIk1ENVwiIHByb3A9XCJtZDVcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiB0eXBlPVwicGFzc3dvcmRcIiBhdXRvY29tcGxldGU9XCJvZmZcIiA6dmFsaWRhdGUtZXZlbnQ9XCJmYWxzZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzdWJtaXRGb3JtKGZvcm1SZWYpXCJcbiAgICAgICAgPlN1Ym1pdDwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Rm9ybShmb3JtUmVmKVwiPlJlc2V0PC9lbC1idXR0b24+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuICBcbmxldCBpbnB1dCA9IHJlZignJylcblxuY29uc3QgZm9ybVJlZiA9IHJlZigpXG5cbmZ1bmN0aW9uIGlzVmFsaWRNZDVIYXNoKGlucHV0KSB7XG4gIGNvbnN0IG1kNUhhc2hSZWdleCA9IC9eW2EtZjAtOV17MzJ9JC87XG4gIHJldHVybiBtZDVIYXNoUmVnZXgudGVzdChpbnB1dCk7XG59XG5cbmNvbnN0IHZhbGlkYXRlUGFzcyA9IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG4gIGlmICh2YWx1ZSA9PT0gJycpIHtcbiAgICBjYWxsYmFjayhuZXcgRXJyb3IoJ1BsZWFzZSBpbnB1dCB0aGUgbWQ1JykpXG4gIH0gZWxzZSBpZiAoIWlzVmFsaWRNZDVIYXNoKHZhbHVlKSkge1xuICAgICAgY2FsbGJhY2sobmV3IEVycm9yKCdpbnZhbGlkIG1kNScpKVxuICAgIH1cbn1cblxuXG5jb25zdCBydWxlcyA9IHJlZih7XG4gIG1kNTogW3sgdmFsaWRhdG9yOiB2YWxpZGF0ZVBhc3MsIHRyaWdnZXI6ICdibHVyJyB9XSxcbn0pXG5cbmNvbnN0IHN1Ym1pdEZvcm0gPSAoZm9ybUVsKSA9PiB7XG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBjb25zb2xlLmxvZygndmFsaWRhdGlvbiB0cmlnZ2VyZWQnKVxuICAgIGlmICh2YWxpZCkge1xuICAgICAgY29uc29sZS5sb2coJ3N1Ym1pdCEnKVxuICAgIH0gZWxzZSB7XG4gICAgICBjb25zb2xlLmxvZygnZXJyb3Igc3VibWl0IScpXG4gICAgICByZXR1cm4gZmFsc2VcbiAgICB9XG4gIH0pXG59XG5cbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWwpID0+IHtcbiAgZm9ybUVsLnJlc2V0RmllbGRzKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Type any string in the input box
2. Click on Reset
3. Click on Submit

### What is Expected?

- In step 2, the input box is cleared
- In step 3, the form validation is triggered and a failed result returned

### What is actually happening?

Nothing happens except "clicked" is logged to the console indicating the function bind to button clicks is in fact called

### Additional comments

It is not clear if this issue is reproducible in TypeScript. I am only using JavaScript as the project I am working on is a legacy project.

Another thing I've noticed here is if I remove `:validate-event="false"` from the input box, the `value` printed to console during validation is `undefined`. I am not sure if this is the right behaviour. I've also tried using `reactive` instead of `ref` for `v-model`, but the observed behaviour remains the same.

Thank you.

![image](https://user-images.githubusercontent.com/47962501/233970891-1b6ef5aa-ed5a-4040-a4b0-7a3a582f7ebf.png)

**Comment by btea** [comment]
Maybe you should bind parameters to the form first, you can refer to this [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIHN0YXR1cy1pY29uXG4gICAgOm1vZGVsPVwicGFyYW1zXCJcbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiTUQ1XCIgcHJvcD1cIm1kNVwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJwYXJhbXMubWQ1XCIgdHlwZT1cInBhc3N3b3JkXCIgYXV0b2NvbXBsZXRlPVwib2ZmXCIgOnZhbGlkYXRlLWV2ZW50PVwiZmFsc2VcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiXG4gICAgICAgID5TdWJtaXQ8L2VsLWJ1dHRvblxuICAgICAgPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCBwYXJhbXMgPSByZWFjdGl2ZSh7XG4gIG1kNTogJydcbn0pXG5cbmNvbnN0IGZvcm1SZWYgPSByZWYoKVxuXG5mdW5jdGlvbiBpc1ZhbGlkTWQ1SGFzaChpbnB1dCkge1xuICBjb25zdCBtZDVIYXNoUmVnZXggPSAvXlthLWYwLTldezMyfSQvO1xuICByZXR1cm4gbWQ1SGFzaFJlZ2V4LnRlc3QoaW5wdXQpO1xufVxuXG5jb25zdCB2YWxpZGF0ZVBhc3MgPSAocnVsZSwgdmFsdWUsIGNhbGxiYWNrKSA9PiB7XG4gIGNvbnNvbGUubG9nKHZhbHVlKVxuICBpZiAodmFsdWUgPT09ICcnKSB7XG4gICAgY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIG1kNScpKVxuICB9IGVsc2UgaWYgKCFpc1ZhbGlkTWQ1SGFzaCh2YWx1ZSkpIHtcbiAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcignaW52YWxpZCBtZDUnKSlcbiAgICB9XG59XG5cblxuY29uc3QgcnVsZXMgPSByZWYoe1xuICBtZDU6IFt7IHZhbGlkYXRvcjogdmFsaWRhdGVQYXNzLCB0cmlnZ2VyOiAnYmx1cicgfV0sXG59KVxuXG5jb25zdCBzdWJtaXRGb3JtID0gKGZvcm1FbCkgPT4ge1xuICBmb3JtRWwudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ3ZhbGlkYXRpb24gdHJpZ2dlcmVkJylcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsKSA9PiB7XG4gIGZvcm1FbC5yZXNldEZpZWxkcygpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==).

**Comment by Astrisle** [comment]
> Maybe you should bind parameters to the form first, you can refer to this [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIHN0YXR1cy1pY29uXG4gICAgOm1vZGVsPVwicGFyYW1zXCJcbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiTUQ1XCIgcHJvcD1cIm1kNVwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJwYXJhbXMubWQ1XCIgdHlwZT1cInBhc3N3b3JkXCIgYXV0b2NvbXBsZXRlPVwib2ZmXCIgOnZhbGlkYXRlLWV2ZW50PVwiZmFsc2VcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiXG4gICAgICAgID5TdWJtaXQ8L2VsLWJ1dHRvblxuICAgICAgPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCBwYXJhbXMgPSByZWFjdGl2ZSh7XG4gIG1kNTogJydcbn0pXG5cbmNvbnN0IGZvcm1SZWYgPSByZWYoKVxuXG5mdW5jdGlvbiBpc1ZhbGlkTWQ1SGFzaChpbnB1dCkge1xuICBjb25zdCBtZDVIYXNoUmVnZXggPSAvXlthLWYwLTldezMyfSQvO1xuICByZXR1cm4gbWQ1SGFzaFJlZ2V4LnRlc3QoaW5wdXQpO1xufVxuXG5jb25zdCB2YWxpZGF0ZVBhc3MgPSAocnVsZSwgdmFsdWUsIGNhbGxiYWNrKSA9PiB7XG4gIGNvbnNvbGUubG9nKHZhbHVlKVxuICBpZiAodmFsdWUgPT09ICcnKSB7XG4gICAgY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIG1kNScpKVxuICB9IGVsc2UgaWYgKCFpc1ZhbGlkTWQ1SGFzaCh2YWx1ZSkpIHtcbiAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcignaW52YWxpZCBtZDUnKSlcbiAgICB9XG59XG5cblxuY29uc3QgcnVsZXMgPSByZWYoe1xuICBtZDU6IFt7IHZhbGlkYXRvcjogdmFsaWRhdGVQYXNzLCB0cmlnZ2VyOiAnYmx1cicgfV0sXG59KVxuXG5jb25zdCBzdWJtaXRGb3JtID0gKGZvcm1FbCkgPT4ge1xuICBmb3JtRWwudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ3ZhbGlkYXRpb24gdHJpZ2dlcmVkJylcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsKSA9PiB7XG4gIGZvcm1FbC5yZXNldEZpZWxkcygpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==).

Hmm..That is a bit strange, I am pretty sure I have tried this locally but it didn't work at all.
Anyways, it did fix it; thanks for your help!
