### ISSUE TITLE
[TypeScript] [All] 没有全局注册的element组件, 单个组件单独引用的时候出现类型错误

### ISSUE THREAD

**Issue by xjhxqza** [element-plus/element-plus#12605]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `114.0.5720.4`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsQnV0dG9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEVsQnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgY2xhc3M9XCJ3LVsxMDAlXVwiPmJ0bjI8L0VsQnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.全局不注册element-plus组件
2.使用方式
```
<script setup lang="ts">
import { ElButton } from 'element-plus'
</script>

<template>
  <ElButton type="primary" class="w-[100%]">btn2</ElButton>
</template>
```

### What is Expected?

正常使用

### What is actually happening?

出现类型报错 
报错信息
```
Argument of type '{ type: "primary"; class: string; }' is not assignable to parameter of type 'App<any> & Record<string, unknown> & Partial<{ readonly type: EpPropMergeType<StringConstructor, "" | "default" | "text" | "primary" | "success" | "warning" | "info" | "danger", unknown>; ... 12 more ...; readonly dark: boolean; }> & Omit<...>'.
  Type '{ type: "primary"; class: string; }' is missing the following properties from type 'App<any>': version, config, use, mixin, and 11 more.
```

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
see https://github.com/element-plus/element-plus/issues/12555
