### ISSUE TITLE
[Component] [select] select blur 事件无效

### ISSUE THREAD

**Issue by lrkor** [element-plus/element-plus#12603]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `win11 谷歌`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2YWx1ZSA9IHJlZignJylcblxuY29uc3QgYmx1ciA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coMTExKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgQGJsdXI9XCJibHVyKClcIj5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiMjIyMlwiIHZhbHVlPVwiNDQ0NFwiIC8+XG4gIDwvZWwtc2VsZWN0PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击不选选项可以正常触发blur 事件 但是选完新的选项就不会触发

### What is Expected?

blur事件可以正常触发

### What is actually happening?

blur事件不可以正常触发

### Additional comments

_(empty)_

**Comment by tolking** [comment]
This issue has been fixed, please try the latest version
