### ISSUE TITLE
[Component] [tree] tree

### ISSUE THREAD

**Issue by newbeedaly** [element-plus/element-plus#12618]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.3.4`
- Browser / OS: `edge最新版`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcbiAgPGJ1dHRvbiBAY2xpY2s9XCJvbkNobmFnZVwiPmNoYW5nZTwvYnV0dG9uPlxuICA8ZWwtdHJlZVxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIG5vZGUta2V5PVwiaWRcIlxuICAgIDpkZWZhdWx0LWV4cGFuZGVkLWtleXM9XCJbMiwgM11cIlxuICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cImNoZWNrZWRcIlxuICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBcbmltcG9ydCB7cmVmfSBmcm9tIFwidnVlXCJcbmNvbnN0IGRlZmF1bHRQcm9wcyA9IHtcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGxhYmVsOiAnbGFiZWwnLFxufVxuY29uc3QgY2hlY2tlZCA9IHJlZihbNV0pXG5jb25zdCBvbkNobmFnZSA9ICgpPT57XG4gIGNoZWNrZWQudmFsdWUgPSBjaGVja2VkLnZhbHVlLmluY2x1ZGVzKDUpID8gWzZdIDogWzVdXG59XG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDQsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDksXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAxMCxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTInLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAyJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNSxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiA2LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDcsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogOCxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0yJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<template>
  
  <button @click="onChnage">change</button>
  <el-tree
    :data="data"
    show-checkbox
    node-key="id"
    :default-expanded-keys="[2, 3]"
    :default-checked-keys="checked"
    :props="defaultProps"
  />
</template>

<script lang="ts" setup>
  
import {ref} from "vue"
const defaultProps = {
  children: 'children',
  label: 'label',
}
const checked = ref([5])
const onChnage = ()=>{
  checked.value = checked.value.includes(5) ? [6] : [5]
}
const data = [
  {
    id: 1,
    label: 'Level one 1',
    children: [
      {
        id: 4,
        label: 'Level two 1-1',
        children: [
          {
            id: 9,
            label: 'Level three 1-1-1',
          },
          {
            id: 10,
            label: 'Level three 1-1-2',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    label: 'Level one 2',
    children: [
      {
        id: 5,
        label: 'Level two 2-1',
      },
      {
        id: 6,
        label: 'Level two 2-2',
      },
    ],
  },
  {
    id: 3,
    label: 'Level one 3',
    children: [
      {
        id: 7,
        label: 'Level two 3-1',
      },
      {
        id: 8,
        label: 'Level two 3-2',
      },
    ],
  },
]
</script>

### What is Expected?

切换选择时，在 5 和 6 勾选框回来勾选

### What is actually happening?

没有销毁，只有追加

### Additional comments

修复后请发邮件通知我，谢谢 newbeedaly@163.com

**Comment by newbeedaly** [comment]
<template>
  
  <button @click="onChnage">change</button>
  <el-tree
    :data="data"
    show-checkbox
    node-key="id"
    :default-expanded-keys="[2, 3]"
    :default-checked-keys="checked"
    :props="defaultProps"
  />
</template>

<script lang="ts" setup>
  
import {ref} from "vue"
const defaultProps = {
  children: 'children',
  label: 'label',
}
const checked = ref([5])
const onChnage = ()=>{
  checked.value = checked.value.includes(5) ? [6] : [5]
}
const data = [
  {
    id: 1,
    label: 'Level one 1',
    children: [
      {
        id: 4,
        label: 'Level two 1-1',
        children: [
          {
            id: 9,
            label: 'Level three 1-1-1',
          },
          {
            id: 10,
            label: 'Level three 1-1-2',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    label: 'Level one 2',
    children: [
      {
        id: 5,
        label: 'Level two 2-1',
      },
      {
        id: 6,
        label: 'Level two 2-2',
      },
    ],
  },
  {
    id: 3,
    label: 'Level one 3',
    children: [
      {
        id: 7,
        label: 'Level two 3-1',
      },
      {
        id: 8,
        label: 'Level two 3-2',
      },
    ],
  },
]
</script>

**Comment by newbeedaly** [comment]
此处应该对原有已勾选的清空
![lQLPJx0cP1HakK7NAv3NA-mw_y33dUWrwvgEQMGLCECDAA_1001_765](https://user-images.githubusercontent.com/30494444/234510748-374060ba-8590-42a3-999b-2483a1168fbd.png)

**Comment by yj-liuzepeng** [comment]
没有修复，怎么关了

**Comment by newbeedaly** [comment]
> 没有修复，怎么关了

我还以为你改好了呢

**Comment by yj-liuzepeng** [comment]
哈哈，只是提了个pr，还没有被审核
