### ISSUE TITLE
[Bug Report] Col does not define the props tag

### ISSUE THREAD

**Issue by goodtong** [element-plus/element-plus#1262]
### Element Plus version
1.0.1-beta.24

### OS/Browsers version
Win10 / Chrome

### Vue version
3.0.5

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
https://github.com/element-plus/element-plus/blob/dev/packages/col/src/col.ts

### What is Expected?
Col does not define the props tag

### What is actually happening?
Col does not define the props tag

**Comment by zazzaz** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/10731096/104265192-04768280-54c8-11eb-8c3b-4d5ee58c15d6.png">
you can check here as a reference

**Comment by Ryan2128** [comment]
Maybe he means this. The Col component lacks props named tag.

![image](https://user-images.githubusercontent.com/33176053/104267264-3e498800-54cc-11eb-932e-0e683a780c22.png)
