### ISSUE TITLE
[feature request] internationalized dayjs locale config incorrect apply  when use mulit dayjs packages

### ISSUE THREAD

**Issue by Akimotorakiyu** [element-plus/element-plus#1263]
### Existing Component
Yes

### Component Name
date-picker

### Description
when install different  dayjs ，
```
import 'dayjs/locale/zh-cn'
```
the locale config will not be apply on the dayjs which not used in element-plus 

![图片](https://user-images.githubusercontent.com/31165554/104416393-b0929900-55ae-11eb-8f1e-8afbd170bf64.png)

**Comment by zazzaz** [comment]
Hi, you can check the document here about how to set Day.js locale 

https://element-plus.org/#/en-US/component/i18n#set-day.js-locale

**Comment by Ryan2128** [comment]
Maybe he means this. The Col component lacks props named tag.

![image](https://user-images.githubusercontent.com/33176053/104267003-bf544f80-54cb-11eb-8fb8-e6c5b344d4a4.png)

**Comment by Akimotorakiyu** [comment]
> Hi, you can check the document here about how to set Day.js locale
> 
> https://element-plus.org/#/en-US/component/i18n#set-day.js-locale

@zazzaz  did you understand what say? I mean that document method is not work 


current I use method below:
```ts

import zhLocale from 'element-plus/es/locale/lang/zh-cn'
import { use } from 'element-plus/es/locale/index'
import zhcn from 'dayjs/locale/zh-cn'

// ...

app.use(Element, {
  locale: zhLocale,
})

// use this
use({ name: zhcn })
```

**Comment by zazzaz** [comment]
The code blew should be working as expected.
```
app.use(Element, {
  locale: zhLocale,        // so not really work for element  dayjs , 
})
```

Can you please provide a demo for us to check the code?

**Comment by Akimotorakiyu** [comment]
@zazzaz please wait a moment, I'm working!
I will update , please wait

**Comment by Akimotorakiyu** [comment]
@zazzaz   reproduce [element-plus-dayjs-issue-reproduce](https://github.com/Akimotorakiyu/element-plus-dayjs-issue-reproduce)

**Comment by zazzaz** [comment]
Checked your repo, you have installed two Day.js in your project one in node_module/dayjs and one node_module/element-plsu/dayjs, please make sure only one dayjs installed under node_module/dayjs

**Comment by Akimotorakiyu** [comment]
@zazzaz This may cause confuse to user. I take 2 hours to analysis element-plus & dayjs source code to find this quesstion.

**Comment by zazzaz** [comment]
we will see if we could add some note to our document.

**Comment by Akimotorakiyu** [comment]
@zazzaz may you add `import 'dayjs/locale/zh-cn'` to `element-plus/es/locale/lang/zh-cn` file?

**Comment by zazzaz** [comment]
this is hard, cause you can't tell how our users use element plus. Like, refer it directly from a CDN script.

**Comment by Akimotorakiyu** [comment]
@zazzaz this issue should be close by me? or wait for you colse when the document has be updated?

**Comment by zazzaz** [comment]
Thanks, marked here https://github.com/element-plus/element-plus/issues/540
