### ISSUE TITLE
[Bug Report] The thead checkbox is not aligned.

### ISSUE THREAD

**Issue by canvascat** [element-plus/element-plus#1265]
### Element Plus version

1.0.1-beta.24

### OS/Browsers version

Win10 / Chrome

### Vue version

3.0.5

### Reproduction Link

https://element-plus.org/#/zh-CN/component/table#duo-xuan

### Steps to reproduce

![image](https://user-images.githubusercontent.com/31235016/104288788-3bae5900-54f3-11eb-9d54-5c64c575619d.png)
![image](https://user-images.githubusercontent.com/31235016/104288832-4c5ecf00-54f3-11eb-976b-a9e67a4d8644.png)

### What is Expected?

All checkbox should be vertically aligned.

### What is actually happening?

The header checkbox is not aligned.
The style of `thead .el-table-column--selection .cell` is overridden.

**Comment by Ryan2128** [comment]
cc @justwiner
