### ISSUE TITLE
[Style] 组件size属性与组件实际渲染大小不一样，与官网显示不一致

### ISSUE THREAD

**Issue by willianfu** [element-plus/element-plus#12653]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.4`
- Browser / OS: `edge、chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-date-picker`
- `el-button`

### Reproduction Link

[CodePen](https://codepen.io/iamkun/pen)

### Steps to reproduce

就拿官网的input组件文档里面的实例举例，点文档示例的在线运行，在codepan里面的size都不一致
![image](https://user-images.githubusercontent.com/25615627/235092073-974cbe08-4dea-46ed-a79e-dd4b3a810a6a.png)

### What is Expected?

 large、medium、small、 mini ，四个组件依次变小

### What is actually happening?

mini比small还大，medium和mini一样大

### Additional comments

_(empty)_

**Comment by wzc520pyfm** [comment]
The component's size property support three values: `large` `default` `small`.
