### ISSUE TITLE
[Bug Report] After selecting the option, popover disappears automatically

### ISSUE THREAD

**Issue by stevieyu** [element-plus/element-plus#1266]
### Element Plus version
1.0.1-beta.24

### OS/Browsers version
mac 11.2 / chrome 78

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/dgjx/pen/XWjxbwL

### Steps to reproduce
el-select In the popover, choose an option at will

### What is Expected?
popover stays there

### What is actually happening?
popover disappeared

**Comment by kooriookami** [comment]
Because the option of select is outside of the popover. You can use `manual` trigger to control the popover.

**Comment by stevieyu** [comment]
@kooriookami But element-ui's popover does not have such a thing, you can see the link below https://codepen.io/dgjx/pen/zYKmJaP

**Comment by zhixialihan** [comment]
select 使用 visible-change事件  this.$refs.popover.show()，解决popver消失

**Comment by AndrewSparrowww** [comment]
@kooriookami What is the reason under this topic to not migrate Element-UI functionality? It's common practice to have nested popovers, select or dropdown inside of popover? This works extremely well in Vue2

**Comment by kooriookami** [comment]
> @kooriookami What is the reason under this topic to not migrate Element-UI functionality? It's common practice to have nested popovers, select or dropdown inside of popover? This works extremely well in Vue2
> 
> cc @zhazhanitian

Well, we redid the popover component, so the logic could be different, and we need a discussion about this.

**Comment by yoshida-m-3** [comment]
I'm having trouble with the same problem.
Is this problem likely to be resolved?

**Comment by youngshuyu** [comment]
> The issue has so long time no replying. Long story short, please setting `false` to `popper-append-to-body` that it is props of `el-select`. It's works for me.

It's useful! thanks a lot! 👍

**Comment by sebdei** [comment]
> The issue has so long time no replying. Long story short, please setting `false` to `popper-append-to-body` that it is props of `el-select`. It's works for me.

Unfortunately, this solution causes other issues. In my case, vue-i18n throws errors.
<img width="237" alt="Screenshot 2022-01-17 at 16 28 55" src="https://user-images.githubusercontent.com/23342317/149798029-5954a941-24f9-4faa-93fe-7a2490e8f81d.png">

**Comment by ixtiyorjon** [comment]
`:teleported="false"`
`<el-select :teleported="false"></el-select>`
it worked for me

**Comment by Dazaer** [comment]
Has this been investigated yet to assess how hard this would be to fix? It completely ruins the component in my case as we use the popover to open filters. Cannot have `el-select` in it which is crucial for filtering.

**Comment by tranthuybn** [comment]
> `:teleported="false"` `<el-select :teleported="false"></el-select>` it worked for me

thanks a lot !

**Comment by zhixiao-kooboo** [comment]
I also have the same problem with `popover` in `popover`

**Comment by alapeta** [comment]
Really, not being able to have interaction in popups (filtering, selecting, check boxing, etc) is very very annoying :-(
Guys, teleport=false is not the solution to these problems...
Any hope that it would be fixed soon?

**Comment by zhixiao-kooboo** [comment]
@alapeta 
I have found a workaround
1. the main popover is set to manual mode by using `:visible="visible"` and it also has a directive `v-click-outside="onClickOutside"`
     1. onClickOutside will set the `visible` to false if the inside popover is not visible. Because clicking on the inside popover will also trigger this event.
2. the inside popover (eg filter) is set to `trigger="click"` mode

**Comment by alapeta** [comment]
Nice try @zhixiao-kooboo , thanks :-) 
But it is still only workaround. Also highly dependent on popover element used inside other components: select, autocomplete, cascader - each one has different, not consistent API for popover options :-(

**Comment by kooriookami** [comment]
Please set `:teleported="false"`.
