### ISSUE TITLE
[Bug Report] Can el-checkbox-group bind the value returned by setup?

### ISSUE THREAD

**Issue by ChainsDW** [element-plus/element-plus#1267]
### Element Plus version
1.0.1-beta.24

### OS/Browsers version
mac/chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/chainsdw/pen/VwKEvOX

### Steps to reproduce
如果把绑定值改为data里的是可以的，setup里的值没有反应

### What is Expected?
is that a problem?

### What is actually happening?
1

**Comment by Ryan2128** [comment]
Please read vue 3 docs.

The `reactive` can only accept a object. If you want to make only a array reactive, you should use `ref`.

![image](https://user-images.githubusercontent.com/33176053/104303723-66091200-5505-11eb-9b99-30060e5f0bd8.png)
