### ISSUE TITLE
[Docs] [backtop] Missing Bac-to-top docs

### ISSUE THREAD

**Issue by Ahmard** [element-plus/element-plus#12679]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Brave Browser`
- Build Tool: `Other`

### Related Component

- `el-backtop`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/backtop.html)

### Steps to reproduce

Visit https://element-plus.org/en-US/component/backtop.html

### What is Expected?

To see BacToTop documentation

### What is actually happening?

Missing page

### Additional comments

Fix it please

**Comment by wzc520pyfm** [comment]
You mean the backtop document page is missing? But when I open the link, it's fine.Can you describe it in more detail?

**Comment by Ahmard** [comment]
I see now it's working.
I will go ahead and close this.
Thanks.
