### ISSUE TITLE
[Component] [table-column] table-column 组件的自定义插槽内容在渲染时会先创建一个隐藏的 div 元素

### ISSUE THREAD

**Issue by Hongbusi** [element-plus/element-plus#12688]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 112.0.5615.137 / macOS 13.3.1`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8VGFibGU+XG4gICAgPHRlbXBsYXRlICN0ZXN0PlxuICAgIFx0PGVsLXN3aXRjaFxuICAgICAgICA6YWN0aXZlLXZhbHVlPVwiMVwiXG4gICAgICAgIDppbmFjdGl2ZS12YWx1ZT1cIjJcIlxuICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgIC8+XG4gICAgPC90ZW1wbGF0ZT5cdFxuICA8L1RhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCBUYWJsZSBmcm9tICcuL1RhYmxlLnZ1ZSdcbiAgXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoKSA9PiB7XG5cdGNvbnNvbGUubG9nKCdhcHAgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJUYWJsZS52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIHRlc3RcbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIDphY3RpdmUtdmFsdWU9XCIxXCJcbiAgICAgICAgICA6aW5hY3RpdmUtdmFsdWU9XCIyXCJcbiAgICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgICAgLz5cbiAgICAgICAgPHNsb3QgbmFtZT1cInRlc3RcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXSlcblxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKCkgPT4ge1xuXHRjb25zb2xlLmxvZygndGFibGUgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==)

### Steps to reproduce

定义一个 `Table` 组件：

``` vue
<template>
  <el-table>
    <el-table-column>
      <template #default>
        <slot name="test" />
      </template>
    </el-table-column>
  </el-table>
</template>
```

在使用 `Table` 的过程中，`test` 插槽的内容如果是一个 `switch` 组件，并设置了 `active-value` 和 `inactive-value` 属性，且传入的 `modelValue` 与这两个值都不匹配，在初始化的时候就会执行一次 `change` 事件：

``` vue
<template>
  <Table>
    <template #test>
      <el-switch
        :active-value="1"
        :inactive-value="2"
        @change="handleChange"
      />
    </template>	
  </Table>
</template>

<script lang="ts" setup>
import Table from './Table.vue'
  
const handleChange = () => {
  console.log('app - test')
}
</script>
```

问题原因：在初始化的时候，`test` 插槽的内容会被提前构建一次，并生成隐藏的元素：

``` html
<div class="hidden-columns">
  <div>
    ...
  </div>
</div>
```

### What is Expected?

初始化的时候不会执行 `switch` 的 `change` 事件。

### What is actually happening?

在初始化的时候触发一次 `change` 事件。

### Additional comments

还有一个疑惑：为什么要创建一个隐藏的元素，用来存放一部分 `childNode`？

感谢你的回答~

**Comment by Hongbusi** [comment]
@chenxch Thank you~

**Comment by Hongbusi** [comment]
导致遇到的问题原因是相似的，但最终的问题是不一样的。

问题：在使用 Table 的过程中，test 插槽的内容如果是一个 switch 组件，并设置了 active-value 和 inactive-value 属性，且传入的 modelValue 与这两个值都不匹配，**在初始化的时候就会执行一次 change 事件**。详细复现可见[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8VGFibGU+XG4gICAgPHRlbXBsYXRlICN0ZXN0PlxuICAgIFx0PGVsLXN3aXRjaFxuICAgICAgICA6YWN0aXZlLXZhbHVlPVwiMVwiXG4gICAgICAgIDppbmFjdGl2ZS12YWx1ZT1cIjJcIlxuICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgIC8+XG4gICAgPC90ZW1wbGF0ZT5cdFxuICA8L1RhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCBUYWJsZSBmcm9tICcuL1RhYmxlLnZ1ZSdcbiAgXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoKSA9PiB7XG5cdGNvbnNvbGUubG9nKCdhcHAgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJUYWJsZS52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIHRlc3RcbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIDphY3RpdmUtdmFsdWU9XCIxXCJcbiAgICAgICAgICA6aW5hY3RpdmUtdmFsdWU9XCIyXCJcbiAgICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgICAgLz5cbiAgICAgICAgPHNsb3QgbmFtZT1cInRlc3RcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXSlcblxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKCkgPT4ge1xuXHRjb25zb2xlLmxvZygndGFibGUgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==)

期望：避免在初始化的时候执行一次 change 事件。

很抱歉没有突出重点。 @chenxch

**Comment by cyx447653591** [comment]
怎么解决？

**Comment by Hongbusi** [comment]
还没解决。@cyx447653591

**Comment by cyx447653591** [comment]
> 还没解决。@cyx447653591

好像可以了，要赋值初始值

**Comment by Hongbusi** [comment]
但通过 table-column 插槽的方式还是有问题的。[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8VGFibGU+XG4gICAgPHRlbXBsYXRlICN0ZXN0PlxuICAgIFx0PGVsLXN3aXRjaFxuICAgICAgICA6YWN0aXZlLXZhbHVlPVwiMVwiXG4gICAgICAgIDppbmFjdGl2ZS12YWx1ZT1cIjJcIlxuICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgIC8+XG4gICAgPC90ZW1wbGF0ZT5cdFxuICA8L1RhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCBUYWJsZSBmcm9tICcuL1RhYmxlLnZ1ZSdcbiAgXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoKSA9PiB7XG5cdGNvbnNvbGUubG9nKCdhcHAgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJUYWJsZS52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIHRlc3RcbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIDphY3RpdmUtdmFsdWU9XCIxXCJcbiAgICAgICAgICA6aW5hY3RpdmUtdmFsdWU9XCIyXCJcbiAgICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgICAgLz5cbiAgICAgICAgPHNsb3QgbmFtZT1cInRlc3RcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXSlcblxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKCkgPT4ge1xuXHRjb25zb2xlLmxvZygndGFibGUgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==) @cyx447653591

**Comment by userzeor** [comment]
请问这个问题解决了吗？ @Hongbusi

**Comment by Hongbusi** [comment]
> 请问这个问题解决了吗？ @Hongbusi

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8VGFibGU+XG4gICAgPHRlbXBsYXRlICN0ZXN0PlxuICAgIFx0PGVsLXN3aXRjaFxuICAgICAgICA6YWN0aXZlLXZhbHVlPVwiMVwiXG4gICAgICAgIDppbmFjdGl2ZS12YWx1ZT1cIjJcIlxuICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgIC8+XG4gICAgPC90ZW1wbGF0ZT5cdFxuICA8L1RhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCBUYWJsZSBmcm9tICcuL1RhYmxlLnZ1ZSdcbiAgXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoKSA9PiB7XG5cdGNvbnNvbGUubG9nKCdhcHAgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJUYWJsZS52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIHRlc3RcbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIDphY3RpdmUtdmFsdWU9XCIxXCJcbiAgICAgICAgICA6aW5hY3RpdmUtdmFsdWU9XCIyXCJcbiAgICAgICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgICAgLz5cbiAgICAgICAgPHNsb3QgbmFtZT1cInRlc3RcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXSlcblxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKCkgPT4ge1xuXHRjb25zb2xlLmxvZygndGFibGUgLSB0ZXN0Jylcbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==) 看样子还没有解决。

**Comment by Jackliu007888** [comment]
感觉是 switch  组件设计有问题，不是人为操作为什么触发更新事件

**Comment by diudiudiuu** [comment]
2024年了,问题解决了吗

**Comment by wan-kong** [comment]
2025年了，问题解决了吗

**Comment by skylingfly** [comment]
2025年9月1日依然没解决
