### ISSUE TITLE
[Docs] [switch] 翻译出错

### ISSUE THREAD

**Issue by HammCn** [element-plus/element-plus#12681]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-switch`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/switch.html#%E4%BA%8B%E4%BB%B6)

### Steps to reproduce

off 状态时的背景颜色(已废弃，使用 CSS var --el-switch-of-color )

### What is Expected?

off 状态时的背景颜色(已废弃，使用 CSS var --el-switch-off-color )

### What is actually happening?

off 状态时的背景颜色(已废弃，使用 CSS var --el-switch-of-color )

### Additional comments

https://crowdin.com/translate/element-plus/891/en-zhcn#81936

**Comment by btea** [comment]
谢谢反馈，翻译已修改。
