### ISSUE TITLE
[select-v2] Select V2 虚拟列表选择器 -创建临时选项，搜狗输入法中文输入，切换成英文时，没有把输入的内容带入到input中

### ISSUE THREAD

**Issue by cobratyt** [element-plus/element-plus#12684]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.3.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select-v2.html#%E5%88%9B%E5%BB%BA%E4%B8%B4%E6%97%B6%E9%80%89%E9%A1%B9)

### Steps to reproduce

创建临时选项时使用搜狗输入法中文输入内容，在选择中文时shift切换中英文输入

### What is Expected?

切换输入法能正确的把内容带入input

### What is actually happening?

输入的内容没有带入input中

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
目前没有此问题
