### ISSUE TITLE
[Style] [button, button-group] 设置 --el-color-primary后button的hover颜色没变

### ISSUE THREAD

**Issue by zhang19980518** [element-plus/element-plus#12686]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 112.0.5615.137/mac 13.0.1`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-button-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPuS9oOWlvTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICA6cm9vdHtcbiAgICAtLWVsLWNvbG9yLXByaW1hcnk6IGdyZWVuICFpbXBvcnRhbnQ7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
</script>

<template>
  <h1>{{ msg }}</h1>
  <el-input v-model="msg" />

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
  <el-button type="primary">你好</el-button>
</template>

<style>
  :root{
    --el-color-primary: green !important;
  }
</style>

### What is Expected?

hover的颜色应该改变

### What is actually happening?

只有按钮颜色改变,当鼠标悬浮与按钮之上时,颜色还是原来默认主题色的

### Additional comments

没有

**Comment by btea** [comment]
This is normal, if you want to customize the color, you can refer to this [document](https://element-plus.org/zh-CN/guide/theming.html).
