### ISSUE TITLE
[Docs] [All] 官网文档炸了

### ISSUE THREAD

**Issue by ealldy** [element-plus/element-plus#12707]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.0-beta.4`
- Element Plus Version: `2.3.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html)

### Steps to reproduce

打开链接，发现报错404.

### What is Expected?

能看到正常的文档

### What is actually happening?

多个组件的文档打不开

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
> 官网文档非常不稳定，时常打不开，很抓狂

可以访问https://element-plus.org/zh-CN/#/zh-CN

**Comment by chenxch** [comment]
或者https://cn.element-plus.org/zh-CN/

**Comment by lyxxxh** [comment]
![image](https://github.com/element-plus/element-plus/assets/35553218/30cbd733-43fc-42bf-aabc-f48530fef95f)

`gitee` 的令人无语
