### ISSUE TITLE
[Component] [table, table-column] 在使用CDN的Element Plus时，表格中的每一列都会独占一行，导致显示效果错乱

### ISSUE THREAD

**Issue by yu0A** [element-plus/element-plus#12702]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 113.0.5672.63`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Link](单个HTML文件，无需链接)

### Steps to reproduce

直接打开以下html即可复现问题：

### What is Expected?

表格中的每行可以显示多个列

### What is actually happening?

表格中的每行只能显示一个列

### Additional comments

_(empty)_

**Comment by yu0A** [comment]
GitHub的编辑器不能正确显示HTML，它会吃掉<body></body>。您可以留个邮箱，我把html发过去

**Comment by yu0A** [comment]
body /body

**Comment by yu0A** [comment]
或者，您把\`去掉即可得到我提到的html

`<!DOCTYPE html>`
`<html>`
``
`<head>`
`    <meta charset="utf-8">`
`    <meta name="viewport" content="width=device-width, initial-scale=1.0">`
`    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`
`    <meta name="title" content="">`
`    <meta name="description" content="">`
`    <meta name="keywords" content="">`
`    <title></title>`
``
`        <!-- Import style -->`
`        <link rel="stylesheet" href="//unpkg.com/element-plus/dist/index.css" />`
`        <!-- Import Vue 3 -->`
`        <script src="//unpkg.com/vue@3"></script>`
`        <!-- Import component library -->`
`        <script src="//unpkg.com/element-plus"></script>`
``
`</head>`
``
`<body>`
`    <div id="app" class="fclass">`
`        <el-table :data="tableData" :border="true" style="width: 100%">`
`            <el-table-column prop="date" label="Date" width="180" />`
`            <el-table-column prop="name" label="Name" width="180" />`
`            <el-table-column prop="address" label="Address" />`
`        </el-table>`
`    </div>`
`    <script src="" async defer></script>`
`    <script>`
`        const { createApp } = Vue`
``
`        createApp({`
`            data() {`
`                return {`
`                    message: 'Hello Vue!',`
`                    User: { date: "Fiat", name: 500, address: "white" },`
`                    tableRowClassName({ row, rowIndex, }) {`
`                        if (rowIndex === 1) {`
`                            return 'warning-row'`
`                        } else if (rowIndex === 3) {`
`                            return 'success-row'`
`                        }`
`                        return ''`
`                    },`
`                    tableData: [`
`                        {`
`                            date: '2016-05-03',`
`                            name: 'Tom',`
`                            address: 'No. 189, Grove St, Los Angeles',`
`                        },`
`                        {`
`                            date: '2016-05-02',`
`                            name: 'Tom',`
`                            address: 'No. 189, Grove St, Los Angeles',`
`                        },`
`                        {`
`                            date: '2016-05-04',`
`                            name: 'Tom',`
`                            address: 'No. 189, Grove St, Los Angeles',`
`                        },`
`                        {`
`                            date: '2016-05-01',`
`                            name: 'Tom',`
`                            address: 'No. 189, Grove St, Los Angeles',`
`                        },`
`                    ]`
`                }`
`            }`
`        }).use(ElementPlus).mount('#app')`
``
``
``
`    </script>`
``
`    <style>`
`        .el-table .warning-row {`
`            --el-table-tr-bg-color: var(--el-color-warning-light-9);`
`        }`
``
`        .el-table .success-row {`
`            --el-table-tr-bg-color: var(--el-color-success-light-9);`
`        }`
``
`        .el-table th.gutter {`
`            display: table-cell !important;`
`        }`
`    </style>`
`</body>`
``
`</html>`

**Comment by yu0A** [comment]
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="title" content="">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <title></title>

    <!-- Import style -->
    <link rel="stylesheet" href="//unpkg.com/element-plus/dist/index.css" />
    <!-- Import Vue 3 -->
    <script src="//unpkg.com/vue@3"></script>
    <!-- Import component library -->
    <script src="//unpkg.com/element-plus"></script>

</head>

<body>
    <div id="app" class="fclass">
        <el-table :data="tableData" :border="true" style="width: 100%">
            <el-table-column prop="date" label="Date" width="180" />
            <el-table-column prop="name" label="Name" width="180" />
            <el-table-column prop="address" label="Address" />
        </el-table>
    </div>
    <script src="" async defer></script>
    <script>
        const { createApp } = Vue

        createApp({
            data() {
                return {
                    message: 'Hello Vue!',
                    User: { date: "Fiat", name: 500, address: "white" },
                    tableRowClassName({ row, rowIndex, }) {
                        if (rowIndex === 1) {
                            return 'warning-row'
                        } else if (rowIndex === 3) {
                            return 'success-row'
                        }
                        return ''
                    },
                    tableData: [
                        {
                            date: '2016-05-03',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-02',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-04',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-01',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                    ]
                }
            }
        }).use(ElementPlus).mount('#app')



    </script>

    <style>
        .el-table .warning-row {
            --el-table-tr-bg-color: var(--el-color-warning-light-9);
        }

        .el-table .success-row {
            --el-table-tr-bg-color: var(--el-color-success-light-9);
        }

        .el-table th.gutter {
            display: table-cell !important;
        }
    </style>
</body>

</html>
```

**Comment by plainheart** [comment]
不要使用自闭标签，参见 [FAQ](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)

**Comment by yu0A** [comment]
> 不要使用自闭标签，参见 [FAQ](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)

改为正常的标签写法之后，表格显示错乱问题得到解决。

**Comment by chenxch** [comment]
@yu0A
