### ISSUE TITLE
[Component][pagination,select,select-v2] 下拉选项在全屏中不显示

### ISSUE THREAD

**Issue by catkinmu** [element-plus/element-plus#12709]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Microsoft Edge 版本 106.0.1370.42 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-pagination`
- `el-select`
- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aHIgY2xhc3M9XCJteS00XCIgLz5cbiAgIDxlbC1idXR0b24gQGNsaWNrPVwiZnVsbHNyZWVuXCI+XG4gICAgXHR0b2dnbGUgZnVsbHNjcmVlblxuICAgIDwvZWwtYnV0dG9uPlxuXHQ8ZGl2IHJlZj1cIndyYXBcIj5cbiAgICAgPGVsLXBhZ2luYXRpb25cbiAgICAgICAgdi1tb2RlbDpjdXJyZW50LXBhZ2U9XCJjdXJyZW50UGFnZVwiXG4gICAgICAgIHYtbW9kZWw6cGFnZS1zaXplPVwicGFnZVNpemVcIlxuICAgICAgICA6cGFnZS1zaXplcz1cIlsxMDAsIDIwMCwgMzAwLCA0MDBdXCJcbiAgICAgICAgbGF5b3V0PVwidG90YWwsIHNpemVzLCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyXCJcbiAgICAgICAgOnRvdGFsPVwiNDAwXCJcbiAgICBcbiAgICAgIC8+XG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgdi1tb2RlbD1cInNlbGVcIlxuICAgICAgOm9wdGlvbnM9XCJcbiAgICAgICAgWy4uLkFycmF5KDUpLmtleXMoKV0ubWFwKGsgPT4gKHsgdmFsdWU6IChrKzEpLCBsYWJlbDogYCR7aysxfWAgfSkpXG4gICAgICBcIlxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG4gIFxuY29uc3Qgc2VsZSA9IHJlZigxKVxuXG5jb25zdCBjdXJyZW50UGFnZSA9IHJlZig0KVxuY29uc3QgcGFnZVNpemUgPSByZWYoMTAwKVxuY29uc3Qgd3JhcCA9IHJlZihudWxsKVxuY29uc3QgZnVsbHNyZWVuID0gKCkgPT4ge1xuICBpZiAod3JhcC52YWx1ZS5yZXF1ZXN0RnVsbHNjcmVlbikge1xuICAgIHdyYXAudmFsdWUucmVxdWVzdEZ1bGxzY3JlZW4oKVxuICB9XG4gIGlmICh3cmFwLnZhbHVlLndlYmtpdFJlcXVlc3RGdWxsc2NyZWVuKSB7XG5cdFx0d3JhcC52YWx1ZS53ZWJraXRSZXF1ZXN0RnVsbHNjcmVlbigpXG4gIH1cbiBcbn1cbjwvc2NyaXB0PlxuXG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 容器内使用select-v2, select，pagination组件
2. 增加按钮，使容器执行requestFullscreen相关Api，进行全屏展示
3. 交互select，发现选项不可选

### What is Expected?

select默认将teleported 置为false，或者pagination组件中select组件可配置

### What is actually happening?

select默认将teleported 置为 true ，且pagination组件中select组件不可配置

### Additional comments

发现之前有相同的issues，https://github.com/element-plus/element-plus/issues/9329

**Comment by ishowman** [comment]
@catkinmu 
- "select默认将teleported 置为 true "这个完全可以在你自己项目中设置为 false 来解决
- “或者pagination组件中select组件可配置”：pagination组件提供了 default 插槽，可以自己在项目中定制化一个分页组件来替换页码数的 selector
