### ISSUE TITLE
[bug report] element plus component CSS is missing when vuecli is not used

### ISSUE THREAD

**Issue by clark-cui** [element-plus/element-plus#1271]
### Element Plus version
1.0.1-beta.24

### OS/Browsers version
chrome v 87.0.4280.141

### Vue version
3.0.0

### Steps to reproduce
使用webpack初始化一个vue3项目，使用babel-plugin-component按需引入element-plus组件

### What is Expected?
我没有用vuecli初始化项目，使用webpack构建。项目可以正常运行，vue-loader能解析.vue文件，和其中的<style lang="scss">。但是引入的element-plus组件样式缺失了，猜测是webpack配置的问题。

### What is actually happening?
我看文档里有vuecli的引用示例，也有vite的引用示列。可否给一个用webpack构建的项目的引用示例呢？

**Comment by zazzaz** [comment]
yes 
https://github.com/element-plus/element-plus-starter

**Comment by clark-cui** [comment]
> yes 
> https://github.com/element-plus/element-plus-starter

Thank you for replying.but this reposity is built with vuecli.Is there a demo built nonuse vuecli?I mean  directly use webpack to build.

**Comment by zazzaz** [comment]
check this https://element-plus.org/#/en-US/component/quickstart#import-element-plus

**Comment by clark-cui** [comment]
thanks.I find the question.I use babel-plugin-import to import element-plus components.But my webpack.config.js hadn't use babel-loader to transpiling javascript.
There are two ways to fix it.
1:Fully import Element-plus.
```
//main.js
import ElementPlus from 'element-plus';
import 'element-plus/lib/theme-chalk/index.css';
```
2.On demand
check this https://element-plus.org/#/en-US/component/quickstart.
if you don't use vuecli.I mean directly use webpack to build.you need to install some package and add this code in webpack.config.js
```
//shell
npm install -D babel-loader @babel/core @babel/preset-env @babel/plugin-transform-runtime @babel/runtime
```


```
//webpack.config.js
module.exports={
module:{
rules:[  
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                  loader: 'babel-loader',
                  options: {
                    presets: ['@babel/preset-env'],
                    plugins: ['@babel/plugin-transform-runtime']

                  }
                }
              },]
}


```

**Comment by JeremyWuuuuu** [comment]
Closing since this is fixed.
