### ISSUE TITLE
[TypeScript] [tree] tree组件 TreeOptionProps的TS类型判断不对  disabled?: string | ((data: TreeNodeData, node: Node) => string);

### ISSUE THREAD

**Issue by GoodMorningaMe** [element-plus/element-plus#12722]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.46`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZSA6ZGF0YT1cImRhdGFcIiA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIiBAbm9kZS1jbGljaz1cImhhbmRsZU5vZGVDbGlja1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW50ZXJmYWNlIFRyZWUge1xuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGhhbmRsZU5vZGVDbGljayA9IChkYXRhOiBUcmVlKSA9PiB7XG4gIGNvbnNvbGUubG9nKGRhdGEpXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cblxuY29uc3QgZGVmYXVsdFByb3BzID0ge1xuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGRpc2FibGVkOiAoZGF0YTogYW55LCBub2RlOiBhbnkpPT57XG4gICAgICAgIHJldHVybiB0cnVlOyAvL3Rz5oql6ZSZICDkuI3og73lsIbnsbvlnovigJx7ZGlzYWJsZWQ6IChkYXRhOiBhbnksIG5vZGU6IGFueSkgPT4gYm9vbGVhbjsgfeKAneWIhumFjee7meexu+Wei+KAnFRyZWVPcHRpb25Qcm9wc+KAnSDlsZ7mgKfigJxkaXNhYmxlZOKAneeahOexu+Wei+S4jeWFvOWuueOAglxuICBcbiAgfVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<el-tree :data='data' :props="defaultProps">
设置props的disabled时ts检验不对

### What is Expected?

1、修改disabled的TS类型

### What is actually happening?

1、disabled不应该是string

### Additional comments

联系方式：809395593@qq.com 
有个疑问：请问为什么el-tree的属性show-checkbox为false时，不许设置节点的disabled; 我在node-click时阻止事件还是会出现，is-current选中的状态
![image](https://user-images.githubusercontent.com/34636081/236832473-2b590f98-751f-4eba-b334-c333913007fe.png)

**Comment by GoodMorningaMe** [comment]
截图是issue的图哈  我的疑问没有配置图片

**Comment by chenxch** [comment]
@GoodMorningaMe Hello, before asking questions, it is recommended to check the document description first, so that you may be able to answer quickly.

[tree-props](https://element-plus.org/en-US/component/tree.html#props)

**Comment by pcj725** [comment]
在数据源中添加了一个disabled属性，值的类型为boolean
`js
treeDataProps = {
  disabled: 'disabled'
}
`
