### ISSUE TITLE
[TypeScript] [message] Module '"element-plus"' has no exported member 'ElMessage'

### ISSUE THREAD

**Issue by BerniceYao** [element-plus/element-plus#12723]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `chrome 112.0.5615.137`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHsgcHJveHkgfTogYW55ID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbnByb3h5LiRtZXNzYWdlLmVycm9yKCdmYWlsZCcpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuXHQ8ZGl2PlxuICBlbGVtZW50LXBsdXNcbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJtYWluLnRzIjoiaW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSAndnVlJ1xuaW1wb3J0ICcuL3N0eWxlLmNzcydcbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzLCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCAnZWxlbWVudC1wbHVzL2Rpc3QvaW5kZXguY3NzJ1xuXG5jb25zdCBhcHAgPSBjcmVhdGVBcHAoQXBwKVxuYXBwLnVzZShFbGVtZW50UGx1cylcbmFwcC5jb25maWcuZ2xvYmFsUHJvcGVydGllcy4kbWVzc2FnZSA9IEVsTWVzc2FnZVxuXG5hcHAubW91bnQoJyNhcHAnKSIsIl9vIjp7fX0=)

### Steps to reproduce

在main.ts中引入ElMessage
import ElementPlus, { ElMessage } from 'element-plus'
会报错：Module '"element-plus"' has no exported member 'ElMessage'. 

### What is Expected?
<img width="572" alt="企业微信截图_3eb6d087-d150-4489-93e0-9524ffb0a958" src="https://user-images.githubusercontent.com/45138071/236839746-c878a88e-3fbd-4052-a522-17cb709247cc.png">

成功打包，不会报错

### What is actually happening?

error TS2614: Module '"element-plus"' has no exported member 'ElMessage'. Did you mean to use 'import ElMessage from "element-plus"' instead?

### Additional comments

_(empty)_

**Comment by paulohfsantos** [comment]
What's up?!!
how did u complete or solve this issue?
