### ISSUE TITLE
[Component] el-select配合el-drawer后无法正常弹出

### ISSUE THREAD

**Issue by tjucaokun** [element-plus/element-plus#12734]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-beta.5`
- Element Plus Version: `2.3.4`
- Browser / OS: `edge/ windows10`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-drawer`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHNpemU9XCJsYXJnZVwiIEBjaGFuZ2U9XCJ0YWJsZT10cnVlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICAgIDxlbC1kcmF3ZXJcbiAgICAgICAgICAgICAgIHYtbW9kZWw9XCJ0YWJsZVwiXG4gICAgICAgICAgICAgICB0aXRsZT1cIjFcIlxuICAgICAgICAgICAgICAgc2l6ZT1cIjUwJVwiXG4gICAgICAgICAgICAgICBhcHBlbmQtdG8tYm9keTp0cnVlXG4gICAgICAgICAgICAgICA+XG4gICAgPC9lbC1kcmF3ZXI+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5sZXQgdGFibGUgPSByZWYoZmFsc2UpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击select选项 完成后 再次点开select框 弹出drawer

### What is Expected?

修改后立刻弹出

### What is actually happening?

change el-select值后，再次点开 才弹出drawer框

### Additional comments

谢谢大家

**Comment by nszbf** [comment]
xd，你的代码真是离谱啊...不说写到里面了 就连属性都错了..

**Comment by tjucaokun** [comment]
> xd，你的代码真是离谱啊...不说写到里面了 就连属性都错了..

emmm 不好意思 没怎么写过前端，，请问这个是应该把drawer拿出来吗 然后哪个属性写错了呢，麻烦赐教，万分感谢

**Comment by ryuhangyeong** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgc2l6ZT1cImxhcmdlXCIgQGNoYW5nZT1cInRhYmxlPXRydWVcIj5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gICAgPGVsLWRyYXdlciBcbiAgICBcdHYtbW9kZWw9XCJ0YWJsZVwiXG4gICAgICB0aXRsZT1cIjFcIlxuICAgICAgc2l6ZT1cIjUwJVwiXG4gICAgPlxuICAgIDwvZWwtZHJhd2VyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxubGV0IHRhYmxlID0gcmVmKGZhbHNlKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

Better to get the el-drawer out of the el-select!

**Comment by tjucaokun** [comment]
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgc2l6ZT1cImxhcmdlXCIgQGNoYW5nZT1cInRhYmxlPXRydWVcIj5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gICAgPGVsLWRyYXdlciBcbiAgICBcdHYtbW9kZWw9XCJ0YWJsZVwiXG4gICAgICB0aXRsZT1cIjFcIlxuICAgICAgc2l6ZT1cIjUwJVwiXG4gICAgPlxuICAgIDwvZWwtZHJhd2VyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxubGV0IHRhYmxlID0gcmVmKGZhbHNlKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> Better to get the el-drawer out of the el-select!

get it! thank u very much!!
