### ISSUE TITLE
[Component] [select] ElSelect 异步 placeholder 属性的显示问题

### ISSUE THREAD

**Issue by Lionad-Morotar** [element-plus/element-plus#12735]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-beta.5`
- Element Plus Version: `2.3.4`
- Browser / OS: `Microsoft Edge 104.0.1293.63`
- Build Tool: `CDN`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIDpwbGFjZWhvbGRlcj1cInBsYWNlaG9sZGVyXCIgbXVsdGlwbGUgZmlsdGVyYWJsZSBmaXQtaW5wdXQtd2lkdGg+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIGNpdGllc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGNvbXB1dGVkLCByZWYsIG5leHRUaWNrLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHBsYWNlaG9sZGVyID0gcmVmKCdTZWxlY3QtU2VsZWN0LVNlbGVjdCcpXG5vbk1vdW50ZWQoYXN5bmMgKCkgPT4ge1xuICBhd2FpdCBuZXh0VGljaygpXG4gIHBsYWNlaG9sZGVyLnZhbHVlID0gJ+WPpuS4gOS4qiBwbGFjZWhvbGRlcidcbiAgXG4gIGxldCBpZHggPSAxXG4gIHNldEludGVydmFsKCgpID0+IHtcbiAgICBwbGFjZWhvbGRlci52YWx1ZSA9ICflj4jmmK/lj6bkuIDkuKogcGxhY2Vob2xkZXInICsgU3RyaW5nKGlkeCArKylcbiAgfSwgMTAwMClcbn0pXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3QgY2l0aWVzID0gW1xuICB7XG4gICAgdmFsdWU6ICdCZWlqaW5nJyxcbiAgICBsYWJlbDogJ0JlaWppbmcnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdTaGFuZ2hhaScsXG4gICAgbGFiZWw6ICdTaGFuZ2hhaScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ05hbmppbmcnLFxuICAgIGxhYmVsOiAnTmFuamluZycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0NoZW5nZHUnLFxuICAgIGxhYmVsOiAnQ2hlbmdkdScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ1NoZW56aGVuJyxcbiAgICBsYWJlbDogJ1NoZW56aGVuJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnR3Vhbmd6aG91JyxcbiAgICBsYWJlbDogJ0d1YW5nemhvdScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiU2VsZWN0SXRlbS52dWUiOiI8dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3Qgdi1iaW5kPVwiJGF0dHJzXCI+XG4gICAgPHNsb3QgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBzZXR1cD48L3NjcmlwdD4iLCJfbyI6e319)

### Steps to reproduce

1. 打开页面
2. 给 el-select 选中一项值
2. 等待几秒钟，观察 el-select 的占位文本的变化
3. 即使选了值，仍然会出现占位文本

### What is Expected?

选了值之后，占位文本不应该显示

### What is actually happening?

即使选了值，仍然出现了占位文本

### Additional comments

_(empty)_

**Comment by btea** [comment]
Fiexed by #11051
