### ISSUE TITLE
Setting the width to El date picker affects the style

### ISSUE THREAD

**Issue by 5454267364** [element-plus/element-plus#1274]
**给el-date-picker设置宽度会影响样式**

比如：
  <el-date-picker v-model="form.tenantInfo.effectEndTime" style="width: auto;" type="datetime"  placeholder="选择日期" />
   <el-date-picker v-model="dateRange" size="small" style="width: 240px" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期" />

  
![image](https://user-images.githubusercontent.com/48704489/104563263-654aba00-5684-11eb-8627-aa77a77c6c7a.png)
![image](https://user-images.githubusercontent.com/48704489/104563403-91663b00-5684-11eb-8c32-b48b17806f88.png)

  <el-date-picker v-model="form.tenantInfo.effectEndTime" style="width: auto;" type="datetime"  placeholder="选择日期" />
   <el-date-picker v-model="dateRange" size="small" style="width: 240px" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期" />

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz

**Comment by zazzaz** [comment]
will fix soon
