### ISSUE TITLE
[Component] [table-v2] el-table-v2 set Column width *  invalid

### ISSUE THREAD

**Issue by weklay** [element-plus/element-plus#12759]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-beta.5`
- Element Plus Version: `2.3.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table-v2`

### Reproduction Link

[CodePen](https://codepen.io/qq4154/pen/GRYxbXR)

### Steps to reproduce

columns set width

### What is Expected?

Set width to be valid

### What is actually happening?

Invalid width setting

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/39334071/ed801a92-cbfc-4436-90d5-72e628ed221c)

**Comment by btea** [comment]
You should set width on `el-table-column`, refer [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCI4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=).

**Comment by weklay** [comment]
I am using el-table-v2,  Not used el-table

**Comment by btea** [comment]
I misread, if you use `el-table-v2`, set the width in columns, refer to the [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtdjJcbiAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOndpZHRoPVwiNzAwXCJcbiAgICA6aGVpZ2h0PVwiNDAwXCJcbiAgICBmaXhlZFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGdlbmVyYXRlQ29sdW1ucyA9IChsZW5ndGggPSAxMCwgcHJlZml4ID0gJ2NvbHVtbi0nLCBwcm9wcz86IGFueSkgPT5cbiAgQXJyYXkuZnJvbSh7IGxlbmd0aCB9KS5tYXAoKF8sIGNvbHVtbkluZGV4KSA9PiAoe1xuICAgIC4uLnByb3BzLFxuICAgIGtleTogYCR7cHJlZml4fSR7Y29sdW1uSW5kZXh9YCxcbiAgICBkYXRhS2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIHRpdGxlOiBgQ29sdW1uICR7Y29sdW1uSW5kZXh9YCwgXG4gICAgd2lkdGg6IGNvbHVtbkluZGV4ID09PSAwID8gODAgOiAxNTAsXG4gIH0pKVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoXG4gIGNvbHVtbnM6IFJldHVyblR5cGU8dHlwZW9mIGdlbmVyYXRlQ29sdW1ucz4sXG4gIGxlbmd0aCA9IDIwMCxcbiAgcHJlZml4ID0gJ3Jvdy0nXG4pID0+XG4gIEFycmF5LmZyb20oeyBsZW5ndGggfSkubWFwKChfLCByb3dJbmRleCkgPT4ge1xuICAgIHJldHVybiBjb2x1bW5zLnJlZHVjZShcbiAgICAgIChyb3dEYXRhLCBjb2x1bW4sIGNvbHVtbkluZGV4KSA9PiB7XG4gICAgICAgIHJvd0RhdGFbY29sdW1uLmRhdGFLZXldID0gYFJvdyAke3Jvd0luZGV4fSAtIENvbCAke2NvbHVtbkluZGV4fWBcbiAgICAgICAgcmV0dXJuIHJvd0RhdGFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiBgJHtwcmVmaXh9JHtyb3dJbmRleH1gLFxuICAgICAgICBwYXJlbnRJZDogbnVsbCxcbiAgICAgIH1cbiAgICApXG4gIH0pXG5cbmNvbnN0IGNvbHVtbnMgPSBnZW5lcmF0ZUNvbHVtbnMoMTApXG5jb25zdCBkYXRhID0gZ2VuZXJhdGVEYXRhKGNvbHVtbnMsIDEwMDApXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==).

**Comment by weklay** [comment]
I see, it must be set columns key, If not set columns key, it will be invalid!  Can it support taking effect without setting a key.
![image](https://github.com/element-plus/element-plus/assets/39334071/3bbbcd4b-50c6-43bb-855f-1a19b1ed0baf)

**Comment by btea** [comment]
`key` seems to be necessary.
