### ISSUE TITLE
[Performance] [All] 项目中导入 element-plus 后导致 volar 的性能问题

### ISSUE THREAD

**Issue by yeyuqh** [element-plus/element-plus#12770]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `e.g. Chrome 96.0.4664.45 / macOS 13.3.1`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

1. 使用 pnpm 创建 vite + vue 项目
2. 安装 element-plus
3. 在 App.vue 中导入 element-plus

注：volar 已启用 takeover 模式

### What is Expected?

!

### What is actually happening?

1. volar 首次加载变慢
2. 文件导入路径提示变慢

### Additional comments

_(empty)_

https://github.com/element-plus/element-plus/assets/49150556/c6068132-9350-43e9-8761-77b3e97df1f0

**Comment by 1581433801** [comment]
确实变慢了不少

**Comment by Cheerwhy** [comment]
有没有什么简单的解决办法，确实很卡
