### ISSUE TITLE
[Component] [dialog, tooltip] the position of <el-tooltip> is wrong in the <el-dialog>  ; <el-dialog>内的<el-tooltip>显示位置错误.

### ISSUE THREAD

**Issue by ZeroStarkW** [element-plus/element-plus#12772]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome  108.0.5359.73`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBvcGVuPXJlZihmYWxzZSlcbmNvbnN0IGxpc3Q9cmVmKFsxLDIsMyw0XSlcblxuXG5cbmZ1bmN0aW9uIG9wZW5EaWFsb2coKXtcbiAgb3Blbi52YWx1ZT10cnVlO1xuICBtc2cudmFsdWU9XCLlk4jlk4jlk4hcIlxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvcGVuRGlhbG9nXCI+e3ttc2d9fTwvZWwtYnV0dG9uPlxuICBcbiAgPGVsLWRpYWxvZyAgdi1tb2RlbD1cIm9wZW5cIlxuICAgICAgICAgICAgIDp0aXRsZT1cIm1zZ1wiIFxuICAgICAgICAgICAgIDp3aWR0aD0zMDBcbiAgICAgICAgICAgPlxuPGVsLXRhYmxlIDpkYXRhPVwibGlzdFwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbj5cbiAgPHRlbXBsYXRlICNkZWZhdWx0PVwie3Jvd31cIj5cbiAgPGVsLXRvb2x0aXBcbiAgICAgICAgIHYtaWY9XCJvcGVuXCJcbjp2aXNpYmxlPVwidHJ1ZVwiXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRlbnQ9XCLmtYvor5VcIiAgIFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPlxuICAgIDxlbC1idXR0b24+5rWL6K+VPC9lbC1idXR0b24+XG4gICAgPC9lbC10b29sdGlwPlxuICAgICAgICA8ZWwtYnV0dG9uIHYtZm9yPVwidCBpbiBsaXN0XCI+e3t0fX08L2VsLWJ1dHRvbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击按钮打开dialog弹窗
click button to open dialog

### What is Expected?

按钮上出现位置正确的tooltip提示
The button has the tooltip on current position

### What is actually happening?

tooltip 位置异常
tooltip position is wrong 

### Additional comments

在已打开dialog界面的情况下,修改窗口大小(网页窗口大小),tooltip位置会变正确
if dialog has opened, change the windows size(Browser windows size), tooltip's position will be current

**Comment by btea** [comment]
There will be a transition effect when the dialog appears, and you can display the tooltip after the transition is complete.You can refer to this [example](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgb3Blbj1yZWYoZmFsc2UpXG5jb25zdCBzaG93VGlwID0gcmVmKGZhbHNlKVxuY29uc3QgbGlzdD1yZWYoWzEsMiwzLDRdKVxuXG5cblxuZnVuY3Rpb24gb3BlbkRpYWxvZygpe1xuICBvcGVuLnZhbHVlPXRydWU7XG4gIG1zZy52YWx1ZT1cIuWTiOWTiOWTiFwiO1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiBcdFx0IHNob3dUaXAudmFsdWUgPSB0cnVlOyAgIFxuICB9LCAzMDApXG59XG5mdW5jdGlvbiBjbG9zZSgpIHtcbiAgc2hvd1RpcC52YWx1ZSA9IGZhbHNlO1xufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvcGVuRGlhbG9nXCI+e3ttc2d9fTwvZWwtYnV0dG9uPlxuIFx0XHQ8ZWwtZGlhbG9nICBcbiAgICAgIEBjbG9zZT1cImNsb3NlXCJcbiAgICAgIHYtbW9kZWw9XCJvcGVuXCJcbiAgICAgIDp0aXRsZT1cIm1zZ1wiIFxuICAgICAgOndpZHRoPTMwMFxuICAgID5cbiAgICA8ZWwtdG9vbHRpcFxuICAgICAgOnZpc2libGU9XCJzaG93VGlwXCJcbiAgICAgIGNvbnRlbnQ9XCLmtYvor5VcIlxuICAgICA+ICAgXG4gICAgICA8ZWwtYnV0dG9uPua1i+ivlTwvZWwtYnV0dG9uPlxuICAgIDwvZWwtdG9vbHRpcD5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319).
