### ISSUE TITLE
[Component] [image] el-image对于loading="lazy"的懒加载未实现，存在bug

### ISSUE THREAD

**Issue by xhc-code** [element-plus/element-plus#12771]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome最新浏览器`
- Build Tool: `Nuxt`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbWFnZV9fbGF6eVwiPlxuICAgIDxlbC1pbWFnZSB2LWZvcj1cInVybCBpbiB1cmxzXCIgOmtleT1cInVybFwiIDpzcmM9XCJ1cmxcIiBsb2FkaW5nPVwibGF6eVwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHVybHMgPSBbXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMS8zNC8xOWFhOThiMWZjYjI3ODFjNGZiYTMzZDg1MDU0OWpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMC82Zi9lMzVmZjM3NTgxMmU2YjAwMjBiNmI0ZThmOTU4M2pwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vOS9iYi9lMjc4NThlOTczZjVkN2QzOTA0ODM1ZjQ2YWJiZGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZC9lNi9jNGQ5M2EzODA1YjNjZTNmMzIzZjc5NzRlNmY3OGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy8yOC9iYmY4OTNmNzkyZjAzYTU0NDA4YjNiN2E3ZWJmMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMi8xMS82NTM1YmNmYjI2ZTRjNzliNDhkZGRlNDRmNGI2ZmpwZWcuanBlZycsXG5dXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWltYWdlX19sYXp5IHtcbiAgaGVpZ2h0OiA0MDBweDtcbiAgb3ZlcmZsb3cteTogYXV0bztcbn1cbi5kZW1vLWltYWdlX19sYXp5IC5lbC1pbWFnZSB7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBtaW4taGVpZ2h0OiAyMDBweDtcbiAgbWFyZ2luLWJvdHRvbTogMTBweDtcbn1cbi5kZW1vLWltYWdlX19sYXp5IC5lbC1pbWFnZTpsYXN0LWNoaWxkIHtcbiAgbWFyZ2luLWJvdHRvbTogMDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.打开地址

### What is Expected?

1. 正常图片懒加载

### What is actually happening?

1. 未实现loading="lazy"属性的作用。

### Additional comments

_(empty)_

**Comment by btea** [comment]
虽然img src显示有值，但实际还是懒加载的。
![image](https://github.com/element-plus/element-plus/assets/24516654/6d3b2872-8e55-4307-9acb-cd6be1cc9c0a)

**Comment by xhc-code** [comment]
> 虽然img src显示有值，但实际还是懒加载的。 ![image](https://user-images.githubusercontent.com/24516654/237835635-6d3b2872-8e55-4307-9acb-cd6be1cc9c0a.gif)

但是当你刷新F5刷新页面后，再次看请求就没有懒加载的请求了、

**Comment by btea** [comment]
这种时候应该浏览器缓存了文件不会重复请求，这是浏览器原生行为。

**Comment by xhc-code** [comment]
> 这种时候应该浏览器缓存了文件不会重复请求，这是浏览器原生行为。

浏览器请求图片的资源了，是在刷新浏览器后就直接请求了，而不是通过图片懒加载滚动方式进行的请求。
看来是浏览器对已缓存的直接请求，否则是懒加载滚动的方式了。


谢谢
