### ISSUE TITLE
[Bug Report] ElLoading transition not work

### ISSUE THREAD

**Issue by xyorz** [element-plus/element-plus#1280]
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
Google Chrome 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xyorz/pen/poEQrwJ

### Steps to reproduce
click show loading button

### What is Expected?
loading show and close with transition just like element-ui:
https://element.eleme.cn/#/zh-CN/component/loading#zheng-ye-jia-zai

### What is actually happening?
loading show and close without transition

**Comment by Ryan2128** [comment]
Will fix soon.
