### ISSUE TITLE
[Component] [steps] el-steps: 数据源改变之后，步骤条的顺序出错

### ISSUE THREAD

**Issue by Snoopy-Li** [element-plus/element-plus#12811]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.28`
- Browser / OS: `Microsoft Edge Version 113.0.1774.42 (Official build) (64-bit)`
- Build Tool: `Other`

### Related Component

- `el-steps`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHN0ZXBzID0gcmVmKFt7XG5cdHRpdGxlOiBcIuesrOS4gFwiLFxuICB9LCB7XG4gICAgdGl0bGU6IFwi56ys5LqMXCIsXG4gIH0sIHtcbiAgICB0aXRsZTogXCLnrKzkuIlcIixcbn0sIHtcblx0XHR0aXRsZTogXCLnrKzlm5tcIlxufSwge1xuXHRcdHRpdGxlOiBcIuesrOS6lFwiXG59XSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc3RlcHMgOmFjdGl2ZT1cIi0xXCIgcHJvY2Vzcy1zdGF0dXM9XCJwcm9jZXNzXCIgZmluaXNoLXN0YXR1cz1cImZpbmlzaFwiIDphbGlnbi1jZW50ZXI9XCJ0cnVlXCI+XG4gICAgPHRlbXBsYXRlIDprZXk9XCJzdGVwLnRpdGxlXCIgdi1mb3I9XCIoc3RlcCwgaW5kZXgpIGluIHN0ZXBzXCI+XG4gICAgXHQ8ZWwtc3RlcCA6dGl0bGU9XCJzdGVwLnRpdGxlXCIgOmRlc2NyaXB0aW9uPVwic3RlcC5kZXNjcmlwdGlvblwiPjwvZWwtc3RlcD5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXN0ZXBzPlxuICBcbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzdGVwcyA9IFt7XG5cdHRpdGxlOiAnYScsXG4gIH0sIHtcbiAgICB0aXRsZTogJ2InLFxuICB9LCB7XG4gICAgdGl0bGU6ICdjJyxcbn0sIHtcblx0dGl0bGU6ICdkJyxcbiAgfSwge1xuICAgIHRpdGxlOiAnZScsXG4gIH0sIHtcbiAgICB0aXRsZTogJ2YnLFxufSwge1xuICAgIHRpdGxlOiAnZycsXG59XVwiPueCueaIkeabtOaWsOaVsOaNrjwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 打开上面的 playgoround 的链接，直接点击"点我更新数据"，发现 step 上的号码反序了，步骤方向也反向了.

注：不使用key不能复现，不确定是vue的视图刷新策略，还是element的bug，劳烦调查一下

### What is Expected?

steps不反向

### What is actually happening?

steps反向了

### Additional comments

不使用key不能复现，不确定是vue的视图刷新策略，还是element的bug，劳烦调查一下

**Comment by zhengsixsix** [comment]
应该是vue的diff问题

**Comment by 13725102796** [comment]
这个bug是因为steps组件在设置step组件的index引起的
``` bash
# 初始化时正确是因为 stepItemState 能按照渲染顺序依次写入 parent.steps.value
# steps/src/item.vue    line - 216
parent.steps.value = [...parent.steps.value, stepItemState]

# 从而再遍历时，能正确设置 index
# steps/src/steps.vue  line - 27
watch(steps, async () => {
  steps.value.forEach((instance: StepItemState, index: number) => {
    instance.setIndex(index)
  })
})

# 当steps 数据更新时，部分step可能会保留下来，部分step可能会重新绘制，导致生成了
# parent.steps.value = [...保留的step, ...新生成的step]  这样一份数据
# 当 通过 steps.value.forEach 去 instance.setIndex(index) 就会有问题

```
diff 检测到文本变化是直接替换文本，而不是重新渲染整个组件。diff应该是正常的操作。这里的数据结构parent.steps.value和实际渲染的数据结构无法保持一致。这才是原因。

暂时没有想到很好的解决方案，可以通过不缓存渲染组件的方式去规避：
``` bash
 <template :key="index" v-for="(step, index) in steps">
    <el-step :title="step.title" :description="step.description"></el-step>
 </template>

```
