### ISSUE TITLE
[TypeScript] [All] 导入类型提示不正确

### ISSUE THREAD

**Issue by ckvv** [element-plus/element-plus#12821]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/ckvv/vue3_demo)

### Steps to reproduce

+ npm create vue
+ npm install element-plus
+ 修改App.vue

```vue
<script setup lang="ts">
import 'element-plus/theme-chalk/index.css'
import { ElButton } from "element-plus";
</script>

<template>
  <ElButton>ElButton</ElButton>
</template>
```

### What is Expected?

import { ElButton } from "element-plus";
ts类型提示正常

### What is actually happening?

<img width="820" alt="截屏2023-05-15 12 24 05" src="https://github.com/element-plus/element-plus/assets/30174970/872741e4-cb4d-4584-81b0-3b233554bf7b">

VSCode 显示以下错误:
Module '"element-plus"' has no exported member 'ElButton'. Did you mean to use 'import ElButton from "element-plus"' instead?ts(2614)

### Additional comments

项目可以正常运行但是类型提示不正确

**Comment by zhengsixsix** [comment]
你这种按需导入 是根据官方文档来的吗 是否配置了vite

**Comment by mioxs** [comment]
3.3不兼容吧，emit和slot都发生了变化。

**Comment by well-he** [comment]
可以参考这里设置一下自动导入 [Configuration](https://github.com/antfu/unplugin-auto-import#configuration)

**Comment by LadyChatterleyLover** [comment]
@mioxs vue 3.2.47也是一样的，导入提示错误，但项目可以正常运行，element-plus 版本为2.3.4

**Comment by Dedicatus546** [comment]
同样的问题，使用 unplugin-vue-components 生成的 component.d.ts 无法提示正确的类型

![image](https://github.com/element-plus/element-plus/assets/48575405/96930e3b-6947-4f37-a60d-6f57f3773301)

**Comment by Dedicatus546** [comment]
退到 2.3.3 可以正确识别，但是 2.3.4 就无法识别了

![image](https://github.com/element-plus/element-plus/assets/48575405/28de2f75-ab36-4ccd-8bf1-185b0cc30b7a)

**Comment by Dedicatus546** [comment]
试了下，应该是 tsconfig.json 里面 "moduleResolution": "bundler", 这个配置的问题，现在创建项目使用的是 "moduleResolution": "bundler" ，这种情况下会报错，改回 "moduleResolution": "node" 错误信息消失，所有版本都是最新，bundler 这个选项是 ts 5.0 的新特性，可能对导入有问题

[Announcing TypeScript 5.0 - --moduleResolution bundler](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler)

**Comment by Dedicatus546** [comment]
测试了下 node16 nodenext 均报错，只有 node 选项能正确工作

**Comment by LadyChatterleyLover** [comment]
@Dedicatus546 感谢，修改了tsconfig就没有报错了

**Comment by Robert-Du0001** [comment]
@Dedicatus546 感谢

**Comment by Mario-Marion** [comment]
> 测试了下 node16 nodenext 均报错，只有 node 选项能正确工作

感谢

**Comment by hankli1985** [comment]
为什么我改了配置还是报错
![image](https://github.com/element-plus/element-plus/assets/48507363/b836b8ea-28f5-4c95-a73a-5f562da60cf3)

**Comment by Mario-Marion** [comment]
> 为什么我改了配置还是报错
> ![image](https://github.com/element-plus/element-plus/assets/48507363/b836b8ea-28f5-4c95-a73a-5f562da60cf3)
> 

两个 tsconfig 文件都要改

**Comment by luqiudi** [comment]
新版的vue3.3 tsconfig.json 关联了两个 tsconfig.app.json tsconfig.node.json 文件,我发现在这种结构下,element 的组件类型不支持自动导入了.然而我换成旧的 tsconfig.json 方式,又可以正常显示组件类型了.不造为啥


生效的 old_tsconfig.json:
`{
    "compilerOptions": {
        "target": "esnext",

        "useDefineForClassFields": true,
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "allowJs": true,
        "sourceMap": true,
        "resolveJsonModule": true,
        "isolatedModules": true,
        "esModuleInterop": true,
        "lib": ["esnext", "dom"],
        "importHelpers": true,
        "skipLibCheck": true,
        "jsx": "preserve",
        "jsxFactory": "h",
        "jsxFragmentFactory": "Fragment",
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"]
        },
        "types": ["naive-ui/volar", "element-plus/global"]
    },
    "include": [
        "src/**/*.js",
        "src/**/*.ts",
        "src/**/*.d.ts",
        "src/**/*.tsx",
        // "src/**/*.jsx",
        "src/**/*.vue"
        // "src/**/*"
    ],
    "exclude": ["node_modules", "dist", "src/lib/*"]
}`



不生效的新的组织方式
### tsconfig.json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}

### tsconfig.node.json

{
  "extends": "@tsconfig/node18/tsconfig.json",
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "nightwatch.conf.*",
    "playwright.config.*"
  ],
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "types": [
      "node"
    ]
  }
}

### tsconfig.app.json

{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  // "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "types": [
      "naive-ui/volar",
      "element-plus/global"
    ]
  }
}

我用的
vue 3.3 
element-plus :2.3.6

在old_tsconfig.json 下是能正常支持组件类型自动导入的

在新的配置方式下不支持,希望可以为你提供帮助

**Comment by GiannaJun1030** [comment]
@Dedicatus546 🐮🍺

**Comment by KokoTa** [comment]
2.3.7 也有这样的问题

**Comment by 1301604100** [comment]
> 新版的vue3.3 tsconfig.json 关联了两个 `tsconfig.app.json` `tsconfig.node.json `文件,我发现在这种结构下,element 的组件类型不支持自动导入(其实支持,但是不提供类型提示)了.然而我换成旧的 tsconfig.json 方式,又可以正常显示组件类型了.不造为啥
> 
> 生效的 old_tsconfig.json: `{ "compilerOptions": { "target": "esnext",
> 
> ```
>     "useDefineForClassFields": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "strict": true,
>     "allowJs": true,
>     "sourceMap": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "esModuleInterop": true,
>     "lib": ["esnext", "dom"],
>     "importHelpers": true,
>     "skipLibCheck": true,
>     "jsx": "preserve",
>     "jsxFactory": "h",
>     "jsxFragmentFactory": "Fragment",
>     "baseUrl": ".",
>     "paths": {
>         "@/*": ["src/*"]
>     },
>     "types": ["naive-ui/volar", "element-plus/global"]
> },
> "include": [
>     "src/**/*.js",
>     "src/**/*.ts",
>     "src/**/*.d.ts",
>     "src/**/*.tsx",
>     // "src/**/*.jsx",
>     "src/**/*.vue"
>     // "src/**/*"
> ],
> "exclude": ["node_modules", "dist", "src/lib/*"]
> ```
> 
> }`
> 
> 不生效的新的组织方式
> 
> ### tsconfig.json
> { "files": [], "references": [ { "path": "./tsconfig.node.json" }, { "path": "./tsconfig.app.json" } ] }
> 
> ### tsconfig.node.json
> { "extends": "@tsconfig/node18/tsconfig.json", "include": [ "vite.config._", "vitest.config._", "cypress.config._", "nightwatch.conf._", "playwright.config.*" ], "compilerOptions": { "composite": true, "module": "ESNext", "types": [ "node" ] } }
> 
> ### tsconfig.app.json
> { "extends": "@vue/tsconfig/tsconfig.dom.json", "include": ["env.d.ts", "src/**/*", "src/**/_.vue"], // "exclude": ["src/**/**tests**/_"], "compilerOptions": { "composite": true, "baseUrl": ".", "paths": { "@/_": ["src/_"] }, "types": [ "naive-ui/volar", "element-plus/global" ] } }
> 
> 我用的 vue 3.3 element-plus :2.3.6
> 
> 在old_tsconfig.json 下是能正常支持组件类型自动导入的
> 
> 在新的配置方式下不支持,希望可以为你提供帮助

请问解决了吗
