### ISSUE TITLE
[Bug Report] style repeat

### ISSUE THREAD

**Issue by whitecuteXu** [element-plus/element-plus#1283]
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
chrome  87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://github.com/ElemeFE/element/issues

### Steps to reproduce
1.  On-demand introduction 
import { App } from 'vue';

import {
  ElButton,
];

const plugins = [
  ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox,
  ElNotification,
];

export const installElement = {
    install(app: App) {
        app.config.globalProperties.$ELEMENT = { size: 'small', zIndex: 3000 };
        components.forEach((component) => {
            app.component(component.name, component);
        });
        plugins.forEach((plugin) => {
            app.use(plugin as any);
        });
    },
};
2. babel.config.js

module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  plugins: [
    [
      "component",
      {
        "libraryName": "element-plus",
        // "styleLibraryName": "theme-chalk"
        style: false
      }
    ]
  ]
}

3. element-variables
/* 改变主题色变量 */
$--color-primary: teal;

/* 改变 icon 字体路径变量，必需 */
$--font-path: '~element-plus/lib/theme-chalk/fonts';

/* mix cannot read css var() */
@import "~element-plus/packages/theme-chalk/src/index";

4. main.ts
import '@/assets/theme/element-ui/element-variables.scss';

5. use el-button

BUG: found that the button style was introduced 5 times

### What is Expected?
the button style was introduced 1 times

### What is actually happening?
the button style was introduced 5 times

**Comment by JeremyWuuuuu** [comment]
use compressor to do the trick.
![image](https://user-images.githubusercontent.com/15975785/104870108-a263c480-5982-11eb-920b-76bf31c749bd.png)

**Comment by JeremyWuuuuu** [comment]
Closing due to stale. Feel free to reopen this.

**Comment by jdinartejesus** [comment]
I'm also having the same issue with similar configuration.
