### ISSUE TITLE
[Performance] [select] element-plus@2.3.4版本el-select组件存在内存泄漏。最早期element-plus@1.1.0-beta.24这个版本可以正常销毁

### ISSUE THREAD

**Issue by lingyucao** [element-plus/element-plus#12848]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.3.1`
- Element Plus Version: `2.3.4`
- Browser / OS: `Windows NT 10.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Github Repo](https://github.com/lingyucao/element-plus-demo/blob/main/demo.html)

### Steps to reproduce

浏览器的  内存=> 性能分析 可以检测到，手动销毁也不能销毁

### What is Expected?

能修复

### What is actually happening?

能修复

### Additional comments

_(empty)_

**Comment by CwRv07** [comment]
很抱歉，我经过测试并未发现内存泄露的问题，我只能猜测可能您测试时，GC销毁的时机更滞后？或者给出您更具体的检测流程？

**Comment by lingyucao** [comment]
***@***.***的情况


下面分两种方式验证。


一。内存检测 【1。未加载组件，2。加载组件，3。销毁组件】。 每一步都手动垃圾回收，确保不受干扰。



1。未加载组件




2。加载组件










3。销毁组件


二。录制内存时间变化【组件销毁后，仍有22m没销毁】










大雄
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Performance] [select] ***@***.******@***.***这个版本可以正常销毁 (Issue #12848)





 
很抱歉，我经过测试并未发现内存泄露的问题，我只能猜测可能您测试时，GC销毁的时机更滞后？或者给出您更具体的检测流程？

**Comment by lingyucao** [comment]
请问问题定位了吗？












下面分两种方式验证。


一。内存检测 【1。未加载组件，2。加载组件，3。销毁组件】。 每一步都手动垃圾回收，确保不受干扰。



1。未加载组件




2。加载组件










3。销毁组件


二。录制内存时间变化【组件销毁后，仍有22m没销毁】










大雄
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Performance] [select] ***@***.******@***.***这个版本可以正常销毁 (Issue #12848)





 
很抱歉，我经过测试并未发现内存泄露的问题，我只能猜测可能您测试时，GC销毁的时机更滞后？或者给出您更具体的检测流程？

**Comment by CwRv07** [comment]
确实存在内存泄露，但现象很奇怪，在组件库在打包和未打包泄露情况不同，我测试时，在未打包情况下没内存泄露，打包情况则存在，但我没能找到原因

**Comment by lingyucao** [comment]
未打包时例子我看下，帮你一块看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月23日(周二) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [element-plus/element-plus] [Performance] [select] ***@***.******@***.***这个版本可以正常销毁 (Issue #12848)




 
确实存在内存泄露，但现象很奇怪，在组件库在打包和未打包泄露情况不同，我测试时，在未打包情况下没内存泄露，打包情况则存在，但我没能找到原因

**Comment by CwRv07** [comment]
一样的代码，只是一个未打包的在element plus库的play目录里跑的；另一个在本地其的项目，使用element plus库打包的结果跑，其他条件几乎都一致

**Comment by lingyucao** [comment]
好的，我抽空验证下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月23日(周二) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [element-plus/element-plus] [Performance] [select] ***@***.******@***.***这个版本可以正常销毁 (Issue #12848)




 
一样的代码，只是一个未打包的在element plus库的play目录里跑的；另一个在本地其的项目，使用element plus库打包的结果跑，其他条件几乎都一致

**Comment by lingyucao** [comment]
未打包情况下，已发现有内存泄漏。已绕过，

**Comment by 1zxca** [comment]
本地开发确实存在内存泄漏，还没解决

**Comment by 1zxca** [comment]
官方可以出个appen-to-body不？现在vue那边teleport还没解决

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/element-plus/element-plus/issues/14948)
