### ISSUE TITLE
[bug report] using V-for loop to generate El table -- columns

### ISSUE THREAD

**Issue by Wolferring** [element-plus/element-plus#1285]
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
macos bigsur

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/whimsy/pen/LYRXoXo

### Steps to reproduce
尝试使用日期数组，构建表格列，日期数组经过更新后，列的排序出现错误。
点-号更新数据，再点加号更新回来，列的排序出现问题

### What is Expected?
排序应该按照数组排序

### What is actually happening?
实际会出现乱序

**Comment by kooriookami** [comment]
Cause you set the same key, remove the `key` and try again.

**Comment by Ryan2128** [comment]
> Cause you set the same key, remove the `key` and try again.

This might be a bug, `v-for` requires `key`.

cc @justwiner

**Comment by Wolferring** [comment]
> Cause you set the same key, remove the `key` and try again.

not because of the key,it work well with other components.maybe the vnode diff code?

**Comment by justwiner** [comment]
Hello guys, the problem is that when the column is inserted, the splice method adds elements beyond the array pair to the end of the array.
```js
["2021-01-12", "2021-01-11", "2021-01-10"].splice(5, 0, '2021-01-08') 
// ["2021-01-12", "2021-01-11", "2021-01-10", '2021-01-08']

["2021-01-12", "2021-01-11", "2021-01-10", "2021-01-08"].splice(4, 0, '2021-01-09') 
// ["2021-01-12", "2021-01-11", "2021-01-10", '2021-01-08', '2021-01-09']

// hope: ["2021-01-12", "2021-01-11", "2021-01-10", '2021-01-09', '2021-01-08']
```

which I will fix.
