### ISSUE TITLE
[Component] [date-picker] element-plus@2.3.4版本el-date-picker组件的月份选择-calendar-change方法失效

### ISSUE THREAD

**Issue by noStaylate** [element-plus/element-plus#12854]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmxldCBtc2cgPSByZWYoJycpXG5sZXQgbXNnRGF5ID0gcmVmKCcnKVxubGV0IGRhdGFMaXN0ID0gcmVmKFtdKVxubGV0IGRhdGFEYXlMaXN0ID0gcmVmKFtdKVxuXG5jb25zdCBjYWxlbmRhckNoYW5nZSA9ICh2YWw6IGFueSkgPT4ge1xuICBtc2cudmFsdWUgPSBKU09OLnN0cmluZ2lmeSh2YWwpXG4gIGNvbnNvbGUubG9nKHZhbCwgJ+aciOS7vemAieaLqeinpuWPkScpXG59XG5cbmNvbnN0IGNhbGVuZGFyRGF5Q2hhbmdlID0gKHZhbDogYW55KSA9PiB7XG4gIG1zZ0RheS52YWx1ZSA9IEpTT04uc3RyaW5naWZ5KHZhbClcbiAgY29uc29sZS5sb2codmFsLCAn5pel5pyf6YCJ5oup6Kem5Y+RJylcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMTBweDsgZGlzcGxheTogZmxleFwiPlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cImRhdGFMaXN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMHB4XCJcbiAgICAgIEBjYWxlbmRhci1jaGFuZ2U9XCJjYWxlbmRhckNoYW5nZVwiXG4gICAgICB2YWx1ZS1mb3JtYXQ9XCJZWVlZLU1NXCJcbiAgICAgIHR5cGU9XCJtb250aHJhbmdlXCJcbiAgICAgIHVubGluay1wYW5lbHNcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIi1cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCLlvIDlp4vmnIjku71cIlxuICAgICAgZW5kLXBsYWNlaG9sZGVyPVwi57uT5p2f5pyI5Lu9XCJcbiAgICA+PC9lbC1kYXRlLXBpY2tlcj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6MDtmbGV4OjE7XCI+5pyI5Lu96Kem5Y+R5pWw5o2u77yae3sgbXNnIH19PC9kaXY+XG4gIDwvZGl2PlxuICA8ZGl2IHN0eWxlPVwid2lkdGg6IDEwMCU7IG1hcmdpbjogMTBweCAwcHg7IGRpc3BsYXk6IGZsZXhcIj5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgIHYtbW9kZWw9XCJkYXRhRGF5TGlzdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDBweFwiXG4gICAgICBAY2FsZW5kYXItY2hhbmdlPVwiY2FsZW5kYXJEYXlDaGFuZ2VcIlxuICAgICAgdmFsdWUtZm9ybWF0PVwiWVlZWS1NTS1ERFwiXG4gICAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIi1cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCLlvIDlp4vml6XmnJ9cIlxuICAgICAgZW5kLXBsYWNlaG9sZGVyPVwi57uT5p2f5pel5pyfXCJcbiAgICA+PC9lbC1kYXRlLXBpY2tlcj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6MDtmbGV4OjE7XCI+5pel5pyf6Kem5Y+R5pWw5o2u77yae3sgbXNnRGF5IH19PC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion, ElDatePicker } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

let msg = ref('')
let msgDay = ref('')
let dataList = ref([])
let dataDayList = ref([])

const calendarChange = (val: any) => {
  msg.value = JSON.stringify(val)
  console.log(val, '月份选择触发')
}

const calendarDayChange = (val: any) => {
  msgDay.value = JSON.stringify(val)
  console.log(val, '日期选择触发')
}
</script>

<template>
  <div style="width: 100%; margin-bottom: 10px; display: flex">
    <el-date-picker
      v-model="dataList"
      style="width: 100px"
      @calendar-change="calendarChange"
      value-format="YYYY-MM"
      type="monthrange"
      unlink-panels
      range-separator="-"
      start-placeholder="开始月份"
      end-placeholder="结束月份"
    ></el-date-picker>
    <div style="width:0;flex:1;">月份触发数据：{{ msg }}</div>
  </div>
  <div style="width: 100%; margin: 10px 0px; display: flex">
    <el-date-picker
      v-model="dataDayList"
      style="width: 100px"
      @calendar-change="calendarDayChange"
      value-format="YYYY-MM-DD"
      type="daterange"
      range-separator="-"
      start-placeholder="开始日期"
      end-placeholder="结束日期"
    ></el-date-picker>
    <div style="width:0;flex:1;">日期触发数据：{{ msgDay }}</div>
  </div>
</template>
```

### What is Expected?

输出msg的内容

### What is actually happening?

msg为空

### Additional comments

_(empty)_

**Comment by btea** [comment]
`calender-change` seems to only support `daterange`, refer to the [documentation](https://element-plus.org/en-US/component/date-picker.html#events#:~:text=Only%20for%20daterange).

**Comment by noStaylate** [comment]
> `calender-change`似乎只支持`daterange`，请参考[文档](https://element-plus.org/en-US/component/date-picker.html#events#:~:text=Only%20for%20daterange)。

zh-CN站点文档上没有标明好像，不过es-US上写了

**Comment by noStaylate** [comment]
> `calender-change`似乎只支持`daterange`，请参考[文档](https://element-plus.org/en-US/component/date-picker.html#events#:~:text=Only%20for%20daterange)。

zh-CN站点文档上没有标明好像，不过es-US上写了

**Comment by btea** [comment]
嗯，可能是翻译的时候写漏了。
