### ISSUE TITLE
[Bug Report] Dialog set lock-scroll invalidation The page can still be scrolled

### ISSUE THREAD

**Issue by hreochen** [element-plus/element-plus#1287]
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
macos

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/hreochen/pen/GRjwbwM

### Steps to reproduce
show Dialog

### What is Expected?
The page cannot be scrolled

### What is actually happening?
The page can still be scrolled

**Comment by kooriookami** [comment]
Will be fixed soon.

**Comment by JeremyWuuuuu** [comment]
Well, this is a confirmed bug and already been fixed in #1282 , also, lock scroll is an API for locking the document content, instead of locking dialog itself.

**Comment by JeremyWuuuuu** [comment]
We'll have a release soon. Closing
