### ISSUE TITLE
[Component] [form, drawer] el-form表单外层套Drawer或者Dialog组件时 应用于接口返回数据场景时 表单的resetFields()无效  手动初始化对象formValue的值可以但是会触发validator错误

### ISSUE THREAD

**Issue by jswbiubiu** [element-plus/element-plus#12886]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.21`
- Browser / OS: `Chrome 113.0.5672.126`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-drawer`

### Reproduction Link

[Github Repo](https://github.com/jswbiubiu/Elawer_ElFrom_bug)

### Steps to reproduce

1、先点新建 - 重置 没问题
2、刷新页面 - 先点编辑 - 重置无效 并且 新建\编辑其他行 重置都会重置为第一次编辑的元素~！

### What is Expected?

期望可以修复这个bug

### What is actually happening?

开发猜测 element2版本用 :visabled=""是不会有这个问题
visible	是否显示 Drawer，支持 .sync 修饰符	boolean	—	false  但是element-plus版本去除了这个属性 只能通过v-model 
    model-value 方式绑定显示隐藏导致的这个bug的出现  

### Additional comments

1

**Comment by jswbiubiu** [comment]
> 我也遇到了这个问题

希望早点修复吧   客户现在体验比较差哈哈哈

**Comment by jswbiubiu** [comment]
> 我也遇到了这个问题

希望早点修复吧 客户现在体验比较差~~

**Comment by tao892509844** [comment]
resetFields重置的数据是以el-form初次渲染时绑定的model为准，当你第一次打开弹窗时el-form才渲染，而此时已经赋值formData了，所以每次resetFields的数据就是第一次赋值formData的数据。所以你得在打开弹窗后在nextTick里赋值
![image](https://github.com/element-plus/element-plus/assets/20335041/e4bffc5d-b0a8-4136-982a-df38fcd160d0)

**Comment by tao892509844** [comment]
下次提issue还是按照规范来吧，具体看组件库说的提issue的步骤。要像别人那样点链接就直接看到具体bug的，也就我这种闲人会复制你的代码重现了

**Comment by jswbiubiu** [comment]
> 下次提issue还是按照规范来吧，具体看组件库说的提issue的步骤。要像别人那样点链接就直接看到具体bug的，也就我这种闲人会复制你的代码重现了

大佬666~
