### ISSUE TITLE
[Component] [tree] [El-Tree]的setCheckedKeys方法不严谨

### ISSUE THREAD

**Issue by HwuuF7** [element-plus/element-plus#12893]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBjb21wdXRlZCwgb25Nb3VudGVkLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdHJlZURhdGEgPSByZWYoW1xuICB7aWQ6IDEsIG5hbWU6ICfmoLkxJywgY2hpbGRyZW46IFtcbiAgICB7IGlkOiAxMSwgbmFtZTogJ+aguTExJyB9LFxuICAgIHsgaWQ6IDEyLCBuYW1lOiAn5qC5MTInIH0sXG4gICAgeyBpZDogMTMsIG5hbWU6ICfmoLkxMycgfVxuICBdfSxcbl0pLFxuICAgIHRyZWVQcm9wcyA9IGNvbXB1dGVkKCgpID0+IHtcbiAgICAgICAgcmV0dXJuIHtcbiAgICAgICAgICAgIGxhYmVsOiAnbmFtZScsXG4gICAgICAgICAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICAgICAgfVxuICAgIH0pO1xuIFxuICBjb25zdCB0cmVlUmVmID0gcmVmKG51bGwpXG4gb25Nb3VudGVkKCgpID0+IHtcbiAgIG5leHRUaWNrKCgpID0+IHtcbiAgICAgICAgICAgIHRyZWVSZWYudmFsdWUgJiYgdHJlZVJlZi52YWx1ZS5zZXRDaGVja2VkS2V5cyhbMSwxMSwgMTIsXSwgZmFsc2UpXG4gICAgICAgIH0pXG4gfSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICBcbiAgXG5cdDxlbC10cmVlIFxuICAgXHRub2RlLWtleT1cImlkXCIgXG4gICAgcmVmPVwidHJlZVJlZlwiIFxuICAgIDpkZWZhdWx0LWV4cGFuZGVkLWtleXM9XCJbMSwyLDNdXCIgXG4gICAgOmRhdGE9XCJ0cmVlRGF0YVwiIFxuICAgIDpwcm9wcz1cInRyZWVQcm9wc1wiIFxuICAgIHNob3ctY2hlY2tib3ggXG4gIC8+XG5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

treeData的ID为： [1 -> [11, 12, 13]]
setCheckedKeys: [1, 11, 12]  选中这三个节点 在逻辑判断上 节点1不应该显示为选中状态 而是半选状态
因为13没有被选中，因此内部逻辑处理上还需要进一步优化

### What is Expected?

节点1不应该显示为选中状态

### What is actually happening?

节点1应该显示为半选状态

### Additional comments

_(empty)_

**Comment by btea** [comment]
这个表现应该是正确的，如果照你所说想要节点1为半选状态，设置`[11, 12]`就行。

**Comment by HwuuF7** [comment]
> 选

并不正确。因为节点13是后来新增的呢？数据[1, 11, 12]是原有的，此时不应该强行帮我选中13

**Comment by HwuuF7** [comment]
@btea 

> 这个表现应该是正确的，如果照你所说想要节点1为半选状态，设置`[11, 12]`就行。

并不正确。我的节点13是后续新增的，而之前的数据是[1, 11, 12]，你不应该将我的节点13勾选上

**Comment by chenxch** [comment]
> @btea
> 
> > 这个表现应该是正确的，如果照你所说想要节点1为半选状态，设置`[11, 12]`就行。
> 
> 并不正确。我的节点13是后续新增的，而之前的数据是[1, 11, 12]，你不应该将我的节点13勾选上

是正确的哦，checked就是表示勾选的，半选状态===没勾选，1都勾选了，它的children不应该勾选上么

**Comment by tingfeng-key** [comment]
@HwuuF7 遇到同样的问题，有其他的解决方案吗

**Comment by tingfeng-key** [comment]
用`setChecked`手动设置可以达到想要的效果：`setChecked(v, true, false)`
