### ISSUE TITLE
[Component] [notification] Notification zIndex not work

### ISSUE THREAD

**Issue by hvv123** [element-plus/element-plus#12909]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 113.0.0.0 / Windows NT 10.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW4yXCI+IFdvbid0IGNsb3NlIGF1dG9tYXRpY2FsbHkgPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTm90aWZpY2F0aW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBvcGVuMiA9ICgpID0+IHtcbiAgRWxOb3RpZmljYXRpb24oe1xuICAgIHpJbmRleDo5OTk5LFxuICAgIHRpdGxlOiAnUHJvbXB0JyxcbiAgICBtZXNzYWdlOiAnVGhpcyBpcyBhIG1lc3NhZ2UgdGhhdCBkb2VzIG5vdCBhdXRvbWF0aWNhbGx5IGNsb3NlJyxcbiAgICBkdXJhdGlvbjogMCxcbiAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. click button to show notification.
2. inspect dom to find notification dom element.
3. the zIndex option is not working.

### What is Expected?

The component should respect options.zIndex as documented.

### What is actually happening?

zIndex option not work

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed by #12474
