### ISSUE TITLE
[Component] [All] colorpicker面板打开时光标位置不对

### ISSUE THREAD

**Issue by wtjperi2003** [element-plus/element-plus#12901]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/color-picker.html)

### Steps to reproduce

官网示例，直接打开，然后随便选个颜色，点击确定，收起面板。之后再打开发现，光标还是停留在左上角

### What is Expected?

什么颜色就停留在什么颜色上

### What is actually happening?

打开默认都是在左上角

### Additional comments

_(empty)_

**Comment by 2048920439** [comment]
可以看看https://github.com/element-plus/element-plus/pull/12597这个处理方法,PR太麻烦了我就关闭了

**Comment by kooriookami** [comment]
> 可以看看#12597 这个处理方法,PR太麻烦了我就关闭了

其实只是ref写错了，导致update没有触发😂
