### ISSUE TITLE
[Component] [button] 项目中同时使用element-plus和view-ui-plus时，el-button上绑有ive的类名

### ISSUE THREAD

**Issue by Chia-L** [element-plus/element-plus#12919]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 版本 113.0.5672.127（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Github Repo](https://github.com/Chia-L/demo)

### Steps to reproduce

同时引入element-plus和view-ui-plusUI库，在界面中写入el-button

### What is Expected?

预期应该是正常的

### What is actually happening?

发现el-button上带有ivu-类名  

### Additional comments

_(empty)_

**Comment by Chia-L** [comment]
![image](https://github.com/element-plus/element-plus/assets/37490498/5ca0f3a6-f2d8-4ae2-a4df-8ff1a87ed193)
布局组件的背景色也没有生效

**Comment by chenxch** [comment]
可能是组件重名注册，如果你通过ref打印实例会发现组件内部属性出现一些el-button没有的属性，如果一定要使用2个组件库的话，把使用较少的那个通过按需加载方式使用，不要全局注册。

**Comment by Chia-L** [comment]
> 可能是组件重名注册，如果你通过ref打印实例会发现组件内部属性出现一些el-button没有的属性，如果一定要使用2个组件库的话，把使用较少的那个通过按需加载方式使用，不要全局注册。

view-ui-plus组件库名字叫Button和ElButton不重名，打印模板引用（ref）结果是的element-plus中el-button组件Exposes出来的属性，在上面的链接中你可以测试。

**Comment by chenxch** [comment]
> view-ui-plus组件库名字叫Button和ElButton不重名，打印模板引用（ref）结果是的element-plus中el-button组件Exposes出来的属性，在上面的链接中你可以测试。

![image](https://github.com/element-plus/element-plus/assets/23251408/e217d186-c33f-4a75-b0fa-e801b202fb24) 你可以查看ref，等于是tag的 button指向view-ui-plus的Button.

**Comment by chenxch** [comment]
一个是不使用Button这种关键字，另一个就是我说你不要全量注册，按需引用。

**Comment by Chia-L** [comment]
> 这个与ep无关，我先关闭这个问题哈。

好的
