### ISSUE TITLE
[Component] [input] el-input使用computed输入不了

### ISSUE THREAD

**Issue by wangxiaoze-view** [element-plus/element-plus#12923]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 113.0.5672.127 `
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbi8vIHNldCBhIHZhbHVlXG5jb25zdCBhID0gcmVmKDEpXG5cbi8vIHNldCBiIHZhbHVlXG5jb25zdCBiID0gcmVmKDIpXG5cbi8vIGNvbXB1dGVkIHRvIGNcbmNvbnN0IGMgPSBjb21wdXRlZCh7XG4gIGdldCgpIHtcbiAgICByZXR1cm4gTnVtYmVyKGEudmFsdWUpICsgTnVtYmVyKGIudmFsdWUpXG4gIH0sXG4gIHNldCh2YWwpIHtcbiAgICAvLyBzZXQgdmFsdWVcbiAgICBjb25zb2xlLmxvZyh2YWwpXG4gIH1cbn0pXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwiYVwiIC8+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwiYlwiIC8+XG4gIDwhLS0gVE9ETzog5Li65LuA5LmI6L+Z6YeM5L2/55SoZWwtaW5wdXQgY29tcHV0ZWQgc2V05aSx5pWI77yfIC0tPlxuICA8IS0tIHNldOS7o+eggeaJp+ihjOS6hu+8jOS9huaYr+i+k+WFpeahhui+k+WFpeS4jeS6huWGheWuue+8nyAtLT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJjXCIgLz5cbiAgXG4gIDwhLS0g6ICM5pmu6YCa55qEaW5wdXQgc2V05piv5Y+v5Lul55qEIC0tPlxuICA8aW5wdXQgdHlwZT1cInRleHRcIiB2LW1vZGVsPVwiY1wiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

``` vue
<script setup lang="ts">
import { ref, computed } from 'vue'
// set a value
const a = ref(1)
// set b value
const b = ref(2)
// computed to c
const c = computed({
  get() {
    return Number(a.value) + Number(b.value)
  },
  set(val) {
    // set value
    console.log(val)
  }
})
</script>

<template>
  <el-input v-model="a" />
  <el-input v-model="b" />
  <!-- TODO: 为什么这里使用el-input computed set失效？ -->
  <!-- set代码执行了，但是输入框输入不了内容？ -->
  <el-input v-model="c" />
  
  <!-- 而普通的input set是可以的 -->
  <input type="text" v-model="c" />
</template>
```

我想要在`C`输入框继续执行，为了避免`vue computed set`警告，默认写了`set`方法，但是第一个输入框和第二个输入数字之后是可以的，但是在第三个输入框中，却`set`不了，但是`SET`方法执行了，输入按键输入不了任何字符；

### What is Expected?

我觉得el-input应该也是可以执行的；

### What is actually happening?

在原生input的情况下，是可以输入继续执行的，而在el-input中却执行不了；

### Additional comments

vite构建起也尝试过，也是不行的；

**Comment by wangxiaoze-view** [comment]
@tao892509844  这个我明白了，c和对于a,b进行相应依赖，但是我有一件事不明白，在不考虑c的响应数据的情况下。 为什么原生的input可以输入，而el-input 是不能输入的呢？el-input是在原生input的基础上进行封装的，难道el-input是做了限制嘛？

**Comment by tao892509844** [comment]
因为el-input自己定义了input事件，你可以自己去看源码

**Comment by tao892509844** [comment]
如果你想要实现c既可以自定义也可以由a和b相加得来，可以用watchEffect
![image](https://github.com/element-plus/element-plus/assets/20335041/f17f7767-a7e8-4bb0-b8b2-0e1776425f83)

**Comment by wangxiaoze-view** [comment]
@tao892509844  谢谢 这下明白了
