### ISSUE TITLE
[TypeScript] [tree] Tree filter example type error

### ISSUE THREAD

**Issue by Benleie** [element-plus/element-plus#12936]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZpbHRlclRleHRcIiBwbGFjZWhvbGRlcj1cIkZpbHRlciBrZXl3b3JkXCIgLz5cblxuICA8ZWwtdHJlZVxuICAgIHJlZj1cInRyZWVSZWZcIlxuICAgIGNsYXNzPVwiZmlsdGVyLXRyZWVcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOnByb3BzPVwiZGVmYXVsdFByb3BzXCJcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICA6ZmlsdGVyLW5vZGUtbWV0aG9kPVwiZmlsdGVyTm9kZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsVHJlZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW50ZXJmYWNlIFRyZWUge1xuICBpZDogbnVtYmVyXG4gIGxhYmVsOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cblxuY29uc3QgZmlsdGVyVGV4dCA9IHJlZignJylcbmNvbnN0IHRyZWVSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbFRyZWU+PigpXG5cbmNvbnN0IGRlZmF1bHRQcm9wcyA9IHtcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGxhYmVsOiAnbGFiZWwnLFxufVxuXG53YXRjaChmaWx0ZXJUZXh0LCAodmFsKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLmZpbHRlcih2YWwpXG59KVxuXG5jb25zdCBmaWx0ZXJOb2RlID0gKHZhbHVlOiBzdHJpbmcsIGRhdGE6IFRyZWUpID0+IHtcbiAgaWYgKCF2YWx1ZSkgcmV0dXJuIHRydWVcbiAgcmV0dXJuIGRhdGEubGFiZWwuaW5jbHVkZXModmFsdWUpXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA0LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA5LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDUsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogNixcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA3LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDgsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiJ9)

### Steps to reproduce

open in VSCODE：docs\examples\tree\filtering.vue

### What is Expected?

no type error

### What is actually happening?

Error：Types of parameters 'data' and 'data' are incompatible.
![image](https://github.com/element-plus/element-plus/assets/24362871/0529017c-2c81-4edb-b6e6-fbf7f4a2b587)

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
Type definition of the second parameter is `{ [key: string]: any }`. It's not assignable to type `Tree` because not all properties in type `Tree` are optional. AFAIK, there is no good solution until EP upgrades Vue version to 3.3.
