### ISSUE TITLE
[Docs] [All] 你们这个官网动不动就404，503，让人怎么用？？？？

### ISSUE THREAD

**Issue by wisdomwb** [element-plus/element-plus#12972]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `edge 113.0.1774.57 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message.html)

### Steps to reproduce

打开官网，看组件文档

### What is Expected?

正常显示

### What is actually happening?

404，503

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Recommended [element-plus.org](https://element-plus.org/)
https://github.com/element-plus/element-plus/issues/9196
