### ISSUE TITLE
[Bug Report] tree lazy load not work with axios

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#1297]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
macOS 10.15.7 / Chrome 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/tothingway/pen/oNzJpXB?editors=1111

### Steps to reproduce
1. use axios in load function
2. resolve axios response data
3. tree data not work

### What is Expected?
tree data work

### What is actually happening?
tree data not work

**Comment by Ryan2128** [comment]
Will fix soon.
