### ISSUE TITLE
[TypeScript] [input] :prefix-icon error

### ISSUE THREAD

**Issue by semanticDao** [element-plus/element-plus#12971]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.5`
- Browser / OS: `Chrome  112.0.5615.138`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyAsVXNlciwgTG9ja30gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgOnByZWZpeC1pY29uPVwiTG9ja1wiIC8+XG4gIDwhLS0gdGhpcyBlcnJvciBtc2cgZm9yIDpwcmVmaXgtaWNvbiBpbiB3ZWJzdG9ybSAtLT5cbiAgPCEtLVxuVHlwZSBEZWZpbmVDb21wb25lbnQ8e30sIHt9LCB7fSwgaW1wb3J0KFwidnVlXCIpLkNvbXB1dGVkT3B0aW9ucywgaW1wb3J0KFwidnVlXCIpLk1ldGhvZE9wdGlvbnMsIGltcG9ydChcInZ1ZVwiKS5Db21wb25lbnRPcHRpb25zTWl4aW4sIGltcG9ydChcInZ1ZVwiKS5Db21wb25lbnRPcHRpb25zTWl4aW4sIHt9LCBzdHJpbmcsIGltcG9ydChcInZ1ZVwiKS5WTm9kZVByb3BzICYgaW1wb3J0KFwidnVlXCIpLkFsbG93ZWRDb21wb25lbnRQcm9wcyAmIGltcG9ydChcInZ1ZVwiKS5Db21wb25lbnRDdXN0b21Qcm9wcywgUmVhZG9ubHk8aW1wb3J0KFwidnVlXCIpLkV4dHJhY3RQcm9wVHlwZXM8e30+Piwge30+IGlzIG5vdCBhc3NpZ25hYmxlIHRvIHR5cGUgc3RyaW5nIHwgQ29tcG9uZW50IFxuLS0+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus ,User, Lock} from '@element-plus/icons-vue'

const msg = ref('Hello World!')
</script>

<template>
  <h1>{{ msg }}</h1>
  <el-input v-model="msg" :prefix-icon="Lock" />
  
  

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>

### What is Expected?

no error msg 

### What is actually happening?

error display

### Additional comments

_(empty)_

**Comment by semanticDao** [comment]
![image](https://github.com/element-plus/element-plus/assets/102669067/8ca069e7-dba3-404b-84d5-01a8f37ea197)

**Comment by semanticDao** [comment]
![image](https://github.com/element-plus/element-plus/assets/102669067/7a7c0bb5-63b8-429f-b322-6dedcc9658e7)

**Comment by Brain777777** [comment]
@semanticDao This may be caused by WebStorm. It is recommended that you try using VSCode, which has better support for TS templates with `Volar` in VSCode.

**Comment by tolking** [comment]
It seems that WebStorm cannot correctly derive these two types.

We are currently unable to fix this issues.
