### ISSUE TITLE
[Docs] [dropdown] How do I only disable one button in dropdown split-button

### ISSUE THREAD

**Issue by roddc** [element-plus/element-plus#12993]
Bug Type: **`Docs`**

The disable prop in dropdown component will disable both buttons, but I would like to only disable the left button. Is there a way I can render my own button?
## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

None

### What is Expected?

Can only disable the left button of dropdown

### What is actually happening?

Disabled prop will disable both buttons

### Additional comments

_(empty)_

**Comment by Brain777777** [comment]
@roddc  Is this the usage method you need?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyxBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtYnV0dG9uLWdyb3VwPlxuICAgIDxlbC1idXR0b24gZGlzYWJsZWQgdHlwZT1cInByaW1hcnlcIj5CdXR0b248L2VsLWJ1dHRvbj5cbiAgICAgPGVsLWRyb3Bkb3duPlxuICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48QXJyb3dEb3duIC8+PC9lbC1pY29uPlxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgIDwvZWwtZHJvcGRvd24+XG4gIDwvZWwtYnV0dG9uLWdyb3VwPlxuICBcbiBcblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by roddc** [comment]
> @roddc Is this the usage method you need?
> 
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyxBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtYnV0dG9uLWdyb3VwPlxuICAgIDxlbC1idXR0b24gZGlzYWJsZWQgdHlwZT1cInByaW1hcnlcIj5CdXR0b248L2VsLWJ1dHRvbj5cbiAgICAgPGVsLWRyb3Bkb3duPlxuICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48QXJyb3dEb3duIC8+PC9lbC1pY29uPlxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgIDwvZWwtZHJvcGRvd24+XG4gIDwvZWwtYnV0dG9uLWdyb3VwPlxuICBcbiBcblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

Yeah, I can only think of this way, I thought there's a better way to do this.

**Comment by btea** [comment]
I think the implementation of @Brain777777  already meets your needs. What do you mean by better way? 🤔

**Comment by roddc** [comment]
> I think the implementation of @Brain777777 already meets your needs. What do you mean by better way? thinking

I mean there would be a slot to render the custom Button like [Ant Design Dropdown](https://ant.design/components/dropdown#dropdownbutton). I'm new to Vue and Element-plus, so I'm not sure how to do it. Nevermind. Thanks for the solution.
