### ISSUE TITLE
[Bug Report] element-plus中el-input-number组件，设置精度:precision="0"，可输入小数点（.）

### ISSUE THREAD

**Issue by ybj-github** [element-plus/element-plus#12998]
### Element Plus version
2.3.5

### OS/Browsers version
chrome / 113.0.5672.127（正式版本） （64 位）

### Vue version
3.3.4

### Reproduction Link
https://codepen.io/ybj-github/pen/MWPdEYz

### Steps to reproduce
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://unpkg.com/vue@next"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
    
    <script src="https://unpkg.com/element-plus"></script>
    <title>Element Plus demo</title>
  </head>
  <body>
    <div id="app">
       <el-input-number v-model="num" :precision="0" :max="10" />
    </div>
    <script>
      const App = {
        data() {
          return {
            num: 1,
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");
    </script>
  </body>
</html>

### What is Expected?
修复bug

### What is actually happening?
none

**Comment by chenxch** [comment]
This is a normal behavior of the control. If your business requirements cannot be input, please consider preventing input through keyboard events `.`.
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHJlZj1cImVsXCIgdi1tb2RlbD1cIm51bVwiIDptaW49XCIxXCIgOnByZWNpc2lvbj1cIjBcIiA6bWF4PVwiMTBcIiBAa2V5ZG93bj1cImhhbmRsZUNoYW5nZVwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMSlcbmNvbnN0IGVsID0gcmVmKG51bGwpXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoZSkgPT4ge1xuICBpZihlLmNvZGUgPT09ICdQZXJpb2QnKXtcbiAgICAvL251bS52YWx1ZT0gdmFsdWVcbiAgICBlLnByZXZlbnREZWZhdWx0KClcbiAgICBjb25zb2xlLmxvZyhlbC52YWx1ZSlcbiAgfVxuICBcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
