### ISSUE TITLE
[bug report] is imported on demand, and an error is prompted when using plugin

### ISSUE THREAD

**Issue by ansonvwang** [element-plus/element-plus#1301]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
macOS 10.15.7 / Chrome 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/ansonvwang/pen/ZEpwBEO

### Steps to reproduce
createApp(App).use(ElMessageBox) 报错，提示 类型“ElMessageBox”的参数不能赋给类型 “Plugin_2” 的参数

### What is Expected?
按需引入插件

### What is actually happening?
按需引入插件

**Comment by ansonvwang** [comment]
能否则代码层解决这个问题 我不想用 createApp(App).use(ElMessageBox as any) 这种方式

**Comment by JeremyWuuuuu** [comment]
Could be. Will fix soon, you can use `as any` for temporary fix/

**Comment by jiangshujsf** [comment]
> 能否则代码层解决这个问题 我不想用 createApp(App).use(ElMessageBox as any) 这种方式

不要再main.ts中引入这类插件，在需要使用的地方，用下面的方式引入就可以了
<template>
  <el-button :plain="true" @click="open">打开消息提示</el-button>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'
import { ElMessage } from 'element-plus'
export default defineComponent({
  setup() {
    return {
      open() {
        ElMessage('只是一条消息提示')
      }
    }
  }
})
</script>

<style>
</style>

**Comment by jiangshujsf** [comment]
> 能否则代码层解决这个问题 我不想用 createApp(App).use(ElMessageBox as any) 这种方式

不要在main.ts中按需引入这类插件，只需按需引入组件（ElButton）就可以了
main.ts

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import {
  ElButton
  // ElInfiniteScroll,
  // ElLoading,
  // ElMessage,
  // ElMessageBox,
  // ElNotification
} from 'element-plus'

const components = [ElButton]

// const plugins = [
//   ElInfiniteScroll,
//   ElLoading,
//   ElMessage,
//   ElMessageBox,
//   ElNotification
// ]
const app = createApp(App)

app.use(store)
app.use(router)

components.forEach(component => {
  app.component(component.name, component)
})

// plugins.forEach(plugin => {
//   app.use(plugin as any)
// })

app.mount('#app')


在其他需要使用的地方import { ElMessage } from 'element-plus'就可以用了，例如在App.vue中
<template>
  <el-button :plain="true" @click="open">打开消息提示</el-button>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'
import { ElMessage } from 'element-plus'
export default defineComponent({
  setup() {
    return {
      open() {
        ElMessage('只是一条消息提示')
      }
    }
  }
})
</script>

<style>
</style>
