### ISSUE TITLE
[Component] [table-column] table-column二次封装后无法传递#default插槽

### ISSUE THREAD

**Issue by YueYan11223** [element-plus/element-plus#13012]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.5`
- Browser / OS: `Chrome/113.0.5672.127 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCBQcm9qZWN0Q29sdW1uIGZyb20gJy4vUHJvamVjdENvbHVtbi52dWUnXG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBJVGFibGVSb3cge1xuICByYW5kb206IG51bWJlclxufVxub25Nb3VudGVkKCgpID0+IHtcbiAgZ2V0TGlzdCgpXG59KVxuY29uc3QgdGFibGVEYXRhID0gcmVmPElUYWJsZVJvd1tdPihbXSlcbi8vIOiOt+WPluWIl+ihqFxuY29uc3QgZ2V0TGlzdCA9ICgpID0+IHtcbiAgY29uc3QgbGlzdDogSVRhYmxlUm93W10gPSBbXVxuICBmb3IgKGxldCBpID0gMDsgaSA8IDU7IGkrKykge1xuICAgIGxpc3QucHVzaCh7XG4gICAgICByYW5kb206IE1hdGgucmFuZG9tKCksXG4gICAgfSlcbiAgfVxuICB0YWJsZURhdGEudmFsdWUgPSBsaXN0XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgdi1pZj1cIjFcIiA6ZGF0YT1cInRhYmxlRGF0YVwiIGJvcmRlciBzdHJpcGU+XG4gICAgPFByb2plY3RDb2x1bW4gcHJvcD1cInJhbmRvbVwiIGxhYmVsPVwi6ZqP5py65pWwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgICB7eyBzY29wZSB9fVxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvUHJvamVjdENvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gIH1cbn0iLCJQcm9qZWN0Q29sdW1uLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5cbi8vICNyZWdpb24gdHPmjqXlj6NcblxuaW50ZXJmYWNlIFByb3BzIHtcbiAgcHJvcD86IHN0cmluZ1xuICBsYWJlbDogc3RyaW5nXG4gIGFsaWduPzogJ2xlZnQnIHwgJ2NlbnRlcicgfCAncmlnaHQnXG4gIHNob3dPdmVyZmxvd1Rvb2x0aXA/OiBib29sZWFuXG59XG5cbi8vICNlbmRyZWdpb24gdHPmjqXlj6NcblxuLy8gI3JlZ2lvbiDnu4Tku7bkvKDlj4JcblxuY29uc3QgcHJvcHMgPSB3aXRoRGVmYXVsdHMoZGVmaW5lUHJvcHM8UHJvcHM+KCksIHtcbiAgYWxpZ246ICdsZWZ0JyxcbiAgc2hvd092ZXJmbG93VG9vbHRpcDogZmFsc2Vcbn0pXG5cbi8vICNlbmRyZWdpb24g57uE5Lu25Lyg5Y+CXG5cblxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICdQcm9qZWN0Q29sdW1uJyB9XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtY29sdW1uIDpwcm9wPVwicHJvcFwiIDpsYWJlbD1cImxhYmVsXCIgOmFsaWduPVwiYWxpZ25cIiA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwic2hvd092ZXJmbG93VG9vbHRpcFwiID5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgPHNsb3Qgdi1iaW5kPVwic2NvcGVcIiA+PC9zbG90PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdGFibGUtY29sdW1uPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJzY3NzXCIgc2NvcGVkPlxuPC9zdHlsZT4iLCJfbyI6e319)

### Steps to reproduce

在示例代码中,App.vue文件:如果注释掉<ProjectColumn>中的template代码;ProjectColumn.vue文件中注释<el-table-column>中的template代码,那么就可以正常渲染出"随机数"列

### What is Expected?

传递#default模板也能正常渲染出数据

### What is actually happening?

传递#default后报错,无法正常渲染

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCBQcm9qZWN0Q29sdW1uIGZyb20gJy4vUHJvamVjdENvbHVtbi52dWUnXG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBJVGFibGVSb3cge1xuICByYW5kb206IG51bWJlclxufVxub25Nb3VudGVkKCgpID0+IHtcbiAgZ2V0TGlzdCgpXG59KVxuY29uc3QgdGFibGVEYXRhID0gcmVmPElUYWJsZVJvd1tdPihbXSlcbi8vIOiOt+WPluWIl+ihqFxuY29uc3QgZ2V0TGlzdCA9ICgpID0+IHtcbiAgY29uc3QgbGlzdDogSVRhYmxlUm93W10gPSBbXVxuICBmb3IgKGxldCBpID0gMDsgaSA8IDU7IGkrKykge1xuICAgIGxpc3QucHVzaCh7XG4gICAgICByYW5kb206IE1hdGgucmFuZG9tKCksXG4gICAgfSlcbiAgfVxuICB0YWJsZURhdGEudmFsdWUgPSBsaXN0XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgdi1pZj1cIjFcIiA6ZGF0YT1cInRhYmxlRGF0YVwiIGJvcmRlciBzdHJpcGU+XG4gICAgPFByb2plY3RDb2x1bW4gcHJvcD1cInJhbmRvbVwiIGxhYmVsPVwi6ZqP5py65pWwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgICB7eyBzY29wZSB9fVxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgIDwvUHJvamVjdENvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gIH1cbn0iLCJQcm9qZWN0Q29sdW1uLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5cbi8vICNyZWdpb24gdHPmjqXlj6NcblxuaW50ZXJmYWNlIFByb3BzIHtcbiAgcHJvcD86IHN0cmluZ1xuICBsYWJlbDogc3RyaW5nXG4gIGFsaWduPzogJ2xlZnQnIHwgJ2NlbnRlcicgfCAncmlnaHQnXG4gIHNob3dPdmVyZmxvd1Rvb2x0aXA/OiBib29sZWFuXG59XG5cbi8vICNlbmRyZWdpb24gdHPmjqXlj6NcblxuLy8gI3JlZ2lvbiDnu4Tku7bkvKDlj4JcblxuY29uc3QgcHJvcHMgPSB3aXRoRGVmYXVsdHMoZGVmaW5lUHJvcHM8UHJvcHM+KCksIHtcbiAgYWxpZ246ICdsZWZ0JyxcbiAgc2hvd092ZXJmbG93VG9vbHRpcDogZmFsc2Vcbn0pXG5cbi8vICNlbmRyZWdpb24g57uE5Lu25Lyg5Y+CXG5cblxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5leHBvcnQgZGVmYXVsdCB7IG5hbWU6ICdQcm9qZWN0Q29sdW1uJyB9XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtY29sdW1uIDpwcm9wPVwicHJvcFwiIDpsYWJlbD1cImxhYmVsXCIgOmFsaWduPVwiYWxpZ25cIiA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwic2hvd092ZXJmbG93VG9vbHRpcFwiID5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7cm93LCBjb2x1bW4sICRpbmRleH1cIj5cbiAgICAgICAgPHNsb3Qgdi1iaW5kPVwie3JvdywgY29sdW1uLCAkaW5kZXh9XCI+PC9zbG90PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdGFibGUtY29sdW1uPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJzY3NzXCIgc2NvcGVkPlxuPC9zdHlsZT4iLCJfbyI6e319)

**Comment by YueYan11223** [comment]
感谢
