### ISSUE TITLE
[Docs] [input] 在edge dev版浏览器下样式不正确显示

### ISSUE THREAD

**Issue by 370295005** [element-plus/element-plus#13035]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)

### Steps to reproduce

使用edge dev版浏览器访问https://element-plus.org/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86
以及使用chrome浏览器访问同一页面

### What is Expected?

两个浏览器看到的组件样式一致

### What is actually happening?

edge dev浏览器的样式会显示不正确

### Additional comments

_(empty)_

**Comment by Lionad-Morotar** [comment]
在我的浏览器中没能复现问题

Microsoft Edge
版本 113.0.1774.50 (正式版本) (64 位)

![image](https://github.com/element-plus/element-plus/assets/26913795/e0428269-f626-4b4d-9e5b-44935e42b965)

**Comment by 370295005** [comment]
> 在我的浏览器中没能复现问题
> 
> Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)
> 
> ![image](https://user-images.githubusercontent.com/26913795/242677041-e0428269-f626-4b4d-9e5b-44935e42b965.png)

更新了edge dev后样式正常
![image](https://github.com/element-plus/element-plus/assets/39272235/fe0591f3-2ca3-408f-bfc5-e91535dff6c3)
