### ISSUE TITLE
[TypeScript] [All] Error when extending an Element component?

### ISSUE THREAD

**Issue by trandaison** [element-plus/element-plus#13047]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

I would like to create a wrap component for `el-form-item`. This component should `extends FormItemProps`, some like this

```vue
<script lang="ts" setup>
import { FormItemProps } from 'element-plus/es/components';

interface Props extends FormItemProps {
  hint?: string;
}

const props = defineProps<Props>();
</script>

<template>
  <el-form-item v-bind="$attrs">
    <slot />
    <span v-if="hint">{{ hint }}</span>
  </el-form-item>
</template>
```

And use the component

```vue
<FormItem label="Error" hint="Lorem ipsum">
  <el-input v-model="input" placeholder="Placeholder" />
</FormItem>
```

But I got an error from typescript as below:

### What is Expected?

There are no type error.

### What is actually happening?

Type error.

<img width="774" alt="Screen Shot 2023-06-01 at 21 44 04" src="https://github.com/element-plus/element-plus/assets/13447235/00b3cb1a-4990-48a0-87c6-0a67a530ba66">
<img width="762" alt="Screen Shot 2023-06-01 at 21 44 25" src="https://github.com/element-plus/element-plus/assets/13447235/f3734b55-f6c7-4080-b1d0-359064b96677">

### Additional comments

_(empty)_

**Comment by btea** [comment]
Two solutions:

The first: When the custom component declares prop, pass the value directly instead of the type.
```vue
<script lang="ts" setup>
import { formItemProps} from 'element-plus/es/components';

const props = defineProps({
  hint: {
    type: String,
    default: '',
  },
  ...formItemProps,
});
</script>

<template>
  <el-form-item v-bind="$attrs">
    <slot />
    <span v-if="hint">{{ hint }}</span>
  </el-form-item>
</template>
```

The second: Pass values ​​to props that require default values.
```vue
<FormItem label="Error" hint="Lorem ipsum" labelWidth="" inlineMessage="" :showMessage="true">
  <el-input v-model="input" placeholder="Placeholder" />
</FormItem>
```

**Comment by trandaison** [comment]
@btea Thanks for your support.

I confirm that those two solutions work. Or this type-based declaration will work as well.

```ts
interface Props extends FormItemProps {
  hint?: string;
}

const props = withDefaults(defineProps<Props>(), {
  hint: '',
  label: '',
  labelWidth: '',
  inlineMessage: '',
  showMessage: true,
});
```
