### ISSUE TITLE
[Component] [drawer] drawer关闭遮罩显示时无法点击遮罩关闭

### ISSUE THREAD

**Issue by xianengzhi** [element-plus/element-plus#13045]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `macOs 12`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgIH0gZnJvbSAndnVlJ1xuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gdHJ1ZVwiPmRyYXdlcjwvZWwtYnV0dG9uPlxuICA8ZWwtZHJhd2VyXG4gICAgdi1tb2RlbD1cInZpc2libGVcIlxuICAgIGNsYXNzPVwic21zLWRyYXdlclwiXG4gICAgc2l6ZT1cIjM4NHB4XCJcbiAgICBhcHBlbmQtdG8tYm9keVxuICAgIDp3aXRoLWhlYWRlcj1cImZhbHNlXCJcbiAgICA6Y2xvc2Utb24tY2xpY2stbW9kYWw9XCJ0cnVlXCJcbiAgICA6bW9kYWw9XCJmYWxzZVwiXG4gICAgOnNob3ctY2xvc2U9XCJmYWxzZVwiXG4gID5cbiAgICAxMjNcbiAgPC9lbC1kcmF3ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.点击按钮打开抽屉弹框
2.点击弹框外蒙层

### What is Expected?

关闭抽屉弹框

### What is actually happening?

没有反应

### Additional comments

dialog组件是加custom-mask-event属性排除el-overlay监听
然后自己加一层div来实现@click="overlayEvent.onClick"
所以我想drawer应该也可以这么做

**Comment by sleepyShen1989** [comment]
modal属性使用默认值true就能点击遮罩关闭了，不知道这是不是你想要的

**Comment by chenxch** [comment]
从demo来看你已经取消了modal，何来点击modal关闭这么一说。至于为什么不和dialog一样，通常来说drawer跟多的是作为一个辅助块出现，他需要和主区域联动操作，所以当modal设置为false的时候，更多的是需要和主区域做一些联动操作，如果的需求实在是需要modal为false且点击外部关闭，可以考虑clickoutside。

**Comment by chenxch** [comment]
@xianengzhi 如果没有其他问题，我先关闭这个问题了
