### ISSUE TITLE
[Component] [select] Select组件设置clearable为true，点击清空图标后，绑定值为空字符串，期望为undefined

### ISSUE THREAD

**Issue by heappynd** [element-plus/element-plus#13077]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome 113.0.0.0 / Win64`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnVzZXJfaWRcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc2l6ZT1cImxhcmdlXCIgY2xlYXJhYmxlPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxoMj57eyBmb3JtIH19PC9oMj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHt1c2VyX2lkOiB1bmRlZmluZWR9KVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6IDEsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAyLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDQsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiA1LFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. select 组件设置 clearable 为 true
2. 点击清空按钮

### What is Expected?

期望为 undefined

### What is actually happening?

为空字符串

### Additional comments

When the clearable property of the Select component is set to true, clicking on the clear icon sets the bound value to an empty string. I expect it to be set to undefined.

**Comment by chenxch** [comment]
Thank you for your feedback. This may be due to the different identification methods for empty options. This part is currently a continuation of the element-ui rules.

**Comment by heappynd** [comment]
Thank you for clarifying. I noticed that the SelectV2 component has been modified to "undefined." Perhaps I can use the new select component to solve my issue.

**Comment by chenxch** [comment]
If you need to set it to undefined in select, you can modify it in the @clear event.

**Comment by Azraelj** [comment]
> If you need to set it to undefined in select, you can modify it in the @clear event.

clear事件触发时点晚于change事件
