### ISSUE TITLE
[Bug Report] Row selection button of table can still be clicked even it's disabled (no rows).

### ISSUE THREAD

**Issue by ro-n** [element-plus/element-plus#1307]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
OSX Catalina

### Vue version
3.0.5

### Reproduction Link
jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
![A](https://user-images.githubusercontent.com/66688118/104947750-2eafcf00-59f7-11eb-9d09-bc8d0128d6d2.gif)

### What is Expected?
Disabled button should not be clicked.

### What is actually happening?
Disabled button is clicked.

**Comment by justwiner** [comment]
This is because when the checkbox is disabled, the click event of the checkbox will still be triggered. 
I will make a judgment inside the table first, but I think the best way is to solve this problem from the check box component, because I think that when the check box is disabled, it cannot trigger the click event of the check box.

**Comment by Ryan2128** [comment]
Is it possible that this bug has been fixed in #1294 ? @justwiner

**Comment by Ryan2128** [comment]
That pr is merged after `1.0.1-beta.27`.

**Comment by justwiner** [comment]
https://github.com/element-plus/element-plus/blob/df6918f51c7bcbe7f6997df7338a3dd73aa9d00f/packages/table/src/config.ts#L34-L45

this need to add a judgment when the click event is triggered:
```js
    renderHeader: function({ store: store_ }) {
      const store = store_ as Store
      function isDisabled() {
        return store.states.data.value && store.states.data.value.length === 0
      }
      return h(ElCheckbox, {
        disabled: isDisabled(),
        indeterminate:
          store.states.selection.value.length > 0 &&
          !store.states.isAllSelected.value,
        onClick: () => {
          // this line
          !isDisabled() && store.toggleAllSelection()
          // END
        },
        modelValue: store.states.isAllSelected.value,
      })
    },
```

**Comment by justwiner** [comment]
I don’t know whether the click event should be triggered when the `checkbox` component is `disabled`. This may need to be discussed.
@Ryan2128

**Comment by Ryan2128** [comment]
I think the click event should not be triggered when the `checkbox` component is `disabled`.

**Comment by Ryan2128** [comment]
I think the click event should be triggered when the `checkbox` component is `disabled`.  Is there another event to make `modelValue` of checkbox change? Maybe `update:modelValue`?
