### ISSUE TITLE
[dialog] 还请项目开发团队能够遵循语义化版本规则，请勿在次要版本中移除特性

### ISSUE THREAD

**Issue by tu6ge** [element-plus/element-plus#13092]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `any`
- Build Tool: `Other`

### Related Component

- `el-dialog`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dialog.html#attributes)

### Steps to reproduce

custom-class 已被 弃用, 之后 将会被 移除到 
2.3.0, 请使用 class.

### What is Expected?

遵循语义化版本 https://semver.org/lang/zh-CN/

### What is actually happening?

在次要版本中移除了 custom-class 的支持

### Additional comments

这样是超出其他开发者预期的行为，损害了框架的信誉

**Comment by tu6ge** [comment]
可以使用 deprecated 标识将要弃用的特性，在下次主版本号变更时移除该特性
```
/**
 * @deprecated 将于下个版本 1.0.2 被弃用
 */
```

**Comment by chenxch** [comment]
> 可以使用 deprecated 标识将要弃用的特性，在下次主版本号变更时移除该特性
> 
> ```
> /**
>  * @deprecated 将于下个版本 1.0.2 被弃用
>  */
> ```

Good idea.

**Comment by tu6ge** [comment]
？啥情况？留下一句话就关闭了吗，还是说解决了？

**Comment by tu6ge** [comment]
@chenxch 其实如果 issue 跟 pr 关联后，当 pr 合并的时候，该 issue 可以自动关闭
