### ISSUE TITLE
[Component] [skeleton] Skeleton 骨架屏 rows

### ISSUE THREAD

**Issue by RayJason** [element-plus/element-plus#13094]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Safari 16.4 / macOS 14`
- Build Tool: `Nuxt`

### Related Component

- `el-skeleton`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/skeleton.html#更多参数)

### Steps to reproduce

<template>
  <el-skeleton :rows="5" />
</template>

### What is Expected?

Expect to get 5 rows

### What is actually happening?

Actually gets 6 rows

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
文档中已说明了哦。
