### ISSUE TITLE
[Component] [table] Table filter selections doesn't update when "filtered-value" changes

### ISSUE THREAD

**Issue by Karolis-Stoncius** [element-plus/element-plus#13105]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome 114.0.5735.90 / Windows 10 Pro`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uXG4gICAgdi1mb3I9XCJkYXRlIG9mIGZpbHRlcnMuZGF0ZVwiXG4gICAgOmtleT1cImRhdGVcIlxuICAgIEBjbGljaz1cIigpID0+IGhhbmRsZVJlbW92ZShkYXRlKVwiXG4gID5cbiAgICB7eyBkYXRlIH19XG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIEBmaWx0ZXItY2hhbmdlPVwib25GaWx0ZXJDaGFuZ2VcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICBwcm9wPVwiZGF0ZVwiXG4gICAgICBsYWJlbD1cIkRhdGVcIlxuICAgICAgc29ydGFibGVcbiAgICAgIHdpZHRoPVwiMTgwXCJcbiAgICAgIGNvbHVtbi1rZXk9XCJkYXRlXCJcbiAgICAgIDpmaWx0ZXJzPVwiW1xuICAgICAgICB7IHRleHQ6ICcyMDE2LTA1LTAxJywgdmFsdWU6ICcyMDE2LTA1LTAxJyB9LFxuICAgICAgICB7IHRleHQ6ICcyMDE2LTA1LTAyJywgdmFsdWU6ICcyMDE2LTA1LTAyJyB9LFxuICAgICAgICB7IHRleHQ6ICcyMDE2LTA1LTAzJywgdmFsdWU6ICcyMDE2LTA1LTAzJyB9LFxuICAgICAgICB7IHRleHQ6ICcyMDE2LTA1LTA0JywgdmFsdWU6ICcyMDE2LTA1LTA0JyB9LFxuICAgICAgXVwiXG4gICAgICA6ZmlsdGVyZWQtdmFsdWU9XCJmaWx0ZXJzLmRhdGVcIlxuICAgIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiPlxuZXhwb3J0IGRlZmF1bHQge1xuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBmaWx0ZXJzOiB7IGRhdGU6IFsnMjAxNi0wNS0wMyddIH0sXG4gICAgICB0YWJsZURhdGE6IFtcbiAgICAgICAge1xuICAgICAgICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfVxuICB9LFxuXG4gIG1ldGhvZHM6IHtcbiAgICBvbkZpbHRlckNoYW5nZSh2YWx1ZSkge1xuICAgICAgZm9yIChjb25zdCBwcm9wZXJ0eSBpbiB2YWx1ZSkge1xuICAgICAgICBpZiAodmFsdWVbcHJvcGVydHldID09PSAnJykge1xuICAgICAgICAgIHRoaXMuZmlsdGVyc1twcm9wZXJ0eV0gPSBbXVxuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIHRoaXMuZmlsdGVyc1twcm9wZXJ0eV0gPSB2YWx1ZVtwcm9wZXJ0eV1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0sXG4gICAgaGFuZGxlUmVtb3ZlKHZhbHVlKSB7XG4gICAgICB0aGlzLmZpbHRlcnMuZGF0ZSA9IHRoaXMuZmlsdGVycy5kYXRlLmZpbHRlcigoZGF0ZSkgPT4gZGF0ZSAhPT0gdmFsdWUpXG4gICAgfSxcbiAgfSxcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Update "filtered-value" outside of the el-table filter selection.

### What is Expected?

el-table filter selection should update (removed items should be unselected)

### What is actually happening?

el-table filter selection doesn't update 

### Additional comments

I'm trying to add special buttons for displaying active filters. When a user clicks on one of them - a filter selection is removed and the table's selected filters should update accordingly.

**Comment by victoryning** [comment]
So far, it doesn't seem to be working.
