### ISSUE TITLE
[Component] el-dropdown按照官方文档指示使用，但下拉条的功能失效了

### ISSUE THREAD

**Issue by HDUysz** [element-plus/element-plus#13106]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome/114.0.5735.90/Windows10`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-dropdown-item`
- `el-dropdown-menu`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-8xw5fs?file=/src/App.vue)

### Steps to reproduce

我正在使用element-plus，在期望使用一个下拉的dropdown组件的时候，我发现我引入它之后它表现得和普通的span没有什么区别，让我十分疑惑，我在查询了官方文档的示例之后，确信我的使用方式是没有错的，但是不知道为什么出现了这样的问题。

### What is Expected?

鼠标移动到dropdown后出现下拉框

### What is actually happening?

没有任何效果

### Additional comments

_(empty)_

**Comment by btea** [comment]
下拉框内容应该使用 `slot` 传入，如下图所示
![image](https://github.com/element-plus/element-plus/assets/24516654/3ccbed88-528e-402e-adaf-a119bf4740da)

**Comment by HDUysz** [comment]
> 下拉框内容应该使用 `slot` 传入，如下图所示 ![image](https://user-images.githubusercontent.com/24516654/243520500-3ccbed88-528e-402e-adaf-a119bf4740da.png)

感谢，解决了
