### ISSUE TITLE
[Component] [dialog] Dialog的focusout事件影响了input的焦点

### ISSUE THREAD

**Issue by kimxu97** [element-plus/element-plus#13109]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.14`
- Browser / OS: `google`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBzaG93ID0gcmVmKHRydWUpXG5jb25zdCBpbnB1dCA9IHJlZignJylcbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgXHQ8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4XCI+XG4gICAgICA8ZGl2IGNsYXNzPVwibGVmdFwiPlxuICAgICAgICA8ZWwtZGlhbG9nXG4gICAgICAgICAgICAgICAgICAgdi1tb2RlbD1cInNob3dcIlxuICAgICAgICAgICAgICAgICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgICAgICAgICAgICAgICAgd2lkdGg9XCI3MCVcIlxuICAgICAgICAgICAgICAgICAgIDpjbG9zZS1vbi1jbGljay1tb2RhbD1cImZhbHNlXCJcbiAgICAgICAgICAgICAgICAgICA6Y2xvc2Utb24tcHJlc3MtZXNjYXBlPVwiZmFsc2VcIlxuICAgICAgICAgICAgICAgICAgID5cbiAgICAgICAgICA8c3Bhbj5UaGlzIGlzIGEgbWVzc2FnZTwvc3Bhbj5cbiAgICAgICAgPC9lbC1kaWFsb2c+XG4gXHRcdCA8L2Rpdj5cbiAgICAgPGRpdiBjbGFzcz1cInJpZ2h0XCI+XG4gICAgICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiID5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+ICAgICAgIFxuICAgICAgICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiAvPlxuICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICAgICAgPC9lbC10YWJsZT5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XHRcblx0XHRcbiAgXG5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInN0eWxlLmNzcyI6IiAgLmxlZnR7XG4gICAgZmxleDoxO1xuICAgIHdpZHRoOiA2MDBweDtcbiAgICBoZWlnaHQ6NjAwcHg7XG4gICAgYmFja2dyb3VuZDpncmVlbjtcbiAgICBwb3NpdGlvbjpyZWxhdGl2ZTtcbiAgfVxuLnJpZ2h0OntcbiAgd2lkdGg6MjAwcHg7XG59XG4uZWwtb3ZlcmxheS1kaWFsb2csLmVsLW92ZXJsYXkge1xuICAgIHBvc2l0aW9uOiB1bnNldCAhaW1wb3J0YW50O1xufVxuLmVsLW92ZXJsYXl7XG4gIFxuICAgIFx0aGVpZ2h0OmNhbGMoMTAwdmggLSAyMDBweCkhaW1wb3J0YW50O1xufSIsIl9vIjp7fX0=)

### Steps to reproduce

进去最小复现环境的链接之后，切换element版本为2.2.14，点击右边的table的输入框，会自动失去焦点,目前排查是class="el-dialog"这个元素的focusout引起，希望有解决办法。

### What is Expected?

正常获取焦点输入

### What is actually happening?

自动失去焦点

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这个应该是在2.2.17版本修复了
