### ISSUE TITLE
When [bug report] is introduced on demand, the internationalization configuration is invalid

### ISSUE THREAD

**Issue by fyunfei** [element-plus/element-plus#1310]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
Chrome  87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://github.com/fyunfei/element_plus_problem

### Steps to reproduce
- npm install
- npm run dev 
- the internationalization configuration is in main.js
- open browser and check content of datepicker

### What is Expected?
datepicker language is zh-cn

### What is actually happening?
datepicker language is still en

**Comment by zazzaz** [comment]
This is because you are using Vite. Vite will load the es bundle by default under `/es` not `/lib`
```
import { ElDatePicker, locale } from "element-plus";
import lang from "element-plus/es/locale/lang/zh-cn";
locale(lang);
```

**Comment by fyunfei** [comment]
It's useful for me, thank you very much

> This is because you are using Vite. Vite will load the es bundle by default under `/es` not `/lib`
> 
> ```
> import { ElDatePicker, locale } from "element-plus";
> import lang from "element-plus/es/locale/lang/zh-cn";
> locale(lang);
> ```
