### ISSUE TITLE
[Bug Report] I8n becomes English

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#1311]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
linxu centos

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/iamkun

### Steps to reproduce
I pulled the Git code from the server, packaged it and deployed it, and found that the buttons were in English, but from the local package they were in Chinese

### What is Expected?
The server packaging is also in Chinese, what should I do

### What is actually happening?
I pulled the Git code from the server, packaged it and deployed it, and found that the buttons were in English, but from the local package they were in Chinese

**Comment by zazzaz** [comment]
The default locale of Element Plus is English. If you want to use another language, you'll need to do some i18n configuration.

https://element-plus.org/#/en-US/component/i18n

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/104988098-2cc72980-5a52-11eb-9218-08a7a8e04202.png)
I've already introduced, it works locally, it doesn't work on the server

**Comment by wukang0718** [comment]
When I was running the development environment on the server, it was also in English

**Comment by wukang0718** [comment]
Does this have anything to do with my server?What do I need to configure on the server?

**Comment by wukang0718** [comment]
我调用了 `locale.use` 的方法了

**Comment by wukang0718** [comment]
I might guess that because of `cancelButtonText` and `confirmButtonText` in the `props` of the `MessageBox ` component, the `default` is English and should not use the `t` method to get the value of `i18n` by default

**Comment by zazzaz** [comment]
It's better to check your config. Or maybe you can give us a reproduction repo.

**Comment by JeremyWuuuuu** [comment]
Actually message box handles the translation correctly, see the screenshot:
![image](https://user-images.githubusercontent.com/15975785/105685848-85566500-5f31-11eb-89f3-db6d467a736d.png)

**Comment by JeremyWuuuuu** [comment]
I think you need to provide a reproducible demo for use to reproduce this issue, it might be caused by the wrong usage of `i18n` setting.

**Comment by wukang0718** [comment]
I have specified `cancelButtonText` and `confirmButtonText` of `message-box`, the problem has been solved

**Comment by JeremyWuuuuu** [comment]
> I have specified `cancelButtonText` and `confirmButtonText` of `message-box`, the problem has been solved

I know the cause of this bug, I will fix it immediately. Sorry for that.
