### ISSUE TITLE
[Component] [drawer] el-drawer组件在打开时屏幕为什么会闪一下

### ISSUE THREAD

**Issue by zhengwei-D** [element-plus/element-plus#13118]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc3R5bGU9XCJtYXJnaW4tbGVmdDogMTZweFwiIEBjbGljaz1cImRyYXdlciA9IHRydWVcIj5cbiAgICBvcGVuXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1kcmF3ZXIgdi1tb2RlbD1cImRyYXdlclwiIHRpdGxlPVwiSSBhbSB0aGUgdGl0bGVcIiA6d2l0aC1oZWFkZXI9XCJmYWxzZVwiPlxuICAgIDxzcGFuPkhpIHRoZXJlITwvc3Bhbj5cbiAgPC9lbC1kcmF3ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgZHJhd2VyID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

我不知道为什么复现环境里是没有这个问题的，但是目前的plus中drawer组件文档中的例子是有这个问题的，并且我自己的代码和文档中的例子的问题是一样的。就是每次在打开抽屉时，页面会先出现关闭抽屉的动画然后再打开，导致屏幕会闪一下

### What is Expected?

1

### What is actually happening?

1

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![drawer](https://github.com/element-plus/element-plus/assets/23251408/f02b9054-6e16-41d0-9f2e-123cd93ea59d)
方便提供录屏么

**Comment by chenxch** [comment]
![drawer-slow](https://github.com/element-plus/element-plus/assets/23251408/ef44f993-d88f-47d2-b381-012bc3c3478e)
这是慢速动画效果

**Comment by zhengwei-D** [comment]
> 
![GIF 2023-6-7 12-23-13](https://github.com/element-plus/element-plus/assets/12321764/b6ed4658-715e-4083-ad8d-57ce7657f6ec)

**Comment by zhengwei-D** [comment]
哦哦，我发现了，我用谷歌浏览器的话没问题，我用的是360极速浏览器就会有这个问题..........

**Comment by zhengwei-D** [comment]
但是360极速浏览器用的也是谷歌内核的啊，另外我用360极速浏览器访问上面那个复现环境就又是正常的了，plus官方文档内是不正常的.......

**Comment by zhengwei-D** [comment]
![image](https://github.com/element-plus/element-plus/assets/12321764/a924eb4f-9e5e-42e4-a0c2-76c0c4558049)

**Comment by chenxch** [comment]
不知道会不会是滚动条的问题，你可以尝试一下把lock-scroll设置为false

**Comment by zhengwei-D** [comment]
> 不知道会不会是滚动条的问题，你可以尝试一下把lock-scroll设置为false

试了...不行~

**Comment by liang-jingjing** [comment]
我也是遇到同样的问题，v-model绑定的变量，初始为false。但每次打开drawer时候，快速的隐藏然后再出现
![VeryCapture_20230616133736](https://github.com/element-plus/element-plus/assets/54902020/b07e605e-8b33-42e1-b15b-235b8c627d42)

**Comment by chenxch** [comment]
refer to #13216

**Comment by chenxch** [comment]
@liang-jingjing 试试无痕模式或者把插件什么先禁用一下
