### ISSUE TITLE
[Bug Report] ElLoading transition not work while loading open

### ISSUE THREAD

**Issue by xyorz** [element-plus/element-plus#1312]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
Chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xyorz/pen/poEQrwJ

### Steps to reproduce
click the open loading button

### What is Expected?
Loading opened with transition. Just like element-ui:
https://element.eleme.cn/#/zh-CN/component/loading#zheng-ye-jia-zai

### What is actually happening?
Loading opened without transition

**Comment by xyorz** [comment]
I had report about this the other day, but I found transition still not work while open ElLoading in latest version.

**Comment by Ryan2128** [comment]
Sorry, In the last fix, a detail was lost.

Will be fixed in next version.
