### ISSUE TITLE
[Component] [drawer] el-drawer 组件存在内存泄漏

### ISSUE THREAD

**Issue by orziz** [element-plus/element-plus#13128]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

1、不使用 el-drawer 组件未出现内存泄漏问题
2、使用 el-drawer 组件出现内存泄漏问题
3、使用 el-drawer 组件但 v-if 为 false 未出现内存泄漏问题
4、使用 el-drawer 组件切换一次 v-if 为 true 出现内存泄漏问题

### What is Expected?

组件正常销毁，不出现内存泄漏

### What is actually happening?

出现内存泄漏问题

### Additional comments

_(empty)_

**Comment by orziz** [comment]
el-dialog 同样有这个问题

**Comment by 1037055457** [comment]
何时能修复好这个内存泄漏问题啊

**Comment by mxismean** [comment]
一样的问题，drawer 关闭之后，内部的组件没有被销毁，导致一些不期望的业务问题发生
