### ISSUE TITLE
[Component] [select, dropdown] Dropdown options close immediately on mousehover.

### ISSUE THREAD

**Issue by adrkn** [element-plus/element-plus#13131]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `el-select`
- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLWRyb3Bkb3duIHRyaWdnZXI9XCJjbGlja1wiPlxuICA8ZWwtYnV0dG9uPkJ1dHRvbjwvZWwtYnV0dG9uPlxuICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1zcGFjZT5cbiAgICAgICAgICA8ZWwtdGV4dD5MYW5ndWFnZTo8L2VsLXRleHQ+XG4gICAgICAgICAgPGVsLXNlbGVjdD5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gdmFsdWU9XCJKYXZhc2NyaXB0XCIvPlxuICAgICAgICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIlR5cGVzY3JpcHRcIi8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgIDwvZWwtc3BhY2U+XG4gICAgICAgIDxicj48YnI+PGJyPjxicj48YnI+PGJyPiZuYnNwO1xuICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgPC90ZW1wbGF0ZT5cbjwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Use the el-select inside the el-dropdown

### What is Expected?

It should be possible to select an item from the options.

### What is actually happening?

The menu closes before you have time to select something.

### Additional comments

See the reproduction example.
The problem is observed only in version 2.3.6
If in the example we change the version to 2.3.5, then the problem disappears.
Apparently, this change broke the behavior of the select:

https://github.com/element-plus/element-plus/blob/dev/CHANGELOG.en-US.md
- Components [select] optimize the triggering of blur event (#11524 by @tolking)

**Comment by plehnen** [comment]
After updating element-plus from 2.3.5 to 2.3.6 the ElSelect (with multiple options) is broken. In our cypress test, most of the time it closes after the first option has been selected. Sometimes cypress is apparently fast enough to click the others, but it seems that after the first click (especially when the dropdown menu opens to the top, when the dropdown is placed at the last element on the page), it's closing instantly after the first option has been selected.

**Comment by tolking** [comment]
When the mouse pointer leave from `DropdownItem`, it will trigger the focus event change, causing the `Select` lose focus. 

The best solution is to use `Popover` instead of `Dropdown`.

Of course, currently `Dropdown` components can also be optimized, but there will still be some strange behaviors similar to before.
