### ISSUE TITLE
[Style] [sub-menu] 折叠状态下，鼠标移到 sub-menu 后，menu 右侧边框被遮挡

### ISSUE THREAD

**Issue by Lucky-Ya-Q** [element-plus/element-plus#13133]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-sub-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImlzQ29sbGFwc2VcIiBzdHlsZT1cIm1hcmdpbi1ib3R0b206IDIwcHhcIj5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIDpsYWJlbD1cImZhbHNlXCI+ZXhwYW5kPC9lbC1yYWRpby1idXR0b24+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCJ0cnVlXCI+Y29sbGFwc2U8L2VsLXJhZGlvLWJ1dHRvbj5cbiAgPC9lbC1yYWRpby1ncm91cD5cbiAgPGVsLW1lbnVcbiAgICBkZWZhdWx0LWFjdGl2ZT1cIjJcIlxuICAgIGNsYXNzPVwiZWwtbWVudS12ZXJ0aWNhbC1kZW1vXCJcbiAgICA6Y29sbGFwc2U9XCJpc0NvbGxhcHNlXCJcbiAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICAgIEBjbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgPlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjFcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgIDxlbC1pY29uPjxsb2NhdGlvbiAvPjwvZWwtaWNvbj5cbiAgICAgICAgPHNwYW4+TmF2aWdhdG9yIE9uZTwvc3Bhbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8ZWwtbWVudS1pdGVtLWdyb3VwPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPjxzcGFuPkdyb3VwIE9uZTwvc3Bhbj48L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgIDxlbC1tZW51LWl0ZW0tZ3JvdXAgdGl0bGU9XCJHcm91cCBUd29cIj5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudS1pdGVtLWdyb3VwPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMS00XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+PHNwYW4+aXRlbSBmb3VyPC9zcGFuPjwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjJcIj5cbiAgICAgIDxlbC1pY29uPjxpY29uLW1lbnUgLz48L2VsLWljb24+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPk5hdmlnYXRvciBUd288L3RlbXBsYXRlPlxuICAgIDwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCIgZGlzYWJsZWQ+XG4gICAgICA8ZWwtaWNvbj48ZG9jdW1lbnQgLz48L2VsLWljb24+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPk5hdmlnYXRvciBUaHJlZTwvdGVtcGxhdGU+XG4gICAgPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj5cbiAgICAgIDxlbC1pY29uPjxzZXR0aW5nIC8+PC9lbC1pY29uPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5OYXZpZ2F0b3IgRm91cjwvdGVtcGxhdGU+XG4gICAgPC9lbC1tZW51LWl0ZW0+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBEb2N1bWVudCxcbiAgTWVudSBhcyBJY29uTWVudSxcbiAgTG9jYXRpb24sXG4gIFNldHRpbmcsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBpc0NvbGxhcHNlID0gcmVmKHRydWUpXG5jb25zdCBoYW5kbGVPcGVuID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5lbC1tZW51LXZlcnRpY2FsLWRlbW86bm90KC5lbC1tZW51LS1jb2xsYXBzZSkge1xuICB3aWR0aDogMjAwcHg7XG4gIG1pbi1oZWlnaHQ6IDQwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

折叠状态下，鼠标移到 sub-menu 后，menu 右侧边框被遮挡

### What is Expected?

鼠标移到 sub-menu 后，menu 右侧边框正常显示

### What is actually happening?

鼠标移到 sub-menu 后，menu 右侧边框被遮挡

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/8b7c3776-be5d-43e3-afee-7fbbe07f7273)
方便截图看下具体是什么样的表现么，我在repo中并没有看到你说的情况，或许是我没理解到。

**Comment by Lucky-Ya-Q** [comment]
@chenxch 这里
![微信截图_20230608121241](https://github.com/element-plus/element-plus/assets/63504321/003c8ee9-7b2c-43b7-a69c-af7c164334f3)

**Comment by Lucky-Ya-Q** [comment]
@chenxch 你好，这个 pr 能合并吗

**Comment by chenxch** [comment]
> @chenxch 你好，这个 pr 能合并吗

请等待另一位reviewer确认。
