### ISSUE TITLE
[Bug Report] clearable is invalid after wrapping the el-date-picker component

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#1313]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
MacOS10.15.7 / Chrome 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-xv6jx?file=/src/myDate.vue:14-28

### Steps to reproduce
1. select a date 
2. click the clearable btn
3. the value is not cleared

### What is Expected?
value are cleared

### What is actually happening?
value is not cleared

**Comment by zazzaz** [comment]
You can not pass a `computed` value to `model-value`. Simply change it to normal data like:

```
<el-date-picker
    v-model="value"
    type="datetime"
  />


 data() {
    return {
      value: '',
    }
  },
```

**Comment by TothingWay** [comment]
Thank you. It's me.
