### ISSUE TITLE
[Component] [table, table-column] Fixed column style overrides row-class-name styles

### ISSUE THREAD

**Issue by msmosavar** [element-plus/element-plus#13130]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome 114.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBpZDogMSxcbiAgICBuYW1lOiAnbmFtZTEnLFxuICAgIGRlc2M6ICdkZXNjcmlwdGlvbjEnXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBuYW1lOiAnbmFtZTInLFxuICAgIGRlc2M6ICdkZXNjcmlwdGlvbjInXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBuYW1lOiAnbmFtZTMnLFxuICAgIGRlc2M6ICdkZXNjcmlwdGlvbjMnXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJkYXRhXCIgcm93LWNsYXNzLW5hbWU9XCJjdXN0b20tYmdcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGZpeGVkIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGVzY1wiIGxhYmVsPVwiRGVzY3JpcHRpb25cIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbiAgXG4gIDxlbC10YWJsZSA6ZGF0YT1cImRhdGFcIiByb3ctY2xhc3MtbmFtZT1cImN1c3RvbS1iZy12YXJcIiBzdHlsZT1cIm1hcmdpbi10b3A6IDMwcHg7XCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiPjwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRlc2NcIiBsYWJlbD1cIkRlc2NyaXB0aW9uXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIC5jdXN0b20tYmcge1xuICAgIGJhY2tncm91bmQtY29sb3I6IHJnYigyNTQgMjI2IDIyNikgIWltcG9ydGFudDtcbiAgfVxuICBcbiAgLmN1c3RvbS1iZy12YXIge1xuICAgIC8qIGV2ZW4gdXNpbmcgdGhlIGNzcyB2YXJpYWJsZXMgaGFzIHRoZSBzYW1lIGlzc3VlICovXG4gICAgLS1lbC10YWJsZS10ci1iZy1jb2xvcjogcmdiKDI1NCAyMjYgMjI2KTtcbiAgICAvKiB0aGUgb25seSB3YXkgdG8gbWFuYWdlIGl0IGlzIG92ZXJyaWRpbmcgLS1lbC1iZy1jb2xvciBhbG9uZyB3aXRoIC0tZWwtdGFibGUtdHItYmctY29sb3IgKi9cbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

- Create an `el-table` containing `row-class-name` that specifies `background-color`
- Provide some `el-table-column` components containing fixed column(s)

### What is Expected?

The class provided via `row-class-name` attribute should apply on whole row (including fixed column cells)

### What is actually happening?

Fixed column's `background-color` doesn't change to specified color

### Additional comments

As mentioned in the reproduced example, even using CSS variables (just like [docs](https://element-plus.org/en-US/component/table.html#table-with-status)) has the same issue and the only way to manage it is overriding `--el-bg-color` along with `--el-table-tr-bg-color`

**Comment by YUN-RU-TSENG** [comment]
i have same issue

**Comment by jswxwxf** [comment]
I have same issue, can someone please take a look?

**Comment by btea** [comment]
Just overwrite it with custom variables. [link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbmFtZTogJ25hbWUxJyxcbiAgICBkZXNjOiAnZGVzY3JpcHRpb24xJ1xuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgbmFtZTogJ25hbWUyJyxcbiAgICBkZXNjOiAnZGVzY3JpcHRpb24yJ1xuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgbmFtZTogJ25hbWUzJyxcbiAgICBkZXNjOiAnZGVzY3JpcHRpb24zJ1xuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwiZGF0YVwiIHJvdy1jbGFzcy1uYW1lPVwiY3VzdG9tLWJnXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiPjwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRlc2NcIiBsYWJlbD1cIkRlc2NyaXB0aW9uXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG4gIFxuICA8ZWwtdGFibGUgOmRhdGE9XCJkYXRhXCIgcm93LWNsYXNzLW5hbWU9XCJjdXN0b20tYmctdmFyXCIgc3R5bGU9XCJtYXJnaW4tdG9wOiAzMHB4O1wiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiPjwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkZXNjXCIgbGFiZWw9XCJEZXNjcmlwdGlvblwiPjwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuY3VzdG9tLWJnIHtcbiAgICAtLWVsLWJnLWNvbG9yOiByZ2IoMjU0LCAyMjYsIDIyNik7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NCAyMjYgMjI2KSAhaW1wb3J0YW50O1xuICB9XG4gIFxuICAuY3VzdG9tLWJnLXZhciB7XG4gICAgLyogZXZlbiB1c2luZyB0aGUgY3NzIHZhcmlhYmxlcyBoYXMgdGhlIHNhbWUgaXNzdWUgKi9cbiAgICAtLWVsLXRhYmxlLXRyLWJnLWNvbG9yOiByZ2IoMjU0IDIyNiAyMjYpO1xuICAgIC8qIHRoZSBvbmx5IHdheSB0byBtYW5hZ2UgaXQgaXMgb3ZlcnJpZGluZyAtLWVsLWJnLWNvbG9yIGFsb25nIHdpdGggLS1lbC10YWJsZS10ci1iZy1jb2xvciAqL1xuICB9XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)
