### ISSUE TITLE
[Component] [select-v2] Virtualized Select的placeholder属性无法显示文案

### ISSUE THREAD

**Issue by bigbigtime** [element-plus/element-plus#13137]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.6`
- Browser / OS: `版本 114.0.5735.110（正式版本） （64 位）/ win11`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[CodePen](https://codepen.io/iyccdiaq-the-bashful/pen/rNQaNdR)

### Steps to reproduce

初始化载入el-select-v2，默认配置placeholder属性

### What is Expected?

渲染placeholder属性配置的方案

### What is actually happening?

placeholder属性配置的方案无法正常渲染

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#13096

**Comment by makai1027** [comment]
解决了吗？大佬
