### ISSUE TITLE
[Component] [icon] 引用cdnjs中element-plus-icons-vue@2.1.0，图标不显示问题

### ISSUE THREAD

**Issue by renrenduxing** [element-plus/element-plus#13147]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG48IURPQ1RZUEUgaHRtbD5cbjxodG1sIGxhbmc9XCJlblwiPlxuPGhlYWQ+XG4gICAgPG1ldGEgY2hhcnNldD1cInV0Zi04XCIgLz5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLGluaXRpYWwtc2NhbGU9MSxtaW5pbXVtLXNjYWxlPTEuMCxtYXhpbXVtLXNjYWxlPTEuMCx1c2VyLXNjYWxhYmxlPW5vXCIgLz5cbiAgICA8dGl0bGU+5Y2P5a646L+b6ZSA5a2Y566h55CG57O757ufPC90aXRsZT5cbiAgICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cImh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb20vYWpheC9saWJzL2VsZW1lbnQtcGx1cy8yLjMuNC9pbmRleC5jc3NcIj5cbiAgICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cImh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb20vYWpheC9saWJzL2ZvbnQtYXdlc29tZS82LjQuMC9jc3MvYWxsLmNzc1wiPlxuICAgIDxzY3JpcHQgdHlwZT1cInRleHQvamF2YXNjcmlwdFwiIHNyYz1cImh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb20vYWpheC9saWJzL3Z1ZS8zLjIuNDcvdnVlLmdsb2JhbC5qc1wiPjwvc2NyaXB0PlxuICAgIDxzY3JpcHQgdHlwZT1cInRleHQvamF2YXNjcmlwdFwiIHNyYz1cImh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb20vYWpheC9saWJzL2VsZW1lbnQtcGx1cy8yLjMuNC9pbmRleC5mdWxsLm1pbi5qc1wiPjwvc2NyaXB0PlxuICAgIDxzY3JpcHQgdHlwZT1cInRleHQvamF2YXNjcmlwdFwiIHNyYz1cImh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb20vYWpheC9saWJzL2pxdWVyeS8zLjYuNC9qcXVlcnkubWluLmpzXCI+PC9zY3JpcHQ+XG4gICAgPHNjcmlwdCB0eXBlPVwidGV4dC9qYXZhc2NyaXB0XCIgc3JjPVwiaHR0cHM6Ly9jZG5qcy5jbG91ZGZsYXJlLmNvbS9hamF4L2xpYnMvZWxlbWVudC1wbHVzLWljb25zLXZ1ZS8yLjEuMC9nbG9iYWwuaWlmZS5taW4uanNcIj48L3NjcmlwdD5cbiAgICAgXG48L2hlYWQ+XG48Ym9keT5cbiAgICBcbjxkaXYgaWQ9XCJhcHBcIj5cbiAgICA8ZWwtZm9ybSBsYWJlbC1wb3NpdGlvbj1cInRvcFwiXG4gICAgICAgICAgICAgbGFiZWwtd2lkdGg9XCIxMDBweFwiXG4gICAgICAgICAgICAgc3R5bGU9XCJtYXgtd2lkdGg6IDQ2MHB4XCI+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLnlKjmiLflkI1cIj5cbiAgICAgICAgICAgIDxlbC1pbnB1dCBwbGFjZWhvbGRlcj1cIueUqOaIt+WQjVwiIDpzdWZmaXgtaWNvbj1cIlVzZXJGaWxsZWRcIj48L2VsLWlucHV0PlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWvhueggVwiPlxuICAgICAgICAgICAgPGVsLWlucHV0IHBsYWNlaG9sZGVyPVwi5a+G56CBXCI+PC9lbC1pbnB1dD5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLpqozor4HnoIFcIj5cbiAgICAgICAgICAgIDxlbC1pbnB1dCBwbGFjZWhvbGRlcj1cIumqjOivgeeggVwiPjwvZWwtaW5wdXQ+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib25TdWJtaXRcIj5DcmVhdGU8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dDFcIlxuICAgICAgICAgICAgICAgICAgY2xhc3M9XCJ3LTUwIG0tMlwiXG4gICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXRlXCJcbiAgICAgICAgICAgICAgICAgIDpzdWZmaXgtaWNvbj1cIlVzZXJGaWxsZWRcIiAvPlxuICAgICAgICA8ZWwtaWNvbj48aSBjbGFzcz1cIlVzZXJGaWxsZWRcIj48L2k+PC9lbC1pY29uPlxuICAgICAgICA8ZWwtaWNvbj48VXNlckZpbGxlZD48L1VzZXJGaWxsZWQ+PC9lbC1pY29uPlxuICAgIDwvZWwtZm9ybT5cbiBcbjwvZGl2PlxuXG5cbiAgICBcbiAgICBcbiAgICA8c2NyaXB0PlxuICAgICBcblxuICAgICAgICBjb25zdCBBcHAgPSB7XG4gICAgICAgICAgICBkYXRhKCkge1xuICAgICAgICAgICAgICAgIHJldHVybiB7XG5cbiAgICAgICAgICAgICAgICB9O1xuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIG1vdW50ZWQoKSB7XG4gICAgICAgICAgICAgICAgXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgbWV0aG9kczoge1xuICAgICAgICAgICAgICAgIG9uU3VibWl0KCkge1xuXG4gICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIH1cbiAgICAgICAgfTtcblxuICAgICAgICBjb25zdCBhcHAgPSBWdWUuY3JlYXRlQXBwKEFwcCk7XG4gICAgICAgIGFwcC51c2UoRWxlbWVudFBsdXMpO1xuICAgICAgICBhcHAuY29tcG9uZW50KCdVc2VyRmlsbGVkJywgRWxlbWVudFBsdXNJY29uc1Z1ZS5Vc2VyRmlsbGVkKTtcbiAgICAgICAgYXBwLm1vdW50KFwiI2FwcFwiKTtcblxuXG4gICAgPC9zY3JpcHQ+XG4gICAgXG48L2JvZHk+XG48L2h0bWw+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

 app.component('UserFilled', ElementPlusIconsVue.UserFilled);

### What is Expected?

图标能够显示

### What is actually happening?

图标没有显示

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/90117fa1-9651-43d6-a7d0-f6c928cf9365)
注意闭标签和组件使用kebab-case方式使用。

**Comment by chenxch** [comment]
那这个就是另一个问题了。
如果需要在插槽内显示请在data中定义UserFilled
```
return {
                  UserFilled: ElementPlusIconsVue.UserFilled
                };
```

**Comment by renrenduxing** [comment]
感谢您的解答，我在data加入了UserFilled: ElementPlusIconsVue.UserFilled之后，input插槽中确实可以显示图标了，
现在还有个问题通过app.component('uff', ElementPlusIconsVue.UserFilled);注册组件后，
		<el-icon><uff></uff></el-icon>
        <el-icon><uff /></el-icon>两种方式仍然无法显示图标，请问这个是什么原因？

**Comment by renrenduxing** [comment]
已经尝试出来了，大概率是变量/名称冲突，感谢
