### ISSUE TITLE
[Component] [date-picker, popover] popover 组件弹出框里使用 date-picker，点击日期选择弹出面板内时，会关闭全部的弹出框

### ISSUE THREAD

**Issue by SeptEarlyMorning** [element-plus/element-plus#13150]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome/113.0.5672.129（正式版本） （64 位）`
- Build Tool: `Other`

### Related Component

- `el-date-picker`
- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlclwiPlxuICAgIDxlbC1wb3BvdmVyIHBsYWNlbWVudD1cInJpZ2h0XCIgOndpZHRoPVwiNDAwXCIgdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgPGVsLWJ1dHRvbiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMTZweFwiPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCJcbiAgICAgICAgOnNpemU9XCJzaXplXCJcbiAgICAgIC8+XG4gICAgPC9lbC1wb3BvdmVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gaW1wb3J0IHtyZWZ9IGZyb20gXCJ2dWVcIlxuY29uc3QgZ3JpZERhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ0phY2snLFxuICAgIGFkZHJlc3M6ICdOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnSmFjaycsXG4gICAgYWRkcmVzczogJ05ldyBZb3JrIENpdHknLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKYWNrJyxcbiAgICBhZGRyZXNzOiAnTmV3IFlvcmsgQ2l0eScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ0phY2snLFxuICAgIGFkZHJlc3M6ICdOZXcgWW9yayBDaXR5JyxcbiAgfSxcbl1cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.点击按钮
2.点击日期控件
3.点击日期控件的弹出框

### What is Expected?

两个弹出框均不消失

### What is actually happening?

两个弹出框均消失

### Additional comments

_(empty)_

**Comment by xingyixiang** [comment]
这应该不是问题，可以使用el-date-picker的:teleported="false"实现你想要的效果
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlclwiPlxuICAgIDxlbC1wb3BvdmVyIHBsYWNlbWVudD1cInJpZ2h0XCIgOndpZHRoPVwiNDAwXCIgdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgPGVsLWJ1dHRvbiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMTZweFwiPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCJcbiAgICAgICAgOnNpemU9XCJzaXplXCJcbiAgICAgICAgOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiXG4gICAgICAvPlxuICAgIDwvZWwtcG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuIGltcG9ydCB7cmVmfSBmcm9tIFwidnVlXCJcbmNvbnN0IGdyaWREYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdKYWNrJyxcbiAgICBhZGRyZXNzOiAnTmV3IFlvcmsgQ2l0eScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0phY2snLFxuICAgIGFkZHJlc3M6ICdOZXcgWW9yayBDaXR5JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnSmFjaycsXG4gICAgYWRkcmVzczogJ05ldyBZb3JrIENpdHknLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdKYWNrJyxcbiAgICBhZGRyZXNzOiAnTmV3IFlvcmsgQ2l0eScsXG4gIH0sXG5dXG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
