### ISSUE TITLE
[All] No tag version or git head were found, make sure that you set the environment variable $TAG_VERSION 

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#13166]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.4`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus.git)

### Steps to reproduce

pnpm update:version

### What is Expected?

no error

### What is actually happening?

 ERROR  No tag version or git head were found, make sure that you set the environment variable $TAG_VERSION

### Additional comments

null

**Comment by jw-foss** [comment]
Please do not raise irrelevant issue if this is not related to the project itself, if you want to know how the project works, please go read the source code and get to know about the basic information about GitHub Actions and Environment Variables, those documents can be easily found at the bottom of this very website.
