### ISSUE TITLE
The problem of element plus table data display is affected by the style

### ISSUE THREAD

**Issue by Caoxiongk** [element-plus/element-plus#1317]
![image](https://user-images.githubusercontent.com/44657881/105022087-4aad8200-5a84-11eb-8e3e-2e8493473f8f.png)
当table-layout: fixed时，头部无法对齐
table-layout: auto时，可以对其
这个是框架自带的样式，需要调整和解决

**Comment by Caoxiongk** [comment]
可以提供一个远程的软件给你们现场调试 因为我刚用你们那个在线的没有问题

**Comment by Caoxiongk** [comment]
升级版本后 暂无问题了 估计是版本影响的

**Comment by kooriookami** [comment]
Since there is no problem, close this issue.

**Comment by chenlike** [comment]
封装el-table的时候重现了 [https://github.com/chenlike/element-issue](url)
chrome版本:87.0.4280.141（正式版本） （64 位）
![pic](https://user-images.githubusercontent.com/20675545/105152567-565f7e00-5b42-11eb-8b9d-7effd45ffea4.png)

**Comment by Ryan2128** [comment]
cc @justwiner

**Comment by XingXiaoWu** [comment]
same question

**Comment by justwiner** [comment]
hey guys.
Maybe duplicate #1330. 
I have fixed the issue of #1330. Please confirm whether there is such a problem in the subsequent new version.

**Comment by Ryan2128** [comment]
@Caoxiongk @chenlike @XingXiaoWu 

#1334 has been merged, please confirm whether there is such a problem in next new version.

**Comment by Ryan2128** [comment]
@Caoxiongk @chenlike @XingXiaoWu 

New version has been published, please check if the bug is fixed.

**Comment by Ryan2128** [comment]
Since there is no reply for too long, close this issue, if there are still problems, please reopen.
