### ISSUE TITLE
[Component] [cascader] Cascader 在Dialog里的 form表单里 开启 multiple 多选后 显示高度会有问题

### ISSUE THREAD

**Issue by ctl1148116524** [element-plus/element-plus#13176]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.6`
- Browser / OS: `edge114.0.1823.43`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus.git)

### Steps to reproduce

在最新的element-plus 中 项目中使用了@use "element-plus/theme-chalk/src/index.scss"as *;并且在dialog里的el-form里,并开启 multiple 多选,会触发这个问题 之前的版本则不会

### What is Expected?

高度正常

### What is actually happening?

高度为0.5px

### Additional comments

_(empty)_

**Comment by ctl1148116524** [comment]
![微信截图_20230612172640](https://github.com/element-plus/element-plus/assets/67696132/87366db4-6f95-40ff-b1d3-86fe1aa4f408)

**Comment by yj-liuzepeng** [comment]
<img width="876" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/11d49a00-f9d9-4501-91e0-689774835a2d">

没有复现，能否给个demo: [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by ctl1148116524** [comment]
@yj-liuzepeng https://github.com/ctl1148116524/element-Cascader-demo 这个是github demo的地址 因为用到了主题css,没办法在Element Plus Playground 里复现

**Comment by yj-liuzepeng** [comment]
@ctl1148116524 看了一下demo，应该不是element-plus的问题，是你demo中 postcss-plugin-px2rem 这个插件的原因，去掉这个插件后是正常的，或者参考  [csdn](https://blog.csdn.net/Kerwin_yue/article/details/123473665?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-4-123473665-blog-84633110.235^v38^pc_relevant_anti_t3_base&spm=1001.2101.3001.4242.3&utm_relevant_index=7)

**Comment by ctl1148116524** [comment]
> @ctl1148116524 看了下demo，应该不是element-plus的问题，是你demo中 postcss-plugin-px2rem 这个插件的原因，去掉这个插件后是正常的，或者参考 [csdn](https://blog.csdn.net/Kerwin_yue/article/details/123473665?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-4-123473665-blog-84633110.235%5Ev38%5Epc_relevant_anti_t3_base&spm=1001.2101.3001.4242.3&utm_relevant_index=7)
还真是这个的问题,因为之前的element-plus2.2.17是好的,感谢解决问题
