### ISSUE TITLE
[Component] [steps] Steps process-status无法控制当前步骤状态，全部被finish-status控制了

### ISSUE THREAD

**Issue by meteorice** [element-plus/element-plus#13170]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.30`
- Browser / OS: `Intel Mac OS X`
- Build Tool: `Vite`

### Related Component

- `el-steps`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc3RlcHMgYWN0aXZlPVwiM1wiIHByb2Nlc3Mtc3RhdHVzPVwiZXJyb3JcIiBmaW5pc2gtc3RhdHVzPVwiZmluaXNoXCI+XG4gICAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAxXCIgZGVzY3JpcHRpb249XCJTb21lIGRlc2NyaXB0aW9uXCIgLz5cbiAgICAgICAgPGVsLXN0ZXAgdGl0bGU9XCJTdGVwIDJcIiBkZXNjcmlwdGlvbj1cIlNvbWUgZGVzY3JpcHRpb25cIiAvPlxuICAgICAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgM1wiIGRlc2NyaXB0aW9uPVwiU29tZSBkZXNjcmlwdGlvblwiIC8+XG4gICAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCA0XCIgZGVzY3JpcHRpb249XCJTb21lIGRlc2NyaXB0aW9uXCIgLz5cbiAgICA8L2VsLXN0ZXBzPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<el-steps active="3" process-status="error" finish-status="finish">
    <el-step title="Step 1" description="Some description" />
    <el-step title="Step 2" description="Some description" />
    <el-step title="Step 3" description="Some description" />
    <el-step title="Step 4" description="Some description" />
</el-steps>

### What is Expected?

step1,step2 是 finish 状态，step3 是 error 状态
step4是 wait 状态

### What is actually happening?

step1,step2,step3都是 finish 状态，step4是 wait 状态

### Additional comments

_(empty)_

**Comment by sleepyShen1989** [comment]
`el-steps`中的active接收的是一个从0开始的数字 改成`:active="2"`就行了

**Comment by yj-liuzepeng** [comment]
<img width="604" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/a6725f13-6454-446e-a08c-f2087bb0ecc4">

**Comment by meteorice** [comment]
不对哦！
我的意思不是位置不对，是状态不对。process-status="error" 的红色状态提现在哪里？当前错误状态
<img width="1659" alt="image" src="https://github.com/element-plus/element-plus/assets/11306060/21bc852a-a377-4dd7-9c01-e710ddf39613">

**Comment by meteorice** [comment]
> `el-steps`中的active接收的是一个从0开始的数字 改成`:active="2"`就行了

不对哦！
我的意思不是位置不对，是状态不对。process-status="error" 的红色状态提现在哪里？当前错误状态
![image](https://github.com/element-plus/element-plus/assets/11306060/0207bdb2-b7ae-4034-84fd-cae1c034da78)
finish-status="error" 把之前的状态都改成 error 了
<img width="1208" alt="image" src="https://github.com/element-plus/element-plus/assets/11306060/91e82436-f3dc-428e-8aab-924ebe18b06f">

**Comment by sleepyShen1989** [comment]
> > `el-steps`中的active接收的是一个从0开始的数字 改成`:active="2"`就行了
> 
> 不对哦！ 我的意思不是位置不对，是状态不对。process-status="error" 的红色状态提现在哪里？当前错误状态 ![image](https://user-images.githubusercontent.com/11306060/245667362-0207bdb2-b7ae-4034-84fd-cae1c034da78.png) finish-status="error" 把之前的状态都改成 error 了 <img alt="image" width="1208" src="https://user-images.githubusercontent.com/11306060/245667432-91e82436-f3dc-428e-8aab-924ebe18b06f.png">

`active`是数字，不是字符串
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc3RlcHMgOmFjdGl2ZT1cIjJcIiBwcm9jZXNzLXN0YXR1cz1cImVycm9yXCIgZmluaXNoLXN0YXR1cz1cImZpbmlzaFwiPlxuICAgICAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgMVwiIGRlc2NyaXB0aW9uPVwiU29tZSBkZXNjcmlwdGlvblwiIC8+XG4gICAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAyXCIgZGVzY3JpcHRpb249XCJTb21lIGRlc2NyaXB0aW9uXCIgLz5cbiAgICAgICAgPGVsLXN0ZXAgdGl0bGU9XCJTdGVwIDNcIiBkZXNjcmlwdGlvbj1cIlNvbWUgZGVzY3JpcHRpb25cIiAvPlxuICAgICAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgNFwiIGRlc2NyaXB0aW9uPVwiU29tZSBkZXNjcmlwdGlvblwiIC8+XG4gICAgPC9lbC1zdGVwcz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
