### ISSUE TITLE
[Style] Use the namespace set by el-config-provider="ep", but the class name is still the class name of el 

### ISSUE THREAD

**Issue by riversword** [element-plus/element-plus#13171]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome  114.0.5735.110`
- Build Tool: `Vue CLI`

### Related Component

- `el-loading`
- `el-message`
- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94ICB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG9wZW5Nc2cgPSAoKSA9PiB7XG4gIEVsTWVzc2FnZSgnZXhwZWN0ZWQgY2xhc3Mgc3RhcnQgd2l0aCBcImVwXCIsIGJ1dCBzdGlsbCBcImVsXCInKTtcbn07XG4gIFxuY29uc3Qgb3Blbk1zZ0JveCA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oXG4gICAgJ2V4cGVjdGVkIGNsYXNzIHN0YXJ0IHdpdGggXCJlcFwiLCBidXQgc3RpbGwgXCJlbFwiJyxcbiAgICAnV2FybmluZycsXG4gICAge1xuICAgICAgY29uZmlybUJ1dHRvblRleHQ6ICdPSycsXG4gICAgICBjYW5jZWxCdXR0b25UZXh0OiAnQ2FuY2VsJyxcbiAgICAgIHR5cGU6ICd3YXJuaW5nJyxcbiAgICB9XG4gIClcbiAgICAudGhlbigoKSA9PiB7XG4gICAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgIH0pXG59O1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciBuYW1lc3BhY2U9XCJlcFwiPlxuICAgPGVsLWJ1dHRvbiA6cGxhaW49XCJ0cnVlXCIgQGNsaWNrPVwib3Blbk1zZ1wiPlNob3cgbWVzc2FnZTwvZWwtYnV0dG9uPlxuICAgPGVsLWJ1dHRvbiA6cGxhaW49XCJ0cnVlXCIgQGNsaWNrPVwib3Blbk1zZ0JveFwiPlNob3cgbWVzc2FnZSBib3g8L2VsLWJ1dHRvbj5cbiAgICA8YnI+XG4gIDxwPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gICA8IS0tPGgxIHYtbG9hZGluZz1cInRydWVcIj5JIGFtIGxvYWRpbmc8L2gxPi0tPlxuICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

setting the namespace as 'ep', reference to https://element-plus.org/zh-CN/guide/namespace.html

### What is Expected?

the css class start with 'ep'

### What is actually happening?

the css class start with 'el'

### Additional comments

_(empty)_

**Comment by riversword** [comment]
After adding the following code, solve the problem
```
app.use(ElementPlus, { namespace: "ep" })
```

**Comment by maqianqiandegithup** [comment]
Thank you very much!
