### ISSUE TITLE
[Bug Report] el-color-picker :predefine can not use

### ISSUE THREAD

**Issue by hujintao0309** [element-plus/element-plus#1318]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://elementui.github.io

### Steps to reproduce
use color-picker with :predefine

### What is Expected?
can choose predefine color

### What is actually happening?
can use

**Comment by hujintao0309** [comment]
![image](https://user-images.githubusercontent.com/34874340/105029702-a6c8d400-5a8d-11eb-94b7-3aeb2c0cbe9e.png)

**Comment by Ryan2128** [comment]
Please provide a repprodction or your predefine color data.

**Comment by zazzaz** [comment]
this should be fixed in #1323

**Comment by Ryan2128** [comment]
If there still no reply, I will close this issue.

**Comment by qiaozhu** [comment]
![image](https://user-images.githubusercontent.com/25722049/105796432-d2861580-5fc9-11eb-9677-6e5e4978dce5.png)
![image](https://user-images.githubusercontent.com/25722049/105796470-e3cf2200-5fc9-11eb-82f5-3e9bf2eceea9.png)
![image](https://user-images.githubusercontent.com/25722049/105796547-03fee100-5fca-11eb-9fd9-4f2a3f699585.png)
预设的颜色 没有显示(background没有设置上) 但点击事件有效
