### ISSUE TITLE
[TypeScript] [table] [ElTable]     toggleRowSelection: (row: any, selected: boolean) => void;参数2应该允许undefined

### ISSUE THREAD

**Issue by L1yp** [element-plus/element-plus#13197]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcbiAgPGVsLXNjcm9sbGJhciBtYXgtaGVpZ2h0PVwiNjAwXCIgYWx3YXlzPlxuICBcdCAgPGVsLXRyZWVcbiAgICAgICAgcmVmPVwidHJlZVJlZlwiXG4gICAgICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgICAgIHNob3ctY2hlY2tib3hcbiAgICAgICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgICAgIGhpZ2hsaWdodC1jdXJyZW50XG4gICAgICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gICAgICAvPlxuICA8L2VsLXNjcm9sbGJhcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFRyZWUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5cbmludGVyZmFjZSBUcmVlIHtcbiAgaWQ6IG51bWJlclxuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IHRyZWVSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbFRyZWU+PigpXG5cbmNvbnN0IGRlZmF1bHRQcm9wcyA9IHtcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGxhYmVsOiAnbGFiZWwnLFxufVxuXG5jb25zdCBkYXRhOiBUcmVlW10gPSBbXG4gIHtcbiAgICBpZDogMSxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNCxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogOSxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDEwLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA1LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDYsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiA4LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

table导出的toggleRowSelection方法类型有误

### What is Expected?

应该允许传入undefined

### What is actually happening?

实际传入undefined，IDE会报错

### Additional comments
![image](https://github.com/element-plus/element-plus/assets/22633943/51132c93-8d6d-4f01-8fe7-d4ea92378e43)

_(empty)_

**Comment by Tickly** [comment]
有人知道如何手动在项目内修复这个问题吗？

**Comment by tolking** [comment]
Fixed by #17687
