### ISSUE TITLE
### ColorPicker

### ISSUE THREAD

**Issue by zouhangwithsweet** [element-plus/element-plus#132]

**Comment by MBearo** [comment]
Can I help you?

**Comment by zazzaz** [comment]
@MBearo That would be nice, please.

**Comment by MBearo** [comment]
> @MBearo That would be nice, please.

What should I do?

**Comment by zazzaz** [comment]
@MBearo 
Check here for more information.

https://github.com/element-plus/element-plus/issues/148

**Comment by MBearo** [comment]
> @MBearo
> Check here for more information.
> 
> #148

Create an issue and the title is ColorPicker ?

**Comment by zazzaz** [comment]
@MBearo we already have this issue.  #132   you can start coding right away. 😁

**Comment by JeremyWuuuuu** [comment]
@MBearo  I think ColorPicker has been taken by someone, the label is not correct, sorry about that

**Comment by MBearo** [comment]
> @MBearo I think ColorPicker has been taken by someone, the label is not correct, sorry about that

All right
