### ISSUE TITLE
[bug report] datepicker when selecting a date range, when the first value is greater than the second value, the selected part has no background color

### ISSUE THREAD

**Issue by haliuhei** [element-plus/element-plus#1320]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
windows 10

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=9a116ca3-a4ae-4e38-8ef9-9b4a562d2a2b

### Steps to reproduce
点击输入框->选择第一个值->滑动鼠标选择第二个值（要求为第一个值之前的日期，比如第一个值选择2021-01-24，第二个选择2021-01-01）->现象为选中部分没有背景颜色

### What is Expected?
有背景颜色区分

### What is actually happening?
实际没有背景色不好区分

**Comment by JeremyWuuuuu** [comment]
See this screen shot, `message box` handles the translation correctly, closing.
![image](https://user-images.githubusercontent.com/15975785/105685874-8d160980-5f31-11eb-94b8-b27b512277c6.png)

**Comment by BeADre** [comment]
The screenshot does not seem to be related to this issue

**Comment by zazzaz** [comment]
fixed in #1322
