### ISSUE TITLE
[Component] [steps] Steps process-status无法控制当前步骤状态，全部被finish-status控制了

### ISSUE THREAD

**Issue by meteorice** [element-plus/element-plus#13201]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.30`
- Browser / OS: `Intel Mac OS X`
- Build Tool: `Vite`

### Related Component

- `el-steps`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc3RlcHMgYWN0aXZlPVwiM1wiIHByb2Nlc3Mtc3RhdHVzPVwiZXJyb3JcIiBmaW5pc2gtc3RhdHVzPVwiZmluaXNoXCI+XG4gICAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAxXCIgZGVzY3JpcHRpb249XCJTb21lIGRlc2NyaXB0aW9uXCIgLz5cbiAgICAgICAgPGVsLXN0ZXAgdGl0bGU9XCJTdGVwIDJcIiBkZXNjcmlwdGlvbj1cIlNvbWUgZGVzY3JpcHRpb25cIiAvPlxuICAgICAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgM1wiIGRlc2NyaXB0aW9uPVwiU29tZSBkZXNjcmlwdGlvblwiIC8+XG4gICAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCA0XCIgZGVzY3JpcHRpb249XCJTb21lIGRlc2NyaXB0aW9uXCIgLz5cbiAgICA8L2VsLXN0ZXBzPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<el-steps active="2" process-status="error" finish-status="finish">
    <el-step title="Step 1" description="Some description" />
    <el-step title="Step 2" description="Some description" />
    <el-step title="Step 3" description="Some description" />
    <el-step title="Step 4" description="Some description" />
</el-steps>

### What is Expected?

step1,step2 是 finish 状态，step3 是 error 状态
step4是 wait 状态

### What is actually happening?

step1,step2,step3都是 finish 状态，step4是 wait 状态

### Additional comments

 没有 error 状态的体现

process-status="error" 的红色状态提现在哪里？当前错误状态
![image](https://github.com/element-plus/element-plus/assets/11306060/389a09e9-2208-4a1e-91ec-0d192ca4c35e)
步骤 3 应该是一个红色的错误状态吧
<img width="1638" alt="image" src="https://github.com/element-plus/element-plus/assets/11306060/68981a6e-d265-44e0-989f-df899dde3ada">

**Comment by chenxch** [comment]
reopen #13201
