### ISSUE TITLE
[Component] [input] 在360极速X浏览器上input组件的size='small'失效

### ISSUE THREAD

**Issue by zhengwei-D** [element-plus/element-plus#13216]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiBzaXplPSdzbWFsbCcgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<el-input size='small' />

### What is Expected?

输入框会很小

### What is actually happening?

输入框的大小和默认大小一样

### Additional comments

谷歌浏览器正常，360极速X浏览器不正常，plus官网的例子就能看出来

**Comment by zhengwei-D** [comment]
![image](https://github.com/element-plus/element-plus/assets/12321764/c6902cdc-3ef4-41bc-80b8-8389ec403b18)

**Comment by zhengwei-D** [comment]
![image](https://github.com/element-plus/element-plus/assets/12321764/60b70430-4b84-479d-82d7-2cc509bfdb9d)
还有这个

**Comment by chenxch** [comment]
请尽量使用chrome，国产浏览器经常会做一些魔改，无法全部兼容，希望理解。

**Comment by kooriookami** [comment]
我下载了该浏览器，显示是正常的，确保没有安装一些插件造成影响。

**Comment by zhengwei-D** [comment]
> 我下载了该浏览器，显示是正常的，确保没有安装一些插件造成影响。

啊，确实，我把插件一个一个禁用最后发现有一个京淘助手，这个禁用后就没问题了...........

**Comment by chenxch** [comment]
那我先关闭这个问题了哈，之前你那个drawer的看看会不会也是插件导致的？

**Comment by zhengwei-D** [comment]
> 那我先关闭这个问题了哈，之前你那个drawer的看看会不会也是插件导致的？

是的，那个也正常了，感谢
