### ISSUE TITLE
ELTable 问题反馈

### ISSUE THREAD

**Issue by Foxiaoy** [element-plus/element-plus#13213]
1. 当设置了:tree-props中的hasChildren属性, 源数据列中如果没有children的数据没有设置hasChildren=false, 所有的children都不会显示, 这和官方示例不同(仅设置了hasChildren=true的数据);
2. 当设置了:tree-props中的children属性, 使用type="selection"的el-table-column, 勾选父节点, 子节点不会一同选中, 和不设置:tree-props:children的效果不同;

**Comment by ccfish86** [comment]
不要`hasChildren`是正常的，
如果不能改接口数据，那就把hasChildren设置成别的。
```
:tree-props="{ children: 'children', hasChildren: 'qtmd' }"
```
