### ISSUE TITLE
[Component] [select] tabs下有select组件，切换tabs的时候，如果此时select的下拉列表是展开状态，则列表会闪到在屏幕左上角隐藏，体验不好

### ISSUE THREAD

**Issue by devloperNumber-1** [element-plus/element-plus#13221]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4O2hlaWdodDo1MDBweFwiPlxuICAgIDxkaXYgc3R5bGU9XCJ3aWR0aDoyMDBweDtiYWNrZ3JvdW5kOiNmMTJcIj5cbiAgICAgIGZkc1xuICAgIDwvZGl2PlxuICAgIDxkaXYgc3R5bGU9XCJmbGV4OjFcIj5cbiAgICAgIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgdHlwZT1cImJvcmRlci1jYXJkXCIgY2xhc3M9XCJkZW1vLXRhYnNcIiBAdGFiLWNsaWNrPVwiaGFuZGxlQ2xpY2tcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+VXNlcjwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiQ29uZmlnXCIgbGF6eSBuYW1lPVwic2Vjb25kXCI+XG4gICAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgbXVsdGlwbGVcbiAgICBmaWx0ZXJhYmxlXG4gICAgYWxsb3ctY3JlYXRlXG4gICAgZGVmYXVsdC1maXJzdC1vcHRpb25cbiAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgICAgICAgICAgIDpzdWZmaXgtdHJhbnNpdGlvbj1cImZhbHNlXCJcbiAgICBwbGFjZWhvbGRlcj1cIkNob29zZSB0YWdzIGZvciB5b3VyIGFydGljbGVcIlxuICA+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgIHR5cGU9XCJkYXRlXCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCJcbiAgICAgIC8+XG4gICAgXG4gICAgPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJSb2xlXCIgbGF6eSBuYW1lPVwidGhpcmRcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCIgbGF6eSBuYW1lPVwiZm91cnRoXCI+VGFzazwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIFxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYnNQYW5lQ29udGV4dCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignZmlyc3QnKVxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICAgIGRpc2FibGVkOiB0cnVlLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICh0YWI6IFRhYnNQYW5lQ29udGV4dCwgZXZlbnQ6IEV2ZW50KSA9PiB7XG4gIGNvbnNvbGUubG9nKHRhYiwgZXZlbnQpXG59XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

粘贴下面代码，虽然最新版本2.3.6有改善，但并非彻底解决。参考日期组件修复一下，日期组件没有该问题
```vue
<template>
  <div style="display:flex;height:500px">
    <div style="width:200px;background:#f12">
      fds
    </div>
    <div style="flex:1">
      <el-tabs v-model="activeName" type="border-card" class="demo-tabs" @tab-click="handleClick">
    <el-tab-pane label="User" name="first">User</el-tab-pane>
    <el-tab-pane label="Config" lazy name="second">
    <el-select
    v-model="value"
    multiple
    filterable
    allow-create
    default-first-option
    :reserve-keyword="false"
             :suffix-transition="false"
    placeholder="Choose tags for your article"
  >
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
    />
      </el-select>
      <el-date-picker
        v-model="value1"
        type="date"
        placeholder="Pick a day"
      />
    
    </el-tab-pane>
    <el-tab-pane label="Role" lazy name="third">Role</el-tab-pane>
    <el-tab-pane label="Task" lazy name="fourth">Task</el-tab-pane>
  </el-tabs>
    </div>
  </div>
  
</template>
<script lang="ts" setup>
import { ref } from 'vue'
import type { TabsPaneContext } from 'element-plus'

const activeName = ref('first')
const value1 = ref('')
const value = ref('')
const options = [
  {
    value: 'Option1',
    label: 'Option1',
  },
  {
    value: 'Option2',
    label: 'Option2',
    disabled: true,
  },
  {
    value: 'Option3',
    label: 'Option3',
  },
  {
    value: 'Option4',
    label: 'Option4',
  },
  {
    value: 'Option5',
    label: 'Option5',
  },
]

const handleClick = (tab: TabsPaneContext, event: Event) => {
  console.log(tab, event)
}
</script>
<style>
.demo-tabs > .el-tabs__content {
  padding: 32px;
  color: #6b778c;
  font-size: 32px;
  font-weight: 600;
}
</style>

```

### What is Expected?

tabs切换不要出现下拉选项闪动的问题

### What is actually happening?

tabs切换下拉选项会闪到左上角

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
设置一下这个属性
```
:persistent="false"
```

**Comment by devloperNumber-1** [comment]
> 设置一下这个属性
> 
> ```
> :persistent="false"
> ```

加这个属性，select就无法从options里面找label显示，影响显示

**Comment by kooriookami** [comment]
目前已修复
