### ISSUE TITLE
[Component] [select] Select在一些情况下会出现不停抖动

### ISSUE THREAD

**Issue by dean5277** [element-plus/element-plus#13228]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome 113.0.5672.64`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+ZGVmYXVsdDwvcD5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgICAgbXVsdGlwbGVcbiAgICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgICAgcGxhY2Vob2xkZXI9XCIzMzMzMzNcIlxuICAgICAgICA+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuWKoOaLv+Wkp+ermVwiIHZhbHVlPVwiMFwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIue+juWbveermVwiIHZhbHVlPVwiMVwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIue+jjHlm73nq5lcIiB2YWx1ZT1cIjJcIiAvPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLnvo4xMeWbveermVwiIHZhbHVlPVwiM1wiIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgICAgICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjEwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+dXNlIGNvbGxhcHNlLXRhZ3M8L3A+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+dXNlIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcDwvcD5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWUzXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBjb2xsYXBzZS10YWdzXG4gICAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxwPnVzZSBtYXgtY29sbGFwc2UtdGFnczwvcD5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWU0XCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBjb2xsYXBzZS10YWdzXG4gICAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICAgIDptYXgtY29sbGFwc2UtdGFncz1cIjNcIlxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFtdKVxuY29uc3QgdmFsdWUyID0gcmVmKFtdKVxuY29uc3QgdmFsdWUzID0gcmVmKFtdKVxuY29uc3QgdmFsdWU0ID0gcmVmKFtdKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW8zMzMzbjEnLFxuICAgIGxhYmVsOiAnT3B0aTQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpMjIyb24yJyxcbiAgICBsYWJlbDogJ09wdGlvMzMzbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpbzIyMjMnLFxuICAgIGxhYmVsOiAnT3B0aTIzNDJvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpbzIybjQnLFxuICAgIGxhYmVsOiAnT3B0aTIzNDJvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpMzQyNDIzNDIzb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjIzMjMyMzUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. 先选加拿大站、美国站、美1国站
2. 然后删掉美1国站， 就会出现抖动

### What is Expected?

不出现抖动

### What is actually happening?

出现抖动

### Additional comments

 <el-select
          v-model="value1"
          multiple
          filterable
          clearable
          placeholder="333333"
        >
          <el-option label="加拿大站" value="0" />
          <el-option label="美国站" value="1" />
          <el-option label="美1国站" value="2" />
          <el-option label="美11国站" value="3" />
        </el-select>

**Comment by btea** [comment]
fixed by #12106
