### ISSUE TITLE
[upload] 官网的upload组件上传接口失效

### ISSUE THREAD

**Issue by likaiyang98** [element-plus/element-plus#13257]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.6`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/upload.html)

### Steps to reproduce

上传图片，控制台报错

Access to XMLHttpRequest at 'https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15' from origin 'https://element-plus.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

UploadAjaxError: fail to post https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15 0

app.91d65c54.js:53     POST https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15 net::ERR_FAILED 503 (Service Unavailable)

### What is Expected?

上传成功

### What is actually happening?

上传失败

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/58417280/d32d848e-758e-4ee2-8431-ae8729545606)

**Comment by chenxch** [comment]
<img width="1100" alt="image" src="https://github.com/element-plus/element-plus/assets/23251408/7abe3e66-0288-4d4e-9bfe-8bceda8f54c1">
正常，你可以试试无痕模式看看是不是你电脑哪里设置问题
