### ISSUE TITLE
[Component] [select-v2] Select V2无法回显默认值

### ISSUE THREAD

**Issue by 223xgg** [element-plus/element-plus#13259]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmxldCB2YWx1ZSA9cmVhY3RpdmUoXG4gIFtcbiAgICB7IFwidmFsdWVcIjogXCIwMC0xMFwiLCBcImxhYmVsXCI6IFwi54Wk55+/5re35ZCI5belXCIgfSxcbiAgXSlcbmNvbnN0IGhhcm1PcHRpb25zID0gW3tcbiAgbGFiZWw6IFwi54Wk55+/5re35ZCI5belXCIsXG4gIHZhbHVlOiB7XG4gICAgXCJ2YWx1ZVwiOiBcIjAwLTEwXCIsXG4gICAgXCJsYWJlbFwiOiBcIueFpOefv+a3t+WQiOW3pVwiXG4gIH1cbn0sXG57XG4gIGxhYmVsOiBcIumAieeFpOW3pVwiLFxuICB2YWx1ZToge1xuICAgIFwidmFsdWVcIjogXCIwMC0xMVwiLFxuICAgIFwibGFiZWxcIjogXCLpgInnhaTlt6VcIlxuICB9XG59XVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtc2VsZWN0LXYyIHN0eWxlPVwid2lkdGg6MTAwJVwiIHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgbXVsdGlwbGUgOm9wdGlvbnM9XCJoYXJtT3B0aW9uc1wiICAvPlxuICA8L2Rpdj5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup >
import { reactive } from 'vue'
import { ElementPlus } from '@element-plus/icons-vue'
let value =reactive(
  [
    { "value": "00-10", "label": "煤矿混合工" },
  ])
const harmOptions = [{
  label: "煤矿混合工",
  value: {
    "value": "00-10",
    "label": "煤矿混合工"
  }
},
{
  label: "选煤工",
  value: {
    "value": "00-11",
    "label": "选煤工"
  }
}]
</script>

<template>
    <el-select-v2 v-model="value" filterable multiple :options="harmOptions"  />
</template>


```

### What is Expected?

设置默认值,能够进行回显

### What is actually happening?

没有进行回显

### Additional comments

_(empty)_

**Comment by 223xgg** [comment]
![snipaste_20230617_200931](https://github.com/element-plus/element-plus/assets/96895055/22be536f-964f-4c0b-8d15-e8f18ba7df98)

**Comment by sleepyShen1989** [comment]
Is this what you want?
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by 223xgg** [comment]
> 这是你想要的吗？ [演示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)



> 这是你想要的吗？ [演示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

No, I hope value is an Array<object>type

**Comment by sleepyShen1989** [comment]
> > 这是你想要的吗？ [演示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> 
> > 这是你想要的吗？ [演示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> 
> 我希望是array里面是object类型,而不是string

you can use `computed` to get the array like this:
```js
const submitOption = computed(() => {
  return harmOptions.filter((item) => {
    return value.value.indexOf(item.value.value) !== -1
  })
})
```

**Comment by 223xgg** [comment]
> > > 这是你想要的吗？[显示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> > 
> > 
> > > 这是你想要的吗？[显示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgdmFsdWUgPSByZWYoWycwMC0xMCddKVxuY29uc3QgaGFybU9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eFpOefv+a3t+WQiOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTAnLFxuICAgICAgbGFiZWw6ICfnhaTnn7/mt7flkIjlt6UnLFxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ+mAieeFpOW3pScsXG4gICAgdmFsdWU6IHtcbiAgICAgIHZhbHVlOiAnMDAtMTEnLFxuICAgICAgbGFiZWw6ICfpgInnhaTlt6UnLFxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgbXVsdGlwbGVcbiAgICA6b3B0aW9ucz1cImhhcm1PcHRpb25zXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS52YWx1ZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> > 
> > 
> > 我希望数组里面是对象类型，而不是字符串
> 
> 您可以`computed`像这样获取数组：
> 
> ```js
> const submitOption = computed(() => {
>   return harmOptions.filter((item) => {
>     return value.value.indexOf(item.value.value) !== -1
>   })
> })
> ```

感谢你给我提供一个比较好的思路
