### ISSUE TITLE
[Bug Report] When the el-table has no data, there is an error in the calculation of the height of the fixed column

### ISSUE THREAD

**Issue by CitizenChaos** [element-plus/element-plus#1325]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
win 10 64bit 20H2 / Chorme 88.0.4324.96

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/citizenchaos/pen/yLaQwXQ

### Steps to reproduce
1. el-table has no data
2. fix some column
3. the height of the fixed column is calculated incorrectly
4. cannot drag the scroll bar

### What is Expected?
the height of the fixed column is calculated correctly

### What is actually happening?
When the el-table has no data, the height of the fixed column is calculated incorrectly, causing the scroll bar to be covered. Cannot drag the scroll bar.

**Comment by justwiner** [comment]
The reason for the inconsistency of the height in the two cases is because the height of the empty container is 60px, and the data in each row occupies 48px. And I can drag the scroll bar, I don’t know why you can’t drag it.

I think this is not a bug, what do you think?
