### ISSUE TITLE
[feature request] how to use the form verification of element plus in vue3, the current code example is still written in vue2.

### ISSUE THREAD

**Issue by dongfenglong** [element-plus/element-plus#1326]
### Existing Component
Yes

### Component Name
Form

### Description
Vue3 中怎样使用 Element Plus的表单校验，现在的代码示例还是 Vue2 的写法。

**Comment by kooriookami** [comment]
You can use both callback or promise. `validate now returns a promise that reject invalidFields instead of a single boolean if no callback is provided`

**Comment by dongfenglong** [comment]
ok，我已经找到答案了。
For example:<el-form ref="formRef" ...>
在setup中定义一个与formRef同名的响应式变凉，然后就可以用 formRef.value.validate((valid)=>{...}) 了
