### ISSUE TITLE
[TypeScript] [form] FormRules无法使用

### ISSUE THREAD

**Issue by FairyWorld** [element-plus/element-plus#13270]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB0eXBlIHtGb3JtUnVsZXN9IGZyb20gXCJlbGVtZW50LXBsdXNcIjtcbmltcG9ydCB7cmVhY3RpdmV9IGZyb20gXCJ2dWVcIjtcblxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZTxGb3JtUnVsZXM+KHtcbiAgICB1c2VybmFtZTogW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICfor7fovpPlhaXnlKjmiLflkI0nLCB0cmlnZ2VyOiAnYmx1cicgfV1cbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2Lz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

import type {FormRules} from "element-plus";

### What is Expected?

打包时类型检查正常

### What is actually happening?

打包时类型检查FormRules类型不可用，Module '"element-plus"' has no exported member 'FormProps'

### Additional comments

_(empty)_

**Comment by btea** [comment]
I tried it locally and it seems to be normal. Can you provide a link to a minimal code repository that reproduces it?

**Comment by SuperMrBean** [comment]
edit your tsconfig.json,  "moduleResolution": "Node"
