### ISSUE TITLE
[bug report] navmenu cannot hide text after slot shrinkage

### ISSUE THREAD

**Issue by yudan215** [element-plus/element-plus#1328]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
windows10-64-

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/yudan215/pen/ExgJNXg

### Steps to reproduce
el-submenu是正常的
但是在el-menu-item收缩后文字无法隐藏

### What is Expected?
NavMenu使用slot具名插槽收缩后无法隐藏文字
el-submenu是正常的
但是在el-menu-item收缩后文字无法隐藏

### What is actually happening?
NavMenu使用slot具名插槽收缩后无法隐藏文字
el-submenu是正常的
但是在el-menu-item收缩后文字无法隐藏

**Comment by JeremyWuuuuu** [comment]
Please go read `Vue3` documentation before raising issues.

**Comment by Ryan2128** [comment]
Please check vue's docs about how to pass a slot to a component.
