### ISSUE TITLE
[Component] [select] When the property value of 'ElSelect' is changed, the height value is forced to change together.

### ISSUE THREAD

**Issue by SangJuBaek** [element-plus/element-plus#13297]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome 114.0.5735.111`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwidGVzdC1jb250YWluZXJcIj5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiIHNpemU9XCJkZWZhdWx0XCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIEBjbGljaz1cInRlc3RcIj5cbiAgICAgYnV0dG9uIFxuICAgIDwvYnV0dG9uPlxuICA8L2Rpdj5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IGRpc2FibGVkID0gcmVmKGZhbHNlKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbmZ1bmN0aW9uIHRlc3QgKCkge1xuICBkaXNhYmxlZC52YWx1ZSA9ICFkaXNhYmxlZC52YWx1ZVxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuICAudGVzdC1jb250YWluZXIge1xuICBcdC0tZWwtY29tcG9uZW50LXNpemU6IDI4cHg7ICBcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

click button in reproduction page

### What is Expected?

Only the disabled option of el-select should be changed

### What is actually happening?

el-select's height is changed together

### Additional comments

I need to customize the height of el-select, so I am overriding the --el-component-size variable. However, I found that 'height: 30px' is forcibly applied when the disabled value of el-select is changed. Is this an intended feature? Can I solve it?

**Comment by btea** [comment]
I tried it locally and it seems to be normal. Can you provide a link to a minimal code repository that reproduces it?

**Comment by wonderl17** [comment]
maybe you can remove ```size="default"``` prop of el-select

**Comment by SangJuBaek** [comment]
> maybe you can remove `size="default"` prop of el-select

I confirmed that removing the size prop does not provide inline height. However, if the size prop is small rather than default, inline height that reflects the current css height value is created. It seems that the problem is that the operation is different when size prop is 'default'.

**Comment by kooriookami** [comment]
It seems work now
