### ISSUE TITLE
[Component] [All] edge 浏览器 v115 动画失效

### ISSUE THREAD

**Issue by cethink** [element-plus/element-plus#13293]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `edge 115.0.1901.14 / win11 23481`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/menu.html)

### Steps to reproduce

Edge版本 115.0.1901.14 (正式版本) stable应用，beta频道 (64 位)
这个版本下动画失效

### What is Expected?

有动画

### What is actually happening?

无动画

### Additional comments

_(empty)_

**Comment by btea** [comment]
Seems to be a browser issue https://github.com/vuejs/core/issues/8409.

**Comment by btea** [comment]
You can refer to this [comment](https://github.com/vuejs/core/issues/8409#issuecomment-1562454964) or wait for the next release of vue.
