### ISSUE TITLE
[bug report] table header rendering dislocation of talble component

### ISSUE THREAD

**Issue by zhangguojun111** [element-plus/element-plus#1330]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
macOs 11.1   / chrome 版本 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/zhangguojun111/pen/qBawXeN

### Steps to reproduce
直接赋值 d.value = [ 。。。 ] 则会出现问题， 如果 d.value.push(....) 则不会

### What is Expected?
表格头部正常

### What is actually happening?
表头右边出现错位

**Comment by zhangguojun111** [comment]
希望，尽快解决！

**Comment by Ryan2128** [comment]
Maybe duplicate #1317
