### ISSUE TITLE
[Component] [dropdown, input] Using el-input in el-dropdown does not allow to input a whitespace into the input field

### ISSUE THREAD

**Issue by Georgitto** [element-plus/element-plus#13300]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome/114.0.5735.134`
- Build Tool: `CDN`

### Related Component

- `el-dropdown`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gcmVmPVwiZHJvcGRvd24xXCIgdHJpZ2dlcj1cImhvdmVyXCIgc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDMwcHhcIj5cbiAgICA8ZWwtaW5wdXRcbiAgICAgICAgICB2LW1vZGVsPVwiaW5wdXRcIlxuICAgICAgICAvPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IERyb3Bkb3duSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGRyb3Bkb3duMSA9IHJlZjxEcm9wZG93bkluc3RhbmNlPigpXG5jb25zdCBpbnB1dCA9IHJlZignJylcblxuZnVuY3Rpb24gaGFuZGxlVmlzaWJsZTIodmlzaWJsZTogYW55KSB7XG4gIGlmICghZHJvcGRvd24xLnZhbHVlKSByZXR1cm5cbiAgaWYgKHZpc2libGUpIHtcbiAgICBkcm9wZG93bjEudmFsdWUuaGFuZGxlQ2xvc2UoKVxuICB9IGVsc2Uge1xuICAgIGRyb3Bkb3duMS52YWx1ZS5oYW5kbGVPcGVuKClcbiAgfVxufVxuZnVuY3Rpb24gc2hvd0NsaWNrKCkge1xuICBjb25zb2xlLmxvZyhkcm9wZG93bjEudmFsdWUpXG4gIGlmICghZHJvcGRvd24xLnZhbHVlKSByZXR1cm5cbiAgZHJvcGRvd24xLnZhbHVlLmhhbmRsZU9wZW4oKVxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmV4YW1wbGUtc2hvd2Nhc2UgLmVsLWRyb3Bkb3duLWxpbmsge1xuICBjdXJzb3I6IHBvaW50ZXI7XG4gIGNvbG9yOiB2YXIoLS1lbC1jb2xvci1wcmltYXJ5KTtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. Input some text into the field
2. Input a white space

### What is Expected?

You can see a whitespace in the input field

### What is actually happening?

No whitespace, hitting spacebar only triggers a dropdown menu and after multiple smashing input field loses it focus.

### Additional comments

I am working on an input field which could promts users about existing names in the system. Recently I noticed this erroneous behavior and just don`t understand why smashing spacebar triggers a dropdown window except input field (adding whitespace in the field)

**Comment by itsalimanuel** [comment]
Hello @Georgitto , what about [autocomplete](https://element-plus.org/en-US/component/autocomplete.html#basic-usage) ?

**Comment by chenxch** [comment]
If it is not done automatically, you can try to use the components separately, for example [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPGVsLWlucHV0XG4gICAgICAgICAgdi1tb2RlbD1cImlucHV0XCJcbiAgICAgICAgICAgICBAa2V5ZG93bj1cImhhbmRsZUtleURvd25cIlxuICAgICAgICAvPlxuICA8ZWwtZHJvcGRvd24gcmVmPVwiZHJvcGRvd24xXCIgdHJpZ2dlcj1cImhvdmVyXCIgc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDMwcHhcIj5cbiAgIDxzcGFuPjwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXZpZGVkPkFjdGlvbiA1PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBEcm9wZG93bkluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkcm9wZG93bjEgPSByZWY8RHJvcGRvd25JbnN0YW5jZT4oKVxuY29uc3QgaW5wdXQgPSByZWYoJycpXG5cbmZ1bmN0aW9uIGhhbmRsZVZpc2libGUyKHZpc2libGU6IGFueSkge1xuICBpZiAoIWRyb3Bkb3duMS52YWx1ZSkgcmV0dXJuXG4gIGlmICh2aXNpYmxlKSB7XG4gICAgZHJvcGRvd24xLnZhbHVlLmhhbmRsZUNsb3NlKClcbiAgfSBlbHNlIHtcbiAgICBkcm9wZG93bjEudmFsdWUuaGFuZGxlT3BlbigpXG4gIH1cbn1cbmZ1bmN0aW9uIHNob3dDbGljaygpIHtcbiAgY29uc29sZS5sb2coZHJvcGRvd24xLnZhbHVlKVxuICBpZiAoIWRyb3Bkb3duMS52YWx1ZSkgcmV0dXJuXG4gIGRyb3Bkb3duMS52YWx1ZS5oYW5kbGVPcGVuKClcbn1cbiAgXG4gIGZ1bmN0aW9uIGhhbmRsZUtleURvd24oZSl7XG4gICAgY29uc29sZS5sb2coZSlcbiAgICBpZihlLmtleUNvZGUgPT09IDMyKXtcbiAgICAgIGNvbnNvbGUubG9nKGRyb3Bkb3duMS52YWx1ZSlcbiAgICAgICBkcm9wZG93bjEudmFsdWUuaGFuZGxlT3BlbigpXG4gICAgfVxuICB9XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtZHJvcGRvd24tbGluayB7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Georgitto** [comment]
Hello, @chenxch. I saw your example and it seems to be a good for me. Thank you for your help.
