### ISSUE TITLE
[Bug Report] ElButton onClick can't not be inferenced correctly in .tsx file

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1331]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
macOS 10.15

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr?

### Steps to reproduce
1. please ignore `Reproduction Link` because there is no ts template in auto-issues web page.    /    请忽略 Reproduction Link，auto issues 这个页面均没有提供 ts 的模版来写

2. error occurs in the code: 👇    /    错误会出现下面的代码：👇

``` tsx
import { defineComponent } from "vue";
import { ElButton } from "element-plus";

const HelloWorld = defineComponent({
  render() {
    return (
      <ElButton
        type="primary"
        size="small"
        // element-plus 对 tsx 支持还不是很好, 实际运行的时候这样是 ok 的
        // 但是带的类型声明这样不能写, 可以看看吗？
        onClick={this.ecznClk}
      >
        新增授权
      </ElButton>
    );
  },

  methods: {
    ecznClk() {
      console.log("ecznClk");
    }
  }
});

export default HelloWorld;
```

### What is Expected?
`onClick` could be inferenced correctly in .tsx file    /    希望 .tsx 组件中能正确推断 onClick

### What is actually happening?
we have to use to many @ts-ignore to ignore such this errror    /    会不得不写很多 ts-ignore 来忽略这类错误

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/105362200-8c315f00-5c35-11eb-9418-a16c83e50489.png)

**Comment by eczn** [comment]
补充一下，ElTableColumn 也有类似的问题

**Comment by CaicoLeung** [comment]
我也是用tsx, 刚好遇到这个问题...

**Comment by CaicoLeung** [comment]
![image](https://user-images.githubusercontent.com/36806569/105481381-ebe54400-5ce1-11eb-8df3-57fe89105533.png)

**Comment by eczn** [comment]
> 我也是用tsx, 刚好遇到这个问题...

![image](https://user-images.githubusercontent.com/13131724/105481624-48486380-5ce2-11eb-9319-85457cfd8724.png)

总之感觉 vue 的 tsx 建设还不太行

**Comment by Ryan2128** [comment]
> > 我也是用tsx, 刚好遇到这个问题...
> 
> ![image](https://user-images.githubusercontent.com/13131724/105481624-48486380-5ce2-11eb-9319-85457cfd8724.png)
> 
> 总之感觉 vue 的 tsx 建设还不太行

Please check `jsx-next`'s [docs](https://github.com/vuejs/jsx-next) about how to use `v-model` in jsx/tsx.

**Comment by Ryan2128** [comment]
The event attrs of element-plus's components will be supported in next version.

**Comment by Ryan2128** [comment]
Sorry, I think it should be consider again. Because `xxx.vue.d.ts` is automatically generated and we can not add `onClick` on 'props'. And if we override `ComponentCustomProps`, all components will use it. It means there is no way to add each event declare to each component without affecting the attrs of other components.

**Comment by Ryan2128** [comment]
I think it should be resolved by vue, it should generate event attrs automatically for each component.

**Comment by eczn** [comment]
> Sorry, I think it should be consider again. Because `xxx.vue.d.ts` is automatically generated and we should not add `onClick` on 'props'. If we override `ComponentCustomProps`, all components will use it. It means there is no way to add each event declare to each component without affecting the attrs of other components.

yes, vue uses event to process DOM event, and its handler function will be invoked by father component, not the subcomponent.
jsx didn't provide a property way to declare `Vue Style Event` ... it is a vue/tsx issue need to improve

**Comment by Ryan2128** [comment]
If you do not want this error, you can check this temporary solution, add below code to your `shim.d.ts` file.

```
export * from '@vue/runtime-core'

declare module '@vue/runtime-core' {
  interface ComponentCustomProps {
    [elemName: string]: any;
  }
}
```

**Comment by Ryan2128** [comment]
If there are no other questions, I will close the issue later.

**Comment by eczn** [comment]
thanks, let me try try
