### ISSUE TITLE
[Performance] [select, input] el-select 数量比较多时，el-input在输入时会很卡顿 

### ISSUE THREAD

**Issue by Meow642** [element-plus/element-plus#13334]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome 114.0.5735.106`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmxldCBhID0gcmVmKFtdKVxuXG5mb3IgKGxldCBpID0gMDsgaSA8IDE2MDsgaSsrKSB7XG4gIGEudmFsdWUucHVzaCh7XG4gICAga2V5OiBpLFxuICAgIHZhbHVlOiAnJyxcbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxkaXYgdi1mb3I9XCJpdGVtIGluIGFcIiA6a2V5PVwiaXRlbS5rZXlcIj5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJpdGVtLnZhbHVlXCI+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiZm9vXCIgdmFsdWU9XCJiYXJcIiAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

创建一个input 和 一些 select

### What is Expected?

input输入时不会卡顿

### What is actually happening?

输入时很卡

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
demo还是很流畅的，方便提供一下录屏已经设备性能方便的信息么，我目前认为这个更多的应该是使用层面上的问题，或者是你可以把select更换到select-v2

**Comment by Meow642** [comment]
快速在输入框里输入一些字母，还是可以明显感觉到一些延迟的
然后在vue devtool 里面， 可以看到在输入一个字母后，会产生很多ElSelect的相关事件
![image](https://github.com/element-plus/element-plus/assets/78215201/7932f7d8-6575-4a2f-8e71-e37545096623)
可是在这个demo里，input组件和select组件的绑定数据应该并没有相互影响啊？不知道咋回事

**Comment by chenxch** [comment]
考虑先使用v-memo或者是把这么多select用组件包一层的方式

**Comment by Meow642** [comment]
应该不是el-input的问题，换成原声的input也一样，我目前也是通过把el-select包一层组件解决的
我发现只有通过v-for循环使用el-select会有这个问题，
怀疑是不是更改输入值后，两次渲染函数渲染出的el-select的vdom不一样，导致这些el-select全都patch了一遍？

**Comment by chenxch** [comment]
因为v-for出来的diffpatch这边判断会走到动态节点这边，el-select里面东西本身就相对比较多，明明没变化，内部又全都diffpatch了一遍,160个全部这样走一遍
