### ISSUE TITLE
[Style] [switch] Using "useDark|VueUse" to control "Dark Mode" toggles will cause animation exceptions

### ISSUE THREAD

**Issue by Cxk-1233** [element-plus/element-plus#13347]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Github Repo](https://github.com/Cxk-1233/use-dark-debug)

### Steps to reproduce

```vue
<script setup>
import {useDark} from "@vueuse/core";
import {ref} from "vue";

let isDark = useDark();

</script>

<template>
  <div>
    <el-switch v-model="isDark"></el-switch>
  </div>
</template>

<style scoped>
</style>
```

### What is Expected?

el-switch animates normally when clicked

### What is actually happening?

After the el-switch is clicked, the state is abruptly switched, and the animation does not perform normally

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
应该和这个@vueuse/core 库版本更新有关，在9.1.0版本是有这个切换动画效果的

**Comment by Cxk-1233** [comment]
> 应该和这个@vueuse/core 库版本更新有关，在9.1.0版本是有这个切换动画效果的

我换成 `"@vueuse/core": "^9.1.0"` 后确实正常了

**Comment by imleeou** [comment]
我也出现了这个问题。
`"@vueuse/core": "^10.2.1",`
