### ISSUE TITLE
[Component] [table] el-table 树形表格选中父节点会自动选中子节点

### ISSUE THREAD

**Issue by falcon-jin** [element-plus/element-plus#13352]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdGFibGVEYXRhID0gcmVmKFtcbntcbiAgICBpZDogMSxcbiAgICBuYW1lOiAn5byg5LiJJyxcbiAgICBkYXRlOiAnMjAyMy0wNi0yNScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDIsXG4gICAgICAgIGRhdGU6ICcyMDIzLTA2LTI1JyxcbiAgICAgICAgbmFtZTogJ+adjuWbmydcbiAgICAgIH1cbiAgICBdXG4gIH1cbl0pXG5jb25zdCB0YWJsZURhdGEyID0gcmVmKFtcbntcbiAgICBpZDogMSxcbiAgICBuYW1lOiAn5byg5LiJJyxcbiAgICBkYXRlOiAnMjAyMy0wNi0yNScsXG4gICAgX2NoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAyLFxuICAgICAgICBkYXRlOiAnMjAyMy0wNi0yNScsXG4gICAgICAgIG5hbWU6ICfmnY7lm5snXG4gICAgICB9XG4gICAgXVxuICB9XG5dKVxuY29uc3QgdHJlZVByb3BzPXJlZih7Y2hpbGRyZW46ICdfY2hpbGRyZW4nfSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48aDE+6KGo5qC8IOWtkOaVsOaNruaYr2NoaWxkcmVu5a2X5q61IOWLvumAieeItue6p+S8mumAieS4reWtkOe6pzwvaDE+XG4gIDxlbC10YWJsZSAgOmRhdGE9XCJ0YWJsZURhdGFcIiByb3dLZXk9XCJpZFwiIGRlZmF1bHQtZXhwYW5kLWFsbD5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiB3aWR0aD1cIjU1XCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiBzb3J0YWJsZSAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHNvcnRhYmxlIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgc29ydGFibGUgLz5cbiAgPC9lbC10YWJsZT5cblxuICA8aDE+6KGo5qC8IOWtkOaVsOaNruaYr19jaGlsZHJlbuWtl+autSDli77pgInniLbnuqfkuI3kvJrpgInkuK3lrZDnuqc8L2gxPlxuICA8ZWwtdGFibGUgIDpkYXRhPVwidGFibGVEYXRhMlwiIHJvd0tleT1cImlkXCIgOnRyZWVQcm9wcz1cInRyZWVQcm9wc1wiIGRlZmF1bHQtZXhwYW5kLWFsbD5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiB3aWR0aD1cIjU1XCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiBzb3J0YWJsZSAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHNvcnRhYmxlIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgc29ydGFibGUgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

参考复现链接

### What is Expected?

有个参数可以控制是不是严格模式

### What is actually happening?

没有参数控制

### Additional comments

_(empty)_
问题可能出在这个地方
![image](https://github.com/element-plus/element-plus/assets/48880836/58c89cb3-e0e7-436c-87b2-989b2c0911d6)

**Comment by init-qy** [comment]
seems fixed in #10566
