### ISSUE TITLE
[Component] [select] 在el-dialog中使用el-select时，下拉框超出界面存在

### ISSUE THREAD

**Issue by StephenDugu** [element-plus/element-plus#13356]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.17`
- Browser / OS: ` chrome 114.0.5735.110（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjEnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjInLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjMnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjQnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjUnLFxuICAgIH0sXG5dXG5cbmNvbnN0IGhhbmRsZVVwZGF0ZSA9ICgpID0+IHtcbiAgICBkaWFsb2dWaXNpYmxlLnZhbHVlID0gdHJ1ZVxufVxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoKSA9PiB7XG4gZGlhbG9nVmlzaWJsZS52YWx1ZSA9IGZhbHNlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiaGFuZGxlVXBkYXRlXCI+5by556qXPC9lbC1idXR0b24+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiIHdpZHRoPVwiMzAlXCIgYWxpZ24tY2VudGVyIHRvcD1cIjV2aFwiIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiPlxuICAgICAgICAgICAgPGRpdiBzdHlsZT1cImhlaWdodDoyMDBweDtwYWRkaW5nOjMwcHg7b3ZlcmZsb3c6aGlkZGVuO1wiPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6MjAwcHg7cGFkZGluZzozMHB4O292ZXJmbG93OmF1dG87XCI+XG4gICAgICAgICAgICAgICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1.点击弹窗
2.下拉至最后一个el-select
3.点击el-select
4.滚动滑轮

### What is Expected?

点击的那个select看不到的时候，select的下拉选项也消失

### What is actually happening?

点击的那个select看不到的时候，select的下拉选项还在，超出显示范围

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjEnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjInLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjMnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjQnLFxuICAgIH0sXG4gICAge1xuICAgICAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgICAgICBsYWJlbDogJ09wdGlvbjUnLFxuICAgIH0sXG5dXG5cbmNvbnN0IGhhbmRsZVVwZGF0ZSA9ICgpID0+IHtcbiAgICBkaWFsb2dWaXNpYmxlLnZhbHVlID0gdHJ1ZVxufVxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoKSA9PiB7XG4gZGlhbG9nVmlzaWJsZS52YWx1ZSA9IGZhbHNlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiaGFuZGxlVXBkYXRlXCI+5by556qXPC9lbC1idXR0b24+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiIHdpZHRoPVwiMzAlXCIgYWxpZ24tY2VudGVyIHRvcD1cIjV2aFwiIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiPlxuICAgICAgICAgICAgPGRpdiBzdHlsZT1cImhlaWdodDoyMDBweDtwYWRkaW5nOjMwcHg7b3ZlcmZsb3c6aGlkZGVuO1wiPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6MjAwcHg7cGFkZGluZzozMHB4O292ZXJmbG93OmF1dG87XCI+XG4gICAgICAgICAgICAgICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6dGVsZXBvcnRlZD1cImZhbHNlXCIgPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD48ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6dGVsZXBvcnRlZD1cImZhbHNlXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtc2VsZWN0PjxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDp0ZWxlcG9ydGVkPVwiZmFsc2VcIiBwbGFjZW1lbnQ9XCJ0b3BcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+PGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiIHBsYWNlbWVudD1cInRvcFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAvPlxuICAgICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

考虑利用placement和teleported来解决
