### ISSUE TITLE
[Bug Report] When setting the disabled-hours attribute for <el-date-picker>, the second parameter of the callback function is always undefined.

### ISSUE THREAD

**Issue by chendx97** [element-plus/element-plus#13364]
### Element Plus version
2.3.5

### OS/Browsers version
window10/chrome114

### Vue version
3.3.2

### Reproduction Link
https://codepen.io/dcba/pen/wvQgzPZ

### Steps to reproduce
打开日期选择器，打开时-分选择器，打印信息中第2个一直是undefined
Open the date picker, open the hour-minute selector, and the second one in the printed information is always undefined.

### What is Expected?
disabled-hours回调函数的第2个参数comparingDate应该是当前修改的（还未点确定按钮前的）日期
The second parameter, comparingDate, of the disabled-hours callback function should have a value.

### What is actually happening?
disabled-hours回调函数的第2个参数comparingDate一直是undefined

**Comment by JackieCheung** [comment]
同样的问题
