### ISSUE TITLE
[Component] [input] el-input 组件绑定了 type 为 number 的 v-model 在改变值后，v-model 的类型从 number 变为 string 了

### ISSUE THREAD

**Issue by Ashy6** [element-plus/element-plus#13365]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.0.1`
- Browser / OS: `Chrome 114.0.5735.134 / Windows 10 64位`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

1. 使用 el-input 组件(type 类型设置为 number)
2. v-model 绑定一个值
3. 初始化的时候，v-model 绑定的值是 number 类型的
4. 但是当我改写了这个值以后 这个 v-model 的值就为 string 类型了

### What is Expected?

number 类型的值保持不变

### What is actually happening?

只有初始化的时候是 number，后面都会是 string

### Additional comments

如果有需要我可以帮 提交 pr

**Comment by chenxch** [comment]
type=number建议使用input-number组件，原生input中type=number也是输出string哦

**Comment by 13579123** [comment]
这个应该不算bug吧，自己转换一下就行

**Comment by Ashy6** [comment]
> 

啊  好吧~
总感觉类型变了不是个好的行为，感觉 el-input 可以在封装 input 的时候进行一次转换（目前我已经换了 number 组件）

**Comment by 13579123** [comment]
确实类型改变不是好的行为，但是el-input组件本身就是给string类型数据的，就我感觉来说，一开始给个number可能不是那么合法

**Comment by Ashy6** [comment]
所以说，还是期望得到官方的支持可能会好点。
不然就是使用者都去做类型转换了。
或许会有 el-input-number 不能使用的场景，并且期望通过传 type 来控制类型呢

> 确实类型改变不是好的行为，但是el-input组件本身就是给string类型数据的，就我感觉来说，一开始给个number可能不是那么合法

**Comment by btea** [comment]
如 @chenxch @13579123 所说，这是正常的，和原生input表现一致。
组件库只提供基本功能，对于不同业务场景下的具体需求由开发者自行控制会比较好。
