### ISSUE TITLE
[Docs] [table-v2] Table-V2文档Typo

### ISSUE THREAD

**Issue by liucy1983** [element-plus/element-plus#13370]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome/114.0.0.0 Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Link]()

### Steps to reproduce

1. 官网的component文档中，table-v2组件有Typo
2. 应该是TableV2 事件，写成了TreeV2 事件
   - https://element-plus.org/zh-CN/component/table-v2.html#treev2-%E4%BA%8B%E4%BB%B6

### What is Expected?

应该是TableV2 事件

### What is actually happening?

写成了TreeV2 事件

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
英文文档没问题，这属于翻译错了

**Comment by btea** [comment]
https://crowdin.com/translate/element-plus/946/en-zhcn?filter=basic&value=0
