### ISSUE TITLE
[Component] [date-picker] DatePicker 组件 type 切换关联的 v-model 解析失败

### ISSUE THREAD

**Issue by sunvictor** [element-plus/element-plus#13371]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.7`
- Browser / OS: `Google Chrome /14.0.5735.134`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRhdGVUeXBlID0gcmVmKCd5ZWFyJylcbmNvbnN0IGRhdGUgPSByZWYoJzIwMjMtMDEtMDEnKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gZSA9PiB7XG4gIGlmIChlID09PSAnZGF0ZScpIHtcbiAgICBkYXRlLnZhbHVlID0gJzIwMjMtMDEtMDEnXG4gIH0gZWxzZSBpZiAoZSA9PT0gJ2RhdGVyYW5nZScpIHtcbiAgICBkYXRlLnZhbHVlID0gWycyMDIzLTAxLTAxJywgJzIwMjMtMDEtMzAnXVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwieXgtcGFnZUlkeFwiPlxuICAgIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwiZGF0ZVwiIDp0eXBlPVwiZGF0ZVR5cGVcIiAvPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImRhdGVUeXBlXCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cImRhdGVcIj55ZWFyPC9lbC1vcHRpb24+XG4gICAgICA8ZWwtb3B0aW9uIHZhbHVlPVwiZGF0ZXJhbmdlXCI+d2VlazwvZWwtb3B0aW9uPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

select 从 year 切换到 week，会报错 be.format is not a function

### What is Expected?

正常切换不报错

### What is actually happening?

be.format is not a function

### Additional comments

_(empty)_

**Comment by tolking** [comment]
This issue has been fixed
