### ISSUE TITLE
[Component] [tree, scrollbar] Tree外放一个ScrollBar默认会出现滚动条

### ISSUE THREAD

**Issue by lzl82891314** [element-plus/element-plus#13396]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Version 114.0.5735.135 (Official Build) (64-bit)`
- Build Tool: `CDN`

### Related Component

- `el-tree`
- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC1zY3JvbGxiYXI+XG4gIDxlbC10cmVlXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBzaG93LWNoZWNrYm94XG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cIlsyLCAzXVwiXG4gICAgOmRlZmF1bHQtY2hlY2tlZC1rZXlzPVwiWzVdXCJcbiAgICA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIlxuICAvPlxuICA8L2VsLXNjcm9sbGJhcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cbmNvbnN0IGRhdGEgPVtcbiAgICB7XG4gICAgICAgIGlkOiAxLFxuICAgICAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICB9LFxuICAgIHtcbiAgICAgICAgaWQ6IDIsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIH0sXG4gICAge1xuICAgICAgICBpZDogMyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

playground中默认就有滚动条

### What is Expected?

不应该有滚动条

### What is actually happening?

有滚动条

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC1zY3JvbGxiYXI+XG4gIDxlbC10cmVlXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBzaG93LWNoZWNrYm94XG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cIlsyLCAzXVwiXG4gICAgOmRlZmF1bHQtY2hlY2tlZC1rZXlzPVwiWzVdXCJcbiAgICA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIlxuICAvPlxuICA8L2VsLXNjcm9sbGJhcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cbmNvbnN0IGRhdGEgPVtcbiAgICB7XG4gICAgICAgIGlkOiAxLFxuICAgICAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICB9LFxuICAgIHtcbiAgICAgICAgaWQ6IDIsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIH0sXG4gICAge1xuICAgICAgICBpZDogMyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgfSxcbl1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmVsLWNoZWNrYm94e1xuaGVpZ2h0OiB1bnNldCAhaW1wb3J0YW50O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

/cc @YunYouJun Judging from the demo above, it should be that the height of the checkbox exceeds the line height, which causes this problem. I don't know whether to reset the height of the checkbox in the tree or to cancel the default height of the checkbox. I would like to hear your views.

**Comment by YunYouJun** [comment]
Oops, i find it. `.el-checkbox` `height` is `32px`, and this item of list is `26px`.

**Comment by YunYouJun** [comment]
`.el-tree-node__content` `height` is `26px`, so i think we can add a css var for `el-checkbox` height, and set css var in `el-tree-node__content`.

**Comment by YunYouJun** [comment]
I create a PR https://github.com/element-plus/element-plus/pull/13446, please check it.

**Comment by L1yp** [comment]
哈哈上个月我也遇到了这个问题，看到了修复很开心https://discord.com/channels/746646622431346728/902898413094465587/1118145904462024837
