### ISSUE TITLE
[Component] [cascader] el-cascader多选组件在深色模式下展开，下拉框左上角出现异常内容，深色模式可见

### ISSUE THREAD

**Issue by ZQlmh** [element-plus/element-plus#13400]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/113.0.5672.126 Mac OS 13.4`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html#%E5%A4%9A%E9%80%89)

### Steps to reproduce

1、切换官网右上角深色模式
2、点击多选级联input框
3、观察左上角下拉框展开瞬间出现异常白色线框内容

### What is Expected?

下拉框展开时无白色异常内容出现

### What is actually happening?

下拉框展开瞬间有白框异常

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
cascader 还是 calendar ？

**Comment by ZQlmh** [comment]
cascader



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xc ***@***.***&gt;
发送时间: 2023年6月28日 20:47
收件人: element-plus/element-plus ***@***.***&gt;
抄送: LMH ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [element-plus/element-plus] [Component] [calendar] el-cascader多选组件在深色模式下展开，下拉框左上角出现异常内容，深色模式可见 (Issue #13400)





 
cascader 还是 calendar ？

**Comment by chenxch** [comment]
似乎和checkbox有关系

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/bce4b465-f5e0-4f25-9322-ab2ae24826c6)
/cc @YunYouJun  是否可以将这个属性移动到 .el-checkbox__input.is-checked .el-checkbox__inner:after中

**Comment by ZQlmh** [comment]
似乎并不生效

![WeChat05fc1e030eec1b0bcc4593e0dc4412fa](https://github.com/element-plus/element-plus/assets/16482781/d268b300-a255-4a15-a365-2a74cb7a1a30)

**Comment by chenxch** [comment]
https://preview-13402-element-plus.surge.sh/en-US/component/cascader.html#multiple-selection
