### ISSUE TITLE
[Docs] 官网文档报错

### ISSUE THREAD

**Issue by sleepyShen1989** [element-plus/element-plus#13403]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5)

### Steps to reproduce

直接进入组件文档或指南文档
console.error "Hydration completed but contains mismatches." app.36d5fe36.js:4:22897

从首页或者资源进入没有问题

### What is Expected?

no console.error

### What is actually happening?

console.error

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://element-plus.org/
访问这个站点吧，看了下都正常。
