### ISSUE TITLE
[Component] [select] element-plus@2.3.6版本el-select组件收起下拉会触发remote-method方法

### ISSUE THREAD

**Issue by noStaylate** [element-plus/element-plus#13413]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKTtcbmNvbnN0IGNvdW50ID0gcmVmKDApO1xuXG5jb25zdCBnZXREYXRhcyA9ICh2YWw6IFN0cmluZykgPT4ge1xuICBjb3VudC52YWx1ZSArPSAxO1xuICBjb25zb2xlLmxvZyh2YWwpXG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgcGxhY2Vob2xkZXI9XCLor7fpgInmi6lcIiBmaWx0ZXJhYmxlIHJlbW90ZVxuICAgIDpyZW1vdGUtbWV0aG9kPVwiZ2V0RGF0YXNcIiByZXNlcnZlLWtleXdvcmQgcmVtb3RlLXNob3ctc3VmZml4PlxuICAgIDxlbC1vcHRpb24gbGFiZWw9XCLmtYvor5UxXCIgdmFsdWU9XCIxXCIgLz5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5rWL6K+VMlwiIHZhbHVlPVwiMlwiIC8+XG4gICAgPGVsLW9wdGlvbiBsYWJlbD1cIua1i+ivlTNcIiB2YWx1ZT1cIjNcIiAvPlxuICAgIDxlbC1vcHRpb24gbGFiZWw9XCLmtYvor5U0XCIgdmFsdWU9XCI0XCIgLz5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5rWL6K+VNVwiIHZhbHVlPVwiNVwiIC8+XG4gICAgPGVsLW9wdGlvbiBsYWJlbD1cIua1i+ivlTZcIiB2YWx1ZT1cIjZcIiAvPlxuICAgIDxlbC1vcHRpb24gbGFiZWw9XCLmtYvor5U3XCIgdmFsdWU9XCI3XCIgLz5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5rWL6K+VOFwiIHZhbHVlPVwiOFwiIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8c3BhbiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiA4cHg7XCI+XG4gICAg6Kem5Y+Re3sgY291bnQgfX3mrKFcbiAgPC9zcGFuPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点击下拉框，然后收起下拉框，就会触发remote-method里的方法，具体看右边显示的次数

### What is Expected?

展开下拉框和收起下拉框不触发remote-method里的方法

### What is actually happening?

展开下拉框和收起下拉框触发了remote-method里的方法

### Additional comments

_(empty)_

**Comment by kamesan012** [comment]
`
if (props.filterable) {
  if (isFunction(props.filterMethod)) {
    props.filterMethod('')
  }
  if (isFunction(props.remoteMethod)) {
    props.remoteMethod('')
  }
}
`
尝试将select.vue的这段代码删除(264行开始)，下拉框收起时会清除input的值，这时候也会触发一次远程搜索，根据需要决定是否清楚值即可。

**Comment by liuguangsen0409** [comment]
同样遇到了 而且点击 option 里面的选项 也会触发

**Comment by Yaodog** [comment]
这个问题解决没有呀？

**Comment by kooriookami** [comment]
解决了吼
