### ISSUE TITLE
[Component] [input] [Input] maxlength 属性问题

### ISSUE THREAD

**Issue by long-woo** [element-plus/element-plus#13427]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Edge 114.0.1823.55 / Mac OS 13.2 (22D49)`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgbWF4bGVuZ3RoPVwiMlwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJzEyMzQnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

给 input 组件添加一个 `maxlength` 属性值为 `2`，同时设置默认值 `1234`，最终输入框显示 `1234`，没有裁剪超出字符。

```vue
<template>
  <el-input v-model="input" placeholder="Please input" maxlength="2" />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
const input = ref('1234')
</script>
```

![image](https://github.com/element-plus/element-plus/assets/3394035/22d1c806-f079-4ead-bf31-cd588d61e38f)

### What is Expected?

输入框显示 `12`

### What is actually happening?

输入框显示 `1234`

### Additional comments

_(empty)_

**Comment by kamesan012** [comment]
maxlength是input的原生属性，它只会在正常输入的时候进行拦截，不会拦截js赋值时值的长度
