### ISSUE TITLE
[Component] [select] New select option can't be confirmed by the Enter key

### ISSUE THREAD

**Issue by yuri1969** [element-plus/element-plus#13425]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxoMT5BZGQgaXRlbSAmIGNvbmZpcm0gYnkgdGhlIEVudGVyIGtleTwvaDE+XG4gICAgPHA+VXAgdG8gPHN0cm9uZz4yLjIuMzI8L3N0cm9uZz4gaXQncyBwb3NzaWJsZSB0byBrZWVwIGNvbmZpcm1pbmcgYWRkZWQgb3B0aW9ucyBieSB0aGUgRW50ZXIga2V5LlxuICAgIEluIDxzdHJvbmc+Mi4yLjMzKzwvc3Ryb25nPiBqdXN0IHRoZSBpbml0aWFsIG9uZSBjYW4gYmUgY29uZmlybWVkIGJ5IHRoZSBFbnRlciBrZXkuPC9wPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIDptb2RlbC12YWx1ZT1cIm9wdGlvbnNcIlxuICAgICAgQHVwZGF0ZTptb2RlbC12YWx1ZT1cInVwZGF0ZVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgY2xlYXJhYmxlXG4gICAgICBjb2xsYXBzZS10YWdzXG4gICAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgICA6cGVyc2lzdGVudD1cImZhbHNlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQWRkIGl0ZW1zXCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgICA6bGFiZWw9XCJpdGVtXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHVwZGF0ZSA9ICh2YWx1ZSkgPT4gKG9wdGlvbnMudmFsdWUgPSB2YWx1ZS5zbGljZSgpKTtcbmNvbnN0IG9wdGlvbnMgPSByZWYoW10pO1xuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

* Select Element Plus version 2.2.32
* Keep adding new select options by hitting the Enter key
* Select Element Plus 2.2.33 or newer
* Attempt to add new select options by hitting the Enter key

### What is Expected?

The options can be confirmed by the Enter key.

### What is actually happening?

You can confirm just the first option via the Enter key. Any other option can be confirmed by clicking only.

### Additional comments

A change between 2.2.32 and 2.2.33 broke this behavior.

**Comment by yuri1969** [comment]
@kamesan012 It seems you are right. That particular commit dealt with remote search issues - 842fb2b2860b0aab0fb6b2d37f048975c002840d.

**Comment by wzc520pyfm** [comment]
This problem seems to be fixable with https://github.com/element-plus/element-plus/pull/12635
