### ISSUE TITLE
[Component] [sub-menu] 当el-menu处于折叠状态时,el-sub-menu的高度超出可视范围时导致子菜单不能全部显示

### ISSUE THREAD

**Issue by beiTiao-lys** [element-plus/element-plus#13426]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58`
- Build Tool: `Vite`

### Related Component

- `el-sub-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgY29sbGFwc2VcbiAgPCEtLSDor6XmoIfnrb7mqKHmi5/lkI7lj7DnrqHnkIbkuK3nmoTlt6bkvqflm7rlrprkvqfovrnmoI8gLS0+XG4gIDxkaXYgY2xhc3M9XCJsaXl1ZXNoZW5nXCI+XG5cbiAgICA8ZWwtc2Nyb2xsYmFyIGhlaWdodD1cIjQwMHB4XCI+XG4gICAgICA8ZWwtbWVudSBjbGFzcz1cImVsLW1lbnUtdmVydGljYWwtZGVtb1wiIDpjb2xsYXBzZT1cInRydWVcIj5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMVwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgICAgICA8ZWwtaWNvbj5cbiAgICAgICAgICAgICAgPGxvY2F0aW9uIC8+XG4gICAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgT25lPC9zcGFuPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+PHNwYW4+R3JvdXAgT25lPC9zcGFuPjwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDI8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gMzwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSA0PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gNjwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSA3PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDg8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gOTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxMDwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxMTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxMjwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxMzwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxNDwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxNTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxNjwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxNzwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAxODwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+5L2g5aW95oiR5piv5bqV6YOoPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyXCI+XG4gICAgICAgICAgPGVsLWljb24+PEljb25NZW51IC8+PC9lbC1pY29uPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+TmF2aWdhdG9yIFR3bzwvdGVtcGxhdGU+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuXG4gICAgICA8L2VsLW1lbnU+XG4gICAgPC9lbC1zY3JvbGxiYXI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7XG4gIE1lbnUgYXMgSWNvbk1lbnUsXG4gIExvY2F0aW9uLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZWwtbWVudS12ZXJ0aWNhbC1kZW1vOm5vdCguZWwtbWVudS0tY29sbGFwc2UpIHtcbiAgd2lkdGg6IDIwMHB4O1xuICBtaW4taGVpZ2h0OiA0MDBweDtcbn1cbi5saXl1ZXNoZW5ne1xuICBwb3NpdGlvbjogZml4ZWQ7XG4gIHRvcDogNTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

将菜单处于折叠状态,鼠标移至首个一级菜单使二级菜单弹出,滚动鼠标滚轮,二级菜单无法正常展示

### What is Expected?

当超出浏览器可视范围时,让sub-menu本身置于可滚动状态

### What is actually happening?

高度超出会让html出现滚动条,由于insert属性的存在,sub-menu会始终处于屏幕中央,导致html可向下无限滚动,始终无法正确显示被遮盖的sub-menu

### Additional comments

若此问题不属于bug,希望可以帮我提出一个可行的解决方案,谢谢(●'◡'●)

![image](https://github.com/element-plus/element-plus/assets/84766338/247fb211-53e7-44f7-b035-af892e658fc0)

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgY29sbGFwc2VcbiAgPCEtLSDor6XmoIfnrb7mqKHmi5/lkI7lj7DnrqHnkIbkuK3nmoTlt6bkvqflm7rlrprkvqfovrnmoI8gLS0+XG4gIDxkaXYgY2xhc3M9XCJsaXl1ZXNoZW5nXCI+XG5cbiAgICA8ZWwtc2Nyb2xsYmFyIGhlaWdodD1cIjQwMHB4XCI+XG4gICAgICA8ZWwtbWVudSBjbGFzcz1cImVsLW1lbnUtdmVydGljYWwtZGVtb1wiIDpjb2xsYXBzZT1cInRydWVcIj5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMVwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgICAgICA8ZWwtaWNvbj5cbiAgICAgICAgICAgICAgPGxvY2F0aW9uIC8+XG4gICAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgT25lPC9zcGFuPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCBzdHlsZT1cIm1heC1oZWlnaHQ6NTAwcHg7IG92ZXJmbG93LXk6YXV0b1wiPlxuICAgICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT48c3Bhbj5Hcm91cCBPbmU8L3NwYW4+PC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gMjwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSAzPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDQ8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gNTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSA2PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDc8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTItMVwiPml0ZW0gODwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMi0xXCI+aXRlbSA5PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDEwPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDExPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDEyPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDEzPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE0PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE1PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE2PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE3PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj5pdGVtIDE4PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yLTFcIj7kvaDlpb3miJHmmK/lupXpg6g8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48SWNvbk1lbnUgLz48L2VsLWljb24+XG4gICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5OYXZpZ2F0b3IgVHdvPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1tZW51LWl0ZW0+XG5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLXNjcm9sbGJhcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgTWVudSBhcyBJY29uTWVudSxcbiAgTG9jYXRpb24sXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5lbC1tZW51LXZlcnRpY2FsLWRlbW86bm90KC5lbC1tZW51LS1jb2xsYXBzZSkge1xuICB3aWR0aDogMjAwcHg7XG4gIG1pbi1oZWlnaHQ6IDQwMHB4O1xufVxuLmxpeXVlc2hlbmd7XG4gIHBvc2l0aW9uOiBmaXhlZDtcbiAgdG9wOiA1MHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

看看这个可以不

**Comment by beiTiao-lys** [comment]
这个解决方案与我想的一致, 非常的完美, 谢谢

**Comment by chenxch** [comment]
那我就关闭这个issue了哈
