### ISSUE TITLE
[Component] 弹窗式组件都存在内存泄露

### ISSUE THREAD

**Issue by caoguanjie** [element-plus/element-plus#13459]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.21`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-dropdown`
- `el-popper`
- `el-popover`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8dGVtcGxhdGVcbiAgICAgICAgOmtleT1cIml0ZW1cIlxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiPlxuICAgICAgPGNvbXAtYS8+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IENvbXBBIGZyb20gJy4vQ29tcEEudnVlJ1xuXG5jb25zdCBsaXN0ID0gcmVmKFtdKVxuXG5zZXRJbnRlcnZhbCgoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbe31dXG59LCAxMDAwKVxuXG5zZXRJbnRlcnZhbCgoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbXVxufSwgMTUwMClcblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInNyYy9Db21wQS52dWUiOiI8dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLXNlbGVjdD48L2VsLXNlbGVjdD5cbiAgICA8ZWwtc2VsZWN0PjwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIG5hbWU6ICdDb21wQScsXG4gIHByb3BzOiB7XG4gICAgZGF0YTogT2JqZWN0XG4gIH0sXG4gIGRhdGEgKCkge1xuICAgIHJldHVybiB7XG4gICAgICBjYWNoZTogbmV3IEFycmF5KDQwMDAwMDApLmZpbGwoMCkuam9pbignJylcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuXG48L3N0eWxlPlxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

我以el-dialog组件举例，只要页面有用到它，那么这个页面占用的内存就得不到释放，但是如果我配置属性：append-to-body，内存就能得到释放
同样地，如果使用el-popover组件的页面，都得不到内存的释放，配置该属性：:persistent="false"就可以，但是一旦激活了组件，内存还是得不到释放
同理，其他弹窗式组件el-select等等都是这样

### What is Expected?

能释放父组件的占用的内存

### What is actually happening?

内存得不到释放

### Additional comments

我这边已经排查出问题了，的确有可能是vue的内置组件Teleport造成的，也有相应的issues：https://github.com/vuejs/core/issues/6347
vue官方不修复Teleport组件的问题的时候，希望element-plus团队尽快给出不使用Teleport的配置项供开发者选择，避免内存泄露影响

**Comment by emojiiii** [comment]
这些弹窗组件都有一个属性叫 `teleported`, 可以尝试一下

**Comment by songyx95** [comment]
> 这些弹窗组件都有一个属性叫 `teleported`, 可以尝试一下
> 
> https://element-plus.org/zh-CN/component/popover.html#attributes

都加上这个属性了，另外也设置了:persistent=false(组件有这个属性的话)，内存也扩大了，一样是内存泄漏，Out of Memory

**Comment by tolking** [comment]
很可能 #13158 修复了部分问题

**Comment by Clareyang213** [comment]
大神，这个问题解决了没？急急急

**Comment by 1zxca** [comment]
依然没解决  已测试 #13158 ，内存还是增加 现在加append-to-body内存涨少了一点

**Comment by JinLShan** [comment]
el-pagination也有这个问题

**Comment by sangyong1203** [comment]
设置 KeepAlive 的max值， 会解决一部分问题。 然后当关闭弹窗时清空所有数据。
<KeepAlive :max="10">
  <component :is="activeComponent" />
</KeepAlive>

**Comment by Joshua-Leee** [comment]
刚刚更新了最新版本，vue@3.4.1，element-plus@2.4.4，下拉选择器好了，但日期组件仍然存在内存泄露，游离元素无法被回收，有大佬解决这个问题了吗

**Comment by a1225282494** [comment]
el-table、el-tabs等组件还是会有内存堆积无法释放的问题。vue3 element-plus官网自己就有这个情况。多次来回切换组件，内存一直在堆积。
