### ISSUE TITLE
[Bug Report] I set locale to zh-cn, but table and pagination still show English

### ISSUE THREAD

**Issue by Yayoiqz** [element-plus/element-plus#1345]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
Chrome 88.0.4324.96（正式版本） (x86_64)

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/yayoiqz/pen/yLadMzP

### Steps to reproduce
set locale to zh-cn
use table and pagination

### What is Expected?
show Chinese

### What is actually happening?
show English

**Comment by Yayoiqz** [comment]
By the way,  there is still a bug in issue page。The link of codesandbox will make validator fail, and block the process.
![image](https://user-images.githubusercontent.com/23414662/105658061-b4081780-5f00-11eb-98a7-25e5dc3a4385.png)

**Comment by JeremyWuuuuu** [comment]
@Yayoiqz Thank you for filing this issue, your image actually didn't get uploaded, could you upload that again? We will fix that  soon, sorry for the inconvenience.

**Comment by Yayoiqz** [comment]
<img width="921" alt="snapshot" src="https://user-images.githubusercontent.com/23414662/105658950-950a8500-5f02-11eb-831a-5584d567e670.png">
How about this?

**Comment by JeremyWuuuuu** [comment]
Yep, I can see the image now, we will fix that soon. cc @zazzaz

**Comment by JeremyWuuuuu** [comment]
@Yayoiqz I still need that link, could you please paste that link here?

**Comment by JeremyWuuuuu** [comment]
Seems some bug in locale package. 
![image](https://user-images.githubusercontent.com/15975785/105659832-ae143580-5f04-11eb-852a-c792987aae1e.png)

**Comment by zazzaz** [comment]
```
import { createApp } from "vue";
import App from "./App.vue";
import lang from "element-plus/lib/locale/lang/zh-cn";
import "dayjs/locale/zh-cn";
// import locale from "element-plus/lib/locale";
import "element-plus/lib/theme-chalk/index.css";

import { ElTable, ElTableColumn, ElPagination, locale } from "element-plus";
const components = [ElTable, ElTableColumn, ElPagination];
locale(lang);
const app = createApp(App);

components.forEach((component) => {
  app.component(component.name, component);
});

app.mount("#app");

```
You should import `locale` from `element-plus` the same as import  a component.

**Comment by Yayoiqz** [comment]
> ```
> import { createApp } from "vue";
> import App from "./App.vue";
> import lang from "element-plus/lib/locale/lang/zh-cn";
> import "dayjs/locale/zh-cn";
> // import locale from "element-plus/lib/locale";
> import "element-plus/lib/theme-chalk/index.css";
> 
> import { ElTable, ElTableColumn, ElPagination, locale } from "element-plus";
> const components = [ElTable, ElTableColumn, ElPagination];
> locale(lang);
> const app = createApp(App);
> 
> components.forEach((component) => {
>   app.component(component.name, component);
> });
> 
> app.mount("#app");
> ```
> 
> You should import `locale` from `element-plus` the same as import a component.

Thanks, this really works.
I just write same as the Docs， maybe the Docs should be updated， or locale to be updated.

**Comment by JeremyWuuuuu** [comment]
Sure, we will update it.

**Comment by zhenzhenChange** [comment]
I just followed the instructions of the document to configure, indeed, it did not take effect, but fortunately found here, according to the method upstairs to configure successfully, the Chinese document did not update this description

我刚刚也是按照文档的说明进行配置，确实是没有生效，还好找到了这里，按照楼上的方法配置成功了，中文文档没有更新这个配置方法

**Comment by yshAnswer** [comment]
I do this, it works
![image](https://user-images.githubusercontent.com/24540820/112292641-4001aa00-8ccc-11eb-87bc-af19eb40089d.png)
 if demand loading,
![image](https://user-images.githubusercontent.com/24540820/112292498-1b0d3700-8ccc-11eb-9e0b-614069c1d3c9.png)
when import 'locale', there will be an error occurred
![image](https://user-images.githubusercontent.com/24540820/112292188-c9fd4300-8ccb-11eb-842a-cb5666545fcf.png)
Here ，I decide a condition when name is 'locale' ,return a static css file, like this:
![image](https://user-images.githubusercontent.com/24540820/112292018-a3d7a300-8ccb-11eb-8c9a-8e58acbe743e.png)
 Is there an optimal solution? @JeremyWuuuuu

**Comment by oooowl** [comment]
nuxt3 is the same as
