### ISSUE TITLE
[Docs] [progress] Progress文档描述错误

### ISSUE THREAD

**Issue by Xianyu123465** [element-plus/element-plus#13466]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-progress`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/progress.html)

### Steps to reproduce

进度条显示百分比标识中对stroke-width的描述是属性更改进度条的高度，而在Api的属性中的描述是进度条的宽度

### What is Expected?

stroke-width在Api的描述中改为进度条的高度

### What is actually happening?

stroke-width在Api的描述为进度条的宽度

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
中文翻译问题了 https://crowdin.com/translate/element-plus/831/en-zhcn?filter=basic&value=0

**Comment by Xianyu123465** [comment]
> 中文翻译问题了 https://crowdin.com/translate/element-plus/831/en-zhcn?filter=basic&value=0

好了 已提交

**Comment by chenxch** [comment]
首先感谢你们帮忙给ep把关文档，不过这个应该没有问题哈，在2D平面应该只有长宽。

**Comment by chenxch** [comment]
如果没有其他疑问，我先关闭了哦
