### ISSUE TITLE
[Style] [tree] el-tree,一次性展開所有節點時動畫錯誤

### ISSUE THREAD

**Issue by dianxianbaobao** [element-plus/element-plus#13468]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome  113.0.5672.127 Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICAgIDxlbC10cmVlXG4gICAgICA6ZGF0YT1cImRhdGFcIlxuICAgICAgOnByb3BzPVwiZGVmYXVsdFByb3BzXCJcbiAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgICBjbGFzcz1cIm15RG9jTWVtdVwiXG4gICAgICByZWY9XCJteUVsVHJlZVwiXG4gICAgLz5cbiAgICA8RWxCdXR0b24gQGNsaWNrPVwic2hvd0FsbFRyZWVOb2RlXCI+c2hvdzwvRWxCdXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSdcbmNvbnN0IG15RWxUcmVlID0gcmVmKClcbmNvbnN0IGlzU2hvd0FsbFRyZWVOb2RlID0gcmVmKHRydWUpIC8v5piv5ZCm5bGV6ZaL5omA5pyJ56+A6bueXG5pbnRlcmZhY2UgVHJlZSB7XG5pZDpzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBkYXRhOiBUcmVlW10gPSBbXG4gIHtcbiAgICBpZDogJ2gxLTEnLFxuICAgIGxhYmVsOiAnSDHmoIfpophoMS0xJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogJ2gyLTEnLFxuICAgICAgICBsYWJlbDogJ2gy5qCH6aKYaDItMScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogJ2gyLTInLFxuICAgICAgICBsYWJlbDogJ2gy5qCH6aKYaDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6ICdoMy0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnaDPmoIfpophoMy0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAnaDMtMicsXG4gICAgICAgICAgICBsYWJlbDogJ2gz5qCH6aKYaDMtMicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAnaDEtMicsXG4gICAgbGFiZWw6ICdIMeagh+mimGgxLTInLFxuICB9LFxuXVxuXG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cblxuZnVuY3Rpb24gc2hvd0FsbFRyZWVOb2RlKCkge1xuICBjb25zdCB0cmVlTm9kZSA9IG15RWxUcmVlLnZhbHVlLnN0b3JlLm5vZGVzTWFwXG4gIGZvciAobGV0IGtleSBpbiB0cmVlTm9kZSkge1xuICAgICAgdHJlZU5vZGVba2V5XS5leHBhbmRlZCA9ICFpc1Nob3dBbGxUcmVlTm9kZS52YWx1ZVxuICB9XG4gIGlzU2hvd0FsbFRyZWVOb2RlLnZhbHVlID0gIWlzU2hvd0FsbFRyZWVOb2RlLnZhbHVlXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1、我寫了一個方法，這個方法會將treeNode中所有的節點的expande改爲true或者false,以此來一次性展開或關閉所有節點。
2、執行這個方法

### What is Expected?

節點都展開並執行相應的動畫

### What is actually happening?

節點展開，但是動畫閃現

### Additional comments
我大概知道是什麽原因造成的，想問下有沒有其他方法可以做到一次性展開所有節點呢？

**Comment by dianxianbaobao** [comment]
https://github.com/element-plus/element-plus/assets/138119538/3da3dfe6-db8b-4ee4-adcc-77c742133fb5

**Comment by kamesan012** [comment]
逐层展开试试
