### ISSUE TITLE
[Build] [All]  ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#13460]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.4`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548)

### Steps to reproduce

在本地pnpm build 没有问题
在github actions 报如下错误：
[10:35:14] ReferenceError: __name is not defined
 ELIFECYCLE  Command failed with exit code 1.
[10:35:14] 'shellTask:buildModules' errored after 22 s
[10:35:14] /home/runner/work/***/***/internal/build/src/utils/process.ts:24
          new Error(`Command failed. \n Command: ${command} \n Code: ${code}`)
          ^

Error: Command failed. 

### What is Expected?

no error

### What is actually happening?

在github actions 报如下错误：
[10:35:14] ReferenceError: __name is not defined
 ELIFECYCLE  Command failed with exit code 1.
[10:35:14] 'shellTask:buildModules' errored after 22 s
[10:35:14] /home/runner/work/***/***/internal/build/src/utils/process.ts:24
          new Error(`Command failed. \n Command: ${command} \n Code: ${code}`)
          ^

Error: Command failed. 

### Additional comments

null

**Comment by chenweiyi** [comment]
I have also encountered this issue. Have you managed to solve it?

**Comment by chenweiyi** [comment]
> I have also encountered this issue. Have you managed to solve it?



> Bug Type: **`Build`**
> 
> ## Environment
> * Vue Version: `3.2.37`
> * Element Plus Version: `2.3.4`
> * Browser / OS: `105.0.5195.102（正式版本） （64 位）`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `All`
> 
> ### Reproduction Link
> [Github Repo](https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548)
> 
> ### Steps to reproduce
> 在本地pnpm build 没有问题 在github actions 报如下错误： [10:35:14] ReferenceError: __name is not defined  ELIFECYCLE  Command failed with exit code 1. [10:35:14] 'shellTask:buildModules' errored after 22 s [10:35:14] /home/runner/work/_**/**_/internal/build/src/utils/process.ts:24 new Error(`Command failed. \n Command: ${command} \n Code: ${code}`) ^
> 
> Error: Command failed.
> 
> ### What is Expected?
> no error
> 
> ### What is actually happening?
> 在github actions 报如下错误： [10:35:14] ReferenceError: __name is not defined  ELIFECYCLE  Command failed with exit code 1. [10:35:14] 'shellTask:buildModules' errored after 22 s [10:35:14] /home/runner/work/_**/**_/internal/build/src/utils/process.ts:24 new Error(`Command failed. \n Command: ${command} \n Code: ${code}`) ^
> 
> Error: Command failed.
> 
> ### Additional comments
> null

I have also encountered this issue. Have you managed to solve it?

**Comment by chenweiyi** [comment]
I have also encountered this issue. Have you managed to solve it?

**Comment by chenweiyi** [comment]
I switched my node version to 16 and reinstalled the dependencies to resolve this issue.

**Comment by sdjnduantong** [comment]
我本地打包页报这个错误，请问如何解决

**Comment by yaoyao1987** [comment]
打包环境比较严格，需要node版本设置为16，pnpm版本设置为7.3.0

**Comment by lixiaofa** [comment]
我解决了， 但是我忘记怎么解决的

**Comment by LKen** [comment]
> 我解决了， 但是我忘记怎么解决的

请问如何解决的？

**Comment by G1King** [comment]
@lixiaofa 老哥 咋解决的啊

**Comment by G1King** [comment]
@yaoyao1987     node 16.16 pnpm 8.3 还是报这个错误

**Comment by yaoyao1987** [comment]
> @yaoyao1987 node 16.16 pnpm 8.3 还是报这个错误

pnpm需要将为7.x

**Comment by G1King** [comment]
The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed 有没有遇到这个问题啊  build 之后 @yaoyao1987

**Comment by G1King** [comment]
> 

解决了 对比了才发现 得7.x

**Comment by lixiaofa** [comment]
@G1King @yaoyao1987 @chenweiyi @HeftyKoo 你们都在element plus 上二开吗 ， 我们可以加个群交流啊

**Comment by G1King** [comment]
> @G1King @yaoyao1987 @chenweiyi @HeftyKoo 你们都在element plus 上二开吗 ， 我们可以加个群交流啊

我们是 基于 ele 开发自己的业务组件的  怎么加群

**Comment by lixiaofa** [comment]
我建一个群 ， 我微信 L15999673889

**Comment by Jam1zhu** [comment]
`node@16.20.2`、`pnpm@7.3.0`，还是有这个问题。还有什么需要注意的吗

**Comment by JuniorMeng** [comment]
我在将element plus 升级时也遇到这个错误，最终找到是因为一个次级依赖"@esbuild-kit/core-utils"版本过高导致的，于是加了
"overrides": {
      "@esbuild-kit/core-utils": "2.0.2"
 }
即可build成功。 另@esbuild-kit/cjs-loader版本最好也锁死到2.2.1。

**Comment by imycod** [comment]
"@esbuild-kit/cjs-loader": "2.2.1" 锁死版本  或者重装 依赖， 去gitee clone 重装试试
pnpm -v
9.15.9
node -v
v23.11.1
npm -v
10.9.2
