### ISSUE TITLE
[table-v2] Element Plus Playground 不支持 tsx

### ISSUE THREAD

**Issue by 1368725603** [element-plus/element-plus#13479]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome/114.0.5735.91`
- Build Tool: `CDN`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImhlaWdodDogNDAwcHhcIj5cbiAgICA8ZWwtYXV0by1yZXNpemVyPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBoZWlnaHQsIHdpZHRoIH1cIj5cbiAgICAgICAgPGVsLXRhYmxlLXYyXG4gICAgICAgICAgOmNvbHVtbnM9XCJjb2x1bW5zXCJcbiAgICAgICAgICA6ZGF0YT1cImRhdGFcIlxuICAgICAgICAgIDp3aWR0aD1cIndpZHRoXCJcbiAgICAgICAgICA6aGVpZ2h0PVwiaGVpZ2h0XCJcbiAgICAgICAgICBmaXhlZFxuICAgICAgICAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWF1dG8tcmVzaXplcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c3hcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgdW5yZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbENoZWNrYm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbXBvcnQgdHlwZSB7IEZ1bmN0aW9uYWxDb21wb25lbnQgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IENoZWNrYm94VmFsdWVUeXBlLCBDb2x1bW4gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbnR5cGUgU2VsZWN0aW9uQ2VsbFByb3BzID0ge1xuICB2YWx1ZTogYm9vbGVhblxuICBpbnRlcm1lZGlhdGU/OiBib29sZWFuXG4gIG9uQ2hhbmdlOiAodmFsdWU6IENoZWNrYm94VmFsdWVUeXBlKSA9PiB2b2lkXG59XG5cbmNvbnN0IFNlbGVjdGlvbkNlbGw6IEZ1bmN0aW9uYWxDb21wb25lbnQ8U2VsZWN0aW9uQ2VsbFByb3BzPiA9ICh7XG4gIHZhbHVlLFxuICBpbnRlcm1lZGlhdGUgPSBmYWxzZSxcbiAgb25DaGFuZ2UsXG59KSA9PiB7XG4gIHJldHVybiAoXG4gICAgPEVsQ2hlY2tib3hcbiAgICAgIG9uQ2hhbmdlPXtvbkNoYW5nZX1cbiAgICAgIG1vZGVsVmFsdWU9e3ZhbHVlfVxuICAgICAgaW5kZXRlcm1pbmF0ZT17aW50ZXJtZWRpYXRlfVxuICAgIC8+XG4gIClcbn1cblxuY29uc3QgZ2VuZXJhdGVDb2x1bW5zID0gKGxlbmd0aCA9IDEwLCBwcmVmaXggPSAnY29sdW1uLScsIHByb3BzPzogYW55KSA9PlxuICBBcnJheS5mcm9tKHsgbGVuZ3RoIH0pLm1hcCgoXywgY29sdW1uSW5kZXgpID0+ICh7XG4gICAgLi4ucHJvcHMsXG4gICAga2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIGRhdGFLZXk6IGAke3ByZWZpeH0ke2NvbHVtbkluZGV4fWAsXG4gICAgdGl0bGU6IGBDb2x1bW4gJHtjb2x1bW5JbmRleH1gLFxuICAgIHdpZHRoOiAxNTAsXG4gIH0pKVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoXG4gIGNvbHVtbnM6IFJldHVyblR5cGU8dHlwZW9mIGdlbmVyYXRlQ29sdW1ucz4sXG4gIGxlbmd0aCA9IDIwMCxcbiAgcHJlZml4ID0gJ3Jvdy0nXG4pID0+XG4gIEFycmF5LmZyb20oeyBsZW5ndGggfSkubWFwKChfLCByb3dJbmRleCkgPT4ge1xuICAgIHJldHVybiBjb2x1bW5zLnJlZHVjZShcbiAgICAgIChyb3dEYXRhLCBjb2x1bW4sIGNvbHVtbkluZGV4KSA9PiB7XG4gICAgICAgIHJvd0RhdGFbY29sdW1uLmRhdGFLZXldID0gYFJvdyAke3Jvd0luZGV4fSAtIENvbCAke2NvbHVtbkluZGV4fWBcbiAgICAgICAgcmV0dXJuIHJvd0RhdGFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiBgJHtwcmVmaXh9JHtyb3dJbmRleH1gLFxuICAgICAgICBjaGVja2VkOiBmYWxzZSxcbiAgICAgICAgcGFyZW50SWQ6IG51bGwsXG4gICAgICB9XG4gICAgKVxuICB9KVxuXG5jb25zdCBjb2x1bW5zOiBDb2x1bW48YW55PltdID0gZ2VuZXJhdGVDb2x1bW5zKDEwKVxuY29sdW1ucy51bnNoaWZ0KHtcbiAga2V5OiAnc2VsZWN0aW9uJyxcbiAgd2lkdGg6IDUwLFxuICBjZWxsUmVuZGVyZXI6ICh7IHJvd0RhdGEgfSkgPT4ge1xuICAgIGNvbnN0IG9uQ2hhbmdlID0gKHZhbHVlOiBDaGVja2JveFZhbHVlVHlwZSkgPT4gKHJvd0RhdGEuY2hlY2tlZCA9IHZhbHVlKVxuICAgIHJldHVybiA8U2VsZWN0aW9uQ2VsbCB2YWx1ZT17cm93RGF0YS5jaGVja2VkfSBvbkNoYW5nZT17b25DaGFuZ2V9IC8+XG4gIH0sXG5cbiAgaGVhZGVyQ2VsbFJlbmRlcmVyOiAoKSA9PiB7XG4gICAgY29uc3QgX2RhdGEgPSB1bnJlZihkYXRhKVxuICAgIGNvbnN0IG9uQ2hhbmdlID0gKHZhbHVlOiBDaGVja2JveFZhbHVlVHlwZSkgPT5cbiAgICAgIChkYXRhLnZhbHVlID0gX2RhdGEubWFwKChyb3cpID0+IHtcbiAgICAgICAgcm93LmNoZWNrZWQgPSB2YWx1ZVxuICAgICAgICByZXR1cm4gcm93XG4gICAgICB9KSlcbiAgICBjb25zdCBhbGxTZWxlY3RlZCA9IF9kYXRhLmV2ZXJ5KChyb3cpID0+IHJvdy5jaGVja2VkKVxuICAgIGNvbnN0IGNvbnRhaW5zQ2hlY2tlZCA9IF9kYXRhLnNvbWUoKHJvdykgPT4gcm93LmNoZWNrZWQpXG5cbiAgICByZXR1cm4gKFxuICAgICAgPFNlbGVjdGlvbkNlbGxcbiAgICAgICAgdmFsdWU9e2FsbFNlbGVjdGVkfVxuICAgICAgICBpbnRlcm1lZGlhdGU9e2NvbnRhaW5zQ2hlY2tlZCAmJiAhYWxsU2VsZWN0ZWR9XG4gICAgICAgIG9uQ2hhbmdlPXtvbkNoYW5nZX1cbiAgICAgIC8+XG4gICAgKVxuICB9LFxufSlcblxuY29uc3QgZGF0YSA9IHJlZihnZW5lcmF0ZURhdGEoY29sdW1ucywgMjAwKSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

在 Element Plus 官网中，使用 Playground 打开任意使用 tsx 的案例组件，就会复现

### What is Expected?

tsx 也支持

### What is actually happening?

Only lang="ts" is supported for script blocks.

### Additional comments

Element Plus Playground 不支持 tsx，这样会造成两个问题：
1.很多官方案例不能在 Playground 里调试
2.el-table-v2 组件的 issue 不能使用 Element Plus Playground 来提供复现环境。

![屏幕截图 2023-07-05 003149](https://github.com/element-plus/element-plus/assets/37211488/db31ce15-3208-40cc-869f-71194251b4f5)

**Comment by chenxch** [comment]
https://github.com/vuejs/repl/pull/68
