### ISSUE TITLE
[Bug Report] Popover props 'open-delay' can't be used

### ISSUE THREAD

**Issue by zangxiyang** [element-plus/element-plus#1347]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
Chrome 版本 87.0.4280.141（正式版本） (arm64)

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-se9r5

### Steps to reproduce
1. Create the element plus componet `<el-popover>`.
2. Setting the prop 'open-delay' to 900.

### What is Expected?
When open the pop it shoud be delay.

### What is actually happening?
When open the pop it can't be delay

**Comment by tinycold** [comment]
You should use `show-after` now.

**Comment by JeremyWuuuuu** [comment]
I think this is a mistake that we didn't update the documentation in time. Sorry for the inconvenience.

**Comment by zangxiyang** [comment]
Thank you for your answer. 
Because I'm just getting started with typescript, I didn't find the dependent content when I looked at the source code.
