### ISSUE TITLE
[Component] [descriptions-item] el-descriptions-item component's customer style(attribute class-name and label-class-name) is invalid.

### ISSUE THREAD

**Issue by YoosonChan** [element-plus/element-plus#13480]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome/114.0.5735.199`
- Build Tool: `Vite`

### Related Component

- `el-descriptions-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRlc2NyaXB0aW9ucyB0aXRsZT1cIkN1c3RvbWl6ZWQgc3R5bGUgbGlzdFwiIDpjb2x1bW49XCIzXCIgYm9yZGVyPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbVxuICAgICAgbGFiZWw9XCJVc2VybmFtZVwiXG4gICAgICBsYWJlbC1hbGlnbj1cInJpZ2h0XCJcbiAgICAgIGFsaWduPVwiY2VudGVyXCJcbiAgICAgIGxhYmVsLWNsYXNzLW5hbWU9XCJteS1sYWJlbFwiXG4gICAgICBjbGFzcy1uYW1lPVwibXktY29udGVudFwiXG4gICAgICB3aWR0aD1cIjE1MHB4XCJcbiAgICAgID5rb29yaW9va2FtaTwvZWwtZGVzY3JpcHRpb25zLWl0ZW1cbiAgICA+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVGVsZXBob25lXCIgbGFiZWwtYWxpZ249XCJyaWdodFwiIGFsaWduPVwiY2VudGVyXCJcbiAgICAgID4xODEwMDAwMDAwMDwvZWwtZGVzY3JpcHRpb25zLWl0ZW1cbiAgICA+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiUGxhY2VcIiBsYWJlbC1hbGlnbj1cInJpZ2h0XCIgYWxpZ249XCJjZW50ZXJcIlxuICAgICAgPlN1emhvdTwvZWwtZGVzY3JpcHRpb25zLWl0ZW1cbiAgICA+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiUmVtYXJrc1wiIGxhYmVsLWFsaWduPVwicmlnaHRcIiBhbGlnbj1cImNlbnRlclwiPlxuICAgICAgPGVsLXRhZyBzaXplPVwic21hbGxcIj5TY2hvb2w8L2VsLXRhZz5cbiAgICA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIkFkZHJlc3NcIiBsYWJlbC1hbGlnbj1cInJpZ2h0XCIgYWxpZ249XCJjZW50ZXJcIlxuICAgICAgPk5vLjExODgsIFd1emhvbmcgQXZlbnVlLCBXdXpob25nIERpc3RyaWN0LCBTdXpob3UsIEppYW5nc3VcbiAgICAgIFByb3ZpbmNlPC9lbC1kZXNjcmlwdGlvbnMtaXRlbVxuICAgID5cbiAgPC9lbC1kZXNjcmlwdGlvbnM+XG48L3RlbXBsYXRlPlxuPHN0eWxlIHNjb3BlZD5cbi5teS1sYWJlbCB7XG4gIGJhY2tncm91bmQ6IHZhcigtLWVsLWNvbG9yLXN1Y2Nlc3MtbGlnaHQtOSk7XG59XG4ubXktY29udGVudCB7XG4gIGJhY2tncm91bmQ6IHZhcigtLWVsLWNvbG9yLWRhbmdlci1saWdodC05KTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

The original code of the component document by Element Plus Playground

### What is Expected?

valid style

### What is actually happening?

invald style

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
< style ~~scoped~~ >
