### ISSUE TITLE
[Bug Report] DatePicker default value is not working

### ISSUE THREAD

**Issue by ochanje210** [element-plus/element-plus#1348]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
macOS / chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/ochanje210/pen/zYKVEjx

### Steps to reproduce
just simple default value is not working even in the docs.

### What is Expected?
default value should be shown initially

### What is actually happening?
default value is not working

**Comment by zazzaz** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/10731096/105684795-60152700-5f30-11eb-8ace-e6e65076838c.png">

According to the reproduction link, it shows the expected month and year.

**Comment by JeremyWuuuuu** [comment]
@zazzaz I think he might mean that the given date wasn't selected?

**Comment by JeremyWuuuuu** [comment]
This could be misunderstanding of the usage of `default-value` or maybe we just implemented the feature incorrectly? Which one is this?

**Comment by zazzaz** [comment]
In Element UI, seems the default-value only shows the month, but not select the value.

This a good point to discuss with, still.

**Comment by ochanje210** [comment]
Oh..! I misunderstood as @JeremyWuuuuu said.

This is quite confusing.

**Comment by JeremyWuuuuu** [comment]
Please do update documentation for avoiding further confusion @zazzaz

**Comment by chenxch** [comment]
The functionality and documentation are confirmed and I will close this issue.
