### ISSUE TITLE
[Style] [form, form-item] 如何通过覆盖 scss 变量来修改 el-form、el-form-item 的相关样式

### ISSUE THREAD

**Issue by sunvictor** [element-plus/element-plus#13514]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.7`
- Browser / OS: `Google Chrome /14.0.5735.134`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Github Repo](https://github.com/sunvictor/test-theme-chalk)

### Steps to reproduce

直接运行项目就能看到错误

### What is Expected?

正常修改 form.scss 样式不报错

### What is actually happening?

修改 form.scss 样式报错

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://element-plus.org/zh-CN/guide/theming.html#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%AE%83%EF%BC%9F
