### ISSUE TITLE
[Component] [select] inline form 下的select组件，input部分宽度被默认设置了220px(--el-form-inline-content-width)

### ISSUE THREAD

**Issue by aishumiao** [element-plus/element-plus#13525]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.7`
- Browser / OS: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[CodePen](https://codepen.io/taromisaki/pen/YzREVJZ)

### Steps to reproduce

1，el-form（inline）
2，添加el-select组件

### What is Expected?

整体组件宽度不为固定值，自适应上级节点

### What is actually happening?

宽度固定，导致即使设置el-select的宽度，组件也会被类名为el-input的节点撑开

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed by #13375

**Comment by Allihol** [comment]
请问各位大佬，这个问题修复了吗？
我目前使用2.3.7，在form inline的场景下，el-select里的el-input使用的css变量值仍然是220px，没有自适应。

**Comment by Allihol** [comment]
> 

el-form下的--el-form-inline-content-width仍然是220px啊

**Comment by btea** [comment]
新版本还未发布，请等待新版本发布或者版本回退。

**Comment by Allihol** [comment]
请问需要回退到哪个版本呢

**Comment by btea** [comment]
2.3.6就可以了，这个修改是在2.3.7发布的。这是更新[日志](https://github.com/element-plus/element-plus/blob/dev/CHANGELOG.en-US.md#features)。

**Comment by Allihol** [comment]
多谢~
