### ISSUE TITLE
[Component] [form-item] 当el-form 设置  label-position="top"时  点击form-item   label部分的时候，form-item中的input会自动聚焦

### ISSUE THREAD

**Issue by yuanzengding-1234** [element-plus/element-plus#13527]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.4`
- Browser / OS: `chrome`
- Build Tool: `Vite`

## Reproduction
![25e1120a45916ad03bf324496e02c27](https://github.com/element-plus/element-plus/assets/56818385/bcbad079-26ab-4904-b874-6f91545d60c0)

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm1cbiAgICByZWY9XCJmb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJudW1iZXJWYWxpZGF0ZUZvcm1cIlxuICAgIGxhYmVsLXdpZHRoPVwiMTAwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gICAgbGFiZWwtcG9zaXRpb249XCJ0b3BcIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJhZ2VcIlxuICAgICAgcHJvcD1cImFnZVwiXG4gICAgICA6cnVsZXM9XCJbXG4gICAgICAgIHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdhZ2UgaXMgcmVxdWlyZWQnIH0sXG4gICAgICAgIHsgdHlwZTogJ251bWJlcicsIG1lc3NhZ2U6ICdhZ2UgbXVzdCBiZSBhIG51bWJlcicgfSxcbiAgICAgIF1cIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsLm51bWJlcj1cIm51bWJlclZhbGlkYXRlRm9ybS5hZ2VcIlxuICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgIGF1dG9jb21wbGV0ZT1cIm9mZlwiXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuXG5jb25zdCBudW1iZXJWYWxpZGF0ZUZvcm0gPSByZWFjdGl2ZSh7XG4gIGFnZTogJycsXG59KVxuXG5jb25zdCBzdWJtaXRGb3JtID0gKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XG4gIGlmICghZm9ybUVsKSByZXR1cm5cbiAgZm9ybUVsLnZhbGlkYXRlKCh2YWxpZCkgPT4ge1xuICAgIGlmICh2YWxpZCkge1xuICAgICAgY29uc29sZS5sb2coJ3N1Ym1pdCEnKVxuICAgIH0gZWxzZSB7XG4gICAgICBjb25zb2xlLmxvZygnZXJyb3Igc3VibWl0IScpXG4gICAgICByZXR1cm4gZmFsc2VcbiAgICB9XG4gIH0pXG59XG5cbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC5yZXNldEZpZWxkcygpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

进入网址  点击age之后，输入框会自动聚焦

### What is Expected?

当el-form 设置  label-position="top"时  点击age的时候 不自动聚焦input

### What is actually happening?

当el-form 设置  label-position="top"时  点击age的时候 自动聚焦input

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
Ant Design也是点label的时候会聚焦，个人感觉这是优化😁

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/issues/9752
Please search the question before asking, maybe you can solve your problem quickly.
