### ISSUE TITLE
[Component] [select] Support Vertically centering el-message

### ISSUE THREAD

**Issue by xwillmadeit** [element-plus/element-plus#13524]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Link]()

### Steps to reproduce

none

### What is Expected?

Pass an center prop to el-message or change el-message css top property to 50% will make el-message shown vertically center

### What is actually happening?

when setting el-message top to 50%, if multiple message shown same time, message will overlap.

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiA6cGxhaW49XCJ0cnVlXCIgQGNsaWNrPVwib3BlblZuXCI+Vk5vZGU8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2UoJ3RoaXMgaXMgYSBtZXNzYWdlLicpXG59XG5cbmNvbnN0IG9wZW5WbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlKHtcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnc3BhbicsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICAgIGN1c3RvbUNsYXNzOiAnY2VudGVyJ1xuICB9KVxufVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uY2VudGVyIHtcbiAgbWFyZ2luLXRvcDogNTAlO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)
Is this the effect you want?

**Comment by xwillmadeit** [comment]
It's nearly meet the requirement, but it's not perfectly vertically centered, if the content in message box has multiple lines, than the error is more obvious.

**Comment by chenxch** [comment]
Of course, I just provide a simple demo to tell you that it can be realized by customizing the class, and you need to adjust the css to solve it yourself.

**Comment by chenxch** [comment]
```css

    top: 0 !important;
    bottom: 0;
    height: fit-content;
    margin: auto;

```

**Comment by xwillmadeit** [comment]
I use this temporarily
