### ISSUE TITLE
[Component] [table-v2] 虚拟表格固定列时宽度计算有误

### ISSUE THREAD

**Issue by ouweicong** [element-plus/element-plus#13520]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.3.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtdjJcbiAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOnNvcnQtYnk9XCJzb3J0QnlcIlxuICAgIDp3aWR0aD1cIjcwMFwiXG4gICAgOmhlaWdodD1cIjQwMFwiXG4gICAgZml4ZWRcbiAgICBAY29sdW1uLXNvcnQ9XCJvblNvcnRcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFRhYmxlVjJGaXhlZERpciwgVGFibGVWMlNvcnRPcmRlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW1wb3J0IHR5cGUgeyBTb3J0QnkgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGdlbmVyYXRlQ29sdW1ucyA9IChsZW5ndGggPSAxMCwgcHJlZml4ID0gJ2NvbHVtbi0nLCBwcm9wcz86IGFueSkgPT5cbiAgQXJyYXkuZnJvbSh7IGxlbmd0aCB9KS5tYXAoKF8sIGNvbHVtbkluZGV4KSA9PiAoe1xuICAgIC4uLnByb3BzLFxuICAgIGtleTogYCR7cHJlZml4fSR7Y29sdW1uSW5kZXh9YCxcbiAgICBkYXRhS2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIHRpdGxlOiBgQ29sdW1uICR7Y29sdW1uSW5kZXh9YCxcbiAgICB3aWR0aDogMTUwLFxuICB9KSlcblxuY29uc3QgZ2VuZXJhdGVEYXRhID0gKFxuICBjb2x1bW5zOiBSZXR1cm5UeXBlPHR5cGVvZiBnZW5lcmF0ZUNvbHVtbnM+LFxuICBsZW5ndGggPSAyMDAsXG4gIHByZWZpeCA9ICdyb3ctJ1xuKSA9PlxuICBBcnJheS5mcm9tKHsgbGVuZ3RoIH0pLm1hcCgoXywgcm93SW5kZXgpID0+IHtcbiAgICByZXR1cm4gY29sdW1ucy5yZWR1Y2UoXG4gICAgICAocm93RGF0YSwgY29sdW1uLCBjb2x1bW5JbmRleCkgPT4ge1xuICAgICAgICByb3dEYXRhW2NvbHVtbi5kYXRhS2V5XSA9IGBSb3cgJHtyb3dJbmRleH0gLSBDb2wgJHtjb2x1bW5JbmRleH1gXG4gICAgICAgIHJldHVybiByb3dEYXRhXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogYCR7cHJlZml4fSR7cm93SW5kZXh9YCxcbiAgICAgICAgcGFyZW50SWQ6IG51bGwsXG4gICAgICB9XG4gICAgKVxuICB9KVxuXG5jb25zdCBjb2x1bW5zID0gZ2VuZXJhdGVDb2x1bW5zKDEwKVxubGV0IGRhdGEgPSBnZW5lcmF0ZURhdGEoY29sdW1ucywgMjAwKVxuXG5jb2x1bW5zWzBdLmZpeGVkID0gdHJ1ZVxuY29sdW1uc1sxXS5maXhlZCA9IFRhYmxlVjJGaXhlZERpci5MRUZUXG5jb2x1bW5zWzldLmZpeGVkID0gVGFibGVWMkZpeGVkRGlyLlJJR0hUXG5cbmZvciAobGV0IGkgPSAwOyBpIDwgMzsgaSsrKSBjb2x1bW5zW2ldLnNvcnRhYmxlID0gdHJ1ZVxuXG5jb25zdCBzb3J0QnkgPSByZWY8U29ydEJ5Pih7XG4gIGtleTogJ2NvbHVtbi0wJyxcbiAgb3JkZXI6IFRhYmxlVjJTb3J0T3JkZXIuQVNDLFxufSlcblxuY29uc3Qgb25Tb3J0ID0gKF9zb3J0Qnk6IFNvcnRCeSkgPT4ge1xuICBkYXRhID0gZGF0YS5yZXZlcnNlKClcbiAgc29ydEJ5LnZhbHVlID0gX3NvcnRCeVxufVxuPC9zY3JpcHQ+XG4ifQ==)

### Steps to reproduce

把滚动条拉到最右边，除了被固定的列的最后一列会有部分被隐藏，是固定列挡住了，大约是6px的大小。

### What is Expected?

固定列不会挡住除了被固定的列的最后一列

### What is actually happening?

把滚动条拉到最右边，除了被固定的列的最后一列会有部分被隐藏，是固定列挡住了，大约是6px的大小。

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/106805834/3fff1204-fd51-4669-a04e-1730c7dc92f4)

**Comment by Zhuxb-Clouds** [comment]
应该是旁边scroll-bar的宽度6px

**Comment by ouweicong** [comment]
> 应该是旁边滚动条的宽度6px

不清楚，固定列的宽度总是比占位宽度多6px，导致被内容被盖住了，这应该是通过计算出来的

**Comment by KanLai** [comment]
它这个会自动减去6像素，比如宽度设值800  ，row 总宽度就会自动减去6像素，应该是滚动条的宽度，很不合理啊。
