### ISSUE TITLE
[Style] [message-box] 消息弹出框，保存按钮样式失效

### ISSUE THREAD

**Issue by Tian-1-2** [element-plus/element-plus#13534]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chorm`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSB7IEFjdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKFxuICAgICdZb3UgaGF2ZSB1bnNhdmVkIGNoYW5nZXMsIHNhdmUgYW5kIHByb2NlZWQ/JyxcbiAgICAnQ29uZmlybScsXG4gICAge1xuICAgICAgZGlzdGluZ3Vpc2hDYW5jZWxBbmRDbG9zZTogdHJ1ZSxcbiAgICAgIGNvbmZpcm1CdXR0b25UZXh0OiAnU2F2ZScsXG4gICAgICBjYW5jZWxCdXR0b25UZXh0OiAnRGlzY2FyZCBDaGFuZ2VzJyxcbiAgICB9XG4gIClcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICB0eXBlOiAnaW5mbycsXG4gICAgICAgIG1lc3NhZ2U6ICdDaGFuZ2VzIHNhdmVkLiBQcm9jZWVkaW5nIHRvIGEgbmV3IHJvdXRlLicsXG4gICAgICB9KVxuICAgIH0pXG4gICAgLmNhdGNoKChhY3Rpb246IEFjdGlvbikgPT4ge1xuICAgICAgRWxNZXNzYWdlKHtcbiAgICAgICAgdHlwZTogJ2luZm8nLFxuICAgICAgICBtZXNzYWdlOlxuICAgICAgICAgIGFjdGlvbiA9PT0gJ2NhbmNlbCdcbiAgICAgICAgICAgID8gJ0NoYW5nZXMgZGlzY2FyZGVkLiBQcm9jZWVkaW5nIHRvIGEgbmV3IHJvdXRlLidcbiAgICAgICAgICAgIDogJ1N0YXkgaW4gdGhlIGN1cnJlbnQgcm91dGUnLFxuICAgICAgfSlcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gTWVzc2FnZSBCb3g8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击消息弹出框，鼠标放到save按钮上

### What is Expected?

save按钮能出现样式变动，和普通按钮一样

### What is actually happening?

一直为蓝灰色固定，点击其他地方，按钮才出现变化，触摸进行颜色变动

### Additional comments

消息弹出框保存按钮样式失效，而其他类似的按钮却正常，期望解决

**Comment by emojiiii** [comment]
Please refer to the [document](https://element-plus.org/zh-CN/component/message-box.html#messagebox-%E9%85%8D%E7%BD%AE%E9%A1%B9)
 `autofocus: false`
