### ISSUE TITLE
[Component] [date-picker] 通过h函数使用日期组件（ElDatePicker）双向绑定无效，onChange事件无效

### ISSUE THREAD

**Issue by Mrceel** [element-plus/element-plus#13532]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.0.1`
- Browser / OS: `Google Chrome版本 114.0.5735.198（正式版本） (x86_64) / MacBook Pro 13.4.1 (22F82)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICAvLyBwcm9wczogWydtaW5EYXRlJywgJ21heERhdGUnLCAncHJvcGVydHknXSxcbiAgICBzZXR1cChwcm9wcykge1xuICAgICAgICBjb25zdCB2ID0gcmVmKFtdKVxuICAgICAgICBjb25zdCBvbkNoYW5nZSA9ICh2YWwpPT57XG4gICAgICAgICAgICBjb25zb2xlLmxvZyh2YWwpXG4gICAgICAgICAgICAvLyB2LnZhbHVlID0gdmFsXG4gICAgICAgIH1cbiAgICAgICAgcmV0dXJuICgpID0+IHtcbiAgICAgICAgICAgIHJldHVybiBoKEVsRGF0ZVBpY2tlciwge1xuICAgICAgICAgICAgICAgICd2LW1vZGVsJzogdi52YWx1ZSxcbiAgICAgICAgICAgICAgICAvLyAnbW9kZWwtdmFsdWUnOiB2LnZhbHVlLFxuICAgICAgICAgICAgICAgIC8vIG1vZGVsVmFsdWU6IHYudmFsdWUsXG4gICAgICAgICAgICAgICAgdHlwZTogJ21vbnRocmFuZ2UnLFxuICAgICAgICAgICAgICAgIGZvcm1hdDogJ1lZWVkvTU0vREQnLFxuICAgICAgICAgICAgICAgICd2YWx1ZS1mb3JtYXQnOiAnWVlZWU1NREQnLFxuICAgICAgICAgICAgICAgICdyYW5nZS1zZXBhcmF0b3InOiAn6IezJyxcbiAgICAgICAgICAgICAgICAnc3RhcnQtcGxhY2Vob2xkZXInOiAn5byA5aeL5pel5pyfJyxcbiAgICAgICAgICAgICAgICAnZW5kLXBsYWNlaG9sZGVyJzogJ+e7k+adn+aXpeacnycsXG4gICAgICAgICAgICAgICAgJ29uVXBkYXRlOm1vZGVsVmFsdWUnOiBvbkNoYW5nZSxcbiAgICAgICAgICAgICAgICAvLyBvbkNoYW5nZVxuICAgICAgICAgICAgfSlcbiAgICAgICAgfVxuICAgIH1cbn0pXG5cbjwvc2NyaXB0PlxuXG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

加载完成后，选择日期，

### What is Expected?

组件正常显示日期

### What is actually happening?

组件无法显示任何信息

### Additional comments

_(empty)_

**Comment by wonderl17** [comment]
这样写看起来正常
[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICAvLyBwcm9wczogWydtaW5EYXRlJywgJ21heERhdGUnLCAncHJvcGVydHknXSxcbiAgICBzZXR1cChwcm9wcykge1xuICAgICAgICBjb25zdCB2ID0gcmVmKFtdKVxuICAgICAgICBjb25zdCBvbkNoYW5nZSA9ICh2YWwpPT57XG4gICAgICAgICAgICB2LnZhbHVlID0gdmFsXG4gICAgICAgIH1cbiAgICAgICAgcmV0dXJuICgpID0+IHtcbiAgICAgICAgICAgIHJldHVybiBoKEVsRGF0ZVBpY2tlciwge1xuICAgICAgICAgICAgICAgIC8vJ3YtbW9kZWwnOiB2LnZhbHVlLFxuICAgICAgICAgICAgICAgIC8vICdtb2RlbC12YWx1ZSc6IHYudmFsdWUsXG4gICAgICAgICAgICAgICAgbW9kZWxWYWx1ZTogdi52YWx1ZSxcbiAgICAgICAgICAgICAgICB0eXBlOiAnbW9udGhyYW5nZScsXG4gICAgICAgICAgICAgICAgZm9ybWF0OiAnWVlZWS9NTS9ERCcsXG4gICAgICAgICAgICAgICAgJ3ZhbHVlLWZvcm1hdCc6ICdZWVlZTU1ERCcsXG4gICAgICAgICAgICAgICAgJ3JhbmdlLXNlcGFyYXRvcic6ICfoh7MnLFxuICAgICAgICAgICAgICAgICdzdGFydC1wbGFjZWhvbGRlcic6ICflvIDlp4vml6XmnJ8nLFxuICAgICAgICAgICAgICAgICdlbmQtcGxhY2Vob2xkZXInOiAn57uT5p2f5pel5pyfJyxcbiAgICAgICAgICAgICAgICAnb25VcGRhdGU6bW9kZWxWYWx1ZSc6IG9uQ2hhbmdlLFxuICAgICAgICAgICAgfSlcbiAgICAgICAgfVxuICAgIH1cbn0pXG5cbjwvc2NyaXB0PlxuXG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by Mrceel** [comment]
<script lang="ts">
import { defineComponent, h, ref } from 'vue'
import { ElDatePicker } from 'element-plus'

export default defineComponent({
    // props: ['minDate', 'maxDate', 'property'],
    setup(props) {
        const v = ref(['20230101', '20230202'])
        const onChange = (val)=>{
            v.value = val
        }
        return () => {
            return h(ElDatePicker, {
                modelValue: v.value,
                type: 'monthrange',
                format: 'YYYY/MM/DD',
                'value-format': 'YYYYMMDD',
                'range-separator': '至',
                'start-placeholder': '开始日期',
                'end-placeholder': '结束日期',
                onChange: onChange //这样的写法确实是无效的。
            })
        }
    }
})

</script>

**Comment by Mrceel** [comment]
这样的写法确实是无效的。[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIGgsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICAvLyBwcm9wczogWydtaW5EYXRlJywgJ21heERhdGUnLCAncHJvcGVydHknXSxcbiAgICBzZXR1cChwcm9wcykge1xuICAgICAgICBjb25zdCB2ID0gcmVmKFtdKVxuICAgICAgICBjb25zdCBvbkNoYW5nZSA9ICh2YWwpPT57XG4gICAgICAgICAgICBjb25zb2xlLmxvZyh2YWwpXG4gICAgICAgIH1cbiAgICAgICAgcmV0dXJuICgpID0+IHtcbiAgICAgICAgICAgIHJldHVybiBoKEVsRGF0ZVBpY2tlciwge1xuICAgICAgICAgICAgICAgIG1vZGVsVmFsdWU6IHYudmFsdWUsXG4gICAgICAgICAgICAgICAgdHlwZTogJ21vbnRocmFuZ2UnLFxuICAgICAgICAgICAgICAgIGZvcm1hdDogJ1lZWVkvTU0vREQnLFxuICAgICAgICAgICAgICAgICd2YWx1ZS1mb3JtYXQnOiAnWVlZWU1NREQnLFxuICAgICAgICAgICAgICAgICdyYW5nZS1zZXBhcmF0b3InOiAn6IezJyxcbiAgICAgICAgICAgICAgICAnc3RhcnQtcGxhY2Vob2xkZXInOiAn5byA5aeL5pel5pyfJyxcbiAgICAgICAgICAgICAgICAnZW5kLXBsYWNlaG9sZGVyJzogJ+e7k+adn+aXpeacnycsXG4gICAgICAgICAgICAgICAgb25DaGFuZ2U6IG9uQ2hhbmdlXG4gICAgICAgICAgICB9KVxuICAgICAgICB9XG4gICAgfVxufSlcblxuPC9zY3JpcHQ+XG5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by emojiiii** [comment]
> 这样的写法确实是无效的

`onChange` 是当你的 `modelValue` 更改后才会触发的，请使用 `onUpdate:modelValue` 事件赋值后，再监听 `onChange`
