### ISSUE TITLE
[Component] [date-picker] 日期格式转换显示错误

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#13537]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.7`
- Browser / OS: ` Chrome 102.0.5005.63 / Windows10`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRpbWUgPSByZWYobmV3IERhdGUoKSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgIHYtbW9kZWw9XCJ0aW1lXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgIGZvcm1hdC12YWx1ZT1cIllZWVktTU0tREQgSEg6bW06c3NcIlxuICAgIGZvcm1hdD1cIllZWVnlubRNTeaciERE5pelIEhI5pe2bW3liIZcIlxuICAgIEBmb2N1cz1cInRpbWUgPSBuZXcgRGF0ZSgpXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1.导入el-date-picker组件
2.设置format-value="YYYY-MM-DD HH:mm:ss"
3.设置format="YYYY年MM月DD日 HH时mm分"

### What is Expected?

文本框内显示：2023年07月11日 14时47分

### What is actually happening?

文本框内显示：2023年07月11日分 日 14时47分

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/34450888/fb0ebbab-244a-4d5c-ab9f-502bc67eff53)

**Comment by yj-liuzepeng** [comment]
duplicate https://github.com/element-plus/element-plus/issues/11465

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SmallSample** [comment]
![image](https://github.com/element-plus/element-plus/assets/34450888/3bfa3b9d-4576-4dde-a674-ec50245dcf86)
其实正则表达式改成这样就可解决问题 @yj-liuzepeng

**Comment by tolking** [comment]
Fixed by #14330

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
