### ISSUE TITLE
[Bug Report] when table-column fixed, the shadow shows incorrectly

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1353]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
chrome84

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-k9586

### Steps to reproduce
Change the width of browser

### What is Expected?
There should be shown a shadow
![image](https://user-images.githubusercontent.com/38392315/105794108-4a9e0c80-5fc5-11eb-9b2d-5cc515eaa6e0.png)

The shadow should be hidden
![image](https://user-images.githubusercontent.com/38392315/105794166-6b666200-5fc5-11eb-9536-3b729be96c3d.png)

**Comment by Ryan2128** [comment]
Another issue's description:

1、when set column fixed="right" and has scorll-x, the fixed-column's boder-left is none.
2、when has selection column and fixed="right" column, the fixed column header's boder-bottom is none and the fixed column's border-left is none
