### ISSUE TITLE
[bug report] uses El select to select a data by default. After opening the drop-down list, it does not jump to the currently selected data anchor, but only displays the top data

### ISSUE THREAD

**Issue by bigfatDone** [element-plus/element-plus#1356]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
 86.0.4240.198（正式版本）谷歌

### Vue version
3.0.5

### Steps to reproduce
no

### What is Expected?
应该跳转到当前选中的数据

### What is actually happening?
没有跳转当前选中数据的锚地

**Comment by JeremyWuuuuu** [comment]
I kind of know what you actually means, but could you give us a minimal reproducible link or repo to do debugging?
