### ISSUE TITLE
[Component] [input] el-input password 不是 type 的有效值。预期值: text或textarea

### ISSUE THREAD

**Issue by li-fcb1899** [element-plus/element-plus#13589]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Edge 114.0.1823.82/Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgdHlwZT1cInBhc3N3b3JkXCIvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-input v-model="msg" type="password"/>
</template>
```

### What is Expected?

预期值：text、textarea、...

### What is actually happening?

password 不是 type 的有效值。预期值: text或textarea

### Additional comments

idea对type="password"标黄，警告：password 不是 type 的有效值。预期值: text或textarea

**Comment by li-fcb1899** [comment]
![屏幕截图 2023-07-14 002016](https://github.com/element-plus/element-plus/assets/65374839/f9159c11-02a8-455e-8f4c-a47c261104be)

**Comment by btea** [comment]
![image](https://github.com/element-plus/element-plus/assets/24516654/4d3a742d-4a55-4412-a728-2ce33f62b9ab)

My local is normal, maybe you need to provide more information about the ts version and editor.

**Comment by li-fcb1899** [comment]
IntelliJ IDEA Ultimate 2023.1.4
Typescript 5.1.6
Element Plus 2.3.7

**Comment by li-fcb1899** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/253445888-4d3a742d-4a55-4412-a728-2ce33f62b9ab.png)
> 
> My local is normal, maybe you need to provide more information about the ts version and editor.

IntelliJ IDEA Ultimate 2023.1.4
Typescript 5.1.6
