### ISSUE TITLE
[Component] [date-picker] 与 inline form 一起使用样式错乱

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#13587]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.7`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC1mb3JtIDppbmxpbmU9XCJ0cnVlXCI+XG4gICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgdHlwZT1cImRhdGV0aW1lcmFuZ2VcIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCBEYXRlXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBEYXRlXCJcbiAgICAgIDpkZWZhdWx0LXRpbWU9XCJkZWZhdWx0VGltZTJcIlxuICAgICAgOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiXG4gICAgLz5cbjwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcblxuY29uc3QgZGVmYXVsdFRpbWUxID0gbmV3IERhdGUoMjAwMCwgMSwgMSwgMTIsIDAsIDApIC8vICcxMjowMDowMCdcbmNvbnN0IGRlZmF1bHRUaW1lMjogW0RhdGUsIERhdGVdID0gW1xuICBuZXcgRGF0ZSgyMDAwLCAxLCAxLCAxMiwgMCwgMCksXG4gIG5ldyBEYXRlKDIwMDAsIDIsIDEsIDgsIDAsIDApLFxuXSAvLyAnMTI6MDA6MDAnLCAnMDg6MDA6MDAnXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uYmxvY2sge1xuICBwYWRkaW5nOiAzMHB4IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgYm9yZGVyLXJpZ2h0OiBzb2xpZCAxcHggdmFyKC0tZWwtYm9yZGVyLWNvbG9yKTtcbiAgZmxleDogMTtcbn1cbi5ibG9jazpsYXN0LWNoaWxkIHtcbiAgYm9yZGVyLXJpZ2h0OiBub25lO1xufVxuLmJsb2NrIC5kZW1vbnN0cmF0aW9uIHtcbiAgZGlzcGxheTogYmxvY2s7XG4gIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgbWFyZ2luLWJvdHRvbTogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

需要添加 :teleported="false" 属性

### What is Expected?

样式不乱

### What is actually happening?

样式错乱

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/41162158/11df9712-6258-4db9-bfcc-28abbab072bf)

**Comment by hibichann** [comment]
可能是刚刚修复过了，现在的dev分支上已经复现不了

https://github.com/element-plus/element-plus/pull/13375

**Comment by tolking** [comment]
Fixed on 2.3.8
