### ISSUE TITLE
In version 1.0.2-beta.29, the pagination style is inconsistent

### ISSUE THREAD

**Issue by Caoxiongk** [element-plus/element-plus#1358]
作者开放的element-plus网站上 也可以看到 分页附加功能中的完整功能和直接前往中 前往页数那里出现不协调 一个向上 一个向下
![image](https://user-images.githubusercontent.com/44657881/105811381-84800a80-5fe7-11eb-9321-358aa337e5a6.png)

**Comment by Ryan2128** [comment]
This version has bug, please use `1.0.2-beta.30`.

**Comment by Ryan2128** [comment]
If still has this error, please re-open this issue.

**Comment by JeremyWuuuuu** [comment]
Couldn't see your image.. please re-upload.

**Comment by Caoxiongk** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午5:41
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"来杯牛奶"<1036752557@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] In version 1.0.2-beta.29, the pagination style is inconsistent (#1358)





 
If still has this error, please re-open this issue.
