### ISSUE TITLE
[Component] [color-picker] el-color-picker  初始换 颜色选中位置不对 一直在左上角

### ISSUE THREAD

**Issue by Mrwuchuan** [element-plus/element-plus#13588]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0`
- Element Plus Version: `2.3.7`
- Browser / OS: `谷歌浏览器`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/color-picker.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)

### Steps to reproduce

直接点击示例就可以

### What is Expected?

组件初始化时小圆点展示在正确的位置

### What is actually happening?

初始换的时候小圆点展示位置一直在左上角

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed by #13516
