### ISSUE TITLE
[Component] [tab-pane] Icon is not rendering within el-tab-pane while render the el-tabs using dynamic array of object data value and using 'h' instance in Vue3 composition API

### ISSUE THREAD

**Issue by Sudharsan-SathiyaNarayanan** [element-plus/element-plus#13596]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tab-pane`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/vue)

### Steps to reproduce

Please click the below links for minimal reproduction section
Reproduction Link: https://stackblitz.com/edit/vue-oo52wq?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue

Scenario:
1. I'm try to render the dynamic tabs using Vue3 composition api and 'h' instance with array of object data value. For me, el-tabs and el-tab-pane with label are rendered successfully.
2. I additionally set slot label, and element plus icon class name for el-tab-pane component.
3. Data schema is available in the above shared link and the page name is Helloworld.vue page.
4. Actual Issue: 
   Icon not getting render within el-tab-pane.
   slot label is not working for me.

### What is Expected?

Need to render icon within el-tab-pane component.

### What is actually happening?

Icon is not render within el-tab-pane header. 
Label value only render within el-tab-pane header

### Additional comments

Note:
The above reported issue (icon, slot label for el-tab-pane) is working fine in Vue2 options API and element-ui.
We're facing the above issue while migrate from vue2 to vue3 composition api and element-ui to element plus

**Comment by chenxch** [comment]
I think we should check the documentation in detail first, not to say that the copy of vue2 can be used directly.
