### ISSUE TITLE
[Bug Report] DatePicker，The second clearing of datepicker does not trigger the change event

### ISSUE THREAD

**Issue by qiaozhu** [element-plus/element-plus#1359]
### Element Plus version
1.0.2-beta.29

### OS/Browsers version
chrome87

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/3qnnu

### Steps to reproduce
1.selected date
2.clearing date
3.selected date
4.clearing data

Pay attention to check console.log , the second time did not trigger change

### What is Expected?
trigger change

### What is actually happening?
change event not trigger

**Comment by qiaozhu** [comment]
Date and time related controls have this problem

**Comment by zazzaz** [comment]
will fix, thanks

**Comment by AndyLZC** [comment]
[Bug Report] DatePicker, the change event was  triggered twice when  clearing datepicker
