### ISSUE TITLE
How to expand multiple submenus at the same time in NavMenu？

### ISSUE THREAD

**Issue by qiaozhu** [element-plus/element-plus#1360]
“default-openeds” Only the first rendering works
“Menu Methods open”  Can only open one

what should I do？

**Comment by Liiked** [comment]
What's your business scenario? You may recursively call `open` method under your second described situation.

**Comment by qiaozhu** [comment]
Okay thank you

**Comment by JeremyWuuuuu** [comment]
Closing due to it's solved, feel free to reopen.
