### ISSUE TITLE
[i18n] [All] [plugin:vite:import-analysis] No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

### ISSUE THREAD

**Issue by hc-advokate** [element-plus/element-plus#13609]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `Chrome 112.0.5615.137/ Mac OS 13.3.1`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/chao921125/vue-vite)

### Steps to reproduce

升级："element-plus": "^2.3.8"
运行项目

### What is Expected?

正常运行

### What is actually happening?

[plugin:vite:import-analysis] No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

### Additional comments

_(empty)_

**Comment by waitingHao** [comment]
我这也出现了

**Comment by pangjianxin** [comment]
一样

**Comment by hc-advokate** [comment]
版本降级到2.3.7就好了，猜测应该是这个提交出现了问题：https://github.com/element-plus/element-plus/commit/3ab31b4d607d97355d5acf5887f37d3da0b8ca99

**Comment by DavidKFL** [comment]
我也是这个问题，但是我是2.3.3的版本呢

**Comment by achangchangchang** [comment]
我也是2.3.3

**Comment by DavidKFL** [comment]
> 我也是2.3.3
你可以试试升级下vue的版本。我刚升级vue到3.3.4，element-plus到2.3.7是可以的。

**Comment by yjw-214** [comment]
2.3.8的版本有问题  
换成2.3.7就好了

**Comment by tolking** [comment]
`lib` -> `es`

**Comment by chao921125** [comment]
2.3.7以及之前的引用方法：
import zhCN from "element-plus/lib/locale/lang/zh-cn";
import en from "element-plus/lib/locale/lang/en";
2.3.8的引用方法：
import zhCN from "element-plus/dist/locale/zh-cn.mjs";
import en from "element-plus/dist/locale/en.mjs";

**Comment by hc-advokate** [comment]
[chao921125](https://github.com/chao921125)大家看这个

**Comment by trry-github** [comment]
![image](https://github.com/element-plus/element-plus/assets/67309192/87f8374b-dfc8-413d-a2c8-a9ae38c02ea8)


精确固定element-plus 小版本，这个问题在 2.3.8 中出现

**Comment by youtiao66** [comment]
@chao921125 参考他的回答，去掉了文件后缀
```
// v2.3.8
import zhCn from "element-plus/dist/locale/zh-cn";
```

**Comment by oknixus** [comment]
你们是使用了`cnpm`来安装的吗？可以试下`npm i`，我的也是2.3.3的版本，遇到这个问题。然后查了下资料，`npm i`安装依赖后，就正常了

**Comment by ntnyq** [comment]
Use `'import zhCN from 'element-plus/es/locale/lang/zh-cn'`  with type support

**Comment by xiaotao2018** [comment]
2.3.7及之前
import zhCn from 'element-plus/lib/locale/lang/zh-cn'
import en from 'element-plus/lib/locale/lang/en'

2.3.8+
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import en from 'element-plus/es/locale/lang/en'

https://github.com/element-plus/element-plus/commit/3ab31b4d607d97355d5acf5887f37d3da0b8ca99

**Comment by TryChai** [comment]
想不懂改这玩意干嘛 升级不应该是平缓过度吗？没事做吗？搞那么多bug

**Comment by liubaicai** [comment]
> 想不懂改这玩意干嘛 升级不应该是平缓过度吗？没事做吗？搞那么多bug

附议。。很无语

**Comment by zyb1123** [comment]
运行一切正常，但是在使用vite3.2.5版本打包构建built的时候报以下错误：

Could not resolve './hooks/use-prevent-window/index.mjs' from node_modules/element-plus/es/index.mjs error during build: Error: Could not resolve './hooks/use-prevent-window/index.mjs' from node_modules/element-plus/es/index.mjs at error (file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:1858:30) at ModuleLoader.handleResolveId (file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:22156:24) at file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:22119:26
试过了很多个element-plus版本都无法解决

请求大佬帮忙看看
以下是我的依赖项：
{
"name": "admin-template-vue",
"private": true,
"version": "0.0.0",
"scripts": {
"clean": "rimraf dist node_modules/.vite",
"dev": "vite",
"build": "set NODE_OPTIONS=--max-old-space-size=8192 && vite build",
"preview": "vite preview"
},
"dependencies": {
"@excalidraw/excalidraw": "^0.17.0",
"@excalidraw/mermaid-to-excalidraw": "^1.1.2",
"@hufe921/canvas-editor": "^0.9.100",
"@hufe921/canvas-editor-plugin-docx": "^0.0.5",
"@hufe921/canvas-editor-plugin-floating-toolbar": "^0.0.4",
"@js-preview/docx": "^1.6.4",
"@vue-office/docx": "^1.6.3",
"@vueuse/core": "^8.7.5",
"@wangeditor/editor-for-vue": "^5.1.12",
"admin-template-vue": "file:",
"axios": "^0.27.2",
"crypto-js": "^4.2.0",
"docx": "^9.0.3",
"dom-to-image": "^2.6.0",
"element-plus": "^2.2.6",
"js-cookie": "^3.0.1",
"jsmind": "^0.8.6",
"jwt-decode": "^4.0.0",
"less": "^4.1.3",
"lodash": "^4.17.21",
"mammoth": "^1.8.0",
"mermaid": "^11.4.1",
"mitt": "^3.0.1",
"node-libs-browser": "^2.2.1",
"nprogress": "^0.2.0",
"pdf-lib": "^1.17.1",
"pdf-parse": "^1.1.1",
"pdfjs-dist": "^2.2.228",
"pinia": "^2.2.6",
"sass": "^1.53.0",
"swiper": "^8.3.1",
"uuid": "^11.0.3",
"vue": "^3.2.25",
"vue-clipboard3": "^2.0.0",
"vue-demi": "^0.14.10",
"vue-router": "^4.0.16"
},
"devDependencies": {
"@iconify-json/akar-icons": "^1.1.7",
"@iconify-json/ant-design": "^1.1.3",
"@iconify-json/arcticons": "^1.1.20",
"@iconify-json/bi": "^1.1.4",
"@iconify-json/bx": "^1.1.3",
"@iconify-json/bxs": "^1.1.3",
"@iconify-json/carbon": "^1.1.6",
"@iconify-json/ci": "^1.1.2",
"@iconify-json/clarity": "^1.1.4",
"@iconify-json/ep": "^1.1.6",
"@iconify-json/fluent": "^1.1.21",
"@iconify-json/icon-park-outline": "^1.1.11",
"@iconify-json/icon-park-solid": "^1.1.3",
"@iconify-json/material-symbols": "^1.1.41",
"@iconify-json/mdi": "^1.1.50",
"@iconify-json/ri": "^1.1.3",
"@iconify-json/solar": "^1.1.1",
"@vitejs/plugin-legacy": "^2.2.0",
"@vitejs/plugin-vue": "^3.1.0",
"terser": "^5.15.0",
"unplugin-auto-import": "^0.9.1",
"unplugin-icons": "^0.14.5",
"unplugin-vue-components": "^0.20.1",
"vite": "^3.2.5"
}
}
