### ISSUE TITLE
[TypeScript] [All] 无法找到模块“element-plus/dist/locale/zh-cn.mjs”的声明文件

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#13614]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/i18n.html)

### Steps to reproduce

2.3.8版本改变了原有的国际化方式，是不是忘记添加声明文件了
```
无法找到模块“element-plus/dist/locale/zh-cn.mjs”的声明文件。“D:/Web Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/element-plus@2.3.8_vue@3.3.4/node_modules/element-plus/dist/locale/zh-cn.mjs”隐式拥有 "any" 类型。
  如果“element-plus”包实际公开了此模块，请尝试添加包含 `declare module‘element-plus/dist/locale/zh-cn.mjs';` 的新声明(.d.ts)文件ts(7016)
```
### What is Expected?

内置类型，不提示此错误

### What is actually happening?

存在类型错误提示

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
ref to #13609

**Comment by WangJincheng4869** [comment]
> ref to #13609

我看这个，但不是同一个问题，引入mjs后报错。我目前是通过自己写声明文件解决的。
```
无法找到模块“element-plus/dist/locale/zh-cn.mjs”的声明文件。“D:/Web Workspace/CODE_Develop/Service_Products/BasicPaper/webCode/basic-paper-cloud-vue3/node_modules/.pnpm/element-plus@2.3.8_vue@3.3.4/node_modules/element-plus/dist/locale/zh-cn.mjs”隐式拥有 "any" 类型。
  如果“element-plus”包实际公开了此模块，请尝试添加包含 `declare module‘element-plus/dist/locale/zh-cn.mjs';` 的新声明(.d.ts)文件ts(7016)
```

**Comment by WangJincheng4869** [comment]
> ref to #13609

我在加了以下内容报错才消失

```ts
declare module 'element-plus/dist/locale/zh-cn.mjs' {
  const zhLocale: any;
  export default zhLocale;
}

declare module 'element-plus/dist/locale/en.mjs' {
  const enLocale: any;
  export default enLocale;
}

```

**Comment by chenxch** [comment]
试一下在tsconfig 文件 types中添加locale声明看看

**Comment by WangJincheng4869** [comment]
> "element-plus/lib/locale"

不好使...

**Comment by lettered** [comment]
这个问题的原因在于有位同志更改了导出引入方式，缺少了 lib 的import。但是es还可以取，你可以先试试
把 element-plus/lib ->  element-plus/es 替换用es的导出

**Comment by XiaoBaiClassmate** [comment]
> `import zhCn from 'element-plus/es/locale/lang/zh-cn'`

目前使用该老哥的方案

**Comment by achangchangchang** [comment]
把element-plus版本固定到2.3.7 不要加^

**Comment by Minori-ty** [comment]
> `import zhCn from 'element-plus/es/locale/lang/zh-cn'`

亲测可以

**Comment by 772778995** [comment]
再也不用 element-plus 了，小版本更新就报错，大大小小bug一堆，我真的服了

**Comment by WangJincheng4869** [comment]
> 再也不用 element-plus 了，小版本更新就报错，大大小小bug一堆，我真的服了

这个库版本管理上的确有问题，出现这种配置不兼容的情况最起码应该添加一个大的版本号，并在版本记录中添加升级说明。显然这个库没有做到，但也不至于不用。

**Comment by DevDengChao** [comment]
建议审查 PR 流程 🤣

**Comment by jvhuaiying** [comment]
到2024年了依然存在😂

**Comment by Minori-ty** [comment]
> 到2024年了依然存在😂

主要还是官网提供的例子有点问题，你可以替换成`import zhCn from "element-plus/es/locale/lang/zh-cn"`

**Comment by jvhuaiying** [comment]
> > 到2024年了依然存在😂
> 
> 主要还是官网提供的例子有点问题，你可以替换成`import zhCn from "element-plus/es/locale/lang/zh-cn"`

对的，感谢，主要还是官网有点坑，原本用js是没有这个问题的，但是因为看组件部分的示例都是用的ts，所以才硬着头皮上了ts，没想到一上来就遇到这个坑😆

**Comment by Jesseszhang** [comment]
升级vscode 到最新版本 ，插件用vue-office

**Comment by leafney** [comment]
劳烦开发大大们把官网中的示例代码修正一下

**Comment by jvhuaiying** [comment]
> 劳烦开发大大们把官网中的示例代码修正一下

+1

**Comment by zyb1123** [comment]
运行一切正常，但是在使用vite3.2.5版本打包构建built的时候报以下错误：

Could not resolve './hooks/use-prevent-window/index.mjs' from node_modules/element-plus/es/index.mjs error during build: Error: Could not resolve './hooks/use-prevent-window/index.mjs' from node_modules/element-plus/es/index.mjs at error (file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:1858:30) at ModuleLoader.handleResolveId (file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:22156:24) at file:///E:/AI/smart-doc-checkout/node_modules/rollup/dist/es/shared/rollup.js:22119:26
试过了很多个element-plus版本都无法解决

请求大佬帮忙看看
以下是我的依赖项：
{
"name": "admin-template-vue",
"private": true,
"version": "0.0.0",
"scripts": {
"clean": "rimraf dist node_modules/.vite",
"dev": "vite",
"build": "set NODE_OPTIONS=--max-old-space-size=8192 && vite build",
"preview": "vite preview"
},
"dependencies": {
"@excalidraw/excalidraw": "^0.17.0",
"@excalidraw/mermaid-to-excalidraw": "^1.1.2",
"@hufe921/canvas-editor": "^0.9.100",
"@hufe921/canvas-editor-plugin-docx": "^0.0.5",
"@hufe921/canvas-editor-plugin-floating-toolbar": "^0.0.4",
"@js-preview/docx": "^1.6.4",
"@vue-office/docx": "^1.6.3",
"@vueuse/core": "^8.7.5",
"@wangeditor/editor-for-vue": "^5.1.12",
"admin-template-vue": "file:",
"axios": "^0.27.2",
"crypto-js": "^4.2.0",
"docx": "^9.0.3",
"dom-to-image": "^2.6.0",
"element-plus": "^2.2.6",
"js-cookie": "^3.0.1",
"jsmind": "^0.8.6",
"jwt-decode": "^4.0.0",
"less": "^4.1.3",
"lodash": "^4.17.21",
"mammoth": "^1.8.0",
"mermaid": "^11.4.1",
"mitt": "^3.0.1",
"node-libs-browser": "^2.2.1",
"nprogress": "^0.2.0",
"pdf-lib": "^1.17.1",
"pdf-parse": "^1.1.1",
"pdfjs-dist": "^2.2.228",
"pinia": "^2.2.6",
"sass": "^1.53.0",
"swiper": "^8.3.1",
"uuid": "^11.0.3",
"vue": "^3.2.25",
"vue-clipboard3": "^2.0.0",
"vue-demi": "^0.14.10",
"vue-router": "^4.0.16"
},
"devDependencies": {
"@iconify-json/akar-icons": "^1.1.7",
"@iconify-json/ant-design": "^1.1.3",
"@iconify-json/arcticons": "^1.1.20",
"@iconify-json/bi": "^1.1.4",
"@iconify-json/bx": "^1.1.3",
"@iconify-json/bxs": "^1.1.3",
"@iconify-json/carbon": "^1.1.6",
"@iconify-json/ci": "^1.1.2",
"@iconify-json/clarity": "^1.1.4",
"@iconify-json/ep": "^1.1.6",
"@iconify-json/fluent": "^1.1.21",
"@iconify-json/icon-park-outline": "^1.1.11",
"@iconify-json/icon-park-solid": "^1.1.3",
"@iconify-json/material-symbols": "^1.1.41",
"@iconify-json/mdi": "^1.1.50",
"@iconify-json/ri": "^1.1.3",
"@iconify-json/solar": "^1.1.1",
"@vitejs/plugin-legacy": "^2.2.0",
"@vitejs/plugin-vue": "^3.1.0",
"terser": "^5.15.0",
"unplugin-auto-import": "^0.9.1",
"unplugin-icons": "^0.14.5",
"unplugin-vue-components": "^0.20.1",
"vite": "^3.2.5"
}
}

**Comment by btea** [comment]
@zyb1123 能提供一个仓库链接吗？

**Comment by zyb1123** [comment]
> [@zyb1123](https://github.com/zyb1123) 能提供一个仓库链接吗？

https://gitee.com/zheng-yanbin-12/smart-doc-checkout

**Comment by zyb1123** [comment]
> [@zyb1123](https://github.com/zyb1123) 能提供一个仓库链接吗？

麻烦大佬了
