### ISSUE TITLE
TS typings import in project components.

### ISSUE THREAD

**Issue by fabianmarz** [element-plus/element-plus#1361]
### Existing Component
Yes

### Component Name
Upload

### Description
Hello, sorry as this is not a real feature request, but I'm fairly new to TS and trying to figure out how to do proper typing in my Vue 3 components. I included the upload component and added a custom handler function.

This function accepts the `data` parameter which eslint complains as "any" type. So I wanted to define it as `data: ElUploadRequestOptions` but my IDE can't pick up the typing. I modified the `tsconfig.json` file to explicitly include the type files

```
"include": [
  "src/**/*.ts",
  "src/**/*.tsx",
  "src/**/*.vue",
  "tests/**/*.ts",
  "tests/**/*.tsx",
  "node_modules/element-plus/**/*.type.ts"
],
```

I'm now able to resolve the type and the code compiles correctly. But this also requires to add the following line to my Vue component

`import { ElUploadRequestOptions } from 'element-plus/packages/upload/src/upload.type';`

Is there a way to have the typings included implicitly instead of defining the required types in each Vue component?

**Comment by JeremyWuuuuu** [comment]
May I ask which IDE you are currently using?

**Comment by JeremyWuuuuu** [comment]
We are also exploring the best way to making typescript work. Also I'd like to know what plugin you are using right now.

**Comment by fabianmarz** [comment]
Thanks for the reply :-) As an IDE I'm using PHPStorm. Also see my config files below.

**tsconfig.json**

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ],
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "node_modules/element-plus/**/*.type.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**babel.config.js**
```
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
  ],
  plugins: [
    ['component', {
      libraryName: 'element-plus',
      styleLibraryName: 'theme-chalk',
    }],
  ],
};
```

**vue.config.js**
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = {
  configureWebpack: {
    plugins: [
      new StyleLintPlugin({
        files: ['**/*.{vue,scss,sass}'],
      }),
    ],
  },
  css: {
    loaderOptions: {
      sass: {
        prependData: `
          @import '~/node_modules/element-plus/packages/theme-chalk/src/common/var';
          @import '@/assets/scss/config.variables';
        `,
      },
    },
  },
};
```

**Comment by Ryan2128** [comment]
Can you provide a repro? Maybe a repository?

**Comment by Ryan2128** [comment]
> I'm now able to resolve the type and the code compiles correctly. But this also requires to add the following line to my Vue component
> 
> `import { ElUploadRequestOptions } from 'element-plus/packages/upload/src/upload.type';`
> 
> Is there a way to have the typings included implicitly instead of defining the required types in each Vue component?

Implicitly importing types may cause duplication of names, so the best way is to import types when using types.

If you insist on using this type globally, you can copy the type to your `shims.d.ts` file.

**Comment by JeremyWuuuuu** [comment]
Thank you for giving us these information, but we still need a minimal reproducible version in order to help you with that.

**Comment by JeremyWuuuuu** [comment]
A repo or link to online IDE will be fine. Thanks.

**Comment by fabianmarz** [comment]
Really appreciate your help guys, thank you! The repo can be found here: https://github.com/fabianmarz/vue-working-title

The type import can be found here
- https://github.com/fabianmarz/vue-working-title/blob/master/src/views/SingleList/SingleListItemDetails.vue#L75 
- https://github.com/fabianmarz/vue-working-title/blob/master/src/views/SingleList/SingleListItemDetails.vue#L111

I used the Vue CLI to bootstrap the project, so it can be run via `$ npm run serve`

In case you want to access the frontend the important route is `/login` -> Currently there is no redirect after successfully logging in, so just reload the page and a kanban board with items should show up. You can click on a single item to get to the detailview with the upload form at the bottom


PS: On the detail view I'm using the input element with type textarea which throws a JS error with some styling which cannot be applied. Not sure if this is because of beta 🤷

**Comment by JeremyWuuuuu** [comment]
We'll start investigating this issue ASAP. Will keep you notified.

**Comment by sxzz** [comment]
This issue is outdated, so I close it. If you have any questions, please create a new issue.
