### ISSUE TITLE
In version 1.0.2-beta.30, pagination styles are inconsistent

### ISSUE THREAD

**Issue by Caoxiongk** [element-plus/element-plus#1363]
在1.0.2-beta.30版本中，分页样式不一致 
一样的情况

**Comment by Caoxiongk** [comment]
![image](https://user-images.githubusercontent.com/44657881/105830152-1d228480-6000-11eb-8515-a98c8d1b02cf.png)
![image](https://user-images.githubusercontent.com/44657881/105830195-29a6dd00-6000-11eb-8210-853da36ff9b3.png)
![image](https://user-images.githubusercontent.com/44657881/105830248-3cb9ad00-6000-11eb-976c-1bb264b4794a.png)

**Comment by JeremyWuuuuu** [comment]
Seemed like something has been changed, but we didn't actually touched this component since like a month ago.

**Comment by JeremyWuuuuu** [comment]
We'll do investigation, will notify you when once we have any clue.

**Comment by Ryan2128** [comment]
The reason is that I modified the default `line-height` of the input component in #1349 to solve the wrong pop-up position of the time/date picker.

Will be fixed soon.
