### ISSUE TITLE
[Component] [dropdown] dropdown组件下拉态，在dom元素全屏状态下无法显示

### ISSUE THREAD

**Issue by liujianya371** [element-plus/element-plus#13636]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.6`
- Browser / OS: `chrome 114.0.5735.198（正式版本） (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlZn0gZnJvbSBcInZ1ZVwiXG5jb25zdCBpc0Z1bGxTY3JlZW4gPSByZWYoZmFsc2UpO1xuY29uc3QgZnVsbFNjcmVlbiA9ICgpPT57XG4gIGlmKCFpc0Z1bGxTY3JlZW4udmFsdWUpe1xuICAgIGNvbnN0IGVsID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJmdWxsXCIpXG4gICAgZWwucmVxdWVzdEZ1bGxzY3JlZW4oKTtcbiAgICBpc0Z1bGxTY3JlZW4udmFsdWUgPSB0cnVlO1xuICB9ZWxzZXtcbiAgICBkb2N1bWVudC5leGl0RnVsbHNjcmVlbigpO1xuICAgIGlzRnVsbFNjcmVlbi52YWx1ZSA9IGZhbHNlO1xuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGlkPVwiZnVsbFwiIGNsYXNzPVwicm9vdFwiPlxuICAgICA8ZWwtZHJvcGRvd24+XG4gICAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIHt7aXNGdWxsU2NyZWVuP1wi56ys5LqM5q2l5Zyo54K55oiR77yM5LiL5ouJ5YiX6KGo5rKh5LqGXCI6XCLnrKzkuIDmraXlhYjngrnmiJHvvIzkuIvmi4nmmL7npLrmraPluLhcIn19XG4gICAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXNhYmxlZD5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZnVsbFNjcmVlblwiPnt7aXNGdWxsU2NyZWVuP1wi6YCA5Ye65YWo5bGPXCI6XCLnrKzkuozmraXngrnmiJHlhajlsY9cIn19PC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSBzY29wZWQ+XG4ucm9vdHtcbndpZHRoOiAxMDAlO1xuaGVpZ2h0OiAxMDAlO1xufVxuLmVsLWRyb3Bkb3duLWxpbmsge1xuICBjdXJzb3I6IHBvaW50ZXI7XG4gIGNvbG9yOiByZWQ7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1 非全屏状态下点击下拉列表：显示正常
2 点击全屏
3 全屏状态下在点击下拉列表: 下拉无法显示

### What is Expected?

期望：全屏状态下，下拉组件正常。

### What is actually happening?

全屏状态下下拉组件显示不正常，无论设置teleported是true还是false，不起作用，下拉dom永远在body下。

### Additional comments

_(empty)_

**Comment by kaine0923** [comment]
teleported false [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlZn0gZnJvbSBcInZ1ZVwiXG5jb25zdCBpc0Z1bGxTY3JlZW4gPSByZWYoZmFsc2UpO1xuY29uc3QgZnVsbFNjcmVlbiA9ICgpPT57XG4gIGlmKCFpc0Z1bGxTY3JlZW4udmFsdWUpe1xuICAgIGNvbnN0IGVsID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJmdWxsXCIpXG4gICAgZWwucmVxdWVzdEZ1bGxzY3JlZW4oKTtcbiAgICBpc0Z1bGxTY3JlZW4udmFsdWUgPSB0cnVlO1xuICB9ZWxzZXtcbiAgICBkb2N1bWVudC5leGl0RnVsbHNjcmVlbigpO1xuICAgIGlzRnVsbFNjcmVlbi52YWx1ZSA9IGZhbHNlO1xuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGlkPVwiZnVsbFwiIGNsYXNzPVwicm9vdFwiPlxuICAgICA8ZWwtZHJvcGRvd24gOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+XG4gICAgICB7e2lzRnVsbFNjcmVlbj9cIuesrOS6jOatpeWcqOeCueaIke+8jOS4i+aLieWIl+ihqOayoeS6hlwiOlwi56ys5LiA5q2l5YWI54K55oiR77yM5LiL5ouJ5pi+56S65q2j5bi4XCJ9fVxuICAgICAgPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImZ1bGxTY3JlZW5cIj57e2lzRnVsbFNjcmVlbj9cIumAgOWHuuWFqOWxj1wiOlwi56ys5LqM5q2l54K55oiR5YWo5bGPXCJ9fTwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGUgc2NvcGVkPlxuLnJvb3R7XG53aWR0aDogMTAwJTtcbmhlaWdodDogMTAwJTtcbn1cbi5lbC1kcm9wZG93bi1saW5rIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBjb2xvcjogcmVkO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by liujianya371** [comment]
<img width="451" alt="image" src="https://github.com/element-plus/element-plus/assets/4703288/8df42d63-20f6-4896-a42a-b64995242076">

@kaine0923

**Comment by kaine0923** [comment]
> <img alt="image" width="451" src="https://user-images.githubusercontent.com/4703288/254219773-8df42d63-20f6-4896-a42a-b64995242076.png">

Can you provide minimal reproduction?

**Comment by kaine0923** [comment]
I see you need to update the Element-plus version, dropdown teleported attr supported in ver 2.2.20  #10012

**Comment by liujianya371** [comment]
好的，我刚刚也试出来了，2.2.20版本修复了这个问题。
多谢，我升级一下。
