### ISSUE TITLE
[Component] [date-picker] el-date-picker 在配置了disabledDate的情况下仍然可以通过`now`按钮选择被禁用的日期

### ISSUE THREAD

**Issue by lyric-zemin** [element-plus/element-plus#13643]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tZGF0ZXRpbWUtcGlja2VyXCI+XG4gICAgPGRpdiBjbGFzcz1cImJsb2NrXCI+XG4gICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICAgIDpkaXNhYmxlZC1kYXRlPVwiZGlzYWJsZWREYXRlXCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3QgZGF0ZSBhbmQgdGltZVwiXG4gICAgICAvPlxuICAgIDwvZGl2PlxuXG4gICAgPHA+5aSN546w5q2l6aqk77yaPC9wPlxuICAgIDxvbD5cbiAgICAgIDxsaT7pgInkuK3ml7bpl7TovpPlhaXmoYY8L2xpPlxuICAgICAgPGxpPueCueWHu25vd+aMiemSrjwvbGk+XG4gICAgICA8bGk+54K55Ye7b2vmjInpkq48L2xpPlxuICAgIDwvb2w+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7ZGF5anN9IGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbmNvbnN0IGRpc2FibGVkRGF0ZSA9IChkKSA9PiBkYXlqcyhkKS5pc0JlZm9yZShkYXlqcygpLmFkZCgxLCAnZGF5JykpXG48L3NjcmlwdD5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

打开demo

### What is Expected?

被禁用的日期不可选择

### What is actually happening?

被禁用的日期可选择

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/54665054/f00cee30-6c1c-4de3-a138-1f81fd743a13)

**Comment by matto49** [comment]
The problem seems unrelated to the now button.Click one date and click now-button it doesn't chosse the now date.I think it just the default value problem
