### ISSUE TITLE
[Bug Report] el-dialog type error for width props and the width value passed through doesn't work

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1365]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
mac

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973????

### Steps to reproduce
``` tsx
<ElDialog width={660} title="a title" />
// it will cause a type error of witdh props: Type 'number' is not assignable to type 'string | undefined'.
```

### What is Expected?
expecting width to be width?: string | number;

### What is actually happening?
-

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/105867688-54a92500-6030-11eb-9e9f-880cefd8c3ec.png)

error here

**Comment by eczn** [comment]
ooops, it doesn't work whatever value passed as width passed to ElDialog,  QAQ

**Comment by Ryan2128** [comment]
You passed a `number` for this prop, and the `width` of the dialog only accepts `string` values, as shown below:

```
<el-dialog width=“300px”></dialog>
<el-dialog width={“300px”}></dialog>
<el-dialog width={“75%”}></dialog>
<el-dialog width="75%"></dialog>
```

The suffix of the string must be one of `['px','rem','em','vw','%','vmin','vmax']`.

**Comment by eczn** [comment]
> You passed a `number` for this prop, and the `width` of the dialog only accepts `string` values, as shown below:
> 
> ```
> <el-dialog width="300px"></dialog>
> <el-dialog width={"300px"}></dialog>
> <el-dialog width={"75%"}></dialog>
> <el-dialog width="75%"></dialog>
> ```
> 
> The suffix of the string must be one of `['px','rem','em','vw','%','vmin','vmax']`.

can element-plus add a default unit for numberic string width ?

**Comment by Ryan2128** [comment]
I think it can be enhanced because the size of the drawer can pass a `number` value.
