### ISSUE TITLE
[Component] [select, option] not show properly the active items

### ISSUE THREAD

**Issue by hackpirodev** [element-plus/element-plus#13656]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `all`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/github/hackpirodev/element-plus-vite-starter/draft/vibrant-feynman?file=%2Fsrc%2FApp.vue%3A17%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clk9fzwxk000g2v6mzv0v1usr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clk9fzwxk000b2v6mgjg8yl7d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clk9fzwxk000f2v6m9wcgk6ej%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clk9fzwxk000d2v6m82ig7b6c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clk9fzwxk000b2v6mgjg8yl7d%2522%253A%257B%2522id%2522%253A%2522clk9fzwxk000b2v6mgjg8yl7d%2522%252C%2522activeTabId%2522%253A%2522clk9glq7a01212v6mjmux4anp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clk9fzwxk000a2v6mbqw1h9fr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522view%2522%253A%2522code%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522clk9g1xtx01zh2v6m6j0xr0nc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clk9glq7a01212v6mjmux4anp%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clk9fzwxk000d2v6m82ig7b6c%2522%253A%257B%2522id%2522%253A%2522clk9fzwxk000d2v6m82ig7b6c%2522%252C%2522activeTabId%2522%253A%2522clk9g0qtj01092v6minppb5fr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clk9g0qtj01092v6minppb5fr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clk9fzwxk000f2v6m9wcgk6ej%2522%253A%257B%2522id%2522%253A%2522clk9fzwxk000f2v6m9wcgk6ej%2522%252C%2522activeTabId%2522%253A%2522clk9g0oos00pe2v6mz449o40r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clk9fzwxk000e2v6mjn3yed26%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clk9fzx100015h1gbe7py8l0h%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clk9g0oos00pe2v6mz449o40r%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
using this code we not see the active items

```vue
<template>
  <el-config-provider namespace="ep">
    <h1>selecteds not active</h1>
    <div style="display: flex; width: 100%; justify-content: space-around">
      <div>
        <h3>selected items</h3>
        <pre>{{ selecteds }}</pre>
      </div>
      <div>
        <h3>options</h3>
        <pre>{{ options }}</pre>
      </div>
    </div>
    <el-select v-model="selecteds" multiple placeholder="Select">
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      />
    </el-select>
  </el-config-provider>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const selecteds = ref([
  {
    value: "Option1",
    label: "Option1",
  },
]);

const options = [
  {
    value: "Option1",
    label: "Option1",
  },
  {
    value: "Option2",
    label: "Option2",
  },
  {
    value: "Option3",
    label: "Option3",
  },
  {
    value: "Option4",
    label: "Option4",
  },
  {
    value: "Option5",
    label: "Option5",
  },
];
</script>
```

![image](https://github.com/element-plus/element-plus/assets/68652588/69c680dc-aaba-4c88-94fc-6a0e9b5b8860)

### What is Expected?

when I open the select I expect to see the active item already selected

### What is actually happening?

I see on the select the active element and in my state (ref) properly but when I open the select it seems no items are selected

### Additional comments

_(empty)_

**Comment by dzye** [comment]
```
const selecteds = ref([ "Option1"]);
```
or
```
<el-select v-model="selecteds" multiple placeholder="Select">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item"
    />
  </el-select>
```

**Comment by hackpirodev** [comment]
my bad, thanks a lot! 🙏🏾
