### ISSUE TITLE
[Bug Report] el-date-picker shortcuts onClick

### ISSUE THREAD

**Issue by xiaolannuoyi** [element-plus/element-plus#1367]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
mac15/chrome 版本 88.0.4324.96（正式版本） (x86_64)

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xiaolannuoyi/pen/ZEpgMKy?editors=1010

### Steps to reproduce
点击快捷选项。报错。e.toDate is not a function

### What is Expected?
点击快捷选项。更新时间。

### What is actually happening?
报错 
e.toDate is not a function

**Comment by 1063428973** [comment]
Check the configuration
https://element-plus.org/#/en-US/component/date-picker
![image](https://user-images.githubusercontent.com/32738523/105957129-b9f22a00-60b3-11eb-87a1-cbf5cbe876cd.png)

**Comment by xiaolannuoyi** [comment]
> Check the configuration
> https://element-plus.org/#/en-US/component/date-picker
> ![image](https://user-images.githubusercontent.com/32738523/105957129-b9f22a00-60b3-11eb-87a1-cbf5cbe876cd.png)

你好，谢谢你的回复。
shortcuts中的value只能是固定的值，我想用onClick去更新。
问题链接已更新https://codepen.io/xiaolannuoyi/pen/ZEpgMKy?editors=1010

![image](https://user-images.githubusercontent.com/21079721/105958356-77315180-60b5-11eb-9d3e-2ba9b121c975.png)

但是这么用，会报错，且不会更新时间
![image](https://user-images.githubusercontent.com/21079721/105958429-8f08d580-60b5-11eb-8a76-682b3885941d.png)

**Comment by zazzaz** [comment]
You should pass a `Date` according to the doc 
```
object[{ text: string, value: Date }]
```

**Comment by xiaolannuoyi** [comment]
> You should pass a `Date` according to the doc
> 
> ```
> object[{ text: string, value: Date }]
> ```

why？
https://element-plus.org/#/en-US/component/datetime-picker

![image](https://user-images.githubusercontent.com/21079721/105960366-15261b80-60b8-11eb-8e6c-9af6b3ba916f.png)

**Comment by zazzaz** [comment]
This should be a doc error, you can check this at the moment https://element-plus.org/#/en-US/component/date-picker

**Comment by xiaolannuoyi** [comment]
> This should be a doc error, you can check this at the moment https://element-plus.org/#/en-US/component/date-picker
> 
> fixed in #1369

我不认为这是文档问题。
源码位置 https://github.com/element-plus/element-plus/blob/dev/packages/time-picker/src/common/picker.vue 

![image](https://user-images.githubusercontent.com/21079721/105963793-63d5b480-60bc-11eb-8db3-064546f3f059.png)

shortcuts中的onClick 会触发 这个方法。报错也是这个 toDate .

将_.toDate 换成 dayjs(_) 会好使。

**Comment by zazzaz** [comment]
Please check the demo code to set the correct config

<img width="579" alt="image" src="https://user-images.githubusercontent.com/10731096/105968547-2c6a0680-60c2-11eb-9492-bc87a8af8fb3.png">

**Comment by xiaolannuoyi** [comment]
> Please check the demo code to set the correct config
> 
> <img alt="image" width="579" src="https://user-images.githubusercontent.com/10731096/105968547-2c6a0680-60c2-11eb-9492-bc87a8af8fb3.png">

我知道你说的是` object[{ text: string, value: Date }]`，但是这个value是 `(()=>{})()`,只执行一次。
假如页面停留的时间有些久了  我此时点击 想要的是最新的5分钟，或者点击进行一些操作。
所以我想用 onClick 来进行一些操作。

onClick 是没有问题的，`picker.emit('pick',[start,end] )`有问题，它触发源码中的` onPick` 方法。只是方法中的 `toDate()` 是错误的， 将`_.toDate` 换成 `dayjs(_)` 会好使。

**Comment by JeremyWuuuuu** [comment]
Can you just update `shortcut` instead?

**Comment by zazzaz** [comment]
if you want to use `onClick` the hidden method, the value you passed in should be a Day.js object.

**Comment by xiaolannuoyi** [comment]
奥奥好的，非常感谢。

我应该这样使用，并安装dayjs
`
import dayjs from 'dayjs'

shortcuts: [{
         text: '最近5分钟',
         onClick(picker) {
            console.warn('picker', picker)
             let end = +new Date()
             let start = end - 1000 * 60 * 5
            picker.emit('pick',[dayjs(start),dayjs(end)])
           }
        }],`

我觉的可以改下 使它变得更易用。谢谢

**Comment by zazzaz** [comment]
There's no need to install Day.js your self cause it's a dev dependency of element plus

**Comment by xiaolannuoyi** [comment]
奥奥，好的，谢谢。

**Comment by JeremyWuuuuu** [comment]
Since this is not a public API, we do not recommend users to use it, use it at your own cost.

**Comment by zazzaz** [comment]
solved and close
