### ISSUE TITLE
[Component] el-popover trigger 拦截了空格和回车事件

### ISSUE THREAD

**Issue by ly-chn** [element-plus/element-plus#13708]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `chrome 115`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-popper`
- `el-popconfirm`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuY29uc3QgY291bnQgPSByZWY8bnVtYmVyPigwKVxuY29uc3QgZW50ZXJDb3VudCA9IHJlZjxudW1iZXI+KDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIiB3aWR0aD1cIjIwMFwiPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgIOS9oOWlvVxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNvdW50KytcIiAgQGtleXVwLmVudGVyPVwiZW50ZXJDb3VudCsrXCI+5omT5byAcG9wb3ZlcjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjb3VudCsrXCIgIEBrZXl1cC5lbnRlcj1cImVudGVyQ291bnQrK1wiPuaZrumAmuaMiemSruinpuWPkeWbnui9pjwvZWwtYnV0dG9uPlxuICA8ZGl2PuaMiemSrmNsaWNr5qyh5pWwOiB7e2NvdW50fX08L2Rpdj5cbiAgPGRpdj7lm57ovaZlbnRlcuasoeaVsDoge3tlbnRlckNvdW50fX08L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

使用键盘上的TAB选中按钮, 敲下回车触发回车事件, 此时按钮无法正常触发click事件

### What is Expected?

回车和空格能够正常触发click事件

### What is actually happening?

当鼠标点击时可以触发click, 回车和空格不行

### Additional comments

_(empty)_

**Comment by OlyLis1005** [comment]
我也遇到了这个问题，在使用popover+input组合时候，内部input无法正常输入空格键
