### ISSUE TITLE
[Component] [switch] Slider 滑块的这两个属性是干嘛用的 ：range-start-label  ， range-end-label

### ISSUE THREAD

**Issue by l406054531** [element-plus/element-plus#13707]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.3.8`
- Browser / OS: `win10；最新谷歌`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cInNsaWRlci1kZW1vLWJsb2NrXCI+XG4gICAgPGVsLXNsaWRlciB2LW1vZGVsPVwidmFsdWVcIiByYW5nZSBzaG93LXN0b3BzIDptaW49XCIxOTQ5XCIgOm1heD1cIjIwMjNcIiByYW5nZS1zdGFydC1sYWJlbD1cIjEyM1wiIHJhbmdlLWVuZC1sYWJlbD1cIjMyMVwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLnNsaWRlci1kZW1vLWJsb2NrIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbn1cbi5zbGlkZXItZGVtby1ibG9jayAuZWwtc2xpZGVyIHtcbiAgbWFyZ2luLXRvcDogMDtcbiAgbWFyZ2luLWxlZnQ6IDEycHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

主要不知道这两个属性在哪生效了   range-start-label="123" range-end-label="321"

### What is Expected?

在选择的范围开始点和结束点下面显示文本，但我不知道这两个属性是干嘛的，也不见在哪生效

### What is actually happening?

看不到结果

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
range-start-label和range-end-label，对应的就是标签的aria-label属性，关于这个属性 [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)

> aria-label是HTML中的一个属性，用于提供有关元素的文本描述，以便辅助技术可以理解和呈现该元素。"aria"表示"可访问性富互联网应用程序"（Accessible Rich Internet Applications），它是一组规范，旨在使Web内容对于残障人士更易于访问。
> 
> aria-label属性用于指定一个可读文本标签，来描述与该属性关联的元素。这对于那些没有文本内容或者文本内容不足以描述其用途的元素特别有用。屏幕阅读器等辅助技术会读取aria-label的值，以帮助用户了解元素的功能或用途。


<img width="962" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/d94c910a-f463-43ad-8550-40f0f033d30f">

**Comment by emojiiii** [comment]
请看文档 https://element-plus.org/zh-CN/component/slider.html#%E5%B1%9E%E6%80%A7
