### ISSUE TITLE
[Component] [select] select选择器组件内创建新的选项这个示例default-first-option属性不生效

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#13706]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `版本 114.0.5735.199（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E9%80%89%E9%A1%B9)

### Steps to reproduce

示例里说：  **default-first-option** 属性， 在该属性为 true 的情况下，按下回车就可以选中当前选项列表中的第一个选项，无需使用鼠标或键盘方向键进行定位。
然而实际按下回车键后并未生效

### What is Expected?

按下回车键应选中第一个选项

### What is actually happening?

按下回车键后并未生效

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
试了谷歌 115.0.5790.98（正式版本） 和火狐 115.0.2（64位）都是生效的，并没有不生效 🤔️

**Comment by kooriookami** [comment]
现在的版本还有这个问题吗

**Comment by PeyFon** [comment]
> 现在的版本还有这个问题吗

没了，我关掉
