### ISSUE TITLE
[Component] [table] 表格设置斑马纹的背景颜色不生效

### ISSUE THREAD

**Issue by githubzml** [element-plus/element-plus#13716]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `114.0.5735.248 /  Mac OS 13.4`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCfmtYvor5XnlKjkvoshJylcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wM1wiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMlwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wNFwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHJpcGUgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cblxuXG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtdGFibGVfX3Jvdy0tc3RyaXBlZCB7XG4gIGJhY2tncm91bmQtY29sb3I6IGFxdWEgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-table :data="tableData" stripe style="width: 100%">
    <el-table-column prop="date" label="Date" width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </el-table>
</template>

<script lang="ts" setup>
const tableData = [
  {
    date: "2016-05-03",
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles",
  },
  {
    date: "2016-05-02",
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles",
  },
  {
    date: "2016-05-04",
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles",
  },
  {
    date: "2016-05-01",
    name: "Tom",
    address: "No. 189, Grove St, Los Angeles",
  },
];
</script>
<style lang="scss">
.el-table__row--striped {
  background-color: aqua !important;
}
</style>

```

### What is Expected?

表格设置斑马纹的背景颜色生效

### What is actually happening?

表格设置斑马纹的背景颜色不生效

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
Do you mean this? [link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCfmtYvor5XnlKjkvoshJylcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wM1wiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMlwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wNFwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHJpcGUgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cblxuXG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtdGFibGVfX3Jvdy0tc3RyaXBlZCA+IC5lbC10YWJsZV9fY2VsbCB7XG4gIGJhY2tncm91bmQtY29sb3I6IGFxdWEgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by githubzml** [comment]
Yeah, 

but if i wont set `all row` color , 

like this  `background-color: linear-gradient(90deg, rgba(23, 50, 81, 1) 0%, rgba(59, 190, 255, 0.02) 100%) !important;` 

`all row` yes, from left to right , and what should i do ???

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCfmtYvor5XnlKjkvoshJylcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wM1wiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMlwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wNFwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHJpcGUgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cblxuXG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtdGFibGVfX3Jvdy0tc3RyaXBlZCB7XG4gIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCg5MGRlZywgcmdiYSgyMywgNTAsIDgxLCAxKSAwJSwgcmdiYSg1OSwgMTkwLCAyNTUsIDAuMDIpIDEwMCUpO1xuICAtLWVsLWZpbGwtY29sb3ItbGlnaHRlcjogdHJhbnNwYXJlbnQ7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

You see if this meets your expectations.

**Comment by githubzml** [comment]
> [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCfmtYvor5XnlKjkvoshJylcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wM1wiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMlwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wNFwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHJpcGUgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cblxuXG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtdGFibGVfX3Jvdy0tc3RyaXBlZCB7XG4gIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCg5MGRlZywgcmdiYSgyMywgNTAsIDgxLCAxKSAwJSwgcmdiYSg1OSwgMTkwLCAyNTUsIDAuMDIpIDEwMCUpO1xuICAtLWVsLWZpbGwtY29sb3ItbGlnaHRlcjogdHJhbnNwYXJlbnQ7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)
> 
> You see if this meets your expectations.

Yes , thank you so much haha~
