### ISSUE TITLE
[Bug Report] element-variables.scss doesn't work when importing ElMessageBox

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1371]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
mac

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973????

### Steps to reproduce
use element-variables.scss:

``` scss
/* theme color */
$--color-primary: #07C160;

/* icon font path, required */
$--font-path: '~element-plus/lib/theme-chalk/fonts';

@import "~element-plus/packages/theme-chalk/src/index";
```

and it works, but when i write `import { ElMessageBox } from 'element-plus'` it return back to default theme css style.

### What is Expected?
resolve style conflct of importing ElMessageBox

### What is actually happening?
-

**Comment by eczn** [comment]
Normal Case: 
![image](https://user-images.githubusercontent.com/13131724/105975560-0cd6dc00-60ca-11eb-815e-76978735d559.png)


---- 
When Importing ElMessageBox:
![image](https://user-images.githubusercontent.com/13131724/105975596-195b3480-60ca-11eb-9819-51bb27d33d08.png)

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/105979212-5b867500-60ce-11eb-9517-5b0f47997ac8.png)

el-button's styles found in el-message-box

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/105998047-37835d80-60e7-11eb-9315-54ab26640f08.png)

this problem disapeared after removing babel component plugin.

**Comment by JeremyWuuuuu** [comment]
That's because the loader requires the actual component related css for you. So the variable overriding was overrode again by css.

**Comment by JeremyWuuuuu** [comment]
In your case, you want to use customized theme with the component loader seems like possible, based on https://github.com/ant-design/babel-plugin-import#options documentation, you can mark the field by `"style": true` to get the source files. Would you like to try that out?

**Comment by JeremyWuuuuu** [comment]
Please refer to this link: https://github.com/element-plus/element-plus/issues/1392#issuecomment-770713761
And you will also need to modify the `babel.config.js` at `customStyleName` part, with the return filename `css` replaced to `scss`, then you can resolve the confliction.
