### ISSUE TITLE
[Component] [dialog] dialog组件设置draggable可拖拽偶尔拖到屏幕顶部下不来

### ISSUE THREAD

**Issue by xy1327462182** [element-plus/element-plus#13724]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Link](http://case-erp-p003.ponlay.com/admin)

### Steps to reproduce

本系统属于测试环境，可正常测试使用。账号是:admin密码是:admin123。复现步骤：进入【系统管理】【角色管理】点击【配置菜单】按钮，如果将dialog里的tree都展开，高度被撑开到遮罩层出现滚动条时，拖拽dialog组件会把顶部拖出到顶部可视口外，并且回不来

### What is Expected?

dialog无法被拖到可视口外

### What is actually happening?

dialog被拖到可视口外后且无法拖回

### Additional comments

_(empty)_

**Comment by jokerAAA** [comment]
给 dialog 内容区域加个 max-height 和 overflow，避免超出屏幕高度

**Comment by flyher** [comment]
@jokerAAA 
看起来目前只能限制高度缓解一下了。

看起来当内容过长且设置了允许draggable时，无论是否允许 overflow，只要点一下就会被自动跳到屏幕顶部下不来。
