### ISSUE TITLE
[Style] [All] After modifying the namespace, use render, still the default class name(改了命名空间 用render渲染 类名还是默认的 )

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#13748]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `Chrome 115.0.5790.99 `
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/vela666/test)

### Steps to reproduce

```vue
<template>
  <el-button>Not render.</el-button>
  <div>Use Render</div>
  <Test>
    <el-button class="21312">Test</el-button>
    <el-input v-model="input" placeholder="Please input"/>
    <el-radio-group v-model="radio1" class="ml-4">
      <el-radio label="1" size="large">Option 1</el-radio>
      <el-radio label="2" size="large">Option 2</el-radio>
    </el-radio-group>
  </Test>
</template>

<script setup>
import Test from './test.vue'

const input = null
const radio1 = null
</script>
<style lang="scss">
 @use "element-plus/theme-chalk/src/index.scss" as *;
</style>
```

```vue
<template>
  <div id="boxCls" ref="targetRef"></div>
</template>

<script setup>
import {h, render, ref, onMounted, useSlots} from 'vue'

const slots = useSlots()
const targetRef = ref(null)
const initLayout = () => {
  const itemContentVNode = h(
      'div',
      {},
      // 插槽
      slots,
  )
  // Render the vue node into the item element
  render(itemContentVNode, targetRef.value)
}
onMounted(() => {
  initLayout()
})

</script>
```

### What is Expected?

Display the correct class name and style

### What is actually happening?

Both the class name and the style are wrong

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[docs](https://element-plus.org/zh-CN/guide/namespace.html#%E8%AE%BE%E7%BD%AE-elconfigprovider)
Please consult the documentation and follow the above steps to implement.

**Comment by gongxi0307** [comment]
> [docs](https://element-plus.org/zh-CN/guide/namespace.html#%E8%AE%BE%E7%BD%AE-elconfigprovider) Please consult the documentation and follow the above steps to implement.

这个什么时候可以修复下的
