### ISSUE TITLE
[Component] [input-number] el-input-number组件最小值设为0时不生效

### ISSUE THREAD

**Issue by Grnetsky** [element-plus/element-plus#13741]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbixyZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmxldCBtID0gcmVhY3RpdmUoe1xuICBhOjEyM1xufSlcbmxldCBmb3JtTGlzdCA9IHJlYWN0aXZlKFtcbiAge3RpdGxlOlwi5rWL6K+VXCIsXG4gIGNoaWxkcmVuOltcbiAgICB7XG4gICAgdGl0bGU6XCLmtYvor5XkuIBcIixcbiAgICB0eXBlOlwibnVtYmVyXCIsXG4gICAgcHJvcDpcImFcIixcbiAgICBiaW5kUHJvcDptLFxuICAgIG9wdGlvbjp7XG4gICAgICBwbGFjZWhvbGRlcjpcIuacgOWwj+WAvOS4ujBcIixcbiAgICAgIG1heDoxMCxcbiAgICAgIG1pbjowXG4gICAgfSxcbiAgICBmdW5jKCl7XG4gICAgY29uc29sZS5sb2coNjY2KX1cbiAgICB9XG4gIF19XG5dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlPlxuICAgIDxlbC1jb2xsYXBzZS1pdGVtICB2LWZvcj1cIml0ZW0gaW4gZm9ybUxpc3RcIiA6dGl0bGU9XCJpdGVtLnRpdGxlXCI+XG4gICAgICA8ZWwtZm9ybSBAc3VibWl0PVwiKGUpPT5lLnByZXZlbnREZWZhdWx0KClcIj5cbiAgICAgICAgPGVsLWZvcm0taXRlbSB2LWZvcj1cImkgaW4gaXRlbS5jaGlsZHJlblwiIDpsYWJlbD1cImkudGl0bGVcIj5cbiAgICAgICAgICB7e3R5cGVvZiBpLm9wdGlvbj8ubWluIH19e3tpLm9wdGlvbj8ubWlufX1cblxuICAgICAgICAgIDwhLS0gICAgICAgICAg6L6T5YWl5qGGLS0+XG4gICAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpLmJpbmRQcm9wW2kucHJvcF1cIiA6cGxhY2Vob2xkZXI9XCJpLm9wdGlvbj8ucGxhY2Vob2xkZXIgfHwgJ+ivt+i+k+WFpSdcIiB2LWlmPVwiaS50eXBlPT09J2lucHV0J1wiIEBbaS5ldmVudF09XCJpLmZ1bmNcIiA6dHlwZT1cImkub3B0aW9uPy50eXBlfHwndGV4dCdcIi8+XG48IS0tICAgICAgICAgIOaWh+S7tuahhi0tPlxuICAgICAgICAgICAgPGVsLWJ1dHRvbiB2LWVsc2UtaWY9XCJpLnR5cGU9PT0nZmlsZSdcIj48bGFiZWwgZm9yPVwiaW5wdXRcIiA+XG4gICAgICAgICAgICAgIDxpbnB1dCBpZD1cImlucHV0XCIgc3R5bGU9XCJkaXNwbGF5OiBub25lXCIgdHlwZT1cImZpbGVcIiA6YWNjZXB0PVwiaS5vcHRpb24/LmFjY2VwdCB8fCAnKi8qJ1wiIEBbaS5ldmVudF09XCJpLmZ1bmNcIiA+XG4gICAgICAgICAgICAgICAg6YCJ5oup5paH5Lu2XG4gICAgICAgICAgICAgIDwvbGFiZWw+XG4gICAgICAgICAgICA8L2VsLWJ1dHRvbj5cbjwhLS0gICAgICAgICAg5pWw5a2X5qGGLS0+XG4gICAgICAgICAgPGVsLWlucHV0LW51bWJlciA6cGxhY2Vob2xkZXI9XCJpLm9wdGlvbj8ucGxhY2Vob2xkZXIgfHwgJ+ivt+i+k+WFpSdcIiA6c3RlcD1cImkub3B0aW9uPy5zdGVwIHx8IDFcIiB2LW1vZGVsPVwiaS5iaW5kUHJvcFtpLnByb3BdXCIgOm1pbj1cImkub3B0aW9uPy5taW4gfHwgLUluZmluaXR5XCIgOm1heD1cImkub3B0aW9uPy5tYXggfHwgSW5maW5pdHlcIiBAW2kuZXZlbnRdPVwiaS5mdW5jXCIgdi1lbHNlLWlmPVwiaS50eXBlPT09J251bWJlcidcIi8+XG48IS0tICAgICAgICAgIOmAieaLqeahhi0tPlxuICAgICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImkuYmluZFByb3BbaS5wcm9wXVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgdi1lbHNlLWlmPVwiaS50eXBlPT09J3NlbGVjdCdcIj5cbiAgICAgICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gaS5vcHRpb25cIlxuICAgICAgICAgICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICAgICAgICA6ZGlzYWJsZWQ9XCJpdGVtLmRpc2FibGVkXCJcbiAgICAgICAgICAgIC8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG5cbjwhLS0gICAgICAgICAg5Y+W6Imy5ZmoLS0+XG4gICAgICAgICAgPGVsLWNvbG9yLXBpY2tlciB2LW1vZGVsPVwiaS5iaW5kUHJvcFtpLnByb3BdXCIgc2hvdy1hbHBoYSB2LWVsc2UtaWY9XCJpLnR5cGUgPT09ICdjb2xvcidcIiBAW2kuZXZlbnRdPVwiaS5mdW5jXCIvPlxuPCEtLSAgICAgICAgICDlvIDlhbMtLT5cbiAgICAgICAgICA8ZWwtc3dpdGNoIHYtbW9kZWw9XCJpLmJpbmRQcm9wW2kucHJvcF1cIiB2LWVsc2UtaWY9XCJpLnR5cGU9PT0nc3dpdGNoJ1wiIEBbaS5ldmVudF09XCJpLmZ1bmNcIi8+XG5cbjwhLS0gICAgICAgICAg5oyJ6ZKuLS0+XG4gICAgICAgICAgPGVsLWJ1dHRvbiA6dHlwZT1cImkub3B0aW9uLnR5cGVcIiB2LWVsc2UtaWY9XCJpLnR5cGUgPT09ICdidXR0b24nXCIgQFtpLmV2ZW50XT1cImkuZnVuY1wiIDpzdHlsZT1cImkubWlkZGxlPyd3aWR0aDoxMDAlO21hcmdpbjogYXV0bzsnOicnXCI+e3tpLm9wdGlvbi50aXRsZX19PC9lbC1idXR0b24+XG5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICA8L2VsLWZvcm0+XG5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

通过循环遍历渲染表单列表，传值设置el-input-number的min值为0时，无效，但是max属性有效

### What is Expected?

最小值应该为0

### What is actually happening?

无效

### Additional comments

_(empty)_

**Comment by jokerAAA** [comment]
代码里的 min 是 i.option?.min || -Infinity，这个表达式的值是 -Infinity，所以无效，可以考虑换一种写法:
![image](https://github.com/element-plus/element-plus/assets/23433168/dba849b8-0a13-4dfc-b5a7-1aa5af2c5ee4)

**Comment by Grnetsky** [comment]
恍然大悟，thanks

**Comment by Grnetsky** [comment]
> 代码里的 min 是 i.option?.min || -Infinity，这个表达式的值为 -Infinity，所以无效，可以考虑换一种写法： ![图像](https://user-images.githubusercontent.com/23433168/256431616-dba849b8-0a13-4dfc-b5a7-1aa5af2c5ee4.png)

恍然大悟，谢谢
