### ISSUE TITLE
[Bug Report] ElUpload picture-card animates incorrectly when remove image

### ISSUE THREAD

**Issue by xyorz** [element-plus/element-plus#1376]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
Chrome 88.0.4324.104

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xyorz/pen/OJbLjLd?editors=1111

### Steps to reproduce
Remove the first image

### What is Expected?
The first image removed with animation

### What is actually happening?
The first image was removed, however the final image animated.

**Comment by Ryan2128** [comment]
Are you interested in fixing it? If not, I will investigate it?

**Comment by xyorz** [comment]
Sure, I'll try to fix it.
