### ISSUE TITLE
[Component] [date-picker] pnpm + unplugin-vue-components 设置 el-date-picker日期组件 width:100% 无效

### ISSUE THREAD

**Issue by tsai996** [element-plus/element-plus#13772]
![微信图片_20230730125628](https://github.com/element-plus/element-plus/assets/62540486/9f7cb39c-c35b-4134-b4ef-c74a8fd2aac6)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/tsai996/element-plus-vite-starter)

### Steps to reproduce

这个问题只会出现在 pnpm + unplugin-vue-components
.ep-date-editor类的display:inline-block覆盖了.ep-input的display:inline-flex导致的

### What is Expected?

期望能成功设置el-date-picker 100%宽度

### What is actually happening?

无法设置el-date-picker 100%宽度

### Additional comments

必须使用 pnpm 才会出现这个问题

![微信图片_20230730125628](https://github.com/element-plus/element-plus/assets/62540486/764289cb-9d60-470f-ae01-a3f547495b5a)

**Comment by chenxch** [comment]
Fixed #12897,  in version  2.3.7
