### ISSUE TITLE
[Component] [avatar] Avatar jpg图片 fit属性失效

### ISSUE THREAD

**Issue by Wgqtion** [element-plus/element-plus#13827]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `Microsoft Edge版本 115.0.1901.188 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-avatar`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/avatar.html#%E9%80%82%E5%BA%94%E5%AE%B9%E5%99%A8)

### Steps to reproduce

把图片替换成jpg格式https://yibanoss.oss-cn-shanghai.aliyuncs.com/user/435/166355466399067zx7o.jpg，fit属性是无效的

### What is Expected?

能够时间图片自适应裁剪缩放

### What is actually happening?

fit属性是无效的

### Additional comments

_(empty)_
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHVybCA9IHJlZignaHR0cHM6Ly95aWJhbm9zcy5vc3MtY24tc2hhbmdoYWkuYWxpeXVuY3MuY29tL3VzZXIvNDM1LzE2NjM1NTQ2NjM5OTA2N3p4N28uanBnJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1hdmF0YXIgc2hhcGU9XCJzcXVhcmVcIiA6c2l6ZT1cIjEwMFwiIGZpdD1cImNvdmVyXCIgOnNyYz1cInVybFwiIC8+XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/310019cc-71c4-4137-8336-136fd120a946)
cc @YunYouJun Is it possible to directly write `width: 100%;` instead of `max-width: 100%;`

**Comment by yj-liuzepeng** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/257714043-310019cc-71c4-4137-8336-136fd120a946.png) cc @YunYouJun Is it possible to directly write `width: 100%;` instead of `max-width: 100%;`

The `max-width: 100%` property is set in `docs/.vitepress/vitepress/styles/base.scss`, so it will take effect in the examples. However, the avatar component does not have a `width` set. @chenxch
