### ISSUE TITLE
[Component] [avatar] Avatar jpg图片 fit属性失效

### ISSUE THREAD

**Issue by Wgqtion** [element-plus/element-plus#13826]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `Microsoft Edge版本 115.0.1901.188 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-avatar`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/avatar.html#%E9%80%82%E5%BA%94%E5%AE%B9%E5%99%A8)

### Steps to reproduce

把图片替换成jpg格式https://yibanoss.oss-cn-shanghai.aliyuncs.com/user/435/166355466399067zx7o.jpg，fit属性是无效的

### What is Expected?

能够时间图片自适应裁剪缩放

### What is actually happening?

fit属性是无效的

### Additional comments

_(empty)_

![1690950740563](https://github.com/element-plus/element-plus/assets/23358740/05b3794b-3622-48b1-962d-db4a9d73a29a)

**Comment by chenxch** [comment]
@Wgqtion Please do not submit the same question repeatedly.
