### ISSUE TITLE
[TypeScript] [tree] element tree 中icon属性类型sting 和component 如何正确使用

### ISSUE THREAD

**Issue by Pancake-Q** [element-plus/element-plus#13834]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBudW1iZXJcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxubGV0IGlkID0gMTAwMFxuXG5jb25zdCBhcHBlbmQgPSAoZGF0YTogVHJlZSkgPT4ge1xuICBjb25zdCBuZXdDaGlsZCA9IHsgaWQ6IGlkKyssIGxhYmVsOiAndGVzdHRlc3QnLCBjaGlsZHJlbjogW10gfVxuICBpZiAoIWRhdGEuY2hpbGRyZW4pIHtcbiAgICBkYXRhLmNoaWxkcmVuID0gW11cbiAgfVxuICBkYXRhLmNoaWxkcmVuLnB1c2gobmV3Q2hpbGQpXG4gIGRhdGFTb3VyY2UudmFsdWUgPSBbLi4uZGF0YVNvdXJjZS52YWx1ZV1cbn1cblxuY29uc3QgcmVtb3ZlID0gKG5vZGU6IE5vZGUsIGRhdGE6IFRyZWUpID0+IHtcbiAgY29uc3QgcGFyZW50ID0gbm9kZS5wYXJlbnRcbiAgY29uc3QgY2hpbGRyZW46IFRyZWVbXSA9IHBhcmVudC5kYXRhLmNoaWxkcmVuIHx8IHBhcmVudC5kYXRhXG4gIGNvbnN0IGluZGV4ID0gY2hpbGRyZW4uZmluZEluZGV4KChkKSA9PiBkLmlkID09PSBkYXRhLmlkKVxuICBjaGlsZHJlbi5zcGxpY2UoaW5kZXgsIDEpXG4gIGRhdGFTb3VyY2UudmFsdWUgPSBbLi4uZGF0YVNvdXJjZS52YWx1ZV1cbn1cbmNvbnN0IGljb249cmVmKCdkaXYnKVxuY29uc3QgZGF0YVNvdXJjZSA9IHJlZjxUcmVlW10+KFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA0LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA5LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDUsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogNixcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA3LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDgsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgPGRpdiBjbGFzcz1cImN1c3RvbS10cmVlLWNvbnRhaW5lclwiPlxuICAgIDxwPlVzaW5nIHNjb3BlZCBzbG90PC9wPlxuICAgIDxlbC10cmVlXG4gICAgICA6aWNvbj1cImljb25cIlxuICAgICAgOmRhdGE9XCJkYXRhU291cmNlXCJcbiAgICAgIG5vZGUta2V5PVwiaWRcIlxuICAgICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBub2RlLCBkYXRhIH1cIj5cbiAgICAgICAgPHNwYW4gY2xhc3M9XCJjdXN0b20tdHJlZS1ub2RlXCI+XG4gICAgICAgICAgPHNwYW4+e3sgbm9kZS5sYWJlbCB9fTwvc3Bhbj5cbiAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgIDxhIEBjbGljaz1cImFwcGVuZChkYXRhKVwiPiBBcHBlbmQgPC9hPlxuICAgICAgICAgICAgPGEgc3R5bGU9XCJtYXJnaW4tbGVmdDogOHB4XCIgQGNsaWNrPVwicmVtb3ZlKG5vZGUsIGRhdGEpXCI+IERlbGV0ZSA8L2E+XG4gICAgICAgICAgPC9zcGFuPlxuICAgICAgICA8L3NwYW4+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdHJlZT5cbiAgPC9kaXY+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4uY3VzdG9tLXRyZWUtbm9kZSB7XG4gIGZsZXg6IDE7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcbiAgZm9udC1zaXplOiAxNHB4O1xuICBwYWRkaW5nLXJpZ2h0OiA4cHg7XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

icon 输入的有效sting 是什么 对一ts而言component 的有效类型是什么

### What is Expected?

ts中icon类型component
有效的string 输入

### What is actually happening?

const icon=ref('div')
const icon=ref('xxx')
const icon=ref(component as Component)

### Additional comments

_(empty)_
<img width="1161" alt="image" src="https://github.com/element-plus/element-plus/assets/81684567/ddd3a071-675b-459c-8bad-dad00af3fb2c">

**Comment by btea** [comment]
You can refer to here https://github.com/element-plus/element-plus/blob/69dcee0a51414ae8442d661d9f9b0c4b0ac426b6/packages/components/tree/src/tree.type.ts#L1-L8

**Comment by Pancake-Q** [comment]
<img width="1278" alt="image" src="https://github.com/element-plus/element-plus/assets/81684567/e31bc7f4-adaa-4cc1-947d-624e7211b89e">
<img width="969" alt="image" src="https://github.com/element-plus/element-plus/assets/81684567/8bef5d9a-3fce-4d71-9163-8199a86dc123">
Is that a bad way to write code. so confused

**Comment by Pancake-Q** [comment]
I don't know what is the reference value of this sting type
eg： icon-name？

**Comment by btea** [comment]
For `component` used internally, you can refer to the description of `string` and `Component` in the vue <a href="https://vuejs.org/api/built-in-special-elements.html#component:~:text=When is is a string, it could be either an HTML tag name or a component's registered name">document</a>.
https://github.com/element-plus/element-plus/blob/69dcee0a51414ae8442d661d9f9b0c4b0ac426b6/packages/components/tree/src/tree-node.vue#L43

**Comment by Pancake-Q** [comment]
I know he has no problem using it this way, the key is the feedback from his ts type check, which I have asserted is a component type,Am I missing the TS related configuration

**Comment by btea** [comment]
It seems to be related to the editor, I use vscode is normal. 🤔

![image](https://github.com/element-plus/element-plus/assets/24516654/2e3145f5-56e7-46f6-adfd-415b235b8546)

**Comment by Pancake-Q** [comment]
I know webstorm config 
<img width="982" alt="image" src="https://github.com/element-plus/element-plus/assets/81684567/1bd2a84b-a17c-46d4-a7b0-a62a24055bcb">
but `icon="Loading"` is It worked in a way I didn't expect!
Thank you for your time.
