### ISSUE TITLE
[Component] [select] el-select 的 placement 属性 不生效

### ISSUE THREAD

**Issue by Alone-Michael** [element-plus/element-plus#13845]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/windows`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/j0phfnz8/1/)

### Steps to reproduce

<el-select v-model="serviceType" class="m-2" placement="right-start" clearable placeholder="请选择服务方式"
                    v-else>
                    <el-option v-for="item in serviceOptionsList" :key="item.value" :label="item.label"
                      :value="item.value" />
                  </el-select>

### What is Expected?

下拉弹框出现在右边

### What is actually happening?

出现在上边或者下边

### Additional comments

_(empty)_

**Comment by Tranyan** [comment]
那一定是右边空间不够

**Comment by Tranyan** [comment]
![image](https://github.com/element-plus/element-plus/assets/37946480/071047c1-afbd-4f3e-ba96-bed27f9f9de4)

**Comment by chenxch** [comment]
@Alone-Michael Is it convenient to reproduce through the playground, JSFiddle cannot be accessed.

**Comment by Alone-Michael** [comment]
查找了下原因  最新版本的可以生效 但是我现在使用的2.1.8 版本 无法生效 查看DOM节点还是 单独挂载的 无法直接生效
![image](https://github.com/element-plus/element-plus/assets/49513546/7abfb6cf-04c3-4287-93fc-386b64f57c9a)
![image](https://github.com/element-plus/element-plus/assets/49513546/42db0440-20fd-4ceb-b7e5-85d85538d100)

**Comment by Alone-Michael** [comment]
![image](https://github.com/element-plus/element-plus/assets/49513546/6a8ae934-3588-4fe2-a3c9-2e77d76c1ee8)
2.1.8版本 无法生效 ，最新版本是正常的 查看DOM节点 发现只是添加了这个属性 还是单独挂载的 没有触发

**Comment by Alone-Michael** [comment]
> ![image](https://user-images.githubusercontent.com/37946480/258018403-071047c1-afbd-4f3e-ba96-bed27f9f9de4.png)
这个是因为该编译器 无法选择版本，只是默认最新的话 是生效的
