### ISSUE TITLE
[Component] [select] 最新版2.3.8select的问题

### ISSUE THREAD

**Issue by yyq914828jzg** [element-plus/element-plus#13847]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.3.8`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Link]()

### Steps to reproduce

<template>
  <div class="flex flex-wrap">
    <div class="m-4">
      <p>default</p>
      <el-select
        v-model="value"
        filterable
        remote
        reserve-keyword
        placeholder="Please enter a keyword"
        :remote-method="remoteMethod"
        :loading="loading"
        @change="change"
      >
        <el-option
          v-for="item in options"
          :key="item.value"
          :label="item.label"
          :value="item.value"
        />
      </el-select>
    </div>
 
  </div>
</template>

<script lang="ts" setup>
import { onMounted, ref } from 'vue'

interface ListItem {
  value: string
  label: string
}

const list = ref<ListItem[]>([])
const options = ref<ListItem[]>([])
const value = ref<string[]>([])
const loading = ref(false)

onMounted(() => {
  list.value = states.map((item) => {
    return { value: `value:${item}`, label: `label:${item}` }
  })
})
const change = () =>{
  console.log(333)
}
const remoteMethod = (query: string) => {
  console.log(111)
  if (query) {
    loading.value = true
    setTimeout(() => {
      loading.value = false
      options.value = list.value.filter((item) => {
        return item.label.toLowerCase().includes(query.toLowerCase())
      })
    }, 200)
  } else {
    options.value = []
  }
}

const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]
</script>

### What is Expected?

执行change事件的时候不在执行remoteMethod方法

### What is actually happening?

执行change事件的时候又执行remoteMethod方法，之前的版本是没有执行的

### Additional comments

_(empty)_

**Comment by yyq914828jzg** [comment]
> 我也遇到，尝试Vue Version: 3.3.x 解决

这不是框架的问题吗？和vue的版本还有关系？

**Comment by yj-liuzepeng** [comment]
> > 我也遇到，尝试Vue Version: 3.3.x 解决
> 
> 这不是框架的问题吗？和vue的版本还有关系？

和 vue版本无关，与[2.2.18版本](https://github.com/element-plus/element-plus/blob/dev/CHANGELOG.en-US.md#bug-fixes-26)的这个 #9587 pr有关系
