### ISSUE TITLE
[Bug Report] DatePicker set the clearable to false the clear button still display when its type is datetimerange

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1385]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
Chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/vgbire/pen/eYBOjZa

### Steps to reproduce
set the clearable to false and its type is datetimerange

### What is Expected?
clear button can't display

### What is actually happening?
clear button display

**Comment by zazzaz** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/10731096/106159291-96b4a100-61bf-11eb-9604-c29d6fdcbcd6.png">
well, by design, clearable is used to control the clear icon in the input field.

Still, we could add some more API to control the button in the panel.

**Comment by Vgbire** [comment]
I think the functions of clear button and clearable here are repeated. Maybe it should be replaced with cancel or some other button. If you want to keep it and let the user control it, maybe you should change it like this, replace clearable with inputclearable, and add a new panel clearable to distinguish them.

**Comment by Vgbire** [comment]
Even canceling this button is reasonable, because developers can customize it in shortcuts. One bad thing is that now you set clearable to false. I don't want users to leave it empty, but there is a cancel button to clear it.

**Comment by zazzaz** [comment]
We will add some more props to control the panel button, at present, you may hide it via css.

**Comment by kooriookami** [comment]
Seems it has been fixed.
