### ISSUE TITLE
[Component] [input] el-ui 文档中input组件disabled属性 默认值填错了，文档中写的是false，实际应该是true

### ISSUE THREAD

**Issue by He-Jia-Cheng** [element-plus/element-plus#13868]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0`
- Element Plus Version: `2.3.0`
- Browser / OS: `Microsoft Edge 版本 115.0.1901.188 `
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html)

### Steps to reproduce

我在修改el-input 标签的disabled属性值的时候，按默认值false填写，输入框能正常输入，什么都不加，直接在标签上填写disabled(等于使用默认值)，输入框有禁止输入的标记，说明false不是disabled的默认值

### What is Expected?

修改文档中el-input 标签的disabled的默认值false为 true

### What is actually happening?

el-ui 文档中input组件disabled属性 默认值填错了，文档中写的是false，实际应该是true

### Additional comments

_(empty)_

**Comment by freezepluto** [comment]
?

**Comment by yj-liuzepeng** [comment]
disabled：禁用，默认值是false---->不禁用，ture----> 禁用

**Comment by SuperRonin** [comment]
提问题的精神可佳，但是基础知识也要扎实啊！

**Comment by fuxichen1** [comment]
你理解错了,默认值是false，是指不传这个参数的时候是默认为false，只写disabled，不写值会自动填充成true，原生input也是这么处理的
![image](https://github.com/element-plus/element-plus/assets/132568355/2694b0fe-1134-4b48-84cf-ae908e543589)

**Comment by chenxch** [comment]
感谢 @yj-liuzepeng @fuxichen1 的回答， @He-Jia-Cheng  你也可以看看这个https://www.zhihu.com/question/266456980，适当的通过搜索引擎来解决你的一些问题。

**Comment by He-Jia-Cheng** [comment]
> 提问题的精神可佳，但是基础知识也要扎实啊！

快莫秀优越，我要是扎实就不会问了，你完全可以不打这句话的
