### ISSUE TITLE
[i18n] [All] 2.3.7升级2.3.8后 ./lib/locale/lang/zh-cn no known

### ISSUE THREAD

**Issue by zhangyuge7** [element-plus/element-plus#13877]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `chrome 115.0.5790.170/win11`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgPlxuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgemhDbiBmcm9tICdlbGVtZW50LXBsdXMvbGliL2xvY2FsZS9sYW5nL3poLWNuJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

引入import zhCn from 'element-plus/lib/locale/lang/zh-cn' 有问题

### What is Expected?

正常

### What is actually happening?

错误

### Additional comments

_(empty)_

**Comment by ChuTingzj** [comment]
官方推荐使用这种方式引入
```typescript
import zhCn from 'element-plus/dist/locale/zh-cn'
```

**Comment by ChuTingzj** [comment]
I think this is the source of the issues
## 2.3.7
```json
"exports": {
  ".": {
    "types": "./es/index.d.ts",
        "import": "./es/index.mjs",
        "require": "./lib/index.js"
  },
  "./es": "./es/index.mjs",
  "./lib": "./lib/index.js",
  "./es/*.mjs": "./es/*.mjs",
  "./es/*": "./es/*.mjs",
  "./lib/*.js": "./lib/*.js",
  "./lib/*": "./lib/*.js",
  "./*": "./*"
},
```
## 2.3.8
```json
"exports": {
  ".": {
    "types": "./es/index.d.ts",
        "import": "./es/index.mjs",
        "require": "./lib/index.js"
  },
  "./es": {
    "types": "./es/index.d.ts",
        "import": "./es/index.mjs"
  },
  "./lib": {
    "types": "./lib/index.d.ts",
        "require": "./lib/index.js"
  },
  "./es/*.mjs": {
    "types": "./es/*.d.ts",
        "import": "./es/*.mjs"
  },
  "./es/*": {
    "types": [
      "./es/*.d.ts",
      "./es/*/index.d.ts"
    ],
        "import": "./es/*.mjs"
  },
  "./lib/*.js": {
    "types": "./lib/*.d.ts",
        "require": "./lib/*.js"
  },
  "./lib/*": {
    "types": [
      "./lib/*.d.ts",
      "./lib/*/index.d.ts"
    ],
    "require": "./lib/*.js"
  },
  "./*": "./*"
},
```
