### ISSUE TITLE
[Component] [select] Error `TypeError: Cannot read properties of null (reading 'value')` after setting value in el-select with props: multiple, disabled, filterable

### ISSUE THREAD

**Issue by Anastasia226** [element-plus/element-plus#13872]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome/115.0.0.0  Mac OS X 10_15_7`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICAgIG11bHRpcGxlXG4gICAgZGlzYWJsZWRcbiAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrQnRuXCI+Y2xpY2s8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmPHN0cmluZ1tdPihbXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ0hUTUwnLFxuICAgIGxhYmVsOiAnSFRNTCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0NTUycsXG4gICAgbGFiZWw6ICdDU1MnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdKYXZhU2NyaXB0JyxcbiAgICBsYWJlbDogJ0phdmFTY3JpcHQnLFxuICB9LFxuXVxuXG5jb25zdCBjbGlja0J0biA9ICgpID0+IHtcbiAgdmFsdWUudmFsdWUucHVzaCgnSFRNTCcpXG59XG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Error appears after setting value in select

### What is Expected?

no error

### What is actually happening?

error in console  TypeError: Cannot read properties of null (reading 'value')

### Additional comments

in version 2.3.6 its work correct, in latest versions have error

**Comment by Anastasia226** [comment]
This error still appears in version 2.3.9

**Comment by cc-hearts** [comment]
> This error still appears in version 2.3.9

can you provide a playground?

**Comment by Anastasia226** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICAgIG11bHRpcGxlXG4gICAgZGlzYWJsZWRcbiAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrQnRuXCI+Y2xpY2s8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmPHN0cmluZ1tdPihbXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ0hUTUwnLFxuICAgIGxhYmVsOiAnSFRNTCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0NTUycsXG4gICAgbGFiZWw6ICdDU1MnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdKYXZhU2NyaXB0JyxcbiAgICBsYWJlbDogJ0phdmFTY3JpcHQnLFxuICB9LFxuXVxuXG5jb25zdCBjbGlja0J0biA9ICgpID0+IHtcbiAgdmFsdWUudmFsdWUucHVzaCgnSFRNTCcpXG59XG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==
