### ISSUE TITLE
[Docs] [All] 连个最基本的文档都维护不好吗 三天两头无法访问 一个中国的项目不把demo写成中文 写成英语显得你们水平高还是显得你们爱国  连个js文档都没有

### ISSUE THREAD

**Issue by wjh123484** [element-plus/element-plus#13887]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `1111`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/button.html)

### Steps to reproduce

连个最基本的文档都维护不好吗 三天两头无法访问 一个中国的项目不把demo写成中国 写成英语显得你们水平高还是显得你们爱国  连个js文档都没有

### What is Expected?

连个最基本的文档都维护不好吗 三天两头无法访问 一个中国的项目不把demo写成中国 写成英语显得你们水平高还是显得你们爱国  连个js文档都没有
### What is actually happening?

连个最基本的文档都维护不好吗 三天两头无法访问 一个中国的项目不把demo写成中国 写成英语显得你们水平高还是显得你们爱国  连个js文档都没有

### Additional comments

_(empty)_

**Comment by tsai996** [comment]
免费给你用你还理直气壮了？逼着你用了？

**Comment by baiwusanyu-c** [comment]
单走一个6

**Comment by songjianet** [comment]
> 单走一个6

跟一张6
