### ISSUE TITLE
[Component] [table, tooltip] 表格中启用tooltip, 配置option append-to,不生效

### ISSUE THREAD

**Issue by dean5277** [element-plus/element-plus#13905]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome 113.0.5672.64`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC10YWJsZSByZWY9XCJtdWx0aXBsZVRhYmxlUmVmXCIgOmRhdGE9XCJ0YWJsZURhdGFcIiBib3JkZXIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiIEBzZWxlY3Rpb24tY2hhbmdlPVwiaGFuZGxlU2VsZWN0aW9uQ2hhbmdlXCI+XG4gIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTIwXCI+XG4gICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvdGVtcGxhdGU+XG4gIDwvZWwtdGFibGUtY29sdW1uPlxuICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIj5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICA8ZWwtdGFibGUgcmVmPVwibXVsdGlwbGVUYWJsZVJlZlwiIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiIHNob3ctb3ZlcmZsb3ctdG9vbHRpcCA6dG9vbHRpcC1vcHRpb25zPVwie1xuICAgICAgICBwb3BwZXJDbGFzczogJ3ctNDAwcHgnLFxuICAgICAgICB0ZWxlcG9ydGVkOiB0cnVlLFxuICAgICAgICAnYXBwZW5kLXRvJzogJ2JvZHknXG4gICAgICB9XCIgQHNlbGVjdGlvbi1jaGFuZ2U9XCJoYW5kbGVTZWxlY3Rpb25DaGFuZ2VcIj5cblxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTIwXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvdGVtcGxhdGU+XG4gICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICAgICAgPC9lbC10YWJsZT5cbiAgICAgIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAyMHB4XCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlU2VsZWN0aW9uKFt0YWJsZURhdGFbMV0sIHRhYmxlRGF0YVsyXV0pXCI+VG9nZ2xlIHNlbGVjdGlvbiBzdGF0dXMgb2Ygc2Vjb25kIGFuZCB0aGlyZFxuICAgICAgICAgIHJvd3M8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0b2dnbGVTZWxlY3Rpb24oKVwiPkNsZWFyIHNlbGVjdGlvbjwvZWwtYnV0dG9uPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJsZS1jb2x1bW4+XG48L2VsLXRhYmxlPlxuPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDIwcHhcIj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0b2dnbGVTZWxlY3Rpb24oW3RhYmxlRGF0YVsxXSwgdGFibGVEYXRhWzJdXSlcIj5Ub2dnbGUgc2VsZWN0aW9uIHN0YXR1cyBvZiBzZWNvbmQgYW5kIHRoaXJkXG4gICAgcm93czwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInRvZ2dsZVNlbGVjdGlvbigpXCI+Q2xlYXIgc2VsZWN0aW9uPC9lbC1idXR0b24+XG48L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFRhYmxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYWRkcmVzczogc3RyaW5nXG59XG5cbmNvbnN0IG11bHRpcGxlVGFibGVSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbFRhYmxlPj4oKVxuY29uc3QgbXVsdGlwbGVTZWxlY3Rpb24gPSByZWY8VXNlcltdPihbXSlcbmNvbnN0IHRvZ2dsZVNlbGVjdGlvbiA9IChyb3dzPzogVXNlcltdKSA9PiB7XG4gIGlmIChyb3dzKSB7XG4gICAgcm93cy5mb3JFYWNoKChyb3cpID0+IHtcbiAgICAgIC8vIFRPRE86IGltcHJvdmVtZW50IHR5cGluZyB3aGVuIHJlZmFjdG9yIHRhYmxlXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50XG4gICAgICAvLyBAdHMtZXhwZWN0LWVycm9yXG4gICAgICBtdWx0aXBsZVRhYmxlUmVmLnZhbHVlIS50b2dnbGVSb3dTZWxlY3Rpb24ocm93LCB1bmRlZmluZWQpXG4gICAgfSlcbiAgfSBlbHNlIHtcbiAgICBtdWx0aXBsZVRhYmxlUmVmLnZhbHVlIS5jbGVhclNlbGVjdGlvbigpXG4gIH1cbn1cbmNvbnN0IGhhbmRsZVNlbGVjdGlvbkNoYW5nZSA9ICh2YWw6IFVzZXJbXSkgPT4ge1xuICBtdWx0aXBsZVNlbGVjdGlvbi52YWx1ZSA9IHZhbFxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA4JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA3JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLnctNDAwcHgge1xuICB3aWR0aDogNDAwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1.表格启用show-overflow-tooltip
2.配置:tooltip-options="{
        popperClass: 'w-400px',
        teleported: true,
        'append-to': 'body'
      }"

### What is Expected?

1. 希望能插入到body那里，就不会被表格遮挡

### What is actually happening?

1. 因为没有生效，所以弹出层被表格border切割，可以查看边缘部分

### Additional comments
![K@TFKU3AZJ@ )12A@HZ0 UK](https://github.com/element-plus/element-plus/assets/1802631/9c082824-2450-4c1e-97b7-741c60579b3d)

**Comment by btea** [comment]
`tooltipOptions` does not currently support `appendTo`.
https://github.com/element-plus/element-plus/blob/ec639c4d14c6b12c7ef12bbcd113ae789c8e74ab/packages/components/table/src/util.ts#L18-L32

**Comment by dean5277** [comment]
OK~
