### ISSUE TITLE
[Component] [tree] el-tree，同时开启多选框和拖拽功能后，拖拽节点会导致节点取消选中

### ISSUE THREAD

**Issue by Alixhan** [element-plus/element-plus#13912]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Microsoft Edge 版本 115.0.1901.188 (正式版本) (64 位)`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCBkYXRhID0gW1xuICB7IGlkOiAxLCBsYWJlbDogJ2FhYScgfSxcbiAgeyBpZDogMiwgbGFiZWw6ICdiYmInIH0sXG4gIHsgaWQ6IDMsIGxhYmVsOiAnY2NjJyB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICAgIG5vZGUta2V5PVwiaWRcIlxuICAgICAgOmRhdGE9XCJkYXRhXCJcbiAgICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cIlsxLDIsM11cIlxuICAgICAgOnByb3BzPVwie1xuICAgICAgICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgICAgICAgbGFiZWw6ICdsYWJlbCcsXG4gICAgICB9XCJcbiAgICAgIGRyYWdnYWJsZVxuICAgICAgc2hvdy1jaGVja2JveFxuICAgIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-tree，同时开启多选框和拖拽功能后，拖拽节点会导致节点取消选中

### What is Expected?

拖拽节点后保持原本的checked状态

### What is actually happening?

节点选中状态被取消

### Additional comments

_(empty)_

**Comment by Alixhan** [comment]
Hello?

**Comment by dwyanewang** [comment]
我也遇到同样的问题，在选中的情况下拖拽，选中会丢失，还会触发check-change事件
