### ISSUE TITLE
[Bug Report] el-form  的 status-icon 会在一些使用了插槽的表单元素中显示

### ISSUE THREAD

**Issue by CrazyMAD001** [element-plus/element-plus#13917]
### Element Plus version
2.3.9

### OS/Browsers version
macos

### Vue version
3.2.47

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-6pgkfr

### Steps to reproduce
配置一个有插槽元素的表单项 触发表单验证 error  status-icon 在插槽元素中也显示

### What is Expected?
不要在插槽中显示 stasut-icon

### What is actually happening?
在插槽中显示 stasut-icon

**Comment by chenxch** [comment]
```
<el-form-item>
          <el-select>
          </el-select>
</el-form-item>
```

**Comment by CrazyMAD001** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm1cbiAgICByZWY9XCJydWxlRm9ybVJlZlwiXG4gICAgOm1vZGVsPVwicnVsZUZvcm1cIlxuICAgIHN0YXR1cy1pY29uXG4gICAgOnJ1bGVzPVwicnVsZXNcIlxuICAgIGxhYmVsLXdpZHRoPVwiMTIwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUGFzc3dvcmRcIiBwcm9wPVwicGFzc1wiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJydWxlRm9ybS5wYXNzXCIgdHlwZT1cInBhc3N3b3JkXCIgYXV0b2NvbXBsZXRlPVwib2ZmXCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQ29uZmlybVwiIHByb3A9XCJjaGVja1Bhc3NcIj5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsPVwicnVsZUZvcm0uY2hlY2tQYXNzXCJcbiAgICAgICAgdHlwZT1cInBhc3N3b3JkXCJcbiAgICAgICAgYXV0b2NvbXBsZXRlPVwib2ZmXCJcbiAgICAgIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFnZVwiIHByb3A9XCJhZ2VcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cInJ1bGVGb3JtLmFnZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzdWJtaXRGb3JtKHJ1bGVGb3JtUmVmKVwiXG4gICAgICAgID5TdWJtaXQ8L2VsLWJ1dHRvblxuICAgICAgPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0ocnVsZUZvcm1SZWYpXCI+UmVzZXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSwgRm9ybVJ1bGVzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBydWxlRm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KClcblxuY29uc3QgY2hlY2tBZ2UgPSAocnVsZTogYW55LCB2YWx1ZTogYW55LCBjYWxsYmFjazogYW55KSA9PiB7XG4gIGlmICghdmFsdWUpIHtcbiAgICByZXR1cm4gY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIGFnZScpKVxuICB9XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGlmICghTnVtYmVyLmlzSW50ZWdlcih2YWx1ZSkpIHtcbiAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcignUGxlYXNlIGlucHV0IGRpZ2l0cycpKVxuICAgIH0gZWxzZSB7XG4gICAgICBpZiAodmFsdWUgPCAxOCkge1xuICAgICAgICBjYWxsYmFjayhuZXcgRXJyb3IoJ0FnZSBtdXN0IGJlIGdyZWF0ZXIgdGhhbiAxOCcpKVxuICAgICAgfSBlbHNlIHtcbiAgICAgICAgY2FsbGJhY2soKVxuICAgICAgfVxuICAgIH1cbiAgfSwgMTAwMClcbn1cblxuY29uc3QgdmFsaWRhdGVQYXNzID0gKHJ1bGU6IGFueSwgdmFsdWU6IGFueSwgY2FsbGJhY2s6IGFueSkgPT4ge1xuICBpZiAodmFsdWUgPT09ICcnKSB7XG4gICAgY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIHBhc3N3b3JkJykpXG4gIH0gZWxzZSB7XG4gICAgaWYgKHJ1bGVGb3JtLmNoZWNrUGFzcyAhPT0gJycpIHtcbiAgICAgIGlmICghcnVsZUZvcm1SZWYudmFsdWUpIHJldHVyblxuICAgICAgcnVsZUZvcm1SZWYudmFsdWUudmFsaWRhdGVGaWVsZCgnY2hlY2tQYXNzJywgKCkgPT4gbnVsbClcbiAgICB9XG4gICAgY2FsbGJhY2soKVxuICB9XG59XG5jb25zdCB2YWxpZGF0ZVBhc3MyID0gKHJ1bGU6IGFueSwgdmFsdWU6IGFueSwgY2FsbGJhY2s6IGFueSkgPT4ge1xuICBpZiAodmFsdWUgPT09ICcnKSB7XG4gICAgY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIHBhc3N3b3JkIGFnYWluJykpXG4gIH0gZWxzZSBpZiAodmFsdWUgIT09IHJ1bGVGb3JtLnBhc3MpIHtcbiAgICBjYWxsYmFjayhuZXcgRXJyb3IoXCJUd28gaW5wdXRzIGRvbid0IG1hdGNoIVwiKSlcbiAgfSBlbHNlIHtcbiAgICBjYWxsYmFjaygpXG4gIH1cbn1cblxuY29uc3QgcnVsZUZvcm0gPSByZWFjdGl2ZSh7XG4gIHBhc3M6ICcnLFxuICBjaGVja1Bhc3M6ICcnLFxuICBhZ2U6ICcnLFxufSlcblxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZTxGb3JtUnVsZXM8dHlwZW9mIHJ1bGVGb3JtPj4oe1xuICBwYXNzOiBbeyB2YWxpZGF0b3I6IHZhbGlkYXRlUGFzcywgdHJpZ2dlcjogJ2JsdXInIH1dLFxuICBjaGVja1Bhc3M6IFt7IHZhbGlkYXRvcjogdmFsaWRhdGVQYXNzMiwgdHJpZ2dlcjogJ2JsdXInIH1dLFxuICBhZ2U6IFt7IHZhbGlkYXRvcjogY2hlY2tBZ2UsIHRyaWdnZXI6ICdibHVyJyB9XSxcbn0pXG5cbmNvbnN0IHN1Ym1pdEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgaWYgKHZhbGlkKSB7XG4gICAgICBjb25zb2xlLmxvZygnc3VibWl0IScpXG4gICAgfSBlbHNlIHtcbiAgICAgIGNvbnNvbGUubG9nKCdlcnJvciBzdWJtaXQhJylcbiAgICAgIHJldHVybiBmYWxzZVxuICAgIH1cbiAgfSlcbn1cblxuY29uc3QgcmVzZXRGb3JtID0gKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XG4gIGlmICghZm9ybUVsKSByZXR1cm5cbiAgZm9ybUVsLnJlc2V0RmllbGRzKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==

**Comment by CrazyMAD001** [comment]
<img width="1750" alt="image" src="https://github.com/element-plus/element-plus/assets/39940108/2c0c36a9-0e7b-4bf6-bea5-ffc158903c44">

**Comment by zhao1995chen** [comment]
@CrazyMAD001 

It looks like `el-select` shares `el-form-item` attribute `prop` which triggers `checkPass` validation.
I'm not sure if adding another validation component to the prefix or the suffix meets ​​the official expectation or not.
But if you want to achieve your expectations, you could try the following method, it looks workable.

```html
<el-form-item label="Confirm" prop="checkPass">
  <el-input v-model="ruleForm.checkPass" type="password" autocomplete="off">
    <template #prepend>
      <el-form-item>
        <el-select></el-select>
      </el-form-item>
    </template>
  </el-input>
</el-form-item>
```
<img width="729" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/67bf4080-d0b7-4b0b-8a12-9d446982ac53">

---

By the way, your reproduction link is invalid, cannot reproduce the situation on CodeSandbox. 

<img width="540" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/6dc89479-8dd1-484d-983b-b19b3e478f06">

Also, putting `setup` attribute in `script` tag is necessary to make the code workable, or get lots of error warnings.

<img width="701" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/c9ddf4c5-e4fd-4707-a609-8064cf15a926">

**Comment by CrazyMAD001** [comment]
@zhao1995chen 3Q 3Q your method is workable!
