### ISSUE TITLE
[Component] [upload] beforeUpload事件改变上传参数data字段的数据后 上传时无法获取到最新的数据

### ISSUE THREAD

**Issue by hao-xh** [element-plus/element-plus#13925]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIHYtbW9kZWw6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIGFjdGlvbj1cImh0dHBzOi8vb3NzLWNuLWJlaWppbmcuYWxpeXVuY3MuY29tXCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIDpiZWZvcmUtdXBsb2FkPVwiYmVmb3JlVXBsb2FkXCJcbiAgICA6b24tc3VjY2Vzcz1cInVwbG9hZFN1Y2Nlc3NcIlxuICAgIDpsaW1pdD1cIjk5OTlcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmltcG9ydCB0eXBlIHsgVXBsb2FkUHJvcHMsIFVwbG9hZFVzZXJGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmaWxlTGlzdCA9IHJlZjxVcGxvYWRVc2VyRmlsZVtdPihbXG5dKVxuXG5jb25zdCB1cGxvYWREYXRhID0gcmVhY3RpdmU8e1xuICBrZXk6IHN0cmluZztcbn0+KHtcbiAga2V5OiAnMTExMTEnLFxufSk7XG5cbmNvbnN0IGJlZm9yZVVwbG9hZDogVXBsb2FkUHJvcHNbJ2JlZm9yZVVwbG9hZCddID0gKHJhd0ZpbGUpID0+IHtcbiAgLy8g5LuOMi4zLjPniYjmnKzlvIDlp4vvvIxkYXRh5Lit55qE5pWw5o2u5aaC5p6c5piv5byC5q2l5pu05pS555qE77yM5ZyocmVzb2x2ZSh0cnVlKei/m+ihjOS4iuS8oOaXtu+8jOacgOaWsOeahGRhdGHkuK3nmoTmlbDmja7ml6Dms5Xooqvmm7TmlrBcbiAgLy8gMi4zLjPniYjmnKzku6XkuIvliJnkuI3lj5flvbHlk41cbiAgcmV0dXJuIG5ldyBQcm9taXNlKHJlc29sdmUgPT4ge1xuICAgIC8vIOaooeaLn+W8guatpeWkhOeQhlxuICAgIC8vIOivt+axgmFwaeaLv29zc+eahOmFjee9ruaVsOaNrlxuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgdXBsb2FkRGF0YS5rZXkgPSAnMjIyMic7XG4gICAgICAvLyDms6jmhI/nnIvmjqfliLblj7BuZXR3b3Jr5LiLb3Nz5o6l5Y+j5Y+C5pWw77yMa2V55a2X5q615bqU6K+l5Li6MjIyMlxuICAgICAgcmVzb2x2ZSh0cnVlKVxuICAgIH0sIDEwMDApXG4gIH0pO1xuICBcbn07XG5cbmNvbnN0IHVwbG9hZFN1Y2Nlc3MgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd1cGxvYWQtc3VjY2VzcycpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

beforeUplaod事件在resolve之前改变data的数据，在开始上传后，上传的接口中的参数并不是最新的。
目前已回退版本解决，但有些新特性无法使用了。
具体复现操作可以看上面的代码链接

### What is Expected?

data的参数能够取得最新的数据

### What is actually happening?

传的接口中的参数并不是最新的

### Additional comments

_(empty)_

**Comment by Zhuxb-Clouds** [comment]
看起来似乎和这个pr有关 #12575

**Comment by HeftyKoo** [comment]
This issue is caused by #12029 and #12575.

IMO, we should revert these two PRs, and keep the original behavior. `beforeUpload` runs in parallel, changing data in this hook is a side effect, which should be handled on the user side.

#12029 only keeps a snapshot after synchronization change, but can not deal with asynchronous.
Honestly, I don know what the problem of  #12575 exactly resolves. 

At last, I don't think changing `beforeUpload` runs in the queue is a good solution. Because users may use it to do some heavy jobs.

@chenxch @jianjunyuu @btea @GenerQAQ What do your gays think?

**Comment by jianjunyuu** [comment]
> 

As you describe:
1. issue https://github.com/element-plus/element-plus/pull/12029 does not solve the asynchronous situation. I think this can expand props.data and support hooks like beforeUpload, data is processed first, and then beforeUpload
`data: (file: UploadRawFile) => Awaitable<Record<string, any> | null | undefined>`
2. I also think that the new code in https://github.com/element-plus/element-plus/pull/12029 is useless

@HeftyKoo @chenxch In this way props.data can satisfy many complex scenarios.

**Comment by HeftyKoo** [comment]
> I think this can expand props.data and support hooks like beforeUpload, data is processed first, and then beforeUpload

Good point. But I have a slightly different perspective on the timing. `data` should be executed after the `beforeUpload`,  because it relies on the `file` which `beforeUpload` may be transformed.

**Comment by HeftyKoo** [comment]
> I think this can expand props.data and support hooks like beforeUpload, data is processed first, and then beforeUpload

Good point. But I have a slightly different perspective on the timing. `data` should be executed after the `beforeUpload`,  because it relies on the `file` which `beforeUpload` may be transformed.

**Comment by jianjunyuu** [comment]
> Good point. But I have a slightly different perspective on the timing. data should be executed after the beforeUpload, because it relies on the file which beforeUpload may be transformed.

agree~

**Comment by jianjunyuu** [comment]
related discussion https://github.com/element-plus/element-plus/discussions/14016

**Comment by Kimmyzhao** [comment]
这个问题解决了么？在2.3.14中好像还存在这个问题

**Comment by hao-xh** [comment]
> 这个问题解决了么？在2.3.14中好像还存在这个问题

上次的更新好像并未解决这个问题，我在问题的“Reproduction Link”中使用最后一个版本依然存在这个问题。
@jianjunyuu

**Comment by HeftyKoo** [comment]
> > 这个问题解决了么？在2.3.14中好像还存在这个问题
> 
> 上次的更新好像并未解决这个问题，我在问题的“Reproduction Link”中使用最后一个版本依然存在这个问题。 @jianjunyuu

因为 `beforeUpload` 异步修改数据时，会存在冲突的情况，现在 `data` 支持传入函数，需要异步获取的数据，可以在 `data` 函数中操作。

[example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIHYtbW9kZWw6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIGFjdGlvbj1cImh0dHBzOi8vb3NzLWNuLWJlaWppbmcuYWxpeXVuY3MuY29tXCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIDpvbi1zdWNjZXNzPVwidXBsb2FkU3VjY2Vzc1wiXG4gICAgOmxpbWl0PVwiOTk5OVwiXG4gID5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+Q2xpY2sgdG8gdXBsb2FkPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwS0IuXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbl0pXG5cbmNvbnN0IHVwbG9hZERhdGEgPSAocmF3RmlsZSkgPT4ge1xuICAvLyDku44yLjMuM+eJiOacrOW8gOWni++8jGRhdGHkuK3nmoTmlbDmja7lpoLmnpzmmK/lvILmraXmm7TmlLnnmoTvvIzlnKhyZXNvbHZlKHRydWUp6L+b6KGM5LiK5Lyg5pe277yM5pyA5paw55qEZGF0YeS4reeahOaVsOaNruaXoOazleiiq+abtOaWsFxuICAvLyAyLjMuM+eJiOacrOS7peS4i+WImeS4jeWPl+W9seWTjVxuICByZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XG4gICAgLy8g5qih5ouf5byC5q2l5aSE55CGXG4gICAgLy8g6K+35rGCYXBp5ou/b3Nz55qE6YWN572u5pWw5o2uXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAvLyDms6jmhI/nnIvmjqfliLblj7BuZXR3b3Jr5LiLb3Nz5o6l5Y+j5Y+C5pWw77yMa2V55a2X5q615bqU6K+l5Li6MjIyMlxuICAgICAgcmVzb2x2ZSh7XG4gICAgICAgIGtleTogJzIyMjInXG4gICAgICB9KVxuICAgIH0sIDEwMDApXG4gIH0pO1xuICBcbn07XG5cbmNvbnN0IHVwbG9hZFN1Y2Nlc3MgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd1cGxvYWQtc3VjY2VzcycpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by hao-xh** [comment]
> > > 这个问题解决了么？在2.3.14中好像还存在这个问题
> > 
> > 
> > 上次的更新好像并未解决这个问题，我在问题的“Reproduction Link”中使用最后一个版本依然存在这个问题。 @jianjunyuu
> 
> 因为 `beforeUpload` 异步修改数据时，会存在冲突的情况，现在 `data` 支持传入函数，需要异步获取的数据，可以在 `data` 函数中操作。
> 
> [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIHYtbW9kZWw6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIGFjdGlvbj1cImh0dHBzOi8vb3NzLWNuLWJlaWppbmcuYWxpeXVuY3MuY29tXCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIDpvbi1zdWNjZXNzPVwidXBsb2FkU3VjY2Vzc1wiXG4gICAgOmxpbWl0PVwiOTk5OVwiXG4gID5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+Q2xpY2sgdG8gdXBsb2FkPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwS0IuXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbl0pXG5cbmNvbnN0IHVwbG9hZERhdGEgPSAocmF3RmlsZSkgPT4ge1xuICAvLyDku44yLjMuM+eJiOacrOW8gOWni++8jGRhdGHkuK3nmoTmlbDmja7lpoLmnpzmmK/lvILmraXmm7TmlLnnmoTvvIzlnKhyZXNvbHZlKHRydWUp6L+b6KGM5LiK5Lyg5pe277yM5pyA5paw55qEZGF0YeS4reeahOaVsOaNruaXoOazleiiq+abtOaWsFxuICAvLyAyLjMuM+eJiOacrOS7peS4i+WImeS4jeWPl+W9seWTjVxuICByZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XG4gICAgLy8g5qih5ouf5byC5q2l5aSE55CGXG4gICAgLy8g6K+35rGCYXBp5ou/b3Nz55qE6YWN572u5pWw5o2uXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAvLyDms6jmhI/nnIvmjqfliLblj7BuZXR3b3Jr5LiLb3Nz5o6l5Y+j5Y+C5pWw77yMa2V55a2X5q615bqU6K+l5Li6MjIyMlxuICAgICAgcmVzb2x2ZSh7XG4gICAgICAgIGtleTogJzIyMjInXG4gICAgICB9KVxuICAgIH0sIDEwMDApXG4gIH0pO1xuICBcbn07XG5cbmNvbnN0IHVwbG9hZFN1Y2Nlc3MgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd1cGxvYWQtc3VjY2VzcycpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

感谢您的提醒，通过修改已经成功了！
