### ISSUE TITLE
[Component] [dropdown] Dropdown组件聚焦会出现黑色边框

### ISSUE THREAD

**Issue by zjqphp** [element-plus/element-plus#13923]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Windows `
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dropdown.html)

### Steps to reproduce

打开你们的官网，组件示例。在左侧菜单栏中选择Dropdown下拉菜单组件。将鼠标悬停到基础用法的第一个例子上。偶尔会出现黑色边框。按F12打开开发者工具，选中该节点，使用开发者工具让这个元素聚焦，会出现黑色边框。

### What is Expected?

在hover模式下不出现黑色边框

### What is actually happening?

现在官网的dropdown组件在hover模式下会出现黑色边框

### Additional comments

_(empty)_

![25dd89fb1e39894ce2dc587f1fec558](https://github.com/element-plus/element-plus/assets/40885190/a5b0a206-1038-4738-81f2-6903d9908b98)

**Comment by chenxch** [comment]
same as #11662

**Comment by zjqphp** [comment]
@chenxch thx
