### ISSUE TITLE
[feature request] can el-tree support "ctrl + drag" to copy nodes

### ISSUE THREAD

**Issue by diction** [element-plus/element-plus#1394]
### Existing Component
是

### Component Name
el-tree

### Description
el-tree是否可以添加功能，支持“ctrl 拖拽”实现复制节点功能。

**Comment by JeremyWuuuuu** [comment]
I'm afraid we can't. We have exposed the API which you can manage that yourself. Check this one out: https://element-plus.org/#/en-US/component/tree#draggable
