### ISSUE TITLE
[Component] form表单内存泄漏

### ISSUE THREAD

**Issue by Clareyang213** [element-plus/element-plus#13949]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome 115.0.5790.171`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`
- `el-input`
- `el-select`
- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblx0PGRpdj5cbiAgICA8ZGl2PuaIkeaYr+eItue7hOS7tjwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJuYXYtYm94XCI+XG4gICAgICA8ZGl2IGNsYXNzPVwibmF2LWl0ZW1cIiBAY2xpY2s9XCJoYW5kbGVDaGFuZ2UoJ25hdjEnKVwiPueCueaIkeWIh+aNom5hdjE8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJuYXYtaXRlbVwiIEBjbGljaz1cImhhbmRsZUNoYW5nZSgnbmF2MicpXCI+54K55oiR5YiH5o2ibmF2MjwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjb250ZW50LWJveFwiPlxuICAgICAgPGRpdj5cbiAgICAgICAgPGZvcm1UYWIgdi1pZj1cIm5hdlR5cGUgPT09ICduYXYxJ1wiIG5hbWU9XCJuYXYxXCIgLz5cbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdj5cbiAgICAgICAgPGZvcm1UYWIgdi1pZj1cIm5hdlR5cGUgPT09ICduYXYyJ1wiIG5hbWU9XCJuYXYyXCIgLz5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IGZvcm1UYWIgZnJvbSAnLi9mb3JtLXRhYi52dWUnXG5jb25zdCBuYXZUeXBlID0gcmVmKCcnKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHR5cGU6IHN0cmluZykgPT4ge1xuICBuYXZUeXBlLnZhbHVlID0gdHlwZVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5uYXYtYm94IHtcbiAgZGlzcGxheTogZmxleDtcbiAgbWFyZ2luLXRvcDogOHB4O1xuICBtYXJnaW4tYm90dG9tOiAxNnB4O1xufVxuLm5hdi1pdGVtIHtcbiAgbWFyZ2luLXJpZ2h0OiA4cHg7XG4gIGN1cnNvcjogcG9pbnRlcjtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2Zvcm0tdGFiLnZ1ZSI6Ijx0ZW1wbGF0ZT5cclxuICA8ZGl2PlxyXG4gICAgPGRpdj7miJHmmK/lrZDnu4Tku7Y8L2Rpdj5cclxuICAgIDxkaXY+Y3VycmVudDoge3sgbmFtZSB9fTwvZGl2PlxyXG4gICAgXHJcbiAgICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtRGF0YVwiIHJlZj1cInZGb3JtXCIgbGFiZWwtcG9zaXRpb249XCJyaWdodFwiIGxhYmVsLXdpZHRoPVwiNzZweFwiIHNpemU9XCJkZWZhdWx0XCIgQHN1Ym1pdC5wcmV2ZW50PlxyXG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLov5DljZXlj7dcIiBwcm9wPVwib3JkZXJOb1wiIGNsYXNzPVwibGFiZWwtcmlnaHQtYWxpZ25cIj5cclxuICAgICAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtRGF0YS5vcmRlck5vXCIgdHlwZT1cInRleHRcIiBjbGVhcmFibGUgPjwvZWwtaW5wdXQ+XHJcbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuW9leWNleaXpeacnzpcIiBsYWJlbC13aWR0aD1cIjYycHhcIiBwcm9wPVwib3JkZXJUaW1lXCIgY2xhc3M9XCJsYWJlbC1yaWdodC1hbGlnblwiPlxyXG4gICAgICAgICAgICA8ZWwtZGF0ZS1waWNrZXIgdi1tb2RlbD1cImZvcm1EYXRhLm9yZGVyVGltZVwiIHR5cGU9XCJkYXRldGltZVwiIGNsYXNzPVwiZnVsbC13aWR0aC1pbnB1dFwiIGZvcm1hdD1cIllZWVktTU0tREQgSEg6bW1cIiB2YWx1ZS1mb3JtYXQ9XCJ4XCIgY2xlYXJhYmxlPjwvZWwtZGF0ZS1waWNrZXI+XHJcbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICA8L2VsLWZvcm0+XHJcbiAgPC9kaXY+XHJcbjwvdGVtcGxhdGU+XHJcblxyXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxyXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXHJcblxyXG5kZWZpbmVQcm9wcyh7XHJcbiAgbmFtZToge1xyXG4gICAgdHlwZTogU3RyaW5nLFxyXG4gIH0sXHJcbn0pXHJcblxyXG5jb25zdCBmb3JtRGF0YSA9IHJlZih7XHJcbiAgb3JkZXJObzogJycsXHJcbiAgb3JkZXJUaW1lOiAnJ1xyXG59KTtcclxuPC9zY3JpcHQ+IiwiX28iOnt9fQ==)

### Steps to reproduce

打开控制台memory进行内存查看，点击切换nav按钮，进行子组件切换，多切换几次，内存有泄漏

### What is Expected?

切换子组件时，废弃的子组件所占用的内存被释放

### What is actually happening?

内存没清干净

### Additional comments

一个录单的大表单页面，100多个字段，多打开关闭几次，浏览器就崩溃了，客户一个小时浏览器能崩溃2、3次
![image](https://github.com/element-plus/element-plus/assets/32185886/5e49b72f-ff22-4ca0-9cd4-d84ac98507c4)

**Comment by Clareyang213** [comment]
切换组件，内存清不干净，特别是第一次销毁时，内存残留很多。在大表单页面，页面开关一次内存能增加20M，经常导致浏览器崩溃，各位大神帮忙看下，公司催的急，太影响客户操作了

**Comment by sangyong1203** [comment]
i have the same problem

**Comment by sangyong1203** [comment]
设置 KeepAlive 的max值。这个设置缓存多少个组件是活的并且管理占用的内存。 然后当关闭弹窗时记得清空所有数据。
<KeepAlive :max="10">
  <component :is="activeComponent" />
</KeepAlive>

**Comment by iwusong** [comment]
没发现内存泄漏现象

**Comment by YujiaCheng1996** [comment]
之前也遇到过，只能在onBeforeUmount/closeDialog等钩子里手动清除，还清不全面。后面就随机地在用户切换页面路由时进行重载刷新（类似F5），就能彻底清除内存泄露。

**Comment by 1zxca** [comment]
> 之前也遇到过，只能在onBeforeUmount/closeDialog等钩子里手动清除，还清不全面。后面就随机地在用户切换页面路由时进行重载刷新（类似F5），就能彻底清除内存泄露。

请问下有没有那种用户感知不到的刷新，大佬

**Comment by zhangxin0723** [comment]
V2.3.3 可以试试

**Comment by xiaoxian521** [comment]
Hello, after testing, it is basically impossible to reproduce the memory leak problem. If you still have this problem, it is recommended to reproduce it by writing a more complicated `demo` so that we can easily reproduce it. Just mention the memory leak related issues. It is best to provide a `github` warehouse and do not use it. `Element Plus Playground` may have a memory leak problem itself

Temporarily close this `issues` as mentioned above, if you can easily reproduce it, please open a new `issues` and we will investigate again
