### ISSUE TITLE
[button] docs: button components page misaligned

### ISSUE THREAD

**Issue by yilaikesi** [element-plus/element-plus#13957]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.htm)

### Steps to reproduce

Open this button document on the mobile side, some button components will be misaligned,
There are also web pages that you can swipe left and right

### What is Expected?

aligned and no swipe left and right

### What is actually happening?

misaligned and swipe left and right

### Additional comments

_(empty)_

![docs](https://github.com/element-plus/element-plus/assets/59329360/029b1d5c-093c-4c93-81ca-dd75a39a7011)

**Comment by yilaikesi** [comment]
It looks like the button component is misaligned causing the page to slide left and right

**Comment by chenxch** [comment]
@yilaikesi Thank you for your feedback. At present, there is no detailed plan to adapt the document to the mobile terminal.
