### ISSUE TITLE
[Build] [All] element 首页报错

### ISSUE THREAD

**Issue by Nacy0624** [element-plus/element-plus#13959]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `chrome最新版本`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/en-US/component/button.html)

### Steps to reproduce

https://element-plus.gitee.io/en-US/component/button.html

### What is Expected?

正常显示组件

### What is actually happening?

页面报错

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://element-plus.org/zh-CN/
