### ISSUE TITLE
[Bug Report] ElPagination got an unaligned style when its total is 1

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1395]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
mac

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973????

### Steps to reproduce
ElPagination will has an algin error when total is 1

### What is Expected?
align

### What is actually happening?
align

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/106354673-7e16c900-632e-11eb-8386-60ec5b974853.png)

**Comment by Ryan2128** [comment]
Fixed in #1372 , but next version not release.
