### ISSUE TITLE
[Component] Nuxt3 ssr 使用Menu mode在horizontal的情况下SubMenu嵌套两层会导致第二层打不开

### ISSUE THREAD

**Issue by AriesLyt** [element-plus/element-plus#13962]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome 115.0.5790.171`
- Build Tool: `Nuxt`

### Related Component

- `el-sub-menu`
- `el-menu`
- `el-menu-item`
- `el-menu-item-group`

### Reproduction Link

[Github Repo](https://github.com/AriesLyt/elementplus-error.git)

### Steps to reproduce

horizontal模式下的第二层submenu会丢失，控制台警告水合错误
vertical正常

### What is Expected?

horizontal二层正常

### What is actually happening?

horizontal二层未正常显示，vertical模式下正常
![3](https://github.com/element-plus/element-plus/assets/81557497/e512542e-0413-420f-9477-322c2460841b)
![2](https://github.com/element-plus/element-plus/assets/81557497/0962efd6-c491-4152-b28f-3c3520768541)

### Additional comments

_(empty)_

**Comment by ryuhangyeong** [comment]
<img width="680" alt="image" src="https://github.com/element-plus/element-plus/assets/27342882/0afc2507-a174-4411-a777-312e6093baa1">
