### ISSUE TITLE
[Style] [badge] Add an extra semicolon

### ISSUE THREAD

**Issue by tsinghua-lau** [element-plus/element-plus#13964]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrom 115.0.5790.170 `
- Build Tool: `Vite`

### Related Component

- `el-badge`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/badge.html)

### Steps to reproduce

https://element-plus.org/zh-CN/component/badge.html

### What is Expected?

Remove semicolon

### What is actually happening?

<img width="314" alt="image" src="https://github.com/element-plus/element-plus/assets/43164478/e6fa8a9c-e664-4337-a869-c0b910ffc71c">

**Comment by btea** [comment]
谢谢反馈！翻译问题，已修改，[链接](https://crowdin.com/translate/element-plus/899/en-zhcn?filter=basic&value=0)。
