### ISSUE TITLE
[Component] [select] Changing value of disabled multiple el-select triggers js error

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#13971]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Firefox 116 Chrome 115`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIGRhdGEoKSB7XG4gICAgcmV0dXJuIHtcbiAgICAgIHZhbDogWycxJywgJzInXVxuICAgIH07XG4gIH0sXG4gIG1vdW50ZWQoKSB7XG4gICAgICBzZXRUaW1lb3V0KCgpID0+IHtcblx0XHQgIHRoaXMudmFsID0gWycyJywnMyddO1xuXHQgIH0sIDUwMCk7XG4gIH1cbn1cbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IGRpc2FibGVkIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiIGZpbHRlcmFibGUgbXVsdGlwbGUgdi1tb2RlbD1cInZhbFwiPlxuICAgIDxlbC1vcHRpb24gdmFsdWU9XCIxXCI+MTwvZWwtb3B0aW9uPlxuICAgIDxlbC1vcHRpb24gdmFsdWU9XCIxXCI+MjwvZWwtb3B0aW9uPlxuICAgIDxlbC1vcHRpb24gdmFsdWU9XCIxXCI+MzwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Changing value of el-select triggers js error "s.value is null" when it has the following options:
- disabled=true
- multiple=true
- filterable=true
- reserve-keyword=false

It occurs at **useSelect:447**
```vue
      nextTick(() => {
        const length = input.value!.value.length * 15 + 20

```

### What is Expected?

no js errors

### What is actually happening?

js error "s.value is null"

### Additional comments

_(empty)_

**Comment by cc-hearts** [comment]
This issue has been fixed, take a look at #13872
