### ISSUE TITLE
[TypeScript] [All] 在vite-env.d.ts中声明自定义的全局组件会导致element-plus组件的类型声明失效

### ISSUE THREAD

**Issue by lechenc** [element-plus/element-plus#13985]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome/115.0.5790.170/macOS Ventura 版本13.4.1 (c) (22F770820d)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](https://gitee.com/chenlechenle/vue3_admin/tree/main/src)

### Steps to reproduce

```
//在vite-env.d.ts文件中
/// <reference types="vite/client" />
// 扩展Vue.js的类型定义，全局组件组件能够获得类型检查和自动补全的支持。
import Category from '@/components/global/Category/index.vue'
declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof Category
  }
}
```

### What is Expected?

全局组件Category得到TS提示，并且不影响到element-plus的组件TS提示

### What is actually happening?

全局组件Category得到了TS提示，但是会导致element-plus的组件失去TS提示

### Additional comments

可以到src/views/product/attr/index.vue下验证提示信息

添加声明时
<img width="682" alt="image" src="https://github.com/element-plus/element-plus/assets/48351275/858eb26b-7b9b-41ca-8601-e59e68ab2649">
<img width="977" alt="image" src="https://github.com/element-plus/element-plus/assets/48351275/83cd7892-b89e-48e4-972b-2e9cfe83acf3">

取消声明后
<img width="1048" alt="image" src="https://github.com/element-plus/element-plus/assets/48351275/d8492e66-a7f5-4e49-b6d1-7c572b660c1b">
<img width="714" alt="image" src="https://github.com/element-plus/element-plus/assets/48351275/ef82f593-3353-47fe-8119-4e8082517f03">

**Comment by tolking** [comment]
Perhaps you need to modify it like this

```diff
- declare module 'vue' {
+ declare module '@vue/runtime-core' {
```

**Comment by lechenc** [comment]
> Perhaps you need to modify it like this
> 
> ```diff
> - declare module 'vue' {
> + declare module '@vue/runtime-core' {
> ```

This will cause Category to lose the hint

**Comment by lixiaofa** [comment]
我也用到这样问题， 
![image](https://github.com/element-plus/element-plus/assets/23230215/cfa956ca-16cf-4ad6-9059-ad4782f07a88)
![image](https://github.com/element-plus/element-plus/assets/23230215/da7a657a-9d85-47d4-bea2-7a093d54c23a)
env.d.ts 
什么都没有
@lechenc @exherb @rotu @purepear

**Comment by tolking** [comment]
有很多原因可能引起这个问题。你可以参考文档手动引用全局类型；或者参考官方模板使用。

对于 pnpm 可能还需要增加

```
// .npmrc
shamefully-hoist=true
```

或者可能更新 Volar

**Comment by HongbiaoHe** [comment]
这个有解决办法吗

**Comment by miraclemada** [comment]
> 这个有解决办法吗

![Image](https://github.com/user-attachments/assets/cccec277-cb33-4724-ae8e-a1378dc3ed9b)

![Image](https://github.com/user-attachments/assets/d22bf2ff-c5b8-457e-a8a1-3403bac7840a)
试过改成这样临时解决了

**Comment by miraclemada** [comment]
> 这个有解决办法吗

![Image](https://github.com/user-attachments/assets/2e959f1f-b3e0-4ddd-8dda-24a218dc2e81)

**Comment by miraclemada** [comment]
> > 这个有解决办法吗
> 
> ![Image](https://github.com/user-attachments/assets/2e959f1f-b3e0-4ddd-8dda-24a218dc2e81)

这样临时解决了

**Comment by miraclemada** [comment]
> 这个有解决办法吗

![Image](https://github.com/user-attachments/assets/b89733e9-846d-4d89-8710-8d81b740688a)  这样临时解决了
