### ISSUE TITLE
[Component] [select] el-select组件，在开启filterable属性时，使用group分组，内容不显示

### ISSUE THREAD

**Issue by QiiSyhx** [element-plus/element-plus#13999]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `edge 115.0.1901.203 / windows`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcbmNvbnN0IGxpc3QgPSByZWYoW10pXG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBsaXN0LnZhbHVlID0gW1xuICAgIHtpZDogMSwgbGFiZWw6ICdsYWJlbDEnfSxcbiAgICB7aWQ6IDIsIGxhYmVsOiAnbGFiZWwyJ30sXG4gIF1cbn0sIDEwMDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGU+XG4gICAgPGVsLW9wdGlvbi1ncm91cCBsYWJlbD1cImFsbCBkYXRhXCI+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiKGl0ZW0sIGluZGV4KSBpbiBsaXN0XCJcbiAgICAgICAgOmtleT1cImluZGV4XCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0uaWRcIlxuICAgICAgLz5cbiAgICA8L2VsLW9wdGlvbi1ncm91cD5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlMlwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiKGl0ZW0sIGluZGV4KSBpbiBsaXN0XCJcbiAgICAgIDprZXk9XCJpbmRleFwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0uaWRcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

点击第一个select组件，下拉框的内容为空

### What is Expected?

点击打开select组件时，正常显示内容。

### What is actually happening?

不显示内容

### Additional comments

_(empty)_

**Comment by cc-hearts** [comment]
定位到问题是因为 `el-option-group`  没有添加 `key` 属性 从而导致没有渲染出来
