### ISSUE TITLE
[Build] [All] ，vue.config.js配置element-plus命名空间不生效

### ISSUE THREAD

**Issue by jianggangsheng** [element-plus/element-plus#14002]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.6`
- Browser / OS: `mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/115.0.0.0 safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL3Z1ZS5jb25maWcuanMiOiJjb25zdCB7IGRlZmluZUNvbmZpZyB9ID0gcmVxdWlyZShcIkB2dWUvY2xpLXNlcnZpY2VcIilcblxubW9kdWxlLmV4cG9ydHMgPSBkZWZpbmVDb25maWcoe1xuICBjc3M6IHtcbiAgICBsb2FkZXJPcHRpb25zOiB7XG4gICAgICBzYXNzOiB7XG4gICAgICAgIGFkZGl0aW9uYWxEYXRhOiBgQGltcG9ydCBcIi4vc3JjL3N0eWxlL2VsZW1lbnQvaW5kZXguc2Nzc1wiO2AsXG4gICAgICB9XG4gICAgfSxcbiAgfSxcbn0pXG5cblxuLy8gc2NzcyDphY3nva7lpoLkuItcblxuXG5AZm9yd2FyZCBcImVsZW1lbnQtcGx1cy90aGVtZS1jaGFsay9zcmMvbWl4aW5zL2NvbmZpZy5zY3NzXCIgd2l0aCAoXG4gICRuYW1lc3BhY2U6IFwiZXBcIlxuKTtcblxuXG4iLCJzcmMvbWFpbi5qcyI6ImltcG9ydCBcImVsZW1lbnQtcGx1cy9kaXN0L2luZGV4LmNzc1wiO1xuaW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSBcInZ1ZVwiXG5pbXBvcnQgQXBwIGZyb20gXCIuL0FwcC52dWVcIlxuY29uc3QgaW5zdGFuY2UgPSBjcmVhdGVBcHAoQXBwKVxuXG5pbXBvcnQgemhDbiBmcm9tIFwiZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qc1wiXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSBcImVsZW1lbnQtcGx1c1wiXG5cbmluc3RhbmNlLnVzZShFbGVtZW50UGx1cywge1xubG9jYWxlOiB6aENuLFxuc2l6ZTogXCJzbWFsbFwiLFxubmFtZXNwYWNlOiBcImVwXCIsXG59KSIsIl9vIjp7fX0=)

### Steps to reproduce

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL3Z1ZS5jb25maWcuanMiOiJjb25zdCB7IGRlZmluZUNvbmZpZyB9ID0gcmVxdWlyZShcIkB2dWUvY2xpLXNlcnZpY2VcIilcblxubW9kdWxlLmV4cG9ydHMgPSBkZWZpbmVDb25maWcoe1xuICBjc3M6IHtcbiAgICBsb2FkZXJPcHRpb25zOiB7XG4gICAgICBzYXNzOiB7XG4gICAgICAgIGFkZGl0aW9uYWxEYXRhOiBgQGltcG9ydCBcIi4vc3JjL3N0eWxlL2VsZW1lbnQvaW5kZXguc2Nzc1wiO2AsXG4gICAgICB9XG4gICAgfSxcbiAgfSxcbn0pXG5cblxuLy8gc2NzcyDphY3nva7lpoLkuItcblxuXG5AZm9yd2FyZCBcImVsZW1lbnQtcGx1cy90aGVtZS1jaGFsay9zcmMvbWl4aW5zL2NvbmZpZy5zY3NzXCIgd2l0aCAoXG4gICRuYW1lc3BhY2U6IFwiZXBcIlxuKTtcblxuXG4iLCJzcmMvbWFpbi5qcyI6ImltcG9ydCBcImVsZW1lbnQtcGx1cy9kaXN0L2luZGV4LmNzc1wiO1xuaW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSBcInZ1ZVwiXG5pbXBvcnQgQXBwIGZyb20gXCIuL0FwcC52dWVcIlxuY29uc3QgaW5zdGFuY2UgPSBjcmVhdGVBcHAoQXBwKVxuXG5pbXBvcnQgemhDbiBmcm9tIFwiZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qc1wiXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSBcImVsZW1lbnQtcGx1c1wiXG5cbmluc3RhbmNlLnVzZShFbGVtZW50UGx1cywge1xubG9jYWxlOiB6aENuLFxuc2l6ZTogXCJzbWFsbFwiLFxubmFtZXNwYWNlOiBcImVwXCIsXG59KSIsIl9vIjp7fX0=

### What is Expected?

可以修改element-plus成功

### What is actually happening?

html元素修改成功，样式没有生效

### Additional comments

_(empty)_

**Comment by btea** [comment]
You can refer to this template https://github.com/element-plus/element-plus-vite-starter.

**Comment by jianggangsheng** [comment]
> 您可以参考这个模板https://github.com/element-plus/element-plus-vite-starter。

这也不是vue.config.js的写法呀
