### ISSUE TITLE
[Component] [form, form-item] Bug: Unable to test form validations using vue-test-utils 

### ISSUE THREAD

**Issue by shubham-cpp** [element-plus/element-plus#14001]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Link](https://stackblitz.com/edit/github-wpbrk7?file=src%2Fcomponents%2F__tests__%2FApp.spec.ts)

### Steps to reproduce

1. create form with validation rules
2. Write test cases using vue test utils
3. Test cases are failing.

I've also raised a github issue on vue test utils. https://github.com/vuejs/test-utils/issues/2157

### What is Expected?

Should be able to test error messages for el-form

### What is actually happening?

Test cases are failing because element with class `.el-form-item__error` is never found

### Additional comments

I've provided a minimal example on stackblitz and also have similar issue on vue test-utils. 
But they said its issue with element-plus and not VTU.
Could you help me with finding a way.

**Comment by btea** [comment]
You can have a 300ms delay because `.el-form-item__error` has a 300ms transition.

![image](https://github.com/element-plus/element-plus/assets/24516654/e7f0a20a-9ab3-4073-9770-68ec43245883)

**Comment by shubham-cpp** [comment]
Yes thank you that's the solution
