### ISSUE TITLE
[Component] [tabs] [tabs] 数据变化后，dom没有更新

### ISSUE THREAD

**Issue by jiangzhenxiang** [element-plus/element-plus#14004]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgdHlwZT1cImJvcmRlci1jYXJkXCIgY2xhc3M9XCJkZW1vLXRhYnNcIj5cbiAgICA8ZWwtdGFiLXBhbmUgdi1mb3I9XCJpdGVtIGluIG1lbnVUYWJzXCI+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8c3BhbiBjbGFzcz1cImN1c3RvbS10YWJzLWxhYmVsXCI+XG4gICAgICAgICAgPGVsLWljb24+PGNhbGVuZGFyIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPnt7aXRlbS5sYWJlbH19PC9zcGFuPlxuICAgICAgICAgIDxlbC1iYWRnZSB2LWlmPVwiaXRlbS5zZWFyY2hOdW1cIiA6dmFsdWU9XCJpdGVtLnNlYXJjaE51bVwiIDptYXg9XCI5OVwiIC8+XG5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIFJvdXRlXG4gICAgPC9lbC10YWItcGFuZT5cblxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgQ2FsZW5kYXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IHsgcmVmLCBjb21wdXRlZCB9IGZyb20gJ3Z1ZSc7XG5jb25zdCBudW1iZXJBID0gcmVmKDApXG5cbmNvbnN0IG1lbnVUYWJzID0gY29tcHV0ZWQoKCkgPT4ge1xuICByZXR1cm4gW1xuICB7XG4gICAgbGFiZWw6ICdhYScsXG4gICAgc2VhcmNoTnVtOiBudW1iZXJBLnZhbHVlXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ2JiJyxcbiAgICBzZWFyY2hOdW06ICcyJ1xuICB9XG4gIF1cbn0pXG5cbnNldFRpbWVvdXQoKCkgPT4ge1xubnVtYmVyQS52YWx1ZSA9IDEwXG59LCAxMDAwKVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuLmRlbW8tdGFicyAuY3VzdG9tLXRhYnMtbGFiZWwgLmVsLWljb24ge1xuICB2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlO1xufVxuLmRlbW8tdGFicyAuY3VzdG9tLXRhYnMtbGFiZWwgc3BhbiB7XG4gIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7XG4gIG1hcmdpbi1sZWZ0OiA0cHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

数据更新后，tabs对应的dom没有更新。需要手动切换一下tab才更新。

### What is Expected?

期望数据更新后，tabs的dom立即更新

### What is actually happening?

期望数据更新后，tabs的dom没有立即更新

### Additional comments

示例代码
<template>
  <el-tabs type="border-card" class="demo-tabs">
    <el-tab-pane v-for="item in menuTabs">
      <template #label>
        <span class="custom-tabs-label">
          <el-icon><calendar /></el-icon>
          <span>{{item.label}}</span>
          <el-badge v-if="item.searchNum" :value="item.searchNum" :max="99" />

        </span>
      </template>
      Route
    </el-tab-pane>

  </el-tabs>
</template>

<script lang="ts" setup>
import { Calendar } from '@element-plus/icons-vue'

import { ref, computed } from 'vue';
const numberA = ref(0)

const menuTabs = computed(() => {
  return [
  {
    label: 'aa',
    searchNum: numberA.value
  },
  {
    label: 'bb',
    searchNum: '2'
  }
  ]
})

setTimeout(() => {
  numberA.value = 10
}, 1000)
</script>

**Comment by betavs** [comment]
```typescript
import { Calendar } from "@element-plus/icons-vue";

import { ref, computed, reactive } from "vue";
const numberA = ref(0);

const menuTabs = reactive([
  {
    label: "aa",
    searchNum: computed(() => numberA.value),
  },
  {
    label: "bb",
    searchNum: "2",
  },
]);

setTimeout(() => {
  numberA.value = 10;
}, 1000);
```

**Comment by jiangzhenxiang** [comment]
> ```ts
> import { Calendar } from "@element-plus/icons-vue";
> 
> import { ref, computed, reactive } from "vue";
> const numberA = ref(0);
> 
> const menuTabs = reactive([
>   {
>     label: "aa",
>     searchNum: computed(() => numberA.value),
>   },
>   {
>     label: "bb",
>     searchNum: "2",
>   },
> ]);
> 
> setTimeout(() => {
>   numberA.value = 10;
> }, 1000);
> ```

多谢，改为这种写法确实生效。不过这个问题的根本原因还是elementui的bug吧。同样的写法，在vue中是没有问题的。
[vue的复现demo](https://play.vuejs.org/#eNp9U8tu2zAQ/JUFL3IAW3aTmysbSIsc2kNatL6VPVDS2mEqkQIfqgtB/94l9XBeiA4CuTOznN0lO3bbNGnrkW1ZZgsjGwcWnW/2XHEl60YbBx0YPC6h0HXjHZbQw9HoGhKSJR+5KrSyDpSvczS3sAvkxeYq6AekRuUPIrcETSkWiyvY7aHjCojuvFHwK6xjAKASOVZbSIRIlkPEojDFw72vt9NBaSsqjwHtI+eFNM/fkCbXSRSE32+u+miSyj3IGrV3F1fPziDfHzbEXsL1ZhMKy9ZDp2KPMod1UwmHtAPIStmC+9fgjrNcmxLNqhCm5AyKSlhL0RJrvXLUDs6iYtS0q6M2BEtKB1LNTYusgTd8mW2E2nddIKax2r4nQyH4ikZZ5XFMms59IDOTfo49yTGaWpOrcTets/VcK1syZ2m8R3lKH61WdH3iADgLI5YVmm+NkzR+zrbTaDgTVaX/fo0xZzyOAyLNAxZ/3og/2nOIcfbdoEXTImcz5oQ5oRvgu5/3eKb1DNa69BWx3wF/oNWVDx4H2ievSrL9hBfdfolPQKrTwd6dHSo7FRWMXm4fZ/QYPr9T+sXuTXozXsKe9f8BtmAkmg==)

**Comment by G1King** [comment]
目前还有这种问题

**Comment by favorite58** [comment]
这个bug在2.2.2版本是好的，后面我动态for循环渲染tabs项出现了顺序不一致的问题，就升级到2.2.18，label插槽数据不及时更新的问题又出现了，无语
