### ISSUE TITLE
[Component] [dialog] el-dialog设置modal=false无效，设置了append-to-body，背景仍然无法点击

### ISSUE THREAD

**Issue by jing-ge-star** [element-plus/element-plus#14013]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues/new/choose)

### Steps to reproduce

```
<el-dialog el-drag-dialog width="70%" :modal="false" :append-to-body="true" draggable destroy-on-close :lock-scroll="false"
             :title="dialog.title" center align-center v-model="dialog.visible">
    对话框内容
  </el-dialog>
```

### What is Expected?

背景可点击

### What is actually happening?

背景不可点击

### Additional comments

_(empty)_

**Comment by jing-ge-star** [comment]
代码：

**Comment by kaine0923** [comment]
[ElementPlus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgY2VudGVyRGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiY2VudGVyRGlhbG9nVmlzaWJsZSA9IHRydWVcIj5cbiAgICBDbGljayB0byBvcGVuIHRoZSBEaWFsb2dcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiY2VudGVyRGlhbG9nVmlzaWJsZVwiIDptb2RhbD1cImZhbHNlXCIgdGl0bGU9XCJXYXJuaW5nXCIgd2lkdGg9XCIzMCVcIiBjZW50ZXI+XG4gICAgPHNwYW4+XG4gICAgICBJdCBzaG91bGQgYmUgbm90ZWQgdGhhdCB0aGUgY29udGVudCB3aWxsIG5vdCBiZSBhbGlnbmVkIGluIGNlbnRlciBieVxuICAgICAgZGVmYXVsdFxuICAgIDwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNlbnRlckRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiY2VudGVyRGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+XG4gICAgICAgICAgQ29uZmlybVxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

我猜你想表达的意思是设置了`modal`属性为false, 虽然背景的mask不显示了，但是还是有元素沾满了整个窗口，阻止其他的操作触发。比如我就无法在dialog显示的情况下直接点击input输入

**Comment by JSeasy** [comment]
is this as a bug？ it seems this was a expect behavior

**Comment by nothing-sy** [comment]
use css prop: pointer-events to solve it.  
set  .el-dialog pointer-events to 'auto'  and set it's div parents to 'none'
it work for me!
