### ISSUE TITLE
[upload] Upload上传组件的照片墙，预览图片的方法多了一个!

### ISSUE THREAD

**Issue by RanGuMo** [element-plus/element-plus#14018]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome/115.0.0.0`
- Build Tool: `Webpack`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/upload.html#%E7%85%A7%E7%89%87%E5%A2%99)

### Steps to reproduce

https://element-plus.org/zh-CN/component/upload.html#%E7%85%A7%E7%89%87%E5%A2%99

### What is Expected?

dialogImageUrl.value = uploadFile.url

### What is actually happening?

dialogImageUrl.value = uploadFile.url!

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
<img width="915" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/3cb9a1db-038b-4745-b1d3-803dd2520fef">

**Comment by yj-liuzepeng** [comment]
<img width="690" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/09d4a635-2d1c-465f-ab00-d4c690fb1660">

**Comment by RanGuMo** [comment]
了解了，因为我没有用到ts写法，直接拷贝，以为是bug，非常抱歉
