### ISSUE TITLE
[Component] [table] Table Sort fails when sorting percentage strings

### ISSUE THREAD

**Issue by rynokins** [element-plus/element-plus#14010]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIDpkZWZhdWx0LXNvcnQ9XCJ7IHByb3A6ICdwZXJjZW50YWdlJywgb3JkZXI6ICdkZXNjZW5kaW5nJyB9XCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInBlcmNlbnRhZ2VcIiBsYWJlbD1cIlBlcmNlbnRcIiBzb3J0YWJsZSAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cblxuaW50ZXJmYWNlIFBlcmNlbnRhZ2VUZXN0IHtcbiAgcGVyY2VudGFnZTogc3RyaW5nXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogUGVyY2VudGFnZVRlc3RbXSA9IFtcbiAge1xuICAgIHBlcmNlbnRhZ2U6ICc4MCUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnOCUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnMSUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnMTAwJSdcbiAgfSxcbiAge1xuICAgIHBlcmNlbnRhZ2U6ICcyMDAlJ1xuICB9LFxuICB7XG4gICAgcGVyY2VudGFnZTogJzEwJSdcbiAgfSxcbiAge1xuICAgIHBlcmNlbnRhZ2U6ICc2MCUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnMjAlJ1xuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Populate column with percentage strings of any range, ensure that some of them are multiples of 10.

### What is Expected?

Strings should sort in numerical order.

### What is actually happening?

Strings containing zeros are sorted after their associated 1-9 number, eg. '20%' is ordered next to '2%'.

### Additional comments

_(empty)_

**Comment by kaine0923** [comment]
Maybe u need [sort-method](https://element-plus.org/en-US/component/table.html#table-column-attributes)

**Comment by btea** [comment]
Added an [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIDpkZWZhdWx0LXNvcnQ9XCJ7IHByb3A6ICdwZXJjZW50YWdlJywgb3JkZXI6ICdkZXNjZW5kaW5nJyB9XCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInBlcmNlbnRhZ2VcIiBsYWJlbD1cIlBlcmNlbnRcIiBzb3J0YWJsZSA6c29ydC1tZXRob2Q9XCJzb3J0TWV0aG9kXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5cbmludGVyZmFjZSBQZXJjZW50YWdlVGVzdCB7XG4gIHBlcmNlbnRhZ2U6IHN0cmluZ1xufVxuXG5jb25zdCB0YWJsZURhdGE6IFBlcmNlbnRhZ2VUZXN0W10gPSBbXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnODAlJ1xuICB9LFxuICB7XG4gICAgcGVyY2VudGFnZTogJzglJ1xuICB9LFxuICB7XG4gICAgcGVyY2VudGFnZTogJzElJ1xuICB9LFxuICB7XG4gICAgcGVyY2VudGFnZTogJzEwMCUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnMjAwJSdcbiAgfSxcbiAge1xuICAgIHBlcmNlbnRhZ2U6ICcxMCUnXG4gIH0sXG4gIHtcbiAgICBwZXJjZW50YWdlOiAnNjAlJ1xuICB9LFxuICB7XG4gICAgcGVyY2VudGFnZTogJzIwJSdcbiAgfSxcbl1cblxuY29uc3Qgc29ydE1ldGhvZCA9IChhLCBiKSA9PiB7XG4gIHJldHVybiBwYXJzZUludChhLnBlcmNlbnRhZ2UpIC0gcGFyc2VJbnQoYi5wZXJjZW50YWdlKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319) for reference based on @kaine0923 's comment.

**Comment by rynokins** [comment]
Thank you both! I can report that [sort-method](url) works without `sort` being set on columns, so one can build external sort options [like so](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInNvcnRUeXBlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIEBjaGFuZ2U9XCJzb3J0QnlcIlxuICAgICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICAgIHYtZm9yPVwic29ydCBpbiBzb3J0T3B0aW9uc1wiXG4gICAgICAgICAgOmtleT1cInNvcnQudmFsdWVcIlxuICAgICAgICAgIDpsYWJlbD1cInNvcnQubGFiZWxcIlxuICAgICAgICAgIDp2YWx1ZT1cInNvcnQudmFsdWVcIlxuICAgICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxlbC10YWJsZVxuICAgIHJlZj1cInRhYmxlUmVmXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbHBoYWJldGljYWxcIiBsYWJlbD1cIkxldHRlclwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwicGVyY2VudGFnZVwiIGxhYmVsPVwiUGVyY2VudFwiIDpzb3J0LW1ldGhvZD1cInNvcnRNZXRob2RcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cblxuaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgVGFibGVJbnN0YW5jZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW50ZXJmYWNlIFBlcmNlbnRhZ2VUZXN0IHtcbiAgYWxwaGFiZXRpY2FsOiBzdHJpbmdcbiAgcGVyY2VudGFnZTogc3RyaW5nXG59XG5cbmNvbnN0IHRhYmxlRGF0YTogUGVyY2VudGFnZVRlc3RbXSA9IFtcbiAge1xuICAgIGFscGhhYmV0aWNhbDogJ2InLFxuICAgIHBlcmNlbnRhZ2U6ICc4MCUnXG4gIH0sXG4gIHtcbiAgICBhbHBoYWJldGljYWw6ICd6JyxcbiAgICBwZXJjZW50YWdlOiAnOCUnXG4gIH0sXG4gIHtcbiAgICBhbHBoYWJldGljYWw6ICdxJyxcbiAgICBwZXJjZW50YWdlOiAnMSUnXG4gIH0sXG4gIHtcbiAgICBhbHBoYWJldGljYWw6ICdzJyxcbiAgICBwZXJjZW50YWdlOiAnMTAwJSdcbiAgfSxcbiAge1xuICAgIGFscGhhYmV0aWNhbDogJ2MnLFxuICAgIHBlcmNlbnRhZ2U6ICcyMDAlJ1xuICB9LFxuICB7XG4gICAgYWxwaGFiZXRpY2FsOiAnbicsXG4gICAgcGVyY2VudGFnZTogJzEwJSdcbiAgfSxcbiAge1xuICAgIGFscGhhYmV0aWNhbDogJ2UnLFxuICAgIHBlcmNlbnRhZ2U6ICc2MCUnXG4gIH0sXG4gIHtcbiAgICBhbHBoYWJldGljYWw6ICdhJyxcbiAgICBwZXJjZW50YWdlOiAnMjAlJ1xuICB9XG5dXG5cbmNvbnN0IHRhYmxlUmVmID0gcmVmPFRhYmxlSW5zdGFuY2U+KClcblxuZnVuY3Rpb24gc29ydEJ5KCB0eXBlOnN0cmluZyApe1xuICB0YWJsZVJlZi52YWx1ZT8uc29ydCh0eXBlLCAnZGVzY2VuZGluZycpXG59XG5cbmNvbnN0IHNvcnRUeXBlID0gcmVmKCcnKVxuXG5jb25zdCBzb3J0TWV0aG9kID0gKGE6YW55LCBiOmFueSkgPT4ge1xuICByZXR1cm4gcGFyc2VJbnQoYS5wZXJjZW50YWdlKSAtIHBhcnNlSW50KGIucGVyY2VudGFnZSlcbn1cblxuY29uc3Qgc29ydE9wdGlvbnMgPSByZWYoW1xuICB7IGxhYmVsOiAnQWxwaGFiZXRpY2FsJywgdmFsdWU6ICdhbHBoYWJldGljYWwnIH0sXG4gIHsgbGFiZWw6ICdQZXJjZW50YWdlJywgdmFsdWU6ICdwZXJjZW50YWdlJyB9XG5dKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319) - which is exactly what I needed.
