### ISSUE TITLE
[Component] [All] <el-select-v2 /> 数据选择时，最底层的数据初次无法选中

### ISSUE THREAD

**Issue by zoukai930225** [element-plus/element-plus#14023]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome/116.0.5845.96`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select-v2.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

无

### What is Expected?

初次点击即可选中

### What is actually happening?

初次点击即可选中

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
文档没有复现 🤔️

![test](https://github.com/element-plus/element-plus/assets/75007029/6f1afae7-8ea4-4263-85ae-64beae9b3b49)
