### ISSUE TITLE
[Component] [date-picker]时间选择框多出一些文字

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#14031]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `chrome115`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdmFsdWUxID0gcmVmKFwiXCIpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICBmb3JtYXQ9XCJZWVlZ5bm0TU3mnIhEROaXpSBISDptbTpzc1wiXG4gICAgPlxuICAgIDwvZWwtZGF0ZS1waWNrZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

打开就能看到

### What is Expected?

弹出选择的日期，时间选择没有多余的“日”字

### What is actually happening?

弹出选择的日期，时间选择有多余的“日”字

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/14806813/fe75592b-c255-4090-98e3-02118c355000)
element-ui也存在这个问题

**Comment by ViLi230** [comment]
我也遇到了同样的问题

**Comment by ViLi230** [comment]
我也遇到了同样的问题
![208e09d585ca78bee688b879e9a86b1](https://github.com/element-plus/element-plus/assets/44049799/2545c2ac-fc96-40d0-8b58-151ad1723d51)

**Comment by ViLi230** [comment]
https://codesandbox.io/s/elementui-playground-forked-chggr4?file=/src/App.vue

**Comment by yj-liuzepeng** [comment]
duplicate https://github.com/element-plus/element-plus/issues/11465

**Comment by tolking** [comment]
Fixed by #14330 

You can now modify the format through `dateFormat` and `timeFormat` attributes
