### ISSUE TITLE
[Component] [select] select has inline style let custom sass setting invalid

### ISSUE THREAD

**Issue by zhao1995chen** [element-plus/element-plus#14038]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome 115.0.5790.170 / MacOS 13.4.1`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUsIGNvbXB1dGVkLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxudHlwZSBTaXplID0gXCJzbWFsbFwiIHwgXCJkZWZhdWx0XCIgfCBcImxhcmdlXCJcbmNvbnN0IHNpemUgPSByZWY8U2l6ZT4oJ2RlZmF1bHQnKVxuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICByZWdpb246ICcnLFxufSlcblxuLyoqIFRoZSBmb2xsb3dpbmcgaXMgdGhlIHNldHRpbmcgSSBwdXQgaW4gaW5kZXguc2Nzc1xuQHVzZSAnc2FzczptYXAnO1xuQHVzZSAnZWxlbWVudC1wbHVzL3RoZW1lLWNoYWxrL3NyYy9taXhpbnMvZnVuY3Rpb24uc2NzcycgYXMgKjtcblxuQGZvcndhcmQgJ2VsZW1lbnQtcGx1cy90aGVtZS1jaGFsay9zcmMvY29tbW9uL3Zhci5zY3NzJyB3aXRoIChcbiAgJGNvbW1vbi1jb21wb25lbnQtc2l6ZTogKFxuICAgICdsYXJnZSc6IDUwcHgsXG4gICAgJ2RlZmF1bHQnOiAzMHB4LFxuICAgICdzbWFsbCc6IDEwcHgsXG4gICksXG4pO1xuKi9cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L2gxPlxuIDxlbC1kaXZpZGVyPjwvZWwtZGl2aWRlcj5cbiAgPHA+Q09NUE9ORU5UIE9QVElPTlM8L3A+XG4gIDxlbC1mb3JtIGxhYmVsLXdpZHRoPVwiODBweFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJTaXplXCIgY2xhc3M9XCJmbGV4IGl0ZW1zLWNlbnRlclwiPlxuICAgICAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJzaXplXCI+XG4gICAgICAgIDxlbC1yYWRpbyBsYWJlbD1cInNtYWxsXCI+U21hbGw8L2VsLXJhZGlvPlxuICAgICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJkZWZhdWx0XCI+RGVmYXVsdDwvZWwtcmFkaW8+XG4gICAgICAgIDxlbC1yYWRpbyBsYWJlbD1cImxhcmdlXCI+TGFyZ2U8L2VsLXJhZGlvPlxuICAgICAgPC9lbC1yYWRpby1ncm91cD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuICA8ZWwtZGl2aWRlcj48L2VsLWRpdmlkZXI+XG4gIDxwPkdpdmUgc2l6ZSBieSBlbC1mb3JtLjwvcD5cbiAgPGVsLWZvcm1cbiAgICA6bW9kZWw9XCJmb3JtXCJcbiAgICBsYWJlbC13aWR0aD1cIjE2MHB4XCJcbiAgICA6c2l6ZT1cInNpemVcIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IHpvbmVcIj5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJwbGVhc2Ugc2VsZWN0IHlvdXIgem9uZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIDxlbC1kaXZpZGVyPjwvZWwtZGl2aWRlcj5cbiAgPHA+R2l2ZSBzaXplIGJ5IGVsLWZvcm0taXRlbS48L3A+XG4gIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCIgOnNpemU9XCJzaXplXCI+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwiZm9ybS5yZWdpb25cIiBwbGFjZWhvbGRlcj1cInBsZWFzZSBzZWxlY3QgeW91ciB6b25lXCI+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZWwtZm9ybS1pdGVtPlxuICA8ZWwtZGl2aWRlcj48L2VsLWRpdmlkZXI+XG4gIDxwPkdpdmUgc2l6ZSBieSBlbC1zZWxlY3QuPC9wPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwicGxlYXNlIHNlbGVjdCB5b3VyIHpvbmVcIiA6c2l6ZT1cInNpemVcIj5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSB0d29cIiB2YWx1ZT1cImJlaWppbmdcIiAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

- Use the recommended way to set your custom height for select in index.scss file. e.g. small is 10px, default is 30px, large is 50px.
- Change component size by options.

### What is Expected?

select component could change the size by the custom setting in index.scss file.

### What is actually happening?

Custom setting will be overwritten by inline style but not the custom setting.

### Additional comments

_(empty)_

**Comment by kamesan012** [comment]
![image](https://github.com/element-plus/element-plus/assets/79386745/ab506b22-c899-43c2-8d3f-625077e11877)
![image](https://github.com/element-plus/element-plus/assets/79386745/651fe767-38d8-4200-aeec-dd3e04c0734b)
It does use the css variable. Check your index.scss file or the way you set it.

**Comment by zhao1995chen** [comment]
Since I'm not sure how to add index.scss on the playground, this is another link to reproduce the bug.
Please check it out, thanks.

## Reproduction

### Related Component

- `el-select`

### Reproduction Link

[codesandbox](https://codesandbox.io/p/sandbox/component-select-select-has-inline-style-let-custom-sass-setting-invalid-14038-6d28nd?welcome=true)

### Steps to reproduce

Same as above.

### What is Expected?

Same as above.

### What is actually happening?

Same as above.

![image](https://github.com/element-plus/element-plus/assets/53460349/e6847792-98be-49ec-b19d-261dca60223c)

When I use this online editor, after the first change is workable, other custom settings will be overwritten by the first inline style but not the custom setting.

At my local server, each el-select will be overwritten by themselves inline style but not the custom setting.

### Additional comments

_(empty)_

**Comment by zhao1995chen** [comment]
This is the demo on my local server.
Please check it out, thanks.

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.10`
- Browser / OS: `Chrome 116.0.5845.110 / MacOS 13.4.1`
- Build Tool: `Vite`

## Reproduction

### Related Component

- `el-select`

### Reproduction Link

[Demo](https://zhao1995chen.github.io/el-select-error-demo/)

### Steps to reproduce

Same as above.

### What is Expected?

Same as above.

### What is actually happening?

Same as above.

![image](https://github.com/element-plus/element-plus/assets/53460349/cb56c6ca-8c44-4d22-9541-760e8b5865d0)

At my local server, each el-select will be overwritten by themselves inline style but not the custom setting.

### Additional comments

_(empty)_

**Comment by kamesan012** [comment]
Can you provide a git repostiry url? I may find the problem, but still need to verify.

**Comment by zhao1995chen** [comment]
Sure.
Please check it out.
 [el-select-error-demo repository](https://github.com/zhao1995chen/el-select-error-demo)

**Comment by kamesan012** [comment]
> When I use this online editor, after the first change is workable, other custom settings will be overwritten by the first inline style but not the custom setting.
I feel confused about it too.

**Comment by zhao1995chen** [comment]
> When I use this online editor, after the first change is workable, other custom settings will be overwritten by the first inline style but not the custom setting.
> I feel confused about it too.

When I used the same version settings as the online editor, I found the problem showed up just like the online editor situation.
Need I provide the demo environment for you again to debug?

**Comment by zhao1995chen** [comment]
> When I used the same version settings as the online editor, I found the problem showed up just like the online editor situation.
> Need I provide the demo environment for you again to debug?

I just published using element-plus@2.3.1 & vue@3.2.47. 
I found that no matter whether I use vue@3.2.47 or vue@3.3.4 could show the problem.
So maybe it is the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes the problem.

[Demo](https://zhao1995chen.github.io/el-select-error-demo/)

**Comment by kamesan012** [comment]
> > When I used the same version settings as the online editor, I found the problem showed up just like the online editor situation.
> > Need I provide the demo environment for you again to debug?
> 
> I just published using element-plus@2.3.1 & vue@3.2.47. I found that no matter whether I use vue@3.2.47 or vue@3.3.4 could show the problem. So maybe it is the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes the problem.
> 
> [Demo](https://zhao1995chen.github.io/el-select-error-demo/)

Select componet use the fixed value to change the inline style, maybe this is the reason for this issue.

**Comment by zhao1995chen** [comment]
> > > When I used the same version settings as the online editor, I found the problem showed up just like the online editor situation.
> > > Need I provide the demo environment for you again to debug?
> > 
> > 
> > I just published using element-plus@2.3.1 & vue@3.2.47. I found that no matter whether I use vue@3.2.47 or vue@3.3.4 could show the problem. So maybe it is the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes the problem.
> > [Demo](https://zhao1995chen.github.io/el-select-error-demo/)
> 
> Select componet use the fixed value to change the inline style, maybe this is the reason for this issue.

I mean that is why CodeSandbox produces the different result beyond my local environment.
It seems to be the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes when I use CodeSandbox, after the first change is workable, other custom settings will be overwritten by the first inline style but not the custom setting.

**Comment by kamesan012** [comment]
> > > > When I used the same version settings as the online editor, I found the problem showed up just like the online editor situation.
> > > > Need I provide the demo environment for you again to debug?
> > > 
> > > 
> > > I just published using element-plus@2.3.1 & vue@3.2.47. I found that no matter whether I use vue@3.2.47 or vue@3.3.4 could show the problem. So maybe it is the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes the problem.
> > > [Demo](https://zhao1995chen.github.io/el-select-error-demo/)
> > 
> > 
> > Select componet use the fixed value to change the inline style, maybe this is the reason for this issue.
> 
> I mean that is why CodeSandbox produces the different result beyond my local environment. It seems to be the difference between element-plus@2.3.1 & element-plus@2.3.10 that makes when I use CodeSandbox, after the first change is workable, other custom settings will be overwritten by the first inline style but not the custom setting.

I have seen same the file in 2.3.1, it didn't changed, maybe the behavior is a bug from another file.

**Comment by zhao1995chen** [comment]
After tracing the problem, I found that the problem was reported #11962 five months ago, appeared until v2.3.3, and was fixed on v2.3.4(#11973).

<img width="733" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/0dadaee7-4bad-4d60-b928-f02378b909e3">

<img width="1384" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/3aededfa-0e51-4bb8-843e-a59d88014097">

That's why they have different behavior.

**Comment by kamesan012** [comment]
> After tracing the problem, I found that the problem was reported #11962 five months ago, appeared until v2.3.3, and was fixed on v2.3.4(#11973).
> 
> <img alt="image" width="733" src="https://user-images.githubusercontent.com/53460349/263462780-0dadaee7-4bad-4d60-b928-f02378b909e3.png"> <img alt="image" width="1384" src="https://user-images.githubusercontent.com/53460349/263462984-3aededfa-0e51-4bb8-843e-a59d88014097.png">
> That's why they have different behavior.

Hahaha, I'm still confused why when you first change the size, the inline style height is correct. The value gotSize use three fixed value.

**Comment by zhao1995chen** [comment]
First change? Actually, it is also incorrect in my reproduction, but the style setting after rendering didn't have any inline style is correct.
I just added test cases in README.md and changed the value for `large`, `default`, and `small` to bigger to make observation more intuitive.
