### ISSUE TITLE
[Bug Report] timepicker triggers 'change' scrolling for each scrolling in h/min/sec. Documentation: it should  triggers when user confirms the value  

### ISSUE THREAD

**Issue by wotamann** [element-plus/element-plus#1404]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
WIN 10 / Chrome || FF latest

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/a3uc8or4/

### Steps to reproduce
set up 

<el-time-picker valueModel="value" @change="value = $event" ></el-time-picker>

and watch fireing 'change' event on each change of h/min/sec and not only on confirmation

### What is Expected?
documentation writes 'change triggers when user confirms the value' 
 It would be nice to have an event only on confirmation 

Thanks for your work and creating Elements-Plus, it is a super UI-Framework

### What is actually happening?

Any change of sec/min/hour in timepicker send an change event, instead only on confirmation with 'Ok'.

**Comment by zazzaz** [comment]
will fix soon
