### ISSUE TITLE
[Component] [pagination] toplayer全屏模式下分页下拉框无法显示

### ISSUE THREAD

**Issue by boomboy4** [element-plus/element-plus#14070]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.3.9`
- Browser / OS: `chrome 116.0.5845.110`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBwYWdlc2l6ZSA9IHJlZigxMClcbmNvbnN0IGN1cnJlbnRQYWdlID0gcmVmKDEpXG5jb25zdCBmdWxsc2NyZWVuID0gKGVsZW1lbnQpPT4ge1xuICBpZiAoZG9jdW1lbnQubW96RnVsbFNjcmVlbkVuYWJsZWQpIHtcbiAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwi5YWo5bGP5qih5byP6KKr56aB55SoXCIpKTtcbiAgfVxuICBsZXQgcmVzdWx0ID0gbnVsbDtcbiAgaWYgKGVsZW1lbnQucmVxdWVzdEZ1bGxzY3JlZW4pIHtcbiAgICByZXN1bHQgPSBlbGVtZW50LnJlcXVlc3RGdWxsc2NyZWVuKCk7XG4gIH0gZWxzZSBpZiAoZWxlbWVudC5tb3pSZXF1ZXN0RnVsbFNjcmVlbikge1xuICAgIHJlc3VsdCA9IGVsZW1lbnQubW96UmVxdWVzdEZ1bGxTY3JlZW4oKTtcbiAgfSBlbHNlIGlmIChlbGVtZW50Lm1zUmVxdWVzdEZ1bGxzY3JlZW4pIHtcbiAgICByZXN1bHQgPSBlbGVtZW50Lm1zUmVxdWVzdEZ1bGxzY3JlZW4oKTtcbiAgfSBlbHNlIGlmIChlbGVtZW50LndlYmtpdFJlcXVlc3RGdWxsc2NyZWVuKSB7XG4gICAgcmVzdWx0ID0gZWxlbWVudC53ZWJraXRSZXF1ZXN0RnVsbFNjcmVlbigpO1xuICB9XG4gIHJldHVybiByZXN1bHQgfHwgUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwi5LiN5pSv5oyB5YWo5bGPXCIpKTtcbn1cbmNvbnN0IGRvbSA9IHJlZignZG9tJylcbmNvbnN0IHRvZ2dsZUZ1bGxzY3JlZW4gPSAoKT0+e1xuICBmdWxsc2NyZWVuKGRvbS52YWx1ZSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuIFxuICA8ZGl2IHJlZj1cImRvbVwiPlxuICAgIDxlbC1idXR0b24gdHlwZT0ncHJpbWFyeScgQGNsaWNrPVwidG9nZ2xlRnVsbHNjcmVlblwiPiBmdWxsc2NyZWVuIDwvZWwtYnV0dG9uPlxuICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgICA8ZWwtcGFnaW5hdGlvblxuICAgICAgYmFja2dyb3VuZFxuICAgICAgOnBhZ2Utc2l6ZXM9XCJbMTAsIDIwLCA1MCwgODAsIDEwMF1cIlxuICAgICAgdi1tb2RlbDpwYWdlLXNpemU9XCJwYWdlc2l6ZVwiXG4gICAgICB2LW1vZGVsOmN1cnJlbnQtcGFnZT1cImN1cnJlbnRQYWdlXCJcbiAgICAgIGxheW91dD1cInRvdGFsLCBwcmV2LCBwYWdlciwgbmV4dCwgc2l6ZXMsIGp1bXBlclwiXG4gICAgICA6dG90YWw9XCIyMFwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击fullscreen按钮
2. 点击分页size选择器

### What is Expected?

显示size下拉框选项

### What is actually happening?

不显示size下拉框选项

### Additional comments

_(empty)_

**Comment by LQ6666666** [comment]
分页数的 `Select` 插在 `Body` 上，不在要全屏的 `DOM` 下层
![image](https://github.com/element-plus/element-plus/assets/64238945/453c59d8-71e5-4649-8247-318a24d32438)
源码修改增加`teleported` 为 `false` 可以解决，不知道合不合适
![image](https://github.com/element-plus/element-plus/assets/64238945/54a03fb8-fabb-40af-9023-5d4f332cbe77)

**Comment by boomboy4** [comment]
已提交pr 我觉得在不影响现状情况下 添加teleported参数 默认为true最好 用户可以根据自己需求选择是否插入body
