### ISSUE TITLE
[Performance] [table-v2] Virtualized Table 虚拟化表格建议饿了么开除写这个的员工 从头写吧 

### ISSUE THREAD

**Issue by qq2356231203** [element-plus/element-plus#14085]
这个虚拟化表格就是个死妈的玩意儿 手机平板 全部卡死 滚动条滚不动 害我研究半天以为是自己的问题 打开官网 我你妹 官网的demo也卡死 饿了么这么大以公司不知道哪里招的这么烂的程序员 写这么烂

## Details

这个虚拟化表格就是个死妈的玩意儿 手机平板 全部卡死 滚动条滚不动 害我研究半天以为是自己的问题 打开官网 我你妹 官网的demo也卡死 饿了么这么大以公司不知道哪里招的这么烂的程序员 写这么烂

## Description

这个虚拟化表格就是个死妈的玩意儿 手机平板 全部卡死 滚动条滚不动 害我研究半天以为是自己的问题 打开官网 我你妹 官网的demo也卡死 饿了么这么大以公司不知道哪里招的这么烂的程序员 写这么烂

### Additional comments

这个虚拟化表格就是个死妈的玩意儿 手机平板 全部卡死 滚动条滚不动 害我研究半天以为是自己的问题 打开官网 我你妹 官网的demo也卡死 饿了么这么大以公司不知道哪里招的这么烂的程序员 写这么烂

**Comment by qq2356231203** [comment]
https://element-plus.org/zh-CN/component/table-v2.html  自己去看  发布这么久这么严重的bug发现不了  KPI绩效不要了是吧  真TMD给饿了么抹黑

**Comment by kaine0923** [comment]
这个组件目前还是处于beta阶段，建议你多提有效issue和pr
