### ISSUE TITLE
[Component] [date-picker] DatePicker 日期選擇器預設時間沒有作用

### ISSUE THREAD

**Issue by chrislitw** [element-plus/element-plus#14094]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Chrome/116.0.0.0 / Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker.html#%E9%BB%98%E8%AE%A4%E5%80%BC)

### Steps to reproduce

1. 在 el-date-picker 加上 default-value

### What is Expected?

會顯示預設時間

### What is actually happening?

沒有顯示預設時間

### Additional comments

官網的範例也沒有顯示預設時間

**Comment by xu-L** [comment]
用v-model进行赋值呢？？    请确认交互数据的格式 使用format定义
`  <el-date-picker
        v-model="value1"
        type="date"
        placeholder="Pick a Date"
        format="YYYY/MM/DD"
      />`

**Comment by kamesan012** [comment]
default-value只影响点击日期选择器后显示的日期范围，例子中显示的为2010年10月的日期范围，如不选择就应该是当前时间的日期范围，应该只是描述有歧义，如果要设置显示的预设时间，请修改v-model的绑定值。
