### ISSUE TITLE
[Component] [upload] Upload 组件手动上传调用 submit 无效

### ISSUE THREAD

**Issue by tantaiMoon** [element-plus/element-plus#14122]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chrome 116.0.5845.96/Macos 13.5.1`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/button.html#%E6%89%8B%E5%8A%A8%E4%B8%8A%E4%BC%A0)

### Steps to reproduce

点击 upload to server 按钮无反应

### What is Expected?

upload to server 点击后弹出文件选择框

### What is actually happening?

点击无反应

### Additional comments

_(empty)_

**Comment by zhao1995chen** [comment]
IMO, this bug maybe reperent in this case.

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Chrome 116.0.5845.110 / MacOS 13.4.1`

## Reproduction

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIHJlZj1cInVwbG9hZFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6bGltaXQ9XCIxXCJcbiAgICA6b24tZXhjZWVkPVwiaGFuZGxlRXhjZWVkXCJcbiAgICA6YXV0by11cGxvYWQ9XCJmYWxzZVwiXG4gID5cbiAgICA8dGVtcGxhdGUgI3RyaWdnZXI+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+c2VsZWN0IGZpbGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1idXR0b24gY2xhc3M9XCJtbC0zXCIgdHlwZT1cInN1Y2Nlc3NcIiBAY2xpY2s9XCJzdWJtaXRVcGxvYWRcIj5cbiAgICAgIHVwbG9hZCB0byBzZXJ2ZXJcbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI3RpcD5cbiAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RpcCB0ZXh0LXJlZFwiPlxuICAgICAgICBsaW1pdCAxIGZpbGUsIG5ldyBmaWxlIHdpbGwgY292ZXIgdGhlIG9sZCBmaWxlXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBnZW5GaWxlSWQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSB7IFVwbG9hZEluc3RhbmNlLCBVcGxvYWRQcm9wcywgVXBsb2FkUmF3RmlsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgdXBsb2FkID0gcmVmPFVwbG9hZEluc3RhbmNlPigpXG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMpID0+IHtcbiAgdXBsb2FkLnZhbHVlIS5jbGVhckZpbGVzKClcbiAgY29uc3QgZmlsZSA9IGZpbGVzWzBdIGFzIFVwbG9hZFJhd0ZpbGVcbiAgZmlsZS51aWQgPSBnZW5GaWxlSWQoKVxuICB1cGxvYWQudmFsdWUhLmhhbmRsZVN0YXJ0KGZpbGUpXG59XG5cbmNvbnN0IHN1Ym1pdFVwbG9hZCA9ICgpID0+IHtcbiAgdXBsb2FkLnZhbHVlIS5zdWJtaXQoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

> Use [official example code](https://element-plus.org/en-US/component/upload.html#cover-previous-file) could find it out.
- Click `select file` button to select a file to upload.
- Click `upload to server` button.

### What is Expected?

API POST success.

### What is actually happening?

API POST returns `503` CORS error.

<img width="715" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/443d852a-7e9f-44a5-b6eb-eabfe588c24b">

<img width="443" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/f1670c71-ef30-493b-8723-90ed48fd459e">

<img width="548" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/33aced05-ee03-40df-b522-e8a54b7bc2a1">

**Comment by HeftyKoo** [comment]
这个是因为上传的文件太大了，mocky 作为免费的服务对请求大小做了限制
