### ISSUE TITLE
[Bug Report] vue props warning when passing VNode as message to ElMessageBox

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1412]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
mac

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973????

### Steps to reproduce
vue props warning when passing VNode as message to ElMessageBox

``` tsx
ElMessageBox({
  title: '',
  message: (
    <div class="common-error-handler">
      { renderErrorSection('请求出现错误, 请稍后重试, 错误内容:') }
      { renderErrorContent(errorContent) }
      { renderErrorSection('错误上下文信息:') }
      { renderErrorContent(ctxContent) }
    </div>
  ) as VNode,
  confirmButtonText: '确定',
});
```

### What is Expected?
no warning.

### What is actually happening?
-

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/106454411-aa188280-64c5-11eb-8cf0-68067ecfc815.png)

**Comment by Ryan2128** [comment]
Which of tempalte and jsx/tsx are you using?

**Comment by Ryan2128** [comment]
Is the `message` of MessageBox rendered correctly?

**Comment by eczn** [comment]
> Is the `message` of MessageBox rendered correctly?

it works


> Which of tempalte and jsx/tsx are you using?

vue jsx-next ?

**Comment by Ryan2128** [comment]
Will fix soon.
