### ISSUE TITLE
[Component] [menu, menu-item] 按需自动加载下自定义命名空间，webpack构建的工程menu组件样式会丢失

### ISSUE THREAD

**Issue by pekonchan** [element-plus/element-plus#14148]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.12`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-menu`
- `el-menu-item`

### Reproduction Link

[Github Repo](https://github.com/pekonchan/namespace-test)

### Steps to reproduce

按照官方文档提示的配置设置 ElConfigProvider 和 scss $namespace， 菜单组件的样式存在丢失，无法正常显示。

1. clone链接中的工程
2. yarn install
3. yarn run serve
4. 启动工程就能看到效果了

### What is Expected?

自定义命名空间后，菜单组件显示正常

### What is actually happening?

自定义命名空间后，菜单组件显示不正常

### Additional comments

不正常的效果：
![image](https://github.com/element-plus/element-plus/assets/38689834/bfcbe446-2165-4ab8-b817-02daeba64183)

正常的效果：

![image](https://github.com/element-plus/element-plus/assets/38689834/5a9f7683-1839-41fd-84ef-b35a74591f02)

**Comment by vela666** [comment]
configureWebpack: {
    plugins: [
      AutoImport({
        resolvers: [ElementPlusResolver({
          // 自定义命名空间且按需导入必需，不然样式不会被引入
          importStyle: 'sass',
        })],
      }),
      Components({
        resolvers: [ElementPlusResolver({
          // 自定义命名空间且按需导入必需，不然样式不会被引入
          importStyle: 'sass',
        })],
      }),
    ]
  },

**Comment by pekonchan** [comment]
> configureWebpack: { plugins: [ AutoImport({ resolvers: [ElementPlusResolver({ // 自定义命名空间且按需导入必需，不然样式不会被引入 importStyle: 'sass', })], }), Components({ resolvers: [ElementPlusResolver({ // 自定义命名空间且按需导入必需，不然样式不会被引入 importStyle: 'sass', })], }), ] },

之前的写法没有传入参数importStyle: 'sass'。 现在成功了。感谢~
