### ISSUE TITLE
[Bug Report] [Component] [Select V2] 数据处理操作放在options中后，删除标签导致已选中标签不显示

### ISSUE THREAD

**Issue by tiaopiiii** [element-plus/element-plus#14146]
### Element Plus version
2.3.12

### OS/Browsers version
win11/Chrome116

### Vue version
3.3.4

### Reproduction Link
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlYWN0aXZlfSBmcm9tIFwidnVlXCI7XG5jb25zdCBpbnB1dD1yZWFjdGl2ZSh7c2VsZWN0OicnfSlcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3QtdjJcbiAgICA6b3B0aW9ucz1cIiBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICB2YWx1ZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXCJcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICB2LW1vZGVsPVwiaW5wdXQuc2VsZWN0XCJcbiAgICBzdHlsZT1cIndpZHRoOiAzMDBweFwiXG4vPlxuPC90ZW1wbGF0ZT5cblxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319
``` vue
<template>
<el-select-v2
    :options=" Array.from({ length: 1000 }).map((_, idx) => ({
  value: `Option ${idx + 1}`,
  label: `${initials[idx % 10]}${idx}`,
}))"
    multiple
    filterable
    v-model="input.select"
    style="width: 300px"
/>
</template>

<script setup>
import {reactive} from "vue";
const input=reactive({select:''})
const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
</script>

```

### Steps to reproduce

1.在 el-select-v2 的 options 直接放入进行 map 等操作过的数据 ，加上多选和过滤属性；
2. 先选中几个下拉项；
3. 使用模糊搜索选择几个下拉项后，在搜索关键词还在时删除已有选项；

但当把数据存放到变量后再放入 options 后进行上述步骤却是正常。

### What is Expected?
点击删除只会删除对应选中标签，其他已选中标签展示不受影响。

### What is actually happening?
在上面步骤下，点击删除标签后，部分标签消失没有展示，但数据还在。
(展示的标签异常，存放数据的变量正常)

**Comment by kamesan012** [comment]
对options的赋值有问题，用这种方式赋值会触发这里的watch，就会出现你所复现的异常行为
![image](https://github.com/element-plus/element-plus/assets/79386745/8090a1ab-5a86-4400-bd72-365a934d8866)

**Comment by tiaopiiii** [comment]
> 对options的赋值有问题，用这种方式赋值在下拉选项改变时就会触发这里的watch，正常应该是在options改变时才触发，就会出现描述中的异常行为，应该是options每次都使用了一个新的Array导致的。 `useSelect.ts` 743行
> 
> ```ts
>   watch(
>     () => props.options,
>     () => {
>       const input = inputRef.value
>       // filter or remote-search scenarios are not initialized
>       if (!input || (input && document.activeElement !== input)) {
>         initStates()
>       }
>     },
>     {
>       deep: true,
>     }
>   )
> ```

可以问一下这种给 props 的赋值方式是在什么特殊背景下触发 watch 吗？这种类似的数据源自己平时这样写好像没有遇到这样触发 watch 的情况。

**Comment by kamesan012** [comment]
> > 对options的赋值有问题，用这种方式赋值在下拉选项改变时就会触发这里的watch，正常应该是在options改变时才触发，就会出现描述中的异常行为，应该是options每次都使用了一个新的Array导致的。 `useSelect.ts` 743行
> > ```ts
> >   watch(
> >     () => props.options,
> >     () => {
> >       const input = inputRef.value
> >       // filter or remote-search scenarios are not initialized
> >       if (!input || (input && document.activeElement !== input)) {
> >         initStates()
> >       }
> >     },
> >     {
> >       deep: true,
> >     }
> >   )
> > ```
> 
> 可以问一下这种给 props 的赋值方式是在什么特殊背景下触发 watch 吗？这种类似的数据源自己平时这样写好像没有遇到这样触发 watch 的情况。

你可以在后面加上时间戳，你会发现你选中或者删除选项时都会对options重新传值，在你的例子中值是一样的但是地址不一样所以不容易发现。
```vue
<script setup lang="ts">
import {reactive} from "vue";
const input=reactive({select:''})
const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
</script>

<template>
  <el-select-v2
    :options="Array.from({ length: 10 }).map((_, idx) => {
      const date = new Date()
      return {
        value: `Option ${idx + 1}`,
        label: `${initials[idx % 10]}${date.getTime()}`,
      }
    })"
    multiple
    filterable
    v-model="input.select"
    style="width: 300px"
/>
</template>
```

**Comment by tiaopiiii** [comment]
> > > 对options的赋值有问题，用这种方式赋值在下拉选项改变时就会触发这里的watch，正常应该是在options改变时才触发，就会出现描述中的异常行为，应该是options每次都使用了一个新的Array导致的。 `useSelect.ts` 743行
> > > ```ts
> > >   watch(
> > >     () => props.options,
> > >     () => {
> > >       const input = inputRef.value
> > >       // filter or remote-search scenarios are not initialized
> > >       if (!input || (input && document.activeElement !== input)) {
> > >         initStates()
> > >       }
> > >     },
> > >     {
> > >       deep: true,
> > >     }
> > >   )
> > > ```
> > 
> > 
> > 可以问一下这种给 props 的赋值方式是在什么特殊背景下触发 watch 吗？这种类似的数据源自己平时这样写好像没有遇到这样触发 watch 的情况。
> 
> 你可以在后面加上时间戳，你会发现你选中或者删除选项时都会对options重新传值，在你的例子中值是一样的但是地址不一样所以不容易发现。
> 
> ```
> <script setup lang="ts">
> import {reactive} from "vue";
> const input=reactive({select:''})
> const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
> </script>
> 
> <template>
>   <el-select-v2
>     :options="Array.from({ length: 10 }).map((_, idx) => {
>       const date = new Date()
>       return {
>         value: `Option ${idx + 1}`,
>         label: `${initials[idx % 10]}${date.getTime()}`,
>       }
>     })"
>     multiple
>     filterable
>     v-model="input.select"
>     style="width: 300px"
> />
> </template>
> ```
谢谢，不过我想问的其实不是内存地址改变引起 watch ，而是为什么 props 会触发更新？是不是因为 select-v2 这个选择器组件有什么不一样的处理，我在自己写的组件中使用好像并不会导致 props 更新😂。

**Comment by kamesan012** [comment]
> > > > 对options的赋值有问题，用这种方式赋值在下拉选项改变时就会触发这里的watch，正常应该是在options改变时才触发，就会出现描述中的异常行为，应该是options每次都使用了一个新的Array导致的。 `useSelect.ts` 743行
> > > > ```ts
> > > >   watch(
> > > >     () => props.options,
> > > >     () => {
> > > >       const input = inputRef.value
> > > >       // filter or remote-search scenarios are not initialized
> > > >       if (!input || (input && document.activeElement !== input)) {
> > > >         initStates()
> > > >       }
> > > >     },
> > > >     {
> > > >       deep: true,
> > > >     }
> > > >   )
> > > > ```
> > > 
> > > 
> > > 可以问一下这种给 props 的赋值方式是在什么特殊背景下触发 watch 吗？这种类似的数据源自己平时这样写好像没有遇到这样触发 watch 的情况。
> > 
> > 
> > 你可以在后面加上时间戳，你会发现你选中或者删除选项时都会对options重新传值，在你的例子中值是一样的但是地址不一样所以不容易发现。
> > ```
> > <script setup lang="ts">
> > import {reactive} from "vue";
> > const input=reactive({select:''})
> > const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
> > </script>
> > 
> > <template>
> >   <el-select-v2
> >     :options="Array.from({ length: 10 }).map((_, idx) => {
> >       const date = new Date()
> >       return {
> >         value: `Option ${idx + 1}`,
> >         label: `${initials[idx % 10]}${date.getTime()}`,
> >       }
> >     })"
> >     multiple
> >     filterable
> >     v-model="input.select"
> >     style="width: 300px"
> > />
> > </template>
> > ```
> 
> 谢谢，不过我想问的其实不是内存地址改变引起 watch ，而是为什么 props 会触发更新？是不是因为 select-v2 这个选择器组件有什么不一样的处理，我在自己写的组件中这样赋值使用好像并不会导致 props 更新😂。

props变化会触发组件更新的生命周期

**Comment by tiaopiiii** [comment]
> > > > > 对options的赋值有问题，用这种方式赋值在下拉选项改变时就会触发这里的watch，正常应该是在options改变时才触发，就会出现描述中的异常行为，应该是options每次都使用了一个新的Array导致的。 `useSelect.ts` 743行
> > > > > ```ts
> > > > >   watch(
> > > > >     () => props.options,
> > > > >     () => {
> > > > >       const input = inputRef.value
> > > > >       // filter or remote-search scenarios are not initialized
> > > > >       if (!input || (input && document.activeElement !== input)) {
> > > > >         initStates()
> > > > >       }
> > > > >     },
> > > > >     {
> > > > >       deep: true,
> > > > >     }
> > > > >   )
> > > > > ```
> > > > 
> > > > 
> > > > 可以问一下这种给 props 的赋值方式是在什么特殊背景下触发 watch 吗？这种类似的数据源自己平时这样写好像没有遇到这样触发 watch 的情况。
> > > 
> > > 
> > > 你可以在后面加上时间戳，你会发现你选中或者删除选项时都会对options重新传值，在你的例子中值是一样的但是地址不一样所以不容易发现。
> > > ```
> > > <script setup lang="ts">
> > > import {reactive} from "vue";
> > > const input=reactive({select:''})
> > > const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
> > > </script>
> > > 
> > > <template>
> > >   <el-select-v2
> > >     :options="Array.from({ length: 10 }).map((_, idx) => {
> > >       const date = new Date()
> > >       return {
> > >         value: `Option ${idx + 1}`,
> > >         label: `${initials[idx % 10]}${date.getTime()}`,
> > >       }
> > >     })"
> > >     multiple
> > >     filterable
> > >     v-model="input.select"
> > >     style="width: 300px"
> > > />
> > > </template>
> > > ```
> > 
> > 
> > 谢谢，不过我想问的其实不是内存地址改变引起 watch ，而是为什么 props 会触发更新？是不是因为 select-v2 这个选择器组件有什么不一样的处理，我在自己写的组件中这样赋值使用好像并不会导致 props 更新😂。
> 
> props变化会触发组件更新的生命周期

可能我没表述清楚，我还是不纠结这个了😂，谢谢大佬回复。
