### ISSUE TITLE
[Component] date picker's popper trigger has aria-expanded which causes accessibility issues

### ISSUE THREAD

**Issue by Karolis-Stoncius** [element-plus/element-plus#14150]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Chrome 114.0.5735.90 / Windows 10 Pro`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-popper`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRhdGUtcGlja2VyIGlkPVwiZGF0ZS1mcm9tXCIgdHlwZT1cImRhdGVyYW5nZVwiIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBkYXRlXCJcbiAgICBhcmlhLWxhYmVsPVwiRGF0ZSBwaWNrZXJcIiA6Y2xlYXJhYmxlPVwiZmFsc2VcIiAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Inspect the date picker tooltip's trigger `div`

### What is Expected?

date picker tooltip's trigger `div` should not have an `aria-expanded` attribute

### What is actually happening?

date picker tooltip's trigger `div` has an `aria-expanded` attribute

### Additional comments

I'm using axe DevTool chrome extension to find accessibility issues and it finds [this](https://dequeuniversity.com/rules/axe/4.7/aria-allowed-attr?application=AxeChrome) issue which is caused by `aria-expanded` attribute. I think this happens because ["Though a tooltip may appear and disappear, as its appearance is automatic and not intentionally controlled by the user, the aria-expanded role is not supported."](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role)

**Comment by Karolis-Stoncius** [comment]
I tried solving this myself and my investigation led to [this](https://github.com/element-plus/element-plus/blob/dev/packages/components/popper/src/trigger.vue) component. Removing `:aria-expanded="ariaExpanded"` would solve this issue, but there's probably a reason why it's there so I didn't want to break something 😄

**Comment by Karolis-Stoncius** [comment]
@btea could you look at this one too? 🙇

**Comment by Karolis-Stoncius** [comment]
@tolking 🙇

**Comment by Karolis-Stoncius** [comment]
@btea

**Comment by tolking** [comment]
IMO, the `aria-*` tags should be added to the input instead of the current div tag.

aria-expanded is a label that must exist

**Comment by tolking** [comment]
Because the Tab focus on the input instead of div

**Comment by Karolis-Stoncius** [comment]
Should I attempt to fix this issue, or could anyone more knowledgeable pick this up?

**Comment by tolking** [comment]
I will fix it

**Comment by SofijaSutton** [comment]
Is there an update on this, I am encountering these accessibility issues still. Thank you so much for helping!
