### ISSUE TITLE
[Bug Report] How do I validate data against cells of a table embedded in a form?

### ISSUE THREAD

**Issue by mengweijin** [element-plus/element-plus#1415]
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
Windows 10 / Google Browser

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/mengweijin/pen/ZEBGBRJ

### Steps to reproduce
1. “https://codepen.io/mengweijin/pen/ZEBGBRJ” is currently in the code to run to expect normal behavior：
````
    Line 18：<el-form-item label=" " :prop="'dataList.0.name'" :rules="rules.name">
    Line 26：<el-form-item label=" " :prop="'dataList.0.amount'" :rules="rules.amount">
````
Operating steps：

    a. Don't enter any characters in the input field of the form, click the Submit button. It will prompt you to fill in the required fields, and no Alert box will pop up on the page.

    b. Enter any character in all the input fields in the form, click the submit button, and the page will display an Alert box.

2. However, in the real development process, the table data is dynamic, and we cannot write it like this：   :prop="'dataList.0.name'"

Therefore, referring to the official documentation, we made the following changes：
````
    Line 18：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.name'" :rules="rules.name">
    Line 26：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.amount'" :rules="rules.amount">
````
At the moment, the page rendering is abnormal, can not display the table. And debugging finds that scope.$index is always -1.

### What is Expected?
After make the following modifications:
````
    Line 18：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.name'" :rules="rules.name">
    Line 26：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.amount'" :rules="rules.amount">
````
The form in the page can be rendered normally, and the form validation function in the form is normal. Click the submit button, and the Alert box will pop up.

### What is actually happening?
After make the following modifications:
````
    Line 18：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.name'" :rules="rules.name">
    Line 26：<el-form-item label=" " :prop="'dataList.' + scope.$index + '.amount'" :rules="rules.amount">
````
The page is rendered abnormally. The table cannot be displayed properly.

**Comment by JeremyWuuuuu** [comment]
So I have had investigated the demo code.
1. I don't quite understand why the business needs something like this.
2. `prop` attribute isn't some attribute only for deriving the value, it also used in `validation`. So basically you will need to create `rules` with the same entry point just like your `dataList`

**Comment by JeremyWuuuuu** [comment]
Also, the easiest way for you to fix this is that:

Remove `:rules` field in `el-form` tag. Only bind `:rules` locally on the `form-item`.

**Comment by mengweijin** [comment]
@JeremyWuuuuu 

I updated the code to add a business scenario.       https://codepen.io/mengweijin/pen/ZEBGBRJ

When the Add Row Button is clicked once, a row is added to the table, and the user needs to select or enter data. Multiple form records can be submitted in one commit.

In addition, as you suggested，Remove :rules field in el-form tag. Only bind :rules locally on the form-item.

But it still didn't work.

I'm looking forward to is that the latest code on https://codepen.io/mengweijin/pen/ZEBGBRJ       （I removed the prop property because adding the page broke），How do I make all form validation work?

**Comment by JeremyWuuuuu** [comment]
You still need `prop` on `form-item` to derive value from `el-form`

**Comment by mengweijin** [comment]
> You still need `prop` on `form-item` to derive value from `el-form`

Sorry, I don't understand how to write the value of 'prop'.

Because when I tried to write this, the page form got an exception and didn't render properly:
````
<el-form-item label=" " :prop="'dataList.' + scope.$index + '.name'" :rules="rules.name">
````

Can you give an example of how to write it? Many thanks.

**Comment by JeremyWuuuuu** [comment]
The code is rather simple:

```vue
<template>
  <el-form :model="form" ref="form" label-width="20px">
    <el-table :data="form.dataList" border stripe>
      <el-table-column label="name">
        <template #default="scope">
          <el-form-item label=" " :prop="'name'" :rules="rules.name">
            <el-input v-model="scope.row.name"></el-input>
          </el-form-item> 
        </template>
      </el-table-column>

      <el-table-column label="amount">
        <template #default="scope">
          <el-form-item
            <!-- Note this line bellow is quite important, since the initial $index would always be -1, we need this to determine whether render the column -->
            v-if="scope && scope.$index >= 0"
            label=" "
            :prop="'dataList.' + scope.$index + '.amount'"
            :rules="rules.amount"
          >
            <el-input v-model="scope.row.amount"></el-input>
          </el-form-item>
        </template>
      </el-table-column>
    </el-table>
    <el-form-item>
      <el-button type="primary" @click="submitForm('form')">Submit</el-button>
    </el-form-item>
  </el-form>
</template>
```

See the screenshots:
### Input value given.
![image](https://user-images.githubusercontent.com/15975785/106689869-b27ad580-660b-11eb-895b-4ef62a802889.png)

### Input value not given
![image](https://user-images.githubusercontent.com/15975785/106689917-c6263c00-660b-11eb-9e7d-3bbe50acd0f5.png)


### Notice

Also there are things I'd like to mention which is when you use dynamic form like this, the error message is basically unreadable, you can see the screenshot, make sure that you provide a customized message to your user.

**Comment by mengweijin** [comment]
It worked. That's exactly what I wanted. My problem is solved. Thank you very much.
