### ISSUE TITLE
[Component] [form-item] El-form-item uses "error" slot exception

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#14170]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Chrome 115.0.5790.99 `
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm1cbiAgICByZWY9XCJydWxlRm9ybVJlZlwiXG4gICAgOm1vZGVsPVwicnVsZUZvcm1cIlxuICAgIDpydWxlcz1cInJ1bGVzXCJcbiAgICBsYWJlbC13aWR0aD1cIjEyMHB4XCJcbiAgICBjbGFzcz1cImRlbW8tcnVsZUZvcm1cIlxuICAgIDpzaXplPVwiZm9ybVNpemVcIlxuICAgIHN0YXR1cy1pY29uPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJuYW1lXCIgcHJvcD1cIm5hbWVcIj5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsPVwicnVsZUZvcm0ubmFtZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwibmFtZVwiXG4gICAgICAvPlxuICAgICAgPHRlbXBsYXRlICNlcnJvcj1cInsgZXJyb3IgfVwiPlxuICAgICAgICAgIHt7IGVycm9yIH19XG4gICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzdWJtaXRGb3JtKHJ1bGVGb3JtUmVmKVwiPlxuICAgICAgICBDcmVhdGVcbiAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0ocnVsZUZvcm1SZWYpXCI+UmVzZXQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCAgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBmb3JtU2l6ZSA9IHJlZignZGVmYXVsdCcpXG5jb25zdCBydWxlRm9ybVJlZiA9IHJlZigpXG5jb25zdCBydWxlRm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJycsXG59KVxuXG5mdW5jdGlvbiB2YWxpZElkZW50aWZpZXJSZWdleCh2YWwpIHtcbiAgcmV0dXJuIC9eW2EtekEtWl1cXHcqJC8udGVzdCh2YWwpXG59XG5cbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmUoe1xuICBuYW1lOiBbXG4gICAgeyByZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ1BsZWFzZSBpbnB1dCBBY3Rpdml0eSBuYW1lJywgdHJpZ2dlcjogIFsnYmx1cicsICdjaGFuZ2UnXSB9LFxuICAgICAgICAgIHtcbiAgICAgICAgdmFsaWRhdG9yOiAocnVsZSwgdmFsdWUsIGNhbGxiYWNrKSA9PiB7XG4gICAgICAgICAgaWYgKCF2YWxpZElkZW50aWZpZXJSZWdleCh2YWx1ZSkpIHtcbiAgICAgICAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcign5Lul5a2X5q+N5byA5aS077yM5Y+q6IO95YyF5ZCr5pWw5a2X77yM5a2X5q+N5ZKM5LiL5YiS57q/XCJfXCInKSlcbiAgICAgICAgICAgIHJldHVyblxuICAgICAgICAgIH1cbiAgICAgICAgICBjYWxsYmFjaygpXG4gICAgICAgIH0sXG4gICAgICAgIHRyaWdnZXI6ICBbJ2JsdXInLCAnY2hhbmdlJ10sXG4gICAgICB9LFxuXG4gIF0sXG59KVxuXG5jb25zdCBzdWJtaXRGb3JtID0gYXN5bmMgKGZvcm1FbCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGF3YWl0IGZvcm1FbC52YWxpZGF0ZSgodmFsaWQsIGZpZWxkcykgPT4ge1xuICAgIGlmICh2YWxpZCkge1xuICAgICAgY29uc29sZS5sb2coJ3N1Ym1pdCEnKVxuICAgIH0gZWxzZSB7XG4gICAgICBjb25zb2xlLmxvZygnZXJyb3Igc3VibWl0IScsIGZpZWxkcylcbiAgICB9XG4gIH0pXG59XG5cbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWwpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBgJHtpZHggKyAxfWAsXG4gIGxhYmVsOiBgJHtpZHggKyAxfWAsXG59KSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Open the console to view error reports.
First, enter the incorrect content in the input box, and then clear the content.

### What is Expected?

Normal verification 

### What is actually happening?

Affect the verification result

### Additional comments

_(empty)_

**Comment by vela666** [comment]
![GIF 2023-9-2 22-41-18](https://github.com/element-plus/element-plus/assets/69613314/52592390-7282-4c51-b7e1-2cfe77f50522)
In GIF, you can see that the first input error is the content, and then the input box is cleared, causing a problem with the verification

**Comment by cc-hearts** [comment]
locate the error posted by `transitionGroup`，`text elements` cannot produce transitions and should be avoided

```diff
 <template #error="{ error }">
-  {{ error }}
+  <span>
+   {{ error }}
+  </span>
  </template>
```

**Comment by vela666** [comment]
> locate the error posted by `transitionGroup`，`text elements` cannot produce transitions and should be avoided
> 
> ```diff
>  <template #error="{ error }">
> -  {{ error }}
> +  <span>
> +   {{ error }}
> +  </span>
>   </template>
> ```

ok thank

**Comment by btea** [comment]
This may be regarded as a bug in vue.
https://github.com/vuejs/core/pull/6761
