### ISSUE TITLE
[Component] [tree-select] v-for循环el-tree-select组件出来后无法修改第一个el-tree-select组件的value值

### ISSUE THREAD

**Issue by destiny-yyc** [element-plus/element-plus#14204]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.10`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxkaXYgdi1mb3I9XCIoaXRlbSxpbmRleCkgaW4gdmFsdWVMaXN0XCI+XG48ZWwtdHJlZS1zZWxlY3RcbiAgICB2LW1vZGVsPVwiaXRlbS5vcmdOYW1lXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGNoZWNrLXN0cmljdGx5XG4gICAgOnJlbmRlci1hZnRlci1leHBhbmQ9XCJmYWxzZVwiXG4gICAgbm8tZGF0YS10ZXh0PVwi5pqC5peg6YCJ6aG5XCJcbiAgICBhY2NvcmRpb25cbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBwbGFjZWhvbGRlcj1cIiBcIlxuICAgIHZhbHVlLWtleT1cIm9yZ05hbWVcIlxuICAgIDpwcm9wcz1cInsgbGFiZWw6ICdvcmdOYW1lJywgdmFsdWU6ICdvcmdOYW1lJywgY2hpbGRyZW46J2NoaWxkcmVuJywgfVwiXG4gIC8+XG48L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlTGlzdCA9IHJlZihbe1wib3JnTmFtZVwiOlwiXCJ9LHtcIm9yZ05hbWVcIjpcIlwifV0pXG5cbmNvbnN0IGdldERhdGEgPSBhc3luYyAoKSA9PiB7XG4gIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiBzZXRUaW1lb3V0KHJlc29sdmUsIDMwMCkpXG4gIHZhbHVlTGlzdC52YWx1ZSA9IFtcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4fkuIBcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5LqMXCJ9LFxuICAgIHtcIm9yZ05hbWVcIjpcIue7hOe7h+S4iVwifSxcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4flm5tcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5LqUXCJ9LFxuICAgIHtcIm9yZ05hbWVcIjpcIue7hOe7h+WFrVwifSxcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4fkuINcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5YWrXCJ9XG4gIF1cbn1cbmdldERhdGEoKVxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIFwiaWRcIjoyNyxcbiAgICBcInBhcmVudElkXCI6LTEsXG4gICAgXCJjaGlsZHJlblwiOltcbiAgICAgIHtcbiAgICAgICAgXCJpZFwiOjI4LFxuICAgICAgICBcInBhcmVudElkXCI6MjcsXG4gICAgICAgIFwiY2hpbGRyZW5cIjpbXG4gICAgICAgICAge1xuICAgICAgICAgICAgXCJpZFwiOjMwLFxuICAgICAgICAgICAgXCJwYXJlbnRJZFwiOjI4LFxuICAgICAgICAgICAgXCJjaGlsZHJlblwiOltdLFxuICAgICAgICAgICAgXCJvcmdOYW1lXCI6XCLnp4DmlrAy6ZifXCIsXG4gICAgICAgICAgICBcImxldmVsXCI6MyxcbiAgICAgICAgICAgIFwic29ydFwiOjFcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwiaWRcIjoyOSxcbiAgICAgICAgICAgIFwicGFyZW50SWRcIjoyOCxcbiAgICAgICAgICAgIFwiY2hpbGRyZW5cIjpbXSxcbiAgICAgICAgICAgIFwib3JnTmFtZVwiOlwi56eA5pawMemYn1wiLFxuICAgICAgICAgICAgXCJsZXZlbFwiOjMsXG4gICAgICAgICAgICBcInNvcnRcIjoxXG4gICAgICAgICAgfVxuICAgICAgICBdLFxuICAgICAgXCJvcmdOYW1lXCI6XCLnp4DmlrBcIixcbiAgICAgIFwibGV2ZWxcIjoyLFxuICAgICAgXCJzb3J0XCI6MVxuICAgICAgfVxuICAgIF0sXG4gICAgXCJvcmdOYW1lXCI6XCLlnZHmopPpobnnm65cIixcbiAgICBcImxldmVsXCI6MSxcbiAgICBcInNvcnRcIjoxXG4gIH0sXG4gIHtcbiAgICBcImlkXCI6MzIsXG4gICAgXCJwYXJlbnRJZFwiOi0xLFxuICAgIFwiY2hpbGRyZW5cIjpbXSxcbiAgICBcIm9yZ05hbWVcIjpcIuWdkeaik+a1i+ivlVwiLFxuICAgIFwibGV2ZWxcIjoxLFxuICAgIFwic29ydFwiOjJcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1.初始化valueList的值
2.请求获取的值并赋值给valueList
3.修改valueList中的某一项
4.初始化的那一项无法触发修改
详细情况可通过`Element Plus Playground`查看，也就是上面的链接
1. Initialize the value of the valueList
2. Request the obtained value and assign it to the valueList
3. Modify an item in the valueList
4. The initialized item cannot trigger modification
Details can be found in the 'Element Plus Playground', which is the link above

### What is Expected?

希望修改tree-select组件的值
I want to change the value of tree-select component

### What is actually happening?

但是第一个tree-select组件无法更换值
But the first tree-select component cannot be replaced

### Additional comments

当`valueList`的初始化值为`[]`（空数组），又可以选择了，我就想知道这是问什么呢，在之前的写的都没遇到过这种问题
When the `valueList` is initialized to `[]` (empty array) and can be selected again, I wonder what this is asking, since I have never encountered this problem before

**Comment by yj-liuzepeng** [comment]
<img width="496" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/60789c03-f8ad-4d48-b820-2d572d4b30df">

**Comment by destiny-yyc** [comment]
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/75007029/265972953-60789c03-f8ad-4d48-b820-2d572d4b30df.png">

已重新修改地址，可以重新查看
The address has been changed. You can view the address again
