### ISSUE TITLE
[Bug Report] Input rendering on MacOS Safari

### ISSUE THREAD

**Issue by AubSs** [element-plus/element-plus#1420]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
macOS Big Sur / Safari Version 14.0.3 (16610.4.3.1.4)

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/0obg9jut/1/

### Steps to reproduce
Just a small rendering problem on safari with `<el-input size="mini" />`
(Append on all input which is not normal size)
(Also append on others components like cascader/input number/etc..)

### What is Expected?
inside input must be center

### What is actually happening?
inside input is wayyy below (cf img)

<img width="1079" alt="Screenshot 2021-02-03 at 23 02 18" src="https://user-images.githubusercontent.com/10529080/106816249-65cbe480-6675-11eb-8774-7141a8a3a55f.png">

**Comment by Ryan2128** [comment]
cc @JeremyWuuuuu , limited by the operating system.

**Comment by zazzaz** [comment]
can confirm it's a bug on Safari Macos

**Comment by AubSs** [comment]
Yes, it doesn't append on Chromium or Firefox for information (neither  opera & brave)

**Comment by AubSs** [comment]
@zazzaz , @JeremyWuuuuu you should look at https://www.browserstack.com/open-source for use case like this, they have a nice free plan for open source project !

**Comment by JeremyWuuuuu** [comment]
Yep, I'am currently on MacOS `11.0.1`, bug confirmed, I'll go find a work around for this.

**Comment by JeremyWuuuuu** [comment]
I already know how to fix this, simply apply the same `height` value to `line-height` this can be fixed.
