### ISSUE TITLE
[Docs] [icon] typo error @element-plus/icons-vue

### ISSUE THREAD

**Issue by pdsuwwz** [element-plus/element-plus#14201]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

## Reproduction

![image](https://github.com/element-plus/element-plus/assets/19891724/e4ce0870-1293-4cb5-ba9f-abe0a9515685)

### Related Component

- `el-icon`

https://crowdin.com/translate/element-plus/867/en-zhcn?filter=basic&value=0

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/icon.html)

### Steps to reproduce

https://element-plus.org/zh-CN/component/icon.html

### What is Expected?

只要你安装了 `@element-plus/icons-vue`，就可以在任意版本里使用 SVG 图标。

### What is actually happening?

只要你安装了 `@element-plus/icons`，就可以在任意版本里使用 SVG 图标。

### Additional comments

_(empty)_

**Comment by btea** [comment]
谢谢反馈，翻译问题，已修复！
https://crowdin.com/translate/element-plus/867/en-zhcn?filter=basic&value=0
