### ISSUE TITLE
[Component] [image, table-column] el-table中使用el-image的图片预览功能，样式错乱

### ISSUE THREAD

**Issue by poicc** [element-plus/element-plus#14215]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome/116.0.5845.141（Windows NT 10.0; Win64; x64）`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZHJhZnRMaXN0OiBhbnkgPSByZWYoW1xue1xucGhvdG9LZXk6ICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZS81ZC80YTczMWE5MDU5NGE0YWY1NDRjMGMyNTk0MTE3MWpwZWcuanBlZycsXG5pbWdMaXN0IDogW1xuJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9lLzVkLzRhNzMxYTkwNTk0YTRhZjU0NGMwYzI1OTQxMTcxanBlZy5qcGVnJyxcbidodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZS81ZC80YTczMWE5MDU5NGE0YWY1NDRjMGMyNTk0MTE3MWpwZWcuanBlZycsXG5dXG59LFxue1xucGhvdG9LZXk6ICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZS81ZC80YTczMWE5MDU5NGE0YWY1NDRjMGMyNTk0MTE3MWpwZWcuanBlZycsXG5pbWdMaXN0IDogW1xuJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9lLzVkLzRhNzMxYTkwNTk0YTRhZjU0NGMwYzI1OTQxMTcxanBlZy5qcGVnJyxcbidodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZS81ZC80YTczMWE5MDU5NGE0YWY1NDRjMGMyNTk0MTE3MWpwZWcuanBlZycsXG5dXG59XG5dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIHJlZj1cImRyYWZ0TGlzdFJlZlwiIDpkYXRhPVwiZHJhZnRMaXN0XCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiIGNsYXNzPVwibXQtOFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJwb3N0Q29udGVudFwiIGxhYmVsPVwi6LS05paHXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cInBvc3RDb250ZW50X2ZsZXhcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJpbWdfY29udGFpbmVyXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGVsLWltYWdlXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNsYXNzPVwicG9zdF9pbWdcIlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA6c3JjPVwic2NvcGUucm93LnBob3RvS2V5XCJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgOmluaXRpYWwtaW5kZXg9XCIwXCJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZml0PVwiY292ZXJcIlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNjb3BlLnJvdy5pbWdMaXN0XCJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICAgICAgICAgICAgICAgICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5wb3N0X2ltZyB7XG53aWR0aDogNTBweDtcbmhlaWdodDogNTBweDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-table-column中使用el-image组件，el-image组件添加:preview-src-list="imgList"进行图片预览，在表格中点击图片进行预览就会出现

### What is Expected?

图片预判的mask遮罩层覆盖全屏

### What is actually happening?

表格元素的分割线、选中行以及图片元素未被mask覆盖

### Additional comments

_(empty)_

**Comment by poicc** [comment]
![image](https://github.com/element-plus/element-plus/assets/59445871/25b63567-0997-410b-bd59-04c7d8a1b4d9)

**Comment by lovelytan** [comment]
请问您解决了吗，我也遇到了这个问题
