### ISSUE TITLE
[Component] [select, popper] el-select激活状态下滚动出容器范围外，el-popper没有消失而是悬浮在容器外部

### ISSUE THREAD

**Issue by ghost** [element-plus/element-plus#14220]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.5`
- Browser / OS: `Chrome 116.0.5845.140`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-popper`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFNlbGVjdCxFbE9wdGlvbn0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBtc2cgPSByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cIm1zZ1wiPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjFcIiBsYWJlbD1cIjAwMVwiPjwvZWwtb3B0aW9uPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjJcIiBsYWJlbD1cIjAwMlwiPjwvZWwtb3B0aW9uPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjNcIiBsYWJlbD1cIjAwM1wiPjwvZWwtb3B0aW9uPlxuICAgIDwvZWwtc2VsZWN0PlxuICAgIDxkaXY+5Y2g5L2NPC9kaXY+XG4gICAgPGRpdj7ljaDkvY08L2Rpdj5cbiAgICA8ZGl2PuWNoOS9jTwvZGl2PlxuICAgIDxkaXY+5Y2g5L2NPC9kaXY+XG4gICAgPGRpdj7ljaDkvY08L2Rpdj5cbiAgICA8ZGl2PuWNoOS9jTwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4uY29udGFpbmVyIHtcbiAgd2lkdGg6IDMwMHB4OyBcbiAgaGVpZ2h0OiA1MHB4O1xuICBwYWRkaW5nOiAxMHB4OyBcbiAgbWFyZ2luOjEwMHB4OyBcbiAgYm9yZGVyOiAxcHggc29saWQgIzhjOGM4YzsgXG4gIG92ZXJmbG93OnNjcm9sbFxufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 将 `el-select` 放置在一个有滚动的容器中（.container）；
2. 激活 `el-select` 下拉框，使 `el-popper` 展示出来；
3. 滚动容器的滚动条，且保持 `el-select` 处于激活状态；
4. 即可发现 `el-select` 滚动出视野范围，且 `el-popper` 悬浮在容器区域之外；

### What is Expected?

期望 `el-select` 滚动出容器可是范围之外时候，自动收起  `el-popper` 

### What is actually happening?

目前`el-select` 滚动出容器可视范围后，`el-popper` 没有消失，并且悬浮在容器范围外

### Additional comments

实际项目中，设置 `teleported = false` 会因为 z-index 导致 `el-popper` 遮盖，所以不考虑设置 `teleported = false` 。

**Comment by zhangwei312936** [comment]
你太菜

**Comment by jswxwxf** [comment]
我遇到同样的问题

**Comment by srchafreenn** [comment]
> 你太菜

你有病？ 哪远死哪去 臭傻逼

**Comment by zhangwei312936** [comment]
母狗去死

**Comment by srchafreenn** [comment]
> 母狗去死

可怜的蛆蝻，这么仇女，你妈把你生下来就扔粪坑里了吧？怎么不烂死在粪坑里呢？出来干嘛？张着臭嘴就对人乱咬。

**Comment by Big-Shawn** [comment]
v2er围观吃瓜

**Comment by zhoufanglu** [comment]
设置el-popper 是否可以解决层级问题？

**Comment by aizela** [comment]
围观国女魅力时刻

**Comment by leakn** [comment]
尝试一下监听滚动事件，然后手动隐藏popper：
文档显示可以调用blur使input框失去焦点并隐藏下拉框
https://element-plus.org/zh-CN/component/select.html#select-exposes
![image](https://github.com/element-plus/element-plus/assets/49036291/6616ae47-f140-41f3-bb04-a07af6778fd8)

**Comment by cc-hearts** [comment]
Can you refer to this playground?
 [element-plus playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsU2VsZWN0LEVsT3B0aW9ufSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG1zZyA9IHJlZignMScpXG5jb25zdCBlbCA9IHJlZihudWxsKVxuY29uc3Qgc2VsZWN0RWwgPSByZWYobnVsbClcbm9uTW91bnRlZCgoKSA9PiB7XG5cbiAgY29uc3QgaW50ZXJzZWN0aW9uT2JzZXJ2ZXIgPSBuZXcgSW50ZXJzZWN0aW9uT2JzZXJ2ZXIoKGVudHJpZXMpID0+IHtcbiAgICBjb25zdCBbZW50cnldID0gZW50cmllc1xuXG4gICAgaWYgKGVudHJ5LmludGVyc2VjdGlvblJhdGlvIDw9MCkge1xuICAgICAgc2VsZWN0RWwudmFsdWU/LmJsdXIoKVxuICAgIH1cbiAgfSlcblxuICBpbnRlcnNlY3Rpb25PYnNlcnZlci5vYnNlcnZlKGVsLnZhbHVlKVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IHJlZj1cImVsXCI+XG4gICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJtc2dcIiByZWY9XCJzZWxlY3RFbFwiPlxuICAgICAgICA8ZWwtb3B0aW9uIHZhbHVlPVwiMVwiIGxhYmVsPVwiMDAxXCI+PC9lbC1vcHRpb24+XG4gICAgICAgIDxlbC1vcHRpb24gdmFsdWU9XCIyXCIgbGFiZWw9XCIwMDJcIj48L2VsLW9wdGlvbj5cbiAgICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjNcIiBsYWJlbD1cIjAwM1wiPjwvZWwtb3B0aW9uPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gICAgPGRpdj7ljaDkvY08L2Rpdj5cbiAgICA8ZGl2PuWNoOS9jTwvZGl2PlxuICAgIDxkaXY+5Y2g5L2NPC9kaXY+XG4gICAgPGRpdj7ljaDkvY08L2Rpdj5cbiAgICA8ZGl2PuWNoOS9jTwvZGl2PlxuICAgIDxkaXY+5Y2g5L2NPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi5jb250YWluZXIge1xuICB3aWR0aDogMzAwcHg7IFxuICBoZWlnaHQ6IDUwcHg7XG4gIHBhZGRpbmc6IDEwcHg7IFxuICBtYXJnaW46MTAwcHg7IFxuICBib3JkZXI6IDFweCBzb2xpZCAjOGM4YzhjOyBcbiAgb3ZlcmZsb3c6c2Nyb2xsXG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by kooriookami** [comment]
请手动处理，这不是bug所以关闭。
