### ISSUE TITLE
[Component] [select] select组件在无法匹配选项的时不应该显示 value 属性。与浏览器自带 select 表现不一致

### ISSUE THREAD

**Issue by milo-xiaomeng** [element-plus/element-plus#14235]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[el-select与 select 对比](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPHNlbGVjdCBuYW1lPVwicGV0c1wiIHYtbW9kZWw9XCJ2YWx1ZVwiPlxuICAgICAgPG9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L3NlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCdPcHRpb24wJylcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

[原生校验](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8Zm9ybSBtZXRob2Q9XCJnZXRcIj5cbiAgICAgIDxoMT7ljp/nlJ88L2gxPlxuICAgICAge3sgdmFsdWUgfX1cbiAgICAgIDxzZWxlY3QgbmFtZT1cInBldHNcIiB2LW1vZGVsPVwidmFsdWVcIiA6cmVxdWlyZWQ9XCJ0cnVlXCI+XG4gICAgICAgIDxvcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgIC8+XG4gICAgICA8L3NlbGVjdD5cbiAgICAgIDxpbnB1dCB0eXBlPVwic3VibWl0XCIgdmFsdWU9XCLmj5DkuqRcIi8+XG4gICAgPC9mb3JtPlxuICA8L2Rpdj4gXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignT3B0aW9uMCcpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9XG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <el-select v-model="value" class="m-2" placeholder="Select" size="large">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
    />
  </el-select>
  <select name="pets" v-model="value">
      <option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
    />
  </select>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const value = ref('Option0')

const options = [
  {
    value: 'Option1',
    label: 'Option1',
  }
]
</script>

```

### What is Expected?

与浏览器自带 select 表现一致,理应都为空
在vuetifyjs,primevue,这两个UI 框架不存在这个问题。

### What is actually happening?

显示具体的 value

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/115647582/1be7a868-395f-42f6-b459-e2c76bfdbe07)

**Comment by axinss** [comment]
.......那你把ref()设置成空值不就行了

**Comment by milo-xiaomeng** [comment]
> .......那你把ref()设置成空值不就行了

我是指这种现象,不是指解决方案,匹配不到选项理应就是空的.

**Comment by axinss** [comment]
这个没问题啊，select双向绑定的就是value值。建议你看下vue官方文档。了解下它的渲染原理和v-model。

**Comment by dryzeng** [comment]
为什么select只有一种样式，就是带箭头的悬浮框。它不像是下拉选项，更像是一个tip。

**Comment by heart-to-the-sea** [comment]
> > .......那你把ref()设置成空值不就行了
> 
> 我是指这种现象,不是指解决方案,填充 value 值很诡异呐。 匹配不到选项理应就是空的.这点应该与原生 select 一致呐。

从现象上看确实是这样，如果没有匹配到相应的选项应该展示为空，不过一般出现这种情况就是在编辑历史数据的时候，数据回显的字段在当前可能已经废弃了，这得手动清理，否则一个空的表单也能通过校验这才不正常呢

**Comment by milo-xiaomeng** [comment]
> > > .......那你把ref()设置成空值不就行了
> > 
> > 
> > 我是指这种现象,不是指解决方案,填充 value 值很诡异呐。 匹配不到选项理应就是空的.这点应该与原生 select 一致呐。
> 
> 从现象上看确实是这样，如果没有匹配到相应的选项应该展示为空，不过一般出现这种情况就是在编辑历史数据的时候，数据回显的字段在当前可能已经废弃了，这得手动清理，否则一个空的表单也能通过校验这才不正常呢

麻烦看看这份事例,我利用原生的写了个demo
[案例demo](https://github.com/element-plus/element-plus/issues/14235#issuecomment-1715069317)

**Comment by milo-xiaomeng** [comment]
> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.3.4`
> * Element Plus Version: `2.3.12`
> * Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `el-select`
> 
> ### Reproduction Link
> [与原生表现不一致demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPHNlbGVjdCBuYW1lPVwicGV0c1wiIHYtbW9kZWw9XCJ2YWx1ZVwiPlxuICAgICAgPG9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L3NlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCdPcHRpb24wJylcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)
> 
> [原生校验](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8Zm9ybSBtZXRob2Q9XCJnZXRcIj5cbiAgICAgIDxoMT7ljp/nlJ88L2gxPlxuICAgICAge3sgdmFsdWUgfX1cbiAgICAgIDxzZWxlY3QgbmFtZT1cInBldHNcIiB2LW1vZGVsPVwidmFsdWVcIiA6cmVxdWlyZWQ9XCJ0cnVlXCI+XG4gICAgICAgIDxvcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgIC8+XG4gICAgICA8L3NlbGVjdD5cbiAgICAgIDxpbnB1dCB0eXBlPVwic3VibWl0XCIgdmFsdWU9XCLmj5DkuqRcIi8+XG4gICAgPC9mb3JtPlxuICA8L2Rpdj4gXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignT3B0aW9uMCcpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9XG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)
> 
> ### Steps to reproduce
> ```
> <template>
>   <el-select v-model="value" class="m-2" placeholder="Select" size="large">
>     <el-option
>       v-for="item in options"
>       :key="item.value"
>       :label="item.label"
>       :value="item.value"
>     />
>   </el-select>
>   <select name="pets" v-model="value">
>       <option
>       v-for="item in options"
>       :key="item.value"
>       :label="item.label"
>       :value="item.value"
>     />
>   </select>
> </template>
> 
> <script lang="ts" setup>
> import { ref } from 'vue'
> 
> const value = ref('Option0')
> 
> const options = [
>   {
>     value: 'Option1',
>     label: 'Option1',
>   }
> ]
> </script>
> ```
> 
> ### What is Expected?
> 与浏览器自带 select 表现一致,理应都为空
> 
> ### What is actually happening?
> 显示具体的 value
> 
> ### Additional comments
> ![image](https://user-images.githubusercontent.com/115647582/266557099-1be7a868-395f-42f6-b459-e2c76bfdbe07.png)

**Comment by milo-xiaomeng** [comment]
> 这个没问题啊，select双向绑定的就是value值。建议你看下vue官方文档。了解下它的渲染原理和v-model。

您还是别回复了,谢谢

**Comment by boomboy4** [comment]
的确有这个问题 没有对应的option的时候 默认赋值了value给label
<img width="187" alt="1694679166341" src="https://github.com/element-plus/element-plus/assets/37095891/cc0e5ad6-4fe9-44f8-b9c0-fd1420640d28">
但就是取舍吧 显示不显示都有它的说法

**Comment by milo-xiaomeng** [comment]
> 的确有这个问题 没有对应的option的时候 默认赋值了value给label <img alt="1694679166341" width="187" src="https://user-images.githubusercontent.com/37095891/267906700-cc0e5ad6-4fe9-44f8-b9c0-fd1420640d28.png"> 但就是取舍吧，这里沿用了之前element的操作逻辑，显示不显示都有它的说法 我觉得不算Bug

嗯,虽然我不清楚从一代开始这样做的原因,而且我还发现大部分ui 库都是这样。
但是目前看起来与原生一致效果好点啊,我不清楚你们会考虑优化这点吗。

**Comment by bobohuochai** [comment]
确实这个默认行为表现很奇怪诶，有什么特殊考虑嘛

**Comment by tongwoo** [comment]
这个很早就发现了，官方应该不会改了，我个人认为默认情况下不应该把值显示出来，因为列表数据没有这个值，或者给个选项交给使用者决定。

说到这个问题，我这边是特别频繁出现在加载表单的时候，这时候详情数据加载好了并赋值，几个下拉框的列表数据还没加载完，导致先显示了id，测试还跟我说是bug。😂

**Comment by L1yp** [comment]
确实，应该优化，如果options里面没有应该当成未选择

**Comment by milo-xiaomeng** [comment]
> 这个很早就发现了，官方应该不会改了，我个人认为默认情况下不应该把值显示出来，因为列表数据没有这个值，或者给个选项交给使用者决定。
> 
> 说到这个问题，我这边是特别频繁出现在加载表单的时候，这时候详情数据加载好了并赋值，几个下拉框的列表数据还没加载完，导致先显示了id，测试还跟我说是bug。😂

我最近开了vuetifyjs和primevue,这两个UI 框架就没有这个问题。。

**Comment by enjoy-myLife** [comment]
亟待解决啊，应该这种情况太常见了，比如后端把可选项的某条数据删了，但是返回的表单数据没变，导致表单数据没有匹配到数据回显了value，那测试和产品肯定说是bug了，如果这时候后端不做校验值有效性，那就更炸裂了，前端还需要遍历比对值是否存在

**Comment by kooriookami** [comment]
#15031 你们可以battle一下 :D

**Comment by L1yp** [comment]
select还有一个离谱的问题，点击clear按钮会emit一个空字符串出来，当我的value是number 或者object的时候真是麻烦，要自己处理转换一下

**Comment by kooriookami** [comment]
> select还有一个离谱的问题，点击clear按钮会emit一个空字符串出来，当我的value是number 或者object的时候真是麻烦，要自己处理转换一下

我看最新的代码，清空的时候会返回undefined了

**Comment by L1yp** [comment]
> > select还有一个离谱的问题，点击clear按钮会emit一个空字符串出来，当我的value是number 或者object的时候真是麻烦，要自己处理转换一下
> 
> 我看最新的代码，清空的时候会返回undefined了

那真是太棒了 我去测试下🤭

**Comment by kooriookami** [comment]
统一为不匹配时显示value值

**Comment by L1yp** [comment]
> 一为不匹配时显示value

value是object时呢

**Comment by kevindaizj** [comment]
> 统一为不匹配时显示value值

还是应该要考虑特殊情况的。
一个常见的场景是当用户预设了一个默认值（`id`），但此时`options`尚在加载中。在这期间，界面会暂时展示`id`而非实际选项内容。用户体验就挺差的。

这个场景并不是 「**不匹配**」，而是 「**尚未确定是否有匹配项（需等待确定）**」。 应该区分这两者。

**Comment by wweggplant** [comment]
解决办法就是自己写一个Select组件，官方估计不会管了。这个问题是比较头疼
