### ISSUE TITLE
[Component] [input, select] <el-input> <el-select> do not allow input changes / interaction without v-model

### ISSUE THREAD

**Issue by dreis2211** [element-plus/element-plus#14241]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-input`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGZvcm0+XG4gICAgPGVsLWlucHV0IHR5cGU9XCJ0ZXh0XCIgcGxhY2Vob2xkZXI9XCJUeXBlIHNvbWV0aGluZ1wiIG5hbWU9XCJmb3JtX2lucHV0XCIvPlxuICAgIDxlbC1zZWxlY3Q+XG4gICAgICA8ZWwtb3B0aW9uIHZhbHVlPVwidmFsdWUxXCIga2V5PVwia2V5MVwiIGxhYmVsPVwiTGFiZWwgMVwiPjwvZWwtb3B0aW9uPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Zvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Consider the following snippet.
```vue
<template>
  <form>
    <el-input type="text" placeholder="Type something" name="form_input"/>
    <el-select>
      <el-option value="value1" key="key1" label="Label 1"></el-option>
    </el-select>
  </form>
</template>

<script lang="ts" setup>

</script>
```

- Try to type any input or try to select an option from the select element.
- Notice no change in either the input or select

### What is Expected?

Native input functions still work. 

### What is actually happening?

Input is not reflected in native element

### Additional comments

The input is used to send form data and not anywhere inside a component. While maybe unusual, having a v-model should not be required to be able to interact with an `<input>` field. Element Plus is used here to have a properly styled input element, nothing more. (In other places of our app it's used with v-model btw.)

**Maybe interesting to note**: `<el-input-number />` does exactly what I'm expecting. It still allows interaction without having a `v-model` attribute set.

Cheers 👋

**Comment by kooriookami** [comment]
It's not a bug, you need use `v-model` to bind the compoents. Native input isn't wrote for Vue but el-input is.

**Comment by dreis2211** [comment]
@kooriookami Thanks for the answer, but maybe you have overseen that `<el-input-number />` does exactly what I'm expecting. It's just inconsistent.

**Comment by kooriookami** [comment]
Well, maybe we need to discuss the behavior without `v-model`. The binding value shouldn't be changed, but the change event could be triggered.

**Comment by dreis2211** [comment]
The element should be still usable - even without a model binding.

**Comment by kooriookami** [comment]
You can share your idea in [discussions](https://github.com/element-plus/element-plus/discussions), every one can talk your topic.
