### ISSUE TITLE
[Feature Request] Search engine in public doc

### ISSUE THREAD

**Issue by AubSs** [element-plus/element-plus#1425]
### Existing Component
No

### Component Name
Search engine on public doc

### Description
As it seems, search engine on top of public https://element-plus.org doesn't work.
Maybe using Algolia to help users finding what they need instead of posting issues should be considered.

Algolia help open source project by providing a search engine base on IA. You can take a look at https://www.algolia.com/for-open-source

**Comment by zazzaz** [comment]
will do thanks

**Comment by iamkun** [comment]
done
