### ISSUE TITLE
[TypeScript] [upload] clone下项目 build 报错  The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

### ISSUE THREAD

**Issue by G1King** [element-plus/element-plus#14277]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.12`
- Browser / OS: `Microsoft Edge 版本 116.0.1938.76 (正式版本) (x86_64) / macos 10.15.7`
- Build Tool: `Rollup`

### Related Component

- `el-upload`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

clone 下项目 pnpm install --- pnpm build  

The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

### What is Expected?

正常打包

### What is actually happening?

打包失败 

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
在 dev 分支没有复现你说的问题，可以提供一下 node 版本，pnpm 版本这些信息吗？

**Comment by G1King** [comment]
node 18.16  pnpm 8.4

**Comment by G1King** [comment]
@HeftyKoo  node 18.16 pnpm 8.4

**Comment by HeftyKoo** [comment]
> @HeftyKoo node 18.16 pnpm 8.4

建议使用 node 16 试一下，EP 目前还没有支持node 18
