### ISSUE TITLE
[Bug Report] Empty date-picker data, pop-up select time selection status is not cleared

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#1427]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
windows/chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/wukang0718/pen/WNoQqeQ

### Steps to reproduce
Select time, click clear, select at click time

### What is Expected?
The selected state can be cleared

### What is actually happening?
The selected state was not cleared, or the method of clearing was not revealed

**Comment by zazzaz** [comment]
I don't think this is a good way to clear value.

**Comment by liushuiyuan001** [comment]
I have a pr

**Comment by kooriookami** [comment]
It seems has been resolved.
