### ISSUE TITLE
[Component] [descriptions-item, descriptions] ElDescriptionsItem 绑定自定义指令不执行

### ISSUE THREAD

**Issue by RJQingHuan** [element-plus/element-plus#14275]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `edge/windows`
- Build Tool: `Vite`

### Related Component

- `el-descriptions-item`
- `el-descriptions`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCB2VGVzdCA9IChlbCkgPT4ge1xuICBjb25zb2xlLmxvZyhlbClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgdi10ZXN0PmZvbzwvZGl2PlxuICA8RWxEZXNjcmlwdGlvbnM+XG4gICAgICA8RWxEZXNjcmlwdGlvbnNJdGVtIHYtdGVzdCBsYWJlbD1cIjIzM1wiPlxuICAgICAgICBiYXJcbiAgICAgIDwvRWxEZXNjcmlwdGlvbnNJdGVtPlxuICAgIDwvRWxEZXNjcmlwdGlvbnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

打开示例代码查看控制台

### What is Expected?

指令正常执行

### What is actually happening?

指令未执行

### Additional comments

_(empty)_

**Comment by RJQingHuan** [comment]
v-show同样无效

**Comment by hickeyhub** [comment]
> v-show同样无效
指令语法应该是一个Object，你给的是一个function, 亲测官方例子可以正常执行log
