### ISSUE TITLE
[i18n] [All] 官网无法切换中文

### ISSUE THREAD

**Issue by southliu** [element-plus/element-plus#14297]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/en-US/)

### Steps to reproduce

进入官网点击右上角切换国际化，无法切换中文。
![image](https://github.com/element-plus/element-plus/assets/26358837/faffa60b-4be0-4609-8217-98eb75a8c06a)

输入https://element-plus.org/zh-CN/就显示404。
![image](https://github.com/element-plus/element-plus/assets/26358837/a26c6bb6-d66e-40d7-93c2-c150e40d4319)

### What is Expected?

可以点击切换中文。

### What is actually happening?

无法切换中文。

### Additional comments

_(empty)_

**Comment by iamkun** [comment]
will fix soon

**Comment by iamkun** [comment]
请暂时先使用英文官网 会尽快修复这个问题

**Comment by icecream8086** [comment]
+1 前几天还是好的

**Comment by buchiyv1119** [comment]
很糟糕

**Comment by back-sir** [comment]
+1 刚刚发现

**Comment by old-gang** [comment]
哇~是糟糕的感觉

**Comment by wbxl2000** [comment]
+1

**Comment by yhw2003** [comment]
+1 英文苦手

**Comment by hr1201** [comment]
+1

**Comment by WalterBrightHub** [comment]
+1

**Comment by iamkun** [comment]
国内镜像站已恢复 https://element-plus.gitee.io/zh-CN/
