### ISSUE TITLE
### Slider

### ISSUE THREAD

**Issue by Ryan2128** [element-plus/element-plus#143]

**Comment by Ryan2128** [comment]
90% completed, waiting for InputNumber & Tooltip refactored.

[commit](https://github.com/Ryan2128/element-plus/commit/364d8404d1aecac349ac414d28882aa9c5b38e9a)

**Comment by JeremyWuuuuu** [comment]
Neat, you can try attach `popper` on this is the internal tooltip for us developers to use, and also if you find any bug please feel free to raise an issue and assign to me

**Comment by Ryan2128** [comment]
> Neat, you can try attach `popper` on this is the internal tooltip for us developers to use, and also if you find any bug please feel free to raise an issue and assign to me

Yes, I will try it after get off work. 😁
