### ISSUE TITLE
[Component] [date-picker] ElDatePicker shows the wrong time format when the user set format to LLL

### ISSUE THREAD

**Issue by cuongle-hdwebsoft** [element-plus/element-plus#14305]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'`
- Build Tool: `Other`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxEYXRlUGlja2VyLCBkYXlqcywgdmVyc2lvbiBhcyBlbGVtZW50VmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmltcG9ydCBsb2NhbGl6ZWRGb3JtYXQgZnJvbSAnLi9sb2NhbGl6ZWRGb3JtYXQnXG5cbmRheWpzLmV4dGVuZChsb2NhbGl6ZWRGb3JtYXQpXG5cbmNvbnN0IGRlZmF1bHRUaW1lID0gcmVmKG5ldyBEYXRlKCkpO1xuXG5jb25zdCBlbERhdGVQaWNrZXJSZWYxID0gcmVmPEluc3RhbmNlVHlwZTx0eXBlb2YgRWxEYXRlUGlja2VyPj4oKVxuY29uc3QgZWxEYXRlUGlja2VyUmVmMiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsRGF0ZVBpY2tlcj4+KClcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cInNwYWNlLWJldHdlZW5cIj5cbiAgICA8RWxEYXRlUGlja2VyXG4gICAgICByZWY9XCJlbERhdGVQaWNrZXJSZWYxXCJcbiAgICAgIDptb2RlbC12YWx1ZT1cImRlZmF1bHRUaW1lXCIgXG4gICAgICBmb3JtYXQ9XCJMTExcIiBcbiAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICA6Y2xlYXJhYmxlPVwiZmFsc2VcIlxuICAgIC8+XG5cbiAgICA8RWxEYXRlUGlja2VyXG4gICAgICByZWY9XCJlbERhdGVQaWNrZXJSZWYyXCJcbiAgICAgIDptb2RlbC12YWx1ZT1cImRlZmF1bHRUaW1lXCIgXG4gICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgOmNsZWFyYWJsZT1cImZhbHNlXCJcbiAgICAvPiAgXG4gIDwvZGl2PlxuXG4gIDxkaXY+dnVlOiB7eyB2dWVWZXJzaW9uIH19PC9kaXY+XG4gIDxkaXY+ZWxlbWVudDoge3sgZWxlbWVudFZlcnNpb24gfX08L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5zcGFjZS1iZXR3ZWVuIHtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvbG9jYWxpemVkRm9ybWF0LmpzIjoiaW1wb3J0IHsgRk9STUFUX0RFRkFVTFQgfSBmcm9tICcuL2NvbnN0YW50JztcbmltcG9ydCB7IHUsIGVuZ2xpc2hGb3JtYXRzIH0gZnJvbSAnLi91dGlscyc7XG5leHBvcnQgZGVmYXVsdCAoZnVuY3Rpb24gKG8sIGMsIGQpIHtcbiAgdmFyIHByb3RvID0gYy5wcm90b3R5cGU7XG4gIHZhciBvbGRGb3JtYXQgPSBwcm90by5mb3JtYXQ7XG4gIGQuZW4uZm9ybWF0cyA9IGVuZ2xpc2hGb3JtYXRzO1xuXG4gIHByb3RvLmZvcm1hdCA9IGZ1bmN0aW9uIChmb3JtYXRTdHIpIHtcbiAgICBpZiAoZm9ybWF0U3RyID09PSB2b2lkIDApIHtcbiAgICAgIGZvcm1hdFN0ciA9IEZPUk1BVF9ERUZBVUxUO1xuICAgIH1cblxuICAgIHZhciBfdGhpcyQkbG9jYWxlID0gdGhpcy4kbG9jYWxlKCksXG4gICAgICAgIF90aGlzJCRsb2NhbGUkZm9ybWF0cyA9IF90aGlzJCRsb2NhbGUuZm9ybWF0cyxcbiAgICAgICAgZm9ybWF0cyA9IF90aGlzJCRsb2NhbGUkZm9ybWF0cyA9PT0gdm9pZCAwID8ge30gOiBfdGhpcyQkbG9jYWxlJGZvcm1hdHM7XG5cbiAgICB2YXIgcmVzdWx0ID0gdShmb3JtYXRTdHIsIGZvcm1hdHMpO1xuICAgIHJldHVybiBvbGRGb3JtYXQuY2FsbCh0aGlzLCByZXN1bHQpO1xuICB9O1xufSk7Iiwic3JjL3V0aWxzLmpzIjoiLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lIGltcG9ydC9wcmVmZXItZGVmYXVsdC1leHBvcnRcbmV4cG9ydCB2YXIgdCA9IGZ1bmN0aW9uIHQoZm9ybWF0KSB7XG4gIHJldHVybiBmb3JtYXQucmVwbGFjZSgvKFxcW1teXFxdXStdKXwoTU1NTXxNTXxERHxkZGRkKS9nLCBmdW5jdGlvbiAoXywgYSwgYikge1xuICAgIHJldHVybiBhIHx8IGIuc2xpY2UoMSk7XG4gIH0pO1xufTtcbmV4cG9ydCB2YXIgZW5nbGlzaEZvcm1hdHMgPSB7XG4gIExUUzogJ2g6bW06c3MgQScsXG4gIExUOiAnaDptbSBBJyxcbiAgTDogJ01NL0REL1lZWVknLFxuICBMTDogJ01NTU0gRCwgWVlZWScsXG4gIExMTDogJ01NTU0gRCwgWVlZWSBoOm1tIEEnLFxuICBMTExMOiAnZGRkZCwgTU1NTSBELCBZWVlZIGg6bW0gQSdcbn07XG5leHBvcnQgdmFyIHUgPSBmdW5jdGlvbiB1KGZvcm1hdFN0ciwgZm9ybWF0cykge1xuICByZXR1cm4gZm9ybWF0U3RyLnJlcGxhY2UoLyhcXFtbXlxcXV0rXSl8KExUUz98bHsxLDR9fEx7MSw0fSkvZywgZnVuY3Rpb24gKF8sIGEsIGIpIHtcbiAgICB2YXIgQiA9IGIgJiYgYi50b1VwcGVyQ2FzZSgpO1xuICAgIHJldHVybiBhIHx8IGZvcm1hdHNbYl0gfHwgZW5nbGlzaEZvcm1hdHNbYl0gfHwgdChmb3JtYXRzW0JdKTtcbiAgfSk7XG59OyIsInNyYy9jb25zdGFudC5qcyI6ImV4cG9ydCB2YXIgU0VDT05EU19BX01JTlVURSA9IDYwO1xuZXhwb3J0IHZhciBTRUNPTkRTX0FfSE9VUiA9IFNFQ09ORFNfQV9NSU5VVEUgKiA2MDtcbmV4cG9ydCB2YXIgU0VDT05EU19BX0RBWSA9IFNFQ09ORFNfQV9IT1VSICogMjQ7XG5leHBvcnQgdmFyIFNFQ09ORFNfQV9XRUVLID0gU0VDT05EU19BX0RBWSAqIDc7XG5leHBvcnQgdmFyIE1JTExJU0VDT05EU19BX1NFQ09ORCA9IDFlMztcbmV4cG9ydCB2YXIgTUlMTElTRUNPTkRTX0FfTUlOVVRFID0gU0VDT05EU19BX01JTlVURSAqIE1JTExJU0VDT05EU19BX1NFQ09ORDtcbmV4cG9ydCB2YXIgTUlMTElTRUNPTkRTX0FfSE9VUiA9IFNFQ09ORFNfQV9IT1VSICogTUlMTElTRUNPTkRTX0FfU0VDT05EO1xuZXhwb3J0IHZhciBNSUxMSVNFQ09ORFNfQV9EQVkgPSBTRUNPTkRTX0FfREFZICogTUlMTElTRUNPTkRTX0FfU0VDT05EO1xuZXhwb3J0IHZhciBNSUxMSVNFQ09ORFNfQV9XRUVLID0gU0VDT05EU19BX1dFRUsgKiBNSUxMSVNFQ09ORFNfQV9TRUNPTkQ7IC8vIEVuZ2xpc2ggbG9jYWxlc1xuXG5leHBvcnQgdmFyIE1TID0gJ21pbGxpc2Vjb25kJztcbmV4cG9ydCB2YXIgUyA9ICdzZWNvbmQnO1xuZXhwb3J0IHZhciBNSU4gPSAnbWludXRlJztcbmV4cG9ydCB2YXIgSCA9ICdob3VyJztcbmV4cG9ydCB2YXIgRCA9ICdkYXknO1xuZXhwb3J0IHZhciBXID0gJ3dlZWsnO1xuZXhwb3J0IHZhciBNID0gJ21vbnRoJztcbmV4cG9ydCB2YXIgUSA9ICdxdWFydGVyJztcbmV4cG9ydCB2YXIgWSA9ICd5ZWFyJztcbmV4cG9ydCB2YXIgREFURSA9ICdkYXRlJztcbmV4cG9ydCB2YXIgRk9STUFUX0RFRkFVTFQgPSAnWVlZWS1NTS1ERFRISDptbTpzc1onO1xuZXhwb3J0IHZhciBJTlZBTElEX0RBVEVfU1RSSU5HID0gJ0ludmFsaWQgRGF0ZSc7IC8vIHJlZ2V4XG5cbmV4cG9ydCB2YXIgUkVHRVhfUEFSU0UgPSAvXihcXGR7NH0pWy0vXT8oXFxkezEsMn0pP1stL10/KFxcZHswLDJ9KVtUdFxcc10qKFxcZHsxLDJ9KT86PyhcXGR7MSwyfSk/Oj8oXFxkezEsMn0pP1suOl0/KFxcZCspPyQvO1xuZXhwb3J0IHZhciBSRUdFWF9GT1JNQVQgPSAvXFxbKFteXFxdXSspXXxZezEsNH18TXsxLDR9fER7MSwyfXxkezEsNH18SHsxLDJ9fGh7MSwyfXxhfEF8bXsxLDJ9fHN7MSwyfXxaezEsMn18U1NTL2c7IiwiX28iOnt9fQ==)

### Steps to reproduce

- Click on the first date picker
- Confirm that time input shows the date format
- Click on the second date picker
- Confirm that time input shows the time format

### What is Expected?

The time input should show the time format

### What is actually happening?

The time input does not show the time format

### Additional comments

_(empty)_

**Comment by TomatoDroid** [comment]
There is no problem with the example inside the link.But there is a syntax error here: replace `:model-value` with` v-model`, and you can toggle time.
<img width="1534" alt="image" src="https://github.com/element-plus/element-plus/assets/22388686/efc4cb63-a07f-42cb-a96c-f82347031504">

**Comment by cuongle-hdwebsoft** [comment]
Could you explain to me what is the purpose of this input? @TomatoDroid 

![CleanShot 2023-09-16 at 19 30 08@2x](https://github.com/element-plus/element-plus/assets/102006695/99155143-71de-4fe4-b139-af07fd715831)
