### ISSUE TITLE
[Component] [collapse-item] el-collapse-item in el-form is broken - clicking on its header triggers form post

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#14304]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 117 / Firefox 117`
- Build Tool: `Webpack`

### Related Component

- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gYWN0aW9uPVwiaHR0cHM6Ly9nb29nbGUuY29tXCI+XG4gIDxlbC1jb2xsYXBzZT5cbiAgPGVsLWNvbGxhcHNlLWl0ZW0gdGl0bGU9XCJjb2xsYXBzZVwiLz5cbiAgPC9lbC1jb2xsYXBzZT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Clicking on el-collapse-item header in el-form triggers post due to div tag was replaced with button:
https://github.com/element-plus/element-plus/commit/d791229a6aaf695f451b6c4afedc2fd7fa764b79

### What is Expected?

Form is not posted

### What is actually happening?

Form is posted

### Additional comments

_(empty)_

**Comment by bribar** [comment]
@MonkeyMaster I'm experiencing this same issue. v2.3.12 works fine, upgrade to v2.3.14 collapse items seem to append a "?" onto the end of the url causing a reload. My collapse component is within a form component too. Quick fix is stay on v2.3.12, but would be nice if the button didn't cause this.

**Comment by btea** [comment]
Sorry for the inconvenience caused to you, maybe you can add `@submit.prevent` to the `el-form` component. [playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gYWN0aW9uPVwiaHR0cHM6Ly9nb29nbGUuY29tXCIgQHN1Ym1pdC5wcmV2ZW50PlxuICA8ZWwtY29sbGFwc2U+XG4gIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiY29sbGFwc2VcIi8+XG4gIDwvZWwtY29sbGFwc2U+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by MonkeyMaster** [comment]
@btea 
shouldn't the component be fixed?
Now all forms with el-collapse are broken, we also rolled back to 2.3.12

**Comment by btea** [comment]
@MonkeyMaster  We will fix this issue, and the above only provides a temporary solution.
