### ISSUE TITLE
[Component] [select] ios15系统中，el-select组件-远程搜索组件，option列表需要点击两次才能选中值，component el-select under ios15 need to click twice to trigger selected event

### ISSUE THREAD

**Issue by SubtitleTassel** [element-plus/element-plus#14303]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.32`
- Browser / OS: `wkwebview  IOS15`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbixvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHZhbHVlPXJlZihcIlwiKTtcbmNvbnN0IGxpc3QgPSByZWY8YW55W10+KFtdKVxuY29uc3Qgb3B0aW9ucyA9IHJlZjxhbnlbXT4oW10pXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxuXG5jb25zdCByZW1vdGVNZXRob2QgPSAocXVlcnk6IHN0cmluZykgPT4ge1xuICBpZiAocXVlcnkpIHtcbiAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgICBvcHRpb25zLnZhbHVlID0gbGlzdC52YWx1ZTtcbiAgICB9LCAyMDApXG4gIH1cbn1cblxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBsaXN0LnZhbHVlID1be2xhYmVsOlwiYXBwbGVcIix2YWx1ZTpcImFwcGxlXCJ9LHtsYWJlbDpcIm11c2ljXCIsdmFsdWU6XCJtdXNpY1wifSx7bGFiZWw6XCJmcnVpdFwiLHZhbHVlOlwiZnJ1aXRcIn0sXVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICByZW1vdGVcbiAgICAgICAgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXkuIvkuIDkvY3lpITnkIbkurpcIlxuICAgICAgICA6cmVtb3RlLW1ldGhvZD1cInJlbW90ZU1ldGhvZFwiXG4gICAgICAgIDpsb2FkaW5nPVwibG9hZGluZ1wiXG4gICAgICAgIGNsZWFyYWJsZVxuICAgICAgPlxuICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

使用苹果手机13pro，打开内嵌到app中的小程序，app使用wkwebview渲染小程序，使用el-select远程搜索组件，

### What is Expected?

el-select组件，el-option在ios上点击一次选上值

### What is actually happening?

el-option需要点击两次el-select才有值，第一次点击没有触发点击事件。

### Additional comments

_(empty)_

**Comment by yeminxuan** [comment]
Element Plus is a **desktop** component library based on Vue.js 3.0. Element Plus is not a component library designed for applets, applets suggest using 'vant', 'weapp' etc
