### ISSUE TITLE
[Feature Request] select add header slot and bottom slot

### ISSUE THREAD

**Issue by poem-love** [element-plus/element-plus#1430]
### Existing Component
Yes

### Component Name
select

### Description
can select add header slot and bottom slot
some group datas show like table need header and pagebar

**Comment by zazzaz** [comment]
you can use custom template

https://element-plus.org/#/en-US/component/select#custom-template

**Comment by poem-love** [comment]
> you can use custom template
> 
> https://element-plus.org/#/en-US/component/select#custom-template

this only can change  one row in a body.   not header and footer.you can view like this  https://vue-select.org/api/slots.html#footer

**Comment by monkeychennn** [comment]
You can implement it like this:
```javascript
<el-select v-model="value" placeholder="请选择">
  <div>header</div>
  <el-option
    v-for="item in cities"
    :key="item.value"
    :label="item.label"
    :value="item.value">
    <span style="float: left">{{ item.label }}</span>
    <span style="float: right; color: #8492a6; font-size: 13px">{{ item.value }}</span>
    </el-option>
  <div>footer</div>
</el-select>
```
![image](https://user-images.githubusercontent.com/16893289/108327350-46e95880-7206-11eb-9124-f50267eff277.png)

**Comment by poem-love** [comment]
> You can implement it like this:
> 
> ```js
> <el-select v-model="value" placeholder="请选择">
>   <div>header</div>
>   <el-option
>     v-for="item in cities"
>     :key="item.value"
>     :label="item.label"
>     :value="item.value">
>     <span style="float: left">{{ item.label }}</span>
>     <span style="float: right; color: #8492a6; font-size: 13px">{{ item.value }}</span>
>   </el-option>
>   <div>footer</div>
> </el-select>
> ```
> 
> ![image](https://user-images.githubusercontent.com/16893289/108327350-46e95880-7206-11eb-9124-f50267eff277.png)

this i do it before, when your data more than it can display,like 10 items. when scroll, it will not show header or footer.

**Comment by shengtann** [comment]
@zazzaz Hi, do you have any play for this feature, i have implemented it, maybe i can open a pull request.
![image](https://user-images.githubusercontent.com/16893289/109815014-1ffd3e80-7c6a-11eb-8443-a91cc88c63f3.png)

**Comment by kooriookami** [comment]
Please refer to `header` and `footer` slot in docs.
