### ISSUE TITLE
[Component] [select-v2] When I use filter in a table with tree data and lazy mode, an error will be throwed: "Cannot read properties of null (reading 'resetScrollTop')"

### ISSUE THREAD

**Issue by 497363983** [element-plus/element-plus#14316]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuY29uc3Qgc2V0dGluZ0NvbHVtbnMgPSByZWYoW1xuICB7XG4gICAgXCJrZXlcIjogXCJmbGRzcmZ2cFc2XCIsXG4gICAgXCJmaWVsZFwiOiB7XG4gICAgICBcImlkXCI6IFwiZmxkc3JmdnBXNlwiLFxuICAgICAgXCJ0eXBlXCI6IDQsXG4gICAgICBcIm5hbWVcIjogXCLlpJrpgIlcIixcbiAgICAgIFwicHJvcGVydHlcIjoge1xuICAgICAgICBcIm9wdGlvbnNcIjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcImFcIixcbiAgICAgICAgICAgIFwiaWRcIjogXCJvcHRkUGJTRFpXXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IDBcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcImNcIixcbiAgICAgICAgICAgIFwiaWRcIjogXCJvcHRKNFNzRUNSXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IDFcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwiY29sb3JcIjogMixcbiAgICAgICAgICAgIFwibmFtZVwiOiBcInZcIixcbiAgICAgICAgICAgIFwiaWRcIjogXCJvcHRNazdudWg0XCJcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIiBjXCIsXG4gICAgICAgICAgICBcImlkXCI6IFwib3B0S01LMWR4a1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiAzXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBcImlkXCI6IFwib3B0Smc5eVJQdlwiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiA0LFxuICAgICAgICAgICAgXCJuYW1lXCI6IFwiIHZcIlxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgXCJjb2xvclwiOiA1LFxuICAgICAgICAgICAgXCJuYW1lXCI6IFwiblwiLFxuICAgICAgICAgICAgXCJpZFwiOiBcIm9wdFFJYmVQQUpcIlxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwibVwiLFxuICAgICAgICAgICAgXCJpZFwiOiBcIm9wdGlWUEdLSWFcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogNlxuICAgICAgICAgIH1cbiAgICAgICAgXSxcbiAgICAgICAgXCJvcHRpb25zVHlwZVwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpc1ByaW1hcnlcIjogZmFsc2UsXG4gICAgICBcImRlc2NyaXB0aW9uXCI6IHtcbiAgICAgICAgXCJkaXNhYmxlU3luY1RvRm9ybURlc2NcIjogZmFsc2UsXG4gICAgICAgIFwiY29udGVudFwiOiBudWxsXG4gICAgICB9XG4gICAgfSxcbiAgICBcInRhYmxlXCI6IFwidGJseGFyZzh3a0RobWpXMVwiLFxuICAgIFwiY29uZmlnXCI6IHtcbiAgICAgIFwic2VwYXJhdG9yXCI6IFwiLFwiXG4gICAgfSxcbiAgICBcInJvb3RcIjogdHJ1ZSxcbiAgICBcImhhc0NoaWxkcmVuXCI6IGZhbHNlLFxuICAgIFwiY2hpbGRyZW5cIjogW11cbiAgfSxcbiAge1xuICAgIFwia2V5XCI6IFwiZmxkYUU0MGZrd1wiLFxuICAgIFwiZmllbGRcIjoge1xuICAgICAgXCJpZFwiOiBcImZsZGFFNDBma3dcIixcbiAgICAgIFwidHlwZVwiOiAxOCxcbiAgICAgIFwibmFtZVwiOiBcIuWNleWQkeWFs+iBlFwiLFxuICAgICAgXCJwcm9wZXJ0eVwiOiB7XG4gICAgICAgIFwidGFibGVJZFwiOiBcInRibDhacmxLM2hhSFRIZU1cIixcbiAgICAgICAgXCJtdWx0aXBsZVwiOiB0cnVlXG4gICAgICB9LFxuICAgICAgXCJpc1ByaW1hcnlcIjogZmFsc2UsXG4gICAgICBcImRlc2NyaXB0aW9uXCI6IHtcbiAgICAgICAgXCJkaXNhYmxlU3luY1RvRm9ybURlc2NcIjogZmFsc2UsXG4gICAgICAgIFwiY29udGVudFwiOiBudWxsXG4gICAgICB9XG4gICAgfSxcbiAgICBcInRhYmxlXCI6IFwidGJseGFyZzh3a0RobWpXMVwiLFxuICAgIFwiY29uZmlnXCI6IHtcbiAgICAgIFwic2VwYXJhdG9yXCI6IFwiLFwiXG4gICAgfSxcbiAgICBcInJvb3RcIjogdHJ1ZSxcbiAgICBcImhhc0NoaWxkcmVuXCI6IHRydWUsXG4gICAgXCJjaGlsZHJlblwiOiBbXVxuICB9LFxuICB7XG4gICAgXCJrZXlcIjogXCJmbGQ2eDNBT3k3XCIsXG4gICAgXCJmaWVsZFwiOiB7XG4gICAgICBcImlkXCI6IFwiZmxkNngzQU95N1wiLFxuICAgICAgXCJ0eXBlXCI6IDE4LFxuICAgICAgXCJuYW1lXCI6IFwi54i26K6w5b2VIDJcIixcbiAgICAgIFwicHJvcGVydHlcIjoge1xuICAgICAgICBcInRhYmxlSWRcIjogXCJ0Ymx4YXJnOHdrRGhtalcxXCIsXG4gICAgICAgIFwibXVsdGlwbGVcIjogZmFsc2VcbiAgICAgIH0sXG4gICAgICBcImlzUHJpbWFyeVwiOiBmYWxzZSxcbiAgICAgIFwiZGVzY3JpcHRpb25cIjoge1xuICAgICAgICBcImRpc2FibGVTeW5jVG9Gb3JtRGVzY1wiOiBmYWxzZSxcbiAgICAgICAgXCJjb250ZW50XCI6IG51bGxcbiAgICAgIH1cbiAgICB9LFxuICAgIFwidGFibGVcIjogXCJ0Ymx4YXJnOHdrRGhtalcxXCIsXG4gICAgXCJjb25maWdcIjoge1xuICAgICAgXCJzZXBhcmF0b3JcIjogXCIsXCJcbiAgICB9LFxuICAgIFwicm9vdFwiOiB0cnVlLFxuICAgIFwiaGFzQ2hpbGRyZW5cIjogZmFsc2UsXG4gICAgXCJjaGlsZHJlblwiOiBbXVxuICB9LFxuXSlcbmNvbnN0IGV4Y2VsRmllbGRzID0gcmVmKFtdKVxuY29uc3QgZmlsdGVycyA9IGNvbXB1dGVkKCgpID0+IHtcbiAgcmV0dXJuIHNldHRpbmdDb2x1bW5zLnZhbHVlLm1hcCgoaXRlbSkgPT4ge1xuICAgIHJldHVybiB7XG4gICAgICB0ZXh0OiBpdGVtLmZpZWxkLm5hbWUsXG4gICAgICB2YWx1ZTogaXRlbS5maWVsZC5uYW1lLFxuICAgIH1cbiAgfSlcbn0pXG5pbnRlcmZhY2UgZmllbGRNYXAge1xuICBrZXk6IHN0cmluZ1xuICBmaWVsZDogUmVjb3JkPHN0cmluZywgYW55PixcbiAgdGFibGU6IHN0cmluZ1xuICBleGNlbF9maWVsZDogc3RyaW5nIHwgdW5kZWZpbmVkXG4gIHJvb3Q6IGJvb2xlYW5cbiAgY29uZmlnOiB7XG4gICAgZm9ybWF0Pzogc3RyaW5nXG4gICAgc2VwYXJhdG9yPzogc3RyaW5nXG4gICAgYm9vbFZhbHVlPzoge1xuICAgICAgdHJ1ZTogc3RyaW5nW11cbiAgICAgIGZhbHNlOiBzdHJpbmdbXVxuICAgIH1cbiAgfVxuICBoYXNDaGlsZHJlbjogYm9vbGVhblxuICBjaGlsZHJlbj86IGZpZWxkTWFwW11cbn1cbmZ1bmN0aW9uIGZpbHRlckhhbmRsZXIoXG4gIHZhbHVlOiBzdHJpbmcsXG4gIHJvdzogZmllbGRNYXBcbikge1xuICByZXR1cm4gcm93LmZpZWxkLm5hbWUgPT09IHZhbHVlXG59XG5cbmFzeW5jIGZ1bmN0aW9uIGxvYWRMaW5rVGFibGUoXG4gIHJvdzogZmllbGRNYXAsXG4gIF86IGFueSxcbiAgcmVzb2x2ZTogKGRhdGE6IGZpZWxkTWFwW10pID0+IHZvaWQsXG4pIHtcbiAgc2V0VGltZW91dChhc3luYyAoKSA9PiB7XG4gICAgcm93LmNoaWxkcmVuID0gYXdhaXQgbmV3IFByb21pc2UoKHJlc29sdmUpID0+IHJlc29sdmUoW3tcbiAgICAgIGtleTogXCJ0ZXN0LVwiICsgcm93LmZpZWxkLmlkLFxuICAgICAgaGFzQ2hpbGRyZW46IGZhbHNlLFxuICAgICAgY2hpbGRyZW46IFtdLFxuICAgICAgZmllbGQ6IHtcbiAgICAgICAgbmFtZTogXCJ0ZXN0XCJcbiAgICAgIH0sXG4gICAgICB0YWJsZTogXCJ0YmwxXCIsXG4gICAgICBleGNlbF9maWVsZDogdW5kZWZpbmVkLFxuICAgICAgcm9vdDogZmFsc2UsXG4gICAgICBjb25maWc6IHt9XG4gICAgfV0pKVxuICAgIHJlc29sdmUocm93LmNoaWxkcmVuKVxuICB9LCAyMDAwKVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgc3RyaXBlIG1heC1oZWlnaHQ9XCIyNTBcIiA6ZGF0YT1cInNldHRpbmdDb2x1bW5zXCIgOmxvYWQ9XCJsb2FkTGlua1RhYmxlXCIgbGF6eSByb3cta2V5PVwia2V5XCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkJhc2UgRmllbGRcIiA6ZmlsdGVycz1cImZpbHRlcnNcIiA6ZmlsdGVyLW1ldGhvZD1cImZpbHRlckhhbmRsZXJcIiBwcm9wPVwiZmllbGQubmFtZVwiXG4gICAgICBmaWx0ZXItcGxhY2VtZW50PVwiYm90dG9tLWVuZFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAge3sgc2NvcGUucm93LmZpZWxkLm5hbWUgfX1cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkV4Y2VsRmllbGRcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInsgcm93IH1cIj5cbiAgICAgICAgPGVsLXNlbGVjdC12MiB2LW1vZGVsPVwicm93LmV4Y2VsX2ZpZWxkXCIgOm9wdGlvbnM9XCJleGNlbEZpZWxkcy5tYXAoKGkpID0+ICh7IGxhYmVsOiBpLm5hbWUsIHZhbHVlOiBpLm5hbWUgfSkpXG4gICAgICAgICAgXCIgZmlsdGVyYWJsZSBjbGVhcmFibGUgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. Use the filter of "Base Field" column
2. The error "Cannot read properties of null (reading 'resetScrollTop')" will be throwed.

### What is Expected?

No error

### What is actually happening?

It will throw an error "Cannot read properties of null (reading 'resetScrollTop')".

### Additional comments

Actually, it will cause the filter panel can't disappear probably.

**Comment by FrontEndDog** [comment]
Do not assign the return value of a method to `options` in the `<template></template>`,
Otherwise, this method will be executed every time when update.

**Comment by FrontEndDog** [comment]
This problem is not caused by `table` , but by `select-v2`, I have tried to fix it.

**Comment by 497363983** [comment]
> This problem is not caused by `table` , but by `select-v2`, I have tried to fix it.

Yes, I tried to comment the el-select-v2, and it worked as expected.

**Comment by 497363983** [comment]
> This problem is not caused by `table` , but by `select-v2`, I have tried to fix it.

Yes, I tried to comment the el-select-v2, and it worked as expected.
