### ISSUE TITLE
[TypeScript] [form] FormRules类型找不到

### ISSUE THREAD

**Issue by zhongzhaoli** [element-plus/element-plus#14336]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.14`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gY2xhc3M9XCJsb2dpbi1mb3JtXCIgOm1vZGVsPVwibG9naW5Gcm9tXCIgOnJ1bGVzPVwibG9naW5SdWxlc1wiPlxuICAgIDxkaXYgY2xhc3M9XCJ0aXRsZS1jb250YWluZXJcIj5cbiAgICAgIDxoMyBjbGFzcz1cInRpdGxlXCI+55So5oi355m75b2VPC9oMz5cbiAgICA8L2Rpdj5cbiAgICA8IS0tIHVzZXJuYW1lIC0tPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtaW5wdXQgcGxhY2Vob2xkZXI9XCJ1c2VybmFtZVwiIHYtbW9kZWw9XCJsb2dpbkZyb20udXNlcm5hbWVcIiBuYW1lPVwidXNlcm5hbWVcIiB0eXBlPVwidGV4dFwiPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPCEtLSBwYXNzd29yZCAtLT5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWlucHV0IHBsYWNlaG9sZGVyPVwicGFzc3dvcmRcIiB2LW1vZGVsPVwibG9naW5Gcm9tLnBhc3N3b3JkXCIgbmFtZT1cInBhc3N3b3JkXCIgdHlwZT1cInBhc3N3b3JkXCI+PC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8IS0tIOeZu+W9leaMiemSriAtLT5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMzBweFwiPueZu+W9lTwvZWwtYnV0dG9uPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG4vLyDmlbDmja7mupBcbmludGVyZmFjZSBMb2dpbkZvcm1Qcm9wcyB7XG4gIHVzZXJuYW1lOiBzdHJpbmdcbiAgcGFzc3dvcmQ6IHN0cmluZ1xufVxuY29uc3QgbG9naW5Gcm9tID0gcmVhY3RpdmU8TG9naW5Gb3JtUHJvcHM+KHtcbiAgdXNlcm5hbWU6ICdzdXBlci1hZG1pbicsXG4gIHBhc3N3b3JkOiAnMTIzNDU2J1xufSlcbi8vIOmqjOivgeinhOWImVxuY29uc3QgbG9naW5SdWxlcyA9IHJlYWN0aXZlPEZvcm1SdWxlcz4oe1xuICB1c2VybmFtZTogW3sgcmVxdWlyZWQ6IHRydWUsIHRyaWdnZXI6ICdibHVyJywgbWVzc2FnZTogJ+eUqOaIt+WQjeS4uuW/heWhq+mhuScgfV0sXG4gIHBhc3N3b3JkOiBbeyByZXF1aXJlZDogdHJ1ZSwgdHJpZ2dlcjogJ2JsdXInLCBtZXNzYWdlOiAn5a+G56CB5Li65b+F5aGr6aG5JyB9XVxufSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

import type { FormRules } from 'element-plus'

### What is Expected?

成功

### What is actually happening?

模块 ""element-plus"" 没有导出的成员 "FormRules"。你是想改用 "import FormRules from "element-plus"" 吗?

### Additional comments

我使用的vue add element-plus方式添加。

以下是vue项目中package.json中关于element-plus的安装版本：
"element-plus": "^1.0.2-beta.28",
"vue-cli-plugin-element-plus": "~0.0.13"

**Comment by FrontEndDog** [comment]
版本过旧  请升级EP版本

**Comment by zhongzhaoli** [comment]
感谢回答，我已经升级到了Element Plus Version: 2.3.14版本。还是没有FormRules。
