### ISSUE TITLE
[Style] [table] table组件中，使用 :empty::before 异常

### ISSUE THREAD

**Issue by heyXiaoT** [element-plus/element-plus#14332]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.14`
- Browser / OS: `Microsoft Edge 版本 117.0.2045.31 / Windows 11 22H2`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB0YWJsZURhdGEgPSByZWYoW10pO1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgYm9yZGVyIDpkYXRhPVwidGFibGVEYXRhXCIgY2xhc3M9XCJ0YWJsZS1jbGFzc1wiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJpbmRleFwiIGxhYmVsPVwi5bqP5Y+3XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCLlp5PlkI1cIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZD5cbi8qIOihqOagvOaVsOaNruS4uuepuuaXtuaYvuekuuKAlOKAlCovXG4udGFibGUtY2xhc3MgOmVtcHR5OjpiZWZvcmUge1xuICBjb250ZW50OiBcIi1cIjtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup>
import { ref } from 'vue'
const tableData = ref([]);

</script>

<template>
  <el-table border :data="tableData" class="table-class" style="width: 100%">
    <el-table-column type="index" label="序号" />
    <el-table-column prop="name" label="姓名" />
  </el-table>
</template>

<style scoped>
/* 表格数据为空时显示——*/
.table-class :empty::before {
  content: "-";
}
</style>

```

### What is Expected?

通过CSS :empty::before 设置了空值是 “xxx”后，不会出现多余的 “xxx”，而是正常渲染

### What is actually happening?

出现了异常的“xxx”值

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/30957584/734c8013-8588-495f-aaaa-4031c5b0d8d2)

**Comment by chenxch** [comment]
如果你想通过样式添加 占位符的话，那么你应该根据实际的dom渲染后的情况去编写css, 例如
```
.table-class :empty:not(tbody):not(.hidden-columns):not(.el-table__border-left-patch)::before {
  content: "-";
}
```
