### ISSUE TITLE
[Bug Report] select can't put it away when options change

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1434]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/vgbire/pen/poNjqZG

### Steps to reproduce
click the dropdown icon to expand the options.And then you can't put it away.
only you change the options list.this bug will appear

### What is Expected?
Put it away

### What is actually happening?
Can't put it away

**Comment by Ryan2128** [comment]
Same as #1207 #1300 

It is a bug of vue, the demo works well in version 3.0.2.

[vue 3 #2768](https://github.com/vuejs/vue-next/issues/2768)
[vue 3 #2829](https://github.com/vuejs/vue-next/issues/2829)

**Comment by Vgbire** [comment]
before Vue fix it, you can simply hide the icon to solve this problem temporary.

**Comment by Ryan2128** [comment]
Vue 3.0.7 has released. If still has problem, please reopen issue.
