### ISSUE TITLE
[Docs] [popconfirm] Popconfirm组件文档错误

### ISSUE THREAD

**Issue by qiushui7** [element-plus/element-plus#14340]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-popconfirm`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/popconfirm.html#attributes)

### Steps to reproduce

打开文档

### What is Expected?

文档Events下应该为事件名，Slots下应该为插槽名

### What is actually happening?

文档Events下为插槽名，Slots下为事件名

### Additional comments

![elment-plus文档错误](https://github.com/element-plus/element-plus/assets/107985463/dc1ab6dd-8dbd-4eb2-a690-2a27f37a1ce2)

**Comment by btea** [comment]
谢谢反馈，翻译问题，已修复！https://crowdin.com/translate/element-plus/801/en-zhcn?filter=basic&value=0
