### ISSUE TITLE
[Component] [dialog] el-dialog  set z-index:0  can't work properly

### ISSUE THREAD

**Issue by nothing-sy** [element-plus/element-plus#14369]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-demo-forked-2g59hw?file=/src/App.vue)

### Steps to reproduce

Set z-index to 0

### What is Expected?

The element z-index is 0

### What is actually happening?

The element z-index is default setting

### Additional comments

_(empty)_

**Comment by Liberty-liu** [comment]
https://github.com/element-plus/element-plus/blob/adfe2444dbbc7bbfaa058f0060d51c503e7b77c7/packages/components/dialog/src/use-dialog.ts#L38

See here if it is 0, nextZIndex() is executed

**Comment by nothing-sy** [comment]
@Liberty-liu Thanks.
