### ISSUE TITLE
[Style] [All] 新版Chrome浏览器上所有组件样式出现异常（包括官网）

### ISSUE THREAD

**Issue by mingle98** [element-plus/element-plus#14376]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: ` Chrome 版本 116.0.5845.187（正式版本） (arm64)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/design.html)

### Steps to reproduce

目前发现所有elementPlus组件在新版chrome浏览器上样式均出现异常，具体表现是padding异常、定位异常、表单样式异常等

### What is Expected?

样式兼容恢复正常

### What is actually happening?

样式异常

### Additional comments

_(empty)_

![截屏2023-09-22 下午5.53.01.png](https://pic.sl.al/gdrive/pic/2023-09-22/650d652573e25.png)
![截屏2023-09-22 下午5.53.14.png](https://pic.sl.al/gdrive/pic/2023-09-22/650d654259471.png)

**Comment by mingle98** [comment]
[补充异常截图](https://pic.sl.al/gdrive/pic/2023-09-22/650d6597d9935.png)

**Comment by btea** [comment]
![image](https://github.com/element-plus/element-plus/assets/24516654/58c02824-c753-4eee-a35f-0c95feb9d895)

It's normal on my device.

**Comment by yj-liuzepeng** [comment]
正常的

**Comment by z362831561** [comment]
同样的问题，在升级到Chrome117后打开官网无法正常显示
<img width="1271" alt="微信图片_20230926091117" src="https://github.com/element-plus/element-plus/assets/9544659/04e29381-f4fe-4e4c-b595-c19fa04ed5a5">
<img width="761" alt="微信图片_20230926091136" src="https://github.com/element-plus/element-plus/assets/9544659/82a34d70-d34b-485d-9220-6c2913fc7111">

**Comment by z362831561** [comment]
补充一下，同一个电脑，同样网络环境，换用Edge浏览器打开element-plus官网正常

<img width="1244" alt="微信图片_20230926091518" src="https://github.com/element-plus/element-plus/assets/9544659/3525c097-f1ea-4aec-abac-bdc2c257d51f">

<img width="589" alt="微信图片_20230926091511" src="https://github.com/element-plus/element-plus/assets/9544659/3ba58bff-8920-4dfd-8906-8f50d73d2e53">

**Comment by cuifuan** [comment]
同样的问题

**Comment by cuifuan** [comment]
插件的原因，把所有插件禁用，排查下，我的是 JourneyDraw 插件影响

**Comment by z362831561** [comment]
> 插件的原因，把所有插件禁用，排查下，我的是 JourneyDraw 插件影响

禁用JourneyDraw 后好了，多谢
