### ISSUE TITLE
[Component] [collapse, collapse-item] el-collapse title 插槽样式污染(Slot style pollution)

### ISSUE THREAD

**Issue by wjw020206** [element-plus/element-plus#14372]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 117.0.5938.89`
- Build Tool: `Vite`

### Related Component

- `el-collapse`
- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+PC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlPlxuICAgIDxlbC1jb2xsYXBzZS1pdGVtPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgPGRpdiBjbGFzcz1cInRpdGxlLWNvbnRlbnRcIj5cbiAgICAgICAgICA8IS0tIOW3puS+p+WMuuWfnyAtLT5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwibGVmdC1zZWN0aW9uXCI+XG4gICAgICAgICAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogcmVkO1wiPua1i+ivleaWh+acrDE8L2Rpdj5cbiAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiBncmVlbjtcIj7mtYvor5XmlofmnKwyPC9kaXY+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIDpkZWVwKC5lbC1jb2xsYXBzZS1pdGVtX19oZWFkZXIpIHtcbiAgaGVpZ2h0OiBhdXRvO1xufVxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIC50aXRsZS1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICB3aWR0aDogMTAwJTtcbiAgbWFyZ2luLXJpZ2h0OiAyNHB4O1xufVxuXG4uZWwtY29sbGFwc2UgLmVsLWNvbGxhcHNlLWl0ZW0gLnRpdGxlLWNvbnRlbnQgLmxlZnQtc2VjdGlvbiB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG59XG48L3N0eWxlPlxuXG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

【CN】title插槽中放入的元素会被自动继承.el-collapse-item__header的高度
【EN】The element placed in the title slot will automatically inherit the height of .el-collapse-item__header

### What is Expected?

【CN】title插槽中的元素不自动继承.el-collapse-item__header的高度
【EN】Elements in the title slot do not automatically inherit the height of .el-collapse-item__header

### What is actually happening?

【CN】title插槽中的元素自动继承了.el-collapse-item__header的高度
【EN】The element in the title slot automatically inherits the height of .el-collapse-item__header

### Additional comments
【CN】这是我想实现的效果
【EN】This is the effect I want to achieve
![709e5c3bcbfc8d8ef822d073b283df8](https://github.com/element-plus/element-plus/assets/59106659/28710537-a250-4022-a699-3c150f4a47dc)

![image](https://github.com/element-plus/element-plus/assets/59106659/064111bf-f7b1-4b2b-ac51-c225f7d6f6f3)

**Comment by makedopamine** [comment]
Overwrite the `line-height` CSS property. [link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+PC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlPlxuICAgIDxlbC1jb2xsYXBzZS1pdGVtPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgPGRpdiBjbGFzcz1cInRpdGxlLWNvbnRlbnRcIj5cbiAgICAgICAgICA8IS0tIOW3puS+p+WMuuWfnyAtLT5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwibGVmdC1zZWN0aW9uXCI+XG4gICAgICAgICAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogcmVkO1wiPua1i+ivleaWh+acrDE8L2Rpdj5cbiAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiBncmVlbjtcIj7mtYvor5XmlofmnKwyPC9kaXY+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIDpkZWVwKC5lbC1jb2xsYXBzZS1pdGVtX19oZWFkZXIpIHtcbiAgaGVpZ2h0OiBhdXRvO1xufVxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIC50aXRsZS1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICB3aWR0aDogMTAwJTtcbiAgbWFyZ2luLXJpZ2h0OiAyNHB4O1xufVxuXG4uZWwtY29sbGFwc2UgLmVsLWNvbGxhcHNlLWl0ZW0gLnRpdGxlLWNvbnRlbnQgLmxlZnQtc2VjdGlvbiB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIGxpbmUtaGVpZ2h0OiAxLjVcbn1cbjwvc3R5bGU+XG5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by wjw020206** [comment]
> Overwrite the `line-height` CSS property. [link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+PC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbGxhcHNlPlxuICAgIDxlbC1jb2xsYXBzZS1pdGVtPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgPGRpdiBjbGFzcz1cInRpdGxlLWNvbnRlbnRcIj5cbiAgICAgICAgICA8IS0tIOW3puS+p+WMuuWfnyAtLT5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwibGVmdC1zZWN0aW9uXCI+XG4gICAgICAgICAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogcmVkO1wiPua1i+ivleaWh+acrDE8L2Rpdj5cbiAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiBncmVlbjtcIj7mtYvor5XmlofmnKwyPC9kaXY+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gIDwvZWwtY29sbGFwc2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIDpkZWVwKC5lbC1jb2xsYXBzZS1pdGVtX19oZWFkZXIpIHtcbiAgaGVpZ2h0OiBhdXRvO1xufVxuLmVsLWNvbGxhcHNlIC5lbC1jb2xsYXBzZS1pdGVtIC50aXRsZS1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICB3aWR0aDogMTAwJTtcbiAgbWFyZ2luLXJpZ2h0OiAyNHB4O1xufVxuXG4uZWwtY29sbGFwc2UgLmVsLWNvbGxhcHNlLWl0ZW0gLnRpdGxlLWNvbnRlbnQgLmxlZnQtc2VjdGlvbiB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIGxpbmUtaGVpZ2h0OiAxLjVcbn1cbjwvc3R5bGU+XG5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

Thank you very much for your reply. This is the effect I want. Could you please tell me what the principle of line-height: 1.5 is?

**Comment by makedopamine** [comment]
It means that the height of a single line of text is the font size * 1.5. Plus, the property value can be specified with different type, referring to the [doc](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) for details.

**Comment by wjw020206** [comment]
> It means that the height of a single line of text is the font size * 1.5. Plus, the property value can be specified with different type, referring to the [doc](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) for details.

It turned out to be like this, thank you very much for your answer, and express your gratitude again
