### ISSUE TITLE
[Component] [input-number] el-input-number的max和min国际化失败

### ISSUE THREAD

**Issue by RosyCloudsLee** [element-plus/element-plus#14384]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 117.0.5938.89 / Firefox linux 113`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCIgOm1pbj1cIjFcIiA6bWF4PVwiMTBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG51bSA9IHJlZigxKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbHVlOiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG59XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

在input中输入-1(min=1,max=10)，

### What is Expected?

因Element Plus 组件 默认 使用英语，故chrome和firefox都应该显示英文的提示

### What is actually happening?

chrome会提示“值必须大于或等于1”;
firefox会提示“Please select a value that is no less than 1”

### Additional comments

Element Plus 组件的label 和rule等其他的国际化都成功的

**Comment by yj-liuzepeng** [comment]
有提示吗？

**Comment by RosyCloudsLee** [comment]
有提示的，chrome会提示“值必须大于或等于1”

**Comment by bobohuochai** [comment]
给的链接点击进去没有提示，会自动变为最大值或最小值

**Comment by RosyCloudsLee** [comment]
input -1后，不要点enter，鼠标停留在方框内2s左右，会有提示的

**Comment by kaine0923** [comment]
这个应该是浏览器input设置max/min属性之后默认的提示，每个浏览器显示不一致

**Comment by RosyCloudsLee** [comment]
感觉也是浏览器的原因

**Comment by kooriookami** [comment]
是浏览器自带的提示
