### ISSUE TITLE
[select-v2] el-select-v2组件进行搜索时，输入法在中文状态时，输入字母b时（不按shift和回车键），选择搜出来的某一个选项，回显的不是我选中的选项。

### ISSUE THREAD

**Issue by zhangqin0817** [element-plus/element-plus#14410]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome / 117.0.5938.92`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select-v2.html#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E5%A4%9A%E9%80%89)

### Steps to reproduce

1：Select V2 虚拟列表选择器
2：可过滤的多选
3：切换中文输入法后，输入B2,（必须是中文输入法）
4，然后这个时候出来了:b21,b201,b211,b221, 
5,选择b211,回显出来的是c2

### What is Expected?

选择b211,我希望回显的是b211

### What is actually happening?

选择b211,回显出来的是c2

### Additional comments

输入法是中文时，输入一个字母，没有按回车或shift键，会出来搜的列表，但是点击时，回显的却是默认列表的选项，不是自己选中的。

**Comment by betavs** [comment]
![image](https://github.com/element-plus/element-plus/assets/34408516/6a031254-65fc-4264-a47c-1d9ed842b786)

**Comment by kooriookami** [comment]
问题不在组件上，你使用输入法的时候，输入框正在isComposing。当你点击组件，输入框认为你放弃输入，此时等同于你清空了输入框。

**Comment by picking-zichun** [comment]
我在搜狗输入法下会出现这个问题，电脑自带的输入法不会出现，请问这是什么原因？

![Image](https://github.com/user-attachments/assets/8c95c9c2-a11b-45b1-a6a9-e320b455962a)

![Image](https://github.com/user-attachments/assets/7b80a0a2-230f-4f60-a670-a97c49114730)

![Image](https://github.com/user-attachments/assets/fc5ac4c6-e9b1-4fda-afb8-0ffe96ea34a1)
