### ISSUE TITLE
[Component] [input-number] el-input-number组件显示值与实际值对不上

### ISSUE THREAD

**Issue by ouweicong** [element-plus/element-plus#14438]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0LW51bWJlclxuICAgIHYtbW9kZWw9XCJudW1cIlxuICAgIDptaW49XCIxXCJcbiAgICA6bWF4PVwiMTBcIlxuICAgIGNvbnRyb2xzLXBvc2l0aW9uPVwicmlnaHRcIlxuICAgIDpwcmVjaXNpb249XCIxXCJcbiAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJudW0gPSA2LjNcIj4xMjM8L2VsLWJ1dHRvbj5cbiAge3tudW19fVxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG51bSA9IHJlZig5LjIpXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

先把数字输入框给一个9.3的默认值，然后改成9.2，再改回9.3，这时候点击按钮修改绑定值，显示值与绑定值就对不上了

### What is Expected?

显示值与绑定值一致

### What is actually happening?

显示值与绑定值不一致

### Additional comments

_(empty)_

**Comment by btea** [comment]
Please provide detailed reproduction steps, thank you!

**Comment by ouweicong** [comment]
> 请提供详细的复制步骤，谢谢！

我给的例子，先改成9.3在改成9.2然后点击按钮就复现了

**Comment by ouweicong** [comment]
> Please provide detailed reproduction steps, thank you!

我给的例子，先改成9.3在改成9.2然后点击按钮就复现了
