### ISSUE TITLE
[All] Popover hydration failed with ElConfigProvider

### ISSUE THREAD

**Issue by qwent71** [element-plus/element-plus#14444]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-nuxt-starter)

### Steps to reproduce

i add data from guide https://element-plus.org/en-US/guide/namespace.html#set-scss-css-vars

### What is Expected?

normal work

### What is actually happening?

[Vue warn]: Hydration text content mismatch in <span>:
- Client: light
- Server: dark 
  at <ElSwitch modelValue=true onUpdate:modelValue=fn inline-prompt=""  ... > 
  at <Examples> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/', hash: '', query: {…}, name: 'index', path: '/', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <ElConfigProvider namespace="ep" > 
  at <App key=3 > 
  at <NuxtRoot>

chunk-FI4Y3IOY.js:1449 [Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <ElTooltipContent ref_key="contentRef" ref=Ref< undefined > aria-label=undefined  ... > 
  at <ElPopper ref_key="popperRef" ref=Ref< undefined > role="menu"  ... > 
  at <ElTooltip ref="popperRef" role="menu" effect="light"  ... > 
  at <ElDropdown class="m-4" type="primary" > 
  at <Examples> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/', hash: '', query: {…}, name: 'index', path: '/', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <ElConfigProvider namespace="ep" > 
  at <App key=3 > 
  at <NuxtRoot>

### Additional comments

I refresh the page and get a hydration error. elConfigProvider. I see the dropdown and calendar together if I click on either one. And in the nuxt configuration, the “namespace” attribute in the ElementPlus settings does not work.

**Comment by qwent71** [comment]
![image](https://github.com/element-plus/element-plus/assets/113848666/cbbed28a-d327-4fa7-8c70-c2107151d04f)

**Comment by tolking** [comment]
You need to set the [namespace](https://github.com/element-plus/element-plus-nuxt#namespace) for Element Plus Nuxt
