### ISSUE TITLE
[Style] [breadcrumb-item] Why the last breadcrumb item has different style?

### ISSUE THREAD

**Issue by Huelse** [element-plus/element-plus#14450]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome/117`
- Build Tool: `Vite`

### Related Component

- `el-breadcrumb-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJyZWFkY3J1bWIgc2VwYXJhdG9yPVwiL1wiPlxuICAgIDxlbC1icmVhZGNydW1iLWl0ZW0gOnRvPVwieyBwYXRoOiAnLycgfVwiPlRyYW5zZm9ybTwvZWwtYnJlYWRjcnVtYi1pdGVtPlxuICAgIDxlbC1icmVhZGNydW1iLWl0ZW0gOnRvPVwieyBwYXRoOiAnL3RvLXRzJyB9XCI+VG8gVFM8L2VsLWJyZWFkY3J1bWItaXRlbT5cbiAgICA8ZWwtYnJlYWRjcnVtYi1pdGVtIDp0bz1cInsgcGF0aDogJy90by1zcWwnIH1cIj5UbyBTUUw8L2VsLWJyZWFkY3J1bWItaXRlbT5cbiAgPC9lbC1icmVhZGNydW1iPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

use el-breadcrumb and el-breadcrumb-item

### What is Expected?

the last item should be same as before

### What is actually happening?

it has effected by the `.el-breadcrumb__item:last-child` css style

### Additional comments

Is that a feature? I didn't see any explains in the docs.

**Comment by btea** [comment]
Usually, the last breadcrumb represents the current, non-clickable jump, so the style is different from other jumpable links.

If this is not the style you expect, you can override it yourself through the style.
