### ISSUE TITLE
[feature request] can datepicker set the format of value format binding value?

### ISSUE THREAD

**Issue by ClyingDeng** [element-plus/element-plus#1445]
### Existing Component
Yes

### Component Name
1.0.2-beta.31

### Description
chrome

**Comment by zazzaz** [comment]
Any demo or detail, please?

**Comment by ClyingDeng** [comment]
像element2一样，使用value-format属性可以指定date的日期格式。
<el-date-picker
          v-model=“date"
          type="date"
          placeholder="选择日期"
          vaule-foramt="YYYY-MM-DD"
 > </el-date-picker>

**Comment by zazzaz** [comment]
you can join this issue #1068,

short answer: we have Day.js for you to deal with all the formatting issues.

**Comment by iamkun** [comment]
fixed in #2120
