### ISSUE TITLE
[Style] [icon, upload] 当el-icon组件在el-upload组件内部时，el-icon的color、font-size将受到css样式------> .el-upload--picture-card i  的干扰！！

### ISSUE THREAD

**Issue by baiseng** [element-plus/element-plus#14469]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `chrome 119.0.6045.9  / widows 11`
- Build Tool: `Vite`

### Related Component

- `el-icon`
- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMsVXBsb2FkIGFzIEVsSWNvblVwbG9hZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICDniYjmnKznjq/looPvvJpcbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxwPlxuICAgIOato+W4uOihqOeOsO+8mjxFbEJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPjxFbEljb24+PEVsSWNvblVwbG9hZC8+PC9FbEljb24+5LiK5LygPC9FbEJ1dHRvbj5cbiAgPC9wPlxuICA8cD5cbiAgICDlvILluLjooajnjrDvvJpcbiAgICA8RWxVcGxvYWQgbGlzdC10eXBlPVwicGljdHVyZS1jYXJkXCI+XG4gICAgICA8RWxCdXR0b24gdHlwZT1cInByaW1hcnlcIj48RWxJY29uPjxFbEljb25VcGxvYWQvPjwvRWxJY29uPuS4iuS8oDwvRWxCdXR0b24+XG4gICAgPC9FbFVwbG9hZD4gXG4gIDwvcD5cblxuICA8cD7mpoLopoHor7TmmI7vvJppY29u5Y+X5Yiw5LqGRWxVcGxvYWTnmoTlubLmibDvvIxpY29u55qEZm9udC1zaXpl5ZKMY29sb3LkuI3lnKjnu6fmib/oh6rniLbmoLflvI/vvIzogIzmmK/lj5fliLDkuobkuIvpnaLmoLflvI/nmoTlubLmibDvvIHvvIEgPC9wPlxuICA8cD5cbiAgICA8Y29kZT5cbiAgICAgIC5lbC11cGxvYWQtLXBpY3R1cmUtY2FyZCBpIHs8YnIvPlxuICAgICAgICAgIGZvbnQtc2l6ZTogMjhweDs8YnIvPlxuICAgICAgICAgIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7PGJyLz5cbiAgICAgIH1cbiAgICA8L2NvZGU+IFxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

见Playground 

### What is Expected?

修复为正常继承样式

### What is actually happening?

目前样式混乱

### Additional comments

_(empty)_

**Comment by btea** [comment]
@baiseng Hello, thank you for your feedback. However, I don’t think this is a bug. The relevant styles are configured for the default icons. If you add custom icons, you can override and configure the relevant styles according to your own needs.

**Comment by FrontEndDog** [comment]
> @baiseng Hello, thank you for your feedback. However, I don’t think this is a bug. The relevant styles are configured for the default icons. If you add custom icons, you can override and configure the relevant styles according to your own needs.

@btea  Hello  I think this is a bug ,`el-upload--picture-card i` affects the style of icons in buttons.
[example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMsIFVwbG9hZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICDlvILluLjooajnjrDvvJpcbiAgICA8RWxVcGxvYWQgbGlzdC10eXBlPVwicGljdHVyZS1jYXJkXCI+XG4gICAgICA8RWxCdXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIlVwbG9hZFwiPuS4iuS8oDwvRWxCdXR0b24+XG4gICAgPC9FbFVwbG9hZD5cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by baiseng** [comment]
样式选择器.el-upload--picture-card i 是否有点过于宽泛了？？
是否应该精确定位一点，避免影响其他组件原有逻辑？？

**Comment by baiseng** [comment]
> @baiseng Hello, thank you for your feedback. However, I don’t think this is a bug. The relevant styles are configured for the default icons. If you add custom icons, you can override and configure the relevant styles according to your own needs.

样式选择器.el-upload--picture-card i 是否有点过于宽泛了？？
是否应该精确定位一点，避免影响其他组件原有逻辑？？

**Comment by baiseng** [comment]
> @baiseng Hello, thank you for your feedback. However, I don’t think this is a bug. The relevant styles are configured for the default icons. If you add custom icons, you can override and configure the relevant styles according to your own needs.

这种宽泛选择器行为，就类似于以下行为：
<el-container>
     <el-main>
           <el-row>
                <el-col>
                    <el-col>
                        <el-tag>哈哈哈</el-tag>
                     </el-col>
                </el-col>
           </el-row>
     </el-main>
</el-container>

.el-container i{
   font-size:100px;
  color:red;
}


总结来说，宽泛选择器恶心的层级太深了，我里面的组件都需要去阻止最外层的宽泛行为。

**Comment by baiseng** [comment]
> @baiseng Hello, thank you for your feedback. However, I don’t think this is a bug. The relevant styles are configured for the default icons. If you add custom icons, you can override and configure the relevant styles according to your own needs.

这种宽泛选择器行为，就类似于以下行为：

el-container>el-main->el-row->el-col>el-space->el-tag

.el-container i{
font-size:100px;
color:red;
}

总结来说，宽泛选择器恶心的层级太深了，我里面的组件都需要去阻止最外层的宽泛行为。

**Comment by btea** [comment]
I know what you mean, but in my opinion, the original design intention of each component will only consider the current use of the component alone. In actual use, users may combine them in unexpected ways. Therefore, for these style issues in actual applications, I think it is better for users to add new styles to cover them.

Even if you adjust it according to the PR created by @FrontEndDog , if you use the icon directly, you will still be interfered with by the style. Therefore, you still have to define relevant classes yourself for style coverage.

**Comment by FrontEndDog** [comment]
@btea  but classes of `el-upload--picture-card i` just for the sake of use the icon directly, in addition，It does not affect any elements.

**Comment by kooriookami** [comment]
May be we can replace `.el-upload--picture-card i` with a specific name, like `.el-upload--picture-card .upload-icon`.
