### ISSUE TITLE
[Component] [collapse-item] Form配合Collapse折叠功能时，Collapse点击触发了submit

### ISSUE THREAD

**Issue by songshuzhong** [element-plus/element-plus#14462]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47`
- Build Tool: `Webpack`

### Related Component

- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm1cbiAgICByZWY9XCJmb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJudW1iZXJWYWxpZGF0ZUZvcm1cIlxuICAgIGxhYmVsLXdpZHRoPVwiMTAwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gID5cbiAgICAgIDxlbC1jb2xsYXBzZSB2LW1vZGVsPVwiYWN0aXZlTmFtZXNcIj5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiQ29uc2lzdGVuY3lcIiBuYW1lPVwiMVwiPlxuICAgICAgPC9lbC1jb2xsYXBzZS1pdGVtPlxuICAgIDwvZWwtY29sbGFwc2U+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJhZ2VcIlxuICAgICAgcHJvcD1cImFnZVwiXG4gICAgICA6cnVsZXM9XCJbXG4gICAgICAgIHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdhZ2UgaXMgcmVxdWlyZWQnIH0sXG4gICAgICAgIHsgdHlwZTogJ251bWJlcicsIG1lc3NhZ2U6ICdhZ2UgbXVzdCBiZSBhIG51bWJlcicgfSxcbiAgICAgIF1cIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsLm51bWJlcj1cIm51bWJlclZhbGlkYXRlRm9ybS5hZ2VcIlxuICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgIGF1dG9jb21wbGV0ZT1cIm9mZlwiXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiPlN1Ym1pdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuXG5jb25zdCBudW1iZXJWYWxpZGF0ZUZvcm0gPSByZWFjdGl2ZSh7XG4gIGFnZTogJycsXG59KVxuY29uc3QgYWN0aXZlTmFtZXMgPSByZWYoWycxJ10pXG5jb25zdCBzdWJtaXRGb3JtID0gKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XG4gIGlmICghZm9ybUVsKSByZXR1cm5cbiAgZm9ybUVsLnZhbGlkYXRlKCh2YWxpZCkgPT4ge1xuICAgIGlmICh2YWxpZCkge1xuICAgICAgY29uc29sZS5sb2coJ3N1Ym1pdCEnKVxuICAgIH0gZWxzZSB7XG4gICAgICBjb25zb2xlLmxvZygnZXJyb3Igc3VibWl0IScpXG4gICAgICByZXR1cm4gZmFsc2VcbiAgICB9XG4gIH0pXG59XG5cbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC5yZXNldEZpZWxkcygpXG59XG5jb25zb2xlLmxvZygxMjM0KTtcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Collapse放置在Form标签下即可复现。

### What is Expected?

点击CollapseItem折叠时，不触发外层Form的submit事件。

### What is actually happening?

点击CollapseItem折叠时，触发了外层Form的submit事件。

### Additional comments

CollapseItem的button上缺少type="button"属性

**Comment by betavs** [comment]
fixed #14308

**Comment by songshuzhong** [comment]
同样的问题在轮播图组件也有

**Comment by songshuzhong** [comment]
> fixed #14308

轮播图组件有相同的问题
