### ISSUE TITLE
[bug report] hopes that the pagination component can integrate current change and update:currentPage  Continue to trigger separately to facilitate secondary assembly

### ISSUE THREAD

**Issue by huijiewei** [element-plus/element-plus#1446]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
macOS / Chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/huijiewei/pen/ZEBWmBp?editors=1011

### Steps to reproduce
点击按钮设置页面为3的时候触发了2种事件

### What is Expected?
点击按钮设置页面为3的时候应该只触发 update:currentPage 即可，方便二次组装

### What is actually happening?
点击按钮设置页面为3的时候触发了2种事件

**Comment by Ryan2128** [comment]
`update:currentPage` only should be used for `v-model:current-page`, you should directly use `current-change` event.

**Comment by Ryan2128** [comment]
If there are other problem, please open this issue again.
