### ISSUE TITLE
[Bug Report] set locale failed in popconfirm

### ISSUE THREAD

**Issue by huxianc** [element-plus/element-plus#1447]
### Element Plus version
1.0.2-beta.31

### OS/Browsers version
Google Chrome 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://github.com/huxianc/element-plus-locale

### Steps to reproduce
[preview](https://huxianc.github.io/element-plus-locale/dist/index.html)

### What is Expected?
 click the `删除` button,expect the `confirmButtonText` and `cancelButtonText` in `popconfirm` to be the lang("zh-cn") I set.

### What is actually happening?
get default lang(es)

**Comment by JeremyWuuuuu** [comment]
Hey, we have made a breaking change to set the default language to be `en_US`, if you wish to use Chinese as translation texts, please refer to the documentation to set it properly: [国际化](https://element-plus.org/#/zh-CN/component/i18n)

**Comment by huxianc** [comment]
I've set the lang to Chinese,In my preview page,the `transfer` and `table` was normal,the `popconfirm` was still in `en_US`

**Comment by JeremyWuuuuu** [comment]
I see, I'll go find out why that won't work.

**Comment by JeremyWuuuuu** [comment]
I think I've found the root cause, I'll go fix it in the next release, I expect to roll out the next release before 2021.02.08 6pm GMT+8.

**Comment by huxianc** [comment]
Thanks!
