### ISSUE TITLE
[Docs] [select] select组件中文文档标题错误

### ISSUE THREAD

**Issue by baiwusanyu-c** [element-plus/element-plus#14474]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `-`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html#alert-api)

### Steps to reproduce

打开链接

### What is Expected?

显示为 Select Api 

### What is actually happening?

显示为 Alert Api

### Additional comments

_(empty)_

**Comment by btea** [comment]
多谢反馈，已更新！https://crowdin.com/translate/element-plus/833/en-zhcn?filter=basic&value=0
