### ISSUE TITLE
[Style] [col] 新版edge浏览器，栅格适配问题

### ISSUE THREAD

**Issue by achangchangchang** [element-plus/element-plus#14481]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43`
- Build Tool: `Vite`

### Related Component

- `el-col`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/layout.html#%E5%93%8D%E5%BA%94%E5%BC%8F%E5%B8%83%E5%B1%80)

### Steps to reproduce

在新版edge浏览器下,浏览器会默认开启全新外观(edge://settings/appearance),设置页面中可以看到这项设置
在启用全新外观的情况下栅格布局会失效,1920的屏幕会走lg的媒体查询尺寸
官方文档的col文档部分也存在这个问题

### What is Expected?

1920屏幕走xl的媒体查询尺寸

### What is actually happening?

1920屏幕走lg的媒体查询尺寸

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/33746006/dd77a0d3-2c88-4ff2-b4bb-7cfde2ff6193)
![image](https://github.com/element-plus/element-plus/assets/33746006/b03518b1-3ffb-46dc-a53d-7c6681fdeceb)
![image](https://github.com/element-plus/element-plus/assets/33746006/3d53c67a-784b-4d67-b3d2-7b413a3c5be7)

**Comment by kooriookami** [comment]
这个是正常的，开启Edge特性，浏览器可视区域宽度就不是1920px了
