### ISSUE TITLE
[Docs] [select] 错误的中文文档子标题

### ISSUE THREAD

**Issue by skyclouds2001** [element-plus/element-plus#14491]
Bug Type: **`Docs`**

## Environment

- Vue Version: `-`
- Element Plus Version: `-`
- Browser / OS: `-`
- Build Tool: `-`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html#alert-api)

### Steps to reproduce

文档该区域的子标题为“Alert API”
从URL https://element-plus.org/zh-CN/component/select.html#alert-api 也可以发现

### What is Expected?

应当修改为“Select API”或“API”

### What is actually happening?

实际为“Alert API”

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/95597335/a2cd79ad-7507-4bda-8972-fca7db1e85ac)

**Comment by skyclouds2001** [comment]
Also https://element-plus.org/zh-CN/component/dialog.html#attributes

![image](https://github.com/element-plus/element-plus/assets/95597335/0d9af44b-8af1-47dd-bffc-a8f264c808d1)

**Comment by btea** [comment]
感谢反馈，select 同 #14474 重复，已经修复了；dialog 这个确实有问题。
