### ISSUE TITLE
[Component] [drawer] Drawer的遮罩自定义类无效。在使用Drawer的时候，定义modal-class = "modal9" ,然后再style标签中.modal9{backgroundColor = ...}——无效。

### ISSUE THREAD

**Issue by LiaoZhiXion** [element-plus/element-plus#14502]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 已是最新版本 版本 117.0.5938.150`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJkaXJlY3Rpb25cIj5cbiAgICA8ZWwtcmFkaW8gbGFiZWw9XCJsdHJcIj5sZWZ0IHRvIHJpZ2h0PC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gbGFiZWw9XCJydGxcIj5yaWdodCB0byBsZWZ0PC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gbGFiZWw9XCJ0dGJcIj50b3AgdG8gYm90dG9tPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gbGFiZWw9XCJidHRcIj5ib3R0b20gdG8gdG9wPC9lbC1yYWRpbz5cbiAgPC9lbC1yYWRpby1ncm91cD5cblxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc3R5bGU9XCJtYXJnaW4tbGVmdDogMTZweFwiIEBjbGljaz1cImRyYXdlciA9IHRydWVcIj5cbiAgICBvcGVuXG4gIDwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc3R5bGU9XCJtYXJnaW4tbGVmdDogMTZweFwiIEBjbGljaz1cImRyYXdlcjIgPSB0cnVlXCI+XG4gICAgd2l0aCBmb290ZXJcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLWRyYXdlclxuICAgIHYtbW9kZWw9XCJkcmF3ZXJcIlxuICAgIHRpdGxlPVwiSSBhbSB0aGUgdGl0bGVcIlxuICAgIDpkaXJlY3Rpb249XCJkaXJlY3Rpb25cIlxuICAgIG1vZGFsLWNsYXNzID0gXCJtb2RhbDlcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8c3Bhbj5IaSwgdGhlcmUhPC9zcGFuPlxuICA8L2VsLWRyYXdlcj5cbiAgPGVsLWRyYXdlciB2LW1vZGVsPVwiZHJhd2VyMlwiIDpkaXJlY3Rpb249XCJkaXJlY3Rpb25cIj5cbiAgICA8dGVtcGxhdGUgI2hlYWRlcj5cbiAgICAgIDxoND5zZXQgdGl0bGUgYnkgc2xvdDwvaDQ+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICA8ZGl2PlxuICAgICAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMVwiIGxhYmVsPVwiT3B0aW9uIDFcIiBzaXplPVwibGFyZ2VcIlxuICAgICAgICAgID5PcHRpb24gMTwvZWwtcmFkaW9cbiAgICAgICAgPlxuICAgICAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMVwiIGxhYmVsPVwiT3B0aW9uIDJcIiBzaXplPVwibGFyZ2VcIlxuICAgICAgICAgID5PcHRpb24gMjwvZWwtcmFkaW9cbiAgICAgICAgPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxkaXYgc3R5bGU9XCJmbGV4OiBhdXRvXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2FuY2VsQ2xpY2tcIj5jYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImNvbmZpcm1DbGlja1wiPmNvbmZpcm08L2VsLWJ1dHRvbj5cbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJhd2VyPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLm1vZGFsOXtcbmJhY2tncm91bmQtY29sb3I6IGFxdWE7XG59XG48L3N0eWxlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkcmF3ZXIgPSByZWYoZmFsc2UpXG5jb25zdCBkcmF3ZXIyID0gcmVmKGZhbHNlKVxuY29uc3QgZGlyZWN0aW9uID0gcmVmKCdydGwnKVxuY29uc3QgcmFkaW8xID0gcmVmKCdPcHRpb24gMScpXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lOiAoKSA9PiB2b2lkKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmUgeW91IHdhbnQgdG8gY2xvc2UgdGhpcz8nKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIGRvbmUoKVxuICAgIH0pXG4gICAgLmNhdGNoKCgpID0+IHtcbiAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgfSlcbn1cbmZ1bmN0aW9uIGNhbmNlbENsaWNrKCkge1xuICBkcmF3ZXIyLnZhbHVlID0gZmFsc2Vcbn1cbmZ1bmN0aW9uIGNvbmZpcm1DbGljaygpIHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oYEFyZSB5b3UgY29uZmlybSB0byBjaG9zZSAke3JhZGlvMS52YWx1ZX0gP2ApXG4gICAgLnRoZW4oKCkgPT4ge1xuICAgICAgZHJhd2VyMi52YWx1ZSA9IGZhbHNlXG4gICAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgICAgLy8gY2F0Y2ggZXJyb3JcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

运行代码查看是否显示遮罩背景颜色

### What is Expected?

显示

### What is actually happening?

不显示

### Additional comments

希望得到帮助

**Comment by btea** [comment]
As @yj-liuzepeng  said, just increase the style priority. 
However, in my opinion, it is generally not recommended to use `important` lightly. You can overlay classes, such as:
```css
.el-overlay.modal9 {
  background-color: aqua;
}
```
