### ISSUE TITLE
[Component] [collapse, collapse-item] [Component] [collapse-item] Form配合Collapse折叠功能时，Collapse点击无效，只刷新了页面

### ISSUE THREAD

**Issue by LullabyLY** [element-plus/element-plus#14512]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-collapse`
- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybVwiIGxhYmVsLXdpZHRoPVwiMTIwcHhcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgbmFtZVwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm5hbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCI+XG4gICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwicGxlYXNlIHNlbGVjdCB5b3VyIHpvbmVcIj5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgb25lXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgdGltZVwiPlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjExXCI+XG4gICAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICAgIHYtbW9kZWw9XCJmb3JtLmRhdGUxXCJcbiAgICAgICAgICB0eXBlPVwiZGF0ZVwiXG4gICAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF0ZVwiXG4gICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgICAgIC8+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCIyXCIgY2xhc3M9XCJ0ZXh0LWNlbnRlclwiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cInRleHQtZ3JheS01MDBcIj4tPC9zcGFuPlxuICAgICAgPC9lbC1jb2w+XG4gICAgICA8ZWwtY29sIDpzcGFuPVwiMTFcIj5cbiAgICAgICAgPGVsLXRpbWUtcGlja2VyXG4gICAgICAgICAgdi1tb2RlbD1cImZvcm0uZGF0ZTJcIlxuICAgICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIHRpbWVcIlxuICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1jb2w+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkluc3RhbnQgZGVsaXZlcnlcIj5cbiAgICAgIDxlbC1zd2l0Y2ggdi1tb2RlbD1cImZvcm0uZGVsaXZlcnlcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB0eXBlXCI+XG4gICAgICA8ZWwtY2hlY2tib3gtZ3JvdXAgdi1tb2RlbD1cImZvcm0udHlwZVwiPlxuICAgICAgICA8ZWwtY2hlY2tib3ggbGFiZWw9XCJPbmxpbmUgYWN0aXZpdGllc1wiIG5hbWU9XCJ0eXBlXCIgLz5cbiAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiUHJvbW90aW9uIGFjdGl2aXRpZXNcIiBuYW1lPVwidHlwZVwiIC8+XG4gICAgICAgIDxlbC1jaGVja2JveCBsYWJlbD1cIk9mZmxpbmUgYWN0aXZpdGllc1wiIG5hbWU9XCJ0eXBlXCIgLz5cbiAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiU2ltcGxlIGJyYW5kIGV4cG9zdXJlXCIgbmFtZT1cInR5cGVcIiAvPlxuICAgICAgPC9lbC1jaGVja2JveC1ncm91cD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUmVzb3VyY2VzXCI+XG4gICAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImZvcm0ucmVzb3VyY2VcIj5cbiAgICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiU3BvbnNvclwiIC8+XG4gICAgICAgIDxlbC1yYWRpbyBsYWJlbD1cIlZlbnVlXCIgLz5cbiAgICAgIDwvZWwtcmFkaW8tZ3JvdXA+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IGZvcm1cIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZm9ybS5kZXNjXCIgdHlwZT1cInRleHRhcmVhXCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgPGVsLWNvbGxhcHNlPlxuXG4gICAgICA8ZWwtY29sbGFwc2UtaXRlbSB0aXRsZT1cIkNvbnNpc3RlbmN5XCIgbmFtZT1cIjFcIj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBDb25zaXN0ZW50IHdpdGggcmVhbCBsaWZlOiBpbiBsaW5lIHdpdGggdGhlIHByb2Nlc3MgYW5kIGxvZ2ljIG9mIHJlYWxcbiAgICAgICAgICBsaWZlLCBhbmQgY29tcGx5IHdpdGggbGFuZ3VhZ2VzIGFuZCBoYWJpdHMgdGhhdCB0aGUgdXNlcnMgYXJlIHVzZWQgdG87XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIENvbnNpc3RlbnQgd2l0aGluIGludGVyZmFjZTogYWxsIGVsZW1lbnRzIHNob3VsZCBiZSBjb25zaXN0ZW50LCBzdWNoXG4gICAgICAgICAgYXM6IGRlc2lnbiBzdHlsZSwgaWNvbnMgYW5kIHRleHRzLCBwb3NpdGlvbiBvZiBlbGVtZW50cywgZXRjLlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZWwtY29sbGFwc2UtaXRlbT5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiRmVlZGJhY2tcIiBuYW1lPVwiMlwiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIE9wZXJhdGlvbiBmZWVkYmFjazogZW5hYmxlIHRoZSB1c2VycyB0byBjbGVhcmx5IHBlcmNlaXZlIHRoZWlyXG4gICAgICAgICAgb3BlcmF0aW9ucyBieSBzdHlsZSB1cGRhdGVzIGFuZCBpbnRlcmFjdGl2ZSBlZmZlY3RzO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBWaXN1YWwgZmVlZGJhY2s6IHJlZmxlY3QgY3VycmVudCBzdGF0ZSBieSB1cGRhdGluZyBvciByZWFycmFuZ2luZ1xuICAgICAgICAgIGVsZW1lbnRzIG9mIHRoZSBwYWdlLlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZWwtY29sbGFwc2UtaXRlbT5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiRWZmaWNpZW5jeVwiIG5hbWU9XCIzXCI+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgU2ltcGxpZnkgdGhlIHByb2Nlc3M6IGtlZXAgb3BlcmF0aW5nIHByb2Nlc3Mgc2ltcGxlIGFuZCBpbnR1aXRpdmU7XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIERlZmluaXRlIGFuZCBjbGVhcjogZW51bmNpYXRlIHlvdXIgaW50ZW50aW9ucyBjbGVhcmx5IHNvIHRoYXQgdGhlXG4gICAgICAgICAgdXNlcnMgY2FuIHF1aWNrbHkgdW5kZXJzdGFuZCBhbmQgbWFrZSBkZWNpc2lvbnM7XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIEVhc3kgdG8gaWRlbnRpZnk6IHRoZSBpbnRlcmZhY2Ugc2hvdWxkIGJlIHN0cmFpZ2h0Zm9yd2FyZCwgd2hpY2ggaGVscHNcbiAgICAgICAgICB0aGUgdXNlcnMgdG8gaWRlbnRpZnkgYW5kIGZyZWVzIHRoZW0gZnJvbSBtZW1vcml6aW5nIGFuZCByZWNhbGxpbmcuXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC1jb2xsYXBzZS1pdGVtPlxuICAgICAgPGVsLWNvbGxhcHNlLWl0ZW0gdGl0bGU9XCJDb250cm9sbGFiaWxpdHlcIiBuYW1lPVwiNFwiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIERlY2lzaW9uIG1ha2luZzogZ2l2aW5nIGFkdmljZXMgYWJvdXQgb3BlcmF0aW9ucyBpcyBhY2NlcHRhYmxlLCBidXQgZG9cbiAgICAgICAgICBub3QgbWFrZSBkZWNpc2lvbnMgZm9yIHRoZSB1c2VycztcbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgQ29udHJvbGxlZCBjb25zZXF1ZW5jZXM6IHVzZXJzIHNob3VsZCBiZSBncmFudGVkIHRoZSBmcmVlZG9tIHRvXG4gICAgICAgICAgb3BlcmF0ZSwgaW5jbHVkaW5nIGNhbmNlbGluZywgYWJvcnRpbmcgb3IgdGVybWluYXRpbmcgY3VycmVudFxuICAgICAgICAgIG9wZXJhdGlvbi5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+ICAgICA8L2VsLWNvbGxhcHNlPlxuXG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJvblN1Ym1pdFwiPkNyZWF0ZTwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPiBcblxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG4vLyBkbyBub3QgdXNlIHNhbWUgbmFtZSB3aXRoIHJlZlxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJycsXG4gIHJlZ2lvbjogJycsXG4gIGRhdGUxOiAnJyxcbiAgZGF0ZTI6ICcnLFxuICBkZWxpdmVyeTogZmFsc2UsXG4gIHR5cGU6IFtdLFxuICByZXNvdXJjZTogJycsXG4gIGRlc2M6ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Collapse放置在Form标签下即可复现。

### What is Expected?

可以正常展开

### What is actually happening?

没有展开，页面刷新

### Additional comments

_(empty)_

**Comment by betavs** [comment]
duplicated with #14462

fixed with #14308
