### ISSUE TITLE
[Component] [collapse-item] el-collapse-item作为el-form组件时 点击折叠会刷新页面

### ISSUE THREAD

**Issue by daLeiStrive** [element-plus/element-plus#14519]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60`
- Build Tool: `Vite`

### Related Component

- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiBcbiBjb25zdCBhY3RpdmVOYW1lcyA9ICByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cblxuICBcbiAgPGVsLWZvcm0gID5cbiAgICAgPGVsLWNvbGxhcHNlIHYtbW9kZWw9XCJhY3RpdmVOYW1lc1wiID5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwi54K55Ye75oiR6aG16Z2i5Lya5Yi35pawMVwiIG5hbWU9XCIxXCI+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgQ29uc2lzdGVudCB3aXRoIHJlYWwgbGlmZTogaW4gbGluZSB3aXRoIHRoZSBwcm9jZXNzIGFuZCBsb2dpYyBvZiByZWFsXG4gICAgICAgICAgbGlmZSwgYW5kIGNvbXBseSB3aXRoIGxhbmd1YWdlcyBhbmQgaGFiaXRzIHRoYXQgdGhlIHVzZXJzIGFyZSB1c2VkIHRvO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBDb25zaXN0ZW50IHdpdGhpbiBpbnRlcmZhY2U6IGFsbCBlbGVtZW50cyBzaG91bGQgYmUgY29uc2lzdGVudCwgc3VjaFxuICAgICAgICAgIGFzOiBkZXNpZ24gc3R5bGUsIGljb25zIGFuZCB0ZXh0cywgcG9zaXRpb24gb2YgZWxlbWVudHMsIGV0Yy5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgICA8ZWwtY29sbGFwc2UtaXRlbSB0aXRsZT1cIueCueWHu+aIkemhtemdouS8muWIt+aWsDJcIiBuYW1lPVwiMlwiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIE9wZXJhdGlvbiBmZWVkYmFjazogZW5hYmxlIHRoZSB1c2VycyB0byBjbGVhcmx5IHBlcmNlaXZlIHRoZWlyXG4gICAgICAgICAgb3BlcmF0aW9ucyBieSBzdHlsZSB1cGRhdGVzIGFuZCBpbnRlcmFjdGl2ZSBlZmZlY3RzO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBWaXN1YWwgZmVlZGJhY2s6IHJlZmxlY3QgY3VycmVudCBzdGF0ZSBieSB1cGRhdGluZyBvciByZWFycmFuZ2luZ1xuICAgICAgICAgIGVsZW1lbnRzIG9mIHRoZSBwYWdlLlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZWwtY29sbGFwc2UtaXRlbT5cbiAgICAgXG4gICAgPC9lbC1jb2xsYXBzZT5cbiAgICAgXG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

在form表单中使用el-collapse

### What is Expected?

点击el-collapse-item时实现展开收起效果

### What is actually happening?

点击el-collapse-item时页面刷新

### Additional comments

_(empty)_

**Comment by tolking** [comment]
repeat with #14512

fixed by #14308
