### ISSUE TITLE
[Component] [tree] props配置项是否能配置value属性

### ISSUE THREAD

**Issue by yj-liuzepeng** [element-plus/element-plus#14522]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`
- `el-tree-select`
- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIDpkYXRhPVwiZGF0YVwiICA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIiA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKClcbmNvbnN0IGRlZmF1bHRQcm9wcyA9IHtcbiAgY2hpbGRyZW46IFwiY2hpbGRyZW5cIixcbiAgbGFiZWw6IFwiY2NOYW1lXCIsXG4gIC8vIHZhbHVlOiBcImNjSWRcIlxufTtcblxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIGNjSWQ6ICcxJyxcbiAgICBjY05hbWU6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgY2NJZDogJzEtMScsXG4gICAgICAgIGNjTmFtZTogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGNjSWQ6ICcxLTEtMScsXG4gICAgICAgICAgICBjY05hbWU6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGNjSWQ6ICcyJyxcbiAgICBjY05hbWU6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgY2NJZDogJzItMScsXG4gICAgICAgIGNjTmFtZTogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGNjSWQ6ICcyLTEtMScsXG4gICAgICAgICAgICBjY05hbWU6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGNjSWQ6ICcyLTInLFxuICAgICAgICBjY05hbWU6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjY0lkOiAnMi0yLTEnLFxuICAgICAgICAgICAgY2NOYW1lOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBjY0lkOiAnMycsXG4gICAgY2NOYW1lOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGNjSWQ6ICczLTEnLFxuICAgICAgICBjY05hbWU6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjY0lkOiAnMy0xLTEnLFxuICAgICAgICAgICAgY2NOYW1lOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBjY0lkOiAnMy0yJyxcbiAgICAgICAgY2NOYW1lOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgY2NJZDogJzMtMi0xJyxcbiAgICAgICAgICAgIGNjTmFtZTogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

打开上面👆地址，配置上 props的value，组件正常
注释掉defaultProps中的value，组件出现问题

### What is Expected?

组件正常使用

但是文档中props中并没有value项的配置 https://element-plus.gitee.io/en-US/component/tree.html#props

**Comment by kooriookami** [comment]
你是不是在找 `node-key`

**Comment by yj-liuzepeng** [comment]
> 你是不是在找 `node-key`

@kooriookami  应该是我的项目ep版本太低了 2.1.11，即使加上 node-key也是有问题，切换到最新版本，问题没有了，应该是修复了这个问题，谢谢大佬！
<img width="1106" alt="image" src="https://github.com/element-plus/element-plus/assets/75007029/25e8160f-278e-47a0-a48c-6a85a217cf28">
