### ISSUE TITLE
[Feature Request] Would you like to remove the popover elements from the DOM if they are not visible?

### ISSUE THREAD

**Issue by PotapOblomov103** [element-plus/element-plus#1453]
### Existing Component
Yes

### Component Name
Select, Tooltip, Popover, Dropdown

### Description
For example, a page has 100 elements using a poper, and 100 elements are inserted into the DOM. Wanted: elements to be inserted into the DOM only if the element using poper is active (hover, clicked, etc.), as v-if does, not v-show

**Comment by zhenzhenChange** [comment]
agree with +1

I also think it would be better to use `v-if`

**Comment by AubSs** [comment]
agree with +1

**Comment by AndrewSparrowww** [comment]
That make sense!

**Comment by AndrewSparrowww** [comment]
We even can see that performance of the page containing 100+ tooltips is much worse in comparison to ElementUI

**Comment by AubSs** [comment]
up

**Comment by msidolphin** [comment]
This feature has been implemented in https://github.com/element-plus/element-plus/pull/5035

**Comment by jasondeng** [comment]
it looks like this is still happening even on the latest version (1.3.0.-beta 5)?

**Comment by OKAAMI** [comment]
Still seeing lots of popper elements rendered without any popper interaction. This is causing performance issues.

**Comment by JonasPardon** [comment]
Still an issue on the latest version of Element Plus. 

Since our migration from Element UI to Element Plus we've seen a very big performance hit because of this.

**Comment by goldenfireking** [comment]
I also encountered this problem, and it still has not been solved, which greatly affects performance
