### ISSUE TITLE
[Component] [collapse, collapse-item] click on title of el-collapse-item placed in form reload page

### ISSUE THREAD

**Issue by eLeszek** [element-plus/element-plus#14537]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome 105.0.5195.52 (Monetary) (arm64)`
- Build Tool: `Vite`

### Related Component

- `el-collapse`
- `el-collapse-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tY29sbGFwc2VcIj5cbiAgICA8ZWwtZm9ybT5cbiAgICA8ZWwtY29sbGFwc2Ugdi1tb2RlbD1cImFjdGl2ZU5hbWVzXCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiPlxuICAgICAgPGVsLWNvbGxhcHNlLWl0ZW0gdGl0bGU9XCJDb25zaXN0ZW5jeVwiIG5hbWU9XCIxXCI+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgQ29uc2lzdGVudCB3aXRoIHJlYWwgbGlmZTogaW4gbGluZSB3aXRoIHRoZSBwcm9jZXNzIGFuZCBsb2dpYyBvZiByZWFsXG4gICAgICAgICAgbGlmZSwgYW5kIGNvbXBseSB3aXRoIGxhbmd1YWdlcyBhbmQgaGFiaXRzIHRoYXQgdGhlIHVzZXJzIGFyZSB1c2VkIHRvO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBDb25zaXN0ZW50IHdpdGhpbiBpbnRlcmZhY2U6IGFsbCBlbGVtZW50cyBzaG91bGQgYmUgY29uc2lzdGVudCwgc3VjaFxuICAgICAgICAgIGFzOiBkZXNpZ24gc3R5bGUsIGljb25zIGFuZCB0ZXh0cywgcG9zaXRpb24gb2YgZWxlbWVudHMsIGV0Yy5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgICA8ZWwtY29sbGFwc2UtaXRlbSB0aXRsZT1cIkZlZWRiYWNrXCIgbmFtZT1cIjJcIj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBPcGVyYXRpb24gZmVlZGJhY2s6IGVuYWJsZSB0aGUgdXNlcnMgdG8gY2xlYXJseSBwZXJjZWl2ZSB0aGVpclxuICAgICAgICAgIG9wZXJhdGlvbnMgYnkgc3R5bGUgdXBkYXRlcyBhbmQgaW50ZXJhY3RpdmUgZWZmZWN0cztcbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgVmlzdWFsIGZlZWRiYWNrOiByZWZsZWN0IGN1cnJlbnQgc3RhdGUgYnkgdXBkYXRpbmcgb3IgcmVhcnJhbmdpbmdcbiAgICAgICAgICBlbGVtZW50cyBvZiB0aGUgcGFnZS5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgICA8ZWwtY29sbGFwc2UtaXRlbSB0aXRsZT1cIkVmZmljaWVuY3lcIiBuYW1lPVwiM1wiPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIFNpbXBsaWZ5IHRoZSBwcm9jZXNzOiBrZWVwIG9wZXJhdGluZyBwcm9jZXNzIHNpbXBsZSBhbmQgaW50dWl0aXZlO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBEZWZpbml0ZSBhbmQgY2xlYXI6IGVudW5jaWF0ZSB5b3VyIGludGVudGlvbnMgY2xlYXJseSBzbyB0aGF0IHRoZVxuICAgICAgICAgIHVzZXJzIGNhbiBxdWlja2x5IHVuZGVyc3RhbmQgYW5kIG1ha2UgZGVjaXNpb25zO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBFYXN5IHRvIGlkZW50aWZ5OiB0aGUgaW50ZXJmYWNlIHNob3VsZCBiZSBzdHJhaWdodGZvcndhcmQsIHdoaWNoIGhlbHBzXG4gICAgICAgICAgdGhlIHVzZXJzIHRvIGlkZW50aWZ5IGFuZCBmcmVlcyB0aGVtIGZyb20gbWVtb3JpemluZyBhbmQgcmVjYWxsaW5nLlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZWwtY29sbGFwc2UtaXRlbT5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiQ29udHJvbGxhYmlsaXR5XCIgbmFtZT1cIjRcIj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBEZWNpc2lvbiBtYWtpbmc6IGdpdmluZyBhZHZpY2VzIGFib3V0IG9wZXJhdGlvbnMgaXMgYWNjZXB0YWJsZSwgYnV0IGRvXG4gICAgICAgICAgbm90IG1ha2UgZGVjaXNpb25zIGZvciB0aGUgdXNlcnM7XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIENvbnRyb2xsZWQgY29uc2VxdWVuY2VzOiB1c2VycyBzaG91bGQgYmUgZ3JhbnRlZCB0aGUgZnJlZWRvbSB0b1xuICAgICAgICAgIG9wZXJhdGUsIGluY2x1ZGluZyBjYW5jZWxpbmcsIGFib3J0aW5nIG9yIHRlcm1pbmF0aW5nIGN1cnJlbnRcbiAgICAgICAgICBvcGVyYXRpb24uXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC1jb2xsYXBzZS1pdGVtPlxuICAgIDwvZWwtY29sbGFwc2U+XG4gICAgPC9lbC1mb3JtPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGFjdGl2ZU5hbWVzID0gcmVmKFsnMSddKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2codmFsKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Open link and click on title of el-collapse-item

### What is Expected?

toggle el-collapse-item

### What is actually happening?

reload page; el-collapse-item is not expanded;

### Additional comments

when is added event @click.prevent to el-collapse it works;

**Comment by usmanasghar** [comment]
Thanks for opening this issue. I am also facing this recently when I deploy my app on production yesterday. It was working fine on my local maching.

**Comment by btea** [comment]
Has been fixed by #14308.

**Comment by eLeszek** [comment]
ok, I see version 2.4.0 now (I haven't seen it before); looks like it works
