### ISSUE TITLE
[bug report] loading component. In the development environment, the command usage posture is abnormal

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1454]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Microsoft Edge 版本 88.0.705.56 (官方内部版本) (64 位)

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/n4az9x2s/2/

### Steps to reproduce

1. 这个 https://jsfiddle.net/n4az9x2s/2/ 网址代码运行结果正常

2.问题出现在开发环境(我本地fork了一份element-plus)

3.在fork的项目element-plus/website/play/index.vue写上 https://jsfiddle.net/n4az9x2s/2/ 这个网址的demo代码

4.运行 npm run website-dev:play

5.就会发现改变loading的值，无任何效果

### What is Expected?
1.希望为true的时候出现loading ui，为false的时候 ui消失

### What is actually happening?
1.实际上没有任何反应，也没有执行element-plus/packages/loading/src/directive.ts中的钩子函数(一开始我以为是element的bug，后来确信是Vue的bug，但是我作为使用者，确实是使用了v-loading的造成的，所以就提了这个bug)

2.下面我说下这个bug造成的原因(希望能看下，或许我说的不对)

**a.造成bug的根本原因，我觉得是模板编译或者vue-loader出了问题, 相同的模板只是使用了不同方式(ref,reactive)创建的响应式数据，最后模板编译的结果却不同。**

  b.withDirectives(vNode, [ [dir, value, argument, modifiers] ])函数接受2个参数,这里我们关心下第二个参数数组里面的成员，成员数组的第一个dir值我觉得必须为一个对象(虽然可以是函数，但是内部实现中，还是会转成对象){ beforeMount,  mounted, beforeUpdate, updated, beforeUnmount, unmounted },值为钩子函数。对于我提的这个bug的代码，模板解析完，dir的值却是一个boolean值(内部没有特殊处理)，所以当调用钩子时，   解析不到对应的钩子，所以就没执行element-plus/packages/loading/src/directive.ts中的钩子函数。

c.看下模板编译的结果
  使用 Vue.compile 编译后的render函数,这是正常的，所以生产环境没毛病。_directive_loading拿到了element-plus/packages/loading/src/directive.ts中的钩子函数
```dart
function render(_ctx, _cache) {

    with(_ctx) {
        const {
            toDisplayString: _toDisplayString,
            resolveDirective: _resolveDirective,
            createVNode: _createVNode,
            withDirectives: _withDirectives,
            openBlock: _openBlock,
            createBlock: _createBlock
        } = _Vue

        const _directive_loading = _resolveDirective("loading")

        return (_openBlock(), _createBlock("div", _hoisted_1, [
            _withDirectives(_createVNode("div", {
                class: "element-plus-loading__box1"
            }, " 注意看我: " + _toDisplayString(loading), 513 /* TEXT, NEED_PATCH */ ), [
                [_directive_loading, loading]
            ])
        ]))
    }

}
```
使用ref 创建响应式数据时, 模板编译有问题, withDirectives(vNode, [[dir, value, argument, modifiers]])方法,dir是个对象，里面是不同的钩子，下面编译后的代码dir却是boolean值， $setup["loading"]这句话应该是问题所在，应该是element-plus/packages/loading/src/directive.ts中的钩子函数，现在却是布尔值。
```dart
function render(_ctx, _cache, $props, $setup, $data, $options) {

    return Object(vue__WEBPACK_IMPORTED_MODULE_0__["openBlock"])(), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createBlock"])("div", _hoisted_1, [Object(vue__WEBPACK_IMPORTED_MODULE_0__["withDirectives"])(Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])("div", {
            class: "element-plus-loading__box1"
        }, " 注意看我: " + Object(vue__WEBPACK_IMPORTED_MODULE_0__["toDisplayString"])($setup.loading), 513
        /* TEXT, NEED_PATCH */
    ), [
        [$setup["loading"], $setup.loading]
    ])]);

}
```
使用reactive 创建的响应式数据, 和预期一样， 这个和Vue.compile 编译后的差不多，所以正常
```dart
function render(_ctx, _cache, $props, $setup, $data, $options) {

    var _directive_loading = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveDirective"])("loading");

    return Object(vue__WEBPACK_IMPORTED_MODULE_0__["openBlock"])(), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createBlock"])("div", _hoisted_1, [Object(vue__WEBPACK_IMPORTED_MODULE_0__["withDirectives"])(Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])("div", {
            class: "element-plus-loading__box1"
        }, " 注意看我: " + Object(vue__WEBPACK_IMPORTED_MODULE_0__["toDisplayString"])(_ctx.loading), 513
        /* TEXT, NEED_PATCH */
    ), [
        [_directive_loading, _ctx.loading]
    ])]);

}
```
3.希望我的解释是对的，感谢阅读

**Comment by SorrowX** [comment]
1.关于在生成环境下，这个demo能跑起来，但也有另一个bug

2.就是当v-loading="loading" loading值变成false时，消失的过渡动画没有了？？？

3.这应该不算是bug,而是我个人的使用姿势有问题，但是我觉得可以在官方文档可以说明下。

4.消失的过渡动画没有的原因是模板中绑定指令的dom元素的孩子是文本节点，当loading值变成false时，触发render effect更新,执行新老vNode patch时，当patch的vNode的孩子是文本节点时，会执行hostSetElementText(el, n2.children);这样会把elLoadingComponent组件创建好的el元素也替换了，所以动画没了。这个锅我觉得vue和element都不能背，我觉得官网可以提醒下：当使用指令loading时，绑定指令的dom元素的孩子最好不要直接是文本节点，可以使用dom标签包裹一下就能解决这个问题。

5.学习vue3的使用姿势，除了vue-next的单侧，element-puls的源码学习也是很棒的，感谢element团队

**Comment by SorrowX** [comment]
el.instance = Loading({

    text: vm && vm[textExr] || textExr, // vm?.textExr || textExr
    spinner: vm && vm[spinnerExr] || spinnerExr, // vm?.spinnerExr || spinnerExr
    background: vm && vm[backgroundExr] || backgroundExr,  // vm?.backgroundExr || backgroundExr
    customClass: vm && vm[customClassExr] || customClassExr, // vm?.customClassExr || customClassExr
    fullscreen: !!binding.modifiers.fullscreen,
    target: !!binding.modifiers.fullscreen ? null : el,
    body: !!binding.modifiers.body,
    visible: true,
    lock: !!binding.modifiers.lock,

  })

vm && vm[textExr] || textExr 不改成 vm?.textExr || textExr ？？？
我看有的组件好像使用 ?. 语法 @Ryan2128

**Comment by zhenzhenChange** [comment]
我也遇到同样的问题，不过我没有详细去测试，就算不用 ref，直接给一个 true 都不会启动 loading

---

vue composition fn：
```ts
const data = ref([])
const loading = ref(false)

const requestState = async () => {
    // 开启 loading
    loading.value = true

    try {
      // 这里进行 http 请求，然后将请求结果赋值给 table data prop
      data.value = "http result"
    } catch (error) {
      console.log(error)
    } finally {
      // 最终关闭 loading
      loading.value = false
    }
}
```

vue sfc:

```html
<script setup lang="ts">
import { onMounted } from "vue"

import { data, loading, requestState } from "./xxxxFn"

onMounted(async () => await requestState())
</script>

<template>
    <!-- 这里的 loading 不生效 -->
    <el-table border stripe :data="data" v-loading="loading"></el-table>
</template>
```

即使是这样都不会开启 loading

```html
<el-table v-loading="true"></el-table>
```

官网的例子可以，唯一的区别就是，我这里是使用 setup 选项，并且使用 ref 值，而官网的不是，所以我猜测可能也是 setup 或者 ref 相关的问题

**Comment by SorrowX** [comment]
你的可能是el-table的bug，明天如果我的心还没飞往老家，我去公司帮你找下导致这个bug的原因。
我提的这个bug，你仔细看下我说的，应该是vue模板编译的问题。
还有，大哥，你回复的代码格式怎么这么好看，怎么搞得？

**Comment by zhenzhenChange** [comment]
哈哈，过年不放假嘛，辛苦辛苦~

代码格式是 markdown 的语法，给代码块加上语言就可以了

看这个链接：https://blog.csdn.net/peng2hui1314/article/details/104755498/

**Comment by SorrowX** [comment]
你说<el-table v-loading="true"></el-table>这样也不行

估计还是模板编译有问题，没有拿到正确的dir，所以没有执行正确的钩子，你可以在loading组件那个指令.ts文件的钩子打个断点，估计没执行进去。

你说的官网可以，我也试了，options api和steup加reactive是可以的，就是steup和ref联合使用出了问题。如果你也是这个问题，你可以看下我最上面解释的理由

好的，谢谢大哥的链接

**Comment by zhenzhenChange** [comment]
我大概也看了一下你的解释，不过奈何水平不够，大部分还是懵懂的，哈哈，等待大佬你们来解决。

**Comment by SorrowX** [comment]
😃，那坐等官方给出答案吧

**Comment by SorrowX** [comment]
@zhenzhenChange 
1.大哥，我刚才试了一下，我们是同一类型的bug，我感觉尤大那边修复就可以了。
2.下面是根据你提供的信息写的2个demo(注意生产环境都能正常运行)
https://jsfiddle.net/expksj6u/  这个demo,在开发和生产环境都能正常运行
https://jsfiddle.net/trdv4xeu/ 这个demo，生产环境ok,但是放在本地开发环境，就没有效果了，和我提的这个bug一样。
3.就拿https://jsfiddle.net/trdv4xeu/ 这个demo来说明原因吧
a.原因还是模板编译后的render函数有问题
b.看render函数, $setup["loading"]结果是Boolean值，不是element/loading/src/directive.ts抛出的vLoading对象，所以压根没执行相应的mounted，updated，unmounted钩子，所以就没效果了。
```dark
function render(_ctx, _cache, $props, $setup, $data, $options) {

  var _component_el_table_column = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table-column");

  var _component_el_table = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table");

  return Object(vue__WEBPACK_IMPORTED_MODULE_0__["withDirectives"])((Object(vue__WEBPACK_IMPORTED_MODULE_0__["openBlock"])(), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createBlock"])(_component_el_table, {
    border: "",
    stripe: "",
    data: $setup.data
  }, {
    default: Object(vue__WEBPACK_IMPORTED_MODULE_0__["withCtx"])(function () {
      return [Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "date",
        label: "日期",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "name",
        label: "姓名",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "address",
        label: "地址"
      })];
    }),
    _: 1
    /* STABLE */

  }, 8
  /* PROPS */
  , ["data"])), [[$setup["loading"], $setup.loading]]);

}
```

**Comment by zhenzhenChange** [comment]
wow，了解了，了解了，谢谢大伙

> as I temporary workaround, you can trigger loader via service
> e.g.
> 
> ```js
> <template>
>   <div ref="root">This is a root element</div>
> </template>
> 
> <script>
> 
> import {ref, onMounted} from 'vue';
> import { ElLoading } from 'element-plus';
> 
> export default {
>     setup() {
>       const root = ref(null);
> 
>       onMounted(() => {
>         const loadingInstance = ElLoading.service({
>           target: root.value.$el, //  Accepts a DOM object or a string. If it's a string, it will be passed to document.querySelector to get the corresponding DOM node
>           fullscreen: false
>         });
> 
>         // do some async staff here...
> 
>         // loadingInstance.close(); // close loader
>       })
> 
>       return {
>         root
>       }
>     }
>   }
> 
> </script>
> ```
> 
> https://element-plus.org/#/en-US/component/loading#service

也谢谢大哥提供的临时解决方案

**Comment by SorrowX** [comment]
@yaremayurchyshyn 

1. Thank you for your plan, the service method can indeed be called.

2. Because the essence of ElLoading.service is still calling Loading(options), but the bug I mentioned is caused by not executing the relevant hooks in the vLoading instruction.

**Comment by Ryan2128** [comment]
Duplicate #1431 , this might be vue's error, when the directive name is the same as a varriable which is returned in `setup`. I don't know if this is due to the design of Vue or a bug.

For the transition invalid when child node is text node, you can add `body` modifier to `v-loading`. This modifier will append loading's dom to `<body>`, so can avoid this error.

**Comment by Ryan2128** [comment]
> 我也遇到同样的问题，不过我没有详细去测试，就算不用 ref，直接给一个 true 都不会启动 loading
> 
> vue composition fn：
> 
> ```ts
> const data = ref([])
> const loading = ref(false)
> 
> const requestState = async () => {
>     // 开启 loading
>     loading.value = true
> 
>     try {
>       // 这里进行 http 请求，然后将请求结果赋值给 table data prop
>       data.value = "http result"
>     } catch (error) {
>       console.log(error)
>     } finally {
>       // 最终关闭 loading
>       loading.value = false
>     }
> }
> ```
> 
> vue sfc:
> 
> ```
> <script setup lang="ts">
> import { onMounted } from "vue"
> 
> import { data, loading, requestState } from "./xxxxFn"
> 
> onMounted(async () => await requestState())
> </script>
> 
> <template>
>   
>   <el-table border stripe :data="data" v-loading="loading"></el-table>
> </template>
> ```
> 
> 即使是这样都不会开启 loading
> 
> ```
> <el-table v-loading="true"></el-table>
> ```
> 
> 官网的例子可以，唯一的区别就是，我这里是使用 setup 选项，并且使用 ref 值，而官网的不是，所以我猜测可能也是 setup 或者 ref 相关的问题

If you use `v-loading='true'` directly, it works well, you can check [this demo](https://codesandbox.io/s/element-plus-spa-forked-lex00).

**Comment by SorrowX** [comment]
1. 这个bug我觉得是vue 模板编译的问题，而不是指令名和绑定的变量同名的原因。因为除了使用ref，其他使用reactive和options api都是正常的。还有你看我最上面贴的模板编译代码，可以对照参考下，问题感觉出现在那里。
2. 感谢告知动画问题的解决方案，不过我那个demo的问题和问题原因，我觉得我说的也没错。
3. 大哥，我英文不好，就用中文回复了😂

**Comment by SorrowX** [comment]
> > 我也遇到同样的问题，不过我没有详细去测试，就算不用 ref，直接给一个 true 都不会启动 loading
> > vue composition fn：
> > ```ts
> > const data = ref([])
> > const loading = ref(false)
> > 
> > const requestState = async () => {
> >     // 开启 loading
> >     loading.value = true
> > 
> >     try {
> >       // 这里进行 http 请求，然后将请求结果赋值给 table data prop
> >       data.value = "http result"
> >     } catch (error) {
> >       console.log(error)
> >     } finally {
> >       // 最终关闭 loading
> >       loading.value = false
> >     }
> > }
> > ```
> > 
> > 
> > vue sfc:
> > ```
> > <script setup lang="ts">
> > import { onMounted } from "vue"
> > 
> > import { data, loading, requestState } from "./xxxxFn"
> > 
> > onMounted(async () => await requestState())
> > </script>
> > 
> > <template>
> >   
> >   <el-table border stripe :data="data" v-loading="loading"></el-table>
> > </template>
> > ```
> > 
> > 
> > 即使是这样都不会开启 loading
> > ```
> > <el-table v-loading="true"></el-table>
> > ```
> > 
> > 
> > 官网的例子可以，唯一的区别就是，我这里是使用 setup 选项，并且使用 ref 值，而官网的不是，所以我猜测可能也是 setup 或者 ref 相关的问题
> 
> If you use `v-loading='true'` directly, it works well, you can check [this demo](https://codesandbox.io/s/element-plus-spa-forked-lex00).

你把他的问题放在本地开发环境中，就能复现了，官网因为是生产环境，模板编译的结果和开发环境的模板编译结果不同。

**Comment by Ryan2128** [comment]
> 1. 这个bug我觉得是vue 模板编译的问题，而不是指令名和绑定的变量同名的原因。因为除了使用ref，其他使用reactive和options api都是正常的。还有你看我最上面贴的模板编译代码，可以对照参考下，问题感觉出现在那里。
> 2. 感谢告知动画问题的解决方案，不过我那个demo的问题和问题原因，我觉得我说的也没错。
> 3. 大哥，我英文不好，就用中文回复了😂

Indeed, it seems that something went wrong in my last test. The reason for this error has been found during the last test.

Thank you very much for your help.

**Comment by Ryan2128** [comment]
> 你把他的问题放在本地开发环境中，就能复现了，官网因为是生产环境，模板编译的结果和开发环境的模板编译结果不同。

In my local, it still works well.

![image](https://user-images.githubusercontent.com/33176053/108014618-3a6bd100-7049-11eb-9dc3-9ecf41af730d.png)

**Comment by SorrowX** [comment]
> > 你把他的问题放在本地开发环境中，就能复现了，官网因为是生产环境，模板编译的结果和开发环境的模板编译结果不同。
> 
> In my local, it still works well.
> 
> ```
> <template>
>   <div>
>     <el-table v-loading="true"></el-table>
>   </div>
> </template>
> 
> 
> <script>
> import { ref } from "vue";
> export default {
>   setup() {
>     const input = ref("");
>     return {
>       input,
>     };
>   },
> };
> </script>
> ```
> 
> ![image](https://user-images.githubusercontent.com/33176053/108014618-3a6bd100-7049-11eb-9dc3-9ecf41af730d.png)

好吧，我可能记错了，不好意思。
大哥，你如果有空，把这个地址的代码放到你的本地开发环境中试试https://jsfiddle.net/trdv4xeu/
我记得当时是有问题的

**Comment by Ryan2128** [comment]
> 好吧，我可能记错了，不好意思。
> 大哥，你如果有空，把这个地址的代码放到你的本地开发环境中试试https://jsfiddle.net/trdv4xeu/
> 我记得当时是有问题的

You should modify the name of `loading` varriable.

**Comment by SorrowX** [comment]
> > 1. 这个bug我觉得是vue 模板编译的问题，而不是指令名和绑定的变量同名的原因。因为除了使用ref，其他使用reactive和options api都是正常的。还有你看我最上面贴的模板编译代码，可以对照参考下，问题感觉出现在那里。
> > 2. 感谢告知动画问题的解决方案，不过我那个demo的问题和问题原因，我觉得我说的也没错。
> > 3. 大哥，我英文不好，就用中文回复了😂
> 
> Indeed, it seems that something went wrong in my last test. The reason for this error has been found during the last test.
> 
> Thank you very much for your help.

1.如果你也觉得是vue的bug，那就终结此贴吧。
2.毕竟我也有好多种方式去避免这个bug
3.由于我喜欢对vue或者vue ui库的有关问题追查原因，所以才提了这个bug

**Comment by Ryan2128** [comment]
This is a bug in vue, waiting to be fixed.

**Comment by zhenzhenChange** [comment]
我明白了，还真是同名的问题。

这样是可以的
```html
<script setup></script>

<template>
  <el-table v-loading="true"></el-table>
</template>
```

出现任何的`loading` 变量就不行，不管这个`loading`是什么类型的数据（ref，还是普通值）

```html
<script setup>
const loading = "any string"
</script>

<template>
  <!-- 上下文有 loading 变量，则不生效 -->
  <el-table v-loading="true"></el-table>
</template>
```

只要不出现`loading`变量就行了
```html
<script setup>
const loading123 = "any string"
</script>

<template>
  <!-- ok 没毛病 -->
  <el-table v-loading="true"></el-table>
</template>
```

**Comment by SorrowX** [comment]
> > 好吧，我可能记错了，不好意思。
> > 大哥，你如果有空，把这个地址的代码放到你的本地开发环境中试试https://jsfiddle.net/trdv4xeu/
> > 我记得当时是有问题的
> 
> You should modify the name of `loading` varriable.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108015592-7f910280-704b-11eb-9386-6aee028292d2.png)

1.改个变量名或许可以
2.https://jsfiddle.net/expksj6u/ 这个例子不改变 变量名也是可以的

**Comment by SorrowX** [comment]
> This is a bug in vue, waiting to be fixed.

1.相同的想法😃
2.等我回去，我试试使用loading1这个变量来绑定，看看模板编译成啥样😉
3.此贴终结

**Comment by zhenzhenChange** [comment]
我觉得出现这个 bug，可能跟以下几点有关：

- 有没有使用 `<script setup>`
- 有没有使用 `ref`
- 有没有使用同名变量 `loading`

或者是以上任意情况的组合，可能就会出现这个 bug，详细的结果还需要测试一下

**Comment by SorrowX** [comment]
1. https://jsfiddle.net/trdv4xeu/ 还是这个例子，我改变指令绑定的变量名，换成loading1,本地发开确实正常了，对结果稍微做了以下解释

2. 模板编译的结果不同
a. 使用 var loading1 = ref(false); v-loading="loading1"编译后的render函数结果如下(这是正常的,_directive_loading拿到了正常的指令钩子)
```dart
function render(_ctx, _cache, $props, $setup, $data, $options) {
  var _component_el_table_column = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table-column");

  var _component_el_table = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table");

  var _directive_loading = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveDirective"])("loading");

  return Object(vue__WEBPACK_IMPORTED_MODULE_0__["withDirectives"])((Object(vue__WEBPACK_IMPORTED_MODULE_0__["openBlock"])(), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createBlock"])(_component_el_table, {
    border: "",
    stripe: "",
    data: $setup.data
  }, {
    default: Object(vue__WEBPACK_IMPORTED_MODULE_0__["withCtx"])(function () {
      return [Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "date",
        label: "日期",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "name",
        label: "姓名",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "address",
        label: "地址"
      })];
    }),
    _: 1
    /* STABLE */

  }, 8
  /* PROPS */
  , ["data"])), [[_directive_loading, $setup.loading1]]);
}

```

b.使用 var loading = ref(false); v-loading="loading"编译后的render函数结果如下(这就不正常,$setup["loading"]是个布尔值，不是element-plus/packages/loading/src/directive.ts中的钩子函数)

```dart
function render(_ctx, _cache, $props, $setup, $data, $options) {
  var _component_el_table_column = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table-column");

  var _component_el_table = Object(vue__WEBPACK_IMPORTED_MODULE_0__["resolveComponent"])("el-table");

  return Object(vue__WEBPACK_IMPORTED_MODULE_0__["withDirectives"])((Object(vue__WEBPACK_IMPORTED_MODULE_0__["openBlock"])(), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createBlock"])(_component_el_table, {
    border: "",
    stripe: "",
    data: $setup.data
  }, {
    default: Object(vue__WEBPACK_IMPORTED_MODULE_0__["withCtx"])(function () {
      return [Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "date",
        label: "日期",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "name",
        label: "姓名",
        width: "180"
      }), Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])(_component_el_table_column, {
        prop: "address",
        label: "地址"
      })];
    }),
    _: 1
    /* STABLE */

  }, 8
  /* PROPS */
  , ["data"])), [[$setup["loading"], $setup.loading]]);
}

```

3.这2个render函数的编译结果应该是vue-loader处理的，超出我的能力范围了，就不进行debugger追踪为什么绑定不同的变量名，render函数的结果却不同。

4.至于这个例子https://jsfiddle.net/trdv4xeu/ 为啥是正常的，https://unpkg.com/vue@next 应该是包含模板编译的完整版，使用Vue.compile编译后的结果是正常的，所以没毛病。（以下通过Vue.compile编译的结果和a中的编译结果类似）
```dart
function render(_ctx, _cache) {
  with (_ctx) {
    const { resolveComponent: _resolveComponent, createVNode: _createVNode, resolveDirective: _resolveDirective, withCtx: _withCtx, withDirectives: _withDirectives, openBlock: _openBlock, createBlock: _createBlock } = _Vue

    const _component_el_table_column = _resolveComponent("el-table-column")
    const _component_el_table = _resolveComponent("el-table")
    const _directive_loading = _resolveDirective("loading")

    return _withDirectives((_openBlock(), _createBlock(_component_el_table, {
      border: "",
      stripe: "",
      data: data
    }, {
      default: _withCtx(() => [
        _createVNode(_component_el_table_column, {
          prop: "date",
          label: "日期",
          width: "180"
        }),
        _createVNode(_component_el_table_column, {
          prop: "name",
          label: "姓名",
          width: "180"
        }),
        _createVNode(_component_el_table_column, {
          prop: "address",
          label: "地址"
        })
      ]),
      _: 1 /* STABLE */
    }, 8 /* PROPS */, ["data"])), [
      [_directive_loading, loading]
    ])
  }
}
```

5.好吧，至此我不再纠结了，后续等待vue-loader更新或者参考zhenzhenChange说的注意事项，Ryan2128说的变相解决方案，yaremayurchyshyn 说的使用服务方式调用。

**Comment by Ryan2128** [comment]
Waitting for being fixed:

[Vue #3275](https://github.com/vuejs/vue-next/issues/3275)
[Vue #3270](https://github.com/vuejs/vue-next/issues/3270)

**Comment by SorrowX** [comment]
> Waitting for being fixed:
> 
> [Vue #3275](https://github.com/vuejs/vue-next/issues/3275)
> [Vue #3270](https://github.com/vuejs/vue-next/issues/3270)

感谢！

看来一开始的我的解释没错

**Comment by Silentdoer** [comment]
this can be closed?

**Comment by HuangZhaoPing** [comment]
setup不要return loading就ok

**Comment by Silentdoer** [comment]
这个是不是可以关闭了，vue应该解决了这个bug吧？

**Comment by zhenzhenChange** [comment]
我刚刚升级了最新版（除了`vite`）试了一下，这个问题依旧存在

- "element-plus": "^1.0.2-beta.41"
- "vue": "^3.0.11"
- "@vitejs/plugin-vue": "^1.2.1"
- "@vue/compiler-sfc": "^3.0.11"
- "vite": "^2.1.5"

**Comment by hr837** [comment]
> 我明白了，还真是同名的问题。
> 
> 这样是可以的
> 
> ```
> <script setup></script>
> 
> <template>
>   <el-table v-loading="true"></el-table>
> </template>
> ```
> 
> 出现任何的`loading` 变量就不行，不管这个`loading`是什么类型的数据（ref，还是普通值）
> 
> ```
> <script setup>
> const loading = "any string"
> </script>
> 
> <template>
>   
>   <el-table v-loading="true"></el-table>
> </template>
> ```
> 
> 只要不出现`loading`变量就行了
> 
> ```
> <script setup>
> const loading123 = "any string"
> </script>
> 
> <template>
>   
>   <el-table v-loading="true"></el-table>
> </template>
> ```

牛逼呀大哥，刚好解决了我的问题。
因为我的页面里面用了自定义的LoadingService，所以变量名叫loading，改了变量名就解决。

```js
// 不工作
const loadingStatus = ref(false);
const loading = new LoadingService();
onMounted(() => {
	loading.status.subscribe((v) => (loadingStatus.value = v));
	model.approvalStatus = "WAIT_APPROVAL";
	refreshData();
});
```

```js
// 工作了
const loadingStatus = ref(false);
const loadingService = new LoadingService();
onMounted(() => {
	loadingService.status.subscribe((v) => (loadingStatus.value = v));
	model.approvalStatus = "WAIT_APPROVAL";
	refreshData();
});
```
