### ISSUE TITLE
[Bug Report] el-date-picker in el-tooltip causes warning

### ISSUE THREAD

**Issue by ysinsane** [element-plus/element-plus#1455]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Mac OS big sur 11.2/ Chrome 88.0.4324.96 (x86_64)

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-bug-mhkny

### Steps to reproduce
run it you'll see console warnings.

### What is Expected?
Hope it not generate so much warnings.

### What is actually happening?
Gets lots of warnings like below because component renders fragment or text root nodes. 

[Vue warn]: Extraneous non-props attributes (value-format, ariaDescribedby) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ElPopper ref="refPopper"

**Comment by iendeavor** [comment]
The value-format is no longer supported now, and the value/v-model binding value is Date instance.
Reference: [document](https://element-plus.org/#/en-US/component/date-picker).

**Comment by ysinsane** [comment]
> The value-format is no longer supported now, and the value/v-model binding value is Date instance.
> Reference: [document](https://element-plus.org/#/en-US/component/date-picker).

Hi, let's skip the value-format attr.
The real problem is that el-date-picker cannot be use in el-tooltip. Here is a codepen example. Check the console output.
https://codepen.io/eason_yan/pen/vYyajaJ
