### ISSUE TITLE
[Docs] [notification] 中文文档不维护了吗？部分api说明，英语和西班牙语都是对的，就中文是错的！

### ISSUE THREAD

**Issue by pandafeeeder** [element-plus/element-plus#14563]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPiBDbG9zZXMgYXV0b21hdGljYWxseSA8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMlwiPiBXb24ndCBjbG9zZSBhdXRvbWF0aWNhbGx5IDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGggfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE5vdGlmaWNhdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbjEgPSAoKSA9PiB7XG4gIEVsTm90aWZpY2F0aW9uKHtcbiAgICB0aXRsZTogJ1RpdGxlJyxcbiAgICBtZXNzYWdlOiBoKCdpJywgeyBzdHlsZTogJ2NvbG9yOiB0ZWFsJyB9LCAnVGhpcyBpcyBhIHJlbWluZGVyJyksXG4gIH0pXG59XG5cbmNvbnN0IG9wZW4yID0gKCkgPT4ge1xuICBFbE5vdGlmaWNhdGlvbih7XG4gICAgdGl0bGU6ICdQcm9tcHQnLFxuICAgIG1lc3NhZ2U6ICdUaGlzIGlzIGEgbWVzc2FnZSB0aGF0IGRvZXMgbm90IGF1dG9tYXRpY2FsbHkgY2xvc2UnLFxuICAgIGR1cmF0aW9uOiAwLFxuICAgICdvbi1jbG9zZSc6KCk9PnthbGVydCgnY2xvc2UnKX1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<template>
  <el-button plain @click="open1"> Closes automatically </el-button>
  <el-button plain @click="open2"> Won't close automatically </el-button>
</template>

<script lang="ts" setup>
import { h } from 'vue'
import { ElNotification } from 'element-plus'

const open1 = () => {
  ElNotification({
    title: 'Title',
    message: h('i', { style: 'color: teal' }, 'This is a reminder'),
  })
}

const open2 = () => {
  ElNotification({
    title: 'Prompt',
    message: 'This is a message that does not automatically close',
    duration: 0,
    'on-close':()=>{alert('close')}
  })
}
</script>

### What is Expected?

关闭notification，页面弹出提示框

### What is actually happening?

页面没有弹出提示框

### Additional comments

英文和西班牙语api说明都是'onClose',中文是'on-close',notify源文件里面userOnClose = options.onClose,这怎么能调用得到？

**Comment by lixinru1234** [comment]
傻屌  你不去给文档捐赠拿脚给你维护吗  有的看就不错了  还在这挑三拣四

**Comment by yj-liuzepeng** [comment]
翻译的问题你可以帮他改一下在这 https://accounts.crowdin.com/login?continue=%2Ftranslate%2Felement-plus%2Fall%2Fen-zhcn

**Comment by WangJincheng4869** [comment]
发现文档错误就提一个PR，开源项目每个人都可以参与，没有实力写代码，发现文档错误帮助改一下也是一种贡献

**Comment by 0song** [comment]
fixed thanks 
<img width="401" alt="image" src="https://github.com/element-plus/element-plus/assets/82012629/ffc0989d-db5c-42f2-bcd4-c5db902dce0a">
