### ISSUE TITLE
[Component] [watermark] watermark水印组件引用报错

### ISSUE THREAD

**Issue by Y00z** [element-plus/element-plus#14560]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.0`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-watermark`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/watermark.html)

### Steps to reproduce

<el-watermark :content="['Element+', 'Element Plus']">
    <div style="height: 500px" />
  </el-watermark>

### What is Expected?

<el-watermark :content="['Element+', 'Element Plus']">
    <div style="height: 500px" />
  </el-watermark>

### What is actually happening?

<el-watermark :content="['Element+', 'Element Plus']">
    <div style="height: 500px" />
  </el-watermark>

### Additional comments

vite.config.ts 配置
export default ({ mode }: { mode: string }) => {
  const plugins: PluginOption[] = [
    vue(),
    Components({
      resolvers: [ElementPlusResolver()]
    })
  ]
  const env = loadEnv(mode, './')
  return defineConfig({
    plugins,
    css: {
      postcss: {
        plugins: [autoprefixer]
      }
    },
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url))
      }
    },
    build: {
      assetsDir: 'static',
      rollupOptions: {
        output: {
          manualChunks: splitVendorChunk
        }
      }
    },
    experimental: {
      renderBuiltUrl(filename: string, { type }: { hostId: string; hostType: 'js' | 'css' | 'html'; type: 'public' | 'asset' }) {
        if (type === 'public') {
          return '/' + filename
        } else {
          return env.VITE_CDN_PATH + filename
        }
      }
    },
    test: {
      globals: true,
      environment: 'jsdom',
      coverage: {
        provider: 'istanbul'
      }
    }
  })
}

报错信息：
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/watermark/style/css" from "src/pages/home/HomeView.vue". Does the file exist?
/***/HomeView.vue:1:171
1  |  /* unplugin-vue-components disabled */import { ElWatermark as __unplugin_components_0 } from 'element-plus/es';import 'element-plus/es/components/base/style/css';import 'element-plus/es/components/watermark/style/css';
   |                                                                                                                                                                            ^
2  |  import { defineComponent } from "vue";
3  |  const _sfc_main = defineComponent({});

<img width="858" alt="image" src="https://github.com/element-plus/element-plus/assets/18053148/a5210c79-9041-4c51-a433-360c002fbdb2">

**Comment by Ttou** [comment]
同样的问题，全局类型也没配置好

**Comment by Y00z** [comment]
> 相同的问题，全局类型也配置好

你找到问题了吗

**Comment by tolking** [comment]
应该可以向下面这样配置临时解决问题

```ts
ElementPlusResolver({
  noStylesComponents: ['ElWatermark'],
})
```

**Comment by Y00z** [comment]
> 应该可以向下面这样配置临时解决问题
> 
> ```ts
> ElementPlusResolver({
>   noStylesComponents: ['ElWatermark'],
> })
> ```

<img width="526" alt="image" src="https://github.com/element-plus/element-plus/assets/18053148/3c19b4bc-fdbe-49c6-82f6-3772eb7b6e8b">

加上后又报这个错。
