### ISSUE TITLE
[Feature Request] [New Component] [] 提个建议：menu菜单严重bug，希望官方大大认真审核PR，不要让一些菜鸡的狗屎代码也能提交上来

### ISSUE THREAD

**Issue by lixinru1234** [element-plus/element-plus#14566]
Feature type: **`New Component`**

## Details

- New component name: `期待朱坤、杨奕等大佬回归
`

## Description

select, popper，还有menu的ul标签的高度设置有问题，无法覆盖掉子元素 这就是导致一旦子元素是透明的就会出现在容器外面，以前是没问题的，menu菜单严重bug，希望官方大大认真审核PR，不要让一些菜鸡的狗屎代码也能提交上了，期待朱坤、杨奕等大佬回归饿了么，现在的代码质量实在是太差劲了 一点测试都没有的 让人觉得像是学生干的活一样 一点严谨性都没有 本来都是用的好好的 每次发个新版本必须带点坑进来

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/148168556/34bf5dd5-e3fc-44c3-9fbb-80cab0d59237)

看了下是这个人写的狗屎代码影响到的，线上的项目pover相关的外层高度全坏了：

![image](https://github.com/element-plus/element-plus/assets/148168556/1d1bce28-d1f9-4701-a996-b0a69caf1cd2)
![image](https://github.com/element-plus/element-plus/assets/148168556/83f7c6b5-8bca-4703-a699-75c8d8f8c5af)

**Comment by geedys** [comment]
我也遇到这个问题, 暂时的解决方案:

**Comment by geedys** [comment]
我也遇到这个问题,看了官方的文档中横向菜单也出了这个bug, 暂时的解决方案: 
.el-menu--horizontal{
	height: unset;
}

**Comment by yj-liuzepeng** [comment]
> Feature type: **`New Component`**
> 
> ## Details
> * New component name: `期待朱坤、杨奕等大佬回归 `
> 
> ## Description
> select, popper，还有menu的ul标签的高度设置有问题，无法覆盖掉子元素 这就是导致一旦子元素是透明的就会出现在容器外面，以前是没问题的，menu菜单严重bug，希望官方大大认真审核PR，不要让一些菜鸡的狗屎代码也能提交上了，期待朱坤、杨奕等大佬回归饿了么，现在的代码质量实在是太差劲了 一点测试都没有的 让人觉得像是学生干的活一样 一点严谨性都没有 本来都是用的好好的 每次发个新版本必须带点坑进来
> 
> ### Additional comments
> _(empty)_
> 
> ![image](https://user-images.githubusercontent.com/148168556/275678920-34bf5dd5-e3fc-44c3-9fbb-80cab0d59237.png)
> 
> 看了下是这个人写的狗屎代码影响到的，线上的项目pover相关的外层高度全坏了：
> 
> ![image](https://user-images.githubusercontent.com/148168556/275679440-1d1bce28-d1f9-4701-a996-b0a69caf1cd2.png) ![image](https://user-images.githubusercontent.com/148168556/275679502-83f7c6b5-8bca-4703-a699-75c8d8f8c5af.png)

你竟然说这个人是菜鸡，写的还是狗屎，你是多厉害啊！！

**Comment by boomboy4** [comment]
@YunYouJun 被cue了

**Comment by YunYouJun** [comment]
很抱歉给您带来不好的体验，该问题是我的疏忽导致，没有考虑到其他场景且较难通过测试代码，我们正在排查原因，将尽快解决该问题。

**Comment by lixinru1234** [comment]
> 很抱歉给您带来不好的体验，该问题是我的疏忽导致，没有考虑到其他场景且较难通过测试代码，我们正在排查原因，将尽快解决该问题。

大佬我错了  我以为是小白提交的 被你合并的

**Comment by lixinru1234** [comment]
> 很抱歉给您带来不好的体验，该问题是我的疏忽导致，没有考虑到其他场景且较难通过测试代码，我们正在排查原因，将尽快解决该问题。

小问题不打紧 大佬注意休息

**Comment by likui628** [comment]
建议保持冷静和尊重，避免使用侮辱性的语言。

**Comment by baiwusanyu-c** [comment]
慕名而来

**Comment by so1ve** [comment]
慕名而来

**Comment by zhangmo8** [comment]
慕名+1

**Comment by haoziqaq** [comment]
哈哈哈

**Comment by beiranc** [comment]
慕名而来

**Comment by sxzz** [comment]
本 issue 关闭。
如需继续讨论，请另开 issue 并使用礼貌用语讨论。
