### ISSUE TITLE
Custom first day in date picker

### ISSUE THREAD

**Issue by Oleksii14** [element-plus/element-plus#1458]
Hello guys! Can you please add an additional prop for the custom first day of the week? So the users could provide their own value. For now, it is generated automatically in this line:
https://github.com/element-plus/element-plus/blob/0380fa7bde5196a56883dc557cec7d9cbd10f873/packages/date-picker/src/date-picker-com/basic-date-table.vue#L98

Thanks in advance!

**Comment by kooriookami** [comment]
https://element-plus.org/#/en-US/component/i18n#set-day.js-locale

**Comment by ddeboer** [comment]
That section is gone from the docs. What is currently the recommended way to configure the first day of the week?
