### ISSUE TITLE
[bug report] on demand loading style failure

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#1460]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
win10

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/romantic-rosalind-mzmps

### Steps to reproduce
使用按需加载样式失效,官网的按需加载方式也是一样

npm i babel-plugin-component 

babel.config.js配置：
 "plugins": [
        [
            "component",
            {
                "libraryName": "element-plus",
                "styleLibraryName": "theme-chalk"
            }
        ]
    ]

### What is Expected?
怎么解决该问题

### What is actually happening?
已经尝试了两种方式(官网借助babel-plugin-import方式和vue add element-plus方式)都是相同的问题，按需加载样式失效

**Comment by Ryan2128** [comment]
Can you provide a repo? I test your demo in my local, it works well.

**Comment by vela666** [comment]
> 您可以提供回购吗？我在本地测试了您的演示，效果很好。



> Can you provide a repo? I test your demo in my local, it works well.

https://github.com/vela666/test  看这个

**Comment by Ryan2128** [comment]
I cloned the repo you provided, it still works will.

![image](https://user-images.githubusercontent.com/33176053/108621998-18bb8100-7471-11eb-9476-0391cacd9eff.png)

I did not change any of your code.

![image](https://user-images.githubusercontent.com/33176053/108622020-312b9b80-7471-11eb-900d-793c62ee0533.png)

**Comment by vela666** [comment]
> I cloned the repo you provided, it still works will.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108621998-18bb8100-7471-11eb-9476-0391cacd9eff.png)
> 
> I did not change any of your code.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108622020-312b9b80-7471-11eb-900d-793c62ee0533.png)



> I cloned the repo you provided, it still works will.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108621998-18bb8100-7471-11eb-9476-0391cacd9eff.png)
> 
> I did not change any of your code.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108622020-312b9b80-7471-11eb-900d-793c62ee0533.png)

You can try clicking the "click more" button multiple times.

**Comment by vela666** [comment]
> I cloned the repo you provided, it still works will.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108621998-18bb8100-7471-11eb-9476-0391cacd9eff.png)
> 
> I did not change any of your code.
> 
> ![image](https://user-images.githubusercontent.com/33176053/108622020-312b9b80-7471-11eb-900d-793c62ee0533.png)

The style of the occlusion layer is missing.

**Comment by Ryan2128** [comment]
Thanks, I got it.
