### ISSUE TITLE
[Bug Report] Input "password visible" view error

### ISSUE THREAD

**Issue by STARKXu** [element-plus/element-plus#1462]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Windows 10  Edge 88.0.705.68

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/starkxu/pen/vYygwjB

### Steps to reproduce
When you type into the password box, two eyes appear.

### What is Expected?
fix the bug.

### What is actually happening?
When you type into the password box, two eyes appear.

**Comment by Ryan2128** [comment]
I can not reproduce this error in your demo.

![image](https://user-images.githubusercontent.com/33176053/108013150-0d69ef00-7046-11eb-9c3c-a2e650d17c32.png)

![image](https://user-images.githubusercontent.com/33176053/108013168-15299380-7046-11eb-9ca5-f6495b333684.png)

**Comment by STARKXu** [comment]
This is a problem when using the Edge.

**Comment by STARKXu** [comment]
This is a built-in feature of the Edge.
Solution:
`input[type="password"]::-ms-reveal {
  display: none;
}`
