### ISSUE TITLE
[Style] [button, button-group] I want the style to automatically return to its original state after clicking the button

### ISSUE THREAD

**Issue by ljh-code** [element-plus/element-plus#14637]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome/win10`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-button-group`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html#%E5%9B%BE%E6%A0%87%E6%8C%89%E9%92%AE)

### Steps to reproduce

The buttons in the elementUI will have a focus style after clicking, and only after clicking elsewhere will the button lose focus and the style will be restored to the previous style. For example, the main button is bright blue, and when clicked, it is dark blue. Clicking elsewhere will restore the bright blue color。elementUI 中的按钮，点击后会有focus样式，且只有点击其他地方后，按钮才会失焦，样式才会恢复到点击之前的样式。例如主要按钮是亮蓝色，点击后是暗蓝色。点击其他地方才会恢复亮蓝色。

### What is Expected?

I want the style to automatically return to its original state after clicking the button。我希望点击按钮后样式自动恢复到点击前的样子

### What is actually happening?

After clicking the button, there will be a focus style, and only after clicking elsewhere will the button lose focus and the style will be restored to the previous style。按钮点击后会有focus样式，且只有点击其他地方后，按钮才会失焦，样式才会恢复到点击之前的样式。

### Additional comments

_(empty)_

**Comment by CherishTheYouth** [comment]
I met this problem too, and I solved it  by this way:
define a directive to listen the el-button click event, when you click the el-button, it will auto set the el-button to blur.

Here is how I realize that, hope useful for you!

https://juejin.cn/post/7295720738568978467

```ts
// main.ts
import { createApp, type DirectiveBinding, type VNode } from 'vue'
import App from './App.vue'
const app = createApp(App)

const elBlur = (el: HTMLElement) => {
  return () => el?.blur()
}

app.directive('blur', {
    created (el: HTMLElement, binding: DirectiveBinding, vnode: VNode) {
        if (vnode?.type === 'button') {
          el.addEventListener('click', elBlur(el))
        }
    },
    unmounted (el: HTMLElement) {
        el.removeEventListener('click', elBlur(el))
    }
})
app.mount('#app')

```

```html
<template>
    <el-button type="primary" v-blur>Primary</el-button>
    <el-button type="success" v-blur>Success</el-button>
    <el-button type="warning" v-blur>Warning</el-button>
</template>

```
![image](https://github.com/element-plus/element-plus/assets/41944818/23f11597-8242-475f-b99e-ad6e45a767c1)

**Comment by CherishTheYouth** [comment]
It's probably not a bug, it's designed that way.

**Comment by tolking** [comment]
Link #12221

You can modify the style yourself

[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+UHJpbWFyeTwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBkaXNhYmxlZD5QcmltYXJ5PC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5lbC1idXR0b246Zm9jdXMge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjAwICFpbXBvcnRhbnQ7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)
