### ISSUE TITLE
[Feature Request] Keep increasing or decreasing when controls are being held down on mobile

### ISSUE THREAD

**Issue by JarnoRFB** [element-plus/element-plus#1463]
### Existing Component
Yes

### Component Name
el-input-number

### Description
Hi, great library!

Currently `el-input-number´ keeps increasing or decreasing when the controls are being held clicked in a desktop browsers, which is nice for quickly changing across larger number ranges. But on mobile browsers, one has to repeatedly click. It would be nice if the behavior on mobile browsers would resemble the behavior on desktop browsers in this way.

Probably, this can be achieved by also responding to the touchdown event here https://github.com/element-plus/element-plus/blob/dev/packages/directives/repeat-click/index.ts#L17.

**Comment by kooriookami** [comment]
May be support mobile in the future :D
