### ISSUE TITLE
[Feature Request] requried:true can't be recognize from form.validate?

### ISSUE THREAD

**Issue by Azaleta** [element-plus/element-plus#1464]
### Existing Component
Yes

### Component Name
ElForm

### Description
Version: 1.0.2-beta.32

Hi, 
I try to do a form validate in the submit button.And it seems [requried:true] form rule is not working.

<el-form ref="formRef">

 const formRules = {
      userId: [
        //{ required: true, trigger: ["blur", "change"], message: "" },
        { validator: validateUsername, trigger: "change" },
      ],
  };

const formRef = ref<InstanceType<typeof ElForm>>();

const onSubmit = () => {
      formRef.value?.validate(async (valid) => {
        if (!valid) {
          console.log("error");
          return false;
        }

if I use a validator I can get false result
but when i use required:true , it is always return true?

is there something wrong with my code?

**Comment by scx567888** [comment]
Me too
