### ISSUE TITLE
[Component] [carousel-item] vue3 h() can not render nested el-carousel 

### ISSUE THREAD

**Issue by yeminxuan** [element-plus/element-plus#14655]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.14`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-carousel-item`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-xvnunz?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue,src%2Fmain.js&terminal=dev)

### Steps to reproduce

1. open the /src/components/HelloWord.vue
2. Uncomment the annotated code in 'renderCarousel' and annotate '223'
3. you'll find a bug where the dom is present but not displayed

### What is Expected?

it's can display normally

### What is actually happening?

Each 'carousel-item' is rendered with a 'display: none' style

### Additional comments

_(empty)_

**Comment by yeminxuan** [comment]
In this case, I found that when rendering nested structures via the h() render function, el-carousel-item automatically carries a style="{display:none}" '

**Comment by chenxch** [comment]
因为是插槽，所以需要调整写法
```js
{default:[
          h(
            'div',
            {
              // 将ref绑定到Carousel组件上
              style: { color: '#fff', backgroundColor: '#fff' },
              autoplay: false,
              arrow: 'never',
              height: '100px',
            },
            item.pictureList.map((item1: any, index1: number) => {
              return h('div', { key: index1, height: '100px' }, [
                h('div', {}, item1.name),
                h('div', {}, item1.content),
              ]);
            })
          ),
          item.manager,
        ]}
```

https://vuejs.org/api/render-function.html#h
