### ISSUE TITLE
[Feature Request] CSS Custom properties

### ISSUE THREAD

**Issue by beltranrengifo** [element-plus/element-plus#1465]
### Existing Component
No

### Component Name
All

### Description
Is it possible to use css custom properties with Element plus? 
I've gave it a first look and some `mix()` scss functions make it impossible the way it is now.
I'm thinking the way to implement CSS custom pproperties, but I want to ask before anything to know your thoughts...
I think it should be great to deliver fast theming and dark/light modes for all the library.
Any help/thoughts are appreciated.
Thanks

**Comment by brent-williams** [comment]
Beautiful library but dark mode is a hard requirement for our project as well.
