### ISSUE TITLE
[Style] [popover] （element-plus@2.3.12，根据官网el-popover虚拟触发案例，在vue3中导入ClickOutside指令显示找不到node_modules/element-plus/es/components/ck-outside/style/css）                                      According to the el-popover virtual trigger case on the official website, importing ClickOutside directive in vue3 shows that it cannot be found node_modules/element-plus/es/components/ck-outside/style/css

### ISSUE THREAD

**Issue by blngblng** [element-plus/element-plus#14658]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.0`
- Element Plus Version: `2.3.12`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIHJlZiwgcmVhY3RpdmUsIHVucmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgQ2xpY2tPdXRzaWRlIGFzIHZDbGlja091dHNpZGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuZGlyZWN0aXZlczogeyB2Q2xpY2tPdXRzaWRlIH0sXG5zZXR1cCgpIHtcbiAgY29uc3QgY29uZGl0aW9uUmVmID0gcmVmKClcbiAgY29uc3QgY29uZGl0aW9uUG9wb3ZlclJlZiA9IHJlZigpXG4gIGNvbnN0IG9uQ2xpY2tPdXRzaWRlID0gKCkgPT4ge1xuICAgIHVucmVmKGNvbmRpdGlvblBvcG92ZXJSZWYpLmNvbmRpdGlvblBvcG92ZXJSZWY/LmRlbGF5SGlkZT8uKClcbiAgfVxuICByZXR1cm4ge1xuICBjb25kaXRpb25SZWYsXG4gIGNvbmRpdGlvblBvcG92ZXJSZWYsXG4gIG9uQ2xpY2tPdXRzaWRlXG4gIH1cbn1cbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgICByZWY9XCJjb25kaXRpb25SZWZcIlxuICAgICAgdi1jbGlja291dHNpZGU9XCJvbkNsaWNrT3V0c2lkZVwiXG4gICAgPlxuICAgICAgPHNwYW4+5rWL6K+V5YaF5a65PC9zcGFuPlxuICAgIDwvZGl2PlxuICAgIDxlbC1wb3BvdmVyXG4gICAgICByZWY9XCJjb25kaXRpb25Qb3BvdmVyUmVmXCJcbiAgICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgICB2aXJ0dWFsLXRyaWdnZXJpbmdcbiAgICAgIDp2aXJ0dWFsLXJlZj1cImNvbmRpdGlvblJlZlwiXG4gICAgICA6cGxhY2VtZW50PVwiJ3JpZ2h0J1wiXG4gICAgICA6cGVyc2lzdGVudD1cImZhbHNlXCJcbiAgICAgIDpoaWRlLWFmdGVyPVwiMFwiXG4gICAgPlxuICAgIDxkaXY+5rWL6K+VcG9wb3ZlcjwvZGl2PlxuICAgIDwvZWwtcG9wb3Zlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

在directives: { vClickOutside }中添加后，刷新页面就会显示

### What is Expected?

不影响指令的导入使用

### What is actually happening?

指令的导入使用失败。
报错信息：
Failed to resolve import "E:/xxxx/node_modules/element-plus/es/components/ck-outside/style/css" from "src\components\Popover\src\Popover.vue". Does the file exist?

### Additional comments

使用的部分：
<script lang="ts">
import { defineComponent, ref, unref } from 'vue'
import { ClickOutside as vClickOutside } from 'element-plus'
export default defineComponent({
directives: { vClickOutside },
setup() {
  const conditionRef = ref()
  const conditionPopoverRef = ref()
  const onClickOutside = () => {
    unref(conditionPopoverRef).conditionPopoverRef?.delayHide?.()
  }
  return {
  conditionRef,
  conditionPopoverRef,
  onClickOutside
  }
}
})
</script>

<template>
  <div
      ref="conditionRef"
     v-click-outside="onClickOutside"
    >
      <span>测试内容</span>
    </div>
    <el-popover
      ref="conditionPopoverRef"
      trigger="click"
      virtual-triggering
      :virtual-ref="conditionRef"
      :placement="'right'"
      :persistent="false"
      :hide-after="0"
    >
    <div>测试popover</div>
    </el-popover>
</template>

**Comment by blngblng** [comment]
![image](https://github.com/element-plus/element-plus/assets/47748375/6e1cca34-406c-4939-8723-78be7b079e3c)
链接中的v-clickoutside="onClickOutside"实际使用的是v-click-outside="onClickOutside"，后面调试忘记改回来了

Link in the (v-clickoutside="onClickOutside") actually used is (v-click-outside="onClickOutside"),  forgot to change back after debugging

**Comment by btea** [comment]
Could you provide a minimal reproducing warehouse address? The online playground doesn't seem to be able to reproduce this problem.

**Comment by blngblng** [comment]
> Could you provide a minimal reproducing warehouse address? The online playground doesn't seem to be able to reproduce this problem.

[https://github.com/blngblng/Demo](https://github.com/blngblng/Demo)

我重新创建了一个demo，然后根据我在实际项目中的配置来进行还原，发现在vite.config.ts中引入ElementPlusResolve后，控制台就会直接报样式引入的错误

I recreated a demo and then restored it based on my configuration in the actual project, and found that after introducing ElementPlusResolve in vite.config.ts, the console reported a style import error directly

![image](https://github.com/element-plus/element-plus/assets/47748375/0c34eba7-b889-42c4-a510-5b12fec89878)

![image](https://github.com/element-plus/element-plus/assets/47748375/4159604b-28ef-4264-8033-e13a72bb0fd1)

**Comment by blngblng** [comment]
这个路径问题我尝试去更改，取消了指令的样式导入，但是虚拟触发没有生效。
I tried to change this path problem and cancelled the style import of the directive, but the virtual trigger did not work.

![image](https://github.com/element-plus/element-plus/assets/47748375/f7187a95-64b8-4019-96ec-d42b495c4c25)

**Comment by songshuzhong** [comment]
popperRef.delayHide is not a function

**Comment by blngblng** [comment]
> popperRef.delayHide is not a function

我在main.ts做了全局组件导入，但是popover的样式没有显示，也显示popperRef.delayHide is not a function。

I did the global component import in main.ts, but the popover style is not displayed, and it also shows that popperRef.delayHide is not a function

**Comment by blngblng** [comment]
重新修改导入的style路径后，已解决
