### ISSUE TITLE
[Component] [input-number] vue中h函数加载ElInputNumber组件，v-model为边缘值时按钮会始终失效

### ISSUE THREAD

**Issue by HostDay123** [element-plus/element-plus#14652]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.6`
- Element Plus Version: `2.4.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-input-number`

### Reproduction Link

[CodePen](https://codepen.io/GGB_tony/pen/RwvPRvX)

### Steps to reproduce

使用vue中h函数加载该组件时，若初始时modelValue值与限定的max或min相等，则对应的增减按钮始终无效，详见复现链接,
[ Element Plus Playground复现链接](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiAsaH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gLEVsSW5wdXROdW1iZXJ9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBuID0gcmVmKDEpO1xuY29uc3QgbnVtID0gcmVmKDEpXG5cdFx0XHRcdFx0Ly8gbW9kZWxWYWx1ZeWIneWni+WAvOS4jm1pbuWxnuaAp+WAvOebuOetieaXtu+8jOWPquiDvemAkuWinu+8jOmAkuWHj+aMiemSruWni+e7iOaXoOazleeCueWHu1xuXHRcdFx0XHRcdGNvbnN0IGRvbSA9IGgoRWxJbnB1dE51bWJlciwge1xuXHRcdFx0XHRcdFx0c2l6ZTogJ3NtYWxsJyxcblx0XHRcdFx0XHRcdG1pbjogMSxcblx0XHRcdFx0XHRcdHN0ZXA6IDEsXG5cdFx0XHRcdFx0XHRtYXg6IDQsXG5cdFx0XHRcdFx0XHRtb2RlbFZhbHVlOiBudW0udmFsdWUsXG5cdFx0XHRcdFx0XHQnb25VcGRhdGU6bW9kZWxWYWx1ZSc6ICh2YWwpID0+IHtcblx0XHRcdFx0XHRcdFx0bnVtLnZhbHVlID0gdmFsO1xuXHRcdFx0XHRcdFx0fSxcblx0XHRcdFx0XHR9LCB7fSk7XG5cdFx0XHRcdFx0Y29uc3QgbnVtMiA9IHJlZig0KVxuXHRcdFx0XHRcdC8vIG1vZGVsVmFsdWXliJ3lp4vlgLzkuI5taW7lsZ7mgKflgLzkuI3nm7jnrYnml7bvvIzpgJLlop7pgJLlh4/lnYfmraPluLhcblx0XHRcdFx0XHRjb25zdCBkb20yID0gaChFbElucHV0TnVtYmVyLCB7XG5cdFx0XHRcdFx0XHRzaXplOiAnc21hbGwnLFxuXHRcdFx0XHRcdFx0bWluOiAxLFxuXHRcdFx0XHRcdFx0c3RlcDogMSxcblx0XHRcdFx0XHRcdG1heDogNCxcblx0XHRcdFx0XHRcdG1vZGVsVmFsdWU6IG51bTIudmFsdWUsXG5cdFx0XHRcdFx0XHQnb25VcGRhdGU6bW9kZWxWYWx1ZSc6ICh2YWwpID0+IHtcblx0XHRcdFx0XHRcdFx0bnVtMi52YWx1ZSA9IHZhbDtcblx0XHRcdFx0XHRcdH0sXG5cdFx0XHRcdFx0fSwge30pO1xuXG4gICAgICAgICAgY29uc3QgbnVtMyA9IHJlZigyKVxuXHRcdFx0XHRcdC8vIG1vZGVsVmFsdWXliJ3lp4vlgLzkuI5taW7lsZ7mgKflgLzkuI3nm7jnrYnml7bvvIzpgJLlop7pgJLlh4/lnYfmraPluLhcblx0XHRcdFx0XHRjb25zdCBkb20zID0gaChFbElucHV0TnVtYmVyLCB7XG5cdFx0XHRcdFx0XHRzaXplOiAnc21hbGwnLFxuXHRcdFx0XHRcdFx0bWluOiAxLFxuXHRcdFx0XHRcdFx0c3RlcDogMSxcblx0XHRcdFx0XHRcdG1heDogNCxcblx0XHRcdFx0XHRcdG1vZGVsVmFsdWU6IG51bTMudmFsdWUsXG5cdFx0XHRcdFx0XHQnb25VcGRhdGU6bW9kZWxWYWx1ZSc6ICh2YWwpID0+IHtcblx0XHRcdFx0XHRcdFx0bnVtMy52YWx1ZSA9IHZhbDtcblx0XHRcdFx0XHRcdH0sXG5cdFx0XHRcdFx0fSwge30pO1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD7moIfnrb7mlrnlvI/ml6DorrrliJ3lp4vml7Z2LW1vZGVs5LiObWlu5oiWbWF45YC85piv5ZCm55u4562J5Z2H5q2j5bi4PC9wPlxuXHRcdFx0PGVsLWlucHV0LW51bWJlciBzaXplPSdzbWFsbCcgOm1pbj1cIjFcIiA6bWF4PVwiNVwiIHYtbW9kZWw9XCJuXCI+PC9lbC1pbnB1dC1udW1iZXI+XG5cdFx0XHQ8cD52dWXkuK1o5Ye95pWw5Yqg6L295pa55byP77yM5Yid5aeL5pe2di1tb2RlbOS4jm1pbuWAvOebuOetiSzlkI7nu63ljbPkvb/pgJLlop7lpKfkuo5taW7lkI7vvIzpgJLlh4/mjInpkq7lp4vnu4jml6DmlYg8L3A+XG5cdFx0XHQ8Y29tcG9uZW50IDppcz1cImRvbVwiPjwvY29tcG9uZW50PlxuXHRcdFx0PHA+dnVl5LitaOWHveaVsOWKoOi9veaWueW8j++8jOWIneWni+aXtnYtbW9kZWzkuI5tYXjlgLznm7jnrYks5ZCO57ut5Y2z5L2/6YCS5YeP5bCP5LqObWlu5ZCO77yM6YCS5aKe5oyJ6ZKu5aeL57uI5peg5pWIPC9wPlxuXHRcdFx0PGNvbXBvbmVudCA6aXM9XCJkb20yXCI+PC9jb21wb25lbnQ+XG4gICAgICA8cD52dWXkuK1o5Ye95pWw5Yqg6L295pa55byP77yM5Yid5aeL5pe2di1tb2RlbOS4jeS4jm1heOaIlm1pbuWAvOebuOetiSzpgJLlop7pgJLlh4/lp4vnu4jmraPluLg8L3A+XG5cdFx0XHQ8Y29tcG9uZW50IDppcz1cImRvbTNcIj48L2NvbXBvbmVudD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

[CodePen复现链接](https://codepen.io/GGB_tony/pen/RwvPRvX)
```vue
<script setup lang="ts">
import { ref, version as vueVersion ,h} from 'vue'
import { version as epVersion ,ElInputNumber} from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
const n = ref(1);
const num = ref(1)
					// modelValue初始值与min属性值相等时，只能递增，递减按钮始终无法点击
					const dom = h(ElInputNumber, {
						size: 'small',
						min: 1,
						step: 1,
						max: 4,
						modelValue: num.value,
						'onUpdate:modelValue': (val) => {
							num.value = val;
						},
					}, {});
					const num2 = ref(4)
					// modelValue初始值与min属性值不相等时，递增递减均正常
					const dom2 = h(ElInputNumber, {
						size: 'small',
						min: 1,
						step: 1,
						max: 4,
						modelValue: num2.value,
						'onUpdate:modelValue': (val) => {
							num2.value = val;
						},
					}, {});

          const num3 = ref(2)
					// modelValue初始值与min属性值不相等时，递增递减均正常
					const dom3 = h(ElInputNumber, {
						size: 'small',
						min: 1,
						step: 1,
						max: 4,
						modelValue: num3.value,
						'onUpdate:modelValue': (val) => {
							num3.value = val;
						},
					}, {});

</script>

<template>
  <p>标签方式无论初始时v-model与min或max值是否相等均正常</p>
			<el-input-number size='small' :min="1" :max="5" v-model="n"></el-input-number>
			<p>vue中h函数加载方式，初始时v-model与min值相等,后续即使递增大于min后，递减按钮始终无效</p>
			<component :is="dom"></component>
			<p>vue中h函数加载方式，初始时v-model与max值相等,后续即使递减小于min后，递增按钮始终无效</p>
			<component :is="dom2"></component>
      <p>vue中h函数加载方式，初始时v-model不与max或min值相等,递增递减始终正常</p>
			<component :is="dom3"></component>
</template>
```

### What is Expected?

使用vue中h函数加载时使用效果与标签方式直接使用效果一致

### What is actually happening?

使用vue中h函数加载会因modelValue初始值产生不一致使用结果

### Additional comments

_(empty)_

**Comment by luozejian** [comment]
试一下这种方法看看可不可行？
Try this way and see if it works or not
const dom2 = ()=> h(ElInputNumber, {
						size: 'small',
						min: 1,
						step: 1,
						max: 4,
						modelValue: num2.value,
						'onUpdate:modelValue': (val) => {
							num2.value = val;
						},
					}, {});

**Comment by HostDay123** [comment]
> 试一下这种方法看看可不可行？ Try this way and see if it works or not `const dom2 = ()=> h(ElInputNumber, { size: 'small', min: 1, step: 1, max: 4, modelValue: num2.value, 'onUpdate:modelValue': (val) => { num2.value = val; }, }, {});`

非常感谢！！
以const dom = （）=>h( )方式可以有正确的效果，即使为边缘值时增减均正常反应。
