### ISSUE TITLE
[Component] [descriptions, descriptions-item] descriptions-item单独封装成组件后不显示

### ISSUE THREAD

**Issue by TheTimeMachine** [element-plus/element-plus#14666]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.1`
- Browser / OS: `Chrome 118.0.5993.118`
- Build Tool: `Vite`

### Related Component

- `el-descriptions`
- `el-descriptions-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1kZXNjcmlwdGlvbnMgdGl0bGU9XCJVc2VyIEluZm9cIj5cbiAgICA8Q29tcCAvPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlRlbGVwaG9uZVwiPjE4MTAwMDAwMDAwPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgPC9lbC1kZXNjcmlwdGlvbnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL0NvbXAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cclxuXHJcbjwvc2NyaXB0PlxyXG5cclxuPHRlbXBsYXRlPlxyXG4gIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlVzZXJuYW1lXCI+a29vcmlvb2thbWk8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxyXG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=)

### Steps to reproduce

将el-descriptions-item抽离成组件后无法显示了

### What is Expected?

能正常显示

### What is actually happening?

没有正常显示

### Additional comments

是不能这么使用吗？  还望大神们赐教

**Comment by btea** [comment]
This is not correct usage, the `el-description` component will filter the default slot content and only accept `ElDescriptionsItem` components.
https://github.com/element-plus/element-plus/blob/940b2648d3cec23a43623498a7274850ff8d0cb4/packages/components/descriptions/src/description.vue#L77-L80

**Comment by TheTimeMachine** [comment]
OK thank you so much!!!
