### ISSUE TITLE
[Docs] [dropdown] （只是一个疑问）大佬们，请问ElementPlus的源码里面，docs项目中怎么实现的安装的element-plus是从npm安装，而不是workspace？pnpm安装包不是会默认安装workspace中（如果有）的吗？ 

### ISSUE THREAD

**Issue by huangxu510** [element-plus/element-plus#14679]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.8`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgRHJvcGRvd24gTGlzdFxuICAgICAgPGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1yaWdodFwiPlxuICAgICAgICA8YXJyb3ctZG93biAvPlxuICAgICAgPC9lbC1pY29uPlxuICAgIDwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDM8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXZpZGVkPkFjdGlvbiA1PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgQXJyb3dEb3duIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtZHJvcGRvd24tbGluayB7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

进入页面，鼠标悬浮到 Drowdown List 上面，可以看到文字连着图标外有一圈border

### What is Expected?

没有border

### What is actually happening?

有border

### Additional comments

_(empty)_

**Comment by tolking** [comment]
same as #11662

**Comment by huangxu510** [comment]
> same as #11662

麻烦看一下标题，我这里只是在issue里面想问一下大佬们，ElementPlus的源码里面，docs项目中怎么实现的安装的element-plus是从npm安装，而不是workspace？pnpm安装包不是会默认安装workspace中（如果有）的吗？

求知道的大佬帮忙解答下，拜托🙏🏻🙏🏻🙏🏻

**Comment by tolking** [comment]
自己看看代码中的依赖写法不就行了

**Comment by huangxu510** [comment]
> 自己看看代码中的依赖写法不就行了

我看过了， docs 里面的依赖是  "element-plus": "npm:element-plus@latest"
我有两个疑问：
1. 这样的写法是通过命令如何安装的
2. 我拉下代码试了，自己在docs里面卸载掉element-plus，然后就是普通的命令pnpm add element-plus，安装的也是npm的版本，而不是workspace里面的，很好奇是怎么做到的，我在pnpm官网没有查到有哪个命令能够做到这个效果

我看了这块是由 三咲智子 大佬由yarn重构成pnpm的时候搞的，不知大佬清楚不

**Comment by huangxu510** [comment]
> > 自己看看代码中的依赖写法不就行了
> 
> 我看过了， docs 里面的依赖是 "element-plus": "npm:element-plus@latest" 我有两个疑问：
> 
> 1. 这样的写法是通过命令如何安装的
> 2. 我拉下代码试了，自己在docs里面卸载掉element-plus，然后就是普通的命令pnpm add element-plus，安装的也是npm的版本，而不是workspace里面的，很好奇是怎么做到的，我在pnpm官网没有查到有哪个命令能够做到这个效果
> 
> 我看了这块是由 三咲智子 大佬由yarn重构成pnpm的时候搞的，不知大佬清楚不

感觉是哪个配置文件控制了安装element-plus的来源，但是找不到是哪个🤣🤣🤣

**Comment by shilim-developer** [comment]
> > > 自己看看代码中的依赖写法不就行了
> > 
> > 
> > 我看过了， docs 里面的依赖是 "element-plus": "npm:element-plus@latest" 我有两个疑问：
> > 
> > 1. 这样的写法是通过命令如何安装的
> > 2. 我拉下代码试了，自己在docs里面卸载掉element-plus，然后就是普通的命令pnpm add element-plus，安装的也是npm的版本，而不是workspace里面的，很好奇是怎么做到的，我在pnpm官网没有查到有哪个命令能够做到这个效果
> > 
> > 我看了这块是由 三咲智子 大佬由yarn重构成pnpm的时候搞的，不知大佬清楚不
> 
> 感觉是哪个配置文件控制了安装element-plus的来源，但是找不到是哪个🤣🤣🤣

https://pnpm.io/zh/aliases
