### ISSUE TITLE
[Style] [select-v2] el-select-v2 使用height和item-height自定义otions高度时，在options小于170/34=5个的时候，自定义height不起作用

### ISSUE THREAD

**Issue by LuckyChengf** [element-plus/element-plus#14695]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.6`
- Element Plus Version: `2.4.1`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgIGZpbHRlcmFibGVcbiAgICByZW1vdGVcbiAgICA6cmVtb3RlLW1ldGhvZD1cInJlbW90ZU1ldGhvZFwiXG4gICAgY2xlYXJhYmxlXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6bG9hZGluZz1cImxvYWRpbmdcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGVudGVyIGEga2V5d29yZFwiXG4gICAgOmhlaWdodD1cIjMwMFwiXG4gICAgOml0ZW0taGVpZ2h0PVwiMTEwXCI+XG4gICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBpdGVtIH1cIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJveEggY3ItY2VudGVyIG10LTEwXCI+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cInRlYWNoZXItbmFtZSBtbC0xNVwiPnt7IGl0ZW0ubGFiZWwgfX08L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtc2VsZWN0LXYyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgc3RhdGVzID0gW1xuICAnQWxhYmFtYScsXG4gICdBbGFza2EnLFxuICAnQXJpem9uYScsXG4gICdBcmthbnNhcycsXG4gICdDYWxpZm9ybmlhJyxcbiAgJ0NvbG9yYWRvJyxcbiAgJ0Nvbm5lY3RpY3V0JyxcbiAgJ0RlbGF3YXJlJyxcbiAgJ0Zsb3JpZGEnLFxuICAnR2VvcmdpYScsXG4gICdIYXdhaWknLFxuICAnSWRhaG8nLFxuICAnSWxsaW5vaXMnLFxuICAnSW5kaWFuYScsXG4gICdJb3dhJyxcbiAgJ0thbnNhcycsXG4gICdLZW50dWNreScsXG4gICdMb3Vpc2lhbmEnLFxuICAnTWFpbmUnLFxuICAnTWFyeWxhbmQnLFxuICAnTWFzc2FjaHVzZXR0cycsXG4gICdNaWNoaWdhbicsXG4gICdNaW5uZXNvdGEnLFxuICAnTWlzc2lzc2lwcGknLFxuICAnTWlzc291cmknLFxuICAnTW9udGFuYScsXG4gICdOZWJyYXNrYScsXG4gICdOZXZhZGEnLFxuICAnTmV3IEhhbXBzaGlyZScsXG4gICdOZXcgSmVyc2V5JyxcbiAgJ05ldyBNZXhpY28nLFxuICAnTmV3IFlvcmsnLFxuICAnTm9ydGggQ2Fyb2xpbmEnLFxuICAnTm9ydGggRGFrb3RhJyxcbiAgJ09oaW8nLFxuICAnT2tsYWhvbWEnLFxuICAnT3JlZ29uJyxcbiAgJ1Blbm5zeWx2YW5pYScsXG4gICdSaG9kZSBJc2xhbmQnLFxuICAnU291dGggQ2Fyb2xpbmEnLFxuICAnU291dGggRGFrb3RhJyxcbiAgJ1Rlbm5lc3NlZScsXG4gICdUZXhhcycsXG4gICdVdGFoJyxcbiAgJ1Zlcm1vbnQnLFxuICAnVmlyZ2luaWEnLFxuICAnV2FzaGluZ3RvbicsXG4gICdXZXN0IFZpcmdpbmlhJyxcbiAgJ1dpc2NvbnNpbicsXG4gICdXeW9taW5nJyxcbl1cbmNvbnN0IGxpc3QgPSBzdGF0ZXMubWFwKChpdGVtKTogTGlzdEl0ZW0gPT4ge1xuICByZXR1cm4geyB2YWx1ZTogYHZhbHVlOiR7aXRlbX1gLCBsYWJlbDogYGxhYmVsOiR7aXRlbX1gIH1cbn0pXG5cbmludGVyZmFjZSBMaXN0SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xufVxuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWY8TGlzdEl0ZW1bXT4oW10pXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxuXG5jb25zdCByZW1vdGVNZXRob2QgPSAocXVlcnk6IHN0cmluZykgPT4ge1xuICBpZiAocXVlcnkgIT09ICcnKSB7XG4gICAgbG9hZGluZy52YWx1ZSA9IHRydWVcbiAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuICAgICAgb3B0aW9ucy52YWx1ZSA9IGxpc3QuZmlsdGVyKChpdGVtKSA9PiB7XG4gICAgICAgIHJldHVybiBpdGVtLmxhYmVsLnRvTG93ZXJDYXNlKCkuaW5jbHVkZXMocXVlcnkudG9Mb3dlckNhc2UoKSlcbiAgICAgIH0pXG4gICAgfSwgMjAwKVxuICB9IGVsc2Uge1xuICAgIG9wdGlvbnMudmFsdWUgPSBbXVxuICB9XG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

height="550"，item-height="110"时
在输入框输入al,搜索结果为3个，但是下拉框高度不符合预期，只有110

### What is Expected?

optios在<（height/item-height）时，下拉框高度为*item-height*options的数量
options在>=（height/item-height）时，下拉框高度为height

### What is actually happening?

optios在<（height/item-height）时，下拉框高度为item-height

### Additional comments

_(empty)_

**Comment by 5046312** [comment]
Select V2 失去焦点的时候，不会自动收起option

**Comment by litt1e-p** [comment]
in `packages/components/select-v2/src/useSelect.ts`:
```ts
const popupHeight = computed(() => {
    const totalHeight = filteredOptions.value.length * 34
    return totalHeight > props.height ? props.height : totalHeight
})
```
this `34` should be `props.itemHeight`, so this is a bug

**Comment by dxFlue** [comment]
mark and hope will fix this bug as soon as possible.

**Comment by dxFlue** [comment]
mark and hope to fix this bug as soon as quickly

**Comment by kooriookami** [comment]
This has been fixed.
