### ISSUE TITLE
[Component] [tabs] change activeName through code, can not trigger tab-change event

### ISSUE THREAD

**Issue by iizyd** [element-plus/element-plus#14697]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.1`
- Browser / OS: `Chrome 118.0.5993.117 / MacOS 13.6`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiBjbGFzcz1cImRlbW8tdGFic1wiIEB0YWItY2hhbmdlPVwib25UYWJDaGFuZ2VcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+VXNlcjwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiQ29uZmlnXCIgbmFtZT1cInNlY29uZFwiPkNvbmZpZzwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJycpXG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGFjdGl2ZU5hbWUudmFsdWUgPSAnZmlyc3QnXG4gIC8vIGNhbmB0IG5vdCB0cmlnZ2VyIHRhYiBjaGFuZ2VcblxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBhY3RpdmVOYW1lLnZhbHVlID0gJ3NlY29uZCdcbiAgfSwgMzAwMClcbn0pXG5cbmNvbnN0IG9uVGFiQ2hhbmdlID0gKHRhYjogc3RyaW5nKSA9PiB7XG4gY29uc29sZS5sb2codGFiKVxufVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <el-tabs v-model="activeName" class="demo-tabs" @tab-change="onTabChange">
    <el-tab-pane label="User" name="first">User</el-tab-pane>
    <el-tab-pane label="Config" name="second">Config</el-tab-pane>
  </el-tabs>
</template>
<script lang="ts" setup>
import { onMounted, ref } from 'vue'

const activeName = ref('')

onMounted(() => {
  activeName.value = 'first'
  // can`t not trigger tab change

  setTimeout(() => {
    activeName.value = 'second'
  }, 3000)
})

const onTabChange = (tab: string) => {
 console.log(tab)
}
```

### What is Expected?

Modifying the activename field through code can trigger the tab-change event.

### What is actually happening?

Modifying the activename field through code does not trigger the tab-change event.

### Additional comments

It was possible before version 2.4.0, but not after upgrading to version 2.4.0 and later.

**Comment by eivmosn** [comment]
You can use watch API. It looks like the onChange event only takes effect when clicked.
```javascript
watch(activeName, (tabName)=> {
  console.log(tabName)
})
```

**Comment by iizyd** [comment]
> You can use watch API. It looks like the onChange event only takes effect when clicked.
> 
> ```js
> watch(activeName, (tabName)=> {
>   console.log(tabName)
> })
> ```

I know this, but the performance of the version before 2.4.0 is inconsistent with the version after 2.4.0. Is this expected?

**Comment by CherishTheYouth** [comment]
@iizyd #14224 , program to be desigend not trigger tabChange function. you can see the issue #14224  for details.

**Comment by iizyd** [comment]
> @iizyd #14224 , program was desigend not trigger tabChange function. you can see the issue #14224 for details.

But the document says "triggers when activeName is changed"

[tabs event](https://element-plus.org/en-US/component/tabs.html#tabs-events)

**Comment by markthree** [comment]
I also think this is a bug, which is different from the description in the document. In the old version, it met the expectations

**Comment by LTAND** [comment]
I also think this is a bug. In version 2.3.0, I followed the documentation to address the issue in the project through tabChange. However, after upgrading to version 2.4.0, el-tab does not conform to the expected logic of version 2.3.0

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImhhbmRsZUNsaWNrKCdmaXJzdCcpXCI+Y2hhbmdlIGZpcnN0PC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiBAY2xpY2s9XCJoYW5kbGVDbGljaygnc2Vjb25kJylcIj5jaGFuZ2Ugc2Vjb25kPC9lbC1idXR0b24+XG5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiBjbGFzcz1cImRlbW8tdGFic1wiIEB0YWItY2hhbmdlPVwib25UYWJDaGFuZ2VcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJmaXJzdFwiIG5hbWU9XCJmaXJzdFwiPmZpcnN0PC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJzZWNvbmRcIiBuYW1lPVwic2Vjb25kXCI+c2Vjb25kPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignZmlyc3QnKVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuXG59KVxuY29uc3QgaGFuZGxlQ2xpY2sgPSAodGFiKT0+e1xuICBhY3RpdmVOYW1lLnZhbHVlID0gdGFiXG59XG5cbmNvbnN0IG9uVGFiQ2hhbmdlID0gKHRhYjogc3RyaW5nKSA9PiB7XG4gYWxlcnQoYG9uVGFiQ2hhbmdlOiAke3RhYn1gKVxufVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by CherishTheYouth** [comment]
@LTAND @markthree @iizyd Emm..., I will studied it carefully and try to solve it.
