### ISSUE TITLE
🎉 Welcome to Element Plus

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#147]
Element Plus - A Vue.js 3.0 UI library
------

## Core Updates

Element UI is an awesome Vue 2.x UI library.

However, in order to support Vue 3.0 with new syntax and great composition API, a  fully refactor and rewritten is needed.

[Element Plus](https://github.com/element-plus/element-plus/)  is the next generation of Element UI with full **Vue 3.0** composition API support. 

And it's rewritten in **TypeScript** with predictable static types. 

## Dependency Updates

The dependencies in the current project are slightly old, we managed to update them to the current stable version to get better performance and new features.

- @popperjs/core ^2.4.4 (replace old popperjs 1.x)
- dayjs ^1.8.33 (replace old fecha)
- async-validator ^3.4.0 (replace old async-validator 1.x)
- lodash ^4.17.20 (replace some old utils) **Note: only those have been used will be packaging into the bundle**

## Project Status

This project is still under heavy development. 

Feel free to join us and make your first pull request. 

If you like Element Plus, Give us a 💖 star 💖 to support us.

**Comment by HassanKrayem** [comment]
Wonderful Guys
Would The Next Generation Element UI Plus also work on VUe 2.x ?

**Comment by JeremyWuuuuu** [comment]
> Wonderful Guys
> Would The Next Generation Element UI Plus also work on VUe 2.x ?

Well, the answer is no, because we have made syntax changes to support Vue3 (setups and hooks), in this case `ElementPlus` won't be compatible to `Vue2` based application, but we will make sure component API remains the same as `V2`.

**Comment by microkof** [comment]
Is this a offical next version of Element UI? Why does the document seem to be counterfeit? Ex: https://element-plus.org/#/zh-CN/component/installation, Check Hello World's code.

**Comment by microkof** [comment]
> > Wonderful Guys
> > Would The Next Generation Element UI Plus also work on VUe 2.x ?
> 
> Well, the answer is no, because we have made syntax changes to support Vue3 (setups and hooks), in this case `ElementPlus` won't be compatible to `Vue2` based application, but we will make sure component API remains the same as `V2`.

Is this a offical next version of Element UI? Why does the document seem to be counterfeit? Ex: https://element-plus.org/#/zh-CN/component/installation, Check Hello World's code.

**Comment by zazzaz** [comment]
ref https://github.com/element-plus/element-plus/issues/171
