### ISSUE TITLE
[Feature Request] Provide an option to make the margin-right of the last el-space-item 0, or set it to 0 by default

### ISSUE THREAD

**Issue by zhenzhenChange** [element-plus/element-plus#1474]
### Existing Component
Yes

### Component Name
el-space

### Description
I think the spacing should be set only between these elements, and the last element is not required spacing, and some scenarios need to align the layout of the two ends of multiple lines, but the last element has set margin-right value, resulting in some visual distance contrast

**Comment by zhenzhenChange** [comment]
zh:

简单来说就是，`el-space-item` 的最后一项，默认不用设置间距，或者是否提供一个属性来控制最后一项是否需要设置间距

![el-space-item](https://s3.ax1x.com/2021/02/17/ygfEeP.png)

有些场景下做两端布局（多行），而某一行的使用了 `el-space`，最后一项的间距会有点突出，造成视觉效果不太友好

**Comment by JeremyWuuuuu** [comment]
We can, you interested in making a PR for this feature? If you do, add me in the reviewer list would be fine.

**Comment by zhenzhenChange** [comment]
I don't know if I can do it haha, I'll try it first and then reply to you

**Comment by zhenzhenChange** [comment]
Sorry, I've been so busy at work lately. I don't have time to do this `feat`, so I'll trouble you guys. (I think I saw someone else do it)
