### ISSUE TITLE
[Style] [select] el-select组件的下来弹窗的z-index层级问题

### ISSUE THREAD

**Issue by ET-WY** [element-plus/element-plus#14749]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.0`
- Browser / OS: `版本 119.0.6045.105（正式版本）/macOS14.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select.html#%E6%9C%89%E7%A6%81%E7%94%A8%E9%80%89%E9%A1%B9)

### Steps to reproduce

(1)点击下拉选择框，拖动滚动条，发现下拉弹窗始终保持在最上面

### What is Expected?

期望下拉弹窗与类似输入框层级保持一致

### What is actually happening?

期望下拉弹窗与类似输入框层级实际不一致，滚动到顶部的时候，会出现问题

### Additional comments

_(empty)_

<img width="426" alt="image" src="https://github.com/element-plus/element-plus/assets/149550114/326e6777-9e4c-464a-85bd-9ecb15e7482d">

**Comment by CherishTheYouth** [comment]
Could you provide a playground for reproduction? I can not actually understand what your mean, as I have not seen any exception in Docs.

**Comment by StormerZSha** [comment]
l got his means.when he click el-select then scroll the page,el-option would over the navbar and other things in doc.he want zIndex of el-option same as el-select.
l think this's not a issue of  el-select,since lt will be ok after change the zIndex of navbar
我明白他什么意思了，他在文档里点击了选择框然后滚动页面发现el-option盖在了导航栏和其他各种东西上面。他大概想要el-option和el-select层级相同。
我认为这不是el-select的问题，修改文档navbar的zIndex就可以了

**Comment by ET-WY** [comment]
> l got his means.when he click el-select then scroll the page,el-option would over the navbar and other things in doc.he want zIndex of el-option same as el-select. l think this's not a issue of el-select,since lt will be ok after change the zIndex of navbar 我明白他什么意思了，他在文档里点击了选择框然后滚动页面发现el-option盖在了导航栏和其他各种东西上面。他大概想要el-option和el-select层级相同。 我认为这不是el-select的问题，修改文档navbar的zIndex就可以了

Yes, thank you very much. This el-option may need a little optimization, otherwise we have to set the z-index of navbar every time

**Comment by kooriookami** [comment]
设置teleported为false试试
