### ISSUE TITLE
[Component] [date-picker] Clear event triggers "update:model-value" twice

### ISSUE THREAD

**Issue by Oleksii14** [element-plus/element-plus#14752]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.5`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24sIGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBzdGFydDogdW5kZWZpbmVkLFxuICBlbmQ6IHVuZGVmaW5lZCxcbn0pO1xuY29uc3QgcmFuZ2VWYWx1ZSA9IGNvbXB1dGVkPFtzdHJpbmcsIHN0cmluZ10gfCB1bmRlZmluZWQ+KCgpID0+IHtcbiAgaWYgKGZvcm0uc3RhcnQgJiYgZm9ybS5lbmQpIHtcbiAgICByZXR1cm4gW2Zvcm0uc3RhcnQsIGZvcm0uZW5kXVxuICB9XG5cbiAgcmV0dXJuIHVuZGVmaW5lZDtcbn0pXG5cbmNvbnN0IHNldERhdGVWYWx1ZSA9IChyYW5nZT86IFtzdHJpbmcsIHN0cmluZ10pID0+IHtcbiAgY29uc29sZS5sb2cocmFuZ2UpO1xuICBjb25zdCBbc3RhcnQsIGVuZF0gPSByYW5nZSA/PyBbXTtcbiAgZm9ybS5zdGFydCA9IHN0YXJ0O1xuICBmb3JtLmVuZCA9IGVuZDtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgOm1vZGVsLXZhbHVlPVwicmFuZ2VWYWx1ZVwiXG4gICAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgICBlbmQtcGxhY2Vob2xkZXI9XCJFbmQgZGF0ZVwiXG4gICAgICBjbGVhcmFibGVcbiAgICAgIHZhbHVlLWZvcm1hdD1cIllZWVktTU0tRERUSEg6bW06c3Muc3NzWlwiXG4gICAgICBAdXBkYXRlOm1vZGVsLXZhbHVlPVwic2V0RGF0ZVZhbHVlXCJcbiAgICAvPlxuICAgIFxuICBcbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

- visit the reproduction example link
- choose a date range
- click "clear" button
- see console

### What is Expected?

On clear, the update:model-value is called once

### What is actually happening?

When clearing date picker, update:model-value event is triggered twice

### Additional comments

_(empty)_

<img width="613" alt="image" src="https://github.com/element-plus/element-plus/assets/36737084/c0a8439b-b89a-4768-9de3-1270e5e5b2ce">

**Comment by CherishTheYouth** [comment]
I have prepared a pr for that bug.

**Comment by 178320805** [comment]
I found that the method emitInput (null) was also executed at the deletion point, which is where you mentioned the update trigger. When checking the data, this method is also triggered

**Comment by Oleksii14** [comment]
@CherishTheYouth could you check @178320805 comment as well?

**Comment by CherishTheYouth** [comment]
> @CherishTheYouth could you check @178320805 comment as well?
Sorry ，I could not understand what you mean ，my pr just for this issue, if some situation else , could you give codes or playground ，I will optimize my pr！😊😊😊

**Comment by CherishTheYouth** [comment]
> I found that the method emitInput (null) was also executed at the deletion point, which is where you mentioned the update trigger. When checking the data, this method is also triggered

Or Could you describe it in Chinese ，my English poor 😂😂😂😂

**Comment by CherishTheYouth** [comment]
> > @CherishTheYouth could you check @178320805 comment as well?
> > Sorry ，I could not understand what you mean ，my pr just for this issue, if some situation else , could you give codes or playground ，I will optimize my pr！😊😊😊

I have checked it last night, it runs well. Clear event triggers "update:model-value" once.

**Comment by jue** [comment]
> @Oleksii14 I have checked it last night, it runs well. Clear event triggers "update:model-value" once.

When the input is focused, the calendar expands. Clicking the clear icon at this point triggers the action twice.
