### ISSUE TITLE
[Bug Report] yarn website-dev  : Failed to compile.

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#1476]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen

### Steps to reproduce
git clone
yarn
yarn website-dev  

### What is Expected?
website can run

### What is actually happening?
```
ERROR in ./packages/element-plus/index.ts
Module not found: Error: Can't resolve './version' in '/xxx/packages/element-plus'
ℹ ｢wdm｣: Failed to compile.
```

**Comment by BeADre** [comment]
You need to run command `yarn gen:version` for that.

**Comment by XingXiaoWu** [comment]
> You need to run command `yarn gen:version` for that.

thx, I look so stupid😂😂
