### ISSUE TITLE
[Component] [tree-select] el-tree-select 干净的组件出现警告runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-emits event listeners (updateOptions) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 

### ISSUE THREAD

**Issue by time202051** [element-plus/element-plus#14778]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-beta.2`
- Element Plus Version: `2.3.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-htxxgz?file=/src/App.vue)

### Steps to reproduce

runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-emits event listeners (updateOptions) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 

### What is Expected?

解决报错

### What is actually happening?

解决报错

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlVlwiIDpkYXRhPVwiZGF0YVwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuXG48c2NyaXB0PlxuaW1wb3J0IHsgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuZXhwb3J0IGRlZmF1bHQge1xuICBzZXR1cCgpIHtcbiAgICBjb25zdCB2YWx1ZVYgPSByZWYoKTtcbiAgICBjb25zdCBkYXRhID0gcmVmKFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IFwiMVwiLFxuICAgICAgICBsYWJlbDogXCJMZXZlbCBvbmUgMVwiLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiBcIjEtMVwiLFxuICAgICAgICAgICAgbGFiZWw6IFwiTGV2ZWwgdHdvIDEtMVwiLFxuICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIHZhbHVlOiBcIjEtMS0xXCIsXG4gICAgICAgICAgICAgICAgbGFiZWw6IFwiTGV2ZWwgdGhyZWUgMS0xLTFcIixcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiBcIjJcIixcbiAgICAgICAgbGFiZWw6IFwiTGV2ZWwgb25lIDJcIixcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogXCIyLTFcIixcbiAgICAgICAgICAgIGxhYmVsOiBcIkxldmVsIHR3byAyLTFcIixcbiAgICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICB2YWx1ZTogXCIyLTEtMVwiLFxuICAgICAgICAgICAgICAgIGxhYmVsOiBcIkxldmVsIHRocmVlIDItMS0xXCIsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBdLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6IFwiMi0yXCIsXG4gICAgICAgICAgICBsYWJlbDogXCJMZXZlbCB0d28gMi0yXCIsXG4gICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgdmFsdWU6IFwiMi0yLTFcIixcbiAgICAgICAgICAgICAgICBsYWJlbDogXCJMZXZlbCB0aHJlZSAyLTItMVwiLFxuICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgXSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IFwiM1wiLFxuICAgICAgICBsYWJlbDogXCJMZXZlbCBvbmUgM1wiLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiBcIjMtMVwiLFxuICAgICAgICAgICAgbGFiZWw6IFwiTGV2ZWwgdHdvIDMtMVwiLFxuICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIHZhbHVlOiBcIjMtMS0xXCIsXG4gICAgICAgICAgICAgICAgbGFiZWw6IFwiTGV2ZWwgdGhyZWUgMy0xLTFcIixcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogXCIzLTJcIixcbiAgICAgICAgICAgIGxhYmVsOiBcIkxldmVsIHR3byAzLTJcIixcbiAgICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICB2YWx1ZTogXCIzLTItMVwiLFxuICAgICAgICAgICAgICAgIGxhYmVsOiBcIkxldmVsIHRocmVlIDMtMi0xXCIsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBdLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0pO1xuICAgIHJldHVybiB7XG4gICAgICB2YWx1ZVYsXG4gICAgICBkYXRhLFxuICAgIH07XG4gIH0sXG59O1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)
请提供可复现demo，如果是codesandbox中的版本尝试升级到最新版本。

**Comment by baiyuze** [comment]
我也遇到了

**Comment by baiyuze** [comment]
需要用jsx语法，使用这个el-select

**Comment by time202051** [comment]
我是直接在模版上渲染el-tree-select的，报这个错&nbsp;


李嘉鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [tree-select] el-tree-select 干净的组件出现警告runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-emits event listeners (updateOptions) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the &quot;emits&quot; option.  (Issue #14778)





 
需要用jsx语法，使用这个el-select

**Comment by baiyuze** [comment]
我查到问题了，从2.2.36版本开始就会有这个报错

**Comment by baiyuze** [comment]
如果不要错误的话，极限版本2.2.32，还你一个清爽的控制台

**Comment by baiyuze** [comment]
> 我是直接在模版上渲染el-tree-select的，报这个错&nbsp; 李嘉鹏 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年1月3日(星期三) 下午5:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [element-plus/element-plus] [Component] [tree-select] el-tree-select 干净的组件出现警告runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-emits event listeners (updateOptions) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the &quot;emits&quot; option. (Issue #14778) 需要用jsx语法，使用这个el-select — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你可以测试一下，我现在没了警告，一下子舒服了，耽误我3小时查这个问题....

**Comment by time202051** [comment]
公司版本已经2.3.9了，应该多处用了新版本组件。版本回不去了&nbsp;


李嘉鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [tree-select] el-tree-select 干净的组件出现警告runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-emits event listeners (updateOptions) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the &quot;emits&quot; option.  (Issue #14778)





 
如果不要错误的话，极限版本2.2.32，还你一个清爽的控制台

**Comment by baiyuze** [comment]
没戏了，我试了最高版本的组件也是会报这个问题

**Comment by baiyuze** [comment]
除非他们能修复这个问题，主要是基于el-select组件的emits没有传递updateOptions，仍然进行了调用，或者你可以提个MR给他们合并试试？

**Comment by kooriookami** [comment]
updateOptions这个emit我在重构中删除了，应该之后就没问题了

**Comment by baiyuze** [comment]
@kooriookami 高版本的vue不会出现在这个问题，但是低版本的vue比如3.2.31仍然会报错options.updateOptions，为什么不对全系列的vue版本做支持？
而且貌似只有这个组件会有这个问题。

**Comment by baiyuze** [comment]
![image](https://github.com/element-plus/element-plus/assets/27543832/9fef9107-2b8a-408c-a6f1-a97ad2d6435e)
这里也没说，不能用vue@3.2.31

**Comment by baiyuze** [comment]
![image](https://github.com/element-plus/element-plus/assets/27543832/5d8e3121-c49e-4ad9-ac31-25eb5420aa91)

**Comment by kooriookami** [comment]
> @kooriookami 高版本的vue不会出现在这个问题，但是低版本的vue比如3.2.31仍然会报错options.updateOptions，为什么不对全系列的vue版本做支持？ 而且貌似只有这个组件会有这个问题。

并没有使用 vue 某个特定版本的特性，低版本报错可能触发了 vue 的 bug，在高版本中修复了这个问题。

**Comment by baiyuze** [comment]
@kooriookami 
![image](https://github.com/element-plus/element-plus/assets/27543832/f7594757-15f1-4b12-85cf-93cc364768c7)
![image](https://github.com/element-plus/element-plus/assets/27543832/946af12a-a555-4292-a732-2023d6f984ad)
如果是vue的bug或者编译器的问题，能否加上改update属性，校验通过再调用？

**Comment by baiyuze** [comment]
![image](https://github.com/element-plus/element-plus/assets/27543832/18a11002-89a6-4c6b-9eb6-0c20822f73a2)

**Comment by baiyuze** [comment]
![image](https://github.com/element-plus/element-plus/assets/27543832/9bd3e98f-f545-4442-a650-5f6c7256daa3)
kan'qi'l看起来并没有完全代理

**Comment by kooriookami** [comment]
可以的，一会我提一个pr

**Comment by baiyuze** [comment]
> 可以的，一会我提一个pr

如果判定optionUpdate是否存在来做兼容。
![image](https://github.com/element-plus/element-plus/assets/27543832/c221cf10-5d36-4bb0-9d43-1a7642850477)
那么这块逻辑不执行，会对整体组件造成什么影响吗？

**Comment by baiyuze** [comment]
> > 可以的，一会我提一个pr
> 
> 如果判定optionUpdate是否存在来做兼容。 ![image](https://private-user-images.githubusercontent.com/27543832/316463339-c221cf10-5d36-4bb0-9d43-1a7642850477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjE2MzcsIm5iZiI6MTcxMTM2MTMzNywicGF0aCI6Ii8yNzU0MzgzMi8zMTY0NjMzMzktYzIyMWNmMTAtNWQzNi00YmIwLTlkNDMtMWE3NjQyODUwNDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwMDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MWZhZmIyYjA5ZDFlOTIxZGQwOWI2Y2E0MzVhM2E1MGE3MTEwMzNiNDc1YTI3ZThlMTU0YjEwMmM5YTBjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.26vd16AmkChvgXPPx48_PqUwSQRdD5XJbtHb4qLU2Yk) 那么这块逻辑不执行，会对整体组件造成什么影响吗？

看起来是个显隐状态

**Comment by kooriookami** [comment]
> > > 可以的，一会我提一个pr
> > 
> > 
> > 如果判定optionUpdate是否存在来做兼容。 ![image](https://private-user-images.githubusercontent.com/27543832/316463339-c221cf10-5d36-4bb0-9d43-1a7642850477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjE2MzcsIm5iZiI6MTcxMTM2MTMzNywicGF0aCI6Ii8yNzU0MzgzMi8zMTY0NjMzMzktYzIyMWNmMTAtNWQzNi00YmIwLTlkNDMtMWE3NjQyODUwNDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwMDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MWZhZmIyYjA5ZDFlOTIxZGQwOWI2Y2E0MzVhM2E1MGE3MTEwMzNiNDc1YTI3ZThlMTU0YjEwMmM5YTBjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.26vd16AmkChvgXPPx48_PqUwSQRdD5XJbtHb4qLU2Yk) 那么这块逻辑不执行，会对整体组件造成什么影响吗？
> 
> 看起来是个显隐状态

会执行的，低版本的 vue 在初始化之后在实例中加入了 updateOption 等属性，而新版本的 vue 是同步添加的。
