### ISSUE TITLE
[Feature Request]  [Suggest] Provide separate @types file

### ISSUE THREAD

**Issue by Asyoulikeme** [element-plus/element-plus#1477]
### Existing Component
No

### Component Name
element-plus@latest

### Description
mac 10.15.7
google latest

## Compositon Api
```js
import { ElLoading,ILoadingInstance } from "element-plus"

export const useLoadingHook = () => {
    const loadingInstance:ILoadingInstance | null = null

    function startLoading(text?:string){
        ElLoading.service({
            lock: true,
            text: text || '拼命加载中',
            spinner: 'el-icon-loading',
            background: 'rgba(0, 0, 0, 0.7)'
        });
    }

    function closeLoading(){
       loadingInstance && (loadingInstance as ILoadingInstance).close()
    }


    return {
        startLoading,
        closeLoading
    }
}
```
## idea told me ：
> 
>Module '"../../node_modules/element-plus/lib"' has no exported member 'ILoadingInstance'. Did you mean to use 'import ILoadingInstance from "../../node_modules/element-plus/lib"' instead?
>

what does the "../../node_modules" is ？，I think it well take effect，but it's too long .....

I see on the vue/vite project package.json file：
like vite ："types": "link:./packages/vite/types",
like vue ："types": "dist/vue.d.ts",

maybe the best way is this？

thanks! 如果没看懂我的意思，那就是我英语不好😅

**Comment by Asyoulikeme** [comment]
### Actually  
> import ILoadingInstance from "../../node_modules/element-plus/lib" ❌ It doesn't work
> import { ILoadingInstance } from "../../node_modules/element-plus/lib/el-loading/src/loading.type" ✅

**Comment by JeremyWuuuuu** [comment]
I think we currently do suffer from the release files structuring issue, sometimes users need. We will make effort on this in the coming versions. Especially with `Vite`

**Comment by Asyoulikeme** [comment]
> I think we currently do suffer from the release files structuring issue, sometimes users need. We will make effort on this in the coming versions. Especially with `Vite`

thanks!!!

**Comment by tolking** [comment]
@Asyoulikeme `types ` same as `typings`. The problem is many types are not export correctly.

@JeremyWuuuuu Are there plans to export types from the main portal? (It would be better if the `utils` and `hooks` could be export at the same time.)

**Comment by sxzz** [comment]
We have exported the props, emits, and types of some components.

```ts
import { buttonProps, ButtonProps } from 'element-plus`
```

Let's track this issue #2040
