### ISSUE TITLE
[Component] [infinite-scroll] 当 v-infinite-scroll 释放的时候, SCOPE 不存在导致的错误

### ISSUE THREAD

**Issue by nianwu** [element-plus/element-plus#14775]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-infinite-scroll`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/HEAD/packages/components/infinite-scroll/src/index.ts#L165)

### Steps to reproduce

1. 页面使用 vue-router 进行切换
2. v-infinite-scroll 指令加在 el-collapse 组件之上
3. el-collapse 在 el-scrollbar 之内
4. 通过路由切换, 第一次离开该页面没有问题
5. 回到该页面
6. 再次通过 router 离开该页面, 则出现以下错误

```text
Uncaught (in promise) TypeError: Cannot destructure property 'container' of 'el[SCOPE9]' as it is undefined.
    at unmounted (index.ts:112:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:1914:7)
    at Array.<anonymous> (runtime-core.esm-bundler.js:6232:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:40)
    at flushJobs (runtime-core.esm-bundler.js:363:5)
```

[链接](https://github.com/element-plus/element-plus/blob/HEAD/packages/components/infinite-scroll/src/index.ts#L165)

经过检查, 发现源码中存在如下代码 

```js
  unmounted(el) {
    const { container, onScroll } = el[SCOPE]

    container?.removeEventListener('scroll', onScroll)
    destroyObserver(el)
  },
```

代码中存在 contaienr 不存在的 情况, 此时使用结构 (即错误中的 destructure ) 必然出错

应该将上述代码改为 
```js
  unmounted(el) {
    const container = el[SCOPE].container
    const onScroll = el[SCOPE].onScroll

    container?.removeEventListener('scroll', onScroll)
    destroyObserver(el)
  },
```

由于时间有限,暂时无法复现该问题, 但是使用此方法大概率可以修复该问题

### What is Expected?

修复该问题

### What is actually happening?

修复该问题

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这个无法解决问题哦，报错信息上已经说明了是 el[SCOPE] 未定义， 所以应该是对el[SCOPE]进行判断，而不是去调整解构。

**Comment by nianwu** [comment]
恩恩  是这样的，我看错了

**Comment by nianwu** [comment]
@chenxch 我的 pull request 可能是我点错导致关闭了, 需要怎么能重新打开？

**Comment by chenxch** [comment]
@nianwu 已经reopen了，标题记得也改一下哦
