### ISSUE TITLE
[Component] [watermark] 在360极速浏览器32位版本下 文字水印不显示

### ISSUE THREAD

**Issue by MuXiTong** [element-plus/element-plus#14807]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.4.2`
- Browser / OS: `360极速浏览器32位版本`
- Build Tool: `Vue CLI`

### Related Component

- `el-watermark`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/watermark.html)

### Steps to reproduce

在360极速浏览器32位版本里打开 https://element-plus.org/zh-CN/component/watermark.html 

### What is Expected?

显示文字水印

### What is actually happening?

文字水印不显示

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
能否先看下控制台是否有报错信息

**Comment by MuXiTong** [comment]
> 能否先看下控制台是否有报错信息

![image](https://github.com/element-plus/element-plus/assets/20792388/164d5f21-f505-447f-a1f8-3bb86e7b4411)
查看控制台时 有个样式 background-size 的值计算错误，还有生成的base64图片是空白的
