### ISSUE TITLE
[Bug Report] Partial document missing or error

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#1481]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen

### Steps to reproduce
none

### What is Expected?
Document is complete

### What is actually happening?
Partial document missing or error

Sorry, my English isn't good, so I need to speak Chinese.

我在把文档站的示例代码修改为使用setup方法的时候 https://github.com/element-plus/element-plus/pull/1480 ，发现了一些文档的缺失或错误，但我对改动和其他语言不是很了解，只能列出我发现的问题。

1.drawer组件：

自定义内容-打开嵌套 Form 的 Drawer-closeDrawer-方法错误

[链接](https://element-plus.gitee.io/#/zh-CN/component/drawer#zi-ding-yi-nei-rong)

2. Slider文档出现警告
```
Invalid prop: custom validator check failed for prop "modelValue". 
```
[链接](https://element-plus.gitee.io/#/zh-CN/component/slider)

3. Table文档，es语言下应该少了一些说明
4. transfer文档，es-us语言下缺失挺多的
5. tree文档，es-us和jp 至少缺少自定义节点的文档

**Comment by psalcedodev** [comment]
Hi, when trying to use el-input-number inside a table, I get the following error
```Invalid prop: custom validator check failed for prop "modelValue".```
```at <ElInputNumber size="mini" value="1" modelValue="1"  ... > ```

Here is some code to be more precise

```
<el-table
    max-height="500"
    :data="categories.filter(data => !search || data.name.toLowerCase().includes(search.    toLowerCase()))"
    style="width: 100%">
    <el-table-column
    label="Nombre"
    prop="name">
    </el-table-column>
    <el-table-column
    label="Slider titulo"
    prop="title">
    </el-table-column>

    <el-table-column
        prop="order"
        label="Orden">
            <template #default="scope">
                <div class="numberinput tw-m-auto" >
                <el-input-number size="mini" :value="scope.row.order" v-model="scope.row.order"     :min="1" @change="changeOrder(scope.row)"></el-input-number>
                </div>
        </template>
    </el-table-column>
    <el-table-column
    align="right">
    <template #header>
        <el-input
        v-model="search"
        size="mini"
        placeholder="Type to search"/>
    </template>
    <template #default="scope">
        <a :href="route('admin.categories.show', scope.row.id) " class="tw-mx-2"><el-button
        size="mini"
        >Editar</el-button></a>
        <el-button
        @click="deleteCategory(scope.row)"
        size="mini"
        type="danger"
        >Borrar</el-button>
    </template>
    </el-table-column>
</el-table>
```

I hope you guys could help me solve this issue, thank you!

**Comment by XingXiaoWu** [comment]
> custom validator check failed for prop "modelValue"

maybe u can open a new issue and provide a repeatable link to track the problem

**Comment by XingXiaoWu** [comment]
> Hi, when trying to use el-input-number inside a table, I get the following error
> `Invalid prop: custom validator check failed for prop "modelValue".`
> `at <ElInputNumber size="mini" value="1" modelValue="1" ... > `
> 
> Here is some code to be more precise
> 
> ```
> <el-table
>     max-height="500"
>     :data="categories.filter(data => !search || data.name.toLowerCase().includes(search.    toLowerCase()))"
>     style="width: 100%">
>     <el-table-column
>     label="Nombre"
>     prop="name">
>     </el-table-column>
>     <el-table-column
>     label="Slider titulo"
>     prop="title">
>     </el-table-column>
> 
>     <el-table-column
>         prop="order"
>         label="Orden">
>             <template #default="scope">
>                 <div class="numberinput tw-m-auto" >
>                 <el-input-number size="mini" :value="scope.row.order" v-model="scope.row.order"     :min="1" @change="changeOrder(scope.row)"></el-input-number>
>                 </div>
>         </template>
>     </el-table-column>
>     <el-table-column
>     align="right">
>     <template #header>
>         <el-input
>         v-model="search"
>         size="mini"
>         placeholder="Type to search"/>
>     </template>
>     <template #default="scope">
>         <a :href="route('admin.categories.show', scope.row.id) " class="tw-mx-2"><el-button
>         size="mini"
>         >Editar</el-button></a>
>         <el-button
>         @click="deleteCategory(scope.row)"
>         size="mini"
>         type="danger"
>         >Borrar</el-button>
>     </template>
>     </el-table-column>
> </el-table>
> ```
> 
> I hope you guys could help me solve this issue, thank you!

https://github.com/element-plus/element-plus/blob/0cac0bda3827ad00c9f5d5699dd0a8297dc33c85/packages/input-number/src/index.vue#L104

it's check the type, I don't know your `scope.row.order` type, maybe you can look at it

**Comment by XingXiaoWu** [comment]
> Hi, when trying to use el-input-number inside a table, I get the following error
> `Invalid prop: custom validator check failed for prop "modelValue".`
> `at <ElInputNumber size="mini" value="1" modelValue="1" ... > `
> 
> Here is some code to be more precise
> 
> ```
> <el-table
>     max-height="500"
>     :data="categories.filter(data => !search || data.name.toLowerCase().includes(search.    toLowerCase()))"
>     style="width: 100%">
>     <el-table-column
>     label="Nombre"
>     prop="name">
>     </el-table-column>
>     <el-table-column
>     label="Slider titulo"
>     prop="title">
>     </el-table-column>
> 
>     <el-table-column
>         prop="order"
>         label="Orden">
>             <template #default="scope">
>                 <div class="numberinput tw-m-auto" >
>                 <el-input-number size="mini" :value="scope.row.order" v-model="scope.row.order"     :min="1" @change="changeOrder(scope.row)"></el-input-number>
>                 </div>
>         </template>
>     </el-table-column>
>     <el-table-column
>     align="right">
>     <template #header>
>         <el-input
>         v-model="search"
>         size="mini"
>         placeholder="Type to search"/>
>     </template>
>     <template #default="scope">
>         <a :href="route('admin.categories.show', scope.row.id) " class="tw-mx-2"><el-button
>         size="mini"
>         >Editar</el-button></a>
>         <el-button
>         @click="deleteCategory(scope.row)"
>         size="mini"
>         type="danger"
>         >Borrar</el-button>
>     </template>
>     </el-table-column>
> </el-table>
> ```
> 
> I hope you guys could help me solve this issue, thank you!

https://github.com/element-plus/element-plus/blob/0cac0bda3827ad00c9f5d5699dd0a8297dc33c85/packages/input-number/src/index.vue#L104

it's check the type, I don't know your `scope.row.order` type, maybe you can look at it
