### ISSUE TITLE
[Docs] 官网文档无法通过搜索栏搜出watermark组件

### ISSUE THREAD

**Issue by sleepyShen1989** [element-plus/element-plus#14825]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/en-US/)

### Steps to reproduce

进入官网，点击Search栏，输入watermark

### What is Expected?

通过Search栏搜索出watermark组件

### What is actually happening?

无法通过Search栏搜索出watermark组件

### Additional comments

_(empty)_

**Comment by CherishTheYouth** [comment]
It seems that something wrong in algolia's crawler.
