### ISSUE TITLE
[Component] [select, popover] 当trigger为hover的el-popover 与 带有 filterable 的el-select 同时存在；选中el-select后，点击hover出现的popover中的某个内容再移出会触发el-select的下拉

### ISSUE THREAD

**Issue by nightost** [element-plus/element-plus#14829]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.2`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJ0b3Atc3RhcnRcIlxuICAgIHRpdGxlPVwiVGl0bGVcIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImhvdmVyXCJcbiAgICBjb250ZW50PVwidGhpcyBpcyBjb250ZW50LCB0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudFwiXG4gID5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJtLTJcIj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwiYVwiIGZpbHRlcmFibGU+PGVsLW9wdGlvbiBsYWJlbD1cInRlc3RcIiB2YWx1ZT1cIjFcIj48L2VsLW9wdGlvbj48ZWwtb3B0aW9uIGxhYmVsPVwidGVzdDJcIiB2YWx1ZT1cIjJcIj48L2VsLW9wdGlvbj48L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBhID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtYnV0dG9uICsgLmVsLWJ1dHRvbiB7XG4gIG1hcmdpbi1sZWZ0OiA4cHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击下拉选中option
2. hover 到左侧按钮，点击popover中的内容
3. 鼠标移出popover
4. 右侧下拉依旧打开

### What is Expected?

点击popover后，elselect 应该失去焦点，且不应重新打开

### What is actually happening?

点击popover后，elselect 没有失去焦点，且重新打开

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
自动弹出的问题我修复了，焦点的问题你换成原生input也是一样的
