### ISSUE TITLE
[Bug Report] Element Theme does not generate stylesheet for ElAffix

### ISSUE THREAD

**Issue by guihig** [element-plus/element-plus#1482]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Manjaro / Firefox 85.0.1 (64-bit)

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/

### Steps to reproduce
Follow the steps in https://element-plus.org/#/en-US/component/custom-theme#cli-theme-tool

### What is Expected?
The CLI to generate stylesheets for every component in Element Plus

### What is actually happening?
When following the steps in https://element-plus.org/#/en-US/component/custom-theme, the final build for element-theme does not generate the affix.css. 

I'm openning this issue here because the element-theme-chalk repository don't have an issue board.

**Comment by JeremyWuuuuu** [comment]
Right now `custom-theme` is not available since we did not implement the backend functionalities for `ElementPlus`, this might take time.
