### ISSUE TITLE
[Bug Report] can't import Eltablecolumn

### ISSUE THREAD

**Issue by hhb1994** [element-plus/element-plus#1484]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
macOS 11

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/hhb1994/pen/QWGgwjx

### Steps to reproduce
open https://codepen.io/hhb1994/pen/QWGgwjx to see

### What is Expected?
 导入  eltablecolumn

### What is actually happening?
 在 vue3.05(使用了  typescript) 项目中导入 table, 在按需加载 eltablecolumns 时(app.use(ElTableColumn))时报错:
 Argument of type 'DefineComponent<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, void, unknown, {}, {}, ComponentOptionsMixin, ... 5 more ..., {} | { ...; }>' is not assignable to parameter of type 'Plugin_2'.
  Property 'install' is missing in type 'ComponentPublicInstanceConstructor<({ $: ComponentInternalInstance; $data: {}; $props: (Partial<{}> & Pick<(Readonly<{ [x: number]: string; } & { length?: number | undefined; toString?: string | undefined; ... 20 more ...; flat?: unknown[] | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps) ...' but required in type '{ install: PluginInstallFunction; }'.

**Comment by hhb1994** [comment]
solved

edit  `node_modules/element-plus/lib/el-table-column/index.t.ts`

```ts
import TableColumn from '../el-table/src/tableColumn';
export default TableColumn;
```

```ts
 
import type { SFCWithInstall } from '../utils/types';
import tableColumn from "./src/tableColumn.vue"
declare const _TableColumn: SFCWithInstall<typeof tableColumn>
export default _TableColumn
```

**Comment by yanyang1116** [comment]
Looking forward to the next version to fix this problem. @element-bot
