### ISSUE TITLE
[Component] [input] el-form el-input 自定义校验规则不生效

### ISSUE THREAD

**Issue by xubaobao19940428** [element-plus/element-plus#14850]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.1`
- Browser / OS: `mac/chrome119.0.6045.159`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/johnqian/kfb3481c/9/)

### Steps to reproduce

先用中文输入法在电话那一行随便输入然后点击 输入法的第一个文字，当第一个输入的文字显示在el-input上时再清空，再去输入数字，这个时候el-input的value 就保留在上一次输入的值了
无法更新

### What is Expected?

希望可以更新

### What is actually happening?

无法更新

### Additional comments

_(empty)_

**Comment by xubaobao19940428** [comment]
复现步骤
![image](https://github.com/element-plus/element-plus/assets/39545419/fb498583-fd1f-4e98-a73b-41aa21b09141)


![image](https://github.com/element-plus/element-plus/assets/39545419/3225ab8e-8933-4a93-bfa4-7225cafadb61)


![image](https://github.com/element-plus/element-plus/assets/39545419/8be718f7-5895-4750-a938-1348d7daeaaa)

**Comment by liqiangsky** [comment]
> 复现步骤 ![image](https://user-images.githubusercontent.com/39545419/283382975-fb498583-fd1f-4e98-a73b-41aa21b09141.png)
> 
> ![image](https://user-images.githubusercontent.com/39545419/283382894-3225ab8e-8933-4a93-bfa4-7225cafadb61.png)
> 
> ![image](https://user-images.githubusercontent.com/39545419/283382750-8be718f7-5895-4750-a938-1348d7daeaaa.png)

![屏幕截图 2023-11-18 233947](https://github.com/element-plus/element-plus/assets/74276685/e1d31824-8c0b-47a4-a79d-635a6729eec3)
改成这样就可以了

**Comment by liqiangsky** [comment]
> 复现步骤 ![image](https://user-images.githubusercontent.com/39545419/283382975-fb498583-fd1f-4e98-a73b-41aa21b09141.png)
> 
> ![image](https://user-images.githubusercontent.com/39545419/283382894-3225ab8e-8933-4a93-bfa4-7225cafadb61.png)
> 
> ![image](https://user-images.githubusercontent.com/39545419/283382750-8be718f7-5895-4750-a938-1348d7daeaaa.png)

两个问题
1.你的校验方法在粘贴demo时是不是放错了位置
![屏幕截图 2023-11-18 234324](https://github.com/element-plus/element-plus/assets/74276685/41d58108-6a89-4b71-a7b9-1fd6234c55fd)
2.将onkeyup的处理改成 onkeyup="() => item.phoneNumber = item.phoneNumber.replace(/[^\d]/g,'')"
![屏幕截图 2023-11-18 234240](https://github.com/element-plus/element-plus/assets/74276685/05d15d00-bc83-4c56-9dd3-4546a9babc47)
上述问题改完后正常校验

**Comment by xubaobao19940428** [comment]
好的，感谢，没有放错位置，我是通过方法传给子组件的
