### ISSUE TITLE
### Drawer

### ISSUE THREAD

**Issue by luxueyan** [element-plus/element-plus#149]
https://github.com/element-plus/element-plus/projects/1#card-42276200
只能复制 没有权限convert

**Comment by JeremyWuuuuu** [comment]
I believe this one is depend on #144 , can you dig into it before coding?

**Comment by luxueyan** [comment]
Sorry for continually disturbing you！But I just checked the old element-ui(2.13.2) ，the drawer component dose not depend on the Dialog component. It only depend on a css class 'el-dialog__close'. Is there some change?

**Comment by JeremyWuuuuu** [comment]
Nope, just checked it out, it only depends on `PopupManager`. You can go ahead doing it

**Comment by JeremyWuuuuu** [comment]
Duplicated with #150
