### ISSUE TITLE
[Component] [date-picker] <el-date-picker> 当type="monthrange" 时，编辑功能有问题，方法报错无法切换

### ISSUE THREAD

**Issue by lfcod** [element-plus/element-plus#14905]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-alpha.1`
- Element Plus Version: `2.4.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

选择月份区间，鼠标编辑输入，失去标点后，控制台报错，值未修改

### What is Expected?

可编辑切换

### What is actually happening?

编辑未切换

### Additional comments

_(empty)_

**Comment by CherishTheYouth** [comment]
Oh, something wrong really occurs, I will make time to have a check and prepare a PR.
