### ISSUE TITLE
[Feature Request] I remember a plan to use Composition API in docs,how is it going, need help?

### ISSUE THREAD

**Issue by MBearo** [element-plus/element-plus#1490]
### Existing Component
Yes

### Component Name
all

### Description
I remember a plan to use Composition API in docs,but I found that only a few components use Composition API in docs,how is it going, need help?

**Comment by XingXiaoWu** [comment]
I have submitted the pull, but there is no member to review...
https://github.com/element-plus/element-plus/pull/1480

**Comment by XingXiaoWu** [comment]
And I found that the multilingual documentation was missing
https://github.com/element-plus/element-plus/issues/1481

**Comment by kooriookami** [comment]
We now support Composition API in docs, need time to perfect it.
