### ISSUE TITLE
[Component] [tree-select] el-tree-select的value是对象时，所有的检点是选中状态的bug

### ISSUE THREAD

**Issue by yzh1234567** [element-plus/element-plus#14910]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.3.8`
- Browser / OS: `Chrome/119.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJkYXRhLnZhbHVlXCIgbGF6eSA6bG9hZD1cImxvYWRcIiA6cHJvcHM9XCJwcm9wc1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkYXRhID0gcmVhY3RpdmUoe1xuICAgIHZhbHVlOicnXG59KVxuXG5jb25zdCBwcm9wcyA9IHtcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBpc0xlYWY6ICdpc0xlYWYnLFxufVxuXG5sZXQgaWQgPSAwXG5cbmNvbnN0IGxvYWQgPSAobm9kZSwgcmVzb2x2ZSkgPT4ge1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBjb25zdCBvYmogPSB7XG4gICAgICAgaWQ6ICsraWQsXG4gICAgICAgbGFiZWw6IGBsYXp5IGxvYWQgbm9kZSR7aWR9YCxcbiAgICAgICBpc0xlYWY6IG5vZGUubGV2ZWwgIT09IDAsXG4gICAgfVxuICAgIHJlc29sdmUoW1xuICAgICAge1xuICAgICAgICAuLi5vYmosXG4gICAgICAgIHZhbHVlOm9ialxuICAgICAgfVxuICAgIF0pXG4gIH0sIDQwMClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1、设置value为对象；2、初始的v-model为空，3、打开下拉选择框

### What is Expected?

只有选中的才是激活状态

### What is actually happening?

所有的节点都是选中状态

### Additional comments

_(empty)_

**Comment by DcloudApp** [comment]
[https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cImRhdGEudmFsdWVcIiBsYXp5IDpsb2FkPVwibG9hZFwiIDpwcm9wcz1cInByb3BzXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYscmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gICAgdmFsdWU6Jydcbn0pXG5cbmNvbnN0IHByb3BzID0ge1xuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGlzTGVhZjogJ2lzTGVhZicsXG59XG5cbmxldCBpZCA9IDBcblxuY29uc3QgbG9hZCA9IChub2RlLCByZXNvbHZlKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnN0IG9iaiA9IHtcbiAgICAgICB2YWx1ZTogKytpZCxcbiAgICAgICBsYWJlbDogYGxhenkgbG9hZCBub2RlJHtpZH1gLFxuICAgICAgIGlzTGVhZjogbm9kZS5sZXZlbCAhPT0gMCxcbiAgICB9XG4gICAgcmVzb2x2ZShbXG4gICAgICB7XG4gICAgICAgIC4uLm9iaixcbiAgICAgIH1cbiAgICBdKVxuICB9LCA0MDApXG4gIFxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319](url)

**Comment by DcloudApp** [comment]
[https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cImRhdGEudmFsdWVcIiBsYXp5IDpsb2FkPVwibG9hZFwiIDpwcm9wcz1cInByb3BzXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYscmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gICAgdmFsdWU6Jydcbn0pXG5cbmNvbnN0IHByb3BzID0ge1xuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGlzTGVhZjogJ2lzTGVhZicsXG59XG5cbmxldCBpZCA9IDBcblxuY29uc3QgbG9hZCA9IChub2RlLCByZXNvbHZlKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnN0IG9iaiA9IHtcbiAgICAgICB2YWx1ZTogKytpZCxcbiAgICAgICBsYWJlbDogYGxhenkgbG9hZCBub2RlJHtpZH1gLFxuICAgICAgIGlzTGVhZjogbm9kZS5sZXZlbCAhPT0gMCxcbiAgICB9XG4gICAgcmVzb2x2ZShbXG4gICAgICB7XG4gICAgICAgIC4uLm9iaixcbiAgICAgIH1cbiAgICBdKVxuICB9LCA0MDApXG4gIFxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319](url)

**Comment by DcloudApp** [comment]
You can see if the following meets your expectations [Element Plus](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJkYXRhLnZhbHVlXCIgbGF6eSA6bG9hZD1cImxvYWRcIiA6cHJvcHM9XCJwcm9wc1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmLHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkYXRhID0gcmVhY3RpdmUoe1xuICAgIHZhbHVlOicnXG59KVxuXG5jb25zdCBwcm9wcyA9IHtcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBpc0xlYWY6ICdpc0xlYWYnLFxufVxuXG5sZXQgaWQgPSAwXG5cbmNvbnN0IGxvYWQgPSAobm9kZSwgcmVzb2x2ZSkgPT4ge1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBjb25zdCBvYmogPSB7XG4gICAgICAgdmFsdWU6ICsraWQsXG4gICAgICAgbGFiZWw6IGBsYXp5IGxvYWQgbm9kZSR7aWR9YCxcbiAgICAgICBpc0xlYWY6IG5vZGUubGV2ZWwgIT09IDAsXG4gICAgfVxuICAgIHJlc29sdmUoW1xuICAgICAge1xuICAgICAgICAuLi5vYmosXG4gICAgICB9XG4gICAgXSlcbiAgfSwgNDAwKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by yzh1234567** [comment]
我期望v-model得到的也是对象或者数组对象
