### ISSUE TITLE
[TypeScript] [date-picker] TSX 使用 ElDatePicker 缺少事件类型，例如 onChange onBlur ... 。提示 "不存在属性“onChange”" 。(TSX uses ElDatePicker missing event types, such as onChange onBlur... . Prompt "No property 'onChange' exists")

### ISSUE THREAD

**Issue by peng-xiao-shuai** [element-plus/element-plus#14924]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36  bugReport.browser is required 构建工具`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuaW1wb3J0IHsgZGVmaW5lQ29tcG9uZW50LCByZWYsIHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxEYXRlUGlja2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzJ1xuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgc2V0dXAoKSB7XG4gIGNvbnN0IGZvcm1EYXRhID0gcmVhY3RpdmUoe1xuICAgIHRpbWVzOiBbXVxuICB9KVxuICAgIHJldHVybiAoKSA9PiAoXG4gICAgICA8PlxuICAgICAgICA8RWxEYXRlUGlja2VyXG4gICAgICAgICAgdi1tb2RlbD17Zm9ybURhdGEudGltZXN9XG4gICAgICAgICAgb25DaGFuZ2U9eyguLi5hcmc6IGFueSkgPT4ge1xuICAgICAgICAgIH19XG4gICAgICAgICAgb25CbHVyPXsoLi4uYXJnOiBhbnkpID0+IHtcbiAgICAgICAgICB9fVxuICAgICAgICAgIG9uRm9jdXM9eyguLi5hcmc6IGFueSkgPT4ge1xuICAgICAgICAgIH19XG4gICAgICAgICAgb25DYWxlbmRhckNoYW5nZT17KC4uLmFyZzogYW55KSA9PiB7XG4gICAgICAgICAgfX1cbiAgICAgICAgICBvblBhbmVsQ2hhbmdlPXsoLi4uYXJnOiBhbnkpID0+IHtcbiAgICAgICAgICB9fVxuICAgICAgICAgIG9uVmlzaWJsZUNoYW5nZT17KC4uLmFyZzogYW55KSA9PiB7XG4gICAgICAgICAgfX1cbiAgICAgICAgLz5cbiAgICAgIDwvPlxuICAgIClcbiAgfVxufSlcbjwvc2NyaXB0PlxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<script lang="tsx">
import { defineComponent, ref, reactive } from 'vue'
import { ElDatePicker } from 'element-plus/es'
export default defineComponent({
  setup() {
  const formData = reactive({
    times: []
  })
    return () => (
      <>
        <ElDatePicker
          v-model={formData.times}
          onChange={(...arg: any) => {
          }}
          onBlur={(...arg: any) => {
          }}
          onFocus={(...arg: any) => {
          }}
          onCalendarChange={(...arg: any) => {
          }}
          onPanelChange={(...arg: any) => {
          }}
          onVisibleChange={(...arg: any) => {
          }}
        />
      </>
    )
  }
})
</script>
```

### What is Expected?

得到正确的事件类型提示
(Get the correct event type prompt)

### What is actually happening?

事件类型提示缺失
(The event type indicates that the alarm is missing)

### Additional comments

_(empty)_

**Comment by peng-xiao-shuai** [comment]
<img width="476" alt="1700709507487" src="https://github.com/element-plus/element-plus/assets/53845479/c622a5e7-8578-42a5-8dab-5983c5e9eb64">
<img width="479" alt="1700709862556" src="https://github.com/element-plus/element-plus/assets/53845479/93c07e82-8acb-4bd0-9efa-b3087f760b2b">
<img width="715" alt="1700709851427" src="https://github.com/element-plus/element-plus/assets/53845479/84e88568-8d5c-41f4-be7c-d67e9d0205d2">

**Comment by tolking** [comment]
Discussion on #8424

**Comment by Moresl** [comment]
怎么还没解决？有代替的办法吗控件无法触发onChange
