### ISSUE TITLE
[bug report] load on demand, unable to use SCSS file, wrong description on official website

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#1492]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
谷歌

### Vue version
3.0.5

### Steps to reproduce
根据按需最新官方文档进行配置按需加载，使用scss文件的情况下报错
如下是官方文档的说明，无法使用只能使用css文件
// elementUI按需加载
    [
      'import',
      {
        libraryName: 'element-plus',
        customStyleName: (name) => {
          // 由于 customStyleName 在配置中被声明的原因，`style: true` 会被直接忽略掉，
          // 如果你需要使用 scss 源文件，把文件结尾的扩展名从 `.css` 替换成 `.scss` 就可以了
          return `element-plus/lib/theme-chalk/${name}.css`
        },
      },
    ],

### What is Expected?
可以使用scss源文件

### What is actually happening?
只能使用css文件

**Comment by mPyth** [comment]
Seems there are several errors in section [Import component theme on demand](https://element-plus.org/#/en-US/component/custom-theme#import-component-theme-on-demand) \:

- in the place of `babel-plugin-component` package `babel-plugin-import` should be used, as it is mentioned on the page [Quick Start -> On Demand](https://element-plus.org/#/en-US/component/quickstart#on-demand) .
- in the place of `.babelrc` file `babel.config.js` should be edited in the same way as it is described on [Quick Start -> On Demand](https://element-plus.org/#/en-US/component/quickstart#on-demand), with the note that in the place of `styleLibraryName` probably `styleLibraryDirectory`  should be used (see [babel-plugin-import usage -> styleLibraryDirectory](https://github.com/ant-design/babel-plugin-import#stylelibrarydirectory) ).

**Comment by jdinartejesus** [comment]
I'm having the similar issue, where I need to use on-demand components with my own style scss variables. Can someone help me here?
