### ISSUE TITLE
[Style] [drawer, card] Drawer el-drawer__body样式不生效

### ISSUE THREAD

**Issue by zzfF1** [element-plus/element-plus#14931]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.1.0`
- Browser / OS: `chrome 119.0.6045.160`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-card`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdmlzaWJsZSA9IHJlZih0cnVlKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1kcmF3ZXJcbiAgICAgIHRpdGxlPVwi5rWL6K+VXCJcbiAgICAgIHYtbW9kZWw9XCJ2aXNpYmxlXCJcbiAgICAgIHNpemU9XCI1MCVcIlxuICAgICAgYXBwZW5kLXRvLWJvZHlcbiAgICAgIDpjbG9zZS1vbi1jbGljay1tb2RhbD1cImZhbHNlXCJcbiAgICAgIHN0eWxlPVwicGFkZGluZy10b3A6IDBweCAhaW1wb3J0YW50O1wiXG4gICAgPlxuICAgIDxlbC1jYXJkIHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMTBweDsgYmFja2dyb3VuZC1jb2xvcjogIzFjODRjNjsgcGFkZGluZy10b3A6IDVweCAhaW1wb3J0YW50O1wiPlxuICAgICAgPGRpdj4xMTExPC9kaXY+XG4gICAgPC9lbC1jYXJkPlxuICA8L2VsLWRyYXdlcj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtZHJhd2VyX19ib2R5e1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMWM4NGM2O1xuICBwYWRkaW5nLXRvcDogMHB4ICFpbXBvcnRhbnQ7XG59XG48L3N0eWxlPlxuXG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

添加el-drawer

### What is Expected?

<style scoped>
.el-drawer__body{
  background-color: #1c84c6;
  padding-top: 0px !important;
}
</style>

### What is actually happening?

el-drawer__body的背景颜色生效,padding-top为0

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/44562386/54b96079-0627-4b4a-a550-77f3c1c1e44d)

**Comment by Jevin0** [comment]
uses this global selector`:global(.el-drawer__body)`

**Comment by zzfF1** [comment]
:global(.el-drawer__body) 可以实现我想要的效果.
think @Jevin0

**Comment by zzfF1** [comment]
:global(.el-drawer__body) 这样设置全局的样式 有什么方法只有本界面生效吗? @Jevin0

**Comment by Jevin0** [comment]
![image](https://github.com/element-plus/element-plus/assets/69580637/b941d106-875d-44ac-a015-1d299397dda6)

You are mounting the drawer on the body. The scoped style tag in the current component cannot be applied to the drawer. You can try adding a tag without scoped
