### ISSUE TITLE
[Component] [select] el-select 本身会造成内存泄漏，使用自定义图标后则不会

### ISSUE THREAD

**Issue by hw952** [element-plus/element-plus#14948]
既 [BUG 14944](https://github.com/element-plus/element-plus/issues/14944) 引起了大家强烈反应，希望能提供测试地址供测试。
现以el-select为例：

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select el-pagination el-date-picker`   等其他使用内置icon的组件都如出一辙，都存在同样的问题

### Reproduction Link

[Github Repo](https://github.com/hw952/test-el-select)

### Steps to reproduce

1. 打开控制-性能监视器
 
![1](https://github.com/element-plus/element-plus/assets/32861583/7284ab94-3462-45ed-92da-1e9861456794)
> 原始dom节点只有60个以下

2. 打开页签 【el-select 原始】再回到页签【Home】 观察dom节点数量
![2](https://github.com/element-plus/element-plus/assets/32861583/9ddf3dcd-997b-4c26-be58-dcce11469116)
> 等了很久dom节点数量一直不下降

3. F5刷新页面释放内存， 然后打开页签 【el-select 替换icon】 再回到页签【Home】
    观察dom节点数量

![image](https://github.com/element-plus/element-plus/assets/32861583/876e9b46-e69a-46df-92c0-a8ef13aec570)

> dom节点数量会回到起始水平

也可以手动触发回收
![image](https://github.com/element-plus/element-plus/assets/32861583/bd1f7d51-5b3d-41fa-b5d8-88b4be43d7d5)

> 后两个标签都for循环了500个el-select

### What is Expected?

dom节点数量降下来

### What is actually happening?

dom节点数量不会下降

### Additional comments

_(empty)_

**Comment by onlyscv** [comment]
前排围观，最近我们自己的ELEMENT-PLUS 也是有各种内存泄露问题。
特别是表格套 tooltips ，刷新页面，刷着刷着···内存就爆表了，浏览器就崩溃了。

希望下一个版本修复下内存泄露问题，要不然真的要换了。。遭不住。。

**Comment by kooriookami** [comment]
我下午定位到问题在@element-plus/icons-vue打包的文件node_modules\@element-plus\icons-vue\dist\index.js上。
源文件精简只留1个icon，引入其中的图标会造成内存溢出：
```js
/*! Element Plus Icons Vue v2.1.0 */

var add_location_vue_vue_type_script_lang_default = {
  name: "AddLocation"
};

// src/components/add-location.vue
import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue";

// unplugin-vue: /plugin-vue/export-helper
var export_helper_default = (sfc, props) => {
  let target = sfc.__vccOpts || sfc;
  for (let [key, val] of props)
    target[key] = val;
  return target;
};

// src/components/add-location.vue
var _hoisted_1 = {
  xmlns: "http://www.w3.org/2000/svg",
  viewBox: "0 0 1024 1024"
}, _hoisted_2 = /* @__PURE__ */ _createElementVNode(
  "path",
  {
    fill: "currentColor",
    d: "M288 896h448q32 0 32 32t-32 32H288q-32 0-32-32t32-32z"
  },
  null,
  -1
  /* HOISTED */
), _hoisted_3 = /* @__PURE__ */ _createElementVNode(
  "path",
  {
    fill: "currentColor",
    d: "M800 416a288 288 0 1 0-576 0c0 118.144 94.528 272.128 288 456.576C705.472 688.128 800 534.144 800 416zM512 960C277.312 746.688 160 565.312 160 416a352 352 0 0 1 704 0c0 149.312-117.312 330.688-352 544z"
  },
  null,
  -1
  /* HOISTED */
), _hoisted_4 = /* @__PURE__ */ _createElementVNode(
  "path",
  {
    fill: "currentColor",
    d: "M544 384h96a32 32 0 1 1 0 64h-96v96a32 32 0 0 1-64 0v-96h-96a32 32 0 0 1 0-64h96v-96a32 32 0 0 1 64 0v96z"
  },
  null,
  -1
  /* HOISTED */
), _hoisted_5 = [
  _hoisted_2,
  _hoisted_3,
  _hoisted_4
];
function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
  return _openBlock(), _createElementBlock("svg", _hoisted_1, _hoisted_5);
}
var add_location_default = /* @__PURE__ */ export_helper_default(add_location_vue_vue_type_script_lang_default, [["render", _sfc_render], ["__file", "add-location.vue"]]);

export {
  add_location_default as AddLocation,
};
```

换一种实现方式，直接import图标的vue文件，就不会内存溢出：
```js
import AddLocation from './add-location.vue'

export {
    AddLocation,
};
```

add-location.vue：
```vue
<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
    <path
      fill="currentColor"
      d="M288 896h448q32 0 32 32t-32 32H288q-32 0-32-32t32-32z"
    />
    <path
      fill="currentColor"
      d="M800 416a288 288 0 1 0-576 0c0 118.144 94.528 272.128 288 456.576C705.472 688.128 800 534.144 800 416zM512 960C277.312 746.688 160 565.312 160 416a352 352 0 0 1 704 0c0 149.312-117.312 330.688-352 544z"
    />
    <path
      fill="currentColor"
      d="M544 384h96a32 32 0 1 1 0 64h-96v96a32 32 0 0 1-64 0v-96h-96a32 32 0 0 1 0-64h96v-96a32 32 0 0 1 64 0v96z"
    />
  </svg>
</template>
<script lang="ts">
import type { DefineComponent } from 'vue'
export default {
  name: 'AddLocation',
} as DefineComponent
</script>
```
以上两者渲染后的dom结构是一致的，目前还没有排除是组件库的问题还vue的问题。

**Comment by kooriookami** [comment]
https://github.com/vuejs/core/issues/8790 相关问题
