### ISSUE TITLE
[All] 神经病，这可是fastjson经典传承，圣诞节彩蛋能叫bug吗

### ISSUE THREAD

**Issue by 36k-wild-monkey** [element-plus/element-plus#14950]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.4.0-alpha.1`
- Element Plus Version: `2.4.2`
- Browser / OS: `chrome`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/xxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx.js)

### Steps to reproduce

神经病，这可是fastjson经典传承，圣诞节彩蛋能叫bug吗

### What is Expected?

1

### What is actually happening?

2

### Additional comments

今天是美国感恩节，这是感恩节彩蛋

（阴阳怪气的李xx语气）你们有没有努力工作修bug，这么多年一直都是这个彩蛋，别乱说好吗

**Comment by kooriookami** [comment]
？
