### ISSUE TITLE
[Bug Report] Search for label that are not in the options, lose focus, and still display "No matching data" after getting focus

### ISSUE THREAD

**Issue by CitizenChaos** [element-plus/element-plus#1495]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
win10 20H2 64bit / Chrome 88.0.4324.182 64bit

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/citizenchaos/pen/oNYXoOj

### Steps to reproduce
1. <el-select> has a default value.
2. Search for label that are not in the options. It will appear "No matching data".
3. Lose focus.
4. Get focus.
5. It will also display "No matching data"

### What is Expected?
Do not display "No matching data" after getting focus.
The same operation will not display "No matching data" in "https://element.eleme.cn/#/zh-CN/component/select#ke-sou-suo"

### What is actually happening?
It still shows "No matching data" after getting focus

**Comment by Ryan2128** [comment]
Will fix soon.
