### ISSUE TITLE
[Bug Report] ElSelect  Remote Search No data bug

### ISSUE THREAD

**Issue by LiuwqGit** [element-plus/element-plus#1496]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
chrome  88.0.4324.182 （64 位）

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/weiqinl/pen/NWbaagE

### Steps to reproduce
 操作步骤：
  1. 先输入a，选择一个选项。
  2. 再输入abc，此时没有数据 No data。
  3. 点击页面空白处，下拉列表未正确消失

### What is Expected?
希望正常消失

### What is actually happening?
未正常消失

**Comment by Ryan2128** [comment]
Same as #1207 #1300 

It is a bug of vue, the demo works well in version 3.0.2.

[vue 3 #2768](https://github.com/vuejs/vue-next/issues/2768)
[vue 3 #2829](https://github.com/vuejs/vue-next/issues/2829)

**Comment by Ryan2128** [comment]
Vue 3.0.7 has released. If still has problem, please reopen issue.
