### ISSUE TITLE
[Style] [table-column, table] el-table的fixed固定列低版本兼容问题

### ISSUE THREAD

**Issue by LeeZChuan** [element-plus/element-plus#14978]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.4.2`
- Browser / OS: `版本 52.0.2718.0 (64-bit) 以及更低版本的浏览器`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgY3VycmVudERhdGEgPSBbXG4gIHtcbiAgICBpbmRleDogMSxcbiAgICBjb2RlOiAnMjIyMjInLFxuICAgIG1hcmtldDogJ1NaSFEnLFxuICAgIHN0a0lkOiAyMjIyMjIsXG4gICAgbmFtZTogJ3h4eHh4JyxcbiAgICBjb3VsZEFwcGx5OiBmYWxzZSxcbiAgICBsYXRlc3ROb3RpY2U6IHtcbiAgICAgIGRhdGU6ICcyMDIzLTEyLTA0J1xuICAgIH0sXG4gICAgYXBwbHlNYXhOdW06IDAsXG4gICAgY2xvc2VQcmljZTogNzguOSxcbiAgICBkYXlSaXNlOiAwLjksXG4gICAgcGhhc2VSaXNlOiAwLjlcbiAgfSxcbiAge1xuICAgIGluZGV4OiAyLFxuICAgIGNvZGU6ICczMzMzMzMnLFxuICAgIG1hcmtldDogJ1NISFEnLFxuICAgIHN0a0lkOiAzMzMzMyxcbiAgICBuYW1lOiAneXl5eXknLFxuICAgIGNvdWxkQXBwbHk6IGZhbHNlLFxuICAgIGxhdGVzdE5vdGljZToge1xuICAgICAgZGF0ZTogJzIwMjMtMTItMDQnXG4gICAgfSxcbiAgICBhcHBseU1heE51bTogMCxcbiAgICBjbG9zZVByaWNlOiAzNzguOSxcbiAgICBkYXlSaXNlOiAwLjksXG4gICAgcGhhc2VSaXNlOiAwLjlcbiAgfSxcbiAge1xuICAgIGluZGV4OiAzLFxuICAgIGNvZGU6ICc0NDQ0NCcsXG4gICAgbWFya2V0OiAnU1pIUScsXG4gICAgc3RrSWQ6IDQ0NDQsXG4gICAgbmFtZTogJ3p6enp6JyxcbiAgICBjb3VsZEFwcGx5OiBmYWxzZSxcbiAgICBsYXRlc3ROb3RpY2U6IHtcbiAgICAgIGRhdGU6ICcyMDIzLTEyLTA0J1xuICAgIH0sXG4gICAgYXBwbHlNYXhOdW06IDEwLFxuICAgIGNsb3NlUHJpY2U6IDE3OC45LFxuICAgIGRheVJpc2U6IDEwLjksXG4gICAgcGhhc2VSaXNlOiAxMC45XG4gIH0sXG4gIHtcbiAgICBpbmRleDogNCxcbiAgICBjb2RlOiAnNTU1NTU1JyxcbiAgICBuYW1lOiAnY2NjY2NjYycsXG4gICAgYm9hcmQ6ICdTWl9TJyxcbiAgICBhcHBseUNvZGU6ICczMDE1MTYnLFxuICAgIGNvdWxkQXBwbHk6IGZhbHNlLFxuICAgIGxhdGVzdE5vdGljZToge1xuICAgICAgZGF0ZTogJzIwMjMtMTItMDQnXG4gICAgfSxcbiAgICBhcHBseU1heE51bTogMCxcbiAgICBjbG9zZVByaWNlOiA3OC45LFxuICAgIGRheVJpc2U6IDMwLjksXG4gICAgcGhhc2VSaXNlOiAzMC45XG4gIH0sXG4gIHtcbiAgICBpbmRleDogNSxcbiAgICBjb2RlOiAnNjY2NjY2JyxcbiAgICBuYW1lOiAndnZ2dnZ2dicsXG4gICAgYm9hcmQ6ICdTSF9TVEFSJyxcbiAgICBhcHBseUNvZGU6ICc3ODc3MjAnLFxuICAgIGNvdWxkQXBwbHk6IGZhbHNlLFxuICAgIGxhdGVzdE5vdGljZToge1xuICAgICAgZGF0ZTogJzIwMjMtMTItMDQnXG4gICAgfSxcbiAgICBhcHBseU1heE51bTogMCxcbiAgICBjbG9zZVByaWNlOiA3OC45LFxuICAgIGRheVJpc2U6IDAuOSxcbiAgICBwaGFzZVJpc2U6IDAuOVxuICB9LFxuICB7XG4gICAgaW5kZXg6IDYsXG4gICAgY29kZTogJzc3Nzc3NycsXG4gICAgbmFtZTogJ2JiYmJiYicsXG4gICAgYm9hcmQ6ICdTSF9NJyxcbiAgICBhcHBseUNvZGU6ICc3ODAwODMnLFxuICAgIGNvdWxkQXBwbHk6IGZhbHNlLFxuICAgIGxhdGVzdE5vdGljZToge1xuICAgICAgZGF0ZTogJzIwMjMtMTItMDQnXG4gICAgfSxcbiAgICBhcHBseU1heE51bTogMCxcbiAgICBjbG9zZVByaWNlOiA3OC45LFxuICAgIGRheVJpc2U6IDAuOSxcbiAgICBwaGFzZVJpc2U6IDAuOVxuICB9LFxuICB7XG4gICAgaW5kZXg6IDcsXG4gICAgY29kZTogJzg4ODg4OCcsXG4gICAgbmFtZTogJ25ubm5ubicsXG4gICAgYm9hcmQ6ICdTWl9TJyxcbiAgICBhcHBseUNvZGU6ICczMDE1MDgnLFxuICAgIGNvdWxkQXBwbHk6IGZhbHNlLFxuICAgIGxhdGVzdE5vdGljZToge1xuICAgICAgZGF0ZTogJzIwMjMtMTItMDQnXG4gICAgfSxcbiAgICBhcHBseU1heE51bTogMCxcbiAgICBjbG9zZVByaWNlOiA3OC45LFxuICAgIGRheVJpc2U6IDAuOSxcbiAgICBwaGFzZVJpc2U6IDAuOVxuICB9XVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImhlaWdodDo0MDBweDt3aWR0aDo1MDBweDtcIj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJjdXJyZW50RGF0YVwiIHN0eWxlPVwiaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaW5kZXhcIiBsYWJlbD1cInjluo/lj7dcIiB3aWR0aD1cIjEwMFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJjb2RlXCIgbGFiZWw9XCLku6PnoIFcIiB3aWR0aD1cIjEwMFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCLogqHnpajlkI3np7BcIiB3aWR0aD1cIjEwMFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJjbG9zZVByaWNlXCIgbGFiZWw9XCLmnIDmlrDku7dcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXlSaXNlXCIgbGFiZWw9XCLmtqjluYVcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXlSaXNlXCIgbGFiZWw9XCLmtqjluYVcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXlSaXNlXCIgbGFiZWw9XCLmtqjluYVcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXlSaXNlXCIgbGFiZWw9XCLmtqjluYVcIiB3aWR0aD1cIjEwMFwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-table在打包后的页面，低版本下展示效果有问题

正常编写类似这样的结构：
```vue
<div class="stock-table">
    <el-table :data="data" style="height: 100%; width: 100%">
      <el-table-column
        prop="index" label="x序号" width="100"
        fixed
      />
      <el-table-column
        prop="code" label="代码" width="100"
        fixed
      />
      <el-table-column
        prop="name" label="股票名称" width="100"
        fixed
      />
      <el-table-column prop="closePrice" label="最新价" width="100" />
      <el-table-column prop="dayRise" label="涨幅" width="100" />
      <el-table-column prop="dayRise" label="涨幅" width="100" />
      <el-table-column prop="dayRise" label="涨幅" width="100" />
      <el-table-column prop="dayRise" label="涨幅" width="100" />
    </el-table>
  </div>
```

由于前三列配置了列的fixed属性，组件内部计算定位出现了问题
在低版本浏览器就会出现如下展示问题：
![QQ截图20231127193941](https://github.com/element-plus/element-plus/assets/48050314/9b5be058-2749-47f5-929c-d49596e981fc)
正常的预期想要的效果：
![QQ截图20231127194211](https://github.com/element-plus/element-plus/assets/48050314/a39a7493-bdb8-484d-95ad-4401532e742b)

### What is Expected?

在低版本的el-table-column的fixed配置项样式可以正常展示；
或者我需要写那些兼容逻辑呢？

### What is actually happening?

现在的样式会发现低版本以chrome 版本 52.0.2718.0 、或者更低的浏览器版本：49版本，会发现文字列排版错乱；

在高版本的浏览器是正常的

### Additional comments

这个可能是固定列的定位样式导致的问题，
也就是组件内部添加的：
![image](https://github.com/element-plus/element-plus/assets/48050314/1cbf2758-8a4e-4726-a812-b6cd685089ed)

**Comment by chenxch** [comment]
环境支持要求chrome ≥ 64

**Comment by LeeZChuan** [comment]
> 环境支持要求chrome ≥ 64

如果我想强行兼容，请问有什么方案吗？或者有哪些提供的思路？

**Comment by chenxch** [comment]
目前我这没有该版本的chorme可以查看， 原因可能是出在sticky样式上，你可以往样式方向上看看

**Comment by LeeZChuan** [comment]
好的，感谢，我们使用原生table重新写了
