### ISSUE TITLE
[Feature Request] MessageBox should have a width prop

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1497]
### Existing Component
Yes

### Component Name
MessageBox

### Description
I think he should support the definition of width just like dialog.
When I set a long text and want the message box to be displayed in one line. I found that he didn't have a width attribute for me to modify his width.

**Comment by wulinsheng123** [comment]
@zazzaz 这个任务可以分配给我嘛 #

**Comment by liushuiyuan001** [comment]
yeah, It's ok. I will try fix

**Comment by Ryan2128** [comment]
Can you provide a demo?

**Comment by liushuiyuan001** [comment]
The attribute **customClass** can meet the needs

**Comment by Vgbire** [comment]
> Can you provide a demo?

https://codepen.io/vgbire/pen/jOVaOBP

**Comment by Vgbire** [comment]
> The attribute **customClass** can meet the needs

year,In my project, that's how I solve it temporarily.This dialog is highly reusable, so I abstract it to the composition API for reuse. But it seems that the composition API can't define styles, so I have to put its styles into global styles or components.
which is like.
``` javascript
export default funnction xxx(){
  const openDialog = (context)=>{
    context.$confirm('message body','title',{
      customClass: 'xxxdialog'
    })
  }
  return { openDialog }
}
```
