### ISSUE TITLE
[Bug Report]Dart sass discard warning

### ISSUE THREAD

**Issue by Mu5sun** [element-plus/element-plus#1499]
main.js文件中直接引入element-plus/packages/theme-chalk/src/index.scss文件会报警告

**警告为：**
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$B: null` at the root of the
stylesheet.

**Comment by gzf6** [comment]
same issue in vite2

**Comment by qqjay2017** [comment]
in vite2 project,if you use `vite-plugin-style-import` to auto import scss , terminal will export `DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
`
version: 

"sass": "^1.33.0",
"element-plus": "^1.0.2-beta.44",
"vite": "^2.2.4",
"vite-plugin-style-import": "^0.10.0",

**Comment by qqjay2017** [comment]
and if you import `base.scss` 
```
More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $--group-option-flex: 0 0 (1/5) * 100% !default;
    │                            ^^^
    ╵
    node_modules\element-plus\packages\theme-chalk\src\common\var.scss 498:28      @import
    node_modules\element-plus\packages\theme-chalk\src\common\transition.scss 2:9  @import
    node_modules\element-plus\packages\theme-chalk\src\base.scss 1:9               root stylesheet
```

**Comment by bokuns** [comment]
> and if you import `base.scss`
> 
> ```
> More info and automated migrator: https://sass-lang.com/d/slash-div
> 
>     ╷
> 498 │ $--group-option-flex: 0 0 (1/5) * 100% !default;
>     │                            ^^^
>     ╵
>     node_modules\element-plus\packages\theme-chalk\src\common\var.scss 498:28      @import
>     node_modules\element-plus\packages\theme-chalk\src\common\transition.scss 2:9  @import
>     node_modules\element-plus\packages\theme-chalk\src\base.scss 1:9               root stylesheet
> ```

Same.

**Comment by icksky** [comment]
@JeremyWuuuuu It's seems had fixed by latest version, but the npm package haven't update.

**Comment by codepandy** [comment]
@icksky how to resolve it?the project can't work.

**Comment by icksky** [comment]
> @icksky how to resolve it?the project can't work.

@codepandy you can ignore the warnings until the npm is updated.😂

**Comment by JeremyWuuuuu** [comment]
Guys, we will have a release tomorrow. You will no longer suffer from this issue, if you do suffer from this issue, please downgrade to the version that supports `/` operator

**Comment by savannahp** [comment]
This is still an issue with that version

**Comment by JeremyWuuuuu** [comment]
@savannahp Can you give us a reproducible code for fixing this? We would really like to help. Please do reach out to me ;)
Maybe you can open an issue.

**Comment by JeremyWuuuuu** [comment]
@savannahp Could you follow this instruction to see whether it solves your issue?
https://github.com/element-plus/element-plus/issues/2132#issuecomment-853505747

**Comment by YunYouJun** [comment]
It seems to have been fixed in the new version.
