### ISSUE TITLE
[Component] [menu] el-menu 的default-openeds为响应式数据时 不生效

### ISSUE THREAD

**Issue by ZTzhangtuo** [element-plus/element-plus#14991]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.3`
- Browser / OS: `macOS12.1`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51XG4gICAgICAgIGNsYXNzPVwiZWwtbWVudS12ZXJ0aWNhbC1kZW1vXCJcbiAgICAgICAgQG9wZW49XCJoYW5kbGVPcGVuXCJcbiAgICAgICAgQGNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICAgICAgIGRlZmF1bHQtYWN0aXZlPVwiMVwiXG4gICAgICAgOmRlZmF1bHQtb3BlbmVkcz1cImFyclwiXG4gICAgICA+XG4gICAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjFcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICAgICAgPGVsLWljb24+PGxvY2F0aW9uIC8+PC9lbC1pY29uPlxuICAgICAgICAgICAgPHNwYW4+TmF2aWdhdG9yIE9uZTwvc3Bhbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDxlbC1tZW51LWl0ZW0tZ3JvdXAgdGl0bGU9XCJHcm91cCBPbmVcIj5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCB0aXRsZT1cIkdyb3VwIFR3b1wiPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIxLTRcIj5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48aWNvbi1tZW51IC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPk5hdmlnYXRvciBUd288L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiM1wiIGRpc2FibGVkPlxuICAgICAgICAgIDxlbC1pY29uPjxkb2N1bWVudCAvPjwvZWwtaWNvbj5cbiAgICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgVGhyZWU8L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNFwiPlxuICAgICAgICAgIDxlbC1pY29uPjxzZXR0aW5nIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPk5hdmlnYXRvciBGb3VyPC9zcGFuPlxuICAgICAgICA8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge1xuICBEb2N1bWVudCxcbiAgTWVudSBhcyBJY29uTWVudSxcbiAgTG9jYXRpb24sXG4gIFNldHRpbmcsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHtyZWYsb25Nb3VudGVkfSBmcm9tICd2dWUnXG5jb25zdCBoYW5kbGVPcGVuID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuY29uc3QgYXJyID1yZWYoW10pXG5vbk1vdW50ZWQoKCk9PntcbmFyci52YWx1ZT1bJzEnXX0pXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

<template>
      <el-menu
        class="el-menu-vertical-demo"
        @open="handleOpen"
        @close="handleClose"
       default-active="1"
       :default-openeds="arr"
      >
        <el-sub-menu index="1">
          <template #title>
            <el-icon><location /></el-icon>
            <span>Navigator One</span>
          </template>
          <el-menu-item-group title="Group One">
            <el-menu-item index="1-1">item one</el-menu-item>
            <el-menu-item index="1-2">item two</el-menu-item>
          </el-menu-item-group>
          <el-menu-item-group title="Group Two">
            <el-menu-item index="1-3">item three</el-menu-item>
          </el-menu-item-group>
          <el-sub-menu index="1-4">
            <template #title>item four</template>
            <el-menu-item index="1-4-1">item one</el-menu-item>
          </el-sub-menu>
        </el-sub-menu>
        <el-menu-item index="2">
          <el-icon><icon-menu /></el-icon>
          <span>Navigator Two</span>
        </el-menu-item>
        <el-menu-item index="3" disabled>
          <el-icon><document /></el-icon>
          <span>Navigator Three</span>
        </el-menu-item>
        <el-menu-item index="4">
          <el-icon><setting /></el-icon>
          <span>Navigator Four</span>
        </el-menu-item>
      </el-menu>
</template>

<script lang="ts" setup>
import {
  Document,
  Menu as IconMenu,
  Location,
  Setting,
} from '@element-plus/icons-vue'
import {ref,onMounted} from 'vue'
const handleOpen = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
const handleClose = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
const arr =ref([])
onMounted(()=>{
arr.value=['1']})
</script>

### What is Expected?

从接口获取到菜单数据之后，需要全部展开el-sub-menu 传入el-sub-menu的index数组后 并未展开

### What is actually happening?

el-sub-menu不展开

### Additional comments

_(empty)_

**Comment by yj-liuzepeng** [comment]
在onMounted之前设置呢
