### ISSUE TITLE
### Drawer

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#150]
Assign to @luxueyan
Drawer component

**Comment by JeremyWuuuuu** [comment]
#149

**Comment by JeremyWuuuuu** [comment]
Hi @luxueyan, just checking in see if you have made any progress yet, and I am closing this issue for now, feel free to reopen this issue if you feel like it

**Comment by luxueyan** [comment]
I have done the feature, but the unit test is doing at my free time.
