### ISSUE TITLE
[Component] [cascader] update v-model leads to syncMenuState and scrollToExpandingNode

### ISSUE THREAD

**Issue by nothing-sy** [element-plus/element-plus#15006]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWZ9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7ZGF0YX0gZnJvbSAnLi9kYXRhJ1xuXG5jb25zdCBpdGVtTGlzdFByb3BzID0gcmVmKHtcbiAgICBsYWJlbDogJ3N5c3RlbURlc2MnLFxuICAgIHZhbHVlOiAnbmFtZScsXG4gICAgY2hpbGRyZW46ICdjaGlsZHJlbnMnLFxuICAgIGNoZWNrU3RyaWN0bHk6IHRydWUsXG4gICAgbXVsdGlwbGU6IHRydWUsXG4gICAgZW1pdFBhdGg6IGZhbHNlXG4gIH0pXG5jb25zdCBkZXZpY2VEYXRhTGlzdCA9IHJlZihkYXRhKVxuY29uc3QgY3VyRGV2aWNlRGF0YUxpc3QgPSByZWYoWzEsMiwzLDRdKVxuXG5mdW5jdGlvbiBjKCl7XG4vLyDljrvmjonlhbbkuK3kuIDkuKrlrZDpobnnmoTmiYDmnInmlbDmja5bMyw0Xe+8jOS8muWvvOiHtOS6jOe6p+mdouadv+ebtOaOpeWIh+aNouWIsOWJqeS9meWtkOmhuVsxLDJd5omA5Zyo55qE6Z2i5p2/LOiAjOS4jeaYr+WBnOeVmeWcqOW9k+WJjeaTjeS9nOaVsOaNrumhueeahOS6jOe6p+mdouadv1xuLy8gcmVtb3ZlIGFsbCBjaGlsZHJlbiBvZiBvbmUgb2YgcGFyZW50Tm9kZSxUaGUgcGFuZWwgb2YgY2hpbGQgd2lsbCBzd2l0Y2ggdG8gb3RoZXIgcGFuZWxcbmN1ckRldmljZURhdGFMaXN0LnZhbHVlID0gWzEsMl1cbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtY2FzY2FkZXJcbiAgICAgICAgICB2LW1vZGVsPVwiY3VyRGV2aWNlRGF0YUxpc3RcIlxuICAgICAgICAgIDpwcm9wcz1cIml0ZW1MaXN0UHJvcHNcIlxuICAgICAgICAgIDpjb2xsYXBzZS10YWdzPVwidHJ1ZVwiXG4gICAgICAgICAgOm9wdGlvbnM9XCJkZXZpY2VEYXRhTGlzdFwiXG4gICAgICAgICAgOnNob3ctYWxsLWxldmVscz1cImZhbHNlXCJcbiAgICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgICAgQGNoYW5nZT1cImNcIlxuICAgICAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9kYXRhLnRzIjoiZXhwb3J0IGNvbnN0IGRhdGEgPSBbXHJcbiAge1xyXG4gICAgXCJpZFwiOiA0ODkzLFxyXG4gICAgXCJuYW1lXCI6IFwidmlyMDAyXCIsXHJcbiAgICBcInN5c3RlbURlc2NcIjogXCLmtYvor5UyXCIsXHJcbiAgICBcImNoaWxkcmVuc1wiOiBbXHJcbiAgICAgIHtcclxuICAgICAgICBcImlkXCI6IDQzNjEsXHJcbiAgICAgICAgXCJuYW1lXCI6IDEsXHJcbiAgICAgICAgXCJzeXN0ZW1EZXNjXCI6IFwi5qih5Z2X55S15rWB5LiN5bmz6KGhXCIsXHJcbiAgICAgICAgXCJjaGlsZHJlbnNcIjogbnVsbFxyXG4gICAgICB9LFxyXG4gICAgICB7XHJcbiAgICAgICAgXCJpZFwiOiA0MzU5LFxyXG4gICAgICAgIFwibmFtZVwiOiAyLFxyXG4gICAgICAgIFwic3lzdGVtRGVzY1wiOiBcIlBDU+S6pOa1geS+p+WRiuitplwiLFxyXG4gICAgICAgIFwiY2hpbGRyZW5zXCI6IG51bGxcclxuICAgICAgfVxyXG4gICAgXVxyXG4gIH0sXHJcbiAge1xyXG4gICAgXCJpZFwiOiA0ODkyLFxyXG4gICAgXCJuYW1lXCI6IFwidmlyMDAxXCIsXHJcbiAgICBcInN5c3RlbURlc2NcIjogXCLmtYvor5UxXCIsXHJcbiAgICBcImNoaWxkcmVuc1wiOiBbXHJcbiAgICAgIHtcclxuICAgICAgICBcImlkXCI6IDQzNTcsXHJcbiAgICAgICAgXCJuYW1lXCI6MyxcclxuICAgICAgICBcInN5c3RlbURlc2NcIjogXCJQQ1PmqKHlnZfpmZDmtYHlkYroraZcIixcclxuICAgICAgICBcImNoaWxkcmVuc1wiOiBudWxsXHJcbiAgICAgIH0sXHJcbiAgICAgIHtcclxuICAgICAgICBcImlkXCI6IDI2OTgsXHJcbiAgICAgICAgXCJuYW1lXCI6IDQsXHJcbiAgICAgICAgXCJzeXN0ZW1EZXNjXCI6IFwi5bel5L2c54q25oCB77yI6Ieq5a6a5LmJ77yJXCIsXHJcbiAgICAgICAgXCJjaGlsZHJlbnNcIjogbnVsbFxyXG4gICAgICB9XHJcbiAgICBdXHJcbiAgfV0iLCJfbyI6e319)

### Steps to reproduce

1. Default checked all item, change checked and force update v-model data
2. cascader menu will change to first checked node(sometimes we don't hope like this, eg: define a "select_all" child item, when I check it , I will update v-model data for select all children)

### What is Expected?

When I update v-model data , don't sync menu state to first checked node

### What is actually happening?

sync menu state , expand and scroll to first check node menu

### Additional comments

_(empty)_

**Comment by nothing-sy** [comment]
I know the reason, because update v-model data, component updates menu state and expand to first checked node

**Comment by nothing-sy** [comment]
![image](https://github.com/element-plus/element-plus/assets/30278419/986b5891-210e-4383-9455-3fe63f239691)
在拓展一些使用场景的时候，只要我去更新v-model的数据，都会触发`syncMenuState` or `scrollToExpandingNode`， 从而导致面板会滚动到第一个选择的节点，而子面板会展开到第一个选择的节点。

希望在更新v-model的时候，不要有这种强制的行为，否则很多需要更新数据的场景都会有这个问题发生

**Comment by btea** [comment]
@nothing-sy 你好，根据你提供的链接以及说明内容，我还是没有明白你具体的问题是什么。你能完善一下链接里的代码，提供一份更加详细具体的操作步骤说明吗？谢谢。

**Comment by nothing-sy** [comment]
@btea 感谢回复，我看到 [pr](https://github.com/element-plus/element-plus/pull/14806)，这应该能解决我的问题。 是我使用方式和描述有点问题，这个issue我关了
