### ISSUE TITLE
[Component] [input-number] 数字输入框出问题了

### ISSUE THREAD

**Issue by OaimIsGnay** [element-plus/element-plus#15001]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.3`
- Browser / OS: `edge mac14.1`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input-number.html)

### Steps to reproduce

打开官方文档就能看见问题

### What is Expected?

解决bug

### What is actually happening?

解决bug

### Additional comments

打开官方文档就能看见问题

**Comment by OaimIsGnay** [comment]
<img width="825" alt="image" src="https://github.com/element-plus/element-plus/assets/58240619/9078b105-0653-45d9-b168-9e67accd500f">
有点没搞懂。。为什么会变成这样

**Comment by chenxch** [comment]
用无痕模式看下，可能是你的插件影响了。

**Comment by OaimIsGnay** [comment]
> 用无痕模式看下，可能是你的插件影响了。

谢谢您，用无痕就没问题了。

**Comment by AoHe123** [comment]
size 默认就有这个问题， 给size其他的值 就正常了

**Comment by chenxch** [comment]
> size 默认就有这个问题， 给size其他的值 就正常了

可能是你的插件值改了默认size的样式
