### ISSUE TITLE
[Component] [table] el-table    show-overflow-tooltip  在body  transform:scale(1.33333)的情况下，位置偏移，并且tooltip 显示错误

### ISSUE THREAD

**Issue by cjy816618** [element-plus/element-plus#15004]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 110.0.5481.178（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5sZXQgbGlzdDEgPSByZWYoW1xue1xuIFwibmFtZVwiOiBcIuW8oOS4gFwiLFxuICAgICAgICAgICAgXCJnZW5kZXJcIjogXCLnlLdcIixcbiAgICAgICAgICAgIFwibnVtYmVyXCI6IFwiMVwiLFxuICAgICAgICAgICAgXCJyZW1hcmtcIjogXCJYWFhYXCIsXG4gICAgICAgICAgICBcIui6q+S7vVwiOiBcIuiuv+WuolwiLFxuICAgICAgICAgICAgXCJpZGVudGl0eUNhcmRcIjogXCIxMTExMTExMTExMTExMTExMTFcIixcbn1cbl0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwidHJhbnNpdGlvbjogbm9uZXMgMHMgZWFzZSAwcztcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMzMzMzMpO21hcmdpbi1sZWZ0OjIwMHB4O1wiPlxuICA8ZWwtdGFibGVcbiAgICAgICAgICAgICAgXG4gICAgICAgICAgICAgICAgc2hvdy1vdmVyZmxvdy10b29sdGlwXG4gICAgICAgICAgICAgICAgOmRhdGE9XCJsaXN0MVwiXG4gICAgICAgICAgICAgICAgc3R5bGU9XCJ3aWR0aDogNDAwcHhcIlxuICAgICAgICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgICAgICA+XG4gICAgICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibnVtYmVyXCIgbGFiZWw9XCLnvJblj7dcIiB3aWR0aD1cIjQ2cHhcIiAvPlxuICAgICAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIuWnk+WQjVwiIHdpZHRoPVwiNTRweFwiIC8+XG4gICAgICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwi6Lqr5Lu9XCIgbGFiZWw9XCLouqvku71cIiB3aWR0aD1cIjQwcHhcIiAvPlxuICAgICAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkZW50aXR5Q2FyZFwiIGxhYmVsPVwi6K+B5Lu25Y+3XCIgd2lkdGg9XCIxMDRweFwiIC8+XG4gICAgICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZ2VuZGVyXCIgbGFiZWw9XCLmgKfliKtcIiB3aWR0aD1cIjQwcHhcIiAvPlxuICAgICAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInJlbWFya1wiIGxhYmVsPVwi5aSH5rOoXCIgd2lkdGg9XCI0NHB4XCI+XG4gICAgICAgICAgICAgICAgICAgXG4gICAgICAgICAgICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgICAgICAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbiBcbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1.在el-table的上级或者上上级加 transform:scale
2.鼠标放在td上，没有超出隐藏的也会鼠标放上去出现tooltip

### What is Expected?

没有超出隐藏鼠标放上去不会出现tooltip

### What is actually happening?

没有超出隐藏的也会鼠标放上去出现tooltip

### Additional comments

只要是加了缩放，element-plus 组件pop位置都会不正确，希望能够识别到缩放，或者加一个缩放参数，算出准确的位置跟宽度

**Comment by mianlang** [comment]
Similar here. When parent component `zoom: 0.9`, my `el-tooltip` (customed inside a `el-table-column` default template) gets a positional shift.

No zoom:
![image](https://github.com/element-plus/element-plus/assets/7913055/21d59971-e548-4046-b1bd-7e3372472333)
With zoom:
![image](https://github.com/element-plus/element-plus/assets/7913055/7fcb4e46-df23-428a-ac99-af2a26030c3f)
