### ISSUE TITLE
[Component] [tree] 树节点拖拽的树区域外部，树节点的 drop 事件依然触发，然后树的排序就会变化，这种情况如何禁止

### ISSUE THREAD

**Issue by manyuemeiquqi** [element-plus/element-plus#15021]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome/119.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICA6YWxsb3ctZHJvcD1cImFsbG93RHJvcFwiXG4gICAgOmFsbG93LWRyYWc9XCJhbGxvd0RyYWdcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgZHJhZ2dhYmxlXG4gICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgQG5vZGUtZHJhZy1zdGFydD1cImhhbmRsZURyYWdTdGFydFwiXG4gICAgQG5vZGUtZHJhZy1lbnRlcj1cImhhbmRsZURyYWdFbnRlclwiXG4gICAgQG5vZGUtZHJhZy1sZWF2ZT1cImhhbmRsZURyYWdMZWF2ZVwiXG4gICAgQG5vZGUtZHJhZy1vdmVyPVwiaGFuZGxlRHJhZ092ZXJcIlxuICAgIEBub2RlLWRyYWctZW5kPVwiaGFuZGxlRHJhZ0VuZFwiXG4gICAgQG5vZGUtZHJvcD1cImhhbmRsZURyb3BcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcbmltcG9ydCB0eXBlIHsgRHJhZ0V2ZW50cyB9IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL3VzZURyYWdOb2RlJ1xuaW1wb3J0IHR5cGUge1xuICBBbGxvd0Ryb3BUeXBlLFxuICBOb2RlRHJvcFR5cGUsXG59IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL3RyZWUudHlwZSdcblxuY29uc3QgaGFuZGxlRHJhZ1N0YXJ0ID0gKG5vZGU6IE5vZGUsIGV2OiBEcmFnRXZlbnRzKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdkcmFnIHN0YXJ0Jywgbm9kZSlcbn1cbmNvbnN0IGhhbmRsZURyYWdFbnRlciA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVudGVyOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ0xlYXZlID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgbGVhdmU6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnT3ZlciA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCBldjogRHJhZ0V2ZW50cykgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIG92ZXI6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnRW5kID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBkcm9wVHlwZTogTm9kZURyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgZW5kOicsIGRyb3BOb2RlICYmIGRyb3BOb2RlLmxhYmVsLCBkcm9wVHlwZSlcbn1cbmNvbnN0IGhhbmRsZURyb3AgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGRyb3BUeXBlOiBOb2RlRHJvcFR5cGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJvcDonLCBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG59XG5jb25zdCBhbGxvd0Ryb3AgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlLCBkcm9wTm9kZTogTm9kZSwgdHlwZTogQWxsb3dEcm9wVHlwZSkgPT4ge1xuICBpZiAoZHJvcE5vZGUuZGF0YS5sYWJlbCA9PT0gJ0xldmVsIHR3byAzLTEnKSB7XG4gICAgcmV0dXJuIGZhbHNlXG4gIH0gZWxzZSB7XG4gICAgcmV0dXJuIHRydWVcbiAgfVxufVxuY29uc3QgYWxsb3dEcmFnID0gKGRyYWdnaW5nTm9kZTogTm9kZSkgPT4ge1xuICByZXR1cm4gIWRyYWdnaW5nTm9kZS5kYXRhLmxhYmVsLmluY2x1ZGVzKCdMZXZlbCB0aHJlZSAzLTEtMScpXG59XG5cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAyJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

树节点拖放到树区域外部

### What is Expected?

树节点拖放到树区域外部禁止拖放

### What is actually happening?

树节点拖放到树区域外部依然可以拖放，节点顺序发生改变

### Additional comments
![tree1](https://github.com/element-plus/element-plus/assets/54520846/3a51b560-eb83-42f7-ab48-8ac4781cb305)

**Comment by CherishTheYouth** [comment]
这个逻辑应该是没啥问题的，拖拽时有指示线，他会被拖到那个位置，限制拖动范围，那拖拽这个交互就失去意义了。

**Comment by manyuemeiquqi** [comment]
额，这样说也是可以，但是拖拽到其他地方，鼠标的效果已经是禁止拖拽的图标，按我的角度，我会认为拖放到这个地方是禁止的，但是事实上，松开鼠标以后，树节点的顺序发生改变了，这就是感到矛盾的一点。

**Comment by CherishTheYouth** [comment]
> 额，这样说也是可以，但是拖拽到其他地方，鼠标的效果已经是禁止拖拽的图标，按我的角度，我会认为拖放到这个地方是禁止的，但是事实上，松开鼠标以后，树节点的顺序发生改变了，这就是感到矛盾的一点。

应该是你在拖动过程中，所以显示的是一个禁止图标，你看下拖动到外部，然后停止一下，鼠标图标就变成了一个矩形的。
