### ISSUE TITLE
[Bug Report] cascader prop(filterable=true) search data select invalid

### ISSUE THREAD

**Issue by ShiYaFan** [element-plus/element-plus#1503]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/shiyafan/pen/RwojEaz

### Steps to reproduce
cascader
prop(filterable=true) 
input 输入 搜索关键词(b)搜索，列表出现选择列表，选择数据，输入框不更新

### What is Expected?
选择列表，被选中，同时输入框更新

### What is actually happening?
输入框不更新

**Comment by iendeavor** [comment]
It can be solved by define the props in data option, but I don't know why it happens:

```html
<el-cascader ... :props="props" />
```

```typescript
data () {
  return {
    ...,
    props: { multiple: true },
  }
}
```

**Comment by iendeavor** [comment]
If you use vue 3 composition API, it will works too🤔.

change this:
```typescript
data () {
  return {
      options: OPTIONS,
      values: [],
  }
}
```

to:

```typescript
setup () {
  return {
      options: OPTIONS,
      values: [],
  }
}
```
