### ISSUE TITLE
[Docs] [input] input组件文档描述有问题

### ISSUE THREAD

**Issue by msojocs** [element-plus/element-plus#15034]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.0-alpha.3`
- Element Plus Version: `2.4.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Link]()

### Steps to reproduce

1. 打开https://element-plus.org/zh-CN/component/input.html#attributes
2. 查看`autosize`，点击感叹号查看提示

### What is Expected?

描述正确

### What is actually happening?

描述错误
![image](https://github.com/element-plus/element-plus/assets/20937135/309cc101-ff15-4b41-92e8-d6258e54a431)

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Thanks for your feedback, the translation has been corrected.
