### ISSUE TITLE
[TypeScript] [date-picker] datePicker modelValue的类型定义不支持数组

### ISSUE THREAD

**Issue by zh925** [element-plus/element-plus#15050]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZGF0ZXMgPSByZWY8c3RyaW5nW10+KFtdKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxlbC1kYXRlLXBpY2tlciB0eXBlPVwiZGF0ZXNcIiB2LW1vZGVsPVwiZGF0ZXNcIj48L2VsLWRhdGUtcGlja2VyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as epVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

// failed
// const dates = ref<string[]>([])

// success
const dates = ref<[string, string]>(['', ''])
</script>

<template>
<el-date-picker type="dates" v-model="dates"></el-date-picker>
</template>
```

### What is Expected?

应该支持string[]的类型定义

### What is actually happening?

typescript检查报错

### Additional comments

_(empty)_

**Comment by lyric-zemin** [comment]
看文档只支持`[string, string]`这样元组的类型

**Comment by zh925** [comment]
> string[] 可能是 [] / [''] / ['', '', '']

type="dates"的情况，类型定义不应该就是string[]么，不是很明白关闭的原因是什么

**Comment by chenxch** [comment]
@lyric-zemin 已经和你说了问题所在，要了解一下ts中 Tuple和Array的区别。

**Comment by chenxch** [comment]
> > @lyric-zemin 已经和你说了问题所在，要了解一下ts中 Tuple和Array的区别。
> 
> 但是在type="dates"的情况下，值的长度并不固定，元组是固定的，不对吗

dates确实是多个，你是对的。
