### ISSUE TITLE
[All] element plus support CSP 

### ISSUE THREAD

**Issue by hrmj008** [element-plus/element-plus#15052]
![Screen Shot 2023-12-05 at 5 37 11 PM](https://github.com/element-plus/element-plus/assets/152969695/e7c8d5ec-5341-461c-9424-e304530c800c)
![Screen Shot 2023-12-05 at 5 36 55 PM](https://github.com/element-plus/element-plus/assets/152969695/338a2667-b172-4c39-88c2-279b1296822b)

Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.1`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

adding a csp rule 
  <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'nonce-12345678'" />

element plus throw exception,
see screenshot

### What is Expected?

load style font correctly

### What is actually happening?

throw exception

### Additional comments

_(empty)_

**Comment by ntnyq** [comment]
Maybe you should add a `data:` directive to your CSP rules.
