### ISSUE TITLE
[Bug Report] ElTooltip don't work with tsx and slot

### ISSUE THREAD

**Issue by zhuqingguang** [element-plus/element-plus#1507]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
MacOS Chrome latest version

### Vue version
3.0.5

### Reproduction Link
https://github.com/zhuqingguang/element-plus-bug-repo

### Steps to reproduce
1. download the repo 
2. run `yarn` 
3. run `npm run serve`

### What is Expected?
ElTooltip should work for `slot`

### What is actually happening?
ElTooltip not work for `slot`

```js
export default defineComponent({
  name: 'HelloWorld',
  setup() {
    const formData = reactive({name: 'name'})
    return () => (
      <>
      <ElTooltip content="content"><span>hover me work</span></ElTooltip>
      <ElForm model={formData}>
        <ElFormItem v-slots={{
          label: () => {
            return h(ElTooltip, {
              content: 'content'
            }, h('h3', 'I am in slot and not work'))
          }
        }}></ElFormItem>
      </ElForm>
      {
        h(ElTooltip, {
          content: 'content'
        }, h('h3', 'I am not in slot with `h` and work'))
      }
      </>
    )
  }
});
```

**Comment by Ryan2128** [comment]
This might be a bug of form-item or others bug, the reason of tooltip not show is the `onmouseenter` event not trigger, just like some thing prevent it.

```
h(ElForm, {
      onMouseenter: () => console.log(1111),
      model: this.formData,
    }, { default: () =>h(ElFormItem, {
      onMouseenter: () => console.log(222),
    }, {
      label: () => h('div', { onMouseenter: () => console.log(333) },'I am in slot and not work'),
    }) })
```

`333` will also not be printed.

**Comment by zhuqingguang** [comment]
> This might be a bug of form-item or others bug, the reason of tooltip not show is the `onmouseenter` event not trigger, just like some thing prevent it.
> 
> ```
> h(ElForm, {
>       onMouseenter: () => console.log(1111),
>       model: this.formData,
>     }, { default: () =>h(ElFormItem, {
>       onMouseenter: () => console.log(222),
>     }, {
>       label: () => h('div', { onMouseenter: () => console.log(333) },'I am in slot and not work'),
>     }) })
> ```
> 
> `333` will also not be printed.
👍 yes, I have try and find that the reason is the style of `form-item-label` . Its style is `float: left` and `form-content` is overlay on it.
![image](https://user-images.githubusercontent.com/24694223/110272172-7f5da480-8004-11eb-9b0a-73d22713e99f.png)

Why element-ui not use `flex` but `float` ?
