### ISSUE TITLE
[Component] [select] Select绑定值为对象类型时，控制台无限循环报警

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#15087]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.4.3`
- Browser / OS: ` Chrome 102.0.5005.63 / Windows10`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGNvbnRyb2xGb3JtID0gcmVhY3RpdmUoe1xuICBkaXNQbGF5Rm9ybWF0OiB7IEZvcm1hdDogXCJcIiwgU3R5bGU6IFwiTm9uZVwiIH1cbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tXG4gIDxlbC1zZWxlY3RcbiAgICB2LW1vZGVsPVwiY29udHJvbEZvcm0uZGlzUGxheUZvcm1hdFwiXG4gICAgdmFsdWUta2V5PVwiRm9ybWF0XCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIDp2YWx1ZT1cIntcbiAgICAgICAgRm9ybWF0OiAnJyxcbiAgICAgICAgU3R5bGU6ICdOb25lJ1xuICAgICAgfVwiXG4gICAgICBsYWJlbD1cIuaXoFwiXG4gICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICA6dmFsdWU9XCJ7IEZvcm1hdDogMCwgU3R5bGU6ICdOdW1lcmljJyB9XCJcbiAgICAgIGxhYmVsPVwiRm9ybWF0OiAwLjAwOyBTdHlsZTogTnVtZXJpY1wiXG4gICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICA6dmFsdWU9XCJ7XG4gICAgICAgIEZvcm1hdDogJ3l5eXktTU0tZGQgSEg6bW06c3MnLFxuICAgICAgICBTdHlsZTogJ0RhdGVUaW1lJ1xuICAgICAgfVwiXG4gICAgICBsYWJlbD1cIkZvcm1hdDogeXl5eS1NTS1kZCBISDptbTpzc1wiXG4gICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICA6dmFsdWU9XCJ7IEZvcm1hdDogJ3l5eXktTU0tZGQnLCBTdHlsZTogJ0RhdGVUaW1lJyB9XCJcbiAgICAgIGxhYmVsPVwiRm9ybWF0OiB5eXl5LU1NLWRkXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIDp2YWx1ZT1cIntcbiAgICAgICAgRm9ybWF0OiAneXl5eeW5tE1N5pyIZGTml6UgSEjml7ZtbeWIhnNz56eSJyxcbiAgICAgICAgU3R5bGU6ICdEYXRlVGltZSdcbiAgICAgIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IHl5eXnlubRNTeaciGRk5pelIEhI5pe2bW3liIZzc+enklwiXG4gICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICA6dmFsdWU9XCJ7IEZvcm1hdDogJ3l5eXnlubRNTeaciGRk5pelJywgU3R5bGU6ICdEYXRlVGltZScgfVwiXG4gICAgICBsYWJlbD1cIkZvcm1hdDogeXl5eeW5tE1N5pyIZGTml6VcIlxuICAgIC8+XG4gICAgPGVsLW9wdGlvblxuICAgICAgOnZhbHVlPVwieyBGb3JtYXQ6ICdISDptbTpzcycsIFN0eWxlOiAnRGF0ZVRpbWUnIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IEhIOm1tOnNzXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIDp2YWx1ZT1cInsgRm9ybWF0OiAnSEjml7ZtbeWIhnNz56eSJywgU3R5bGU6ICdEYXRlVGltZScgfVwiXG4gICAgICBsYWJlbD1cIkZvcm1hdDogSEjml7ZtbeWIhnNz56eSXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgLS0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

撤销代码注释运行

### What is Expected?

正常

### What is actually happening?

控制台无限循环报警，导致页面卡死

### Additional comments

_(empty)_

**Comment by CherishTheYouth** [comment]
You might use it in an incorrect way.
Yours Code:
```ts
 :value="{
      Format: '',
      Style: 'None'
    }"
```

Right Way:
```ts
 value="{
      Format: '',
      Style: 'None'
    }"
```
It works well.
Just try it.

你对象都是常量哈，不用加冒号。如果没有疑义，你可以 close 下 issue。

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CherishTheYouth** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGNvbnRyb2xGb3JtID0gcmVhY3RpdmUoe1xuICBkaXNQbGF5Rm9ybWF0OiB7IEZvcm1hdDogXCJcIiwgU3R5bGU6IFwiTm9uZVwiIH1cbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cImNvbnRyb2xGb3JtLmRpc1BsYXlGb3JtYXRcIlxuICAgIHZhbHVlLWtleT1cIkZvcm1hdFwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2YWx1ZT1cIntcbiAgICAgICAgRm9ybWF0OiAnJyxcbiAgICAgICAgU3R5bGU6ICdOb25lJ1xuICAgICAgfVwiXG4gICAgICBsYWJlbD1cIuaXoFwiXG4gICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2YWx1ZT1cInsgRm9ybWF0OiAwLCBTdHlsZTogJ051bWVyaWMnIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IDAuMDA7IFN0eWxlOiBOdW1lcmljXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHZhbHVlPVwie1xuICAgICAgICBGb3JtYXQ6ICd5eXl5LU1NLWRkIEhIOm1tOnNzJyxcbiAgICAgICAgU3R5bGU6ICdEYXRlVGltZSdcbiAgICAgIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IHl5eXktTU0tZGQgSEg6bW06c3NcIlxuICAgIC8+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdmFsdWU9XCJ7IEZvcm1hdDogJ3l5eXktTU0tZGQnLCBTdHlsZTogJ0RhdGVUaW1lJyB9XCJcbiAgICAgIGxhYmVsPVwiRm9ybWF0OiB5eXl5LU1NLWRkXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHZhbHVlPVwie1xuICAgICAgICBGb3JtYXQ6ICd5eXl55bm0TU3mnIhkZOaXpSBISOaXtm1t5YiGc3Pnp5InLFxuICAgICAgICBTdHlsZTogJ0RhdGVUaW1lJ1xuICAgICAgfVwiXG4gICAgICBsYWJlbD1cIkZvcm1hdDogeXl5eeW5tE1N5pyIZGTml6UgSEjml7ZtbeWIhnNz56eSXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHZhbHVlPVwieyBGb3JtYXQ6ICd5eXl55bm0TU3mnIhkZOaXpScsIFN0eWxlOiAnRGF0ZVRpbWUnIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IHl5eXnlubRNTeaciGRk5pelXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHZhbHVlPVwieyBGb3JtYXQ6ICdISDptbTpzcycsIFN0eWxlOiAnRGF0ZVRpbWUnIH1cIlxuICAgICAgbGFiZWw9XCJGb3JtYXQ6IEhIOm1tOnNzXCJcbiAgICAvPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHZhbHVlPVwieyBGb3JtYXQ6ICdISOaXtm1t5YiGc3Pnp5InLCBTdHlsZTogJ0RhdGVUaW1lJyB9XCJcbiAgICAgIGxhYmVsPVwiRm9ybWF0OiBISOaXtm1t5YiGc3Pnp5JcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=
