### ISSUE TITLE
[Component] [row, col] 使用el-row和el-col进行响应式分栏操作会出现元素不显示

### ISSUE THREAD

**Issue by yunyizea** [element-plus/element-plus#15081]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-row`
- `el-col`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJvdyA6Z3V0dGVyPVwiMjBcIj5cbiAgICA8ZWwtY29sIDpsZz1cIjRcIiA6bWQ9XCI1XCIgOnNtPVwiNlwiIDp4bD1cIjNcIiA6eHM9XCIyNFwiPlxuICAgICAgPGRpdiBjbGFzcz1cImdyaWQtY29udGVudCBlcC1iZy1yZWRcIiAvPlxuICAgIDwvZWwtY29sPlxuICAgIDxlbC1jb2wgOmxnPVwiMTZcIiA6bWQ9XCIxNFwiIDpzbT1cIjEyXCIgOnhsPVwiMThcIiA6eHM9XCIwXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiZ3JpZC1jb250ZW50IGVwLWJnLWJsdWVcIiAvPlxuICAgIDwvZWwtY29sPlxuICAgIDxlbC1jb2wgOmxnPVwiNFwiIDptZD1cIjVcIiA6c209XCI2XCIgOnhsPVwiM1wiIDp4cz1cIjBcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJncmlkLWNvbnRlbnQgZXAtYmctZ3JlZW5cIiAvPlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5lbC1yb3cge1xuICBtYXJnaW4tYm90dG9tOiAyMHB4O1xufVxuXG4uZWwtcm93Omxhc3QtY2hpbGQge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuXG4uZWwtY29sIHtcbiAgYm9yZGVyLXJhZGl1czogNHB4O1xufVxuXG4uZ3JpZC1jb250ZW50IHtcbiAgYm9yZGVyLXJhZGl1czogNHB4O1xuICBtaW4taGVpZ2h0OiAzNnB4O1xufVxuXG4uZXAtYmctcmVkIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogcmVkO1xufVxuXG4uZXAtYmctYmx1ZSB7XG4gIGJhY2tncm91bmQtY29sb3I6IGJsdWU7XG59XG5cbi5lcC1iZy1ncmVlbiB7XG4gIGJhY2tncm91bmQtY29sb3I6IGdyZWVuO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-row :gutter="20">
    <el-col :lg="4" :md="5" :sm="6" :xl="3" :xs="24">
      <div class="grid-content ep-bg-red" />
    </el-col>
    <el-col :lg="16" :md="14" :sm="12" :xl="18" :xs="0">
      <div class="grid-content ep-bg-blue" />
    </el-col>
    <el-col :lg="4" :md="5" :sm="6" :xl="3" :xs="0">
      <div class="grid-content ep-bg-green" />
    </el-col>
  </el-row>
</template>

<style>
.el-row {
  margin-bottom: 20px;
}

.el-row:last-child {
  margin-bottom: 0;
}

.el-col {
  border-radius: 4px;
}

.grid-content {
  border-radius: 4px;
  min-height: 36px;
}

.ep-bg-red {
  background-color: red;
}

.ep-bg-blue {
  background-color: blue;
}

.ep-bg-green {
  background-color: green;
}
</style>
```

### What is Expected?

在窗口大小<768px的时候，应需变成一个分栏
在窗口大小>=768px的时候，应需恢复成为三个分栏

### What is actually happening?

在窗口大小<768px的时候，变成一个分栏
但是在=768px的时候只有xs原先≠0的元素被恢复
只有>768px时候（如769px）才恢复成三栏

### Additional comments

_(empty)_

**Comment by yunyizea** [comment]
![image](https://github.com/element-plus/element-plus/assets/59525863/49f86474-eef5-4c3a-ba34-ca7a7797c643)
![image](https://github.com/element-plus/element-plus/assets/59525863/8b081bc1-6095-47fe-97b7-3e563e472750)
![image](https://github.com/element-plus/element-plus/assets/59525863/1829a725-682c-44a4-ad0f-9218b993c65e)
![image](https://github.com/element-plus/element-plus/assets/59525863/11d748b9-8403-44ff-b1f2-97a1d5a9c540)

**Comment by yunyizea** [comment]
@chenxch 谢谢您提交的 pr，但是问题貌似没有解决，试验了您的 pr 后，发现在视窗为 767px 时，会出现 xs=0 的元素被全宽
![image](https://github.com/element-plus/element-plus/assets/59525863/7efc0768-7492-4454-8e76-f2b32f7a9e4f)

**Comment by yunyizea** [comment]
这是在我 demo 中实验的结果，上一条是在 playground 实验的结果
![image](https://github.com/element-plus/element-plus/assets/59525863/30b67ee2-5173-40b7-9742-2fb03e07c14c)
![image](https://github.com/element-plus/element-plus/assets/59525863/e0c245ad-08c2-4de1-aea2-66ce70d5b726)

**Comment by yunyizea** [comment]
![image](https://github.com/element-plus/element-plus/assets/59525863/725f69f2-7a67-4b9f-b7f2-2bba2f4132da)

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJvdz5cbiAgICA8ZWwtY29sIDp4cz1cIjI0XCIgOnNtPVwiNlwiIDptZD1cIjRcIiA6bGc9XCIzXCIgOnhsPVwiMVwiPlxuICAgICAgPGRpdiBjbGFzcz1cImdyaWQtY29udGVudCBlcC1iZy1wdXJwbGVcIj48L2Rpdj5cbiAgICA8L2VsLWNvbD5cbiAgPC9lbC1yb3c+XG4gIDxlbC1yb3c+XG4gICAgPGVsLWNvbCA6eHM9XCIwXCIgOnNtPVwiNlwiIDptZD1cIjRcIiA6bGc9XCIzXCIgOnhsPVwiMVwiPlxuICAgICAgPGRpdiBjbGFzcz1cImdyaWQtY29udGVudCBlcC1iZy1wdXJwbGVcIj48L2Rpdj5cbiAgICA8L2VsLWNvbD5cbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uZWwtY29sIHtcbiAgYm9yZGVyLXJhZGl1czogNHB4O1xufVxuXG4uZ3JpZC1jb250ZW50IHtcbiAgYm9yZGVyLXJhZGl1czogNHB4O1xuICBtaW4taGVpZ2h0OiAzNnB4O1xufVxuXG4uZXAtYmctcHVycGxlIHtcbiAgYmFja2dyb3VuZDogIzk5YTliZjtcbn1cblxuLmVwLWJnLXB1cnBsZS1saWdodCB7XG4gIGJhY2tncm91bmQ6ICNkM2RjZTY7XG59XG48L3N0eWxlPlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNTA4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xNTA4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNTA4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)  我这边看是正常的哦，目前截图无法上传

**Comment by chenxch** [comment]
![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/55e928956f114a248dfdd9df4c2fe8d3~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=2584&h=590&s=134607&e=png&b=9ac0e5)

**Comment by yunyizea** [comment]
@chenxch 
Chrome version: 119.0.6045.200 (正式版本) （64 位） (cohort: Stable) 
![image](https://github.com/element-plus/element-plus/assets/59525863/db2e3b5e-647f-49d5-b898-412a75efbbe9)

**Comment by chenxch** [comment]
你这个像素已经是超过767了哦，正常设备的的宽度都是整数，我认为是没必要再这个上面纠结，如果一定要处理可以自己补一个小数级的媒体查询

**Comment by yunyizea** [comment]
> 你这个像素已经是超过767了哦，正常设备的的宽度都是整数，我认为是没必要再这个上面纠结，如果一定要处理可以自己补一个小数级的媒体查询

参考 [1849832452](https://github.com/element-plus/element-plus/issues/15081#issuecomment-1849832452) 这里的时候，我这里是整数

**Comment by chenxch** [comment]
> 1849832452

https://github.com/element-plus/element-plus/issues/15081#issuecomment-1850288592  这边也是整数哦

**Comment by yunyizea** [comment]
@chenxch 好吧 Chrome 卖我
![image](https://github.com/element-plus/element-plus/assets/59525863/75d5857e-cfb0-42ac-b057-71a08fbcc909)

**Comment by yunyizea** [comment]
@chenxch 非常谢谢你，我想了很多办法解决就是没想到改一下媒体查询，我之前的解决办法是监听 resize

**Comment by yunyizea** [comment]
@chenxch 需要我主动关闭 issues 吗

**Comment by chenxch** [comment]
> @chenxch 非常谢谢你，我想了很多办法解决就是没想到改一下媒体查询，我之前的解决办法是监听 resize

也要感谢你的issue和对pr的及时反馈，帮助我们更好的完善ep，🤝

**Comment by yunyizea** [comment]
> > @chenxch 非常谢谢你，我想了很多办法解决就是没想到改一下媒体查询，我之前的解决办法是监听 resize
> 
> 也要感谢你的issue和对pr的及时反馈，帮助我们更好的完善ep，🤝

嗯嗯 共筑开源社区 共同完善 ep

**Comment by yunyizea** [comment]
> > @chenxch 需要我主动关闭 issues 吗
> 
> 不用哈， pr通过后会自动关闭哦

早点休息 不早了哦

**Comment by chenxch** [comment]
> 早点休息 不早了哦

Good night.
