### ISSUE TITLE
[Component] el-switch in form click exception

### ISSUE THREAD

**Issue by hualin6** [element-plus/element-plus#15096]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome 120.0.6099.71 x64/Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-switch`
- `el-form`
- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html)

### Steps to reproduce

Clicking on the switch component in the form example switches it normally, and clicking on the form name Instant delivery also triggers the click event

点击表单示例中的switch组件，正常切换，点击表单名称Instant delivery也触发了点击事件

### What is Expected?

Clicking on the form name (Instant delivery in the example) does not trigger the toggle.

点击表单名称(示例中Instant delivery)时不触发切换

### What is actually happening?

The switch click event is triggered when the form name (Instant delivery in the example) is clicked.

点击表单名称(示例中Instant delivery)时触发了switch点击事件

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#9752
