### ISSUE TITLE
[Bug Report] When the col component xs~xl of Layout is 0, the component will be completely hidden

### ISSUE THREAD

**Issue by TuiMao233** [element-plus/element-plus#1509]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
window 10

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/9tvur63L/2/

### Steps to reproduce
Set a value in xs~xl to 0

### What is Expected?
Normal display xs〜xl 0~24 layout

### What is actually happening?
When the col component xs~xl of Layout is 0, the component will be completely hidden

![image](https://user-images.githubusercontent.com/49724027/109092096-e9e32a80-7750-11eb-964e-441f5fb73942.png)

The current size is xl, but it is now hidden
![image](https://user-images.githubusercontent.com/49724027/109092174-08e1bc80-7751-11eb-9f59-3846617b4034.png)

**Comment by goodtong** [comment]
@CokeMine  This is a bug
![image](https://user-images.githubusercontent.com/27069899/113715361-009b7a80-971c-11eb-88c3-3efa33e82003.png)

**Comment by CokeMine** [comment]
@goodtong Hi, it seems that the issue has nothing to do with my fix, but I will look at it.

**Comment by goodtong** [comment]
@CokeMine thank you
