### ISSUE TITLE
[Component] 【el-dropdown】下拉菜单在 hover 触发时菜单中有滚动条时，滚动内容后跳转到顶部

### ISSUE THREAD

**Issue by lin52025iq** [element-plus/element-plus#15108]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.5`
- Element Plus Version: `2.4.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-dropdown-menu`
- `el-dropdown-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIHRyaWdnZXJcbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnUgc3R5bGU9XCJtYXgtaGVpZ2h0OiAzMHZoO1wiPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSB2LWZvcj1cImkgaW4gMTAwMFwiIDprZXk9XCJpXCI+e3sgaSB9fTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

进入上面的复现环境，`hover` 到 `Preview` 中的 `trigger` 文字上，出现下拉菜单后滚动菜单中的内容。

### What is Expected?

滚动停止后始终保留在滚动停止时的位置

### What is actually happening?

滚动停止后大概 200ms 左右下拉菜单中回到了顶部

### Additional comments

_(empty)_

**Comment by sjx1995** [comment]
Don't set `style="max-height: 30vh"` in `<el-dropdown-menu>`.

Use `max-height` attribute in `<el-dropdown>` instead of.

```vue
  <el-dropdown max-height="30vh">
    trigger
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item v-for="i in 100" :key="i">{{ i }}</el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
```

**Comment by kangleyunju** [comment]
> Don't set `style="max-height: 30vh"` in `<el-dropdown-menu>`.
> 
> Use `max-height` attribute in `<el-dropdown>` instead of.
> 
> ```
>   <el-dropdown max-height="30vh">
>     trigger
>     <template #dropdown>
>       <el-dropdown-menu>
>         <el-dropdown-item v-for="i in 100" :key="i">{{ i }}</el-dropdown-item>
>       </el-dropdown-menu>
>     </template>
>   </el-dropdown>
> ```



> Don't set `style="max-height: 30vh"` in `<el-dropdown-menu>`.
> 
> Use `max-height` attribute in `<el-dropdown>` instead of.
> 
> ```
>   <el-dropdown max-height="30vh">
>     trigger
>     <template #dropdown>
>       <el-dropdown-menu>
>         <el-dropdown-item v-for="i in 100" :key="i">{{ i }}</el-dropdown-item>
>       </el-dropdown-menu>
>     </template>
>   </el-dropdown>
> ```

牛
