### ISSUE TITLE
[Bug Report] cannot use el-popover with trigger="hover" in Vue 3.0.6

### ISSUE THREAD

**Issue by Caleb-Xu** [element-plus/element-plus#1511]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
edge 88

### Vue version
3.0.6

### Reproduction Link
https://codepen.io/caleb-xu/pen/zYoppML

### Steps to reproduce
hover the button【hover激活】

### What is Expected?
show popover

### What is actually happening?
nothing happen

**Comment by Ryan2128** [comment]
Please roll back the vue version to `3.0.5` first, we are investigating.

**Comment by yinfoyuan** [comment]
#1514

**Comment by Ryan2128** [comment]
Duplicate #1514, I will close this issue.
