### ISSUE TITLE
[Component] [autocomplete] 使用 el-autocomplete 组件时，样式绑定出现不一致

### ISSUE THREAD

**Issue by yunyizea** [element-plus/element-plus#15110]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLWF1dG9jb21wbGV0ZVxuICAgICAgICA6dHJpZ2dlci1vbi1mb2N1cz1cImZhbHNlXCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgIGNsYXNzPVwic2VhcmNoQm94XCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgSW5wdXRcIlxuICAgICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPiBcbmRpdiB7XG4gIGhlaWdodDogNDAwcHg7XG4gIHdpZHRoOiA0MDBweDtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzk5OTtcbn1cblxuLnNlYXJjaEJveCB7XG4gIG1hcmdpbi10b3A6IDIwcHg7XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">

</script>

<template>
  <div>
    <el-autocomplete
        :trigger-on-focus="false"
        clearable
        class="searchBox"
        placeholder="Please Input"
      />
  </div>
</template>

<style scoped> 
div {
  height: 400px;
  width: 400px;
  background-color: #999;
}

.searchBox {
  margin-top: 20px;
}
</style>
```

### What is Expected?

在 style scoped 中编写 el-autocomplete 的 class 样式应该被绑定

### What is actually happening?

在 style scoped 中编写 el-autocomplete 的 class 样式没有被绑定，绑定的是其原本的名字（不带随机 id）

### Additional comments

_(empty)_

**Comment by yunyizea** [comment]
这样方可符合预期，但是作用域就不对了
<img width="1142" alt="image" src="https://github.com/element-plus/element-plus/assets/59525863/1a748ef4-8d87-45cb-a520-25e0ce89f1fa">

**Comment by dadaguai-git** [comment]
请使用深度选择器实现此效果 `::v-deep`
![微信截图_20231211094948](https://github.com/element-plus/element-plus/assets/35138018/9037d57d-e6ce-4509-ad9f-1f67427baa2e)

**Comment by yunyizea** [comment]
> 请使用深度选择器实现此效果 `::v-deep` ![微信截图_20231211094948](https://private-user-images.githubusercontent.com/35138018/289734781-9037d57d-e6ce-4509-ad9f-1f67427baa2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODIzNzgsIm5iZiI6MTcwMjM4MjA3OCwicGF0aCI6Ii8zNTEzODAxOC8yODk3MzQ3ODEtOTAzN2Q1N2QtZTZjZS00NTA5LWFkOWYtMWY2NzQyN2JhYTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDExNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYWFjMzhlMDA1MTY5OGQyNGVhODEyYWQzNzQ5ZmMzNTI2MWVjYWIxYWE0NDk5MmNlOWMxZGUwNjcxOTc3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHmxvQIdcFSIeWpx460Pu0rFPShwfxP75DRcTDOpnRo)

多谢！
