### ISSUE TITLE
[Component] [cascader] :emitPath="false"后，emitPath无效

### ISSUE THREAD

**Issue by ArkG-001** [element-plus/element-plus#15127]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome  120.0.6099.71（正式版本）（64 位）`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZGVwYXJ0bWVudHMgPSByZWYoW1xuICAgIHtcbiAgICAgICAgRGVwdElkOiA2NSxcbiAgICAgICAgRGVwdE5hbWU6IFwi56ef5oi3LUFcIixcbiAgICAgICAgRGVwdERlc2M6IFwi6L+Z6YeM5piv6YOo6Zeo5o+P6L+w5L+h5oGvXCIsXG4gICAgICAgIERlcHRMZWFkZXJOYW1lOiBcIm5hbWUwMDFcIixcbiAgICAgICAgRGVwdExlYWRlcklkOiBcIjlcIixcbiAgICAgICAgQ2hpbGREZXB0OiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgRGVwdElkOiA2NixcbiAgICAgICAgICAgICAgICBEZXB0TmFtZTogXCLnoJTlj5Hpg6hcIixcbiAgICAgICAgICAgICAgICBEZXB0RGVzYzogXCLov5nph4zmmK/pg6jpl6jmj4/ov7Dkv6Hmga9cIixcbiAgICAgICAgICAgICAgICBEZXB0TGVhZGVyTmFtZTogXCJuYW1lMDAxXCIsXG4gICAgICAgICAgICAgICAgRGVwdExlYWRlcklkOiBcIjlcIixcbiAgICAgICAgICAgICAgICBDaGlsZERlcHQ6IFtdXG4gICAgICAgICAgICB9XG4gICAgICAgIF1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgRGVwdElkOiA2NyxcbiAgICAgICAgRGVwdE5hbWU6IFwiWC1tYW7lj5HlsZXln7rph5HkvJpcIixcbiAgICAgICAgRGVwdERlc2M6IFwi6L+Z6YeM5piv6YOo6Zeo5o+P6L+w5L+h5oGvXCIsXG4gICAgICAgIERlcHRMZWFkZXJOYW1lOiBcIm5hbWUwMDFcIixcbiAgICAgICAgRGVwdExlYWRlcklkOiBcIjlcIixcbiAgICAgICAgQ2hpbGREZXB0OiBbXVxuICAgIH1cbl0pXG5jb25zdCBvcmdhbklkID0gcmVmKFtdKVxuXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsOmFueSkgPT4ge1xuICBjb25zb2xlLmxvZyh2YWwsICd2YWwnKVxufVxuPC9zY3JpcHQ+XG5cblxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBvcmdhbklkIH19PC9oMT5cbiAgPGVsLWNhc2NhZGVyXG4gICAgZmlsdGVyYWJsZVxuICAgIDpvcHRpb25zPVwiZGVwYXJ0bWVudHNcIlxuICAgIDpwcm9wcz1cIntcbiAgICAgIGNoZWNrU3RyaWN0bHk6IHRydWUsXG4gICAgICBjaGlsZHJlbjogJ0NoaWxkRGVwdCcsXG4gICAgICBsYWJlbDogJ0RlcHROYW1lJyxcbiAgICAgIHZhbHVlOiAnRGVwdElkJ1xuICAgIH1cIlxuICAgIGNsZWFyYWJsZVxuICAgIHYtbW9kZWw9XCJvcmdhbklkXCJcbiAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICA6ZW1pdFBhdGg9XCJmYWxzZVwiXG4gIC8+XG5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

选择下拉框下 租户-A 层级下的 研发部

### What is Expected?

按照文档，emitPath设置为false后，change事件返回的val应该是最后一个叶节点绑定的value值为 66

### What is actually happening?

emitPath设置为false后无效，没有达到文档描述的目的，val还是[ 65, 66 ]

### Additional comments

_(empty)_

**Comment by dadaguai-git** [comment]
![微信截图_20231211094948](https://github.com/element-plus/element-plus/assets/35138018/af65ba01-d89a-4b95-a2ef-549270a3797b)
请在props 中传递配置参数

**Comment by ArkG-001** [comment]
> ![微信截图_20231211094948](https://private-user-images.githubusercontent.com/35138018/290080293-af65ba01-d89a-4b95-a2ef-549270a3797b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDQyMTcsIm5iZiI6MTcwMjQ0MzkxNywicGF0aCI6Ii8zNTEzODAxOC8yOTAwODAyOTMtYWY2NWJhMDEtZDg5YS00Yjk1LWEyZWYtNTQ5MjcwYTM3OTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA1MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDI5MDRlMDg1MTFkODFkOGVhOWJkN2YxYmY4ZGI4ZTA3NGQwODVkOTkzY2FiYzJmMzJhZmE1NTI1MGNlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHntZnZrLe1QloDTV4MX4jomZtRAPfoPmOZ7bR6OTcM) 请在props中提交参数配置

感谢感谢
