### ISSUE TITLE
[Component] [table] table组件性能问题

### ISSUE THREAD

**Issue by enjoy-wind** [element-plus/element-plus#15122]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Chrome 116.0.5845.96`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

当table组件的pageSize大于300时，就有性能瓶颈.
官方虽然提供了tableV2,但大部分用户都会根据table封装成业务组件，因为模型和功能不一致，基于此当业务遇到瓶颈时，想快速切换变的十分困难.

### What is Expected?

是否在table组件中的table-body类render函数中，增加vue-virtual-scroller组件包裹，并且一个虚拟开关配置项，当开启时
采用虚拟加载。

### What is actually happening?

这里并没有采取优化，从而导致性能瓶颈

### Additional comments

功能需求不知道为什么无法提交

**Comment by warmthsea** [comment]
https://github.com/x-extends/vxe-table

**Comment by enjoy-wind** [comment]
> https://github.com/x-extends/vxe-table

![image](https://github.com/element-plus/element-plus/assets/39360554/205b554d-e568-4019-a701-d628b814c115)
这两个模型不一致
