### ISSUE TITLE
[Component] [table] el-table 数据大于等于10条时，任意列添加fixed属性，table都会出现竖向滚动条。桌面缩放125%、150%都会出现。

### ISSUE THREAD

**Issue by wangyupo** [element-plus/element-plus#15134]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.3`
- Browser / OS: `Firefox/120.0.1`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJzdGF0ZVwiIGxhYmVsPVwiU3RhdGVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY2l0eVwiIGxhYmVsPVwiQ2l0eVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCI2MDBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiWmlwXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQ9XCJyaWdodFwiIGxhYmVsPVwiT3BlcmF0aW9uc1wiIHdpZHRoPVwiMTIwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIDxlbC1idXR0b24gbGluayB0eXBlPVwicHJpbWFyeVwiIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgICAgICAgICA+RGV0YWlsPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBzaXplPVwic21hbGxcIj5FZGl0PC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnY2xpY2snKVxufVxuXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdIb21lJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ09mZmljZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdPZmZpY2UnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnSG9tZScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdPZmZpY2UnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

见Playground

### What is Expected?

fixed属性不影响竖向滚动条显示/隐藏

### What is actually happening?

数据大于等于10条时，任意列添加fixed属性，table都会出现竖向滚动条

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
**I don’t see the vertical scroll bar?**

![image](https://github.com/element-plus/element-plus/assets/45450994/32909d7f-1c49-47ca-8c05-9c75a9214f97)

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/16b9200d-558e-4ecf-8232-c9402498c16c)
未复现

**Comment by wangyupo** [comment]
我是在屏幕大小为14寸笔记本电脑上看，浏览器为火狐，仍然在那个playGround里，我尝试将数据量减半，右侧又出现了滚动条。大家可以尝试修改数据量增加一倍、减少一倍，查看滚动条现象。
![图片](https://github.com/element-plus/element-plus/assets/21337041/6619105f-0455-479c-b804-6d85892fde4b)

**Comment by wangyupo** [comment]
> **I don’t see the vertical scroll bar?**
> 
> ![image](https://private-user-images.githubusercontent.com/45450994/290384211-32909d7f-1c49-47ca-8c05-9c75a9214f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDc5NTcsIm5iZiI6MTcwMjYwNzY1NywicGF0aCI6Ii80NTQ1MDk5NC8yOTAzODQyMTEtMzI5MDlkN2YtMWM0OS00N2NhLThjMDUtOWM3NWE5MjE0Zjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDY5ODNhYTgwZTgwYjM2NDQ0Yjc1ZWI0ZjRjMzQ0YjE0N2ZlMGFjZTllMmQyYzcwMzEyNzgxNGEyYzFmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Bs7IbSS8ri2WYz7_Tyh6HGBcInliKHnmUvWHrbkVe8)

很奇怪，我再点进去也没了，但是我把网页从外接屏幕，挪到14寸笔记本显示器中，将数据量减少一般，滚动条又出现了。

**Comment by chenxch** [comment]
> > **I don’t see the vertical scroll bar?**
> > ![image](https://private-user-images.githubusercontent.com/45450994/290384211-32909d7f-1c49-47ca-8c05-9c75a9214f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDc5NTcsIm5iZiI6MTcwMjYwNzY1NywicGF0aCI6Ii80NTQ1MDk5NC8yOTAzODQyMTEtMzI5MDlkN2YtMWM0OS00N2NhLThjMDUtOWM3NWE5MjE0Zjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDY5ODNhYTgwZTgwYjM2NDQ0Yjc1ZWI0ZjRjMzQ0YjE0N2ZlMGFjZTllMmQyYzcwMzEyNzgxNGEyYzFmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Bs7IbSS8ri2WYz7_Tyh6HGBcInliKHnmUvWHrbkVe8)
> 
> 很奇怪，我再点进去也没了，但是我把网页从外接屏幕，挪到14寸笔记本显示器中，将数据量减少一般，滚动条又出现了。

看看笔记本是否有字体放大

**Comment by wangyupo** [comment]
> ![image](https://private-user-images.githubusercontent.com/23251408/290698113-16b9200d-558e-4ecf-8232-c9402498c16c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDc5NTcsIm5iZiI6MTcwMjYwNzY1NywicGF0aCI6Ii8yMzI1MTQwOC8yOTA2OTgxMTMtMTZiOTIwMGQtNTU4ZS00ZWNmLTgyMzItYzk0MDI0OThjMTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZjVjMjQ1YjMxZGQ5OTY5MmViMjBlZGU1MDEwMTc3MDUyZDgwYzgwZWU1YjJhNDA5YjdjYTZlYWZiMTVkMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3d_qfPze8BXBplz05EjPWCW9G4ksyJiLeVf_CcKyaOI) 未复现

很奇怪，我再点进去也没了，但是我把网页从外接屏幕，挪到14寸笔记本显示器中，将数据量减少一半，滚动条又出现了。你可以尝试将数据量动态减少、增加一倍观察一下滚动条现象，尤其注意网页尺寸，我是在14寸笔记本显示器中复现。

**Comment by wangyupo** [comment]
这是我的桌面缩放与布局

![图片](https://github.com/element-plus/element-plus/assets/21337041/e0db493b-2b24-4f5b-86be-c8e004c52a5f)

**Comment by chenxch** [comment]
> 这是我的桌面缩放与布局
> 
> ![图片](https://private-user-images.githubusercontent.com/21337041/290710759-e0db493b-2b24-4f5b-86be-c8e004c52a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg5MjcsIm5iZiI6MTcwMjYwODYyNywicGF0aCI6Ii8yMTMzNzA0MS8yOTA3MTA3NTktZTBkYjQ5M2ItMmIyNC00ZjViLTg2YmUtYzhlMDA0YzUyYTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YzViNGI2OGNlOWFlMDU3Mjg5MmQ3OWY5ZDJmZmYzMjcxMDY3NGFiZGZhNmMwN2Y2MzcwYzVlMDQ2NjBiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FMHiQdWiTwTu1p3Lot8h7Pw1JN5ueZnfQYPr-k7TlA)

缩放改成100%试试看

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/cfdd6422-07fb-4f8a-91c7-3d1c6cd1f869

删除数据也正常

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/b9cef6de-917c-4ada-96f5-2fb50e610b05

删除也没显示滚动条

**Comment by wangyupo** [comment]
> > 这是我的桌面缩放与布局
> > ![图片](https://private-user-images.githubusercontent.com/21337041/290710759-e0db493b-2b24-4f5b-86be-c8e004c52a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg5MjcsIm5iZiI6MTcwMjYwODYyNywicGF0aCI6Ii8yMTMzNzA0MS8yOTA3MTA3NTktZTBkYjQ5M2ItMmIyNC00ZjViLTg2YmUtYzhlMDA0YzUyYTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YzViNGI2OGNlOWFlMDU3Mjg5MmQ3OWY5ZDJmZmYzMjcxMDY3NGFiZGZhNmMwN2Y2MzcwYzVlMDQ2NjBiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FMHiQdWiTwTu1p3Lot8h7Pw1JN5ueZnfQYPr-k7TlA)
> 
> 缩放改成100%试试看
![2023-12-15-14-10-47](https://github.com/element-plus/element-plus/assets/21337041/2b351190-2569-4ff3-ab20-cb92df8dc012)
这是我缩放成100%后，确实没有这个问题，但是在缩放125%时会出现滚动条。

**Comment by wangyupo** [comment]
> > 这是我的桌面缩放与布局
> > ![图片](https://private-user-images.githubusercontent.com/21337041/290710759-e0db493b-2b24-4f5b-86be-c8e004c52a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg5MjcsIm5iZiI6MTcwMjYwODYyNywicGF0aCI6Ii8yMTMzNzA0MS8yOTA3MTA3NTktZTBkYjQ5M2ItMmIyNC00ZjViLTg2YmUtYzhlMDA0YzUyYTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YzViNGI2OGNlOWFlMDU3Mjg5MmQ3OWY5ZDJmZmYzMjcxMDY3NGFiZGZhNmMwN2Y2MzcwYzVlMDQ2NjBiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FMHiQdWiTwTu1p3Lot8h7Pw1JN5ueZnfQYPr-k7TlA)
> 
> 缩放改成100%试试看
![2023-12-15-14-24-34](https://github.com/element-plus/element-plus/assets/21337041/7ba26531-73ef-40aa-91c0-1baae63f3668)
在我的电脑上，缩放125%、150%，删减、增加1条数据都会出现滚动条，但是100%缩放不会。 1920x1080，14寸笔记本，windows10.

**Comment by chenxch** [comment]
是呀，100%是正常比例，程序内部计算高度也都正常。

**Comment by wangyupo** [comment]
> 缩放会影响到内部计算的高度的准确性

好的，谢谢您的解答。那这个会计划解决吗？因为在我的部分业务中，用户老是提到有两个滚动条，表格内一个，外部一个，滚动起来很困惑。

**Comment by chenxch** [comment]
对于windows的缩放问题近期暂无计划哦。

**Comment by wangyupo** [comment]
> 对于windows的缩放问题近期暂无计划哦。

Fine,thx
