### ISSUE TITLE
[Component] [input-number] Input-number disables scrolling on all parent containers when hovering over .el-input__inner

### ISSUE THREAD

**Issue by Winston-Guess** [element-plus/element-plus#15135]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmNvbnN0IG1zZyA9IHJlZignU2Nyb2xsIGZ1bmN0aW9uYWwgd2hlbiBob3ZlcmluZyBoZXJlIOKchScpO1xuY29uc3QgbnVtYmVyID0gcmVmKG51bGwpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImhlaWdodDogMjAwcHg7IGJhY2tncm91bmQtY29sb3I6IGdyZWVuOyBwYWRkaW5nIDogMTBweCA0MHB4OyBvdmVyZmxvdy15OiBzY3JvbGw7XCI+IFxuICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDUwMHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiBibHVlOyBwYWRkaW5nIDogMTBweCA0MHB4O1wiPiBcbiAgICAgIDxoMT5TY3JvbGwgbWU8L2gxPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gICAgICA8cD5cbiAgICAgICAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtYmVyXCIgcGxhY2Vob2xkZXI9XCJTY3JvbGwgTk9UIGZ1bmN0aW9uYWwgd2hlbiBob3ZlcmluZyBoZXJlIOKdjFwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIi8+XG4gICAgICA8L3A+XG4gICAgICA8cD5cbiAgICAgICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gICAgICA8L3A+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Make a scrollable container and put an el-input-number container inside. Place mouse over element and try to scroll.

### What is Expected?

Container scrolls.

### What is actually happening?

Container cannot scroll.

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/11677

![image](https://github.com/element-plus/element-plus/assets/45450994/3b2570ca-6a2c-4092-a2ff-2e8f7bcdbb43)
