### ISSUE TITLE
[Bug Report] Tooltip not work with Vue 3.0.6

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#1514]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
MacOS 10.15.7  / Chrome

### Vue version
3.0.6

### Reproduction Link
https://codesandbox.io/s/angry-kepler-wn9qv?file=/src/App.vue

### Steps to reproduce
Tooltip not work with Vue 3.0.6

### What is Expected?
Tooltip work with Vue 3.0.6

### What is actually happening?
Tooltip not work with Vue 3.0.6

**Comment by Ryan2128** [comment]
Please roll back the vue version to `3.0.5` first, we are investigating.

**Comment by yinfoyuan** [comment]
# @Ryan2128 

![image](https://user-images.githubusercontent.com/35027364/109250242-4d8a5800-7824-11eb-8a35-07cdc4890f34.png)

Upgrade the Vue version of my local project to 3.0.6 and just change the red arrow part of the code and everything is fine, I don't know

**Comment by Ryan2128** [comment]
The reason is [here](https://github.com/vuejs/vue-next/pull/2847), will fix soon.

**Comment by Ryan2128** [comment]
> # @Ryan2128
> packages\popper\src\renderers\trigger.ts
> 
> ![image](https://user-images.githubusercontent.com/35027364/109250242-4d8a5800-7824-11eb-8a35-07cdc4890f34.png)
> 
> Upgrade the Vue version of my local project to 3.0.6 and just change the red arrow part of the code and everything is fine. I don't know, that's what happens when upgrade

This way's behavior may be right, but this error should not be fixed in this file, will fix this bug soon.
