### ISSUE TITLE
[Component] [menu]  el-menu 自动省略功能的弹窗无法设置popper-class属性，导致弹窗展示样式和其他设置了popper-class的弹窗样式不同

### ISSUE THREAD

**Issue by Cwealth** [element-plus/element-plus#15149]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cIndpZHRoOiA0MDBweFwiPlxuICAgIDxlbC1tZW51XG4gICAgICA6ZGVmYXVsdC1hY3RpdmU9XCJhY3RpdmVJbmRleFwiXG4gICAgICBjbGFzcz1cImVsLW1lbnUtZGVtb1wiXG4gICAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yPVwiIzU0NWM2NFwiXG4gICAgICB0ZXh0LWNvbG9yPVwiI2ZmZlwiXG4gICAgICBhY3RpdmUtdGV4dC1jb2xvcj1cIiNmZmQwNGJcIlxuICAgICAgbWVudS10cmlnZ2VyPVwiY2xpY2tcIlxuICAgID5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+UHJvY2Vzc2luZyBDZW50ZXI8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIiBwb3BwZXItY2xhc3M9XCJteS1zdWItbWVudVwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPldvcmtzcGFjZTI8L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIzXCIgcG9wcGVyLWNsYXNzPVwibXktc3ViLW1lbnVcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5Xb3Jrc3BhY2UzPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjMtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj7nm67moIfpobk8L2VsLW1lbnUtaXRlbT5cbiAgICA8L2VsLW1lbnU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGFjdGl2ZUluZGV4ID0gcmVmKCcxJylcbjwvc2NyaXB0PlxuPHN0eWxlPlxuLm15LXN1Yi1tZW51IC5lbC1tZW51IHtcbiAgLS1lbC1tZW51LWhvdmVyLWJnLWNvbG9yOiByZWQgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击省略号，hover目标项 期望颜色背景为红色，实际显示为黑色，样式与其他不一样，因为无法设置popper-class

### What is Expected?

hover目标项 背景颜色为红色

### What is actually happening?

hover目标项 背景颜色为黑色

### Additional comments

省略号按钮触发的弹窗无法为其设置单独的样式名称，导致样式不可控

**Comment by Cwealth** [comment]
![8edbd825627276c0e683657a9172d8f](https://github.com/element-plus/element-plus/assets/50280059/7a6cdc82-3dc1-44de-b81d-8eca8dd8a426)
![61b4559b20e6ad1517cb5afd6da2f4f](https://github.com/element-plus/element-plus/assets/50280059/88a6fdfd-5b7f-42c2-9728-8cc4ae569a37)
省略号按钮触发的弹窗无法为其设置单独的样式名称，导致样式不可控

**Comment by warmthsea** [comment]
**Temporary solution**

![image](https://github.com/element-plus/element-plus/assets/45450994/051676f4-8d42-4790-8ca3-3a74a2c1316b)

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/issues/15146

**Comment by Cwealth** [comment]
临时解决是有办法 设置全局样式就行了，但是这样会导致这块内容的表现样式只有一种，要是后期项目另一个模块也用到menu组件，希望这个弹窗改变成其他样式，这个问题就无解了

**Comment by zhixiaotong** [comment]
这个问题，和我之前提的那个offset一样的。popper-class在sub-menu上，由于省略出现的menu无法设置导致问题产生。@kooriookami。
1. 可以参照之前的做法，将`menu`添加一个`popper-class`属性，作用于所有的`submenu`弹窗，若`submenu`自己传了`popper-class`，则以后者为准。
2. `menu`增加一个`ellipsisPopperClass`额外控制，效果不如第一个统一。

**Comment by zhixiaotong** [comment]
同时，这些属性也不在省略出现的popper上体现不出来。
![image](https://github.com/element-plus/element-plus/assets/34681550/6514ec59-0354-4ecc-a757-a93c09da562b)
![image](https://github.com/element-plus/element-plus/assets/34681550/44948481-76a4-456d-9bd4-97bf38b91a85)
是否可以将`popper-effect`、`popper-class`、`popper-offset`、`show-timeout`、`hide-timeout`抽取成一个整体的props：`popperOption`，避免menu上增加多余的prop？

**Comment by zhixiaotong** [comment]
> 同时，这些属性也不在省略出现的popper上体现不出来。 ![image](https://private-user-images.githubusercontent.com/34681550/291126587-6514ec59-0354-4ecc-a757-a93c09da562b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjYyMjAsIm5iZiI6MTcwMjg2NTkyMCwicGF0aCI6Ii8zNDY4MTU1MC8yOTExMjY1ODctNjUxNGVjNTktMDM1NC00ZWNjLWE3NTctYTkzYzA5ZGE1NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODZkMmY0YjFhZGYzOTc4OTFhZmYxNjczNGRkNjkzMDhmNTFhZjIyMWM2ZGU5ZDJlYmYzNzAxNWRhYWM3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l2WysPvxslk6FhZnxUpA1CUL1LiQ38HBE_6CYoPJwEo) ![image](https://private-user-images.githubusercontent.com/34681550/291127078-44948481-76a4-456d-9bd4-97bf38b91a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjYyMjAsIm5iZiI6MTcwMjg2NTkyMCwicGF0aCI6Ii8zNDY4MTU1MC8yOTExMjcwNzgtNDQ5NDg0ODEtNzZhNC00NTZkLTliZDQtOTdiZjM4YjkxYTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ODRkYjk2YmZiMDZmZTk4NThiZGNlNGYzMGNkOGEzMzEyN2NiYTdlOGZmZDkwZjdiNmIzYmEzZWMwYjAxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z1CePK3vJq8ejpZHWp7i6cInqW1rU6zl-MAojPWbfac) 是否可以将`popper-effect`、`popper-class`、`popper-offset`、`show-timeout`、`hide-timeout`抽取成一个整体的props：`popperOption`，避免menu上增加多余的prop？

现阶段若抽取成整体，会导致BREAKING CHANGES，感觉还是要多加几个属性在menu上。`antd`的timeout也是放在menu上的，对submenu单独控制timeout意义不大

**Comment by kooriookami** [comment]
单独对submenu控制的意义不大，给menu添加属性控制所有submenu是好方法。

**Comment by zhixiaotong** [comment]
> 单独对submenu控制的意义不大，给menu添加属性控制所有submenu是好方法。

那避免breaking change，先加popper-class、show-timeout、hide-timeout三个属性到menu中，暂时不去掉submenu的show和hide的timeout，但这个我个人觉得意义不大，是否考虑@deprecated？
