### ISSUE TITLE
[Component][el-input] use input-style props to set width and result is very weird

### ISSUE THREAD

**Issue by trcat** [element-plus/element-plus#15141]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgOmlucHV0LXN0eWxlPVwieyB3aWR0aDogJzI0MHB4JyB9XCIgOnN1ZmZpeC1pY29uPVwiU2VhcmNoXCI+XG4gIDwvZWwtaW5wdXQ+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgU2VhcmNoIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. import and use ElInput
2. import element-plus icon, like Search
3. set `input-style` props value as `{ width: '240px' }`
4. set `suffix-icon` props value as `Search`

### What is Expected?

The actual width of ElInput should be 240 px，and no content overflow，include suffix -icon 

### What is actually happening?

The actual width of ElInput box exceeds 240px，suffix-icon is overflow，the content behind ElInput is cover suffix-icon

### Additional comments

why does input-style set both wrapper and input style？

![image](https://github.com/element-plus/element-plus/assets/23648263/93ad9198-fdf0-4e33-bfb8-064fd7a3ecf1)

**Comment by yunchuan123** [comment]
![image](https://github.com/element-plus/element-plus/assets/76022317/e9c1ae4c-1937-4aa8-a346-899b9bf57193)
Just like its name. The "input-style" attribute is specifically for styling the internal input element of 'el-input', not the overall style of the 'el-input' component.

**Comment by trcat** [comment]
Has this issue been fixed ！？

**Comment by btea** [comment]
@trcat Hello, as @yunchuan123  described, `input-style` is only used to set the style of the `input` tag, so I think this is not a problem and does not need to be dealt with.
If you want to meet your needs, maybe just bind style directly or add css style to `.el-input`.

**Comment by trcat** [comment]
> @trcat Hello, as @yunchuan123 described, `input-style` is only used to set the style of the `input` tag, so I think this is not a problem and does not need to be dealt with. If you want to meet your needs, maybe just bind style directly or add css style to `.el-input`.

no，visit the demo please，input-style also set the overall style of el-input，it should only set <input> style

**Comment by btea** [comment]
Well, you are right, there is indeed a problem, I will fix it.
