### ISSUE TITLE
 element-ui theme generator is not available elementUI官网在线主题编辑器不可用

### ISSUE THREAD

**Issue by Cheerwhy** [element-plus/element-plus#15142]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Link](https://element.eleme.cn/#/zh-CN/theme/preview)

### Steps to reproduce

进入页面后，提示服务不可用503

### What is Expected?

服务可用

### What is actually happening?

服务不可用

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
Need Help!

**Comment by chenxch** [comment]
element-ui相关问题还请在相应仓库反馈，这个服务似乎已经停了好几年了。
