### ISSUE TITLE
[Component] [menu] el-menu 自动省略功能的弹窗无法设置popper-class属性，导致弹窗展示样式和其他设置了popper-class的弹窗样式不同

### ISSUE THREAD

**Issue by Cwealth** [element-plus/element-plus#15146]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.4.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cIndpZHRoOiA0MDBweFwiPlxuICAgIDxlbC1tZW51XG4gICAgICA6ZGVmYXVsdC1hY3RpdmU9XCJhY3RpdmVJbmRleFwiXG4gICAgICBjbGFzcz1cImVsLW1lbnUtZGVtb1wiXG4gICAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yPVwiIzU0NWM2NFwiXG4gICAgICB0ZXh0LWNvbG9yPVwiI2ZmZlwiXG4gICAgICBhY3RpdmUtdGV4dC1jb2xvcj1cIiNmZmQwNGJcIlxuICAgICAgbWVudS10cmlnZ2VyPVwiY2xpY2tcIlxuICAgID5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+UHJvY2Vzc2luZyBDZW50ZXI8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIiBwb3BwZXItY2xhc3M9XCJteS1zdWItbWVudVwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPldvcmtzcGFjZTI8L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIzXCIgcG9wcGVyLWNsYXNzPVwibXktc3ViLW1lbnVcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5Xb3Jrc3BhY2UzPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiNFwiIHBvcHBlci1jbGFzcz1cIm15LXN1Yi1tZW51XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+V29ya3NwYWNlNDwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLW1lbnU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGFjdGl2ZUluZGV4ID0gcmVmKCcxJylcbjwvc2NyaXB0PlxuPHN0eWxlPlxuLm15LXN1Yi1tZW51IC5lbC1tZW51IHtcbiAgLS1lbC1tZW51LWhvdmVyLWJnLWNvbG9yOiByZWQgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、点击Workspace2菜单 hover菜单项item one，hover样式为红色
2、点击省略号，hover菜单项 Workspace3，样式与其他不一样，因为无法设置popper-class

### What is Expected?

希望省略号弹窗可以设置popper-class，让弹窗表现和其他设置了popper-class的弹窗表现一致

### What is actually happening?

省略号弹窗无法设置popper-class值导致弹窗样式无法和设置了popper-class属性的弹窗表象一致

### Additional comments

_(empty)_

**Comment by xlcodes** [comment]
<img width="864" alt="image" src="https://github.com/element-plus/element-plus/assets/90412675/83373d02-b754-400d-bec7-0d017bcd009b">

这不是可以实现功能吗？你的期望是Workspace3这个【el-sub-menu】也可以显示红色？

**Comment by Cwealth** [comment]
![微信截图_20231214173234](https://github.com/element-plus/element-plus/assets/50280059/197e3629-b507-48e9-a654-06368f5abb41)
workspace3 那一项的hover无法表现为红色，我蓝圈范围的弹窗无法设置popper-class值，无法为其设置样式

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/issues/15149
