### ISSUE TITLE
[Docs] [All] 我切换成中文文档状态下，按Ctrl+K搜索关键字出来的文档点进去却给我切换到英文文档了

### ISSUE THREAD

**Issue by dong-lufei** [element-plus/element-plus#15147]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.3`
- Browser / OS: `googlechrome: 120.0.6099.71`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/button.html)

### Steps to reproduce

https://element-plus.org/zh-CN/component/button.html 
在此链接里调出搜索，查询 button

### What is Expected?

中文文档

### What is actually happening?

英文文档

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
目前资源有限，algolia只对站点默认语言生成检索索引。
