### ISSUE TITLE
[Style] [text] <el-text> component issue

### ISSUE THREAD

**Issue by VVriter** [element-plus/element-plus#15167]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.4`
- Browser / OS: `Brave`
- Build Tool: `Vite`

### Related Component

- `el-text`

### Reproduction Link

[Link]()

### Steps to reproduce

<el-text>abazazaaza<el-text>

### What is Expected?

the text is not correctly transferred to a new line

### What is actually happening?

the text is not correctly transferred to a new line

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
I can't understand what you described, any demos?

**Comment by VVriter** [comment]
> I can't understand what you described, any demos?

https://vydra.store

**Comment by cuongle-hdwebsoft** [comment]
![CleanShot 2023-12-18 at 17 04 20@2x](https://github.com/element-plus/element-plus/assets/102006695/2b6417e7-ec6f-4ad2-a676-b05433989865)

I guess this is what he actually gets stuck. The word `инновационную` should be the same line, but it breaks down because the library uses `word-break: break-all;` for the text so it shows as above image. If it is correct, it should maybe related to CSS. @VVriter

**Comment by VVriter** [comment]
Yes!

**Comment by cuongle-hdwebsoft** [comment]
Thanks for your information. I don't know what your design looks like but here is my approach. As I mentioned above, `Element Plus` set `word-break` to `break-all`, you can change that default style by using CSS. [Here is example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtY2FyZCBjbGFzcz1cIm9yaWdpbmFsXCI+XG4gICAgICA8ZWwtdGV4dD7QnNGLINC40YHQv9C+0LvRjNC30YPQtdC8INC40L3QvdC+0LLQsNGG0LjQvtC90L3Rg9GOINGB0LjRgdGC0LXQvNGDINC+0L/Qu9Cw0YLRiywg0LrQvtGC0L7RgNCw0Y8g0L/QvtC30LLQvtC70Y/QtdGCINC+0L/Qu9Cw0YLQuNGC0Ywg0YEg0LzQuNC90LjQvNCw0LvRjNC90L7QuSDQutC+0LzQuNGB0YHQuNC10Lkg0YEg0LvRjtCx0L7QuSDRgtC+0YfQutC4INC80LjRgNCwPC9lbC10ZXh0PlxuICAgIDwvZWwtY2FyZD5cblxuICAgIDxici8+XG5cbiAgICA8ZWwtY2FyZCBjbGFzcz1cImZpeGVkXCI+XG4gICAgICA8ZWwtdGV4dD7QnNGLINC40YHQv9C+0LvRjNC30YPQtdC8INC40L3QvdC+0LLQsNGG0LjQvtC90L3Rg9GOINGB0LjRgdGC0LXQvNGDINC+0L/Qu9Cw0YLRiywg0LrQvtGC0L7RgNCw0Y8g0L/QvtC30LLQvtC70Y/QtdGCINC+0L/Qu9Cw0YLQuNGC0Ywg0YEg0LzQuNC90LjQvNCw0LvRjNC90L7QuSDQutC+0LzQuNGB0YHQuNC10Lkg0YEg0LvRjtCx0L7QuSDRgtC+0YfQutC4INC80LjRgNCwPC9lbC10ZXh0PlxuICAgIDwvZWwtY2FyZD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuOmRlZXAoLmVsLWNhcmQpIHtcbiAgd2lkdGg6IDIwMHB4O1xufVxuXG46ZGVlcCguZWwtY2FyZC5maXhlZCAuZWwtdGV4dCkge1xuICB3b3JkLWJyZWFrOiBicmVhay13b3JkO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=). Hope this help

**Comment by kooriookami** [comment]
I know now. We should consider use `overflow-wrap: break-word` rather than word-break.
