### ISSUE TITLE
[Component] [tree] 在el-tree中，开启懒加载和树节点过滤，会出现第一次过滤节点时，过滤后的节点可以展开下级节点

### ISSUE THREAD

**Issue by fjyong** [element-plus/element-plus#15186]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `谷歌`
- Build Tool: `Webpack`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC1pbnB1dCB2LW1vZGVsPVwiZmlsdGVyVGV4dFwiIHBsYWNlaG9sZGVyPVwiRmlsdGVyIGtleXdvcmRcIiAvPlxuICA8ZWwtdHJlZSA6cHJvcHM9XCJwcm9wc1wiIDpsb2FkPVwibG9hZE5vZGVcIiByZWY9XCJ0cmVlUmVmXCIgbGF6eSBzaG93LWNoZWNrYm94IDpmaWx0ZXItbm9kZS1tZXRob2Q9XCJmaWx0ZXJOb2RlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5pbXBvcnQgeyByZWYsIHdhdGNoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxUcmVlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIG5hbWU6IHN0cmluZ1xuICBsZWFmPzogYm9vbGVhblxufVxuY29uc3QgZmlsdGVyVGV4dCA9IHJlZignJylcbmNvbnN0IHRyZWVSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbFRyZWU+PigpXG53YXRjaChmaWx0ZXJUZXh0LCAodmFsKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLmZpbHRlcih2YWwpXG59KVxuXG5jb25zdCBmaWx0ZXJOb2RlID0gKHZhbHVlOiBzdHJpbmcsIGRhdGE6IFRyZWUpID0+IHtcbiAgaWYgKCF2YWx1ZSkgcmV0dXJuIHRydWVcbiAgcmV0dXJuIGRhdGEubmFtZS5pbmNsdWRlcyh2YWx1ZSlcbn1cblxuY29uc3QgcHJvcHMgPSB7XG4gIGxhYmVsOiAnbmFtZScsXG4gIGNoaWxkcmVuOiAnem9uZXMnLFxuICBpc0xlYWY6ICdsZWFmJyxcbn1cblxuY29uc3QgbG9hZE5vZGUgPSAobm9kZTogTm9kZSwgcmVzb2x2ZTogKGRhdGE6IFRyZWVbXSkgPT4gdm9pZCkgPT4ge1xuICBpZiAobm9kZS5sZXZlbCA9PT0gMCkge1xuICAgIHJldHVybiByZXNvbHZlKFt7IG5hbWU6ICdyZWdpb24nIH1dKVxuICB9XG4gIGlmIChub2RlLmxldmVsID4gMSkgcmV0dXJuIHJlc29sdmUoW10pXG5cbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgY29uc3QgZGF0YTogVHJlZVtdID0gW1xuICAgICAge1xuICAgICAgICBuYW1lOiAnbGVhZicsXG4gICAgICAgIGxlYWY6IHRydWUsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnem9uZScsXG4gICAgICB9LFxuICAgIF1cblxuICAgIHJlc29sdmUoZGF0YSlcbiAgfSwgNTAwKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

el-tree中，开启懒加载和树节点过滤，第一次过滤节点

### What is Expected?

第一次过滤节点，过滤的节点是不能展开下级节点的

### What is actually happening?

第一次过滤节点，过滤的节点是可以展开下级节点

### Additional comments

_(empty)_

**Comment by btea** [comment]
@fjyong Hello, can you provide more detailed steps to explain the problem?

**Comment by fjyong** [comment]
> @fjyong Hello, can you provide more detailed steps to explain the problem?


https://github.com/element-plus/element-plus/assets/50645312/e08a64d0-3d77-4e35-b3fc-30f72f9daa95


 I uploaded an MP4 file. You can see that nodes can be expanded during the first node search, but not during the second one.

**Comment by btea** [comment]
Based on your description and the video provided, this behavior is normal. 

You can expand the child nodes for the first time because you are dynamically loading the content of the child nodes, and filtering will not be triggered at this time. 

The second time you modify the content of the input box to trigger filtering, because the keyword `re` will only match the node `region` and will not match the content of the child nodes because the expanded child nodes cannot be seen.

**Comment by fjyong** [comment]
Thank you for your answer

**Comment by fjyong** [comment]
Thank you
