### ISSUE TITLE
[Component] [input] el-input 的maxlength 全局配置的优先度高于组件的单独配置

### ISSUE THREAD

**Issue by dang0705** [element-plus/element-plus#15189]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome 100+`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7RWxJbnB1dH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5FbElucHV0LnByb3BzID0ge1xuICAuLi5FbElucHV0LnByb3BzLFxuICBtYXhsZW5ndGg6MTAwXG59XG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiA6bWF4bGVuZ3RoPVwiMTBcIi8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

组件的maxlength无效,无法有效约束字符数量

### What is Expected?

组件配置的优先度应该最高

### What is actually happening?

全局配置优先度高于组件配置

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
```
ElInput.props = {
  ...ElInput.props,
  maxlength:100
}
```
这并不是全局配置的方法。目前input的maxlength是从attrs读取，暂不支持全局默认配置。

**Comment by chenxch** [comment]
这样的写法等于是添加了props.maxlength, 导致原来从attrs读取的maxlength被props取走了，就等于没有设置maxlength，或许应该将maxlength设置为props，内部也从props中获取

**Comment by chenxch** [comment]
input由于涉及属性太多，建议你可以封装一层

**Comment by dang0705** [comment]
问题是，从开发工具上观察，组件单独的 maxlength 已经是明确传入成功，但实际表现却是在内部被某个优先度更高的属性给层叠掉了，我没去看源码，能想象的到是优先级没有取合适的，建议开发组可以看下开发工具

**Comment by dang0705** [comment]
为什么同样是 input 原生属性, placeholder 被定义在props中, 但maxlength却要从$attrs 中取呢, 个人建议应该抹平这种认为的不统一, 毕竟会给用户带来心智负担

**Comment by chenxch** [comment]
> 为什么同样是 input 原生属性, placeholder 被定义在props中, 但maxlength却要从$attrs 中取呢, 个人建议应该抹平这种人为的不统一, 毕竟会给用户带来心智负担

同意，应该将maxlength这种高频使用的属性提取到props中管理。

**Comment by FrontEndDog** [comment]
> 为什么同样是 input 原生属性, placeholder 被定义在props中, 但maxlength却要从$attrs 中取呢, 个人建议应该抹平这种人为的不统一, 毕竟会给用户带来心智负担

同意，在文档中注明的props不应该通过attrs去取，另外我还发现，@dang0705 的那种写法只需要把props换成对象，实际上是有效的。[test](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbElucHV0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5FbElucHV0LnByb3BzID0ge1xuICAuLi5FbElucHV0LnByb3BzLFxuICBwbGFjZWhvbGRlcjogeyB0eXBlOiBTdHJpbmcsIGRlZmF1bHQ6ICflhajlsYDphY3nva7lgLwnIH0sXG59XG5cbmNvbnN0IG1zZyA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgOm1heGxlbmd0aD1cIjEwXCIgcGxhY2Vob2xkZXI9XCLlsYDpg6jkvKDlhaXlgLxcIiAvPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIDptYXhsZW5ndGg9XCIxMFwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by kooriookami** [comment]
我建议Config Provider添加一个props属性，覆盖所有组件props的默认值，类似如下用法：
```vue
<template>
  <el-config-provider :props="props">
    <el-button>中文</el-button>
  </el-config-provider>
</template>

<script lang="ts" setup>
import { reactive } from 'vue'

const props= reactive({
  button: {
    round: {
      default: true
    },
  },
  popover: {
    effect: {
      default: 'dark'
    }
  }
})
</script>
```

**Comment by kooriookami** [comment]
> > 我建议Config Provider添加一个props属性，覆盖所有组件props的默认值，类似如下用法：
> > ```
> > <template>
> >   <el-config-provider :props="props">
> >     <el-button>test</el-button>
> >   </el-config-provider>
> > </template>
> > 
> > <script lang="ts" setup>
> > import { reactive } from 'vue'
> > 
> > const props = reactive({
> >   button: {
> >     round: {
> >       default: true
> >     },
> >   },
> >   popover: {
> >     effect: {
> >       default: 'dark'
> >     }
> >   }
> > })
> > </script>
> > ```
> 
> 你好请问一下这个功能有计划实施吗

讨论没有通过这个方案，可以先提到到discussion里，看看是否有更多人需要这个功能。
