### ISSUE TITLE
[Component] [radio, radio-group] el-radio无法选中

### ISSUE THREAD

**Issue by 2000dzh** [element-plus/element-plus#15191]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.10`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome/120.0.6099.110/ Win64`
- Build Tool: `Vite`

### Related Component

- `el-radio`
- `el-radio-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5cbmNvbnN0IHJhZGlvMSA9IHJlZihudWxsKVxuXG5jb25zdCBsaXN0ID0gcmVmKFxuICBBcnJheS5mcm9tKHsgbGVuZ3RoOiAyIH0sIGZ1bmN0aW9uIChpdGVtLCBpbmRleCkge1xuICAgIHJldHVybiB7XG4gICAgICBuYW1lOiBg5rWL6K+VJHtpbmRleCArIDF9YCxcbiAgICAgIGlkOiBpbmRleCArIDEsXG4gICAgfVxuICB9KSxcbilcblxuXG5cbmNvbnN0IGZuID0gKCkgPT4ge1xuICBjb25zdCBsZW4gPSBsaXN0LnZhbHVlLmxlbmd0aCArIDFcbiAgbGlzdC52YWx1ZS51bnNoaWZ0KHtcbiAgICBuYW1lOiBg5rWL6K+VJHtsZW59YCxcbiAgICBpZDogbGVuLFxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJyYWRpbzFcIj5cbiAgICA8ZGl2IHYtZm9yPVwiKG9iaiwgaW5kZXgpIGluIGxpc3RcIiA6a2V5PVwiaW5kZXhcIj5cbiAgICAgIDxlbC1yYWRpbyA6bGFiZWw9XCJvYmouaWRcIiBzaXplPVwibGFyZ2VcIj57eyBvYmoubmFtZSB9fTwvZWwtcmFkaW8+XG4gICAgPC9kaXY+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiZm5cIj7mt7vliqA8L2VsLWJ1dHRvbj5cblxuICAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

当使用索引作为 key 时,首先选中第一个 radio,然后点击添加按钮在头部新增一条数据此时无法选中新增的 radio

### What is Expected?

可以选中新增的 radio

### What is actually happening?

无法选中新增的 radio

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/2979d70c-0f5b-466c-b471-849221f0ae40

无法复现

**Comment by dadaguai-git** [comment]
> 2023-12-19.10.28.01.mov 
> 无法复现

选中第一个然后进行添加就会复现

**Comment by 2000dzh** [comment]
> 2023-12-19.10.28.01.mov 
> 无法复现

选中第一个点击添加,新增此时无法选中

**Comment by chenxch** [comment]
> > 2023-12-19.10.28.01.mov
> > 无法复现
> 
> 选中第一个点击添加,新增此时无法选中

已复现。

**Comment by Jeffrey-mu** [comment]
key的问题， 因为使用头部添加 index == 0 key没有发生变化，可以使用id作为key 或者使用push 防止这种问题

**Comment by chenxch** [comment]
[vuejs playground](https://play.vuejs.org/#eNp9U81u00AQfpWRhdREBEelNyutKKgHOACiiJMP3drjZNv1rLXeDY0svwCcufMGnBAHnoeKx2Bm7fwIVVWkeGe+b2a/+dkuOW+adB0wyZJFWzjdeGjRhwaMouVpnvg2T85y0nVjnYcOHFYzWKNrtSVQLXDop9HqoXK2hiN2HeUkv8JS68GpUttjOJXYCQVjpnvMaP4bkJwAzp1Tm1TSTDowSEu/yuA59DOoAhVebploj/UMNJV4N4VOooDjfXC0tQBI1ZjB1f3Pr39/fHvSRTI8heP+aral6DIbkoh/9Pby6adsRYl7mRWxyMkUTs+GO0bxKG4pIV0rEzAdFEtCIR0AgdqVrvxkFPifPA7bCRNZbEerZxUsaTEfBsNjYIOrb4zyyBbAotJoSh7YYBlcIpVnl2iw8KCgVpo8kqICoXSWMFvMR47k4ohSr2H9rLKORz2x1zezsa+aovw8gewWNwxGf1wFUbnQ1AQPftMgY3HAQtUlW5wl1aWYUubokKO4YjsOSfNtRqOu0cCgZBVww3d13Ta071m4EIY65yx7qEC6c9CDiF4H73lRXhRGF7ecrSLOdf/r958v3xfzAYxUiT3oZjLjZefBVnqZ3rSW+EXEceVJYetGG3TvGtlAfhDZdtPyRBljP7+JPu8CjlPkmBUWtw/4b1ruYsaH9w5bdGvuyg7zyi2Rey7wxeVbvOPzDqxtGQyzHwE/YGtNEI0D7WWgkmUf8KLa1/Eta1p+bC/ueD3k8e6Exr2L/Dzhh/zqkdL3ck/SkxjH65r0/wB/dnTX)
@Jeffrey-mu  agree

**Comment by 2000dzh** [comment]
> key的问题， 因为使用头部添加 index == 0 key没有发生变化，可以使用id作为key 或者使用push 防止这种问题 @2000dzh 

好的
