### ISSUE TITLE
[Component] [date-picker] el-date-picker第一次点击选择日期，默认显示选择的为当月1号

### ISSUE THREAD

**Issue by EDGQiLin** [element-plus/element-plus#15196]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `谷歌`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html)

### Steps to reproduce

直接点击第一个例子就可以复现了

### What is Expected?

应该就是选择那个日期就显示哪个日期

### What is actually happening?

第一次点击选择日期，默认显示选择的为当月1号

### Additional comments

这很不合理

**Comment by chenxch** [comment]
Related #14748

**Comment by EDGQiLin** [comment]
> Related #14748



> Related #14748

没懂   这是个问题吗   还是说就这样设计的  我更新了最新版本 也是如此

**Comment by chenxch** [comment]
> 没懂 这是个问题吗 还是说就这样设计的 我更新了最新版本 也是如此

是说由于这个修改导致的，2.4.3版本是正常的

**Comment by EDGQiLin** [comment]
> > 没懂 这是个问题吗 还是说就这样设计的 我更新了最新版本 也是如此
> 
> 是说由于这个修改导致的，2.4.3版本是正常的

好的  感谢~

**Comment by MonkeyMaster** [comment]
We had to rollback to 2.4.3 due to this issue
