### ISSUE TITLE
[Bug Report] please transfer a valid prop path to form item!

### ISSUE THREAD

**Issue by gezhigang1005** [element-plus/element-plus#1519]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

### Vue version
3.0.6

### Reproduction Link
https://codepen.io/gezg/pen/bGBLExp

### Steps to reproduce
el-form -> el-table -> el-form-item 结构只要el-form-item中添加prop属性就会报错

### What is Expected?
el-form -> el-table -> el-form-item  能够正常使用，因主子表关系表单大多使用这种方式

### What is actually happening?
只要el-form-item中添加prop属性就会报错
```xml
<el-form :model="form">
    <el-table :data="form.list">
        <template #default="scope">
            <el-form-item :prop="'list.'   scope.$index   '.value'">
                  <el-input v-model="scope.row.value" />
            </el-form-item>
        </template>
    </el-table>
</el-form>
```

**Comment by liushuiyuan001** [comment]
```
  <div v-for="(item,index) in dynamicValidateForm.domains"
    :key="index"  label-width="100px" >
      <el-form-item

    prop="value"
    label="域名"
    :rules="[
      { required: true, message: '请输入邮箱地址', trigger: 'blur' },
      { type: 'email', message: '请输入正确的邮箱地1址', trigger: ['blur', 'change'] }
    ]"
  >
    <el-input v-model="item.value"></el-input>
  </el-form-item>
  </div>
```
至于你说的在table嵌套,没遇到过.你的改成这样可以吗.以上代码验证是可以的. @gezhigang1005

**Comment by Ryan2128** [comment]
cc @justwiner

**Comment by justwiner** [comment]
@gezhigang1005 
Hey! In the next release, this problem will be fixed!

**Comment by gezhigang1005** [comment]
@justwiner   十分感谢，问题已修复了
