### ISSUE TITLE
[Component] [menu] el-menu组件的“click”事件验证失败

### ISSUE THREAD

**Issue by jvhuaiying** [element-plus/element-plus#15209]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.13`
- Element Plus Version: `2.4.4`
- Browser / OS: `@tauri-apps/api: 1.5.2`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBFZGl0UGVuIH0gZnJvbSBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI7XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCBEYXRhYmFzZSBmcm9tIFwidGF1cmktcGx1Z2luLXNxbC1hcGlcIjtcbmNvbnN0IGVtaXQgPSBkZWZpbmVFbWl0cyhbXCJmdW4wXCJdKTtcbmNvbnN0IGxpc3QwID0gcmVmKFtdKTtcbmNvbnN0IGxpc3QxID0gcmVmKFtdKTtcbm9uTW91bnRlZChhc3luYyAoKSA9PiB7XG4gIGNvbnN0IGRiID0gYXdhaXQgRGF0YWJhc2UubG9hZChcInNxbGl0ZTpibG9nZ2luZy5kYlwiKTtcbiAgLy8g6I635Y+W5YWo6YOo55qEVGl0bGVcbiAgY29uc3QgcmVzdWx0ID0gYXdhaXQgZGIuc2VsZWN0KFwic2VsZWN0IFRpdGxlIGZyb20gRGF0YXNcIik7XG4gIGZvciAobGV0IGkgPSAwOyBpIDwgcmVzdWx0Lmxlbmd0aDsgaSsrKSB7XG4gICAgLy8g5Yik5pat5piv5ZCm5ZyobGlzdDDkuK1cbiAgICBpZiAobGlzdDAudmFsdWUuaW5kZXhPZihyZXN1bHRbaV0uVGl0bGUpID09PSAtMSkge1xuICAgICAgbGlzdDAudmFsdWUucHVzaChyZXN1bHRbaV0uVGl0bGUpO1xuICAgICAgbGlzdDEudmFsdWUucHVzaCh7XG4gICAgICAgIGluZGV4OiBpLFxuICAgICAgICB0aXRsZTogcmVzdWx0W2ldLlRpdGxlLFxuICAgICAgfSk7XG4gICAgfVxuICB9XG59KTtcbmNvbnN0IGZ1bjAgPSAoaW5kZXgpID0+IHtcbiAgZW1pdChcImZ1bjBcIiwgbGlzdDEudmFsdWVbaW5kZXhdLnRpdGxlKTtcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXJvdyA6Z3V0dGVyPVwiMFwiIGp1c3RpZnk9XCJjZW50ZXJcIiBhbGlnbj1cIm1pZGRsZVwiPlxuICAgIDxlbC1jb2wgOnNwYW49XCIyNFwiPlxuICAgICAgPGVsLW1lbnUgZGVmYXVsdC1hY3RpdmU9XCIwXCIgQHNlbGVjdD1cImZ1bjBcIj5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdDFcIiA6a2V5PVwiaXRlbS5pbmRleFwiPlxuICAgICAgICAgIDxlbC1pY29uPjxFZGl0UGVuIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPnt7IGl0ZW0udGl0bGUgfX08L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1tZW51PlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

请查看复现环境

### What is Expected?

在点击时调用el-menu组件的select回调

### What is actually happening?

点击菜单无效，[Vue warn]: Invalid event arguments: event validation failed for event "click".

### Additional comments

感谢各位大神！

**Comment by FrontEndDog** [comment]
<el-menu-item>上少了index属性 请参考文档中的示例
