### ISSUE TITLE
[bug report] invalid internationalization of form component

### ISSUE THREAD

**Issue by 1014156094** [element-plus/element-plus#1520]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
360 极速浏览器13.0

### Vue version
3.0.6

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-mi2ig?file=/src/main.js

### Steps to reproduce
1、设置为中文简体
2、使用 Form 组件，表单设置为必填
3、调用 Form 组件 validate 方法校验，出现必填提示是英文的，应该为中文简体才对
这是错误的
![image](https://user-images.githubusercontent.com/16074662/109247985-e79bd180-781f-11eb-8f39-57f8fe93d8a8.png)
这是正确的，分页组件和日期组件则正常为简体中文
![image](https://user-images.githubusercontent.com/16074662/109248974-cb009900-7821-11eb-9598-33f2890d1f24.png)

不知道为什么 codesandbox 里面复现国际化无效全都是英文

### What is Expected?
设置为中文简体应该为中文简体才对

### What is actually happening?
设置为中文简体，Form 组件出现必填提示是英文的，应该为中文简体才对

**Comment by liushuiyuan001** [comment]
我认为:自定义message根据语言配置可解决. 因为form-item的prop是自定义的无法进行翻译.而且组件内解决的话可配置不高.
