### ISSUE TITLE
[Component] [date-picker] el-date-picker在第一次打开选中日期的时候，会默认选中当前月的1号时间

### ISSUE THREAD

**Issue by FJXiongZY** [element-plus/element-plus#15222]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.4.4`
- Browser / OS: `Chrome/98.0.4758.102 `
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html#%E6%BA%90%E4%BB%A3%E7%A0%81)

### Steps to reproduce

el-date-picker在第一次打开选中日期的时候，点击其他日期(20号)，会默认选中当前月的1号时间

### What is Expected?

el-date-picker在第一次打开选中日期的时候，点击其他日期(例如20号)，期望得到的是选中了20号，而不是选中了1号

### What is actually happening?

选中了1号

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
duplicate of #15196

**Comment by btea** [comment]
fixed by #15197
