### ISSUE TITLE
[Component] [menu, menu-item] Menu组件问题

### ISSUE THREAD

**Issue by Aurora-Tsuki** [element-plus/element-plus#15229]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.0`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiIDpkZWZhdWx0LWFjdGl2ZT1cImFjdGl2ZU1lbnVcIiA6cm91dGVyPVwidHJ1ZVwiIFxuICAgIGJhY2tncm91bmQtY29sb3I9XCIjNTQ1YzY0XCIgdGV4dC1jb2xvcj1cIiNmZmZcIiBhY3RpdmUtdGV4dC1jb2xvcj1cIiNmZmQwNGJcIiBjbGFzcz1cIm1lbnVcIj5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSA6aW5kZXg9XCJwYXRoLmhvbWVcIj7pppbpobU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiY291cnNlXCIgY2xhc3M9XCJzdWJtZW51XCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPuivvueoi+euoeeQhjwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cInBhdGgucHVibGljXCI+6K++56iL5Y+R5biDPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cInBhdGguY2hlY2tcIj7or77nqIvmn6XnnIs8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwicGVvcGxlXCIgY2xhc3M9XCJzdWJtZW51XCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPuS6uuWRmOeuoeeQhjwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cInBhdGgudGVhY2hlclwiPuaVmeW4iOeuoeeQhjwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSA6aW5kZXg9XCJwYXRoLnN0dWRlbnRcIj7lrabnlJ/nrqHnkIY8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgXG4gICAgPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cblxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJqc1wiPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5cbiAgICBjb25zdCBwYXRoID0gcmVhY3RpdmUoe1xuICAgICAgICBob21lOiAnL2FkbWluL2hvbWUnLFxuICAgICAgICBwdWJsaWM6ICcvYWRtaW4vY291cnNlL3B1YmxpYycsXG4gICAgICAgIGNoZWNrOiAnL2FkbWluL2NvdXJzZS9jaGVjaycsXG4gICAgICAgIHRlYWNoZXI6ICcvYWRtaW4vbWFuYWdlL3RlYWNoZXInLFxuICAgICAgICBzdHVkZW50OiAnL2FkbWluL21hbmFnZS9zdHVkZW50JyxcbiAgICB9KTtcbiAgICBjb25zdCBhY3RpdmVNZW51ID0gcmVmKHBhdGguaG9tZSk7XG48L3NjcmlwdD5cblxuXG48c3R5bGUgbGFuZz1cInNjc3NcIiBzY29wZWQ+XG4gICAgLm1lbnUge1xuICAgICAgICB3aWR0aDogMTAwJTtcbiAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAgLy8gZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gICAgICAgIC8vIGZvbnQtc2l6ZTogNjBweFxuICAgICAgICAvLyBtYXJnaW4tYm90dG9tOiA1MHB4O1xuICAgICAgICAuc3VibWVudSB7XG4gICAgICAgICAgICA6ZGVlcCguZWwtc3ViLW1lbnVfX3RpdGxlKSB7XG4gICAgICAgICAgICAgICAgZm9udC1zaXplOiBsYXJnZXI7XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9XG4gICAgLmVsLW1lbnUtaXRlbXtcbiAgICAgICAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogbGFyZ2VyO1xuICAgICAgICB9XG4gICAgXG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

我在el-menu中设定了默认激活的菜单item，并且其中一个菜单选项是sub-menu时，我点击这个子菜单中的一个选项，然后刷新页面，这时我页面还是子菜单中的选项页，但是我激活的菜单变成了默认的

### What is Expected?

激活的菜单也是子菜单页

### What is actually happening?

变成了默认的选项

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
首次加载你应该要自己维护default-active哦
