### ISSUE TITLE
[Component] [message] Message自定义图标后type失效

### ISSUE THREAD

**Issue by 123sdfa** [element-plus/element-plus#15230]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.3.14`
- Browser / OS: `Chrome/120.0.0.0 Windows11`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiA6cGxhaW49XCJ0cnVlXCIgQGNsaWNrPVwib3BlbjVcIj5jaGFuZ2U8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBtYXJrUmF3IH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRGVsZXRlIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG9wZW41ID0gKCkgPT4ge1xuICBFbE1lc3NhZ2Uoe1xuICAgICAgICAgIG1lc3NhZ2U6ICd0ZXN0JyxcbiAgICAgICAgICB0eXBlOiAnZXJyb3InLFxuICAgICAgICAgIHNob3dDbG9zZTogdHJ1ZSxcbiAgICAgICAgICBpY29uOiBtYXJrUmF3KERlbGV0ZSlcbiAgICAgICAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<template>
  <el-button :plain="true" @click="open5">change</el-button>
</template>

<script lang="ts" setup>
import { ElMessage } from 'element-plus'
import { markRaw } from 'vue'
import { Delete } from '@element-plus/icons-vue'

const open5 = () => {
  ElMessage({
          message: 'test',
          type: 'error',
          showClose: true,
          icon: markRaw(Delete)
        })
}
</script>

### What is Expected?

图标变成Delete，样式变成error

### What is actually happening?

图标变成Delete，样式error失效

### Additional comments

_(empty)_

**Comment by betavs** [comment]
https://github.com/element-plus/element-plus/blob/62206bb0c0ce1a024b67382bd3180ba3cd0c4e79/packages/components/message/src/message.vue#L13

It seems that's just how design is.

**Comment by 123sdfa** [comment]
OK, thanks

**Comment by 123sdfa** [comment]
> https://github.com/element-plus/element-plus/blob/62206bb0c0ce1a024b67382bd3180ba3cd0c4e79/packages/components/message/src/message.vue#L13
> 
> It seems that's just how design is.

OK, thanks

**Comment by makedopamine** [comment]
> It seems that's just how design is.

I think it makes more sense to remove the operand `!icon` .🤔

**Comment by betavs** [comment]
> I think it makes more sense to remove the operand `!icon` .🤔

@chenxch  I also think so, what about you?

**Comment by chenxch** [comment]
> > I think it makes more sense to remove the operand `!icon` .🤔
> 
> @chenxch I also think so, what about you?

I also think that the icon should not be put here for judgment. I searched the code and found that it was judged like this from the beginning. I don’t understand the reason. But from a usage perspective, I think that when I want to use a custom icon in a certain type, this should be satisfied.
cc @element-plus/backers WDYT?
