### ISSUE TITLE
[Component] [icon] elementplus 图标无法显示

### ISSUE THREAD

**Issue by fengjianying** [element-plus/element-plus#15232]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-beta.4`
- Element Plus Version: `2.4.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[CodePen](https://codepen.io/pen)

### Steps to reproduce

直接通过设置类名为 el-icon-search 无法正常显示

### What is Expected?

正常显示图标

### What is actually happening?

没有显示图标

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
Element Plus已经移除了iconfont

**Comment by btea** [comment]
@fengjianying Please refer to the official website for [instructions](https://element-plus.org/zh-CN/component/icon.html#icon-collection). I will close this question, if you have other questions you can add comments.
