### ISSUE TITLE
[Component] [image-viewer] el-image-viewer 组件 一个页面写多个会出现 ”超过组件基转换的最大递归更新“ 警告

### ISSUE THREAD

**Issue by jiahui336** [element-plus/element-plus#15234]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.4.3`
- Browser / OS: `macOs`
- Build Tool: `Vite`

### Related Component

- `el-image-viewer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1pbWFnZS12aWV3ZXI+PC9lbC1pbWFnZS12aWV3ZXI+XG4gIDxlbC1pbWFnZS12aWV3ZXI+PC9lbC1pbWFnZS12aWV3ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<template>
	<el-image-viewer></el-image-viewer>
<el-image-viewer></el-image-viewer>
</template>

### What is Expected?

不会出现警告

### What is actually happening?

出现警告

### Additional comments

给个解决方案 ，我想把这个组件封装到指令里面

**Comment by Fuphoenixes** [comment]
@kooriookami See see

**Comment by TryChai** [comment]
这个解决了吗 我也遇到一个预览的问题，打包过后 ，点击页面会卡死

**Comment by TryChai** [comment]
![image](https://github.com/element-plus/element-plus/assets/30064871/413a2a8d-1709-40f6-9334-20906930f78d)

**Comment by TryChai** [comment]
@kooriookami can you help me ?

**Comment by TryChai** [comment]
@Fuphoenixes 本地复现不了 要线上才会出现 我项目比较大 我现在也不知道是不是有其他地方影响了，有2个地方用了预览的组件都会 卡死 ，好像是我 把方法放到pina 之后出现的

**Comment by ironhideee** [comment]
> 这个解决了吗 我也遇到一个预览的问题，打包过后 ，点击页面会卡死

我也遇到了类似的问题，本地服务正常的，到了线上点击预览就卡死

**Comment by TryChai** [comment]
> > 这个解决了吗 我也遇到一个预览的问题，打包过后 ，点击页面会卡死
> 
> 我也遇到了类似的问题，本地服务正常的，到了线上点击预览就卡死

你怎么解决的呢

**Comment by ironhideee** [comment]
> > > 这个解决了吗 我也遇到一个预览的问题，打包过后 ，点击页面会卡死
> > 
> > 
> > 我也遇到了类似的问题，本地服务正常的，到了线上点击预览就卡死
> 
> 你怎么解决的呢

加了这个两个属性就可以了
![image](https://github.com/element-plus/element-plus/assets/41133802/cb6cdc45-8ab1-479f-9509-27a060fc0c1e)

**Comment by Fuphoenixes** [comment]
@TryChai 提供下 element-plus和vue的版本，都是最新版吗？

**Comment by TryChai** [comment]
不是  我的版本是2.3.1的 ，早上想升级到最新版 但是 那个国际化报错了 放弃了

**Comment by TryChai** [comment]
> > > > 这个解决了吗 我也遇到一个预览的问题，打包过后 ，点击页面会卡死
> > > 
> > > 
> > > 我也遇到了类似的问题，本地服务正常的，到了线上点击预览就卡死
> > 
> > 
> > 你怎么解决的呢
> 
> 加了这个两个属性就可以了 ![image](https://private-user-images.githubusercontent.com/41133802/299190749-cb6cdc45-8ab1-479f-9509-27a060fc0c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzMwNzgsIm5iZiI6MTcwNjA3Mjc3OCwicGF0aCI6Ii80MTEzMzgwMi8yOTkxOTA3NDktY2I2Y2RjNDUtOGFiMS00NzlmLTk1MDktMjdhMDYwZmMwYzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMzFkZmE1NWRhZmY3M2RmYWRkMjJlMTM2MmU5OGRhNWVkNmFlMzA2ZWVmM2ZmZjJlODc4NzVhZjVjMGIyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z3awoFYGovDCYKapP-jZKzlGHmebA9nadOtjmKVm3so)

非常非常感谢

**Comment by Fuphoenixes** [comment]
> 不是 我的版本是2.3.1的 ，早上想升级到最新版 但是 那个国际化报错了 放弃了

好的，这个问题是在2.5.2版本修复的

**Comment by TryChai** [comment]
我想升级 但是国际化那个报错怎么弄呢

**Comment by TryChai** [comment]
No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

**Comment by kooriookami** [comment]
You can use `element-plus/es/locale/lang/zh-cn`

**Comment by TryChai** [comment]
> You can use `element-plus/es/locale/lang/zh-cn`

我修改了但 还是报错 
![image](https://github.com/element-plus/element-plus/assets/30064871/e42f089f-58cb-4108-851f-28cf02d9e483)

**Comment by kooriookami** [comment]
Use this `import zhCn from 'element-plus/dist/locale/zh-cn.mjs'`, it could be the the type of `mjs`.

**Comment by TryChai** [comment]
> import zhCn from 'element-plus/dist/locale/zh-cn.mjs'

还是不行
![image](https://github.com/element-plus/element-plus/assets/30064871/c677f719-0b08-4211-beb6-c102feb3c3b6)

**Comment by kooriookami** [comment]
呃 我怎么不知道2.5.2改了这个。。

**Comment by Xavier9896** [comment]
> 加了这个两个属性就可以了 ![image](https://private-user-images.githubusercontent.com/41133802/299190749-cb6cdc45-8ab1-479f-9509-27a060fc0c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzAxMDcsIm5iZiI6MTcwNjI2OTgwNywicGF0aCI6Ii80MTEzMzgwMi8yOTkxOTA3NDktY2I2Y2RjNDUtOGFiMS00NzlmLTk1MDktMjdhMDYwZmMwYzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDExNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjc1Y2YzYzdjOTc5NTM4MzI2NGJkYWExOTE2MjBjMmQxMmJmODhlMjA1NDAzNjEzZDQ0YTJhYWM5YjA5ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IbtAZ2C8Cq7DxNVFuU401uof3oUhW9aQ0RzsDoZWp_g)

Nice! 帮了大忙了！版本固定了，后面版本有兼容问题，这两个小属性就解决问题了！
