### ISSUE TITLE
[Component] [select, config-provider] 在多个el-config-provider 中使用el-select项目报错

### ISSUE THREAD

**Issue by javie5** [element-plus/element-plus#15245]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.3`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHQgPSByZWYoJycpO1xuY29uc3QgdDEgPSByZWYoJycpO1xuY29uc3QgbXNnID0gcmVmKCflnKjlpJrkuKplbC1jb25maWctcHJvdmlkZXIg5Lit5L2/55SoZWwtc2VsZWN0O+mhueebruWHuueOsOW8guW4uCcpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA+XG4gICAgbmFtZXNwYWNlPVwicGxhdGZvcm1cIiBcbiAgICA8ZWwtc2VsZWN0IHBsYWNlaG9sZGVyPVwi6K+36YCJ5oupXCIgdi1tb2RlbD1cInRcIj5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLpgInpobkxXCIgdmFsdWU9XCLpgInpobkxXCI+PC9lbC1vcHRpb24+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICA8aHIgLz5cbiAgPEVsQ29uZmlnUHJvdmlkZXIgbmFtZXNwYWNlPVwicGxhdGZvcm1cIj5cbiAgICBuYW1lc3BhY2U9XCJlbFwiIFxuICAgIDxlbC1zZWxlY3QgcGxhY2Vob2xkZXI9XCLor7fpgInmi6lcIiB2LW1vZGVsPVwidDFcIj5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLpgInpobkxXCIgdmFsdWU9XCLpgInpobkxXCI+PC9lbC1vcHRpb24+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvRWxDb25maWdQcm92aWRlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

直接打开链接即可

项目入口文件:main.js
```js
import ElementPlus from "element-plus";
// import "./element-plus-platform.css"; //提前编译好的namespace为platform的样式文件,不引入也会报错,引入只是为了正常显示namespace为platform的el-select组件
import "element-plus/dist/index.css";
import App from "./bug.select&provider.vue";
import { createApp } from "vue";
let app = createApp(App);
app.use(ElementPlus);
window.app = app.mount("#app");

```
异常组件:bug.select&provider.vue

```vue
<template>
  <el-config-provider namespace="platform">
    namespace="platform" 的下拉选择
    <el-select placeholder="请选择" v-model="t">
      <el-option label="选项1" value="选项1"></el-option>
    </el-select>
  </el-config-provider>
  <hr />
  <ElConfigProvider>
    namespace="el" 的下拉选择
    <el-select placeholder="请选择" v-model="t1">
      <el-option label="选项1" value="选项1"></el-option>
    </el-select>
  </ElConfigProvider>
</template>
<script>
export default {
  data() {
    return { t: null, t1: null };
  }
};
</script>
<style>
:root {
  --platform-border-color: red;
}
</style>
```

### What is Expected?

正常运行不报错

### What is actually happening?

项目异常

### Additional comments

element-plus版本大于等于2.2.30都会报错;s首先先出现异常告警信息;然后项目直接报错;
整个项目代码在复现步骤内

**Comment by mrdonkey3** [comment]
我也遇到类似问题，用qiankun来搭微应用，在主应用的element-plus namespace为ep（避免和子应用element-ui的样式污染），子应用的namespace默认el，使用npm包的引入方式可以正常使用，但是当我想通过cdn复用公共依赖（vue、vue-router、element-plus等），就会报错Uncaught (in promise): Cannot read properties of null (reading 'emitsOptions')的错误，经测试element-plus大于3.2.22，使用cdn方式引入存在多个不同的namespace就会报错，如果namespace一致就正常

**Comment by javie5** [comment]
好几个月了,没人理, @element-plus

**Comment by javie5** [comment]
@sxzz 可以帮忙跟进下这个问题单吗

**Comment by baiyuze** [comment]
根本没有人理这种问题
另外，就是这个问题是vue版本升级后，这个element-plus没有适配低版本的vue导致的，低版本的vue难道都不配使用这个框架吗？

**Comment by warmthsea** [comment]
> 我也遇到类似问题，用qiankun来搭微应用，在主应用的element-plus namespace为ep（避免和子应用element-ui的样式污染），子应用的namespace默认el，使用npm包的引入方式可以正常使用，但是当我想通过cdn复用公共依赖（vue、vue-router、element-plus等），就会报错Uncaught (in promise): Cannot read properties of null (reading 'emitsOptions')的错误，经测试element-plus大于3.2.22，使用cdn方式引入存在多个不同的namespace就会报错，如果namespace一致就正常


相关： https://github.com/element-plus/element-plus/issues/17710#issuecomment-2259636904

**Comment by tolking** [comment]
Fixed by #18121
