### ISSUE TITLE
[Component] [date-picker] 官网案例也有这个问题。日期时间选择器，最新版本里，默认值如果是空，type是 datetime的话 随便选择 第一次都会跳到1号。

### ISSUE THREAD

**Issue by kingeleven** [element-plus/element-plus#15247]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-beta.4`
- Element Plus Version: `2.4.4`
- Browser / OS: `所有浏览器/win10`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E7%82%B9)

### Steps to reproduce

点击https://element-plus.org/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E7%82%B9
这个链接  第一个示例

### What is Expected?

选择几号就是几号

### What is actually happening?

第一次选择会跳到1号

### Additional comments

直接官网就能看到错误

**Comment by FrontEndDog** [comment]
fixed by https://github.com/element-plus/element-plus/pull/15197
duplicate of https://github.com/element-plus/element-plus/issues/15196

**Comment by zhixiaotong** [comment]
我想知道新版本何时发布，这个bug影响太大了，这种错误不该发生。

**Comment by FrontEndDog** [comment]
> 我想知道新版本何时发布，这个bug影响太大了，这种错误不该发生。

可以先退回2.4.3版本，新版本涉及到了select-v2的重构和新组件tour，发版周期会长一些，预计在本周发布。

**Comment by zhixiaotong** [comment]
> > 我想知道新版本何时发布，这个bug影响太大了，这种错误不该发生。
> 
> 可以先退回2.4.3版本，新版本涉及到了select-v2的重构和新组件tour，发版周期会长一些，预计在本周发布。

我需要使用`2.4.4`的一些新特性，暂时打了个本地的补丁包用着。我之前看到一个`issue`的负面评价，虽然很激进，不过确实是这种情况，这次例子就是如此。加一个小功能引发了一个大bug的情况，希望尽量避免。
