### ISSUE TITLE
[Component] [input] 关于ElInput滚动条的问题

### ISSUE THREAD

**Issue by Autumn-27** [element-plus/element-plus#15246]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-beta.4`
- Element Plus Version: `2.4.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBFbFJvdywgRWxDb2wsIEVsQ2FyZCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsVGFicyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsVGFiUGFuZSwgRWxJbnB1dCwgRWxMaW5rIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdGV4dGFyZWEgPSByZWYoXG4gICcxMTExMTExMTExMTF4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eDExMTExMTExMTExMXh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eDExMTExMTExMTExMTExMTExeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4MTExMTExMTExMTExMTExMTF4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHgxMTExMTExMTExMTExMTExMXh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eDExMTExMTExMTExMTExMTExeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4MTExMTExMTExMTExMTExMTF4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHgxMTExMTExMTExMTExMTExMXh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eDExMTExeHh4eHh4eHh4eHh4eHh4eHh4eDExMTExJ1xuKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEVsUm93PlxuICAgIDxFbENvbCA6c3Bhbj1cIjZcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJncmlkLWNvbnRlbnQgZXAtYmctcHVycGxlXCI+eHh4eHh4eHh4eHh4eDwvZGl2PlxuICAgIDwvRWxDb2w+XG4gIDwvRWxSb3c+XG4gIDxFbFJvdyA6Z3V0dGVyPVwiMjBcIiBqdXN0aWZ5PVwic3BhY2UtYmV0d2VlblwiPlxuICAgIDxFbENvbCA6c3Bhbj1cIjE2XCIgOm9mZnNldD1cIjRcIj5cbiAgICAgIDxFbENhcmQgc2hhZG93PVwibmV2ZXJcIiBjbGFzcz1cIm1iLTI1cHhcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLWVsLWZpbGwtY29sb3ItbGlnaHQpXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjaGVhZGVyPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJoZWFkZXItY29udGFpbmVyXCIgc3R5bGU9XCJoZWlnaHQ6IDEwJVwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJoZWFkZXItY29udGVudFwiPlxuICAgICAgICAgICAgICA8RWxMaW5rXG4gICAgICAgICAgICAgICAgOnVuZGVybGluZT1cImZhbHNlXCJcbiAgICAgICAgICAgICAgICBocmVmPVwiaHR0cHM6Ly94eHh4eHh4eC50b3BcIlxuICAgICAgICAgICAgICAgIHN0eWxlPVwiY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCJcbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgIGh0dHBzOi8veHh4eHh4LnRvcFxuICAgICAgICAgICAgICA8L0VsTGluaz5cbiAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPEVsUm93IDpndXR0ZXI9XCIyMFwiPlxuICAgICAgICAgIDxFbENvbCA6c3Bhbj1cIjEwXCI+eHh4eHg8L0VsQ29sPlxuICAgICAgICAgIDxFbENvbCA6c3Bhbj1cIjEzXCI+XG4gICAgICAgICAgICA8RWxUYWJzIHR5cGU9XCJib3JkZXItY2FyZFwiPlxuICAgICAgICAgICAgICA8RWxUYWJQYW5lIDpsYWJlbD1cInh4eHhcIj5cbiAgICAgICAgICAgICAgICA8RWxJbnB1dFxuICAgICAgICAgICAgICAgICAgdi1tb2RlbD1cInRleHRhcmVhXCJcbiAgICAgICAgICAgICAgICAgIHR5cGU9XCJ0ZXh0YXJlYVwiXG4gICAgICAgICAgICAgICAgICA6cm93cz1cIjVcIlxuICAgICAgICAgICAgICAgICAgcmVhZG9ubHlcbiAgICAgICAgICAgICAgICAgIGNsYXNzPVwiY3VzdG9tLXNjcm9sbGJhclwiXG4gICAgICAgICAgICAgICAgLz5cbiAgICAgICAgICAgICAgPC9FbFRhYlBhbmU+XG4gICAgICAgICAgICA8L0VsVGFicz5cbiAgICAgICAgICA8L0VsQ29sPlxuICAgICAgICA8L0VsUm93PlxuICAgICAgPC9FbENhcmQ+XG4gICAgPC9FbENvbD5cbiAgPC9FbFJvdz5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtYnV0dG9uIHtcbiAgbWFyZ2luLXRvcDogMTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

以上链接，ElInput的溢出滚动条的样式不是element plus的样式

### What is Expected?

期望ElInput的溢出滚动是element plus的默认样式

### What is actually happening?

ElInput的滚动条没有样式

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
The design is like this, you can customize the scroll bar style globally.

![image](https://github.com/element-plus/element-plus/assets/45450994/b8bea4b4-1082-4366-b98e-e194aa459bb8)
![image](https://github.com/element-plus/element-plus/assets/45450994/a356c530-b5b4-40d1-8bd5-4f62d4b65a52)

**Comment by chenxch** [comment]
There are no plans yet, please refer to @warmthsea  plan.
