### ISSUE TITLE
According to the description of the official website, the language file is loaded through CDN, and the loading Chinese is invalid

### ISSUE THREAD

**Issue by zh1011** [element-plus/element-plus#1524]
![image](https://user-images.githubusercontent.com/41102878/109277534-6dd10b80-7852-11eb-9e58-7bc3a390cb7d.png)
![image](https://user-images.githubusercontent.com/41102878/109277556-7590b000-7852-11eb-9af4-8a327d3c4b21.png)

**Comment by liushuiyuan001** [comment]
ElementPlus.locale(ElementPlus.lang.zhCn) 跟下面初始化的代码放在一起即可
<img width="1022" alt="截屏2021-02-27 下午6 32 19" src="https://user-images.githubusercontent.com/18300599/109384786-36359280-792a-11eb-9e73-ce9559eef32b.png">

**Comment by Reapers702** [comment]
试试加载中文字典
<script src="//unpkg.com/element-plus/lib/umd/locale/zh-cn.js"></script>
