### ISSUE TITLE
[Component] [tab-pane] 使用label插槽时状态不更新

### ISSUE THREAD

**Issue by liaoruikang** [element-plus/element-plus#15244]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-beta.4`
- Element Plus Version: `2.4.4`
- Browser / OS: `Chrome/120.0.6099.110`
- Build Tool: `Vite`

### Related Component

- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IlxuPHRlbXBsYXRlPlxuICA8aDM+cHJvcDwvaDM+XG4gIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgY2xhc3M9XCJkZW1vLXRhYnNcIj5cbiAgICA8ZWwtdGFiLXBhbmUgdi1mb3I9XCIoaXRlbSxpbmRleCkgaW4gdGFibGlzdFwiIDprZXk9XCJpbmRleFwiIDpsYWJlbD1cIml0ZW0udGl0bGVcIj48L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG5cbiAgPGgzPnNsb3Q8L2gzPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCI+XG4gICAgPGVsLXRhYi1wYW5lIHYtZm9yPVwiKGl0ZW0saW5kZXgpIGluIHRhYmxpc3RcIiA6a2V5PVwiaW5kZXhcIj5cbiAgICAgICAgPHRlbXBsYXRlICNsYWJlbD57e2l0ZW0udGl0bGV9fTwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJycpXG5cbmxldCB0YWJzID0gW1xuICB7XG4gICAgdGl0bGU6ICd0YWIxJ1xuICB9LFxuICB7XG4gICAgdGl0bGU6ICd0YWIyJ1xuICB9LFxuICB7XG4gICAgdGl0bGU6ICd0YWIzJ1xuICB9XG5dXG5cbmNvbnN0IHRhYmxpc3QgPSByZWYodGFicyk7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICAgIHRhYnMgPSB0YWJzLm1hcChpdGVtID0+IHtcbiAgICBpdGVtID0gey4uLml0ZW19XG4gICAgaXRlbS50aXRsZSA9ICd0YWInXG4gICAgcmV0dXJuIGl0ZW1cbiAgfSlcbiAgdGFibGlzdC52YWx1ZSA9IHRhYnNcbn0sMTAwMClcblxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

无

### What is Expected?

数据改变后插槽状态更新

### What is actually happening?

数据改变后插槽状态未更新

### Additional comments

_(empty)_

**Comment by Bbbtt04** [comment]
```html
<script lang="ts" setup>
import { nextTick, reactive, ref } from 'vue'
const activeName = ref('')

let tabs = [
  {
    title: 'tab1'
  },
  {
    title: 'tab2'
  },
  {
    title: 'tab3'
  }
]

let tablist = reactive(tabs);

setTimeout(() => {
  tablist.forEach((tab)=>{
    tab.title = "tab"
  })
},1000)

</script>
```
you can try by this way

**Comment by liaoruikang** [comment]
这样是可以的，但在实际业务中tabs是远程获取的，所以要对响应式对象重新赋值

**Comment by Bbbtt04** [comment]
> 这样是可以的，但在实际业务中tabs是远程获取的，所以要对响应式对象重新赋值

其实可以不要用index作为 key 
```HTML
```

**Comment by Bbbtt04** [comment]
> 这样是可以的，但在实际业务中tabs是远程获取的，所以要对响应式对象重新赋值

@liaoruikang 其实可以改变key来保证视图更新
```html
<template>
  <h3>prop</h3>
  <el-tabs v-model="activeName" class="demo-tabs">
    <el-tab-pane v-for="(item,index) in tablist" :key="index" :label="item.title"></el-tab-pane>
  </el-tabs>

  <h3>slot</h3>
  <el-tabs v-model="activeName" class="demo-tabs">
    <el-tab-pane v-for="(item,index) in tablist" :key="item.title">
        <template #label>{{item.title}}</template>
    </el-tab-pane>
  </el-tabs>
</template>
<script lang="ts" setup>
import { nextTick, reactive, ref } from 'vue'
const activeName = ref('')

let tabs = [
  {
    title: 'tab1'
  },
  {
    title: 'tab2'
  },
  {
    title: 'tab3'
  }
]

const tablist = ref(tabs);

setTimeout(() => {
  tablist.value = [
  {
    title: 'tab3'
  },
  {
    title: 'tab4'
  },
  {
    title: 'tab5'
  }
]
},1000)

</script>
```

**Comment by liaoruikang** [comment]
@Bbbtt04  解决了，感谢

**Comment by Bbbtt04** [comment]
我的荣幸😁 @liaoruikang

**Comment by lichencc** [comment]
通过改变key值去重新渲染貌似会导致el-tabpane默认插槽的内容重新渲染

**Comment by shizhihua666** [comment]
> > 这样是可以的，但在实际业务中tabs是远程获取的，所以要对响应式对象重新赋值
> 
> @liaoruikang 其实可以改变key来保证视图更新
> 
> ```
> <template>
>   <h3>prop</h3>
>   <el-tabs v-model="activeName" class="demo-tabs">
>     <el-tab-pane v-for="(item,index) in tablist" :key="index" :label="item.title"></el-tab-pane>
>   </el-tabs>
> 
>   <h3>slot</h3>
>   <el-tabs v-model="activeName" class="demo-tabs">
>     <el-tab-pane v-for="(item,index) in tablist" :key="item.title">
>         <template #label>{{item.title}}</template>
>     </el-tab-pane>
>   </el-tabs>
> </template>
> <script lang="ts" setup>
> import { nextTick, reactive, ref } from 'vue'
> const activeName = ref('')
> 
> let tabs = [
>   {
>     title: 'tab1'
>   },
>   {
>     title: 'tab2'
>   },
>   {
>     title: 'tab3'
>   }
> ]
> 
> const tablist = ref(tabs);
> 
> setTimeout(() => {
>   tablist.value = [
>   {
>     title: 'tab3'
>   },
>   {
>     title: 'tab4'
>   },
>   {
>     title: 'tab5'
>   }
> ]
> },1000)
> 
> </script>
> ```

如果需求是改变tabList的循序，你这种方法就不行了
