### ISSUE TITLE
[Component] [input-number] el-input-number在中文输入法下，去除小数点，再输入小数点，不会显示小数点

### ISSUE THREAD

**Issue by floraHM** [element-plus/element-plus#15258]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 120.0.6099.111`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、确保输入法为中文
2、输入12.34, 移出鼠标,
3、再focus，删除小数点，输入小数点（第一次显示）
4、再删除，然后输入小数点（第二次不显示）

### What is Expected?

第二次小数点正常显示

### What is actually happening?

第二次小数点未显示，切光标移动到下一个数字

### Additional comments

_(empty)_

**Comment by kingdsa** [comment]
![output](https://github.com/element-plus/element-plus/assets/68138383/d7435f58-7fd6-490b-a46d-76d8ec502f54)
你给的链接地址我试了下 没问题啊

**Comment by FrontEndDog** [comment]
Unable to reproduce. Please provide detailed steps or video recording.

**Comment by betavs** [comment]
https://github.com/element-plus/element-plus/assets/34408516/e8fbfeed-c2db-4ce7-b780-6bd2ed789599

经过测试发现第一次输入的是 `.` 而第二次输入的是 `。` 导致输入无效

**Comment by floraHM** [comment]
1、确保输入法为中文（非常重要，在英文下是没有问题的）
2、输入12.34, 移出鼠标,
3、再focus，删除小数点，输入小数点（第一次显示）
4、再删除，然后输入小数点（第二次不显示）

**Comment by floraHM** [comment]
![image](https://github.com/element-plus/element-plus/assets/14357629/fdbcc745-2632-4b2c-8cea-9a7398d04165)
使用的是这个键哈

**Comment by floraHM** [comment]
> Unable to reproduce. Please provide detailed steps or video recording, Thanks. 我也无法重现，请提供一下详细步骤或者录屏，谢谢。
1、确保输入法为中文（非常重要，在英文下是没有问题的）
2、输入12.34, 移出鼠标,
3、再focus，删除小数点，输入小数点（第一次显示）
4、再删除，然后输入小数点（第二次不显示）
![image](https://github.com/element-plus/element-plus/assets/14357629/22de056e-3f3d-40a6-a2a4-7ad91d7a391f)
使用这个按键

**Comment by FrontEndDog** [comment]
> > Unable to reproduce. Please provide detailed steps or video recording, Thanks. 我也无法重现，请提供一下详细步骤或者录屏，谢谢。
> > 1、确保输入法为中文（非常重要，在英文下是没有问题的）
> > 2、输入12.34, 移出鼠标,
> > 3、再focus，删除小数点，输入小数点（第一次显示）
> > 4、再删除，然后输入小数点（第二次不显示）
> > ![image](https://private-user-images.githubusercontent.com/14357629/292735315-22de056e-3f3d-40a6-a2a4-7ad91d7a391f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM2MTYsIm5iZiI6MTcwMzQ5MzMxNiwicGF0aCI6Ii8xNDM1NzYyOS8yOTI3MzUzMTUtMjJkZTA1NmUtM2YzZC00MGE2LWEyYTQtN2FkOTFkN2EzOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YTgzYmM5OGI3ZTdjMGFkNWVjOTllODBkNzgxZDQwNDcxYzZhYTQ4MGI2MGIyMThkOWFlZmU0MjdhYmYwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iib-o_jJ5xFH-V7g4UJ1oFW111gRtng5ciVmnydpWyU)
> > 使用这个按键

这是正常的表现，在中文输入法下，按这个键输入进去的是标点符号`。`而不是小数点`.`，你可以在任意输入框中验证一下。

**Comment by kingdsa** [comment]
@floraHM 我这边也复现了

**Comment by floraHM** [comment]
> > > Unable to reproduce. Please provide detailed steps or video recording, Thanks. 我也无法重现，请提供一下详细步骤或者录屏，谢谢。
> > > 1、确保输入法为中文（非常重要，在英文下是没有问题的）
> > > 2、输入12.34, 移出鼠标,
> > > 3、再focus，删除小数点，输入小数点（第一次显示）
> > > 4、再删除，然后输入小数点（第二次不显示）
> > > ![image](https://private-user-images.githubusercontent.com/14357629/292735315-22de056e-3f3d-40a6-a2a4-7ad91d7a391f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM2MTYsIm5iZiI6MTcwMzQ5MzMxNiwicGF0aCI6Ii8xNDM1NzYyOS8yOTI3MzUzMTUtMjJkZTA1NmUtM2YzZC00MGE2LWEyYTQtN2FkOTFkN2EzOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YTgzYmM5OGI3ZTdjMGFkNWVjOTllODBkNzgxZDQwNDcxYzZhYTQ4MGI2MGIyMThkOWFlZmU0MjdhYmYwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iib-o_jJ5xFH-V7g4UJ1oFW111gRtng5ciVmnydpWyU)
> > > 使用这个按键
> 
> 这是正常的表现，在中文输入法下，按这个键输入进去的是标点符号`。`而不是小数点`.`，你可以在任意输入框中验证一下。

非常感谢您的回复，我在google的搜索框尝试输入一个数字后，再输入`.`，确实是小数点，继续输入就变成了`。`

**Comment by chenxch** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
目前的表现和原生表现一致哈
