### ISSUE TITLE
[Bug Report] select set options and value in the meanwhile,view doesn't update

### ISSUE THREAD

**Issue by siam-ese** [element-plus/element-plus#1526]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
88.0.4324.182

### Vue version
3.0.6

### Reproduction Link
https://codepen.io/siamzz/pen/oNYEWbr

### Steps to reproduce
sync set select value and options

### What is Expected?
view doesn't update

### What is actually happening?
view update

**Comment by Ryan2128** [comment]
Duplicate #1207 

The demo works well in version 3.0.2.

This is a vue bug, the [pr](https://github.com/vuejs/vue-next/pull/3184) was already merged, waiting for the new version of vue.

**Comment by CitizenChaos** [comment]
If you tries to solve this issue. you can do this:
```javascript
handleClick() {
  this.options = [
    {
      value: "选项1",
      label: "黄金糕"
    }
  ];
  this.$nextTick(() => {
    this.value = "选项1";
  });
}
```
