### ISSUE TITLE
[Component] [tree] Tree defaultProps label not working.

### ISSUE THREAD

**Issue by swuqi** [element-plus/element-plus#15278]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.4`
- Browser / OS: `Chrome / Windows`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Link](N/A)

### Steps to reproduce

1. provide tree data in which there is title key.
2. specify title as label in the defaultProps.

### What is Expected?

Tree labels should show text of title.

### What is actually happening?

Tree label is blank.

### Additional comments

It seems that the defaultProps is ignored.

**Comment by btea** [comment]
Please provide a valid reproduction link, the link you provided seems to be invalid.

**Comment by swuqi** [comment]
Thanks @btea for your quick response. It's my mistake. My code shows the labels using the default slot and it picks the key (field) as the label. This is not an issue of the default props setting.
