### ISSUE TITLE
[Component] [watermark, dialog] el-dialog can not display the 'footer' slot with el-watermark

### ISSUE THREAD

**Issue by yoeb** [element-plus/element-plus#15280]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.12`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-watermark`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgb3BlbiA9IHJlZihmYWxzZSk7XG5cbmZ1bmN0aW9uIHNob3dEaWFsb2coKSB7XG4gICBvcGVuLnZhbHVlID0gdHJ1ZTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBpY29uPVwiVmlld1wiIEBjbGljaz1cInNob3dEaWFsb2coKVwiPm9wZW48L2VsLWJ1dHRvbj5cbiAgPGVsLWRpYWxvZyB0aXRsZT1cIlRlc3QgVGl0bGVcIiB2LW1vZGVsPVwib3BlblwiIGNlbnRlciBhcHBlbmQtdG8tYm9keT5cbiAgICA8ZWwtd2F0ZXJtYXJrPlxuICAgICAgPGVsLWZvcm0+XG4gICAgICAgIDxlbC1yb3c+XG4gICAgICAgICAgPGVsLWNvbCA6c3Bhbj1cIjEyXCI+XG4gICAgICAgICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJsYWJlbDFcIj5hYWE8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImxhYmVsMlwiPmJiYjwvZWwtZm9ybS1pdGVtPlxuICAgICAgICAgIDwvZWwtY29sPlxuICAgICAgICA8L2VsLXJvdz5cbiAgICAgIDwvZWwtZm9ybT5cbiAgICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib3BlbiA9IGZhbHNlXCI+QnV0dG9uPC9lbC1idXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXdhdGVybWFyaz5cbiAgIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Just click 'open' button.

### What is Expected?

el-dialog can display the 'footer' slot with <el-watermark>.

### What is actually happening?

el-dialog can not display the 'footer' slot with <el-watermark>.

### Additional comments

el-dialog can display the 'footer' slot without <el-watermark>.

![image](https://github.com/element-plus/element-plus/assets/40932124/13752740-ca02-4268-87da-a8c18464ddd5)
This is using the <el-watermark>.
![image](https://github.com/element-plus/element-plus/assets/40932124/23e22054-6298-4f50-9f09-6558b8684cfb)
And this is not using <el-watermark>.

**Comment by chenxch** [comment]
The slot needs to be uninstalled under the root node to be recognized.

**Comment by yoeb** [comment]
How do I need to change my code? Can I watermark the entire dialog box including the footer?

**Comment by chenxch** [comment]
> How do I need to change my code? Can I watermark the entire dialog box including the footer?

You can write the bottom bar yourself.

**Comment by yoeb** [comment]
> The slot needs to be uninstalled under the root node to be recognized.
Thank you for your answer, but I still don't understand.   Wheater there is a code example.

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgb3BlbiA9IHJlZihmYWxzZSk7XG5cbmZ1bmN0aW9uIHNob3dEaWFsb2coKSB7XG4gICBvcGVuLnZhbHVlID0gdHJ1ZTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8ZWwtYnV0dG9uIGxpbmsgdHlwZT1cInByaW1hcnlcIiBpY29uPVwiVmlld1wiIEBjbGljaz1cInNob3dEaWFsb2coKVwiPm9wZW48L2VsLWJ1dHRvbj5cbiAgPGVsLWRpYWxvZyB0aXRsZT1cIlRlc3QgVGl0bGVcIiB2LW1vZGVsPVwib3BlblwiIGNlbnRlciBhcHBlbmQtdG8tYm9keT5cbiAgICA8ZWwtd2F0ZXJtYXJrPlxuICAgICAgPGVsLWZvcm0+XG4gICAgICAgIDxlbC1yb3c+XG4gICAgICAgICAgPGVsLWNvbCA6c3Bhbj1cIjEyXCI+XG4gICAgICAgICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJsYWJlbDFcIj5hYWE8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImxhYmVsMlwiPmJiYjwvZWwtZm9ybS1pdGVtPlxuICAgICAgICAgIDwvZWwtY29sPlxuICAgICAgICA8L2VsLXJvdz5cbiAgICAgIDwvZWwtZm9ybT5cbiAgICAgICAgPGZvb3RlciBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9wZW4gPSBmYWxzZVwiPkJ1dHRvbjwvZWwtYnV0dG9uPlxuICAgICAgICA8L2Zvb3Rlcj5cbiAgICA8L2VsLXdhdGVybWFyaz5cbiAgIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi5kaWFsb2ctZm9vdGVye1xuICB0ZXh0LWFsaWduOiBjZW50ZXIgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by yoeb** [comment]
I see. Thank you very much. @chenxch
