### ISSUE TITLE
[Component] [cascader] 更新v-model数据后，二级menu切换了数据的展示

### ISSUE THREAD

**Issue by nothing-sy** [element-plus/element-plus#15297]
Bug Type: **`Component`**

## Environment

- Vue Version: `latest`
- Element Plus Version: `latest`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge2RhdGF9IGZyb20gJy4vZGF0YSdcblxuY29uc3QgaXRlbUxpc3RQcm9wcyA9IHJlZih7XG4gICAgbGFiZWw6ICdzeXN0ZW1EZXNjJyxcbiAgICB2YWx1ZTogJ25hbWUnLFxuICAgIGNoaWxkcmVuOiAnY2hpbGRyZW5zJyxcbiAgICBjaGVja1N0cmljdGx5OiB0cnVlLFxuICAgIG11bHRpcGxlOiB0cnVlLFxuICAgIGVtaXRQYXRoOiBmYWxzZVxuICB9KVxuY29uc3QgZGV2aWNlRGF0YUxpc3QgPSByZWYoZGF0YSlcbmNvbnN0IGN1ckRldmljZURhdGFMaXN0ID0gcmVmKFsxLDJdKVxuXG4vLyDpu5jorqTnirbmgIHkuIvvvIzli77pgIlhbGzpgInpobnvvIzlubbmiorlvZPliY3lrZBtZW5155qE5omA5pyJ6aG55re75Yqg5LiK77yM5q2k5pe25pu05paw5LqGdi1tb2RlbOeahOaVsOaNrlxuLy/vvIzkvJrlr7zoh7RtZW515YiH5o2i5Yiw5YW25LuW5pWw5o2u77yM6ICM5LiN5piv5YGc55WZ5ZyoYWxs6YKj5LiA5Liq6Z2i5p2/XG5mdW5jdGlvbiBjKCl7XG5jdXJEZXZpY2VEYXRhTGlzdC52YWx1ZS5wdXNoKDMsNClcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtY2FzY2FkZXJcbiAgICAgICAgICB2LW1vZGVsPVwiY3VyRGV2aWNlRGF0YUxpc3RcIlxuICAgICAgICAgIDpwcm9wcz1cIml0ZW1MaXN0UHJvcHNcIlxuICAgICAgICAgIDpjb2xsYXBzZS10YWdzPVwidHJ1ZVwiXG4gICAgICAgICAgOm9wdGlvbnM9XCJkZXZpY2VEYXRhTGlzdFwiXG4gICAgICAgICAgOnNob3ctYWxsLWxldmVscz1cImZhbHNlXCJcbiAgICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgICAgQGNoYW5nZT1cImNcIlxuICAgICAgICAvPlxuPC90ZW1wbGF0ZT4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE0ODA2LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTE0ODA2LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ1xuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICB9KVxufSIsInNyYy9kYXRhLnRzIjoiZXhwb3J0IGNvbnN0IGRhdGEgPSBbXHJcblxyXG4gIHtcclxuICAgIFwiaWRcIjogNDg5MyxcclxuICAgIFwibmFtZVwiOiBcInZpcjAwMlwiLFxyXG4gICAgXCJzeXN0ZW1EZXNjXCI6IFwi5rWL6K+VMlwiLFxyXG4gICAgXCJjaGlsZHJlbnNcIjogW1xyXG4gICAgICB7XHJcbiAgICAgICAgXCJpZFwiOiA0MzYxLFxyXG4gICAgICAgIFwibmFtZVwiOiAxLFxyXG4gICAgICAgIFwic3lzdGVtRGVzY1wiOiBcIuaooeWdl+eUtea1geS4jeW5s+ihoVwiLFxyXG4gICAgICAgIFwiY2hpbGRyZW5zXCI6IG51bGxcclxuICAgICAgfSxcclxuICAgICAge1xyXG4gICAgICAgIFwiaWRcIjogNDM1OSxcclxuICAgICAgICBcIm5hbWVcIjogMixcclxuICAgICAgICBcInN5c3RlbURlc2NcIjogXCJQQ1PkuqTmtYHkvqflkYroraZcIixcclxuICAgICAgICBcImNoaWxkcmVuc1wiOiBudWxsXHJcbiAgICAgIH1cclxuICAgIF1cclxuICB9LFxyXG57XHJcbiAgICBcImlkXCI6IDEsXHJcbiAgICBcIm5hbWVcIjogOTk5LFxyXG4gICAgXCJzeXN0ZW1EZXNjXCI6IFwiOTk5XCJcclxuICB9LFxyXG4gIHtcclxuICAgIFwiaWRcIjogMixcclxuICAgIFwibmFtZVwiOiA4ODgsXHJcbiAgICBcInN5c3RlbURlc2NcIjogXCI4ODhcIlxyXG4gIH0sXHJcbiAge1xyXG4gICAgXCJpZFwiOiAxLFxyXG4gICAgXCJuYW1lXCI6IDc3NyxcclxuICAgIFwic3lzdGVtRGVzY1wiOiBcIjc3N1wiXHJcbiAgfSxcclxuICB7XHJcbiAgICBcImlkXCI6IDEsXHJcbiAgICBcIm5hbWVcIjogNjY2LFxyXG4gICAgXCJzeXN0ZW1EZXNjXCI6IFwiNjY2XCJcclxuICB9LFxyXG4gIHtcclxuICAgIFwiaWRcIjogMixcclxuICAgIFwibmFtZVwiOiA1NTUsXHJcbiAgICBcInN5c3RlbURlc2NcIjogXCI1NTVcIlxyXG4gIH0sXHJcbiAge1xyXG4gICAgXCJpZFwiOiAxLFxyXG4gICAgXCJuYW1lXCI6IDQ0NCxcclxuICAgIFwic3lzdGVtRGVzY1wiOiBcIjQ0NFwiXHJcbiAgfSxcclxuICB7XHJcbiAgICBcImlkXCI6IDQ4OTIsXHJcbiAgICBcIm5hbWVcIjogXCJ2aXIwMDFcIixcclxuICAgIFwic3lzdGVtRGVzY1wiOiBcIua1i+ivlTFcIixcclxuICAgIFwiY2hpbGRyZW5zXCI6IFtcclxuICAgIHtcclxuICAgICAgICBcImlkXCI6IDMzMyxcclxuICAgICAgICBcIm5hbWVcIjotMSxcclxuICAgICAgICBcInN5c3RlbURlc2NcIjogXCJhbGxcIixcclxuICAgICAgICBcImNoaWxkcmVuc1wiOiBudWxsXHJcbiAgICAgIH0sXHJcbiAgICAgIHtcclxuICAgICAgICBcImlkXCI6IDQzNTcsXHJcbiAgICAgICAgXCJuYW1lXCI6MyxcclxuICAgICAgICBcInN5c3RlbURlc2NcIjogXCJQQ1PmqKHlnZfpmZDmtYHlkYroraZcIixcclxuICAgICAgICBcImNoaWxkcmVuc1wiOiBudWxsXHJcbiAgICAgIH0sXHJcbiAgICAgIHtcclxuICAgICAgICBcImlkXCI6IDI2OTgsXHJcbiAgICAgICAgXCJuYW1lXCI6IDQsXHJcbiAgICAgICAgXCJzeXN0ZW1EZXNjXCI6IFwi5bel5L2c54q25oCB77yI6Ieq5a6a5LmJ77yJXCIsXHJcbiAgICAgICAgXCJjaGlsZHJlbnNcIjogbnVsbFxyXG4gICAgICB9XHJcbiAgICBdXHJcbiAgfV0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNDgwNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

### Steps to reproduce

1.默认情况下，请滚动到最下方，选择 “测试1 -》 all”
2.二级menu从展示 “测试1”的子集的，变味了展示 "测试2"的子集，且一级menu滚动到了“测试2”所在的位置

### What is Expected?
一级menu不滚动
二级menu仍然停留在"all"选项那一页

### What is actually happening?
一级menu滚动到“测试2”所在位置
二级menu切换到“测试2”的子集

### Additional comments

element-plus本身更新v-model有一个BUG，就是无法更新面板的展示，但是[PR 14806](https://github.com/element-plus/element-plus/pull/14806)已经修复了这个问题，因此该issue的复现环境链接是在修复了这个问题基础上创建的。

所以请把问题的重心放在 更新v-model后， menu的数据会被切换的问题上

**Comment by nothing-sy** [comment]
只要我去更新v-model的数据，都会触发syncMenuState or scrollToExpandingNode， 从而导致一级menu会滚动到第一个选择的节点的父节点位置，而二级menu的数据会被切换为第一个选择的节点所在的children数据

**Comment by yuxuan-ctrl** [comment]
@btea  请问可以针对 #14806 进行讨论吗？
