### ISSUE TITLE
[Bug Report] Responsive Layout issue on media query critical value

### ISSUE THREAD

**Issue by CokeMine** [element-plus/element-plus#1530]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Windows 10 x64

### Vue version
3.0.6

### Reproduction Link
https://codepen.io/cokemine/pen/QWGQRMM

### Steps to reproduce
This is the official demo for "Responsive Layout" in the Website Docs.

When change the viewport width from left to width.

If the viewport width is between 767px and 768px, no style will display.

![](https://img.ams1.imgbed.xyz/2021/02/27/13PME.png)

I wonder if it's better to change the breakpoints in `packages/theme-chalk/src/common/var.scss` ?

### What is Expected?
When the viewport width is from 767px to 768px, the col style should be showed by "xs" attributes.

### What is actually happening?
When the viewport width is from 767px to 768px, no col style display.

**Comment by JayTam** [comment]
I try your reproduction demo, it show normal.
```
System:
    OS: macOS 11.2.2 
  Browsers:
    Chrome: 88.0.4324.192
```

![image](https://user-images.githubusercontent.com/31993846/109520035-c28cb480-7ae6-11eb-9a2b-66d7897611db.png)

**Comment by Ryan2128** [comment]
Has reproduced.

![image](https://user-images.githubusercontent.com/33176053/109529409-abeb5b00-7af0-11eb-8ac9-5f453c410564.png)
