### ISSUE TITLE
[Component] [select] option数组数量超过100时，搜索不到内容会报错：Maximum recursive updates exceeded

### ISSUE THREAD

**Issue by Azir-11** [element-plus/element-plus#15323]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.3`
- Element Plus Version: `2.4.4`
- Browser / OS: `edge 120.0.2210.91`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgc2VsZWN0VmFsdWUgPSByZWY8c3RyaW5nPignJylcbmNvbnN0IHNlbGVjdE9wdGlvbnMgPSByZWYoW10pXG5cbmNvbnN0IGdldEFyciA9ICgpID0+IHtcbiAgY29uc3QgYXJyID0gW11cbiAgZm9yIChsZXQgaSA9IDA7IGkgPCAxMDE7IGkrKykge1xuICAgIGFyci5wdXNoKHtcbiAgICAgIGlkOiBpLFxuICAgICAgbmFtZTogYG5hbWUke2l9YCxcbiAgICAgIHJlc291cmNlX3JvdXRlcl9uYW1lOiBgcmVzb3VyY2Vfcm91dGVyX25hbWUke2l9YCxcbiAgICB9KVxuICB9XG4gIHJldHVybiBhcnJcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgc2VsZWN0T3B0aW9ucy52YWx1ZSA9IGdldEFycigpXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtc2VsZWN0IGNsYXNzPVwidy1bMjAwcHhdXCIgZmlsdGVyYWJsZSBjbGVhcmFibGUgdi1tb2RlbD1cInNlbGVjdFZhbHVlXCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXoj5zljZXlkI3np7BcIj5cbiAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIHNlbGVjdE9wdGlvbnNcIiA6a2V5PVwiaXRlbS5pZFwiIDpsYWJlbD1cIml0ZW0ubmFtZVwiIDp2YWx1ZT1cIml0ZW0ucmVzb3VyY2Vfcm91dGVyX25hbWVcIiAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

selectOptions数组长度大于100，输入无法搜索到的内容，如在playground内输入aa

### What is Expected?

返回No matching data

### What is actually happening?

Maximum recursive updates exceeded in component <ElSelect>.

### Additional comments

_(empty)_

**Comment by Azir-11** [comment]
从vue3.11开始有warn警告,3.4.0-rc.1开始变为报错

**Comment by iceskyfrost** [comment]
恁看中不中
