### ISSUE TITLE
[Feature Request] el-slider 自定义设置标记的固定位置（占整个滑动条长度的百分比），而不是自动计算标记的数据占比的位置

### ISSUE THREAD

**Issue by xmasuhai** [element-plus/element-plus#15338]
### Existing Component
是

### Component Name
el-slider

### Description
el-slider 中有些标记点集中靠近得非常密集，由于标记位置是按照自动计算标记的数据占整个滑动条长度的百分比而来，数据间隔是均匀分布的
现在如果需要非均匀的展示标记点，自定义设置标记的固定位置（虽然会导致滑动条的变化不均匀），使得集中靠近的标记点能够按照自定义的位置分散开来展示
比如有 0分位、25%分位、50%分位、75%分位、100%分位的标记点，对应的数据集中在整个滑动条的前10%的位置，现在需要这几个标记点出现的位置平均占据滑动条的长度，该如何实现

![image](https://github.com/element-plus/element-plus/assets/24904259/86fde3a1-57e7-4cd8-b707-40db6e4f26dd)
![image](https://github.com/element-plus/element-plus/assets/24904259/0bd96644-92da-410c-9e80-39acbbcd2ca4)
![image](https://github.com/element-plus/element-plus/assets/24904259/d14ab1f7-a87e-4abd-a466-96e871c8336e)

**Comment by btea** [comment]
Do you mean that multiple markers are located close together, causing the text to overlap?

**Comment by wzc520pyfm** [comment]
If multiple tags are too close, causing text overlap, rotating the tagged text at a certain angle can have some improvement effect.
[Example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cInNsaWRlci1kZW1vLWJsb2NrXCI+XG4gICAgPGVsLXNsaWRlciB2LW1vZGVsPVwidmFsdWVcIiByYW5nZSA6bWFya3M9XCJtYXJrc1wiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IENTU1Byb3BlcnRpZXMgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBNYXJrIHtcbiAgc3R5bGU6IENTU1Byb3BlcnRpZXNcbiAgbGFiZWw6IHN0cmluZ1xufVxuXG50eXBlIE1hcmtzID0gUmVjb3JkPG51bWJlciwgTWFyayB8IHN0cmluZz5cblxuY29uc3QgdmFsdWUgPSByZWYoWzMwLCA2MF0pXG5jb25zdCBtYXJrcyA9IHJlYWN0aXZlPE1hcmtzPih7XG4gIDA6ICcwwrBDJyxcbiAgODogJzjCsEMnLFxuICAzNzogJzM3wrBDJyxcbiAgNTA6IHtcbiAgICBzdHlsZToge1xuICAgICAgY29sb3I6ICcjMTk4OUZBJyxcbiAgICAgIHRyYW5zZm9ybTogJ3JvdGF0ZSg0NWRlZyknXG4gICAgfSxcbiAgICBsYWJlbDogJzUwJScsXG4gIH0sXG4gIDUzOiB7XG4gICAgc3R5bGU6IHtcbiAgICAgIGNvbG9yOiAnIzE5ODlGQScsXG4gICAgICB0cmFuc2Zvcm06ICdyb3RhdGUoNDVkZWcpJ1xuICAgIH0sXG4gICAgbGFiZWw6ICc1MCUnLFxuICB9LFxuICA1Njoge1xuICAgIHN0eWxlOiB7XG4gICAgICBjb2xvcjogJyMxOTg5RkEnLFxuICAgICAgdHJhbnNmb3JtOiAncm90YXRlKDQ1ZGVnKSdcbiAgICB9LFxuICAgIGxhYmVsOiAnNTAlJyxcbiAgfSxcbiAgNTk6IHtcbiAgICBzdHlsZToge1xuICAgICAgY29sb3I6ICcjMTk4OUZBJyxcbiAgICAgIHRyYW5zZm9ybTogJ3JvdGF0ZSg0NWRlZyknXG4gICAgfSxcbiAgICBsYWJlbDogJzUwJScsXG4gIH0sXG59KVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLnNsaWRlci1kZW1vLWJsb2NrIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbn1cbi5zbGlkZXItZGVtby1ibG9jayAuZWwtc2xpZGVyIHtcbiAgbWFyZ2luLXRvcDogMDtcbiAgbWFyZ2luLWxlZnQ6IDEycHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by kooriookami** [comment]
The comment above is great.
