### ISSUE TITLE
[date-picker] Incorrect "type" options of the date-picker component in web-type.json

### ISSUE THREAD

**Issue by kaine0923** [element-plus/element-plus#15331]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.4.3`
- Element Plus Version: `2.4.4`
- Browser / OS: `Chrome/120.0.6099.71`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Link]()

#### IDE: WebStorm
```vue
<script setup>
import {ref} from "vue";
const value = ref('')
</script>

<template>
  <el-date-picker
    v-model="value"
    type="date"
    placeholder="请选择日期"
  ></el-date-picker>
</template>
```

### What is Expected?

type="date" 不会出现波浪线

### What is actually happening?

当type="date"会出现波浪线，并提示date 不是 type 的有效值。预期值: year、month、Date、dates、datetime、week、datetimerange、daterange或monthrange

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/121680374/9dfa826d-2e4c-4c36-a4c5-e8fb1f9b4934)
![image](https://github.com/element-plus/element-plus/assets/121680374/ae0b8bb4-9718-4817-93ea-6fb843f560b1)

**Comment by yj-liuzepeng** [comment]
![image](https://github.com/element-plus/element-plus/assets/75007029/3e756a17-35f7-479a-b7b0-1ab7f14bf578)


没问题呢

**Comment by kaine0923** [comment]
> ![image](https://private-user-images.githubusercontent.com/75007029/293842917-3e756a17-35f7-479a-b7b0-1ab7f14bf578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzIyNTIsIm5iZiI6MTcwNDI3MTk1MiwicGF0aCI6Ii83NTAwNzAyOS8yOTM4NDI5MTctM2U3NTZhMTctMzVmNy00NzlhLWI3YjAtMWFiN2YxNGJmNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA4NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2I2YmY2MzQxMGM1NWM3YmZiMjI5YTg0ZTE1MjdhN2U5NWJjMTk4ZTNkYjZkYzBkYzgwMDdjZjk3N2Q1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ka_ZlS6roc9y58qmBEtAS__oQgMb-5Pvm8sM6fh2LGw)
> 
> 没问题呢

这个问题出现在 **WebStorm** 中，应该是初始化项目依赖的时候，使用了web-types.json里面的数据作为IDE的提示
正常情况下是会去使用`.d.ts`里面的数据作为类型推断

**Comment by kaine0923** [comment]
web-types. json文件是在打包的时候根据文档中的数据匹配动态生成的，但我打包出来里面没数据只有几个基本字段数据。

**Comment by btea** [comment]
@kaine0923 It seems that there are some problems in the conversion process of the generated json file. It is recommended that you use the Volar plug-in first.
