### ISSUE TITLE
[Component] [date-picker] 日期选择器定位日期错误

### ISSUE THREAD

**Issue by LiYuhangggg** [element-plus/element-plus#15335]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.9`
- Browser / OS: `Google Chrome版本 120.0.6099.130（正式版本） （64 位）`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/datetime-picker.html)

### Steps to reproduce

官网的示例的就有问题，选择时间时，点击当天日期会定位到这个月的第一天。这个问题只在生产环境有，开发环境没有

### What is Expected?

点击日期某一天定位到点击的当天

### What is actually happening?

点击日期某一天定位到了这个月的一号日期（生产环境出问题）

### Additional comments

_(empty)_

![1704253783906](https://github.com/element-plus/element-plus/assets/133179384/9fde1513-33a9-44aa-9491-c3326190f0b0)

**Comment by chenxch** [comment]
fixed #15197
