### ISSUE TITLE
[Component] [popover, color-picker] el-popover里面放一个el-color-picker，在el-popover里面打开取色器，在取色器中任意点击， el-popover就关闭了

### ISSUE THREAD

**Issue by fjyong** [element-plus/element-plus#15357]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `谷歌`
- Build Tool: `Webpack`

### Related Component

- `el-popover`
- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICA8ZWwtcG9wb3ZlciBwbGFjZW1lbnQ9XCJyaWdodFwiIDp3aWR0aD1cIjQwMFwiIHRyaWdnZXI9XCJjbGlja1wiPlxuICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgIDxlbC1idXR0b24gc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDE2cHhcIj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1jb2xvci1waWNrZXIgdi1tb2RlbD1cImNvbG9yMVwiIC8+XG4gICAgPC9lbC1wb3BvdmVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbG9yMSA9IHJlZignIzQwOUVGRicpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

打开取色器，任意点击取色器，el-popover关闭

### What is Expected?

el-popover里面放一个el-color-picker，点击取色器，应该是完成取色后，el-popover也不会关闭

### What is actually happening?

el-popover里面放一个el-color-picker，打开取色器，在取色器里面任意点击el-popover就关闭了

### Additional comments

_(empty)_

**Comment by xingyixiang** [comment]
是不是可以开发业务代码是给el-color-picker 增加一个:teleported="false"属性配置
