### ISSUE TITLE
[bug report] dialog cannot be closed

### ISSUE THREAD

**Issue by 134355** [element-plus/element-plus#1535]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
window

### Vue version
3.0.6

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
<el-dialog
        v-model={dialog.visible}
        ref={((e: any) => { ctx.dialogRef = e })}
        v-slots={{
          footer: () => {
            return (
              <span class="dialog-footer">
                <el-button onClick={ctx.handleClose}>取消</el-button>
                <el-button type="primary" loading={dialog.loading} onClick={ctx.handleSubmit}>确定</el-button>
              </span>
            )
          }
        }}>

      </el-dialog>

点击取消按钮并不能关闭 visible 实际状态已经改变，追踪到dialog内部的visible还是true, 使用默认关闭按钮就可以，而且追踪到dialog内部的visible是false

### What is Expected?
点击取消按钮可以关闭

### What is actually happening?
点击取消按钮并不能关闭 visible 实际状态已经改变，追踪到dialog内部的visible还是true, 使用默认关闭按钮就可以，而且追踪到dialog内部的visible是false

**Comment by Ryan2128** [comment]
Can you provide a reproduction repo? I test the demo just now, it works well.

**Comment by 134355** [comment]
很抱歉，现在复现不了
