### ISSUE TITLE
[Component] [date-picker] el-date-picker点击选择第一下都是每月的一号，点击第二下才能正确选择要选的日期

### ISSUE THREAD

**Issue by xanxus01** [element-plus/element-plus#15356]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.4`
- Element Plus Version: `2.4.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/datetime-picker.html)

### Steps to reproduce

el-date-picker点击选择第一下都是每月的一号，点击第二下才能正确选择要选的日期。官网的示例链接也是这个问题

### What is Expected?

点击第一下就选择正确的时间

### What is actually happening?

不管点几号点击第一下都是每月的一号。官网的示例链接也是这个效果

### Additional comments

官网的示例链接也是这个问题。各个操作系统，浏览器，能测的都复现。

**Comment by btea** [comment]
Duplicate of #15196
