### ISSUE TITLE
How can El date picker automatically get the focus and pop up the pop-up window

### ISSUE THREAD

**Issue by zhixialihan** [element-plus/element-plus#1536]
![Snipaste_2021-03-01_10-30-21](https://user-images.githubusercontent.com/56864653/109444869-32fcec80-7a79-11eb-821a-a7ec9d831ad8.png)
![Snipaste_2021-03-01_10-30-37](https://user-images.githubusercontent.com/56864653/109444878-398b6400-7a79-11eb-8121-32a43eadb4bb.png)
$refs[''].focus不能直接让他获取焦点
目前只能通过点击input输入框触发日期选择器，我希望能通过其他方式触发日期选择器同时把input输入框去掉，如点击按钮

**Comment by Ryan2128** [comment]
Maybe this pr has what you want. #1475

**Comment by Sessay** [comment]
I also encountered this problem. Have you solved it?

**Comment by MikeSaprykin** [comment]
> Maybe this pr has what you want. #1475

This PR indeed fixed the issue. Couldn't reproduce the issue with version 1.0.2-beta.39
