### ISSUE TITLE
Can a hover trigger method be added to the [feature request] tabs tab?

### ISSUE THREAD

**Issue by dongfenglong** [element-plus/element-plus#1538]
### Existing Component
Yes

### Component Name
Tabs

### Description
目前 Tabs 标签页只能通过 click 方式触发，希望后续能添加 hover 触发方式。

**Comment by Ryan2128** [comment]
Sorry, this trigger way seem not a common and intuitive interaction way. Just like chrome's tabs.

Not considering adding this feature at this time.
