### ISSUE TITLE
[Style] [table] el-table表合并之后，鼠标移动上去样式错误

### ISSUE THREAD

**Issue by aBlindBoy** [element-plus/element-plus#15384]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.4`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuXG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDIsXG4gICAgICAgIGNvbHNwYW46IDEsXG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZGl2PlxuXG5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

按照官网步骤合并表格

### What is Expected?

1.合并表格
2.鼠标移动到第一行，左边合并的列不高亮

### What is actually happening?

1.合并表格
2.样式出现错误，鼠标移动到第一行，左边合并的列高亮

### Additional comments

_(empty)_

**Comment by aBlindBoy** [comment]
![image](https://github.com/element-plus/element-plus/assets/44792248/b08357b5-ecdf-46ae-be39-ba8e9c2c3627)
补充说明

**Comment by aBlindBoy** [comment]
![image](https://github.com/element-plus/element-plus/assets/44792248/a24e2637-f03f-4073-8d7e-969399d15afe)

**Comment by dowinweb** [comment]
应该是两行都选上吧， hover下面那行也应该选中
