### ISSUE TITLE
[Bug Report] [Bug] ElTransfer with all items selected as default model value from source data will cause exception when select/unselect items

### ISSUE THREAD

**Issue by tikazyq** [element-plus/element-plus#1539]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Chrome

### Vue version
3.0.6

### Reproduction Link
https://codepen.io/tikazyq/pen/NWbYoKG

### Steps to reproduce
1. Create a valid data item list for el-transfer;
2. Assign model-value for el-transfer as all items of data;
3. Attempt to move item(s) from right to left.
4. Issue reproduced.

### What is Expected?
All items should be freely moved between left and right without any issue.

### What is actually happening?
I think this is caused by the fact that the children of el-checkbox-group were empty in the first place, which caused Vue3 to encounter null exceptions when comparing old (which is null) and new children. It could be a Vue3 issue but I think this could be avoided by fixing on the element-plus side.

**Comment by Ryan2128** [comment]
What exception happended? The items in right panel did not move to left? If did, you should use `v-model` instead of `:model-value`.

**Comment by tikazyq** [comment]
@Ryan2128, thanks for the reply.

But I think I have put the link for issue reproduction quite clearly in the bug report. It's in the codepen link I provided. Please let me know if the link works for you.

I don't think v-model will be a solution as it's only a syntactic sugar for model-value and input event. If got one, you are welcome to contact me on WeChat and my id is "tikazyq1".

Btw I really think the code for the new component el-transfer should be optimized as I already saw some terrible implementations.

Good luck!

**Comment by Ryan2128** [comment]
What is your want? 

The transfer component's `model-value` has its status which is selected, so if you need select some records, you need change the `model-value`, whether using events or using `v-model` syntactic sugar.

> All items should be freely moved between left and right without any issue.

According to your expect, the `model-value` need to be changed.

**Comment by Ryan2128** [comment]
In my test, I didn’t encounter any errors. The only thing was that it didn’t move to the left after clicking the button, but this is a mistake in your writing.

**Comment by Ryan2128** [comment]
I will close this issue, if you has any problem, please feel free to reopen it.

**Comment by tikazyq** [comment]
Okay, it might be the change event is incorrectly coded. But I re-coded the el-transfer component as the current implementation in Element+ is not good enough to satisfy my use case.
