### ISSUE TITLE
### NavMenu

### ISSUE THREAD

**Issue by Liiked** [element-plus/element-plus#154]
Includes these components:
- `el-menu`
- `el-menu-item`
- `el-menu-item-group`
- `el-submenu`

Dependencies:
- `el-tooltip` (depended by `el-menu-item`, tracked by #107)

**Comment by g3r4n** [comment]
@Liiked are you working on this one ?

**Comment by Liiked** [comment]
> @Liiked are you working on this one ?

yeah, I'm working on it☺️

**Comment by Ghitu** [comment]
Hi, can I help with this?

**Comment by Liiked** [comment]
> Hi, can I help with this?

yeah, it would be very helpful!
welcome to  follow the progress and fork [branch](https://github.com/element-plus/element-plus/tree/feat/nav_menu) to contribute your effort

**Comment by bastarder** [comment]
@Ghitu @Liiked 
Is there any progress?

**Comment by Ghitu** [comment]
@bastarder Not from my side. Sorry.

**Comment by JeremyWuuuuu** [comment]
I believe all dependencies were completed. We can proceed on this.

**Comment by JeremyWuuuuu** [comment]
cc @Ghitu @Liiked, feel free to contact me if you need anything.
