### ISSUE TITLE
[Component] [calendar] 国际化切换时，日历组件周第一天设置dayjs.en.weekStart无效

### ISSUE THREAD

**Issue by kaivin** [element-plus/element-plus#15408]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.5`
- Element Plus Version: `2.4.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-calendar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6bG9jYWxlPVwibGFuZ3VhZ2UgPT09ICdlbicgPyBlbiA6IHpoQ25cIj5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImxhbmd1YWdlXCIgQGNoYW5nZT1cImxhbmd1YWdlQ2hhbmdlXCI+XG4gICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJlblwiIGJvcmRlcj7oi7Hmloc8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiemgtY25cIiBib3JkZXI+5Lit5paHPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgIDxlbC1jYWxlbmRhciB2LW1vZGVsPVwidmFsdWVcIiAvPlxuICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsQ29uZmlnUHJvdmlkZXIsIGRheWpzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcbmltcG9ydCBlbiBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvZW4ubWpzJ1xuY29uc3QgdmFsdWUgPSByZWYobmV3IERhdGUoKSlcbmNvbnN0IGxhbmd1YWdlID0gcmVmKCd6aC1jbicpXG5cbmRheWpzLmVuLndlZWtTdGFydCA9IGxhbmd1YWdlLnZhbHVlID09PSAnZW4nID8gMCA6IDFcblxuY29uc3QgbGFuZ3VhZ2VDaGFuZ2UgPSAodikgPT4ge1xuICBkYXlqcy5lbi53ZWVrU3RhcnQgPSB2ID09PSAnZW4nID8gMCA6IDFcbiAgdmFsdWUudmFsdWUgPSBuZXcgRGF0ZSgpXG59XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGRheWpzLmVuLndlZWtTdGFydCA9IGxhbmd1YWdlLnZhbHVlID09PSAnZW4nID8gMCA6IDFcbn0pXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

切换中英文，日历组件不能实现英文时周第一天是周日，中文时周第一天是周一

### What is Expected?

切换为中文时，周第一天是周一，切换为英文时，周第一天时周日

### What is actually happening?

中英文切换时，周第一天无法更改，更改weekStart无效

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
因为切换只会对于多语言部分的响应式替换，对于已经初始化话好的组件，需要进行更新。
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6bG9jYWxlPVwibGFuZ3VhZ2UgPT09ICdlbicgPyBlbiA6IHpoQ25cIj5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImxhbmd1YWdlXCIgQGNoYW5nZT1cImxhbmd1YWdlQ2hhbmdlXCI+XG4gICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJlblwiIGJvcmRlcj7oi7Hmloc8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiemgtY25cIiBib3JkZXI+5Lit5paHPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgIDxlbC1jYWxlbmRhciB2LW1vZGVsPVwidmFsdWVcIiA6a2V5PVwidmFsdWVcIi8+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxDb25maWdQcm92aWRlciwgZGF5anMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgemhDbiBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvemgtY24ubWpzJ1xuaW1wb3J0IGVuIGZyb20gJ2VsZW1lbnQtcGx1cy9kaXN0L2xvY2FsZS9lbi5tanMnXG5jb25zdCB2YWx1ZSA9IHJlZihuZXcgRGF0ZSgpKVxuY29uc3QgbGFuZ3VhZ2UgPSByZWYoJ2VuJylcblxuZGF5anMuZW4ud2Vla1N0YXJ0ID0gbGFuZ3VhZ2UudmFsdWUgPT09ICdlbicgPyAwIDogMVxuXG5jb25zdCBsYW5ndWFnZUNoYW5nZSA9ICh2KSA9PiB7XG4gIGRheWpzLmVuLndlZWtTdGFydCA9IHYgPT09ICdlbicgPyAwIDogMVxuICB2YWx1ZS52YWx1ZSA9IG5ldyBEYXRlKClcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgZGF5anMuZW4ud2Vla1N0YXJ0ID0gbGFuZ3VhZ2UudmFsdWUgPT09ICdlbicgPyAwIDogMVxufSlcblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)
