### ISSUE TITLE
[feature request] tree filtering: when the parent node is filtered, the child node cannot be seen

### ISSUE THREAD

**Issue by qianxunlly** [element-plus/element-plus#1540]
### Existing Component
Yes

### Component Name
Tree

### Description
常规需求是需要通过筛选父节点，来点击子节点。这样的筛选不符合常规需求

**Comment by Ryan2128** [comment]
Can you provide a demo?

**Comment by qianxunlly** [comment]
![20210302092551](https://user-images.githubusercontent.com/78261883/109582562-54bda880-7b39-11eb-86d7-2654b2527454.jpg)

**Comment by qianxunlly** [comment]
![20210302092839](https://user-images.githubusercontent.com/78261883/109582773-b9790300-7b39-11eb-9208-ca1a54134a55.jpg)

**Comment by Ryan2128** [comment]
Nope, the search should only find matching records.
