### ISSUE TITLE
[Component] [All] element plus 类型提示丢失

### ISSUE THREAD

**Issue by lixiaofa** [element-plus/element-plus#15405]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.12`
- Element Plus Version: `2.4.4`
- Browser / OS: `105.0.5195.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/lixiaofa/fast-plus/blob/dev/play/src/virtualized-table/virtualized-table.vue)

### Steps to reproduce

null

### What is Expected?

有声明提示

### What is actually happening?

鼠标移上去组件类型声明提示都丢失， 提示如下:
(property) ElAutoResizer: unknown
(property) ElTableV2: unknown

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
We very much welcome you to modify this project according to your own ideas. Due to our limited energy, any problems that arise during the modification process that are not related to the original project need to be solved by yourself.

**Comment by lixiaofa** [comment]
> We very much welcome you to modify this project according to your own ideas. Due to our limited energy, any problems that arise during the modification process that are not related to the original project need to be solved by yourself.

Can you tell me what might be the problem？
Thank you！
@chenxch

**Comment by chenxch** [comment]
@lixiaofa You can try to check the tsconfig related paths.
