### ISSUE TITLE
[Component] [slider] 关于el-slider滑块在按住的滑动的情况下 鼠标移动到另外一个el-slider滑块并右击时两个滑块将会同时一起滑动

### ISSUE THREAD

**Issue by rookiefishs** [element-plus/element-plus#15424]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome 版本 120.0.6099.200（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/slider.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

两个el-slider组件同时使用,按照标题步骤操作即可复现,并 element-plus文档的el-slider部分也可以直接复现

### What is Expected?

鼠标控制一个el-slider时 即使移动到另外一个el-slider并右击,也不会同时控制两个el-slider,起码保证只控制一个

### What is actually happening?

鼠标控制一个el-slider时 移动到另外一个el-slider并右击,两个会一起移动

### Additional comments

希望element的issue添加可以增加上传演示视频功能

![image](https://github.com/element-plus/element-plus/assets/103868319/cd5711ab-34c0-4fac-b3bd-8f10cd1b3304)

**Comment by chenxch** [comment]
右键不是弹出菜单么，视频录制好直接在输入框粘贴就会自动上传（当然看你的网络

**Comment by chenxch** [comment]
我将你的右击操作换成滚轮轴点击是可以出现你说的情况

**Comment by zhangjinzhangjin** [comment]
感觉不是啥问题，只是左右键都绑定了事件，都能拖动。拖动改的也是各自单独的状态，并不是触发了什么BUG

**Comment by rookiefishs** [comment]
> 感觉不是啥问题，只是左右键都绑定了事件，都能拖动。拖动改的也是各自单独的状态，并不是触发了什么BUG

是的,但是如果不小心触发了,可能会导致一些操作上的误解,因为我们测试的时候出现这个问题,我复现了很长时间也没有复现

**Comment by chenxch** [comment]
因为在组件的设计上，考虑到少数的人的鼠标键位问题，采用mousedown作为触发条件，所以左右键等都能触发drag。
