### ISSUE TITLE
[Component] [All] 很急很重要的问题！！！DateTimePicker日期时间选择器，第一次选择日期的时候，日期错误，每次都显示的选择月份的1日

### ISSUE THREAD

**Issue by ChinaLewis** [element-plus/element-plus#15425]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.6`
- Element Plus Version: `2.4.4`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html)

### Steps to reproduce

官网该组件就有问题

### What is Expected?

期望第一次点击选的日期正常

### What is actually happening?

第一次点击选的日期不对

### Additional comments

_(empty)_

**Comment by xingyixiang** [comment]
#15197
