### ISSUE TITLE
[Bug Report] Autocomplete not giving up focus, Number Input toFixed() warning

### ISSUE THREAD

**Issue by jay-karkar** [element-plus/element-plus#1543]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/

### Steps to reproduce
https://element-plus.org/#/en-US/component/input
Once an item is selected in auto complete, "Tab" doesn't move to next object.

Other issue is input number, if manually set any value's precision via .toFixed() it throws following warning.
runtime-core.esm-bundler.js?5c40:38 

[Vue warn]: Invalid prop: custom validator check failed for prop "modelValue". 
  at <ElInputNumber modelValue="0" onUpdate:modelValue=fn controls=false  ... > 
  at <ElCol span=3 > 
  at <ElRow key=0 style= {padding-top: "10px"} > 
  at <Billing onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {billCreate: ƒ, billGet: ƒ, billUpdate: ƒ, computeBillItem: ƒ, addService: ƒ, …} > > 
  at <RouterView> 
  at <ElMain> 

### What is Expected?
Autocomplete input should transfer focus to next object.

Number Input should allow me to set precision manually.

### What is actually happening?
Autocomplete focus is stuck, can't transfer to next object.

Number input toFixed() throw's warning when used

**Comment by Ryan2128** [comment]
Duplicate #1459 

Already fixed.

**Comment by Ryan2128** [comment]
Please waiting for next version.
