### ISSUE TITLE
[Component] [select] 升级2.5.0后，select组件设置 multiple collapse-tags时，当组件宽度不足时，样式发生了破坏性的变化。

### ISSUE THREAD

**Issue by Fuphoenixes** [element-plus/element-plus#15459]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKFsnT3B0aW9uMScsICdPcHRpb24yJ10pXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBtdWx0aXBsZVxuICAgIGNvbGxhcHNlLXRhZ3NcbiAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTQwcHhcIlxuICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgIDptYXgtY29sbGFwc2UtdGFncz1cIjFcIlxuICA+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

切换element-plus版本至2.5.0版本，发现组件内tags出现换行，切换回2.4.4版本时不会换行

### What is Expected?

组件内tags不换行

### What is actually happening?

组件内tags换行

### Additional comments

一般来讲，传collapse-tags且max-collapse-tags为1，都是希望不要出现换行导致的组件高度发现变化，这样会导致样式布局出现问题。所以这里还是保持和2.4.4版本一致为好。

<img width="309" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/9af30592-e81e-4331-a1e0-935c53418fd2">
<img width="295" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/77b5e5dd-29a4-4d6e-8dbc-042f120a3de7">

**Comment by kooriookami** [comment]
@element-plus/backers See see

**Comment by Fuphoenixes** [comment]
这里有个很常见的升级后导致样式错乱的场景。
element-plus 2.4.4
<img width="1139" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/0e05ae55-f6c8-4578-9dd5-4ead760c28c4">

element-plus 2.5.0
<img width="1116" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/999cb04b-70ec-40ad-8dd8-28f3c9a1b66d">

**Comment by kooriookami** [comment]
That makes sense.
