### ISSUE TITLE
[Component] [select] 部分控件像el-select下拉选择这种，在开发环境、测试环境居然和正式环境下生成的dom结构不一样？

### ISSUE THREAD

**Issue by li-zejiang** [element-plus/element-plus#15452]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.16`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Link]()

### Steps to reproduce

<el-select v-model="value" class="m-2" placeholder="Select" size="large">

### What is Expected?

dom结构一致

### What is actually happening?

dom结构不一致

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
2.5.0版本有一次重构，请检查各个环境所依赖的版本是否一致。

**Comment by icemanstudy** [comment]
我也遇到了...1月10发布了2.5.0,对el-select做了重构.你看看是不是打包的时候升级到最新版了.

**Comment by Thunder7991** [comment]
我也遇到了是ElSelectV2 
开发环境:
![image](https://github.com/element-plus/element-plus/assets/61643801/aa0053dc-c2ea-47d0-9292-506532d91adc)
测试环境:
![image](https://github.com/element-plus/element-plus/assets/61643801/fe790d31-861c-46af-9b8d-565cc93a6944)
