### ISSUE TITLE
[Style] [select] [Component] [select] 升级2.5.0后，select组件宽度变成 100%。是一个 break change

### ISSUE THREAD

**Issue by mansonchor** [element-plus/element-plus#15467]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.9`
- Element Plus Version: `2.5.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHNwYW4+6YCJ6aG577yaPC9zcGFuPlxuICA8ZWwtc2VsZWN0IC8+XG4gIFxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <span>选项：</span>
  <el-select />
</template>
```

### What is Expected?

`<span>选项：</span>` 和下拉框应该可以 inline 左右布局

### What is actually happening?

下拉框变成了默认 100%，把本来的左右布局顶掉了

### Additional comments

这绝对算是样式的 break change 了...没人反馈有问题？

<img width="1034" alt="image" src="https://github.com/element-plus/element-plus/assets/2160731/0ad36528-3212-46cb-b1a6-5b3e343d7359">

<img width="1284" alt="image" src="https://github.com/element-plus/element-plus/assets/2160731/17d9391a-2320-4596-bce7-9d1ac44fcaa6">

**Comment by kooriookami** [comment]
具体修改内容可以看这里：#15352

**Comment by bobohuochai** [comment]
2.5.1 版本 select 默认宽度会变成很小

**Comment by zhixiao-kooboo** [comment]
Such a breaking change should be noticed in the release note!

**Comment by wellfrog16** [comment]
> 具体修改内容可以看这里：#15352

![image](https://github.com/element-plus/element-plus/assets/22096815/3ae621e0-45b9-487a-ab97-43da2240e8a6)

此修改会影响页面排版，甚至会导致某些深度使用的地方无法正常显示
但是并不是更新主版本号，仅仅只是更新了次版本号，并没有做向下兼容
极不负责的开源更新方式
