### ISSUE TITLE
[Component] [image] Image 跨域问题

### ISSUE THREAD

**Issue by besscroft** [element-plus/element-plus#15468]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.3`
- Element Plus Version: `2.5.1`
- Browser / OS: `Chrome/120.0.6099.216`
- Build Tool: `Nuxt`

### Related Component

- `el-image`

### Reproduction Link

[Github Repo](https://github.com/besscroft/kamera/blob/f2f63d8c8bbb664c7873f33dac52e5d01aea28cb/pages/index.vue#L91)

### Steps to reproduce

我把 element-plus 从 2.4.4 升级到 2.5.1 之后出现的问题，然后查看 releases 发现，新增了 crossorigin 属性。我单独对 crossorigin 和 referrerpolicy 属性，以及同时使用的各种值的排列组合进行了测试，依旧会出现跨域问题，所以来求助看看。项目中使用其他方式而非 el-image 的图片能够正常加载。

谢谢！

### What is Expected?

图片正常加载

### What is actually happening?

No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
试试看
```vue
<el-image :crossorigin="null" />
```

**Comment by besscroft** [comment]
@Cheerwhy 感谢你的回复，设置为 null 可以了。

**Comment by xiaoxian521** [comment]
> 试试看, 移除crossorigin
> 
> ```
> <el-image :crossorigin="null" />
> ```

可以将这个说明加到image文档的crossorigin属性上，欢迎`pr`❤️

**Comment by besscroft** [comment]
谢谢，我在 docs 上添加了 `null` type。
https://github.com/element-plus/element-plus/pull/15471

**Comment by xiaoxian521** [comment]
我注意到文档上有个空字符串 或许设置空字符串也可以呢
<img width="947" alt="image" src="https://github.com/element-plus/element-plus/assets/44761321/0dee9991-ddf2-474c-94f3-f0b614d884c9">

**Comment by kooriookami** [comment]
crossorigin 默认值清空吧，然后只保留 `anonymous`、`use-credentials`、`空字符串` 三个选项。

**Comment by kooriookami** [comment]
Fixed

**Comment by KuAi9** [comment]
> crossorigin 不要设置默认值，然后只保留 `anonymous`、`use-credentials`、`空字符串` 三个选项。之前的改动确实会有影响。

通过设置 el-image 的 crossorigin 为 null 解决跨域，但是会有TS类型错误，而且 el-image-viewer 仍然跨域

**Comment by li-wanbin** [comment]
我也遇到了这个问题，el-image-viewer 仍然跨域

**Comment by liu-kuan** [comment]
之前 el-image 好好的，就是新版本加上 crossorigin 之后所有图片都产生了跨域问题，看了下提交是个印度老哥提交的，感觉以后官方维护者代码合并的审查需要更认真一点
