### ISSUE TITLE
There is a problem with the Affix component. When the target attribute is not body, the positioning of the Affix component is wrong, and the value of top or bottom is not just the offet value

### ISSUE THREAD

**Issue by woxixiuqiangwei** [element-plus/element-plus#1546]
Existing Component
Yes

Component Name
Affix

Description
Affix组件有问题，当target属性不为body时、Affix组件的定位错误，top 或者 bottom 的值不只是offet值。

**Comment by Ryan2128** [comment]
Can you provide a reproduction demo or repo?

cc @kooriookami

**Comment by woxixiuqiangwei** [comment]
> Can you provide a reproduction demo or repo?
> 
> cc @kooriookami

<template>
  <div>
    <p v-for='i in 20'>当 affix-container 容器的滚动条到达一定距离时，会发现Affix组件的top值为100，top值应该是容器的top值+offset值</p>
    <div class="affix-container">
      <p v-for='i in 20'>1</p>
      <el-affix target=".affix-container" position='top' :offset="100">
        <el-button type="primary">指定容器</el-button>
      </el-affix>
      <p v-for='i in 20'>1</p>
    </div>
  </div>
</template>


<style type="text/css">
  .affix-container{
    overflow: auto;
    border:5px solid blue;
    width: 350px;
    height: 450px;
  }
</style>

**Comment by woxixiuqiangwei** [comment]
> Can you provide a reproduction demo or repo?
> 
> cc @kooriookami
https://static01.imgkr.com/temp/6cde0fbbe460483a99090f7bf175b024.txt

**Comment by woxixiuqiangwei** [comment]
> Hello @woxixiuqiangwei. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> 
> 你好 @woxixiuqiangwei, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。

https://static01.imgkr.com/temp/6cde0fbbe460483a99090f7bf175b024.txt

**Comment by kooriookami** [comment]
> > Hello @woxixiuqiangwei. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> > 你好 @woxixiuqiangwei, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。
> 
> https://static01.imgkr.com/temp/6cde0fbbe460483a99090f7bf175b024.txt

The affix is not fixed inside the target, but will be hidden when the target is out of view.

定位永远是body，这个target不是指定定位位置的，而是target不在视野范围内固钉就消失的意思。

**Comment by woxixiuqiangwei** [comment]
> > > Hello @woxixiuqiangwei. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> > > 你好 @woxixiuqiangwei, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。
> > 
> > 
> > https://static01.imgkr.com/temp/6cde0fbbe460483a99090f7bf175b024.txt
> 
> The affix is not fixed inside the target, but will be hidden when the target is out of view.
> 
> 定位永远是body，这个target不是指定定位位置的，而是target不在视野范围内固钉就消失的意思。
如果定位
额，每个人想法不一样，我的想法是target设置了，那么定位 就是target
