### ISSUE TITLE
[Style] [All] 不使用 vue-router 时，与 tailwindcss 的兼容性问题

### ISSUE THREAD

**Issue by Cat7373** [element-plus/element-plus#15461]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.8`
- Element Plus Version: `2.5.1`
- Browser / OS: `Edge/120.0.0.0 / macOS 14.2.1 (23C71)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/Cat7373/element-plus-bug-demo-code)

### Steps to reproduce

1. 创建一个最小的 Element-Plus 项目，使用 Vue-Router 默认导航到 /home 页面
2. 在 /home 页面放置几个 el-button
3. 运行项目，button 正常显示、工作
4. 将 router-view 去掉，改为直接引入 /home 页面的组件
5. button 的背景色消失，导致看不到按钮上的字（这只是问题之一，还会带来好多其他不正常的地方，这是最小化复现方式）

### What is Expected?

页面正常显示和工作

### What is actually happening?

button 的背景色消失，导致看不到按钮上的字

### Additional comments

1. 使用 router-view，按钮正常展示和使用

   ![](https://github.com/Cat7373/element-plus-bug-demo-code/assets/9296576/0888af45-a4b0-4b72-86ef-bd287753eede)

   ![](https://github.com/Cat7373/element-plus-bug-demo-code/assets/9296576/6766ad5b-2b06-4bcc-ad8a-a146ff26392a)

2. 直接引入组件，按钮无法正常使用

   ![](https://github.com/Cat7373/element-plus-bug-demo-code/assets/9296576/4659ef5d-37c2-443d-9326-73e79bffa8f5)

   ![](https://github.com/Cat7373/element-plus-bug-demo-code/assets/9296576/6b999e51-8bea-4be1-a127-fe2c1be80a4c)

**Comment by Cat7373** [comment]
我猜测是在 createApp 之前，就通过 main.js import 了`App.vue`，然后关联 import 了`home/index.vue`，导致`home/index.vue`中初始化什么东西过早而出现的这个问题。

**Comment by Cat7373** [comment]
我找到了一个方案，可以让组件正常工作，但控制台会输出一个警告：

```html
<template lang="pug">
el-config-provider(:locale="zhCn")
  component(:is="homeView")
</template>

<script setup>
import { ref, onMounted } from 'vue'
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'

const homeView = ref()

onMounted(async () => {
  homeView.value  = (await import('@/views/home/index.vue')).default
})
</script>
```

**Comment by btea** [comment]
It seems to be a problem with `tailwind`. The default style introduced here overrides the `element-plus` style.

**Comment by btea** [comment]
Releated pr https://github.com/tailwindlabs/tailwindcss/pull/12735.

**Comment by Cat7373** [comment]
我还以为 tailwindcss 不会造成什么问题呢😂

其实 pinia 在这种情况下工作也不正常，似乎用`component(:is="homeView")`是一个比较好的解决方案
