### ISSUE TITLE
[Bug Report] Table column resize not work

### ISSUE THREAD

**Issue by languanghao** [element-plus/element-plus#1548]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
win10/Chorme 88

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/zzh161/pen/RwoygeV

### Steps to reproduce
直接运行文档中的例子：https://codepen.io/zzh161/pen/RwoygeV

虽然文档中的表格支持拖动调整列宽，但是到codepen里面就不行了

### What is Expected?
文档中的表现和codepen中的表现保持一致

### What is actually happening?
文档中的表格支持拖动调整列宽，但是到codepen里面就不行了

**Comment by justwiner** [comment]
This is due to the version upgrade of Vue, please go back to v3.0.5

**Comment by justwiner** [comment]
duplicate: #1514

**Comment by languanghao** [comment]
> This is due to the version upgrade of Vue, please go back to v3.0.5

Thank you for your reply, After change Vue version to v3.0.5 everything works fine.

**Comment by Ryan2128** [comment]
@justwiner  I update the version of vue in #1556 , this issue need be fixed after the pr being merged.

**Comment by Yimisunny** [comment]
窗口拉大 table会相应变大，但是窗口再缩小时table不会再变小了
