### ISSUE TITLE
[Component] [checkbox-group] el-checkbox-group 设置的max属性小于value长度时，没法取消勾选

### ISSUE THREAD

**Issue by junyo** [element-plus/element-plus#15494]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-checkbox-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNoZWNrYm94LWdyb3VwIHYtbW9kZWw9XCJjaGVja2VkQ2l0aWVzXCIgOm1heD1cIm1heFwiPlxuICAgIDxlbC1jaGVja2JveCB2LWZvcj1cImNpdHkgaW4gY2l0aWVzXCIgOmtleT1cImNpdHlcIiA6bGFiZWw9XCJjaXR5XCI+e3tcbiAgICAgIGNpdHlcbiAgICB9fTwvZWwtY2hlY2tib3g+XG4gIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG4gIDxsYWJlbD7mnIDlpKflgLw8L2xhYmVsPjxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cIm1heFwiPjwvZWwtaW5wdXQ+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtYXggPSByZWYoMSk7XG5jb25zdCBjaGVja2VkQ2l0aWVzID0gcmVmKFsnU2hhbmdoYWknLCAnQmVpamluZycsICdTaGVuemhlbiddKVxuY29uc3QgY2l0aWVzID0gWydTaGFuZ2hhaScsICdCZWlqaW5nJywgJ0d1YW5nemhvdScsICdTaGVuemhlbiddXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

把max属性改成比已勾选的数量少就能重现。

### What is Expected?

当勾选数量超过max不能再添加可以理解，但不能取消我觉得就显得太死了。

### What is actually happening?

有一种场景就是会有动态max值的场景，但用户没办法取消了

### Additional comments

_(empty)_

**Comment by xingyixiang** [comment]
packages\components\checkbox\src\composables\use-checkbox-model.ts  line:21

set(val: unknown) {
      if (isGroup.value && isArray(val)) {
        const isReduced =
          isArray(model.value) && val.length < model.value.length
        isLimitExceeded.value =
          checkboxGroup?.max?.value !== undefined &&
          val.length > checkboxGroup.max.value
        if (!isLimitExceeded.value || isReduced) {
          checkboxGroup?.changeEvent?.(val)
        }
      } else {
        emit(UPDATE_MODEL_EVENT, val)
        selfModel.value = val
      }
    },
