### ISSUE TITLE
[Bug Report] The style of the icon set on the right side of the header of the container layout of the container instance is disordered

### ISSUE THREAD

**Issue by summertzz** [element-plus/element-plus#1549]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
all

### Vue version
3.0.7

### Reproduction Link
https://github.com/element-plus/element-plus/tree/dev/packages/container

### Steps to reproduce
1. open (https://element-plus.gitee.io/#/zh-CN/component/container)
2. view sample position
3. the style of the icon set on the right side of the header of the container layout of the container instance is disordered

### What is Expected?
1. open (https://element-plus.gitee.io/#/zh-CN/component/container)
2. view sample position
3. the style of the icon set on the right side of the header of the container layout of the container instance is normal

### What is actually happening?
1. open (https://element-plus.gitee.io/#/zh-CN/component/container)
2. view sample position
3. the style of the icon set on the right side of the header of the container layout of the container instance is disordered

**Comment by Ryan2128** [comment]
This cause by a style of docs site instead of componnet's error.

**Comment by Ryan2128** [comment]
It will be fixed soon.
