### ISSUE TITLE
[i18n] [date-picker] The "el-date-picker" component uses global Chinese internationalization, and the "format" format uses "MMMM" to display errors.

### ISSUE THREAD

**Issue by DrBetty** [element-plus/element-plus#15504]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.4.1`
- Browser / OS: `Chrome/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tICd2dWUnXG5pbXBvcnQgQ29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCBsb2NhbGUgZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcblxuXG5jb25zdCBhcHAgPSBjcmVhdGVBcHAoQ29tcClcbmFwcC51c2UoRWxlbWVudFBsdXMsIHtcbiAgbG9jYWxlXG59KVxuXG5hcHAubW91bnQoJyNhcHAnKVxuXG48L3NjcmlwdD5cblxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwPlxyXG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcclxuXHJcbmNvbnN0IGdhdGhlciA9IHJlYWN0aXZlKHtcclxubW9udGg6IDExLFxyXG59KVxyXG48L3NjcmlwdD5cclxuXHJcbjx0ZW1wbGF0ZT5cclxuPGVsLWRhdGUtcGlja2VyXHJcbiAgICAgICAgICAgICAgdi1tb2RlbD1cImdhdGhlci5tb250aFwiXHJcbiAgICAgICAgICAgICAgdHlwZT1cIm1vbnRoXCJcclxuICAgICAgICAgICAgICBmb3JtYXQ9XCJNTU1NXCJcclxuICAgICAgICAgICAgICB2YWx1ZS1mb3JtYXQ9XCJNTVwiXHJcbiAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCLor7fpgInmi6nmnIjku71cIlxyXG4gICAgICAgICAgICAvPlxyXG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=)

### Steps to reproduce

Click on the date picker to select any day of the month

### What is Expected?

The "el-date-picker" input box displays the month name in Chinese characters.

### What is actually happening?

The "el-date-picker" input box returns the name of the month in English.

### Additional comments

1，Configuring the global 'dayjs' to be in 'zh-cn' format returns the same error
2，Or using the 'el-config-provider' component wrapper is also an error return

**Comment by chenxch** [comment]
You also need to set the language for dayjs.
```
import dayjs from 'dayjs'
import dayjsZhCnLocale from 'dayjs/locale/zh-cn'
dayjs.locale(dayjsZhCnLocale)
```

**Comment by DrBetty** [comment]
@chenxch

**Comment by DrBetty** [comment]
@chenxch First of all, thank you very much for your reply, but you said this method I have also used, in the main.js file will be set globally dayjs language to Chinese, or use the following code to modify also have no practical effect

`
import dayjs from 'dayjs'
import updateLocale from 'dayjs/plugin/updateLocale'

const monthShortFormat = [
  '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月',
]

dayjs.extend(updateLocale)
  dayjs.updateLocale('en', {
    months(dayjsInstance, format) {
      if (format.startsWith('MMMM')) {
        return monthShortFormat[dayjsInstance.month()]
      }
    },
  })`

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/1fecc778-9b59-4e24-bcef-46e77a31259b)
Try again.

**Comment by chenxch** [comment]
@DrBetty Do you have any other questions? If not, I will close this issue.

**Comment by DrBetty** [comment]
@chenxch 

Thank you very much for resurrecting it again, I tried to test it with the code you provided but it didn't solve the problem, even when I used the method you provided in the "Playground" tool. The following link shows how I tested it in the "Playground" tool and the result.

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tICd2dWUnXG5pbXBvcnQgQ29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCBkYXlqcyBmcm9tICdkYXlqcydcbmltcG9ydCBkYXlqc1poQ25Mb2NhbGUgZnJvbSAnZGF5anMvbG9jYWxlL3poLWNuLmpzJ1xuaW1wb3J0IGxvY2FsZSBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvemgtY24ubWpzJ1xuXG5jb25zdCBhcHAgPSBjcmVhdGVBcHAoQ29tcClcbmFwcC51c2UoRWxlbWVudFBsdXMpXG5kYXlqcy5sb2NhbGUoZGF5anNaaENuTG9jYWxlKVxuYXBwLm1vdW50KCcjYXBwJylcblxuPC9zY3JpcHQ+XG5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICBcImRheWpzXCIgOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2L2RheWpzQDEuMTEuOFwiLFxuICBcImRheWpzL1wiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2L2RheWpzQDEuMTEuOC9cIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9Db21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XHJcbmltcG9ydCBkYXlqcyBmcm9tICdkYXlqcydcclxuaW1wb3J0IHsgb25CZWZvcmVNb3VudCwgb25Nb3VudGVkLCByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xyXG5pbXBvcnQgemhDbiBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvemgtY24ubWpzJ1xyXG5cclxuY29uc29sZS5sb2coJ3poQ24gPSAnLHpoQ24pXHJcblxyXG5cclxuY29uc3QgZ2F0aGVyID0gcmVmKDExKVxyXG5cclxuXHJcbmNvbnNvbGUubG9nKCdsb2NhbGUgPSAnLGRheWpzLmxvY2FsZSgpKVxyXG48L3NjcmlwdD5cclxuXHJcbjx0ZW1wbGF0ZT5cclxuPGVsLWNvbmZpZy1wcm92aWRlciA6bG9jYWxlPVwiemhDblwiPlxyXG48ZWwtZGF0ZS1waWNrZXJcclxuICAgICAgICAgICAgICB2LW1vZGVsPVwiZ2F0aGVyXCJcclxuICAgICAgICAgICAgICB0eXBlPVwibW9udGhcIlxyXG4gICAgICAgICAgICAgIGZvcm1hdD1cIk1NTU1cIlxyXG4gICAgICAgICAgICAgIHZhbHVlLWZvcm1hdD1cIk1NXCJcclxuICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeaciOS7vVwiXHJcbiAgICAgICAgICAgIC8+XHJcbjwvZWwtY29uZmlnLXByb3ZpZGVyPlxyXG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=

**Comment by chenxch** [comment]
@DrBetty Have you tested it in an actual project? It is possible to test it on my local project.

**Comment by DrBetty** [comment]
@chenxch Yes, I have tried the above method in my own local project, but the result is the same with the test project, but it does not matter you can close the problem, I used a radio component temporarily solved the problem, thank you for your patience over the past few days, thank you very much!

**Comment by issuashoshi** [comment]
`import {dayjs} from 'element-plus';
import dayjsZhCnLocale from 'dayjs/locale/zh-cn';
dayjs.locale(dayjsZhCnLocale)`
