### ISSUE TITLE
[Component] [icon] icons名称没有加横杠，但实际上要加了横杠才会显示

### ISSUE THREAD

**Issue by xiebruce** [element-plus/element-plus#15518]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.13`
- Element Plus Version: `2.5.1`
- Browser / OS: `macOS Big Sur 11.5.1,Edge 版本 120.0.2210.133 (正式版本) (x86_64)`
- Build Tool: `CDN`

### Related Component

- `el-icon`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/r0ueh5xs/1/)

### Steps to reproduce

1. 打开这个链接：https://jsfiddle.net/r0ueh5xs/1/
2. 运行它

### What is Expected?

显示CirclePlus和FullScreen图标

### What is actually happening?

这两个图标都不显示

### Additional comments

原因我知道，是因为CirclePlus要写成Circle-Plus，FullScreen要写成Full-Screen，然而我在这里：https://element-plus.org/zh-CN/component/icon.html#icon-collection 点击图标复制div的时候，都是没有横杠的。

**Comment by chenxch** [comment]
CDN模式使用组件只能是串式，相关信息可以自己在vue文档中搜索。

**Comment by chenxch** [comment]
https://cn.vuejs.org/guide/essentials/component-basics.html#case-insensitivity
