### ISSUE TITLE
[select] Select 没有了默认宽度

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#15510]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.13`
- Element Plus Version: `2.5.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOmlubGluZT1cInRydWVcIiA6bW9kZWw9XCJmb3JtSW5saW5lXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFwcHJvdmVkIGJ5XCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm1JbmxpbmUudXNlclwiIHBsYWNlaG9sZGVyPVwiQXBwcm92ZWQgYnlcIiBjbGVhcmFibGUgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgem9uZVwiPlxuICAgICAgPGVsLXNlbGVjdFxuICAgICAgICB2LW1vZGVsPVwiZm9ybUlubGluZS5yZWdpb25cIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIkFjdGl2aXR5IHpvbmVcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgID5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgb25lXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgdGltZVwiPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJmb3JtSW5saW5lLmRhdGVcIlxuICAgICAgICB0eXBlPVwiZGF0ZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIGRhdGVcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJvblN1Ym1pdFwiPlF1ZXJ5PC9lbC1idXR0b24+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZm9ybUlubGluZSA9IHJlYWN0aXZlKHtcbiAgdXNlcjogJycsXG4gIHJlZ2lvbjogJycsXG4gIGRhdGU6ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

详见复现环境链接内的内容

### What is Expected?

下拉框在表单中存在默认宽度，和input默认宽度一致效果最佳。

可能有些人觉得这个宽度需要自己设置，但是既然是表单组件。并且设置了 inline，在表单内就应该更加的易用，最起码要像输入框那样有一个差不多的默认宽度，而不是小的可怜的极限宽度。

### What is actually happening?

没有默认宽度，导致显示的非常小

### Additional comments

_(empty)_

**Comment by chdyiboke** [comment]
遇到了同样的问题，升级之后 select 框样式错乱了

**Comment by vbin-dev** [comment]
+1 默认宽度变的很小。2.5.0开始就存在了。2.4.4正常

**Comment by chenxch** [comment]
参考 https://element-plus.org/zh-CN/component/form.html#%E8%A1%8C%E5%86%85%E8%A1%A8%E5%8D%95
select控件在2.5.0版本进行了重构，解决了一直诟病的默认最小宽度问题，改为自适应宽度。

**Comment by WangJincheng4869** [comment]
> 参考 https://element-plus.org/zh-CN/component/form.html#%E8%A1%8C%E5%86%85%E8%A1%A8%E5%8D%95 select控件在2.5.0版本进行了重构，解决了一直诟病的默认最小宽度问题，改为自适应宽度。

按照什么自适应的啊！我这有没有数据都是很窄的一丢丢。看一下我的那个demo链接，就是那个样子

**Comment by chenxch** [comment]
因为你没给父级宽度

**Comment by kooriookami** [comment]
2.4.x版本select宽度是原生input的默认宽度，重构之后select默认是父容器100%宽度。

**Comment by WangJincheng4869** [comment]
> 因为你没给父级宽度

父元素是 form-item 啊，也就说新版本要给每个form-item设置一个宽度么。这样用起来比较麻烦，或者完善一下form-item组件，当`el-form` 的 `inline` 为 `true` 时，组件内部直接给 form-item 一个默认宽度，这样用起来能方便些，要不每个 form-item 都得写宽度

**Comment by chenxch** [comment]
默认宽度这个东西重口难调，不过可以考虑给form添加栅格模式的配置项。

**Comment by WangJincheng4869** [comment]
> 默认宽度这个东西重口难调，不过可以考虑给form添加栅格模式的配置项。

对，宽度这个东西的确是众口难调的东西。在 form 上配置也行，我现在完全使用 deep 给 --el-select 的变量设置的宽度。

但是我觉得给 select 个和文本框默认宽度一样的默认宽度应该会更好，特别适合我这种懒鬼。因为几乎不用写什么东西了，拿来直接用。

**Comment by kooriookami** [comment]
我看了antd和naive ui的select，宽度也是100%，它们在行模式也会变得很窄。以前很多人也是默认给select一个100%的宽度，相较之下宽度100%更符合大部分场景。这种情况很好处理，用户全局样式给定一个默认值，自行设置是一个很好的选择。一般来说select与input之类的宽度在表单中都是一样宽的，用户统一控制宽度是比较合理的。

**Comment by 736048546** [comment]
2.5版本input 也有bug 2.4没有

**Comment by zhiyong-y** [comment]
我是在el-space里边复现的这个问题

**Comment by zhocf** [comment]
2.3.6版本也这样，重新下node包后就没有宽度了

**Comment by lxy030988** [comment]
破坏性的升级，在版本日志里没有写处理方案啊

**Comment by xl495** [comment]
> 破坏性的升级，在版本日志里没有写处理方案啊

我也觉得应该加个说明啥的 至少不会这么懵逼

**Comment by wellfrog16** [comment]
此修改会影响页面排版，甚至会导致某些深度使用的地方无法正常显示
但是并不是更新主版本号，仅仅只是更新了次版本号，并没有做向下兼容
极不负责的开源更新方式

**Comment by kooriookami** [comment]
> 此修改会影响页面排版，甚至会导致某些深度使用的地方无法正常显示 但是并不是更新主版本号，仅仅只是更新了次版本号，并没有做向下兼容 极不负责的开源更新方式

抱歉这次升级给你带来了不便。升级版本本身是件有风险的事情，次版本号一般是用来发布新特性与代码重构。如果要升级依赖版本，请先阅读更新日志。一些大的重构，PR 当中会列举修改内容，请注意查看。

文档我们也会进一步优化，但是目前没有专人对更新日志整理，所以只能显示 PR 的名称。Element Plus 是社区开源的项目，欢迎更多开源人的共同参与维护。

**Comment by kooriookami** [comment]
对于 2.5.0 Select 与 SelectV2 组件重构的具体内容可以查看 #15352

**Comment by BugPcp** [comment]
更新版本是为了更新在现有版本上Element本身存在的bug，而不是产生新的bug，现在这个是完全没有必要去变更他

**Comment by star-hs** [comment]
> 2.5.0 版本 Select 与 SelectV2 组件重构的具体内容可以查看 #15352

作为只用组件的伸手党感谢你的代码贡献。但是次版本号不带破坏性的改动我以为是约定俗成的，这样一来会让人害怕升级的，不知道都有哪些“惊喜”在等着我

**Comment by tracker1999** [comment]
+1 默认宽度变的很小。2.5.0开始就存在了。2.4.4正常

**Comment by tracker1999** [comment]
![2 4 4](https://github.com/element-plus/element-plus/assets/6487670/03b351c7-2be3-47a7-9275-4b0b979e4f52)
![2 5](https://github.com/element-plus/element-plus/assets/6487670/71577d4a-025e-43cb-9559-73547b015515)
+1 默认宽度变的很小。2.5.0开始就存在了。2.4.4正常

**Comment by izhaorui** [comment]
我是这样解决的
// 修复饿了么 el-select没有宽度
```
.el-select {
  --el-select-width: 200px !important;
}
```

我看文档里面的示例都变成了这样
![image](https://github.com/element-plus/element-plus/assets/16451400/087a8f84-a961-4c8a-9a19-d51bc5e80ce4)
ganx感觉这样很sb，那么多el-select 还得一个个去设置

**Comment by wbsllm** [comment]
想更新到最新版(2.5.3)使用SelectV2,突然发现很多页面的select宽度变的很窄,且部分select下拉选择框无法弹出下拉框...默默的又退回到了之前的版本,害怕还有其他的坑等着.

**Comment by huanlirui** [comment]
### 同样的问题！宽度丢失，关键是为什么一部分 Ok一部分是有问题的？？

<img width="1613" alt="image" src="https://github.com/element-plus/element-plus/assets/40491203/e777adde-679f-41fe-99a9-d0c1f2f55452">

#### 问题 出在这个行内样式，11px是个什么东西？

<img width="620" alt="image" src="https://github.com/element-plus/element-plus/assets/40491203/19c6ace3-8fd5-4e85-9a8c-32a5286cabe1">

**Comment by kooriookami** [comment]
> ### 同样的问题！宽度丢失，关键是为什么一部分 Ok一部分是有问题的？？
> <img alt="image" width="1613" src="https://private-user-images.githubusercontent.com/40491203/300316375-e777adde-679f-41fe-99a9-d0c1f2f55452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTYzNzUtZTc3N2FkZGUtNjc5Zi00MWZlLTk5YTktZDBjMWYyZjU1NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTIzMjljMzc5YTUxMWFlYzE4Y2YxMDBjN2Q0NmNkMmQzYTg4OTM5NjRjODcyNzEzZjgwZjVmYzQxOThhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPWFaMojVBYpKAlPByKytrmZzHivksbuVLbpn1xb-j8">
> #### 问题 出在这个行内样式，11px是个什么东西？
> <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/40491203/300316500-19c6ace3-8fd5-4e85-9a8c-32a5286cabe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTY1MDAtMTljNmFjZTMtOGZkNS00ZTg1LTlhOGMtMzJhNTI4NmNhYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MGRlZWU4M2I5N2U4MDdlYTRiNTRiM2Y3ZjlkOWJmYjRhNmI0M2QxZGE4ZGVlMWFhN2JhYzYwYTczNTE3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g9KyydXT1qKJH8uLm0dhIwPV4ipQe6dI72aSLr9ZAFk">

这个11px是filterable时，最小的input宽度，根据输入文本长度自动变化宽度，在前面有tag时能够自动换行。

**Comment by huanlirui** [comment]
> > ### 同样的问题！宽度丢失，关键是为什么一部分 Ok一部分是有问题的？？
> > <img alt="image" width="1613" src="https://private-user-images.githubusercontent.com/40491203/300316375-e777adde-679f-41fe-99a9-d0c1f2f55452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTYzNzUtZTc3N2FkZGUtNjc5Zi00MWZlLTk5YTktZDBjMWYyZjU1NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTIzMjljMzc5YTUxMWFlYzE4Y2YxMDBjN2Q0NmNkMmQzYTg4OTM5NjRjODcyNzEzZjgwZjVmYzQxOThhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPWFaMojVBYpKAlPByKytrmZzHivksbuVLbpn1xb-j8">
> > #### 问题 出在这个行内样式，11px是个什么东西？
> > <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/40491203/300316500-19c6ace3-8fd5-4e85-9a8c-32a5286cabe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTY1MDAtMTljNmFjZTMtOGZkNS00ZTg1LTlhOGMtMzJhNTI4NmNhYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MGRlZWU4M2I5N2U4MDdlYTRiNTRiM2Y3ZjlkOWJmYjRhNmI0M2QxZGE4ZGVlMWFhN2JhYzYwYTczNTE3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g9KyydXT1qKJH8uLm0dhIwPV4ipQe6dI72aSLr9ZAFk">
> 
> 这个11px是filterable时，最小的input宽度，根据输入文本长度自动变化宽度，在前面有tag时能够自动换行。
> 
> Select本身宽度是100%的，在行内布局时需要指定一个具体宽度，不然会宽度出现问题。

2.4.4 版本没有问题，重新 install 一下依赖就有问题了，什么情况，我也没升级到什么 2.5

**Comment by kooriookami** [comment]
@huanlirui 你看看nodemodules里的element-plus依赖具体安装版本是不是2.4.4

**Comment by huanlirui** [comment]
> @huanlirui 你看看nodemodules里的element-plus依赖具体安装版本是不是2.4.4

还真是 2.5.3 ，不好意思，还真是 2.5 的问题 ，在执行缓存清理后，再执行 pnpm i，为何还是拉的 2.5.3
```
"clean": "pnpx rimraf node_modules",
    "clean:cache": "pnpx rimraf node_modules/.cache",
```

<img width="363" alt="image" src="https://github.com/element-plus/element-plus/assets/40491203/278ad99c-c2d1-4dd7-a7a7-b8e2e15a44c1">

**Comment by xl495** [comment]
> > @huanlirui 你看看nodemodules里的element-plus依赖具体安装版本是不是2.4.4
> 
> 还真是 2.5.3 ，不好意思，还真是 2.5 的问题 ，在执行缓存清理后，再执行 pnpm i，为何还是拉的 2.5.3
> 
> ```
> "clean": "pnpx rimraf node_modules",
>     "clean:cache": "pnpx rimraf node_modules/.cache",
> ```
> 
> <img alt="image" width="363" src="https://private-user-images.githubusercontent.com/40491203/300326784-278ad99c-c2d1-4dd7-a7a7-b8e2e15a44c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTk2NDgsIm5iZiI6MTcwNjQ5OTM0OCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMjY3ODQtMjc4YWQ5OWMtYzJkMS00ZGQ3LWE3YTctYjhlMmUxNWE0NGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MmI5N2MyN2JhNmIxNDE0NTU0ZmExOTYwNjM0NjQxYWMzMmM5MjJkNzhlMDZmNWYzMWJiYjVhMzgxODUyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpOhZdW7C8-t1S8PUVLiliTCJyY4HE068IK4hfUQ3-s">

你要想安装 2.4.x 应该是 ~2.4.4 而不是 ^2.4.4

**Comment by huanlirui** [comment]
> > > @huanlirui 你看看nodemodules里的element-plus依赖具体安装版本是不是2.4.4
> > 
> > 
> > 还真是 2.5.3 ，不好意思，还真是 2.5 的问题 ，在执行缓存清理后，再执行 pnpm i，为何还是拉的 2.5.3
> > ```
> > "clean": "pnpx rimraf node_modules",
> >     "clean:cache": "pnpx rimraf node_modules/.cache",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="363" src="https://private-user-images.githubusercontent.com/40491203/300326784-278ad99c-c2d1-4dd7-a7a7-b8e2e15a44c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTk2NDgsIm5iZiI6MTcwNjQ5OTM0OCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMjY3ODQtMjc4YWQ5OWMtYzJkMS00ZGQ3LWE3YTctYjhlMmUxNWE0NGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MmI5N2MyN2JhNmIxNDE0NTU0ZmExOTYwNjM0NjQxYWMzMmM5MjJkNzhlMDZmNWYzMWJiYjVhMzgxODUyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpOhZdW7C8-t1S8PUVLiliTCJyY4HE068IK4hfUQ3-s">
> 
> 你要想安装 2.4.x 应该是 ~2.4.4 而不是 ^2.4.4

### 感谢大神！🙏是我学艺不精了🤡

回答来自 gpt ：
> ^2.4.4 是一个语义化版本范围的符号，它表示安装的依赖包版本可以是 2.4.4 或者在 2.x.x 版本范围内的任何兼容版本。也就是说，当你运行 npm install 或者 yarn install 时，会尝试安装最新的符合兼容范围的版本。例如，如果有一个可用的 2.5.0 版本，那么它将会被安装。

**Comment by drylint** [comment]
> > 此修改会影响页面排版，甚至会导致某些深度使用的地方无法正常显示 但是并不是更新主版本号，仅仅只是更新了次版本号，并没有做向下兼容 极不负责的开源更新方式
> 
> 抱歉这次升级给你带来了不便。升级版本本身是件有风险的事情，次版本号一般是用来发布新特性与代码重构。如果要升级依赖版本，请先阅读更新日志。一些大的重构，PR 当中会列举修改内容，请注意查看。
> 
> 文档我们也会进一步优化，但是目前没有专人对更新日志整理，所以只能显示 PR 的名称。Element Plus 是社区开源的项目，欢迎更多开源人的共同参与维护。

「次版本号一般是用来发布新特性与代码重构」，这句话没问题，但你在重构的时候，加上了 BREAKING CHANGE 就不合理了吧。

个人觉得，作为一个用户众多的开源项目，还是应该克制一点，再忍受不了的设计要做破坏性变更，也应该留到下一个 Major 版本中去。

我认为，大部分用户都还是愿意相信大项目更能遵守版本约定，所以大部分用户在升级 minor 和 patch 版本时，都会比较放心的升级，我觉得除了 Major 版本的更新，也不应该要求所有用户在升级时查看所有的更新日志来确保自己是否能进行升级。

以上只是发表一下个人意见，最后，依然特别感谢您对开源的贡献，以及对组件样式复用、代码冗余等方面花费不少时间来做重构，Respect ！

**Comment by lxfljw** [comment]
shit 我就碰到这个问题了 莫名其妙给我select 加了个 11px 的宽度，布局完全变了，真的是乱搞，小版本不应该做这种破坏性改动！

**Comment by zzzpppy** [comment]
> > ### 同样的问题！宽度丢失，关键是为什么一部分 Ok一部分是有问题的？？
> > <img alt="image" width="1613" src="https://private-user-images.githubusercontent.com/40491203/300316375-e777adde-679f-41fe-99a9-d0c1f2f55452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTYzNzUtZTc3N2FkZGUtNjc5Zi00MWZlLTk5YTktZDBjMWYyZjU1NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTIzMjljMzc5YTUxMWFlYzE4Y2YxMDBjN2Q0NmNkMmQzYTg4OTM5NjRjODcyNzEzZjgwZjVmYzQxOThhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPWFaMojVBYpKAlPByKytrmZzHivksbuVLbpn1xb-j8">
> > #### 问题 出在这个行内样式，11px是个什么东西？
> > <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/40491203/300316500-19c6ace3-8fd5-4e85-9a8c-32a5286cabe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTU3MjAsIm5iZiI6MTcwNjQ5NTQyMCwicGF0aCI6Ii80MDQ5MTIwMy8zMDAzMTY1MDAtMTljNmFjZTMtOGZkNS00ZTg1LTlhOGMtMzJhNTI4NmNhYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MGRlZWU4M2I5N2U4MDdlYTRiNTRiM2Y3ZjlkOWJmYjRhNmI0M2QxZGE4ZGVlMWFhN2JhYzYwYTczNTE3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g9KyydXT1qKJH8uLm0dhIwPV4ipQe6dI72aSLr9ZAFk">
> 
> 这个11px是filterable时，最小的input宽度，根据输入文本长度自动变化宽度，在前面有tag时能够自动换行。
> 
> Select本身宽度是100%的，在行内布局时需要指定一个具体宽度，不然会宽度出现问题。

我这边也遇到一个使用filterable的时候,样式发生bug,在输入一个字符串的时候,字符串很短是正常的,字符串变长的时候,输入时,字符串前半部分会被选择框盖住,输入完成,后半部分会被盖住.

**Comment by lau96** [comment]
4个月了都不修复吗

**Comment by kooriookami** [comment]
应该在给inline的父容器设置一个宽度，而不是select默认加一个宽度。

**Comment by 1nFrastr** [comment]
如果是tailwindcss可以这样解决，使用正则表达式全局搜索替换：el-select(.*)class="w- 替换为 el-select$1class="!w- 设置tailwindcss宽度样式最高优先级

**Comment by yulimchen** [comment]
可以尝试添加全局样式：
```css
/* 内联表单默认宽度 */
.el-form--inline .el-form-item :where(
  .el-input,
  .el-cascader,
  .el-select,
  .el-date-editor,
  .el-autocomplete
) {
  width: 200px;
}
```
