### ISSUE TITLE
[Style] [select] [el-select] 远程搜索模式中，输入框内输入内容后加空格，内容会往前顶出select框

### ISSUE THREAD

**Issue by FloraCode-hyy** [element-plus/element-plus#15535]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.5.1`
- Browser / OS: ` Chrome/120.0.0.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

在select输入框内输入内容后输入空格

### What is Expected?

内容和空格都应该在输入框内展示

### What is actually happening?

实际上内容和空格会往左偏移，一直往左走

### Additional comments

_(empty)_

**Comment by qppq54s** [comment]
空格的问题应该出在宽度计算span，计算的span样式是whitespace: nowrap 默认会合并多个空格。
但是我尝试了输入多个1，也会出现类似问题，貌似calculatorRef.value.getBoundingClientRect().width 返回的结果并不准确

**Comment by qppq54s** [comment]
> 你只输入中文是不是就准确的，西文不准。那就是input字体没继承上去。

对的，但是输入中文的时候会出现这样的问题，在一次性输入的文字超出select宽度时，文字展示会有问题
<img width="275" alt="Snipaste_2024-01-16_16-20-02" src="https://github.com/element-plus/element-plus/assets/12963415/398bf9fc-a049-4bd4-b526-7b208200cf16">

**Comment by kooriookami** [comment]
这是正常的吧，文字长度超过input，宽度会左右滚动显示

**Comment by qppq54s** [comment]
嗯，那就是宽度计算的问题了。

**Comment by qppq54s** [comment]
@kooriookami 我看了下你的pr，只修改了字体继承问题，但是输入空格的时候还是会把文字顶到左侧外面。

```css
@include e(input-calculator) {
    position: absolute;
    left: 0;
    top: 0;
    max-width: 100%;
    visibility: hidden;
    white-space: preserve nowrap;
    overflow: hidden;
  }
```
修改这里的white-space可以解决这个问题

**Comment by kooriookami** [comment]
white-space没有preserve选项，pre可以
