### ISSUE TITLE
[Bug Report] When switching routes, there is a problem with highlighting in the sidebar

### ISSUE THREAD

**Issue by TuiMao233** [element-plus/element-plus#1553]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
win 10

### Vue version
3.0.5

### Reproduction Link
I'm sorry, I can't reproduce it
https://codesandbox.io/s/element-plus-spa-forked-73sx0

### Steps to reproduce
When there is a switching route, the route injection information is incorrect

### What is Expected?
Highlight normal

### What is actually happening?
When there is a switching route, the route injection information is incorrect

![image](https://user-images.githubusercontent.com/49724027/109646108-b6f6c780-7b92-11eb-8097-dd715915f545.png)

When switching, the index of the first item is /shop/my-shop, which is consistent with the default-active of the current el-menu, but it cannot be highlighted

![image](https://user-images.githubusercontent.com/49724027/109646227-e3aadf00-7b92-11eb-88cc-012bb65ce2ba.png)

But there is no problem with other items

![image](https://user-images.githubusercontent.com/49724027/109646651-6895f880-7b93-11eb-9e25-111bae572c58.png)

**Comment by Ryan2128** [comment]
You can update the vue's version try it again. Maybe a bug in `3.0.5`.

**Comment by TuiMao233** [comment]
> You can update the vue's version try it again. Maybe a bug in 3.0.5.

No, I upgraded the vue version to vue 3.0.7, the problem still exists, but I solved it this way

I used showAsideTwoLevel to control whether I display the secondary menu or not. I also used v-if in el-menu to regenerate the component, and the highlighting was displayed normally.

![image](https://user-images.githubusercontent.com/49724027/109648553-b4e23800-7b95-11eb-88b3-fda38cc74571.png)

This is amazing.......

![GIF](https://user-images.githubusercontent.com/49724027/109649081-5f5a5b00-7b96-11eb-8724-e3c4726584b2.gif)

**Comment by Ryan2128** [comment]
Can you provide me a repo? The online demo is invalid.

**Comment by TuiMao233** [comment]
I try to reproduce it. I don’t know how to date and use vue-router on these sites.

**Comment by TuiMao233** [comment]
I think of a way, the project is compressed into a file and sent to you, and then you try, the key code is in line 27 of src / layout / components / SideBar

[project.zip](https://github.com/element-plus/element-plus/files/6074130/project.zip)

**Comment by Ryan2128** [comment]
> I think of a way, the project is compressed into a file and sent to you, and then you try, the key code is in line 27 of src / layout / components / SideBar
> 
> [project.zip](https://github.com/element-plus/element-plus/files/6074130/project.zip)

OK, I will investigate it.

**Comment by JacBian** [comment]
+1,mark

**Comment by JacBian** [comment]
通过翻看源码，定位到问题了，侧边栏的菜单是动态的，而menu组件只拷贝了第一次传入的数据，所以导致匹配不到当前数据，无法高亮，通过强写组件内的activeIndex临时解决了

**Comment by JacBian** [comment]
> +1,mark

解决了，在menu-item和sub-menu加上key属性，并且绑定了path..
先前没有key，或者key为index的情况下，key可能因为相同，导致了menItem中的onMounted和onBeforeUnmount没有按预期的执行。
菜单是动态的..打脸了
