### ISSUE TITLE
[Component] [select] 2.5.X select default value empty string does not working

### ISSUE THREAD

**Issue by norangit** [element-plus/element-plus#15538]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `Chrome/120.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnJyxcbiAgICBsYWJlbDogJ0FMTCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

打开就能看到，默认值是空字符串，下拉列表是选中的，只是值没有回填到Select中去，

### What is Expected?

我个人理解严格来说，回填的值取值应该是 options.find(s => s.value === selected.value).label 类似这样的，如果是多选则是filter 数组，单选则是 find 单个值。这样无论默认值是什么都是用户所期望的，除非用户写错了默认值

### What is actually happening?

实际不是这样的行为

### Additional comments

_(empty)_

**Comment by YoungDan-hero** [comment]
```
  const hasModelValue = computed(() => {
    return props.multiple
      ? isArray(props.modelValue) && props.modelValue.length > 0
      : props.modelValue !== undefined &&
          props.modelValue !== null &&
          props.modelValue !== ''
  })
```
I have examined the source code of the select component and found that it excludes the case of an empty string when determining if a value is bound or not. I'm not sure whether this is by design or a bug. In my opinion, it could be a bug, because when the bound value is an empty string, it can still be properly selected and highlighted. If this is indeed a bug, I will submit a pull request to fix this issue.

**Comment by YoungDan-hero** [comment]
> ```
>   const hasModelValue = computed(() => {
>     return props.multiple
>       ? isArray(props.modelValue) && props.modelValue.length > 0
>       : props.modelValue !== undefined &&
>           props.modelValue !== null &&
>           props.modelValue !== ''
>   })
> ```
> 
> I have examined the source code of the select component and found that it excludes the case of an empty string when determining if a value is bound or not. I'm not sure whether this is by design or a bug. In my opinion, it could be a bug, because when the bound value is an empty string, it can still be properly selected and highlighted. If this is indeed a bug, I will submit a pull request to fix this issue.

I submitted a PR, but it failed some unit tests. Upon reviewing the unit test code, I found that it includes a condition that checks for empty strings. When the bound value is empty, the test expects a return of the default value 'DEFAULT_PLACEHOLDER'. However, this might cause an issue, as in reality, an option would be highlighted and selected when its value is an empty string.

**Comment by norangit** [comment]
thank you for your contribution very much. @YunYouJun what do you think? is this a bug or design point?

**Comment by YoungDan-hero** [comment]
@chenxch

**Comment by YunYouJun** [comment]
In [radix-vue](https://www.radix-vue.com/components/select.html), the empty value is not allowed and an error will occur.
Not using empty string value as value should be a recommended practice.

Element Plus didn't throw an error. 

I see default example in https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/select
It use `value=""` to display an default option as placeholder.

```html
<select name="pets" id="pet-select">
  <option value="">--Please choose an option--</option>
  <option value="cat">Cat</option>
  <option value="hamster">Hamster</option>
  <option value="parrot">Parrot</option>
  <option value="spider">Spider</option>
  <option value="goldfish">Goldfish</option>
</select>
```

So i think you are right, when we click `value=''` option, it should display the label.

I need more advice.
CC @element-plus/backers 

---

@YoungDan-hero I think the priority is option > placeholder. Maybe we need to add additional tests.

**Comment by btea** [comment]
I agree with @YunYouJun  and @YoungDan-hero .

**Comment by FrontEndDog** [comment]
@YoungDan-hero 

我认为组件的表现应该与原生组件一致，我们可以需要修改一下测试用例。

I think the expectations of `el-select` should be consistent with that of native components，We may need to modify the test cases.

**Comment by YoungDan-hero** [comment]
> @YoungDan-hero
> 
> 我认为组件的表现应该与原生组件一致，我们可能需要修改一下测试用例。
> 
> I think the expectations of `el-select` should be consistent with that of native components，We may need to modify the test cases.

Okay, thank you very much for your explanation

**Comment by chwech** [comment]
same issue.

**Comment by norangit** [comment]
Hi @YoungDan-hero, any update?
is the fix ready for next release?

**Comment by ZhaoLLe** [comment]
same issue.
I need an empty string to represent all.

**Comment by kooriookami** [comment]
Many people use empty string as empty value, and someone use use empty string as option value. There's a conflict.

**Comment by ZhaoLLe** [comment]
How do you intend to address this issue? @kooriookami 
Do we need to wait for your updates?

**Comment by kooriookami** [comment]
@ZhaoLLe please see the PR blow.
