### ISSUE TITLE
[Component] [image] 2.5.1版本 el-image组件存在跨域问题，使用原生image组件正常

### ISSUE THREAD

**Issue by wuxiandashu** [element-plus/element-plus#15555]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `chorme`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

 <el-image src="http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg" size="small"  :preview-src-list="['http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg']"></el-image>

### What is Expected?

 <el-image src="http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg" size="small"  :preview-src-list="['http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg']"></el-image>

### What is actually happening?

 <el-image src="http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg" size="small"  :preview-src-list="['http://atjoss.df0535.cn/ptm/pf_0/2024-01-15/2024-01-15_1705306484622_0.jpg']"></el-image>

### Additional comments

设置crossorigin =null正常现实，但是预览功能异常

**Comment by Cheerwhy** [comment]
这个我看已经有pr合并 https://github.com/element-plus/element-plus/pull/15511
下个版本就修复了

**Comment by wuxiandashu** [comment]
还没修复

**Comment by kooriookami** [comment]
Fixed
