### ISSUE TITLE
[Component] [tree] elTree拖拽时不能使用鼠标滚轮进行滚动

### ISSUE THREAD

**Issue by DragonGoBC** [element-plus/element-plus#15567]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `chome`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Link](暂无)

### Steps to reproduce

按照网址复现

### What is Expected?

拖拽时可以使用鼠标进行滚动

### What is actually happening?

拖拽时不能滚动

### Additional comments

_(empty)_

**Comment by DragonGoBC** [comment]
复现网址：https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICA6YWxsb3ctZHJvcD1cImFsbG93RHJvcFwiXG4gICAgOmFsbG93LWRyYWc9XCJhbGxvd0RyYWdcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgZHJhZ2dhYmxlXG4gICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgQG5vZGUtZHJhZy1zdGFydD1cImhhbmRsZURyYWdTdGFydFwiXG4gICAgQG5vZGUtZHJhZy1lbnRlcj1cImhhbmRsZURyYWdFbnRlclwiXG4gICAgQG5vZGUtZHJhZy1sZWF2ZT1cImhhbmRsZURyYWdMZWF2ZVwiXG4gICAgQG5vZGUtZHJhZy1vdmVyPVwiaGFuZGxlRHJhZ092ZXJcIlxuICAgIEBub2RlLWRyYWctZW5kPVwiaGFuZGxlRHJhZ0VuZFwiXG4gICAgQG5vZGUtZHJvcD1cImhhbmRsZURyb3BcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcbmltcG9ydCB0eXBlIHsgRHJhZ0V2ZW50cyB9IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL3VzZURyYWdOb2RlJ1xuaW1wb3J0IHR5cGUge1xuICBBbGxvd0Ryb3BUeXBlLFxuICBOb2RlRHJvcFR5cGUsXG59IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL3RyZWUudHlwZSdcblxuY29uc3QgaGFuZGxlRHJhZ1N0YXJ0ID0gKG5vZGU6IE5vZGUsIGV2OiBEcmFnRXZlbnRzKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdkcmFnIHN0YXJ0Jywgbm9kZSlcbn1cbmNvbnN0IGhhbmRsZURyYWdFbnRlciA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVudGVyOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ0xlYXZlID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgbGVhdmU6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnT3ZlciA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCBldjogRHJhZ0V2ZW50cykgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIG92ZXI6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnRW5kID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBkcm9wVHlwZTogTm9kZURyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgZW5kOicsIGRyb3BOb2RlICYmIGRyb3BOb2RlLmxhYmVsLCBkcm9wVHlwZSlcbn1cbmNvbnN0IGhhbmRsZURyb3AgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGRyb3BUeXBlOiBOb2RlRHJvcFR5cGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJvcDonLCBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG59XG5jb25zdCBhbGxvd0Ryb3AgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlLCBkcm9wTm9kZTogTm9kZSwgdHlwZTogQWxsb3dEcm9wVHlwZSkgPT4ge1xuICBpZiAoZHJvcE5vZGUuZGF0YS5sYWJlbCA9PT0gJ0xldmVsIHR3byAzLTEnKSB7XG4gICAgcmV0dXJuIHR5cGUgIT09ICdpbm5lcidcbiAgfSBlbHNlIHtcbiAgICByZXR1cm4gdHJ1ZVxuICB9XG59XG5jb25zdCBhbGxvd0RyYWcgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlKSA9PiB7XG4gIHJldHVybiAhZHJhZ2dpbmdOb2RlLmRhdGEubGFiZWwuaW5jbHVkZXMoJ0xldmVsIHRocmVlIDMtMS0xJylcbn1cblxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgXG4gICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0zJyxcbiAgICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS00JyxcbiAgICAgICAgICAgIH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNScsfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS02Jyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNycsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTknLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtOCcsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEwJyx9LHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTExJyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTInLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTMnLH1cbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0zJyxcbiAgICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS00JyxcbiAgICAgICAgICAgIH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNScsfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS02Jyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNycsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTknLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtOCcsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEwJyx9LHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTExJyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTInLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTMnLH1cbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0zJyxcbiAgICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS00JyxcbiAgICAgICAgICAgIH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNScsfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS02Jyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNycsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTknLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtOCcsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEwJyx9LHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTExJyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTInLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTMnLH1cbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0zJyxcbiAgICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS00JyxcbiAgICAgICAgICAgIH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNScsfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS02Jyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNycsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTknLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtOCcsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEwJyx9LHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTExJyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTInLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTMnLH1cbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0zJyxcbiAgICAgICAgICAgfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS00JyxcbiAgICAgICAgICAgIH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNScsfSx7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS02Jyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtNycsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTknLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtOCcsfSx7XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEwJyx9LHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTExJyx9LHtcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTInLH0se1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMTMnLH1cbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==

**Comment by chenxch** [comment]
![截屏2024-01-17 17 05 28](https://github.com/element-plus/element-plus/assets/23251408/cfee7e5c-eabf-499a-9291-568d514831d0)
未复现

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/a0d3db96-6bbb-451d-911a-12013a69de00

**Comment by DragonGoBC** [comment]
不是拖拽的时候自动滚动，想要可以利用鼠标的滚轮进行滚动
