### ISSUE TITLE
[Component] [select-v2] help me, I don't know what's happening / 帮帮我，我不知道发生了什么

### ISSUE THREAD

**Issue by leeobrum** [element-plus/element-plus#15586]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `Edg/117.0.2045.31 (Wind64)`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgYUxpc3RGaWxpYWwgZnJvbSAnLi9hbGlzdEZpbGlhbC5qcydcblxuY29uc3QgYk9wZW49cmVmKGZhbHNlKVxuY29uc3QgYk9wZW4xPXJlZihmYWxzZSlcbmNvbnN0IGFMaXN0RmlsaWFpc01vZGVsPXJlZihbXSlcbmNvbnN0IGRlZmF1bHRGb3JtID0ge1xuICBzRmlsUGFkOiBbXVxufVxuY29uc3Qgb0Zvcm11bGFyaW9DYWRhc3Rybz1yZWYoT2JqZWN0LmFzc2lnbih7fSwgZGVmYXVsdEZvcm0pKVxuXG5vbk1vdW50ZWQoYXN5bmMgKCkgPT4ge1xuICBjb25zdCBhR2V0TGlzdEZpbGlhaXMgPSBhd2FpdCBhTGlzdEZpbGlhbCBhcyBhbnlbXVxuICBmb3IgKGxldCB7IHZhbHVlLCBsYWJlbCB9IG9mIGFHZXRMaXN0RmlsaWFpcykge1xuICAgIGFMaXN0RmlsaWFpc01vZGVsLnZhbHVlLnB1c2goeyB2YWx1ZTogdmFsdWUsIGxhYmVsOiBsYWJlbCB9KVxuICB9XG59KVxuXG5jb25zdCBvcGVuID0gKCkgPT4ge1xub0Zvcm11bGFyaW9DYWRhc3Ryby52YWx1ZS5zRmlsUGFkID0gW11cbmNvbnN0IHNFeGlzdCA9IGxvY2FsU3RvcmFnZS5nZXRJdGVtKCdzYXZlU2VsZWN0JylcbiAgaWYoc0V4aXN0KXtcbiAgICBvRm9ybXVsYXJpb0NhZGFzdHJvLnZhbHVlLnNGaWxQYWQgPSBKU09OLnBhcnNlKHNFeGlzdClcbiAgfVxuICBiT3Blbi52YWx1ZSA9IHRydWVcbn1cbmNvbnN0IGNoYW5nZWQgPSAoKSA9PiB7XG4gIGJPcGVuMS52YWx1ZSA9IHRydWVcbn1cbmNvbnN0IHNhdmUgPSAoKSA9PiB7XG4gIGxvY2FsU3RvcmFnZS5zZXRJdGVtKCdzYXZlU2VsZWN0JywgSlNPTi5zdHJpbmdpZnkob0Zvcm11bGFyaW9DYWRhc3Ryby52YWx1ZS5zRmlsUGFkKSlcbiAgYk9wZW4udmFsdWUgPSBmYWxzZVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9wZW5cIj5DbGljazwvZWwtYnV0dG9uPlxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImJPcGVuXCJcbiAgICB3aWR0aD1cIjgwJVwiXG4gID5cbiAgICA8ZWwtc2VsZWN0LXYyXG4gICAgICBwbGFjZWhvbGRlcj1cIkZpbGlhbFwiXG4gICAgICB2LW1vZGVsPVwib0Zvcm11bGFyaW9DYWRhc3Ryby5zRmlsUGFkXCJcbiAgICAgIDpvcHRpb25zPVwiYUxpc3RGaWxpYWlzTW9kZWxcIlxuICAgICAgQGNoYW5nZT1cImNoYW5nZWRcIlxuICAgICAgY2xlYXJhYmxlXG4gICAgLz5cbiAgICA8ZWwtYnV0dG9uIHYtaWY9XCJiT3BlbjFcIiBAY2xpY2s9XCJzYXZlXCIgc3R5bGU9XCJtYXJnaW4tdG9wOiAxMHB4O1wiPnNhdmU8L2VsLWJ1dHRvbj5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2FsaXN0RmlsaWFsLmpzIjoiY29uc3QgYUxpc3RGaWxpYWlzTW9kZWwgPSBbXHJcbiAgeyB2YWx1ZTogJzAwJywgbGFiZWw6ICdOT1ZBIFBSQVRBJyB9LFxyXG4gIHsgdmFsdWU6ICcwMScsIGxhYmVsOiAnQkVOVE8gR09Ow4dBTFZFUycgfSxcclxuICB7IHZhbHVlOiAnMDInLCBsYWJlbDogJ1NBTlRBIENSVVogRE8gU1VMJyB9LFxyXG4gIHsgdmFsdWU6ICcwMycsIGxhYmVsOiAnUE9SVE8gQUxFR1JFJyB9LFxyXG4gIHsgdmFsdWU6ICcwNicsIGxhYmVsOiAnU0FOVEEgTUFSSUEnIH0sXHJcbiAgeyB2YWx1ZTogJzA3JywgbGFiZWw6ICdOT1ZPIEhBTUJVUkdPJyB9LFxyXG4gIHsgdmFsdWU6ICcwOCcsIGxhYmVsOiAnUEFTU08gRlVORE8nIH0sXHJcbiAgeyB2YWx1ZTogJzEwJywgbGFiZWw6ICdQRUxPVEFTJyB9XHJcbl1cclxuXHJcbmV4cG9ydCBkZWZhdWx0IGFMaXN0RmlsaWFpc01vZGVsXHJcbiIsIl9vIjp7fX0=)

### Steps to reproduce

It's in the code above / 就在上面的代码中

### What is Expected?

take the label / 拿标签

### What is actually happening?

take the value / 价值

### Additional comments

In the example shown it works, but in my code it doesn't, what can I do wrong?
In version "element-plus": "^2.4.4" - it worked

在显示的示例中它可以工作，但在我的代码中却不能，我能做错什么？
在版本“element-plus”中：“^2.4.4” - 它有效

![image](https://github.com/element-plus/element-plus/assets/28123085/3dc1acaf-8417-4474-9f6c-a6dfdfe4890d)
![image](https://github.com/element-plus/element-plus/assets/28123085/ebf8e869-12f8-4e5c-baf0-65ab1378df0a)

**Comment by leeobrum** [comment]
My exemple / 我的例子

![image](https://github.com/element-plus/element-plus/assets/28123085/d11ebd6e-fcda-4437-960e-dafb5f519041)

![image](https://github.com/element-plus/element-plus/assets/28123085/2f9538b9-2a68-4772-8109-9174c7837f50)

**Comment by chenxch** [comment]
@leeobrum It should be that the component did not update the matching result after the option returned. You can consider giving the component a new key and refreshing the component after the option returned to solve it temporarily.

**Comment by leeobrum** [comment]
@chenxch Can you tell me if this behavior was changed in this latest version? because in the element-plus" version: "^2.4.4" it worked.
I saw the update packages and there were many changes to this el-select and el-select-v2 method

**Comment by leeobrum** [comment]
Sorted out! I realized that my variable wasn't even finding the value in the array. So decide to make a promise to wait for it to load and then find the value. It worked out! If someone could check the code if it is ok

![image](https://github.com/element-plus/element-plus/assets/28123085/ad879e01-9615-4180-9da3-feced63de143)

**Comment by chenxch** [comment]
> @chenxch Can you tell me if this behavior was changed in this latest version? because in the element-plus" version: "^2.4.4" it worked. I saw the update packages and there were many changes to this el-select and el-select-v2 method

#15352

**Comment by leeobrum** [comment]
Thank you very much
