### ISSUE TITLE
[Component] menu Collapse 折叠面板 特殊情况收缩卡

### ISSUE THREAD

**Issue by dustfreenj** [element-plus/element-plus#15581]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `mac os ventura 13.1`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`
- `el-sub-menu`
- `el-menu-item-group`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/sandbox/an-niu-lei-xing-ant-design-vue-4-1-0-gh3xqd)

### Steps to reproduce

<template>
  <el-radio-group v-model="isCollapse" style="margin-bottom: 20px">
    <el-radio-button :label="false">expand</el-radio-button>
    <el-radio-button :label="true">collapse</el-radio-button>
  </el-radio-group>
  <el-menu
    default-active="2"
    class="el-menu-vertical-demo"
    :collapse="isCollapse"
    @open="handleOpen"
    @close="handleClose"
  >
    <el-sub-menu index="1">
      <template #title>
        <el-icon><location /></el-icon>
        <span>Navigator One</span>
      </template>
      <el-menu-item-group>
        <template #title><span>Group One</span></template>
        <el-menu-item index="1-1">item one</el-menu-item>
        <el-menu-item index="1-2">item two</el-menu-item>
      </el-menu-item-group>
      <el-menu-item-group title="Group Two">
        <el-menu-item index="1-3">item three</el-menu-item>
      </el-menu-item-group>
      <el-sub-menu index="1-4">
        <template #title><span>item four</span></template>
        <el-menu-item index="1-4-1">item one</el-menu-item>
      </el-sub-menu>
    </el-sub-menu>
    <el-menu-item index="2">
      <el-icon><icon-menu /></el-icon>
      <template #title>Navigator Two</template>
    </el-menu-item>
    <el-menu-item index="3" disabled>
      <el-icon><document /></el-icon>
      <template #title>Navigator Three</template>
    </el-menu-item>
    <el-sub-menu index="4">
     <template #title><span>item four</span></template>
        <el-menu-item index="4-4-10">item one</el-menu-item>
         <el-menu-item index="4-4-2">item one1</el-menu-item>
          <el-menu-item index="4-4-3">item one3</el-menu-item>
           <el-menu-item index="4-4-4">item one2</el-menu-item>
    </el-sub-menu>
  </el-menu>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import {
  Document,
  Menu as IconMenu,
  Location,
  Setting,
} from '@element-plus/icons-vue'

const isCollapse = ref(true)
const handleOpen = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
const handleClose = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
</script>

<style>
.el-menu-vertical-demo:not(.el-menu--collapse) {
  width: 200px;
  min-height: 400px;
}
</style>

### What is Expected?

item four 这个标题点击的时候上下收缩的动画会卡顿，就是用的官网在线代码加下，原有代码正好避开了有多个下拉子菜单的情况

### What is actually happening?

像第一个菜单一样收缩很丝滑

### Additional comments

就在官网上面最后一个例子的代码贴进去就能复现,在线地址随便填的请忽略

**Comment by chenxch** [comment]
请填写正确repo地址，可以是官网Collapse组件链接。其次是请提供录屏或者其他能复现卡顿的信息，我这边未复现。

**Comment by dustfreenj** [comment]
[](url) 点第二个选项的时候向上收缩的时候很明显，一顿顿的，点 第一个选项很丝滑

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/232f2300-8211-4584-81eb-fedf94d4879a

帧率稳定，方便的话也一样录个屏幕

**Comment by dustfreenj** [comment]
[me](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJpc0NvbGxhcHNlXCIgc3R5bGU9XCJtYXJnaW4tYm90dG9tOiAyMHB4XCI+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCJmYWxzZVwiPmV4cGFuZDwvZWwtcmFkaW8tYnV0dG9uPlxuICAgIDxlbC1yYWRpby1idXR0b24gOmxhYmVsPVwidHJ1ZVwiPmNvbGxhcHNlPC9lbC1yYWRpby1idXR0b24+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDxlbC1tZW51XG4gICAgZGVmYXVsdC1hY3RpdmU9XCIyXCJcbiAgICBjbGFzcz1cImVsLW1lbnUtdmVydGljYWwtZGVtb1wiXG4gICAgOmNvbGxhcHNlPVwiaXNDb2xsYXBzZVwiXG4gICAgQG9wZW49XCJoYW5kbGVPcGVuXCJcbiAgICBAY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIxXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICA8ZWwtaWNvbj48bG9jYXRpb24gLz48L2VsLWljb24+XG4gICAgICAgIDxzcGFuPk5hdmlnYXRvciBPbmU8L3NwYW4+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT48c3Bhbj5Hcm91cCBPbmU8L3NwYW4+PC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICA8ZWwtbWVudS1pdGVtLWdyb3VwIHRpdGxlPVwiR3JvdXAgVHdvXCI+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjEtNFwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPjxzcGFuPml0ZW0gZm91cjwvc3Bhbj48L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS00LTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuXG48ZWwtc3ViLW1lbnUgaW5kZXg9XCI0LTRcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT48c3Bhbj5pdGVtIGZvdXI8L3NwYW4+PC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjQtNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtMTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtMjFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNC00LTMxXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtNDFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtNTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNC00LTYxXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtNzFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtODFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNC00LTkxXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0LTQtMTAwXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNC00LTEwMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBEb2N1bWVudCxcbiAgTWVudSBhcyBJY29uTWVudSxcbiAgTG9jYXRpb24sXG4gIFNldHRpbmcsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBpc0NvbGxhcHNlID0gcmVmKHRydWUpXG5jb25zdCBoYW5kbGVPcGVuID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5lbC1tZW51LXZlcnRpY2FsLWRlbW86bm90KC5lbC1tZW51LS1jb2xsYXBzZSkge1xuICB3aWR0aDogMjAwcHg7XG4gIG1pbi1oZWlnaHQ6IDQwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by dustfreenj** [comment]
<template>
  <el-radio-group v-model="isCollapse" style="margin-bottom: 20px">
    <el-radio-button :label="false">expand</el-radio-button>
    <el-radio-button :label="true">collapse</el-radio-button>
  </el-radio-group>
  <el-menu
    default-active="2"
    class="el-menu-vertical-demo"
    :collapse="isCollapse"
    @open="handleOpen"
    @close="handleClose"
  >
    <el-sub-menu index="1">
      <template #title>
        <el-icon><location /></el-icon>
        <span>Navigator One</span>
      </template>
      <el-menu-item-group>
        <template #title><span>Group One</span></template>
        <el-menu-item index="1-1">item one</el-menu-item>
        <el-menu-item index="1-2">item two</el-menu-item>
      </el-menu-item-group>
      <el-menu-item-group title="Group Two">
        <el-menu-item index="1-3">item three</el-menu-item>
      </el-menu-item-group>
      <el-sub-menu index="1-4">
        <template #title><span>item four</span></template>
        <el-menu-item index="1-4-1">item one</el-menu-item>
      </el-sub-menu>
    </el-sub-menu>

<el-sub-menu index="4-4">
        <template #title><span>item four</span></template>
        <el-menu-item index="4-4-1">item one</el-menu-item>
         <el-menu-item index="4-4-11">item one</el-menu-item>
          <el-menu-item index="4-4-21">item one</el-menu-item>
           <el-menu-item index="4-4-31">item one</el-menu-item>
            <el-menu-item index="4-4-41">item one</el-menu-item>
             <el-menu-item index="4-4-51">item one</el-menu-item>
              <el-menu-item index="4-4-61">item one</el-menu-item>
               <el-menu-item index="4-4-71">item one</el-menu-item>
                <el-menu-item index="4-4-81">item one</el-menu-item>
                 <el-menu-item index="4-4-91">item one</el-menu-item>
                  <el-menu-item index="4-4-100">item one</el-menu-item>
                   <el-menu-item index="4-4-101">item one</el-menu-item>

      </el-sub-menu>
  </el-menu>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import {
  Document,
  Menu as IconMenu,
  Location,
  Setting,
} from '@element-plus/icons-vue'

const isCollapse = ref(true)
const handleOpen = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
const handleClose = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
</script>

<style>
.el-menu-vertical-demo:not(.el-menu--collapse) {
  width: 200px;
  min-height: 400px;
}
</style>

**Comment by dustfreenj** [comment]
https://element-plus.gitee.io/zh-CN/component/menu.html#%E4%BE%A7%E6%A0%8F  是这个搞错了

**Comment by dustfreenj** [comment]
视频录了传不过去，20M 只能传10M

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/assets/23251408/597f9efc-6aeb-4d05-afff-f324c82c48cd

**Comment by chenxch** [comment]
我大概知道了，你可以看一下 #10570

**Comment by chenxch** [comment]
设备是windows 独显么 @dustfreenj

**Comment by dustfreenj** [comment]
对是这个意思， 点itemfour收缩的时候 你仔细观察下，尤其明显，我是MAC m1pro ，我把动画CSS注掉了就没有这问题，不知道为什么，一个下拉项就不卡，两个更多很明显

**Comment by kooriookami** [comment]
你是用Firefox试试看还卡不卡，这个有可能是Chrome的问题

**Comment by dustfreenj** [comment]
还是不行，Firefox，safari 都试过了，一样的效果
