### ISSUE TITLE
[Component] [select] el-select 的 tag 插槽在单选模式下不生效

### ISSUE THREAD

**Issue by Lionad-Morotar** [element-plus/element-plus#15580]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `Microsoft Edge 版本 120.0.2210.133 (正式版本) (64 位)`
- Build Tool: `CDN`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBtdWx0aXBsZSA6bXVsdGlwbGUtbGltaXQ9XCIxXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiBzdHlsZT1cIndpZHRoOiAyNDBweFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBjb2xvcnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZmxleCBpdGVtcy1jZW50ZXJcIj5cbiAgICAgICAgPGVsLXRhZyA6Y29sb3I9XCJpdGVtLnZhbHVlXCIgc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDhweFwiIHNpemU9XCJzbWFsbFwiIC8+XG4gICAgICAgIDxzcGFuIDpzdHlsZT1cInsgY29sb3I6IGl0ZW0udmFsdWUgfVwiPnt7IGl0ZW0ubGFiZWwgfX08L3NwYW4+XG4gICAgICA8L2Rpdj5cbiAgICA8L2VsLW9wdGlvbj5cbiAgICA8dGVtcGxhdGUgI3RhZz5cbiAgICAgIDxlbC10YWcgdi1mb3I9XCJjb2xvciBpbiB2YWx1ZVswXSA/IFt2YWx1ZVswXV0gOiBbXVwiIDprZXk9XCJjb2xvci52YWx1ZVwiIDpjb2xvcj1cImNvbG9yXCIgLz5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXNlbGVjdD5cblxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIj5cbiAgICA8dGVtcGxhdGUgI3RhZz5cbiAgICAgIDxlbC10YWcgdi1mb3I9XCJjb2xvciBpbiB2YWx1ZVswXSA/IFt2YWx1ZVswXV0gOiBbXVwiIDprZXk9XCJjb2xvci52YWx1ZVwiIDpjb2xvcj1cImNvbG9yXCIgLz5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKFtdKVxuY29uc3QgY29sb3JzID0gW1xuICB7XG4gICAgdmFsdWU6ICcjRTYzNDE1JyxcbiAgICBsYWJlbDogJ3JlZCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJyNGRjY2MDAnLFxuICAgIGxhYmVsOiAnb3JhbmdlJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnI0ZGREUwQScsXG4gICAgbGFiZWw6ICd5ZWxsb3cnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICcjMUVDNzlEJyxcbiAgICBsYWJlbDogJ2dyZWVuJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnIzE0Q0NDQycsXG4gICAgbGFiZWw6ICdjeWFuJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnIzQxNjdGMCcsXG4gICAgbGFiZWw6ICdibHVlJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnIzYyMjJDOScsXG4gICAgbGFiZWw6ICdwdXJwbGUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtdGFnIHtcbiAgYm9yZGVyOiBub25lO1xuICBhc3BlY3QtcmF0aW86IDE7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 打开复现环境
2. 在第一个 select 随便选择一种颜色

### What is Expected?

两个 select 的 tag slot 的代码是一样的。
但是第一个 select 中有显示 tag slot，但是第二个 select 中没有显示任何内容

### What is actually happening?

两个 select 都应当显示内容。

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/26913795/b54dab9f-2dc9-48a2-b3ce-8109a913a8b7)

**Comment by chenxch** [comment]
首先你的demo代码存在错误，这个自己研究。其次本身tag功能就是为多选设计的，用于隔开选项，单选tag不是多此一举？

**Comment by kooriookami** [comment]
Tag插槽只对多选模式生效。

**Comment by Lionad-Morotar** [comment]
> 首先你的demo代码存在错误，这个自己研究。
是指运算优先级问题吧，抱歉，在复现代码中出现了这样的错误（

**Comment by wzc520pyfm** [comment]
> > 首先你的demo代码存在错误，这个自己研究。
> 
> 是指运算优先级问题吧，抱歉，在复现代码中出现了这样的错误（
> 
> 建这个 issue 起源于我想替换掉单选模式下 el-select 展示的选中的值。tag 插槽出现之前，el-select 只能通过 prefix 插槽去改变显示。然而，在我的印象中，el-select 的 prefix 的样式是不正确的，而且这个问题许久没有处理（见 [#10644](https://github.com/element-plus/element-plus/issues/10644)），所以对新的 tag 插槽抱有期待。
> 
> 现在，我能理解 tag 只适用于多选模式这一设计。请问除了 prefix 或者 tag 有没有更合适的方法去修改 el-select 中的内容呢

The styling issue with the prefix has been fixed in version 2.5.0. Can the [custom template](https://element-plus.org/en-US/component/select.html#custom-template) meet your requirements?

**Comment by chenxch** [comment]
手动画一个select框，把el-select隐藏起来，这样结果的渲染就都可以自己处理了。

**Comment by Lionad-Morotar** [comment]
> 手动画一个select框，把el-select隐藏起来，这样结果的渲染就都可以自己处理了。

这能解决问题，但不是一个合适的方法。也许应该给 ElSelect 新增一个插槽来表示“选中”的内容？

**Comment by chenxch** [comment]
当然最好的方法是新增插槽，但是没这么快哦。
新增插槽可能还需要考虑是否要把tag插槽收敛进去之类的。

**Comment by zhouxianjun** [comment]
> > 手动画一个select框，把el-select隐藏起来，这样结果的渲染就都可以自己处理了。
> 
> 这能解决问题，但不是一个合适的方法。也许应该给 ElSelect 新增一个插槽来表示“选中”的内容？
> 
> 对用户和开发者而言，Select 是选中内容而不是字符输入，这是符合直觉的，所以既然 Option 可以自定义的话，Select 所选中的内容也应该可以自定义。

+1 我们也需要自己渲染已选择的内容，比如人员选择，需要显示头像，或者有些直接不用tag，而是用文字的方式分隔：aaa,bbb,ccc,dd...
![img_v3_02an_0f5e68a3-979c-43c1-bc91-4e743031aa2g](https://github.com/element-plus/element-plus/assets/5254523/9ea7edca-d5b8-4682-88b5-aa2b494cab29)

**Comment by kooriookami** [comment]
> > > 手动画一个select框，把el-select隐藏起来，这样结果的渲染就都可以自己处理了。
> > 
> > 
> > 这能解决问题，但不是一个合适的方法。也许应该给 ElSelect 新增一个插槽来表示“选中”的内容？
> > 对用户和开发者而言，Select 是选中内容而不是字符输入，这是符合直觉的，所以既然 Option 可以自定义的话，Select 所选中的内容也应该可以自定义。
> 
> +1 我们也需要自己渲染已选择的内容，比如人员选择，需要显示头像，或者有些直接不用tag，而是用文字的方式分隔：aaa,bbb,ccc,dd... ![img_v3_02an_0f5e68a3-979c-43c1-bc91-4e743031aa2g](https://private-user-images.githubusercontent.com/5254523/333026407-9ea7edca-d5b8-4682-88b5-aa2b494cab29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDQ4ODgsIm5iZiI6MTcxNjQ0NDU4OCwicGF0aCI6Ii81MjU0NTIzLzMzMzAyNjQwNy05ZWE3ZWRjYS1kNWI4LTQ2ODItODhiNS1hYTJiNDk0Y2FiMjkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDYwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY4ZjZiYmVhM2FiOTIwMTdiMGZiMGI1YzhjN2YzY2NmNTQ3ZGUxZWZkZmVkZmE4NTVhOWVlOTUyOGM1NDc1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ow5Z5txNnx6zb8XdODt8_n-JmFf40PZY5VhZuKR9Ojw)

#16960
