### ISSUE TITLE
[Component] [tree] el-tree 拖拽禁用未被阻止

### ISSUE THREAD

**Issue by yfttgdzy** [element-plus/element-plus#15591]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHR5cGUgTm9kZSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC9ub2RlJ1xuaW1wb3J0IHR5cGUge1xuICBBbGxvd0Ryb3BUeXBlLFxuICBOb2RlRHJvcFR5cGUsXG59IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL3RyZWUudHlwZSdcblxuXG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ25hbWUnLFxufVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbmFtZTogJ3Rlc3QnLFxuICAgIGZ1bGxuYW1lOiBudWxsLFxuICAgIGNvbG9yOiBudWxsLFxuICAgIG5vZGVLZXk6ICcvMS8nLFxuICAgIHByZXNldDogbnVsbCxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMixcbiAgICAgICAgbmFtZTogJzIyJyxcbiAgICAgICAgZnVsbG5hbWU6IG51bGwsXG4gICAgICAgIGNvbG9yOiBudWxsLFxuICAgICAgICBub2RlS2V5OiAnLzIvJyxcbiAgICAgICAgcHJlc2V0OiBudWxsLFxuICAgICAgICBjaGlsZHJlbjogbnVsbCxcbiAgICAgICAgZXh0cmE6IG51bGwsXG4gICAgICB9LFxuICAgIF0sXG4gICAgZXh0cmE6IG51bGwsXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBuYW1lOiAnNjYnLFxuICAgIGZ1bGxuYW1lOiBudWxsLFxuICAgIGNvbG9yOiBudWxsLFxuICAgIG5vZGVLZXk6ICcvMy8nLFxuICAgIHByZXNldDogbnVsbCxcbiAgICBjaGlsZHJlbjogbnVsbCxcbiAgICBleHRyYTogbnVsbCxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIG5hbWU6ICcxMTExJyxcbiAgICBmdWxsbmFtZTogbnVsbCxcbiAgICBjb2xvcjogbnVsbCxcbiAgICBub2RlS2V5OiAnLzQvJyxcbiAgICBwcmVzZXQ6IG51bGwsXG4gICAgY2hpbGRyZW46IG51bGwsXG4gICAgZXh0cmE6IG51bGwsXG4gIH0sXG5dXG5cbmNvbnN0IGFsbG93RHJvcCA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCB0eXBlOiBBbGxvd0Ryb3BUeXBlKSA9PiB7XG4gIGlmIChcbiAgICAoZHJhZ2dpbmdOb2RlLnBhcmVudC5kYXRhWydub2RlS2V5J10gPT09IGRyb3BOb2RlLmRhdGFbJ25vZGVLZXknXSAmJiB0eXBlID09PSAnaW5uZXInKSB8fFxuICAgIChkcmFnZ2luZ05vZGUucGFyZW50LmRhdGFbJ25vZGVLZXknXSA9PT0gZHJvcE5vZGUucGFyZW50LmRhdGFbJ25vZGVLZXknXSAmJiB0eXBlICE9PSAnaW5uZXInKVxuICApIHtcblxuICBjb25zb2xlLmxvZygnZHJhZycsIGRyYWdnaW5nTm9kZSwgZHJvcE5vZGUsIHR5cGUpXG4gICAgcmV0dXJuIHRydWU7XG4gIH1cbiAgY29uc29sZS5sb2coJ2ZhbHNlJylcbiAgcmV0dXJuIGZhbHNlO1xufVxuY29uc3QgYWxsb3dEcmFnID0gKGRyYWdnaW5nTm9kZTogTm9kZSkgPT4ge1xuICBpZiAoZHJhZ2dpbmdOb2RlLmxldmVsID09PSAxKSB7XG4gICAgcmV0dXJuIGZhbHNlO1xuICB9XG4gIHJldHVybiB0cnVlO1xufVxuY29uc3QgaGFuZGxlRHJvcCA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCBkcm9wVHlwZTogTm9kZURyb3BUeXBlKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdkcm9wJywgZHJhZ2dpbmdOb2RlLCBkcm9wTm9kZSwgZHJvcFR5cGUpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC10cmVlXG4gICAgOmFsbG93LWRyb3A9XCJhbGxvd0Ryb3BcIlxuICAgIDphbGxvdy1kcmFnPVwiYWxsb3dEcmFnXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIG5vZGUta2V5PVwibm9kZWtleVwiXG4gICAgZHJhZ2dhYmxlXG4gICAgOnByb3BzPVwiZGVmYXVsdFByb3BzXCJcbiAgICBAbm9kZS1kcm9wPVwiaGFuZGxlRHJvcFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmVsLXRyZWUge1xuICAuZWwtdHJlZS1ub2RlX19jb250ZW50IHtcbiAgICBtYXJnaW4tYm90dG9tOiA4cHg7XG4gICAgaGVpZ2h0OiA0MHB4O1xuICAgIGxpbmUtaGVpZ2h0OiA0MHB4O1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIGJvcmRlci1yYWRpdXM6IDIwcHg7XG4gIH1cbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

把22节点往上拖动值test节点下，并放开

### What is Expected?

不允许这种情况出现

### What is actually happening?

出现22节点与test平级

### Additional comments

_(empty)_

**Comment by yfttgdzy** [comment]
![image](https://github.com/element-plus/element-plus/assets/36906155/3f9d8622-e0ca-47ad-ad72-e2dfb46b7d0c)
![image](https://github.com/element-plus/element-plus/assets/36906155/aabc5f37-6266-4734-bca3-5f26b25e535a)

**Comment by chenxch** [comment]
修改一下你的allowDrop
```
const allowDrop = (draggingNode: Node, dropNode: Node, type: AllowDropType) => {
  if (
    (draggingNode.parent.data['nodeKey'] === dropNode.data['nodeKey'] && type === 'inner') ||
    (draggingNode.parent.data['nodeKey'] === dropNode.parent.data['nodeKey'] && type !== 'inner')
  ) {
  if(draggingNode.level > dropNode.level){
    return false
  }
  console.log('drag', draggingNode, dropNode, type)
    return true;
  }
  console.log('false')
  return false;
}
```

**Comment by yfttgdzy** [comment]
你的意思是目前无法只通过我提供的代码完全阻止，还得通过level进行进一步判断是吗，那如果有其他特殊处理，也需进行level判断？

**Comment by yfttgdzy** [comment]
非常感谢，我将对其他拖动规则进行进一步处理，来保证完全阻止
