### ISSUE TITLE
[Docs] [All] 什么垃圾？就你家的网站打开慢死了

### ISSUE THREAD

**Issue by w569638598** [element-plus/element-plus#15590]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.5`
- Element Plus Version: `2.5.1`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html#%E5%85%A8%E5%B1%80%E6%96%B9%E6%B3%95)

### Steps to reproduce

自己看

### What is Expected?

瞬间打开，别耽误我上班。

### What is actually happening?

跟拉不出来一样，耽误我上班。

### Additional comments

_(empty)_

**Comment by YoungDan-hero** [comment]
https://github.com/element-plus/element-plus/assets/66891653/35322b48-1fff-4418-b3c5-48a33b29c386

**Comment by chenxch** [comment]
组件库的使用是免费的，但是服务器的运行和维护是需要成本的，我们非常感谢您一直使用我们的组件库进行工作以获得报酬，并且我们希望能够继续提供更好的服务。如果您愿意，您可以考虑赞助我们购买更好的服务器来提高访问速度，这将使我们能够更好地满足您的需求。

**Comment by baizhi958216** [comment]
https://github.com/element-plus/element-plus/assets/46777503/6fea951a-b40e-4ab7-b99c-761fcd843fc6

挺快的我觉得

**Comment by MichaelYuhe** [comment]
> 组件库的使用是免费的，但是服务器的运行和维护是需要成本的，我们非常感谢您一直使用我们的组件库进行工作以获得报酬，并且我们希望能够继续提供更好的服务。如果您愿意，您可以考虑赞助我们购买更好的服务器来提高访问速度，这将使我们能够更好地满足您的需求。

我们这可以赞助部署，比起 GitHub Pages 应该好些，如果需要可以聊聊看～

**Comment by pan93412** [comment]
你可以自己部署一个本地版的，这样就算公司断网也不会耽误你上班了：https://github.com/element-plus/element-plus/tree/dev/docs

这个是 CI，里面有 element-plus 构建 docs 的一切流程：https://github.com/element-plus/element-plus/blob/dev/.github/workflows/pr-docs-build.yml

**Comment by zzydannyer** [comment]
幽默

**Comment by sunpm** [comment]
还以为是 https://element-plus.org 😊
