### ISSUE TITLE
[Component] [radio-button, radio] radiobutton losting style using jsx

### ISSUE THREAD

**Issue by tjc0726** [element-plus/element-plus#15620]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-radio-button`
- `el-radio`

### Reproduction Link

[Link](can't use jsx in playground)

### Steps to reproduce

```vue
<template>
  <asd></asd>
</template>
  
<script lang="tsx" setup>
import { ElRadioButton } from 'element-plus'

const asd = <ElRadioButton label={1}>X</ElRadioButton>

</script>
```

### What is Expected?

radiobutton with correct style
![image](https://github.com/element-plus/element-plus/assets/49085201/5ffc446d-143a-4de8-a115-b96007828f10)

### What is actually happening?

wrong style applied
![image](https://github.com/element-plus/element-plus/assets/49085201/907e58ce-b84e-4e07-a32c-5b35b11cffb0)

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Referencing a component manually requires referencing styles at the same time
