### ISSUE TITLE
[Bug Report] The animation effect does not take effect when the navigation menu expands and closes quickly

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1562]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
windows10

### Vue version
3.0.7

### Steps to reproduce
https://element-plus.gitee.io/#/zh-CN/component/menu

The official website demo can be reproduced

### What is Expected?
The animation can be transitioned or transitioned quickly

### What is actually happening?
The animation effect does not take effect when the navigation menu expands and closes quickly

The official website demo can be reproduced

**Comment by Ryan2128** [comment]
In my test, it works well. I can not reproduct it.

![demo](https://user-images.githubusercontent.com/33176053/109966748-901fc900-7d2b-11eb-9f14-1777caf0ab29.gif)

**Comment by jahnli** [comment]
![20210304_205805](https://user-images.githubusercontent.com/20943608/109967921-ff49ed00-7d2c-11eb-9bd7-29bae42a12fb.gif)
Whether you can see that the animation fails when you are stuck and switching too fast

**Comment by Liiked** [comment]
> ![20210304_205805](https://user-images.githubusercontent.com/20943608/109967921-ff49ed00-7d2c-11eb-9bd7-29bae42a12fb.gif)
> Whether you can see that the animation fails when you are stuck and switching too fast

It seems caused by the bottleneck of your computer or browser performance. You may try to reproduce in other browser or envrionment, if it still exists, please update this issue and let us informed, thx!
