### ISSUE TITLE
[Component] [All] [Component] [table] 2.5.2 show-overflow-tooltip 插入的 dom 没有按照自定义命名空间

### ISSUE THREAD

**Issue by mansonchor** [element-plus/element-plus#15626]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `Table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciBuYW1lc3BhY2U9XCJlcFwiPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIHNob3ctb3ZlcmZsb3ctdG9vbHRpcD5cbiAgICAgICAgVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tVG9tXG4gICAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuXG48c3R5bGUgbGFuZz1cInNjc3NcIj5cbkBmb3J3YXJkICdlbGVtZW50LXBsdXMvdGhlbWUtY2hhbGsvc3JjL21peGlucy9jb25maWcuc2Nzcycgd2l0aCAoXG4gICRuYW1lc3BhY2U6ICdlcCdcbik7XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 设置全局命名空间
2. `Table-column` 开启 `show-overflow-tooltip` 属性 

### What is Expected?

Table 插入的 tooltips 应该遵循全局命名空间，否则样式会失效

### What is actually happening?

Table 插入的 tooltips 遵循全局命名空间

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/2160731/4ca82032-62d5-41aa-b810-eff7d25577a3)

**Comment by kooriookami** [comment]
@xingyixiang Could you please look at this? It may be the change of #15470

**Comment by xingyixiang** [comment]
@kooriookami Yeah, I'm looking at how to fix it.

**Comment by mansonchor** [comment]
> @kooriookami Yeah, I'm looking at how to fix it.

Looking forward to fixing it soon

**Comment by vela666** [comment]
https://github.com/element-plus/element-plus/issues/15354  这个能顺便看看吗？ 也是命名空间
