### ISSUE TITLE
[Component] [select] Filterable el-select: in version 2.5.2 it's not possible to delete filtering text - backspace isn't working

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#15625]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `Chrome 120 / Firefox 121`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC1zZWxlY3QgZmlsdGVyYWJsZS8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Enter any text inside el-select and press backspace

### What is Expected?

backspace is working as expected

### What is actually happening?

backspace is not working

### Additional comments
It was broken with https://github.com/element-plus/element-plus/commit/f8f9620b
```
 @keydown.delete.stop.prevent="deletePrevTag"
```
_(empty)_

![изображение](https://github.com/element-plus/element-plus/assets/1491688/6cb991df-ca69-4b00-b1fb-0076daee51a3)

**Comment by kooriookami** [comment]
Fixed in 2.5.3
