### ISSUE TITLE
[Component] [popover, color-picker] 在气泡组件中添加颜色选择器组件，在界面鼠标移入气泡组件点击颜色选择器，并将鼠标移动至颜色选择器。颜色选择器组件不展示，直接消失。

### ISSUE THREAD

**Issue by lianyutian** [element-plus/element-plus#15630]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.1`
- Element Plus Version: `2.5.2`
- Browser / OS: `chrome 120.0.6099.225`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuLy/oh6rlrprkuYnkuLvpophcbi8v6aKc6Imy57uE5Lu257uE5Lu255qE5pWw5o2uXG5jb25zdCBjb2xvciA9IHJlZigncmdiYSgyNTUsIDY5LCAwLCAwLjY4KScpXG5jb25zdCBwcmVkZWZpbmVDb2xvcnMgPSByZWYoW1xuICAnI2ZmNDUwMCcsXG4gICcjZmY4YzAwJyxcbiAgJyNmZmQ3MDAnLFxuICAnIzkwZWU5MCcsXG4gICcjMDBjZWQxJyxcbiAgJyMxZTkwZmYnLFxuICAnI2M3MTU4NScsXG4gICdyZ2JhKDI1NSwgNjksIDAsIDAuNjgpJyxcbiAgJ3JnYigyNTUsIDEyMCwgMCknLFxuICAnaHN2KDUxLCAxMDAsIDk4KScsXG4gICdoc3ZhKDEyMCwgNDAsIDk0LCAwLjUpJyxcbiAgJ2hzbCgxODEsIDEwMCUsIDM3JSknLFxuICAnaHNsYSgyMDksIDEwMCUsIDU2JSwgMC43MyknLFxuICAnI2M3MTU4NTc3Jyxcbl0pXG4vL+S4u+mimOminOiJsueahOiuvue9rlxuY29uc3Qgc2V0Q29sb3IgPSAoKSA9PiB7XG4gIC8v6YCa55+lanPkv67mlLnmoLnoioLngrnnmoTmoLflvI/lr7nosaHnmoTlsZ7mgKfkuI7lsZ7mgKflgLxcbiAgY29uc3QgaHRtbCA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudFxuICBodG1sLnN0eWxlLnNldFByb3BlcnR5KCctLWVsLWNvbG9yLXByaW1hcnknLCBjb2xvci52YWx1ZSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1wb3BvdmVyIHBsYWNlbWVudD1cImJvdHRvbVwiIHRpdGxlPVwi5Li76aKY6K6+572uXCIgOndpZHRoPVwiMzAwXCIgdHJpZ2dlcj1cImhvdmVyXCI+XG4gICAgPCEtLSDooajljZXlhYPntKAgLS0+XG4gICAgPGVsLWZvcm0+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5Li76aKY6aKc6ImyXCI+XG4gICAgICAgIDxlbC1jb2xvci1waWNrZXJcbiAgICAgICAgICBAY2hhbmdlPVwic2V0Q29sb3JcIlxuICAgICAgICAgIHYtbW9kZWw9XCJjb2xvclwiXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICBzaG93LWFscGhhXG4gICAgICAgICAgOnByZWRlZmluZT1cInByZWRlZmluZUNvbG9yc1wiXG4gICAgICAgIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8YnV0dG9uPnNldHRpbmc8L2J1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1.将鼠标移到setting按钮
2.点击主题颜色
3.将鼠标移动到颜色选择器

### What is Expected?

颜色选择器不消失，可以选定颜色

### What is actually happening?

颜色选择器消失

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
Popover 嵌套需要用户手动控制显示隐藏，如果你有更好的做法或者在其他组件库看到合理的解决方式，可以留言讨论。

**Comment by lianyutian** [comment]
切换Element Plus Version: 2.4版本以下，是没有问题的
![image](https://github.com/element-plus/element-plus/assets/37819573/e333a70f-bf68-4f1c-92b0-fc5582d4341e)

**Comment by lianyutian** [comment]
> Popover 嵌套需要用户手动控制显示隐藏，如果你有更好的做法或者在其他组件库看到合理的解决方式，可以留言讨论。

切换Element Plus Version: 2.3.14版本，是没有问题的
https://github.com/element-plus/element-plus/assets/37819573/e333a70f-bf68-4f1c-92b0-fc5582d4341e

**Comment by kooriookami** [comment]
https://github.com/element-plus/element-plus/assets/38392315/1e38f42c-d550-4e29-88ac-ee7d996525d3

这不是预期的结果，可以认为是个bug。

**Comment by lianyutian** [comment]
> QQ2024124-151244-HD.mp4 
> 这不是预期的结果，可以认为是个bug。

好的，谢谢解答
