### ISSUE TITLE
[Performance] [select, icon] el-select  与 el-icon 特定条件下会引起下拉框卡顿

### ISSUE THREAD

**Issue by wk-iei** [element-plus/element-plus#15635]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.4.0`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome, Edge / windows11`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiAgPlxuICAgICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwibmFtZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiMVwiIHZhbHVlPVwiMVwiPjwvZWwtb3B0aW9uPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiMlwiIHZhbHVlPVwiMlwiPjwvZWwtb3B0aW9uPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICA8ZWwtaWNvbiBzaXplPVwiMThcIj48U2V0dGluZyAvPjwvZWwtaWNvbj5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBTZXR0aW5nIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG5hbWUgPSByZWYoJzEnKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```javascript

<el-select v-model="name">
  <el-option label="1" value="1"></el-option>
  <el-option label="2" value="2"></el-option>
</el-select>
<el-icon size="18"><Setting /></el-icon>

```
如上代码，会引起下拉框卡顿，很长时间才弹出下拉选项。
测试去掉size="18"或者将Setting图标换成其他图标可以规避该情况。

### What is Expected?

无任何异常

### What is actually happening?

下拉框卡顿

### Additional comments

_(empty)_

**Comment by YoungDan-hero** [comment]
I can't reproduce this issue

https://github.com/element-plus/element-plus/assets/66891653/cf124769-bcc7-4f68-8e4a-667a0b9c1757

**Comment by xiaoxian521** [comment]
Can you provide a recurrence video? Someone has reported that this `Setting` icon will cause caton before. Here is a collection of everyone's recurrence videos and unified processing.

**Comment by wk-iei** [comment]
![screenshot](https://github.com/element-plus/element-plus/assets/153057208/fb6883f3-1480-4468-b300-1a9e65ee9da0)

Here is a screenshot. 
 Is this related to screen resolution? I reproduced at 2560*1440, but every is OK at 1920*1080
