### ISSUE TITLE
[Component] [drawer] Drawer没有获取动态zIndex

### ISSUE THREAD

**Issue by chg122345** [element-plus/element-plus#15641]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHN0eWxlPVwibWFyZ2luLWxlZnQ6IDE2cHhcIiBAY2xpY2s9XCJkcmF3ZXIgPSB0cnVlXCI+XG4gICAgb3BlblxuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJkcmF3ZXJcIiB0aXRsZT1cIkkgYW0gdGhlIHRpdGxlXCIgOndpdGgtaGVhZGVyPVwiZmFsc2VcIj5cbiAgICA8c3Bhbj5IaSB0aGVyZSE8L3NwYW4+XG4gIDwvZWwtZHJhd2VyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGRyYXdlciA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

弹开抽屉

### What is Expected?

动态获取zIndex

### What is actually happening?

动态获取zIndex

### Additional comments

_(empty)_

**Comment by chg122345** [comment]
![image](https://github.com/element-plus/element-plus/assets/37102948/7ed078d3-a910-49ea-b3f6-a82cc8dd75db)

**Comment by kooriookami** [comment]
Fixed
