### ISSUE TITLE
[Component] [select-v2] select-v2 cannot be expanded(无法展开)

### ISSUE THREAD

**Issue by jack20211101** [element-plus/element-plus#15647]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome 120.0.0.0 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdHlwZXMgPSBbXG4gIHsgdmFsdWU6IDAsIGxhYmVsOiBcIlR5cGUwXCIgfSxcbiAgeyB2YWx1ZTogMSwgbGFiZWw6IFwiVHlwZTFcIiB9LFxuICB7IHZhbHVlOiAyLCBsYWJlbDogXCJUeXBlMlwiIH1cbl07XG5jb25zdCB0eXBlID0gcmVmKDApO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0taXRlbSBwcm9wPVwidHlwZVwiPlxuICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgIDxlbC1zZWxlY3QtdjJcbiAgICAgIHYtbW9kZWw9XCJ0eXBlXCJcbiAgICAgIDpvcHRpb25zPVwidHlwZXNcIlxuICAgICAgcGxhY2Vob2xkZXI9XCLnsbvlnotcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgIC8+XG4gIDwvdGVtcGxhdGU+XG4gIDwvZWwtZm9ybS1pdGVtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

used.

### What is Expected?

expanded

### What is actually happening?

cannot be expanded

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
原因应该是id写到到input上，然后和label for属性对应上了

**Comment by kooriookami** [comment]
点击label会触发select展开，点击select也会触发select展开，切换两次就关闭了。
请手动设置FormItem的for属性为其他值，例如：
```
  <el-form-item prop="type" for="other">
    <template #label>
      <el-select-v2
        v-model="type"
        :options="types"
        placeholder="类型"
        filterable
      />
    </template>
  </el-form-item>
```

**Comment by jack20211101** [comment]
> 点击label会触发select展开，点击select也会触发select展开，切换两次就关闭了。 请手动设置FormItem的for属性为其他值，例如：
> 
> ```
>   <el-form-item prop="type" for="other">
>     <template #label>
>       <el-select-v2
>         v-model="type"
>         :options="types"
>         placeholder="类型"
>         filterable
>       />
>     </template>
>   </el-form-item>
> ```

添加之后正常
