### ISSUE TITLE
[Bug Report] There is no code hint, for example, when typing '<el-'.

### ISSUE THREAD

**Issue by YongHengFu** [element-plus/element-plus#1565]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Win10

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/yonghengfu/pen/LYbrMJy

### Steps to reproduce
The project is based on 'vite2 vue3 TypeScript', has installed 'element-plus'', and introduced in 'main.ts', but there is no code hint. For example, when typing '<el-'. But the component is displayed normally in the page after running.
I have tried in 'vscode' and 'webstrom'.

zh:
项目基于'vite2 vue3 TypeScript',已经安装了‘element-plus'’,并且在‘main.ts’中引入，但是没有代码提示。比如在输入'<el-'的时候。但是运行后在页面中组件能够正常显示。
在'vscode’和‘webstrom'中都已经尝试过。

### What is Expected?
Code hint appears

### What is actually happening?
no code hint

**Comment by tolking** [comment]
vscode + Vetur

**Comment by YongHengFu** [comment]
Ok, thanks. Is this a bug? Version 2.0 does it without using Vetur.

**Comment by tolking** [comment]
I don't think this is a element-plus bug.

> Version 2.0 does it without using Vetur.

I don't know how to work.

 webstrom is not yet supported, I will try it (Add `web-types.json` for webstrom)

**Comment by Ryan2128** [comment]
> I don't think this is a element-plus bug.
> 
> > Version 2.0 does it without using Vetur.
> 
> I don't know how to work.
> 
> webstrom is not yet supported, I will try it (Add `web-types.json` for webstrom)
