### ISSUE TITLE
[Component] [tour-step] Tour step title slot does not work

### ISSUE THREAD

**Issue by Meital-Kozhidov** [element-plus/element-plus#15655]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tour-step`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxlbC10b3VyIHYtbW9kZWw9XCJpc1RvdXJpbmdcIj5cbiAgPGVsLXRvdXItc3RlcD5cbiAgICA8dGVtcGxhdGUgI3RpdGxlPiB0aXRsZSA8L3RlbXBsYXRlPlxuICA8L2VsLXRvdXItc3RlcD5cbjwvZWwtdG91cj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuXG5jb25zdCBpc1RvdXJpbmcgPSByZWYodHJ1ZSk7XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Enter the provided Element Plus Playground link.

### What is Expected?

Content inside the title slot is excpected to appear at the tour step title. 

### What is actually happening?

Nothing. the title slot doesn't effect the tour step title.

### Additional comments

_(empty)_

**Comment by wzc520pyfm** [comment]
oh sorry, i find doc is error, the solt is `header`, not `title`
