### ISSUE TITLE
[Style] [rate] ElRate为什么选中的星星会比未选中的小？

### ISSUE THREAD

**Issue by dean5277** [element-plus/element-plus#15650]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `win11`
- Build Tool: `Vite`

### Related Component

- `el-rate`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiA8ZWwtcmF0ZSB2LW1vZGVsPVwidmFsdWVcIiAgLz5cbiAgPGJyIC8+XG4gIDxlbC1yYXRlIHYtbW9kZWw9XCJ2YWx1ZVwiIHNpemU9XCJsYXJnZVwiIC8+XG4gIDxiciAvPlxuICA8ZWwtcmF0ZSB2LW1vZGVsPVwidmFsdWVcIiAvPlxuICA8YnIgLz5cbiAgPGVsLXJhdGUgdi1tb2RlbD1cInZhbHVlXCIgc2l6ZT1cInNtYWxsXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKG51bGwpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1.可操作的rate选中

### What is Expected?

1. 希望星星一样大

### What is actually happening?

1.选中的星星比较小

### Additional comments

1.其实也不是不可以，但是看到一个矛盾点就是只读的星星选中不选中都是一样大，但是非只读的就选中的比较小

![image](https://github.com/element-plus/element-plus/assets/1802631/8865c568-c635-4073-99c1-85e74bf6303b)
![image](https://github.com/element-plus/element-plus/assets/1802631/b026e783-9b5c-4e2d-a940-524186c1ff33)

**Comment by chenxch** [comment]
设计如此哦，如果有需要的话可以自行重写选中的font-size即可。
