### ISSUE TITLE
[Component] [form-item, form] 使用表单上传图片成功后，表单校验信息还存在

### ISSUE THREAD

**Issue by yusheng13** [element-plus/element-plus#15659]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.5.0`
- Browser / OS: `chrome120.0 /windows64`
- Build Tool: `Vite`

### Related Component

- `el-form-item`
- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7IFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZm9ybUluc3RhbmNlID0gcmVmKClcbmNvbnN0IGZvcm0gPSByZWYoeyBpbWdVcmw6ICcnIH0pXG5jb25zdCBmb3JtUnVsZXMgPSB7IGltZ1VybDogeyByZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ+ivt+S4iuS8oOWbvueJhycgfSB9XG5cbmZ1bmN0aW9uIHZhbGlkYXRlKCkge1xuICBmb3JtSW5zdGFuY2UudmFsdWUudmFsaWRhdGUoKVxufVxuZnVuY3Rpb24gaGFuZGxlQXZhdGFyU3VjY2VzcyhyZXMpIHtcbiAgZm9ybS52YWx1ZS5pbWdVcmwgPSAnaHR0cHM6Ly9pbWcyLmJhaWR1LmNvbS9pdC91PTIyNDczMjM0NDIsNDA2NDc1ODI1NSZmbT0yNTMmZm10PWF1dG8mYXBwPTEzOCZmPUpQRUc/dz0yMDAmaD0yMDAnXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuZm9ybTp7e2Zvcm19fVxuICA8ZWwtZm9ybSByZWY9XCJmb3JtSW5zdGFuY2VcIiA6bW9kZWw9XCJmb3JtXCIgOnJ1bGVzPVwiZm9ybVJ1bGVzXCIgOmxhYmVsLXdpZHRoPVwiMTAwXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkxPR09cIiBwcm9wPVwiaW1nVXJsXCI+XG4gICAgICA8ZWwtdXBsb2FkIGNsYXNzPVwiYXZhdGFyLXVwbG9hZGVyXCIgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICAgICAgOnNob3ctZmlsZS1saXN0PVwiZmFsc2VcIiA6b24tc3VjY2Vzcz1cImhhbmRsZUF2YXRhclN1Y2Nlc3NcIj5cbiAgICAgICAgPGltZyB2LWlmPVwiZm9ybS5pbWdVcmxcIiA6c3JjPVwiZm9ybS5pbWdVcmxcIiBjbGFzcz1cImF2YXRhclwiIC8+XG4gICAgICAgIDxlbC1pY29uIHYtZWxzZSBjbGFzcz1cImF2YXRhci11cGxvYWRlci1pY29uXCI+XG4gICAgICAgICAgPFBsdXMgLz5cbiAgICAgICAgPC9lbC1pY29uPlxuICAgICAgPC9lbC11cGxvYWQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJ2YWxpZGF0ZVwiPumqjOivgeihqOWNlTwvYnV0dG9uPlxuICA8YnV0dG9uIEBjbGljaz1cImZvcm0uaW1nVXJsPSdodHRwczovL2ltZzIuYmFpZHUuY29tL2l0L3U9MjI0NzMyMzQ0Miw0MDY0NzU4MjU1JmZtPTI1MyZmbXQ9YXV0byZhcHA9MTM4JmY9SlBFRz93PTIwMCZoPTIwMCdcIj7miYvliqjkv67mlLlpbWdVcmw8L2J1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4uYXZhdGFyLXVwbG9hZGVyIC5hdmF0YXIge1xuICB3aWR0aDogMTc4cHg7XG4gIGhlaWdodDogMTc4cHg7XG4gIGRpc3BsYXk6IGJsb2NrO1xufVxuPC9zdHlsZT5cblxuPHN0eWxlPlxuLmF2YXRhci11cGxvYWRlciAuZWwtdXBsb2FkIHtcbiAgYm9yZGVyOiAxcHggZGFzaGVkIHZhcigtLWVsLWJvcmRlci1jb2xvcik7XG4gIGJvcmRlci1yYWRpdXM6IDZweDtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gIG92ZXJmbG93OiBoaWRkZW47XG4gIHRyYW5zaXRpb246IHZhcigtLWVsLXRyYW5zaXRpb24tZHVyYXRpb24tZmFzdCk7XG59XG5cbi5hdmF0YXItdXBsb2FkZXIgLmVsLXVwbG9hZDpob3ZlciB7XG4gIGJvcmRlci1jb2xvcjogdmFyKC0tZWwtY29sb3ItcHJpbWFyeSk7XG59XG5cbi5lbC1pY29uLmF2YXRhci11cGxvYWRlci1pY29uIHtcbiAgZm9udC1zaXplOiAyOHB4O1xuICBjb2xvcjogIzhjOTM5ZDtcbiAgd2lkdGg6IDE3OHB4O1xuICBoZWlnaHQ6IDE3OHB4O1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

在form表单里使用el-upload组件上传图片，字段假设是imgUrl，在上传之前先触发表单required校验，imgUrl必传，之后上传图片成功后给imgUrl赋值（或者手动给imgUrl赋值），发现校验信息没有消失；

### What is Expected?

给imgUrl赋值后表单验证信息自动消失

### What is actually happening?

验证信息没有消失

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
外部操作进行的变更需要自行手动再次进行校验。

**Comment by yusheng13** [comment]
> 外部操作进行的变更需要自行手动再次进行校验。

我新加了个input输入框字段name，先触发表单校验，然后像修改imgUrl一样手动修改name，为什么表单校验信息会清除了
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7IFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZm9ybUluc3RhbmNlID0gcmVmKClcbmNvbnN0IGZvcm0gPSByZWYoeyBpbWdVcmw6ICcnLG5hbWU6JycgfSlcbmNvbnN0IGZvcm1SdWxlcyA9IHsgXG4gIG5hbWU6IHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICfor7fovpPlhaXlp5PlkI0nIH0sXG4gIGltZ1VybDogeyByZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ+ivt+S4iuS8oOWbvueJhycgfVxuIH1cblxuZnVuY3Rpb24gdmFsaWRhdGUoKSB7XG4gIGZvcm1JbnN0YW5jZS52YWx1ZS52YWxpZGF0ZSgpXG59XG5mdW5jdGlvbiBoYW5kbGVBdmF0YXJTdWNjZXNzKHJlcykge1xuICBmb3JtLnZhbHVlLmltZ1VybCA9ICdodHRwczovL2ltZzIuYmFpZHUuY29tL2l0L3U9MjI0NzMyMzQ0Miw0MDY0NzU4MjU1JmZtPTI1MyZmbXQ9YXV0byZhcHA9MTM4JmY9SlBFRz93PTIwMCZoPTIwMCdcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5mb3JtOnt7Zm9ybX19XG4gIDxlbC1mb3JtIHJlZj1cImZvcm1JbnN0YW5jZVwiIDptb2RlbD1cImZvcm1cIiA6cnVsZXM9XCJmb3JtUnVsZXNcIiA6bGFiZWwtd2lkdGg9XCIxMDBcIj5cbiAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWnk+WQjVwiIHByb3A9XCJuYW1lXCI+XG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm5hbWVcIiAvPlxuICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiTE9HT1wiIHByb3A9XCJpbWdVcmxcIj5cbiAgICAgIDxlbC11cGxvYWQgY2xhc3M9XCJhdmF0YXItdXBsb2FkZXJcIiBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgICAgICA6c2hvdy1maWxlLWxpc3Q9XCJmYWxzZVwiIDpvbi1zdWNjZXNzPVwiaGFuZGxlQXZhdGFyU3VjY2Vzc1wiPlxuICAgICAgICA8aW1nIHYtaWY9XCJmb3JtLmltZ1VybFwiIDpzcmM9XCJmb3JtLmltZ1VybFwiIGNsYXNzPVwiYXZhdGFyXCIgLz5cbiAgICAgICAgPGVsLWljb24gdi1lbHNlIGNsYXNzPVwiYXZhdGFyLXVwbG9hZGVyLWljb25cIj5cbiAgICAgICAgICA8UGx1cyAvPlxuICAgICAgICA8L2VsLWljb24+XG4gICAgICA8L2VsLXVwbG9hZD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuICA8YnV0dG9uIEBjbGljaz1cInZhbGlkYXRlXCI+6aqM6K+B6KGo5Y2VPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwiZm9ybS5uYW1lPSd4eHh4J1wiPuaJi+WKqOS/ruaUuW5hbWU8L2J1dHRvbj5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJmb3JtLmltZ1VybD0naHR0cHM6Ly9pbWcyLmJhaWR1LmNvbS9pdC91PTIyNDczMjM0NDIsNDA2NDc1ODI1NSZmbT0yNTMmZm10PWF1dG8mYXBwPTEzOCZmPUpQRUc/dz0yMDAmaD0yMDAnXCI+5omL5Yqo5L+u5pS5aW1nVXJsPC9idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmF2YXRhci11cGxvYWRlciAuYXZhdGFyIHtcbiAgd2lkdGg6IDE3OHB4O1xuICBoZWlnaHQ6IDE3OHB4O1xuICBkaXNwbGF5OiBibG9jaztcbn1cbjwvc3R5bGU+XG5cbjxzdHlsZT5cbi5hdmF0YXItdXBsb2FkZXIgLmVsLXVwbG9hZCB7XG4gIGJvcmRlcjogMXB4IGRhc2hlZCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBib3JkZXItcmFkaXVzOiA2cHg7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xuICBvdmVyZmxvdzogaGlkZGVuO1xuICB0cmFuc2l0aW9uOiB2YXIoLS1lbC10cmFuc2l0aW9uLWR1cmF0aW9uLWZhc3QpO1xufVxuXG4uYXZhdGFyLXVwbG9hZGVyIC5lbC11cGxvYWQ6aG92ZXIge1xuICBib3JkZXItY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xufVxuXG4uZWwtaWNvbi5hdmF0YXItdXBsb2FkZXItaWNvbiB7XG4gIGZvbnQtc2l6ZTogMjhweDtcbiAgY29sb3I6ICM4YzkzOWQ7XG4gIHdpZHRoOiAxNzhweDtcbiAgaGVpZ2h0OiAxNzhweDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by chenxch** [comment]
因为input有validate-event属性

**Comment by yusheng13** [comment]
> 因为input有validate-event属性

为啥不给upload也加这个属性让表单也能自动验证，每次都要手动给upload验证，对于像我一样的懒人觉得很难受

**Comment by chenxch** [comment]
目前只针对常见表单类型中使用的一些组件添加该属性，无法涵盖该所有的组件。welcome pr。

**Comment by yusheng13** [comment]
> 目前只针对常见表单类型中使用的一些组件添加该属性，无法涵盖该所有的组件。welcome pr。

ok~我看element ui对于这个问题一直没有做优化，希望在element plus这里未来能优化一下
