### ISSUE TITLE
[i18n] [All] No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

### ISSUE THREAD

**Issue by TryChai** [element-plus/element-plus#15651]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `chorm`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

升级版本 从2.3.1 升级到2.5.3 使用了 vue-i18n

### What is Expected?

平缓过度

### What is actually happening?

一堆报错

### Additional comments

No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package
![image](https://github.com/element-plus/element-plus/assets/30064871/7db9c116-ef2f-4642-a4e8-1812a998db4f)
![image](https://github.com/element-plus/element-plus/assets/30064871/fd4570c6-4e85-44d9-a597-7d99b163363f)
![image](https://github.com/element-plus/element-plus/assets/30064871/31b2514f-4377-4867-a12b-c13ffbba59c8)
![image](https://github.com/element-plus/element-plus/assets/30064871/6bbf94b0-77c8-4c31-b731-ed664429e413)
![image](https://github.com/element-plus/element-plus/assets/30064871/30f43502-36be-4969-9a68-05b51a7316f4)
没升级之前是好的

**Comment by TryChai** [comment]
@Fuphoenixes 求大佬帮忙看看 非常紧急

**Comment by TryChai** [comment]
复现不出来 妈的不升级了 烦死了

**Comment by kooriookami** [comment]
我刚刚用最新的代码试了，App.vue这么写的没问题呀
```App.vue
<template>
  <el-config-provider :locale="locale">
    <el-button>test</el-button>
  </el-config-provider>
</template>

<script setup>
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'
import { ref } from "vue";

const locale = ref(zhCn)
</script>
```

**Comment by TryChai** [comment]
我大概是疯了 为了一个预览的功能 引入了另一个框架

**Comment by izhaorui** [comment]
import zhCn from 'element-plus/dist/locale/zh-cn' // 中文语言
import en from 'element-plus/dist/locale/en' // 英文语言
import thTw from 'element-plus/dist/locale/zh-tw' //繁体
