### ISSUE TITLE
[Component] [select] 【Select】cannot be clicked to expand the dropdown menu；【选择】无法点击展开下拉菜单；

### ISSUE THREAD

**Issue by tetezi** [element-plus/element-plus#15662]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucz0gcmVmKFt7bGFiZWw6JzEnLHZhbHVlOjF9LHtsYWJlbDonMicsdmFsdWU6Mn0se2xhYmVsOiczJyx2YWx1ZTozfV0pXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgICBjbGVhcmFibGUgICAgZmlsdGVyYWJsZSAgcmVtb3RlIDpyZW1vdGUtbWV0aG9kPVwiKCk9Pnt9XCIgID5cbiAgICAgICA8ZWwtb3B0aW9uICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIDprZXk9XCJpdGVtLnZhbHVlXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsdWVcIj5cbiAgICAgICA8L2VsLW9wdGlvbj5cbiAgIDwvZWwtc2VsZWN0PlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

设置remote、remote-method，并点击下拉框

### What is Expected?

Expand dropdown；展开下拉框

### What is actually happening?

Cannot  Expand dropdown；没有展开下拉框

### Additional comments

But when I switch to 2.5.1, I can successfully expand the dropdown menu
但当我切换至2.5.1即可成功展开下拉框

**Comment by purepear** [comment]
I noticed this bug too. 
Using `automatic-dropdown` as a workaround helped but that's not what that prop is supposed to do.

**Comment by nInDream** [comment]
我也遇到了

**Comment by wbsllm** [comment]
我也遇到了

**Comment by fu827707013** [comment]
我也遇到了，详细测试了下，应该是2.5.0重构后造成的问题
2.5.0鼠标样式变化成光标而不是手势，不过这时候还可以绑定@click赋值数据源list，
一直到2.5.2，才出的问题
希望能跟进

**Comment by jialanmo** [comment]
看了下源码，应该是v2.5.2增加了下面这2行的造成的
packages/components/select/src/useSelect.ts
```
  const toggleMenu = () => {
    if (selectDisabled.value) return
+    if (props.filterable && props.remote && isFunction(props.remoteMethod))
+      return
    if (states.menuVisibleOnFocus) {
      // controlled by automaticDropdown
      states.menuVisibleOnFocus = false
    } else {
      expanded.value = !expanded.value
    }
  }
```

**Comment by purepear** [comment]
This should be fixed in the next version
https://github.com/element-plus/element-plus/issues/15679

**Comment by liangshan09321** [comment]
automatic-dropdown

**Comment by liangshan09321** [comment]
automatic-dropdown

**Comment by XLY-lois** [comment]
我也遇到了 暂时先把版本降低

**Comment by kooriookami** [comment]
Fixed in new version.
