### ISSUE TITLE
[Component] [select] el-select 使用value-key 赋值回显没有回显选中颜色

### ISSUE THREAD

**Issue by DejaVuuuuuuu** [element-plus/element-plus#15664]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.5.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICB2YWx1ZS1rZXk9XCJpZFwiXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLmlkXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW1cIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICA8cD5cbiAgICAgIHNlbGVjdGVkIG9wdGlvbidzIGRlc2NyaXB0aW9uOlxuICAgICAge3sgdmFsdWUgPyB2YWx1ZS5kZXNjIDogJ25vIHNlbGVjdCcgfX1cbiAgICA8L3A+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxudHlwZSBPcHRpb24gPSB7XG4gIGlkOiBudW1iZXJcbiAgbGFiZWw6IHN0cmluZ1xuICBkZXNjOiBzdHJpbmdcbn1cbmNvbnN0IHZhbHVlID0gcmVmPE9wdGlvbj4oe1xuaWQ6IDMsIGxhYmVsOiAnT3B0aW9uIEEnLCBkZXNjOiAnT3B0aW9uIEEgLSAyMzA1MDYnXG59KVxuY29uc3Qgb3B0aW9ucyA9IHJlZihbXG4gIHsgaWQ6IDEsIGxhYmVsOiAnT3B0aW9uIEEnLCBkZXNjOiAnT3B0aW9uIEEgLSAyMzA1MDYnIH0sXG4gIHsgaWQ6IDIsIGxhYmVsOiAnT3B0aW9uIEInLCBkZXNjOiAnT3B0aW9uIEIgLSAyMzA1MDYnIH0sXG4gIHsgaWQ6IDMsIGxhYmVsOiAnT3B0aW9uIEMnLCBkZXNjOiAnT3B0aW9uIEMgLSAyMzA1MDYnIH0sXG4gIHsgaWQ6IDQsIGxhYmVsOiAnT3B0aW9uIEEnLCBkZXNjOiAnT3B0aW9uIEEgLSAyMzA1MDcnIH0sXG5dKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

打开链接查看回显状态

### What is Expected?

点开下拉之后回显数据加粗和默认选中样式

### What is actually happening?

没有选中样式

### Additional comments

_(empty)_

**Comment by DejaVuuuuuuu** [comment]
2.4.x的版本我对比了是有选中样式

**Comment by purepear** [comment]
In your example, the selected option only matches the `id` but not the `label` and `desc`.
This change should make it work:
```ts
// From:
const value = ref<Option>({ id: 3, label: 'Option A', desc: 'Option A - 230506' })
// To:
const value = ref<Option>({ id: 3, label: 'Option C', desc: 'Option C - 230506' })
```

However, looks like 2.4.x selects the option only by `id` (even if `label` and `desc` don't match) 🤔

**Comment by DejaVuuuuuuu** [comment]
你这样调整是可以，但是如果要求其他的属性全部都能够和之前对应上那么这个value-key就失去意义了
