### ISSUE TITLE
[Component] [dialog, drawer] el-dialog 和 el-drawer 同时使用时 zindex 错误

### ISSUE THREAD

**Issue by roojay520** [element-plus/element-plus#15660]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome/120.0.0.0, Intel Mac OS X 10_15_7`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`
- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm91dGVyVmlzaWJsZSA9IHRydWVcIj5cbiAgICBvcGVuIHRoZSBvdXRlciBEaWFsb2dcbiAgPC9lbC1idXR0b24+XG5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwib3V0ZXJWaXNpYmxlXCIgdGl0bGU9XCJPdXRlciBEaWFsb2dcIiBhcHBlbmQtdG8tYm9keT5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPGRpdiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvdXRlclZpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZHJhd2VyVmlzaWJsZSA9IHRydWVcIj5cbiAgICAgICAgICBvcGVuIGRyYXdlclxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZGlhbG9nPlxuICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJkcmF3ZXJWaXNpYmxlXCIgdGl0bGU9XCJJIGFtIHRoZSB0aXRsZVwiIDp3aXRoLWhlYWRlcj1cImZhbHNlXCIgYXBwZW5kLXRvLWJvZHk+XG4gICAgPHNwYW4+SGkgdGhlcmUhPC9zcGFuPlxuICA8L2VsLWRyYXdlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG91dGVyVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGRyYXdlclZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 打开 dialog
2. 点击 dialog 里面的 open drawer

### What is Expected?

drawer 的层级在 dialog 之上

### What is actually happening?

dialog 的层级在 drawer 之上

### Additional comments

在 2.5.1 版本时是能够按照先后顺序正确渲染层级的：
<img width="1604" alt="image" src="https://github.com/element-plus/element-plus/assets/11495164/4a79de60-40ff-4480-899a-b9621c08ea05">

在 2.5.2 版本的时候就出现层级错误了:

<img width="1603" alt="image" src="https://github.com/element-plus/element-plus/assets/11495164/ce918fee-6e40-4001-b0bb-9932df05f24d">

应该是和这个提交有关：https://github.com/element-plus/element-plus/commit/e15fca80d2df15677b121e86db3c3fc888378ccd
其中漏掉了 `zIndex` props

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/issues/15641 已修复

**Comment by roojay520** [comment]
神速 👍

**Comment by Taosome** [comment]
并没有解决呢  我升级了2.5.3 依然存在这个问题  el-drawer 的z-index始终都是2000

**Comment by roojay520** [comment]
> 并没有解决呢 我升级了2.5.3 依然存在这个问题 el-drawer 的z-index始终都是2000 我在nuxt中使用的

2.5.3 版本只解决了 el-select 启用过滤时输入值没法删除的问题， 他的这个 pr 还没有合并。

目前有个临时解决办法。把 el-drawer 写在 el-dialog 的 slot 里面，去掉 append-to-body 属性应该能暂时解决这个问题。
