### ISSUE TITLE
[Component] [select, select-v2] regression: native input value is not synced

### ISSUE THREAD

**Issue by purepear** [element-plus/element-plus#15665]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome/MacOS`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCBpZD1cInNlbGVjdC1pZFwiIHYtbW9kZWw9XCJ2YWx1ZVwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG5cbiAgPHByZT57eyBkZWJ1ZyB9fTwvcHJlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgd2F0Y2gsIG9uTW91bnRlZCwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCdPcHRpb24gMScpXG5jb25zdCBkZWJ1ZyA9IHJlZih7fSlcblxub25Nb3VudGVkKCgpID0+IHtcbiAgd2F0Y2godmFsdWUsIGFzeW5jICgpID0+IHtcbiAgICBhd2FpdCBuZXh0VGljaygpXG4gICAgZGVidWcudmFsdWUgPSB7XG4gICAgICAndi1tb2RlbCc6IHZhbHVlLnZhbHVlLCBcbiAgICAgICdpbnB1dC52YWx1ZSc6IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWxlY3QtaWQnKT8udmFsdWVcbiAgICB9XG4gIH0sIHtcbiAgICBpbW1lZGlhdGU6IHRydWVcbiAgfSlcbn0pXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Open the repro link. See that the initial v-model value is `"Option 1"` but the native input value is `""`. Even after selecting `"Option 2"`, the native input value is still `""`.

### What is Expected?

The native input value should be synced with the v-model value

### What is actually happening?

The native input value is always empty string

### Additional comments

This was not an issue in versions < 2.5.0

Having the native input synced is particularly helpful for testing (with [Testing Library](https://testing-library.com/), [Playwright](https://playwright.dev/), etc):
```js
expect(getByLabelText('Category')).toHaveValue('Option 1')
```

**Comment by kooriookami** [comment]
Hello, the native input is designed for filtering the options. And the native input couldn't display the array too.

**Comment by purepear** [comment]
Fair enough :) I guess it was a bonus that it worked before. I'll close the issue. Thanks @kooriookami!
