### ISSUE TITLE
[Component] [drawer, input] 抽屉组件与外部的input同时存在时，外部input无法通过点击事件聚集

### ISSUE THREAD

**Issue by BruceCham** [element-plus/element-plus#15661]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHN0eWxlPVwibWFyZ2luLWxlZnQ6IDE2cHhcIiBAY2xpY2s9XCJkcmF3ZXIgPSB0cnVlXCI+b3BlbjwvZWwtYnV0dG9uPlxuICA8ZWwtaW5wdXQgc3R5bGU9XCJ3aWR0aDogNDAwcHg7IG1hcmdpbi1sZWZ0OiA1MDBweFwiIC8+XG4gIDxlbC1kcmF3ZXJcbiAgICB2LW1vZGVsPVwiZHJhd2VyXCJcbiAgICB0aXRsZT1cIkkgYW0gdGhlIHRpdGxlXCJcbiAgICA6bW9kYWw9XCJ0cnVlXCJcbiAgICA6d2l0aC1oZWFkZXI9XCJ0cnVlXCJcbiAgICBkaXJlY3Rpb249XCJsdHJcIlxuICAgIDpjbG9zZS1vbi1wcmVzcy1lc2NhcGU9XCJmYWxzZVwiXG4gICAgOm1vZGFsLWFwcGVuZC10by1ib2R5PVwiZmFsc2VcIlxuICA+XG4gICAgPHNwYW4+SGkgdGhlcmUhPC9zcGFuPlxuICA8L2VsLWRyYXdlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRyYXdlciA9IHJlZihmYWxzZSlcblxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZWwtb3ZlcmxheSB7XG4gIHdpZHRoOiAzMHZ3ICFpbXBvcnRhbnQ7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgYmFja2dyb3VuZDogdHJhbnNwYXJlbnQ7XG59XG4uZWwtZHJhd2VyIHtcbiAgd2lkdGg6IDMwdncgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、先点击 【open】，将左侧的抽屉弹窗打开
2、点击input填写信息

### What is Expected?

可以正常填写信息

### What is actually happening?

输入框无法聚集，无法填写内容

### Additional comments

_(empty)_

**Comment by BruceCham** [comment]
@chenxch

**Comment by hona-app** [comment]
我这边也是遇到了相同问题，反馈数量 +1
