### ISSUE TITLE
[Component] [select, select-v2] 开启远程搜索时候，不加载默认Options的数据

### ISSUE THREAD

**Issue by xxdisgod415** [element-plus/element-plus#15679]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-select-v2`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select.html#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2)

### Steps to reproduce

官方文档示例即可实现

### What is Expected?

正常加载默认options

### What is actually happening?

不正常

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
远程搜索是需要输入后才查询，输入条件为空展开时不查询。

**Comment by xxdisgod415** [comment]
> 远程搜索是需要输入后才查询，输入条件为空展开时不查询。

之前的版本，在不去查询的时候，下拉列表是会展示传入的option的。查询的时候才会像你说这样。
