### ISSUE TITLE
[Component] [select] ElSelect throws an error when running in Vue versions less than 3.2.34-beta.1.

### ISSUE THREAD

**Issue by 1453671194** [element-plus/element-plus#15678]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.5.3`
- Browser / OS: `Microsoft Edge 119.0.2151.72`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCBzZVZhbHVlID0gcmVmKCcnKTtcbmNvbnN0IG9wdGlvbnMgPSByZWYoW1xuICB7IGxhYmVsOiAnbGFiZWwxJywgdmFsdWU6ICd2YWx1ZTEnIH0sXG4gIHsgbGFiZWw6ICdsYWJlbDInLCB2YWx1ZTogJ3ZhbHVlMicgfSxcbiAgeyBsYWJlbDogJ2xhYmVsMycsIHZhbHVlOiAndmFsdWUzJyB9LFxuXSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJzZVZhbHVlXCI+XG4gICAgPGVsLW9wdGlvbiBcbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIHYtYmluZD1cIml0ZW1cIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuXG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. Switch the Element-Plus version to 2.5.3.
2. Switch the Vue version to to any version less than 3.2.34-beta.1.
3. Refresh the preview iframe.

### What is Expected?

It works normally. 

### What is actually happening?

It throws an error: 'we.updateOption is not a functoin.'

### Additional comments

In my development environment, the error is 'option.updateOption is not a function'.

![image](https://github.com/element-plus/element-plus/assets/84755178/ee67e480-63cc-490f-b16f-1fba8a07d210)

**Comment by liuwanwei8** [comment]
I had the same problem

**Comment by Chen0217** [comment]
u can try options data init when mounted

**Comment by Yanjinghao** [comment]
i havenot solved the problem yet

**Comment by Yanjinghao** [comment]
i fixed by setting attribute 'lazy' as true

**Comment by Yanjinghao** [comment]
i fixed by setting attribute 'lazy' as true when using el-tree-select component

**Comment by JackWangz** [comment]
I also had this issue. Any updates for this problem?

**Comment by 1453671194** [comment]
I eventually upgraded the Vue version to 3.2.34, ensuring that other dependencies in the project continued to function properly. This allowed me to temporarily bypass the issue.

**Comment by P-J27** [comment]
I also had this issue. Any updates for this problem?

**Comment by better-pz** [comment]
I had the same problem

**Comment by baiyuze** [comment]
为什么不对低版本的vue组件做支持？

Why not support lower versions of Vue components?

**Comment by baiyuze** [comment]
目前vue组件版本为3.2.31仍然会报这个问题

Currently, the Vue component version is 3.2.31 and still reports this issue

**Comment by baiyuze** [comment]
![image](https://github.com/element-plus/element-plus/assets/27543832/83be8ab9-b02d-45bd-9bde-e273e5d2ca9e)

**Comment by jannicaTan** [comment]
请问这里修复后需要重新install嘛 如果是用cdn引入的有什么办法修复嘛 element-plus版本2.2.28
