### ISSUE TITLE
[Component]  [drawer, select,selectTree]抽屉组件与外部的select/TreeSelect组件同时存在时，无法打开select/treeselect的下拉窗口

### ISSUE THREAD

**Issue by Even93** [element-plus/element-plus#15676]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome/120.0.6099.227 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-select`
- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tIFwidnVlXCI7XG5jb25zdCBkcmF3ZXIgPSByZWYodHJ1ZSk7XG5jb25zdCB2YWx1ZSA9IHJlZigpO1xuLypcbmNvbnN0IGRhdGEgPSBbXG4gICAge1xuICAgICAgICB2YWx1ZTogXCIxXCIsXG4gICAgICAgIGxhYmVsOiBcIkxldmVsIG9uZSAxXCIsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgdmFsdWU6IFwiMS0xXCIsXG4gICAgICAgICAgICAgICAgbGFiZWw6IFwiTGV2ZWwgdHdvIDEtMVwiLFxuICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiBcIjEtMS0xXCIsXG4gICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogXCJMZXZlbCB0aHJlZSAxLTEtMVwiLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgIF0sXG4gICAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgIH0sXG5dO1xuKi9cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPCEtLSA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgOmRhdGE9XCJkYXRhXCIgOnJlbmRlci1hZnRlci1leHBhbmQ9XCJmYWxzZVwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCIgY2xhc3M9XCJtYjIwcHhcIiA+PC9lbC10cmVlLXNlbGVjdD4gLS0+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHNpemU9XCJsYXJnZVwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJvcHRpb24xXCIgdmFsdWU9XCJvcHRpb24xXCIgPjwvZWwtb3B0aW9uPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwib3B0aW9uMlwiIHZhbHVlPVwib3B0aW9uMlwiID48L2VsLW9wdGlvbj5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImRyYXdlciA9IHRydWVcIj5vcGVuPC9lbC1idXR0b24+XG4gICAgPGVsLW1haW4+XG4gICAgICAgIDxlbC1kcmF3ZXIgdi1tb2RlbD1cImRyYXdlclwiIHRpdGxlPVwiSSBhbSB0aGUgdGl0bGVcIiA6d2l0aC1oZWFkZXI9XCJ0cnVlXCIgZGlyZWN0aW9uPVwicnRsXCIgOmNsb3NlLW9uLXByZXNzLWVzY2FwZT1cImZhbHNlXCIgOm1vZGFsLWFwcGVuZC10by1ib2R5PVwiZmFsc2VcIj5cbiAgICAgICAgICAgIDxzcGFuPkhpLCB0aGVyZSE8L3NwYW4+XG4gICAgICAgIDwvZWwtZHJhd2VyPlxuICAgIDwvZWwtbWFpbj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5lbC1tYWluIHtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgaGVpZ2h0OiAzMDBweDtcbiAgICBtYXJnaW4tdG9wOiA2MHB4O1xuICAgIGJvcmRlcjogMXB4IHNvbGlkICMwMDA7XG59XG5cbi5lbC1vdmVybGF5IHtcbiAgICBwb3NpdGlvbjogYWJzb2x1dGUgIWltcG9ydGFudDtcbiAgICBoZWlnaHQ6IDMwMHB4O1xufVxuXG4uZWwtZHJhd2VyIHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiBncmVlbjtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、打开抽屉drawer
2、点击select/selectTree组件
3、无法打开下拉窗(需要点击一下select/selectTree组件外部区域，则恢复正常)

### What is Expected?

可以直接打开select/selectTree组件的下拉窗

### What is actually happening?

无法直接打开select/selectTree组件的下拉窗

### Additional comments

抽屉存在时，首次需要点击select/selectTree外部，再次点击select/selectTree可打开下拉窗口

**Comment by yunjunting** [comment]
@

**Comment by yunjunting** [comment]
@chenxch

**Comment by nova1751** [comment]
Related to #7915.It seems that the element-plus team want users to stay focused in the draw layer.So they write some logic parts to do this.But it will cause some wierd effects when the draw layer doesn't cover the whole page.I can fix this by disabling the re-focusing logic part but it will be a break change.
