### ISSUE TITLE
gulp 打包丢失 svg 中的 r 属性

### ISSUE THREAD

**Issue by HeroMeiKong** [element-plus/element-plus#15686]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdndWxwIOaJk+WMheS4ouWksSBzdmcg5Lit55qEIHIg5bGe5oCn5YC877yM5rKh5rOV5o+Q5L6b5aSN546w6ZO+5o6l77yM5Y+v5pys5Zyw6L+Q6KGM55yL55yL57uT5p6cJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8YSBocmVmPVwiaHR0cHM6Ly93d3cuYWxpcGFuLmNvbS9zL3pVTVRLdG1CcnJwXCI+6K+354K55Ye76L+Z6YeM5p+l55yLPC9hPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 在 theme-chalk 的样式中添加
```@keyframes spinners-react-round {
  27%, 73% {
    r: 2;
    stroke-width: 6;
  }
}
```
2. 打包样式

### What is Expected?

```
@keyframes spinners-react-round {
  27%, 73% {
    r: 2;
    stroke-width: 6;
  }
}
```

### What is actually happening?

```
@keyframes spinners-react-round {
  27%, 73% {
    stroke-width: 6;
  }
}
```

### Additional comments

gulp 打包丢失 svg 中的 r 属性值，没法提供复现链接，可本地运行看看结果

**Comment by AprilTong** [comment]
![image](https://github.com/element-plus/element-plus/assets/24354441/33505990-27ce-4fed-b76c-e0a53a31f599)
同一个版本的element-plus，不知道是不是一个错误，本地启动正常，构建之后报错，页面打开空白😭

**Comment by zhixiaotong** [comment]
本地试了一下，定位到`gulp-clean-css`压缩`css`移除了部分属性

**Comment by zhixiaotong** [comment]
`r`和`path`这些不被识别成`css`属性的默认会被`ignore`，如图
![image](https://github.com/element-plus/element-plus/assets/34681550/73742e09-a4f4-4779-8850-4353c530151d)

https://github.com/clean-css/clean-css?tab=readme-ov-file#what-errors-and-warnings-are

**Comment by zhixiaotong** [comment]
经过测试发现，`gulp-clean-css@4.3.0` 依赖的`clean-css@4.2.3`是有问题的，目前用`clean-css@latest(v5.3.3)` 测试没有这个问题了，前者版本会将不认识的属性作为警告移除。但`gulp-clean-css`已经很久没更新了。@chenxch @btea 如果觉得没问题，我将移除`gulp-clean-css`直接使用`clean-css`做`clean`处理。
