### ISSUE TITLE
[Component] [image-viewer] vue3.4.x + elemenet-plus 2.4.x 打开图片预览 直接卡死

### ISSUE THREAD

**Issue by xl495** [element-plus/element-plus#15682]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.4.4`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-image-viewer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8taW1hZ2VfX3ByZXZpZXdcIj5cbiAgICA8ZWwtaW1hZ2VcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgICAgIDpzcmM9XCJ1cmxcIlxuICAgICAgOnpvb20tcmF0ZT1cIjEuMlwiXG4gICAgICA6bWF4LXNjYWxlPVwiN1wiXG4gICAgICA6bWluLXNjYWxlPVwiMC4yXCJcbiAgICAgIDpwcmV2aWV3LXNyYy1saXN0PVwic3JjTGlzdFwiXG4gICAgICA6aW5pdGlhbC1pbmRleD1cIjRcIlxuICAgICAgZml0PVwiY292ZXJcIlxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHVybCA9XG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZydcbmNvbnN0IHNyY0xpc3QgPSBbXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMS8zNC8xOWFhOThiMWZjYjI3ODFjNGZiYTMzZDg1MDU0OWpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMC82Zi9lMzVmZjM3NTgxMmU2YjAwMjBiNmI0ZThmOTU4M2pwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vOS9iYi9lMjc4NThlOTczZjVkN2QzOTA0ODM1ZjQ2YWJiZGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZC9lNi9jNGQ5M2EzODA1YjNjZTNmMzIzZjc5NzRlNmY3OGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy8yOC9iYmY4OTNmNzkyZjAzYTU0NDA4YjNiN2E3ZWJmMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMi8xMS82NTM1YmNmYjI2ZTRjNzliNDhkZGRlNDRmNGI2ZmpwZWcuanBlZycsXG5dXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCB7XG4gIGZvbnQtc2l6ZTogMzBweDtcbn1cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCAuZWwtaWNvbiB7XG4gIGZvbnQtc2l6ZTogMzBweDtcbn1cbi5kZW1vLWltYWdlX19lcnJvciAuZWwtaW1hZ2Uge1xuICB3aWR0aDogMTAwJTtcbiAgaGVpZ2h0OiAyMDBweDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

直接打开网址

### What is Expected?

打开正常

### What is actually happening?

点击打开预览报错.
Uncaught (in promise) Maximum recursive updates exceeded in component <BaseTransition>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

### Additional comments

_(empty)_

**Comment by xxdisgod415** [comment]
除了2.5.3以外的所有版本都会出现你说这个问题

**Comment by xl495** [comment]
> 除了2.5.3以外的所有版本都会出现你说这个问题

你是怎么解决的? 还是说先不要升级3.4.x?

**Comment by xxdisgod415** [comment]
> > 除了2.5.3以外的所有版本都会出现你说这个问题
> 
> 你是怎么解决的? 还是说先不要升级3.4.x?

解决不了哦，不知道官方这次更新的是个什么东东

**Comment by xl495** [comment]
> > > 除了2.5.3以外的所有版本都会出现你说这个问题
> > 
> > 
> > 你是怎么解决的? 还是说先不要升级3.4.x?
> 
> 解决不了哦，不知道官方这次更新的是个什么东东。这个跟Vite没有关系吧，单纯就是 ElementPlus的问题

感觉这要被迫升级了 本来想着重构了 select 的组件 想等等稳定了先的

**Comment by gaojiangtao-git** [comment]
你可以用第三方预览插件暂时解决这个问题

**Comment by kooriookami** [comment]
这个是Vue3.4更新后的问题，你可以先使用Vue3.3的版本

**Comment by xl495** [comment]
> 这个是Vue3.4更新后的问题，你可以先使用Vue3.3的版本

3.3.14 貌似没问题 切到 3.3.15 就会有这个问题 看来只能先把版本锁着了 看看3.3.16 会不会还存在这个问题

**Comment by Fuphoenixes** [comment]
fixed in https://github.com/element-plus/element-plus/pull/15483
