### ISSUE TITLE
[Component] [popconfirm] Popconfirm 气泡确认框-点击页面其他地方自动关闭不触发关闭事件

### ISSUE THREAD

**Issue by HU914** [element-plus/element-plus#15702]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.3.14`
- Browser / OS: ` Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popconfirm`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uICwgRWxQb3Bjb25maXJtfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cblxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5mdW5jdGlvbiBjYW5jZWwgKCkge1xuY29uc29sZS5sb2coJ+S9oOeCueWHu+S6huWFs+mXreaMiemSricpfVxuZnVuY3Rpb24gY29uZmlybSAoKSB7XG5jb25zb2xlLmxvZygn5L2g54K55Ye75LqG56Gu6K6k5oyJ6ZKuJyl9XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG5cbiAgICAgIDxlbC1wb3Bjb25maXJtXG4gICAgICAgICAgICAgICAgICAgIHdpZHRoPVwiMjIwXCJcbiAgICAgICAgICAgICAgICAgICAgaWNvbi1jb2xvcj1cIiM2MjZBRUZcIlxuICAgICAgICAgICAgICAgICAgICBAY2FuY2VsPVwiY2FuY2VsXCJcbiAgICAgICAgICAgICAgICAgICAgQGNvbmZpcm09XCJjb25maXJtXCJcbiAgICAgICAgICAgICAgICAgICAgdGl0bGU9XCJBcmUgeW91IHN1cmUgdG8gZGVsZXRlIHRoaXM/XCJcbiAgICAgICAgICAgICAgICA+XG4gICAgICAgICAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgICAgICAgIDxzcGFuPuawlOazoeivoumXrjwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8L2VsLXBvcGNvbmZpcm0+XG4gICAgICA8cD5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgdnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点击打开气泡，然后在屏幕任一位置点击，气泡关闭

### What is Expected?

增加el-dialog属性
                    :close-on-click-modal="false"，可控制是否点击取消

### What is actually happening?

没有相关属性配置

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
对于Popconfirm来说，不选择和选择否这是两个意思哦。
可以考虑使用popover可控式模式。

**Comment by HU914** [comment]
这样对于整体使用，不是特别友好，个人建议;
1、要么新增el-dialog属性:close-on-click-modal，可控制是否点击屏幕触发取消或者隐藏。
2、要么对于点击隐藏触发cancel事件
3、依据源码，popconfirm基于el-tooltip二次封装，本身视为可操作组件（气泡确认框），而非提示组件。

**Comment by Fuphoenixes** [comment]
是的，popconfirm是用popover实现的，所以可以直接参考 popover可控式模式 ,用visible 参数处理，就像这样：
```vue
<template>
  <el-popconfirm
    width="220"
    icon-color="#626AEF"
    @cancel="cancel"
    @confirm="confirm"
    title="Are you sure to delete this?"
    :visible="visible"
  >
    <template #reference>
      <el-button @click="visible = !visible">气泡询问</el-button>
    </template>
  </el-popconfirm>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const visible = ref(false)

function cancel() {
  console.log('你点击了关闭按钮')
}
function confirm() {
  console.log('你点击了确认按钮')
}
</script>

```

**Comment by Fuphoenixes** [comment]
https://github.com/element-plus/element-plus/blob/cf9c936a0150375f3c1396c2baeeac2b5314068a/packages/components/popconfirm/src/popconfirm.vue#L6

**Comment by chenxch** [comment]
> 这样对于整体使用，不是特别友好，个人建议; 1、要么新增el-dialog属性:close-on-click-modal，可控制是否点击屏幕触发取消或者隐藏。 2、要么对于点击隐藏触发cancel事件 3、依据源码，popconfirm基于el-tooltip二次封装，本身视为可操作组件（气泡确认框），而非提示组件。

1、重点是popconfirm没有modal层一说，不是什么属性都能随便套。
2、说了是两个不同意义的操作怎么能用一个相同事件呢。
3、看了源码你应该就会发现可以使用 @Fuphoenixes 所说的方式。

**Comment by HU914** [comment]
是的，我现在是用的可控模式，
上述新增属性，只是个人建议，并不是说用modal层，只是类似的可控属性
