### ISSUE TITLE
[Style] [message] 使用 unplugin-auto-import 和 unplugin-vue-components 自动引入时，Elmessage样式丢失，或使 sass 自定义主题失效

### ISSUE THREAD

**Issue by polarove** [element-plus/element-plus#15717]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Github Repo](https://github.com/polarove/elmessage-bug-report)

### Steps to reproduce

clone最小复现环境的git仓库

```shell
pnpm i
```
```shell
pnpm dev
```

打开项目地址，点击 Click me 按钮

### What is Expected?

Elmessage 定位正确，样式不丢失

### What is actually happening?

Elmessage 定位有误，且样式丢失

### Additional comments

_(empty)_

**Comment by nova1751** [comment]
When using auto-import plugin,please don't import components explicitly,instead use `ElMessage` directly.To avoid `tsc` errors, include the revelant `*.d.ts` file in `tsconfig.json`.

**Comment by chenxch** [comment]
![WX20240130-184630](https://github.com/element-plus/element-plus/assets/23251408/2c8a5317-abca-497f-8e13-2d5f499fe985)
函数式组件需要自行引入样式。

**Comment by polarove** [comment]
> ![WX20240130-184630](https://private-user-images.githubusercontent.com/23251408/300777705-2c8a5317-abca-497f-8e13-2d5f499fe985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjU1MDgsIm5iZiI6MTcwNjY2NTIwOCwicGF0aCI6Ii8yMzI1MTQwOC8zMDA3Nzc3MDUtMmM4YTUzMTctYWJjYS00OTdmLThlMTMtMmQ1ZjQ5OWZlOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjgyMzUwMzNiZjI2NjdmMDM3M2M4MzU1MThjNjZkODI0MzNmYTUxZGI5MDBhZTFiNjY5MTBiZTFlMThlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMNJcxFQ6j7v-lfIXSKe4r1tR2tvgn4TjcVSpXtrL-w) 函数式组件需要自行引入样式。

感谢解答
原来我一直手动引入是对的吗？我在此之前寻思半天没理解什么是组件API，现在明白了。
