### ISSUE TITLE
[Style] [collapse] cant change el-collapse background

### ISSUE THREAD

**Issue by LAIguapi** [element-plus/element-plus#15710]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.0`
- Browser / OS: `Chrome 120.0.6099.227 /windows`
- Build Tool: `Vite`

### Related Component

- `el-collapse`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1jb2xsYXBzZSBzdHlsZT1cImJhY2tncm91bmQ6ICMwZjI0MzhcIiBjbGFzcz1cImRvbVwiPlxuICAgICAgPGVsLWNvbGxhcHNlLWl0ZW0gdGl0bGU9XCJDb25zaXN0ZW5jeVwiIG5hbWU9XCIxXCI+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgQ29uc2lzdGVudCB3aXRoIHJlYWwgbGlmZTogaW4gbGluZSB3aXRoIHRoZSBwcm9jZXNzIGFuZCBsb2dpYyBvZiByZWFsXG4gICAgICAgICAgbGlmZSwgYW5kIGNvbXBseSB3aXRoIGxhbmd1YWdlcyBhbmQgaGFiaXRzIHRoYXQgdGhlIHVzZXJzIGFyZSB1c2VkIHRvO1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICBDb25zaXN0ZW50IHdpdGhpbiBpbnRlcmZhY2U6IGFsbCBlbGVtZW50cyBzaG91bGQgYmUgY29uc2lzdGVudCwgc3VjaFxuICAgICAgICAgIGFzOiBkZXNpZ24gc3R5bGUsIGljb25zIGFuZCB0ZXh0cywgcG9zaXRpb24gb2YgZWxlbWVudHMsIGV0Yy5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgPC9lbC1jb2xsYXBzZT5cbiAgPGRpdiBjbGFzcz1cImRvbVwiIHN0eWxlPVwid2lkdGg6IDEwMHB4O2hlaWdodDogMTAwcHg7XCI+PC9kaXY+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmRvbXtcbiAgYmFja2dyb3VuZDogIzBmMjQzODtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzBmMjQzODtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

cant set background to el-collapse component
but after I switch Dark Theme, it is active

### What is Expected?

set the background style to collapse component whether in Dark Theme

### What is actually happening?

Only in the dark theme can it be available

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/56880133/159fc6e7-cea8-4a9d-942c-24d9632ee332)
![image](https://github.com/element-plus/element-plus/assets/56880133/ba7741eb-be99-42cf-90dd-1886189aeaea)
![image](https://github.com/element-plus/element-plus/assets/56880133/d1194c56-d4b4-410f-ad51-17defe30b154)

Before my screenshot, I also upgrade the version to 2.5.3, and I found that this problem still exists. I hope my problem can be carved with you

**Comment by kaine0923** [comment]
cause `el-collapse-item__header` and `el-collapse-item__content` has their style, you have to override it by yourself, in dark mode `background` is `transparent`
For now
[ElementPlus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1jb2xsYXBzZT5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiQ29uc2lzdGVuY3lcIiBuYW1lPVwiMVwiPlxuICAgICAgPGRpdj5cbiAgICAgICAgQ29uc2lzdGVudCB3aXRoIHJlYWwgbGlmZTogaW4gbGluZSB3aXRoIHRoZSBwcm9jZXNzIGFuZCBsb2dpYyBvZiByZWFsXG4gICAgICAgIGxpZmUsIGFuZCBjb21wbHkgd2l0aCBsYW5ndWFnZXMgYW5kIGhhYml0cyB0aGF0IHRoZSB1c2VycyBhcmUgdXNlZCB0bztcbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdj5cbiAgICAgICAgQ29uc2lzdGVudCB3aXRoaW4gaW50ZXJmYWNlOiBhbGwgZWxlbWVudHMgc2hvdWxkIGJlIGNvbnNpc3RlbnQsIHN1Y2hcbiAgICAgICAgYXM6IGRlc2lnbiBzdHlsZSwgaWNvbnMgYW5kIHRleHRzLCBwb3NpdGlvbiBvZiBlbGVtZW50cywgZXRjLlxuICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgPC9lbC1jb2xsYXBzZT5cbiAgPGRpdiBjbGFzcz1cImRvbVwiIHN0eWxlPVwid2lkdGg6IDEwMHB4O2hlaWdodDogMTAwcHg7XCI+PC9kaXY+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmVsLWNvbGxhcHNlLWl0ZW1fX2hlYWRlcixcbi5lbC1jb2xsYXBzZS1pdGVtX19jb250ZW50IHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzBmMjQzOCAhaW1wb3J0YW50O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by LAIguapi** [comment]
> cause `el-collapse-item__header` and `el-collapse-item__content` has their style, you have to override it by yourself, in dark mode `background` is `transparent` For now [ElementPlus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1jb2xsYXBzZT5cbiAgICAgIDxlbC1jb2xsYXBzZS1pdGVtIHRpdGxlPVwiQ29uc2lzdGVuY3lcIiBuYW1lPVwiMVwiPlxuICAgICAgPGRpdj5cbiAgICAgICAgQ29uc2lzdGVudCB3aXRoIHJlYWwgbGlmZTogaW4gbGluZSB3aXRoIHRoZSBwcm9jZXNzIGFuZCBsb2dpYyBvZiByZWFsXG4gICAgICAgIGxpZmUsIGFuZCBjb21wbHkgd2l0aCBsYW5ndWFnZXMgYW5kIGhhYml0cyB0aGF0IHRoZSB1c2VycyBhcmUgdXNlZCB0bztcbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdj5cbiAgICAgICAgQ29uc2lzdGVudCB3aXRoaW4gaW50ZXJmYWNlOiBhbGwgZWxlbWVudHMgc2hvdWxkIGJlIGNvbnNpc3RlbnQsIHN1Y2hcbiAgICAgICAgYXM6IGRlc2lnbiBzdHlsZSwgaWNvbnMgYW5kIHRleHRzLCBwb3NpdGlvbiBvZiBlbGVtZW50cywgZXRjLlxuICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbGxhcHNlLWl0ZW0+XG4gICAgPC9lbC1jb2xsYXBzZT5cbiAgPGRpdiBjbGFzcz1cImRvbVwiIHN0eWxlPVwid2lkdGg6IDEwMHB4O2hlaWdodDogMTAwcHg7XCI+PC9kaXY+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmVsLWNvbGxhcHNlLWl0ZW1fX2hlYWRlcixcbi5lbC1jb2xsYXBzZS1pdGVtX19jb250ZW50IHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzBmMjQzOCAhaW1wb3J0YW50O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

Okay, thank you very much for your reply, but this seems a bit anti -intuitive. In my understanding, if you can use it in the dark theme, then the light theme should also be okay like that
but this is just a bit of my personal question LOL
In short, thank you very much for your answer
