### ISSUE TITLE
[bug report] current-page property of pagination component

### ISSUE THREAD

**Issue by cjb263** [element-plus/element-plus#1571]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
window10/Google Chrome 87.0.4280.141（正式版本） （64 位）

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/cjb263/pen/rNWKgzm?editors=1111

### Steps to reproduce
打开https://codepen.io/cjb263/pen/rNWKgzm?editors=1111
等待2s

### What is Expected?
分页器组件在父组件中修改了current-page属性值不要触发current-change事件

### What is actually happening?
分页器组件在父组件中修改了current-page属性值会触发current-change事件 为什么会这样 我记得在element-ui中不会触发的

**Comment by Ryan2128** [comment]
Will fix soon.

**Comment by XingXiaoWu** [comment]
Why page change in parentComponent don't emit? it should be emit
