### ISSUE TITLE
[Component] [select] el-select组件在el-form组件为inline模式下，input没有渲染出来，必须指定宽度

### ISSUE THREAD

**Issue by BruceCham** [element-plus/element-plus#15715]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOmlubGluZT1cInRydWVcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgem9uZVwiPlxuICAgICAgPGVsLXNlbGVjdFxuICAgICAgICB2LW1vZGVsPVwiZm9ybUlubGluZS5yZWdpb25cIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIkFjdGl2aXR5IHpvbmVcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgID5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgb25lXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9uU3VibWl0XCI+UXVlcnk8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBmb3JtSW5saW5lID0gcmVhY3RpdmUoe1xuICB1c2VyOiAnJyxcbiAgcmVnaW9uOiAnYmVpamluZycsXG4gIGRhdGU6ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1mb3JtLWlubGluZSAuZWwtaW5wdXQge1xuICAtLWVsLWlucHV0LXdpZHRoOiAyMjBweDtcbn1cblxuLmRlbW8tZm9ybS1pbmxpbmUgLmVsLXNlbGVjdCB7XG4gIC0tZWwtc2VsZWN0LXdpZHRoOiAyMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、链接中可直接复现看到

### What is Expected?

能正常展现

### What is actually happening?

select没有渲染成功

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
请参考官网[demo](https://element-plus.org/zh-CN/component/form.html#%E8%A1%8C%E5%86%85%E8%A1%A8%E5%8D%95)实现方式。
