### ISSUE TITLE
[TypeScript] [pagination] paginationEmits 类型错误

### ISSUE THREAD

**Issue by JieleeJie** [element-plus/element-plus#15716]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.3`
- Browser / OS: `macOS 14.1.1`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHR5cGUgeyBQYWdpbmF0aW9uRW1pdHMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5pbnRlcmZhY2UgUGFnZVBhcmFtc1R5cGUge1xuICBjdXJyZW50UGFnZTogbnVtYmVyO1xuICBwYWdlU2l6ZTogbnVtYmVyO1xufVxuXG5jb25zdCBwYWdlUGFyYW1zID0gcmVmPFBhZ2VQYXJhbXNUeXBlPih7XG4gIGN1cnJlbnRQYWdlOiAxLFxuICBwYWdlU2l6ZTogMTBcbn0pO1xuXG5jb25zdCBnZXRBY3Rpdml0aWVzOlBhZ2luYXRpb25FbWl0c1snY2hhbmdlJ10gPSAoY3VycmVudFBhZ2UsIHBhZ2VTaXplKSA9PiB7fVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcGFnaW5hdGlvblxuICAgIHYtbW9kZWw6Y3VycmVudC1wYWdlPVwicGFnZVBhcmFtcy5jdXJyZW50UGFnZVwiXG4gICAgdi1tb2RlbDpwYWdlLXNpemU9XCJwYWdlUGFyYW1zLnBhZ2VTaXplXCJcbiAgICBsYXlvdXQ9XCJ0b3RhbCwgcHJldiwgcGFnZXIsIG5leHQsIHNpemVzLCBqdW1wZXJcIlxuICAgIGhpZGUtb24tc2luZ2xlLXBhZ2VcbiAgICA6cGFnZS1zaXplcz1cIlsxMCwgMjAsIDUwLCAxMDBdXCJcbiAgICA6dG90YWw9XCIxMDBcIlxuICAgIEBjaGFuZ2U9XCJnZXRBY3Rpdml0aWVzKClcIlxuICAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

handleChange函数TS报错

### What is Expected?

PaginationEmits['change'] 返回的应该是void而不是boolean

### What is actually happening?

Type 'void' is not assignable to type 'boolean'.ts(2322)

### Additional comments

_(empty)_

<img width="829" alt="image" src="https://github.com/element-plus/element-plus/assets/50036357/f961a8aa-4ca0-4cdf-b55b-853cc84c7d7d">

**Comment by JieleeJie** [comment]
<img width="737" alt="image" src="https://github.com/element-plus/element-plus/assets/50036357/80f3c990-7b7c-4609-a985-fe79f5b8414a">

**Comment by Fuphoenixes** [comment]
不是这么用的，PaginationEmits是 EmitValidator 类型[参考](https://cn.vuejs.org/api/options-state.html#emits)。
你可以这么写：
```ts
import { ElPagination } from 'element-plus'

type ElPaginationProps = InstanceType<typeof ElPagination>['$props']

const handleChange:ElPaginationProps['onChange']= (currentPage, pageSize) => {}
```
