### ISSUE TITLE
[Component] [cascader] el-cascader 在手机端，点击选项后，新的选项在屏幕之外，导致用户以为点击动作没有生效。  el-cascader On mobile, after clicking on an option, the new option is off-screen, causing the user to think that the click action did not take effect.

### ISSUE THREAD

**Issue by wuminmin** [element-plus/element-plus#15724]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.1`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Link](https://auto.dito.ph/#/form/mobile-drp)

### Steps to reproduce

用手机打开 https://auto.dito.ph/#/form/mobile-drp， 移动到 Home Address 的 el-cascader组件，任意点击二级选项，新出现的选项在屏幕之外。

### What is Expected?

期望新出现的选项应该自动显示在屏幕中，而不是屏幕之外。

### What is actually happening?

点击二级一下的任意选项，新生成的选项出现在屏幕之外。

### Additional comments

在老版本的 element ui的vue2版本，点击选项后，新生产的下一级选项会自动在屏幕内显示。

**Comment by yyuueexxiinngg** [comment]
This issue suggests improving user selection experience on mobile devices referencing the Cascader behavior in Element UI.

Whereas the cascade panel will auto-shift to left or right, ensuring the user's next possible selection stays in the middle of the screen.
 
Following is the demonstration video comparing the behaviors between Element UI and Element Plus.

https://github.com/element-plus/element-plus/assets/20928306/b5009282-3cd3-472a-a848-f1769a4533f5

**Comment by mrxyliushuang** [comment]
the same issue with me........

**Comment by muxigame** [comment]
https://codepen.io/yoloooooh/pen/WNobzEM
