### ISSUE TITLE
[Bug Report] el-table-column callback itself error

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#1572]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
win 10 / chorem 88

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-3bu0n?file=/src/table-column.vue

### Steps to reproduce
Upgrade to version 1.0.2-beta.33 does not work properly

### What is Expected?
Work as before (1.0.2-beta.32)

### What is actually happening?
Can't render accurately

**Comment by tolking** [comment]
I find the code from [table-column](https://github.com/element-plus/element-plus/blob/dev/packages/table/src/table-column/index.ts#L223)

```ts
const renderDefault = this.$slots.default?.()
if (renderDefault instanceof Array) {
  for (const childNode of renderDefault) {
    if (childNode.type?.name === 'ElTableColumn') {
      children.push(childNode)
    } else if (childNode.type === Fragment && childNode.children instanceof Array) {
      renderDefault.push(...childNode.children)
    }
  }
}
```

It will work when i try to change `renderDefault.push(...childNode.children)` to `children.push(...childNode.children)`, is a typo?

**Comment by Ryan2128** [comment]
cc @justwiner
