### ISSUE TITLE
[Component] [tabs] Tabs组件addIcon插槽没有效果

### ISSUE THREAD

**Issue by yuleniwo** [element-plus/element-plus#15732]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome104/Windows7`
- Build Tool: `CDN`

### Related Component

- `el-tabs`

### Reproduction Link

[CodePen](https://codepen.io/yuleniwo/pen/BabYqGw)

### Steps to reproduce

打开上面的链接即可查看效果。

主要代码：
<div id="app">
  <el-tabs type="card" tab-position="top" stretch addable>
    <template #addIcon><el-button type="primary" plain>Button</el-button></template>
    <el-tab-pane label="PANE"></el-tab-pane>
  </el-tabs>
</div>
<script>
  const app = Vue.createApp({});
  app.use(ElementPlus);
  app.mount("#app");
</script>

### What is Expected?

tabs组件的默认添加按钮变成一个自定义的按钮。

### What is actually happening?

还是默认的添加按钮，addIcon插槽不生效。

### Additional comments

下载并修改element-plus最终的js文件https://unpkg.com/element-plus@2.5.3/dist/index.full.js，把里面的两处“addIcon”修改成“addicon”，即改成小写，上述的问题得到解决。不确定是不是bug，不知道有没有办法强制区分插槽名大小写。

**Comment by chenxch** [comment]
[docs](https://cn.vuejs.org/guide/essentials/component-basics.html#case-insensitivity)  这是vue在cdn模式下一个机制问题，当然我们在设计插槽的使用应该要考虑到这个场景。后续会修复这个问题。
