### ISSUE TITLE
[Component] [select-v2] The component does not show the selected label but value, when I set the value manually.

### ISSUE THREAD

**Issue by GeraltWang** [element-plus/element-plus#15751]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24sIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZmFrZUFwaSA9IGFzeW5jICgpID0+IHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7XG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICByZXNvbHZlKHtcbiAgICAgICAgZGF0YTogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGNvbXBJZDogNSxcbiAgICAgICAgICAgIGNvbXBOYW1lOiBcIuaxn+iLj+aXuuWxueaNt+W7uuetkeW3peeoi+aciemZkOWFrOWPuFwiXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjb21wSWQ6IDYsXG4gICAgICAgICAgICBjb21wTmFtZTogXCLmsZ/oi4/llK/ljY7lu7rorr7mnInpmZDlhazlj7hcIlxuICAgICAgICAgIH1cbiAgICAgICAgXVxuICAgICAgfSlcbiAgICB9LCAxMDAwKVxuICB9KVxufVxuIFxuY29uc3QgcXVlcnlQYXJhbXMgPSByZWFjdGl2ZSh7XG4gIGNvbXBJZDogdW5kZWZpbmVkXG59KVxuXG5jb25zdCBjb21wYW55T3B0aW9ucyA9IHJlZihbXSlcblxuY29uc3QgZ2V0Q29tcGFueUxpc3QgPSBhc3luYyAoKSA9PiB7XG4gIC8vIGdldCBjb21wYW55IGxpc3QgZnJvbSBzZXJ2ZXIgXG4gIGNvbnN0IHsgZGF0YSB9ID0gYXdhaXQgZmFrZUFwaSgpXG5cbiAgLy8gZmlsdGVyIHNlcnZlciBjb21wYW55IGxpc3RcbiAgY29tcGFueU9wdGlvbnMudmFsdWUgPSBkYXRhLm1hcCgoaXRlbSkgPT4gKHtcbiAgICBsYWJlbDogaXRlbS5jb21wTmFtZSxcbiAgICB2YWx1ZTogaXRlbS5jb21wSWRcbiAgfSkpXG5cbiAgLy8gZGVmYXVsdCBzZWxlY3QgdGhlIGZpcnN0IGNvbXBhbnlcbiAgcXVlcnlQYXJhbXMuY29tcElkID0gY29tcGFueU9wdGlvbnMudmFsdWVbMF0/LnZhbHVlXG59XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGdldENvbXBhbnlMaXN0KClcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInF1ZXJ5UGFyYW1zLmNvbXBJZFwiXG4gICAgOm9wdGlvbnM9XCJjb21wYW55T3B0aW9uc1wiXG4gICAgZmlsdGVyYWJsZVxuICAgIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oupXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

The issue only shows on production environment, on dev server everything works.
- get options from an api
- manually set component's value to the first option's value
- The component does not show the selected label but value

### What is Expected?

The component should show the selected label, when I set the value manually.

### What is actually happening?

The component does not show the selected label but value, when I set the value manually.

### Additional comments

_(empty)_

on dev everything works
![image](https://github.com/element-plus/element-plus/assets/58298096/d8d8c614-87c2-4ffb-8aee-143544bca42e)
on production it does not show the selected label but value
![image](https://github.com/element-plus/element-plus/assets/58298096/724401fa-62d5-4473-b254-16877dbc1547)

**Comment by kooriookami** [comment]
This demo is incomplete. Can you use setTimeout to mock the api?

**Comment by GeraltWang** [comment]
> This demo is incomplete. Can you use setTimeout to mock the api?

demo updated, please check, thanks

**Comment by kooriookami** [comment]
https://github.com/element-plus/element-plus/assets/38392315/ec619278-0455-473a-b0eb-4471bbd29459

I tried 2.5.3, it shows well.

**Comment by GeraltWang** [comment]
> QQ2024131-112753-HD.mp4 
> I tried 2.5.3, it shows well.


https://github.com/element-plus/element-plus/assets/58298096/d9c13bc1-d8d7-4a86-bd25-23e4fdd286b7

**Comment by kooriookami** [comment]
I found it's abnormal in playground. It's weird.

**Comment by GeraltWang** [comment]
> I found it's abnormal in playground. It's weird.

i found it happends after version 2.4.4

https://github.com/element-plus/element-plus/assets/58298096/987cbfda-08f9-49d3-9732-2bb21c80f823

**Comment by chenxch** [comment]
same as #15586

**Comment by leeobrum** [comment]
Hi @GeraltWang , here is your solution!

Old
queryParams.compId = companyOptions.value[0]?.value

New
queryParams.compId = await new Promise((resolve) => {
  resolve(companyOptions.value[0]?.value)
})
