### ISSUE TITLE
[Component] [select] El-Select in form showed the smallest width in v2.5.3

### ISSUE THREAD

**Issue by duxingzhe** [element-plus/element-plus#15759]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Link](https://gitee.com/duxingzhe103/element-bug-report/blob/master/2024%E5%B9%B42%E6%9C%882%E6%97%A5%E5%8F%8D%E9%A6%88%E7%9A%84%E9%97%AE%E9%A2%98.vue)

### Steps to reproduce

使用最新的2.5.3版本，el-select的宽度是最小的，但是退回到2.4.0版本则是正常大小。

### What is Expected?

与2.4.0保持一致。

### What is actually happening?

一个非常非常小的选择框，是不正常的。

### Additional comments

_(empty)_
2.4.0，正常版本
![2 4 0](https://github.com/element-plus/element-plus/assets/8346252/e72f891c-0bec-4f02-a731-539da750774c)
2.5.3，最新版本
![2 5 3](https://github.com/element-plus/element-plus/assets/8346252/ea99fae5-f164-4248-8ac0-3014b16d21b4)

**Comment by chenxch** [comment]
```css
.demo-form-inline .el-select {
  --el-select-width: 220px;
}
```

**Comment by duxingzhe** [comment]
> ```css
> .demo-form-inline .el-select {
>   --el-select-width: 220px;
> }
> ```

My Suggestion is rollback to previous behavior.

**Comment by chenxch** [comment]
> > ```css
> > .demo-form-inline .el-select {
> >   --el-select-width: 220px;
> > }
> > ```
> 
> My Suggestion is rollback to previous behavior.

Sry, there is no rollback plan for this part, you can check #15352.

**Comment by duxingzhe** [comment]
But the question is el-select could change the width automatically as same as el-input in el-form. If I make the fixed width, it will be a layout problem in other pages. Please provide a better solution.

**Comment by chenxch** [comment]
<el-form-item label="故障等级" prop="faultLevel" style="width: 100%;">

**Comment by chenxch** [comment]
<el-form-item label="故障等级" prop="faultLevel" style="width: 100%;">

**Comment by chenxch** [comment]
```
 <el-form-item label="故障等级" prop="faultLevel" style="width: 100%;">
```

**Comment by duxingzhe** [comment]
> ```
>  <el-form-item label="故障等级" prop="faultLevel" style="width: 100%;">
> ```

For heaven sake, not working.

**Comment by chenxch** [comment]
```
:deep(.el-form-item){
  width: 100%;
}
```
If you find it troublesome to add them one by one, you can be flexible.

**Comment by duxingzhe** [comment]
> ```
> :deep(.el-form-item){
>   width: 100%;
> }
> ```
> 
> If you find it troublesome to add them one by one, you can be flexible.

Well, thanks for this advise. But I still hope that el-select could be rollbacked to previous behavior in future version. The discussion is accomplished.
