### ISSUE TITLE
[Docs] [All] 组件文档不规范，中英文混乱

### ISSUE THREAD

**Issue by gudch** [element-plus/element-plus#15763]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.3`
- Browser / OS: `任意`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/steps.html#%E8%B4%A1%E7%8C%AE%E8%80%85)

### Steps to reproduce

1. 登录组件官网
2. 查看组件文档
3. 就会发现组件文档中的属性等的描述标题有的是英文有的是中文

### What is Expected?

建议：规范点儿，中文环境下全写成中文，或者一律英文

### What is actually happening?

中英文混乱

### Additional comments

加油

**Comment by chenxch** [comment]
![image](https://github.com/element-plus/element-plus/assets/23251408/4bf7fce4-d479-498e-947f-3464c54f8c0a)
Welcome to join translation
