### ISSUE TITLE
[Component] [image] el-image 预览图片出现死循环问题

### ISSUE THREAD

**Issue by 1142231051** [element-plus/element-plus#15777]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.10`
- Element Plus Version: `2.3.4`
- Browser / OS: `window10 window 11`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8taW1hZ2VfX3ByZXZpZXdcIj5cbiAgICA8ZWwtaW1hZ2Ugc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIiA6c3JjPVwidXJsXCIgOnpvb20tcmF0ZT1cIjEuMlwiIDptYXgtc2NhbGU9XCI3XCIgOm1pbi1zY2FsZT1cIjAuMlwiXG4gICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIiA6aW5pdGlhbC1pbmRleD1cIjRcIiBmaXQ9XCJjb3ZlclwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCAgc2V0dXA+XG5jb25zdCB1cmwgPVxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnXG5jb25zdCBzcmNMaXN0ID0gW1xuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzEvMzQvMTlhYTk4YjFmY2IyNzgxYzRmYmEzM2Q4NTA1NDlqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzAvNmYvZTM1ZmYzNzU4MTJlNmIwMDIwYjZiNGU4Zjk1ODNqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzkvYmIvZTI3ODU4ZTk3M2Y1ZDdkMzkwNDgzNWY0NmFiYmRqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2QvZTYvYzRkOTNhMzgwNWIzY2UzZjMyM2Y3OTc0ZTZmNzhqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvMjgvYmJmODkzZjc5MmYwM2E1NDQwOGIzYjdhN2ViZjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzIvMTEvNjUzNWJjZmIyNmU0Yzc5YjQ4ZGRkZTQ0ZjRiNmZqcGVnLmpwZWcnLFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1pbWFnZV9fZXJyb3IgLmltYWdlLXNsb3Qge1xuICBmb250LXNpemU6IDMwcHg7XG59XG5cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCAuZWwtaWNvbiB7XG4gIGZvbnQtc2l6ZTogMzBweDtcbn1cblxuLmRlbW8taW1hZ2VfX2Vycm9yIC5lbC1pbWFnZSB7XG4gIHdpZHRoOiAxMDAlO1xuICBoZWlnaHQ6IDIwMHB4O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

创建一个干净的vite vue3项目  把上面链接的代码复制 过去，点击预览

### What is Expected?

不会出现死循环 

### What is actually happening?

localhost/:1 Uncaught (in promise) Maximum recursive updates exceeded in component <BaseTransition>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

### Additional comments

出现上面的红色警告和 Unhandled error during execution of app errorHandler 我不知道是不是vue 和 elementui兼容问题

**Comment by Fuphoenixes** [comment]
2.5.2 版本之后就已修复
https://github.com/element-plus/element-plus/pull/15483
