### ISSUE TITLE
[Feature Request] is element plus responsive-first design?

### ISSUE THREAD

**Issue by laoshaw** [element-plus/element-plus#1578]
### Existing Component
Yes

### Component Name
element-plus

### Description
I could not find any statement about element plus, new to it, element UI was desktop only, is element plus adding responsive support?

**Comment by Giwayume** [comment]
It works on phones, but not all components are designed with touch screen in mind. For example, in the el-select component if the options list has a scrollbar it will not show up on a phone because it's designed to display based on mouse hover.
