### ISSUE TITLE
[ BUG ] Tree with over 168mb data is freezing chrome

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1579]
https://element-plus.org/#/en-US/component/tree
This tree is working great with almost any data.
I have one component that is using the tree and it receiving data.
When i receive data with size 168mb, Tree is freezing chrome and everything is not working.
or chrome will show a dialog box Page Unresponsive

**Comment by Ryan2128** [comment]
Sorry, at the current stage, we have not dealt with the problem of big data rendering. We will deal with this problem in a subsequent version. Thank you for your feedback.

**Comment by vadimt2** [comment]
@Ryan2128
```
<div class="custom-tree-container">
    <el-tree :data="data">
      <span class="custom-tree-node" slot-scope="{ data }">
        <span>{{ data.item.label }}</span>
      </span>
    </el-tree>
</div>
```
Please try this code above and fetch this data:
[https://num1.co.il/fetchdata/data.json](https://num1.co.il/fetchdata/data.json)
You will see that the tree can't handle it and the browser will be out of memory.
**Element UI - not crashing like element plus**

* I have no other way to provide this data, expect downloading the url that i have provided to local machine
and using axios or fetch

**Comment by Ryan2128** [comment]
Sorry, we can’t process so much data at once. When I used the browser to request the data you gave, the browser’s tab page or the Postman already reported a memory overflow error.

The browser does not support creating so many Dom nodes at once.

![image](https://user-images.githubusercontent.com/33176053/111162693-5c6c5b00-85d7-11eb-8151-69e4a0b60224.png)

I don’t think Element UI can handle so much data, because 160MB of data is too much.

**Comment by vadimt2** [comment]
I have increased the memory in vue js 2 and element ui did the job.
I have  increased the memory in vue js 3 and element plus wash crashing.
And i had to switch the element plus tree to primevue tree.
I hope in the feature element plus tree will have same performance as element ui.

**Comment by Ryan2128** [comment]
> I have increased the memory in vue js 2 and element ui did the job.
> I have increased the memory in vue js 3 and element plus wash crashing.
> And i had to switch the element plus tree to primevue tree.
> I hope in the feature element plus tree will have same performance as element ui.

Can you provide me with more data details? Just like how many levels and how many pieces of data, instead of a simple 160MB, I don’t know how many pieces of data this physical size represents.

**Comment by vadimt2** [comment]
I have uploaded this file to here
https://drive.google.com/file/d/1-G17oZeJPTnkJ1uIeuJJeg88MHY10ZQV/view?usp=sharing
or you can get the data from here by copy past
https://num1.co.il/fetchdata/data.json
