### ISSUE TITLE
table resize

### ISSUE THREAD

**Issue by Yimisunny** [element-plus/element-plus#1580]
窗口拉大 table宽度会相应变大，但是窗口再缩小时table宽度不会再变小了

**Comment by Ryan2128** [comment]
Maybe has been fixed #1567 , cc @justwiner

**Comment by yuanguqiu** [comment]
table还有个问题，expand拓展栏现在点击以后是整个表格数据更新了，而不是仅展开

**Comment by Yimisunny** [comment]
@yuanguqiu 你也遇到table窗口缩小不能改变大小吗

**Comment by Yimisunny** [comment]
@justwiner 窗口缩小时，table上的style="width: XXXpx;" 样式没有变化

**Comment by Yimisunny** [comment]
@justwiner 我查找出原因了，我的最外层页面容器使用了display:flex;  ，table的父级容器使用了flex:1。  这样的设置窗口缩小table就不会改变尺寸。

**Comment by justwiner** [comment]
> @justwiner 我查找出原因了，我的最外层页面容器使用了display:flex; ，table的父级容器使用了flex:1。 这样的设置窗口缩小table就不会改变尺寸。

Hey, Can you provide a test case, I will follow up on this issue here. Maybe `codeopen`
thanks.

**Comment by mrsai** [comment]
很多年的BUG了，一直没有修复。。。就是flex布局下会出现这个问题，我用计算属性重新设置了一下宽度，但是由于有动画，所以效果非常不好。

**Comment by rebider** [comment]
mark
