### ISSUE TITLE
[Component] [dropdown, button] Component Dropdown with button, an outline shows when hover, but not disappear when hover out.

### ISSUE THREAD

**Issue by maicss** [element-plus/element-plus#15808]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.5`
- Browser / OS: `Chrome/121.0.0.0 Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgPGVsLWJ1dHRvbiA6aWNvbj1cIkFycm93RG93blwiIHBsYWluPkRyb3Bkb3duIExpc3Q8L2VsLWJ1dHRvbj5cbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXNhYmxlZD5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IEFycm93RG93biB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

When mouse hover dropdown button, it will show an outline around the button, when mouse hover out, the outline still there

### What is Expected?

When mouse hover out or clicked submenu, the outline disappears.

### What is actually happening?

The outline keeps showing.

### Additional comments

_(empty)_

**Comment by nova1751** [comment]
This is because the dropdown box is foucused when your cursor move into the dropdown box area.The outline is the behavior of the browser.

**Comment by maicss** [comment]
> This is because the dropdown box is foucused when your cursor move into the dropdown box area.The outline is the behavior of the browser.

So, this will not be treated as a bug and will not be fixed?

**Comment by nova1751** [comment]
> > This is because the dropdown box is foucused when your cursor move into the dropdown box area.The outline is the behavior of the browser.
> 
> So, this will not be treated as a bug and will not be fixed?

I guess this issue won't be solved until next big version release.There are some hack ways to fix this.But they are not reasonable enough because the deep focus logic parts don't change though.

**Comment by tolking** [comment]
This is normal behavior
