### ISSUE TITLE
[Component] [select] el-form为行内表单时，select下拉框父级未设置宽度，导致样式错误

### ISSUE THREAD

**Issue by bingo-Hub** [element-plus/element-plus#15811]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.5`
- Browser / OS: `Chrome 121.0.6167.140/Win10`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCBEZW1vIGZyb20gJy4vRGVtby52dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+XG4gICAgICA8RWxlbWVudFBsdXMgLz5cbiAgICA8L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cblxuICA8aDI+RGVtb+a1i+ivlTwvaDI+XG4gIDxkZW1vIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL0RlbW8udnVlIjoiPHRlbXBsYXRlPlxyXG48ZWwtZm9ybSA6bW9kZWw9XCJxdWVyeVBhcmFtc1wiIDppbmxpbmU9XCJ0cnVlXCIgbGFiZWwtd2lkdGg9XCI2OHB4XCI+XHJcbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi6YOo6Zeo5ZCN56ewXCIgcHJvcD1cImRlcHROYW1lXCI+XHJcbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwicXVlcnlQYXJhbXMuZGVwdE5hbWVcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpemDqOmXqOWQjeensFwiIGNsZWFyYWJsZSAvPlxyXG4gICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi54q25oCBIFwiIHByb3A9XCJzdGF0dXNcIj5cclxuICAgICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwicXVlcnlQYXJhbXMuc3RhdHVzXCIgcGxhY2Vob2xkZXI9XCLor7fpgInmi6nnirbmgIEgXCIgY2xlYXJhYmxlPlxyXG4gICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiA6dmFsdWU9XCJpdGVtLnZhbHVlXCIgLz5cclxuICAgICAgPC9lbC1zZWxlY3Q+XHJcbiAgICA8L2VsLWZvcm0taXRlbT5cclxuICAgIDxlbC1mb3JtLWl0ZW0+XHJcbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBpY29uPVwiU2VhcmNoXCI+5pCc57SiPC9lbC1idXR0b24+XHJcbiAgICAgIDxlbC1idXR0b24gaWNvbj1cIlJlZnJlc2hcIj7ph43nva48L2VsLWJ1dHRvbj5cclxuICAgIDwvZWwtZm9ybS1pdGVtPlxyXG4gIDwvZWwtZm9ybT5cclxuPC90ZW1wbGF0ZT5cclxuXHJcbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XHJcbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJztcclxuXHJcbmNvbnN0IHF1ZXJ5UGFyYW1zID0gcmVhY3RpdmUoeyBkZXB0TmFtZTogJycsIHN0YXR1czogbnVsbCB9KVxyXG5cclxuY29uc3Qgb3B0aW9ucyA9IHJlYWN0aXZlKFt7IGxhYmVsOiAn5q2j5bi4JywgdmFsdWU6ICcxJyB9LCB7IGxhYmVsOiAn5YGc55SoJywgdmFsdWU6ICcwJyB9XSlcclxuPC9zY3JpcHQ+IiwiX28iOnt9fQ==)

### Steps to reproduce

el-form为行内表单时，select下拉框宽度显示不全

### What is Expected?

select下拉框宽度和input一致

### What is actually happening?

select下拉框宽度特别窄，无法显示具体内容

### Additional comments

_(empty)_

**Comment by axolo** [comment]
#15352

**Comment by kooriookami** [comment]
```scss
.el-form--inline {
  .el-form-item {
    & > .el-input, .el-cascader, .el-select, .el-date-editor, .el-autocomplete {
      width: 240px;
    }
  }
}
```

**Comment by bingo-Hub** [comment]
解决方案：如果不影响其他组件的情况下，是否可以统一设置此属性样式，以达到避免单独设置样式又可以解决此问题。
.el-form-item__content {
  min-width: var(--el-form-inline-content-width);
}



Ni好
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月5日(星期一) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [select] el-form为行内表单时，select下拉框父级未设置宽度，导致样式错误 (Issue #15811)





 
#15352
