### ISSUE TITLE
[Style] [select] el-select使用远程搜索(remote)的bug

### ISSUE THREAD

**Issue by xiaoxin-vue** [element-plus/element-plus#15816]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.5.5`
- Browser / OS: `Google Chrome120.0.6099.110`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Link]()

### Steps to reproduce

<el-select
            v-model="idList"
            :loading="isLawLoading"
            placeholder="请选择选项"
            filterable
            remote
            reserve-keyword
            :remote-method="remoteMethod"
            multiple
            @focus="focusSelect"
            @change="Change"
          >
            <el-option
              v-for="item in List"
              :key="item.id"
              :label="item.bt"
              :value="item.id"
            >
            </el-option>
          </el-select>

### What is Expected?

输入文本框宽度很小

### What is actually happening?

输入框宽度宽度100%

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/71539641/6090d9f2-ab80-49a6-a2ea-5b6ce8b76a72)

**Comment by xiaoxin-vue** [comment]
<img width="612" alt="Snipaste_2024-02-05_17-05-22" src="https://github.com/element-plus/element-plus/assets/71539641/a0eed55a-19a9-4039-8947-e72614fb78b8">

**Comment by xiaoxin-vue** [comment]
https://github.com/element-plus/element-plus/assets/71539641/8a411841-ac77-4be3-9ed6-7d0aeef55850

**Comment by nova1751** [comment]
#15510

**Comment by kooriookami** [comment]
未复现，请提供一个有效的demo

**Comment by george-waynee** [comment]
> el-select.bug.mp4

我也出现了相同问题，查看元素排查，发现输入文字的时候，里面的input不会自动增大宽度，请问现在解决了吗？我用的是element-plus@2.6.0

**Comment by kooriookami** [comment]
> > el-select.bug.mp4
> 
> 我也出现了相同问题，查看元素排查，发现输入文字的时候，里面的input不会自动增大宽度，请问现在解决了吗？我用的是element-plus@2.6.0

可以提供一下复现条件，比如浏览器版本，或者具体的代码

**Comment by george-waynee** [comment]
> > > el-select.bug.mp4
> > 
> > 
> > 我也出现了相同问题，查看元素排查，发现输入文字的时候，里面的input不会自动增大宽度，请问现在解决了吗？我用的是element-plus@2.6.0
> 
> 可以提供一下复现条件，比如浏览器版本，或者具体的代码

浏览器: 版本 122.0.6261.112（正式版本） (arm64)
element-plus@2.6.0

` <el-select
        v-model="selectVal"
        class="catalog-select"
        placeholder="输入搜索关键字"
        remote
        remote-show-suffix
        filterable
        reserve-keyword
        :remote-method="remoteMethod"
        :loading="loading"
        style="width: 246px"
      >
        <template #prefix>指导部门：</template>
        <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value" />
      </el-select>`

![image](https://github.com/element-plus/element-plus/assets/17469911/8a11da49-215e-446b-bdf7-e0542fe3735e)
正常的拷贝Demo过来使用，输入文字之后，输入框的行内宽度样式没有变化

**Comment by kooriookami** [comment]
@george-waynee 我本地未复现，请在 https://element-plus.run/ 创建一个可复现的链接。

**Comment by george-waynee** [comment]
> @george-waynee 我本地未复现，请在 https://element-plus.run/ 创建一个可复现的链接。

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgdHlwZSBSZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSlcbmNvbnN0IHNlbGVjdFZhbCA9IHJlZignJylcbmNvbnN0IG9wdGlvbnM6IFJlZjxcbiAgQXJyYXk8e1xuICAgIHZhbHVlOiBzdHJpbmdcbiAgICBsYWJlbDogc3RyaW5nXG4gIH0+XG4+ID0gcmVmKFtdKVxuXG5jb25zdCByZW1vdGVNZXRob2QgPSAocXVlcnk6IHN0cmluZykgPT4ge1xuICBpZiAocXVlcnkpIHtcbiAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICAgIC8vIFRPRE8g6K+35rGC5o6l5Y+jXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICBsb2FkaW5nLnZhbHVlID0gZmFsc2VcbiAgICAgIG9wdGlvbnMudmFsdWUgPSBjYXRhbG9nT3B0aW9uc1xuICAgIH0sIDIwMClcbiAgfSBlbHNlIHtcbiAgICBvcHRpb25zLnZhbHVlID0gW11cbiAgfVxufVxuXG5jb25zdCBjYXRhbG9nT3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJ1xuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMydcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240J1xuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnXG4gIH1cbl1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cblxuPGVsLXNlbGVjdFxuICB2LW1vZGVsPVwic2VsZWN0VmFsXCJcbiAgY2xhc3M9XCJjYXRhbG9nLXNlbGVjdFwiXG4gIHBsYWNlaG9sZGVyPVwi6L6T5YWl5pCc57Si5YWz6ZSu5a2XXCJcbiAgcmVtb3RlXG4gIHJlbW90ZS1zaG93LXN1ZmZpeFxuICBmaWx0ZXJhYmxlXG4gIDpyZW1vdGUtbWV0aG9kPVwicmVtb3RlTWV0aG9kXCJcbiAgOmxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgc3R5bGU9XCJ3aWR0aDogMjQ2cHhcIlxuPlxuICA8dGVtcGxhdGUgI3ByZWZpeD7mtYvor5XmlofmnKzvvJo8L3RlbXBsYXRlPlxuICA8ZWwtb3B0aW9uIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsdWVcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIC8+XG48L2VsLXNlbGVjdD5cblxuPC90ZW1wbGF0ZT5cblxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319



抱歉，我这边没有办法复现出来，我留意一下我这边的情况
