### ISSUE TITLE
[Bug Report] Opening two notifications at the same time causes overlap

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1581]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
chrome

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/vgbire/pen/KKNejOB

### Steps to reproduce
Call $notify twice in a row to open notification

### What is Expected?
Non overlapping

### What is actually happening?
overlap

**Comment by Vgbire** [comment]
The reason for this problem is that the DOM is hung up, but it hasn't been rendered well, so the height is unknown
![image](https://user-images.githubusercontent.com/32129111/110113835-a5116080-7dee-11eb-962e-97f2ee48ce67.png)

**Comment by Ryan2128** [comment]
You can add `await nextTick()` between them, this method may be changed to asynchronous in the future to ensure that the position is correct when a large number of calls are made, but not now.
