### ISSUE TITLE
[Component] Vue 3.4.16 will cause all components created with render function in Element-Plus to not display.

### ISSUE THREAD

**Issue by mlkt** [element-plus/element-plus#15840]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.16`
- Element Plus Version: `2.5.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-select`
- `el-menu`
- `el-container`
- `el-overlay`
- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpkaXNhYmxlZD1cIml0ZW0uZGlzYWJsZWRcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICAgIGRpc2FibGVkOiB0cnVlLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Vue 3.4.16 版本会导致 element-plus 所有用渲染函数创建的组件都无法显示

可以在上面的链接测试，Element Plus版本选择2.5.5，Vue版本选择3.4.16，选择后可以发现点击 el-select 下拉框无法显示，看控制台发现是弹出层被设为了 display: none 导致无法显示，将Vue版本切换为 3.4.15 后恢复正常。

除了 el-select 无法显示的组件还有很多，比如 el-container 、el-menu 、el-scrollbar 、 el-overlay 等，看了下代码，发现这些组件都是用渲染函数实现的，使用 template 的组件好像都正常显示。原因可以看我在 https://github.com/vuejs/core/issues/10294 发的。但不知道是Vue那边的改动欠考虑还是这边的写法有问题。

### What is Expected?

正常显示

### What is actually happening?

无法显示

### Additional comments

_(empty)_

**Comment by mlkt** [comment]
https://github.com/vuejs/core/issues/10294

**Comment by yetian** [comment]
It will be interesting to see why it happens... Here is the diff between v3.4.15 and v3.4.16: https://github.com/vuejs/core/compare/v3.4.15..v3.4.16

**Comment by leorantakupari** [comment]
Same here, help lol

**Comment by sxzz** [comment]
Cannot do anything, but users can rollback to Vue v3.4.15. Please track issue https://github.com/vuejs/core/issues/10294

**Comment by sxzz** [comment]
Try Vue v3.4.18
