### ISSUE TITLE
[Build] Can't run pnpm i, postinstall commands breaking on import line

### ISSUE THREAD

**Issue by guska8** [element-plus/element-plus#15842]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.4.16`
- Element Plus Version: `2.5.5`
- Browser / OS: `none`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

1. Clone the project on master branch
2. run `pnpm i`

### What is Expected?

install all dependencies and run postinstall without errors

### What is actually happening?

postinstall "pnpm gen:version" command is giving error:

```
/element-plus/internal/metadata/src/components.ts:1
import path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
```

### Additional comments

I'm trying to create my version of select component based on elSelect. On my legacy project based on ElementUI i could just `extends: ElSelect` and override what was needed but it seems no longer possible with composition API. Because o that i figured i could create a branch of elementplus and create my customized component in there.

**Comment by ikkkp** [comment]
try ` pnpm update tsx`

**Comment by guska8** [comment]
> try ` pnpm update tsx`

this fixed my problem, thank you!

**Comment by xuejunnan** [comment]
Sorry, i just want to know what's your version of node.
My node version: v20.11.0
I already run "pnpm update tsx", but the error "SyntaxError: Cannot use import statement outside a module" still remains
How to resolve that?

**Comment by guska8** [comment]
> Sorry, i just want to know what's your version of node. My node version: v20.11.0 I already run "pnpm update tsx", but the error "SyntaxError: Cannot use import statement outside a module" still remains How to resolve that?

I was using node 18 but on the next day when i restarted my computed the problem came back and i gave up. As the problem is ocurring with more people i'm reopening this.

**Comment by guska8** [comment]
node 16 fixed for real this time! thank you
