### ISSUE TITLE
[Component] [dialog, select] 在el-dialog中渲染大量dom导致弹窗打开时间长

### ISSUE THREAD

**Issue by codehrXuan** [element-plus/element-plus#15859]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.5.5`
- Browser / OS: `edge 121.0.2277.98 / macOS 14.2 (23C64)`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3Qgc2VsZWN0VmFsdWUgPSByZWYoJycpXG5jb25zdCB0aW1lciA9IHJlZigxKVxuY29uc3QgZGlhbG9nVGFibGVWaXNpYmxlID0gcmVmKGZhbHNlKTtcbmNvbnN0IHNob3dEaWFsb2cgPSAoKT0+e1xuICBkaWFsb2dUYWJsZVZpc2libGUudmFsdWUgPSB0cnVlXG59XG5zZXRJbnRlcnZhbCgoKSA9PiB7XG4gIHRpbWVyLnZhbHVlKytcbn0sIDEwMDApO1xuY29uc3Qgb3B0aW9ucyA9IFtdXG5mb3IgKGxldCBpID0gMDsgaSA8IDEwMDAwOyBpKyspIHtcbiAgb3B0aW9ucy5wdXNoKFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24nK2ksXG4gICAgbGFiZWw6ICdPcHRpb24nK2ksXG4gIH0pXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8YnV0dG9uIEBjbGljaz1cInNob3dEaWFsb2dcIj4zMjE8L2J1dHRvbj5cbiAge3sgdGltZXIgfX1cbiAgIDxlbC1kaWFsb2cgdi1tb2RlbD1cImRpYWxvZ1RhYmxlVmlzaWJsZVwiPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJzZWxlY3RWYWx1ZVwiXG4gICAgICBjbGFzcz1cIm0tMlwiXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZWwtZGlhbG9nPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvQ29tcC52dWUiOiIiLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <button @click="showDialog">321</button>
  <el-dialog v-model="dialogTableVisible">
    <el-select
      v-model="value"
      class="m-2"
      placeholder="Select"
      size="large"
      style="width: 240px"
    >
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      />
    </el-select>
  </el-dialog>
</template>

<script setup>
import { ref } from 'vue'

const value = ref('')
const dialogTableVisible = ref(false);
const showDialog = ()=>{
  dialogTableVisible.value = true
}

const options = []
for (let i = 0; i < 10000; i++) {
  options.push(
  {
    value: 'Option'+i,
    label: 'Option'+i,
  })
}
</script>
```

### What is Expected?

点击按钮直接打开dialog弹窗

### What is actually happening?

点击按钮后页面卡顿数秒时间，页面定时器阻塞，过几秒后弹窗出现

### Additional comments

_(empty)_

**Comment by codehrXuan** [comment]
2.3.0以上版本会有这个问题，以下版本正常

**Comment by codehrXuan** [comment]
2.3.0版本以上会有这个问题

**Comment by shenlanchenwei** [comment]
直接弹出都不显示了,有bug

**Comment by chenxch** [comment]
数据量这么大，请考虑使用el-select-v2

**Comment by codehrXuan** [comment]
> 数据量这么大，请考虑使用el-select-v2

里面不一定会是select，使用级联选择器或者其他的组件也会有这个问题，只要是数据比较多的情况就会有。比如动态渲染某些组件的情况

**Comment by shenlanchenwei** [comment]
拿官方代码都弹不出下拉选择框

**Comment by codehrXuan** [comment]
> 数据量这么大，请考虑使用el-select-v2

我的页面中大概有三四个select,然后每个大概有400-500条数据，然后打开渲染的时候就会有4-5秒的延迟
