### ISSUE TITLE
[Component] [input] v-show使用初始化变量控制显示或隐藏时不起作用

### ISSUE THREAD

**Issue by wangnamin** [element-plus/element-plus#15864]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.5.5`
- Browser / OS: `Chrome版本 121.0.6167.185（正式版本） （64 位）`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cImNoZWNrZWQxXCIgOmxhYmVsPVwiJ+WAvOS4uu+8micgKyBjaGVja2VkMVwiIHNpemU9XCJsYXJnZVwiIC8+XG4gICAgPGRpdj5cbiAgICAgICAgaW5wdXTkuI3nlJ/mlYjvvJogIDxlbC1pbnB1dCB2LXNob3c9XCJjaGVja2VkMVwiIHYtbW9kZWw9XCJtc2dcIj48L2VsLWlucHV0PlxuICAgICAgICBzd2l0Y2jlj6/ku6XnlJ/mlYjvvJogPGVsLXN3aXRjaCB2LXNob3c9XCJjaGVja2VkMVwiPjwvZWwtc3dpdGNoPlxuICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY2hlY2tlZDEgPSByZWYoZmFsc2UpXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点击Playground链接可以直接查看效果

### What is Expected?

初始化时v-show的值为false，input控件应该是不显示的

### What is actually happening?

【初始化】时v-show的值为false，但是input控件还是显示出来了

### Additional comments

在示例中还放置了一个`el-switch`作为对比，是正常的，只有`el-input`有问题

**Comment by nova1751** [comment]
<img width="899" alt="image" src="https://github.com/element-plus/element-plus/assets/97817985/435e6dcd-7257-4674-a40e-2c85da257e00">
我这里都不见了呀

**Comment by wangnamin** [comment]
我这里是这样的。
![image](https://github.com/element-plus/element-plus/assets/26314962/88d7a8bf-a38b-4571-aa9e-98df47278059)

**Comment by btea** [comment]
似乎是vue的问题，切换到 3.4.17就可以了。

**Comment by wangnamin** [comment]
> 似乎是vue的问题，切换到 3.4.17就可以了。

vue中使用原生的示例没问题，就是`el-input`不行，还请大神看下如何解决

```html
<script setup>
import { ref } from 'vue'

const msg = ref('Hello World!')
const bool1 = ref(false)
</script>

<template>
  <h1>{{ msg }}</h1>{{bool1}}
  <input v-model="bool1" type="checkbox" />
  <input v-show="bool1" v-model="msg" />
</template>

```

![image](https://github.com/element-plus/element-plus/assets/26314962/53ab00de-8646-4b40-98e8-1cea7690a1c4)

**Comment by chenxch** [comment]
https://github.com/vuejs/core/blob/main/CHANGELOG.md#3418-2024-02-09

**Comment by chenxch** [comment]
@wangnamin 看来3.4.19都还没修复， 考虑降级锁定到3.4.13

**Comment by wangnamin** [comment]
> @wangnamin 看来3.4.19都还没修复， 考虑降级锁定到3.4.15

好的
