### ISSUE TITLE
[Bug Report] Table Column render-header signature description wrong

### ISSUE THREAD

**Issue by luopu** [element-plus/element-plus#1587]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
macOS BigSur & Chrome 89.0

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/magical-hooks-hmyvy?file=/src/tableColumn.vue

### Steps to reproduce
Use a render header function in form of Function(h, { column, $index }) to render a table column header, as document said.

### What is Expected?
That should work to render the table column header correctly.

### What is actually happening?
Got error:
TypeError Cannot read property 'column' of undefined

I believe that render-header should be in form of Function({ column, $index }) as for Vue3 which has changed h as globally imported.

**Comment by justwiner** [comment]
After this `PR` merged, the `h` function is not available now, you can do it like this: 
```js
renderHeader({ column, $index }) {
    return column.label;
},
```

**Comment by schunlee** [comment]
> After this `PR` merged, the `h` function is not available now, you can do it like this:
> 
> ```js
> renderHeader({ column, $index }) {
>     return column.label;
> },
> ```

@justwiner if you want to newline of the label, without h param, now how to add html tag?  ref: https://segmentfault.com/a/1190000015936833
