### ISSUE TITLE
[bug report] tab cannot use value as default tab. V-model must be used

### ISSUE THREAD

**Issue by duanzhichao** [element-plus/element-plus#1588]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
chrome

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/cm2nbxzy/5/

### Steps to reproduce
直接使用value无法默认显示设置的tab

### What is Expected?
修复bug

**Comment by BeADre** [comment]
you should use `model-value`,  this is a documentation error
