### ISSUE TITLE
[tree] [plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/tree-node/style/css" from "dist/assets/el-popper-BpYy968T.js". Does the file exist?

### ISSUE THREAD

**Issue by RubyRose2001** [element-plus/element-plus#15919]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.5.1`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Github Repo](https://github.com/RubyRose2001/authSettings，https://github.com/RubyRose2001/super)

### Steps to reproduce

在authSettings项目中导出3个模块需要在super项目中加载，先yarn install 安装包 先npm run build authSettings工程在通过npm run dev启动项目端口号http://localhost:5173/ 页面地址http://localhost:5173/settings/auth/user
在通过npm run dev 启动super项目http://localhost:5174/ 在sub集合列表中点击b就可以复现

### What is Expected?

希望能够正常加载组件

### What is actually happening?

[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/tree-node/style/css" from "dist/assets/el-popper-BpYy968T.js". Does the file exist?
/Users/mac/Desktop/项目/煤矿/authSettings/dist/assets/el-popper-BpYy968T.js:10:9
8  |  import 'element-plus/es/components/checkbox/style/css';
9  |  import 'element-plus/es/components/collapse-transition/style/css';
10 |  import 'element-plus/es/components/tree-node/style/css';
   |          ^
11 |  const ln=(e,t,{checkForDefaultPrevented:n=!0}={})=>r=>{const a=e?.(r);if(n===!1||!a)return t?.(r)},VD=e=>t=>t.pointerType==="mouse"?e(t):void 0;

### Additional comments

_(empty)_

**Comment by RubyRose2001** [comment]
![Uploading WechatIMG3166.jpg…]()

**Comment by RubyRose2001** [comment]
![WechatIMG3166](https://github.com/element-plus/element-plus/assets/29368840/1ab94211-8c77-4b6d-88e9-5a124d4d177c)

**Comment by RubyRose2001** [comment]
把组件内的el-tree注释掉就没这个问题

**Comment by RubyRose2001** [comment]
ElementPlusResolver()引起的

**Comment by btea** [comment]
@RubyRose2001 Hi, can you provide an accessible reproduction link? The link provided now seems incorrect.

**Comment by RubyRose2001** [comment]
@btea https://github.com/RubyRose2001/authSettings

https://github.com/RubyRose2001/super

**Comment by btea** [comment]
You provided two repository addresses. Do you need to combine the two repository to reproduce? If so, please provide detailed reproduction steps.

**Comment by RubyRose2001** [comment]
@btea 先启动authSettings工程，地址位http://localhost:5173，在启动super项目， 在authSettings打开http://localhost:5173/settings/auth/user页面，然后super项目点击 集合sub下面的b or c

**Comment by btea** [comment]
你提供的 super 启动有问题。
![image](https://github.com/element-plus/element-plus/assets/24516654/ebd11693-838a-4f3c-b51e-6439fa1b67d7)

**Comment by RubyRose2001** [comment]
@btea   home/stores 是另一个工程的包应该不会有影响，能否打开页面，要是打不开我调整下

**Comment by btea** [comment]
可以了，看起来是自动导入组件样式的时候，有些组件不存在对应的样式文件，你可以配置一下`noStylesComponents`，比如 `noStylesComponents: ['ElTreeNode']`。
https://github.com/unplugin/unplugin-vue-components/blob/aeaf51d422da1286a204581ebd9d11d5e8c0361f/src/core/resolvers/element-plus.ts#L40

**Comment by RubyRose2001** [comment]
@btea  好的谢谢 我试试

**Comment by RubyRose2001** [comment]
@btea 你那边在super是否能够正常展示页面 我这边配置了AutoImport({
        resolvers: [
          ElementPlusResolver({
            noStylesComponents: ['ElTreeNode']
          }),
          // IconsResolver({
          //   prefix: 'Icon',
          // }),
        ],
        dts: path.resolve(pathSrc, 'auto-imports.d.ts'),
      }),
      在super中 控制台报错 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/element-plus_es.js?v=9c7a6cb3' does not provide an export named 'ElTreeNode'
      我在项目中使用了el-tree

**Comment by btea** [comment]
添加到这里：
```ts
Components({
  resolvers: [
    // 自动注册图标组件
    IconsResolver({
      enabledCollections: ['ep'],
    }),
    ElementPlusResolver({
      noStylesComponents: ['ElTreeNode']
    }),
 ],
 dts: path.resolve(pathSrc, 'components.d.ts'),
}),
```

**Comment by RubyRose2001** [comment]
还是tree-node/style/css问题
AutoImport({
        resolvers: [
          ElementPlusResolver(),
        ],
        dts: path.resolve(pathSrc, 'auto-imports.d.ts'),
      }),
      Components({
        resolvers: [
          // 自动注册图标组件
          IconsResolver({
            enabledCollections: ['ep'],
          }),
          ElementPlusResolver({
            noStylesComponents: ['ElTreeNode']
          }),
        ],
        dts: path.resolve(pathSrc, 'components.d.ts'),
      }),
   但是把这个删掉就是好的 
   AutoImport({
        resolvers: [
          ElementPlusResolver(),
        ],
    @btea

**Comment by btea** [comment]
我本地创建一个项目使用按需引入，使用了`el-tree`也没问题。你这仓库代码能精简一下吗？现在干扰代码太多，不好确定问题。

**Comment by RubyRose2001** [comment]
@btea 仓库你重新拉一下看看，我在authSettings项目中复制了个treeNode/index.vue 里面就一个tree组件 http://localhost:5173/settings/auth/TreeNode  在打开AutoImpor({ resolvers:[ElementPlusResolver()] })前提下 authSettings打包完 npm run build在super中使用还是会报错 如果注释掉el-tree构建其他内容 在重新上述步骤是没有问题的

**Comment by btea** [comment]
单独启动访问`authSettings`页面，即使使用了`el-tree`也能动态加载。两个项目联动时，会导致报错，看起来似乎和`federation`有关。

**Comment by RubyRose2001** [comment]
@btea 但是报错是一个不存在的elementplus路径，如果在authsettings中把AutoImpor中的ElementPlusResolver()删除掉在重新打包，联动就没问题，虽然联动的时候不需要按需加载，但是还是想解决一下
