### ISSUE TITLE
[Component] [tour, tour-step] tour component issues

### ISSUE THREAD

**Issue by freeman-xv** [element-plus/element-plus#15957]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome 121.0.6167.185`
- Build Tool: `Vite`

### Related Component

- `el-tour`
- `el-tour-step`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBFbEJ1dHRvbiwgRWxUb3VyLCBFbFRvdXJTdGVwIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHR5cGUgeyBCdXR0b25JbnN0YW5jZSwgSW5wdXRJbnN0YW5jZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBidG5SZWYgPSByZWY8QnV0dG9uSW5zdGFuY2U+KClcbmNvbnN0IGlucHV0UmVmID0gcmVmPElucHV0SW5zdGFuY2U+KClcbmNvbnN0IG9wZW4gPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtYnV0dG9uIHJlZj1cImJ0blJlZlwiIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib3BlbiA9IHRydWVcIj5cbiAgICBCZWdpbiBUb3VyXG4gIDwvZWwtYnV0dG9uPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cInZhbHVlXCIgcmVmPVwiaW5wdXRSZWZcIj48L2VsLWlucHV0PlxuXG4gIDxlbC10b3VyIHYtbW9kZWw9XCJvcGVuXCI+XG4gICAgPGVsLXRvdXItc3RlcFxuICAgICAgdGl0bGU9XCJDZW50ZXJcIlxuICAgICAgOnRhcmdldD1cImlucHV0UmVmPy4kZWxcIlxuICAgICAgZGVzY3JpcHRpb249XCJEaXNwbGF5ZWQgaW4gdGhlIGNlbnRlciBvZiBzY3JlZW4uXCJcbiAgICAvPlxuICAgIDxlbC10b3VyLXN0ZXBcbiAgICAgIHRpdGxlPVwiUmlnaHRcIlxuICAgICAgZGVzY3JpcHRpb249XCJPbiB0aGUgcmlnaHQgb2YgdGFyZ2V0LlwiXG4gICAgICBwbGFjZW1lbnQ9XCJyaWdodFwiXG4gICAgICA6dGFyZ2V0PVwiYnRuUmVmPy4kZWxcIlxuICAgIC8+XG4gICAgPGVsLXRvdXItc3RlcFxuICAgICAgdGl0bGU9XCJUb3BcIlxuICAgICAgZGVzY3JpcHRpb249XCJPbiB0aGUgdG9wIG9mIHRhcmdldC5cIlxuICAgICAgcGxhY2VtZW50PVwidG9wXCJcbiAgICAgIDp0YXJnZXQ9XCJidG5SZWY/LiRlbFwiXG4gICAgLz5cbiAgPC9lbC10b3VyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

When the el our step component does not provide a `target` attribute, an error occurs,blocking the page,TypeError: Cannot read properties of null (reading 'contextElement'),This issue does not exist in Element Plus Playground and element plus. org, but it occurs in my environment

### What is Expected?

I hope to have the prompt box centered, error free, and page unobstructed when not passing the `target` attribute

### What is actually happening?

When the target attribute is not passed, an exception will be thrown to block the click on the page

### Additional comments

_(empty)_

**Comment by freeman-xv** [comment]
The link to Element Plus Playground should be this [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiByZWY9XCJidG5SZWZcIiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9wZW4gPSB0cnVlXCI+XG4gICAgQmVnaW4gVG91clxuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtdG91ciB2LW1vZGVsPVwib3BlblwiPlxuICAgIDxlbC10b3VyLXN0ZXBcbiAgICAgIHRpdGxlPVwiQ2VudGVyXCJcbiAgICAgIGRlc2NyaXB0aW9uPVwiRGlzcGxheWVkIGluIHRoZSBjZW50ZXIgb2Ygc2NyZWVuLlwiXG4gICAgLz5cbiAgICA8ZWwtdG91ci1zdGVwXG4gICAgICB0aXRsZT1cIlJpZ2h0XCJcbiAgICAgIGRlc2NyaXB0aW9uPVwiT24gdGhlIHJpZ2h0IG9mIHRhcmdldC5cIlxuICAgICAgcGxhY2VtZW50PVwicmlnaHRcIlxuICAgICAgOnRhcmdldD1cImJ0blJlZj8uJGVsXCJcbiAgICAvPlxuICAgIDxlbC10b3VyLXN0ZXBcbiAgICAgIHRpdGxlPVwiVG9wXCJcbiAgICAgIGRlc2NyaXB0aW9uPVwiT24gdGhlIHRvcCBvZiB0YXJnZXQuXCJcbiAgICAgIHBsYWNlbWVudD1cInRvcFwiXG4gICAgICA6dGFyZ2V0PVwiYnRuUmVmPy4kZWxcIlxuICAgIC8+XG4gIDwvZWwtdG91cj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEJ1dHRvbkluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBidG5SZWYgPSByZWY8QnV0dG9uSW5zdGFuY2U+KClcblxuY29uc3Qgb3BlbiA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by Fuphoenixes** [comment]
Unable to reproduce, please provide a minimal case that can be reproduced

**Comment by freeman-xv** [comment]
https://github.com/freeman-xv/element-bug-demo.git 
I have created a project, you can try to get it running.
When I click the` Begin Tour` button, the console will report an error. And clicking the `next` button again did not respond.

**Comment by freeman-xv** [comment]
> Unable to reproduce, please provide a minimal case that can be reproduced

https://github.com/freeman-xv/element-bug-demo.git
I have created a project, you can try to get it running.
When I click the Begin Tour button, the console will report an error. And clicking the next button again did not respond.

**Comment by Fuphoenixes** [comment]
This is caused by the @floating-ui/dom version upgrade. You can roll back @floating-ui/dom in your project to version 1.0.1 to temporarily solve it. 
`npm install @floating-ui/dom@1.0.1`

**Comment by freeman-xv** [comment]
> This is caused by the @floating-ui/dom version upgrade. You can roll back @floating-ui/dom in your project to version 1.0.1 to temporarily solve it. `npm install @floating-ui/dom@1.0.1`
The problem has been solved, thank you very much
