### ISSUE TITLE
[Style] [drawer, dialog] The z-index with dialog and drawer open at the same time does not behave as expected.

### ISSUE THREAD

**Issue by wuhaohuang** [element-plus/element-plus#15954]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvdXRlclZpc2libGUgPSB0cnVlXCI+XG4gICAgT3BlbiB0aGUgb3V0ZXIgRGlhbG9nXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1kcmF3ZXJcbiAgICB2LW1vZGVsPVwiaW5uZXJWaXNpYmxlMVwiXG4gICAgY2xhc3M9XCJjdXMtZHJhd2VyLW1hdGVyaWFsXCJcbiAgICA6d2l0aC1oZWFkZXI9XCJmYWxzZVwiXG4gICAgc2l6ZT1cIjUwJVwiXG4gICAgOmNsb3NlLW9uLWNsaWNrLW1vZGFsPVwiZmFsc2VcIlxuICAgIDpjbG9zZS1vbi1wcmVzcy1lc2NhcGU9XCJmYWxzZVwiXG4gICAgOmFwcGVuZC10by1ib2R5PVwidHJ1ZVwiXG4gID5cbiAgICA8ZGl2PjExMTExPC9kaXY+XG4gIDwvZWwtZHJhd2VyPlxuXG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cIm91dGVyVmlzaWJsZVwiIDphcHBlbmQtdG8tYm9keT1cInRydWVcIiB0aXRsZT1cIk91dGVyIERpYWxvZ1wiIHdpZHRoPVwiODAwXCI+XG4gICAgPHNwYW4+VGhpcyBpcyB0aGUgb3V0ZXIgRGlhbG9nPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPGRpdiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvdXRlclZpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiaW5uZXJWaXNpYmxlMSA9IHRydWVcIj5cbiAgICAgICAgICBPcGVuIHRoZSBpbm5lciBEaWFsb2dcbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG91dGVyVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGlubmVyVmlzaWJsZTEgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

When version 2.5.1 is selected, it is as expected. When version greater than 2.5.1 is selected, the drawer appears below the dialog.

### What is Expected?

Place the mask layer on top in order of clicks.

### What is actually happening?

The drawer mask layer clicked later appears below the dialog.

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
fixed #15900
