### ISSUE TITLE
[Bug Report] How to not allow selected items to be removed in a multiple select if condition is not true.(do not remove tag from select if condition is false)

### ISSUE THREAD

**Issue by thamibn** [element-plus/element-plus#1595]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
windows 10

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ckplp?file=/src/App.vue

### Steps to reproduce
1. Create a select with a @change or @remove-tag events and try to not remove a tag if condition is not true.

### What is Expected?
1. it should allow me to stop the process if the condition was not met

### What is actually happening?
1. it contiunues to remove the tag.

**Comment by JeremyWuuuuu** [comment]
Closing due to #1605
