### ISSUE TITLE
[Component] [tree-select] tree-select的远程搜索方法不执行

### ISSUE THREAD

**Issue by elem0504** [element-plus/element-plus#15965]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.3.9`
- Browser / OS: `edge/windows11`
- Build Tool: `Vue CLI`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2YWx1ZURhdGEgPSByZWYoJycpXG5jb25zdCBwcm9wcyA9IHtcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBpc0xlYWY6ICdpc0xlYWYnLFxufVxuY29uc3Qgc291cmNlRGF0YSA9IFtcbiAge1xuICAgIHZhbHVlOiAnMScsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMS0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbmNvbnN0IHJlbW90ZU1ldGhvZHMgPSAocXVlcnkpID0+IHtcbiAgICAgIEVsTWVzc2FnZS53YXJuaW5nKCfmiJHmiafooYzkuoYhIScpXG4gICAgfVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWUtc2VsZWN0XG4gICAgICAgICAgICAgICAgICB2LW1vZGVsPVwidmFsdWVEYXRhXCJcbiAgICAgICAgICAgICAgICAgIDpkYXRhPVwic291cmNlRGF0YVwiXG4gICAgICAgICAgICAgICAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgICAgICAgICAgICAgICA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCJcbiAgICAgICAgICAgICAgICAgIGNoZWNrLXN0cmljdGx5XG4gICAgICAgICAgICAgICAgICA6cmVtb3RlLW1ldGhvZD1cInJlbW90ZU1ldGhvZHNcIlxuICAgICAgICAgICAgICAgICAgcmVtb3RlLXNob3ctc3VmZml4XG4gICAgICAgICAgICAgICAgICBhdXRvbWF0aWMtZHJvcGRvd25cbiAgICAgICAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgICAgICAgICAgZml0LWlucHV0LXdpZHRoXG4gICAgICAgICAgICAgICAgICByZW1vdGVcbiAgICAgICAgICAgICAgICAgIHJlc2VydmUta2V5d29yZFxuICAgICAgICAgICAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICAgICAgICAvPlxuICAgICAgICAgICAgICA8cD5yZW1vdGVNZXRob2Rz6L+Z5Liq5pa55rOV5LiN6KKr5omn6KGMPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

el-tree-select,开启远程搜索后,不会执行远程搜索方法

### What is Expected?

远程搜索

### What is actually happening?

方法不执行

### Additional comments

_(empty)_

**Comment by ccs-song** [comment]
<img width="698" alt="image" src="https://github.com/element-plus/element-plus/assets/52770276/31721dc7-ec43-481b-802d-404326ee66e7">
tree-select会补充filterMethod方法，就导致不会执行remoteMethod了

**Comment by kooriookami** [comment]
@yujinpan Could you look at this problem?

**Comment by yujinpan** [comment]
> @yujinpan Could you look at this problem?

OK
