### ISSUE TITLE
[Component] [select-v2] [Component] [el-select-v2] 当可筛选过滤且多选时，直接给value赋值会出现映射异常

### ISSUE THREAD

**Issue by ZywO1** [element-plus/element-plus#15973]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxwPnVzZSBjb2xsYXBzZS10YWdzLXRvb2x0aXA8L3A+XG4gICAgPGVsLXNlbGVjdC12MiB2LW1vZGVsPVwidmFsdWUyXCIgOm9wdGlvbnM9XCJvcHRpb25zXCIgY2xlYXJhYmxlIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCIgbXVsdGlwbGUgZmlsdGVyYWJsZVxuICAgICAgY29sbGFwc2UtdGFncyBjb2xsYXBzZS10YWdzLXRvb2x0aXAgQGNoYW5nZT1cImNoYW5nZVwiPlxuXG4gICAgICA8dGVtcGxhdGUgI2hlYWRlcj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VWYWx1ZVwiPlxuICAgICAgICAgIHRlc3RcbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtc2VsZWN0LXYyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZTIgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24gJHtpZHggKyAxfWAsXG4gIGxhYmVsOiBgdGVzdCR7aWR4fWAsXG59KSlcblxuY29uc3QgY2hhbmdlID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyh2YWx1ZTIudmFsdWUpXG59XG5cbmNvbnN0IGNoYW5nZVZhbHVlID0gKCk9PntcbiAgdmFsdWUyLnZhbHVlPVsnT3B0aW9uIDEnLCdPcHRpb24gMiddXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

当直接点击下拉框里的按钮，映射正常。
复现步骤：
1、清空下拉框，然后选择test0,test1,test2
2、下拉框输入100，此时过滤后选项只剩下test100
3、直接点击按钮
或者下拉框直接输入100（即不展示出test1以及test2即可），点击button，同样复现

### What is Expected?

select的tags以及 collapse-tags-tooltip
展示为 test0，test1 ，即映射options下拉列表的value

### What is actually happening?

展示Options 1，Options 2，即直接展示的是value

### Additional comments

当filterOptions不为allOptions时，直接给value赋予 allOptions存在而filteredOptions不存在的值时，tags的展示会出现问题，无法映射到对应的label。

**Comment by huangjw1997** [comment]
selectV2绑定值发生变化时 设置选中项目前确实是从filteredOptionsValueMap查找的，所以在过滤下设置选中确实会有如上问题
![屏幕截图 2024-02-28 093537](https://github.com/element-plus/element-plus/assets/159113473/819208aa-3517-4887-b256-501914dc16d8)
