### ISSUE TITLE
[Component] [image] el-image 忽视了max-height请求

### ISSUE THREAD

**Issue by varhuman** [element-plus/element-plus#15979]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.6`
- Browser / OS: `"Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"`
- Build Tool: `Nuxt`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWltYWdlXG4gIHNyYz1cImh0dHBzOi8vYy1zZWNvbmRoYW5kLm9zcy1jbi1ndWFuZ3pob3UuYWxpeXVuY3MuY29tLzIwMjQwMjI4L2ZkZDRlODE2NjhkMDZjMTQ3MzVjYmNhNDBhNjc4NzkyLmpwZ1wiXG4gIHN0eWxlPVwibWF4LWhlaWdodDogMzAwcHg7XCJcbiAgZml0PVwiY29udGFpblwiLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

nothing

### What is Expected?

max-height和fit应该共同约束让他变成完全显示的状态

### What is actually happening?

可是我们看到el-image-inner的height不受el-image的maxheight的控制，导致图片无论如何都无法完全显示

### Additional comments

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as epVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

</script>

<template>
  <el-image
  src="https://c-secondhand.oss-cn-guangzhou.aliyuncs.com/20240228/fdd4e81668d06c14735cbca40a678792.jpg"
  style="max-height: 300px;"
  fit="contain"/>
</template>

**Comment by huangjw1997** [comment]
子级img无法继承父级的max-height，展示自己的height，所以失效。要么设置maxHeight时 源码也需要在el-image-inner上设置，才能同步生效
![屏幕截图 2024-02-28 113325](https://github.com/element-plus/element-plus/assets/159113473/1448a65d-b4ad-4f98-806e-7477faf5fe96)

**Comment by varhuman** [comment]
> 子级img无法继承父级的max-height，只展示自己的height，加上父级的overflow：hidden，导致失效。所以要么设置maxHeight时 源码也需要在el-image-inner上设置，才能同步生效 ![屏幕截图 2024-02-28 113325](https://private-user-images.githubusercontent.com/159113473/308409757-1448a65d-b4ad-4f98-806e-7477faf5fe96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjI5NzQsIm5iZiI6MTcwOTEyMjY3NCwicGF0aCI6Ii8xNTkxMTM0NzMvMzA4NDA5NzU3LTE0NDhhNjVkLWI0YWQtNGY5OC04MDZlLTc0NzdmYWY1ZmU5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMjE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2YxMThhMTE0YjQxYzAyNTEzNGIxYzJkNWVkYTRmMGYxYTdiYzNmZmEyNDMzNDQyOGJhOTQ2YWUxYjY3MDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OIRektttiZ9EfzJjkmucivMuWEI28eJxbTgiNrPLoWw)

原来如此，看样子算是前端常识问题不足，感谢~
