### ISSUE TITLE
[bug report] small attribute of pagination component

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1597]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
Microsoft Edge 版本 88.0.705.81 (官方内部版本) (64 位)

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/sorrowx/pen/eYBPQGW?editors=1111

### Steps to reproduce
1.打开 https://codepen.io/sorrowx/pen/eYBPQGW?editors=1111
2. 看效果

### What is Expected?
1.期望ui统一变小
<img width="522" alt="WechatIMG12038" src="https://user-images.githubusercontent.com/20411966/110413488-eba1dc00-80c8-11eb-974a-253771d9b693.png">
![WechatIMG12040](https://user-images.githubusercontent.com/20411966/110413494-f0669000-80c8-11eb-9e4b-d23ecbad3b6e.jpeg)

### What is actually happening?
1. select组件的ui没有变化
![image](https://user-images.githubusercontent.com/20411966/110413557-08d6aa80-80c9-11eb-9918-8975b6c6de42.png)
![image](https://user-images.githubusercontent.com/20411966/110413574-11c77c00-80c9-11eb-90d8-6407c7823f32.png)

问题原因及解决方法(仅供参考)

问题:在sizes.vue组件中, el-select组件除了使用size="mini"，没有其他任何处理逻辑,el-select组件的最小ui的line-height和height为28px,所以效果就这样了。

解决方案：
方案一：el-select原子组件内部修改，感觉不太可能，估计你们产品当初设计时当size为mini时高度和行高应该是28px。

方案二:  让用户使用时，自己编写样式覆盖。(这么说，那我提的就不是个bug)

方案三: 
我在packages/theme-chalk/src/pagination.scss下编写相关的css样式,来覆盖el-select组件下的样式

如果觉得是问题，也觉得方案三行的话，就让我提个pr试试

**Comment by JeremyWuuuuu** [comment]
Closing due to #1598
