### ISSUE TITLE
[i18n] [message-box] 在全局设置 namespace 的情况下，部分组件的国际化不正确

### ISSUE THREAD

**Issue by brign123** [element-plus/element-plus#15982]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.4.20`
- Element Plus Version: `2.5.6`
- Browser / OS: ` Chrome/122.0.0.0`
- Build Tool: `Other`

### Related Component

- `el-message-box`

### Reproduction Link

[CodePen](https://codepen.io/brign123/pen/poBzazG)

### Steps to reproduce

点击 `Switch Language` 切换语言，可以看到 `el-table` 中的提示文字语言会改变。
点击 `test` 可以看到 `message-box` 的语言一直是英文。
> 如果删除 `app.use(ElementPlus,{ namespace: 'el' });` 中的 `namespace` 配置，一切就会变得正常。

### What is Expected?

`message-box` 的语言跟配置的一致。

### What is actually happening?

`message-box` 的语言跟配置的不一致。

### Additional comments

因为只在 `config-provider` 组件中配置 `namespace` 的话，会导致部分直接引入的 `ElMessage` 等组件的样式还是 `el-`，所以在全局配置了 `namespace`，然后发现了这个问题，希望能帮忙看一下，谢谢。

**Comment by Jesseszhang** [comment]
需要在main.ts 引入  ` import 'element-plus/theme-chalk/src/message.css'    import 'element-plus/theme-chalk/src/message-box.css' `  对应的样式才可以

**Comment by brign123** [comment]
@zeyongTsai 
感谢回复，其实现在的疑惑是我在注册`ElemengPlus`的时候，如果提供了`namespace`属性，没有提供`local`，MessageBox 无法拿到正确的 local 配置，但是如果直接`app.use(ElementPlus)`，既什么配置都不提供的情况下，MessageBox 又可以正确的国际化。
看上去像是只要注册`ElemengPlus`提供了某个配置项，其余的全局配置都会使用默认值？

**Comment by zeyongTsai** [comment]
@brign123  请重新理解一下我括号里面的描述，源码里面配置分：全局（组件库安装）、局部（使用config-provider）。 如果没提供全局配置，则初次使用的局部配置（第一个被初始化的 config-provier 组件的属性）也会成为全局配置。

**Comment by brign123** [comment]
@zeyongTsai  我理解您说的意思，我的问题是现在配置似乎是一个整体。比如我注册的时候是`app.use(ElementPlus,{namespace:'el'})`，没有提供 local 属性。然后我 config-provier 组件的 local 设置为 zh-cn，在这种情况下，MessageBox 是英文的，第一个被初始化的 config-provier 组件的属性即 local 并没有成为全局配置。

**Comment by zeyongTsai** [comment]
@brign123  因为它们不会被 merge。而命令式 的 message-box 使用的是全局的配置。
