### ISSUE TITLE
[Component] [tooltip] el-tooltip button no keyboard control possible

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#15998]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdG9nZ2xlID0gcmVmKGZhbHNlKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwidG9nZ2xlID0gIXRvZ2dsZVwiPnRyeSB0b2dnbGUgdmlhIGtleWJvYXJkICh3b3Jrcyk8L2J1dHRvbj5cbiAgJm5ic3A7XG4gIDxlbC10b29sdGlwIGNvbnRlbnQ9XCJoZWxsb1wiPlxuICAgIDxidXR0b24gQGNsaWNrPVwidG9nZ2xlID0gIXRvZ2dsZVwiPnRyeSB0b2dnbGUgdmlhIGtleWJvYXJkIChkb2VzIG5vdCB3b3JrLCBiZWNhdXNlIG9mIHRvb2x0aXApPC9idXR0b24+XG4gIDwvZWwtdG9vbHRpcD5cblxuICA8aHIgc3R5bGU9XCJtYXJnaW4tYm90dG9tOiAxMDBweFwiIC8+XG4gIFRvZ2dsZToge3sgdG9nZ2xlIH19XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

See the playground example.

Clicking a button works as usual, but for keyboard users the @click event is not triggered when the button is wrapped inside an el-tooltip component.

### What is Expected?

Click event should also be triggerable via keyboard as usual.

### What is actually happening?

No event is emitted via keyboard, unless you add @keydown.space @keydown.enter manually.

### Additional comments

Might be related to https://github.com/element-plus/element-plus/issues/8375

**Comment by ZTrainWilliams** [comment]
trigger-keys
description:  When you click the mouse to focus on the trigger element, you can define a set of keyboard codes to control the display of tooltip through the keyboard 
default: [EVENT_CODE.enter, EVENT_CODE.space]

if you want to contorl, you can set :trigger-keys="[]"

**Comment by plehnen** [comment]
@ZTrainWilliams thanks for the hint!
