### ISSUE TITLE
[Component] [form, dialog] el-form 的 restFileds 无法生效问题

### ISSUE THREAD

**Issue by herzorf** [element-plus/element-plus#15991]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome 121.0.6167.184`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gdHJ1ZVwiPlxuICAg5paw5aKeXG4gIDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gcGxhaW4gQGNsaWNrPVwiZWRpdFwiPlxuICAg57yW6L6RXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1kaWFsb2cgQGNsb3NlPVwiY2xvc2UoZm9ybVJlZilcIiB2LW1vZGVsPVwiZGlhbG9nRm9ybVZpc2libGVcIiB0aXRsZT1cIlNoaXBwaW5nIGFkZHJlc3NcIiB3aWR0aD1cIjUwMFwiPlxuICAgIDxlbC1mb3JtIHJlZj1cImZvcm1SZWZcIiA6bW9kZWw9XCJmb3JtXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUHJvbW90aW9uIG5hbWVcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8ZGl2IGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gZmFsc2VcIj5cbiAgICAgICAgICBDb25maXJtXG4gICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJztcbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGZvcm1SZWYgPSByZWYoKVxuY29uc3QgZGlhbG9nRm9ybVZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBmb3JtTGFiZWxXaWR0aCA9ICcxNDBweCdcbmNvbnN0IGVkaXQgPSAoKT0+IHtcbiAgICBmb3JtLm5hbWUgPSBcInh4eFwiXG4gICAgZGlhbG9nRm9ybVZpc2libGUudmFsdWUgPSB0cnVlXG59XG5jb25zdCBjbG9zZSAgPSAoZm9ybVJlZjpGb3JtSW5zdGFuY2UpPT57XG5jb25zb2xlLmxvZygxKVxuICBmb3JtUmVmLnJlc2V0RmllbGRzKClcbn1cbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7XG4gIG5hbWU6ICcnLFxufSlcblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击新增和编辑可对dialog中的form进行操作，如果点击编辑则会通过edit函数对dialog中的form的表单数据进行回显，关闭dialog后会调用close函数重置表单数据。

### What is Expected?

当点击编辑，对表单数据进行回显后，关闭表单，表单数据被重置，再次点击新增后表单数据应该为空

### What is actually happening?

当点击编辑，表单数据回显后再次点新增，表单数据仍未被重置

### Additional comments

resetFileds函数是重置为当前表单所绑定的数据，还是重置为初始化时的表单数据。

**Comment by ZTrainWilliams** [comment]
你需要在el-form-item中添加prop，如palyground中的案例，你需要添加prop=“name”

**Comment by btea** [comment]
@herzorf Hello, thank you for your feedback. The correct configuration should be as @ZTrainWilliams  said, so I will close this issue.

If you have other questions, you can continue to comment below.
