### ISSUE TITLE
[Component] [dialog] 当Dialog的内容高度超过页面高度，且该Dialog加上draggable属性时，点击header部分开始拖拽，产生的样式bug

### ISSUE THREAD

**Issue by amo022** [element-plus/element-plus#15993]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.6`
- Browser / OS: `chrome 121.0.6167.184 / macOS 14.2.1 (23C71)`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/dialog.html)

### Steps to reproduce

1.在可拖拽对话框下，点击“ Open a draggable Dialog ”按钮
2.打开F12控制台，将内容部分一直复制粘贴，直至内容部分高度超出页面高度，即整个弹窗高度大于页面高度
3.此时点击header处进行拖拽，则bug出现

### What is Expected?

期望弹窗高度超过页面的Dialog组件，拖拽同其他小Dialog组件一样正常。

### What is actually happening?

点击header处进行拖拽后，弹窗会自动上移，弹窗底部会贴在页面最底部。但由于整个弹窗高度超过页面高度，导致header部分在屏幕上方，点击不到，就无法进行拖拽。

### Additional comments

经排查，draggable 属性给 “div.is-draggabl” 元素加上了 transform: translate(0, 0) 的样式，但高度超出页面高度的弹窗，加上的 translate 并不是 (0, 0)

![image](https://github.com/element-plus/element-plus/assets/30771431/24977c22-a982-46d4-a74f-a147d418a308)

**Comment by kooriookami** [comment]
请添加 `overflow` 属性，这就是为了处理此情况加入的属性。

**Comment by amo022** [comment]
> 请添加 `overflow` 属性，这就是为了处理此情况加入的属性。点击 Open a overflow draggable Dialog 按钮可以查看案例。

好的，是我蠢了= =，升个版本，再加 overflow 确实解决了问题，3Q！
