### ISSUE TITLE
 [Component] [Select] 当el-select中v-model绑定的值为空字符串时 匹配不上el-option中的value

### ISSUE THREAD

**Issue by pengdragon** [element-plus/element-plus#15994]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome 122.0.6261.95 / window10`
- Build Tool: `Webpack`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT4gIFxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiPiAgXG4gICAgPGVsLW9wdGlvbiAgXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiICBcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCIgIFxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiICBcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIiAgXG4gICAgPjwvZWwtb3B0aW9uPiAgXG4gIDwvZWwtc2VsZWN0PiAgXG48L3RlbXBsYXRlPiAgXG4gIFxuPHNjcmlwdCBzZXR1cD4gIFxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJzsgIFxuICBcbi8vIOS9v+eUqCByZWYg5Yib5bu65ZON5bqU5byP5Y+Y6YePICBcbmNvbnN0IHZhbHVlID0gcmVmKCcnKTsgIFxuICBcbi8vIG9wdGlvbnMg5piv5LiA5Liq5bi46YeP5pWw57uE77yM5LiN6ZyA6KaB5L2/55SoIHJlZiAgXG5jb25zdCBvcHRpb25zID0gWyAgXG4gIHsgdmFsdWU6ICcnLCBsYWJlbDogJ+WFqOmDqCcgfSwgIFxuICB7IHZhbHVlOiAnT3B0aW9uMScsIGxhYmVsOiAnT3B0aW9uMScgfSwgIFxuICB7IHZhbHVlOiAnT3B0aW9uMicsIGxhYmVsOiAnT3B0aW9uMicgfSwgIFxuXTsgIFxuPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<template>  
  <el-select v-model="value">  
    <el-option  
      v-for="item in options"  
      :key="item.value"  
      :label="item.label"  
      :value="item.value"  
    ></el-option>  
  </el-select>  
</template>  
  
<script setup>  
import { ref } from 'vue';  
  
// 使用 ref 创建响应式变量  
const value = ref('');  
  
// options 是一个常量数组，不需要使用 ref  
const options = [  
  { value: '', label: '全部' },  
  { value: 'Option1', label: 'Option1' },  
  { value: 'Option2', label: 'Option2' },  
];  
</script>

### What is Expected?

初始展示全部

### What is actually happening?

匹配不了任何一项

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
空字符串会被当成是空值，不匹配选项。

**Comment by pengdragon** [comment]
不匹配选项感觉不太合理哦 2.4版本的可以匹配 没有见着版本升级说把这个规则重新定义

**Comment by kooriookami** [comment]
我提了一个PR，动态分辨是否匹配空字符串

**Comment by pengdragon** [comment]
感谢
