### ISSUE TITLE
[Component] [button] 按钮点击后焦点不能自动去掉

### ISSUE THREAD

**Issue by romypan** [element-plus/element-plus#16001]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.5.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/button.html#%E6%96%87%E5%AD%97%E6%8C%89%E9%92%AE)

### Steps to reproduce

按钮点击后

### What is Expected?

焦点失去

### What is actually happening?

焦点仍然存在

### Additional comments

_(empty)_

**Comment by lazyyumin** [comment]
怎么又是这个问题，我建议提问之间还是先搜一下历史issue吧，按钮点击之后焦点仍然存在是el做的a11y，同时也是w3c的标准，如果你想去掉完全可以使用自定义指令完成。[#12221 ](https://github.com/element-plus/element-plus/issues/12221)
