### ISSUE TITLE
[Bug Report] Tabs component :model-value bug

### ISSUE THREAD

**Issue by BeADre** [element-plus/element-plus#1600]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
macos / chrome

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/BeADre/0fgqtz4x/2/

### Steps to reproduce
switch tab-item

### What is Expected?
tab-item can't be switched

### What is actually happening?
tab-item can switch

**Comment by JeremyWuuuuu** [comment]
Clicking on the tab seems working fine.


https://user-images.githubusercontent.com/15975785/110631485-88f03380-81e1-11eb-8674-01fbd8d8dba3.mov

**Comment by BeADre** [comment]
@JeremyWuuuuu 是这样的  当我用v-bind绑定值的时候 我认为在这个值未更改的时候界面应该不应该发生改变 这个例子中我绑定的value值并未发生更改  所以我认为界面的改变是不对的 emmmmm  不知道我的理解是否正确

**Comment by bastarder** [comment]
> @JeremyWuuuuu 是这样的 当我用v-bind绑定值的时候 我认为在这个值未更改的时候界面不应该发生改变 这个例子中我绑定的value值并未发生更改 所以我认为界面的改变是不对的 emmmmm 不知道我的理解是否正确

i think you should add `disabled` on tab-pane

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
