### ISSUE TITLE
[Component] [select] Select 选择器的 el-option 标签不使用v-for列表渲染时，会只有一个选项

### ISSUE THREAD

**Issue by z184924** [element-plus/element-plus#16008]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.5.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.160`
- Build Tool: `Other`

### Related Component

- `el-select`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/spbyndzj/1/)

### Steps to reproduce

select1可以正常渲染出Option1、2、3，但select2只有Option6，缺少了4和5。

### What is Expected?

select2能渲染出Option4、5、6

### What is actually happening?

select2只能渲染出Option6

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/32642280/fe464e84-539d-4d0e-b60a-6e6252dcf131)

![image](https://github.com/element-plus/element-plus/assets/32642280/8483208c-3724-48d8-82b3-c872515a9f21)

**Comment by ljf1834** [comment]
根据你给出的demo，判断是Vue再编译template时没能正确的编译出没有结束标记`<el-option />`, 将`<el-option />`改写为完整的写法`<el-option></el-option>`可以解决！
这应该是Vue的一个compiler sfc的bug

**Comment by z184924** [comment]
感谢提供解决方案，确实换用<el-option></el-option>写法正常了~
