### ISSUE TITLE
[Component] [pagination] Elpagination的提示

### ISSUE THREAD

**Issue by kunkunInCn** [element-plus/element-plus#16012]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.5.3`
- Browser / OS: `Google Chrome121.0.6167.140`
- Build Tool: `Nuxt`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPCEtLSA8aDQ+e3sgbGlzdCB9fTwvaDQ+IC0tPlxuICA8ZGl2IGNsYXNzPVwicGFnaW5hdGlvblwiPlxuICAgIDxlbC1wYWdpbmF0aW9uIHYtbW9kZWw6Y3VycmVudC1wYWdlPVwiY3VycmVudFBhZ2VcIiB2LW1vZGVsOnBhZ2Utc2l6ZT1cInBhZ2VTaXplXCIgOnBhZ2Utc2l6ZXM9XCJbOCwgMTIsIDE2XVwiXG4gICAgICA6YmFja2dyb3VuZD1cInRydWVcIiBsYXlvdXQ9XCJ0b3RhbCwganVtcGVyLCBzaXplcywgcHJldiwgcGFnZXIsIG5leHRcIiA6dG90YWw9XCJ0b3RhbFwiIEBzaXplLWNoYW5nZT1cImhhbmRsZVNpemVDaGFuZ2VcIlxuICAgICAgQGN1cnJlbnQtY2hhbmdlPVwiaGFuZGxlQ3VycmVudENoYW5nZVwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4vLyBjb25zdCByZXMgPSBhd2FpdCB1c2VBc3luY0RhdGEoJ3N0dWR5JywgKCkgPT4gJGZldGNoKCdodHRwOi8vbG9jYWxob3N0OjMwODIvc3R1ZHkvbm90ZScpKVxuLy8gY29uc3QgbGlzdCA9IHJlZihyZXMpXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB0b3RhbCA9IHJlZigpO1xuY29uc3QgY3VycmVudFBhZ2UgPSByZWYoKTtcbmNvbnN0IHBhZ2VTaXplID0gcmVmKCk7XG5mdW5jdGlvbiBoYW5kbGVTaXplQ2hhbmdlKCkgeyB9XG5mdW5jdGlvbiBoYW5kbGVDdXJyZW50Q2hhbmdlKCkgeyB9XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQgbGFuZz1cImxlc3NcIj48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-pagination的正常使用

### What is Expected?

正常使用

### What is actually happening?

控制台有提醒:ElementPlusError: [ElPagination] 你使用了一些已被废弃的用法，请参考 el-pagination 的官方文档

### Additional comments

_(empty)_

**Comment by btea** [comment]
@kunkunInCn `total` should be set to a number, now it is `undefined`.

You can set it as follows:
```ts
const total = ref(0)
```

**Comment by kunkunInCn** [comment]
> @kunkunInCn `total` should be set to a number, now it is `undefined`.
> 
> You can set it as follows:
> 
> ```ts
> const total = ref(0)
> ```

you are right  ,  its usefil

**Comment by kunkunInCn** [comment]
> @kunkunInCn `total` should be set to a number, now it is `undefined`.
> 
> You can set it as follows:
> 
> ```ts
> const total = ref(0)
> ```

you are right  ,  its usefil
