### ISSUE TITLE
[Component] [dialog] <style scoped> 对ElDialog 不生效

### ISSUE THREAD

**Issue by trcat** [element-plus/element-plus#16028]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gdHJ1ZVwiPlxuICAgIENsaWNrIHRvIG9wZW4gdGhlIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCI1MDBcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gICAgY2xhc3M9XCJkaWFsb2dcIlxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyBhIG1lc3NhZ2U8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8ZGl2IGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+XG4gICAgICAgICAgQ29uZmlybVxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcblxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoZG9uZSkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybSgnQXJlIHlvdSBzdXJlIHRvIGNsb3NlIHRoaXMgZGlhbG9nPycpXG4gICAgLnRoZW4oKCkgPT4ge1xuICAgICAgZG9uZSgpXG4gICAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgICAgLy8gY2F0Y2ggZXJyb3JcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nIHtcbiAgYmFja2dyb3VuZDogcmVkO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 复制官网Dialog示例代码
2. 设置 style scoped 样式，并将对应类名加到 Dialog 上

### What is Expected?

在 Dialog 上的类名样式生效

### What is actually happening?

在 Dialog 上的类名样式未生效，也没有看到有因 style scoped 而生产的自定义属性

### Additional comments

我不知道这个是 Element UI的问题，还是 Vue Cli 的问题

![image](https://github.com/element-plus/element-plus/assets/23648263/bccce276-6e75-414d-b10d-241a326b213b)

**Comment by huangjw1997** [comment]
不是 Element UI的问题，请去掉scoped，不然样式不会生效

**Comment by trcat** [comment]
> 不是 Element UI的问题，请去掉scoped，不然样式不会生效

但是 Vue2 版本的没有这个问题，查看了视作缺失也没什么问题，感觉可能和 vue cli 或 vue 有关

**Comment by huangjw1997** [comment]
> > 不是 Element UI的问题，请去掉scoped，不然样式不会生效
> 
> 但是 Vue2 版本的没有这个问题，查看源码确实也没什么问题，感觉可能和 vue cli 或 vue 有关

这算CSS作用域的问题吧

**Comment by trcat** [comment]
> > > 不是 Element UI的问题，请去掉scoped，不然样式不会生效
> > 
> > 
> > 但是 Vue2 版本的没有这个问题，查看源码确实也没什么问题，感觉可能和 vue cli 或 vue 有关
> 
> 这算CSS作用域的问题吧

是啊，ElDialg 结构上没有出现自定义属性，所以样式没有生效。这个现象应该是不符合预期的吧

**Comment by kaine0923** [comment]
具体原因参见 #10515

**Comment by plainheart** [comment]
这种情况一般建议使用全局样式，或者先获取到当前组件的 scopeId 然后手动绑定至需要使用的组件上。参见这个[例子](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gdHJ1ZVwiPlxuICAgIENsaWNrIHRvIG9wZW4gdGhlIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCI1MDBcIlxuICAgIGNsYXNzPVwiZGlhbG9nXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICAgIHYtYmluZD1cInsgW3Njb3BlSWRdOiAnJyB9XCJcbiAgPlxuICAgIDxzcGFuPlRoaXMgaXMgYSBtZXNzYWdlPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPGRpdiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPlxuICAgICAgICAgIENvbmZpcm1cbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSAgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmUpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oJ0FyZSB5b3Ugc3VyZSB0byBjbG9zZSB0aGlzIGRpYWxvZz8nKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIGRvbmUoKVxuICAgIH0pXG4gICAgLmNhdGNoKCgpID0+IHtcbiAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgfSlcbn1cblxuY29uc3Qgc2NvcGVJZCA9IGdldEN1cnJlbnRJbnN0YW5jZSgpLnR5cGUuX19zY29wZUlkXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5kaWFsb2cge1xuICBiYWNrZ3JvdW5kOiByZWQ7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)。

如需多处使用，可以考虑如下封装一个工具函数，在需要的地方 import 然后使用 v-bind 绑定至组件元素上。
```js
export const useScopeId = () => {
  const instance = getCurrentInstance()
  return instance && instance.type.__scopeId
}
```
