### ISSUE TITLE
[Component] [transfer] Transfer 穿梭框 警告 el-check 使用了label 打印警告 label act as value is about to be deprecated in version 3.0.0

### ISSUE THREAD

**Issue by Memory1998** [element-plus/element-plus#16030]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.6.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-transfer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5pbnRlcmZhY2UgT3B0aW9uIHtcbiAgdmFsdWU6IG51bWJlclxuICBkZXNjOiBzdHJpbmdcbiAgZGlzYWJsZWQ6IGJvb2xlYW5cbn1cblxuY29uc3QgZ2VuZXJhdGVEYXRhID0gKCkgPT4ge1xuICBjb25zdCBkYXRhOiBPcHRpb25bXSA9IFtdXG4gIGZvciAobGV0IGkgPSAxOyBpIDw9IDE1OyBpKyspIHtcbiAgICBkYXRhLnB1c2goe1xuICAgICAgdmFsdWU6IGksXG4gICAgICBkZXNjOiBgT3B0aW9uICR7aX1gLFxuICAgICAgZGlzYWJsZWQ6IGkgJSA0ID09PSAwLFxuICAgIH0pXG4gIH1cbiAgcmV0dXJuIGRhdGFcbn1cblxuY29uc3QgZGF0YSA9IHJlZjxPcHRpb25bXT4oZ2VuZXJhdGVEYXRhKCkpXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuXG4gIFxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

随意引入一个穿梭框组建后会控制台会打印警告

### What is Expected?

https://github.com/element-plus/element-plus/blob/dev/packages/components/transfer/src/transfer-panel.vue     将      :label="item[propsAlias.key]" 修改为           :value="item[propsAlias.key]"

### What is actually happening?

https://github.com/element-plus/element-plus/blob/dev/packages/components/transfer/src/transfer-panel.vue     将      :label="item[propsAlias.key]" 修改为           :value="item[propsAlias.key]"

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/36466449/f73c927a-5aae-4d69-98a1-98a215696b08)

![image](https://github.com/element-plus/element-plus/assets/36466449/8bf5f2a7-aa98-47aa-a82c-3dcf25edb47f)

**Comment by tiansQAQ** [comment]
你的pr被拒绝了，格式不正确。你按照正确的格式和规范提交修复下。

**Comment by tiansQAQ** [comment]
> node组件内部也用到了el-checkbox的label标签
