### ISSUE TITLE
[Feature Request] Is it possible to add more type options to the El-Button component with type="text"?

### ISSUE THREAD

**Issue by zxgMaster** [element-plus/element-plus#1604]
### Existing Component
是

### Component Name
el-button

### Description
hello，type ="text" button type now only has a default. If you want to use other colors, you have to write your own style. Can you consider adding some new text types to the button, such as "text-success", "text-info", "text-warning", "text-danger", "text-delete"?

**Comment by JeremyWuuuuu** [comment]
What would it be look like? You can achieve that via global css overriding, IMHO, I don't think that adding as many classes as possible is a good idea though.

**Comment by iendeavor** [comment]
Maybe we could extract the `text` prop as single prop and the `type` would be more consistent?
If this approach is OK, I would delight in open a PR for this.
