### ISSUE TITLE
[Component] [dialog] dialog的append-to属性配制不生效

### ISSUE THREAD

**Issue by 269153522** [element-plus/element-plus#16058]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.6.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGlkPVwid3JhcFwiPlxuICAgIDxidXR0b24gQGNsaWNrPVwiZGlhbG9nVmlzaWJsZT0hZGlhbG9nVmlzaWJsZVwiPkNsaWNrIE1lPC9idXR0b24+XG4gIDwvZGl2PlxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCI1MDBcIlxuICAgIGFwcGVuZC10bz1cIiN3cmFwXCJcbiAgPlxuICAgIDxzcGFuPlRoaXMgaXMgYSBtZXNzYWdlPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPGRpdiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPlxuICAgICAgICAgIENvbmZpcm1cbiAgICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4jd3JhcHtcbiAgd2lkdGg6IDgwMHB4O1xuICBoZWlnaHQ6IDUwMHB4O1xuICBiYWNrZ3JvdW5kOiBwaW5rO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1.配制element-plus,
2.配制dialog弹窗配制append-to属性

### What is Expected?

append-to可以配制后，弹窗出现在append-to配制的DOM里

### What is actually happening?

append-to配制后，弹窗依旧出现在body里

### Additional comments

_(empty)_

**Comment by 269153522** [comment]
![image](https://github.com/element-plus/element-plus/assets/43581398/f0322936-9396-4469-a9cf-e94fa467e6f7)

**Comment by btea** [comment]
According to the example you provided, the effect is normal.

![image](https://github.com/element-plus/element-plus/assets/24516654/0c13a11e-c56e-47c9-becc-bb27f6129522)

**Comment by 269153522** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 269153522** [comment]
![image](https://github.com/element-plus/element-plus/assets/43581398/8e1fa925-944d-4674-ae00-379313847775)
这应该是弹窗覆盖在wrap才对吧，而不是覆盖整个body,那样的话app-to属性意义就没了

**Comment by 269153522** [comment]
这应该是弹窗覆盖在wrap才对吧，而不是覆盖整个body,那样的话app-to属性意义就没了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [dialog] dialog的append-to属性配制不生效 (Issue #16058)





 
According to the example you provided, the effect is normal.
 
image.png (view on web)

**Comment by nova1751** [comment]
模态框本身是`fixed`定位的，是相对于整个视口而言的。如果想要达到你想要的效果可以考虑设置外层`#wrap`元素定位为`relative`，模态框元素定位为`absolute`。

**Comment by 269153522** [comment]
![image](https://github.com/element-plus/element-plus/assets/43581398/8ddeb553-20f6-4745-8480-b06a8c0674d7)
调试地址还是文章上边的那个

**Comment by btea** [comment]
这看起来像是playground的问题，你刷新一下就好了。

**Comment by 269153522** [comment]
刷新不行的，这个报错是在我运行的项目里也出现的，弹窗第一次正常，刷新之后再点击就报错Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月7日(星期四) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [dialog] dialog的append-to属性配制不生效 (Issue #16058)





 
这看起来像是playground的问题，你刷新一下就好了。

**Comment by btea** [comment]
我这边操作显示是正常的。

![play](https://github.com/element-plus/element-plus/assets/24516654/ffe7c8eb-9fc1-4c88-9ceb-20df0c927d14)

**Comment by 269153522** [comment]
![image](https://github.com/element-plus/element-plus/assets/43581398/f15df757-e75d-492f-a240-ccfeb1acd105)
多个弹窗的不行，你试下我那个在线代码，点击没有反应，会有报错。

**Comment by 269153522** [comment]
大佬，我找到问题关键点了
![image](https://github.com/element-plus/element-plus/assets/43581398/26abc1d0-a3d3-4f08-b66e-186da37c535c)
![image](https://github.com/element-plus/element-plus/assets/43581398/2ba58855-b9c5-4558-a833-c48a8dd88200)
![image](https://github.com/element-plus/element-plus/assets/43581398/ded8db7d-3429-4c39-911d-7ee7f4d5e967)
这个问题应该是出在哪里呢

**Comment by btea** [comment]
或许你要提供一个最小的复现代码仓库，现在只看图看不出问题所在。

**Comment by 269153522** [comment]
你好，我复现代码仓库地址是https://gitee.com/kaixinjiuhao888/element-plus-dialog.git

**Comment by btea** [comment]
根据警告信息可知，在dialog进行渲染的时候，`#appMain` 元素还不存在。`#appMain` 所在的组件  `AppMain.vue` 是 `dialog` 所在的组件`views/index.vue` 的父组件。
要解决这个问题，要么调整它们的结构，要么可以在`views/index.vue`里面延迟 `dialog`  的渲染。

![image](https://github.com/element-plus/element-plus/assets/24516654/668b627f-825f-42d0-828a-5c906819a8a3)

**Comment by 269153522** [comment]
好的，谢谢啦

**Comment by 269153522** [comment]
好的，谢谢啦，我改成这样可以了。
`<script setup name="Index">
import { ref } from 'vue';
const dialogVisible = ref(false);
const dialogBox = ref(false);
const showDialog = () => {
    dialogBox.value = true;
    dialogVisible.value = true;
};
</script>

<template>
    <div id="wrap" class="s-flex-c-c-c">
        <el-button type="primary" @click="showDialog">首页弹窗</el-button>
    </div>
    <div v-if="dialogBox">
        <el-dialog v-model="dialogVisible" title="Tips" width="500" append-to="#wrap">
            <span>index</span>
            <template #footer>
                <div class="dialog-footer">
                    <el-button @click="dialogVisible = false">Cancel</el-button>
                    <el-button type="primary" @click="dialogVisible = false">
                        Confirm
                    </el-button>
                </div>
            </template>
        </el-dialog>
    </div>
</template>

<style scoped>
#wrap {
    position: relative;
    height: 100%;
}
</style>
`

**Comment by kirokiller** [comment]
> 麻烦问下，当我这样使用后，有的弹窗点击不出现，报错这个是什么原因呢？ Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')

遇到了同样得问题，在el-tooltip中，没法处理延时渲染，要怎么解决

**Comment by 269153522** [comment]
![image](https://github.com/element-plus/element-plus/assets/43581398/05c796e9-4af9-4961-976a-24f2f819bcc4)
![image](https://github.com/element-plus/element-plus/assets/43581398/0be7fae6-3e7b-45e2-b8c4-4e8558c98123)
我目前是这样解决的，dialog包在一个div里，给divs设置个v-if属性，等到当前组件mounted的时候设置显示。
