### ISSUE TITLE
[Bug Report] When el-table's default-sort property is set, newly added items won't be rendered, unless sorting order is changed

### ISSUE THREAD

**Issue by maciejpedzich** [element-plus/element-plus#1606]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
Windows 10 / Google Chrome 88.0.4324.190

### Vue version
3.0.0

### Reproduction Link
https://jsfiddle.net/osv9zwpt/4/

### Steps to reproduce
1. Type anything in the "First name" input
2. Click the "Add person" button

### What is Expected?
Upon adding a new item, data array should be sorted again, and table rows re-rendered accordingly.

### What is actually happening?
New items won't be rendered at all, unless the sorting order of any field is changed.

**Comment by justwiner** [comment]
Can you provide test cases on `codeopen`, `jsfiddle` is not accessible in China, or provide the source code in the comments.

**Comment by maciejpedzich** [comment]
> @maciejpedzich
> hey, can you provide test cases on `codeopen`, `jsfiddle` is not accessible in China, or provide the source code in the comments, thanks.

Hey! Of course, I'll add a codepen link in a minute

**Comment by maciejpedzich** [comment]
> @maciejpedzich
> hey, can you provide test cases on `codeopen`, `jsfiddle` is not accessible in China, or provide the source code in the comments, thanks.

[Codepen repro link](https://codepen.io/maciejpedzich/pen/OJbrpOy)
