### ISSUE TITLE
[Component] [select, input] el-select focus状态，会出现边框溢出的问题。blur后仍有残留的蓝色像素在角落

### ISSUE THREAD

**Issue by kokonatsuli** [element-plus/element-plus#16077]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `Chrome 122.0.6261.95`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/form.html#%E8%A1%A8%E5%8D%95%E6%A0%A1%E9%AA%8C)

### Steps to reproduce

在文档的 #表单校验 部分，点击 Activity zone 选择器，然后仔细观察选择器边框的左上角。
包括 https://issue.element-plus.org/ issue标题的输入框也出现了同样情况。

### What is Expected?

hover、focus、error各个状态的边框范围一致，仅颜色有变化

### What is actually happening?

focus、error状态时，边框除了颜色变化，还溢出到了应有的范围之外。主要体现在左上角和右上角出现多余的蓝色或红色像素点。
且组件失焦后，蓝色像素点仍存在于左上角和右上角。

### Additional comments

其它版本我不清楚，我之前使用的2.3.14版本无此问题，升级到2.6.0则发现了这个问题。

![image](https://github.com/element-plus/element-plus/assets/40257376/6393c486-eff2-4949-a255-511f7a6a3e25)

**Comment by nova1751** [comment]
这种问题一般与屏幕分辨率和系统缩放有关，不是组件的问题。

**Comment by kooriookami** [comment]
似乎是chromium内核浏览器特有的问题

**Comment by kokonatsuli** [comment]
> 似乎是chromium内核浏览器特有的问题

确实，在 Firefox 没有复现这个问题。不过 element-plus@2.3.x 也没有这个问题。
对于这个问题发生的机制我完全没有头绪😅，明明看起来v2.3与v2.6的边框都是一样的，通过内阴影实现，但为什么会产生差异呢……🤔

**Comment by nova1751** [comment]
> > 似乎是chromium内核浏览器特有的问题
> 
> 确实，在 Firefox 没有复现这个问题。不过 [element-plus@2.3.x](mailto:element-plus@2.3.x) 也没有这个问题。 对于这个问题发生的机制我完全没有头绪😅，明明看起来v2.3与v2.6的边框都是一样的，通过内阴影实现，但为什么会产生差异呢……🤔

将浏览器缩放调整至150%缩放以上会不会出现同样的情况呢？

**Comment by kokonatsuli** [comment]
> > > 似乎是chromium内核浏览器特有的问题
> > 
> > 
> > 确实，在 Firefox 没有复现这个问题。不过 [element-plus@2.3.x](mailto:element-plus@2.3.x) 也没有这个问题。 对于这个问题发生的机制我完全没有头绪😅，明明看起来v2.3与v2.6的边框都是一样的，通过内阴影实现，但为什么会产生差异呢……🤔
> 
> 将浏览器缩放调整至150%缩放以上会不会出现同样的情况呢？

尝试了一下，也会，某些缩放倍率下会出现此问题。对我的设备来说（3440*1440），100%、110%、175%、200%时会出现

**Comment by nova1751** [comment]
> > > > 似乎是chromium内核浏览器特有的问题
> > > 
> > > 
> > > 确实，在 Firefox 没有复现这个问题。不过 [element-plus@2.3.x](mailto:element-plus@2.3.x) 也没有这个问题。 对于这个问题发生的机制我完全没有头绪😅，明明看起来v2.3与v2.6的边框都是一样的，通过内阴影实现，但为什么会产生差异呢……🤔
> > 
> > 
> > 将浏览器缩放调整至150%缩放以上会不会出现同样的情况呢？
> 
> 尝试了一下，也会，某些缩放倍率下会出现此问题。对我的设备来说（3440*1440），100%、110%、175%、200%时会出现

似乎是设备像素和设备独立像素没对齐导致的

**Comment by felixruan** [comment]
![image](https://github.com/user-attachments/assets/3552bace-de5a-4355-a76d-a7d6630704bf)
最新的2.8.0在100%没缩放的Edge和Chrome都有，怎么解决，这个真的很丑

**Comment by HaceraI** [comment]
+1 官方的白底背景看起来还不是很明显，我这种就很明显了😟
![look7](https://github.com/user-attachments/assets/611dcf4a-749e-49ef-83d3-f80272aac6d6)

**Comment by HaceraI** [comment]
貌似通过设置 [translate3d](transform: translate3d(0, 0, 0)) 能解决 -> https://github.com/element-plus/element-plus/issues/7034#issuecomment-1283537305


https://stackblitz.com/edit/stackblitz-starters-fezc3r?file=styles.css
(windows系统可以通过win + (+ / -)) 放大镜查看
| 浏览器          | 版本                                                    | 是否存在问题 |
|-----------------|-------------------------------------------------------|--------------|
| Microsoft Edge | 127.0.2651.105 (正式版本) (64 位) | 未发现问题 |
| Google Chrome | 27.0.6533.120 (Official Build) (64-bit) | 未发现问题 |
| Firefox | 121.0 (64 位) | 未发现问题 |

不知道还有没有其他的解决方案
