### ISSUE TITLE
[Component] [anchor, anchor-link] 使用锚点(el-anchor)组件报错

### ISSUE THREAD

**Issue by yzz-415** [element-plus/element-plus#16074]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.6.0`
- Browser / OS: `Chrome/121.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-anchor`
- `el-anchor-link`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvcGVuXCI+eHh4PC9lbC1idXR0b24+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cInNob3dcIj5cbiAgICA8ZWwtcm93PlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjE4XCI+XG4gICAgICAgIDxkaXYgcmVmPVwiY29udGFpbmVyUmVmXCIgc3R5bGU9XCJoZWlnaHQ6IDMwMHB4OyBvdmVyZmxvdy15OiBhdXRvXCI+XG4gICAgICAgICAgPGRpdlxuICAgICAgICAgICAgaWQ9XCJwYXJ0MVwiXG4gICAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2JhKDI1NSwgMCwgMCwgMC4wMik7XG4gICAgICAgICAgICAgIG1hcmdpbi10b3A6IDMwcHg7XG4gICAgICAgICAgICBcIlxuICAgICAgICAgID5cbiAgICAgICAgICAgIHBhcnQxXG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgPGRpdlxuICAgICAgICAgICAgaWQ9XCJwYXJ0MlwiXG4gICAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2JhKDAsIDI1NSwgMCwgMC4wMik7XG4gICAgICAgICAgICAgIG1hcmdpbi10b3A6IDMwcHg7XG4gICAgICAgICAgICBcIlxuICAgICAgICAgID5cbiAgICAgICAgICAgIHBhcnQyXG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgPGRpdlxuICAgICAgICAgICAgaWQ9XCJwYXJ0M1wiXG4gICAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2JhKDAsIDAsIDI1NSwgMC4wMik7XG4gICAgICAgICAgICAgIG1hcmdpbi10b3A6IDMwcHg7XG4gICAgICAgICAgICBcIlxuICAgICAgICAgID5cbiAgICAgICAgICAgIHBhcnQzXG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC1jb2w+XG4gICAgICA8ZWwtY29sIDpzcGFuPVwiNlwiPlxuICAgICAgICA8ZWwtYW5jaG9yXG4gICAgICAgICAgOmNvbnRhaW5lcj1cImNvbnRhaW5lclJlZlwiXG4gICAgICAgICAgZGlyZWN0aW9uPVwidmVydGljYWxcIlxuICAgICAgICAgIHR5cGU9XCJkZWZhbHV0XCJcbiAgICAgICAgICA6b2Zmc2V0PVwiMzBcIlxuICAgICAgICAgIEBjbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgICAgICAgPlxuICAgICAgICAgIDxlbC1hbmNob3ItbGluayBocmVmPVwiI3BhcnQxXCIgdGl0bGU9XCJwYXJ0MVwiIC8+XG4gICAgICAgICAgPGVsLWFuY2hvci1saW5rIGhyZWY9XCIjcGFydDJcIiB0aXRsZT1cInBhcnQyXCIgLz5cbiAgICAgICAgICA8ZWwtYW5jaG9yLWxpbmsgaHJlZj1cIiNwYXJ0M1wiIHRpdGxlPVwicGFydDNcIiAvPlxuICAgICAgICA8L2VsLWFuY2hvcj5cbiAgICAgIDwvZWwtY29sPlxuICAgIDwvZWwtcm93PlxuICAgICA8L2VsLWRpYWxvZz5cbiAgPC9kaXY+XG4gXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG93ID0gcmVmKGZhbHNlKVxuY29uc3QgY29udGFpbmVyUmVmID0gcmVmPEhUTUxFbGVtZW50IHwgbnVsbD4obnVsbClcbmNvbnN0IG9wZW4gPSAoZTogTW91c2VFdmVudCkgPT4ge1xuICBzaG93LnZhbHVlID0gdHJ1ZVxufVxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoZTogTW91c2VFdmVudCkgPT4ge1xuICBlLnByZXZlbnREZWZhdWx0KClcbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

<template>
  <div>
  <el-button @click="open">xxx</el-button>
  <el-dialog v-model="show">
    <el-row>
      <el-col :span="18">
        <div ref="containerRef" style="height: 300px; overflow-y: auto">
          <div
            id="part1"
            style="
              height: 300px;
              background: rgba(255, 0, 0, 0.02);
              margin-top: 30px;
            "
          >
            part1
          </div>
          <div
            id="part2"
            style="
              height: 300px;
              background: rgba(0, 255, 0, 0.02);
              margin-top: 30px;
            "
          >
            part2
          </div>
          <div
            id="part3"
            style="
              height: 300px;
              background: rgba(0, 0, 255, 0.02);
              margin-top: 30px;
            "
          >
            part3
          </div>
        </div>
      </el-col>
      <el-col :span="6">
        <el-anchor
          :container="containerRef"
          direction="vertical"
          type="defalut"
          :offset="30"
          @click="handleClick"
        >
          <el-anchor-link href="#part1" title="part1" />
          <el-anchor-link href="#part2" title="part2" />
          <el-anchor-link href="#part3" title="part3" />
        </el-anchor>
      </el-col>
    </el-row>
     </el-dialog>
  </div>
 
</template>

<script setup lang="ts">
import { ref } from 'vue'

const show = ref(false)
const containerRef = ref<HTMLElement | null>(null)
const open = (e: MouseEvent) => {
  show.value = true
}
const handleClick = (e: MouseEvent) => {
  e.preventDefault()
}
</script>

### What is Expected?

正常使用anchor

### What is actually happening?

会出现报错Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#/schedule' is not a valid selector.

我的路由为：http://localhost:3000/#/schedule

### Additional comments

查询anchor源码
onMounted(() => {
  getContainer()
  const hash = decodeURIComponent(window.location.hash)
  const target = getElement(hash)
  if (target) {
    scrollTo(hash)
  } else {
    handleScroll()
  }
})
export const getElement = ((
  target: string | HTMLElement | Window | null | undefined
) => {
  if (!isClient || target === '') return null
  if (isString(target)) {
    return document.querySelector<HTMLElement>(target)
  }
  return target
}) as GetElement

为什么会获取当前地址hash 去查询节点

**Comment by chenzhengduan** [comment]
请问问题解决了吗，我也遇到了

**Comment by yzz-415** [comment]
> 请问问题解决了吗，我也遇到了

路由不能用hash模式（createWebHashHistory） 用history模式（createWebHistory），但是会导致路由地址的显示异常。
我看他已经修复这个问题了 加了try catch

**Comment by chenzhengduan** [comment]
原来是这样，我也看到了，一直在等着更新，刚刚npm更新了，等了四十分钟

**Comment by chenzhengduan** [comment]
那只能用history模式了吗，不用history模式用不了这个组件了？
