### ISSUE TITLE
[Bug Report] Invalid watch source

### ISSUE THREAD

**Issue by exidot** [element-plus/element-plus#1608]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
Windows 10 / Chrome 79

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-fv80x?file=/src/App.vue

### Steps to reproduce
Avatar 组件，在使用 icon 属性为内置的 el-icon-* 时，Console会显示警告（我并不清楚其他组件会不会出现这个警告）
```
[Vue warn]: Invalid watch source:  undefined A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. 
 at <ElAvatar icon="el-icon-user-solid">
 at <App>
```

### What is Expected?
当我使用1.0.2-beta.32版本时并没有这个问题，升级为1.0.2-beta.33开始出现该问题。
请问是什么原因？

### What is actually happening?
我该怎么做才能消除这个警告？

**Comment by JeremyWuuuuu** [comment]
We didn't modify anything since the very beginning, it might be caused by `Vue` itself I suppose, but we have @inottn fixing it.

**Comment by exidot** [comment]
感谢您的及时处理，我看到了[#1615](https://github.com/element-plus/element-plus/pull/1615)，我想应该问题应该与1615相同
