### ISSUE TITLE
[Style] [button, dialog] link button class bug

### ISSUE THREAD

**Issue by huxiguo** [element-plus/element-plus#16116]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.5.6`
- Browser / OS: `Chrome 122.0.6261.112/Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsICB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsQnV0dG9uLEVsRGlhbG9nIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgaGFuZGxlRGlhbG9nPSgpPT57XG4gIGRpYWxvZ1Zpc2libGUudmFsdWU9dHJ1ZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxFbEJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGxpbmsgQGNsaWNrPVwiaGFuZGxlRGlhbG9nXCI+bGluazwvRWxCdXR0b24+XG5cdDxFbERpYWxvZyB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiIDp0aXRsZT1cImBCdWdgXCIgd2lkdGg9XCI2MCVcIiB0b3A9XCIyMHB4XCIgY2VudGVyPlxuXHRcdDx0ZW1wbGF0ZSAjZm9vdGVyPlxuXHRcdFx0PGRpdiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cblx0XHRcdFx0PGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPiBjb25maXJtIDwvZWwtYnV0dG9uPlxuXHRcdFx0PC9kaXY+XG5cdFx0PC90ZW1wbGF0ZT5cblx0PC9FbERpYWxvZz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Click the link button to pop up the dialog component. After pressing ESC on the keyboard, the link button will have a border.

### What is Expected?

I hope that the link button will have no border after pressing the ESC button.

### What is actually happening?

Actually when I press ESC there is a border

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsICB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsQnV0dG9uLEVsRGlhbG9nIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgaGFuZGxlRGlhbG9nPSgpPT57XG4gIGRpYWxvZ1Zpc2libGUudmFsdWU9dHJ1ZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxFbEJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGxpbmsgQGNsaWNrPVwiaGFuZGxlRGlhbG9nXCI+bGluazwvRWxCdXR0b24+XG4gIDxFbEJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImhhbmRsZURpYWxvZ1wiPmxpbms8L0VsQnV0dG9uPlxuXHRcblx0PEVsRGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgOnRpdGxlPVwiYEJ1Z2BcIiB3aWR0aD1cIjYwJVwiIHRvcD1cIjIwcHhcIiBjZW50ZXI+XG5cdFx0PHRlbXBsYXRlICNmb290ZXI+XG5cdFx0XHQ8ZGl2IGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuXHRcdFx0XHQ8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+IGNvbmZpcm0gPC9lbC1idXR0b24+XG5cdFx0XHQ8L2Rpdj5cblx0XHQ8L3RlbXBsYXRlPlxuXHQ8L0VsRGlhbG9nPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZD5cbi5lbC1idXR0b24uaXMtbGluazpmb2N1cy12aXNpYmxlIHtcbiAgb3V0bGluZS1zdHlsZTogbm9uZTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by kankan-web** [comment]
You may want to consider trying the deep selector.

**Comment by tolking** [comment]
This is an accessibility standard
