### ISSUE TITLE
[Component] [tree-select] treeselect二次过滤

### ISSUE THREAD

**Issue by Justicx26** [element-plus/element-plus#16126]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/sandbox/element-plus-spa-forked-7jn3f7?file=%2Fsrc%2FApp.vue%3A16%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltpgheho00073b6m7yo63yai%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltpgheho00033b6mv6x8vv0i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltpgheho00043b6mw3pe54eq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltpgheho00063b6mcfmckevf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltpgheho00033b6mv6x8vv0i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltpgheho00023b6meqzd89xb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltpgheho00033b6mv6x8vv0i%2522%252C%2522activeTabId%2522%253A%2522cltpgheho00023b6meqzd89xb%2522%257D%252C%2522cltpgheho00063b6mcfmckevf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltpgheho00053b6m0qyym3rn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltpgheho00063b6mcfmckevf%2522%252C%2522activeTabId%2522%253A%2522cltpgheho00053b6m0qyym3rn%2522%257D%252C%2522cltpgheho00043b6mw3pe54eq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltpgheho00043b6mw3pe54eq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

配置remote-method, 在远程搜索完成之后, 下拉面板的 options 显示内容与远程请求的数据不一致, 本地会对远程搜索返回的内容进行二次过滤.
### What is Expected?

远程所搜索后, options 直接显示远程返回的数组

### What is actually happening?

远程搜索后, 会再次在本地根据 props.label配置的字段过滤一遍

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
请提供有效的在线示例
https://element-plus.run/

**Comment by Justicx26** [comment]
[https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoXCJcIik7XG5jb25zdCBkYXRhID0gcmVmKFtdKTtcblxuLy8g5pCc57Si5qGG6L6T5YWlJzIn5p2l5aSN546w6Zeu6aKYXG5jb25zdCBzZWFyY2ggPSAocXVlcnkpID0+IHtcbiAgaWYgKCFxdWVyeSkge1xuICAgIGRhdGEudmFsdWUgPSBbXTtcbiAgICByZXR1cm47XG4gIH1cbiAgZGF0YS52YWx1ZSA9IFtcbiAgICB7XG4gICAgICBpZDogXCIxXCIsXG4gICAgICBuYW1lOiBcIjFcIixcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogXCIxLTFcIixcbiAgICAgICAgICBuYW1lOiBcIjEtMVwiLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgaWQ6IFwiMS0yXCIsXG4gICAgICAgICAgbmFtZTogXCIxLTJcIixcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiBcIjEtM1wiLFxuICAgICAgICAgIG5hbWU6IFwiMi0zXCIsXG4gICAgICAgIH0sXG4gICAgICBdLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6IFwiMlwiLFxuICAgICAgbmFtZTogXCIyXCIsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogXCIzXCIsXG4gICAgICBuYW1lOiBcIjNcIixcbiAgICB9LFxuICBdO1xufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gIDxlbC10cmVlLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgICA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCJcbiAgICAgIDpkZWZhdWx0LWV4cGFuZC1hbGw9XCJ0cnVlXCJcbiAgICAgIDpkZWZhdWx0LWZpcnN0LW9wdGlvbj1cImZhbHNlXCJcbiAgICAgIDpwcm9wcz1cInsgdmFsdWU6ICdpZCcsIGxhYmVsOiAnbmFtZScsIGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgY2xlYXJhYmxlXG4gICAgICBjaGVjay1zdHJpY3RseVxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgcmVtb3RlXG4gICAgICA6cmVtb3RlLW1ldGhvZD1cInNlYXJjaFwiXG4gICAgICByZW1vdGUtc2hvdy1zdWZmaXhcbiAgICAgIHJlc2VydmUta2V5d29yZFxuICAgID5cbiAgICA8L2VsLXRyZWUtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319](url)

**Comment by Justicx26** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoXCJcIik7XG5jb25zdCBkYXRhID0gcmVmKFtdKTtcblxuLy8g5pCc57Si5qGG6L6T5YWlJzIn5p2l5aSN546w6Zeu6aKYXG5jb25zdCBzZWFyY2ggPSAocXVlcnkpID0+IHtcbiAgaWYgKCFxdWVyeSkge1xuICAgIGRhdGEudmFsdWUgPSBbXTtcbiAgICByZXR1cm47XG4gIH1cbiAgZGF0YS52YWx1ZSA9IFtcbiAgICB7XG4gICAgICBpZDogXCIxXCIsXG4gICAgICBuYW1lOiBcIjFcIixcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogXCIxLTFcIixcbiAgICAgICAgICBuYW1lOiBcIjEtMVwiLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgaWQ6IFwiMS0yXCIsXG4gICAgICAgICAgbmFtZTogXCIxLTJcIixcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiBcIjEtM1wiLFxuICAgICAgICAgIG5hbWU6IFwiMi0zXCIsXG4gICAgICAgIH0sXG4gICAgICBdLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6IFwiMlwiLFxuICAgICAgbmFtZTogXCIyXCIsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogXCIzXCIsXG4gICAgICBuYW1lOiBcIjNcIixcbiAgICB9LFxuICBdO1xufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gIDxlbC10cmVlLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgICA6cmVuZGVyLWFmdGVyLWV4cGFuZD1cImZhbHNlXCJcbiAgICAgIDpkZWZhdWx0LWV4cGFuZC1hbGw9XCJ0cnVlXCJcbiAgICAgIDpkZWZhdWx0LWZpcnN0LW9wdGlvbj1cImZhbHNlXCJcbiAgICAgIDpwcm9wcz1cInsgdmFsdWU6ICdpZCcsIGxhYmVsOiAnbmFtZScsIGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgY2xlYXJhYmxlXG4gICAgICBjaGVjay1zdHJpY3RseVxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgcmVtb3RlXG4gICAgICA6cmVtb3RlLW1ldGhvZD1cInNlYXJjaFwiXG4gICAgICByZW1vdGUtc2hvdy1zdWZmaXhcbiAgICAgIHJlc2VydmUta2V5d29yZFxuICAgID5cbiAgICA8L2VsLXRyZWUtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by warmthsea** [comment]
@yujinpan
这段代码是导致这个问题产生的原因


https://github.com/element-plus/element-plus/pull/15974
https://github.com/element-plus/element-plus/blob/e80262b2db0967a52ebd75c1371497c2830f267e/packages/components/tree-select/src/select.ts#L32

**Comment by Justicx26** [comment]
这个问题会处理吗
