### ISSUE TITLE
[feature request] hopes to enable the label of eltabpanel to support custom slot

### ISSUE THREAD

**Issue by focus0802** [element-plus/element-plus#1613]
### Existing Component
Yes

### Component Name
ElTabPane

### Description
现在的ElTabPane的label只支持string，希望能够新增自定义slot，这样便可以添加图标或者头像等等内容。
类似于：
```
<el-tabs>
    <el-tab-pane>
        <template #label>
            <i class="el-icon-user" />
            <span>用户选项卡</span>
        </template>
    </el-tab-pane>
</el-tabs>
```

**Comment by Ryan2128** [comment]
You can directly use the slot named `label` to pass the label, the docs is not updated at present.
