### ISSUE TITLE
[Component] el-select 放置在 el-radio 组件当中，导致 el-select 点击时无法展开

### ISSUE THREAD

**Issue by Hollelihanqi** [element-plus/element-plus#16147]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.10`
- Element Plus Version: `2.6.1`
- Browser / OS: `Chrome 122.0.6261.112`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-radio`
- `el-radio-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgcmlza0xldmVsS2V5ID0gcmVmPGFueT4oKVxuY29uc3QgZm9ybU1vZGVsID0gcmVmPGFueT4oeyB0aW1lTGltaXQ6IFwiaW5kZWZpbml0ZWx5XCIgfSlcbmNvbnN0IHJ1bGVzID0ge1xuICByaXNrTGV2ZWw6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiBcIuivt+mAieaLqVwiLCB0cmlnZ2VyOiBbXCJibHVyXCIsIFwiY2hhbmdlXCJdIH1dLFxuICB0aW1lTGltaXQ6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiBcIuivt+mAieaLqVwiLCB0cmlnZ2VyOiBbXCJibHVyXCIsIFwiY2hhbmdlXCJdIH1dLFxuICBlbmRUaW1lOiBbeyByZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogXCLor7fpgInmi6lcIiwgdHJpZ2dlcjogW1wiYmx1clwiLCBcImNoYW5nZVwiXSB9XSxcbn1cbmNvbnN0IFJJU0tSQVRJTkcyID0gW1xuICB7IGxhYmVsOiBcIuaXoOmjjumZqVwiLCB2YWx1ZTogMCwgIH0sXG4gIHsgbGFiZWw6IFwi55aR5Ly86aOO6ZmpXCIsIHZhbHVlOiAxLCAgfSxcbiAgeyBsYWJlbDogXCLkvY7ljbHpo47pmalcIiwgdmFsdWU6IDIsICB9LFxuICB7IGxhYmVsOiBcIuS4reWNsemjjumZqVwiLCB2YWx1ZTogMywgIH0sXG4gIHsgbGFiZWw6IFwi6auY5Y2x6aOO6ZmpXCIsIHZhbHVlOiA0LCAgfSxcbiAgeyBsYWJlbDogXCLkuKXph43po47pmalcIiwgdmFsdWU6IDUsICB9LFxuXVxuY29uc3QgRm9ybUluc3RhbmNlUmVmID0gcmVmKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICAgIDxlbC1yYWRpby1ncm91cCAgdi1tb2RlbD1cInJpc2tMZXZlbEtleVwiIGNsYXNzPVwidy1mdWxsIGZsZXggZmxleC1jb2wgZ2FwLVsxNnB4XVwiPlxuICAgICAgICA8ZWwtcmFkaW8gdmFsdWU9XCJ0ZW5jZW50XCIgc2l6ZT1cImxhcmdlXCIgYm9yZGVyIGNsYXNzPVwidy1mdWxsICFtLTBcIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuXCI+XG4gICAgICAgICAgICA8c3Bhbj7ohb7orq88L3NwYW4+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZWwtcmFkaW8+XG4gICAgICAgIDxlbC1yYWRpbyB2YWx1ZT1cInFpYW54aW5cIiBzaXplPVwibGFyZ2VcIiBib3JkZXIgY2xhc3M9XCJ3LWZ1bGwgIW0tMFwiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW5cIj5cbiAgICAgICAgICAgIDxzcGFuPuWlh+WuieS/oTwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9lbC1yYWRpbz5cbiAgICAgICAgPGVsLXJhZGlvXG4gICAgICAgICAgdmFsdWU9XCJjdXN0b21cIlxuICAgICAgICAgIHNpemU9XCJsYXJnZVwiXG4gICAgICAgICAgYm9yZGVyXG4gICAgICAgICAgY2xhc3M9XCJ3LWZ1bGwgIW0tMCBtaW4taC1bNDBweF0gIWgtYXV0byBmbGV4ICFpdGVtcy1iYXNlbGluZSBlbC1yYWRpb19faW5wdXQtdG9weFwiXG4gICAgICAgID5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwicHQtWzhweF1cIj5cbiAgICAgICAgICAgIDxkaXY+5Lq65bel5qCH5rOoPC9kaXY+XG4gICAgICAgICAgICA8ZWwtZm9ybVxuICAgICAgICAgICAgICB2LWlmPVwicmlza0xldmVsS2V5ID09PSAnY3VzdG9tJ1wiXG4gICAgICAgICAgICAgIHJlZj1cIkZvcm1JbnN0YW5jZVJlZlwiXG4gICAgICAgICAgICAgIDptb2RlbD1cImZvcm1Nb2RlbFwiXG4gICAgICAgICAgICAgIDpydWxlcz1cInJ1bGVzXCJcbiAgICAgICAgICAgICAgbGFiZWwtd2lkdGg9XCI3MHB4XCJcbiAgICAgICAgICAgICAgbGFiZWwtcG9zaXRpb249XCJyaWdodFwiXG4gICAgICAgICAgICAgIGNsYXNzPVwicHQtWzI0cHhdXCJcbiAgICAgICAgICAgID5cbiAgICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIumjjumZqeivhOe6p1wiIHByb3A9XCJyaXNrTGV2ZWxcIj5cbiAgICAgICAgICAgICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtTW9kZWwucmlza0xldmVsXCIgY2xhc3M9XCJ3LWZ1bGxcIiBwbGFjZWhvbGRlcj1cIuivt+mAieaLqVwiIHN0eWxlPVwid2lkdGg6MjAwcHhcIj5cbiAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICAgICAgICAgICAgdi1mb3I9XCJpdGVtIGluIFJJU0tSQVRJTkcyXCJcbiAgICAgICAgICAgICAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAgICAgICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICAgICAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgICAgICAgICAgICA+PC9lbC1vcHRpb24+XG4gICAgICAgICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICAgICAgPC9lbC1mb3JtPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2VsLXJhZGlvPlxuICAgICAgPC9lbC1yYWRpby1ncm91cD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击人工标注，然后点击下拉选择框

### What is Expected?

点击下拉选择框，可以正常下拉

### What is actually happening?

点击下拉选择框，无法正常下拉

### Additional comments

_(empty)_

**Comment by Hollelihanqi** [comment]
原本好好的功能，更新到最新的 2.6.1 坑死了。居然这么不负责任

**Comment by warmthsea** [comment]
> 原本好好的功能，更新到最新的 2.6.1 坑死了。居然这么不负责任

两个焦点冲突导致的，不太好处理，上午已经看看了

**Comment by warmthsea** [comment]
你本来那个版本是正常的发一下

**Comment by kooriookami** [comment]
![image](https://github.com/element-plus/element-plus/assets/38392315/6615bd0c-a8f9-410b-a2dd-0753bdd81f60)

**Comment by kooriookami** [comment]
以前不存在这个问题吗，一直没有阻止过默认事件。
