### ISSUE TITLE
[Component] [select] When set teleported is "false", click header slot, dropdown will disappears.

### ISSUE THREAD

**Issue by meitan-li** [element-plus/element-plus#16148]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgbXVsdGlwbGVcbiAgICBjbGVhcmFibGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgIHBvcHBlci1jbGFzcz1cImN1c3RvbS1oZWFkZXJcIlxuICAgIDptYXgtY29sbGFwc2UtdGFncz1cIjFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA6dGVsZXBvcnRlZD1cImZhbHNlXCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjaGVhZGVyPlxuICAgICAgPGVsLWNoZWNrYm94XG4gICAgICAgIHYtbW9kZWw9XCJjaGVja0FsbFwiXG4gICAgICAgIDppbmRldGVybWluYXRlPVwiaW5kZXRlcm1pbmF0ZVwiXG4gICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGVja0FsbFwiXG4gICAgICA+XG4gICAgICAgIEFsbFxuICAgICAgPC9lbC1jaGVja2JveD5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBjaXRpZXNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIHdhdGNoIH0gZnJvbSAndnVlJ1xuXG5pbXBvcnQgdHlwZSB7IENoZWNrYm94VmFsdWVUeXBlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBjaGVja0FsbCA9IHJlZihmYWxzZSlcbmNvbnN0IGluZGV0ZXJtaW5hdGUgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZjxDaGVja2JveFZhbHVlVHlwZVtdPihbXSlcbmNvbnN0IGNpdGllcyA9IHJlZihbXG4gIHtcbiAgICB2YWx1ZTogJ0JlaWppbmcnLFxuICAgIGxhYmVsOiAnQmVpamluZycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ1NoYW5naGFpJyxcbiAgICBsYWJlbDogJ1NoYW5naGFpJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnTmFuamluZycsXG4gICAgbGFiZWw6ICdOYW5qaW5nJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnQ2hlbmdkdScsXG4gICAgbGFiZWw6ICdDaGVuZ2R1JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnU2hlbnpoZW4nLFxuICAgIGxhYmVsOiAnU2hlbnpoZW4nLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdHdWFuZ3pob3UnLFxuICAgIGxhYmVsOiAnR3Vhbmd6aG91JyxcbiAgfSxcbl0pXG5cbndhdGNoKHZhbHVlLCAodmFsKSA9PiB7XG4gIGlmICh2YWwubGVuZ3RoID09PSAwKSB7XG4gICAgY2hlY2tBbGwudmFsdWUgPSBmYWxzZVxuICAgIGluZGV0ZXJtaW5hdGUudmFsdWUgPSBmYWxzZVxuICB9IGVsc2UgaWYgKHZhbC5sZW5ndGggPT09IGNpdGllcy52YWx1ZS5sZW5ndGgpIHtcbiAgICBjaGVja0FsbC52YWx1ZSA9IHRydWVcbiAgICBpbmRldGVybWluYXRlLnZhbHVlID0gZmFsc2VcbiAgfSBlbHNlIHtcbiAgICBpbmRldGVybWluYXRlLnZhbHVlID0gdHJ1ZVxuICB9XG59KVxuXG5jb25zdCBoYW5kbGVDaGVja0FsbCA9ICh2YWw6IENoZWNrYm94VmFsdWVUeXBlKSA9PiB7XG4gIGluZGV0ZXJtaW5hdGUudmFsdWUgPSBmYWxzZVxuICBpZiAodmFsKSB7XG4gICAgdmFsdWUudmFsdWUgPSBjaXRpZXMudmFsdWUubWFwKChfKSA9PiBfLnZhbHVlKVxuICB9IGVsc2Uge1xuICAgIHZhbHVlLnZhbHVlID0gW11cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5jdXN0b20taGVhZGVyIC5lbC1jaGVja2JveCB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBoZWlnaHQ6IHVuc2V0O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. As in the official example, use the header slot in the dropdown.
2. Set teleported is 'false'.
3. Click the All checkbox in the dropdown.
4. The dropdown will disappears.

### What is Expected?

The dropdown stay expanded, just like setting teleported is 'true'.

### What is actually happening?

Dropdown will disappears.

### Additional comments

1. 使用header插槽实现一键全选的功能
2. 如果设置teleported为false
3. 点击下拉中的“全选”checkbox
4. 下拉将会收起

如果teleported为true则一切正常，下拉不会收起

**Comment by dadaguai-git** [comment]
![image](https://github.com/element-plus/element-plus/assets/35138018/7eb04a76-5c1b-4774-9af5-a61e67e41a74)
没复现成功啊 而且你的false 写错了吧

**Comment by zeyongTsai** [comment]
猜测是因为 dropdown 点击事件冒泡出去认为不是点的  option 而收起。 放到 body 下没有冒泡则没有问题。建议阻止一下冒泡：

```html
<el-checkbox
  v-model="checkAll"
  :indeterminate="indeterminate"
  @change="handleCheckAll"
  @click.stop
>
  All
</el-checkbox>
```

**Comment by meitan-li** [comment]
> 猜测是因为 dropdown 点击事件冒泡出去认为不是点的 option 而收起。 放到 body 下没有冒泡则没有问题。建议阻止一下冒泡：
> 
> ```
> <el-checkbox
>   v-model="checkAll"
>   :indeterminate="indeterminate"
>   @change="handleCheckAll"
>   @click.stop
> >
>   All
> </el-checkbox>
> ```

看起来是这个原因了
感谢！ 这很好的解决了我的问题
