### ISSUE TITLE
[Component] [select] Dropdown menu fails to expand when the el-select component is placed within a <label> element

### ISSUE THREAD

**Issue by yxb94616** [element-plus/element-plus#16157]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `Chrome/122.0.0.0 Safari/537.36 / Windows NT 10.0; Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImZsZXggZmxleC13cmFwIGdhcC00IGl0ZW1zLWNlbnRlclwiPlxuICAgIDxlbC1yb3cgOmd1dHRlcj1cIjMwXCI+XG4gICAgICA8ZWwtY29sIDpzcGFuPVwiOFwiPlxuICAgICAgICA8bGFiZWw+XG4gICAgICAgICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWUudGVzdFwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc2l6ZT1cImxhcmdlXCIgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIj5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLmmK9cIiA6dmFsdWU9XCJ0cnVlXCIgLz5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLlkKZcIiA6dmFsdWU9XCJmYWxzZVwiIC8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgIDwvbGFiZWw+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCI4XCI+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlLnRlc3QxXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiBzaXplPVwibGFyZ2VcIiBzdHlsZT1cIndpZHRoOiAyNDBweFwiPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLmmK9cIiA6dmFsdWU9XCJ0cnVlXCIgLz5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5ZCmXCIgOnZhbHVlPVwiZmFsc2VcIiAvPlxuICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgIDwvZWwtY29sPlxuICAgIDwvZWwtcm93PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWFjdGl2ZSh7IHRlc3Q6IHVuZGVmaW5lZCwgdGVzdDE6IHVuZGVmaW5lZCB9KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

When the el-select component is wrapped within a <label> element, clicking the el-select component fails to expand the dropdown menu.

### What is Expected?

el-select works normally when used within a <label>.

### What is actually happening?

The dropdown menu fails to expand when the el-select component is placed within a <label> element.

### Additional comments

_(empty)_

**Comment by yxb94616** [comment]
After testing, it has been found that starting from version 2.5.0, this issue persists. However, in my project, after reverting the version to 2.4.4, it functions normally.

**Comment by chenxch** [comment]
Please add the for attribute to the label label.

**Comment by kooriookami** [comment]
Fixed.
