### ISSUE TITLE
[Build] [All] elementplus 全量引入后使用vite打包报错，按需引入不会报错

### ISSUE THREAD

**Issue by yklhello** [element-plus/element-plus#16158]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.6.0`
- Browser / OS: `任意`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL0NvbXAudnVlIjoiIiwiX28iOnt9fQ==)

### Steps to reproduce

1、npm create vite@latest
// main.ts 
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

import './style.css'
import App from './App.vue'

const app = createApp(App)
app.use(ElementPlus)

app.mount('#app')
2、npm run build

### What is Expected?

build normal

### What is actually happening?

error during build:
SyntaxError: [vite:esbuild-transpile] Unexpected token b in JSON at position 0
    at JSON.parse (<anonymous>)
    at transformWithEsbuild (file:///D:/sungrow/vue3-study/authoity-pro/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:14712:28)
    at async Object.renderChunk (file:///D:/sungrow/vue3-study/authoity-pro/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:14816:25)
    at async transformChunk (file:///D:/sungrow/vue3-study/authoity-pro/node_modules/rollup/dist/es/shared/node-entry.js:17723:16)
    at async file:///D:/sungrow/vue3-study/authoity-pro/node_modules/rollup/dist/es/shared/node-entry.js:17797:17
    at async Promise.all (index 0)
    at async transformChunksAndGenerateContentHashes (file:///D:/sungrow/vue3-study/authoity-pro/node_modules/rollup/dist/es/shared/node-entry.js:17792:5)
    at async renderChunks (file:///D:/sungrow/vue3-study/authoity-pro/node_modules/rollup/dist/es/shared/node-entry.js:17701:137)

### Additional comments

_(empty)_

**Comment by zeyongTsai** [comment]
![image](https://github.com/element-plus/element-plus/assets/8591261/a1589857-efb0-459f-afd1-34e5eb375c08)
使用 vite 官方的 demo 没有复现。

**Comment by chenxch** [comment]
请提供可复现demo以及相关环境信息
