### ISSUE TITLE
[Component] [color-picker] When flex-direction: column is used; There will be a floating layer disorder

### ISSUE THREAD

**Issue by xxholly32** [element-plus/element-plus#16171]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.5.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tY29sb3ItYmxvY2tcIj5cbiAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5XaXRoIGRlZmF1bHQgdmFsdWU8L3NwYW4+XG4gICAgPGVsLWNvbG9yLXBpY2tlciB2LW1vZGVsPVwiY29sb3IxXCIgLz5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJkZW1vLWNvbG9yLWJsb2NrXCI+XG4gICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+V2l0aCBubyBkZWZhdWx0IHZhbHVlPC9zcGFuPlxuICAgIDxlbC1jb2xvci1waWNrZXIgdi1tb2RlbD1cImNvbG9yMlwiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY29sb3IxID0gcmVmKCcjNDA5RUZGJylcbmNvbnN0IGNvbG9yMiA9IHJlZigpXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmRlbW8tY29sb3ItYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICBtYXJnaW4tYm90dG9tOiAxNnB4O1xufVxuLmRlbW8tY29sb3ItYmxvY2sgLmRlbW9uc3RyYXRpb24ge1xuICBtYXJnaW4tcmlnaHQ6IDE2cHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

When flex-direction: column is used; There will be a floating layer disorder

### What is Expected?

no disorder

### What is actually happening?

Not selected

### Additional comments

Adding placement="top-start" at https://github.com/element-plus/element-plus/blob/dev/packages/components/color-picker/src/color-picker.vue#L6 here takes effect

need more research if we're gonna solve it

**Comment by Fuphoenixes** [comment]
```
 <div class="demo-color-block">
    <span class="demonstration">With default value</span>
    <div>
      <el-color-picker v-model="color1" />
    </div>
  </div>
```

**Comment by Fuphoenixes** [comment]
I don't think this is a problem. You can handle it like above.
