### ISSUE TITLE
[Component] [select] el-select 宽度被限制为最大16px

### ISSUE THREAD

**Issue by xzhdev** [element-plus/element-plus#16170]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.0`
- Browser / OS: `Chrome 122.0.6261.112 / Mac os 14.4 `
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCB2YWx1ZTEgPSByZWYoW1wiT3B0aW9uMVwiXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiID5cbiAgICAgIDxlbC1mb3JtLWl0ZW0gPlxuICAgICAgICA8ZWwtc2VsZWN0XG4gICAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgICAgICAgIG11bHRpcGxlXG4gICAgICAgICAgcGxhY2Vob2xkZXI9XCLml6DmlbDmja5cIlxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgID5cbiAgICAgICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

将 el-select 组件 放在<el-form :inline="true">中即可复现

### What is Expected?

el-select 宽度不被限制正常显示如版本2.4.4

### What is actually happening?

el-select 宽度被限制为 max-width: 16px

### Additional comments

_(empty)_

**Comment by xzhdev** [comment]
异常
<img width="1113" alt="image" src="https://github.com/element-plus/element-plus/assets/102580603/3d53a6e4-e4e0-4b40-b7bd-dbc462cc65d7">
正常
<img width="1244" alt="image" src="https://github.com/element-plus/element-plus/assets/102580603/22697db2-e0ef-4086-b905-0822f86b66a9">

**Comment by kooriookami** [comment]
inline 模式请给 el-form-item 设置一个固定宽度，el-select 会 100% 撑满容器宽度。

**Comment by BwinYang** [comment]
这个确实是个问题，element-plus后面的版本把el-select的样式全改了，导致父元素用flex布局，el-select就塌缩了。之前谁改的el-select的样式，需要修复一下这个问题。

**Comment by LTaooo** [comment]
![image](https://github.com/element-plus/element-plus/assets/28125259/ccf53a08-fdf0-4b10-bc1a-68c0ae94e897)
同样的问题

**Comment by Manba0** [comment]
现在官网是建议我们设置宽度 ，这里设置默认宽度是不做修改了吗

**Comment by gyt95** [comment]
更新完偶尔发现这个突如其来的问题，好坑

**Comment by gaojiangtao-git** [comment]
升级时多看看破坏性更新记录
