### ISSUE TITLE
[Docs] [table] 文档解释文字冗余

### ISSUE THREAD

**Issue by dong-lufei** [element-plus/element-plus#16187]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.3`
- Browser / OS: `googlechrome: 120.0.6099.71`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#table-api)

### Steps to reproduce

empty-text 熟悉解释：“空数据时显示的文本内容， 也可以通过 #empty 设置 也可以通过 #empty 设置”

### What is Expected?

不要重复或者把重复的内容补充为别的漏的功能：空数据时显示的文本内容， 也可以通过 #empty 设置

### What is actually happening?

没有

### Additional comments

_(empty)_

**Comment by dong-lufei** [comment]
@wzc520pyfm crowdin I can't use it. Those of you who find that you really need to delete a few redundant words, you can go to PR yourself

**Comment by chenxch** [comment]
@dong-lufei @wzc520pyfm Thanks for your contribution, the document modification has been approved.
