### ISSUE TITLE
[Component] [select] Select 组件 options 数据中 value 对应的字段重复时，筛选显示有问题

### ISSUE THREAD

**Issue by wangxiaocuo** [element-plus/element-plus#16197]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.5.3`
- Browser / OS: `Chrome/120.0.0.0 / macOS 14.2.1`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZSArIGl0ZW0ubGFiZWxcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLmxhYmVsXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAgeyBsYWJlbDogJy0t5Li656m6LS0nLCB2YWx1ZTogLTEgfSxcbiAgeyBsYWJlbDogJ+a1i+ivlemHjeWkjWxhYmxlJywgdmFsdWU6IDEgfSxcbiAgeyBsYWJlbDogJ+a1i+ivlemHjeWkjWxhYmxlJywgdmFsdWU6IDIgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

由于业务需要，`value` 需要设置为 `label`，但是 `label` 有重复。具体见链接和截图。

### What is Expected?

显示正常

### What is actually happening?

显示不正常

### Additional comments

_(empty)_

![WX20240321-110848@2x](https://github.com/element-plus/element-plus/assets/16472134/05abbd97-0e0e-4ecb-917d-fa1aa5af107b)

**Comment by Fuphoenixes** [comment]
请保证value参数唯一，后续业务需要时，在通过value去获取label。
```
const options = [
  { label: '--为空--', value: -1 },
  { label: '测试重复lable', value: 1 },
  { label: '测试重复lable', value: 2 }
]
const getLabelByValue = (value) => {
   const theOne = options.find(item => item.value === value)
   return theOne ? theOne.label : ''
}
```
