### ISSUE TITLE
Css migration from element ui to element plus

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1619]
Hi i have used elememt ui
```@import "../../node_modules/element-ui/packages/theme-chalk/src/index";```

When i'm switching to element plus, half of my css is braking.
Can you tell me please the difference so i will not how to fix it?
```@import "../../node_modules/element-plus/packages/theme-chalk/src/index";```

**Comment by iamkun** [comment]
Are you looking for the SASS source file? 

You can find it here `/packages/theme-chalk/src/index.scss`

**Comment by vadimt2** [comment]
I'm using the latest version.
I have found what was is the issue.
```
row.scss
```

How did i fix it ?
Copy from 
```
C:\Users\vadim\OneDrive\Desktop\WebApplication\node_modules\element-ui\packages\theme-chalk\src
```
to:
```
```
C:\Users\vadim\OneDrive\Desktop\WebApplication\node_modules\element-plus\packages\theme-chalk\src
```
