### ISSUE TITLE
☝️ Breaking Change List

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#162]
Here is the list of breaking changes from Element 2.x to Element Plus

**Comment by zazzaz** [comment]
## Time Picker

### Attributes
1. Delete picker-options (Move picker-options to component tag)
2. Delete picker-options.format (Use the only picker format)
3. Delete picker-options.selectableRange (New selectableRange API )
4. Add disabledHours disabledMinutes disabledSeconds APIs

**Comment by bastarder** [comment]
## Timeline

### Attributes
1. Delete reverse (You should update data to reverse time-line，not bind props reverse)

**Comment by JeremyWuuuuu** [comment]
## Tooltip

### Attributes
1. popperOptions: since we have replaced the previous version to `@popperjs/core` v2, the popperOptions are completely different from v1.
~~~diff
--- popper.js parameters
+++ once the user has provided this option, the popper is under the user's control, `Popper` will not initialize `popper` from the default options anymore, all attributes such as `offset` will not be effective
~~~

**Comment by xiaoeyuZZZ** [comment]
## Popconfirm

### Attributes
1. onConfirm is replaced by confirm
2. onCancel is replaced by cancel

**Comment by zazzaz** [comment]
## Calendar

### Attributes
1. value / v-model Date Object only
2. range Date Object only, do not have to be start day of week / end day of week
3. remove first-day-of-week, use Day.js locale instead
4. slot data add date (JS Date)

### Doc
How to set Day.js locale

**Comment by zazzaz** [comment]
## Date Picker

### Attributes
1. remove first-day-of-week, use Day.js locale instead

### Doc
Update editable description

**Comment by HerringtonDarkholme** [comment]
# Form

1. validate now returns a promise that reject invalidFields instead of a single boolean if no callback is provided.
2. the library now assumes Promise is always available and users should provide a sensible polyfill if they need ever to support deprecate browsers at all.

**Comment by zazzaz** [comment]
## Locale

1. Default language English
2. Locale file name in lower case

**Comment by zazzaz** [comment]
## TimePicker

#### Attributes

- Delete picker-options option (Move to top-level options separately)

**Comment by edsolater** [comment]
> 
> ## Date Picker
> ### Attributes
> 
>     1. remove first-day-of-week, use Day.js locale instead
> 
>     2. Delete picker-options option (Move to top-level options separately)
> 
>     3. Add shortcut option, change accepted values [{text, value}]
> 
>     4. Add disabledDate option
> 
>     5. defaultTime option accept Date object
> 
>     6. remove `type`, and export saparate component
> 
> 
> > Date(s)Picker(time)  - DateRangePicker(time)
> > MonthPicker  - MonthRangePicker
> > WeekPicker
> > YearPicker
> 
> ### Doc
> 
> Update editable description

there should be an example about how to set locale on Day.js which may affect element-plus as metioned。

**Comment by Grubby520** [comment]
> ## Time Picker
> ### Attributes
> 1. Delete picker-options option (Move to top-level options separately)
> 2. Delete picker-options.format (Use the only picker format)
> 3. Delete picker-options.selectableRange (New selectableRange API )
> 4. Delete value-format option, out-put binding value will always be a Date Object
> 5. emove is-range, and export saparate component
> 
> > TimePicker TimeRangePicker
> 
> 1. Add disabledHours(for range picker type start | end) disabledMinutes disabledSeconds APIs
> 
> ### Doc
> Update editable description (prevent mobile device virtual keyboard)

Attributes “value-format” ，has it been cancelled? how to format values?

**Comment by attacking** [comment]
> ## Time Picker
> ### Attributes
> 1. Delete picker-options option (Move to top-level options separately)
> 2. Delete picker-options.format (Use the only picker format)
> 3. Delete picker-options.selectableRange (New selectableRange API )
> 4. Delete value-format option, out-put binding value will always be a Date Object
> 5. emove is-range, and export saparate component
> 
> > TimePicker TimeRangePicker
> 
> 1. Add disabledHours(for range picker type start | end) disabledMinutes disabledSeconds APIs
> 
> ### Doc
> Update editable description (prevent mobile device virtual keyboard)

In demo code, there is still 'is-range' and works correctly. It seems that the summary has some mistake. Will there be a comprehensive and accurate migration guide in the near future?

**Comment by attacking** [comment]
> ## Popconfirm
> ### Attributes
> 1. event onConfirm is replaced by confirm
> 2. event onCancel is replaced by cancel

there seems does not change.

**Comment by xiaoeyuZZZ** [comment]
yes, just changed the method name
------------------ Original ------------------

**Comment by attacking** [comment]
> ## Timeline
> ### Attributes
> 1. Delete reverse (You should update data to reverse time-line，not bind props reverse)

can we achieve reverse by judging the vnode type and its children?  Anyway, keeping functions stable is good for elementui users

**Comment by zazzaz** [comment]
> In the demo code, there is still 'is-range' and works correctly. It seems that the summary has some mistakes. Will there be a comprehensive and accurate migration guide in the near future?

The split component plan is canceled and deleted above, cause this will increase a huge bundle size.

**Comment by zazzaz** [comment]
> there should be an example about how to set locale on Day.js which may affect element-plus as metioned。

@edsolater Yes, updated here #1096

**Comment by JeremyWuuuuu** [comment]
Since before this PR https://github.com/element-plus/element-plus/pull/1354/files, the API is kind of confusing, for instance: 
`show-after` indicates when the trigger event occurred, `tooltip` and `popover` will appear after `show-after` time.
But `hide-after` indicates the `tooltip` `popover` should be auto closed after `hide-after` time.
In this PR we adjust the semantics for `hide-after` which means after `hide-after` time the popups should be disappear from the screen. Also a new API `auto-close` for indicating closing the popups after `auto-close` time popups right after `show` event occurred.

So here is the API changes
## Tooltip Popover PopConfirm

> `open-delay` changed to `show-after`
> `close-delay` changed to `hide-after`
> `hide-after` changed to `auto-close`

**Comment by OuZehui** [comment]
[Vue warn]: Failed to resolve component: el-affix

**Comment by JeremyWuuuuu** [comment]
> [Vue warn]: Failed to resolve component: el-affix

Please DO NOT REPORT ISSUES HERE, open an individual one with specific description, thank you very much.

**Comment by iamkun** [comment]
## Dialog

- 1. `visible` change to `v-model`

**Comment by YunYouJun** [comment]
## Theme-chalk

- use `sass:map` to refactor var `color` #2504

**Comment by kooriookami** [comment]
## Form
* `float` layout changed to `flex` layout.

## Row
* `float` layout changed to `flex` layout.
* Remove prop `type="flex"`.

**Comment by JeremyWuuuuu** [comment]
## Menu

- rename `el-submenu` to `el-sub-menu` (class name included)

**Comment by kooriookami** [comment]
## Menu
* When menu is horizontal and too long to show, the overflow will be added to a sub menu.
![image](https://user-images.githubusercontent.com/38392315/131630035-23b6b5c9-0f03-4525-b54d-63a60b6081ee.png)

**Comment by YunYouJun** [comment]
## Theme-chalk

- `-background-color` -> `-bg-color`
- `-font-color` -> `-text-color`

Example:
- `$--button-font-color` will change to `$--button-text-color`
- `$--button-background-color` will change to `$--button-bg-color`

> Similiar to tailwindcss

**Comment by sxzz** [comment]
移除全局配置 app.config.globalProperties.$ELEMENT | Remove global config app.config.globalProperties.$ELEMENT https://github.com/element-plus/element-plus/pull/4793

关于 app.config.globalProperties.$ELEMENT，也是从 Element UI 遗留下来的代码。使用 Vue 3 建议使用 inject 的方式去传递全局配置。新方式支持配置 reactive 可变。

About app.config.globalProperties.$ELEMENT, it is also the code left over from Element UI. With Vue 3, it is recommended to use inject to pass the global configuration. The new way supports reactive configuration.

**Comment by sxzz** [comment]
This issue is outdated, please see 

- [Element Plus 不兼容变化（中文简体）](https://github.com/element-plus/element-plus/discussions/5657)
- [Element Plus Breaking Changes (English version)](https://github.com/element-plus/element-plus/discussions/5658)
