### ISSUE TITLE
[bug report] when using avatar, the SRC console will print a warning message

### ISSUE THREAD

**Issue by zhixiaotong** [element-plus/element-plus#1620]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
Chrome

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/zhixiaotong/pen/jOVdPLz

### Steps to reproduce
F12 -> console
在官网demo使用页面代码中，例子可以不用传递src，直接传icon即可，但是console会打印warning

查看源码，直接watch了src属性，而src默认不传是undefined，由于我代码只展示icon，不需要传空字符串src，所以麻烦优化一下，谢谢。

### What is Expected?
conole不打印warning

### What is actually happening?
console实际打印了如下信息
```
vue@next:1254 [Vue warn]: Invalid watch source:  undefined A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. 
  at <ElAvatar icon="el-icon-user" > 
  at <App>
```

**Comment by inottn** [comment]
resolved #1615

**Comment by zhixiaotong** [comment]
OK
