### ISSUE TITLE
[Style] [rate] Rate评分，半选属性，选择完成后，鼠标快速划入，组件显示与value不符

### ISSUE THREAD

**Issue by Power-Monster** [element-plus/element-plus#16206]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-rate`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/rate.html)

### Steps to reproduce

Rate评分，半选属性，选择完成后，鼠标快速划入，组件显示与value不符

### What is Expected?

显示与value相符合

### What is actually happening?

显示与value不符合

### Additional comments

_(empty)_

**Comment by Fuphoenixes** [comment]
怎么不符？请提供更多的信息。

**Comment by wonderl17** [comment]
点击以后才会更改value吧
