### ISSUE TITLE
[Docs] [All] 版本更新日志为什么只有英文？难道作为国内产品，第一语言不该是中文吗？

### ISSUE THREAD

**Issue by itunic** [element-plus/element-plus#16225]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/guide/changelog.html)

### Steps to reproduce

版本更新日志为什么只有英文？难道作为国内产品，第一语言不该是中文吗？

### What is Expected?

版本更新日志为什么只有英文？难道作为国内产品，第一语言不该是中文吗？

### What is actually happening?

版本更新日志为什么只有英文？难道作为国内产品，第一语言不该是中文吗？

### Additional comments

_(empty)_

**Comment by cuideyu** [comment]
包装自己是个国际化的东西呗。提个bug几百年没人回复。下个项目不再用这个东西了。

**Comment by plainheart** [comment]
因为这是从 GitHub PR 自动生成的，没有进行翻译。
