### ISSUE TITLE
[Bug Report] el-select Delete data, display problems

### ISSUE THREAD

**Issue by xiaolannuoyi** [element-plus/element-plus#1623]
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
mac os 11.2.3

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/xiaolannuoyi/pen/jOVdbJO?editors=1010

### Steps to reproduce
el-select multiple selected data will not change after deletion.
![2021-03-12 18-20-14 2021-03-12 18_22_09](https://user-images.githubusercontent.com/21079721/110927095-283b3500-8360-11eb-9db3-0c64d38261f0.gif)

### What is Expected?
The data of select is consistent with the real data

### What is actually happening?
No change

**Comment by Ryan2128** [comment]
Sorry, I think the reason is vue's bug, the watch will be called after props changed in vue2.

**Comment by xiaolannuoyi** [comment]
@Ryan2128 
I see you mentioned issues in vue3, but you closed it again. Why? [https://github.com/vuejs/vue-next/issues/3430](https://github.com/vuejs/vue-next/issues/3430)

**Comment by Ryan2128** [comment]
> @Ryan2128
> I see you mentioned issues in vue3, but you closed it again. Why? [vuejs/vue-next#3430](https://github.com/vuejs/vue-next/issues/3430)

Because they think this behavior is correct.

![image](https://user-images.githubusercontent.com/33176053/111431179-69ec2700-8736-11eb-96ca-806fbcc67f2f.png)

**Comment by xiaolannuoyi** [comment]
I got it ! thank you！
