### ISSUE TITLE
[TypeScript] [anchor] 锚点组件`Anchor` type属性的类型提示应该是`default`而不是`defalut`

### ISSUE THREAD

**Issue by L0st1** [element-plus/element-plus#16233]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'`
- Build Tool: `Vue CLI`

### Related Component

- `el-anchor`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbEFuY2hvciwgRWxBbmNob3JMaW5rIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBjb250YWluZXJSZWYgPSByZWY8SFRNTEVsZW1lbnQgfCBudWxsPihudWxsKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1hbmNob3JcbiAgICA6Y29udGFpbmVyPVwiY29udGFpbmVyUmVmXCJcbiAgICBkaXJlY3Rpb249XCJ2ZXJ0aWNhbFwiXG4gICAgdHlwZT1cImRlZmF1bHRcIlxuICAgIDpvZmZzZXQ9XCIzMFwiXG4gID5cbiAgICA8ZWwtYW5jaG9yLWxpbmsgaHJlZj1cIiNwYXJ0MVwiIHRpdGxlPVwicGFydDFcIiAvPlxuICAgIDxlbC1hbmNob3ItbGluayBocmVmPVwiI3BhcnQyXCIgdGl0bGU9XCJwYXJ0MlwiIC8+XG4gICAgPGVsLWFuY2hvci1saW5rIGhyZWY9XCIjcGFydDNcIiB0aXRsZT1cInBhcnQzXCIgLz5cbiAgPC9lbC1hbmNob3I+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

设置组件type值为default
随后VS Code将报红，提示类型不符

### What is Expected?

type值为default时正常通过类型提示

### What is actually happening?

type的枚举是default，所以编译器会报红
```
Type '"default"' is not assignable to type 'EpPropMergeType<(new (...args: any[]) => "defalut" | "underline") | (() => "defalut" | "underline") | ((new (...args: any[]) => "defalut" | "underline") | (() => "defalut" | "underline"))[], unknown, unknown> | undefined'. Did you mean '"defalut"'?ts(2820)
index.d.ts(108, 5): The expected type comes from property 'type' which is declared here on type 'Partial<{ type: EpPropMergeType<(new (...args: any[]) => "defalut" | "underline") | (() => "defalut" | "underline") | ((new (...args: any[]) => "defalut" | "underline") | (() => "defalut" | "underline"))[], unknown, unknown>; ... 4 more ...; direction: EpPropMergeType<...>; }> & Omit<...> & Record<...>'
```

### Additional comments

_(empty)_

**Comment by L0st1** [comment]
![image](https://github.com/element-plus/element-plus/assets/64479959/819088f5-cfa8-4279-a15d-d3975d27ef50)

**Comment by makedopamine** [comment]
已在2.6.2版本中修复
