### ISSUE TITLE
[Component] [watermark] iOS safari browser cannot display watermark properly

### ISSUE THREAD

**Issue by happy-lsl** [element-plus/element-plus#16235]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.6.1`
- Browser / OS: `iPhone XR IOS 14.6`
- Build Tool: `Nuxt`

### Related Component

- `el-watermark`

### Reproduction Link

[CodePen](https://codepen.io/second-Junior-Brother/pen/bGJRBgq)

### Steps to reproduce

Access the link directly and cannot see the generated watermark.

### What is Expected?

It is hoped that the component can directly display the watermark

### What is actually happening?

It is hoped that the component can directly display the watermark

### Additional comments

_(empty)_

**Comment by zeyongTsai** [comment]
![image](https://github.com/element-plus/element-plus/assets/8591261/14d9bf12-c998-4ab0-883c-f3edf23d272f)

syntax error

**Comment by happy-lsl** [comment]
> ![图像](https://private-user-images.githubusercontent.com/8591261/317096911-14d9bf12-c998-4ab0-883c-f3edf23d272f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTEyODIsIm5iZiI6MTcxMTUxMDk4MiwicGF0aCI6Ii84NTkxMjYxLzMxNzA5NjkxMS0xNGQ5YmYxMi1jOTk4LTRhYjAtODgzYy1mM2VkZjIzZDI3MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDM0MzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc0YzVmNDhiZGU0NWE1YWM2MWI1YzgyY2ZiZWMwMWFlY2Y1NTI5NDZmNzU0MDhmMjg4ZWU0ZTY5NjU4OWZmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eKo6Ob_5gycL-bce0Mr-tBAYgY8rxVPuhh8Js4HjesI)
> 
> 语法错误

even if the test machine directly accesses the official website, the watermark will not be displayed. ：https://element-plus.org/zh-CN/component/watermark.html#watermark
