### ISSUE TITLE
[Component] [cascader, date-picker] 表单使用多个弹出层，数据叠加

### ISSUE THREAD

**Issue by m120703897** [element-plus/element-plus#16240]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.6.2`
- Browser / OS: `Chrome 123.0.6312.58 / Mac OS 14.2.1`
- Build Tool: `Nuxt`

### Related Component

- `el-cascader`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICAgICA8ZWwtZm9ybSA6bW9kZWw9XCJpbmZvRm9ybVwiIGxhYmVsLXdpZHRoPVwiYXV0b1wiIGxhYmVsLXBvc2l0aW9uPVwidG9wXCI+XG4gICAgXG4gICAgICAgICAgICA8ZWwtZm9ybS1pdGVtIHByb3A9XCJhcmVhX2NvZGVcIj5cbiAgICAgICAgICAgICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cIml0ZW0tc3BhblwiPuWcsOWMujwvc3Bhbj5cbiAgICAgICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJ3aWR0aDoxMDAlXCI+XG4gICAgICAgICAgICAgICAgICAgIDxlbC1jYXNjYWRlciBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeWcsOWMulwiIHYtbW9kZWw9XCJpbmZvRm9ybS5hcmVhX2NvZGVcIiA6b3B0aW9ucz1cImNpdHlEYXRhU3JvdWNlXCIgLz5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIFxuICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuaIkOeri+aXtumXtFwiIHByb3A9XCJzdGFydF9kYXRlXCI+XG4gICAgICAgICAgICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJpdGVtLXNwYW5cIj7miJDnq4vml7bpl7Q8L3NwYW4+XG4gICAgICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICBcbiAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPVwid2lkdGg6MTAwJVwiPlxuICAgICAgICAgICAgICAgICAgICA8ZWwtY29uZmlnLXByb3ZpZGVyIGNsYXNzPVwiY3VzdG9tLWRhdGUtcGlja2VyXCIgOmxvY2FsZT1cInpoQ25cIj4gXG4gICAgICAgICAgICAgICAgICAgICAgICA8ZWwtZGF0ZS1waWNrZXIgc3R5bGU9XCJ3aWR0aDoxMDAlXCIgdi1tb2RlbD1cImluZm9Gb3JtLnN0YXJ0X2RhdGVcIiB0eXBlPVwiZGF0ZVwiIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oup5oiQ56uL5pe26Ze0XCIgIC8+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIFxuICAgICAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgXG4gICAgICAgIDwvZWwtZm9ybT5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4gIFxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB6aENuIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9sb2NhbGUvbGFuZy96aC1jbidcblxuaW1wb3J0IHsgRWxGb3JtLCBFbEZvcm1JdGVtLEVsRGF0ZVBpY2tlcixFbENvbmZpZ1Byb3ZpZGVyLEVsQ2FzY2FkZXJ9IGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmNvbnN0IGNpdHlEYXRhU3JvdWNlID0gcmVmKFtcbiAge1xuICAgIFwibGFiZWxcIjogXCLljJfkuqzluIJcIixcbiAgICBcInZhbHVlXCI6IFwiMTEwMDAwXCIsXG4gICAgXCJjaGlsZHJlblwiOiBbXG4gICAgICB7XG4gICAgICAgIFwibGFiZWxcIjogXCLluILovpbljLpcIixcbiAgICAgICAgXCJ2YWx1ZVwiOiBcIjExMDEwMFwiXG4gICAgICB9XG4gICAgXVxuICB9LFxuICB7XG4gICAgXCJsYWJlbFwiOiBcIuWkqea0peW4glwiLFxuICAgIFwidmFsdWVcIjogXCIxMjAwMDBcIixcbiAgICBcImNoaWxkcmVuXCI6IFtcbiAgICAgIHtcbiAgICAgICAgXCJsYWJlbFwiOiBcIuW4gui+luWMulwiLFxuICAgICAgICBcInZhbHVlXCI6IFwiMTIwMTAwXCJcbiAgICAgIH1cbiAgICBdXG4gIH1cbl0pO1xuXG5cbi8vIOihqOWNleaVsOaNrlxuY29uc3QgaW5mb0Zvcm0gPSByZWYoe1xuICAgIGFyZWE6JycsXG4gICAgYXJlYV9jb2RlOicnLFxuICAgIHN0YXJ0X2RhdGU6JycsXG4gIH1cbilcblxuPC9zY3JpcHQ+XG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点击地区级联选择器，弹出层 出现了 日期选择与地区选择的数据， 但是点击日期选择器，也是同样的问题。 

### What is Expected?

单击地区只弹出地区选择的数据，
单击日期只弹出日期选择的数据
单击地区框，不选择数据然后单击日期框，选择器不弹出了。

### What is actually happening?

单击地区弹出地区选择的数据+日期选择的数据
单击日期弹出日期选择的数据+地区选择的数据
单击地区框，不选择地区数据，然后单击日期框，应该弹出日期选择器

### Additional comments

如果时我写错了，请写一份简单的表单，数据只包含，日期选择与级联选择器， 发送到我的邮箱(120703897@qq.com)谢谢

**Comment by m120703897** [comment]
在我的的编辑器里也是同样的代码，但是展示的却不一样。如附件
<img width="411" alt="截屏2024-03-26 09 39 01" src="https://github.com/element-plus/element-plus/assets/9362483/2930f416-6b00-417f-9d9f-81c49be73624">

**Comment by m120703897** [comment]
没人解决？

**Comment by tolking** [comment]
为什么不看看文档 [服务端渲染 (SSR)](https://element-plus.org/zh-CN/guide/ssr.html)
