### ISSUE TITLE
[Component] [table] vue-router的RouterView使用KeepAlive后，切换router会出现el-table的滚动条和滚动位置不匹配的情况

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#16257]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/devbox/test-el-table-fj684z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu88xt6t0007356ghh95bxe2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu88xt6s0002356g1k7z6mzg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu88xt6s0004356gbwe7okyp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu88xt6t0006356gn2kqb95a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu88xt6s0002356g1k7z6mzg%2522%253A%257B%2522id%2522%253A%2522clu88xt6s0002356g1k7z6mzg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu88xt6t0006356gn2kqb95a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu88xt6t0005356g6uuvogbg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522clu88xt6t0006356gn2kqb95a%2522%252C%2522activeTabId%2522%253A%2522clu88xt6t0005356g6uuvogbg%2522%257D%252C%2522clu88xt6s0004356gbwe7okyp%2522%253A%257B%2522id%2522%253A%2522clu88xt6s0004356gbwe7okyp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu88xt6s0003356g7i97bpwc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu88xt6s0003356g7i97bpwc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1.点击About
2.拖动el-table的横向滚动条
3.切换到Home再切换回去About
4.可以看到滚动条和滚动位置不匹配了

### What is Expected?

滚动条和滚动位置一致

### What is actually happening?

滚动条和滚动位置不一致

### Additional comments

_(empty)_

**Comment by btea** [comment]
The link provided does not appear to be valid.

**Comment by hzf-666** [comment]
https://github.com/element-plus/element-plus/assets/55825301/e1963663-3f7e-413a-882d-f26434afb8de

我这边是可以复现出来的

**Comment by btea** [comment]
![image](https://github.com/element-plus/element-plus/assets/24516654/e0641557-65bd-4514-a9bf-74052d849bb6)

**Comment by hzf-666** [comment]
https://codesandbox.io/p/devbox/test-el-table-fj684z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu88xt6t0007356ghh95bxe2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu88xt6s0002356g1k7z6mzg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu88xt6s0004356gbwe7okyp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu88xt6t0006356gn2kqb95a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu88xt6s0002356g1k7z6mzg%2522%253A%257B%2522id%2522%253A%2522clu88xt6s0002356g1k7z6mzg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu88xt6t0006356gn2kqb95a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu88xt6t0005356g6uuvogbg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522clu88xt6t0006356gn2kqb95a%2522%252C%2522activeTabId%2522%253A%2522clu88xt6t0005356g6uuvogbg%2522%257D%252C%2522clu88xt6s0004356gbwe7okyp%2522%253A%257B%2522id%2522%253A%2522clu88xt6s0004356gbwe7okyp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu88xt6s0003356g7i97bpwc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu88xt6s0003356g7i97bpwc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
