### ISSUE TITLE
[TypeScript] [All] Component PascalCase naming convention not working or not recognized in WebStorm. 组件大写驼峰提示在webstorm内不生效

### ISSUE THREAD

**Issue by DEAN-Cherry** [element-plus/element-plus#16259]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter)

### Steps to reproduce

使用上述链接提供的仓库，装好依赖后随便在某一个文件下输入El，只会提示src/components.d.ts内声明的组件类型，当然web-type.json的小写横线组件提示是正常的，组件指向路径也是正常的。我将element-plus/global.ts内的内容全部复制到src目录下就可以正常获得所有组件的提示，似乎是webstorm识别不了element-plus/gobal.ts。隔壁arco-design-vue是把声明文件放到es目录下就正常了，这个问题很神奇，我是webstorm最新版本

### What is Expected?
Get Component hints by Pascal Cases
正常获得所有组件的大写驼峰组件提示

![316986939-71d8a510-a46b-43bc-b42f-75793a66227e](https://github.com/element-plus/element-plus/assets/76607677/d5f8f797-8909-4a7d-a645-66ce9a03cdf3)

### What is actually happening?
Only works in camel cases
只能获取到src/components.d.ts内声明的组件，放src外还不行

![图片](https://github.com/element-plus/element-plus/assets/76607677/5865bfcb-5773-43fe-b88d-07391bd464fa)

#### Related Issue
https://github.com/element-plus/element-plus/issues/13117

**Comment by DEAN-Cherry** [comment]
> Maybe you could use the Volar extension.

Thanks for your reply, but I am using `WebStorm` and as far as I know it is `VSCode` that uses `Volar extension` 
Dose it means it only works in `VSCode`？

**Comment by btea** [comment]
There is currently no Webstorm in my local area, but Webstorm should support Volar. refer to https://blog.jetbrains.com/webstorm/2023/05/webstorm-2023-2-eap2/#volar_support_for_vue

**Comment by DEAN-Cherry** [comment]
> There is currently no Webstorm in my local area, but Webstorm should support Volar. refer to https://blog.jetbrains.com/webstorm/2023/05/webstorm-2023-2-eap2/#volar_support_for_vue

I managed to use `Volar` or `Vue Language Server` in `WebStorm` but still cannot get hints in PascalCase :(.
![image](https://github.com/element-plus/element-plus/assets/76607677/234a4c87-7181-4e1b-b068-08e76db1fe59)

**Comment by btea** [comment]
@kooriookami Can you help verify this issue?

**Comment by kooriookami** [comment]
![image](https://github.com/element-plus/element-plus/assets/38392315/c0a41e39-8964-4d52-80ff-eb387804914d)
I can see all the components.

**Comment by DEAN-Cherry** [comment]
> ![image](https://private-user-images.githubusercontent.com/38392315/317612324-c0a41e39-8964-4d52-80ff-eb387804914d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjY0MTIsIm5iZiI6MTcxMTYyNjExMiwicGF0aCI6Ii8zODM5MjMxNS8zMTc2MTIzMjQtYzBhNDFlMzktODk2NC00ZDUyLTgwZmYtZWIzODc4MDQ5MTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDExNDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTE5NTg2MzljMmJhYTk4N2EwYmRlNmJiZTU3ZmFhYmNlNTk1MTA5ZDllNjUwNTBkYTI0NzcxZTIyYjYzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6zH0KrtvsLpchk-Ro9VDMxuyXI7ntK9DwsaOqweEi8) I can see all the components.


Wow, are u using this template https://github.com/element-plus/element-plus-vite-starter?

**Comment by kooriookami** [comment]
Nope, I just install a vite project. Nothing else~

**Comment by DEAN-Cherry** [comment]
> Nope, I just install a vite project. Nothing else~

Thanks, I will try later to find out what causes the difference.
