### ISSUE TITLE
[Bug Report] After NPM install element-plus, the TS declaration file is missing in the element-plus file package

### ISSUE THREAD

**Issue by hjyyang** [element-plus/element-plus#1625]
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
mac/Google Chrome 88.0.4324.150

### Vue version
3.0.0

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN?repo=element-plus

### Steps to reproduce
npm install element-plus -save
Look at the element-plus package in the node_modules directory, where the ts declaration file is missing

### What is Expected?
The TS declaration file is behind the Install Element-Plus package

### What is actually happening?
There is no TS declaration file after the install element-plus package

**Comment by YunYouJun** [comment]
Can be reproduced. I temporarily use `1.0.2-beta.32` to solve this problem.

**Comment by develar** [comment]
Yes, 1.0.2-beta.34 is broken because no typings :(

**Comment by xiaohulu** [comment]
me tooo

**Comment by hjyyang** [comment]
@YunYouJun Yes, it is also possible to use version 1.0.2-beta.33. I have a TS declaration file when I backtrack to version 1.0.2-beta.33 after a problem

**Comment by Brolly0204** [comment]
no TS declaration file  "element-plus": "^1.0.2-beta.34",

**Comment by Brolly0204** [comment]
How to solve it now

**Comment by hjyyang** [comment]
@Brolly0204 Version falls back to ^1.0.2-beta.33

**Comment by yifred777** [comment]
Same issue here, everything is ok when downgrading to beta 33 or 32, but not for beta 34.

**Comment by iamkun** [comment]
fixed in `1.0.2-beta.35`
