### ISSUE TITLE
[Component] [dialog] 在 dialog中 预览图片时按下esc按键，会同时将图片预览和dialog关闭

### ISSUE THREAD

**Issue by D06F6E67** [element-plus/element-plus#16264]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwidGV4dFwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSB0cnVlXCJcbiAgICA+Y2xpY2sgdG8gb3BlbiB0aGUgRGlhbG9nPC9lbC1idXR0b25cbiAgPlxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCIzMCVcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwic2hvd0ltYWdlID0gdHJ1ZVwiXG4gICAgPmNsaWNrIHRvIG9wZW4gdGhlIEltYWdlPC9lbC1idXR0b25cbiAgPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkaWFsb2ctZm9vdGVyXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIlxuICAgICAgICAgID5Db25maXJtPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC9zcGFuPlxuICAgIDwvdGVtcGxhdGU+XG5cbiAgPC9lbC1kaWFsb2c+XG4gIDxlbC1pbWFnZS12aWV3ZXIgdi1pZj1cInNob3dJbWFnZVwiIDpoaWRlLW9uLWNsaWNrLW1vZGFsPVwidHJ1ZVwiICA6dXJsLWxpc3Q9XCJbJ2h0dHBzOi8vZ2ltZzIuYmFpZHUuY29tL2ltYWdlX3NlYXJjaC9zcmM9aHR0cCUzQSUyRiUyRnBpYzMuemhpbWcuY29tJTJGdjItNWY2NzAzOTQ0N2E4NDA2MGE2Njg4N2RjZmJmMjFkNzJfci5qcGcmcmVmZXI9aHR0cCUzQSUyRiUyRnBpYzMuemhpbWcuY29tJmFwcD0yMDAyJnNpemU9Zjk5OTksMTAwMDAmcT1hODAmbj0wJmc9MG4mZm10PWF1dG8/c2VjPTE2NTI1ODUwMzAmdD1hYTQ1ODdmYzI3MDI3YzEwNmM5M2M5ODhmZjAyZDJhNiddXCIgQGNsb3NlPVwic2hvd0ltYWdlID0gZmFsc2VcIi8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3Qgc2hvd0ltYWdlID0gcmVmKGZhbHNlKVxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoZG9uZTogKCkgPT4gdm9pZCkgPT4ge1xuICBkb25lKClcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kaWFsb2ctZm9vdGVyIGJ1dHRvbjpmaXJzdC1jaGlsZCB7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1.点击click to open the Dialog
2.点击click to open the Image
3.按下键盘esc按键

### What is Expected?

关闭图片预览，不关闭dialog弹窗

### What is actually happening?

同时关闭了图片预览和弹窗

### Additional comments

目前使用了如下方法处理，有没有更好的方法
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwidGV4dFwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSB0cnVlXCJcbiAgICA+Y2xpY2sgdG8gb3BlbiB0aGUgRGlhbG9nPC9lbC1idXR0b25cbiAgPlxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCIzMCVcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwic2hvd0ltYWdlID0gdHJ1ZVwiXG4gICAgPmNsaWNrIHRvIG9wZW4gdGhlIEltYWdlPC9lbC1idXR0b25cbiAgPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkaWFsb2ctZm9vdGVyXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIlxuICAgICAgICAgID5Db25maXJtPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC9zcGFuPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZGlhbG9nPlxuICA8ZWwtaW1hZ2Utdmlld2VyIHYtaWY9XCJzaG93SW1hZ2VcIiA6aGlkZS1vbi1jbGljay1tb2RhbD1cInRydWVcIiAgOnVybC1saXN0PVwiWydodHRwczovL2dpbWcyLmJhaWR1LmNvbS9pbWFnZV9zZWFyY2gvc3JjPWh0dHAlM0ElMkYlMkZwaWMzLnpoaW1nLmNvbSUyRnYyLTVmNjcwMzk0NDdhODQwNjBhNjY4ODdkY2ZiZjIxZDcyX3IuanBnJnJlZmVyPWh0dHAlM0ElMkYlMkZwaWMzLnpoaW1nLmNvbSZhcHA9MjAwMiZzaXplPWY5OTk5LDEwMDAwJnE9YTgwJm49MCZnPTBuJmZtdD1hdXRvP3NlYz0xNjUyNTg1MDMwJnQ9YWE0NTg3ZmMyNzAyN2MxMDZjOTNjOTg4ZmYwMmQyYTYnXVwiIEBjbG9zZT1cInNob3dJbWFnZSA9IGZhbHNlXCIvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IHNob3dJbWFnZSA9IHJlZihmYWxzZSlcbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmU6ICgpID0+IHZvaWQpID0+IHtcbiAgaWYoIWRvY3VtZW50LmdldEVsZW1lbnRzQnlDbGFzc05hbWUoJ2VsLWltYWdlLXZpZXdlcl9fd3JhcHBlcicpWzBdKXtcbiAgICBkb25lKClcbiAgfVxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmRpYWxvZy1mb290ZXIgYnV0dG9uOmZpcnN0LWNoaWxkIHtcbiAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==

**Comment by kankan-web** [comment]
```
const handleClose = (done: () => void) => {
  if(!showImage){
    done()
  }
}
```
如果图片处于展示状态也就是showImage：false，按esc时，你就不执行done()

**Comment by btea** [comment]
这是业务相关的逻辑问题，不是组件问题。可按照 @kankan-web 所提供的方法自行处理，我将关闭这个issue，有问题可继续在下方评论。
