### ISSUE TITLE
[Component] [cascader] 级联选择器

### ISSUE THREAD

**Issue by duanghaha123** [element-plus/element-plus#16263]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `谷歌 / windows`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/edit/dev/docs/examples/cascader/basic.vue)

### Steps to reproduce

自定义级联选择器无数据部分，失效

### What is Expected?

自定义级联选择器无数据部分，可以自定义；

### What is actually happening?

自定义级联选择器无数据部分，失效

### Additional comments

_(empty)_

**Comment by btea** [comment]
You can use the `empty` slot to customize content without data. https://element-plus.org/en-US/component/cascader.html#cascader-slots

**Comment by duanghaha123** [comment]
> You can use the `empty` slot to customize content without data. https://element-plus.org/en-US/component/cascader.html#cascader-slots



> You can use the `empty` slot to customize content without data. https://element-plus.org/en-US/component/cascader.html#cascader-slots

empty   这个插槽失效了，加上了根本没效果

**Comment by btea** [comment]
嗯，是的。现在的 empty 插槽是在进行过滤的时候没有匹配到选项时用的。

**Comment by huanlirui** [comment]
无法修改默认的empty 文案吗？这功能2025年了还没有
