### ISSUE TITLE
[Component] [table-column] el-table-column 默认插槽数据出现错误

### ISSUE THREAD

**Issue by 2420479972** [element-plus/element-plus#16265]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `macOS14.1.1`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIuaXpeacn1wiPlxuICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPiB7eyBzY29wZSB9fSA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup>
interface User {
  date: string
  name: string
  address: string
}

const handleEdit = (index: number, row: User) => {
  console.log(index, row)
}
const handleDelete = (index: number, row: User) => {
  console.log(index, row)
}

const tableData: User[] = [
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>

<template>
<el-table :data="tableData" style="width: 100%">
    <el-table-column label="Date" prop="date" width="180">
      <template #default="scope">
        {{ JSON.stringify(scope) }}
      </template>
    </el-table-column>
  </el-table>
</template>
```

### What is Expected?

默认插槽获取到scope的值

### What is actually happening?

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'vnode' -> object with constructor 'Object'
    --- property 'component' closes the circle
    at JSON.stringify (<anonymous>)
    at toDisplayString (runtime-dom.esm-browser.js:264:154)
    at <anonymous>:56:28
    at Proxy.renderFnWithContext (runtime-dom.esm-browser.js:2320:13)
    at C.type.C.renderCell (event.ts:5:64)
    at E (event.ts:5:64)
    at event.ts:5:64
    at Proxy.map (<anonymous>)
    at C (event.ts:5:64)
    at wrappedRowRender (event.ts:5:64)

### Additional comments

_(empty)_

**Comment by kankan-web** [comment]
```
<el-table :data="tableData" style="width: 100%">
    <el-table-column label="Date" prop="date" width="180">
      <template #default="scope">
        {{ scope.row }}
      </template>
    </el-table-column>
  </el-table>
```
这不是可以获取到对应的行值嘛

**Comment by 2420479972** [comment]
{{ JSON.stringify(scope) }} 我这样输出他就出现错了 我不太清楚为什么

**Comment by 2420479972** [comment]
我有点疑惑 可否解答一下 满足一下我的好奇心 可以吗 拜托拜托

**Comment by kooriookami** [comment]
说明 scope 是不可被 stringify 的
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#%E5%85%B3%E4%BA%8E%E5%BA%8F%E5%88%97%E5%8C%96%E5%BE%AA%E7%8E%AF%E5%BC%95%E7%94%A8%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by 2420479972** [comment]
好的 我明白了。非常感谢解答
