### ISSUE TITLE
[Component] [input-number] inputNumber组件可以输入 ++、--、++e--等非法数字

### ISSUE THREAD

**Issue by JZLeung** [element-plus/element-plus#16267]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtXCIgOm1pbj1cIjFcIiA6bWF4PVwiMTBcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCIgQGtleXVwLm5hdGl2ZT1cIm9uS2V5dXBcIiAvPlxuICA8aDE+SW5wdXQ6IHt7bnVtfX08L2gxPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbnVtID0gcmVmKDEpXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsdWU6IG51bWJlcikgPT4ge1xuICBjb25zb2xlLmxvZyh2YWx1ZSlcbn1cbmNvbnN0IG9uS2V5dXAgPSAoZSkgPT4ge1xuICBjb25zb2xlLmxvZyhlLmtleSwgbnVtLnZhbHVlKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1、输入框中输入1++、1--、1+e-2
2、查看组件上显示的值
3、获取v-model的值

### What is Expected?

2、组件显示为空
3、v-model的值为空

### What is actually happening?

2、组件上显示1++、1--、1+e-2
3、v-model的值为空

### Additional comments

建议组件上显示的文本和值表现一致

**Comment by chenxch** [comment]
目前表现与原生input type=number一致。
