### ISSUE TITLE
When dynamically generating el-table columns, some data will cause the website to fall into an infinite loop

### ISSUE THREAD

**Issue by chenkai0520** [element-plus/element-plus#1626]
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
Mac Google Chrome 版本 89.0.4389.82

### Vue version
3.0.7

### Reproduction Link
https://github.com/chenkai0520/vue-element-plus-issue/blob/master/src/App.vue

### Steps to reproduce
动态生成el-table 列时某些数据会导致页面卡死
重现问题代码仓库文件
```html
<template>
    <el-table
      :data="dataInfo.rows"
      size='mini'
      border
      height="100%"
      style="width: 100%;">
      <el-table-column  v-for="(value, key) in dataInfo.columns" :key="key" :prop="key">
        <template #header>
          <div>{{key}}</div>
          <div>{{value}}</div>
        </template>
      </el-table-column>
    </el-table>
</template>
```
https://github.com/chenkai0520/vue-element-plus-issue/blob/master/src/App.vue

如果用slot的方式是正常的，
```html
<template #default="scope">
    <div>{{scope.row[key]}}</div>
</template>
```
此外如果不用单文件组件的方式是正常的
https://jsfiddle.net/aq4jfg19/

问题似乎是由`prop` 触发的

### What is Expected?
无

### What is actually happening?
动态生成el-table 列时某些数据会陷入某个死循环

**Comment by chenkai0520** [comment]
这个问题似乎是由数据中的`cp: [84.9023, 42.148]` 引起的

**Comment by justwiner** [comment]
I tested the [code](https://github.com/chenkai0520/vue-element-plus-issue/blob/master/src/App.vue) you provided in the local environment, and it seems that there is no recurrence problem.

**Comment by chenkai0520** [comment]
@justwiner 
It Does not work on my computer, my OS/Browsers version is `Mac Google Chrome 版本 89.0.4389.82` ,
Looking at the log, it seems that the program has fallen into an infinite loop and keeps printing warning
![https://s3.ax1x.com/2021/03/15/6B6xln.png](https://s3.ax1x.com/2021/03/15/6B6xln.png)

**Comment by HuanDoan** [comment]
I have the same issue, even it causes a recursive updates error when I update table data props by using vuex.

![image](https://user-images.githubusercontent.com/20861694/111104568-927fef80-8583-11eb-871c-47ff0959a5b6.png)

Warning infinity
![image](https://user-images.githubusercontent.com/20861694/111104611-a3c8fc00-8583-11eb-8341-3faa6dcc2a19.png)

```javascript
<el-table
        :data="media"
        row-key="id"
        border
        style="width: 100%; margin-top: 20px;">
        <el-table-column
            prop="name"
            label="Name">
        </el-table-column>
        <el-table-column
            prop="type"
            label="Type"
            width="120">
        </el-table-column>
        <el-table-column
            prop="extension"
            label="Extension">
        </el-table-column>
    </el-table>
```

```javascript
computed: {
        media() {
            return this.$store.getters['assetModule/assets'];
        }
    },
```
