### ISSUE TITLE
[Component] [checkbox, select] The checkbox inside dropdown is not checking. 

### ISSUE THREAD

**Issue by sucheep-s** [element-plus/element-plus#16270]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.14`
- Element Plus Version: `2.4.3`
- Browser / OS: `Chrome 123.0.6312.59`
- Build Tool: `Nuxt`

### Related Component

- `el-checkbox`
- `el-select`

### Reproduction Link

[Link]()

### Steps to reproduce

1. Copy the code from https://element-plus.org/en-US/component/select.html#header-of-the-dropdown
2. Add further imports,
```
import {
  ElSelect,
  ElOption,
  ElCheckbox,
} from "element-plus";
```
3. The full of the code will be
```
<template>
    <el-select
    v-model="value"
    multiple
    clearable
    collapse-tags
    placeholder="Select"
    popper-class="custom-header"
    :max-collapse-tags="1"
    style="width: 240px"
  >
    <template #header>
      <el-checkbox
        v-model="checkAll"
        :indeterminate="indeterminate"
        @change="handleCheckAll"
      >
        All
      </el-checkbox>
    </template>
    <el-option
      v-for="item in cities"
      :key="item.value"
      :label="item.label"
      :value="item.value"
    />
    </el-select>
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue'

import type { CheckboxValueType } from 'element-plus'

import {
  ElSelect,
  ElOption,
  ElCheckbox,
} from "element-plus";

const checkAll = ref(false)
const indeterminate = ref(false)
const value = ref<CheckboxValueType[]>([])
const cities = ref([
  {
    value: 'Beijing',
    label: 'Beijing',
  },
  {
    value: 'Shanghai',
    label: 'Shanghai',
  },
  {
    value: 'Nanjing',
    label: 'Nanjing',
  },
  {
    value: 'Chengdu',
    label: 'Chengdu',
  },
  {
    value: 'Shenzhen',
    label: 'Shenzhen',
  },
  {
    value: 'Guangzhou',
    label: 'Guangzhou',
  },
])

watch(value, (val) => {
  if (val.length === 0) {
    checkAll.value = false
    indeterminate.value = false
  } else if (val.length === cities.value.length) {
    checkAll.value = true
    indeterminate.value = false
  } else {
    indeterminate.value = true
  }
})

const handleCheckAll = (val: CheckboxValueType) => {
  indeterminate.value = false
  if (val) {
    value.value = cities.value.map((_) => _.value)
  } else {
    value.value = []
  }
}
</script>

<style lang="scss">
.custom-header {
  .el-checkbox {
    display: flex;
    height: unset;
  }
}
</style>
```
4.excute
5.check on the checkbox, all values has selected/unselected successfully. But the checkbox itself didn't check/uncheck

### What is Expected?

Checkbox inside the el-select can check/uncheck normally.

### What is actually happening?

The checkbox inside the el-select doesn't change.

### Additional comments

Result Video: https://jumpshare.com/embed/oMmIAJQkBNKgNaVW6ZO6

**Comment by sucheep-s** [comment]
https://github.com/element-plus/element-plus/assets/8954519/abc378c5-5243-4aeb-9f06-8d21438df47e

Adding the result video in case the url is broken.

**Comment by btea** [comment]
It looks normal to me. [link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgbXVsdGlwbGVcbiAgICBjbGVhcmFibGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgIHBvcHBlci1jbGFzcz1cImN1c3RvbS1oZWFkZXJcIlxuICAgIDptYXgtY29sbGFwc2UtdGFncz1cIjFcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA6dGVsZXBvcnRlZD1cImZhbHNlXCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjaGVhZGVyPlxuICAgICAgPGVsLWNoZWNrYm94XG4gICAgICAgIHYtbW9kZWw9XCJjaGVja0FsbFwiXG4gICAgICAgIDppbmRldGVybWluYXRlPVwiaW5kZXRlcm1pbmF0ZVwiXG4gICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGVja0FsbFwiXG4gICAgICA+XG4gICAgICAgIEFsbFxuICAgICAgPC9lbC1jaGVja2JveD5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPGVsLWNoZWNrYm94XG4gICAgICAgIHYtbW9kZWw9XCJjaGVja0FsbFwiXG4gICAgICAgIDppbmRldGVybWluYXRlPVwiaW5kZXRlcm1pbmF0ZVwiXG4gICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGVja0FsbFwiXG4gICAgICA+XG4gICAgICAgIEFsbFxuICAgICAgPC9lbC1jaGVja2JveD5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBjaXRpZXNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIHdhdGNoIH0gZnJvbSAndnVlJ1xuXG5pbXBvcnQgdHlwZSB7IENoZWNrYm94VmFsdWVUeXBlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBjaGVja0FsbCA9IHJlZihmYWxzZSlcbmNvbnN0IGluZGV0ZXJtaW5hdGUgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZjxDaGVja2JveFZhbHVlVHlwZVtdPihbXSlcbmNvbnN0IGNpdGllcyA9IHJlZihbXG4gIHtcbiAgICB2YWx1ZTogJ0JlaWppbmcnLFxuICAgIGxhYmVsOiAnQmVpamluZycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ1NoYW5naGFpJyxcbiAgICBsYWJlbDogJ1NoYW5naGFpJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnTmFuamluZycsXG4gICAgbGFiZWw6ICdOYW5qaW5nJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnQ2hlbmdkdScsXG4gICAgbGFiZWw6ICdDaGVuZ2R1JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnU2hlbnpoZW4nLFxuICAgIGxhYmVsOiAnU2hlbnpoZW4nLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdHdWFuZ3pob3UnLFxuICAgIGxhYmVsOiAnR3Vhbmd6aG91JyxcbiAgfSxcbl0pXG5cbndhdGNoKHZhbHVlLCAodmFsKSA9PiB7XG4gIGlmICh2YWwubGVuZ3RoID09PSAwKSB7XG4gICAgY2hlY2tBbGwudmFsdWUgPSBmYWxzZVxuICAgIGluZGV0ZXJtaW5hdGUudmFsdWUgPSBmYWxzZVxuICB9IGVsc2UgaWYgKHZhbC5sZW5ndGggPT09IGNpdGllcy52YWx1ZS5sZW5ndGgpIHtcbiAgICBjaGVja0FsbC52YWx1ZSA9IHRydWVcbiAgICBpbmRldGVybWluYXRlLnZhbHVlID0gZmFsc2VcbiAgfSBlbHNlIHtcbiAgICBpbmRldGVybWluYXRlLnZhbHVlID0gdHJ1ZVxuICB9XG59KVxuXG5jb25zdCBoYW5kbGVDaGVja0FsbCA9ICh2YWw6IENoZWNrYm94VmFsdWVUeXBlKSA9PiB7XG4gIGluZGV0ZXJtaW5hdGUudmFsdWUgPSBmYWxzZVxuICBpZiAodmFsKSB7XG4gICAgdmFsdWUudmFsdWUgPSBjaXRpZXMudmFsdWUubWFwKChfKSA9PiBfLnZhbHVlKVxuICB9IGVsc2Uge1xuICAgIHZhbHVlLnZhbHVlID0gW11cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5jdXN0b20taGVhZGVyIC5lbC1jaGVja2JveCB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBoZWlnaHQ6IHVuc2V0O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by sucheep-s** [comment]
If I move the el-checkbox outside the el-select's scope. the check/uncheck is working normally

**Comment by btea** [comment]
Please provide an example using the link above.
