### ISSUE TITLE
[bug report] Using El Popover in V-for

### ISSUE THREAD

**Issue by Dpuer** [element-plus/element-plus#1629]
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
win10/chrome89

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/yuyangw/pen/ExNrLvb

### Steps to reproduce
1.v-for中使用el-popover
2.快速切换popover显示

### What is Expected?
前一个popover直接消失不要等待

### What is actually happening?
前一个popover会有一个渐出过程

**Comment by Ryan2128** [comment]
This is the correct behavior and will not change it.

**Comment by Ryan2128** [comment]
> 我理解该行为的当前表现，但如果我有预期希望没有过程直接消失，是否可以提供一些额外的 方法 或配置

Add `popper-class`, and cover the style of `popper`.

```
<template>
  <el-popover
    popper-class="test"
    v-for="item of list"
    :key="item.id"
    placement="bottom"
    title="标题"
    :width="200"
    trigger="click"
    content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。"
  >
    <template #reference>
      <el-button>{{ item.msg }}</el-button>
    </template>
  </el-popover>
</template>

<script>
export default {
  data() {
    return {
      list: [
        {
          id:1,
          msg:'Hello Element Plus1',
        },
        {
          id:2,
          msg:'Hello Element Plus2',
        },
        {
          id:3,
          msg:'Hello Element Plus3',
        },
      ],
    }
  },
}
</script>

<style>
.test.fade-in-linear-leave-active {
  transition: none;
}
</style>
```

**Comment by Dpuer** [comment]
> .test.fade-in-linear-leave-active {
>   transition: none;
> }

我按照你说的做了，但是好像并没有效果
https://codepen.io/yuyangw/pen/ExNrLvb

**Comment by Ryan2128** [comment]
> 我按照你说的做了，但是好像并没有效果
> https://codepen.io/yuyangw/pen/ExNrLvb

Transition has been removed. Can't do more about it outside the component, right? @JeremyWuuuuu
