### ISSUE TITLE
where is index.d.ts since 1.0.2-beta.34 for TS

### ISSUE THREAD

**Issue by serloi** [element-plus/element-plus#1631]
Hello There!

I update this morning to beta 34, and I can't transpile my project because there is no index.d.ts for TypeScript

node_modules\element-plus\lib\index.d.ts exists for beta 33, and is not here for beta 34, is it normal ?

[EDIT] Sorry, same subject as #1625 ...

**Comment by JeremyWuuuuu** [comment]
We had some build issue, sorry for that, I am making fix on it. Please use `1.0.2-33` for a while. I will rollout a new release with `1.0.2-35` to fix it.
