### ISSUE TITLE
[Bug Report] error: [ vite:dep-scan ] Failed to resolve entry for package "element-plus". The package may have incorrect main/module/exports specified in its  package.json .

### ISSUE THREAD

**Issue by Lexokid** [element-plus/element-plus#1632]
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
window10 1909

### Vue version
3.0.7

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/package.json

### Steps to reproduce
"vite": "^2.0.5"
"esbuild": "^0.9.2"
node: v14.5.0

使用vite api构建项目
在项目根目录新建文件 build.js：
const { createServer } = require('vite')
  ; (async () => {
    const server = await createServer()
    await server.listen()
  })()

运行 node build.js

启动时报 error: [vite:dep-scan] Failed to resolve entry for package "element-plus". The package may have incorrect main/module/exports specified in its package.json.
在路径 node_modules\element-plus\package.json 发现package.json，里面有配置"module": "lib/index.esm.js"，实际目录下没有该文件，尝试修改为"es/index.js"可以正常运行

### What is Expected?
no error

### What is actually happening?
error: [vite:dep-scan] Failed to resolve entry for package "element-plus". The package may have incorrect main/module/exports specified in its package.json.

**Comment by citrucn** [comment]
我也是这样，退回33版本就没事

**Comment by llushikang** [comment]
我也是，希望快点修复

**Comment by TothingWay** [comment]
I have the same problem

**Comment by tolking** [comment]
miss  `lib/index.esm.js` and `lib/index.d.ts`

**Comment by Ryan2128** [comment]
Already fixed in `1.0.2-beta.35`.

**Comment by Sharlaan** [comment]
![image](https://user-images.githubusercontent.com/2692027/115126445-58b16700-9fcf-11eb-91ae-41391e128583.png)
Looks like still same problem, even worse since the node_modules/element-plus directory is now almost empty (contain only the package.json)

Node 15.4
Vue 3.0.11
Vite 2.1.5
Element-Plus 1.0.2 beta 40
