### ISSUE TITLE
[Bug Report] when use h render el-switch in el-collapse-item, el-switch value bind fail

### ISSUE THREAD

**Issue by 874435441** [element-plus/element-plus#1634]
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
macos chorme 88.0.4324.192

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/pen/?template=wvoOgvP

### Steps to reproduce
click "test" open collapse, click inner switch it do not work normal. As a contrast, outer switch work normal.

### What is Expected?
inner switch can work normal,

### What is actually happening?
inner switch do not  work normal, i try el-input ,it seems has the same error

**Comment by JeremyWuuuuu** [comment]
Bug confirmed. Seems like the inner components only gets updated when the `collapse-item` updates

**Comment by bastarder** [comment]
May be this is a vue bug, look at this [example](https://codesandbox.io/s/element-plus-spa-forked-49edj?file=/src/CollapseItem.vue)

when you click at the first 'True', the second will not change;

but, when you remove de `el-collapse-transition` in `CollapseItem.vue`, everything ok.

I will further confirm this problem when I am free, thanks for your report @874435441

**Comment by 874435441** [comment]
@bastarder From an example, it's really more like a Vue bug. I tried similar examples before，the difference from yours is I use local registration like 
`import ElCollapseTransition from "./CollapseTransition.vue";  
export default {
  components: [ElCollapseTransition],
};`
it is ok.

**Comment by Silentdoer** [comment]
this can be closed?

**Comment by Silentdoer** [comment]
新版的vue是解决了这个问题嘛？

**Comment by JeremyWuuuuu** [comment]
Do you still have this issue after you installed v3.0.11?
