### ISSUE TITLE
### Popover

### ISSUE THREAD

**Issue by Chersquwn** [element-plus/element-plus#164]
https://github.com/element-plus/element-plus/projects/1#card-42276101

Hi, I wish to contribute this component.

**Comment by JeremyWuuuuu** [comment]
Hi, before you doing so , I'd like to ask you to go through the old version of popover for better understanding of how it was designed, and how to do the migration, when you ready, you can go ahead doing it

**Comment by JeremyWuuuuu** [comment]
@Chersquwn Hi, is there any progress on this? If not, I'm going to close this issue then

**Comment by Chersquwn** [comment]
@JeremyWuuuuu Oh, sorry. I didn‘t see the reply in time, and i have complete popover component.
