### ISSUE TITLE
[Component] Infinite Scroll 无法继续触发v-infinite-scroll内func

### ISSUE THREAD

**Issue by sansWl** [element-plus/element-plus#16406]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBzaXplID0gcmVmKDMwKVxuY29uc3QgY291bnQgPXJlZigzMClcbmNvbnN0IGxvYWQgPSAoKSA9PiB7XG4gIGNvdW50LnZhbHVlICs9MTA7IC8v5rua5Yqo5Yeg5qyh5peg5rOV57un57ut5ZCR5LiL5rua5Yqo5Yi35pawXG4gIC8vY291bnQudmFsdWUgKz0xNTsgIC8v5q2j5bi45rua5Yqo5Yi35pawXG4gIGNvbnNvbGUubG9nKDEpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1zcGFjZVxuICAgICAgdi1pbmZpbml0ZS1zY3JvbGw9XCJsb2FkXCJcbiAgICAgIGluZmluaXRlLXNjcm9sbC1pbW1lZGlhdGU9XCJmYWxzZVwiXG4gICAgICB3cmFwXG4gICAgICA6c2l6ZT1cInNpemVcIlxuICAgICAgY2xhc3M9XCJob21lLWNvbnRhaW5lclwiXG4gICAgPlxuICAgICAgPGVsLWNhcmQgdi1mb3I9XCJpIGluIGNvdW50XCIgOmtleT1cImlcIiA+XG4gICAgICAgIDx0ZW1wbGF0ZSAjaGVhZGVyPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjYXJkLWhlYWRlclwiPlxuICAgICAgICAgICAgPHNwYW4+Q2FyZCBuYW1lPC9zcGFuPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8ZGl2IHYtZm9yPVwibyBpbiA0XCIgOmtleT1cIm9cIiBjbGFzcz1cInRleHQgaXRlbVwiPlxuICAgICAgICAgIHt7ICdMaXN0IGl0ZW0gJyArIG8gfX1cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNhcmQ+XG4gICAgPC9lbC1zcGFjZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgc2NvcGVkPlxuXG4uaGVhZC1jYXJke1xuICBib3gtc2hhZG93OiAtLWVsLWJveC1zaGFkb3ctZGFyaztcbiAgbWluLXdpZHRoOiAyNTBweDtcbn1cbi5ob21lLWNvbnRhaW5lcntcbiAgd2lkdGg6IDEwMCU7XG4gIG92ZXJmbG93OiBhdXRvO1xuICBoZWlnaHQ6IDEwMDBweDtcbn1cblxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

页面使用鼠标滚轮滚动

### What is Expected?

滚动到页面底部时<div>标签内 <el-card>会刷新出新的内容

### What is actually happening?

当到底部时额外新增card数量为10时，v-infinite-scroll仅能触发2次左右，当新增数量为15时，v-infinite-scroll正常触发

### Additional comments

1707 x 1019 //window.outerWidth、window.outerHeight
1699 x 911 //window.innerWidth、window.innerHeight

**Comment by Liao-js** [comment]
建议 distance 不要设置成 0。有些时候滚动条滚动到底部时，并不等于0。

**Comment by xuyimingwork** [comment]
看样子是首屏未铺满的情况下不会触发 load 事件，和 += 多少没有关系，+= 10 在显示区域宽度小点的情况下也可以触发

**Comment by btea** [comment]
@sansWl I ran the link you provided locally and the function is normal. Maybe it has something to do with page size? 🤔

**Comment by youqiangyr** [comment]
@sansWl 试试把immediate设为false

**Comment by sansWl** [comment]
> 建议 distance 不要设置成 0。有些时候滚动条滚动到底部时，并不等于0。
设置distance有效，感谢
