### ISSUE TITLE
[Feature Request]  Element.Dialog.props . closeOnClickModal.default

### ISSUE THREAD

**Issue by tracker1999** [element-plus/element-plus#1643]
### Existing Component
是

### Component Name
ElDialog

### Description
How can I change the default props of ElDialog in element plus?

In element-ui(Fully import) 

import Element from 'element-ui'

Element.Dialog.props.closeOnClickModal.default = false

**Comment by JeremyWuuuuu** [comment]
Well, I think you can do that by encapsulate `ElDialog` into your own components and use `v-bind=$attrs` to it.

**Comment by JeremyWuuuuu** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
