### ISSUE TITLE
[Component] [date-picker] I hope that when one of the items in the array bound by daterangepicker is empty, the picker can still show another time instead of all being empty

### ISSUE THREAD

**Issue by panoued** [element-plus/element-plus#16432]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGF0ZXMgPSByZWFjdGl2ZShbbnVsbCwgbmV3IERhdGUoKV0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8cD5cbiAgICAgIEkgaG9wZSB0aGF0IHdoZW4gb25lIG9mIHRoZSBpdGVtcyBpbiB0aGUgYXJyYXkgYm91bmQgYnkgZGF0ZXJhbmdlLXBpY2tlciBpcyBlbXB0eSwgdGhlIHBpY2tlciBjYW4gc3RpbGwgc2hvdyBhbm90aGVyIHRpbWUgaW5zdGVhZCBvZiBhbGwgYmVpbmcgZW1wdHkuXG4gICAgICDmiJHluIzmnJtkYXRlcmFuZ2Xnu5HlrprnmoTmlbDnu4RkYXRlc+WFtuS4reS4gOmhueS4uuepuuWAvOaXtnBpY2tlcuS7jeiDveWPpuS4gOmhueaXtumXtOiAjOS4jeaYr+WFqOmDqOS4uuepuu+8jOWwseWDj3Z1ZTLnmoRlbGVtZW50LXVp6YKj5qC3XG4gICAgPC9wPlxuICAgIDxlbC1kYXRlLXBpY2tlciB0eXBlPVwiZGF0ZXJhbmdlXCIgdi1tb2RlbD1cImRhdGVzXCI+PC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGF0ZXMgPSByZWFjdGl2ZShbbnVsbCwgbmV3IERhdGUoKV0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8cD5cbiAgICAgIEkgaG9wZSB0aGF0IHdoZW4gb25lIG9mIHRoZSBpdGVtcyBpbiB0aGUgYXJyYXkgYm91bmQgYnkgZGF0ZXJhbmdlLXBpY2tlciBpcyBlbXB0eSwgdGhlIHBpY2tlciBjYW4gc3RpbGwgc2hvdyBhbm90aGVyIHRpbWUgaW5zdGVhZCBvZiBhbGwgYmVpbmcgZW1wdHkuXG4gICAgICDmiJHluIzmnJtkYXRlcmFuZ2Xnu5HlrprnmoTmlbDnu4RkYXRlc+WFtuS4reS4gOmhueS4uuepuuWAvOaXtnBpY2tlcuS7jeiDveWPpuS4gOmhueaXtumXtOiAjOS4jeaYr+WFqOmDqOS4uuepuu+8jOWwseWDj3Z1ZTLnmoRlbGVtZW50LXVp6YKj5qC3XG4gICAgPC9wPlxuICAgIDxlbC1kYXRlLXBpY2tlciB0eXBlPVwiZGF0ZXJhbmdlXCIgdi1tb2RlbD1cImRhdGVzXCI+PC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==

### What is Expected?

date range picker能显示第二项的时间

### What is actually happening?

两个时间均为空

### Additional comments

_(empty)_

**Comment by wzc520pyfm** [comment]
This seems to be a deliberate design.

**Comment by panoued** [comment]
Okay, it seems I'll just have to figure out a way to make it happen myself.
