### ISSUE TITLE
[Component] [image, table] el-image full screen not fully working

### ISSUE THREAD

**Issue by penndev** [element-plus/element-plus#16447]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `Chrome 已是最新版本 版本 123.0.6312.106（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRhdGEgPSByZWYoW1xuICB7XG4gICAgaWQ6MSxcbiAgICBuYW1lOidsaXUnLFxuICAgIHBpYzogJ2h0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuOkFOZDlHY1J4MHE0QnBpUUJoNHk4TE1XSmpIekVDM0w4SzVYenoybml6ZjA0SVZRQ2h3JnMnLFxuICB9LFxuXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGVsLXRhYmxlXG4gICAgICA6ZGF0YT1cImRhdGFcIlxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgbGFiZWw9XCJJRFwiXG4gICAgICAgIHByb3A9XCJpZFwiXG4gICAgICAgIGZpeGVkXG4gICAgICAgIHdpZHRoPVwiODBcIlxuICAgICAgICBzb3J0YWJsZT1cImN1c3RvbVwiXG4gICAgICAvPlxuXG4gICAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICAgIGxhYmVsPVwibmFtZVwiXG4gICAgICAgIHByb3A9XCJuYW1lXCJcbiAgICAgICAgYWxpZ249XCJjZW50ZXJcIlxuICAgICAgLz5cblxuICAgICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICBsYWJlbD1cImNvdmVyXCJcbiAgICAgICAgYWxpZ249XCJjZW50ZXJcIlxuICAgICAgPlxuICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICAgIDxlbC1pbWFnZVxuICAgICAgICAgICAgOnNyYz1cInNjb3BlLnJvdy5waWNcIlxuICAgICAgICAgICAgOnpvb20tcmF0ZT1cIjEuMlwiXG4gICAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cIltzY29wZS5yb3cucGljXVwiXG4gICAgICAgICAgICBmaXQ9XCJjb3ZlclwiXG4gICAgICAgICAgICBzdHlsZT1cIndpZHRoOiA2MHB4O21pbi1oZWlnaHQ6IDkwcHg7XCJcbiAgICAgICAgICAvPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

el-image full screen not fully working. just click the cover

### What is Expected?

full screen mask

### What is actually happening?

z-index confusion

### Additional comments

old same issues https://github.com/element-plus/element-plus/issues/14215

**Comment by penndev** [comment]
```
<style>
.el-table .el-table__cell {
  position: static !important;
}
</style>
```
This code fix my problem

**Comment by Fuphoenixes** [comment]
see the [docs](https://element-plus.org/en-US/component/table.html#how-to-use-image-preview-in-the-table)
since the fixed column is implement by sticky, when you have fixed columns in table, please add the `preview-teleported` attribute in image

**Comment by penndev** [comment]
<el-image
      preview-teleported

**Comment by penndev** [comment]
> ```
> <style>
> .el-table .el-table__cell {
>   position: static !important;
> }
> </style>
> ```
> 
> This code fix my problem

```js
<el-image
  preview-teleported
   ...
/>
```  
This is the most correct approach.
