### ISSUE TITLE
[Component] [checkbox] checkbox的value与label是哪个大神定义的

### ISSUE THREAD

**Issue by shiki-gm** [element-plus/element-plus#16441]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-checkbox`

### Reproduction Link

[CodePen](https://codepen.io/)

### Steps to reproduce

checkbox的value与label是哪个大神定义的,为什么是相反的，浪费时间，这是什么脑回路

### What is Expected?

继续

### What is actually happening?

无

### Additional comments

_(empty)_

**Comment by shiki-gm** [comment]
<el-checkbox-group v-model="newFormInline.roleIds">
        <el-checkbox
          v-for="item in roleListData.list"
          :key="item.id"
          :label="item.roleName"
          :value="item.id"
        />
        >
      </el-checkbox-group>
任谁第一反应都应该是这么写吧，淦！

**Comment by Fuphoenixes** [comment]
<img width="1000" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/4603fe99-f422-4877-bdf6-6b37155186c6">
这种写法自2.6.0后已支持。
