### ISSUE TITLE
[Component] [date-picker] 请求移除dayjs

### ISSUE THREAD

**Issue by cweijan** [element-plus/element-plus#16464]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `Windows/macOS`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker.html#%E6%97%A5%E6%9C%9F%E6%A0%BC%E5%BC%8F)

### Steps to reproduce

使用date-picker组件, 将日期格式设置为yyyy-MM-dd

### What is Expected?

使用日期标准格式(yyyy-MM-dd)显示日期

### What is actually happening?

组件出现异常, 无法正常交互

### Additional comments

刚从Element-UI升级到Plus, 原先使用日期标准规范无法正常使用了,原因是plus依赖的dayjs并不使用标准规范, yyyy必须写成YYYY, dd必须写成DD, 这是非常糟糕的, 建议使用date-format库替代dayjs.
https://www.npmjs.com/package/date-format

**Comment by kooriookami** [comment]
日期格式化需要遵循dayjs的规范。Element UI到Plus都迁移稳定了4年了，怎么可能再换呢。

**Comment by cweijan** [comment]
好吧, 只能说一开始选择dayjs是个糟糕的决定.

**Comment by cweijan** [comment]
也许可以在组件内对yyyy隐式替换成YYYY, 让用户无感知.
