### ISSUE TITLE
[Style] [table, image] When el-table and el-image are used simultaneously, z-index may become distorted

### ISSUE THREAD

**Issue by Xmppp** [element-plus/element-plus#16468]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.6.3`
- Browser / OS: `Chrome/macos`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFt7bmFtZTonMTExJ30se25hbWU6JzExMSd9LHtuYW1lOicxMTEnfSx7bmFtZTonMTExJ31dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwibGlzdFwiPlxuICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwibmFtZVwiIHByb3A9XCJuYW1lXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLlm77niYdcIiBwcm9wPVwibmFtZVwiPlxuICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZWRcIj5cbiAgPGVsLWltYWdlIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCJcbiAgIDpwcmV2aWV3LXNyYy1saXN0PVwiWydodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZyddXCI+PC9lbC1pbWFnZT5cbiAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Click on image to zoom in

### What is Expected?

The image is enlarged normally, and all other are covered

### What is actually happening?

The remaining images were not covered

### Additional comments

_(empty)_

**Comment by Xmppp** [comment]
![Uploading 4CBB2C45-478E-4FC9-B09B-D8FD1711871E.png…]()

**Comment by Fuphoenixes** [comment]
see the [docs](https://element-plus.org/en-US/component/table.html#how-to-use-image-preview-in-the-table)

**Comment by Xmppp** [comment]
文档里的不是解决这个问题的，我说的是图片放大后有bug。跟 #16447 一样的bug。
![E9E08C78-F4B7-426C-80CE-C0BB9B13F43C](https://github.com/element-plus/element-plus/assets/82095287/3bf318cd-d61f-41a3-af14-39cb5a54a12a)
你应该打开我给的链接看一下

**Comment by Fuphoenixes** [comment]
<img width="1159" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/2cfc2c6b-597d-4dac-b723-6af6125bb677">
<img width="1806" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/92e6a517-a46f-4058-ade0-01f6d1b6eeb4">
