### ISSUE TITLE
[Component] [input] [复合型输入框] 当Input的size设置为large时, 使用select组件样式变得很丑

### ISSUE THREAD

**Issue by Yuelioi** [element-plus/element-plus#16500]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `chrome,火狐,edge`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblxuICA8ZGl2IGNsYXNzPVwibXQtNFwiPlxuICAgIDxlbC1pbnB1dFxuICAgICAgdi1tb2RlbD1cImlucHV0M1wiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4XCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCJcbiAgICAgIGNsYXNzPVwiaW5wdXQtd2l0aC1zZWxlY3RcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjcHJlcGVuZD5cbiAgICAgICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPHRlbXBsYXRlICNhcHBlbmQ+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdFwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMTE1cHhcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiUmVzdGF1cmFudFwiIHZhbHVlPVwiMVwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIk9yZGVyIE5vLlwiIHZhbHVlPVwiMlwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlRlbFwiIHZhbHVlPVwiM1wiIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWlucHV0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBTZWFyY2ggfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgaW5wdXQzID0gcmVmKCcnKVxuY29uc3Qgc2VsZWN0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5pbnB1dC13aXRoLXNlbGVjdCAuZWwtaW5wdXQtZ3JvdXBfX3ByZXBlbmQge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1lbC1maWxsLWNvbG9yLWJsYW5rKTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

官网示例就不行,https://element-plus.org/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86, 这里将input的size改成large, select高度直接不对了

### What is Expected?

通过 slot 来指定在 Input 中分发的前置  Select组件, 当input的尺寸设置为large时, 应该样式一致

### What is actually happening?

select组件高度不对, 因此会多一个border

### Additional comments

_(empty)_

**Comment by Yuelioi** [comment]
请看Select

![20240414-04334670.png](https://cdn.yuelili.com/cache/2024/04/20240414-04334670.png)

**Comment by Yuelioi** [comment]
解决方案

```css
/* 给select哪个层级加个100% */
.el-select{
  height: 100%;
}

/* 加个100% */
:deep(.el-select__wrapper) {
  height: 100%;
}
```

**Comment by kooriookami** [comment]
Select也加一个size="large"

**Comment by Yuelioi** [comment]
> Select也加一个size="large"

草草草
