### ISSUE TITLE
2.7.0版本，在vue3.4.21下，控制台有警告 Write operation failed: computed value is readonly

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#16505]
## 问题描述
![image](https://github.com/element-plus/element-plus/assets/22720488/01f5db73-c55f-402c-9630-1b7e84cfd54e)
![image](https://github.com/element-plus/element-plus/assets/22720488/96293ff6-a8f9-4d20-a7a9-b3cf83e3e3bd)
![image](https://github.com/element-plus/element-plus/assets/22720488/5a8e3b61-912e-49cb-9ca9-870e75ff514d)

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `chrome 120`
- Build Tool: `Webpack`

**Comment by FastGUI** [comment]
我发现是 el-select 这个组件引起的，不知道修复了没有

**Comment by YINA-6** [comment]
It has been fixed in 2.7.1, you can try it.
