### ISSUE TITLE
[bug report] El table column set type = selection in chrome@65.0.3325.181 Click the check box of tbody to neither select nor trigger the selection change of El table

### ISSUE THREAD

**Issue by will-pan** [element-plus/element-plus#1650]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
window/chrome@65.0.3325.181

### Vue version
3.0.0

### Reproduction Link
jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
el-table-column设置type=selection在chrome@65.0.3325.181中，点击勾选tbody的checkbox，既不会选中，也不会触发el-table的selection-change

### What is Expected?
点击勾选tbody的checkbox，能正常选中，且触发el-table的selection-change

### What is actually happening?
el-table-column设置type=selection在chrome@65.0.3325.181中，点击勾选tbody的checkbox，既不会选中，也不会触发el-table的selection-change

**Comment by Ryan2128** [comment]
cc @justwiner

**Comment by justwiner** [comment]
@will-pan 
Can you provide test cases on `codeopen`? `jsfiddle` is not accessible at present.

**Comment by will-pan** [comment]
> @ will-pan
> 您可以提供有关的测试用例`codeopen`吗？`jsfiddle`目前无法访问。

是这样的，因为这个情况会在任何地方重现（包括docs的地址：https://element-plus.org/）当我使用chrome@65.0.3325.181或者Microsoft Edge 44.17763.1.0的时候。但当我使用chrome@87.0.4280.8则是正常的，我认为这是一个关于浏览器兼容性问题，所以我没有办法提供测试用例。

ps:我检查了dom元素的事件，发现element-plus表格tbody中的label.el-checkbox有一个input事件，似乎是这个事件存在兼容性问题，同样的位置在element-ui因为没有使用input事件，则是正常的。
