### ISSUE TITLE
[Component] [table] 表格合并两层行的时候鼠标hover高亮异常

### ISSUE THREAD

**Issue by zjian233** [element-plus/element-plus#16515]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: ` Chrome/123.0.0.0 / win 10`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICBcbiAgICAgIDxlbC10YWJsZVxuICAgICAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgICBib3JkZXJcbiAgICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLXRvcDogMjBweFwiXG4gICAgICA+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MlwiIGxhYmVsPVwiQW1vdW50IDJcIiAvPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgICA8L2VsLXRhYmxlPlxuICAgIDwvZGl2PlxuICA8L3RlbXBsYXRlPlxuICBcbiAgPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiAgaW1wb3J0IHR5cGUgeyBUYWJsZUNvbHVtbkN0eCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbiAgXG4gIGludGVyZmFjZSBVc2VyIHtcbiAgICBpZDogc3RyaW5nXG4gICAgbmFtZTogc3RyaW5nXG4gICAgYW1vdW50MTogc3RyaW5nXG4gICAgYW1vdW50Mjogc3RyaW5nXG4gICAgYW1vdW50MzogbnVtYmVyXG4gICAgbm9kZUlkOiBudW1iZXI7XG5cbiAgICBzcGFuOiBudW1iZXJbXVtdO1xuICB9XG4gIFxuICBpbnRlcmZhY2UgU3Bhbk1ldGhvZFByb3BzIHtcbiAgICByb3c6IFVzZXJcbiAgICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4gICAgcm93SW5kZXg6IG51bWJlclxuICAgIGNvbHVtbkluZGV4OiBudW1iZXJcbiAgfVxuICBcbiAgXG4gIGNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICAgIHJvdyxcbiAgICBjb2x1bW4sXG4gICAgcm93SW5kZXgsXG4gICAgY29sdW1uSW5kZXgsXG4gIH06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICAgIGlmIChyb3cuc3Bhbltjb2x1bW5JbmRleF0pIHtcbiAgICAgICAgcmV0dXJuIHJvdy5zcGFuW2NvbHVtbkluZGV4XVxuICAgIH1cbiAgICByZXR1cm4gWzEsIDFdO1xuXG4gIH1cbiAgXG4gIGNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICAgIHtcbiAgICAgIGlkOiAnMTI5ODcxMjInLFxuICAgICAgbm9kZUlkOiAwLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhbW91bnQxOiAnMjM0JyxcbiAgICAgIGFtb3VudDI6ICczLjInLFxuICAgICAgYW1vdW50MzogMTAsXG4gICAgICBzcGFuOiBbWzQsMV0sIFsyLCAxXV1cbiAgICB9LFxuICAgIHtcbiAgICAgIGlkOiAnMTI5ODcxMjMnLFxuICAgICAgbm9kZUlkOiAwLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhbW91bnQxOiAnMTY1JyxcbiAgICAgIGFtb3VudDI6ICc0LjQzJyxcbiAgICAgIGFtb3VudDM6IDEyLFxuICAgICAgc3BhbjogW1swLCAwXSwgWzAsIDBdXVxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgICBub2RlSWQ6IDAsXG4gICAgICBuYW1lOiAnVG9tMScsXG4gICAgICBhbW91bnQxOiAnMzI0JyxcbiAgICAgIGFtb3VudDI6ICcxLjknLFxuICAgICAgYW1vdW50MzogOSxcbiAgICAgIHNwYW46IFtbMCwgMF0sIFsyLCAxXV1cbiAgICB9LFxuICAgIHtcbiAgICAgIGlkOiAnMTI5ODcxMjUnLFxuICAgICAgbm9kZUlkOiAwLFxuICAgICAgbmFtZTogJ1RvbTEnLFxuICAgICAgYW1vdW50MTogJzYyMScsXG4gICAgICBhbW91bnQyOiAnMi4yJyxcbiAgICAgIGFtb3VudDM6IDE3LFxuICAgICAgc3BhbjogW1swLCAwXSwgWzAsIDBdXVxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6ICcxMjk4NzEyNicsXG4gICAgICBub2RlSWQ6IDEsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFtb3VudDE6ICc1MzknLFxuICAgICAgYW1vdW50MjogJzQuMScsXG4gICAgICBhbW91bnQzOiAxNSxcbiAgICAgIHNwYW46IFtbMiwgMV0sIFsxLCAxXV1cbiAgICB9LFxuICAgIHtcbiAgICAgIGlkOiAnMTI5ODcxMjcnLFxuICAgICAgbm9kZUlkOiAxLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhbW91bnQxOiAnNTM5JyxcbiAgICAgIGFtb3VudDI6ICc0LjEnLFxuICAgICAgYW1vdW50MzogMTUsXG4gICAgICBzcGFuOiBbWzAsIDBdLCBbMSwgMV1dXG4gICAgfSxcbiAgXVxuICA8L3NjcmlwdD5cbiAgIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<template>
    <div>
  
      <el-table
        :data="tableData"
        :span-method="objectSpanMethod"
        border
        style="width: 100%; margin-top: 20px"
      >
        <el-table-column prop="id" label="ID" width="180" />
        <el-table-column prop="name" label="Name" />
        <el-table-column prop="amount1" label="Amount 1" />
        <el-table-column prop="amount2" label="Amount 2" />
        <el-table-column prop="amount3" label="Amount 3" />
      </el-table>
    </div>
  </template>
  
  <script lang="ts" setup>
  import type { TableColumnCtx } from 'element-plus'
  
  interface User {
    id: string
    name: string
    amount1: string
    amount2: string
    amount3: number
    nodeId: number;

    span: number[][];
  }
  
  interface SpanMethodProps {
    row: User
    column: TableColumnCtx<User>
    rowIndex: number
    columnIndex: number
  }
  
  
  const objectSpanMethod = ({
    row,
    column,
    rowIndex,
    columnIndex,
  }: SpanMethodProps) => {
    if (row.span[columnIndex]) {
        return row.span[columnIndex]
    }
    return [1, 1];

  }
  
  const tableData: User[] = [
    {
      id: '12987122',
      nodeId: 0,
      name: 'Tom',
      amount1: '234',
      amount2: '3.2',
      amount3: 10,
      span: [[4,1], [2, 1]]
    },
    {
      id: '12987123',
      nodeId: 0,
      name: 'Tom',
      amount1: '165',
      amount2: '4.43',
      amount3: 12,
      span: [[0, 0], [0, 0]]
    },
    {
      id: '12987124',
      nodeId: 0,
      name: 'Tom1',
      amount1: '324',
      amount2: '1.9',
      amount3: 9,
      span: [[0, 0], [2, 1]]
    },
    {
      id: '12987125',
      nodeId: 0,
      name: 'Tom1',
      amount1: '621',
      amount2: '2.2',
      amount3: 17,
      span: [[0, 0], [0, 0]]
    },
    {
      id: '12987126',
      nodeId: 1,
      name: 'Tom',
      amount1: '539',
      amount2: '4.1',
      amount3: 15,
      span: [[2, 1], [1, 1]]
    },
    {
      id: '12987127',
      nodeId: 1,
      name: 'Tom',
      amount1: '539',
      amount2: '4.1',
      amount3: 15,
      span: [[0, 0], [1, 1]]
    },
  ]
  </script>
  ```

### What is Expected?

鼠标移入第4行的时候，第二列应该高亮Tom1

### What is actually happening?

结果第二列高亮了Tom
![image](https://github.com/element-plus/element-plus/assets/33460651/c8270b2d-dc3a-486b-b824-698d68db98a6)

### Additional comments

_(empty)_

**Comment by dowinweb** [comment]
fixed here  #16517
see if there is other situations that didnot consider
