### ISSUE TITLE
[Style] [table, image] When el-table and el-image are used simultaneously, z-index may become distorted

### ISSUE THREAD

**Issue by Xmppp** [element-plus/element-plus#16514]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.6.3`
- Browser / OS: `Chrome/macos`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFt7bmFtZTonMTExJ30se25hbWU6JzExMSd9LHtuYW1lOicxMTEnfSx7bmFtZTonMTExJ31dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwibGlzdFwiPlxuICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwibmFtZVwiIHByb3A9XCJuYW1lXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLlm77niYdcIiBwcm9wPVwibmFtZVwiPlxuICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZWRcIj5cbiAgPGVsLWltYWdlIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCJcbiAgIDpwcmV2aWV3LXNyYy1saXN0PVwiWydodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZyddXCI+PC9lbC1pbWFnZT5cbiAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Click on image to zoom in

### What is Expected?

The image is enlarged normally, and all other are covered

### What is actually happening?

The remaining images were not covered

### Additional comments

参考 #16447 。去年9月的问题了。文档里的常见问题解决不了这个，别总想着赶紧把issues关掉。

**Comment by Xmppp** [comment]
![Uploading E9E08C78-F4B7-426C-80CE-C0BB9B13F43C.png…]()

**Comment by Xmppp** [comment]
![Uploading E9E08C78-F4B7-426C-80CE-C0BB9B13F43C.png…]()
这是bug图

**Comment by Xmppp** [comment]
不想打开[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBsaXN0ID0gcmVmKFt7bmFtZTonMTExJ30se25hbWU6JzExMSd9LHtuYW1lOicxMTEnfSx7bmFtZTonMTExJ31dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwibGlzdFwiPlxuICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwibmFtZVwiIHByb3A9XCJuYW1lXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLlm77niYdcIiBwcm9wPVwibmFtZVwiPlxuICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZWRcIj5cbiAgPGVsLWltYWdlIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCJcbiAgIDpwcmV2aWV3LXNyYy1saXN0PVwiWydodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZyddXCI+PC9lbC1pbWFnZT5cbiAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)，我就给你先截个图。
![E9E08C78-F4B7-426C-80CE-C0BB9B13F43C](https://github.com/element-plus/element-plus/assets/82095287/b7ce2b21-5fb6-4e54-a774-3b14e2c30701)
，别总想着关issues。

**Comment by Fuphoenixes** [comment]
为`el-image`加上`preview-teleported`参数就可以解决这个问题，这是定位导致的层级异常。

**Comment by Fuphoenixes** [comment]
<img width="1774" alt="image" src="https://github.com/element-plus/element-plus/assets/27912232/b7768c40-e8bb-4af3-b0e7-407a47b618b6">

**Comment by Xmppp** [comment]
ok，抱歉，刚才试了找了半天。还是把那句话错过了。把自己整红温了。抱歉 @Fuphoenixes
