### ISSUE TITLE
[Bug Report] el-table expand collapse when the first the row was modified

### ISSUE THREAD

**Issue by ysinsane** [element-plus/element-plus#1652]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
macOS Big Sur11.2.3 / chrome 89.0.4389.82

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/ysanity/akgszd2u/

### Steps to reproduce
Click > to expand, then the expandChange() will be called to fetch data. When data fetched, the whole table will be render again. And expand will all be collapse.

### What is Expected?
Only refresh data 

### What is actually happening?
Refresh data and expand

**Comment by inottn** [comment]
I think It is intended, you should use row-key in el-table.

**Comment by justwiner** [comment]
@ysinsane 
Can you provide test cases on `codeopen`? `jsfiddle` is not accessible at present.

**Comment by justwiner** [comment]
@ysinsane 
```js
<el-table
  row-key="id"
>
```
When you set `row-key`, the data will not update all columns

**Comment by ysinsane** [comment]
Yes, It worked for me. Thanks to @inottn and @justwiner . My code works in beta32 without row-key.
If this is intended, I shall close this issue.
