### ISSUE TITLE
[Bug Report] el-table The sorting function causes a table style disorder

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1653]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/iamkun/ods21k7t/

### Steps to reproduce
So when I click sort, it's going to make my table look a little bit different

### What is Expected?
fix 

### What is actually happening?
So when I click sort, it's going to make my table look a little bit different
![t](https://user-images.githubusercontent.com/20943608/111421976-de1fce00-8728-11eb-883a-8d9876db020d.gif)

**Comment by justwiner** [comment]
@jahnli 
Can you provide test cases on `codeopen`? `jsfiddle` is not accessible at present.

**Comment by jahnli** [comment]
I'll give you the link in a second, but I've tested it, and when I click Filter or Sort it inserts an element like this, and I'm not sure what this node is for, but I think it's probably the problem
![image](https://user-images.githubusercontent.com/20943608/111593778-480da580-8805-11eb-8bab-f6dae0990ec2.png)

**Comment by jahnli** [comment]
@justwiner  https://codepen.io/jahnli/pen/QWGRXgM
