### ISSUE TITLE
[TypeScript] [All] tsconfig.moduleResolution for bundler. ts type not found

### ISSUE THREAD

**Issue by Jevin0** [element-plus/element-plus#16541]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.22`
- Element Plus Version: `2.7.0`
- Browser / OS: `latest`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/Jevin0/ep-ts/blob/main/src/App.vue)

### Steps to reproduce

-

### What is Expected?

正常import type

### What is actually happening?

找不到模块“element-plus/es/components/form/src/form.type”或其相应的类型声明。ts(2307)

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/69580637/a0eecd7f-a936-43ca-8e8c-c508aa5c259c)

**Comment by btea** [comment]
It seems to have been exported directly, maybe you can use `import type { formProps } from 'element-plus'` directly.

**Comment by Jevin0** [comment]
@btea But here vscode treats formProps as value? (My ts is not very good, I don’t understand the reason)
![image](https://github.com/element-plus/element-plus/assets/69580637/78be0d6a-a8af-43f4-9cd4-0e58d6c1b571)

**Comment by btea** [comment]
Sorry, the first letter of the `FormProps` type must be capitalized.
![image](https://github.com/element-plus/element-plus/assets/24516654/0915a62b-2d65-4784-80de-b7186dfe0cc0)
