### ISSUE TITLE
[Question] EL Table Selected Checkboxes

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1655]
```
https://element-plus.org/#/en-US/component/table
```
Hi, I would like to find out what is the property for selected checkboxes array.
In element ui i have used:
```
    <el-table
            ref="linkObjectTable"
```

```
this.$refs.linkObjectTable.selection;
```

and selection gave a list of selected checkboxes in the table.
but now it's undefined. How can i find out selected checkboxes in the table ?

```
this.$refs.linkObjectTable.store.states.selection.value
```
is there another way ?

**Comment by justwiner** [comment]
You can listen and get the currently selected item through the `select` and `selection-change` events.
see the detail: [https://element-plus.org/#/en-US/component/table#table-events](https://element-plus.org/#/en-US/component/table#table-events)
