### ISSUE TITLE
[Bug Report] When I try to set multiple to false for in-table filtering, the filters filter list will have an additional entry All

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1656]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10
### Vue version
3.0.7

### Reproduction Link
https://codepen.io/jahnli/pen/dyOEXVo

### Steps to reproduce
![image](https://user-images.githubusercontent.com/20943608/111442858-c3a71e00-8743-11eb-9f8c-2b283e8d19c1.png)

When I try to set multiple to false for in-table filtering, the filters filter list will have an additional entry All

### What is Expected?
The default ALL field is not required

### What is actually happening?
When I try to set multiple to false for in-table filtering, the filters filter list will have an additional entry All

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/111447857-ceb07d00-8748-11eb-92f1-807893bfcc01.png)
Another problem is that when I click on the filter box, the console will output an error like this

**Comment by justwiner** [comment]
@jahnli 
When filter multiple is false, if there is no all option, you will never see all the data after selecting one, therefore, the all option must be included here.

**Comment by justwiner** [comment]
> ![image](https://user-images.githubusercontent.com/20943608/111447857-ceb07d00-8748-11eb-92f1-807893bfcc01.png)
> Another problem is that when I click on the filter box, the console will output an error like this

This warning doesn't reappear on my computer, can you describe it in more detail

**Comment by jahnli** [comment]
If it is necessary, can you provide a custom option? At present, we are a Chinese project, and an English option of ALL suddenly appears, which will be very prominent

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/111563834-ac177600-87d3-11eb-91d5-d54c78b8aaff.png)
![test](https://user-images.githubusercontent.com/20943608/111563835-ade13980-87d3-11eb-8217-5ea3f13f2e88.gif)
When I click Filter, the console prompts me with this error

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/111563917-cfdabc00-87d3-11eb-9fae-775bebae3f9b.png)
If you look at the end, there's also a problem with clicking on the filter table that you get a little bit more space

**Comment by justwiner** [comment]
The test link you provided in this issue does not contain style problems. Can you update the code? I'll fix it as soon as possible. 

As for the all option, I will consider using internationalization internally.

**Comment by jahnli** [comment]
Thank you. I'll try to fix it   ，Another problem is that if you click Filter or Sort, you get an extra area in the table

![test](https://user-images.githubusercontent.com/20943608/111578530-49cc6e80-87ef-11eb-8f63-c90d4f4c7333.gif)
