### ISSUE TITLE
[Performance] [All] 由于组件库导致 `Volar` VSCode 卡顿问题

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#16575]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.4.23`
- Element Plus Version: `2.6.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/vuejs/language-tools/issues/4115)

### Steps to reproduce

这真是一个非常诡异的现象，当我尝试删除项目中的 element-plus 后卡顿的确就消失了，我用的是自动导入的方式。

### What is Expected?

不会导致 VSCode 卡顿

### What is actually happening?

导致 VSCode 的提示功能卡顿

### Additional comments

由于本人就是个菜鸡，没办法给出合理的解释，只能劳烦各位大神了。

**Comment by warmthsea** [comment]
降 Volar 版本

**Comment by WangJincheng4869** [comment]
> 降 Volar 版本

老版本的那个 TS 插件不让安装了...

**Comment by warmthsea** [comment]
高版本我不太清楚，我最近一直在使用 2.0.2版本好像没遇到什么问题，没必要降低到 2.0 以下；
那个 TS 的是低于2.0 使用的，现在大于 2.0 已经把 TS 功能集成一个插件了

**Comment by makedopamine** [comment]
#16111 应该可以优化这个问题,  刚才发布到了npm上，你可以安装测试下。如果有比较大的改善，可以反馈一下，我会尽快推进这个PR
```
  "dependencies": {
    "element-plus": "npm:@makedopamine/element-plus",
  }
```

**Comment by WangJincheng4869** [comment]
@makedopamine 经过测测效果显著，虽然偶尔提示依旧会有卡顿（但是卡顿时间也比之前短特别多）。但是比之前强太多了，之前是几乎必卡，偶尔不卡。

**Comment by Cheerwhy** [comment]
> #16111 应该可以优化这个问题, 刚才发布到了npm上，你可以安装测试下。如果有比较大的改善，可以反馈一下，我会尽快推进这个PR
> 
> ```
>   "dependencies": {
>     "element-plus": "npm:@makedopamine/element-plus",
>   }
> ```

效果显著

**Comment by mxp131011** [comment]
希望尽快推进
