### ISSUE TITLE
[TypeScript] [form] 在使用pinia配合element-plus时ts报错

### ISSUE THREAD

**Issue by huankong233** [element-plus/element-plus#16579]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Github Repo](https://github.com/huankong233/94list-frontend-demo)

### Steps to reproduce

使用 `ref` 获取 `el-form` 表单元素

### What is Expected?

类型不报错

### What is actually happening?

类型报错

### Additional comments

错误信息：

如果没有引用 ".pnpm/@vue+shared@3.4.21/node_modules/@vue/shared"，则无法命名 "useLoginPannelStore" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)

![image](https://github.com/element-plus/element-plus/assets/49610758/0d817930-fd0f-4466-b711-792e4b2f5eca)

**Comment by btea** [comment]
Perhaps you could follow the prompts and add a type declaration.

![image](https://github.com/element-plus/element-plus/assets/24516654/8efc1cef-a4cb-4acd-a309-6ff9e4d458c8)

**Comment by huankong233** [comment]
> Perhaps you could follow the prompts and add a type declaration.
> 
> ![image](https://private-user-images.githubusercontent.com/24516654/323860972-8efc1cef-a4cb-4acd-a309-6ff9e4d458c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTM2NjMsIm5iZiI6MTcxMzUxMzM2MywicGF0aCI6Ii8yNDUxNjY1NC8zMjM4NjA5NzItOGVmYzFjZWYtYTRjYi00YWNkLWEzMDktNmZmOWU0ZDQ1OGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3NTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODE3OWQ5MjY4NTYzNGQ4ZjY4ODhmNTNkZDNiYmU3YmNmMjAzODA1MzM3OTA5ODRiOGIyZmVjOTNjZmQ5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iYjQ8hvijmx4WEL1NtzyYWZi8bhJNw6aiQvgIFWY9Ik)

thx

**Comment by huankong233** [comment]
> Perhaps you could follow the prompts and add a type declaration.
> 
> ![image](https://private-user-images.githubusercontent.com/24516654/323860972-8efc1cef-a4cb-4acd-a309-6ff9e4d458c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjM2ODYsIm5iZiI6MTcxNTI2MzM4NiwicGF0aCI6Ii8yNDUxNjY1NC8zMjM4NjA5NzItOGVmYzFjZWYtYTRjYi00YWNkLWEzMDktNmZmOWU0ZDQ1OGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE0MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTc3N2ExMzRjMWVmNmYxMjY4N2M0NWM0Y2E4MmYxODdkYjYyYWFmOGQ3MzQwODgyMzY3OTUwMGZjNWE0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-Hw6fbgV7BY5OZGH94T4Anr2JSKDsWV7b1DL5OnmDk)

## Environment
- Vue Version: `3.4.27`
- Element Plus Version: `2.7.2`
- Browser / OS: UserAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
- Build Tool: `Vite`

## problem

when i add the type of the store, my code hint is gone.

but when i remove the `StoreDefinition` , and the code hint works again , but alert the error again.

## screenshot

### code hint
![image](https://github.com/element-plus/element-plus/assets/49610758/9b4b60f7-7e88-4cf8-a84c-caad4d4efb7b)
![image](https://github.com/element-plus/element-plus/assets/49610758/a1f1a8fb-a2d6-4c83-a11d-ca9cdfe5ea53)

### StoreDefinition
![image](https://github.com/element-plus/element-plus/assets/49610758/c00c13ef-1a77-4c72-bb95-1121f82df399)

remove the code in red rect ,the error will dispear.

**Comment by btea** [comment]
你的意思是加了类型声明没有提示，不加会报错？

**Comment by huankong233** [comment]
> 你的意思是加了类型声明没有提示，不加会报错？

嗯嗯，英语水平不太好，哈哈哈

如果取消那个 FormInstance 那个类型注释就没问题了

**Comment by btea** [comment]
看起来像是组件声明打乱了defineStore 的类型推断。🤔

**Comment by huankong233** [comment]
> 看起来像是组件声明打乱了defineStore 的类型推断。🤔
> 
> 你把`FormInstance`换成你本地自定义的组件试试，有没有同样的问题？

不太会啊，哈哈，怎么操作

**Comment by btea** [comment]
关于你这个正常情况下的提示能发个动态图或者视频吗？

**Comment by huankong233** [comment]
> 关于你这个正常情况下的提示能发个动态图或者视频吗？

好的，等一下

**Comment by huankong233** [comment]
[视频 https://tmpfiles.org/dl/5731228/qq2024510-91259-hd.mp4](https://tmpfiles.org/dl/5731228/qq2024510-91259-hd.mp4)

**Comment by huankong233** [comment]
我现在暂时用的解决方案是在我要用的地方直接as，但是这样感觉不好，不知道有没有更好的办法

![image](https://github.com/element-plus/element-plus/assets/49610758/f26454b2-b68b-45cd-afe3-73f573d584f4)

**Comment by btea** [comment]
看起来应该是 pinia 类型推断不出自定义的组件类型。或许不应该在 store 中直接声明组件引用的变量，只保存单纯的数据。🤔

**Comment by btea** [comment]
直接把 `tsconfig.app.json` 里面的 `tsBuildInfoFile` 和 `composite` 去掉应该就可以了。

**Comment by huankong233** [comment]
> 直接把 `tsconfig.app.json` 里面的 `tsBuildInfoFile` 和 `composite` 去掉应该就可以了。

🤔确实不报错了
