### ISSUE TITLE
[Component] [button] el-button按钮，当设置tag="a"的时候 disabled无效

### ISSUE THREAD

**Issue by 136323000** [element-plus/element-plus#16591]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `Windows`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiA6ZGlzYWJsZWQ9dHJ1ZSAgaHJlZj1cImh0dHBzOi8vd3d3LmJhaWR1LmNvbVwiIHRhZz1cImFcIj50ZXN0PC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<el-button :disabled=true  href="https://www.baidu.com" tag="a">test</el-button>

### What is Expected?

当设置:disabled=true的时候 无法点击跳转

### What is actually happening?

实际可以点击跳转

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
![image](https://github.com/element-plus/element-plus/assets/45450994/19c8e954-4879-47cd-a6b1-aeebb3f3ed43)
建议直接手动解决

**Comment by btea** [comment]
This is normal behavior. In fact, `a` tag does not support disabled. If you need this effect, please handle it yourself as @warmthsea  suggested.

**Comment by chenxch** [comment]
是否可以考虑是在a标签的时候使用pointer-events在实现禁用功能

**Comment by wangdaodao** [comment]
> 是否可以考虑是在a标签的时候使用pointer-events在实现禁用功能

`pointer-events`也不是最佳实践，用户可以通过控制面板去掉样式。这块假如是`a`标签，是可以预先知道的，手动解决就行。

**Comment by chenxch** [comment]
> > 是否可以考虑是在a标签的时候使用pointer-events在实现禁用功能
> 
> `pointer-events`也不是最佳实践，用户可以通过控制面板去掉样式。这块假如是`a`标签，是可以预先知道的，手动解决就行。

是的，这只是hack的一个方案想法，对于大部分用户来说，普遍认为就只要设置了disabled点击事件不要触发。我相信这种场景来问问题的用户肯定不在少数，或许可以在文档中说明，disabled在tag=a时候无效。

**Comment by 136323000** [comment]
> ![图像](https://private-user-images.githubusercontent.com/45450994/324149715-19c8e954-4879-47cd-a6b1-aeebb3f3ed43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODk3NzYsIm5iZiI6MTcxNDE4OTQ3NiwicGF0aCI6Ii80NTQ1MDk5NC8zMjQxNDk3MTUtMTljOGU5NTQtNDg3OS00N2NkLWE2YjEtYWVlYmIzZjNlZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAzNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5M2M2ZGNlNGQxMzQ2ODRmMzUxNTUwZTRiNzMxMjM2OWE0Njc4MWFiYzNiYjk4OTliNGMzNWQ3Y2MxOTA5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjPqwHRqEJByh1MpNwyqFG3eqCoXSHE6GnctnITDLd0) 建议直接手动解决

成功解决了我的问题 感谢
