### ISSUE TITLE
[bug report] cannot be imported on demand

### ISSUE THREAD

**Issue by wangfpp** [element-plus/element-plus#1659]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
MAC OS 11.1/ Chrome 89.0.4389.82

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-odyf9?file=/src/main.js

### Steps to reproduce
按照官网的按需引入文档结果是无法按需引入,还是需要引入全量的element-plus  css文件

### What is Expected?
实现按需引入

### What is actually happening?
按需引入没有生效

**Comment by Ryan2128** [comment]
It works well with vue-cli.

![image](https://user-images.githubusercontent.com/33176053/111575503-74b3c400-87e9-11eb-9ad7-4530ed3bb6f2.png)

![image](https://user-images.githubusercontent.com/33176053/111575511-78dfe180-87e9-11eb-94c4-2c3a82d4275f.png)

![image](https://user-images.githubusercontent.com/33176053/111575524-7d0bff00-87e9-11eb-8665-a4a4cb3d84a0.png)

![image](https://user-images.githubusercontent.com/33176053/111575573-a4fb6280-87e9-11eb-93c5-6a2f1dea44a9.png)

**Comment by Ryan2128** [comment]
If you use vite, you can use `vite-plugin-importer` or `vite-plugin-components`.

- Use vite-plugin-importer

![image](https://user-images.githubusercontent.com/33176053/111576072-ba24c100-87ea-11eb-9e86-14515168e20e.png)

**Comment by wangfpp** [comment]
@Ryan2128  我使用的是vite  使用了vite-plugin-imp@2.0.4是可以得了,
希望能有一个文档帮助更多人

**Comment by iSuslov** [comment]
@wangfpp Is it possible to use english here? (It's not my native language too)
