### ISSUE TITLE
[Style] [button] el-button的auto-insert-space属性或是全局autoInsertSpace属性在按钮包含el-icon的情况下不生效

### ISSUE THREAD

**Issue by JoryPai** [element-plus/element-plus#16608]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.1`
- Browser / OS: `Chrome 123.0.6312.107 / MacOS 13.4`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIGF1dG8taW5zZXJ0LXNwYWNlIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCI+XG4gICAgPGVsLWljb24+XG4gICAgICA8UGx1cyAvPlxuICAgIDwvZWwtaWNvbj5cbiAgICDliJvlu7pcbiAgPC9lbC1idXR0b24+XG48IS0tLeS4jeW4puWbvuagh+eahOaDheWGtS0tLT5cbiAgICA8ZWwtYnV0dG9uIGF1dG8taW5zZXJ0LXNwYWNlIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCI+XG4gICAg5Yib5bu6XG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

见链接代码

### What is Expected?

按钮中的中文之间有空格

### What is actually happening?

按钮中的中文之间没有空格

### Additional comments

未对除el-button之外的组件如el-button-group等进行测试

<img width="193" alt="image" src="https://github.com/element-plus/element-plus/assets/43819980/c2d5aa66-b44d-477b-8c55-373eb5ed9b39">

**Comment by JoryPai** [comment]
我很疑惑这是一个bug还是设计如此

**Comment by makedopamine** [comment]
设计如此，内容必须是两个表意字符才会加间距，使用icon prop或者icon slot应该可以达到你预期的结果。 [playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIGF1dG8taW5zZXJ0LXNwYWNlIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCIgOmljb249XCJQbHVzXCI+XG4gICAg5Yib5bu6XG4gIDwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIGF1dG8taW5zZXJ0LXNwYWNlIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCIgOmljb249XCJQbHVzXCI+XG4gICAgPHRlbXBsYXRlICNpY29uPlxuICAgICAgPFBsdXM+PC9QbHVzPlxuICAgIDwvdGVtcGxhdGU+XG4gICAg5Yib5bu6XG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)
