### ISSUE TITLE
[Bug Report] ElFormItem component lose resetField and clearValidate methods

### ISSUE THREAD

**Issue by xiaohulu** [element-plus/element-plus#1660]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10/firefox86

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-vmm1c?file=/src/App.vue

### Steps to reproduce
```vue
<template>
  <div>
    <el-form>
      <el-form-item ref='formItemRef'>
          <el-input v-model="value"></el-input>
      </el-form-item>
    </el-form>
  </div>
</template>
<script>
import { ref } from 'vue'
export default {
  setup(){
    const value = ref('')
    const formItemRef = ref();

    formItemRef.value.resetField();

    return {
      value,
      formItemRef
    }
  }
};
</script>

```

```
TypeError
formItemRef.value is undefined
setup
/src/App.vue:21:4

  18 | const value = ref('')
  19 | const formItemRef = ref();
  20 | 
> 21 | formItemRef.value.resetField();
  22 | 
  23 | return {
  24 |   value,
```

### What is Expected?
can call resetFiled or clearValidate  method at ElFormItem

### What is actually happening?
can not find resetField or clearValidate  method

**Comment by Ryan2128** [comment]
Please read vue3's docs.

The component and its dom has not been rendered in `setup`. You should put it into the hook of `onMounted`.

**Comment by xiaohulu** [comment]
@Ryan2128 I put `formItemRef.value.resetField();` into `onMounted`, `resetField` also does NOT found. Please get to the point.

see https://codesandbox.io/s/element-plus-spa-forked-vmm1c?file=/src/App.vue

```
  17 | const formItemRef = ref();
  18 | 
  19 | onMounted(() => {
> 20 |   formItemRef.value.resetField();
     |                    ^
  21 | });
  22 | 
  23 | return {
```

**Comment by Ryan2128** [comment]
Next version available.

**Comment by xiaohulu** [comment]
@Ryan2128  谢谢(Thanks!)
