### ISSUE TITLE
[bug report] multiple animations of navmenu component

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1661]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
Microsoft Edge 版本 89.0.774.48 (官方内部版本) (64 位)

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/sorrowx/pen/OJbYKao

### Steps to reproduce
1. 打开 https://codepen.io/sorrowx/pen/OJbYKao
2. 鼠标移到菜单上的 ’我的工作台ui‘ 上
3. 移开，移入，移开....
4. 重复着，仔细看着下拉的过度动画，你会发现有2个动画，一个是el-fade-in-linear，一个是el-zoom-in-left/el-zoom-in-top

### What is Expected?
1. 希望只有一个过度动画，没有残影

### What is actually happening?
1. 有2个过度动画

### 问题及解决方案(仅供参考)

问题是:

![image](https://user-images.githubusercontent.com/20411966/111607133-eeac7300-8812-11eb-861c-4cde79b204be.png)

ElPopper组件的默认插槽内容也使用了一个transition 组件来进行动画，其实ElPopper组件的内容本身自带transition动画

![image](https://user-images.githubusercontent.com/20411966/111607467-3d5a0d00-8813-11eb-8ce8-fabc5e044d58.png)

所以就重复了。

解决方案:

![image](https://user-images.githubusercontent.com/20411966/111607880-a04ba400-8813-11eb-81dd-cee40faa8783.png)

上面方案我在本地测试了，没毛病.
如果该解决方案可行的话，我提个pr.

**Comment by SorrowX** [comment]
@Liiked 大哥，其实我也发现另一个问题，就是折叠的时候，会出现卡顿
https://element-plus.gitee.io/#/zh-CN/component/menu 官网最后一个例子，你来回切换，就会出现这个bug. 虽然我们用户可以通过函数节流来稀释函数的调用频率，从而防止这个问题。但是目前看着就挺难受的。

https://user-images.githubusercontent.com/20411966/112103471-c5aa2a80-8be4-11eb-8c2a-2e7f08558df8.mp4

**Comment by SorrowX** [comment]
@Liiked 刚才我改了下源码，虽然这个bug解决了，但是我没找到产生这个问题的根本原因，我可能需要跟一下BaseTransition的源码，才能找出原因。大佬如果你找出原因，麻烦告知下。


https://user-images.githubusercontent.com/20411966/112104009-934cfd00-8be5-11eb-8fb5-9e9879188b9f.mp4

**Comment by SorrowX** [comment]
@Liiked 上面视频动画卡顿的原因：

1. 动画不卡顿的前提，需要挨个执行 beforeLeave leave beforeEnter enter afterEnter这5个钩子，当old元素ul执行beforeLeave后保存el.dataset.scrollWidth值，执行 leave钩子后，给ul添加'.horizontal-collapse-transition'类，且设置el的宽度，从而达到宽度的伸缩动画,因为使用的'out-in'先出后进模式,老元素ul先出去，之后渲染一个占位节点,然后transition内部重新更新组件，新的ul元素执行 beforeEnter enter afterEnter这3个钩子，分别添加opacity值和.el-opacity-transition类，然后再移除.el-opacity-transition类和重置opacity。这应该是你写ElMenuCollapseTransition组件的原理。

2. 但是上面的视频，可以看出，点的快时，会出现卡顿。这里会存在这么一种情况：
   新元素未完全进入之前，又执行了离开的钩子，这样就会执行  beforeEnter enter beforeLeave leave这4个钩子,可以发现没有触发 afterEnter钩子，这会导致，新元素执行 leave钩子时，添加.horizontal-collapse-transition类无效，因为上面添加过.el-opacity-transition类，这个el-opacity-transition类会覆盖.horizontal-collapse-transition类，所以ul元素宽度伸缩时动画就出问题了。

解决方案：
 1.既然点的快的时候没有执行beforeEnter钩子，那就手动触发他

 2.enter 钩子可以多提供一个参数，这样transitionnene内部会把执行权交给我们开发者
```js
enter(el, done) {
    addClass(el, 'el-opacity-transition')
    el.style.opacity = 1
    done()
}
```

 3.这样就解决了问题，但是我没测其他情况

 4. 有时间我使用BaseTransition组件改写下试试


所以上面仅供参考

**Comment by JeremyWuuuuu** [comment]
Thanks for the detailed reply and explanation! ❤️

**Comment by SorrowX** [comment]
> Thanks for the detailed reply and explanation! ❤️

这次我的解释，我也很虚，仅做参考
![image](https://user-images.githubusercontent.com/20411966/112718324-3f1b8300-8f2d-11eb-9e68-4eaf608d6809.png)

**Comment by BoBoooooo** [comment]
遇到同样的问题 等待修复!

**Comment by SorrowX** [comment]
这个issues应该可以关闭了，你拉下最新的代码试试
@BoBoooooo

**Comment by BoBoooooo** [comment]
@SorrowX 

我本地升级到beta36了。

el-menu在折叠的时候似乎还是有卡顿。

http://server.boboooooo.top:9995 

有一个线上demo  账号admin密码123

**Comment by SorrowX** [comment]
@BoBoooooo 
你这之前也是这样吗？
你这不是卡，这卡到不行啊，使用姿势对吗？
地址代码是压缩的代码，看不懂

**Comment by BoBoooooo** [comment]
@SorrowX 感谢，我再寻思寻思。可能有什么样式冲突。

**Comment by SorrowX** [comment]
@BoBoooooo 
你可以尝试下改下布局方式，参考下https://github.com/PanJiaChen/vue-element-admin ，挺好的

**Comment by sxzz** [comment]
Can someone check if this problem still exists?

**Comment by SorrowX** [comment]
> Can someone check if this problem still exists?

这个帖子应该包含了2个问题，一个是我当时提的，修复了。还有一个是@BoBoooooo 大兄弟提的，不知道他的问题解决了没，当时他给的问题链接，代码是压缩的,看不出问题所在。后来他说再寻思寻思 @sxzz

**Comment by sxzz** [comment]
Thanks. Feel free to open a new question please if @BoBoooooo has questions,
