### ISSUE TITLE
[Component] [table] Sortable El-Table

### ISSUE THREAD

**Issue by leeobrum** [element-plus/element-plus#16618]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.24`
- Element Plus Version: `2.7.1`
- Browser / OS: `Edge`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZGF0YSA9IHJlZihbXG57bkNoZWNraW46ICcxJ30sXG57bkNoZWNraW46ICc1J30sXG57bkNoZWNraW46ICcxMDAnfSxcbntuQ2hlY2tpbjogJzMzMyd9LFxue25DaGVja2luOiAnNCd9LFxue25DaGVja2luOiAnTmV2ZXIgUmVhbGl6ZWQnfSBcbl0pXG5cbmNvbnN0IHNvcnRDaGFuZ2UgPSAoZGF0YTogeyBwcm9wOiBhbnk7IG9yZGVyOiBhbnk7IH0pID0+IHtcbiAgY29uc3QgeyBwcm9wLCBvcmRlciB9ID0gZGF0YVxuICBzb3J0QnlJRChvcmRlciwgcHJvcClcbn1cbmNvbnN0IHNvcnRCeUlEID0gKG9yZGVyOiBzdHJpbmcsIHByb3A6IHN0cmluZykgPT4ge1xuICBjb25zdCBwcm9wTWFwID0ge1xuICAgICduQ2hlY2tpbic6ICduQ2hlY2tpbidcbiAgfVxuXG4gIGNvbnN0IGNvbXBhcmVGdW5jdGlvbiA9IChhOiB7IFt4OiBzdHJpbmddOiBhbnkgfSwgYjogeyBbeDogc3RyaW5nXTogYW55IH0pID0+IHtcbiAgICBjb25zdCBhVmFsdWUgPSBwcm9wTWFwW3Byb3BdID8gYVtwcm9wTWFwW3Byb3BdXSA6IHVuZGVmaW5lZFxuICAgIGNvbnN0IGJWYWx1ZSA9IHByb3BNYXBbcHJvcF0gPyBiW3Byb3BNYXBbcHJvcF1dIDogdW5kZWZpbmVkXG5cbiAgICBpZiAob3JkZXIgPT09ICdhc2NlbmRpbmcnKSB7XG4gICAgICByZXR1cm4gYVZhbHVlID09PSBiVmFsdWUgPyAwIDogYVZhbHVlID4gYlZhbHVlID8gMSA6IC0xXG4gICAgfSBlbHNlIGlmIChvcmRlciA9PT0gJ2Rlc2NlbmRpbmcnKSB7XG4gICAgICByZXR1cm4gYVZhbHVlID09PSBiVmFsdWUgPyAwIDogYVZhbHVlIDwgYlZhbHVlID8gMSA6IC0xXG4gICAgfVxuICB9XG5cbiAgZGF0YS52YWx1ZS5zb3J0KGNvbXBhcmVGdW5jdGlvbilcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZVxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgQHNvcnQtY2hhbmdlPVwic29ydENoYW5nZVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiQ2hlY2tpblwiIHByb3A9XCJuQ2hlY2tpblwiIHNvcnRhYmxlIGFsaWduPVwiY2VudGVyXCIgLz5cbiAgPC9lbC10YWJsZT5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

use sortable

### What is Expected?

order correctly

### What is actually happening?

The function is ordering wrong

### Additional comments

Maybe I don't know how to do it, but I wasted some time on this and couldn't solve it.

**Comment by zeyongTsai** [comment]
The comparison of magnitude between strings is different from numbers. If you expect numerical magnitude ordering, please convert them to numbers before making the comparison.

**Comment by leeobrum** [comment]
@zeyongTsai I understood
but, I will show numbers in the field and I will need to show string when the field is empty, that's the problem.

**Comment by adapt0** [comment]
Couple of things to keep in mind:

* el-table can sort the data for you (see `sort-method`), no need to mutate your data directly (don't use data.value.sort)
* similarly el-table handles ascending/descending order, no need to mutate data for that either
* sort comparison function argument order is not guaranteed. Consider compareFunction('333', 'Never Realized')

Here's an updated example which uses `sort-method`, will sort the mixture of strings & numbers, and doesn't mutate the data:
 [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgZGF0YSA9IHJlZihbXG4gIHtuQ2hlY2tpbjogJzEnfSxcbiAge25DaGVja2luOiAnNSd9LFxuICB7bkNoZWNraW46ICcxMDAnfSxcbiAge25DaGVja2luOiAnMzMzJ30sXG4gIHtuQ2hlY2tpbjogJzQnfSxcbiAge25DaGVja2luOiAnTmV2ZXIgUmVhbGl6ZWQnfSBcbl0pXG5cbmZ1bmN0aW9uIHNvcnRGdW5jdGlvbihwcm9wOiBzdHJpbmcsIGE6IHsgW3g6IHN0cmluZ106IGFueSB9LCBiOiB7IFt4OiBzdHJpbmddOiBhbnkgfSkge1xuICBjb25zdCBhU3RyID0gYVtwcm9wXVxuICBjb25zdCBiU3RyID0gYltwcm9wXVxuICBsZXQgYU51bSA9IE51bWJlcihhU3RyKVxuICBsZXQgYk51bSA9IE51bWJlcihiU3RyKVxuICBpZiAoaXNOYU4oYU51bSkgfHwgaXNOYU4oYk51bSkpIHJldHVybiBhU3RyLmxvY2FsZUNvbXBhcmUoYlN0cilcbiAgcmV0dXJuIGFOdW0gLSBiTnVtXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICA6ZGF0YT1cImRhdGFcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgbGFiZWw9XCJDaGVja2luXCJcbiAgICAgIHByb3A9XCJuQ2hlY2tpblwiXG4gICAgICBhbGlnbj1cImNlbnRlclwiXG4gICAgICA6c29ydC1tZXRob2Q9XCJzb3J0RnVuY3Rpb24uYmluZCh1bmRlZmluZWQsICduQ2hlY2tpbicpXCJcbiAgICAgIHNvcnRhYmxlXG4gICAgLz5cbiAgPC9lbC10YWJsZT5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by leeobrum** [comment]
@adapt0 you helped me a lot, thank you!! xd
