### ISSUE TITLE
[Component] el-form、el-form-item、el-select配合使用异常

### ISSUE THREAD

**Issue by XuJianChen1999** [element-plus/element-plus#16625]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.1`
- Browser / OS: `Windows Chrome 124.0.6367.61`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybVwiIGxhYmVsLXdpZHRoPVwiYXV0b1wiIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCI+XG4gICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwicGxlYXNlIHNlbGVjdCB5b3VyIHpvbmVcIj5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgb25lXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG4vLyBkbyBub3QgdXNlIHNhbWUgbmFtZSB3aXRoIHJlZlxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgcmVnaW9uOiAnJyxcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IlxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1、使用el-form、el-form-item、el-select进行数据展示
2、点击el-form-item的label区域仍然能触发el-select的下拉选项展示

### What is Expected?

点击el-form-item的label区域不展示el-select下拉选项展示，希望只有点击el-select的区域才出发下拉选项

### What is actually happening?

点击el-form-item后仍然展示el-options选项

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#9752
