### ISSUE TITLE
[Component] [select] el-select 组件在 el-form 组件添加 inline 属性的包裹下，宽度丢了

### ISSUE THREAD

**Issue by HJ1281581411** [element-plus/element-plus#16649]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.7.1`
- Browser / OS: `Chrome 124.0.6367.79`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbmFtZSA9IHJlZignJylcbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gaW5saW5lPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJOYW1lXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm5hbWVcIiAgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cblxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJTZWxlY3RcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgID5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIjFcIiA6dmFsdWU9XCIxXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIjJcIiA6dmFsdWU9XCIyXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIjNcIiA6dmFsdWU9XCIzXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-select 组件在 el-form 组件添加 inline 属性的包裹下，宽度丢了

### What is Expected?

el-select 组件在 el-form 组件添加 inline 属性的包裹下，修复宽度丢失问题

### What is actually happening?

el-select 组件在 el-form 组件添加 inline 属性的包裹下，宽度丢了

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/15352
