### ISSUE TITLE
[Component] [All] DateTimePicker 日期时间选择器选择都选择当天日期后输入开始时间再输入结束时间开始时间显示有问题

### ISSUE THREAD

**Issue by cluyun** [element-plus/element-plus#16667]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.1`
- Browser / OS: `最新`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E8%8C%83%E5%9B%B4)

### Steps to reproduce

1、点日期框（此时会弹出日期选择，有左边和右边两个）
2、左边开始面板选16日，右边也选16日
3、在左边时间框上面输入时间：16:00:00（此时你会发现第一个问题，他会从00:00:00变成当前时间）
4、在右边时间框上面输入时间：16:40:00（此时发现第二个问题，第一个时间框时间变成了一个莫名其妙的值）

### What is Expected?

输入时间的时候，值不要变，按我输入的来

### What is actually happening?

时间总是会发生变化，自动变，不可控，没有任何属性和方法可以控制这个现象

### Additional comments

我希望知道当前版本的临时解决方案

![1](https://github.com/element-plus/element-plus/assets/33676184/06ef96f5-85f7-42b4-bfe3-2dd806e568d4)

**Comment by cluyun** [comment]
1

**Comment by cluyun** [comment]
![1](https://github.com/element-plus/element-plus/assets/33676184/d21378e1-0724-4432-b627-84bc449aa4fd)

**Comment by Liao-js** [comment]
你可以先输入结束时间，再输入开始时间就不会变了，结束时间 > 开始时间。
看动图开始时间会改变的原因：你输入的时候，结束时间就已经在判断是否大于开始时间了，发现开始时间 > 结束时间的时候，就会导致开始时间 = 结束时间

**Comment by cluyun** [comment]
> 你可以先输入结束时间，再输入开始时间就不会变了，结束时间 > 开始时间。 看动图开始时间会改变的原因：你输入的时候，结束时间就已经在判断是否大于开始时间了，发现开始时间 > 结束时间的时候，就会导致开始时间 = 结束时间

用户提的。我是开发。只负责解决问题
