### ISSUE TITLE
[bug report] messgebox uses instance to modify message in beforeclose, but it doesn't respond

### ISSUE THREAD

**Issue by feenn** [element-plus/element-plus#1666]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
Win10, Chrome 89

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/feenn/pen/ZEBdrme

### Steps to reproduce
使用了doc中提供的例子，尝试修改未达到预期。该功能在element-ui 2.x版本中运行正常。

### What is Expected?
message修改为新值并正确render

### What is actually happening?
message没有被渲染出来

**Comment by Ryan2128** [comment]
Will be fixed soon.
