### ISSUE TITLE
[Docs] [drawer] el-drawer使用文档书写错误

### ISSUE THREAD

**Issue by traveler-h** [element-plus/element-plus#16671]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.1`
- Browser / OS: `Chrome最新版`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/drawer.html#%E4%BA%8B%E4%BB%B6)

### Steps to reproduce

https://element-plus.gitee.io/zh-CN/component/drawer.html#%E4%BA%8B%E4%BB%B6
事件名称写错了

### What is Expected?

事件名称

### What is actually happening?

插槽名称

### Additional comments

_(empty)_

**Comment by btea** [comment]
谢谢反馈，已修改。 https://crowdin.com/editor/element-plus/851/en-zhcn?view=comfortable&filter=basic&value=0
