### ISSUE TITLE
[Style] 所有弹窗都会为body添加.el-popup-parent--hidden类，其中overflow: hidden属性会导致窗口滚动条位置重置

### ISSUE THREAD

**Issue by Ketuer** [element-plus/element-plus#16687]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-drawer`
- `el-message-box`

### Reproduction Link

[Link]()

### Steps to reproduce

直接添加一个高度很大的盒子，扩展整个body高度，使浏览器出现滚动条，此时向下滚动一定位置，当打开抽屉或者出现弹窗时，页面直接跳到顶部，滚动高度被重置。

### What is Expected?

不应该影响滚动高度

### What is actually happening?

.el-popup-parent--hidden包含overflow: hidden样式导致滚动位置跳回顶部

### Additional comments

_(empty)_

**Comment by FrontEndDog** [comment]
请提供一个复现链接   以便我们定位问题   谢谢
