### ISSUE TITLE
[Component] [upload] 使用el-upload的时候，请求头参数设置无效

### ISSUE THREAD

**Issue by 136323000** [element-plus/element-plus#16683]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `Windows`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IlxuPHNjcmlwdCAgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHVwbG9hZFJlZiA9IHJlZihcIlwiKVxuXG5cbmNvbnN0IGhlYWRlcnNSZWYgPSByZWYoe1xuICBcInRva2VuXCI6IFwiMTIzXCJcbn0pXG5cbjwvc2NyaXB0PlxuXG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZWwtdXBsb2FkIHJlZj1cInVwbG9hZFJlZlwiIGNsYXNzPVwidXBsb2FkLWRlbW9cIiBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgICAgICA6YXV0by11cGxvYWQ9XCJ0cnVlXCJcbiAgICAgICAgOmhlYWRlcnM9XCJoZWFkZXJzUmVmXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdHJpZ2dlcj5cbiAgICAgICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5zZWxlY3QgZmlsZTwvZWwtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuXG5cbiAgICAgICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAgICAgICAgICBqcGcvcG5nIGZpbGVzIHdpdGggYSBzaXplIGxlc3MgdGhhbiA1MDBrYlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

<script  setup>
import { ref } from 'vue'

const uploadRef = ref("")

const headersRef = ref({
  "token": "123"
})

</script>

<template>
    <el-upload ref="uploadRef" class="upload-demo" action="https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15"
        :auto-upload="true"
        :headers="headersRef">
        <template #trigger>
            <el-button type="primary">select file</el-button>
        </template>

        <template #tip>
            <div class="el-upload__tip">
                jpg/png files with a size less than 500kb
            </div>
        </template>
    </el-upload>
</template>

### What is Expected?

我希望在上传文件的时候可以将 header里的"token": "123"传到我的服务器

### What is actually happening?

实际什么都没传

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
我看请求头中是有 token:123
![截图](https://github.com/element-plus/element-plus/assets/43257608/c5a6b30e-8c6d-4add-b535-aa4f8509213b)

**Comment by 136323000** [comment]
哦哦 不好意思 可能是我看错了
