### ISSUE TITLE
[Bug Report] pagination component, select the number of items per page, it will trigger the current page event

### ISSUE THREAD

**Issue by vincentSea** [element-plus/element-plus#1668]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
mac os

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-el-pagination-7oivr

### Steps to reproduce
when the number of pages for the last page, select the number of entries per page, trigger current-change events, but also trigger size-change event
当页数为最后一页，选择每页显示条目个数，触发current-change事件，同时也触发size-change事件

### What is Expected?
When the number of pages for the last page, select the number of entries per page, only trigger the current-change event
当页数为最后一页，选择每页显示条目个数，只触发current-change事件

### What is actually happening?
 trigger current-change and  size-change event
触发current-change事件，同时也触发size-change事件

**Comment by iendeavor** [comment]
IMHO, there should be an event which is emitted after both (or one) of current-change and size change, it would be more useful.

**Comment by Ryan2128** [comment]
> When the number of pages for the last page, select the number of entries per page, only trigger the current-change event

I think this is the correct behavior.

Your main behavior is to change the `page-size`, so the `size-change` event is emitted. Because the `page-size` is changed, the `current-page` is changed, so the `current-change` event is emitted. There is no problem.

**Comment by betterliyu** [comment]
We need to call API to get new data once page size or page number changed.  As you said, it will trigger `current-change` event under certain circumstances, then the API must be called twice. How we can prevent it?
