### ISSUE TITLE
[Component] [pagination] 2.7.2版本的el-pagination组件内部的jumper组件使用了el-input组件的label属性导致控制台报警告

### ISSUE THREAD

**Issue by wen-lun** [element-plus/element-plus#16681]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXBhZ2luYXRpb24gbGF5b3V0PVwicGFnZXIsIGp1bXBlclwiIDp0b3RhbD1cIjEwMDBcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbi8vIGVsLXBhZ2luYXRpb27nu4Tku7blhoXpg6jnmoRqdW1wZXLlnKjkvb/nlKhlbC1pbnB1dOaXtu+8jOS9v+eUqOS6hmxhYmVs5bGe5oCn77yM6ICM5LiN5piv5pyA5paw55qEYXJpYS1sYWJlbO+8jFxuLy8g5LuO6ICM5a+86Ie05byA5Y+R546v5aKD5Lya5oql6K2m5ZGK77yaW2VsLWlucHV0XSBbQVBJXSBsYWJlbCBpcyBhYm91dCB0byBiZSBkZXByZWNhdGVkIGluIHZlcnNpb24gMi44LjAsIHBsZWFzZSB1c2UgYXJpYS1sYWJlbCBpbnN0ZWFkLlxuLy8g55Sx5LqO6L+Z6YeM5piv55Sf5Lqn546v5aKD77yM5omA5Lul5rKh5pyJ6K2m5ZGK6L6T5Ye6XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

开发环境使用el-pagination组件，layout属性包含jumper

### What is Expected?

控制台不打印警告信息

### What is actually happening?

控制台打印警告：[el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.

### Additional comments

_(empty)_

**Comment by jiaozhiye** [comment]
发版之前内部组件都不做基本的测试吗？基础组件api有破坏性变化，都不想着排查一下所有使用这个组件的其他组件吗？哪怕做一次简单的全局搜索也能发现这种低级的错误吧！

**Comment by linghe0530** [comment]
main.ts:18 ElementPlusError: [el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.

**Comment by 111504** [comment]
main.js:41 ElementPlusError: [el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.
