### ISSUE TITLE
[Component] [anchor] anchor在最底部高度不足的情况下,无法滑动到最后的条目

### ISSUE THREAD

**Issue by singlerace** [element-plus/element-plus#16698]
![Snipaste_2024-04-29_10-09-36](https://github.com/element-plus/element-plus/assets/26650843/84c9791c-c23d-41c9-9cec-c68d961dfc1f)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-anchor`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues)

### Steps to reproduce

anchor在最底部高度不足时,无法滑动到最后的条目,element plus的官网也是这种情况

### What is Expected?

anchor可以将选中条目滑动到最后一个

### What is actually happening?

底部高度不足时,anchor的选中条目不能滑动到最后一个条目

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/26650843/3bfc210c-cabc-419d-ac28-d3f4d291ed1f)

**Comment by kooriookami** [comment]
是的，这个是根据顶部计算的

**Comment by singlerace** [comment]
> 是的，这个是根据顶部计算的

那这不算bug吗?

**Comment by kooriookami** [comment]
不算bug呀，确实没滚动到对应位置。

**Comment by singlerace** [comment]
![image](https://github.com/element-plus/element-plus/assets/26650843/66747660-838d-40db-936d-88079bcb54a2)
vue的官网可以在高度不足的情况下滚动到最后一个条目

**Comment by kooriookami** [comment]
https://github.com/element-plus/element-plus/assets/38392315/85046834-7761-40c5-9e03-a35dc06b28f0

我看了一下，vue的页面滚动到底就强制把锚点高亮最后一个。但是中间的锚点就会有问题了，看上面视频倒数第二个锚点被跳过了。

**Comment by singlerace** [comment]
> QQ2024430-102649-HD.mp4 
> 我看了一下，vue的页面滚动到底就强制把锚点高亮最后一个。但是中间的锚点就会有问题了，看上面视频倒数第二个锚点被跳过了。

还真没注意,感谢解答
