### ISSUE TITLE
[Component] [message-box] ELMessageBox组件使用center:true的时候，icon在title前面，如果不是center:true，icon就在内容那一行。

### ISSUE THREAD

**Issue by xialeyixia** [element-plus/element-plus#16695]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.23`
- Element Plus Version: `2.7.2`
- Browser / OS: `chrome/windows`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBvbkNlbnRlciA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oXCLmgqjlpb3vvIznoa7orqTliKDpmaTlkJfvvJ9cIiwgXCLmj5DphpJcIiwge1xuICAgIHR5cGU6IFwid2FybmluZ1wiLFxuICAgIGNlbnRlcjogdHJ1ZVxuICB9KS50aGVuKCkuY2F0Y2goKVxufVxuY29uc3Qgb25Ob3RDZW50ZXIgPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKFwi5oKo5aW977yM56Gu6K6k5Yig6Zmk5ZCX77yfXCIsIFwi5o+Q6YaSXCIsIHtcbiAgICB0eXBlOiBcIndhcm5pbmdcIixcbiAgfSkudGhlbigpLmNhdGNoKClcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib25DZW50ZXJcIj7lsYXkuK1jb25maXJtPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib25Ob3RDZW50ZXJcIj7pnZ7lsYXkuK1jb25maXJtPC9lbC1idXR0b24+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1、点击居中居中confirm按钮
2、点击非居中confirm按钮

### What is Expected?

点击两个按钮的时候，提醒的黄色icon都在title那一行

### What is actually happening?

点击居中居中confirm按钮时提醒的黄色icon在title那一行，点击非居中confirm按钮提醒的黄色icon在内容那一行

### Additional comments

_(empty)_

**Comment by xialeyixia** [comment]
![image](https://github.com/element-plus/element-plus/assets/54968667/3568862c-99a0-4389-9a45-c78f2b6d4ad4)
![image](https://github.com/element-plus/element-plus/assets/54968667/d25cd6ef-7c8b-4289-a072-0274988f02ac)

**Comment by warmthsea** [comment]
设计如此
