### ISSUE TITLE
Is this a document problem

### ISSUE THREAD

**Issue by wike2019** [element-plus/element-plus#1669]
现在到文档对新API不友好 很多组件还是要用data method，是文档没更新还是为了兼容老项目。

![image](https://user-images.githubusercontent.com/5925704/111807078-8ee6c280-890d-11eb-990a-e2f871d4fda6.png)

例如这个 明显是vue2的语法啊

**Comment by 0song** [comment]
Options API is still available and recommended in Vue 3 https://v3.vuejs.org/api/options-api.html.

Still, we will use Vue composition API in some of the components document to make the demo code clear.
