### ISSUE TITLE
[Component] [table] cdn script 标签方式使用 table 组件，表头显示有问题

### ISSUE THREAD

**Issue by bruce-teng** [element-plus/element-plus#16708]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0'`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/bruce-teng/pen/dyLLVGY)

### Steps to reproduce

cdn 方式使用
只单独显示一个最简单的表格组件

### What is Expected?

表格显示正常

### What is actually happening?

表格头显示有问题

### Additional comments

_(empty)_

![Uploading 运行结果.gif…]()

**Comment by bruce-teng** [comment]
![运行结果](https://github.com/element-plus/element-plus/assets/24269297/3038cf44-ec4d-48b8-8f97-99401a4d151e)

**Comment by chenxch** [comment]
请使用闭标签，建议先在issue中搜索后再提交问题。
