### ISSUE TITLE
[Component] [form] form 为何不提供类似getFieldsvalue方法（动态表单，表单项能到达30+）

### ISSUE THREAD

**Issue by sanmuw** [element-plus/element-plus#16719]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/mac`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIFxuIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgdi1pZj1cImlzTW91bnRlZFwiPlxuICAgIDxkaXYgdi1pbmZpbml0ZS1zY3JvbGw9XCJsb2FkXCIgXG5pbmZpbml0ZS1zY3JvbGwtZGlzdGFuY2U9XCIyMFwiXG4gICAgICAgICBzdHlsZT1cImhlaWdodDoyMDBweDtcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgICAgICAgICAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmRpc2FibGVkPVwiaXRlbS5kaXNhYmxlZFwiXG4gICAgLz5cbiAgICA8L2Rpdj5cblxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbiAgXG4gIGNvbnN0IGlzTW91bnRlZCA9IHJlZihmYWxzZSlcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbiAgICB7XG4gICAgdmFsdWU6ICdPcHRpb242JyxcbiAgICBsYWJlbDogJ09wdGlvbjYnLFxuICB9LFxuICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uNycsXG4gICAgbGFiZWw6ICdPcHRpb243JyxcbiAgfSxcbiAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sXG4gICAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSwgICAgICB7XG4gICAgdmFsdWU6ICdPcHRpb244JyxcbiAgICBsYWJlbDogJ09wdGlvbjgnLFxuICB9LCAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSxcbl0pXG5cbiBjb25zdCBsb2FkID0gKCkgPT4ge1xuIC8v5byC5q2l6I635Y+W5pWw5o2u5Ye95pWw77yM6L+Z6YeM55qEZGVib3VuY2XmmK/miJHoh6rlt7HlsIHoo4XnmoTpmLLmipblh73mlbDvvIzkuI3nhLbkvJrmnInkuIvmi4nkuIDmrKHor7fmsYLkuKTmrKHnmoTpl67popjjgIJcbiAgIGNvbnNvbGUubG9nKDEyMylcbiAgIG9wdGlvbnMudmFsdWUucHVzaCh7XG4gICAgICAgICB2YWx1ZTogJ09wdGlvbjEwJyxcbiAgICBsYWJlbDogJ09wdGlvbjEwJyxcbiAgIH0pXG4gfTtcblxub25Nb3VudGVkKCgpID0+IHtcbiAgaXNNb3VudGVkLnZhbHVlID0gdHJ1ZVxufSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

无

### What is Expected?

能获取getFeildsvalue类型的api

### What is actually happening?

没有

### Additional comments

动态表单能获取到的展示的表单项值，而不是model所有的字段

**Comment by Fuphoenixes** [comment]
因为vue是双向绑定，直接通过`model.xxx`就可以动态获取对应项的当前值了。你是刚从react antd 那边转过来吗？建议你去看 Ant Design Vue 都不用提供 `getFieldsvalue` 方法。

**Comment by sanmuw** [comment]
> 因为vue是双向绑定，直接通过`model.xxx`就可以动态获取对应项的当前值了。你是刚从react antd 那边转过来吗？建议你去看 Ant Design Vue 都不用提供 `getFieldsvalue` 方法。

antd vue 它可以通过finish拿到values

**Comment by Fuphoenixes** [comment]
抱歉是我看错了，你是想通过类似`getFieldsvalue`的手段获取当前所有注册了的表单项的值。后续可以考虑添加对应api，同时也欢迎你来贡献！

**Comment by sanmuw** [comment]
> 抱歉是我看错了，你是想通过类似`getFieldsvalue`的手段获取当前所有注册了的表单项的值。后续可以考虑添加对应api，同时也欢迎你来贡献！
是我表达的问题，哈哈哈。有机会一定来贡献 codes

**Comment by xylplm** [comment]
+1 希望提供一个能够拿到表单所有的对象值，用于表单直接提交。而不是一个一个取值

**Comment by FrontEndDog** [comment]
fixed by #16755
