### ISSUE TITLE
[Style] [All] Custom namespace，vue3+vite失败

### ISSUE THREAD

**Issue by arrayListTwo** [element-plus/element-plus#16745]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.26`
- Element Plus Version: `2.7.2`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/arrayListTwo/cus-element-plus)

### Steps to reproduce

自定义命名空间失败，:root注入的样式依旧是以 --el开头

### What is Expected?

样式正常

### What is actually happening?

样式丢失

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
看你项目没有引用设置 SCSS 和 CSS 变量的文件
```
@forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
  $namespace: 'ep'
);
```

**Comment by arrayListTwo** [comment]
> 看你项目没有引入设置 SCSS 和 CSS 变量的文件
> 
> ```
> @forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
>   $namespace: 'ep'
> );
> ```
创建了变量文件并且在vite.config.js中引入了
![15d7b467-0c93-4f90-b475-c661eb625139](https://github.com/element-plus/element-plus/assets/14231989/6d734b12-d0fa-4c60-b6cb-38893cf201ec)
![{EB9FB959-B697-4356-8D14-09F45C40C341}](https://github.com/element-plus/element-plus/assets/14231989/45a0b94c-7934-4dd3-813b-fa677863cee4)

启动项目，在root中注入的依旧是 el 开头的变量

**Comment by Liao-js** [comment]
因为你的 mian.js 文件导入样式使用的是`import 'element-plus/dist/index.css'`，这个是打包后的产物，是不会改变的。
所以你需要导入使用 `import 'element-plus/theme-chalk/src/index.scss'` 来导入样式，这样变量才能加入进去

**Comment by arrayListTwo** [comment]
> 因为你的 mian.js 文件导入样式使用的是`import 'element-plus/dist/index.css'`，这个是打包后的产物，是不会改变的。 所以你需要导入使用 `import 'element-plus/theme-chalk/src/index.scss'` 来导入样式，这样变量才能加入进去

感谢指点，确实如此，已可以自定义命名空间，谢谢~
