### ISSUE TITLE
How to add effective blocking default behavior to render function `h` wheel event? I've tried many methods, but to no avail.

### ISSUE THREAD

**Issue by warmthsea** [element-plus/element-plus#16742]
https://github.com/element-plus/element-plus/blob/8662178484ca80e297bc74de72db9cd3aa724001/packages/components/virtual-list/src/builders/build-grid.ts#L651

https://github.com/element-plus/element-plus/blob/8662178484ca80e297bc74de72db9cd3aa724001/packages/components/virtual-list/src/builders/build-list.ts#L521

![image](https://github.com/element-plus/element-plus/assets/45450994/4744fa8c-2149-4b3a-8b03-dc7ecc1c0cd0)

https://staging.element-plus.org/zh-CN/component/select-v2.html

![image](https://github.com/element-plus/element-plus/assets/45450994/701dbd65-3d0e-47f6-a8b8-1ef9097136bd)

**Comment by btea** [comment]
`withModifiers` does not support setting `passive`. To set `passive`, bind it directly through addEventListener or use `withDirectives` to configure it.
