### ISSUE TITLE
[Bug Report] El-select should reset the placeholder after clear when both of multiple and filterable are true

### ISSUE THREAD

**Issue by iendeavor** [element-plus/element-plus#1674]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
macOS 10.15.7

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-g24es?file=/src/App.vue

### Steps to reproduce
1. click the tag close icon.

### What is Expected?
Placeholder should appear

### What is actually happening?
Placeholder is empty string

**Comment by Ryan2128** [comment]
Will be fixed soon.
