### ISSUE TITLE
[Component] [input-number] el-input-number 不显示样式

### ISSUE THREAD

**Issue by bbhxwl** [element-plus/element-plus#16754]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.0`
- Browser / OS: `win10`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground]()

### Steps to reproduce

样式不显示
![image](https://github.com/element-plus/element-plus/assets/26525599/882f2bc0-98ed-4614-89d9-6d18e1b4d2f3)

### What is Expected?

样式不显示

### What is actually happening?

样式不显示

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
请提供一个最小复现
