### ISSUE TITLE
[Component] [select] ElForm设置inline属性时ElSelect宽度丢失

### ISSUE THREAD

**Issue by GuoJikun** [element-plus/element-plus#16753]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.26`
- Element Plus Version: `2.7.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cclxuICA8ZWwtZm9ybVxyXG4gICAgcmVmPVwicnVsZUZvcm1SZWZcIlxyXG4gICAgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4XCJcclxuICAgIDptb2RlbD1cInJ1bGVGb3JtXCJcclxuICAgIDpydWxlcz1cInJ1bGVzXCJcclxuICAgIGxhYmVsLXdpZHRoPVwiYXV0b1wiXHJcbiAgICBjbGFzcz1cImRlbW8tcnVsZUZvcm1cIlxyXG4gICAgOnNpemU9XCJmb3JtU2l6ZVwiXHJcbiAgICBzdGF0dXMtaWNvblxyXG4gICAgaW5saW5lXHJcbiAgPlxyXG4gICAgXHJcbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgem9uZVwiIHByb3A9XCJyZWdpb25cIj5cclxuICAgICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwicnVsZUZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJBY3Rpdml0eSB6b25lXCI+XHJcbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgb25lXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XHJcbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cclxuICAgICAgPC9lbC1zZWxlY3Q+XHJcbiAgICA8L2VsLWZvcm0taXRlbT5cclxuICA8L2VsLWZvcm0+XHJcbjwvdGVtcGxhdGU+XHJcblxyXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxyXG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xyXG5pbXBvcnQgdHlwZSB7IENvbXBvbmVudFNpemUsIEZvcm1JbnN0YW5jZSwgRm9ybVJ1bGVzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xyXG5cclxuaW50ZXJmYWNlIFJ1bGVGb3JtIHtcclxuICBuYW1lOiBzdHJpbmdcclxuICByZWdpb246IHN0cmluZ1xyXG4gIGNvdW50OiBzdHJpbmdcclxuICBkYXRlMTogc3RyaW5nXHJcbiAgZGF0ZTI6IHN0cmluZ1xyXG4gIGRlbGl2ZXJ5OiBib29sZWFuXHJcbiAgbG9jYXRpb246IHN0cmluZ1xyXG4gIHR5cGU6IHN0cmluZ1tdXHJcbiAgcmVzb3VyY2U6IHN0cmluZ1xyXG4gIGRlc2M6IHN0cmluZ1xyXG59XHJcblxyXG5jb25zdCBmb3JtU2l6ZSA9IHJlZjxDb21wb25lbnRTaXplPignZGVmYXVsdCcpXHJcbmNvbnN0IHJ1bGVGb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxyXG5jb25zdCBydWxlRm9ybSA9IHJlYWN0aXZlPFJ1bGVGb3JtPih7XHJcbiAgbmFtZTogJ0hlbGxvJyxcclxuICByZWdpb246ICcnLFxyXG4gIGNvdW50OiAnJyxcclxuICBkYXRlMTogJycsXHJcbiAgZGF0ZTI6ICcnLFxyXG4gIGRlbGl2ZXJ5OiBmYWxzZSxcclxuICBsb2NhdGlvbjogJycsXHJcbiAgdHlwZTogW10sXHJcbiAgcmVzb3VyY2U6ICcnLFxyXG4gIGRlc2M6ICcnLFxyXG59KVxyXG5cclxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZTxGb3JtUnVsZXM8UnVsZUZvcm0+Pih7XHJcbiAgcmVnaW9uOiBbXHJcbiAgICB7XHJcbiAgICAgIHJlcXVpcmVkOiB0cnVlLFxyXG4gICAgICBtZXNzYWdlOiAnUGxlYXNlIHNlbGVjdCBBY3Rpdml0eSB6b25lJyxcclxuICAgICAgdHJpZ2dlcjogJ2NoYW5nZScsXHJcbiAgICB9LFxyXG4gIF0sXHJcbn0pXHJcblxyXG5jb25zdCBzdWJtaXRGb3JtID0gYXN5bmMgKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XHJcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxyXG4gIGF3YWl0IGZvcm1FbC52YWxpZGF0ZSgodmFsaWQsIGZpZWxkcykgPT4ge1xyXG4gICAgaWYgKHZhbGlkKSB7XHJcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcclxuICAgIH0gZWxzZSB7XHJcbiAgICAgIGNvbnNvbGUubG9nKCdlcnJvciBzdWJtaXQhJywgZmllbGRzKVxyXG4gICAgfVxyXG4gIH0pXHJcbn1cclxuXHJcbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xyXG4gIGlmICghZm9ybUVsKSByZXR1cm5cclxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxyXG59XHJcblxyXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XHJcbiAgdmFsdWU6IGAke2lkeCArIDF9YCxcclxuICBsYWJlbDogYCR7aWR4ICsgMX1gLFxyXG59KSlcclxuPC9zY3JpcHQ+XHJcbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

给ElForm设置inline属性就可以直接看到ElSelect组件的宽度丢失

### What is Expected?

ElSelect组件的宽度正常

### What is actually happening?

给ElForm设置inline属性就可以直接看到ElSelect组件的宽度丢失

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
> 组件默认宽度为100%，行内表单会造成组件宽度无法自适应。建议手动设置固定宽度样式

具体查看这个[链接](https://github.com/element-plus/element-plus/issues/15834#issuecomment-1936919229)

**Comment by GuoJikun** [comment]
> > 组件默认宽度为100%，行内表单会造成组件宽度无法自适应。建议手动设置固定宽度样式
> 
> 具体查看这个[链接](https://github.com/element-plus/element-plus/issues/15834#issuecomment-1936919229)

我知道怎么解决这个问题。
这怎么看怎么像是 Bug，form在inline模式下目前就Select组件有这个问题。

**Comment by yanglilong127** [comment]
确实是bug，我固定了使用版本2.4.3就没有问题

**Comment by kooriookami** [comment]
inlin

> > > 组件默认宽度为100%，行内表单会造成组件宽度无法自适应。建议手动设置固定宽度样式
> > 
> > 
> > 具体查看这个[链接](https://github.com/element-plus/element-plus/issues/15834#issuecomment-1936919229)
> 
> 我知道怎么解决这个问题。 这怎么看怎么像是 Bug，form在inline模式下目前就Select组件有这个问题。 ![image](https://private-user-images.githubusercontent.com/21582741/328092237-95a86b54-0122-4503-85cf-8fce3b22de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTEwMDksIm5iZiI6MTcxNTM5MDcwOSwicGF0aCI6Ii8yMTU4Mjc0MS8zMjgwOTIyMzctOTVhODZiNTQtMDEyMi00NTAzLTg1Y2YtOGZjZTNiMjJkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMjUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZWEzYWZlNTQ1OTVjNWQyZjU3OWY0YzAwYmYwNjFkZWEzZTA0ZGRiZTIzNWNiZDAxY2M4MjE4YzA1YzBiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0kxJ1KxYyEBDb4ojgwAEqq4H2-IeKs70c_Tey7vNGQc) 这个 css 变量明显没有使用

确实，项目中只是定义了，没有地方使用

**Comment by saymy** [comment]
同样的问题，什么时候修复啊？

**Comment by GuoJikun** [comment]
> 同样的问题，什么时候修复啊？

看上面 pr 里面的回复，貌似没打算修复

**Comment by lliyuu520** [comment]
解决办法给了吧,![image](https://github.com/user-attachments/assets/d6466992-c87f-42e5-b998-a01b1086d2dd)

**Comment by GuoJikun** [comment]
> 解决办法给了吧,![image](https://private-user-images.githubusercontent.com/12896160/359785721-d6466992-c87f-42e5-b998-a01b1086d2dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjQwNTgsIm5iZiI6MTcyNDIyMzc1OCwicGF0aCI6Ii8xMjg5NjE2MC8zNTk3ODU3MjEtZDY0NjY5OTItYzg3Zi00MmU1LWI5OTgtYTAxYjEwODZkMmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA3MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMjRiOWE2Yjg0ZjJlZDFhOWMzMDUxNzE1OTQ2ZWQ5NGQzNTU1NzBiYTMwYjZiZTkyYWZmMWY4ZmU2OWViOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mmgjsdEzs-zaqvFY4HiRXyn4JvaaWLqhVX3eeFT9Pn8)

就 css 问题肯定知道怎么解决

**Comment by chunge16** [comment]
这样加 css，感觉也可以解决这个问题
```css
.el-form-item--default .el-form-item__content {
       line-height: 32px;
       min-width: var(--el-form-inline-content-width);
}
```

**Comment by warmthsea** [comment]
Please refer to: 
https://github.com/element-plus/element-plus/issues/15834#issuecomment-1936919229
https://github.com/element-plus/element-plus/pull/15352

**Comment by lang10217** [comment]
我还以为是我个人的问题。既然如此，我加了全局样式(scss)
.el-form-item__content {
  .el-select--default {
    width: 160px;
  }
  .el-select--large {
    width: 180px;
  }
  .el-select--small {
    width: 140px;
  }
}

**Comment by fakeNihilist** [comment]
可以这样写，给了默认值也不会影响已经设置style的情况
`.el-form--inline .el-form-item .el-form-item__content{
  width: var(--el-form-inline-content-width) default;
}`

**Comment by fakeNihilist** [comment]
可以这样写，不会影响已经在select设置style="width: xxxpx"的地方
```css
// --el-form-inline-content-width: 220px;

.el-form--inline .el-form-item__content .el-select--default{
  width: var(--el-form-inline-content-width) ; 
}
