### ISSUE TITLE
[Component] [checkbox] 使用 h 函数渲染 ElCheckbox 组件时，组件选中样式不能被改变

### ISSUE THREAD

**Issue by lin52025iq** [element-plus/element-plus#16760]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.26`
- Element Plus Version: `2.7.2`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBFbENoZWNrYm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgaCwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBjaGVja2VkID0gcmVmKGZhbHNlKVxuY29uc3QgTXlDaGVja2JveCA9IGgoRWxDaGVja2JveCwge1xuICBtb2RlbFZhbHVlOiBjaGVja2VkLnZhbHVlLFxuICBvbkNoYW5nZSh2YWw6IGJvb2xlYW4pIHtcbiAgICBjaGVja2VkLnZhbHVlID0gdmFsXG4gIH0sXG4gIGxhYmVsOiAnY2hlY2tib3gxJ1xufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIGNoZWNrZWQ6IHt7IGNoZWNrZWQgfX1cbiAgPGJyIC8+XG4gIGNoZWNrZWQxOlxuICA8TXlDaGVja2JveCAvPlxuICA8YnIgLz5cbiAgY2hlY2tlZDI6XG4gIDxFbENoZWNrYm94IHYtbW9kZWw9XCJjaGVja2VkXCIgbGFiZWw9XCJjaGVja2JveDJcIj48L0VsQ2hlY2tib3g+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

进入复现 playground，分别点击 checkbox1 和 checkbox2，观察 checkbox1 勾选框状态

### What is Expected?

当 checked 为 true 时，checkbox1 的勾选框为选中状态

### What is actually happening?

checked 为 true 时，checkbox 的勾选框还是未选中

### Additional comments

在 playground 环境中，不管是切换 checkbox1 还是切换 checkbox2，checkbox1 的勾选状态均不会改变，但相同的代码在 element-plus 的开发环境(element-plus/play/src/App.vue)中，切换 checkbox1 后，checkbox1 的勾选状态会发生改变，但勾选 checkbox2 时 checkbox1 的勾选状态不会改变

**Comment by Liao-js** [comment]
你可以看下这个 demo [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBFbENoZWNrYm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgaCwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBjaGVja2VkID0gcmVmKGZhbHNlKVxuY29uc3QgTXlDaGVja2JveCA9ICgpID0+IGgoRWxDaGVja2JveCwge1xuICBtb2RlbFZhbHVlOiBjaGVja2VkLnZhbHVlLFxuICAnb25VcGRhdGU6bW9kZWxWYWx1ZSc6ICh2YWw6IGJvb2xlYW4pID0+IHtcbiAgICBjaGVja2VkLnZhbHVlID0gdmFsO1xuICB9LFxuICBsYWJlbDogJ2NoZWNrYm94MSdcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICBjaGVja2VkOiB7eyBjaGVja2VkIH19XG4gIDxiciAvPlxuICBjaGVja2VkMTpcbiAgPE15Q2hlY2tib3ggLz5cbiAgPGJyIC8+XG4gIGNoZWNrZWQyOlxuICA8RWxDaGVja2JveCB2LW1vZGVsPVwiY2hlY2tlZFwiIGxhYmVsPVwiY2hlY2tib3gyXCI+PC9FbENoZWNrYm94PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by lin52025iq** [comment]
感谢感谢，学习了
