### ISSUE TITLE
[Bug Report] table does not display scrollbars in some case

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1677]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
chrmoe

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/vgbire/pen/WNReoWV

### Steps to reproduce
expand select

### What is Expected?
display scrollbars
when you set height to 220 in the table it is normal，but it don't work if there is no scroll bar at the beginning

### What is actually happening?
no display scrollbars

**Comment by justwiner** [comment]
After setting the height, when the content is not enough to fill the table, the scroll bar will not be displayed

**Comment by Vgbire** [comment]
> After setting the height, when the content is not enough to fill the table, the scroll bar will not be displayed

`when you set height to 220 in the table it is normal`，in this case expand the select,table will expand itself too.Can it be done like this?
![image](https://user-images.githubusercontent.com/32129111/111984535-71e90400-8b46-11eb-8aaa-275957a4e089.png)

**Comment by justwiner** [comment]
> > After setting the height, when the content is not enough to fill the table, the scroll bar will not be displayed
> 
> `when you set height to 220 in the table it is normal`，in this case expand the select,table will expand itself too.Can it be done like this?
> ![image](https://user-images.githubusercontent.com/32129111/111984535-71e90400-8b46-11eb-8aaa-275957a4e089.png)

You can set the `popper-append-to-body` to true to solve this problem. Usually, when using `Select`, it is better to insert the pop-up box into the `body`

**Comment by Vgbire** [comment]
actually,I needed to set popper-append-to-body to false,if set it to true.you expand the select，and scroll the table.it will be that
![image](https://user-images.githubusercontent.com/32129111/112081336-781ac700-8bbe-11eb-892c-35fdaaa82dad.png)

**Comment by justwiner** [comment]
@Vgbire 
When you use the pop-up box in the table and do not insert it into the body, it is normal for the content to exceed the display scroll bar, because the pop-up box is rendered inside the table.

What do you think?

**Comment by Vgbire** [comment]
Yes, I just want this effect, but there will be problems when there is no scroll bar at the beginning
![image](https://user-images.githubusercontent.com/32129111/112083126-71418380-8bc1-11eb-91d7-5eef5011829e.png)

**Comment by justwiner** [comment]
@Vgbire Yes, I'll fix it

**Comment by justwiner** [comment]
hey! @Vgbire 
I think you can solve this problem with `CSS`. [https://codepen.io/justwiner/pen/BapNLEK](https://codepen.io/justwiner/pen/BapNLEK)

You can refer to the official `popperjs` documentation. [https://popper.js.org/docs/v2/modifiers/hide/](https://popper.js.org/docs/v2/modifiers/hide/)

```
.el-select__popper[data-popper-reference-hidden] {
  visibility: hidden;
  pointer-events: none;
}
```

**Comment by Vgbire** [comment]
> hey! @Vgbire
> I think you can solve this problem with `CSS`. https://codepen.io/justwiner/pen/BapNLEK
> 
> You can refer to the official `popperjs` documentation. https://popper.js.org/docs/v2/modifiers/hide/
> 
> ```
> .el-select__popper[data-popper-reference-hidden] {
>   visibility: hidden;
>   pointer-events: none;
> }
> ```

Great!!!
