### ISSUE TITLE
[Style] [button] 自动样式的相关问题

### ISSUE THREAD

**Issue by MoConWu** [element-plus/element-plus#16784]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.2`
- Browser / OS: `Windows`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgICBzdHlsZT1cIlxuICAgICAgICBnYXA6IDEwcHg7XG4gICAgICAgIG1hcmdpbjogMDtcbiAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgIFwiXG4gICAgPlxuICAgICAgPGVsLWJ1dHRvbj4wMDA8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24+MTExPC9lbC1idXR0b24+XG4gICAgICA8ZWwtYnV0dG9uPjIyMjwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbj4zMzM8L2VsLWJ1dHRvbj5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

按钮自动添加了margin-left: 12px;
对于横向布局没有问题，但是纵向的时候，就不对了

### What is Expected?

考虑修复纵向的情况

### What is actually happening?

考虑修复纵向的情况

### Additional comments

_(empty)_

**Comment by MoConWu** [comment]
.el-button + .el-button {
    margin-left: 12px;
}
导致了纵向按钮偏移
![202458-下午-121403](https://github.com/element-plus/element-plus/assets/33497338/9847ee91-7b4a-4ba5-be4c-59d15c67e674)

**Comment by chenxch** [comment]
```
.el-button + .el-button{
  margin-left: 0 !important;
}
```

**Comment by MoConWu** [comment]
> ```
> .el-button + .el-button{
>   margin-left: 0 !important;
> }
> ```

这确实可以主动解决，但是希望的是自适应或自动判断，横着的时候，可以自动添加，纵向的时候就不自动添加了

**Comment by chenxch** [comment]
外层样式属性无法判断哦，这个还是需要自行解决

**Comment by MoConWu** [comment]
> 外层样式属性无法判断哦，这个还是需要自行解决

好吧
