### ISSUE TITLE
[Component] [date-picker] el-date-picker 为week或month时在切换年或者月份的时候会立即更新v-model的value

### ISSUE THREAD

**Issue by zhouxianjun** [element-plus/element-plus#16792]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.23`
- Element Plus Version: `2.7.2`
- Browser / OS: `Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZigpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dWw+XG4gICAgPGxpPueCueWHu+aXpeacn+aOp+S7tjwvbGk+XG4gICAgPGxpPumAieaLqemdouadv+mhtumDqOeahOW5tOS7veaIluiAheaciOS7vTwvbGk+XG4gICAgPGxpPuS9oOWwhuS8mueci+WIsHZhbHVlMeWAvOW3sue7j+WPkeeUn+WPmOWMljwvbGk+XG4gIDwvdWw+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgIHR5cGU9XCJ3ZWVrXCJcbiAgICBmb3JtYXQ9XCJbV2Vla10gd3dcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIHdlZWtcIlxuICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 点击日期控件
2. 选择面板顶部的年份或者月份
3. 你将会看到value1值已经发生变化

### What is Expected?

只有选择周的时候才更新v-model或者在面板关闭的时候如果没有选择周则不触发change事件

### What is actually happening?

v-model被立即变更，且如果使用change事件，也会在面板关闭后抛出change事件，值为选择的年或者月份，并不是我真正选的值（如果没有真正选择的情况）

### Additional comments

我看了element-ui的版本是没有问题的，只有element-plus才有这个问题

![image](https://github.com/element-plus/element-plus/assets/5254523/69aa1906-08dc-4801-ab27-ebfbd46b0edf)

**Comment by zhouxianjun** [comment]
@FrontEndDog 大佬，你这个commit 里面没通过lint检查，有个console？大佬只处理了week的吗？可以一起处理一下month的吗？
然后就是这个如果你直接改掉的话，会不会有兼容问题？就是官方这样做会不会是有些需求需要这样的处理方式？如果有兼容问题的话可以用一个参数判断？

**Comment by FrontEndDog** [comment]
> @FrontEndDog 大佬，你这个commit 里面没通过lint检查，有个console？大佬只处理了week的吗？可以一起处理一下month的吗？ 然后就是这个如果你直接改掉的话，会不会有兼容问题？就是官方这样做会不会是有些需求需要这样的处理方式？如果有兼容问题的话可以用一个参数判断？

lint检查之前已经改了 你可能没注意到

我认真查看了代码逻辑，想不通为什么在这边需要执行一次handleKeyControl，当然，这个修改还需要其他成员审核。
