### ISSUE TITLE
[Component] [table] Issue happens when listening the select-all event

### ISSUE THREAD

**Issue by lhyUnited** [element-plus/element-plus#16796]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.2`
- Browser / OS: `124.0.6367.119 (Official Build) (x86_64) `
- Build Tool: `Other`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgIDxlbC1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIFNlbGVjdFwiXG4gICAgQGNoYW5nZT1cImhhbmRsZVRvZ2dsZVJvd1NlbGVjdGlvblwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJtdWx0aXBsZVRhYmxlUmVmXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgcm93LWtleT1cImRhdGVcIlxuICAgIEBzZWxlY3Q9XCJoYW5kbGVTZWxlY3RcIlxuICAgIEBzZWxlY3QtYWxsPVwiaGFuZGxlU2VsZWN0QWxsXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgIHR5cGU9XCJzZWxlY3Rpb25cIlxuICAgIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTUwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ2YWx1ZVwiIGxhYmVsPVwiVmFsdWVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCBkZWZpbmVDb21wb25lbnQsIGNvbXB1dGVkLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcblxuaW50ZXJmYWNlIEx1bmNoIHtcbiAgbmFtZTogc3RyaW5nXG4gIHZhbHVlOiBudW1iZXJcbn1cblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgc2V0dXAoKSB7XG4gICAgY29uc3Qgb3B0aW9ucyA9IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdGb29kJyxcbiAgICAgICAgdmFsdWU6IDBcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnRHJpbmsnLFxuICAgICAgICB2YWx1ZTogMVxuICAgICAgfVxuICAgIF1cblxuICAgIGNvbnN0IHZhbHVlID0gcmVmKDApXG5cbiAgICBjb25zdCBvcmlnaW5EYXRhID0gcmVmPEx1bmNoW10+KFtcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0Zvb2QnLFxuICAgICAgICB2YWx1ZTogMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0Zvb2QnLFxuICAgICAgICB2YWx1ZTogMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0Zvb2QnLFxuICAgICAgICB2YWx1ZTogMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0Zvb2QnLFxuICAgICAgICB2YWx1ZTogMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0RyaW5rJyxcbiAgICAgICAgdmFsdWU6IDFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICdEcmluaycsXG4gICAgICAgIHZhbHVlOiAxXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRHJpbmsnLFxuICAgICAgICB2YWx1ZTogMVxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0RyaW5rJyxcbiAgICAgICAgdmFsdWU6IDFcbiAgICAgIH1cbiAgICBdKVxuXG4gICAgY29uc3QgdGFibGVEYXRhID0gY29tcHV0ZWQoKCkgPT4ge1xuICAgICAgcmV0dXJuIG9yaWdpbkRhdGEudmFsdWUuZmlsdGVyKHQgPT4gdC52YWx1ZSA9PT0gdmFsdWUudmFsdWUpXG4gICAgfSlcblxuICAgIGNvbnN0IHNlbGVjdGVkSXRlbXNNYXAgPSByZWYoe30pXG5cbiAgICBjb25zdCBtdWx0aXBsZVRhYmxlUmVmID0gcmVmKClcblxuICAgIGNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtcykgPT4ge1xuICAgICAgc2VsZWN0ZWRJdGVtc01hcC52YWx1ZVt2YWx1ZS52YWx1ZV0gPSBpdGVtc1xuICAgIH1cblxuICAgIGNvbnN0IGhhbmRsZVNlbGVjdEFsbCA9IChpdGVtcykgPT4ge1xuICAgICAgc2VsZWN0ZWRJdGVtc01hcC52YWx1ZVt2YWx1ZS52YWx1ZV0gPSBpdGVtc1xuICAgIH1cblxuICAgIGNvbnN0IGhhbmRsZVRvZ2dsZVJvd1NlbGVjdGlvbiA9ICgpID0+IHtcbiAgICAgIG5leHRUaWNrKCgpID0+IHtcbiAgICAgICAgbXVsdGlwbGVUYWJsZVJlZi52YWx1ZT8uY2xlYXJTZWxlY3Rpb24oKVxuICAgICAgICBpZiAoc2VsZWN0ZWRJdGVtc01hcC52YWx1ZVt2YWx1ZS52YWx1ZV0/Lmxlbmd0aCkge1xuICAgICAgICAgIGNvbnNvbGUubG9nKHNlbGVjdGVkSXRlbXNNYXAudmFsdWUpXG4gICAgICAgICAgc2VsZWN0ZWRJdGVtc01hcC52YWx1ZVt2YWx1ZS52YWx1ZV0uZm9yRWFjaChyb3cgPT4ge1xuICAgICAgICAgICAgbXVsdGlwbGVUYWJsZVJlZi52YWx1ZT8udG9nZ2xlUm93U2VsZWN0aW9uKHJvdywgdHJ1ZSlcbiAgICAgICAgICB9KVxuICAgICAgICB9XG4gICAgICB9KVxuICAgIH1cblxuXG4gICAgcmV0dXJuIHtcbiAgICAgIHRhYmxlRGF0YSxcbiAgICAgIG11bHRpcGxlVGFibGVSZWYsXG4gICAgICBoYW5kbGVTZWxlY3QsXG4gICAgICBoYW5kbGVTZWxlY3RBbGwsXG4gICAgICBoYW5kbGVUb2dnbGVSb3dTZWxlY3Rpb24sXG4gICAgICBvcHRpb25zLFxuICAgICAgdmFsdWVcbiAgICB9XG4gIH1cbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

Steps:
1. Create a Table with two or more types of data and a Select to change different types of data to show.
2. First select some items on the Food
3. Switch to Drink types of data
4. Select all and unselect all
5. Switch back to Food, do nothing
6. Switch to Drink again and check the result

### What is Expected?

The select-all header-cell should be unchecked since there is no item being selected.

### What is actually happening?

The select-all header-cell is selected.

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
you can see this [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgIDxlbC1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIFNlbGVjdFwiXG4gICAgQGNoYW5nZT1cImhhbmRsZVRvZ2dsZVJvd1NlbGVjdGlvblwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJtdWx0aXBsZVRhYmxlUmVmXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgQHNlbGVjdC1hbGw9XCJoYW5kbGVTZWxlY3RBbGxcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgdHlwZT1cInNlbGVjdGlvblwiXG4gICAgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxNTBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInZhbHVlXCIgbGFiZWw9XCJWYWx1ZVwiIHdpZHRoPVwiMTUwXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIGRlZmluZUNvbXBvbmVudCwgY29tcHV0ZWQsIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgTHVuY2gge1xuICBuYW1lOiBzdHJpbmdcbiAgdmFsdWU6IG51bWJlclxufVxuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBzZXR1cCgpIHtcbiAgICBjb25zdCBvcHRpb25zID0gW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0Zvb2QnLFxuICAgICAgICB2YWx1ZTogMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdEcmluaycsXG4gICAgICAgIHZhbHVlOiAxXG4gICAgICB9XG4gICAgXVxuXG4gICAgY29uc3QgdmFsdWUgPSByZWYoMClcblxuICAgIGNvbnN0IG9yaWdpbkRhdGEgPSByZWY8THVuY2hbXT4oW1xuICAgICAge1xuICAgICAgICBuYW1lOiAnRm9vZCcsXG4gICAgICAgIHZhbHVlOiAwXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRm9vZCcsXG4gICAgICAgIHZhbHVlOiAwXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRm9vZCcsXG4gICAgICAgIHZhbHVlOiAwXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRm9vZCcsXG4gICAgICAgIHZhbHVlOiAwXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRHJpbmsnLFxuICAgICAgICB2YWx1ZTogMVxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ0RyaW5rJyxcbiAgICAgICAgdmFsdWU6IDFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICdEcmluaycsXG4gICAgICAgIHZhbHVlOiAxXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnRHJpbmsnLFxuICAgICAgICB2YWx1ZTogMVxuICAgICAgfVxuICAgIF0pXG5cbiAgICBjb25zdCB0YWJsZURhdGEgPSBjb21wdXRlZCgoKSA9PiB7XG4gICAgICByZXR1cm4gb3JpZ2luRGF0YS52YWx1ZS5maWx0ZXIodCA9PiB0LnZhbHVlID09PSB2YWx1ZS52YWx1ZSlcbiAgICB9KVxuXG4gICAgY29uc3Qgc2VsZWN0ZWRJdGVtc01hcCA9IHJlZih7fSlcblxuICAgIGNvbnN0IG11bHRpcGxlVGFibGVSZWYgPSByZWYoKVxuXG4gICAgY29uc3QgaGFuZGxlU2VsZWN0ID0gKGl0ZW1zKSA9PiB7XG4gICAgICBzZWxlY3RlZEl0ZW1zTWFwLnZhbHVlW3ZhbHVlLnZhbHVlXSA9IFsuLi5pdGVtc11cbiAgICB9XG5cbiAgICBjb25zdCBoYW5kbGVTZWxlY3RBbGwgPSAoaXRlbXMpID0+IHtcbiAgICAgIHNlbGVjdGVkSXRlbXNNYXAudmFsdWVbdmFsdWUudmFsdWVdID0gWy4uLml0ZW1zXVxuICAgIH1cblxuICAgIGNvbnN0IGhhbmRsZVRvZ2dsZVJvd1NlbGVjdGlvbiA9ICgpID0+IHtcbiAgICAgIG5leHRUaWNrKCgpID0+IHtcbiAgICAgICAgbXVsdGlwbGVUYWJsZVJlZi52YWx1ZT8uY2xlYXJTZWxlY3Rpb24oKVxuICAgICAgICBuZXh0VGljaygoKSA9PiB7XG4gICAgICAgICAgaWYgKHNlbGVjdGVkSXRlbXNNYXAudmFsdWVbdmFsdWUudmFsdWVdPy5sZW5ndGgpIHtcbiAgICAgICAgICAgIHNlbGVjdGVkSXRlbXNNYXAudmFsdWVbdmFsdWUudmFsdWVdLmZvckVhY2gocm93ID0+IHtcbiAgICAgICAgICAgICAgbXVsdGlwbGVUYWJsZVJlZi52YWx1ZT8udG9nZ2xlUm93U2VsZWN0aW9uKHJvdywgdHJ1ZSlcbiAgICAgICAgICAgIH0pXG4gICAgICAgICAgfVxuICAgICAgICB9KVxuICAgICAgICBcbiAgICAgIH0pXG4gICAgfVxuXG5cbiAgICByZXR1cm4ge1xuICAgICAgdGFibGVEYXRhLFxuICAgICAgbXVsdGlwbGVUYWJsZVJlZixcbiAgICAgIGhhbmRsZVNlbGVjdCxcbiAgICAgIGhhbmRsZVNlbGVjdEFsbCxcbiAgICAgIGhhbmRsZVRvZ2dsZVJvd1NlbGVjdGlvbixcbiAgICAgIG9wdGlvbnMsXG4gICAgICB2YWx1ZVxuICAgIH1cbiAgfVxufSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==),does it meet your expectations?

**Comment by lhyUnited** [comment]
Yes, it works well. But the root cause is here, table gives selection out which would cause object reference issue. The data of listeners could change unexpectedly

https://github.com/element-plus/element-plus/blob/c3dc4b304eb34118883eeb07ace81dc79ee48de7/packages/components/table/src/store/watcher.ts#L241

**Comment by Liao-js** [comment]
because when selecting all and canceling, the selection is not updated again. When switching to Food, Food and Drink have the same reference.
