### ISSUE TITLE
[TypeScript] [pagination] 2.7.2版本pagination警告label 

### ISSUE THREAD

**Issue by qiuhengyu** [element-plus/element-plus#16809]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.2`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgcGFnZU9iaiA9IHtcbiAgcGFnZU51bWJlcjogMSxcbiAgcGFnZVNpemVBcnI6IFsxMCwgMTUsIDIwLCA1MCwgMTAwXSxcbiAgcGFnZVNpemU6IDUsXG4gIHRvdGFsOiAxMDBcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGVsLXBhZ2luYXRpb25cbiAgICAgICAgOmN1cnJlbnQtcGFnZT1cInBhZ2VPYmoucGFnZU51bWJlclwiXG4gICAgICAgIDpwYWdlLXNpemVzPVwicGFnZU9iai5wYWdlU2l6ZUFyclwiXG4gICAgICAgIDpwYWdlLXNpemU9XCJwYWdlT2JqLnBhZ2VTaXplXCJcbiAgICAgICAgbGF5b3V0PVwidG90YWwsIHNpemVzLCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyXCJcbiAgICAgICAgOnRvdGFsPVwicGFnZU9iai50b3RhbFwiPlxuICAgIDwvZWwtcGFnaW5hdGlvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
     <el-pagination
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
        :current-page="pageListObj.pageNumber"
        :page-sizes="pageListObj.pageSizeArr"
        :page-size="pageListObj.pageSize"
        layout="total, sizes, prev, pager, next, jumper"
        :total="pageListObj.total">
    </el-pagination>
</template>
```

### What is Expected?

内部使用了label吗？就一个page组件，页面上没有label

### What is actually happening?

index.vue:304 ElementPlusError: [el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.
For more detail, please visit: https://element-plus.org/en-US/component/input.html

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
fixed by https://github.com/element-plus/element-plus/pull/16682

**Comment by btea** [comment]
2.7.3 已修复发版。
