### ISSUE TITLE
[Component] [scrollbar] el-scrollbar内的组件不会触发Vue的生命周期钩子onBeforeUpdate和onUpdated

### ISSUE THREAD

**Issue by a-silent-guy** [element-plus/element-plus#16805]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.2`
- Browser / OS: `Chrome/124.0.6367.60`
- Build Tool: `Vite`

### Related Component

- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIG9uQmVmb3JlVXBkYXRlLCBvblVwZGF0ZWQgfSBmcm9tIFwidnVlXCI7XG5cbmNvbnN0IGNvdW50ID0gcmVmKDApO1xuXG5vbkJlZm9yZVVwZGF0ZSgoKSA9PiB7XG4gIGNvbnNvbGUubG9nKFwib25CZWZvcmVVcGRhdGVcIik7XG59KTtcblxub25VcGRhdGVkKCgpID0+IHtcbiAgY29uc29sZS5sb2coXCJvblVwZGF0ZWRcIik7XG59KTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zY3JvbGxiYXI+XG4gICAgPGRpdiBjbGFzcz1cImNhcmRcIj5cbiAgICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIEBjbGljaz1cImNvdW50KytcIj5jb3VudCBpcyB7eyBjb3VudCB9fTwvYnV0dG9uPlxuICAgIDwvZGl2PlxuICA8L2VsLXNjcm9sbGJhcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击按钮页面count会变化，但不会触发onBeforeUpdate和onUpdated钩子

### What is Expected?

正确触发Vue的钩子

### What is actually happening?

没有触发更新的钩子

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
这是 Vue 的问题么？

**Comment by warmthsea** [comment]
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIG9uQmVmb3JlVXBkYXRlLCBvblVwZGF0ZWQgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgQ29tcCBmcm9tICcuL0NvbXAudnVlJ1xuXG5jb25zdCBjb3VudCA9IHJlZigwKTtcbmNvbnN0IGNvdW50MiA9IHJlZigwKTtcbmNvbnN0IGNvdW50MyA9IHJlZigwKTtcblxub25CZWZvcmVVcGRhdGUoKCkgPT4ge1xuICBjb25zb2xlLmxvZyhcIm9uQmVmb3JlVXBkYXRlXCIpO1xufSk7XG5cbm9uVXBkYXRlZCgoKSA9PiB7XG4gIGNvbnNvbGUubG9nKFwib25VcGRhdGVkXCIpO1xufSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2Nyb2xsYmFyPlxuICAgIDxkaXYgY2xhc3M9XCJjYXJkXCI+XG4gICAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBAY2xpY2s9XCJjb3VudCsrXCI+Y291bnQgaXMge3sgY291bnQgfX08L2J1dHRvbj5cbiAgICA8L2Rpdj5cbiAgPC9lbC1zY3JvbGxiYXI+XG4gIDxDb21wPlxuICAgIDEyM1xuICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIEBjbGljaz1cImNvdW50MisrXCI+Y291bnQyIGlzIHt7IGNvdW50MiB9fTwvYnV0dG9uPlxuICA8L0NvbXA+XG4gIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIEBjbGljaz1cImNvdW50MysrXCI+Y291bnQzIGlzIHt7IGNvdW50MyB9fTwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9Db21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XHJcblxyXG48L3NjcmlwdD5cclxuXHJcbjx0ZW1wbGF0ZT5cclxuICA8ZGl2PlxyXG4gICAgY29tcG9uZW50LVxyXG4gICAgPHNsb3QgLz5cclxuICA8L2Rpdj5cclxuPC90ZW1wbGF0ZT5cclxuIiwiX28iOnt9fQ==)

**Comment by warmthsea** [comment]
https://github.com/vuejs/core/issues/10901

**Comment by Liao-js** [comment]
https://github.com/vuejs/core/issues/4686

**Comment by a-silent-guy** [comment]
> vuejs/core#10901

谢谢
