### ISSUE TITLE
[Bug Report] ElSelect prefix content is blocked by selected tags when add attribute multiple

### ISSUE THREAD

**Issue by xjxujing** [element-plus/element-plus#1681]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
Google Chrome  89.0.4389.90 (official version)   (64-bit)

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/xjxujing/pen/MWJWRwo

### Steps to reproduce
Add ElSelect attribute multiple, and use slot prefix

### What is Expected?
When with attribute multiple, the prefix content will not be blocked.

### What is actually happening?
When multiple choices are available,  it will block prefix content.

**Comment by Ryan2128** [comment]
Duplicate #1680
