### ISSUE TITLE
[Component] [select] el-select with multiple and filterable will not invoke event listener of "remove-tag" when utilize [backspace] to remove tag

### ISSUE THREAD

**Issue by Etern-34520** [element-plus/element-plus#16831]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.2`
- Browser / OS: `Edge 123.0.2420.20 Chrome 124.0.6367.155 / Windows 11 Insider Preview 10.0.26120.470`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCBFbFNlbGVjdCQxIGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmNvbnN0IHNlbGVjdCA9IHJlZihbXSk7XG5jb25zdCBsYXN0UmVtb3ZlZCA9IHJlZihcIm5vbmVcIik7XG5jb25zdCBvblJlbW92ZVRhZyA9ICh2YWx1ZSkgPT4ge1xuICBsYXN0UmVtb3ZlZC52YWx1ZSA9IHZhbHVlO1xufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbnt7IGxhc3RSZW1vdmVkIH19XG48ZWwtc2VsZWN0IEByZW1vdmUtdGFnPVwib25SZW1vdmVUYWdcIiB2LW1vZGVsPVwic2VsZWN0XCIgbXVsdGlwbGUgZmlsdGVyYWJsZT5cbjxlbC1vcHRpb24gOmtleT1cIjFcIiBsYWJlbD1cIjFcIiA6dmFsdWU9XCIxXCIvPlxuPGVsLW9wdGlvbiA6a2V5PVwiMlwiIGxhYmVsPVwiMlwiIDp2YWx1ZT1cIjJcIi8+XG48ZWwtb3B0aW9uIDprZXk9XCIzXCIgbGFiZWw9XCIzXCIgOnZhbHVlPVwiM1wiLz5cbjxlbC1vcHRpb24gOmtleT1cIjRcIiBsYWJlbD1cIjRcIiA6dmFsdWU9XCI0XCIvPlxuPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

remove tag by click the "X" , the tag removed and the label changed,
remove tag by press backspace ,the tag removed but the label won't changed.

### What is Expected?

when remove tag by press backspace ,the tag removed and the label should changed.

### What is actually happening?

remove tag by press backspace ,the tag removed but the label won't changed.

### Additional comments

_(empty)_

**Comment by JiuRanYa** [comment]
@Liao-js I add test cases for select. I didn't notice that you submitted a pull request just now.
