### ISSUE TITLE
[Component] [pagination]  el-config-provider 设置size="small" 后 el-pagination 尺寸错误

### ISSUE THREAD

**Issue by long4488296** [element-plus/element-plus#16830]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.7.2`
- Browser / OS: `Microsoft Edge 124`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7IEVsQ29uZmlnUHJvdmlkZXIgfSBmcm9tIFwiZWxlbWVudC1wbHVzXCI7XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxiciAvPlxuICA8c3Bhbj7lhajlsYDlsI/lsLrlr7g8L3NwYW4+XG4gPGVsLWNvbmZpZy1wcm92aWRlciAgc2l6ZT1cInNtYWxsXCI+XG5cbiA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gXG4gPGVsLXBhZ2luYXRpb24gIGxheW91dD1cInRvdGFsLCBzaXplcywgcHJldiwgcGFnZXIsIG5leHQsIGp1bXBlclwiIDp0b3RhbD1cIjEwMFwiICAvPlxuXG4gPC9lbC1jb25maWctcHJvdmlkZXIgPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

 <el-config-provider size="small">   <el-pagination /></el-config-provider>

### What is Expected?

el-pagination 显示为小尺寸 即 :small="true"

### What is actually happening?

 el-pagination 显示标准尺寸 即 :small="false"

### Additional comments

麻烦你们了

**Comment by JiuRanYa** [comment]
Pagination using the small is true, not size.

**Comment by btea** [comment]
@long4488296 `el-pagination` 只支持通过 `small` 为 `true` 或 `false` 来设置小尺寸和标准尺寸，你的写法应该没问题。

**Comment by long4488296** [comment]
> @long4488296 `el-pagination` 只支持通过 `small` 为 `true` 或 `false` 来设置小尺寸和标准尺寸，你的写法应该没问题。

期望是 通过 el-config-provider  的 size="small"  能够 全局修改到 el-pagination 的尺寸, 就像 el-input那样

**Comment by long4488296** [comment]
期望是 通过 el-config-provider  的 size="small"  能够 全局修改到 el-pagination 的尺寸, 就像 el-input那样

> @long4488296 `el-pagination` 只支持通过 `small` 为 `true` 或 `false` 来设置小尺寸和标准尺寸，你的写法应该没问题。

**Comment by long4488296** [comment]
使用  el-config-provider   可以配置 包括el-input在内的控件, 为何el-pagination 不支持? 这真不是bug还是有什么其他问题?

**Comment by webvs2** [comment]
@long4488296 16858
