### ISSUE TITLE
[Bug Report] The el-upload will animate when I put el-radio together or v-if, v-show together.

### ISSUE THREAD

**Issue by leonzai** [element-plus/element-plus#1683]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
windows 10 19041.867 / Edge 89.0.774.57 , Chrome 89.0.4389.90（正式版本）

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/9pgqcde6/3/

### Steps to reproduce
click the el-radio, the el-input will animate

### What is Expected?
When click the el-radio, the el-input will not animate. It will lead to a poor user experience.

### What is actually happening?
click the el-radio, the el-input will animate

**Comment by Ryan2128** [comment]
Do you mean the file list of el-upload?

**Comment by leonzai** [comment]
> In the demo you provided, I could not find el-input.
> 
> Do you mean the file list of el-upload? If so, there is indeed a bug here, which will be fixed later.

Sorry, it is el-upload, thank u very much.

**Comment by JeremyWuuuuu** [comment]
I could not open `jsfiddle` for like a while, dunno what happened to `jsfiddle`

**Comment by leonzai** [comment]
@JeremyWuuuuu Hello, this bug fixed before, but show now.

**Comment by leonzai** [comment]
https://jsfiddle.net/9pgqcde6/3/

**Comment by leonzai** [comment]
@Ryan2128  Hello, this bug fixed before, but show now.
