### ISSUE TITLE
[bug report] select component cannot be used normally when grouping, multiple selection and search are used at the same time

### ISSUE THREAD

**Issue by dxy2233** [element-plus/element-plus#1685]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10，最新edge

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/3L9hzgos/

### Steps to reproduce
官方文档select组件，分组示例中，增加multiple和filterable属性即可重现

### What is Expected?
修复select组件分组多选时的搜索事件

### What is actually happening?
无法正常搜索与显示

**Comment by inottn** [comment]
It resolved in #1639

**Comment by kooriookami** [comment]
We will fix in next version.
