### ISSUE TITLE
[Component] [select] el-select中, 无法回显value为空的option的label

### ISSUE THREAD

**Issue by anmingan** [element-plus/element-plus#16857]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.3.10`
- Browser / OS: `Chrome 123.0.6312.106`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5cbmNvbnN0IGFkZXRhaWxlckxpc3QgPSByZWYoW10pXG5hZGV0YWlsZXJMaXN0LnZhbHVlID0gW1xuICAgIHtcbiAgICAgICAgXCJzeXN0eXBlXCI6IFwiMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJhaV9tb2RlbFwiLFxuICAgICAgICBcInZhbHVlXCI6IFwiRFBNIGFkYXB0aXZlXCIsXG4gICAgICAgIFwidmFsdWV0eXBlXCI6IFwic3RyaW5nXCIsXG4gICAgICAgIFwiaW5zdHJ1Y3RcIjogXCJEUE0gYWRhcHRpdmVcIixcbiAgICAgICAgXCJtZW1vXCI6IFwiRFBNIGFkYXB0aXZlXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJzeXN0eXBlXCI6IFwiMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJhaV9tb2RlbFwiLFxuICAgICAgICBcInZhbHVlXCI6IFwiRFBNKysgU0RFIEthcnJhc1wiLFxuICAgICAgICBcInZhbHVldHlwZVwiOiBcInN0cmluZ1wiLFxuICAgICAgICBcImluc3RydWN0XCI6IFwiRFBNKysgU0RFIEthcnJhc1wiLFxuICAgICAgICBcIm1lbW9cIjogXCJEUE0rKyBTREUgS2FycmFzXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJzeXN0eXBlXCI6IFwiMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJhaV9tb2RlbFwiLFxuICAgICAgICBcInZhbHVlXCI6IFwiRFBNKysgMk0gS2FycmFzXCIsXG4gICAgICAgIFwidmFsdWV0eXBlXCI6IFwic3RyaW5nXCIsXG4gICAgICAgIFwiaW5zdHJ1Y3RcIjogXCJEUE0rKyAyTSBLYXJyYXNcIixcbiAgICAgICAgXCJtZW1vXCI6IFwiRFBNKysgMk0gS2FycmFzXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJzeXN0eXBlXCI6IFwiMFwiLFxuICAgICAgICBcIm5hbWVcIjogXCJhaV9tb2RlbFwiLFxuICAgICAgICBcInZhbHVlXCI6IFwiXCIsXG4gICAgICAgIFwidmFsdWV0eXBlXCI6IFwic3RyaW5nXCIsXG4gICAgICAgIFwiaW5zdHJ1Y3RcIjogXCJEUE0rKyAzTSBTREVcIixcbiAgICAgICAgXCJtZW1vXCI6IFwiRFBNKysgM00gU0RFXCJcbiAgICB9XG5dXG5jb25zdCBwYXJhbXMgPXJlYWN0aXZlKHtcbmFkZXRhaWxlcjonRFBNIGFkYXB0aXZlJ1xufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgICAgICAgdi1tb2RlbD1cInBhcmFtcy5hZGV0YWlsZXJcIlxuICAgICAgICAgICAgc3R5bGU9XCJ3aWR0aDogNTAlO1wiXG5cbiAgICAgICAgICAgPlxuICAgICAgICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICAgICAgIHYtZm9yPVwiaXRlbSxpbmRleCBpbiBhZGV0YWlsZXJMaXN0XCJcbiAgICAgICAgICAgICAgIDprZXk9XCJpbmRleFwiXG4gICAgICAgICAgICAgICA6bGFiZWw9XCJpdGVtLm1lbW9cIlxuICAgICAgICAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAgICAgICAgID5cbiAgICAgICAgICAgICA8L2VsLW9wdGlvbj5cblxuICAgICAgICAgICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

空的el-select中, 无法回显value为空的option的label

### What is Expected?

能回显value为空的option

### What is actually happening?

呈现为未选择的状态

### Additional comments

_(empty)_

**Comment by tinglinzh** [comment]
升级element-plus为2.70版本以上，配置属性:empty-values="[null, undefined]"

**Comment by wxxcarl** [comment]
我也郁闷了半天，请查看文档：https://element-plus.org/zh-CN/component/config-provider.html#%E7%A9%BA%E5%80%BC%E9%85%8D%E7%BD%AE

**Comment by MisterBowie** [comment]
我也遇到了次情况
`<el-select
					:empty-values="['', null, undefined]"
					:value-on-clear="''"
					v-model="queryParams.examineStatus"
					placeholder="请选择审核状态"
					clearable
				>
					<el-option
						label="全部"
						:value="''"
					/>
					<el-option
						v-for="dict in examine_status"
						:key="dict.value"
						:label="dict.label"
						:value="dict.value"
					/>
				</el-select>`
<img width="230" alt="image" src="https://github.com/element-plus/element-plus/assets/22372554/b2e4683e-d5d1-4a82-bb53-cf781fff6142">

**Comment by yyblove** [comment]
> 我也遇到了次情况 `<el-select :empty-values="['', null, undefined]" :value-on-clear="''" v-model="queryParams.examineStatus" placeholder="请选择审核状态" clearable > <el-option label="全部" :value="''" /> <el-option v-for="dict in examine_status" :key="dict.value" :label="dict.label" :value="dict.value" /> </el-select>` <img alt="image" width="230" src="https://private-user-images.githubusercontent.com/22372554/345755690-b2e4683e-d5d1-4a82-bb53-cf781fff6142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjgyMzQsIm5iZiI6MTcyNTI2NzkzNCwicGF0aCI6Ii8yMjM3MjU1NC8zNDU3NTU2OTAtYjJlNDY4M2UtZDVkMS00YTgyLWJiNTMtY2Y3ODFmZmY2MTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDZkNzQ4NzFiZGQwZTdjZGIzODFiM2FhYjdkMDNhM2Q0YWI0YjQ5MzJjMWFmMTNmZjk2MzNhNjA2MGMwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YVSohrU6NEl4xE-sB-yvYJQ_Gv8bY7-myB6Q3JWVUc">

 :empty-values="[null, undefined]" :value-on-clear="null" 其余不变 就可以

**Comment by gwl002** [comment]
兼容性是真差呀
