### ISSUE TITLE
[Component] [table, table-column] table 多列合并后渲染了多余的数据

### ISSUE THREAD

**Issue by czbczb** [element-plus/element-plus#16869]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.3`
- Browser / OS: `124.0.6367.201（正式版本） (arm64)/ mac os Apple M1`
- Build Tool: `Webpack`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cImFycmF5U3Bhbk1ldGhvZFwiXG4gICAgICBib3JkZXJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIHNvcnRhYmxlIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MlwiIHNvcnRhYmxlIGxhYmVsPVwiQW1vdW50IDJcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50M1wiIHNvcnRhYmxlIGxhYmVsPVwiQW1vdW50IDNcIiAvPlxuICAgIDwvZWwtdGFibGU+XG5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgYXJyYXlTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuXG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMikge1xuICAgIHJldHVybiBbMSwgMl1cbiAgfWVsc2Uge1xuICByZXR1cm4gWzEsMV1cbiAgfVxufVxuXG5jb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAnMTI5ODcxMjInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICcyMzQnLFxuICAgIGFtb3VudDI6ICczLjInLFxuICAgIGFtb3VudDM6IDEwLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzMyNCcsXG4gICAgYW1vdW50MjogJzEuOScsXG4gICAgYW1vdW50MzogOSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjUnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc2MjEnLFxuICAgIGFtb3VudDI6ICcyLjInLFxuICAgIGFtb3VudDM6IDE3LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzUzOScsXG4gICAgYW1vdW50MjogJzQuMScsXG4gICAgYW1vdW50MzogMTUsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

设了一行数据全部合并，或者从某个column开始合并以后所有数据

### What is Expected?

不展示后面的多余数据

### What is actually happening?

展示了多余数据

### Additional comments

麻烦大佬帮忙看看，很着急

![image](https://github.com/element-plus/element-plus/assets/23630100/eb87e10c-e8e2-4969-bad7-b562fbfa66b7)

**Comment by Liao-js** [comment]
you can see this [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6c3Bhbi1tZXRob2Q9XCJhcnJheVNwYW5NZXRob2RcIiBib3JkZXIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMlwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgPC9lbC10YWJsZT5cblxuICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIiBib3JkZXIgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLXRvcDogMjBweFwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgbGFiZWw9XCJBbW91bnQgMVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgbGFiZWw9XCJBbW91bnQgMlwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHR5cGUgeyBUYWJsZUNvbHVtbkN0eCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW50ZXJmYWNlIFVzZXIge1xuICBpZDogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhbW91bnQxOiBzdHJpbmdcbiAgYW1vdW50Mjogc3RyaW5nXG4gIGFtb3VudDM6IG51bWJlclxufVxuXG5pbnRlcmZhY2UgU3Bhbk1ldGhvZFByb3BzIHtcbiAgcm93OiBVc2VyXG4gIGNvbHVtbjogVGFibGVDb2x1bW5DdHg8VXNlcj5cbiAgcm93SW5kZXg6IG51bWJlclxuICBjb2x1bW5JbmRleDogbnVtYmVyXG59XG5cbmNvbnN0IGFycmF5U3Bhbk1ldGhvZCA9ICh7XG4gIHJvdyxcbiAgY29sdW1uLFxuICByb3dJbmRleCxcbiAgY29sdW1uSW5kZXgsXG59OiBTcGFuTWV0aG9kUHJvcHMpID0+IHtcblxuICBpZiAoY29sdW1uSW5kZXggPT09IDIpIHtcbiAgICByZXR1cm4gWzEsIDJdXG4gIH0gZWxzZSBpZiAoY29sdW1uSW5kZXggPT09IDMpIHtcbiAgICByZXR1cm4gWzAsIDBdXG4gIH0gZWxzZSB7XG4gICAgcmV0dXJuIFsxLCAxXVxuICB9XG59XG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDIsXG4gICAgICAgIGNvbHNwYW46IDEsXG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by czbczb** [comment]
@Liao-js I see

**Comment by Steve0211** [comment]
合并的方法必须要是逐个单元格遍历的，tabel的合并不是真正的合并，只是把你需要合并的单元格放大，被合并的单元格还是存在的，所以合并的时候除了要处理要合并单元格，还要处理被合并的单元格。
![image](https://github.com/element-plus/element-plus/assets/52101276/f985acd0-ae97-4a16-b5fc-26152c0f1da2)
也就是红色圈的单元格隐藏，因此这部分单元格返回[0,0]
![image](https://github.com/element-plus/element-plus/assets/52101276/7a74f47c-ee11-4a41-bed0-12d882ec4aea)
