### ISSUE TITLE
[Style] [table] 表格内容溢出时，鼠标移入显示的tooltip背景色显示无效

### ISSUE THREAD

**Issue by wanWanWei** [element-plus/element-plus#16864]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.7.3`
- Browser / OS: `chrome`
- Build Tool: `Webpack`

### Related Component

- `el-table`

### Steps to reproduce

下载最新包会发现表格内容溢出部分，鼠标移入导致tooltip无背景色，下载2.3.12版本就没问题。playground无复现，本地代码有复现

### What is Expected?

表格内容溢出时，tooltip背景色正常

### What is actually happening?

背景色消失

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/27143024/9068defb-89b2-4381-94a9-47b2a5a754af)

**Comment by webvs2** [comment]
可以做一个在线复现例子吗
