### ISSUE TITLE
[Component] [tour] CDN 下使用el-tour 会报错aria.ts:22  Uncaught (in promise) ReferenceError: process is not defined

### ISSUE THREAD

**Issue by 360060316** [element-plus/element-plus#16861]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: ` Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1 Edg/124.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tour`

### Reproduction Link

[Docs](https://element-plus.org/)

### Steps to reproduce

调试 发布均不能正常

### What is Expected?

正常运行

### What is actually happening?

控制台报错

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
Please provide a mini reproduction and screenshot.

**Comment by plainheart** [comment]
检查了构建后的代码，确实包含了 `process.env` 相关用法。

https://unpkg.com/element-plus@2.7.3/dist/index.full.js

似乎是当前构建脚本中 esbuild [define](https://github.com/element-plus/element-plus/blob/dev/internal/build/src/tasks/full-bundle.ts#L56-L58) 定义的 `process.env.NODE_ENV` 并未将 Tour 组件内引用的三方库 `floating-ui` 代码内的 `process.env.NODE_ENV` 替换 [1]，不太清楚什么原因 🤔。不过如果改用 rollup 的 replace plugin 替换的话，似乎就没问题。

```diff
// ...
+import replace from '@rollup/plugin-replace'

esbuild({
  // ...
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
  },
  // ...
}),
+replace({
+  'process.env.NODE_ENV': JSON.stringify('production'),
+}),

cc: @btea @warmthsea

**Comment by warmthsea** [comment]
https://github.com/floating-ui/floating-ui/issues/1506

**Comment by 360060316** [comment]
`plugins: [
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  })
]`

并不能解决问题

**Comment by warmthsea** [comment]
> `plugins: [ replace({ 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV), }) ]`
> 
> 并不能解决问题

需要elp库更改

**Comment by plainheart** [comment]
@warmthsea 要不你开个 PR 先按这个方案改下？

**Comment by warmthsea** [comment]
> @warmthsea 要不你开个 PR 先按这个方案改下？

好的

**Comment by warmthsea** [comment]
@360060316 
稍后我会发个私包，临时解决你的问题

**Comment by 360060316** [comment]
测试dev版已修复

**Comment by warmthsea** [comment]
> 测试dev版已修复

请与正式版2.7.4发布后替换为正式版的地址
