### ISSUE TITLE
[Style] [dropdown] Dropdown 下拉菜单

### ISSUE THREAD

**Issue by rczdgbg** [element-plus/element-plus#16893]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.6.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dropdown.html)

### Steps to reproduce

1.使浏览器窗口失焦（点另一个新开窗口或者其他） 
2.鼠标移回组件处，hover组件

### What is Expected?

hover弹出的菜单需要有hover样式

### What is actually happening?

没有hover样式

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
请提供一个最小复现

**Comment by rczdgbg** [comment]
> 请提供一个最小复现

![image](https://github.com/element-plus/element-plus/assets/38928451/9c0925ef-3ed3-45a7-bb12-f8bb5d0c0c4f)

我很想去复现 但是提供的环境 用文档copy的代码都跑不起来

贴的文档地址就可以当最小复现  你可以去试试

**Comment by rczdgbg** [comment]
https://codesandbox.io/p/sandbox/element-plus-spa-forked-y6z95z?file=%2Fsrc%2Fmain.js

**Comment by Liao-js** [comment]
能提供一下截图吗？我这边按照你的步骤，看到的是没有问题的

**Comment by rczdgbg** [comment]
https://github.com/element-plus/element-plus/assets/38928451/689c6df5-a1b8-4fe1-a77e-222d77f1fc88

不要让窗口聚焦 直接hover上去

**Comment by rczdgbg** [comment]
![image](https://github.com/element-plus/element-plus/assets/38928451/b3636f0d-e36d-46f9-9fcd-e80945c4130d)
