### ISSUE TITLE
Popper bug list

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#169]

**Comment by zazzaz** [comment]
It's better to provide a pure popper with no default styles like padding, border color
<img width="396" alt="image" src="https://user-images.githubusercontent.com/10731096/90731903-e6339e80-e2fc-11ea-977a-7103fc9669e2.png">

**Comment by zazzaz** [comment]
wrong arrow direction in `effect="light"`
<img width="404" alt="image" src="https://user-images.githubusercontent.com/10731096/90732159-4591ae80-e2fd-11ea-95c9-3ca188c68187.png">

**Comment by JeremyWuuuuu** [comment]
> It's better to provide a pure popper with no default styles like padding, border color (no transitions maybe?)
> <img alt="image" width="396" src="https://user-images.githubusercontent.com/10731096/90731903-e6339e80-e2fc-11ea-977a-7103fc9669e2.png">

I am considering a new API called `shouldDecorate` as `boolean` to  fix this one.

**Comment by JeremyWuuuuu** [comment]
loop @ Ryan2128 in to get updates

**Comment by Ryan2128** [comment]
> loop @Ryan2128 in to get updates

Should I wait for your update first? I don't understand what you mean too much.

**Comment by JeremyWuuuuu** [comment]
> > loop @Ryan2128 in to get updates
> 
> Should I wait for your update first? I don't understand what you mean too much.

Nope, you can go ahead implement features related to tooltip with popper, the current documentation might be fragmentary, 
Here are some APIs you might need:
1. manualMode (if you want to control the tooltip manually like `manual` in tooltip in v2
2. value (if manualMode is set to true) you are going to need it to control the visibility
3. placement as same as tooltip's in v2
4. effect

**Comment by Ryan2128** [comment]
Ok, thank you for your explanation.😁

**Comment by JeremyWuuuuu** [comment]
ElPopper needs to add a minimum width ~20px to `el-popper` in order to keep the arrow placement correct

**Comment by Hades-li** [comment]
![image](https://user-images.githubusercontent.com/12124478/92063242-54806280-edcd-11ea-96ae-dbaca7a53785.png)
I need v-model one value。but，is not work。
![image](https://user-images.githubusercontent.com/12124478/92063403-a2956600-edcd-11ea-8e9d-d2dbd5991815.png)
maybe you need change this code

**Comment by JeremyWuuuuu** [comment]
> ![image](https://user-images.githubusercontent.com/12124478/92063242-54806280-edcd-11ea-96ae-dbaca7a53785.png)
> I need v-model one value。but，is not work。
> ![image](https://user-images.githubusercontent.com/12124478/92063403-a2956600-edcd-11ea-8e9d-d2dbd5991815.png)
> maybe you need change this code

Hey @Hades-li , please note that `el-popper` is only an internal component that provides all component that based on it the ability to use wrapped `@popperjs`, you need you play this on popper's rule, value will only be effective when `manualMode` is set to true, the component which uses `el-popper` will have the control of the visibility of popper.

You just play it by the rule ok?

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/92198295-97623900-eea6-11ea-83f0-14f021db44cb.png)
`Popper.js` will add in-line style for `div.el-poppe-arrow`.But it's not a corrrect stylesheet.

:smiling_imp:
```css
{
    position: absolute;
    left: 0px;
    transform: translate3d(15px, 0px, 0px);
}
```

:100:
```css
{
    position: absolute;
    left: 50%;
    transform: translate3d(-50%, 0px, 0px);
}
```

**Comment by bastarder** [comment]
1. Slots v-if problem， v-show style problem
2. closeDelay
3. `show`, ‘hide’ event miss 
  4. `activated`, `deactivated` should use hook
  5. width ，title props miss

**Comment by JeremyWuuuuu** [comment]
> 1. Slots `v-if` problem， `v-show` style problem
> 2. closeDelay
> 3. `show`, `hide` event miss
> 4. `activated`, `deactivated` should use hook
> 5. `width` ，`title` props miss

I did not see any `width` `title` in v2 [ElementUI](https://element.eleme.cn/#/zh-CN/component/tooltip)

**Comment by zazzaz** [comment]
set `trigger="click"` , should do nothing on mouse leave.

Demo code 
```
<el-popper
    v-model:visible="pickerVisible"
    pure
    effect="light"
    trigger="click"
  >
```

**Comment by zazzaz** [comment]
fixed
