### ISSUE TITLE
[bug report] when the page is enlarged, the head and content of El table will be misplaced

### ISSUE THREAD

**Issue by yeyue1992** [element-plus/element-plus#1691]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
windows Google Chrome 版本 89.0.4389.90（正式版本）

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/yeyue1992/pen/mdReYaV

### Steps to reproduce
Chrome  ctrl     Zoom in page

浏览器放大页面

### What is Expected?
希望能够修复

### What is actually happening?
放大的使用不出现错位现象

**Comment by JeremyWuuuuu** [comment]
cc @justwiner
