### ISSUE TITLE
[Component] [select]: select 配置可清空功能，清空后值变成undefined，类型发生变化

### ISSUE THREAD

**Issue by xingyixiang** [element-plus/element-plus#16919]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgY2xlYXJhYmxlXG4gICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIHt7IGB2YWx1ZSBpcyAke3ZhbHVlfWAgICB9fVxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

下拉选择后点击清空按钮

### What is Expected?

绑定的值还是string类型，值变成空字符串

### What is actually happening?

值变成undefined

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/blob/b1bfb9fd1b52265ffd7737f4e9d81e0ac99c17d6/packages/hooks/use-empty-values/index.ts#L39C1-L51C5

It seems to be here.

**Comment by warmthsea** [comment]
you can set `:empty-values`.

**Comment by warmthsea** [comment]
You can set `:value-on-clear`

![image](https://github.com/element-plus/element-plus/assets/45450994/bd73a675-df19-469a-9153-c7ab5640ca3a)

**Comment by btea** [comment]
@xingyixiang  The current effect should be the same as before 2.7.0. To meet your requirements, configuring `value-on-clear` as @warmthsea  suggested should be enough. 

Or did I misunderstand what you meant? 🤔

**Comment by warmthsea** [comment]
#### clearable after: 

`2.56`:   (<`2.60`)  old value type
`2.60`:   `undefined`
`2.70`:   `undefined` (add new attributes `:value-on-clear`)
🤔

![screenshots](https://github.com/element-plus/element-plus/assets/45450994/f3345123-131b-461e-af51-79bd6c1bb223)

**Comment by btea** [comment]
An adjustment made intentionally in version 2.6.0. https://github.com/element-plus/element-plus/pull/15995

**Comment by xingyixiang** [comment]
> An adjustment made intentionally in version 2.6.0. #15995

If it's a long-term change, so be it.

**Comment by huhaoer** [comment]
> https://github.com/element-plus/element-plus/blob/b1bfb9fd1b52265ffd7737f4e9d81e0ac99c17d6/packages/hooks/use-empty-values/index.ts#L39C1-L51C5
> 
> It seems to be here.

I also encountered this problem, thank you
