### ISSUE TITLE
The global Z-index will not take effect if it is imported on demand

### ISSUE THREAD

**Issue by kiki575** [element-plus/element-plus#1693]

**Comment by kiki575** [comment]
const app = createApp(EntrySdk)
app.config.globalProperties.$ELEMENT = { size: 'small', zIndex: 9000 }

**Comment by JeremyWuuuuu** [comment]
You cannot set it this way, I think it was a mistake we made, you have to use `setConfig`  in the package `@element-plus/utils/config` to set the config.
Just for your reference:
![image](https://user-images.githubusercontent.com/15975785/112717838-08903900-8f2a-11eb-8987-6c7f7842e02d.png)

**Comment by kiki575** [comment]
import { setConfig } from 'element-plus/lib/utils/config.js'
const install = (app, option): void => {
  app.config.globalProperties.$ELEMENT = option
  setConfig(option)

  components.forEach(component => {
    app.component(component.name, component)
  })

  plugins.forEach(plugin => {
    app.use(plugin)
  })
}

let ExportData = {install}

const app = createApp(EntrySdk)
app.use(ExportData, { size: 'small', zIndex: 9000 })
 Am  i right ?     The global Z-index will not take effect if it is imported on demand

**Comment by kiki575** [comment]
我发现修改后调用了setConfig方法，但在使用el-dailog以及其他弹层组件时，并没有调用getConfig
