### ISSUE TITLE
[Bug Report] Drawer Mouse Long press the upper right corner to close the arrow, the default frame will appear

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1695]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=3dc8ce0d-405d-4a23-8875-627b61218f03

### Steps to reproduce
Drawer Mouse Long press the upper right corner to close the arrow, the default frame will appear
![image](https://user-images.githubusercontent.com/20943608/112596335-a4487900-8e46-11eb-8d21-5de2fa4c3eeb.png)

### What is Expected?
Whether it should be cancelled

### What is actually happening?
Drawer Mouse Long press the upper right corner to close the arrow, the default frame will appear

**Comment by JeremyWuuuuu** [comment]
Your codepen link is invalid, I also tried it both locally and on the website, it is not reproducible.

**Comment by jahnli** [comment]
I am the codepen link of the demo on the Element-plus website ，If you long press it, this border will appear

**Comment by jahnli** [comment]
![t](https://user-images.githubusercontent.com/20943608/112650980-e85b6e00-8e86-11eb-80fc-448a135dc2b6.gif)

**Comment by JeremyWuuuuu** [comment]
You mean the "button outline" right?
Instead of some "frame" ...
So in terms of a11y(accessibility) this is an expected behavior because it promotes the users where the cursor is when using keyboard navigation. If you need want to  remove it use the rule
```css
* {
  outline: none;
}
```
to remove it.

**Comment by jahnli** [comment]
Yes, but I don't think Element-Plus should be considered None

**Comment by JeremyWuuuuu** [comment]
> Yes, but I don't think Element-Plus should be considered None

Correct, I think we will fix this in the next release. Sorry for the inconvenience.
