### ISSUE TITLE
[Component] [button] Button link variant has invalid color

### ISSUE THREAD

**Issue by akadlec** [element-plus/element-plus#16979]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mac/Chrome`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/4c3c81e3d61ec8fba411b6a4a233de28acaec8b8/packages/theme-chalk/src/common/var.scss#L698)

### Steps to reproduce

Button with "link" type is using "info" color, so in case you have customized "primary-color" this color is ignored and button is still in blue color

### What is Expected?

Use primary color

### What is actually happening?

Use info color

### Additional comments

_(empty)_

**Comment by btea** [comment]
I don’t seem to understand what you mean, but the official website looks normal.

![image](https://github.com/element-plus/element-plus/assets/24516654/704e9aef-909e-48a3-8bc4-65d74f47fff5)

**Comment by akadlec** [comment]
Hi @btea, I'm using custom primary colors:

```
$--colors: (
	'primary': (
		'base': #d9230f,
	),
	'success': (
		'base': #469408,
	),
	'warning': (
		'base': #d9831f,
	),
	'danger': (
		'base': #db2828,
	),
	'error': (
		'base': #db2828,
	),
	'info': (
		'base': #029acf,
	),
);

@forward 'element-plus/theme-chalk/src/common/var.scss' with (
	$colors: $--colors,
);
```

Everything is ok, but for :HOVER there is still blue color

**Comment by btea** [comment]
It seems normal. 

<img width="1072" alt="image" src="https://github.com/element-plus/element-plus/assets/24516654/fedb29e1-bee2-4d5f-8026-73d2a31d1401">

**Comment by akadlec** [comment]
check this:
![image](https://github.com/element-plus/element-plus/assets/1866672/2890ba61-0207-4a5f-9715-fd822feae369)
![image](https://github.com/element-plus/element-plus/assets/1866672/1446236e-cddd-4c86-8c44-ffa2c7eadefc)

**Comment by akadlec** [comment]
it is using `--el-button-hover-link-text-color` and this var is defined by `--el-color-info` and you could find it on provided link in above

file: /packages/theme-chalk/src/common/var.scss
line: 698

![image](https://github.com/element-plus/element-plus/assets/1866672/d34181eb-6ad3-4de1-8352-7f6ee15d671a)

**Comment by btea** [comment]
This seems to be normal. When type is not set by default, the corresponding variable value of type info is used here.

**Comment by akadlec** [comment]
imo no. Default/Primary color for element-plus is blue, but if I want to change it to different color, it should be applied on all places and the blue color should be replaced by the user defined.

**Comment by btea** [comment]
Because the info color you currently define is blue(#029acf), the corresponding color for hover is blue, which should be logical.

**Comment by akadlec** [comment]
yes, but I need to keep `info` as `blue`. This definition is imo wrong:
```
    'hover-link-text-color': getCssVar('color-info'),
```
other button variables uses `primary` or other variables, but this one is directly to `info`

**Comment by btea** [comment]
> This seems to be normal. When type is not set by default, the corresponding variable value of type info is used here.

Yes, as I said here, when the type is not set by default, the info-related variable value is used directly. It seems that it cannot be changed easily, otherwise it will be a breaking change for existing users.

**Comment by akadlec** [comment]
yes, it could affect users with custom color. but imo it should be fixed.
I could use `type="primary"` for my button but this change will change color of the text to `primary` which is not what I want to achieve. Button should have `default` color and for hover use `primary`

**Comment by btea** [comment]
Can you create a PR?

**Comment by akadlec** [comment]
OK

**Comment by akadlec** [comment]
Hi @btea, thanks for solving the issue. Was not able to find time to create PR :(

**Comment by btea** [comment]
Never mind, I fixed it. : )
