### ISSUE TITLE
[Component] [tree] 官网上 el-tree 自定义节点类名这个例子好像有问题，叶子节点横向显示有问题

### ISSUE THREAD

**Issue by bruce-teng** [element-plus/element-plus#16976]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0'`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImN1c3RvbS10cmVlLW5vZGUtY29udGFpbmVyXCI+XG4gICAgPGVsLXRyZWVcbiAgICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgICA6ZGF0YT1cImRhdGFcIlxuICAgICAgc2hvdy1jaGVja2JveFxuICAgICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICAgIDpleHBhbmQtb24tY2xpY2stbm9kZT1cImZhbHNlXCJcbiAgICAgIDpwcm9wcz1cInsgY2xhc3M6IGN1c3RvbU5vZGVDbGFzcyB9XCJcbiAgICAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5cbmludGVyZmFjZSBUcmVlIHtcbiAgaWQ6IG51bWJlclxuICBsYWJlbDogc3RyaW5nXG4gIGlzUGVudWx0aW1hdGU/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGN1c3RvbU5vZGVDbGFzcyA9IChkYXRhOiBUcmVlLCBub2RlOiBOb2RlKSA9PiB7XG4gIGlmIChkYXRhLmlzUGVudWx0aW1hdGUpIHtcbiAgICByZXR1cm4gJ2lzLXBlbnVsdGltYXRlJ1xuICB9XG4gIHJldHVybiBudWxsXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA0LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBpc1BlbnVsdGltYXRlOiB0cnVlLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA5LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgaXNQZW51bHRpbWF0ZTogdHJ1ZSxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNSxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiA2LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgaXNQZW51bHRpbWF0ZTogdHJ1ZSxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogNyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiA4LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5pcy1wZW51bHRpbWF0ZSA+IC5lbC10cmVlLW5vZGVfX2NvbnRlbnQge1xuICBjb2xvcjogIzYyNmFlZjtcbn1cblxuLmVsLXRyZWUtbm9kZS5pcy1wZW51bHRpbWF0ZSA+IC5lbC10cmVlLW5vZGVfX2NoaWxkcmVuIHtcbiAgZGlzcGxheTogZmxleDtcbiAgZmxleC1kaXJlY3Rpb246IHJvdztcbn1cbi5pcy1wZW51bHRpbWF0ZSA+IC5lbC10cmVlLW5vZGVfX2NoaWxkcmVuID4gZGl2IHtcbiAgd2lkdGg6IDI1JTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

https://element-plus.org/zh-CN/component/tree.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%B1%BB%E5%90%8D
官网的链接，树形组件，自定义节点类名，看这个例子中 css 的意识是把叶子节点横向显示，就是这个
.el-tree-node.is-penultimate > .el-tree-node__children {
    display: flex;
    flex-direction: row;
}

但是看效果，叶子节点没有横向显示，

我把 display: flex; 改成 display: flex !important; 之后，可以横向显示。
但是，此时，点击左边的箭头，叶子节点不能折叠了，一直在那显示

### What is Expected?

叶子节点能够横向显示

### What is actually happening?

叶子节点没有横向显示

### Additional comments

_(empty)_

![运行结果](https://github.com/element-plus/element-plus/assets/24269297/5189bfae-7428-42a3-8bd8-1c94bc9b06a0)

**Comment by warmthsea** [comment]
``` css
.el-tree .el-tree-node.is-expanded > .el-tree-node__children,
.el-tree .el-tree-node.is-penultimate > .el-tree-node__children {
  display: flex ;
  flex-direction: row;
}
```

![screenshots](https://github.com/element-plus/element-plus/assets/45450994/2825bce4-d2f8-4541-848f-044e55cbfc88)

**Comment by bruce-teng** [comment]
> ```css
> .el-tree .el-tree-node.is-expanded > .el-tree-node__children,
> .el-tree .el-tree-node.is-penultimate > .el-tree-node__children {
>   display: flex ;
>   flex-direction: row;
> }
> ```
> 
> ![screenshots](https://private-user-images.githubusercontent.com/45450994/333492465-2825bce4-d2f8-4541-848f-044e55cbfc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzY0MjQsIm5iZiI6MTcxNjUzNjEyNCwicGF0aCI6Ii80NTQ1MDk5NC8zMzM0OTI0NjUtMjgyNWJjZTQtZDJmOC00NTQxLTg0OGYtMDQ0ZTU1Y2JmYzg4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjYzYTIyODc1MzZkYzUzNWQwZjkwYTNkYTg4MzNkMTQ3ZjY2Y2Y2MzNkYzQ3NGUwNGIyOWRjMWI5NTU5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZmJysdWYvSINWEoyJ8CCv_hO_8cqYTKzOGxFAJvaeY) [ ![screenshots](https://private-user-images.githubusercontent.com/45450994/333492465-2825bce4-d2f8-4541-848f-044e55cbfc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzY0MjQsIm5iZiI6MTcxNjUzNjEyNCwicGF0aCI6Ii80NTQ1MDk5NC8zMzM0OTI0NjUtMjgyNWJjZTQtZDJmOC00NTQxLTg0OGYtMDQ0ZTU1Y2JmYzg4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjYzYTIyODc1MzZkYzUzNWQwZjkwYTNkYTg4MzNkMTQ3ZjY2Y2Y2MzNkYzQ3NGUwNGIyOWRjMWI5NTU5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZmJysdWYvSINWEoyJ8CCv_hO_8cqYTKzOGxFAJvaeY) ](https://private-user-images.githubusercontent.com/45450994/333492465-2825bce4-d2f8-4541-848f-044e55cbfc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzY0MjQsIm5iZiI6MTcxNjUzNjEyNCwicGF0aCI6Ii80NTQ1MDk5NC8zMzM0OTI0NjUtMjgyNWJjZTQtZDJmOC00NTQxLTg0OGYtMDQ0ZTU1Y2JmYzg4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjYzYTIyODc1MzZkYzUzNWQwZjkwYTNkYTg4MzNkMTQ3ZjY2Y2Y2MzNkYzQ3NGUwNGIyOWRjMWI5NTU5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZmJysdWYvSINWEoyJ8CCv_hO_8cqYTKzOGxFAJvaeY) [ ](https://private-user-images.githubusercontent.com/45450994/333492465-2825bce4-d2f8-4541-848f-044e55cbfc88.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzY0MjQsIm5iZiI6MTcxNjUzNjEyNCwicGF0aCI6Ii80NTQ1MDk5NC8zMzM0OTI0NjUtMjgyNWJjZTQtZDJmOC00NTQxLTg0OGYtMDQ0ZTU1Y2JmYzg4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjYzYTIyODc1MzZkYzUzNWQwZjkwYTNkYTg4MzNkMTQ3ZjY2Y2Y2MzNkYzQ3NGUwNGIyOWRjMWI5NTU5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZmJysdWYvSINWEoyJ8CCv_hO_8cqYTKzOGxFAJvaeY)

这样是好了，多谢
