### ISSUE TITLE
[Component] [All] 在谷歌21版本的浏览器中，el-input输入中文自动带入拼音

### ISSUE THREAD

**Issue by dwightProject** [element-plus/element-plus#16981]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.23`
- Element Plus Version: `2.7.3`
- Browser / OS: `windows`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues/new/choose)

### Steps to reproduce

在21版本的谷歌浏览器直接用el-input可以复现

### What is Expected?

兼容

### What is actually happening?

兼容

### Additional comments

_(empty)_

**Comment by plainheart** [comment]
21？你是认真的吗？

**Comment by gaojiangtao-git** [comment]
这浏览器版本也太古老

**Comment by kooriookami** [comment]
请先查看一下组件版本对应浏览器的兼容性：https://element-plus.org/zh-CN/guide/installation.html#%E5%85%BC%E5%AE%B9%E6%80%A7
