### ISSUE TITLE
[Component] el-table-v2 设置columns的fixed属性后，如果row-key使用数字或者数字开头的字符串，onRowHovered 事件报错

### ISSUE THREAD

**Issue by pangujs** [element-plus/element-plus#16988]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlLXYyXG4gICAgOmNvbHVtbnM9XCJjb2x1bW5zXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIDp3aWR0aD1cIjcwMFwiXG4gICAgOmhlaWdodD1cIjQwMFwiXG4gICAgcm93LWtleT1cImlkXCJcbiAgICBmaXhlZFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7aH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxJbnB1dCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IGNvbHVtbnMgPSBbXG4gIHtcbiAgICBrZXk6IFwiaWRcIixcbiAgICB0aXRsZTogXCJJRFwiLFxuICAgIGRhdGFLZXk6IFwiaWRcIixcbiAgICB3aWR0aDogMjAwLFxuICAgIGNlbGxSZW5kZXJlcjogKHsgcm93RGF0YSwgY29sdW1uIH0pID0+IGgoRWxJbnB1dCwgeyBtb2RlbFZhbHVlOiByb3dEYXRhLmlkIH0pXG4gIH0sXG4gICB7XG4gICAga2V5OiBcIm5hbWVcIixcbiAgICB0aXRsZTogXCJOYW1lXCIsXG4gICAgZGF0YUtleTogXCJuYW1lXCIsXG4gICAgd2lkdGg6IDIwMCxcbiAgfSxcbiAgIHtcbiAgICBrZXk6IFwicGF0aFwiLFxuICAgIHRpdGxlOiBcIlBhdGhcIixcbiAgICBkYXRhS2V5OiBcInBhdGhcIixcbiAgICB3aWR0aDogMjAwLFxuICB9LFxuICB7XG4gICAga2V5OiBcInBhcmVudFwiLFxuICAgIHRpdGxlOiBcIlBhcmVudFwiLFxuICAgIGRhdGFLZXk6IFwicGFyZW50XCIsXG4gICAgd2lkdGg6IDIwMCxcbiAgfSxcbiAge1xuICAgIGtleTogXCJ0eXBlXCIsXG4gICAgdGl0bGU6IFwiVHlwZVwiLFxuICAgIGRhdGFLZXk6IFwidHlwZVwiLFxuICAgIHdpZHRoOiAyMDAsXG4gICAgZml4ZWQ6ICdyaWdodCcsXG4gIH0sXG5dXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaWQ6IFwiMTAwMDAxXCIsXG4gICAgbmFtZTogXCJuYW1lMVwiLFxuICAgIHBhdGg6IFwiJC5uYW1lMVwiLFxuICAgIHBhcmVudDogXCIxMjNcIlxuICB9LFxuICAgIHtcbiAgICBpZDogXCIxMDAwMDJcIixcbiAgICBuYW1lOiBcIm5hbWUyXCIsXG4gICAgcGF0aDogXCIkLm5hbWUyXCJcbiAgfSxcbiAgICB7XG4gICAgaWQ6IFwiMTAwMDAzXCIsXG4gICAgbmFtZTogXCJuYW1lMlwiLFxuICAgIHBhdGg6IFwiJC5uYW1lM1wiXG4gIH1cbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

column设置fixed属性，并设置row-key字段值是以数字开头字符串

### What is Expected?

column设置fixed属性，并row-key字段值是以数字开头字符串不会报错

### What is actually happening?

column设置fixed属性，并row-key字段值是以数字开头字符串会报错

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed by #16989
