### ISSUE TITLE
[Style] [tabs, tab-pane] 给el-tabs__item的style添加 padding-lert  right  !important 导致只有一个ElTabPane的时候下划线长度计算错误

### ISSUE THREAD

**Issue by k983551019** [element-plus/element-plus#17006]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tabs`
- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiBjbGFzcz1cImRlbW8tdGFic1wiIEB0YWItY2xpY2s9XCJoYW5kbGVDbGlja1wiPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlVzZXJcIiBuYW1lPVwiZmlyc3RcIj5Vc2VyPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJDb25maWdcIiBuYW1lPVwic2Vjb25kXCI+Q29uZmlnPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJSb2xlXCIgbmFtZT1cInRoaXJkXCI+Um9sZTwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVGFza1wiIG5hbWU9XCJmb3VydGhcIj5UYXNrPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuICAgIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgY2xhc3M9XCJkZW1vLXRhYnNcIiBAdGFiLWNsaWNrPVwiaGFuZGxlQ2xpY2tcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+VXNlcjwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBUYWJzUGFuZUNvbnRleHQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcblxuY29uc3QgaGFuZGxlQ2xpY2sgPSAodGFiOiBUYWJzUGFuZUNvbnRleHQsIGV2ZW50OiBFdmVudCkgPT4ge1xuICBjb25zb2xlLmxvZyh0YWIsIGV2ZW50KVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5kZW1vLXRhYnM+LmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuXG4uZGVtby10YWJzIHtcbiAgLmVsLXRhYnNfX2hlYWRlciB7XG4gICAgLmVsLXRhYnNfX2l0ZW0ge1xuICAgICAgcGFkZGluZy1yaWdodDogMjBweCAhaW1wb3J0YW50O1xuICAgICAgcGFkZGluZy1sZWZ0OiAyMHB4ICAhaW1wb3J0YW50O1xuICAgIH1cbiAgfVxufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

```
.demo-tabs {
  .el-tabs__header {
    .el-tabs__item {
      padding-right: 20px !important;
      padding-left: 20px  !important;
    }
  }
}
```

### What is Expected?

样式正常

### What is actually happening?

样式错误

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/48147837/4e158f2a-9524-4cef-af5d-0e947d20b5c0)

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/blob/f57b10c2ba89444c33b7a9d71842a78a0e14431d/packages/components/tabs/src/tab-bar.vue#L58C6-L58C35

似乎是这里的代码引起的，你可以选择自己提交PR或者等待其它人有时间来解决这个问题（需要考虑删除这一行带来的影响）
