### ISSUE TITLE
[TypeScript] [All] 组件类型报错，提示缺少属性

### ISSUE THREAD

**Issue by noclimbing** [element-plus/element-plus#17018]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](https://gitee.com/dromara/RuoYi-Vue-Plus.git)

### Steps to reproduce

克隆代码、安装依赖、组件类型报错

### What is Expected?

组件不再提示缺少属性

### What is actually happening?

组件提示缺少属性

### Additional comments

![image](https://github.com/element-plus/element-plus/assets/33425644/4ec69985-074e-46fc-a77e-26fa5b2939eb)

**Comment by warmthsea** [comment]
![image](https://github.com/element-plus/element-plus/assets/45450994/0dc3f200-2f13-42d4-9706-cadea8ba4c29)

Reproduction Link seems to be invalid. I did not find element-plus in this project.

**Comment by warmthsea** [comment]
https://gitee.com/JavaLionLi/plus-ui/blob/ts/src/types/global.d.ts#L8

Delete this line, It will work normally.

**Comment by noclimbing** [comment]
> https://gitee.com/JavaLionLi/plus-ui/blob/ts/src/types/global.d.ts#L8
> 
> Delete this line, It will work normally.

Thanks, that worked!
