### ISSUE TITLE
[Component] [notification] Notification 通知组件的title与message会出现不换行然后超出当前范围的情况

### ISSUE THREAD

**Issue by yaowangmx** [element-plus/element-plus#17021]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.3`
- Browser / OS: `User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPiBDbG9zZXMgYXV0b21hdGljYWxseSA8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxOb3RpZmljYXRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4xID0gKCkgPT4ge1xuICBFbE5vdGlmaWNhdGlvbih7XG4gICAgdGl0bGU6ICdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEnLFxuICAgIG1lc3NhZ2U6IGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEnKSxcbiAgfSlcbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

title与messages设置为同一个字母比如：AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### What is Expected?

通知组件样式正常换行显示

### What is actually happening?

文本没有换行

### Additional comments

解决方法：
`
.el-notification {
  .el-notification__icon {
    flex-shrink: 0;
  }
  .el-notification__group {
    flex: 1;
    width: 0;
    .el-notification__title,
    .el-notification__content p {
      word-wrap: break-word !important;
      word-break: normal !important;
    }
  }
}
`

**Comment by Liao-js** [comment]
你可以试着自己提交 PR 的
