### ISSUE TITLE
[TypeScript] [popover] Popover 气泡卡片 effect Type bug

### ISSUE THREAD

**Issue by stevqin** [element-plus/element-plus#17030]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.2`
- Browser / OS: `edge `
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/popover.html#attributes)

### Steps to reproduce

```vue
<template>
    <el-popover
         placement="left"
         effect="dark"
         :width="250">
    </el-popover>
</template>
```

经过TS约束检查时发现, effect 可接受的参数仅为 string
与文档中提到的,支持element theme 主题 dark 和 light 表现不一致;

### What is Expected?

期望 修复 el-popover 组件对 effect 属性的约束. 将错误的 约束类型 "string" 更改为  "dark" | "light"

### What is actually happening?

当前el-popover 组件的 effect属性只允许使用 "string" 作为属性值

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
欢迎 PR
