### ISSUE TITLE
[Bug Report] No response when type the first letter in 'el-select' component

### ISSUE THREAD

**Issue by vanoneang** [element-plus/element-plus#1705]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Chrome

### Vue version
3.0.9

### Reproduction Link
https://codepen.io/vanoneang/pen/vYgKmav

### Steps to reproduce
Component: select
1. use property `filter-method` to bind a function `search`
2. print the parameter of the `search()` function 

### What is Expected?
Print the letter

### What is actually happening?
No response when typing the first letter in 'el-select' component

**Comment by JeremyWuuuuu** [comment]
It seems like the function is working, but when the first letter came in, nothing happened.
![image](https://user-images.githubusercontent.com/15975785/112784647-c9c2c600-9084-11eb-8535-8cf28f34abc7.png)

**Comment by JeremyWuuuuu** [comment]
Definitely a bug, will fix soon.
