### ISSUE TITLE
[Bug Report] Failed to resolve import "element-plus/lib/theme-chalk/locale.css" from "src\plugins\element-plus\index.ts". Does the file exist?

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1706]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
1.0.2-beta.36

### Vue version
3.0.9

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaxw

### Steps to reproduce
So when I load the import locale on demand, I'll follow the documentation and I'll be prompted

 [vite] Internal server error: Failed to resolve import "element-plus/lib/theme-chalk/locale.css" from "src\plugins\element-plus\index.ts". Does the file exist?

### What is Expected?
fix

### What is actually happening?
So when I load the import locale on demand, I'll follow the documentation and I'll be prompted

 [vite] Internal server error: Failed to resolve import "element-plus/lib/theme-chalk/locale.css" from "src\plugins\element-plus\index.ts". Does the file exist?

![image](https://user-images.githubusercontent.com/20943608/112775621-01734300-9070-11eb-9ec9-527c07723bdf.png)

**Comment by Ryan2128** [comment]
Please check the latest docs. Use `vite-plugin-style-import` , and add `ensureStyleFile: true`.

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        ensureStyleFile: true,
        resolveStyle: (name) => {
          if(name === 'locale') return '';
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    })
  ]
})
```

**Comment by jahnli** [comment]
I have installed vite-plugin-style-import, but the documentation doesn't say to set ensureStyleFile: true

I have added locale judgment to vite.config.js

**Comment by JeremyWuuuuu** [comment]
> I have installed vite-plugin-style-import, but the documentation doesn't say to set ensureStyleFile: true
> 
> I have added locale judgment to vite.config.js

Did the steps you took fix the issue? We will add the description in the next release.

**Comment by jahnli** [comment]
I installed vite-plugin-style-import according to the documentation.
But you also need to
 resolveStyle: (name) => {
      if(name === 'locale') return '';
      return `element-plus/packages/theme-chalk/src/${name}.scss`;
    }

**Comment by wukang0718** [comment]
```
{
          	libraryName: 'element-plus',
          	resolveStyle: (name) => {
				name = name.slice(3)
				return `element-plus/packages/theme-chalk/src/${name}.scss`;
			},
			resolveComponent: (name) => {
				return `element-plus/lib/${name}`;
			},
			esModule: true,
			ensureStyleFile: true
        }
```
After setting both `esModule` and `ensurestyleFile`, there are no errors

**Comment by jahnli** [comment]
@wukang0718  yes I tried  I can

**Comment by wukang0718** [comment]
`npm run build`
![image](https://user-images.githubusercontent.com/42261663/112789680-37282400-9090-11eb-9e12-9ab23564d10b.png)
Ever seen?

**Comment by Ryan2128** [comment]
> I have installed vite-plugin-style-import, but the documentation doesn't say to set ensureStyleFile: true
> 
> I have added locale judgment to vite.config.js

Will update docs next version.
