### ISSUE TITLE
[Component] [tour] 在dialog中使用el-tour,svg镂空位置绘制出错

### ISSUE THREAD

**Issue by WangYIlo** [element-plus/element-plus#17071]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.7.3`
- Browser / OS: `Edg`
- Build Tool: `Vite`

### Related Component

- `el-tour`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9wZW5EaWFsb2dcIj7miZPlvIDlr7nor53moYY8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtZGlhbG9nXG4gICAgICB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiXG4gICAgICB0aXRsZT1cIuWvueivneahhlwiXG4gICAgICBkZXN0cm95LW9uLWNsb3NlXG4gICAgICB3aWR0aD1cIjMwJVwiXG4gICAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIj5cbiAgICAgIDxlbC1jb250YWluZXI+XG4gICAgICA8ZWwtYXNpZGUgd2lkdGg9XCIyMDBweFwiPlxuICAgICAgICA8dWwgcmVmPVwidGVzdFwiPlxuICAgICAgICAgIDxsaSB2LWZvcj1cIml0ZW0gaW4gaXRlbXNcIiA6a2V5PVwiaXRlbS5pZFwiPnt7IGl0ZW0ubmFtZSB9fTwvbGk+XG4gICAgICAgIDwvdWw+XG4gICAgICA8L2VsLWFzaWRlPlxuICAgIDwvZWwtY29udGFpbmVyPlxuICAgIDwvZWwtZGlhbG9nPlxuICA8L2Rpdj5cbiAgPGVsLXRvdXIgdi1tb2RlbD1cIm9wZW5cIiA6ei1pbmRleD1cIjk5OTlcIj5cbiAgICA8ZWwtdG91ci1zdGVwIDp0YXJnZXQ9XCJ0ZXN0XCIgdGl0bGU9XCJVcGxvYWQgRmlsZVwiIHBsYWNlbWVudD1cInJpZ2h0XCI+XG4gICAgICA8aW1nXG4gICAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgICAgc3JjPVwiaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmdcIlxuICAgICAgICBhbHQ9XCJ0b3VyLnBuZ1wiXG4gICAgICAvPlxuICAgICAgPGRpdj5QdXQgeW91IGZpbGVzIGhlcmUuPC9kaXY+XG4gICAgPC9lbC10b3VyLXN0ZXA+XG4gIDwvZWwtdG91cj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG4gIGNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpO1xuICBjb25zdCB0ZXN0ID0gcmVmKClcbiAgY29uc3Qgb3BlbiA9IHJlZihmYWxzZSlcbiAgY29uc3QgaXRlbXMgPSBbXG4gICAgeyBpZDogMSwgbmFtZTogJ+mhueebrjEnIH0sXG4gICAgeyBpZDogMiwgbmFtZTogJ+mhueebrjInIH0sXG4gICAgeyBpZDogMywgbmFtZTogJ+mhueebrjMnIH1cbiAgXTtcblxuICBjb25zdCBvcGVuRGlhbG9nID0gKCkgPT4ge1xuICAgIG9wZW4udmFsdWUgPSB0cnVlXG4gICAgY29uc29sZS5sb2codGVzdClcbiAgICBkaWFsb2dWaXNpYmxlLnZhbHVlID0gdHJ1ZTtcbiAgfTtcblxuICBjb25zdCBoYW5kbGVDbG9zZSA9IChkb25lKSA9PiB7XG4gICAgZGlhbG9nVmlzaWJsZS52YWx1ZSA9IGZhbHNlO1xuICAgIGRvbmUoKTtcbiAgfTtcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

将target定为el-dialog中内部的元素

### What is Expected?

svg绘制镂空位置正确

### What is actually happening?

svg绘制镂空位置发生偏差

### Additional comments

使用debugger后位置正常，或者在异常的时候使用F12后位置正常

**Comment by Liao-js** [comment]
你可以试下 el-dialog 打开动画结束后，才打开 el-tour。如 [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9wZW5EaWFsb2dcIj7miZPlvIDlr7nor53moYY8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtZGlhbG9nIEBvcGVuZWQ9XCJoYW5kbGVPcGVuZWRcIiB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiIHRpdGxlPVwi5a+56K+d5qGGXCIgZGVzdHJveS1vbi1jbG9zZSB3aWR0aD1cIjMwJVwiIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiPlxuICAgICAgPGVsLWNvbnRhaW5lcj5cbiAgICAgICAgPGVsLWFzaWRlIHdpZHRoPVwiMjAwcHhcIj5cbiAgICAgICAgICA8dWwgcmVmPVwidGVzdFwiPlxuICAgICAgICAgICAgPGxpIHYtZm9yPVwiaXRlbSBpbiBpdGVtc1wiIDprZXk9XCJpdGVtLmlkXCI+e3sgaXRlbS5uYW1lIH19PC9saT5cbiAgICAgICAgICA8L3VsPlxuICAgICAgICA8L2VsLWFzaWRlPlxuICAgICAgPC9lbC1jb250YWluZXI+XG4gICAgPC9lbC1kaWFsb2c+XG4gIDwvZGl2PlxuICA8ZWwtdG91ciB2LW1vZGVsPVwib3BlblwiIDp6LWluZGV4PVwiOTk5OVwiPlxuICAgIDxlbC10b3VyLXN0ZXAgOnRhcmdldD1cInRlc3RcIiB0aXRsZT1cIlVwbG9hZCBGaWxlXCIgcGxhY2VtZW50PVwicmlnaHRcIj5cbiAgICAgIDxpbWcgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIiBzcmM9XCJodHRwczovL2VsZW1lbnQtcGx1cy5vcmcvaW1hZ2VzL2VsZW1lbnQtcGx1cy1sb2dvLnN2Z1wiIGFsdD1cInRvdXIucG5nXCIgLz5cbiAgICAgIDxkaXY+UHV0IHlvdSBmaWxlcyBoZXJlLjwvZGl2PlxuICAgIDwvZWwtdG91ci1zdGVwPlxuICA8L2VsLXRvdXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYsIG5leHRUaWNrIH0gZnJvbSAndnVlJztcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpO1xuY29uc3QgdGVzdCA9IHJlZigpXG5jb25zdCBvcGVuID0gcmVmKGZhbHNlKVxuY29uc3QgaXRlbXMgPSBbXG4gIHsgaWQ6IDEsIG5hbWU6ICfpobnnm64xJyB9LFxuICB7IGlkOiAyLCBuYW1lOiAn6aG555uuMicgfSxcbiAgeyBpZDogMywgbmFtZTogJ+mhueebrjMnIH1cbl07XG5cbmNvbnN0IG9wZW5EaWFsb2cgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKHRlc3QpXG4gIGRpYWxvZ1Zpc2libGUudmFsdWUgPSB0cnVlO1xufTtcblxuY29uc3QgaGFuZGxlT3BlbmVkID0gKCkgPT4ge1xuICBvcGVuLnZhbHVlID0gdHJ1ZVxufVxuXG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmUpID0+IHtcbiAgZGlhbG9nVmlzaWJsZS52YWx1ZSA9IGZhbHNlO1xuICBkb25lKCk7XG59O1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by WangYIlo** [comment]
谢谢可以啦
