### ISSUE TITLE
[Docs] [form, checkbox-group] 官网示例代码疑似存在错误

### ISSUE THREAD

**Issue by xianggu-skillnote** [element-plus/element-plus#17087]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.18`
- Element Plus Version: `2.7.3`
- Browser / OS: `Edge`
- Build Tool: `Webpack`

### Related Component

- `el-form`
- `el-checkbox-group`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/form.html#basic-form)

### Steps to reproduce

官网在el-form的说明页中，使用实例中的BasicForm展示了checkbox-group的用法。
示例的代码如下：
```
 <el-checkbox-group v-model="form.type">
        <el-checkbox value="Online activities" name="type">
          Online activities
        </el-checkbox>
        <el-checkbox value="Promotion activities" name="type">
          Promotion activities
        </el-checkbox>
        <el-checkbox value="Offline activities" name="type">
          Offline activities
        </el-checkbox>
        <el-checkbox value="Simple brand exposure" name="type">
          Simple brand exposure
        </el-checkbox>
      </el-checkbox-group> 
```
我在本地环境运行这套示例代码，发现任意checkbox勾选时，其余所有checkbox都会被勾选。
我猜测是否是因为代码中的el-check缺少label属性所导致。盼请核实。

### What is Expected?

修复文档

### What is actually happening?

文档中的el-checkbox属性缺失

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/17051

**Comment by xianggu-skillnote** [comment]
@warmthsea Thank you for fixing the description in the document!
 I just noticed that my project is running on version 2.2, so the `value `attribute in the checkbox-group does not work for me.
maybe I should update to >2.6 or keep using` label `
