### ISSUE TITLE
[Style] [table] el-table 表格样式排版小bug

### ISSUE THREAD

**Issue by mpmp22** [element-plus/element-plus#17083]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/mpmp22/pen/bGyWZoV)

### Steps to reproduce

直接通过浏览器的 HTML 标签导入 Element Plus 使用 el-table 表格 样式排版是一种列表展示，它不是表格展示！

### What is Expected?

样式正常

### What is actually happening?

样式出错

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
It doesn't look like a simple style error, it may be a data rendering anomaly.

**Comment by warmthsea** [comment]
### Use CDN:

❌❌❌❌❌❌

``` vue
<el-table :data="tableData">
    <el-table-column prop="address" label="Address" />
    <el-table-column prop="name" label="Name" />
    <el-table-column prop="date" label="Date" /> 
</el-table>
```
😱😱😱
![image](https://github.com/element-plus/element-plus/assets/45450994/f6abe83a-4780-4a78-9fe9-e1d147d389e4)

✅✅✅✅✅✅

``` vue
<el-table :data="tableData">
    <el-table-column prop="address" label="Address"></el-table-column>
    <el-table-column prop="name" label="Name"></el-table-column>
    <el-table-column prop="date" label="Date"></el-table-column>
</el-table>
```

``` vue
<el-table :data="tableData">
    <el-table-column prop="address" label="Address">
        <template #default="scope">
            {{scope.row.address}}
        </template>
    </el-table-column>
    <el-table-column prop="name" label="Name">
        <template #default="scope">
            {{scope.row.name}}
        </template>
    </el-table-column>
    <el-table-column prop="date" label="Date">
        <template #default="scope">
            {{scope.row.date}}
        </template>
    </el-table-column>
</el-table>
```

![image](https://github.com/element-plus/element-plus/assets/45450994/61e5fb5e-da1e-4140-af1a-b8068f25257e)

**Comment by warmthsea** [comment]
``` vue
<el-input v-model="title" style="width: 240px" placeholder="Please input" />
<el-input v-model="title" style="width: 240px" placeholder="Please input" />
<el-input v-model="title" style="width: 240px" placeholder="Please input" />
```

![image](https://github.com/element-plus/element-plus/assets/45450994/e48f2abf-ddf0-4bc1-baff-270e44c7cf2a)
