### ISSUE TITLE
[Docs] [input] 中文文档：input -> API -> Attributes 中show-word-limit和rows默认值错误，英文版正确

### ISSUE THREAD

**Issue by sleepyShen1989** [element-plus/element-plus#17086]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.3.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html#api)

### Steps to reproduce

打开文档地址https://element-plus.org/zh-CN/component/input.html#api

### What is Expected?

show-word-limit和rows默认值正确

### What is actually happening?

show-word-limit和rows默认值错误

### Additional comments

_(empty)_

**Comment by btea** [comment]
谢谢反馈，已经修改。https://crowdin.com/editor/element-plus/781/en-zhcn?view=comfortable&filter=basic&value=0

**Comment by sleepyShen1989** [comment]
> 谢谢反馈，已经修改。https://crowdin.com/editor/element-plus/781/en-zhcn?view=comfortable&filter=basic&value=0

我看了下文档还是老样子，是我这里缓存问题吗？

**Comment by btea** [comment]
不是缓存问题，官网要等下次发版一起更新。

**Comment by sleepyShen1989** [comment]
了解了，感谢回复
