### ISSUE TITLE
[Component] [dialog] Dialog将draggable和overflow设为true，拖到最右，会出现滚动条

### ISSUE THREAD

**Issue by lanrenbulan** [element-plus/element-plus#17094]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.4`
- Browser / OS: `Chrome 124.0.6367.208`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dialog.html)

### Steps to reproduce

官网示例即可复现

### What is Expected?

无滚动条出现

### What is actually happening?

有滚动条出现，

### Additional comments

且向下拖动时，可以一直接拖动，比如在windows系统，鼠标可以拖动在任务栏。

![1717597430682](https://github.com/element-plus/element-plus/assets/9604624/818a50dc-7cc1-438e-8756-9d9e362b143f)
![1717597660081](https://github.com/element-plus/element-plus/assets/9604624/c044e25d-b10c-4920-897a-60cdce906f66)
![1717597572064](https://github.com/element-plus/element-plus/assets/9604624/301e8568-a47b-447a-9030-c456403f76a1)

**Comment by warmthsea** [comment]
这个问题似乎是正常行为，没必要解决

**Comment by lanrenbulan** [comment]
> 这个问题似乎是正常行为 🫨

是正常行为？不太理解

**Comment by warmthsea** [comment]
> > 这个问题似乎是正常行为 🫨
> 
> 是正常行为？不太理解

如果没有滚动条，比较大的弹框超出屏幕了，就无法看到内容了

**Comment by lanrenbulan** [comment]
这样看，也不算是BUG了。可以自己覆写样式决定了
