### ISSUE TITLE
🎉 Welcome to Element Plus 

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#171]
![element-plus-logo](https://user-images.githubusercontent.com/10731096/91267529-259f3680-e7a6-11ea-9a60-3286f750de01.png)

Element Plus - A Vue.js 3.0 UI library
------

## Core Updates

Element UI is an awesome Vue 2.x UI library.

However, in order to support Vue 3.0 with new syntax and great composition API, a  fully refactor and rewritten is needed.

[Element Plus](https://github.com/element-plus/element-plus/)  is the next generation of Element UI with full **Vue 3.0** composition API support. 

And it's rewritten in **TypeScript** with predictable static types. 

## Dependency Updates

The dependencies in the current project are slightly old, we managed to update them to the current stable version to get better performance and new features.

- @popperjs/core ^2.4.4 (replace old popperjs 1.x)
- dayjs ^1.8.33 (replace old fecha)
- async-validator ^3.4.0 (replace old async-validator 1.x)
- lodash ^4.17.20 (replace some old utils) **Note: only those have been used will be packaging into the bundle**

## Relation to Element UI 

<img width="889" alt="Screen Shot 2020-12-05 at 11 42 53 PM" src="https://user-images.githubusercontent.com/10731096/101251463-d7acae00-3758-11eb-9b45-ecda5c566b9d.png">

Element will stay with Vue 2.x

For Vue 3.0, we recommend using Element Plus from the same team

https://github.com/ElemeFE/element/blob/dev/README.md

## Project Status

Alpha release  🎉🎉🎉
```
npm install element-plus
```

This project is still under heavy development. 

Feel free to join us and make your first pull request. 

If you like Element Plus, Give us a 💖 star 💖 to support us.

**Comment by Linkontoask** [comment]
nice

**Comment by CHOYSEN** [comment]
What's the difference between the two projects?

[https://github.com/kkbjs/element3](url)

**Comment by chuzhixin** [comment]
💯💯💯 多番打探比对，发现还是element-ui原来的团队成员，这下可算放心了，vue-admin-beautiful差点就要换成了ant-design了，恭喜element plus获得新生

**Comment by NO-MAP** [comment]
什么时候能发布呢？可以给一个大概的时间么。

**Comment by zazzaz** [comment]
@NO-MAP You can use 
```
npm install element-plus@latest
```
to try Element Plus today.

And also check here as an installation reference.
https://element-plus.org/#/en-US/component/installation

**Comment by NO-MAP** [comment]
> @NO-MAP
> This project is still under heavy development.
> 
> However, you can use
> 
> ```
> npm install element-plus@latest
> ```
> 
> to try the alpha version today.
> 
> And also check here as an installation reference.
> https://element-plus.org/#/en-US/component/installation

ok, i got it, thanks.

**Comment by trincer** [comment]
什么时候能发布呢？能否给一个大致的时间计划？

**Comment by zazzaz** [comment]
@trincer We plan to release within one month if everything goes well as expected.

**Comment by zhuzhichao** [comment]
期待早日发布，祝顺利！

**Comment by trincer** [comment]
> @trincer We plan to release within one month if everything goes well as expected.

Looking forward to that. Thanks!

**Comment by ElementPlus** [comment]
🎉

**Comment by sunlifei1** [comment]
I have been using element-ui as a desktop application for a long time. I am a fan of element-ui. I hope that the development team can do better than the previous version.

**Comment by ElementPlus** [comment]
Thanks, and feel free to join our Element Plus development.
________________________________

**Comment by SJanJan** [comment]
element ui是世界上最好用的框架

**Comment by liangbaika** [comment]
什么时候能发布正式的呢

**Comment by zazzaz** [comment]
> 什么时候能发布正式的呢

@liangbaika You can now use Element Plus vie npm today.

**Comment by IWSR** [comment]
是继续以饿了吗的名义开发，还是以私人团队的名义开发？饿了吗被阿里收购后内部不是都被统一成react了吗，为什么这个还有3.x的兼容计划？

**Comment by anrananran** [comment]
@zazzaz 大佬的github是小号吗，想关注一波

**Comment by kang558** [comment]
很不错，看到尤大星星了，顺道看了一下。加油！期待稳定版本

**Comment by OLetsGame** [comment]
加油，献上 star 支持一下，会持续关注！

**Comment by lycHub** [comment]
你好，为什么vue3的源码是ts和js混合的呢

**Comment by JeremyWuuuuu** [comment]
### how to make feature request 
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

### Open a new feature request
https://github.com/element-plus/element-plus/discussions/new

**Comment by TothingWay** [comment]
正式版预计还有多久发布

**Comment by snowdream** [comment]
是否可以投入生产？

**Comment by werfei** [comment]
table是否可以支持ui虚拟化
