### ISSUE TITLE
[Component] [date-picker] DatePicker reports error: Unchecked runtime.lastError by "inlineForm.html:13"

### ISSUE THREAD

**Issue by zhy1378** [element-plus/element-plus#17102]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.4`
- Browser / OS: `Edge 125.0.2535.67/ macOS 14.5`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHNpemUgPSByZWY8J2RlZmF1bHQnIHwgJ2xhcmdlJyB8ICdzbWFsbCc+KCdkZWZhdWx0JylcblxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgdmFsdWUyID0gcmVmKCcnKVxuXG5jb25zdCBzaG9ydGN1dHMgPSBbXG5cdHtcblx0XHR0ZXh0OiAnVG9kYXknLFxuXHRcdHZhbHVlOiBuZXcgRGF0ZSgpXG5cdH0sXG5cdHtcblx0XHR0ZXh0OiAnWWVzdGVyZGF5Jyxcblx0XHR2YWx1ZTogKCkgPT4ge1xuXHRcdFx0Y29uc3QgZGF0ZSA9IG5ldyBEYXRlKClcblx0XHRcdGRhdGUuc2V0VGltZShkYXRlLmdldFRpbWUoKSAtIDM2MDAgKiAxMDAwICogMjQpXG5cdFx0XHRyZXR1cm4gZGF0ZVxuXHRcdH1cblx0fSxcblx0e1xuXHRcdHRleHQ6ICdBIHdlZWsgYWdvJyxcblx0XHR2YWx1ZTogKCkgPT4ge1xuXHRcdFx0Y29uc3QgZGF0ZSA9IG5ldyBEYXRlKClcblx0XHRcdGRhdGUuc2V0VGltZShkYXRlLmdldFRpbWUoKSAtIDM2MDAgKiAxMDAwICogMjQgKiA3KVxuXHRcdFx0cmV0dXJuIGRhdGVcblx0XHR9XG5cdH1cbl1cblxuY29uc3QgZGlzYWJsZWREYXRlID0gKHRpbWU6IERhdGUpID0+IHtcblx0cmV0dXJuIHRpbWUuZ2V0VGltZSgpID4gRGF0ZS5ub3coKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGgyPuWuouaIt+e8lui+kTwvaDI+XG5cblx0PGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJzaXplXCIgYXJpYS1sYWJlbD1cInNpemUgY29udHJvbFwiPlxuXHRcdDxlbC1yYWRpby1idXR0b24gdmFsdWU9XCJsYXJnZVwiPmxhcmdlPC9lbC1yYWRpby1idXR0b24+XG5cdFx0PGVsLXJhZGlvLWJ1dHRvbiB2YWx1ZT1cImRlZmF1bHRcIj5kZWZhdWx0PC9lbC1yYWRpby1idXR0b24+XG5cdFx0PGVsLXJhZGlvLWJ1dHRvbiB2YWx1ZT1cInNtYWxsXCI+c21hbGw8L2VsLXJhZGlvLWJ1dHRvbj5cblx0PC9lbC1yYWRpby1ncm91cD5cblx0PGRpdiBjbGFzcz1cImRlbW8tZGF0ZS1waWNrZXJcIj5cblx0XHQ8ZGl2IGNsYXNzPVwiYmxvY2tcIj5cblx0XHRcdDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPkRlZmF1bHQ8L3NwYW4+XG5cdFx0XHQ8ZWwtZGF0ZS1waWNrZXJcblx0XHRcdFx0di1tb2RlbD1cInZhbHVlMVwiXG5cdFx0XHRcdHR5cGU9XCJkYXRlXCJcblx0XHRcdFx0cGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCJcblx0XHRcdFx0OnNpemU9XCJzaXplXCJcblx0XHRcdC8+XG5cdFx0PC9kaXY+XG5cdFx0PGRpdiBjbGFzcz1cImJsb2NrXCI+XG5cdFx0XHQ8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5QaWNrZXIgd2l0aCBxdWljayBvcHRpb25zPC9zcGFuPlxuXHRcdFx0PGVsLWRhdGUtcGlja2VyXG5cdFx0XHRcdHYtbW9kZWw9XCJ2YWx1ZTJcIlxuXHRcdFx0XHR0eXBlPVwiZGF0ZVwiXG5cdFx0XHRcdHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiXG5cdFx0XHRcdDpkaXNhYmxlZC1kYXRlPVwiZGlzYWJsZWREYXRlXCJcblx0XHRcdFx0OnNob3J0Y3V0cz1cInNob3J0Y3V0c1wiXG5cdFx0XHRcdDpzaXplPVwic2l6ZVwiXG5cdFx0XHQvPlxuXHRcdDwvZGl2PlxuXHQ8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1kYXRlLXBpY2tlciB7XG5cdGRpc3BsYXk6IGZsZXg7XG5cdHdpZHRoOiAxMDAlO1xuXHRwYWRkaW5nOiAwO1xuXHRmbGV4LXdyYXA6IHdyYXA7XG59XG5cbi5kZW1vLWRhdGUtcGlja2VyIC5ibG9jayB7XG5cdHBhZGRpbmc6IDMwcHggMDtcblx0dGV4dC1hbGlnbjogY2VudGVyO1xuXHRib3JkZXItcmlnaHQ6IHNvbGlkIDFweCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuXHRmbGV4OiAxO1xufVxuXG4uZGVtby1kYXRlLXBpY2tlciAuYmxvY2s6bGFzdC1jaGlsZCB7XG5cdGJvcmRlci1yaWdodDogbm9uZTtcbn1cblxuLmRlbW8tZGF0ZS1waWNrZXIgLmRlbW9uc3RyYXRpb24ge1xuXHRkaXNwbGF5OiBibG9jaztcblx0Y29sb3I6IHZhcigtLWVsLXRleHQtY29sb3Itc2Vjb25kYXJ5KTtcblx0Zm9udC1zaXplOiAxNHB4O1xuXHRtYXJnaW4tYm90dG9tOiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

The project is standard Vue 3 Project with TypeScript, and the code is copied from the standard sample.

So simple.

### What is Expected?

It should be compatible with Edge.

### What is actually happening?

The code is copied from the standard sample, but it failed with:

"inlineForm.html:13 " 

Unchecked runtime.lastError: You do not have a background page.

However, the code works in Chrome and Safari on MacOS. But by Microsoft Edge, it encounters an error.

### Additional comments

When I open the sample page directly in Edge on MacOS, it contains two error:

https://element-plus.org/en-US/component/date-picker.html

app.c684b821.js:4  Hydration completed but contains mismatches.

inlineForm.html:13  Unchecked runtime.lastError: You do not have a background page.

**Comment by btea** [comment]
My local environment is edge 125.0.2535.92, mac 14.4.1 and there is no duplicate line. Perhaps more information is needed.
