### ISSUE TITLE
[Bug Report] vite build error

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#1710]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
win10

### Vue version
3.0.9

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaxw

### Steps to reproduce
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [
        {
          	libraryName: 'element-plus',
          	resolveStyle: (name) => {
				name = name.slice(3)
				return `element-plus/packages/theme-chalk/src/${name}.scss`;
			},
			resolveComponent: (name) => {
				return `element-plus/lib/${name}`;
			},
			esModule: true,
			ensureStyleFile: true
        }
      ]
    })
  ]
})
```
```
npm run build
```
![image](https://user-images.githubusercontent.com/42261663/112789646-21b2fa00-9090-11eb-80e6-35c0a5b0a8f3.png)

### What is Expected?
build success

### What is actually happening?
build failed

**Comment by wukang0718** [comment]
```app.component(ElCard.name, ElCard)```
![image](https://user-images.githubusercontent.com/42261663/112798046-e966e800-909e-11eb-81cd-09a7bd048b41.png)

**Comment by wukang0718** [comment]
after `vue-tsc` In 0.0.16 version 
![image](https://user-images.githubusercontent.com/42261663/112828053-c568ce00-90c1-11eb-9fd3-0fdf0216ef10.png)

**Comment by keno80** [comment]
try this

 "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit --skipLibCheck && vite build",
    "serve": "vite preview"
  },

add --skipLibCheck to build

**Comment by wukang0718** [comment]
yes, it's ok
