### ISSUE TITLE
[Component] [input] Input class based on append/prepend slot is not reactive because slots are not reactive

### ISSUE THREAD

**Issue by krystian-wolarek** [element-plus/element-plus#17112]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.4`
- Browser / OS: `Chrome 123.0.6312.124 / macOS 12.6.3`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInRvZ2dsZVNsb3RcIj50b2dnbGUgc2xvdDwvZWwtYnV0dG9uPjxici8+XG4gICAgPGVsLWlucHV0XG4gICAgICB2LW1vZGVsPVwiaW5wdXQxXCJcbiAgICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICNbZHluYW1pY1Nsb3RdPkh0dHA6Ly88L3RlbXBsYXRlPlxuICAgIDwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0MSA9IHJlZignJylcbmNvbnN0IGR5bmFtaWNTbG90ID0gcmVmKCdwcmVwZW5kJylcblxuZnVuY3Rpb24gdG9nZ2xlU2xvdCgpe1xuIGR5bmFtaWNTbG90LnZhbHVlID0gZHluYW1pY1Nsb3QudmFsdWUgPT09J3ByZXBlbmQnPydhcHBlbmQnOidwcmVwZW5kJztcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uaW5wdXQtd2l0aC1zZWxlY3QgLmVsLWlucHV0LWdyb3VwX19wcmVwZW5kIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtZmlsbC1jb2xvci1ibGFuayk7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Input has computed property for setting classes, and sets append/prepend class based on slots existence. The problem is that slots are not reactive like that and the class will not get recalculated when the slot is changed dynamically. 

### What is Expected?

Changing dynamic slot append/prepend should set the correct classes 

### What is actually happening?

Input preserves initial state and doesn't recalculate class

### Additional comments

_(empty)_

**Comment by btea** [comment]
Hello, I don't fully understand what you mean. Based on the example you provided, the style you wrote did not take effect because your selector did not match the element.

**Comment by krystian-wolarek** [comment]
I'm using dynamic slot names that toggles between `prepend/append`. Initial state as you can see is `prepend` and root element has class `el-input-group--prepend` that's fine.

Then when u click "toggle slot" then slot name is changed to `append`, slots work well but root element still have class `el-input-group--prepend` that "breaks styles" a little bit (input is rounded on right ).

Classes are set by this computed 
```
const containerKls = computed(() => [
  props.type === 'textarea' ? nsTextarea.b() : nsInput.b(),
  nsInput.m(inputSize.value),
  nsInput.is('disabled', inputDisabled.value),
  nsInput.is('exceed', inputExceed.value),
  {
    [nsInput.b('group')]: slots.prepend || slots.append,
    [nsInput.bm('group', 'append')]: slots.append,
    [nsInput.bm('group', 'prepend')]: slots.prepend,
    [nsInput.m('prefix')]: slots.prefix || props.prefixIcon,
    [nsInput.m('suffix')]:
      slots.suffix || props.suffixIcon || props.clearable || props.showPassword,
    [nsInput.bm('suffix', 'password-clear')]:
      showClear.value && showPwdVisible.value,
    [nsInput.b('hidden')]: props.type === 'hidden',
  },
  rawAttrs.class,
])
```
and problematic is that slots are not reactive so this will not trigger computed to recalculate 
```
 [nsInput.bm('group', 'append')]: slots.append,
 [nsInput.bm('group', 'prepend')]: slots.prepend,
```

**Comment by btea** [comment]
I see, this is a problem.
