### ISSUE TITLE
[Component] [message-box] 自动导入下ElMessageBox显示异常，必须import 'element-plus/dist/index.css'才正常显示

### ISSUE THREAD

**Issue by 360060316** [element-plus/element-plus#17146]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.5`
- Browser / OS: ` Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1 Edg/124.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs](https://element-plus.org/)

### Steps to reproduce

调试模式不能正常显示

### What is Expected?

正常显示

### What is actually happening?

界面显示异常

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
文档标注了这一点
https://staging.element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

**Comment by 360060316** [comment]
> 文档标注了这一点 https://staging.element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

我是自动导入啊为何还要手动指定

**Comment by warmthsea** [comment]
文档似乎有问题，我去看一下

**Comment by warmthsea** [comment]
我试了一下是没有问题的，可能是你又像下面手动导入了一次的原因

https://github.com/warmthsea/test-create-elp


```
import { ElMessageBox } from "element-plus";
```

**Comment by xionkq** [comment]
> 我试了一下是没有问题的，可能是你又像下面手动导入了一次的原因
> 
> https://github.com/warmthsea/test-create-elp/blob/main/src/App.vue
> 
> ```
> import { ElMessageBox } from "element-plus";
> ```

你说的没错，我也遇到了相同的问题。我使用了自动导入，但当我用 ElMessageBox 时我的 ide 提示我并未导入它，因此我手动导入了一次导致出现样式问题。当我删除 `import { ElMessageBox } from "element-plus";` 后，`AutoImport` 自动帮我导入了，问题解决。
