### ISSUE TITLE
[Component] [date-picker] DatePicker format动态修改无效

### ISSUE THREAD

**Issue by polikm5** [element-plus/element-plus#17149]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0`
- Element Plus Version: `2.7.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tZGF0ZXRpbWUtcGlja2VyXCI+XG4gICAgPGRpdiBjbGFzcz1cImJsb2NrXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5FbWl0cyBEYXRlIG9iamVjdDwvc3Bhbj5cbiAgICAgIDxkaXYgY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+VmFsdWU6IHt7IHZhbHVlMSB9fTwvZGl2PlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIERhdGVcIlxuICAgICAgICA6Zm9ybWF0PVwiZm9ybWF0MlwiXG4gICAgICAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VcIj5mb3JtYXTkv67mlLk8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYscmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcbmNvbnN0IHZhbHVlMyA9IHJlZignJylcbmNvbnN0IGZvcm1hdDIgPSByZWYoXCJZWVlZL01NL0REIEhIOm1tOnNzXCIpXG5jb25zdCBjaGFuZ2UgPSAoKSA9PiB7XG4gIGZvcm1hdDIudmFsdWUgPSBcIllZWVktTU0tRERcIlxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmRlbW8tZGF0ZXRpbWUtcGlja2VyIHtcbiAgZGlzcGxheTogZmxleDtcbiAgd2lkdGg6IDEwMCU7XG4gIHBhZGRpbmc6IDA7XG4gIGZsZXgtd3JhcDogd3JhcDtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuYmxvY2sge1xuICBwYWRkaW5nOiAzMHB4IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgYm9yZGVyLXJpZ2h0OiBzb2xpZCAxcHggdmFyKC0tZWwtYm9yZGVyLWNvbG9yKTtcbiAgZmxleDogMTtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuYmxvY2s6bGFzdC1jaGlsZCB7XG4gIGJvcmRlci1yaWdodDogbm9uZTtcbn1cbi5kZW1vLWRhdGV0aW1lLXBpY2tlciAuZGVtb25zdHJhdGlvbiB7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBjb2xvcjogdmFyKC0tZWwtdGV4dC1jb2xvci1zZWNvbmRhcnkpO1xuICBmb250LXNpemU6IDE0cHg7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

点击按钮之后 选择日期

### What is Expected?

点击按钮之后 选择日期根据格式展示日期
或者 修改change方法 根据return出来的值进行展示 

### What is actually happening?

点击按钮之后 选择日期依旧是之前的format格式

### Additional comments

_(empty)_

**Comment by dddssw** [comment]
maybe "format2.value = "YYYY/MM/DD"

**Comment by dddssw** [comment]
emm,我花了一些时间阅读源码,我发现可能是这个数据没有更新.
`provide('EP_PICKER_BASE', {
  props,
})  


const pickerBase = inject('EP_PICKER_BASE') as any
`
我更新format之后`EP_PICKER_BASE`没有变化,但是转化格式时需要它.如果这样就解释的通.但是按道理props改变了,应该会重新渲染才对.也许遗漏了什么.明天我会尝试再看一下

如果这确实是bug的话🐛,我建议暂时加上一个key,这样他就按照预期工作了. @polikm5
