### ISSUE TITLE
[Bug Report] What is the function of the outermost  <div></div> tag.

### ISSUE THREAD

**Issue by llk2yq** [element-plus/element-plus#1717]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
win10 / edge89

### Vue version
3.0.9

### Reproduction Link
https://github.com/element-plus/element-plus/blob/6cb474f46d3a10d42f88ed48e0f2d013682ba584/packages/card/src/index.vue

### Steps to reproduce
Go to file and see line 2.

### What is Expected?
No div tag

### What is actually happening?
have div tag

**Comment by CokeMine** [comment]
Yeah. I think that 'div' is not really needed.

**Comment by JeremyWuuuuu** [comment]
Yeah, exactly, you guys interested in making a PR?

**Comment by JeremyWuuuuu** [comment]
If you do, please reply below I will assign it to you, otherwise I will fix this myself.

**Comment by CokeMine** [comment]
@JeremyWuuuuu 
Let me make a PR and fix it. )
