### ISSUE TITLE
[Component] [popover] dropdown里的popover在关闭时出现闪屏的现象

### ISSUE THREAD

**Issue by typenoob** [element-plus/element-plus#17178]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.3`
- Browser / OS: `Chrome 125.0.6422.142/Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgPGVsLWJ1dHRvbj5cbiAgICAgIDxlbC1pY29uPlxuICAgICAgICA8RWxlbWVudFBsdXMgLz5cbiAgICAgIDwvZWwtaWNvbj5cbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIiA6dmlzaWJsZT1cInZpc2libGVcIj5cbiAgICAgICAgICAgICAgPHA+6L+Z5piv5LiA5q615YaF5a656L+Z5piv5LiA5q615YaF5a6556Gu5a6a5Yig6Zmk5ZCXPC9wPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPuWPlua2iDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gdHJ1ZVwiPuWIoOmZpDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgICAgPC9lbC1wb3BvdmVyPlxuICAgICAgICAgIDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 点击按钮
2. 点击下拉菜单中的"删除"选项
3. 点击popover中的"取消"按钮

### What is Expected?

popover组件被正常关闭

### What is actually happening?

popover组件会瞬移到左上角，然后再消失

### Additional comments

_(empty)_

**Comment by btea** [comment]
似乎是触发 `popover` 的元素在关闭前消失了，导致这种情况。可以给删除按钮的点击事件添加一个`stop`修饰符。[示例](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgPGVsLWJ1dHRvbj5cbiAgICAgIDxlbC1pY29uPlxuICAgICAgICA8RWxlbWVudFBsdXMgLz5cbiAgICAgIDwvZWwtaWNvbj5cbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIiA6dmlzaWJsZT1cInZpc2libGVcIj5cbiAgICAgICAgICAgICAgPHA+6L+Z5piv5LiA5q615YaF5a656L+Z5piv5LiA5q615YaF5a6556Gu5a6a5Yig6Zmk5ZCXPC9wPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPuWPlua2iDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2suc3RvcD1cInZpc2libGUgPSB0cnVlXCI+5Yig6ZmkPC9lbC1idXR0b24+XG4gICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by typenoob** [comment]
![image](https://github.com/element-plus/element-plus/assets/61347081/e683e0c9-6f75-4f4a-9ce9-43a261b25248)
是不是应该增加一个选项，让触发popover的元素不消失。否则一旦点击空白的地方，导致这个元素消失后，还会出现此现象。

**Comment by typenoob** [comment]
把hide-on-click设为false也可以
[示例](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgPGVsLWJ1dHRvbj5cbiAgICAgIDxlbC1pY29uPlxuICAgICAgICA8RWxlbWVudFBsdXMgLz5cbiAgICAgIDwvZWwtaWNvbj5cbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIiA6dmlzaWJsZT1cInZpc2libGVcIj5cbiAgICAgICAgICAgICAgPHA+6L+Z5piv5LiA5q615YaF5a656L+Z5piv5LiA5q615YaF5a6556Gu5a6a5Yig6Zmk5ZCXPC9wPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPuWPlua2iDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2suc3RvcD1cInZpc2libGUgPSB0cnVlXCI+5Yig6ZmkPC9lbC1idXR0b24+XG4gICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gdHJpZ2dlcj1cImNsaWNrXCIgOmhpZGUtb24tY2xpY2s9XCJmYWxzZVwiPlxuICAgIDxlbC1idXR0b24+XG4gICAgICA8ZWwtaWNvbj5cbiAgICAgICAgPEVsZW1lbnRQbHVzIC8+XG4gICAgICA8L2VsLWljb24+XG4gICAgPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLXBvcG92ZXIgdHJpZ2dlcj1cImNsaWNrXCIgOnZpc2libGU9XCJ2aXNpYmxlXCI+XG4gICAgICAgICAgICAgIDxwPui/meaYr+S4gOauteWGheWuuei/meaYr+S4gOauteWGheWuueehruWumuWIoOmZpOWQlzwvcD5cbiAgICAgICAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gZmFsc2VcIj7lj5bmtog8L2VsLWJ1dHRvbj5cbiAgICAgICAgICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZSA9IHRydWVcIj7liKDpmaQ8L2VsLWJ1dHRvbj5cbiAgICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDwvZWwtcG9wb3Zlcj5cbiAgICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by btea** [comment]
开发者使用场景难以界定，用户根据自己的场景具体处理比较好。
