### ISSUE TITLE
[Component] [drawer] el-drawer 设置 class不生效

### ISSUE THREAD

**Issue by QQ755816** [element-plus/element-plus#17180]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.5`
- Browser / OS: `Chrome 124.0.6367.119`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQSA9IHRydWVcIj4gQSBGYWlsdWU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQiA9IHRydWVcIj4gQiBGYWlsdWUgKGFwcGVuZC10by1ib2R5KSA8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQyA9IHRydWVcIj4gQyBTdWNjZXNzIDwvZWwtYnV0dG9uPlxuICA8ZWwtZHJhd2VyIGNsYXNzPVwiZHJhd2VyQVwiIHYtbW9kZWw9XCJ2aXNpYmxlQVwiIHNpemU9XCI1MCVcIiBkZXN0cm95LW9uLWNsb3NlPlxuICAgIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiMwMDBcIj5kcmF3ZXJBPC9kaXY+XG4gIDwvZWwtZHJhd2VyPlxuICA8ZGl2IGNsYXNzPVwiZHJhd2VyQlwiPlxuICAgIDxlbC1kcmF3ZXIgY2xhc3M9XCJkcmF3ZXJCXCIgdi1tb2RlbD1cInZpc2libGVCXCIgc2l6ZT1cIjUwJVwiIGFwcGVuZC10by1ib2R5IGRlc3Ryb3ktb24tY2xvc2U+XG4gICAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjojMDAwXCI+ZHJhd2VyQjwvZGl2PlxuICAgIDwvZWwtZHJhd2VyPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImRyYXdlckNcIj5cbiAgICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJ2aXNpYmxlQ1wiIHNpemU9XCI1MCVcIiBkZXN0cm95LW9uLWNsb3NlPlxuICAgICAgPGRpdiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IzAwMFwiPmRyYXdlckM8L2Rpdj5cbiAgICA8L2VsLWRyYXdlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxCdXR0b24sIEVsRHJhd2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgQ2lyY2xlQ2xvc2VGaWxsZWQgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmlzaWJsZUEgPSByZWYoZmFsc2UpXG5jb25zdCB2aXNpYmxlQiA9IHJlZihmYWxzZSlcbmNvbnN0IHZpc2libGVDID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmRyYXdlckE6ZGVlcCguZWwtZHJhd2VyX19oZWFkZXIpIHtcbiAgbWFyZ2luLWJvdHRvbTogMDtcbn1cbi5kcmF3ZXJCOmRlZXAoLmVsLWRyYXdlcl9faGVhZGVyKSB7XG4gIG1hcmdpbi1ib3R0b206IDA7XG59XG4uZHJhd2VyQzpkZWVwKC5lbC1kcmF3ZXJfX2hlYWRlcikge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

无

### What is Expected?

class在drawer上生效

### What is actually happening?

class只有在drawer外部且append-to-body=false才生效

### Additional comments

_(empty)_

**Comment by ggblcs** [comment]
你的样式穿透写的有问题吧，修改一下。[链接](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQSA9IHRydWVcIj4gQSBGYWlsdWU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQiA9IHRydWVcIj4gQiBGYWlsdWUgKGFwcGVuZC10by1ib2R5KSA8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlQyA9IHRydWVcIj4gQyBTdWNjZXNzIDwvZWwtYnV0dG9uPlxuICA8ZGl2PlxuICAgIDxlbC1kcmF3ZXIgY2xhc3M9XCJkcmF3ZXJBXCIgdi1tb2RlbD1cInZpc2libGVBXCIgc2l6ZT1cIjUwJVwiIGRlc3Ryb3ktb24tY2xvc2U+XG4gICAgPGRpdiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IzAwMFwiPmRyYXdlckE8L2Rpdj5cbiAgPC9lbC1kcmF3ZXI+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiZHJhd2VyQlwiPlxuICAgIDxlbC1kcmF3ZXIgY2xhc3M9XCJkcmF3ZXJCXCIgdi1tb2RlbD1cInZpc2libGVCXCIgc2l6ZT1cIjUwJVwiIGFwcGVuZC10by1ib2R5IGRlc3Ryb3ktb24tY2xvc2U+XG4gICAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjojMDAwXCI+ZHJhd2VyQjwvZGl2PlxuICAgIDwvZWwtZHJhd2VyPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImRyYXdlckNcIj5cbiAgICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJ2aXNpYmxlQ1wiIHNpemU9XCI1MCVcIiBkZXN0cm95LW9uLWNsb3NlPlxuICAgICAgPGRpdiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IzAwMFwiPmRyYXdlckM8L2Rpdj5cbiAgICA8L2VsLWRyYXdlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxCdXR0b24sIEVsRHJhd2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgQ2lyY2xlQ2xvc2VGaWxsZWQgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmlzaWJsZUEgPSByZWYoZmFsc2UpXG5jb25zdCB2aXNpYmxlQiA9IHJlZihmYWxzZSlcbmNvbnN0IHZpc2libGVDID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuZGl2OmRlZXAoLmRyYXdlckEgLmVsLWRyYXdlcl9faGVhZGVyICl7XG4gIG1hcmdpbi1ib3R0b206IDA7XG4gIGJhY2tncm91bmQtY29sb3I6IHllbGxvdztcbn1cbi5kcmF3ZXJCOmRlZXAoLmVsLWRyYXdlcl9faGVhZGVyKSB7XG4gIG1hcmdpbi1ib3R0b206IDA7XG59XG4uZHJhd2VyQzpkZWVwKC5lbC1kcmF3ZXJfX2hlYWRlcikge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by zuoanCo** [comment]
You can add a parent node or use ElementPlus common style variables.
![Snipaste_2024-10-17_16-08-51](https://github.com/user-attachments/assets/df6e71ad-497e-4922-b46b-f96911ffede4)
