### ISSUE TITLE
[Bug Report] When the el-date-picker component type is dateRange or dateTimeRange. The unlink-panels property is not valid

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#1718]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
 windows 10/Google Chrome 89.0.4389.82

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/smallsample/pen/VwPmVKB

### Steps to reproduce
1. Apply the el-date-picker component
2. Set type to daterange or datetimerange
3. Add the unlink-panels property

### What is Expected?
The two panels can switch the current month or year independently

### What is actually happening?
no response

**Comment by JeremyWuuuuu** [comment]
I think it is working, see the screen recording below:

https://user-images.githubusercontent.com/15975785/113115747-5618e880-923f-11eb-8dcf-aee7a862e980.mov

**Comment by SmallSample** [comment]
@JeremyWuuuuu Sorry, I misunderstood the role of the unlink-panels attribute

**Comment by VanishMax** [comment]
@JeremyWuuuuu Is there any possibility to show only one panel at the same time? This might be crucial for the mobile screens where the default 646px popper doesn't fit the window.

I believe that `unlink-panels` was a good name for such a feature, so writing here.

**Comment by sxzz** [comment]
@VanishMax Would you like make a new feature request?
