### ISSUE TITLE
[Component] [select] remote El-select with option value object does not show correctly No-Data element

### ISSUE THREAD

**Issue by DanyaShemet** [element-plus/element-plus#17209]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.5`
- Browser / OS: `Version 126.0.6478.56 (Official Build) (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgbXVsdGlwbGVcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICByZW1vdGVcbiAgICAgICAgcmVzZXJ2ZS1rZXl3b3JkXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGVudGVyIGEga2V5d29yZFwiXG4gICAgICAgIDpyZW1vdGUtbWV0aG9kPVwicmVtb3RlTWV0aG9kXCJcbiAgICAgICAgOmxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgICAgPlxuICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgICA6dmFsdWU9XCJpdGVtXCJcbiAgICAgICAgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBMaXN0SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xufVxuXG5jb25zdCBsaXN0ID0gcmVmPExpc3RJdGVtW10+KFtdKVxuY29uc3Qgb3B0aW9ucyA9IHJlZjxMaXN0SXRlbVtdPihbXSlcbmNvbnN0IHZhbHVlID0gcmVmPHN0cmluZ1tdPihbXSlcbmNvbnN0IGxvYWRpbmcgPSByZWYoZmFsc2UpXG5cbm9uTW91bnRlZChhc3luYyAoKSA9PiB7XG4gICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goJ2h0dHBzOi8vanNvbnBsYWNlaG9sZGVyLnR5cGljb2RlLmNvbS9wb3N0cycpXG4gICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKCkgIFxuICAgIFxuICBsaXN0LnZhbHVlID0ganNvbi5tYXAoKGl0ZW0pID0+IHtcbiAgICByZXR1cm4geyB2YWx1ZTogaXRlbS51c2VySWQsIGxhYmVsOiBpdGVtLmlkIH1cbiAgfSlcbn0pXG5cblxuY29uc3QgcmVtb3RlTWV0aG9kID0gYXN5bmMgKHF1ZXJ5OiBzdHJpbmcpID0+IHtcbiAgaWYgKHF1ZXJ5KSB7XG4gICAgbG9hZGluZy52YWx1ZSA9IHRydWVcblxuICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKGBodHRwczovL2pzb25wbGFjZWhvbGRlci50eXBpY29kZS5jb20vcG9zdHM/dXNlcklkPSR7cXVlcnl9YClcbiAgICBjb25zdCBqc29uID0gYXdhaXQgcmVzLmpzb24oKSAgXG5cbiAgICBvcHRpb25zLnZhbHVlPSBqc29uLm1hcCgoaXRlbSkgPT4gKHsgdmFsdWU6IGl0ZW0udXNlcklkLCBsYWJlbDogaXRlbS5pZCB9KSlcbiAgXG4gICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgXG4gIH0gZWxzZSB7XG4gICAgb3B0aW9ucy52YWx1ZSA9IFtdXG4gIH1cbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. Enter '1' in select search
2. Wait for result
3. Enter space in select search, should be '1 '
4. Wait for result
5. Enter 2 in select search, should be '1 2'
4. Observe result

### What is Expected?

NO DATA shows

### What is actually happening?

Rendered list items but without items

### Additional comments

Its occurs only when option value type = object and only when remote method has real request to the server with filtration logic. It is not reproducible via SetTimeout with custom filtering.

Looks like selectRef.states.otionsValue does not updates to empty array, and try to render empty list

Before update to the latest varsion on the project I used 2.4.0 version and this part worked fine

**Comment by mamayserg** [comment]
I have the same issue, it is really annoying, fix that please

**Comment by dddssw** [comment]
I spent a lot of time on this problem, but fortunately, I seem to have found the way to fix it.
