### ISSUE TITLE
[Feature Request] Auto generate code hint files from the docs

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#1721]
### Existing Component
no

### Component Name
-

### Description
Manual maintenance code hint files is more cumbersome than auto generate.

I found that the style of most docs is unified, auto generate code hint files from the docs will be a good choice.

I developed a plugIn([components-helper](https://github.com/tolking/components-helper)) to generate related code hint files(`tags.json` `attributes.json` `web-types.json`).

Now keep the style unanimously be able to auto generate code hint files.

example:

``` md
## components name

components description

...

### Attributes
| Attribute      | Description          | Type      | Accepted Values       | Default  |
...

### Breadcrumb Item Attributes (or Breadcrumb-Item or BreadcrumbItem)
| Attribute      | Description          | Type      | Accepted Values            | Default|
...

### Events
| Event Name | Description | ...
...

### Slots

| Name | Description | ...
...

### Directives (for loading and infiniteScroll)

| Name | Description | Type  | ...
...
```

I can do it.

**Comment by iamkun** [comment]
That looks cool. Feel free to make some test to check if this great tool works well with Element Plus.

**Comment by JeremyWuuuuu** [comment]
Great! I will assign this issue to you then.
