### ISSUE TITLE
[Component] [table] el-table组件 动态修改参数后报错 需要手动刷新页面 

### ISSUE THREAD

**Issue by shuihang** [element-plus/element-plus#17234]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.8`
- Element Plus Version: `2.7.1`
- Browser / OS: `Chrome /126.0.6478.62`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Link](暂无)

### Steps to reproduce

动态修改el-table-column的min-width参数，保存后浏览器控制台报错需要手动刷新网页

### What is Expected?

动态修改el-table-column的min-width参数，保存后浏览器正常热更新

### What is actually happening?

动态修改el-table-column的min-width参数，保存后浏览器控制台报错需要手动刷新网页

### Additional comments

_(empty)_

**Comment by btea** [comment]
这似乎不是组件的问题，是工具的问题。🤔
