### ISSUE TITLE
[Component] [button, progress] button设置color的异常处理文字颜色

### ISSUE THREAD

**Issue by wx-11** [element-plus/element-plus#17230]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superen Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-progress`

### Reproduction Link

[Link](https://codepen.io/iamkun/pen/YzWMaVr/)

### Steps to reproduce
 复现链接不知道怎么创建生成代码的链接给你们 你们的playground我也进不去 只好这样发了，不过好在问题简单 也不碍事：

 从复现链接进去 14行改成：` <el-button plain color="#ff7567" >{{ message }}</el-button> `发现鼠标放到按钮上 按钮会变成填充色 然后字体变成白色。但是去掉plain 默认的填充样式 字体会是黑色。

这个是 plain 鼠标放到按钮后的文字颜色 
![image](https://github.com/element-plus/element-plus/assets/168356742/19bacba5-e0fb-41a5-8351-5bf7791165fb)
这个是去掉plain默认的样式带个color 可以看到字体是黑色
![image](https://github.com/element-plus/element-plus/assets/168356742/ca8d1ac5-56c1-4ddb-899d-dbc5b04dea3b)

### What is Expected?

虽然可以自己改属性style等等让他正常，但是还是希望可以自动计算判断，修复默认样式里面的自动识别字体颜色

### What is actually happening?

color是自动计算的 在plain上体验正常 但是不加plain的字体效果不像是鼠标置于plain样式上那样。而且不是正常情况就如此 和[官方文档示例](https://element-plus.org/zh-CN/component/button.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)就不同。用官方这里一模一样的代码 字体还是黑色 试过dark那个是另一个功能了和这个没关系。

### Additional comments

另外问一下 我之所以留在2.7.1 是因为2.7.2当时版本的进度条 设置颜色color的时候会取消striped的条纹属性的滚动状态striped-flow 让条纹不再滚动。而2.7.1是正常的 设置color可以正常滚动条纹。当时没反馈，想看一下源码看看是不是bug 好像看到了当时github显示编译失败的，但是[272版本日志](https://github.com/element-plus/element-plus/issues/15834#issuecomment-2071271770)也没说处理过progress  不知道现在有没有修复，我是个新手 看不太懂 不太好发issue ，刚好借这个反馈color一起反馈一下，想知道你们有没有处理过这个问题？

**Comment by btea** [comment]
@wx-11  `progress` 的问题已尝试在 #17235 修复。
`button`的问题我有时间会看一下，你也可以尝试修复这个问题。

**Comment by btea** [comment]
没事，有问题可以在下方评论补充。

**Comment by ccs-song** [comment]
这不像一个bug，更像一个颜色的边界问题

代码里浅色系配黑色字体、深色系配白色字体也没问题

#ff7567 这是一个浅色系，但是配白色字体看着好像更舒服

所以到底是写死白色和黑色，还是根据用户给的颜色来动态设定字体颜色，需要取舍一下

[   const textColor = color.isDark()
          ? `var(${ns.cssVarName('color-white')})`
          : `var(${ns.cssVarName('color-black')})`](https://github.com/element-plus/element-plus/blob/ff936c76b56babae308383cc6909f20820dae961/packages/components/button/src/button-custom.ts#L60-L62)

**Comment by btea** [comment]
@wx-11 自定义颜色时，文本颜色是根据传入的颜色来判断自动适配的。
https://github.com/element-plus/element-plus/blob/c1fcf9e2b8d85bc82e74cd9cea4b31ebb5f98d30/packages/components/button/src/button-custom.ts#L60-L62
https://github.com/scttcper/tinycolor/blob/2927a9d2aa03e037486a79a295542a7848621691/src/index.ts#L103

**Comment by btea** [comment]
我暂时先关闭这个issue，有问题欢迎继续补充。
