### ISSUE TITLE
[Component] [time-picker] 支持通过点击空白处确认修改，但是没有正确处理 handleOpen()

### ISSUE THREAD

**Issue by wanganjun** [element-plus/element-plus#17237]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.5`
- Browser / OS: `Chrome 125.0.6422.176 (arm64) / macOS 13.6.1`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICBlbC1kYXRlLXBpY2tlcu+8iOWPr+S7peS/neaMgeW8ueeql+aJk+W8gO+8ie+8mlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgQGNoYW5nZT1cIm9uQ2hhbmdlMVwiXG4gICAgICByZWY9XCJpbnB1dDFcIlxuICAgIC8+XG4gIDwvZGl2PlxuXG4gIDxkaXY+XG4gICAgZWwtdGltZS1waWNrZXLvvIjkuI3og73kv53mjIHlvLnnqpfmiZPlvIDvvInvvJpcbiAgICA8ZWwtdGltZS1waWNrZXJcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgQGNoYW5nZT1cIm9uQ2hhbmdlMlwiXG4gICAgICByZWY9XCJpbnB1dDJcIlxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG5leHRUaWNrLCByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZigpXG5jb25zdCB2YWx1ZTIgPSByZWYoKVxuXG5jb25zdCBpbnB1dDEgPSByZWYoKVxuY29uc3QgaW5wdXQyID0gcmVmKClcblxuZnVuY3Rpb24gb25DaGFuZ2UxKHYpIHtcbiAgY29uc29sZS5sb2coJy0tLSBjaGFuZ2UgMTExMSAtLS0nLCB2KVxuICBpbnB1dDEudmFsdWUuaGFuZGxlT3BlbigpXG59XG5cbmZ1bmN0aW9uIG9uQ2hhbmdlMih2KSB7XG4gIGNvbnNvbGUubG9nKCctLS0gY2hhbmdlIDIyMjIgLS0tJywgdilcblxuICAvLyDkv67mlLnml7bpl7TlkI5cbiAgLy8g5aaC5p6c54K55Ye744CQT0vjgJHmjInpkq7noa7orqTvvIzliJnkuIvpnaLnmoTku6PnoIHlj6/ku6XmiZPlvIDpgInmi6nml7bpl7TlvLnnqpdcbiAgLy8g5aaC5p6c54K55Ye756m655m95aSE56Gu6K6k77yMICAgIOWImeS4i+mdoueahOS7o+eggeaXoOazleaJk+W8gOmAieaLqeaXtumXtOW8ueeql1xuICBpbnB1dDIudmFsdWUuaGFuZGxlT3BlbigpXG5cbiAgLy8g5ZyoIG5leHRUaWNrIOS5n+S4jeihjFxuICAvLyBuZXh0VGljaygoKSA9PiBpbnB1dC52YWx1ZS5oYW5kbGVPcGVuKCkpXG5cbiAgLy8g5Y+q5pyJIHNldFRpbWVvdXQg5Y+v5Lul77yM5L2G5piv5pe26Ze05LiN5aW95o6M5o6nXG4gIC8vIHNldFRpbWVvdXQoKCkgPT4gaW5wdXQudmFsdWUuaGFuZGxlT3BlbigpLCAzMDAwKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1. 打开 time-picker 弹窗
2. 修改时间
3. 点击空白处

### What is Expected?

弹窗保持打开状态，不要关闭

### What is actually happening?

弹窗关闭

### Additional comments

经过测试 el-date-picker 可以保持弹窗打开

**Comment by jany555555** [comment]
有视频吗？el-date-picker 也是关闭了，关闭了那个时间的

**Comment by wanganjun** [comment]
@jany555555 

业务是这样的：用户在 time-picker 选择一个时间后，如果不合符要求，就在 @change 事件里面调用 handleOpen()，用代码主动打开弹窗，让用户重新再选一个时间

经过测试：用户点击 time-picker 的弹窗的【OK】按钮，@change 事件里面调用 handleOpen() 是可以打开弹窗的。但是用户点击空白处，@change 事件里面调用 handleOpen() 没发打开弹窗

所以期望的行为是 time-picker 的 handleOpen() 能保持弹窗的打开状态，但是实际上不行

**Comment by Panzer-Jack** [comment]
我想我解决了这个问题，PR https://github.com/element-plus/element-plus/pull/17276

**Comment by btea** [comment]
@wanganjun 你可以尝试使用 `visible-change` 事件来处理。
