### ISSUE TITLE
[Component] [tag] el-tag组件再移除时没有动画

### ISSUE THREAD

**Issue by badboyweb** [element-plus/element-plus#17255]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tag`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImZsZXggZ2FwLTJcIj5cbiAgICA8ZWwtdGFnXG4gICAgICB2LWZvcj1cInRhZyBpbiBkeW5hbWljVGFnc1wiXG4gICAgICA6a2V5PVwidGFnXCJcbiAgICAgIGNsb3NhYmxlXG4gICAgICA6ZGlzYWJsZS10cmFuc2l0aW9ucz1cImZhbHNlXCJcbiAgICAgIEBjbG9zZT1cImhhbmRsZUNsb3NlKHRhZylcIlxuICAgID5cbiAgICAgIHt7IHRhZyB9fVxuICAgIDwvZWwtdGFnPlxuICAgIDxlbC1pbnB1dFxuICAgICAgdi1pZj1cImlucHV0VmlzaWJsZVwiXG4gICAgICByZWY9XCJJbnB1dFJlZlwiXG4gICAgICB2LW1vZGVsPVwiaW5wdXRWYWx1ZVwiXG4gICAgICBjbGFzcz1cInctMjBcIlxuICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgIEBrZXl1cC5lbnRlcj1cImhhbmRsZUlucHV0Q29uZmlybVwiXG4gICAgICBAYmx1cj1cImhhbmRsZUlucHV0Q29uZmlybVwiXG4gICAgLz5cbiAgICA8ZWwtYnV0dG9uIHYtZWxzZSBjbGFzcz1cImJ1dHRvbi1uZXctdGFnXCIgc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwic2hvd0lucHV0XCI+XG4gICAgICArIE5ldyBUYWdcbiAgICA8L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgbmV4dFRpY2ssIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsSW5wdXQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGlucHV0VmFsdWUgPSByZWYoJycpXG5jb25zdCBkeW5hbWljVGFncyA9IHJlZihbJ1RhZyAxJywgJ1RhZyAyJywgJ1RhZyAzJ10pXG5jb25zdCBpbnB1dFZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBJbnB1dFJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsSW5wdXQ+PigpXG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKHRhZzogc3RyaW5nKSA9PiB7XG4gIGR5bmFtaWNUYWdzLnZhbHVlLnNwbGljZShkeW5hbWljVGFncy52YWx1ZS5pbmRleE9mKHRhZyksIDEpXG59XG5cbmNvbnN0IHNob3dJbnB1dCA9ICgpID0+IHtcbiAgaW5wdXRWaXNpYmxlLnZhbHVlID0gdHJ1ZVxuICBuZXh0VGljaygoKSA9PiB7XG4gICAgSW5wdXRSZWYudmFsdWUhLmlucHV0IS5mb2N1cygpXG4gIH0pXG59XG5cbmNvbnN0IGhhbmRsZUlucHV0Q29uZmlybSA9ICgpID0+IHtcbiAgaWYgKGlucHV0VmFsdWUudmFsdWUpIHtcbiAgICBkeW5hbWljVGFncy52YWx1ZS5wdXNoKGlucHV0VmFsdWUudmFsdWUpXG4gIH1cbiAgaW5wdXRWaXNpYmxlLnZhbHVlID0gZmFsc2VcbiAgaW5wdXRWYWx1ZS52YWx1ZSA9ICcnXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点tag的关闭按钮移除tag

### What is Expected?

移除tag应该有动画

### What is actually happening?

移除tag应该无动画

### Additional comments

_(empty)_

**Comment by anjiazhuyouxing** [comment]
好像只有新增有动画，这个issue我想认领一下

**Comment by warmthsea** [comment]
> 好像只有新增有动画，这个issue我想认领一下该怎么弄啊

如果你想为 `el-tag` 添加关闭动画，你可以：
- 1、修改 `packages/comonents/tag` 下的内容，有必要时添加测试
- 2、提交 `PR` ，确保代码无冲突，填写正确的解释和标题（你可以直接参考 [被合入的 PR](https://github.com/element-plus/element-plus/pulls?q=is%3Apr+is%3Aclosed) ）
- 3、等待其它人 `review` 你的代码, 如果没有问题管理员会合入主分支
