### ISSUE TITLE
[Component] [table, table-column] 合计行summary-method获取不到循环列数据

### ISSUE THREAD

**Issue by BruceLuo2** [element-plus/element-plus#17251]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.5`
- Browser / OS: `谷歌最新`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Link]()

### Steps to reproduce

<el-table-column v-for="(month, index) in state.months" :key="index" :label="month" width="80" show-overflow-tooltip align="right">
            <template #default="{ row }">
              {{ row.actualMonthVAmount[index + 1].toFixed(2) }}
            </template>
          </el-table-column>

### What is Expected?

通过data.map((item) => Number(item[column.property]))在getSummaries获取正常的数组值

### What is actually happening?

实际获取不到, 数组内全是NaN

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/33817573/639d5c37-06ae-4512-a7ac-5d51a56833fd)

**Comment by warmthsea** [comment]
你想获取列的数据么？
