### ISSUE TITLE
[Component] [tooltip] el-tooltip default slot is a section with v-for will only render the first  of v-for loop

### ISSUE THREAD

**Issue by dddssw** [element-plus/element-plus#17254]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcD5cbiAgPHNwYW4gdi1mb3I9XCJpdGVtIGluIDRcIj57e2l0ZW19fTwvc3Bhbj5cbiAgPC9lbC10b29sdGlwPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

waiting the page show

### What is Expected?

It should show one to four

### What is actually happening?

only show first item

### Additional comments

<pre>
export const OnlyChild = defineComponent({
  name: NAME,
  setup(_, { slots, attrs }) {
    const forwardRefInjection = inject(FORWARD_REF_INJECTION_KEY)
    const forwardRefDirective = useForwardRefDirective(
      forwardRefInjection?.setForwardRef ?? NOOP
    )
    return () => {
      const defaultSlot = slots.default?.(attrs)
      if (!defaultSlot) return null

      if (defaultSlot.length > 1) {
        debugWarn(NAME, 'requires exact only one valid child.')
        return null
      }

      const firstLegitNode = findFirstLegitChild(defaultSlot)
      if (!firstLegitNode) {
        debugWarn(NAME, 'no valid child node found')
        return null
      }

      return withDirectives(cloneVNode(firstLegitNode!, attrs), [
        [forwardRefDirective],
      ])
    }
  },
})
</pre>
The firstLegitNode is error, will only return first item . Why use OnlyChild wrapper the slot, leads the el-tooltip render first one

**Comment by zc-write-code** [comment]
嘛,可以用div包裹然后再div里面再循环,,你不给个名字都是默认插槽肯定是不行的啊,是你自己的问题而不是组件的问题

**Comment by dddssw** [comment]
这里本来就是要默认插槽好吗

**Comment by ccs-song** [comment]
先不说为什么只渲染一个，如果渲染多个那Tooltip在什么元素上触发？Tooltip设置的定位基于那个元素做？等等~

组件这样做，我理解是对的。

**Comment by dddssw** [comment]
@btea Could you help to see this issue

**Comment by warmthsea** [comment]
[Vue SFC Play](https://play.vuejs.org/#eNp9UsFOwzAM/ZWQS0GCVRM7jW4SoEnAARAgccmlat2SkSZRkpZJVf8dJ13LBmw32+/ZfslzS6+1njQ10DlNbGa4dsSCq/WSSV5pZRxpiYGCdKQwqiIRUqMRulWV3tYnsU/8pOiKSSYzJa0jlS3JwvefRncghCLvyoj8JDpjMon7dbgIEweVFqkDzAhJ/KgQYWx1KklzUSizYJQjj3BJZowu29ZnXYeDkNI3BhEYJvHOQHpOnUU9BS8na6skPrX1bEYzZHMB5kk7jnoZnZOAeCxFuV8PoeZMDedDPfuA7POf+tpufI3RZwMWTAOMjphLTQmuh1evj7DBeAQrldcC2UfAF7BK1F5jT7upZY6yd3hB7X1whcvyza42DqQdHuWFemYX+IyiS/6jDj39R+7lZBb6mOzwFweHD9+KZ0z3LmI6nMQxv3PeDHbrpe9K4sH//himQ4b3IJQj8Yj2S7bu93N+mz/K+KP7mKZxz/647hvrRg1e)

[Elp Play](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnO1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcD5cbiAgICA8c3BhbiB2LWZvcj1cIml0ZW0gaW4gNFwiPnt7aXRlbX19PC9zcGFuPlxuICA8L2VsLXRvb2x0aXA+XG4gIFxuICA8Q29tcD5cbiAgICA8c3BhbiB2LWZvcj1cIml0ZW0gaW4gNlwiPnt7aXRlbX19PC9zcGFuPlxuICA8L0NvbXA+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL0NvbXAudnVlIjoiPHNjcmlwdCBzZXR1cD5cclxuaW1wb3J0IENvbXAxIGZyb20gJy4vQ29tcDEudnVlJztcclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPGRpdj5cclxuICAgIDxwPkNvbXA8L3A+XHJcbiAgICAgPENvbXAxPlxyXG4gICAgICA8c2xvdCB2LWlmPVwiJHNsb3RzLmRlZmF1bHRcIiAvPlxyXG4gICAgIDwvQ29tcDE+XHJcbiAgPC9kaXY+XHJcbjwvdGVtcGxhdGU+XHJcbiIsInNyYy9Db21wMS52dWUiOiI8c2NyaXB0IHNldHVwPjwvc2NyaXB0PlxyXG5cclxuPHRlbXBsYXRlPlxyXG4gIDxzbG90IC8+XHJcbjwvdGVtcGxhdGU+XHJcbiIsIl9vIjp7fX0=)


This does look like an error with `el-only-child`.

**Comment by dddssw** [comment]
<pre>
function findFirstLegitChild(node: VNode[] | undefined): VNode | null {
  if (!node) return null

  const children = node as VNode[]
  for (const child of children) {
    /**
     * when user uses h(Fragment, [text]) to render plain string,
     * this switch case just cannot handle, when the value is primitives
     * we should just return the wrapped string
     */
    if (isObject(child)) {
      switch (child.type) {
        case Comment:
          continue
        case Text:
        case 'svg':
          return wrapTextContent(child)
        case Fragment:
          return findFirstLegitChild(child.children as VNode[])
        default:
          return child
      }
    }
    return wrapTextContent(child)
  }
  return null
}
</pre>
There is a recursion here.processing the Fragment(v-for), will return the first of Fragment.Maybe this is what this component does.

**Comment by btea** [comment]
Thank you for your discussion and reply. As designed, the tooltip slot only accepts one root element by default.
