### ISSUE TITLE
[Bug Report] Due to #1640, table default slot's scoped.row is not reactive

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#1726]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
chrome

### Vue version
3.0.10

### Reproduction Link
https://codepen.io/vgbire/pen/jOVaOBP

### Steps to reproduce
Look at https://codepen.io/vgbire/pen/jOVaOBP,
f12 open the console terminal。you can see row is not reative.
because #1640,you cloneDeep the children。Proxy Object will copy to normal Object rather than a Proxy Object.
So reative date will not reactive.
only if default slot is component will display this bug

### What is Expected?
scoped row can reative when it pass on a component。

### What is actually happening?
scoped row can‘t’ reative when it pass on a component。

**Comment by JeremyWuuuuu** [comment]
cc @justwiner
