### ISSUE TITLE
[Component] [select] select multiple 会自动触发一次表单校验

### ISSUE THREAD

**Issue by flonny** [element-plus/element-plus#17279]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.5`
- Browser / OS: `chrome 125.0.6422.176`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cclxuICAgIDxlbC1mb3JtIHJlZj1cInJ1bGVGb3JtUmVmXCIgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4XCIgOm1vZGVsPVwicnVsZUZvcm1cIiA6cnVsZXM9XCJydWxlc1wiIGxhYmVsLXdpZHRoPVwiYXV0b1wiIHN0YXR1cy1pY29uPlxyXG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgbmFtZVwiIHByb3A9XCJuYW1lXCI+XHJcbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJydWxlRm9ybS5uYW1lXCIgLz5cclxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCIgcHJvcD1cInJlZ2lvblwiPlxyXG4gICAgICAgIDxlbC1zZWxlY3QgY2xlYXJhYmxlIG11bHRpcGxlIHYtbW9kZWw9XCJydWxlRm9ybS5yZWdpb25cIiBwbGFjZWhvbGRlcj1cIkFjdGl2aXR5IHpvbmVcIj5cclxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIG9uZVwiIHZhbHVlPVwic2hhbmdoYWlcIiAvPlxyXG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cclxuICAgICAgICA8L2VsLXNlbGVjdD5cclxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICA8L2VsLWZvcm0+XHJcbjwvdGVtcGxhdGU+XHJcblxyXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxyXG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xyXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSwgRm9ybVJ1bGVzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xyXG5pbnRlcmZhY2UgUnVsZUZvcm0ge1xyXG4gIG5hbWU6IHN0cmluZ1xyXG4gIHJlZ2lvbj86IHN0cmluZ1tdXHJcbn1cclxuXHJcbmNvbnN0IHJ1bGVGb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxyXG5jb25zdCBydWxlRm9ybSA9IHJlYWN0aXZlPFJ1bGVGb3JtPih7XHJcbiAgbmFtZTogJ0hlbGxvJyxcclxufSlcclxuXHJcbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmU8Rm9ybVJ1bGVzPFJ1bGVGb3JtPj4oe1xyXG4gIHJlZ2lvbjogW1xyXG4gICAge1xyXG4gICAgICByZXF1aXJlZDogdHJ1ZSxcclxuICAgICAgbWVzc2FnZTogJ1BsZWFzZSBzZWxlY3QgQWN0aXZpdHkgem9uZScsXHJcbiAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxyXG4gICAgfSxcclxuICBdLFxyXG5cclxufSlcclxuPC9zY3JpcHQ+XHJcblxyXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
    <el-form ref="ruleFormRef" style="max-width: 600px" :model="ruleForm" :rules="rules" label-width="auto" status-icon>
      <el-form-item label="Activity name" prop="name">
        <el-input v-model="ruleForm.name" />
      </el-form-item>
      <el-form-item label="Activity zone" prop="region">
        <el-select clearable multiple v-model="ruleForm.region" placeholder="Activity zone">
          <el-option label="Zone one" value="shanghai" />
          <el-option label="Zone two" value="beijing" />
        </el-select>
      </el-form-item>
    </el-form>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
interface RuleForm {
  name: string
  region?: string[]
}

const ruleFormRef = ref<FormInstance>()
const ruleForm = reactive<RuleForm>({
  name: 'Hello',
})

const rules = reactive<FormRules<RuleForm>>({
  region: [
    {
      required: true,
      message: 'Please select Activity zone',
      trigger: 'change',
    },
  ],

})
</script>
```

### What is Expected?

region 不设置初始值时，不触发校验

### What is actually happening?

region 会触发表单校验

### Additional comments

_(empty)_

**Comment by zhuchaoling** [comment]
加上默认值 就不报红了
[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cclxuICAgIDxlbC1mb3JtIHJlZj1cInJ1bGVGb3JtUmVmXCIgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4XCIgOm1vZGVsPVwicnVsZUZvcm1cIiA6cnVsZXM9XCJydWxlc1wiIGxhYmVsLXdpZHRoPVwiYXV0b1wiIHN0YXR1cy1pY29uPlxyXG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgbmFtZVwiIHByb3A9XCJuYW1lXCI+XHJcbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJydWxlRm9ybS5uYW1lXCIgLz5cclxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCIgcHJvcD1cInJlZ2lvblwiPlxyXG4gICAgICAgIDxlbC1zZWxlY3QgY2xlYXJhYmxlIG11bHRpcGxlIHYtbW9kZWw9XCJydWxlRm9ybS5yZWdpb25cIiBwbGFjZWhvbGRlcj1cIkFjdGl2aXR5IHpvbmVcIj5cclxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIG9uZVwiIHZhbHVlPVwic2hhbmdoYWlcIiAvPlxyXG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cclxuICAgICAgICA8L2VsLXNlbGVjdD5cclxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XHJcbiAgICA8L2VsLWZvcm0+XHJcbjwvdGVtcGxhdGU+XHJcblxyXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxyXG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXHJcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlLCBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnXHJcbmludGVyZmFjZSBSdWxlRm9ybSB7XHJcbiAgbmFtZTogc3RyaW5nXHJcbiAgcmVnaW9uPzogc3RyaW5nW11cclxufVxyXG5cclxuY29uc3QgcnVsZUZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpXHJcbmNvbnN0IHJ1bGVGb3JtID0gcmVhY3RpdmU8UnVsZUZvcm0+KHtcclxuICBuYW1lOiAnSGVsbG8nLFxyXG4gIHJlZ2lvbjogW11cclxufSlcclxuXHJcbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmU8Rm9ybVJ1bGVzPFJ1bGVGb3JtPj4oe1xyXG4gIHJlZ2lvbjogW1xyXG4gICAge1xyXG4gICAgICByZXF1aXJlZDogdHJ1ZSxcclxuICAgICAgbWVzc2FnZTogJ1BsZWFzZSBzZWxlY3QgQWN0aXZpdHkgem9uZScsXHJcbiAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxyXG4gICAgfSxcclxuICBdLFxyXG59KVxyXG5cclxuPC9zY3JpcHQ+XHJcblxyXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Comment by Panzer-Jack** [comment]
没有填写默认值  会自动转换成Array，在源码里加了一个标志位可以解决这个问题：
PR: https://github.com/element-plus/element-plus/pull/17284

**Comment by flonny** [comment]
PR:#17286
