### ISSUE TITLE
[Feature Request] Select onChange add second parameter of the current option instance

### ISSUE THREAD

**Issue by cn3lfs** [element-plus/element-plus#1728]
### Existing Component
Yes

### Component Name
el-select

### Description
Suppose I have a list of items. I use v-for make options in select. there are some situtation that i don't want to bind to an object, but i also want to get the entire item. 
```vue
<el-select
  v-model="state.form.processUnitCode"
  filterable
  remote
  :remote-method="querySearchSupplier"
  @change="handleSelectSupplierChange"
  @focus="querySearchSupplier('')"
>
  <el-option
    v-for="item in supplierOptions"
    :key="item.id"
    :label="item.code   '-'   item.name"
    :value="item.code"
    :item="item"
  ></el-option>
</el-select>
```
If we can emit both the value and the option instance, we can get the item by attrs. such option.$attrs.item
```js
this.emitChange(option.value, option);
```

**Comment by cn3lfs** [comment]
many times the backend want to me to pass both code and name, so i can not get an entire object, bind  value to object will not work.

**Comment by liushuiyuan001** [comment]
Just forEach you can get the attrs
