### ISSUE TITLE
[TypeScript] tsconfig 配置 Volar 支持 compilerOptions.types 及路径别名 compilerOptions.paths 后 vscode 路径感知变慢

### ISSUE THREAD

**Issue by AAABingBing** [element-plus/element-plus#17308]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.6`
- Browser / OS: `Edge 126.0.2592.68`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Link]()

### Steps to reproduce

配置 Volar 支持 compilerOptions.types 及路径别名 compilerOptions.paths 后 vscode 路径感知变慢

删除 compilerOptions.types "types": ["element-plus/global"] vscode 路径感知速度正常

### What is Expected?

/

### What is actually happening?

/

### Additional comments

添加 compilerOptions.types 后的 vscode 路径感知速度如下

![添加 compilerOptions.types 后的 vscode 路径感知速度](https://github.com/element-plus/element-plus/assets/53040248/2a9b8efc-90d2-4393-8f7f-d72efaee8729)

删除 compilerOptions.types 后的 vscode 路径感知速度如下

![PixPin_2024-06-24_15-54-01](https://github.com/element-plus/element-plus/assets/53040248/84c6fd36-2549-4f3f-81a5-091e9919f987)

**Comment by warmthsea** [comment]
Hi, @AAABingBing , this PR has made some improvements. You can install the latest version and try again.

https://github.com/element-plus/element-plus/pull/16111
