### ISSUE TITLE
[TypeScript] [All] 使用pnpm安装依赖时，全局组件会失去类型提示

### ISSUE THREAD

**Issue by coder-sunshine** [element-plus/element-plus#17304]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.30`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mac OS 14`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/coder-sunshine/test-element-plus)

### Steps to reproduce

使用pnpm安装依赖，全局组件没有类型提示，比如el-button 等

### What is Expected?

支持完整的类型提示

### What is actually happening?

没有类型提示，全部都是any

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
You can temporarily switch Volar to `2.0.19`.

![image](https://github.com/element-plus/element-plus/assets/45450994/9a7b7a58-0c0e-4cb6-a423-5340efed1a4c)

**Comment by coder-sunshine** [comment]
<img width="684" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/fbcb7c7c-9b7c-4d30-b82f-f4daf2f8db27">
还是不行，我发现我同事的windows都可以 我们mac都不可以

**Comment by wzc520pyfm** [comment]
<img width="1512" alt="image" src="https://github.com/element-plus/element-plus/assets/69044080/97260384-556e-4eec-9015-7b496332e3bc">
@coder-sunshine I used pnpm to run your demo and found type hints, my `Vue - Official` version is v2.0.6.

**Comment by coder-sunshine** [comment]
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/69044080/342397995-97260384-556e-4eec-9015-7b496332e3bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzc2MTAsIm5iZiI6MTcxOTI3NzMxMCwicGF0aCI6Ii82OTA0NDA4MC8zNDIzOTc5OTUtOTcyNjAzODQtNTU2ZS00ZWVjLTkwMTUtN2I0OTYzMzJlM2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDg0YWU0ODE0MWVkY2U2MTVhNmI4YjRmMTg2ZmE2MDVlNzM3MmM0MzEzMmEyN2I3NDc5MzY2YzRhMTEwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVHuNepLZLJVeJkxQFx6dao10kMvoo5TJG2Z26GATXs"> @coder-sunshine I used pnpm to run your demo and found type hints, my `Vue - Official` version is v2.0.6.

是的，我拿我同事的电脑测试了 windows没问题，mac有问题，我现在已经解决了，查阅了相关资料发现，好像是 pnpm 安装的依赖不会安装到顶层，我添加了 .npmrc文件，然后修改了 `Vue - Official` 插件版本就可以了，目前版本为 2.0.19 
<img width="1530" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/6f3ecaa1-7c4f-48af-a649-37671bb995c1">
<img width="1014" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/ef5b2067-ca84-4e8a-8740-da645097d8d5">

**Comment by coder-sunshine** [comment]
> > <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/74751605/342209470-fbcb7c7c-9b7c-4d30-b82f-f4daf2f8db27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDk2NDYsIm5iZiI6MTcxOTIwOTM0NiwicGF0aCI6Ii83NDc1MTYwNS8zNDIyMDk0NzAtZmJjYjdjN2MtOWI3Yy00ZDMwLWI4MmYtZjRkYWYyZjhkYjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGZhYjI2MzMzZDljZDQ0M2ViM2M1ZWZkY2JjZTgwMzAwZmExYTcyN2M2MDRkNmQ5YmU0MTZlMzExN2E2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RAoqBeWmBPnQabBDrHABHAR0ZUke8RHL-Xy1VskQLA"> 还是不行，我发现我同事的windows都可以 我们mac都不可以
> 
> 或者你使用自动导入的方式引入elp试试呢？

自动导入是可以的，但是自动导入会引发新的问题，就是 无法加载动态组件，类似这种 
<img width="1135" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/fa958b32-8ce7-4420-b4df-a3977a107366">
[可见这个issue](https://github.com/element-plus/element-plus/issues/8512)

**Comment by wzc520pyfm** [comment]
> > <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/69044080/342397995-97260384-556e-4eec-9015-7b496332e3bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzc2MTAsIm5iZiI6MTcxOTI3NzMxMCwicGF0aCI6Ii82OTA0NDA4MC8zNDIzOTc5OTUtOTcyNjAzODQtNTU2ZS00ZWVjLTkwMTUtN2I0OTYzMzJlM2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDg0YWU0ODE0MWVkY2U2MTVhNmI4YjRmMTg2ZmE2MDVlNzM3MmM0MzEzMmEyN2I3NDc5MzY2YzRhMTEwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVHuNepLZLJVeJkxQFx6dao10kMvoo5TJG2Z26GATXs"> @coder-sunshine I used pnpm to run your demo and found type hints, my `Vue - Official` version is v2.0.6.
> 
> 是的，我拿我同事的电脑测试了 windows没问题，mac有问题，我现在已经解决了，查阅了相关资料发现，好像是 pnpm 安装的依赖不会安装到顶层，我添加了 .npmrc文件，然后修改了 `Vue - Official` 插件版本就可以了，目前版本为 2.0.19 
> <img width="1530" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/6f3ecaa1-7c4f-48af-a649-37671bb995c1">
> <img width="1014" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/ef5b2067-ca84-4e8a-8740-da645097d8d5">
> 

但我也是使用mac(m3)，我是正常的。依照你的回答，或许是TS对pnpm的mac软链支持不够完善? 或许可以手动指定ts从何处读取elp的类型定义? 不建议将依赖提升至顶层，这会导致幽灵依赖问题。

**Comment by coder-sunshine** [comment]
> > > <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/69044080/342397995-97260384-556e-4eec-9015-7b496332e3bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzc2MTAsIm5iZiI6MTcxOTI3NzMxMCwicGF0aCI6Ii82OTA0NDA4MC8zNDIzOTc5OTUtOTcyNjAzODQtNTU2ZS00ZWVjLTkwMTUtN2I0OTYzMzJlM2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDg0YWU0ODE0MWVkY2U2MTVhNmI4YjRmMTg2ZmE2MDVlNzM3MmM0MzEzMmEyN2I3NDc5MzY2YzRhMTEwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVHuNepLZLJVeJkxQFx6dao10kMvoo5TJG2Z26GATXs"> @coder-sunshine I used pnpm to run your demo and found type hints, my `Vue - Official` version is v2.0.6.
> > 
> > 
> > 是的，我拿我同事的电脑测试了 windows没问题，mac有问题，我现在已经解决了，查阅了相关资料发现，好像是 pnpm 安装的依赖不会安装到顶层，我添加了 .npmrc文件，然后修改了 `Vue - Official` 插件版本就可以了，目前版本为 2.0.19
> > <img alt="image" width="1530" src="https://private-user-images.githubusercontent.com/74751605/342537512-6f3ecaa1-7c4f-48af-a649-37671bb995c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODA4MTAsIm5iZiI6MTcxOTI4MDUxMCwicGF0aCI6Ii83NDc1MTYwNS8zNDI1Mzc1MTItNmYzZWNhYTEtN2M0Zi00OGFmLWE2NDktMzc2NzFiYjk5NWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZWVmYWRlNjNmYzgwOTNiMGNhMjg0M2U5ZjdjMGUwYTg5OTBmM2VjOWI2OTY4Mjg4Yzg2YjM1YWExYTg1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQ2WZbWaowJnADsxT6zLbu-Cu3BI-QD_bAMM3FM2C68">
> > <img alt="image" width="1014" src="https://private-user-images.githubusercontent.com/74751605/342537713-ef5b2067-ca84-4e8a-8740-da645097d8d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODA4MTAsIm5iZiI6MTcxOTI4MDUxMCwicGF0aCI6Ii83NDc1MTYwNS8zNDI1Mzc3MTMtZWY1YjIwNjctY2E4NC00ZThhLTg3NDAtZGE2NDUwOTdkOGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGRmMTNkNWI1NjY0NGY3NmM2Mjk5NGJhMDM4MGM0YzAzZGI2OGNmNjQ5MjUyNTIwYmM0MDMwZDE4MDkwYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiawCjo_2ciKU8S-2EWkUhj4t1Ur-yHzMPFN0wdpl7o">
> 
> 但我也是使用mac(m3)，我是正常的。依照你的回答，或许是TS对pnpm的mac软链支持不够完善? 或许可以手动指定ts从何处读取elp的类型定义? 不建议将依赖提升至顶层，这会导致幽灵依赖问题。

<img width="717" alt="image" src="https://github.com/element-plus/element-plus/assets/74751605/265dd040-9903-4842-bdbb-a86ae0d09c58">

我觉得和  `Vue - Official`  插件版本也有问题，我测试了 antd-vue 库，发现配置好了过后，是正常的，但是更新  `Vue - Official`  插件版本就不提示了。

**Comment by Zyunchao** [comment]
和这个一样 https://github.com/vuejs/language-tools/issues/4503

**Comment by cx690** [comment]
vue-office好像已经不在支持以下方式定义全局组件
element-plus/global.d.ts
```ts
// GlobalComponents for Volar
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
 }
}
```

需要更改为
```ts
declare module 'vue' {
    export interface GlobalComponents {
 }
}
```
上面的方式应该是最早vue2的类型支持定义，现在应该采用下方推荐的方式，此举造成了大量的第三方ui库全局组件类型爆炸（其实官方在很早之前就在文档里面注明了vue2.7+以上的全局组件声明方式）

**Comment by warmthsea** [comment]
另外，可能与 `unplugin-vue-components` 版本有关（如果你使用了）

**Comment by andywang425** [comment]
我在windows下使用npm也遇到了这个问题（完整引入）

解决办法如楼上所说，第一种是降级`Vue - Official`拓展版本到`2.0.19`，第二种是打开`node_modules\element-plus\global.d.ts`，把`declare module '@vue/runtime-core'`改成`declare module 'vue'`

**Comment by cx690** [comment]
看源码已经修改了https://github.com/element-plus/element-plus/blob/dev/global.d.ts
坐等发版应该就可以了

**Comment by coder-sunshine** [comment]
> vue-office好像已经不在支持以下方式定义全局组件 element-plus/global.d.ts
> 
> ```ts
> // GlobalComponents for Volar
> declare module '@vue/runtime-core' {
>   export interface GlobalComponents {
>  }
> }
> ```
> 
> 需要更改为
> 
> ```ts
> declare module 'vue' {
>     export interface GlobalComponents {
>  }
> }
> ```
> 
> 上面的方式应该是最早vue2的类型支持定义，现在应该采用下方推荐的方式，此举造成了大量的第三方ui库全局组件类型爆炸（其实官方在很早之前就在文档里面注明了vue2.7+以上的全局组件声明方式）

是的 官方已经修改了，等官方发版就好了

**Comment by btea** [comment]
@coder-sunshine 新版已发布。

**Comment by coder-sunshine** [comment]
> @coder-sunshine 新版已发布。

收到，谢谢
