### ISSUE TITLE
[Component] [button] Button auto hover and active color not working when `color` obtained from css variable

### ISSUE THREAD

**Issue by AlexRainHao** [element-plus/element-plus#17315]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+VGVzdCBidXR0b24gY29sb3IgZnJvbSB2YXJpYWJsZTwvaDE+XG5cbiAgPGVsLWJ1dHRvbiBjb2xvcj1cInZhcigtLWN1c3RvbS1wcmltYXJ5LWNvbG9yKVwiPlRlc3QgQnV0dG9uPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG46cm9vdHtcbiAgICAtLWN1c3RvbS1wcmltYXJ5LWNvbG9yOiAjNGU0NGE0O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
</script>

<template>
  <h1>Test button color from variable</h1>

  <el-button color="var(--custom-primary-color)">Test Button</el-button>
</template>

<style>
:root{
    --custom-primary-color: #4e44a4;
}
</style>
```

### What is Expected?

Given sets of `css` color variables, The `el-button` color of hover or active could auto calculated

### What is actually happening?

It can not auto inference corresponding hover and active color.
The actual hover color is default set to rgb(77,77,77), active color is rgb(4,4,4)

### Additional comments

_(empty)_

**Comment by webvs2** [comment]
There are some code tradeoffs for this problem, such as: 
1 Is it necessary to write: 'var' in the case of using `css` variables? 
2 Raise variables to bring runtime burden, is it still retain the pure use of `color`, the color acquisition work is left to the developer
@btea  @AlexRainHao
