### ISSUE TITLE
[Component] [date-picker] el-date memory overflow

### ISSUE THREAD

**Issue by SLOE-debug** [element-plus/element-plus#17318]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.30`
- Element Plus Version: `2.7.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBzaG93ID0gcmVmKHRydWUpXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcyMDI0LTYtMjUnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJzaG93ID0gIXNob3dcIj5zaG93L2hpZGU8L2J1dHRvbj5cbiAgPEVsRGF0ZVBpY2tlciB2LW1vZGVsPVwidmFsdWVcIiB2LWlmPVwic2hvd1wiPlxuICA8L0VsRGF0ZVBpY2tlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Open the devtools memory panel, take a snapshot, click "show/hide", take a snapshot, and compare them. You can see a lot of Detached Text

### What is Expected?

Detached Text is released

### What is actually happening?

Detached Text is not released

### Additional comments

_(empty)_

**Comment by SLOE-debug** [comment]
![image](https://github.com/element-plus/element-plus/assets/63086927/01587146-ff1e-41c2-8b12-2ee899921daf)
The problem has been located. Cancel the use of unref and change it to: (!hasCurrent && cell?.text === 1 && cell.type === 'normal') ||

**Comment by SLOE-debug** [comment]
I really need this feature, hope it will be released soon

**Comment by zhuchaoling** [comment]
You can add a parent element to this component, and then use 'v-show' on the parent element.

**Comment by SLOE-debug** [comment]
@zhuchaoling I want to actually uninstall it, not hide it.

**Comment by SLOE-debug** [comment]
The problem has been located, please fix it as soon as possible

**Comment by warmthsea** [comment]
> The problem has been located, please fix it as soon as possible

Can you provide a screenshot of `Detached Text`?

**Comment by SLOE-debug** [comment]
![image](https://github.com/element-plus/element-plus/assets/63086927/3cbc5b2e-ac0c-49ea-911e-c87e8a41c12e)
@warmthsea

**Comment by SLOE-debug** [comment]
![image](https://github.com/element-plus/element-plus/assets/63086927/f951ccbe-f54d-4412-bb55-57b6f353d20e)
@warmthsea This is my local

**Comment by warmthsea** [comment]
> ![image](https://private-user-images.githubusercontent.com/63086927/342598989-01587146-ff1e-41c2-8b12-2ee899921daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDI3NDksIm5iZiI6MTcxOTkwMjQ0OSwicGF0aCI6Ii82MzA4NjkyNy8zNDI1OTg5ODktMDE1ODcxNDYtZmYxZS00MWMyLThiMTItMmVlODk5OTIxZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2NDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjljOGY1NzRmM2E4NWYzZDU0YWExODNkOTdkMWY0MmFiOWQyYjRjZTRmY2E3MDJhYzRiZWI4ZjcyODZjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._DnwXI-tUdyo_SBtqMjmq2oDsFrHwR75NZlTStO-QmQ) The problem has been located. Cancel the use of unref and change it to: (!hasCurrent && cell?.text === 1 && cell.type === 'normal') ||

It seems to be unrelated to the code here. I don't know how to solve this problem. I suggest you refer to:

https://github.com/vuejs/core/issues?q=is%3Aissue+Detached

**Comment by btea** [comment]
I tried the example you provided and it works fine when I run it locally.

![image](https://github.com/element-plus/element-plus/assets/24516654/cc05f824-86e8-4114-b2aa-0bc2a198a156)

**Comment by SLOE-debug** [comment]
@warmthsea https://github.com/vuejs/core/issues/11192
This is the memory leak issue I reported to Vue, and it has been fixed. Please try the fix I provided and compare the memory snapshots before and after the fix.

**Comment by SLOE-debug** [comment]
@btea As long as Detached appears, you should not assume it is working well! I guess this is due to the mixing of sfc/ts/tsx in the element-plus project. When using the changes I suggest, Detached will disappear.

**Comment by warmthsea** [comment]
80% of `Detached Text` comes from here.

https://github.com/element-plus/element-plus/blob/c03c03b49395483fc69593e5fcece0d32e725181/packages/components/date-picker/src/date-picker-com/basic-date-table.vue#L25C7-L42C12

**Comment by SLOE-debug** [comment]
@warmthsea 
![image](https://github.com/element-plus/element-plus/assets/63086927/d5a71858-282b-4319-8991-c7ae68e6242e)
Basically all the overflow comes from here

**Comment by warmthsea** [comment]
@SLOE-debug 

Not from here.

#### Before: count 195

![screenshots](https://github.com/element-plus/element-plus/assets/45450994/cce447d3-d07c-4f64-932f-e880c21a93c6)


#### Edit `unref`: count 191

![screenshots](https://github.com/element-plus/element-plus/assets/45450994/da4dbeec-2cba-4e0a-a9b6-2cb417e91882)

**Comment by SLOE-debug** [comment]
@warmthsea Please check if the vue version is 3.4.30 or above

**Comment by warmthsea** [comment]
> @warmthsea Please check if the vue version is 3.4.30 or above

The build version of `element-plus` is `3.2`, and it is not easy to upgrade to `3.4` at the moment.

**Comment by SLOE-debug** [comment]
@warmthsea https://github.com/vuejs/core/issues/11192 This link has fixed the memory overflow problem during development, so it is not ruled out that the Vue version is too old.

**Comment by SLOE-debug** [comment]
@warmthsea Please use the latest version of vue to fix this problem as soon as possible, thank you

**Comment by warmthsea** [comment]
> @warmthsea Please use the latest version of vue to fix this problem as soon as possible, thank you

I suggest you use other methods to solve this problem. Vue version cannot be upgraded in a short time.

**Comment by btea** [comment]
You just need to install the desired Vue version in the project, this should not be limited by this project.
