### ISSUE TITLE
[Style] [tree]  el-tree 拖拽时结点背景色变透明

### ISSUE THREAD

**Issue by sumingyu1769** [element-plus/element-plus#17325]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/edit/dev/docs/examples/tree/draggable.vue)

### Steps to reproduce

用户在拖拽树形控件时，拖拽结点

### What is Expected?

拖拽结点时，该结点所在的dom是拖拽前的样式（原来的样式）

### What is actually happening?

拖拽中，结点样式略微透明，拖拽鼠标位置在远离文字标题时，文字透明影响显示

### Additional comments

_(empty)_

**Comment by btea** [comment]
元素原生拖拽效果就是如此。

**Comment by sumingyu1769** [comment]
> 元素原生拖拽效果就是如此。
![1](https://github.com/element-plus/element-plus/assets/149745533/abdd9f56-781d-4de6-907b-1c74b7bf8b54)
我使用jquery的拖拽就可以不透明呀

**Comment by btea** [comment]
能提供一个在线示例吗？

**Comment by sumingyu1769** [comment]
> 能提供一个在线示例吗？
您好，请访问以下链接，链接具有时效性，请尽快查阅
http://t.csdnimg.cn/hRG43
