### ISSUE TITLE
[Bug Report] When the table component is complex enough, a large number of warnings are raised

### ISSUE THREAD

**Issue by LemonAppleMo** [element-plus/element-plus#1733]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Chrome 89.0.4389.90

### Vue version
3.0.10

### Reproduction Link
https://codepen.io/lemonapplemo/pen/qBRRKzr

### Steps to reproduce
Open browser console and visit this link (https://codepen.io/lemonapplemo/pen/qBRRKzr), there will be a lot of Vue warnings. This is due to use ref, remove ref attribute the warning will not appear.

### What is Expected?
No warning

### What is actually happening?
There are a lot of Vue warning

**Comment by LemonAppleMo** [comment]
Like this:
![image](https://user-images.githubusercontent.com/32638462/113236425-654b7500-92d7-11eb-8f3a-546840473537.png)

**Comment by LemonAppleMo** [comment]
Warning:

> [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

![image](https://user-images.githubusercontent.com/32638462/113236981-8fe9fd80-92d8-11eb-8845-6844b3ad89f5.png)

**Comment by qiaozhu** [comment]
同样遇到这个问题 回退到1.0.2-beta.35没有这个问题

**Comment by TothingWay** [comment]
This will cause the page to get stuck in production, but back to 1.0.2-beta.35 does not have this problem.

**Comment by Ryan2128** [comment]
> This will cause the page to get stuck in production, but back to 1.0.2-beta.35 does not have this problem. @JeremyWuuuuu

cc @justwiner

**Comment by LemonAppleMo** [comment]
I think it's caused by this.

https://github.com/element-plus/element-plus/blob/dev/packages/table/src/table-column/render-helper.ts#L131

**Comment by savannahp** [comment]
I am also seeing this issue as well!

**Comment by vincentSea** [comment]
I hope to solve it soon
