### ISSUE TITLE
[Component] [select] [Bug Report] ElSelectV2 Labels Change To Value as Labels in Remote Search after User Interaction/ Click

### ISSUE THREAD

**Issue by Hewsman** [element-plus/element-plus#17343]
### Element Plus version
2.7.6

### OS/Browsers version
Windows 10 / Google Chrome 

### Vue version
3.5.0-alpha.2

### Reproduction Link
https://codesandbox.io/p/sandbox/element-plus-spa-forked-4xl29z?file=%2Fsrc%2FApp.vue%3A98%2C1

If sandbox fails try element plus demo -> https://element-plus.org/en-US/component/select-v2.html#remote-search

### Steps to reproduce
Step 1: Use the remote search, type in character A - click any options you want
Step 2: Close the dropdown list (notice that the selected options are at first, labels
Step 3: Click the select element again (notice that the selected options change to value)

### What is Expected?
Only labels show in the component selected values

### What is actually happening?
Values are showing after user interaction during remote search - version 2.7.6 (2.7.5 is okay)
This issue extends to collapse-tags/collapse-tag-tooltip props

**Comment by Hewsman** [comment]
bump

**Comment by Hewsman** [comment]
bump

**Comment by warmthsea** [comment]
@Hewsman 

Can you provide a video or gif of the issue recurring ([in a playground](https://element-plus.run/))? I may need to change the [PR that fixes this issue](https://github.com/element-plus/element-plus/pull/17362), because it causes new problems.
