### ISSUE TITLE
[Component] [tabs, tab-pane] tab-pane 动态设置disabled为何不生效呢???

### ISSUE THREAD

**Issue by zc-write-code** [element-plus/element-plus#17340]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`
- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHNoYWxsb3dSZWYsIHdhdGNoRWZmZWN0LCB1bnJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBmaXJzdCBmcm9tICcuL2ZpcnN0LnZ1ZSdcbmltcG9ydCBzZWMgZnJvbSAnLi9zZWMudnVlJ1xuaW1wb3J0IHRoaXJkIGZyb20gJy4vdGhpcmQudnVlJ1xuaW1wb3J0IGZvdXJ0aCBmcm9tICcuL2ZvdXJ0aC52dWUnXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcbmNvbnN0IGhhbmRsZUluZGV4ID0gcmVmKDApXG5cbmNvbnN0IHRhYkxpc3QgPSBzaGFsbG93UmVmKFtcbiAge1xuICAgIG5hbWU6ICdmaXJzdCcsXG4gICAgbGFiZWw6ICfnrKzkuIDkuKonLFxuICAgIGNvbXBvbnRlbnRzOiBmaXJzdFxuICB9LHtcbiAgICBuYW1lOiAnc2Vjb25kJyxcbiAgICBsYWJlbDogJ+esrOS6jOS4qicsXG4gICAgY29tcG9udGVudHM6IHNlYyxcbiAgICBkaXNhYmxlZDogITBcbiAgfSx7XG4gICAgbmFtZTogJ3RoaXJkJyxcbiAgICBsYWJlbDogJ+esrOS4ieS4qicsXG4gICAgY29tcG9udGVudHM6IHRoaXJkLFxuICAgIGRpc2FibGVkOiAhMFxuICB9LHtcbiAgICBuYW1lOiAnZm91cnRoJyxcbiAgICBsYWJlbDogJ+esrOWbm+S4qicsXG4gICAgY29tcG9udGVudHM6IGZvdXJ0aCxcbiAgICBkaXNhYmxlZDogITBcbiAgfVxuXSlcblxuZnVuY3Rpb24gY2xpY2soaSkge1xuICBoYW5kbGVJbmRleC52YWx1ZSA9IGlcbn1cblxud2F0Y2hFZmZlY3QoKCkgPT4ge1xuICBjb25zdCB0YWIgPSB1bnJlZih0YWJMaXN0KVxuICB0YWJbMV0uZGlzYWJsZWQgPSBoYW5kbGVJbmRleC52YWx1ZSA8IDFcbiAgdGFiWzJdLmRpc2FibGVkID0gaGFuZGxlSW5kZXgudmFsdWUgPCAyXG4gIHRhYlszXS5kaXNhYmxlZCA9IGhhbmRsZUluZGV4LnZhbHVlICE9PSAzXG4gIGNvbnNvbGUubG9nKHRhYilcbn0pXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxFbFRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIj5cbiAgICA8RWxUYWJQYW5lIHYtZm9yPVwiXyBpbiB0YWJMaXN0XCIgOmxhYmVsPVwiXy5sYWJlbFwiIDpuYW1lPVwiXy5uYW1lXCIgOmRpc2FibGVkPVwiXy5kaXNhYmxlZFwiIDprZXk9XCJfLm5hbWVcIj5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiXy5jb21wb250ZW50c1wiIEBjbGljaz1cImNsaWNrXCI+PC9jb21wb25lbnQ+XG4gICAgPC9FbFRhYlBhbmU+XG4gIDwvRWxUYWJzPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9maXJzdC52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxyXG5pbXBvcnQgeyByZWYsIGRlZmluZUVtaXRzIH0gZnJvbSAndnVlJ1xyXG5jb25zdCBlbWl0cyA9IGRlZmluZUVtaXRzKFsnY2xpY2snXSlcclxuXHJcbmZ1bmN0aW9uIGNsaWNrKCl7XHJcbiAgZW1pdHMoJ2NsaWNrJywgMSlcclxufVxyXG48L3NjcmlwdD5cclxuPHRlbXBsYXRlPlxyXG4gIDxFbEJ1dHRvbiBAY2xpY2s9XCJjbGlja1wiPuesrOS4gOS4quaMiemSrjwvRWxCdXR0b24+XHJcbjwvdGVtcGxhdGU+Iiwic3JjL3NlYy52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxyXG5pbXBvcnQgeyByZWYsIGRlZmluZUVtaXRzIH0gZnJvbSAndnVlJ1xyXG5jb25zdCBlbWl0cyA9IGRlZmluZUVtaXRzKFsnY2xpY2snXSlcclxuXHJcbmZ1bmN0aW9uIGNsaWNrKCl7XHJcbiAgZW1pdHMoJ2NsaWNrJywgMilcclxufVxyXG48L3NjcmlwdD5cclxuPHRlbXBsYXRlPlxyXG4gIDxFbEJ1dHRvbiBAY2xpY2s9XCJjbGlja1wiPuesrOS6jOS4quaMiemSrjwvRWxCdXR0b24+XHJcbjwvdGVtcGxhdGU+Iiwic3JjL3RoaXJkLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XHJcbmltcG9ydCB7IHJlZiwgZGVmaW5lRW1pdHMgfSBmcm9tICd2dWUnXHJcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHMoWydjbGljayddKVxyXG5cclxuZnVuY3Rpb24gY2xpY2soKXtcclxuICBlbWl0cygnY2xpY2snLCAzKVxyXG59XHJcbjwvc2NyaXB0PlxyXG48dGVtcGxhdGU+XHJcbiAgPEVsQnV0dG9uIEBjbGljaz1cImNsaWNrXCI+56ys5LiJ5Liq5oyJ6ZKuPC9FbEJ1dHRvbj5cclxuPC90ZW1wbGF0ZT4iLCJzcmMvZm91cnRoLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XHJcbmltcG9ydCB7IHJlZiwgZGVmaW5lRW1pdHMgfSBmcm9tICd2dWUnXHJcbmNvbnN0IGVtaXRzID0gZGVmaW5lRW1pdHMoWydjbGljayddKVxyXG5cclxuZnVuY3Rpb24gY2xpY2soKXtcclxuICBlbWl0cygnY2xpY2snLCA0KVxyXG59XHJcbjwvc2NyaXB0PlxyXG48dGVtcGxhdGU+XHJcbiAgPEVsQnV0dG9uIEBjbGljaz1cImNsaWNrXCI+56ys5Zub5Liq5oyJ6ZKuPC9FbEJ1dHRvbj5cclxuPC90ZW1wbGF0ZT4iLCJfbyI6e319)

### Steps to reproduce

如链接中的实例, 点击第一个按钮触发了点击事件且监听中更改了tab的disabled,,控制台可查看,但是第二个还是不可点击..是shallowRef的影响还是啥呢???而且是禁用状态点击的时候还是会添加一个is-focus的class

### What is Expected?

触发了watchEffect且设置了第二个的disabled为false,第二个应该变为可以点击

### What is actually happening?

触发了watchEffect且设置了第二个的disabled为false,第二个还是不可点击

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://cn.vuejs.org/api/reactivity-advanced.html#shallowref
