### ISSUE TITLE
[bug report] label width bug of form component

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1734]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Microsoft Edge 版本 89.0.774.48 (官方内部版本) (64 位)

### Vue version
3.0.10

### Reproduction Link
https://codepen.io/sorrowx/pen/abppaNj

### Steps to reproduce
1. 打开 https://codepen.io/sorrowx/pen/abppaNj
2. 分别点击2个按钮，会有对应的bug,把2个bug写在一起了，方便查看

### What is Expected?
1. 正常显示

### What is actually happening?
2. 非正常显示

### bug原因及解决方案:
pr 地址 https://github.com/element-plus/element-plus/pull/1735
如果不行，再删除该pr,感谢查看

**Comment by kooriookami** [comment]
It has been fixed in next version, so close it.
