### ISSUE TITLE
[Component] [upload] el-upload 打包后 上传成功 100% 但是状态依然是 uploading

### ISSUE THREAD

**Issue by krmao** [element-plus/element-plus#17352]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome 126.0.6478.115/macos14.5`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

```
<el-upload
        ref="uploaderRef"
        v-model:file-list="additionalImages"
        :action="httpUrlUtil.resolveUrl(httpUrlUtil.baseUrl, '/system/fileUpload/uploadSaleAfterImage')"
        accept="image/png, image/jpg, image/jpeg"
        list-type="picture-card"
        method="post"
        name="file"
        :limit="9"
        :headers="{ Authorization: 'Bearer ' + loginUtil.getAccessToken() }"
        :multiple="true"
        :auto-upload="true"
        :on-remove="handleOnRemove"
        :on-preview="handleOnPreview"
        :on-exceed="handleOnExceed"
        :on-error="handleOnError"
        :on-progress="handleOnProgress"
        :on-success="handleOnSuccess"
        :before-upload="handleBeforeUpload"
        class="upload-images-container"
      >
        <div class="image-add" data-html2canvas-ignore="true">
          <IconPlusBlue class="mb-[3px]" />
          <div>{{ $t("station.uploadPicture") }}</div>
          <div>{{ additionalImages.length }}/9</div>
        </div>
        <template #file="{ file }">
          <el-image
            v-if="
              file?.status === 'success' ||
              file?.percentage == 100 ||
              valueUtil.isValid(file?.response?.data?.permanentObjectURL)
            "
            fit="cover"
            class="el-upload-list__item-thumbnail"
            :src="file?.url || file?.response?.data?.permanentObjectURL"
            alt=""
            style="width: 100%; height: 100%; object-fit: cover"
          />
          <div
            class="upload-uploading-container"
            v-if="
              file?.status === 'uploading' &&
              file?.percentage != 100 &&
              !valueUtil.isValid(file?.response?.data?.permanentObjectURL)
            "
          >
            <div>{{ $t("station.uploading") + file?.status }}</div>
            <span> <span :style="{ width: (file?.percentage || 0) + '%' }" /></span>
          </div>
          <div class="upload-failure-container" v-if="file?.status === 'fail'">
            <IconImageFailure />
            <div>{{ file?.name }}</div>
          </div>
          <span class="el-upload-list__item-actions">
            <span class="el-upload-list__item-preview" @click="handleOnPreview(file)">
              <IconImageViewerTransparent class="w-[20px] h-[20px]" style="cursor: pointer; user-select: none" />
            </span>
            <span class="el-upload-list__item-delete" @click="handleOnRemoveFile(file)">
              <IconImageDelete class="w-[20px] h-[20px]" style="cursor: pointer; user-select: none" />
            </span>
          </span>
          <span>{{ file?.status }}</span>
        </template>
      </el-upload>
```

```
const handleOnSuccess: UploadProps["onSuccess"] = (response: any, uploadFile: UploadFile, uploadFiles: UploadFiles) => {
  console.log("handleOnSuccess", response, uploadFile, uploadFiles, additionalImages.value);
};
```

### What is Expected?

当 percentage 100%时 状态应该是 success

### What is actually happening?

uploading

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/7344437/186ad9bf-8b61-4005-a8ed-1ccfbe7db3f8)

**开发模式是正常的**，打包后生产环境才会出问题

**Comment by xl495** [comment]
有解决方法了吗? 我这边是多选才会出问题 @krmao

**Comment by krmao** [comment]
这是这个组件的bug, 机器人直接关了我这个bug, 为了详细的更多的信息，太麻烦了。

解决方案是:
同时判断 percent 已经 response 里面的url是否存在，三个条件有一个满足就算上传成功

**Comment by xl495** [comment]
好的 谢谢 @krmao
