### ISSUE TITLE
[Component] [select] I want to prevent the dropdown from opening when the Enter key is triggered in a select element. How should I accomplish this?

### ISSUE THREAD

**Issue by 80sky** [element-plus/element-plus#17367]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.5.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBzZWxlY3RlZCA9IHJlZignJylcbmNvbnN0IHNlbGVjdFJlZiA9IHJlZigpO1xuY29uc3Qgb25LZXlEb3duRW50ZXIgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKHNlbGVjdFJlZi52YWx1ZSk7XG5cbiAgLy9XaGVuIEkgcHJlc3MgdGhlIGVudGVyIGtleSwgSSB3YW50IHRvIHByZXZlbnQgdGhlIGRyb3Bkb3duIG1lbnUgZnJvbSBwb3BwaW5nIHVwXG59XG5cblxuY29uc3Qgb25TZWFyY2ggPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzZWFyY2gnKTtcbn1cblxuXG5jb25zdCBvbkNoYW5nZSA9ICh2YWx1ZSkgPT4ge1xuICBjb25zb2xlLmxvZyh2YWx1ZSk7XG4gIHNlbGVjdFJlZi52YWx1ZS5ibHVyKCk7XG5cbiAgLy8gRXZlbiB0aG91Z2ggSSBjYWxsZWQgdGhlIGJsdXIgbWV0aG9kIHRvIGxvc2UgZm9jdXMgZHVyaW5nIHRoZSBjaGFuZ2UgZXZlbnQsIHRoZSBkcm9wZG93biBzdGlsbCBhcHBlYXJzIHdoZW4gSSBoaXQgdGhlIGVudGVyIGtleSBhZ2Fpbi5cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+e3ttc2d9fVxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdGVkXCIgcmVmPVwic2VsZWN0UmVmXCIgQGtleWRvd24uZW50ZXIucHJldmVudD1cIm9uS2V5RG93bkVudGVyXCIgQGtleXVwLmVudGVyPVwib25TZWFyY2hcIiBAY2hhbmdlPVwib25DaGFuZ2VcIj5cbiAgICAgIDxlbC1vcHRpb24gdmFsdWU9XCIxXCIgIGxhYmVsPVwidGVzdDFcIiAvPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjJcIiAgbGFiZWw9XCJ0ZXN0MlwiIC8+XG4gICAgICA8ZWwtb3B0aW9uIHZhbHVlPVwiM1wiICBsYWJlbD1cInRlc3QzXCIgLz5cbiAgICAgIDxlbC1vcHRpb24gdmFsdWU9XCI0XCIgIGxhYmVsPVwidGVzdDRcIiAvPlxuICAgICAgPGVsLW9wdGlvbiB2YWx1ZT1cIjVcIiAgbGFiZWw9XCJ0ZXN0NVwiIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce
1. First, click to focus, then use the keyboard to select a value and press Enter; the @change event triggers when the input loses focus.
2. Click and press the Enter key again.

### What is Expected?

prevent the dropdown from opening 

### What is actually happening?

opening

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/22342011/6ed5ca65-c341-440a-bd8a-5b38153cd0d2)

**Comment by btea** [comment]
This is the normal effect logic. 

According to your description, do you want to disable the dropdown list after selecting a value?

**Comment by 80sky** [comment]
> This is the normal effect logic.
> 
> According to your description, do you want to disable the dropdown list after selecting a value?

**Comment by 80sky** [comment]
Despite needing to execute a search when the enter key is pressed, I don't want the enter key to inadvertently cause the dropdown menu to appear.

**Comment by 80sky** [comment]
If there exists a selected value in the select element, I do not want the dropdown to appear when I press the enter key.

**Comment by 80sky** [comment]
> This is the normal effect logic.
> 
> According to your description, do you want to disable the dropdown list after selecting a value?

yes,If there exists a selected value in the select element, I do not want the dropdown to appear when I press the enter key.but I can't prevent it.

**Comment by 80sky** [comment]
I need to bind the 'keyup.enter' event to trigger the search function, and while executing the search, I do not want the select dropdown menu to reappear.

**Comment by btea** [comment]
Maybe you can disable select after selecting a value. `:disabled="!!selected"`

**Comment by makedopamine** [comment]
> Maybe you can disable select after selecting a value. `:disabled="!!selected"`

IMHO,  `<el-select>` should be able to prevent the default action of the `keydown.enter` event, like a native `<select>` element.🤔

**Comment by btea** [comment]
It is not reasonable to completely block it, and keyboard shortcuts should be supported. Perhaps a property can be added to determine whether keyboard operations are supported.

**Comment by tolking** [comment]
Opening a dropdown with the Enter key is a behavior consistent with [A11y](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/). If you want to avoid this behavior, it is recommended that you implement a component yourself.

When the dropdown is closed, the focus will move from within the dropdown to the input. You should execute the `selectRef.value.blur()` in NextTick (or setTimeout). Additionally, due to issues caused by #15450, it cannot function properly after 2.5.0

**Comment by yzwdzkn** [comment]
> It is not reasonable to completely block it, and keyboard shortcuts should be supported. Perhaps a property can be added to determine whether keyboard operations are supported.

I think this is a good idea, when can this function be implemented?
