### ISSUE TITLE
[Style] [dropdown] dropdown默认选中会有黑框

### ISSUE THREAD

**Issue by ouyang108** [element-plus/element-plus#17388]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgaGFuZGxlQ29tbWFuZCA9IChjb21tYW5kOiBzdHJpbmcgfCBudW1iZXIgfCBvYmplY3QpID0+IHtcbiAgRWxNZXNzYWdlKGBjbGljayBvbiBpdGVtICR7Y29tbWFuZH1gKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtZHJvcGRvd24gQGNvbW1hbmQ9XCJoYW5kbGVDb21tYW5kXCIgPlxuICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgRHJvcGRvd24gTGlzdDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tcmlnaHRcIj48YXJyb3ctZG93biAvPjwvZWwtaWNvbj5cbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiYVwiPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiYlwiPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY1wiPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiZFwiIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiZVwiIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG48c3R5bGVsIHNjb3BlZD5cbi5leGFtcGxlLXNob3djYXNlIC5lbC1kcm9wZG93bi1saW5rIHtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBjb2xvcjogdmFyKC0tZWwtY29sb3ItcHJpbWFyeSk7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG48L3N0eWxlbD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

鼠标移动到内容

### What is Expected?

无黑色边框

### What is actually happening?

有黑色边框

### Additional comments

只有hover会出现该现象

**Comment by warmthsea** [comment]
我觉得这是合理行为, 如果你不想要，你可以这样设置
```
:focus-visible {
  outline: none;
}
```

**Comment by zhuchaoling** [comment]
应该是浏览器的默认样式
![image](https://github.com/element-plus/element-plus/assets/126888254/46aa6ea0-ab3f-4fd8-a7da-dfea3e9c025b)
