### ISSUE TITLE
[Component] [date-picker] [Component][date-picker] 手动编辑日期，会导致绑定值异常

### ISSUE THREAD

**Issue by Xia-Qi** [element-plus/element-plus#17383]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome/126.0.0.0`
- Build Tool: `Other`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/date-picker.html#default-time-for-start-date-and-end-date)

### Steps to reproduce

第一步：打开 https://element-plus.org/en-US/component/date-picker.html#default-time-for-start-date-and-end-date ，开始时间选择 2024-07-01，结束时间选择 2024-07-02，页面显示 Component value：[ "2024-06-30T16:00:00.000Z", "2024-07-02T15:59:59.000Z" ]
第二步：结束时间手动输入为 2024-07-02，页面显示 Component value：[ "2024-06-30T16:00:00.000Z", "2024-07-01T16:00:00.000Z" ]

### What is Expected?

两次时间选择后的组件绑定值应该一样

### What is actually happening?

实际两次选择后，结束时间分别为：2024-07-02T15:59:59.000Z 和 2024-07-01T16:00:00.000Z，明显不一致，且差异较大

### Additional comments

_(empty)_

第一次编辑日期：
![image](https://github.com/element-plus/element-plus/assets/43026886/09d3eb9f-02f1-4f4b-b4e5-425cfd72fb2f)
第二次编辑日期：
![image](https://github.com/element-plus/element-plus/assets/43026886/a69abfc0-4437-4f59-8644-60e185289e7c)

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/discussions/17378
