### ISSUE TITLE
[Style] unocss的样式无法直接应用到组件上的问题，几乎所有组件都不行

### ISSUE THREAD

**Issue by ying-tch** [element-plus/element-plus#17392]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-select`
- `el-input`
- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnMSA9IHJlZignc2VsZWN0IOW6lOeUqHVub2Nzc+eahOagt+W8j+S4jeS8mueUn+aViCcpXG5jb25zdCBtc2cyID0gcmVmKCdpbnB1dCDlupTnlKh1bm9jc3PnmoTmoLflvI/kuI3kvJrnlJ/mlYgnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPiDnu4Tku7blupTnlKh1bm9jc3PnmoTmoLflvI/kuI3kvJrnlJ/mlYggPC9oMT5cbiAgPGVsLXNlbGVjdCBjbGFzcz1cInctMjAwXCIgdi1tb2RlbD1cIm1zZzFcIj5cbiAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gW3tcbiAgICAgICAgbGFiZWw6J3NlbGVjdCDlupTnlKh1bm9jc3PnmoTmoLflvI/kuI3kvJrnlJ/mlYgnLFxuICAgICAgICB2YWx1ZTonc2VsZWN0IOW6lOeUqHVub2Nzc+eahOagt+W8j+S4jeS8mueUn+aViCcsXG4gICAgICAgIH1dXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPGJyIC8+XG4gIDxiciAvPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZzJcIiBjbGFzcz1cInctMjAwXCIgLz5cbiAgPGJyIC8+XG4gIDxiciAvPlxuICA8ZWwtYnV0dG9uIGNsYXNzPVwidy0xMjAgaC04MFwiIHR5cGU9XCJwcmltYXJ5XCI+5oyJ6ZKuIHVub2Nzc+eahOmrmOW6puagt+W8j+S5n+S4jeeUn+aViDwvZWwtYnV0dG9uPlxuXG4gIDxwIGNsYXNzPVwibXQtNVwiPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

可以查看playground地址，w-200 在el-input中和el-select中都不生效，el-button只生效了w-120，但是h-80就会被覆盖掉

### What is Expected?

跟其它UI框架（ant,arco,navie）一样，unocss效果可直接作用于组件上

### What is actually happening?

unocss效果无法作用于组件上

### Additional comments

为啥select不能提供一个options的属性，非要再写一个el-option的，然后又在里面写循环

![1719980031852](https://github.com/element-plus/element-plus/assets/31296940/d7bcff05-5995-4995-92e3-bc1b54b99488)

**Comment by lanrenbulan** [comment]
```
// 可以这样来提高优先级，一劳永逸
presetUno({
  // `#app`是指main.js里的app.mount('#app')
  important: '#app',
}),
```

我碰到这个问题的背景:
- vite + autoimport，按需加载
- 顶级路由的component用的import或() => import()。不能用import

```
import Layout from '~/layout/index.vue'

{
   name: 'main',
    path: '/',
    redirect: '/home',
    component: Layout,
    //component: import('~/layout/index.vue'),
    //component: () => import('~/layout/index.vue'),
    children: routes,
}

```

**Comment by ying-tch** [comment]
> ```
> // 可以这样来提高优先级，一劳永逸
> presetUno({
>   // `#app`是指main.js里的app.mount('#app')
>   important: '#app',
> }),
> ```
> 
> 我设想的议题背景：
> 
> * vite + autoimport，按需加载
> * 顶级路由的组件用的import或() => import()。不能用import
> 
> ```
> import Layout from '~/layout/index.vue'
> 
> {
>    name: 'main',
>     path: '/',
>     redirect: '/home',
>     component: Layout,
>     //component: import('~/layout/index.vue'),
>     //component: () => import('~/layout/index.vue'),
>     children: routes,
> }
> ```



> ```
> // 可以这样来提高优先级，一劳永逸
> presetUno({
>   // `#app`是指main.js里的app.mount('#app')
>   important: '#app',
> }),
> ```
> 
> 我设想的议题摘要：
> 
> * vite + autoimport，按需加载
> * 顶级路由的组件用的import或() => import()。不能用import
> 
> ```
> import Layout from '~/layout/index.vue'
> 
> {
>    name: 'main',
>     path: '/',
>     redirect: '/home',
>     component: Layout,
>     //component: import('~/layout/index.vue'),
>     //component: () => import('~/layout/index.vue'),
>     children: routes,
> }
> ```

非常感谢，您帮到我大忙了

**Comment by ying-tch** [comment]
> ```
> // 可以这样来提高优先级，一劳永逸
> presetUno({
>   // `#app`是指main.js里的app.mount('#app')
>   important: '#app',
> }),
> ```
> 
> 我设想的议题摘要：
> 
> * vite + autoimport，按需加载
> * 顶级路由的组件用的import或() => import()。不能用import
> 
> ```
> import Layout from '~/layout/index.vue'
> 
> {
>    name: 'main',
>     path: '/',
>     redirect: '/home',
>     component: Layout,
>     //component: import('~/layout/index.vue'),
>     //component: () => import('~/layout/index.vue'),
>     children: routes,
> }
> ```

非常感谢，您帮到我大忙了

**Comment by btea** [comment]
感谢 @lanrenbulan 的回复。
我看了一下，样式是有的，没生效只是因为被组件默认样式覆盖了。组件内部样式是使用scss写的，并没有用到 unocss。这个只能自己通过提高样式的优先级来进行覆盖。

> 为啥select不能提供一个options的属性，非要再写一个el-option的，然后又在里面写循环

历史原因吧，从vue2开始组件就是这样的设计，为了不造成 breaking change 保持写法一致，尽量不给迁移用户造成麻烦就沿用了这个写法。

看来问题已经解决了，我就先关闭这个issue了。如果还有其他问题，欢迎评论补充。@ying-tch
