### ISSUE TITLE
[Component] [tooltip] 使用提供的动画类名，el-tooltip无法正常工作

### ISSUE THREAD

**Issue by lcyhyl** [element-plus/element-plus#17391]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.30`
- Element Plus Version: `2.7.5`
- Browser / OS: `最新版谷歌`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8ZWwtdG9vbHRpcCB0cmFuc2l0aW9uPVwiZWwtem9vbS1pbi10b3BcIj5cbiAgICDmtYvor5XliqjnlLtcbiAgICAgICA8dGVtcGxhdGUgI2NvbnRlbnQ+XG5cbiAgICAgICAgPHVsPlxuICAgICAgICAgIDxsaSB2LWZvcj1cIml0ZW0gaW4gMjBcIiA6a2V5PVwiaXRlbVwiPnt7aXRlbX19IGl0ZW0gaXRlbTwvbGk+XG4gICAgICAgIDwvdWw+XG4gICAgICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10b29sdGlwPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

给el-tooltip 添加 transition= "el-zoom-in-top" 

### What is Expected?

动画效果应该与el-select 一直

### What is actually happening?

实际动画并没有改变默认动画

### Additional comments

_(empty)_

**Comment by btea** [comment]
You should add animations matching this name yourself. [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8ZWwtdG9vbHRpcCB0cmFuc2l0aW9uPVwiYm91bmNlXCI+XG4gICAg5rWL6K+V5Yqo55S7XG4gICAgICAgPHRlbXBsYXRlICNjb250ZW50PlxuXG4gICAgICAgIDx1bD5cbiAgICAgICAgICA8bGkgdi1mb3I9XCJpdGVtIGluIDIwXCIgOmtleT1cIml0ZW1cIj57e2l0ZW19fSBpdGVtIGl0ZW08L2xpPlxuICAgICAgICA8L3VsPlxuICAgICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdG9vbHRpcD5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmJvdW5jZS1lbnRlci1hY3RpdmUge1xuICBhbmltYXRpb246IGJvdW5jZS1pbiAwLjVzO1xufVxuLmJvdW5jZS1sZWF2ZS1hY3RpdmUge1xuICBhbmltYXRpb246IGJvdW5jZS1pbiAwLjVzIHJldmVyc2U7XG59XG5Aa2V5ZnJhbWVzIGJvdW5jZS1pbiB7XG4gIDAlIHtcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDApO1xuICB9XG4gIDUwJSB7XG4gICAgdHJhbnNmb3JtOiBzY2FsZSgxLjI1KTtcbiAgfVxuICAxMDAlIHtcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDEpO1xuICB9XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

**Comment by lcyhyl** [comment]
@btea 
![image](https://github.com/element-plus/element-plus/assets/112603643/6eb67765-7708-4c67-adeb-c7da1446201f)
 wei为什么不能直接使用 内置的动画？

**Comment by btea** [comment]
It seems that the corresponding css style is overwritten.

![image](https://github.com/element-plus/element-plus/assets/24516654/54f65d1c-51e5-4224-a3ee-5278ca58ebe1)

**Comment by lcyhyl** [comment]
@btea 我发现只要把     :gpu-acceleration="false" 就可以正常工作了，大佬能帮忙解释一下吗，不是很明白

**Comment by btea** [comment]
设置 `:gpu-acceleration="false"` 之后，弹窗内容并没有设置`transform`样式，所以不会影响动画。

![image](https://github.com/user-attachments/assets/8cb50921-9185-48e7-bee2-e5d36fe0b847)
