### ISSUE TITLE
[Bug Report] When <el-input> slots in <el-table-column>, every time you type in a character in <el-input>, <el-input> loses focus.

### ISSUE THREAD

**Issue by microkof** [element-plus/element-plus#1739]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
windows 10 / Chrome 76

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/microkof/pen/zYNZprp

### Steps to reproduce
<el-input> slot in <el-table-column>

### What is Expected?
 every time you type in a character in <el-input>, <el-input> don't lose focus.

### What is actually happening?
 every time you type in a character in <el-input>, <el-input> loses focus.

**Comment by ydydydq** [comment]
Is there a solution?

**Comment by ogogogo** [comment]
I also found this problem
v1.0.2-beta.37

**Comment by liushuiyuan001** [comment]
#1824 same problem

**Comment by rebider** [comment]
我就想问有人解决了没有？

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am so sorry for this bug, we will try to reimplement our table component within a few days. Right now the component just re-renders the child component whenever it gets updated. So that your input component was being repeatedly unmounted and mounted into the DOM, which caused the problem you were encountering.

**Comment by JeremyWuuuuu** [comment]
Simplest solution for now: https://github.com/element-plus/element-plus/issues/1824#issuecomment-819177897

**Comment by JeremyWuuuuu** [comment]
Fixed in #1835

**Comment by JeremyWuuuuu** [comment]
We will release a hot patch very soon today. You can upgrade to that version and get this issue fixed.

**Comment by JeremyWuuuuu** [comment]
https://github.com/element-plus/element-plus/actions/runs/746929605 if you want to keep an eye on the release process

**Comment by JeremyWuuuuu** [comment]
After the release gets finished, upgrade to beta.40 should solve your issue
