### ISSUE TITLE
[Bug Report] Export raw object/type for globalProperties modules like Notify

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#1740]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Any

### Vue version
3.0.11

### Steps to reproduce
It is impossible to use the $notify utility in Typescript with composition API without typecasting to any.

Example main.ts
```
import { createApp } from 'vue';
import ElNotification from 'element-plus/lib/el-notification';
import App from './app.vue';

const app = createApp(App);
app.use(ElNotification);
app.provide('$notify', app.config.globalProperties.$notify);
```

Example component.vue
```
<template><div>Hello World</div></template>
<script lang="ts">
import { defineComponent, inject } from 'vue';
export default defineComponent({
    setup() {
        const $notify = inject<any>('$notify'); // <- Very bad, needs to be <Notify> instead of <any>
        $notify.info({
             message: 'Hello World'
        });
    }
});
</script>
```

### What is Expected?
It would be a lot easier if the notification module exported the Notify type, or even the raw object as an option. At present I see no way to retrieve this.

https://github.com/element-plus/element-plus/blob/dev/packages/notification/index.ts#L4

e.g.
```
export default _Notify // <- After this line,
export { Notify }
```

### What is actually happening?
There is no way to retrieve the Notify type in order to have Typescript bindings for presenting notifications.

**Comment by Giwayume** [comment]
I see INotification can be imported by digging into the src folder. Is that the intended design? I'm a bit uneasy any time I dig into a folder called 'src' from a framework consumption perspective.

```
import { INotification } from 'element-plus/lib/el-notification/src/notification.type';
```

**Comment by kid1412621** [comment]
i've found some solution for `element-ui` by adding to types in ts.config. However it's not working for `element-plus`

**Comment by sxzz** [comment]
Please use following method for Composition API
```ts
import { ElNotification } from 'element-plus';
ElNotification.success({
  // ....
});
``
