### ISSUE TITLE
[Component] [tree-select] 子组件事件使用相同事件名通知到父组件，父组件调用后报错

### ISSUE THREAD

**Issue by Zharlb** [element-plus/element-plus#17405]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.3.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGNvbXAgdi1tb2RlbD1cInZhbHVlXCIgQG5vZGUtY2xpY2s9XCJhXCIvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIj5cbmltcG9ydCBjb21wIGZyb20gJy4vQ29tcC52dWUnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgbmFtZTogXCJFbFNlbGVjdFRyZWVcIixcbiAgY29tcG9uZW50czoge1xuICAgIGNvbXBcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgdmFsdWU6ICcnXG4gICAgfVxuICB9LFxuICBtZXRob2RzOiB7XG4gICAgYShlKSB7XG4gICAgICBjb25zb2xlLmxvZygyMjIsIGUpXG4gICAgfVxuICB9LFxufTtcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL0NvbXAudnVlIjoiPHRlbXBsYXRlPlxyXG4gIDxlbC10cmVlLXNlbGVjdFxyXG4gICAgdi1tb2RlbD1cImlubmVyVmFsdWVcIlxyXG4gICAgOmRhdGE9XCJbe2xhYmVsOiAn5rWL6K+VJywgaWQ6IDEsIHZhbHVlOiAxfV1cIlxyXG4gICAgQG5vZGUtY2xpY2s9XCJhYWFcIlxyXG4gIC8+XHJcbjwvdGVtcGxhdGU+XHJcblxyXG48c2NyaXB0IGxhbmc9XCJ0c1wiPlxyXG5leHBvcnQgZGVmYXVsdCB7XHJcbiAgbmFtZTogXCJFbFNlbGVjdFRyZWVcIixcclxuICBwcm9wczoge1xyXG4gICAgbW9kZWxWYWx1ZToge1xyXG4gICAgICByZXF1aXJlZDogdHJ1ZSxcclxuICAgICAgdHlwZTogTnVtYmVyLFxyXG4gICAgfSxcclxuICB9LFxyXG4gIGNvbXB1dGVkOiB7XHJcbiAgICBpbm5lclZhbHVlOiB7XHJcbiAgICAgIGdldCgpIHtcclxuICAgICAgICByZXR1cm4gdGhpcy5tb2RlbFZhbHVlO1xyXG4gICAgICB9LFxyXG4gICAgICBzZXQodikge1xyXG4gICAgICAgIHRoaXMuJGVtaXQoXCJ1cGRhdGU6bW9kZWxWYWx1ZVwiLCB2KTtcclxuICAgICAgfSxcclxuICAgIH0sXHJcbiAgfSxcclxuICBtZXRob2RzOiB7XHJcbiAgICBhYWEoKSB7XHJcbiAgICAgIGNvbnNvbGUubG9nKDExMSlcclxuICAgICAgdGhpcy4kZW1pdCgnbm9kZS1jbGljaycsIDEpXHJcbiAgICB9XHJcbiAgfSxcclxufTtcclxuPC9zY3JpcHQ+XHJcbiIsIl9vIjp7fX0=)

### Steps to reproduce

选择下拉框值，控制台报错

### What is Expected?

可以正常通知父节点方法

### What is actually happening?

报错 m.call is not a function

### Additional comments

_(empty)_

**Comment by btea** [comment]
There seems to be something wrong with the writing. Please use the setup syntax. [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGNvbXAgdi1tb2RlbD1cInZhbHVlXCIgQG5vZGUtY2xpY2s9XCJhXCIvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKClcbmNvbnN0IGEgPSAodjogYW55KSA9PiB7XG4gIGNvbnNvbGUubG9nKHYpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9Db21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cclxuICA8ZWwtdHJlZS1zZWxlY3RcclxuICAgIHYtbW9kZWw9XCJpbm5lclZhbHVlXCJcclxuICAgIDpkYXRhPVwiW3tsYWJlbDogJ+a1i+ivlScsIGlkOiAxLCB2YWx1ZTogMX1dXCJcclxuICAgIEBub2RlLWNsaWNrPVwiYWFhXCJcclxuICAvPlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cclxuY29uc3QgaW5uZXJWYWx1ZSA9IGRlZmluZU1vZGVsKClcclxuY29uc3QgZW1pdCA9IGRlZmluZUVtaXRzKFsnbm9kZS1jbGljayddKVxyXG5jb25zdCBhYWEgPSAoZTogYW55KSA9PiB7XHJcbiAgY29uc29sZS5sb2coJ0NvbXAnLCBlKVxyXG4gIGVtaXQoJ25vZGUtY2xpY2snLCBlKVxyXG59XHJcbjwvc2NyaXB0PlxyXG4iLCJfbyI6e319)
