### ISSUE TITLE
[Component] [date-picker] 当使用model-value 代替v-model时，change事件没有被触发

### ISSUE THREAD

**Issue by skyshirt** [element-plus/element-plus#17425]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbERhdGVQaWNrZXIgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGRhdGVWYWx1ZSA9IHJlZignJylcbmNvbnN0IGRhdGVNb2RlbFZhbHVlID0gcmVmKCcnKVxuXG5cbmZ1bmN0aW9uIG9uQ2hhbmdlTW9kZWxNb2RlbChlKSB7XG4gIGNvbnNvbGUubG9nKCdvbkNoYW5nZTogJywgZSlcbiAgZGF0ZU1vZGVsVmFsdWUudmFsdWUgPSBlXG59XG5mdW5jdGlvbiBvbkNoYW5nZVZNb2RlbChlKSB7XG4gIGNvbnNvbGUubG9nKCdvbkNoYW5nZTogJywgZSlcbiAgZGF0ZVZhbHVlLnZhbHVlID0gZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtZGF0ZS1waWNrZXIgOm1vZGVsLXZhbHVlPVwiZGF0ZU1vZGVsVmFsdWVcIiB0eXBlPVwiZGF0ZVwiIEBjaGFuZ2U9XCJvbkNoYW5nZU1vZGVsTW9kZWxcIiAvPlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cImRhdGVWYWx1ZVwiXG4gICAgICB0eXBlPVwiZGF0ZVwiXG4gICAgICB2YWx1ZS1mb3JtYXQ9XCJZWVlZLU1NLUREXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiXG4gICAgICBAY2hhbmdlPVwib25DaGFuZ2VWTW9kZWxcIlxuICAgIC8+XG4gICAgPHA+XG4gICAgICBkYXRlTW9kZWxWYWx1ZToge3sgZGF0ZU1vZGVsVmFsdWUgfX1cbiAgICA8L3A+XG4gICAgPHA+XG4gICAgICBkYXRlVmFsdWU6IHt7IGRhdGVWYWx1ZSB9fVxuICAgIDwvcD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue'

const dateModelValue = ref('')

function onChangeModelModel(e) {
  console.log('onChange: ', e)
  dateModelValue.value = e
}
</script>

<template>
  <div>
    <el-date-picker :model-value="dateModelValue" type="date" @change="onChangeModelModel" />
    <p>
      dateModelValue: {{ dateModelValue }}
    </p>
  </div>
</template>
```

### What is Expected?

可以触发change事件，并收到更新后的值

### What is actually happening?

没有触发change事件，未收到任何值

### Additional comments

_(empty)_

**Comment by XL-YiBai** [comment]
是不是应该添加一个事件监听来改变 model-value 的值，v-model 就是它们（`:model-value="dateModelValue" @update:model-value="val => dateModelValue = val "`）的语法糖  ：

`<el-date-picker :model-value="dateModelValue" @update:model-value="val => dateModelValue = val " type="date" @change="onChangeModelModel" />`

**Comment by btea** [comment]
Duplicate of #17105
