### ISSUE TITLE
[Bug Report] el-checkbox-group min

### ISSUE THREAD

**Issue by xiaolannuoyi** [element-plus/element-plus#1742]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
mac os 11.2.3/ chrome  89.0.4389.90

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/xiaolannuoyi/pen/ZELerQq

### Steps to reproduce
min>1 and `v-model` is `[]`

The checkbox cannot be selected

### What is Expected?
The checkbox can be selected

### What is actually happening?
The checkbox cannot be selected

**Comment by JeremyWuuuuu** [comment]
I don't think that this is a bug, you can use the same code in version 2.x, the result it is consistent to version 3.x, users need to know what they are doing with the properties. using properties like this seemed unreasonable to me.
Would you mind providing me some insights of why you were using it this way?

**Comment by xiaolannuoyi** [comment]
比方说，需要用户填写一个表单，其中 el-checkbox-group 最少填写两个，但是v-model 初始化的数据 肯定是 空数组的

**Comment by xiaolannuoyi** [comment]
我不明白为什么说这是不合理的，不能说，我去给用户添加初始值来保正组件的正常运行吧？

**Comment by JeremyWuuuuu** [comment]
Fair point. When the limit `min` is not reached, `el-checkbox-group` should propagate errors to the upper layer e.g. `el-form`, I think you made your point, will fix ASAP.

**Comment by CokeMine** [comment]
@JeremyWuuuuu Hi, my PR is ready for review. The change allow to add options when default actived options' length <= the min limit. If the change is correct. I will add some tests.)

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu Hi, my PR is ready for review. The change allow to add options when default actived options' length <= the min limit. If the change is correct. I will add some tests.)

You need to mark it `ready for review` there was a button.
