### ISSUE TITLE
[bug report] using label with slot mode in tabs component will lose responsiveness

### ISSUE THREAD

**Issue by totchina** [element-plus/element-plus#1744]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
chrome 88

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/totchina/pen/poReabK?editable=true%3Dhttps%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
1、ref初始化tabs
2、setTimeout 2秒后改变tabs中的label
3、用:label props方式渲染出新label，用#label slots方式无法渲染出新label，丢失响应性

### What is Expected?
能用slots方式使用Tabs并保留数据的响应性

### What is actually happening?
在Tabs组件中用slot方式使用label会丢失响应性

**Comment by kooriookami** [comment]
You can replace `map` with `forEach`. And we will check it out.
For example:
```js
      tabs.value.forEach(item => {
        item.label = item.label + ' new'
      })
```
