### ISSUE TITLE
[Component] [select] 使用在多个namespace 导致el-select组件报错

### ISSUE THREAD

**Issue by javie5** [element-plus/element-plus#17454]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHQgPSByZWYoJycpO1xuY29uc3QgdDEgPSByZWYoJycpO1xuY29uc3QgbXNnID0gcmVmKCflnKjlpJrkuKplbC1jb25maWctcHJvdmlkZXIg5Lit5L2/55SoZWwtc2VsZWN0O+mhueebruWHuueOsOW8guW4uCcpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA+XG4gICAgbmFtZXNwYWNlPVwicGxhdGZvcm1cIiBcbiAgICA8ZWwtc2VsZWN0IHBsYWNlaG9sZGVyPVwi6K+36YCJ5oupXCIgdi1tb2RlbD1cInRcIj5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLpgInpobkxXCIgdmFsdWU9XCLpgInpobkxXCI+PC9lbC1vcHRpb24+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICA8aHIgLz5cbiAgPEVsQ29uZmlnUHJvdmlkZXIgbmFtZXNwYWNlPVwicGxhdGZvcm1cIj5cbiAgICBuYW1lc3BhY2U9XCJlbFwiIFxuICAgIDxlbC1zZWxlY3QgcGxhY2Vob2xkZXI9XCLor7fpgInmi6lcIiB2LW1vZGVsPVwidDFcIj5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLpgInpobkxXCIgdmFsdWU9XCLpgInpobkxXCI+PC9lbC1vcHRpb24+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvRWxDb25maWdQcm92aWRlcj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

直接访问在线链接

### What is Expected?

el-select组件正常工作

### What is actually happening?

后加载的el-select组件报错,不能正常使用

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
请勿重复提交
