### ISSUE TITLE
[Style] [anchor, anchor-link] 手动滚动到特定位置参数异常

### ISSUE THREAD

**Issue by q8018414** [element-plus/element-plus#17450]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-anchor`
- `el-anchor-link`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtcm93PlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjE4XCI+XG4gICAgICAgIDxkaXZcbiAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgaGVpZ2h0OiAzMHB4O1xuICAgICAgICAgICAgd2lkdGg6IDcwJTtcbiAgICAgICAgICAgIGJhY2tncm91bmQ6ICMwMDA7XG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgICAgICB0b3A6IDA7XG4gICAgICAgICAgICBsZWZ0OiAwO1xuICAgICAgICAgICAgY29sb3I6ICNmZmY7XG4gICAgICAgICAgXCJcbiAgICAgICAgPlxuICAgICAgICAgIEZpeGVkIFRvcCBCbG9ja1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiByZWY9XCJjb250YWluZXJSZWZcIiBzdHlsZT1cImhlaWdodDogMzAwcHg7IG92ZXJmbG93LXk6IGF1dG9cIj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQxXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMjU1LCAwLCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDFcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQyXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMjU1LCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDJcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQzXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMCwgMjU1LCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDNcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCI2XCI+XG4gICAgICAgIDxlbC1hbmNob3JcbiAgICAgICAgICA6Y29udGFpbmVyPVwiY29udGFpbmVyUmVmXCJcbiAgICAgICAgICBkaXJlY3Rpb249XCJ2ZXJ0aWNhbFwiXG4gICAgICAgICAgcmVmPVwiYW5jaG9yXCJcbiAgICAgICAgICB0eXBlPVwiZGVmYXVsdFwiXG4gICAgICAgICAgOm9mZnNldD1cIjMwXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVDbGlja1wiXG4gICAgICAgID5cbiAgICAgICAgICA8ZWwtYW5jaG9yLWxpbmsgaHJlZj1cIiNwYXJ0MVwiIHRpdGxlPVwicGFydDFcIiAvPlxuICAgICAgICAgIDxlbC1hbmNob3ItbGluayBocmVmPVwiI3BhcnQyXCIgdGl0bGU9XCJwYXJ0MlwiIC8+XG4gICAgICAgICAgPGVsLWFuY2hvci1saW5rIGhyZWY9XCIjcGFydDNcIiB0aXRsZT1cInBhcnQzXCIgLz5cbiAgICAgICAgPC9lbC1hbmNob3I+XG4gICAgICA8L2VsLWNvbD5cbiAgICA8L2VsLXJvdz5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrXCI+TTwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbnRhaW5lclJlZiA9IHJlZjxIVE1MRWxlbWVudCB8IG51bGw+KG51bGwpXG5jb25zdCBhbmNob3IgPSByZWY8SFRNTEVsZW1lbnQgfCBudWxsPihudWxsKTtcbmNvbnN0IGhhbmRsZUNsaWNrID0gKGU6IE1vdXNlRXZlbnQpID0+IHtcbiAgZS5wcmV2ZW50RGVmYXVsdCgpXG59XG5cbmNvbnN0IGNsaWNrID0gKCk9PntcbiAgY29uc29sZS5sb2coYW5jaG9yLnZhbHVlLnNjcm9sbFRvKVxuICBhbmNob3IudmFsdWUuc2Nyb2xsVG8oe2hyZWY6XCIjcGFydDJcIn0pXG4gIGNvbnRhaW5lclJlZi52YWx1ZS5zY3JvbGxUbyh7aHJlZjpcIiNwYXJ0MlwifSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==) 

### Steps to reproduce

点击m按钮.手动滚动到特定位置。报错.

### What is Expected?

根据链接位置进行滚动.

### What is actually happening?

无任何动作.

### Additional comments

期望,兼容手机进行滑动滑动计算所在位置..手动滚动到特定位置,也是想做这个功能.

**Comment by q8018414** [comment]
[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtcm93PlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjE4XCI+XG4gICAgICAgIDxkaXZcbiAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgaGVpZ2h0OiAzMHB4O1xuICAgICAgICAgICAgd2lkdGg6IDcwJTtcbiAgICAgICAgICAgIGJhY2tncm91bmQ6ICMwMDA7XG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgICAgICB0b3A6IDA7XG4gICAgICAgICAgICBsZWZ0OiAwO1xuICAgICAgICAgICAgY29sb3I6ICNmZmY7XG4gICAgICAgICAgXCJcbiAgICAgICAgPlxuICAgICAgICAgIEZpeGVkIFRvcCBCbG9ja1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiByZWY9XCJjb250YWluZXJSZWZcIiBzdHlsZT1cImhlaWdodDogMzAwcHg7IG92ZXJmbG93LXk6IGF1dG9cIj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQxXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMjU1LCAwLCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDFcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQyXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMjU1LCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDJcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQzXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMCwgMjU1LCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDNcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCI2XCI+XG4gICAgICAgIDxlbC1hbmNob3JcbiAgICAgICAgICA6Y29udGFpbmVyPVwiY29udGFpbmVyUmVmXCJcbiAgICAgICAgICBkaXJlY3Rpb249XCJ2ZXJ0aWNhbFwiXG4gICAgICAgICAgcmVmPVwiYW5jaG9yXCJcbiAgICAgICAgICB0eXBlPVwiZGVmYXVsdFwiXG4gICAgICAgICAgOm9mZnNldD1cIjMwXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVDbGlja1wiXG4gICAgICAgID5cbiAgICAgICAgICA8ZWwtYW5jaG9yLWxpbmsgaHJlZj1cIiNwYXJ0MVwiIHRpdGxlPVwicGFydDFcIiAvPlxuICAgICAgICAgIDxlbC1hbmNob3ItbGluayBocmVmPVwiI3BhcnQyXCIgdGl0bGU9XCJwYXJ0MlwiIC8+XG4gICAgICAgICAgPGVsLWFuY2hvci1saW5rIGhyZWY9XCIjcGFydDNcIiB0aXRsZT1cInBhcnQzXCIgLz5cbiAgICAgICAgPC9lbC1hbmNob3I+XG4gICAgICA8L2VsLWNvbD5cbiAgICA8L2VsLXJvdz5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrXCI+TTwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbnRhaW5lclJlZiA9IHJlZjxIVE1MRWxlbWVudCB8IG51bGw+KG51bGwpXG5jb25zdCBhbmNob3IgPSByZWY8SFRNTEVsZW1lbnQgfCBudWxsPihudWxsKTtcbmNvbnN0IGhhbmRsZUNsaWNrID0gKGU6IE1vdXNlRXZlbnQpID0+IHtcbiAgZS5wcmV2ZW50RGVmYXVsdCgpXG59XG5cbmNvbnN0IGNsaWNrID0gKCk9PntcbiAgY29uc29sZS5sb2coYW5jaG9yLnZhbHVlLnNjcm9sbFRvKVxuICBhbmNob3IudmFsdWUuc2Nyb2xsVG8oe2hyZWY6XCIjcGFydDFcIn0pXG4gIGNvbnRhaW5lclJlZi52YWx1ZS5zY3JvbGxUbyh7aHJlZjpcIiNwYXJ0MVwifSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtcm93PlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjE4XCI+XG4gICAgICAgIDxkaXZcbiAgICAgICAgICBzdHlsZT1cIlxuICAgICAgICAgICAgaGVpZ2h0OiAzMHB4O1xuICAgICAgICAgICAgd2lkdGg6IDcwJTtcbiAgICAgICAgICAgIGJhY2tncm91bmQ6ICMwMDA7XG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgICAgICB0b3A6IDA7XG4gICAgICAgICAgICBsZWZ0OiAwO1xuICAgICAgICAgICAgY29sb3I6ICNmZmY7XG4gICAgICAgICAgXCJcbiAgICAgICAgPlxuICAgICAgICAgIEZpeGVkIFRvcCBCbG9ja1xuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiByZWY9XCJjb250YWluZXJSZWZcIiBzdHlsZT1cImhlaWdodDogMzAwcHg7IG92ZXJmbG93LXk6IGF1dG9cIj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQxXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMjU1LCAwLCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDFcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQyXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMjU1LCAwLCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDJcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICBpZD1cInBhcnQzXCJcbiAgICAgICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgICAgIGhlaWdodDogMzAwcHg7XG4gICAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMCwgMjU1LCAwLjAyKTtcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICAgICAgICAgIFwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgcGFydDNcbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCI2XCI+XG4gICAgICAgIDxlbC1hbmNob3JcbiAgICAgICAgICA6Y29udGFpbmVyPVwiY29udGFpbmVyUmVmXCJcbiAgICAgICAgICBkaXJlY3Rpb249XCJ2ZXJ0aWNhbFwiXG4gICAgICAgICAgcmVmPVwiYW5jaG9yXCJcbiAgICAgICAgICB0eXBlPVwiZGVmYXVsdFwiXG4gICAgICAgICAgOm9mZnNldD1cIjMwXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVDbGlja1wiXG4gICAgICAgID5cbiAgICAgICAgICA8ZWwtYW5jaG9yLWxpbmsgaHJlZj1cIiNwYXJ0MVwiIHRpdGxlPVwicGFydDFcIiAvPlxuICAgICAgICAgIDxlbC1hbmNob3ItbGluayBocmVmPVwiI3BhcnQyXCIgdGl0bGU9XCJwYXJ0MlwiIC8+XG4gICAgICAgICAgPGVsLWFuY2hvci1saW5rIGhyZWY9XCIjcGFydDNcIiB0aXRsZT1cInBhcnQzXCIgLz5cbiAgICAgICAgPC9lbC1hbmNob3I+XG4gICAgICA8L2VsLWNvbD5cbiAgICA8L2VsLXJvdz5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNrXCI+TTwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbnRhaW5lclJlZiA9IHJlZjxIVE1MRWxlbWVudCB8IG51bGw+KG51bGwpXG5jb25zdCBhbmNob3IgPSByZWY8SFRNTEVsZW1lbnQgfCBudWxsPihudWxsKTtcbmNvbnN0IGhhbmRsZUNsaWNrID0gKGU6IE1vdXNlRXZlbnQpID0+IHtcbiAgZS5wcmV2ZW50RGVmYXVsdCgpXG59XG5cbmNvbnN0IGNsaWNrID0gKCk9PntcbiAgY29uc29sZS5sb2coYW5jaG9yLnZhbHVlLnNjcm9sbFRvKVxuICBhbmNob3IudmFsdWUuc2Nyb2xsVG8oe2hyZWY6XCIjcGFydDJcIn0pXG4gIGNvbnRhaW5lclJlZi52YWx1ZS5zY3JvbGxUbyh7aHJlZjpcIiNwYXJ0MlwifSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==) 地址错了

**Comment by btea** [comment]
内置的`scrollTo`方法接收的参数为字符串。
https://github.com/element-plus/element-plus/blob/4a30d886a83450fff41aca43b653d66511aeb23d/packages/components/anchor/src/anchor.vue#L100-L105

**Comment by q8018414** [comment]
额.离谱.我的问题...
