### ISSUE TITLE
[Docs] [radio-group] 文档有问题是

### ISSUE THREAD

**Issue by liyunguang-d** [element-plus/element-plus#17467]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-radio-group`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/radio.html)

### Steps to reproduce

radio-group 需要使用label 文档中使用的value，只使用value 不起作用

### What is Expected?

实际的值为label，而不是value

### What is actually happening?

只有value 没有label

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/17051 ,@liyunguang-d

**Comment by xianggu-skillnote** [comment]
我也有過相同疑惑，後來確認是版本問題而不是文檔問題。你可能使用的是3.0以下的版本。
[#17087](https://github.com/element-plus/element-plus/issues/17087)

**Comment by kisekiremi** [comment]
![image](https://github.com/user-attachments/assets/e631be83-e2a9-4806-a067-1ea646af01f2)
@liyunguang-d
