### ISSUE TITLE
[Component] [dropdown, tooltip] 无法嵌套使用 `ElTooltip` 和 `ElTooltip`

### ISSUE THREAD

**Issue by vanchKong** [element-plus/element-plus#17468]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG5cblxuICA8RWxEcm9wZG93biB0cmlnZ2VyPVwiY2xpY2tcIj5cblx0PEVsVG9vbHRpcCBjb250ZW50PVwiMTIzMTIzXCI+XG5cdFx0PHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+IERyb3Bkb3duIExpc3QgPC9zcGFuPlxuXHQ8L0VsVG9vbHRpcD5cblx0PHRlbXBsYXRlICNkcm9wZG93bj5cblx0XHQ8RWxEcm9wZG93bk1lbnU+XG5cdFx0XHQ8RWxEcm9wZG93bkl0ZW0+QWN0aW9uIDE8L0VsRHJvcGRvd25JdGVtPlxuXHRcdFx0PEVsRHJvcGRvd25JdGVtPkFjdGlvbiAyPC9FbERyb3Bkb3duSXRlbT5cblx0XHRcdDxFbERyb3Bkb3duSXRlbT5BY3Rpb24gMzwvRWxEcm9wZG93bkl0ZW0+XG5cdFx0XHQ8RWxEcm9wZG93bkl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L0VsRHJvcGRvd25JdGVtPlxuXHRcdFx0PEVsRHJvcGRvd25JdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L0VsRHJvcGRvd25JdGVtPlxuXHRcdDwvRWxEcm9wZG93bk1lbnU+XG5cdDwvdGVtcGxhdGU+XG48L0VsRHJvcGRvd24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

```
<ElDropdown trigger="click">
	<ElTooltip content="123123">
		<span class="el-dropdown-link"> Dropdown List </span>
	</ElTooltip>
	<template #dropdown>
		<ElDropdownMenu>
			<ElDropdownItem>Action 1</ElDropdownItem>
			<ElDropdownItem>Action 2</ElDropdownItem>
			<ElDropdownItem>Action 3</ElDropdownItem>
			<ElDropdownItem disabled>Action 4</ElDropdownItem>
			<ElDropdownItem divided>Action 5</ElDropdownItem>
		</ElDropdownMenu>
	</template>
</ElDropdown>
```

### What is Expected?

嵌套使用 `ElTooltip` `ElDropdown`时，能够正常显示tooltip，且点击能够展开菜单

### What is actually happening?

点击无法展开菜单

### Additional comments

_(empty)_

**Comment by btea** [comment]
`dropdown`依赖默认插槽里的标签内容来挂载下拉框内容。你可以给`el-tooltip`标签套一个`div`。[示例](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG5cblxuICA8RWxEcm9wZG93biB0cmlnZ2VyPVwiY2xpY2tcIj5cblx0XHQ8ZGl2Plx0XG5cdFx0XHQ8RWxUb29sdGlwIGNvbnRlbnQ9XCIxMjMxMjNcIj5cblx0XHRcdFx0PHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+IERyb3Bkb3duIExpc3QgPC9zcGFuPlxuXHRcdFx0PC9FbFRvb2x0aXA+XG5cdFx0PC9kaXY+XG5cdDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG5cdFx0PEVsRHJvcGRvd25NZW51PlxuXHRcdFx0PEVsRHJvcGRvd25JdGVtPkFjdGlvbiAxPC9FbERyb3Bkb3duSXRlbT5cblx0XHRcdDxFbERyb3Bkb3duSXRlbT5BY3Rpb24gMjwvRWxEcm9wZG93bkl0ZW0+XG5cdFx0XHQ8RWxEcm9wZG93bkl0ZW0+QWN0aW9uIDM8L0VsRHJvcGRvd25JdGVtPlxuXHRcdFx0PEVsRHJvcGRvd25JdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9FbERyb3Bkb3duSXRlbT5cblx0XHRcdDxFbERyb3Bkb3duSXRlbSBkaXZpZGVkPkFjdGlvbiA1PC9FbERyb3Bkb3duSXRlbT5cblx0XHQ8L0VsRHJvcGRvd25NZW51PlxuXHQ8L3RlbXBsYXRlPlxuPC9FbERyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by vanchKong** [comment]
@btea 确实达到预期效果了，但这也蛮有意思的，加了`div`就不被认作是插槽了吗😂

**Comment by btea** [comment]
因为`div`是默认就存在的标签，所以`dropdown`下拉内容挂载的时候能找到标签，`el-tooltip`里面的标签，要等它的组件渲染默认插槽的时候才存在。
