### ISSUE TITLE
[i18n] [tour, tour-step] missing translation for the fr-locale

### ISSUE THREAD

**Issue by ThomasGa17** [element-plus/element-plus#17474]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome/126.0.6478.127`
- Build Tool: `Vite`

### Related Component

- `el-tour`
- `el-tour-step`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciA6bG9jYWxlPVwiZnJcIj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib3BlbiA9IHRydWVcIj5CZWdpbiBUb3VyPC9lbC1idXR0b24+XG5cbiAgICA8ZWwtZGl2aWRlciAvPlxuXG4gICAgPGVsLXNwYWNlPlxuICAgICAgPGVsLWJ1dHRvbiByZWY9XCJyZWYxXCI+VXBsb2FkPC9lbC1idXR0b24+XG4gICAgICA8ZWwtYnV0dG9uIHJlZj1cInJlZjJcIiB0eXBlPVwicHJpbWFyeVwiPlNhdmU8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gcmVmPVwicmVmM1wiIDppY29uPVwiTW9yZUZpbGxlZFwiIC8+XG4gICAgPC9lbC1zcGFjZT5cblxuICAgIDxlbC10b3VyIHYtbW9kZWw9XCJvcGVuXCI+XG4gICAgICA8ZWwtdG91ci1zdGVwIDp0YXJnZXQ9XCJyZWYxPy4kZWxcIiB0aXRsZT1cIlVwbG9hZCBGaWxlXCI+XG4gICAgICAgIDxpbWdcbiAgICAgICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICAgICAgc3JjPVwiaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmdcIlxuICAgICAgICAgIGFsdD1cInRvdXIucG5nXCJcbiAgICAgICAgLz5cbiAgICAgICAgPGRpdj5QdXQgeW91IGZpbGVzIGhlcmUuPC9kaXY+XG4gICAgICA8L2VsLXRvdXItc3RlcD5cbiAgICAgIDxlbC10b3VyLXN0ZXBcbiAgICAgICAgOnRhcmdldD1cInJlZjI/LiRlbFwiXG4gICAgICAgIHRpdGxlPVwiU2F2ZVwiXG4gICAgICAgIGRlc2NyaXB0aW9uPVwiU2F2ZSB5b3VyIGNoYW5nZXNcIlxuICAgICAgLz5cbiAgICAgIDxlbC10b3VyLXN0ZXBcbiAgICAgICAgOnRhcmdldD1cInJlZjM/LiRlbFwiXG4gICAgICAgIHRpdGxlPVwiT3RoZXIgQWN0aW9uc1wiXG4gICAgICAgIGRlc2NyaXB0aW9uPVwiQ2xpY2sgdG8gc2VlIG90aGVyXCJcbiAgICAgIC8+XG4gICAgPC9lbC10b3VyPlxuICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBNb3JlRmlsbGVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgdHlwZSB7IEJ1dHRvbkluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IGZyIGZyb20gJ2VsZW1lbnQtcGx1cy9kaXN0L2xvY2FsZS9mci5tanMnXG5cbmNvbnN0IHJlZjEgPSByZWY8QnV0dG9uSW5zdGFuY2U+KClcbmNvbnN0IHJlZjIgPSByZWY8QnV0dG9uSW5zdGFuY2U+KClcbmNvbnN0IHJlZjMgPSByZWY8QnV0dG9uSW5zdGFuY2U+KClcblxuY29uc3Qgb3BlbiA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

- Use `ElConfigProvider` with fr as language.
- Use `ElTour` and `ElTourStep` within your project.

### What is Expected?

The french translation for navigation buttons :
- next -> "suivant"
- previous -> "précédent"
- finish -> "fin"

### What is actually happening?

The component uses the translation key :
- next -> "el.tour.next"
- previous -> "el.tour.previous"
- finish -> "el.tour.finish"

### Additional comments

_(empty)_

**Comment by zhuchaoling** [comment]
I've looked at the source code, and these translations aren't there. You can translate and submit a PR.
