### ISSUE TITLE
[Style] [All] Sass rules deprecation warnings

### ISSUE THREAD

**Issue by Jungzl** [element-plus/element-plus#17487]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Link](I think reproduction is not needed for this issue)

### Steps to reproduce

start a new nuxt project with @element-plus/nuxt

### What is Expected?

fix [sass](https://sass-lang.com/d/mixed-decls) warnings.

### What is actually happening?

Almost every component throws a warning like
```bash
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
159│     padding: $padding-vertical $padding-horizontal;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 159:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 75:3           @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet
```

### Additional comments

```json
"dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "@element-plus/nuxt": "^1.0.9",
    "element-plus": "^2.7.6",
    "vue": "^3.4.31",
  },
  "devDependencies": {
    "nuxt": "^3.12.3",
    "sass": "^1.77.7",
  },
```

**Comment by MQYForverT** [comment]
That's right, I also encountered this problem
<img width="981" alt="image" src="https://github.com/element-plus/element-plus/assets/36668907/13365cd9-2c02-4717-935f-9556d32a9ce6">
"dependencies": {
    "element-plus": "^2.7.6",
    "vue": "^3.4.31",
  },
  "devDependencies": {
    "sass": "^1.77.7",
  },

**Comment by MQYForverT** [comment]
look the sass:
https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1775
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by Jungzl** [comment]
I recheck my lock file and yes this issue occurs since sass@1.77.7

**Comment by polarove** [comment]
sass@1.71.1
element-plus@2.7.6

Have encountered this issue as well

**Comment by sudoooooo** [comment]
同上，希望官方尽快升级对sass的处理：
https://sass-lang.com/documentation/breaking-changes/mixed-decls/#deprecating-the-old-way
![image](https://github.com/element-plus/element-plus/assets/16012672/bfdf4b74-2a05-42df-9c6f-da710ad58c98)

**Comment by warmthsea** [comment]
This problem does exist. There are many components and some testing may be needed. I will submit the relevant PR later.

**Comment by warmthsea** [comment]
https://github.com/vuetifyjs/vuetify/issues/20139

@Jungzl @sudoooooo @MQYForverT 

I have seen similar problems with other libraries. If you modify the code directly, the changes will be too much. I don’t think it is the best way, so I suggest that users temporarily use a lower version of sass, for example: `"sass": "^1.53.0"`.

Specific solutions are yet to be discussed.

**Comment by MQYForverT** [comment]
CSS is causing trouble, it depends on whether our UI library complies with the latest CSS standards. Of course, it is not ruled out that CSS may be changed back in the future...

**Comment by lyking90** [comment]
I also encountered such a problem。breaking change for sass@1.77.7
![image](https://github.com/user-attachments/assets/25c78fe0-f9e1-4540-914e-01b696ec8c60)
so I think ,the best solution is to downgrade the sass version

**Comment by Raman117** [comment]
yarn add sass@1.77.6

downgrade SASS this works

**Comment by jiaopengzi** [comment]
> yarn add sass@1.77.6
> 
> downgrade SASS this works

目前也是降级到了 `1.77.6` 解决的，希望官方尽快 fix sass `Breaking Change: Mixed Declarations`

**Comment by MQYForverT** [comment]
@tolking May I ask in which version it was fixed, 2.7.8?

**Comment by tolking** [comment]
> @tolking May I ask in which version it was fixed, 2.7.8?

The next version

**Comment by Jefdeniel** [comment]
> [vuetifyjs/vuetify#20139](https://github.com/vuetifyjs/vuetify/issues/20139)
> 
> @Jungzl @sudoooooo @MQYForverT
> 
> I have seen similar problems with other libraries. If you modify the code directly, the changes will be too much. I don’t think it is the best way, so I suggest that users temporarily use a lower version of sass, for example: `"sass": "^1.53.0"`.
> 
> Specific solutions are yet to be discussed.

1.53.0 works. Thanks!!

**Comment by phoenixweiss** [comment]
BTW, `"sass": "1.77.6"` is the latest version without deprecation warnings.
