### ISSUE TITLE
[Component] [switch]  The @update:model-value event is called at an incorrect time

### ISSUE THREAD

**Issue by joooooooojo** [element-plus/element-plus#17486]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.6`
- Browser / OS: `e.g. Edge 126.0.2592.81  / macOS 14.5`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgYSA9IHJlZigpXG5jb25zdCBvblVwZGF0ZTEgPSAoKT0+e1xuICBjb25zb2xlLmxvZyhcInN3aXRjaC0xIHVwZGF0ZVwiKVxufVxuY29uc3QgYiA9IHJlZigpXG5jb25zdCBvblVwZGF0ZTIgPSgpPT57XG4gIGNvbnNvbGUubG9nKCdzd2l0Y2gtMiB1cGRhdGUnKVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc3dpdGNoIDptb2RlbC12YWx1ZT1cImFcIiA6YWN0aXZlLXZhbHVlPVwiMVwiIDppbmFjdGl2ZS12YWx1ZT1cIjBcIiBAdXBkYXRlOm1vZGVsLXZhbHVlPVwib25VcGRhdGUxXCI+PC9lbC1zd2l0Y2g+XG4gIDxici8+XG4gIDxlbC1zd2l0Y2ggOm1vZGVsLXZhbHVlPVwiYlwiIEB1cGRhdGU6bW9kZWwtdmFsdWU9XCJvblVwZGF0ZTJcIj48L2VsLXN3aXRjaD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

Use @update:model-value to change the value of the el-switch binding with :active-value and :inactive-value
在设置 :active-value 和 :inactive-value 的情况下使用 @update:model-value 来修改 el-switch 绑定的值

### What is Expected?

@update:model-value is not triggered when the component is mounted
在组件挂载时不触发@update:model-value

### What is actually happening?

When a component is mounted, the @update:model-value event is triggered to cause unexpected behavior
组件在挂载时会触发@update:model-value事件导致出现期望外的行为

### Additional comments

_(empty)_

**Comment by btea** [comment]
组件挂载时，状态没有发生变化，不会触发`@update:model-value`是正常逻辑。

**Comment by joooooooojo** [comment]
> 组件挂载时，状态没有发生变化，不会触发`@update:model-value`是正常逻辑。

![image](https://github.com/element-plus/element-plus/assets/73393114/6fe37d3e-cc9a-4268-bd08-229245ee571a)
是的 但是现在如果设置了 `active-value` 这个属性，则在组件挂载时**会**触发`@update:model-value`
