### ISSUE TITLE
[Bug Report] using the vue-router invalidates the is-vertical of the container

### ISSUE THREAD

**Issue by CHOYSEN** [element-plus/element-plus#1750]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Edge 89.0.774.68

### Vue version
3.0.11

### Reproduction Link
https://github.com/CHOYSEN/container-issue

### Steps to reproduce
yarn
yarn dev

### What is Expected?
When nested with a el-header or el-footer, all its child elements will be vertically arranged. Otherwise horizontally.

https://element-plus.org/#/en-US/component/container

### What is actually happening?
using the vue-router invalidates the is-vertical of the container

```vue
<template>
  <el-container>
    <router-view></router-view>
  </el-container>
</template>
```

https://github.com/element-plus/element-plus/blob/1ab50ded03bbf46fb36a6495b207c6785019e753/packages/container/src/container.vue#L24-L32

**Comment by JeremyWuuuuu** [comment]
You might want to take a look at this: (I'm guessing you speak mandarin Chinese)
![image](https://user-images.githubusercontent.com/15975785/114119552-74f13c00-991d-11eb-9f91-262cfc0035fd.png)
Documentation site:
https://element-plus.org/#/zh-CN/component/container
