### ISSUE TITLE
[Component] [radio] Radio单选框组里面的示例代码value应该改成label

### ISSUE THREAD

**Issue by 15257741312** [element-plus/element-plus#17516]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-radio`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/radio.html)

### Steps to reproduce

查看示例代码

### What is Expected?

```vue
<template>
  <el-radio-group v-model="radio">
    <el-radio :label="3">Option A</el-radio>
    <el-radio :label="6">Option B</el-radio>
    <el-radio :label="9">Option C</el-radio>
  </el-radio-group>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const radio = ref(3)
</script>

```

### What is actually happening?

```vue
<template>
  <el-radio-group v-model="radio">
    <el-radio :value="3">Option A</el-radio>
    <el-radio :value="6">Option B</el-radio>
    <el-radio :value="9">Option C</el-radio>
  </el-radio-group>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const radio = ref(3)
</script>

```

### Additional comments

目前官网的示例代码会导致点击所有option全选

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/17051
