### ISSUE TITLE
[Feature Request] Add option to always show scrollbar in el-scrollbar, instead of showing only during mouse movement.

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#1751]
### Existing Component
Yes

### Component Name
el-scrollbar

### Description
Whenever the app shows long dropdowns that scroll, users can't tell that there's more options unless they're the type of person who moves their mouse along text as they read it. Some people will simply click the dropdown, read all the options, and never know that there's more because they never move their mouse over the dropdown to trigger the scrollbar to appear. This is bad usability.

See in this example, there's nothing at all indicating more items are at the bottom. The last one isn't even cut off half-way or something.

![image](https://user-images.githubusercontent.com/4075314/113512102-1f89e900-9531-11eb-8951-3cef70dbdebe.png)

**Comment by JeremyWuuuuu** [comment]
When users use MacOS, it is its default option that only show scrollbar when you are scrolling and you can modify that in System Preference, but on Windows its default setting is always show the scrollbar. 
But I think you made your point, we can add an option for that.

**Comment by Giwayume** [comment]
Yeah I know OSX does this by default, Apple's design team makes a combination of good and bad usability decisions.

**Comment by JeremyWuuuuu** [comment]
> Yeah I know OSX does this by default, Apple's design team makes a combination of good and bad usability decisions.

Aye, we can make this attribute optional in order to make better experience.
