### ISSUE TITLE
[Style] 在nuxt中如何使用@forward来覆盖sass变量？

### ISSUE THREAD

**Issue by shaojiankui** [element-plus/element-plus#17517]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `macos`
- Build Tool: `Nuxt`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

// assets/css/element/index.scss
$test-color: red;
$--colors: (
  'primary': (
    'base': green
  ),
  'success': (
    'base': #21ba45
  ),
  'warning': (
    'base': #f2711c
  ),
  'danger': (
    'base': #db2828
  ),
  'error': (
    'base': #db2828
  ),
  'info': (
    'base': #42b8dd
  )
);

// we can add this to custom namespace, default is 'el'
// @forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
//   $namespace: 'ep'
// );

// You should use them in scss, because we calculate it by sass.
// comment next lines to use default color
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  // do not use same name, it will override.
  $colors: $--colors,
  $button-padding-horizontal: ('default': 50px)
);

// if you want to import all
// @use "element-plus/theme-chalk/src/index.scss" as *;

// You can comment it to hide debug info.
// @debug $--colors;

// custom dark variables
@use './dark.scss';

vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "~/assets/css/element/index.scss" as *;'
        }
      }
    }
  }

### What is Expected?

期望可以对scss变量进行重写

### What is actually happening?

无效果，但是index.scss中的普通变量可以被全局引用到说明additionalData生效了。

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
在 nuxt 覆盖样式的使用和普通 vue 是相同的
你可以参考 https://github.com/element-plus/element-plus-nuxt-starter

**Comment by shaojiankui** [comment]
> 在 nuxt 覆盖样式的使用和普通 vue 是相同的 你可以参考 https://github.com/element-plus/element-plus-nuxt-starter

就是直接参考的这个。只是引用方式不一样。 普通的变量都生效了，就是这个forward不生效 很奇怪
nuxt.config.ts
vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "~/assets/css/element/index.scss" as *;'
        }
      }
    }
  }

**Comment by shaojiankui** [comment]
scss: {
          // additionalData: '@use "~/assets/css/element/index.scss" as *;'
          additionalData: `@use "~/assets/css/element/index.scss" as element;`
        }
        
        知道问题了，as *不行，得as element

**Comment by shaojiankui** [comment]
有个新问题。demo中的element plus 2.4.4,升级最新 element-plus@2.7.6 后，运行demo会报这个错。

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
161│     border-radius: $border-radius;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 161:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 75:3           @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
159 │     padding: $padding-vertical $padding-horizontal;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 159:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 287:7          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 107:7   m()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 273:5          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
160 │     font-size: $font-size;
    │     ^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 160:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 287:7          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 107:7   m()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 273:5          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Warning: 4 repetitive deprecation warnings omitted.

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ╷
22 │ ┌       &::-webkit-inner-spin-button,
23 │ │       &::-webkit-outer-spin-button {
24 │ │         margin: 0;
25 │ │         -webkit-appearance: none;
26 │ │       }
   │ └─── nested rule
27 │         text-align: center;
   │         ^^^^^^^^^^^^^^^^^^ declaration
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/input-number.scss 27:7   @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5  b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/input-number.scss 7:1    root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
22  │ ┌       &::-webkit-inner-spin-button,
23  │ │       &::-webkit-outer-spin-button {
24  │ │         margin: 0;
25  │ │         -webkit-appearance: none;
26  │ │       }
    │ └─── nested rule
... │
28  │         line-height: 1;
    │         ^^^^^^^^^^^^^^ declaration
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/input-number.scss 28:7   @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5  b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/input-number.scss 7:1    root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
175 │ ┌       .is-icon,
176 │ │       .is-text {
177 │ │         font-size: 12px;
178 │ │         color: getCssVar('color-white');
179 │ │         user-select: none;
180 │ │         @include utils-ellipsis;
181 │ │       }
    │ └─── nested rule
182 │ ┌       padding: 0 #{map.get($switch-content-padding, 'default')} 0 calc(#{map.get(
183 │ │               $switch-button-size,
184 │ │               'default'
185 │ │             )} + 2px);
    │ └─────────────────────^ declaration
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/switch.scss 182:7        @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 88:9  e()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/switch.scss 147:3        @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5  b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/switch.scss 82:1         root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
159│     padding: $padding-vertical $padding-horizontal;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 159:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 75:3           @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
160│     font-size: $font-size;
   │     ^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 160:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 75:3           @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
161│     border-radius: $border-radius;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 161:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 75:3           @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
159 │     padding: $padding-vertical $padding-horizontal;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 159:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 287:7          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 107:7   m()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 273:5          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss
160 │     font-size: $font-size;
    │     ^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/_button.scss 160:3  button-size()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 287:7          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 107:7   m()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 273:5          @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5    b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button.scss 23:1           root stylesheet

Warning: 4 repetitive deprecation warnings omitted.

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button-group.scss
9  │     display: inline-block;
   │     ^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/utils.scss
10 │ ┌     #{$selector}::after {
11 │ │       clear: both;
12 │ │     }
   │ └─── nested rule
   ╵
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button-group.scss 9:3    @content
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 60:5  b()
    node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button-group.scss 7:1    root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/button-group.scss
10 │     vertical-align: middle;
   │     ^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/.pnpm/element-plus@2.7.6_vue@3.3.13_typescript@5.3.3_/node_modules/element-plus/theme-chalk/src/mixins/utils.scss
10 │ ┌     #{$selector}::after {
11 │ │       clear: both;
12 │ │     }
   │ └─── nested rule
   ╵

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/issues/17487

**Comment by shaojiankui** [comment]
> #17487

yarn add sass@1.77.6

downgrade SASS this works
