### ISSUE TITLE
[Component] [dialog] input组件，通过focus事件触发打开Dialog组件，在Dialog组件中使用footer插槽自定义了底部按钮，点击底部“取消按钮”关闭不了Dialog弹窗

### ISSUE THREAD

**Issue by UrHomeCn** [element-plus/element-plus#17512]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0XG4gICAgcmVmPVwiaW5wdXRSZWZcIlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgQGZvY3VzPVwiaGFuZGxlRm9jdXMxXCJcbiAgPjwvZWwtaW5wdXQ+XG4gIDxlbC1kaWFsb2dcbiAgICB2LW1vZGVsPVwib3V0ZXJWaXNpYmxlXCJcbiAgICA6Y2xvc2Utb24tY2xpY2stbW9kYWw9XCJmYWxzZVwiXG4gICAgd2lkdGg9XCI4MDBcIlxuICAgIGNsb3NlLW9uLXByZXNzLWVzY2FwZVxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyB0aGUgb3V0ZXIgRGlhbG9nPC9zcGFuPlxuICAgIDxzcGFuPlRoaXMgaXMgdGhlIG91dGVyIERpYWxvZzwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxkaXYgY2xhc3M9XCJwb3B1cC1zZWxlY3QtZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uXG4gICAgICAgICAgQGNsaWNrPVwiaGFuZGxlQ2xvYXNlXCJcbiAgICAgICAgPlxuICAgICAgICAgIDxzcGFuIHN0eWxlPVwiY29sb3I6ICMzMzNcIj7lj5bmtog8L3NwYW4+XG4gICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xubGV0IHZhbHVlID0gcmVmKCcnKTtcbmNvbnN0IG91dGVyVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGhhbmRsZUZvY3VzMSA9IChlOiBhbnkpID0+IHtcbiAgb3V0ZXJWaXNpYmxlLnZhbHVlID0gdHJ1ZTtcbn07XG5jb25zdCBoYW5kbGVDbG9hc2UgPSAoKSA9PiB7XG4gIG91dGVyVmlzaWJsZS52YWx1ZSA9IGZhbHNlXG59O1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

打开复现环境，点击input输入框，点击dialog弹窗的取消按钮

### What is Expected?

关闭dialog

### What is actually happening?

关闭后又自动打开了

### Additional comments

_(empty)_

**Comment by qingyiay** [comment]
focus事件里执行完打开dialog后，让这个输入框失去焦点就好了

**Comment by joooooooojo** [comment]
直接用 ref 修改 dialog 实例的 visible 属性就行了
`dialogRef.value.visible = false`

**Comment by chenxch** [comment]
这是一个合理的设计，关闭弹窗后焦点还原。你可以按照 @qingyiay 提供的方案解决你的问题。

**Comment by UrHomeCn** [comment]
好的，谢谢

**Comment by UrHomeCn** [comment]
但是在大量内部设计器页面，需要在dialog打开和关闭时，input都失去焦点，有办法在dialog组件层面做到吗
