### ISSUE TITLE
[Component] [select-v2] 使用loading，修改options的值，输入框显示成value的值而不是label

### ISSUE THREAD

**Issue by threethieves** [element-plus/element-plus#17510]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKFsxLDJdKVxuY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoW1xuICB7bGFiZWw6ICdhYWEnLCB2YWx1ZTogMX0sXG4gIHtsYWJlbDogJ2JiYicsIHZhbHVlOiAyfSxcbiAge2xhYmVsOiAnY2NjJywgdmFsdWU6IDN9LFxuICB7bGFiZWw6ICdkZGQnLCB2YWx1ZTogNH1cbl0pXG5jb25zdCBhZGRPcHRpb25zID0gKCkgPT4ge1xubG9hZGluZy52YWx1ZSA9IGZhbHNlXG5zZXRUaW1lb3V0KCgpPT57XG4gIG9wdGlvbnMudmFsdWUgPSBbXG4gICAgLi4ub3B0aW9ucy52YWx1ZSwgXG4gICAge2xhYmVsOiAnZWVlJywgdmFsdWU6IDV9XG4gIF1cbiAgbG9hZGluZy52YWx1ZSA9IHRydWVcbn0sMTApXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLXNlbGVjdC12MiBcbiAgICB2LW1vZGVsPVwibXNnXCIgXG4gICAgOmxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIiBcbiAgICBtdWx0aXBsZSBcbiAgICA6bWF4LWNvbGxhcHNlLXRhZ3M9XCI0XCJcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgZmlsdGVyYWJsZVxuICAgIGNsZWFyYWJsZS8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiYWRkT3B0aW9uc1wiPuWinuWKoDwvZWwtYnV0dG9uPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

打开复现环境，点击增加按钮，输入框里的值会变成value的值

### What is Expected?

显示label的值

### What is actually happening?

显示value的值

### Additional comments

_(empty)_

**Comment by btea** [comment]
修改完成，把`loading`改成false就正常了。[示例](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKFsxLDJdKVxuY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoW1xuICB7bGFiZWw6ICdhYWEnLCB2YWx1ZTogMX0sXG4gIHtsYWJlbDogJ2JiYicsIHZhbHVlOiAyfSxcbiAge2xhYmVsOiAnY2NjJywgdmFsdWU6IDN9LFxuICB7bGFiZWw6ICdkZGQnLCB2YWx1ZTogNH1cbl0pXG5jb25zdCBhZGRPcHRpb25zID0gKCkgPT4ge1xubG9hZGluZy52YWx1ZSA9IHRydWVcbnNldFRpbWVvdXQoKCk9PntcbiAgb3B0aW9ucy52YWx1ZSA9IFtcbiAgICAuLi5vcHRpb25zLnZhbHVlLCBcbiAgICB7bGFiZWw6ICdlZWUnLCB2YWx1ZTogNX1cbiAgXVxuICBsb2FkaW5nLnZhbHVlID0gZmFsc2Vcbn0sMTApXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLXNlbGVjdC12MiBcbiAgICB2LW1vZGVsPVwibXNnXCIgXG4gICAgOmxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIiBcbiAgICBtdWx0aXBsZSBcbiAgICA6bWF4LWNvbGxhcHNlLXRhZ3M9XCI0XCJcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgZmlsdGVyYWJsZVxuICAgIGNsZWFyYWJsZS8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiYWRkT3B0aW9uc1wiPuWinuWKoDwvZWwtYnV0dG9uPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)
