### ISSUE TITLE
[Style] [input] input origin raw disabled effect overwrite element ui style and user customize color

### ISSUE THREAD

**Issue by Mowmowj** [element-plus/element-plus#17519]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.6.3`
- Browser / OS: `IOS/Chrome/Edge/Safari`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Link]()

### Steps to reproduce

1. use ios phone
2. use element-input components
3. setuup element-input as readonly and disabled
4. set blue for input disabled color
4. look the input color it's covered by a grey

### What is Expected?

use user's style

### What is actually happening?

input origin raw disabled effect overwrite element ui style and user customize color

### Additional comments

_(empty)_

**Comment by TryChai** [comment]
而且 那个内存也蹭蹭蹭的上涨 绝对有问题
