### ISSUE TITLE
[Docs] [segmented] Documentation error for Segement component

### ISSUE THREAD

**Issue by TangPeicong** [element-plus/element-plus#17534]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-segmented`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgb3B0aW9uczEgPSByZWYoWydzZWcxJywgJ3NlZzInXSlcbmNvbnN0IHZhbHVlMSA9IHJlZihvcHRpb25zMS52YWx1ZVswXSlcbmNvbnN0IG9wdGlvbnMyID0gcmVmKFsnc2VnMScsICdzZWcyJ10pXG5jb25zdCB2YWx1ZTIgPSByZWYob3B0aW9uczIudmFsdWVbMF0pXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsdWUpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VnbWVudGVkIDpjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiB2LW1vZGVsPVwidmFsdWUxXCIgOm9wdGlvbnM9XCJvcHRpb25zMVwiIC8+XG4gIDxiciAvPlxuICA8YnIgLz5cbiAgPGVsLXNlZ21lbnRlZCA6b25DaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiB2LW1vZGVsPVwidmFsdWUyXCIgOm9wdGlvbnM9XCJvcHRpb25zMlwiIC8+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj5cbiAgICAgIDxFbGVtZW50UGx1cyAvPlxuICAgIDwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as epVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
const options1 = ref(['seg1', 'seg2'])
const value1 = ref(options1.value[0])
const options2 = ref(['seg1', 'seg2'])
const value2 = ref(options2.value[0])
const handleChange = (value) => {
  console.log(value)
}
</script>

<template>
  <el-segmented :change="handleChange" v-model="value1" :options="options1" />
  <br />
  <br />
  <el-segmented :onChange="handleChange" v-model="value2" :options="options2" />
  <p>
    <el-icon color="var(--el-color-primary)">
      <ElementPlus />
    </el-icon>
    Element Plus {{ epVersion }} + Vue {{ vueVersion }}
  </p>
</template>

### What is Expected?

In the document, the event that is triggered when the selected value changes is "change"

### What is actually happening?

The event that is triggered when the selected value changes is "onChange"

### Additional comments

_(empty)_

**Comment by wzc520pyfm** [comment]
The event binding method is `<el-segmented @change="handleChange" />`

**Comment by TangPeicong** [comment]
thanks

**Comment by TangPeicong** [comment]
> The event binding method is `<el-segmented @change="handleChange" />`

thanks
