### ISSUE TITLE
[Docs] [progress] 文档内容显示错误

### ISSUE THREAD

**Issue by fufu223** [element-plus/element-plus#17547]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-progress`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/progress.html)

### Steps to reproduce

打开网页查看https://element-plus.org/zh-CN/component/progress.html

### What is Expected?

无

### What is actually happening?

无

### Additional comments

el-progress进度条的动画进图条案例属性写错了，显示属性为`intermediate `,实际属性为`indeterminate`

![image](https://github.com/user-attachments/assets/92a9d8b3-4578-4e6b-9f46-2a40e7341bed)

**Comment by chenxch** [comment]
感谢反馈，crowdin上已修正
