### ISSUE TITLE
[Component] [image] Cannot trigger click when image error occurs

### ISSUE THREAD

**Issue by zhixiaotong** [element-plus/element-plus#17540]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.7`
- Browser / OS: `chrome 126.0.6478.127`
- Build Tool: `Vite`

### Related Component

- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8taW1hZ2VfX2Vycm9yXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmxvY2tcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPk5vIEVycm9yPC9zcGFuPlxuICAgICAgPGVsLWltYWdlIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9lLzVkLzRhNzMxYTkwNTk0YTRhZjU0NGMwYzI1OTQxMTcxanBlZy5qcGVnXCIgQGNsaWNrPVwiaGFuZGxlUHJpbnRcIiAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+RGVmYXVsdDwvc3Bhbj5cbiAgICAgIDxlbC1pbWFnZSBAY2xpY2s9XCJoYW5kbGVQcmludFwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImJsb2NrXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5DdXN0b208L3NwYW4+XG4gICAgICA8ZWwtaW1hZ2UgQGNsaWNrLmNhcHR1cmU9XCJoYW5kbGVQcmludFwiPlxuICAgICAgICA8dGVtcGxhdGUgI2Vycm9yPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJpbWFnZS1zbG90XCI+XG4gICAgICAgICAgICA8ZWwtaWNvbj48aWNvbi1waWN0dXJlIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC1pbWFnZT5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgUGljdHVyZSBhcyBJY29uUGljdHVyZSB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5mdW5jdGlvbiBoYW5kbGVQcmludChlOiBNb3VzZUV2ZW50KSB7XG4gIGNvbnNvbGUubG9nKGUudGFyZ2V0KTtcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmRlbW8taW1hZ2VfX2Vycm9yIC5ibG9jayB7XG4gIHBhZGRpbmc6IDMwcHggMDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBib3JkZXItcmlnaHQ6IHNvbGlkIDFweCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gIHdpZHRoOiA0OSU7XG4gIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gIHZlcnRpY2FsLWFsaWduOiB0b3A7XG59XG4uZGVtby1pbWFnZV9fZXJyb3IgLmRlbW9uc3RyYXRpb24ge1xuICBkaXNwbGF5OiBibG9jaztcbiAgY29sb3I6IHZhcigtLWVsLXRleHQtY29sb3Itc2Vjb25kYXJ5KTtcbiAgZm9udC1zaXplOiAxNHB4O1xuICBtYXJnaW4tYm90dG9tOiAyMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5lbC1pbWFnZSB7XG4gIHBhZGRpbmc6IDAgNXB4O1xuICBtYXgtd2lkdGg6IDMwMHB4O1xuICBtYXgtaGVpZ2h0OiAyMDBweDtcbiAgd2lkdGg6IDEwMCU7XG4gIGhlaWdodDogMjAwcHg7XG59XG5cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICB3aWR0aDogMTAwJTtcbiAgaGVpZ2h0OiAxMDAlO1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1lbC1maWxsLWNvbG9yLWxpZ2h0KTtcbiAgY29sb3I6IHZhcigtLWVsLXRleHQtY29sb3Itc2Vjb25kYXJ5KTtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuLmRlbW8taW1hZ2VfX2Vycm9yIC5pbWFnZS1zbG90IC5lbC1pY29uIHtcbiAgZm9udC1zaXplOiAzMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

如题

### What is Expected?

error时，也应该触发click事件

### What is actually happening?

没有触发，仅正常返回的图片可触发click

console并没有打印输出

### Additional comments

需求：当验证码图片报错时，点击会再次请求新的验证码。

**Comment by webvs2** [comment]
Can you directly use the `errer slot` to achieve it

**Comment by zhixiaotong** [comment]
> Can you directly use the `errer slot` to achieve it

Of course, it's simple.But the point should be that it should respond to click regardless of whether it is loaded incorrectly, rather than ignoring it in another way.This problem still exists.

**Comment by zhixiaotong** [comment]
After reading the source code, I found that the image component sets the attribute inheritance inheritAttrs to false, and explicitly uses useAttrs to bind the variable to the img element instead of the outer div. This will cause the outer layer to fail to get the click, contextmenu and other events normally. Only when the inner img element is loaded correctly can the event bubble mechanism be used to capture the event correctly. I don't think useAttrs should be bound to the img element directly, so that although some properties passed to the image can be directly obtained, some events passed externally cannot be triggered when the image is loaded (placeholder slot) or when the image fails to load (error slot).


In addition, I believe that the solution to this problem should not be to add click to the el-image and then register the same click on the error slot.


### solution


- `inheritAttrs: true`, but there are only a few attributes of the `img` element inside, just register them one by one.
- Without changing `inheritAttrs`, the code maintains event-related property objects separately, `v-bind="containerAttrs"` is bound to the external container, and'img' unbinds these events to avoid multiple triggers.


@qiang, what do you think? If you agree, I will submit pr to solve it, thanks.

**Comment by tolking** [comment]
TIP

The `useAttrs` function has a parameter `excludeListeners`

**Comment by zhixiaotong** [comment]
> TIP
> 
> The `useAttrs` function has a parameter `excludeListeners`

Thx,i didnt know before.
