### ISSUE TITLE
[Feature Request] no 'ua' locale after installing element plus via cli plugin

### ISSUE THREAD

**Issue by demosglok** [element-plus/element-plus#1756]
### Existing Component
Yes

### Component Name
Locale

### Description
ua.js is missing in element-plus/lib/locale/lang/ after i install element plus via cli plugin.

this could be a bug or just missing transaltion. 

if the issue is with translations, i'm happy to provide them, i'm native ukrainian speaker

**Comment by JeremyWuuuuu** [comment]
Sure! Simply open a PR and add me as reviewer.

**Comment by kooriookami** [comment]
There's a uk.js file.

**Comment by demosglok** [comment]
@kooriookami  i was talking about ua.js (ukraine) not uk.js (united kingdom)

i missed this item since i wrote but now as i get email, i'll create ua.js with ukrainian translations

**Comment by kooriookami** [comment]
https://github.com/element-plus/element-plus/blob/dev/packages/locale/lang/uk.ts
Look at this, it's ukrainian, you mean the name of the file should be ua.js?
