### ISSUE TITLE
[Component] [table, table-column] When the width of the column is adjusted, the width of the table header and the content area are different

### ISSUE THREAD

**Issue by yangnanle** [element-plus/element-plus#17590]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.4`
- Browser / OS: `window64`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-ifk4mc?file=src%2FApp.vue)

### Steps to reproduce

Once the item is open, drag the list width

### What is Expected?

When the user drags the width of the column, the width of the table header and the content should be the same

### What is actually happening?

Header and content width do not match, will be confused

### Additional comments

_(empty)_
![image](https://github.com/user-attachments/assets/462fc6fe-663e-4b72-b2ec-cf3567e3bd3f)

**Comment by warmthsea** [comment]
It looks like this line of CSS is causing it.

![screenshots](https://github.com/user-attachments/assets/43a3e11f-4271-49db-a7b2-97969459df08)

**Comment by yangnanle** [comment]
> It looks like this line of CSS is causing it.
> 
> ![screenshots](https://private-user-images.githubusercontent.com/45450994/354947992-43a3e11f-4271-49db-a7b2-97969459df08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzE1NzgsIm5iZiI6MTcyMjgzMTI3OCwicGF0aCI6Ii80NTQ1MDk5NC8zNTQ5NDc5OTItNDNhM2UxMWYtNDI3MS00OWRiLWE3YjItOTc5Njk0NTlkZjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmY4NTQ2NDMzM2M3MTJhYWE5Zjk5MWYzZDM5MWI5MDM2MGFjN2E2YmIyNTE2MGQwMzU0YTU3YTc2ZmJmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9gaDRgK8A9zyrobILxDkvhpKaVnjd3bWA-EDd3wCoU) [ ![screenshots](https://private-user-images.githubusercontent.com/45450994/354947992-43a3e11f-4271-49db-a7b2-97969459df08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzE1NzgsIm5iZiI6MTcyMjgzMTI3OCwicGF0aCI6Ii80NTQ1MDk5NC8zNTQ5NDc5OTItNDNhM2UxMWYtNDI3MS00OWRiLWE3YjItOTc5Njk0NTlkZjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmY4NTQ2NDMzM2M3MTJhYWE5Zjk5MWYzZDM5MWI5MDM2MGFjN2E2YmIyNTE2MGQwMzU0YTU3YTc2ZmJmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9gaDRgK8A9zyrobILxDkvhpKaVnjd3bWA-EDd3wCoU) ](https://private-user-images.githubusercontent.com/45450994/354947992-43a3e11f-4271-49db-a7b2-97969459df08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzE1NzgsIm5iZiI6MTcyMjgzMTI3OCwicGF0aCI6Ii80NTQ1MDk5NC8zNTQ5NDc5OTItNDNhM2UxMWYtNDI3MS00OWRiLWE3YjItOTc5Njk0NTlkZjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmY4NTQ2NDMzM2M3MTJhYWE5Zjk5MWYzZDM5MWI5MDM2MGFjN2E2YmIyNTE2MGQwMzU0YTU3YTc2ZmJmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9gaDRgK8A9zyrobILxDkvhpKaVnjd3bWA-EDd3wCoU) [ ](https://private-user-images.githubusercontent.com/45450994/354947992-43a3e11f-4271-49db-a7b2-97969459df08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzE1NzgsIm5iZiI6MTcyMjgzMTI3OCwicGF0aCI6Ii80NTQ1MDk5NC8zNTQ5NDc5OTItNDNhM2UxMWYtNDI3MS00OWRiLWE3YjItOTc5Njk0NTlkZjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmY4NTQ2NDMzM2M3MTJhYWE5Zjk5MWYzZDM5MWI5MDM2MGFjN2E2YmIyNTE2MGQwMzU0YTU3YTc2ZmJmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9gaDRgK8A9zyrobILxDkvhpKaVnjd3bWA-EDd3wCoU)

Exactly. Thank you!
