### ISSUE TITLE
[Component] [input] <el-input v-model="ruleForm.name"  type="password"  show-password="true" /> 导致校验规则的min，max失效

### ISSUE THREAD

**Issue by deliamurray2001** [element-plus/element-plus#17593]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-alpha.2`
- Element Plus Version: `2.7.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html)

### Steps to reproduce

 表单<el-form-item label="Activity name" prop="name">
      <el-input v-model="ruleForm.name"  type="password"  show-password="true" />
    </el-form-item>
 校验规则 name: [
    { required: true, message: 'Please input Activity name', trigger: 'blur' },
    { min: 5, max: 20, message: 'Length should be 3 to 5', trigger: 'blur' },
  ],
type="password"  show-password="true"两个属性一起用

### What is Expected?

应该3-5长度是可以通过

### What is actually happening?

输入3-5长度内容，在【点击查看密码】那个按钮后会提示Length should be 3 to 5，有效长度不能通过校验

### Additional comments

_(empty)_

**Comment by deliamurray2001** [comment]
![20240719003959](https://github.com/user-attachments/assets/32928cbb-68ec-452f-bb25-f805bbc2d522)
![Uploading 20240719004155.png…]()
在案例中可以复现

**Comment by makedopamine** [comment]
```{ min: 5, max: 20, message: 'Length should be 3 to 5', trigger: 'blur' }```
应该写成
```{ min: 3, max: 5, message: 'Length should be 3 to 5', trigger: 'blur' }```

**Comment by deliamurray2001** [comment]
> `{ min: 5, max: 20, message: 'Length should be 3 to 5', trigger: 'blur' }` 应该写成 `{ min: 3, max: 5, message: 'Length should be 3 to 5', trigger: 'blur' }`

实际上是用的min: 3, max: 5  ，应该是我本地依赖版本2.7.6的问题，升级到2.7.7这个问题就没了 非常感谢

**Comment by deliamurray2001** [comment]
[resolved](http://www.youdao.com/w/resolved/#keyfrom=E2Ctranslation)
