### ISSUE TITLE
[Component] [drawer, message-box] 使用Drawer组件之后执行点击关闭Drawer按钮，无法点击MesageBox的Confirm或Cancel

### ISSUE THREAD

**Issue by WenisOK** [element-plus/element-plus#17601]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.33`
- Element Plus Version: `2.7.6`
- Browser / OS: `Chrome 126 / macOS 14.5`
- Build Tool: `Nuxt`

### Related Component

- `el-drawer`
- `el-message-box`

### Reproduction Link

[Github Repo](https://github.com/WenisOK/element-plus-error-report-1)

### Steps to reproduce

1. 点击关闭drawer按钮。
2. 弹出MessageBox以让用户点击Confirm或者Cancel。
3. 执行后续Confirm或Cancel操作

### What is Expected?

正常出现MesssageBox

### What is actually happening?

+ **Element-plus playground 并不会复现此故障**
+ MessageBox被Drawer的Modal遮挡
![](https://pic.fatcattech.cn/imgs/2024/07/e225843373da1294.png)

### Additional comments

_(empty)_

**Comment by btea** [comment]
Looks like a rendering timing issue, maybe you should make sure the dialog is rendered after the drawer.

**Comment by WenisOK** [comment]
> Looks like a rendering timing issue, maybe you should make sure the dialog is rendered after the drawer.

I think so, but I have ensured that the drawer is rendered first by clicking the close button of the drawer or by clicking Modal.

**Comment by WenisOK** [comment]
It doesn't always have this bug, it occasionally does.

**Comment by btea** [comment]
You can set `appendTo: document.querySelector('.el-overlay')` in `ElMessageBox`.

**Comment by OVYVO** [comment]
> You can set `appendTo: document.querySelector('.el-overlay')` in `ElMessageBox`.

That's right, this is the correct solution
