### ISSUE TITLE
[Bug Report] The doc of TimePicker attributes has a mistake

### ISSUE THREAD

**Issue by angela-1** [element-plus/element-plus#1761]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
debian 10.8, edge  89.0.774.68

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/

### Steps to reproduce
open the links and look at the line below `range-separator`, the time format.
I think the param name is `format`, not `string` like the param in DatePicker.
It must be a mistake.

Because I can not paste this link to The Reproduction, so I paste it here
https://element-plus.gitee.io/#/zh-CN/component/time-picker#attributes

### What is Expected?
the param name should be `format`

### What is actually happening?
the param name is `string`

**Comment by JeremyWuuuuu** [comment]
Yep, definitely a bug, you interested in fix this?

**Comment by angela-1** [comment]
I have made a pr. Because I just know chinese and english, I just fix this two language doc. @JeremyWuuuuu

**Comment by 0song** [comment]
fixed in #1767
