### ISSUE TITLE
[Docs] [collapse] the default value of accordion prop should be false 

### ISSUE THREAD

**Issue by chouchouji** [element-plus/element-plus#17613]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.33`
- Element Plus Version: `2.7.7`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-collapse`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/collapse.html)

### Steps to reproduce

open the cn docs

### What is Expected?

the default value should be false

### What is actually happening?

it is boolean

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/bb426193-98e2-4208-bbe1-cd6140848a38)

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/b7b589ba-c4d1-4319-a243-7426379c9f03)

I edited it

**Comment by btea** [comment]
Thanks for the feedback, it has been updated.
