### ISSUE TITLE
[Style] [message-box] 使用自动导入组件，单独使用MessageBox时，缺少el-overlay样式

### ISSUE THREAD

**Issue by BxyNeko** [element-plus/element-plus#17642]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.33`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome 126.0.6478.182`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Link](https://gitee.com/iesot/element-plus-issue)

### Steps to reproduce

<script setup>
import { ElMessageBox } from 'element-plus'

ElMessageBox.confirm(
  'xxx?',
  '提示',
  {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning',
  },
).then(() => {

}).catch(() => {})
</script>

### What is Expected?

增加el-overlay样式

### What is actually happening?

增加el-overlay样式

### Additional comments

_(empty)_

**Comment by Fuphoenixes** [comment]
<img width="544" alt="image" src="https://github.com/user-attachments/assets/9ea11dcf-b190-44de-b451-d496c23be895">

你使用了`unplugin-auto-import/vite`,就不需要引入了，注释掉这行代码就行了。

**Comment by huangwenboha563** [comment]
> <img alt="image" width="544" src="https://private-user-images.githubusercontent.com/27912232/351550178-9ea11dcf-b190-44de-b451-d496c23be895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzczOTcsIm5iZiI6MTcyMjU3NzA5NywicGF0aCI6Ii8yNzkxMjIzMi8zNTE1NTAxNzgtOWVhMTFkY2YtYjE5MC00NGRlLWI0NTEtZDQ5NmMyM2JlODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1MzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OTgyN2EzOTlhNzg5N2I0Y2M3NmY1ZjAxZGEwMjE1NWQwZDgzYTk1ODE5ZDI1Njg5MTJjOWZhODZhNTZlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdO9Y7SLSs8wup4AT22w3fSnmCB1_BFnfXQO50GhA40">
> 你使用了`unplugin-auto-import/vite`,就不需要引入了，注释掉这行代码就行了。

经过测试你的回答是准确的，去掉这个Import就可以了，网上都是让单独再次引入样式的。
不过有个疑问，比如message组件，及时加了自动引入，再次引入样式也是不丢失的，为啥这个import会导致样式丢失
