### ISSUE TITLE
 官网换肤切换动画，在MAC环境下动画抖动闪烁

### ISSUE THREAD

**Issue by WilliamJonens** [element-plus/element-plus#17643]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.4.33`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome 126.0.6478.182`
- Build Tool: `Other`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/#/zh-CN)

### Steps to reproduce

官网右上角换肤功能动画，在MAC电脑中，切换时，会伴随闪烁抖动等问题

### What is Expected?

兼容动画的抖动问题

### What is actually happening?

。

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Everything is normal. Please provide more information, such as a screen recording.

**Comment by WilliamJonens** [comment]
https://github.com/user-attachments/assets/6206e19e-0b09-4666-8b8c-e5f244a5e5f7

**Comment by chenxch** [comment]
Have you tried Incognito mode?

**Comment by WilliamJonens** [comment]
how to switch Incognito mode?

**Comment by chenxch** [comment]
https://support.google.com/chrome/answer/95464?hl=zh-Hans&co=GENIE.Platform%3DDesktop

**Comment by WilliamJonens** [comment]
Still the same issue, I don't think it has much to do with incognito mode.

**Comment by WilliamJonens** [comment]
How can we avoid this screen flickering issue? I want to implement this effect on our website, but I noticed that on Mac computers, this flickering occurs during transitions.

**Comment by chenxch** [comment]
The specific reason is still unknown. I have not been able to reproduce the problem on several devices, and no one has reported this problem yet. Maybe I need to see if anyone else needs the same problem or more information.
