### ISSUE TITLE
[Component] [tabs] 使用tabs标签页组件，在tab-click事件中打印v-model绑定的值为之前的值

### ISSUE THREAD

**Issue by July-Month** [element-plus/element-plus#17704]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome 125.0.6422.78/ Windows 10 专业版`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0YWJWYWx1ZSA9IHJlZigncHVibGlzaFRpbWUnKVxuY29uc3QgaGFuZGxlU29ydEZpZWxkID0gKGUpID0+IHtcbiAgY29uc29sZS5sb2codGFiVmFsdWUudmFsdWUpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwidGFiVmFsdWVcIiBAdGFiLWNsaWNrPVwiaGFuZGxlU29ydEZpZWxkXCI+XG4gICAgICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIuacgOaWsOWVhuWTgVwiIG5hbWU9XCJwdWJsaXNoVGltZVwiPjwvZWwtdGFiLXBhbmU+XG4gICAgICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIuacgOmrmOS6uuawlFwiIG5hbWU9XCJvcmRlck51bVwiPjwvZWwtdGFiLXBhbmU+XG4gICAgICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIuivhOiuuuacgOWkmlwiIG5hbWU9XCJldmFsdWF0ZU51bVwiPjwvZWwtdGFiLXBhbmU+XG4gICAgICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<script setup>
import { ref, version as vueVersion } from 'vue'
import { version as epVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const tabValue = ref('publishTime')
const handleSortField = (e) => {
  console.log(tabValue.value)
}
</script>

<template>
  <el-tabs v-model="tabValue" @tab-click="handleSortField">
        <el-tab-pane label="最新商品" name="publishTime"></el-tab-pane>
        <el-tab-pane label="最高人气" name="orderNum"></el-tab-pane>
        <el-tab-pane label="评论最多" name="evaluateNum"></el-tab-pane>
      </el-tabs>
</template>

### What is Expected?

在tab-click的事件中打印绑定的值应该为点击的tab所绑定的值

### What is actually happening?

实际在tab-click的事件中打印绑定的值为上一个tab的值

### Additional comments

_(empty)_

**Comment by dadaguai-git** [comment]
流程是先点击后切换，`tab-change` 是点击的时候触发，要获取点击后数据使用 `tab-change` 事件 [#7628](https://github.com/element-plus/element-plus/issues/7682)

**Comment by zhixiaotong** [comment]
> 流程是先点击后切换，`tab-click` 是点击的时候触发，要获取点击后数据使用 `tab-change` 事件 [#7628](https://github.com/element-plus/element-plus/issues/7682)

他提的应该没问题的，`tabClick`是在设置值之后触发的。
![image](https://github.com/user-attachments/assets/5b3d3483-24e3-42a2-a661-82118d725b84)

**Comment by btea** [comment]
The current logic is correct, we should keep the original event dispatch order, refer to https://github.com/element-plus/element-plus/issues/10519#issuecomment-1307386732

**Comment by zhixiaotong** [comment]
> The current logic is correct, we should keep the original event dispatch order, refer to https://github.com/element-plus/element-plus/issues/10519#issuecomment-1307386732

看到了，两年前就有异议了（好家伙），之前谈论的分歧在于没有传递beforeLeave的处理，由于该函数是异步，虽然设置值逻辑在前面，还是无法在主流程完成时获得最新的值。但默认情况没有传递before钩子时，这样异步是否合理？

**Comment by btea** [comment]
@zhixiaotong 我认为保持目前逻辑比较好，如果按照你 pr 中进行修改，`tab-click` 和 `tab-change` 似乎就重复了。

**Comment by zhixiaotong** [comment]
> @zhixiaotong 我认为保持目前逻辑比较好，如果按照你 pr 中进行修改，`tab-click` 和 `tab-change` 似乎就重复了。

这个看你们的决定了，不会重复，change只会值更改时触发，但click不同，点一次就会触发一次。我把那个pr临时关闭了。

**Comment by zhixiaotong** [comment]
> > @zhixiaotong 我认为保持目前逻辑比较好，如果按照你 pr 中进行修改，`tab-click` 和 `tab-change` 似乎就重复了。
> 
> 这个看你们的决定了，不会重复，change只会值更改时触发，但click不同，点一次就会触发一次。我把那个pr临时关闭了。

其实这个存在争议性的，答案也不一定就是对的。

**Comment by btea** [comment]
我还是认为保持现状比较好，`tab-change` 完全能满足需求，而且做出逻辑调整，对于目前用户来说属于 breaking change，没必要。

**Comment by zhixiaotong** [comment]
> 我还是认为保持现状比较好，`tab-change` 完全能满足需求，而且做出逻辑调整，对于目前用户来说属于 breaking change，没必要。

嗯好的
