### ISSUE TITLE
[Component] [input] 在 input 内填充带 tabindex 的元素会导致 blur 事件触发中断，无法失去焦点

### ISSUE THREAD

**Issue by HaceraI** [element-plus/element-plus#17708]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.34`
- Element Plus Version: `2.7.8`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgZm9ybVZhbHVlcyA9IHJlZih7XG4gIG5hbWU6IFwiXCIsXG4gIGNvZGU6IFwiXCIsXG4gIHJlbWFyazogXCJcIlxufSk7XG5jb25zdCBmb3JtUnVsZXMgPSByZWFjdGl2ZSh7XG4gIG5hbWU6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiBcIuivt+i+k+WFpeWQjeensFwiLCB0cmlnZ2VyOiBcImJsdXJcIiB9XSxcbiAgY29kZTogW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6IFwi6K+36L6T5YWl57yW56CBXCIsIHRyaWdnZXI6IFwiYmx1clwiIH1dLFxufSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtVmFsdWVzXCIgOnJ1bGVzPVwiZm9ybVJ1bGVzXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWQjeensFwiIHByb3A9XCJuYW1lXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm1WYWx1ZXMubmFtZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIue8lueggVwiIHByb3A9XCJjb2RlXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm1WYWx1ZXMuY29kZVwiPlxuICAgICAgICA8dGVtcGxhdGUgI3N1ZmZpeD5cbiAgICAgICAgICA8c3BhbiB2LWlmPVwidHJ1ZVwiIHRhYmluZGV4PVwiMFwiPueCueaIkeeUn+aIkDwvc3Bhbj5cbiAgICAgICAgICA8ZWwtYnV0dG9uIHYtZWxzZSB0ZXh0PueCueaIkeeUn+aIkDwvZWwtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5aSH5rOoXCIgcHJvcD1cInJlbWFya1wiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtVmFsdWVzLnJlbWFya1wiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、将焦点聚焦到第一个输入框内；
2、使用Tab按键一直按到焦点聚焦于备注

### What is Expected?

1、离开后，因不在属于 is-focus
2、校验与错误信息能够正常提示

### What is actually happening?

1、离开后未失去焦点。
2、因未失去焦点，导致校验未刷新

### Additional comments

_(empty)_

[视频.webm](https://github.com/user-attachments/assets/3c172213-ebef-4c7e-8f99-3e27e63ed142)

**Comment by HaceraI** [comment]
当input拥有一个可被Tab选中的suffix (prefix未测试，估计是一样的)时，会出现该问题。

**Comment by zhixiaotong** [comment]
`prefix`没有问题，当按下tab触发blur时，由于suffix的内容还在input dom内，导致`blur`触发中断。

![image](https://github.com/user-attachments/assets/66731db7-9a66-4ced-a09f-88a3498a890b)

**Comment by HaceraI** [comment]
> 由于suffix的内容还在input dom内，导致`blur`触发中断。

🤔如果说suffix内容还在input dom内的话，prefix应该也算还在吧。我刚刚试了下prefix好像也存在这个问题.
这个问题是不是可以理解为：在 input内填充任何带 tabindex 的元素都会导致 blur事件触发中断.
![image](https://github.com/user-attachments/assets/73b8db3d-7f3f-4a25-83e1-f2582c583bb9)

**Comment by zhixiaotong** [comment]
![20240730134149_rec_](https://github.com/user-attachments/assets/0c4bc39b-e519-437b-843b-fae7b5efda8b)
`prefix`没有问题吧，我试了按tab没问题，这块原本设计应该是避免对prefix或suffix交互的，css也都做了禁止鼠标交互。

![image](https://github.com/user-attachments/assets/8387fbc1-f2d6-41b3-bc17-0a72863d022b)
源码中添加判断就没问题了，tab按到suffix自然就blur了。

这块影响还是较大的，我看了`select`、`select-v2`、`input`都用了focus相关逻辑，都具备`suffix slot`，是否被认定是问题需要修复？
@tolking @kooriookami

**Comment by HaceraI** [comment]
> `prefix`没有问题吧，我试了按tab没问题，这块原本设计应该是避免对prefix或suffix交互的，css也都做了禁止鼠标交互。

prefix试试按shift + tab，我这里是这样测试的

**Comment by zhixiaotong** [comment]
> > `prefix`没有问题吧，我试了按tab没问题，这块原本设计应该是避免对prefix或suffix交互的，css也都做了禁止鼠标交互。
> 
> prefix试试按shift + tab，我这里是这样测试的

反着走是有问题，原因和suffix一样

**Comment by HaceraI** [comment]
是的，这块依赖还是比较多的，我等等具体的解决方案吧，辛苦🙏

**Comment by tolking** [comment]
`el-input__wrapper` 内的元素属于一个整体（即 prefix + suffix + 原生input）。它们应该只能够有一个可聚焦元素。

**Comment by HaceraI** [comment]
> `el-input__wrapper` 内的元素属于一个整体（即 prefix + suffix + 原生input）。它们应该只能够有一个可聚焦元素。这样才好处理组件的聚焦和失焦事件。

这样的话，是不是有点不符合无障碍设计了。比如这种常用的验证码登录，就得需要通过鼠标+键盘的方式来完成登录操作

![image](https://github.com/user-attachments/assets/d8f99406-ccd0-4b7c-b310-7c429fe1d800)

**Comment by tolking** [comment]
可以先使用 append 插槽，我先尝试优化下焦点的处理
