### ISSUE TITLE
[Component] [select, option] wujie微前端方案加载微应用, 并且微应用使用element-plus时, vue重新实例化后elm组件报错

### ISSUE THREAD

**Issue by Lisheri** [element-plus/element-plus#17710]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.7`
- Browser / OS: `Chrome126.0.6478.183（正式版本） (arm64)/macos14.3.1`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[Github Repo](https://github.com/Lisheri/wujie_v3_elm_demo)

### Steps to reproduce

1. 启动main以及micro_app
2. 点击main的about加载一次微应用以及点击微应用about切换到对应页面
3. 点击home切出微应用
4. 再次加载微应用, 切换到微应用about页面, 操作select
5. 出现报错

### What is Expected?

正常加载并正常使用组件

### What is actually happening?

无法下拉并产生报错

### Additional comments

疑似vue重新实例化时, 前一次的element-plus产生遗留, 查找emitOptions找的已销毁的组件实例

![image](https://github.com/user-attachments/assets/b7c64c2b-0be0-4edb-a95c-a4524bbbf8e2)

**Comment by warmthsea** [comment]
可以录制一个如何操作的视频么，我启动起来项目但是不知道如何操作

**Comment by Lisheri** [comment]
> 可以录制一个如何操作的视频么，我启动起来项目但是不知道如何操作

可以, 稍等~

**Comment by Lisheri** [comment]
![20240731100918](https://github.com/user-attachments/assets/83bec353-1d07-4c78-a9ab-dcc16a7b7459)

**Comment by Lisheri** [comment]
https://github.com/user-attachments/assets/87f282ee-232e-4ace-8dc4-3776e340c40e

**Comment by warmthsea** [comment]
` <el-select v-model="value" :teleported="false">`
目前你可以通过  `:teleported="false"` 来临时解决你的问题
具体解决方案有待探讨

相关：
https://github.com/search?q=properties+of+null+%28reading+%27emitsOptions%27%29&type=issues
https://github.com/vuejs/core/issues?q=is%3Aissue++teleport+emitsOptions
https://github.com/vuejs/core/issues/8146

**Comment by Lisheri** [comment]
啊这, 是teleport影响的吗。。
不过这种改法有点难受哈哈, 毕竟接进来的微应用大部分页面都不太方便再去动一下= =

**Comment by warmthsea** [comment]
> 啊这, 是teleport影响的吗。。 不过这种改法有点难受哈哈, 毕竟接进来的微应用大部分页面都不太方便再去动一下= =

是的，[这个仓库](https://github.com/Tencent/wujie)关于  `element-ui`  `element-plus` 90% 的问题似乎都是受 `teleport` 影响

**Comment by Lisheri** [comment]
行~, 感谢感谢~, 我这想想能否全局处理下

**Comment by warmthsea** [comment]
> 行~, 感谢感谢~, 我这想想能否全局处理下

如果我有能力处理这个问题我会尽量处理，你也可以在 github 看看相关 issus 帮助解决这个问题

**Comment by tolking** [comment]
看起来像是重新进入时 teleport to 的目标节点不存在引起的。由于组件内部是动态生成这个节点的，我觉得可以可以提供一个静态的节点

// index.html

```html
<div id="app"></div>
<div id="el-popper-container-1024"></div>
```

然后注入 id 即可

// main.ts

```ts
import ElementPlus, { ID_INJECTION_KEY } from 'element-plus';
import 'element-plus/dist/index.css';

const render = () => {
  const router = createCurrentRouter();
  const instance = createApp(App);

  instance.use(createPinia());
  instance.use(router);
  instance.use(ElementPlus);
  instance.provide(ID_INJECTION_KEY, {
    prefix: 1024, // 需要与 html 中的 el-popper-container-1024 的后缀保持一致
    current: 0,
  });

  instance.mount('#app');
  return instance;
};
```

这样就能够确保每次进入时 teleport to 的目标节点存在，自然就不会出现错误了 [demo](https://stackblitz.com/edit/github-mbr2rr?file=wujie_elm_micro_app%2Findex.html)

**Comment by Lisheri** [comment]
> 看起来像是重新进入时 teleport to 的目标节点不存在引起的。由于组件内部是动态生成这个节点的，我觉得可以可以提供一个静态的节点
> 
> // index.html
> 
> ```
> <div id="app"></div>
> <div id="el-popper-container-1024"></div>
> ```
> 
> 然后注入 id 即可
> 
> // main.ts
> 
> ```ts
> import ElementPlus, { ID_INJECTION_KEY } from 'element-plus';
> import 'element-plus/dist/index.css';
> 
> const render = () => {
>   const router = createCurrentRouter();
>   const instance = createApp(App);
> 
>   instance.use(createPinia());
>   instance.use(router);
>   instance.use(ElementPlus);
>   instance.provide(ID_INJECTION_KEY, {
>     prefix: 1024, // 需要与 html 中的 el-popper-container-1024 的后缀保持一致
>     current: 0,
>   });
> 
>   instance.mount('#app');
>   return instance;
> };
> ```
> 
> 这样就能够确保每次进入时 teleport to 的目标节点存在，自然就不会出现错误了 [demo](https://stackblitz.com/edit/github-mbr2rr?file=wujie_elm_micro_app%2Findex.html)

可行~

**Comment by kimverchan** [comment]
https://github.com/element-plus/element-plus/pull/10541/commits/0d9a7c360fc4991aa8831e414e94fd3f5beac3ff#diff-1450138748d4a28633e18c07fe757c81879308be03cf00d53e3e0951b191de7c
![image](https://github.com/user-attachments/assets/46b724d1-3eb1-431d-9374-4014047cc6f9)
这一句更改导致的bug
