### ISSUE TITLE
[bug report] there is a problem with the SCSS style configuration example introduced by vite

### ISSUE THREAD

**Issue by Kassell** [element-plus/element-plus#1771]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
windwos10

### Vue version
3.0.11

### What is Expected?
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        resolveStyle: (name) => {
          name = name.splice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    })
  ]
})

### What is actually happening?
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        resolveStyle: (name) => {
          name = name.splice(3)     //    resolveStyle传入的name参数是一个字符串，怎么就splice了
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    })
  ]
})

**Comment by junjieit** [comment]
It's work.
```
resolveStyle: (name) => {
    name = name.replace(/^el-/, '')
    return `element-plus/packages/theme-chalk/src/${name}.scss`;
}
```

**Comment by JeremyWuuuuu** [comment]
See #1777
Sorry, we have fixed it, will be release this afternoon. Sorry for that.

**Comment by JeremyWuuuuu** [comment]
FYI:
https://github.com/element-plus/element-plus/pull/1729/files

**Comment by JeremyWuuuuu** [comment]
Fixed.
