### ISSUE TITLE
[Bug Report] Custom theme url has not been updated

### ISSUE THREAD

**Issue by junjieit** [element-plus/element-plus#1772]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
WIN 10 , Edge 89.0.774.68

### Vue version
3.0.11

### Steps to reproduce
1. open https://element-plus.gitee.io/#/zh-CN/component/custom-theme.

2. click `在线主题生成工具`.

3. change the theme.

4. download.

### What is Expected?
Get the theme css of `element-plus`.

### What is actually happening?
Get the theme css of `element-ui`.

For example, the dialog.css not includes `.el-overlay`.

**Comment by JeremyWuuuuu** [comment]
Sorry, we currently do not have the resource to support the customized theme feature. It's sort of unavailable for you😂, you might need to consider the **[Change Sass Variable](https://element-plus.org/#/zh-CN/component/custom-theme#zai-xiang-mu-zhong-gai-bian-scss-bian-liang)** option

**Comment by iamkun** [comment]
fixed in #1861
