### ISSUE TITLE
[bug report] element plus document introduces annotation error on demand!!!

### ISSUE THREAD

**Issue by wushijiang13** [element-plus/element-plus#1773]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
mac  10.13.6

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/wushijiang/pen/wvgrKWd

### Steps to reproduce
vite 的按需引入写法中 styleImport 中 有一个明显的语法错误问题！
resolveStyle: (name) => {
          name = name.splice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
},
name.splice(3) //如果是name 是string 应使用substr 等函数

修改后的如下
name = name.substr(3,name.length);

### What is Expected?
name = name.substr(3,name.length);

### What is actually happening?
resolveStyle: (name) => {
          name = name.splice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
},

**Comment by wushijiang13** [comment]
https://element-plus.gitee.io/#/zh-CN/component/quickstart 文档按需引入错误地址。

**Comment by JeremyWuuuuu** [comment]
FYI:
https://github.com/element-plus/element-plus/pull/1729/files

**Comment by JeremyWuuuuu** [comment]
Fixed.
