### ISSUE TITLE
[Bug Report] el-input-number display error when use small size 

### ISSUE THREAD

**Issue by llk2yq** [element-plus/element-plus#1775]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Edge 89.0.774.68

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/llk2yq/pen/poRWgQJ

### Steps to reproduce
open the codepen link above  add see the effect

### What is Expected?
display nomal

### What is actually happening?
display error (only when use small size)
![image](https://user-images.githubusercontent.com/22813922/113842625-6c85ed80-97c5-11eb-9b3a-e43b25eee9f1.png)

**Comment by llk2yq** [comment]
It seems that some other components have the same problem when use small size.

**Comment by arronKler** [comment]
I changed the font-family of the input element manually in Chrome DevTool, the problem disappeared. It can be solved either when I change the size from 13px to 14px or 12px.
And I find two post shows that different font-family will render different even they got same font-size. Maybe you can 
give it a try to specify a workable font in your project.

https://medium.com/@julienetienne/pixels-are-dead-faa87cd8c8b9
https://stackoverflow.com/questions/6266671/font-family-causes-one-pixel-drawing-problem-in-chrome

**Comment by JeremyWuuuuu** [comment]
I didn't see that happening on Mac, so I'm guessing you are using Windows, right?
![image](https://user-images.githubusercontent.com/15975785/113963419-22038000-985c-11eb-9ae1-5748f6bf3a3d.png)
I think we can do some modification to avoid this from happening by change odd number to even.

**Comment by llk2yq** [comment]
@JeremyWuuuuu  Yes, I'm using win10, and after I changed  `font-size` of `.el-input--small` to `14px`, it will render correct.

**Comment by liushuiyuan001** [comment]
![image](https://user-images.githubusercontent.com/18300599/114376484-3e831d80-9bb8-11eb-982c-db1c1f1d195b.png)
@JeremyWuuuuu
I reproduce it on my mac. I deleted ```font-size``` of ```.el-input--small```, it will render correct
![image](https://user-images.githubusercontent.com/18300599/114377076-d84aca80-9bb8-11eb-80d5-f56218a7b2f2.png)

**Comment by JeremyWuuuuu** [comment]
Seems like a legacy font-size issue because `ElementUI` used to support the mobile apps so `13px` is presented into code base, we might need to remove this `font-size` since odd pixel size seemed like a issue for desktop rendering.

**Comment by Alanscut** [comment]
This problem should have been fixed, you can try again.

**Comment by llk2yq** [comment]
> This problem should have been fixed, you can try again.

Yes~ It had fixed in 1.2.0, but 1.1.x not.
