### ISSUE TITLE
[TypeScript] [tooltip, tooltip-v2] ts errors when a custom effect is set to a tooltip

### ISSUE THREAD

**Issue by AxelConceicao** [element-plus/element-plus#17751]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.4.35`
- Element Plus Version: `2.7.8`
- Browser / OS: `Chrome lastest`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`
- `el-tooltip-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcCBjb250ZW50PVwiVG9wIGNlbnRlclwiIHBsYWNlbWVudD1cInRvcFwiPlxuICAgIDxlbC1idXR0b24+RGFyazwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+XG4gIDxlbC10b29sdGlwIGNvbnRlbnQ9XCJCb3R0b20gY2VudGVyXCIgcGxhY2VtZW50PVwiYm90dG9tXCIgZWZmZWN0PVwibGlnaHRcIj5cbiAgICA8ZWwtYnV0dG9uPkxpZ2h0PC9lbC1idXR0b24+XG4gIDwvZWwtdG9vbHRpcD5cblxuICA8ZWwtdG9vbHRpcCBjb250ZW50PVwiQm90dG9tIGNlbnRlclwiIGVmZmVjdD1cImN1c3RvbWl6ZWRcIj5cbiAgICA8ZWwtYnV0dG9uPkN1c3RvbWl6ZWQgdGhlbWU8L2VsLWJ1dHRvbj5cbiAgPC9lbC10b29sdGlwPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLmVsLXBvcHBlci5pcy1jdXN0b21pemVkIHtcbiAgLyogU2V0IHBhZGRpbmcgdG8gZW5zdXJlIHRoZSBoZWlnaHQgaXMgMzJweCAqL1xuICBwYWRkaW5nOiA2cHggMTJweDtcbiAgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KDkwZGVnLCByZ2IoMTU5LCAyMjksIDE1MSksIHJnYigyMDQsIDIyOSwgMTI5KSk7XG59XG5cbi5lbC1wb3BwZXIuaXMtY3VzdG9taXplZCAuZWwtcG9wcGVyX19hcnJvdzo6YmVmb3JlIHtcbiAgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KDQ1ZGVnLCAjYjJlNjhkLCAjYmNlNjg5KTtcbiAgcmlnaHQ6IDA7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjcuOC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Set a custom effect to a tooltip

### What is Expected?

We should be free to set a custom effect for a tooltip as specified in the documentation.
Not only 'dark' or 'light'.

### What is actually happening?

ts errors when a custom effect is set to a tooltip
```ts
Type '"customized"' is not assignable to type 'EpPropMergeType<(new (...args: any[]) => "dark" | "light") | (() => "dark" | "light") | ((new (...args: any[]) => "dark" | "light") | (() => "dark" | "light"))[], unknown, unknown>'.ts(2322)
index.d.ts(3227, 5): The expected type comes from property 'effect' which is declared here on type 'Partial<{ offset: number; effect: EpPropMergeType<(new (...args: any[]) => "dark" | "light") | (() => "dark" | "light") | ((new (...args: any[]) => "dark" | "light") | (() => "dark" | "light"))[], unknown, unknown>; ... 26 more ...; showArrow: EpPropMergeType<...>; }> & Omit<...> & Record<...>'
(property) effect?: EpPropMergeType<(new (...args: any[]) => ("light" | "dark") & {}) | (() => "light" | "dark") | ((new (...args: any[]) => ("light" | "dark") & {}) | (() => "light" | "dark"))[], unknown, unknown>
```

### Additional comments

mr causing this : https://github.com/element-plus/element-plus/pull/17040

playground from official documentation :
![2024-08-01_17h45_10](https://github.com/user-attachments/assets/caaa7d55-434d-4405-aa68-0eb0fa806cb9)

**Comment by wzc520pyfm** [comment]
#17040 expected constraint `effect` type is `light | dark`, but effect support custom, the ts type that come to mind is `light | dark | string`, but this is same as `string`.
Is there a better solution besides returning the `effect` type to `string`?
<img width="588" alt="image" src="https://github.com/user-attachments/assets/fa46d801-e94b-4931-8099-0128eb071262">
