### ISSUE TITLE
The select component cannot set the placeholder to null

### ISSUE THREAD

**Issue by wjw-gavin** [element-plus/element-plus#1776]
Sometimes I want it to not show the default placeholder
![image](https://user-images.githubusercontent.com/19986739/113864090-0f963180-97dd-11eb-8475-63dcc15673a7.png)

[https://codepen.io/sweetjun/pen/BapwQKX](https://codepen.io/sweetjun/pen/BapwQKX)

**Comment by JeremyWuuuuu** [comment]
Set it with a single space ` ` would satisfy your requirement.
![image](https://user-images.githubusercontent.com/15975785/113963233-cfc25f00-985b-11eb-831a-6311d95372c7.png)
