### ISSUE TITLE
[Style] [All] Deprecation Warning Sass

### ISSUE THREAD

**Issue by sergdevguy** [element-plus/element-plus#17762]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.8`
- Browser / OS: `Chrome 127.0.6533.89`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

1) Install latest versions Element-plus and sass. (fore example "element-plus": "^2.7.7", "sass": "^1.77.8")
2) Add some components
3) Run

### What is Expected?

Clear console )

### What is actually happening?

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in & {}.
More info: https://sass-lang.com/d/mixed-decls

### Additional comments

The latest versions of sass flood the console with warnings. I solved the problem by installing the "sass" version: "1.72.0". But will the styles be corrected in the future in the library?

**Comment by warmthsea** [comment]
This issue seems to have been fixed in version `2.7.8`.

https://github.com/element-plus/element-plus/pull/17549
