### ISSUE TITLE
[bug report] [vite] Internal server error: name.splice is not a function

### ISSUE THREAD

**Issue by cx-foolish** [element-plus/element-plus#1777]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
windows/版本 89.0.4389.90（正式版本） （64 位）

### Vue version
3.0.11

### Reproduction Link
https://github.com/cx-foolish/vite-vue3-elementPlus

### Steps to reproduce
https://element-plus.gitee.io/#/zh-CN/component/quickstart

官方文档按需引入在vite.config.js中遍历引入的组件获取组件名称，name值为string，但是却使用了splice方法，导致项目运行报错,name.splice(3) is not function

//vite.config.js

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'
const path = require("path");
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        resolveStyle: (name) => {
           //按需引入name.splice报错
          // name = name.splice(3)
          name = name.substring(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    }),
  ],
  resolve: {
    alias: [
      { find: '@', replacement: path.resolve(__dirname, 'src') }
    ],
  }
})

### What is Expected?
name.splice改为name.substring

### What is actually happening?
官方文档按需引入在vite.config.js中遍历引入的组件获取组件名称，name值为string，但是却使用了splice方法，导致项目运行报错,name.splice(3) is not function

**Comment by JeremyWuuuuu** [comment]
We had a PR fixed that, but it will be released in the next version. see https://github.com/element-plus/element-plus/pull/1729/files

**Comment by JeremyWuuuuu** [comment]
We will rollout the release ASAP.
