### ISSUE TITLE
[Bug Report] base env vite   ts   vue3   element-plus, when i run vue-tsc --noEmit && vite build, but  execute error!

### ISSUE THREAD

**Issue by NikFranki** [element-plus/element-plus#1780]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
chrome

### Vue version
3.0.5

### Steps to reproduce
main.ts part content:

import { createApp } from 'vue'
import App from './App.vue';

import {
  ElAlert,
  ElAside,
  ElAutocomplete,
  ElAvatar,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElButtonGroup,
  ElCalendar,
  ElCard,
  ElCarousel,
  ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  ElColorPicker,
  ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElOption,
  ElOptionGroup,
  ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRate,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSlider,
  ElStep,
  ElSteps,
  ElSubmenu,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTag,
  ElTimePicker,
  ElTimeSelect,
  ElTimeline,
  ElTimelineItem,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElUpload,
  ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox,
  ElNotification,
} from 'element-plus';

const components = [
  ElAlert,
  ElAside,
  ElAutocomplete,
  ElAvatar,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElButtonGroup,
  ElCalendar,
  ElCard,
  ElCarousel,
  ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  ElColorPicker,
  ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElOption,
  ElOptionGroup,
  ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRate,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSlider,
  ElStep,
  ElSteps,
  ElSubmenu,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTag,
  ElTimePicker,
  ElTimeSelect,
  ElTimeline,
  ElTimelineItem,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElUpload,
]

const plugins = [
  ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox,
  ElNotification,
]

const app = createApp(App)

components.forEach(component => {
  app.component(component.name, component)
})

plugins.forEach(plugin => {
  app.use(plugin)
})

action:
1. yarn build (vue-tsc --noEmit && vite build)
2. get error

### What is Expected?
execute correctly!

### What is actually happening?
src/main.ts:207:17 - error TS1131: Property or signature expected.

207   app.component(component.name, component);
                    ~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<!-- generated by https://elementui.github.io/issue-generator DO NOT REMOVE -->

**Comment by JeremyWuuuuu** [comment]
The error description is quite vague, I can't tell what is happening here.
Could you provide a more detailed error message here?

**Comment by NikFranki** [comment]
ok

details as follows

error Screenshot:

![build-error](https://user-images.githubusercontent.com/12709235/114122781-905f4580-9923-11eb-95c1-4e2dae83318c.png)

project's main.ts:

![main](https://user-images.githubusercontent.com/12709235/114122813-a40aac00-9923-11eb-91d8-ab5c0a7623a7.png)

**Comment by Lucas-lululu** [comment]
I also encountered the same problem，what should I do

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/114538892-75276980-9c86-11eb-9e44-f886a543df35.png)

Caused by adding  `vue-tsc --noEmit`

> vue-tsc is a tool for checking TypeScript types in `.vue` file

Just delete `vue-tsc --noEmit`, waiting for Element Plus team optimization.

**Comment by sxzz** [comment]
Refactoring for TypeScript types is underway.
