### ISSUE TITLE
Unable to see month in datepicker

### ISSUE THREAD

**Issue by gopz19** [element-plus/element-plus#1782]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/34704368/113979300-b1139680-9862-11eb-9d3b-951cc137a0f8.png">

**Comment by gopz19** [comment]
"element-plus" version is "1.0.2-beta.36",

**Comment by gopz19** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/34704368/113980309-f1274900-9863-11eb-85a7-ff68a22d5f6d.png">

**Comment by 0song** [comment]
a reproduction demo, please

**Comment by gopz19** [comment]
https://user-images.githubusercontent.com/34704368/114010411-b59b7780-9881-11eb-8567-ca7bde3ef3c4.mov

**Comment by gopz19** [comment]
code used: <el-date-picker format="DD/MM/YYYY"
      v-model="filterVal"
      type="date"
      placeholder="Start">
    </el-date-picker>

**Comment by gopz19** [comment]
<el-date-picker style="margin-right:5px;font-size:13px;" format="DD/MM/YYYY"
      v-model="filterValidationStartDate"
      type="date"
      placeholder="Start">
    </el-date-picker>

**Comment by gopz19** [comment]
"<el-date-picker style="margin-right:5px;font-size:13px;" format="DD/MM/YYYY"
      v-model="filterValidationStartDate"
      type="date"
      placeholder="Start">
    </el-date-picker>"

**Comment by gopz19** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/34704368/114010979-5722c900-9882-11eb-8354-ec9693165679.png">

**Comment by JeremyWuuuuu** [comment]
Please give us informations with detailed description instead of screenshot with only slightly code, we need to figure out what was going on with context, this is not helpful.
