### ISSUE TITLE
[Component] 最新版本的火狐浏览器（129.0），tree组件拖拽报错

### ISSUE THREAD

**Issue by vastwu1** [element-plus/element-plus#17846]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `FireFox 129.0 (64位)`
- Build Tool: `Vite`

### Related Component

- `el-tree`
- `el-tree-select`
- `el-tree-v2`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree.html#%E5%8F%AF%E6%8B%96%E6%8B%BD%E8%8A%82%E7%82%B9)

### Steps to reproduce

使用火狐129.0 官网示例即可复现
129.0下载地址：https://ftp.mozilla.org/pub/firefox/releases/129.0/win64/zh-CN/

### What is Expected?

不报错

### What is actually happening?

报错
TypeError: p.dataTransfer is null
    treeNodeDragEnd https://element-plus.org/assets/chunks/theme.CK6SIbTt.js:44
    handleDragEnd https://element-plus.org/assets/chunks/theme.CK6SIbTt.js:44
    wf https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    He https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    Ee https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    n https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/0b888123-7b40-4cf9-a493-31cbcd7c4301)

**Comment by Lin-Van** [comment]
同上
