### ISSUE TITLE
[Component] [date-picker] datePicker类型为yearrange时，限制选择时间范围，下拉面板时间悬浮样式不对

### ISSUE THREAD

**Issue by wbsnpc** [element-plus/element-plus#17845]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.8.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkYXRlUmFuZ2VQYWNrWWVhclRpbWUgPSByZWYoW10pXG5cbmNvbnN0IGRhdGVQaWNrZXIgPSByZWFjdGl2ZSh7XG4gICAgc3RhcnREYXRhOiBudWxsIGFzIG51bWJlciB8IG51bGwsXG59KTtcblxuLy8g6YCJ5oup5pel5pyf5byA5aeL5pe26Ze0XG5jb25zdCBkYXRlUmFuZ2VDbGVhciA9ICh0aW1lOiBhbnkpID0+IHtcbiAgICBsZXQgaGFzU2VsZWN0RGF0ZSA9IHRpbWUgIT09IG51bGwgJiYgdGltZS5sZW5ndGggPiAwO1xuICAgIGRhdGVQaWNrZXIuc3RhcnREYXRhID0gaGFzU2VsZWN0RGF0ZVxuICAgICAgICA/IE1hdGguZmxvb3IodGltZVswXS5nZXRUaW1lKCkgLyAxMDAwKVxuICAgICAgICA6IG51bGw7XG59O1xuLy/ph43nva7ml6XmnJ/lvIDlp4vml7bpl7RcbmNvbnN0IHRpbWVDaGFuZ2UgPSAodGltZTogYW55KSA9PiB7XG4gICAgZGF0ZVBpY2tlci5zdGFydERhdGEgPSBudWxsXG59O1xuXG4vLyDnpoHnlKjml7bpl7TpgInpoblcbmNvbnN0IGRpc2FibGVkRGF0ZSA9ICh0aW1lOiBhbnkpID0+IHtcbiAgICBpZiAoZGF0ZVBpY2tlci5zdGFydERhdGEgIT09IG51bGwpIHtcbiAgICAgICAgY29uc3Qgc3RhcnREYXRlID0gbmV3IERhdGUoZGF0ZVBpY2tlci5zdGFydERhdGEgKiAxMDAwKTtcbiAgICAgICAgbGV0IGJlZm9yZURhdGU6IERhdGU7XG4gICAgICAgIGxldCBhZnRlckRhdGU6IERhdGU7XG5cbiAgICAgICAgIC8vIOW5tC3mmL7npLrlubQsIOacgOWkmjXlubTlhoVcbiAgICAgICAgYmVmb3JlRGF0ZSA9IG5ldyBEYXRlKHN0YXJ0RGF0ZSk7XG4gICAgICAgIGFmdGVyRGF0ZSA9IG5ldyBEYXRlKHN0YXJ0RGF0ZSk7XG4gICAgICAgIGJlZm9yZURhdGUuc2V0RnVsbFllYXIoc3RhcnREYXRlLmdldEZ1bGxZZWFyKCkgLSA1KTtcbiAgICAgICAgYWZ0ZXJEYXRlLnNldEZ1bGxZZWFyKHN0YXJ0RGF0ZS5nZXRGdWxsWWVhcigpICsgNSk7XG4gICAgICAgIHJldHVybiB0aW1lLmdldFRpbWUoKSA8IGJlZm9yZURhdGUuZ2V0VGltZSgpIHx8IHRpbWUuZ2V0VGltZSgpID4gYWZ0ZXJEYXRlLmdldFRpbWUoKTtcbiAgICB9XG4gICAgcmV0dXJuIGZhbHNlO1xufTtcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1kYXRlLXBpY2tlciA6Y2xlYXJhYmxlPVwiZmFsc2VcIiBAY2FsZW5kYXItY2hhbmdlPVwiZGF0ZVJhbmdlQ2xlYXJcIiBAY2hhbmdlPVwidGltZUNoYW5nZVwiIFxuICA6ZGlzYWJsZWQtZGF0ZT1cImRpc2FibGVkRGF0ZVwiIHYtbW9kZWw9XCJkYXRlUmFuZ2VQYWNrWWVhclRpbWVcIiBmb3JtYXQ9XCJZWVlZXCIgXG4gIHZhbHVlLWZvcm1hdD1cIllZWVlcIiB0eXBlPVwieWVhcnJhbmdlXCIgcmFuZ2Utc2VwYXJhdG9yPVwiLVwiIFxuICBzdGFydC1wbGFjZWhvbGRlcj1cIuW8gOWni+aXpeacn1wiIGVuZC1wbGFjZWhvbGRlcj1cIue7k+adn+aXpeacn1wiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi40NS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy4yLjQ1L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, reactive } from 'vue'

const dateRangePackYearTime = ref([])

const datePicker = reactive({
    startData: null as number | null,
});
// 选择日期开始时间
const dateRangeClear = (time: any) => {
    let hasSelectDate = time !== null && time.length > 0;
    datePicker.startData = hasSelectDate
        ? Math.floor(time[0].getTime() / 1000)
        : null;
};
//重置日期开始时间
const timeChange = (time: any) => {
    datePicker.startData = null
};

// 禁用时间选项
const disabledDate = (time: any) => {
    if (datePicker.startData !== null) {
        const startDate = new Date(datePicker.startData * 1000);
        let beforeDate: Date;
        let afterDate: Date;

         // 年-显示年, 最多5年内
        beforeDate = new Date(startDate);
        afterDate = new Date(startDate);
        beforeDate.setFullYear(startDate.getFullYear() - 5);
        afterDate.setFullYear(startDate.getFullYear() + 5);
        return time.getTime() < beforeDate.getTime() || time.getTime() > afterDate.getTime();
    }
    return false;
};
</script>
<template>
  <el-date-picker :clearable="false" @calendar-change="dateRangeClear" @change="timeChange" 
  :disabled-date="disabledDate" v-model="dateRangePackYearTime" format="YYYY" 
  value-format="YYYY" type="yearrange" range-separator="-" 
  start-placeholder="开始日期" end-placeholder="结束日期" />
</template>
```

### What is Expected?

悬浮样式在鼠标指示的时间上

### What is actually happening?

悬浮样式不在鼠标指示的时间上
![image](https://img.picgo.net/2024/08/12/imagee1ad5eae0c1352f7.png)
如图，鼠标在2025上，但是悬浮样式在2021上
选择开始时间后，鼠标指示能选择的最后结束时间，悬浮样式不生效
其它时间正常

### Additional comments

_(empty)_

**Comment by zxt97** [comment]
怎么解决的？

**Comment by index-name** [comment]
> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.2.45`
> * Element Plus Version: `2.8.0`
> * Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `el-date-picker`
> 
> ### Reproduction Link
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkYXRlUmFuZ2VQYWNrWWVhclRpbWUgPSByZWYoW10pXG5cbmNvbnN0IGRhdGVQaWNrZXIgPSByZWFjdGl2ZSh7XG4gICAgc3RhcnREYXRhOiBudWxsIGFzIG51bWJlciB8IG51bGwsXG59KTtcblxuLy8g6YCJ5oup5pel5pyf5byA5aeL5pe26Ze0XG5jb25zdCBkYXRlUmFuZ2VDbGVhciA9ICh0aW1lOiBhbnkpID0+IHtcbiAgICBsZXQgaGFzU2VsZWN0RGF0ZSA9IHRpbWUgIT09IG51bGwgJiYgdGltZS5sZW5ndGggPiAwO1xuICAgIGRhdGVQaWNrZXIuc3RhcnREYXRhID0gaGFzU2VsZWN0RGF0ZVxuICAgICAgICA/IE1hdGguZmxvb3IodGltZVswXS5nZXRUaW1lKCkgLyAxMDAwKVxuICAgICAgICA6IG51bGw7XG59O1xuLy/ph43nva7ml6XmnJ/lvIDlp4vml7bpl7RcbmNvbnN0IHRpbWVDaGFuZ2UgPSAodGltZTogYW55KSA9PiB7XG4gICAgZGF0ZVBpY2tlci5zdGFydERhdGEgPSBudWxsXG59O1xuXG4vLyDnpoHnlKjml7bpl7TpgInpoblcbmNvbnN0IGRpc2FibGVkRGF0ZSA9ICh0aW1lOiBhbnkpID0+IHtcbiAgICBpZiAoZGF0ZVBpY2tlci5zdGFydERhdGEgIT09IG51bGwpIHtcbiAgICAgICAgY29uc3Qgc3RhcnREYXRlID0gbmV3IERhdGUoZGF0ZVBpY2tlci5zdGFydERhdGEgKiAxMDAwKTtcbiAgICAgICAgbGV0IGJlZm9yZURhdGU6IERhdGU7XG4gICAgICAgIGxldCBhZnRlckRhdGU6IERhdGU7XG5cbiAgICAgICAgIC8vIOW5tC3mmL7npLrlubQsIOacgOWkmjXlubTlhoVcbiAgICAgICAgYmVmb3JlRGF0ZSA9IG5ldyBEYXRlKHN0YXJ0RGF0ZSk7XG4gICAgICAgIGFmdGVyRGF0ZSA9IG5ldyBEYXRlKHN0YXJ0RGF0ZSk7XG4gICAgICAgIGJlZm9yZURhdGUuc2V0RnVsbFllYXIoc3RhcnREYXRlLmdldEZ1bGxZZWFyKCkgLSA1KTtcbiAgICAgICAgYWZ0ZXJEYXRlLnNldEZ1bGxZZWFyKHN0YXJ0RGF0ZS5nZXRGdWxsWWVhcigpICsgNSk7XG4gICAgICAgIHJldHVybiB0aW1lLmdldFRpbWUoKSA8IGJlZm9yZURhdGUuZ2V0VGltZSgpIHx8IHRpbWUuZ2V0VGltZSgpID4gYWZ0ZXJEYXRlLmdldFRpbWUoKTtcbiAgICB9XG4gICAgcmV0dXJuIGZhbHNlO1xufTtcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1kYXRlLXBpY2tlciA6Y2xlYXJhYmxlPVwiZmFsc2VcIiBAY2FsZW5kYXItY2hhbmdlPVwiZGF0ZVJhbmdlQ2xlYXJcIiBAY2hhbmdlPVwidGltZUNoYW5nZVwiIFxuICA6ZGlzYWJsZWQtZGF0ZT1cImRpc2FibGVkRGF0ZVwiIHYtbW9kZWw9XCJkYXRlUmFuZ2VQYWNrWWVhclRpbWVcIiBmb3JtYXQ9XCJZWVlZXCIgXG4gIHZhbHVlLWZvcm1hdD1cIllZWVlcIiB0eXBlPVwieWVhcnJhbmdlXCIgcmFuZ2Utc2VwYXJhdG9yPVwiLVwiIFxuICBzdGFydC1wbGFjZWhvbGRlcj1cIuW8gOWni+aXpeacn1wiIGVuZC1wbGFjZWhvbGRlcj1cIue7k+adn+aXpeacn1wiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi40NS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy4yLjQ1L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4wL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)
> 
> ### Steps to reproduce
> ```
> <script setup lang="ts">
> import { ref, reactive } from 'vue'
> 
> const dateRangePackYearTime = ref([])
> 
> const datePicker = reactive({
>     startData: null as number | null,
> });
> // 选择日期开始时间
> const dateRangeClear = (time: any) => {
>     let hasSelectDate = time !== null && time.length > 0;
>     datePicker.startData = hasSelectDate
>         ? Math.floor(time[0].getTime() / 1000)
>         : null;
> };
> //重置日期开始时间
> const timeChange = (time: any) => {
>     datePicker.startData = null
> };
> 
> // 禁用时间选项
> const disabledDate = (time: any) => {
>     if (datePicker.startData !== null) {
>         const startDate = new Date(datePicker.startData * 1000);
>         let beforeDate: Date;
>         let afterDate: Date;
> 
>          // 年-显示年, 最多5年内
>         beforeDate = new Date(startDate);
>         afterDate = new Date(startDate);
>         beforeDate.setFullYear(startDate.getFullYear() - 5);
>         afterDate.setFullYear(startDate.getFullYear() + 5);
>         return time.getTime() < beforeDate.getTime() || time.getTime() > afterDate.getTime();
>     }
>     return false;
> };
> </script>
> <template>
>   <el-date-picker :clearable="false" @calendar-change="dateRangeClear" @change="timeChange" 
>   :disabled-date="disabledDate" v-model="dateRangePackYearTime" format="YYYY" 
>   value-format="YYYY" type="yearrange" range-separator="-" 
>   start-placeholder="开始日期" end-placeholder="结束日期" />
> </template>
> ```
> 
> ### What is Expected?
> 悬浮样式在鼠标指示的时间上
> 
> ### What is actually happening?
> 悬浮样式不在鼠标指示的时间上 ![image](https://camo.githubusercontent.com/0752f79dc5bfcfce8c050567b2996af82898e2e043099fe508e976be55628526/68747470733a2f2f696d672e706963676f2e6e65742f323032342f30382f31322f696d616765653161643565616530633133353266372e706e67) 如图，鼠标在2025上，但是悬浮样式在2021上 选择开始时间后，鼠标指示能选择的最后结束时间，悬浮样式不生效 其它时间正常
> 
> ### Additional comments
> _(empty)_
请问我也遇到了这个情况怎么解决的？

**Comment by index-name** [comment]
没人吗，请问怎么解决的？
