### ISSUE TITLE
[Bug Report] Message covered by Dialog

### ISSUE THREAD

**Issue by llk2yq** [element-plus/element-plus#1785]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Edge 89 Windows 10

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/llk2yq/pen/zYNPOrZ

### Steps to reproduce
1 click Message button,
2 click Dialog button.

### What is Expected?
Message cover Dialog.

### What is actually happening?
Dialog cover Message.

**Comment by JeremyWuuuuu** [comment]
Not a bug, it should follow the sequence of calling out the popups, see the screenshot, 
I moved your message callout button into `dialog`, then click on the button, you get the correct behavior.
NOTE THAT:
**When new popups showing, it will always cover the previous popup.**
![image](https://user-images.githubusercontent.com/15975785/114036656-d7f9b900-98b2-11eb-87b2-7c98298699c9.png)

**Comment by llk2yq** [comment]
使用这种方式引入时就会有问题：`import ElMessage from "element-plus/lib/el-message"`，而使用这种方式就不会有问题：`const { ElMessage } = ElementPlus`。

**Comment by JeremyWuuuuu** [comment]
This could be related to #1778 I already had a fix for it, let's see if you still get the problem after the new release
