### ISSUE TITLE
[Component] [select] v2.8.0 el-select 组件@click功能失效

### ISSUE THREAD

**Issue by Forze64** [element-plus/element-plus#17863]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `Microsoft Edge 版本 127.0.2651.98 (正式版本) (64 位)`
- Build Tool: `CDN`

### Related Component

- `el-select`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/sandbox/elementplus-v2-8-0-el-select-issue-ghyms5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzrskzf600063j6i1consm0c%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzrskzf600023j6irinv7eak%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzrskzf600033j6iwea1e1sa%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzrskzf600053j6irkp46d9b%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzrskzf600023j6irinv7eak%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrskzf500013j6iaw3te76i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clzrskzf600023j6irinv7eak%2522%252C%2522activeTabId%2522%253A%2522clzrskzf500013j6iaw3te76i%2522%257D%252C%2522clzrskzf600053j6irkp46d9b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzrskzf600043j6iy5sx4umb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clzrskzf600053j6irkp46d9b%2522%252C%2522activeTabId%2522%253A%2522clzrskzf600043j6iy5sx4umb%2522%257D%252C%2522clzrskzf600033j6iwea1e1sa%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzrskzf600033j6iwea1e1sa%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

复制以下代码保存为html文件使用live server打开
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>v2.8.0</title>
    <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
    <script src="https://unpkg.com/vue@3"></script>
    <script src="https://unpkg.com/element-plus@2.8.0"></script>
</head>
<body>
    <div id="app">
        <el-select v-model="stage" placeholder="选择阶段" @click="getStages" filterable>
            <el-option v-for="item in stages" :lable="item.label" :value="item.value"/>
        </el-select>
    </div>

    <script>
        const stage = "";
        const stages = [
        {
            "value": "核对库存",
            "label": "核对库存"
        },
        {
            "value": "需求确认",
            "label": "需求确认"
        }]
        const { createApp } = Vue;
        const App = {
            data(){
                return {stages, stage}
            },
            methods:{
                getStages(){
                    console.log("hello from getStages")
                }
            }
        }
        const app = createApp(App);
        app.use(ElementPlus)
        app.mount('#app')
    </script>
</body>
</html>
```
**将cdn改回@2.7.7版本，getStages正常触发**
<script src="https://unpkg.com/element-plus@2.7.7"></script>

### What is Expected?

控制台打印"hello from getStages"

### What is actually happening?

什么都没有发生，getStages方法没有被触发

### Additional comments

_(empty)_

**Comment by mrreddevil2412** [comment]
I have a same bug. after upgrade version to 2.8.0 :((
event @click not working
