### ISSUE TITLE
[Bug Report] ElButton implementation has a potential bug in an edge case

### ISSUE THREAD

**Issue by eczn** [element-plus/element-plus#1789]
### Element Plus version
1.0.2-beta.37

### OS/Browsers version
macos

### Vue version
3.0.11

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/button/src/button.vue#L103-L108

### Steps to reproduce
https://github.com/element-plus/element-plus/blob/dev/packages/button/src/button.vue#L103-L108

the line from 103 to 108 is execpting a computed value for a reactive object, but is not equal to watch 3 reactive one with short-circuit OR operator, i.e the pattern `A || B || C` is not strict equal to `[A, B, C]`

here:

``` jsx
// maybe cause some bug
const buttonSize = computed(() => {
  return props.size || elFormItem.size || $ELEMENT.size;
});
// a better one
const buttonSize2 = computed(() => {
  const watches = [props.size, elFormItem.size, $ELEMENT.size];
  return watches[0] || watches[1] || watches[2];
});
```

### What is Expected?
a correct way to maintaince computed value.

### What is actually happening?
-

**Comment by kooriookami** [comment]
Can you show me a demo with this situation please?

**Comment by JeremyWuuuuu** [comment]
Are you willing to fix it? If you do, send us a PR would be great!

**Comment by msidolphin** [comment]
@eczn I don't understand what bugs might cause?
