### ISSUE TITLE
[Component] [tree] Component Tree Draggable does not work on Firefox

### ISSUE THREAD

**Issue by omni-frontend-dev** [element-plus/element-plus#17899]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0`
- Build Tool: `Nuxt`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmFsbG93LWRyb3A9XCJhbGxvd0Ryb3BcIlxuICAgIDphbGxvdy1kcmFnPVwiYWxsb3dEcmFnXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIGRyYWdnYWJsZVxuICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgIG5vZGUta2V5PVwiaWRcIlxuICAgIEBub2RlLWRyYWctc3RhcnQ9XCJoYW5kbGVEcmFnU3RhcnRcIlxuICAgIEBub2RlLWRyYWctZW50ZXI9XCJoYW5kbGVEcmFnRW50ZXJcIlxuICAgIEBub2RlLWRyYWctbGVhdmU9XCJoYW5kbGVEcmFnTGVhdmVcIlxuICAgIEBub2RlLWRyYWctb3Zlcj1cImhhbmRsZURyYWdPdmVyXCJcbiAgICBAbm9kZS1kcmFnLWVuZD1cImhhbmRsZURyYWdFbmRcIlxuICAgIEBub2RlLWRyb3A9XCJoYW5kbGVEcm9wXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5pbXBvcnQgdHlwZSB7IERyYWdFdmVudHMgfSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC91c2VEcmFnTm9kZSdcbmltcG9ydCB0eXBlIHtcbiAgQWxsb3dEcm9wVHlwZSxcbiAgTm9kZURyb3BUeXBlLFxufSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy90cmVlLnR5cGUnXG5cbmNvbnN0IGhhbmRsZURyYWdTdGFydCA9IChub2RlOiBOb2RlLCBldjogRHJhZ0V2ZW50cykgPT4ge1xuICBjb25zb2xlLmxvZygnZHJhZyBzdGFydCcsIG5vZGUpXG59XG5jb25zdCBoYW5kbGVEcmFnRW50ZXIgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBlbnRlcjonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdMZWF2ZSA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGxlYXZlOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ092ZXIgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlLCBkcm9wTm9kZTogTm9kZSwgZXY6IERyYWdFdmVudHMpID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBvdmVyOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ0VuZCA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZHJvcFR5cGU6IE5vZGVEcm9wVHlwZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVuZDonLCBkcm9wTm9kZSAmJiBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG59XG5jb25zdCBoYW5kbGVEcm9wID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBkcm9wVHlwZTogTm9kZURyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyb3A6JywgZHJvcE5vZGUubGFiZWwsIGRyb3BUeXBlKVxufVxuY29uc3QgYWxsb3dEcm9wID0gKGRyYWdnaW5nTm9kZTogTm9kZSwgZHJvcE5vZGU6IE5vZGUsIHR5cGU6IEFsbG93RHJvcFR5cGUpID0+IHtcbiAgaWYgKGRyb3BOb2RlLmRhdGEubGFiZWwgPT09ICdMZXZlbCB0d28gMy0xJykge1xuICAgIHJldHVybiB0eXBlICE9PSAnaW5uZXInXG4gIH0gZWxzZSB7XG4gICAgcmV0dXJuIHRydWVcbiAgfVxufVxuY29uc3QgYWxsb3dEcmFnID0gKGRyYWdnaW5nTm9kZTogTm9kZSkgPT4ge1xuICByZXR1cm4gIWRyYWdnaW5nTm9kZS5kYXRhLmxhYmVsLmluY2x1ZGVzKCdMZXZlbCB0aHJlZSAzLTEtMScpXG59XG5cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAyJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. Use firefox
2. Try to drag a tree node using firefox 

### What is Expected?

You can drag and drop Tree nodes

### What is actually happening?

Getting Error: f.dataTransfer is null

### Additional comments

My Firefox version is 129 (updated as of 8/14/2024)

_(empty)_

**Comment by warmthsea** [comment]
fixed by https://github.com/element-plus/element-plus/pull/17849

need to wait for the next version release or publishing your own packages
