### ISSUE TITLE
[Component] [slider] 横屏时（也就是页面旋转90度），el-slider无法滑动

### ISSUE THREAD

**Issue by IndexLibrary** [element-plus/element-plus#17908]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.30`
- Element Plus Version: `2.8.0`
- Browser / OS: `Chrome127 windows10`
- Build Tool: `Webpack`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBpbmRleCA9IHJlZigyKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNsaWRlciB2LW1vZGVsPVwiaW5kZXhcIiA6bWF4PVwiMTBcIiBzaG93LXN0b3BzPjwvZWwtc2xpZGVyPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuaHRtbCB7XG4gIHdpZHRoOiAxMDB2bWF4O1xuICBoZWlnaHQ6IDEwMHZtaW47XG4gIHRyYW5zZm9ybTogcm90YXRlKDkwZGVnKTtcbiAgdHJhbnNmb3JtLW9yaWdpbjogNTB2bWluIDUwdm1pbjtcbn1cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

拖动滑块往另一边移动

### What is Expected?

滑块往拖动方向移动

### What is actually happening?

没有移动

### Additional comments

_(empty)_

**Comment by betavs** [comment]
[垂直模式](https://element-plus.org/zh-CN/component/slider.html#%E5%9E%82%E7%9B%B4%E6%A8%A1%E5%BC%8F)

**Comment by qtencent7** [comment]
你这个滚动条，如果html正常，本身是横着的嘛。如果，html转动90度，slider竖起来了。
我试了一下，如果横着滑动，是可以滚动的，但是，竖着滑动，就没有效果。

**Comment by qtencent7** [comment]
原因就在源码的这个地方，
![image](https://github.com/user-attachments/assets/96c38556-5790-49da-bab6-29f117718194)
slider里面有个属性，叫做vertical，如果设置成vertical，那么计算的就是Y的值，如果，vertical不存在，那么计算就是X的值。
这个地方需要修改计算X，Y的逻辑，改成，先根据slider的长度和屏幕的移动的X，Y值对应的单位长度像素计算出来，从而确定X值或者Y值，加一，代表多少像素。然后，在根据移动的X值和Y值，共同确定，初始点距离当前点的X，Y的绝对距离是多少，然后根据像素比，把对应的移动距离表示出来就可以了

**Comment by IndexLibrary** [comment]
> [垂直模式](https://element-plus.org/zh-CN/component/slider.html#%E5%9E%82%E7%9B%B4%E6%A8%A1%E5%BC%8F)

是要横着显示的，实例里的代码是旋转页面模拟横屏，实际上滑块是横着

**Comment by IndexLibrary** [comment]
> 你这个滚动条，如果html正常，本身是横着的嘛。如果，html转动90度，slider竖起来了。 我试了一下，如果横着滑动，是可以滚动的，但是，竖着滑动，就没有效果。

是的，是需要横着显示

**Comment by betavs** [comment]
> 是要横着显示的，实例里的代码是旋转页面模拟横屏，实际上滑块是横着

@IndexLibrary 移除旋转样式后，在手机中竖屏可以正常滑动，旋转屏幕后横屏也是正常的

**Comment by IndexLibrary** [comment]
> > 是要横着显示的，实例里的代码是旋转页面模拟横屏，实际上滑块是横着
> 
> @IndexLibrary 移除旋转样式后，在手机中竖屏可以正常滑动，旋转屏幕后横屏也是正常的

我们这边是用旋转样式来显示横屏效果，试了下设置vertical然后把slider旋转90度，滑动是没问题了，但是tooltip位置没有跟着移动

**Comment by btea** [comment]
@IndexLibrary `tooltip`位置可以通过设置`placement`变化。

**Comment by IndexLibrary** [comment]
后面我设置了disabled，自己监听touch了
