### ISSUE TITLE
[Bug Report] el-image-viewer  code bug, when switch photo index, and all img tag will all change the same url

### ISSUE THREAD

**Issue by gorphensu** [element-plus/element-plus#1791]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
window10/chrome 80

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/gorphensu/pen/jOyaKWN?editors=1111

### Steps to reproduce
show the dom ,open chrome devtool and check the img tag, all tags has the same url, change prev or next  the url alway change the same

### What is Expected?
change pre or next should not change url and refresh img tag

### What is actually happening?
show the dom ,open chrome devtool and check the img tag, all tags has the same url, change prev or next  the url alway change the same

**Comment by gorphensu** [comment]
![image](https://user-images.githubusercontent.com/1619039/114120122-7c651500-991e-11eb-97d7-d8a0337fc01e.png)

**Comment by JeremyWuuuuu** [comment]
Seems like a bug, but the functionality seems fine, do you have something to do with the DOM? (I'm asking because it determines whether this bug is critical.

**Comment by JeremyWuuuuu** [comment]
Fixed in #1819
