### ISSUE TITLE
[Component] [pagination, config-provider] el-config-provider的size如果变化过快el-pagination受影响会有控制台报错

### ISSUE THREAD

**Issue by litchia** [element-plus/element-plus#17947]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.38`
- Element Plus Version: `2.8.0`
- Browser / OS: `Chrome  127.0.6533.120（正式版本） (arm64)/ MacOS Ventura 13.2.1`
- Build Tool: `Vite`

### Related Component

- `el-pagination`
- `el-config-provider`

### Reproduction Link

[Github Repo](https://github.com/litchia/element-plus-vite-starter)

### Steps to reproduce

复现链接是我fork的element-plus-vite-starter基础上改的。element-plus和vue都是最新版本。除了版本外，改动只有App.vue这个文件。
下载之后，只需要pnpm i并且pnpm dev即可。打开浏览器运行网页，打开F12控制台，然后鼠标快速拉动缩放浏览器视窗尺寸，观察组件的尺寸变化和控制台是否报错。

### What is Expected?

快速改变浏览器视窗尺寸，el-config-provider的size尺寸响应式变化，期望el-pagination和el-button的大小也能跟着变化。

### What is actually happening?

控制台报错
chunk-GV3NIXIC.js?v=16226131:12705 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'size')
    at chunk-GV3NIXIC.js?v=16226131:12705:31
    at ReactiveEffect.fn (chunk-2GSE3T2T.js?v=16226131:1272:13)
    at ReactiveEffect.run (chunk-2GSE3T2T.js?v=16226131:461:19)
    at get value (chunk-2GSE3T2T.js?v=16226131:1284:107)
    at chunk-GV3NIXIC.js?v=16226131:37718:86
    at ReactiveEffect.fn (chunk-2GSE3T2T.js?v=16226131:1272:13)
    at ReactiveEffect.run (chunk-2GSE3T2T.js?v=16226131:461:19)
    at get value (chunk-2GSE3T2T.js?v=16226131:1284:107)
    at triggerComputed (chunk-2GSE3T2T.js?v=16226131:479:20)
    at get dirty (chunk-2GSE3T2T.js?v=16226131:433:11)
我需要同时给el-pagination一个size属性才可以避免这种情况。而el-button则不需要给size属性也可以响应el-config-provider的size变化。

### Additional comments

_(empty)_

**Comment by btea** [comment]
你的值没传对，`size`应该绑定具体值，`:size="size"`。
https://github.com/litchia/element-plus-vite-starter/blob/9163f96127c83493425851a003ac4cf20758d573/src/App.vue#L2

**Comment by litchia** [comment]
> 你的值没传对，`size`应该绑定具体值，`:size="size"`。
> 
> https://github.com/litchia/element-plus-vite-starter/blob/9163f96127c83493425851a003ac4cf20758d573/src/App.vue#L2

这个分页组件的size不受全局组件控制吗？ button是受全局组件控制的

**Comment by btea** [comment]
支持的，但你这里`size`没绑定对应的变量，应该改成`:size="size"`
![image](https://github.com/user-attachments/assets/fb8bb1a1-aeb0-4f9c-a85b-fca68f872e6a)

**Comment by litchia** [comment]
> 支持的，但你这里`size`没绑定对应的变量，应该改成`:size="size"`
> 
> ![image](https://github.com/user-attachments/assets/fb8bb1a1-aeb0-4f9c-a85b-fca68f872e6a)
> 
> 

这里应该是v-bind的同名简写  我直接简写了。写全的话应该也是不可以的，您那边复现是不报错的是吗

**Comment by btea** [comment]
对，我使用 `:size="size"` 没有复现。

**Comment by btea** [comment]
能提供一份视频或者gif吗？

**Comment by Memory1998** [comment]
我也发现这个问题了
![Video_2024-08-23_114447 00_00_00-00_00_30](https://github.com/user-attachments/assets/8a1a98bd-8dcd-4729-8bb2-95445d55bb10)

**Comment by btea** [comment]
@Memory1998 图片太模糊了，看不清楚，能提供一份更清晰的图片吗？或者一份必现的最小复现代码。

**Comment by litchia** [comment]
https://github.com/user-attachments/assets/5cbf5aed-972a-48d4-9b54-b2f6b94c7548

<img width="670" alt="image" src="https://github.com/user-attachments/assets/1613a121-d717-426b-94fc-aa73188fd571">

vue版本和ep版本都是最新稳定版

**Comment by litchia** [comment]
现在就是  el-button没有问题，而且尺寸会跟着变化。分页不会跟着变化，控制台报错

**Comment by Memory1998** [comment]
> @Memory1998 图片太模糊了，看不清楚，能提供一份更清晰的图片吗？或者一份必现的最小复现代码。

`<template>
  <div>
    <el-button mb-2 @click="toggle">Switch Language</el-button>
    <br/>

    <el-config-provider :size="size" :locale="locale">
      <el-form :model="form" label-width="auto" style="max-width: 600px">
        <el-form-item label="Activity name">
          <el-input v-model="form.name"/>
        </el-form-item>
        <el-form-item label="Activity zone">
          <el-select v-model="form.region" placeholder="please select your zone">
            <el-option label="Zone one" value="shanghai"/>
            <el-option label="Zone two" value="beijing"/>
          </el-select>
        </el-form-item>
        <el-form-item label="Activity time">
          <el-col :span="11">
            <el-date-picker
                v-model="form.date1"
                type="date"
                placeholder="Pick a date"
                style="width: 100%"
            />
          </el-col>
          <el-col :span="2" class="text-center">
            <span class="text-gray-500">-</span>
          </el-col>
          <el-col :span="11">
            <el-time-picker
                v-model="form.date2"
                placeholder="Pick a time"
                style="width: 100%"
            />
          </el-col>
        </el-form-item>
        <el-form-item label="Instant delivery">
          <el-switch v-model="form.delivery"/>
        </el-form-item>
        <el-form-item label="Activity type">
          <el-checkbox-group v-model="form.type">
            <el-checkbox value="Online activities" name="type">
              Online activities
            </el-checkbox>
            <el-checkbox value="Promotion activities" name="type">
              Promotion activities
            </el-checkbox>
            <el-checkbox value="Offline activities" name="type">
              Offline activities
            </el-checkbox>
            <el-checkbox value="Simple brand exposure" name="type">
              Simple brand exposure
            </el-checkbox>
          </el-checkbox-group>
        </el-form-item>
        <el-form-item label="Resources">
          <el-radio-group v-model="form.resource">
            <el-radio value="Sponsor">Sponsor</el-radio>
            <el-radio value="Venue">Venue</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="Activity form">
          <el-input v-model="form.desc" type="textarea"/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSubmit">Create</el-button>
          <el-button>Cancel</el-button>
        </el-form-item>
      </el-form>
      <br>
      <el-pagination :total="100"/>
      <br>
    </el-config-provider>
  </div>
</template>

<script setup>
import {computed, reactive, ref} from 'vue'
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'
import en from 'element-plus/dist/locale/en.mjs'

const language = ref('zh-cn')
const size = ref('default')
const locale = computed(() => (language.value === 'zh-cn' ? zhCn : en))
const form = reactive({
  name: '',
  region: '',
  date1: '',
  date2: '',
  delivery: false,
  type: [],
  resource: '',
  desc: '',
})
const toggle = () => {
  language.value = language.value === 'zh-cn' ? 'en' : 'zh-cn'
  size.value = size.value === 'default' ? 'large' : 'default'
}
</script>`

**Comment by btea** [comment]
确实有问题。
