### ISSUE TITLE
[Component] [table-column] el-table-column中width属性设置不生效

### ISSUE THREAD

**Issue by NanFei9** [element-plus/element-plus#17968]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `chrome127.0.6533.120`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Link](没有链接)

### Steps to reproduce

  <el-table-column label="序号" width="80" align="center" />

### What is Expected?

设置width应该这一列生效

### What is actually happening?

实际width:"80",但是浏览器没有任何变化，刷新也重启了项目没用

### Additional comments

暂无

**Comment by wsyf0308** [comment]
width | 对应列的宽度 | string / number
:width='80'   /  width='80px'

**Comment by NanFei9** [comment]
yes,I tried it many times,but nothing worked,vue2 is will take effect发自我的手机-------- 原始邮件 --------发件人： isYang ***@***.***>日期： 2024年8月21日周三 下午4:45收件人： element-plus/element-plus ***@***.***>抄送： NanFei9 ***@***.***>, Mention ***@***.***>主    题： Re: [element-plus/element-plus] [Component] [table-column] el-table-column中width属性设置不生效 (Issue #17968)
width | 对应列的宽度 | string / number
:width='80'   /  width='80px'
@NanFei9
