### ISSUE TITLE
[Bug Report] el-menu set default-active-index not work

### ISSUE THREAD

**Issue by lifeilu** [element-plus/element-plus#1796]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
Chrome

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
set activeIndex, the active el-menu-item does not change

### What is Expected?
when the activeIndex change, the index el-menu-item has active class

### What is actually happening?
the activeIndex change , the active item doesnot change

**Comment by lifeilu** [comment]
[link](https://codepen.io/lifeilu/pen/OJWvvrL)

Steps：
firstly: select the second item of menu;
secondly:click the button;
thirdly: select the second item of menu;
forthly: click the button;
result expected: the active item is the forth one.
actual result: the active item is the second one.

**Comment by BeADre** [comment]
你的`activeIndex`值在点击按钮后一直是4并没有更新， 所以你应该在`handleSelect`函数中改变`activeIndex`值

**Comment by lifeilu** [comment]
> 你的`activeIndex`值在点击按钮后一直是4并没有更新， 所以你应该在`handleSelect`函数中改变`activeIndex`值

所以activeIndex在click的时候不会自动更新，需要手动去改变它的值，了解
