### ISSUE TITLE
[bug report] rollup package element plus, add on demand invalid

### ISSUE THREAD

**Issue by bhabgs** [element-plus/element-plus#1797]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
11.2.2

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/bhabgs-the-lessful/pen/mdEYPPy

### Steps to reproduce
* .babel 配置
``` json
{
  "plugins": [
    ["@vue/babel-plugin-jsx"],
    [
      "component",
      {
        "libraryName": "element-plus",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}

```

* rollup 配置
``` js
import typescript from '@rollup/plugin-typescript';
import babel from '@rollup/plugin-babel';
import postcss from 'rollup-plugin-postcss';
// import replace from "@rollup/plugin-replace";
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import cssnano from 'cssnano';

const extensions = ['.ts', '.js', '.tsx'];

export default [
  typescript({
    lib: ['es5', 'dom'], // , 'es6', 'dom'
    target: 'es5',
    noEmitOnError: true,
  }),

  resolve({ mainFields: ['module', 'main', 'browser'] }),
  commonjs({ extensions, sourceMap: true }),
  babel({ babelHelpers: 'bundled', extensions }),
  postcss({
    plugins: [cssnano],
    extract: 'style.css', // 输出路径
  }),
];

```

* rollup 入口文件
``` ts
import 'element-plus/lib/theme-chalk/index.css';
import { ElTable, ElTableColumn } from 'element-plus';
import type { App } from 'vue';
import { App } from '@vue/runtime-core';

const components = [ElTable, ElTableColumn];

export const setupElement = (app: App) => {
  components.forEach((component) => {
    app.component(component.name, component);
  });
};

const install = (app: App) => {
  setupElement(app);
}

export default {
  install,
};
```

### What is Expected?
希望能够 按需打包element-plus 到js文件

### What is actually happening?
目前使用rollup打包，会将全部的element-plus包打包到 出口文件

**Comment by JeremyWuuuuu** [comment]
I think this is caused by mistakenly using babel config files. Since babel no longer support `.babel` file after v7.8.0, check this out:
https://babeljs.io/docs/en/options#rootmode

I used the exact same config like yours to run a minimal build, and it succeeded only with the required components.

Change your `.babel` file's name to `babel.config.js` then run it again. You should get the correct output.

**Comment by JeremyWuuuuu** [comment]
I also changed the file `babel.config.js`'s name to `.babel` then the output bundle contains the entire `element-plus` bundle, this also helped me verify my theory. 
If you have any further question, please feel free to reopen this issue and reach out to us. Thanks!
