### ISSUE TITLE
[Docs] [All] 官网的 playground 功能失效了

### ISSUE THREAD

**Issue by enjoy-myLife** [element-plus/element-plus#17986]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.0-beta.3`
- Element Plus Version: `2.8.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/button.html)

### Steps to reproduce

打开官网的playground在线运行100%复现，https://cdn.jsdelivr.net/npm/@vue/compiler-sfc@latest/dist/compiler-sfc.esm-browser.js静态文件请求失败

### What is Expected?

正常

### What is actually happening?

失效

### Additional comments

_(empty)_

**Comment by btea** [comment]
应该是网络问题，我这边可以正常打开。

![image](https://github.com/user-attachments/assets/f74b398f-1426-467d-a70e-b324410d574d)

**Comment by enjoy-myLife** [comment]
![image](https://github.com/user-attachments/assets/a425768e-4c66-4ff3-92f9-ed064fab666b)

应该不是网络问题，很奇怪唯独这一个文件访问不到

**Comment by btea** [comment]
应该就是网络问题，我不开梯子有时候就访问不了。

![image](https://github.com/user-attachments/assets/f660581d-ff53-4d8b-a66e-caeec847e69f)
