### ISSUE TITLE
[bug report] nesting of tooltip components and expansion of select component option

### ISSUE THREAD

**Issue by jsliu27** [element-plus/element-plus#1799]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
chrome89

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
上述链接为无效链接
el-tooltip组件嵌套el-select组件，option展开后，点击页面空白处，不能收起

### What is Expected?
点击空白处，能正常收起

### What is actually happening?
下面是实际用使用的代码
<el-tooltip
            placement="top"
            popper-class="user-tooltip"
            :disabled="testers.length == 0"
          >
            <template v-slot:content>
              <section v-for="(item, index) in testers" :key="index">
                <span>{{ getTestName(item.toString(), testersOptions) }}</span>
                <br />
              </section>
            </template> 
            <el-select
              :disabled="
                info.environment === 'TEST'
                  ? !info.authority.editTestTester
                  : !info.authority.editVerifyTester
              "
              clearable
              multiple
              filterable
              collapse-tags
              v-model="testers"
              @change="editTestMission('tester')"
              size="small"
              style="width: 55%"
              :title="getTestName(testers, testersOptions)"
            >
              <el-option
                v-for="item in testersOptions"
                :key="item.id"
                :label="item.userName"
                :value="item.id"
              >
              </el-option>
            </el-select>
         </el-tooltip>

**Comment by JeremyWuuuuu** [comment]
We need a reproducible code to debug, with vague informations, we cannot provide any help.

**Comment by jsliu27** [comment]
> 你好@ jsliu27。请点击此提供一个网上再现演示[链接](https://codepen.io/iamkun/pen/YzWMaVr)或最小GitHub的仓库。
> 
> 你好@ jsliu27，请提供一个可复现问题的链接以便于我们帮你排查问题。通过可以点击[此处](https://codepen.io/iamkun/pen/YzWMaVr)创建³³或者提供一个最小化的GitHub仓库。

你好，创建了一个测试地址：https://codepen.io/jsliu27/pen/wvgjWPb
问题：当点开select时，option展开，点击空白不会收起
期望：点击空白处 option收起

**Comment by JeremyWuuuuu** [comment]
This is triggered because you have made `select` as root trigger of two popups, which is not suggested to do so.
If you really needed to do things like this, then you should wrap the select inside of another tag to make it independent instead of trigger of two.
Based on your demo:
```vue
<el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
   <div class="wrapper-element">
      <el-select v-model="value" placeholder="请选择">
        <el-option
          v-for="item in options"
          :key="item.value"
          :label="item.label"
          :value="item.value">
        </el-option>
      </el-select>
  </div>
</el-tooltip>
```

**Comment by jsliu27** [comment]
> ```
>  class="wrapper-element"
> ```

Thank you very much

**Comment by jsliu27** [comment]
Thank you very much
