### ISSUE TITLE
[Component] [carousel] el-carousel组件遇上sticky属性显示层级错误

### ISSUE THREAD

**Issue by an78mK89fy** [element-plus/element-plus#17994]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.8.0`
- Browser / OS: `Microsoft Edge 版本 128.0.2739.42 (正式版本) (64 位) / 版本	Windows 11 专业版 版本号	23H2 安装日期	‎2024/‎02/‎21 操作系统版本	22631.4037 体验	Windows Feature Experience Pack 1000.22700.1027.0`
- Build Tool: `Vite`

### Related Component

- `el-carousel`

### Reproduction Link

[Github Repo](https://github.com/an78mK89fy/el-carousel-minBug.git)

### Steps to reproduce

npm run dev，向下滚轮，让走马灯el-carousel和设置了sticky的头部el-header交叉

### What is Expected?

el-carousel应该在设置了sticky的el-header下方，和el-main行为一致

### What is actually happening?

el-carousel跑到了el-header上方

### Additional comments

应该让button.el-carousel__arrow放在div.el-carousel__container下方，省去给button设置z-index=10，因为如果设置el-carousel的z-index=-1，el-carousel和el-header关系正确，但是button会仍然在el-header上方

**Comment by btea** [comment]
给 `el-header` 设置 `z-index`就可以了。这里不涉及到组件的问题，而是项目中布局的影响，自行在项目中调整就可以了。[参考链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbnRhaW5lcj5cbiAgICA8ZWwtaGVhZGVyPjwvZWwtaGVhZGVyPlxuICAgIDxlbC1tYWluPlxuICAgICAgPGVsLWNhcm91c2VsPlxuICAgICAgICA8ZWwtY2Fyb3VzZWwtaXRlbT5cbiAgICAgICAgICA8cD5cbiAgICAgICAgICAgIOW6lOivpeiuqWVsLWNhcm91c2Vs5ZKMZWwtbWFpbuS4gOagt++8jOi1sOWcqOiuvue9ruS6hnBvc2l0aW9u5YC8c3RpY2t555qEZWwtaGVhZGVy5LiL6Z2iXG4gICAgICAgICAgPC9wPlxuICAgICAgICAgIDxwPlxuICAgICAgICAgICAg5aaC5p6c6K6+572uZWwtaGVhZGVy55qEei1pbmRleD0xMe+8jOmCo+S5iOS8mumBruebluS9j2VsLXNjcm9sbGJhclxuICAgICAgICAgIDwvcD5cbiAgICAgICAgICA8cD5cbiAgICAgICAgICAgIOWmguaenOS9v+eUqGVsLWFmZml4IHBvc2l0aW9uPXRvcOWPiOS8muacieWFtuS7lumXrumimFxuICAgICAgICAgIDwvcD5cbiAgICAgICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICAgICAgPC9lbC1jYXJvdXNlbD5cbiAgICAgIDxkaXYgY2xhc3M9XCJib3hcIj48L2Rpdj5cbiAgICA8L2VsLW1haW4+XG4gIDwvZWwtY29udGFpbmVyPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLmVsLWhlYWRlciB7XG4gIGJhY2tncm91bmQtY29sb3I6IGRhcmtyZWQ7XG4gIHBvc2l0aW9uOiBzdGlja3k7XG4gIHRvcDogOHB4O1xuICB6LWluZGV4OiAxMTtcbn1cblxuLmVsLW1haW4ge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiBidXJseXdvb2Q7XG4gIG1hcmdpbjogMjBweDtcblxuICAuZWwtY2Fyb3VzZWwge1xuICAgIHdpZHRoOiA1MGR2dztcbiAgICBtYXJnaW46IGF1dG87XG5cbiAgICBkaXYuZWwtY2Fyb3VzZWxfX2NvbnRhaW5lciB7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiBibHVlO1xuICAgICAgO1xuICAgIH1cblxuICAgIHAge1xuICAgICAgZm9udC13ZWlnaHQ6IDkwMDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICB9XG4gIH1cbn1cblxuZGl2LmJveCB7XG4gIGhlaWdodDogMjAwZHZoO1xufVxuPC9zdHlsZT4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)
