### ISSUE TITLE
[Component] [affix] el-affix在edge下面滚动突然出现高度为22369600

### ISSUE THREAD

**Issue by gushenyi123** [element-plus/element-plus#18003]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.6.1`
- Browser / OS: `Microsoft Edge 版本 128.0.2739.42 (正式版本) (64 位)`
- Build Tool: `Vue CLI`

### Related Component

- `el-affix`

### Reproduction Link

[Link]()

### Steps to reproduce

1、屏幕分辨率在4K或者2k情况下，即大于1080P;
2、今天windows突然更新edge版本到128，导致的异常。以前在127版本及其以下都是正常的。保证edge版本在128版本及其以上。
3、使用方式：
 <el-affix target=".affix-container" :offset="80">  </el-affix>

### What is Expected?

支持4K或者2k分辨率下面显示正常

### What is actually happening?

支持4K或者2k分辨率下面显示正常

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
![image](https://github.com/user-attachments/assets/2464f2bc-08d2-4871-a31d-490785e8c2d7)
![image](https://github.com/user-attachments/assets/6954c251-dd8b-446e-93db-b08cafae626e)

Looks like nothing's wrong

**Comment by gushenyi123** [comment]
有空的时候我写一下，今天更新谷歌浏览器到128版本，也遇见了el-popover 在4K屏幕150%缩放下错位问题。
