### ISSUE TITLE
[Bug Report] Select with filterable has wrong dropdown options

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#1800]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
win10 chrome89

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-1rmx9

### Steps to reproduce
1. select any option
2. click select

### What is Expected?
the dropdown menu has all options

### What is actually happening?
the dropdown menu only has one option

@inottn Hello, this bug caused by your pr #1711. Could you help fix it?

**Comment by inottn** [comment]
Seems like a bug, I will fix it soon.
