### ISSUE TITLE
[Bug Report] Cannot select time from el-time-select when it has inputted first value with v-model

### ISSUE THREAD

**Issue by mecaota** [element-plus/element-plus#1801]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
MaxOSX / Chrome 89.0.4389.114（Official Build） （x86_64）

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/mecaota/pen/XWpzGpq

### Steps to reproduce
After set initial value to el-time-select with v-model, Cannot select time from pulldown menu.

### What is Expected?
If v-model have been set, I can select time from pulldown menu.

### What is actually happening?
If initial value with v-model is set, cannot select from pulldown menu(but can input)

**Comment by mecaota** [comment]
Maybe, #1800 is same bug as this

**Comment by kooriookami** [comment]
Yes, if you are confused about this, you can use 1.0.2-beta.36 for workaround.

**Comment by JeremyWuuuuu** [comment]
Fixed in #1811 .
