### ISSUE TITLE
[Component] [table] 可选择的树形数据，disable会被关联勾选

### ISSUE THREAD

**Issue by jiangjiang1208688179** [element-plus/element-plus#18021]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.8`
- Element Plus Version: `2.8.1`
- Browser / OS: `chrome 128.0.6613.84`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#%E5%8F%AF%E9%80%89%E6%8B%A9%E7%9A%84%E6%A0%91%E5%BD%A2%E6%95%B0%E6%8D%AE)

### Steps to reproduce

1.打开element-plus官网，https://element-plus.org/zh-CN/component/table.html#%E5%8F%AF%E9%80%89%E6%8B%A9%E7%9A%84%E6%A0%91%E5%BD%A2%E6%95%B0%E6%8D%AE;
2.查看示例【可选择的树形数据 2.8.0】；
3.checkStrictly 选择 false;
4.勾选单条复选框（选择的复选项存在有disable的子节点）

### What is Expected?

父节点和非disable的子节点可被选中，disable的子节点不能选中

### What is actually happening?

所有子节点均选中

### Additional comments

_(empty)_

**Comment by jiangjiang1208688179** [comment]
![image](https://github.com/user-attachments/assets/f0aec192-8e32-4d3f-b04f-f90ed71e5f6f)

**Comment by trry-hub** [comment]
el-table 非树形也有类似问题
