### ISSUE TITLE
[Component] vue3 defineComponent中render函数渲染el-menu>el-menu-item递归

### ISSUE THREAD

**Issue by hszl000** [element-plus/element-plus#18054]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.8.1`
- Browser / OS: `eg、Chrome`
- Build Tool: `Vite`

### Related Component

- `el-main`
- `el-menu-item`
- `el-sub-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgaCB9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCB7IEVsTWVudSwgRWxTdWJNZW51LCBFbE1lbnVJdGVtIH0gZnJvbSBcImVsZW1lbnQtcGx1c1wiO1xuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBuYW1lOiBcIkxheW91dFwiLFxuICBzZXR1cCgpIHtcbiAgICBjb25zdCBkYXRhID0gW1xuICAgICAge1xuICAgICAgICBpbmRleDogJzEnLFxuICAgICAgICBsYWJlbDogJ+mmlumhtScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpbmRleDogJzInLFxuICAgICAgICBsYWJlbDogJ+ivpuaDhScsXG4gICAgICAgIGNoaWxkcmVuOltcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpbmRleDogJzItMScsXG4gICAgICAgICAgICBsYWJlbDogJ+aWsOW7uicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpbmRleDogJzItMicsXG4gICAgICAgICAgICBsYWJlbDogJ+e8lui+kScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpbmRleDogJzItMycsXG4gICAgICAgICAgICBsYWJlbDogJ+abtOWkmicsXG4gICAgICAgICAgICBjaGlsZHJlbjpbXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICBpbmRleDogJzItMy0xJyxcbiAgICAgICAgICAgICAgICBsYWJlbDogJ+WPkeeOsCcsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICBpbmRleDogJzItMy0yJyxcbiAgICAgICAgICAgICAgICBsYWJlbDogJ+aOqOiNkCcsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBdLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF07XG5cbiAgICByZXR1cm4gKCkgPT5cbiAgICAgIGgoRWxNZW51LCB7XG4gICAgICAgIGVsbGlwc2lzOiB0cnVlLFxuICAgICAgICBjbGFzczogXCJlbC1tZW51LXBvcHBlci1kZW1vXCIsXG4gICAgICAgIG1vZGU6IFwiaG9yaXpvbnRhbFwiLFxuICAgICAgICBwb3BwZXJPZmZzZXQ6IDE2LFxuICAgICAgICBzdHlsZTogXCJtYXgtd2lkdGg6IDYwMHB4XCIsXG4gICAgICAgIGNvbGxhcHNlOiB0cnVlLFxuICAgICAgfSwgZGF0YS5tYXAoaXRlbSA9PiBoKFNpZGViYXJJdGVtLCB7IGtleTogaXRlbS5pbmRleCwgZGF0YTogaXRlbSB9KSkpO1xuICB9LFxufSk7XG5cbmNvbnN0IFNpZGViYXJJdGVtID0gZGVmaW5lQ29tcG9uZW50KHtcbiAgbmFtZTogJ1NpZGViYXJJdGVtJyxcbiAgcHJvcHM6IHtcbiAgICBkYXRhOiB7XG4gICAgICB0eXBlOiBPYmplY3QsXG4gICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICB9LFxuICB9LFxuICBzZXR1cChwcm9wcykge1xuICAgIGNvbnN0IHsgZGF0YSB9ID0gcHJvcHM7XG5cbiAgICBpZiAoZGF0YSAmJiBkYXRhLmNoaWxkcmVuPy5sZW5ndGgpIHtcbiAgICAgIHJldHVybiAoKSA9PlxuICAgICAgICBoKFxuICAgICAgICAgIEVsU3ViTWVudSxcbiAgICAgICAgICB7IGluZGV4OiBkYXRhLmluZGV4IH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdGl0bGU6ICgpID0+IGRhdGEubGFiZWwsXG4gICAgICAgICAgICBkZWZhdWx0OiAoKSA9PiBkYXRhLmNoaWxkcmVuLm1hcChpdGVtID0+IGgoU2lkZWJhckl0ZW0sIHsga2V5OiBpdGVtLmluZGV4LCBkYXRhOiBpdGVtIH0pKSxcbiAgICAgICAgICB9LFxuICAgICAgICApO1xuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4gKCkgPT5cbiAgICAgICAgaChFbE1lbnVJdGVtLCB7IGluZGV4OiBkYXRhLmluZGV4IH0sICgpID0+IGRhdGEubGFiZWwpO1xuICAgIH1cbiAgfSxcbn0pO1xuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

使用 tsx 或者 render+h函数渲染封装的el-menu组件（上方链接）出现递归渲染menu

### What is Expected?

不要递归

### What is actually happening?

递归渲染多个menu

### Additional comments

_(empty)_

**Comment by tolking** [comment]
ElMenu 中需要直接使用 ElMenuItem ElSubMenu 。内部暂时无法处理引用组件的情况

**Comment by hszl000** [comment]
感谢

在 2024-08-29 08:16:42，qiang ***@***.***> 写道：


ElMenu 中需要直接使用 ElMenuItem ElSubMenu 。内部暂时无法处理引用组件的情况
