### ISSUE TITLE
[Style] [scrollbar] [Component] [el-scrollbar] vue+vite+elementplus打包后浏览器报错

### ISSUE THREAD

**Issue by sumingyu1769** [element-plus/element-plus#18076]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.38`
- Element Plus Version: `2.8.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8ZWwtc2Nyb2xsYmFyIGFsd2F5cz5cbiAgICA8cD5cbiAgICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgICA8L3A+XG4gIDwvZWwtc2Nyb2xsYmFyPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

使用npm run build打包后，再使用npm run preview预览或者部署到nginx上预览的时候，F12控制台打印，报错[Deprecation]Custom state pseudo classes have been changed from ":--cui-scrollbar-color-contrast" to ":state(cui-scrollbar-color-contrast)". See more here: https://github.com/w3c/csswg-drafts/issues/4805

### What is Expected?

正常运行

### What is actually happening?

打印台报错，但并不影响使用

### Additional comments

--cui-scrollbar-color-contrast我不太清除是element的样式还是其他ui的样式，我只安装了elemenplus一个ui，另外安装了data-view可能影响的大屏可视化ui插件，但是我在搜索--cui-scrollbar-color-contrast样式的时候，并没有在node_modules里发现此类css样式，但是打印台报错了，并提供了一个element的论坛页（https://github.com/w3c/csswg-drafts/issues/4805），在vue中使用了el的el-scrollbar组件以及表格el-table的:scrollbar-always-on="true"属性。

**Comment by JuneOY** [comment]
我在使用el-select遇到了同样的问题
![image](https://github.com/user-attachments/assets/6133309a-2a45-46e7-81ee-18b310c543a2)

**Comment by sumingyu1769** [comment]
> 我在使用el-select遇到了同样的问题 ![image](https://private-user-images.githubusercontent.com/75666139/362620066-6133309a-2a45-46e7-81ee-18b310c543a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjQ2NTgsIm5iZiI6MTcyNDkyNDM1OCwicGF0aCI6Ii83NTY2NjEzOS8zNjI2MjAwNjYtNjEzMzMwOWEtMmE0NS00NmU3LTgxZWUtMThiMzEwYzU0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5MzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMzViOTU0YTViMWJiNGRmMzAxYWFmMjRjMWZlZjZlMzI2MmZhNTYyNGFiYzRlMjI0NDY1NzdhMjMwZjU5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zd4WWUKLl59xuDaKCu-ve5VqikS7NQHzxPxUpJa1u6c)

haha

**Comment by btea** [comment]
Please provide a reproducible code.

**Comment by sumingyu1769** [comment]
> Please provide a reproducible code.

I don't even know how to report an error or how to reproduce it？

**Comment by btea** [comment]
You can create a new project, make sure this error will occur, and then submit the relevant code to the GitHub repository.

**Comment by JuneOY** [comment]
forgive my recklessness, I will follow the instructions and reproduce it later

**Comment by btea** [comment]
It’s okay, just provide it when it’s convenient for you.

**Comment by JuneOY** [comment]
Vue version 3.0.0, element plus version 1.0.2-beta.69, do you still support maintenance for lower versions? This is a small demo I wrote, and introducing the element style in the main file will result in errors
[https://github.com/JuneOY/vue-element-select](url)

**Comment by btea** [comment]
Do you know if this problem still exists in the new version? Versions are constantly updated, and we only maintain the latest version. Do you know if this problem still exists in the new version? Versions are updated continuously, and we only maintain the latest version.

**Comment by Chinegoodman** [comment]
same problem

**Comment by wanghuipeng** [comment]
> 我在使用el-select遇到了同样的问题 ![image](https://private-user-images.githubusercontent.com/75666139/362620066-6133309a-2a45-46e7-81ee-18b310c543a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDgxOTcsIm5iZiI6MTczMzcwNzg5NywicGF0aCI6Ii83NTY2NjEzOS8zNjI2MjAwNjYtNjEzMzMwOWEtMmE0NS00NmU3LTgxZWUtMThiMzEwYzU0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjM4YmIzYjAzY2M2ODQ2Mjk4MzYwNGQ0MjM3MDI4MTE0Njk3NTNlNGYyYzA5ZGMwMjczY2I3MGY1MmFjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mg7zMBAYsRyNTUSX4ooEKt3Vtm6qyxwMNdwXxFpkoJA)

解决了吗？我也遇到同样问题

**Comment by JuneOY** [comment]
> > 我在使用 el-select 时遇到了同样的问题![图像](https://private-user-images.githubusercontent.com/75666139/362620066-6133309a-2a45-46e7-81ee-18b310c543a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDgxOTcsIm5iZiI6MTczMzcwNzg5NywicGF0aCI6Ii83NTY2NjEzOS8zNjI2MjAwNjYtNjEzMzMwOWEtMmE0NS00NmU3LTgxZWUtMThiMzEwYzU0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjM4YmIzYjAzY2M2ODQ2Mjk4MzYwNGQ0MjM3MDI4MTE0Njk3NTNlNGYyYzA5ZGMwMjczY2I3MGY1MmFjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mg7zMBAYsRyNTUSX4ooEKt3Vtm6qyxwMNdwXxFpkoJA)
> 
> 解决了吗？我也遇到了同样的问题

没有 项目更换了其他ui 你可以尝试更新el版本或者升级到最新版本

**Comment by wanghuipeng** [comment]
> > > 我在使用 el-select 时遇到了同样的问题![图像](https://private-user-images.githubusercontent.com/75666139/362620066-6133309a-2a45-46e7-81ee-18b310c543a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDgxOTcsIm5iZiI6MTczMzcwNzg5NywicGF0aCI6Ii83NTY2NjEzOS8zNjI2MjAwNjYtNjEzMzMwOWEtMmE0NS00NmU3LTgxZWUtMThiMzEwYzU0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjM4YmIzYjAzY2M2ODQ2Mjk4MzYwNGQ0MjM3MDI4MTE0Njk3NTNlNGYyYzA5ZGMwMjczY2I3MGY1MmFjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mg7zMBAYsRyNTUSX4ooEKt3Vtm6qyxwMNdwXxFpkoJA)
> > 
> > 
> > 解决了吗？我也遇到了同样的问题
> 
> 没有 项目更换了其他ui 你可以尝试更新el版本或者升级到最新版本

thanks for your reply

**Comment by btea** [comment]
@wanghuipeng 你使用的版本多少？能提供一个复现示例吗？

**Comment by btea** [comment]
应该是同一个问题，在2.2.0版本已经修复了。

https://github.com/element-plus/element-plus/issues/18493#issuecomment-2413292557
