### ISSUE TITLE
[Feature Request] 添加一个el-split组件，

### ISSUE THREAD

**Issue by whenTheMorningDark** [element-plus/element-plus#18081]
### Existing Component
No

### Component Name
el-split

### Description
该组件是用于左右伸缩，或者上下伸缩，嵌套伸缩等功能

**Comment by btea** [comment]
Can you describe it in more detail, such as the approximate design effect, supported configurations, and specific usage scenarios?

**Comment by whenTheMorningDark** [comment]
> Can you describe it in more detail, such as the approximate design effect, supported configurations, and specific usage scenarios?

![image](https://github.com/user-attachments/assets/95d3fc9a-dab9-47ce-be00-ea9a036185cd)
![image](https://github.com/user-attachments/assets/33d59123-7321-49fb-b372-f8a97c936f22)

```js
 <el-split :style="{
        height: '200px',
        width: '100%',
        minWidth: '500px',
        border: '1px solid #ddd'
      }"
      v-model:size="size"
      min="80px"
    >
      <template #left>
        left
      </template>
      <template #right>
        right
      </template>
    </el-split>
```
类似这样的这样的方式，因为我在业务中大量使用，也基于element-plus二开过，我可以提供pr

**Comment by kooriookami** [comment]
很实用的组件，欢迎提交PR

**Comment by whenTheMorningDark** [comment]
> 很实用的组件，欢迎提交PR

ok

**Comment by wkl007** [comment]
应该类似这个 https://yui.vip/components/split

**Comment by whenTheMorningDark** [comment]
> 应该类似这个 https://yui.vip/components/split

哇 这个真的很不错的ui框架

**Comment by wkl007** [comment]
Ant Design 也有这个组件了 https://ant.design/components/splitter-cn
