### ISSUE TITLE
[Feature Request] Cannot find module '@vue/shared'

### ISSUE THREAD

**Issue by caesarding07** [element-plus/element-plus#1808]
### Existing Component
Yes

### Component Name
Cannot find module '@vue/shared'

### Description
使用nuxt导入element plus 的时候，显示这个错误
```
# node_modules/element-plus/lib/utils/util.js
var vue = require('vue');
var shared = require('@vue/shared'); 
var isServer = require('./isServer');
```

**Comment by JeremyWuuuuu** [comment]
So here is the thing, `@vue/shared` seems like a underlaying library which the entire `vue` bundle depends on, but I think we need to add this to our dependency list, for temporary fix, could you do something like:

```bash
$ yarn add @vue/shared
```

or if you use npm

```bash
$ npm install @vue/shared
```

**Comment by caesarding07** [comment]
Thank you so much! 
I had installed NUXT again. and I think I have found the reason why causes this. 'NUXT' is deponed on vue2.0 and no dependent named vue3.0 on the 'package.json', so it is not crazy that Cannot find module '@vue/shared'.Maybe I need to add vue3.0 by myself.

```json
#package.json
  "dependencies": {
    "@nuxt/content": "^1.14.0",
    "@nuxtjs/axios": "^5.13.1",
    "core-js": "^3.9.1",
    "element-ui": "^2.15.1",
    "nuxt": "^2.15.3"
  },
```

**Comment by JeremyWuuuuu** [comment]
So I am going to close this issue since it had been resolved.
