### ISSUE TITLE
[Feature Request] Add indeterminate progress bar state

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#1814]
### Existing Component
Yes

### Component Name
el-progress

### Description
Many client-side promise based tasks and server-side implementations will not allow for polling in order to be able to update the progress bar percentage on the fly. In this case, it would be best to have an indeterminate progress bar state like many other frameworks.

Example:

![PuC7J](https://user-images.githubusercontent.com/4075314/114331419-f27d9d80-9b11-11eb-818a-faa86b8e25bb.gif)

**Comment by JeremyWuuuuu** [comment]
Well, I think we could, but for now I couldn't make any promise on when this is going to be implemented because we are currently facing resource issue.
If anyone wants to help implementing this feature, please reach out ;)

**Comment by rottenpen** [comment]
#1832 indeterminate line progress done

**Comment by Giwayume** [comment]
@JeremyWuuuuu I assume once code is in dev, it's set to be in a future release. Closing the issue.
