### ISSUE TITLE
[Bug Report] The message box opens repeatedly by pressing enter when it opens

### ISSUE THREAD

**Issue by Wuge11** [element-plus/element-plus#1815]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
macOS/chrome

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/wuge11/pen/PoWQQbR

### Steps to reproduce
1.click button
2.press enter

### What is Expected?
close message box

### What is actually happening?
reopen message box

**Comment by JeremyWuuuuu** [comment]
Seems like a bug, by the way, space won't trigger this issue, seemed like the event somehow get passed through the button element then triggered the button's `onClick` event again.

**Comment by Wuge11** [comment]
> Seems like a bug, by the way, space won't trigger this issue, seemed like the event somehow get passed through the button element then triggered the button's `onClick` event again.

OK, thank you for your reply
