### ISSUE TITLE
[Bug Report] from 1.0.2-beta.37, webstorm warn el-* as unknown html tag

### ISSUE THREAD

**Issue by languanghao** [element-plus/element-plus#1821]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
win10 x64

### Vue version
3.0.9

### Reproduction Link
none

### Steps to reproduce
1. upgrade element-plus to 1.0.2-beta.37 or higher
2. webstorm 2021.1 warn el-* as unknown html tag

### What is Expected?
webstrom should recognize el-* components

### What is actually happening?
webstorm 2021.1 warn el-* as unknown html tag

**Comment by JeremyWuuuuu** [comment]
Yes, this was a mistake that we made, we have improved our IDE support builder but forgot to include it into the build process, the next release should be normal. See the PR here: #1802

**Comment by languanghao** [comment]
@JeremyWuuuuu @iamkun  same problem appare again  in element-plus 1.1.0-beta.18.

**Comment by languanghao** [comment]
@jectychen It seems fixed in version 1.1.0-beta.19, maybe this pr #3718 ?
