### ISSUE TITLE
[Component] [select-v2] ElSelectV2: interacting with elements in custom header slot then closing the dropdown doesn't remove focus

### ISSUE THREAD

**Issue by em1382** [element-plus/element-plus#18235]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.1`
- Element Plus Version: `2.8.2`
- Browser / OS: `Firefox/130.0/Windows NT 10.0; Win64; x64; rv:130.0`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/select-v2.html#header-of-the-dropdown)

### Steps to reproduce

This bug is actually present in the docs!

1. Go to https://element-plus.org/en-US/component/select-v2.html#header-of-the-dropdown.
2. Open `ElSelectV2`'s dropdown.
3. Click "All" `ElCheckbox`.
4. Click outside to close the dropdown.
5. Element remains focused.

### What is Expected?

The element should lose focus on click outside after interacting with header elements (same issue is present for `ElTabs`, `ElRadioGroup`, etc).

### What is actually happening?

The element isn't losing focus when clicking outside, presumably because it already has "lost focus" on header element interaction.

### Additional comments

Thanks for the awesome project!

**Comment by DDDDD12138** [comment]
`ElSelect` also has the same issue. Adding the `filterable` attribute makes it easier to observe whether the component has lost focus.
