### ISSUE TITLE
[feature request] El input is used in El table. El input will lose focus after inputting characters each time and cannot input continuously

### ISSUE THREAD

**Issue by oydf1994** [element-plus/element-plus#1824]
### Existing Component
Yes

### Component Name
1.0.2-beta.33

### Description
谷歌浏览器
  <el-form-item label="text">
            <el-table :data="form.detail" border style="width: 100%">
              <el-table-column label="text" winth="auto">
                <template #default="scope">
                  <el-input
                    v-model="scope.row.text"
                  ></el-input>
                </template>
               </el-table-column>
         </el-table>
   </el-form-item>

**Comment by oydf1994** [comment]
<el-form-item label="text">
            <el-table :data="form.detail" border style="width: 100%">
              <el-table-column label="text" winth="auto">
                <template #default="scope">
                  <el-input
                    v-model="scope.row.text"
                  ></el-input>
                </template>
             </el-table-column>
         </el-table>
      </el-form-item>

**Comment by rebider** [comment]
我想问你解决了没有 @oydf1994

**Comment by JeremyWuuuuu** [comment]
duplicated with #1739 
The current simplest solution is that you use `v-focus` directive like this:

```ts
app.directive({
  mounted(el) {
    el.focus()
  }
})
```
Then use it like this:
`<el-input v-focus />`

**Comment by JeremyWuuuuu** [comment]
But this won't work when you have multiple input items.

**Comment by JeremyWuuuuu** [comment]
I have fixed it in #1835

**Comment by JeremyWuuuuu** [comment]
We will release a hot patch very soon today. You can upgrade to that version and get this issue fixed.

**Comment by JeremyWuuuuu** [comment]
https://github.com/element-plus/element-plus/actions/runs/746929605 if you want to keep an eye on the release process.

**Comment by JeremyWuuuuu** [comment]
After the release gets finished, upgrade to `beta.40` should solve your issue
