### ISSUE TITLE
[Component] [image, image-viewer] el-image预览图片，在表格里预览图片，表格会覆盖预览的图片

### ISSUE THREAD

**Issue by h723999742** [element-plus/element-plus#18240]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.3.1`
- Browser / OS: `Chrome/128.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-image-viewer`

### Reproduction Link

[Link](https://暂时没上线)

### Steps to reproduce

表格自定义

### What is Expected?

不覆盖

### What is actually happening?

覆盖

### Additional comments

_(empty)_

**Comment by Fuphoenixes** [comment]
Duplicated of https://github.com/element-plus/element-plus/issues/16514
