### ISSUE TITLE
[Component] [All] <el-progress的striped参数设置了后背景条纹不重复，只有一条

### ISSUE THREAD

**Issue by Allis-well** [element-plus/element-plus#18241]
![企业微信截图_17260188904464](https://github.com/user-attachments/assets/6e7d330a-ef67-415a-9126-b31b70806bf9)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0`
- Element Plus Version: `2.8.1`
- Browser / OS: `chrome128.0.6613.120 火狐也是 `
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgPGVsLXByb2dyZXNzXG4gICAgICAgICAgICAgIDp0ZXh0LWluc2lkZT1cInRydWVcIlxuICAgICAgICAgICAgICA6c3Ryb2tlLXdpZHRoPVwiMjRcIlxuICAgICAgICAgICAgICA6cGVyY2VudGFnZT1cIjIzXCJcbiAgICAgICAgICAgICAgY29sb3I9XCJyZ2JhKDY5LCAxMjAsIDIzNywgMC44NSlcIlxuICAgICAgICAgICAgICBzdHJpcGVkXG4gICAgICAgICAgICAgIHN0cmlwZWQtZmxvd1xuICAgICAgICAgICAgLz5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjcuMC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjcuMC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjMuMC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy4zLjAvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy4wL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjAvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、input <el-progress
              :text-inside="true"
              :stroke-width="24"
              :percentage="currentCaseRadio"
              color="rgba(69, 120, 237, 0.85)"
              striped
            />

### What is Expected?

texture can full progress

### What is actually happening?

texture just one column

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
Can you provide more information? It looks fine in the playground.

![image](https://github.com/user-attachments/assets/849e6977-4b62-4108-9c6d-d6437e3f0c09)

**Comment by Allis-well** [comment]
I don't know if there is a compatibility issue with other components. I haven't made any style changes, and even I just want the texture to cover the line, but manual changes don‘t work.

`{
  "name": "cisytem",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "start": "node index.js",
    "server": "nodemon index.js --ignore client"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "@vue/cli-service": "^5.0.8",
    "animate.css": "^4.1.1",
    "axios": "^1.6.0",
    "clipboard": "^2.0.0",
    "cross-env": "^7.0.3",
    "easy-typer-js": "^2.x",
    "echarts": "^5.5.0",
    "element-plus": "2.8.1",
    "highlight.js": "^11.4.0",
    "markdown-it": "^12.0.6",
    "mavon-editor": "^3.x.x",
    "moment": "^2.29.1",
    "pinia": "^2.1.0",
    "vue": "^3.4.0",
    "vue-avatar-cropper": "^6.0",
    "vue-axios": "^3.4.0",
    "vue-router": "^4.0.0",
    "vue-social-share": "^0.0.3",
    "vuetify": "^3.7.0",
    "vuex": "^4.0.0",
    "vuex-persistedstate": "^4.1.0"
  },
  "devDependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "animate.css": "^4.1.1",
    "axios": "^1.6.0",
    "clipboard": "^2.0.0",
    "cross-env": "^7.0.3",
    "easy-typer-js": "^2.x",
    "echarts": "^5.5.0",
    "element-plus": "2.8.1",
    "highlight.js": "^11.4.0",
    "markdown-it": "^12.0.6",
    "mavon-editor": "^3.x.x",
    "moment": "^2.29.1",
    "pinia": "^2.1.0",
    "sass": "^1.78.0",
    "sass-loader": "^16.0.1",
    "vue": "^3.5.4",
    "vue-avatar-cropper": "^6.0",
    "vue-axios": "^3.4.0",
    "vue-router": "^4.0.0",
    "vue-social-share": "^0.0.3",
    "vuetify": "^3.7.0",
    "vuex": "^4.0.0",
    "vuex-persistedstate": "^4.1.0",
    "webpack": "^5.94.0"
  }
}`

> import { createApp } from 'vue';
import App from "./App.vue";
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import * as ElementPlusIconsVue from '@element-plus/icons-vue'
import router from "./router";
import store from "./store";
import vuetify from "./plugins/vuetify";
import axios from "axios";
import VueAxios from "vue-axios";
import ToastPlugin from "./components/toast/index";
const app = createApp(App);
for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
  app.component(key, component)
}
app.use(ElementPlus);
app.use(router);
app.use(store);
app.use(vuetify);
app.use(VueAxios, axios);
app.use(ToastPlugin);
app.config.productionTip = false;
router.beforeEach((to, from, next) => {
  if (to.meta.title) {
    document.title = to.meta.title;
  }
  next();
});
router.afterEach(() => {
  window.scrollTo({
    top: 0,
    behavior: "instant"
  });
});
axios.interceptors.response.use(
  function(response) {
    switch (response.data.code) {
      case 400:
        break;
    }
    return response;
  },
  function(error) {
    return Promise.reject(error);
  }
);
app.mount('#app');
![企业微信截图_17260226872449](https://github.com/user-attachments/assets/f8f43c4e-2673-458a-9d01-43455f43a0b4)

**Comment by Allis-well** [comment]
I have reviewed the CSS style of this component and I believe it should include the phrase 'background repeat: no repeat;'

.el-progress-bar__inner--striped{background-image:linear-gradient(45deg,rgba(0,0,0,.1) 25%,transparent 0,transparent 50%,rgba(0,0,0,.1) 0,rgba(0,0,0,.1) 75%,transparent 0,transparent);background-size:1.25em 1.25em}

**Comment by Allis-well** [comment]
I have already resolved it, thank you very much

::v-deep .el-progress-bar__inner--striped {
  background-repeat: repeat; 
}
