### ISSUE TITLE
[Docs] [table-v2] “table-v2.scss”There are declaration and nesting errors in the document

### ISSUE THREAD

**Issue by janaMXCX** [element-plus/element-plus#18254]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.4`
- Element Plus Version: `2.8.2`
- Browser / OS: `windows 11`
- Build Tool: `Other`

### Related Component

- `el-table-v2`

### Reproduction Link

[Github Repo](https://github.com/janaMXCX/element-plus-littlebug)

### Steps to reproduce

###run "npm install"
Then the run will be raised ...

### What is Expected?

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

Debugger listening on ws://127.0.0.1:5858/b4d33811-9535-4a72-8bf0-065c510388ef
For help, see: https://nodejs.org/en/docs/inspector

### What is actually happening?

Debugger listening on ws://127.0.0.1:5858/8fafe4f5-1ae9-44d6-bb53-457ef6e35dda
For help, see: https://nodejs.org/en/docs/inspector
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
44  │ ┌   .#{$namespace}-vl__vertical,
45  │ │   .#{$namespace}-vl__horizontal {
46  │ │     z-index: -1;
47  │ │   }
    │ └─── nested rule
... │
90  │       z-index: 1;
    │       ^^^^^^^^^^ declaration
    ╵
    node_modules\element-plus\theme-chalk\src\table-v2.scss 90:5       @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 88:9  e()
    node_modules\element-plus\theme-chalk\src\table-v2.scss 84:3       @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5  b()
    node_modules\element-plus\theme-chalk\src\table-v2.scss 54:1       @use
    node_modules\element-plus\theme-chalk\src\index.scss 85:1          @use
    src\renderer\src\assets\cust-elementplus.scss 3:1                  root stylesheet

### Additional comments

In your code, the z-index declaration after the nested rule needs to be moved before the nested rule, or wrapped in &{} to ensure compatibility with future versions of Sass.

**Comment by janaMXCX** [comment]
![dd36d86b-77ca-4af7-9c2e-ba064afa8070](https://github.com/user-attachments/assets/9d904fc7-eada-4e64-b1b3-bb903ebf9213)
At the moment, only "z-index = 1" in this position will be incorrect when using "npm install element-plus" to download in the node environment
![ae9277e7-196d-45ce-88f6-2f9e74cc29ee](https://github.com/user-attachments/assets/1149ff49-2c9a-4535-a332-88d2b428de29)
This is no problem with the source code on github
![ed538839-94c7-4adf-9164-634ddce1f341](https://github.com/user-attachments/assets/ca0bee00-67b3-4e8b-91ac-430c2184e62a)
This is my own call, there was a problem when the call happened

**Comment by btea** [comment]
Thanks for the feedback, it has been fixed in #18218.
