### ISSUE TITLE
[Component] [select] select组件在被外部修改model value后，显示label只显示了value，且下拉框内的option的状态还是上一个value被选中的状态

### ISSUE THREAD

**Issue by chenyuncai** [element-plus/element-plus#18274]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.4`
- Element Plus Version: `2.8.3`
- Browser / OS: `chrome 128（最新的）`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSdcblxuY29uc3QgaXRlbSA9IHJlZignMScpXG5jb25zdCBsaXN0ID0gWycxJywnMicsJzMnLCc0J11cbmNvbnN0IGFjdGlvbiA9ICgpID0+IHtcbiAgaXRlbS52YWx1ZSA9IGxpc3RbKE51bWJlcihpdGVtLnZhbHVlKSkgJSBsaXN0Lmxlbmd0aF1cbn1cbi8qKlxuICog5aSN546w77yaXG4xLiDpu5jorqTliJ3lp4vljJblkI7vvIzku7vmhI/liIfmjaLvvIzpg73mmK/lr7nnmoTvvIxcbjIuIOS4i+aLieahhuato+W4uOmAieaLqeWAvOWQju+8jOS7u+aEj+WIh+aNou+8jOmDveaYr+WvueeahFxuMy4g5Zyo5LiL5ouJ5qGG5YaF6L6T5YWl5LiA5Liq5a2X5q+N5pCc57Si5ZCO77yM5peg6K665piv5ZCm5Y676YCJ5a6a5LiA5Liq77yM5ZCO57ut5Lu75oSP5YiH5o2i77yM6YO95Lya5pi+56S66ZSZ6K+vbGFiZWzkuLp2YWx1ZVxuICovXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIHt7ZXBWZXJzaW9ufX1cbiAgICB7e3Z1ZVZlcnNpb259fVxuICAgIDxFbEJ1dHRvbiBAY2xpY2s9XCJhY3Rpb25cIj7liIfmjaI8L0VsQnV0dG9uPlxuICAgIDxDb21wIHYtbW9kZWw9XCJpdGVtXCIgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy41LjQvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQDMuNS40L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMy9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4zL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIkNvbXAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cclxuaW1wb3J0IHsgY29tcHV0ZWQsIHJlZiB9IGZyb20gJ3Z1ZSdcclxuY29uc3QgTGFuZ3VhZ2VMaXN0ID0gW1xyXG4gIHt2YWx1ZTogJzEnLCBsYWJlbDogJ2EnfSxcclxuICB7dmFsdWU6ICcyJywgbGFiZWw6ICdiJ30sXHJcbiAge3ZhbHVlOiAnMycsIGxhYmVsOiAnYyd9LFxyXG4gIHt2YWx1ZTogJzQnLCBsYWJlbDogJ2QnfSxcclxuXVxyXG5jb25zdCBsYW5nU2VhcmNoS2V5ID0gcmVmKCcnKVxyXG5jb25zdCBsYW5ndWFnZUxpc3QgPSBjb21wdXRlZCgoKSA9PiBMYW5ndWFnZUxpc3QuZmlsdGVyKChpdGVtKSA9PiBpdGVtLmxhYmVsPy5pbmNsdWRlcyhsYW5nU2VhcmNoS2V5LnZhbHVlKSkpXHJcbmNvbnN0IGxhbmcgPSBkZWZpbmVNb2RlbDxzdHJpbmc+KClcclxuY29uc3QgZmlsdGVyTWV0aG9kID0gKGtleTogc3RyaW5nKSA9PiB7XHJcbiAgbGFuZ1NlYXJjaEtleS52YWx1ZSA9IGtleVxyXG59XHJcbjwvc2NyaXB0PlxyXG5cclxuPHRlbXBsYXRlPlxyXG4gIDxFbFNlbGVjdCBjbGFzcz1cIiF3LVsxNjBweF1cIiB2LW1vZGVsPVwibGFuZ1wiIGZpbHRlcmFibGUgY2xlYXJhYmxlIDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVyTWV0aG9kXCJcclxuICAgIDpkZWZhdWx0LWZpcnN0LW9wdGlvbj1cInRydWVcIj5cclxuICAgIDwhLS0gYnVnOiDlpJbpg6jkv67mlLlsYW5n5ZCO77yMc2VsZWN057uE5Lu25pyq5pi+56S65pyA5paw55qEbGFiZWzmlofmoYggLS0+XHJcbiAgICA8RWxPcHRpb24gdi1mb3I9XCJpdGVtIGluIGxhbmd1YWdlTGlzdFwiIDprZXk9XCJpdGVtLnZhbHVlXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIj5cclxuICAgICAgPGRpdiBjbGFzcz1cImZsZXgganVzdGlmeS1iZXR3ZWVuIGl0ZW1zLWNlbnRlclwiPlxyXG4gICAgICAgIDxzcGFuPnt7IGl0ZW0ubGFiZWwgfX08L3NwYW4+XHJcbiAgICAgICAgPHNwYW4+e3sgaXRlbS52YWx1ZSB9fTwvc3Bhbj5cclxuICAgICAgPC9kaXY+XHJcbiAgICA8L0VsT3B0aW9uPlxyXG4gIDwvRWxTZWxlY3Q+XHJcbjwvdGVtcGxhdGU+XHJcbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 创建一个按钮和一个下拉框，下拉框正常渲染多个选项
2. 点击按钮循环切换下拉框的当前值
3. 下拉框搜索后选定一个新的值
4. 再次点击按钮循环切换下拉框的值，此时label显示为value了

### What is Expected?

外部切换select组件的model值时，select组件正确显示label

### What is actually happening?

搜索过滤后，外部再次修改value，select组件没有显示正确的label

### Additional comments

_(empty)_

**Comment by rubbishmaker** [comment]
这个应该属于预期内的现象，原因是options每次搜索完都会动态更新。

**Comment by chenyuncai** [comment]
> 这个应该属于预期内的现象，原因是options每次搜索完都会动态更新。

不是的哦，应该是没考虑到这个场景的一种bug，不能因为搜索了一次，就不能在外部组件里修改这个v-model的值了。

**Comment by Mookiepiece** [comment]
在你的示例里选项是用 `filter` + `v-for`  在物理层面屏蔽的，选项实打实地在组件树中消失了，所以没查找到是预期现象。

如果官方要支持，那么"缓存所有曾经的选项"的尽头就是爆内存。要不然就不能用 `filter` + `v-for`

我个人觉得是 `filter-method` 这个 prop 的存在就是个 bug，因为没有配套的推荐用法。

针对这个问题我想到两个解法：


直接整个组件重开，搜索字符串的状态就归零了，这样就不会缺斤少两了。

```js
const a = ref(0)
const action = () => {
  a.value++
  item.value = list[(Number(item.value)) % list.length]
}
`<Comp v-model="item" :key="a" />`
```

更加激进的做法是使用 `v-show` + `disabled`，这样选项就不会物理屏蔽了只是看不见，~~别和别人说是我教的~~

```html

<ElOption
  v-for="item in [
    {value: '1', label: 'a'},
    {value: '2', label: 'b'},
    {value: '3', label: 'c'},
    {value: '4', label: 'd'},
  ]"
  v-show="item.label?.includes(langSearchKey)"
  :disabled="item.label?.includes(langSearchKey)"

  :key="item.value" :value="item.value" :label="item.label">
  <div class="flex justify-between items-center">
    <span>{{ item.label }}</span>
    <span>{{ item.value }}</span>
  </div>
</ElOption>

```

或者你看能不能改掉 item.label 属性改成容易搜出来的字符，并仅使用 filterable 属性。

**Comment by chenyuncai** [comment]
是的，目前准备用key刷新渲染方式。不用filterable的原因是我这边这个list有点大，一千条，怕影响渲染性能。感谢回复

**Comment by CherishTheYouth** [comment]
有解法的issue 可以顺手关掉额
