### ISSUE TITLE
### Autocomplete

### ISSUE THREAD

**Issue by FFFFof7** [element-plus/element-plus#183]
I can do this

**Comment by JeremyWuuuuu** [comment]
Hi, @FFFFof7 , if you wish to work on this component, you can simply fork this repo and get started, also, before you get started, I'd like to ask you to review the original component see if there's any dependency that might block you on this.

**Comment by bmfs** [comment]
Duplicated with #206

**Comment by JeremyWuuuuu** [comment]
@FFFFof7 Hi, it seems like the guy who implemented input has already implemented this components #216 , so I am closing this issue since there were no updates from you
