### ISSUE TITLE
[Component] [date-picker] el-date-pick 下拉面板显示的位置不正确

### ISSUE THREAD

**Issue by web-ning** [element-plus/element-plus#18305]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.6`
- Element Plus Version: `2.8.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCIgbGFiZWwtd2lkdGg9XCJhdXRvXCIgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4OyBwYWRkaW5nLXRvcDogMTUwcHhcIj5cbiAgICAgIDxlbC1mb3JtLWl0ZW0gIGxhYmVsPVwiQWN0aXZpdHlcIj5cbiAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cImZvcm0udlwiXG4gICAgICAgIHR5cGU9XCJkYXRlcmFuZ2VcIlxuICAgICAgICA6c2hvcnRjdXRzPVwic2hvcnRjdXRzXCJcbiAgICAgICAgOnBvcHBlci1vcHRpb25zPVwieyBwbGFjZW1lbnQ6ICdib3R0b20nIH1cIlxuICAgICAgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG9ydGN1dHMgPSBbXG4gIHtcbiAgICB0ZXh0OiAnTCcsXG4gICAgdmFsdWU6ICgpID0+IHtcbiAgICAgIHJldHVybiBbJycsICcnXVxuICAgIH0sXG4gIH1cbl1cbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7XG4gIHY6ICcnXG59KVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

<template>
  <el-form :model="form" label-width="auto" style="max-width: 600px; padding-top: 150px">
      <el-form-item  label="Activity">
       <el-date-picker
        v-model="form.v"
        type="daterange"
        :shortcuts="shortcuts"
        :popper-options="{ placement: 'bottom' }"
      />
    </el-form-item>
  </el-form>
</template>

<script lang="ts" setup>
import { reactive } from 'vue'

const shortcuts = [
  {
    text: 'L',
    value: () => {
      return ['', '']
    },
  }
]
const form = reactive({
  v: ''
})
</script>

### What is Expected?

日期范围框下拉面板位于下侧

### What is actually happening?

日期范围框下拉面板位于右侧；下方有足够的空间且特意设置placement: 'bottom'，但当日期范围框上侧和右侧有足够的空间时，下拉面板依旧强制显示在右侧

### Additional comments

最小复现环境的链接 =》 限制长度的太短了，差点写不出可提交的示例

![image](https://github.com/user-attachments/assets/89e936b7-8617-4d09-909b-6ca9735f27dd)

**Comment by btea** [comment]
![image](https://github.com/user-attachments/assets/41202598-aa4e-4398-a220-4411c0dba87e)

我尝试了一下你提供的链接，是可以的。

**Comment by web-ning** [comment]
当日期范围框上侧和右侧有足够的空间时

**Comment by web-ning** [comment]
![image](https://github.com/user-attachments/assets/0aa99db5-1a6c-4251-8b31-062a03206e80)
![image](https://github.com/user-attachments/assets/6ba06f33-03c3-46a2-a5a0-3817fac5f5cd)

往左拖拽，以增大右侧空间

**Comment by btea** [comment]
还是未能复现。🤔
![image](https://github.com/user-attachments/assets/64b60229-0f16-4f21-bbc3-4e7f9c96e704)

**Comment by web-ning** [comment]
![image](https://github.com/user-attachments/assets/c479f12e-ba04-4c9a-b78d-4ba1a467c738)

![image](https://github.com/user-attachments/assets/309f543d-a7d2-49c9-a170-da950e08f4e0)
你的屏幕分辨率是否过于小，目测你的依旧放不下，
max-width: 100px; 设小一点看看

**Comment by btea** [comment]
确实如此。

**Comment by web-ning** [comment]
好的，目前我使用的element-plus@2.6.0，直到目前最新版2.8.3；此问题依旧存在

**Comment by btea** [comment]
`el-date-picker`目前好像不支持配置`placement`，可以新增一下。你有兴趣创建一个PR吗？

**Comment by btea** [comment]
@web-ning 我又看了一下，表现好像是正常的，设置`bottom`时，正常面板应该出现在下面，且是居中的，但下面的空间居中放不下，所以适应`fallback-placement`变成在右边展开了。如果你设置成`bottom-start`或者设置`bottom`且左边有一定的空间能让面板居中显示就会一直在下面。

**Comment by web-ning** [comment]
![image](https://github.com/user-attachments/assets/a334c77b-5f38-4a85-93bf-c6f504f5df4a)
下方完全放的下哈，这么大空间还不够放的？

**Comment by btea** [comment]
设置`bottom`时，会在下方x轴方向居中，上面的示例要在x轴方向居中，左侧空间不够。
![image](https://github.com/user-attachments/assets/8c1b5649-c6df-4d5d-9f85-5a9a74d2f8c8)

**Comment by web-ning** [comment]
![image](https://github.com/user-attachments/assets/8f7387c1-84dc-497f-a538-76d29be53d33)
上方空间不够时，为什么可以呢；底层代码肯定有判断错误的。。。

**Comment by btea** [comment]
因为代码判断其他方向空间都不够，所以只能回到下面，这种情况下弹窗的位置既不是正常的`bottom`，也不是正常的`bottom-start`。
https://github.com/element-plus/element-plus/blob/bbd652e9f8f89361a131809fba75734367f92746/packages/components/time-picker/src/common/picker.vue#L14

**Comment by web-ning** [comment]
![image](https://github.com/user-attachments/assets/c19a5bc9-47aa-4c63-84eb-c5b8036797f8)
下方空间绝对是够的，只能说代码判断空间大小有问题，而且我强制设置了只在下方显示也不行:popper-options="{ placement: 'bottom'}"；如果官方不想处理，那就算了

**Comment by btea** [comment]
> 设置`bottom`时，会在下方x轴方向居中，上面的示例要在x轴方向居中，左侧空间不够。
> 
> ![image](https://private-user-images.githubusercontent.com/24516654/369223776-8c1b5649-c6df-4d5d-9f85-5a9a74d2f8c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTcxNzksIm5iZiI6MTcyNjc5Njg3OSwicGF0aCI6Ii8yNDUxNjY1NC8zNjkyMjM3NzYtOGMxYjU2NDktYzZkZi00ZDVkLTlmODUtNWE5YTc0ZDJmOGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjkzMjM2YjA2N2YyZmI4YzdkODZmYTExY2Y2ODIwMjM5NTIyNDkxZjgxMGQxYmU3MmNjNTM1NDZjNzI4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5XJNbw2v6Xd_On2tzegSg3uPQwnFpvarE5_e1Cxbfuk)

设置了`placement: 'bottom'`, 正常效果是这样的，弹窗面板会以`input`为中心，但在上面的例子中，左侧的空间不够，所以会自动计算适配上方，右方，下方，左方，哪里有足够的空间，面板就会显示在哪里。
