### ISSUE TITLE
[Style] [All] 适配sass1.79.0的弃用更改

### ISSUE THREAD

**Issue by lvzhenbo** [element-plus/element-plus#18306]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.6`
- Element Plus Version: `2.8.3`
- Browser / OS: `Chrome/128.0.0.0 Windows 11`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

将sass版本升级到1.79.1

### What is Expected?

没有弃用警告

### What is actually happening?

有弃用警告

### Additional comments

https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

**Comment by lvzhenbo** [comment]
> 弃用警告应该是你项目，安装的sass版本提示的 参考[这个](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/) ![image](https://private-user-images.githubusercontent.com/68949154/369300714-5b3c6d26-8612-4478-9ac4-49043f0dfff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQwMjAsIm5iZiI6MTcyNjgyMzcyMCwicGF0aCI6Ii82ODk0OTE1NC8zNjkzMDA3MTQtNWIzYzZkMjYtODYxMi00NDc4LTlhYzQtNDkwNDNmMGRmZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmNiMWU3NzQ1ZTA0MDhmY2Q0NWRhYTI4NjMwNzA1MTAzOTczN2ZhOTcxNmRiYTRkYTViZDMzYjU3OGIxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8HOWAvqld90HEXjETHWewzCGj3dtKrgjuAbzAtJlVHw)

这个也是一个，而且还要更新vite版本，不过我说的是pr的，颜色方法的弃用

**Comment by SkywalkerJi** [comment]
package.json
```
  "dependencies": {
    "element-plus": "^2.8.3",
  },
  "devDependencies": {
    "sass-embedded": "^1.79.3",
    "vite": "^5.4.7",
  },
```

vite.config.js

```
preprocessorOptions: {
  sass: {
    api: 'modern-compiler',
  },
},
```

still have Deprecation Warning

```
Deprecation Warning: red() is deprecated. Suggestion:

color.channel($color, "red", $space: rgb)

More info: https://sass-lang.com/d/color-functions

   ╷
52 │     #{red($color),
   │       ^^^^^^^^^^^
   ╵
    ../../../element-plus/theme-chalk/src/mixins/_var.scss 52:7  set-css-color-rgb()
    ../../../element-plus/theme-chalk/src/var.scss 17:5          @use
    ../../../element-plus/theme-chalk/src/base.scss 4:11         root stylesheet

Deprecation Warning: green() is deprecated. Suggestion:

color.channel($color, "green", $space: rgb)

More info: https://sass-lang.com/d/color-functions

   ╷
53 │     green($color),
   │     ^^^^^^^^^^^^^
   ╵
    ../../../element-plus/theme-chalk/src/mixins/_var.scss 53:5  set-css-color-rgb()
    ../../../element-plus/theme-chalk/src/var.scss 17:5          @use
    ../../../element-plus/theme-chalk/src/base.scss 4:11         root stylesheet

Deprecation Warning: blue() is deprecated. Suggestion:

color.channel($color, "blue", $space: rgb)

More info: https://sass-lang.com/d/color-functions

   ╷
54 │     blue($color)}
   │     ^^^^^^^^^^^^
   ╵
    ../../../element-plus/theme-chalk/src/mixins/_var.scss 54:5  set-css-color-rgb()
    ../../../element-plus/theme-chalk/src/var.scss 17:5          @use
    ../../../element-plus/theme-chalk/src/base.scss 4:11         root stylesheet
```

**Comment by lvzhenbo** [comment]
@SkywalkerJi Yes, these are two different types of warnings, one for api deprecation and one for method deprecation, api deprecation is solved by vite, but method deprecation has to modify the element-plus code, there's already a pull request on the top that you can see, but the initiator didn't refine the code, so it hasn't been merged yet

**Comment by SkywalkerJi** [comment]
> @SkywalkerJi Yes, these are two different types of warnings, one for api deprecation and one for method deprecation, api deprecation is solved by vite, but method deprecation has to modify the element-plus code, there's already a pull request on the top that you can see, but the initiator didn't refine the code, so it hasn't been merged yet@SkywalkerJi是的，这是两种不同类型的警告，一种是api弃用，一种是方法弃用，api弃用是通过vite解决的，但是方法弃用必须修改element-plus代码，顶部已经有一个pull request 可以看到，但是发起者没有完善代码，所以还没有合并

Hope it can be merged.

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/18376 has been fixed, you can click here to install the latest version

![image](https://github.com/user-attachments/assets/b096cb78-6fe9-4bfc-a5df-5361e245a8a5)

**Comment by Nejoe** [comment]
> #18376 has been fixed, you can click here to install the latest version
> 
> ![image](https://private-user-images.githubusercontent.com/45450994/371998821-b096cb78-6fe9-4bfc-a5df-5361e245a8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzcyNDMsIm5iZiI6MTcyOTEzNjk0MywicGF0aCI6Ii80NTQ1MDk5NC8zNzE5OTg4MjEtYjA5NmNiNzgtNmZlOS00YmZjLWE1ZGYtNTM2MWUyNDVhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAzNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTU3MWY3MTgxYjRiNTg4NDJmNWIzYTM0NWVmNGU5OWQwMzliY2Q0Y2I0NmE0YjQwOTVmZmQ1MzUwYjMzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rm_5g2rEoqt3PqoJ_duPvAYPpeKdnCk3dZmsILR9ieA)

导入暗黑模式的样式后也会报错。
import "element-plus/theme-chalk/dark/css-var.css"

**Comment by lvzhenbo** [comment]
@Nejoe 兄嘚，是css-vars.css

**Comment by Nejoe** [comment]
> @Nejoe 兄嘚，是css-vars.css

手机回复的，打错了。反正就是官方文档里引入暗黑模式里的那条css

**Comment by lvzhenbo** [comment]
@Nejoe 试了试没有什么问题，自己开issue提供demo
