### ISSUE TITLE
After modifying the [bug report] code, the error report will be loaded automatically

### ISSUE THREAD

**Issue by kyle-go** [element-plus/element-plus#1831]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
Windows10 / Chrome 89.0.4389.114

### Vue version
3.0.11

### Reproduction Link
https://gist.github.com/RyoHina/59fc9362d4affa613d2696744a5a9fd7

### Steps to reproduce
```
<template>
  <!--  将el-main换成div则不会报错了，大概率是element-plus的锅 -->
  <el-main>
    <div>
      <!-- 去掉 @click 也不报错了，好奇怪啊-->
      <i class="el-icon-close" style="float: right;" @click="func"></i>
      <span>{{ title + "运行起来后，随便改本字符串一个字母，WebStorm自动加载, 会报错123" }}</span>
    </div>
  </el-main>
</template>

<script>
export default {
  mounted() {
    this.title = "Title"
  },
  data() {
    return {
      title: "",
    }
  },
  methods: {
    func() {
      alert("closed!!!")
    }
  }
}
</script>
```
Webstorm运行此vue后， 修改line 7字符串，浏览器会重新加载，然后报错。

### What is Expected?
重新加载浏览器不报错

### What is actually happening?
重新加载浏览器报错

**Comment by JeremyWuuuuu** [comment]
I think the bug was caused because we made changes on generating WebStorm IDE support, we will release a patch very soon to fix it, after you upgrade the version, you will no longer have this issue.

**Comment by JeremyWuuuuu** [comment]
Can you upgrade to `beta.40` and see if you get any error?

**Comment by RyoHina** [comment]
> Can you upgrade to `beta.40` and see if you get any error?

Upgrade element-plus to 1.0.2-beta.40, clean all the cache(remove node_modules  and yarn.lock), yarn install again,  BUT THE ERROR STILL EXIST.

**Comment by JeremyWuuuuu** [comment]
Seems like we have already included the files into `lib`, could you manually set the direction of you IDE(WebStorm) here point to `element-plus/lib`?

**Comment by JeremyWuuuuu** [comment]
I don't know how `WebStorm` works but I guess there was a way to manually set the IDE path. Since I personally do not own any `WebStorm` license, it could be hard for me to help you out. I'll go do some dig online see what I can help.

**Comment by RyoHina** [comment]
> I don't know how `WebStorm` works but I guess there was a way to manually set the IDE path. Since I personally do not own any `WebStorm` license, it could be hard for me to help you out. I'll go do some dig online see what I can help.

you can use webstorm with  1 mounth free.   Here is my debug information

```
>>>> the error stack
runtime-core.esm-bundler.js?5c40:540 TypeError: Cannot read property 'style' of null
    at patchStyle (runtime-dom.esm-bundler.js?830f:104)
    at patchProp (runtime-dom.esm-bundler.js?830f:363)
    at patchProps (runtime-core.esm-bundler.js?5c40:4104)
    at patchElement (runtime-core.esm-bundler.js?5c40:4051)
    at processElement (runtime-core.esm-bundler.js?5c40:3871)
    at patch (runtime-core.esm-bundler.js?5c40:3788)
    at patchKeyedChildren (runtime-core.esm-bundler.js?5c40:4506)
    at patchChildren (runtime-core.esm-bundler.js?5c40:4449)
    at patchElement (runtime-core.esm-bundler.js?5c40:4062)
    at processElement (runtime-core.esm-bundler.js?5c40:3871)


webpack:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js?830f
>>>>>> line 104,  

function patchStyle(el, prev, next) {
    const style = el.style; >>>>>>> the param el is null
    if (!next) {
        el.removeAttribute('style');
    }
    else if (isString(next)) {
        if (prev !== next) {
            const current = style.display;
            style.cssText = next;
            // indicates that the `display` of the element is controlled by `v-show`,
            // so we always keep the current `display` value regardless of the `style` value,
            // thus handing over control to `v-show`.
            if ('_vod' in el) {
                style.display = current;
            }
        }
    }
    else {
        for (const key in next) {
            setStyle(style, key, next[key]);
        }
        if (prev && !isString(prev)) {
            for (const key in prev) {
                if (next[key] == null) {
                    setStyle(style, key, '');
                }
            }
        }
    }
}
```

**Comment by JeremyWuuuuu** [comment]
I need to ask, where did this error came from, in the terminal(which runs your `yarn serve` command) or in the WebStorm console(which collects all your IDE informations), if it was the previous one, could you reproduce it by running the `yarn serve` command in your outside terminal?
I need to know this is critical for me to debug the error

**Comment by JeremyWuuuuu** [comment]
We have several guys in our team use `WebStorm`, I'll go ask them for some help. cc @Ryan2128 @kooriookami

**Comment by RyoHina** [comment]
> I need to ask, where did this error came from, in the terminal(which runs your `yarn serve` command) or in the WebStorm console(which collects all your IDE informations), if it was the previous one, could you reproduce it by running the `yarn serve` command in your outside terminal?
> I need to know this is critical for me to debug the error

Thank you for your patience.

The error is nothing about Webstorm. Here is the way to show the error.

1. open cmd or terminal,  go to the  project root,  run 'yarn serve'
2. open  chrome  and  put "http://localhost:8080/",  and open Console Debug Tab.
3. open  App.vue by notepad.exe, and modify  line 7  with one  char  modified,  and  "Ctrl + S" Save the file.
Now  the  cmd will reload  the vue project,  and  Browser Console  will get the error.

**Comment by JeremyWuuuuu** [comment]
Well, from my experiences, it could be platform related issue since Windows uses different line carry sign '\r\n' which in POSIX  OSs is '\n', could be something like that, you also said you were using `notepad` this could be notepad automatically changing your file's metadata, can you reproduce this issue on `VSCode`?

**Comment by RyoHina** [comment]
> Well, from my experiences, it could be platform related issue since Windows uses different line carry sign '\r\n' which in POSIX OSs is '\n', could be something like that, you also said you were using `notepad` this could be notepad automatically changing your file's metadata, can you reproduce this issue on `VSCode`?

YES, change notepad.exe to VSCODE,  the error still exist.

**Comment by JeremyWuuuuu** [comment]
Maybe you can upload a minimal repo for us to investigate? I copied the code you provided in the gist on my Mac, which worked fine.

**Comment by RyoHina** [comment]
> Maybe you can upload a minimal repo for us to investigate? I copied the code you provided in the gist on my Mac, which worked fine.

Thank you for your patience again.
My OS is Windows 10 Professional Edition  20H2, here is the repo.
[bug.zip](https://github.com/element-plus/element-plus/files/6315047/bug.zip)

**Comment by JeremyWuuuuu** [comment]
> > Maybe you can upload a minimal repo for us to investigate? I copied the code you provided in the gist on my Mac, which worked fine.
> 
> Thank you for your patience again.
> My OS is Windows 10 Professional Edition 20H2, here is the repo.
> [bug.zip](https://github.com/element-plus/element-plus/files/6315047/bug.zip)

Nice, I can reproduce this on my own machine now.

**Comment by JeremyWuuuuu** [comment]
Weird, I will let you know when I found the solution.
So I have just copy paste  the code in `ElMain.vue`  then created locally with the same code, then the error disappeared, I dunno why is this happening for now, but it could be related to the hot-reload feature. (I also used your code locally and didn't  get the error)

**Comment by RyoHina** [comment]
> Weird, I will let you know when I found the solution.
> So I have just copy paste the code in `ElMain.vue` then created locally with the same code, then the error disappeared, I dunno why is this happening for now, but it could be related to the hot-reload feature. (I also used your code locally and didn't get the error)

YES,  there must be something wrong with  hot-reload.  I don't know which one  cause the error,  VUE3 or  Element-plus?

**Comment by JeremyWuuuuu** [comment]
The root cause is quite complicated, I will start investigating the root cause of this issue and let you know the moment that I get any conclusion.
