### ISSUE TITLE
[Bug Report] Runtime and packaging errors in the vite2 environment

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1833]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
win10

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7aa

### Steps to reproduce
When running or packaging in a vite environment, there will be the following errors
![image](https://user-images.githubusercontent.com/20943608/114640141-0d166900-9d02-11eb-9ed7-7a39f78a651d.png)

![image](https://user-images.githubusercontent.com/20943608/114640271-52d33180-9d02-11eb-8c94-a63f7f30bf78.png)

![Uploading image.png…]()

### What is Expected?
fix

### What is actually happening?
TS2304: Cannot find name 'ComponentSize'.
TS2304: Cannot find name 'Nullable'.

**Comment by JeremyWuuuuu** [comment]
Sorry for causing this issue, we will fix it in the coming versions.

**Comment by jahnli** [comment]
thank， I look forward to a quick fix ， This caused the project to fail to run

**Comment by JeremyWuuuuu** [comment]
Turn off your typescript checker this shall work perfectly.

**Comment by JeremyWuuuuu** [comment]
I mean only on compile mode (do not do type check on 3rd party libraries)

**Comment by jahnli** [comment]
OK  thanks

**Comment by jahnli** [comment]
Can you provide a demo?

**Comment by JeremyWuuuuu** [comment]
> Can you provide a demo?

Could you wait a minute? I am currently on something else, I can only provide your the demo after I'm done with current task. Sorry for kept you waiting. 🙇

**Comment by jahnli** [comment]
OK, thank you very much. I'll wait for you to finish

**Comment by JeremyWuuuuu** [comment]
Can you provide a repo for me to work with? As simple as possible.

**Comment by JeremyWuuuuu** [comment]
Seems like you've got the same issue with #1780, see the comment for a quick fix: https://github.com/element-plus/element-plus/issues/1780#issuecomment-818639111

**Comment by jahnli** [comment]
https://github.com/jahnli/test

This will do? Or do  need jsfiddle ?

**Comment by jahnli** [comment]
OK，I've seen it, thank you

**Comment by JeremyWuuuuu** [comment]
Seemed like you remove the `tsc --noEmit` part the project will be bundled  perfectly. For temporary fix I think it is ok to remove that part, and we will fix that in the coming versions.

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/114676723-2936fc00-9d3c-11eb-8e32-a560134576d3.png)
Everything looks when I run
```shell
$ vite build
```
command standalone.

**Comment by jahnli** [comment]
yes，is OK 
![image](https://user-images.githubusercontent.com/20943608/114677113-9185dd80-9d3c-11eb-8f6f-96b4fedcc3ee.png)

**Comment by JeremyWuuuuu** [comment]
Great, then I am going to close this issue then, I will create a task for tracking this issue, so we will fix this type related issue int the coming versions. Sorry for the inconvenience.

**Comment by jahnli** [comment]
thank you very much for your help

**Comment by ulevitsky** [comment]
Removing `tsc --noEmit` is a type safety hazard; a better workaround would be to add `"skipLibCheck": true` to tsconfig.json.
