### ISSUE TITLE
When the [bug report] select component clicks the drop-down item, it is not selected

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1834]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
Microsoft Edge 版本 89.0.774.48 (官方内部版本) (64 位)

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/sorrowx/pen/JjEvovz?editors=1112

### Steps to reproduce
1. 打开 https://codepen.io/sorrowx/pen/JjEvovz?editors=1112
2. 打开控制台
3. 点击下拉面板中的item的选项

### What is Expected?
1. 选中item

### What is actually happening?
1.ui没有更新
2. 但是v-model绑定的值确实是正确的

### 原因?
1. vue-next的bug
2. 响应式值发生变化后并没有trigger更新（链接中注释的代码使用姿势是可以的）
3. 组件安装时会处理setup函数的返回值，看下图的调用栈,这样对返回值做了代理，当点击下拉item时，把options vm的value赋值给v-model="绑定值变量"的绑定值变量时，会走shallowUnwrapHandler对象的set,但是走的是else分支，所以不会触发更新，导致 useOptions.ts(element-plus/packages/select/src/useOption.ts)中的计算属性itemSelected没有更新,所以ui没变化，但是绑定值变量更新了。
```js
const shallowUnwrapHandlers = {
    get: (target, key, receiver) => unref(Reflect.get(target, key, receiver)),
    set: (target, key, value, receiver) => {
        const oldValue = target[key];
        if (isRef(oldValue) && !isRef(value)) {
            oldValue.value = value;
            return true;
        }
        else {
            return Reflect.set(target, key, value, receiver);
        }
    }
};

// 上面尤大的代码加一行后不知道靠不靠谱（这里只是想法）
const shallowUnwrapHandlers = {
    get: (target, key, receiver) => unref(Reflect.get(target, key, receiver)),
    set: (target, key, value, receiver) => {
        const oldValue = target[key];
        if (isRef(oldValue) && !isRef(value)) {
            oldValue.value = value;
            return true;
        } else if (isReactive(target[key])) { // 新加一个分支
           target[key] = value
        } else {
            return Reflect.set(target, key, value, receiver);
        }
    }
};
```
![image](https://user-images.githubusercontent.com/20411966/114642762-0d653300-9d07-11eb-951f-eebed7fff40f.png)

4. 这里是由vue-next修复还是element-plus修复这个问题？
5. element-plus select组件修复的话，我的想法是在点击时执行 handleOptionSelect的后面加上挨个遍历option vm组件，强制更新，这样会导致除了这种使用姿势外，每次点击item, 所有option 组件会更新2次😂

**Comment by JeremyWuuuuu** [comment]
We can do $forceUpdate.

**Comment by JeremyWuuuuu** [comment]
Check this out: https://v3.vuejs.org/api/instance-methods.html#forceupdate, we can manually dispatch force updating UI via the given API. Do you want to implement it with this API?

**Comment by xlz26296** [comment]
看你分析得这么用心，又是 vue-next修复还是element-plus修复
忍不住告诉你一声，是你自己用错了，你应该先弄懂 ref 和 reactive 的用法
```javascript
const aa = ref(5)
const bb= reactive({
  val: 5
 })
```
```html
<el-select v-model="aa"></el-select>
<el-select v-model="bb.val"></el-select>
```

**Comment by SorrowX** [comment]
> We can do $forceUpdate.

但是除了我上面的使用姿势外，其他的使用姿势会造成2次更新😂

**Comment by JeremyWuuuuu** [comment]
> 看你分析得这么用心，又是 vue-next修复又是element-plus修复
> 忍不住告诉你一声，是你自己用错了，你应该先弄懂 ref 和 reactive 的用法😂
> 
> ```js
> const aa = ref(5)
> const bb= reactive({
>   val: 5
>  })
> ```
> 
> ```
> <el-select v-model="aa"></el-select>
> <el-select v-model="bb.val"></el-select>
> ```

@SorrowX Seems like he was right, I didn't click the demo you made, after seeing this I went to your demo found out that you are wrong about how to use `reactive`, so the thing is that if you use `reactive`, you don't get automatically unwrapped inner value via `Vue`, you need to ues `value.value` to get the value.

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/114645424-0d1b6680-9d0c-11eb-93d6-2c7add9a89aa.png)

You either do

```ts
const value = ref(5)
```
then use it in the template like
```vue
<tag v-model="value" />
```

or 

```ts
const value = reactive({value: 5})
```
then use it in the template like

```vue
<tag v-model="value.value" />
```

**Comment by JeremyWuuuuu** [comment]
Closing since this is not bug from us.

**Comment by SorrowX** [comment]
@JeremyWuuuuu 我明白的你们说的，你们这么写确实是对的。那个demo的其他使用姿势也是对的。
```js
return {
          ...toRefs(reactive({ options: opt, value: { value: 5 } })), // 单独这么写也行
          // 下面这么写也行
          options: ref(opt),
          value: ref({ value: 5 }),
        }
```
上面这么写都能正确走到shallowUnwrapHandler中的set。
你们那么写也行，但是我觉得那个链接写的demo从使用姿势上看也并没有什么不妥？
那先不管吧😂

**Comment by SorrowX** [comment]
@JeremyWuuuuu @xlz26296 
2位大哥，我们抛开这个问题不说哈，我有个问题想请教下，希望有空解答下。
1.setup函数中可以返回一个对象，该对象会作为响应式时在模板和计算属性和watch时使用。
   setup函数也可以返回一个函数，该函数会作为render函数，其优先级大于我们自己手写的render函数，大于模板。
2.当响应式的值发生变化后，如果用在模板中，模板应该会更新，用在计算属性中，等下次求值计算属性时也能得到最新值，watch中，监测到响应式值发生变化后，会触发回调。
3.上面2点是我理解的，应该没错是吧
4. 打开这个新的地址 https://codepen.io/sorrowx/pen/WNRJvya?editors=1111  我们测试下
5. 发现setup抛出的响应式值(创建响应式数据常用的可以使用ref,reactive，这里使用reactive)发生变化后并没有更新模板，原因其实我在最上面已经说过了，我不知道vue-next的设计如此还是该使用姿势就是不对的。
6. 我知道其他使用姿势是对的，我就想知道这种使用姿势对于我们普通开发者来说是对还是不对？😂
7. 希望有空解答下

**Comment by SorrowX** [comment]
> 
> ```ts
> const value = reactive({value: 5})
> ```
> 
> then use it in the template like
> 
> ```
> <tag v-model="value.value" />
> ```

JeremyWuuuuu  大哥，你这种使用姿势不对
![image](https://user-images.githubusercontent.com/20411966/114651967-8b313a80-9d17-11eb-81d3-ccd5adb639a3.png)

options的value是对象，v-model绑定的也是对象，我当时偷懒省略了value-key属性，他的默认值就是value,所以刚好和vue 中的ref的响应式数据，用在模板中自动unwrapped的混淆了。所以你才告诉我上面2种姿势
![image](https://user-images.githubusercontent.com/20411966/114652085-c6336e00-9d17-11eb-8c60-26fa866daf8a.png)
你没仔细看我的demo😂，抛开这个话题，您有空能解答下下面的那个问题吗，下面的问题解答了，这个问题自然就明白了？
不弄明白很是难受😢
@JeremyWuuuuu
