### ISSUE TITLE
[Component] [slider] el-slider设置showTooltip为false时依然生成poper元素

### ISSUE THREAD

**Issue by timmykawhi** [element-plus/element-plus#18346]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.7.8`
- Browser / OS: `Chrome/127.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlYWN0aXZlLGNvbXB1dGVkIH0gZnJvbSAndnVlJztcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG50eXBlIE1hcmtzID0gUmVjb3JkPG51bWJlciwgc3RyaW5nPlxuICBjb25zdCBtaW4gPSAwO1xuICBjb25zdCBtYXggPSA2MDtcbmNvbnN0IG1hcmtzID0gY29tcHV0ZWQoKCkgPT4gZ2V0TWFya3MobWluLCBtaW4pKVxuZnVuY3Rpb24gZ2V0TWFya3MobWluOiBudW1iZXIsIG1heDogbnVtYmVyKTogTWFya3Mge1xuICBjb25zdCByYW5nZSA9IG1heCAtIG1pblxuICBjb25zdCBpbnRlcnZhbCA9IHJhbmdlID4gMjAgPyA1IDogMi41XG4gIGNvbnN0IGJpZ01hcmsgPSByYW5nZSA+IDIwID8gMTAgOiA1XG4gIGNvbnN0IG1hcmtzOiBNYXJrcyA9IHt9XG4gIGZvciAobGV0IG1hcmsgPSBtYXg7IG1hcmsgPj0gbWluOyBtYXJrIC09IGludGVydmFsKSB7XG4gICAgY29uc3QgYWJzTWFyayA9IE1hdGguYWJzKG1hcmspXG4gICAgaWYgKG1hcmsgJSBiaWdNYXJrID09PSAwIHx8IChhYnNNYXJrID09PSBpbnRlcnZhbCAmJiBtaW4gPCAwKSkge1xuICAgICAgbWFya3NbbWFya10gPSBgJHthYnNNYXJrfWBcbiAgICB9IGVsc2Uge1xuICAgICAgbWFya3NbbWFya10gPSAnJ1xuICAgIH1cbiAgfVxuICByZXR1cm4gbWFya3Ncbn1cblxuY29uc3QgZ2V0T3B0aW9uTGlzdD0gKCk9PntcbiAgY29uc3QgbGlzdCA9IFtdXG4gIGZvcihsZXQgaT0wO2k8NDA7aSsrKXtcbiAgICBsaXN0LnB1c2goe1xuICAgICAgaWQ6aSxcbiAgICAgIG1pbjowLFxuICAgICAgbWF4OjYwLFxuICAgICAgdmFsdWU6MTBcbiAgICB9KVxuICB9XG4gIHJldHVybiBsaXN0XG59XG5jb25zdCBvcHRpb25MaXN0ID0gcmVhY3RpdmUoZ2V0T3B0aW9uTGlzdCgpKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiB2LWZvcj1cIm9wdGlvbiBpbiBvcHRpb25MaXN0XCIgOmtleT1cIm9wdGlvbi5pZFwiPlxuICA8ZWwtc2xpZGVyIFxuICAgIHZlcnRpY2FsXG4gICAgaGVpZ2h0PVwiMTAwcHhcIlxuICAgIHYtbW9kZWw9XCJvcHRpb24udmFsdWVcIiBcbiAgICAgICA6c2hvdy10b29sdGlwPVwiZmFsc2VcIiBcbiAgICAgICA6bWluPVwibWluXCIgXG4gICAgICAgOm1heD1cIm1heFwiIFxuICAgICAgIDptYXJrcz1cIm1hcmtzXCJcbiAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy40LjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjQuMjkvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy44L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.页面用v-for生成20个以上el-slider组件，el-slider设置showTooltip为false
2.查看页面元素\<div id="el-popper-container-xx"\>,发现生成很多poper子元素

### What is Expected?

showTooltip设为false不生成poper或只生成一个poper

### What is actually happening?

poper元素过多，增加页面渲染时间

### Additional comments

_(empty)_

**Comment by timmykawhi** [comment]
![image](https://github.com/user-attachments/assets/7568bee3-e69f-44c8-8ebb-dbe43a2ee050)

**Comment by timmykawhi** [comment]
![image](https://github.com/user-attachments/assets/4d233ac6-6c9b-4597-8fb5-606f954d08cb)

**Comment by timmykawhi** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJztcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBnZXRPcHRpb25MaXN0PSAoKT0+e1xuICBjb25zdCBsaXN0ID0gW11cbiAgZm9yKGxldCBpPTA7aTwzMDtpKyspe1xuICAgIGxpc3QucHVzaCh7XG4gICAgICBpZDppLFxuICAgICAgbWluOjAsXG4gICAgICBtYXg6NjAsXG4gICAgICB2YWx1ZToxMFxuICAgIH0pXG4gIH1cbiAgcmV0dXJuIGxpc3Rcbn1cbmNvbnN0IG9wdGlvbkxpc3QgPSByZWFjdGl2ZShnZXRPcHRpb25MaXN0KCkpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHYtZm9yPVwib3B0aW9uIGluIG9wdGlvbkxpc3RcIiA6a2V5PVwib3B0aW9uLmlkXCI+XG4gIDxlbC1zbGlkZXIgdG9vbHRpcC1jbGFzcz1cIm15LXNsaWRlclwiIHYtbW9kZWw9XCJvcHRpb24udmFsdWVcIiA6c2hvdy10b29sdGlwPVwiZmFsc2VcIiA6bWluPVwib3B0aW9uLm1pblwiIDptYXg9XCJvcHRpb24ubWF4XCIgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy40LjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjQuMjkvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy44L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjgvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by xingyixiang** [comment]
packages\components\slider\src\button.vue   line:22
是不是可以删除persistent属性

**Comment by timmykawhi** [comment]
> #5250

这个bug还修吗？怎么一年多了还没有改

**Comment by xingyixiang** [comment]
packages\components\slider\src\button.vue  line22的persistent可以删除吗   @kooriookami

**Comment by timmykawhi** [comment]
> packages\components\slider\src\button.vue line22的persistent可以删除吗 @kooriookami

这个真是不打算fix了吗，怎么这么久没回复的？对于一些大量使用slider的项目来说，这个算很严重的bug了，预生成了这么多重复的popper，严重拖慢渲染速度. 而且我发现好像select、menu等一些用到popper的组件也有类似的问题
