### ISSUE TITLE
[Component] [form] 在el-form里面使用el-select的时候，点击表单的文字会触发下拉框的展示

### ISSUE THREAD

**Issue by onlySparrow** [element-plus/element-plus#18353]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.8`
- Element Plus Version: `2.8.3`
- Browser / OS: `所有系统`
- Build Tool: `Vue CLI`

### Related Component

- `el-form`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html)

### Steps to reproduce

进入官网地址找到form表单组建，触发下拉框的标题就能看到效果

### What is Expected?

点击表单名称的时候不触发select下拉框的展开

### What is actually happening?

点击表单名称的时候触发select下拉框的展开

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
@onlySparrow 

This issue has been fixed. Or you can temporarily set css

```scss
.el-form-item__label {
    display: inline-block;
    vertical-align: middle;
}
```

https://github.com/element-plus/element-plus/pull/18293

**Comment by warmthsea** [comment]
Or you can use: 

```scss
.el-form-item__label {
    pointer-events: none;
}
```

[Playground Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCIgbGFiZWwtd2lkdGg9XCJhdXRvXCIgc3R5bGU9XCJtYXgtd2lkdGg6IDYwMHB4XCI+XG4gICAgPGVsLWZvcm0taXRlbSA6Zm9yPVwidW5kZWZpbmVkXCIgbGFiZWw9XCJBY3Rpdml0eSBuYW1lXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IHpvbmVcIj5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJwbGVhc2Ugc2VsZWN0IHlvdXIgem9uZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB0aW1lXCI+XG4gICAgICA8ZWwtY29sIDpzcGFuPVwiMTFcIj5cbiAgICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgICAgdi1tb2RlbD1cImZvcm0uZGF0ZTFcIlxuICAgICAgICAgIHR5cGU9XCJkYXRlXCJcbiAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXRlXCJcbiAgICAgICAgICBzdHlsZT1cIndpZHRoOiAxMDAlXCJcbiAgICAgICAgLz5cbiAgICAgIDwvZWwtY29sPlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjJcIiBjbGFzcz1cInRleHQtY2VudGVyXCI+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwidGV4dC1ncmF5LTUwMFwiPi08L3NwYW4+XG4gICAgICA8L2VsLWNvbD5cbiAgICAgIDxlbC1jb2wgOnNwYW49XCIxMVwiPlxuICAgICAgICA8ZWwtdGltZS1waWNrZXJcbiAgICAgICAgICB2LW1vZGVsPVwiZm9ybS5kYXRlMlwiXG4gICAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgdGltZVwiXG4gICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgICAgIC8+XG4gICAgICA8L2VsLWNvbD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiSW5zdGFudCBkZWxpdmVyeVwiPlxuICAgICAgPGVsLXN3aXRjaCB2LW1vZGVsPVwiZm9ybS5kZWxpdmVyeVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IHR5cGVcIj5cbiAgICAgIDxlbC1jaGVja2JveC1ncm91cCB2LW1vZGVsPVwiZm9ybS50eXBlXCI+XG4gICAgICAgIDxlbC1jaGVja2JveCB2YWx1ZT1cIk9ubGluZSBhY3Rpdml0aWVzXCIgbmFtZT1cInR5cGVcIj5cbiAgICAgICAgICBPbmxpbmUgYWN0aXZpdGllc1xuICAgICAgICA8L2VsLWNoZWNrYm94PlxuICAgICAgICA8ZWwtY2hlY2tib3ggdmFsdWU9XCJQcm9tb3Rpb24gYWN0aXZpdGllc1wiIG5hbWU9XCJ0eXBlXCI+XG4gICAgICAgICAgUHJvbW90aW9uIGFjdGl2aXRpZXNcbiAgICAgICAgPC9lbC1jaGVja2JveD5cbiAgICAgICAgPGVsLWNoZWNrYm94IHZhbHVlPVwiT2ZmbGluZSBhY3Rpdml0aWVzXCIgbmFtZT1cInR5cGVcIj5cbiAgICAgICAgICBPZmZsaW5lIGFjdGl2aXRpZXNcbiAgICAgICAgPC9lbC1jaGVja2JveD5cbiAgICAgICAgPGVsLWNoZWNrYm94IHZhbHVlPVwiU2ltcGxlIGJyYW5kIGV4cG9zdXJlXCIgbmFtZT1cInR5cGVcIj5cbiAgICAgICAgICBTaW1wbGUgYnJhbmQgZXhwb3N1cmVcbiAgICAgICAgPC9lbC1jaGVja2JveD5cbiAgICAgIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIlJlc291cmNlc1wiPlxuICAgICAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJmb3JtLnJlc291cmNlXCI+XG4gICAgICAgIDxlbC1yYWRpbyB2YWx1ZT1cIlNwb25zb3JcIj5TcG9uc29yPC9lbC1yYWRpbz5cbiAgICAgICAgPGVsLXJhZGlvIHZhbHVlPVwiVmVudWVcIj5WZW51ZTwvZWwtcmFkaW8+XG4gICAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSBmb3JtXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0uZGVzY1wiIHR5cGU9XCJ0ZXh0YXJlYVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJvblN1Ym1pdFwiPkNyZWF0ZTwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG4vLyBkbyBub3QgdXNlIHNhbWUgbmFtZSB3aXRoIHJlZlxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJycsXG4gIHJlZ2lvbjogJycsXG4gIGRhdGUxOiAnJyxcbiAgZGF0ZTI6ICcnLFxuICBkZWxpdmVyeTogZmFsc2UsXG4gIHR5cGU6IFtdLFxuICByZXNvdXJjZTogJycsXG4gIGRlc2M6ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZWwtZm9ybS1pdGVtX19sYWJlbCB7XG4gICAgcG9pbnRlci1ldmVudHM6IG5vbmU7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)
