### ISSUE TITLE
[Docs] [All] 官网案例右侧导航点击不生效

### ISSUE THREAD

**Issue by hao-qingyang** [element-plus/element-plus#18380]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.8`
- Element Plus Version: `2.8.3`
- Browser / OS: `chrome  129.0.6668.58（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](https://issue.element-plus.org/)

### Steps to reproduce

官网组件案例右侧Contents点击不生效

### What is Expected?

点击可以跳转到对应的文档内容

### What is actually happening?

点击无反应

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
Looks normal together.

![screenshots](https://github.com/user-attachments/assets/e369738b-07bc-4903-819c-c7e71ce28726)

**Comment by hao-qingyang** [comment]
> Bug Type: **`Docs`**
> 
> ## Environment
> * Vue Version: `3.5.8`
> * Element Plus Version: `2.8.3`
> * Browser / OS: `chrome  129.0.6668.58（正式版本） （64 位）`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `All`
> 
> ### Reproduction Link
> [Link](https://issue.element-plus.org/)
> 
> ### Steps to reproduce
> 官网组件案例右侧Contents点击不生效
> 
> ### What is Expected?
> 点击可以跳转到对应的文档内容
> 
> ### What is actually happening?
> 点击无反应
> 
> ### Additional comments
> _(empty)_
