### ISSUE TITLE
[Component] [input] Input 输入框密码框使用 show-password 属性切换显示隐藏的密码框,光标会移到第一位

### ISSUE THREAD

**Issue by junyoua** [element-plus/element-plus#18387]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.8.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html)

### Steps to reproduce

Input 输入框密码框使用 show-password 属性切换显示隐藏的密码框,光标会移到第一位

### What is Expected?

光标在最后一位

### What is actually happening?

光标在第一位

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
It seems to be a problem starting from version `2.8.0`

**Comment by tuskermanshu** [comment]
As a result of this PR #17362

**Comment by limoonrise** [comment]
![image](https://github.com/user-attachments/assets/a036c63d-1989-418a-8cda-1a646cf691b0)

切换的时候先blur后聚焦就行了。我看源码上有相关的问题修改，加了个 await nextTick。不晓得为啥现在没有效果。

**Comment by CherishTheYouth** [comment]
const handleFocus = (event: FocusEvent) => {
    const cancelFocus = isFunction(beforeFocus) ? beforeFocus(event) : false
    if (cancelFocus || isFocused.value) return
    isFocused.value = true
    emit('focus', event)
    afterFocus?.()
  }
  
  似乎是因为执行聚焦逻辑时（ref.focus()），会触发handleFocus，这段代码中 isFocused 仍处于聚焦状态，所以 handleFocus 并不会触发聚焦效果。

const focus = async () => {
  // see: https://github.com/ElemeFE/element/issues/18573
// 先blur一下有效
  _ref.value?.blur()
  await nextTick()
  _ref.value?.focus()
}

**Comment by CherishTheYouth** [comment]
> ![image](https://private-user-images.githubusercontent.com/176233457/371456334-a036c63d-1989-418a-8cda-1a646cf691b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTQ2MzEsIm5iZiI6MTczMDk5NDMzMSwicGF0aCI6Ii8xNzYyMzM0NTcvMzcxNDU2MzM0LWEwMzZjNjNkLTE5ODktNDE4YS04Y2RhLTFhNjQ2Y2Y2OTFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNTQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjgwZTFjMzc3N2Q4MDJhZGI4ZTk2YzQ2YzM1NDU2MzlhMzViOTNhMzEwYzdkZDVmOGJiYWEwZDlkN2JlOGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cPINf93kPvXLDQ2pxLlgGYR2l9YWtntdCrmWhDfDCcQ)
> 
> 切换的时候先blur后聚焦就行了。我看源码上有相关的问题修改，加了个 await nextTick。不晓得为啥现在没有效果。

我这里加 blur 后有效果啊，怎么回四？

**Comment by limoonrise** [comment]
> > ![image](https://private-user-images.githubusercontent.com/176233457/371456334-a036c63d-1989-418a-8cda-1a646cf691b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTQ2MzEsIm5iZiI6MTczMDk5NDMzMSwicGF0aCI6Ii8xNzYyMzM0NTcvMzcxNDU2MzM0LWEwMzZjNjNkLTE5ODktNDE4YS04Y2RhLTFhNjQ2Y2Y2OTFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNTQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjgwZTFjMzc3N2Q4MDJhZGI4ZTk2YzQ2YzM1NDU2MzlhMzViOTNhMzEwYzdkZDVmOGJiYWEwZDlkN2JlOGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cPINf93kPvXLDQ2pxLlgGYR2l9YWtntdCrmWhDfDCcQ)
> > 切换的时候先blur后聚焦就行了。我看源码上有相关的问题修改，加了个 await nextTick。不晓得为啥现在没有效果。
> 
> 我这里加 blur 后有效果啊，怎么回四？

加上 blur 是没问题的呀，我的截图是我加上了的，源码上是没有 blur 的
