### ISSUE TITLE
[Component] [table-column] columns > 50 Maximum recursive updates exceeded 

### ISSUE THREAD

**Issue by huan1936** [element-plus/element-plus#18395]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJnZW5lcmF0ZURhdGFcIj7nlJ/miJDmlbDmja48L2VsLWJ1dHRvbj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgICB2LWZvcj1cImNvbHVtbiBpbiBDb2x1bW5zXCJcbiAgICAgICAgICA6a2V5PVwiY29sdW1uLnByb3BcIlxuICAgICAgICAgIDpwcm9wPVwiY29sdW1uLnByb3BcIlxuICAgICAgICAgIDpsYWJlbD1cImNvbHVtbi5sYWJlbFwiXG4gICAgICAgICAgOndpZHRoPVwiY29sdW1uLndpZHRoXCJcbiAgICAgIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGNvbHVtbnNMaXN0ID0gWydpbnQ2NF8wJywgJ2ludDY0XzEnLCAnaW50NjRfMicsICdpbnQ2NF8zJyxcbiAgICAnaW50NjRfNCcsICdpbnQ2NF81JywgJ2ludDY0XzYnLCAnaW50NjRfNycsICdpbnQ2NF84JywgJ2ludDY0XzknLCAnaW50NjRfMTAnLCAnaW50NjRfMTEnLCAnaW50NjRfMTInLFxuICAgICdpbnQ2NF8xMycsXG4gICAgJ2ludDY0XzE0JywgJ2ludDY0XzE1JywgJ2ludDY0XzE2JywgJ2ludDY0XzE3JywgJ2ludDY0XzE4JywgJ2ludDY0XzE5JywgJ2ludDY0XzIwJywgJ2ludDY0XzIxJywgJ2ludDY0XzIyJyxcbiAgICAnaW50NjRfMjMnLCAnaW50NjRfMjQnLCAnaW50NjRfMjUnLCAnaW50NjRfMjYnLCAnaW50NjRfMjcnLCAnaW50NjRfMjgnLCAnaW50NjRfMjknLCAnaW50NjRfMzAnLCAnaW50NjRfMzEnLFxuICAgICdpbnQ2NF8zMicsICdpbnQ2NF8zMycsICdpbnQ2NF8zNCcsICdpbnQ2NF8zNScsICdpbnQ2NF8zNicsICdpbnQ2NF8zNycsICdpbnQ2NF8zOCcsICdpbnQ2NF8zOScsICdpbnQ2NF80MCcsXG4gICAgJ2ludDY0XzQxJywgJ2ludDY0XzQyJywgJ2ludDY0XzQzJywgJ2ludDY0XzQ0JywgJ2ludDY0XzQ1JywgJ2ludDY0XzQ2JywgJ2ludDY0XzQ3JywgJ2ludDY0XzQ4JywgJ2ludDY0XzQ5JyxcbiAgICAnaW50NjRfNTAnLFxuXTtcblxuY29uc3QgQ29sdW1ucyA9IHJlZihjb2x1bW5zTGlzdC5tYXAoKGtleSkgPT4ge1xuICAgIHJldHVybiB7XG4gICAgICAgIHByb3A6IGtleSxcbiAgICAgICAgbGFiZWw6IGtleSxcbiAgICAgICAgd2lkdGg6IDEwMCxcbiAgICB9O1xufSkpO1xuY29uc3QgdGFibGVEYXRhID0gcmVmKFtdKTtcblxuY29uc3QgZ2VuZXJhdGVEYXRhID0gKCkgPT4ge1xuICAgIGNvbnN0IGRhdGEgPSBbXTtcbiAgICBmb3IgKGxldCBpID0gMDsgaSA8IDEwOyBpKyspIHtcbiAgICAgICAgY29uc3QgaXRlbSA9IHt9O1xuICAgICAgICBjb2x1bW5zTGlzdC5mb3JFYWNoKChrZXkpID0+IHtcbiAgICAgICAgICAgIGl0ZW1ba2V5XSA9IE1hdGgucmFuZG9tKCk7XG4gICAgICAgIH0pO1xuICAgICAgICBkYXRhLnB1c2goaXRlbSk7XG4gICAgfVxuICAgIHRhYmxlRGF0YS52YWx1ZSA9IGRhdGE7XG59O1xuXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Running in a local environment
```
<template>
  <div>
    <el-button type="primary" @click="generateData">生成数据</el-button>
    <el-table :data="tableData">
      <el-table-column
          v-for="column in Columns"
          :key="column.prop"
          :prop="column.prop"
          :label="column.label"
          :width="column.width"
      />
    </el-table>
  </div>
</template>

<script lang="ts" setup>
import {ref} from 'vue';

const columnsList = ['int64_0', 'int64_1', 'int64_2', 'int64_3',
    'int64_4', 'int64_5', 'int64_6', 'int64_7', 'int64_8', 'int64_9', 'int64_10', 'int64_11', 'int64_12',
    'int64_13',
    'int64_14', 'int64_15', 'int64_16', 'int64_17', 'int64_18', 'int64_19', 'int64_20', 'int64_21', 'int64_22',
    'int64_23', 'int64_24', 'int64_25', 'int64_26', 'int64_27', 'int64_28', 'int64_29', 'int64_30', 'int64_31',
    'int64_32', 'int64_33', 'int64_34', 'int64_35', 'int64_36', 'int64_37', 'int64_38', 'int64_39', 'int64_40',
    'int64_41', 'int64_42', 'int64_43', 'int64_44', 'int64_45', 'int64_46', 'int64_47', 'int64_48', 'int64_49',
    'int64_50',
];

const Columns = ref(columnsList.map((key) => {
    return {
        prop: key,
        label: key,
        width: 100,
    };
}));
const tableData = ref([]);

const generateData = () => {
    const data = [];
    for (let i = 0; i < 10; i++) {
        const item = {};
        columnsList.forEach((key) => {
            item[key] = Math.random();
        });
        data.push(item);
    }
    tableData.value = data;
};

</script>

```

### What is Expected?

Render all columns normally. No error reported.

### What is actually happening?

Render all columns normally. Exists Error.
```
Maximum recursive updates exceeded in component <ElTableBody>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

### Additional comments

When the number of columns is greater than 50, the Maximum recursive updates exceeded in component message will appear.
Cannot reproduce using Element Plus Playground

![image](https://github.com/user-attachments/assets/53b3ea6d-04f6-4c5b-8b3a-4f339f6231f7)

**Comment by btea** [comment]
似乎是vue的问题，你更新到 vue 3.5.2应该就可以了。上面的链接直接打开是可以的。

**Comment by masterworgen** [comment]
> 似乎是vue的问题，你更新到 vue 3.5.2应该就可以了。上面的链接直接打开是可以的。

Hello, i update vue to last version and element-plus too, but I get infinite recursion on more column, when in table 5-10 column, it work

**Comment by btea** [comment]
I switched to the latest version and it seems to be working fine.

![image](https://github.com/user-attachments/assets/f04d4e2d-8f78-4775-acfc-282106efc554)

**Comment by masterworgen** [comment]
I just tryed hide column in my table with 40+ column, i have next design
```
      <el-table-column
          v-if="columm.hide"
          :prop="column.prop"
          :label="column.label"
          :width="column.width"
      />
```
And i get max recursion

**Comment by masterworgen** [comment]
> I switched to the latest version and it seems to be working fine.
> 
> ![image](https://private-user-images.githubusercontent.com/24516654/374444378-f04d4e2d-8f78-4775-acfc-282106efc554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzU0OTksIm5iZiI6MTcyODM3NTE5OSwicGF0aCI6Ii8yNDUxNjY1NC8zNzQ0NDQzNzgtZjA0ZDRlMmQtOGY3OC00Nzc1LWFjZmMtMjgyMTA2ZWZjNTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxN2Q3M2I5MjA1NDZkMDBlOWJhYWE5YzIyZDg5MzVlOTVkZGYwNDJlZjA4YjEyZWRjZDkyN2FkMDFmN2IxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mhwxLcYwcbeDYMof7fbbo4aMN4TWSdgfAk1Nbs7Pogw)

I just tryed hide column in my table with 40+ column, i have next design
```
      <el-table-column
          v-if="columm.hide"
          :prop="column.prop"
          :label="column.label"
          :width="column.width"
      />
```
And i get max recursion
