### ISSUE TITLE
[Component] [All] Element Plus 组件列表滚动问题

### ISSUE THREAD

**Issue by Chris-G-X** [element-plus/element-plus#18397]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.9`
- Element Plus Version: `2.8.2`
- Browser / OS: `macOS 12.4`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

进入组件列表正常向下滚动 会出现二次滚动 标题错位的情况

### What is Expected?

组件列表页面正常滚动

### What is actually happening?

组件列表页面滚动第一次触底 会出现二次滚动 导致标题错位

### Additional comments

_(empty)_

![1727427571955](https://github.com/user-attachments/assets/1c272ecd-178c-4e85-827f-62da24ddb4b7)

**Comment by Chris-G-X** [comment]
![Uploading 1727427571955.jpg…]()

**Comment by warmthsea** [comment]
It may be caused by your network.

![screenshots](https://github.com/user-attachments/assets/51f6e30d-300e-4797-b7f9-66d3a0f4b3d3)
