### ISSUE TITLE
[Bug Report] `el-space` attribute `spacer` with `el-input` || `el-select`, style might be weird.

### ISSUE THREAD

**Issue by fanhefeng** [element-plus/element-plus#1839]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
window 10 Chrome latest

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/fanhefeng/pen/MWJGjoO

### Steps to reproduce
<el-space spacer="|">
	<el-input v-model="input1"></el-input>
	<el-input v-model="input2"></el-input>
</el-space>

### What is Expected?
style looks like comfortable

### What is actually happening?
width too long.
https://github.com/fanhefeng/element-plus/blob/dev/packages/space/src/index.ts
line:100
createVNode(
	'span',
	// adding width 100% for vertical alignment,
	// when the spacer inherit the width from the
	// parent, this span's width was not set, so space
	// might disappear
	{ style: [itemStyle, 'width: 100%'], key: idx },
	[
	  // if spacer is already a valid vnode, then append it to the current
	  // span element.
	  // otherwise, treat it as string.
	  isVNode(spacer)
		? spacer
		: createTextVNode(spacer as string, PatchFlags.TEXT),
	],
	PatchFlags.STYLE,
),

**Comment by JeremyWuuuuu** [comment]
Yep, I think you made the point, you interested in fixing this?

**Comment by JeremyWuuuuu** [comment]
If you do I will assign this issue to you then.
