### ISSUE TITLE
[Docs] [message] unplugin-element-plus 经测试是可以做到 tree shaking并引入组件 css的，为什么文档说要手动引入css文件？

### ISSUE THREAD

**Issue by Minglu-Huo** [element-plus/element-plus#18398]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.9`
- Element Plus Version: `2.8.3`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5)

### Steps to reproduce

```vue
<script lang="ts">
import { ElMessage } from 'element-plus';

ElMessage.success({
  message: '123',
});
</script>

<template>
  <div></div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  transition: filter 300ms;
  will-change: filter;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

```

```ts
// vite.config.ts
import ElementPlus from 'unplugin-element-plus/vite';
    ElementPlus({
          format: 'esm',
        }),
        // AutoImport({
        //   resolvers: [ElementPlusResolver()],
        // }),
        // Components({
        //   dirs: [],
        //   resolvers: [ElementPlusResolver()],
        // }),
      ],
```

### What is Expected?

unplugin-element-plus 经测试是可以做到 tree shaking并引入组件 css的，为什么文档说要手动引入？

### What is actually happening?

unplugin-element-plus 经测试是可以做到 tree shaking并引入组件 css的，为什么文档说要手动引入？

### Additional comments

unplugin-element-plus 经测试是可以做到 tree shaking并引入组件 css的，为什么文档说要手动引入？

![image](https://github.com/user-attachments/assets/7a918e9d-c507-4bf4-87bb-67aab1449f9a)

**Comment by makedopamine** [comment]
应该是没有更新文档
