### ISSUE TITLE
[Bug Report] `el-popover` does not work when `el-tooltip` is the default slot

### ISSUE THREAD

**Issue by pndllxzzy** [element-plus/element-plus#1843]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
macOS 10.14.6/ Google Chrome	89.0.4389.82

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/s/wonderful-napier-4lrio?file=/src/App.vue

### Steps to reproduce
1. open https://codesandbox.io/s/wonderful-napier-4lrio?file=/src/App.vue
2. click div `reference` in the `Browser` right side of the page, div `popover guide` does not appear

### What is Expected?
div `popover guide`  appear

### What is actually happening?
div `popover guide` does not appear

**Comment by JeremyWuuuuu** [comment]
Simply because `el-tooltip` cannot be root reference of two popups, you need to wrap it with another tag like:
```vue
<template>
  <el-popover placement="bottom-end" :width="200" trigger="click">
    <template #reference>
        <div class="wrap-me">
          <el-tooltip placement="bottom" content="tooltip">
            <div>reference</div>
          </el-tooltip>
        </div>
    </template>
    <div>popover guide</div>
  </el-popover>
</template>
```
