### ISSUE TITLE
[Component] [table] component does not properly clean up side effects after unmounting

### ISSUE THREAD

**Issue by diyan-slavov-infoleven** [element-plus/element-plus#18433]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.8.4`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/devbox/trusting-resonance-9rz3y9)

### Steps to reproduce

Run `npm run test`

The test completes successfully, but the `doLayout` gets called after the test has finished and it causes an uncaught exception that is reported by Vitest.

### What is Expected?

When the toggle button is clicked, the ElTable component will be unmounted from the document.

It should be expected that when the component unmounts, it properly clears all of the side effects that it has registered during its lifecycle.

### What is actually happening?

The `doLayout` function inside ElTable is debounced with a 50ms delay as can be seen here https://github.com/element-plus/element-plus/blob/18a77d5829df0b7db064d634cd45645befe77435/packages/components/table/src/table.vue#L281

When this function is called, it is going to run later, even if the <ElTable /> component has been unmounted from the document. 

This causes issues in test environments, because if the test completes before the debounced doLayout function is called, it will be invoked after the environment (jsdom or alike) has been torn down, which results in uncaught Vitest errors after the test suit has been completed.

### Additional comments

The function that debounce returns has a `cancel` method, which should be called from the `onUnmounted` hook inside <ElTable /> component.

It should either be cancelled, or the implementation of the `doLayout` should check if the component has not unmounted, before performing the side effects.

This is how I imagine a fix would look like

```js
const debouncedUpdateLayout = debounce(doLayout, 50)
onUnmounted(() => debouncedUpdateLayout.cancel())
```

The `useLockscreen` hook, which is used inside the Dialog component also has the same problem

https://github.com/element-plus/element-plus/blob/18a77d5829df0b7db064d634cd45645befe77435/packages/hooks/use-lockscreen/index.ts#L50

The `setTimeout` call can also run after the browser environment has been torn down, leading to the same problem. The code uses nullish coalescent operator for references ( document?.body and subsequently && document ), however, in non-browser environment simply referring to a `document` variable is going to result in a reference error.

For a possible solution, we can just check if the document variable is undefined

```js
  const cleanup = () => {
    setTimeout(() => {
      if (typeof document === 'undefined') {
        return
      }

      removeClass(document?.body, hiddenCls.value)
      if (withoutHiddenClass && document) {
        document.body.style.width = bodyWidth
      }
    }, 200)
  }

```
These bugs cause a lot of issues when ElementPlus is used alongside Vitest ( which is how a lot of the modern workflows are structured ), because they are hard to address on the application level and they lead to unnecessary and confusing error logs on test runs, which can make the tests themselves less reliable.

**Comment by warmthsea** [comment]
![image](https://github.com/user-attachments/assets/fae557ce-e315-4407-8e20-0e0ebbf5280a)

**Comment by warmthsea** [comment]
It doesn't seem to need processing here.

```ts
const cleanup = () => {
  setTimeout(() => {
    removeClass(document?.body, hiddenCls.value)
    if (withoutHiddenClass && document) {
      document.body.style.width = bodyWidth
    }
  }, 200)
}
```

**Comment by diyan-slavov-infoleven** [comment]
> It doesn't seem to need processing here.
> 
> ```ts
> const cleanup = () => {
>   setTimeout(() => {
>     removeClass(document?.body, hiddenCls.value)
>     if (withoutHiddenClass && document) {
>       document.body.style.width = bodyWidth
>     }
>   }, 200)
> }
> ```

@warmthsea if you run `document?.body` in NodeJS environment ( which is effectively what happens in the tests after jsdom has been torn down ), its gonna throw an error.

The nullish coalescent operator does not work here, because document is not defined and simply referring to it in strict mode is going to result in a reference error.

The code needs to verify if document variable is available before proceeding.

![image](https://github.com/user-attachments/assets/5b66d5f0-0d4c-4dc1-b812-81a43a4d1175)

Thank you for fixing this in a timely manner  ❤️

**Comment by btea** [comment]
As far as I understand, jsdom should simulate document-related APIs and there should be no errors, otherwise, all test cases should have problems.

**Comment by diyan-slavov-infoleven** [comment]
> As far as I understand, jsdom should simulate document-related APIs and there should be no errors, otherwise, all test cases should have problems.

It does, the problem is the delay for the setTimeout is 200ms, so the test completes, `afterEach` hooks run, and eventually the jsdom environment is destroyed, and then the callback gets invoked and `document` is no longer defined.

The timeout needs to either be cancelled, ran before the component unmounts, or the callback needs to tolerate document variable not being defined

![image](https://github.com/user-attachments/assets/984c15e1-34db-416f-a45b-ff777386a19e)

**Comment by btea** [comment]
Can you provide a reproducible example? According to the link provided above, there is no error when executing `pnpm test`.

**Comment by diyan-slavov-infoleven** [comment]
> Can you provide a reproducible example? According to the link provided above, there is no error when executing `pnpm test`.

There is no error when running the test script in the reproduction, because the Table component does not use the useLockscreen hook. 

For some reason, this is harder to reproduce by itself, but it fails consistently in our CI/CD environment and on local runs. 

If you see the log from the provided screen, it points to the exact line where the problem occurs, and if you take a look at the code, its the exact same problem like it is with the requestAnimationFrame from the reproduction link.

I can see that you are saying that `document?.body` line should have this covered, however, please note that after Vitest destroys the jsdom instance, we are back to a vanilla nodejs environment, and simply referring to `document` ( even if you omit the ?.body part ) will result in a reference error

**Comment by btea** [comment]
Okay, anyway, it seems better to make a compatibility judgment here.

**Comment by diyan-slavov-infoleven** [comment]
Thank you for resolving these ❤️
