### ISSUE TITLE
[Component] [affix] el-affix: target parameter is invalid

### ISSUE THREAD

**Issue by elkon028** [element-plus/element-plus#18448]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.8.4`
- Browser / OS: `System:     OS: macOS 14.6.1     CPU: (14) arm64 Apple M3 Max     Memory: 1.41 GB / 36.00 GB     Shell: 5.9 - /bin/zsh   Binaries:     Node: 20.16.0 - /usr/local/bin/node     npm: 10.8.2 - /usr/local/bin/npm     pnpm: 9.11.0 - /usr/local/bin/pnpm     Watchman: 2024.09.02.00 - /opt/homebrew/bin/watchman   Browsers:     Chrome: 129.0.6668.70     Safari: 17.6`
- Build Tool: `Vite`

### Related Component

- `el-affix`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsQWZmaXgsIEVsQnV0dG9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdlbC1hZmZpeDogVGFyZ2V0IGNvbnRhaW5lcicpXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8Q29tcD5cbiAgICA8RWxBZmZpeCA6b2Zmc2V0PVwiMjBcIiB0YXJnZXQ9XCIudGFyZ2V0LWNvbnRhaW5lclwiPlxuICAgICAgPEVsQnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+YnV0dG9uPC9FbEJ1dHRvbj5cbiAgICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDEwMDBweDtcIiAvPlxuICAgIDwvRWxBZmZpeD5cbiAgPC9Db21wPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbmh0bWwsYm9keSwjYXBwe1xuICBoZWlnaHQ6MTAwJTtcbn1cbjwvc3R5bGU+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJ3aWR0aDoxMDAlOyBoZWlnaHQ6IDEwMCU7ZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcIj5cbiAgICA8aGVhZGVyIHN0eWxlPVwiaGVpZ2h0OiAxMDBweDtcIj4gaGVhZGVyOiBoZWlnaHQ9MTAwcHg8L2hlYWRlcj5cbiAgICA8ZGl2IGNsYXNzPVwidGFyZ2V0LWNvbnRhaW5lclwiIHN0eWxlPVwiaGVpZ2h0OiAxMDAwcHg7b3ZlcmZsb3cteTogYXV0bztmbGV4OjE7bWluLWhlaWdodDogMDtcIj5cbiAgICAgIDxkaXY+VGFyZ2V0IGNvbnRhaW5lcjwvZGl2PiBcbiAgICAgIDxzbG90IC8+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJfbyI6e319)

### Steps to reproduce

- ./test.vue
```vue
<script setup lang="ts">
import { ElAffix, ElButton } from 'element-plus'
import { ref } from 'vue'
import Comp from './Comp.vue'

const msg = ref('el-affix: Target container')

</script>

<template>
  <h1>{{ msg }}</h1>
  <Comp>
    <ElAffix :offset="20" target=".target-container">
      <ElButton type="primary">button</ElButton>
      <div style="height: 1000px;" />
    </ElAffix>
  </Comp>
</template>
<style>
html,body,#app{
  height:100%;
}
</style>
```
- ./Comp.vue
```vue
<template>
  <div style="width:100%; height: 100%;display: flex; flex-direction: column;">
    <header style="height: 100px;"> header: height=100px</header>
    <div class="target-container" style="height: 1000px;overflow-y: auto;flex:1;min-height: 0;">
      <div>Target container</div> 
      <slot />
    </div>
  </div>
</template>
```

### What is Expected?

Target parameter is valid

### What is actually happening?

Target parameter is invalid

### Additional comments

_(empty)_

**Comment by Fuphoenixes** [comment]
Put this element outside of el-affix.  `<div style="height: 1000px;" />`
```
<script setup lang="ts">
import { ElAffix, ElButton } from 'element-plus'
import { ref } from 'vue'
import Comp from './Comp.vue'

const msg = ref('el-affix: Target container')

</script>
<template>
  <h1>{{ msg }}</h1>
  <Comp>
    <ElAffix :offset="20" target=".target-container">
      <ElButton type="primary">button</ElButton>
    </ElAffix>
    <div style="height: 1000px;" />
  </Comp>
</template>
<style>
html,body,#app{
  height:100%;
}
</style>
```
