### ISSUE TITLE
About the components of the date class, why cancel the value-format formatting attribute?

### ISSUE THREAD

**Issue by asen946640** [element-plus/element-plus#1844]
关于日期类的组件 为什么要取消掉 value-format 格式化属性呢
没有这个属性来 难道以后每个日期组件都要写一个chant事件来格式化吗

About the components of the date class, why cancel the value-format formatting attribute?
Without this attribute, would it be necessary to write a chant event to format each date component in the future?

**Comment by mayuxian** [comment]
I am also confused, having introduced DayJS, if there is a value-format will give the user a better experience, expect to add

**Comment by iamkun** [comment]
We will take this into deep consideration. Sorry for the innocence ATM.

**Comment by iamkun** [comment]
fixed in #2120

**Comment by xiaoLus** [comment]
请问现在 value-format 如何使用 dayjs.tz.setDefault() 后的时区进行转换？
@iamkun
