### ISSUE TITLE
[Docs] 官方文档点击头部之后左侧功能菜单不刷新啦

### ISSUE THREAD

**Issue by zc-tired** [element-plus/element-plus#18466]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.11`
- Element Plus Version: `2.8.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/design)

### Steps to reproduce

打开链接之后点击右上角的指南和组件，会在链接后面增加一个.html。这就导致了【Overview 组件总览】和【基础】这些不切换了。。。需要把.html去掉在回车才会出来，希望修复一下。。。

### What is Expected?

切换头部的指南和组件左侧可以渲染出正确的内容

### What is actually happening?

切换头部的指南和组件左侧渲染出错误的内容，需要把.html去掉之后才会正常，但是再点击另一个又会加上.html不会渲染正确的内容

### Additional comments

_(empty)_

**Comment by wangxuefei95** [comment]
![image](https://github.com/user-attachments/assets/9da4e8ac-32b4-4276-bd8c-23fce2fbf6ff)

**Comment by wangxuefei95** [comment]
样式也错乱了

**Comment by wangxuefei95** [comment]
还有button 设置size 文字大小不变的问题

**Comment by zc-tired** [comment]
> 还有button 设置size 文字大小不变的问题

size我这里是能改变文字大小的，small是12px，看看是不是你自定义了文字大小覆盖了

**Comment by btea** [comment]
![image](https://github.com/user-attachments/assets/c5a62f36-d979-4a56-ad96-dd80d187b53a)

我这边看着是正常的。

**Comment by zc-tired** [comment]
> ![image](https://private-user-images.githubusercontent.com/24516654/374807641-c5a62f36-d979-4a56-ad96-dd80d187b53a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTAzNzcsIm5iZiI6MTcyODQ1MDA3NywicGF0aCI6Ii8yNDUxNjY1NC8zNzQ4MDc2NDEtYzVhNjJmMzYtZDk3OS00YTU2LWFkOTYtZGQ4MGQxODdiNTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA1MDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ODk4MWZhZWQ1OTg1YmJhM2YwMDQ4NTc4NTEyZTRmOTAzNTI4Y2QxYzRjNWVlMzY0ZjYyNGZlNWQ1ZjIwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-cHWwkEJ0kiKgmBHJQ7jvto2S7qYFeuNHy1_u9IRW-c)
> 
> 我这边看着是正常的。


https://github.com/user-attachments/assets/163038b3-83ce-47fd-b0c3-71f14ba801f3

你看看视频呢

**Comment by btea** [comment]
确实存在问题。

**Comment by 1393254712** [comment]
一样 切换到国内镜像就没问题

**Comment by makedopamine** [comment]
重新发布了文档，问题已修复。
