### ISSUE TITLE
[Bug Report] Uncaught TypeError: Cannot read property 'target' of undefined 

### ISSUE THREAD

**Issue by pengxiaotian** [element-plus/element-plus#1847]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Firefox/Chrome latest

### Vue version
3.0.6

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/directives/click-outside/index.ts

### Steps to reproduce
If user called stopPropagation on mousedown somehow. There will be an exception in the documentHandler function
/packages/directives/click-outside/index.ts

### What is Expected?
Should check if the startClick is assigned before using it.

### What is actually happening?
exception

**Comment by ErricLu** [comment]
我也遇到同样的问题，当我使用高德地图api的时候，只要点击地图就会报同样的错误，若页面中移除Element Plus相关表单组件则不会有这个问题

**Comment by pengxiaotian** [comment]
我发现在 1.0.2-beta.37 版本里已经修复了
