### ISSUE TITLE
[Component] [tabs] 动态创建tab样式问题

### ISSUE THREAD

**Issue by andyz168** [element-plus/element-plus#18522]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.11`
- Element Plus Version: `2.8.4`
- Browser / OS: `Edg`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5cbmNvbnN0IHRhYnMgPSByZWYoe1xuICBcImxpc3RcIjogW1xuICAgIFwicGhvbmUtY29kZVwiLFxuICAgIFwicGFzc3dvcmRcIixcbiAgICBcImFwcC1xcmNvZGVcIixcbiAgXSxcbiAgXCJkZWZhdWx0XCI6IFwid2VjaGF0bXAtcXJjb2RlXCIsXG4gIFwidGl0bGVcIjoge1xuICAgIFwicGhvbmUtY29kZVwiOiBcIumqjOivgeeggeeZu+W9lVwiLFxuICAgIFwicGFzc3dvcmRcIjogXCLlr4bnoIHnmbvlvZVcIixcbiAgICBcImFwcC1xcmNvZGVcIjogXCLmiavnoIHnmbvlvZVcIixcbiAgfVxufSwpXG5jb25zdCBhY3RpdmVOYW1lID0gcmVmKFwicGFzc3dvcmRcIilcbmNvbnN0IHRhYk5hbWUgPSAoa2V5OiBzdHJpbmcpID0+IHtcbiAgcmV0dXJuIHRhYnMudmFsdWUudGl0bGVba2V5XVxufVxuY29uc3QgdGFiQ2xpY2sgPSAodGFiOiBUYWJzUGFuZUNvbnRleHQsIGV2ZW50OiBFdmVudCkgPT4ge1xuICBjb25zb2xlLmxvZyh0YWIsIGV2ZW50KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgcmVmPVwidGFiX2lkXCIgdi1pZj1cInRhYnNcIiB0YWItcG9zaXRpb249XCJ0b3BcIiB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIHYtZm9yPVwiKHRhYiwgaW5kZXgpIGluIHRhYnMubGlzdFwiXG4gICAgQHRhYi1jbGljaz1cInRhYkNsaWNrXCI+XG4gICAgPGVsLXRhYi1wYW5lIDpsYWJlbD1cInRhYk5hbWUodGFiKVwiIDpuYW1lPVwidGFiXCI+XG4gICAgICB7eyB0YWIgfX1cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG4gIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgY2xhc3M9XCJkZW1vLXRhYnNcIiBAdGFiLWNsaWNrPVwidGFiQ2xpY2tcIj5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLpqozor4HnoIHnmbvlvZVcIiBuYW1lPVwiZmlyc3RcIj5Vc2VyPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLlr4bnoIHnmbvlvZVcIiBuYW1lPVwic2Vjb25kXCI+Q29uZmlnPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLmiavnoIHnmbvlvZVcIiBuYW1lPVwidGhpcmRcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<script setup lang="ts">
import { ElementPlus } from '@element-plus/icons-vue'
import { version as epVersion } from 'element-plus'
import { ref, version as vueVersion } from 'vue'

const tabs = ref({
  "list": [
    "phone-code",
    "password",
    "app-qrcode",
  ],
  "default": "wechatmp-qrcode",
  "title": {
    "phone-code": "验证码登录",
    "password": "密码登录",
    "app-qrcode": "扫码登录",
  }
},)
const activeName = ref("password")
const tabName = (key: string) => {
  return tabs.value.title[key]
}
const tabClick = (tab: TabsPaneContext, event: Event) => {
  console.log(tab, event)
}
</script>

<template>
   <el-tabs ref="tab_id" v-if="tabs" tab-position="top" v-model="activeName" v-for="(tab,index) in tabs.list"
                     @tab-click="tabClick">
              <el-tab-pane :label="tabName(tab)" :name="tab">
                {{ tab }}
              </el-tab-pane>
            </el-tabs>
</template>

### What is Expected?

横向布局
![image](https://github.com/user-attachments/assets/2752691d-245c-4610-b352-e5cff1d6330e)

### What is actually happening?

垂直布局
![image](https://github.com/user-attachments/assets/ca79236f-6238-4a8e-930b-cd60a0cbf647)

### Additional comments

写死的没问题，动态的样式有问题

**Comment by andyz168** [comment]
` <el-tabs
                ref="tab_id"
                v-model="activeName"
                tab-position="top"
                @tab-click="tabClick"
            >
              <el-tab-pane
                  v-for="(tab, index) in tabs.list"
                  :key="index"
                  :label="tabName(tab)"
                  :name="tab"
              >
                <password v-if="tab === LoginTypeV1.password" @signInSuccess="signInSuccess"
                          @change="changeLoginType"/>
              </el-tab-pane>
            </el-tabs>`
代码写错了，for写错地方了，要写到el-tab-pane

**Comment by warmthsea** [comment]
You need to add this here

![image](https://github.com/user-attachments/assets/d6f0611d-6038-406b-b2ef-f0e7a0bbf9bf)
