### ISSUE TITLE
[Bug Report]build error（vite、vue3、typescript、element plus）

### ISSUE THREAD

**Issue by SonDemigods** [element-plus/element-plus#1852]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
windows 10/Chrome

### Vue version
3.0.11

### Reproduction Link
https://github.com/SonDemigods/vue3_element_init

### Steps to reproduce
An error occurred during the build
![image](https://user-images.githubusercontent.com/23623726/114990161-d2136180-9eca-11eb-820a-2180b4deb243.png)

### What is Expected?
build can be done normally

### What is actually happening?
build error

**Comment by initdc** [comment]
In your ```package.json``` file, it has commands to run, 
```yarn build``` will run ```vue-tsc --noEmit && vite build```

ignore ```vue-tsc --noEmit```, 
just try ```vite build```  ,then ```vite preview```

**Comment by SonDemigods** [comment]
> In your file, it has commands to run,
> will run `package.json``yarn build``vue-tsc --noEmit && vite build`
> 
> ignore ,
> just try ,then `vue-tsc --noEmit``vite build``vite preview`

I tried the solution you provided
`vue-tsc --noEmit`       fail
`vite build`                   success
`vite preview`              success

![image](https://user-images.githubusercontent.com/23623726/115199818-2b2b0180-a126-11eb-8e72-510209525ccc.png)
Is this a problem with type checking?

**Comment by Zhaocl1997** [comment]
> > In your file, it has commands to run,
> > will run `` package.json``yarn build``vue-tsc --noEmit && vite build ``
> > ignore ,
> > just try ,then `` vue-tsc --noEmit``vite build``vite preview ``
> 
> I tried the solution you provided
> `vue-tsc --noEmit` fail
> `vite build` success
> `vite preview` success
> 
> ![image](https://user-images.githubusercontent.com/23623726/115199818-2b2b0180-a126-11eb-8e72-510209525ccc.png)
> Is this a problem with type checking?

I think so. By the way, I recommend you to add `--skipLibCheck` after `--noEmit` option.

**Comment by SonDemigods** [comment]
thank you.
I have solved this problem.
add `--skipLibCheck`,This method is very effective.

**Comment by yob-yob** [comment]
I really wanted an explanation on why this happens... I'm still learning typescript and I don't really know how it locates decoration files... some packages works with skipLibCheck.. say only vue without element-plus.. but with element-plus... it struggles at finding declaration files.. 

I do think Vue3 is has types... and importing from `vue` resolves in an `index.d.ts` file
and importing from `element-plus` resolves in an `index.d.ts` file also... so why does it still say that it can't find declaration files? 

short-version of my error....

```
node_modules/.pnpm/element-plus@1.1.0-beta.12_vue@3.2.12/node_modules/element-plus/lib/components/table/index.d.ts:529:26 - error TS2307: Cannot find module './src/table/defaults' or its corresponding type declarations.

529     defaultSort?: import("./src/table/defaults").Sort;
                             ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/element-plus@1.1.0-beta.12_vue@3.2.12/node_modules/element-plus/lib/components/table/index.d.ts:531:28 - error TS2307: Cannot find module './src/table/defaults' or its corresponding type declarations.

531     summaryMethod?: import("./src/table/defaults").SummaryMethod<any>;
                               ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/element-plus@1.1.0-beta.12_vue@3.2.12/node_modules/element-plus/lib/components/table/index.d.ts:532:27 - error TS2307: Cannot find module './src/table/defaults' or its corresponding type declarations.

532     rowClassName?: import("./src/table/defaults").ColumnCls<any>;
                              ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/element-plus@1.1.0-beta.12_vue@3.2.12/node_modules/element-plus/lib/components/table/index.d.ts:535:33 - error TS2307: Cannot find module './src/table/defaults' or its corresponding type declarations.

535     headerRowClassName?: import("./src/table/defaults").ColumnCls<any>;
                                    ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/element-plus@1.1.0-beta.12_vue@3.2.12/node_modules/element-plus/lib/components/table/src/table-column/defaults.d.ts:3:28 - error TS2307: Cannot find module '../table/defaults' or its corresponding type declarations.

3 import type { Table } from '../table/defaults';
                             ~~~~~~~~~~~~~~~~~~~
```
