### ISSUE TITLE
[Component] [All] 求助:Nuxt3项目引入ElementPlus库后导致Vite热刷新失效问题

### ISSUE THREAD

**Issue by Dark-Skl** [element-plus/element-plus#18537]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `edge win11`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Link](http://localhost:3000)

### Steps to reproduce

创建一个Nuxt3项目，通过pnpm install 安装依赖后再 pnpm install element-plus 安装UI库，然后安装Nuxt3开发模块pnpm i @element-plus/nuxt -D 最后再nuxt.config.ts里配置UI 
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  modules:["@element-plus/nuxt"],
  devtools: { enabled: true }
})
后发现vite无法热刷新

### What is Expected?

写好代码保存即可及时热刷新

### What is actually happening?

写好代码保存即无法热刷新

### Additional comments

无

**Comment by zhuopengfei001** [comment]
也是遇到同样的问题。

**Comment by warmthsea** [comment]
> 也是遇到同样的问题。

请提供一个有效的复现仓库

**Comment by zhuopengfei001** [comment]
https://github.com/zhuopengfei001/nuxt-app

**Comment by zhuopengfei001** [comment]
上面这个库可以复线该问题。

**Comment by warmthsea** [comment]
@zhuopengfei001 @Dark-Skl 

我升级了 element-plus/nuxt 的版本以及新增了 .npmrc 配置热更新是正常的

![image](https://github.com/user-attachments/assets/530e1658-3479-4db0-b315-943e80b03b0f)
![screenshots](https://github.com/user-attachments/assets/34060a08-f6b6-4359-bdcf-ec594c3e22a6)
