### ISSUE TITLE
[bug report] error occurred when clicking select all in the cycled El checkbox

### ISSUE THREAD

**Issue by zxgMaster** [element-plus/element-plus#1853]
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Google Chrome 版本 90.0.4430.61（正式版本）beta (x86_64)

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/zhaoxiaojiu/pen/eYgKXYa

### Steps to reproduce
在循环产生的多个选择框中，如果未选中的个数剩一个的时候，在去点击全选就会取消全选

### What is Expected?
希望在没有全选的时候，点击能全选

### What is actually happening?
会导致取消选择

**Comment by inottn** [comment]
I don't think it's a bug. Maybe you could modify the code, like below.
```js
handleCheckedCitiesChange(value, item) {
    let checkedCount = value.length;
    item.checkAll = checkedCount > item.children.length - 1;
    item.isIndeterminate = checkedCount > 0 && checkedCount < item.children.length;
}
```

**Comment by zxgMaster** [comment]
> I don't think it's a bug. Maybe you could modify the code, like below.
> 
> ```js
> handleCheckedCitiesChange(value, item) {
>     let checkedCount = value.length;
>     item.checkAll = checkedCount > item.children.length - 1;
>     item.isIndeterminate = checkedCount > 0 && checkedCount < item.children.length;
> }
> ```
Thank you for your advice. I'll have a try
