### ISSUE TITLE
[Style] [All] 2.8.5版本，sass在编译时报错

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#18544]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.38`
- Element Plus Version: `2.8.5`
- Browser / OS: `chrome 120`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

![image](https://github.com/user-attachments/assets/39526ce8-d3d7-4b8c-ab99-7cef17f4b606)

### Steps to reproduce

升级到2.8.5版本，工程启动时sass报错

### What is Expected?

修复这个问题

### What is actually happening?

sass报错

### Additional comments

_(empty)_

**Comment by jiaozhiye** [comment]
2.8.4 版本不报错

**Comment by warmthsea** [comment]
@jiaozhiye 

Please upgrade the sass version and try again.

See more: 
https://element-plus.org/en-US/guide/installation.html#sass

**Comment by lvzhenbo** [comment]
@jiaozhiye 更新sass版本1.79以上

**Comment by Zhaojjjjjj** [comment]
> @jiaozhiye 更新sass版本1.79以上

<img width="663" alt="image" src="https://github.com/user-attachments/assets/ffb9dc60-00d6-47d9-bbd9-fc7f4d80e1b6">
更新完sass了，报错变成了这个

**Comment by lvzhenbo** [comment]
> > @jiaozhiye 更新sass版本1.79以上
> 
> <img width="663" alt="image" src="https://github.com/user-attachments/assets/ffb9dc60-00d6-47d9-bbd9-fc7f4d80e1b6">
> 更新完sass了，报错变成了这个

这是你项目里的了，查看sass和vite对sass支持的更改应该能找到是什么问题
