### ISSUE TITLE
[Component] [select, option] select组件在2.8.2及以上版本的回显行为和之前版本不一致

### ISSUE THREAD

**Issue by SuperMao00** [element-plus/element-plus#18543]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.8.2`
- Browser / OS: `Chrome 129.0.6668.100 / window 11`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQsIGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgSXRlbSB7XG4gIGxhYmVsOiBzdHJpbmc7XG4gIHZhbHVlOiBzdHJpbmc7XG59XG5cbmNvbnN0IHN0YXRlcyA9IFtcbiAgJ0FsYWJhbWEnLFxuICAnQWxhc2thJyxcbiAgJ0FyaXpvbmEnLFxuICAnQXJrYW5zYXMnLFxuICAnQ2FsaWZvcm5pYScsXG4gICdDb2xvcmFkbycsXG4gICdDb25uZWN0aWN1dCcsXG4gICdEZWxhd2FyZScsXG4gICdGbG9yaWRhJyxcbiAgJ0dlb3JnaWEnLFxuICAnSGF3YWlpJyxcbiAgJ0lkYWhvJyxcbiAgJ0lsbGlub2lzJyxcbiAgJ0luZGlhbmEnLFxuICAnSW93YScsXG4gICdLYW5zYXMnLFxuICAnS2VudHVja3knLFxuICAnTG91aXNpYW5hJyxcbiAgJ01haW5lJyxcbiAgJ01hcnlsYW5kJyxcbiAgJ01hc3NhY2h1c2V0dHMnLFxuICAnTWljaGlnYW4nLFxuICAnTWlubmVzb3RhJyxcbiAgJ01pc3Npc3NpcHBpJyxcbiAgJ01pc3NvdXJpJyxcbiAgJ01vbnRhbmEnLFxuICAnTmVicmFza2EnLFxuICAnTmV2YWRhJyxcbiAgJ05ldyBIYW1wc2hpcmUnLFxuICAnTmV3IEplcnNleScsXG4gICdOZXcgTWV4aWNvJyxcbiAgJ05ldyBZb3JrJyxcbiAgJ05vcnRoIENhcm9saW5hJyxcbiAgJ05vcnRoIERha290YScsXG4gICdPaGlvJyxcbiAgJ09rbGFob21hJyxcbiAgJ09yZWdvbicsXG4gICdQZW5uc3lsdmFuaWEnLFxuICAnUmhvZGUgSXNsYW5kJyxcbiAgJ1NvdXRoIENhcm9saW5hJyxcbiAgJ1NvdXRoIERha290YScsXG4gICdUZW5uZXNzZWUnLFxuICAnVGV4YXMnLFxuICAnVXRhaCcsXG4gICdWZXJtb250JyxcbiAgJ1ZpcmdpbmlhJyxcbiAgJ1dhc2hpbmd0b24nLFxuICAnV2VzdCBWaXJnaW5pYScsXG4gICdXaXNjb25zaW4nLFxuICAnV3lvbWluZycsXG5dO1xuXG5jb25zdCBzZWxlY3RlZCA9IHJlZihcIlwiKTtcblxuY29uc3QgbGlzdCA9IHJlZjxJdGVtW10+KFtdKTtcblxuY29uc3QgdGV4dCA9IHJlZihcIlwiKTtcblxuY29uc3QgZmlsdGVyTGlzdCA9IGNvbXB1dGVkKCgpID0+IHtcbiAgcmV0dXJuIGxpc3QudmFsdWUuZmlsdGVyKHQgPT4gdC5sYWJlbC5pbmNsdWRlcyh0ZXh0LnZhbHVlKSk7XG59KTtcblxub25Nb3VudGVkKCgpID0+IHtcbiAgbGlzdC52YWx1ZSA9IHN0YXRlcy5tYXAoKGl0ZW0pID0+IHtcbiAgICByZXR1cm4geyB2YWx1ZTogYHZhbHVlOiR7aXRlbX1gLCBsYWJlbDogYGxhYmVsOiR7aXRlbX1gIH1cbiAgfSlcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PmVwVmVyc2lvbjoge3tlcFZlcnNpb259fTwvZGl2PlxuICA8ZGl2PnZ1ZVZlcnNpb246IHt7dnVlVmVyc2lvbn19PC9kaXY+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdGVkXCI+XG4gICAgPHRlbXBsYXRlICNoZWFkZXI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cInRleHRcIiBjbGVhcmFibGUgcGxhY2Vob2xkZXI9XCLmn6Xor6JcIiAvPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gZmlsdGVyTGlzdFwiIDprZXk9XCJpdGVtLnZhbHVlXCIgOnZhbHVlPVwiaXRlbS52YWx1ZVwiIDpsYWJlbD1cIml0ZW0ubGFiZWxcIiAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMi9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMi90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjUuMTAvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQDMuNS4xMC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjIvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMi9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

不使用组件原生的filterable，在header插槽使用el-input自定义过滤功能(业务需求：数据分页且远程检索)
1.先选中一个值，此时回显的文案是label开头，也就是回显了el-option的label值
2.在头部输入框输入检索文字，过滤掉已选项，会发现回显的是value开头，也就是回显了el-option的value值

### What is Expected?

回显保持和2.8.1及以前版本的一致的行为

### What is actually happening?

回显异常

### Additional comments
在Element Plus Playground中，切换2.8.1和2.8.2版本查看实际效果

**Comment by warmthsea** [comment]
你提供的例子看起来是正常的
![image](https://github.com/user-attachments/assets/27e2cda0-a0d4-4112-bcc1-e70847ef7c69)

**Comment by SuperMao00** [comment]
> 你提供的例子看起来是正常的 ![image](https://private-user-images.githubusercontent.com/45450994/376129438-27e2cda0-a0d4-4112-bcc1-e70847ef7c69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODkwNjgsIm5iZiI6MTcyODg4ODc2OCwicGF0aCI6Ii80NTQ1MDk5NC8zNzYxMjk0MzgtMjdlMmNkYTAtYTBkNC00MTEyLWJjYzEtZTcwODQ3ZWY3YzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA2NTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjI2NTA1NTM2NmIzODM1NTE0MzlmN2M5NzU3OTQyMWJlNmNjMzgxOWY2Yjc1NDVhZTYzOTZmYzQ4MTIxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.19QpponQFoaxbISaiI8hPYi0mlCA8SECQjj7BDn6des)

![image](https://github.com/user-attachments/assets/d12b483e-017f-4880-a825-809a74bf7519)
偶现问题么

**Comment by warmthsea** [comment]
![screenshots](https://github.com/user-attachments/assets/55034c53-1c14-42d0-aed4-200a70a6d591)

**Comment by SuperMao00** [comment]
https://github.com/user-attachments/assets/f5b3715a-280e-4961-889e-80b620dbcd19

**Comment by shizhihuaxu** [comment]
@warmthsea 同我之前 [提出的issues](https://github.com/element-plus/element-plus/issues/18332) 好像是一个 bug，多选没问题，单选有问题，select 及 selectv2 均存在此问题，在 fix pr 的 playground 里试了一下好像并没有被解决

**Comment by warmthsea** [comment]
> @warmthsea 同我之前 [提出的issues](https://github.com/element-plus/element-plus/issues/18332) 好像是一个 bug，多选没问题，单选有问题，select 及 selectv2 均存在此问题，在 fix pr 的 playground 里试了一下好像并没有被解决

看起来是2个问题，select 是之前变动影响到了，select-v2 似乎一直都有这个问题

**Comment by shizhihuaxu** [comment]
> > @warmthsea 同我之前 [提出的issues](https://github.com/element-plus/element-plus/issues/18332) 好像是一个 bug，多选没问题，单选有问题，select 及 selectv2 均存在此问题，在 fix pr 的 playground 里试了一下好像并没有被解决
> 
> 看起来是2个问题，select 是之前变动影响到了，select-v2 似乎一直都有这个问题

[这位师傅的 pr ](https://github.com/element-plus/element-plus/pull/18334)可以解决掉 bug，代码是否合理还需团队 review 一下
