### ISSUE TITLE
[Component] [tabs] el-tabs 无法禁用键盘切换

### ISSUE THREAD

**Issue by qinfeng0214** [element-plus/element-plus#18545]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `无`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlVGFiXCIgQHRhYi1jbGljaz1cImhhbmRsZVRhYkNsaWNrXCIgQGtleWRvd24ubmF0aXZlLnN0b3A+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwi55So5oi3566h55CGXCIgbmFtZT1cImZpcnN0XCI+XG4gICAgICDnlKjmiLfnrqHnkIbnlYzpnaLnmoTlhoXlrrkuLi5cbiAgICA8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIumFjee9rueuoeeQhlwiIG5hbWU9XCJzZWNvbmRcIj5cbiAgICAgIOmFjee9rueuoeeQhueVjOmdoueahOWGheWuuS4uLlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwi6KeS6Imy566h55CGXCIgbmFtZT1cInRoaXJkXCI+XG4gICAgICDop5LoibLnrqHnkIbnlYzpnaLnmoTlhoXlrrkuLi5cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcblxuZXhwb3J0IGRlZmF1bHQge1xuICBzZXR1cCgpIHtcbiAgICBjb25zdCBhY3RpdmVUYWIgPSByZWYoJ2ZpcnN0Jyk7IC8vIOm7mOiupOmAieS4reesrOS4gOS4quagh+etvumhtVxuXG4gICAgY29uc3QgaGFuZGxlVGFiQ2xpY2sgPSAodGFiLCBldmVudCkgPT4ge1xuICAgICAgY29uc29sZS5sb2coJ+mAieS4reeahOagh+etvumhtTonLCB0YWIubGFiZWwpO1xuICAgIH07XG5cbiAgICByZXR1cm4ge1xuICAgICAgYWN0aXZlVGFiLFxuICAgICAgaGFuZGxlVGFiQ2xpY2tcbiAgICB9O1xuICB9XG59O1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi8qIOS9oOWPr+S7peWcqOi/memHjOa3u+WKoOS4gOS6m+iHquWumuS5ieagt+W8jyAqL1xuLmVsLXRhYnMtLXRvcCB7XG4gIG1hcmdpbi10b3A6IDIwcHg7XG59XG48L3N0eWxlPiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

键盘按左右键，可以控制 tabs 切换

### What is Expected?

不希望键盘可以控制 tabs 切换

### What is actually happening?

键盘按左右键，可以控制 tabs 切换

### Additional comments

我应该如何做

**Comment by betavs** [comment]
@warmthsea Is it feasible to add `keyboard-controllable` attribute to Tabs component?

**Comment by warmthsea** [comment]
> @warmthsea Is it feasible to add `keyboard-controllable` attribute to Tabs component?

IMO, `keyboard-switch` is more concise.

Refer test code:
https://github.com/element-plus/element-plus/pull/16902/files#diff-b88917b414d144644317f2eb8b41271a39498a7ee25bbf094cd003e0ad8cb96b

**Comment by tolking** [comment]
Tabs 组件聚焦时通过键盘切换标签是无障碍的规范要求，禁用这种行为会影响无障碍功能。

你可能需要考虑其它方案

**Comment by qinfeng0214** [comment]
> Tabs 组件聚焦时通过键盘切换标签是无障碍的规范要求，禁用这种行为会影响无障碍功能。
> 
> 你可能需要考虑其它方案

thanks
