### ISSUE TITLE
[Style] [table-v2] 虚拟表格滚动条bug

### ISSUE THREAD

**Issue by wypbin** [element-plus/element-plus#18550]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `Chrome/129.0.0.0 `
- Build Tool: `esbuild`

### Related Component

- `el-table-v2`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table-v2.html)

### Steps to reproduce

官网的虚拟表格第三个案例就可以看到，鼠标进入左侧浮动的列上面会出现滚动条

### What is Expected?

不出现滚动条

### What is actually happening?

出现了滚动条

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/9675d798-f2bc-48f9-bb7e-f12f2097696b)

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/18179

It seems that this change caused.

**Comment by elarbor** [comment]
表格就该用一个组件，就叫`<el-table>` 。现在是两个[`<el-table>` ](https://element-plus.org/zh-CN/component/table.html)和[`<el-table-v2>`](https://element-plus.org/zh-CN/component/table-v2.html) 。

用type区分更好一点：
`<el-table type="default">` 就是原来的`<el-table>`组件
`<el-table type="virtualized">`  就是原来的`<el-table-v2>` 组件
`<el-table type="第三种">`  就是以后的`<第三种>` 组件。    ......
