### ISSUE TITLE
[Component] [tabs] 升级2.8.0后，tabs标题在最底下

### ISSUE THREAD

**Issue by lau96** [element-plus/element-plus#18589]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.8.0`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

playground打不开。此问题在多个生产环境均可复现

### Steps to reproduce

<el-tabs v-model="activeName">
      <el-tab-pane label="tab1" name="tab1">
        <slot name="tab1" />
      </el-tab-pane>
      <el-tab-pane label="tab2" name="tab2">
        <slot name="tab2" />
      </el-tab-pane>
    </el-tabs>

### What is Expected?

tab在最顶上显示

### What is actually happening?

tab在最底下显示

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
谢谢反馈，的确存在这个问题，是为了处理 SSR，请参考:

https://github.com/element-plus/element-plus/issues/18455#issuecomment-2399020930
