### ISSUE TITLE
[Component] [form] cdn引入vue3和elementplus2.8.5本地开发，调用el-form表单组件validate方法无效，报错：异常：TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at AsyncFunction.invokeGetter (<anonymous>:3:28

### ISSUE THREAD

**Issue by web-du** [element-plus/element-plus#18610]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `Chrome  129.0.6668.90（正式版本） （64 位）`
- Build Tool: `CDN`

### Related Component

- `el-form`

### Reproduction Link

[CodePen](https://codepen.io/web-du/pen/zYgdwVV)

### Steps to reproduce

用户主动点击按钮调用el-form组件的validate方法无效

### What is Expected?

可以验证整个表单

### What is actually happening?

无任何反馈

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
```diff
- :mode="formData"
+ :model="formData"
```
