### ISSUE TITLE
[Docs] [table] 中文文档，Table 表格组件的Table API 的Table 属性中的border类型和default错误，英文文档正常

### ISSUE THREAD

**Issue by Xin-hai** [element-plus/element-plus#18626]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#table-api)

### Steps to reproduce

文档中查看 Table 表格组件的Table API 的Table 属性中的border类型和default错误

### What is Expected?

border属性类型应为 boolean ,而默认值为false

### What is actually happening?

border属性类型为	::: ,而默认值为boolean。

### Additional comments

无

![Snipaste_2024-10-21_22-42-38](https://github.com/user-attachments/assets/6e849a14-0400-49ef-bdd7-19a2177d8814)

**Comment by btea** [comment]
多谢反馈，已修改。下载发布会更新。
