### ISSUE TITLE
[Component] [descriptions, descriptions-item] Descriptions 中文下，label 会换行

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#18639]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0`
- Build Tool: `Vite`

### Related Component

- `el-descriptions`
- `el-descriptions-item`

### Reproduction Link
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInNpemVcIj5cbiAgICA8ZWwtcmFkaW8gdmFsdWU9XCJsYXJnZVwiPkxhcmdlPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gdmFsdWU9XCJkZWZhdWx0XCI+RGVmYXVsdDwvZWwtcmFkaW8+XG4gICAgPGVsLXJhZGlvIHZhbHVlPVwic21hbGxcIj5TbWFsbDwvZWwtcmFkaW8+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG5cbiAgPGVsLWRlc2NyaXB0aW9uc1xuICAgIGNsYXNzPVwibWFyZ2luLXRvcFwiXG4gICAgdGl0bGU9XCJXaXRoIGJvcmRlclwiXG4gICAgOmNvbHVtbj1cIjNcIlxuICAgIDpzaXplPVwic2l6ZVwiXG4gICAgYm9yZGVyXG4gID5cbiAgICA8dGVtcGxhdGUgI2V4dHJhPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPk9wZXJhdGlvbjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNlbGwtaXRlbVwiPlxuICAgICAgICAgIDxlbC1pY29uIDpzdHlsZT1cImljb25TdHlsZVwiPlxuICAgICAgICAgICAgPHVzZXIgLz5cbiAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAg55So5oi35ZCNXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIOa1i+ivleS4gOS4quWQjeivjVxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNlbGwtaXRlbVwiPlxuICAgICAgICAgIDxlbC1pY29uIDpzdHlsZT1cImljb25TdHlsZVwiPlxuICAgICAgICAgICAgPGlwaG9uZSAvPlxuICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgICDlj7fnoIFcbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAg5rWL6K+V5LiA5Liq5ZCN6K+N5rWL6K+V5LiA5Liq5ZCN6K+N5rWL6K+V5LiA5Liq5ZCN6K+NXG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8bG9jYXRpb24gLz5cbiAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAgUGxhY2VcbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgU3V6aG91XG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8dGlja2V0cyAvPlxuICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgICBSZW1hcmtzXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC10YWcgc2l6ZT1cInNtYWxsXCI+U2Nob29sPC9lbC10YWc+XG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8b2ZmaWNlLWJ1aWxkaW5nIC8+XG4gICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgIOWcsOWdgFxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICDmtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or41cbiAgICA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICA8L2VsLWRlc2NyaXB0aW9ucz5cblxuICA8ZWwtZGVzY3JpcHRpb25zXG4gICAgY2xhc3M9XCJtYXJnaW4tdG9wXCJcbiAgICB0aXRsZT1cIldpdGhvdXQgYm9yZGVyXCJcbiAgICA6Y29sdW1uPVwiM1wiXG4gICAgOnNpemU9XCJzaXplXCJcbiAgICA6c3R5bGU9XCJibG9ja01hcmdpblwiXG4gID5cbiAgICA8dGVtcGxhdGUgI2V4dHJhPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPk9wZXJhdGlvbjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVXNlcm5hbWVcIj5rb29yaW9va2FtaTwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVGVsZXBob25lXCI+MTgxMDAwMDAwMDA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlBsYWNlXCI+U3V6aG91PC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJSZW1hcmtzXCI+XG4gICAgICA8ZWwtdGFnIHNpemU9XCJzbWFsbFwiPlNjaG9vbDwvZWwtdGFnPlxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiQWRkcmVzc1wiPlxuICAgICAgTm8uMTE4OCwgV3V6aG9uZyBBdmVudWUsIFd1emhvbmcgRGlzdHJpY3QsIFN1emhvdSwgSmlhbmdzdSBQcm92aW5jZVxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gIDwvZWwtZGVzY3JpcHRpb25zPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGNvbXB1dGVkLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBJcGhvbmUsXG4gIExvY2F0aW9uLFxuICBPZmZpY2VCdWlsZGluZyxcbiAgVGlja2V0cyxcbiAgVXNlcixcbn0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgdHlwZSB7IENvbXBvbmVudFNpemUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHNpemUgPSByZWY8Q29tcG9uZW50U2l6ZT4oJ2RlZmF1bHQnKVxuXG5jb25zdCBpY29uU3R5bGUgPSBjb21wdXRlZCgoKSA9PiB7XG4gIGNvbnN0IG1hcmdpbk1hcCA9IHtcbiAgICBsYXJnZTogJzhweCcsXG4gICAgZGVmYXVsdDogJzZweCcsXG4gICAgc21hbGw6ICc0cHgnLFxuICB9XG4gIHJldHVybiB7XG4gICAgbWFyZ2luUmlnaHQ6IG1hcmdpbk1hcFtzaXplLnZhbHVlXSB8fCBtYXJnaW5NYXAuZGVmYXVsdCxcbiAgfVxufSlcbmNvbnN0IGJsb2NrTWFyZ2luID0gY29tcHV0ZWQoKCkgPT4ge1xuICBjb25zdCBtYXJnaW5NYXAgPSB7XG4gICAgbGFyZ2U6ICczMnB4JyxcbiAgICBkZWZhdWx0OiAnMjhweCcsXG4gICAgc21hbGw6ICcyNHB4JyxcbiAgfVxuICByZXR1cm4ge1xuICAgIG1hcmdpblRvcDogbWFyZ2luTWFwW3NpemUudmFsdWVdIHx8IG1hcmdpbk1hcC5kZWZhdWx0LFxuICB9XG59KVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtZGVzY3JpcHRpb25zIHtcbiAgbWFyZ2luLXRvcDogMjBweDtcbn1cbi5jZWxsLWl0ZW0ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLm1hcmdpbi10b3Age1xuICBtYXJnaW4tdG9wOiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

将其中一行输入长文本即可

### What is Expected?

label 宽带固定不换行

### What is actually happening?

换行了

### Additional comments

推荐添加 `label-width` 参数可以固定标签宽度，就像 `form` 组件那样。
![图片](https://github.com/user-attachments/assets/ed8a3af9-e06b-45f4-be6d-01496cc29504)

**Comment by Lakphy** [comment]
I will add `labelWidth` in `el-descriptions-item` to solve your issue.

**Comment by Lakphy** [comment]
The feature you suggested has been merged in #18673. You can update to version 2.8.8 and use the `labelWidth` parameter.
