### ISSUE TITLE
[Component] [table] 封装el-table时出现的简单情况下的问题

### ISSUE THREAD

**Issue by wordyhuang** [element-plus/element-plus#18643]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `edge 129.0`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/r02f6s8h/)

### Steps to reproduce

二次封装el-table，使用其插槽后，排版出现异常。

### What is Expected?

能够按照el-table样式进行排版

### What is actually happening?

排版错位

**Comment by warmthsea** [comment]
Refer to:

https://element-plus.org/zh-CN/guide/installation.html#jsdelivr

![image](https://github.com/user-attachments/assets/c7a1e8db-2307-4f7a-bbf2-e29679b2ea37)

**Comment by wordyhuang** [comment]
确实是此问题。已解决
