### ISSUE TITLE
[All] 关于vue安装sass和element-plus后，控制条部分报错，但是sass1.79以上版本开始弃用了，请看文档就直接代码替换

### ISSUE THREAD

**Issue by Verdant-Grassland** [element-plus/element-plus#18659]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790)

### Steps to reproduce

运行控制台有报错，警告提示弃用了，请需要替换

### What is Expected?

sass官方文档这里 https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

### What is actually happening?

sass官方文档这里 https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

### Additional comments

麻烦尽快更新一下吧

**Comment by warmthsea** [comment]
Can you provide relevant screenshots?

**Comment by Verdant-Grassland** [comment]
![0e8722ef8aa3b77e34dea107af6f0df1](https://github.com/user-attachments/assets/694c7c9e-0702-449a-b9f6-78b5caf86dea)
![e6af5eb9b68bc228289c95dd6f7a1d38](https://github.com/user-attachments/assets/e9794b6a-c69f-405e-8fc9-885dcc3cd9e2)

**Comment by warmthsea** [comment]
Refer to https://github.com/element-plus/element-plus/issues/18648#issuecomment-2435261667

**Comment by Verdant-Grassland** [comment]
您好，按照你这个https://pkg.pr.new/element-plus/element-plus/element-plus@0e8454a  好使了，什么时候才能升级呢？

**Comment by warmthsea** [comment]
> 按照你说的安装 这个pnpm add https://pkg.pr.new/element-plus/element-plus@0e8454a
> 
> 就好了，不知道怎么回事？什么时候才能发布新版本

这个是和正式版一样效果的，你下次等版本更新再升一次就行了

**Comment by Verdant-Grassland** [comment]
感谢大佬
