### ISSUE TITLE
[Feature Request] Better flexibility of Popover's width is needed

### ISSUE THREAD

**Issue by mPyth** [element-plus/element-plus#1866]
### Existing Component
Yes

### Component Name
Popover

### Description
`width` of root `<div>` of component Popover is set as its style attribute in runtime, so it could not be customized !  
Here is demo:  https://jsfiddle.net/hrgz3cw4/30/  .

I've tried to set component's prop `width` to `unset` or `auto` but it doesn't work (documentation says that prop `width` should accept string). The only integer value are accepted (with implied pixels unit), but that is not enough flexible (Popover's content could be dynamic).

In demo example I have quite narrow `<div>` with 3 short strings (its background is in green to highlight its width), and it would be nice that popover encompass that `<div>` without forcing me to set its width in pixels (or more precise: to have the same width as its content, in this demo the width of green pixels).

By setting prop `popper-class` to custom `miniMenuPopover` and additional css manipulation (see demo example) I managed to remove the `min-width=150px` restriction, but the same action was not possible for css property `width` - it is set as Popover's root `<div>` style attribute so it could not be overwritten.

* Proposal 1: please remove 'width' from runtime element's style. Setting it in the same way as `min-width` would be enough flexible, so later it could be customized.

* Proposal 2: in my opinion in 99% cases Popover should encompass its children. The ideal solution would be to set  `display: inline-block` to Popover's root `<div>` - in this way it will have width as its content.  
It is important how it is done - it should be done in the same way as `min-width` is set in current code (part of css class **` .el-popover.el-popper `**). In this way those 1% users which need `width` customization (for example `width=150px`) could do it with some additional effort, but it is feasible). In this way all cases are covered.
I have impression that there is no need to set `min-width` to Popover's root `<div>`, but because Popover is used by other components, it is possible that this is needed to avoid existing code breakage.

Proposal 2 is much better than Proposal 1, if possible. If not possible Proposal 1 would be OK.
  

p.s. On the end I found the way to overwrite css `width` by using next code (trick is taken from https://css-tricks.com/override-inline-styles-with-css/ ). Seems that this approach is the only possible and so tricky, so you will probably agree that component customization in this way is not the right way. Here is the css (the emphasis is on quite weird selector and line `width: unset !important`):
```css
div[style].miniMenuPopover.el-popover.el-popper {
  width: unset !important;
  display: inline-block;
}
```

**Comment by JeremyWuuuuu** [comment]
I am sorry that you have encountered the issue. The screenshot below showed that the width value with `unset` worked in the demo you provided. I dunno why you have this issue, but it seemed all good in my perspective.
![image](https://user-images.githubusercontent.com/15975785/115492211-efae4580-a293-11eb-9252-42cc0ae5f368.png)

**Comment by mPyth** [comment]
Thanks for your answer and detailed screenshot.

I can see, why it didn't work for me:
`:width="unset"`    <-- this does not work ('unset' is not member variable, so it has value `undefined`) - I've tried it in this way
`:width="'unset'"`  <-- this is OK
`width="unset"`    <-- this is OK also (this is your approach)

Sorry because spending your time.
I'm going to close the issue.

**Comment by JeremyWuuuuu** [comment]
Yeah, sometimes it's confusing when you using template instead of JSX you always know what type you were giving to the component.
Glad that I could help.
