### ISSUE TITLE
[Component] [notification] 通知弹框同时打开两个 第二个覆盖第一个

### ISSUE THREAD

**Issue by Heyexi** [element-plus/element-plus#18677]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `chorme`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW4xXCI+IFRvcCBSaWdodCA8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMlwiPiBCb3R0b20gUmlnaHQgPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gcGxhaW4gQGNsaWNrPVwib3BlbjNcIj4gQm90dG9tIExlZnQgPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gcGxhaW4gQGNsaWNrPVwib3BlbjRcIj4gVG9wIExlZnQgPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWxOb3RpZmljYXRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4xID0gKCkgPT4ge1xuICBFbE5vdGlmaWNhdGlvbih7XG4gICAgdGl0bGU6ICdDdXN0b20gUG9zaXRpb24nLFxuICAgIG1lc3NhZ2U6IFwiSSdtIGF0IHRoZSB0b3AgcmlnaHQgY29ybmVyXCIsXG4gIH0pXG4gICAgRWxOb3RpZmljYXRpb24oe1xuICAgIHRpdGxlOiAnQ3VzdG9tIFBvc2l0aW9uMTIzJyxcbiAgICBtZXNzYWdlOiBcIkknbSBhdCB0aGUgdG9wIHJpZ2h0IGNvcm5lclwiLFxuICB9KVxufVxuXG5jb25zdCBvcGVuMiA9ICgpID0+IHtcbiAgRWxOb3RpZmljYXRpb24oe1xuICAgIHRpdGxlOiAnQ3VzdG9tIFBvc2l0aW9uJyxcbiAgICBtZXNzYWdlOiBcIkknbSBhdCB0aGUgYm90dG9tIHJpZ2h0IGNvcm5lclwiLFxuICAgIHBvc2l0aW9uOiAnYm90dG9tLXJpZ2h0JyxcbiAgfSlcbn1cblxuY29uc3Qgb3BlbjMgPSAoKSA9PiB7XG4gIEVsTm90aWZpY2F0aW9uKHtcbiAgICB0aXRsZTogJ0N1c3RvbSBQb3NpdGlvbicsXG4gICAgbWVzc2FnZTogXCJJJ20gYXQgdGhlIGJvdHRvbSBsZWZ0IGNvcm5lclwiLFxuICAgIHBvc2l0aW9uOiAnYm90dG9tLWxlZnQnLFxuICB9KVxufVxuXG5jb25zdCBvcGVuNCA9ICgpID0+IHtcbiAgRWxOb3RpZmljYXRpb24oe1xuICAgIHRpdGxlOiAnQ3VzdG9tIFBvc2l0aW9uJyxcbiAgICBtZXNzYWdlOiBcIkknbSBhdCB0aGUgdG9wIGxlZnQgY29ybmVyXCIsXG4gICAgcG9zaXRpb246ICd0b3AtbGVmdCcsXG4gIH0pXG59XG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

看连接 

### What is Expected?

依次弹出

### What is actually happening?

依次弹出

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
```js
const open1 = () => {
  ElNotification({
    title: 'Custom Position',
    message: "I'm at the top right corner",
  })
  nextTick(()=>{
    ElNotification({
      title: 'Custom Position123',
      message: "I'm at the top right corner",
    })
  })
}
```

**Comment by CherishTheYouth** [comment]
If your problem has been solved, Could you close the issue  in your convenience. @Heyexi
