### ISSUE TITLE
[Bug Report] Cannot import custom theme scss file with Vite

### ISSUE THREAD

**Issue by oleksii-shaposhnikov** [element-plus/element-plus#1867]
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
MacOs

### Vue version
3.0.7

### Reproduction Link
https://github.com/vitejs/vite/issues/650

### Steps to reproduce
Just use Vue 3   Vite, try to import a scss file like this: 
`@import '~element-plus/packages/theme-chalk/src/index';`

And then Vite returns an error: Can't find stylesheet to import

Postcss config: 

```
const path = require('path');

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},

    'postcss-import': {
      resolve(id, basedir) {
        if (/^~/.test(id)) {
          return path.resolve('./node_modules', id)
        }

        return path.resolve(basedir, id)
      },
    },
  },
}

```

### What is Expected?
Vite should import those styles correctly

### What is actually happening?
Vite can't find Element Scss module

**Comment by JeremyWuuuuu** [comment]
Hi @oleksii-shaposhnikov , could you provide a minimal reproducible repo to us? I will start investigating what caused the issue ASAP.

**Comment by mpicciollicmq** [comment]
@oleksii-shaposhnikov did you find a solution ?

**Comment by Oleksii14** [comment]
@mpicciollicmq unfortunately, not yet

**Comment by mpicciollicmq** [comment]
@oleksii-shaposhnikov It works for us : 

"vite": "2.3.7",
"element-plus": "^1.0.2-beta.53",
"sass": "1.35.1",

You have to import element plus scss file and define your custom variables like this:

`
$--color-primary: #8e54ec;

@import 'element-plus/packages/theme-chalk/src/index';
`

**Comment by Oleksii14** [comment]
@mpicciollicmq you are fully importing the styles in your example. I don't need it because I am using babel-plugin-import and import the stuff on demand. 

Here is my scss:

```
$--color-primary: #0069a6;
$--color-info: #3e8a99;
$--color-danger: #ff5252;
$--color-warning: #fb8c00;

$--font-path: '~element-plus/lib/theme-chalk/fonts';
```

babel.config.json

```
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  plugins: [
    [
      'import',
      {
        libraryName: 'element-plus',
        customStyleName: name => {
          name = name.slice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`
        },
      },
    ],
  ],
}
```

main.ts

```
import 'element-plus/packages/theme-chalk/src/base.scss'
```

vue.config.js

```
const path = require('path')
const fs = require('fs')
const elementScssVariables = fs.readFileSync(path.join(__dirname, 'shared/scss/_element-plus.scss'), 'utf8')
...
css: {
    loaderOptions: {
      sass: {
        additionalData: `
          ${elementScssVariables}
        `,
      },
    },
  },
```

And the custom theme is not working. Version beta.56 broke it. @JeremyWuuuuu do you plan to fix and document it properly? We cannot use the custom theme feature at all in the new versions of element-plus

Please add some docs for configuring the custom theme, while using vue-cli and babel-plugin-import

Thanks in advance!

**Comment by Oleksii14** [comment]
@mpicciollicmq can you share the example with on-demand import?
