### ISSUE TITLE
Can the [feature request] switch provide a hook function before switching

### ISSUE THREAD

**Issue by SorrowX** [element-plus/element-plus#1868]
### Existing Component
Yes

### Component Name
Switch 

### Description
1. 点击Switch开关时，想在值发生变化前处理某些事情
2. 比如处理后台接口，根据返回值再进行是否切换
3. 返回值为真值则继续执行切换，假值则什么都不做

### 组件扩展
1. 新增 一个 beforeChange 属性
```ts
props: {
   // ...
   beforeChange: Function,
   // ...
}
```
2. 改写 switchValue 函数
```ts
// 目前 switchValue函数
const switchValue = (): void => {
  !switchDisabled.value && handleChange()
}

// 改写后的 switchValue函数
const switchValue = (): void => {
  if (switchDisabled.value) return

  const beforeChange = props.beforeChange
  if (!beforeChange) {
    return handleChange()
  }

  const before = beforeChange() as any
  if (isPromise(before)) {
    before.then(result => {
      if (!!result) {
        handleChange()
      }
    }).catch(() => {/* prevent log error */ })
  } else if (!!before) {
    handleChange()
  }
}
```

### 使用姿势
```ts
<template>
  <div class="box">
    <el-switch
      v-model="value"
      active-color="#13ce66"
      inactive-color="#ff4949"
      :loading="loading"
      :before-change="beforeChange"
      @change="change"
    />
  </div>
</template>

<script>
export default {

  data: function() {
    return {
      value: true,
      loading: false,
    }
  },
  methods: {
    beforeChange() {
      this.loading = true
      return new Promise(resolve => {
        setTimeout(() => {
          this.loading = false
          return resolve(true)
        }, 1000)
      })
    },
    change(val) {
      console.log(val)
    },
  },
}
</script>

// beforeChange 函数的返回值为真值则继续执行切换的逻辑，否则不执行
```

### demo运行结果

https://user-images.githubusercontent.com/20411966/115345284-29724400-a1e1-11eb-9eb4-09e3b7d861c3.mp4

看switch开关中的那个loading状态即可

**Comment by JeremyWuuuuu** [comment]
Well, first of all, we have `loading` API for indicating the loading status, when you get the `@change` event triggered, you can set `loading` to true then do whatever you need to do, if your procedure didn't get passed, simply set the `v-model` back to `false`, then you can also set the indicator `loading` to `false` as well.

If we do take the suggestion you raised, what should the API be like? Should `beforeChange` return `promise` to us? You do know that inside `beforeChange` you will have circumstances like async job such as requesting your backend for permission, pre-request for something, etc.

**Comment by SorrowX** [comment]
> Well, first of all, we have `loading` API for indicating the loading status, when you get the `@change` event triggered, you can set `loading` to true then do whatever you need to do, if your procedure didn't get passed, simply set the `v-model` back to `false`, then you can also set the indicator `loading` to `false` as well.
> 
我明白，(一开始我也想到了这种做法)可以利用现有的loading api来达到我所说的需求，但是你会发现这样就会造成来回设置switch的状态，体验不好(我们测试人员会当bug来提)。(后来看了下iview的文档，发现他有beforeChange钩子，我觉得挺便利的。所以我就这提了这个特性）
>If we do take the suggestion you raised, what should the API be like? Should beforeChange return promise to us? You do know that inside beforeChange you will have circumstances like async job such as requesting your backend for permission, pre-request for something, etc.
>
关于这个特性的API是什么样,其实我在上面 ’组件扩展‘ 和 ’使用姿势‘ 都写了代码，大哥是不是没有看啊😂
根据beforeChange函数的返回值，如果该函数是同步函数，直接根据函数的返回值，如果是真值则继续执行switch切换。
如果该函数是异步返回是promise实例，根据结果，如果是真值则继续执行switch切换，否则不执行。
这个特性配合loading api，使用起来，我觉得更方便。
这只是我的想法
@JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Alright, I get it. I personally think that this is some API we could need, you interested making PR on the feature?

**Comment by JeremyWuuuuu** [comment]
I'll let you do the enhancement then.

**Comment by SorrowX** [comment]
> I'll let you do the enhancement then.

好的，大佬，等我搬完砖，我再提pr，感谢认可这个特性

**Comment by createskyak** [comment]
各位大佬，switch 组件在table中初始化的时候，会自动执行 change事件，请问这个如何解决？

**Comment by createskyak** [comment]
请问，switch 组件在table中初始化的时候，会自动执行 change事件，请问这个如何解决？

![image](https://user-images.githubusercontent.com/24787348/116854018-98ac5700-ac29-11eb-89a7-53330b0b1e17.png)

**Comment by kooriookami** [comment]
> 请问，switch 组件在table中初始化的时候，会自动执行 change事件，请问这个如何解决？
> 
> ![image](https://user-images.githubusercontent.com/24787348/116854018-98ac5700-ac29-11eb-89a7-53330b0b1e17.png)

It must be a BUG, re #2147
