### ISSUE TITLE
[Style] [All] 自定义主题sass 警告

### ISSUE THREAD

**Issue by leo95123** [element-plus/element-plus#18708]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.6`
- Browser / OS: `Edg`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/devbox/y4ln3d)

### Steps to reproduce

1. 自定义主题文件
2. 主题文件定义变量后引入 "@use "element-plus/theme-chalk/src/index.scss" as *;"
3. main.ts 引入主题文件

### What is Expected?

不报控制台不报警告

### What is actually happening?

控制台报 Global xxx are deprecated and will be removed in Dart Sass 3.0.0. 
Use string.index instead.

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
Please provide a valid address.

![image](https://github.com/user-attachments/assets/7ac8a8aa-1e4d-4c6f-ab8f-b8e44fb4f673)

**Comment by leo95123** [comment]
> Please provide a valid address.
> 
> ![image](https://private-user-images.githubusercontent.com/45450994/381361754-7ac8a8aa-1e4d-4c6f-ab8f-b8e44fb4f673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTQ0MDYsIm5iZiI6MTczMDI1NDEwNiwicGF0aCI6Ii80NTQ1MDk5NC8zODEzNjE3NTQtN2FjOGE4YWEtMWU0ZC00YzZmLWFiOGYtYjhlNDRmYjRmNjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzgzOTA1OTBjMGJkYWU5Y2ZmMTYyMWNjMjkzYmViMzg3ZWYxMGRmYWViN2ZlMmJmY2NlMjQ4YTIwMDk3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HKLnhl7YzMkXLjFAbkIvYpQ3JHXWMWXWjY-YWQghA7I)

https://codesandbox.io/p/live/1234ebdf-6442-4597-b3ae-2203c948e3ba

**Comment by warmthsea** [comment]
Can you provide an example where I can see the error directly?

![image](https://github.com/user-attachments/assets/a466ba57-eb78-4058-829e-50e507b40d42)

**Comment by leo95123** [comment]
pnpm run build 
![image](https://github.com/user-attachments/assets/4425d773-e375-4e6b-9502-30ee60ec6e7f)

**Comment by warmthsea** [comment]
Can you install this link and try again?

https://github.com/element-plus/element-plus/pull/18711#issuecomment-2446096858

**Comment by IrvingZhao** [comment]
Sass 库，降级至 1.79.x 就行，sass 的 1.80.x 里面，mix 函数，需要通过 @use 'sass:colors' 才能使用

**Comment by leo95123** [comment]
> Sass 库，降级至 1.79.x 就行，sass 的 1.80.x 里面，mix 函数，需要通过 @use 'sass:colors' 才能使用

谢谢。  
我直接定义root 变量解决了
