### ISSUE TITLE
Load element on demand

### ISSUE THREAD

**Issue by lzh-kf** [element-plus/element-plus#1870]
在element-plus的按需加载配置页面 文档错误

请确保已经安装了 sass 和 sass-loader 依赖并将 element-plus/packages/theme-chalk/src/base.scss 文件在入口文件中引入

这个base.scss  应该是index.scss

**Comment by kooriookami** [comment]
The doc is correct, why do you think it should be `index.scss`? `index.scss` includes the whole style files.
