### ISSUE TITLE
[bug report] when multi select is used for El cascade panel, after binding V-model value, the sub node in the panel will be selected and the panel will return to its original position

### ISSUE THREAD

**Issue by jinrongni** [element-plus/element-plus#1871]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
win10 edge 90.0.818.39 

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/s/beautiful-blackwell-p9fxn?file=/src/App.vue

### Steps to reproduce
选择 组件->form->form单选框

### What is Expected?
面板应该保持 选择时 的展开状态

### What is actually happening?
选择完后直接跳到最初状态

**Comment by inottn** [comment]
I reproduced it. I'll try to fix it.

**Comment by JeremyWuuuuu** [comment]
Me too, I can reproduce it both locally and remotely.

**Comment by msidolphin** [comment]
I've found that defining props as literal in the template causes this problem. here is the solution:
But I'm still very confused, and this seems to be Vue3's problem, the value change causes the props change to re-execute the initStore function
![image](https://user-images.githubusercontent.com/26672484/122738484-9b840980-d2b4-11eb-8524-de6952a69bee.png)
