### ISSUE TITLE
[Component] [select] Error occured when fast mount and unmount with ElSelect 

### ISSUE THREAD

**Issue by DavidKitano** [element-plus/element-plus#18712]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.34`
- Element Plus Version: `2.7.8`
- Browser / OS: `Chrome 130.0.6723.69 arm 64, Edge 130 / Mac OS`
- Build Tool: `Vite 2.0.5`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG93ID0gcmVmKGZhbHNlKVxuY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSlcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGhhbmRsZVRvZ2dsZSA9IGFzeW5jICgpID0+IHtcbiAgaWYgKCFzaG93LnZhbHVlKSB7XG4gICAgbXNnLnZhbHVlID0gYXdhaXQgZmV0Y2goKVxuICB9XG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuICBzaG93LnZhbHVlID0gIXNob3cudmFsdWVcbn1cbmNvbnN0IGZldGNoID0gYXN5bmMgKCkgPT4ge1xuICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUscmVqZWN0KSA9PiB7XG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgcmVzb2x2ZSgncmFuZDogJyArIE1hdGgucmFuZG9tKCkgKyBuZXcgRGF0ZSgpKVxuICB9LCBNYXRoLnJhbmRvbSgpICogMTAwICsgNTAwKVxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGJ1dHRvbiBjbGFzcz1cInRvZ2dsZS1idG5cIiBAY2xpY2s9XCJoYW5kbGVUb2dnbGVcIiBzdHlsZT1cIm1hcmdpbi1ib3R0b206IDEwcHg7XCI+VG9nZ2xlIE1lPC9idXR0b24+XG4gIDxkaXYgdi1sb2FkaW5nPVwibG9hZGluZ1wiPlxuICA8ZWwtc2VsZWN0IHYtaWY9XCJzaG93XCIgdi1tb2RlbD1cIm1zZ1wiLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Check the reproduction example, continously quickly click "Toggle Me" and sometimes `TypeError: Cannot read properties of null (reading 'getBoundingClientRect')` occurs.

If it's difficult to make it happen you can try Cypress simulation.

```typescript
describe('Simulation', () => {
  it('Error Occured', () => {
    cy.get('.toggle-btn').contains('Toggle Me').realClick({ clickCount: 99 })
  })
})
```

It happens in a real app. Sometimes when users try to click a element to make selectors visible, and immediately or by accident click it again to make it invisible, this kind of error will appear. It actually has no effects but will be logged by browser and Sentry.

Because of the actual limitation of UI/UX design, it cannot be solved by adding throttles or debounces.

Is it a bug or just wrongly used? Is there any way to solve it?

### What is Expected?

No error

### What is actually happening?

Has error

### Additional comments

Following the console info, it can be traced that it happend in `resetSelectionWidth()` or `resetCalculatorWidth()` in `useSelect.js` 

### Screenshots
![20241030161350](https://github.com/user-attachments/assets/388c9260-7def-452c-a5c2-9000e79011d1)

**Comment by DavidKitano** [comment]
![20241030161350](https://github.com/user-attachments/assets/388c9260-7def-452c-a5c2-9000e79011d1)

**Comment by btea** [comment]
I can't reproduce it using the link you provided. Can you reproduce it using the link you provided?

**Comment by DavidKitano** [comment]
> I can't reproduce it using the link you provided. Can you reproduce it using the link you provided?

It is really difficult to reproduce the issue in Playground.
You can create a new `.vue` file with the code in it and use Cypress to simulate quickly continously click, which is 100% reproducible

Sometimes I can reproduce it manully when network is weak or page is lagging.

**Comment by DavidKitano** [comment]
> I can't reproduce it using the link you provided. Can you reproduce it using the link you provided?

Problem solved, it is because the ResizeObserver API is manually replaced. This issue could be closed
