### ISSUE TITLE
[ Bug Report ]  The abort method of upload is missing

### ISSUE THREAD

**Issue by MQYForverT** [element-plus/element-plus#1872]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
win10

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/9pgqcde6/3/

### Steps to reproduce
1.页面上使用upload组件
<el-upload  ref="upload"></el-upload>

2.在js中调用组件方法abort
setup(props, { emit }){
  const refs: any = reactive({
		upload: null
   })

   onBeforeUnmount(() => {
	console.log(refs.upload)
	refs.upload.abort(null)
  })

  return {
   ...toRefs(refs)
  }

}

### What is Expected?
1.在onBeforeUnmount方法中打印可以看到abort方法
2.可以调用到abort方法

### What is actually happening?
报错：
Uncaught (in promise) TypeError：refs.upload.abort is not a function

**Comment by JeremyWuuuuu** [comment]
Fixed and will be released on Friday this week.

**Comment by MQYForverT** [comment]
> 已修复，将在本周星期五发布。

实际上在上周五并没有进行发布，等到1.0.2-beta.41版本也没有修复此问题
