### ISSUE TITLE
[Bug Report] Element Form validate method throw exceptions

### ISSUE THREAD

**Issue by DevinQi** [element-plus/element-plus#1874]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
Chrome  89.0.4389.128

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/daVincitheboy/pen/ZELqPbx

### Steps to reproduce
In the official example, when you open chrome developer tool, you can find that the validate() throws an un-catch exception

### What is Expected?
should be act like element ui, that exception need to be caught

### What is actually happening?
should be act like element ui, that exception need to be caught

**Comment by JeremyWuuuuu** [comment]
The link you pasted inside was empty, I could'n see anything useful for us for debugging.

**Comment by DevinQi** [comment]
> The link you pasted inside was empty, I could'n see anything useful for us for debugging.

I updated the code pen link in the description and here it is for convenience  https://codepen.io/daVincitheboy/pen/ZELqPbx

It is just the official example for "Form", when I use the validate, async validate throws exceptions when check failed

You can reproduce it by doing a failed validate  in the code pen link with developer console open

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/115489882-8d534600-a28f-11eb-97e0-cf60b7030ed0.png)
![image](https://user-images.githubusercontent.com/15975785/115489998-c7244c80-a28f-11eb-8fb2-20b53bb4ba26.png)

I didn't see any exception been thrown from the console on both the website and codepen

**Comment by DevinQi** [comment]
![截屏2021-04-21 上午10 55 53](https://user-images.githubusercontent.com/13559152/115490211-3863ff80-a290-11eb-82de-f15c48e1ffd3.png)
weird!

**Comment by JeremyWuuuuu** [comment]
Can you provide your Platform with version also Browser with version?
This could be platform related issue.

**Comment by JeremyWuuuuu** [comment]
I've tested on MacOS Big Sur 11.0.1 with both Chrome Version 89.0.4389.128 (Official Build) (x86_64) and Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64), all looking good.
I've also tested on Safari with Version 14.0.1 (16610.2.11.51.8), all looking good.

**Comment by DevinQi** [comment]
> Can you provide your Platform with version also Browser with version?
> This could be platform related issue.

MacOS Catalina version 10.15.7
Google Chrome 89.0.4389.128

btw,  your fast response amaze me! from now on you have one more fan, thanks for the help!

**Comment by JeremyWuuuuu** [comment]
I think it was caused by the button here, it catches exceptions no matter it was handled or not, it will always pause the thread and jump right on the exception, turn off that button you won't have any problem.
![image](https://user-images.githubusercontent.com/15975785/115490886-89c0be80-a291-11eb-8bb4-41135602d910.png)

**Comment by DevinQi** [comment]
Yep, that's it
Thanks for the help, issue closed
