### ISSUE TITLE
[Component] [option] el-option在disabled模式下还能被删除问题

### ISSUE THREAD

**Issue by guday** [element-plus/element-plus#18743]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.8.7`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgdGl0bGU6IFwib3B0aW9uMVwiXG4gIH0sXG4gIHtcbiAgICB0aXRsZTogXCJvcHRpb24yXCJcbiAgfSxcbl07XG5cbmNvbnN0IGN1cnJlbnRWYWx1ZSA9IHJlZihbXCJvcHRpb24xXCIsXCJvcHRpb24yXCJdKTsgXG5jb25zdCBkaXNhYmxlZCA9IHJlZihmYWxzZSlcbmNvbnN0IG9uQ2hhbmdlViA9ICh2KSA9PiB7XG4gIGNvbnNvbGUubG9nKGBvdXRwdXQtPnZgLCB2KTtcbn07XG5zZXRUaW1lb3V0KCgpID0+IHtcbiAgZGlzYWJsZWQudmFsdWUgPSB0cnVlXG59LCAxMDApO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPumXrumimDE8L2gxPlxuICA8aDM+5aaC5p6cZWwtb3B0aW9u55qEZGlzYWJsZWTmmK/liqjmgIHorr7nva50cnVl55qE77yI6buY6K6kZmFsc2XvvInvvIzplK7nm5jnmoQgYmFja1NwYWNl5oyJ6ZSu5Y+v5Lul5Yig6ZmkPC9oMz5cbiAgPEVsU2VsZWN0IHYtbW9kZWw9XCJjdXJyZW50VmFsdWVcIiBtdWx0aXBsZSBAY2hhbmdlPVwib25DaGFuZ2VWXCIgZmlsdGVyYWJsZT5cbiAgICAgIDxFbE9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gZGF0YVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0udGl0bGVcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnRpdGxlXCJcbiAgICAgICAgOmtleT1cIml0ZW0udGl0bGVcIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiXG4gICAgICA+PC9FbE9wdGlvbj5cbiAgICA8L0VsU2VsZWN0PlxuXG4gXG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly91bnBrZy5jb20vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3VucGtnLmNvbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vdW5wa2cuY29tL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

如果el-option的disabled是动态设置true的（默认false），键盘的 backSpace按键可以删除改el-option

### What is Expected?

el-option设置disabled时，不可被删除。
1. tag上不显示close按钮 // 组件已实现
2. 激活el-select后，按键盘backSpace按键，不可被删除 // 此处有bug
3. 看el-option键盘删除的源码，只屏蔽了delete，没屏蔽backSpace // 此处有bug

### What is actually happening?

按键盘backSpace按键，disabled的el-option被删除掉了

### Additional comments

本人现在项目中的临时解决方案是，对所有el-option选项，默认设置为true，然后动态更新为true，false；可临时屏蔽该问题

_(empty)_

**Comment by cszhjh** [comment]
此问题引起的原因在[`useSelect.ts 中 630 行处`](https://github.com/element-plus/element-plus/blob/2a032217c79bfc7b7b1ab1b10838b00f313a918b/packages/components/select/src/useSelect.ts#L630)中将`option`加入`disabledOptions`时的判断未考虑动态修改`disabled`的情况。

可以将此issue分配给我吗？我想尝试解决这个bug

**Comment by btea** [comment]
@cszhjh 谢谢你的积极参与，已将此问题分配给你了。

**Comment by cszhjh** [comment]
> @cszhjh 谢谢你的积极参与，已将此问题分配给你了。

非常感谢，我将开始我的工作，稍后将提交PR
