### ISSUE TITLE
[ Bug Report ]  http request pending using v - show build in the table slot

### ISSUE THREAD

**Issue by LYao0919** [element-plus/element-plus#1875]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
mac

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/tsh5bdp6/4/

### Steps to reproduce
http request pending using v-show build in the table slot

1. When using slots in the table column and using v-show in the slots
2. Run build --> cd dist --> http-server, when the page is packaged and run, the http request of the current page will be in the pending state, causing the page to crash

When changing v-show to v-if this problem disappears

### What is [Expected?](url)
Use v-show normally

### What is actually happening?
英语不好 ，用中文把整体流程描述如下：
复现步骤：当我在table的coumn中放了操作按钮，操作按钮通过scope中的某个值通过v-show 判断显示，正常情况下没有任何问题，页面可以进行http请求 ， 但是当npm run build  发布线上环境后发现当前http请求被pending挂起，导致页面卡死

回滚 ····

排除了后端问题和运维问题后发现是当前ui导致的 

当把v-show修改为v-if  打包后页面恢复正常

 和当前问题有相似之处  ：https://www.secn.net/article/1543902.html

当使用v-show判断按钮
![image](https://user-images.githubusercontent.com/39789970/115402491-07e37d80-a21e-11eb-9ae1-cb752b57c59d.png)
当使用v-show之后 线上http请求表现形式，在之后页面会奔溃···
![image](https://user-images.githubusercontent.com/39789970/115402537-129e1280-a21e-11eb-8ae4-0a2295d4e35a.png)
修改为v-if之后 打包 上线后正常，如下
![image](https://user-images.githubusercontent.com/39789970/115402577-1df13e00-a21e-11eb-9781-e295ad4bf273.png)

**Comment by JeremyWuuuuu** [comment]
Could you provide a simple version for us to find out why? It would be hard for us to find the root cause by guessing.
可以提供一个最简单的版本吗，这个可能得看一下，还挺严重的。BTW，我们最近在考虑重构 Table，因为之前的实现搬过来之后发现 Bug 很多。

**Comment by LYao0919** [comment]
![image](https://user-images.githubusercontent.com/39789970/115488339-e53c7d80-a28c-11eb-85cb-90e260ea2acb.png)
![image](https://user-images.githubusercontent.com/39789970/115488441-1452ef00-a28d-11eb-99d9-9b7aa32da2d9.png)

**Comment by JeremyWuuuuu** [comment]
实在不好意思，自定义主题那个是之前 Element v2 版本的，我们现在也正在做，基本都做好了，只需要 PR 合了上线了，稳定版可能还需要点时间，有些 feature 我们也还没有办法那么快给出去，人手有限（大家都有自己的全职工作），我们都是自发的来做这个就那么几个人 非常感谢信任，我们一定加快进度！

**Comment by LYao0919** [comment]
相信且看好你们加油

现在允许组外人员提供bug修复么

**Comment by JeremyWuuuuu** [comment]
> 相信且看好你们加油
> 
> 现在允许组外人员提供bug修复么

非常欢迎，请全力输出。
More than welcome, please do that if you want.

**Comment by justwiner** [comment]
After building, I didn't reproduce this problem. Can you complete the test case based on [https://github.com/justwiner/EP_Issues.git](https://github.com/justwiner/EP_Issues.git)

https://github.com/justwiner/EP_Issues/blob/dd4d01f4c4bdbaae61026214da845db192325497/src/App.vue#L1-L30

**Comment by justwiner** [comment]
okey! There are still some remaining problems due to code migration and the original problems of element-ui, we will try our best to fix them.
