### ISSUE TITLE
[All] 官网总是打不开，影响使用

### ISSUE THREAD

**Issue by LIANGQI0811** [element-plus/element-plus#18755]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.7`
- Browser / OS: `Chrome `
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html)

### Steps to reproduce

直接打开官网

### What is Expected?

1秒内打开官网

### What is actually happening?

卡了5分钟

### Additional comments

_(empty)_

**Comment by stupidream** [comment]
用[国内镜像](https://cn.element-plus.org/zh-CN/)

**Comment by warmthsea** [comment]
可能是由于你使用的网络导致部分js请求错误引起的，你可以尝试以下地址

https://cn.element-plus.org/zh-CN/
https://staging.element-plus.org/zh-CN/
https://element-plus.org/en-US/
