### ISSUE TITLE
[Feature Request] Dialog window

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1876]
Can you make something like this ?
[https://www.telerik.com/kendo-vue-ui/window](https://www.telerik.com/kendo-vue-ui/window)
it would be nice to have in element plus :)

**Comment by JeremyWuuuuu** [comment]
Yeah, we were consider adding APIs that allows Dialog to be draggable and resizable, but that could take some time since we have encountering resourcing shortage right now.

**Comment by Chen-WeiZhen** [comment]
@JeremyWuuuuu 
Questions: 
1. Why choose low-level api of Vue like `createBlock,openBlock,createCommentVNode` to develope this project ? Have you written any blog for this?
2. If I want to master these low-level api of Vue,the most importance that using it in my developmental project, do you have any suggestion ?

For Reason!!
Sorry for asking question here. I'm exploring the source code of Element-plus. I'm confused some time for why not use jsx for render function, but use the inital function of Vue like `createVNode , createCommentVNode,openBlock,createBlock` for this project. 
Ok, It's so greate greate amazing job, knowledgeable, sometimes I think that's so crazy , or sometimes looks messing and confused.

**Comment by Giwayume** [comment]
Some things aren't possible to do or are very inefficient with a template.
