### ISSUE TITLE
[Component] [popover] popover 组件trigger="click"使用v-model:visible后显示了又直接消失了

### ISSUE THREAD

**Issue by zc-tired** [element-plus/element-plus#18766]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.8.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5jb25zdCB2aXNpYmxlID0gcmVmKCExKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXBvcG92ZXIgZWZmZWN0PVwiZGFya1wiIHRyaWdnZXI9XCJjbGlja1wiIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxzcGFuIEBjbGljaz1cInZpc2libGU9ITBcIj7ngrnmiJHllaY8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dWw+XG4gICAgICA8bGk+MTExPC9saT5cbiAgICAgIDxsaT4yMjI8L2xpPlxuICAgICAgPGxpPjMzMzwvbGk+XG4gICAgICA8bGk+NDQ0PC9saT5cbiAgICA8L3VsPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

设置trigger="click"，点击出现了popover马上消失了。。。请问是正常的吗？

### What is Expected?

点击外部区域才消失

### What is actually happening?

点击显示后接着消失了

### Additional comments

_(empty)_

**Comment by Onion-L** [comment]
应该是你的点击事件把visible改成true，然后trigger又改成了false
![image](https://github.com/user-attachments/assets/93d4005c-9a03-49cc-bec8-1dce1e464ec3)

**Comment by zc-tired** [comment]
应该是组件里面的问题吧。。我没有设置为false，而且那个auto-close设置什么数字都没有用
&nbsp;


龘靐齉齾麤龖龗鱻爩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月4日(星期一) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [popover] popover 组件trigger=&quot;click&quot;使用v-model:visible后显示了又直接消失了 (Issue #18766)














 
应该是你的点击事件把visible改成true，然后trigger又改成了false
 image.png (view on web)

**Comment by zc-tired** [comment]
> 应该是你的点击事件把visible改成true，然后trigger又改成了false ![image](https://private-user-images.githubusercontent.com/71209582/382672001-93d4005c-9a03-49cc-bec8-1dce1e464ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDU3NTEsIm5iZiI6MTczMDcwNTQ1MSwicGF0aCI6Ii83MTIwOTU4Mi8zODI2NzIwMDEtOTNkNDAwNWMtOWEwMy00OWNjLWJlYzgtMWRjZTFlNDY0ZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDRhOWRkZmMxZjZhNzJmZTcxNTBiN2U5ZTdjNGRjZjJjZDE3NWEzMGQ2ZGVkZmVkMDRjODQ2NzRmOTAxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._VpsRUeBgTzcqjuOutCnwzjqHaELd9iQP4XGxnPH5ns)

应该是组件里面的问题吧，我没有设置为false，而且那个auto-close设置什么数字都没有用

**Comment by Onion-L** [comment]
> > 应该是你的点击事件把visible改成true，然后trigger又改成了false ![image](https://private-user-images.githubusercontent.com/71209582/382672001-93d4005c-9a03-49cc-bec8-1dce1e464ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDU3NTEsIm5iZiI6MTczMDcwNTQ1MSwicGF0aCI6Ii83MTIwOTU4Mi8zODI2NzIwMDEtOTNkNDAwNWMtOWEwMy00OWNjLWJlYzgtMWRjZTFlNDY0ZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDRhOWRkZmMxZjZhNzJmZTcxNTBiN2U5ZTdjNGRjZjJjZDE3NWEzMGQ2ZGVkZmVkMDRjODQ2NzRmOTAxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._VpsRUeBgTzcqjuOutCnwzjqHaELd9iQP4XGxnPH5ns)
> 
> 应该是组件里面的问题吧，我没有设置为false，而且那个auto-close设置什么数字都没有用

![image](https://github.com/user-attachments/assets/7266df04-9d6d-420a-ab6f-51a4fb469c6f)
把这个click删掉就可以了

**Comment by zc-tired** [comment]
> > > 应该是你的点击事件把visible改成true，然后trigger又改成了false ![image](https://private-user-images.githubusercontent.com/71209582/382672001-93d4005c-9a03-49cc-bec8-1dce1e464ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDU3NTEsIm5iZiI6MTczMDcwNTQ1MSwicGF0aCI6Ii83MTIwOTU4Mi8zODI2NzIwMDEtOTNkNDAwNWMtOWEwMy00OWNjLWJlYzgtMWRjZTFlNDY0ZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDRhOWRkZmMxZjZhNzJmZTcxNTBiN2U5ZTdjNGRjZjJjZDE3NWEzMGQ2ZGVkZmVkMDRjODQ2NzRmOTAxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._VpsRUeBgTzcqjuOutCnwzjqHaELd9iQP4XGxnPH5ns)
> > 
> > 
> > 应该是组件里面的问题吧，我没有设置为false，而且那个auto-close设置什么数字都没有用
> 
> ![image](https://private-user-images.githubusercontent.com/71209582/382673093-7266df04-9d6d-420a-ab6f-51a4fb469c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDYwNDUsIm5iZiI6MTczMDcwNTc0NSwicGF0aCI6Ii83MTIwOTU4Mi8zODI2NzMwOTMtNzI2NmRmMDQtOWQ2ZC00MjBhLWFiNmYtNTFhNGZiNDY5YzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA3MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGUxYzZlNTZiYjJlNDM0ZjU1YWZkNDJhODMzYjk4M2UyZTg4ODBmZjEyZjhkODZiZGQzMWE1OGY2NzhjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FHBuMxmmXURDVvNKbfPauFv5qmpunBNv2O2SXcCRrdc) 把这个click删掉就可以了

好吧，居然是这样的
