### ISSUE TITLE
[All] element-plus关于sass问题

### ISSUE THREAD

**Issue by Verdant-Grassland** [element-plus/element-plus#18779]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/github/Verdant-Grassland/similar-wechat/master?import=true)

### Steps to reproduce

您好，关于这个情况，我运行项目时候有提示：

Deprecation Warning: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.

Recommendation: add `$B: null` at the stylesheet root.

   ╷
59 │   $B: $namespace + $common-separator + $block !global;
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 59:3  b()  
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\icon.scss 24:1           @use 
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\base.scss 3:1            @use 
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\index.scss 1:1           @use 
    src\renderer\src\assets\css\cust-elementplus.scss 3:1
                                                                                          root 
stylesheet

Deprecation Warning: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.

Recommendation: add `$E: null` at the stylesheet root.

   ╷
67 │   $E: $element !global;
   │   ^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 67:3  e()  
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\alert.scss 63:3          @content
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 62:5  b()
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\alert.scss 5:1           @use
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\index.scss 4:1           @use
    src\renderer\src\assets\css\cust-elementplus.scss 3:1                                                                                                                                root stylesheet

ent
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 62:5  b()
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\alert.scss 5:1           @use
    node_modules\.pnpm\element-plus@https+++pkg.pr.new+element-plus+element-plus@f23e4b2_vue@3.5.12_typescript@5.6.3_\node_modules\element-plus\theme-chalk\src\index.scss 4:1           @use
    src\renderer\src\assets\css\cust-elementplus.scss 3:1                                                                                                                                root stylesheet

### What is Expected?

需要解决出现问题

### What is actually happening?

需要解决出现问题

### Additional comments

_(empty)_

**Comment by warmthsea** [comment]
fixed in https://github.com/element-plus/element-plus/pull/18711, can do this install new version:

![screenshots](https://github.com/user-attachments/assets/8ec28109-2391-4e82-85dc-51af50d1835c)
