### ISSUE TITLE
[Docs] el-select-v2组件teleported属性英文文档和中文文档不一致

### ISSUE THREAD

**Issue by grzhan** [element-plus/element-plus#18795]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.7`
- Browser / OS: `Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gY2l0aWVzXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxlbC1idXR0b24gdi1pZj1cIiFpc0FkZGluZ1wiIHRleHQgYmcgc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwib25BZGRPcHRpb25cIj5cbiAgICAgICAgQWRkIGFuIG9wdGlvblxuICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8dGVtcGxhdGUgdi1lbHNlPlxuICAgICAgICA8ZWwtaW5wdXRcbiAgICAgICAgICB2LW1vZGVsPVwib3B0aW9uTmFtZVwiXG4gICAgICAgICAgY2xhc3M9XCJvcHRpb24taW5wdXRcIlxuICAgICAgICAgIHBsYWNlaG9sZGVyPVwiaW5wdXQgb3B0aW9uIG5hbWVcIlxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgIC8+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBzaXplPVwic21hbGxcIiBAY2xpY2s9XCJvbkNvbmZpcm1cIj5cbiAgICAgICAgICBjb25maXJtXG4gICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImNsZWFyXCI+Y2FuY2VsPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBDaGVja2JveFZhbHVlVHlwZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgaXNBZGRpbmcgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZjxDaGVja2JveFZhbHVlVHlwZVtdPihbXSlcbmNvbnN0IG9wdGlvbk5hbWUgPSByZWYoJycpXG5jb25zdCBjaXRpZXMgPSByZWYoW1xuICB7XG4gICAgdmFsdWU6ICdCZWlqaW5nJyxcbiAgICBsYWJlbDogJ0JlaWppbmcnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdTaGFuZ2hhaScsXG4gICAgbGFiZWw6ICdTaGFuZ2hhaScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ05hbmppbmcnLFxuICAgIGxhYmVsOiAnTmFuamluZycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0NoZW5nZHUnLFxuICAgIGxhYmVsOiAnQ2hlbmdkdScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ1NoZW56aGVuJyxcbiAgICBsYWJlbDogJ1NoZW56aGVuJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnR3Vhbmd6aG91JyxcbiAgICBsYWJlbDogJ0d1YW5nemhvdScsXG4gIH0sXG5dKVxuXG5jb25zdCBvbkFkZE9wdGlvbiA9ICgpID0+IHtcbiAgaXNBZGRpbmcudmFsdWUgPSB0cnVlXG59XG5cbmNvbnN0IG9uQ29uZmlybSA9ICgpID0+IHtcbiAgaWYgKG9wdGlvbk5hbWUudmFsdWUpIHtcbiAgICBjaXRpZXMudmFsdWUucHVzaCh7XG4gICAgICBsYWJlbDogb3B0aW9uTmFtZS52YWx1ZSxcbiAgICAgIHZhbHVlOiBvcHRpb25OYW1lLnZhbHVlLFxuICAgIH0pXG4gICAgY2xlYXIoKVxuICB9XG59XG5cbmNvbnN0IGNsZWFyID0gKCkgPT4ge1xuICBvcHRpb25OYW1lLnZhbHVlID0gJydcbiAgaXNBZGRpbmcudmFsdWUgPSBmYWxzZVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Nzc1wiIHNjb3BlZD5cbi5vcHRpb24taW5wdXQge1xuICB3aWR0aDogMTAwJTtcbiAgbWFyZ2luLWJvdHRvbTogOHB4O1xufVxuPC9zdHlsZT5cbiJ9)

### Steps to reproduce

查看文档

### What is Expected?

说明：是否将下拉列表插入至 body 元素

### What is actually happening?

说明：是否将下拉列表元素插入 append-to 指向的元素下

### Additional comments

_(empty)_

**Comment by YiMo1** [comment]
和选择器组件一样，会有添加一个`append-to`属性，预计是在`2.8.8`版本更新此功能。

`teleported`和`append-to`两个属性配合，可以传送至任意节点，前者决定是否开启传送，后者决定传送至哪，若`append-to`不指定值，则默认传送至body下创建的一个`id`为`el-popper-container-[number]`的元素。

由于英文版本的这两个属性的介绍好像是错误的，或者说是并不准确的？所以中文版本也只能错误的翻译。

看后续会不会对英文版做出矫正。
