### ISSUE TITLE
[bug report] the performance of native icon is inconsistent, and the question mark icon is distorted and unsightly

### ISSUE THREAD

**Issue by huangzhongzhong** [element-plus/element-plus#1880]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
全版本

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVe

### Steps to reproduce
官方Demo即可发现不一致，上面的重现链接是随便写的，无法访问。
https://element-plus.org/#/zh-CN/component/icon

### What is Expected?
question问号图标扭曲不美观。
s-fold和s-unfold图标的三角形不一致。

### What is actually happening?
question问号图标重绘。
s-fold和s-unfold图标的三角形统一。

**Comment by huangzhongzhong** [comment]
原先的问号图标，造型扭曲不美观
![image](https://user-images.githubusercontent.com/46183365/115509923-a53bc180-a2b1-11eb-8edf-57d84d308945.png)
现在的问号图标，造型合理
![image](https://user-images.githubusercontent.com/46183365/115509877-90f7c480-a2b1-11eb-8cc7-c8fd81d2a9ab.png)

原先的s-fold和s-unfold图标的三角形不统一
![image](https://user-images.githubusercontent.com/46183365/115510686-9f92ab80-a2b2-11eb-8f23-2e377f1a4e3f.png)
现在的s-fold和s-unfold图标的三角形统一
![image](https://user-images.githubusercontent.com/46183365/115510595-838f0a00-a2b2-11eb-99dd-1b2b17ba7046.png)

附上ttf和woff格式的字体图标文件
[fonts.zip](https://github.com/element-plus/element-plus/files/6348724/fonts.zip)

**Comment by JeremyWuuuuu** [comment]
这个 zip 里是所有的 font 还是单独的 font？（我之所以这样问是因为我们发布font资源需要合并发布）

**Comment by JeremyWuuuuu** [comment]
oh 我看了一下好像是全部都在里面了，我让 @kooriookami 跟一下，把这个替换一下

**Comment by iamkun** [comment]
可以提供一份修改后的 svg 文件吗？

**Comment by kooriookami** [comment]
https://user-images.githubusercontent.com/38392315/115520198-7b3bcc80-a2bc-11eb-9375-fc54a7ac5fb2.mp4

视频中第一组是原来的感叹号和问号，第二组是您修改的。
问号感觉细了、偏下了，问号下面的点也没有和感叹号的保持一致。

**Comment by huangzhongzhong** [comment]
> 可以提供一份修改后的svg文件吗？

请问你是需要修改的对应图标的单个svg文件吗？比如改了三个图标，给三个单独的svg文件

**Comment by huangzhongzhong** [comment]
>  WeChat_20210421161253.mp4 
> 视频中第一组是原来的感叹号和问号，第二组是您修改的。
> 问号感觉细了，偏下了，问号下面的点也没有和感叹号的保持一致。

这个问号确实细节比较多，我也在权衡，我有满意的版本后再重新提交吧哈哈

**Comment by huangzhongzhong** [comment]
我暂时放弃了对问号的调整，把握不好最佳的形态。仅调整了s-unfold，附上字体文件和svg文件，请查阅。有什么问题也可以加微信avx358交流~
[fonts-210422.zip](https://github.com/element-plus/element-plus/files/6357878/fonts-210422.zip)

**Comment by JeremyWuuuuu** [comment]
cc @kooriookami
