### ISSUE TITLE
Can the icon of the [feature request] header pageheader component be changed to customizable?

### ISSUE THREAD

**Issue by chaode0620** [element-plus/element-plus#1881]
### Existing Component
是

### Component Name
PageHeader

### Description
页头 PageHeader 组件的图标能否改成可自定义的？ 目前的图标是一个 左向箭头，组件内写死。没法动态更改图标。这个图标能否改成可以自己动态设定的那种。

**Comment by kooriookami** [comment]
Yes, it's necessary to improve this compoent.
