### ISSUE TITLE
[Component] [tree] 树节点拖拽时，如果目标节点没有子节点，那么源节点就无法被拖到目标节点下作为目标节点的子节点，只能与目标节点平级放

### ISSUE THREAD

**Issue by heyingjie** [element-plus/element-plus#18817]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree.html#%E5%8F%AF%E6%8B%96%E6%8B%BD%E8%8A%82%E7%82%B9)

### Steps to reproduce

将demo中的一个节点拖到第一层节点，然后将另外的节点拖到刚刚那个节点下。

### What is Expected?

第二个拖动的节点可以做为第一个节点的子节点

### What is actually happening?

第二个拖动的节点只能是第一个节点的兄弟节点，不能作为子节点

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
可以提供更详细的信息吗？

**Comment by heyingjie** [comment]
第一步：将demo中Level two 1-1节点拖到Level one 2节点下
![image](https://github.com/user-attachments/assets/ecc41d2a-3e14-4f1a-b461-297044e32306)
拖动后如下：
![image](https://github.com/user-attachments/assets/b8cd5219-9198-4d66-b801-8138605d8079)

第二步：将Level two 1-1节点拖回Level one 1节点下，会发现拖不回去，Level two 1-1节点本应是Level one 1的子节点，现在变成兄弟节点了。
![image](https://github.com/user-attachments/assets/03e48fa7-104e-4d0b-bf32-5258982452b9)

**Comment by Liao-js** [comment]
![image](https://github.com/user-attachments/assets/6a283dfd-a3c8-43c3-a20d-160909e7922a)
我这边是可以的，这样就能拖回去了

**Comment by heyingjie** [comment]
谢谢，明白了，在目标节点没有子节点的时候，如果想把源节点拖到目标节点下，操作逻辑有点不同，需要把源节点拉到目标节点上，而不是拉到目标节点的下方。
下面这种是有子节点的拖拽情况：
![image](https://github.com/user-attachments/assets/18e21472-d81c-4775-81fb-f2b6c28aece0)
下面这种是没有子节点的拖拽情况：
![image](https://github.com/user-attachments/assets/dc435c5c-1655-4d71-8545-67f885cb6070)
