### ISSUE TITLE
[bug report] when I use vite to introduce components on demand, I switch components to multiple languages, and in the vite.config  Resolvestyle in styleimport contains locale, but there is no multi language SCSS file, which leads to failure

### ISSUE THREAD

**Issue by wushijiang13** [element-plus/element-plus#1883]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
mac 10.13.6

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/wushijiang/pen/GRrwJNz

### Steps to reproduce
1.import {ElButton,ElPagination,locale} from 'element-plus';
2.按需引入的代码
libraryName: 'element-plus',
              resolveStyle: (name:any) => {
                  name = name.slice(3);
                      console.log(name);
                      return `element-plus/packages/theme-chalk/src/${name}.scss`;
              }
}
3.得到error
import 'element-plus/packages/theme-chalk/src/button.scss';
  11 |  import 'element-plus/packages/theme-chalk/src/pagination.scss';
  12 |  import 'element-plus/packages/theme-chalk/src/ale.scss';
     |          ^

### What is Expected?
样式检查 不应检查locale。

### What is actually happening?
按需引入中遍历了locale 的声明

**Comment by wushijiang13** [comment]
重现的图片演示步骤
![image](https://user-images.githubusercontent.com/38801556/115543884-7a169980-a2d4-11eb-803b-da0efb04fdf2.png)

![image](https://user-images.githubusercontent.com/38801556/115543862-6ff49b00-a2d4-11eb-8fb4-1671e4326ddc.png)

![image](https://user-images.githubusercontent.com/38801556/115543769-56ebea00-a2d4-11eb-92f1-7b5dc8a1f7b6.png)

**Comment by Zhaocl1997** [comment]
add `esModule: true` and `ensureStyleFile: true` option to `styleImport` options.
![微信截图_20210421191832](https://user-images.githubusercontent.com/52120824/115545441-666c3280-a2d6-11eb-8fe2-75210ae755e1.png)

**Comment by wushijiang13** [comment]
> add `esModule: true` and `ensureStyleFile: true` option to `styleImport` options.
> ![微信截图_20210421191832](https://user-images.githubusercontent.com/52120824/115545441-666c3280-a2d6-11eb-8fe2-75210ae755e1.png)

This operation can ensure no error, but when I output the log, I will still include ale. I think this is abnormal
![image](https://user-images.githubusercontent.com/38801556/115650833-978f4600-a35c-11eb-9972-9b18a2f7fd1a.png)

**Comment by Zhaocl1997** [comment]
`ale.scss` is abnormal. Maybe `alert.scss`? Try to clean `.vite` cache folder in `node_modules` and restart the server again

**Comment by wushijiang13** [comment]
No, I can be sure. I think I cut the string when I introduce the style name. When I comment it out, it will display the full name.

![image](https://user-images.githubusercontent.com/38801556/115813545-f10f7780-a425-11eb-8444-10c937737cfa.png)

And I didn't introduce 'alert'

![image](https://user-images.githubusercontent.com/38801556/115813625-113f3680-a426-11eb-964d-dab2c9c00c39.png)

**Comment by HongqingCao** [comment]
在node_modules    找到element-plus/lib/theme-chalk，添加一个locale.css空文件

**Comment by Otto-J** [comment]
babel-import 遇到相同问题，和导出 locale 有关系。最终我新建了一个空的css文件

```js
config={
customStyleName: (name) => {
      name = name.slice(3);
      console.log(name);
      return name === 'ale'
        ? '@/assets/blank.css'
        : `element-plus/packages/theme-chalk/src/${name}.scss`;
    }
}
```

**Comment by Otto-J** [comment]
我以为是 local 导出的问题，实际上文档提的很清楚，如果使用了自动import，locale应当从 lib 中引入。详见 https://element-plus.gitee.io/#/zh-CN/component/i18n

**Comment by pollux2015** [comment]
请问怎么解决的

**Comment by wushijiang13** [comment]
> 请问怎么解决的

详情见第一个回答

**Comment by kukuyuhai** [comment]
```
 resolveStyle: (name) => {
    if (name !== "locale") {
      name = name.slice(3)
    }
    return `element-plus/packages/theme-chalk/src/${name}.scss`
}
```
我这样解决了
