### ISSUE TITLE
el-input in el-table will lose focus after type

### ISSUE THREAD

**Issue by bazingaedward** [element-plus/element-plus#1884]
```
<el-table 
  class="c-base-attrs"
  :data="modelValue"
>
  <el-table-column label="属性名称">
    <template #default="{row}">
    <el-input 
      v-model="row.key"
      placeholder="name"
      size="small"
    ></el-input>
    </template>
  </el-table-column>
</el-table>
```
``
当在input框中输入一个字符后，自动失去焦点

**Comment by schunlee** [comment]
我也刚好遇到这个问题了，好像element-ui 2.4.7就没这个问题(https://codepen.io/Vine_Yip/pen/aRpwww)
尝试过@blur(keepFocus)
keepFocus(event){
    event.target.focus();
}
好像这样也不起作用

**Comment by LYao0919** [comment]
我也遇到了 ···

**Comment by schunlee** [comment]
> 我也刚好遇到这个问题了，好像element-ui 2.4.7就没这个问题(https://codepen.io/Vine_Yip/pen/aRpwww)
> 尝试过@blur(keepFocus)
> keepFocus(event){
> event.target.focus();
> }
> 好像这样也不起作用

后来发现应该与element ui版本无关。
代码(只是Element Plus基础表格例子中嵌入el-input， 一个使用vue-cli构建，一个则是html引入cdn地址)，在同样的浏览器上运行，发现cdn地址的可以正常连续输入，但是vue-cli构建的输入一个字符则失去焦点导致无法继续输入下个字符。

**Comment by mufenger** [comment]
`
<el-table 
  class="c-base-attrs"
  :data="modelValue"
>
  <el-table-column label="属性名称">
    <template #default="{row}">
    <div class="table-div">
       <input type="text" class="table-input" v-model="row.key">
    </div>
     </template>
  </el-table-column>
</el-table>

<style>
  .table-input {
    height: 28px;
    line-height:28px;
    border: 1px solid;
    -webkit-appearance: none;
    background-color: #FFF;
    background-image: none;
    border-radius: 4px;
    border: 1px solid #DCDFE6;
    box-sizing: border-box;
    color: #606266;
    display: inline-block;
    outline: 0;
    padding: 0 15px;
    transition: border-color .2s cubic-bezier(.645,.045,.355,1);
    width: 100%;
  }
  .table-div {
    font-size: 12px;
    line-height: 28px;
  }
</style>
`
没有好的办法解决，所以换用了input并使用el-input的css样式，css有些冗余

**Comment by mufenger** [comment]
因为没有好的办法解决，所以采用了input及el-input的css样式去实现

**Comment by mufenger** [comment]
same issue,  我使用的是vue3的环境，当时package.json文件中"element-plus": "*",所以我更新了element-plus的版本解决了这个问题。

**Comment by sxzz** [comment]
It seems that this problem has been resolved. If anyone has any questions, please feel free to open a new issue.
