### ISSUE TITLE
[Bug Report] [Bug Report] Build with Vue3/Vite/TS failed

### ISSUE THREAD

**Issue by WalkAlone0325** [element-plus/element-plus#1886]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
window 10

### Vue version
3.0.5

### Reproduction Link
https://github.com/element-plus/element-plus/

### Steps to reproduce
only create vite vue3 ts project,then build, errors

### What is Expected?
i hope build success.

### What is actually happening?
yarn run v1.22.5
$ vue-tsc --noEmit && vite build
node_modules/element-plus/lib/el-carousel/src/main.vue.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts:4:20 - error TS2304: Cannot find name 'Nullable'.

4     readonly data: Nullable<CascaderOption>;
                     ~~~~~~~~

node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts:22:23 - error TS2304: Cannot find name 'Nullable'.

22     constructor(data: Nullable<CascaderOption>, config: CascaderConfig, parent?: Node, root?: boolean);
                         ~~~~~~~~

node_modules/element-plus/lib/el-cascader-panel/src/types.d.ts:50:20 - error TS2304: Cannot find name 'Nullable'.

50     expandingNode: Nullable<CascaderNode>;
                      ~~~~~~~~

node_modules/element-plus/lib/el-form/src/token.d.ts:28:11 - error TS2304: Cannot find name 'ComponentSize'.

28     size: ComponentSize;
             ~~~~~~~~~~~~~

node_modules/element-plus/lib/el-popper/src/use-popper/defaults.d.ts:7:34 - error TS2304: Cannot find name 'Nullable'.

7 export declare type RefElement = Nullable<HTMLElement>;
                                   ~~~~~~~~

node_modules/element-plus/lib/el-slider/src/slider.type.d.ts:23:17 - error TS2304: Cannot find name 'Nullable'.

23     firstValue: Nullable<number>;
                   ~~~~~~~~

node_modules/element-plus/lib/el-slider/src/slider.type.d.ts:24:18 - error TS2304: Cannot find name 'Nullable'.

24     secondValue: Nullable<number>;
                    ~~~~~~~~

node_modules/element-plus/lib/el-slider/src/slider.type.d.ts:25:15 - error TS2304: Cannot find name 'Nullable'.

25     oldValue: Nullable<number>;
                 ~~~~~~~~

node_modules/element-plus/lib/el-slider/src/slider.type.d.ts:69:48 - error TS2304: Cannot find name 'Nullable'.

69     [s in 'firstButton' | 'secondButton']: Ref<Nullable<ISliderButton>>;
                                                  ~~~~~~~~

node_modules/element-plus/lib/el-slider/src/slider.type.d.ts:89:18 - error TS2304: Cannot find name 'Nullable'.

89     tooltip: Ref<Nullable<HTMLElement>>;
                    ~~~~~~~~

node_modules/element-plus/lib/el-time-picker/src/common/props.d.ts:35:24 - error TS2304: Cannot find name 'ComponentSize'.

35         type: PropType<ComponentSize>;
                          ~~~~~~~~~~~~~

node_modules/element-plus/lib/el-tree/src/model/node.d.ts:28:24 - error TS2304: Cannot find name 'Nullable'.

28     get nextSibling(): Nullable<Node>;
                          ~~~~~~~~

node_modules/element-plus/lib/el-tree/src/model/node.d.ts:29:28 - error TS2304: Cannot find name 'Nullable'.

29     get previousSibling(): Nullable<Node>;
                              ~~~~~~~~

node_modules/element-plus/lib/utils/config.d.ts:2:11 - error TS2304: Cannot find name 'ComponentSize'. 

2     size: ComponentSize;

**Comment by WalkAlone0325** [comment]
only create `vite+vue3+ts` project,then build, errors

**Comment by WalkAlone0325** [comment]
1. only use `vitejs` create `vite+vue3+ts` project
2. in `main.ts`,add `import ElementPlus from 'element-plus';import 'element-plus/lib/theme-chalk/index.css'`
3. use `yarn build`
4. build error.

i think `vue-tsc --noEmit` have problems,then use `vite build`,it's OK.

**Comment by Zhaocl1997** [comment]
try `vue-tsc --noEmit --skipLibCheck`

**Comment by WalkAlone0325** [comment]
> try `vue-tsc --noEmit --skipLibCheck`

You mean the same as I do, use `vite build` no `tsc`.

**Comment by cool-delete** [comment]
I have the same problem
see [issue](https://github.com/vitejs/vite/issues/3122#issue-866725728)

**Comment by atdow** [comment]
> > try `vue-tsc --noEmit --skipLibCheck`
> 
> You mean the same as I do, use `vite build` no `tsc`.

thinks,this way can resolve the buildinng of types error

**Comment by atdow** [comment]
> 1. only use `vitejs` create `vite+vue3+ts` project
> 2. in `main.ts`,add `import ElementPlus from 'element-plus';import 'element-plus/lib/theme-chalk/index.css'`
> 3. use `yarn build`
> 4. build error.
> 
> i think `vue-tsc --noEmit` have problems,then use `vite build`,it's OK.

thinks,this way can solve the building of types error!

**Comment by Zhaocl1997** [comment]
The error you got is from `element-plus` module, use `--skipLibCheck` can skip type check from modules in `node_modules`. As long as your own code doesn't have any type error, `vue-tsc --noEmit --skipLibCheck && vite build` would pass.

**Comment by LDHgiser** [comment]
use  "vue-tsc --noEmit --skipLibCheck && vite build"  or  "vite build",
But hope can the element-plus can solve the problem。
Thanks

**Comment by LBJDJW** [comment]
vue-tsc : 无法将“vue-tsc”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

**Comment by Minori-ty** [comment]
靠，这个bug到现在还没修复吗。。。
