### ISSUE TITLE
[Component] [date-picker] 日期选择器组件当type不为date的时候，默认插槽不生效

### ISSUE THREAD

**Issue by Magisk2** [element-plus/element-plus#18886]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.7.4`
- Browser / OS: `Chrome 86.2.4240.75 / window 10 和 130.0.6723.116/ linux mint 21.3`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/Magisk2/elementDatePickerIssue)

### Steps to reproduce

1. 点击不同类型的日期组件
2. 查看弹框内容

### What is Expected?

当type=“month”或type=“year”时候。下面框中内容可以自定义内容

### What is actually happening?

下拉内容没有被改变。显示内容和默认的一样

### Additional comments

当前只试了type="date",month,year这几种。其他的没试，不确定有没有问题
![code](https://github.com/user-attachments/assets/57d56a49-cc63-45e6-831b-2243f7a57b83)
![day](https://github.com/user-attachments/assets/15f7990a-4239-4e98-89e2-449b2a35c001)
![month](https://github.com/user-attachments/assets/f002c692-072d-47d5-91bd-45d3534925c7)
![year](https://github.com/user-attachments/assets/78b832a1-2c32-4e75-9bba-892a89de85cb)

**Comment by thinkasany** [comment]
版本需要升级啦，你看的demo是比较新的

![image](https://github.com/user-attachments/assets/0a1829d1-5475-430b-916d-d485bef91cb9)

![image](https://github.com/user-attachments/assets/5e75a0ff-a8dd-4d47-a8a6-6c308d9dc125)

![image](https://github.com/user-attachments/assets/11b7747c-3f0d-47b7-b209-8f5d8563f4aa)

**Comment by btea** [comment]
2.8.0 已经修复了 https://github.com/element-plus/element-plus/pull/17748

**Comment by Magisk2** [comment]
> 版本需要升级啦，你看的demo是比较新的
> 
> ![image](https://private-user-images.githubusercontent.com/117748716/385274372-0a1829d1-5475-430b-916d-d485bef91cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjA4NjksIm5iZiI6MTczMTQ2MDU2OSwicGF0aCI6Ii8xMTc3NDg3MTYvMzg1Mjc0MzcyLTBhMTgyOWQxLTU0NzUtNDMwYi05MTZkLWQ0ODViZWY5MWNiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMTE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Y4NjUyYWYyYTk1MGIyMDg4NmY5NTUwMmU0MjczODNmMWM3ODlhYmRlYTQxODdjYzVkZWExN2VkOTJjMWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s7Ssn3kzh7KhTEGm3Ff6h99Wgm6L95NQvSgSxeeK0kQ)
> 
> ![image](https://private-user-images.githubusercontent.com/117748716/385274139-5e75a0ff-a8dd-4d47-a8a6-6c308d9dc125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjA4NjksIm5iZiI6MTczMTQ2MDU2OSwicGF0aCI6Ii8xMTc3NDg3MTYvMzg1Mjc0MTM5LTVlNzVhMGZmLWE4ZGQtNGQ0Ny1hOGE2LTZjMzA4ZDlkYzEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMTE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjc3NmEzOWE0NTI2MjMxM2NiOWY5ZWRkMDM2MjQ2ZGYxNDcxODk1Y2QxNjM4MzZkNjY0NmY1Y2RiNGIzNTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1RMybYAlYxc-pP9uprAMrJSCCncZt7cVPiKvk-jW6zg)
> 
> ![image](https://private-user-images.githubusercontent.com/117748716/385274198-11b7747c-3f0d-47b7-b209-8f5d8563f4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjA4NjksIm5iZiI6MTczMTQ2MDU2OSwicGF0aCI6Ii8xMTc3NDg3MTYvMzg1Mjc0MTk4LTExYjc3NDdjLTNmMGQtNDdiNy1iMjA5LThmNWQ4NTYzZjRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMTE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTc4MDUxOTM1M2NlZjFiODM2ZDcyMTgxMDlmY2VmZjVhOTA2Njc0MDgwOGFmOTM4NGY0YTg5OGE5YzBhYzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q9djTurHSGfouJudqqsgjhSBj0-UIy37tXGQDOReu8k)

好的，感谢感谢，我看文档没有标注哪个版本可用，我以为是跟type=“date”一起出来的功能

**Comment by Magisk2** [comment]
> 2.8.0 已经修复了 #17748

好的，谢谢
