### ISSUE TITLE
 [Bug Report] <el-time-select> 设置了 :editable="false" 后，组件会自动变为 disabled 状态

### ISSUE THREAD

**Issue by Dreamer365** [element-plus/element-plus#1892]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
windows / chrome 90 

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/Dreamer365/pen/QWdzOXO

### Steps to reproduce
```
<el-time-select`
    v-model="value"
    start='00:30'
    step='00:15'
    end='18:30'
    :editable="false"
    placeholder="选择时间"
></el-time-select>
```

### What is Expected?
<el-time-select> 设置  :editable="false"  后仍可正常选择时间。

### What is actually happening?
<el-time-select> 设置  :editable="false"  导致 <el-time-select> 组件变为  disabled 状态，从而无法操作。

**Comment by wechatdeveloper** [comment]
遇到相同问题；想通过 editable="false" ，解决调出移动端键盘的问题，结果被禁用了
