### ISSUE TITLE
[Component] [date-picker] 日期选择面板默认日期无效

### ISSUE THREAD

**Issue by xing403** [element-plus/element-plus#18925]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.8.8`
- Browser / OS: `windows 11`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/date-picker.html#default-value)

### Steps to reproduce

docs 中对于默认日期选择是无效的 https://element-plus.org/en-US/component/date-picker.html#default-value

### What is Expected?

对日期的选择初始化时填充日期默认值

### What is actually happening?

实际未选中

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
default-value 是指选择器打开时默认显示的时间，并不会填充默认值

**Comment by Yorlg** [comment]
或者你通过生命周期的时候给el-date-picker赋值也行

**Comment by xing403** [comment]
> default-value 是指选择器打开时默认显示的时间，并不会填充默认值

哦哦，原来是这样，还以为是给默认选中的值
