### ISSUE TITLE
[TypeScript] [notification] el-notification use app context inheritance cause ts(2554)

### ISSUE THREAD

**Issue by tyuterry** [element-plus/element-plus#18941]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.8.8`
- Browser / OS: `Chrome/130.0.6723.117  macOS 15.1`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cInRlc3RGblwiPiBhcHAtY29udGV4dC1pbmhlcml0YW5jIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGggfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE5vdGlmaWNhdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgeyBhcHBDb250ZXh0IH0gPSBnZXRDdXJyZW50SW5zdGFuY2UoKSFcblxuLy8gSURFIGVycm9yIHRzKDI1NTQpIHdoZW4gdXNlIGFwcENvbnRleHRcblxuY29uc3QgdGVzdEZuID0gKCkgPT4ge1xuICBFbE5vdGlmaWNhdGlvbih7XG4gICAgdGl0bGU6ICdQcm9tcHQnLFxuICAgIG1lc3NhZ2U6ICdUaGlzIGlzIGEgbWVzc2FnZSB0aGF0IGRvZXMgbm90IGF1dG9tYXRpY2FsbHkgY2xvc2UnLFxuICAgIGR1cmF0aW9uOiAwLFxuICB9LGFwcENvbnRleHQpXG59XG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<template>
  <el-button plain @click="testFn"> app-context-inheritanc </el-button>
</template>

<script lang="ts" setup>
import { h } from 'vue'
import { getCurrentInstance } from 'vue'
import { ElNotification } from 'element-plus'

const { appContext } = getCurrentInstance()!

// IDE error ts(2554) when use appContext

const testFn = () => {
  ElNotification({
    title: 'Prompt',
    message: 'This is a message that does not automatically close',
    duration: 0,
  },appContext)
}
</script>
```

### What is Expected?

no error

### What is actually happening?

IDE error ts(2554) when use appContext

### Additional comments

Type NotifyFn and NotifyTypedFn missing attribute appContext
https://github.com/element-plus/element-plus/blob/2a1fe4d6eeb6c080b08ed4b17649a7fe3d40e1f4/packages/components/notification/src/notification.ts#L135-L142

It should be more like el-message Type MessageFn and MessageTypedFn
https://github.com/element-plus/element-plus/blob/2a1fe4d6eeb6c080b08ed4b17649a7fe3d40e1f4/packages/components/message/src/message.ts#L190-L198

doc: https://element-plus.org/en-US/component/notification.html#app-context-inheritance-2-0-4

**Comment by YiMo1** [comment]
@DDDDD12138 

你认为怎么样？

What do you think?

**Comment by DDDDD12138** [comment]
Fix in #18558, waiting for the next version.

**Comment by DDDDD12138** [comment]
@YiMo1 哦哦，才看明白，好像是少了这个类型，[官网](https://element-plus.org/zh-CN/component/notification.html#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%B8%8B%E6%96%87%E7%BB%A7%E6%89%BF-2-0-4)是有这个用法的

**Comment by YiMo1** [comment]
> @YiMo1 哦哦，才看明白，好像是少了这个类型，[官网](https://element-plus.org/zh-CN/component/notification.html#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%B8%8B%E6%96%87%E7%BB%A7%E6%89%BF-2-0-4)是有这个用法的

是的，所以从一开始类型声明就是错误的，但由于调用者几乎很少传第二个参数（至少我在实际中没传过），所以一直没人提出这个问题。我已经新建分支开始修复此问题了。晚上或者明天提交PR。

Yes, so the type declaration was incorrect from the beginning, but since the caller rarely passes the second parameter (at least I haven't passed it in practice), no one has raised this issue. I have created a new branch to fix this issue. Submit PR tonight or tomorrow.
