### ISSUE TITLE
[Feature Request] Acces to input suffix slot in select

### ISSUE THREAD

**Issue by jordan-boyer** [element-plus/element-plus#1894]
### Existing Component
Yes

### Component Name
Select

### Description
First thank you for your work on element for vue 3 =) 

At we work we don't use icon font to deal with icon and we would like to change icon for the select component. 

But since we don't have access to the suffix slot of the input it's not possible for us to change it to our own svg. 

Is there plan to have access to this slot on this component ?

**Comment by kooriookami** [comment]
Sorry, we may not have a plan.
