### ISSUE TITLE
 2.8.8版本无法在浏览器中调试组件源码

### ISSUE THREAD

**Issue by 2840365628** [element-plus/element-plus#18967]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.3`
- Element Plus Version: `2.8.8`
- Browser / OS: `131.0.6778.86`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

在浏览器中对源码进行断点，断点无法触发 或者 触发了但是断点位置错误, 尝试console.log 提示行数存在偏差

### What is Expected?

正常调试

### What is actually happening?

2.8.8无法在浏览器断点调试，2.8.7可以

### Additional comments

_(empty)_

![QQ_1732166867557](https://github.com/user-attachments/assets/d0ef3f79-b456-4f3d-9cbc-c5576d30f437)
比如此时应该去触发onOptionCreate ，但是断点没有生效

**Comment by btea** [comment]
我试了一下，把下面这一行注释似乎就正常了。
https://github.com/element-plus/element-plus/blob/9bf729fbeb19d51b6095b5ba0583fa14ab10e6f5/play/vite.config.mts#L77

**Comment by btea** [comment]
vite应该默认就支持打包调试，应该是这个插件和vite相互干扰了导致定位不准。

**Comment by 2840365628** [comment]
> vite应该默认就支持打包调试，应该是这个插件和vite相互干扰了导致定位不准。

明白了 感谢佬
