### ISSUE TITLE
[Bug Report] select groupoption label默认值横线失效

### ISSUE THREAD

**Issue by 24078177** [element-plus/element-plus#18997]
### Element Plus version
2.7.4

### OS/Browsers version
131.0.2903.51

### Vue version
3.5.12

### Reproduction Link
https://codepen.io/xiongxing/pen/oNKKMqZ

### Steps to reproduce
select group option 默认label是横线失效

### What is Expected?
預期label默認為橫線

### What is actually happening?
沒有默認值

**Comment by 24078177** [comment]
我该如何实现以前不写label他会自动出现一条横线呢

**Comment by YiMo1** [comment]
我初步看了下，好像在 `2.7.4` 版本后就没有横线了。

I took a preliminary look and it seems that there are no horizontal lines after version `2.7.4`.

**Comment by 24078177** [comment]
那之后的版本都需要自定义了吗

**Comment by YiMo1** [comment]
> 那之后的版本都需要自定义了吗

抱歉，这个问题我并没有答案，也许你应该去问这个PR的作者。

Sorry, I don't have an answer to this question. Perhaps you should ask the author of this PR.

**Comment by 24078177** [comment]
好的，非常感谢
