### ISSUE TITLE
[Style] [table] 使用csdn的引入的方式el-table显示bug

### ISSUE THREAD

**Issue by zhao1217** [element-plus/element-plus#19009]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.8.8`
- Browser / OS: `谷歌`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/guide/installation.html)

### Steps to reproduce
https://element-plus.org/zh-CN/guide/installation.html

示例代码换成el-table,其他不变

### What is Expected?

能够正常显示

### What is actually happening?

表头分成三行显示，数据只显示第一列

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/fc549e1b-c998-44a4-a8bd-124e3c94fbb4)
![image](https://github.com/user-attachments/assets/91cd6d77-d01a-4b35-85ad-188ef7b80df6)

**Comment by warmthsea** [comment]
Due to the limitations of native HTML parsing behavior, single-closed tags may cause some exceptions, so please use double-closed tags, [reference](https://vuejs.org/guide/essentials/component-basics.html#in-dom-template-parsing-caveats)

```vue
<!-- examples -->
<el-table>
  <el-table-column></el-table-column>
  <el-table-column></el-table-column>
</el-table>
```
