### ISSUE TITLE
[Component] [All] Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

### ISSUE THREAD

**Issue by newives** [element-plus/element-plus#19049]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.8.8`
- Browser / OS: `谷歌最新版`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixvbk1vdW50ZWQsb25CZWZvcmVVbm1vdW50LCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGlzU2hvdyA9IHJlZih0cnVlKVxuY29uc3QgaGFuZGxlQ29tbWFuZCA9IChzOiBzdHJpbmcpID0+IHtcbiAgY29uc29sZS5sb2cocyk7XG59XG5vbk1vdW50ZWQoKCkgPT4ge1xuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcigncmVzaXplJywgd2F0Y2hXaW5kb3dTaXplKTtcbiAgd2F0Y2hXaW5kb3dTaXplKClcbn0pXG5cbmNvbnN0IHdhdGNoV2luZG93U2l6ZSA9ICgpID0+IHtcbiAgY29uc3Qgd2lkdGggPSBkb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xpZW50V2lkdGg7XG4gIC8vIGNvbnNvbGUubG9nKHdpZHRoKTtcbiAgaWYgKHdpZHRoIDwgMTIwMCkge1xuICAgIGlzU2hvdy52YWx1ZSA9IGZhbHNlXG4gIH0gZWxzZSB7XG4gICAgaXNTaG93LnZhbHVlID0gdHJ1ZVxuICB9XG59XG5vbkJlZm9yZVVubW91bnQoKCkgPT4ge1xuICB3aW5kb3cucmVtb3ZlRXZlbnRMaXN0ZW5lcigncmVzaXplJywgd2F0Y2hXaW5kb3dTaXplKTtcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1kcm9wZG93biB2LWlmPVwiIWlzU2hvd1wiIEBjb21tYW5kPVwiaGFuZGxlQ29tbWFuZFwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+XG4gICAgICAgIOiPnOWNlVxuICAgICAgPC9zcGFuPlxuICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gY29tbWFuZD1cIi9ob21lXCI+6aaW6aG1PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGNvbW1hbmQ9XCIvYWJvdXRcIj7lhbPkuo7miJHku6w8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gY29tbWFuZD1cIi9jb250YWN0XCI+6IGU57O75oiR5LusPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtZHJvcGRvd24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy40L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy40L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy40LjIxL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjQuMjEvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNy40L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi43LjQvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

跟这个一样的复现 https://github.com/element-plus/element-plus/issues/17720#issue-2439068041

### What is Expected?

不报错

### What is actually happening?

报错

### Additional comments

ant-design也有类似问题不过修复了：https://github.com/react-component/dialog/pull/449 和 https://github.com/ant-design/ant-design/issues/50170

ant-design-vue也有类似问题：https://github.com/vueComponent/ant-design-vue/issues/7749

naive-ui也有类似问题：https://github.com/tusen-ai/naive-ui/issues/6436

element-ui也有类似问题：https://github.com/ElemeFE/element/issues/22936#issue-2437547008

**Comment by Louis-CSI** [comment]
I have the same question when I use filter of table or click the button in the popover.

**Comment by lyric-zemin** [comment]
![image](https://github.com/user-attachments/assets/54a9d8b0-8863-4f68-8ce3-f6f5e044ac2b)
同样的问题

**Comment by tolking** [comment]
Is there an demo that can be stably reproduced?

It seems that the focus is still inside the popup after it is closed.

It may be caused by the use of `setTimeout` in the `onFocusOut` function of `ElFocusRap`

Alternatively, it may be necessary to replace `aria-hidden` with `inert`

**Comment by newives** [comment]
不容易复现 但肯定是有这个bug
用inert有bug（https://github.com/tusen-ai/naive-ui/pull/6569） 
ant-design的处理方式是直接删了aria-hidden

**Comment by tolking** [comment]
`inert` 也需要动态改变值。只是 inert 中的焦点会转到 body 上。

`aria-hidden` 的用处应该是防止在弹窗关闭时弹窗内部节点被聚焦。删除可能会影响 a11y 的功能

**Comment by likaixuan** [comment]
在tabs中也存在这个问题，如果在一个tab-pane中点击按钮通过改变当前name跳转到另一个tab-pane就可以复现

**Comment by MrKleene** [comment]
官网中el-dropdown组件中点击任意一个示例都是百分比复现, 地址: https://element-plus.org/zh-CN/component/dropdown.html

El in website - click on any one of sample in the dropdown can components are percentage emersion, address: https://element-plus.org/zh-CN/component/dropdown.html

**Comment by rsacode** [comment]
请问这个最终怎么解决的呢 2.9.1 win11 edge 131.0.2903.112也是出现dropdown menu的问题
li元素被聚焦

**Comment by Louis-CSI** [comment]
> I have the same question when I use filters of table or click the button in the popover.

Version 2.9.1 still has this problem

**Comment by tolking** [comment]
下个版本修复

**Comment by badspider7** [comment]
el-popover组件调用hide也会出现这个问题

**Comment by maxueli** [comment]
el-menu collapse属性为true，且有子级菜单，点击子级菜单就会复现这个错误
