### ISSUE TITLE
[Bug Report] Remove comments from production build

### ISSUE THREAD

**Issue by bbosiljcic** [element-plus/element-plus#1907]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
Windows 10 / Chrome 89

### Vue version
3.0.11

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/input/src/index.vue#L22

### Steps to reproduce
Build project, the comments are still DOM

### What is Expected?
No comments in production build

### What is actually happening?
Comments in production build

**Comment by pifako** [comment]
Yes, i need too
