### ISSUE TITLE
[Component] [notification] Notification notification, uses HTML fragments as body content, does not render HTML（Notification 通知，使用 HTML 片段作为正文内容，不渲染 HTML ）

### ISSUE THREAD

**Issue by jackloves111** [element-plus/element-plus#19083]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/notification.html)

### Steps to reproduce

```
<template>
  <el-button plain @click="open"> Use HTML String </el-button>
</template>

<script lang="ts" setup>
import { ElNotification } from 'element-plus'

const open = () => {
  ElNotification({
    title: 'HTML String',
    dangerouslyUseHTMLString: true,
    message: '<strong>This is <i>HTML</i> string</strong>',
  })
}
</script>
```

### What is Expected?

<strong>This is <i>HTML</i> string</strong>

### What is actually happening?

```
<strong>This is <i>HTML</i> string</strong>
```
![image](https://github.com/user-attachments/assets/a7ba74cc-d511-41e9-9361-a004176d1dbf)

### Additional comments

Hope this can be fixed

Notification notification, uses HTML fragments as body content, does not render HTML

**Comment by jackloves111** [comment]
![image](https://github.com/user-attachments/assets/46de3db3-87f3-4647-9bbb-377cc4d3fea9)
![image](https://github.com/user-attachments/assets/a7ba74cc-d511-41e9-9361-a004176d1dbf)
I also discovered that after upgrading to version 2.9.0, the notification no longer renders HTML.


**Hope this can be fixed**

**Comment by jackloves111** [comment]
Everything was fine in the previous version 2.8.8

**Comment by Dsaquel** [comment]
duplicates #19067
it will be fixed
