### ISSUE TITLE
[Component] [pagination] about el-pagination  @size-change="handleSizeChange" problem

### ISSUE THREAD

**Issue by huangwenboha563** [element-plus/element-plus#19097]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `chrome 100+ windows11`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcbiAgPGhyIGNsYXNzPVwibXktNFwiIC8+XG5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0ZXN0XCI+5rWL6K+VPC9lbC1idXR0b24+XG5cbiAgPGRpdiBjbGFzcz1cImRlbW8tcGFnaW5hdGlvbi1ibG9ja1wiPlxuICAgIDxkaXYgY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+QWxsIGNvbWJpbmVkPC9kaXY+XG4gICAgPGVsLXBhZ2luYXRpb25cbiAgICAgIHYtbW9kZWw6Y3VycmVudC1wYWdlPVwiY3VycmVudFBhZ2VcIlxuICAgICAgdi1tb2RlbDpwYWdlLXNpemU9XCJwYWdlU2l6ZVwiXG4gICAgICA6cGFnZS1zaXplcz1cIlsxMCwgMTUsIDIwLCAzMF1cIlxuICAgICAgbGF5b3V0PVwidG90YWwsIHNpemVzLCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyXCJcbiAgICAgIDp0b3RhbD1cInRvdGFsXCJcbiAgICAgIEBzaXplLWNoYW5nZT1cImhhbmRsZVNpemVDaGFuZ2VcIlxuICAgICAgQGN1cnJlbnQtY2hhbmdlPVwiaGFuZGxlQ3VycmVudENoYW5nZVwiXG4gICAgLz5cbiAgPC9kaXY+XG4gIFxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IENvbXBvbmVudFNpemUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG4vLyDlvZPliY3nrKzlh6DpobVcbmNvbnN0IGN1cnJlbnRQYWdlID0gcmVmKDEpXG5jb25zdCB0b3RhbCA9IHJlZigxMDApXG4vLyDliJ3lp4vljJbmr4/pobXlpJrlsJHmnaFcbmNvbnN0IHBhZ2VTaXplID0gcmVmKDEwKVxuLy8g5q+P6aG15aSa5bCR5p2h5Y+R55Sf5Y+Y5YyWXG5jb25zdCBoYW5kbGVTaXplQ2hhbmdlID0gKHZhbDogbnVtYmVyKSA9PiB7XG4gIGNvbnNvbGUubG9nKGAke3ZhbH0gaXRlbXMgcGVyIHBhZ2VgKVxufVxuLy8g54K55Ye756ys5Yeg6aG1XG5jb25zdCBoYW5kbGVDdXJyZW50Q2hhbmdlID0gKHZhbDogbnVtYmVyKSA9PiB7XG4gIGFsZXJ0KCfmiafooYzkuoYnKVxuICBjb25zb2xlLmxvZyhgY3VycmVudCBwYWdlOiAke3ZhbH1gKVxufVxuLy8g5rWL6K+V5pa55rOVXG5mdW5jdGlvbiB0ZXN0KCkge1xuICAgIHRvdGFsLnZhbHVlID0gOVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1wYWdpbmF0aW9uLWJsb2NrICsgLmRlbW8tcGFnaW5hdGlvbi1ibG9jayB7XG4gIG1hcmdpbi10b3A6IDEwcHg7XG59XG4uZGVtby1wYWdpbmF0aW9uLWJsb2NrIC5kZW1vbnN0cmF0aW9uIHtcbiAgbWFyZ2luLWJvdHRvbTogMTZweDtcbn1cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 点击第二页 第三页 都会alert（‘执行了’）
2. 点击测试按钮，调用测试方法，为什么也会alert（‘执行了’）
真实项目比较复杂，用playground做了最小化复现

### What is Expected?

点击测试方法，不调用handleCurrentChange 
handleCurrentChange就是纯粹的的页码发生变化时去调用

### What is actually happening?

当我通过某个按钮，去改变查询条件，total发生变化时候，handleCurrentChange会执行，handleCurrentChange方法里面有调用接口的动作，导致接口调用两次

### Additional comments

_(empty)_

**Comment by xionkq** [comment]
在这个示例中，我认为是调用 `test` 修改总条数时，导致页码被改变，因此触发了 `handleCurrentChange`

用例1：直接点击测试按钮，由于 `currentPage` 仍然是第一页，未发生改变，因此不会触发 `alert('执行了')`
![demo3](https://github.com/user-attachments/assets/59a45f0d-f382-4ac5-89fa-354eef292441)

用例2：将 `currentPage` 切换到第二页，再次点击测试按钮，`currentPage` 被设置为第一页，页面被改变，触发 `alert('执行了')`
![demo4](https://github.com/user-attachments/assets/bcc99194-6deb-4e3a-b019-87484d52ce50)

**Comment by YiMo1** [comment]
我认为这个行为符合预期，因为 `current-page` 确实改变了，即使是因为 `total` 变化导致从新计算最大页码数而导致的改变。

**Comment by btea** [comment]
我意见和 @xionkq @YiMo1 一致，@xionkq 给出了详细的说明。

你能详细说明一下你具体的场景吗？

**Comment by toesbieya** [comment]
这种问题比较常见了，就是当前查询条件下的最大页数小于已选页数，所以自动改了`current-page`，解决方案一般都是写个通用列表查询，存两份查询条件，点查询按钮用最新的条件，点分页用旧的条件

**Comment by huangwenboha563** [comment]
> 在这个示例中，我认为是调用 `test` 修改总条数时，导致页码被改变，因此触发了 `handleCurrentChange`
> 
> 用例1：直接点击测试按钮，由于 `currentPage` 仍然是第一页，未发生改变，因此不会触发 `alert('执行了')` ![demo3](https://private-user-images.githubusercontent.com/65892539/391879140-59a45f0d-f382-4ac5-89fa-354eef292441.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkxNDAtNTlhNDVmMGQtZjM4Mi00YWM1LTg5ZmEtMzU0ZWVmMjkyNDQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjQ0MjhiNmI2MTQzMWVlY2FmM2E2NDI4MjQzNGExZjJhZDhlMGRiZTc2ZWZkMjQ3OTQzYmNkMzlhOGYyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nxhd9oiwPaQK-zoeIgVSPag1obrmkTwfyToSAB-nLIM) [ ![demo3](https://private-user-images.githubusercontent.com/65892539/391879140-59a45f0d-f382-4ac5-89fa-354eef292441.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkxNDAtNTlhNDVmMGQtZjM4Mi00YWM1LTg5ZmEtMzU0ZWVmMjkyNDQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjQ0MjhiNmI2MTQzMWVlY2FmM2E2NDI4MjQzNGExZjJhZDhlMGRiZTc2ZWZkMjQ3OTQzYmNkMzlhOGYyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nxhd9oiwPaQK-zoeIgVSPag1obrmkTwfyToSAB-nLIM) ](https://private-user-images.githubusercontent.com/65892539/391879140-59a45f0d-f382-4ac5-89fa-354eef292441.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkxNDAtNTlhNDVmMGQtZjM4Mi00YWM1LTg5ZmEtMzU0ZWVmMjkyNDQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjQ0MjhiNmI2MTQzMWVlY2FmM2E2NDI4MjQzNGExZjJhZDhlMGRiZTc2ZWZkMjQ3OTQzYmNkMzlhOGYyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nxhd9oiwPaQK-zoeIgVSPag1obrmkTwfyToSAB-nLIM) [ ](https://private-user-images.githubusercontent.com/65892539/391879140-59a45f0d-f382-4ac5-89fa-354eef292441.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkxNDAtNTlhNDVmMGQtZjM4Mi00YWM1LTg5ZmEtMzU0ZWVmMjkyNDQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjQ0MjhiNmI2MTQzMWVlY2FmM2E2NDI4MjQzNGExZjJhZDhlMGRiZTc2ZWZkMjQ3OTQzYmNkMzlhOGYyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nxhd9oiwPaQK-zoeIgVSPag1obrmkTwfyToSAB-nLIM)
> 
> 用例2：将 `currentPage` 切换到第二页，再次点击测试按钮，`currentPage` 被设置为第一页，页码被改变，触发 `alert('执行了')` ![demo4](https://private-user-images.githubusercontent.com/65892539/391879262-bcc99194-6deb-4e3a-b019-87484d52ce50.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkyNjItYmNjOTkxOTQtNmRlYi00ZTNhLWIwMTktODc0ODRkNTJjZTUwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDI2YzZiNTMxNjdlZDU0MWY3ZDY4NTZlZWQ5YmY1YTFkNGQxOGY3ZWI1NTgyNDI5YjE0YzkwZDI2ZWM2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._f2Wh1vHHokPPImSu9SFTjE_1lZzKDj-smbcFV4kp-4) [ ![demo4](https://private-user-images.githubusercontent.com/65892539/391879262-bcc99194-6deb-4e3a-b019-87484d52ce50.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkyNjItYmNjOTkxOTQtNmRlYi00ZTNhLWIwMTktODc0ODRkNTJjZTUwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDI2YzZiNTMxNjdlZDU0MWY3ZDY4NTZlZWQ5YmY1YTFkNGQxOGY3ZWI1NTgyNDI5YjE0YzkwZDI2ZWM2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._f2Wh1vHHokPPImSu9SFTjE_1lZzKDj-smbcFV4kp-4) ](https://private-user-images.githubusercontent.com/65892539/391879262-bcc99194-6deb-4e3a-b019-87484d52ce50.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkyNjItYmNjOTkxOTQtNmRlYi00ZTNhLWIwMTktODc0ODRkNTJjZTUwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDI2YzZiNTMxNjdlZDU0MWY3ZDY4NTZlZWQ5YmY1YTFkNGQxOGY3ZWI1NTgyNDI5YjE0YzkwZDI2ZWM2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._f2Wh1vHHokPPImSu9SFTjE_1lZzKDj-smbcFV4kp-4) [ ](https://private-user-images.githubusercontent.com/65892539/391879262-bcc99194-6deb-4e3a-b019-87484d52ce50.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODcyMjYsIm5iZiI6MTczMzM4NjkyNiwicGF0aCI6Ii82NTg5MjUzOS8zOTE4NzkyNjItYmNjOTkxOTQtNmRlYi00ZTNhLWIwMTktODc0ODRkNTJjZTUwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDI2YzZiNTMxNjdlZDU0MWY3ZDY4NTZlZWQ5YmY1YTFkNGQxOGY3ZWI1NTgyNDI5YjE0YzkwZDI2ZWM2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._f2Wh1vHHokPPImSu9SFTjE_1lZzKDj-smbcFV4kp-4)

你的分析是对的
当我点击测试的，给新的查询条件，获取新的数据，total之后，我让currentPage.value = 1，解决了这个问题，谢谢

**Comment by huangwenboha563** [comment]
> 这种问题比较常见了，就是当前查询条件下的最大页数小于已选页数，所以自动改了`current-page`，解决方案一般都是写个通用列表查询，存两份查询条件，点查询按钮用最新的条件，点分页用旧的条件

你的思路也可以，但是我一旦有新的查询条件，有新的total我让currentPage.value = 1解决了

**Comment by huangwenboha563** [comment]
> 我意见和 @xionkq @YiMo1 一致，@xionkq 给出了详细的说明。
> 
> 你能详细说明一下你具体的场景吗？

谢谢，就是用户把自己常用的查询条件给保存了，存到后台了，然后根据使用习惯，点击之前保存的查询条件，给后端
一有新的条件，我就把currentPage.value = 1 解决了
