### ISSUE TITLE
Problems in lazy loading of [bug report] El cascade

### ISSUE THREAD

**Issue by MQYForverT** [element-plus/element-plus#1911]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
win10

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/mqyforvert/pen/vYgPwxg

### Steps to reproduce
如上链接demo

我使用el-cascader懒加载，因为在实际项目中层级不清楚，所以不知道哪一个为leaf节点，所以我在demo不指定leaf属性。
我模拟当leaf等于3时，也就是当来到第四层时，就resolve一个空数组[]

按照文档约定：如果没指定leaf属性，会简单的以有无子节点来判断是否为叶子节点。

### What is Expected?
当leaf等于3，也就是当来到第四层时，因为第4层为[]，所以按照约定，第三层为叶子节点，我打印了日志，发现第三层的isLeaf属性确实为true，
但是问题是：

此时级联框没有回显数据，
期望：
级联框同步回显数据

### What is actually happening?
级联框没有回显数据

**Comment by xiaoxian521** [comment]
@sxzz  It has been verified that this problem has been resolved in the latest version
<img width="786" alt="WechatIMG257" src="https://user-images.githubusercontent.com/44761321/133268239-cd1177c4-fb18-48e7-8ba7-234a8ef7cb8e.png">
