### ISSUE TITLE
[Docs] [select] Missing Chinese translation for Select component's tabs.

### ISSUE THREAD

**Issue by xionkq** [element-plus/element-plus#19117]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `Chrome 131.0.6778.86`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html)

### Steps to reproduce

Open the document [link](https://element-plus.org/zh-CN/component/select.html)

### What is Expected?

show "Select 选择器"

### What is actually happening?

show "Select"

### Additional comments

![image](https://github.com/user-attachments/assets/0535646f-0bf3-4899-af0b-36a2f283a931)

**Comment by btea** [comment]
谢谢反馈和修正，已接受修改。下次发版会更新。
