### ISSUE TITLE
[Bug Report] el-row type

### ISSUE THREAD

**Issue by fushengruomengzhang** [element-plus/element-plus#1912]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
Google Chrome	90.0.4430.85 (正式版本) (x86_64)

### Vue version
3.0.11

### Reproduction Link
jsfiddle/codepen/codesandbox

### Steps to reproduce
el-row 的type 默认值为空，想要启用flex，需要配置type=flex,目前我未配置type=flex，也启用了flex。而且多层的 el-col 不生效。

```
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://unpkg.com/vue@next"></script>
    <!-- import CSS -->
    <link rel="stylesheet" href="https://unpkg.com/element-plus/lib/theme-chalk/index.css">
    <!-- import JavaScript -->
    <script src="https://unpkg.com/element-plus/lib/index.full.js"></script>
    <title>Element Plus demo</title>
  </head>
  <body>
    <div id="app">
      <el-row>
        <el-col :span=24>123</el-col>
        <el-col :span=24>
          <el-col :span=24>123</el-col>
          <el-col :span=24>123</el-col>
        </el-col>
      </el-row>
    </div>
    <script>
      const App = {
        data() {
          return {
            message: "Hello Element Plus",
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");
    </script>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/63709269/116241638-ada36900-a797-11eb-84c8-b7c3ed9b737c.png)

### What is Expected?
希望和layout文档中描述的一致。希望 多层 el-col 同样生效

### What is actually happening?
和layout文档中描述的不一致，未启用flex，结果启用了，另外多层el-col 存在问题。

**Comment by kooriookami** [comment]
Well, You can add el-row to the outer layer of el-col. And we delete `type="flex"` prop, now el-row default use flex layout.
