### ISSUE TITLE
[Component] ElNotification, dangerouslyUseHTMLString设置为true失效

### ISSUE THREAD

**Issue by Joey-Ren** [element-plus/element-plus#19126]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.9.0`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-notification`
- `el-message`
- `el-message-box`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/notification.html)

### Steps to reproduce

1、打开网址：https://element-plus.org/zh-CN/component/notification.html
2、找到使用 HTML 片段作为正文内容
3、点击按钮Use HTML String

### What is Expected?

渲染出正常的HDML标签

### What is actually happening?

直接把HTML标签打印出来了

### Additional comments

_(empty)_

**Comment by shizhihuaxu** [comment]
[看起来pr已经合并了](https://github.com/element-plus/element-plus/pull/19068)

**Comment by btea** [comment]
fixed by #19068
