### ISSUE TITLE
[feature request] what is the type of El form instance

### ISSUE THREAD

**Issue by wellfrog16** [element-plus/element-plus#1913]
### Existing Component
Yes

### Component Name
el-form

### Description
通过
`<el-form ref="myform" >`
中ref获取到实例后，myForm的ts类型是什么呢？

**Comment by hr837** [comment]
> Translation of this issue:
> 
> ### Existing Component
> Yes
> 
> ### Component Name
> el-form
> 
> ### Description
> What is the TS type of myform after obtaining the instance through ref in < El form ref = "myform" >?

同问，ref怎么定义ElForm的类型

**Comment by wellfrog16** [comment]
InstanceType<typeof ElForm>
