### ISSUE TITLE
[Component] [upload, dialog] el-upload 上传文件名超过el-dialog弹窗宽度时，会超出显示

### ISSUE THREAD

**Issue by xiaomanong001** [element-plus/element-plus#19168]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `Chrome 131.0.6778.108`
- Build Tool: `Vite`

### Related Component

- `el-upload`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmltcG9ydCB0eXBlIHsgVXBsb2FkUHJvcHMsIFVwbG9hZFVzZXJGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuY29uc3QgZm9ybURhdGE9cmVmKHt9KVxuXG5jb25zdCBmaWxlTGlzdCA9IHJlZjxVcGxvYWRVc2VyRmlsZVtdPihbXG4gIHtcbiAgICBuYW1lOiAn5YWz5LqO5LuK5aSp5piv5pif5pyf5LqU77yM5ZGY5bel5peg5b+D5oOF5LiK54+t55qE5Yaz5a6a6YCa55+lJyxcbiAgICB1cmw6ICdodHRwczovL2VsZW1lbnQtcGx1cy5vcmcvaW1hZ2VzL2VsZW1lbnQtcGx1cy1sb2dvLnN2ZycsXG4gIH0sXG4gIHtcbiAgICBuYW1lOiAnZWxlbWVudC1wbHVzLWxvZ28yLnN2ZycsXG4gICAgdXJsOiAnaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmcnLFxuICB9LFxuXSlcblxuY29uc3QgaGFuZGxlUmVtb3ZlOiBVcGxvYWRQcm9wc1snb25SZW1vdmUnXSA9IChmaWxlLCB1cGxvYWRGaWxlcykgPT4ge1xuICBjb25zb2xlLmxvZyhmaWxlLCB1cGxvYWRGaWxlcylcbn1cblxuY29uc3QgaGFuZGxlUHJldmlldzogVXBsb2FkUHJvcHNbJ29uUHJldmlldyddID0gKHVwbG9hZEZpbGUpID0+IHtcbiAgY29uc29sZS5sb2codXBsb2FkRmlsZSlcbn1cblxuY29uc3QgaGFuZGxlRXhjZWVkOiBVcGxvYWRQcm9wc1snb25FeGNlZWQnXSA9IChmaWxlcywgdXBsb2FkRmlsZXMpID0+IHtcbiAgRWxNZXNzYWdlLndhcm5pbmcoXG4gICAgYFRoZSBsaW1pdCBpcyAzLCB5b3Ugc2VsZWN0ZWQgJHtmaWxlcy5sZW5ndGh9IGZpbGVzIHRoaXMgdGltZSwgYWRkIHVwIHRvICR7XG4gICAgICBmaWxlcy5sZW5ndGggKyB1cGxvYWRGaWxlcy5sZW5ndGhcbiAgICB9IHRvdGFsbHlgXG4gIClcbn1cblxuY29uc3QgYmVmb3JlUmVtb3ZlOiBVcGxvYWRQcm9wc1snYmVmb3JlUmVtb3ZlJ10gPSAodXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgcmV0dXJuIEVsTWVzc2FnZUJveC5jb25maXJtKFxuICAgIGBDYW5jZWwgdGhlIHRyYW5zZmVyIG9mICR7dXBsb2FkRmlsZS5uYW1lfSA/YFxuICApLnRoZW4oXG4gICAgKCkgPT4gdHJ1ZSxcbiAgICAoKSA9PiBmYWxzZVxuICApXG59XG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlPXRydWVcIj7lvLnnqpc8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cInZpc2libGVcIlxuICAgIHRpdGxlPVwi5LiK5Lyg5paH5Lu2XCJcbiAgICB3aWR0aD1cIjMwdmhcIlxuICA+XG4gICA8ZWwtZnJvbSA6bW9kZWw9XCJmb3JtRGF0YVwiIGxhYmVsLXdpZHRoPVwiMTYwcHhcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5paH5Lu25LiK5Lyg77yaXCI+XG4gICAgICAgPGVsLXVwbG9hZFxuICAgIHYtbW9kZWw6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIGFjdGlvbj1cImh0dHBzOi8vcnVuLm1vY2t5LmlvL3YzLzlkMDU5YmY5LTQ2NjAtNDVmMi05MjVkLWNlODBhZDZjNGQxNVwiXG4gID5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+Q2xpY2sgdG8gdXBsb2FkPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwS0IuXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgIDwvZWwtZnJvbT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi42LjAvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi42LjAvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy40LjIxL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjQuMjEvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuNi4wL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi42LjAvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```
<script setup lang="ts">
import { ElementPlus } from '@element-plus/icons-vue'
import { version as epVersion } from 'element-plus'
import { ref, version as vueVersion } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

import type { UploadProps, UploadUserFile } from 'element-plus'
const formData=ref({})

const fileList = ref<UploadUserFile[]>([
  {
    name: '关于今天是星期五，员工无心情上班的决定通知',
    url: 'https://element-plus.org/images/element-plus-logo.svg',
  },
  {
    name: 'element-plus-logo2.svg',
    url: 'https://element-plus.org/images/element-plus-logo.svg',
  },
])

const handleRemove: UploadProps['onRemove'] = (file, uploadFiles) => {
  console.log(file, uploadFiles)
}
const visible = ref(false)

<template>
  <el-button @click="visible=true">弹窗</el-button>
    <el-dialog
    v-model="visible"
    title="上传文件"
    width="30vh"
  >
   <el-from :model="formData" label-width="160px">
    <el-form-item label="文件上传：">
       <el-upload
    v-model:file-list="fileList"
    action="https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15"
  >
    <el-button type="primary">Click to upload</el-button>
    <template #tip>
      <div class="el-upload__tip">
        jpg/png files with a size less than 500KB.
      </div>
    </template>
  </el-upload>
    </el-form-item>
   </el-from>
  </el-dialog>
</template>
</script>

```

### What is Expected?

超出弹窗边界应该自动省略在弹窗内

### What is actually happening?

超出弹窗边界而是现实在弹窗内外了

### Additional comments

_(empty)_

**Comment by shizhihuaxu** [comment]
给 el-upload 设置 width: 100%

**Comment by btea** [comment]
文件名称已经添加了超出省略的样式，其他的需要用户自己调整。
