### ISSUE TITLE
[Component] [input] ElMessageBox 添加虚拟输入框无法输入内容

### ISSUE THREAD

**Issue by 4104389** [element-plus/element-plus#19174]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `谷歌浏览器`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cblxuaW1wb3J0IHtFbElucHV0LCBFbE1lc3NhZ2VCb3h9IGZyb20gXCJlbGVtZW50LXBsdXNcIjtcbmltcG9ydCB7aCwgcmVmfSBmcm9tIFwidnVlXCI7XG5cbmNvbnN0IGlucHV0VmFsdWUgPSByZWYoKTtcblxuZnVuY3Rpb24gY2xpY2soKSB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICfmtYvor5UnLFxuICAgIG1lc3NhZ2U6IGgoRWxJbnB1dCwge1xuICAgICAgbW9kZWxWYWx1ZTogaW5wdXRWYWx1ZS52YWx1ZSwgcGxhY2Vob2xkZXI6ICfor7fovpPlhaXkvaDnmoTlhoXlrrknLFxuICAgICAgJ29uVXBkYXRlOm1vZGVsVmFsdWUnOiAodmFsdWU6IHN0cmluZykgPT4ge1xuICAgICAgICBpbnB1dFZhbHVlLnZhbHVlID0gdmFsdWU7XG4gICAgICB9XG4gICAgfSlcbiAgfSk7XG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2xpY2soKVwiIHR5cGU9XCJzdWNjZXNzXCI+54K55oiRPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<script lang="ts" setup>

import {ElInput, ElMessageBox} from "element-plus";
import {h, ref} from "vue";

const inputValue = ref();

function click() {
  ElMessageBox({
    title: '测试',
    message: h(ElInput, {
      modelValue: inputValue.value, placeholder: '请输入你的内容',
      'onUpdate:modelValue': (value: string) => {
        inputValue.value = value;
      }
    })
  });
}

</script>

<template>
  <el-button @click="click()" type="success">点我</el-button>
</template>

### What is Expected?

输入框能够正常输入内容

### What is actually happening?

输入框无法输入内容

### Additional comments

_(empty)_

**Comment by btea** [comment]
写法要调整一下，[示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cblxuaW1wb3J0IHtFbElucHV0LCBFbE1lc3NhZ2VCb3h9IGZyb20gXCJlbGVtZW50LXBsdXNcIjtcbmltcG9ydCB7aCwgcmVmfSBmcm9tIFwidnVlXCI7XG5cbmNvbnN0IGlucHV0VmFsdWUgPSByZWYoKTtcblxuZnVuY3Rpb24gY2xpY2soKSB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICfmtYvor5UnLFxuICAgIG1lc3NhZ2U6ICgpID0+IGgoRWxJbnB1dCwge1xuICAgICAgbW9kZWxWYWx1ZTogaW5wdXRWYWx1ZS52YWx1ZSwgcGxhY2Vob2xkZXI6ICfor7fovpPlhaXkvaDnmoTlhoXlrrknLFxuICAgICAgJ29uVXBkYXRlOm1vZGVsVmFsdWUnOiAodmFsdWU6IHN0cmluZykgPT4ge1xuICAgICAgICBpbnB1dFZhbHVlLnZhbHVlID0gdmFsdWU7XG4gICAgICB9XG4gICAgfSlcbiAgfSk7XG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2xpY2soKVwiIHR5cGU9XCJzdWNjZXNzXCI+54K55oiRPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by songyucoder** [comment]
可以尝试 这样 写法
`const form = ref({
  audit_status: '2',
  reject_reason: ''
}) as any`

`const CustomComponent = () => {
  return (
    <>
      <ElForm v-model={form} label-width="120px">
        <ElFormItem label="审核状态">
          <ElRadioGroup v-model={form.value.audit_status}>
            <ElRadio value="2">审核通过</ElRadio>
            <ElRadio value="1">审核未通过</ElRadio>
          </ElRadioGroup>
        </ElFormItem>
        {form.value.audit_status == '1' ? (
          <>
            <ElFormItem label="原因">
              <ElInput v-model={form.value.reject_reason} type="textarea" />
            </ElFormItem>
          </>
        ) : (
          <></>
        )}
      </ElForm>
    </>
  )
}
`

`ElMessageBox({
    title: '审核',
    message: h(CustomComponent),
    callback: (action) => {
      if (action === 'confirm') {
        if (ids.value.length > 1) {
          ElMessage.error('暂只能选择一个商品')
          return
        }
        check(null)
      } else if (action === 'cancel') {
      }
    }
  })`

![Uploading 截屏2024-12-16 15.15.54.png…]()

**Comment by songyucoder** [comment]
![截屏2024-12-16 15 15 54](https://github.com/user-attachments/assets/f5b076c3-f607-4b23-a31c-3d35d1622906)

可以尝试 这样 写法
`const form = ref({
  audit_status: '2',
  reject_reason: ''
}) as any`

`const CustomComponent = () => {
  return (
    <>
      <ElForm v-model={form} label-width="120px">
        <ElFormItem label="审核状态">
          <ElRadioGroup v-model={form.value.audit_status}>
            <ElRadio value="2">审核通过</ElRadio>
            <ElRadio value="1">审核未通过</ElRadio>
          </ElRadioGroup>
        </ElFormItem>
        {form.value.audit_status == '1' ? (
          <>
            <ElFormItem label="原因">
              <ElInput v-model={form.value.reject_reason} type="textarea" />
            </ElFormItem>
          </>
        ) : (
          <></>
        )}
      </ElForm>
    </>
  )
}
`

`ElMessageBox({
    title: '审核',
    message: h(CustomComponent),
    callback: (action) => {
      if (action === 'confirm') {
        if (ids.value.length > 1) {
          ElMessage.error('暂只能选择一个商品')
          return
        }
        check(null)
      } else if (action === 'cancel') {
      }
    }
  })`
