### ISSUE TITLE
[Question / Feature Request] Date table sorting with progenitor

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1918]
Hi, I have connected progenitor and i have issue with date sorting.
If you try to sort the date you will see that: dateCreated
Page 1: 2020 then 2021
Page 2: 2020 then 2021
and it should be
2020 -> 2021 in all the pages
and
2021 > 2020
This is happened because of the computed, pagedTableData property.
if you will attach the projects(Data Property) instead it will work great.

How can i slove this?
Is there away to connect progenitor to the table with date sorting feature?

[https://codepen.io/vadimt2/pen/poRmGdV](https://codepen.io/vadimt2/pen/poRmGdV)

**Comment by vadimt2** [comment]
Can you please add a paginator to a table with sorting?
or help me please to fix this issue:
[https://codepen.io/vadimt2/pen/poRmGdV](https://codepen.io/vadimt2/pen/poRmGdV)
try to sort the data in page one and 2, and it always will be 2020

**Comment by sxzz** [comment]
Hi.
The Table component will be refactored, so this issue is temporarily closed, and feel free to reopen an issue if you have any questions.
