### ISSUE TITLE
[Docs] [upload] el-upload 使用file作用域插槽时，文档所提供的类型中有index这个字段，但实际使用中没有，是文档没同步更新吗？

### ISSUE THREAD

**Issue by MingTuT** [element-plus/element-plus#19182]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.7.2`
- Browser / OS: `Chrome 131.0.6778.69`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/upload.html)

### Steps to reproduce

在使用el-ipload的file作用域插槽时，解构出来的属性只有file。

### What is Expected?

根据文档的类型是有{ file: UploadFile, index: number }

### What is actually happening?

实际只有{ file: UploadFile }

### Additional comments

请问这种情况是代码更新后但文档没及时同步吗？

**Comment by shizhihuaxu** [comment]
index 属性是在[ 2.8.0](https://github.com/element-plus/element-plus/releases/tag/2.8.0) 版本增加的

**Comment by btea** [comment]
@shizhihuaxu 感谢回复。👍

文档中之前忘了加版本标记，有兴趣的话，可以在文档中添加一个新的示例并添加版本号。
