### ISSUE TITLE
In el-table, <el-table-column type="index"></el-table-column> and <el-table-column type="expand"> < /el-table-column> are used. When expand is expanded, the index sorting error occurs

### ISSUE THREAD

**Issue by Buttii** [element-plus/element-plus#1919]
[https://codesandbox.io/s/element-plus-spa-forked-9zho8?file=/src/App.vue](https://codesandbox.io/s/element-plus-spa-forked-9zho8?file=/src/App.vue)

**Comment by Buttii** [comment]
上面的问题解决了，但又出现了新的问题，当el-table设置row-key属性时，type="index"的el-table-column页面显示全部为1。
https://codesandbox.io/s/element-plus-spa-forked-fzgs4?file=/src/App.vue

**Comment by yaohzone** [comment]
翻看源码发现很奇怪的逻辑：
```
this.wrappedRowRender(
    row,
    acc.filter(item => typeof item.key === 'number').length,
)`
```
[源码](https://github.com/element-plus/element-plus/blob/a08f9efcbb62f3ddfb8dfa262401a44a3cfe8f69/packages/table/src/table-body/index.ts#L82)。
查看这里[`item.key`](https://github.com/element-plus/element-plus/blob/a08f9efcbb62f3ddfb8dfa262401a44a3cfe8f69/packages/table/src/table-body/render-helper.ts#L64)值，如果设置`row-key`就是该字段提供值，为非数值时就会产生类似BUG，即$index全为0，由此也导致hover项始终为第一个即0。
从44升级到45之后table确实遇到了这个BUG。。。
没时间细看这块的问题，希望能尽快解决
