### ISSUE TITLE
[Bug Report] <el-Input> changes within a <el-form> component cannot trigger a hot reload

### ISSUE THREAD

**Issue by 9thDaybreak** [element-plus/element-plus#1922]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
MacOS 11.2.3 / Chrome  89.0.4389.90

### Vue version
3.0.11

### Reproduction Link
https://github.com/9thDaybreak/Test-component-problems

### Steps to reproduce
Modify “size” attribute and “label” attribute of  <el-input> in the <el-form> component and the <el-form-item> component
will not trigger hot reload

在<el-form>表单组件、<el-form-item>内的 el 组件发生了修改，不会触发热重载，
例如修改 <el-input> 的 size 属性、label 属性等，
其他表单组件尚未测试，
在表单<el-form>组件以外的地方测试修改 <el-input> 的属性是可以触发热重载的，
vue2、element-ui 的环境下，<el-form>内的表单组件也可以正常触发热重载

浏览器、nodejs、vuecli均为目前最新版本

### What is Expected?
Normal hot overload

### What is actually happening?
Hot overload can fail in some cases

**Comment by 9thDaybreak** [comment]
![image](https://user-images.githubusercontent.com/20859145/116532165-88873580-a912-11eb-81a1-579ce264f465.png)

Modif 'size' and 'label' attribute in the <el-input>

**Comment by kooriookami** [comment]
I test in latest version, it works, so close it.
