### ISSUE TITLE
[Component] [notification] Notification 通知 HTML 渲染为字符串

### ISSUE THREAD

**Issue by Haoingli** [element-plus/element-plus#19225]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/notification.html)

### Steps to reproduce

->element-plus 官网
->Notification 通知      
->使用 HTML 片段作为正文内容

点击  Use HTML String 按钮

### What is Expected?

使用HTML 渲染

### What is actually happening?

HTML 标签 当做 字符 渲染了

### Additional comments

_(empty)_

**Comment by Haoingli** [comment]
![Uploading eb34dfb2-a39a-4761-97c3-d28d433c59c9.jpeg…]()
​​

**Comment by Liao-js** [comment]
fixed by https://github.com/element-plus/element-plus/pull/19068
