### ISSUE TITLE
[Component] [table] clearSelection of Table is not function

### ISSUE THREAD

**Issue by SunYong0821** [element-plus/element-plus#19224]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.8.4`
- Browser / OS: `Chrome/131.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[[Link]()
](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRhYmxlRGF0YSA9IHJlYWN0aXZlKHtcbiAgZGF0YTogW3twYXRpZW50TmFtZTogJ0FBQSd9XVxufSlcbmNvbnN0IGVkaXRhYmxlVGFicyA9IHJlZihbXSlcbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpeGVkJylcbmNvbnN0IHNlbGVjdFJvd3MgPSByZWYoW10pXG5jb25zdCBvblNlbGVjdCA9IChyb3dzKSA9PiB7XG4gIHNlbGVjdFJvd3MudmFsdWUgPSByb3dzXG4gIGNvbnNvbGUubG9nKCd4dWFuemUnKVxufVxuY29uc3Qgc2FtcGxlVGFibGUgPSByZWYobnVsbClcbmNvbnN0IG9uU2VsZWN0Q2hhbmdlID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygncWluZ2NodScpXG4gIHNhbXBsZVRhYmxlLnZhbHVlLmNsZWFyU2VsZWN0aW9uKClcbn1cbmNvbnN0IGNoZWNrUmVwb3J0ID0gYXN5bmMgKCkgPT4ge1xuICAgICAgY29uc3QgdCA9IHtcbiAgICAgICAgdGl0bGU6ICdCQkInLFxuICAgICAgICBuYW1lOiAnQkJCJyxcbiAgICAgICAgc2FtcGxlOiBbe2xhYkRhdGU6ICcyMDI0MTAxMCd9XVxuICAgICAgfVxuICAgICAgZWRpdGFibGVUYWJzLnZhbHVlLnB1c2godClcbiAgICAgIGFjdGl2ZU5hbWUudmFsdWUgPSB0Lm5hbWVcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJzIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCIgdHlwZT1cImJvcmRlci1jYXJkXCIgQHRhYi1jbGljaz1cIm9uU2VsZWN0Q2hhbmdlXCI+XG4gICAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLlvoXnlJ/miJDmiqXlkYrliJfooahcIiBuYW1lPVwiZml4ZWRcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImZsZXggaXRlbXMtY2VudGVyIGZsZXgtY29sXCI+XG4gICAgICAgICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhLmRhdGFcIiA6Ym9yZGVyPVwidHJ1ZVwiIHN0cmlwZSB0YWJsZS1sYXlvdXQ9XCJhdXRvXCI+XG4gICAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwicGF0aWVudE5hbWVcIiBsYWJlbD1cIuaCo+iAheWnk+WQjVwiIC8+XG4gICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIue7k+aenOafpeeci1wiIGZpeGVkPVwicmlnaHRcIiB3aWR0aD1cIjkwXCIgc2hvdy1vdmVyZmxvdy10b29sdGlwPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgdi1zbG90PVwic2NvcGVcIj5cbiAgICAgICAgICAgICAgICA8ZWwtdG9vbHRpcCBlZmZlY3Q9XCJkYXJrXCIgY29udGVudD1cIuafpeeci+e7k+aenFwiIHBsYWNlbWVudD1cInRvcFwiPlxuICAgICAgICAgICAgICAgICAgPGVsLWJ1dHRvbiBjaXJjbGUgdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJjaGVja1JlcG9ydFwiPlxuICAgICAgICAgICAgICAgICAgICA8ZWwtaWNvbj48TW9uaXRvciAvPjwvZWwtaWNvbj5cbiAgICAgICAgICAgICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICAgIDwvZWwtdGFibGU+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC10YWItcGFuZT5cbiAgICAgIDxlbC10YWItcGFuZSB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gZWRpdGFibGVUYWJzXCIgOmtleT1cIml0ZW0ubmFtZSArIGluZGV4XCIgOmxhYmVsPVwiaXRlbS50aXRsZVwiIDpuYW1lPVwiaXRlbS5uYW1lXCIgY2xvc2FibGU+XG4gICAgICAgIDxlbC10YWJsZSA6ZGF0YT1cIml0ZW0uc2FtcGxlXCIgOmJvcmRlcj1cInRydWVcIiBzdHJpcGUgdGFibGUtbGF5b3V0PVwiYXV0b1wiIEBzZWxlY3Rpb24tY2hhbmdlPVwib25TZWxlY3RcIiByZWY9XCJzYW1wbGVUYWJsZVwiPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIGZpeGVkIHdpZHRoPVwiNDBcIiAvPlxuICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJsYWJEYXRlXCIgbGFiZWw9XCLkuIrmnLrml6XmnJ9cIiAvPiAgIFxuICAgICAgICA8L2VsLXRhYmxlPlxuICAgICAgPC9lbC10YWItcGFuZT5cbiAgICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjQvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjQvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy40LjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjQuMjkvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC40L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjQvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)
### Steps to reproduce

```vue
<script setup lang="js">
import { ElementPlus } from '@element-plus/icons-vue'
import { version as epVersion } from 'element-plus'
import { ref, version as vueVersion, reactive } from 'vue'
const tableData = reactive({
  data: [{patientName: 'AAA'}]
})
const editableTabs = ref([])
const activeName = ref('fixed')
const selectRows = ref([])
const onSelect = (rows) => {
  selectRows.value = rows
  console.log('xuanze')
}
const sampleTable = ref(null)
const onSelectChange = () => {
  console.log('qingchu')
  sampleTable.value.clearSelection()
}
const checkReport = async () => {
      const t = {
        title: 'BBB',
        name: 'BBB',
        sample: [{labDate: '20241010'}]
      }
      editableTabs.value.push(t)
      activeName.value = t.name
}
</script>

<template>
  <el-tabs v-model="activeName" type="border-card" @tab-click="onSelectChange">
      <el-tab-pane label="待生成报告列表" name="fixed">
        <div class="flex items-center flex-col">
          <el-table :data="tableData.data" :border="true" stripe table-layout="auto">
            <el-table-column property="patientName" label="患者姓名" />
             <el-table-column label="结果查看" fixed="right" width="90" show-overflow-tooltip>
              <template v-slot="scope">
                <el-tooltip effect="dark" content="查看结果" placement="top">
                  <el-button circle type="primary" @click="checkReport">
                    <el-icon><Monitor /></el-icon>
                  </el-button>
                </el-tooltip>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </el-tab-pane>
      <el-tab-pane v-for="(item, index) in editableTabs" :key="item.name + index" :label="item.title" :name="item.name" closable>
        <el-table :data="item.sample" :border="true" stripe table-layout="auto" @selection-change="onSelect" ref="sampleTable">
          <el-table-column type="selection" fixed width="40" />
          <el-table-column property="labDate" label="上机日期" />   
        </el-table>
      </el-tab-pane>
    </el-tabs>
</template>

```

### What is Expected?

when i click tabs, the value of selection need to clear

### What is actually happening?

it reported clearSelection is not function

### Additional comments

_(empty)_

**Comment by Liao-js** [comment]
![image](https://github.com/user-attachments/assets/24cf0a3f-a644-4473-aed5-e2e26b35d015)

sampleTable.value 是一个数组

**Comment by SunYong0821** [comment]
> ![image](https://private-user-images.githubusercontent.com/43257608/394550840-24cf0a3f-a644-4473-aed5-e2e26b35d015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODcyNjEsIm5iZiI6MTczMzg4Njk2MSwicGF0aCI6Ii80MzI1NzYwOC8zOTQ1NTA4NDAtMjRjZjBhM2YtYTY0NC00NDczLWFlZDUtZTJlMjZiMzVkMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAzMTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTljYmU4ZTUxNDBlMzc3ZjBiYzUyNDE1ODY3MzYxOWZlNzhkYTNlMWI4NDczOTZhMjQyNTlmMDVkYjQ1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F0tp92XXyXWlvDLetIefZGw3geOTaM3vnygBMAjnL2M)
> 
> sampleTable.value 是一个数组

您的意思是这个ref要写在数组里面，而且不同的table之间不能一样的ref，是吗

**Comment by Liao-js** [comment]
> > ![image](https://private-user-images.githubusercontent.com/43257608/394550840-24cf0a3f-a644-4473-aed5-e2e26b35d015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODcyNjEsIm5iZiI6MTczMzg4Njk2MSwicGF0aCI6Ii80MzI1NzYwOC8zOTQ1NTA4NDAtMjRjZjBhM2YtYTY0NC00NDczLWFlZDUtZTJlMjZiMzVkMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAzMTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTljYmU4ZTUxNDBlMzc3ZjBiYzUyNDE1ODY3MzYxOWZlNzhkYTNlMWI4NDczOTZhMjQyNTlmMDVkYjQ1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F0tp92XXyXWlvDLetIefZGw3geOTaM3vnygBMAjnL2M)
> > sampleTable.value 是一个数组
> 
> 您的意思是这个ref要写在数组里面，而且不同的table之间不能一样的ref，是吗

因为放在循环中，所以会导致 sampleTable.value 返回的是一个数组，数组中每个值都代表着不同的 table 组件

**Comment by SunYong0821** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/43257608/394550840-24cf0a3f-a644-4473-aed5-e2e26b35d015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODcyNjEsIm5iZiI6MTczMzg4Njk2MSwicGF0aCI6Ii80MzI1NzYwOC8zOTQ1NTA4NDAtMjRjZjBhM2YtYTY0NC00NDczLWFlZDUtZTJlMjZiMzVkMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAzMTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTljYmU4ZTUxNDBlMzc3ZjBiYzUyNDE1ODY3MzYxOWZlNzhkYTNlMWI4NDczOTZhMjQyNTlmMDVkYjQ1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F0tp92XXyXWlvDLetIefZGw3geOTaM3vnygBMAjnL2M)
> > > sampleTable.value 是一个数组
> > 
> > 
> > 您的意思是这个ref要写在数组里面，而且不同的table之间不能一样的ref，是吗
> 
> 因为放在循环中，所以会导致 sampleTable.value 返回的是一个数组，数组中每个值都代表着不同的 table 组件

好的，我下午先把sampleTable变成一个数组进行测试一下。非常感谢！~
