### ISSUE TITLE
 [CI]: Running `Publish PR Commit Pkg` locally

### ISSUE THREAD

**Issue by Dsaquel** [element-plus/element-plus#19269]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `chrome/brave on ubuntu`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[PR's before & after](https://github.com/Dsaquel/element-plus/pulls)

### Steps to reproduce

I think there is might be a vulnerability issue (?)
After deleting:
```yml
if: ${{ github.repository == 'element-plus/element-plus' }}
```
in [PR](https://github.com/element-plus/element-plus/commit/afa57bf3741dedea0c260cc2b9777c6ea03c22c2#diff-09d64145ceb29ff06a45898550dc02cdb1d844711cfcabd8af13fd3e2c948171L16)

I was curious so i decide to open a PR locally and commit to it and i was able to run `Publish PR Commit Pkg`.

### What is Expected?

Not able to run `publish-pr-commit-pkg.yml`

### What is actually happening?

able to run `publish-pr-commit-pkg.yml`

### Additional comments

I made two PR's in my own repo to see what ci are runs locally before [PR merge](https://github.com/element-plus/element-plus/pull/19252) and after.

Maybe it's not an security issue and maybe its a cool ci to run locally but i prefer to report just in case i dont have the whole context.

**Comment by btea** [comment]
Thanks for your report. However, this is because @Aslemammad  and I recently debug the 403 error after merging PR into the dev branch.

You can create a pr to add the if statement back.

**Comment by Aslemammad** [comment]
sorry for that, yea it was for debugging! feel free to send a PR if you want, if not, I'd be happy to do it.

**Comment by Dsaquel** [comment]
Ill do it no problem

**Comment by Aslemammad** [comment]
thank you so much!
