### ISSUE TITLE
[Feature Request] how to add a type to template-scope for better use of Typescript

### ISSUE THREAD

**Issue by Darma1106** [element-plus/element-plus#1926]
### Existing Component
Yes

### Component Name
el-table-colum

### Description
```
<el-table-column >
      <template #default="scope">
        <el-button @click="deleteRow(scope)" type="text" size="small">
          xxx
        </el-button>
      </template>
</el-table-column>
```

this scopoe's type is any,how to add a type to scope

**Comment by Zhaocl1997** [comment]
try to use [`volar`](https://github.com/johnsoncodehk/volar) plugin on vscode. It supports for slot type enhancement
