### ISSUE TITLE
[Component] [tree-select] 选择后警告：[Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.

### ISSUE THREAD

**Issue by yangxu52** [element-plus/element-plus#19271]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.8.8`
- Browser / OS: `Chrome/131.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzZWxlY3QgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgaWQ6IDIsXG4gICAgcGFyZW50SWQ6IG51bGwsXG4gICAgbmFtZTogJ+aZuuiDveeUn+a0uycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMsXG4gICAgICAgIHBhcmVudElkOiAyLFxuICAgICAgICBuYW1lOiAn5pm66IO955S15YqbJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiAxMDEwMTAxOCxcbiAgICAgICAgcGFyZW50SWQ6IDIsXG4gICAgICAgIG5hbWU6ICfmmbrog73miYvooagnLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgcGFyZW50SWQ6IG51bGwsXG4gICAgcHJvZHVjdFBhdGg6ICdHR0cnLFxuICAgIG5hbWU6ICfkvKDmhJ/lmagnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA1LFxuICAgICAgICBwYXJlbnRJZDogNCxcbiAgICAgICAgbmFtZTogJ+S6jOawp+WMlueis+ajgOa1i+WZqCcsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDYsXG4gICAgICAgICAgICBwYXJlbnRJZDogNSxcbiAgICAgICAgICAgIG5hbWU6ICfphbjnorHluqbmo4DmtYvorqEnLFxuICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIGlkOiAxMDEwMTAxNyxcbiAgICAgICAgICAgICAgICBwYXJlbnRJZDogNixcbiAgICAgICAgICAgICAgICBuYW1lOiAn55uQ5bqm5qOA5rWL6K6hJyxcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBzZWxlY3QgfX08L2gxPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdFwiIDpkYXRhPVwib3B0aW9uc1wiIDpwcm9wcz1cInsgbGFiZWw6ICduYW1lJyB9XCIgY2hlY2stc3RyaWN0bHkgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgY2xlYXJhYmxlIHZhbHVlLWtleT1cImlkXCIgLz5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPlxuICAgICAgPEVsZW1lbnRQbHVzIC8+XG4gICAgPC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjgvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjgvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy41LjEzL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjUuMTMvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC44L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjgvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

选择任意选项，控制台将输出警告`[Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.`

### What is Expected?

不显示 该emit事件未定义的警告

### What is actually happening?

emit事件未定义的警告

### Additional comments

[codesandbox连接](https://codesandbox.io/p/devbox/elated-pateu-wl6xqf)
不知道什么原有在线沙盒无法弹出告警，但是可以确认的是该警告来自于element-plus的el-tree-select组件的代码，v2.9.0本地依然可以复现。

vite：6.0.3

https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/select.ts#L45

```
chunk-CAGAHDR2.js?v=6a715544:2116 [Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.
    warn$1 @ chunk-CAGAHDR2.js?v=6a715544:2116
    emit @ chunk-CAGAHDR2.js?v=6a715544:8415
    （匿名） @ chunk-CAGAHDR2.js?v=6a715544:10175
    onUpdate:modelValue @ element-plus.js?v=12c16314:56586  // [source-code-1](https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/select.ts#L45)
    callWithErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2263
    callWithAsyncErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2270
    emit @ chunk-CAGAHDR2.js?v=6a715544:8466
    （匿名） @ chunk-CAGAHDR2.js?v=6a715544:10175
    handleOptionSelect @ element-plus.js?v=12c16314:36018  //[csource-code2](https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/select/src/useSelect.ts#L574)
    onNodeClick @ element-plus.js?v=12c16314:56765  // [source-code-3](https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/tree.ts#L176)
    callWithErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2263
    callWithAsyncErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2270
    emit @ chunk-CAGAHDR2.js?v=6a715544:8466
    （匿名） @ chunk-CAGAHDR2.js?v=6a715544:10175
    handleClick @ element-plus.js?v=12c16314:55965  // [source-code-4](https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree/src/tree-node.vue#L256)
    cache.<computed>.cache.<computed> @ chunk-CAGAHDR2.js?v=6a715544:12160
    callWithErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2263
    callWithAsyncErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2270
    invoker @ chunk-CAGAHDR2.js?v=6a715544:11202
    selectOptionClick @ element-plus.js?v=12c16314:56629  // [source-code-5](https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/tree-select-option.ts#L44)
    cache.<computed>.cache.<computed> @ chunk-CAGAHDR2.js?v=6a715544:12160
    callWithErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2263
    callWithAsyncErrorHandling @ chunk-CAGAHDR2.js?v=6a715544:2270
    invoker @ chunk-CAGAHDR2.js?v=6a715544:11202
```
1：https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/select.ts#L45
2：https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/select/src/useSelect.ts#L574
3：https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/tree.ts#L176
4：https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree/src/tree-node.vue#L256
5：https://github.com/element-plus/element-plus/blob/6ea5358acde01a5cf950771a734176dcefec30d6/packages/components/tree-select/src/tree-select-option.ts#L44

**Comment by btea** [comment]
我本地没能复现。有必现的场景或者步骤吗？

**Comment by yangxu52** [comment]
断点找到问题，和element-plus无关，项目问题。
`runtime-core.esm-bundler.js`L6333 `if (!(event in emitsOptions) && true).......`
条件里`emitsOptions`对象定义的一系列的emits，不知何原因被项目某mixin逻辑顶掉，导致in为false，if最终为true，进入后续警告逻辑。
