### ISSUE TITLE
[Component] [form-item] 用el-form-item包裹表单子组件，点击表单字段标题文本区域，会触发输入型组件获取焦点和点击事件

### ISSUE THREAD

**Issue by yomho** [element-plus/element-plus#19312]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.8.4`
- Browser / OS: `Chrome 131.0.6778.140`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html)

### Steps to reproduce

直接访问上面最小复现环境的链接，然后点击含下拉框和输入框的字段标题区域（标题区域如留有空白，则点击该空白区域也一样）

### What is Expected?

如果未对el-form-item绑定点击事件，则不用触发输入型组件任何交互（包括获取焦点，触发点击事件等）

### What is actually happening?

会引起el-form-item下面输入型控件（包括输入框、下拉框组件等）获取焦点或触发点击事件

### Additional comments

element-ui版本组件没问题，可参与https://element.eleme.cn/#/zh-CN/component/form

**Comment by hanchao-c0ldwave** [comment]
label通过for属性与输入框绑定，可以让用户通过点击标签来聚焦相应的输入框，增强表单的可访问性和用户体验。我觉得这不仅不是个bug，反而是一种功能增强

**Comment by yomho** [comment]
> label通过for属性与输入框绑定，可以让用户通过点击标签来聚焦相应的输入框，增强表单的可访问性和用户体验。我觉得这不仅不是个bug，反而是一种功能增强

您说的有点道理，不过有些项目客户不喜欢或测试人员会认为这种交互是BUG
但好在可以设置for = ' '来规避，谢谢提醒
由于有规避措施，这个issue可以关闭了
