### ISSUE TITLE
When [bug report] select and El tootip are nested, the option of select cannot be retracted

### ISSUE THREAD

**Issue by kevinlvhsl** [element-plus/element-plus#1933]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
chrome89

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/kevinlvhsl/pen/BapgNdp

### Steps to reproduce
通用bug， 参见链接demo   https://codepen.io/kevinlvhsl/pen/BapgNdp

<el-tooltip effect="dark" content="组合使用无法收起" placement="top">
  <el-select v-model="value1" multiple placeholder="请选择" >
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
    </el-option>
  </el-select>
  </el-tooltip>
js：

options: [{
          value: '选项1',
          label: '黄金糕'
        }, {
          value: '选项2',
          label: '双皮奶'
        }, {
          value: '选项3',
          label: '蚵仔煎'
        }, {
          value: '选项4',
          label: '龙须面'
        }, {
          value: '选项5',
          label: '北京烤鸭'
        }],

### What is Expected?
期待：嵌套使用能够正常

### What is actually happening?
实际： 目前在select选完以后不能收起

**Comment by msidolphin** [comment]
At present, i recommended that you add a wrapper outside the component

**Comment by JeremyWuuuuu** [comment]
Temporary solution, use a `div` tag to wrap the select component.
