### ISSUE TITLE
[All] [vite] (client) Pre-transform error: [sass] This variable is available from multiple global modules.

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#19382]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0`
- Build Tool: `Vite`

### Related Component

- `All`

这是一个 SASS 兼容性问题，猜测应该是 `as *` 导致的变量重复，应该使用 `namespace` 来处理就好了。

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/icon.html)

### Steps to reproduce

![图片](https://github.com/user-attachments/assets/2628b87a-3aa8-434a-af27-4814a8d08206)

![图片](https://github.com/user-attachments/assets/2d89a3bc-b334-4851-b4e9-440308b7de2d)

**Comment by WangJincheng4869** [comment]
![图片](https://github.com/user-attachments/assets/c2ac7a25-713e-4551-967d-2fe99b79343e)

**Comment by WangJincheng4869** [comment]
1.83.0














---Original---
From: ***@***.***&gt;
Date: Tue, Dec 24, 2024 20:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] [All] [vite] (client) Pre-transformerror: [sass] This variable is available from multiple global modules. (Issue#19382)




 
你使用的sass版本是多少？

**Comment by btea** [comment]
I couldn't reproduce it using https://github.com/element-plus/element-plus-vite-starter, can you provide more information?

**Comment by WangJincheng4869** [comment]
> I couldn't reproduce it using https://github.com/element-plus/element-plus-vite-starter, can you provide more information?

我发现我也无法复现了，可能是因为我过长时间没有重启哪里出现的错误（大约的有一两周没有重启了，因为重启之后加载贼慢）
