### ISSUE TITLE
[Component] [pagination] [Pagination,Table]当分页组件选择到别的页数(非第一页),再进行查询

### ISSUE THREAD

**Issue by youyMM** [element-plus/element-plus#19391]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.8`
- Element Plus Version: `2.9.0`
- Browser / OS: `Chrome/131.0.6778.110`
- Build Tool: `Vue CLI`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlYWN0aXZlLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5cbi8vIOWIhumhteWPguaVsFxubGV0IGRhdGEgPSByZWFjdGl2ZSh7XG4gIHF1ZXJ5UGFyYW1zOntcbiAgICBwYWdlTnVtOiAxLFxuICAgIHBhZ2VTaXplOiAxMCxcbiAgfSxcbiAgdG90YWw6IDIwMCxcbiAgdGFibGVEYXRhOiBbXVxufSlcblxuICBjb25zdCBoYW5kbGVDaGFuZ2UgPSAoY3VycmVudFBhZ2UsIHBhZ2VTaXplKSA9PiB7XG4gICAgY29uc29sZS5sb2coJ+WQjOaXtuaUueWPmCcsIGN1cnJlbnRQYWdlLCBwYWdlU2l6ZSk7XG4gICAgZGF0YS5xdWVyeVBhcmFtcy5wYWdlTnVtID0gY3VycmVudFBhZ2U7XG4gICAgZGF0YS5xdWVyeVBhcmFtcy5wYWdlU2l6ZSA9IHBhZ2VTaXplO1xuICAgIGdldERhdGEoY3VycmVudFBhZ2UsIHBhZ2VTaXplKTtcbiAgfTtcbiAgY29uc3Qgc2VhcmNoID0gKCk9PntcbiAgICBkYXRhLnF1ZXJ5UGFyYW1zLnBhZ2VOdW0gPSAxO1xuICAgIGRhdGEucXVlcnlQYXJhbXMucGFnZVNpemUgPSAxMDtcbiAgICBnZXREYXRhKGRhdGEucXVlcnlQYXJhbXMucGFnZU51bSwgZGF0YS5xdWVyeVBhcmFtcy5wYWdlU2l6ZSk7XG4gIH1cbiAgY29uc3QgZ2V0RGF0YSA9IChwYWdlTnVtLCBwYWdlU2l6ZSkgPT4ge1xuICAgIC8vIOaooeaLn+aOpeWPo+ivt+axglxuICAgIGRhdGEudGFibGVEYXRhID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogcGFnZVNpemUgfSwgKCkgPT4gKHtcbiAgICAgIGRhdGU6IHBhZ2VOdW0sXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0pKTtcbiAgfVxuICBzZWFyY2goKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzZWFyY2goKVwiPuaQnOe0ojwvZWwtYnV0dG9uPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJkYXRhLnRhYmxlRGF0YVwiIGJvcmRlciBzaXplPVwic21hbGxcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJuYW1lXCIgd2lkdGg9XCIxODBcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJkYXRlXCIgd2lkdGg9XCIxODBcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJhZGRyZXNzXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPC9lbC10YWJsZT5cbiAgIDxlbC1wYWdpbmF0aW9uXG4gICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgIHYtbW9kZWw6Y3VycmVudC1wYWdlPVwiZGF0YS5xdWVyeVBhcmFtcy5wYWdlTnVtXCJcbiAgICAgICAgdi1tb2RlbDpwYWdlLXNpemU9XCJkYXRhLnF1ZXJ5UGFyYW1zLnBhZ2VTaXplXCJcbiAgICAgICAgbGF5b3V0PVwidG90YWwsIHNpemVzLCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyXCJcbiAgICAgICAgOnRvdGFsPVwiZGF0YS50b3RhbFwiXG4gICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.切换页面到第二页（非第一页的任何一页）
2.再次点击查询，会调用发送两次请求，调用两次查询的接口

### What is Expected?

只触发一次发送请求

### What is actually happening?

两次请求一次是search方法本身的，第二次是pageNum页码改变到第一页又触发了handleChange

### Additional comments

@size-change和@current-change组合使用就不会出现这个问题，但是有handleChange同时有pageNum和pageSize这两个参数可用，没必要组合使用啊

**Comment by jeff-fe** [comment]
这种问题就别提bug了和组件库没有关系，你自己的业务逻辑问题，按照下面方法优化一下

```javascript
const search = ()=>{
    if( data.queryParams.pageNum > 1){
        data.queryParams.pageNum = 1;
        data.queryParams.pageSize = 10;
    }else{
        getData(data.queryParams.pageNum, data.queryParams.pageSize)
    }
 }
`
