### ISSUE TITLE
[Bug Report/Feature Request] Form not submitting on pressing enter key

### ISSUE THREAD

**Issue by TimVanHerwijnen** [element-plus/element-plus#1944]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
Windows 10 Enterprise - Firefox v88.0 64bit

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/LennyFaze/pen/VwpZvYw

### Steps to reproduce
1. Create a form using `<el-form>`
1. Try submitting the form

### What is Expected?
I expected the form to be submitted on pressing enter

### What is actually happening?
Nothing

**Comment by mistery-li** [comment]
The document has stated: When there is only one input box in a form element, press Enter on the input check box to submit the form
link: https://element-plus.gitee.io/#/en-US/component/form
