### ISSUE TITLE
[Bug Report] el-table selection can't selected in chrome version49.0.2623.112

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#1948]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
chrome version49.0.2623.112

### Vue version
3.0.11

### Reproduction Link
https://github.com/XingXiaoWu/element-error

### Steps to reproduce
When using Chrome Version49.0.2623.112, the selection is used in the El-Table, and the multiple boxes will not be selected. It is normal to use a checkbox alone.

downUrl:
32:https://dl.google.com/release2/h8vnfiy7pvn3lxy9ehfsaxlrnnukgff8jnodrp0y21vrlem4x71lor5zzkliyh8fv3sryayu5uk5zi20ep7dwfnwr143dzxqijv/49.0.2623.112_chrome_installer.exe
64:https://dl.google.com/release2/va5qxmf7d3oalefqdjoubnamxboyf9zt3o6zj33pzo2r3adq2cjea9an8hhc6tje8y4jiieqsruld9oyajv9i6atj40utl3hpl2/49.0.2623.112_chrome_installer_win64.exe

### What is Expected?
can select

### What is actually happening?
can't select

**Comment by xiaoxian521** [comment]
The browser version is too low, the selected Google browser is all 90.0.4430.93 version

**Comment by XingXiaoWu** [comment]
> The browser version is too low, the selected Google browser is all 90.0.4430.93 version

This is a compatibility issue.
49 is the latest version in XP. I can convince my clIEnts not to use IE If chrome work normally.


https://github.com/element-plus/element-plus/pull/1945
