### ISSUE TITLE
[Feature Request] DateTimePicker Clear button

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#1952]
### Existing Component
Yes

### Component Name
DateTimePicker 

### Description
Can the Clear button in the DateTimePicker panel be removed?  If not, can we provide it

![QQ截图20210507100806](https://user-images.githubusercontent.com/20943608/117387822-22a33b00-af1c-11eb-8f56-305be9707775.png)

**Comment by xiaoxian521** [comment]
clearable:false

**Comment by jahnli** [comment]
@xiaoxian521  https://codepen.io/jahnli/pen/ZEeYqLG  ，When I set clearable:false, the cleanup is still in place

**Comment by dreamqyq** [comment]
> @xiaoxian521 https://codepen.io/jahnli/pen/ZEeYqLG ，When I set clearable:false, the cleanup is still in place

clearable is attribution of input, not of picker. mybe we can provide another props to control it
