### ISSUE TITLE
[Bug Report] Datepicker event is not firing

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#1955]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
chrome

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/ntgraph/pen/NWpPaYQ

### Steps to reproduce
Code show an example of :modelValue and @change in el-date-picker. ( I notice there is no modelValue in documentation.
I do not want to use v-model as I am using el-date-picker in a custom component.
Change event is not firing.

### What is Expected?
Expect to see modelValue and change to work 

### What is actually happening?
I am using :modelValue, it is binding, change event is not firing,

**Comment by xiaoxian521** [comment]
Please try the following
```
<script src="//unpkg.com/vue@next"></script>
<script src="//unpkg.com/element-plus/lib/index.full.js"></script>
<div id="app">
<div class="block">
    
    <el-date-picker
      v-model="value1"
      type="date"
      placeholder="Pick a day"
      @change="updateValue"
      >
    </el-date-picker>
  </div> 
</div>

@import url("//unpkg.com/element-plus/lib/theme-chalk/index.css");

var Main = {
    data() {
      return {
        disabledDate(time) {
          return time.getTime() > Date.now()
        },
        shortcuts: [{
          text: 'Today',
          value: new Date(),
        }, {
          text: 'Yesterday',
          value: (() => {
            const date = new Date()
            date.setTime(date.getTime() - 3600 * 1000 * 24)
            return date
          })(),
        }, {
          text: 'A week ago',
          value: (() => {
            const date = new Date()
            date.setTime(date.getTime() - 3600 * 1000 * 24 * 7)
            return date
          })(),
        }],
        value1: '',
        value2: '',
      };
    },
  
  props: {
			fieldValue: [String, Boolean]
		},

  methods: {
			updateValue(event) {
				console.log('update-----', event)

				this.$emit('update:fieldValue', event);
			},
		},
  
  
  };
;const app = Vue.createApp(Main);
app.use(ElementPlus);
app.mount("#app")
```

**Comment by alex-outsourci** [comment]
Same here, `@change` event fires with `v-model`, but does not fire with `:model-value`.

**Comment by lakkinzimusic** [comment]
Please re-open this issue. model-value is required instead of v-model in some situations.
Same here, model-value does not work together with the @change or @input event, as indicated in a similar issue:
https://github.com/ElemeFE/element/issues/16862

Thank you for your work!

**Comment by kooriookami** [comment]
> Please re-open this issue. model-value is required instead of v-model in some situations.
> Same here, model-value does not work together with the @change or @input event, as indicated in a similar issue:
> [ElemeFE/element#16862](https://github.com/ElemeFE/element/issues/16862)
> 
> Thank you for your work!

`model-value` means readonly, it will never trigger @change or @input.
