### ISSUE TITLE
[bug report] when customizing the theme, the online theme generation tool is used to generate the theme color. After putting it into the project, the style of the component is messy

### ISSUE THREAD

**Issue by yuanxin778** [element-plus/element-plus#1959]
### Element Plus version
1.0.2-beta.41

### OS/Browsers version
谷歌浏览器

### Vue version
3.0.11

### Reproduction Link
https://github.com/element-plus/element-plus/issues/new/choose

### Steps to reproduce
自定义主题的时候，用在线主题生成工具生成了主题色放入项目后，组件的样式都乱了

### What is Expected?
自定义主题的时候，用在线主题生成工具生成了主题色放入项目后，组件的样式都乱了

### What is actually happening?
自定义主题的时候，用在线主题生成工具生成了主题色放入项目后，组件的样式都乱了

**Comment by LYao0919** [comment]
同求

**Comment by kooriookami** [comment]
Right now custom-theme is not available since we did not implement the backend functionalities for ElementPlus, this might take time.

**Comment by yuanxin778** [comment]
Oh my God!

**Comment by Greasen** [comment]
参考 https://github.com/element-plus/element-plus/issues/1018
https://github.com/element-plus/theme-chalk-preview/
我用这个解决了自定义主题的问题
用在线主题编辑器生成的主题替换et 生成后的 theme/index.css
