### ISSUE TITLE
[Bug Report] Cascader highlight previous selected option after select an option

### ISSUE THREAD

**Issue by iendeavor** [element-plus/element-plus#1977]
### Element Plus version
1.0.2-beta.42

### OS/Browsers version
macOS 10.15.7 / Chrome 90.0.4430.93

### Vue version
3.1.0-beta.2

### Reproduction Link
https://codesandbox.io/s/element-plus-cascader-props-d0e8i?file=/src/components/HelloWorld.vue

### Steps to reproduce
1. Open second Cascader.
2. Select one leaf option in the Asia group.
3. Select another one leaf option in the Europe group.

### What is Expected?
It should keep highlight on latest option.

### What is actually happening?
It open/highlight on previous (Asia) group.

**Comment by iendeavor** [comment]
@kooriookami  Is this resolved?

**Comment by kooriookami** [comment]
It is similar to #2063
