### ISSUE TITLE
[Bug Report] Select dropdown in popover

### ISSUE THREAD

**Issue by CaiWenlie** [element-plus/element-plus#1978]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Google Chrome 90.0.4430.93（正式版本） （64 位）

### Vue version
3.1.0-beta.2

### Reproduction Link
https://codesandbox.io/s/naughty-satoshi-f8os5?file=/src/App.vue

### Steps to reproduce
1. open select options
2. click anywhere in select dropdown
3. will see the popover hiding not as expected

### What is Expected?
popover not hide when click in select dropdown

### What is actually happening?
 popover hided not as expected

**Comment by iendeavor** [comment]
I personally think this is not the Select bug, you can try this:

https://codesandbox.io/s/element-plus-nested-popover-8ldxi?file=/src/components/HelloWorld.vue

**Comment by kooriookami** [comment]
> I personally think this is not the Select bug, you can try this:
> 
> https://codesandbox.io/s/element-plus-nested-popover-8ldxi?file=/src/components/HelloWorld.vue

Yes, you need to deal with it yourself.
