### ISSUE TITLE
[bug report] document introduces internationalization configuration error on demand

### ISSUE THREAD

**Issue by zh1011** [element-plus/element-plus#1986]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
windows10  Chrome 90.0.4430.93

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/angry-turing-81g4e?file=/src/main.js

### Steps to reproduce
如代码所示

### What is Expected?
切换到中文

### What is actually happening?
配置了中文  但是还是英文

**Comment by sxzz** [comment]
Hi, please use `config-provider` for new, https://element-plus.org/#/zh-CN/component/config-provider.

Feel free to reopen it if you have any questions.
