### ISSUE TITLE
[Bug Report] `<el-tab-pane>` can't be wrapped

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#1989]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Win 10 / Chrome 90

### Vue version
3.1.0-beta.2

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-vy6jq?file=/src/App.vue

### Steps to reproduce
Please use the repro link.

### What is Expected?
Can be wrapped.

### What is actually happening?
Cannot be wrapped.

**Comment by wenfangdu** [comment]
@zazzaz @JeremyWuuuuu Please take a look at this 🙏🙏🙏.

**Comment by bastarder** [comment]
because we should find all el-tab-pane in tabs, i think it is not necessary to wrap el-tab-pane, you can do this

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
