### ISSUE TITLE
[Bug Report] component can't dynamic render

### ISSUE THREAD

**Issue by LiuwqGit** [element-plus/element-plus#1990]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
win7

### Vue version
3.1.0-beta.2

### Reproduction Link
https://codesandbox.io/s/blissful-germain-khgu2?file=/src/componentB.vue

### Steps to reproduce
有两个组件，组件A，组件B
组件B中，使用render函数来生成组件，但是渲染 ElementPlus 组件的时候，无法正常渲染成可显示的组件。

https://codesandbox.io/s/blissful-germain-khgu2?file=/src/componentB.vue
这是 element-plus 的案例，想渲染 el-input ，但是无法成功。
![image](https://user-images.githubusercontent.com/7065327/117953563-b627a200-b348-11eb-84ea-50fd4d6aa8a4.png)

https://codesandbox.io/s/youthful-gagarin-jv7tj?file=/src/componentB.vue
这是 element-ui 的案例，可以正常渲染 el-input

### What is Expected?
正常 渲染 ElementPlus组件

### What is actually happening?
没有正常渲染 ElementPlus 组件

**Comment by kooriookami** [comment]
Use `resolveComponent` to resolve a component.
```js
import { h, resolveComponent } from "vue";
export default {
  render() {
    return h("div", [
      h("input", {
        type: "submit",
        value: "submit",
      }),
      h("input", {
        type: "checkbox",
        checked: true,
      }),
      h(resolveComponent("el-input"), {
        placeholder: "请输入内容",
      }),
    ]);
  },
};
```

**Comment by LiuwqGit** [comment]
> Use `resolveComponent` to resolve a component.
> 
> ```js
> import { h, resolveComponent } from "vue";
> export default {
>   render() {
>     return h("div", [
>       h("input", {
>         type: "submit",
>         value: "submit",
>       }),
>       h("input", {
>         type: "checkbox",
>         checked: true,
>       }),
>       h(resolveComponent("el-input"), {
>         placeholder: "请输入内容",
>       }),
>     ]);
>   },
> };
> ```

谢谢，可以正常渲染了。
