### ISSUE TITLE
[Bug Report] elememt-plus  vue-i18n@next   The introduction of component language on demand has always been in English

### ISSUE THREAD

**Issue by octshen** [element-plus/element-plus#1994]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
chrom

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-d1exx?file=/src/main.js:328-340

### Steps to reproduce
直接展示就是英文

### What is Expected?
跟随本地语言切换 组件语言进行切换

### What is actually happening?
本地语言切换 组件还是英文

**Comment by JserWang** [comment]
@octshen 
Hi,在你的codesandbox 中，你可以尝试做如下改动即可生效：

``` js
import ElPagination from "element-plus/lib/el-pagination";
```

这个问题产生的根本原因在于，如果引用组件是通过`import { } from 'element-plus'`的方式，那这些组件将从根目录的`index.esm.js` 中引用，而设置语言的代码却是在`element-plus/lib` 中，他们所处的环境不同，导致实现中的 [i18nHandler](https://github.com/element-plus/element-plus/blob/dev/packages/locale/index.ts#L16) 没有取到值。
所以，这里需要保证让引用组件与设置语言的环境一致.

**Comment by octshen** [comment]
@JserWang 
es/index.js 的导出方法中把 locale文件中的  i18nHandler方法加上 是不是就可以不修改组件的引用方式了

**Comment by callmesoul** [comment]
@octshen 解决了么？
我把import { } from 'element-plus' 改成  import something from 'element-plus/lib/*'
但是样式没了
