### ISSUE TITLE
[feature request] shuttle box add form shuttle box

### ISSUE THREAD

**Issue by Hu-Jixiang** [element-plus/element-plus#1995]
### Existing Component
是

### Component Name
el-transfer

### Description
穿梭框目前没有表格穿梭框，可考虑添加一个

**Comment by Hu-Jixiang** [comment]
add table shuttle box

**Comment by sxzz** [comment]
Can you describe it in more detail.
Currently we have no time to implement this feature. If someone can post a pr, I will handle it.
