### ISSUE TITLE
使用 cdn 的方式引用，然后在使用 el-table 时候，row-click 事件不起作用，但是我换成npm引入的方式时候，是没有任何问题的，不知道到具体是怎么回事

### ISSUE THREAD

**Issue by wzXJF** [element-plus/element-plus#2009]

**Comment by wzXJF** [comment]
<link rel="stylesheet" href="https://unpkg.com/element-plus/lib/theme-chalk/index.css">

<script src="https://unpkg.com/element-plus/lib/index.full.js"></script>

**Comment by JeremyWuuuuu** [comment]
Feel free to reopen when you can submit a reproducible code.

**Comment by hanx316** [comment]
https://codepen.io/hanx316/pen/qBrmmzp try this. it's ok.
