### ISSUE TITLE
[Feature request] Toggle menu Top bar

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#2012]
[https://element-plus.org/#/en-US/component/menu](https://element-plus.org/#/en-US/component/menu)

Can you please add toggle menu like in
[https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_topnav](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_topnav)
So it would be responsive to mobile ?

**Comment by JeremyWuuuuu** [comment]
Sorry for the late response, but I think ElementPlus should focus on desktop only for a relatively long period of time. We are branded to be a desktop UI library. If you need that feature, you can use resize observer combining `el-menu` to do the trick.
E.g.

```ts
// I am guessing that you want this feature whenever the main frame's width gets changed
const observer = new ResizeObserver(() => {
   // handles the resize event
})
observer.observe(window)
```

![image](https://user-images.githubusercontent.com/15975785/119426669-36cca200-bd3c-11eb-9f32-d63080d1833b.png)
