### ISSUE TITLE
In TSX mode, the elformitem rules pattern attribute is invalid, and the validator callback value parameter has no valid value

### ISSUE THREAD

**Issue by mikepxq** [element-plus/element-plus#2015]
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
window/edge chrome 版本

### Vue version
3.0.5

### Reproduction Link
https://github.com/mikepxq/vue-element-template

### Steps to reproduce
1.clone https://github.com/mikepxq/vue-element-template
2.切换到 v1-dev 分支
3.npm install    npm run dev
4.角色管理页面
//线上已经用其他方式，规避bug 你们可以使用下面代码重现
<ElForm inline v-model={form} class="m-form" ref={refForm}>
          <ElFormItem
            label="角色名称"
            prop="roleName"
            rules={[
              {
                validator: (rule, value) => {
                //这里value 是undef
                  return pattern.zh_alpha_num__.test(form.roleName);
                },
              //async-validator  pattern 属性无效
              //pattern: zh_alpha_num__
                message: "请输入中文，英文字母和数字及下划线",
              },
            ]}>
            <ElInput placeholder="请输入角色名称" v-model={form.roleName}></ElInput>
          </ElFormItem>
        </ElForm>

### What is Expected?
tsx 模式下 pattern 有效
 validator 回调函数 value 参数有效

### What is actually happening?
tsx 模式下 pattern 无效
 validator 回调函数 value 参数为undefined

**Comment by JeremyWuuuuu** [comment]
I'll go investigating this issue, will let you know once I had conclusion.

**Comment by JeremyWuuuuu** [comment]
So I did clone your repo to my computer. Then with the command to bootstrap the project. In your code:

```ts
{
      path: "/console/role-manage",
      component: () => import("@/views/role/manage.vue"),
      meta: {
        icon: "location",
        title: "角色管理",
        // auths: ["superAdmin0"], //test
        //  hidden: true
      },
      // children: [
      //   {
      //     path: "/console/role-manage/create",
      //     component: () => import("@/views/role/manage.vue"),
      //     meta: {
      //       title: "新增角色",
      //     },
      //   },
      // ],
    },
```

but there was absolutely no folder called `role` under `views/` for the three branches you had `master` `v1-dev` , `v1`.

I think your demo code is invalid. Please verify that then reopen this issue.
