### ISSUE TITLE
My project will have mousewheel passive warning????

### ISSUE THREAD

**Issue by yang867381349** [element-plus/element-plus#2016]
我的项目在使用了element-plus ^1.0.2-beta.33
出现了警告的问题。具体警告如下：

### 警告：
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

但我都在网上查了好久都说是element-ui 导致的。但我不确定？ element-plus 还会不会存在这个问题？

所以我只能发布小小的问题来咨询一下各位是如何解决的？

我已使用     $ **npm install default-passive-events** 给出的基本解决方法。可未能解决我现在的问题。

**Comment by JeremyWuuuuu** [comment]
Which component?

**Comment by nabaonan** [comment]
同样有这个问题，我用了default-passive-events插件，其他组件库比如antd vue都已经没有了，但是element-plus依然存在

**Comment by yang867381349** [comment]
el-table 这个组件存在的问题？

**Comment by yang867381349** [comment]
> 哪个组件？

el-table 这个组件存在的问题？

**Comment by cozygCN** [comment]
使用el-table组件时出现相同问题，使用default-passive-events插件无效，在el-table可以水平滚动时出现warning
same problem with el-table component, 'default-passive-events' plugin not working, and chrome warning when el-table can scroll horizontally

**Comment by yys-0505** [comment]
![image](https://user-images.githubusercontent.com/11680854/122856777-f74ca200-d349-11eb-90f0-01f49a7bf14d.png)
Same issue under Chrome, related to el-table.

**Comment by linuxzha** [comment]
Same issue on el-table

**Comment by coniferchina** [comment]
问题同上

**Comment by mxp131011** [comment]
我也有相同问题

**Comment by jiangjunfeng98** [comment]
Can fix this problem? Maybe just change the El table  addEventListener

**Comment by jiangjunfeng98** [comment]
> Hello @yang867381349. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> 
> 你好 @yang867381349, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。

https://codepen.io/510879374/pen/RwgbXXg

![image](https://user-images.githubusercontent.com/12987428/130418307-9644b388-cccf-49e6-98f1-c71e07e62079.png)


Google Chrome
版本 92.0.4515.131（正式版本） (x86_64)

**Comment by mxp131011** [comment]
@jiangjunfeng98 
![image](https://user-images.githubusercontent.com/31055355/131290931-7b409f5f-77f9-46fa-8c53-389750554b37.png)
在官方例子中复现，只要有固定列就会有此问题，用的是：Microsoft Edge

**Comment by jiangjunfeng98** [comment]
> @jiangjunfeng98
> ![image](https://user-images.githubusercontent.com/31055355/131290931-7b409f5f-77f9-46fa-8c53-389750554b37.png)
> 在官方例子中复现，只要有固定列就会有此问题，用的是：Microsoft Edge

实际使用都有，官网上的demo 正常，不知道他们是不是做了什么处理

macOS 11.5.2 
Google Chrome 版本 92.0.4515.131（正式版本） (x86_64)

**Comment by DFNJKD-98** [comment]
- element-plus 1.1.0-beta.15 依旧存在这样的问题（default-passive-events插件也没有效果）
- Element plus 1.1.0-beta.15 still has this problem (the default passive events plug-in has no effect)

**Comment by HaoAurora** [comment]
也遇到了同样的问题，请问有最终解决方案了吗

**Comment by atpsoul** [comment]
我这边也有这样的问题。
这是官方文档跳转到playground的例子，打开控制台，f5刷新一下就会出现。
![el-table相关问题](https://user-images.githubusercontent.com/9943065/147998747-e2247158-532b-4ee0-a641-f1aeb4519685.png)

**Comment by mayangyang1** [comment]
一样的问题

**Comment by lsguang0** [comment]
Why not fix it？？？？？

**Comment by JeremyWuuuuu** [comment]
@lsguang0 PR is always welcomed

**Comment by FarAwayShe** [comment]
有解决方法吗

**Comment by song-yan-ru-mo** [comment]
> [Violation]Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

一年了 还没修复吗...
