### ISSUE TITLE
[Bug Report] Incorrect placement of el-select #prefix when inside el-collapse-item

### ISSUE THREAD

**Issue by JaconsMorais** [element-plus/element-plus#2023]
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Win 10 / Chrome v. 90.0.4430.212

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/jacons-morais/pen/RwpoaoO

### Steps to reproduce
If we place one el-select with prefix slot inside el-collapse > el-collapse-item the placeholder/value overlaps the prefix.

### What is Expected?
Should show prefix and then placeholder/value

### What is actually happening?
prefix and placeholder/value is at the same place

**Comment by dsqiao** [comment]
This is because the 'display' property of collapse item content is none when the page is first rendered. So we cannot get the width of the prefix (because it is not rendered). 

in select.vue, prefix.getBoundingClientRect().width returns zero, so the paddingLeft is set to 30px.
```
const prefix = reference.value.$el.querySelector('.el-input__prefix')
prefixWidth.value = Math.max(prefix.getBoundingClientRect().width + 5, 30)
if (states.prefixWidth) {
     input.style.paddingLeft = `${Math.max(states.prefixWidth, 30)}px`
}
```
but i don't know how to fix it.

**Comment by JaconsMorais** [comment]
Hi, thanks for your response.

What if select component navigates up in components tree until he finds one component with valid width?
collapse components has width in most of cases, just height is unknow or can change.

**Comment by dsqiao** [comment]
But the prefix width has nothing to do with the collapse item width, it only depends on the string you entered.
You may set the collapse item to active at first place, so that the select component can be rendered correctly.
https://codepen.io/dsqiao/pen/GRWWXyE

**Comment by JaconsMorais** [comment]
Ah ok, I understand, what if we could set some specific width for prefix?

**Comment by JaconsMorais** [comment]
I'm still having this issue...
Why when I use input prefix inside collapse everything works, but when I use select prefix the padding-left is wong? See this pic.
I need to find a way to reach input element created by element-plus, so I could set padding-left manually, there is a way to do this?
![image](https://user-images.githubusercontent.com/6156243/125864539-80bed156-e26c-4098-8496-c9ea35c8728d.png)
