### ISSUE TITLE
[Bug Report] Table component header and column misalignment

### ISSUE THREAD

**Issue by lainbo** [element-plus/element-plus#2024]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Win 10 / Chrome v. 90.0.818.62

### Vue version
3.0.10

### Reproduction Link
https://codepen.io/lainbojc/pen/MWpbeYG

### Steps to reproduce
In the case of different screen resolutions and Windows system scaling may appear in the table header and column misalignment, currently known in 2160 * 1440 resolution, Windows system 150% scaling, 2880 * 1800 resolution, Windows system 175% scaling will appear this problem, perhaps these screen sizes are not 16:9 reasons

### What is Expected?
Table headers can be aligned with columns

### What is actually happening?
The table header is not aligned with the column, and causes a bug in dragging the column width, you can drag out an empty column

**Comment by sxzz** [comment]
Hi.
The Table component will be refactored, so this issue is temporarily closed, and feel free to reopen an issue if you have any questions.
