### ISSUE TITLE
[Feature Request] onPick callback for datepicker

### ISSUE THREAD

**Issue by YNWA** [element-plus/element-plus#2027]
### Existing Component
Yes

### Component Name
ElDatePicker

### Description
Element UI supports `onPick` callback that triggers when the selected date is changed. 
https://element.eleme.io/#/en-US/component/date-picker#picker-options

Element Plus seems missing this feature. Would be nice to have it back. Is this possible?

**Comment by iamkun** [comment]
Duplicate of #2627
