### ISSUE TITLE
[bug report] when you enter a date in the date range control, the callback value is not the correct date object

### ISSUE THREAD

**Issue by NoaAlan** [element-plus/element-plus#2028]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Chorme

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/NoaAlan/pen/RwpoOXY

### Steps to reproduce
当自行在日期范围控件中输入日期时，回调值不是正确的date对象

### What is Expected?
返回正确的Date对象

### What is actually happening?
返回值：{"$L":"en","$u":"__vue_devtool_undefined__","$d":"[native Date Fri Jan 01 2021 00:00:00 GMT 0800 (中国标准时间)]","$y":2021,"$M":0,"$D":1,"$W":5,"$H":0,"$m":0,"$s":0,"$ms":0}

**Comment by kooriookami** [comment]
It's correct, you can refer to UTC.
