### ISSUE TITLE
[bug report] Select selector, searchable function. After the change event, the input is not blur processed

### ISSUE THREAD

**Issue by JensenYao** [element-plus/element-plus#2029]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
window10/Google Chrome 版本 90.0.4430.212（正式版本） （64 位）

### Vue version
3.1.0-beta.3

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
Select 选择器，可搜索功能，change事件后，input 没有做blur处理

### What is Expected?
Select 选择器，可搜索功能，change事件后，input 失去焦点

### What is actually happening?
Select 选择器，可搜索功能，change事件后，input 没有进行blur处理

**Comment by msidolphin** [comment]
you can use @visible-chage instead blur event
