### ISSUE TITLE
[Feature Request] how to use the el-form method validate with Composition API (JS), the current code example is still written with Options API

### ISSUE THREAD

**Issue by victor-chauzov** [element-plus/element-plus#2031]
### Existing Component
Yes

### Component Name
el-form

### Description
I wrote a <el-form ... > using the Options API - it works
 (I did everything exactly as in the examples https://element-plus.org/#/en-US/component/form)

But there are difficulties when translating to the Composition API
can't use validate, resetFields ...   see code example with Validation

in the example for the Options API
         this. $ refs [formName] .validate ((valid) => {
         this. $ refs [formName] .resetFields ();

how to do the same for the Composition API in JS (but not TS. I don't own it)

Thanks in advance for the advice

**Comment by victor-chauzov** [comment]
i find exampl, but it don't work (( https://penueling.com/%E6%8A%80%E8%A1%93%E7%AD%86%E8%A8%98/vue3-elementui-plus-%E8%A1%A8%E5%96%AE%E9%A9%97%E8%AD%89%E4%BD%BF%E7%94%A8-refs/

**Comment by dybxin** [comment]
@victor-chauzov i'm also want to ask how to use the el-form method validate with Composition API (JS)?Have you solved it?

**Comment by AlekseyMalakhov** [comment]
Here is my example how to use validated form with composition API
```
<template>
    <el-form :model="state.login" :rules="state.rules" ref="loginForm">
            <el-form-item label="Username" prop="name">
                <el-input v-model="state.login.name" @keyup.enter="() => submitForm()"></el-input>
            </el-form-item>
            <el-form-item label="Password" prop="password">
                <el-input v-model="state.login.password" @keyup.enter="() => submitForm()"></el-input>
            </el-form-item>

            <el-row>
                <el-button type="primary" @click="submitForm()">Login</el-button>
                <el-button @click="cancel()">Cancel</el-button>
            </el-row>
        </el-form>    
</template>

<script>
import { ref, reactive } from '@vue/reactivity';

export default {
    setup() {
        const state = reactive({
            login: {
                name: "",
                password: "",
            },
            rules: {
                name: [
                    {required: true, message: "Please, enter username", trigger: "change"},
                ],
                password: [
                    {required: true, message: "Please, enter password", trigger: "change"},
                ],
            },
        });

        const loginForm = ref(null);

        function submitForm() {
            this.loginForm.validate(valid => {
                if (valid) {
                    //send(this.state.login);
                }
            });            
        }

        function cancel() {
            this.loginForm.resetFields();
        }

        return {
            state,
            submitForm,
            loginForm,
            cancel,
        }
    },
}
</script>

<style lang="scss">  
</style>
```

**Comment by dybxin** [comment]
@AlekseyMalakhov thanks a lot. 

correct write is replace `this.loginForm` with `loginForm.value`?

**Comment by youzizi1** [comment]
this is a example that worked for me
```
const formRef = ref(null)
const onLogin = () => {
  formRef.value.validate((valid) => {
    if (valid) {
      console.log('pass')
    } else {
      console.log('fail')
    }
  })
}
```

**Comment by victor-chauzov** [comment]
thank you, guys! I will definitely try

**Comment by lebadapetru** [comment]
can anyone confirm that it works ONLY with composition api? i removed options api with webpack from the final build and i get a `Failed to resolve component:`

**Comment by LBJDJW** [comment]
> thank you, guys! I will definitely try

`const ruleForm = ref(null)
const resetForm = (formName: string) => {
    ruleForm.value.resetFields()
}`
but ruleForm.value is null  , null.resetFields() is not my answer, how can i do it?
Object is possibly 'null'.ts(2531)
const ruleForm: any
const ruleForm: Ref<null>

**Comment by LBJDJW** [comment]
I try it successly!
`
//html
  <el-form
            :model="formClass"
            :label-position="labelPosition"
            ref="ruleForm"
        >
.......
<el-button @click="resetForm()">resetForm</el-button>
</el-form>

//script
const ruleForm = ref<InstanceType<typeof ElForm>>()
const resetForm = () => {
    // console.log(ruleForm.value)
    if (ruleForm.value) {
        ruleForm.value.resetFields()
    }
}

`
