### ISSUE TITLE
[feature request] date time range selector. The "clear" button in the selector cannot be hidden

### ISSUE THREAD

**Issue by wjw-gavin** [element-plus/element-plus#2035]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
个人理解，既然我不想用户能清空日期时间，设置了clearable=false，目前又无法通过属性去掉选择器中的“清空”按钮，那选择器里的“清空”按钮是不是就和预期冲突了呢？（虽然可以通过css类名.el-button--text控制）这样的话，是不是“清空”按钮可以和clearable共用一个属性来控制是否显示呢？
![image](https://user-images.githubusercontent.com/19986739/118960016-7179b780-b995-11eb-8e65-7b4f4dd255d3.png)

**Comment by JeremyWuuuuu** [comment]
Seems like a good suggestion, we should use `clearable` to control both of the `clear` button. cc @0song
