### ISSUE TITLE
el-dialog

### ISSUE THREAD

**Issue by lihaopeng1024** [element-plus/element-plus#2036]
<el-dialog
    id="testdialog"
    title="提示"
    v-model="dialogVisible"
    width="30%"
    >     
    <span>这是一段信息</span>
    <p><el-button type="primary" @click.stop="test3">test3</el-button ></p>
    <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">取 消</el-button>
        <el-button type="primary" @click="dialogVisible = false">确 定</el-button>
      </span>
    </template>
  </el-dialog>
![image](https://user-images.githubusercontent.com/45090081/118979956-96792500-b9ab-11eb-8a3f-99ad8697f4f2.png)

**Comment by kooriookami** [comment]
Please remove the `id` props.

**Comment by lihaopeng1024** [comment]
It has been solved successfully. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] el-dialog (#2036)





 
Please remove the id props.
