### ISSUE TITLE
[Feature Request] tree-select

### ISSUE THREAD

**Issue by chendaozhun** [element-plus/element-plus#2037]
### Existing Component
No

### Component Name
tree-select

### Description
建议增加tree-select组件

**Comment by LIUSHUAI2018** [comment]
strongly endorse

**Comment by EstebanFuentealba** [comment]
👀

**Comment by cjq02** [comment]
#878 

I found this component el-tree-select is under deveopment, but it seems to be no progress.

**Comment by iamjxc** [comment]
虽然自己能够封装, 但是整体性还是差点儿意思, 希望官方能够推出，并支持以下特性：
支持单选/多选
获得焦点自动展开下拉
清除按钮
级联选择上下级
检索过滤
弹框自适应数据宽度
延迟加载
虚拟渲染
自动展开N级

**Comment by emojiiii** [comment]
You can describe the functions you need, and we will add them as much as possible

**Comment by LIUSHUAI2018** [comment]
选择组织机构，树选择组件非常常见，众多组件库当中只有element plus没有，很让人费解

**Comment by emojiiii** [comment]
Duplicated of #6887
