### ISSUE TITLE
[bug report] El collapse value is invalid

### ISSUE THREAD

**Issue by Yusoo** [element-plus/element-plus#2039]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Microsoft Edge 90

### Vue version
3.0.11

### Reproduction Link
https://jsfiddle.net/utvm0r8o/1/

### Steps to reproduce
此组件v-model有效，但是value无效，与文档描述不同。

### What is Expected?
默认打开第一个面板

### What is actually happening?
所有面板都是关闭状态

**Comment by Pmj136** [comment]
You can use 'modelValue' to instead of 'value'

**Comment by kooriookami** [comment]
re #2044
