### ISSUE TITLE
### MessageBox

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#204]

**Comment by YuLinXi** [comment]
https://github.com/element-plus/element-plus/projects/1#card-42275921

**Comment by YuLinXi** [comment]
i do this

**Comment by JeremyWuuuuu** [comment]
@YuLinXi Did this mean that you want to take this task?

**Comment by JeremyWuuuuu** [comment]
@YuLinXi If you have any progress, please make a draft PR to us to track on. If we haven't seen any progress in 3 days, we will remove you from the assignee.

**Comment by YuLinXi** [comment]
@JeremyWuuuuu  ok

**Comment by YuLinXi** [comment]
@JeremyWuuuuu Hello, is my priority to migrate the original components and ts-type later ?

**Comment by JeremyWuuuuu** [comment]
@YuLinXi, No, you need to work on both **migration** and **type annotation** ;)

**Comment by YuLinXi** [comment]
@JeremyWuuuuu fine

**Comment by g3r4n** [comment]
I know that the Message-box component was in Element-UI, but was is the difference with Dialog ? #144 ?

**Comment by YuLinXi** [comment]
> I know that the Message-box component was in Element-UI, but what is the difference with Dialog ? #144

message-box base on dialog
