### ISSUE TITLE
[Bug Report] DatePicker value is not correct when enter a date in the date range input

### ISSUE THREAD

**Issue by tracker1999** [element-plus/element-plus#2041]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
win10/chrome

### Vue version
3.1.0-beta.3

### Reproduction Link
https://codepen.io/NoaAlan/pen/RwpoOXY

### Steps to reproduce
enter a date in the date range input
the value is
[0: f {$L: "en", $u: undefined, $d: Tue Mar 02 2021 00:00:00 GMT 0800 (中国标准时间), $y: 2021, $M: 2, …}
1: f {$L: "en", $u: undefined, $d: Sat Apr 03 2021 23:59:59 GMT 0800 (中国标准时间), $y: 2021, $M: 3, …}]

### What is Expected?
datapicker value is [0: Fri Apr 02 2021 00:00:00 GMT 0800 (中国标准时间) {}
1: Sat Apr 03 2021 23:59:59 GMT 0800 (中国标准时间) {}]

### What is actually happening?
the value is
[0: f {$L: "en", $u: undefined, $d: Tue Mar 02 2021 00:00:00 GMT 0800 (中国标准时间), $y: 2021, $M: 2, …}
1: f {$L: "en", $u: undefined, $d: Sat Apr 03 2021 23:59:59 GMT 0800 (中国标准时间), $y: 2021, $M: 3, …}]

![datepicker](https://user-images.githubusercontent.com/6487670/119289363-0a058580-bc7d-11eb-8f22-d584b5dfeaaa.gif)

**Comment by msidolphin** [comment]
I suggest use value-format like element-ui @JeremyWuuuuu 
https://element.eleme.cn/#/zh-CN/component/date-picker#ri-qi-ge-shi

**Comment by sxzz** [comment]
It seems that this issue has been fixed.
PR: #2120
