### ISSUE TITLE
[bug report] the checkbox component cannot use the check property to control the state

### ISSUE THREAD

**Issue by lchtao26** [element-plus/element-plus#2046]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
chrome85

### Vue version
3.1.0-beta.3

### Reproduction Link
https://codepen.io/lchtao26/pen/eYvvqPw

### Steps to reproduce
<el-checkbox :checked="true">不能被checked属性改变状态</el-checkbox>

### What is Expected?
checked属性能改变checkbox的状态

### What is actually happening?
checked属性不能改变checkbox的状态

**Comment by JeremyWuuuuu** [comment]
Yeah, all form components seem like only take `v-model` or `model-value` as input to control the form value, like radio button, checkboxes, select, etc.

**Comment by JeremyWuuuuu** [comment]
If you tried to do single binding, use `model-value` instead.

**Comment by JeremyWuuuuu** [comment]
Or maybe this is something that we can optimize with, for temporary fix, use `model-value` istead.
