### ISSUE TITLE
[Feature Request] ElTable transition-group

### ISSUE THREAD

**Issue by rogierwiertz** [element-plus/element-plus#2047]
### Existing Component
Yes

### Component Name
ElTable

### Description
Is there a way to add transitions to the ElTable component?
I can't find a way right now.

For example, change the tbody to <transition-group tag="tbody">, so it's possible to add transition effects when adding data / using expandable rows.

**Comment by JeremyWuuuuu** [comment]
I don't think there were any features to support that.

**Comment by JeremyWuuuuu** [comment]
Might be a good way to enhance the component in the future.
