### ISSUE TITLE
[Bug Report] inpu with jsx  blur not work

### ISSUE THREAD

**Issue by duansheli** [element-plus/element-plus#2053]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
edge 90

### Vue version
3.0.11

### Reproduction Link
https://github.com/duansheli/vue-ep-bug

### Steps to reproduce
在输入框中输入任意文字 

### What is Expected?
正常情况下 
输入任意文字 触发 change 事件
失去焦点 触发blur

### What is actually happening?
事实是 
输入啥子 都触发 blur

**Comment by JeremyWuuuuu** [comment]
Dude, you need to know how jsx works.

In template when you type

```vue
<el-input @blur="invocation(params)" />
```
will be compiled to:

```ts

h(resolveComponent('el-input', {
  onInput: (_cache[0] || _cache[0] = () => invocation(params)),
})

```

in jsx refer to your code

> 
```jsx
export default defineComponent({
  setup() {
    /**
     * 只要修改就会触发
     * 
     */
    const sname = ref("bad2");

    return () => (
      <>
      <h1>任意输入，两个事件都会触发</h1>
      <el-form>
        <el-form-item label="test-bad">
          // this is invocation expression, you pass the result of `onblur(sname.value)` to <el-input />
         // use blur={() => onblur(sname.value)} instead 
          <el-input v-model={sname.value} blur={onblur(sname.value)}
          input={input(sname.value)}
          change={onchange(sname.value)} />
        </el-form-item>
      </el-form>
      <h1>blur 正常， 修改时change 不会触发， 修改后失去焦点change会被触发</h1>
      <input type="text" value={sname.value} 
          onChange={()=>onchange(sname.value)} 
          onBlur={()=>onblur(sname.value)} 
           /> 
      </>
    );
  },
});
```

**Comment by JeremyWuuuuu** [comment]
Please double check your code so that we can spend less time on solving issues are not caused by us to have more time focusing on this project in order to make it better.

**Comment by duansheli** [comment]
@JeremyWuuuuu 

改成这样后
```
 <el-input v-model={sname.value} 
          blur={() => onblur(sname.value)}
          input={() =>input(sname.value)}
          change={() => onchange(sname.value)}
            />
```
输入任意字符， 离开焦点 
啥也不打印了

那这样是不是该提交一个 事件无法触发的bug？？

**Comment by JeremyWuuuuu** [comment]
For events, please use `onEventName` to get the correctness, I am not your private vue teacher, please go read the documentation first.
FYI: [jsx-next](https://github.com/vuejs/jsx-next)

**Comment by duansheli** [comment]
@JeremyWuuuuu 
 `blur={onblur(sname.value)}` 是错误的写法 
`blur={() => onblur(sname.value)}` 是正确的写法

错误的写法， 要么编译报错，要么就被忽略了不被执行 
此处 `blur={onblur(sname.value)} ` 错误的写法  却被触发了

那从这个角度看，算是bug吗？

**Comment by JeremyWuuuuu** [comment]
大哥，能不能搞清楚什么叫触发了，你输入了Vue不更新吗？更新不render吗？你render里面每次都调这个方法能不触发吗？

**Comment by JeremyWuuuuu** [comment]
哪个角度来看都是你自己的问题，能不能好好去看看文档啊？提 issue 我帮你解答了，你要变着法儿各种角度来看这是不是个 bug，我每天花时间来回这种 issue，这个项目还做不做了？

**Comment by JeremyWuuuuu** [comment]
你连 jsx 的基础知识都不知道就开始问是不是 bug，能不能去好好学习一下，没有说一定要做什么贡献，issue 如果真的自己查过是 element-plus 的问题，我们肯定会修，你这完全就跟这个项目无关，甚至跟 Vue 都没多少关系，什么错误不错误的写法呢？
`onblur(sname.value)` 就是一个函数调用，错在哪里了？
`() => onblur(sname.value)` 是一个函数，又错在哪里了？
你传给方法的 event handler 要加 on 在前面，你错在哪里了？

你 setup 返回了一个 render 函数，每次有更新 vue 都会去调用你的那个方法，你自己的方法里又调用了一个函数，他能不每次都调用吗？

我们确实没有在文档上放怎么写 jsx，但我觉得这个问题并不是我们的问题，template 减少您的心智负担您怎么简单怎么用，非要用 jsx 的话就去看看 jsx 的文档看看怎么写 jsx。
