### ISSUE TITLE
[Bug Report] Sass code duplication

### ISSUE THREAD

**Issue by Oleksii14** [element-plus/element-plus#2054]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Mac OS BigSur, Chrome 90.0.4430.212

### Vue version
3.0.11

### Reproduction Link
https://github.com/Oleksii14/element-plus-scss-bug

### Steps to reproduce
Hello!
I have noticed an annoying issue with scss files of element-plus.

If you're using the custom theme (see babel config file in the repo), the styles are being duplicated. When I checked element scss files, I noticed that different scss files may import the same file many times. I am attaching the screenshoots

### What is Expected?
Css is not being duplicated

### What is actually happening?
element plus scss files may import the same scss file many times, that causes code duplication

![image](https://user-images.githubusercontent.com/36737084/119322777-a718ec00-bc86-11eb-88f9-c0593b4b960d.png)
![image](https://user-images.githubusercontent.com/36737084/119322963-ddef0200-bc86-11eb-8c44-f363b5d6553b.png)
![image](https://user-images.githubusercontent.com/36737084/119323034-ef380e80-bc86-11eb-98e9-bf1b359aa3a8.png)

**Comment by JeremyWuuuuu** [comment]
I think this is only when you are in `dev` mode, you get duplications and if you are in `prod` mode, your bundler like `webpack`, `rollup` will resolve that for you if you have introduced `terser` like plugins, you will not get the duplicated output.
In case that you were interested in why we were doing this:

We did this for stand alone usage when user who did not want to introduce the whole package into their code base, and they want have full styled component, they can use the `babel-import-plugin` which introduces the `css/scss` file along with the component. And some components depended on others like `input-number` in your case.

**Comment by Oleksii14** [comment]
Thanks for the reply. But anyway, can we avoid those duplications in the dev mode? Because `yarn serve` is building much styles, it increases the bundling time for the development

**Comment by JeremyWuuuuu** [comment]
You can run a production build see if you get duplications. 

You can hold the css minify plugin as a variable. Try to build your project in production mode with the plugin given or without. See if there were any size changes.

**Comment by JeremyWuuuuu** [comment]
> Thanks for the reply. But anyway, can we avoid those duplications in the dev mode? Because `yarn serve` is building much styles, it increases the bundling time for the development

I think we could, the easiest way to do that is that you configure your bundler to minify css code in development mode, but that's not suggested to do so because it will cause you more time to debug your code. I think adding up these styles won't  cause any overheads for your build process though. You can try building your code with `esbuild` if you think your build process takes forever. (They also offers rollup plugin for users who wants to try `esbuild`).

**Comment by Oleksii14** [comment]
Thanks for the help! My issue is resolved then

**Comment by JeremyWuuuuu** [comment]
FYI:
[esbuild](https://github.com/evanw/esbuild)
[esbuild-rollup-plugin](https://github.com/egoist/rollup-plugin-esbuild)

Hope these links could help you. ;)
