### ISSUE TITLE
[bug report] El cascade size = "mini", filterable = true, and then set multiple = true of props to 34px. If there is a problem, it should be 28px of mini

### ISSUE THREAD

**Issue by jinrongni** [element-plus/element-plus#2061]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
win10专业版20H2

### Vue version
3.1.0-beta.4

### Reproduction Link
https://codesandbox.io/s/little-currying-50nnq?file=/src/App.vue

### Steps to reproduce
打开链接就能看到
cascader设置以下属性 size="mini" , filterable=true 再设置 props 的 multiple=true 

### What is Expected?
展示mini的高度28px

### What is actually happening?
默认34px

**Comment by JeremyWuuuuu** [comment]
Seems to be a problem. Thanks for submitting this issue, I will have someone to fix this in the next version.
Seems to me that the inner input got size of 28px. But the container box is bigger than that.

I also go double check with v2.15.1, the appearance looks the same to `element-plus`, which I think it could be a common bug.

![Xnip2021-05-25_14-30-39](https://user-images.githubusercontent.com/15975785/119449899-caff2f00-bd65-11eb-99bd-37698aa57b44.jpg)

The reason behind this is that when you got `filterable` enabled. You'll get one more input element than `non-filterable` mode.

![Xnip2021-05-25_14-35-26](https://user-images.githubusercontent.com/15975785/119450445-76a87f00-bd66-11eb-81d5-6953de54e8ff.jpg)
