### ISSUE TITLE
[bug report] [El cascade] Select carton

### ISSUE THREAD

**Issue by jinrongni** [element-plus/element-plus#2063]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
win10 专业版20H2/edge 90.0.818.66

### Vue version
3.1.0-beta.4

### Reproduction Link
https://codesandbox.io/s/billowing-night-9pzkt?file=/src/App.vue

### Steps to reproduce
打开codesadbox连接选中任意一个年份
不知道是不是写法导致的，因为有场景需要这样写，方便点，按理说应该不会导致这个问题

### What is Expected?
很卡

### What is actually happening?
不卡

**Comment by jinrongni** [comment]
最新复现ademo: https://codesandbox.io/s/wonderful-mendeleev-7bsmc?file=/src/App.vue

![image](https://user-images.githubusercontent.com/41502851/119494975-7aeb9100-bd94-11eb-83fb-77a5190defac.png)

**Comment by kooriookami** [comment]
Fixed.
