### ISSUE TITLE
Can input? Textarea provide a property to set textarea style directly?

### ISSUE THREAD

**Issue by gcclll** [element-plus/element-plus#2068]
```js
h(E.ElInput, {
   type: 'textarea',
   placeholder: '测试。。。。',
   modelValue: word.text,
   onInput: function(val) {
      word.text = val;
  },
  style: {
     lineHeight: word.lineHeight,
     fontSize: word.fontSize + 'px',
     color: word.color
   }
})
```
需求场景：想做个简易的文字编辑组件，希望文字修改、颜色啊什么的能直接同步的体现在下面的 textarea 里面。
![](http://qiniu.ii6g.com/img/20210525193304.png)

但是在直接使用 api 的时候，发现怎么也不能直接修改 textarea 标签的样式，传入的 style 只是作用在外层的 div 上，看源码有个 `textareaStyle` 属性虽然是直接作用于 `textarea` 但并没有暴露出来。

使用 style  有些属性还是起不了作用(比如：颜色)，希望有个属性可以暴露出来直接修改`textarea` 的样式。

**Comment by JeremyWuuuuu** [comment]
Indeed, I see why this is happening since we have made the inheritance of the component impossible with this flag:
![image](https://user-images.githubusercontent.com/15975785/119791770-b490d900-bf07-11eb-9f9e-6de7bb7476ee.png)

We can provide an additional API to do that. Do you want to do that?

**Comment by Ryan2128** [comment]
> Indeed, I see why this is happening since we have made the inheritance of the component impossible with this flag:
> ![image](https://user-images.githubusercontent.com/15975785/119791770-b490d900-bf07-11eb-9f9e-6de7bb7476ee.png)
> 
> We can provide an additional API to do that. Do you want to do that?

If no one does it, I can do it.
