### ISSUE TITLE
[Bug Report] Transition not working

### ISSUE THREAD

**Issue by logustra** [element-plus/element-plus#2069]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
Google Chrome 90.0.4430.212

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/s/vivu-in9p2?file=/src/components/molecules/VFormItem/vformItem.vue

### Steps to reproduce
- type something in the form
- delete text that you already type
- the error message will show up

### What is Expected?
the error message shows up with a transition

### What is actually happening?
the error message does not show up with a transition

### Note
I'm using on-demand element-plus

**Comment by JeremyWuuuuu** [comment]
The link you provided is not available which I don't know why it says:
![image](https://user-images.githubusercontent.com/15975785/119785746-12222700-bf02-11eb-9517-0e95c20f7573.png)

So I went straight to your repo and checked it out.
Basically you were doing the same thing that `ElFormItem` did once you can check it out here:
You provided an error slot:
https://github.com/logustra/vivu/blob/master/src/components/molecules/VFormItem/vformItem.vue#L8
ElementPlus ElFormItem also provided this feature:
https://github.com/element-plus/element-plus/blob/dev/packages/form/src/form-item.vue#L21

You can see that they are redundant. You may pass `error` as props to `ElFormItem` to display the validation message.

**Comment by JeremyWuuuuu** [comment]
You might want to check out that if you have the `transitions.scss` imported in to the project. This could be the root cause of your issue.

**Comment by logustra** [comment]
> The link you provided is not available which I don't know why it says:
> ![image](https://user-images.githubusercontent.com/15975785/119785746-12222700-bf02-11eb-9517-0e95c20f7573.png)
> 
> So I went straight to your repo and checked it out.
> Basically you were doing the same thing that `ElFormItem` did once you can check it out here:
> You provided an error slot:
> https://github.com/logustra/vivu/blob/master/src/components/molecules/VFormItem/vformItem.vue#L8
> ElementPlus ElFormItem also provided this feature:
> https://github.com/element-plus/element-plus/blob/dev/packages/form/src/form-item.vue#L21
> 
> You can see that they are redundant. You may pass `error` as props to `ElFormItem` to display the validation message.

I'm using `vuelidate` for validation that why I'm not using `ElFormItem `

**Comment by logustra** [comment]
> You might want to check out that if you have the `transitions.scss` imported in to the project. This could be the root cause of your issue.

Yea, I guess that also
but how do I make sure the `transitions.scss` already imported or not
coz I saw there's no `ElTransition` component, there's only `ElCollapseTransition`

**Comment by logustra** [comment]
@JeremyWuuuuu 
I try to import it manually and it works

```
import 'element-plus/packages/theme-chalk/src/common/transition.scss'
```

I only use `el-zoom-in-top` so the transition that not used will be imported also, can we make an on-demand component for this one also?
