### ISSUE TITLE
[Feature Request] Is there a demo corresponding to vue3?

### ISSUE THREAD

**Issue by oaifshdfaseo** [element-plus/element-plus#2071]
### Existing Component
No

### Component Name
Documentation

### Description
Is there a demo corresponding to vue3,Now the documents are all vue2

**Comment by JeremyWuuuuu** [comment]
I don't quite get it. The project is all composition API based, but how to use the components is essentially the same like Vue2 or ElementUI, how you implement your component has nothing to do with ElementPlus, if you have any question about how to write `Vue3`, you should go visiting [v3.vuejs.org](https://v3.vuejs.org) instead.
