### ISSUE TITLE
[Bug Report] el-row has display:flex style without type="flex"

### ISSUE THREAD

**Issue by Feng-paiVen** [element-plus/element-plus#2075]
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
win 10 / 86.0.4240.198

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/paiwen/pen/eYvERNp

### Steps to reproduce
Check that the parent of the test element does not declare type="flex", but has display="flex" effect, resulting in the test element inherits from the parent highly

### What is Expected?
display: flex is only available if type="flex"

### What is actually happening?
El-row will also have display: flex without type="flex"

**Comment by kooriookami** [comment]
Yes, the default style uses `flex`.
