### ISSUE TITLE
The style of the home page of the official website is misplaced.

### ISSUE THREAD

**Issue by geekLeopoldFitz** [element-plus/element-plus#209]
![image](https://user-images.githubusercontent.com/15906192/91251728-9df9fd80-e78e-11ea-8dfb-fa2e9ea851c5.png)
At the same time, is this project based on community?

**Comment by zazzaz** [comment]
That is because the `el-select` component is not ready yet. And will be avaliable soon

**Comment by JeremyWuuuuu** [comment]
Hi, the front page is not our highest priority right now, and this is as @zazzaz said, `el-select` is an ongoing component. I'm closing this issue.
