### ISSUE TITLE
[Feature Request] el-popper could use the `$--border-radius-base` variable

### ISSUE THREAD

**Issue by hyvyys** [element-plus/element-plus#2094]
### Existing Component
Yes

### Component Name
popper

### Description
el-popper currently has `border-radius` hard-coded to `4px`, instead of being bound to `$--border-radius-base` (which is also by default `4px`). Seems like an omission.

**Comment by bastarder** [comment]
cool! pr welcome!

**Comment by JeremyWuuuuu** [comment]
Whoops, I thought I merged this before new release, seems like we didn't update that in `beta46`, this will be queued in `beta47`. Sorry for kept you waiting. We are expecting a new release at Jun 4. GMT + 08:00
