### ISSUE TITLE
[Feature Request] How to tell el-popover to reposition itself when popover content size changes?

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#2103]
### Existing Component
Yes

### Component Name
el-popover

### Description
https://element-plus.org/#/en-US/component/popover

After a popover opens it doesn't seem to recalculate its top/left position when the content changes size.

```
<el-popover placement="top-end" trigger="hover">
   <template #reference>
      <el-button>Hover to activate</el-button>
    </template>
    <div :style="{ width: width + 'px', height: height + 'px' }">Some div</div>
</el-popover>
```

In this example if I change the width/height of the div after el-popper shows, it doesn't adjust to correct its position. Is there a way to tell the popover to reposition itself manually?

**Comment by bastarder** [comment]
there is no placement name `to-right`, may be you want `top-end`, try this?

**Comment by Giwayume** [comment]
My bad if I remembered the placement wrong, the position used isn't the problem. I just need a way to tell to reposition itself because it's not always detecting when it should be repositioned automatically.

**Comment by Giwayume** [comment]
@kooriookami Is that a "no this isn't possible, and we don't intend to implement"? I'm confused why this was closed.

**Comment by kooriookami** [comment]
> @kooriookami Is that a "no this isn't possible, and we don't intend to implement"? I'm confused why this was closed.

You may refer to https://popper.js.org/documentation.html, `popover` is based on `popper`.
