### ISSUE TITLE
[bug report] lazy load echo problem.

### ISSUE THREAD

**Issue by qinpeip** [element-plus/element-plus#2106]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
mac OS

### Vue version
3.1.0-beta.6

### Reproduction Link
https://codesandbox.io/s/long-dawn-vnmjm?file=/src/App.vue

### Steps to reproduce
业务场景：在编辑的时候需要回显选中的数据。
1. 因为设置了懒加载，所以我在回显的时候需要手动把选中的二级菜单数据加入到一级菜单中。
 2.但是这就导致了我在点击一级菜单的时候，不会在加载二级菜单的数据了（只加载了已选中的数据，没有加载全部二级数据），同时我点击其他的一级菜单，也没有加载该菜单下的二级数据。

### What is Expected?
希望能够加载全部的二级数据。

### What is actually happening?
没有加载子级菜单的全部数据，并且点击其他的一级菜单也没有加载子级菜单的数据。

**Comment by Wynnfan** [comment]
没复现，我点击0-1勾选  再点击其他的一级菜单 是加载了对应的二级菜单

**Comment by qinpeip** [comment]
@Wynnfan 
您看下现在激活的是第三个一级菜单，但是没有展开对应的二级菜单。
![image](https://user-images.githubusercontent.com/25759354/120993755-707abf80-c7b6-11eb-9c39-1f1bdebf8a80.png)

**Comment by qinpeip** [comment]
> ### Element Plus version
> 1.0.2-beta.45
> 
> ### OS/Browsers version
> mac OS
> 
> ### Vue version
> 3.1.0-beta.6
> 
> ### Reproduction Link
> https://codesandbox.io/s/long-dawn-vnmjm?file=/src/App.vue
> 
> ### Steps to reproduce
> 业务场景：在编辑的时候需要回显选中的数据。
> 
> 1. 因为设置了懒加载，所以我在回显的时候需要手动把选中的二级菜单数据加入到一级菜单中。
>    2.但是这就导致了我在点击一级菜单的时候，不会在加载二级菜单的数据了（只加载了已选中的数据，没有加载全部二级数据），同时我点击其他的一级菜单，也没有加载该菜单下的二级数据。
> 
> ### What is Expected?
> 希望能够加载全部的二级数据。
> 
> ### What is actually happening?
> 没有加载子级菜单的全部数据，并且点击其他的一级菜单也没有加载子级菜单的数据。
