### ISSUE TITLE
[Bug Report] vite hmr imort element plus failed when use the element plus version 1.0.2-beta.45

### ISSUE THREAD

**Issue by wwsheng009** [element-plus/element-plus#2107]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
linux chrome/firefox

### Vue version
3.0.11

### Reproduction Link
https://github.com/wwsheng009/element-plus-vite-hmr-failed

### Steps to reproduce
1. git clone https://github.com/wwsheng009/element-plus-vite-hmr-failed
2. cd element-plus-vite-hmr-failed
3. npm i
4. npm run dev
5. open browser http:localhost:3000
6. change the source file src/App.vue. the browser will not auto refresh.
7. npm i element-plus@"1.0.2-beta.44" ,and repeat the vue file modify operation.
8. It will work fine,when change the element-plus to version "1.0.2-beta.44". 

### What is Expected?
the vite hmr should work then we don't need to refresh the page manually.

### What is actually happening?
the vite hmr import the es module failled where we use the ElementPlus the main.ts/mainjs.

**Comment by nickngqs** [comment]
Im having this issue too.

Another issue was opened, but apparently close -> #620

**Comment by bitjjj** [comment]
refer to #2077

**Comment by wwsheng009** [comment]
> refer to #2077

got it.this issue will be closed now
