### ISSUE TITLE
There is a problem with the dimension parameter of power-off type

### ISSUE THREAD

**Issue by liu-bluesky** [element-plus/element-plus#2108]
hidden-md-and-down  hidden-md-and-up 这俩类有错误

**Comment by bastarder** [comment]
it is work for me, did you try `import 'element-plus/lib/theme-chalk/display.css';`
[see here](https://element-plus.org/#/zh-CN/component/layout#ji-yu-duan-dian-de-yin-cang-lei)

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
