### ISSUE TITLE
Tag  bug list 

### ISSUE THREAD

**Issue by Uluer** [element-plus/element-plus#211]
1. the close event should not trigger the click event
`
emits: ['close'],  // ['close', 'click']
`
`
const handleClick = event => {
     ctx.emit('close', event)  // click
}
`
2. [Using <transition> as component's root will no longer trigger transitions when the component is toggled from the outside.](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0017-transition-as-root.md)
whether to consider letting users use `<transition>` by themselves ?

3. [0018-transition-class-change](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0018-transition-class-change.md)

**el-zoom-in-center-enter** in “src/style/element-ui@2.13.2.css” needs to be changed to **el-zoom-in-center-from**

**Comment by JeremyWuuuuu** [comment]
@Uluer Hi, thanks for raising this up, all transition-related styles will be updated later when the migration finished.
Would you like to make a PR for the bug?

**Comment by Uluer** [comment]
Thank you for seeing this question, I will not submit a PR because my technique is too low

**Comment by JeremyWuuuuu** [comment]
@Uluer Feel free to submit a PR for this, we will have some people working with you on this one.
