### ISSUE TITLE
Invalid setting style of time picker and date picker in [bug report] single file component

### ISSUE THREAD

**Issue by Yusoo** [element-plus/element-plus#2113]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
chrome 90

### Vue version
3.0.11

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
不知道单文件组件怎么做成在线的，大致代码如下
```
<template>
  <el-time-picker
    v-model="value"
    class="qwqwqw"
  />
  <el-date-picker
    v-model="value"
    class="qwqwqw"
  />
</template>

<style scoped>
  .qwqwqw {
    color: red;
  }
</style>
```

### What is Expected?
红色样式生效

### What is actually happening?
样式没有生效

**Comment by bastarder** [comment]
`qwqwqw` classname will be added on `el-input` but not on `<input>`, if you want to set color to red, you should set it on input
```
<style>
  .qwqwqw {
    .el-input__inner {
      color: red;
    }
  }
</style>
```

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by Yusoo** [comment]
我知道这个class是加在el-input上的，但是再chrome里面根本看不到这个class上面有样式。而且想设置<input>也不生效

**Comment by Yusoo** [comment]
> `qwqwqw` classname will be added on `el-input` but not on `<input>`, if you want to set color to red, you should set it on input
> 
> ```
> <style>
>   .qwqwqw {
>     .el-input__inner {
>       color: red;
>     }
>   }
> </style>
> ```

我知道这个class是加在el-input上的，但是在chrome里面只能看到el-input有class，缺没有样式。而且想设置的样式同样也不生效
