### ISSUE TITLE
[Bug Report] vite hmr not working in beta.45

### ISSUE THREAD

**Issue by llk2yq** [element-plus/element-plus#2114]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
win10 edge91

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
(Reproduction Link is unavailable😁)

update elementPlus version to beta.45

yarn dev

change some code

hmr not working

but beta.44 vite hmr works well.

### What is Expected?
hmr working

### What is actually happening?
hmr not working

**Comment by huzedong2015** [comment]
**+10086**

**Comment by seolhw** [comment]
+10086

**Comment by andreylysenko** [comment]
+10086

**Comment by xinhuaer** [comment]
+10086

**Comment by bastarder** [comment]
May be `el-table` caused this mistake，some component import something from @vue/runtime-core; @msidolphin thanks for pr to solve this bug; we will fix this next version; 
#2097
