### ISSUE TITLE
[feature request] vite introduces the SCSS style of components on demand, which cannot be used in scss:additionalData  Configure the @ import SCSS file to change the SCSS variables in the theme

### ISSUE THREAD

**Issue by toneylan** [element-plus/element-plus#2116]
### Existing Component
Yes

### Component Name
loading

### Description
在之前的beta.44版本中，我通过如下vite配置，可以按需引入组件样式，同时通过variables.scss可以改变主题中的scss变量（variables.scss也为了定义其他全局scss变量，以在vue组件中使用）。
```
//vite.config.ts file
plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        esModule: true,
        ensureStyleFile: true,
        resolveStyle: (name) => {
          name = name.slice(3);
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        }
      }]
    })
  ],
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@import "./src/style/variables.scss";`
      }
    }
  }

//variables.scss file
$--color-primary: #19D4AE;

//main.ts 单独引入了
$--font-path: 'element-plus/lib/theme-chalk/fonts';
@import "element-plus/packages/theme-chalk/src/base.scss";
```
但是在更新到beta.45后，sass编译报错了，因为`additionalData: '@import "./src/style/variables.scss";'`，应该会在每个按需引入的组件样式里都执行，而比如loading组件的loading.scss样式开头，使用了`@use "sass:math";`，这触发了sass错误：不能在use前使用import。google后看到sass目前的module system已经建议大家改用@use 'variables'来替代@import方式。

于是我改用`additionalData: '@use "./src/style/variables.scss" as *;'`，然后不报错了，可惜$--color-primary无法改变主题的默认变量了，因为@use模式把“_或-”打头的变量，看作是private的，相当于无法被导出到外部……

目前找到了一个折中解决办法，即：
```
additionalData: '@use "./src/style/variables.scss" as *; $--color-primary: #19D4AE;'
```
这样单独定义出变量就有效，不知道是否有更优雅的，类似使用scss文件的方式。

**Comment by JeremyWuuuuu** [comment]
We updated our sass dependency, you might need to update your scss dependency accordingly. 
Refer to:
#1499 
https://github.com/element-plus/element-plus/pull/2060

**Comment by toneylan** [comment]
Thanks @JeremyWuuuuu .
But when upgrade sass to latest version: 1.34.1, and the problem still exists, maybe not the version caused.
https://github.com/element-plus/element-plus/issues/2132#issuecomment-855169803

**Comment by BelinChung** [comment]
@toneylan 原来如此。其实就是我们在 webpack 级别 import 了一个全局变量文件，导致@import 先于 @use 执行，就报错了。这样的话，我们只需要找到其他的方式，继续全局引入 mixin 应该就能避免这个问题

**Comment by BelinChung** [comment]
我们可以把原先 @import 方式引入的变量，通过 readFile 读成字符串传递给 additionalData
```
const fs = require('fs')
const scssVariables = fs.readFileSync(path.join(__dirname, '../', 'assets/styles/_variables.scss'), 'utf8')
...
{
  sass: {
      additionalData: scssVariables,
    }
}
...
```

**Comment by toneylan** [comment]
> 我们可以把原先 @import 方式引入的变量，通过 readFile 读成字符串传递给 additionalData
> 
> ```
> const fs = require('fs')
> const scssVariables = fs.readFileSync(path.join(__dirname, '../', 'assets/styles/_variables.scss'), 'utf8')
> ...
> {
>   sass: {
>       additionalData: scssVariables,
>     }
> }
> ...
> ```
不错，又是一个解决办法。
之前我还想，要是能在scss @use 时，把$--color-primary这种变量，不作为private处理就好了，但是没有找到规避的办法。

**Comment by lijingfaatcumt** [comment]
> > 我们可以把原先 @import 方式引入的变量，通过 readFile 读成字符串传递给 additionalData
> > ```
> > const fs = require('fs')
> > const scssVariables = fs.readFileSync(path.join(__dirname, '../', 'assets/styles/_variables.scss'), 'utf8')
> > ...
> > {
> >   sass: {
> >       additionalData: scssVariables,
> >     }
> > }
> > ...
> > ```
> 
> 不错，又是一个解决办法。
> 之前我还想，要是能在scss @use 时，把$--color-primary这种变量，不作为private处理就好了，但是没有找到规避的办法。

为什么在我项目中，修改主题色后还是无法生效呢，步骤如下
1. 配置按需导入的babel插件，并配置如下：
![image](https://user-images.githubusercontent.com/22764487/127115098-0e7dee16-2cad-4f60-af18-0ff08d7e0220.png)

2. 在vue.config.js中配置prependData,修改element-plus的主题色，如下
![image](https://user-images.githubusercontent.com/22764487/127115130-73f456d3-c448-4467-bb7b-34e565d44d2b.png)

3. 运行项目，发现程序的主题色没有生效
![image](https://user-images.githubusercontent.com/22764487/127115303-d4fbb6c7-6313-4a25-928a-4969520baa54.png)

**Comment by taoqingqiu** [comment]
> > > 我们可以把原先 @import 方式引入的变量，通过 readFile 读成字符串传递给 additionalData
> > > ```
> > > const fs = require('fs')
> > > const scssVariables = fs.readFileSync(path.join(__dirname, '../', 'assets/styles/_variables.scss'), 'utf8')
> > > ...
> > > {
> > >   sass: {
> > >       additionalData: scssVariables,
> > >     }
> > > }
> > > ...
> > > ```
> > 
> > 
> > 不错，又是一个解决办法。
> > 之前我还想，要是能在scss @use 时，把$--color-primary这种变量，不作为private处理就好了，但是没有找到规避的办法。
> 
> 为什么在我项目中，修改主题色后还是无法生效呢，步骤如下
> 
> 1. 配置按需导入的babel插件，并配置如下：
>    ![image](https://user-images.githubusercontent.com/22764487/127115098-0e7dee16-2cad-4f60-af18-0ff08d7e0220.png)
> 2. 在vue.config.js中配置prependData,修改element-plus的主题色，如下
>    ![image](https://user-images.githubusercontent.com/22764487/127115130-73f456d3-c448-4467-bb7b-34e565d44d2b.png)
> 3. 运行项目，发现程序的主题色没有生效
>    ![image](https://user-images.githubusercontent.com/22764487/127115303-d4fbb6c7-6313-4a25-928a-4969520baa54.png)

Wow, found one TCLer~
