### ISSUE TITLE
[Bug Report] 1.0.2-beta.45 tree table uses fixed="right", which leads to the dislocation of hover style

### ISSUE THREAD

**Issue by f81883387** [element-plus/element-plus#2124]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
chrome

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/f81883387/pen/mdWpjKM

### Steps to reproduce
tree table uses fixed="right"

### What is Expected?
OK style，haaa

### What is actually happening?
Style dislocation

**Comment by BertieGo** [comment]
I do not see any hover style dislocation situation in the reproduction，can u show me more information，like operation step something...

**Comment by f81883387** [comment]
EMMM~
![dd](https://user-images.githubusercontent.com/2329573/120578945-3aa5a600-c459-11eb-98ba-6d9f27cb410e.gif)

**Comment by sxzz** [comment]
It seems that this problem has been fixed for now. feel free to reopen it if the problem consists.
