### ISSUE TITLE
[Bug Report] Vue-loader and Element-plus conflict, hot replacement exception

### ISSUE THREAD

**Issue by NameWjp** [element-plus/element-plus#2126]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
chrome 90.0.4430.212

### Vue version
3.0.11

### Reproduction Link
https://github.com/NameWjp/webpack-template

### Steps to reproduce
https://github.com/NameWjp/webpack-template

### What is Expected?
克隆该仓库地址，执行 npm install，npm run dev，修改 App.vue 中的 template文字，控制台显示热替换成功，页面无反应。将 index.js 中引入的 element-plus 注释掉，热替换恢复正常。

### What is actually happening?
引入 element-plus，不影响热替换

**Comment by xinhuaer** [comment]
Vite 2.3.6 + Element-plus 1.0.2-beta.45 has the same problem.

**Comment by JeremyWuuuuu** [comment]
This is kind of strange behavior since I had a local development environment which HMR works as good as it should be. I dunno what was causing this issue, we will start investigating this and will let you know once we have any updates.
cc @bastarder to track this issue.

**Comment by bastarder** [comment]
May be `el-table` caused this mistake，some component import something from @vue/runtime-core; @msidolphin thanks for pr to solve this bug; we will fix this next version;
