### ISSUE TITLE
[bug report] in El form item, after using El tool IP of El input, it prompts warning: invalid prop: type check failed for prop "tabIndex". Expected string with value "0", got number with value 0

### ISSUE THREAD

**Issue by gslancer** [element-plus/element-plus#2127]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
mac chrome

### Vue version
3.0.11

### Reproduction Link
https://codepen.io/ihoryan/pen/ExWQyJa

### Steps to reproduce
<el-form-item style="width: 100%; margin-bottom: 1rem">
              <el-tooltip :disabled="selectAdminLevel.length > 0" effect="dark" placement="right">
                <template #content>
                  请注意填写正确
                </template>
                <el-input
                  v-model="selectWayNum"
                  :disabled="selectAdminLevel.length > 0"
                  @change="handleWayChange"
                ></el-input>
              </el-tooltip>
            </el-form-item>

### What is Expected?
不应该有warning

### What is actually happening?
[Vue warn]: Invalid prop: type check failed for prop "tabindex". Expected String with value "0", got Number with value 0. 
  at <ElInput modelValue="" onUpdate:modelValue=fn disabled=false  ... > 
  at <ElPopper arrowOffset=5 appendToBody=true autoClose=0  ... > 
  at <ElTooltip disabled=false effect="dark" placement="right" > 
  at <ElFormItem style= {width: "100%", margin-bottom: "1rem"} > 
  at <ElForm label-width="140px" > 
  at <Index> 
  at <PageLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <Main> 
  at <ElMain> 
  at <ElContainer> 
  at <BaseLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< {} > > 
  at <RouterView> 
  at <App>

**Comment by BertieGo** [comment]
> ### Element Plus version
> 1.0.2-beta.45
> 
> ### OS/Browsers version
> mac chrome
> 
> ### Vue version
> 3.0.11
> 
> ### Reproduction Link
> https://codepen.io/ihoryan/pen/ExWQyJa
> 
> ### Steps to reproduce
> 请注意填写正确
> ### What is Expected?
> 不应该有warning
> 
> ### What is actually happening?
> [Vue warn]: Invalid prop: type check failed for prop "tabindex". Expected String with value "0", got Number with value 0.
> at <ElInput modelValue="" onUpdate:modelValue=fn disabled=false ... >
> at <ElPopper arrowOffset=5 appendToBody=true autoClose=0 ... >
> at
> at <ElFormItem style= {width: "100%", margin-bottom: "1rem"} >
> at
> at
> at <PageLayout onVnodeUnmounted=fn ref=Ref< Proxy {…} > >
> at
> at
> 
> 
> at
> at
> at <BaseLayout onVnodeUnmounted=fn ref=Ref< {} > >
> at
> at

已经定位问题，准备提 PR 了

**Comment by bastarder** [comment]
i change the `tabindex` prop type to [String, Number], i hope you can help me to review my changes
