### ISSUE TITLE
[Bug Report] 1.0.2-beta.45 vite error @use rules must be written before any other rules

### ISSUE THREAD

**Issue by ssw1992** [element-plus/element-plus#2132]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
win10

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/

### Steps to reproduce
项目脚手架：vite ts环境
原环境1.0.2-beta.44，正常使用
升级1.0.2-beta.45，再次运行项目，不能运行，报错如下
![1E$N@SR ${G(I{1BSE@{TIK](https://user-images.githubusercontent.com/24841397/120575139-16df6180-c453-11eb-9223-6d707e1e6c08.png)

### What is Expected?
vite脚手架上能运行

### What is actually happening?
升级新版本，脚手架不能正常运行

**Comment by xuan-zhang** [comment]
dart sass upgrade to ^1.34.0

**Comment by JeremyWuuuuu** [comment]
We have updated sass dependencies. You need to update your dependencies.

**Comment by BelinChung** [comment]
Element Plus version
1.0.2-beta.46

When I upgraded `sass` to `"sass": "^1.34.1"`, the problem still existed.
I use the on-demand Components.

Error message
```
 Syntax Error: SassError: @use rules must be written before any other rules.
╷
│ @use "sass:math"; 
│ ^^^^^^^^^^^^^^^^
╵
```

**Comment by ssw1992** [comment]
still can not work("element-plus": "^1.0.2-beta.46","sass": "^1.34.0")

**Comment by ssw1992** [comment]
![image](https://user-images.githubusercontent.com/24841397/120772199-9dc73380-c552-11eb-95f4-0a24dd0fa81a.png)
![image](https://user-images.githubusercontent.com/24841397/120772228-a61f6e80-c552-11eb-83c7-f27845a2ff70.png)
element-plus style

**Comment by toneylan** [comment]
@ssw1992 If you use vite  [css.preprocessorOptions](https://cn.vitejs.dev/config/#css-postcss), I think the "@import *.scss" in additionalData setting, has conflict with element-plus component style(like your screenshot). Currently, I have to change the @import to @use syntax, but might exists some other problem, such as sass private variables :
```
preprocessorOptions: {
    scss: {
      additionalData: '@use "./src/style/mixin.scss" as *;'
    }
}
``` 
#2116

**Comment by ssw1992** [comment]
@toneylan It also can't work when i commented code additionalData in vite.config.ts,but it will report another error;

**Comment by ssw1992** [comment]
> @ssw1992 If you use vite [css.preprocessorOptions](https://cn.vitejs.dev/config/#css-postcss), I think the "@import *.scss" in additionalData setting, has conflict with element-plus component style(like your screenshot). Currently, I have to change the @import to @use syntax, but might exists some other problem, such as sass private variables :
> 
> ```
> preprocessorOptions: {
>     scss: {
>       additionalData: '@use "./src/style/mixin.scss" as *;'
>     }
> }
> ```
> 
> #2116

I solve it by element-plus@1.0.2-beta.46 sass@1.34.1 and remove custom sass additionalData.
In other word,I can't custom add global sass variable, becase @import is runtime and @use is built.

**Comment by toneylan** [comment]
I put global scss var in the variables.scss, it work good, in Vue component file，can use global scss var, without any additional config.
`additionalData: '@use "./src/style/variables.scss" as *; $-- color-primary: #19D4AE;'
`

**Comment by ssw1992** [comment]
you are right,I lost "as *",so the view that "@import is runtime and @use is built" maybe are not right.
In a word,thanks your help.
