### ISSUE TITLE
[bug report] El select when multiple choices are made, there is an in line style height: 40px

### ISSUE THREAD

**Issue by yunziyan11** [element-plus/element-plus#2133]
### Element Plus version
1.0.2-beta.45

### OS/Browsers version
 chrome 91.0.4472.77

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
首先我定制样式 给 $--input-height：28px   设置全部的input的高度是28px 结果select多选时   高度并非28  检查样式 发现里面多一个行内样式  height: 40px

### What is Expected?
期望  $--input-height：28px  设置了28 select多选时  高度是28

### What is actually happening?
首先我定制样式 给 $--input-height：28px   设置全部的input的高度是28px 结果select多选时   高度并非28  检查样式 发现里面多一个行内样式  height: 40px

**Comment by BertieGo** [comment]
@yunziyan11 Can u reproduce the scene by online demo？ cause I can't reproduce this bug by my dev environment
