### ISSUE TITLE
You can't hide the font after the menu is folded. Span doesn't have the corresponding style, but it does on the official website

### ISSUE THREAD

**Issue by liu-bluesky** [element-plus/element-plus#2135]
下面是 el-menu菜单组件里面的样式 官网有 安装包没有
`
 .el-menu--collapse .el-submenu .el-submenu__title span{
 height: 0  ;
    width: 0  ;
    overflow: hidden  ;
    visibility: hidden;
    display: inline-block  ;
}
`

**Comment by kooriookami** [comment]
那个只是demo的样式，组件是没有的

**Comment by 634323580** [comment]
自己写吧，找了一下午了
