### ISSUE TITLE
[bug report] El table column type = "index" error after using row key attribute in El table

### ISSUE THREAD

**Issue by Buttii** [element-plus/element-plus#2143]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
macOS / Chrome 91

### Vue version
3.0.9

### Reproduction Link
https://codesandbox.io/s/ecstatic-ramanujan-1gnci?file=/src/App.vue

### Steps to reproduce
el-table设置row-key属性并且使用<el-table-column type="index"></el-table-column> index 列出错

### What is Expected?
data.reduce((acc: VNode[], row) => {
            return acc.concat(
              this.wrappedRowRender(
                row,
                acc.filter(item => typeof item.key === 'number').length,
              ),
            )
          }, [])

修改acc.filter(item => typeof item.key === 'number').length

### What is actually happening?
实际上设置row-key后acc.filter(item => typeof item.key === 'number').length

**Comment by BertieGo** [comment]
@Buttii I have found the reason of bug occur，but I'm not sure what time the fix can merge & release，so in here maybe some workaround trick will work on your scene。

**Comment by BertieGo** [comment]
@JeremyWuuuuu Hi, about this issue that I have found the bug occur reason，but in the same time I have the request about fix plan，cause now even not add to ``row-key``, but in the expand case, like: 
![image](https://user-images.githubusercontent.com/19757483/120754652-8f235100-c53f-11eb-99de-31fcd30f485e.png)

also have the bug occur, so I plan to make the children row index to like 2.1 2.2 ..., support children index so the user can according the index to custom their index showing in the ``index`` function，is this plan correct？

**Comment by BertieGo** [comment]
@Buttii Before the bug fixed，maybe u can using the `` index `` prop to custom index display via a function，u can check it out in the element plus document...

**Comment by Buttii** [comment]
当设置`el-table`设置`row-key`后`el-table-column`使用插槽时输出的$index全部为0

**Comment by BertieGo** [comment]
> 当设置`el-table`设置`row-key`后`el-table-column`使用插槽时输出的`$index`全部为0

看了下源码，你定位的 `` acc.filter(item => typeof item.key === 'number').length ``该段代码的确是导致问题的原因，因为当设置了 ``row-key `` 之后， item 的 key 即是 row 的 key，并且会转为字符串所以 length 永远为 0，这个 bug 不是那么好修，先看 maintainer 打算怎么设计吧，这个 index 牵扯到挺多东西的...，假如你很急，可以先用 index 这个 prop 处理下..
![image](https://user-images.githubusercontent.com/19757483/120767045-6609bd00-c54d-11eb-8eb1-8bed555d3030.png)

**Comment by Buttii** [comment]
https://codesandbox.io/s/ecstatic-ramanujan-1gnci?file=/src/App.vue
我重新修改了一下案例，我是需要在`el-table-column expand`里面进行修改tableData；如果没有设置`row-key`，每次修改tableData可能是tree Shaking问题，会自动闭合expand，故设置`expand-row-keys`和`row-key`，导致index为0，所以无法使用index去处理其他逻辑。

**Comment by BertieGo** [comment]
可能你需要脱离 element table 的机制，watch 数据的变化，map data 的数量去做 index 了，假如有 expand 的场景，那么还需要 watch expand 的数据。

**Comment by Buttii** [comment]
我就是用的map data的数量去做的index，期待element-plus团队后续能修复好这个问题
