### ISSUE TITLE
el-switch @change is auto triggered when page load

### ISSUE THREAD

**Issue by happy-func** [element-plus/element-plus#2147]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
chrome 版本 90.0.4430.212（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/happy-func/pen/YzZavvd?editors=1111

### Steps to reproduce
what should i say?100% happen.open this link https://codepen.io/happy-func/pen/YzZavvd?editors=1111, check console you will see

### What is Expected?
when page load don't trigger @change

### What is actually happening?
el-switch @change is auto triggered when page load

**Comment by BeADre** [comment]
由于你设置了`active-value` 和 `inactive-value` 属性, 所以在load的时候你双向绑定的值会被改变，于是触发了change事件

**Comment by happy-func** [comment]
> 由于你设置了`active-value` 和 `inactive-value` 属性, 所以在load的时候你双向绑定的值会被改变，于是触发了change事件

but its same value with origin data, can i think its a bug?

**Comment by yang867381349** [comment]
之前的版本是不存在这个问题的。

**Comment by lipengzhou** [comment]
> 之前的版本是不存在这个问题的。

之前版本是没有这个问题的，我觉得这是一个 bug。

**Comment by kooriookami** [comment]
@justwiner Can you look at this if you are free.

**Comment by BiosSun** [comment]
唔，我想应该是有两个问题：

首先，是在 Switch 组件中，若 moduleValue 的值是 `undefined`，同时设置了 `inactive-value` 和 `active-value` 为其它值，那么会在组件被创建时触发 change 事件，但若没有设置 `inactive-value` 和 `active-value`，保持其默认值为 `false` 和 `true`，那么就不会触发 change 事件。

我认为这使 Switch 组件失去了正交性，而且是不必要的，因此应当处理一下，感觉改成「让  modalValue 的默认值为 `inactive-value` 属性的值」会比较好。

另外，就是 Table Column 组件，会隐式地渲染一行，该行的索引为 -1，且数据只是一个空对象。即便没有给 table 传入任何数据，这一行也会被渲染。且所渲染的这一行，对用户来说是看不见的，即便渲染失败了，其异常也会被捕获并不做任何处理。

因此通常，该行为对用户来说是无感知的。但是，若用户在自定义的列中所使用的子组件包含副作用，那么就会容易出现问题。比如将行数据中的 id 字段作为参数来请求某个接口，那么用户就会发现发出了一个参数值为 undefined 的请求。

或我所遇到的，在 Table Column 中使用了 Switch 组件，自定义其 `inactive-value` 和 `active-value`，并监听 `change` 事件，而且在 `change` 事件触发时调用某个接口去更新服务器端的状态。那么在表格渲染时就会看到，Switch 自动触发了一次 `change` 事件……

**Comment by kooriookami** [comment]
@BiosSun 是的，我们会考虑如何修复这些问题。

**Comment by bigbigtime** [comment]
确实存在这种情况，变更了switch的默认值，初始化组件后便会自动触发change事件，所以不得不在方法内部做if条件的return动作。

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/123358461-193e6280-d59e-11eb-861b-43de5bc7a721.png)

为什么这里需要去执行slots.default函数呢？还传入了默认参数
@kooriookami @JeremyWuuuuu

**Comment by cmdparkour** [comment]
在业务中暂时解决方案如下：
const handleUpdateStatus = (row: any) => {
     // 第一次加载table时候不会拿到id的值
      if (!row.id) {
        return
      }
      row.loading = true
      let params = {
        id: row.id,
        status: row.status
      }
      updateStatus(params)
      .then(res => {
        ElMessage({
          type: 'success',
          message: '状态变更成功'
        })
      })
    }

**Comment by cmdparkour** [comment]
在业务中暂时解决方案如下：
const handleUpdateStatus = (row: any) => {
     // 第一次加载table时候不会拿到id的值
      if (!row.id) {
        return
      }
      row.loading = true
      let params = {
        id: row.id,
        status: row.status
      }
      updateStatus(params)
      .then(res => {
        ElMessage({
          type: 'success',
          message: '状态变更成功'
        })
      })
    }

**Comment by msidolphin** [comment]
> 唔，我想应该是有两个问题：
> 
> 首先，是在 Switch 组件中，若 modelValue 的值是 `undefined`，同时设置了 `inactive-value` 和 `active-value` 属性为其它值，那么就会在组件被创建时触发一次 `change` 事件；但若没有设置 `inactive-value` 和 `active-value` 属性，保持其默认值为 `false` 和 `true`，却不会触发。
> 
> 我认为这使 Switch 组件失去了正交性，而且是不必要的，因此应当处理一下。该问题的原因是 modelValue 的默认值被写死为 `false`，因此感觉改成「让 modelValue 的默认值为 `inactive-value` 属性的值」会比较好。
> 
> 另外，就是 Table Column 组件，它会隐式地渲染一行，该行的索引为 -1，且数据只是一个空对象。即便没有给 table 传入任何数据，这一行也会被渲染。且所渲染的这一行，对用户来说是看不见的，即便渲染失败了，其异常也会被捕获并不做任何处理。因此通常，该行为对用户来说是无感知的。
> 
> 但是，若用户在自定义的列中所使用的子组件包含副作用，那么就会容易出现问题。比如将行数据中的 id 字段作为参数来请求某个接口，那么用户就会发现发出了一个参数值为 undefined 的请求。
> 
> 或我所遇到的，在 Table Column 中使用了 Switch 组件，自定义其 `inactive-value` 和 `active-value`，并监听 `change` 事件，而且在 `change` 事件触发时调用某个接口去更新服务器端的状态。那么在表格渲染时就会看到，Switch 自动触发了一次 `change` 事件……

这个表格隐式渲染的问题我们已经解决了
