### ISSUE TITLE
[bug report] El input number component bidirectional binding failure

### ISSUE THREAD

**Issue by heyuycl001** [element-plus/element-plus#2149]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
macOs10.15.7  /   Edge  91.0.864.37 

### Vue version
3.1.0-beta.7

### Reproduction Link
https://codesandbox.io/s/hungry-platform-h8sdz?file=/src/components/HelloWorld.vue:14-29

### Steps to reproduce
1. 在el-input-number 绑定 @change 把变量赋值为100
2. 然后在修改输入框里的值，第一次页面跟数据都会变为100
3. 后面在输入，数据是100， 页面输入框会继续变化。页面跟数据不一致

### What is Expected?
后面在输入，数据是100， 页面输入框会继续变化。页面跟数据保持一致

### What is actually happening?
后面在输入，数据是100， 页面输入框会继续变化。页面跟数据不一致

**Comment by nothinginterested** [comment]
额，这不是bug吧。 onChange事件你接收传来的input的值呀

**Comment by heyuycl001** [comment]
> 额，这不是bug吧。 onChange事件你没有接收传来的input的值呀

我的意思是el-input-number 这个组件，onChange修改绑定的值是100，但是后续我在页面输入后 页面还会持续变化。

**Comment by heyuycl001** [comment]
> 额，这不是bug吧。 onChange事件你没有接收传来的input的值呀

看了下代码，发现是做了一些优化，但是如果我使用 el-input-number 这个组件，想保留两位小数，并且不使用precision API，自己处理数据，就会出现这个问题。目前的解决方案是把数据转换为string，这样element就不会走优化的逻辑。
