### ISSUE TITLE
[Bug Report] Switch prevent switching invalid

### ISSUE THREAD

**Issue by BakaRice** [element-plus/element-plus#2150]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
Windows 10 /Google Chrome 90.0.4430.212

### Vue version
3.1.0-beta.7

### Reproduction Link
https://codepen.io/ricemarch/pen/wvJjGyV

### Steps to reproduce
just click the switch 

### What is Expected?
prevent switching

### What is actually happening?
No switches are blocked, there is no happening

**Comment by BeADre** [comment]
maybe you should use `before-change` to replace `beforeChange`

**Comment by kooriookami** [comment]
https://v3.vuejs.org/guide/component-props.html#prop-casing-camelcase-vs-kebab-case
You can only use kebab-case in HTML, but if you use template, you can use both of them.
