### ISSUE TITLE
[Bug Report] Module not found: Error: Can't resolve './play/index.vue' in ……

### ISSUE THREAD

**Issue by carveybunt** [element-plus/element-plus#2166]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
mac

### Vue version
3.1.0-beta.7

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
yarn website-dev:play

### What is Expected?
就想看看命令执行后生成的相关文件

### What is actually happening?
学习

**Comment by BertieGo** [comment]
需要自己手动添加该 index.vue，因为这个是给到开发者用来做开发测试的，并不是标配的文件。
