### ISSUE TITLE
[Bug Report] table tree highlight problem

### ISSUE THREAD

**Issue by gmingchen** [element-plus/element-plus#2171]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
window10 Chrome 91.0.4472.77（正式版本） （64 位）

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/1240235512/pen/wvJXYOZ

### Steps to reproduce
table树形组件添加 固定列Table-column 会出现hover高亮不准确

### What is Expected?
高亮准确

### What is actually happening?
hover行 与 高亮行 不符

**Comment by lvfangren** [comment]
https://github.com/element-plus/element-plus/pull/2235

也许问题已经修复（尝试过fix，好像没正确fix😂）。

**Comment by msidolphin** [comment]
> #2235
> 
> 也许问题已经修复（尝试过fix，好像没正确fix😂）。

Is it still incorrect in latest version? i cannot reproduce
