### ISSUE TITLE
[Bug report] element:^1.0.2-beta.46, vue: ^3.1.1;  color-picker con't open select dialog and the bind color always show rgb(255, 0, 0)

### ISSUE THREAD

**Issue by zhanlizhu530** [element-plus/element-plus#2179]

**Comment by staugur** [comment]
Following.

And add one, one of my projects, after the overall upgrade (npm-check-updates), found that the `NavMenu` could not be expanded, and the title of `Menu-Group` is not displayed .

Reinstalled vue 3.0.11 to restore it.

**Comment by JohanManders** [comment]
Dropdowns also don't work anymore, because popper style keeps `display: none` fixed.

Example code: https://codesandbox.io/s/eager-volhard-ld8ov

If you change Vue 3.1.1 to Vue 3.0.11 it works fine.

**Comment by oliverzy** [comment]
发现了同样的问题，辛苦看一下

**Comment by ChenWeihua123** [comment]
遇到同样的问题 升级 vue3.1.1 后 dropdown 不显示 popper

**Comment by iamkun** [comment]
Vue 3.1.1 的 breaking change 请先回退到 3.0.11 使用， 已经在跟进中 

please fall back to vue 3.0.11 before we fix this bug, cheers

**Comment by kooriookami** [comment]
Please update element-plus to the latest version.
