### ISSUE TITLE
New directive: Trap focus

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#218]
Adding a new directive named `v-trap-focus` to trapping focus inside opened `modal`
### Functionality:
 - Should be able to trap the first focusable element on the modal
 - Should be able to restore the focus event when modal gets closed
 - Should be able to trap the focus inside the open modal

**Comment by JeremyWuuuuu** [comment]
cc @zouhangwithsweet @HerringtonDarkholme @zazzaz  @bastarder , any suggestions?

**Comment by bastarder** [comment]
if i set two element `v-trap-focus`, which one will be focus?

**Comment by JeremyWuuuuu** [comment]
> if i set two element `v-trap-focus`, which one will be focus?
> is it conflict with `autofocus`?
> when first element change, will be focus on new first element?

IMHO, the main design of this directive is that we want to trap focus inside some modal with structure like this:
```vue
<div v-trap-focus role="modal">
  <button>I am a button can be focused</button>
  <button>cancel</button>
  <div tabindex="1" role="document">
  </div>
  <input autofocus />
</div>
```
The main idea is to trap focus inside this modal, instead of manipulate the focus, there might be some sort of conflict for components with autofocus, we'll dig into that and keep them isolated

**Comment by zouhangwithsweet** [comment]
how to handle `select` or `checkbox` ?
