### ISSUE TITLE
[bug report] El select cannot be used

### ISSUE THREAD

**Issue by aklivecai** [element-plus/element-plus#2180]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/aklivecai/pen/abJKeKg

### Steps to reproduce
el-select 

https://codepen.io/aklivecai/pen/abJKeKg

### What is Expected?
下拉选择 显示

### What is actually happening?
无法显示选择窗口

**Comment by Tryndamere-wang** [comment]
> ### Element Plus version
> 1.0.2-beta.46
> 
> ### OS/Browsers version
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
> 
> ### Vue version
> 3.1.1
> 
> ### Reproduction Link
> https://codepen.io/aklivecai/pen/abJKeKg
> 
> ### Steps to reproduce
> el-select
> 
> https://codepen.io/aklivecai/pen/abJKeKg
> 
> ### What is Expected?
> 下拉选择 显示
> 
> ### What is actually happening?
> 无法显示选择窗口

 "element-plus": "^1.0.2-beta.44", 这个也不能用了，下拉选择，以及时间选择器都不能用

**Comment by kooriookami** [comment]
Please return vue to version 3.0.9, we will solve it as soon as possible

**Comment by Tryndamere-wang** [comment]
这个bug什么时候能修好？

**Comment by qujiahao** [comment]
我页面已经崩了  版本都不敢发

**Comment by YangNNN** [comment]
eye

**Comment by Tryndamere-wang** [comment]
怎么还没修好吗？为什么done下来的代码引入没有错误，发布的npm包会有错误哪？

**Comment by qujiahao** [comment]
> 怎么还没修好吗？为什么done下来的代码引入没有错误，发布的npm包会有错误哪？

使用3.0.11版本vue就可以了   明天更新3.1.1版本，不想替换版本先等着

**Comment by Tryndamere-wang** [comment]
升级了vue到3.0.1还是没用的，那就等明天吧

**Comment by Tryndamere-wang** [comment]
使用3.0.11版本vue也没用，还是出不来下拉框，只能等明天。

**Comment by staunchheart** [comment]
日期选择框同样有问题，3.1.1无法弹出下接窗口，官网DEMO可重现这一问题，不能下拉。

**Comment by aehyok** [comment]
日期选择框同样有问题，3.1.1无法弹出下接窗口，官网DEMO可重现这一问题，不能下拉。

**Comment by aehyok** [comment]
> 使用3.0.11版本vue也没用，还是出不来下拉框，只能等明天。

可以了。

**Comment by Tryndamere-wang** [comment]
目前使用以下版本可以了。注意^有无

"vue": "3.0.9",
"element-plus": "^1.0.2-beta.46",
"@vue/compiler-sfc": "3.0.9",

**Comment by kooriookami** [comment]
Please update `element-plus` and `vue` to the latest version. The problem is caused by changes of vue 3.1.
