### ISSUE TITLE
[bug report] navmenu navigation menu collapse function of the latest version cannot be used

### ISSUE THREAD

**Issue by feirnova** [element-plus/element-plus#2183]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
chrome

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/feirnova/pen/KKWBQpG

### Steps to reproduce
导航菜单折叠后的展开功能无法使用，页面报错。
使用官网的在线运行功能一样有这个错误。

### What is Expected?
正常展开折叠后的菜单

### What is actually happening?
没有任何反应，页面上显示报错

**Comment by kooriookami** [comment]
Please return vue to version 3.0.9, we will solve it as soon as possible

**Comment by JeremyWuuuuu** [comment]
We are not compatible with `Vue^3.1.0`, you need to rollback your `Vue` version in order to get ElementPlus work. This is the issue caused by them instead of us, we will need time to fix it.

**Comment by feirnova** [comment]
收到
