### ISSUE TITLE
Component exception

### ISSUE THREAD

**Issue by pxy0601** [element-plus/element-plus#2192]
el-date-picker 组件的type属性报错
NavMenu组件的mode属性设置为'horizontal',显示异常，控制台[Vue warn]: Invalid VNode type: undefined (undefined)
at <ElPopper ref="popperVNode" manualMode=true visible=false ... >
at <ElSubmenu index="2" >
at <BaseTransition mode="out-in" onBeforeEnter=fn<onBeforeEnter> onEnter=fn ... >
at <Transition mode="out-in" onBeforeEnter=fn<beforeEnter> onEnter=fn<enter> ... >
at <ElMenuCollapseTransition key=0 class="el-menu-demo" >
at <ElMenu default-active="2" class="el-menu-demo" mode="horizontal" ... >
at <App>
有可能其他控件也有错
官方文档中的实例在线运行即可看到组件异常情况，希望官方尽快解决！！！！！

**Comment by qujiahao** [comment]
table弹窗插入还有select都有问题，示例同样问题，现在页面跳转报错，卡死  感觉是所有的prop出了问题

**Comment by JeremyWuuuuu** [comment]
有个模板给你们填你们填一下行吗 Vue版本也不说 3.1 现在有问题 还没支持

**Comment by iamkun** [comment]
Please fall back to Vue  3.0.11 before we fix this bug.

**Comment by JeremyWuuuuu** [comment]
Vue 的 breaking change 我们修了 会影响用 3.0.x 版本的人。现在暂时还没有人手修，这个明天（北京时间六月十一号）会 release 一个版本跟进。 再次恳请下次提issue的时候把版本带上，已经是最低要求了 感谢。还有不要加那么多感叹号，给人感觉像是在命令。

**Comment by JeremyWuuuuu** [comment]
暂时修复办法就是把你们vue的版本锁在3.0.x。：）

**Comment by qujiahao** [comment]
vue版本3.0.0，报错问题，插入表格中el-popover报错type或者exposed为null  下拉框无显示 在官方文档在线调试出现同样的问题，辛苦了，前element-plus版本使用.28，表格中el-tooltip已根据文档替换为el-popover

**Comment by JeremyWuuuuu** [comment]
> vue版本3.0.0，报错问题，插入表格中el-popover报错type或者exposed为null 下拉框无显示 在官方文档在线调试出现同样的问题，辛苦了，前element-plus版本使用.28，表格中el-tooltip已根据文档替换为el-popover

3.0.0 还没有expose API 起码要3.0.9（如果我没记错）你把你版本升级到3.0.11试试看

**Comment by qujiahao** [comment]
好的  我先试试  谢谢

**Comment by bokuns** [comment]
Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
What versions should I downgrade to?

Current Versions:
```
vue: ^3.0.5,
element-plus: ^1.0.2-beta.46",
vite: ^2.3.3
```

**Comment by qujiahao** [comment]
vue已经更为3.0.11版本  select和tooltip已经可以正常

> Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
> What versions should I downgrade to?
> 
> Current Versions:
> 
> ```
> vue: ^3.0.5,
> element-plus: ^1.0.2-beta.46,
> vite: ^2.3.3
> ```

**Comment by JeremyWuuuuu** [comment]
> Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
> What versions should I downgrade to?
> 
> Current Versions:
> 
> ```
> vue: ^3.0.5,
> element-plus: ^1.0.2-beta.46,
> vite: ^2.3.3
> ```

Could you update and lock your Vue to 3.0.11 and give it a try? some APIs are not compatible with your version.

**Comment by JeremyWuuuuu** [comment]
> vue已经更为3.0.11版本 select和tooltip已经可以正常
> 
> > Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
> > What versions should I downgrade to?
> > Current Versions:
> > ```
> > vue: ^3.0.5,
> > element-plus: ^1.0.2-beta.46,
> > vite: ^2.3.3
> > ```
Good. Please lock the version until we make a release for 3.1.1

**Comment by qujiahao** [comment]
okay, thank you.

**Comment by bokuns** [comment]
> > vue已经更为3.0.11版本 select和tooltip已经可以正常
> > > Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
> > > What versions should I downgrade to?
> > > Current Versions:
> > > ```
> > > vue: ^3.0.5,
> > > element-plus: ^1.0.2-beta.46,
> > > vite: ^2.3.3
> > > ```
> 
> Good. Please lock the version until we make a release for 3.1.1

LOL, just tried ```vue: 3.1.1```, but no luck. I'll probably stay on 3.1.1 and wait for your release. How soon would it be out?

**Comment by JeremyWuuuuu** [comment]
> > > vue已经更为3.0.11版本 select和tooltip已经可以正常
> > > > Just found out that Popover content is not displaying after upgrading all the packages (it used to work). Is this related?
> > > > What versions should I downgrade to?
> > > > Current Versions:
> > > > ```
> > > > vue: ^3.0.5,
> > > > element-plus: ^1.0.2-beta.46,
> > > > vite: ^2.3.3
> > > > ```
> > 
> > 
> > Good. Please lock the version until we make a release for 3.1.1
> 
> LOL, just tried `vue: 3.1.1`, but no luck. I'll probably stay on 3.1.1 and wait for your release. How soon would it be out?

It should be considered at tomorrow(11st Jun Beijing time)
Til now we still have no clue what caused the issue but we are going to find out.

**Comment by BertieGo** [comment]
> Vue 的 breaking change 我们修了 会影响用 3.0.x 版本的人。现在暂时还没有人手修，这个明天（北京时间六月十一号）会 release 一个版本跟进。 再次恳请下次提issue的时候把版本带上，已经是最低要求了 感谢。还有不要加那么多感叹号，给人感觉像是在命令。

I'm all day paddling and intend to join element-plus group, should I need interview or something...?

**Comment by JeremyWuuuuu** [comment]
Guys, new release have been dispatched, FYI: https://github.com/element-plus/element-plus/actions/runs/928272289

**Comment by JeremyWuuuuu** [comment]
> > Vue 的 breaking change 我们修了 会影响用 3.0.x 版本的人。现在暂时还没有人手修，这个明天（北京时间六月十一号）会 release 一个版本跟进。 再次恳请下次提issue的时候把版本带上，已经是最低要求了 感谢。还有不要加那么多感叹号，给人感觉像是在命令。
> 
> Hi，I'm all day paddling and intend to join element-plus group, should I need to interview or something...?

If you intent to be a maintainer of this project, you can simply start with fixing bugs, and send PR to us. You do not need to be interviewed to be a maintainer. Start coding right away :), If I or the team can not find time to respond you in time, you can ping me via mentioning me in your PRs.

**Comment by JeremyWuuuuu** [comment]
I think I can close this issue since the release have been released.
