### ISSUE TITLE
[Bug Report] Website codepen demo is not working

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#2197]
### Element Plus version

1.0.2-beta.46

### OS/Browsers version

Win 10 / Chrome

### Vue version

3.1.1

### Reproduction Link

https://codepen.io/wenfang/pen/abJaZpW

### Steps to reproduce

Click cascader to expand options.

### What is Expected?

The cascader options show up.

### What is actually happening?

The cascader options aren't showing up.

**Comment by iamkun** [comment]
Please fall back to Vue  3.0.11 before we fix this bug.

**Comment by kooriookami** [comment]
Please update element-plus to the latest version.
