### ISSUE TITLE
[Bug Report]  el-select , el-dropdown don't work with  vue@3.1.1 

### ISSUE THREAD

**Issue by ZhouJiang** [element-plus/element-plus#2198]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
chrome 91

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/zhoujiang/pen/RwpYGbm

### Steps to reproduce
 el-select , el-dropdown don't work with  vue@3.1.1 

### What is Expected?
The options show up.

### What is actually happening?
don't work

**Comment by iamkun** [comment]
Please fall back to Vue  3.0.11 before we fix this bug.

**Comment by ErrorJe** [comment]
> Please fall back to Vue 3.0.11 before we fix this bug.

when will it be finished

**Comment by fruitGirl** [comment]
用不了这个什么时候可以修复一下

**Comment by fruitGirl** [comment]
Vue 3.0.11 这个版本也有问题 也是不能运行

**Comment by zrx1118** [comment]
Vue 3.0.0 也不能用啊

**Comment by sharpFD** [comment]
好烦，好多问题

**Comment by 6506302** [comment]
Vue 3.0.5 这个版本的没问题

**Comment by Otto-J** [comment]
> Please fall back to Vue 3.0.11 before we fix this bug.

再解决之前，在文档上给个提示吧

**Comment by Chris-Kin** [comment]
> > Please fall back to Vue 3.0.11 before we fix this bug.
> 
> 再解决之前，在文档上给个提示吧

has fixed in latest version
