### ISSUE TITLE
[Bug Report] NavMenu error during menu collapse

### ISSUE THREAD

**Issue by caryhgq** [element-plus/element-plus#2202]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
windows10 / Chrome 91.0.4472.77

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/CaryHGQ/pen/NWpLpyp

### Steps to reproduce
The NavMenu  component set to collapse, console visible error。

[Vue warn]: Invalid VNode type: undefined (undefined) 
  

### What is Expected?
NavMenu   components work normally

### What is actually happening?
Console printing error, component working properly

 [Vue warn]: Invalid VNode type: undefined (undefined)

**Comment by mexican-jack** [comment]
The submenu.vue template has been commented out. this is causing the issue.

**Comment by lipengzhou** [comment]
I made the same mistake.

**Comment by kooriookami** [comment]
Please update `element-plus` to the latest version.
