### ISSUE TITLE
[Feature Request] Expand supported range for `isValidWidthUnit`

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#2203]
Given the current implementation:

```js
export const isValidWidthUnit = (val: string | number): boolean => {
  if (isNumber(val)) {
    return true
  } else {
    return ['px', 'rem', 'em', 'vw', '%', 'vmin', 'vmax'].some(unit =>
      (val as string).endsWith(unit),
    )
  }
}
```

Values like `max-content`, `calc(100px + 10vw)` etc. aren't allowed and will throw a warning, it'd be great if these values are supported as well.

**Comment by stevending1st** [comment]
@sxzz @wenfangdu @jlputter This issue should be closed.
https://github.com/element-plus/element-plus/pull/5568
