### ISSUE TITLE
The row key attribute is set in the [bug report] table, and fixed = "right" is set in the next column. Moving the mouse to a row indicates that it is wrong

### ISSUE THREAD

**Issue by nie312122330** [element-plus/element-plus#2208]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
widnows  chrome

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-pwfjv?file=/src/App.vue

### Steps to reproduce
直接访问 

### What is Expected?
鼠标移动到某行    高亮某行

### What is actually happening?
鼠标移动到任意一行          高亮都是第一行

**Comment by msidolphin** [comment]
I already fix this.
