### ISSUE TITLE
[Feature Request] In the Nuxt.js

### ISSUE THREAD

**Issue by akmalov-i** [element-plus/element-plus#2209]
### Existing Component
No

### Component Name
Nuxt

### Description
I would like to see Element-plus in Nuxt.js 
It is very necessary for the future, are you planning to add it?

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for using Element-Plus.

GitHub issue is for feature request and bug reporting. 
You can already use element plus along with Nuxt.

Searching Nuxt and Element on Google gives me https://github.com/ElementUI/nuxt-with-element-ui.
For more questions, please refer to stackoverflow. Thanks.
