### ISSUE TITLE
[Bug Report] Checkbox "selfModel "property not use ref

### ISSUE THREAD

**Issue by XyyF** [element-plus/element-plus#2210]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0g2e5?file=/src/App.vue

### Steps to reproduce
el-checkbox非受控特性由 selfModel 控制，selfModel未使用响应式，不触发UI更新

### What is Expected?
selfModel 能通过响应式触发UI更新

### What is actually happening?
selfModel未使用响应式，不触发UI更新

**Comment by JeremyWuuuuu** [comment]
Agreed, this is indeed a bug that we need to fix.
