### ISSUE TITLE
When will feature request support vite and postcss?

### ISSUE THREAD

**Issue by carveybunt** [element-plus/element-plus#2211]
### Existing Component
是

### Component Name
website

### Description
使用现在项目yarn website-dev 构建后，若是有更新内容，会编译全部模块。何时支持使用vite，只会编译有变更的内容。
同时，能否在website中支持postcss?

**Comment by sxzz** [comment]
The documentation site is currently being refactored using vitepress. If there are other questions, please wait for the new document site to be released and raise a new issue.
