### ISSUE TITLE
The problem of leaf field in tree component

### ISSUE THREAD

**Issue by xiangxinji** [element-plus/element-plus#2212]
If the tree component loads data asynchronously, if I add it through the append method through the current node, if the current node is a leaf node, I should judge when I append. If it is a leaf node, it should become a non leaf node. Now it seems that the tree component does not deal with this situation, and the example does not have this solution

**Comment by JeremyWuuuuu** [comment]
Could you provide a simple reproducible repo to demonstrate your issue? We'd like to help but only when you can provide some example.
