### ISSUE TITLE
[Bug Report] tooltip just didnt work as it should be 

### ISSUE THREAD

**Issue by wyx0k** [element-plus/element-plus#2213]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
tooltip demo and chrome 91.0.4472.101

### Vue version
3.1.1

### Reproduction Link
none

### Steps to reproduce
create a new project by vue ui , 
and add plugin by vue add element-plus ,
then using el-tooltip like demo,
just hover on button
![image](https://user-images.githubusercontent.com/19360718/121707505-34729200-cb09-11eb-947c-4146578a9211.png)

![捕获](https://user-images.githubusercontent.com/19360718/121701499-8adcd200-cb03-11eb-90e6-bda560015eb0.PNG)

### What is Expected?
popup a tip

### What is actually happening?
nothing happend

**Comment by kooriookami** [comment]
Please update your `element-plus` to the latest version and try again.
