### ISSUE TITLE
pagination page-sizes do not show, and Popover do not show too

### ISSUE THREAD

**Issue by MissLlq** [element-plus/element-plus#2215]
"element-plus": "^1.0.2-beta.46"
"vue": "^3.0.4"

**Comment by MissLlq** [comment]
![0c47f108e9d5bf49e509439dd322b049](https://user-images.githubusercontent.com/30867842/121628055-18400800-caab-11eb-978e-c3b6be1f3dda.png)

**Comment by shanhan0** [comment]
我的也是，本地是好的，发布测试就不行了

**Comment by shanhan0** [comment]
解决了吗

**Comment by shanhan0** [comment]
解决了吗

**Comment by kooriookami** [comment]
Update `element-plus` and `vue` to the latest version please.

**Comment by sonicsunsky** [comment]
我的是使用vite，本地测试vite dev是好的，发布测试vite build && vite preview就不显示了

**Comment by zzjjbbaa** [comment]
和楼上一毛一样的问题

**Comment by kooriookami** [comment]
> 和楼上一毛一样的问题

我刚刚测试了，能够显示。相关库的版本都升级了吗？

**Comment by zzjjbbaa** [comment]
谢谢提醒，最新的库，已经解决了

**Comment by zzjjbbaa** [comment]
> > 和楼上一毛一样的问题
> 
> 我刚刚测试了，能够显示。相关库的版本都升级了吗？

谢谢提醒，最新的库，已经解决该问题了
