### ISSUE TITLE
Sass has been reporting errors since [bug report] was introduced on demand

### ISSUE THREAD

**Issue by zy94xhn** [element-plus/element-plus#2217]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
mac os

### Vue version
3.1.1

### Reproduction Link
https://github.com/zy94xhn/vue3-admin-vite-ts

### Steps to reproduce
1.项目是vite vue
2.安装依赖
3.按需引入
4。报错

### What is Expected?
#{math.div($--transfer-filter-height, 2)};
一直报语法错误
![image](https://user-images.githubusercontent.com/51955207/121649470-2f8eed80-cacb-11eb-97d9-267824bc2d50.png)

### What is actually happening?
[plugin:vite:css] Undefined function.
    ╷
119 │       border-radius: #{math.div($--transfer-filter-height, 2)};
    │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/element-plus/packages/theme-chalk/src/transfer.scss 119:24     @content
  node_modules/element-plus/packages/theme-chalk/src/mixins/mixins.scss 97:9  e()
  node_modules/element-plus/packages/theme-chalk/src/transfer.scss 106:3      @content
  node_modules/element-plus/packages/theme-chalk/src/mixins/mixins.scss 74:5  b()
  node_modules/element-plus/packages/theme-chalk/src/transfer.scss 39:1       root stylesheet

**Comment by zy94xhn** [comment]
更新sass版本，可解决

**Comment by lslsshuo-iie** [comment]
> 更新sass版本，可解决

Which sass version？thanks~
