### ISSUE TITLE
[Bug Report] el-cascader cannot display content after clicking

### ISSUE THREAD

**Issue by TuiMao233** [element-plus/element-plus#2218]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
window 10

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/zowyreqm/1/

### Steps to reproduce
Use el-cascader normally

### What is Expected?
Use el-cascader normally

### What is actually happening?
el-cascader cannot display content after clicking

**Comment by Otto-J** [comment]
怀疑和 vue3.1.x 有关，我尝试降级到 vue3.0.11 可用，正在看什么原因导致的

**Comment by JeremyWuuuuu** [comment]
Hi guys, the new release is on its way. You can upgrade to beta.47 to solve this issue.
