### ISSUE TITLE
[bug report] official example of form custom rule verification

### ISSUE THREAD

**Issue by 15904550933** [element-plus/element-plus#2219]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
windows/chrom

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-2xc3r?file=/src/App.vue

### Steps to reproduce
<template>
  

  <div>
    <el-form
      :model="ruleForm"
      status-icon
      :rules="rules"
      ref="ruleForm"
      label-width="100px"
      class="demo-ruleForm"
    >
      <el-form-item label="密码" prop="pass">
        <el-input
          type="password"
          v-model="ruleForm.pass"
          autocomplete="off"
        ></el-input>
      </el-form-item>
      <el-form-item label="确认密码" prop="checkPass">
        <el-input
          type="password"
          v-model="ruleForm.checkPass"
          autocomplete="off"
        ></el-input>
      </el-form-item>
      <el-form-item label="年龄" prop="age">
        <el-input v-model.number="ruleForm.age"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('ruleForm')"
          >提交</el-button
        >
        <el-button @click="resetForm('ruleForm')">重置</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>
import { reactive } from "vue";
export default {
  setup() {
    var checkAge = (rule, value, callback) => {
      if (!value) {
        return callback(new Error("年龄不能为空"));
      }
      setTimeout(() => {
        if (!Number.isInteger(value)) {
          callback(new Error("请输入数字值"));
        } else {
          if (value < 18) {
            callback(new Error("必须年满18岁"));
          } else {
            callback();
          }
        }
      }, 1000);
    };
    var validatePass = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("请输入密码"));
      } else {
        if (this.ruleForm.checkPass !== "") {
          this.$refs.ruleForm.validateField("checkPass");
        }
        callback();
      }
    };
    var validatePass2 = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("请再次输入密码"));
      } else if (value !== this.ruleForm.pass) {
        callback(new Error("两次输入密码不一致!"));
      } else {
        callback();
      }
    };

    const ruleForm = reactive({
      pass: "",
      checkPass: "",
      age: "",
    });
    const rules = reactive({
      pass: [{ validator: validatePass, trigger: "blur" }],
      checkPass: [{ validator: validatePass2, trigger: "blur" }],
      age: [{ validator: checkAge, trigger: "blur" }],
    });

    return {
      checkAge,
      validatePass,
      validatePass2,
      ruleForm,
      rules,
    };
  },
};
</script>

### What is Expected?
官方示例

### What is actually happening?
在 element-plus 中，表单 的 自定义校验规则 官方示例代码
    在<el-form>标签中 ref="ruleForm"  与   <el-input> 标签中 v-model="ruleForm.pass"
    使用了相同变量 ruleForm 。
    会造成无法输入的问题

**Comment by kooriookami** [comment]
组合式 API 中请保证 `model` 和 `ref` 不重名。
