### ISSUE TITLE
Checkbox: label type and modelValue type

### ISSUE THREAD

**Issue by Ryan2128** [element-plus/element-plus#223]
**label:**
When I was refactoring `Transfer` component which depend on `Checkbox` and `CheckboxGroup` component, I met the warn below.

![image](https://user-images.githubusercontent.com/33176053/91640124-dd09a680-ea4d-11ea-94eb-ab602f5b65f2.png)

Then I checked the API of Element2's `Checkbox` components and found that the type of `label` is `string / number / boolean`.  But now it receives the type is `[Object, Boolean, String]`, is there missing `Number`?

```
label: {
  type: [Object, Boolean, String],
  default: '  ',
},
```

**modelValue:**
I also found that the type  of `modelValue` is `[Object, Boolean]`, why the type of `modelValue` can be `Object`? Shouldn't it always be a `Boolean`?

In my test, when use `Checkbox` component individually, the `modelValue` will change to a `Boolean` value if pass a object to `modelValue` and change the status of it.

```
modelValue: {
  type: [Object, Boolean],
  default: () => undefined,
},
```

**Comment by Ryan2128** [comment]
Link to `Checkbox` [migration issue](https://github.com/element-plus/element-plus/issues/109)

cc @zouhangwithsweet.

**Comment by zouhangwithsweet** [comment]
I will fix it in a new branch

**Comment by Ryan2128** [comment]
> I will fix it in a new branch

OK.
