### ISSUE TITLE
Table Expandable issue

### ISSUE THREAD

**Issue by hirenreshamwala** [element-plus/element-plus#2233]
# el-table Expandable row
When we add el-form inside expandable content, the expansion will auto close if any form controls value change.
Working fine with element-ui

Expand the row in both examples and try to change input as well as the dropdown

#### Element plus
[https://codepen.io/hirenreshamwala/pen/yLMRRXE](https://codepen.io/hirenreshamwala/pen/yLMRRXE)

#### Element UI
[https://codepen.io/hirenreshamwala/pen/gOmBBGg](https://codepen.io/hirenreshamwala/pen/gOmBBGg)

**Comment by msidolphin** [comment]
try to use row-key?

**Comment by hirenreshamwala** [comment]
#### Thanks @msidolphin 

row-key works

**Comment by HerringtonDarkholme** [comment]
Minimal reproduciton:

https://codepen.io/herringtondarkholme/pen/yLMGaRa

**Comment by HerringtonDarkholme** [comment]
I think we should use `$index` as default key. Opinion? @JeremyWuuuuu @justwiner ?

**Comment by HerringtonDarkholme** [comment]
****
