### ISSUE TITLE
[Bug Report] TimePicker and DateTimePicker hours issue

### ISSUE THREAD

**Issue by laurisstepanovs** [element-plus/element-plus#2239]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Mac OS/ Version 91.0.4472.77 (Official Build) (x86_64)

### Vue version
3.1.1

### Steps to reproduce
Add new data time picker component

{{ value1 }}
<el-date-picker
  v-model="value1"
  type="datetime"
  placeholder="Select date and time"
>

### What is Expected?
I am expecting to v-model the actual time from the datetimepicker.

### What is actually happening?
When I am selecting hours it does not display the actual hours from the time picker but it shows the current time picker selected time -3 hours.

![Screenshot 2021-06-14 at 04 13 02](https://user-images.githubusercontent.com/33573735/121828224-a4c71200-ccc7-11eb-8b17-975ae209f7a0.png)

**Comment by kooriookami** [comment]
The value used UTC format. It's correct.
