### ISSUE TITLE
[Feature Request] use CSS3 var to refactor theme-chalk

### ISSUE THREAD

**Issue by YunYouJun** [element-plus/element-plus#2242]
### Existing Component
Yes

### Component Name
theme-chalk

### Description

> Many themes now support switching between bright and dark modes.
> We can also use [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) and [var](https://developer.mozilla.org/zh-CN/docs/Web/CSS/var()) to achieve it.

I see that many variables in `theme-chalk` are fixed, and it is completely possible for us to use CSS3 `var` to achieve it.

Users can more easily customize the theme by overriding the value of CSS3 `var` without recompiling scss.

The migration process of development is basically without impact.

For example, `--el-font-color: $--font-color;`

If you think this proposal is good, I would be happy to contribute code for it.

**Comment by kooriookami** [comment]
The idea sounds great! PR is always welcome.

**Comment by YunYouJun** [comment]
Thanks.
I plan to use `--element` as the prefix name, any other suggestions?

Because there are many components, I plan to migrate them component by component.
And in the future, different colors will be provided for `light` and `dark` modes.

**Comment by kooriookami** [comment]
I sent an e-mail(me@yunyoujun.cn) to invite you join our team. :D

**Comment by Christopher-Simmons** [comment]
This would be great! Currently I'm experiencing UI bugs when using a custom theme, it would be much better to just override the color variables

**Comment by YunYouJun** [comment]
> This would be great! Currently I'm experiencing UI bugs when using a custom theme, it would be much better to just override the color variables

Yeah, it is under development, and it may take some time to fully migrate.

**Comment by simmonschris1984** [comment]
> > This would be great! Currently I'm experiencing UI bugs when using a custom theme, it would be much better to just override the color variables
> 
> Yeah, it is under development, and it may take some time to fully migrate.

Excellent! I have plenty of time, thank you for your effort on this.

**Comment by oliverzy** [comment]
It looks very promising!
Vant 3.1 has finished the movement.

**Comment by wwbluechip** [comment]
> > This would be great! Currently I'm experiencing UI bugs when using a custom theme, it would be much better to just override the color variables
> 
> Yeah, it is under development, and it may take some time to fully migrate.

hey bro,how is the progress?

**Comment by YunYouJun** [comment]
> hey bro,how is the progress?

Hey, you can check the current migration progress by <https://github.com/element-plus/element-plus/pulls?q=label%3A%22css+migration%22>.

We have completed the overall design and migrated half of the components.

Of course, there are still a lot of details that need to be optimized, and we'll write a full migration guide when we're done, along with a example of custom theme.

**Comment by wwbluechip** [comment]
> > hey bro,how is the progress?
> 
> Hey, you can check the current migration progress by https://github.com/element-plus/element-plus/pulls?q=label%3A%22css+migration%22.
> 
> We have completed the overall design and migrated half of the components.
> 
> Of course, there are still a lot of details that need to be optimized, and we'll write a full migration guide when we're done, along with a example of custom theme.

thanks a lot.

**Comment by KawaiiZapic** [comment]
Maybe a little presumptuous, is this change causing a performace problem in devtools?  
With the hot replace, css will be re-add into the document without remove old css.  
after some edit, there are a ton of css variable in the `:root` scope, like this:
![A ton of css variable](https://user-images.githubusercontent.com/45936772/127098061-84d0e2e5-f930-4332-b5e8-def6fb38e094.png)
And this will be listed in any element in the document, because these variable is defined in the `:root`  
It will take a really long time to wait the devtools list all this variable.   
  
  
The idea to refactor these variable with css3 is great, but is there any solution for this performace problem?  
Now I can only restart the dev server to clean up this code, is there any better solution?

**Comment by YunYouJun** [comment]
@KawaiiZapic 

For css variable performance issues, you can refer to this.
> https://lisilinhart.info/posts/css-variables-performance/

The css variable does have performance issues, although its advantages are obvious (theme color/light/dark/runtime).
Some frameworks have also experimented with using css variables to build their styles. 

> [material-components-web-components](https://github.com/material-components/material-components-web-components), [vant](https://github.com/youzan/vant)

In theory, the performance impact of css variables is acceptable.

We move the css var variables to the css of each component.
If you care about performance issues, you should introduce your components on demand.

---

Of course, you are right. We will also cut back on css variables to achieve a balance between sass variables and css variables, convenience and performance.

But you know, due to limited effort, the beta version of the migration process will inevitably have some problems. You are welcome to make any suggestions during this period.

**Comment by KawaiiZapic** [comment]
> @KawaiiZapic
> 
> For css variable performance issues, you can refer to this.
> 
> > https://lisilinhart.info/posts/css-variables-performance/
> 
> The css variable does have performance issues, although its advantages are obvious (theme color/light/dark/runtime).
> Some frameworks have also experimented with using css variables to build their styles.
> 
> > [material-components-web-components](https://github.com/material-components/material-components-web-components), [vant](https://github.com/youzan/vant)
> 
> In theory, the performance impact of css variables is acceptable.
> 
> We move the css var variables to the css of each component.
> If you care about performance issues, you should introduce your components on demand.
> 
> Of course, you are right. We will also cut back on css variables to achieve a balance between sass variables and css variables, convenience and performance.
> 
> But you know, due to limited effort, the beta version of the migration process will inevitably have some problems. You are welcome to make any suggestions during this period.

I know that the css variable performance losing can be ignored.  
  
But I mean, a tons of css variable will be listed in the devtools, that causing the devtools slowly response. The Chrome Devtools take a long time to list these variable out, indirectly make the app is not able to debug.   
So these variables are causing a __devtools__ performance issue, not the application performance issue.
The performance issue of devtools make debugging app with element-plus is nearly impossible.

**Comment by YunYouJun** [comment]
> I know that the css variable performance losing can be ignored.
> 
> But I mean, a tons of css variable will be listed in the devtools, that causing the devtools slow response. The Chrome Devtools take a long time to list these variable out, indirectly make the app is not able to debug.
> So these variables are causing a **devtools** performance issue, not the application performance issue.
> 
> For me, I frequently use devtools to preview the results of changing css code, or find out what messing up the layout.
> The performance issue of devtools causes that is nearly impossible to debug app with element-plus.

I'm sorry. I'm not sure I understand.
Css Var does take up a large part of your DevTool interface by default, but it shouldn't affect debugging performance.

**Comment by KawaiiZapic** [comment]
> > I know that the css variable performance losing can be ignored.
> > But I mean, a tons of css variable will be listed in the devtools, that causing the devtools slow response. The Chrome Devtools take a long time to list these variable out, indirectly make the app is not able to debug.
> > So these variables are causing a **devtools** performance issue, not the application performance issue.
> > For me, I frequently use devtools to preview the results of changing css code, or find out what messing up the layout.
> > The performance issue of devtools causes that is nearly impossible to debug app with element-plus.
> 
> I'm sorry. I'm not sure I understand.
> Css Var does take up a large part of your DevTool interface by default, but it shouldn't affect debugging performance.
  
Maybe a my CPU is out of date.  
This is devtool with ElementPlus-beta-48:
![beta-48](https://user-images.githubusercontent.com/45936772/127632057-73009cc3-7633-4391-84c2-5e939a391623.gif)
And this is with ElementPlus-beta-65:
![beta-65](https://user-images.githubusercontent.com/45936772/127632064-1410c3c8-0f6b-4b3c-b5a1-3f2733cbb310.gif)   

\* I have overclocked my CPU, now it got 72% single core performace of Intel i7-7700K(testing with CPU-Z). I think this is enough to develop frontend, and can catch up most modern middle end CPU.

**Comment by scarsu** [comment]
> > I'm sorry. I'm not sure I understand.
> > Css Var does take up a large part of your DevTool interface by default, but it shouldn't affect debugging performance.
> 
> Maybe a my CPU is out of date.
> This is devtool with ElementPlus-beta-48:
> ![beta-48](https://user-images.githubusercontent.com/45936772/127632057-73009cc3-7633-4391-84c2-5e939a391623.gif)
> And this is with ElementPlus-beta-65:
> ![beta-65](https://user-images.githubusercontent.com/45936772/127632064-1410c3c8-0f6b-4b3c-b5a1-3f2733cbb310.gif)
> As the gif, devtools hang for 3s.
> 
> I think this idea is great, now it's much flexible then before, bring us a better coding experience.
> But it is not affordable to developer using middle end or worse computer. It need a better way to be implemented.
> 
> * I have overclocked my CPU(a gen3 i5), now it got 72% single core performace of Intel i7-7700K(testing with CPU-Z). I think this is enough to develop frontend, and can catch up most modern middle end CPU.

same for me

**Comment by YunYouJun** [comment]
@KawaiiZapic I understand what you mean. This may be related to the current packaging method. We are trying a new way to remove some variables and be repeatedly packaged.
We will try to reduce the css var exposed by each component, so as to achieve the convenience of custom variables, and at the same time, there are as few variables as possible.
Before that, you can temporarily downgrade back to beta.55. When the optimization of the variables is completed, we will have a complete migration document.
Thanks again for your suggestions.

**Comment by Dirian9754** [comment]
> > 抱歉。我不确定我是否理解。
> > 默认情况下，Css Var 确实占据了 DevTool 界面的很大一部分，但它不应该影响调试性能。
> 
> 也许我的 CPU 已经过时了。
> 这是带有 ElementPlus-beta-48 的 devtool： 这是带有 ElementPlus-beta-65 的： 作为 gif，devtools 挂起 3 秒。
> ![β-48](https://user-images.githubusercontent.com/45936772/127632057-73009cc3-7633-4391-84c2-5e939a391623.gif)
> 
> ![β-65](https://user-images.githubusercontent.com/45936772/127632064-1410c3c8-0f6b-4b3c-b5a1-3f2733cbb310.gif)
> 
> 我觉得这个想法很棒，现在它比以前灵活多了，给我们带来了更好的编码体验。
> 但是使用中端或更差的计算机的开发人员负担不起。它需要一种更好的方式来实现。
> 
> * 我已经超频了我的 CPU（第 3 代 i5），现在它的单核性能达到了英特尔 i7-7700K 的 72%（使用 CPU-Z 测试）。我认为这足以开发前端，并且可以赶上大多数现代中端CPU。

me too

**Comment by YunYouJun** [comment]
We have moved it for every component class to avoid performance problem by global var. Just wait next released version `beta.68`.

**Comment by 1165468011** [comment]
> 我们已经为每个组件类移动了它，以避免全局变量的性能问题。只需升级到`beta.69`。

我现在正在使用beta.70， 但是我发现.el-button--primary并未使用css3 var变量，请问是故意如此还是没来得及迁移呢，或者是应该以什么样的方式来修改.el-button--primary的各种颜色

**Comment by YunYouJun** [comment]
> 我现在正在使用beta.70， 但是我发现.el-button--primary并未使用css3 var变量，请问是故意如此还是没来得及迁移呢，或者是应该以什么样的方式来修改.el-button--primary的各种颜色

Unfortunately, the variables in button use sass's `mix` function to blend the corresponding shadows and dark effects as a percentage, and pure CSS variables can not implement mix functionality.
We're also thinking about how to implement it more gracefully, whether to add a new mixed button variable, or something else.

You can change sass first by setting it up.

```scss
$--colors: (
  'primary': (
    'base': xxx
  )
);
```

Or just set button var.

```scss
$--button-border-color: (
  'primary': xxx
);
$--button-background-color: (
  'primary': xxx
);
$--button-font-color: (
  'primary': xxx
);
```

We will also give a pure css var as soon as possible in the future what we can try.

**Comment by 1165468011** [comment]
谢谢您对el的贡献，我通过修改scss变量的方式修改Button颜色会导致按需引入时出现BUG，刷新时颜色无问题，一切换路由就无效，不知道怎么解决，希望能尽早提供css3&nbsp; var的方式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月7日(星期六) 凌晨0:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Feature Request] use CSS3 var to refactor theme-chalk (#2242)





  
我现在正在使用beta.70， 但是我发现.el-button--primary并未使用css3 var变量，请问是故意如此还是没来得及迁移呢，或者是应该以什么样的方式来修改.el-button--primary的各种颜色
  
Unfortunately, the variables in button use sass's mix function to blend the corresponding shadows and dark effects as a percentage, and pure CSS variables can not implement mix functionality.
 We're also thinking about how to implement it more gracefully, whether to add a new mixed button variable, or something else.
 
You can change sass first by setting it up.
 $--colors: (   'primary': (     'base': xxx   ) );
 
Or just set button var.
 $--button-border-color: (   'primary': xxx ); $--button-background-color: (   'primary': xxx ); $--button-font-color: (   'primary': xxx );
 
We will also give a pure css var as soon as possible in the future what we can try.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wwbluechip** [comment]
> > 我现在正在使用beta.70， 但是我发现.el-button--primary并未使用css3 var变量，请问是故意如此还是没来得及迁移呢，或者是应该以什么样的方式来修改.el-button--primary的各种颜色
> 
> Unfortunately, the variables in button use sass's `mix` function to blend the corresponding shadows and dark effects as a percentage, and pure CSS variables can not implement mix functionality.
> We're also thinking about how to implement it more gracefully, whether to add a new mixed button variable, or something else.
> 
> You can change sass first by setting it up.
> 
> ```css-scss
> $--colors: (
>   'primary': (
>     'base': xxx
>   )
> );
> ```
> 
> Or just set button var.
> 
> ```css-scss
> $--button-border-color: (
>   'primary': xxx
> );
> $--button-background-color: (
>   'primary': xxx
> );
> $--button-font-color: (
>   'primary': xxx
> );
> ```
> 
> We will also give a pure css var as soon as possible in the future what we can try.

请问这个文件写在哪里？我新建了一个scss文件写了这个，并在main.ts引入了，但button主题并没有生效

**Comment by KawaiiZapic** [comment]
`el-dialog` still using inline style to modify style:
![InlineStyle](https://user-images.githubusercontent.com/45936772/133124195-8f346418-fc41-446f-a7c9-112ac857e536.png)

**Comment by YunYouJun** [comment]
> `el-dialog` still using inline style instead css var:
> ![InlineStyle](https://user-images.githubusercontent.com/45936772/133124195-8f346418-fc41-446f-a7c9-112ac857e536.png)

I create a PR to optimize it. https://github.com/element-plus/element-plus/pull/3431

**Comment by zhixiaotong** [comment]
@YunYouJun 非常感谢，我已经在使用css variable为我的应用添加主题切换，目前也遇到了button颜色未被覆盖的问题。等解决中...

Thank you very much. I have been using css variable to add theme switching to my application, and I am currently experiencing the problem that the button color is not covered. Waiting to be resolved...

**Comment by YunYouJun** [comment]
> @YunYouJun 非常感谢，我已经在使用css variable为我的应用添加主题切换，目前也遇到了button颜色未被覆盖的问题。等解决中...

Can you open a issue? And provide a example?


New custom theme doc is here: https://staging.element-plus.org/en-US/guide/theming.html

It will be merged into master after stabilization.

**Comment by 634323580** [comment]
> > > 我现在正在使用beta.70，但是我发现了.el-button-primary 使用css3 var变量，希望是故意如此没得及迁移呢，或者应该是应该做出的方式来修改。el-button- -原色的各种颜色
> > 
> > 
> > 遗憾的是，button 中的变量使用sass 的`mix`函数来混合对应的阴影和深色效果的百分比，纯CSS 变量无法实现混合功能。
> > 我们也在考虑如何更优雅地实现它，是添加一个新的混合按钮变量，还是其他什么。
> > 您可以先通过设置来更改 sass。
> > ```
> > $--colors: (
> >   'primary': (
> >     'base': xxx
> >   )
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者只是设置按钮变量。
> > ```
> > $--button-border-color: (
> >   'primary': xxx
> > );
> > $--button-background-color: (
> >   'primary': xxx
> > );
> > $--button-font-color: (
> >   'primary': xxx
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以后可以尝试的，我们也会尽快给出一个纯css var。
> 
> 好像这个文件写在哪里？我新建了一个scss文件写了这个，并在main.ts引入了，但button主题并没有生效

我也是没有生效，请问有解决了吗？

**Comment by 634323580** [comment]
> > @YunYouJun非常感谢，我已经在使用css变量为我的应用添加了主题切换，目前也遇到了按钮无法覆盖的问题。等解决中...
> 
> 你能打开一个问题吗？并提供一个例子？
> 
> 新的自定义主题文档在这里：[https](https://staging.element-plus.org/en-US/guide/theming.html) : [//staging.element-plus.org/en-US/guide/theming.html](https://staging.element-plus.org/en-US/guide/theming.html)
> 
> 稳定后会合并到master。

按照文档通过 SCSS 变量覆盖没有生效

> > @YunYouJun非常感谢，我已经在使用css变量按钮为我的应用添加了主题切换，目前也遇到了无法覆盖的问题。等解决中...
> 
> 你能打开一个问题吗？并提供一个例子？
> 
> 新的自定义主题文档在这里：[https](https://staging.element-plus.org/en-US/guide/theming.html) : [//staging.element-plus.org/en-US/guide/theming.html](https://staging.element-plus.org/en-US/guide/theming.html)
> 
> 稳定后会合并到master。

按照文档通过 SCSS 变量覆盖没有生效，只能通过以下方式

```
:root {
  --el-color-primary: #b42373;
}
```

**Comment by kangjiancheng** [comment]
> > > @YunYouJun非常感谢，我已经在使用css变量为我的应用添加了主题切换，目前也遇到了按钮无法覆盖的问题。等解决中...
> > 
> > 
> > 你能打开一个问题吗？并提供一个例子？
> > 新的自定义主题文档在这里：[https](https://staging.element-plus.org/en-US/guide/theming.html) : [//staging.element-plus.org/en-US/guide/theming.html](https://staging.element-plus.org/en-US/guide/theming.html)
> > 稳定后会合并到master。
> 
> 按照文档通过 SCSS 变量覆盖没有生效
> 
> > > @YunYouJun非常感谢，我已经在使用css变量按钮为我的应用添加了主题切换，目前也遇到了无法覆盖的问题。等解决中...
> > 
> > 
> > 你能打开一个问题吗？并提供一个例子？
> > 新的自定义主题文档在这里：[https](https://staging.element-plus.org/en-US/guide/theming.html) : [//staging.element-plus.org/en-US/guide/theming.html](https://staging.element-plus.org/en-US/guide/theming.html)
> > 稳定后会合并到master。
> 
> 按照文档通过 SCSS 变量覆盖没有生效，只能通过以下方式
> 
> ```
> :root {
>   --el-color-primary: #b42373;
> }
> ```

你需要vite config里引入这个变量文件，然后 就可以通过官方的那个scss变量覆盖。
然后：我使用这个root方式不生效，被官方覆盖了，在devtool里 我的优先级比较低，在最下面，为什么啊？
`:root {
  --el-color-primary: #b42373;
}`

**Comment by YunYouJun** [comment]
css 是后覆盖前，scss 变量则留了默认值，是前覆盖后，注意两者顺序区别。

I will create a theme customization example in https://github.com/element-plus/element-plus-vite-starter. Just wait one day?

**Comment by YunYouJun** [comment]
I made a example about how to custom theme color.

Try this. [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter)
