### ISSUE TITLE
[bug report] date picker component

### ISSUE THREAD

**Issue by GuoYi666** [element-plus/element-plus#2245]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
macos最新 chrome最新

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/guoyi666/pen/poeqRoZ

### Steps to reproduce
vue3 使用date-picker组件的时候，点击选择日期  组件不显示，查看代码   还是display：none，未变成block

### What is Expected?
vue3 使用date-picker组件的时候，点击选择日期  组件不显示，查看代码   还是display：none，未变成block

### What is actually happening?
vue3 使用date-picker组件的时候，点击选择日期  组件不显示，查看代码   还是display：none，应变成block

**Comment by iamkun** [comment]
Please check here for more reference https://element-plus.org/#/zh-CN/component/date-picker
