### ISSUE TITLE
[bug report] index.full.js uses define ('elementplus', [], t) to define the module, and does not introduce Vue dependency. When requirejs is introduced, Vue is null

### ISSUE THREAD

**Issue by exvu** [element-plus/element-plus#2251]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
chrome

### Vue version
3.1.1

### Steps to reproduce
使用requirejs引入element-plus 通过require引入

### What is Expected?
requirejs引入element-plus vue 能正常使用

### What is actually happening?
Cannot read property 'defineComponent' of undefined 研究源码发现index.full.js 使用 define('elementPlus',[],t)定义模块，并没有引入vue依赖，requirejs引入时出现Vue 为null

**Comment by sxzz** [comment]
Please provide a reproduction link.
