### ISSUE TITLE
[bug report] Wrong resource path under es package

### ISSUE THREAD

**Issue by code-farmer-i** [element-plus/element-plus#2252]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
mac Chrome

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/bitter-sea-0o9vr?file=/src/main.js

### Steps to reproduce
引入es模块下的资源

### What is Expected?
正常使用

### What is actually happening?
内部资源路径错误，导致编译失败。

**Comment by code-farmer-i** [comment]
希望下个版本尽快修复啊，我们现在固定在1.0.2-beta.46版本，感谢！

**Comment by climba03003** [comment]
I have posted the workaround for `vite` here. You may modify it for `vue-cli` if you need.
https://github.com/element-plus/element-plus-vite-starter/issues/15

**Comment by code-farmer-i** [comment]
> I have posted the workaround for `vite` here. You may modify it for `vue-cli` if you need.
> [element-plus/element-plus-vite-starter#15](https://github.com/element-plus/element-plus-vite-starter/issues/15)

Thanks

**Comment by JeremyWuuuuu** [comment]
实在不好意思这么晚才回复，现在应该是没有这个问题了吧？@code-farmer-i

**Comment by code-farmer-i** [comment]
> 实在不好意思这么晚才回复，现在应该是没有这个问题了吧？@code-farmer-i

嗯 现在的版本已经解决了

**Comment by JeremyWuuuuu** [comment]
@code-farmer-i 实在是抱歉 :pray:
