### ISSUE TITLE
[Bug Report] Table component “expand-row-keys ” properties do not work

### ISSUE THREAD

**Issue by Tomxuetao** [element-plus/element-plus#2253]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
mac Chrome

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/tomxuetao/pen/rNyoXwe

### Steps to reproduce
https://codepen.io/tomxuetao/pen/rNyoXwe

### What is Expected?
There is "row key", but the first line of ": expand row keys = [1]" is expanded

### What is actually happening?
There is "row key", but the first line of ": expand row keys = [1]" is not expanded

**Comment by sxzz** [comment]
Could you please provide a reproduction link and feel free to reopen it.
