### ISSUE TITLE
[Bug Report] V-model z

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#2258]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/2qrkbeuw/

### Steps to reproduce
 did build a form with Element Plus (https://element-plus.org/#/en-US/component/select). Specific: Basic Multiple Select.

The problem I have is that the Element Plus element (Basis Multiple Select) works with v-model. From the API I retrieve the following output in JSON: [1, 2] which is fieldData[field.field].

If I use v-model, it won't work as v-model does not accept JSON I think. The selected options aren't visible. How can I JSON parse in V-model or do I need to fix it otherwise?

### What is Expected?
If I change the code to: v-model="value2" and add data to the component (check below) it is working.

data() {
 return {
   value2: [1, 2]
 }
}

### What is actually happening?
If I use v-model, it won't work as v-model does not accept JSON I think. The selected options aren't visible. How can I JSON parse in V-model or do I need to fix it otherwise?

**Comment by kooriookami** [comment]
Your demo is incomplete, can you provide simplest one?
