### ISSUE TITLE
[Feature Request] Repeater

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#2260]
### Existing Component
No

### Component Name
Repeater

### Description
A repeater module for forms. (Input fields e.g.) with the option to add lines and remove it dynamicly.

**Comment by kooriookami** [comment]
Could you provide a specific description?

**Comment by nhatimme** [comment]
@kooriookami Done.

**Comment by kooriookami** [comment]
Do you mean this?
https://element-plus.org/#/en-US/component/form#delete-or-add-form-items-dynamically
