### ISSUE TITLE
There is a bug in the selector component. When dynamically binding the loading attribute, the expansion direction of the drop-down box is wrong

### ISSUE THREAD

**Issue by Anqi0324** [element-plus/element-plus#2262]
作者你好，选择器组件，在动态绑定 loading 时，展开下拉框会横向展示

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/122402684-4abc9a00-cfb0-11eb-823a-d90ee7fbf432.png)
是这种情况吗？空间不足，导致下拉菜单横向展示，和 loading 无关。

**Comment by Anqi0324** [comment]
> ![image](https://user-images.githubusercontent.com/38392315/122402684-4abc9a00-cfb0-11eb-823a-d90ee7fbf432.png)
> 是这种情况吗？空间不足，导致下拉菜单横向展示，和 loading 无关。

是的呢~不过被我组合到 form 中使用的时候就没有该问题啦

**Comment by kooriookami** [comment]
你可以更新一下最新版本，我们调整了下拉菜单的默认弹出位置，优先级是下→上→右→左，应该可以解决你遇到的问题。

**Comment by Anqi0324** [comment]
> 你可以更新一下最新版本，我们调整了下拉菜单的默认弹出位置，优先级是下→上→右→左，应该可以解决你遇到的问题。

好滴。谢谢
