### ISSUE TITLE
[bug report] Select drop-down list and placeholder are not displayed

### ISSUE THREAD

**Issue by lijiu-b** [element-plus/element-plus#2265]
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
win7 / google chrome Version 87.0.4259.3 (Official Build) dev (64-bit)

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/lijiu-b/pen/eYvXBME

### Steps to reproduce
win7   vue3.0.0   ts   nodejs12 这个组合时select的下拉列表、placeholder、设置的值都不显示，但是也不报错

win10    vue3.0.0   ts   nodejs14 这个组合时正常

### What is Expected?
能解决一下这个问题

### What is actually happening?
win7   vue3.0.0   ts   nodejs12 这个组合时select的下拉列表、placeholder、设置的值都不显示，但是也不报错

win10    vue3.0.0   ts   nodejs14 这个组合时正常

**Comment by kooriookami** [comment]
Update element-plus to the latest version and try again.
