### ISSUE TITLE
[Bug Report] [Cascader] When the width is 100%, the arrow is misaligned

### ISSUE THREAD

**Issue by eAliwei** [element-plus/element-plus#2266]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
MacOS 10.15.7 Chrome 91.0.4472.114

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/qbxLg2mo/

### Steps to reproduce
see this https://jsfiddle.net/qbxLg2mo/

### What is Expected?
see this https://jsfiddle.net/qbxLg2mo/

### What is actually happening?
see this https://jsfiddle.net/qbxLg2mo/

**Comment by kooriookami** [comment]
Not reproduced. Do you have a screenshot?

**Comment by eAliwei** [comment]
@kooriookami 
Attached a screenshot
![image](https://user-images.githubusercontent.com/6028737/122533235-e6531680-d053-11eb-91ba-c20b8ff2e2bc.png)

![image](https://user-images.githubusercontent.com/6028737/122533301-f834b980-d053-11eb-9115-5b945347a418.png)
