### ISSUE TITLE
[Bug Report] el-image error event handler called multiple times

### ISSUE THREAD

**Issue by ekoooo** [element-plus/element-plus#2269]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
版本 90.0.4430.212（正式版本） （64 位）

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/w9sh7r6v/1/

### Steps to reproduce
run: https://jsfiddle.net/w9sh7r6v/1/
1. el-image error event handler called **three times**.
2. when i add `v-if="scope.row['img']"` condition to el-image, handler will be called **twice**.
3. after remove `fixed` attribute from `<el-table-column width="100" align="center" label="操作"  fixed="right">`, will be normal.

### What is Expected?
el-image error event handler should called once

### What is actually happening?
el-image error event handler called multiple

**Comment by kooriookami** [comment]
Similar to #2147

**Comment by ekoooo** [comment]
@kooriookami 你好，这个问题在最新版本中依然存在，see: https://jsfiddle.net/g8ue4wts/6/

**Comment by kooriookami** [comment]
> @kooriookami 你好，这个问题在最新版本中依然存在，see: https://jsfiddle.net/g8ue4wts/6/

Yes, we will release it in next version.
