### ISSUE TITLE
[Bug Report] DatePicker and DateTimePicker Component have a lot Vue Warning in browser console.log

### ISSUE THREAD

**Issue by YuancaiDing** [element-plus/element-plus#2271]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ppb8d?file=/src/App.vue

### Steps to reproduce
The official document page is producing the issue, open following link and check browser console.

https://element-plus.gitee.io/#/zh-CN/component/datetime-picker

https://element-plus.gitee.io/#/zh-CN/component/date-picker

### What is Expected?
Component should not have warning message

### What is actually happening?
main.8e33361877bdda519b2b.js:1656 [Vue warn]: Extraneous non-props attributes (align) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ElPopper ref="refPopper" visible=false onUpdate:visible=fn  ... > 
  at <Picker disabledDate=fn<disabledDate> name="" popperClass=""  ... > 
  at <ElDatePicker modelValue="" onUpdate:modelValue=fn align="right"  ... > 
  at <Anonymous> 
  at <DemoBlock> 
  at <ComponentDoc class="content" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <AsyncComponentWrapper class="content" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView class="content" > 
  at <ElScrollbar ref="componentScrollBar" class="page-component__scroll" > 
  at <Anonymous onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {addContentObserver: ƒ, renderAnchorHref: ƒ, goAnchor: ƒ, handleScroll: ƒ, …} > > 
  at <AsyncComponentWrapper onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {addContentObserver: ƒ, renderAnchorHref: ƒ, goAnchor: ƒ, handleScroll: ƒ, …} > > 
  at <RouterView> 
  at <App>

**Comment by kooriookami** [comment]
The align prop is no longer used, so remove it is fine.

**Comment by ChenWeihua123** [comment]
@kooriookami what instead of it?
