### ISSUE TITLE
[bug report] style error when using post elements of compound input box

### ISSUE THREAD

**Issue by Aoyamakiri** [element-plus/element-plus#2273]
### Element Plus version
1.0.2-beta.47

### OS/Browsers version
windows/Google Chrome 91.0.4472.106

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0mll0?file=/src/App.vue

### Steps to reproduce
创建复合型输入框，使用后置元素，当后置元素为botton时且设置为disable出现样式错误（当该元素被focus时）

### What is Expected?
后置button元素样式完整

### What is actually happening?
后置button元素下方样式丢失

**Comment by XingXiaoWu** [comment]
https://codesandbox.io/s/element-plus-spa-forked-ozbh5?file=/src/App.vue

Is that what you expect? Maybe you can do it with CSS
