### ISSUE TITLE
[Bug Report]  icons cannot be displayed

### ISSUE THREAD

**Issue by LiuWenXing1996** [element-plus/element-plus#2277]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
chrome/edge

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/sad-neumann-m8b4k?file=/src/App.vue

### Steps to reproduce
打开上面的项目链接，会发现左侧的页面结果里面的图标没有显示出来
![image](https://user-images.githubusercontent.com/71174044/122652165-f3652800-d16f-11eb-964e-0251e7cf62b4.png)

### What is Expected?
图标应该显示出来

### What is actually happening?
图标没有显示出来

**Comment by someGenki** [comment]
我也遇到了这个问题了，老哥解决了吗

**Comment by someGenki** [comment]
> 我也遇到了这个问题了，老哥解决了吗

我是 "vite": "2.3.7" => "vite": "^2.3.8" 导致的，降回2.3.7就可以了耶😂

**Comment by LiuWenXing1996** [comment]
> > 我也遇到了这个问题了，老哥解决了吗
> 
> 我是 "vite": "2.3.7" => "vite": "^2.3.8" 导致的，降回2.3.7就可以了耶😂

我本地用vite 2.3,7 测试了下，还是有这个问题，我开的这个codesandbox的这个项目https://codesandbox.io/s/sad-neumann-m8b4k?file=/src/App.vue用的是vue-cli，也有这个问题

**Comment by LiuWenXing1996** [comment]
> > > 我也遇到了这个问题了，老哥解决了吗
> > 
> > 
> > 我是 "vite": "2.3.7" => "vite": "^2.3.8" 导致的，降回2.3.7就可以了耶😂
> 
> 我本地用vite 2.3,7 测试了下，还是有这个问题，我开的这个codesandbox的这个项目https://codesandbox.io/s/sad-neumann-m8b4k?file=/src/App.vue 用的是vue-cli，也有这个问题

我刚才又试了下vite 2.3.7 版本，图标可以显示出来了，之前应该是我的vite版本没有修改成功，还是原来的2.3.8

**Comment by LiuWenXing1996** [comment]
不过，为什么这个vue-cli项目 https://codesandbox.io/s/sad-neumann-m8b4k?file=/src/App.vue 也会出现这个问题就不太清楚了

**Comment by hooray** [comment]
持续关注，今天vite也遇到这个问题了

**Comment by twelvescore** [comment]
我也遇到了同样的问题，在线急等解决！

**Comment by rieval** [comment]
Vite 同样的问题，之前 `beta.44` 还没这问题，应该是 `vue` 带来的

```json
"dependencies": {
  "element-plus": "^1.0.2-beta.48",
  "vue": "^3.1.1",
  "vue-router": "^4.0.9",
  "vuex": "^4.0.2"
}
```

**Comment by someGenki** [comment]
> Vite 同样的问题，之前 `beta.44` 还没这问题，应该是 `vue` 带来的
> 
> ```json
> "dependencies": {
>   "element-plus": "^1.0.2-beta.48",
>   "vue": "^3.1.1",
>   "vue-router": "^4.0.9",
>   "vuex": "^4.0.2"
> }
> ```
> 
> 编辑：
> 试了下回滚到更新包之前的状态，还是会有这个问题，是缓存的原因？

node_module\vite\package.json看看版本号就清楚了

**Comment by rieval** [comment]
> > Vite 同样的问题，之前 `beta.44` 还没这问题，应该是 `vue` 带来的
> > ```json
> > "dependencies": {
> >   "element-plus": "^1.0.2-beta.48",
> >   "vue": "^3.1.1",
> >   "vue-router": "^4.0.9",
> >   "vuex": "^4.0.2"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 编辑：
> > 试了下回滚到更新包之前的状态，还是会有这个问题，是缓存的原因？
> 
> node_module\vite\package.json看看版本号就清楚了

版本号是没问题的，我是先卸载再安装

**Comment by twelvescore** [comment]
> > > Vite 同样的问题，之前 `beta.44` 还没这问题，应该是 `vue` 带来的
> > > ```json
> > > "dependencies": {
> > >   "element-plus": "^1.0.2-beta.48",
> > >   "vue": "^3.1.1",
> > >   "vue-router": "^4.0.9",
> > >   "vuex": "^4.0.2"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 编辑：
> > > 试了下回滚到更新包之前的状态，还是会有这个问题，是缓存的原因？
> > 
> > 
> > node_module\vite\package.json看看版本号就清楚了
> 
> 版本号是没问题的，我是先卸载再安装
> 
> 编辑：
> 哦你说 `Vite` 啊，我没留意你前面说的，试了下 `Vite` 回滚到 `2.3.7` 确实问题解决了。

我这儿怎么弄都不行，能发一下你的package.json我试下可以吗？

**Comment by rieval** [comment]
> > > > Vite 同样的问题，之前 `beta.44` 还没这问题，应该是 `vue` 带来的
> > > > ```json
> > > > "dependencies": {
> > > >   "element-plus": "^1.0.2-beta.48",
> > > >   "vue": "^3.1.1",
> > > >   "vue-router": "^4.0.9",
> > > >   "vuex": "^4.0.2"
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 编辑：
> > > > 试了下回滚到更新包之前的状态，还是会有这个问题，是缓存的原因？
> > > 
> > > 
> > > node_module\vite\package.json看看版本号就清楚了
> > 
> > 
> > 版本号是没问题的，我是先卸载再安装
> > 编辑：
> > 哦你说 `Vite` 啊，我没留意你前面说的，试了下 `Vite` 回滚到 `2.3.7` 确实问题解决了。
> 
> 我这儿怎么弄都不行，能发一下你的package.json我试下可以吗？

我就仅仅回滚一下 `Vite` 版本就解决了，不知道你那边是什么情况

你可以先试着卸载 `Vite` ：
```bash
npm uninstall vite
```
然后安装指定版本看看行不行：
```bash
npm install vite@2.3.7
```

**Comment by youzizi1** [comment]
遇到同样的问题，mark一下

**Comment by jcindex** [comment]
回退到vite@2.3.7没问题了

**Comment by sunwe** [comment]
最终原因已找到，index.css中的font-face是这样：@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff"),url(fonts/element-icons.ttf) format("truetype");
vite@2.3.8对于这部分处理，变成了@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff") url(fonts/element-icons.ttf) format("truetype");多个url中间的一个逗号消失了

**Comment by youzizi1** [comment]
> 最终原因已找到，index.css中的font-face是这样：@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff"),url(fonts/element-icons.ttf) format("truetype");
> vite@2.3.8对于这部分处理，变成了@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff") url(fonts/element-icons.ttf) format("truetype");多个url中间的一个逗号消失了
> 有没有热心网友，可以把这个问题翻译成英文发到vite的issue？

相关issue，https://github.com/vitejs/vite/issues/3922

**Comment by sunwe** [comment]
> 
> 
> > 最终原因已找到，index.css中的font-face是这样：@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff"),url(fonts/element-icons.ttf) format("truetype");
> > vite@2.3.8对于这部分处理，变成了@font-face{font-family:element-icons;src:url(fonts/element-icons.woff) format("woff") url(fonts/element-icons.ttf) format("truetype");多个url中间的一个逗号消失了
> > 有没有热心网友，可以把这个问题翻译成英文发到vite的issue？
> 
> 相关issue，[vitejs/vite#3922](https://github.com/vitejs/vite/issues/3922)

谢谢，没注意，已经有了就等待官方修复了。

**Comment by wenfangdu** [comment]
`vue-cli` 创建的项目发布后也是无法显示图标的

element-plus: v1.0.2-beta.52

**Comment by wenfangdu** [comment]
@iamkun @JeremyWuuuuu 

Projects being created by `vue-cli` can't display icons in production mode either, display fine in development mode.

element-plus: v1.0.2-beta.52

**Comment by wenfangdu** [comment]
> @iamkun @JeremyWuuuuu
> 
> Projects being created by `vue-cli` can't display icons in production mode either, display fine in development mode.
> 
> element-plus: v1.0.2-beta.52

For anyone who comes to this issue when using `vue-li`, try deleting `package-lock.json` / `yarn.lock` and reinstall dependencies, it solved this issue for me.

**Comment by SimonaliaChen** [comment]
Closed for it's not an issue of `element-plus`

**Comment by helloCheng09** [comment]
同样问题，yarn add  vite@2.3.7 -D 已解决

**Comment by helloCheng09** [comment]
同样问题。调了几个小时样式，没解决。看看这里的人才的回答，yarn add vite@2.3.7 -D 已解决。都是大佬
