### ISSUE TITLE
[Bug Report] Select dropdown width is calculate wrong when inside a transition

### ISSUE THREAD

**Issue by mattiapv** [element-plus/element-plus#2278]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
macOS/chrome

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/cranky-satoshi-9rlqy

### Steps to reproduce
Place a Select inside a transition, the dropdown size is calculate wrong. I placed two Select at different times, one after 150ms and two after 300ms the transition is started. In these two cases width increase. I also noticed there is an inline style width on .el-select-dropdown div that change every time the window width is resized.

### What is Expected?
.el-select-dropdown width should be same as .el-select

### What is actually happening?
Width is less

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/127631964-ba8aa9ab-c2bb-47cc-848e-d7885d3c1e25.png)

I'm sorry if I don't understand what you mean.

**Comment by mattiapv** [comment]
Refresh the page and you will see

**Comment by sxzz** [comment]
Sorry, I cannot reproduce this problem.
