### ISSUE TITLE
[Bug Report] yarn add element-plus failed

### ISSUE THREAD

**Issue by hhyygg2009** [element-plus/element-plus#2280]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
win10x64

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/tjsafz3v/

### Steps to reproduce
vue create vue3 project
yarn add element-plus 

in main.js
Module not found: Error: Can't resolve 'element-plus' in ./src/main.js

### What is Expected?
install via yarn ,import success

### What is actually happening?
install via yarn ,import failed.
install via npm,import success

**Comment by XingXiaoWu** [comment]
try beta.52 or use beta.47
https://github.com/element-plus/element-plus/issues/2294#issuecomment-867330054

**Comment by JeremyWuuuuu** [comment]
Upgrade to `beta.52` to solve your issue.
