### ISSUE TITLE
[Bug Report] Missing label in mixed input for el-select

### ISSUE THREAD

**Issue by shiny** [element-plus/element-plus#2281]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome latest

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/daijie/g06fh7jq/

### Steps to reproduce
drop down the el-select and select any option

### What is Expected?
change the label 

### What is actually happening?
 it's value changed but the label still empty
only appeared in mixed input mode

**Comment by kooriookami** [comment]
You can add `style="width:120px"` to `el-select`.

**Comment by shiny** [comment]
> You can add `style="width:120px"` to `el-select`.

The problem is solved
