### ISSUE TITLE
[Bug Report] set el-slider value will trigger update:modelValue

### ISSUE THREAD

**Issue by spx443812507** [element-plus/element-plus#2282]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
mac catelina chrome 91.0.4472.106

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/spx443812507/pen/GRWLXdM

### Steps to reproduce
set slider v-model after setTimeout

### What is Expected?
don't trigger update:modelValue event

### What is actually happening?
trigger update:modelValue event

**Comment by XingXiaoWu** [comment]
I don't think it's bug

[Vue documents](https://v3.vuejs.org/guide/component-custom-events.html#v-model-arguments)

> By default, v-model on a component uses modelValue as the prop and update:modelValue as the event. We can modify these names passing an argument to v-model

I think it means, no matter about u how to change `modelValue`, it will emits `updateModelValue`.

**Comment by spx443812507** [comment]
> I don't think it's bug
> 
> [Vue documents](https://v3.vuejs.org/guide/component-custom-events.html#v-model-arguments)
> 
> > By default, v-model on a component uses modelValue as the prop and update:modelValue as the event. We can modify these names passing an argument to v-model
> 
> I think it means, no matter about u how to change `modelValue`, it will emits `update:modelValue`.

well, update:modelValue should trigger by component itself, you can test other element plus components such as el-input el-input-number , they don't trigger update:modelValue except el-slider, so i think these shoud be same
please check example as below

**Comment by XingXiaoWu** [comment]
From the point of view of consistency, I think you are right

**Comment by sxzz** [comment]
The above problem seems to have been resolved, please reopen the issue if there is any problem.

**Comment by spx443812507** [comment]
> The above problem seems to have been resolved, please reopen the issue if there is any problem.

seems haven't been resolved
