### ISSUE TITLE
[Bug Report] Put a switch in a table column, it auto trigger change event after rendered.

### ISSUE THREAD

**Issue by BiosSun** [element-plus/element-plus#2285]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Chrome 93.0.4535.0 canary (x86_64)

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-pluss-table-component-render-1-index-row-r7bnk?file=/src/components/Table.vue

### Steps to reproduce
1. use el-table;
2. write a custom column, and put a el-switch in the column.

### What is Expected?
The el-switch don't trigger change event after rendered.

### What is actually happening?
After rendered, the el-switch auto trigger change event.

I see in the el-table-column component, an empty row with an index  value of -1 is render by default, which is the cause of the problem. But I don't know why this is done.

**Comment by blueLi0428** [comment]
status should use true or false
`js
items: [{ status: true }],
`

**Comment by kooriookami** [comment]
#2147

**Comment by kooriookami** [comment]
Fixed.
