### ISSUE TITLE
[Bug Report] Input within inline form not expanded/100%

### ISSUE THREAD

**Issue by bobmcallan** [element-plus/element-plus#2288]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Win 10 / Chrome

### Vue version
3.1.1

### Reproduction Link
https://jsfiddle.net/bobmcallan/gn78f4wy/1/

### Steps to reproduce
As per example.

### What is Expected?
Search input should remain 100% expanded whilst 'pushing' the button to the right. 

### What is actually happening?
Search input reduces in size to ?

**Comment by kooriookami** [comment]
`inline` means `display: inline-flex`. You can remove `inline`, and use flex container.
