### ISSUE TITLE
The problem of [bug report] value format

### ISSUE THREAD

**Issue by LeslieZhang** [element-plus/element-plus#2291]
### Element Plus version
1.0.1-beta.14

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

### Vue version
3.0.5

### Reproduction Link
https://github.com/element-plus/element-plus/issues/new/choose

### Steps to reproduce
      打印{{value}}
        <el-date-picker
          v-model="value"
          style="width: 240px"
          value-format="YYYY-MM-DD"
          type="daterange"
          range-separator="-"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          :clearable="false"
        />

### What is Expected?
预期打印输出的格式应该是[ "2021-06-15", "2021-06-23" ]

### What is actually happening?
实际格式是[ "2021-06-15T16:00:00.000Z", "2021-06-23T16:00:00.000Z" ]
![image](https://user-images.githubusercontent.com/24609152/122858478-e94c5080-d34c-11eb-9ed6-66bcece9b52d.png)

**Comment by msidolphin** [comment]
Please upgrade to the latest version
