### ISSUE TITLE
[Bug Report] When adding elements dynamically, the scroll bar is not displayed

### ISSUE THREAD

**Issue by ketao4869** [element-plus/element-plus#2293]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/w4oqdf06/14/

### Steps to reproduce
Add elements dynamically beyond the width of the parent box.But the scroll bar is not displayed (you can scroll with the trackpad).
You need to resize the window to display the scroll bar.

### What is Expected?
The width set by the El-ScrollBar is exceeded. Mouse over the El-ScrollBar to display the scrollbar

### What is actually happening?
The scroll bar is not displayed

**Comment by binvb** [comment]
same

**Comment by binvb** [comment]
you cant set viewstyle display: inline-block;  is fine   
你可以设置viewstyle display属性为 inline-block 即可
```
<el-scrollbar viewStyle="display:inline-block;">
  <div class="flex-content">
    <p class="item" v-for="item in count">{{ item }}</p>
  </div>
</el-scrollbar>
```
because div tag is default 100%, so they can't listen the resize event;  
因为div标签默认宽度100%，他们没办法监听到resize事件

**Comment by ketao4869** [comment]
> you cant set viewstyle display: inline-block; is fine
> 你可以设置viewstyle display属性为 inline-block 即可
> 
> ```
> <el-scrollbar viewStyle="display:inline-block;">
>   <div class="flex-content">
>     <p class="item" v-for="item in count">{{ item }}</p>
>   </div>
> </el-scrollbar>
> ```
> 
> because div tag is default 100%, so they can't listen the resize event;
> 因为div标签默认宽度100%，他们没办法监听到resize事件

这样写是改变视窗的div，
```
<div class="el-scrollbar" data-v-7ba5bd90="">      <!-- 按你的说法应该是需要让这个div变为行内 -->
        <div class="el-scrollbar__wrap el-scrollbar__wrap--hidden-default" style="width: 650px; background-color: red">
            <div class="el-scrollbar__view" style="display: inline-block">       <!-- 但是改变的是这个div -->
                <div class="flex-content" data-v-7ba5bd90="">
                    <p class="item" data-v-7ba5bd90="">1</p>
                    <p class="item" data-v-7ba5bd90="">2</p>
                    <p class="item" data-v-7ba5bd90="">3</p>
                </div>
            </div>
        </div>
        <div class="el-scrollbar__bar is-horizontal" style="display: none"><div class="el-scrollbar__thumb" style="transform: translateX(0%)"></div></div>
        <div class="el-scrollbar__bar is-vertical" style="display: none"><div class="el-scrollbar__thumb" style="transform: translateY(0%)"></div></div>
    </div>
```

**Comment by ketao4869** [comment]
```
    const update = () => {
      if (!wrap.value) return

      const heightPercentage = (wrap.value.clientHeight * 100) / wrap.value.scrollHeight
      const widthPercentage = (wrap.value.clientWidth * 100) / wrap.value.scrollWidth

      sizeHeight.value = heightPercentage < 100 ? heightPercentage + '%' : ''
      sizeWidth.value = widthPercentage < 100 ? widthPercentage + '%' : ''
    }
```
需要调用这个事件才会改变滚动条，但是这个事件只能是窗口改变才会调用

**Comment by kooriookami** [comment]
For workaround. You can set `ref="scrollbar"` to el-scrollbar, when elements changed, do `this.$refs.scrollbar.update();`.
![image](https://user-images.githubusercontent.com/38392315/123187593-0c9e0980-d4cd-11eb-90ea-0c11d67e5845.png)

**Comment by ketao4869** [comment]
> For workaround. You can set `ref="scrollbar"` to el-scrollbar, when elements changed, do `this.$refs.scrollbar.update();`.
> ![image](https://user-images.githubusercontent.com/38392315/123187593-0c9e0980-d4cd-11eb-90ea-0c11d67e5845.png)

这样滚动条是可以出现，但是调用事件更新的滚动条是上一次的
。

**Comment by kooriookami** [comment]
> > For workaround. You can set `ref="scrollbar"` to el-scrollbar, when elements changed, do `this.$refs.scrollbar.update();`.
> > ![image](https://user-images.githubusercontent.com/38392315/123187593-0c9e0980-d4cd-11eb-90ea-0c11d67e5845.png)
> 
> 这样滚动条是可以出现，但是调用事件更新的滚动条是上一次的
> 。

包裹一层异步，比如nextTick

**Comment by JeremyWuuuuu** [comment]
@kooriookami can you follow this up? In order to get it fixed.

**Comment by ketao4869** [comment]
> @kooriookami can you follow this up? In order to get it fixed.

ok

**Comment by kooriookami** [comment]
> @kooriookami can you follow this up? In order to get it fixed.

Yes, I'll look at this.
