### ISSUE TITLE
[Bug Report] Cannot find module '../el-scrollbar/src/util' in Server-Side Rendering

### ISSUE THREAD

**Issue by jackjtr** [element-plus/element-plus#2294]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
Windows 10, Chrome 91.0.4472.114

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/102-beta48-el-scrollbar-ssr-bug-787w1?file=/src/pages/Home.vue

### Steps to reproduce
1. use `el-scrollbar` tag in template
2. run command `yarn ssr`

### What is Expected?
node server runs successfully

### What is actually happening?
```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '../el-scrollbar/src/util'
Require stack:
- [Project_Path]\node_modules\element-plus\lib\el-virtual-list\index.js
- [Project_Path]\node_modules\element-plus\lib\el-select-v2\index.js
- [Project_Path]\node_modules\element-plus\lib\index.js
- [Project_Path]\dist\server\js\app.0595415c.js
- [Project_Path]\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ([Project_Path]\node_modules\element-plus\lib\el-virtual-list\index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[Project_Path]\\node_modules\\element-plus\\lib\\el-virtual-list\\index.js',
    '[Project_Path]\\node_modules\\element-plus\\lib\\el-select-v2\\index.js',
    '[Project_Path]\\node_modules\\element-plus\\lib\\index.js',
    '[Project_Path]\\dist\\server\\js\\app.0595415c.js',
    '[Project_Path]\\server.js'
  ]
}
error Command failed with exit code 1.
```

**Comment by JeremyWuuuuu** [comment]
Could have been some compatibility issue with `virtual-list`. Could you provide a detail reproducible code for me to investigate? Like how you render your components.

**Comment by JeremyWuuuuu** [comment]
According to the error, seems like ElementPlus somehow registered virtual-scroller as ElScrollBar which override the actual ElScrollBar

**Comment by Hugo01** [comment]
Having same issue using Vue 3.0 with Vitte and SSR
still couldn't find any workarrounds

**Comment by JeremyWuuuuu** [comment]
I think I have found the root cause of this issue.
Here is the root cause if you are interested:
From El-Virtual-List we imported `util` from `el-scrollbar`

![image](https://user-images.githubusercontent.com/15975785/123186410-a57f5580-d4ca-11eb-95a7-c3adae75780b.png)

But in the individual build don't have any file named 'el-scrollbar/src/utils.js'

![image](https://user-images.githubusercontent.com/15975785/123186706-4cfc8800-d4cb-11eb-8e15-c0877c5abc32.png)

Going to fix it right away.

**Comment by JeremyWuuuuu** [comment]
Note that the fix is in the dev branch but the release could take few days because we just had a new release yesterday.

**Comment by XingXiaoWu** [comment]
> 请注意，修复是在开发分支，但释放可能需要几天，因为我们昨天刚刚有一个新的版本。

I think it needs to release quickly, if user use like `^` this scope limitation, it will make user lose heart.(it's like me)

**Comment by JeremyWuuuuu** [comment]
Right, this could be a fatal issue so that we decided to release a new version immediately

**Comment by JeremyWuuuuu** [comment]
@jackjtr @XingXiaoWu  try beta.52. Let me know if you have further issue

**Comment by XingXiaoWu** [comment]
> @jackjtr @XingXiaoWu try beta.52. Let me know if you have further issue
> 
> Edit
> Loop @Hugo01

Sorry, our private server source is a synchronous upstream source every day, we cannot try it on the project today, I will try it tomorrow

**Comment by XingXiaoWu** [comment]
beta.52 is ok

**Comment by JeremyWuuuuu** [comment]
> beta.52 is ok

Nice. Let me know if you have further questions
