### ISSUE TITLE
Please add a new function to 'el-select-v2'

### ISSUE THREAD

**Issue by 838239178** [element-plus/element-plus#2295]
### Existing Component
Yes

### Component Name
el-select-v2

### Description
希望向服务端请求 `options`  内容时下拉框能显示 loadding 图案或者提示，感谢开发者团队。
hope that when program get options from server, component could show loadding hint. Thank you.

**Comment by JeremyWuuuuu** [comment]
Hi, the feature you requested is definitely going to be implemented into select-v2, I will implement it ASAP.
