### ISSUE TITLE
[Bug Report] el-cascader multiple search with v-model can't work

### ISSUE THREAD

**Issue by genffy** [element-plus/element-plus#2296]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
macos chorme 91.0.4472.10

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/genffy/pen/oNZRavz

### Steps to reproduce
typing "指南" in search box and then select item from dorpdown list

### What is Expected?
show multiple select

### What is actually happening?
only show one item select at first

Actually:
![image](https://user-images.githubusercontent.com/1506972/122932561-6e148a00-d3a0-11eb-8291-f1dd0508ce7a.png)

Expected:
![image](https://user-images.githubusercontent.com/1506972/122932762-9603ed80-d3a0-11eb-9611-fd30a7a56126.png)

**Comment by JeremyWuuuuu** [comment]
Cc @SimonaliaChen this one as well

**Comment by SimonaliaChen** [comment]
It seems all fine in your demo. I'm afraid I did't get your issue, could you be more specific？

**Comment by genffy** [comment]
> It seems all fine in your demo. I'm afraid I did't get your issue, could you be more specific？ @genffy

umm, It seems be fixed by some PRs recently. The version `1.0.2-beta.53` have resolved this.
