### ISSUE TITLE
How can [bug report] improve efficiency?

### ISSUE THREAD

**Issue by mrerhuo** [element-plus/element-plus#2297]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
mac os

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-test-xol1b?file=/vite.config.ts

### Steps to reproduce
typescript 全局引用后无效，然后只能一个一个的引用组件，那么在开发的时候，比如我做个from 里面有各种元素得一个一个的引用，很慢的。怎么提高开发效率？

### What is Expected?
提高开发效率

### What is actually happening?
提高开发效率

**Comment by msidolphin** [comment]
怎么会无效呢？你是不是忘了引入样式了？

**Comment by zy94xhn** [comment]
参考官方文档，你不是没生效，你是根本没做引入处理

**Comment by mrerhuo** [comment]
import { createApp } from 'vue'
import ElementPlus from 'element-plus';
import App from './App.vue';

const app = createApp(App)
app.use(ElementPlus, { size: 'small', zIndex: 3000 });

**Comment by mrerhuo** [comment]
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

export default defineConfig({
  plugins: [
    vue(),

    styleImport({
      libs: [{

        libraryName: 'element-plus',
        esModule: true,

        ensureStyleFile: true,
        resolveStyle: (name) => {

          name = name.slice(3);
          return `element-plus/packages/theme-chalk/src/${name}.scss`;

        },
        resolveComponent: (name) => {

          return `element-plus/lib/${name}`;
        }

      }]
    })

  ],
  css: {

    preprocessorOptions: {
      scss: {

        additionalData: `@import \"./src/styles/variables.scss\";`
      }

    }
  }
})

**Comment by mrerhuo** [comment]
https://codesandbox.io/s/adoring-worker-tpivs?file=/src/App.vue

**Comment by mrerhuo** [comment]
@element-bot

**Comment by msidolphin** [comment]
你没有挂载，而且没有引入样式

**Comment by msidolphin** [comment]
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import styleImport from 'vite-plugin-style-import'
> 
> export default defineConfig({
> plugins: [
> vue(),
> 
> ```
> styleImport({
>   libs: [{
> 
>     libraryName: 'element-plus',
>     esModule: true,
> 
>     ensureStyleFile: true,
>     resolveStyle: (name) => {
> 
>       name = name.slice(3);
>       return `element-plus/packages/theme-chalk/src/${name}.scss`;
> 
>     },
>     resolveComponent: (name) => {
> 
>       return `element-plus/lib/${name}`;
>     }
> 
>   }]
> })
> ```
> 
> ],
> css: {
> 
> ```
> preprocessorOptions: {
>   scss: {
> 
>     additionalData: `@import \"./src/styles/variables.scss\";`
>   }
> 
> }
> ```
> 
> }
> })

这是按需引入，你要的是完整引入
https://element-plus.org/#/zh-CN/component/quickstart
仔细参考下文档

**Comment by JeremyWuuuuu** [comment]
Closing since @msidolphin has given the correct answer, by fully importing, you need to import the stylesheet into your project on your own.
