### ISSUE TITLE
[bug report] in the vite project environment, all icons cannot be displayed normally

### ISSUE THREAD

**Issue by chaode0620** [element-plus/element-plus#2299]
### Element Plus version
1.0.2-beta.48

### OS/Browsers version
window 10 / Google Chrome 版本 91.0.4472.114（正式版本） （64 位）

### Vue version
3.1.2

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-sv8et?file=/src/App.vue:0-421

### Steps to reproduce
 只要是带有icon的，必现。反正我是没遇到哪次能是正常出现的。  你可以把你button带图标放上试试看

### What is Expected?
正常显示图标

### What is actually happening?
图标不能正常显示

**Comment by iamkun** [comment]
Duplicate of #2277
