### ISSUE TITLE
Compiled failed:Can't resolve 'throttle-debounce/throttle'

### ISSUE THREAD

**Issue by MBearo** [element-plus/element-plus#230]
### Env
mac 10.15.6
node 14.5.0 && 11.12.0 && 10.21.0
### Detail
website/pages/component.vue
website/pages/index.vue

```javascript
import throttle from 'throttle-debounce/throttle'
```

**Comment by JeremyWuuuuu** [comment]
Hey, have you tried it with `yarn bootstrap`? I just checked it out, `throttle-debounce/throttle` is declared in the `package.json` file.

**Comment by MBearo** [comment]
> Hey, have you tried it with `yarn bootstrap`? I just checked it out, `throttle-debounce/throttle` is declared in the `package.json` file.

```
import {throttle} from 'throttle-debounce'
```
Modify it to the above so it can run
