### ISSUE TITLE
[bug report] after using NPM to install dependency package, some components are lost

### ISSUE THREAD

**Issue by xLong1029** [element-plus/element-plus#2309]
### Element Plus version
1.0.2-beta.49

### OS/Browsers version
版本 87.0.4280.141（正式版本） （64 位）

### Vue version
3.1.2

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-66cdh

### Steps to reproduce
本地项目根据官方文档提示的Vue CLI按需引入，安装了Element Plus 1.0.2-beta.49，丢失部分组件，安装Element Plus 1.0.2-beta.36则正常包含所有组件

线上演示代码无此问题

### What is Expected?
希望能正常安装依赖并引用所有组件

### What is actually happening?
丢失部分组件，提示找不到模块

<img width="791" alt="丢失模块" src="https://user-images.githubusercontent.com/18066675/123082858-13d40180-d452-11eb-9c8a-08a9c90aca63.png">
<img width="462" alt="找不到模块" src="https://user-images.githubusercontent.com/18066675/123082864-159dc500-d452-11eb-9b6c-9c9f9095e984.png">

相关代码
<img width="510" alt="App vue" src="https://user-images.githubusercontent.com/18066675/123083031-39f9a180-d452-11eb-8764-e6d87ff29352.png">
<img width="463" alt="main js" src="https://user-images.githubusercontent.com/18066675/123083090-4d0c7180-d452-11eb-80f3-581198f49ae0.png">
<img width="448" alt="babel config js" src="https://user-images.githubusercontent.com/18066675/123083143-5b5a8d80-d452-11eb-9725-5b154cea58ed.png">

**Comment by JeremyWuuuuu** [comment]
Seems like something went wrong with the package. I am currently investigating the root cause, hope that we will fix it soon.

**Comment by JeremyWuuuuu** [comment]
Check it out here: https://github.com/element-plus/element-plus/actions/runs/964198172
