### ISSUE TITLE
[Feature Request] In webstorm,the function "go to definition" couldn't work

### ISSUE THREAD

**Issue by yzqdev** [element-plus/element-plus#2311]
### Existing Component
Yes

### Component Name
el-tooltip

### Description
In the latest version of webstorm(supporting vue3 syntax), only el-tooltip component and its props could be accessed through 'go to definition' (press Ctrl and right click) , while other components couldn't. The same in vscode. **because of the web-types.json file** . See more here  [https://github.com/JetBrains/web-types](https://github.com/JetBrains/web-types)
Hope we could jump to the component and props in IDEs using typescript typings

在webstorm最新版本(支持vue3语法)中element-plus只有el-tooltip可以按Ctrl 鼠标左键直接跳转到组件的源码以及props定义的位置,然而其他的组件都无法跳转;
在webstorm最新版本(支持vue3语法)中elementui(就是element-plus的上一代)却可以跳转到所有组件的props以及自定义function的位置
希望element-plus也可以做到直接跳转到props定义

**Comment by JeremyWuuuuu** [comment]
Hi, is this happening recently or it was always like that?

**Comment by yzqdev** [comment]
It was always like that. I gave feedback in the element group of dingtalk five months ago. And the administrator said we will fix this. (I guess maybe typescript  defines the 'index.ts' file as a module in its syntax,so if there is no 'index.ts'  in src folder, it's not a module. While webstorm and vscode seems to like modules.)

**Comment by JeremyWuuuuu** [comment]
Yeah, TBH, we currently supported `vetur` and `WebStorm` for a limited range, but not all functionalities are ready, and we kind of having issues of our own which was design failure. We will keep this open until we find a way to fix this, also we may send a email to JetBrains' team for requesting a license for us to fix this issue.

**Comment by JeremyWuuuuu** [comment]
@yzqdev Also I'd like to ask you whether you'd like joining us for fixing this issue. It is ok that you say no, if you do please do let me know and we will be very glad that you say so.

**Comment by yzqdev** [comment]
Of course I  will.I've seen elementui progressing over the past year. Many of my own projects are uses element . So I'll spare no efforts to make element-plus better.

**Comment by JeremyWuuuuu** [comment]
Great! That's a good news for us. Let's see what we can do together then.

**Comment by tolking** [comment]
抱歉！这应该是我为 `element-plus` 增加 web-types 文件引起的。我测试了下，删除 node_modules/element-plus/package.json 中的

``` diff
{
- "web-types": "lib/web-types.json",
}
```

将满足你的需求（似乎这样仅适用于 element-ui 与 element-plus，我无从知道 IDE 内部施加了什么魔法）。这样你将会失去 web-types 带来的提示功能，关于两者的兼容你可以咨询官方。

通过 web-types 可以增加点击组件跳转到 type 类型定义，无法支持属性

**Comment by sxzz** [comment]
If you like, please use VSCode + Volar, which is the officially recommended by Vue. Volar will be first-class citizen support.
