### ISSUE TITLE
[Bug Report] Cascader `Array<Object>` type `modelValue` doesn't work in lazy mode

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#2312]
### Element Plus version

1.0.2-beta.51

### OS/Browsers version

Windows 10
Chrome v91

### Vue version

3.1.2

### Reproduction Link

https://codepen.io/wenfang/pen/ExWBZMR

### Steps to reproduce

Notice cascader's `modelValue` is `[{ id: 1 }, { id: 2 }, { id: 4 }]`.

### What is Expected?

`选项1 / 选项2 / 选项4` being selected.

### What is actually happening?

No option is selected.

**Comment by wenfangdu** [comment]
@JeremyWuuuuu Please have a look at this 🙏.

**Comment by JeremyWuuuuu** [comment]
cc @SimonaliaChen can you take a look on this?

**Comment by JeremyWuuuuu** [comment]
I had a look on the code. Seems like when Cascader is at lazy mode and when it expands the sub nodes, it didn't go check whether the model value matches the expanding node, which caused the issue. The code of expanding the node is at `CascaderPanel/index.vue` if you are interested in fixing this bug.

**Comment by JeremyWuuuuu** [comment]
If you are interested in fixing this bug, you can go to the file I mentioned and adding `modelValue` checking logic inside the function. Then add a test case just like your reproduce code and simulate the expanding process (which is already implemented in the test file, you can simply copy paste it) then test whether the value satisfies your requirement.

**Comment by JeremyWuuuuu** [comment]
Also cc @kooriookami  you interested in this?

**Comment by XingXiaoWu** [comment]
> I had a look on the code. Seems like when Cascader is at lazy mode and when it expands the sub nodes, it didn't go check whether the model value matches the expanding node, which caused the issue. The code of expanding the node is at if you are interested in fixing this bug.`CascaderPanel/index.vue`

How to design this kind of interaction effect, itself is lazy load, loaded level of values then select the level `modelValue`?

**Comment by XingXiaoWu** [comment]
when `lazy` and set `modelValue`, set default options value for the `modelValue` after load options if options have the `modelValue` value, merge it

**Comment by SimonaliaChen** [comment]
> I had a look on the code. Seems like when Cascader is at lazy mode and when it expands the sub nodes, it didn't go check whether the model value matches the expanding node, which caused the issue. The code of expanding the node is at `CascaderPanel/index.vue` if you are interested in fixing this bug.

It do check the model value and synchronize the default checked state in lazy mode in https://github.com/element-plus/element-plus/blob/dev/packages/cascader-panel/src/index.vue#L201.

The cause of this problem is that @wangfangdu pass option's value with an object but not a primitive value. This should work https://codepen.io/simonaliachen/pen/YzZomqo

**Comment by wenfangdu** [comment]
@SimonaliaChen Can `modelValue` with `Array<Object>` type  value be supported? Since if the last selection is an object, `选项1 / 选项2 / 选项4` will be selected when initializing, see it in action: https://codepen.io/wenfang/pen/dyvBxVx.

There're many cases we would want to store more info rather than just a primitive value for each node, if the entire `modelValue` array supports object type, that'd be great.

**Comment by wenfangdu** [comment]
@SimonaliaChen Also, `Array<Object>` type `modelValue` works for non-lazy mode, please see https://codepen.io/wenfang/pen/eYvqOZo. If the lazy mode doesn't support this, it'll be inconsistent.

**Comment by SimonaliaChen** [comment]
> @SimonaliaChen Also, `Array<Object>` type `modelValue` works for non-lazy mode, please see https://codepen.io/wenfang/pen/eYvqOZo. If the lazy mode doesn't support this, it'll be inconsistent.

I see. I will fix it ASAP.
