### ISSUE TITLE
[Bug Report] <ElRow> is not full with width spread in <Form>

### ISSUE THREAD

**Issue by ErrorJe** [element-plus/element-plus#2319]
### Element Plus version
1.0.2-beta.51

### OS/Browsers version
mac

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/ErrorJE/pen/XWMLowQ

### Steps to reproduce
show the code by above link

### What is Expected?
i hope this component's width can full of the container width

### What is actually happening?
<el-row> is not work success

**Comment by JeremyWuuuuu** [comment]
Did this happen in the previous versions?

**Comment by ErrorJe** [comment]
> Did this happen in the previous versions?

this happen in version after `^1.0.2-beta.49"`, i use this component and layout class is ok of version `^1.0.2-beta.48"`

**Comment by JeremyWuuuuu** [comment]
Weird. But we do have changes for the `scss` file at #2237

**Comment by JeremyWuuuuu** [comment]
Ping @dreamqyq here. Can you take a look on this?

**Comment by dreamqyq** [comment]
> Ping @dreamqyq here. Can you take a look on this?

ok

**Comment by dreamqyq** [comment]
@JeremyWuuuuu because at this pr #2270 , it changed display of form `block` to `flex`, and then make `el-row` width shrink. maybe we can set default width of `el-row` 100%?

**Comment by ErrorJe** [comment]
> @JeremyWuuuuu because at this pr #2270 , it changed display of form `block` to `flex`, and then make `el-row` width shrink. maybe we can set default width of `el-row` 100%?

Bro, has any conclusion?

**Comment by kooriookami** [comment]
Why do you use `inline` prop?
![image](https://user-images.githubusercontent.com/38392315/123283222-c59c2c80-d53d-11eb-827d-e5eca9fe70e0.png)

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/123283634-29bef080-d53e-11eb-8a5f-46d496ae26f6.png)
And you need change `span="8"` to `:span="8"`, span receives number type.

**Comment by ErrorJe** [comment]
> Why do you use `inline` prop?
> ![image](https://user-images.githubusercontent.com/38392315/123283222-c59c2c80-d53d-11eb-827d-e5eca9fe70e0.png)

whatever

**Comment by kooriookami** [comment]
> > Why do you use `inline` prop?
> > ![image](https://user-images.githubusercontent.com/38392315/123283222-c59c2c80-d53d-11eb-827d-e5eca9fe70e0.png)
> 
> whatever, and i use `inline` in old version by `-48`, everythings is ok

We used flex layout for the form. When you use `inline` and `label-position="top"`, we will add `display: flex; flex-wrap: wrap;` to form.

**Comment by ErrorJe** [comment]
> > > Why do you use `inline` prop?
> > > ![image](https://user-images.githubusercontent.com/38392315/123283222-c59c2c80-d53d-11eb-827d-e5eca9fe70e0.png)
> > 
> > 
> > whatever, and i use `inline` in old version by `-48`, everythings is ok
> 
> We used flex layout for the form. When you use `inline` and `label-position="top"`, we will add `display: flex; flex-wrap: wrap;` to form.

The scope of influence should be like `form-item`, not `el-row` or other components layout's logic.
Of course, that's your choice, these are just my opinions above all
