### ISSUE TITLE
[Bug Report] Syntax Error: SassError: @use rules must be written before any other rules.

### ISSUE THREAD

**Issue by webliving** [element-plus/element-plus#2331]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
Mac OS

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/webliving/pen/oNZrrNG

### Steps to reproduce
1. 按需加载编译的element-plus 组件
2. 加载 ElCol 组件

### What is Expected?
正常编译

### What is actually happening?
in ./node_modules/element-plus/packages/theme-chalk/src/col.scss

Syntax Error: SassError: @use rules must be written before any other rules.
  ╷
2 │ @use "sass:math";

**Comment by JeremyWuuuuu** [comment]
@dreamqyq I believe this has something to do with your changes as well, please take a look on this.

**Comment by mrerhuo** [comment]
Plugin: vite:css
  File: /Users/mrer/Code/GitProject/jc_element_admin/node_modules/element-plus/packages/theme-chalk/src/loading.scss
  Error: @use rules must be written before any other rules.
    ╷
  3 │       @use "sass:math";
    │       ^^^^^^^^^^^^^^^^
    ╵
    node_modules/element-plus/packages/theme-chalk/src/loading.scss 3:7  root stylesheet
      at Object._newRenderError (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:13222:19)
      at Object._wrapException (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:13050:16)
      at _render_closure1.call$2 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:81775:21)
      at _RootZone.runBinary$3$3 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:27547:18)
      at _FutureListener.handleError$1 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:26096:19)
      at _Future__propagateToListeners_handleError.call$0 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:26394:49)
      at Object._Future__propagateToListeners (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:4541:77)
      at _Future._completeError$2 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:26226:9)
      at _AsyncAwaitCompleter.completeError$2 (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:25880:12)
      at Object._asyncRethrow (/Users/mrer/Code/GitProject/jc_element_admin/node_modules/sass/sass.dart.js:4340:17)

**Comment by mrerhuo** [comment]
@JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Will release a new version today for fixing this issue.

**Comment by webliving** [comment]
> Will release a new version today for fixing this issue.

今天还发版嘛? 👍

**Comment by webliving** [comment]
@JeremyWuuuuu 这个问题, 发布的1.0.2-beta.53版本好像还是报错呢

**Comment by dreamqyq** [comment]
> @JeremyWuuuuu 这个问题, 发布的1.0.2-beta.53版本好像还是报错呢

麻烦给一个可以复现的代码示例，以及具体的复现步骤，谢谢

Please give me a code example that can be re-emerged, as well as specific re-emergence steps, thank you

**Comment by webliving** [comment]
@dreamqyq  自定义element样式变量时, 会报错
```javascript
sass: {
        // hoistUseStatements: true,
        prependData: '$--font-path: \'~element-plus/lib/theme-chalk/fonts\'; @import \'./src/styles/variables.scss\';'
}
```

**Comment by webliving** [comment]
@dreamqyq  自定义element样式变量时, 会报错
```javascript
sass: {
        // hoistUseStatements: true,
        prependData: '$--font-path: \'~element-plus/lib/theme-chalk/fonts\'; @import \'./src/styles/variables.scss\';'
}
```

**Comment by dreamqyq** [comment]
> @dreamqyq 自定义element样式变量时, 会报错
> 
> ```js
> sass: {
>         // hoistUseStatements: true,
>         prependData: '$--font-path: \'~element-plus/lib/theme-chalk/fonts\'; @import \'./src/styles/variables.scss\';'
> }
> ```

https://github.com/dreamqyq/element-plus-demo

我写了个例子，用了你的自定义样式代码，并没有复现这个问题，可否在我的例子基础上复现一下这个问题，方便修复bug

**Comment by webliving** [comment]
@dreamqyq  这样, 你加入ElCol 组件
![image](https://user-images.githubusercontent.com/3808577/123884543-094bc780-d97e-11eb-9574-3669d8e90bed.png)

**Comment by dreamqyq** [comment]
> @dreamqyq 这样, 你加入ElCol 组件
> ![image](https://user-images.githubusercontent.com/3808577/123884543-094bc780-d97e-11eb-9574-3669d8e90bed.png)

好的，我会尽快修复这个问题

**Comment by webliving** [comment]
@dreamqyq  👍  辛苦

**Comment by dreamqyq** [comment]
@webliving 

As described this issues , when custom element style variables are used, components that use @use "sass:math" are introduced as needed, and an error will be reported, such as `badge`, `carousel`, `col`, `input-number`, `loading`, `transfer`.

I resolve this problem, it's not bug for element-plus,

For example, in this repo: https://github.com/dreamqyq/element-plus-demo, I fixed this problem,introduce custom style files, write like this "@use filename as *" in `vue.config.js`

```
 sass: {
    prependData:
      "$--font-path: '~element-plus/lib/theme-chalk/fonts'; @use './src/styles/variables.scss' as *;"
}
```

You can try it, if there are any other questions, you can continue to feedback.

**Comment by webliving** [comment]
@dreamqyq  💯  , 修复了.

**Comment by webliving** [comment]
@dreamqyq 有另一个问题, demo 代码里加载了全量样式吗?
```javascript
@import "~element-plus/packages/theme-chalk/src/index";
```
但, 这个去掉之后, 自定义皮肤scss样式变量就会不生效了?

**Comment by dreamqyq** [comment]
> @dreamqyq 有另一个问题, demo 代码里加载了全量样式吗?
> 
> ```js
> @import "~element-plus/packages/theme-chalk/src/index";
> ```
> 
> 但, 这个去掉之后, 自定义皮肤scss样式变量就会不生效了?

![image](https://user-images.githubusercontent.com/34675975/124692180-ac1cbc80-df0f-11eb-97c3-15d09ba08102.png)

文档里有写

**Comment by webliving** [comment]
@dreamqyq 但这样写会全量加载样式了吧, 想要按需打包样式呢?
> @import "~element-plus/packages/theme-chalk/src/index";

**Comment by CaiWenlie** [comment]
用`style-resources-loader`加了前缀之后还是会有问题
1.0.2-beta.62

**Comment by Miss-Sixty** [comment]
1.0.2-beta.59 再次出现此问题，升级到 1.0.2-beta.62 依然未解决

```base
error in ./node_modules/element-plus/packages/theme-chalk/src/button.scss

Syntax Error: SassError: @use rules must be written before any other rules.
   ╷
51 │ @use "sass:map";
   │ ^^^^^^^^^^^^^^^
   ╵
  /Users/xh/work/ics_version2_admin/node_modules/element-plus/packages/theme-chalk/src/button.scss 51:1  root stylesheet


 @ ./node_modules/element-plus/packages/theme-chalk/src/button.scss 4:14-271 15:3-20:5 16:22-279
 @ ./src/plugins/element.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.50.183:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by JeremyWuuuuu** [comment]
>  @use "sass:map";

Can you give us a demo?

**Comment by JeremyWuuuuu** [comment]
> 用`style-resources-loader`加了前缀之后还是会有问题
> 1.0.2-beta.62

Can you give a demo?

**Comment by Miss-Sixty** [comment]
> > @use "sass:map";
> 
> 你能给我们一个演示吗？

https://github.com/Miss-Sixty/sixty-admin.git

**Comment by webliving** [comment]
@dreamqyq  这个问题在最新版(1.0.2-beta.70)又有了,  自定义的SCSS颜色变量, 如: $--color-primary

**Comment by EliazTray** [comment]
any update now?

**Comment by hjklink** [comment]
1.0.2-beta.70

**Comment by iamkun** [comment]
@hjklink can you provide the full error message pls.

**Comment by webliving** [comment]
@hjklink 看这里#2920 说明是用 css var 解决, 但目前试了还不行, 应该还没有支持好.
