### ISSUE TITLE
Carousel lantern components, using the v-show command to control the display status, will be fuzzy display and can not play

### ISSUE THREAD

**Issue by Anqi0324** [element-plus/element-plus#2335]
作者你好，当使用 v-show 控制 Carousel 走马灯组件的显示状态时，走马灯元素会重叠显示并且不能播放，下面的是我的代码
```javascript
<script lang="ts">
import { defineComponent, PropType } from "vue";
import BroadcastCarouselItem from "./broadcast-carousel-item.vue";

import { useModelBroadcastItems } from "../hooks/use-model-broadcast";
import { CaseBroadcastItem } from "@/utils/service";

export default defineComponent({
  name: "BroadcastCarouselItems",
  components: {
    BroadcastCarouselItem,
  },
  props: {
    items: {
      type: Array as PropType<CaseBroadcastItem[]>,
      default: [] as CaseBroadcastItem[],
    },
  },
  setup(props) {
    const { itemsRef, showItemsRef } =
      useModelBroadcastItems<CaseBroadcastItem>(props);
    return { itemsRef, showItemsRef };
  },
});
</script>

<template>
  <el-carousel height="30px" direction="vertical" v-show="showItemsRef">
    <el-carousel-item v-for="item in itemsRef" :key="item.caseId">
      <broadcast-carousel-item :item="item" />
    </el-carousel-item>
  </el-carousel>
</template>
```

**Comment by mrerhuo** [comment]
從入門到放棄。。

**Comment by Anqi0324** [comment]
> 作者你好，当使用 v-show 控制 Carousel 走马灯组件的显示状态时，走马灯元素会重叠显示并且不能播放，下面的是我的代码
> 
> ```js
> <script lang="ts">
> import { defineComponent, PropType } from "vue";
> import BroadcastCarouselItem from "./broadcast-carousel-item.vue";
> 
> import { useModelBroadcastItems } from "../hooks/use-model-broadcast";
> import { CaseBroadcastItem } from "@/utils/service";
> 
> export default defineComponent({
>   name: "BroadcastCarouselItems",
>   components: {
>     BroadcastCarouselItem,
>   },
>   props: {
>     items: {
>       type: Array as PropType<CaseBroadcastItem[]>,
>       default: [] as CaseBroadcastItem[],
>     },
>   },
>   setup(props) {
>     const { itemsRef, showItemsRef } =
>       useModelBroadcastItems<CaseBroadcastItem>(props);
>     return { itemsRef, showItemsRef };
>   },
> });
> </script>
> 
> <template>
>   <el-carousel height="30px" direction="vertical" v-show="showItemsRef">
>     <el-carousel-item v-for="item in itemsRef" :key="item.caseId">
>       <broadcast-carousel-item :item="item" />
>     </el-carousel-item>
>   </el-carousel>
> </template>
> ```

改为使用 v-if 控制就好啦。作者可以看看优先级是否需要修改即可

**Comment by msidolphin** [comment]
Not reproduced, can you provide any reproduction link?
https://codepen.io/msidolphin/pen/jOBgLxG

**Comment by JeremyWuuuuu** [comment]
Any screenshots and reproducible link would be appreciated! Thanks. We need a minimal version for reproduction.

**Comment by msidolphin** [comment]
> Any screenshots and reproducible link would be appreciated! Thanks. We need a minimal version for reproduction.

The assigned was cancelled by accident... if there is a problem I'll try to fix it

**Comment by Anqi0324** [comment]
> The assigned was cancelled by accident... if there is a problem I'll try to fix it
![bug-img-1](https://user-images.githubusercontent.com/47526889/123358124-738af380-d59d-11eb-976b-8af7040130a4.png)

this is image

**Comment by msidolphin** [comment]
> image
Can you provide any reproduction link? I'm not sure if it's your implement issue

**Comment by Anqi0324** [comment]
> > > The assigned was cancelled by accident... if there is a problem I'll try to fix it
> > > ![bug-img-1](https://user-images.githubusercontent.com/47526889/123358124-738af380-d59d-11eb-976b-8af7040130a4.png)
> > 
> > 
> > this is image
> 
> Can you provide any reproduction link? I'm not sure if it's your implement issue

https://codepen.io/msidolphin/pen/jOBgLxG

复现步骤：
1. 先将 items 列表设置为空
2. 组件挂载后，延迟 1 秒 将 items 更新为 [0, 1, 2, 3, 4]，并且将 show 设置为 true
3. 组件展示，但停止工作

**Comment by Anqi0324** [comment]
> > > The assigned was cancelled by accident... if there is a problem I'll try to fix it
> > > ![bug-img-1](https://user-images.githubusercontent.com/47526889/123358124-738af380-d59d-11eb-976b-8af7040130a4.png)
> > 
> > 
> > this is image
> 
> Can you provide any reproduction link? I'm not sure if it's your implement issue

```javascript
var Main = {
            data() {
              return {
                show: false,
                items: []
              }
            },
            methods: {
            onClick() {
              this.show = !this.show
            }
           },
           mounted() {
             setTimeout(() => {
               items = [0, 1, 2, 3, 4]
               this.show = !this.show
             }, 1000)
           }
           }
;const app = Vue.createApp(Main);
app.use(ElementPlus);
app.mount("#app")
```
