### ISSUE TITLE
[Bug Report] v-popover cant work

### ISSUE THREAD

**Issue by ruleeeer** [element-plus/element-plus#2339]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
Mac 11.2.3/Chrome 91

### Vue version
3.0.3

### Reproduction Link
https://codesandbox.io/s/v-popove-true-q0iol?file=/src/App.vue

### Steps to reproduce
if i use directive 'v-popover',it will throw 'Cannot read property 'created' of undefined'

### What is Expected?
vue and element Plus work normally

### What is actually happening?
![image](https://user-images.githubusercontent.com/70385062/123358950-f95b6e80-d59e-11eb-96f5-b7ee05eb3849.png)

**Comment by JeremyWuuuuu** [comment]
Seems like something went wrong. By the time this was written the issue cannot be reproduced. I will go investigate what was going on with this. Til then, would you mind using the slot way to do your feature?

**Comment by ruleeeer** [comment]
i found it first at transformation vue2 to vue3,then i reproduced it in sanbox. i will replace it with using 'reference' slot
thank you very much

**Comment by XingXiaoWu** [comment]
> Seems like something went wrong. By the time this was written the issue cannot be reproduced. I will go investigate what was going on with this. Til then, would you mind using the slot way to do your feature?

plugins forget import popover
https://github.com/element-plus/element-plus/pull/2341
