### ISSUE TITLE
[Bug Report] Icon is invalid

### ISSUE THREAD

**Issue by allowing** [element-plus/element-plus#2342]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
chrome 91

### Vue version
3.1.2

### What is actually happening?
![image](https://user-images.githubusercontent.com/20262949/123384383-e8265800-d5c6-11eb-8234-c951962217af.png)
![image](https://user-images.githubusercontent.com/20262949/123384434-fb392800-d5c6-11eb-97f1-5014333f65a8.png)

**Comment by XingXiaoWu** [comment]
vite?

**Comment by allowing** [comment]
It has nothing to do with vite, these are pre-compiled by the library

**Comment by JeremyWuuuuu** [comment]
Did the fonts loaded correctly?

**Comment by Jmysy** [comment]
我也出现了该问题，请问是否有解决

**Comment by Jmysy** [comment]
https://jmysy.github.io/element-enhance 升级后导致图表无效

**Comment by Jmysy** [comment]
vite 2.3.8 --> vite 2.3.7

**Comment by allowing** [comment]
这个问题与vite无关。因为这个`'element-plus/lib/theme-chalk/index.css'`文件是官方预构建好的，而这个预构建文件本身出了问题。

解决方案：
```js
// import 'element-plus/lib/theme-chalk/index.css';
import 'element-plus/packages/theme-chalk/src/index.scss';
```
不引入预构建版的css，直接引入源码，引入源码需要安装`sass`解析库。`npm i sass`

**Comment by Hugo01** [comment]
Having the same issue lately
They used to work just fine on older versions of ELPlus and Vitte tho

**Comment by Ankol-v** [comment]
感谢提供解决方案，正好碰到了这个问题

**Comment by iteniasim** [comment]
Same problem here, but alternative solution is to use the cdn for the styles,
the styles are broken only in npm package not in cdn

**Comment by YangZhaocool** [comment]
> 这个问题与vite无关。因为这个`'element-plus/lib/theme-chalk/index.css'`文件是官方预构建好的，而这个预构建文件本身出了问题。
> 
> 解决方案：
> 
> ```js
> // import 'element-plus/lib/theme-chalk/index.css';
> import 'element-plus/packages/theme-chalk/src/index.scss';
> ```
> 
> 不引入预构建版的css，直接引入源码，引入源码需要安装`sass`解析库。`npm i sass`

感谢 我遇到的也是这个问题 我用的是1.0.2-beta.53

**Comment by mihailo124** [comment]
> 这个问题与vite无关。因为这个`'element-plus/lib/theme-chalk/index.css'`文件是官方预构建好的，而这个预构建文件本身出了问题。
> 
> 解决方案：
> 
> ```js
> // import 'element-plus/lib/theme-chalk/index.css';
> import 'element-plus/packages/theme-chalk/src/index.scss';
> ```
> 
> 不引入预构建版的css，直接引入源码，引入源码需要安装`sass`解析库。`npm i sass`


"element-plus": "1.0.2-beta.53",

This did work out for me, thanks a lot!!

**Comment by allowing** [comment]
新版本已解决，现在关闭
