### ISSUE TITLE
[Bug Report] Select V2 v-model fail

### ISSUE THREAD

**Issue by Mcler520** [element-plus/element-plus#2346]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
Chrome

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/EnMcler/pen/OJpKvKL

### Steps to reproduce
Use cases

### What is Expected?
Use cases

### What is actually happening?
Use cases

**Comment by JeremyWuuuuu** [comment]
The value you put was `选项${}`, the model was `a0`.
What do you think it will get when you compare '选项' with `a`?

**Comment by Mcler520** [comment]
Vitejs has a warning and cannot use V-model
