### ISSUE TITLE
[Bug Report] peer vue@"3.1.1" from element-plus@1.0.2-beta.53

### ISSUE THREAD

**Issue by isameng** [element-plus/element-plus#2349]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
mac / chrome 91.0.4472.114

### Vue version
3.1.2

### Reproduction Link
https://github.com/element-plus

### Steps to reproduce
https://github.com/element-plus

### What is Expected?
npm install element-plus --save

### What is actually happening?
Conflicting peer dependency: vue@3.1.1
npm ERR! node_modules/vue
npm ERR!   peer vue@"3.1.1" from element-plus@1.0.2-beta.53
npm ERR!   node_modules/element-plus
npm ERR!     element-plus@"*" from the root project

**Comment by itskaiway** [comment]
in the same situation, but i retry this command with "--legacy-peer-deps"

**Comment by pengsp** [comment]
`npm install element-plus --save  --force`

with `--force`, It works...

**Comment by isameng** [comment]
> `npm install element-plus --save --force`
> 
> with `--force`, It works...

thank~

**Comment by 0song** [comment]
fixed in #2352
