### ISSUE TITLE
[Bug Report] Slot "default" invoked outside of the render function

### ISSUE THREAD

**Issue by buqiyuan** [element-plus/element-plus#2350]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
win10 / chrome 91.0.4472.114

### Vue version
3.1.2

### Reproduction Link
https://github.com/buqiyuan/vite-vue3-lowcode

### Steps to reproduce
update to 1.0.2-beta.53

### What is Expected?
no warning

### What is actually happening?
Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <ElScrollbar ref="scrollbar" tag="ul" wrap-class="el-select-dropdown__wrap"  ... > 
  at <ElSelectDropdown> 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <ElPopper ref="popper" visible=false onUpdate:visible=fn  ... > 
  at <ElSelect modelValue="text" onUpdate:modelValue=fn<onUpdate:modelValue> valueKey="value"  ... > 
  at <ElFormItem key="vid_1624625727745type" style= {} > 
  at <ElForm size="mini" labelPosition="left" > 
  at <FormEditor> 
  at <Anonymous> 
  at <ElTabPane label="属性" name="attr" > 
  at <ElTabs modelValue="attr" onUpdate:modelValue=fn<onUpdate:modelValue> type="border-card"  ... > 
  at <RightAttributePanel> 
  at <ElMain> 
  at <ElContainer class="layout-container" > 
  at <ElContainer> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" > 
  at <RouterView> 
  at <App>

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/123437587-694f1080-d602-11eb-94a1-8447acce4f0f.png)
when I update to 1.0.2-beta.53 the scrollbar component will trigger some many warning

**Comment by msidolphin** [comment]
same problem #2362

**Comment by kooriookami** [comment]
Fixed.
