### ISSUE TITLE
[Feature Request] It is recommended to use css variables to replace scss variables, and to change the theme easily

### ISSUE THREAD

**Issue by OneSeven** [element-plus/element-plus#2357]
### Existing Component
Yes

### Component Name
custom-theme

### Description
The CSS variable has an interface in javascript to control the value of the variable very conveniently, which is more convenient for changing the theme
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

**Comment by iamkun** [comment]
please check #2242
