### ISSUE TITLE
[Bug Report] <el-select> 's popover is not working after upgrade version to beta-53 in production env

### ISSUE THREAD

**Issue by ErrorJe** [element-plus/element-plus#2365]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
mac os

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/ErrorJE/pen/rNmNBxr

### Steps to reproduce
- i upgrade the version to beta 53
- everything is ok in beta52 or beta53 but in development env(NODE_NEV===development)
- use beta53 in production env (NODE_ENV===production), has some wrong of this issue title

### What is Expected?
popover can show text list completly

### What is actually happening?
popover just show a white box, nothing in it

**Comment by staunchheart** [comment]
我也遇到同样的问题，
在编译后下拉框（如果固定设定的值）会不显示文字。

**Comment by 9-lives** [comment]
比较急的话，先回滚到 element-plus1.0.2-beta.48

**Comment by xelinel32** [comment]
> 我把版本降级到1.0.2-beta.48了 问题好像还没解决
> I downgraded the version to1.0.2-beta.48. The problem seems to be unresolved.

It working for me. 
- vue@3.1.1
- element-plus@1.0.2-beta.48
Just reinstall packages.

**Comment by 9-lives** [comment]
> 我把版本降级到1.0.2-beta.48了 问题好像还没解决
> I downgraded the version to1.0.2-beta.48. The problem seems to be unresolved.

make sure it element-plus 1.0.2-beta.48 not ^element-plus 1.0.2-beta.48

**Comment by YangYmimi** [comment]
vue@3.1.1
element-plus@1.0.2-beta.51
work for me

**Comment by libbGit** [comment]
me too, 1.0.2-beta.53

**Comment by jsun969** [comment]
It work for me when I remove '^' from version
```json
"dependencies": {
    ...
    "element-plus": "1.0.2-beta.48",
    "vue": "^3.0.5",
  },
```

**Comment by NO-MAP** [comment]
53 还有这个问题  救一下啊哥哥们

**Comment by SadWood** [comment]
同样的问题，依旧没有得到解决

**Comment by NO-MAP** [comment]
> 同样的问题，依旧没有得到解决

回退到 48 可以暂时解决这个严重bug，但是又衍生了其他的问题
比如：树形表格的hover高亮会出现混乱。

希望官方尽快处理这个问题吧，影响到上线了...

**Comment by kooriookami** [comment]
#2384

**Comment by Sunday0717** [comment]
官方赶快解决吧，这么大的Bug

**Comment by 604587986** [comment]
回退到48 時間選擇器又有bug

**Comment by SadWood** [comment]
官方更新54了，亲测问题解决了

**Comment by libbGit** [comment]
> 官方更新54了，亲测问题解决了

唉，这么明显的bug，官方更新版本后，都没发现，真不知道他们的测试是干什么的

**Comment by kooriookami** [comment]
Please update to the latest version, sorry for the inconvenience.

**Comment by imminmin** [comment]
> 官方更新54了，亲测问题解决了

为什么我更新到54还是不行

**Comment by yzend** [comment]
> > 官方更新54了，亲测问题解决了
> 
> 为什么我更新到54还是不行

可以试下 onMounted 后赋值

**Comment by CaiWenlie** [comment]
> > 官方更新54了，亲测问题解决了
> 
> 唉，这么明显的bug，官方更新版本后，都没发现，真不知道他们的测试是干什么的

现在都不敢随便升级，问题一大堆，头疼

**Comment by kooriookami** [comment]
> > > 官方更新54了，亲测问题解决了
> > 
> > 
> > 唉，这么明显的bug，官方更新版本后，都没发现，真不知道他们的测试是干什么的
> 
> 现在都不敢随便升级，问题一大堆，头疼

谅解哦，成员不是全职维护的，也有自己的工作。有明显的问题一定会第一时间修复，另外也需要社区的支持。有意愿帮忙测试或者提交 PR 的，都很欢迎！~
