### ISSUE TITLE
[bug report] 级联选择器懒加载

### ISSUE THREAD

**Issue by qinpeip** [element-plus/element-plus#2366]
> ### Element Plus version
> 1.0.2-beta.45
> 
> ### OS/Browsers version
> mac OS
> 
> ### Vue version
> 3.1.0-beta.6
> 
> ### Reproduction Link
> https://codesandbox.io/s/long-dawn-vnmjm?file=/src/App.vue
> 
> ### Steps to reproduce
> 业务场景：在编辑的时候需要回显选中的数据。
> 
> 1. 因为设置了懒加载，所以我在回显的时候需要手动把选中的二级菜单数据加入到一级菜单中。
>    2.但是这就导致了我在点击一级菜单的时候，不会在加载二级菜单的数据了（只加载了已选中的数据，没有加载全部二级数据），同时我点击其他的一级菜单，也没有加载该菜单下的二级数据。
> 
> ### What is Expected?
> 希望能够加载全部的二级数据。
> 
> ### What is actually happening?
> 没有加载子级菜单的全部数据，并且点击其他的一级菜单也没有加载子级菜单的数据。

_Originally posted by @qinpeip in https://github.com/element-plus/element-plus/issues/2106#issuecomment-869494989_

**Comment by wenfangdu** [comment]
Is it still reproducible in `v1.0.2-beta.53`?

**Comment by msidolphin** [comment]
Please upgrade to the latest version.

**Comment by qinpeip** [comment]
是的，问题还是存在。我使用 v-1.0.2-beta.63 测试了一下。问题还是存在。
我遇到的问题是：虽然默认加载了已经选中的二级数据，但是我还有未选中的二级数据，无法加载出来。
这是我测试问题的新链接：
https://codesandbox.io/embed/happy-brahmagupta-hlx1j?fontsize=14&hidenavigation=1&theme=dark

**Comment by qinpeip** [comment]
@msidolphin 请您重新看下这个问题的，谢谢。

**Comment by msidolphin** [comment]
> @msidolphin 请您重新看下这个问题的，谢谢。

https://user-images.githubusercontent.com/26672484/127156371-2419f57c-a189-4071-a9f8-de6b3bd4c898.mp4

**Comment by qinpeip** [comment]
> > @msidolphin 请您重新看下这个问题的，谢谢。
> 
> 没有重现
> 
>  Kapture.2021-07-27.at.20.49.46.mp4

您好，现在的问题是： 标签0下面的子标签，除了显示选中的数据，还应该加载未选中的数据。现在是只显示了选中的数据。未选中的数据没有展示。

**Comment by msidolphin** [comment]
> 是

很抱歉，这段时候工作比较忙现在才看到，我认为我既然把数据已经加载过了就应该加载完整啊，组件会认为数据已经加载完毕的。如果不这么做开发者也需要自己去判断某项的数据是否加载完成

**Comment by msidolphin** [comment]
> > > @msidolphin 请您重新看下这个问题的，谢谢。
> > 
> > 
> > 没有重现
> > Kapture.2021-07-27.at.20.49.46.mp4
> 
> 您好，现在的问题是： 标签0下面的子标签，除了显示选中的数据，还应该加载未选中的数据。现在是只显示了选中的数据。未选中的数据没有展示。

很抱歉，这段时候工作比较忙现在才看到，我认为我既然把数据已经加载过了就应该加载完整啊，组件会认为数据已经加载完毕的。如果不这么做开发者也需要自己去判断某项的数据是否加载完成

**Comment by msidolphin** [comment]
> > > @msidolphin 请您重新看下这个问题的，谢谢。
> > 
> > 
> > 没有重现
> > Kapture.2021-07-27.at.20.49.46.mp4
> 
> 您好，现在的问题是： 标签0下面的子标签，除了显示选中的数据，还应该加载未选中的数据。现在是只显示了选中的数据。未选中的数据没有展示。

很抱歉，最近工作比较忙现在才看到，其实这个问题是因为node判断存在children就认为loaded了，如果不这么做的话我们需要让开发者自己去维护这个loaded状态或者不管有没有load我们都触发加载（但是这样也需要开发者自己判断是否loaded）。所以我认为现在的设计还是很合理的，你需要自己加载完整的数据

**Comment by qinpeip** [comment]
> > > > @msidolphin 请您重新看下这个问题的，谢谢。
> > > 
> > > 
> > > 没有重现
> > > Kapture.2021-07-27.at.20.49.46.mp4
> > 
> > 
> > 您好，现在的问题是： 标签0下面的子标签，除了显示选中的数据，还应该加载未选中的数据。现在是只显示了选中的数据。未选中的数据没有展示。
> 
> 很抱歉，最近工作比较忙现在才看到，其实这个问题是因为node判断存在children就认为loaded了，如果不这么做的话我们需要让开发者自己去维护这个loaded状态或者不管有没有load我们都触发加载（但是这用样也需要开发者自己判断是否loaded）。所以我认为现在的设计还是很合理的，你需要自己加载完整的数据

您好，您可以看下这个：
https://codesandbox.io/s/immutable-platform-5nm75?file=/src/App.vue
这是我在element-ui版本中做的实验，在这个版本中是可以实现我想要的功能的。因为这是我在项目中需要用到的。所以希望您能看看有什么好的解决办法吗？

**Comment by msidolphin** [comment]
> > > > > @msidolphin 请您重新看下这个问题的，谢谢。
> > > > 
> > > > 
> > > > 没有重现
> > > > Kapture.2021-07-27.at.20.49.46.mp4
> > > 
> > > 
> > > 您好，现在的问题是： 标签0下面的子标签，除了显示选中的数据，还应该加载未选中的数据。现在是只显示了选中的数据。未选中的数据没有展示。
> > 
> > 
> > 很抱歉，最近工作比较忙现在才看到，其实这个问题是因为node判断存在children就认为loaded了，如果不这么做的话我们需要让开发者自己去维护这个loaded状态或者不管有没有load我们都触发加载（但是这用样也需要开发者自己判断是否loaded）。所以我认为现在的设计还是很合理的，你需要自己加载完整的数据
> 
> 您好，您可以看下这个：
> https://codesandbox.io/s/immutable-platform-5nm75?file=/src/App.vue
> 这是我在element-ui版本中做的实验，在这个版本中是可以实现我想要的功能的。因为这是我在项目中需要用到的。所以希望您能看看有什么好的解决办法吗？

因为element2初始化node的时候loaded状态直接赋值为false了
