### ISSUE TITLE
[Bug Report] Icon is not used when i install 1.0.2-beta.53

### ISSUE THREAD

**Issue by cmdparkour** [element-plus/element-plus#2367]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
QQ浏览器

### Vue version
3.1.2

### Reproduction Link
https://github.com/cmdparkour/vue-admin-box

### Steps to reproduce
use <i class="el-icon-*">

### What is Expected?
has not the right icon as i want to see

### What is actually happening?
i use the package 1.0.2-beta.42 before ,and i use yarn to update the package

**Comment by cmdparkour** [comment]
it's not a but in element-plus ,it's the bug from vite 2.3.7 to 2.3.8, i fixed it

**Comment by ThreeFiveSevenWords** [comment]
> 它不是但在 element-plus 中，它是从 vite 2.3.7 到 2.3.8 的错误，我修复了它

how to fix it?degraded version vite?
