### ISSUE TITLE
Form validation in [feature request] < script lang = "ts" setup >.

### ISSUE THREAD

**Issue by iZaiZaiA** [element-plus/element-plus#2371]
### Existing Component
Yes

### Component Name
el-form

### Description
<script lang="ts" setup> 中，应该如何效验表单？？官方示例的代码，在 <script lang="ts" setup>中并不能使用。

**Comment by iZaiZaiA** [comment]
找到解决方案了，已经解决了

**Comment by qiuguanyou** [comment]
> 找到解决方案了，已经解决了

请问是怎么处理的呢？

**Comment by xiuxiuyifan** [comment]
> 找到解决方案了，已经解决了

我也遇见了，目前采用的defineComponent的形式才可以
