### ISSUE TITLE
The internationalization in element plus is normal in the development environment, and an error is reported after deployment

### ISSUE THREAD

**Issue by sonicsunsky** [element-plus/element-plus#2374]
使用vite按需加载element-plus，在国际化使用中按照如下文档配置发现在vite dev开发环境下使用正常，在vite build部署后local(lang)会报错，经过打印locale发现开发环境下locale没有use方法，但是在正式部署后打印locale发现有use方法，改为locale.use(lang)后正常，开发和正式部署下的locale表现不一致。分别打印不同环境下的locale就可以发现问题。

如果是通过 es modules 按需引入 Element Plus:

import { createApp } from 'vue'
import { ElButton, locale } from 'element-plus'
import lang from 'element-plus/lib/locale/lang/zh-cn'
import 'dayjs/locale/zh-cn'

locale(lang) 这里在开发环境下可以，在正式环境下会报错，改为locale.use(lang)后正常
createApp(App).component(ElButton.name, ElButton)

**Comment by yys-0505** [comment]
Same issue: locale.use(lang) works well in local, but saying 'p is not a function' when deployed with production version. 'p' refers to 'locale'
![image](https://user-images.githubusercontent.com/11680854/123896501-46bb4f80-d994-11eb-9846-32107f03292d.png)

**Comment by yys-0505** [comment]
workaround: import.meta.env.DEV ? locale(lang) : locale.use(lang)

**Comment by sonicsunsky** [comment]
> workaround: import.meta.env.DEV ? locale(lang) : locale.use(lang)
yes, we can do that, but the problem is that

**Comment by sonicsunsky** [comment]
1. yarn dev正常;
2. yarn build打包后报错;
3. yarn dev和yarn build locale表现不一致，应该表现一致;
4. 按照文档按需引入element-plus即可复现;

**Comment by sonicsunsky** [comment]
[bug report] vite introduces element plus international packaging error on demand #2403 the same issue

**Comment by sonicsunsky** [comment]
> workaround: import.meta.env.DEV ? locale(lang) : locale.use(lang)

是的，这样应该可以，这个是element-plus的问题，开发和生产打印的locale应该保持一致，不应该用这中hack的方式去解决，不太优雅
