### ISSUE TITLE
Table action display problem

### ISSUE THREAD

**Issue by wayiqi** [element-plus/element-plus#2381]
前提：
    1. table设置了max-length
    2. table设置操作列，并设置fixed="right"
问题：
    table超出部分显示异常，如图所示：
![image](https://user-images.githubusercontent.com/45176899/123761156-220f9b00-d8f4-11eb-9f5d-bbbeb34d0fd7.png)

**Comment by wayiqi** [comment]
删掉is-hidden属性，显示正常，顺便问一下：is-hidden属性的使用场景是什么？文档中暂未看到该属性的说明

**Comment by wayiqi** [comment]
![image](https://user-images.githubusercontent.com/45176899/123762060-fccf5c80-d8f4-11eb-8eaa-558e6313407d.png)

**Comment by msidolphin** [comment]
is-hidden是用来隐藏固定列，如果存在bug请提供复现链接

**Comment by wayiqi** [comment]
复现链接：
https://codesandbox.io/s/upbeat-lumiere-eo513?file=/src/components/HelloWorld.vue
直接原因：自定义table的高度与滚动条
场景：table需要适配不同分辨率的显示器，所以自定义table高度
           `.el-table {
                   border: 1px solid #e7e7e7 !important;
                   height: calc(100vh - 240px) !important;
                   overflow-y: auto !important;
            }`

（哈哈哈哈 之前一直怀疑提供复现链接的必要性，emmm确实有必要哈，这样，自己才能真正找到问题 ）

**Comment by msidolphin** [comment]
你没有必要去使用样式固定table的高度，可以传入height

**Comment by wayiqi** [comment]
emmmmmm 有道理，好的 蟹蟹啦
