### ISSUE TITLE
[Bug Report] SassError: Invalid CSS after "...-height: #{math": expected expression (e.g. 1px, bold), was ".div($--input-heigh"

### ISSUE THREAD

**Issue by yudan215** [element-plus/element-plus#2383]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
win10

### Vue version
3.1.2

### Reproduction Link
http://jsfiddle.com

### Steps to reproduce
从版本1.0.2-beta.30升级到1.0.2-beta.53版本报错

### What is Expected?
正常编译

### What is actually happening?
./src/assets/styles/element-variables.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...-height: #{math": expected expression (e.g. 1px, bold), was ".div($--input-heigh"
        on line 142 of node_modules/element-plus/packages/theme-chalk/src/input-number.scss
        from line 13 of node_modules/element-plus/packages/theme-chalk/src/index.scss
        from line 12 of C:\vue\hy-english-admin\src\assets\styles\element-variables.scss
>>       line-height: #{math.div($--input-height - 2, 2)};

   -------------------------^

    at C:\vue\hy-english-admin\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\vue\hy-english-admin\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\vue\hy-english-admin\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\vue\hy-english-admin\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.callback (C:\vue\hy-english-admin\node_modules\sass-loader\dist\index.js:73:7)
    at Object.done [as callback] (C:\vue\hy-english-admin\node_modules\neo-async\async.js:8069:18)
    at options.error (C:\vue\hy-english-admin\node_modules\node-sass\lib\index.js:294:32)

**Comment by xxyGoTop** [comment]
同样的错

**Comment by yudan215** [comment]
> 错的同

换成dart-sass就正常了

**Comment by wxxcarl** [comment]
`File: XXX/node_modules/element-plus/packages/theme-chalk/src/input-number.scss
  Error: Undefined function.
      ╷
  142 │       line-height: #{math.div($--input-height - 2, 2)};
      │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ╵
    node_modules/element-plus/packages/theme-chalk/src/input-number.scss 142:22  @content
    node_modules/element-plus/packages/theme-chalk/src/mixins/mixins.scss 90:11  e()
    node_modules/element-plus/packages/theme-chalk/src/input-number.scss 140:5   @content
    node_modules/element-plus/packages/theme-chalk/src/mixins/mixins.scss 168:7  when()
    node_modules/element-plus/packages/theme-chalk/src/input-number.scss 134:3   @content
    node_modules/element-plus/packages/theme-chalk/src/mixins/mixins.scss 74:5   b()
    node_modules/element-plus/packages/theme-chalk/src/input-number.scss 7:1     @import
    node_modules/element-plus/packages/theme-chalk/src/index.scss 13:9           @import
    src/assets/style/index.scss 24:9                                             root stylesheet
      at Object._newRenderError (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:13494:19)
      at Object._wrapException (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:13337:16)
      at _render_closure1.call$2 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:80007:21)
      at _RootZone.runBinary$3$3 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:27193:18)
      at _FutureListener.handleError$1 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:25721:19)
      at _Future__propagateToListeners_handleError.call$0 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:26018:49)
      at Object._Future__propagateToListeners (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:4539:77)
      at _Future._completeError$2 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:25851:9)
      at _AsyncAwaitCompleter.completeError$2 (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:25194:12)
      at Object._asyncRethrow (/Users/sy/work/self/door-front/node_modules/sass/sass.dart.js:4288:17)`

我本来就是dart，还是报错，类似的错误

**Comment by wuxj00** [comment]
从 1.0.2-beta.45开始就看是报错，44还是好的，内部scss框架变了是不是有啥依赖要单独装啊

**Comment by lbjlsy** [comment]
装了dart-sass不管用，从1.0.2-beta.44 升级到55也是报这个错误 line-height: #{math.div($--input-height - 2, 2)}; 用的是Vite

**Comment by Isliwei** [comment]
Syntax Error: SassError: Invalid CSS after "$--colors: map": expected expression (e.g. 1px, bold), was ".deep-merge("

版本撤回到.32也不行，啥时候能解决

**Comment by lbjlsy** [comment]
> 装了dart-sass不管用，从1.0.2-beta.44 升级到55也是报这个错误 line-height: #{math.div($--input-height - 2, 2)}; 用的是Vite

升级了sass和sass-loader之后可以了，已经升级到 1.0.2-beta.59 版本。

**Comment by Daisy-ZLY** [comment]
beta45版本升级了sass【Chore Project: bump sass from 1.26.10 to 1.34.0 (#2060)】，beta45+需要升级sass到1.34.0+，就可以正常显示了

**Comment by scarsu** [comment]
目前在1.0.2-beta.65版本，sass版本1.35.1，仍然有报错”Syntax Error: SassError: Invalid CSS after "$--colors: map": expected expression (e.g. 1px, bold), was ".deep-merge("
        on line 14 of node_modules/element-plus/packages/theme-chalk/src/common/var.scss“

**Comment by scarsu** [comment]
node-sass 改成 dart-sass后可以了。

**Comment by jjshuai** [comment]
我是修改 babel.config.js 中element-plus按需引入方式解决的
之前是这样的
```js
[
    'import',
    {
      libraryName: 'element-plus',
      customStyleName: name => {
        name = name.slice(3)
        return `element-plus/packages/theme-chalk/src/${name}.scss`
      }
    }
  ]
```
修改后
```js
[
  'component',
  {
    libraryName: 'element-plus',
    styleLibraryName: 'theme-chalk'
  }
],

```

**Comment by Isliwei** [comment]
试过了，不行



在 2021-07-31 15:20:49，"ScarSu" ***@***.***> 写道：

node-sass 改成 dart-sass后可以了。

**Comment by Isliwei** [comment]
嗯，难搞，我用回了原来的包



在 2021-07-31 10:43:10，"ScarSu" ***@***.***> 写道：

目前在1.0.2-beta.65版本，sass版本1.35.1，仍然有报错”Syntax Error: SassError: Invalid CSS after "$--colors: map": expected expression (e.g. 1px, bold), was ".deep-merge("
on line 14 of node_modules/element-plus/packages/theme-chalk/src/common/var.scss“

**Comment by napoleonjk** [comment]
改sass版本，亲测可以的。

配置参考：

1.main.ts 
`
import '@/assets/styles/element-variables.scss'
`
2.element-variables.scss
`
/* 改变主题色变量 */ 
$--color-primary: #33d65e; 
/* 改变 icon 字体路径变量，必需 */
$--font-path: '~element-plus/lib/theme-chalk/fonts';
@import "~element-plus/packages/theme-chalk/src/index";
`
3.package.json
`
"element-plus": "^1.0.2-beta.71"
"sass": "^1.38.0" 
`

参考来源：https://element-plus.org/#/zh-CN/component/custom-theme

**Comment by noeGnh** [comment]
@zxzybin 我也有同样的问题，发现发生这种情况是因为color-primary-light变量没有被改变，它们保持着默认值。我试着在element-variables.scss文件中重新定义它们，但并不奏效。

**Comment by napoleonjk** [comment]
> 改sass版本，亲测可以的。
> 
> 配置参考：
> 
> 1.main.ts
> 
> `import '@/assets/styles/element-variables.scss'`
> 
> 2.element-variables.scss
> 
> ```
> /* 改变主题色变量 */ 
> 
> $--color-primary: #33d65e; 
> 
> /* 改变 icon 字体路径变量，必需 */
> 
> $--font-path: '~element-plus/lib/theme-chalk/fonts';
> 
> @import "~element-plus/packages/theme-chalk/src/index";
> ```
> 
> 3.package.json
> 
> ```
> "element-plus": "^1.0.2-beta.71"，
> 
> "sass": "^1.38.0" 
> ```
> 
> 参考来源：https://element-plus.org/#/zh-CN/component/custom-theme

按照此配置，按钮的主题色确实还有问题，官方这里可能还是有bug。
我又看了一下我的代码，发现我还加了个主题配置（main.ts ： @/assets/styles/color.scss )。
color.scss：
```
$--color-primary: #33d65e;
$--font-path: './theme/fonts';
@import "./theme/index.css";
```

但这和官方文档说明不太一致，怪怪的，总之暂时可以work。

**Comment by kuaifengle** [comment]
![image](https://user-images.githubusercontent.com/24524172/132828619-e8f3536b-f2d7-464c-8eff-926988a60c1b.png)
设置了  "sass": "^1.38.0"
按钮背景色没变

**Comment by y-pp** [comment]
> ![image](https://user-images.githubusercontent.com/24524172/132828619-e8f3536b-f2d7-464c-8eff-926988a60c1b.png)
> 设置了 "sass": "^1.38.0"
> 按钮背景色没变

我也遇到同样问题

**Comment by WeiXingLiu** [comment]
@zxzybin 
![image](https://user-images.githubusercontent.com/13642337/134880347-fd39f344-ea6d-4ac0-b4d1-09031e9fe6f9.png)
我是这样写的可以的

**Comment by WeiXingLiu** [comment]
@zxzybin 
![image](https://user-images.githubusercontent.com/13642337/134881997-1274b231-883b-4e75-b366-682a52ba9ca8.png)
我这样写可以的

**Comment by Js-Man-H5** [comment]
换肤教程不够详细 很多问题，而且这个功能重要，麻烦官方重视一下吧

**Comment by PLQin** [comment]
看：https://github.com/ElemeFE/element/issues/21494
解决方法：暂时先使用2.15.6

**Comment by 664215399** [comment]
> 配置参考：
> 
> 1.main.ts
> 
> import '@/assets/styles/element-variables.scss'
> 
> 2.element-variables.scss
> 
> /* 改变主题色变量 */
> 
> $--color-primary: #33d65e;
> 
> /* 改变 icon 字体路径变量，必需 */
> 
> $--font-path: '~element-plus/lib/theme-chalk/fonts';
> 
> @import "~element-plus/packages/theme-chalk/src/index"; 3.package.json
> 
> "element-plus": "^1.0.2-beta.71"，
> 
> "sass": "^1.38.0"
> 
> ### **按照这个配置，主题色确实变了，但是按钮主题色还是没变？有人遇到过吗？？？**

我也遇到过
