### ISSUE TITLE
Drop down to select bug, the development environment is normal, and there is a problem when executing build

### ISSUE THREAD

**Issue by huanggengzhong** [element-plus/element-plus#2384]
![image](https://user-images.githubusercontent.com/45531884/123794413-665f6300-d915-11eb-831e-ae62c4f9cb8d.png)

**Comment by 9-lives** [comment]
#2365

**Comment by libbGit** [comment]
我这边也是，一模一样，开发上好着，编译后空白

**Comment by initchen** [comment]
![image](https://user-images.githubusercontent.com/46468802/123964543-18fef680-d9e6-11eb-9161-f64bcc136bba.png)
一样的, 请问上面的伙伴解决了吗

**Comment by KangpingWANG** [comment]
The same problem for me. Switching to Select V2 as a temporary solution. Hope the bug can be fixed in next version.

**Comment by allowing** [comment]
Same problem

**Comment by shaolongwendd01** [comment]
降至1.0.2-beta.52版本

**Comment by Dawnxiaozhao** [comment]
解决了吗？影响上线了！！！

**Comment by initchen** [comment]
> 解决了吗？影响上线了！！！

回退版本解决的, 注意package.json里版本号的^号要去掉, 不然回退没效果

**Comment by kooriookami** [comment]
Please update to the latest version, sorry for the inconvenience.
