### ISSUE TITLE
el-date-picker ： drop-down options location

### ISSUE THREAD

**Issue by sinsy** [element-plus/element-plus#2386]
el-date-picker ：drop-down options will appear on the left and right,
expect: if there is enough space above, it will appear on the top

![image](https://user-images.githubusercontent.com/4956934/123892455-35bb1000-d98d-11eb-9aaa-c00375634bd9.png)

**Comment by kooriookami** [comment]
Because the top has no enough sapce. You can give top more space and try agian.
