### ISSUE TITLE
[Bug Report] el-select-v2 do not support scroll on touch screen device

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#2400]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
Chrome Dev 93 in Android 10

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/kawaiizapic/full/JjNoQVK

### Steps to reproduce
1. Create a select-v2
2. Try to scroll the drop-down menu, or drag the scroll bar.

### What is Expected?
Scroll up and down

### What is actually happening?
Nothing.

**Comment by sxzz** [comment]
Hi. It seems to be okay now. If you have any questions, please feel free to reopen this issue.
