### ISSUE TITLE
[Bug Report] eltable replace update bug

### ISSUE THREAD

**Issue by aa294828045** [element-plus/element-plus#2401]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome

### Vue version
3.1.2

### Reproduction Link
https://codesandbox.io/s/intelligent-darwin-ykxzb?file=/src/App.vue

### Steps to reproduce
Looking at the browser console, there are two options, from top to bottom, called a and B. A is outside the El table, and changing the value controls the output only once a day. Interestingly, select b nested in the El table, and you will find that there will be two outputs
=====
chinese: 查看浏览器控制台，有两个option，由上至下，称为A和B，A在el-table外面，更改值控制天只输出一次，然后有意思的是，选择嵌套在el-table里面的B，你会发现会有两次的输出

### What is Expected?
Methods that should not be executed twice in El table

### What is actually happening?
fix the issue

**Comment by aa294828045** [comment]
chrome 版本 89.0.4389.128（正式版本） （64 位）

**Comment by msidolphin** [comment]
el-select is also rendered in hidden-columns
