### ISSUE TITLE
[Bug Report] el-row default css error

### ISSUE THREAD

**Issue by chiyu1996** [element-plus/element-plus#2402]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/chiyu1996/pen/ExmjjmL

### Steps to reproduce
文档中说明 type布局模式，可选 flex，现代浏览器下有效，无默认值。为何默认样式是flex？

### What is Expected?
.el-row {
    position: relative;
    box-sizing: border-box;
}

### What is actually happening?
.el-row {
    display: flex;
    flex-wrap: wrap;
    position: relative;
    box-sizing: border-box;
}

**Comment by msidolphin** [comment]
#1912
