### ISSUE TITLE
[bug report] vite introduces element plus international packaging error on demand

### ISSUE THREAD

**Issue by a586543** [element-plus/element-plus#2403]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/licheng586/pen/bGWdVwo

### Steps to reproduce
使用vite搭建项目，按需引入Element Plus,配置国际化开发环境运行正常，打包生产环境运行报错，开发环境运行控制台打印locale为函数，打包生产环境运行打印locale为一个包含'use'属性的对象

### What is Expected?
locale(lang)

### What is actually happening?
 locale.use(lang)

**Comment by sonicsunsky** [comment]
我也遇到了这个问题了

**Comment by xinhuaer** [comment]
找了好久问题，原来是这个国际化配置导致的问题，泪奔啊；花了好多时间定位问题

**Comment by sxzz** [comment]
It seems that there is a solution: https://github.com/element-plus/element-plus/issues/2374

Feel free to reopen this issue if you have any question.
