### ISSUE TITLE
El upload file list not updated 1.0.2-beta.52

### ISSUE THREAD

**Issue by Dawnxiaozhao** [element-plus/element-plus#2405]
设置 :file-list="fileList" 
改变fileList之后并且 this.$forceUpdate(); 
数据没有更新！！！

**Comment by msidolphin** [comment]
Please provide any reproduction link.

**Comment by Dawnxiaozhao** [comment]
> Hello @Dawnxiaozhao. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> 
> 你好 @Dawnxiaozhao, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。

git@github.com:Dawnxiaozhao/element-plus-upload.git

**Comment by msidolphin** [comment]
I have fixed this problem, but I recommend that you use `accept` to filter files
