### ISSUE TITLE
[Bug Report] label cannot display in el-select component

### ISSUE THREAD

**Issue by JamesCZF** [element-plus/element-plus#2407]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome 90.0.4430.212

### Vue version
3.0.0

### Reproduction Link
https://github.com/JamesCZF/problem-display

### Steps to reproduce
1.pull the code from the repository I provide in Reproduction Link
2.npm install  then npm run build
3.run the dist file , then you can see the problem. label donot display in the page

### What is Expected?
label in el-select component after build should display 

### What is actually happening?
label donot display in el-select component after npm run build. development is fine.

**Comment by JamesCZF** [comment]
![image](https://user-images.githubusercontent.com/39017262/124151894-9baab300-dac5-11eb-9af5-bf3ce512087c.png)
this is the problem img

**Comment by JamesCZF** [comment]
i find a way to solve this problem .  assignment in onMounted
`
setup() {
    const options = ref([])
    onMounted(() => {
      options.value = [
      {
        value: '选项1',
        label: '黄金糕'
      }, {
        value: '选项2',
        label: '双皮奶'
      }
    ]
    })
    return {
      options
    }
  }
`

**Comment by msidolphin** [comment]
Please upgrade to the latest version
