### ISSUE TITLE
[bug report] how to restore the component size set globally to the default without reporting warning in the console

### ISSUE THREAD

**Issue by wellfrog16** [element-plus/element-plus#2408]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
无

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/wellfrog16/pen/YzVXQRN

### Steps to reproduce
全局设置element的size：
`app.use(ElementPlus, { size: 'small' });`

之后我需要恢复默认的button大小，设置一个不存在的size：
`<el-button size="default">按钮</el-button>`
效果可以实现，但是会在console报warning

### What is Expected?
当前这个button恢复默认从尺寸大小，console不会报warning

### What is actually happening?
当前这个button恢复默认从尺寸大小，但是console报warning

**Comment by msidolphin** [comment]
Because accepted values are only medium / small / mini, i think this is not a bug

**Comment by wellfrog16** [comment]
> Because accepted values are only medium / small / mini, i think this is not a bug

@msidolphin 在全局设置了size之后，如何在单个ui里恢复default尺寸（未做全局设置时ui样式）
