### ISSUE TITLE
[bug report] El table fixed column moving vertical line causes typesetting error

### ISSUE THREAD

**Issue by wenyuanSun** [element-plus/element-plus#2409]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
windows chrome

### Vue version
3.1.3

### Reproduction Link
jsfiddle/codepen/codesandbox

### Steps to reproduce
table表格固定列部分，先去移动 操作列 前面的可移动竖线，移动至中间位置，此时原本的一条竖线会变成两条竖线，此时在将第二条竖线向右拖拽至由顶端，排版出错。

### What is Expected?
最后一列与倒数第二列之间会出现额外一列且出现空白，有时固定列也会发生变成

### What is actually happening?
最后一列与倒数第二列之间会出现额外一列且出现空白，有时固定列也会发生变成

**Comment by wenyuanSun** [comment]
![b3877b0229b30e0391bc7b3ef54a03d](https://user-images.githubusercontent.com/43402583/124208250-bdce2080-db19-11eb-84f6-d5471f858ec9.png)

**Comment by msidolphin** [comment]
你可以暂时将某些列不设置列宽以适应弹性布局，这样就能解决这个问题了

**Comment by sxzz** [comment]
The Table component is planning to refactor. Please wait for the new component.
