### ISSUE TITLE
The value format attribute of datepicker component of [feature request] element plus does not support the output of timestamp format

### ISSUE THREAD

**Issue by javazeng** [element-plus/element-plus#2416]
### Existing Component
Yes

### Component Name
1.0.2-beta.45

### Description
chrome

**Comment by msidolphin** [comment]
You can set value-format to 'x'

https://day.js.org/docs/en/plugin/advanced-format

**Comment by iamkun** [comment]
you can use `value-format="x"`

e.g. https://github.com/element-plus/element-plus/pull/2449/files
