### ISSUE TITLE
Upload verification problem

### ISSUE THREAD

**Issue by zy201114** [element-plus/element-plus#2418]
设置自动上传后 before-upload返回false还是会自动上传，用Promise来验证也无效

**Comment by Dawnxiaozhao** [comment]
git@github.com:Dawnxiaozhao/element-plus-upload.git

**Comment by Dawnxiaozhao** [comment]
> Hello @zy201114. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> 
> 你好 @zy201114, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。

git@github.com:Dawnxiaozhao/element-plus-upload.git

**Comment by msidolphin** [comment]
> > Hello @zy201114. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> > 你好 @zy201114, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。
> 
> [git@github.com](mailto:git@github.com):Dawnxiaozhao/element-plus-upload.git

你的这个重现仓库好像和你前面描述的不一样啊，请提供一个能够重现问题的链接或者仓库

**Comment by Dawnxiaozhao** [comment]
> > > Hello @zy201114. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.
> > > 你好 @zy201114, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。
> > 
> > 
> > [git@github.com](mailto:git@github.com):Dawnxiaozhao/element-plus-upload.git
> 
> 你的这个重现仓库好像和问题描述的不一样啊，请提供一个能够重现问题的链接、仓库或者重新提交一个issue

不好意识，我提错 issues

**Comment by sxzz** [comment]
Please provide a correct reproduction link and reopen this issue.
