### ISSUE TITLE
Can you add a top navigation menu similar to ant-design-vue to display three points beyond the display, and click on the three points to temporarily hide the menu?

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#2422]
Recurring address: https://www.antdv.com/components/menu-cn/

**Comment by XingXiaoWu** [comment]
you means this? https://element-plus.gitee.io/#/zh-CN/component/menu#zhe-die

**Comment by xiaoxian521** [comment]
https://www.antdv.com/components/menu-cn/#%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA
就是导航项太多显示...  然后通过点击... 去展开 在一行显示不下的导航

**Comment by XingXiaoWu** [comment]
![image](https://user-images.githubusercontent.com/22769131/124561012-0108f600-de70-11eb-87eb-26b3ca42db39.png)
I need to reduce the width of the browser, like this?

**Comment by xiaoxian521** [comment]
是的哦

**Comment by sxzz** [comment]
sovled in #3083
