### ISSUE TITLE
[bug report] the style of the internal component tool tip in the shrink mode menu is lost when it is loaded on demand

### ISSUE THREAD

**Issue by nabaonan** [element-plus/element-plus#2423]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
Mac 10.15.7

### Vue version
3.1.2

### Reproduction Link
https://codesandbox.io/s/elem-bug-menu-style-fju5d?file=/src/App.vue

### Steps to reproduce
鼠标hover到菜单

### What is Expected?
右侧应该有个黑色的tootip组件显示出title

### What is actually happening?
没有加载tootip的样式

**Comment by china-bin** [comment]
把 vite-plugin-style-import 换成直接在main.ts
`import "element-plus/lib/theme-chalk/index.css";` 这样就没问题。


https://codesandbox.io/s/elem-bug-menu-style-forked-dp30h?file=/src/main.ts

**Comment by nabaonan** [comment]
> 把 vite-plugin-style-import 换成直接在main.ts
> `import "element-plus/lib/theme-chalk/index.css";` 这样就没问题。
> 
> 
> https://codesandbox.io/s/elem-bug-menu-style-forked-dp30h?file=/src/main.ts

这个是全量引入样式吧，我想样式按需加载

**Comment by msidolphin** [comment]
菜单依赖了tooltip、tooltip依赖了popper，所以暂时的解决方式是把它们也引入进来

**Comment by nabaonan** [comment]
> 菜单依赖了tooltip、tooltip依赖了popper，所以暂时的解决方式是把它们也引入进来

嗯，我没有太仔细测其他组件会不会有类似的依赖关系，也有可能存在重复引入同一个样式吧
