### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by qdleader** [element-plus/element-plus#2429]
在vite2和vue3用ts搭建的的项目中icon 不显示

**Comment by qdleader** [comment]
import { createApp } from 'vue'
import App from './App.vue'

import ElementPlus from 'element-plus'
import 'element-plus/lib/theme-chalk/index.css';

createApp(App).use(ElementPlus).mount('#app')



新搭建的项目，引入就出不来

  <i class="el-icon-share"></i>
<i class="el-icon-delete"></i>
<el-button type="primary" icon="el-icon-search">搜索</el-button>

icon 不显示

**Comment by qdleader** [comment]
我直接在index.html中引入<link rel="stylesheet" href="https://unpkg.com/element-plus/lib/theme-chalk/index.css">这个才可以，直接import 'element-plus/lib/theme-chalk/index.css';不行

**Comment by kooriookami** [comment]
#2342

**Comment by allowing** [comment]
what element-plus version is?

**Comment by qdleader** [comment]
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "element-plus": "^1.0.2-beta.54",
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "typescript": "^4.3.2",
    "vite": "^2.3.8",
    "vue-tsc": "^0.0.24"
  }
}

**Comment by SugarAdam** [comment]
I have the same problem, and the version is "1.0.2-beta.54".
T_T

<yarn add sass + import 'element-plus/packages/theme-chalk/src/index.scss'; >  instead of <import 'element-plus/lib/theme-chalk/index.css';> didn't work.

**Comment by zhan1025** [comment]
do this:
yarn add sass -D

vite:
styleImport({
      libs: [{
        libraryName: 'element-plus',
        esModule: true,
        ensureStyleFile: true,
        resolveStyle: (name) => {
          name = name.slice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    }),

**Comment by zhan1025** [comment]
do this:
yarn add sass -D

vite:
styleImport({
      libs: [{
        libraryName: 'element-plus',
        esModule: true,
        ensureStyleFile: true,
        resolveStyle: (name) => {
          name = name.slice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    }),

**Comment by SugarAdam** [comment]
> do this:
> yarn add sass -D
> 
> vite:
> styleImport({
> libs: [{
> libraryName: 'element-plus',
> esModule: true,
> ensureStyleFile: true,
> resolveStyle: (name) => {
> name = name.slice(3)
> return `element-plus/packages/theme-chalk/src/${name}.scss`;
> },
> resolveComponent: (name) => {
> return `element-plus/lib/${name}`;
> },
> }]
> }),

This works!!!
Thanks♪(･ω･)ﾉ

**Comment by qdleader** [comment]
do this:
yarn add sass -D
yarn add vite-plugin-style-import -D

vite：
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import path from 'path'
import styleImport from 'vite-plugin-style-import'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        vue(),
        styleImport({
            libs: [{
                libraryName: 'element-plus',
                esModule: true,
                ensureStyleFile: true,
                resolveStyle: (name) => {
                name = name.slice(3)
                return `element-plus/packages/theme-chalk/src/${name}.scss`;
            },
            resolveComponent: (name) => {
                return `element-plus/lib/${name}`;
            },
            }]
        }),
    ],
  
})

不管用。。。
