### ISSUE TITLE
[Feature Request] Radio-button (and radio inside a group) needs a clear visual style for focus state

### ISSUE THREAD

**Issue by Owen-Tsai** [element-plus/element-plus#2438]
### Existing Component
Yes

### Component Name
el-radio

### Description
好巧不巧，我有一天鼠标坏了，用键盘上了半天班：

When navigating through the keyboard without the mouse or touchpad, `radio-button`s inside a group can be hard to select since there is no visual style to indicate the focus point unless users check one button first and then navigate using arrow keys. 

Same issues when using normal radio components within a group.

IMO there should be a clear focus style, or just activate the first button(option) when the `radio-group` gains focus.

**Comment by JeremyWuuuuu** [comment]
True, we can only implement this util our design resources got free.

**Comment by Giwayume** [comment]
@Owen-Tsai Check the latest release

**Comment by xiaoxian521** [comment]
The latest version has been implemented
