### ISSUE TITLE
[Bug Report] ctx.expose error happenned which  is not a function on prod 

### ISSUE THREAD

**Issue by Sefrid** [element-plus/element-plus#2440]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
windows 10 / chrome 91

### Vue version
3.1.4

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/date-picker/src/date-picker.ts

### Steps to reproduce
element-plus latest	environment
vue 3.1.1
prod environment display typeError: t.expose is not a function

### What is Expected?
none

### What is actually happening?
none

**Comment by JeremyWuuuuu** [comment]
What version of Vue are you using? Vue added this API after 3.0.9 or 3.0.10 can't remember, if you upgrade to `3.1.x` you will have no issue on this.

To get your version of vue:

at your project root
```shell
$ cat node_modules/vue/package.json | grep version
```
or in your applications:

```ts
import { version } from 'vue'

console.log(version)
```

**Comment by Sefrid** [comment]
thanks very much。
because of referring vue through CDN。 so it's version stays on 3.0.0.
