### ISSUE TITLE
[Feature Request] No way to set navbar logo

### ISSUE THREAD

**Issue by Fanna1119** [element-plus/element-plus#2445]
### Existing Component
Yes

### Component Name
https://element-plus.org/#/en-US/component/menu

### Description
There is navbar slot || prop || way to set a navbar logo that aligns in properly

**Comment by msidolphin** [comment]
You can write your logo like this: 
```html
<header>
    <div class="logo"></div>
    <menu />
</header>
```

```html
<aside>
    <div class="logo"></div>
    <menu />
</aside>
```

**Comment by xiaoxian521** [comment]
Almost all mainstream component libraries are like this, please add them if necessary
