### ISSUE TITLE
[bug report] import {elbutton, locale} from 'element plus' import Lang from' element plus / lib / locale / Lang / zh CN 'exception in production mode after packaging

### ISSUE THREAD

**Issue by lihaopeng1024** [element-plus/element-plus#2446]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
google 89

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr1

### Steps to reproduce
import { createApp } from 'vue'
import {ElTable, ElTableColumn,ElDatePicker,ElLoading,ElCarousel,ElCarouselItem,ElDialog,locale } from 'element-plus'
import lang from 'element-plus/lib/locale/lang/zh-cn'
import 'dayjs/locale/zh-cn'

locale(lang)
createApp(App).component(ElButton.name, ElButton)

### What is Expected?
Normal in development mode
Error in production mode after packaging
 Tips “locale(lang)”  It's not a function

### What is actually happening?
Normal in development mode
Error in production mode after packaging
 Tips “locale(lang)”  It's not a function

**Comment by sxzz** [comment]
Please use `config-provider` for now.
