### ISSUE TITLE
Integrate `InputNumber` with `Slider`

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#245]
Currently `InputNumber` is in development, so the `InputNumber` featured `Slider` has no been implemented yet, this feature should be integrated right after `InputNumber` gets merged

**Comment by JeremyWuuuuu** [comment]
Assigning this to @Ryan2128 , since he is the owner of `Slider`

**Comment by Ryan2128** [comment]
👌  😁

**Comment by zazzaz** [comment]
@Ryan2128 `input-number` is avaliable
