### ISSUE TITLE
[Bug Report] style is not load in documents

### ISSUE THREAD

**Issue by NWYLZW** [element-plus/element-plus#2455]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
Windows 10/Chrome 91

### Vue version
3.1.4

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973

### Steps to reproduce
当我在 docs 中的 :::demo::: 中的 ```html``` 使用 style 标签的时候，样式不会被加载到开发环境

### What is Expected?
我希望样式作用于标签上

### What is actually happening?
样式并没有作用于标签

**Comment by NWYLZW** [comment]
我指的就是主仓库的 docs 文件中的内容
docs 中给样例设置 style，不会被启用
这个不需要可复现的实例，直接是仓库的问题
我是在编写 element 文档时发现的

**Comment by iamkun** [comment]
The demo style is located here for easy management.

https://github.com/element-plus/element-plus/tree/dev/website/demo-styles

**Comment by NWYLZW** [comment]
> The demo style is located here for easy management.
> 
> https://github.com/element-plus/element-plus/tree/dev/website/demo-styles

thx

**Comment by NWYLZW** [comment]
![image](https://user-images.githubusercontent.com/51358815/124799655-600d5e80-df87-11eb-8b89-39d6386754ea.png)
So won't it be rendered to code example like this?
![image](https://user-images.githubusercontent.com/51358815/124799932-a82c8100-df87-11eb-8c47-65b44eed398e.png)

**Comment by iamkun** [comment]
Yes, the style in the markdown file is for code demo ONLY. 

There for, you should add both to md file and website/demo-styles folder

**Comment by NWYLZW** [comment]
> Yes, the style in the markdown file is for code demo ONLY.
> 
> There for, you should add both to md file and website/demo-styles folder
Ok, thanks for your reply and I know

**Comment by NWYLZW** [comment]
emmmm, I think the style of the demo should be shown in code example.
