### ISSUE TITLE
The calendar component does not take effect during the internationalization of [bug report]

### ISSUE THREAD

**Issue by janeyhjy** [element-plus/element-plus#2470]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
chrome 91.0.4472.101

### Vue version
3.0.7

### Reproduction Link
https://codesandbox.io/s/dreamy-morse-9hq49?file=/src/App.vue

### Steps to reproduce
打开网页就可见

### What is Expected?
日期全部显示为中文

### What is actually happening?
只有年月显示为中文，星期还是显示英文

**Comment by sxzz** [comment]
Please try
```
// add to main.js
import "dayjs/locale/zh-cn";
```
