### ISSUE TITLE
[Bug Report] El table column height calculation error

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#2471]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
windows/Chrome 89

### Vue version
3.1.4

### Reproduction Link
https://jsfiddle.net/angtme1o/1/

### Steps to reproduce
1. Apply El table
2. Dynamically generate columns (delay getting columns data)
3. Set a fixed: true column

### What is Expected?
Set the column of fixed property, height calculation error

### What is actually happening?
repair

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/125589003-716d26ae-fb60-4c61-a53c-204b674d2021.png)

seems no problem

**Comment by SmallSample** [comment]
https://codepen.io/smallsample/pen/VwbPdyY

**Comment by msidolphin** [comment]
> https://codepen.io/smallsample/pen/VwbPdyY

Cannot reproduce, can you provide more details?

**Comment by SmallSample** [comment]
![image](https://user-images.githubusercontent.com/34450888/125746540-5a45d942-1986-4a90-8a39-1d1f7edd0584.png)
dislocation

**Comment by msidolphin** [comment]
Can you try calling the doLayout method?

**Comment by SmallSample** [comment]
@msidolphin Thank you. It's settled
