### ISSUE TITLE
[bug report] cascade selector layout problem

### ISSUE THREAD

**Issue by flmbbb** [element-plus/element-plus#2472]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
chrome

### Vue version
3.1.4

### Reproduction Link
https://github.com/flmbbb/OneEasyAdmin

### Steps to reproduce
<el-form-item label="结构代码">
        <el-input v-model="FEditCompany.FCompanyName"></el-input>
      </el-form-item>
      <el-form-item label="上级结构">
        <el-cascader
          v-model="FEditCompany.tempPCompanyID"
          :options="FElmDataTree"
          :props="{ checkStrictly: true }"
          filterable
          clearable
          placeholder="单击选择"
          size="medium"
        ></el-cascader>
      </el-form-item>
联级表单是没对齐的,和其它控件比不会自动适应,请参考链接的图片

### What is Expected?
http://edu.callbaba.cn:8000/myWeb/123.png

### What is actually happening?
http://edu.callbaba.cn:8000/myWeb/123.png

**Comment by kooriookami** [comment]
Yes, it has a default width, the same as select.

**Comment by flmbbb** [comment]
size="medium" 去掉也没用。不会自动适应，倒至和其它input控件的排版不一样.

**Comment by flmbbb** [comment]
> Yes, it has a default width, the same as select.

size="medium" 去掉也没用。不会自动适应，倒至和其它input控件的排版不一样.

**Comment by flmbbb** [comment]
.el-form-item .el-cascader {
  width: 100%;
}
我现在采用此方法，在form-item下面 width100%让他撑满

**Comment by flmbbb** [comment]
.el-form-item .el-cascader {
  width: 100%;
}
我现在采用此方法，在form-item下面 width100%让他撑满
