### ISSUE TITLE
[bug report] I18N internationalization does not take effect when components are introduced into the page on demand

### ISSUE THREAD

**Issue by callmesoul** [element-plus/element-plus#2473]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
chrome

### Vue version
3.1.4

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
1.根据文档设置i18n
2.组件不在man全局引入
3.在使用的页面引入组件

### What is Expected?
组件i18生效，样式也没问题

### What is actually happening?
组件i18n不能效，但引入lib路径下就生效，但是样式没有引入

**Comment by sxzz** [comment]
Please provide a reproduction link, and reopen this issue.
