### ISSUE TITLE
[Bug Report] Use Vite2.0 and vite-plugin-style-import to dynamic import ElDatePicker， lang use 'zh-cn', but words in popup is still en

### ISSUE THREAD

**Issue by caibirdkhtd** [element-plus/element-plus#2476]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
Window10/Chrome  91.0.4472.114

### Vue version
3.1.1

### Reproduction Link
https://github.com/caibirdkhtd/vite-vue3-element

### Steps to reproduce
use element-plus and vite2.0 by https://element-plus.org/#/zh-CN/component/quickstart  and set lang to 'zh-cn' by following:

import 'dayjs/locale/zh-cn'
import locale from 'element-plus/lib/locale/index.js'
import lang from 'element-plus/lib/locale/lang/zh-cn'
locale.use(lang)

### What is Expected?
date picker after popup display like this:  ‘一， 二， 三， 四， 五， 六， 日’ 
![image](https://user-images.githubusercontent.com/14315052/124920904-686aa580-e02a-11eb-93a3-70ad79aa37b5.png)

### What is actually happening?
date picker after popup display like this:  ‘Sun，Mon， Tue， Wed， Thu， Fri， Sat’
![image](https://user-images.githubusercontent.com/14315052/124920863-5e48a700-e02a-11eb-8b6f-accfbaaa6821.png)

**Comment by jackyzz123** [comment]
same problem

**Comment by tolking** [comment]
maybe same problem. link #2201

**Comment by hearsay316** [comment]
不知道怎么搞得这个locale 在开发和打包以后不一样 , 建议用  typeof locale === 'function' ? locale(lang) : locale.use(lang);来避免这个样的错误.

**Comment by xieanwen** [comment]
现在怎么处理这个啊！

**Comment by tolking** [comment]
@xieanwen 目前修改了使用国际化的方式，参考[文档](https://element-plus.gitee.io/#/zh-CN/component/i18n)

**Comment by xiaoxian521** [comment]
Example reference：https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/plugins/i18n/config.ts#L7
