### ISSUE TITLE
[Bug Report] Form does not take effect when label-width prop is auto

### ISSUE THREAD

**Issue by qige2016** [element-plus/element-plus#2479]
Element Plus version
1.0.2-beta.54

OS/Browsers version
Window10/Chrome 91.0.4472.124

Vue version
3.1.4

Reproduction Link
https://codepen.io/qige/pen/YzVWvyN

Steps to reproduce
Set label-width to auto

What is Expected?
Label-width calculation is right

What is actually happening?
Label-width calculation is no effect

**Comment by sriramNV** [comment]
try this -> "https://github.com/element-plus/element-plus/pull/830"
