### ISSUE TITLE
[Bug Report]  Uncaught (in promise) TypeError: Cannot read property 'appContext' of null

### ISSUE THREAD

**Issue by jok311** [element-plus/element-plus#2481]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
mac

### Vue version
3.1.4

### Reproduction Link
https://github.com/

### Steps to reproduce
Uncaught (in promise) TypeError: Cannot read property 'appContext' of null

1.0.2-beta.54 版本报这个错

### What is Expected?
不报错

### What is actually happening?
不报错

**Comment by sxzz** [comment]
Please provide a reproduction link to help us get more detailed information, and reopen this issue.
