### ISSUE TITLE
[el-cascader] support LowerCase and UpperCase Letters filtring

### ISSUE THREAD

**Issue by gonmedtara** [element-plus/element-plus#2483]
Con you change this function to support Lower and UpperCase Letters ? thanks
 Example : `node.text.toUpperCase().includes(keyword.toUpperCase())`
https://github.com/element-plus/element-plus/blob/e96dc8ac65d4c3ec2e4d7c295014e930d138e24d/packages/cascader/src/index.vue#L216

**Comment by YangYmimi** [comment]
@gonmedtara Hi，this function is default. you can set by yourself logic ( https://element-plus.gitee.io/#/zh-CN/component/cascader#cascader-attributes ). default is exact match.

**Comment by msidolphin** [comment]
You can use filter-method customize your search logic. as @YangYmimi said.
