### ISSUE TITLE
[Feature Request] There is no feature for year range selector. please add year range picker feature

### ISSUE THREAD

**Issue by suman111sanjel** [element-plus/element-plus#2487]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
Invalid prop: custom validator check failed for prop "type". 

    <el-date-picker
      v-model="value1"
      size="mini"
      type="yearrange"
      range-separator="To"
      start-placeholder="Start month"
      end-placeholder="End month">
    </el-date-picker>

 type="yearrange" doesn't works

**Comment by JeremyWuuuuu** [comment]
sounds like a relatively good feature cc @0song can you take a look on this?

**Comment by TothingWay** [comment]
I am also looking forward to adding this feature. Is it in the plan now?

**Comment by emojiiii** [comment]
i'm sorry. There is no such plan in the RoadMap. If you are interested, you are welcome to contribute

**Comment by TothingWay** [comment]
Ok, I will make time to complete this feature

**Comment by CherishTheYouth** [comment]
I have seen several issues about the feature request of add yearrange, but it have not been implemented now, so what is the current progress?

**Comment by WestFarmer** [comment]
搞开源都是一时激情，激情过后就淡了。
加上中国人都生存压力居大。
理解万岁！
