### ISSUE TITLE
< El form item > component will cause elementpluserror: [util] binding value must be a string or number warning message

### ISSUE THREAD

**Issue by LBJDJW** [element-plus/element-plus#2490]
报错信息：
index.esm.js:1 ElementPlusError: [Util] binding value must be a string or number
    at $e (http://localhost:3000/node_modules/.vite/element-plus.js?v=80b63977:6653:16)
    at nt (http://localhost:3000/node_modules/.vite/element-plus.js?v=80b63977:6720:42)
    at http://localhost:3000/node_modules/.vite/element-plus.js?v=80b63977:10154:15
    at ComputedRefImpl.reactiveEffect [as effect] (http://localhost:3000/node_modules/.vite/chunk-JQQLQ4Z6.js?v=80b63977:294:16)
    at ComputedRefImpl.get value [as value] (http://localhost:3000/node_modules/.vite/chunk-JQQLQ4Z6.js?v=80b63977:1017:27)
    at unref (http://localhost:3000/node_modules/.vite/chunk-JQQLQ4Z6.js?v=80b63977:938:29)
    at Object.get (http://localhost:3000/node_modules/.vite/chunk-JQQLQ4Z6.js?v=80b63977:941:35)
    at Object.get (http://localhost:3000/node_modules/.vite/chunk-AUWRX4RC.js?v=80b63977:5173:26)
    at Proxy.os.render (http://localhost:3000/node_modules/.vite/element-plus.js?v=80b63977:10226:125)
    at renderComponentRoot (http://localhost:3000/node_modules/.vite/chunk-AUWRX4RC.js?v=80b63977:910:39)
$e @ index.esm.js:1
nt @ index.esm.js:1
(anonymous) @ index.esm.js:1
reactiveEffect @ reactivity.esm-bundler.js:42
get value @ reactivity.esm-bundler.js:877
unref @ reactivity.esm-bundler.js:791
get @ reactivity.esm-bundler.js:793
get @ runtime-core.esm-bundler.js:6820
os.render @ index.esm.js:1
renderComponentRoot @ runtime-core.esm-bundler.js:1167
componentEffect @ runtime-core.esm-bundler.js:5220
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:5173
mountComponent @ runtime-core.esm-bundler.js:5132
processComponent @ runtime-core.esm-bundler.js:5090
patch @ runtime-core.esm-bundler.js:4684
patchKeyedChildren @ runtime-core.esm-bundler.js:5574
patchChildren @ runtime-core.esm-bundler.js:5376
processFragment @ runtime-core.esm-bundler.js:5079
patch @ runtime-core.esm-bundler.js:4677
patchKeyedChildren @ runtime-core.esm-bundler.js:5433
patchChildren @ runtime-core.esm-bundler.js:5376
patchElement @ runtime-core.esm-bundler.js:4967
processElement @ runtime-core.esm-bundler.js:4776
patch @ runtime-core.esm-bundler.js:4681
componentEffect @ runtime-core.esm-bundler.js:5293
reactiveEffect @ reactivity.esm-bundler.js:42
updateComponent @ runtime-core.esm-bundler.js:5161
processComponent @ runtime-core.esm-bundler.js:5094
patch @ runtime-core.esm-bundler.js:4684
patchKeyedChildren @ runtime-core.esm-bundler.js:5433
patchChildren @ runtime-core.esm-bundler.js:5376
patchElement @ runtime-core.esm-bundler.js:4967
processElement @ runtime-core.esm-bundler.js:4776
patch @ runtime-core.esm-bundler.js:4681
componentEffect @ runtime-core.esm-bundler.js:5293
reactiveEffect @ reactivity.esm-bundler.js:42
(anonymous) @ runtime-core.esm-bundler.js:494
rerender @ runtime-core.esm-bundler.js:487
(anonymous) @ runtime-core.esm-bundler.js:545
(anonymous) @ index.vue:54
(anonymous) @ client.ts:422
(anonymous) @ client.ts:344
(anonymous) @ client.ts:205
queueUpdate @ client.ts:205
async function (async)
queueUpdate @ client.ts:200
(anonymous) @ client.ts:71
handleMessage @ client.ts:69
(anonymous) @ client.ts:43
Show 16 more frames

**Comment by equt** [comment]
This bug is caused by https://github.com/element-plus/element-plus/pull/2396#discussion_r667283699.

**Comment by LBJDJW** [comment]
> This bug is caused by [#2396 (comment)](https://github.com/element-plus/element-plus/pull/2396#discussion_r667283699).

thank you!

**Comment by xinzi1990** [comment]
Why label-width has become a required item？

**Comment by equt** [comment]
@xiaoeyuZZZ This issue has been fixed and will be available in the next beta release.

**Comment by kooriookami** [comment]
> Why label-width has become a required item？

It's not must required, fixed in next version.
