### ISSUE TITLE
[feature request] select component (elselect). If it is set to remote = true and filterable = false, can it call remote method to get data immediately when it clicks the drop-down box?

### ISSUE THREAD

**Issue by gowiny** [element-plus/element-plus#2496]
### Existing Component
Yes

### Component Name
ElSelect

### Description
Select组件(ElSelect)，如果把设置为remote=true，filterable=false的时候，可否让它点击下拉框的时候就立即调用remote-method获取数据？
现在好像只能通过@visible-change	 事件中去判断是否有加载数据，如果没有加载，则加载一次，这样感觉比较麻烦。
这个需求应该是普遍常用的把。

**Comment by msidolphin** [comment]
Remote search mode must enable filterable and remote, there is something wrong with your usage.
