### ISSUE TITLE
The click event in El Popper conflicts with the click event in El cascade

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#2500]
![popover](https://user-images.githubusercontent.com/60815493/125256685-41b0b580-e32f-11eb-9b13-e1a5fd90c6ea.png)

<script src="//unpkg.com/vue@next"></script>
<script src="//unpkg.com/element-plus/lib/index.full.js"></script>
<div id="app">
<el-popover
  placement="right"
  :width="400"
  trigger="click"
>
  <template #reference>
    <el-button>click 激活</el-button>
  </template>
<el-cascader :options="options" :show-all-levels="false"></el-cascader>
</el-popover>
</div>

@import url("//unpkg.com/element-plus/lib/theme-chalk/index.css");

var Main = {
    data() {
      return {
       options: [
                {
                  label: '青岛',
                  value: 0,
                  children: [
                    {
                      value: '0-1',
                      label: '李沧'
                    },
                    {
                      value: '0-2',
                      label: '崂山'
                    }
                  ]
                },
                {
                  label: '济南',
                  value: 1,
                  children: [
                    {
                      value: '1-1',
                      label: '长青'
                    },
                    {
                      value: '1-2',
                      label: '章丘'
                    }
                  ]
                }
              ]
      };
    }
  };
;const app = Vue.createApp(Main);
app.use(ElementPlus);
app.mount("#app")

**Comment by PeyFon** [comment]
https://codepen.io/peyfon/pen/QWvGXKY

**Comment by JeremyWuuuuu** [comment]
apply `:popper-append-to-body="false"` for el-cascader or for el-popover you should have this.

**Comment by PeyFon** [comment]
> apply `:popper-append-to-body="false"` for el-cascader or for el-popover you should have this.

I don't see this attribute on the official website，Is it to be added in the next version？

**Comment by msidolphin** [comment]
> Is

Yeah, we plan to provide `popperOptions` to configure popper features. but it is not guaranteed to be available in the next version
