### ISSUE TITLE
If label width is not filled in the form El form item, there will be a warning

### ISSUE THREAD

**Issue by distant-xingsu** [element-plus/element-plus#2501]
表单el-form-item 不填label-width会有警告，
el-form填写完label-width=“0”时候，按理说el-form-item 不应该在提示警告，文档中写道‘（表单域标签的宽度，例如 '50px'。作为 Form 直接子元素的 form-item 会继承该值。支持 auto。）’

**Comment by kooriookami** [comment]
Fixed in next version.
