### ISSUE TITLE
[Bug Report] submenu content will go beyond the window area without scroll bar

### ISSUE THREAD

**Issue by qianxunlly** [element-plus/element-plus#2503]
### Existing Component
Yes

### Component Name
NavMenu

### Description
Submenu内容会超出窗口区域而不出现滚动条

![示例图片](https://github.com/qianxunlly/image/blob/main/20210712205501.jpg?raw=true)

**Comment by qianxunlly** [comment]
由于我们并不能获取到组件的top的值，因此下图中的height是无法被计算的。

![](https://github.com/qianxunlly/image/blob/main/66B2A4C5-5777-488D-A671-6917340D55EC.png?raw=true)

**Comment by qianxunlly** [comment]
直接用你们的示例就行：https://element-plus.gitee.io/#/zh-CN/component/menu#zhe-die 
把浏览器窗口调小看就知道了～

**Comment by msidolphin** [comment]
You can force the Menu height yourself, but don't forget to set popper-append-to-body

![image](https://user-images.githubusercontent.com/26672484/125418325-4e0d8e4e-c873-48b3-b62b-016c29e2de9b.png)

```vue
<el-submenu index="1-4" popper-append-to-body>
    <template #title>选项4</template>
    <el-menu-item index="1-4-1">选项1</el-menu-item>
  </el-submenu>
```

**Comment by qianxunlly** [comment]
我知道可以，正如上面我放的那个代码大图的红色箭头。
问题是我获取不到组件内联的top/bottom值，因此无法反算正确的style高度～。能获取到就行了。

**Comment by msidolphin** [comment]
> 我知道可以，正如上面我放的那个代码大图的红色箭头。
> 问题是我获取不到组件内联的top/bottom值，因此无法反算正确的高度，比如，max-height: calc(100% - ${top}px)。

为什么最大高度需要动态计算呢？

**Comment by JeremyWuuuuu** [comment]
Simply left out some space then calculate it with the `window.clientHeight` you could get the correct height I suppose.

**Comment by qianxunlly** [comment]
> Simply left out some space then calculate it with the `window.clientHeight` you could get the correct height I suppose.

Yes, this way could work. Thank you for your time.
