### ISSUE TITLE
[Bug Report] Select filterable: labels of empty option groups should be filtered out

### ISSUE THREAD

**Issue by maelga** [element-plus/element-plus#2506]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows 10 / Edge Version 91.0.864.67

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/maelga/pen/dyWOZRV

### Steps to reproduce
See codepen, using a filterable select with options grouping.
Try this: type "sh" in the filterable select will return 'Shanghai' and 'Shenzhen'.
However, option group labels with no options (i.e. "Australia", "Indonesia", "India") should not show.

### What is Expected?
When using filterable, the label of empty option groups should not show if no options are available. There is no benefits for users to see labels (e.g. country names in this codepen example) when no options (e.g. cities) can be selected. The select should show only option group labels (e.g. country names) if options are available (e.g. cities).

### What is actually happening?
Labels of empty option groups are currently displayed even if there are no options displayed for the user to select.

**Comment by XingXiaoWu** [comment]
https://github.com/element-plus/element-plus/blob/0074f334fe5dcb7921260d5b3f722f305b20b0fd/packages/select/src/option-group.vue#L38-L43
I think it has something to do with this code

In group code, the `select?.optionsArray?` is a flat array. Don't include group information.
On the other hand,  when filter options is no trigger `selectEvents.groupQueryChange`

**Comment by binvb** [comment]
i'm late, haha, but maybe better
```
    const queryChange = () => {
      let ownChildren = select?.optionsArray?.filter(element => element.$parent.label === props.label)
      
      visible.value = ownChildren.some(option => option.visible === true)
    }
```
