### ISSUE TITLE
[Bug Report] [el-date-picker]When value format = x, the component cannot display the time

### ISSUE THREAD

**Issue by D1N910** [element-plus/element-plus#2513]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Mac OS

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/d1n910/pen/abWBgrw

### Steps to reproduce
(1) Choose the time
(2) And then I found that I couldn't show it

### What is Expected?
Show selected time

### What is actually happening?
No show

**Comment by msidolphin** [comment]
dayjs dependency problem

**Comment by binvb** [comment]
> dayjs dependency problem

seem's like dayjs' s problem: https://github.com/iamkun/dayjs/issues/1569

**Comment by sxzz** [comment]
It seems that the problem has been fixed. https://github.com/iamkun/dayjs/issues/1569#issuecomment-916770395
