### ISSUE TITLE
[Bug Report] Invalid use of line-height in Form label

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#2516]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows 10 / Chrome (latest)

### Vue version
3.1.4

### Reproduction Link
https://jsfiddle.net/oev0fnjb/2/

### Steps to reproduce
Form label is styled by line-height which leads to weird spacing when the label is multiple lines long.

### What is Expected?
Use normal padding/margin to position the text

### What is actually happening?
long spacing between words

**Comment by JeremyWuuuuu** [comment]
Because we've adapted `flex` for our `Form` component so that you can see the label and the form item is not aligned "properly", we could provide an API for form item that allows user to set the alignment. cc @kooriookami  @msidolphin

**Comment by JeremyWuuuuu** [comment]
Whoops, I think I misunderstood your request. Can we find a way to control that? @kooriookami

**Comment by JeremyWuuuuu** [comment]
Also I'd like to add here: ElementPlus is inherited from the original design language, I would suggest you to use another approach to solve your issue which is you can shorten your label put the full description into tooltip content so that your UI would look "better(IMHO)".

**Comment by JeremyWuuuuu** [comment]
If you think otherwise, you will have to override the style rule on your own, WDYT?

**Comment by plehnen** [comment]
I agree there are possible workarounds (tooltip, globally overwrite style with `!important`, using `<template #label><div>` with custom stylesheets). But I believe `line-height` is not suitable for vertical positioning of text, as it will behave weirdly when the text is multiline (which can easily happen in responsive websites for smaller resolutions, and sometimes is intentional for long components like textareas).

**Comment by sxzz** [comment]
This issue is obsolete. Please create a new issue if you have a related question.
