### ISSUE TITLE
[Bug Report] Component <el-date-picker> can not use prop 'model-value' and '@change' to replace 'v-model'

### ISSUE THREAD

**Issue by web-zhangbo** [element-plus/element-plus#2537]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
chrome 91

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/web-zhangbo/pen/wvdJGOq

### Steps to reproduce
on DateTimePicker component
replace 'v-model="val "' to ':model-value="val"' and '@change="changeVal"'
```

let val = ''
const = changeVal = v => val = v
```
check it
not work!!!

### What is Expected?
val is changed

### What is actually happening?
val not change
and function changeVal don't work

**Comment by ioslh** [comment]
`model-value` and `@change` combination is not replacement for `v-model` in Vue 3, Refer to [breaking change](https://v3.vuejs.org/guide/migration/v-model.html#overview)

**Comment by kooriookami** [comment]
Use `@update:model-value="valueChange"` will be OK.
