### ISSUE TITLE
[Bug Report] Component <el-date-picker> can not use prop 'model-value' and '@change' to replace 'v-model'

### ISSUE THREAD

**Issue by web-zhangbo** [element-plus/element-plus#2538]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
chrome 91

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/web-zhangbo/pen/wvdJGOq

### Steps to reproduce
在el-date-picker组件上把 v-model指令替换为model-value绑定值 和 change事件
用选择器选择一个日期

### What is Expected?
绑定值改变

### What is actually happening?
绑定值伪变化，且change事件的处理函数未执行

**Comment by binvb** [comment]
here is sourcecode: 
```
emits: ['update:modelValue'],
```
you should used like this： 
```
@update:model-value
```

**Comment by web-zhangbo** [comment]
> 这里是源代码：
> 
> ```
> emits: ['update:modelValue'],
> ```
> 
> 你应该这样使用：
> 
> ```
> @update:model-value
> ```
