### ISSUE TITLE
[bug report] table causes page memory leak

### ISSUE THREAD

**Issue by 1910563900** [element-plus/element-plus#2541]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
chorme

### Vue version
3.1.4

### Reproduction Link
https://codesandbox.io/s/fragrant-waterfall-o77co?file=/src/App.vue

### Steps to reproduce
当Table表格组件列的宽度为自动撑开时，同时设置了column的fixed值，那么表格在Aside伸缩时Table的列伸缩会引起页面卡顿

### What is Expected?
预期流程自动伸缩

### What is actually happening?
卡顿

**Comment by binvb** [comment]
我试了下没看到有内存泄漏。卡顿一般是复杂计算阻塞导致的，如果有内存泄漏可以给个内存监控截图看下。

**Comment by 1910563900** [comment]
应该就是复杂计算导致的卡顿，示例上可以看到

**Comment by kooriookami** [comment]
Table 组件近期会重构，暂时关闭这个 issue 了。
