### ISSUE TITLE
[bug report] when the El table row is expanded, when the data of the El table row is changed in the expanded row, all expanded rows will be closed

### ISSUE THREAD

**Issue by shaolongwendd01** [element-plus/element-plus#2542]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
mac 11.2.3 / chrome 91.0.4472.114（正式版本)

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/shaolongwen/pen/mdmWRzp

### Steps to reproduce
展开某行，点击添加价格

### What is Expected?
el-table 展示最新的价格数据，并且不关闭当前所有展开的行

### What is actually happening?
关闭当前展开的所有行，不仅仅是当前行

**Comment by msidolphin** [comment]
Please use rowKey to solve this problem
