### ISSUE TITLE
[Feature Request] Ability to hide the horizontal/vertical line of Navigation Menu

### ISSUE THREAD

**Issue by JakeMa2017** [element-plus/element-plus#2546]
### Existing Component
Yes

### Component Name
NavMenu https://element-plus.org/#/en-US/component/menu

### Description
Correct me if I'm wrong, that for default color navigation menu, I don't find a way to hide the gray line on the bottom for horizontal or the line on the right for vertical. It would be great if it has an attribute for <el-menu> to show/hide it.

**Comment by binvb** [comment]
这种不太适合加变量控制，要加的话太多了，建议可以用样式覆盖掉element的样式了

**Comment by kooriookami** [comment]
You can try to cover these styles.
![image](https://user-images.githubusercontent.com/38392315/125887550-c4da9de6-e39a-4376-a962-e29237a5ce0d.png)
