### ISSUE TITLE
Does the filter function of the [feature request] Table add input and date period selection

### ISSUE THREAD

**Issue by f81883387** [element-plus/element-plus#2551]
### Existing Component
Yes

### Component Name
table

### Description
都是国人我就不写英文了，
在大部分开发系时，单单的filter多选已经满足不了需求了~
比如要在过滤文章列表时，需要过滤带有特殊字符的标题、又或者过滤一个时间段内的文章
希望可以在过滤上增加 输入 和 日期时间选择

**Comment by binvb** [comment]
都是国人我也不跟你客气了，😄。这个需求相当于要form和table结合了，这是重型组件(反正有这么叫的)的范畴。阿里有一个pro-component的重型组件框架，可以试下，不过是react版本的，vue版本写的好像不怎么样

**Comment by kooriookami** [comment]
复杂的筛选可以使用 `form` 组件，或者传参让后台返回筛选后的数据。
