### ISSUE TITLE
[bug report] bug of El pagination component

### ISSUE THREAD

**Issue by huzhanlin** [element-plus/element-plus#2554]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
google/版本 91.0.4472.124（正式版本） （64 位）

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/huzhanlin/pen/jOmBjJd

### Steps to reproduce
页面初始化之后，点击页码的10，然后重新选择条目数为50，执行结果和element-ui的组件不一致。（为什么要点击页码的10，原因是条目数改变，而分页页码被动改变）

页面10的事件它先获得结果为 ： 20 10 "page"
条目数为50的事件为： 50 1 "size" and 50 4 "page" (这个事件执行了一次handleSizeChange 和一次 handleCurrentChange)
并且页码的激活数为4
我明白的给this.pageData.page赋值为1...但激活数为4

### What is Expected?
期待element-plus 和 element-ui 的 el-pagination组件 一致

### What is actually happening?
页面初始化之后，点击页码的10，然后重新选择条目数为50，执行结果和element-ui的组件不一致。

页面10的事件它先获得结果为 ： 20 10 "page"
条目数为50的事件为： 50 1 "size" and 50 4 "page" (这个事件执行了一次handleSizeChange 和一次 handleCurrentChange)
并且页码的激活数为4
我明白的给this.pageData.page赋值为1...但激活数为4

（在条目数改变的时候，页码数被动改变的时候）这个结果会导致，向后端发起了两次请求

**Comment by ioslh** [comment]
Looks same issue with #2395
