### ISSUE TITLE
[Bug Report] could not unselect first tag when there are two tags that are created by Enter with "allow-create" property, by typing Enter

### ISSUE THREAD

**Issue by CoderMonkie** [element-plus/element-plus#2562]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows10 / Chrome 91.0.4472.124

### Vue version
3.2.0-beta.1

### Reproduction Link
https://codepen.io/codermonkie/pen/wvdegVy

### Steps to reproduce
component:  select
use property of “allow-create”

1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => "TS" tag disappeared, now showing "JS" tag
4. type "JS" and Enter => "TS" tag appeared, now showing "JS TS"

### What is Expected?
1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => "JS" tag disappeared, show "TS" tag only
4. type "JS" and Enter => "JS" tag appeared, now showing "TS JS"

### What is actually happening?
1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => [BUG] "TS" tag disappeared, now showing "JS" tag
4. type "JS" and Enter => [BUG] "TS" tag appeared, now showing "JS TS"

and it seems "default-first-option" also doesn't work correctly (or am I miss-understanding..)

![select-allow-create.gif](https://z3.ax1x.com/2021/07/19/W87vyn.gif)

**Comment by JeremyWuuuuu** [comment]
This might be a potentially long existing bug, would you like to fix this in this repo?
