### ISSUE TITLE
[Bug Report] the dynamic form rules within popover does not work

### ISSUE THREAD

**Issue by norangit** [element-plus/element-plus#2566]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
chrome 75

### Vue version
3.1.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-4fozr?file=/src/App.vue

### Steps to reproduce
step 1: click li, then popover is shown
step 2: add new form item
step 3: do submit
step 4: there is no any error rule

### What is Expected?
there should be error rule infos

### What is actually happening?
nothing

**Comment by kooriookami** [comment]
Please check the code before submitting an issue. `prop` and `rules` should be added to `el-form-item`.
![image](https://user-images.githubusercontent.com/38392315/126727969-8d02750f-c42e-4345-b6c1-3c7b9d489dd2.png)

**Comment by norangit** [comment]
thanks very much, my mistake. but there is still a problem, e.g: the form items added newly after 'New' clicked, validation wont work properly before click li to reopen popover,
step1: click li to open popover
step2: click save without do nothing, validation just work fine
step3: click outside of popover to close, then redo step1
step4: now, click 'New' to add one or more form items, then click 'Save'
step5: the new form item were validated by checking the console, but there is no error styles on UI, pls see the screenshot below
![图片](https://user-images.githubusercontent.com/24283475/126738976-59a65fd7-0c9e-4a39-ba58-e7272a7ab406.png)
step6: close and reopen popover then validation works fine again

what did I miss?
thanks very much

**Comment by norangit** [comment]
@kooriookami 
could you help me? thanks very much.

**Comment by norangit** [comment]
@JeremyWuuuuu colud you help to check what is wrong? Is it a bug?
https://codesandbox.io/s/element-plus-spa-forked-4fozr?file=/src/App.vue
