### ISSUE TITLE
[Bug Report] datepicker: id prop not passed to input

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#2576]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows 10 / Chrome (latest)

### Vue version
3.2.0-beta.1

### Reproduction Link
https://jsfiddle.net/gvno4bqt/3/

### Steps to reproduce
For accessibility reasons it is required to have a label associated with an input field. (see https://github.com/maranran/eslint-plugin-vue-a11y/blob/master/docs/rules/label-has-for.md)

An `id` prop added to `<el-date-picker>` will not be passed to the `<input>`

### What is Expected?
id prop should be added to the internal input field

### What is actually happening?
id is discarded

**Comment by Giwayume** [comment]
@emojiiii This was fixed in #7450
