### ISSUE TITLE
Element plus swtich bug.. @ change is automatically triggered

### ISSUE THREAD

**Issue by rzg813** [element-plus/element-plus#2591]

**Comment by JeremyWuuuuu** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by JeremyWuuuuu** [comment]
If you cannot provide a valid reproducible demo to us, we are not able to help you with anything. Feel free to reopen this after you have a valid demo. :)

如果没有一个可以复现的代码我们确实没办法靠脑补帮到您，请给我们提供一个可复现的代码或者链接以便我们做排查 ;)
