### ISSUE TITLE
[Bug Report] Affix is not responsive to the size of the screen

### ISSUE THREAD

**Issue by francochau** [element-plus/element-plus#2594]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
MacOs / Chromium: 91.0.4472.124 (Official Build) (x86_64)

### Vue version
3.2.0-beta.3

### Reproduction Link
https://jsfiddle.net/nx5djL3w/20/

### Steps to reproduce
1. Resize window in non-affix state - works just fine
2. Scroll down and affix container appear
3. Resize window in affix state - the width is fix to the width that in non-affix state causing overflow

### What is Expected?
width of the affix container resize when screen width change

### What is actually happening?
css of the container is not responsive

**Comment by JeremyWuuuuu** [comment]
I see, the `size` is fixed for affix, we should add a feature to allow it to be responsive to window resize event, are you interested in doing this?

**Comment by JeremyWuuuuu** [comment]
After discussion with @element-plus/backers team, we decided that we will expose an API for our user to set the size of affix when they needed. The API should be considered done for a short time period, we will keep this open until the API is provided. cc @kooriookami @msidolphin You guys interested on this? If you do please assign to yourself.
