### ISSUE TITLE
[bug report] after adding the modifier number to the input box, you can't enter a number like 1.01. If you click delete, it will only become 1

### ISSUE THREAD

**Issue by notlaughingzzm** [element-plus/element-plus#2595]
Element UI version
1.0.2-beta.55

OS/Browsers version
windows10/google(87.0.4280.88)

Steps to reproduce
将'number'设置为el-input,Usev-model.number .Input1.01 el-input.当输入0时，小数点和0将被删除。

What is Expected?
可以输入1.01,不要删除小数点和0。

What is actually happening?
小数点和0将被删除

**Comment by JeremyWuuuuu** [comment]
This is a little bit hard to comprehend, would you mind uploading a reproducible code sample so that we can provide help?
