### ISSUE TITLE
[bug report] how can I apply to become an advertising sponsor of element plus website?

### ISSUE THREAD

**Issue by osthink** [element-plus/element-plus#2596]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
windows10

### Vue version
3.2.0-beta.3

### Reproduction Link
https://jsfiddle.net/iamkun/ods20kee7t/

### Steps to reproduce
请问怎样申请官网广告位赞助商
https://element-plus.gitee.io/#/zh-CN
一直没有找到相关官方人员的联系方式
请看到后联系我：QQ：83286720  osthink@qq.com
谢谢

### What is Expected?
-

### What is actually happening?
-

**Comment by JeremyWuuuuu** [comment]
We will have someone of our team to get in touch with you, I'd like to thank you for considering sponsoring `ElementPlus`. Thanks!
