### ISSUE TITLE
[Bug Report] css is not applied to the class name specified in label-class-name attribute.

### ISSUE THREAD

**Issue by ohno-kouki** [element-plus/element-plus#2597]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windwos10 

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/nekoze/pen/RwVZvoy

### Steps to reproduce
Specify the class name in the label-class-name attribute and describe the style of the class name in css.

### What is Expected?
The css must be applied.

### What is actually happening?
css will not be applied to the class name specified in the label-class-name attribute of Descriptions Item.

**Comment by kooriookami** [comment]
You can add `!important` to your style.

**Comment by ohno-kouki** [comment]
@kooriookami
thank you!!
I got the result I was looking for.

However, it is preferable not to use "!important".
Is there any other way to ignore CSS priorities?
