### ISSUE TITLE
[Bug Report] shortcuts's value should be a function to update the time when click

### ISSUE THREAD

**Issue by Vgbire** [element-plus/element-plus#2598]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
chrome

### Vue version
3.2.0-beta.3

### Reproduction Link
https://codepen.io/vgbire/pen/WNjEmaO

### Steps to reproduce
Two clicks last 30 minutes

### What is Expected?
The last 30 minutes of the display have changed in real time

### What is actually happening?
The last 30 minutes have been fixed when the time selection component is initialized
if you think it's a bug maybe i can fix it

**Comment by kooriookami** [comment]
@Vgbire now `value`, supports function. It'will be released in the next version.
```js
value: () => {
  const end = new Date();
  const start = new Date();
  start.setTime(start.getTime() - 60 * 1000 * 30);
  return [start, end]
}
```
