### ISSUE TITLE
Element UI vs Element Plus

### ISSUE THREAD

**Issue by johnwheeler** [element-plus/element-plus#260]
Hi,

It's been a while since I've looked at element-ui. I went to the repo and it looks like it hasn't had activity for 4 months, so I searched #elementui on twitter and found this project, which is an upgrade to Vue 3, what I'm looking for. Is this a continuation from the same group of people or a fork with different maintainers? I only ask because of the lack of activity in the element repo; just trying to get some context into what's going on.

Thanks,
John

**Comment by HerringtonDarkholme** [comment]
Hi! Glad to see you here! 
ElementPlus is a UI library for Vue3, the spiritual descendant of ElementUI (which is more or less inactive for some reason),

Most of our contributors are also contributors to ElementUI,  right now we are focusing on rapid development of Element Plus' components. If you want to know more information about this project, keep an eye on us!

 We are anticipating our first alpha released within maybe one month and we are looking forward to continuously improving ElementPlus.

**Comment by johnwheeler** [comment]
Thank you @HerringtonDarkholme !
