### ISSUE TITLE
I want to use the JS variable of vue3 to write to CSS, and v-bind is invalid. For example, const topheight = ref (` red ') in JS, background: v-bind (topheight) in CSS; Invalid background color

### ISSUE THREAD

**Issue by LBJDJW** [element-plus/element-plus#2600]
我想利用vue3的JS变量写入到css中，v-bind无效，比如JS中const topHeight = ref(`red`)，css中 background: v-bind(topHeight);背景颜色无效
<script>
const topHeight = ref(`red`)
</script>

<style scoped lang="scss">
    .demo-drawer__content {
        background: v-bind(topHeight);//无效
    }
</style>

**Comment by JeremyWuuuuu** [comment]
Eight you provide a readable reproducible code to us to help you find a solution or you can go straight to [Vue Documentation](https://v3.vuejs.org) to find you answer. Thank you for submitting issue, feel free to reopen this issue once you have a valid reproducible code.
