### ISSUE TITLE
[Bug Report] `ElNotification` doesn't display correct font

### ISSUE THREAD

**Issue by schnerring** [element-plus/element-plus#2604]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows 10 / Version 92.0.4515.107 (Official Build) (64-bit) / Firefox 90.0 (64-bit)

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/0p7runmo/2/

### Steps to reproduce
Display a notification

### What is Expected?
The notification displays the same font as the rest of the app does

### What is actually happening?
There is a mismatch between the font in the notification and the rest of the app

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/126585589-8274d4b2-8b28-4ba2-a561-949898ce0825.png)
Emm, I don't see any mistake. Could you show me a screenshot?

**Comment by schnerring** [comment]
Firefox:

![image](https://user-images.githubusercontent.com/3743342/126589303-420cbefc-41c9-4be2-8450-aafda85c5247.png)

Chrome:

![image](https://user-images.githubusercontent.com/3743342/126589345-b075289e-b3ba-4e0b-8166-156d2df78638.png)

To "rule out" OS related issues, I also tested it in the Vanadium Browser on my phone which also displays a `serif` font.

**Comment by JeremyWuuuuu** [comment]
Hummmm, interesting. 
Can you provide the networking tab in your devtool, and send us a screenshot for all requests? @schnerring

**Comment by schnerring** [comment]
That's from Chome on my Windows 10 machine. Hope that's sufficient:

![image](https://user-images.githubusercontent.com/3743342/126646389-0206b802-64b2-494f-a462-ecc55ac9d1d5.png)

I have also spun up a Ubuntu VM on the same host machine. Here's Firefox Network tab of that machine.

![Screenshot from 2021-07-22 15-27-56](https://user-images.githubusercontent.com/3743342/126647190-a4221052-cd56-4f5d-b0e5-d6b34e5cf9cf.png)

I also cleared the browser cache on my phone, disconnected from local WiFi, and the issue still persists.

**Comment by kooriookami** [comment]
May be you can give body a default style.
```css
font-family: "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
```

**Comment by JeremyWuuuuu** [comment]
I see, @kooriookami gave a solution, can you give it a try? so that we can figure out how to proceed? 

Since I open the official documentation site we get this, you can see the `font-family` is set on the `html` tag so that the children can automatically inherit it.

Can you set that accordingly as [ElementPlus Font](http://element-plus.org/#/en-US/component/typography) suggested

![image](https://user-images.githubusercontent.com/15975785/126760163-ecb8244d-bd0b-4000-bcb3-a7b729201e2b.png)

**Comment by schnerring** [comment]
That solved the issue, thanks. My bad, but maybe it would be nice to mention this in the Quick Start? I would have expected to get a well rounded out-of-the-box experience after following the instructions there.

**Comment by tim-lyon** [comment]
I also had this issue, which affects many components (message, date picker, select etc) when used from the official example app template. I've made a PR to apply the above suggestion to the example app: https://github.com/element-plus/element-plus-starter/pull/2
