### ISSUE TITLE
Vite for website build

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#2614]
### Background

ElementUI uses `Webpack` as part of its build system, but with `Vite` we can be a lot faster when developing, so we need to migrate from `Webpack` to `Vite` to get better experience

### Nice to have
- Static Site Generation like Gatsby for React which enables us to have a better search rank than dynamic rendering.

**Comment by tolking** [comment]
I have writing a component library based on element-plus, and it is built based on vite (docs support SSG). Maybe I can provide some help.
