### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2618]
导入vue-i18n,
为什么会有这样的警告
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
![image](https://user-images.githubusercontent.com/44356902/126617376-dce81320-e3b1-4c85-a6ad-5699de1a6983.png)

**Comment by JeremyWuuuuu** [comment]
You should go to vue-i18n instead of ElementPlus since this isn't the issue of ElementPlus
