### ISSUE TITLE
ElementPlusError: [Util] binding value must be a string or number

### ISSUE THREAD

**Issue by keke599** [element-plus/element-plus#2631]
版本 1.0.2-beta.55
使用了 el-form 标签
其中有几个 el-form-item 就会报几次该警告
ElementPlusError: [Util] binding value must be a string or number

**Comment by wjw-gavin** [comment]
@keke599  这个应该是el-form-item没有设置 label-width引起的，最新版好像修复了这个问题，如果不是最新版本，可以通过设置 label-width避免

**Comment by wjw-gavin** [comment]
#2615

**Comment by kooriookami** [comment]
Fixed in 1.0.2-beta.56.
