### ISSUE TITLE
Element latest package

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2636]
element用了刚刚发布最新版，报了错，是和element有关吗.vue.js用的是最新版。
![image](https://user-images.githubusercontent.com/44356902/126768905-86f26829-ffc4-49f6-95e5-8eaa624e6c85.png)

**Comment by caige88** [comment]
> element用了刚刚发布最新版，报了错，是和element有关吗.vue.js用的是最新版。
> ![image](https://user-images.githubusercontent.com/44356902/126768905-86f26829-ffc4-49f6-95e5-8eaa624e6c85.png)

我也遇到这个问题了， vue@next

**Comment by natee** [comment]
.56版本  element-plus/lib/local/*.ts 文件丢失了

**Comment by JeremyWuuuuu** [comment]
收到 会紧急处理下

**Comment by caige88** [comment]
> > element用了刚刚发布最新版，报了错，是和element有关吗.vue.js用的是最新版。
> > ![image](https://user-images.githubusercontent.com/44356902/126768905-86f26829-ffc4-49f6-95e5-8eaa624e6c85.png)
> 
> 我也遇到这个问题了， vue@next

html式引入；  回退到上一版本 beta.55

**Comment by JeremyWuuuuu** [comment]
Already located the root cause, I will release a new version with hotfix to fix this

**Comment by JeremyWuuuuu** [comment]
closes via #2645

**Comment by JeremyWuuuuu** [comment]
@stgzhangzheyi please update to newest version see if you still have this issue. Feel free to ping me here! Thank you so much

**Comment by JeremyWuuuuu** [comment]
cc @natee @caige88
