### ISSUE TITLE
[feature request] 1.0.2-beta.56 and 1.0.2-beta.57 cannot use Src

### ISSUE THREAD

**Issue by jsasg** [element-plus/element-plus#2649]
### Existing Component
Yes

### Component Name
el-form, el-form-item, el-button, el-input............................

### Description
1.0.2-beta.56及1.0.2-beta.57都无法使用src方式了，是从这些版本不支持直接src方式吗？

**Comment by JeremyWuuuuu** [comment]
could you elaborate about this?

**Comment by JeremyWuuuuu** [comment]
My apologies for the inconvenience I caused. 
I have refactored the current index.ts and made a mistake which is not exporting the install function.

New release is on the way and you will not have this issue after upgrade to beta-58

:bow:
