### ISSUE TITLE
[Bug Report] Menu items :hover and :focus states issue

### ISSUE THREAD

**Issue by Jimmyzm** [element-plus/element-plus#2655]
### Element Plus version
1.0.2-beta.28

### OS/Browsers version
macOS Big Sur 11.5 - Chrome 92

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/jimmyzm/pen/YzVEBxQ

### Steps to reproduce
Click the menu items, watch the background-color change

### What is Expected?
_I think the second one which is set background-color and clears the :focus state is more reasonable._
Clear the :focus state.

### What is actually happening?
The :focus state of the default active menu item never clear.

**Comment by JeremyWuuuuu** [comment]
@Jimmyzm I think ur right, I’d like to ask that would you like fixing this issue as you proposed? If you do it’d be great and I will assign it to you, otherwise I will log this to the backlog.

**Comment by Jimmyzm** [comment]
> @Jimmyzm I think ur right, I’d like to ask that would you like fixing this issue as you proposed? If you do it’d be great and I will assign it to you, otherwise I will log this to the backlog.

Okay, I would like to fix it.

**Comment by JeremyWuuuuu** [comment]
Close via #2659
