### ISSUE TITLE
[bug report] match between El table expand and El input

### ISSUE THREAD

**Issue by ZhouShuren1881** [element-plus/element-plus#2657]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Chrome 91

### Vue version
3.2.0-beta.4

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-x3vqz

### Steps to reproduce
运行codesandbox的例子，展开expand，在expand中的input里输入任意字符，expand会立即关闭

### What is Expected?
在expand中的input里输入，expand不会关闭。

### What is actually happening?
在expand中的input里输入，expand会立即关闭，导致无法正常输入。

**Comment by msidolphin** [comment]
Please try to use row-key

**Comment by ZhouShuren1881** [comment]
it works, thanks!



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 25, 2021 00:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] [bug report] match between El table expand and El input (#2657)




 
Please try to use row-key
