### ISSUE TITLE
[Feature Request] Space items not expanding to parent

### ISSUE THREAD

**Issue by NoahCardoza** [element-plus/element-plus#2675]
### Existing Component
Yes

### Component Name
Space

### Description
I wanted to use the space component but the items within do not expand to the width of the parent when using `direction="vertical"`. It would be cool if there might be a `fill` option so that when set to true, each `.el-space__item` div gets `width: 100%.` added to it.

**Comment by JeremyWuuuuu** [comment]
Yeah, I think you are right, we can do that, are you interested in making a PR for this feature? We can call it `fill` as you mentioned, it's definitely a good feature for this.

**Comment by adaex** [comment]
I tried to do this feature #2716

**Comment by NoahCardoza** [comment]
Sorry, totally missed your reply @JeremyWuuuuu but thanks a million @adaex for the PR!
