### ISSUE TITLE
element-plus-datetimepicker

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2676]
beta.59版本，引入vue-i18n时，在默认为中文的情况下，日期选择器依旧显示的是英文，而在beta.55版本却显示正常，这是什么原因导致的？
![image](https://user-images.githubusercontent.com/44356902/126920674-24691cd5-ed59-4fc4-8822-440ea14e42c9.png)

**Comment by JeremyWuuuuu** [comment]
What version you are currently using? We made some change for i18n during last weekend, the documentation release is on its way, you should be able to see it in about 2 mins.

**Comment by JeremyWuuuuu** [comment]
With changes we made, `dayjs` related configuration might be broken and we intend to fix that ASAP.

**Comment by JeremyWuuuuu** [comment]
Ref: https://element-plus.org/#/zh-CN/component/i18n

**Comment by stgzhangzheyi** [comment]
> 您目前使用的是什么版本？我们在上周末对 i18n 进行了一些更改，文档发布正在进行中，您应该可以在大约 2 分钟内看到它。
element-plus@1.0.2-beta.59
vue@3.1.5
vue-i18n@9.1.7

**Comment by JeremyWuuuuu** [comment]
> > 您目前使用的是什么版本？我们在上周末对 i18n 进行了一些更改，文档发布正在进行中，您应该可以在大约 2 分钟内看到它。
> > element-plus@1.0.2-beta.59
> > vue@3.1.5
> > vue-i18n@9.1.7

We made breaking changes during the weekend and we think that is the right way to do, we do urge you to checkout the updated documentation for getting simplified config providing strategy 🙏

**Comment by plehnen** [comment]
I tried both, composition api and then with the ElConfigProvider, passing my locale. But datepicker is still english.
Had to additionally do...
```
import lang from 'element-plus/lib/locale/lang/de';
import { use } from 'element-plus/lib/locale';
use(lang);
```
...to get it to work. But now getting a deprecated warning.

**Comment by sxzz** [comment]
This issue is outdated, so I close it. If you have any questions, please create a new issue.
