### ISSUE TITLE
[Bug Report] ElementPlusError: [Util] binding value must be a string or number

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#2677]
### Element Plus version
1.0.2-beta.59

### OS/Browsers version
macOS / chrome 90.0.4430.93

### Vue version
3.1.5

### Reproduction Link
https://github.com/element-plus/element-plus/issues/2615

### What is Expected?
Warnings disappear

### What is actually happening?
This problem still exists in version 1.0.2-beta.59

**Comment by stgzhangzheyi** [comment]
这个问题，我已经消失了

**Comment by TothingWay** [comment]
It still occurs when I set label-width to null, and disappears when I set it to undefined.

**Comment by JeremyWuuuuu** [comment]
@kooriookami Can you follow this up?

**Comment by kooriookami** [comment]
@TothingWay `null` is not a string or number, you can set label-width `0`. And what situation will use `null`?

**Comment by TothingWay** [comment]
Conditional, I want to set a default value and a calculated value, so t it to `null`

**Comment by yuanjinyong** [comment]
我刚从1.0.2-beta.55升级到1.0.2-beta.62后没有再报这个告警了。
After upgrade from 1.0.2-beta.55 to 1.0.2-beta.62, this warring message disappear.

**Comment by kooriookami** [comment]
> Conditional, I want to set a default value and a calculated value, so t it to `null`

You can set an empty string.
