### ISSUE TITLE
International language

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2681]
![image](https://user-images.githubusercontent.com/44356902/126930347-142396de-61cd-4178-a25d-ca75c09b01da.png)
请问这个地址是对的吗？import zhCn from 'element-plus/lib/locale/zh-cn'
还是：import zhCn from 'element-plus/lib/locale/lang/zh-cn'

**Comment by JeremyWuuuuu** [comment]
FYI: ![image](https://user-images.githubusercontent.com/15975785/126934018-b62cc173-4675-4e2f-bed9-a4a59300fd17.png)

**Comment by JeremyWuuuuu** [comment]
The address you gave is wrong, and we haven't update the address yet. Please use the address I pasted here:

`element-plus/locale/lang/zh-cn`

**Comment by JeremyWuuuuu** [comment]
#2684

**Comment by JeremyWuuuuu** [comment]
The release of website is triggered, see the updated content in 5 mins.

**Comment by JeremyWuuuuu** [comment]
@stgzhangzheyi Check this out https://element-plus.org/#/zh-CN/component/i18n

**Comment by woshixinjiu** [comment]
![image](https://user-images.githubusercontent.com/88706517/131342221-e617df5b-e5fb-498e-81c0-ae42f7b351e9.png)
是哪里错了吗，没有生效
