### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2685]
![image](https://user-images.githubusercontent.com/44356902/126940887-f2bf080a-53ca-4317-94a6-890b90ec6c75.png)
请问，app.use(ElementPlus, {
  i18n: i18n.global.t,
})它在1.0.2-beta.59中仍然有效吗？
应该是无效了对吧？

**Comment by JeremyWuuuuu** [comment]
No, this won't work, please refer to [Config Provider](https://element-plus.org/#/zh-CN/component/config-provider) for more detail usage.
