### ISSUE TITLE
[Bug Report] ElNotification.closeAll() | this.$notify.close() not a function

### ISSUE THREAD

**Issue by thamibn** [element-plus/element-plus#2696]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Chrome

### Vue version
3.2.0-beta.4

### Reproduction Link
https://codesandbox.io/s/busy-glade-t4x6c?file=/src/App.vue

### Steps to reproduce
creted notifications but cannot close them manually by calling ElNotification.closeAll() | this.$notify.close()
so this results to same notifications shown multiple times instead of one per time.

### What is Expected?
to close all notifications before showing new ones

### What is actually happening?
throws an error

Layout.vue?f926:42 Uncaught (in promise) TypeError: this.$notify.close is not a function

**Comment by msidolphin** [comment]
close is a method on the Notification instance
