### ISSUE TITLE
[feature request] el-select-v2 how to adjust the number of options displayed by default in the drop-down box

### ISSUE THREAD

**Issue by codepiano** [element-plus/element-plus#2700]
### Existing Component
是

### Component Name
el-select-v2

### Description
el-select-v2 当前默认只渲染了7条，展示前5条。

我想调整一下下拉框长度，增加默认显示的选项条数，在文档中没有找到调整默认数量和下拉框height的示例，不确定是目前没有这个功能还是我没找到，麻烦告知一下调整方法

**Comment by msidolphin** [comment]
You can use the height property(the default value of this property is 170), we apologize for not mentioning this property in the documentation, we will add to the documentation in time.

**Comment by msidolphin** [comment]
By the way, close is a method on the Notification instance.

**Comment by codepiano** [comment]
> You can use the height property(the default value of this property is 170), we apologize for not mentioning this property in the documentation, we will add to the documentation in time.

Thanks. It works well.

```
  <el-select-v2
      class="node-selector"
      v-model="value"
      filterable
      :height=600
/>
```
