### ISSUE TITLE
[bug report] avatar component line height style error

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#2701]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
win10

### Vue version
3.2.0-beta.4

### Reproduction Link
/

### Steps to reproduce
![1627306938(1)](https://user-images.githubusercontent.com/1574903/126998896-410ea07b-e1a9-462e-aeec-daeb922374df.jpg)

### What is Expected?
/

### What is actually happening?
/

**Comment by YunYouJun** [comment]
This is a typo. Thanks. We'll fix it right away.
