### ISSUE TITLE
[Bug Report] Getting "Vue warn" when combining el-form with WritableComputedRef

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#2706]
### Element Plus version
1.0.2-beta.62

### OS/Browsers version
Windows 10 / Chrome (Latest)

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/4Lrco1kh/15/

### Steps to reproduce
When using a WritableComputedRef as a container object for form components, and wrapping those with an el-form I get the following warning:
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

See reproduction link (note: locally editing is possible, but had troubles getting this to work in the jsfiddle. dunno why)

If I don't use el-form around the el-input, everything is working fine without any warning.

### What is Expected?
There should not be a warning when using el-form

### What is actually happening?
A warning is shown

**Comment by kooriookami** [comment]
`ref` can't be the same value as `model`. You can use like this `<el-form ref="formRef" :model="form">`

**Comment by plehnen** [comment]
Very interesting. I wasn't aware that this.form and this.$refs.form should not co-exist with the "same" name.
I don't really understand why they are colliding but renaming one is indeed fixing the problem. Many thanks for the hint! :)
