### ISSUE TITLE
Rewriting SCSS color variables

### ISSUE THREAD

**Issue by hls-1992** [element-plus/element-plus#2708]
通过vue-cli创建，vue add element-plus，版本^1.0.2-beta.28。
可以发现源码中var.scss代码发生变化，在本地的element-variables.scss中覆盖相关变量不起作用

**Comment by kooriookami** [comment]
是的，目前我们在迁移样式，使用css3的var变量来覆盖样式。

**Comment by 1165468011** [comment]
> 是的，目前我们在迁移样式，使用css3的var变量来覆盖样式。

现在我使用的element-plus版本是1.0.2-beta.63，vite版本是2.3.8，使用element-variables.scss文件覆盖变量无效。请问何时可以完成样式迁移以使用css3的var变量

**Comment by YunYouJun** [comment]
> 现在我使用的element-plus版本是1.0.2-beta.63，vite版本是2.3.8，使用element-variables.scss文件覆盖变量无效。请问何时可以完成样式迁移以使用css3的var变量

我们将在本周完成大部分组件的迁移。考虑到一些隐藏的 bug 与细节优化。最终的迁移文档与简易的示例将会较迟完成。

**Comment by YunYouJun** [comment]
您可以通过 https://github.com/element-plus/element-plus/issues?q=is%3Aopen+is%3Aissue+label%3A%22css+migration%22 了解目前的迁移进度。

**Comment by 1165468011** [comment]
> 您可以通过 https://github.com/element-plus/element-plus/pulls?q=is%3Aopen+is%3Apr+label%3A%22css+migration%22 了解目前的迁移进度。

十分感谢

**Comment by YunYouJun** [comment]
More suggestions can be made at #2242.
