### ISSUE TITLE
V1.0.2-beta62 custom theme, individual parameters invalid

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#2712]
ElelementPlus v1.0.2-beta62 自定义主题，个别参数失效，感觉是一下代码造成的影响：
![image](https://user-images.githubusercontent.com/22720488/127091499-956617d5-001c-4c72-8dcf-bf0e14f94c48.png)

**Comment by jiaozhiye** [comment]
类似这种写法，外部的自定义主题变量无法覆盖：
![image](https://user-images.githubusercontent.com/22720488/127098108-239cb54a-e53e-4bc4-a65d-05dcb0f926af.png)

**Comment by adaex** [comment]
这个问题在最新的提交中已经解决了 [详情](https://github.com/element-plus/element-plus/pull/2691/files#diff-eb85fc73444e26f19f950007c73a7d86028b1453c33efc86d2b5478ea027c01a)

**Comment by YunYouJun** [comment]
The beta version of the SCSS system is undergoing a major refactoring and some naming conventions are being corrected. For example, `color-text` to `text-color`.

It has been solved. Just upgrade it. 😄
