### ISSUE TITLE
Elementplus v1.0.2-beta62/63 rollup package error

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#2715]
ElementPlus v1.0.2-beta62/63 rollup 打包时 ts 报错，如下：
(!) Plugin typescript: @rollup/plugin-typescript TS2304: Cannot find name 'Nullable'.
node_modules\element-plus\lib\utils\types.ts: (24:26)

24 export type RefElement = Nullable<HTMLElement>

**Comment by likeswinds** [comment]
![image](https://user-images.githubusercontent.com/7099174/127108658-558f4597-0ed2-47d5-aac1-4f0e94ad9ac0.png)
webpack

**Comment by antk0m** [comment]
Same problem

**Comment by kooriookami** [comment]
It seems solved.
