### ISSUE TITLE
[Bug Report] new css var $--input-height can't be overwritten

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#2720]
### Element Plus version
1.0.2-beta.63

### OS/Browsers version
Windows 10 / Chrome (latest)

### Vue version
3.1.5

### Reproduction Link
n/a

### Steps to reproduce
I am using the "on demand" import (with customStyleName configuration).

In an older beta I was using `$--input-height: 48px !default;` to overwrite the input height. The variable apparently changed to:
```
$--input-height: (
  'default': 40px,
  'medium': 36px,
  'small': 32px,
  'mini': 28px,
);
```

But I am not able to overwrite this, regardless if I put it before or after `@import '~element-plus/packages/theme-chalk/src/index';` I cannot change the height.

### What is Expected?
I want to be able to overwrite the input-height 

### What is actually happening?
It is still using the old value.

**Comment by YunYouJun** [comment]
You can use `sass:map`.

Just like this;

```scss
$--input-height: map.merge(
  $--input-height,
  (
    'default': 56px
  )
);
```

---

😄 Then we will provide a default mode automatically merge `$--input-height` for you to use directly like this:

```scss
$--input-height: (
  'default': 56px
);
```

**Comment by plehnen** [comment]
Regardless what I do, the height remains **40px** instead of **48px**:

I guess it is internally overwritten via common/var.scss again?

![image](https://user-images.githubusercontent.com/24891471/127139981-8c7feba4-e7f5-46f7-8a99-4b23ad79269b.png)

**Comment by YunYouJun** [comment]
In fact, i try it. And it works.

```scss
$--input-height: map.merge(
  $--input-height,
  (
    'default': 48px,
  )
);
```

![image](https://user-images.githubusercontent.com/25154432/127166236-9c54dbb4-92d3-4991-a0ad-8882b414020f.png)

You should merge it after `var.scss` of element. (Or, just use `$--input-height: ( 'default': 48px )` before it. A new PR will be created, and released in tomorrow.)

**Comment by YunYouJun** [comment]
It has been released. See #2733.
