### ISSUE TITLE
[bug report] 1.0.2-bate56 and later versions cannot customize the theme when using 'vite plugin style import' to load on demand

### ISSUE THREAD

**Issue by mbossX** [element-plus/element-plus#2724]
### Element Plus version
1.0.2-beta.56

### OS/Browsers version
windows

### Vue version
3.1.5

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
as `base.scss ` change from  
```
@import "common/transition.scss";
@import "icon.scss";
```
to
```
@import 'common/transition.scss';
@import 'icon.scss';
@import 'var.scss';
```

and each component do not `@import 'var'`, so `additionalData` can not work.

when I use `1.0.2-bate55` and older version, it works.

### What is Expected?
`additionalData` can affect theme.

### What is actually happening?
`additionalData` can not work.

**Comment by mbossX** [comment]
使用全局加载的没问题，按需加载就不行。
测试发现版本 `1.0.2-bate55` 以后就不行了。

**Comment by JeremyWuuuuu** [comment]
Sorry, we are making updates to cssvar for better theming experiences, this breaks the current way of implementing theme.

**Comment by mbossX** [comment]
ok, plase update docs for new version and `vite-plugin-style-import` custom theme.

thanks.

**Comment by JeremyWuuuuu** [comment]
> ok, plase update docs for new version and `vite-plugin-style-import` custom theme.
> 
> thanks.

Will do, once the feature is 100% usable, we will update the documentation accordingly! Thank you for giving feedback, this is important for this project.

**Comment by Oleksii14** [comment]
@JeremyWuuuuu I am having the same issue using Vue CLI. Can this be fixed somehow in the new versions?

**Comment by ErrorJe** [comment]
> > ok, plase update docs for new version and `vite-plugin-style-import` custom theme.
> > thanks.
> 
> Will do, once the feature is 100% usable, we will update the documentation accordingly! Thank you for giving feedback, this is important for this project.

any docs update?

**Comment by dmytropryshliak** [comment]
I have similar to @Oleksii14 issue, vue cli build is failing because of `SassError: Undefined variable.`. Everything works fine with beta-54.

**Comment by Oleksii14** [comment]
@JeremyWuuuuu do you plan to fix that for vue-cli?

Here is my scss:

```
$--color-primary: #0069a6;
$--color-info: #3e8a99;
$--color-danger: #ff5252;
$--color-warning: #fb8c00;

$--font-path: '~element-plus/lib/theme-chalk/fonts';
```

babel.config.json

```
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  plugins: [
    [
      'import',
      {
        libraryName: 'element-plus',
        customStyleName: name => {
          name = name.slice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`
        },
      },
    ],
  ],
}
```

main.ts

```
import 'element-plus/packages/theme-chalk/src/base.scss'
```

vue.config.js

```
const path = require('path')
const fs = require('fs')
const elementScssVariables = fs.readFileSync(path.join(__dirname, 'shared/scss/_element-plus.scss'), 'utf8')
...
css: {
    loaderOptions: {
      sass: {
        additionalData: `
          ${elementScssVariables}
        `,
      },
    },
  },
```

And the custom theme is not working. Version beta.56 broke it. @JeremyWuuuuu do you plan to fix and document it properly? We cannot use the custom theme feature at all in the new versions of element-plus

Please add some docs for configuring the custom theme, while using vue-cli and babel-plugin-import

Thanks in advance!
