### ISSUE TITLE
[bug report] elpagination does not display problems when the CurrentPage is defined but the current change event is not monitored

### ISSUE THREAD

**Issue by fwfx1234** [element-plus/element-plus#2736]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
macos/edge

### Vue version
3.2.0-beta.4

### Reproduction Link
https://codepen.io/fwfx1234/pen/LYyQqLY

### Steps to reproduce
codepen

### What is Expected?
咨询下是有意设计成这样的还是bug

### What is actually happening?
使用的版本1.0.2-beta.63
```
<el-pagination

      :current-page="currentPage4"
      :page-sizes="[100, 200, 300, 400]"
      :page-size="100"
      layout="total, sizes, prev, pager, next, jumper"
      :total="400">
    </el-pagination>
```
使用了current-page但是没监听current-change事件。这么使用会在控制台打印warn，并且组件没有显示。看代码逻辑是要求有current-page的时候要监听current-change事件。并且在warn之后结束了流程，导致界面没有渲染。觉得不太合理，应该让ui展示出来的。毕竟是个warn，不是error。 另外升级版本之后，由于国际化改了，这个地方的warn信息就是undefined了。
```ts
//packages/pagination/src/index.ts  248行
      if (!assertValidUsage.value) {
        debugger
        warn(componentName, t('el.pagination.docRefer'))
        return null
      }
```

**Comment by SakuOtonashi** [comment]
我也遇到了之前一直使用 v-model ，这样改了后 v-model 双向绑定没什么意义了，要么
```
  // 只能先定义一个空函数
  function noop() {}

  // 临时处理
  @size-change="noop"
  @current-change="noop"
```

**Comment by ChenWeihua123** [comment]
遇到了同样的问题 按照issue修改了写法也不好使 请问怎么解决 
```
ElementPlusError: [ElPagination] undefined
```

**Comment by dmytropryshliak** [comment]
@ChenWeihua123 you can add `@current-change="() => {}"` to your `el-pagination`. At least pagination component will display and is working.

**Comment by ChenWeihua123** [comment]
@dmytropryshliak I did what you said and it didn't work... 
vue@3.2、ElementPlus@beta.70
```
<el-pagination
        class="main-pagination"
        :default-page-sizes="tableSize"
        :default-current-Page="tablePage"
        @current-change="() => {}"
        @size-change="() => {}"
      ></el-pagination>
```

**Comment by ChenWeihua123** [comment]
@dmytropryshliak I did what you said and it didn't work... 
vue@3.2、ElementPlus@beta.70
```
<el-pagination
        class="main-pagination"
        :default-page-sizes="tableSize"
        :default-current-Page="tablePage"
        @current-change="() => {}"
        @size-change="() => {}"
      ></el-pagination>
```

**Comment by dmytropryshliak** [comment]
@ChenWeihua123 maybe I have different props setup. This is mine:

`<el-pagination
    background
    layout="prev, pager, next"
    :total="total"
    :page-size="pageSize"
    v-model:current-page="page"
    @current-change="() => {}"
  >`

I use the same element version.

**Comment by ChenWeihua123** [comment]
@dmytropryshliak thanks, I try again

**Comment by ChenWeihua123** [comment]
@dmytropryshliak it works! thanks a million.
 the warning is not detailed
