### ISSUE TITLE
ElForm

### ISSUE THREAD

**Issue by huangliangb0** [element-plus/element-plus#2744]
怎么声明ElForm类型，例如formRef = ref<ElForm>(null)，让TS检测到formRef 存在validate方法以及其它属性

**Comment by JeremyWuuuuu** [comment]
@huangliangb0, 可以尝试一下, 我不太确定这样行不行，因为目前类型生成有些小问题。
```ts
import ElForm from 'element-plus'

const formRef = ref<typeof ElForm>()

```

**Comment by gwen1230** [comment]
When i do that and return formRef in my setup, I have this issue : "Default export of the module has or is using private name 'Callback'.".
It could come come from "declaration: true" in my tsconfig, but I need that...

**Comment by huangliangb0** [comment]
> @huangliangb0, 可以尝试一下, 我不太确定这样行不行，因为目前类型生成有些小问题。
> 
> ```ts
> import ElForm from 'element-plus'
> 
> const formRef = ref<typeof ElForm>()
> ```

很显然不行,只能在全局global.d.ts去声明ElForm的类型

**Comment by anguiao** [comment]
```typescript
import ElForm from 'element-plus'

const formRef = ref<InstanceType<typeof ElForm>>()
```
这样应该是没有问题的

**Comment by huangliangb0** [comment]
> ```ts
> import ElForm from 'element-plus'
> 
> const formRef = ref<InstanceType<typeof ElForm>>()
> ```
> 
> 这样应该是没有问题的

good，稍微写错了一下，ElForm是解构出来的值
