### ISSUE TITLE
[Bug Report] ssr Image is not defined

### ISSUE THREAD

**Issue by yang867381349** [element-plus/element-plus#2746]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
System:     OS: macOS 11.4     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz     Memory: 59.43 MB / 16.00 GB     Shell: 5.8 - /bin/zsh   Binaries:     Node: 14.17.3 - /usr/local/bin/node     Yarn: 1.22.10 - /usr/local/bin/yarn     npm: 6.14.13 - /usr/local/bin/npm   Browsers:     Chrome: 92.0.4515.107     Firefox: 89.0.2     Safari: 14.1.1

### Vue version
3.2.0-beta.4

### Reproduction Link
https://github.com/yang867381349/error-element-plus

### Steps to reproduce
$ npm install   

$ node serverOs

### What is Expected?
尽快解决该问题。

### What is actually happening?
导致ssr 无法在服务器中使用和生产。

**Comment by yang867381349** [comment]
@JeremyWuuuuu

**Comment by yang867381349** [comment]
@bmfs

**Comment by yang867381349** [comment]
@PxlBuzzard 
@luxueyan

**Comment by yang867381349** [comment]
@msidolphin  我现在如何才能处理这个问题。我很着急  我要发布项目。

**Comment by JeremyWuuuuu** [comment]
@yang867381349 你给的项目地址我看不了，给个最简单的 demo 代码

**Comment by JeremyWuuuuu** [comment]
@yang867381349 如果非常着急，建议先回滚定到 beta.55 发布，https://github.com/element-plus/element-plus/issues/2611#issuecomment-886399740 我不太确定，我正在看这个问题

**Comment by yang867381349** [comment]
5.5也存在这个问题？我已经尝试了。

**Comment by yang867381349** [comment]
这个问题是打包后出现的。

**Comment by JeremyWuuuuu** [comment]
> 这个问题是打包后出现的。

准备发个 Patch，你大概等个 20 分钟左右就可以 upgrade 看看有没有什么问题。

**Comment by yang867381349** [comment]
https://github.com/yang867381349/error-zhizhi

**Comment by yang867381349** [comment]
@JeremyWuuuuu 这是我的项目 可以运行后查看

**Comment by yang867381349** [comment]
打包的包  要拿出这个项目以外  再 npm install  错误就会显示出来了

**Comment by yang867381349** [comment]
要拿出去 以下文件
dist
serverOs.js
package.json

**Comment by JeremyWuuuuu** [comment]
Close via #2754 , 5分钟之内我会触发发布脚本，然后再等 10 - 15 分钟就可以了。

**Comment by yang867381349** [comment]
如果在原有的包内运行是看不到错误的。

**Comment by JeremyWuuuuu** [comment]
@yang867381349  https://github.com/element-plus/element-plus/actions/runs/1074849975
