### ISSUE TITLE
[Bug Report] i18n breaks when using on-demand-import

### ISSUE THREAD

**Issue by wenfangdu** [element-plus/element-plus#2755]
### Element Plus version

1.0.2-beta.62

### OS/Browsers version

Windows 10, Chrome 92

### Vue version

3.2.0-beta.4

### Reproduction Link

https://github.com/wenfangdu/el-plus-repro/tree/i18n

### Steps to reproduce

Please use the repro link and run the app, the following error will be thrown:

```
Failed to compile.

./src/main.js
Module not found: Error: Can't resolve 'element-plus/lib/theme-chalk/use-locale-props.css'
```

For what it's worth, I used [vue-cli-plugin-element-plus](https://github.com/element-plus/vue-cli-plugin-element-plus) to bootstrap the on-demand-import.

### What is Expected?

i18n works as documented.

### What is actually happening?

i18n breaks when using on-demand-import.

**Comment by JeremyWuuuuu** [comment]
@wenfangdu Please check out here: https://element-plus.org/#/zh-CN/component/i18n
We made breaking change during last weekend, sorry for the inconvenience :bow:

**Comment by wenfangdu** [comment]
@JeremyWuuuuu Yes, I'm aware of that, I tried both full import and on-demand import with the new i18n setup, but on-demand import just couldn't succeed, please try my on-demand import repro [here](https://github.com/wenfangdu/el-plus-repro/tree/i18n).

**Comment by wenfangdu** [comment]
> > @JeremyWuuuuu What I provided is a _minimal_ repro case, which means before wrapping, the behavior already goes wrong, in this case, the following are printed:
> > ```
> > These dependencies were not found:
> > 
> > * element-plus/lib/theme-chalk/use-locale-props.css in ./src/main.js
> > * element-plus/lib/theme-chalk/use-locale.css in ./src/main.js
> > * element-plus/lib/use-locale in ./src/main.js
> > * element-plus/lib/use-locale-props in ./src/main.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know good programmers can know the problem just by looking at the code, but please, clone the repro and actually run it. Otherwise, we're always talking about the different issues.
> 
> May I ask which version you are currently using? The issue looks familiar to me since we didn't add an empty `config-provider.scss` into the repo.

@JeremyWuuuuu I've upgraded `element-plus` to `v1.0.2-beta.65` in my [repro](https://github.com/wenfangdu/el-plus-repro/tree/i18n), and the issue persists, could you please reopen this issue?

**Comment by wenfangdu** [comment]
> I think this is caused by the webpack-plugin or vite plugin you are using, for composables, there was no `css` for the plugin to import, we need to adjust the plugin config.

@JeremyWuuuuu I used [vue-cli-plugin-element-plus](https://github.com/element-plus/vue-cli-plugin-element-plus) to bootstrap the on-demand import.

It hasn't been updated to reflect the i18n change, I've created an issue for that:

- https://github.com/element-plus/vue-cli-plugin-element-plus/issues/19
