### ISSUE TITLE
[feature request] datepicker width adjustment

### ISSUE THREAD

**Issue by Cat7373** [element-plus/element-plus#2765]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
希望能主动控制组件宽度，尤其是现在显示成 2021-07-30 这种格式时，整个组件有一大半区域是空白的

**Comment by iamkun** [comment]
Feel free to customize  it via css 
![image](https://user-images.githubusercontent.com/17680888/127599454-845a3b6f-22fe-4fb9-a258-fc60fe5af911.png)

**Comment by YunYouJun** [comment]
I think css var can solve this problem.

**Comment by YunYouJun** [comment]
I create a PR(2836) to custom date-editor width by css var. Is this what you want?

![image](https://user-images.githubusercontent.com/25154432/128219017-57b6ddce-7390-4ee4-b2d4-fd234041b952.png)
![image](https://user-images.githubusercontent.com/25154432/128219832-b842ecc2-ba79-4442-a8d4-e058579291ba.png)
