### ISSUE TITLE
[Bug Report] el-select-v2 in a inactive el-tab-pane, the droplist panel's width is half of the el-select-v2

### ISSUE THREAD

**Issue by codepiano** [element-plus/element-plus#2767]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
macos big sur 11.4/ chrome 91.0.4472.164 (Official Build) (x86_64)

### Vue version
3.1.5

### Reproduction Link
https://codepen.io/codepiano-the-sasster/pen/vYmjGMG

### Steps to reproduce
put an el-select-v2 tag which set width property by "style" in an inactive el-tab-pane, then click this el-tab-pane, click the el-select-v2 component

### What is Expected?
the width of dropbox is correct calculate, the same as el-select-v2's width

### What is actually happening?
the width of dropbox is not correct, half of the el-select-v2

**Comment by codepiano** [comment]
same el-select-v2 code  in different el-tab-pane produce:

# correct
![Xnip2021-07-30_12-21-28](https://user-images.githubusercontent.com/2015631/127599812-5696cbe5-37f8-44d4-93ad-e9af0c9aee2a.jpg)
# incorrent
![Xnip2021-07-30_12-21-11](https://user-images.githubusercontent.com/2015631/127599816-77e075da-131e-4c83-84e4-26936daa1861.jpg)

**Comment by codepiano** [comment]
I used the following code as a temporary fix
```
.el-select-dropdown__list {
  width: 400px !important;
}
```

**Comment by zhaozhongyu** [comment]
因为在inactive的tab中处于display: none状态时尝试去执行getBoundingClientRect, 此时获取到宽度0, 从而使用了默认宽度200, 与一半无关
