### ISSUE TITLE
[Bug Report] [ElTable] default-expand-all not working

### ISSUE THREAD

**Issue by pdsuwwz** [element-plus/element-plus#2776]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
MacOS Big Sur 11.2 / Chrome 92.0.4515.107 (x86_64)

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/XDB/pen/jOmxXBN

### Steps to reproduce
1. Open https://element-plus.org/#/en-US/component/table#tree-data-and-lazy-mode

2. Move to `Tree data and lazy mode`

3. Run this demo on codepen.io

### What is Expected?
All rows of the table are expanded

### What is actually happening?
All rows of the table are not expanded, `default-expand-all` doesn't seem to work

**Comment by pdsuwwz** [comment]
Although `default-expand-all` is set, it does not actually work.

![image](https://user-images.githubusercontent.com/19891724/127730408-28a99c46-7945-4fc8-9e02-b90a200172f1.png)

**Comment by adaex** [comment]
It is correct on the version before `vue@3.1.4`.

![image](https://user-images.githubusercontent.com/29560987/127771508-d4dd9fbf-1712-4f5e-8c6d-f249b242ccb6.png)

However, all versions after `vue@3.1.5`are incorrect.

![image](https://user-images.githubusercontent.com/29560987/127771662-38631954-3e19-49f4-b7da-a5e4c4526f54.png)


Check the [changelog of `vue@3.1.5` ](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#315-2021-07-16) , no useful information has been found yet. 😔


![image](https://user-images.githubusercontent.com/29560987/127771614-5a9147aa-e7fe-4366-af49-5d44b4f4f517.png)

**Comment by End4You** [comment]
same problem
