### ISSUE TITLE
[Bug Report] The (: input style) attribute of < El-input > cannot be changed in real time

### ISSUE THREAD

**Issue by WifiStop** [element-plus/element-plus#2777]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
winow 10

### Vue version
3.1.5

### Reproduction Link
https://codepen.io/a13588957213/pen/XWRqGdQ

### Steps to reproduce
The background color of the input box does not turn green two seconds after opening the link

### What is Expected?
After two seconds, the background color of the input box automatically turns green

### What is actually happening?
The input box will not turn green after two seconds. The input box does not turn green until you enter something

**Comment by adaex** [comment]
PR #2779
