### ISSUE TITLE
[bug report] use select in Popover or dropdownitem (trigger = click). When select has no data, click the drop-down box or there is data. Click the upper and lower edges of the drop-down box, and the position of the drop-down box will drift

### ISSUE THREAD

**Issue by bitjjj** [element-plus/element-plus#2781]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
MacOS / Chrome 92

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/bitjjj/pen/xxdzzqj

### Steps to reproduce
1)  点击Select，弹出下拉框
2）单击下拉框上下边缘
3）下拉框会发生位置漂移

### What is Expected?
下拉框正确显示

### What is actually happening?
下拉框位置被重置到页面左上角

**Comment by msidolphin** [comment]
> ### Element Plus version
> 1.0.2-beta.65
> 
> ### OS/Browsers version
> MacOS / Chrome 92
> 
> ### Vue version
> 3.2.0-beta.7
> 
> ### Reproduction Link
> https://codepen.io/bitjjj/pen/xxdzzqj
> 
> ### Steps to reproduce
> 1. 点击Select，弹出下拉框
>    2）单击下拉框上下边缘
>    3）下拉框会发生位置漂移
> 
> ### What is Expected?
> 下拉框正确显示
> 
> ### What is actually happening?
> 下拉框位置被重置到页面左上角

Please set `popper-to-append-body` to false

**Comment by binvb** [comment]
i can help in this
