### ISSUE TITLE
[bug report] cascade component sets props property checkstrictly: true

### ISSUE THREAD

**Issue by itHulk** [element-plus/element-plus#2783]
### Element Plus version
1.0.2-beta.53

### OS/Browsers version
chrome  88.0.4324.192

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/hua-yu/pen/xxdzaPq

### Steps to reproduce
element ui 官方demo： https://element.eleme.io/#/zh-CN/component/cascader                                                    
element plus 官方demo：  https://element-plus.gitee.io/#/zh-CN/component/cascader                                          
在elemnt ui中 cascader 组件设置 props属性 checkStrictly: true，来实现选择任意一级的效果，当父级radio被选中的时候，加载对应的children。但是在element plus中，父级radio被选中，不加载对应的children，除非去点击父级的文本。

### What is Expected?
 可否把element plus的交互与element ui 中cascader的交互一致？或者提供类似的功能。 测试认为这种变化是组件bug

### What is actually happening?
element plus中 cascader 组件设置 props属性 checkStrictly: true，与 element ui 中的 cascader 组件设置 props属性 checkStrictly: true，交互表现不一致。

**Comment by SimonaliaChen** [comment]
When set `checkStrictly: true`, the selection of the parent node is independent of that of the child nodes. Which means, check and expand should be unrelated, checking the parent node should not expand the child nodes. So IMO, `element-plus`'s interaction is more reasonable and consistent in either single or multiple mode. If the QA of your company insists that it's a  bug, I recommend you fork `cascader` and custom it yourself according to #2788 (Thanks to @BeADre ). But I'm sure you'll convince the QA :)
