### ISSUE TITLE
cdn中使用国际化无效

### ISSUE THREAD

**Issue by jipengwei** [element-plus/element-plus#2786]
[
![20210802174605](https://user-images.githubusercontent.com/12807371/127841576-357a44a9-38d7-4d8f-82d8-cf21cbe0649b.png)
](url)

官方能不能把这个处理一下，这个半点作用都没有,  使用大量的时间调试发现根本就是无效的！

**Comment by JeremyWuuuuu** [comment]
> [ ![20210802174605](https://user-images.githubusercontent.com/12807371/127841576-357a44a9-38d7-4d8f-82d8-cf21cbe0649b.png) ](url)
> 
> 官方能不能把这个处理一下，这个半点作用都没有, 使用大量的时间调试发现根本就是无效的！

实在抱歉，我们这边疏忽了，我们会加急修改一下文档。:bow:

**Comment by sxzz** [comment]
It seems that docs has been changed.
