### ISSUE TITLE
[Bug Report] El-Form: vue ref attribute overlaps fields with the same name

### ISSUE THREAD

**Issue by bearbattle** [element-plus/element-plus#2790]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
Windows 10 LTSC 2019 (Version 1809), Microsoft Edge/92.0.902.62

### Vue version
3.1.5

### Reproduction Link
https://codepen.io/bearbattle/pen/NWjzVxP

### Steps to reproduce
Open Console in the codepen. The output should automatically shows up.

### What is Expected?
`this.form` should refer to filed previously defined.

### What is actually happening?
`this.form` refers to the instance of `<el-form>` itself.

**Comment by kooriookami** [comment]
You can refer to vue doc. https://v3.vuejs.org/guide/composition-api-template-refs.html
It's not up to us. Maybe you can give a suggestion to vue.

**Comment by bearbattle** [comment]
@kooriookami Thanks! I'm migrating from Vue2.x, so the behavior of template `ref` different among versions is quite confusing. I'll take that and close the issue.
