### ISSUE TITLE
[bug report] theme color coverage failed after upgrading 1.0.2-beta.46 to 1.0.2-beta.65

### ISSUE THREAD

**Issue by wendyLai** [element-plus/element-plus#2793]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
window10

### Vue version
3.0.5

### Reproduction Link
https://github.com/element-plus/element-plus/tags

### Steps to reproduce
$--color-primary: $MAIN_COLOR; // 无效

### What is Expected?
$--color-primary: $MAIN_COLOR; // 有效

### What is actually happening?
$--color-primary: $MAIN_COLOR; // 无效

**Comment by wanghuaichao** [comment]
Just change the version of Element-Plus to 1.0.0-deta.55

**Comment by YunYouJun** [comment]
After `1.0.2-beta.55`, we refactor sass and support css var.

You can use this method to override colors.

```scss
$--colors:  (
  'white': #ffffff,
  'black': #000000,
  'primary': (
    'base': #409eff,
  ),
  'success': (
    'base': #67c23a,
  ),
  'warning': (
    'base': #e6a23c,
  ),
  'danger': (
    'base': #f56c6c,
  ),
  'error': (
    'base': #f56c6c,
  ),
  'info': (
    'base': #909399,
  ),
);
```
or write global css

```css
:root {
  --el-color-primary: red;
}
```

A complete migration guide will come soon.

You can subscribe #2242.

**Comment by yang867381349** [comment]
我试了为啥只能生效 $--colors 里面的  却无法生效  :root {
  --el-color-primary: red;
}
