### ISSUE TITLE
[Bug Report] Attributes `size` not effect in component el-button with type of circle

### ISSUE THREAD

**Issue by vegaoqiang** [element-plus/element-plus#2795]
### Existing Component
Yes

### Component Name
el-button

### Element-plus version
1.0.2-beta.65

### Vue version
3.1.1

### system / Chrome version
macOS 10.15.7 / 91.0.4472.114

### Description
使用圆形按钮不能调整按钮大小

**Comment by exidot** [comment]
我从beta48升级到beta65时也遇到了这个问题，并且好像是从beta49开始出现。我发现此时button标签的padding有点大，是12px，当改成8px时看着比较合适

**Comment by YunYouJun** [comment]
The circle button doesn't have this function, but it might be worth considering.

**Comment by AubSs** [comment]
Prior to x.55 circle button was using the attr :size=""
now :size doesn't have any effect

it's more a bug than a enhancement

**Comment by YunYouJun** [comment]
I see. I will fix it.
