### ISSUE TITLE
[Bug Report] el-image preview not work with el-arousel in Element Plus, But work in Element UI

### ISSUE THREAD

**Issue by eligarfzzz** [element-plus/element-plus#2798]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
windows 10 / chrome 92.0.4515.107

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/2291030272/pen/gOWjRNx

### Steps to reproduce
click the image

### What is Expected?
hope the image fit full screen in window, like element ui in vue2 https://codepen.io/2291030272/pen/QWvBMLV

点击图片后，希望预览图在浏览器全屏显示，但实际只在el-carousel-item区域显示。

在vue2 版本element ui可以正常显示

vue3 版本https://codepen.io/2291030272/pen/gOWjRNx

vue2 版本https://codepen.io/2291030272/pen/QWvBMLV

### What is actually happening?
 image only fit <el-carousel-item>

**Comment by eligarfzzz** [comment]
希望的结果（Vue2）
![企业微信截图_16279754584596](https://user-images.githubusercontent.com/71590040/127975040-c5f601d3-de2a-4d00-9f23-e6fb63a2f6f5.png)
实际的结果
![企业微信截图_16279754902427](https://user-images.githubusercontent.com/71590040/127975086-19d0208a-8f00-4e3b-9235-d9a48932a5b2.png)

**Comment by JeremyWuuuuu** [comment]
> 希望的结果（Vue2）
> ![企业微信截图_16279754584596](https://user-images.githubusercontent.com/71590040/127975040-c5f601d3-de2a-4d00-9f23-e6fb63a2f6f5.png)
> 实际的结果
> ![企业微信截图_16279754902427](https://user-images.githubusercontent.com/71590040/127975086-19d0208a-8f00-4e3b-9235-d9a48932a5b2.png)

看起来是这个没有 append 到 body 所以导致只能 inline，你需要给 image 加一个 appendToBody 就可以了。
![image](https://user-images.githubusercontent.com/15975785/128110544-52dc8a8c-bbe2-47c4-9c63-f67ff5f2a949.png)
