### ISSUE TITLE
[Bug Report] Descriptions border

### ISSUE THREAD

**Issue by hyke123** [element-plus/element-plus#2801]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
windows

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
这个版本Descriptions组件边框不显示了

### What is Expected?
show border

### What is actually happening?
这个版本Descriptions组件边框不显示了

**Comment by YunYouJun** [comment]
Has been fixed in `1.0.2-beta.66`.
