### ISSUE TITLE
[Bug Report] "element-icons.ttf"  "element-icons.woff" File size 0KB??? Yes 😥

### ISSUE THREAD

**Issue by dabaii** [element-plus/element-plus#2811]
### Element Plus version
1.0.2-beta.66

### OS/Browsers version
win10/chrome 92/npm 7.11.1

### Vue version
3.2.0-beta.7

### Reproduction Link
https://jsfiddle.net/

#### uninstall  element-plus-1.0.2-beta.48
npm uninstall element-plus

#### install element-plus-1.0.2-beta.66
npm install element-plus  

open: node_modules\element-plus\lib\theme-chalk\fonts

"element-icons.ttf"  "element-icons.woff" File size 0KB

### What is Expected?
Font Icon normal use...

### What is actually happening?
Font Icon not working properly...

**Comment by yclgkd** [comment]
I have the same question :disappointed_relieved:

**Comment by liaozheng-yi** [comment]
same question

**Comment by JeremyWuuuuu** [comment]
@YunYouJun Seems like you did something in the gulp file failed to copy the font?

**Comment by JeremyWuuuuu** [comment]
We will address this issue soon and release a hotfix patch. sorry for the inconvenience! :bow:

**Comment by YunYouJun** [comment]
I'm sorry for it. Our patch #2817 will fix this issue soon.

**Comment by lonerwolf** [comment]
> I'm sorry for it. Our patch #2817 will fix this issue soon.

be quick。need update beta 67？

**Comment by YunYouJun** [comment]
> be quick。need update beta 67？

20 minutes later. Upgrade to `beta.67`.

**Comment by lonerwolf** [comment]
> > be quick。need update beta 67？
> 
> 20 minutes later. Upgrade to `beta.67`.

谢谢，查了我一个晚上加早上- -!

**Comment by JeremyWuuuuu** [comment]
> > > be quick。need update beta 67？
> > 
> > 
> > 20 minutes later. Upgrade to `beta.67`.
> 
> 谢谢，查了我一个晚上加早上- -!

发好了，更新一下试试 :bow:
