### ISSUE TITLE
[Bug Report] remote search instance lose its icon in select component

### ISSUE THREAD

**Issue by yclgkd** [element-plus/element-plus#2815]
### Element Plus version
1.0.2-beta.66

### OS/Browsers version
win10/chrome 92

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/yclgkd/pen/zYwLgmq

### Steps to reproduce
It has classNames include `el-select__caret el-input__icon el-icon-` in <i> element, but it is not incorrect. Its classNames should be `el-select__caret el-input__icon el-icon-arrow-up`.

### What is Expected?
The <i> element has a correct icon

### What is actually happening?
The <i> element lost its icon

**Comment by yclgkd** [comment]
![image](https://user-images.githubusercontent.com/31514100/128110776-9b208185-3eb3-476d-a1bd-4f3fed8a37ef.png)

**Comment by Arctic7** [comment]
many components default icons are missing, like NavMenu, Tabs……

**Comment by YunYouJun** [comment]
A hot fix will be released. Just wait a moment.

**Comment by yclgkd** [comment]
> A hot fix will be released. Just wait a moment.

The problem may be long-standing. It's not just in this 66version

**Comment by YunYouJun** [comment]
Do you mean this https://element-plus.org/#/zh-CN/component/select#yuan-cheng-sou-suo?

> https://element.eleme.cn/#/zh-CN/component/select#yuan-cheng-sou-suo same with element-ui

This should not be a bug, the icon is deliberately hidden.

**Comment by yclgkd** [comment]
Without the icon, it looks like an input field.

**Comment by YunYouJun** [comment]
@JeremyWuuuuu @iamkun What do you think?

**Comment by xiaoxian521** [comment]
same: https://github.com/element-plus/element-plus/issues/4985
