### ISSUE TITLE
[Bug Report] The background of cascader component is transparent 

### ISSUE THREAD

**Issue by yclgkd** [element-plus/element-plus#2822]
### Element Plus version
1.0.2-beta.67

### OS/Browsers version
win10/chrome 92

### Vue version
3.2.0-beta.7

### Reproduction Link
https://element-plus.org/#/en-US/component/cascader#basic-usage

### Steps to reproduce
https://element-plus.org/#/en-US/component/cascader#basic-usage
When I click the <select> element,  the component will pop up with a transparent block.

### What is Expected?
The cascader component should have a white background

### What is actually happening?
The background of cascader component is transparent

**Comment by JeremyWuuuuu** [comment]
Should be fixed by now, try upgrade to the newest version. Thank you!
