### ISSUE TITLE
[Bug Report] date-picker, when the type is daterange, the border is missing

### ISSUE THREAD

**Issue by 2h-Lin** [element-plus/element-plus#2825]
### Element Plus version
1.0.2-beta.67

### OS/Browsers version
chrome 92

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/2h-lin/pen/vYmzOVb

### Steps to reproduce
1. open the link https://element-plus.gitee.io/#/zh-CN/component/date-picker
2. find the type is daterange date-picker
3. the border is missing

### What is Expected?
Border is displayed normally

### What is actually happening?
date-pciker border is missing

**Comment by JeremyWuuuuu** [comment]
I think now it has been fixed, you can try visit that site you pasted again, if you still suffer from this please reopen this issue. 

Reminder, you could hit the cache so try `cmd + R` if you are using MacOS, `ctrl + R` if you are using Linux or Windows.
