### ISSUE TITLE
[bug report] for the select component in 'allow create' mode, the options to be created are displayed incorrectly in the options list

### ISSUE THREAD

**Issue by noah19846** [element-plus/element-plus#2826]
### Element Plus version
1.0.2-beta.67

### OS/Browsers version
Mac、win10 / 92

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/noah19846/pen/LYyJVNO

### Steps to reproduce
1. 输入框中输入 foo
2. 输入完毕后观察 options 列表中是否出现 foo 选项
3. 输入一个空格（或者其他任意字符），然后再将空格删除，观察 options 列表中 option 情况
4. options 里终于出现 foo 选项待选

### What is Expected?
1. step 2 应该出现 foo 选项供选择
2. step 3 应该出现 'foo ' 选项供选择
3. 输入框里输入的内容应该及时反馈在 options 列表中

### What is actually happening?
1. step 2 没有出现 foo 选项供选择
2. step 3 没有出现 'foo ' 选项供选择
3. 输入框里输入的内容没有及时反馈在 options 列表中

**Comment by hanx316** [comment]
create an another commit in you repo to fix this and also fix #2854 
yours still have a problem when pressing enter after inputs
