### ISSUE TITLE
[Bug Report] How can I show checkbox only without a label being displayed

### ISSUE THREAD

**Issue by thamibn** [element-plus/element-plus#2838]
### Element Plus version
1.0.2-beta.69

### OS/Browsers version
Chrome

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/thamibn/pen/OJmozaE

### Steps to reproduce
Create checkbox-group with checkboxes setting label make the value being displayed next to the checkbox
i dont wanna show the label i want the checkbox only since i am using it on a table list.

```
<el-checkbox-group v-model="selectedVendors" @change="addVendor">
    <el-checkbox :label="vendor.id" :key="vendor.id" />
</el-checkbox-group>
```

make it not default other someone can show it like below
if I want to show labels i can then do `<el-checkbox>{{ label }}</...> `rather than showing it by default

### What is Expected?
show checkboxes without the labels next to it just like the normal html checkboxes

### What is actually happening?
showing labels next to checkboxes by default

**Comment by CoderMonkie** [comment]
![image](https://user-images.githubusercontent.com/26118847/128283780-66d7a919-0c3a-47d1-8cdb-1813c1e8381f.png)

@thamibn

**Comment by CoderMonkie** [comment]
but, how can I know what the checkbox stands for without a lable..

**Comment by JeremyWuuuuu** [comment]
Same here, why would you want checkbox like that? I think you should use switch BTW, but no matter which component you use you are still going to need a label for the user

**Comment by JeremyWuuuuu** [comment]
I think @CoderMonkie  have already answered your question, if you feel like you need to reopen this issue feel free to do so.

**Comment by thamibn** [comment]
> but, how can I know what the checkbox stands for without a lable..

Thanks for the reply however you can use checkboxes without a label like on tables where you allow users to tick before doing a bulk action.

![Screenshot from 2021-08-05 08-38-04](https://user-images.githubusercontent.com/28577943/128303333-8b7d3466-e203-4304-b3ab-70daab2a2140.png)

so what i want is a list of checboxes like on the table above with their values being vendor.id

so your example wont work without using grouped checkboxes, since a single checkbox does not allow v-model to be an array of values checked values. so for my scenarioo i would need to use a grouped checkboxes

i have just by passed it now by the below code it shows the checboxes without labels on the table list
```
<el-checkbox-group v-model="selectedVendors">
     <el-checkbox :label="vendor.id" :key="vendor.id">&nbsp;</el-checkbox>
 </el-checkbox-group>
```
![Screenshot from 2021-08-05 08-48-11](https://user-images.githubusercontent.com/28577943/128304551-329d2bbb-51dc-47ba-81dd-47e44d47c2bb.png)

**Comment by thamibn** [comment]
> Same here, why would you want checkbox like that? I think you should use switch BTW, but no matter which component you use you are still going to need a label for the user

they are many scenarios out there unfotunately, so thats why i think if you can allow the checboxes to be used without labels by default that will solve this kind problem.

something like below

```
<el-checkbox :label='what ever value' />  //no label will be showned 

//then to show label someone can do it like below
<el-checkbox :label="whatever value">{{ label to be displayed }}</el-checkbox>
```
