### ISSUE TITLE
[bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document

### ISSUE THREAD

**Issue by github2683** [element-plus/element-plus#2841]
### Element Plus version
1.0.2-beta.69

### OS/Browsers version
macos/chrome

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
https://element-plus.gitee.io/#/zh-CN/component/table

### What is Expected?
https://element-plus.gitee.io/#/zh-CN/component/table

### What is actually happening?
比如表格组件里的示例代码 
methods: {
      setCurrent(row) {
        this.$refs.singleTable.setCurrentRow(row);
      },
      handleCurrentChange(val) {
        this.currentRow = val;
      }
    }

如果是高手可能觉得会自己改，但对于我这新手来看，这文档让我头疼不已。各种无效，各种bug。这文档不合格啊。vue3.0里，哪里来的 this.$ref.xxx之类的

**Comment by JeremyWuuuuu** [comment]
@github2683 麻烦自己看截图哈

![image](https://user-images.githubusercontent.com/15975785/128300818-f89dd42e-dd5e-4d1c-8cea-7dc548c990f7.png)

文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。

**Comment by JeremyWuuuuu** [comment]
BTW: [Try it out](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDEgcmVmPVwidGVzdFwiPnt7IG1zZyB9fTwvaDE+XG4gIDxidXR0b24gQGNsaWNrPVwid2hhdFwiPlxuICAgIGNsaWNrTWVcbiAgPC9idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuZXhwb3J0IGRlZmF1bHQge1xuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBtc2c6ICdIZWxsbyBXb3JsZCEnXG4gICAgfVxuICB9LFxuICBtZXRob2RzOiB7XG4gICAgd2hhdCgpIHtcbiAgICAgIGNvbnNvbGUubG9nKHRoaXMuJHJlZnMpXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD4ifQ==)

**Comment by JeremyWuuuuu** [comment]
这边再贴一下文档链接:

[Options API](https://v3.vuejs.org/api/options-api.html)
[Composition API](https://v3.vuejs.org/api/composition-api.html)

**Comment by github2683** [comment]
我以前没用过vue，但我写过很多js。 vue3.0不是说了setup里的this是没有的吗，而且我用vs写代码，也会提示this是未知的，不管提示，直接跑起来，比如el-table的选中方法&nbsp;this.$refs.multipleTable.toggleRowSelection(row);会直接报错。还有就是不是vue3.0说了 不要method了，改成 const xxx = fun();就行，不要mounted了，写在 mounted(fun)就行，，，你们的文档，有些示例是有把代码转成组合api，
比如 





但很多地方又没有转组成api的，比如我使用el-table组件时看的例子。我就不知道怎么调用组件的“选中一行”的方法。示例的代码是：




如果我用 <script lang='ts' setup&gt; ......</script&gt;的方式写，怎么转这个metods里面的两个函数呢? vue3.0的文档是直接没有methods这个属性了，直接写成 const setCurrent = (row)=&gt;{....}


我是想既然用了vue3.0就全部用，不再回头看2.x的东西了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





 
这边再贴一下文档链接:
 
Options API
 Composition API
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamkun** [comment]
![image](https://user-images.githubusercontent.com/17680888/128305685-d31921bd-c8b2-454c-a9f4-11c0e6ec9a2e.png)

Vue.js 3.0 官方文档里居然也有 methods 和 this， 就很离谱 
https://v3.vuejs.org/guide/component-custom-events.html#validate-emitted-events

**Comment by github2683** [comment]
确实是，我又看了一次文档，好多地方有用this，大概理解好像是时序问题，是不是组件没初始化完成就没有this，唉，头大了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





 

 
Vue.js 3.0 官方文档里居然也有 methods 和 this， 就很离谱
 https://v3.vuejs.org/guide/component-custom-events.html#validate-emitted-events
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by github2683** [comment]
不是故意找碴啊，我真不看不懂怎么调用table的method啊，示例里是用 this.$ref.xxxTable 来获得组件实例，然后调用table的方法。但我的代码报错说没有this。
比如说我想点击就调用 setCurrentRow 方法，应该是有一个对象来调用的，如果xxxtable.&nbsp;setCurrentRow(row); &nbsp; 但如何获取到这个xxxtable我不懂。示例里是用vue2.0的方式 &nbsp;xxxtable = this.$ref.xxxtable;









------------------ 原始邮件 ------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





 
@github2683 麻烦自己看截图哈
 

 
文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bastarder** [comment]
> 不是故意找碴啊，我真不看不懂怎么调用table的method啊，示例里是用 this.$ref.xxxTable 来获得组件实例，然后调用table的方法。但我的代码报错说没有this。 比如说我想点击就调用 setCurrentRow 方法，应该是有一个对象来调用的，如果xxxtable.&nbsp;setCurrentRow(row); &nbsp; 但如何获取到这个xxxtable我不懂。示例里是用vue2.0的方式 &nbsp;xxxtable = this.$ref.xxxtable;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "element-plus/element-plus" ***@***.***&gt;; 发送时间:&nbsp;2021年8月5日(星期四) 下午2:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841) @github2683 麻烦自己看截图哈 文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs

**Comment by JeremyWuuuuu** [comment]
> 不是故意找碴啊，我真不看不懂怎么调用table的method啊，示例里是用 this.$ref.xxxTable 来获得组件实例，然后调用table的方法。但我的代码报错说没有this。 比如说我想点击就调用 setCurrentRow 方法，应该是有一个对象来调用的，如果xxxtable.&nbsp;setCurrentRow(row); &nbsp; 但如何获取到这个xxxtable我不懂。示例里是用vue2.0的方式 &nbsp;xxxtable = this.$ref.xxxtable;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "element-plus/element-plus" ***@***.***&gt;; 发送时间:&nbsp;2021年8月5日(星期四) 下午2:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841) @github2683 麻烦自己看截图哈 文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

因为 setup 是没有 this 这个关键字的，Options API 才可以，如果你想用 refs 你需要去参考 refs 的文档，而不是来这里跟我们说这个，我知道文档是有些晦涩，但是按我理解，能在 options 和 composition 中间转换应该是最基本要求吧？
https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs

**Comment by kooriookami** [comment]
使用 setup，不能用this ❌
使用传统的 data、methods，可以用 this ✔️

**Comment by github2683** [comment]
好吧，是我在把option api转 composition api时，没理解清楚



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





 
使用 setup，不能用this ❌
 使用传统的 data、methods，可以用 this ✔️
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by github2683** [comment]
好吧，是我文档没看清楚，没理解清楚。我自己把你们写的option api转composition api的问题，我的错！不好意思！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





  
不是故意找碴啊，我真不看不懂怎么调用table的method啊，示例里是用 this.$ref.xxxTable 来获得组件实例，然后调用table的方法。但我的代码报错说没有this。 比如说我想点击就调用 setCurrentRow 方法，应该是有一个对象来调用的，如果xxxtable.&nbsp;setCurrentRow(row); &nbsp; 但如何获取到这个xxxtable我不懂。示例里是用vue2.0的方式 &nbsp;xxxtable = this.$ref.xxxtable;
 …
 ------------------ 原始邮件 ------------------ 发件人: "element-plus/element-plus" @.&gt;; 发送时间:&nbsp;2021年8月5日(星期四) 下午2:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841) @github2683 麻烦自己看截图哈 文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
因为 setup 是没有 this 这个关键字的，Options API 才可以，如果你想用 refs 你需要去参考 refs 的文档，而不是来这里跟我们说这个，我知道文档是有些晦涩，但是按我理解，能在 options 和 composition 中间转换应该是最基本要求吧？
 https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by github2683** [comment]
算是弄明白了如何调用el-table 组件的setCurrentRow方法。vue2原：
<el-table ref="xxx" &gt; ...... &nbsp;<button @click="toggleSelectRow" &nbsp;..../&gt; &nbsp;</el-table&gt;
<script&gt;
.....
methods:{&nbsp;
toggleSelectRow:(row)=&gt;{this.$ref.xxx.setCurrentRow(row);}
}
</script&gt;


....&gt;&gt;&gt;&gt;&gt;
vue3组合api
<script setup&gt;
//这个时候组件的实例还没有生成
let xxx = ref(null);//变量名称与DOM上的ref属性对应
let table = null;
const toggleSelectRow = (row){&nbsp;
&nbsp; &nbsp; &nbsp;table.setCurrentRow(row);
&nbsp; &nbsp; &nbsp;//或者&nbsp;
&nbsp; &nbsp; // xxx.value.setCurrentRow(row);
}
onMounted(
()=&gt;{
//这个时候组件实例初始化完成了
&nbsp; &nbsp; &nbsp;table = xxx.value;///----之前我一直是 &nbsp;table = xxxx; &nbsp;就是把xxx当table对象用，所以一直提示 setCurrentRow 不存在
}
);
</script&gt;


算是给自己做个笔记吧。变量名称与DOM上的ref属性对应则有效，这让我感觉思路断层。如果是ref的参数与DOM的ref对应还想得通。第一次遇到起变量名称竟然要与某些东西对应，那为何不直接做成一个（当前组件）的环境变量直接用呢。一直都觉得变量名只是为了代码美观易读的，怎么起看自己的。


------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841)





  
不是故意找碴啊，我真不看不懂怎么调用table的method啊，示例里是用 this.$ref.xxxTable 来获得组件实例，然后调用table的方法。但我的代码报错说没有this。 比如说我想点击就调用 setCurrentRow 方法，应该是有一个对象来调用的，如果xxxtable. setCurrentRow(row); &nbsp; 但如何获取到这个xxxtable我不懂。示例里是用vue2.0的方式 &nbsp;xxxtable = this.$ref.xxxtable;
 …
 ------------------ 原始邮件 ------------------ 发件人: "element-plus/element-plus" @.&gt;; 发送时间: 2021年8月5日(星期四) 下午2:18 @.&gt;; @.@.&gt;; 主题: Re: [element-plus/element-plus] [bug report] it is said that vue3.0 is supported. Why is there some code using vue2. X in the document (#2841) @github2683 麻烦自己看截图哈 文档确实可能写的不是很好，希望社区的同学一起来努力把它变得更好。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
因为 setup 是没有 this 这个关键字的，Options API 才可以，如果你想用 refs 你需要去参考 refs 的文档，而不是来这里跟我们说这个，我知道文档是有些晦涩，但是按我理解，能在 options 和 composition 中间转换应该是最基本要求吧？
 https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
