### ISSUE TITLE
[bug report] drawer style CSS var cannot find the variable

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#2848]
### Element Plus version
1.0.2-beta.69

### OS/Browsers version
win10

### Vue version
3.2.0-beta.7

### Reproduction Link
http://github.com

### Steps to reproduce
![image](https://user-images.githubusercontent.com/1574903/128357968-e70ca371-a4b1-4763-8494-8d9e46eb2627.png)

### What is Expected?
/

### What is actually happening?
/

**Comment by YunYouJun** [comment]
Thanks. I will fix it.
