### ISSUE TITLE
[bug report] El select, when there is no drop-down list and no data, enter a new entry, which will appear only after being deleted back for you to select

### ISSUE THREAD

**Issue by leslieDD** [element-plus/element-plus#2854]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Win10/Chrome

### Vue version
3.2.0-beta.7

### Reproduction Link
https://codepen.io/lesliedd-the-sasster/pen/gOWBWBq

### Steps to reproduce
el-select中，当下拉列表没有数据的时候，这时想创建新字段，需要在输入数据时，往回删，才可以在下拉框中显示，并供选择，如果继续输入，下拉框中双不显示了

el-select中，When there is no data in the drop-down list, if you want to create a new field, you need to delete it back when entering data then it can be displayed and selected in the drop-down box. If you continue to enter, it will not be displayed in the drop-down box

### What is Expected?
因为允许创建字段，所以新输入数据时，任何时候都应该可供选择，完成新字段的创建
Because it is allowed to create fields, you should be able to select new data at any time to complete the creation of new fields

### What is actually happening?
el-select，没有下拉列表没有数据的时候，输入新条目，要往回删才会出现，让你选择
el-select, When there is no drop-down list and no data, enter a new item and it will appear only after you delete it back for you to select

gif: 
![ezgif-1-6eae1b5012b1](https://user-images.githubusercontent.com/5474698/128456395-c2116348-d0f3-4d93-b334-60522be938ca.gif)

**Comment by hanx316** [comment]
fixed by https://github.com/element-plus/element-plus/pull/2830
