### ISSUE TITLE
[Feature Request] Drawer docs comfirm button haven't text

### ISSUE THREAD

**Issue by 787352714** [element-plus/element-plus#2857]
### Existing Component
Yes

### Component Name
docs（Drawer）

### Description
Drawer docs comfirm button haven't text

**Comment by 787352714** [comment]
![image](https://user-images.githubusercontent.com/18625708/128497016-d8ce10ae-1167-4251-b6c6-2c22a0b71d66.png)

**Comment by 787352714** [comment]
pull Request #2856

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/128541464-cc42004c-c921-4283-9243-2942c03c139b.png)

emm, It seems that I can see the text, even if it is not set.

**Comment by 787352714** [comment]
sry，I can't reproduce i,I will close the issue
