### ISSUE TITLE
[bug report] pagination cannot be displayed normally

### ISSUE THREAD

**Issue by LeeSamFong** [element-plus/element-plus#2862]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
win10 / Chrome 92.0.4515.131

### Vue version
3.1.5

### Reproduction Link
https://github.com/LeeSamFong/test-element-plus

### Steps to reproduce
1.完整引入的element-plus

2.最简单的pagination组件使用

### What is Expected?
pagination组件能正常的展示

### What is actually happening?
`1.0.2-beta.55`以前包括`55`版本都是正常没问题的，

但在`55`版本之后，包括最新的`70`版本，
使用`pagination`不显示，以及在控制台输出了`ElementPlusError: [ElPagination] undefined的warning`

**Comment by feenn** [comment]
@LeeSamFong 我也遇到这个问题了，请问您是怎么解决的？谢谢！

**Comment by LeeSamFong** [comment]
> @LeeSamFong我也遇到了问题了，请问您是怎么解决的？谢谢！

请问方便把Pagination组件这块的代码放上来吗？

**Comment by LeeSamFong** [comment]
> @LeeSamFong我也遇到了问题了，请问您是怎么解决的？谢谢！

如果不方便的话，请问你在Pagination组件中，有没有使用`v-model:current-page`、`v-model:page-size`或者是`@current-change`与`@size-change`？

**Comment by LeeSamFong** [comment]
**PS：目前使用Pagination需要注意**

如果使用`v-model`的话，请注意目前该组件中只能使用`v-model:currentPage`这种驼峰写法。
这是由于组件内部做了一些判断，但只判断了驼峰写法，没有判断`v-model:current-page`这种连字符写法
如果不使用`v-model`，则必须监听`@current-change`的事件。
`v-model:current-page`这种写法的兼容，已经通过PR提交给官方

**详情：[https://github.com/element-plus/element-plus/pull/2884](https://github.com/element-plus/element-plus/pull/2884)**

**Comment by feenn** [comment]
@LeeSamFong  确实是连字符写法的问题．感谢您！
