### ISSUE TITLE
[feature request] can a slot named label be added to the form item, similar to element UI 2. X, or the label text can be embedded < br > and displayed as a newline.

### ISSUE THREAD

**Issue by yuanjinyong** [element-plus/element-plus#2870]
### Existing Component
Yes

### Component Name
FormItem

### Description
Form-Item能否增加具名为label的slot，类似Element UI 2.x的，或者label的文本支持嵌入<br>显示成换行。

**Comment by kooriookami** [comment]
You can use like this.
```vue
  <el-form-item>
    <template #label>
      <div>123</div>
      <div>123</div>
    </template>
    <el-input v-model="form.name"></el-input>
  </el-form-item>
```

**Comment by yuanjinyong** [comment]
Thanks. This feature already exist, but section "Form-Item Slot" in the doc https://element-plus.gitee.io/#/zh-CN/component/form doesn't description this.
I have tried  template #label, it work ok.
