### ISSUE TITLE
[Bug Report] Datepicker uses font-icons which cannot be rendered

### ISSUE THREAD

**Issue by ythomop** [element-plus/element-plus#2874]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Chromium 92.0.4515.131 / Linux 5.13.8 

### Vue version
3.1.0

### Reproduction Link
https://codesandbox.io/s/lucid-keldysh-x8u79?file=/src/main.js

### Steps to reproduce
1. Insert a DatePicker element
2. See icons not being rendered

### What is Expected?
Icons should be rendered.

### What is actually happening?
No icons are rendered. The same issue should exist in all components that use font icons.

**Comment by iamkun** [comment]
relate to #2871

**Comment by ythomop** [comment]
I managed to fix this locally by adding these lines to my main.ts (entry point):
## main.ts:
```
import "element-plus/packages/theme-chalk/src/index.scss";
import "@/assets/index.scss";
```

## @/assets/index.scss:
```
$--font-path: "~element-plus/lib/theme-chalk/fonts";
```

However, I cannot do the same in the codesandbox. I get the following error:

```
Error
Error: I.getInterceptor$x(...) is undefined
```

Anyways, I consider my issue resolved.

**Comment by iamkun** [comment]
I've downloaded your codesandbox project to my local machine, and the font-icon seems fine.

![image](https://user-images.githubusercontent.com/17680888/128634922-784cc0e3-422d-449c-97f5-48a4cf8b2468.png)
