### ISSUE TITLE
[Bug Report] Horizontal el-menu with el-submenu not working as expected when menu-trigger="click"

### ISSUE THREAD

**Issue by purepear** [element-plus/element-plus#2875]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
MacOS, Chrome 92

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/4f08wuyn/

### Steps to reproduce
```
<el-menu mode="horizontal" menu-trigger="click">
  <el-submenu index="1">
    <template #title>Submenu 1</template>
    
    <el-submenu index="1-1">
      <template #title>Submenu 1-1</template>
      <el-menu-item index="1-1-1">Item 1-1-1</el-menu-item>
      <el-menu-item index="1-1-2">Item 1-1-2</el-menu-item>
    </el-submenu>
    
    <el-submenu index="1-2">
      <template #title>Submenu 1-2</template>
      <el-menu-item index="1-2-1">Item 1-2-1</el-menu-item>
      <el-menu-item index="1-2-2">Item 1-2-2</el-menu-item>
    </el-submenu>
  </el-submenu>
  <el-menu-item index="2">Item 1</el-menu-item>
  <el-menu-item index="3">Item 2</el-menu-item>
</el-menu>
```

![demo](https://user-images.githubusercontent.com/144010/128622483-041dfb2b-753f-4fe8-b437-b948110246be.gif)

### What is Expected?
* Clicking on one submenu should close the other open submenus
* Clicking outside of the menu should close the whole menu

### What is actually happening?
* Clicking on submenu opens it on top of the already opened one. The only way to close the other menus is to click on them again.
* Clicking outside of the menu does not close the menu. The only way to close it  is to click on the parent submenu again.

**Comment by Dreamerryao** [comment]
I'll try to solve this.

**Comment by Dreamerryao** [comment]
You can just add attribute `unique-opened="true"` to fix the problem. @purepear

**Comment by purepear** [comment]
Thank you so much @Dreamerryao 🙇 
I don't know how i missed this prop 🤦 , my bad.

This solves the first issue! Do you have any idea about the second one (clicking outside of the menu doesn't close it)? Or is it not closing by design (is it a bug or a feature :) )?

**Comment by Dreamerryao** [comment]
I see, and I'm not advocating that components encapsulate such actions.
I think components should not be aware of global actions.
And you can simply call `close` methods to finish it.

**Comment by purepear** [comment]
Thanks for your help @Dreamerryao! I will close the issue as it seems that this is not a bug but a feature :) If i end up manually adding "close on click away" functionality, i'll share my solution here.
