### ISSUE TITLE
There is an extra 0 after the total line of the [bug report] table component

### ISSUE THREAD

**Issue by thang009** [element-plus/element-plus#2876]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Safari

### Vue version
3.2.0-beta.8

### Reproduction Link
https://element-plus.gitee.io/#/zh-CN/component/table

### Steps to reproduce
在table组件添加show-summary自动合计之后会多出一个0

### What is Expected?
合计按照正常方式显示

### What is actually happening?
合计行会多一个0

**Comment by Dreamerryao** [comment]
有复现地址么

**Comment by thang009** [comment]
> 有复现地址么

示例里面就有了。

**Comment by thang009** [comment]
示例里面就有了

<img width="846" alt="WX20210811-154434@2x" src="https://user-images.githubusercontent.com/8577380/128990245-2c250c15-bead-476f-abfd-d2e2903d9f38.png">
> 有复现地址么

**Comment by thang009** [comment]
> 系统&浏览器版本

macos 11.5
