### ISSUE TITLE
[Bug Report] CSS var cannot find the variable

### ISSUE THREAD

**Issue by svendehens** [element-plus/element-plus#2880]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
macOS Big Sur

### Vue version
3.2.0-beta.8

### Reproduction Link
http://github.com

### Steps to reproduce
Although the theme seems to be fully loaded, a lot of the css var's aren't defined. Both for Datepicker, ElSelect, Elmessage, only partial styles seem to be loaded. Is this a bug, or am I missing something?
<img width="543" alt="Schermafbeelding 2021-08-08 om 20 52 58" src="https://user-images.githubusercontent.com/63284017/128642876-f84511a4-0646-4105-9ad4-e3b60f1f818e.png">

### What is Expected?
//

### What is actually happening?
//

**Comment by gzf6** [comment]
> ### Element Plus version
> 1.0.2-beta.70
> 
> ### OS/Browsers version
> macOS Big Sur
> 
> ### Vue version
> 3.2.0-beta.8
> 
> ### Reproduction Link
> [http://github.com](https://github.com)
> 
> ### Steps to reproduce
> Although the theme seems to be fully loaded, a lot of the css var's aren't defined. Both for Datepicker, ElSelect, Elmessage, only partial styles seem to be loaded. Is this a bug, or am I missing something?
> <img alt="Schermafbeelding 2021-08-08 om 20 52 58" width="543" src="https://user-images.githubusercontent.com/63284017/128642876-f84511a4-0646-4105-9ad4-e3b60f1f818e.png">
> 
> ### What is Expected?
> //
> 
> ### What is actually happening?
> //

Maybe need `import 'element-plus/packages/theme-chalk/src/base.scss'`

**Comment by dmytropryshliak** [comment]
Also vars related to the table component are missing.
