### ISSUE TITLE
[feature request] can I use the elscrollbar scroll bar when setting the fixed header through height in the eltable component

### ISSUE THREAD

**Issue by vaas1993** [element-plus/element-plus#2881]
### Existing Component
Yes

### Component Name
ElTable、ElScrollbar

### Description
使用ElScrollbar替代了windows的默认滚动条，但是ElTable里的滚动条无法取代掉，导致风格严重不一致

**Comment by kooriookami** [comment]
same #2882

**Comment by sxzz** [comment]
Duplicate of https://github.com/element-plus/element-plus/issues/2881
