### ISSUE TITLE
[feature request] scroll bar optimization in table component

### ISSUE THREAD

**Issue by ketao4869** [element-plus/element-plus#2882]
### Existing Component
是

### Component Name
el-table

### Description
现在不是有一个Scrollbar 滚动条组件吗，这个样式挺好的，能否把他放到table组件中。因为table组件是浏览器的滚动条样式。如果为了table的样式而写css改变浏览器默认滚动条样式，那么Scrollbar 组件又有什么用

**Comment by zhazhanitian** [comment]
Very reasonable proposal. I will try to solve this problem as soon as possible

**Comment by ketao4869** [comment]
> 非常合理的提议。我会尽快解决这个问题

加油，等你

**Comment by xiaoxian521** [comment]
The latest version has been implemented
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/44761321/181688198-f1f5a217-75b2-4a66-a8d7-9f4d4859584e.png">
