### ISSUE TITLE
[Bug Report] Some tags are not recognized by webstorm

### ISSUE THREAD

**Issue by OneSeven** [element-plus/element-plus#2891]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
windows/chrome

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/as

### Steps to reproduce
Only found ``` <el-main>``` for the time being 
There may be others

### What is Expected?
Hope to fix it. Starting from element-ui2, it is all ide friendly. I hope it can be maintained, thanks

### What is actually happening?
some tags are not recognized by webstorm

![fff](https://user-images.githubusercontent.com/17974392/128714097-de040498-096c-4032-8965-ebdc29f047f3.png)

**Comment by zhazhanitian** [comment]
Hello, this problem should belong to webstorm, and webstorm has provided the corresponding solution. You can try to use plug-in or IDE settings to solve this problem

**Comment by OneSeven** [comment]
> Hello, this problem should belong to webstorm, and webstorm has provided the corresponding solution. You can try to use plug-in or IDE settings to solve this problem

This requires developers to complete, please refer to
https://github.com/JetBrains/web-types
Https://cdn.jsdelivr.net/npm/naive-ui@2.16.2/web-types.json

I also hope to check, after all, there is no problem with element-ui2.
If it is done through web-types, there will be no props prompt when sfc imports components separately. It is best if you can maintain the element-ui2 method，Thanks

**Comment by tolking** [comment]
Now it is the `web-types.json` generated according to the document.

I find the `el-container` in [web-types.json](https://unpkg.com/element-plus@1.0.2-beta.70/lib/web-types.json) but i can not find the `el-main`.

so I suggest you check your plugin and IDE settings first.

**Comment by OneSeven** [comment]
> Now it is the `web-types.json` generated according to the document.
> 
> I find the `el-container` in [web-types.json](https://unpkg.com/element-plus@1.0.2-beta.70/lib/web-types.json) but i can not find the `el-main`.
> 
> so I suggest you check your plugin and IDE settings first.

I just lack el-main, and everything else is normal. Did you lack it when you generated the web-types.json file?

**Comment by zhazhanitian** [comment]
> I just lack el-main, and everything else is normal. Did you lack it when you generated the web-types.json file?

This lack should not be much and is inevitable, so it's OK to add it manually when you encounter it

**Comment by OneSeven** [comment]
> > I just lack el-main, and everything else is normal. Did you lack it when you generated the web-types.json file?
> 
> This lack should not be much and is inevitable, so it's OK to add it manually when you encounter it

Can you fix it? Although it can be manually specified, it is a bit obsessive-compulsive. I hope it can be done perfectly. :wink:

**Comment by tolking** [comment]
> Can you fix it? Although it can be manually specified, it is a bit obsessive-compulsive. I hope it can be done perfectly. 😉

Just add a description of el-main in the document.

**Comment by OneSeven** [comment]
> > Can you fix it? Although it can be manually specified, it is a bit obsessive-compulsive. I hope it can be done perfectly. 😉
> 
> Just add a description of el-main in the document.

Thank you very much, you may need to check and repair the document again. At present, I have encountered that the ``` el-submenu ``` component document does not declare slots. There may be many component documents that are not complete. It is recommended to keep the issue until the repair is completed. :pray:

**Comment by tolking** [comment]
There are many components missing default slots descriptions in the documents. It is not necessary, but it is more conducive to the generation of code hint files. @JeremyWuuuuu need to do it now?

**Comment by Xwudao** [comment]
> There are many components missing default slots descriptions in the documents. It is not necessary, but it is more conducive to the generation of code hint files. @JeremyWuuuuu need to do it now?

Thanks, Why do I use element-ui instead of antdv or other ui, it is the out-of-the-box webstorm tag prompt.

Please fix it. 🙏
