### ISSUE TITLE
[Bug Report] css repeat in index.css

### ISSUE THREAD

**Issue by llk2yq** [element-plus/element-plus#2894]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
win 10 / edge 92

### Vue version
3.1.5

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
open https://unpkg.com/element-plus@1.0.2-beta.70/lib/theme-chalk/index.css or open the index.css file in node_modules
search `el-input-small`
you will find so much result in the file

### What is Expected?
index.css 不重复

### What is actually happening?
index.css因为重复，所以该文件达到700kb ，导致打包后的体积也非常大（全局引入）。测试64版本没有这个问题，65开始有这个问题。

**Comment by L-linc** [comment]
same problem.some css is not repeated, but some is repeated 7-8 times.(eg. el-button)

**Comment by kooriookami** [comment]
It has been fixed.
Please refer to https://github.com/element-plus/element-plus/discussions/3020
