### ISSUE TITLE
how use icon attribute for el-button if replacing all font icon with svg icon in future

### ISSUE THREAD

**Issue by icksky** [element-plus/element-plus#2898]
In the documents, I see I should use it like this:
```html
<el-button type="primary">
  <el-icon style="vertical-align: middle;">
    <search />
  </el-icon>
  <span style="vertical-align: middle;">
    Search
  </span>
</el-button>
```
and not like this:
```html
<el-button type="primary" icon="search">
   Search
</el-button>
```

**The new way of using it is so inconvenient**

**Comment by zhixiaotong** [comment]
我也想开一个issue问呢，等解决方式，目前的迁移成本太高了。el-button和el-dropdown-item等，改代码一大堆

**Comment by thetime50** [comment]
A lot of components need to be registered

**Comment by chunjine** [comment]
I want to know the reason of transfer from font icon to svg icon？
import each icon when used?

**Comment by sxzz** [comment]
@thetime50 I will add a auto import preset to https://github.com/antfu/unplugin-vue-components in the future.

**Comment by banlify** [comment]
> > A lot of components need to be registered
> 
> I will add an auto import preset to https://github.com/antfu/unplugin-vue-components in the future.

您好, 在使用了 unplugin-vue-components 自动引入组件包以后, 我该如何设置全局配置呢? 比如 z-index/size 等

**Comment by banlify** [comment]
> > > 很多组件需要注册
> > 
> > 
> > 将来我会在https://github.com/antfu/unplugin-vue-components中添加一个自动导入预设。
> 
> 你好，在使用了 unplugin-vue-components 自动引入组件包以后，我该如何设置配置呢？例如 z-index/size 等

还是说这个配置后续会通过 el-config-provide 来提供配置信息的支持呢?

**Comment by sxzz** [comment]
@banlify 请参阅文档 https://element-plus.org/zh-CN/guide/quickstart.html#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE，后续也会在 `el-config-provider` 提供

```js
import { createApp } from 'vue'
import { ElButton } from 'element-plus'
import App from './App.vue'

const app = createApp(App)
app.config.globalProperties.$ELEMENT = {
  // options
}
app.use(ElButton)
```

**Comment by sxzz** [comment]
https://codepen.io/sxzz/pen/GRMgavo
