### ISSUE TITLE
Elmessage.closeall reports CTX error after packaging

### ISSUE THREAD

**Issue by sinsy** [element-plus/element-plus#2914]
![2975ebb02e464a9e704a88162c23c8f](https://user-images.githubusercontent.com/4956934/129132600-822ff6c8-1cf6-4468-b0bc-5be075873ed2.png)
element-plus message.ts源码中使用改了ctx，ctx在打包后无法找到对象，要换成proxy

**Comment by LilyWangxl** [comment]
我也遇到了这个问题

**Comment by sxzz** [comment]
I will fix it later.
