### ISSUE TITLE
slider can not drag

### ISSUE THREAD

**Issue by wuxj00** [element-plus/element-plus#2917]
Vue: vue@3.1.5 
element-plus: element-plus@1.0.2-beta.70
platform: mac
node version: v14.17.3

模板： 
<template>
  <el-slider
    v-model="rangeVal"
    :min="0"
    :max="180"
    :step="1"
    range>
  </el-slider>
</template>

当用setup时，slider不能拖拽
<script lang="ts">
import { defineComponent, reactive } from 'vue'
export default defineComponent({
  setup () {
    const rangeVal = reactive([40, 80])
    return {
      rangeVal
    }
  }
})
</script>

当采用vue2 data语法时，可以拖拽

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  data () {
    return {
      rangeVal: [40, 80]
    }
  },
})
</script>

**Comment by kooriookami** [comment]
Use `ref` instead of `reactive`.
