### ISSUE TITLE
[Bug Report] Custom themes are not working

### ISSUE THREAD

**Issue by lqsong** [element-plus/element-plus#2919]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
win

### Vue version
3.2.2

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-wrux3?file=/src/element-variables.scss

### Steps to reproduce
/* theme color */ $--color-primary: teal; 
/* icon font path, required */
$--font-path: '~element-plus/lib/theme-chalk/fonts'; 
@import "~element-plus/packages/theme-chalk/src/index";

### What is Expected?
success

### What is actually happening?
error

**Comment by wilhantian** [comment]
$--font-path: '~element-plus/lib/theme-chalk/fonts';"
change to
$--font-path: '~element-plus/theme-chalk/fonts';"
