### ISSUE TITLE
The sass custom style variable imported in [bug report] prependdata is invalid

### ISSUE THREAD

**Issue by webliving** [element-plus/element-plus#2920]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
mac os

### Vue version
3.2.2

### Reproduction Link
https://codepen.io/webliving/pen/oNZrrNG

### Steps to reproduce
1.  vue.config.js

sass: {
        prependData:
          "$--font-path: '~element-plus/lib/theme-chalk/fonts'; @use './src/styles/variables.scss' as *;",
      }

2. variables.scss

$red: #f00;
/* 改变主题色变量 */
$--color-primary: #f00; 
$--font-path: "~element-plus/lib/theme-chalk/fonts";
@import "~element-plus/packages/theme-chalk/src/button";

3. main.ts

import { ElButton, ElSelect, ElOption, ElCol } from "element-plus";
import "element-plus/packages/theme-chalk/src/base.scss";

const app = createApp(App);
app.component(ElCol.name, ElCol);
app.component(ElButton.name, ElButton);
app.component(ElSelect.name, ElSelect);
app.component(ElOption.name, ElOption);

### What is Expected?
$--color-primary 可以生效

### What is actually happening?
$--color-primary 没有生效

**Comment by gtbl2012** [comment]
same problem

**Comment by L-775** [comment]
https://github.com/element-plus/element-plus/blob/7fb574a1616a5e8083cc1c4f6fe823f24c01adf2/packages/theme-chalk/src/common/var.scss#L45

css var之前的代码：
$--color-primary: #409EFF !default;

现在的代码：
$--color-primary: map.get($--colors, 'primary', 'base');

因为缺失了  !default

当前如果需要使用自定义颜色的话。直接改css变量 --el-color-primary 吧。
或者拉一份源码下来自己打包css

**Comment by kooriookami** [comment]
@YunYouJun Can you look at this

**Comment by yizhiyan** [comment]
我遇到同样的问题了，什么时候修复啊，我现在只能手动更改var.scss，这样我换个电脑就又不行了
![image](https://user-images.githubusercontent.com/33596562/129720756-9d0147a0-72a5-47bf-be1c-9182c9e3914f.png)
应该更改为
![image](https://user-images.githubusercontent.com/33596562/129720871-66094876-a326-4778-8722-b9482857c16c.png)

**Comment by webliving** [comment]
> https://github.com/element-plus/element-plus/blob/7fb574a1616a5e8083cc1c4f6fe823f24c01adf2/packages/theme-chalk/src/common/var.scss#L45
> 
> css var之前的代码：
> $--color-primary: #409EFF !default;
> 
> 现在的代码：
> $--color-primary: map.get($--colors, 'primary', 'base');
> 
> 因为缺失了 !default
> 
> 当前如果需要使用自定义颜色的话。直接改css变量 --el-color-primary 吧。
> 或者拉一份源码下来自己打包css。
> 
> 也可以尝试直接设置 $--colors 下（$--colors加了 !default）
> $--colors: (
> (
> 'primary': (
> 'base': #{xxxxxx},
> ),
> )
> );


也可以尝试直接设置 $--colors 下 , 这个试了, 好象没试出效果, 可能姿势不对 😃

**Comment by YunYouJun** [comment]
Hello, style system of element-plus is breaking.
We will introduce a new way to use sass variables or css var. (In order to maintain the unity of the two, we refactored using map.)
Unfortunately, the main work has been basically completed, but the migration document is not yet ready. We will complete the content of the document in the next two weeks.
> If you want to know when, just subscribe https://github.com/element-plus/element-plus/issues/2242.

You can use this method to change the colors. （import it before `base.scss`）.

```scss
$--colors: (
  "primary": (
    "base": #003261,
  ),
  "success": (
    "base": #21ba45,
  ),
  "warning": (
    "base": #f2711c,
  ),
  "danger": (
    "base": #db2828,
  ),
  "error": (
    "base": #db2828,
  ),
  "info": (
    "base": #42b8dd,
  ),
);

// this is also ok
$--colors: (
  "primary": (
    "base": #003261,
  )
);
```

Or just set `--el-color-primary` for them!

```css
:root {
  --el-color-primary: #fff;
}
```

**Comment by pdsuwwz** [comment]
> Hello, style system of element-plus is breaking.
> We will introduce a new way to use sass variables or css var. (In order to maintain the unity of the two, we refactored using map.)
> Unfortunately, the main work has been basically completed, but the migration document is not yet ready. We will complete the content of the document in the next two weeks.
> 
> > If you want to know when, just subscribe #2242.
> 
> You can use this method to change the colors. （import it before `base.scss`）.
> 
> ```css-scss
> $--colors: (
>   "primary": (
>     "base": #003261,
>   ),
>   "success": (
>     "base": #21ba45,
>   ),
>   "warning": (
>     "base": #f2711c,
>   ),
>   "danger": (
>     "base": #db2828,
>   ),
>   "error": (
>     "base": #db2828,
>   ),
>   "info": (
>     "base": #42b8dd,
>   ),
> );
> 
> // this is also ok
> $--colors: (
>   "primary": (
>     "base": #003261,
>   )
> );
> ```
> 
> Or just set `--el-color-primary` for them!
> 
> ```css
> :root {
>   --el-color-primary: #fff;
> }
> ```

I just found that it works, but if you change it to this way, how to use variables in `<style>` in vue ?

**Comment by YunYouJun** [comment]
> I just found that it works, but if you change it to this way, how to use variables in <style> in vue ?

Do you mean sass or css?

sass just use `map.get($--colors, 'primary', 'base')`

css can use

```js
getComputedStyle(document.documentElement).getPropertyValue(
  `--el-color-${type}`,
)
```

**Comment by pdsuwwz** [comment]
> Do you mean sass or css?
> 
> sass just use `map.get($--colors, 'primary', 'base')`
> 
> css can use
> 
> ```js
> getComputedStyle(document.documentElement).getPropertyValue(
>   `--el-color-${type}`,
> )
> ```

Great, thank you for your reply.

**Comment by YunYouJun** [comment]
I think it has been solved, so i will close it.
If you want to know more about variable, please ref https://github.com/element-plus/element-plus/issues/2242. Thanks.
