### ISSUE TITLE
The [bug report] tabs component currently activates the active bar of the tab

### ISSUE THREAD

**Issue by bwangs** [element-plus/element-plus#2926]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
chrome v92.0.4515.131

### Vue version
3.2.2

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-uo2rj?file=/src/App.vue

### Steps to reproduce
新增多个tab，数量越多越明显

### What is Expected?
渲染较多数量的tab时，active-bar不错位

### What is actually happening?
在计算active-bar的位置的时候，el使用了clientWidth字段来算active-bar的偏移量，但是tab-item的width多数情况下为小数，clientWidth的值是一个整数，这样每一个tab都会出现不足1px的偏差，当tab的数量多了之后这个偏差就会积累的比较明显
![image](https://user-images.githubusercontent.com/29780591/129344346-37959a1f-8024-4f3e-aa82-80a940d0abe9.png)

**Comment by Alanscut** [comment]
这么改页面确实没有了微小偏移。不过tabs.spec.ts中测试用例会报错，
![image](https://user-images.githubusercontent.com/21104054/129862911-fe394ed7-38a9-4d88-aefa-b7c37ebd80f5.png)
