### ISSUE TITLE
[bug report] [El select] when you select radio and create an item, you can't re create the item by entering text after creating and rotating the first item. You must enter a character and then delete another character before you can generate a new entry

### ISSUE THREAD

**Issue by gowiny** [element-plus/element-plus#2927]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
window 10 / firefox 91.0

### Vue version
3.2.2

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
el-select 组件，设置为允许创建条目，并设置为单选，第一次能正常创建条目，但创建完第一次条目后再输入文字，就无法正常创建，需要往前删除一个字符，才能正常创建条目。

<template>
  <el-select
    v-model="value"
    filterable
    allow-create
    default-first-option
    placeholder="请选择文章标签">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
    </el-option>
  </el-select>
</template>

<script>
  export default {
    data() {
      return {
        options: [{
          value: 'HTML',
          label: 'HTML'
        }, {
          value: 'CSS',
          label: 'CSS'
        }, {
          value: 'JavaScript',
          label: 'JavaScript'
        }],
        value: []
      }
    }
  }
</script>

### What is Expected?
预期：应该是不管创建了几次条目，再次输入字符后应该能正常创建条目

### What is actually happening?
实际是：第一个条目能正常创建，但再次输入文字后，就无法正常创建条目了。需要输入完字符后，往前删除一个字符才能创建条目

**Comment by Alanscut** [comment]
i can't reproduce your issue. there is no problem here.
https://jsfiddle.net/zL0qncrd/
are you sure about this issue?
maybe you can create a simple demo page with : 
https://codepen.io/iamkun/pen/YzWMaVr
or
https://jsfiddle.net/iamkun/ods20k7t/
or
https://codesandbox.io/s/element-plus-spa-ms973?file=/src/App.vue

**Comment by gowiny** [comment]
演示地址：https://codepen.io/gowiny/pen/rNmgwPB
你可以先输入 中国，然后回车，可以正常创建
然后再点开，输入大家好，就无法创建，需要把最后一个好字删除，才能创建

**Comment by Alanscut** [comment]
@gowiny 你这个演示项目代码少了个`multiple`属性，
![image](https://user-images.githubusercontent.com/21104054/129680985-c639be5d-95a6-46d4-a341-c0e0f4569b8e.png)
我这边加上multiple属性之后，是正常。你用的是什么浏览器，什么版本呢。

https://user-images.githubusercontent.com/21104054/129681887-af095c0e-0bdc-41ff-bae2-4ed832e895c5.mp4

**Comment by Alanscut** [comment]
GitHub上视频在线看我这边好像有问题，你可以下载一下

**Comment by gowiny** [comment]
是的，我说的问题，就是不设置multiple 的时候，就有问题，设置为多选是正常的，设置为默认的单选模式，就有问题了

**Comment by Alanscut** [comment]
确实，单选情况确实有问题

**Comment by Alanscut** [comment]
@gowiny 

https://user-images.githubusercontent.com/21104054/129718679-2302549f-c762-4a80-a88a-c71be4be9770.mp4

你也克隆下来打包然后本地引用试一下，可能是某个pr已经解决了
