### ISSUE TITLE
[Bug Report] allow-drop send incorret type in Tree component

### ISSUE THREAD

**Issue by programulin** [element-plus/element-plus#2932]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Chrome 92.0.4515.131

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/zt370v5o/3/

### Steps to reproduce
1. Open jsfiddle link and open console
2. Try drag some element on other
3. See strange logs like:
"9 7 next"
"9 7 prev"
"9 7 inner"
"9 7 next"
"9 7 prev"
"9 7 inner"

### What is Expected?
I expect that i get or only 1 type of event in one moment, or get all 3 types, but for different ids. How event can be a prev, next and inner for single node at same time?

### What is actually happening?
I see 3 events for same node.

**Comment by Alanscut** [comment]
i think you have a wrong understanding. this method (`onDrop(drag, drop, type)`) is use to control if the draggingNode can be move to the 3 types position of dropNode.
the function is not use to show  state of draggingNode with your mouse pointer, 
just like this 
![image](https://user-images.githubusercontent.com/21104054/129535156-6ba1e405-e51e-4906-b3d4-a7486355b049.png)
your can control the node can not move to  inner of ohter nodes.
