### ISSUE TITLE
[Bug Report] yarn build

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#2946]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
windows:版本	Windows 10 专业版 版本号	20H2 安装日期	‎2021/‎6/‎21 操作系统内部版本	19042.1165 体验	Windows Feature Experience Pack 120.2212.3530.0.  yarn version: 1.22.11

### Vue version
3.1.5

### Reproduction Link
https://github.com/element-plus/element-plus.git

### Steps to reproduce
git clone https://github.com/element-plus/element-plus.git; 
yarn install ; 
yarn build;  

### What is Expected?
build with no error,
and use local element-plus lib with no error.

### What is actually happening?
yarn build is report lots of errors

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/129508843-71b09157-8d9e-4451-968c-6c3dd2c1f631.png)
![image](https://user-images.githubusercontent.com/21104054/129508855-e03810ca-cda2-4642-8b9f-8ad4579a25ff.png)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/129508903-b6b28261-905a-4df2-8057-a2c8506578a9.png)

**Comment by Alanscut** [comment]
`vue create demo1`;
`yarn add E:\projects\element-plus`;
**create a page wiht el-input;**
it will be error in browser
![image](https://user-images.githubusercontent.com/21104054/129521141-e9444c36-5271-4bf7-a6f2-f97543c946cc.png)

**Comment by kooriookami** [comment]
Could you delete the node_modules and install again?

**Comment by Alanscut** [comment]
ok,i will do it temorrow

**Comment by Alanscut** [comment]
git clone 
yarn install
yarn build
still have error:
![image](https://user-images.githubusercontent.com/21104054/130710982-b0351eef-b460-41a7-a45c-c35ecb51dd55.png)
![image](https://user-images.githubusercontent.com/21104054/130712696-27dcc448-51f8-41cc-8507-c1c68d4a532f.png)

by the way, 'yarn build' is too slowly in my machine, it always take more than 40 minitues

**Comment by sxzz** [comment]
Hi, have you solved the problem?
please try (for Linux/macOS)
```
rm -fr node_modules
git pull origin dev
yarn bootstrap
yarn build
```

**Comment by Alanscut** [comment]
my machine is win10
and i create a new folder
`git clone ...`
then 
`yarn bootstrap`
`yarn build`
get this error again
![image](https://user-images.githubusercontent.com/21104054/131474632-75dd73ec-3d2f-4ce7-bb74-fa8839cee290.png)
```
$ rollup --config ./build/rollup.config.bundle.js && yarn build:type
[!] Error: Could not resolve entry module (build\rollup.config.bundle.js).
Error: Could not resolve entry module (build\rollup.config.bundle.js).
    at error (E:\projects\element-test\element-plus\node_modules\rollup\dist\shared\rollup.js:5210:30)
    at ModuleLoader.loadEntryModule (E:\projects\element-test\element-plus\node_modules\rollup\dist\shared\rollup.js:18295:16)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by sxzz** [comment]
please reference `scripts/monorepo.sh`

**Comment by Alanscut** [comment]
follow` scripts/monorepo.sh`
when i run  `yarn build:style`
get the error: 
![image](https://user-images.githubusercontent.com/21104054/131793480-69d3b436-f7d3-42fb-a36e-7adda06c0fb6.png)
```
E:\projects\element-test\element-plus\build\gulpfile.ts:1
import gulp from 'gulp'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireOrImport (E:\projects\element-test\element-plus\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (E:\projects\element-test\element-plus\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:37:3)
    at Liftoff.handleArguments (E:\projects\element-test\element-plus\node_modules\gulp-cli\index.js:211:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by sxzz** [comment]
Please update to latest version, and retry. Thanks.

**Comment by sxzz** [comment]
Hey, have you solved it? Feel free to ask me.
