### ISSUE TITLE
[Bug Report] ElementPlusError: [ElPagination] undefined

### ISSUE THREAD

**Issue by carmel** [element-plus/element-plus#2947]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Brave 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)

### Vue version
3.2.2

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
```vue
<el-pagination
        small
        background
        hide-on-single-page
        :page-sizes="filter.pageSize"
        layout="sizes,total,prev,pager,next"
        :total="filter.total"
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
      />
```
![image](https://user-images.githubusercontent.com/36031579/129512647-4af4e3f2-4a9b-4977-af13-656610442ab0.png)

### What is Expected?
no error

### What is actually happening?
error

**Comment by carmel** [comment]
No help available? @JeremyWuuuuu

**Comment by yhm-summer** [comment]
try to add two attributes , v-model:pageSize, v-model:currentPage

**Comment by zwidny** [comment]
I meet the same issue, finally I use  @current-change="getPageData" to get data from remote

**Comment by odex21** [comment]
> try to add two attributes , v-model:pageSize, v-model:currentPage

but `v-model:current-page`, `v-model:page-size`  will also cause this problem

**Comment by z-ao** [comment]
Try to replace the event name "currentChange"、“sizeChange”

**Comment by carmel** [comment]
这个错误可说有点低级，具体解决方法如下：
```javascript
// 错误  (filter被定义成一个空对象)
const data = reactive({
    filter: {}
}

// 正确  (filter对象中需指定total属性，且要明确类型的初值)
const data = reactive({
    filter: {
        total: 0
    }
}


```

**Comment by zwidny** [comment]
> 这个bug可说有点低级，具体解决方法如下：
> 
> ```js
> // 错误  (filter被定义成一个空对象)
> const data = reactive({
>     filter: {}
> }
> 
> // 正确  (filter对象中需指定total属性，且要明确类型的初值)
> const data = reactive({
>     filter: {
>         total: 0
>     }
> }
> ```

这个应该报错filter不对吧， 而不是[ElPagination] undefined，
另外filter如果不定义是不是应该有默认值， 或者提示应该定义filter，而不是[ElPagination] undefined

**Comment by Dirian9754** [comment]
> > 这个bug可说有点低级，具体解决方法如下：
> > ```js
> > // 错误  (filter被定义成一个空对象)
> > const data = reactive({
> >     filter: {}
> > }
> > 
> > // 正确  (filter对象中需指定total属性，且要明确类型的初值)
> > const data = reactive({
> >     filter: {
> >         total: 0
> >     }
> > }
> > ```
> 
> 我都没有定义filter， 依然报错：[ElPagination] undefined， 应该不止是total取值不对的问题

我也遇到了这个问题，如果不传递 total 这个参数，就会出现这个错误，我都才写上这个组件就报错了，我觉得这是个BUG

**Comment by carmel** [comment]
> > 这个bug可说有点低级，具体解决方法如下：
> > ```js
> > // 错误  (filter被定义成一个空对象)
> > const data = reactive({
> >     filter: {}
> > }
> > 
> > // 正确  (filter对象中需指定total属性，且要明确类型的初值)
> > const data = reactive({
> >     filter: {
> >         total: 0
> >     }
> > }
> > ```
> 
> 我都没有定义filter， 依然报错：[ElPagination] undefined， 应该不止是total取值不对的问题

`明确类型的初值`有没有？这里`total`要取整型初值0！
