### ISSUE TITLE
[Bug Report] document error in Custom theme

### ISSUE THREAD

**Issue by a88795596** [element-plus/element-plus#2949]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
maxos

### Vue version
3.2.2

### Reproduction Link
https://codesandbox.io/embed/element-plus-spa-forked-7j9pu?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
create file element-variables.scss and cover variable $--color-primary to blue, but not work

### What is Expected?
the color of button should be blue

### What is actually happening?
color is green. The document is wrong

**Comment by OneSeven** [comment]
Reconstructed scss variables with css variables, it is estimated that it will take some time to reconstruct

**Comment by shiny** [comment]
> ```scss
> // not work
> $--color-primary: #ff0000;
> 
> // success
> $--colors: (
>   'primary': (
>     'base': #00ff00,
>   )
> );```
> 

It is quite useful!

**Comment by YunYouJun** [comment]
The new custom theme doc here: http://staging.element-plus.org/en-US/guide/theming.html

It may take a while for us to merge into master document.
