### ISSUE TITLE
[Bug Report] peerDependencies cause npm install error with vue@3.2.2

### ISSUE THREAD

**Issue by klwfwdk** [element-plus/element-plus#2950]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
mac

### Vue version
3.2.2

### Reproduction Link
none

### Steps to reproduce
run npm install

to fix it, just remove peerDependencies or change it to 

"peerDependencies": {
    "vue": ">=3.1.0"
  },

### What is Expected?
install without error

### What is actually happening?
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@0.0.0
npm ERR! Found: vue@3.2.2
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.1.x" from element-plus@1.0.2-beta.70
npm ERR! node_modules/element-plus
npm ERR!   element-plus@"^1.0.2-beta.70" from the root project

**Comment by deepak-s-da** [comment]
Am also getting below error on vue project

 warning  in ./src/App.vue?vue&type=template&id=7ba5bd90

"export 'createElementBlock' (imported as '_createElementBlock') was not found in 'vue'

 warning  in ./src/App.vue?vue&type=template&id=7ba5bd90

"export 'createElementVNode' (imported as '_createElementVNode') was not found in 'vue'

**Comment by jiangjunfeng98** [comment]
> Am also getting below error on vue project
> 
> warning in ./src/App.vue?vue&type=template&id=7ba5bd90
> 
> "export 'createElementBlock' (imported as '_createElementBlock') was not found in 'vue'
> 
> warning in ./src/App.vue?vue&type=template&id=7ba5bd90
> 
> "export 'createElementVNode' (imported as '_createElementVNode') was not found in 'vue'

vue 、 @vue/compiler-sfc version number is the same。

3.1.5 ok

**Comment by klwfwdk** [comment]
> > Am also getting below error on vue project
> > warning in ./src/App.vue?vue&type=template&id=7ba5bd90
> > "export 'createElementBlock' (imported as '_createElementBlock') was not found in 'vue'
> > warning in ./src/App.vue?vue&type=template&id=7ba5bd90
> > "export 'createElementVNode' (imported as '_createElementVNode') was not found in 'vue'
> 
> vue 、 @vue/compiler-sfc version number is the same。
> 
> 3.1.5 ok

vue 3.1.x  is not within the scope of this issu.

**Comment by VanishMax** [comment]
> "export 'createElementBlock' (imported as '_createElementBlock') was not found in 'vue'

Also have the same issue with 3.1.x. Looks like an upgrade to the new Vue is not just changing `peerDependencies`.
But yeah, Vue 3.2 brings many cool features, and it would be nice to have Element-ui support for it.

**Comment by uinio** [comment]
Use defineComponent to upgrade smoothly
