### ISSUE TITLE
Can the [feature request] El link component add a property that disables the page jump function

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#2952]
### Existing Component
是

### Component Name
el-link

### Description
当我在el-table组件内使用el-link的时候，有些情况下并不需要它的跳转页面功能，仅作为个button按钮使用。

**Comment by adaex** [comment]
你可以使用 `Button`，[详情](https://element-plus.org/#/zh-CN/component/button#wen-zi-an-niu)
![image](https://user-images.githubusercontent.com/29560987/129692650-68f9535c-9228-4943-9964-1876dd964138.png)

**Comment by PeyFon** [comment]
> 你可以使用`Button`，[详情](https://element-plus.org/#/zh-CN/component/button#wen-zi-an-niu)
> ![图像](https://user-images.githubusercontent.com/29560987/129692650-68f9535c-9228-4943-9964-1876dd964138.png)

当我想要红色的文本样式时使用el-button按钮还要额外修改它的class，感觉麻烦。我看el-link组件里面有href属性，是否可以让它的默认值为 javascript:;

**Comment by adaex** [comment]
> > 你可以使用`Button`，[详情](https://element-plus.org/#/zh-CN/component/button#wen-zi-an-niu)
> > ![图像](https://user-images.githubusercontent.com/29560987/129692650-68f9535c-9228-4943-9964-1876dd964138.png)
> 
> 当我想要红色的文本样式时使用el-button按钮还要额外修改它的class，感觉麻烦。我看el-link组件里面有href属性，是否可以让它的默认值为 javascript:;

这个和原生的 href 属性表现形态一致，你可以直接把`href`值设置为`javascript:;`呀。

**Comment by PeyFon** [comment]
> > > 你可以使用`Button`，[详情](https://element-plus.org/#/zh-CN/component/button#wen-zi-an-niu)
> > > ![图像](https://user-images.githubusercontent.com/29560987/129692650-68f9535c-9228-4943-9964-1876dd964138.png)
> > 
> > 
> > 当我想要红色的文本样式时使用el-button按钮还要额外修改它的class，感觉麻烦。我看el-link组件里面有href属性，是否可以让它的默认值为 javascript:;
> 
> 这个和原生的 href 属性表现形态一致，你可以直接把`href`值设置为`javascript:;`呀。

是的， 目前我确实是这么处理的。那退一步来说，假设：如果我使用el-link组件 但没有写href属性。那么它会带一个不知道跳转到哪的默认的链接跳转功能，且不会报错或警告。这样是不是容易让人误解？ 那么把href做成一个必填属性是否会好一点？

**Comment by adaex** [comment]
> > > > 你可以使用`Button`，[详情](https://element-plus.org/#/zh-CN/component/button#wen-zi-an-niu)
> > > > ![图像](https://user-images.githubusercontent.com/29560987/129692650-68f9535c-9228-4943-9964-1876dd964138.png)
> > > 
> > > 
> > > 当我想要红色的文本样式时使用el-button按钮还要额外修改它的class，感觉麻烦。我看el-link组件里面有href属性，是否可以让它的默认值为 javascript:;
> > 
> > 
> > 这个和原生的 href 属性表现形态一致，你可以直接把`href`值设置为`javascript:;`呀。
> 
> 是的， 目前我确实是这么处理的。那退一步来说，假设：如果我使用el-link组件 但没有写href属性。那么它会带一个不知道跳转到哪的默认的链接跳转功能，且不会报错或警告。这样是不是容易让人误解？ 那么把href做成一个必填属性是否会好一点？

同意，观察源码发现el-link上href不填写的时候，也会在a标签加上一个空的href属性，确实会让人误解。我稍后提一个PR。
