### ISSUE TITLE
[Bug Report] error in form.spec.ts

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#2955]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
windows

### Vue version
3.2.2

### Reproduction Link
https://github.com/element-plus/element-plus.git

### Steps to reproduce
npm run test Form

### What is Expected?
no error with `npm run test`

### What is actually happening?
error with `npm run test Form `
![image](https://user-images.githubusercontent.com/21104054/129678562-a85f5e09-87ee-4d95-a0dc-11ffd3197170.png)

**Comment by sxzz** [comment]
Fixed in https://github.com/element-plus/element-plus/pull/3109/files
