### ISSUE TITLE
vite 拆分包 提示hyphenate没有定义，我看element plus有导入import { hyphenate } from '@vue/shared'这个导致的

### ISSUE THREAD

**Issue by wlinglinux** [element-plus/element-plus#2959]
1、vite.config.js 
build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('element-plus')) {
            return 'element-plus'
          } else if (id.includes('vant')) {
            return 'vant'
          } else if (id.includes('node_modules')) {
            return 'vendor';
          }
        }
      }
    }
  },
2、npm run build
3、element-plus.44dfe061.js:1 Uncaught TypeError: Cannot read property 'hyphenate' of undefined
    at element-plus.44dfe061.js:1
    at element-plus.44dfe061.js:1
(anonymous) @ element-plus.44dfe061.js:1
(anonymous) @ element-plus.44dfe061.js:1

**Comment by wlinglinux** [comment]
我的项目在vite最终打包的时候主文件有些大，console中有提示，我按照文档在vite.config.js中配置如下
![image](https://user-images.githubusercontent.com/286261/129702168-c03bec8a-f22e-4869-95f2-5e04ead894b3.png)
将element-plus单独打包，运行npm run build 成功，但是部署到服务器后就会报错如下    element-plus.44dfe061.js:1 Uncaught TypeError: Cannot read property 'hyphenate' of undefined
at element-plus.44dfe061.js:1

at element-plus.44dfe061.js:1
(anonymous) @ element-plus.44dfe061.js:1

(anonymous) @ element-plus.44dfe061.js:1，我不知道是什么原因，我看vant也是一样的配置就没有问题；

**Comment by wlinglinux** [comment]
我看了源代码 
![image](https://user-images.githubusercontent.com/286261/130171415-40179ccd-d9c0-4c06-8c35-2504f92a6f57.png)
可以不引用vue里的代码？这样就可以单独打包了，就不会再报错了

**Comment by llk2yq** [comment]
遇到了同样的问题，vite部分配置如下
```
rollupOptions: {
    output: {
        manualChunks(id) {
            if (id.includes("node_modules")) {
                return id.toString().split("node_modules/")[1].split("/")[0].toString();
            }
        },
    },
}
```

**Comment by sxzz** [comment]
Could you please provide a minimum reproduction link? Prefer Github repository.

**Comment by sxzz** [comment]
Feel free to reopen this issue after you provided a reproduction repo.
