### ISSUE TITLE
The feedback style of El dropdown item mouse over is missing

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#2965]
Element Plus version
1.0.2-beta.70
![image](https://user-images.githubusercontent.com/22720488/129818257-173cde26-c82a-41a0-b986-f7eb7567f46d.png)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/130546966-2ca9770a-657e-40a4-9b1a-f226e4ee90ee.png)
it seems that it  is fixed
