### ISSUE TITLE
[Feature Request] want to rewrite the dynamic edit tag using the Composition API

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#2966]
### Existing Component
是

### Component Name
el-tag

### Description
because Input focus is not working

**Comment by iamkun** [comment]
I don’t get it. Any detail, please?

**Comment by PeyFon** [comment]
> 我不明白。请问有详细的吗？

I wrote the dynamic edit tag using the Composition API and found that the input box did not focus. I want to know how to write

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/129845702-7ccf3c4a-debe-4930-82e2-4f191dc31b44.png)

**Comment by undefined-degisn** [comment]
Can you show your code？
