### ISSUE TITLE
DatePicker && TimePicker bug list

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#297]

**Comment by zazzaz** [comment]
#### TimePicker 

1. double tap `Tab` to set focus on first input and trigger popper panel 

#### TimeRangePicker 

1. double tap `Tab` to set focus on first input and trigger popper panel

**Comment by ArishSultan** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by zazzaz** [comment]
That would be nice

**Comment by g3r4n** [comment]
@zazzaz from my testing, this seems to be fixed. Can you confirm ?
If you still reproduce it, can you give me a demo or steps to reproduce ?

**Comment by zazzaz** [comment]
@g3r4n Thanks, and yes it's fixed. I'll close it.
