### ISSUE TITLE
[bug report] when there is no border, the label align and width properties of the El descriptions component are invalid

### ISSUE THREAD

**Issue by wayiqi** [element-plus/element-plus#2970]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
none

### Vue version
3.2.4

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-5iwfv?file=/src/App.vue

### Steps to reproduce
no border
column: 1
label-align="right"
width="200"

 有border时，是正常的。如果没有border，使用文档列出的属性，则无效

### What is Expected?
每列一行，label右对齐

### What is actually happening?
右对齐

**Comment by rottenpen** [comment]
看了一下源码，确实是bug
![image](https://user-images.githubusercontent.com/12029924/129874492-e5e8a9c3-a1d5-4a24-b05c-61f9600a10b6.png)

**Comment by kooriookami** [comment]
> 看了一下源码，确实是bug
> ![image](https://user-images.githubusercontent.com/12029924/129874492-e5e8a9c3-a1d5-4a24-b05c-61f9600a10b6.png)

其实这个不是bug，当不使用border时，label和content是属于一个td下面的，是紧挨着的，所以没有对齐和宽度调整。
![未标题-1](https://user-images.githubusercontent.com/38392315/129995157-cb357352-5bc3-43c8-9d60-69cc9b0330a1.png)

**Comment by kooriookami** [comment]
> > 看了一下源码，确实是bug
> > ![image](https://user-images.githubusercontent.com/12029924/129874492-e5e8a9c3-a1d5-4a24-b05c-61f9600a10b6.png)
> 
> 其实这个不是bug，当不使用border时，label和content是属于一个td下面的，是紧挨着的。要是想要对齐，只能是label+content整体对齐
> ![未标题-1](https://user-images.githubusercontent.com/38392315/129995157-cb357352-5bc3-43c8-9d60-69cc9b0330a1.png)

**Comment by rottenpen** [comment]
> > 看了一下源码，确实是bug
> > ![image](https://user-images.githubusercontent.com/12029924/129874492-e5e8a9c3-a1d5-4a24-b05c-61f9600a10b6.png)
> 
> 其实这个不是bug，当不使用border时，label和content是属于一个td下面的，是紧挨着的。要是想要对齐，可以通过align实现label+content整体对齐，或者使用自定义类名修改。
> ![未标题-1](https://user-images.githubusercontent.com/38392315/129995157-cb357352-5bc3-43c8-9d60-69cc9b0330a1.png)

那应该标明 labelAlign 在没有 border 的时候不支持吧 @kooriookami

**Comment by kooriookami** [comment]
@rottenpen 可以的，文档之后补充一下
