### ISSUE TITLE
[Bug Report] Attributes size not effect in component el-radio-group with border

### ISSUE THREAD

**Issue by upupzealot** [element-plus/element-plus#2973]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Mac/Chrome

### Vue version
3.1.5

### Reproduction Link
https://jsfiddle.net/h07mp5qo/2/

### Steps to reproduce
see Reproduction Link

### What is Expected?
radio buttons with different sizes

### What is actually happening?
all radio buttons with size "mini"

**Comment by kooriookami** [comment]
Thanks, It has been solved.
