### ISSUE TITLE
[Feature Request] ElSelect remote search auto load data

### ISSUE THREAD

**Issue by zwidny** [element-plus/element-plus#2974]
### Existing Component
Yes

### Component Name
ElSelect

### Description
I use ElSelect remote search,  I can see nothing when i focus select， except  i press some key,  Hoping add a propery: remote-auto-load[bool]
that control get remote data when init  

我在使用ElSelect时， 只有当我输入了字符时才能看到选项， 默认进去为空，希望可能增加remote-auto-load: bool, 支持是否默认获取远程数据的功能

**Comment by msidolphin** [comment]
You can initialize the options yourself, according to your description, it might be more appropriate to use filterable instead of remote-search
