### ISSUE TITLE
[bug report] TimePicker model value mode cannot select time normally

### ISSUE THREAD

**Issue by blalablack** [element-plus/element-plus#2975]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
chrome 版本 92.0.4515.107（正式版本） (x86_64)

### Vue version
3.2.4

### Reproduction Link
https://codepen.io/blalablack/pen/ZEKdpPW

### Steps to reproduce
选择某个时间

### What is Expected?
重置到默认时间

### What is actually happening?
能够正常选择

**Comment by iamkun** [comment]
please refer to #2537

**Comment by kooriookami** [comment]
Can use `@update:model-value='handleChange'`

**Comment by Tianyz** [comment]
The `value` should not update without clicking the confirm button. This behavior confused me.
