### ISSUE TITLE
[Feature Request] Product Specification configurator

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#2977]
### Existing Component
No

### Component Name
Product Specification configurator

### Description
We would like to see a Product Specifications configurator which WooCommerce also has.  https://www.file.io/download/c52bRSA4ewFB

We would love to see that you are able to add specification (the key) (via API) and add/remove values in it.

**Comment by iamkun** [comment]
can you please detail it?

**Comment by sxzz** [comment]
Hi, could you please describe it in detail? The file you uploaded has been rmeoved.

**Comment by sxzz** [comment]
Feel free to reopen this issue if you provided more useful information.
