### ISSUE TITLE
[bug report] the rendering component reports an error, which makes the page value unable to be dynamically updated

### ISSUE THREAD

**Issue by loca-spirit** [element-plus/element-plus#2986]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
mac/chrome最新版

### Vue version
3.1.5

### Reproduction Link
https://github.com/element-plus/element-plus/blob/7c97bc5283292e095518d6dd9f95777069a31ab6/packages/form/src/label-wrap.ts

### Steps to reproduce
代码写的有点复杂，不好直接贴链接，并且是用render函数去递归渲染的。
渲染逻辑是先递归渲染input，select等，然后push到form-item组件里，最后递归好了后push道form组件进行return。
这个时候label-wrap.ts里面的一段代码
onMounted(() => {
      addResizeListener(el.value.firstElementChild as ResizableElement, updateLabelWidthFn)
      updateLabelWidthFn()
    })
......
function render() {
      if (!slots) return null
......
}
label-wrap元素存在还没有生成的情况，但是el.value.firstElementChild缺执行了el.value为undefined，则页面报错，造成页面的数据无法动态更新。

### What is Expected?
onMounted(() => {
      addResizeListener(el.value?.firstElementChild as ResizableElement, updateLabelWidthFn)
      updateLabelWidthFn()
    })
    onBeforeUnmount(() => {
      updateLabelWidth('remove')
      removeResizeListener(el.value?.firstElementChild as ResizableElement, updateLabelWidthFn)
    })
希望对el.value?做判断是否为空

### What is actually happening?
onMounted(() => {
      addResizeListener(el.value.firstElementChild as ResizableElement, updateLabelWidthFn)
      updateLabelWidthFn()
    })
    onBeforeUnmount(() => {
      updateLabelWidth('remove')
      removeResizeListener(el.value.firstElementChild as ResizableElement, updateLabelWidthFn)
    })
递归渲染的时候el.value为undefined，造成所有页面的值无法响应。

**Comment by taosher** [comment]
same problem

**Comment by sxzz** [comment]
It looks like it has been fixed. https://github.com/element-plus/element-plus/pull/3172
