### ISSUE TITLE
[bug report] el-select-v2 bind object. If the object attribute does not have label and value, it cannot be selected

### ISSUE THREAD

**Issue by herowzz** [element-plus/element-plus#2993]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
chorme

### Vue version
3.2.4

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/select-v2/index.ts

### Steps to reproduce
:options="stockList", stockList里是对象数组，但是对象里没有label和value属性

### What is Expected?
能够正常选择

### What is actually happening?
选择下拉框任意内容后，下拉框全部变蓝，选中项在文本框中无法显示

**Comment by msidolphin** [comment]
#2994

**Comment by herowzz** [comment]
@msidolphin 冒昧的请问一下，这个issues关闭是什么原因？
是对象本来就支持不用其他属性绑定，我不会用呢？ 
还是确定对象就是不支持其他属性，也不打算后续支持？
还是说这个bug已经解决了？

**Comment by msidolphin** [comment]
> @msidolphin 冒昧的请问一下，这个issues关闭是什么原因？
> 是对象本来就支持不用其他属性绑定，我不会用呢？
> 还是确定对象就是不支持其他属性，也不打算后续支持？
> 还是说这个bug已经解决了？

这个问题在#2994不是提及了吗？目前是不支持绑定一个对象的

**Comment by herowzz** [comment]
> > @msidolphin 冒昧的请问一下，这个issues关闭是什么原因？
> > 是对象本来就支持不用其他属性绑定，我不会用呢？
> > 还是确定对象就是不支持其他属性，也不打算后续支持？
> > 还是说这个bug已经解决了？
> 
> 这个问题在#2994不是提及了吗？目前是不支持绑定一个对象的，但是我也有说你可以用一些特殊的方式去获取

好的，明白了，谢谢
