### ISSUE TITLE
[feature request] el-select-v2 whether the user-defined filter method can be supported after enabling filterable

### ISSUE THREAD

**Issue by herowzz** [element-plus/element-plus#2994]
### Existing Component
Yes

### Component Name
el-select-v2

### Description
el-select-v2在绑定对象后，filterable想通过对象多个属性进行查找，请求支持filter-method方法

**Comment by herowzz** [comment]
还有select-v2的:options绑定数组对象后，v-model里我只能拿到value数组，请问v-model如何能够拿到选中项的对象数组吗

**Comment by msidolphin** [comment]
> 还有select-v2的:options绑定数组对象后，v-model里我只能拿到value数组，请问v-model如何能够拿到选中项的对象数组吗

states.cachedOptions应该能满足你的要求，不过我更加推荐你自己去获取，这个不承诺不会修改
