### ISSUE TITLE
[bug report] after using the slot of El form item to customize the label area, clicking anywhere in the label area will trigger the click effect and event of the first button on the right. Trying to use prevent will still trigger the effect

### ISSUE THREAD

**Issue by HarryToo** [element-plus/element-plus#2995]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
win10 / Microsoft Edge 版本 92.0.902.73

### Vue version
3.2.4

### Reproduction Link
https://codepen.io/harrytoo/pen/LYywzXB

### Steps to reproduce
点击自定义的label区域任何区域

### What is Expected?
只有点击按钮才会触发本身的效果及事件

### What is actually happening?
点击label区域任何位置均会触发右侧首个按钮的点击效果及事件

**Comment by kooriookami** [comment]
Please refer to this
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/label
![image](https://user-images.githubusercontent.com/38392315/130203423-f3fc951d-0b2f-40b7-bd6f-e3b94afa818f.png)
