### ISSUE TITLE
[Bug Report] Input Number change event triggered twice 

### ISSUE THREAD

**Issue by causingh** [element-plus/element-plus#2997]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Windows 10 / Chrome Version 92.0.4515.159 / Edge Chromium Version 92.0.902.73

### Vue version
3.2.4

### Reproduction Link
https://jsfiddle.net/causingh/cpro3Lqu/2/

### Steps to reproduce
Create an input number component with controls. Click the increment/decrement controls.

### What is Expected?
When clicking increase/decrease button, the value should only increment/decrement once.

### What is actually happening?
It was incrementing/decrementing twice.

**Comment by adaex** [comment]
I didn't find the problem you described

![recording](https://user-images.githubusercontent.com/29560987/130211646-8166bafb-b2fb-4458-bdf8-91dd9fcd9f4a.gif)

**Comment by ZhenXiongQian** [comment]
demo do not reproduce the problem

**Comment by kooriookami** [comment]
The demo is no problem. Is there other information you could provide? Or I'll close this issue.
