### ISSUE TITLE
[bug report] when < El Menu > is set to 200px and < El side > is set to auto, the value is actually 201px, resulting in misalignment on the right side of the left menu bar.

### ISSUE THREAD

**Issue by dstweihao** [element-plus/element-plus#2998]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Chrome版本 92.0.4515.159（正式版本） (x86_64)

### Vue version
3.2.4

### Reproduction Link
https://github.com/dstweihao

### Steps to reproduce
<el-aside width="auto">
      <el-menu style="200px"></el-menu>
</el-aside>

### What is Expected?
当<el-menu>设置width为200px，<el-aside>设置with为auto，实际上其值是201px，导致左侧菜单栏右侧不对齐，这多出来的1px是哪里的？

### What is actually happening?
当<el-menu>设置width为200px，<el-aside>设置with为auto，实际上其值是201px，导致左侧菜单栏右侧不对齐。
问题应该出在<el-menu>组件，因为我自己测试过，<el-aside>设置width为auto，是可以正确获取内容设置的宽度值的。

**Comment by kooriookami** [comment]
It caused by the `box-sizing` style, I'll improve it.
