### ISSUE TITLE
[bug report] overriding SCSS variable custom theme does not take effect

### ISSUE THREAD

**Issue by yunziyan11** [element-plus/element-plus#3003]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
win10  chrome

### Vue version
3.2.0

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
覆盖scss变量自定义主题不生效

### What is Expected?
覆盖scss变量自定义主题不生效

### What is actually happening?
覆盖scss变量自定义主题不生效

**Comment by kooriookami** [comment]
We are now migrating the styles, you can override css var to change style. The document is on the way.

**Comment by adiramardiani** [comment]
Hai @kooriookami 

### Element Plus version
v1.1.0-beta.8

## Issue
Currently I have some issue (I'm using vite, without vite element plus plugin)

I manualy add this component individually
```js
import {
    ElButton,
    ElMenu,
    ElTag
} from 'element-plus'

import 'element-plus/es/components/button/style'
import 'element-plus/es/components/menu/style'
import 'element-plus/es/components/icon/style'

export default function (app) {
    app.use(ElButton)
    app.use(ElMenu)
    app.use(ElTag)
}
```

On main.js I create a new style file, e.g. element-variables.scss (like on documentation) and put this style on main.js

On .scss file :
```scss
/* theme color */ 
$--color-primary: red; 
$--color-success: red !default;
$--color-warning: red  !default;
$--color-danger: red  !default;
$--color-info: red  !default;
/* icon font path, required */
$--font-path: 'element-plus/lib/theme-chalk/fonts'; 
@import "element-plus/packages/theme-chalk/src/index";
```

but my button is the same, not change to red on primary, success, warning, danger, or info

is my method correct or has something changed in the theming related documentation?

**Comment by themojilla** [comment]
@adiramardiani 

Write them down on this way:

```scss
$--colors: (
  'white': #ffffff,
  'black': #000000,
  'primary': (
          'base': $sui-color-primary,
  ),
  'success': (
          'base': $sui-color-success,
  ),
  'warning': (
          'base': $sui-color-warning,
  ),
  'danger': (
          'base': $sui-color-danger,
  ),
  'error': (
          'base': $sui-color-danger,
  ),
  'info': (
          'base': $sui-color-info,
  ),
);

$--font-path: "element-plus/packages/theme-chalk/src/fonts";
```

That should do the trick for you.

**Comment by adiramardiani** [comment]
Hei @themojilla 
Wow, thank you so much, it's working !!!

**Comment by YunYouJun** [comment]
Right method is as shown above.

```scss
$--colors: (
  'primary': (
    'base': xxx
  )
);
```

I will close it because it has been resolved.

> More info see #2242.
