### ISSUE TITLE
Shuttle box wrong version

### ISSUE THREAD

**Issue by dhj2020** [element-plus/element-plus#3004]
![image](https://user-images.githubusercontent.com/11954087/130215420-0a20a448-c61a-4cf9-b82a-bbdaf5ddb80c.png)

**Comment by ZhenXiongQian** [comment]
你好，能给出使用的具体版本，和浮现步骤已经在线demo吗
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

**Comment by kooriookami** [comment]
I see, it the style problem.
