### ISSUE TITLE
[bug report] el-dropdown hover style is lost

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#3007]
### Element Plus version
.0.2-beta.71

### OS/Browsers version
win10

### Vue version
3.2.4

### Reproduction Link
http://github.com

### Steps to reproduce
/

### What is Expected?
/

### What is actually happening?
![image](https://user-images.githubusercontent.com/1574903/130332047-f583b2f6-c43d-41b0-a366-f64e2f1e1d73.png)

**Comment by kooriookami** [comment]
It has been fixed, but the doc website hasn't update.
