### ISSUE TITLE
[Bug Report] The el-upload will animate when I put el-radio together or v-if, v-show together. The bug fixed 5 months ago，now it show again.

### ISSUE THREAD

**Issue by leonzai** [element-plus/element-plus#3014]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
windows 10 19041.867 / Edge 89.0.774.57 , Chrome 89.0.4389.90（正式版本）

### Vue version
3.2.4

### Reproduction Link
https://jsfiddle.net/9pgqcde6/3/

### Steps to reproduce
click the el-radio, the el-upload will animate

### What is Expected?
When click the el-radio, the el-upload will not animate. It will lead to a poor user experience.

### What is actually happening?
click the el-radio, the el-upload will animate

**Comment by adaex** [comment]
Using a variable reference for file-list can temporarily solve this problem. 

![recording](https://user-images.githubusercontent.com/29560987/130454788-31cdea6f-274c-48a6-8101-e41abd6bf675.gif)



I am trying to find out why this is happening.

**Comment by leonzai** [comment]
@adaex hey, guys, look at the same issue which i ask before. Thank u.

**Comment by Alanscut** [comment]
@adaex hey, do you find out the reason of this problem

**Comment by adaex** [comment]
I tried to solve this problem. Before the code merge, you can add the unique `uid` attribute to avoid this problem.

![image](https://user-images.githubusercontent.com/29560987/130611311-d3c43ae6-8e51-459d-ab86-d67796a5010e.png)
