### ISSUE TITLE
[Bug Report] ElDialog width validation is too restrictive if input is a string

### ISSUE THREAD

**Issue by alex-dunn** [element-plus/element-plus#3032]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
Chrome

### Vue version
3.1.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ryz4g?file=/src/App.vue

### Steps to reproduce
Set the width prop of an ElDialog element to a string like `calc(200px   50%)`.
Deploy app in Vue development mode (so that validation is performed & displayed).

### What is Expected?
No warnings in console. I would expect width to support any string that is a valid CSS width, including using calc.

### What is actually happening?
Validation fails but dialog is still rendered with the provided width.
```
[Vue warn]: Invalid prop: custom validator check failed for prop "width". 
  at <ElDialog modelValue=true onUpdate:modelValue=fn width="calc(200px   50%)" > 
  at <App> 
```

**Comment by niesk** [comment]
I suggest you take a look at the usage of `calc`
[https://developer.mozilla.org/de/docs/Web/CSS/calc()](https://developer.mozilla.org/de/docs/Web/CSS/calc())
