### ISSUE TITLE
[Bug Report] SFC Type breaking

### ISSUE THREAD

**Issue by sxzz** [element-plus/element-plus#3035]
### Element Plus version
1.1.0-beta.2

### OS/Browsers version

\*

### Vue version
3.2.6

### Reproduction Link
N/A

### Steps to reproduce

```typescript
import { ElMenuItem } from 'element-plus';

export const setupElementPlus = (app: App) => {
  app.use(ElMenuItem);
  // 类型“DefineComponent<unknown, object, {}, ComputedOptions, MethodOptions, ComponentOptionsMixin, ComponentOptionsMixin, ... 4 more ..., {}>”的参数不能赋给类型“Plugin_2”的参数。
  // 类型 "ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<{ [x: string]: any; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): Watc..." 中缺少属性 "install"，但类型 "{ install: PluginInstallFunction; }" 中需要该属性。ts(2345)
}
```

### What is Expected?
Type problem is fixed

### What is actually happening?

I upgrade `element-plus`@`1.1.0-beta.2`, and the types is broken...

There is the issue in these components:
- ElMenuItem
- ElSubMenu
- ElButtonGroup
- ElHeader
- ElAside
- ElMain
- ElTabPane
- ElTableColumn
- ElRadioGroup
- ElRadioButton
- ElFooter
- ElFormItem
- ElCheckboxGroup
- ElOption
- ElBreadcrumbItem
- ElStep
- ElDropdownItem
- ElDropdownMenu

**Comment by JeremyWuuuuu** [comment]
@sxzz You actually do not register `xx-item` alone since it cannot be used individually, register the main component, e.g `ElMenu` will automatically register `ElMenuItem` for you.

**Comment by JeremyWuuuuu** [comment]
I will put them into the breaking change list.
