### ISSUE TITLE
[Bug Report] Uncaught ReferenceError: ElementPlus is not defined

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#3039]
### Element Plus version
1.1.0-beta.3

### OS/Browsers version
Microsoft Edge 版本 94.0.982.2 (官方内部版本) dev (64 位)

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/yummy/pen/OJmGrMa?editors=1011

### Steps to reproduce
open the codepen, then you can see there is the error log

### What is Expected?
html with element-plus run normaly

### What is actually happening?
html with element-plus have error
![image](https://user-images.githubusercontent.com/21104054/130711911-3d8c6212-d496-4bb4-8724-cd188fc5e457.png)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/130713925-dc42c798-5449-4904-9063-cc4a79460d54.png)
![image](https://user-images.githubusercontent.com/21104054/130713728-e2461e15-c4a6-4100-8d6e-86f460111daa.png)
default code in codepen in 'new issue'

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/130718159-b18c37b3-c5b7-4e46-8dfc-1259fa745438.png)
![image](https://user-images.githubusercontent.com/21104054/130718163-6d9e58b4-e30a-4361-b017-dd7e6f54df3a.png)
![image](https://user-images.githubusercontent.com/21104054/130718168-d3e49eb2-71d0-480f-9c30-e74d18f2584c.png)
use the CDN link from your website, it is no error but component is not work

**Comment by Wynnfan** [comment]
![image](https://user-images.githubusercontent.com/24774321/130721669-7aaf258c-0c74-4543-9763-0ce5a3d2d2e1.png)
add default

**Comment by JeremyWuuuuu** [comment]
@Alanscut @Wynnfan Already fixed in `1.1.0-beta.4`
