### ISSUE TITLE
[bug report] < El button icon = "El icon edit" circle > < / El button > the button icon cannot be displayed

### ISSUE THREAD

**Issue by linrongbin16** [element-plus/element-plus#3040]
### Element Plus version
1.1.0-beta.3

### OS/Browsers version
Microsoft Edge 版本 92.0.902.78 (官方内部版本) (x86_64)

### Vue version
3.2.6

### Reproduction Link
https://jsfiddle.net/h4szrf2j/

### Steps to reproduce
open jsfiddle link and check the page

### What is Expected?
show el-button

### What is actually happening?
now showing

**Comment by Wynnfan** [comment]
![image](https://user-images.githubusercontent.com/24774321/130721174-6cbc1fed-ff0e-47eb-9c1e-c9222c9fe289.png)
link error

**Comment by JeremyWuuuuu** [comment]
Check this out: https://github.com/element-plus/element-plus/discussions/3020
