### ISSUE TITLE
[Bug Report] scrollbar yarn build error

### ISSUE THREAD

**Issue by agoni1212** [element-plus/element-plus#3044]
### Element Plus version
1.1.0-beta.4

### OS/Browsers version
chrome 

### Vue version
3.2.6

### Reproduction Link
https://elementui.github.io/

### Steps to reproduce
update to 1.1.0
1.0.0 build success

### What is Expected?
build error
![3def1a9474ad18deddfc34f931b85b3](https://user-images.githubusercontent.com/22545824/130726272-0b596097-95f9-4097-a481-32036d8fbe6d.png)

### What is actually happening?
build success

**Comment by JeremyWuuuuu** [comment]
@agoni1212 components don't have `el-` prefix at the front. Please remove that.

**Comment by JeremyWuuuuu** [comment]
https://github.com/element-plus/element-plus/discussions/3020 Please check this out. Sorry for the update caused issue. :bow:
