### ISSUE TITLE
[Bug Report] Issue in production build with few element plus component.

### ISSUE THREAD

**Issue by paudelsulav** [element-plus/element-plus#3049]
### Element Plus version
1.0.2-beta.52

### OS/Browsers version
Windows10/Chrome, Brave

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/developerhub/35un80oj/19/

### Steps to reproduce
The reproduction link provided above is of dev environment. The issue is in production build for the pagination and option-group component.
When we used the pagination and option-group components, then in production build it won't shows the label items.

### What is Expected?
It is supposed to show the option label.

### What is actually happening?
The items is there but not able to show the labels.

**Comment by kooriookami** [comment]
Can you provide a whole demo repository?

**Comment by ParryingDagger** [comment]
I have the save problem using element-plus@1.0.2-beta.53

```
vue-cli-service build --mode development
```
![devbuild](https://user-images.githubusercontent.com/25905249/131632560-486e6575-2203-4298-9162-4516eb8ccf17.png)

```
vue-cli-service build
```
![build](https://user-images.githubusercontent.com/25905249/131632642-8c245040-1a83-4cf9-aff4-a5f514300fde.png)
![build2](https://user-images.githubusercontent.com/25905249/131632651-520b4c09-db1e-406d-92ab-972a0860ec07.png)


1.0.2-beta.47 works for me

Demo: https://github.com/ParryingDagger/elPlusIssueDemo

**Comment by sxzz** [comment]
Hi, please provide what is said above and reopen this issue.
