### ISSUE TITLE
[bug report] bug released by unpkg

### ISSUE THREAD

**Issue by cole-dda** [element-plus/element-plus#3050]
### Element Plus version
1.1.0-beta.4

### OS/Browsers version
chrome

### Vue version
3.2.6

### Reproduction Link
https://jsfiddle.net/j84o29pL/

### Steps to reproduce
<script src="https://unpkg.com/element-plus/lib/index.full.js">

### What is Expected?
正确的为：
https://unpkg.com/element-plus@1.1.0-beta.4/dist/index.full.js

### What is actually happening?
重定向为：
https://unpkg.com/element-plus@1.1.0-beta.4/lib/index.full.js

**Comment by JeremyWuuuuu** [comment]
@cole-dda Hi, we've noticed this issue, we will update the template code ASAP cc @0song.

**Comment by JeremyWuuuuu** [comment]
Meanwhile, if you really need to use online demo, please try it with codepen.

**Comment by cole-dda** [comment]
now,i found the document already updated,that is right
<img width="1027" alt="screenshot_4528" src="https://user-images.githubusercontent.com/1077830/130829779-8122e5d0-9779-4350-a7ba-ac8ed275ca33.png">

**Comment by iamkun** [comment]
cool, fixed. 

ref: 
https://jsfiddle.net/iamkun/ods20k7t/4/
https://codepen.io/iamkun/pen/YzWMaVr
