### ISSUE TITLE
[Feature] Virtualized Table

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#3067]
As a user, I would like to have a table with virtualization integrated. Which have better performance. Better experience.

The functionalities should match the current existing ElTable.

In this refactor, I think the table should be using data driven. Unlike the ElementUI version

Functionality matches: 

1. Basic form
2. Striped form
3. Bordered form
4. Stateful form
5. Fixed header form
6. Fixed column form
7. Combine of 5 & 6
8. Multi-level column header
9. Single select
10. Multi-select
11. Sorting
12. Filtering
13. Customized template rendering
14. Row expansion
15. Tree form and lazy loading
16. Customized Column header
17. Trailing summary
18. Row and Column merging
19. Customized indexing

**Comment by mxp131011** [comment]
非常需要

**Comment by Greasen** [comment]
非常需要

**Comment by mingyangzhu** [comment]
请问什么时候可以发布虚拟表啊？真的非常需要这个功能，现在稍微大些数据的表格渲染都会有明显的卡顿。可以告知下虚拟表大概什么时候可以出解决方案嘛？我记得看官方写过一篇文档介绍有2中方案可选的：一种官方直接实现，另外一种官方提供适配器，可适配社区第三方虚拟表解决方案。

**Comment by Lovercz** [comment]
2000条数据的表格  带勾选 瑟瑟发抖

**Comment by sxzz** [comment]
Released in `2.2.0`

**Comment by Xiamu-ssr** [comment]
Virtualized Table 虚拟化表格这一章中，关于Sort，为什么示例代码中有data = data.reverse()？？因为示例的数据都是非常有序的，col-0123456。。。所以看起来和真的排序一样，但是当我的数据不这么有序时，我发现这个sort功能，完全是在按照reverse()走，并没有在排序。是还在开发吗？还是说还没有更新element-plus的示例？
