### ISSUE TITLE
[Bug Report] VNode el-input don't input value

### ISSUE THREAD

**Issue by iQuick** [element-plus/element-plus#3068]
### Element Plus version
1.1.0-beta.5

### OS/Browsers version
electron 12

### Vue version
3.2.6

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce

      const wifi_ssid = ref("");
      proxy.$msgbox({
        title: '设置WIFI',
        message: h('div', null, [
          h(ElInput, {
            placeholder: '请输入Wifi名称',
            modelValue: wifi_ssid.value,
            onInput: (v) => {
              proxy.$emit('update:modelValue', v)
              wifi_ssid.value = v;
              console.log("value : "   wifi_ssid.value)
            }
          }),
          h(ElInput, {
            style: [{'padding-top': '10px'}],
            placeholder: '请输入密码',
          })
        ]),
        showCancelButton: true,
        confirmButtonText: '设置',
        cancelButtonText: '取消',
        beforeClose: (action, instance, done) => {
          done()
        }
      }).then(action => {
      });

### What is Expected?
输入框能正常输入，并获取输入的值

### What is actually happening?
输入框无法输入

**Comment by msidolphin** [comment]
Maybe this code will solve your problem

```js
const { h, resolveComponent, defineComponent,getCurrentInstance, ref } = Vue;
const { ElMessageBox, ElInput } = ElementPlus;

var Page = defineComponent({
  setup () {
    const valueRef = ref('')
    return () => {
      return h('div', null, [
          h(ElInput, {
            placeholder: '请输入Wifi名称',
            modelValue: valueRef.value,
            onInput (val) {
              valueRef.value = val
            },
          }, {})
        ])
    }
  }
})

var Main = defineComponent ({
  setup() {
    const {proxy} = getCurrentInstance();
    const wifi_ssid = ref('')
    const open = () => {
      proxy.$msgbox({
        title:"设置",
        message: h(Page)
      })
    }
    return {
      open
    }
  }
});
const app = Vue.createApp(Main);
app.use(ElementPlus);
app.mount("#app")
```

**Comment by iQuick** [comment]
@msidolphin Thank you for your advice. I have solved it using normal input, but I don't know if this way of using is recommended.

let wifi_ssid = '';
let wifi_passwd = '';
proxy.$msgbox({
  title: '设置WIFI',
  message: h('div', null, [
    h('input', {
      placeholder: '请输入Wifi名称',
      style:[{'width':"100%"}, {"height":"40px"}],
      class:"el-input__inner",
      value: wifi_ssid,
      onInput(e) {
        wifi_ssid = e.target.value
      }
    }),
    h('input', {
      style: [{'width':"100%"}, {"height":"40px"}, {"margin-top":"10px"}],
      placeholder: '请输入密码',
      value: wifi_passwd,
      class:"el-input__inner",
      onInput(e) {
        wifi_passwd = e.target.value
      }
    })
  ])
})

**Comment by yaunfei** [comment]
这个问题现在有解决吗？这边使用还是不行一
