### ISSUE TITLE
[bug report] custom theme cannot be used and cannot be downloaded

### ISSUE THREAD

**Issue by vaas1993** [element-plus/element-plus#3074]
### Element Plus version
1.1.0-beta.5

### OS/Browsers version
Mac / Chrome

### Vue version
3.2.6

### Reproduction Link
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

### Steps to reproduce
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

### What is Expected?
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

### What is actually happening?
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

**Comment by xiaoxian521** [comment]
https://element-plus.gitee.io/zh-CN/guide/theming.html
