### ISSUE TITLE
[Bug Report] el-space incrementally growing horizontally by itself without end

### ISSUE THREAD

**Issue by ldevai** [element-plus/element-plus#3087]
### Element Plus version
1.1.0-beta.6

### OS/Browsers version
Mac OS Big Sur - Firefox/Safari

### Vue version
3.2.6

### Reproduction Link
https://jsfiddle.net/1bd4sLto/

### Steps to reproduce
Simply placing an el-table inside an el-space with :fill=true will cause the div to expand forever

            <el-space :fill="true">
                <el-table>
                    <el-table-column>This will be expanding horizontally</el-table-column>
                </el-table>
            </el-space>

### What is Expected?
Expected for the el-space to take the max available width and stop moving

### What is actually happening?
From t=0 of render time, the width of <main class="el-main"> element keeps increasing forever

**Comment by Alanscut** [comment]
this https://github.com/element-plus/element-plus/pull/3096 seems to fix this bug
