### ISSUE TITLE
[Feature Request] The container can support changing the width or height by dragging

### ISSUE THREAD

**Issue by jayconscious** [element-plus/element-plus#3104]
### Existing Component
Yes

### Component Name
Container or Other menthod

### Description
The container can support changing the width or height by dragging, Just like this example.
https://www.zhangxinxu.com/study/201903/css-idea/behavior-stretch.php?aside=0

**Comment by xiaoxian521** [comment]
this is same: https://github.com/element-plus/element-plus/issues/3272

**Comment by sxzz** [comment]
Duplicate of https://github.com/element-plus/element-plus/issues/3272
