### ISSUE TITLE
[Bug Report] el-cascader multiple search with v-model can't work

### ISSUE THREAD

**Issue by shangxinbo** [element-plus/element-plus#3111]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
macbook chrome

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/shangxinbo/pen/YzQXbNy

### Steps to reproduce
Find the official example, and then add the V-model attribute to reproduce it。
in addition.https://github.com/element-plus/element-plus/issues/2296 report before but closed. why? so got the question correct？

### What is Expected?
可选搜索能多选

### What is actually happening?
不能多选

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/131209408-3efc2d3c-1bea-4f4b-9c04-ea9a6078fc9a.png)
can not reproduce your problem, it can be selected more than one option in my machine

**Comment by Alanscut** [comment]
btw, I found another small problem.
 the window of select will jump a long distance., when options' level and length are different 
that maybe make user displeasure

https://user-images.githubusercontent.com/21104054/131209783-09c69c02-549b-4127-914e-28346f8109c2.mp4

**Comment by shangxinbo** [comment]
> ![image](https://user-images.githubusercontent.com/21104054/131209408-3efc2d3c-1bea-4f4b-9c04-ea9a6078fc9a.png)
> can not reproduce your problem, it can be selected more than one option in my machine


You need to search for text first, for example, search for "框" and then select multiple items in the drop-down list

**Comment by shangxinbo** [comment]
两个中国人在这里彪翻译真是好笑

**Comment by Alanscut** [comment]
有时候就很尴尬

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/131305280-d313829f-739b-4e68-93aa-66d63bed13d8.mp4

应该是修复了你说的这个

**Comment by Alanscut** [comment]
不过我发现了一个新的问题。
搜索的结果鼠标可以选中，但是使用按键无效了，方向键选择时向下到第一项就动不了了，enter也无法选中了

**Comment by shangxinbo** [comment]
>  cascader.mp4 
> 应该是修复了你说的这个

你说的修复了是指最新的版本修复了么？
可别告诉我你没有加v-model属性，官网的例子就没有加v-model, 所以复现不了。复现这个情况需要加v-model属性，请认真看我的复现示例。
我明明在上文的复现条件里写了加上v-model属性，难道说英语就看不到么

**Comment by Alanscut** [comment]
好吧，第二次是我忘加v-model了

**Comment by Alanscut** [comment]
@shangxinbo 提交pr了，等待检视和合入

**Comment by Alanscut** [comment]
@shangxinbo 这个问题是由于标签中设定多选属性时使用语句`:prop="{multiple : true}"`造成的，需要改为
![image](https://user-images.githubusercontent.com/21104054/134646877-a3973609-455e-4bf6-af98-da104e796fe0.png)

**Comment by shangxinbo** [comment]
> @shangxinbo 这个问题是由于标签中设定多选属性时使用语句`:prop="{multiple : true}"`造成的，需要改为
> ![image](https://user-images.githubusercontent.com/21104054/134646877-a3973609-455e-4bf6-af98-da104e796fe0.png)

没明白什么意思，这个问题不是在最新的版本里修复了么，我已经更新了最新版本，可以解决了

**Comment by Alanscut** [comment]
> > @shangxinbo 这个问题是由于标签中设定多选属性时使用语句`:prop="{multiple : true}"`造成的，需要改为
> > ![image](https://user-images.githubusercontent.com/21104054/134646877-a3973609-455e-4bf6-af98-da104e796fe0.png)
> 
> 没明白什么意思，这个问题不是在最新的版本里修复了么，我已经更新了最新版本，可以解决了

新版本的那个修复导致了一些其他的问题，需要回退。
后来讨论发现这个bug是`:props`赋值导致的问题，是可以避免的。
你看官网的组件示例应该也能看到，之前是直接`:props={multiple:true}`,
现在需要在<script>标签中定义`props:{multiple:true}`变量，然后将变量赋值给<el-cascader>的属性(`:props=props`)
