### ISSUE TITLE
[Bug Report] el-image-viewer drag have problem

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#3115]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
Microsoft Edge 版本 94.0.992.4 (官方内部版本) dev (64 位)

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/CN-litai/pen/powJzPx

### Steps to reproduce
click to open the image-view
mouse-down to drag image to the left(black area) and mouse-up,
you will found that image will follow the mouse without mouse-down

### What is Expected?
image follow mouse only when mouse-down

### What is actually happening?
image follow mouse without mouse-down

**Comment by Alanscut** [comment]
i can fix this bug ,but there is a problem should be discussed.
it seems that image can be drage out of the default area, i don't know is this be set or just a bug?
in my opinion the  image should only can be drag in the default area,

**Comment by Alanscut** [comment]
there are two solutions here, 
if you also think image should not be drag out of default area, we can limit the area that image can be drag
if you don't think that is problem, we can fix the issue by set when to off _dragHandler

**Comment by adaex** [comment]
> if you don't think that is problem, we can fix the issue by set when to off _dragHandler

I personally think this way will be better.

**Comment by Alanscut** [comment]
> > if you don't think that is problem, we can fix the issue by set when to off _dragHandler
> 
> I personally think this way will be better.

But are there any user needs that need to drag images out of bounds?

**Comment by adaex** [comment]
> > > if you don't think that is problem, we can fix the issue by set when to off _dragHandler
> > 
> > 
> > I personally think this way will be better.
> 
> But are there any user needs that need to drag images out of bounds?

I'm not sure, but I'm going to refer to how the performance of similar products.

**Comment by Alanscut** [comment]
o,,k, i will work to fix it by  by set when to off _dragHandler

**Comment by Alanscut** [comment]
oh, i found another case.
i have two screen so i can move my mouse to the other screen , but brower is just exist in the first screen and image will disapper
![image](https://user-images.githubusercontent.com/21104054/131275360-2f8167a7-b5d8-434b-93fe-81e206586a7f.png)

**Comment by adaex** [comment]
@Alanscut 
I also found another one from ant-design.

When the mouse is lifted, this picture will return to the original position.

https://user-images.githubusercontent.com/29560987/131276024-5fd23549-7e10-42ec-b871-9f29c2f4bae5.mp4

**Comment by Alanscut** [comment]
is this the different between mac and windows?

https://user-images.githubusercontent.com/21104054/131276420-2fbd7194-bade-4a6d-85ba-a39d850fae4e.mp4

**Comment by Alanscut** [comment]
Ok, this way is better。
I will try to achieve this effect

**Comment by adaex** [comment]
> but brower is just exist in the first screen and image will disapper

Can you record a screen, I didn't find pictures disappeared, I found that the picture will stay in place.


https://user-images.githubusercontent.com/29560987/131279319-6ad0aa27-2065-4212-a0d8-3c969bb254d6.mp4

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/131279599-73a205df-b113-42c5-9903-75f4df059059.mp4

**Comment by adaex** [comment]
>  bandicam.2021-08-30.10-21-13-756.mp4

😯 Oh, I see. A little less friendly.

**Comment by sxzz** [comment]
Fixed in #3133
