### ISSUE TITLE
[bug report] eltabpane elformitem cannot use app. Use()

### ISSUE THREAD

**Issue by dboy2018** [element-plus/element-plus#3118]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
win10

### Vue version
3.2.6

### Reproduction Link
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

### Steps to reproduce
import {  ElButton,  ElCheckbox,  ElForm,  ElFormItem,  ElInput,  ElLink,  ElRadio,  ElTabPane,  ElTabs} from 'element-plus'
app.use(ElButton)
app.use(ElCheckbox)
......
app.use(ElFormItem)
app.use(ElTabPane)

ElFormItem ElTabPane 出现错误
可能还有其他的,目前先这两个

### What is Expected?
..

### What is actually happening?
类型“(SFCWithInstall<DefineComponent<{ type: { type: (new (...args: any[]) => ("text" | "success" | "info" | "warning" | "default" | "primary" | "danger") & {}) | (() => "text" | "success" | "info" | "warning" | "default" | "primary" | "danger") | ((new (...args: any[]) => ("text" | ... 5 more ... | "danger") & {}) | (()...”的参数不能赋给类型“Plugin_2”的参数。
  不能将类型“DefineComponent<{ label: StringConstructor; labelWidth: { type: (StringConstructor | NumberConstructor)[]; default: string; }; prop: StringConstructor; ... 7 more ...; size: { ...; }; }, ... 10 more ..., { ...; }>”分配给类型“Plugin_2”。
    类型 "ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{ labelWidth: string | number; inlineMessage: string | boolean; showMessage: boolean; required: boolean; }> & Omit<...>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefin..." 中缺少属性 "install"，但类型 "{ install: PluginInstallFunction; }" 中需要该属性。ts(2345)
runtime-core.d.ts(1293, 5): 在此处声明了 "install"。

**Comment by imswk** [comment]
I just tried，I think you should` import { ElTabs } from 'element-plus'` and ` app.use(ElTabs)`. Instead of referencing his subcomponents. `ElFormItem` It's the same，Because none of their subcomponents can work alone.

**Comment by imswk** [comment]
@dboy2018

**Comment by sxzz** [comment]
please read this. https://github.com/element-plus/element-plus/discussions/3020
You only need to register the parent component.

请参考这个 https://github.com/element-plus/element-plus/discussions/3020
只需要注册父组件即可。

**Comment by dboy2018** [comment]
那么,问题来了,ElContainer里面有Aside Footer Header Main,但是按需引用缺少样式
element-plus\lib\components\container\style\css
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../../../components/base/style/css");
require("../../../../theme-chalk/el-container.css");

下面没有,是不是需要添加一下
require("../../../../theme-chalk/el-aside.css");


还有就是按需引用打包的样式问题

module.exports = {
  plugins: [
    [
      'import',
      {
        libraryName: 'element-plus',
        customName: (name) => {

          name = name.slice(3)
  

          return `element-plus/lib/components/${name}`
        },
       
        customStyleName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}/style/css`
          // return `element-plus/theme-chalk/${name}.css`
        }
      }
    ]
  ],
  presets: ['@vue/cli-plugin-babel/preset']
}


如果用`element-plus/lib/components/${name}/style/css` ,缺少样式,上面已经说过了,而且build打包,没有css样式
用 element-plus/theme-chalk/${name}.css build后有样式,但是需要自己添加base.css,el-aside.css...

**Comment by dboy2018** [comment]
还有人吗

**Comment by JeremyWuuuuu** [comment]
@dboy2018 You don't need to use `app.use(ElTabPane)` it is registered for you when `ElTab` gets registered.

**Comment by JeremyWuuuuu** [comment]
Since I have already mentioned in https://github.com/element-plus/element-plus/discussions/3020 this channel, which you should read before upgrading I suppose.

**Comment by JeremyWuuuuu** [comment]
You can also introduce `ElTabPane` via
```ts
import { ElTab } from 'element-plus'
const { TabPane } = ElTab
```

**Comment by JeremyWuuuuu** [comment]
The reason behind this is that since these item-ish component cannot be independently used, we have decided to take them out of the context just like `antd` does.

**Comment by JeremyWuuuuu** [comment]
About `ElAside` `ElFooter` `ElMain` I think you made your point it is indeed something we forgot to import styles into the bundle. We will add that soon.
