### ISSUE TITLE
[bug report] version "1.0.2-beta.71" theme color has no effect on El button

### ISSUE THREAD

**Issue by GGupzHH** [element-plus/element-plus#3119]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Chrome  94.0.4606.12（正式版本） （64 位）

### Vue version
3.0.2

### Reproduction Link
https://github.com/GGupzHH/Vite2-Vue3-Template

### Steps to reproduce
<el-button type="primary">主要按钮</el-button>

### What is Expected?
起作用

### What is actually happening?
I don't know

**Comment by imswk** [comment]
@GGupzHH  You can use the following method to replace `$--color-primary: teal; ` 
```
$--colors: (
  (
    'primary': (
      'base': teal,
    )
  )
);
```

**Comment by GGupzHH** [comment]
$--colors: (
  "primary": (
    "base": #F37021,
  ),
  "success": (
    "base": #67c23a,
  ),
  "warning": (
    "base": #e6a23c,
  ),
  "danger": (
    "base": #f56c6c,
  ),
  "error": (
    "base": #db2828,
  ),
  "info": (
    "base": #909399,
  ),
);

谢谢您~ 
上午找到了  忘记说了😊😊😊

**Comment by JeremyWuuuuu** [comment]
Closing since invalid.
