### ISSUE TITLE
[Bug Report] Blob Image Not revoked at default remove method

### ISSUE THREAD

**Issue by Kudo-Nori** [element-plus/element-plus#3130]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
Windows10 / Chrome 92.0.4515.131

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/kudo-nori/pen/zYzrOLb

### Steps to reproduce
Correct behavior
1: Set the file.
2: Unmount el-upload. (Press the Toggle button)
3: Press the ToggleButton again.
4: The Blob image was released.

Bugs
1: Set the file.
2: Delete the file (press the trash can icon on mouse-over)
3: Unmount el-upload. (Press the ToggleButton).
4: Press the ToggleButton again.
5: Blob images are not released.

### What is Expected?
Blob images will be released.

### What is actually happening?
Unintended use of memory

**Comment by adaex** [comment]
I will try to solve it later.
