### ISSUE TITLE
[Bug Report] ElTable defaultExpandAll prop doesn't work with tree in table

### ISSUE THREAD

**Issue by bitjjj** [element-plus/element-plus#3139]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
Chrome92

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/bitjjj/pen/yLXeyXJ

### Steps to reproduce
1) 在table里使用tree
2）默认设置defaultExpandAll为true

### What is Expected?
有children的行默认展开

### What is actually happening?
有children的行没有自动展开。

问题在tree.ts文件里的updateTreeData函数：

const defaultExpandAll = instance.store?.states.defaultExpandAll.value

在取defaultExpandAll时，store还没有被挂载到instance上，所以取不到正确的值

**Comment by adaex** [comment]
Repeat with this issue: https://github.com/element-plus/element-plus/issues/2776
