### ISSUE TITLE
[feature request] CSS change of El form

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#3141]
### Existing Component
是

### Component Name
el-form

### Description
vue2的时候：.el-form-item.is-required:not(.is-no-asterisk)
  .el-form-item__label-wrap
  > .el-form-item__label:before,
.el-form-item.is-required:not(.is-no-asterisk) > .el-form-item__label:before {
  content: "*";
  color: #f56c6c;
  margin-right: 4px;
}
vue3的时候：.el-form-item.is-required:not(.is-no-asterisk)>.el-form-item__label:before{content:"*";color:var(--el-color-danger);margin-right:4px}   
为什么要删掉.el-form-item__label-wrap？

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/131436071-eea553dd-e9b7-4dff-9dd3-94585807353e.png)
![image](https://user-images.githubusercontent.com/60815493/131436136-30e579d1-731f-42fa-b2ee-d521b8f52cf5.png)

**Comment by PeyFon** [comment]
"vue": "^3.2.6", "element-plus": "^1.1.0-beta.7",  我不知道为啥还会有.el-form-item__label-wrap这个属性？

**Comment by msidolphin** [comment]
The `.el-form-item__label-wrap` has not been removed, when the width of the item is auto it will be wrapped with div .el-form-item__label-wrap

**Comment by PeyFon** [comment]
> The `.el-form-item__label-wrap` has not been removed, when the width of the item is auto it will be wrapped with div .el-form-item__label-wrap

So it doesn't show a red asterisk

**Comment by PeyFon** [comment]
> The `.el-form-item__label-wrap` has not been removed, when the width of the item is auto it will be wrapped with div .el-form-item__label-wrap

 when the width of the item is auto it doesn't show a red asterisk

**Comment by PeyFon** [comment]
> The `.el-form-item__label-wrap` has not been removed, when the width of the item is auto it will be wrapped with div .el-form-item__label-wrap

https://codepen.io/peyfon/pen/KKqzJBq  
I will turn it off if the problem is resolved, thank you
