### ISSUE TITLE
[Feature Request] popover auto placement

### ISSUE THREAD

**Issue by CNlitai** [element-plus/element-plus#3145]
### Existing Component
Yes

### Component Name
popover

### Description
When the position of the pop-up box is close to the boundary, it should automatically switch to the opposite direction for display. You can add a familiar control here. Ant design has this default configuration item. Although element can now achieve this function by customizing Popper options. But I spent a lot of time exploring in the process of implementation. If you don't add this feature, you can consider allowing me to update the document
Because this function is commonly used in development

**Comment by kooriookami** [comment]
You can use `fallbackPlacements` like `:fallback-placements="['bottom', 'top', 'right', 'left']"`.

**Comment by CNlitai** [comment]
> placements

thanks
it should be add to documents

**Comment by kooriookami** [comment]
Yes, we will update the document.

**Comment by Qzhor** [comment]
hahahaha, helps a lot

**Comment by Qzhor** [comment]
fallbackplacement 

> Yes, we will update the document.

:fallback-placements="['bottom', 'top', 'right', 'left']" , this not work for me....

**Comment by CNlitai** [comment]
> '

you can try 
:popper-options="{
                    placement: 'right',
                    modifiers: [
                      {
                        name: 'flip',
                        options: {
                          fallbackPlacements: ['bottom', 'left', 'right'],
                        },
                      },
                    ],
                  }"
if it’s also not work, please check your element-plus version

**Comment by Qzhor** [comment]
> > '
> 
> you can try
> :popper-options="{
> placement: 'right',
> modifiers: [
> {
> name: 'flip',
> options: {
> fallbackPlacements: ['bottom', 'left', 'right'],
> },
> },
> ],
> }"
> if it’s also not work, please check your element-plus version

I found that if append-to-body is true, will not use the fallbackPlacements option, so I mannually set append-to-body to fasle, it works~ ^_^

**Comment by Qzhor** [comment]
> > '
> 
> you can try
> :popper-options="{
> placement: 'right',
> modifiers: [
> {
> name: 'flip',
> options: {
> fallbackPlacements: ['bottom', 'left', 'right'],
> },
> },
> ],
> }"
> if it’s also not work, please check your element-plus version

I mannually set append-to-body to fasle, it works..  ^_^
