### ISSUE TITLE
[Feature Request] el-table custom scrollbar

### ISSUE THREAD

**Issue by Xqrrrr** [element-plus/element-plus#3146]
### Existing Component
Yes

### Component Name
1.1.0-beta.8

### Description
Google Chrome

Can I customize the scrollbar, because I want to change the color of the scrollbar and its continuous display in el-table

**Comment by msidolphin** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by Xqrrrr** [comment]
> https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

After I use webkit-scrollbar, the scrollbar disappears directly
