### ISSUE TITLE
[bug report] radio group cannot set the fill color when it is not selected

### ISSUE THREAD

**Issue by Cat7373** [element-plus/element-plus#3148]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
MacOS 12.0 Beta/Chrome 92.0

### Vue version
3.2.6

### Reproduction Link
https://jsfiddle.net/q26o9ktw/3/

### Steps to reproduce
如复现链接

之前版本中，未选中的选项是有填充色的，不会把背景色透过来，当前版本似乎是直接透明了

### What is Expected?
不要透明，或至少可以通过选项配置

### What is actually happening?
未选中的选项透明了

**Comment by kooriookami** [comment]
OK
