### ISSUE TITLE
El cascade selector initialization slow

### ISSUE THREAD

**Issue by duanhaobo** [element-plus/element-plus#3149]
elementui-plus的级联选择器，第一次初始化一级节点的时候  34个值，渲染花了300ms ，这是不是有点不正常，一直感觉会卡顿一下，渲染170个值会话1秒左右的时间

**Comment by duanhaobo** [comment]
没有连接，我开发中遇到的，就单纯定义了40个数据，渲染需要花200-300ms， 用的是最简单的那个例子，我想做省市区三级联动，我发现很卡

**Comment by msidolphin** [comment]
@duanhaobo 那你需要提供一个重现demo给我们啊，不然我们不知道到底是开发者的问题还是组件的问题
