### ISSUE TITLE
[Bug Report] el-calendar range prop did not validate rightly

### ISSUE THREAD

**Issue by NO-MAP** [element-plus/element-plus#3152]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
chrome

### Vue version
3.2.6

### Reproduction Link
https://github.com/element-plus/element-plus/blob/12006ecdb758ed2997dddbc163467045aaea3918/packages/components/calendar/src/index.vue#L171

### Steps to reproduce
1. use el-canlendar component.
2. set the range prop over than one month but less than tow month
3. got the result: 
  console.warn(
            '[ElementCalendar]start time and end time interval must not exceed two months',
          )

4. https://github.com/element-plus/element-plus/blob/12006ecdb758ed2997dddbc163467045aaea3918/packages/components/calendar/src/index.vue#L171

```
// code
// two months
        if (startDayjs.add(1, 'month').month() !== endDayjs.month()) {
          console.warn(
            '[ElementCalendar]start time and end time interval must not exceed two months',
          )
          return []
        }

// startDayjs.add(1, 'month')  =>>  startDayjs.add(2, ''month) 
```

### What is Expected?
range prop is not right

### What is actually happening?
range prop to be right

**Comment by adaex** [comment]
@NO-MAP  这个代码逻辑其实没有错，文档的描述可能不太准确。

时间跨度不能超过两个月的意思其实是输入的时间范围月份跨度最多只能是1个月，比如 2月20日-3月30日是月份跨度为1个月，是允许的，但2月20日到4月10日，月份跨越了2个月，是不允许的。

**Comment by NO-MAP** [comment]
> @NO-MAP 这个代码逻辑其实没有错，文档的描述可能不太准确。
> 
> 时间跨度不能超过两个月的意思其实是输入的时间范围月份跨度最多只能是1个月，比如 2月20日-3月30日是月份跨度为1个月，是允许的，但2月20日到4月10日，月份跨越了2个月，是不允许的。

OK, THANKS

**Comment by zhangshichun** [comment]
> @NO-MAP 这个代码逻辑其实没有错，文档的描述可能不太准确。
> 
> 时间跨度不能超过两个月的意思其实是输入的时间范围月份跨度最多只能是1个月，比如 2月20日-3月30日是月份跨度为1个月，是允许的，但2月20日到4月10日，月份跨越了2个月，是不允许的。

但是，为什么呢？
![image](https://user-images.githubusercontent.com/15374687/140437045-e6f6735d-dad4-435f-8d7f-b8848d62e8ae.png)
2021年11月，组件默认的时间范围是：10-3 到 12-11；range传入[10-3, 12-4]居然会被判定为范围过宽；
