### ISSUE TITLE
[bug report] if the sub menu El menu item of navmenu navigation menu is introduced into El menu through component, the navigation in horizontal mode will be invalid if it exceeds the display

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#3161]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
mac

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/xiaoxian521/pen/BaZKjbX

### Steps to reproduce
1. 创建el-menu
2. 将el-menu-item封装成 fragment
3. 引入封装好的el-menu-item到el-menu里，即可看到效果

### What is Expected?
希望恢复正常

### What is actually happening?
不正常

**Comment by wanyakun** [comment]
+1

**Comment by adiramardiani** [comment]
Hai @kooriookami 
I have some issue too, the drop down icon not show on el-sub-menu
On previous release sub-menu give ```<i class="el-sub-menu__icon-arrow el-icon-arrow-down"></i>``` icon, currently this icon is gone
Is the icon can customize to other icon ?
![image](https://user-images.githubusercontent.com/8703419/131613081-d1d7139a-0844-4e30-a159-88a691906ab0.png)

Is ellipsis can add more control ? like when menu reach 13 menu, the ellipsis will be show, the ellipsis can disable to

Is el-sub-menu can manualy configure, the sub menu will show from left or right, I have some problem on complex menu, on last menu the  sub menu drop down is overlap page

**Comment by kooriookami** [comment]
@adiramardiani icon-arrow will add back.

**Comment by xiaoxian521** [comment]
@msidolphin 这个问题解决了？
