### ISSUE TITLE
[Bug Report] el-dropdown In el-dialog make dialog cannot show

### ISSUE THREAD

**Issue by zhangshichun** [element-plus/element-plus#3164]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/zhangshichun/pen/XWgdjdd

### Steps to reproduce
just click [点击打开 Dialog] button

### What is Expected?
dialog show

### What is actually happening?
dialog cannot show;
but if you remove the <el-dropdown>，the dialog can show success;

**Comment by adaex** [comment]
You should add a triggering element ( rendered by the default `slot`) and the dropdown part ( rendered by the `slot` named `dropdown` ).  see: https://element-plus.org/#/en-US/component/dropdown#basic-usage

But there is still an error in this, if the component `solt` is empty, it should not output an error on the console. I will try to fix it later.

**Comment by zhangshichun** [comment]
> You should add a triggering element ( rendered by the default `slot`) and the dropdown part ( rendered by the `slot` named `dropdown` ). see: https://element-plus.org/#/en-US/component/dropdown#basic-usage
> 
> But there is still an error in this, if the component `solt` is empty, it should not output an error on the console. I will try to fix it later.

thank you ：）

**Comment by adaex** [comment]
Solved in https://github.com/element-plus/element-plus/pull/3173
