### ISSUE TITLE
[Bug Report] ElDropdown has an error in the console when default `solt` is empty

### ISSUE THREAD

**Issue by adaex** [element-plus/element-plus#3171]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
chrome 

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/adaex/pen/PojNWJK

### Steps to reproduce
Open the web to view the console

### What is Expected?
No error output

### What is actually happening?

Console has error message

**Comment by sxzz** [comment]
close due to #3173
