### ISSUE TITLE
[Bug Report] dependency was not found about On-demand introduction

### ISSUE THREAD

**Issue by panssdr** [element-plus/element-plus#3177]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
windows

### Vue version
3.2.6

### Reproduction Link
https://github.com/element-plus/element-plus/tree/1.1.0-beta.8

### Steps to reproduce
babel.config.js根据官网配置如下：

module.exports = {
  plugins: [
    [
      'import',
      {
        libraryName: 'element-plus',
        customName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}`
        },
        customStyleName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}/style/css`
        }
      }
    ]
  ],
  presets: ['@vue/cli-plugin-babel/preset']
}

### What is Expected?
按需加载正常引入 (全局引入是正常的)

### What is actually happening?
直接报错
This dependency was not found:

* element-plus/lib/el-button in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/view/login/login.vue?vue&type=script&lang=ts

To install it, you can run: npm install --save element-plus/lib/el-button

**Comment by re3lex** [comment]
Same here. Any upate?

**Comment by ssaldarriaga** [comment]
Same here. I'm getting issues with the following component too:

- element-plus/lib/components/table-column

**Comment by ssaldarriaga** [comment]
Hello, Good news. I just achieved to use some of those components.

How JeremyWuuuuu mentioned in their [PR](https://github.com/element-plus/element-plus/discussions/3020#discussion-3536301), we only need to register the component manually.

I registered this component. After that, I was able to use it
```js
// main.ts
import { createApp } from "vue";
import App from "./App.vue";
import { ElTable, ElForm } from "element-plus";

const app = createApp(App);
app.component("ElFormItem", ElForm.FormItem);

app.mount("#app");

```
