### ISSUE TITLE
[Bug Report] el-dropdown Cannot hide automatically after losing focus

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#3184]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
MacOs Chrome 91.0.4472.114

### Vue version
3.2.7

### Steps to reproduce
you can use jsfiddle to enter the code for reproduction

<el-dropdown trigger="click" placement="bottom-end">
          <i class="el-icon-more-outline"></i>
          <template #dropdown>
            <el-dropdown-item command="1" icon="el-icon-refresh-right">刷新</el-dropdown-item>
            <el-dropdown-item command="2" icon="el-icon-minus">关闭</el-dropdown-item>
            <el-dropdown-item command="5" icon="el-icon-finished">关闭其他</el-dropdown-item>
            <el-dropdown-item command="6" icon="el-icon-circle-close">关闭全部</el-dropdown-item>
          </template>
        </el-dropdown>

### What is Expected?
el-dropdown can be hidden automatically after losing focus

### What is actually happening?
el-dropdown Cannot hide automatically after losing focus

**Comment by Alanscut** [comment]
ｃａｎ　ｙｏｕ　provide　ａ　reproduce　ｌｉｎｋ

**Comment by Lupeiwen0** [comment]
Found the reason

<template #dropdown>
  <el-dropdown-menu>
      <el-dropdown-item>黄金糕</el-dropdown-item>
      <el-dropdown-item>狮子头</el-dropdown-item>
      <el-dropdown-item>螺蛳粉</el-dropdown-item>
  </el-dropdown-menu>
</template>

Missing   el-dropdown-menu
