### ISSUE TITLE
[Bug Report] $() bindings can only be declared with let

### ISSUE THREAD

**Issue by orziz** [element-plus/element-plus#3187]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
mac/chrome

### Vue version
3.2.7

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/5/

### Steps to reproduce
just run dev

### What is Expected?
fixed this

### What is actually happening?
[vite] Internal server error: $() bindings can only be declared with let

![image](https://user-images.githubusercontent.com/36832622/131774807-471899fc-fcbe-4e52-b7ac-742ca8d1db80.png)

**Comment by btea** [comment]
the reproduction link is 404

**Comment by orziz** [comment]
> the reproduction link is 404

no reproduction link. just run.
but i used `refTransform: true`. also, you can try [https://github.com/pohunchn/vite-ts-quick](https://github.com/pohunchn/vite-ts-quick)

**Comment by sxzz** [comment]
Just ignore node_modules. Please refer to the ref sugar documentation.

**Comment by sxzz** [comment]
```js
```

**Comment by sxzz** [comment]
In view of the long period of inactivity, this issue has been closed. If there is a problem, please feel free to post a new issue.
