### ISSUE TITLE
[Feature Request] Add label width limit to descriptions

### ISSUE THREAD

**Issue by phpjishu** [element-plus/element-plus#3194]
### Existing Component
Yes

### Component Name
Descriptions 

### Description
Add a label width limit to descriptions. When I only want to display one column, the label width is obviously unreasonable. It is recommended to increase the label width configuration, which can be adapted by default！
![image](https://user-images.githubusercontent.com/6937002/131786038-6029d8af-7c8d-4689-8838-e181923dbeb9.png)

**Comment by kooriookami** [comment]
You can use set `class-name` and `label-class-name`.
