### ISSUE TITLE
[Bug Report] The Props property type of the Tree component is wrong

### ISSUE THREAD

**Issue by Glimpse6** [element-plus/element-plus#3196]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Windows 11

### Vue version
3.2.7

### Reproduction Link
https://jsfiddle.net/ubsdjx1c/4/

### Steps to reproduce
I found that disabled under the TreeOptionProps of the Tree component is a string type

### What is Expected?
Tree > TreeOptionProps > disabled is booblean

### What is actually happening?
Tree > TreeOptionProps > disabled is string

**Comment by Glimpse6** [comment]
![1630567824(1)](https://user-images.githubusercontent.com/35551590/131801551-7c0c80d0-3ed8-4c47-9f06-3bdbba1caba8.png)

**Comment by Glimpse6** [comment]
![image](https://user-images.githubusercontent.com/35551590/131801666-8dd78da2-cb2a-4bfb-baa5-b727194b6f67.png)

**Comment by Alanscut** [comment]
hi @Glimpse6 , `disabled` property in TreeOptionsProps is the property of `props`:
https://github.com/element-plus/element-plus/blob/01b867896efe3c8fe644238e89db67ae53785d02/packages/components/tree/src/tree.vue#L100-L107
 and its default value is `disabled`, namely we could use  the `disabled` property in `data` object:
```
            data: [{
              id: 1,
              label: '一级 2',
              // disabled What type should it be？ ==>  should be boolean here
              disabled: true,
              children: [{
                id: 3,
                label: '二级 2-1',
                children: [{
                  id: 4,
                  label: '三级 3-1-1'
                }, {
                  id: 5,
                  label: '三级 3-1-2',
                  disabled: true
                }]
              },]
              }]
            }],

            defaultProps: {
              children: 'children',
              label: 'label',
              disabled: 'disabled'  // should be string here
            }
```

if the `disabled` property of `props` is set to any other string, then the `disabled` proproty in `data` object won't take effect

**Comment by Glimpse6** [comment]
> 嗨@Glimpse6，`disabled`TreeOptionsProps 中的属性是以下属性`props`：
> https://github.com/element-plus/element-plus/blob/01b867896efe3c8fe644238e89db67ae53785d02/packages/components/tree/src/tree.vue#L100-L107
> 
> 
> 并且它的默认值为`disabled`，即我们可以`disabled`在`data`对象中使用该属性：
> ```
>             data: [{
>               id: 1,
>               label: '一级 2',
>               // disabled What type should it be？ ==>  should be boolean here
>               disabled: true,
>               children: [{
>                 id: 3,
>                 label: '二级 2-1',
>                 children: [{
>                   id: 4,
>                   label: '三级 3-1-1'
>                 }, {
>                   id: 5,
>                   label: '三级 3-1-2',
>                   disabled: true
>                 }]
>               },]
>               }]
>             }],
> 
>             defaultProps: {
>               children: 'children',
>               label: 'label',
>               disabled: 'disabled'  // should be string here
>             }
> ```
> 
> 如果`disabled`of的属性`props`设置为任何其他字符串，则`disabled`object 中的`data`属性不会生效

Thanks, I get it
