### ISSUE TITLE
[bug report] when importing on demand, the item style of the timeline component will not be imported automatically

### ISSUE THREAD

**Issue by kexirong** [element-plus/element-plus#3199]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Chrome/91.0.4472.164

### Vue version
3.2.7

### Reproduction Link
https://https://github.com/not/have

### Steps to reproduce
```
module.exports = {
  "presets": [
    "@vue/cli-plugin-babel/preset"
  ],
  "plugins": [
    [
      "import",
      {
        libraryName: 'element-plus',
        customName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}`
        },
        // 引入样式
        customStyleName: (name) => {
          name = name.slice(3)
          return `element-plus/lib/components/${name}/style`
        },
      },
    ],
  ]
}
```

### What is Expected?
没有引入timeline-item样式

### What is actually happening?
显式 添加
 ```
 import "element-plus/lib/components/timeline-item/style" 
```
才样式正常

**Comment by k0lios** [comment]
Yes, i have some proplems

**Comment by pifako** [comment]
Duplicate of #3177

**Comment by kexirong** [comment]
> Duplicate of #3177
> Duplicate of #3128
Ooh, Buddy. you have an illusion, they are not Duplicate. #3177 Maybe need to delete the build output directory, #3128  Is did't  read the breaking change log
@pifako

**Comment by LightAPIs** [comment]
`radio-group` and `radio-button` have the same problem.

**Comment by SadWood** [comment]
打包也有问题，还是直接引入全部样式吧

**Comment by kexirong** [comment]
> 打包也有问题，还是直接引入全部样式吧

用vite build没有问题，webpack 打包样式有问题，vite基于rollup配置非常简单，几乎0学习成本

**Comment by askwuxue** [comment]
遇到了同样的问题，按需加载组件时，使用babel-plugin-import无法加载对应的样式。试了上述方式也没有解决，故诞生了以下解决方案。
- 将按需加载的组件抽离到一个数组中，通过遍历数组的方式，通过app.component(componet.name, component)的方式注册组件，顺带加载对应的css样式。

```js
import { ElButton, ElLink, ElRate } from 'element-plus/lib
const components = [ElButton, ElLink, ElRate]

import { App } from 'vue'
export default function (app: App): void {
  // 注册element-plus组件
  for (const comp of components) {
    // const name = comp.name.slice(2).toLowerCase()
    // TODO 通过动态加载的方式解决按需加载对应样式无法加载的问题
    // import(`element-plus/lib/components/${name}/style/css`)
    app.component(comp.name, comp)
  }
}
```
试了一下，算是一种代替方案，甚至觉得更方便

**Comment by ymma** [comment]
同样遇到问题，还发现了另一个问题
使用 import 单独引入样式，会发现有些css顺序错误
比如：
```
import 'element-plus/theme-chalk/src/message.scss'
```
在弹出的message中效果
![1636097456734](https://user-images.githubusercontent.com/10007630/140474195-585996cd-4506-479b-94c9-257e7371f22d.jpg)
`.el-message__closeBtn`的优先级应当高于`.el-icon`

**Comment by sxzz** [comment]
Please try `unplugin-vue-components`, and see the latest documentation.
