### ISSUE TITLE
[bug report] if the sub menu El menu item of navmenu navigation menu is introduced into El menu through component, the navigation in horizontal mode will be invalid if it exceeds the display 

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#3203]
Translation of this issue:

### Element Plus version
1.1.0-beta.8

### OS/Browsers version
mac

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/xiaoxian521/pen/BaZKjbX

### Steps to reproduce
1. Create El menu

2. Encapsulate El menu item into fragment
3. Introduce the encapsulated El menu item into the El menu to see the effect

### What is Expected?
Hope to return to normal

### What is actually happening?
abnormal

_Originally posted by @element-bot in https://github.com/element-plus/element-plus/issues/3161#issuecomment-909819039_

**Comment by xiaoxian521** [comment]
This problem directly affects the use, if you have time, please take a look.

**Comment by kooriookami** [comment]
It seems has been fixed, wait next version.

**Comment by JeremyWuuuuu** [comment]
@kooriookami  Would you mind link this to the PR that fix this then close this?

**Comment by kooriookami** [comment]
> @kooriookami Would you mind link this to the PR that fix this then close this?

OK, #3167
