### ISSUE TITLE
[bug report] < El Table > column cannot be changed dynamically in mounted

### ISSUE THREAD

**Issue by ZhouJiang** [element-plus/element-plus#3205]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Chrome 92

### Vue version
3.2.8

### Reproduction Link
https://codepen.io/zhoujiang/pen/oNwLvym

### Steps to reproduce
mounted 生命周期中增加 column ，无法呈现

### What is Expected?
可以呈现

### What is actually happening?
无法呈现

**Comment by Cheerwhy** [comment]
目前看来先用nextTick解决
在mounted中
`**async** mounted() {
        **await this.$nextTick();**
         this.columns.push({
              lable: '日期2',
              prop: 'date',
              width: '180'})     
},`

**Comment by xiaoxian521** [comment]
I think it is necessary to use this.$nextTick()
https://github.com/answershuto/learnVue/blob/master/docs/Vue.js%E5%BC%82%E6%AD%A5%E6%9B%B4%E6%96%B0DOM%E7%AD%96%E7%95%A5%E5%8F%8AnextTick.MarkDown#%E8%AE%BF%E9%97%AE%E7%9C%9F%E5%AE%9Edom%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0%E5%90%8E%E7%9A%84%E6%95%B0%E6%8D%AE
