### ISSUE TITLE
[Bug Report] lazy image is not work when it changes src

### ISSUE THREAD

**Issue by zycoJamie** [element-plus/element-plus#3210]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
chrome 92.0.4515.159

### Vue version
3.2.8

### Reproduction Link
https://codesandbox.io/s/friendly-pond-4ht68?file=/src/ImageDemo.vue

### Steps to reproduce
just waiting for  that "setTimeout" is called, there are two el-image, i hope the last is loaded lazily. but i do not trigger loading by scrolling, i just change src of el-image. at last, all pictures are loaded, the effect did not meet expectations.

### What is Expected?
Changing src of image, images that are invisible are not loaded. the visible el-image is loaded in container.

### What is actually happening?
Changing src of image, all pictures are loaded and lazy loading does not work.

**Comment by zycoJamie** [comment]
![problem](https://user-images.githubusercontent.com/27729870/131944033-ea88c45c-afd3-4e88-8d37-322dea37bf0b.gif)

**Comment by msidolphin** [comment]
I think it is caused by you using the wrong key, try to use a unique id instead of idx
