### ISSUE TITLE
[Bug Report] Uncaught ReferenceError: exports is not defined when import element-plus with CDN ?

### ISSUE THREAD

**Issue by linrongbin16** [element-plus/element-plus#3213]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
macOS Catalina 10.15.7 / Firefox 91.0.2 x64

### Vue version
3.2.8

### Reproduction Link
https://github.com/linrongbin16/financial_tools_app3

### Steps to reproduce
node version: v16.8.0
npm version: 7.21.0
@vue/cli: 5.0.0-beta.3

Download source code and open with Webstorm, install dependency with npm. then start with vue/cli service, the page console will report error:
```
Uncaught ReferenceError: exports is not defined
```

This error comes from `<script src="https://cdn.jsdelivr.net/npm/element-plus@1.1.0-beta.8/lib/index.min.js"></script>`:
```
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});
```

### What is Expected?
import element-plus with CDN correctly

### What is actually happening?
cannot import element-plus with CDN

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/131954756-52cb12d9-885b-4c44-ace3-bdff54d2deb6.png)
We have a typo in package.json, is anyone interested in helping us fix it?

**Comment by linrongbin16** [comment]
Sorry since I'm really new as a frontend engineer, I'm still confused by how to fix it and the typo thing.

**Comment by msidolphin** [comment]
> Sorry since I'm really new as a frontend engineer, I'm still confused by how to fix it and the typo thing.
> Would you please teach me?

You can search in the internet, such as how to contribute code to `github`

**Comment by linrongbin16** [comment]
cool

**Comment by sxzz** [comment]
Merged! Waiting for the next release.
