### ISSUE TITLE
[Bug Report] Variables assigned using variables cannot be customized

### ISSUE THREAD

**Issue by shinwoow** [element-plus/element-plus#3215]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
win

### Vue version
3.2.8

### Reproduction Link
https://codesandbox.io/s/new-dew-9u6qo?file=/src/var.scss

### Steps to reproduce
When I try to modify a variable assigned by another SCSS variable, it always doesn't work.

### What is Expected?
The table header color change

### What is actually happening?
The table header color not change when i modify the default scss variable

**Comment by msidolphin** [comment]
We don't have the variable `$--table-header-background-color` , you can implement this like:
```scss
$--table: (
  'header-background-color': red,
);
```
