### ISSUE TITLE
[Bug Report] The commit template on the document is incorrect

### ISSUE THREAD

**Issue by adaex** [element-plus/element-plus#3216]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
All Browser

### Vue version
3.2.8

### Reproduction Link
none

### Steps to reproduce

![image](https://user-images.githubusercontent.com/29560987/131958570-f82f8b38-b9fc-4a77-98c4-9b5324e009e6.png)

Modify some files, then submit the code by the following command
```bash
git commit -m "feat(button): add type 'button' for form usage #1234"
```

### What is Expected?
Can submit the code normally

### What is actually happening?
Unable to submit the code, report an error

![image](https://user-images.githubusercontent.com/29560987/131958529-3ad41d4c-6fc5-44fe-84d0-32d53c726bce.png)

**Comment by adaex** [comment]
We have a typo in `README.md`, is anyone interested in helping us fix it?

**Comment by JeremyWuuuuu** [comment]
> We have a typo in `README.md`, is anyone interested in helping us fix it?

Plus I think we better add a space after `:`

**Comment by KimYangOfCat** [comment]
> We have a typo in `README.md`, is anyone interested in helping us fix it?

I can fix it.
