### ISSUE TITLE
[Bug Report] Warning @charset rule when using yarn build

### ISSUE THREAD

**Issue by adiramardiani** [element-plus/element-plus#3219]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Windows

### Vue version
3.2.8

### Steps to reproduce
When I use yarn build, some scss give warning about @charset first rule

### What is Expected?
When using yarn build, not show warning (currently on beta stage, I hope on stable release this issue is not show)

### What is actually happening?
warnings when minifying css:
![image](https://user-images.githubusercontent.com/8703419/131965560-5006e192-074f-402c-b6cb-38be1cdaeb10.png)

_edited by @sxzz_

## Track
- [ ] https://github.com/vitejs/vite/issues/5323

**Comment by shiguanghai** [comment]
我遇到了相似的问题 版本在1.1.0-beta.8 和 1.1.0-beta.9 都不行。 vue版本3.2.6
![image](https://user-images.githubusercontent.com/46474644/132158492-e354500c-6a13-4d93-9e08-a6be317c60c9.png)

**Comment by huzedong2015** [comment]
**+1**

**Comment by sxzz** [comment]
Just ignore it for now, we will fix it (in the future 😅)

**Comment by adarshmadrecha** [comment]
Just FYI, same issue when using Vite `2.5.10`, vue `3.2.13`, element-plus `1.1.0 beta13` and npm `7.23.0`

![image](https://user-images.githubusercontent.com/11911938/134358273-bc1f2951-a4a3-41fe-ad7d-9f6325917bae.png)

**Comment by YunYouJun** [comment]
I also encountered this problem when using other content(not element-plus) and vite.

So I think this is a problem related to vite or plugins of vite.

**Comment by YunYouJun** [comment]
Put a link to vite to track the problem. https://github.com/vitejs/vite/issues/5323

**Comment by IrvingZhao** [comment]
我找到了一个新的发现
只有 checkbox.scss 文件经过 sass 编译后，会有一个 @charset 'UTF-8' 的内容
在我使用webstorm把文件编码转成 ISO-8859-1再转回UTF-8后，再使用sass编译后，就没有问题了
我怀疑是这个文件的编码有问题

发现流程：
编译时，输出 warnings when minifying css，根据关键字 minifying css 找到 minifyCSS 函数，发现在 esbuild.transform 时，传入的css内容中，在el-checkbox样式前，多了一段 @charset 'UTF-8';的代码，个人感觉可能是checkbox.scss文件出了问题，但是在代码中，并未发现相关内容，所以尝试使用sass进行一次编译，发现编译结果中，包含 @charset 'UTF-8' 的内容。后面尝试修改编码后，问题消失。

同步验证，在开启动态引入的时候，取消对el-checkbox组件的引入，编译时，不会出现这个问题

element-plus 版本：1.2.0-beta.1
建议官方把所有的sass文件的编码都检查一下，以免再出现类似问题

**Comment by IrvingZhao** [comment]
刚刚对比了一下修改编码后的文件的区别
发现有一段中文注释被修改了，疑似是因为具有中文注释，sass编译时，指定了css的编码

**Comment by YunYouJun** [comment]
Thank you for your discovery, we will remove the Chinese comments to avoid this problem.

> Of course, I think that vite should optimize this someday in the future.

**Comment by IrvingZhao** [comment]
@YunYouJun 事实上这个和vite没有关系，单纯的sass的编译问题，可能vite不想侵入更多的配置吧
不过在vite.config.ts中，可以添加
```
export default defineConfig({
  css: {
    preprocessorOptions: {
      scss: {
        charset: false
      }
    }
  }
})
```
这样可以关闭sass的@charset输出，仅代码带来的效果，还未找到相关性的文档

**Comment by YunYouJun** [comment]
I think this problem has been resolved as @IrvingZhao said above, and I will close it.
If you still have questions, you can leave a message here.

**Comment by neohan666** [comment]
> @YunYouJun 事实上这个和vite没有关系，单纯的sass的编译问题，可能vite不想侵入更多的配置吧 不过在vite.config.ts中，可以添加
> 
> ```
> export default defineConfig({
>   css: {
>     preprocessorOptions: {
>       scss: {
>         charset: false
>       }
>     }
>   }
> })
> ```
> 
> 这样可以关闭sass的@charset输出，仅代码带来的效果，还未找到相关性的文档

没有效果

**Comment by IrvingZhao** [comment]
@neohan666 这个配置是使用库`sass`后并开启编译scss后的配置，如果使用其他的库或者其他的编译方式，需要找对应的库的配置

**Comment by yaochengGit** [comment]
less也有这个问题
```
rendering chunks (2)...warnings when minifying css:
 > <stdin>:8:0: warning: "@charset" must be the first rule in the file
    8 │ @charset "UTF-8";:root{--el-color-white:#ffffff;--el-color-black:#000...
      ╵ ~~~~~~~~
   <stdin>:1:0: note: This rule cannot come before a "@charset" rule
    1 │ * {
      ╵ ^


 > <stdin>:8:0: warning: "@charset" must be the first rule in the file
    8 │ @charset "UTF-8";:root{--el-color-white:#ffffff;--el-color-black:#000...
      ╵ ~~~~~~~~
   <stdin>:5:0: note: This rule cannot come before a "@charset" rule
    5 │ body, html {
      ╵ ^
```

**Comment by IrvingZhao** [comment]
@yaochengGit 这个警告是vite打包的时候压缩css导致的，被压缩的文件中，非第一行，出现了@charset，解决的思路是，把压缩之前的css中的@charset去掉，去掉的方式包括但不限于配置css预编译组件参数

**Comment by FlameMida** [comment]
1.2.0 b5 vite 2.7.1 复现了

**Comment by YunYouJun** [comment]
通常是由于 sass 文件中包含中文字符注释所导致，将会检查下。

**Comment by jerrytang67** [comment]
修改vite.config.ts，加入
```
    css: {
      postcss: {
        plugins: [
          {
            postcssPlugin: 'internal:charset-removal',
            AtRule: {
              charset: (atRule) => {
                if (atRule.name === 'charset') {
                  atRule.remove();
                }
              }
            }
          }
        ],
      },
    }
```

**Comment by vologo** [comment]
我这里的情况是写了一段不支持的中文注释 。用 // 中文注释 就没问题

**Comment by YunYouJun** [comment]
> 我这里的情况是写了一段不支持的中文注释 。用 // 中文注释 就没问题

`/* */` 的方式会导致 CSS 注释也被编译进最终产物，使用 `//` 即可。
