### ISSUE TITLE
[Bug Report] If the message verified by el-form is ""   validate  return true   Verification will pass

### ISSUE THREAD

**Issue by DylightChen** [element-plus/element-plus#3227]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Mac

### Vue version
3.2.8

### Reproduction Link
https://codesandbox.io/embed/vigilant-chebyshev-5e789?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
click submit   validate  return true  

### What is Expected?
I compared the previous version, there should be a required prompt by default

### What is actually happening?
It has not been verified, but the result returns true

**Comment by sxzz** [comment]
Close due to #3227.
