### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by Linkontoask** [element-plus/element-plus#323]
运行 storybook 报以上错误。

![image](https://user-images.githubusercontent.com/26475695/93571840-97def180-f9c7-11ea-93bd-b3aada2ae1be.png)

**Comment by zazzaz** [comment]
please use 'yarn website-dev' instead, please.

**Comment by JeremyWuuuuu** [comment]
Please refer to #316

**Comment by zazzaz** [comment]
I've updated the readme accordingly.
