### ISSUE TITLE
[Bug Report] Please provide an ESM (ES Module) that is importable directly from the browser

### ISSUE THREAD

**Issue by acrodrig** [element-plus/element-plus#3232]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Mac OS

### Vue version
3.2.8

### Reproduction Link
https://codepen.io/iamkun/pen/Tusfkr545A

### Steps to reproduce
Any code

### What is Expected?
Being able to do something like:

```
import ElementPlus from "https://unpkg.com/element-plus";
```

### What is actually happening?
It is impossible to do

**Comment by imswk** [comment]
You can use webpack to depend on externals #3211

**Comment by acrodrig** [comment]
I do not use webpack - bundlers are the scourge of web dev IMO :) . It would be nice to use the library as a module even for people that do not use webpack. Thanks.

**Comment by sxzz** [comment]
Hi, we already finsh a first prototype version. please reference: https://play.element-plus.org/

**Comment by rotu** [comment]
@sxzz this appears to only work with element-plus v1.1.0-beta.9.  Older versions display nothing and newer versions give:

> Uncaught TypeError: Failed to resolve module specifier "@vueuse/core". Relative references must start with either "/", "./", or "../"

**Comment by sxzz** [comment]
@rotu 
I will fix it later.
There is indeed a problem with versions `v1.1.0-beta.9` and `v1.1.0-beta.10, so please skip these two versions and use version `v1.1.0-beta.11`.

**Comment by sxzz** [comment]
@rotu For now, you can modify import map
```json
{
  "imports": {
    "vue": "https://unpkg.com/@vue/runtime-dom@latest/dist/runtime-dom.esm-browser.js",
    "element-plus": "https://unpkg.com/element-plus@latest/es",
    "@vue/shared": "https://unpkg.com/@vue/shared@latest/dist/shared.esm-bundler.js",
    "lodash/": "https://unpkg.com/lodash-es@4/",
    "@popperjs/core": "https://unpkg.com/@popperjs/core@2/dist/esm",
    "normalize-wheel": "https://unpkg.com/@sxzz/normalize-wheel-es@0.0.2/index.js",
    "resize-observer-polyfill": "https://unpkg.com/resize-observer-polyfill@1.5/dist/ResizeObserver.es.js",
    "dayjs": "https://unpkg.com/dayjs@1/esm",
    "dayjs/": "https://unpkg.com/dayjs@1/esm/",
    "mitt": "https://unpkg.com/mitt@3/dist/mitt.mjs",
    "async-validator": "https://unpkg.com/async-validator@3/dist-web/index.js",
    "@vueuse/core": "https://unpkg.com/@vueuse/core@6.3.3/index.mjs",
    "vue-demi": "https://unpkg.com/vue-demi@0.11.4/lib/v3/index.mjs",
    "@vueuse/shared": "https://unpkg.com/@vueuse/shared@6.3.3/index.mjs"
  }
}
```

**Comment by sxzz** [comment]
@rotu  Fixed.

**Comment by rotu** [comment]
I was able to get the example going with `element-plus@1.1.0-beta.12`, though I'm still having issues consuming this as a *real* ES module.

Importing the script `https://unpkg.com/element-plus@1.1.0-beta.12/dist/index.full.js` causes an immediate error. It tries immediately to invoke `vue.defineComponent`, even though `vue` is not yet defined. I would expect no Vue methods to be resolved until I've explicitly loaded the plugin with `app.use(ElementPlus)` and for me to be able to import modules in an arbitrary order.

**Comment by sxzz** [comment]
Please use ESM version: https://unpkg.com/element-plus@latest/es

**Comment by rotu** [comment]
> Please use ESM version: https://unpkg.com/element-plus@latest/es

No dice. I'm getting the following problem in Edge, Chrome, Safari, and Firefox:

```
> import("https://unpkg.com/element-plus@latest/es")

Uncaught (in promise) TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".
```

**Comment by sxzz** [comment]
Did you add import map? For more information, you can see https://github.com/element-plus/element-plus-playground .
```json
{
  "imports": {
    "vue": "https://unpkg.com/@vue/runtime-dom@latest/dist/runtime-dom.esm-browser.js",
    "element-plus": "https://unpkg.com/element-plus@latest/es",
    "@vue/shared": "https://unpkg.com/@vue/shared@latest/dist/shared.esm-bundler.js",
    "lodash/": "https://unpkg.com/lodash-es@4/",
    "@popperjs/core": "https://unpkg.com/@popperjs/core@2/dist/esm",
    "normalize-wheel": "https://unpkg.com/@sxzz/normalize-wheel-es@0.0.2/index.js",
    "resize-observer-polyfill": "https://unpkg.com/resize-observer-polyfill@1.5/dist/ResizeObserver.es.js",
    "dayjs": "https://unpkg.com/dayjs@1/esm",
    "dayjs/": "https://unpkg.com/dayjs@1/esm/",
    "mitt": "https://unpkg.com/mitt@3/dist/mitt.mjs",
    "async-validator": "https://unpkg.com/async-validator@3/dist-web/index.js",
    "@vueuse/core": "https://unpkg.com/@vueuse/core@6.1/index.esm.js",
    "vue-demi": "https://unpkg.com/vue-demi/lib/v3/index.mjs",
    "@vueuse/shared": "https://unpkg.com/@vueuse/shared@6.1/index.esm.js"
  }
}
```

**Comment by rotu** [comment]
Thank you for the pointers!

I got it to work but it feels like there are a few speed bumps that make it awkward to use Element Plus as an ESM:

1. Firefox and Safari *don't* support import maps but *do* support ESM so you need a polyfill/shim or else importing still fails.
2. This code is required to prevent a crash: `window.process = { env: {} };`. It would be nice if it were not necessary.
3. Specifying how to resolve dependencies seems like a bad idea. I *do* expect to have to specify my version of `vue` since this can affect what I can do with `element-plus` components. But I *don't* expect to have to specify other dependencies. For example `dayjs` is an implementation detail - it should probably be either (a) bundled up in the `element-plus` build process such that the importing code doesn't need to know about it or (b) imported via a fully qualified URL.

**Comment by sxzz** [comment]
> 1. Firefox and Safari _don't_ support import maps but _do_ support ESM so you need a polyfill/shim or else importing still fails.

There seems to be no other way.

> 2. This code is required to prevent a crash: `window.process = { env: {} };`. It would be nice if it were not necessary.

According to the Vue repository, this is just for supporting to the old version of Vue. Please use the latest vue. Then maybe you can delete this line.

https://github.com/vuejs/vue-next/blob/64aa8e26ae6c5db927b18bde01fbe0eb4ef460aa/packages/sfc-playground/index.html#L10

> 3. Specifying how to resolve dependencies seems like a bad idea. I _do_ expect to have to specify my version of `vue` since this can affect what I can do with `element-plus` components. But I _don't_ expect to have to specify other dependencies. For example `dayjs` is an implementation detail - it should probably be either (a) bundled up in the `element-plus` build process such that the importing code doesn't need to know about it or (b) imported via a fully qualified URL.

For ESM version, there is currently no full version, and it may be added in the future.

**Comment by rotu** [comment]
> > 1. Firefox and Safari _don't_ support import maps but _do_ support ESM so you need a polyfill/shim or else importing still fails.
> 
> There seems to be no other way.

I can see 3 ways, and I don't know which is best: 1) bundle the external modules into Element Plus in the build process 2) vendor the external modules in Element Plus and use relative urls 3) Import from a fully qualified CDN URL.

> > 1. This code is required to prevent a crash: `window.process = { env: {} };`. It would be nice if it were not necessary.
> 
> According to the Vue repository, this is just for supporting to the old version of Vue. Please use the latest vue. Then maybe you can delete this line.
> 
> https://github.com/vuejs/vue-next/blob/64aa8e26ae6c5db927b18bde01fbe0eb4ef460aa/packages/sfc-playground/index.html#L10

This does appear with the latest Vue. I suspect this code in `@vue/shared@3.2.13` is not meant to run in-browser.

```
Uncaught (in promise) ReferenceError: process is not defined
    at shared.esm-bundler.js:472
(anonymous) @ shared.esm-bundler.js:472
```

> 
> > 1. Specifying how to resolve dependencies seems like a bad idea. I _do_ expect to have to specify my version of `vue` since this can affect what I can do with `element-plus` components. But I _don't_ expect to have to specify other dependencies. For example `dayjs` is an implementation detail - it should probably be either (a) bundled up in the `element-plus` build process such that the importing code doesn't need to know about it or (b) imported via a fully qualified URL.
> 
> For ESM version, there is currently no full version, and it may be added in the future.

This also came back to bite me today as the latest version of element-plus on both my machine and as deployed at play.element-plus.org has a missing dependency: `Failed to resolve module specifier "memoize-one"`.

---

Thank you for your hard work already. I can see that deploying Javascript code is not the easiest problem, and was hoping that ESM could simplify things by using more browser-native functionality.

**Comment by sxzz** [comment]
@rotu Thank you, we will continue to optimize the ESM version, but our current focus may not be on ESM.

About memoize-one, because we have added a new dependency, `memoize-one`, which will be updated to the playground later.

**Comment by sxzz** [comment]
@rotu We just released full esm version.

`https://unpkg.com/element-plus@latest/dist/index.full.mjs`
