### ISSUE TITLE
Datetime picker with default time queries

### ISSUE THREAD

**Issue by newbie2005** [element-plus/element-plus#3244]
Refer to datetime picker with default time, 
https://element-plus.org/#/en-US/component/datetime-picker

I found the time value can't change after set a default time, if 
dest not set default time, the time value can't changed

**Comment by newbie2005** [comment]
https://codepen.io/newbie2005/pen/powwzwK
If default time value setted, user can't change the time value in time pickupbox

**Comment by Alanscut** [comment]
fixed by #4228
