### ISSUE TITLE
[Bug Report] el-date-picker type=“daterange” no work

### ISSUE THREAD

**Issue by chenxinan** [element-plus/element-plus#3252]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
mac

### Vue version
3.2.9

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-8dq98?file=/src/App.vue

### Steps to reproduce
just pick the time can reproduce this

### What is Expected?
work

### What is actually happening?
pick with no reapson and select

**Comment by imswk** [comment]
`:default-time`  type  `Date / range: Date[]` Can't be `Sting`

**Comment by Wynnfan** [comment]
> `:default-time` type `Date / range: Date[]` Can't be `Sting`

and import error , app.use(ElementPlus)

**Comment by chenxinan** [comment]
> `:default-time` type `Date / range: Date[]` Can't be `Sting`

thx it work
