### ISSUE TITLE
[Feature Request] Add the el-upload attribute  

### ISSUE THREAD

**Issue by pingguanfei** [element-plus/element-plus#3253]
### Existing Component
Yes

### Component Name
el-upload

### Description
Currently, multiple attachment submissions send multiple requests. It is recommended to add attributes to control whether multiple files should be submitted at once.

**Comment by xiaoxian521** [comment]
可以参考这个https://blog.csdn.net/qq_39228609/article/details/115319746?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.no_search_link&spm=1001.2101.3001.4242
使用http-request属性覆盖默认的上传行为，可以自定义上传的实现
