### ISSUE TITLE
[Bug Report] el-cascader multiple search can not use keyboard select node

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#3254]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Microsoft Edge 版本 95.0.997.1 (官方内部版本) dev (64 位)

### Vue version
3.2.9

### Reproduction Link
https://jsfiddle.net/v0yz6trd/

### Steps to reproduce
type some word，and then use 'up', 'down' and 'enter' keys found that don‘t work

### What is Expected?
can use the keys to select node

### What is actually happening?
can not use the keys

-------------------------------------------------------------------------------------------------------------
i think this is a bug because when you not type word you can use keyboard to select node.
so i create this issue link an i am working on fix it .

**Comment by imswk** [comment]
Operate after `cascader` gets the focus

**Comment by Alanscut** [comment]
> Operate after `cascader` gets the focus

![image](https://user-images.githubusercontent.com/21104054/132172998-a57e95eb-8fce-4c9c-b863-44245a5f93dc.png)
我说的是这种输入文本后的过滤列表，没法办法上下方向键移动，enter选中

**Comment by imswk** [comment]
Thanks, this is a bug。
