### ISSUE TITLE
[Bug Report] When I use the el-menu component, use the configuration mode="horizontal", an infinite loop appears 

### ISSUE THREAD

**Issue by hsiangleev** [element-plus/element-plus#3256]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Microsoft Edge 93.0.961.38

### Vue version
3.2.9

### Reproduction Link
https://codesandbox.io/s/pensive-margulis-eusdt?file=/index.html

### Steps to reproduce
1. el-menu use mode="horizontal"
2. el-sub-menu use "v-for"

### What is Expected?
Horizontal menu bar 

### What is actually happening?
The browser is stuck and the memory keeps increasing, but deleting the mode="horizontal" attribute is normal

**Comment by xiaotongXT** [comment]
我也遇见了，mode="horizontal"时死循环

**Comment by aslrz-club** [comment]
我还以为是我的问题 浪费了我一个小时 使用v-for 页面直接卡死 死循环可还行

**Comment by ClarenceStar** [comment]
这个版本发了嘛  最新的还是1.1.0-beta.9 依然有这个问题

**Comment by sxzz** [comment]
还没，今晚发版吧

**Comment by ClarenceStar** [comment]
👌 非常感谢

**Comment by xiaotongXT** [comment]
mode="horizontal" 时怎么又死循环了，还是这个例子https://codesandbox.io/s/pensive-margulis-eusdt?file=/index.html，将3改成7，也就是说，在横向超出并且出现 ... 时，就死循环了，当菜单数量较少不会出现 ... 时，就没问题

**Comment by xiaotongXT** [comment]
mode="horizontal" 时怎么又死循环了，还是这个例子
https://codesandbox.io/s/pensive-margulis-eusdt?file=/index.html
将for循环的3改成7，也就是说，在横向超出并且出现 ... 时，就死循环了，当菜单数量较少（不会出现 ... ）时，就没问题

**Comment by mexican-jack** [comment]
i'm still having this issue on beta.10 - it appears to be making infinite copies of handleResize directive from this line:

` props.mode === 'horizontal'
        ? withDirectives(vnode, [[Resize, handleResize]])
        : vnode`
in menu.ts

**Comment by mexican-jack** [comment]
![image](https://user-images.githubusercontent.com/16663045/133208124-1f452b3b-4c77-457b-9e57-6d50c5522a01.png)

**Comment by panchenyu0928** [comment]
> mode="horizontal" 时怎么又死循环了，还是这个例子
> https://codesandbox.io/s/pensive-margulis-eusdt?file=/index.html
> 将for循环的3改成7，也就是说，在横向超出并且出现 ... 时，就死循环了，当菜单数量较少（不会出现 ... ）时，就没问题

@sxzz 遇到同样的问题，有空麻烦关注下。十分感谢

**Comment by sxzz** [comment]
@panchenyu0928 OK. Could you please new another issue for this problem.

**Comment by mexican-jack** [comment]
I think it has something to do with the create resizeHandler Directive hook in menu.ts,  its creating an infinite number of directive binds when using sub-menu - i solved this by wrapping sub-menu inside a span.

**Comment by sxzz** [comment]
@mexican-jack Hi, would you mind create a PR about this problem.

**Comment by mexican-jack** [comment]
sure - i'm away from my PC right now - will do it when i get a chance.

**Comment by hooray** [comment]
the problem in the 1.1.0-beta.12 still haved

**Comment by mexican-jack** [comment]
@sxzz I'm sorry but i have been unable to do a PR - but i have since figured out the issue:

the issue exists on the render function of menu.ts:359
![image](https://user-images.githubusercontent.com/16663045/133586324-d9d7328e-8b24-4421-80bc-f9dfb8e986c5.png)

the force update inside the render function is triggering a re-render which, is essentially creating a render loop. removing this line fixes the nav - but i'm not sure what it impacts

**Comment by mexican-jack** [comment]
I recreated the issue here:
https://github.com/ElemeFE/element/issues/21324
