### ISSUE TITLE
[bug report] dialog pop-up window transform delayed execution

### ISSUE THREAD

**Issue by Yaozefen** [element-plus/element-plus#3262]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Windows 10 家庭中文版 20H2  /   Google Chrome 版本 92.0.4515.131（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://jsfiddle.net/Yaozefeng/L76vc9ot/

### Steps to reproduce
弹窗对translateY(-50%);垂直居中进行了动画过渡

### What is Expected?
top：50%和translateY(-50%);是通用的垂直居中方法，不应该出现动画的行为。      在弹窗出现之前就应该完成translateY(-50%);

### What is actually happening?
在弹窗出现之后动画过渡完成translateY(-50%);

**Comment by adaex** [comment]
I tried to solve this problem.

By the way, if you want the dialog is centered vertically, you still need to override `margin-top` property.

```css
margin-top: 0 !important;
top: 50%;
transform: translateY(-50%);
```

**Comment by Yaozefen** [comment]
Thank you, sir

**Comment by Yaozefen** [comment]
Thank you, sir. But if I'm not mistaken, the el-dialog originally has margin: 0 auto 50px; So margin top: 0! important; It seems unnecessary

**Comment by Yaozefen** [comment]
thank you,sir
