### ISSUE TITLE
[bug report] the change event callback parameter of the select selector is unreasonable

### ISSUE THREAD

**Issue by dabaii** [element-plus/element-plus#3264]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
windows10

### Vue version
3.2.9

### Reproduction Link
https://jsfiddle.net/none

### Steps to reproduce
文档显示Select 的change事件回调参数为 "目前的选中值",但是change事件属于html 的内置事件，应该遵循参数返回(event: Event)。

vue的vscode插件(volar)会对template部分进行ts语法分析，会为默认事件添加对应的类型。这样导致出现ts类型校验出错。

~~~
@change="handleChange"
~~~

"不能将类型“(value: string) => void”分配给类型“(payload: Event) => void”。 参数“value”和“payload” 的类型不兼容。",

目前vuter对template部分的ts校验做的比较滞后，所以很多开发者中并没有感受到这样设计change事件的回调参数有什么问题。

### What is Expected?
如果可以，希望与html内置事件名称一致的，也保证参数类型上一致。

### What is actually happening?
😛

**Comment by sxzz** [comment]
I'm sorry, but I can't reproduce the problem you mentioned.

**Comment by sxzz** [comment]
Hi, could you please provide more detailed information?

**Comment by dabaii** [comment]
问题的起因是 使用volar插件对template部分进行类型检查。而不是使用vatur插件进行检查。因为volar由更加详细的类型检查机制。

目前看问题已经解决了。

volar插件版本更新后，已经对@change 事件的类型 由 change: (payload: Event) => void 更改为 change: any。
相当于放弃了对@change事件进行类型校验。😳

**Comment by sxzz** [comment]
😅 Hope that Volar can parse the types of emits in the future.
