### ISSUE TITLE
[bug report] using V-for rendering for El menu item component will cause browser memory overflow and crash

### ISSUE THREAD

**Issue by dwhmofly** [element-plus/element-plus#3273]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
windows10 Google Chrome 92.0.4515.159（正式版本） （64 位）

### Vue version
3.2.9

### Reproduction Link
https://codepen.io/woden17/pen/dyROmOw

### Steps to reproduce
1.1.0-beta.9 在<el-menu mode = 'horizontal'> 标签内使用v-for渲染el-menu-item 组件即可重现 (只有el-menu标签 mode属性为'horizontal'时会出现此问题)

### What is Expected?
正确循环渲染出el-menu-item组件

### What is actually happening?
页面一致进不去，最后浏览器会报内存溢出

**Comment by ioslh** [comment]
#3256
