### ISSUE TITLE
[bug report] NPM install element plus -- after saving from beta. 8 to beta. 9, the page jumps to no response（ (no such problem in beta.8 and before)

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#3276]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Google Chrome版本 93.0.4577.63（正式版本） （64 位）

### Vue version
3.2.6

### Reproduction Link
https://codepen.io/peyfon/pen/KKqzJBq

### Steps to reproduce
由于必须要填写重现链接所以我只能随便写一个。
1.我把package.json文件内的版本号 ^1.1.0-beta.8改为^1.1.0-beta.9，  然后删掉了node_modules文件夹内element-plus文件夹 。
2.我运行了npm install element-plus --save 然后启动项目发现我的登录页点击后url改变了但页面并无变化无报错且过段时间后浏览器会提示页面无响应（此时同事的电脑上并无这个问题）。
3.经过排查找出是node_modules文件夹的问题。于是我整个删掉node_modules文件夹和package-lock.json，同时升级node版本至v14.17.6，清理相关缓存。但仍旧无效
4.我把同事的node_modules文件夹拷贝过来 并运行 npm install  ，在package.json内把版本号写死为1.1.0-beta.8  这时项目正常运行。我尝试把版本号改为^1.1.0-beta.9，这时项目出现之前的页面无变化无响应错误。
5.我让同事把版本号升级为^1.1.0-beta.9也出现了这个错误。

### What is Expected?
页面应该能正常响应

### What is actually happening?
只有url变化，页面无变化无报错且浏览器会提示页面无响应

**Comment by PeyFon** [comment]
页面是个普通的登录页。且要跳转到的目标页面只有个div文本一行js代码都没有

**Comment by PeyFon** [comment]
登录页使用了el-form ，el-button和el-input 这三种组件，但我打断点查找的时候并未发现登录页问题

**Comment by msidolphin** [comment]
我猜你使用了el-menu？这个组件目前好像会出现死循环，已经被修复了，预计下个版本带出

**Comment by PeyFon** [comment]
> 我猜你使用了el-menu？这个组件目前好像会出现死循环，已经被修复了，预计下个版本带出

是的，做的是个后台管理的系统，确实用到了。那我等下个版本再升级试试。

**Comment by chenroaming** [comment]
我也出现了一样的问题，从beta8升级到beta9出现，回退beta8后正常。在同事的电脑上也是如此，beta8及之前版本正常，beta9就不行。

**Comment by PeyFon** [comment]
> 我也出现了一样的问题，从beta8升级到beta9出现，回退beta8后正常。在同事的电脑上也是如此，beta8及之前版本正常，beta9就不行。

我花了近一天的时间才确定下来是版本的原因

**Comment by PeyFon** [comment]
> 我也出现了一样的问题，从beta8升级到beta9出现，回退beta8后正常。在同事的电脑上也是如此，beta8及之前版本正常，beta9就不行。

期待下一版不会有这个问题
