### ISSUE TITLE
[Bug Report] TimePicker、DatePicker、Dialog (and there may be others) don't support v- directives.

### ISSUE THREAD

**Issue by microkof** [element-plus/element-plus#3281]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
window 7/ chrome 70

### Vue version
3.2.10

### Reproduction Link
https://codepen.io/microkof/pen/MWoJbqa

### Steps to reproduce
Set any v-x for TimePicker, datepicker or Dialog.
v-x will not take effect and the console will print: Runtime directive used on component with non-element root node. The directives will not function as intended.

I didn't test on other components. I don't rule out the possibility that other components also have this bug.

### What is Expected?
I want all components to use v-x directives.

### What is actually happening?
Not work.

**Comment by xiaoxian521** [comment]
https://v3.cn.vuejs.org/guide/custom-directive.html#%E5%9C%A8%E7%BB%84%E4%BB%B6%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by microkof** [comment]
> https://v3.cn.vuejs.org/guide/custom-directive.html#%E5%9C%A8%E7%BB%84%E4%BB%B6%E4%B8%AD%E4%BD%BF%E7%94%A8

Is there any official plan to let the components I listed support custom directives? Especially the Dialog component.
