### ISSUE TITLE
[Feature Request] autocomplete select attribute 

### ISSUE THREAD

**Issue by cool-delete** [element-plus/element-plus#3295]
### Existing Component
Yes

### Component Name
autocomplete 

### Description
I set up a function to pass @select="handleSelect" The function signature is handleSelect: (item: Icity) => Promise<void> ts will report an error'(item: Icity) => Promise<void>' is not assignable to type 'payload: Event) => void".

![image](https://user-images.githubusercontent.com/13638610/132488237-edb74d8f-688d-4af0-9e25-a3766c9e3c33.png)

The signature of this method should not be Event. It passes parameters according to the cb method in fetch-suggestions, not the event type.

**Comment by sxzz** [comment]
Are you using Volar or Vetur?

**Comment by sxzz** [comment]
Hi, could you provide more detailed information?

**Comment by cool-delete** [comment]
> Are you using Volar or Vetur?

i using Volar

**Comment by sxzz** [comment]
Please upgrade you Volar and try again.
https://github.com/element-plus/element-plus/issues/3264#issuecomment-917152935
