### ISSUE TITLE
[Bug Report] el-input-number click increase/decrease value will change double

### ISSUE THREAD

**Issue by DaiHuaXieHuaKai** [element-plus/element-plus#3312]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
chrome

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=a427764a-c42c-48eb-b26d-e42f412b3182

### Steps to reproduce
click increse or decrease

### What is Expected?
click only increase once

### What is actually happening?
increase double

**Comment by DaiHuaXieHuaKai** [comment]
change the repeat-click directive interval delay time. Now 100ms is too short.

**Comment by Alanscut** [comment]
It doesn't seem to be able to reproduce it.

**Comment by DaiHuaXieHuaKai** [comment]
you can use touchpad reproduce it

---Original---
From: "Alan ***@***.***&gt;
Date: Sat, Sep 11, 2021 10:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] [Bug Report] el-input-number click increase/decrease value will change double (#3312)




 
It doesn't seem to be able to reproduce it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HeftyKoo** [comment]
Duplicated with: #3354
