### ISSUE TITLE
[Bug Report] Code snippet replication problem

### ISSUE THREAD

**Issue by doraemon00** [element-plus/element-plus#3313]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Google Chrome 93

### Vue version
3.2.11

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/5

### Steps to reproduce
官方文档中，组件中示例的代码片段如果有两种模式，切换后，复制的内容一直是 options api 的内容。
例如：https://element-plus.gitee.io/#/zh-CN/component/checkbox 

### What is Expected?
当切换显示内容后，复制出的内容是对应的代码

### What is actually happening?
复制的内容一直是 options api 的内容

**Comment by xiaoxian521** [comment]
fix: https://github.com/element-plus/element-plus/pull/3310/commits/05ab46f4f0219d7869356363393c61704a5cdb5f
