### ISSUE TITLE
[bug report] error will be reported on the: current page console of pagination,: Pager count = "5" warning will be given with value, and the icon positions of prev and next in background mode are incorrect

### ISSUE THREAD

**Issue by Silentdoer** [element-plus/element-plus#3319]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Chrome 73

### Vue version
3.2.11

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
随便写一个简单的table加pagination就能复现

### What is Expected?
:current-page要能正常用，:pager-count也应该能直接绑定数字

### What is actually happening?
有异常

**Comment by adaex** [comment]
Please try the latest version, I can't reproduce the problem on `1.1.0-beta.9`.
