### ISSUE TITLE
What's the difference between the two projects?

### ISSUE THREAD

**Issue by CHOYSEN** [element-plus/element-plus#332]
What's the difference between the two projects?

[https://github.com/kkbjs/element3](https://github.com/kkbjs/element3)

**Comment by zazzaz** [comment]
This is Elenent UI for Vue3.0. All of our contributors are from Element UI.

**Comment by CHOYSEN** [comment]
> Element Plus is Elenent UI for Vue3.0. All of our contributors are from Element UI.

ok thanks
