### ISSUE TITLE
[bug report] plus does not have a breakpoint based hidden class import 'element plus / lib / theme talk / display. CSS' file

### ISSUE THREAD

**Issue by flowerburied** [element-plus/element-plus#3331]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
win11

### Vue version
3.2.11

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
2.0有 plus没有 基于断点的隐藏类 import 'element-plus/lib/theme-chalk/display.css' 文件

### What is Expected?
npm添加 基于断点的隐藏类 import 'element-plus/lib/theme-chalk/display.css' 文件

### What is actually happening?
2.0有 plus没有 基于断点的隐藏类 import 'element-plus/lib/theme-chalk/display.css' 文件

**Comment by Alanscut** [comment]
import 'element-plus/theme-chalk/display.css'
