### ISSUE TITLE
[bug report] why add float: right to the menu; Some menus will appear on the right... Fold out

### ISSUE THREAD

**Issue by duanzhichao** [element-plus/element-plus#3332]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
chrome93.0.4577.63

### Vue version
3.2.11

### Reproduction Link
https://jsfiddle.net/tu68nb01/4/

### Steps to reproduce
写一个nav-menu，加入float: right

### What is Expected?
如果正常情况下，应该是全部显示，或者提供参数

### What is actually happening?
自动折叠

**Comment by xiaoxian521** [comment]
For horizontal mode, you can set the width="100%" of el-menu

**Comment by adaex** [comment]
@duanzhichao  Use `justify-content: flex-end` instead of `float: right`, see: https://jsfiddle.net/4xqrysa2/

**Comment by duanzhichao** [comment]
> @duanzhichao 使用`justify-content: flex-end`代替`float: right`，见：[https](https://jsfiddle.net/4xqrysa2/) : //jsfiddle.net/4xqrysa2/[](https://jsfiddle.net/4xqrysa2/)

谢谢,可以了
