### ISSUE TITLE
when updating version element plus, the theme-chalk version is reset to 0.0.0

### ISSUE THREAD

**Issue by Anastasia226** [element-plus/element-plus#3338]
![photo_2021-09-10_18-33-24](https://user-images.githubusercontent.com/72441267/132879616-03aa30ee-1f7a-4968-8f20-049c37c1f4ac.jpg)
version passed: "^1.0.2-beta.45",
new version:  "^1.0.2-beta.60",

**Comment by sxzz** [comment]
The latest version is `1.1.0-beta.9`, would you mind upgrade to latest version and try again?

**Comment by sxzz** [comment]
Furthermore, this version seems to be useless to users, so ignore it.

**Comment by Anastasia226** [comment]
it turned out to be updated, but the styles do not work
![photo_2021-09-13_11-10-12](https://user-images.githubusercontent.com/72441267/133047582-34479bfb-39c1-4e61-9772-dd6e11200fa0.jpg)

**Comment by sxzz** [comment]
Please provide a reproduce link. Thanks.
The following is how to import styles.

[Link](https://element-plus.org/#/zh-CN/component/quickstart)

```ts
import 'element-plus/dist/index.css'
```
