### ISSUE TITLE
Add typescript definition ?

### ISSUE THREAD

**Issue by lytian** [element-plus/element-plus#335]

**Comment by g3r4n** [comment]
添加typescript定义 = Add typescript definition ?
Can you be more specific ?

**Comment by lytian** [comment]
How to use it with typescript？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Enguerrand&amp;nbsp;des&amp;nbsp;Vaux&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月23日(星期三) 凌晨4:05
收件人:&nbsp;&quot;element-plus/element-plus&quot;<element-plus@noreply.github.com&gt;;
抄送:&nbsp;&quot;Vincent&quot;<619115125@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 添加typescript定义 (#335)

**Comment by zazzaz** [comment]
@lytian we will add TypeScript support in our future release.

**Comment by lytian** [comment]
OK，Thinks
