### ISSUE TITLE
[Feature Request] HTTP Put support for upload

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#3352]
### Existing Component
Yes

### Component Name
upload

### Description
Sometime, we prefer to use put than post to upload a file.  
Now the post request is hard encode in the impl of [ajax.ts](https://github.com/element-plus/element-plus/blob/dev/packages/components/upload/src/ajax.ts#L81) (a short string), maybe just need add a prop to decide how file upload?

**Comment by sxzz** [comment]
You can use `http-request` to overide default uplaod action.

**Comment by KawaiiZapic** [comment]
> You can use `http-request` to overwrite default upload action.

Yes, this is not hard, copy existed code and change `post` to `put`.   
But that will produce some duplicate code.   
The 1 line is core, but developer must write another 50 line code that already existed.

**Comment by sxzz** [comment]
Yeah, we can find a way to improve it.
