### ISSUE TITLE
[bug report] ERROR @import "~element-plus/packages/theme-chalk/src/index";

### ISSUE THREAD

**Issue by MZHY08** [element-plus/element-plus#3353]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Windows 10

### Vue version
3.2.11

### Reproduction Link
https://github.com

### Steps to reproduce
1、在element-variables.scss 中 @import "~element-plus/packages/theme-chalk/src/index";

2、在main.ts 中 import element-variables.scss

3、启动报错
These dependencies were not found:

* element-plus/lib/theme-chalk/fonts/element-icons.ttf in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/element-variables.scss
* element-plus/lib/theme-chalk/fonts/element-icons.woff in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/element-variables.scss

![image](https://user-images.githubusercontent.com/44521439/132952275-3b393400-9be8-4aaf-8625-c2cec11c94fa.png)

### What is Expected?
正常启动

### What is actually happening?
启动报错

**Comment by themojilla** [comment]
try 

```scss
$--font-path: "element-plus/packages/theme-chalk/src/fonts";
```

**Comment by MZHY08** [comment]
> try
> 
> ```css-scss
> $--font-path: "element-plus/packages/theme-chalk/src/fonts";
> ```

can use

**Comment by yangxj96** [comment]
I ran into the same problem with version 1.0-beta.19.


> > try
> > ```
> > $--font-path: "element-plus/packages/theme-chalk/src/fonts";
> > ```
> 
> can use

I ran into the same problem with version 1.0-beta.19.

This method didn't solve my problem.

Inspired by your answer.



`@forward "../../../node_modules/element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    "primary": (
      "base": green,
    ),
  ),
  **$font-path:'/fonts'**
);

@import "../../../node_modules/element-plus/theme-chalk/src/index.scss";
`

Solved my problem 
:)
