### ISSUE TITLE
[document update] [el-input-number] add focus & blur methods

### ISSUE THREAD

**Issue by adaex** [element-plus/element-plus#3361]
This issue is to remind me that the documentation needs to be updated

> I was considering that we are redesigning the document, so do not be so anxious to modify.
> In addition, the translation of Japanese and French is too difficult.

Can we create an issue for that incase we forget the task? The documentation is still WIP(won't be long though)

_Originally posted by @JeremyWuuuuu in https://github.com/element-plus/element-plus/issues/3337#issuecomment-917614093_

**Comment by adaex** [comment]
- #3337

**Comment by chenxch** [comment]
cc @sxzz  Can this be turned off?
