### ISSUE TITLE
[Bug Report] dialog can not close by model value

### ISSUE THREAD

**Issue by carmel** [element-plus/element-plus#3362]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
 Google Chrome	93.0.4577.63 (Official Build) (x86_64)

### Vue version
3.2.11

### Reproduction Link
https://codesandbox.io/s/dialog-close-error-gcv5f?file=/src/App.vue

### Steps to reproduce
输入框的focus事件会打开对话框。
点取消按钮时，对话框闪动，但无法关闭（直接点击右上角的X图标进行没有这个问题）。
提供的复现示例是可以关闭，但也会闪动。

### What is Expected?
正常关闭对话框

### What is actually happening?
无法正常关闭对话框

**Comment by carmel** [comment]
![image](https://user-images.githubusercontent.com/36031579/132996329-4c3b148b-8358-46b1-b104-2a2bbcdae442.png)

神奇的是，通过button的click事件触发弹窗没任何问题，通过input的focus事件触发却有问题！

**Comment by adaex** [comment]
@carmel  

The possible reason is that when the dialog is closed, the browser automatically focuses on the input box, causing the focus event to be triggered again. 

To verify this, you can try printing the `focus` call.

**Comment by carmel** [comment]
你的推理是对的，我在获得焦点后立即blur就正常了  👍
