### ISSUE TITLE
[Bug Report] please transfer a valid prop path to form item!

### ISSUE THREAD

**Issue by xiaolannuoyi** [element-plus/element-plus#3372]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
macos 11.5.2 / chrome 版本 93.0.4577.63（正式版本） (arm64)

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/xiaolannuoyi/pen/BaZZpjV?editors=1010

### Steps to reproduce
当 表单中的key 中含有特殊符号的时候，prop 如何写？

```
     numberValidateForm: {
          metadata:{
		    age: '',
		   'baidu.com/age':''
		}
        },
      rules:{
         metadata:{
		['age']:[{ required: true, message: '年龄不能为空'}],
		["baidu.com/age"]:[{ required: true, message: '年龄不能为空'}]
	}
    }
				
```

 prop="metadata['baidu.com/age']"   会报 `please transfer a valid prop path to form item!` 错误
```
<el-form-item
    label="年龄2"
    prop="metadata['baidu.com/age']"
    
  >
    <el-input
      v-model.number="numberValidateForm.metadata['baidu.com/age']"
      autocomplete="off"
    ></el-input>
  </el-form-item>
```

### What is Expected?
 prop="metadata['baidu.com/age']" 这样使用能正常使用，或者含有特殊符号的key 如何使用prop

### What is actually happening?
 prop="metadata['baidu.com/age']"   会报 `please transfer a valid prop path to form item!` 错误

**Comment by xiaoxian521** [comment]
<img width="1670" alt="WechatIMG251" src="https://user-images.githubusercontent.com/44761321/133029695-f9adcb7b-4eb8-4b62-8a3a-263d849f0c73.png">
@xiaolannuoyi You will report when you click submit? This link seems to be unable to reproduce this warning

**Comment by xiaolannuoyi** [comment]
![image](https://user-images.githubusercontent.com/21079721/133030265-5a3727d4-214d-4809-807a-5b1b5ee350dd.png)

初始化就会有这个错误。
且 添加的rules 也不好使。

**Comment by xiaolannuoyi** [comment]
![image](https://user-images.githubusercontent.com/21079721/133030694-5e5dea81-221b-47e2-970b-51183c81e916.png)

初始化就会有这个错误。
且 添加的rules 也不好使。

**Comment by xiaoxian521** [comment]
I took a look at the code, it’s not currently supported. This is a new requirement.
@sxzz

**Comment by sxzz** [comment]
@xiaoxian521 Thank you for your feedback.

**Comment by jiaqidegege** [comment]
可以给prop path中的分隔符`:`, `.`添加转义符支持，类似将`prop: "baidu.com/age" `变成`prop: "baidu\.com/age" `

**Comment by xiaolannuoyi** [comment]
@jiaqidegege 

```
<el-form-item
    label="年龄2"
    prop="metadata['baidu.com/age']"
  >
```
 `prop="metadata['baidu\.com/age']"`  这样么？好像不行。
这里的prop，具体要怎么写呢？

**Comment by xiaoxian521** [comment]
@xiaolannuoyi It’s been changed, and you can wait for the next version to be released according to your previous writing.

**Comment by xiaolannuoyi** [comment]
@xiaoxian521 好的谢谢
