### ISSUE TITLE
[Bug Report] [el-popconfirm] Invalid attribute

### ISSUE THREAD

**Issue by ZelinBu** [element-plus/element-plus#3378]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
macOS 11.4/Chrome 92.0.4515.159（正式版本） (x86_64)

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/zelinbu/pen/abwwWMb

### Steps to reproduce
官网气泡确认框中的“自定义”的在线运行代码，其运行结果无法正常显示属性

### What is Expected?
修复该问题

### What is actually happening?
el-popconfirm 修改文字、图标颜色等属性值无法生效

**Comment by adaex** [comment]
HTML attribute names are case-insensitive, so browser will interpret any uppercase characters as lowercase. Therefore, the prop name of `camelCase` needs to be named using its `kebab-case` equivalent.

```vue
<template>
  <el-popconfirm
    confirm-button-text="好的"
    cancel-button-text="不用了"
    icon="el-icon-info"
    icon-color="red"
    title="这是一段内容确定删除吗？"
  >
    <template #reference>
      <el-button>删除</el-button>
    </template>
  </el-popconfirm>
</template>

```
