### ISSUE TITLE
[Bug Report] When element plus is introduced globally, an error is reported when vited is packaged

### ISSUE THREAD

**Issue by miles-rush** [element-plus/element-plus#3382]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
Chrome version 93.0.4577.63

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/persistr/pen/bGRRMad

### Steps to reproduce
Use vite to create a vue3 typescript project and introduce element plus globally

**main.ts**

```
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'

import router from './router/index'
import axios from 'axios'
import {Loading} from '@element-plus/icons'

const app = createApp(App)
app.component('Loading', Loading)

app.use(ElementPlus)
app.use(router)
app.mount('#app')
```

Use **npm run build** to package

### What is Expected?
Pack dist normally

### What is actually happening?

```
node_modules/element-plus/lib/components/menu/src/menuItem.vue.d.ts:1:24 - error TS2307: Cannot find module 'element-plu
s/es/popper' or its corresponding type declarations.

1 import { Effect } from 'element-plus/es/popper';
                         ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/element-plus/lib/components/select-v2/src/defaults.d.ts:4:30 - error TS2307: Cannot find module 'element-pl
us/es/popper' or its corresponding type declarations.

4 import type { Options } from 'element-plus/es/popper';
                               ~~~~~~~~~~~~~~~~~~~~~~~~ 

node_modules/element-plus/lib/components/time-picker/src/common/picker.vue.d.ts:2:24 - error TS2307: Cannot find module 
'element-plus/es/popper' or its corresponding type declarations.

2 import { Effect } from 'element-plus/es/popper';
                         ~~~~~~~~~~~~~~~~~~~~~~~~ 
```

There is no popper file in the corresponding path
After checking, there is an error in the popper path configuration in the appeal file
The path should be configured as element-plus\es\components\popper

**Comment by xiaoxian521** [comment]
It is good, in the latest version
<img width="1130" alt="WechatIMG291" src="https://user-images.githubusercontent.com/44761321/133781210-ddc3a4d9-5ae0-477d-b301-5109937b08f0.png">

**Comment by heng1025** [comment]
> It is good, in the latest version
> <img alt="WechatIMG291" width="1130" src="https://user-images.githubusercontent.com/44761321/133781210-ddc3a4d9-5ae0-477d-b301-5109937b08f0.png">

run `npx vue-tsc --noEmit `, still have the same issue

**Comment by sxzz** [comment]
@heng1025 set `skipLibCheck` to `true`
