### ISSUE TITLE
error   Invalid CSS after "$--colors: map": expected expression (e.g. 1px, bold), was ".deep-merge("

### ISSUE THREAD

**Issue by Anastasia226** [element-plus/element-plus#3384]
![photo_2021-09-13_17-24-55](https://user-images.githubusercontent.com/72441267/133101447-4b60caf4-7907-47df-86e0-34c720fd5bae.jpg)
an error appears when importing styles from a node_modules/element-plus..
configuration: 
"dependencies": {
    "core-js": "^3.6.5",
    "dart-sass": "^1.25.0",
    "element-plus": "^1.1.0-beta.9",
    "husky": "^6.0.0",
    "node-sass": "^6.0.1",
    "v-slim-mask": "^1.0.24",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@openapitools/openapi-generator-cli": "^2.3.10",
    "jvm": "^0.5.3",
    "@babel/core": "^7.13.14",
    "@storybook/addon-actions": "^6.2.7",
    "@storybook/addon-essentials": "^6.3.7",
    "@storybook/addon-knobs": "^6.2.7",
    "@storybook/addon-links": "^6.2.7",
    "@storybook/vue3": "^6.3.7",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/vue": "^6.4.0",
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "babel-loader": "^8.2.2",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "msw": "^0.28.1",
    "prettier": "^2.2.1",
    "sass": "^1.39.2",
    "sass-loader": "7.0.1",
    "ts-jest": "^26.5.5",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "typescript": "~4.3.5",
    "vue-jest": "^5.0.0-0",
    "vue-loader": "^16.2.0"
  },

**Comment by themojilla** [comment]
`node-sass` is deprecated. you just need:

```bash
yarn add sass
```
