### ISSUE TITLE
bug-report: [el-form] validation broken

### ISSUE THREAD

**Issue by digitalkaoz** [element-plus/element-plus#3388]
this is a follow up of #3294 and #3324 .

The revert of my patch still leaves the whole form validation broken by default.

I also updated the demo with an async validator https://codesandbox.io/s/vue-3-element-pro-form-validation-error-c3qnx the example still doesnt trigger the form validation callback (click on Register should do a `console.log`).

i would say, better have a working form validation for 95% of all use-cases than having a form validation working 0% of the time.

@HerringtonDarkholme you reverted my already merged (and working) PR, so a working solution of your own would be very much appreciated.

**Comment by sxzz** [comment]
@HerringtonDarkholme Hi, do you have any other ways to fix this problem?

**Comment by bastarder** [comment]
i have 2 question with your demo,
the first one is, `const formRules = registerFormRules(user, formRef.value);`
your pass the formRef.value into the registerFormRules, formRef.value will always be 'undefined',  so the `validatePass` function will throw error
the second is, 
`  password: [
    { required: true, message: "Please input your password", trigger: "blur" },
    {
      validator: (rule, value, callback) =>
        validatePass(user, form, rule, value, callback),
      trigger: "blur"
    }
  ],`
the `validatePass` doesn't call the method `callback`,

i change the 2 point, everything is ok.

https://codesandbox.io/s/vue-3-element-pro-form-validation-error-forked-bkmr8?file=/src/components/HelloWorld.vue

**Comment by digitalkaoz** [comment]
thanks, you are right. i had some confusion about refs and observables from a vuex store (the user)

now its working as intended!
