### ISSUE TITLE
[bug report] border color error in textarea focus / hover

### ISSUE THREAD

**Issue by f-jm** [element-plus/element-plus#3390]
### Element Plus version
1.1.0-beta.10

### OS/Browsers version
win10 / edge

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=62be945d-dc65-4ed3-aebf-f5d6282ffdec

### Steps to reproduce
.el-textarea__inner:focus
.el-textarea__inner:hover

### What is Expected?
var(--el-input-focus-border,var(--el-color-primary))

### What is actually happening?
var(--el-input-focus-border,)

**Comment by JeremyWuuuuu** [comment]
cc @YunYouJun

**Comment by adaex** [comment]
@YunYouJun seems to be busy. I'll fix it 🤪
