### ISSUE TITLE
1.1.0-beta.10 version problem

### ISSUE THREAD

**Issue by liu-bluesky** [element-plus/element-plus#3391]
theme-chalk/display.css 文件没了是有替代方案还是什么

**Comment by dong136279559** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/20337504/133190753-74d58c1e-c285-498f-999d-956d462f3775.png">
我集成了element-plus,启动项目就报错了，大佬能给看看吗

**Comment by JeremyWuuuuu** [comment]
> <img alt="image" width="1131" src="https://user-images.githubusercontent.com/20337504/133190753-74d58c1e-c285-498f-999d-956d462f3775.png">
> 
> 我集成了element-plus,启动项目就报错了，大佬能给看看吗

@dong136279559 单独开个 issue 这个我们会修一下。

**Comment by sxzz** [comment]
> <img alt="image" width="1131" src="https://user-images.githubusercontent.com/20337504/133190753-74d58c1e-c285-498f-999d-956d462f3775.png">
> 
> 我集成了element-plus,启动项目就报错了，大佬能给看看吗

https://github.com/element-plus/element-plus/issues/3392

**Comment by sxzz** [comment]
@liu-bluesky Please check again, this file still exists.

**Comment by bitjjj** [comment]
build的配置有问题。脚本没有配置对vue-demi库的处理，打包出来的index.full.js中会从外部导入vue-demi并设置成全局变量：vueDemi。

【No name was provided for external module 'vue-demi' in output.globals – guessing 'vueDemi'】

重现URL： https://codepen.io/bitjjj/pen/YzQxJmw
点击打开dialog，控制台会报错，所有使用@vueuse的地方都会有问题

**Comment by sxzz** [comment]
@bitjjj fix in https://github.com/element-plus/element-plus/pull/3404 .
