### ISSUE TITLE
[Bug Report] Can't import the named export 'xxx' from non EcmaScript module

### ISSUE THREAD

**Issue by Miss-Sixty** [element-plus/element-plus#3392]
### Element Plus version
1.1.0-beta.10

### OS/Browsers version
win11

### Vue version
3.2.11

### Steps to reproduce
更新到1.1.0-beta.10就会出现

### What is Expected?
正常运行

### What is actually happening?
in ./node_modules/@vueuse/core/index.mjs

Can't import the named export 'xxx' from non EcmaScript module (only default export is available)

**Comment by dong136279559** [comment]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/20337504/133191905-6f3c61ec-9b01-4dc1-a85f-34f281ecd417.png">
我这也是报这个错

**Comment by LittleCountryw** [comment]
我在vue-cli4的环境下安装使用element-plus也是这个错误
![code](https://user-images.githubusercontent.com/81803999/133194033-df4cedd7-fcf1-4451-9a0a-92ae20e6d20f.png)
![problem](https://user-images.githubusercontent.com/81803999/133194038-08e57a15-0b13-49fb-bfae-c69f461c076f.png)
![package](https://user-images.githubusercontent.com/81803999/133194044-504f9f5c-011b-4909-b813-f2ed11cf4ad0.png)

**Comment by xiaoxian521** [comment]
This does not seem to be a problem with element-plus, please refer to this to configure your own project
https://github.com/vueuse/vueuse/issues/718

**Comment by sxzz** [comment]
https://github.com/vueuse/vueuse/issues/718#issuecomment-913319680

**Comment by PlayWithSanLei** [comment]
你的办法解决了问题，谢谢啦！

> This problem only occurs in the webpack version of the project, and has no effect on the vite version of the project.
> current solution, please refer to this to configure your own project
> issues: [vueuse/vueuse#718 (comment)](https://github.com/vueuse/vueuse/issues/718#issuecomment-913319680)
> this same issues: #3391
> <img alt="WechatIMG255" width="852" src="https://user-images.githubusercontent.com/44761321/133197508-a6c2da42-3567-4bcd-b3c9-17066166590a.png">

**Comment by sxzz** [comment]
fixed in https://github.com/element-plus/element-plus/pull/3405 .

**Comment by mrzdevcore** [comment]
Hello I have the same issue but with Vite

`node_modules/element-plus/es/hooks/use-timeout/index.mjs:1:9: error: No matching export in "node_modules/@vueuse/core/dist/index.esm.js" for import "tryOnScopeDispose"
    1 │ import { tryOnScopeDispose } from '@vueuse/core';
`
How can I apply the same config as provided here that  fixed the problem but with vite.config.ts instead of webpack

Thanks

**Comment by Miss-Sixty** [comment]
> 你好，我有同样的问题，但与 Vite
> 
> `node_modules/element-plus/es/hooks/use-timeout/index.mjs:1:9: error: No matching export in "node_modules/@vueuse/core/dist/index.esm.js" for import "tryOnScopeDispose" 1 │ import { tryOnScopeDispose } from '@vueuse/core'; ` 我如何应用与此处提供的相同的配置来解决问题，但使用 vite.config.ts 而不是 webpack
> 
> 谢谢

I use vite, and element plus is the latest version. All imported components have not encountered this problem.
