### ISSUE TITLE
[bug report] the El config provider failed to package vite

### ISSUE THREAD

**Issue by Dirian9754** [element-plus/element-plus#3393]
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
win10

### Vue version
3.2.4

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
```js
<template>
  <el-config-provider :locale="locale">
    <router-view />
  </el-config-provider>
</template>

<script lang="ts" setup>
import { ElConfigProvider } from 'element-plus'
import locale from 'element-plus/lib/locale/lang/zh-cn'
</script>
```

我按照官网的示例使用了 ElConfigProvider  以提供中文语言支持，但是进行 vite build 时发生了一些错误，反馈的结果如下：

[vite]: Rollup failed to resolve import "element-plus/lib/el-config-provider" from "src\App.vue?vue&type=script&setup=true&lang.ts".       
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

这是发生了什么问题？我要如何解决它？

### What is Expected?
正确完成 build

### What is actually happening?
build error

**Comment by xiaoxian521** [comment]
the latest version of "element-plus": "1.1.0-beta.10"
y
<img width="1100" alt="WechatIMG256" src="https://user-images.githubusercontent.com/44761321/133226235-dce1f5bb-0864-4ba0-9212-b26e15c56d6a.png">
ou can consider upgrading, you can refer to this example https://github.com/xiaoxian521/vue-pure-admin, also use vite, packaging is no problem

**Comment by Dirian9754** [comment]
我尝试了一下，这似乎并不能解决我的问题

**Comment by Dirian9754** [comment]
> The latest version of "element-plus": "1.1.0-beta.10".
> You can consider upgrading, you can refer to this example https://github.com/xiaoxian521/vue-pure-admin, also use vite, packaging is no problem.
> If you still have questions, you can provide a recurring warehouse, and I will help you to see it.
> <img alt="WechatIMG256" width="1100" src="https://user-images.githubusercontent.com/44761321/133226235-dce1f5bb-0864-4ba0-9212-b26e15c56d6a.png">

我尝试了一下，这似乎并不能解决我的问题

**Comment by xiaoxian521** [comment]
给个你的仓库地址吧 我帮你看下

**Comment by Dirian9754** [comment]
> 给个你的仓库地址吧 我帮你看下

呃。。，由于是公司的项目，没法对外暴露，不过还是很感谢你的帮助。

**Comment by xiaoxian521** [comment]
@Dirian9754 现在解决了吗？如果不行，你可以整个离线demo哦
