### ISSUE TITLE
ElDropdown: Uncaught TypeError: can't convert null to object

### ISSUE THREAD

**Issue by g3r4n** [element-plus/element-plus#340]
on the dev branch when I'm running the website
```
yarn website-dev
```
I got the following error in the navigator:
![image](https://user-images.githubusercontent.com/10941033/93939172-aeb87780-fd2a-11ea-88e8-5a388ac1e6ea.png)

**Comment by zouhangwithsweet** [comment]
- node version v12.14.1
- vue v3.0.0

I cannot reproduce locally :thinking:

**Comment by g3r4n** [comment]
I had to delete and clone again the repository to fix it 🤷‍♂️
