### ISSUE TITLE
[Bug Report] On Demand CSS not loading

### ISSUE THREAD

**Issue by thamibn** [element-plus/element-plus#3417]
### Element Plus version
1.1.0-beta.11

### OS/Browsers version
Chrome

### Vue version
3.2.11

### Reproduction Link
https://codesandbox.io/s/element-plus-on-demand-yp9kt?file=/src/main.js

### Steps to reproduce
copied babel-config.js setup from the documentation but when I load the component it does not have the styles.

### What is Expected?
Component to be styled accordingly

### What is actually happening?
no styles are applied

**Comment by bastarder** [comment]
did you try `element-plus/lib/components/${name}/style/css`

**Comment by bastarder** [comment]
i download the `Project Zip`, than `yarn && yarn run serve`, everything is ok,
![image](https://user-images.githubusercontent.com/16336681/133407153-b9b606fd-aa7c-441a-9d88-7ce08d1557d8.png)

**Comment by thamibn** [comment]
> i download the `Project Zip`, than `yarn && yarn run serve`, everything is ok,
> ![image](https://user-images.githubusercontent.com/16336681/133407153-b9b606fd-aa7c-441a-9d88-7ce08d1557d8.png)

serious?? on my side it does not load the css.
![Screenshot from 2021-09-15 12-23-06](https://user-images.githubusercontent.com/28577943/133416834-d7813c48-2ac2-49d8-880f-70764f2faeb1.png)

**Comment by bastarder** [comment]
> > i download the `Project Zip`, than `yarn && yarn run serve`, everything is ok,
> > ![image](https://user-images.githubusercontent.com/16336681/133407153-b9b606fd-aa7c-441a-9d88-7ce08d1557d8.png)
> 
> serious?? on my side it does not load the css.
> ![Screenshot from 2021-09-15 12-23-06](https://user-images.githubusercontent.com/28577943/133416834-d7813c48-2ac2-49d8-880f-70764f2faeb1.png)

can you try this project, in your local?

**Comment by xiaoxian521** [comment]
@thamibn 
Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus){target="_blank"}

**Comment by thamibn** [comment]
> @thamibn
> Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus)

cool let me try that thanks.

**Comment by thamibn** [comment]
> > > i download the `Project Zip`, than `yarn && yarn run serve`, everything is ok,
> > > ![image](https://user-images.githubusercontent.com/16336681/133407153-b9b606fd-aa7c-441a-9d88-7ce08d1557d8.png)
> > 
> > 
> > serious?? on my side it does not load the css.
> > ![Screenshot from 2021-09-15 12-23-06](https://user-images.githubusercontent.com/28577943/133416834-d7813c48-2ac2-49d8-880f-70764f2faeb1.png)
> 
> can you try this project, in your local?

yes i did on local it does not work.

**Comment by xiaoxian521** [comment]
> > @thamibn
> > Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus)
> 
> cool let me try that thanks.

If you can, please let me know and this issue will be closed
If not, please provide a warehouse and I will help you to see it❤️

**Comment by thamibn** [comment]
> > > @thamibn
> > > Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus)
> > 
> > 
> > cool let me try that thanks.
> 
> If you can, please let me know and this issue will be closed
> If not, please provide a warehouse and I will help you to see it

can you please show me a setup on the below link
https://codesandbox.io/s/element-plus-on-demand-yp9kt?file=/src/main.js

like an example on how i can set it up better and what if i use my custom theme how will you setup that?

**Comment by thamibn** [comment]
> > > @thamibn
> > > Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus)
> > 
> > 
> > cool let me try that thanks.
> 
> If you can, please let me know and this issue will be closed
> If not, please provide a warehouse and I will help you to see it

what is a warehouse i would be glad to setup that so you can help me

**Comment by xiaoxian521** [comment]
> > > > @thamibn
> > > > Recommended use: [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus)
> > > 
> > > 
> > > cool let me try that thanks.
> > 
> > 
> > If you can, please let me know and this issue will be closed
> > If not, please provide a warehouse and I will help you to see it
> 
> what is a warehouse i would be glad to setup that so you can help me

Put your code in the github repository, I will check it out
