### ISSUE TITLE
[feature request] the style contained in element theme chat does not seem to match the current version

### ISSUE THREAD

**Issue by cykcykcykcyk** [element-plus/element-plus#3425]
### Existing Component
No

### Component Name
element-theme-chalk

### Description
目前这个白垩主题似乎和现有的结构并不匹配，且无法相互覆盖。不知道官方有木有意愿发布新版的主题便于自行更换主题

**Comment by adaex** [comment]
Could you describe it in detail?

**Comment by cykcykcykcyk** [comment]
oh sorry 。文档提供的主题npm地址 是原来element的主题
      `npm i element-theme-chalk -D`
我在查看element-plus源码结构，发现有 element-plus/packages/theme-chalk 我决定先试下是否可以正常使用

**Comment by cykcykcykcyk** [comment]
ˋ<(=° ▽、°=)>，可以了 我直接入侵到element-plus源码文件下的element-plus-dev\packages\theme-chalk，使用build命令，可以构建，不过这样似乎有点麻烦

**Comment by zhixiaotong** [comment]
借个楼，顺便问一下， 目前我需要弄白色和黑色两种主题。我采用了css变量的方式，尝试在本地覆盖默认白色主题的基础色，再添加黑色主题，但是:root{--el-color-primary:#1890ff;...}这种方式无法完全覆盖原有的样式，导致白色和黑色主题按钮仍然是之前的颜色。请问有什么解决方案没？不算gulp打包的方式。
