### ISSUE TITLE
[Bug Report] Error: [vite]: Rollup failed to resolve import "element-plus/lib/el-config-provider" from "src/App.vue?vue&type=script&lang.ts".

### ISSUE THREAD

**Issue by GolderBrother** [element-plus/element-plus#3429]
### Element Plus version
1.1.0-beta.11

### OS/Browsers version
11.5.2

### Vue version
3.2.4

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
vite build --mode test

<template>
  <el-config-provider :locale="zhCn">
    <router-view />
  </el-config-provider>
</template>

import zhCn from 'element-plus/lib/locale/lang/zh-cn';

### What is Expected?
build normal

### What is actually happening?
build error

**Comment by xiaoxian521** [comment]
@GolderBrother Please provide a recurring warehouse address, thank you
