### ISSUE TITLE
[Bug Report] when the native type of El button is reset, the behavior is equivalent to the form.resetfields method

### ISSUE THREAD

**Issue by qq326943819** [element-plus/element-plus#3432]
### Existing Component
Yes

### Component Name
el-form el-button

### Description
手动调用form.resetFields方法可以重置v-model的值，而通过设置button的native-type="reset"后点击该按钮，虽然UI上值重置了，但是数据中并没有被重置

**Comment by xiaoxian521** [comment]
Please provide the recurring address, thank you

**Comment by qq326943819** [comment]
> Please provide the recurring address, thank you

[like this](https://github.com/qq326943819/issue-element-plus-3432)
