### ISSUE TITLE
[Bug Report] error of import when use other tag in website-dev

### ISSUE THREAD

**Issue by Alanscut** [element-plus/element-plus#3433]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
window10

### Vue version
3.2.11

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
when there is a bug cause by some other tag like user's build, you change some codes and want to check out if they work quickly ,you will found you can't reproduce this issue in webiste-dev because you can't import the tag .
![image](https://user-images.githubusercontent.com/21104054/133541978-93793290-0f7a-48bb-b00b-067e6852e987.png)

the reason of this problem is transform <script> codes in util.js ,it caused import not appear at the top level
![image](https://user-images.githubusercontent.com/21104054/133541996-f29674d4-21e5-45cf-8ba8-039080b821c5.png)

### What is Expected?
can import tag in xx.md file 

### What is actually happening?
import in xx.md have error

**Comment by sxzz** [comment]
The documentation site is now being refactored, please use the `epic/website-refactor` branch.

**Comment by Alanscut** [comment]
ok，it seems be merged to `dev ` branch

**Comment by Alanscut** [comment]
cd to the docs/examples
`yarn install `
and `yarn dev`
![image](https://user-images.githubusercontent.com/21104054/133739399-01b4b8e2-b437-453a-b400-f7f94ec0a40b.png)
still have error

**Comment by Alanscut** [comment]
cd to the `docs`
`yarn install `
and `yarn dev`
![image](https://user-images.githubusercontent.com/21104054/133739399-01b4b8e2-b437-453a-b400-f7f94ec0a40b.png)
still have error

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/133741464-b33ca894-5792-4eda-858c-4d39d457a5cf.png)

i don't see the i18n folder in this path  `require('./i18n/pages/component.json')`

**Comment by Alanscut** [comment]
@sxzz @JeremyWuuuuu  take a look

**Comment by JeremyWuuuuu** [comment]
run 
```shell
$ yarn docs:gen-locale
```

at `/`

**Comment by JeremyWuuuuu** [comment]
I don't get it, you have the old documentation website code, but the new one does not contain that code.

**Comment by JeremyWuuuuu** [comment]
`website/` folder is now officially deprecated. Try sync up the dev branch to use the newest version of doc. Thank you.
