### ISSUE TITLE
[Bug Report] DateTimePicker: datetimerange changes to wrong date

### ISSUE THREAD

**Issue by sunecosuri** [element-plus/element-plus#3434]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Mac OS 10.15.7 / Google Chrome 93.0.4577.63

### Vue version
3.2.11

### Reproduction Link
https://codesandbox.io/s/element-plus-datetimerange-reproduction-gzi4v?file=/src/main.js

### Steps to reproduce
1. enter `2021-09-15 00:00` -> `2021-09-19 00:00` directly into the form so that the start date is after the end date.
2. remove the form from the focus
3. The input will not be updated and will remain as `2021-09-15 00:00`.

https://user-images.githubusercontent.com/13265134/133556023-51dfabcd-7faf-477e-a935-85a8806a4cc1.mov

### What is Expected?
Determine the start and end date and time when blur event fired
start: `2021-09-18 00:00` end: `2021-09-19 00:00 
end: `2021-09-19 00:00 

Or, maintain the state of the input
start: `2021-09-19 00:00` end: `2021-09-19 00:00 
end: `2021-09-18 00:00 

### What is actually happening?
The input will not be updated.

**Comment by xiaoxian521** [comment]
this is same issues: https://github.com/element-plus/element-plus/issues/3423#issue-996680805

**Comment by Alanscut** [comment]
hi @xiaoxian521 , this is not the same issue with #3424, and I don't think it's a bug. If the input `start-time` is greater than `end-time`, indicating the input value is invalid, so it keeps the original value is a normal behavior.

in element-ui, it works the same way: https://codepen.io/Alan_scut/pen/xxrpZqZ

**Comment by xiaoxian521** [comment]
@Alanscut yes, you are right, this is normal

**Comment by sunecosuri** [comment]
> If the input start-time is greater than end-time, indicating the input value is invalid, so it keeps the original value is a normal behavior.

I understood that it is a specification, not a bug.  🙆‍♂️ Thank you.
Don't you think it's hard for User to tell that the original value is kept and canceled?
Then I thought it would be nicer if it was blank.

After all, do you consider this to be right behavior and decide not to change it?
I'd like to hear your thoughts.

**Comment by Alanscut** [comment]
@sunecosuri , yes, I also think it does seem a litter weired. but so far there is not a better way to deal with that invalid time or date.

* For you first suggestion, the end-time changes to the last day of invalid start-time: please see #3424, some users don't expect the date/time change with the other date/time automatically.

* For your second suggestion, if start-time is after the end-time, then how should the the popover date table show? Should it be same with `end-time ~ start-time` ?

so if users find that when input an invalid time the enter key will not respond, may get theirs attention?
