### ISSUE TITLE
[Bug Report] Drawer is too laggy to open the animation.

### ISSUE THREAD

**Issue by ChinaStan** [element-plus/element-plus#3438]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Chrome 93.0.4577.63（正式版本） (x86_64)

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/iamkun

### Steps to reproduce
点击展开或者关闭时

### What is Expected?
Drawer 打开动画是否可以优化下，让其看起起来自然有点或者设置一个开关可以关闭动画效果

### What is actually happening?
Drawer 打开动画总感觉很卡，

**Comment by ChinaStan** [comment]
我发现这个示例上面的Drawer关闭动画就很流畅 [https://codepen.io/pen/](https://codepen.io/pen/)

**Comment by YunYouJun** [comment]
Record a video? The document's lag may be related to too many drawers in the page sample.
