### ISSUE TITLE
[Bug Report] Cascader Attributes options Loss of responsiveness

### ISSUE THREAD

**Issue by xie073100** [element-plus/element-plus#3455]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Chrome Version 93.0.4577.82 (Official Build) (64-bit)

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/Aliang2021/pen/mdwpYvo?editors=1010

### Steps to reproduce
- before mounting cascader, initialize the options(Cascader Attributes)  properoty,   
like this: [ { value: 1, label: '1', children: [] } ]

- aftermounting, update the options properoty, sush as add something to the “children” array

- check if the view has new options
  
you can view my Reproduction Link above

--- plus ---  
After I downgrage the Element Plus version to 1.1.0-beta.10, I can't reproduce according to the same steps

### What is Expected?
I can see the newly added option on the view

### What is actually happening?
The data “options” has changed, but the view is not updated

**Comment by Alanscut** [comment]
i will check it as soon as possible

**Comment by Alanscut** [comment]
this bug has been fixed by another pr
