### ISSUE TITLE
[Bug Report] the require file error

### ISSUE THREAD

**Issue by btea** [element-plus/element-plus#3456]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10  

### Vue version
3.2.11

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
the require `i18n` file path error  
https://github.com/element-plus/element-plus/blob/2204b8b71af04fc99d080d41b8a55820f378a042/docs/.vitepress/sidebars.js#L1-L2

### What is Expected?
the path is correct.

### What is actually happening?
Cannot find module

**Comment by Alanscut** [comment]
same error

**Comment by btea** [comment]
This file has the same problem  
https://github.com/element-plus/element-plus/blob/477519a52eb3d607d5a67ea7b4b824494fa6cc04/docs/.vitepress/nav.js#L1

**Comment by sxzz** [comment]
run `yarn docs:gen-locale` please

**Comment by btea** [comment]
ok.
