### ISSUE TITLE
[Bug Report] el-menu causing render loop when using v-for to render menu-items in horizontal mode.

### ISSUE THREAD

**Issue by mexican-jack** [element-plus/element-plus#3461]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Chrome

### Vue version
3.2.11

### Reproduction Link
https://github.com/element-plus/element-plus/issues/3256

### Steps to reproduce
![image](https://user-images.githubusercontent.com/16663045/133743949-6da0fae2-67ca-4195-b426-023e1fbc8cc4.png)

el-menu use mode="horizontal"
el-sub-menu use "v-for"

### What is Expected?
menu to load

### What is actually happening?
when you have enough sub menu items a memory leak occurs - caused by a render loop on:

menu.ts::359

the force update inside the render function is triggering a re-render which, is essentially creating a render loop. removing this line fixes the nav - but i'm not sure what it impacts

**Comment by LadenxxxxD** [comment]
I got the same problem
