### ISSUE TITLE
What is the compatibility of Element-Plus？

### ISSUE THREAD

**Issue by wdlnydhcg** [element-plus/element-plus#3462]
I kown vue3 compatibility firefox35 and i can normal run it,but i can't use element-plus,There are no errors on the console, Although I can see this input box, I can't actually enter anything.

**Comment by sxzz** [comment]
> Element Plus can run on browsers that supports ES2018 and ResizeObserver. If you really need to support outdated browsers, please add Babel and Polyfill yourself.
