### ISSUE TITLE
[bug report] dialog content is too long without scroll bar

### ISSUE THREAD

**Issue by xixixida** [element-plus/element-plus#3465]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
window10/Chrome v90

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/xixixida/pen/abwqzQd

### Steps to reproduce
https://codepen.io/xixixida/pen/abwqzQd
吧 dialog 中内容就不会和以前一样出现滚动条。

### What is Expected?
和之前版本一样

### What is actually happening?
没有滚动条，无法正确浏览内容

**Comment by xiaoxian521** [comment]
The normal way is to nest the div at the outermost level of the dialog content yourself, set max-height and overflow-y: auto.

**Comment by ben905713861** [comment]
> 正常的做法是自己将div嵌套在对话框内容的最外层，设置max-height和overflow-y:auto。

项目升级框架出现这个bug，总不可能一个一个去改吧？

**Comment by xiaoxian521** [comment]
Sorry, we will investigate

**Comment by ben905713861** [comment]
It seems the "lock-scroll" configuration is invalid.In adition, the "lock-scroll" default value is "false" in before version,but in this version the default value is "true".It will impact those old project to upgrade new version.

**Comment by adaex** [comment]
Yes, it's a bug, we'll fix it soon.
