### ISSUE TITLE
[Bug Report] El Dialog Component Close Click On Modal don't work!

### ISSUE THREAD

**Issue by MirasTekesbaev94** [element-plus/element-plus#3466]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Windows 10 / Google Chrome 93.0.4577.82 (64)

### Vue version
3.2.11

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-uk9dz?file=/src/App.vue:729-761

### Steps to reproduce
I took an example from the plus element library. Follow the link https://element-plus.org/#/en-US/component/dialog. By default, the "close-on-click-modal" property of the el-dialog component is true. And it should be closed by clicking on the shaded area. But everything works in sandboys! Which is very strange!

### What is Expected?
The modal window should be closed by clicking on the shaded area!

### What is actually happening?
The modal window does not close on clicking on the shaded area!

**Comment by xiaoxian521** [comment]
this same issues: https://github.com/element-plus/element-plus/issues/3419
