### ISSUE TITLE
[Bug Report] overriding SCSS variable custom theme does not take effect

### ISSUE THREAD

**Issue by pifako** [element-plus/element-plus#3468]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10 chrome

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
overriding SCSS variable custom theme does not take effect

### What is Expected?
overriding SCSS variable custom theme does not take effect

### What is actually happening?
*My main.js*

import { ElButton, ElIcon, ElForm, ElCard, ElInput, ElMenu, ElDropdown, ElCheckbox } from 'element-plus'
import './assets/css/element-variables.scss'

app.use(ElButton).use(ElForm).use(ElInput).use(ElCheckbox).use(ElCard).use(ElIcon).use(ElMenu).use(ElDropdown)

*babel.config.js*

module.exports = {
	presets: [
		'@vue/cli-plugin-babel/preset'
	],
	plugins: [
		[
			'import',
			{
				libraryName: 'element-plus',
				customName: (name) => {
					name = name.slice(3)
					return `element-plus/lib/components/${name}`
				},
				customStyleName: (name) => {
					name = name.slice(3)
					return `element-plus/lib/components/${name}/style/css`
				}
			}
		]
	]
}

*element-variables.scss*

???

-----

I tried different options but the theme does not change. How to properly replace primary colors ?

**Comment by pifako** [comment]
if i set 

:root {
	--el-color-white: #ffffff;
	--el-color-black: #000000;
	--el-color-primary: red;
}

change only checkbox but not button

**Comment by ameinhardt** [comment]
For me, https://element-plus.org/#/en-US/component/quickstart#using-webpack also didn't work.
You can try:

`babel.config.js`:
```js
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  plugins: [
    ['import', {
      libraryName:              'element-plus',
      transformToDefaultImport: false,
      customName:               () => 'element-plus/es',
      customStyleName:          (name) => {
        name = name.slice(3);
        return `element-plus/packages/theme-chalk/src/${name}.scss`;
      }
    }]
  ]
};
```

And in your `sass-loader` (or `vue.config.js / css.loaderOptions.scss`, you add `additionalData`. Since sass `@use` have to be on top, you would have to hoist your variables (as suggested in [sass-resources-loader](https://github.com/shakacode/sass-resources-loader/blob/230c4a18cf85452b34ab9b76057201ceedc8b4d4/src/utils/processResources.js#L14))
```js
additionalData: ((prepend) => {
  const multilineParenthesisRegex = '\\([\\s\\S]*?\\);?',
        useRegex = `^@use \\S*(?: with ${multilineParenthesisRegex}|.*)?\n?$`,
        lastUseRegex = new RegExp(`${useRegex}(?![\\s\\S]*${useRegex})`, 'gm');
  return (content) => content.replace(lastUseRegex,  (useStatements) => `${useStatements}${prepend};`);
})('@import "~@/assets/css/element-variables.scss"')
```

`element-variables.scss` then:
```scss
@use "sass:map";

$--colors: () !default;
$--colors: map.deep-merge(
  (
    'primary': (
      'base': #ff0000
  ),
  $--colors
);

@import '~element-plus/packages/theme-chalk/src/common/var';
@import '~element-plus/packages/theme-chalk/src/mixins/var';

$--font-path: '~element-plus/theme-chalk/fonts';
```

Is there an easier way?

**Comment by Mcler520** [comment]
> For me, https://element-plus.org/#/en-US/component/quickstart#using-webpack also didn't work.
> You can try:
> 
> `babel.config.js`:
> 
> ```js
> module.exports = {
>   presets: ['@vue/cli-plugin-babel/preset'],
>   plugins: [
>     ['import', {
>       libraryName:              'element-plus',
>       transformToDefaultImport: false,
>       customName:               () => 'element-plus/es',
>       customStyleName:          (name) => {
>         name = name.slice(3);
>         return `element-plus/packages/theme-chalk/src/${name}.scss`;
>       }
>     }]
>   ]
> };
> ```
> 
> And in your `sass-loader` (or `vue.config.js / css.loaderOptions.scss`, you add `additionalData`. Since sass `@use` have to be on top, you would have to hoist your variables (as suggested in [sass-resources-loader](https://github.com/shakacode/sass-resources-loader/blob/230c4a18cf85452b34ab9b76057201ceedc8b4d4/src/utils/processResources.js#L14))
> 
> ```js
> additionalData: ((prepend) => {
>   const multilineParenthesisRegex = '\\([\\s\\S]*?\\);?',
>         useRegex = `^@use \\S*(?: with ${multilineParenthesisRegex}|.*)?\n?$`,
>         lastUseRegex = new RegExp(`${useRegex}(?![\\s\\S]*${useRegex})`, 'gm');
>   return (content) => content.replace(lastUseRegex,  (useStatements) => `${useStatements}${prepend};`);
> })('@import "~@/assets/css/element-variables.scss"')
> ```
> 
> `element-variables.scss` then:
> 
> ```css-scss
> @use "sass:map";
> 
> $--colors: () !default;
> $--colors: map.deep-merge(
>   (
>     'primary': (
>       'base': #ff0000
>   ),
>   $--colors
> );
> 
> @import '~element-plus/packages/theme-chalk/src/common/var';
> @import '~element-plus/packages/theme-chalk/src/mixins/var';
> 
> $--font-path: '~element-plus/theme-chalk/fonts';
> ```
> 
> Is there an easier way?

Start the prompt

Syntax Error: SassError: Undefined variable. 
  background-color: $--background-color-base;

**Comment by YunYouJun** [comment]
Sorry, I am troubleshooting the problem.

**Comment by YunYouJun** [comment]
I find it, import scss in js/ts will not combine them.

So we need import it in a scss, then import it.

Like this:

```scss
@import "./var.scss";
@import "element-plus/theme-chalk/src/index.scss";
```

```ts
import "~/styles/element/index.scss";
```

I made a example for it. check [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter).

**Comment by ameinhardt** [comment]
@YunYouJun: this is to load all styles. And, like my answer, on demand per component?

**Comment by YunYouJun** [comment]
You can like this:

```scss
// index.scss
@import "./var.scss";
// @import "element-plus/theme-chalk/src/index.scss";

@import "element-plus/theme-chalk/src/base.scss";
@import "element-plus/theme-chalk/src/button.scss";
```

```vue
<script setup lang="ts">
import { ElButton } from "element-plus";
</script>
```

**Comment by ameinhardt** [comment]
That's simpler, true! Yet, it defeats the purpose of on-demand a bit, as index.scss already contains a list of the used components (styles).
That's why I used `babel-plugin-import` together with `additionalData`

**Comment by YunYouJun** [comment]
Hey, I have solved this problem. We provide two examples for your reference. You can choose the plugin you like.

- On demand with unplugin-vue-components: [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter)
- On demand manually with unplugin-element-plus: [unplugin-element-plus/examples/vite](https://github.com/element-plus/unplugin-element-plus)
