### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by 1774298958** [element-plus/element-plus#3476]
![image](https://user-images.githubusercontent.com/26165803/133869924-ff06afb7-25ef-4ab6-ba0b-41bc2c261c8b.png)
![image](https://user-images.githubusercontent.com/26165803/133869940-4277179c-bdd4-4067-8ae8-e235027b6c59.png)

const changeCheckBox = (e:any) => {
      dataMap.settingForm.autoPicking = e
      dataMap.autoPickingText = (e === 1 ? '自动' : '手动')
    }
 <el-checkbox
            :style="{'width': '7.5rem','float': 'right'}"
            :model-value="settingForm.autoPicking"
            :label="autoPickingText"
            :true-label="1"
            :false-label="0"
            @change="changeCheckBox"
          />
勾选时正常显示lable文字，取消勾选时没有lable文字显示

**Comment by xiaoxian521** [comment]
Please provide a valid recurring address, use codepen

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
