### ISSUE TITLE
The @ element plus in the language index.js from the [bug report] command build: locale is not replaced with a relative path

### ISSUE THREAD

**Issue by bitjjj** [element-plus/element-plus#3478]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
macos / chrome92

### Vue version
3.2.12

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
https://unpkg.com/element-plus@1.1.0-beta.12/es/locale/index.js
第一行：
import { debugWarn } from '@element-plus/utils/error';

### What is Expected?
import { debugWarn } from '../utils/error';

### What is actually happening?
import { debugWarn } from '@element-plus/utils/error';

**Comment by xiaoxian521** [comment]
currently @element-plus/utils/resize-event is used
