### ISSUE TITLE
A hope

### ISSUE THREAD

**Issue by JinwiKing** [element-plus/element-plus#348]
I hope that all component reference docs indicates the name of component for referencing at the header, just like Vant:
![image](https://user-images.githubusercontent.com/37678544/94233110-f52ff100-ff39-11ea-9812-3ef2ef88b24b.png)

Thanks a lot.

**Comment by zazzaz** [comment]
Will take this into consideration, thanks.

**Comment by JeremyWuuuuu** [comment]
Nice suggestion, I think this is kind of necessary for the documentation.

**Comment by ArishSultan** [comment]
I want to work on this issue, can someone just elaborate what the problem is? I didn't understand the issue

**Comment by JeremyWuuuuu** [comment]
@ArishSultan 
Well, this is essentially an enhancement for the documentation, which @ExecutableBug would like documentations to have a code fragment for how to get the component from the bundle like this
```ts
import { createApp } from 'vue'
import { ComponentInstaller } from '@element-plus'
import yourAppHere from 'path/to/your/app/entrance'

const app = createApp(yourAppHere)
app.use(ComponentInstaller)

```

**Comment by zazzaz** [comment]
in more detail, it will be better to tell our user what component to import to make the demo work.

```js
<template>
  <el-radio v-model="radio" label="1">备选项</el-radio>
  <el-radio v-model="radio" label="2">备选项</el-radio>
</template>

<script>
 import { ElRadio } from '@element-plus'

  export default {
    data () {
      return {
        radio: '1'
      };
    }
  }
</script>

```

**Comment by ExecutableBug** [comment]
@ArishSultan yep, just like what @JeremyWuuuuu  and @zazzaz  said, and i am sorry for my description, i am working hard on my english

**Comment by taweesakpintakam** [comment]
> I hope that all component reference docs indicates the name of component for referencing at the header, just like Vant:
> ![image](https://user-images.githubusercontent.com/37678544/94233110-f52ff100-ff39-11ea-9812-3ef2ef88b24b.png)
> 
> Thanks a lot.
