### ISSUE TITLE
[Feature Request] support async-validator 4.0

### ISSUE THREAD

**Issue by uinio** [element-plus/element-plus#3485]
### Existing Component
Yes

### Component Name
ElForm

##### typescript 错误的类型校验，建议支持4.0更好的ts支持
 ```ts
import {
  FormRulesMap,
  FormItemRule,
} from 'element-plus/lib/components/form/src/form.type';

const passwordValidator: FormItemRule['validator'] = (
      rule,
      value,
      callback,
    ) => {
      if (!value) return callback('请输入密码！');
      if (value) {
        if (value.length < 6) {
          callback('密码不能小于6位!');
        }
      }
      callback();
    };
    const rules: FormRulesMap = {
      password: [{ validator: passwordValidator, trigger: 'change' }],
    };
```

**Comment by uinio** [comment]
reference

```ts
import { ExecuteValidator } from 'async-validator/dist-types/interface';
import { FormRulesMap } from 'element-plus/lib/components/form/src/form.type';

 const passwordValidator: ExecuteValidator = (rule, value, callback) => {
      callback();
  };

 const rules: FormRulesMap = {
      password: [{ validator: passwordValidator, trigger: 'change' }],
  };
```

**Comment by xiaoxian521** [comment]
`import {  FormRulesMap,  FormItemRule } from 'element-plus`
remind: types can be imported directly

**Comment by uinio** [comment]
严重影响使用vite无法编译

**Comment by yuzhang9804** [comment]
@uinio What does it mean?

**Comment by uinio** [comment]
vite 编译校验失败 ，无法编译
![image](https://user-images.githubusercontent.com/49021590/134753958-8e401d79-dcfe-479f-b488-ecdf38b4bb33.png)

**Comment by uinio** [comment]
使用ts 非常糟糕 
![image](https://user-images.githubusercontent.com/49021590/134754132-8b1144c4-2157-42c1-bad0-6379dd7ce42c.png)

**Comment by mikeshi80** [comment]
> remind: types can be imported directly, such as:
> `import { FormRulesMap, FormItemRule } from 'element-plus`

Currently `import { FormRulesMap } from 'element-plus/lib/components/form/src/form.type'` is only supported, and I tried `import { FormRulesMap, FormItemRule } from 'element-plus`, it failed.
