### ISSUE TITLE
[Bug Report] Random hangs whole page when open cascader menu

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#3498]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
WIndows 10 / Chrome 93.0.4577.82

### Vue version
3.2.12

### Reproduction Link
https://element-plus.org/#/zh-CN/component/cascader

### Steps to reproduce
I don't know how to reproduce, it just happen randomly when try to open cascader menu.  

### What is Expected?
Work as normal

### What is actually happening?
Randomly hangs whole page when try to open cascader menu.

--------------------------
Yes, I know this issue is unreasonable, there is no any reproduce steps.  
But it just hanppen no reason at anytime, it's not trackable at all.   
And it happens any case, whatever in my code or example in docs.  
Only way to reproduce it is open cascader menu, and guess it will happen or not.  
  
I work around with this problem almost 3 hours, over 70% time spent on trigger this problem, but I can't catch it after it happened at all.  
When page hangs by this problem, devtool disconnected from page, breakpoint and profiler can't work at all, console stop responding, refresh not working. Only way to end this is kill process in taskmgr.   
In taskmgr I see that CPU usage of browser process is 100%, maybe there is a infinite loop in page.   
I don't know how to find out what hanging whole page.    
  
-------------------------
If you want to reproduce this, just open docs of cascader and put it into background.  
And check it randomly, maybe after fixed some bug in your project, after your lunch, before sleeping or anytime you like.  
Try to open cascader menu, and guess it will happen or not.

**Comment by xiaoxian521** [comment]
Can you provide a video?😅

**Comment by KawaiiZapic** [comment]
> You can try this api `popper-append-to-body=false`
> If it still doesn’t work, I hope you can record a video to help us determine the problem

I don't know what time it will hanppen, it happen without any reason at any time, that mean we cannot determine this problem without finding out which part of code causing this.   
A video may not give any help at all, the content of reproducing is just click, click, click, click, click, and boom, it happened.   
But I will try to recoding this.

**Comment by xiaoxian521** [comment]
`popper-append-to-body=false` can't solve your problem?

**Comment by KawaiiZapic** [comment]
> `popper-append-to-body=false` can't solve your problem?

I'm not sure this solve or not.    
Because this bug happen at any time...   
Maybe the bug still exists, but it hasn't happened yet.   
  
Only way to determine this problem is finding out which part of code is causing this.

**Comment by flmbbb** [comment]
的确我也碰到这个问题，就是级联下拉，不停的操作选择点击，选择点击，来个十几次，整个页面就崩了

**Comment by KawaiiZapic** [comment]
Fixed in #3546
