### ISSUE TITLE
[Bug Report] about the docs:dev 

### ISSUE THREAD

**Issue by btea** [element-plus/element-plus#3509]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10/Chrome

### Vue version
3.2.12

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
1、The shell command seem cannot compatible win10, when i run `yarn docs:dev` got the error  
![image](https://user-images.githubusercontent.com/24516654/133930058-ba15ebdb-2240-48ea-a634-92ff1b543df0.png)

2、After I run the `bash scripts/build.sh` and `yarn docs:gen-locale && cd docs && yarn dev`, I open the browser and got the error like this
![image](https://user-images.githubusercontent.com/24516654/133930091-5cdb445f-95a4-4b3a-b392-92ae23d81445.png)

### What is Expected?
I can run `docs:dev` successfully and preview the docs.

### What is actually happening?
I met some erros.

**Comment by xiaoxian521** [comment]
Please upgrade node to the latest version
1. `yarn bootstrap`
2. `yarn docs:dev`
<img width="1676" alt="截屏2021-09-20 下午4 51 57" src="https://user-images.githubusercontent.com/44761321/133977333-6df4f26e-caf0-487b-a785-682e30c0f1cb.png">

**Comment by btea** [comment]
@xiaoxian521  Thank you show me the image. But I have upgraded node these errors still exist. 😵‍💫  
![image](https://user-images.githubusercontent.com/24516654/134018599-f3bb560c-8212-47e7-b2f2-434a5944bf60.png)

**Comment by xiaoxian521** [comment]
> @xiaoxian521 Thank you show me the image. But I have upgraded node these errors still exist. 😵‍💫
> ![image](https://user-images.githubusercontent.com/24516654/134018599-f3bb560c-8212-47e7-b2f2-434a5944bf60.png)

Clean up npm or yarn cache

**Comment by btea** [comment]
OK, I'll try later

**Comment by btea** [comment]
@xiaoxian521 I tried it，but the `MIME type`  error still exists~
