### ISSUE TITLE
[feature request] wants to provide a global component type declaration file to cooperate with volar on vs code to achieve a better development experience

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#3530]
### Existing Component
否

### Component Name
-

### Description
[Volar](https://github.com/johnsoncodehk/volar#using) 能够通过 GlobalComponents 为全局注册的组件提供代码提示、类型提示、跳转等功能。提供一个全局组件类型声明文件，并在适合的文档中提示在tsconfig文件中引入文件即可。

根据现在的构建流程，我认为可以在 packages/element-plus/ 下增加一个文件来管理这些内容。

**Comment by JeremyWuuuuu** [comment]
@tolking Yes, would you like to do that? I think this means a lot for both developers and users. cc @sxzz

**Comment by sxzz** [comment]
We are working in progress.
https://github.com/element-plus/element-plus/pull/3113

**Comment by sxzz** [comment]
You can add it by yourself for now.

https://github.com/element-plus/element-plus/blob/dev/typings/components.d.ts

**Comment by tolking** [comment]
> You can add it by yourself for now.
> 
> https://github.com/element-plus/element-plus/blob/dev/typings/components.d.ts

I did not find any relevant files in the NPM package

**Comment by sxzz** [comment]
@tolking This file is not published to npm, but you can copy it directly to your project.
We may add it to npm in the future.

**Comment by tolking** [comment]
> @tolking This file is not published to npm, but you can copy it directly to your project.
> We may add it to npm in the future.

I got it, thanks!
