### ISSUE TITLE
[Bug Report] El Select options changed when composition

### ISSUE THREAD

**Issue by bchen1029** [element-plus/element-plus#3532]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Mac OS / Chrome 93.0.4577.63

### Vue version
3.2.12

### Reproduction Link
https://codepen.io/bchen1222/pen/NWdoYvG?editors=1000

### Steps to reproduce
1. 新增一個 el-select
2. 將 filterable 設為 true
3. 新增有中文 label 的選單，
options: [
{
value: 'cake',
label: '蛋糕'
}
...
]

### What is Expected?
可以正確 filter 符合輸入內容的選項

### What is actually happening?
使用中文輸入法上下鍵選字時，選單的 active 選項也會跟著上下滑動，導致無法選到正確的中文字

**Comment by VincentChen1212** [comment]
Hi,
Cascader has the same Bug (Chinese input method).
Now only Up key to select words, Down key got error
Thanks.
