### ISSUE TITLE
[Bug Report] yarn docs:dev error  if [ ! -d "dist/element-plus" ];  then sh scripts/build.sh;  Fi & & yarn docs: Gen locale & & CD docs & & yarn dev should not be at this time!.

### ISSUE THREAD

**Issue by yingjie-design** [element-plus/element-plus#3535]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10

### Vue version
3.2.12

### Reproduction Link
jsfiddle/codepen/codesandbox

### Steps to reproduce
yarn docs:dev error  if [ ! -d "dist/element-plus" ]; then sh scripts/build.sh; fi && yarn docs:gen-locale && cd docs && yarn dev 此时不应有 !。

### What is Expected?
yarn docs:dev error  if [ ! -d "dist/element-plus" ]; then sh scripts/build.sh; fi && yarn docs:gen-locale && cd docs && yarn dev 此时不应有 !。

### What is actually happening?
yarn docs:dev error  if [ ! -d "dist/element-plus" ]; then sh scripts/build.sh; fi && yarn docs:gen-locale && cd docs && yarn dev 此时不应有 !。

**Comment by btea** [comment]
the same error as #3509

**Comment by xiaoxian521** [comment]
> the same error as #3509

thanks
