### ISSUE TITLE
[bug report] cascade selector of cascader is stuck after clicking or selecting several times

### ISSUE THREAD

**Issue by flmbbb** [element-plus/element-plus#3543]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10 chrome

### Vue version
3.2.13

### Reproduction Link
https://github.com/element-plus/element-plus/issues/3498

### Steps to reproduce

你用win10 chrome打开官网例子
https://element-plus.gitee.io/#/zh-CN/component/cascader
进行不停的点击操作。。就卡死了，整个页面直接挂起卡死。
严重影响，希望尽快修复,我现在很多界面用到这个，全卡死在那

### What is Expected?
尽快解决此BUG 我看GITHUB 也很多人提了，你们为什么多不去解决了，好多天了

### What is actually happening?
尽快解决此BUG 我看GITHUB 也很多人提了，你们为什么多不去解决了，好多天了

**Comment by flmbbb** [comment]
![image](https://user-images.githubusercontent.com/17305384/134280306-ba982c6e-66ac-4a1f-93b9-4e6d0784a645.png)
看到没，你官网的DEMO 多会卡死在那win10 chrome

**Comment by flmbbb** [comment]
![image](https://user-images.githubusercontent.com/17305384/134280399-697f0e7e-765d-4d77-ac30-b36b45df4cc4.png)
只需要多点击选择几次就会，现成的例子现成的DEMO ，你们自已可以操作下

**Comment by KawaiiZapic** [comment]
这个问题可以说是非常难复现了.
几乎就是随机触发, 做不到变量可控...  
一旦卡死调试工具就掉线, 断点打不进去, 大概只能静态分析了.   
  
这页面直接卡死了, 已经不是影响体验的问题了, 可能会导致用户丢失数据.  
虽然这种反馈很无厘头, 什么分析什么证据都没有, 但是换谁来整也整不出什么证据啊.  
只能认为是嫌麻烦所以不重视了...

**Comment by flmbbb** [comment]
那要咱办。。。转ANT阵营？？

**Comment by msidolphin** [comment]
我们已经在定位问题了

**Comment by flmbbb** [comment]
我一直在关注着此问题，今天 看这个BUG 有没有回复不只十次了。。。。。哎。。。如果这两天没解决，我是会找替代方案的。。
真的太蛋痛了。。。谢谢你们的回复，我知道你们也辛苦，但此问题 严重影响了有点严重

**Comment by flmbbb** [comment]
> 这个问题可以说是非常难复现了.
> 完全就是随机触发, 做不到变量可控...
> 想要复现就得点点点, 跟某乎上那个"插拔1w次U盘系统就会把U盘格式化"那种bug差不多, 想要复现非常耗时耗力.
> 一旦卡死调试工具就掉线, 如果没有定位到问题代码, 那就只能全部重来.
> 
> 这页面直接卡死了, 已经不是影响体验的问题了, 可能会导致用户丢失数据.
> 虽然这种反馈很无厘头, 什么分析什么证据都没有, 但是换谁来整也整不出什么证据啊.
> 只能认为是嫌麻烦所以不重视了...

你试下官网的会不会，我现在试不会了，估计BUG 修正了。。

**Comment by flmbbb** [comment]
> 这个问题可以说是非常难复现了。
> 完全就是随机触发，做不到变量可控...
> 想要复现就得点点点，跟某乎上那个“插拔1瓦特次ü盘系统就会把ú盘旋”那个bug差不多，复现非常耗时耗力。
> 点击卡死调试工具就掉线，如果没有定位到问题代码，那就只能全部重来了。
> 
> 这页面直接卡死了，已经不是影响体验的问题了，可能会导致用户丢失数据。
> 虽然这种反馈很无厘头，什么分析什么证据都没有，但是换谁来整也整不出什么证据啊。
> 只能认为是嫌麻烦所以不知道了...

晕还是会。。。。多测几下就会了。。等他们推新版吧。。我看已经回复我在解决了。。

**Comment by flmbbb** [comment]
谢谢各位大大的支持

**Comment by xiaoxian521** [comment]
> 谢谢各位大大的支持
发版了 你再试试

**Comment by mianlang** [comment]
> 发版了 你再试试

有个疑问：
注意到相关 issue 大概近一周密集出现。我这边 self hold 锁定了 element plus 和 vue 版本，之前一直没问题，直到约一周前。
请问问题产生原因跟外部环境（例如第三方库或浏览器实现）有关吗？
