### ISSUE TITLE
[bug report] the dropdown drop-down menu cannot be opened when the theme generated by the command line theme tool is used

### ISSUE THREAD

**Issue by tBYTL** [element-plus/element-plus#3549]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
版本 93.0.4577.82（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
通过命令行主题工具生成主题
编译主题
在页面添加Dropdown 下拉菜单
启动项目，访问页面

### What is Expected?
Dropdown 下拉菜单 可以正常使用

### What is actually happening?
Dropdown 下拉菜单 无法正常显示，现在的是显示了一个小白块。

**Comment by bastarder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by tBYTL** [comment]
.... 第一次提问题，不太了解，链接复制的别人的。。。
