### ISSUE TITLE
Better Responsive Support?

### ISSUE THREAD

**Issue by AugmentBLU** [element-plus/element-plus#355]
Hello, I'm currently building an app using Element UI and found the responsive support for smaller screens to be a little poor. Will Element Plus be looking at better support for responsive design or follow Element UI's ethos that the framework is more for desktop usage?

**Comment by g3r4n** [comment]
@AugmentBLU I don't think, it's on the Roadmap.
The updated web still mention it's for a Desktop usage:
![image](https://user-images.githubusercontent.com/10941033/94366724-63abb500-00da-11eb-8749-10f5e0f17c07.png)

**Comment by zazzaz** [comment]
However, we could do something later to improve responsive support if it does not cost too much.

**Comment by shaci** [comment]
> Hello, I'm currently building an app using Element UI and found the responsive support for smaller screens to be a little poor. Will Element Plus be looking at better support for responsive design or follow Element UI's ethos that the framework is more for desktop usage?

Can you give examples of the bad responsive support for smaller screens? I'm just interesting, it is useful information for future. I found this - https://github.com/ElemeFE/element/issues/6967  ("el-col layout breakpoints different than bootstrap breakpoints" - and support of screens that are smaller than 768 pixels is very necessary)
And this https://github.com/ElemeFE/element/issues/1561

**Comment by marcoValkyriweb** [comment]
@shaci a great one would be to have date picker range to work with a single pane.

**Comment by JeremyWuuuuu** [comment]
We will consider remake the layout part in the future. Closing this
