### ISSUE TITLE
[Bug Report] Console shows that 'tab-pane' cannot be found when referencing component 'ElTabPane' on demand

### ISSUE THREAD

**Issue by LittleCountryw** [element-plus/element-plus#3554]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
win10

### Vue version
3.2.13

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr?editors=1010

### Steps to reproduce
1.npm install element-plus
2.npm install babel-plugin-import -D
3.add the code shown in the document to babel.config.js
4.register the component and use it in App.vue
5.npm run serve

### What is Expected?
Display Tabs and TabPane properly like the documentation example

### What is actually happening?
Console outputs：
Failed to compile with 1 error                                                                                                                         下午5:17:39
This dependency was not found:

* element-plus/lib/components/tab-pane in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=ts

To install it, you can run: npm install --save element-plus/lib/components/tab-pane
No issues found.
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'

**Comment by JeremyWuuuuu** [comment]
Normally you do not import `ElTabPane` independently when you are using on demand css plugins.

Try:

```ts
import { ElTab } from 'element-plus'

const { ElTabPane } = ElTab
```

**Comment by JeremyWuuuuu** [comment]
We had this noted in the discussion, if you prefer a detailed list here is the link.
https://github.com/element-plus/element-plus/discussions/3020 :bow:

**Comment by LittleCountryw** [comment]
Thank you for your reply！
But my compiler reminds me that "element-plus"' has no exported member named 'ElTab'
How can I use it currently, Are there some examples for reference?

**Comment by JeremyWuuuuu** [comment]
@LittleCountryw My apologies, `ElTabs`.

**Comment by LittleCountryw** [comment]
Sorry to bother you again, it still doesn't work correctly

![test1](https://user-images.githubusercontent.com/81803999/134337146-cd54da2f-e7ac-42c2-99c1-00db8377e7a8.png)
![res1](https://user-images.githubusercontent.com/81803999/134337154-98aa1f93-bdd8-43cd-957c-f9896cefa054.png)

I noticed that the official Documents no longer use 'babel-plugin-import' as the plugin for on-demand Import, does this mean that I need to change the plugins to use them properly?

**Comment by PiciuU** [comment]
Gonna join this discussion as I have very similar problem. Im trying to import on demand components, which works but only for "parent" components. For example if im trying to import ElFormItem, console returns same warning like on an image above. 

> Failed to resolve component: el-form-item
> If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement


My main.js

```
import { createApp } from 'vue';

import App from './App.vue';
import router from './router';
import store from './store';

import { ElButton, ElRadio, ElForm, ElFormItem } from 'element-plus';
const components = [ ElButton, ElRadio, ElForm, ElFormItem ];

const app = createApp(App);

components.forEach((component) => {
 	app.component(component.name, component);
});

app.use(store).use(router).mount('#app');
```
Found this solution on https://github.com/element-plus/element-plus/blob/3b4aa5a03cf1019e1f9f0a6de28edfddaa0e6038/website/docs/en-US/quickstart.md but it doesn't work for me sadly.

**Comment by JeremyWuuuuu** [comment]
@PiciuU Each component that we exposed was assigned a `install` method, which can be directly called with `app.use()` not the different here, it was not **app.component**, I am so sorry that we didn't mention that on the documentation, but in fact you can use `app.use(component)` for your case to work.

**Comment by JeremyWuuuuu** [comment]
@LittleCountryw 
I think the code should be right. See:
![image](https://user-images.githubusercontent.com/15975785/134348229-210e63c2-f3af-4c39-9c49-e5dab1a92f76.png)

Since the plugin is only for css injection, if you are using full sized css file it should work, and we are transforming into `uniplugin` for universal plugin solution, you may checkout the documentation for that.

**Comment by JeremyWuuuuu** [comment]
@PiciuU @LittleCountryw Sorry, I believe not exporting these member in `element-plus` was not the original idea, I will fix that **ASAP**, you can get the correct result in `beta.14`, sorry for your inconvenience and thank you for your understanding :bow:

**Comment by KawaiiZapic** [comment]
> @PiciuU Each component that we exposed was assigned a `install` method, which can be directly called with `app.use()` not the different here, it was not **app.component**, I am so sorry that we didn't mention that on the documentation, but in fact you can use `app.use(component)` for your case to work.
> 
> ==== UPDATE
> @KawaiiZapic I will make a PR for this content in order to cause further issue like this.

Is you mentioning someone else?    
I don't understand why I'm mentioned here.  
Is there a typo in "in order to cause future issue"?

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic Sorry... I mentioned the wrong guy...

**Comment by JeremyWuuuuu** [comment]
@PiciuU @LittleCountryw had a PR here https://github.com/element-plus/element-plus/pull/3563 when this CI passed and merged, we will release another version for the update
