### ISSUE TITLE
[Bug Report] memoize-one

### ISSUE THREAD

**Issue by Miss-Sixty** [element-plus/element-plus#3555]
### Element Plus version
1.1.0-beta.13

### OS/Browsers version
win11

### Vue version
3.2.13

### Steps to reproduce
初始项目后报错

### What is Expected?
正常运行

### What is actually happening?
```shell
This dependency was not found:

* memoize-one in ./node_modules/element-plus/es/components/virtual-list/index.js 

To install it, you can run: npm install --save memoize-one
```

**Comment by JeremyWuuuuu** [comment]
@Miss-Sixty Sorry that was my bad. I will fix this in the next version for temporary fix you should install that manually. :bow:

**Comment by kuka-radovan** [comment]
Could you publish this simple fix to npm?
