### ISSUE TITLE
[bug report] the additional DOM added in the message component has not been removed

### ISSUE THREAD

**Issue by lin-xi** [element-plus/element-plus#3568]
### Element Plus version
1.1.0-beta.13

### OS/Browsers version
MacOS 11.5.2

### Vue version
3.2.13

### Reproduction Link
https://codepen.io/lin-xi_1470379435/pen/BaZPLmN

### Steps to reproduce
1.open https://element-plus.org/zh-CN/component/message.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
2. click "show message" button

### What is Expected?
-----------
<div aria-hidden="true" class="el-popper is-dark" id="el-popper-7028" role="tooltip" style="z-index: 2038; display: none;">查看源文件</div>
-----------
message消失的时候，这个dom应该要被删掉

### What is actually happening?
-----------
<div aria-hidden="true" class="el-popper is-dark" id="el-popper-7028" role="tooltip" style="z-index: 2038; display: none;">查看源文件</div>
-----------
message消失的时候，这个dom没有被删掉

**Comment by bastarder** [comment]
message box的 dom是 `el-message el-message--info`, 有被销毁啊，你看到的是页面上其他的popper的dom，请再核实下~
