### ISSUE TITLE
[feature request] el-upload berforeUpload async

### ISSUE THREAD

**Issue by YangLG-7** [element-plus/element-plus#3569]
HI!
At first,thanks coding,It isn't an issue, I hava an idea about el-upload.

if  you hava some async methods in beforeUpload Hooks，such as validate image width or height。maybe you can use FileRender to reade the result and use the `new Imgae` to accept it。I can also change this asynchronous method to synchronous。like:
```
const beforeUpload = async ()=>{
    const result  = await Promise.all([// some async methods])
}
```
but how can I abort the upload , bro。 

I check out the code.
https://github.com/element-plus/element-plus/blob/a887a9632e38def4c90461fb6d9eb637e89b474e/packages/components/upload/src/upload.vue#L186

Maybe this would be better like
```
 if (before instanceof Promise) {
        before
          .then((processedFile) => {
            const fileType = Object.prototype.toString.call(processedFile)
            if (fileType === '[object File]' || fileType === '[object Blob]') {
              if (fileType === '[object Blob]') {
                processedFile = new File([processedFile], rawFile.name, {
                  type: rawFile.type,
                })
              }
              for (const p in rawFile) {
                if (hasOwn(rawFile, p)) {
                  processedFile[p] = rawFile[p]
                }
              }
              post(processedFile)
            } else if(fileType === '[object Boolean]'&&!fileType) { // Maybe it would be better to add a forbidden value
              props.onRemove(null, rawFile)
            }else{
              post(rawFile)
            }
          })
          .catch(() => {
            props.onRemove(null, rawFile)
          })
      }
```

**Comment by bastarder** [comment]
`beforeUpload` support 'Promise',
did you try 
`
const beforeUpload = () => {
   return Promise.resolve();
}
`

**Comment by YangLG-7** [comment]
> `beforeUpload` support 'Promise',
> did you try
> `const beforeUpload = () => { return Promise.resolve(); }`

hi~，I did know it 。 but how can you abort the upload in beforeUpload hooks if you use promise 。the el-upload components dont konw you want to abort  it。because 

https://github.com/element-plus/element-plus/blob/a887a9632e38def4c90461fb6d9eb637e89b474e/packages/components/upload/src/upload.vue#L186

if the ```beforeUpload instanceof Promise```  and if the ```processedFile```  not a file or Blod 。it ````post(rawFile)``
@bastarder

**Comment by sxzz** [comment]
Close via #6014
