### ISSUE TITLE
[Bug Report] Build failed because memoize-one

### ISSUE THREAD

**Issue by adiramardiani** [element-plus/element-plus#3573]
### Element Plus version
1.1.0-beta.14

### OS/Browsers version
Windows 10

### Vue version
3.2.14

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/4

### Steps to reproduce
Help

I use yarn and vite, and on latest version cannot I build and give 

"node_modules/element-plus/es/components/virtual-list/index.js:5:17: error: Could not resolve "memoize-one" (mark it as external to exclude it from the bundle)" error

### What is Expected?
Application can build normally

### What is actually happening?
I use yarn and vite, and on latest version cannot I build and give "node_modules/element-plus/es/components/virtual-list/index.js:5:17: error: Could not resolve "memoize-one" (mark it as external to exclude it from the bundle)" error

**Comment by BarneyRoos** [comment]
yarn add memoize-one

**Comment by JeremyWuuuuu** [comment]
Fixed in #3572

**Comment by JeremyWuuuuu** [comment]
New version publish has been triggered. In ~6mins the new version will be available.
