### ISSUE TITLE
When a field in the [feature request] element plus form fails, the button becomes gray and cannot be clicked. It becomes clickable as the verification passes

### ISSUE THREAD

**Issue by HaoAurora** [element-plus/element-plus#3579]
### Existing Component
Yes

### Component Name
ElForm

### Description
can The element plus form button gray unclickable when a field fails, as the validation becomes clickable?

**Comment by sxzz** [comment]
It is recommended to implement this function by yourself.
If you have further ideas, please post a new post at [Discussions](https://github.com/element-plus/element-plus/discussions).
