### ISSUE TITLE
[Bug Report] ElForm Methods validate callback invalid

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#3581]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
macOs Chrome 93.0.4577.63

### Vue version
3.2.14

### Steps to reproduce
use form methods validate
callback function invalid
or use return Promise can't trigger then/catch

### What is Expected?
It's good  in element-plus 1.1.0-beta.12 
use form methods validate

### What is actually happening?
It's bad  in element-plus 1.1.0-beta.12 after taht
use form methods validate

**Comment by linsiming** [comment]
I found a situation that caused the problem, that is, el-form-item the prop attribute was added. However, this problem occurs if no rules are set.

If I add this prop required entry in rules, I can submit it.

**Comment by yuyx91** [comment]
same problem

**Comment by H-Haynes** [comment]
I have the  same problem, my version is  1.1.0-beta.24,  callback is well ,but Promise did not work
