### ISSUE TITLE
[Bug Report] Migrate to Element-plus from element-ui Bug

### ISSUE THREAD

**Issue by cavallaro123** [element-plus/element-plus#3585]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
Chrome Version 93.0.4577.82 (Official Build) (x86_64)

### Vue version
3.2.0

### Reproduction Link
https://github.com/cavallaro123/vue3-migration-element

### Steps to reproduce
install element ui in vue 2 application
install [migration build ](https://v3.vuejs.org/guide/migration/migration-build.html)
switch to element plus

### What is Expected?
I am on project in Vue2 and use element-ui, but we want upgrade our project to Vue3. For this we need to pass on Element-plus (element-ui doesn't compatible with Vue3).

### What is actually happening?
I'm seeing an error when using a component from element plus in the vue migration build
`TypeError: slot is not a function.`
<img width="738" alt="Screen Shot 2021-09-23 at 2 05 57 AM" src="https://user-images.githubusercontent.com/91242549/134461152-41d6da1c-7c6d-47de-8b64-1fbe34b91148.png">

**Comment by bastarder** [comment]
`https://github.com/cavallaro123/vue3-migration-element` Page not found

**Comment by cavallaro123** [comment]
@bastarder Please try again, sorry it was private

**Comment by jasondeng** [comment]
We're encountering this for a few components (autocomplete, select, etc., anything that uses a popper) when migrating our Vue 2 project to Vue 3 using the migration build.

**Comment by nailonair** [comment]
Hi, We're seeing the same error in our project thats trying to use Vue 3 migration build which is causing us to not be able to progress in migrating to Element Plus or Vue 3. 

Please advise if there is a fix/workaround or if Element Plus will be compatible with the migration build in the near future since it looks like right now, it isn't.

**Comment by sxzz** [comment]
@jasondeng OK. I will check this later.

**Comment by sxzz** [comment]
@jasondeng I tried add some codes below and it will work.

https://github.com/jasondeng/vue3-element-ui-example/blob/27aca65e93da9b3a021d08b55eeae6e7833c69db/src/main.js#L6

```ts
configureCompat({
  MODE: 3
});
```

**Comment by entioentio** [comment]
@sxzz Thank you, it really saves my day. Isn't it a good idea to mention that in the migration docs?

**Comment by jasondeng** [comment]
@sxzz Thanks, this did it for me! For those curious, `RENDER_FUNCTION` is the specific flag that fixes this error (although this would seem to cause Vue 2 libraries, ie `vue-router@3` that requires compat to fail in the migration build)

```javascript
import { configureCompat } from "vue";

configureCompat({
  RENDER_FUNCTION: false
});

```
