### ISSUE TITLE
Not export el-option?

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#360]
```
    <el-select class="select" v-model="curPageSize" placeholder="展示条数">
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"/>
    </el-select>
```

Failed to resolve component: el-option

don't export el-option?

**Comment by g3r4n** [comment]
@XingXiaoWu  Select isn't in the dev branch or in Alpha build yet. You'll have to wait or test with https://github.com/element-plus/element-plus/pull/318

**Comment by JeremyWuuuuu** [comment]
Closing this issue for now due to `Select`'s migration has not completed, you can track #318 to see if it gets merged.

**Comment by zazzaz** [comment]
el-select is avaliable in 1.0.1-alpha.4
