### ISSUE TITLE
[Bug Report] When el-form has only one form-item containing input, pressing the Enter key in the input will trigger the page refresh

### ISSUE THREAD

**Issue by 827753181** [element-plus/element-plus#3600]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
MAC/Google Chrome 93.0.4577.82

### Vue version
3.2.16

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-b7sk1?file=/src/App.vue

### Steps to reproduce
1.使用el-form，子元素只有一个el-form-item，el-form-item的子元素是一个el-input

2.聚焦到el-input

3.按下enter键

### What is Expected?
当el-form只有一个包含el-input的el-form-item时，在el-input中按下enter键不会触发页面刷新

### What is actually happening?
当el-form只有一个包含el-input的el-form-item时，在el-input中按下enter键会触发页面刷新

当el-form只包含两个及以上的el-form-item时，在其中一个el-form-item下的el-input中按下enter键不会触发页面刷新

**Comment by sxzz** [comment]
It's by design.

Doc: https://element-plus.org/en-US/component/form.html#basic-form

> TIP
>
> W3C regulates that
>
> When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.
>
> To prevent this behavior, you can add @submit.prevent on <el-form>.

**Comment by sxzz** [comment]
@JokTronki Please provide a minimum reproduction link.

**Comment by sxzz** [comment]
Due to unable to reproduce the problem, I have no idea to help you, please make sure that your version is the latest version.

**Comment by sxzz** [comment]
You can renew an issue and upload your project code to GitHub repo.
