### ISSUE TITLE
[Bug Report] [Vue warn]: A plugin must either be a function or an object with an "install" function

### ISSUE THREAD

**Issue by shenxingchao** [element-plus/element-plus#3603]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
none

### Vue version
3.2.16

### Reproduction Link
https://codepen.io/shenxingchao/pen/ZEyMRGa?editors=1111

### Steps to reproduce
```
app.use(ElementPlus); //this line reports warnings A plugin must either be a function or an object with an "install" function
```

### What is Expected?
no warnings

### What is actually happening?
console output warnings: A plugin must either be a function or an object with an "install" function
not in 1.1.0-beta.8

**Comment by xiaotongXT** [comment]
me too!

**Comment by Targzp** [comment]
I hope this problem can be solved as soon as possible

**Comment by hcw2175** [comment]
+1

**Comment by xiaoxian521** [comment]
We are very sorry, we will fix it in the next version, it will not affect the use for the time being

**Comment by jijieoo** [comment]
this warning make some components disabled,like el-form.

**Comment by wirk** [comment]
Thanks for looking into this, here is a list of affected components:

```
ElBreadcrumbItem
ElButtonGroup
ElCarouselItem
ElCheckboxButton
ElCheckboxGroup
ElCollapseItem
ElAside
ElFooter
ElHeader
ElMain
ElDescriptionsItem
ElDropdownItem
ElDropdownMenu
ElFormItem
ElMenuItem
ElMenuItemGroup
ElRadioButton
ElRadioGroup
ElOption
ElOptionGroup
ElSkeletonItem
ElStep
ElTableColumn
ElTabPane
ElTimelineItem
```

**Comment by JeremyWuuuuu** [comment]
I myself introduced this issue to this version in order to expose sub components for non-plugin users, and this **won't** affect the functionality of using the component, I will make a patch for this ASAP.

**Comment by JeremyWuuuuu** [comment]
UPDATE:

The PR is already submitted, after review and CI pipeline we should be able to merge it. Also release a version at the weekend, sorry for the inconvenience that I bought :bow: I will be more careful in the future development. :pray:

**Comment by wirk** [comment]
no problem, thank you for your work and the quick patch!
