### ISSUE TITLE
[Feature Request] Select V2 virtualized does not support case insensitive

### ISSUE THREAD

**Issue by duybt** [element-plus/element-plus#3606]
### Existing Component
Yes

### Component Name
el-select-v2

### Description
This component is supported the filterable with case sensitive, I think it should support case insensitive like v1 or could we have a custom filter method?

**Comment by msidolphin** [comment]
You can use `filter-method` property, just like select

**Comment by AubSs** [comment]
filter-method do not work on select-v2.

**Comment by msidolphin** [comment]
> filter-method do not work on select-v2.
> I assume this is why it's not documented

```vue
<template>
  <el-select-v2
    v-model="value"
    filterable
    :filter-method="filterMethod"
    :options="options"
    placeholder="Please select"
    style="width: 240px"
    multiple
  />
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue'
import { ElSelectV2 } from '@element-plus/components'
const initials = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

export default defineComponent({
  components: {
    ElSelectV2,
  },
  setup() {
    const data = Array.from({ length: 1000 }).map((_, idx) => ({
      value: `Option${idx + 1}`,
      label: `${initials[idx % 10]}${idx}`,
    }))
    const options = ref(data)
    return {
      options,
      value: ref([]),
      filterMethod(query) {
        options.value = data.filter((item) => item.label.startsWith(query))
      },
    }
  },
})
</script>

```

**Comment by AubSs** [comment]
@msidolphin 

I tried that.
Filter-method is being called, option is being filtered, but "filterable" seems to filter the filtered options and then you lost all result.

The work around is to use filterable + remote + remote-method.
