### ISSUE TITLE
[Bug Report] [Vue warn]:failed to compile from element-plus 1.1.0-beta.15

### ISSUE THREAD

**Issue by zhangbin1010** [element-plus/element-plus#3608]
WARNING  Compiled with 1 warning                                                                                                                                            
warning  in ./node_modules/element-plus/es/components/button/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

"dependencies": {
    "axios": "^0.21.4",
    "core-js": "^3.18.0",
    "cropperjs": "^1.5.12",
    "echarts": "^5.2.1",
    "element-plus": "^1.1.0-beta.15",
    "js-base64": "^3.7.2",
    "js-cookie": "^3.0.1",
    "js-sha256": "^0.9.0",
    "mockjs": "^1.1.0",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "qs": "^6.10.1",
    "vue": "^3.2.6",
    "vue-axios": "^3.3.7",
    "vue-i18n": "^9.2.0-beta.3",
    "vue-json-editor": "^1.4.3",
    "vue-router": "^4.0.11",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^5.0.0-beta.3",
    "@vue/cli-plugin-router": "^5.0.0-beta.3",
    "@vue/cli-plugin-vuex": "^5.0.0-beta.3",
    "@vue/cli-service": "^5.0.0-beta.3",
    "@vue/compiler-sfc": "^3.2.16",
    "css-loader": "^6.3.0",
    "less": "^4.1.1",
    "less-loader": "^10.0.1",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^5.53.0"
  },

Accessing the display with the browser failed to compile

reproduce code: https://github.com/zhangbin1010/acp-admin

**Comment by xiaoxian521** [comment]
this is same issues: https://github.com/element-plus/element-plus/issues/3603

**Comment by WaqasIbrahim** [comment]
@xiaoxian521 I don't think it's the same issue. Still getting the same warnings with beta.16

**Comment by sxzz** [comment]
Fixed in #3615
