### ISSUE TITLE
Vue warn]: setup() return property "_confirmButtonText" should not start with "$" or "_" which are reserved prefixes for Vue internals.

### ISSUE THREAD

**Issue by songjiachao** [element-plus/element-plus#3613]
![image](https://user-images.githubusercontent.com/70792885/134657116-4472b932-b19a-4002-87ed-7ef7bcb44667.png)
<template>
<el-dialog title="添加用户" v-model="userDialogVisible" @closed="userDialogclose">
</el-dialog>
</template>
<script lang="ts" setup>
</script>

**Comment by JeremyWuuuuu** [comment]
cc @sxzz
