### ISSUE TITLE
[Bug Report] website color-picker and select

### ISSUE THREAD

**Issue by btea** [element-plus/element-plus#3616]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
win10/Brwoser

### Vue version
3.2.16

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
https://element-plus.org/zh-CN/component/color-picker.html
![image](https://user-images.githubusercontent.com/24516654/134671109-07410199-3c26-4247-a7f3-50d3046c7c6f.png)

https://element-plus.org/zh-CN/component/select.html
![image](https://user-images.githubusercontent.com/24516654/134671076-a9d4950f-96de-451d-871d-de829ee9b4fd.png)

### What is Expected?
the color-picker panel position is correct.
the select demo is correct.

### What is actually happening?
see the image.

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/134799594-ef4876e0-f010-4340-9ea3-1652a56f6f3a.png)
