### ISSUE TITLE
Add Icon Picker

### ISSUE THREAD

**Issue by zaingithub** [element-plus/element-plus#362]
Hi, this would be nice if there is icon picker included in this project. Thanks.

**Comment by zazzaz** [comment]
What is an "icon picker", please? Do you mean https://element-plus.org/#/en-US/component/icon

**Comment by JeremyWuuuuu** [comment]
@zaingithub would you mind to be more specific about the feature you requested? Give us a screen recording or something we that we can understand what we need to do.

**Comment by codesinging** [comment]
I think he means that icon picker is like this:

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gj6h39gfnrj30fm0jmtb2.jpg)

**Comment by JeremyWuuuuu** [comment]
I don't quite understand, besides the filterable select, what benefit you can get comparing  to `cmd/ctrl` + `F` provided by browser?
![image](https://user-images.githubusercontent.com/15975785/94413929-506a1980-01ae-11eb-8793-8369535d92cd.png)

**Comment by zhixiaotong** [comment]
IMHO, it‘s not necessary...Empty、Skeleton and so on instead

**Comment by JeremyWuuuuu** [comment]
@zhixiaotong , I personally do have a plan on adding `Skeleton` component in the near future.

**Comment by codesinging** [comment]
Maybe it's different users, one for web developers and one for users of the application. haha

**Comment by zhixiaotong** [comment]
> Maybe it's for different users, one for web developers and one for users of the application. haha

svg icon is usually used much more in my practice

**Comment by zaingithub** [comment]
> What is an "icon picker", please? Do you mean https://element-plus.org/#/en-US/component/icon

Hi, i am sorry for late response. I mean icon picker like this : https://victor-valencia.github.io/bootstrap-iconpicker/

**Comment by diction** [comment]
support+1，支持+1

**Comment by zazzaz** [comment]
Sorry, we have no plan to support this.
