### ISSUE TITLE
[bug report] El menu occupies memory

### ISSUE THREAD

**Issue by songyingchao-cn** [element-plus/element-plus#3622]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
win10 /chrome版本 93.0.4577.82（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/songyingchao-cn/pen/vYZVNLK

### Steps to reproduce
 
     当我持续增加menus里面的元素的时候，页面会崩溃
  
    menus :[
      {text:"11134343434343434"},]
 

### What is Expected?
当menus 里面的元素增加到超过页面宽度的时候希望能正常显示

### What is actually happening?
当menus 里面的元素增加到超过页面宽度的后，多出来的菜单会被省略显示成3个黑点（这个是希望得到的结果），但是同时CPU占用100%，内存不停的增加直到页面崩溃，控制台没有报错

**Comment by sxzz** [comment]
It has been fixed. https://github.com/element-plus/element-plus/pull/3617
