### ISSUE TITLE
[Bug Report] Icon for the Element Plus  component unable to display normally

### ISSUE THREAD

**Issue by Flipped199** [element-plus/element-plus#3626]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
Mac OS 10.15.7 / Chrome 93.0.4577.63

### Vue version
3.2.12

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-d410r

### Steps to reproduce
unable to show the previous icon of msg

### What is Expected?
。。。

### What is actually happening?
。。。

**Comment by xiaoxian521** [comment]
hey, I took a look at your recurring address and found that the element-plus version you are using is very low, please use the latest version, it is no problem
https://element-plus.org/zh-CN/guide/quickstart.html#full-import

**Comment by Flipped199** [comment]
Hello, I have upgraded the element-plus version to 1.1.0-beta.18, and the problem still exists.

https://codesandbox.io/s/element-plus-spa-forked-d410r?file=/src/main.js:226-227

**Comment by xiaoxian521** [comment]
![image](https://user-images.githubusercontent.com/44761321/135290641-e32d707c-8511-4e50-b1dd-e4f1b48cdd6b.png)
