### ISSUE TITLE
[Bug Report] Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#3628]
Element Plus version
1.1.0-beta.16

OS/Browsers version
windows10 / chrome 93.0.4577.82

Vue version
3.2.16

Webpack version
5.50.0

What is Expected?
webpack 编译时不出现警告

What is actually happening?
在执行 npm run dev 编译时，出现了如下警告：
WARNING in ./node_modules/element-plus/es/components/button/index.js 27:33-40
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by jiaozhiye** [comment]
1.1.0-beta.16 出现了如下警告，在1.1.0-beta12 及之前版本没有出现
![image](https://user-images.githubusercontent.com/22720488/134755909-4eb7e387-a1a9-4b34-9906-66290756a8e9.png)

**Comment by scafel** [comment]
![image](https://user-images.githubusercontent.com/25117857/134759732-afa4583b-af2f-4a46-aeff-705f494319e8.png)

vue 3.2.5
element-plus ^1.1.0-beta.16

**Comment by WaqasIbrahim** [comment]
Same as https://github.com/element-plus/element-plus/issues/3608, which was not fixed but closed.

**Comment by chao921125** [comment]
我这里有一个暂时性的解决方案
Hi all, I have a temporary solution here

在vue.config.js配置里面
In the vue.config.js file

添加以下代码即可
Add some code well

configureWebpack: {
    module: {
      unknownContextCritical: false
    }
  }

以下是我的项目地址
This is my project address
https://github.com/chao921125/vue-basic

**Comment by SHDjason** [comment]
我也出现这个问题
![image](https://user-images.githubusercontent.com/53029973/134798632-7634a75c-3471-44ec-a740-e49c497acac1.png)

**Comment by zhangbin1010** [comment]
Same as #3608 , which was not fixed but closed.

**Comment by zhangbin1010** [comment]
Upgrade to 1.1.0-beta.17，this issue was was solved!
