### ISSUE TITLE
[Feature Request] Can you add a ListView component for mobile page development

### ISSUE THREAD

**Issue by Silentdoer** [element-plus/element-plus#3631]
### Existing Component
No

### Component Name
ListView

### Description
我用element plus开发了移动端页面，发现也是基本没有什么问题，最大的问题之一是分页组件不兼容，和缺少ListView，其它的用到移动端基本上稍微修改一下css就可以完成了，所以能否增加一些适配移动端的组件这样用element plus就可以开发多个平台了

**Comment by msidolphin** [comment]
Sry, element-plus is a desktop ui component library, this feature will not be considered
