### ISSUE TITLE
There is no lang.json file in the [bug report] I18N directory

### ISSUE THREAD

**Issue by asdlml6** [element-plus/element-plus#3633]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
win10

### Vue version
3.2.18

### Reproduction Link
https://github.com/element-plus/element-plus/tree/dev/docs/.vitepress/crowdin/en-US

### Steps to reproduce
i18n目录下找不到lang.json文件，整个项目目录里也没有lang.json文件

### What is Expected?
希望尽快得到一个答复，谢谢

### What is actually happening?
希望尽快得到一个答复，谢谢

**Comment by sxzz** [comment]
Please run `pnpm docs:gen-locale`
