### ISSUE TITLE
[bug report] el-date-picker throws errors

### ISSUE THREAD

**Issue by zwonki** [element-plus/element-plus#3634]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
Windows 10 / Chrome 94.0.4606.61

### Vue version
3.2.18

### Steps to reproduce
When selecting a date in el-date-picker the following errors occurs:

Uncaught (in promise) TypeError: props.date.locale(...).localeData is not a function
Uncaught (in promise) TypeError: callback is not a function

in 1.1.0-beta.12 there was no problems

### What is Expected?
No Errors

### What is actually happening?
Errors

**Comment by adarshmadrecha** [comment]
Yes, even I am getting error when user selects daterange

```vue
       <el-date-picker
          v-model="dtCreatedAt"
          type="daterange"
          unlink-panels
          range-separator=""
          start-placeholder="Start date"
          end-placeholder="End date"
        >
        </el-date-picker>
```

Browser Console Logs
![image](https://user-images.githubusercontent.com/11911938/134780883-c30a3fb7-1540-4ef2-aeb5-fb173b6694c0.png)

**Comment by jerrytang67** [comment]
When update to beta 16 .The same error
