### ISSUE TITLE
[Bug Report] when navigator.language is `en`, official website tries to jump to ` https://element-plus.org/en/ ` which is not exist

### ISSUE THREAD

**Issue by CGQAQ** [element-plus/element-plus#3641]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
Windwos 10  chrome93

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/

### Steps to reproduce
navigator.language设置成 en  打开官网https://element-plus.org/

### What is Expected?
跳到 https://element-plus.org/en-US

### What is actually happening?
跳到了 https://element-plus.org/en

**Comment by JeremyWuuuuu** [comment]
I think that was my fault... I didn't realize that `en` is actually a valid language sign :bow:
