### ISSUE TITLE
[feature request] if there are too many cell contents in the table, the table will wrap automatically, resulting in the table height lengthening. Can you add a scheme (overflow ellipsis El tooltip)

### ISSUE THREAD

**Issue by Yaozefen** [element-plus/element-plus#3647]
### Existing Component
Yes

### Component Name
1.0.2-beta.71

### Description
Windows 10 家庭中文版 20H2 / Google Chrome 版本 92.0.4515.131（正式版本） （64 位）

**Comment by xiaoxian521** [comment]
@Yaozefen Hey, please provide a minimum recurring address for us to debug

**Comment by Yaozefen** [comment]
@xiaoxian521 https://jsfiddle.net/e0c6on81/5/       某一列的文字过多就会无限拉长列的高度，希望看到的是：文字过多显示省略号，然后hover上去就显示全部文字。
