### ISSUE TITLE
[Bug Report] Site element-plus.org dont work correct

### ISSUE THREAD

**Issue by victor-chauzov** [element-plus/element-plus#3650]
Site element-plus.org dont work correct

### What is Expected?
Docs: https://element-plus.org/#/en-US/component/

### What is actually happening?

HomePage: https://element-plus.org/#/en-US
Docs: https://element-plus.org/#/en-US/component/

wrong redirect to 

https://element-plus.org/ru-RU/
https://element-plus.org/ru-RU/#/en-US
https://element-plus.org/ru-RU/#/en-US/component/

**Comment by ilaorou** [comment]
什么情况?
这两天都打不开文档,不维护了吗?

**Comment by sxzz** [comment]
Docs link:

```diff
--- https://element-plus.org/#/en-US/
+++ https://element-plus.org/en-US/
```

**Comment by victor-chauzov** [comment]
thanks, i found the documentation))
but the problem remained.
from the 2nd level domain element-plus.org automatically redirect to  https://element-plus.org/ru-RU/
ru-RU is missing, so 404 error

**Comment by sxzz** [comment]
Fixed.

**Comment by msidolphin** [comment]
> thanks, i found the documentation))
> but the problem remained.
> from the 2nd level domain element-plus.org automatically redirect to https://element-plus.org/ru-RU/
> ru-RU is missing, so 404 error

We don't  support Russian for now, I suggest you open a new issue to mention this
