### ISSUE TITLE
[bug report] in the case of color picker show alpha, the color format cannot be set to hex hexadecimal

### ISSUE THREAD

**Issue by SignDawn** [element-plus/element-plus#3654]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
Microsoft Edge 94.0.992.31

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/signdawn/pen/wveQwZo

### Steps to reproduce
无

### What is Expected?
希望能够在 active-change 和 change 方法中返回 hex 格式的数据

### What is actually happening?
实际上返回的仍然是一个 rgba 的结果。

**Comment by zwonki** [comment]
+1
#rrggbbaa hex color notation
[https://caniuse.com/css-rrggbbaa](url)

**Comment by Yaozefen** [comment]
官网：ColorPicker 支持普通颜色，也支持带 Alpha 通道的颜色， 要启用 Alpha 选择，只需添加 show-alpha 属性。
去掉show-alpha返回的不就是hex颜色了么？我不理解

**Comment by SignDawn** [comment]
> 官网：ColorPicker 支持普通颜色，也支持带 Alpha 通道的颜色， 要启用 Alpha 选择，只需添加 show-alpha 属性。
> 去掉show-alpha返回的不就是hex颜色了么？我不理解

我需要的包含透明度的 hex 颜色， #rrggbbaa ，最后两位表示透明度

**Comment by JeremyWuuuuu** [comment]
> > 官网：ColorPicker 支持普通颜色，也支持带 Alpha 通道的颜色， 要启用 Alpha 选择，只需添加 show-alpha 属性。
> > 去掉show-alpha返回的不就是hex颜色了么？我不理解
> 
> 我需要的包含透明度的 hex 颜色， #rrggbbaa ，最后两位表示透明度

是个合理的需求，#3893 已经有个 PR 来做这个了。我们会尽快合进 dev cc @zwonki @SignDawn

**Comment by SignDawn** [comment]
@JeremyWuuuuu 
已经发布到最新的 npm 包了吗？
可以告知一下版本吗？谢谢！
