### ISSUE TITLE
[bug report] input box and drop-down box cannot be displayed normally

### ISSUE THREAD

**Issue by luofeidetuzi** [element-plus/element-plus#3655]
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
5.0（Windows NT 10.0；WOW64）AppleWebKit/537.36（KHTML，like Gecko）Chrome/67.0.3396.79 Safari/537.36

### Vue version
3.2.6

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-gbcdy?file=/src/App.vue

### Steps to reproduce
在该vue版本和Element版本，以及该浏览器内核下，一进入有输入框和下拉框的页面，就会不显示相应的输入框，下拉框则是会丢失其输入框

### What is Expected?
正常显示输入框和下拉框

### What is actually happening?
输入框和下拉框丢失，并报错

**Comment by luofeidetuzi** [comment]
![企业微信截图_16326263333135](https://user-images.githubusercontent.com/59993922/134798091-11ac63f8-a705-435c-9842-fb7c1a6be786.png
![企业微信截图_16326263428714](https://user-images.githubusercontent.com/59993922/134798115-55d83d5b-2e85-43c6-94ec-ca2238e98726.png)
![企业微信截图_16326263739467](https://user-images.githubusercontent.com/59993922/134798127-9d451578-b9e3-4a80-8a40-0c7beb098820.png)
![企业微信截图_16326263817781](https://user-images.githubusercontent.com/59993922/134798129-00b74f7e-1c3b-4949-8e1c-30fa5e47e896.png)
)

**Comment by luofeidetuzi** [comment]
![企业微信截图_16326263333135](https://user-images.githubusercontent.com/59993922/134798277-f97b00c5-759e-441b-a315-5e245a376480.png
![企业微信截图_16326263428714](https://user-images.githubusercontent.com/59993922/134798279-977309d3-ccfa-46ce-a172-708f9fecbb75.png)
![企业微信截图_16326263739467](https://user-images.githubusercontent.com/59993922/134798280-fa76abd2-e0d7-43e1-aa67-6b31812105bf.png)
)
![企业微信截图_16326263817781](https://user-images.githubusercontent.com/59993922/134798282-9296ccfd-d1cb-4547-ac3b-9ac67c660f5b.png)

**Comment by sxzz** [comment]
I can't reproduce it, please provide a reproduction repo.
