### ISSUE TITLE
[bug report] form reset form item does not work

### ISSUE THREAD

**Issue by Yaozefen** [element-plus/element-plus#3657]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
Windows 10 家庭中文版 20H2 / Google Chrome 版本 92.0.4515.131（正式版本） （64 位）

### Vue version
3.2.19

### Reproduction Link
https://jsfiddle.net/bwghvkzt/3/

### Steps to reproduce
随便填入表单任意数据，点提交，查看console

### What is Expected?
表单项被重置

### What is actually happening?
表单项无法被重置

**Comment by bastarder** [comment]
`<el-form-item label="Password" prop="pass">` you should add `prop` on `el-form-item`
