### ISSUE TITLE
[bug report] the < El dialog > customization of elementplus will produce displacement deviation after modifying the center style

### ISSUE THREAD

**Issue by xLong1029** [element-plus/element-plus#3658]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Google Chrome版本 92.0.4515.159

### Vue version
3.2.19

### Reproduction Link
https://codesandbox.io/s/winter-pond-55v01?file=/src/App.vue 【elelemt-plus】

![element-plus弹窗](https://user-images.githubusercontent.com/18066675/134798707-37c248df-7770-4d9e-87a2-bdc52faf80a4.gif)

https://codesandbox.io/s/naughty-breeze-1r0c2?file=/src/App.vue 【elelemt-ui】

![element-ui弹窗](https://user-images.githubusercontent.com/18066675/134798709-d053b62c-d83a-4e1a-ac8c-28c3c81b2227.gif)

### Steps to reproduce
ElementPlus，自定义修改el-dialog样式，使其居中显示，实际效果使用时会产生位移偏差；
ElementUI，相同的写法则没有这个问题，我对比了样式是一样的，不知是哪出错了，请问这个是否可以修复？

### What is Expected?
ElementPlus自定义修改el-dialog样式，能正常显示

### What is actually happening?
ElementPlus自定义修改el-dialog样式后，打开dialog会产生位移偏差

**Comment by Yaozefen** [comment]
#3262 重复问题

**Comment by xLong1029** [comment]
> #3262 重复问题

thanks
