### ISSUE TITLE
[Bug Report] Documentation always redirect to locale and give 404 error

### ISSUE THREAD

**Issue by adiramardiani** [element-plus/element-plus#3663]
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
Windows 10

### Vue version
3.2.19

### Reproduction Link
https://element-plus.org/

### Steps to reproduce
Hai, I need help
Currently I cannot access documentation page

### What is Expected?
Access https://element-plus.org and show documentation

### What is actually happening?
I access https://element-plus.org but always redirect to my locale (maybe locale browser or location), for example https://element-plus.org/in/ wich is always redirect to this and generate git 404 not found. I cannot access documentation page
![image](https://user-images.githubusercontent.com/8703419/134813352-0b610459-a8c6-41f4-92c7-b730565bbabb.png)

**Comment by sxzz** [comment]
Fixed in #3642.

**Comment by sxzz** [comment]
The updated document has not been released yet, please use the development version document https://staging.element-plus.org/ .
