### ISSUE TITLE
[feature request] style optimization of tabs component

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#3676]
### Existing Component
是

### Component Name
el-tabs

### Description
addable这个属性出来的效果不太好看，可以优化

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/134844902-28e60f66-3f02-40e5-ae40-e469c4138671.png)

**Comment by xiaoxian521** [comment]
@PeyFon Please provide a recurring address thank you

**Comment by PeyFon** [comment]
> @PeyFon Please provide a recurring address thank you

We just need to restyle the add button。
https://codepen.io/peyfon/pen/oNwmzbX
