### ISSUE TITLE
[Feature Request] Please provide the distribute with a minified version of index.full.js

### ISSUE THREAD

**Issue by tolbxela** [element-plus/element-plus#3687]
### Existing Component
Yes

### Component Name
index.full.js

### Description
Please provide the distribute with a minified version of the full bundle (index.full.js). I suggest "index.full.min.js" as file name. 
Thanks a lot!

**Comment by sxzz** [comment]
#3677 
You are just a few hours late. 😆
Minified version will be in the next version.
