### ISSUE TITLE
[bug report] vite build official style was not successfully introduced

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#3688]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
Microsoft Edge 94.0.992.31

### Vue version
3.2.19

### Reproduction Link
https://github.com/mxp131011/zlt9_erp_pc_vite

### Steps to reproduce
 Use `unplugin-vue-components` or `unplugin-element-plus` for on-demand loading，The dev versions introduced styles normally, but none of the release versions  styles were successfully introduced
tool： `element-plus 1.1.0-beta.17`      `vite2.5.10`   `vue3.2`  ` javascript`

使用unplugin-vue-components 或 unplugin-element-plus进行按需加载， 测试版都可以正常引入样式，但是发行版样式都没有被成功引入
环境： `element-plus 1.1.0-beta.17`      `vite2.5.10`   `vue3.2`  ` javascript`

vite build
vite preview

### What is Expected?
The release versions style was successfully introduced

正式版样式成功引入

### What is actually happening?
The dev versions introduced styles normally, but none of the release versions  styles were successfully introduced

发行版样式没有被成功引入 ，开发版正常

**Comment by xiaoxian521** [comment]
@mxp131011 Can you give the smallest recurring warehouse, for example, put your code in the github warehouse, and I will help you to check it

**Comment by mxp131011** [comment]
@xiaoxian521 https://github.com/mxp131011/zlt9_erp_pc_vite

**Comment by Name-Terry** [comment]
我的也一样，打包后没有生效

**Comment by mxp131011** [comment]
`unplugin-vue-components` https://github.com/mxp131011/zlt9_erp_pc_vite
`unplugin-element-plus` https://github.com/mxp131011/zlt9_erp_pc_vite2

这两个都是正式版不可以。 我那里做错了，难道必须是TypeScript 开发？

**Comment by mxp131011** [comment]
找到原因了`vite.config.js`中`build.rollupOptions.output.manualChunks `用来配置代码拆分时的问题具体请看图，这应该也是一个bug，但是我不知道怎么修复：


正确拆分方式只能是： 
         ```
       manualChunks(id) {
            if (id.includes('node_modules')) {
              return id.toString().split('node_modules/')[1].split('/')[0].toString();
            }
          }
    ```


![image](https://user-images.githubusercontent.com/31055355/135375299-edf33d86-4ef0-4c65-a54e-55a1596ae81a.png)

**Comment by mxp131011** [comment]
@Name-Terry @xiaoxian521 @rotu @element-bot

**Comment by sxzz** [comment]
> `unplugin-vue-components` [mxp131011/zlt9_erp_pc_vite](https://github.com/mxp131011/zlt9_erp_pc_vite) `unplugin-element-plus` [mxp131011/zlt9_erp_pc_vite2](https://github.com/mxp131011/zlt9_erp_pc_vite2)
> 
> 这两个都是正式版不可以。 我那里做错了，难道必须是TypeScript 开发？

the repo is not exist.

**Comment by Abunuo** [comment]
> 找到原因了`vite.config.js`中`build.rollupOptions.output.manualChunks `用来配置代码拆分时的问题具体请看图，这应该也是一个bug，但是我不知道怎么修复：
> 
> 正确拆分方式只能是： `manualChunks(id) { if (id.includes('node_modules')) { return id.toString().split('node_modules/')[1].split('/')[0].toString(); } }`
> 
> ![image](https://user-images.githubusercontent.com/31055355/135375299-edf33d86-4ef0-4c65-a54e-55a1596ae81a.png)

我一开始也不行，element-plus 升级到 1.1.0-beta.19 就好了，不过目前插件样式还是没有打包成功

**Comment by mxp131011** [comment]
不要用`unplugin-vue-components` 来按需加载所有组件,这个组件其实主要是用来自动引入注册组件的，用这个组件后所有的组件都不用 `import `和 `components：{}`了包含自己写的，所以首次加载会比较慢
建议使用全局手动引入组件 加  `unplugin-element-plus`按需加载样式 的方式来 进行按需加载， （注意指令的样式要单独手动引入）
而且经过对比`unplugin-vue-components` 打包后要比`unplugin-element-plus`打包后大一些
不知道官方为什么在文档推荐使用`unplugin-vue-components` 

![image](https://user-images.githubusercontent.com/31055355/137058132-fdf76790-f588-48e7-8fd1-e9bb36c0c2f0.png)
