### ISSUE TITLE
[Bug Report] 【el-cascader】 When multiple-selection search, when the result item is selected, the input selection search is empty

### ISSUE THREAD

**Issue by shangxinbo** [element-plus/element-plus#3689]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
macboo

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/shangxinbo/pen/JjJeBqd

### Steps to reproduce
1. The setting can be searched, and multiple selections can be made
2. Enter the keyword "s"
3. Click on the search result
4. Keyword is not cleared

### What is Expected?
When clicking on an option, the keyword should be cleared

### What is actually happening?
the keyword without cleared

![image](https://user-images.githubusercontent.com/3213618/134893475-454cc2fa-372e-40a9-921e-8b76cc7cda6a.png)

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/135011341-82ec0101-7148-44a6-9f29-cfefbced4922.mp4
现在是多选时可以点击多次选中多个选项，然后你任意点击其他位置一下输入的文字就被清除了，有什么不对吗？

**Comment by xiaoxian521** [comment]
保留关键字，能够高亮与之匹配的选项，这个体验会更好
