### ISSUE TITLE
[Bug Report] when add rules on a form-item and the component value is array   validate will be not ok

### ISSUE THREAD

**Issue by pangao66** [element-plus/element-plus#3690]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
mac os

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/ilfgisbp/pen/dyRQgGK?editors=1010

### Steps to reproduce
add  reset button 
点击重置按钮

### What is Expected?
validate result will be remove
校验将会清空

### What is actually happening?
the validate result of  radio-group component  is still be wrong  when  I click the reset button
现在点了重置按钮之后, 其他的没有问题, el-radio-group的校验没有清空,当我把rules规则写在form-item上

**Comment by JeremyWuuuuu** [comment]
cc @sxzz is this related to the upgrade?
