### ISSUE TITLE
[Feature Request] can 'elFormItemKey' be defined as a string format

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#3691]
Existing Component
Yes

Component Name
el-form

Description
请问能否把 tokens/form.ts 中的 elFormItemKey 变量还原成之前版本的字符串格式，需求场景如下：
项目中会封装一些自定义的表单组件配合 el-form 使用，为了实现表单校验功能，需要获取 el-form-item 提供的 elFormItem 对象，如果 elFormItemKey 是 Symbol 类型，自定义组件中将无法获取，希望官网能恢复成字符串格式！

**Comment by JeremyWuuuuu** [comment]
cc @sxzz Can we export that from the entry file?


Also, for temporary fix, if you are using `cjs/esm` format, you can import via:

```ts
import { elFormKey } from 'element-plus/es[lib]/tokens`
```

I think it is our responsibilities to export that.

**Comment by JeremyWuuuuu** [comment]
Check this out: https://codesandbox.io/s/sleepy-bash-dxtcr?file=/src/main.js

**Comment by sxzz** [comment]
> Check this out: [codesandbox.io/s/sleepy-bash-dxtcr?file=/src/main.js](https://codesandbox.io/s/sleepy-bash-dxtcr?file=/src/main.js)

@JeremyWuuuuu Your example seems wrong.

**Comment by JeremyWuuuuu** [comment]
> > Check this out: [codesandbox.io/s/sleepy-bash-dxtcr?file=/src/main.js](https://codesandbox.io/s/sleepy-bash-dxtcr?file=/src/main.js)
> 
> @JeremyWuuuuu Your example seems wrong.

Can you point that out?
