### ISSUE TITLE
[Feature Request] Cascader: please add an option to make filtering (searching) case-insensitive

### ISSUE THREAD

**Issue by tolbxela** [element-plus/element-plus#3694]
### Existing Component
Yes

### Component Name
Cascader

### Description
Right now the search (filtering) is case-sensitive. Search is usually case-insensitive and it would be great to have an option to make filtering  case-insensitive. 
Thanks a lot!

**Comment by btea** [comment]
I think this feature can be realized through custom `filter-method` methods. And this is not need add an option, what do you think?

**Comment by Alanscut** [comment]
use `filter-method` like this, you will make filtering case-insecsitive
![image](https://user-images.githubusercontent.com/21104054/136648207-2fce2b35-59cb-4b4c-ba49-5c4ad8b7bedc.png)
![image](https://user-images.githubusercontent.com/21104054/136648214-4e5a8e5d-db27-40c7-9012-e27663cd62d4.png)
![image](https://user-images.githubusercontent.com/21104054/136648220-c7cf5e0c-faaa-462a-a6cb-02813ea4b970.png)

**Comment by chenxch** [comment]
supported
