### ISSUE TITLE
[bug report] El select bind object

### ISSUE THREAD

**Issue by qfcfm** [element-plus/element-plus#3699]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
Microsoft Edge  94.0.992.31

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/cfm1/pen/rNwojdq

### Steps to reproduce
        <el-select
          v-model="currole"
          value-key="name"
          size="mini"
          style="width: 240px"
        >
          <el-option
            v-for="item in allroles"
            :key="item.id"
            :label="item.name"
            :value="item"
          >
          </el-option>
        </el-select>

item没有value属性。

### What is Expected?
选择时，能正常显示已选择状态。

### What is actually happening?
第一个item，一直是hover状态。

**Comment by msidolphin** [comment]
I don't remember value supporting object types, this should be a feature request

**Comment by xiaoxian521** [comment]
label and value coexist
