### ISSUE TITLE
[bug report] colorpicker color bug

### ISSUE THREAD

**Issue by GuCangRan** [element-plus/element-plus#3701]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
Microsoft Edge
版本 94.0.992.31 (官方内部版本) (64 位)

### Vue version
3.2.1

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr/aaa?文档就存在bug,不用测试,sorry

### Steps to reproduce
在edge 94版本下出现这个问题,谷歌低版本不出现, 选择颜色区域,点击确定 颜色就变成黑色的

### What is Expected?
应该选择什么颜色就是什么颜色值,之前版本没这个问题,新版本存在

### What is actually happening?
选择的颜色值被重置为 黑色了

**Comment by GuCangRan** [comment]
发现是浏览 Microsoft Edge 版本 94.0.992.31 (官方内部版本) (64 位)下才出现这个问题

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/135198858-e3a318be-9de2-4c85-bb19-c09e3e1e9b55.png)
![image](https://user-images.githubusercontent.com/26672484/135198881-153c95c6-026b-4120-948d-4e1c36582e89.png)
我和一样的版本，我的没问题哦

**Comment by GuCangRan** [comment]
我重新测试了，无痕打开正常，正常去操作 无论选什么颜色点击确定后颜色变黑色了

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/135210695-fcfd8920-536f-47a2-8618-05b8ee3c650d.png)
我的也没问题

**Comment by GuCangRan** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/135210695-fcfd8920-536f-47a2-8618-05b8ee3c650d.png) 我的也没问题
在颜色上随便选一个颜色， 点击”确定“ 或 ”OK“ 这个颜色就变为黑色了 难道我电脑有毒么

**Comment by Alanscut** [comment]
没问题+1

**Comment by GuCangRan** [comment]
确实没问题了 是我电脑安装插件导致的异常行为 对不住大家了 我的错

**Comment by msidolphin** [comment]
> 确实没问题了 是我电脑安装插件导致的异常行为 对不住大家了 我的错

不至于，不至于
