### ISSUE TITLE
[Bug Report] 【el-cascader】 When multiple-selection search, when the result item is selected, the input selection search is empty

### ISSUE THREAD

**Issue by shangxinbo** [element-plus/element-plus#3710]
以上是我的问题 https://github.com/element-plus/element-plus/issues/3689

为什么关掉我的issue？我还没有说话就关掉我的问题，脑袋被门挤了？

是不是和element-ui 不是一个团队的？ 邀请你看下 element ui
https://codepen.io/shangxinbo/pen/qBjLyVw

你说的“保留关键字，能够高亮与之匹配的选项，这个体验会更好”

保留关键字跟高亮不高亮有什么关系，我没看到有高亮的效果啊

**Comment by shangxinbo** [comment]
@ xiaoxian521

**Comment by shangxinbo** [comment]
@xiaoxian521

**Comment by sxzz** [comment]
请注意你的言行，我们没有任何义务为你服务。

**Comment by shangxinbo** [comment]
> 我们没有任何义务为你服务

你没有义务服务，就不要关我的问题，有权利了就不想谈义务，整个世界就你有解释权
