### ISSUE TITLE
[Bug Report] Webpack 5 tree shaking loses component styles

### ISSUE THREAD

**Issue by WaqasIbrahim** [element-plus/element-plus#3712]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
Manjaro Linux 21.1.3

### Vue version
3.2.19

### Reproduction Link
https://github.com/WaqasIbrahim/element-plus-side-effects

### Steps to reproduce
Install dependencirs and run `npm run watch`

### What is Expected?
Component styles should be extracted to main.css file.

### What is actually happening?
Webpack ignores styles and they are excluded from the build. Adding `"es/components/*/style/index.js"` to `sideEffects` in element-plus `package.json` file solves it.

**Comment by JeremyWuuuuu** [comment]
@WaqasIbrahim Would you like to pull a request for fixing this?

IMHO, we should add both `es` and `cjs` since some people might stick with `cjs` for a while.

**Comment by HelloJunWei** [comment]
Hello @JeremyWuuuuu  @WaqasIbrahim ,

I make a PR to fix this issue.
Please have a look.

https://github.com/element-plus/element-plus/pull/3721

**Comment by JeremyWuuuuu** [comment]
Closing via #3721
