### ISSUE TITLE
[Bug Report] How to custom theme after using unplugin-vue-components?

### ISSUE THREAD

**Issue by ShaneLee-9** [element-plus/element-plus#3713]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
Google Chrome 94.0.4606.61

### Vue version
3.2.19

### Reproduction Link
https://github.com/ShaneLee-9/element-plus-custom-theme-demo

### Steps to reproduce
When I use "unplugin-vue-components" and refer to the documentation for the theming action, it does not work. I tried to use sass additionalData property to inject my scss code for each scss file, but unfortunately it didn't work. However, if I import "element-plus/theme-chalk/src/index.scss" into my scss code, it works, but it doesn't have the effect of loading styles on demand afterwards.

### What is Expected?
Components can tree shaking, styles can be loaded on demand and colors can be customized

### What is actually happening?
Components can be tree shaken, styles can be loaded on demand, but no custom colors

**Comment by JeremyWuuuuu** [comment]
cc @YunYouJun could you help here?

BTW, @YunYouJun is writing demo that could help people had the same question like you.

**Comment by YunYouJun** [comment]
Yeah, just wait a moment. An example will be ready soon.

**Comment by ShaneLee-9** [comment]
> Example of custom theme on demand is ready.
> 
> See `examples/vite` in [unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus/).
> 
> ![image](https://user-images.githubusercontent.com/25154432/135133165-907c3e3f-893a-4888-a433-a686782a7d16.png)

Thank you for your help, following your code, I have configured it successfully.
