### ISSUE TITLE
[Bug Report] pnpm docs:dev run error

### ISSUE THREAD

**Issue by Dreamcreative** [element-plus/element-plus#3715]
### Element Plus version
1.1.0-beta.17

### OS/Browsers version
mac 、chrome  94.0.4606.61

### Vue version
3.2.19

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
先将 normalize-wheel-es 依赖 替换为 normalize-wheel ，执行 pnpm docs:dev，生成 dist 目录后， 再将 normalize-wheel 依赖替换为 normalize-wheel-es ,这时候执行 docs:dev ，本地就会报 normalize-wheel 相关的错误，

### What is Expected?
如果项目有依赖更新，那么不管是否在依赖更新之前已经生成了 dist 目录，直接运行 pnpm docs:dev 命令 ，都应该能够成功启动项目

### What is actually happening?
例如我在 normalize-wheel 这个依赖下执行 pnpm docs:dev 生成了 dist 目录，如果这时候项目将 normalize-wheel 依赖，更新为了 normalize-wheel-es 依赖，我再去执行 pnpm docs:dev 项目运行不起来，因为 dist 文件还是拥有  normalize-wheel 依赖。只需要每次执行 pnpm docs:dev 命令时，将 dist 重新生成就能解决

**Comment by JeremyWuuuuu** [comment]
这确实是一个问题，为什么我们不直接在 docs:dev 的时候编译整个 Element Plus 呢，因为这样会导致我们每次启动的时间过长（当然 Vite 会提供相应程度的 cache）不过按理说这样是预期行为，本身来讲依赖也不会改变。倒是可以考虑一下能不能每次启动前 build 一次。:confused: cc @sxzz
