### ISSUE TITLE
[Bug Report] 1.1.0-beta.17-1.1.0-beta.18 version lacks web-types.json file

### ISSUE THREAD

**Issue by OneSeven** [element-plus/element-plus#3719]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
chrome 94

### Vue version
3.2.19

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
https://unpkg.com/browse/element-plus@1.1.0-beta.18/web-types.json

### What is Expected?
1.1.0-beta.17-1.1.0-beta.18 version lacks web-types.json file

### What is actually happening?
1.1.0-beta.17-1.1.0-beta.18 version lacks web-types.json file

**Comment by JeremyWuuuuu** [comment]
cc @sxzz Please have a look on this

**Comment by sxzz** [comment]
The problem confirmed. I will fix it.
