### ISSUE TITLE
[Feature Request] Support linking to other sites - not only routes in current site

### ISSUE THREAD

**Issue by jasonren0403** [element-plus/element-plus#3724]
### Existing Component
Yes

### Component Name
el-menu / el-menu-item

### Description
When using the items in el-menu, sometimes I want to click them to navigate to outer sites, not only stay in the current routes. The current route param seems to only support navigating between Vue routes.
Thank you!

**Comment by xiaoxian521** [comment]
Hey,this is a solution
https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/router/index.ts#L141

**Comment by jasonren0403** [comment]
> Hey,this is a solution https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/router/index.ts#L141

Inspired a lot, thanks!
