### ISSUE TITLE
[bug report] El menu if background color is set, the parent menu hover is invalid

### ISSUE THREAD

**Issue by ycc3000** [element-plus/element-plus#3734]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
Win11

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/ycc3000/pen/BaZMdRm

### Steps to reproduce
el-menu如果设置了background-color，那么会在html以内联的样式设置背景色，在外部就修改不了了，建议跟text-color类似的加上active-background-color属性
https://codepen.io/ycc3000/pen/BaZMdRm

### What is Expected?
父级菜单鼠标移上去颜色可变

### What is actually happening?
父级菜单鼠标移上去颜色无变化

**Comment by xiaoxian521** [comment]
hey, If you want to customize the colors, I suggest that all customizations may be better
such as: https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/style/sidebar.scss

**Comment by ycc3000** [comment]
我为了一个hover效果，还需要大动干戈去写五六百行css和一堆html+js吗，并且你想一下，应该是成对出现的属性缺少一个，是否应该是从组件本身去解决这个问题比较好呢？或者你别写在inline style里也行啊

**Comment by ycc3000** [comment]
烂
