### ISSUE TITLE
[bug report] cannot complete automatic import by referencing official documents

### ISSUE THREAD

**Issue by Cat7373** [element-plus/element-plus#3737]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
MacOS 12.0 Beta

### Vue version
3.2.19

### Reproduction Link
https://github.com/Cat7373/element-plus-demo

### Steps to reproduce
请参照复现链接

### What is Expected?
请参照复现链接

### What is actually happening?
请参照复现链接

**Comment by xiaoxian521** [comment]
@Cat7373 hey, You only need to use unplugin-element-plus

**Comment by xiaoxian521** [comment]
![image](https://user-images.githubusercontent.com/44761321/135276878-6c605b61-78b3-4c92-97bc-76e3a207fa1d.png)
![image](https://user-images.githubusercontent.com/44761321/135277042-38e6dbb2-2308-4c89-a261-66d4450f8f16.png)
![image](https://user-images.githubusercontent.com/44761321/135277099-8719a4f9-9a2c-42ab-a210-f0e43abb7946.png)

**Comment by Cat7373** [comment]
一直没使用 preview 是因为它默认用 5000 端口，和 MacOS 的 AirPlay 服务冲突，所以每次访问都是 403，刚刚关掉 AirPlay，现在 preview 可以用了

**Comment by Cat7373** [comment]
此问题于 `Element-Plus 1.1.0-beta.19` + `unplugin-vue-components 0.15.6` 已解决。

谢谢。

**Comment by sxzz** [comment]
Seems fixed in https://github.com/element-plus/element-plus/pull/3721
Thanks for your feedback!

**Comment by Cat7373** [comment]
> > 此问题于 `Element-Plus 1.1.0-beta.19` + `unplugin-vue-components 0.15.6` 已解决。
> > 使用对应版本依赖，启用修改点 6、8 即可。
> > 谢谢。
> 
> 启用这两个也会出问题~ ![image](https://user-images.githubusercontent.com/8894321/137058094-db303d35-c1ec-4951-a3a5-0956565f7ab7.png)

我没有对 menu 进行测试，只测试了 button，也许确实有问题，新起个 Issue 吧
