### ISSUE TITLE
[bug report] packaging error missing utils

### ISSUE THREAD

**Issue by uinio** [element-plus/element-plus#3738]
### Element Plus version
1.1.0-beta.18

### Vue version
3.2.19

### Steps to reproduce
![image](https://user-images.githubusercontent.com/49021590/135280151-d26bedde-130c-40a4-8d45-1e3acfb47595.png)
请检查package.json files 属性是否包含utils

**Comment by sxzz** [comment]
Run `pnpm i` please.

**Comment by uinio** [comment]
yarn cant be not work？

**Comment by sxzz** [comment]
Yes. We changed to `pnpm`.

**Comment by uinio** [comment]
documentation should have a hint

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus#bootstrap-project

**Comment by uinio** [comment]
pnpm same problem
![image](https://user-images.githubusercontent.com/49021590/135448781-6851a1bd-9b17-4534-8a88-e484b22a0e7d.png)

**Comment by sxzz** [comment]
Try to remove `node_modules` and `pnpm i` again.

**Comment by uinio** [comment]
relative path is correct
![image](https://user-images.githubusercontent.com/49021590/135450313-a1844543-7ef3-43b2-b974-00988e28d331.png)

**Comment by sxzz** [comment]
Please check if `node_modules/@element-plus` exist

**Comment by sxzz** [comment]
![image](https://user-images.githubusercontent.com/6481596/135450594-d371b7b3-4594-4845-9b19-d11f42c4c85c.png)
It works for me. /cc @msidolphin

**Comment by uinio** [comment]
still the same
![image](https://user-images.githubusercontent.com/49021590/135451681-44765f9f-f114-4e36-84d0-542eab2976e9.png)

**Comment by msidolphin** [comment]
> relative path is correct,fix path ![image](https://user-images.githubusercontent.com/49021590/135450313-a1844543-7ef3-43b2-b974-00988e28d331.png)

Please delete your node_modules folder and run pnpm i. If it still doesn't work, I suggest you restart your computer

**Comment by sxzz** [comment]
This is not an element-plus project, right?

**Comment by msidolphin** [comment]
> still the same ![image](https://user-images.githubusercontent.com/49021590/135451681-44765f9f-f114-4e36-84d0-542eab2976e9.png)

So it's your own project, but you put a screenshot of element-plus?

**Comment by uinio** [comment]
Vite packaging will check element-plus, it cannot be packaged

**Comment by sxzz** [comment]
Please provide a minimal reproduction link.

**Comment by uinio** [comment]
https://github.com/uinio/test

**Comment by sxzz** [comment]
@uinio Please add `"skipLibCheck": true` to `tsconfig.json`, and it works on my machine.
BTW, npm, yarn and pnpm is supported in your project. Before, I was referring to the element-plus project itself.
