### ISSUE TITLE
scroll bar component

### ISSUE THREAD

**Issue by zzfn** [element-plus/element-plus#374]
Whether to export the scroll bar component,provide documentation and rich function

**Comment by JeremyWuuuuu** [comment]
Could you please be more precise about what you need or what you want? I don't quite get what you tried to describe. You may describe it in Chinese, I can read.

**Comment by zzfn** [comment]
```js
<el-scrollbar>

</el-scrollbar>
```
这个组件是否是提供详细的文档和丰富一下组件功能

**Comment by JeremyWuuuuu** [comment]
> ```js
> <el-scrollbar>
> 
> </el-scrollbar>
> ```
> 
> 这个组件是否是提供详细的文档和丰富一下组件功能

For now `ScrollBar` is an internal only component that we did not have the plan to expose it to outside users, this API is used for constructing `select` and the other components. cc @zazzaz, I personally think this component is qualified to be exported to outside users though.
