### ISSUE TITLE
[bug report] custom theme SCSS compilation error

### ISSUE THREAD

**Issue by Mcler520** [element-plus/element-plus#3741]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
Chrome  94.0.4606.61

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
自定义主题 scss编译错误

### What is Expected?
自定义主题 scss编译正常

### What is actually happening?
文件配置   
package.json

"node-sass": "^4.14.1",
"sass": "^1.42.1",
"sass-loader": "^10.2.0"

main.js

import { createApp } from 'vue'
import App from './App.vue'

import './styles/var.scss'
import ElementPlus from 'element-plus'

createApp(App).use(ElementPlus).mount('#app')

styles/var.scss

@forward "element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    "primary": (
      "base": green,
    ),
  ),
);

@import "element-plus/theme-chalk/src/index.scss";

控制台运行结果
                     上午9:28:06
These relative modules were not found:

* ./fonts/element-icons.ttf in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/styles/var.scss
* ./fonts/element-icons.woff in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/styles/var.scss

**Comment by yazid2016** [comment]
同样的问题  不知道怎么解决，有解决了的么？？？

**Comment by daiwanxing** [comment]
我没有使用自定义主题，同样也报了这个错误
![image](https://user-images.githubusercontent.com/37327614/135375651-6f114610-5ebc-4680-a8a5-57941672c1f8.png)

**Comment by Mcler520** [comment]
> 同样的问题 不知道怎么解决，有解决了的么？？？

我在 vite 里面编译没问题，换到 vuecli 里面出现的

**Comment by yazid2016** [comment]
> > 同样的问题 不知道怎么解决，有解决了的么？？？
> 
> 我在 vite 里面编译没问题，换到 vuecli 里面出现的

那我在vite里试试，我还没用过vite打包

**Comment by xmzhy** [comment]
试试增加字体路径
styles/var.scss
@forward "element-plus/theme-chalk/src/common/var.scss" with (
// 自定义需要字体路径
$font-path: '~element-plus/dist/fonts';
);
@use "~element-plus/theme-chalk/src/index";

**Comment by yazid2016** [comment]
> 试试增加字体路径 styles/var.scss @forward "element-plus/theme-chalk/src/common/var.scss" with ( // 自定义需要字体路径 $font-path: '~element-plus/dist/fonts'; ); @use "~element-plus/theme-chalk/src/index";

此方法，已解决，感谢
