### ISSUE TITLE
官方有无计划制作暗黑主题？

### ISSUE THREAD

**Issue by jinmarcus** [element-plus/element-plus#3753]
### Element Plus version
1.1.0-beta.19

### OS/Browsers version
1

### Vue version
3.2.19

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
官方有无计划制作暗黑主题？

### What is Expected?
官方有无计划制作暗黑主题？

### What is actually happening?
官方有无计划制作暗黑主题？

**Comment by jinmarcus** [comment]
目前naiveui和antd都提供了暗黑主题
作为elementUI的老粉，真的很希望能提供一套暗黑主题
https://www.naiveui.com/zh-CN/dark/components/button
https://ant.design/components/overview-cn/?theme=dark

**Comment by YunYouJun** [comment]
Of course. Our designer is working on the color design. Once completed, the dark mode will follow up immediately.

**Comment by YunYouJun** [comment]
I create a discussion for it. Let's discuss here. https://github.com/element-plus/element-plus/discussions/3754
