### ISSUE TITLE
CSS代码优化 / CSS code optimization(refactor)

### ISSUE THREAD

**Issue by huangzhongzhong** [element-plus/element-plus#376]
当前element原生css代码中存在一些**没有应用**到的全局变量，设计逻辑**不一致**的变量结构等，计划后续进行**优化**一波，形成更丰富优雅的变量结构。

Translation:

Currently we have `global vars` that have **not being used** since V2, variable structure **did not match** design logic, planning on **optimizing** these long existed problems, to not only **enrich** the variable structure but also **make it more elegant**.

**Comment by JeremyWuuuuu** [comment]
Great, let's push this project to the world stage

**Comment by huangzhongzhong** [comment]
https://github.com/huangzhongzhong/element-wcag2.0 我做了一些修改工作，但没有完成全部，先放出来给大家看看~ 感觉更适合作为一个设计师用的版本存在？哈哈哈，更改了许多样式嵌套关系，开发可能会觉得不适应~

**Comment by huangzhongzhong** [comment]
发现我更改代码后会出现一些细节问题，关联起来还真是复杂哈哈哈，目前的版本在我公司的系统上是正常运行的，但是一些细节可能需要手动调整，以后有更完整的版本我会放出来的哈哈。

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
