### ISSUE TITLE
Custom theme, invalid override style

### ISSUE THREAD

**Issue by yudan215** [element-plus/element-plus#3760]
element-plus 版本 1.1.0-beta.19

使用按需加载

src/styles/element.scss
`@forward "element-plus/theme-chalk/src/common/var.scss" with (
  $font-path: '~element-plus/dist/fonts',
  $colors: (
    "primary": (
      "base": green,
    ),
  ),
);

@import "element-plus/theme-chalk/src/index.scss";`

main.js

`import { createApp } from 'vue';
import './styles/element.scss';
import { ElButton } from 'element-plus';
import App from './App.vue';

const app = createApp(App);
app.use(ElButton);
app.mount('#app');
`

在页面上使用<el-button type="primary">I am ElButton</el-button>

结果仍然是蓝色，并不会变成绿色，请问需要如何改变主题颜色？？

**Comment by SakuOtonashi** [comment]
```
@forward 'element-plus/theme-chalk/src/common/var' with (
  /* 改变主题色变量 */
  $colors: (
    primary: (
      base: green
    )
  ),
  /* 改变 icon 字体路径变量，必需 */
  $font-path: '/node_modules/element-plus/theme-chalk/src/fonts'
);

@import 'element-plus/theme-chalk/src/index';
```
使用的 Vite 没有问题呀，可以改变的。
There is no problem using vite the result is changed.

**Comment by barry1102** [comment]
![image](https://user-images.githubusercontent.com/27950905/137680481-8471c0db-bcf8-497a-ae43-d676331bb4a9.png)
这个怎么破？必须!default？

**Comment by TangTangJia** [comment]
> element-plus 版本 1.1.0-beta.19
> 
> 使用按需加载
> 
> src/styles/element.scss `@forward "element-plus/theme-chalk/src/common/var.scss" with ( $font-path: '~element-plus/dist/fonts', $colors: ( "primary": ( "base": green, ), ), );
> 
> @import "element-plus/theme-chalk/src/index.scss";`
> 
> main.js
> 
> `import { createApp } from 'vue'; import './styles/element.scss'; import { ElButton } from 'element-plus'; import App from './App.vue';
> 
> const app = createApp(App); app.use(ElButton); app.mount('#app'); `
> 
> 在页面上使用I am ElButton
> 
> 结果仍然是蓝色，并不会变成绿色，请问需要如何改变主题颜色？？

请问这个问题你解决了吗，我也和你遇到一样问题了

**Comment by SakuOtonashi** [comment]
> 
![屏幕截图 2021-11-29 214135](https://user-images.githubusercontent.com/69532233/143878374-aea4e827-2549-49ea-bf1b-936f86c0108f.png)
你对对和你的代码有什么区别，我这里是没有问题的。

**Comment by 1sm23** [comment]
我想改变 el-cascader 里的 checkbox 显示隐藏应该怎么写？
