### ISSUE TITLE
[Bug Report] Incorrect position of the first day of the week for Russian locale

### ISSUE THREAD

**Issue by DKholevinsky** [element-plus/element-plus#3769]
### Element Plus version
1.1.0-beta.19

### OS/Browsers version
Windows 10 / Google Chrome 93.0.4577.82

### Vue version
3.2.11

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-c5d2h

### Steps to reproduce
1. Open example https://codesandbox.io/s/element-plus-spa-forked-c5d2h
2. Open datepicker

First day of the week Sunday (Вс). Should be Monday (Пн)

### What is Expected?
The first day of the week must be Monday (Пн)

### What is actually happening?
First day of week Sunday (Вс)

**Comment by sxzz** [comment]
```ts
import { createApp } from "vue";
import ElementPlus from "element-plus";
import ru from "element-plus/es/locale/lang/ru";
import "element-plus/theme-chalk/index.css";

import dayjs from "dayjs";
import "dayjs/locale/ru";

import App from "./App.vue";

console.log(ElementPlus.version);

dayjs.locale("ru");

createApp(App)
  .use(ElementPlus, {
    locale: ru
  })
  .mount("#app");
```

**Comment by DKholevinsky** [comment]
Thanks. Please add to documentation
