### ISSUE TITLE
Element Plus LOGO 优化 / Element Plus LOGO optimization

### ISSUE THREAD

**Issue by huangzhongzhong** [element-plus/element-plus#377]
当前element plus的logo和原生风格不符，计划进行优化。

Translation: 
The current LOGO style does not match the previous one, planing to optimize it.

**Comment by JeremyWuuuuu** [comment]
Thanks for reaching out! CAN'T WAIT to see the optimized LOGO!

**Comment by huangzhongzhong** [comment]
[element plus-logo.svg.zip](https://github.com/element-plus/element-plus/files/5358941/element.plus-logo.svg.zip)
![element plus-logo](https://user-images.githubusercontent.com/46183365/95654731-94f19f80-0b34-11eb-969e-c4e9c52a6c76.png)

简单的将加号的风格与主体同步了一下，欢迎提出更多意见~

**Comment by JeremyWuuuuu** [comment]
Neat, we'll have this replaced later.
棒！我们后续会把首页替换成这个.

**Comment by zazzaz** [comment]
Looks great.

**Comment by zazzaz** [comment]
updated

**Comment by huangzhongzhong** [comment]
补上了移动端常用的小号版本~
[element plus-logo-small .zip](https://github.com/element-plus/element-plus/files/5610155/element.plus-logo-small.zip)
![image](https://user-images.githubusercontent.com/46183365/100495661-a6e0dd80-3188-11eb-98a4-f8685d48cb62.png)

**Comment by zazzaz** [comment]
Thanks

**Comment by huangzhongzhong** [comment]
![element plus-logo-small@4x](https://user-images.githubusercontent.com/46183365/101162004-b1114900-366c-11eb-9c94-c2f4317253fb.png)
![element plus-logo-small_1@4x](https://user-images.githubusercontent.com/46183365/101162014-b79fc080-366c-11eb-9470-f2645f86a0db.png)
[element plus-logo-small.zip](https://github.com/element-plus/element-plus/files/5642612/element.plus-logo-small.zip)
修复了之前无边框版本忘记设置背景的问题，增加了方形边框版本文件~

**Comment by zazzaz** [comment]
cool
