### ISSUE TITLE
[bug report] when using the auto import plug-in, the v-loading instruction cannot be used

### ISSUE THREAD

**Issue by Cat7373** [element-plus/element-plus#3776]
### Element Plus version
1.1.0-beta.19

### OS/Browsers version
MacOS 12.0 Beta

### Vue version
3.2.19

### Reproduction Link
https://github.com/Cat7373/element-plus-demo/tree/q2

### Steps to reproduce
请参照复现链接

### What is Expected?
请参照复现链接

### What is actually happening?
请参照复现链接

**Comment by daiwanxing** [comment]
目前有可行的解决办法, 只能单独导入VLoading组件和VLoading样式。
`
import VLoading from "element-plus/es/components/loading/index";
import "element-plus/es/components/loading/style/index;
app.use(VLoading)
`

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/issues/3570#issuecomment-925520009

**Comment by daiwanxing** [comment]
> [#3570 (comment)](https://github.com/element-plus/element-plus/issues/3570#issuecomment-925520009)

如果只能以服务的形式去调用组件，目前是否也只能手动import其样式呢?
例如 ElMessage、ElMessageBox

**Comment by sxzz** [comment]
目前的确是的，后续或许会有个更优的方案。

**Comment by daiwanxing** [comment]
好的，😀

**Comment by Cat7373** [comment]
@sxzz 如果说这是插件的限制，建议在官方文档中说明例外情况，不然每个参照文档进行按需导入的人会浪费大量时间去研究几个插件的细节、配置等，毕竟不知道是自己写的有问题还是配置有问题还是插件不支持，需要大量排错大量花时间才知道要怎么解决。

**Comment by sxzz** [comment]
各位愿意的可以提个PR

**Comment by sxzz** [comment]
Track this issue: https://github.com/antfu/unplugin-vue-components/issues/155
