### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by shaci** [element-plus/element-plus#379]
I get vue warnings and most of components not showed
![image](https://user-images.githubusercontent.com/1643065/94682510-b8933980-032d-11eb-8442-54ac95af2cbb.png)

My code:
![image](https://user-images.githubusercontent.com/1643065/94682597-da8cbc00-032d-11eb-9415-a117f59311f8.png)

Are these components not ready (or I do something wrong)?

**Comment by g3r4n** [comment]
el-select and el-option are not yet implement see #318.
same thing for el-table and el-table-column see #314.
