### ISSUE TITLE
[bug report] on demand import document is missing description, type

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#3832]
### Element Plus version
1.1.0-beta.19

### OS/Browsers version
mac 11

### Vue version
3.2.20

### Reproduction Link
https://github.com/Otto-J/vue3-element-plus-cypress

### Steps to reproduce
pnpm i && pnpm run dev
cd src/views/Home.vue  手动引入 ElMessage 来完成弹窗提示

### What is Expected?
正常渲染

### What is actually happening?
需要在 main.ts 里手动引入 message 样式文件，注释掉没有样式

**Comment by Otto-J** [comment]
请确认是否需要手动引入，如果是的话请补充文档说明。

**Comment by sxzz** [comment]
Duplicate of #3776
