### ISSUE TITLE
[feature request] a maximum pop-up quantity limit should be added to the message

### ISSUE THREAD

**Issue by webtianjia** [element-plus/element-plus#3836]
### Existing Component
是

### Component Name
Message 

### Description
在有些情况下,可能会出现很多个Message弹出框,直接铺满整个页面之类的
这样可能会显示不太友好,
建议新增可以设置超过一定数量,
应该把之前得提前已打开自动关闭掉.

**Comment by QQ34205037** [comment]
@zhazhantian 
这不应该由用户自己来实现，可以看看quasar的方式：
https://v1.quasar.dev/quasar-plugins/notify#grouping

**Comment by zhazhanitian** [comment]
Oh! I've learned what you expect. What you want is to take the prompt content as the only instance without distinguishing other attributes of the instance

**Comment by QQ34205037** [comment]
> Oh! I've learned what you expect. What you want is to take the prompt content as the only instance without distinguishing other attributes of the instance

我不确定此问题的提出者 @webtianjia 是否和我的期望一致，对于不同内容的提示，我同意你的说法：应该由开发者自己处理如何显示！

**Comment by zhazhanitian** [comment]
@sxzz 
I have a question. I have completed the function, but when I went to maintain the document, I found that only English, other languages do not need us to maintain?

**Comment by sxzz** [comment]
Yes. You can submit other languages here if you like. https://crowdin.com/project/element-plus
