### ISSUE TITLE
[bug report] in the production environment, when the page number of the El pagination component is greater than 7 pages, clicking the last 4 pages will report an error

### ISSUE THREAD

**Issue by pany-ang** [element-plus/element-plus#3841]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
windows/Chrome 94.0.4606.71

### Vue version
3.2.20

### Reproduction Link
https://github.com/v3-projects/v3-admin

### Steps to reproduce
1.<el-pagination
      layout="prev, pager, next"
      :total="total"
      :currentPage="currentPage"
      @current-change="currentChange"
    />
2.打包（vue: 3.2.20，vue-cli: 4.5.13）

### What is Expected?
正常显示页码

### What is actually happening?
点击最后4个页码时控制台报错：ReferenceError: Cannot access 'e' before initialization

**Comment by pany-ang** [comment]
开发环境：![1KP4K18AXQ_Z1MOY}0ZXKQU](https://user-images.githubusercontent.com/49087880/136763998-27a03a72-9b67-450d-9ca6-bde590bfce63.png
生产环境：![LF~6VYXDX5@9HJ6408}~XGX](https://user-images.githubusercontent.com/49087880/136764036-19469435-184c-4bc0-85bd-9c8a0115d645.png)
)

**Comment by ER-Tiylor** [comment]
hi，I had a similar problem，here is reproduction site：https://vite-base-project.vercel.app/
error message is ： Uncaught ReferenceError: Cannot access 'K' before initialization
The following is the environment information：
- "vue": "^3.2.0",
- "element-plus": "^1.2.0-beta.3",
- "vite": "^2.6.4",
thans！

**Comment by ER-Tiylor** [comment]
hi，I had a similar problem，here is reproduction site：https://vite-base-project.vercel.app/
error message is ： Uncaught ReferenceError: Cannot access 'K' before initialization
The following is the environment information：

"vue": "^3.2.0",
"element-plus": "^1.2.0-beta.3",
"vite": "^2.6.4",
thans！

**Comment by ER-Tiylor** [comment]
hi，I had a similar problem，here is reproduction site：https://vite-base-project.vercel.app/
error message is ： Uncaught ReferenceError: Cannot access 'K' before initialization
The following is the environment information：

"vue": "^3.2.0",
"element-plus": "^1.2.0-beta.3",
"vite": "^2.6.4",
thanks！

**Comment by pany-ang** [comment]
@vue/cli-service 4.5.x 依赖的 terser-webpack-plugin 版本太低 (1.4.4)，更新到 4.2.3 就可以了
