### ISSUE TITLE
[Bug Report] Table example not work

### ISSUE THREAD

**Issue by WingGao** [element-plus/element-plus#3842]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
Windows

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/wingao/pen/zYdYgpr

### Steps to reproduce
示例代码

### What is Expected?
正常

### What is actually happening?
列显示不全

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/136767485-b7b8a7de-7ff4-400f-9741-9565afbcf2e5.png)

I think this is codepen issue

**Comment by msidolphin** [comment]
> ![image](https://user-images.githubusercontent.com/1698794/136768074-512cd80d-0dab-4d2d-9bc4-35d7b9dbc9dd.png) My Chrome version 94.0.4606.71

I mean codepen parsing html has bugs, don't use self-closing
