### ISSUE TITLE
[Bug Report] [ElSelectV2] set value to an empty array after selection, an error will be displayed

### ISSUE THREAD

**Issue by End4You** [element-plus/element-plus#3866]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
macOS  Catalina10.15.7 (19H1323) / Chrome 94.0.4606.61

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/end4you/pen/ZEJGyZj

### Steps to reproduce
1. select a option
2. click reset button

### What is Expected?
display empty when setting empty array

### What is actually happening?
the display is not empty when setting an empty array

### Component
ElSelectV2

### Preview Image
![image](https://user-images.githubusercontent.com/28439270/137100308-024aa792-f932-4b8f-b107-99fd1ac1f5b5.png)

**Comment by btea** [comment]
`clearable` 属性应该是控制输入框右侧的清空按钮是否出现吧，感觉和题主额外通过别的按钮来清空选项要求不是很契合~

**Comment by Alanscut** [comment]
> `clearable` 属性应该是控制输入框右侧的清空按钮是否出现吧，感觉和题主额外通过别的按钮来清空选项要求不是很契合~

也是，不过功能上还是相似的。
