### ISSUE TITLE
[bug report] since it is a Chinese project, can Chinese be mentioned first? Why is it under little Japanese

### ISSUE THREAD

**Issue by qingmang** [element-plus/element-plus#3874]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
既然是中国人的项目能把中文提到前头吗 为啥在小日本文下面

### Vue version
3.2.20

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
既然是中国人的项目能把中文提到前头吗 为啥在小日本文下面

### What is Expected?
既然是中国人的项目能把中文提到前头吗 为啥在小日本文下面

### What is actually happening?
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

**Comment by qingmang** [comment]
![image](https://user-images.githubusercontent.com/67047984/137263471-5364d4f6-4bfb-4375-874d-b1c40aae003b.png)

**Comment by kooriookami** [comment]
Since it sorted by first letter. I dont think it. Nothing to do with the country.
