### ISSUE TITLE
[Bug Report] when request first menu-item route，It will render dynamically route menu； in  el-menu  :default-active="route.path"  ，also this route ` el-menu-item` not highlight show，。

### ISSUE THREAD

**Issue by kiss199203** [element-plus/element-plus#3883]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
google 

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVrasdf

### Steps to reproduce
采用 "vue": "^3.2.20"   "vite": "^2.6.7"
问题：当访问二级菜单路由地址 /user/list （用户管理》用户列表） 时，整个项目菜单会动态的渲染，但是此时用户列表菜单项不会被高亮显示，这个问题在  element-plus 的 1.1.0-beta.8 到 1.1.0-beta.20 版本存在动态回显高亮问题。
在 1.1.0-beta.7 之前版本不会存在此问题。就是采用了 vue-element-admin 那个脚手架渲染菜单的方式。
```
<el-menu
        :default-active="route.path"
        mode="vertical"
        router>
      <second-item v-for="item in currentRoute.children" :key="item.path" :item="item" :base-path="currentRoute.path" />
 </el-menu>

second-item.vue 组件：
<el-menu-item :index="resolvePath(item.path)" :class="{'submenu-title-noDropdown': !isNest}" >
          <item :icon="onlyOneChild.meta.icon||(item.meta&&item.meta.icon)" />
          <template #title>
            <span v-if="onlyOneChild.meta.title" slot="title">{{onlyOneChild.meta.title}}</span> 
          </template>
        </el-menu-item>

function resolvePath(routePath:string) {
        return (props.basePath + '/' + routePath).replace('//', '/') 
}
```

在 1.1.0-beta.7 之前版本浏览器请求一级菜单路由（不是点击了菜单项）可以高亮，下图效果（在 1.1.0-beta.8之后就就不行）：
![image](https://user-images.githubusercontent.com/21252218/137313379-4cb22c2f-08ad-442d-afb6-878edd3ae6bf.png)

### What is Expected?
采用 "vue": "^3.2.20"   "vite": "^2.6.7"
问题：当访问二级菜单路由地址 /user/list （用户管理》用户列表） 时，整个项目菜单会动态的渲染，但是此时用户列表菜单项不会被高亮显示，这个问题在  element-plus 的 1.1.0-beta.8 到 1.1.0-beta.20 版本存在动态回显高亮问题。
在 1.1.0-beta.7 之前版本不会存在此问题。就是采用了 vue-element-admin 那个脚手架渲染菜单的方式。

### What is actually happening?
采用 "vue": "^3.2.20"   "vite": "^2.6.7"
问题：当访问二级菜单路由地址 /user/list （用户管理》用户列表） 时，整个项目菜单会动态的渲染，但是此时用户列表菜单项不会被高亮显示，这个问题在  element-plus 的 1.1.0-beta.8 到 1.1.0-beta.20 版本存在动态回显高亮问题。
在 1.1.0-beta.7 之前版本不会存在此问题。就是采用了 vue-element-admin 那个脚手架渲染菜单的方式。

**Comment by normanfan** [comment]
同样的问题

**Comment by JnStyles** [comment]
me too
