### ISSUE TITLE
[Bug Report] Cannot find module 'vue-router' or its corresponding type declarations

### ISSUE THREAD

**Issue by xianyunyh** [element-plus/element-plus#3902]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
windows

### Vue version
3.2.20

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973?file=/src/App.vue:0-221

### Steps to reproduce
yarn run build

### What is Expected?
编译正常通过

### What is actually happening?
**项目中不使用vue-router**

编译遇到 `vue-router` 依赖错误和`global`错误

- **node_modules/element-plus/es/components/breadcrumb/index.d.ts:34:102 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.**

- **Cannot find name 'global'.**

**Comment by sxzz** [comment]
Please add `vue-router@next` as an devDependency

**Comment by sxzz** [comment]
We need add devDependency `vue-router` in `packages/element-plus/package.json`. PR welcomed.
