### ISSUE TITLE
[Feature Request] Navigation Sidebar usage

### ISSUE THREAD

**Issue by jannis6023** [element-plus/element-plus#3904]
### Existing Component
Yes

### Component Name
Navbar (Sidebar)

### Description
I am trying to implement the Navigation Sidebar for hours. HOW can I do it?

Feature request: PLEASE add some documentation about usage in productive use!

Can anyone help me?

**Comment by btea** [comment]
Maybe you can look here https://element-plus.org/en-US/component/menu.html

**Comment by jannis6023** [comment]
Ok, thanks! This helps me a lot, especially after I found the Layout Container.

But I have another Problem now:
The font's for Buttons are available, but all the other components like **the nav**, don't have the correct font(s)!

What Problem can this be?
I am using webpack-encore and Symfony. This is my App.vue content:
```
<template>
  <el-container>
    <el-header>
      <el-menu
          mode="horizontal"
      >
        ... here is my menu ...
      </el-menu>
    </el-header>

    <el-container>
      <el-aside>
        <el-menu>
          ... nav ...
        </el-menu>
      </el-aside>

      <el-main>
        <el-button>Hi</el-button>
        <p>This is some Test text.</p>
      </el-main>
    </el-container>

  </el-container>
</template>

<script>
export default {
  name: "App"
}
</script>

<style scoped>
</style>
```

And this is, what it finally looks like:
![Screenshot 2021-10-17 um 10 37 04](https://user-images.githubusercontent.com/40733092/137619009-bad4a1f4-e836-497d-a0ed-1991615521a1.png)

Do you know, what is missing?

**Comment by btea** [comment]
Emm, You mean the font you set doesn't work on other components, except the Button component？

**Comment by sxzz** [comment]
```
#app {
font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
  'Microsoft YaHei', '微软雅黑', Arial, sans-serif;
}

**Comment by jannis6023** [comment]
> ```css
> #app {
>   font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
>   'Microsoft YaHei', '微软雅黑', Arial, sans-serif;
> }
> ```

Thanks, works great - but it doesn't apply on e.g. the dropdown:

<img width="289" alt="Bildschirmfoto 2021-10-17 um 11 16 51" src="https://user-images.githubusercontent.com/40733092/137620629-9a166e79-39ca-48e1-97a5-bd87d24d5c95.png">

**Comment by jannis6023** [comment]
> ```css
> #app,html,body {
>   font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
>   'Microsoft YaHei', '微软雅黑', Arial, sans-serif;
> }
> ```

Doesn't change anything...

**Comment by jannis6023** [comment]
And in the examples, a button goes to its default color after click - it doesn't in my setup except if I click anywhere outside... is this cause of Element or my setup?

**Comment by sxzz** [comment]
Yes. Upload the most critical code (exclude irrelevant code) to the GitHub repository please.
