### ISSUE TITLE
Add  element-plus startup error

### ISSUE THREAD

**Issue by xiaohu95271** [element-plus/element-plus#3907]
**报错信息**
`> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                                                                                       下午5:52:23

 error  in ./node_modules/async-validator/dist-web/index.js

Module parse failed: Unexpected token (847:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class Schema {
|   // ========================= Static =========================
>   static register = function register(type, validator) {
|     if (typeof validator !== 'function') {
|       throw new Error('Cannot register a validator by type, validator is not a function');

 @ ./node_modules/element-plus/es/components/form/index.js 6:0-45 453:28-42
 @ ./node_modules/element-plus/es/component.js
 @ ./node_modules/element-plus/es/defaults.js
 @ ./node_modules/element-plus/es/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.6:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

`
**package.json**
`{
  "name": "admin-vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "element-plus": "^1.1.0-beta.20",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "vue-cli-plugin-element-plus": "0.0.13"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
`

**Comment by btea** [comment]
this is because https://github.com/yiminghe/async-validator/issues/295
