### ISSUE TITLE
[Bug Report] carousel with async data load very slowly

### ISSUE THREAD

**Issue by lijingfaatcumt** [element-plus/element-plus#3935]
### Element Plus version
1.1.0-beta.21

### OS/Browsers version
chrome

### Vue version
3.2.20

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-fw3r0?file=/src/App.vue

### Steps to reproduce
when data loaded, carousel load after 5 seconds

### What is Expected?
when data loaded, carousel load quickly

### What is actually happening?
when data loaded, carousel load slowly

**Comment by caio-2k** [comment]
> ```
>  v-if="items.length"
> ```
I'm facing the same problem but that's do the trick, ty mate!

**Comment by HeftyKoo** [comment]
fixed by #8904
