### ISSUE TITLE
[Bug Report] Date range editable prop not working

### ISSUE THREAD

**Issue by gabriellatavares** [element-plus/element-plus#3957]
### Element Plus version
1.1.0-beta.21

### OS/Browsers version
Mac OS / Chrome 

### Vue version
3.2.20

### Reproduction Link
https://jsfiddle.net/2q13x7ev/

### Steps to reproduce
When I put the prop editable to false, nothing works. I can sill edit my dates with my keyboard. 

### What is Expected?
To the input stop being editable. 

### What is actually happening?
Input stills editable.

**Comment by xiaoxian521** [comment]
Apologize for the problem that caused you, this problem has been fixed in the latest version

**Comment by gabriellatavares** [comment]
I'm getting this Vue Warn: Invalid prop: type check failed for prop "editable". Expected Boolean, got String with value "false", even though I'm passing the prop as `editable=false`

**Comment by gabriellatavares** [comment]
Ops, just realised that if I bind the :editable it works fine. Sorry about that and thanks a lot :)
