### ISSUE TITLE
[Bug Report]   Duplicate font folder with ttf found by npm

### ISSUE THREAD

**Issue by urchinstarz** [element-plus/element-plus#3961]
### Element Plus version
1.1.0-beta.21

### OS/Browsers version
win10/firefox

### Vue version
3.2.20

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
npm i element-plus --save
- input some El-plus html with any templte like this
```
<el-row>
      <el-button disabled>Default</el-button>
      <el-button type="primary" disabled>Primary</el-button>
      <el-button type="success" disabled>Success</el-button>
      <el-button type="info" disabled>Info</el-button>
      <el-button type="warning" disabled>Warning</el-button>
      <el-button type="danger" disabled>Danger</el-button>
    </el-row>
```
npm run xxx
。。。

【BUG】
there is two folder name fonts ...

### What is Expected?
- now i made it ok like this 
1. copy element-icons.ttf and element-icons.woff from 【.../node_modules\element-plus\dist\fonts/fonts/ 】to 【.../node_modules\element-plus\dist\fonts/】

### What is actually happening?
the console will notice like this:
Can't resolve './fonts/element-icons.ttf' ...

**Comment by xiaoxian521** [comment]
Apologize for the problem that caused you, this problem has been fixed in the latest version
