### ISSUE TITLE
[feature request] why doesn't the scrollbar of the table be implemented by scrollbar

### ISSUE THREAD

**Issue by WuYunlong** [element-plus/element-plus#3973]
### Existing Component
是

### Component Name
table

### Description
为了样式统一希望table的滚动使用 Scrollbar 实现

**Comment by sylfel** [comment]
It may be a good idea !!
UI Designer wanted to insert scrollbar between table header & table body. With custom scrollbar, it may be possible, isn't it ?

**Comment by HeftyKoo** [comment]
same as #2882
