### ISSUE TITLE
[Bug Report] Custom theme by Sass cause build error

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#3975]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
Any

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/none

### Steps to reproduce
https://element-plus.org/en-US/guide/theming.html#by-scss-variables

1. Create `index.scss` in /src/style with these content:
```scss
@forward "~element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    "primary": (
      "base": green,
    ),
  ),
);

@import "~element-plus/theme-chalk/src/index.scss";
```
2. Include in `App.vue`
3. `yarn run serve`

### What is Expected?
Build successfully.

### What is actually happening?
``` 
ERROR  Failed to compile with 2 errors         5:59:09 PM

These relative modules were not found:

* ./fonts/element-icons.ttf in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/style/index.scss
* ./fonts/element-icons.woff in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-3-3!./src/style/index.scss
```

**Comment by Komugisama** [comment]
same problem with you

**Comment by YunYouJun** [comment]
Hey, in 1.2.0-beta.1, we have removed the font icon and built-in svg icon for the component on demand.

So I think this problem has been solved.

You can refer to https://github.com/element-plus/element-plus-vite-starter.

I will close the issue, if there are still problems, feel free to reply here, thank you for your feedback.
