### ISSUE TITLE
[bug report] as soon as there is a large amount of table data, do you not solve it or provide solutions

### ISSUE THREAD

**Issue by flmbbb** [element-plus/element-plus#3982]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
chrome

### Vue version
3.2.20

### Reproduction Link
https://github.com/geabenitez/nuxt3-app

### Steps to reproduce
el-table 随便绑定个500条以上的数据，造成整个页面卡死。。。1000条以上卡成狗。2000条你别想动了;
 

### What is Expected?
grid加载数据虚拟的就不能解决下吗。。。
往右看看ant，往左看看vxtable哪个表格会现ELM 卡成这样

### What is actually happening?
el-table加载数据超过一定量就卡,受不了。。

**Comment by xiaoxian521** [comment]
嘿，虚拟列表正在开发中，完成后会解决此问题
