### ISSUE TITLE
[Feature Request] Can I wire form validation to the "submit" button?

### ISSUE THREAD

**Issue by superRainbow** [element-plus/element-plus#3983]
### Existing Component
Yes

### Component Name
el-form

### Description
The official website demo is to press the button then to do verification.
Currently, my project is to use watch form.value change to check formRef.validate.
But I think this is too efficient.
I hope the submit button can be disabled true or false according to the rules of the form.

**Comment by xiaoxian521** [comment]
It’s better to be controlled by the user. You can disable the button yourself according to the verification rules.

**Comment by xiaoxian521** [comment]
I think you used deep watch, you can delete onMounted

**Comment by xiaoxian521** [comment]
Please provide a warehouse such as github and I will help you change it

**Comment by xiaoxian521** [comment]
我认为这个必须使用watch，因为在组件中校验和这个button并不是关联的
