### ISSUE TITLE
[Bug Report] el-select component display 'false' which if v-model value is undefined/null

### ISSUE THREAD

**Issue by chwech** [element-plus/element-plus#4002]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
Google Chrome 94.0.4606.81（正式版本） （64 位）

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/chwech/pen/ExvNQmR

### Steps to reproduce
open reproduction link

### What is Expected?
input section display placeholder text

### What is actually happening?
input section display 'false'

**Comment by JeremyWuuuuu** [comment]
@chwech Somehow I wasn't able to reproduce this bug locally, cc @Alanscut can you reproduce it?

**Comment by Alanscut** [comment]
![select1103](https://user-images.githubusercontent.com/21104054/140018969-f261984a-aa42-42cb-8d16-e49f6480f620.png)

**Comment by Alanscut** [comment]
![select1103](https://user-images.githubusercontent.com/21104054/140021206-fbc32091-bee6-429a-907b-1af1cc279087.png)
