### ISSUE TITLE
why not use tsx?

### ISSUE THREAD

**Issue by MuRongXiaoDouBi** [element-plus/element-plus#401]
Now that the `h` function has been used，why not use the easier to read.

**Comment by JeremyWuuuuu** [comment]
2 reasons

1st. Before `jsx-next` launched this project has already been using `h` renderer for a while. 
2nd. You can see that we have applied `block` concept into this repo, so writing with jsx might not be the best solution for us considering performance.

Also we might need to add some comments for readability in the future.

**Comment by JeremyWuuuuu** [comment]
Hoping my answer could be helpful for you
