### ISSUE TITLE
Build fails when using Vue 3 on top of typescript

### ISSUE THREAD

**Issue by calebeaires** [element-plus/element-plus#403]
It is possible to run, but not to build the app.

@vue/cli 4.5.7
 element-plus 1.0.1-alpha.4

main.ts

```ts
import { createApp, Vue } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'

import ElementPlus from "element-plus";
import "element-plus/lib/theme-chalk/index.css";

createApp(App).use(ElementPlus).use(store).use(router).mount('#app')

```

Error message

```

 ERROR  Failed to compile with 1 errors                                                                                                                                                8:45:52 PM

 error  in src/main.ts:9:20

TS2345: Argument of type 'typeof import("/ta/node_modules/element-plus/types/element-ui")' is not assignable to parameter of type 'Plugin_2'.
  Type 'typeof import("/ta/node_modules/element-plus/types/element-ui")' is not assignable to type '{ install: PluginInstallFunction; }'.
    Types of property 'install' are incompatible.
      Type '(vue: typeof import("/ta/node_modules/vue/dist/vue"), options: InstallationOptions) => void' is not assignable to type 'PluginInstallFunction'.
        Types of parameters 'vue' and 'app' are incompatible.
          Type 'App<any>' is missing the following properties from type 'typeof import("/ta/node_modules/vue/dist/vue")': compile, useCssModule, useCssVars, createApp, and 104 more.
     7 | import "element-plus/lib/theme-chalk/index.css";
     8 | 
  >  9 | createApp(App).use(ElementPlus).use(store).use(router).mount('#app')
       |                    ^^^^^^^^^^^
    10 | 

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by fangting1989** [comment]
ElementUI

**Comment by fangting1989** [comment]
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import App from './play/index.vue'
import '../packages/theme-chalk/src/index.scss'
const app = createApp(App)
app.use(ElementPlus)
app.mount('#app')

**Comment by JeremyWuuuuu** [comment]
could you please provide a minimal reproducible version for us? Platform such as Codepen Codesandbox etc.

**Comment by takaximina** [comment]
I have got the same problem,when I  use  vue3+typescript;

**Comment by takaximina** [comment]
After reading the code, it should be during the export of ts. The use method of vue3 will detect whether the export is an object or method. If the export is an object, check whether the install method is included, that is, the code can run Yes, but the ts check will report an error!

**Comment by takaximina** [comment]
export const a='1'
export const b='2'
export default {a,b}

**Comment by cheqianxiao** [comment]
Here is a [reproduction link](https://codesandbox.io/s/vibrant-kowalevski-67e5z?file=/src/index.ts). 
it seems that the [types](https://github.com/element-plus/element-plus/tree/dev/types) haven't been update to compatible with vue3.  @JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Indeed, I’ll take a look at the exported types today, will keep you guys updated.

**Comment by JeremyWuuuuu** [comment]
I took a quick look at the install function exported by ElementPlus which type signature is 
`function install (vue: typeof Vue, options: InstallationOptions): void`

also Vue3 `PluginInstallFunction`'s signature is `declare type PluginInstallFunction = (app: App, ...options: any[]) => any;`
which obviously is not a match.

@cheqianxiao @takaximina  you guys interested in making a PR for this?

**Comment by takaximina** [comment]
ok,I hava down it ;

**Comment by cheqianxiao** [comment]
@JeremyWuuuuu  thanks, got it !  would have a try later.

**Comment by EphraimNetWorks** [comment]
Facing the same error with a typescript project here

**Comment by merrylmr** [comment]
Facing the same error with a typescript project here too;

my solution:

main.ts
```
// @ts-ignore
app.use(ElementPlus)
```
and eslintConfig's rules edit as 
```
"rules": {
      "@typescript-eslint/ban-ts-ignore": "off"
    }
```

**Comment by merrylmr** [comment]
@JeremyWuuuuu  I made a PR for this issue,  can you  review and merge it?
