### ISSUE TITLE
[Feature Request] Is it possible to diable the submenu opened/closed transition?

### ISSUE THREAD

**Issue by Cheerwhy** [element-plus/element-plus#4033]
### Existing Component
Yes

### Component Name
el-menu

### Description
I know that el-menu got "collapesed" to control the menu transition effect.
but how to control the submenu transition?

**Comment by msidolphin** [comment]
`showTimeout` & `hideTimeout` maybe can implememt your needs

**Comment by Cheerwhy** [comment]
> `showTimeout` & `hideTimeout` maybe can implememt your needs

But it only works in collapsed menu

**Comment by msidolphin** [comment]
> > `showTimeout` & `hideTimeout` maybe can implememt your needs
> 
> But it only works in collapsed menu

I suggest you using css to solve , this feature is not considered to implement

```css
.el-sub-menu .collapse-transition{
  transition: none!important;
}
```

**Comment by Cheerwhy** [comment]
> > > `showTimeout` & `hideTimeout` maybe can implememt your needs
> > 
> > 
> > But it only works in collapsed menu
> 
> I suggest you using css to solve , this feature is not considered to implement
> 
> ```css
> .el-sub-menu .collapse-transition{
>   transition: none!important;
> }
> ```

Nice! Thx
