### ISSUE TITLE
[bug report] invalid CSS v-bind in El dialog

### ISSUE THREAD

**Issue by wanderbaby** [element-plus/element-plus#4037]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
chrome 95

### Vue version
3.2.20

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-6v051?file=/src/dialog.vue:70-76

### Steps to reproduce
* 把弹框作为根节点组件
* 添加appent-to-body
* 在css中使用v-bind绑定setup中的变量无效

### What is Expected?
希望考虑一下这种情况要怎么实现

### What is actually happening?
在css中使用v-bind，vue把当前编译好的带hash值的变量通过style的方式关联到根节点的dom上，但是把dialog作为根节点时，el-dialog自定义了一段style样式

**Comment by zhengyangkang** [comment]
同样的问题，appent-to-body后无法使用变量注入scss(v-bind)，需要开放body的style参数或者支持该变量注入。
For the same problem, variable injection SCSS (v-bind) cannot be used after Appent to body. You need to open the style parameter of body or support this variable injection

**Comment by wanderbaby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YunYouJun** [comment]
A temporary solution: just use css var.

**Comment by wanderbaby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chenxch** [comment]
[vue issue](https://github.com/vuejs/core/issues/4605)

**Comment by wanderbaby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wanderbaby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
