### ISSUE TITLE
[Feature Request] Allow to choose any value in `el-time-picker` with `is-range`

### ISSUE THREAD

**Issue by wxs77577** [element-plus/element-plus#4046]
### Existing Component
Yes

### Component Name
el-time-picker

### Description
When I use `is-range` with `el-time-picker` I cannot select values like **20:00-08:00**, but I need to choose a night shift time range for our staff members. Is there any way to do this?

**Comment by wxs77577** [comment]
Thanks, but what I need is making **the end time less then the start time**

**Comment by wxs77577** [comment]
What I need is DO NOT disable any time range so that I can choose any time.
This is how `antdv` does.
![image](https://user-images.githubusercontent.com/1990059/139615300-0a10670f-0965-4f91-ae53-35588b738adb.png)

**Comment by msidolphin** [comment]
> Thanks, but what I need is making **the end time less then the start time**

This is not logical ah, I suggest using two time-picker to implement
