### ISSUE TITLE
[Bug Report] The position offset of fixed colunms  in table with fixed columns and header

### ISSUE THREAD

**Issue by yclgkd** [element-plus/element-plus#4047]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
chrome 95.0.4638.54

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/yclgkd/pen/KKvmBGX

### Steps to reproduce
This problem occurs when my column width is very wide, either fixing the left or the right. There's an example in the codepen that can reproducemy problem.

### What is Expected?
Fixed columns at the same height.

### What is actually happening?
The fixed column has been offset upwards

**Comment by Alanscut** [comment]
three ”日期" columns is fine,  four "日期" columns have problem

**Comment by Alanscut** [comment]
use element-plus 1.2.0-beta.1
set table's height = 300, fixed column height is wrong and offset to the left
![image](https://user-images.githubusercontent.com/21104054/139772299-2fda9c95-739f-46ca-9611-93ef198dbc37.png)
set table's height = 400, fixed column only has height error
![image](https://user-images.githubusercontent.com/21104054/139772346-395d5570-560e-4d86-843f-8d6772931fc0.png)

**Comment by yclgkd** [comment]
#4231
