### ISSUE TITLE
[Feature Request] DatePicker  lunar calendar

### ISSUE THREAD

**Issue by damengbuxing** [element-plus/element-plus#4056]
### Existing Component
Yes

### Component Name
DatePicker

### Description
element UI 3.0   Can it support the display of the lunar calendar

**Comment by msidolphin** [comment]
Now the content of cell can be customized

https://element-plus.org/en-US/component/date-picker.html#custom-content

**Comment by damengbuxing** [comment]
That's too much trouble！Lunar calendar information should not belong to the category of custom content
