### ISSUE TITLE
[bug report] when El cascader sets checkstrict and dynamic loading at the same time, clicking the selection for the first time will trigger the loading of sub items

### ISSUE THREAD

**Issue by webwuyou** [element-plus/element-plus#4092]
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/webwuyou/pen/MWvvZqX

### Steps to reproduce
el-cascader同时配置checkStrictly和lazy属性，当第一次点击选择框时，会触发动态加载子项，再点击一次才能选中，这样就会导致如果要选中某一项，就必须点击两次

### What is Expected?
修复这个必现问题

### What is actually happening?
如果要选中某一项，就必须点击两次

**Comment by webwuyou** [comment]
@SimonaliaChen  
![image](https://user-images.githubusercontent.com/15182683/139650011-04bf20bf-6eea-4ef1-95a9-ca87f8170081.png)

Looking at the source code, the Great God has done the processing here. When the child data is not loaded, it will load the data. I don't know why it is designed like this.

**Comment by webwuyou** [comment]
@SimonaliaChen  
![image](https://user-images.githubusercontent.com/15182683/139650011-04bf20bf-6eea-4ef1-95a9-ca87f8170081.png)

Looking at the source code, the Great God has done the processing here. When the child data is not loaded, it will load the data. I don't know why it is designed like this.

**Comment by msidolphin** [comment]
@webwuyou  This seems to be caused by your custom style, click on node-label does not execute doCheck
