### ISSUE TITLE
Suggestions about scrollbar

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#410]
Some components use native scrollbar, such as Textarea, Table, Transfer etc. It's unattractive, and can replace them with el-scrollbar.
![image](https://user-images.githubusercontent.com/38392315/95935238-5d6d4680-0e05-11eb-82d9-9c45546017c1.png)
The doc does not expose el-scrollbar, and hopefully it will be added to the doc. It's quite useful to users.

**Comment by JeremyWuuuuu** [comment]
Right, `El-ScrollBar` will be included in the first release, also we'll looking into those components see if we can get it integrated.
