### ISSUE TITLE
Does element-plus support template hints now?

### ISSUE THREAD

**Issue by fat4lix** [element-plus/element-plus#413]
Guys, thank a lot for yours work! 
I decided to test the alpha version a bit, and noticed that the IDE (phpStorm) does't see the components in the vue template

![image](https://user-images.githubusercontent.com/3585188/96027606-c9c96380-0e60-11eb-85d3-4ccf600594f5.png)

Is this currently not supported?

**Comment by JeremyWuuuuu** [comment]
Hi @fat4lix , my understanding on template hints is based on your editor/IDE plugins, from what I know VSCode has already supported it if you have `Vetur` plugin installed

**Comment by fat4lix** [comment]
Yes, you're right. I think it is problem with phpStorm, my bad.
