### ISSUE TITLE
[Bug Report] ElTree.emptyText is set to an empty string which is invalid

### ISSUE THREAD

**Issue by yangdan8** [element-plus/element-plus#4135]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome94

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/yangdan8/pen/yLozjzz

### Steps to reproduce
See interface output

### What is Expected?
Display as no data

### What is actually happening?
Show empty content

**Comment by imswk** [comment]
I will fix it
