### ISSUE TITLE
[bug report] when there are fixed elements in El table, more than two lines cannot be aligned

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#4141]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
win11

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/mxp131011/pen/dyzVjbR

### Steps to reproduce
使用 `el-table` 并在`el-table-column` 中添加 `fixed="left"` 且内容有换行或超过两行字符时
![image](https://user-images.githubusercontent.com/31055355/139620909-2989e1d3-0365-40a6-996c-c7a6c1fc9944.png)

### What is Expected?
每个`el-table-column`可以对其

### What is actually happening?
没有对齐

**Comment by zlj130137** [comment]
我也碰到了这个问题，设置了fixed，每行会错开，无法对齐
