### ISSUE TITLE
[Bug Report] space between chinese words not working when break line

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#4146]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/yukisora/pen/XWaexgw

### Steps to reproduce
```
<el-button type="text">
  中文
</el-button>
```

### What is Expected?
It should have space like normal.
BTW, why do we have this feature?

### What is actually happening?
no space between words.

**Comment by msidolphin** [comment]
@sxzz Maybe we should add a property to disable this feature?

**Comment by sxzz** [comment]
Yes. You're right.

**Comment by lnyie** [comment]
@sxzz This feature makes my previous style become confusing
