### ISSUE TITLE
[bug report] 1.2.0-bata cannot customize the theme

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#4148]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
macOS 11

### Vue version
3.2.14

### Reproduction Link
https://github.com/Otto-J/element-plus-bugs

### Steps to reproduce
1. 安装依赖
2. 观察 vite.config.js 和 main.ts
3. 运行 pnpm run dev

### What is Expected?
不报错

### What is actually happening?
一堆报错`Error: Module loop: this module is already being loaded.`

**Comment by msidolphin** [comment]
You don't need to import index.scss anymore
```diff
- @import "element-plus/theme-chalk/src/index.scss";
```

**Comment by Otto-J** [comment]
啥意思啊，我没这句代码，怎么改啊

**Comment by Otto-J** [comment]
哦，我明白了，是文档不对
