### ISSUE TITLE
[Bug Report] virtualized Select with filterable and remote options has warning

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#4149]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/yukisora/pen/LYjzXWj

### Steps to reproduce
This code is copied from virtualized selector remote search's codepen.

### What is Expected?
Show warning like "[Vue warn]: Invalid vnode type when creating vnode: ."

### What is actually happening?
no warning

**Comment by msidolphin** [comment]
cc @adaex like caused by icon
