### ISSUE TITLE
[Bug Report] El-Select cannot update label immediately based on the computed attribute

### ISSUE THREAD

**Issue by gadfly3173** [element-plus/element-plus#4153]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
(Windows NT 10.0; Win64; x64) Chrome/94.0.4606.81

### Vue version
3.2.19

### Reproduction Link
https://codepen.io/gadfly3173/pen/zYdEMaZ

### Steps to reproduce
https://codepen.io/gadfly3173/pen/zYdEMaZ

### What is Expected?
the label can be updated immediately or what should I do to force update it

====Chinese description to prevent ambiguity in English-用来防止英文表述不清的中文说明====

el-select的options使用computed属性动态渲染时，select组件的label不能即时响应选项的变化，我应该如何使它强制刷新？

### What is actually happening?
label show wrong

**Comment by msidolphin** [comment]
你的默认值不存啊

**Comment by gadfly3173** [comment]
了解了，是我的错误，问题应该是没有找到值的label时候会显示上一次的结果，codepen现在修改了

**Comment by msidolphin** [comment]
数据源改变了，你绑定值也应该改变的，或者说根本没必要用同一个select不是吗？

**Comment by gadfly3173** [comment]
场景其实是一个不同层级的节点进行创建的时候，选择这个节点在当前层级中的位置。不过这个其实还是我数据处理得有问题，感谢大佬解惑
