### ISSUE TITLE
[Bug Report] Invalid prop: type check failed for prop "cell". Expected Array, got Object

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#4164]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
window10/Chrome 93.0.4577.63

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/smallsample/pen/pordRJB

### Steps to reproduce
Import el-date-picker component

### What is Expected?
normal

### What is actually happening?
Vue warning

**Comment by SmallSample** [comment]
![image](https://user-images.githubusercontent.com/34450888/139772910-cbd85444-58c8-4671-a748-0c780f6d32f7.png)
![image](https://user-images.githubusercontent.com/34450888/139772929-189aa6e6-33c5-49ce-aaed-1bc94505ee3d.png)

**Comment by msidolphin** [comment]
already fixed
