### ISSUE TITLE
[Bug Report] Icons and related issues

### ISSUE THREAD

**Issue by vains-Sofia** [element-plus/element-plus#4168]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Windows NT 10.0; Win64; x64 / Chrome/95.0.4638.69

### Vue version
3.2.16

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
When I tried to use the icon, I found that there was an icon that would not be parsed, that is, the view icon. After I copied the code directly from the document to my own code, I checked the element in Google Chrome and found that it was still the view tag, but it was not converted to svg label, but when I capitalize the first letter (View), it will be parsed into svg label, and the icon is displayed normally. It is because of this problem that the icon cannot be displayed after the password input box is set: show-password="true".
So far, I only found this label. Other icons may also have this problem. Please solve it quickly.

### What is Expected?
You can use it directly by copying it from the document to your own code. The icon can be displayed normally after the password input box is set to show-password to true.

### What is actually happening?
&lt;el-input v-model="input" placeholder="Please input password" show-password /&gt;
This is the code of the document example, but the password icon will not be displayed in the document, and it is the same in my local.

**Comment by msidolphin** [comment]
@adaex cc

**Comment by adaex** [comment]
Because `view` is a tag in HTML, it is not rendered as an icon component. I have fixed the problem #4198
