### ISSUE TITLE
[Bug Report] Icon refactoring issue

### ISSUE THREAD

**Issue by msidolphin** [element-plus/element-plus#4170]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
mac

### Vue version
3.2.20

### Reproduction Link
https://codepen.io

### Steps to reproduce
I found a lot of warnings in the documentation after the icon refactor

@adaex 
The following components will print warnings:

* [ ] select
* [ ] button
* [ ] switch
* [ ] timeline
* [x] [table](https://github.com/element-plus/element-plus/pull/4167)
* [ ] tabs
* [ ] popconfirm

### What is Expected?
No warning

### What is actually happening?
Many warnings display on the console

**Comment by wenfangxin** [comment]
me too

**Comment by adaex** [comment]
Okay, I'll fix it as soon as possible.

**Comment by tolking** [comment]
and 
- [] ElBreadcrumbItem
- [] ElDropdownItem
...

**Comment by JeremyWuuuuu** [comment]
Thank you all for reporting the issue :pray:

**Comment by adaex** [comment]
Thank you all for reporting the issue 🙏 


@msidolphin  I tried to fix some of the components.  But I was unable to reproduce the warning message for the following components:

- [ ]  button
- [ ]  switch
- [ ]  timeline
- [ ]  tabs

@tolking I also couldn't find the warning message for components `breadcrumb` and `dropdown`.

Could you please check it again on this link? https://preview-4178-element-plus.surge.sh/ 

> Probably because of component dependencies, this will naturally not be a problem once the other components are fixed

**Comment by tolking** [comment]
@adaex [link](https://github.com/element-plus/element-plus/blob/dev/packages/components/breadcrumb/src/breadcrumb-item.vue#L10) Icon component used but never import

```diff
+ import { ElIcon } from '@element-plus/components/icon'
```

**Comment by adaex** [comment]
@tolking Solved the problem.

**Comment by msidolphin** [comment]
> Thank you all for reporting the issue 🙏
> 
> @msidolphin I tried to fix some of the components. But I was unable to reproduce the warning message for the following components:
> 
> * [ ]   button
> * [ ]   switch
> * [ ]   timeline
> * [ ]   tabs
> 
> ~@tolking I also couldn't find the warning message for components `breadcrumb` and `dropdown`.~
> 
> Could you please check it again on this link? https://preview-4178-element-plus.surge.sh/
> 
> > Probably because of component dependencies, this will naturally not be a problem once the other components are fixed

![image](https://user-images.githubusercontent.com/26672484/140012234-c72b8ba9-7f7a-4ab9-a331-7ec3b5b2fff2.png)

**Comment by msidolphin** [comment]
> > Thank you all for reporting the issue 🙏
> > @msidolphin I tried to fix some of the components. But I was unable to reproduce the warning message for the following components:
> > 
> > * [ ]    button
> > * [ ]    switch
> > * [ ]    timeline
> > * [ ]    tabs
> > 
> > ~@tolking I also couldn't find the warning message for components `breadcrumb` and `dropdown`.~
> > Could you please check it again on this link? https://preview-4178-element-plus.surge.sh/
> > > Probably because of component dependencies, this will naturally not be a problem once the other components are fixed
> 

You need to access the document in a dev environment

![image](https://user-images.githubusercontent.com/26672484/140012234-c72b8ba9-7f7a-4ab9-a331-7ec3b5b2fff2.png)

**Comment by ElsaOOo** [comment]
and el-pagination

**Comment by adaex** [comment]
@msidolphin  @ElsaOOo  All solved #4178

**Comment by damengshu** [comment]
1.2.0-beta.1  Why don't my ICONS show up
![1635999299(1)](https://user-images.githubusercontent.com/65537962/140257322-6d561f7e-2bd0-40e6-99a8-ef2ffc63cac6.png)

**Comment by adaex** [comment]
As of 1.2.0-beta1, `FontIcon` has been deprecated and you can use `SVG` components instead.

You can learn more from the following:

- #4060

**Comment by kiss199203** [comment]
<el-table-column fixed="right" align="center"  label="操作" width="200">
question: fixed has set value, this table-column Take up two lines and row don't roll together。

[错误](https://file.mengxuegu.com/group1/M00/00/09/drLt12GDs06AU5S_AAGKYQMts2w917.jpg)

**Comment by adaex** [comment]
> <el-table-column fixed="right" align="center"  label="操作" width="200">
> question: fixed has set value, this table-column Take up two lines and row don't roll together。

It seems that this is not caused by icon, can you open a new issue and provide a minimum reproducible link so that we can track this problem?

By the way, the table component does have some known problems, and we are refactoring the table component to provide a better table experience.

**Comment by msidolphin** [comment]
> @adaex
> 
> ```
> <el-table-column fixed="right" align="center"  label="操作" width="200">
> question: fixed has set value, this table-column Take up two lines and row don't roll together。
> ```
> 
> ![](https://camo.githubusercontent.com/0fd7caac07e804631ebf26fec1752b189884ae35b8a411467ef4190a32186a7e/68747470733a2f2f66696c652e6d656e6778756567752e636f6d2f67726f7570312f4d30302f30302f30392f64724c7431324744733036415535535f4141474b59514d747332773931372e6a7067)

This problem has been resolved #4141
