### ISSUE TITLE
[Bug Report] ElDatePickerCell: type check failed for prop "cell". Expected Array, got Object

### ISSUE THREAD

**Issue by VanishMax** [element-plus/element-plus#4176]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
MacOS Catalina

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/vanishmax/pen/yLoPpwP

### Steps to reproduce
1. Add any simple DatePicker
2. Check console

### What is Expected?
No warnings

### What is actually happening?
Hundreds of warnings saying that the prop of a child component is used incorrectly

**Comment by msidolphin** [comment]
already fixed #4134
