### ISSUE TITLE
Dropdown multilevel menu hope

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#418]
![image](https://user-images.githubusercontent.com/38392315/96090206-7277d180-0efa-11eb-8bcd-9ecba1ff4c44.png)
Can dropdown support multilevel menu like this. And hoping for a right-click menu effect like right click on the browser.

**Comment by g3r4n** [comment]
I think we can improve the Cascader with an options to choose between select and dropdown. see https://element.eleme.io/#/en-US/component/cascader.
For the context menu triggered with a right click you can achieve that with manual Popover -> https://element.eleme.io/#/en-US/component/popover
Note that we didn't implemented Cascader or Popover yet in Element Plus, we are working on it ;)

**Comment by zazzaz** [comment]
It's hard to tell it's an enhancement to Dropdown or Cascader.

**Comment by kooriookami** [comment]
> It's hard to tell it's an enhancement to Dropdown or Cascader.

Look at this, I wonder if can learn from this. http://v1.iviewui.com/components/dropdown
![image](https://user-images.githubusercontent.com/38392315/96358130-5a8c9180-1136-11eb-8bed-81082898842a.png)
