### ISSUE TITLE
[Feature Request] Trigger Input error messages

### ISSUE THREAD

**Issue by megasanjay** [element-plus/element-plus#4185]
### Existing Component
Yes

### Component Name
Input

### Description
Would it be possible to trigger an input or form-item's error state manually? I'm combining a bunch of inputs in a single form item and would like to see if its possible to trigger the error state for the whole form item.

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/140267174-697e9b6e-022b-414e-9426-e7922a0506ab.png)

Does `error` property satisfy your needs?

**Comment by xinboshang** [comment]
```
<form ref="formRef">
...
</form>
formRef.validate()
```

you can use validate() method to trigger error show

**Comment by megasanjay** [comment]
I think the `error` is just what I need. From my quick testing at least, it looks like even having a reactive variable in the error and setting it to anything other than `""` shows the error. I don't need to use validate to trigger the error on my end at least.

**Comment by megasanjay** [comment]
Update: using the `validate` is required it seems. I'm closing this one since it seems to be solved. Thanks for all the help y'all.
