### ISSUE TITLE
Proposal: giving up a "mitt"

### ISSUE THREAD

**Issue by fat4lix** [element-plus/element-plus#419]
I think "mitt" could be given up. At the moment it's used exclusively to change parent stage through events. This task can be accomplished by reactive provide/inject functionality which is well-described in documentation: https://v3.vuejs.org/guide/composition-api-provide-inject.html#mutating-reactive-properties

In our case take a form example. Right now Form provides mitt instance to make FormItem to be able to call 2 events on it: addField and removeField.

Instead of this we could provide 2 functions from Form (addField and removeField) which are to be called in FormItem to mutate parent state.

In that case we would give up needless dependency and would use vue functionality.

It would be looks like this.
In the form:

![image](https://user-images.githubusercontent.com/3585188/96117139-4bb59d00-0ef2-11eb-949b-ebe19a8d5594.png)
In the form-item
![image](https://user-images.githubusercontent.com/3585188/96117332-9a633700-0ef2-11eb-9942-af725e276fcc.png)
![image](https://user-images.githubusercontent.com/3585188/96117394-b535ab80-0ef2-11eb-8a6f-2adb3c04c91f.png)

If you agree with the idea, I could make a PR a little bit later.

**Comment by g3r4n** [comment]
I agree with the idea and I think we should also have a look to Select and other component that use mitt. It will be good to not have it as a dependency.

**Comment by JeremyWuuuuu** [comment]
Indeed, I have looked the PR @fat4lix made, we can do it with broadcasting issue fixed.

**Comment by mayuxian** [comment]
> I think "mitt" could be given up. At the moment it's used exclusively to change parent stage through events. This task can be accomplished by reactive provide/inject functionality which is well-described in documentation: https://v3.vuejs.org/guide/composition-api-provide-inject.html#mutating-reactive-properties
> 
> In our case take a form example. Right now Form provides mitt instance to make FormItem to be able to call 2 events on it: addField and removeField.
> 
> Instead of this we could provide 2 functions from Form (addField and removeField) which are to be called in FormItem to mutate parent state.
> 
> In that case we would give up needless dependency and would use vue functionality.
> 
> It would be looks like this.
> In the form:
> 
> ![image](https://user-images.githubusercontent.com/3585188/96117139-4bb59d00-0ef2-11eb-949b-ebe19a8d5594.png)
> In the form-item
> ![image](https://user-images.githubusercontent.com/3585188/96117332-9a633700-0ef2-11eb-9942-af725e276fcc.png)
> ![image](https://user-images.githubusercontent.com/3585188/96117394-b535ab80-0ef2-11eb-8a6f-2adb3c04c91f.png)
> 
> If you agree with the idea, I could make a PR a little bit later.

As you wish, MIT is no longer a strong dependency, but an optional library for event bus

**Comment by mayuxian** [comment]
As you wish, MIT is no longer a strong dependency, but an optional library for event bus

**Comment by mayuxian** [comment]
As you wish, "mitt" is no longer a strong dependency, but an optional library for event bus
