### ISSUE TITLE
[Bug Report] getCurrentInstance returns null after ElLoading.service

### ISSUE THREAD

**Issue by sxzz** [element-plus/element-plus#4194]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Chrome 95

### Vue version
3.2.21

### Reproduction Link
https://play.element-plus.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJztcbmltcG9ydCB7IEVsSW5wdXQsIEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuc2V0dXBFbGVtZW50UGx1cygpO1xuXG5jb25zb2xlLmxvZyhnZXRDdXJyZW50SW5zdGFuY2UoKSlcbkVsTG9hZGluZy5zZXJ2aWNlKClcbmNvbnNvbGUubG9nKGdldEN1cnJlbnRJbnN0YW5jZSgpKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=

### Steps to reproduce
Open reproduction link.
`getCurrentInstance` returns null after `ElLoading.service`

![image](https://user-images.githubusercontent.com/6481596/140231306-7153eb6f-8952-4c59-89bb-d66d4fe8eff7.png)

### What is Expected?
returns instance

### What is actually happening?
returns null

**Comment by undefined-degisn** [comment]
这或许是正常现象？因为ElLoading内部执行了一个render函数，这会把上一个的实例销毁？
可以看一下简单的实现 [repo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgZ2V0Q3VycmVudEluc3RhbmNlLCByZW5kZXIsIGNyZWF0ZVZOb2RlLCBoIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zb2xlLmxvZyhnZXRDdXJyZW50SW5zdGFuY2UoKSlcbnJlbmRlcihjcmVhdGVWTm9kZSh7XG4gIHJlbmRlciAoKSB7XG4gICAgcmV0dXJuIGgoJ2RpdicsIHt9LCAxMjMpXG4gIH1cbn0pLCBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdkaXYnKSlcbmNvbnNvbGUubG9nKGdldEN1cnJlbnRJbnN0YW5jZSgpKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDb21wLnZ1ZSI6IiJ9)

**Comment by sxzz** [comment]
我认为这比较反直觉，属于副作用。我们应该想办法避免。也是一个 breaking change
WDYT? /cc @JeremyWuuuuu

**Comment by undefined-degisn** [comment]
如果要更改，可以简单的更改，加一个异步函数去执行render就不会发生这样的事情了

**Comment by sxzz** [comment]
或者直接使用 `createApp` 是没问题的。

**Comment by undefined-degisn** [comment]
createApp貌似也不行，你能贴出你的代码吗？

**Comment by sxzz** [comment]
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgZ2V0Q3VycmVudEluc3RhbmNlLCBjcmVhdGVBcHAsIGNyZWF0ZVZOb2RlLCBoIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zb2xlLmxvZyhnZXRDdXJyZW50SW5zdGFuY2UoKSlcbmNyZWF0ZUFwcChjcmVhdGVWTm9kZSh7XG4gIHJlbmRlciAoKSB7XG4gICAgcmV0dXJuIGgoJ2RpdicsIHt9LCAxMjMpXG4gIH1cbn0pLCBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdkaXYnKSlcbmNvbnNvbGUubG9nKGdldEN1cnJlbnRJbnN0YW5jZSgpKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDb21wLnZ1ZSI6IiJ9
