### ISSUE TITLE
Type check failed for prop "cell" when using ElDatePicker 

### ISSUE THREAD

**Issue by feenn** [element-plus/element-plus#4196]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Windows 10 / Chrome 95

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/feenn/pen/wvqpQVN

### Steps to reproduce
Follow the codepen link above, open the Devtools panel and switch to Console tab. Then some vue warnings will be printed about "type check failed for prop 'cell'" etc.  The compoent is functional except the boring warning messages. This is the demo code on (https://element-plus.gitee.io/en-US/component/date-picker.html#date-range).

### What is Expected?
No warning message

### What is actually happening?
The Console prints a lot of vue warnings about type check failure for prop "cell" in ElDatePickerCell.

**Comment by msidolphin** [comment]
already fixed #4134
