### ISSUE TITLE
[bug report] when manually modifying the value of El input number, the view is not updated

### ISSUE THREAD

**Issue by Xyuan-abs** [element-plus/element-plus#4202]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome  95.0.4638.54

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/xyuan-abs/pen/eYEyoKW

### Steps to reproduce
1.在change事件中将modelvalue值固定为某个值(比如5)
2.在el-input-number 手动输入一个值，视图会更新（此时页面展示5）
3.第二次输入一个值，视图没有更新（此时页面展示输入的值）

### What is Expected?
在change事件中将modelvalue值固定为某个值后，无论输入值为多少，页面总是显示为固定的值。在自定义数值范围组件时，需要根据前值来限制后值的最小值，根据后值来限制前值的最大值，需要用到这个实现。

### What is actually happening?
在change事件中将modelvalue值固定为某个值后，第一次手动输入会更新视图，第二次及之后就不会更新

**Comment by msidolphin** [comment]
```js
this.$nextTick(() => {
    this.numberValue = 5
})
```
