### ISSUE TITLE
[bug report] the position of El input with icon is disordered

### ISSUE THREAD

**Issue by xuzhipeng0802** [element-plus/element-plus#4207]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
windows 

### Vue version
3.2.21

### Reproduction Link
https://codepen.io

### Steps to reproduce
el-input 带icon的组件前后位置没有设置height:100% line-height:100% 位置错乱 
地址：https://element-plus.org/zh-CN/component/input.html#%E5%B8%A6-icon-%E7%9A%84%E8%BE%93%E5%85%A5%E6%A1%86 

![image](https://user-images.githubusercontent.com/58281054/140286572-c5bad19b-4a84-4010-8a9a-0b281f4bf609.png)

### What is Expected?
希望他居中

### What is actually happening?
没有警告

**Comment by adaex** [comment]
This issue has been fixed and is awaiting the next release.

**Comment by sxzz** [comment]
fixed in #4238
