### ISSUE TITLE
[bug report] when uploading multiple files, the status is uploading, and only one is success

### ISSUE THREAD

**Issue by donghua990325** [element-plus/element-plus#4210]
### Element Plus version
1.1.0-beta.7

### OS/Browsers version
谷歌

### Vue version
3.2.6

### Reproduction Link
https://codesandbox.io

### Steps to reproduce
在多图上传的时候，按着shift键多个文件上传，filelist返回的status为uploading，只有一个为success
图片全部都是上传成功的
用change还不行

### What is Expected?
在多图上传的时候，在上传成功之后filelist 返回status为success

### What is actually happening?
on-success这个方法   filelist返回的status为uploading，只有一个为success

**Comment by sxzz** [comment]
Please reopen this issue after providing a minimum reproduction link.
