### ISSUE TITLE
[Bug Report] el-dropdown cannot be used with v-show

### ISSUE THREAD

**Issue by Eug620** [element-plus/element-plus#4211]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
mac os / chrome

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/confident-albattani-gowjz?file=/src/App.vue

### Steps to reproduce
Incoming v-show does not take effect

### What is Expected?
Can be used with v-show

### What is actually happening?
Hope it can be used with v-show

**Comment by undefined-degisn** [comment]
@sxzz 单元测试 似乎有问题, 本地跑单元测试每次结果都不太一样
