### ISSUE TITLE
vite build error

### ISSUE THREAD

**Issue by xnny** [element-plus/element-plus#4213]
Element Plus version
1.2.0-beta.1

OS/Browsers version
WIN 10 / Chrome Version 97.0.4690.4

Vue version
3.2.21

Reproduction Link
https://codepen.io/xnny-the-bold/pen/oNepQJw

Steps to reproduce
demo@1.0.0 build vue-tsc --noEmit && vite build node_modules/element-plus/lib/defaults.d.ts:3:57 - error TS2307: Cannot find module '../utils/config' or its corresponding type declarations. 3 install: (app: import("vue").App<any>, opts: import("../utils/config").InstallOptions) => void; ~~~~~

node_modules/element-plus/lib/index.d.ts:7:74 - error TS2307: Cannot find module '../utils/config' or its corresponding type declarations.

7 export declare const install: (app: import("vue").App<any>, opts: import("../utils/config").InstallOptions) => void; ~~~~~

Found 2 errors.

What is Expected?
Build Success

What is actually happening?
Build Error

**Comment by xnny** [comment]
Following the error message.  
I modified the index.d.ts and defaults.d.ts files in the node_modules\element-plus\lib directory.  
Add es to the reference path 

After the modification, I can build successfully  

![image](https://user-images.githubusercontent.com/872259/140305656-7da1b147-9585-4680-91e7-5cdc78708ce8.png)
![image](https://user-images.githubusercontent.com/872259/140305708-5a723d45-b441-4744-9f28-5dd6b55adfcd.png)

**Comment by sxzz** [comment]
I will handle this.

Todo List
- [ ] add `vue-router@next` as dev dep
- [ ] add `@types/node` as dev dep
- [ ] the errors you mentioned

**Comment by sxzz** [comment]
You can use `"skipLibCheck": true` for now.

**Comment by xnny** [comment]
Yes.
Add "skipLibCheck": true in tsconfig.json,
That solved my problem, thanks.

**Comment by sxzz** [comment]
Let this issue open to track. I will fix this errors.
