### ISSUE TITLE
[Bug Report] "el-date-picker" console warn

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#4215]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
macos

### Vue version
3.2.21

### Reproduction Link
https://github.com/Otto-J/element-plus-bugs/blob/main/cli-project/src/App.vue#L23

### Steps to reproduce
1. clone && install && run serve
2. 观察 console
3. 分别运行 vite 文件夹 和 cli 文件夹都有错误

### What is Expected?
没有错误

### What is actually happening?
错误一堆

**Comment by Otto-J** [comment]
https://codepen.io/Otto-J/pen/BadYoow

**Comment by msidolphin** [comment]
already fixed #4134
