### ISSUE TITLE
[Bug Report] el-sub-menu  Arrow dislocation

### ISSUE THREAD

**Issue by Csyyang** [element-plus/element-plus#4222]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome  95.0.4638.69

### Vue version
3.2.16

### Reproduction Link
https://github.com/Csyyang/bug.git

### Steps to reproduce
Import components on demand

Using l-sub-menu

### What is Expected?
The icon position is correct

### What is actually happening?
The icon position is moved below the text

**Comment by adaex** [comment]
fixed by #4230
