### ISSUE TITLE
[Bug Report]  Custom icons cannot be rendered correctly

### ISSUE THREAD

**Issue by daoSs** [element-plus/element-plus#4226]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome 94.0.4606.81

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/daoss/pen/KKvQQmm

### Steps to reproduce
<el-button :icon='MyIcon' />

const MyIcon = Vue.defineComponent({
        name: 'myicon',
        render() {
          return h('i', {
            class: 'icon_add',
          });
        },
      });

### What is Expected?
‘MyIcon‘ is not rendering properly.

### What is actually happening?
‘MyIcon‘ renders in the ‘el-button’ correctly

**Comment by undefined-degisn** [comment]
你应该是传错参数了, 你使用了`:icon="MyIcon"`, 这代表MyIcon是一个动态参数，但是你的实际意思是传入一个组件，所以应该去掉 冒号, 改为 `icon="MyIcon"`

**Comment by msidolphin** [comment]
The code of your demo is wrong, please refer:

```js
const MyIcon = Vue.defineComponent({
  name: 'myicon',
  render() {
    return Vue.h('i', {
      class: 'icon_add',
    });
  },
});
const App = {
  data() {
    return {
      MyIcon: Vue.markRaw(MyIcon),
      message: "Hello Element Plus",
    };
  },
  components: {
    MyIcon
  }
};
const app = Vue.createApp(App);
app.use(ElementPlus);
app.mount("#app");
```
