### ISSUE TITLE
[bug report] icon of elicon, in which the "view" icon is not displayed normally (only this icon is found at present)

### ISSUE THREAD

**Issue by fanyawei** [element-plus/element-plus#4232]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
MacOS/Google Chrome  95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-5g90i?file=/src/App.vue

### Steps to reproduce
1、引入　@element-plus/icons,版本:0.0.11
2、注册图标
3、在代码中使用“<el-icon> <view />  </el-icon>”　来显示view图标

### What is Expected?
图标正确显示

### What is actually happening?
其他图标显示正常，“view”图标显示不正常(目前只有这个)

**Comment by msidolphin** [comment]
You need to know that view is a legal html tag, and you need to give a different name instead of view

**Comment by ErrorJe** [comment]
> You need to know that view is a legal html tag, and you need to give a different name instead of view

有推荐的全量引入方式吗？我们在引入的时候可能是 `app.component(`Icon${component.name}`, component)` 类似增加自定义前缀的方式规避全局组件命名冲突问题~

**Comment by ErrorJe** [comment]
> You need to know that view is a legal html tag, and you need to give a different name instead of view

另外，希望可以在官方文档对应章节，补充下说明
