### ISSUE TITLE
[Bug Report] All of the components that look like el-select that the suffix icon has offset

### ISSUE THREAD

**Issue by JunyWuuuu91** [element-plus/element-plus#4233]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
ac

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr-2

### Steps to reproduce
The official website rendering out of the problem

https://element-plus.gitee.io/zh-CN/component/select.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

![image](https://user-images.githubusercontent.com/33750626/140472448-3bf13811-87f4-40f5-9f1a-7e02f8c8b3b2.png)

### What is Expected?
normal operation

### What is actually happening?
error operation

**Comment by sxzz** [comment]
fixed in #4238
