### ISSUE TITLE
[Feature Request] el-menu needs to support custom popper-plass

### ISSUE THREAD

**Issue by zmzimpl** [element-plus/element-plus#4234]
### Existing Component
是

### Component Name
el-menu

### Description
I know that the subMenu has this property, but sometimes the menu does not need subMenu. So I think popper-class was more suitable be placed in el-menu.

**Comment by msidolphin** [comment]
I'm very confused, why you're worried about popover when you don't have a subMenu

**Comment by zmzimpl** [comment]
> I'm very confused, why you're worried about popover when you don't have a subMenu

Because when menu is collapsed and the mouse is placed on the el-menu-item, there will be a popper.🤔
