### ISSUE TITLE
[Bug Report] ElTabs when editable is true the add icons is not displayed

### ISSUE THREAD

**Issue by msidolphin** [element-plus/element-plus#4237]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
chrome

### Vue version
3.2.21

### Reproduction Link
https://element-plus.org/en-US/component/tabs.html#add-close-tab

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26672484/140487820-2fb7451f-031e-44f9-b4e4-e666db791cb3.png)

### What is Expected?
displayed

### What is actually happening?
not displayed

**Comment by msidolphin** [comment]
@adaex cc

**Comment by adaex** [comment]
I'll fix it right away. 😅

**Comment by adaex** [comment]
This PR #4238 solves this problem.
