### ISSUE TITLE
[Bug Report] In the el-date-picker component, when we create custom content, a warning like "Invalid prop: type check failed for prop" cell "appears in the console. Expected Array, got Object"

### ISSUE THREAD

**Issue by MirasTekesbaev94** [element-plus/element-plus#4244]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Версия 95.0.4638.69 (Официальная сборка), (64 бит)

### Vue version
3.2.20

### Reproduction Link
https://codesandbox.io/s/vue-and-ably-forked-iver0?file=/src/main.js

### Steps to reproduce
I took just copied the example from this link "https://element-plus.org/en-US/component/date-picker.html#custom-content" and checked it out! There are a lot of warning messages for the cell property

### What is Expected?
Normal operation of the el-date-picker element without any errors! yo! Please add Object to prop validation!

### What is actually happening?
A lot of warnings appear, warning that "Invalid prop: type check failed for prop" cell ". Expected Array, got Object"

**Comment by btea** [comment]
duplicate #4196

**Comment by btea** [comment]
fixed #4134
