### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#425]
![image](https://user-images.githubusercontent.com/38392315/96219247-fd1f0600-0fb8-11eb-9da4-dd6d5e5ba658.png)
version 1.0.1-alpha.5

**Comment by zazzaz** [comment]
will fix soon

**Comment by zazzaz** [comment]
Fixed in 1.0.1-alpha.6

**Comment by kooriookami** [comment]
> Fixed in 1.0.1-alpha.6

OK, thank you~
