### ISSUE TITLE
[Bug Report] . on-demand Import   ElRadioGroup bug

### ISSUE THREAD

**Issue by hhhpw** [element-plus/element-plus#4251]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
mac/chrome 

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-7h0zr?file=/src/App.vue

### Steps to reproduce
down the newest version . on-demand Import   ElRadioGroup, ElRadioButton,

### What is Expected?
like Full Import 

### What is actually happening?
ElRadioGroup, ElRadioButton not work

**Comment by hhhpw** [comment]
- [ ] 
<img width="517" alt="72D4842F-34BB-4AB6-AB56-93149A7521D6" src="https://user-images.githubusercontent.com/23467537/140554431-ab0bc4c6-5ec6-4123-98e5-afa30e615e28.png">

when I try to on-demand import ElRadioGroup and ElRadioButton. the dom like this. obvious error

**Comment by hhhpw** [comment]
and if i use full import. it's ok.

**Comment by undefined-degisn** [comment]
嘿，单个组件注册不是用 `app.use()`，而是用`app.component()`
如果想要自动按需引入，可以参考 [按需导入](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)

**Comment by hhhpw** [comment]
> 嘿，单个组件注册不是用 `app.use()`，而是用`app.component()` 如果想要自动按需引入，可以参考 [按需导入](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)

感谢回复。但你理解的不对。可以看下我的连接。d

**Comment by hhhpw** [comment]
element-plus: 1.2.0-beta.2

**Comment by msidolphin** [comment]
你直接引入radio就行了
