### ISSUE TITLE
[button report] button component type = "primary" color is not controlled by CSS variable

### ISSUE THREAD

**Issue by satrong** [element-plus/element-plus#4263]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
windows10 / Chrome 95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/satrong/pen/jOLzqKm

### Steps to reproduce
鼠标经过 和 点击 按钮

### What is Expected?
1. 上面两个没有使用设置的 --el-color-primary 的颜色 （这个不算bug）
2. 下面两个按钮点击时应为绿色

### What is actually happening?
1. 上面两个按钮：不受 --el-color-primary 控制，需要在 .el-button--primary 里面控制样式变量
2. 下面两个按钮仍然为蓝色（默认颜色）

**Comment by satrong** [comment]
希望 Button 的颜色可以通过 --el-color-primary 控制，而不需要单独去针对按钮设置变量。
这个是我做的修改，但感觉还不够好，仅供参考
https://github.com/satrong/element-plus/commit/047002a0c5d6bb64c4591d945dfa4972a51ed263

**Comment by msidolphin** [comment]
单独设置是为了更好灵活度，这点我认为不需要修改

**Comment by msidolphin** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Yeah, I think this pr me has solved the problem and is just waiting for review.

https://github.com/element-plus/element-plus/pull/3664

**Comment by satrong** [comment]
@YunYouJun 是否可以考虑下：将 primary 类型的 button 的颜色使用 --el-color-primary 颜色变量控制？这样对于更换主题色而言，只需要关心 --el-color-primary 这个 css 变量，而无需单独针对 primary 按钮进行颜色设置。

**Comment by YunYouJun** [comment]
> 

Of course. I think we have achieved it.

**Comment by satrong** [comment]
@YunYouJun 感谢你的回复。

可能你没理解我的意思。 primary 按钮的颜色确实是与 --el-color-primary 的颜色一致，但是这仅仅是在 sass 层面。

```html
<button class="el-button el-button--primary" type="button" 
  style="--el-button-bg-color:#409eff; --el-button-border-color:#409eff; --el-button-hover-bg-color:rgb(102, 177, 255); --el-button-hover-border-color:rgb(102, 177, 255); --el-button-active-bg-color:rgb(58, 142, 230); --el-button-active-border-color:rgb(58, 142, 230);">
  <!--v-if-->
  <span class="">primary</span>
</button>
```

最后生成的html代码中，按钮的背景色其实是受 `--el-button-bg-color` 这个css变量控制的，这个时候与 `--el-color-primary` 这个css变量没有直接的关联了。

所以我的意思是 primary 按钮的颜色是否可以下面这些变量控制
```
--el-color-primary
--el-color-primary-light-1
--el-color-primary-light-2
--el-color-primary-light-3
...
```
