### ISSUE TITLE
About form component with display: inline-block

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#427]
This the original form items with small size.
![image](https://user-images.githubusercontent.com/38392315/96226366-16c64a80-0fc5-11eb-9cbb-dd63f0fee9a7.png)
They all have different offset. The expected height is 32px.
![image](https://user-images.githubusercontent.com/38392315/96227371-9c96c580-0fc6-11eb-98c9-f14fe79bc5a0.png)
![image](https://user-images.githubusercontent.com/38392315/96226250-f72f2200-0fc4-11eb-97cf-df782ad76b5a.png)
![image](https://user-images.githubusercontent.com/38392315/96226276-00b88a00-0fc5-11eb-8b4a-0110b74b52c3.png)
![image](https://user-images.githubusercontent.com/38392315/96226320-09a95b80-0fc5-11eb-9561-abeb2a272328.png)
Some components have no vertical-align attribute, some have vertical-align: middle. But in fact, only vertical-align: top works!
I think all the component with display: inline-block should add vertical-align: top. This is my personal opinion. Or you have better ideas.
![image](https://user-images.githubusercontent.com/38392315/96226921-e7640d80-0fc5-11eb-9d23-77d401cefd6b.png)

**Comment by kooriookami** [comment]
Since vue3 does not support below ie11, we can replace float, inline-block, vertical-align so on with display: flex.

**Comment by JeremyWuuuuu** [comment]
@kooriookami what about people using polyfills? This change might break their code. But I think the idea is correct, we might just say we are no longer support IE11.

**Comment by kooriookami** [comment]
> @kooriookami what about people using polyfills? This change might break their code. But I think the idea is correct, we might just say we are no longer support IE11.

What I described was one way. The finally goal is to ensure that the style is accurate. Especially the `color-picker`, there is a large blank in the form.
