### ISSUE TITLE
[Feature Request] Request for Filter box below the table header

### ISSUE THREAD

**Issue by ITKHMER** [element-plus/element-plus#4272]
### Existing Component
Yes

### Component Name
Table

### Description
Hi,
1-Can you please add filter box below the table header? Please find the sample below:
https://raw.githubusercontent.com/rubanraj54/vue-bootstrap4-table/develop/src/assets/img/demo.gif
2-Please make it support multi-field filter

Thank you!

**Comment by chenxch** [comment]
You can try it.
[docs](https://element-plus.org/en-US/component/table.html#table-with-custom-header)
