### ISSUE TITLE
[Bug Report] component input-number show warning Invalid prop: type check failed for prop 'modelValue'. Expected Number with value NaN, got Undefined

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#4279]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
chrome

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/yukisora/pen/JjyvPOv

### Steps to reproduce
input-number should have a default value, but the props in `input-number.ts` file didn't set.
```
  modelValue: {
    type: Number,
    required: true,
  },
```

### What is Expected?
has a default value.

### What is actually happening?
type check failed warning.

**Comment by sxzz** [comment]
modelValue is `required`. So you have to pass a value to it.

**Comment by lemoe2021** [comment]
But, the document said it has default value 0 and type is number / undefined.

**Comment by sxzz** [comment]
Yeah. So we should update documentation.
