### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by OS-the-Person** [element-plus/element-plus#428]
It would be nice to have more icons added to the already available ones

Notable icons include:
- Record (circle)
- Stop (Square)
- Social (Multi user)
- and other simple/common icons 
and a solid version for every outline icon and vice-versa.

Could we also get the Github repo of the icon designer so we could support him/her to do more if that is the case?

**Comment by zazzaz** [comment]
A github repo with icon source files is a cool idea.

**Comment by JeremyWuuuuu** [comment]
Currently we don't have any resources from designer which adding icons to this repo might cause inconsistency icon style to other icons(personal opinion)

**Comment by JeremyWuuuuu** [comment]
Track this in https://github.com/element-plus/element-plus-icons, we are making progress.
