### ISSUE TITLE
[Feature Request] [el-select] It warns when el-option value="null",Is it reasonable?Sometimes null is a meaningful value

### ISSUE THREAD

**Issue by zhangshichun** [element-plus/element-plus#4280]
### Existing Component
Yes

### Component Name
ElSelect

### Description
when <el-option :value="null" ...></el-option>;  
It maybe should not warning;  
(当我使用null作为某个option的值得时候,也许并不用进行报错;对于某些业务而言,可能存在[全部]选项,而不是使用clearable,每当这种是否对于null的报错都让人感到费解)

**Comment by msidolphin** [comment]
Maybe you should use the empty string

**Comment by zhangshichun** [comment]
> Maybe you should use the empty string

ok;  
it is a way;  
thank u
