### ISSUE TITLE
[Bug Report] Checkbox tabindex property doesn't work

### ISSUE THREAD

**Issue by BurNing1993** [element-plus/element-plus#4284]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
Win11  Edge/95.0.1020.40

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/burning1993/pen/PoKePgK?editors=1000

### Steps to reproduce
1.el-checkbox add  property  tabindex ="-1"

2.press keyboard tab key

### What is Expected?
el-checkbox set property  tabindex ="-1" ,press tab key should not focus it.
[tabindex mdn](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/tabindex)

### What is actually happening?
el-checkbox set property  tabindex ="-1" ,press tab key  focus it.

**Comment by sxzz** [comment]
Fixed in #4286
