### ISSUE TITLE
[Bug Report] el-input-number show echo '0' when the value is null 

### ISSUE THREAD

**Issue by JunyWuuuu91** [element-plus/element-plus#4290]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
mac

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/ErrorJE/pen/JjypmWa

### Steps to reproduce
- bind a varaiable to el-input-number
- set the varaiable of `null \ undefine \ NaN` 
- render the component，echo '0' result only when i set the value `null` to the varaiable

### What is Expected?
i think those value  `null` 、`undefined`、`NaN` all of a empty value，so the el-input-number should give me a empty show but not 0

### What is actually happening?
above

**Comment by msidolphin** [comment]
null is not a valid input

**Comment by JunyWuuuu91** [comment]
> null is not a valid input

How do you know that the input value set from background interface?
