### ISSUE TITLE
[Feature Request] TypeScript Cannot find module './affix' or its corresponding type declarations. Cannot find module './slider' or its corresponding type declarations. Cannot find module 'element-plus/es/components/config-provider/config-provider' or its corresponding type declarations. Cannot find module '../utils/config' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ClownLee** [element-plus/element-plus#4291]
### Existing Component
No

### Component Name
affix slider

### Description
Cannot find module './affix' or its corresponding type declarations. Cannot find module './slider' or its corresponding type declarations. Cannot find module 'element-plus/es/components/config-provider/config-provider' or its corresponding type declarations. Cannot find module '../utils/config' or its corresponding type declarations.

**Comment by djrenko96** [comment]
I have same problem

package.json:
`{ 
  "name": "client",
  "version": "0.0.0",
  "scripts": {
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "element-plus": "^1.2.0-beta.2",
    "eslint": "^8.2.0",
    "unplugin-vue-components": "^0.17.2",
    "vue": "^3.2.16",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.25.0",
    "@typescript-eslint/parser": "^4.25.0",
    "@vue/compiler-sfc": "^3.0.5",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^8.2.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-vue": "^7.10.0",
    "prettier": "^2.3.0",
    "@vitejs/plugin-vue": "^1.9.3",
    "typescript": "^4.4.3",
    "vite": "^2.6.4",
    "vue-tsc": "^0.3.0"
  }
}
`

When i start `npm run build` :
![image](https://user-images.githubusercontent.com/26996236/140879889-e6f43ae0-0d7a-4f1e-9162-dbd84459ffbd.png)

**Comment by zjjaxx** [comment]
me too.....

**Comment by sxzz** [comment]
Dulicate of #4313

**Comment by sxzz** [comment]
Please refer to https://github.com/element-plus/element-plus/issues/4213#issuecomment-960804309
