### ISSUE TITLE
[Bug Report] Hover index of el-select jumps to first option after mouse hovering

### ISSUE THREAD

**Issue by MyNameIsNico** [element-plus/element-plus#4293]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Windows 10 / Chrome 95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://jsfiddle.net/JustAnotherSimpleFiddler/3z9uxeq1/2/

### Steps to reproduce
1. Click on el-select to open all options
2. Set the hover index to 'Option2' by pressing arrow down key 2 times
3. Hover on 'Option4' via mouse cursor
4. Press arrow down key one time
=> Hover index has moved to 'Option1'

### What is Expected?
The hover index should jump to the next/previous option without being influenced by the mouse cursor. If the current hover index is on 'Option2' and the cursor  hover over 'Option4', then the next hover index after pressing arrow down should be on 'Option3' and not on 'Option1'.

### What is actually happening?
The hover index always jumps to the first option after mouse hovering, regardless of the current hover index.

**Comment by Alanscut** [comment]
Perhaps the next hover index after pressing the arrow is more appropriate on "Option5"? Like element.
