### ISSUE TITLE
[Bug Report] Hover index of el-select is still there after clearing input

### ISSUE THREAD

**Issue by MyNameIsNico** [element-plus/element-plus#4294]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Windows 10 / Chrome 95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGNsZWFyYWJsZSBtdWx0aXBsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

### Steps to reproduce
1. Click on el-select to open all options
2. Select 'Option3', 'Option4' and 'Option5' by clicking on these 3 options
3. Click outside of el-select to close all options
4. Clear all selected options by clicking on the little cross in the input suffix
5. Click on el-select again to open all options
=> Hover index effect (gray background color) is on 'Option3'

### What is Expected?
After clearing all selected options the hover index effect (gray background color) should be not visible.

### What is actually happening?
The hover index effect is still visible after clearing all selected options and is set to an option I pressed some clicks ago.

**Comment by chenxch** [comment]
Hello, your demo seems to have expired.

**Comment by MyNameIsNico** [comment]
@chenxch I updated the reproduction link, sorry for the expired link.

**Comment by MyNameIsNico** [comment]
@chenxch I updated the reproduction link, sorry for the expired link.

**Comment by chenxch** [comment]
It will be investigated in the near future.
