### ISSUE TITLE
[feature request] the inline prompt in the switch API document is not implemented

### ISSUE THREAD

**Issue by Cxtsl** [element-plus/element-plus#4297]
### Existing Component
Yes

### Component Name
Switch

### Description
1.Switch开关组件文档中属性inline-prompt未实现。
2.“文字描述”中的例子在属性inline-prompt的使用上也与文档矛盾

**Comment by Cxtsl** [comment]
更新到最新版本，Switch开关组件文档中属性inline-prompt可以实现，但是文字描述仅限于一个字符。也就是说active-text和inactive-text设置为一个字符以上，如“属性”只会将第一个字符“属”显示出来。

**Comment by msidolphin** [comment]
inline mode only supports one character, we will adjust the document
