### ISSUE TITLE
[Bug Report] form validate callback can not work

### ISSUE THREAD

**Issue by ElsaOOo** [element-plus/element-plus#4299]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
macOS/chrome 95

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-7g3h8?file=/src/App.vue:9442-9447

### Steps to reproduce
https://codesandbox.io/s/element-plus-spa-forked-7g3h8?file=/src/App.vue:9442-9447

### What is Expected?
表单必填项填完后，form.validate回调函数可以正确执行

### What is actually happening?
表单必填项填完后，form.validate回调函数没有正确执行

**Comment by msidolphin** [comment]
Your validation method does not call callback
```diff
const dictionaryCodeRules = {
  message: "请输入字典编码",
  trigger: "blur",
  validator: (rule, value, callback) => {
    if (!formData.isDictionary) {
+     callback()
      return;
    }
    if (value === "") {
      callback(new Error("请输入字典编码"));
    } else {
      callback();
    }
  },
};
```

**Comment by dingguoqing513** [comment]
我就想问问官网放个2.x的写法是tm什么意思

**Comment by dingguoqing513** [comment]
> 我就想问问官网放个2.x的写法是什么意思！！！！！！

不能用的放上去忽悠鬼呢！明明可以解决却不解决，考验各位coder的编程能力呢！！！！！

**Comment by shalouzaixiayu** [comment]
plus 上面的 callback 不会生效， 错误提示没有显示

The Element plus for form callback not  error message
