### ISSUE TITLE
[Feature Request] Add `@extend %shared-border-pseudo !optional` to avoid sass parse error

### ISSUE THREAD

**Issue by whaliendev** [element-plus/element-plus#4303]
### Existing Component
Yes

### Component Name
el-table

### Description
After I upgrade my element-plus from `1.1.0-beta.16` to ` 1.2.0-beta.2`, the new error is reported. 
Below is the log of HMR:
```text
 ERROR  Failed to compile with 1 error                                                                                                                                                                                          12:18:19 AM

 error  in ./src/styles/app.scss

Syntax Error: SassError: The target selector was not found.
Use "@extend %shared-border-pseudo !optional" to avoid this error.
    ╷
174 │   @extend #{'%shared-'   $name};
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/element-plus/theme-chalk/src/mixins/mixins.scss 174:3  root stylesheet


 @ ./src/styles/app.scss 4:14-223 15:3-20:5 16:22-231
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.133.174.22:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

I'm not sure if it's a actually a bug of the latest element-plus, so I cannot provide a minimal reproduction link. But if I roll back element-plus to `1.1.0-beta.16`, the error will disappear. By the way,  `@include extend-rule(border-pseudo)` is only used in `element-plus/theme-chalk/src/table.scss`.

**Comment by whaliendev** [comment]
If reproduction link is a must, I'll provide one ASAP.

**Comment by BoringDays** [comment]
this happens in my project too, any way to solve this?
