### ISSUE TITLE
[Feature] directly provides refs in exported components

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#4308]
### Existing Component
Yes

### Component Name
elform etc

### Description
如 #4157 所说，目前在 vue3 ts 中调用组件的方法时候，需要提供默认属性，如果可以直接包装之后返回类型，用户理解更容易，使用更方便，作为渐进增强不会对历史用户产生负面影响。

导出的类型，大致会这样
```ts
export const ElFormRef = InstanceType<typeof ElForm>
```

用户使用时候就可以简单地：
```ts
import type {ElFormRef} from 'element-plus'
```

如果设想可行，可以讨论下名称，我可以提 PR 来做。

**Comment by sxzz** [comment]
I think `FormRef` is better, Since there no `el` prefix in props and emits's name `formProps`.

**Comment by undefined-degisn** [comment]
> 我认为更好，因为道具和发射的名字没有前缀。`FormRef``el``formProps`

agree ！

**Comment by tolking** [comment]
`FormExpose`? closer to [expose](https://v3.vuejs.org/api/options-data.html#expose) in vue.

**Comment by Otto-J** [comment]
感觉 FormRef 更合适，更符合惯例，例如 @sxzz 提到的 `fromProps` 。另一方面，用户需要使用 ref='formRef' 来包裹

It feels like `FormRef` would be more appropriate and more in line with conventions, such as fromProps as mentioned by @sxzz. On the other hand, the user needs to wrap.

```html
<el-form ref='formRef'>
xxx
</el-form>
<script lang='ts'>
import type {FormRef} form 'element-plus'
const formRef=ref<FormRef>()
</script>

**Comment by Otto-J** [comment]
simple: componentName+'Ref'

**Comment by tolking** [comment]
> simple: componentName+'Ref'

Personally think that the use of `*Ref` is ambiguous. `*Ref` should represent a ref object (like `Ref` `ComputedRef` in vue), But `FormRef ` is not a ref object.

``` ts
export declare function ref<T extends object>(value: T): [T] extends [Ref] ? T : Ref<UnwrapRef<T>>;
```

The formRef is a ref object after `ref<FormRef>()`.

**Comment by sxzz** [comment]
How about `xxxInstance`?  e.g: `FormInstance`

**Comment by undefined-degisn** [comment]
> How about `xxxInstance`? e.g: `FormInstance`

i think it is a good idea, may be `xxxComponentInstance` ?

**Comment by sxzz** [comment]
@undefined-degisn Hmmm, i think it's too long.

**Comment by undefined-degisn** [comment]
> @undefined-degisn Hmmm, i think it's too long.

It's really too long, but there is also a  `ComponentPublicInstance` in the reference `vue`, so I think it's acceptable

**Comment by sxzz** [comment]
IMO, there are so many component types in Vue, so Vue needs named it accurately. But `xxxInstance` will not ambiguous in Element Plus, so I think we can name it shorter.

**Comment by undefined-degisn** [comment]
> IMO, there are so many component types in Vue, so Vue needs named it accurately. But will not ambiguous in Element Plus, so I think we can name it shorter.`xxxInstance`

Well, you convinced me, but I am worried that if the user introduces other `Component Library` at the same time, and there is the same naming as `EP`，so should we add `ElxxxInstance` ???

**Comment by sxzz** [comment]
Currently, there's no `El` prefix in props and emits types. So we just make it consistent. You can use name alias to avoid confilict.
```
import { FormInstance as ElFormInstance } from 'element-plus'
```

**Comment by undefined-degisn** [comment]
> Currently, there's no `El` prefix in props and emits types. So we just make it consistent. You can use name alias to avoid confilict.
> 
> ```
> import { FormInstance as ElFormInstance } from 'element-plus'
> ```

get, you are right !

**Comment by sxzz** [comment]
@Otto-J @tolking WDYT?

**Comment by tolking** [comment]
The `FormInstance` is easier to understand, good idea

**Comment by Otto-J** [comment]
> The `FormInstance` is easier to understand, good idea

Same.
俺也一样。

**Comment by sxzz** [comment]
So we finally confirmed to use `ComponentNameInstance` as the name.

```ts
export const FormInstance = InstanceType<typeof ElForm>
```

**Comment by Otto-J** [comment]
各位，欣喜地看到各组件已经提供了对应 `xxxInstance` 的类型，比如 [PR](https://github.com/element-plus/element-plus/pull/6669/files#diff-dcee507f8ba45f33de8c2f6b92446b068b46ecb5020c220deefa6f8e30c90856) 感谢付出的努力，本 issues 关闭。😄
