### ISSUE TITLE
[Bug Report] Icons not generated

### ISSUE THREAD

**Issue by causingh** [element-plus/element-plus#4311]
### Element Plus version
1.2.0-beta.2

### OS/Browsers version
Windows 10/Android - Chrome - Version 95.0.1020.44 (Official build) (64-bit)

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-demo-forked-w9x44?file=/package.json

### Steps to reproduce
Create button icon component and import the specified icons.

### What is Expected?
Icons should be generated same as shown on documentation.

### What is actually happening?
Button element is rendered but not the icon/svg

**Comment by SmallSample** [comment]
The version of element plus in your example is 1.1.0-beta.12, which does not support importing icons as components. You can upgrade the version to 1.2.0-beta.2
![image](https://user-images.githubusercontent.com/34450888/140853971-1963dbdf-e133-401a-8397-305d4b21c662.png)

**Comment by causingh** [comment]
@SmallSample element plus version updated to latest and still the same.

**Comment by SmallSample** [comment]
You just import components, not apps. An example of the official website is Vue's < script setup > syntax, which can be viewed https://v3.cn.vuejs.org/api/sfc-script-setup.html @causingh
