### ISSUE TITLE
[Bug Report] nuxt3 build failed

### ISSUE THREAD

**Issue by Licoy** [element-plus/element-plus#4317]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
chrome

### Vue version
3.2.21

### Reproduction Link
https://github.com/Licoy/nuxt3-element-plus-build

### Steps to reproduce
```
npm run build
```

### What is Expected?
```
npm run build [success]
npm run start [success]
```

### What is actually happening?
 ```
ERROR  Could not resolve './hooks/use-prevent-globalThis/index.js' from ./hooks/use-prevent-globalThis/index.js?commonjs-external               13:28:43  

  at error (node_modules\rollup\dist\shared\rollup.js:158:30)
  at ModuleLoader.handleResolveId (node_modules\rollup\dist\shared\rollup.js:22306:24)
  at node_modules\rollup\dist\shared\rollup.js:22300:26
```

**Comment by Licoy** [comment]
不使用`element-plus`编译就是正常的

**Comment by genffy** [comment]
https://github.com/element-plus/element-plus-nuxt-starter/issues/13
https://github.com/nuxt/framework/issues/1006
nuxt3 已经 fix，等待更新发布

**Comment by Licoy** [comment]
@genffy 好的，谢谢
