### ISSUE TITLE
[bug report]ElInputNumber: type check failed for prop "modelValue". Expected Number with value NaN, got Undefined

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#4323]
Element Plus version
1.2.0-beta.3

OS/Browsers version
chrome 95

Vue version
3.2.21

Steps to reproduce
el-input-number 默认值是 undefined 时，控制台出现警告：
[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Number with value NaN, got Undefined
at <ElInputNumber modelValue=undefined onUpdate:modelValue=fn<onUpdateModelValue> controls=false ... >

What is Expected?
el-input-number 希望在不给默认值的时候没有警告，因为很多场景是没有默认值的。在之前的版本 1.2.0-beta.2 是没有问题的

What is actually happening?
el-input-number 默认值是 undefined 时，控制台出现警告

**Comment by gezhigang1005** [comment]
Same question

**Comment by jiaozhiye** [comment]
> @sxzz
> 
> 我也遇到同样的问题！！！
> 
> 原有的表单使用input-number组件默认都是undefined，升级1.2.0后就又变了？
> 
> [1.1.0.20](https://github.com/element-plus/element-plus/blob/8a0cb4a1e79e56076b5179ffc6500488f4c1390b/packages/components/input-number/src/index.vue#L104)
> 
> ```
> modelValue: {
>       type: Number,
> },
> ```
> 
> 刚看了下，ant也是支持undefined的

之前版本出现过一次这个问题，后来修复了，这次 1.2.0-beta.3 版本又出现了

**Comment by YaoXiangMei** [comment]
附议

**Comment by barry1102** [comment]
![image](https://user-images.githubusercontent.com/27950905/145988900-92e47014-7385-4d39-a7e7-928f0cd112b2.png)
bug 又复现了，不给力呀哥们

**Comment by YaoXiangMei** [comment]
来信已经收到！！！谢谢

**Comment by lemoe2021** [comment]
Not merged.
https://github.com/element-plus/element-plus/pull/4338

**Comment by YaoXiangMei** [comment]
来信已经收到！！！谢谢
