### ISSUE TITLE
[Feature Request] Can the datepicker date selector method add a 'blur' method to make 'input' lose focus?

### ISSUE THREAD

**Issue by a452746100** [element-plus/element-plus#4327]
### Existing Component
Yes

### Component Name
DatePicker

### Description
At present, there is only one 'focus' method. I hope the official can consider adding a' blur 'method

**Comment by msidolphin** [comment]
Is blur really necessary?  It doesn't need to be called in other place

**Comment by a452746100** [comment]
When Binding keyboard events, the time selector pop-up window cannot be hidden when moving the focus to the next line with the keyboard

**Comment by a452746100** [comment]
> Is blur really necessary? It doesn't need to be called in other place

When Binding keyboard events, the time selector pop-up window cannot be hidden when moving the focus to the next line with the keyboard

**Comment by a452746100** [comment]
It is normal to switch the next focus with the mouse, but not for keyboard events

**Comment by msidolphin** [comment]
I think there is a problem with the focus method, it doesn't focus the input box, so the picker is not hidden after switching the target

**Comment by a452746100** [comment]
你好，这个问题解决了吗？我这边比较急着用，有结果麻烦回复一下。谢谢哈。
