### ISSUE TITLE
[feature request] node not found_ Modules / element plus / ES / components / affix / index.js file

### ISSUE THREAD

**Issue by shuiche-it** [element-plus/element-plus#4328]
### Existing Component
Yes

### Component Name
Icon

### Description
element-plus 1.2.0.beta-3

直接编译报错

```
./node_modules/element-plus/es/components/affix/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/zhangzexuan/Codes.localized/work.localized/ai-power/ai_power_web/node_modules/element-plus/es/components/affix/index.js'
```

**Comment by shuiche-it** [comment]
> 你好@shuiche-it。请点击此提供一个网上再现演示[链接](https://codepen.io/iamkun/pen/YzWMaVr)或最小GitHub的仓库。你好@洒水车-它，请提供一个可复现问题的链接以便于我们帮你排查问题。通过可以点击[此处](https://codepen.io/iamkun/pen/YzWMaVr)创建³³或者提供一个最小化的 GitHub 仓库。

我升级了element-plus 后就出现了这个问题。之前版本是1.1.0-beta.7， 升级到1.2.0-beta.3 编译就出问题了

**Comment by shuiche-it** [comment]
> > 你好@shuiche-it。请点击此提供一个网上再现演示[链接](https://codepen.io/iamkun/pen/YzWMaVr)或最小GitHub的仓库。你好@洒水车-它，请提供一个可复现问题的链接以便于我们帮你排查问题。通过可以点击[此处](https://codepen.io/iamkun/pen/YzWMaVr)创建³³或者提供一个最小化的 GitHub 仓库。
> 
> 我升级了element-plus 后就出现了这个问题。之前版本是1.1.0-beta.7， 升级到1.2.0-beta.3 编译就出问题了

报错内容如下：
![image](https://user-images.githubusercontent.com/10776422/140903182-ed02c8f8-a5ae-410c-8945-5481db74989a.png)

**Comment by shuiche-it** [comment]
![image](https://user-images.githubusercontent.com/10776422/140907173-11edfa52-5a2b-46ae-bb16-2a210545a383.png)

**Comment by msidolphin** [comment]
提供一个重现demo或者仓库吧
