### ISSUE TITLE
[Feature Request] Why can't the value property of el-option be set to undefined?

### ISSUE THREAD

**Issue by BiosSun** [element-plus/element-plus#4332]
### Existing Component
Yes

### Component Name
el-option

### Description
I want to add the following option in a filter select:

```html
<el-option :value="undefined" :label="All" />
```

But it cannot pass Vue's propertry type check.

**Comment by undefined-degisn** [comment]
I don't understand why you set `undefined`

**Comment by msidolphin** [comment]
You can use empty string instead of undefined
