### ISSUE TITLE
[Bug Report] Adding a space to the text content of a button causes an exception in width and content

### ISSUE THREAD

**Issue by yangdan8** [element-plus/element-plus#4334]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
win10/chrome95

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/yangdan8/pen/JjyZdjW

### Steps to reproduce
Open the demo and view the button for page output

### What is Expected?
The width and spacing of the two buttons are the same

### What is actually happening?
1. The width of the two buttons is inconsistent
2. The space between two characters is inconsistent

**Comment by msidolphin** [comment]
Only supported two chinese characters

**Comment by undefined-degisn** [comment]
> Only supported two chinese characters

but I think it's more appropriate to remove the spaces before and after the words ?

**Comment by lemoe2021** [comment]
This feature is so restrictive, why not set the default to false.

**Comment by msidolphin** [comment]
> This feature is so restrictive, why not set the default to false.

The default value has been adjusted

**Comment by sxzz** [comment]
Fixed in #4330
