### ISSUE TITLE
[bug report] after loading on demand, component styles such as elnotification are lost

### ISSUE THREAD

**Issue by a586543** [element-plus/element-plus#4347]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Chrome 94.0.4606.81

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/licheng586/pen/ExvRzNg

### Steps to reproduce
vite使用ElementPlusResolver按需加载后ElNotification等组件样式丢失

### What is Expected?
应该有基础样式

### What is actually happening?
没有基础样式

**Comment by msidolphin** [comment]
I think ElementPlusResolver should only support components and directives, you need to import ElNotification yourself

```ts
import { ElNotification } from 'element-plus'
```

**Comment by sxzz** [comment]
Please refer to https://github.com/element-plus/element-plus/issues/436#issuecomment-961395053

**Comment by zhoutong123** [comment]
me too, how to solve

**Comment by zhoutong123** [comment]
暂时只能手动引入这个才能正常显示
import "element-plus/theme-chalk/src/base.scss";
import "element-plus/theme-chalk/src/notification.scss";

ElMessage, ElLoading, ElMessageBox 这三个也要特别引入样式

**Comment by Arctic7** [comment]
> 暂时只能手动引入这个才能正常显示 import "element-plus/theme-chalk/src/base.scss"; import "element-plus/theme-chalk/src/notification.scss";
> 
> ElMessage, ElLoading, ElMessageBox 这三个也要特别引入样式

感谢回答，这个问题我前几天也遇到了
