### ISSUE TITLE
[Bug Report] el-table set selected(toggleRowSelection) fail

### ISSUE THREAD

**Issue by zhoutm** [element-plus/element-plus#4348]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Chrome

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/zhoutm/pen/mdMjEyo

### Steps to reproduce
use axios get data set el-table selected(toggleRowSelection) fail,but button click is success

通过axios获得数据，并设置el-table选中失败，但是通过按钮点击是可以设置成功

1.1.0 beta.24 is ok

1.1.0 beta.24的版本就没有问题

this.$refs.class_table.toggleRowSelection(row)
 

### What is Expected?
success

### What is actually happening?
fail

**Comment by zhoutm** [comment]
> Hello @zhoutm. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository.你好 @zhoutm, 请提供一个可复现问题的链接以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。

ok, update Reproduction Link

**Comment by msidolphin** [comment]
cannot reproduced

**Comment by hovees** [comment]
@zhoutm try $nextTick and you missed the second parameter toggleRowSelection(row, **selected**)

**Comment by zhoutm** [comment]
> @zhoutm try $nextTick

        this.$nextTick(()=> {
              this.$refs.class_table.toggleRowSelection(n)
            }
          })
        })

it's ok

**Comment by zhoutm** [comment]
> @zhoutm try $nextTick

ok,very good. it's success.
