### ISSUE TITLE
[Feature Request] Select component required option

### ISSUE THREAD

**Issue by arthurlauck** [element-plus/element-plus#4354]
### Existing Component
Yes

### Component Name
Select

### Description
Select component, don't have a required attribute option, so if I have a form that select should be filled, is not supported.

Is it doable?

**Comment by msidolphin** [comment]
You can refer to the [documentation](https://element-plus.org/en-US/component/form.html#validation)

**Comment by arthurlauck** [comment]
Oh, I didn't know that form validator, thanks, that will work!
