### ISSUE TITLE
[feature request] select whether a custom suffix icon attribute can be added

### ISSUE THREAD

**Issue by hhparty** [element-plus/element-plus#4360]
### Existing Component
是

### Component Name
select

### Description
我看到element字体图标升级为了svg，那么是否可以添加一个属性用来自定义后缀图标呢，就像antd vue中的suffixIcon属性一样

**Comment by msidolphin** [comment]
![image](https://user-images.githubusercontent.com/26672484/141271317-4a3886cf-a50e-4497-b043-9cbe64b7977b.png)
Do you mean this icon?

**Comment by hhparty** [comment]
> ![image](https://user-images.githubusercontent.com/26672484/141271317-4a3886cf-a50e-4497-b043-9cbe64b7977b.png) Do you mean this icon?
yes

**Comment by hhparty** [comment]
请问一下更新的版本大概是每周什么时候发布呢

**Comment by sxzz** [comment]
Released as `1.2.0-beta.4`
