### ISSUE TITLE
[Bug Report] el-upload clearFiles does not work when auto-upload=false

### ISSUE THREAD

**Issue by y3lousso** [element-plus/element-plus#4363]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Windows10/Chrome

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/y3lousso/pen/MWvBqLL

### Steps to reproduce
1. Upload any file
2. Click on clear -> nothing happens
3. Click on manuallyClear -> expected behavior

### What is Expected?
File list to be cleared

### What is actually happening?
It's not being cleared

From the debugger, I can see that status="ready" is not filtered
![image](https://user-images.githubusercontent.com/23299699/141281487-824d350d-b900-4d8c-8255-e2bcab9e7100.png)

**Comment by undefined-degisn** [comment]
if you want to use clearFiles to clear `ready` files, may be you should `this.$refs['test'].clearFiles(['ready'])`

The default parameter for `clearfiles ` is ['success', 'fail']

It seems that the document description is incomplete

**Comment by btea** [comment]
I think we should supplement the default parameters.

**Comment by y3lousso** [comment]
@undefined-degisn , you're right, I was so focused on the documentation, I missed the actual functional parameters ^^'
![image](https://user-images.githubusercontent.com/23299699/141310205-115d96a1-a4be-424e-bddd-668673fc1637.png)

**Comment by undefined-degisn** [comment]
> @undefined-德吉森，你是对的，我是如此专注于文档，我错过了实际的功能参数^^' ![image](https://user-images.githubusercontent.com/23299699/141310205-115d96a1-a4be-424e-bddd-668673fc1637.png)

 I'll change the document as soon as possible

**Comment by undefined-degisn** [comment]
> @undefined-degisn , you're right, I was so focused on the documentation, I missed the actual functional parameters ^^' ![image](https://user-images.githubusercontent.com/23299699/141310205-115d96a1-a4be-424e-bddd-668673fc1637.png)

I'll change the document as soon as possible

**Comment by sxzz** [comment]
Close via #6014
