### ISSUE TITLE
[Bug Report] Virtualized Tree can't used without id in props

### ISSUE THREAD

**Issue by JerryWang24** [element-plus/element-plus#4369]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
chrome

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/jerrywang24/pen/mdMGrVJ

### Steps to reproduce
when i used Virtualized Tree with cid in props, it can't work! if used id , work! 

### What is Expected?
fixed it or show me how to make it work!

### What is actually happening?
no error, just not work

**Comment by msidolphin** [comment]
I'm sorry, I made a mistake in documentation, please use value instead of id
