### ISSUE TITLE
I don't know if the bug of table and form is the problem I set

### ISSUE THREAD

**Issue by xinzi1990** [element-plus/element-plus#4370]
"version": "1.1.0-beta.24"

表格中有Form表单，且有某列**fixed** ，  type="expand" 中的内容会被截断

[https://codesandbox.io/s/romantic-sinoussi-76lrw?file=/src/App.vue](url)

**Comment by undefined-degisn** [comment]
[repo](https://codesandbox.io/s/romantic-sinoussi-76lrw?file=/src/App.vue)

**Comment by xinzi1990** [comment]
[https://codesandbox.io/s/romantic-sinoussi-76lrw?file=/src/App.vue](url)
1、新增一行
2、编辑
3、submit

**Comment by chenxch** [comment]
fixed.
