### ISSUE TITLE
[Bug Report] el-input doesn't display icon

### ISSUE THREAD

**Issue by rainym00d** [element-plus/element-plus#4380]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
macos  10.15.7    Chrome  95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/rainym00d/pen/bGrxwyL

### Steps to reproduce
click the link and you can see no "Search" icon in input box

### What is Expected?
see "Search" icon in input box

### What is actually happening?
no icon in input box

**Comment by undefined-degisn** [comment]
you don't seem to have introduced the `search ` component from `@element-plus/icons`

**Comment by rainym00d** [comment]
Thanks for your reply!
I tried to use `npm install @element-plus/icon` to install the package, and then `import { Search } from "@element-plus/icons";` in this page. However, it still doesn't work.
Maybe you could tell how to introduce it properly, the description of the official documentation is not very detailed, and I am confused.

**Comment by undefined-degisn** [comment]
if you want to  use `component`, remember `setup`, if you don't use `setup`, you must `return` this component
```typescript
<script lang="ts" setup>
import { Search } from "@element-plus/icons"
</script>
```

**Comment by rainym00d** [comment]
> if you want to use `component`
> 
> ```ts
> <script lang="ts">
> import { Search } from "@element-plus/icons"
> export default defineComponent({
>     setup(){
>         return {
>             Search 
>         }
>     }
> })
> </script>
> ```
> 
> or
> 
> ```ts
> <script lang="ts" setup>
> import { Search } from "@element-plus/icons"
> </script>
> ```



> if you want to use `component`
> 
> ```ts
> <script lang="ts">
> import { Search } from "@element-plus/icons"
> export default defineComponent({
>     setup(){
>         return {
>             Search 
>         }
>     }
> })
> </script>
> ```
> 
> or
> 
> ```ts
> <script lang="ts" setup>
> import { Search } from "@element-plus/icons"
> </script>
> ```

Thanks! My problem have solved perferctly with your help!
By the way, does there exists a way to global introduce the icon component, just like global introduce `element-plus`?

**Comment by undefined-degisn** [comment]
> Thanks! My problem has solved perferctly with your help! By the way, does there exists a way to global introduce the icon component, just like global introduce ?`element-plus`

I checked the source code. There is no such way of global registration

may be provide ? @msidolphin

**Comment by ExtReMLapin** [comment]
The issue I see with this is the icons name doesn't start with `el-` and for example, if an icon inited in settup is called File or Lock, you might end up with variable name collision if you don't do camelCase variable naming

**Comment by sxzz** [comment]
> Thanks! My problem has solved perferctly with your help!
> By the way, does there exists a way to global introduce the icon component, just like global introduce element-plus?

@rainym00d We may will add a auto import plugin in the future.
