### ISSUE TITLE
[Bug Report] ElMessage will not auto hide on pad or mobile device

### ISSUE THREAD

**Issue by Sdaiyan** [element-plus/element-plus#4382]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
pad or mobile device

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/embed/element-plus-demo-forked-xcuxc?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
1. call the show ElMessage function
调用 ElMessage 方法
2. （on mobile device）click or drag in the message box and wait for 3s
（使用移动设备，pad 或者 手机）点击或在提示框内拖动后等待3秒
3. messagebox will not auto hide
提示框不会自动消失

### What is Expected?
hide in 3s when opreate end
操作结束以后3秒钟自动消失

### What is actually happening?
i think because there is no mouseleave events on mobile device and there can't be listening the event. finally the messagebox can't be auto hide
我觉得这是因为移动设备上没有鼠标移出事件 导致监听不到事件 没办法自动隐藏提示框

**Comment by undefined-degisn** [comment]
这应该是不能用于移动端的，很多组件实现都不兼容移动端的！

**Comment by xiaoxian521** [comment]
Do not consider compatible mobile terminals, welcome pr if necessary
