### ISSUE TITLE
[bug report] some styles are lost after using automatic import

### ISSUE THREAD

**Issue by 453629963** [element-plus/element-plus#4387]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
windows 10/ edge 95.0.1020.44

### Vue version
3.2.16

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-mprd3

### Steps to reproduce
我使用的vite2.6.4，并且未使用TS，按官方文档使用自动导入方式加载组件。
第一步 安装unplugin-vue-components
第二步 main.js 中添加 
import 'element-plus/dist/index.css'
第三步 vite.config.js 中添加
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
export default defineConfig({
  plugins: [
      ...
      Components({
        resolvers: [ElementPlusResolver()]
      })
  ]
})

### What is Expected?
我希望按官方的文档操作后，可以实现自动导入并可以正常使用。

### What is actually happening?
但是现在自动导入下样式出现了问题，只有在完整引入的时候才显示正常。

**Comment by sxzz** [comment]
Please refer to https://github.com/element-plus/element-plus-vite-starter. If you don't use typescript, just rename `*.ts` to `*.js` and remove all annotations.

**Comment by 453629963** [comment]
@sxzz 
Thank you,The problem is solved
