### ISSUE TITLE
[Bug Report] Cascader lazyLoad bug

### ISSUE THREAD

**Issue by Miss-Sixty** [element-plus/element-plus#4389]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
windows10

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/zxh188300047/pen/LYjJKog

### Steps to reproduce
在官网 Cascader 组件 动态加载那里给的列子添加 :props:{}写在dom上就会出错，而写在js对象里就正常

### What is Expected?
可选择对应的选项

### What is actually happening?
选择选项后 v-modle 有值，但 Cascader 组件会把已选的 label 清空

**Comment by emojiiii** [comment]
guy, your `v-model`  spelling is wrong

**Comment by Miss-Sixty** [comment]
> guy, your `v-model` spelling is wrong

Thanks for reminding me. I described the problem wrong and I have changed it

**Comment by emojiiii** [comment]
In fact, this is not a bug

This is because when `: props = {lazy: XXX} ` is written like this, the address of this object will change each time the component is rendered, which triggers the internal watch

this will trigger redundant `watch` inside the component, resulting in menu update

**Comment by Miss-Sixty** [comment]
> In fact, this is not a bug
> 
> 
> 
> This is because when `:props="{ lazy: true, lazyLoad: lazyLoad }"` is written like this, the address of this object will change each time the component is rendered, which triggers the internal watch
> 
> 
> 
> this will trigger redundant `watch` inside the component, resulting in menu update

Thank you. I see.
