### ISSUE TITLE
[Bug Report] vue3 new feature `setup` is not available at `el-form`

### ISSUE THREAD

**Issue by Air-Cooled** [element-plus/element-plus#4390]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
win 10

### Vue version
3.2.21

### Steps to reproduce
`el-form` uses vue3 new feature to `setup` ​the default value of the form, which cannot be changed
```vue
<script setup>
import { reactive } from 'vue'

const form = reactive({
  input: ''
})
</script>

<template>
  <el-form ref="form" :model="form">
    <el-form-item label="Input" prop="input">
      <el-input v-model="form.input" />
    </el-form-item>
  </el-form>
</template>
```
*Is there something wrong with my writing?*

### What is Expected?
`el-form` supports `setup` of vue3 

### What is actually happening?
no value

**Comment by CSNight** [comment]
hi! change the model attr bind variable name to `formData` different from ref may help

**Comment by emojiiii** [comment]
because your `ref` attribute overlaps with the `form` name, i think if you change `form` to `formRef`，everything will be fine

**Comment by Air-Cooled** [comment]
> because your ref attribute overlaps with the `form` name

Well, the documentation doesn't say...

**checkbox exception**

![image](https://user-images.githubusercontent.com/55440364/143207508-a340f6ba-61bc-4382-812f-e1123d2f603e.png)

**Comment by sxzz** [comment]
Without reproduction link, we can give any help.

**Comment by Air-Cooled** [comment]
在 form 中使用 el-checkbox-group 就会出现异常，导致页面无法渲染

**Comment by sxzz** [comment]
Please provide a minimum reproduction link and reopen this issue.
