### ISSUE TITLE
[bug report] the drop-down menu with icon is not aligned

### ISSUE THREAD

**Issue by 360060316** [element-plus/element-plus#4392]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.30

### Vue version
3.2.21

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
如题

### What is Expected?
速度修复

### What is actually happening?
如题

**Comment by TgT982474256** [comment]
I have the same problem.   [https://codepen.io/TgT982474256/pen/OJjdMGL](https://codepen.io/TgT982474256/pen/OJjdMGL)

**Comment by sxzz** [comment]
Seems duplicate of #4421. Let's track the latest one.
