### ISSUE TITLE
[Bug Report] In nuxt3, el-dropdown will render messy and conflict with el-popover

### ISSUE THREAD

**Issue by cdwmhcc** [element-plus/element-plus#4394]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
windows

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/quizzical-ritchie-9u4n7?file=/pages/index.vue

### Steps to reproduce
In nuxt3, el-dropdown will render messy and conflict with el-popover

### What is Expected?
Hope the rendering is normal

### What is actually happening?
Hope the rendering is normal

**Comment by oooowl** [comment]
The same issues with me.
In el-pagination and el-dropdown

**Comment by oooowl** [comment]
The same issues with me.
In el-pagination and el-dropdown

**Comment by xiaoxian521** [comment]
Appears to behave normally in [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)
<img width="509" alt="image" src="https://user-images.githubusercontent.com/44761321/155048253-19d86410-6d7a-49ec-90ba-2cee736dd1d5.png">

**Comment by xiaoxian521** [comment]
Temporary workaround
refer to: https://github.com/element-plus/element-plus-nuxt-starter/blob/main/components/Examples.vue#L40

**Comment by Drinjs** [comment]
> The same issues with me. In el-pagination and el-dropdown

Since the bug hasn't been fixed @2.1.5, so we should write a pagination by ourselves or overwrite the css ? @xiaoxian521
