### ISSUE TITLE
[Feature Request] Refactor the fixed column implementation of the table with sticky

### ISSUE THREAD

**Issue by msidolphin** [element-plus/element-plus#4399]
### Existing Component
Yes

### Component Name
ElTable

### Description
Using sticky instead of the original implementation will have a better experience and performance, more importantly, it is to solve some long-standing layout problems

![image](https://user-images.githubusercontent.com/26672484/141761322-0a688bda-bcb5-4ea5-8aa9-935ad8549aa2.png)

**Comment by ketao4869** [comment]
@msidolphin 我从1.2.0-bata.2 跟新到2.0.1后发现这行代码不兼容，我像了解一下 z-index:1 主要解决了什么问题
![image](https://user-images.githubusercontent.com/54937496/155281756-ee339f9f-24ea-46a4-a2a3-849164b45c60.png)
