### ISSUE TITLE
[Feature Request] [empty] Need to customize empty style theme color

### ISSUE THREAD

**Issue by NWYLZW** [element-plus/element-plus#4401]
### Existing Component
Yes

### Component Name
empty

### Description
希望给 empty 组件提供修改主题色的方便的方式，目前只能用 css 去改颜色

**Comment by JeremyWuuuuu** [comment]
cc @kooriookami

**Comment by ExtReMLapin** [comment]
I had this issue with my dark theme css repo, wouldn't it mean compiling the SVG on each css color change ?

**Comment by YunYouJun** [comment]
Could you use screenshots and other ways to describe the results you want? I can't understand it clearly.

**Comment by ExtReMLapin** [comment]
The issue with https://github.com/element-plus/element-plus/blob/55348b30b6ae59b0efe8abfa9f8dbbeaabb5614a/packages/components/empty/src/img-empty.vue having hardcoded colors

**Comment by YunYouJun** [comment]
Now, we have css var in `empty` component. I think it has been resolved.
