### ISSUE TITLE
[Bug Report] el-select-v2 when option's value is 0, the label is not correct

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#4403]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
chrome

### Vue version
3.2.21

### Reproduction Link
https://codepen.io/yukisora/pen/vYJVqwQ?editors=1111

### Steps to reproduce
Don't know why codepen is broken, here is playground.

https://play.element-plus.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBFbElucHV0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5zZXR1cEVsZW1lbnRQbHVzKCk7XG4gIFxuY29uc3QgaW5pdGlhbHMgPSBbJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuY29uc3Qgb3B0aW9ucz0gcmVmKFxuICBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICAgIHZhbHVlOiBpZHgsXG4gICAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxuICB9KSlcbik7XG5jb25zdCB2YWx1ZT0gcmVmKCcnKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIHt7IHZhbHVlIH19XG4gIDxlbC1zZWxlY3QtdjJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0XCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==

### What is Expected?
Show the selected label. The old select component did this right.

### What is actually happening?
Show the placeholder.

![pic](https://user-images.githubusercontent.com/79942901/141736549-ea2bd27d-f13a-49aa-b4c5-6fe133b89087.png)

![pic](https://user-images.githubusercontent.com/79942901/141736715-c0005dd0-5021-4cb2-b6c7-46bf3a8acb14.png)

**Comment by lemoe2021** [comment]
Why not release a new version since 16 days

**Comment by btea** [comment]
cc @element-plus/backers

**Comment by sxzz** [comment]
Waiting for https://github.com/element-plus/element-plus/pull/4491
