### ISSUE TITLE
[Bug Report] Icons Not loading

### ISSUE THREAD

**Issue by Manu-Geotourist** [element-plus/element-plus#4404]
### Element Plus version
1.1.0-beta.4

### OS/Browsers version
All

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-78zs4

### Steps to reproduce
Try to load any icons.

Same issue was resolved previously - https://github.com/element-plus/element-plus/issues/3939#issue-1030007703

### What is Expected?
Icons should load

### What is actually happening?
Icons not loading

**Comment by jcindex** [comment]
The variable 'Search' in `App.vue` file is undefined, Please use `import {Search} from "@element-plus/icons"` to fixed it.

**Comment by Manu-Geotourist** [comment]
@jcindex , I have changed the code and now all the components are globally imported, and still, it's not loading, can you please check the sandbox now?

**Comment by jcindex** [comment]
@Manu-Geotourist This is my solution: https://codesandbox.io/s/element-plus-spa-forked-4vob6?file=/src/App.vue

**Comment by Manu-Geotourist** [comment]
@jcindex , yes the SVG icons are loading but the font icons are not loading

**Comment by jcindex** [comment]
@Manu-Geotourist Focus on this warning message in official documents. 
![image](https://user-images.githubusercontent.com/7412888/142185108-beb037e0-8996-4300-bd63-de15846d08c9.png)

**Comment by xiaxichen** [comment]
how do you solve this problem，I have this problem to。

**Comment by sxzz** [comment]
Font Icon has been removed, you can use SVG Icon, and refer to https://element-plus.org/zh-CN/component/icon.html .
