### ISSUE TITLE
[bug report] the content top, content bottom, side top, side mid and side bottom slots in VP app are not used

### ISSUE THREAD

**Issue by coderew** [element-plus/element-plus#4409]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
ma'c

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/pen/define/

### Steps to reproduce
1、在docs/vitepress目录下新建vp-app-d.vue文件
```

<script setup lang="ts">
import { onMounted } from 'vue'
import VPApp from './vp-app.vue'


</script>

<template>
  <div class="App">
    <VPApp>
      <template #content-top>自定义内容aaaaa</template>
    </VPApp>
  </div>
</template>
```
2、docs/theme目录下修改内容：

```
import VPAppD, { globals, NotFound } from '../vitepress'
export default {
  NotFound,
  Layout: VPAppD,
  logo: '/images/element-plus-logo-small.svg',
  enhanceApp: ({ app }) => {
    app.use(ElementPlus)

    globals.forEach(([name, Comp]) => {
      app.component(name, Comp)
    })
  },
}
```

3、启动工程npm run docs:dev，发现页面顶部并没有
自定义内容aaaaa

### What is Expected?
能够自定义content-top、content-bottom、aside-top、aside-mid、aside-bottom的内容

### What is actually happening?
不能自定义content-top、content-bottom、aside-top、aside-mid、aside-bottom的内容

**Comment by emojiiii** [comment]
I don't understand why you need to worry about the components inside the docs

**Comment by sxzz** [comment]
Please reopen this issue after describing the usage case
