### ISSUE TITLE
Simple translations missing?

### ISSUE THREAD

**Issue by lukaszwojtow** [element-plus/element-plus#4410]
Hi,
I'm wondering if there is any deeper cause for some simple translations missing, for example:
https://github.com/element-plus/element-plus/blob/6de5aacce4836fa4201a1a4dc05ad0f7446f8fbb/packages/locale/lang/pl.ts#L117

Is it only a matter of someone submitting PR with 2-3 lines changed?

**Comment by sxzz** [comment]
It seems that because these strings were added later, the author did not add the corresponding translation content.

If anyone is willing to submit a PR, we are very happy to accept it.
