### ISSUE TITLE
[bug report] Import resource error

### ISSUE THREAD

**Issue by swipth** [element-plus/element-plus#4415]
Element Plus version
1.2.0-beta.3

win11

Vue version
3.0.11

node
14.15.0

ERROR  Failed to compile with 87 errors                                                                                                                  上午10:14:17

 error  in ./node_modules/element-plus/es/components/input-number/src/input-number.vue_vue&type=script&lang.mjs

Can't import the named export 'ArrowDown' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/transfer/src/index.vue_vue&type=script&lang.mjs

Can't import the named export 'ArrowLeft' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/transfer/src/index.vue_vue&type=script&lang.mjs

Can't import the named export 'ArrowRight' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/select/src/useSelect.mjs

Can't import the named export 'ArrowUp' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/page-header/src/page-header.mjs

Can't import the named export 'Back' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/time-picker/src/common/picker.vue_vue&type=script&lang.mjs

Can't import the named export 'Calendar' from non EcmaScript module (only default export is available)

 error  in ./node_modules/element-plus/es/components/tree/src/tree-node.vue_vue&type=script&lang.mjs

Can't import the named export 'CaretRight' from non EcmaScript module (only default export is available)

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/issues/3923#issuecomment-953847521
