### ISSUE TITLE
How to make low version browsers(<60) support new ResizeObserver in vite?

### ISSUE THREAD

**Issue by qc-z** [element-plus/element-plus#4419]
![img](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7be5f67f458845d3a05cc601d4068b64~tplv-k3u1fbpfcp-zoom-1.awebp?)

**Comment by sxzz** [comment]
https://www.npmjs.com/package/resize-observer-polyfill

**Comment by sxzz** [comment]
https://element-plus.org/zh-CN/guide/installation.html
> Element Plus 可以在支持 ES2018 和 ResizeObserver 的浏览器上运行。 如果您确实需要支持旧版本的浏览器，请自行添加 Babel 和相应的 Polyfill 。

**Comment by mrlong** [comment]
> https://element-plus.org/zh-CN/guide/installation.html
> 
> > Element Plus 可以在支持 ES2018 和 ResizeObserver 的浏览器上运行。 如果您确实需要支持旧版本的浏览器，请自行添加 Babel 和相应的 Polyfill 。

有例子吗，resize-observer-polyfill 在 vue3 怎么使用。

**Comment by qc-z** [comment]
我也想求一个例子

**Comment by sxzz** [comment]
import ResizeObserver from 'resize-observer-polyfill';

window.ResizeObserver = ResizeObserver

**Comment by qc-z** [comment]
@sxzz 已解决，谢谢
