### ISSUE TITLE
[bug report] El dropdown item: when the icon is set with the icon attribute, the icon is not centered with the text

### ISSUE THREAD

**Issue by jcindex** [element-plus/element-plus#4421]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Windows 10 / Chrome 86.0

### Vue version
3.2.22

### Reproduction Link
https://codesandbox.io/s/xxxxxx

### Steps to reproduce
官方文档即可重现：https://element-plus.gitee.io/zh-CN/component/dropdown.html#触发方式
！！！！！！由于在codesandbox上引入@element-plus/icons出错，所以不使用codesandbox代码片段

### What is Expected?
svg图标与文本居中对齐

### What is actually happening?
svg图标偏向上方了

**Comment by ljw-codeking** [comment]
> ### Element Plus version
> 1.2.0-beta.3
> 
> ### OS/Browsers version
> Windows 10 / Chrome 86.0
> 
> ### Vue version
> 3.2.22
> 
> ### Reproduction Link
> https://codesandbox.io/s/xxxxxx
> 
> ### Steps to reproduce
> 官方文档即可重现：[https://element-plus.gitee.io/zh-CN/component/dropdown.html#触发方式](https://element-plus.gitee.io/zh-CN/component/dropdown.html#%E8%A7%A6%E5%8F%91%E6%96%B9%E5%BC%8F) ！！！！！！由于在codesandbox上引入@element-plus/icons出错，所以不使用codesandbox代码片段
> 
> ### What is Expected?
> svg图标与文本居中对齐
> 
> ### What is actually happening?
> svg图标偏向上方了

我怎么没有看见。。。

**Comment by jcindex** [comment]
@ljw-codeking  ![image](https://user-images.githubusercontent.com/7412888/142166819-56e39729-d61d-4cbb-b90e-05bedb373c8f.png)
