### ISSUE TITLE
[Feature Request] how to add a local picture

### ISSUE THREAD

**Issue by wintersflowers** [element-plus/element-plus#4422]
### Existing Component
Yes

### Component Name
el-image

### Description
<img src="../assets/user.svg" />,it will work.
<el-image src="../assets/user.svg" /></el-image>,it will not work.
according to vite doc,change code like this:

template:
<el-image :src="getImageUrl"></el-image>

typescript:
    const getImageUrl = () => {
        return new URL("../assets/user.svg", import.meta.url).href
    }
return getImageUrl

it can not work.please give me right code.

**Comment by ljw-codeking** [comment]
> ### Existing Component
> Yes
> 
> ### Component Name
> el-image
> 
> ### Description
> ![](../assets/user.svg),it will work. ,it will not work. according to vite doc,change code like this:
> 
> template:
> 
> typescript: const getImageUrl = () => { return new URL("../assets/user.svg", import.meta.url).href } return getImageUrl
> 
> it can not work.please give me right code.

https://vitejs.cn/guide/features.html#%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%A4%84%E7%90%86

**Comment by sxzz** [comment]
This is not issue of Element Plus.
