### ISSUE TITLE
Font Icon introduction problem

### ISSUE THREAD

**Issue by tenyears94** [element-plus/element-plus#4427]
使用场景：原生HTML + vue + Element-plus
问题描述：vue和Element-plus已经引入可正常使用，但是图标始终不能引入，下载icons下面es、lib、type 三个文件夹都测试了不行，请教使用方法

**Comment by emojiiii** [comment]
很抱歉，目前图标库还没有`umd`格式，只能通过`npm`包的形式引入

**Comment by tenyears94** [comment]
那请问<el-icon>组件支持扩展吗？比如我自行去阿里巴巴iconfont引入图标，仍旧使用该组件来显示引入的图标

**Comment by emojiiii** [comment]
> 那请问组件支持扩展吗？比如我自行去阿里巴巴iconfont引入图标，仍旧使用该组件来显示引入的图标

一般EP的组件都支持传入`Component`，所以只要你把对应的图标注册为`Component`就可以正常使用
比如 [Button组件的icon属性](https://element-plus.gitee.io/zh-CN/component/button.html#button-%E5%B1%9E%E6%80%A7)

**Comment by sxzz** [comment]
https://codepen.io/sxzz/pen/GRMgavo
