### ISSUE TITLE
In the [bug report] [El upload] component, the parameter "on preview" is wrong in the TS type declaration

### ISSUE THREAD

**Issue by ll60** [element-plus/element-plus#4436]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
MacOs12.0.1 / 95.0.4638.69（正式版本） (arm64)

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
ts声明是 onPreview?: () => void;  
IDE会报错: 不能将类型“(file: any) => void”分配给类型“() => void”；  
还有onPreview文档中描述: function(file), file的声明是: UploadFile类型，但实际打印出来的结果并不是UploadFile结构???；  

### What is Expected?
预期1: 期望得到正确的onPreview类型声明；  
预期2: 期望[el-upload]中涉及到入参function(file)的file参数类型能明确。

### What is actually happening?
1: onPreview类型声明错误；  
2: [el-upload]涉及到file的参数类型不明确；

**Comment by cheng-shuai** [comment]
我也遇到了

**Comment by cheng-shuai** [comment]
i also met

**Comment by bianyinglong** [comment]
me too

**Comment by wanyakun** [comment]
+1， 2.0.2依然有TS错误，
before-upload和on-preview类型定义都不对
