### ISSUE TITLE
[bug report] header vertical problem of table component

### ISSUE THREAD

**Issue by weizidong** [element-plus/element-plus#4444]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Microsoft Edge 95.0.1020.44

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
1、打开文档：https://element-plus.gitee.io/zh-CN/component/table.html 中的codepen.io测试

### What is Expected?
1、表格组件的表头默认横向

### What is actually happening?
1、表格组件的表头纵向，且未发现文档中有说明如何横向切换
![image](https://user-images.githubusercontent.com/12541963/142369578-6ae27f31-c75c-4d77-938d-100f26ac04e4.png)

**Comment by msidolphin** [comment]
same issue #4278
