### ISSUE TITLE
[Bug Report] [Component] [rate, icon] rate don't show icon

### ISSUE THREAD

**Issue by sxzz** [element-plus/element-plus#4450]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.22`
- Element Plus Version: `1.2.0-beta.3`
- Browser / OS: `Chrome/96.0.4664.45 `
- Build Tool: `CDN`

### Related Component

- `el-rate`
- `el-icon`

### Reproduction Link

[Link](https://element-plus.org/zh-CN/component/rate.html)

### Steps to reproduce

Hover the fourth or fifth star, and then no stars will appear.

### What is Expected?

the stars display normally.

### What is actually happening?

the stars didn't display.

### Additional comments

_(empty)_

**Comment by luyh7** [comment]
#4449
