### ISSUE TITLE
[Bug Report] vue3 use <el-image> preview-src-list warn Component that was made reactive

### ISSUE THREAD

**Issue by weklay** [element-plus/element-plus#4457]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Chrome 94.0.4606.81

### Vue version
3.2.22

### Reproduction Link
https://elementui.github.io/none

### Steps to reproduce
<template>
  <el-image style="width: 100px; height: 100px" :src="url" :preview-src-list="srcList" />
</template>

<script>
import { defineComponent, ref } from "vue";
export default defineComponent({
  setup() {
    const url = ref("https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg");
    const srcList = ref([
      "https://fuss10.elemecdn.com/8/27/f01c15bb73e1ef3793e64e6b7bbccjpeg.jpeg",
      "https://fuss10.elemecdn.com/1/8e/aeffeb4de74e2fde4bd74fc7b4486jpeg.jpeg",
    ]);
    return {
      url,
      srcList,
    };
  },
});
</script>

### What is Expected?
Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 

### What is actually happening?
[Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
Component that was made reactive:  {name: "FullScreen", render: ƒ, __file: "packages/components/FullScreen.vue"} 
  at <ElIcon onClick=fn<toggleMode> > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="viewer-fade" > 
  at <ElImageViewer key=0 z-index=2000 initial-index=0  ... > 
  at <ElImage style= {width: "100px", height: "100px"}height: "100px"width: "100px"__proto__: Object src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg" preview-src-list= (2) ["https://fuss10.elemecdn.com/8/27/f01c15bb73e1ef3793e64e6b7bbccjpeg.jpeg", "https://fuss10.elemecdn.com/1/8e/aeffeb4de74e2fde4bd74fc7b4486jpeg.jpeg"]0: "https://fuss10.elemecdn.com/8/27/f01c15bb73e1ef3793e64e6b7bbccjpeg.jpeg"1: "https://fuss10.elemecdn.com/1/8e/aeffeb4de74e2fde4bd74fc7b4486jpeg.jpeg"length: 2__proto__: Array(0)  ... > 
  at <Point orderId=8888 putType=18 > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>

**Comment by emojiiii** [comment]
can you provide a reproduction?

**Comment by sxzz** [comment]
Please provide a minimum reproduction link and reopen this issue.

**Comment by weklay** [comment]
仓库地址：https://codepen.io/weklay/pen/GRveGMV

问题描述： 使用最新版的VUE3和最新的el-image组件，启用preview-src-list预览图片时，点击预览图片，vue提示console.log提示：Component that was made reactive:  {name: "FullScreen", render: ƒ, __file: "packages/components/FullScreen.vue"}
