### ISSUE TITLE
When the button is active, press enter to execute the bound click event

### ISSUE THREAD

**Issue by jinmarcus** [element-plus/element-plus#4458]
如视频所示：

https://user-images.githubusercontent.com/17996289/142562634-dadce188-d66e-4d01-a425-9dbdcb55d329.mp4

当按钮处于激活状态，此时按下回车可执行绑定的click事件

比如我有一个按钮是删除按钮，当前点击删除按钮的时候，会弹出删除确认框，而此时按钮仍然是激活状态，而此时按下回车，就会相当于不停的点击这个按钮，就会不停的弹出删除窗口，这就很尴尬了，

而在实际的业务场景中，不可能为每个按钮都设置相应的防抖动的点击事件。

**Comment by sxzz** [comment]
这点是继承了原生 button 的特性。可以自行二次封装一个按钮并添加 `@keypress.enter.prevent` 解决
