### ISSUE TITLE
Older browser kernel, error reported.

### ISSUE THREAD

**Issue by mrlong** [element-plus/element-plus#4485]
![image](https://user-images.githubusercontent.com/225022/142765174-0f13ebf6-d2cf-4ca6-baec-8ce65d77efc9.png)

#### miniblink v8 7.5 版本。vue 3.2.22

**Comment by sxzz** [comment]
https://element-plus.org/zh-CN/guide/installation.html
> Element Plus 可以在支持 ES2018 和 ResizeObserver 的浏览器上运行。 如果您确实需要支持旧版本的浏览器，请自行添加 Babel 和相应的 Polyfill 。
