### ISSUE TITLE
[Feature Request] Is it possible for programmatically method to set data in Table component?

### ISSUE THREAD

**Issue by bytrix** [element-plus/element-plus#4490]
### Existing Component
是

### Component Name
Table

### Description
```
<el-table
  :data="tableData" // <-- what if I'm not sure the variable name or the variable name changes?
></el-table>
```
better to provide an API like this:
```
tableRef.setData(tableData)
```

**Comment by ExtReMLapin** [comment]
Let's say for some reason the data you want is either `potato`, `strawberry` or `apple` 
Then you're going to create a variable called `fruitBridge` and everytime what you want to point to changes (any in the list above), you do : 

`this.fruitBridge = this.potato`

And obviously, this doesn't change : 

`:data="fruitBridge"`

**Comment by bytrix** [comment]
> Let's say for some reason the data you want is either `potato`, `strawberry` or `apple` Then you're going to create a variable called `fruitBridge` and everytime what you want to point to changes (any in the list above), you do :
> 
> `this.fruitBridge = this.potato`
> 
> And obviously, this doesn't change :
> 
> `:data="fruitBridge"`

In some cases, I don't want to change the data value.
Let's say here is a data array:
```
[
  { id: 1, title: "some title" },
  { id: 2, title: "another title" },
  { id: 3, title: "another title again" }
]
```
And now I have a toggle button to filter the data, and click again to restore data.
Let's say filter the record which id is 2, and other records hide:
```
const filterData = () => {
  data.value = data.value.filter(item => item.id === 2)
  // this modify the origin data, it cannot be restored
}
```

If I can programmatically set data, the data value can be restored:
```
const filterData = () => {
  tableRef.setData(data.value.filter(item => item.id === 2))
}
const restoreData = () => {
  tableRef.setData(data.value)
}
```

**Comment by sxzz** [comment]
FYI, you can create two vars, `currentData`, `data`. `data` is original, `currentData` is filtered data.
