### ISSUE TITLE
[feature request] can I keep the writing method of El icon using class class name to generate icon? Similar to < I class = "El menu" / >

### ISSUE THREAD

**Issue by angrybird233** [element-plus/element-plus#4498]
### Existing Component
Yes

### Component Name
el-icon

### Description
在使用element-plus时迁移之前的element项目，很多视动态渲染的，无法直接使用图标组件来渲染

**Comment by emojiiii** [comment]
`font icon` has been removed, please see [icon](https://element-plus.gitee.io/zh-CN/component/icon.html)
