### ISSUE TITLE
[Feature Request] Dynamic, Automatical Icon. How to dynamically specify icons through the backend such as management system?

### ISSUE THREAD

**Issue by yhyzgn** [element-plus/element-plus#4502]
### Existing Component
Yes

### Component Name
Icon

### Description
How to dynamically specify icons through the backend such as management system?

**Comment by sxzz** [comment]
FYI: you can import all icons, and use `component` tag
Example: https://play.element-plus.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBFbElucHV0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0ICogYXMgaWNvbnMgZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucydcblxuc2V0dXBFbGVtZW50UGx1cygpO1xuY29uc3QgaWNvbiA9ICdNb29uJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWljb24+XG4gICAgPGNvbXBvbmVudCA6aXM9XCJpY29uc1tpY29uXVwiIC8+XG4gIDwvZWwtaWNvbj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9
