### ISSUE TITLE
[Bug Report] The official website will freeze on some browsers

### ISSUE THREAD

**Issue by xiao11lang** [element-plus/element-plus#4509]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
edge 96.0.1054.29

### Vue version
3.2.22

### Reproduction Link
https://codepen.io

### Steps to reproduce
scroll to example and click on the 'option' to show sub menu

### What is Expected?
show sub menu

### What is actually happening?
the browser will freeze

**Comment by xiao11lang** [comment]
the detail link is https://element-plus.gitee.io/zh-CN/component/container.html#%E4%BE%8B%E5%AD%90

**Comment by xiaoxian521** [comment]
Key code(https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/common/transition.scss#L84)：
```
.collapse-transition {
  transition: var(--el-transition-duration) height ease-in-out,
    var(--el-transition-duration) padding-top ease-in-out,
    var(--el-transition-duration) padding-bottom ease-in-out;
}
```
Each change of these properties will cause the browser to relayout, regenerating the bitmap of the element
Solution：use the following code in scope, reduce rendering costs in the form of reduced animation：
```
.collapse-transition {
  transition: 0.01s all ease-in-out !important;
}
```
