### ISSUE TITLE
[Bug Report] Set plugin language。warning: The previous i18n usage is deprecated

### ISSUE THREAD

**Issue by ManbasJi** [element-plus/element-plus#4515]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
chrome 96

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
import { use } from 'element-plus/lib/locale';
import zhCn from 'element-plus/lib/locale/lang/zh-cn'

### What is Expected?

Language display Chinese

### What is actually happening?
The language is still English, and the prompt
ElementPlusError: [deprecation] :
      The previous i18n usage is deprecated please update to
      the new one to get reactive i18n translations, refer to:
      https://element-plus.org/#/en-US/component/i18n

**Comment by emojiiii** [comment]
Please provide a minimum reproduction link

**Comment by sxzz** [comment]
Please refer to latest docs.
https://element-plus.org/zh-CN/guide/i18n.html
