### ISSUE TITLE
[bug report] the CDN introduces element plus, and the configured dayjs week start day weekstart is ignored

### ISSUE THREAD

**Issue by beckZgh** [element-plus/element-plus#4518]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Chrome

### Vue version
3.2.16

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr/

### Steps to reproduce
1. vite 打包使用 CDN 加载 element-plus ，main.js 引入 "dayjs/locale/zh-cn" 会默认星期一为起始日，使用 CDN 后被忽略

2. vite 打包使用 CDN 加载 element-plus, dayjs , 则提示 "Uncaught TypeError: Failed to resolve module specifier "dayjs". Relative references must start with either "/","./", or "../." "

### What is Expected?
main.ts 引入 "dayjs/locale/zh-cn",  周起始日为星期一，而不是星期天

### What is actually happening?
main.ts 引入 "dayjs/locale/zh-cn", 使用 CDN 加载 “element-plus” ，周起始日还是 “星期天”

**Comment by sxzz** [comment]
Please provide a valid reproduction link (Github Repo link)

**Comment by beckZgh** [comment]
https://github.com/beckZgh/test-vite-element-plus
已将最少测试代码上传，可以下载下来，
1. 运行 dev 命令日期组件如预期设置一样，周一为起始日
2. 运行 build 命令使用 cdn 加载，周日为起始日
3. 将 vite.config.ts 的 cdn 引入 dayjs 的代码注释打开，会导致程序出错 （单独引入 （dayjs 或者 element-plus） 都可以）

**Comment by sxzz** [comment]
这个问题是 `vite-plugin-cdn-import` 和 `dayjs` 的配置问题，建议到 `vite-plugin-cdn-import` 的仓库问问。
