### ISSUE TITLE
[Bug Report] date-picker

### ISSUE THREAD

**Issue by chthu** [element-plus/element-plus#4519]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
ozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36'

### Vue version
3.2.22

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
按照官方引入，分隔符无效
<el-date-picker
            start-placeholder="Start date"
            :editable="false"
            range-separator="------"
            end-placeholder="End date"
            type="datetimerange"
            v-model="dateValue"
          >
            <template #range-separator>
              <span>-----</span>
            </template>
          </el-date-picker>

### What is Expected?
分隔符插槽生效，可以自定义图标

### What is actually happening?

分隔符插槽无效

**Comment by emojiiii** [comment]
Please provide a minimum reproduction link

**Comment by chthu** [comment]
A normal reference to this component, the range separator slot is not available
