### ISSUE TITLE
文档可否改成composititon api的写法

### ISSUE THREAD

**Issue by LadyChatterleyLover** [element-plus/element-plus#452]

**Comment by JeremyWuuuuu** [comment]
Sure, the documentation will be replaced in the next stage, when all of our components is ready, we will work on implementing that. And we will going to need some help for updating the documentations, if you want to be part of it, please let us know.

**Comment by LadyChatterleyLover** [comment]
of course, I really want to join you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午2:22
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 文档可否改成composititon api的写法 (#452)





 
Sure, the documentation will be replaced in the next stage, when all of our components is ready, we will work on implementing that. And we will going to need some help for updating the documentations, if you want to be part of it, please let us know.

**Comment by JeremyWuuuuu** [comment]
Nice, we will let you know when we about to do that.

**Comment by LadyChatterleyLover** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午2:26
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 文档可否改成composititon api的写法 (#452)





 
Nice, we will let you know when we do that.

**Comment by zazzaz** [comment]
@LadyChatterleyLover Great, actually you can start it today if you got some time. A kind reminder, the code in all four languages should be updated accordingilly.

**Comment by LadyChatterleyLover** [comment]
OK, how can I start？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午2:32
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 文档可否改成composititon api的写法 (#452)





 
@LadyChatterleyLover Great, actually you can start it today if you got some time. A kind reminder, the code in all four languages should be updated accordingilly.

**Comment by zazzaz** [comment]
@LadyChatterleyLover Any component is fine.

**Comment by LadyChatterleyLover** [comment]
OK, how can I put the written documents on the official website？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 晚上9:36
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 文档可否改成composititon api的写法 (#452)





 
@LadyChatterleyLover Any component is fine, maybe the one you like.

**Comment by zazzaz** [comment]
You can update the doc under `website/docs` via a pull request.

**Comment by LadyChatterleyLover** [comment]
ok, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 上午10:07
收件人:&nbsp;"element-plus/element-plus"<element-plus@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [element-plus/element-plus] 文档可否改成composititon api的写法 (#452)





 
You can update the doc under website/docs via a pull request.

**Comment by rottenpen** [comment]
I want to join it ! 
I had make a pull request to update Alert docs, and found event close not support any more. 
It turned into event click. Is it bug or feature？

**Comment by zazzaz** [comment]
@rottenpen Agreed. However, we should not update all the docs into VCA, it depends. More important, updating old syntax like slot to the new version to make all demos work is a high priority.

**Comment by rottenpen** [comment]
@zazzaz Are there any Todolist about it？

**Comment by zazzaz** [comment]
Good idea, I have opened a new issue here https://github.com/element-plus/element-plus/issues/540
