### ISSUE TITLE
Icon error css

### ISSUE THREAD

**Issue by laudaikinhdi** [element-plus/element-plus#4523]
When I upgrade 1.2.0-beta.3 then icon CSS error. Please check under picture
![image](https://user-images.githubusercontent.com/34116228/143258662-f615061d-3eb9-46e1-b848-bbb47a5a19fa.png)

**Comment by laudaikinhdi** [comment]
![image](https://user-images.githubusercontent.com/34116228/143260054-69bd223e-f92b-4744-a19a-6f61975e44c7.png)

**Comment by laudaikinhdi** [comment]
I know issue due conflict with reset CSS

**Comment by laudaikinhdi** [comment]
> ![image](https://user-images.githubusercontent.com/34116228/143260054-69bd223e-f92b-4744-a19a-6f61975e44c7.png)

In above picture sometimes reload page, class ".el-icon" place on class ".el-input__icon" => icon date error css
![image](https://user-images.githubusercontent.com/34116228/143514098-0f0cdc2a-6577-4ce2-a99a-c70ec60502d5.png)

**Comment by Liao123** [comment]
I also have this problem. Please solve it quickly

**Comment by sxzz** [comment]
Without reproduction link, we can't give any help.
Please provide a minimum reproduction link / repo and re-open this issue.
