### ISSUE TITLE
el-tree renderContent

### ISSUE THREAD

**Issue by helloworldx0001** [element-plus/element-plus#4532]
## The example given by the website is

      <el-tree
        :data="dataSource"
        show-checkbox
        node-key="id"
        default-expand-all
        :expand-on-click-node="false"
        :render-content="renderContent"
      />

    renderContent(h, { node, data, store }) {
      return h(
        'span',
        {
          class: 'custom-tree-node',
        },
        h('span', null, node.label),
        h(
          'span',
          null,
          h(
            'a',
            {
              onClick: () => this.append(data),
            },
            'Append '
          ),
          h(
            'a',
            {
              onClick: () => this.remove(node, data),
            },
            'Delete'
          )
        )
      )
    },

## In element-ui，If i wish render a el node, I can render like this

    renderContent(h, { node, data, store }) {
     return (
       <el-button

## In element-plus，How to render a el node，Can it be done like this

        return h(
          'el-row',
          {
            class: 'flex',
            ':gutter': 8
          },

**Comment by emojiiii** [comment]
if you registry the component, you can do it
