### ISSUE TITLE
[bug report] cascade selector. When the parent and child have the same value, the data cannot be loaded and selected by default

### ISSUE THREAD

**Issue by fonglezen** [element-plus/element-plus#4539]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Windows 10 / Chrome 版本 96.0.4664.45（正式版本） （64 位）

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/fonglezen/pen/XWavggg

### Steps to reproduce
在codepen https://codepen.io/fonglezen/pen/XWavggg 中复现，selected中的value相同，有问题。
selectedDiff的value不相同，则不存在该问题。
value在不同层级相同，是正常的业务场景。

### What is Expected?
当父子级value相同时，仍能正常加载和选中。

### What is actually happening?
当父子级value相同时，不能正常加载和选中，但是model有值。

**Comment by msidolphin** [comment]
并不认可你提到的value可以在不同层级相同 ，value应该是一个唯一值
