### ISSUE TITLE
[feature request] El select after selecting data or echo, do not empty the input, fill in the data, and fill in the input with the selected data

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#4540]
### Existing Component
是

### Component Name
el-select

### Description
希望el-select选择数据之后，上方的input输入框能够是已经选中的数据。并且非清空状态。同时回显的时候也拿对应的label值放在输入框。不会在点击打开的时候清空输入框的数据。

**Comment by msidolphin** [comment]
根据你的描述，这更像是bug
