### ISSUE TITLE
日期选择器键盘事件由 event.code 监控回车事件。小键盘回车事件无效。小键盘是 numpadenter。希望用e.key来判断或者加个numpadenter来判断。谢谢

### ISSUE THREAD

**Issue by Mr-city** [element-plus/element-plus#4545]

**Comment by Mr-city** [comment]
@Alanscut 可以添加一个numpadEnter的判断吗，表单全部加键盘事件后，按下numpadEnter 不能关闭日期，或者抛出一个手机关闭日期的属性

**Comment by Alanscut** [comment]
@Mr-city 这个pr里就是让enter和numpadEnter的行为一致，现在可以按下小键盘按键关闭弹出层了。

**Comment by Alanscut** [comment]
@Mr-city https://preview-4563-element-plus.surge.sh/en-US/component/date-picker.html#enter-date
这个网址中可以查看这个pr修改后的效果

**Comment by Mr-city** [comment]
@Alanscut 这个版本多久更新了，还有可以抛出一个手动关闭日期的属性吗

**Comment by Alanscut** [comment]
@Mr-city 我不理解为什么需要一个手动关闭日期的属性

**Comment by Mr-city** [comment]
@Alanscut 有一个业务场景，给form表单全部添加了键盘事件，上下左右加回车，按回车就定位到下一个，如果日期没输入值，按下回车定位到下一个，日期候选框是不会消失的，此时须要一个手动关闭的属性

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/143978247-2cfab65f-6aa6-47ed-acd0-756de950f811.png)

**Comment by Mr-city** [comment]
@Alanscut 这个事件不行，须手动执行一个blur方法，可以关闭日期
现在日期只有一个focus 方法

**Comment by Alanscut** [comment]
@Mr-city https://preview-4563-element-plus.surge.sh/en-US/component/date-picker.html#enter-date
你可以看一下现在，输入框为空时，可以直接使用enter关闭了。
