### ISSUE TITLE
How to setup global size when use unplugin-vue-components?

### ISSUE THREAD

**Issue by lwy1010** [element-plus/element-plus#4549]
I am using ```unplugin-vue-components```  plugin to on-demand Import componnets, but how i can setup global size for all components?  It just like ```app.use(ElementPlus, { size: "small" })``` in last version...  And it seems that there no size related configurations in el-config-provider component...

**Comment by sxzz** [comment]
Please refer to https://element-plus.org/en-US/guide/quickstart.html#global-configuration
```ts
import App from './App.vue'

app.config.globalProperties.$ELEMENT = {
  // options
}
```
