### ISSUE TITLE
[Feature Request] how could i setting auto placement in select options?

### ISSUE THREAD

**Issue by ZWkang** [element-plus/element-plus#4566]
### Existing Component
Yes

### Component Name
select

### Description
i want to setting the select options placement position what i want
i was used select component.
https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/select.vue#L15
this fallback-placements was hard code.

**Comment by Alanscut** [comment]
the position of options need be auto-changed by the position of  `select ` in the page

https://user-images.githubusercontent.com/21104054/144537408-941d0773-aef7-41b8-a3e8-56d44ce36799.mp4

**Comment by Alanscut** [comment]
你是有什么具体需求？

**Comment by ZWkang** [comment]
我看了一下 placement 现在是 hard code 了传到弹出层 Popover 上，这个透传的 Popover config 完全可以暴露给开发者呀。 
@Alanscut

**Comment by Alanscut** [comment]
传递到的是popper上，popper并不暴露给用户的。
其次就是我不觉得select这种选择器的弹出选项层有自定义位置的必要。

**Comment by ZWkang** [comment]
OK, closed
