### ISSUE TITLE
[Bug Report] el-menu warnings: [Vue warn]: Failed to resolve component: location

### ISSUE THREAD

**Issue by zhoufanglu** [element-plus/element-plus#4568]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
chrome

### Vue version
3.0.0

### Steps to reproduce
import el-menu
```html
    <el-menu
        :default-active="currentRoutePath"
        class="el-menu-vertical-demo"
        @open="handleOpen"
        @close="handleClose"
    >
      <el-sub-menu
          v-for="(menu,index) in menuList"
          :key="index"
          :index="menu.path">
        <!--title-->
        <template #title>
          <el-icon><location /></el-icon>
          <span>{{menu.meta.label}}</span>
        </template>
        <!--sub-title-->
        <el-menu-item
            v-for="(subMenu, index) in menu.children"
            :index="subMenu.path"
            :key="index"
            @click="menuItemClick(subMenu)"
        >{{subMenu.meta.label}}</el-menu-item>
      </el-sub-menu>
    </el-menu>

```
![image](https://user-images.githubusercontent.com/24451091/143835204-ddcb551d-fefa-40e9-ba64-fc4e6c951f34.png)

### What is actually happening?
`If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. `

**Comment by emojiiii** [comment]
please `import { location } from '@element-plus/icons'`, and registry this component

**Comment by zhoufanglu** [comment]
> please `import { location } from '@element-plus/icons'`, and registry this component

i try to `npm i @element-plus/icons`,
in vue
```js
import { location } from '@element-plus/icons'
export default {
  components: {
    location
  },
}
```
but..
![image](https://user-images.githubusercontent.com/24451091/143968228-5e17509c-9b2b-4d57-8648-c9b400a6034f.png)

**Comment by emojiiii** [comment]
may be `Location` ?

**Comment by emojiiii** [comment]
all icon components begin with uppercase, so may be try `Location` ?

**Comment by zhoufanglu** [comment]
> 

yes! is `Location`, The warning is gone
why import Location components?
I already used  
```js
//element-plus 自动引入插件
const Components = require('unplugin-vue-components/webpack')
const { ElementPlusResolver } = require('unplugin-vue-components/resolvers')
```
can you tell me? ji ni tai mei

**Comment by emojiiii** [comment]
Because `unplugin-vue-components/resolvers`  cannot be imported automatically in this version

**Comment by zhoufanglu** [comment]
> Because `unplugin-vue-components/resolvers` cannot be automatically import icon components in this version
thant you for your answer👏
