### ISSUE TITLE
[Feature Request] scrollbar on el-table not stick to the right side

### ISSUE THREAD

**Issue by schunlee** [element-plus/element-plus#4569]
### Existing Component
No

### Component Name
el-table

### Description
el-table, some times, have many columns, so have to set several columns fixed, 
and also several columns be hided (folded).
so here I want to set import columns to the right, once the table be loaded, scrollbar be drawn to the right side, see snippet below
```
scrollRight() {
      this.$nextTick(() => {
        var scroll_bar = document.getElementsByClassName(
          "el-table__body-wrapper"
        )[0];
        scroll_bar.scrollLeft = Number(
          this.$refs.tableList.bodyWidth.replace("px", "")
        );  
      });
    },
```
But, the scrollbar always not stick to the right side, always have a gap between.
https://i.imgur.com/Jwj00X1.png

**Comment by msidolphin** [comment]
what does "stick to the right side" mean?

**Comment by schunlee** [comment]
> what does "stick to the right side" mean?

I mean no gap between scrollbar and table's right border.
