### ISSUE TITLE
When Dropdown is too long

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#457]
![image](https://user-images.githubusercontent.com/38392315/96852831-35788580-148c-11eb-8301-06cf954455a1.png)
When Dropdown is too long, it looks like this.
Hope that dropdown can set a max-height, or like the style of select component.
![image](https://user-images.githubusercontent.com/38392315/96853012-6e185f00-148c-11eb-8abc-fed79e81cc63.png)

**Comment by zouhangwithsweet** [comment]
In fact, dropdown is used for a small number of options. I don't think this is a bug.
