### ISSUE TITLE
When [bug report] value format = "X", shouldn't model value also accept parameters of type number

### ISSUE THREAD

**Issue by awagege** [element-plus/element-plus#4572]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
mac 12

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-sp2ys?file=/src/App.vue

### Steps to reproduce
el-date-picker 组件既然都支持 value-format="x" 了，就不应该限制 model-value 的参数类型不是number吧？
虽然运行时可以解析
但开发时控制台报warning
 [Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Date | Array | String, got Number with value 1637251200000. 

### What is Expected?
为date-picker model-value放开number| number[]传参类型

### What is actually happening?
目前model-value 只接受 Date | Array | String

**Comment by emojiiii** [comment]
think you, this warning will be removed when refactor `date-picker`
