### ISSUE TITLE
[bug report] change theme color

### ISSUE THREAD

**Issue by TangTangJia** [element-plus/element-plus#4573]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
 95.0.4638.69

### Vue version
3.2.16

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-sp2ys?file=/src/App.vue

### Steps to reproduce
/styles/element/index.scss   

@forward 'element-plus/theme-chalk/src/common/var' with (
  $colors: (
    primary: (
      base: #07aea0
    )
  )
);

main.js   

import './styles/element/index.scss'

vite.config.js   

import ElementPlus from 'unplugin-element-plus/vite'
  plugins: [
    vue(),
    ElementPlus({
      useSource: true
    }),
    Components({
      resolvers: [ElementPlusResolver()]
    })
  ]

### What is Expected?
根据配置实现自定义主题色

### What is actually happening?
修改了主题色不生效

**Comment by XingXiaoWu** [comment]
Try this one
```
import path from "path";
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: "@use '@/styles/element-variables.scss' as *; ",
      }
    }
  },
  plugins: [
    vue(),
    Components({
      resolvers: [
        ElementPlusResolver({
          importStyle: "sass",
        })
      ],
    })
  ],
 
})

```

**Comment by enoshima7** [comment]
> Try this one
> 
> ```
> import path from "path";
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import Components from 'unplugin-vue-components/vite'
> import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   resolve: {
>     alias: {
>       "@": path.resolve(__dirname, "src"),
>     },
>   },
>   css: {
>     preprocessorOptions: {
>       scss: {
>         additionalData: "@use '@/styles/element-variables.scss' as *; ",
>       }
>     }
>   },
>   plugins: [
>     vue(),
>     Components({
>       resolvers: [
>         ElementPlusResolver({
>           importStyle: "sass",
>         })
>       ],
>     })
>   ],
>  
> })
> ```

this works in full-import mode,but not in on-demand import mode
