### ISSUE TITLE
[bug report] CDN language resource 404

### ISSUE THREAD

**Issue by bigbigtime** [element-plus/element-plus#4579]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
win10/Chrome 96.0.4664.45（正式版本） （64 位）

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/youthful-mclaren-9orm3

### Steps to reproduce
1、public/index.html 引入语言资源
<script src="//unpkg.com/element-plus/dist/locale/zh-cn"></script>
2、src/main.js注入
  createApp(App).use(ElementPlus, {
    locale: ElementPlus.lang.zhCn
  })

// unpkg资源Not found
1、https://unpkg.com/browse/element-plus@1.1.0-beta.24/es/locale/lang/zh-cn.js；
2、UNPKG右则Version下拉选项切换1.2.0-bea.1、1.2.0-bea.2、1.2.0-bea.3、1.2.0-bea.4，均404；

### What is Expected?
UNPKG右则Version下拉选项切换1.2.0-bea.1、1.2.0-bea.2、1.2.0-bea.3、1.2.0-bea.4可以获取正确资源

### What is actually happening?
无法找到资源

**Comment by msidolphin** [comment]
After 1.2.0 version you need to change to mjs
eg: 
https://unpkg.com/browse/element-plus@1.2.0-beta.1/es/locale/lang/zh-cn.mjs

**Comment by code-farmer-i** [comment]
> After 1.2.0 version you need to change to mjs eg: https://unpkg.com/browse/element-plus@1.2.0-beta.1/es/locale/lang/zh-cn.mjs

文档中还是错误的示例 https://element-plus.gitee.io/zh-CN/guide/i18n.html#cdn-%E7%94%A8%E6%B3%95

**Comment by emojiiii** [comment]
@msidolphin  i look `locale` doesn't seem to have `UMD` format, and CDN can't be used?
