### ISSUE TITLE
[Bug Report] el-form-item router.push after valid

### ISSUE THREAD

**Issue by DeibyRo** [element-plus/element-plus#4580]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Mac os

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-hvs9r?file=/src/Form.vue:1615-1620

### Steps to reproduce
1. Click on the submit form button
2. Error in the console TypeError: elForm.removeField is not a function

### What is Expected?
After validation, the form is expected to push the router to the desired page.

### What is actually happening?
When sending the form through the composition api, the console throws the error Uncaught (in promise) TypeError: elForm.removeField is not a function,

Looking for the origin, I arrive at the file form-item.vue

 onBeforeUnmount(() => {
      elForm == null ? void 0 : elForm.removeField(elFormItem);
    });

This only happens with the composition api

**Comment by DeibyRo** [comment]
![Screen Shot 2021-11-30 at 12 29 25 PM](https://user-images.githubusercontent.com/8366868/144097612-03e199c1-05fa-4bbb-911d-2e22527c021b.png)

**Comment by hlbj105** [comment]
```
  <el-form-item>
    <el-button type="primary" @click="submit()" :loading="loading"
      >Login</el-button
    >
  </el-form-item>
```
It needs to be within ` <el-form> </el-form>`
