### ISSUE TITLE
[Bug Report] El-menu collapse or expand is not work

### ISSUE THREAD

**Issue by TgT982474256** [element-plus/element-plus#4588]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
96.0.4664.45

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/TgT982474256/pen/qBPBYyQ

### Steps to reproduce
el-menu expand and collapse don't work after upgrade element-plus/1.2.0-beta.4 
but using 1.2.0-bata.3 is ok

### What is Expected?
el-menu should expand or collapse

### What is actually happening?
if collapse  default  false,the collapse don't work,and collapse default true,the expand don't work

**Comment by janey2018** [comment]
I have the same problem.

**Comment by janey2018** [comment]
create project 
and then `npm install element-plus@1.2.0-beta.3` 
The module "vue" or its corresponding type declaration could not be found

**Comment by janey2018** [comment]
Reinstalling the latest version will fix the problem
