### ISSUE TITLE
[Bug Report] table sortable bug

### ISSUE THREAD

**Issue by code-farmer-i** [element-plus/element-plus#4589]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Chrome

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/code-farmer-i/pen/NWaWBNE

### Steps to reproduce
点击三下排序按钮

### What is Expected?
sort-change 回调中 sortable.column  sortable.prop 不为 null

### What is actually happening?
sort-change 回调中 sortable.column sortable.prop 为 null

**Comment by code-farmer-i** [comment]
element-ui 相关问题 https://github.com/ElemeFE/element/pull/15012

**Comment by vela666** [comment]
vue2 版本都是正常的  vue3版本就出现这个  没有排序时 参数都没了(多列排序都不能实现了)

**Comment by MidTin** [comment]
请问这个bug什么时候能修复？

**Comment by sosilence** [comment]
So, any plan to fix the bug? It's really make a trouble when sorting.
