### ISSUE TITLE
[Bug Report] 1.2.0-beta.4  Error - Cannot find module 'element-plus/es/utils/types'

### ISSUE THREAD

**Issue by zhiw-wang** [element-plus/element-plus#4591]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Any

### Vue version
3.2.23

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
//bash

 yarn add element-plus

//main.ts

 import ElementPlus from 'element-plus'
 import 'element-plus/dist/index.css'
 createApp(App).use(ElementPlus)

//bash

 build

element-plus@1.2.0-beta.4/es/utils/types.d.ts   File does not exist on npm and all cdn.
Only types.mjs and types.mjs.map files exist

### What is Expected?
Done

### What is actually happening?
error TS2307: Cannot find module 'element-plus/es/utils/types' or its corresponding type declarations.

**Comment by zhiw-wang** [comment]
![Uploading 截屏2021-11-30 18.25.02.png…]()

**Comment by zhiw-wang** [comment]
<img width="1175" alt="截屏2021-11-30 18 25 02" src="https://user-images.githubusercontent.com/43452320/144030605-0b081766-c49d-42bd-8b5d-43b87e6f96ba.png">

**Comment by emojiiii** [comment]
duplicate #4558
