### ISSUE TITLE
[Bug Report] 1.2.0-beta.1~1.2.0-beta.4 —Build Error

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#4592]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
macOS/Chrome latest

### Vue version
3.2.23

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
// main.ts
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
app.use(ElementPlus) 
// npm run serve
no error, everything well;
// npm run build
ERROR in /*******************/node_modules/@vueuse/shared/index.d.ts(35,5): 
35:5 Property or signature expected.
    33 |  */
    34 | declare type RemovableRef<T> = Omit<Ref<T>, 'value'> & {
  > 35 |     get value(): T;
       |     ^
    36 |     set value(value: T | null | undefined);
    37 | };
    38 | /**
error  in /*******************/node_modules/@vueuse/shared/index.d.ts
35:9 ';' expected.
    33 |  */
    34 | declare type RemovableRef<T> = Omit<Ref<T>, 'value'> & {
  > 35 |     get value(): T;
       |         ^
    36 |     set value(value: T | null | undefined);
    37 | };
    38 | /**
............ same error as front

### What is Expected?
build complete

### What is actually happening?
build fail

**Comment by sxzz** [comment]
Please provide a minimum reproduction link and reopen this issue.

**Comment by wuchaoxin** [comment]
你需要更新你的 typescript 版本
You need to update your typescript version
https://github.com/vueuse/vueuse/issues/876
