### ISSUE TITLE
[Bug Report] Docs [el-menu] name incorrect

### ISSUE THREAD

**Issue by Artsmp** [element-plus/element-plus#4602]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
windows/edge

### Vue version
3.2.23

### Reproduction Link
jsfiddle

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/menu.html#%E4%BE%A7%E6%A0%8F

### What is Expected?
[el-sub-menu] need to transform [el-submenu] 

### What is actually happening?
Failed to resolve component: el-sub-menu， It's actually another name

**Comment by emojiiii** [comment]
The component is now named `Camel-Case`, so this is not wrong

**Comment by CarterLi** [comment]
It should be `el-sub-menu` instead of `el-submenu`
