### ISSUE TITLE
[bug report] the icon size in the component does not change with the size of the component

### ISSUE THREAD

**Issue by bwangs** [element-plus/element-plus#4604]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Windows10/Chrome 96.0.4664.45（正式版本）（64 位）

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-t3843?file=/src/App.vue

### Steps to reproduce
使用ElButton等组件得icon属性

### What is Expected?
组件内的图标应该随着组件的size的变化而变化

### What is actually happening?
带有图标的组件，比如  ElInput、ElButton、ElDatePicker等组件，在设置 了size后，组件内的图标是固定大小，而字号是变化的大小

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
I create https://github.com/element-plus/element-plus/issues/4604 two days ago. 

We need a little time to find out if there are any potential bugs. Just wait next version, thanks.
