### ISSUE TITLE
[Bug Report] i18N in el-form rules

### ISSUE THREAD

**Issue by oooowl** [element-plus/element-plus#4609]
### Element Plus version
1.2.0-beta.3

### Vue version
3.2.22

### Reproduction Link
https://stackblitz.com/edit/github-9ukebr-4khdvj?file=layouts%2Fdefault.vue

### What is actually happening?
In nuxt3 ,set el-config-provider locale to zhCn, but message still was english

**Comment by emojiiii** [comment]
i18N don't support rule error message within the `ElForm` component
