### ISSUE TITLE
[Bug Report] el-dialog errors in nuxt3

### ISSUE THREAD

**Issue by oooowl** [element-plus/element-plus#4612]
### Element Plus version
1.2.0-beta.3

### Vue version
3.2.22

### Reproduction Link
https://stackblitz.com/edit/github-9ukebr-qawjrf?file=pages%2Findex.vue

### What is actually happening?
el-dialog errors in nuxt3
el-dialog not work at first render , and render two el-button

**Comment by sxzz** [comment]
https://stackblitz.com/edit/github-9ukebr-k95pyk?file=layouts%2Fdefault.vue

```diff
<style scoped>
* {
  box-sizing: border-box;
}
</style>

<template>
---  <el-container>
    <el-container>
      <el-main>
        <slot></slot>
      </el-main>
    </el-container>
---  </el-container>
</template>

<script setup></script>

```
