### ISSUE TITLE
[Bug Report] <el-pagination> is buggy

### ISSUE THREAD

**Issue by CarterLi** [element-plus/element-plus#4617]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
N/A

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/CarterLi/pen/WNZbEmG

### Steps to reproduce
<el-pagination ... layout="total" :total="1000" />

### What is Expected?
Total 1000

### What is actually happening?
Total {total}

https://github.com/element-plus/element-plus/pull/4253 @sxzz

**Comment by CarterLi** [comment]
What about add a unit test?

**Comment by sxzz** [comment]
@CarterLi PR welcomed
