### ISSUE TITLE
[Feature Request] Add Stylus files

### ISSUE THREAD

**Issue by InfoLibre** [element-plus/element-plus#4621]
### Existing Component
Yes

### Component Name
Element 

### Description
It's interesting to have a release for Sass, Stylus ans Less, like Fomantic-UI.

https://github.com/fomantic/Fomantic-UI-CSS

https://github.com/fomantic/Fomantic-UI-LESS

https://github.com/fomantic/Fomantic-UI-SASS

fomantic/Fomantic-UI#2152

Developers don't have to learn a new CSS preprocessor syntax for their project.

https://github.com/mojotech/sass2stylus

**Comment by sxzz** [comment]
Currently this project has css and sass. What are the advantages of doing this?

**Comment by InfoLibre** [comment]
It's interesting for contributors and users who know Stylus or Less and don't want to learn cSass/SCSSS.
