### ISSUE TITLE
[Feature Request] After Upload component "file-list" attributes  is assigned, it will automatically request background file resources. It need to use custom headers 

### ISSUE THREAD

**Issue by nocmt** [element-plus/element-plus#4626]
### Existing Component
Yes

### Component Name
Upload

### Description
This is a very common requirement. I verify the token of the back-end image or file resources, but when I edit a group of data, the file list is given the uploaded file address array. It will automatically initiate a get request without using the headers parameter I defined.

This makes it impossible to preview.

**Comment by sxzz** [comment]
Could you please give a example?
