### ISSUE TITLE
[Feature Request] How to change the background-color of el-pagination?

### ISSUE THREAD

**Issue by siriusdemon** [element-plus/element-plus#4627]
### Existing Component
Yes

### Component Name
pagination

### Description
The default color iof a highlighting pager in el-pagination is blue. Is there a way to change it? Such as pass the color as attr?

**Comment by Mrly0** [comment]
<style>
.el-pager li.active {
	background-color: red !important;
}
</style>

**Comment by siriusdemon** [comment]
Thanks. @Mrly0 It works.

And I have found that declaring a local variable with the same name as the global one works too. It will not only change the background but also the text.

**Comment by siriusdemon** [comment]
override the variable locally.
```html
<template>
  <div id="Pagination">
    <el-pagination class="flex items-center"
        background
        layout="prev, pager, next"
        :page-size="pageSize"
        :total="total">
    </el-pagination>
  </div>
</template>

<style>
#Pagination {
  --el-color-primary: rgb(157, 22, 22);
}
</style>
````
