### ISSUE TITLE
When the [bug report] [El table] has a fixed column, the body content does not exceed, and when Max height, the append content cannot be displayed (there is no upper and lower scroll bars)

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#4628]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
win11

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/mxp131011/pen/mdByNPG

### Steps to reproduce
`el-table` 添加 `max-height`   某个 `el-table-column` 添加 `fixed="left"`  然后添加 `<template #append></template>` 
当不算`#append` 的高度没有超过`max-height`高度时（`#append`加上`el-table-column`已经超过 `max-height`时不显示滚动条，所以导致看不到`#append` 的内容）

具体请看我的例子

### What is Expected?
`el-table` 有上下滚动条

### What is actually happening?
`el-table` 没有有上下滚动条

**Comment by mxp131011** [comment]
使用场景时表格做无线滚动是想让用户看到 加载中 没有更多数据 等状态

**Comment by emojiiii** [comment]
@msidolphin cc
