### ISSUE TITLE
[bug report] scrolling position error when the cascader component is selected

### ISSUE THREAD

**Issue by CarlXu94** [element-plus/element-plus#4630]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
chrome

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-5ktqh?file=/src/App.vue

### Steps to reproduce
场景一

1.选择label为2的选项

2.选择最后一个选项，会发现滚动位置会跳到label为2的选项

场景二

1.全选label为1的子项

2.选择label为7的一个子项，出现滚动位置跳到label为1的选项，且子集切换为label为1的子集

### What is Expected?
希望正常切换

在cascader-panel组件的scrollToExpandingNode方法获取active的节点逻辑似乎一直是获取第一个is-active的节点，在支持多选的情况下这个逻辑处理似乎有问题

### What is actually happening?
切换有问题

**Comment by Alanscut** [comment]
@CarlXu94 可以改用config变量而不使用对象字面量来避免这个问题
![cascader](https://user-images.githubusercontent.com/21104054/144813942-bf46c0a2-b440-4e54-bb21-8c316cee894c.png)
