### ISSUE TITLE
[bug report] dropdown menu text offset

### ISSUE THREAD

**Issue by zhixiaotong** [element-plus/element-plus#4631]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chrome

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/zhixiaotong/pen/xxXGbNz

### Steps to reproduce
看此链接，一样的效果。
https://element-plus.gitee.io/zh-CN/component/dropdown.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95。
查看了一下，应该是里面的伪类样式影响。

### What is Expected?
正常

### What is actually happening?
不正常

**Comment by zhixiaotong** [comment]
![image](https://user-images.githubusercontent.com/34681550/144374433-384cfd51-7815-407e-83e9-9bf624d835a3.png)

**Comment by zhixiaotong** [comment]
@YunYouJun

**Comment by zhixiaotong** [comment]
同时还有另一个问题，我看了你们现在直接在button上添加了var变量的style赋予颜色，如果切换主题，这个颜色应该是不会变的，刷新页面才会生效，应该怎么处理它呢？

**Comment by valardie** [comment]
.el-dropdown-menu__item设置 display: block; 覆盖掉display: flex;就好了，好像就是加了display: flex;导致的

**Comment by YunYouJun** [comment]
I create #4638 to fix this. Thanks.

**Comment by YunYouJun** [comment]
> 同时还有另一个问题，我看了你们现在直接在button上添加了var变量的style赋予颜色，如果切换主题，这个颜色应该是不会变的，刷新页面才会生效，应该怎么处理它呢？

这部分目前参考了下 naiveui 的做法，即通过内联样式的方式，来根据样式自动计算按钮的 hover/active 等颜色。
切换主题的话可以借助 vue 的 inject 方案来，全局控制传递给用户的色彩变量即可。
此外，直接设置 css-var 如 `--el-color-primary` 也是可以的，因为会读取此处变量来动态计算内联样式。

当然最后这些配置，我们应该会抽取到 el-config-provider 里，来允许更方便地自定义主题。

**Comment by zhixiaotong** [comment]
> > 同时还有另一个问题，我看了你们现在直接在button上添加了var变量的style赋予颜色，如果切换主题，这个颜色应该是不会变的，刷新页面才会生效，应该怎么处理它呢？
> 
> 这部分目前参考了下 naiveui 的做法，即通过内联样式的方式，来根据样式自动计算按钮的 hover/active 等颜色。 切换主题的话可以借助 vue 的 inject 方案来，全局控制传递给用户的色彩变量即可。 此外，直接设置 css-var 如 `--el-color-primary` 也是可以的，因为会读取此处变量来动态计算内联样式。
> 
> 当然最后这些配置，我们应该会抽取到 el-config-provider 里，来允许更方便地自定义主题。

那我等最后的效果吧，现目前先不改动了，辛苦~
