### ISSUE TITLE
there  are error  in   el-pagination  of    Total {total}

### ISSUE THREAD

**Issue by jzfai** [element-plus/element-plus#4632]
look for   https://element-plus.gitee.io/zh-CN/component/pagination.html#附加功能

![image](https://user-images.githubusercontent.com/35098590/144375554-50005d3e-01c9-406b-b6c6-7c940a8cb470.png)

**Comment by btea** [comment]
Duplicate #4617

**Comment by sxzz** [comment]
Duplicate of #4617. Fix in #4619
