### ISSUE TITLE
[Bug Report] [input-number] extra update event

### ISSUE THREAD

**Issue by littleboarx** [element-plus/element-plus#4636]
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Windows

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/littleboarx/pen/rNGVVoQ

### Steps to reproduce
when enter you see a message info
and when to set the number value to 2 you will see two message

### What is Expected?
no extra event

### What is actually happening?
extra event when reaching to min/max 
in my project, it will make a Vue Error like:
"onUpdated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
  at <ElInputNumber model-value=1 min=1 onUpdate:modelValue=fn<bound edit> > 
..."

**Comment by Alanscut** [comment]
@littleboarx if you set `number=2` (just not equal to min-value), it will not make vue warn

**Comment by littleboarx** [comment]
> @littleboarx if you set `number=2` (just not equal to min-value), it will not make vue warn
yep

**Comment by Alanscut** [comment]
i will try to fix it

**Comment by Alanscut** [comment]
just a problem caused by a '='
