### ISSUE TITLE
[Bug Report] <el-button> type not change reactively

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#4637]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
macOS

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/lemonade1/pen/ZEXGbeZ

### Steps to reproduce
<el-button> type not change reactively when click different radio

### What is Expected?
<el-button> type change with click different radio

### What is actually happening?
<el-button> type not change reactively

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by Alanscut** [comment]
#4744
