### ISSUE TITLE
[Feature Request] el-select create new items option support custom template

### ISSUE THREAD

**Issue by bchen1029** [element-plus/element-plus#4639]
### Existing Component
Yes

### Component Name
el-select

### Description
I have an idea about component el-select.
When props `allow-create` is `true`
Make the el-option created by user custom input can also support custom template.(e.g. add an icon as a suffix)
Maybe can improve user experience.
If it sound fine, I will open PR for it. thx.

**Comment by chenxch** [comment]
@bchen1029 Thank you very much for your contribution, if there is no progress I will close it first.
