### ISSUE TITLE
[Bug Report] el-dropdown-item with "divided" can't display properly

### ISSUE THREAD

**Issue by molun01** [element-plus/element-plus#4649]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Win10

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/molun/pen/YzrXEyq

### Steps to reproduce
官方文档中的Dropdown 下拉菜单展开

### What is Expected?
文字居中显示

### What is actually happening?
带有 divided 属性的 el-dropdown-item ，文字显示偏左有遮挡

**Comment by btea** [comment]
Duplicate #4631
