### ISSUE TITLE
alert 框显示有问题

### ISSUE THREAD

**Issue by wike2019** [element-plus/element-plus#465]
![image](https://user-images.githubusercontent.com/5925704/97146026-20f4ff80-17a2-11eb-8b83-ca5e11537607.png)
一直不显示

**Comment by JeremyWuuuuu** [comment]
Could you give us a least reproducible repo or online preview version here? A link to the repo is appreciated, a fragment of your code is cool as well.
A issue like this is not going to help us to know whatever the bug is.
