### ISSUE TITLE
[Feature Request] Cascader select any level of options

### ISSUE THREAD

**Issue by swatch17** [element-plus/element-plus#4653]
### Existing Component
Yes

### Component Name
Cascader

### Description
When the parents node is selected,it can not be selected.The child node will be loaded by default. The parent node can be selected only after the child node is loaded
`
  //node.vue_vue_type_script_lang.mjs
const handleCheck = (checked) => {
      doCheck(checked);
      // if (!props.node.loaded) {
      //   doLoad();
      // } else {
      //   doCheck(checked);
      //   !checkStrictly.value && doExpand();
      // }
    };
![image](https://user-images.githubusercontent.com/17958903/144563846-22d84d4f-6ece-46cd-8efa-6f4a1b284732.png)

`

**Comment by swatch17** [comment]
级联选择任意一级选项时，在单项选择模式时，选择父节点时父节点没有被选中而是加载了子节点，自己点加载完成后才能选择上一级父节点，查看源码时看到判断了loaded属性

**Comment by Alanscut** [comment]
#4182
