### ISSUE TITLE
[Feature Request] Automatically replace current file in el-upload

### ISSUE THREAD

**Issue by y3lousso** [element-plus/element-plus#4655]
### Existing Component
Yes

### Component Name
el-upload

### Description
Currently, when using el-upload with multiple=false and auto-upload=false, you need to click the cross to remove the currently imported file first before importing a new file. And there is no error/warning when you try to upload another, it just does nothing. There seem to be 2 solutions:
1. Either disable the upload button when multiple=false and a file is already being imported
2. Or automatically replace the previous file when upload anew (without having to remove it first)

Our UX design recommends 2nd choice but I have not look into feasibility to be honest.

**Comment by emojiiii** [comment]
I think the current API is sufficient to implement both solutions
If you choose the second solutions, you can remove the previously selected files when `the change event` trigger

**Comment by gadfly3173** [comment]
sth like this

```vue
<template>
  <el-upload
    ref="logoUploader"
    drag
    action=""
    :limit="1"
    :show-file-list="false"
    :http-request="uploadLogoFile"
    :on-change="handleLogoUploaderChange"
    :on-exceed="handleLogoUploaderExceed"
  >
</template>
<script>
export default {
  methods: {
    handleLogoUploaderExceed(files) {
      this.$refs.logoUploader.clearFiles()
      this.$refs.logoUploader.handleStart(files[0])
    },
    handleLogoUploaderChange() {
      this.$refs.logoUploader.clearFiles()
    },
    async uploadLogoFile(file) {
      // your request
    },
  }
}
</script>
```

**Comment by y3lousso** [comment]
Let's close this issue then 👍

**Comment by y3lousso** [comment]
I guess I closed it too soon: https://codepen.io/y3lousso/pen/MWEwNOK?editors=1010

With the onExceed event, you can't access the newly imported file, hence you can't replace it.
And onChange is not called when limit is reached

**Comment by emojiiii** [comment]
yep, I think this may be a problem.   I've been refactoring `Upload` recently. I'll think about how to implement this function！

**Comment by emojiiii** [comment]
I think adding an `on-before-change` hook can solve your problem. What do you think?

**Comment by y3lousso** [comment]
I guess that would work

**Comment by Alanscut** [comment]
@y3lousso 
With the onExceed event, you can access the newly imported file.
you can use console.log to see it instead of  push in a logs
![image](https://user-images.githubusercontent.com/21104054/146297445-67db0ed1-d1e7-4371-988c-97169d648425.png)

https://user-images.githubusercontent.com/21104054/146297454-2d8302b0-7b78-4357-893b-e188688f5832.mp4


![image](https://user-images.githubusercontent.com/21104054/146297697-55efab45-5d6b-45ee-a90b-4a67e6e5a75a.png)

**Comment by emojiiii** [comment]
> With the onExceed event, you can access the newly imported file.
> you can use console.log to see it instead of push in a logs

You are right, but the method in the component is not recommended

**Comment by Alanscut** [comment]
> > With the onExceed event, you can access the newly imported file.
> > you can use console.log to see it instead of push in a logs
> 
> You are right, but the method in the component is not recommended

you mean use `clearFiles() `and `handleStart()`?

**Comment by emojiiii** [comment]
> > > With the onExceed event, you can access the newly imported file.
> > > you can use console.log to see it instead of push in a logs
> > 
> > 
> > You are right, but the method in the component is not recommended
> 
> you mean use `clearFiles() `and `handleStart()`?

`handleStart`, Because this method is not described in the document, it may be changed

**Comment by gadfly3173** [comment]
> `haeStart`, Because this method is not described in the document, it may be changed

If only the document is cited, this function cannot be realized. I think this method is also available on Vue2, and some blogs recommend it. Maybe there is a better way.

**Comment by emojiiii** [comment]
> > `haeStart`, Because this method is not described in the document, it may be changed
> 
> If only the document is cited, this function cannot be realized. I think this method is also available on Vue2, and some blogs recommend it. Maybe there is a better way.

yep, I just don't recommend it, but it's not prohibited
