### ISSUE TITLE
[Feature Request] class definition of ElTableColumn like element-ui

### ISSUE THREAD

**Issue by jackjtr** [element-plus/element-plus#4658]
### Existing Component
是

### Component Name
el-table-column

### Description
We need a ElTableColumn class to extend like element-ui

[table-column.d.ts](https://github.com/ElemeFE/element/blob/dev/types/table-column.d.ts)

```js
/** TableColumn Component */
export declare class ElTableColumn extends ElementUIComponent {
  /** Type of the column. If set to `selection`, the column will display checkbox. If set to `index`, the column will display index of the row (staring from 1). If set to `expand`, the column will display expand icon. */
  type: TableColumnType

  /** Column label */
  label: string

  /** Column's key. If you need to use the filter-change event, you need this attribute to identify which column is being filtered */
  columnKey: string

  /** Field name. You can also use its alias: property */
  prop: string

  ...
}
```

**Comment by sxzz** [comment]
The type definition already exists. Please use Volar.
https://unpkg.com/browse/element-plus@1.2.0-beta.5/es/components/table/src/table-column/index.d.ts

**Comment by jackjtr** [comment]
Volar installed but still not working 

![image](https://user-images.githubusercontent.com/6552755/144692897-f90ec0f7-852c-4564-998f-b500efae07fe.png)

**Comment by sxzz** [comment]
`typeof ElTableColumn`

**Comment by jackjtr** [comment]
tried but it doesn't work. :(

![image](https://user-images.githubusercontent.com/6552755/144699092-7a01ce7a-d616-4b2b-84f9-891d35066648.png)

**Comment by sxzz** [comment]
`ElTableColumn` is a component type, so you can't extends it directly. You can try to create a new component and extends it.

**Comment by jackjtr** [comment]
We just want to extend the data structrue of el-table-column's props.
