### ISSUE TITLE
[Bug Report]  [el-input-number]  step prop raises native form validation error.

### ISSUE THREAD

**Issue by codespikex** [element-plus/element-plus#4672]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
macos / chrome 96.0.4664.55

### Vue version
3.2.23

### Reproduction Link
https://jsfiddle.net/vxbjas13/1/

### Steps to reproduce
1. Enter any number in two decimal places in the el-input-number component.
2. Click submit.

### What is Expected?
The el-input-number component should not raise any native form validation error for values with decimal places when step prop is defined. 

### What is actually happening?
Unable to submit the form because the el-input-number component is causing the native form validation to fail.

**Comment by Alanscut** [comment]
If you want to use `el-input-number` in  `native form`, you should keep `step ` and  `precision ` corresponding
