### ISSUE TITLE
[Bug Report] style override for On-demand Import order

### ISSUE THREAD

**Issue by LoveofRedMoon** [element-plus/element-plus#4676]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
Chrome newest

### Vue version
3.2.23

### Reproduction Link
Should use vite and in developer mode.
![image](https://user-images.githubusercontent.com/35391556/144772896-009f1399-ae65-4b2f-bfee-0ba50263c365.png)
![image](https://user-images.githubusercontent.com/35391556/144772932-39d41ff8-a3c4-4353-871b-65a088c755cf.png)

May should upgrade the importance of .el-input__icon

### What is Expected?
The icon in input should 'display: flex'

### What is actually happening?
The icon in input shows 'display: inline-block'

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Can you provide a reproducible example?

**Comment by LoveofRedMoon** [comment]
> Can you provide a reproducible example?

https://github.com/LoveofRedMoon/issue_element-plus-4676

```bash
npm i && npm run dev
```

**Comment by YunYouJun** [comment]
Thanks. I create a PR #4684 to fix it temporarily by `!important`.
