### ISSUE TITLE
switch has outline

### ISSUE THREAD

**Issue by BeADre** [element-plus/element-plus#468]
![image](https://user-images.githubusercontent.com/34639100/97162821-b00e1180-17ba-11eb-8fc8-573616401d04.png)

**Comment by Ther-su** [comment]
I think the problem is related to the component tooltip, because when I remove the tooltip in that case, the bug disappeared.

**Comment by JeremyWuuuuu** [comment]
This is fixed in #469 but the changes might take a period of time to get published since we do not have any publishing plan recently.
