### ISSUE TITLE
[bug report] dropdown drop-down menu basic user menu 5 style display error

### ISSUE THREAD

**Issue by AprilTong** [element-plus/element-plus#4686]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
macOS 11 / Google Chrome 96

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/zhirong/pen/OJxMWpb

### Steps to reproduce
打开官网：https://element-plus.gitee.io/zh-CN/component/dropdown.html
基础用户： <el-dropdown-item divided>Action 5</el-dropdown-item> 
展示错误

### What is Expected?
 <el-dropdown-item divided>Action 5</el-dropdown-item>
展示正常

### What is actually happening?
展示错误

![image](https://user-images.githubusercontent.com/24354441/144803999-6a03bc86-daa3-4bd5-933a-2aa791ef6348.png)

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Thanks. I think it has fixed by https://github.com/element-plus/element-plus/pull/4638 .
Just wait next release.
