### ISSUE TITLE
[bug report] when El menu is used, the collapse is true, and the rendering of the third-party icon library fails,

### ISSUE THREAD

**Issue by Songyakang** [element-plus/element-plus#4690]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Chrome  96.0.4664.45

### Vue version
3.2.24

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-yotor?file=/src/App.vue

### Steps to reproduce
https://codesandbox.io/s/element-plus-spa-forked-yotor?file=/src/App.vue

### What is Expected?
 el-icon内的图标应当正常渲染

### What is actually happening?
使用的第三方图标库IconPark渲染出来的图标外层套了span标签导致被隐藏

**Comment by August-Rushme** [comment]
When rendering third-party icons, replace `< span > with < i >` and set `collapse-transition = false`  to temporarily solve the problem.
