### ISSUE TITLE
[Bug Report] El Message Box default focus

### ISSUE THREAD

**Issue by xSpoooK** [element-plus/element-plus#4691]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chromium 96.0.4664.45

### Vue version
3.2.24

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-dje7g

### Steps to reproduce
Click on the 'click' button.

### What is Expected?
Click on the button, the message box is opened, nothing is focused by default

### What is actually happening?
Click on the button, the message box is opened, confirmButton is focused by default

Colors : 
Red is unfocused and yellow is focused.

![Animation](https://user-images.githubusercontent.com/16560108/144913974-b64fe0c5-731c-438d-961a-b22f5b981a1e.gif)

**Comment by emojiiii** [comment]
This is not a bug. Autofocus is to close the Dialog when you enter
