### ISSUE TITLE
[Feature Request] DateTimePicker supports prefix  slots 

### ISSUE THREAD

**Issue by laizuan** [element-plus/element-plus#4701]
### Existing Component
Yes

### Component Name
DateTimePicker/DatePicker

### Description
I want to support the select prefix slot, because that's what it ElSelect

**Comment by Alanscut** [comment]
Do you mean you want to replace the icon with custom content?
![image](https://user-images.githubusercontent.com/21104054/145165318-e6e66741-e207-41f0-b181-900066379d85.png)

**Comment by laizuan** [comment]
Yes. I'd like to have both if I can

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/145318041-e45263e1-23fc-4897-ae32-daf2a390a650.png)
![image](https://user-images.githubusercontent.com/21104054/145318084-fa80e641-0193-4e74-bd52-1674f7a1c1e5.png)
This feature already exists，use `prefix-icon`

**Comment by Alanscut** [comment]
It is achieved through `<component :is=""/>` inside

**Comment by laizuan** [comment]
Oh, my God, that's weird.  Well, that would solve my problem, too
