### ISSUE TITLE
[Bug Report] el-icon and vue-json-pretty at the same time error

### ISSUE THREAD

**Issue by LastKing** [element-plus/element-plus#4703]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
MacOs 11.6.1/Chrome 96.0.4664.55

### Vue version
3.2.23

### Reproduction Link
https://github.com/toonew-study/vue-issue-demo

### Steps to reproduce
1. pnpm install
2. npm run dev
3. open browser  --> localhost:3000
4. chrome dev tool  show

   Uncaught TypeError: isFunction is not a function
      at defineComponent (runtime-core.esm-bundler.js:1529)
      at Aim.js:3

### What is Expected?
1. el-icon can show
2. vue-json-pretty component show  json data view

### What is actually happening?
i don't known what.
This is simple demo. It have not complex logic code.

**Comment by LastKing** [comment]
Element-plus 1.1.0-beta.24  don't have the question

**Comment by sxzz** [comment]
You can temporarily use `@element-plus/icons-vue` instead `@element-plus/icons`.

**Comment by sxzz** [comment]
The new package docs will release in the next version.

**Comment by LastKing** [comment]
Can You add some document...

I don't search the `@element-plus/icons-vue` in document...

Others may have the same question.

Thank you for your help.
