### ISSUE TITLE
defineComponent breaks webstorm-parsing of component tags

### ISSUE THREAD

**Issue by jbrosi** [element-plus/element-plus#471]
Somehow it seems that when defining components with defineComponent like this:

https://github.com/element-plus/element-plus/blob/e01ae5f9352a895d2c8d019398a9d0eddf586d83/packages/card/src/index.vue#L14-L16

Webstorm (latest version 2020.2.3) is not able to identify those components as valid tags in the templates. However when a component is defined like here:

https://github.com/element-plus/element-plus/blob/e01ae5f9352a895d2c8d019398a9d0eddf586d83/packages/date-picker/src/date-picker.ts#L34-L35

Webstorm can recognize it (including full props). As a test i removed the "return defineComponent" from the card and directly returned object as in date picker and all the sudden webstorm could recognize card as well.

Not sure if that bug belongs more to webstorm itself - but as it seems the "defineComponent" is not important anyhow (both versions seem to compile and run) and code is shorter without..., it could also be removed here i guess.

// disclaimer: i'm completely new to vue / element-plus sorry if it doesn't make any sense

**Comment by zazzaz** [comment]
This might because Websotrom has not updated to parse the new syntax of Vue 3.0 yet. I use Vscode with Vetur plugin, and it works fine as expected.

**Comment by JeremyWuuuuu** [comment]
I am not a WebStorm user, if you want full type checking feature, you might need to install some plugin (I dunno if there were any), maybe `Vetur` has its WebStorm version?

**Comment by jbrosi** [comment]
Thank you for your answers. The most common plugin (installed by default) is the vue plugin by jetbrains themselves. So the defineComponent is new for the v3 vue? :/ guess i in fact have to wait then until they update. Thought eventually it's just "more verbose" or even old style of writing here and can be omitted, as some of the components have it, some don't.

**Comment by JeremyWuuuuu** [comment]
So the `defineComponent` API is essentially for enabling IDE support like `VS Code`. I think it will just be fine if your IDE supports `TypeScript`, this API brings type annotations for the users to define their components with correct syntax (the syntax for defining a component have been made breaking. 
If your IDE does not work for this API, you might try it with `VS Code` which is also a **powerful** editor with plugins, make sure that you install `Vetur` provided by Vue.js offical.

**Comment by jbrosi** [comment]
Alright thank you for the support, I understand now, so it's definitely not an option to leave out the defineComponent here. Will open bug ticket with jetbrains and hope they update the plugin soon :). Will try out vs code in the meantime (but would love to be able to continue using my favorite IDE).

**Comment by JeremyWuuuuu** [comment]
NP, glad that I could help.
