### ISSUE TITLE
[bug report] if the page number of pagination component is greater than 7, jump to the last page and report an error

### ISSUE THREAD

**Issue by swatch17** [element-plus/element-plus#4712]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chrome 96.0.4664.45

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/swatch17/pen/JjrXXjN

### Steps to reproduce
1.当页码大于7页，比如100页，点击最后一页，页表条展示数据错误。
2.在本地开发环境没有问题，如果构建后发布线上，点击最后一页就会报错。
3.如果在源码中将 const startPage = pageCount - (pagerCount - 2)直接放在循环条件中，则不会报错

### What is Expected?
分页跳转最后一页正确

### What is actually happening?
仅仅只会在打包完成后的文件中报错，定位
![image](https://user-images.githubusercontent.com/17958903/145029321-dff63033-ffec-4b6f-817a-4b95a2ab3720.png)
![image](https://user-images.githubusercontent.com/17958903/145029419-6de0cdea-2089-476f-9626-aae022e3acf8.png)
![image](https://user-images.githubusercontent.com/17958903/145030405-c7b9b936-d980-41e4-865d-6dfeb9bf6c97.png)
![image](https://user-images.githubusercontent.com/17958903/145030471-ea9cfd6b-4dc7-4713-ad03-4ff84dc7e840.png)
![image](https://user-images.githubusercontent.com/17958903/145031008-ed3987cc-0c42-4a4d-b5bb-7004ab4a9f14.png)

**Comment by swatch17** [comment]
问题已解决由于@vue/cli-service 4.5.x版本依赖包terser-webpack-plugin版本太低(1.4.4),更新到4.2.3就解决了

**Comment by btea** [comment]
好的，那这个issue我关了
