### ISSUE TITLE
[bug report] dropdown plus divided dislocation

### ISSUE THREAD

**Issue by 360060316** [element-plus/element-plus#4714]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Dropdown 加 divided 后错位

### Vue version
3.2.24

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/656/

### Steps to reproduce
Dropdown 加 divided 后错位

### What is Expected?
Dropdown 加 divided 后错位

### What is actually happening?
Dropdown 加 divided 后错位

**Comment by btea** [comment]
Duplicate #4686
