### ISSUE TITLE
[Bug Report]  Cannot find type definition file for 'element-plus/global'

### ISSUE THREAD

**Issue by roy8800** [element-plus/element-plus#4716]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Windows 10

### Vue version
3.2.24

### Steps to reproduce

use ts Volar support and auto import

https://element-plus.org/en-US/guide/quickstart.html#full-import

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "importHelpers": true,
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["esnext", "dom"],
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "/@/*": [
        "src/*"
      ]
    },
    "types": ["element-plus/global"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "exclude": ["node_modules", "dist", "**/*.js"]
}

```

then run tsc cli 

```
tsc --noEmit
```

or vue-tsc at the project

```
npx vue-tsc --noEmit
```

it will show error.

### What is Expected?
build success

### What is actually happening?
```
error TS2688: Cannot find type definition file for 'element-plus/global'.
  The file is in the program because:
    Entry point of type library 'element-plus/global' specified in compilerOptions

  tsconfig.json:22:15
    22     "types": ["element-plus/global"]
                     ~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.
```

Actually vscode show same error at tsconfig.json

i have to create a `tsconfig.prod.json`

```json
{
  "extends":"./tsconfig.json",
  "compilerOptions": {
    "types":[]
  }
}
```

and then run `vue-tsc --noEmit --project tsconfig.prod.json`

It can run successful.

**Comment by tolking** [comment]
``` diff 
+ "include": ["node_modules/element-plus/global.d.ts"]
```

**Comment by roy8800** [comment]
> 

Template hint will be invalid.(TS 4.4.3)

![image](https://user-images.githubusercontent.com/94855817/145156268-acbca8ed-bfd7-48b8-8992-d631095bf01b.png)

**Comment by tfn290181662** [comment]
@tolking 

![image](https://user-images.githubusercontent.com/92365265/145167548-60f33c46-cbce-4742-af8e-91bd68f7e980.png)

**Comment by tolking** [comment]
@tfn290181662 Types file of some components are missing, this is a BUG

```diff
{
  "compilerOptions": {
+    "skipLibCheck": true,
  }
}

```

**Comment by roy8800** [comment]
I found a solution.

like this https://github.com/vitejs/vite/blob/main/packages/create-vite/template-vue-ts/src/env.d.ts

add

```ts
 /// <reference types="element-plus/global" />
```

but the lastest vscode ts version is 4.5.2,the global componet hints will no effect

i have to copy element-plus/global.d.ts code into env.d.ts

**Comment by sxzz** [comment]
Please refer to https://github.com/element-plus/element-plus-playground . 

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext", "DOM"],
    "module": "ESNext",
    "rootDir": ".",
    "baseUrl": ".",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "outDir": "dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "types": ["element-plus/global", "vite/client"]
  },
  "include": ["src/**/*"]
}
```
```jsonc
//package.json
"devDependencies": {
	  "typescript": "4.5.2",
	  "vue-tsc": "0.29.8"
}
```

**Comment by tao1874** [comment]
I encountered the same problem
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "allowJs": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["node", "element-plus/global", "vite/client"],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "type-css.d.ts",
    "src/views/service-repository/components/depend/tree.js"
  ],
  "exclude": ["node_modules"]
}

```
all components of element-plus have no types.
usage by full Import

![image](https://user-images.githubusercontent.com/34742839/145530371-6de04c50-eabe-43b4-b755-32722f070aff.png)

**Comment by sxzz** [comment]
Try `element-plus/global.d.ts` please

**Comment by sxzz** [comment]
Please try this temporarily, it may be a problem with vue-tsc.
```ts
"./node_modules/element-plus/global"
```

**Comment by sxzz** [comment]
Please upgrade `element-plus`, `vue-tsc`, `typescript` to latest version.

**Comment by sxzz** [comment]
You can refer to https://github.com/element-plus/element-plus-issue-helper/blob/main/tsconfig.json .

**Comment by roy8800** [comment]
> ```ts
> ./node_modules/element-plus/global
> ```

it;s OK now with ts 4.5.2
