### ISSUE TITLE
[Bug Report] The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#4719]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Linux version 4.18.0-305.7.1.el8_4.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC))

### Vue version
3.2.24

### Reproduction Link
not in browser

### Steps to reproduce
`pnpm install ../element-plus`

```
Packages:  294
            
Progress: resolved 311, reused 294, downloaded 0, added 0, done
 ERR_INVALID_ARG_TYPE  The "path" argument must be of type string. Received undefined
```

### What is Expected?
I just want to install the package locally.

### What is actually happening?
The "path" argument must be of type string. Received undefined

**Comment by sxzz** [comment]
Try to add `'element-plus': '../element-plus'` to `package.json` please
