### ISSUE TITLE
[Bug Report] ElDatePicker prop 'default-value' is not reactive

### ISSUE THREAD

**Issue by ljq108** [element-plus/element-plus#4720]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chrome

### Vue version
3.2.24

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-6lljl?file=/src/App.vue

### Steps to reproduce
set input value and clear after 2000ms.

### What is Expected?
'defaultValue' in picker expect to change,but not.

### What is actually happening?
'defaultValue' seems lose reactivity when destructure

![imgae](https://user-images.githubusercontent.com/56781101/145149898-8e7f34d4-f160-4e56-a239-6d80646e040f.png)

**Comment by Alanscut** [comment]
if you want to modify the value after `setTimeout`, why not use `modelValue`？

**Comment by ljq108** [comment]
> if you want to modify the value after `setTimeout`, why not use `modelValue`？

我可能表达的不太清楚，我是要修改`default-value`绑定的值，对应到视图就是改变picker打开时显示的默认日期(见图)，然而修改`defaultValue`的值后并没有响应到视图，这在vue2的element-ui是没有问题的。
![微信图片_20211209180002](https://user-images.githubusercontent.com/56781101/145375442-1e907708-9bef-4e41-830f-ce7e584474ca.png)
我大概看了下el-date-picker组件的代码，上面图中`pickerBase.props`是个reactive对象，解构出来的`defaultValue`自动解包变成字符串了，所以也失去响应性了，而我修改value再清空是为了触发`getDefaultValue()`，因为源码中是这样写的:
![微信图片_20211209175730](https://user-images.githubusercontent.com/56781101/145374766-d02cfb83-c68c-4ae1-a784-74e9fc36c773.png)

**Comment by Alanscut** [comment]
> > if you want to modify the value after `setTimeout`, why not use `modelValue`？
> 
> 我可能表达的不太清楚，我是要修改`default-value`绑定的值，对应到视图就是改变picker打开时显示的默认日期(见图)，然而修改`defaultValue`的值后并没有响应到视图，这在vue2的element-ui是没有问题的。 ![微信图片_20211209180002](https://user-images.githubusercontent.com/56781101/145375442-1e907708-9bef-4e41-830f-ce7e584474ca.png) 我大概看了下el-date-picker组件的代码，上面图中`pickerBase.props`是个reactive对象，解构出来的`defaultValue`自动解包变成普通对象了，所以也失去响应性了，而我修改value再清空是为了触发`getDefaultValue()`，因为源码中是这样写的: ![微信图片_20211209175730](https://user-images.githubusercontent.com/56781101/145374766-d02cfb83-c68c-4ae1-a784-74e9fc36c773.png)

有一个细节，现阶段`defaultValue`设置之后对应视图上可以看到年份和月份的区别，但是日期是没有显示的。你截图中圈出的那个蓝色日期字体9代表的是`today`

**Comment by ljq108** [comment]
> > > if you want to modify the value after `setTimeout`, why not use `modelValue`？
> > 
> > 
> > 我可能表达的不太清楚，我是要修改`default-value`绑定的值，对应到视图就是改变picker打开时显示的默认日期(见图)，然而修改`defaultValue`的值后并没有响应到视图，这在vue2的element-ui是没有问题的。 ![微信图片_20211209180002](https://user-images.githubusercontent.com/56781101/145375442-1e907708-9bef-4e41-830f-ce7e584474ca.png) 我大概看了下el-date-picker组件的代码，上面图中`pickerBase.props`是个reactive对象，解构出来的`defaultValue`自动解包变成普通对象了，所以也失去响应性了，而我修改value再清空是为了触发`getDefaultValue()`，因为源码中是这样写的: ![微信图片_20211209175730](https://user-images.githubusercontent.com/56781101/145374766-d02cfb83-c68c-4ae1-a784-74e9fc36c773.png)
> 
> 有一个细节，现阶段`defaultValue`设置之后对应视图上可以看到年份和月份的区别，但是日期是没有显示的。你截图中圈出的那个蓝色日期字体9代表的是`today`

好的，谢谢
