### ISSUE TITLE
[bug report] for multiple selection tables, when UI refresh occurs on the page, the check box will be selected twice, once selected and once cancelled

### ISSUE THREAD

**Issue by ZhouXinQin** [element-plus/element-plus#4728]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
win10 / 版本 92.0.4515.131（正式版本） （64 位）

### Vue version
3.2.24

### Reproduction Link
jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
设置 type = selection  将选中的值弄成响应式的，然后在当前页面显示出选中的值

### What is Expected?
进行一次选中，不取消

### What is actually happening?
会进行两次选中,一次选中，一次取消

**Comment by emojiiii** [comment]
can you provide a mini repo ?
