### ISSUE TITLE
demo Dialog is not work, some compontents is not work

### ISSUE THREAD

**Issue by xlanghejianfeng** [element-plus/element-plus#473]

**Comment by JeremyWuuuuu** [comment]
Please provide detailed error for us in order to track the issue, BTW, I just got a screenshot from the website, which works perfectly for me.
![image](https://user-images.githubusercontent.com/15975785/97276001-9bd91b80-1871-11eb-9f77-322ad5664b50.png)

**Comment by BeADre** [comment]
The reason might be this #475

**Comment by yingjie-design** [comment]
> The reason might be this #475

use English doc 查看,不选中文查看就可以。

**Comment by JeremyWuuuuu** [comment]
This should be fixed in #650 closing due to it's fixed.
