### ISSUE TITLE
[Bug Report] Incorrect typing for modelValue of DatePicker

### ISSUE THREAD

**Issue by websmurf** [element-plus/element-plus#4731]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
OSX/Chrome

### Vue version
3.2.24

### Reproduction Link
https://jsfiddle.net/Lzg0e96p/4/

### Steps to reproduce
Use el-date-picker in the following manner: https://jsfiddle.net/Lzg0e96p/4/

Then try to create a build, this causes the following error:

```
 - error TS2322: Type 'string[]' is not assignable to type 'string | Date | Date[] | undefined'.
  Type 'string[]' is not assignable to type 'Date[]'.
    Type 'string' is not assignable to type 'Date'.
```

### What is Expected?
Functionally, everything works as expected, a build fails on the error above though.

So the expectation is that this command works without error:
`vue-tsc --noEmit --skipLibCheck`

### What is actually happening?
`vue-tsc --noEmit --skipLibCheck` 

causes this error:

```
 - error TS2322: Type 'string[]' is not assignable to type 'string | Date | Date[] | undefined'.
  Type 'string[]' is not assignable to type 'Date[]'.
    Type 'string' is not assignable to type 'Date'.
```

**Comment by websmurf** [comment]
As a workaround; cast the v-model binding:

```
v-model="range as any"
```

This will at least allow you to create builds of your app/library

**Comment by btea** [comment]
You can use like this
```ts
const dateRange = ref([new Date("2021-01-01"), new Date("2021-12-31")])
```

**Comment by websmurf** [comment]
True, but the output of the component is a string as well; so that conflicts with the input

**Comment by btea** [comment]
Yeah，you are right, I'll fix it

**Comment by websmurf** [comment]
> I tried it and triggered the change event, the output value is Date. Can you provide the scene you mentioned?

If you set a `value-format`; then the output will be a string value :-)

**Comment by websmurf** [comment]
@sxzz thanks!

**Comment by SepVeneto** [comment]
https://codepen.io/sepveneto/pen/gOGGXPO

1. open `console`
2. select times

when set a `value-format`, the `modelValue` will output `string[]`, but its type can only be (number | Date)[]
