### ISSUE TITLE
[Feature Request] [el-popconfirm] More customization options

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#4733]
### Existing Component
是

### Component Name
Popconfirm

### Description
目前按钮可控制颗粒度不够细，目前只有默认的 button 和 button primary ，不能控制按钮的 loading 和 type，比如 支持 danger 。比如确认删除按钮，我们希望 danger 和 loading，loading结束再 clouse弹窗

**Comment by emojiiii** [comment]
If you need these functions, I think you should use `eldialog` to implement them yourself
