### ISSUE TITLE
[Bug Report] [El-Menu] renders without active item when items and activeIndex are dynamic values.

### ISSUE THREAD

**Issue by Xing-He** [element-plus/element-plus#4735]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
MAC OS, V15

### Vue version
3.2.16

### Reproduction Link
https://jsfiddle.net/i-am-tired-of-this/seriously

### Steps to reproduce
use Menus with dynamic values for default-active and items, I looked up the source code and found two `watch` functions as follows

```js
watch(() => props.defaultActive, (currentActive) => {
      if (!items.value[currentActive]) {
        activeIndex.value = "";
      }
      updateActiveIndex(currentActive);
});

watch(items.value, () => initMenu());
```

After debugging, I found the first watch always be invoked by defaultActive's change, but the `items` still hold the `old values`.
So. `activeIndex` will get a value of undefined after `updateActiveIndex` executed. 

```js
const updateActiveIndex = (val) => {
      const itemsInData = items.value;
      const item = itemsInData[val] || activeIndex.value && itemsInData[activeIndex.value] || itemsInData[props.defaultActive];
      
     // item is undefined
      if (item) {
       // ...
      } else {
        if (!alteredCollapse.value) {
          activeIndex.value = void 0;
        } else {
         // ...
        }
      }
    }
```
as the second watch invoked, method `initMenu` will be called now. Unfortunately *activeIndex.value is undefined*

### What is Expected?
render correctly.

### What is actually happening?
render without correct active item.

**Comment by emojiiii** [comment]
can you provide a mini repo?
