### ISSUE TITLE
[Bug Report] El-Button background is not reactive

### ISSUE THREAD

**Issue by damiankoper** [element-plus/element-plus#4744]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Linux / Chrome 96

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/kopernick/pen/wvrWyeR

### Steps to reproduce
Click on the warning button

### What is Expected?
The button changes color to `info` and its shape to a circle.

### What is actually happening?
The button does not change color to `info` but its shape is reactive.

**Comment by Alanscut** [comment]
Thanks. I think it has fixed by #4637 .
Just wait next release.
