### ISSUE TITLE
[docs] Some component documents report property errors!

### ISSUE THREAD

**Issue by Sphinm** [element-plus/element-plus#475]
### Components behavior
- [Cascader](https://element-plus.org/#/zh-CN/component/cascader) 
![image](https://user-images.githubusercontent.com/16483962/97267648-71816100-1865-11eb-840c-32c811621527.png)

- [Upload](https://element-plus.org/#/zh-CN/component/upload)
![image](https://user-images.githubusercontent.com/16483962/97267735-9bd31e80-1865-11eb-8644-5721b974d983.png)

- [Transfer](https://element-plus.org/#/zh-CN/component/transfer)
![image](https://user-images.githubusercontent.com/16483962/97267809-c329eb80-1865-11eb-8f32-bb430645681e.png)

### Expectation
> The component document is previewed normally and no error is reported

**Comment by JeremyWuuuuu** [comment]
Hi, @Sphinm 
We are still in progress and some components haven't been implemented yet, or the documentation haven't been updated yet, so the error was expected but certainly not correct, we also need help for updating the documentation.
For now we have 3 components on the way, right after the end of migration, we will begin working on documentations immediately.
Sorry for the inconvenience that we made.

**Comment by Sphinm** [comment]
> Hi, @Sphinm
> We are still in progress and some components haven't been implemented yet, or the documentation haven't been updated yet, so the error was expected but certainly not correct, we also need help for updating the documentation.
> For now we have 3 components on the way, right after the end of migration, we will begin working on documentations immediately.
> Sorry for the inconvenience that we made.

Got it~

**Comment by Ryan2128** [comment]
I will update `Transfer`'s docs today, the reason of errors is syntax of slots.

**Comment by zazzaz** [comment]
fixed, thanks
