### ISSUE TITLE
[Bug Report] Pagination props 'total'

### ISSUE THREAD

**Issue by atpsoul** [element-plus/element-plus#4758]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
chorme 96.0.4664.93

### Vue version
3.2.24

### Reproduction Link
https://codepen.io/atpsoul/pen/WNZGbLJ

### Steps to reproduce
111

### What is Expected?
Total {total}

### What is actually happening?
Total 400

**Comment by emojiiii** [comment]
Duplicate of #4617. Fix in #4619
