### ISSUE TITLE
[Feature Request] How to customize the slot of table filters?

### ISSUE THREAD

**Issue by bytrix** [element-plus/element-plus#4787]
### Existing Component
Yes

### Component Name
Table

### Description
I need to customize the table filter's UI, what should I do?

**Comment by iamkun** [comment]
![正确提示]()

**Comment by emojiiii** [comment]
try use `slot` 
please see [docs](https://element-plus.gitee.io/zh-CN/component/table.html#table-column-%E6%8F%92%E6%A7%BD)
