### ISSUE TITLE
[Bug Report] el-skeleton's :throttle propertity is useless

### ISSUE THREAD

**Issue by wensc1996** [element-plus/element-plus#4804]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-l0ptw?file=/src/App.vue:109-118

### Steps to reproduce
Just Look

### What is Expected?
The skeleton screen appears continuously according to the throttle time

### What is actually happening?
If the data request is fast, the skeleton screen will flash, and after the throttle is set, the skeleton screen will not be displayed

**Comment by Alanscut** [comment]
When the data has arrived, why still show the skeleton?

**Comment by wensc1996** [comment]
> When the data has arrived, why still show the skeleton?

The data request is too fast, and the skeleton flashes by. I just want to stay for a longer period of time to improve the skeleton effect.

**Comment by luzhe0359** [comment]
> 

I also met a similar problem. Have you solved it?

**Comment by wensc1996** [comment]
> > > When the data has arrived, why still show the skeleton?
> > 
> > 
> > The data request is too fast, and the skeleton flashes by. I just want to stay for a longer period of time to improve the skeleton effect.
> 
> I also met a similar problem. Have you solved it?

Not yet, nobody cares.

**Comment by fzu-kwz** [comment]
I also met this problem in version 2.3.3, but not found any method yet
