### ISSUE TITLE
[Bug Report] Collapsed menu can't close popover by clicking an item in mobile device

### ISSUE THREAD

**Issue by joo1es** [element-plus/element-plus#4806]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome 95

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/joo1es/pen/MWEbVqb

### Steps to reproduce
use mobile device and click the '1' menu => then click any item.
it might because of touch and click events do the same thing.

### What is Expected?
close the popover

### What is actually happening?
it flash and popover can't be closed

**Comment by zhangbin1010** [comment]
I have the same problem

**Comment by xiaoxian521** [comment]
Do not consider compatible mobile terminals, welcome pr if necessary
