### ISSUE TITLE
[Bug Report] el-form中使用el-select和时间选择器，status-icon去不掉

### ISSUE THREAD

**Issue by xixidaa** [element-plus/element-plus#4823]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
macos12.0.1 / chrome  96.0.4664.55(arm64)

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/Xixidaa/pen/xxXgOeP

### Steps to reproduce
带有校验功能的el-form使用el-select和时间选择器

### What is Expected?
status-icon置为false取消组件的status-icon

### What is actually happening?
默认会显示status-icon，且无法清除，status-icon置为false对上述两个组件无效

**Comment by Boolean-true** [comment]
![image](https://user-images.githubusercontent.com/43428088/147219089-57cdbdb5-b772-40f2-9213-a5c998b92c09.png)
![image](https://user-images.githubusercontent.com/43428088/147219102-8a344505-dcdd-44fe-8435-0a9b0a8c2598.png)
难受
