### ISSUE TITLE
[Bug Report] How to override scss with Node Sass ?

### ISSUE THREAD

**Issue by Yee1014** [element-plus/element-plus#4826]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
MacOS 12.0.1 / Microsoft Edge  96.0.1054.43 (x86_64)

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-lhhi9

### Steps to reproduce
override primary base value “red”

### What is Expected?
button primary style is red

### What is actually happening?
not work, button style is origin

**Comment by emojiiii** [comment]
please remove `import "element-plus/theme-chalk/index.css"`, because you need to use sass
