### ISSUE TITLE
[Feature Request] 修改--el-color-primary 的值后希望通过--el-color-primary 生成的例如--el-color-primary-light-1的值也发生变化

### ISSUE THREAD

**Issue by tongxin-77** [element-plus/element-plus#4836]
### Existing Component
Yes

### Component Name
element-plus

### Description
修改--el-color-primary 的值后希望通过--el-color-primary 生成的例如--el-color-primary-light-1的值也发生变化

**Comment by fairySusan** [comment]
会发生变化啊

**Comment by fairySusan** [comment]
我遇到的问题是：
App.vue 添加全局配置后
  <el-config-provider :locale="locale"> -->
    <router-view></router-view>
  </el-config-provider>

替换主题色失效了

**Comment by tongxin-77** [comment]
> 会发生变化啊

我是动态修改的

**Comment by shenxingchao** [comment]
[需要生成色阶函数，网上给你个链接](https://juejin.cn/post/7024025899813044232#heading-1)

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by free-pan** [comment]
@tongxin-77 这个方案暂时解决了该问题 [简单编写vite插件, 实现element plus动态主题切换](https://juejin.cn/post/7031404130128101384/) 你可以参考下

**Comment by YunYouJun** [comment]
目前网页并不存在监听 CSS Var 变动的事件，即便存在，添加监听的性价比也是不划算的。

您可以通过 SCSS 设置变量，来自动生成色彩的不同状态。
可参见：https://github.com/element-plus/element-plus-vite-starter
