### ISSUE TITLE
[Bug Report] tooltip style disordered while opening again before disappear

### ISSUE THREAD

**Issue by heruns** [element-plus/element-plus#4837]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
96.0.4664.93

### Vue version
3.2.22

### Reproduction Link
https://codepen.io/chaorun/pen/gOGgJWL

### Steps to reproduce
1. hover on the button, the tooltip shows fine
2. mouse leave from the button, tooltip is going to disappear
3. hover again before the tooltip disappear, the arrow and popper of tooltip will at wrong place

If it's not  reproduce, try more times by hover and mouse leave quickly on the button.

if I set  `:hide-after="0" transition="no-transition"` on the el-tooltip, this bug will not produce, but without any animation.

### What is Expected?
fix the bug

### What is actually happening?
tooltip style disordered

![image](https://user-images.githubusercontent.com/20581745/146114390-f0aa90bc-204b-40cc-9353-41ee2b3fb5dd.png)

**Comment by emojiiii** [comment]
fix in #4907
