### ISSUE TITLE
栅格数和栅格属性对象貌似不起作用

### ISSUE THREAD

**Issue by ziqiangxu** [element-plus/element-plus#484]
https://element-plus.gitee.io/#/zh-CN/component/layout

栅格数和栅格属性对象貌似不起作用
![image](https://user-images.githubusercontent.com/18530271/97314909-1ec69a00-18a3-11eb-8839-af4172570740.png)

**Comment by Ther-su** [comment]
Indeed,I found that the media search did't work for the css.
![image](https://user-images.githubusercontent.com/57524062/97344774-319d9680-18c4-11eb-976c-a5288a74ddd2.png)
And I find the the css about col is like that after I use scss compiler to manage it.
![image](https://user-images.githubusercontent.com/57524062/97344542-d9ff2b00-18c3-11eb-84c2-32e7792d5cfb.png)
It seemed that have an extra bracket.

**Comment by Ther-su** [comment]
However,after I change the code like this. 
![image](https://user-images.githubusercontent.com/57524062/97387633-608e2980-1911-11eb-83bf-ca8ee448257e.png)
![image](https://user-images.githubusercontent.com/57524062/97387646-64ba4700-1911-11eb-9810-97eab8f07dec.png)
And the the css is like this after compiler.
![image](https://user-images.githubusercontent.com/57524062/97387749-93382200-1911-11eb-9d85-3fadfcfcf362.png)
But the media still not work. It seemed that the css about media is't import.
Can someone give me some advice?Was I thinking the wrong way to solve this bug?

**Comment by JeremyWuuuuu** [comment]
Well, one way to find out your assumption is by searching in DevTools see if any of these got loaded into DOM.

**Comment by zazzaz** [comment]
@ziqiangxu  Thanks, this should be a bug in the css bundle, will fix it today.

**Comment by JeremyWuuuuu** [comment]
Since we have switched `node-sass` to `dart-sass`, there were some sort syntax breaking changes between these 2 different compiler. The bug is fixed in #489, @zazzaz could you please make a publish ASAP?

**Comment by zazzaz** [comment]
Fixed in `element-plus@1.0.1-alpha.11`
