### ISSUE TITLE
el-table style 'user-select:none' should be optional

### ISSUE THREAD

**Issue by trydofor** [element-plus/element-plus#4840]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Mac

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-b1q2j?file=/src/App.vue

### Steps to reproduce
1) select rows with head
2) copy selection to clipboard
3) past them into excel
4) the head is copied, but the style 'user-select:none' looks like unselected

### What is Expected?
same as element 2 el-table 
remove style 'user-select:none' or make it optional

### What is actually happening?
style 'user-select:none' make `head` look like unselected but the head is really selected

**Comment by emojiiii** [comment]
you can use `header slot` to customize the header

**Comment by trydofor** [comment]
这个设定为了什么呢？明显和element2 行为不一致，也不太符合table一致性。
解决办法覆盖css比 slot简单，提issue只是希望 element有更好的一致性

``` css
th.el-table__cell {
  user-select: text !important;
}
```
