### ISSUE TITLE
[Feature Request] 关于Element Plus的“Vue3”兼容性问题

### ISSUE THREAD

**Issue by timi137137** [element-plus/element-plus#4848]
### Existing Component
No

### Component Name
All

### Description
很简单的问题，根据Vue3官方文档显示，需要在组件文件中使用[defineComponent](https://v3.cn.vuejs.org/guide/typescript-support.html#%E5%AE%9A%E4%B9%89-vue-%E7%BB%84%E4%BB%B6)去定义this类型，而ele文档中全体组件（至少我看见的地方）全部都是Vue2的写法，如果不使用TS不会报错，但是一旦使用TS会全部爆炸，“TS2339: Property '$refs' does not exist on type '”，也就是this指向错误，如果各位大佬无法复现，那麻烦各位大佬更新文档，使用Vue3正确写法。感谢各位

**Comment by emojiiii** [comment]
Duplicate of #4839

**Comment by timi137137** [comment]
> Of course, I think we can move on to more elegant examples. Just like #4845 and #4801.

在用
![image](https://user-images.githubusercontent.com/36812439/146191163-0b233d4f-5263-4c1f-98d5-c592123357c7.png)
有人说
![image](https://user-images.githubusercontent.com/36812439/146191207-0f19fc78-feb6-4eba-bb2b-c43ffea04735.png)

**Comment by timi137137** [comment]
并且，有问题请不要全丢给用户，并不是所有用户都是高级前端工程师，而是普通的码农，thank you Senior Engineer

**Comment by emojiiii** [comment]
i'm sorry, I'll finish it as soon as possible

**Comment by sxzz** [comment]
@timi137137 
1. 我说的「补齐了」是指 .d.ts 的类型声明。请看清楚上下文，这不是一码事，不要莫名其妙 cue 我。
2. 使用 `defineComponent` 应该是 Vue 3 最基础的知识，Element Plus 只有**文档**，而不是**教程**。这么基础的问题，应该是每个会 Vue 3 的用户应该掌握的。所以即使文档不写 `defineComponent` 也应该知道要加上。例子的主要作用是供用户快速了解 Element Plus 的使用方式，对于 Vue 本身的使用不在 Element Plus 文档的主要范畴内。
3. Element Plus 是开源社区一起维护起来的。靠的是大家的帮助和努力，如果你觉得 Element Plus 不好，你可以选择让他变得更好或者不要使用。你是 Element Plus 的用户，而**不是**客户，请不要摆出一副你是客户的姿态。
4. 如果你觉得以你的知识不够解决或处理某些问题，那么就去学，而不是要求他人必须为你着想。社区没有这个义务和责任。

**Comment by HerringtonDarkholme** [comment]
感谢试用Element Plus。如果您有使用问题，欢迎尝试 https://www.zhihu.com/consult 向开发者提问，或提出拉取请求贡献文档。谢谢！

**Comment by gadfly3173** [comment]
vue3 文档中提到的官方 vscode 插件 volar 在 0.29 之前要求使用`defineComponent`时必须加上`lang=ts`，否则就是满屏幕的蓝色波浪，说明 vue3 官方一开始并不认为使用js的时候还需要 `defineComponent`，而且`defineComponent`这个api也是在 TypeScript 支持页面里提到的，而不是一开始就在 options api 里就有提到，vue3 自己的文档里也没有到处使用它。

**Comment by timi137137** [comment]
@sxzz 
1.截图不是我给的，只是有个“群友”说你更新了能用，我放上来而已。
![image](https://user-images.githubusercontent.com/36812439/146319813-6fd8e005-1359-42b2-b6d2-35a1023a3716.png)
![image](https://user-images.githubusercontent.com/36812439/146319832-074f06bc-18b9-4872-9e52-6a7ccca767c5.png)
![image](https://user-images.githubusercontent.com/36812439/146319862-6c4199ed-51a5-42cb-aad6-7265bc1a329f.png)
2.我承认这是我的问题，从Vue2迁移到Vue3并未完全熟悉使用Vue3以及了解Vue3的改动，这点非常抱歉，我在此道歉
3.这点我只感觉到开发者们到底多厉害，遇到反馈问题收到的只有
![image](https://user-images.githubusercontent.com/36812439/146320162-4e022c1b-bb19-43e9-8c22-ae0208436a76.png)
用户群体中并不是所有人都跟你们一样非常懂，也有我这种懂一些不懂一些的人，遇到问题查找百度等平台找不到结果，自然会提出issue，然后我所看见的是：你提了Issue那你自己修 的态度。不是我想摆出一种哎呀我是甲方我是上帝，而是你们给的感觉就是如此。但凡你们给的回复是，“你可以去看看xxx，文档这边如果可以的话你可以PR提交贡献帮助修改”这样都可以
4.学无止境，我一直在学习，只不过遇到了一些未知的问题，难道你遇到问题就学它怎么实现的吗，你也会去询问别人怎么解决的吧？我不是客户我不需要别人为我着想，只是希望尽力协助罢了。

**Comment by emojiiii** [comment]
> 用户群体中并不是所有人都跟你们一样非常懂，也有我这种懂一些不懂一些的人，遇到问题查找百度等平台找不到结果，自然会提出issue，然后我所看见的是：你提了Issue那你自己修 的态度。不是我想摆出一种哎呀我是甲方我是上帝，而是你们给的感觉就是如此。但凡你们给的回复是，“你可以去看看xxx，文档这边如果可以的话你可以PR提交贡献帮助修改”这样都可以

你可能是误会了我们这个设定，你截图可以截全一点，避免造成误会，这是欢迎开发者贡献！
因为我们都不是全职维护Element Plus，是开源社区一起维护的
![impicture_20211216_144850](https://user-images.githubusercontent.com/30518686/146322013-8c2314d0-5e62-4490-9711-ae2e51a7167f.png)

也许是机器人设定的回复不当，让你造成误会了，但是我们绝对不是你所说的
> 你提了Issue那你自己修 的态度

你可以看到每次发版的贡献记录，绝大部分都是我们的`Member` 修复的

**Comment by timi137137** [comment]
> > 用户群体中并不是所有人都跟你们一样非常懂，也有我这种懂一些不懂一些的人，遇到问题查找百度等平台找不到结果，自然会提出issue，然后我所看见的是：你提了Issue那你自己修 的态度。不是我想摆出一种哎呀我是甲方我是上帝，而是你们给的感觉就是如此。但凡你们给的回复是，“你可以去看看xxx，文档这边如果可以的话你可以PR提交贡献帮助修改”这样都可以
> 
> 你可能是误会了我们这个设定，你截图可以截全一点，避免造成误会，这是欢迎开发者贡献！ 因为我们都不是全职维护Element Plus，是开源社区一起维护的 ![impicture_20211216_144850](https://user-images.githubusercontent.com/30518686/146322013-8c2314d0-5e62-4490-9711-ae2e51a7167f.png)
> 
> 也许是机器人设定的回复不当，让你造成误会了，但是我们绝对不是你所说的
> 
> > 你提了Issue那你自己修 的态度
> 
> 你可以看到每次发版的贡献记录，绝大部分都是我们的`Member` 修复的

嗯....嘛无所谓了，反正问题解决了（先不用ts，再进修吧）
个人建议还是希望能修改一下机器人的回复，感谢
（从ele ui一路用过来并不想放弃使用）

**Comment by YunYouJun** [comment]
应该是上下午互相误解了吧（

sxzz 指的是组件 expose 出的类型，而你遇到的问题则是插件提示和文档示例不够新引起的类型提示错误。

更多的示例迁移已经在 https://github.com/element-plus/element-plus/pull/4849 进行中。

（嘛，Element Plus 相比 Element UI 时代已经完全过渡到社区维护，所以大家都是业余时间而非工作来进行维护。人手时间精力难免不足，总是也是在希望 element 能不断变得更好，只是这必然需要一些时间。Make Element Great Again!）

**Comment by timi137137** [comment]
> 应该是上下午互相误解了吧（
> 
> sxzz 指的是组件 expose 出的类型，而你遇到的问题则是插件提示和文档示例不够新引起的类型提示错误。
> 
> 更多的示例迁移已经在 #4849 进行中。
> 
> （嘛，Element Plus 相比 Element UI 时代已经完全过渡到社区维护，所以大家都是业余时间而非工作来进行维护。人手时间精力难免不足，总是也是在希望 element 能不断变得更好，只是这必然需要一些时间。Make Element Great Again!）

那确实，将来如果我有能力我也会一起维护的（目前我都没精通就别瞎想了x）
Make Element Great Again!

**Comment by timi137137** [comment]
（另外，我用的IDE是 JB的webstorm 不是vscode，因此没有volar，貌似大家都误会了？）

**Comment by YunYouJun** [comment]
快用无敌的 VSCode （帮你艾特个 webstorm 用户交流 @kooriookami ）

**Comment by timi137137** [comment]
> 快用无敌的 VSCode （帮你艾特个 webstorm 用户交流 @kooriookami ）

好耶！非常感谢！（我用习惯了JB的一系列插件xd不是很想用无敌的VSCode）

**Comment by gadfly3173** [comment]
> （另外，我用的IDE是 JB的webstorm 不是vscode，因此没有volar，貌似大家都误会了？）

我提volar是想说明defineComponent对于一般js项目没有很大的意义，也不是官方推荐做法

**Comment by timi137137** [comment]
> > （另外，我用的IDE是 JB的webstorm 不是vscode，因此没有volar，貌似大家都误会了？）
> 
> 我提volar是想说明defineComponent对于一般js项目没有很大的意义，也不是官方推荐做法

我只是在nestjs（一个后端框架）用习惯了TS，然后一时兴起在vue用了TS发现炸了一堆错(只怪自己TS啥也不懂

**Comment by emojiiii** [comment]
> > > （另外，我用的IDE是 JB的webstorm 不是vscode，因此没有volar，貌似大家都误会了？）
> > 
> > 
> > 我提volar是想说明defineComponent对于一般js项目没有很大的意义，也不是官方推荐做法
> 
> 我只是在nestjs（一个后端框架）用习惯了TS，然后一时兴起在vue用了TS发现炸了一堆错(只怪自己TS啥也不懂

Volar还不支持WebStorm，如果要写 vue + ts ，建议还是使用VsCode，安装`Vue Language Features (Volar)` 和 `TypeScript Vue Plugin (Volar)`
