### ISSUE TITLE
[Bug Report] doc site search does not work

### ISSUE THREAD

**Issue by Sepush** [element-plus/element-plus#4850]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win10 chrome96

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/

### Steps to reproduce
go
https://codepen.io/
use search to search component but it does not work

### What is Expected?
work

### What is actually happening?
dose not work

![image](https://user-images.githubusercontent.com/39197136/146208838-129937bd-80ab-4a79-8ce8-81f501ae3df5.png)

**Comment by xiaoxian521** [comment]
same: https://github.com/element-plus/element-plus/discussions/3851
