### ISSUE TITLE
[Bug Report] Getting error - GET https://unpkg.com/element-plus/dist/index.css net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by Manu-Geotourist** [element-plus/element-plus#4851]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Mac

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
index.css is not available in unpkg

### What is Expected?
Css file should load

### What is actually happening?
Css file not loading

**Comment by sxzz** [comment]
Please try again. May be it's caused by network and cache.
