### ISSUE TITLE
[Bug Report] inputNumber无法重置为未输入状态，即输入框啥都不显示

### ISSUE THREAD

**Issue by Xyuan-abs** [element-plus/element-plus#4853]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/xyuan-abs/pen/JjrWLYY?editors=1000

### Steps to reproduce
点击重置按钮

### What is Expected?
inputNumber界面值展示空

### What is actually happening?
value重置为undefind时，界面没有变化  
value重置为null时，界面展示0

**Comment by Alanscut** [comment]
@Xyuan-abs 
代码内部props：
![image](https://user-images.githubusercontent.com/21104054/146331959-249e840a-6cbc-478d-8509-3480184f6248.png)
文档介绍有一点脱节了，
我觉得没有必要将value设为undefined
如果你没有什么必要的需求，我就把文档修改一下好了。

**Comment by Xyuan-abs** [comment]
> @Xyuan-abs 代码内部props： ![image](https://user-images.githubusercontent.com/21104054/146331959-249e840a-6cbc-478d-8509-3480184f6248.png) 文档介绍有一点脱节了， 我觉得没有必要将value设为undefined 如果你没有什么必要的需求，我就把文档修改一下好了。
![image](https://user-images.githubusercontent.com/64180387/146336915-3033a79e-5e14-49d2-93fe-30c0b9ed48a9.png)
初始化 inputNumber的value为undefined时 ，inputNumber在界面上显示空
![image](https://user-images.githubusercontent.com/64180387/146337188-7bd25cd0-3d42-4884-bbfc-3602c100ee77.png)
输入值后   点击重置   
将值赋值为undefined时 inputNumber在界面上仍显示上一个值     
将值赋值为null时 inputNumber在界面上显示0   
 现在的需求是点击重置按钮  inputNumber在界面上显示空

**Comment by Alanscut** [comment]
突然发现只能设置number的话，placeholder完全是无效的了

**Comment by Alanscut** [comment]
我会在这两天修复这个问题

**Comment by Xyuan-abs** [comment]
> 我会在这两天修复这个问题

我传undefined的目的就是让inputNumber在界面上能展示空，让用户知道这个输入框是处于未输入的状态

**Comment by lemoe2021** [comment]
不能为 undefined 这个问题提了好几次也没被同意🤣
https://github.com/element-plus/element-plus/issues/4323
https://github.com/element-plus/element-plus/issues/4279
https://github.com/element-plus/element-plus/issues/4300

**Comment by Xyuan-abs** [comment]
> 不能为 undefined 这个问题提了好几次也没被同意🤣 #4323 #4279 #4300

传undefined的目的为了清空inputNumber界面上显示的值，但是现在传undefined没有变化，传null又会显示0 ，所以我才提了这个issue， 但是感觉老哥@Alanscut没理解我的意思

**Comment by Alanscut** [comment]
> > 不能为 undefined 这个问题提了好几次也没被同意🤣 #4323 #4279 #4300
> 
> 传undefined的目的为了清空inputNumber界面上显示的值，但是现在传undefined没有变化，传null又会显示0 ，所以我才提了这个issue， 但是感觉老哥@Alanscut没理解我的意思

pr解决这个问题了，等检视和合入
