### ISSUE TITLE
[Bug Report] ElIcon 样式问题

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#4854]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome 96.0.4664.93

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/kailong321200875/pen/dyVvmRv

### Steps to reproduce
el-icon 图标没有垂直居中，需要给 el-icon 加上 el-input--icon 的类名才能居中

### What is Expected?
能不能内置 类名，而不需要手动去添加这个类名

### What is actually happening?
能不能内置 类名，而不需要手动去添加这个类名

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
You can try this:

```vue
<el-input
  v-model="input1"
  size="large"
  placeholder="Please Input"
  :prefix-icon="Search"
></el-input>
```

It will be center automatically.

If you want to use `template`, we will not add any styles by default to avoid misunderstandings.
