### ISSUE TITLE
[Bug Report] 1.2.0-beta.6   unplugin-vue-components@0.17.9 自动导入v-loading编译无法通过

### ISSUE THREAD

**Issue by cscxj** [element-plus/element-plus#4855]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome 96.0.4664.110

### Vue version
3.0.0

### Reproduction Link
https://github.com/cxj-github/auto-import-demo

### Steps to reproduce
git clone git@github.com:cxj-github/auto-import-demo.git 
cd auto-import-demo 
npm i 
npm run serve 
 
App.vue 里面使用了一个v-loading 

### What is Expected?
.

### What is actually happening?
查看控制台报错：
This dependency was not found: 
* element-plus/es/components/loading-directive/style/css

**Comment by Viin-zx** [comment]
同问题。。

**Comment by lollplmtm** [comment]
This dependency was not found： element-plus/es/components/loading-directive/style/css

**Comment by lollplmtm** [comment]
+1

**Comment by Dirian9754** [comment]
同样的问题

**Comment by sxzz** [comment]
可能是 webpack 下才有问题。Vite 请参考 https://github.com/sxzz/element-plus-best-practices

**Comment by cxj-github** [comment]
@sxzz 是用的webpack。请问有解决方案吗

**Comment by Dirian9754** [comment]
> 可能是 webpack 下才有问题。Vite 请参考 https://github.com/sxzz/element-plus-best-practices

我使用的构建工具是vite，当我手动导入ElLoadingDirective指令时，也会出现这种问题，它会去导入loading-directive的样式，但是显然它是不存在，能解决下吗？

**Comment by sxzz** [comment]
@Dirian9754 可以导入 `ElLoading` 在获取到 `directive`

[Demo](https://play.element-plus.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBFbExvYWRpbmcgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbnNldHVwRWxlbWVudFBsdXMoKTtcblxuY29uc29sZS5sb2coRWxMb2FkaW5nLmRpcmVjdGl2ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxzcGFuIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

**Comment by Dirian9754** [comment]
> 

nice，这样可行

**Comment by yeshaojun** [comment]
手动引入样式，loading的api可以使用，但是指令还是不行。目前过渡的解决方案是，自己定义一个全局指令，对ElLoading.service再包一层，就可以使用了。不知道有没有更好的办法？
`  app.directive("rsvp-loading", {
    updated(el, binding) {
      if (binding.value && !loadingInstance)  {
        loadingInstance = ElLoading.service({
          target: el,
          lock: true,
          text: "数据加载中",
        });
      }
      if (!binding.value) {
        loadingInstance.close();
      }
    },
  });`

**Comment by Lantern-r** [comment]
Mark 有相同的问题

**Comment by End4You** [comment]
mark

**Comment by BigPengZai** [comment]
import { ElLoading } from 'element-plus/lib/components/loading'
import 'element-plus/theme-chalk/el-loading.css'

you can  try

**Comment by End4You** [comment]
edit vue.config.js or webpack.config.js

`
const Icons = require('unplugin-icons/webpack');
const IconsResolver = require('unplugin-icons/resolver');
const AutoImport = require('unplugin-auto-import/webpack');
const Components = require('unplugin-vue-components/webpack');

AutoImport({
  imports: ['vue'],
  **resolvers: [ElementPlusResolver({ importStyle: false })],**
  dts: 'auto-imports.d.ts',
}),
Components({
  resolvers: [
    IconsResolver({ enabledCollections: ['ep'] }),
    ElementPlusResolver({ importStyle: 'sass' }),
  ],
  dts: 'components.d.ts',
}),
Icons({ autoInstall: true }),
`

**Comment by End4You** [comment]
edit vue.config.js or webpack.config.js

fix code: `resolvers: [ElementPlusResolver({ importStyle: false })]`

```
const Icons = require('unplugin-icons/webpack');
const IconsResolver = require('unplugin-icons/resolver');
const AutoImport = require('unplugin-auto-import/webpack');
const Components = require('unplugin-vue-components/webpack');

AutoImport({
  imports: ['vue'],
  resolvers: [ElementPlusResolver({ importStyle: false })],
  dts: 'auto-imports.d.ts',
}),
Components({
  resolvers: [
    IconsResolver({ enabledCollections: ['ep'] }),
    ElementPlusResolver({ importStyle: 'sass' }),
  ],
  dts: 'components.d.ts',
}),
Icons({ autoInstall: true }),
```

**Comment by littleboarx** [comment]
there is a workaround using webpack,IgnorePlugin without losing style auto import:

new IgnorePlugin({
            resourceRegExp: /es\/components\/loading-directive/,
        }),

**Comment by littleboarx** [comment]
there is a workaround using externals without losing style auto import:
externals: {
        'element-plus/es/components/loading-directive/style/css': 'empty',
},

**Comment by languanghao** [comment]
also have same problem

**Comment by zhoufanglu** [comment]
mark i have the same question

**Comment by ApsarasX** [comment]
使用1.3.0-beta.5也遇到了这个问题

**Comment by fadeds** [comment]
+1 来找指令的方案

**Comment by sxzz** [comment]
`unplugin-auto-import` 和 `unplugin-vue-components` 在 Webpack 下有冲突。

**Comment by itagan** [comment]
> 

vue-cli webpack can use  'resolvers: [ElementPlusResolver({ importStyle: false })]'   in development

**Comment by zhoufanglu** [comment]
> mark i have the same question
操作：修改主题色，出错
原因 是vue.config.js本地sass全局变量影响到了element/index.scss
[参考](https://juejin.cn/post/7052563429395021832)

**Comment by itskaiway** [comment]
I suggest replacing v-loading with a custom directive
```javascript
import { ElLoading } from 'element-plus';
import 'element-plus/es/components/loading/style/css';
import { Directive } from 'vue';

const svg = `
        <path class="path" d="
          M 30 15
          L 28 17
          M 25.61 25.61
          A 15 15, 0, 0, 1, 15 30
          A 15 15, 0, 1, 1, 27.99 7.5
          L 15 15
        " style="stroke-width: 4px; fill: rgba(0, 0, 0, 0)"/>
      `;
let loadingInstance: any;
const common = (el: HTMLElement, value: boolean) => {
  if (value && !loadingInstance) {
    loadingInstance = ElLoading.service({
      target: el,
      text: 'loading...',
      spinner: svg,
      svgViewBox: '-10, -10, 50, 50',
    });
  }
  if (!value) {
    loadingInstance?.close();
    loadingInstance = null;
  }
};
export const spin: Directive = {
  mounted(el, binding) {
    const { value } = binding;
    common(el, value);
  },
  updated(el, binding) {
    const { value } = binding;
    common(el, value);
  },
};
```

**Comment by losscode** [comment]
webpack：
```
const { ElementPlusResolver } = require("unplugin-vue-components/resolvers");
module.exports = {
  configureWebpack: {
    plugins: [
      require("unplugin-auto-import/webpack")({
        resolvers: [ElementPlusResolver({importStyle: false})],
      }),
      require("unplugin-vue-components/webpack")({
        resolvers: [ElementPlusResolver()],
      }),
    ],
  },
};
```
我在这样设置之后好了。

**Comment by HHH917** [comment]
参考你们的 我找到了解决方式   ElementPlusResolver 函数里使用正则表达式 排除 loading-directive 的样式 
使用webpack    vue.config,js    

`
    config.plugin('AutoImport').use(
      AutoImport({
        imports: ['vue'],
        resolvers: [
          ElementPlusResolver({
            importStyle: 'css',
            exclude: new RegExp(/^(?!.*loading-directive).*$/)
          })
        ],
        dts: 'auto-imports.d.ts'
      })
    )
    config.plugin('Components').use(
      Components({
        resolvers: [ElementPlusResolver({ importStyle: 'css' })],
        dts: 'components.d.ts'
      })
    )
`

**Comment by yanggongzhou** [comment]
配置vue.config.js 在我项目中还是不生效

我这边解决办法: 包了一层 自定义指令

`import { vLoading } from "element-plus/es/components/loading/src/directive";`

`app.directive('load', vLoading)`

使用： v-load=“true”
其他 相关指令 element-loading-text、 element-loading-spinner 、 element-loading-svg、 element-loading-background也都可以正常使用

**Comment by nian2760** [comment]
I had the same problem at vite

Put 'AutoImport' in front of 'Components', the error disappears :sweat_smile:

vite.config.ts
```js
plugins:[
  AutoImport(...),
  Components(...)
]
```

**Comment by Lmmmmmm-bb** [comment]
In Vite you can

```ts
// main.ts
import { ElLoading } from 'element-plus';

createApp(App).directive('loading', ElLoading.directive);
```

**Comment by ZiuChen** [comment]
> 配置vue.config.js 在我项目中还是不生效
> 
> 我这边解决办法: 包了一层 自定义指令
> 
> `import { vLoading } from "element-plus/es/components/loading/src/directive";`
> 
> `app.directive('load', vLoading)`
> 
> 使用： v-load=“true” 其他 相关指令 element-loading-text、 element-loading-spinner 、 element-loading-svg、 element-loading-background也都可以正常使用

https://github.com/element-plus/element-plus/issues/4855#issuecomment-1053949738

这个方法对我有效

**Comment by Linhongbin-1111** [comment]
> ```ts
> , 
> ```
I tried import like this, but it doesn't work. element-plus@2.1.4

**Comment by Linhongbin-1111** [comment]
> 

I tried import like this, but it doesn't work. element-plus@2.1.4

**Comment by changlin666666** [comment]
> > 配置vue.config.js 在我的项目中还不生效
> > 我的当前解决办法：
> > `import { vLoading } from "element-plus/es/components/loading/src/directive";`
> > `app.directive('load', vLoading)`
> > 使用： vload="true" 其他相关指令也可以正常使用 element-loading-text、 element-loading-spinner 、 element-loading-svg、 element-loading-background
> 
> [第4855章（评论）](https://github.com/element-plus/element-plus/issues/4855#issuecomment-1053949738)
> 
> 这个方法对我很有效

没效果阿

**Comment by changlin666666** [comment]
> 使用webpack，vue.config.js：
> 
> ```
> const { ElementPlusResolver } = require("unplugin-vue-components/resolvers");
> module.exports = {
>   configureWebpack: {
>     plugins: [
>       require("unplugin-auto-import/webpack")({
>         resolvers: [ElementPlusResolver({importStyle: false})],
>       }),
>       require("unplugin-vue-components/webpack")({
>         resolvers: [ElementPlusResolver()],
>       }),
>     ],
>   },
> };
> ```
> 
> 我在这样设置之后好了。

我尝试了你这种办法之后ElMessage功能就没效果了

**Comment by liwei478** [comment]
> 配置vue.config.js 在我项目中还是不生效
> 
> 我这边解决办法: 包了一层 自定义指令
> 
> `import { vLoading } from "element-plus/es/components/loading/src/directive";`
> 
> `app.directive('load', vLoading)`
> 
> 使用： v-load=“true” 其他 相关指令 element-loading-text、 element-loading-spinner 、 element-loading-svg、 element-loading-background也都可以正常使用

good job, man, i use this way to solve my problem, thanks, bro

**Comment by JialeHub** [comment]
自动回复：您好，您所发的邮件已收到，感谢！This is an automatic reply, confirming that your e-mail was received.Thank you！
