### ISSUE TITLE
[Bug Report] El-Upload handler typescript wrong

### ISSUE THREAD

**Issue by gadfly3173** [element-plus/element-plus#4857]
handlers don't have correct param type

### Element Plus version
1.2.0-beta.6

### OS/Browsers version
x

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
upload.type.d.ts
```ts
export interface ElUpload extends IUseHandlersProps {
    accept: string;
    headers?: Headers;
    data?: Record<string, unknown>;
    multiple?: boolean;
    name?: string;
    drag?: boolean;
    withCredentials?: boolean;
    showFileList?: boolean;
    type?: string;
    dragOver: boolean;
    genUid: () => number;
    tempIndex: number;
    handleError: () => void;
    handleProgress: () => void;
    handleRemove: () => void;
    handleStart: () => void;
    handleSuccess: () => void;
    uploadDisabled: boolean;
    uploadFiles: UploadFile[];
    submit: () => void;
    clearFiles: () => void;
}
```

in source code: 
https://github.com/element-plus/element-plus/blob/2e75c3e086a6f4428fea77fc5de528847418b94c/packages/components/upload/src/useHandlers.ts#L27-L91
### What is Expected?
param type correct

### What is actually happening?
wrong

**Comment by emojiiii** [comment]
yep, I'm already refactoring `ElUpload`
