### ISSUE TITLE
[Bug Report] 组件upload中的before-remove方法没有按照预期执行

### ISSUE THREAD

**Issue by Yanzengyong** [element-plus/element-plus#4859]
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
macos/chrome

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/6/

### Steps to reproduce
        <el-upload
          class="upload-demo"
          action="http://localhost:8080/api/literature/upload"
          :limit="1"
          :before-remove="beforeRemove"
          :on-success="uploadSuccess"
          :on-error="uploadFail"
        >
          <el-button size="mini" type="primary">上传文件 / 更换文件</el-button>
        </el-upload>

      const beforeRemove = async () => {
           return true
      }

### What is Expected?
按照文档的描述，before-remove方法如果返回false，则终止删除

### What is actually happening?
实际，仍然删除了

**Comment by Alanscut** [comment]
使用async函数的问题，现阶段使用非async函数是可以终止删除的
