### ISSUE TITLE
[Bug Report] please do not set fixed height for `el-menu`

### ISSUE THREAD

**Issue by xiangqunXiao** [element-plus/element-plus#4864]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win10 Edge

### Vue version
3.2.26

### Reproduction Link
http://www.codesandbox.com

### Steps to reproduce
source code set fixed height for el-sub-menu, it is an unreasonable code
```
.el-menu--horizontal>.el-sub-menu .el-sub-menu__title {
height: 60px;
line-height: 60px;
}
```

### What is Expected?
Let user decide the height of it in a elegant way.For example:
- `height: 100%` so it can be decided by outer container's height
- css vars to define it's height

### What is actually happening?
I need to override the css rule to set it's height,which is an ugly way.

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Yeah, you are right. I create #5034 to fix it. And we can custom height by css var `--el-menu-item-height`.
