### ISSUE TITLE
[Feature Request] el-message max attribute

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#4868]
### Existing Component
是

### Component Name
el-message

### Description
Add Max attribute for El message and can be set in El Config Provider

**Comment by emojiiii** [comment]
Can you describe the usage scenario？

**Comment by kailong321200875** [comment]
> 

Just want to have a configurable extension. It is possible that when the interface reports an error, there will be a lot of error messages, resulting in unfriendly page display.

**Comment by kailong321200875** [comment]
> Can you describe the usage scenario？

Just want to have a configurable extension. It is possible that when the interface reports an error, there will be a lot of error messages, resulting in unfriendly page display.

**Comment by emojiiii** [comment]
i think you can merge the same message, please see [docs](https://element-plus.gitee.io/zh-CN/component/message.html#grouping)

**Comment by kailong321200875** [comment]
> i think you can merge the same message, please see [docs](https://element-plus.gitee.io/zh-CN/component/message.html#grouping)

OK, I'll try it

**Comment by kailong321200875** [comment]
@emojiiii 

I think the max attribute is necessary, because one application scenario is that when the error information returned by the interface is different, too much error information will affect the beauty of the whole page.

**Comment by btea** [comment]
I am trying to implement this feature, when the length of the message exceeds max, directly intercept the max-length string.  

But I think it’s a bit abrupt, maybe it's better to add `...` after the intercepted string ?

What do you guys think ?  @emojiiii @kailong321200875

**Comment by emojiiii** [comment]
> I am trying to implement this feature, when the length of the message exceeds max, directly intercept the max-length string.
> 
> But I think it’s a bit abrupt, maybe it's better to add `...` after the intercepted string ?
> 
> What do you guys think ? @emojiiii @kailong321200875

I'm sorry, you may have misunderstood his question!
I think what he wants is the number of `messages` appearing at the same time, not the length limit of `messages content`

**Comment by btea** [comment]
@emojiiii   I'm very sorry, I saw that @kailong321200875  said a lot of error messages were returned. I thought it was because the interface reported an error that caused the information to be too long, so it needs to be intercepted. 🤣

**Comment by emojiiii** [comment]
> @emojiiii I'm very sorry, I saw that @kailong321200875 said a lot of error messages were returned. I thought it was because the interface reported an error that caused the information to be too long, so it needs to be intercepted. 🤣

I'm sorry I didn't explain the problem clearly. It's hard for you

**Comment by btea** [comment]
@emojiiii Ok, i will modify it

**Comment by kailong321200875** [comment]
Thank you very much. I wanted to try this function, but there are too many tasks in the company during this period, so I don't have free time. I'm very sorry.
