### ISSUE TITLE
[Feature request] Vite esm import

### ISSUE THREAD

**Issue by vok123** [element-plus/element-plus#487]
大佬, 关于Vite esm怎么说

**Comment by JeremyWuuuuu** [comment]
Pardon?

**Comment by zazzaz** [comment]
You can check the Element Plus Vite starter as a reference. https://github.com/element-plus/element-plus-vite-starter

**Comment by vok123** [comment]
> You can check the Element Plus Vite starter as a reference. https://github.com/element-plus/element-plus-vite-starter

import { Notification } from 'element-plus';  // 这种引入呢

**Comment by zazzaz** [comment]
> > You can check the Element Plus Vite starter as a reference. https://github.com/element-plus/element-plus-vite-starter
> 
> import { Notification } from 'element-plus'; // 这种引入呢

Will support this in the coming version.

**Comment by vok123** [comment]
冒昧问一下, 大概啥时候可以发布呢

**Comment by zazzaz** [comment]
We are working on this.

**Comment by JeremyWuuuuu** [comment]
@vok123 Try it out with `alpha-20`.

**Comment by JeremyWuuuuu** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
