### ISSUE TITLE
[Bug Report] El-Icon style does not effect

### ISSUE THREAD

**Issue by LoveofRedMoon** [element-plus/element-plus#4872]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
newest

### Vue version
3.2.26

### Reproduction Link
https://element-plus.gitee.io/zh-CN/component/icon.html#icon-collection

### Steps to reproduce
Just see the style of `.el-icon`

### What is Expected?
`font-size: var(--font-size)`

### What is actually happening?
`font-size: inherit`

**Comment by emojiiii** [comment]
fix in #4798
