### ISSUE TITLE
[Bug Report] Image component preview image, closed event invalid

### ISSUE THREAD

**Issue by anrui0219** [element-plus/element-plus#4876]
### Element Plus version
1.0.2-beta.59

### OS/Browsers version
Google

### Vue version
3.0.4

### Reproduction Link
https://codepen.io/an-hr/pen/mdBmORd

### Steps to reproduce
After image component preview is enabled, the close event does not respond.
![微信图片_20211217133530](https://user-images.githubusercontent.com/44487076/146494602-a5a632ff-ac14-40bb-9046-8c5b8036ee26.png)
I checked the problem online and found that many said this method was ineffective.
For example：
![image](https://user-images.githubusercontent.com/44487076/146494682-ab12c38a-b07a-4fe1-98c2-7f468c4d06d7.png)
![image](https://user-images.githubusercontent.com/44487076/146494755-1bccdaa6-a3c8-4e08-b7ab-a2d446b13713.png)

### What is Expected?
You want this method to work.
Also, if possible, whether the preview image can generate separate external components？

### What is actually happening?
Tried to execute some event when closing preview, but couldn't

**Comment by emojiiii** [comment]
please see this [example ](https://play.element-plus.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBFbElucHV0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5zZXR1cEVsZW1lbnRQbHVzKCk7XG4gIFxuICBjb25zdCBzcmMgPSBcImh0dHBzOi8vZ2ltZzIuYmFpZHUuY29tL2ltYWdlX3NlYXJjaC9zcmM9aHR0cCUzQSUyRiUyRmhiaW1nLmIwLnVwYWl5dW4uY29tJTJGNjc2OTQwZGQyMzgxNGM0M2JkOGRjZTI2OWVkOTQ0NWRjMjg4NGEwNDE2ODJjLWs2Vm9STF9mdzY1OCZyZWZlcj1odHRwJTNBJTJGJTJGaGJpbWcuYjAudXBhaXl1bi5jb20mYXBwPTIwMDImc2l6ZT1mOTk5OSwxMDAwMCZxPWE4MCZuPTAmZz0wbiZmbXQ9anBlZz9zZWM9MTY0MjMxODMyNCZ0PTE5Mzc3ZTkwZTNmY2Q3ZGZkMDQ3NjJmZWVhMmM2YzVmXCJcbiAgXG4gIGNvbnN0IGNsb3NlSW1nVmlldyA9ICgpID0+IHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKCdjbG9zZUltZ1ZpZXcnKVxuICAgICAgICAgIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbWFnZSBcbiAgICAgICAgICA6c3JjPVwic3JjXCJcbiAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cIltzcmNdXCJcbiAgICAgICAgICByZWY9XCJwcmV2aWV3XCJcbiAgICAgICAgICBAY2xvc2U9XCJjbG9zZUltZ1ZpZXdcIlxuICAgICAgICAgIDpoaWRlLW9uLWNsaWNrLW1vZGFsPVwidHJ1ZVwiXG4gICAgICA+PC9lbC1pbWFnZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by anrui0219** [comment]
I don't understand why it doesn't take effect in normal projects. Do I need to configure anything separately

**Comment by anrui0219** [comment]
It does not take effect if I copy your example into the project completely, is it the version problem？

**Comment by anrui0219** [comment]
Well, I've updated it to 1.2.0-bet.6. It's working, thank you
