### ISSUE TITLE
VUE3.0 typescript 弹窗如何实现

### ISSUE THREAD

**Issue by xlanghejianfeng** [element-plus/element-plus#488]
this.$alert('这是一段内容', '标题名称', {
          confirmButtonText: '确定',
          callback: action => {
            this.$message({
              type: 'info',
              message: `action: ${ action }`
            });
          }

**Comment by JeremyWuuuuu** [comment]
Please at least provide us a least reproducible code or cloud IDE link, otherwise we could not give any suggestion

**Comment by xlanghejianfeng** [comment]
就是 在vue3.0里 都是 composition API ，这样的写法肯定实现不了 弹窗，还需要提供一个 关于vue3.0里的 ts 语法 在官方文档里，谢谢

**Comment by JeremyWuuuuu** [comment]
Options API is also supported in V3, documentation will be updated once our migration has completed. You can try it with syntax just like V2. A quick demo here. 

#### this is not supported by now, so you can not use it in the recent builds. We are trying to find a way to make it work like this
```vue
<script>
import { Notify } from 'element-plus/lib/notification'


export default {
   // ...others
   setup() {
      const someFunc = () => Notify(options)
   }
}
</script>
```
