### ISSUE TITLE
[Bug Report] 使用vite build (vue 3.2.26 & element-plus 1.2.0-beta.6)编译报错

### ISSUE THREAD

**Issue by peterwang1990** [element-plus/element-plus#4884]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
macos 12.0.1

### Vue version
3.2.26

### Reproduction Link
https://github.com/peterwang1990/vue3-debug.git

### Steps to reproduce
本地编译 npm run build 
或者在codesandbox 引入 github地址进行 build

我的 codesandbox链接: https://codesandbox.io/s/vigorous-bas-2j950

我的 package.json

"dependencies": {
    "@makerdao/multicall": "^0.12.0",
    "@metamask/detect-provider": "1.2.0",
    "@vueuse/core": "^6.7.4",
    "@walletconnect/web3-provider": "1.6.6",
    "amfe-flexible": "^2.2.1",
    "autoprefixer": "^10.4.0",
    "axios": "^0.21.1",
    "bignumber.js": "9.0.1",
    "dot-prop-immutable": "2.1.1",
    "element-plus": "1.2.0-beta.6",
    "ethereumjs-util": "^7.1.3",
    "ethers": "^5.5.1",
    "mitt": "3.0.0",
    "moment": "2.29.1",
    "patch-package": "^6.4.7",
    "postcss-pxtorem": "^6.0.0",
    "remixicon": "^2.5.0",
    "vue": "3.2.26",
    "vue-router": "4.0.11",
    "vuex": "^4.0.2",
    "web3": "1.6.0",
    "web3-eth": "1.6.0",
    "web3-eth-contract": "1.6.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@types/jest": "^26.0.22",
    "@types/lodash": "^4.14.176",
    "@types/node": "^16.11.6",
    "@types/uuid": "^8.3.1",
    "@typescript-eslint/eslint-plugin": "^4.21.0",
    "@typescript-eslint/parser": "^4.21.0",
    "@vitejs/plugin-vue": "1.9.4",
    "@vue/compiler-sfc": "3.2.26",
    "@vue/test-utils": "^2.0.0-rc.4",
    "commitizen": "^4.2.3",
    "cz-conventional-changelog": "^3.3.0",
    "cz-customizable": "^6.3.0",
    "eslint": "^7.24.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-import-resolver-node": "^0.3.6",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.3.5",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.8.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylus": "^0.54.8",
    "ts-jest": "^26.5.4",
    "ts-morph": "^12.2.0",
    "typescript": "^4.4.4",
    "unplugin-vue-components": "^0.17.0",
    "vite": "2.6.14",
    "vue-jest": "^5.0.0-alpha.7",
    "vue-tsc": "^0.3.0"
  }

### What is Expected?
应该编译无报错

### What is actually happening?
编译出错

Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
error during build:
Error: Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
    at error (/Users/daviddai/tmp/vue3-debug/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/Users/daviddai/tmp/vue3-debug/node_modules/rollup/dist/shared/rollup.js:22263:24)
    at /Users/daviddai/tmp/vue3-debug/node_modules/rollup/dist/shared/rollup.js:22257:26

**Comment by peterwang1990** [comment]
之前我汇报过一次issue,然后回复让我更新到最新版本的vue.但是我把vue版本和对应的@vue/compiler-sfc 的版本 都更新到最新的 3.2.26 依然报错,麻烦帮忙定位下问题,谢谢了~

**Comment by btea** [comment]
请把配置文件里的global去掉试试
```ts
define: {
    'process.env': {},
    // global: {},
    '_vm._self._c': {},
},
```

**Comment by peterwang1990** [comment]
> 请把配置文件里的global去掉试试
> 
> ```ts
> define: {
>     'process.env': {},
>     // global: {},
>     '_vm._self._c': {},
> },
> ```

感谢,编译通过了

**Comment by peterwang1990** [comment]
@btea 感谢,编译通过了

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/146767432-42ecc448-d730-4ac7-a5f2-c1658e8a5664.png)

因为vite把你定义的 `global` 替换成了 `{}` , 所以引用文件的路径变了
