### ISSUE TITLE
[Bug Report] Tooltip快速隐藏关闭是有黑块

### ISSUE THREAD

**Issue by fengwanqing** [element-plus/element-plus#4886]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
MACOS 12.0.1 / Chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

### What is Expected?
无黑块

### What is actually happening?
有黑块

**Comment by fengwanqing** [comment]
https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
官网这个链接即可复现

**Comment by emojiiii** [comment]
Duplicate of #4837
