### ISSUE TITLE
[Feature Request] Want a "LoadingBar" product component

### ISSUE THREAD

**Issue by 7086cmd** [element-plus/element-plus#4889]
### Existing Component
No

### Component Name
Loading Bar

### Description
Like the document, when I change the page, there are 2 loading tools, and it is loading icon and loading bar. Can this project provide the loading bar?

**Comment by emojiiii** [comment]
@sxzz @JeremyWuuuuu cc

**Comment by 7086cmd** [comment]
Are there any update?
