### ISSUE TITLE
[Feature Request] 下拉组件多选collapse-tags 数字最多显示到 99，超过就换行异常了

### ISSUE THREAD

**Issue by aslrz-club** [element-plus/element-plus#4906]
### Existing Component
Yes

### Component Name
1.2.0-beta.6

### Description
chrome,希望el-select__tags-text的max-width是inputWidth-123px 可以改成减去tagwidth 去配置

**Comment by msidolphin** [comment]
难以避免，如果前面的tag过长呢，没有必要去适配，
