### ISSUE TITLE
[Bug Report] el-table排序错误

### ISSUE THREAD

**Issue by LiuXIn011** [element-plus/element-plus#4912]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows/Chrome 96.0.4664.45（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/liuxin011/pen/RwLZRqo

### Steps to reproduce
使用下列数据填入表格，并设置nub列进行正序排序
     list: [{
        nub: "1",
      },
      {
        nub: "2",
      },
      {
        nub: "3",
      },
      {
        nub: "11",
      },
      {
        nub: "21",
      },
      {
        nub: "31",
      }]  

### What is Expected?
排序结果应为：1-2-3-11-21-31

### What is actually happening?
实际排序结果为：1-11-2-21-3-31

**Comment by gadfly3173** [comment]
因为是传入的值是string吧

**Comment by msidolphin** [comment]
你应该传入number类型，我不认为组件应该改变用户的输入类型来排序
