### ISSUE TITLE
[Bug Report] Popconfirm 气泡确认框，不支持防抖。

### ISSUE THREAD

**Issue by LiuXIn011** [element-plus/element-plus#4913]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows/Chrome 96.0.4664.45（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/liuxin011/pen/yLzoJGQ

### Steps to reproduce
快速点击Popconfirm 气泡确认框

### What is Expected?
只执行一次操作

### What is actually happening?
多次执行操作

**Comment by Alanscut** [comment]
@LiuXIn011 如果和`popover`类似，把`trigger`属性暴露出来，你可以设置为`manual`然后自己在`@click`里面实现自定义的效果怎么样？
https://element-plus.org/zh-CN/component/popover.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
![image](https://user-images.githubusercontent.com/21104054/147202164-3b6ca35c-bfe7-4e4f-817a-39c6f8baa083.png)

**Comment by LiuXIn011** [comment]
> @LiuXIn011如果和`popover`类似，把`trigger`属性暴露，你可以设置为`manual`然后自己在`@click`里面实现自定义的效果怎么样？ [https://element-plus.org/zh-CN/component/popover.html#%E5% 9F%BA%E7%A1%80%E7%94%A8%E6%B3%95](https://element-plus.org/zh-CN/component/popover.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95) ![图片](https://user-images.githubusercontent.com/21104054/147202164-3b6ca35c-bfe7-4e4f-817a-39c6f8baa083.png)

可否参考MessageBox组件，这个组件有防抖，而且很好用哦
https://element-plus.gitee.io/zh-CN/component/message-box.html

**Comment by Alanscut** [comment]
@LiuXIn011 你是指`MessageBox`中的第一个demo吗？

**Comment by LiuXIn011** [comment]
> @LiuXIn011 你是指`MessageBox`中的第一个demo吗？

不是，第二个，做提示框的时候连续点击不会触发多次
![image](https://user-images.githubusercontent.com/48080203/147204220-b261938c-dfda-4964-a42d-1ac019212488.png)

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/147204635-bb04f612-5ea7-4047-9b55-d170ba88e7f6.mp4

我没有见到防抖的效果

**Comment by LiuXIn011** [comment]
> messagebox.mp4 
> 我没有见到防抖的效果

他每次都是触发一次message，不会触发多次

**Comment by Alanscut** [comment]
对不起，我刚刚反应过来你说的是你自定义的`@confirm`事件没有防抖效果？

**Comment by LiuXIn011** [comment]
> 对不起，我刚刚反应过来你说的是你自定义的`@confirm`事件没有防抖效果？

对的

**Comment by Alanscut** [comment]
messageBox的确认按钮存在防抖效果是因为他的`click`事件是内部处理过的。
你这个自己的自定义`@confirm`事件不应该是自己实现防抖效果吗？

**Comment by LiuXIn011** [comment]
> messageBox的确认按钮存在防抖效果是因为他的`click`事件是内部处理过的。 你这个自己的自定义`@confirm`事件不应该是自己实现防抖效果吗？

如果element在执行emit的时候做一个防抖，框架使用者就不用每次@confirm都处理一下防抖了
