### ISSUE TITLE
[Bug Report] 触发select表单校验后，鼠标hover会改变边框的颜色

### ISSUE THREAD

**Issue by Xyuan-abs** [element-plus/element-plus#4917]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/xyuan-abs/pen/poWreeB?editors=1000

### Steps to reproduce
1、进入codepen，直接点击 立即创建按钮 触发表单校验
![image](https://user-images.githubusercontent.com/64180387/146899006-41826cf1-10c2-4123-865b-d012dfdacfc8.png)

2、将鼠标移至select组件上
![image](https://user-images.githubusercontent.com/64180387/146898971-1f734fc2-8426-4108-97af-06404e35a542.png)

### What is Expected?
边框颜色还是红色

### What is actually happening?
边框颜色变成灰色

**Comment by kooriookami** [comment]
Fixed
