### ISSUE TITLE
[Bug Report] <tooltip>组件偶尔会出现显示位置错误的问题

### ISSUE THREAD

**Issue by chendx97** [element-plus/element-plus#4926]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/dcba/pen/gOGxNrp

### Steps to reproduce
1.打开文档 https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E4%B8%BB%E9%A2%98 或上面的codepen链接   
2.鼠标移入到Dark按钮上    
3.多次移入，其中某次会出现三角箭头显示在按钮右边，提示信息显示在页面顶部

### What is Expected?
提示信息每次都显示在设置的placement位置上

### What is actually happening?
设置的位置是top，但某些时候箭头显示在按钮右边，信息显示在页面顶部。

**Comment by emojiiii** [comment]
Duplicate of #4837
