### ISSUE TITLE
[Bug Report] tooltip样式显示bug 

### ISSUE THREAD

**Issue by ruanye** [element-plus/element-plus#4935]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/kf6w3rhm/5/

### Steps to reproduce
jsfidde没法看到效果，但是在官网就可以重现，在官网的tooltip例子里面切换按钮，tooltip出现位置错乱，顶部一个，正常位置一个，并且出现多余的棱形,在官网的例子上来回切换点击就会出现。

### What is Expected?
tooptip 显示正常

### What is actually happening?
tooltip显示不正常

**Comment by jiaozhiye** [comment]
I have the same problem

**Comment by btea** [comment]
fixed #4907

**Comment by emojiiii** [comment]
Duplicate of #4837
