### ISSUE TITLE
[Bug Report] CDN方式国际化不可用ElementPlus.lang.zhCn不存在

### ISSUE THREAD

**Issue by tomorrowgood** [element-plus/element-plus#4936]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
window10

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/tomorrowgood/pen/OJxxjEZ?editors=1111

### Steps to reproduce
按照官方文档根本无法使用cdn达到国际化

### What is Expected?
根据cdn能够国际化，主要是要显示中文

### What is actually happening?
无法根据文档显示中文，而且文档路径下cdn 没有zh-cn，下面是官方例子，实际上ElementPlus.lang.zhCn已不存在
<script src="//unpkg.com/element-plus/dist/locale/zh-cn">
  <script>
  app.use(ElementPlus, {
    locale: ElementPlus.lang.zhCn
  })
</script>

**Comment by 360060316** [comment]
越更新bug越多服了 现在中文变成英文了

**Comment by wp993080086** [comment]
+1

**Comment by wp993080086** [comment]
按如下配置，可以配置为中文

### main.ts

`import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import zhCn from 'element-plus/lib/locale/lang/zh-cn'
import App from '@/App.vue'
import router from '@/router'
import store from '@/store'

const app = createApp(App)
app.use(router)
app.use(store)
app.use(ElementPlus, { locale: zhCn })
app.mount('#app')`

**Comment by guofeng1140559057** [comment]
![image](https://user-images.githubusercontent.com/18492836/149436711-4e797e09-e87d-4571-8725-f031ce6e8ef1.png)
表格暂无数据的国际化不生效
