### ISSUE TITLE
[Bug Report] 面包屑传递 to 属性传递无效

### ISSUE THREAD

**Issue by xiangxinji** [element-plus/element-plus#4939]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
mac

### Vue version
3.2.21

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-hb0w1?file=/src/App.vue

### Steps to reproduce
写入 to 属性, 然后进行点击
没有进行跳转

### What is Expected?
应该进行跳转,而且要进行 replace 逻辑

### What is actually happening?
他不进行跳转

**Comment by emojiiii** [comment]
please install  `vue-router-next`, see the [docs](https://element-plus.gitee.io/zh-CN/component/breadcrumb.html#breadcrumb-item-%E5%B1%9E%E6%80%A7)
