### ISSUE TITLE
[Bug Report] Select 选择器远程搜索问题

### ISSUE THREAD

**Issue by xuelingfei** [element-plus/element-plus#4945]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
FireFox 95.0.2

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/xuelingfei/pen/vYeewZj

### Steps to reproduce
1.输入搜索关键词alaska，下拉框呈现搜索结果label:Alaska
2.点击其他区域使选择器失去焦点，此时选择器内搜索关键词alaska会被自动清除
3.重新点击选择器，此时无搜索关键词，但下拉框仍呈现之前的搜索结果，只有一条数据

### What is Expected?
点击其他区域使选择器失去焦点时保留搜索关键词
或者 重新点击选择器时调用远程搜索对应函数重新获取下拉框选项

### What is actually happening?
如上复现步骤，在重新点击选择器时，无搜索关键词，下拉框却呈现之前的搜索结果，会让人误解为该选择框只有一个选项

**Comment by emojiiii** [comment]
我觉得需要默认需要保留这一次的搜索结果。
如果你想清空下拉框，我觉得你可以自行清空选项值

**Comment by xuelingfei** [comment]
> 我觉得需要默认需要保留这一次的搜索结果。 如果你想清空下拉框，我觉得你可以自行清空选项值

默认保留搜索结果的话，搜索条件也应该保留

**Comment by RenJie-Z** [comment]
没人回答吗？这都2023年了，这个问题该怎么解决啊？

**Comment by kooriookami** [comment]
远程搜索每一次打开应该清空值

**Comment by xuelingfei** [comment]
> 远程搜索每一次打开应该清空值

为了防止用户误认为选择器已有选中项，点击其他区域使选择器失去焦点时确实应该清空搜索关键词。但如果只清空搜索关键词而保留搜索结果（下拉框选项）的话，固然对于用户误操作使选择器失去焦点这一情况比较友好，但同样会导致再次展开选择器时搜索关键词和搜索结果不对应，可能导致用户会误以为该搜索结果是全部选择项
