### ISSUE TITLE
[Bug Report] 按钮和下拉菜单大小不一致

### ISSUE THREAD

**Issue by yangyining** [element-plus/element-plus#4946]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win11 / Edge  96.0.1054.62

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/yyn0210/dj3g8xp7

### Steps to reproduce
加入两个同一大小的按钮和下拉菜单

### What is Expected?
高度相同

### What is actually happening?
同一大小的按钮和下拉菜单高度差了两个像素

**Comment by qinpeip** [comment]
应该是图标的大小引起的，你设置下图标的大小就行了

**Comment by yangyining** [comment]
用svg的图标库好使了

> 应该是图标的大小引起的，你设置下图标的大小就行了
