### ISSUE TITLE
[Feature Request] 希望增加el-tree刷新方法，重新加载树

### ISSUE THREAD

**Issue by tongxin-77** [element-plus/element-plus#4949]
### Description
希望增加el-tree刷新方法，重新加载树

**Comment by emojiiii** [comment]
可以更描述一下使用场景和你希望达到的效果吗？

**Comment by tongxin-77** [comment]
> 可以更描述一下使用场景和你希望达到的效果吗？

懒加载时修改树的数据后需要刷新数据，重新获取树

**Comment by xiaoxian521** [comment]
same issues: https://github.com/element-plus/element-plus/issues/2940
