### ISSUE TITLE
[Feature Request] 希望el-upload 能暴露出remove file 方法

### ISSUE THREAD

**Issue by Xyuan-abs** [element-plus/element-plus#4951]
### Existing Component
是

### Component Name
el-upload

### Description
在 el-uoload 的  list-type="picture-card" 时，通过 #file="{file}" 插槽实现自定义缩略模板，由于插槽值提供了file对象，无法实现 移除功能，希望能暴露一个移除file 的方法

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/147426566-8fca48fb-79a9-4c53-b01b-c76d020f9010.png)

https://user-images.githubusercontent.com/21104054/147426775-d16f173b-de94-459c-bc7d-811d79a596c6.mp4


`handleRemove()` 这个删除文件的方法，实际上已经暴露给用户了，只是文档中没有写出来。
我会补充一下文档。

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/147469271-591645ef-8b14-4036-b7bb-935452979f1e.png)
现在只需要一个参数了
