### ISSUE TITLE
[Feature Request] 类Excel单元格编辑

### ISSUE THREAD

**Issue by iamjxc** [element-plus/element-plus#4953]
### Existing Component
Yes

### Component Name
Table

### Description
表格进入类似 Excel 的单元格编辑状态， 每次只能编辑一个单元格， 这样同一列只需创建一个 editor 控件，对性能也比较友好。
表格编辑完毕后，需要记录发生变更的数据行，并且校验数据格式；
表格通过 validate（）方法，验证录入的数据格式是否有问题；
通过调用 getChanges（）获得变更的数据行，提交给后台。

**Comment by pungfen** [comment]
你自己二次封装封装不就ok的事情.....组件库不能给你这样搞喔

**Comment by iamjxc** [comment]
感谢您的答复。
您说的二次封装，对我们做应用开发来说，难度还是太大了。我们期望是有一款开箱即用的企业级UI库。
我公司目前使用的MiniUI组件库（基于jquery)，该组件库有很多企业级的功能，但是目前业界基于Vue的 UI 库都没有对应功能。


我们对标了主流的几款UI库, 形成了类似下面的表格, 您有时间可以关注下。








这是详细对比表格
https://docs.qq.com/sheet/DSG1wY3hOb2dZelVN


| |
jxc
|
|
***@***.***
|
在2021年12月30日 ***@***.***> 写道：

你自己二次封装封装不就ok的事情.....组件库不能给你这样搞喔

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emojiiii** [comment]
我认为这个可能不适合做通用组件，但是可以作为`EP`的扩展业务组件 @JeremyWuuuuu  @sxzz cc

**Comment by sxzz** [comment]
这个做起来是大工程了，比如像 腾讯文档 这种。目前 EP 团队没有精力和计划去做额外的项目。
个人感觉和 Element Plus 通用 UI 库的定位也不同符合。可以看看其他开源项目。
