### ISSUE TITLE
[Bug Report] dropdown disabled 无效

### ISSUE THREAD

**Issue by mentoorliubin** [element-plus/element-plus#4954]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
mac od

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/PchyMario/pen/QWqOLzb

### Steps to reproduce
dropdown disabled属性没有产生效果

### What is Expected?
dropdown disabled禁用

### What is actually happening?
dropdown disabled属性没有产生效果

**Comment by qinpeip** [comment]
![image](https://user-images.githubusercontent.com/25759354/147375661-c43b1119-dba3-4035-8955-a062ae6e7d1b.png)
你单词拼错了

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/147378845-55e2c5df-b734-4af0-992b-c8b7ff259e70.png)
![image](https://user-images.githubusercontent.com/21104054/147378854-4b3b2ce4-a368-48f2-b471-e5ba092175aa.png)
这个应该是正常的吧
@mentoorliubin 你有什么补充吗

**Comment by mentoorliubin** [comment]
> ![image](https://user-images.githubusercontent.com/21104054/147378845-55e2c5df-b734-4af0-992b-c8b7ff259e70.png) ![image](https://user-images.githubusercontent.com/21104054/147378854-4b3b2ce4-a368-48f2-b471-e5ba092175aa.png) 这个应该是正常的吧 @mentoorliubin 你有什么补充吗

忘记截图了.drop-down-item是有效的,但是dropdown是无效的，无法让整个下拉菜单都禁用
![image](https://user-images.githubusercontent.com/52729282/147379069-8dbab30c-3812-46c9-af64-2ccf0504e6fb.png)

**Comment by xiaoxian521** [comment]
The latest version has been resolved
