### ISSUE TITLE
[Bug Report] Dropdown 下拉菜单 placement 文档默认bottom 但运行后是left 而且修改placement 值后还是left

### ISSUE THREAD

**Issue by xuwei5616** [element-plus/element-plus#4969]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
google

### Vue version
3.2.26

### Steps to reproduce
vite 集成element plus 

### What is Expected?
能够正常显示

### What is actually happening?
Dropdown 下拉菜单 placement 文档默认bottom 但运行后是left 而且修改placement 值后还是left

**Comment by lzq920** [comment]
@xuwei5616 可能是你的屏幕空间不够了？

**Comment by xuwei5616** [comment]
新版和旧版的有区别，触发的在屏幕右侧，老版的可以在下方显示，，新版的需要改宽才可以，代码都是从老版的改成vue3的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月28日(星期二) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Bug Report] Dropdown 下拉菜单 placement 文档默认bottom 但运行后是left 而且修改placement 值后还是left (Issue #4969)





 
@xuwei5616 可能是你的屏幕空间不够了？
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
