### ISSUE TITLE
[Feature Request] The doc on how to use element-plus 's icon needs to be improved

### ISSUE THREAD

**Issue by fullmooooon** [element-plus/element-plus#4978]
### Existing Component
Yes

### Component Name
@element-plus/icons-vue

### Description
I think it's too difficult for beginners to see how documents import'@ element-plus/icons-vue' globally.

**Comment by lzq920** [comment]
做法跟Vue注册全局组件其实是一样的，建议查看Vue文档

**Comment by fullmooooon** [comment]
> 做法跟Vue注册全局组件其实是一样的，建议查看Vue文档

全局引入element-plus 在文档的快速开始中是有代码示例的，而如何引入 icon 完全没有，我觉得这个对于一些人（包括我）单看文档是不知道如何引入 icon

**Comment by lzq920** [comment]
@fullmooooon 
[全局注册](https://v3.vuejs.org/guide/component-registration.html#global-registration)
[文档地址](https://doc-archive.element-plus.org/#/zh-CN/component/icon)

**Comment by fullmooooon** [comment]
> @fullmooooon [全局注册](https://v3.vuejs.org/guide/component-registration.html#global-registration) [文档地址](https://doc-archive.element-plus.org/#/zh-CN/component/icon)

element-plus 其他部分文档都有代码参照，只有 icon 这个没有，我不是来寻求帮助，我百度一下当然知道怎么做。我的意思是文档没有给出代码示例

**Comment by lzq920** [comment]
> > @fullmooooon [全局注册](https://v3.vuejs.org/guide/component-registration.html#global-registration) [文档地址](https://doc-archive.element-plus.org/#/zh-CN/component/icon)
> 
> element-plus 其他部分文档都有代码参照，只有 icon 这个没有，我不是来寻求帮助，我百度一下当然知道怎么做。我的意思是文档没有给出代码示例

这个意思啊，你提一个文档的PR就好了嘛

**Comment by xiaoxian521** [comment]
![image](https://user-images.githubusercontent.com/44761321/148148702-17a3ac9c-9949-4200-813e-50584622fd2f.png)
For code examples, please refer to https://github.com/sxzz/element-plus-best-practices

**Comment by fullmooooon** [comment]
https://element-plus.gitee.io/zh-CN/component/icon.html
新版文档关于icon的部分说的不明不白
https://doc-archive.element-plus.org/#/zh-CN/component/icon
老文档写的明白多了
