### ISSUE TITLE
[Bug Report] 关于低版本浏览器打包后报错的问题

### ISSUE THREAD

**Issue by maxiangrui1995** [element-plus/element-plus#4991]
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Google Chrome 63.0.3239.132

### Vue version
3.2.26

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
按钮 el-button 打包
低版本浏览器报错 Invalod regular expression： /^\p{Unified_Ideograph}{2}$/: Invalid escape

### What is Expected?
Invalod regular expression： /^\p{Unified_Ideograph}{2}$/: Invalid escape

### What is actually happening?
Invalod regular expression： /^\p{Unified_Ideograph}{2}$/: Invalid escape

**Comment by emojiiii** [comment]
很抱歉，因为`button`组件内使用的`Unified_Ideograph` 判断汉字，浏览器需要`Chrome64 Safari 11.1`以上版本才有效，我们会尽快解决这个问题的

**Comment by emojiiii** [comment]
如果你要兼容 `Chrome 63`
如果是`@babel/env 7.7`以上，转译配置已经带有这个正则的转译，可以配置`browserslist` 版本
如果是低于上述版本，我会建议你使用`@babel/plugin-proposal-unicode-property-regex` 进行转译
@maxiangrui1995

**Comment by wsqrin** [comment]
内核70依然不显示
