### ISSUE TITLE
[Bug Report] DateTimePicker  has not value-format attr

### ISSUE THREAD

**Issue by wk1127** [element-plus/element-plus#4995]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
1.2.0

### Vue version
3.2.26

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### What is Expected?
Support this property

### What is actually happening?
The previous version had this property, but now it's gone, and I need to introduce a third party library to handle time separately

**Comment by lzq920** [comment]
value-format属性依旧是可用的，虽然文档遗漏了

**Comment by lzq920** [comment]
@wk1127 value-format属性依旧是可用的，虽然文档遗漏了
