### ISSUE TITLE
[Bug Report] menu组件不开启router模式时的select事件不再返回 menu-item 的route参数

### ISSUE THREAD

**Issue by YuanDaoDao001** [element-plus/element-plus#5000]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
windows最新版chrome

### Vue version
3.2.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-cn9oi?file=/src/App.vue

### Steps to reproduce
直接输出参数

### What is Expected?
不开启router模式势必要自定义跳转，但新版本中@select 事件，在不开启router模式的情况下，不再返回 menu-item 的route参数，这就导致无法根据route参数自定义跳转

### What is actually happening?
无法获取route参数，无法自定义跳转

**Comment by lzq920** [comment]
> 

你可以把router参数绑定在index上面

**Comment by YuanDaoDao001** [comment]
> > 
> 
> 你可以把router参数绑定在index上面

最后就是这样搞的

**Comment by xiaoxian521** [comment]
same issues: https://github.com/element-plus/element-plus/issues/3843

**Comment by ancheGT** [comment]
我也遇到了,绑定给route的,取出来的时候一直是undefined

**Comment by ancheGT** [comment]
我也遇到了,绑定给route的,取出来的时候一直是undefined,单我用的最新的 1.3.0-beta.5.
@xiaoxian521 nemu item 有没有额外的参数,便于菜单携带参数,或者能透传?
