### ISSUE TITLE
[Bug Report] Tooltip 文字提示，鼠标在多个Tooltip上晃动会出现黑色菱形块(官网页面示例上会出现)

### ISSUE THREAD

**Issue by tongxin-77** [element-plus/element-plus#5003]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome  96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr/

### Steps to reproduce
鼠标放在多个tooltip上快速晃动

### What is Expected?
没有黑色菱形块出现

### What is actually happening?
黑色菱形块

**Comment by emojiiii** [comment]
Duplicate of #4837
