### ISSUE TITLE
[Bug Report] 表单验证功能和input插槽suffix同时存在时，Form表单status-icon为false失效

### ISSUE THREAD

**Issue by yangguanglei** [element-plus/element-plus#5006]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows  /  Chrome 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/yangguanglei/pen/poWpKQz

### Steps to reproduce
光标聚焦到输入框，再离开触发rule校验 ———>显示bug

### What is Expected?
账号和密码输入框都不应该出现校验提示图标

### What is actually happening?
密码输入框出现了校验提示图标

**Comment by gastrodia** [comment]
1.3.0-beta.1 这个问题还没修复吗 @emojiiii

**Comment by gastrodia** [comment]
![image](https://user-images.githubusercontent.com/96605737/147810558-5bbb95f8-8636-449b-88a4-493a0a156988.png)
