### ISSUE TITLE
el-pagination一些小疑问

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#501]
1.不传layout的 在查看dom结构的时候发现有一个el-pagination__rightwrapper结构 不知所云
默认值中的 -> 就是简单的想让后面的不渲染吗？ rightWrapperChildren 设计的意义在哪 是否能解答下
2.已经提取了usePagination.ts 还传props属性是否显得多余?

**Comment by zazzaz** [comment]
1. I do think we've missed some logic related to `rightWrapperChildren`. Thanks.

**Comment by JeremyWuuuuu** [comment]
I'll look into this.
