### ISSUE TITLE
[Bug Report] 动态绑定button type 无法更新

### ISSUE THREAD

**Issue by xixixida** [element-plus/element-plus#5015]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
96.0.1054.62

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/xixixida/pen/bGoaOrW

### Steps to reproduce
https://codepen.io/xixixida/pen/bGoaOrW
    <el-button @click="a= !a" :type="a?'primary':'info'">Previous Page</el-button>
点击这个按钮 样式无法改变

### What is Expected?
按钮能正确的显示样式

### What is actually happening?
按钮无法正确显示样式

**Comment by btea** [comment]
Duplicate #4637

**Comment by emojiiii** [comment]
你使用的不是 `1.2.0-beta.6`版本，请更新最新版本！
