### ISSUE TITLE
[Feature Request] table表格 添加多选时 允许设置label属性 文字描述

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#5022]
### Existing Component
Yes

### Component Name
1.2.0-beta.6

### Description
win10/谷歌浏览器最新版

**Comment by vela666** [comment]
<el-table-column type="selection" label="全选" width="55"> </el-table-column>  希望能把label的全选带上 如下图效果
![1](https://user-images.githubusercontent.com/69613314/147622227-1ad76bd1-bf92-4b3e-a1b5-227168882b12.jpg)

**Comment by vela666** [comment]
<el-table-column type="selection" width="55" label="全选"> </el-table-column>  
期望把label的值加上，如下图效果
![1](https://user-images.githubusercontent.com/69613314/147622291-fc32b501-4229-4d84-996a-c1f704cd8953.jpg)

**Comment by vela666** [comment]
` <el-table-column type="selection" width="55" label="全选"> </el-table-column>`  
实现该效果
![1](https://user-images.githubusercontent.com/69613314/147622336-4c9c33ed-55fd-4128-a9b9-0bbe28c67f1c.jpg)

**Comment by msidolphin** [comment]
建议和产品pk下

**Comment by emojiiii** [comment]
如果你要实现这样的效果，我建议你可以自己实现一列选择出来，然后用自定义表头来实现这个功能

**Comment by vela666** [comment]
> 如果你要实现这样的效果，我建议你可以自己实现一列选择出来，然后用自定义表头来实现这个功能
现在实现方式用伪元素实现的，我试试你的方式谢谢
