### ISSUE TITLE
[Bug Report] Tooltip 移动到某个点上，会定位到顶上去

### ISSUE THREAD

**Issue by 584832915** [element-plus/element-plus#5023]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
谷歌最新版

### Vue version
3.2.26

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
在element官网上，tooltip页，鼠标缓慢移动，tooltip会出现在最顶上，很好复现

### What is Expected?
元素出现位置正常

### What is actually happening?
tooltip出现位置不正常

**Comment by emojiiii** [comment]
Duplicate of #4837
