### ISSUE TITLE
[Feature Request] 表格排序事件获取的参数，当无排序时事件获取参数为null

### ISSUE THREAD

**Issue by vela666** [element-plus/element-plus#5024]
### Existing Component
Yes

### Component Name
el-table

### Description
<el-table @sort-change="test">
 
实现多列排序功能时该事件sort-change 触发后 在没有排序时 获取的参数为null,在旧版本中即使没有排序都可以获取到参数而不是为null
{column: Proxy, prop: "date", order: "ascending"}
{column: Proxy, prop: "date", order: "descending"}
{column: null, prop: null, order: null}

**Comment by cokemine** [comment]
https://github.com/element-plus/element-plus/pull/4640
duplicate with https://github.com/element-plus/element-plus/issues/4589

**Comment by wangping1511** [comment]
我找到一种方法
在 `el-table-column`  增加 `:sort-orders="['ascending', 'descending', 'none']"`

{column: Proxy, prop: "date", order: "ascending"}
{column: Proxy, prop: "date", order: "descending"}
{column: Proxy, prop: "date", order: "none"}

但是浏览器会报警报，暂时先实现功能

**Comment by xiaoxian521** [comment]
same issues: https://github.com/element-plus/element-plus/issues/4589
