### ISSUE TITLE
[Bug Report] 'Error: Dynamic require of "vue-demi" is not supported' when trying to use a Carousel with Nuxt3

### ISSUE THREAD

**Issue by cmmata** [element-plus/element-plus#5030]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows 11 / Firefox Developer 96.0b10 (64-bit)

### Vue version
3.2.26

### Reproduction Link
https://github.com/cmmata/nuxt3-elementPlus

### Steps to reproduce
- Clone the repository
- Execute `yarn install` to install all dependencies
- Execute `yarn dev` to start the dev server
- Open the browser with on the url / port that the dev server points to (usually http://localhost:3000)
- A blank page with the two arrows of the carousel should appear

### What is Expected?
It should show a Carousel with two cards, with the option to see both clicking on the arrow buttons

### What is actually happening?
Both cards are hidden and it's only loading the buttons. There's a javascript error which prevents the Carousel to work:

Uncaught (in promise) Error: Dynamic require of "vue-demi" is not supported
    NuxtJS 15
        __require
        node_modules
        __require2
        node_modules
        __require2
        js
        __require2
        js
        __require2
        js
        __require2
        js
        __require2
        js
        __require2
    <anonymous> element-plus_lib:1

**Comment by cmmata** [comment]
I am not 100% sure if this is an error of ElementPlus, or if it's a problem with Nuxt3. But I opened it here because I only found `vue-demi` dependency on this repo. If it does not depend on this repo, then I'm sorry, I'll create the issue on Nuxt3 repository.

**Comment by Upose** [comment]
hello,try import ElementPlus from 'element-plus/dist/index.full'

**Comment by Upose** [comment]
but if i use the el-dropdown,when i refresh page, my style is gone。the console also has a lot of warnings

like this:
Failed to resolve component: arrow-down
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/login" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <NuxtLayout key=0 name=undefined > 
  at <RouterView> 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>

**Comment by cmmata** [comment]
> hello,try import ElementPlus from 'element-plus/dist/index.full'

This works for me, thank you!

**Comment by cmmata** [comment]
I added an el-dropdown as you suggest, and I don't lose style. There's no much styling because it's a demo repository, but both the carousel and the drop-down have the styles I see in Element Plus website. What I see in console is

```
[Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: 
#text "\n  " (text) 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <ElPopper ref="triggerVnode" visible=false onUpdate:visible=fn  ... > 
  at <ElDropdown> 
  at <ElCol span=4 > 
  at <ElRow> 
  at <ElMain class="max-w-xl rounded" > 
  at <PortalIndex class="max-w-xl rounded" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined >  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <NuxtLayout key=0 name=undefined > 
  at <RouterView class="max-w-xl rounded" > 
  at <NuxtPage class="max-w-xl rounded" > 
  at <ElContainer class="is-vertical full-page" > 
  at <App> 
  at <NuxtRoot>
```

I updated this repository with the new code.

**Comment by ZuulAndRibbon** [comment]
> element-plus/dist/index.full

i add this.but it fails again.

**Comment by sunecosuri** [comment]
I have the same issue.

I haven't been able to figure out what the cause is yet, but I'll comment on it as a related issue.
https://github.com/vueuse/vueuse/issues/1069

**Comment by siryan2** [comment]
I would really like to use ElementPlus with Nuxt3. Is the support coming in the near future?

**Comment by xiaoxian521** [comment]
Already fixed：https://github.com/element-plus/element-plus-nuxt-starter/commit/98aa178d5031359d67653e1b5f5f7611ab94ca1f

**Comment by 516310460** [comment]
It seems that this problem always exists in the hydration node mismatch
