### ISSUE TITLE
[Bug Report] update from 1.1.0-beta.17 to 1.1.0-beta.18

### ISSUE THREAD

**Issue by RomanRadaykinFrontend** [element-plus/element-plus#5038]
### Element Plus version
1.1.0-beta.18

### OS/Browsers version
Ubuntu / Chrome v 96

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/

### Steps to reproduce
The project has updated the Element plus version to 1.1.0-beta.18.

"element-plus": "^1.1.0-beta.18"
"sass": "^1.43.2",
"sass-loader": "^8.0.2",

### What is Expected?
The project will be assembled normally

### What is actually happening?
Syntax Error: SassError: Undefined mixin.
  ╷
3 │ ┌ @include b(overlay) {
4 │ │     background-color: rgba($--blue-grey-800, 0.75);
5 │ └ }
  ╵
  src/assets/scss/override/overlay.scss 3:1  @import
  /home/roman/Рабочий стол/sodch-frontend/src/assets/scss/override/index.scss 9:9                                  root stylesheet

 @ ./src/assets/scss/override/index.scss 4:14-273 15:3-20:5 16:22-281
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.55:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

I assume that this is due to the replacement of Theme-chalk use @use instead of @import
Unfortunately, I can't attach a sample code.

**Comment by emojiiii** [comment]
please try to update `1.1.0-beta.24` version !

**Comment by RomanRadaykinFrontend** [comment]
@emojiiii On version 1.1.0-beta.24 version the situation has not changed. Ideally, I need version 1.2, I need a feature with datepicker, which was delivered only in 1.2

**Comment by emojiiii** [comment]
I didn't find this problem. Can you post your `vue.config.js ` and `package.json` ?
@RomanRadaykinFrontend

**Comment by RomanRadaykinFrontend** [comment]
@emojiiii 
https://github.com/RomanRadaykinFrontend/element/blob/main/package.json
https://github.com/RomanRadaykinFrontend/element/blob/main/vue.config.js

**Comment by emojiiii** [comment]
please try to change `prependData` to `additionalData` @RomanRadaykinFrontend
