### ISSUE TITLE
hope support import single component

### ISSUE THREAD

**Issue by adairxiao** [element-plus/element-plus#504]
I write Vue with JSX, I find it's undefined when I import Button in this way:

![image](https://user-images.githubusercontent.com/41007368/97553294-3a02e800-1a10-11eb-9d95-27df38df3fe5.png)

**Comment by AllenMRbai** [comment]
me too

**Comment by zazzaz** [comment]
will support this soon.

**Comment by JeremyWuuuuu** [comment]
We are working on this. This is definitely what we wanted to achieve.
