### ISSUE TITLE
[Bug Report] 官网Demo使用Codepen打开table示例 渲染异常

### ISSUE THREAD

**Issue by zhenghao9929** [element-plus/element-plus#5046]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win10 chrome92 bit 32

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/zhenghao9929/pen/PoJQEXb

### Steps to reproduce
https://codepen.io/zhenghao9929/pen/PoJQEXb

### What is Expected?
表格列头渲染成纵向排列
通过标签引入也有同样的问题

https://codepen.io/zhenghao9929/pen/PoJQEXb

### What is actually happening?
https://codepen.io/zhenghao9929/pen/PoJQEXb

**Comment by emojiiii** [comment]
please use `<el-table-column></el-table-column>` replace to `<el-table-column />`

**Comment by xiaoxian521** [comment]
这是Codepen的解析问题

**Comment by zhenghao9929** [comment]
用标签引入也会是同样的问题 不用codepen



| |
zhenghao9929
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月05日 18:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [element-plus/element-plus] [Bug Report] 官网Demo使用Codepen打开table示例 渲染异常 (Issue #5046) |

Closed #5046.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emojiiii** [comment]
Can you use `https://element-plus.run` to provide a mini repo ? @zhenghao9929

**Comment by zhenghao9929** [comment]
@emojiiii  please use <el-table-column></el-table-column> replace to <el-table-column /> its solved
