### ISSUE TITLE
[Bug Report] 表格数据，当空数据的时候仍然渲染列表，或疑似重复渲染，

### ISSUE THREAD

**Issue by OneSeven** [element-plus/element-plus#5055]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
chrome97

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/oneseven-the-bold/pen/dyVdKeN?editors=1111

### Steps to reproduce
```
<el-table :data="[]" style="width: 100%">
    <el-table-column prop="date" label="Date" width="180">
      {{test()}}
      </el-table-column>
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </el-table>
```
https://github.com/element-plus/element-plus/discussions/4819
### What is Expected?
不进行渲染执行

### What is actually happening?
空数据执行渲染

**Comment by msidolphin** [comment]
我想问有什么问题吗？这个column也需要承担表头的绘制工作，不要动不动随便乱喷

**Comment by OneSeven** [comment]
> Reference in new iss

??，你绘制表头，跟我表体有什么关系？至少element-ui2的逻辑不是这样，plus之前的版本好像也不是这样的，你真的有看过具体问题吗？
@iamkun
