### ISSUE TITLE
[Feature Request] 请问稳定版和虚拟表什么时候可以发布啊？

### ISSUE THREAD

**Issue by mingyangzhu** [element-plus/element-plus#5072]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win10

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/tree/feat/virtualized-table

### Steps to reproduce
请问稳定版和虚拟表什么时候可以发布啊？

### What is Expected?
虚拟表

### What is actually happening?
大数据表格  性能低下，有卡顿

**Comment by xiaoxian521** [comment]
https://github.com/element-plus/element-plus/discussions/3065
