### ISSUE TITLE
[Bug Report] 在use注册element时,全局设置的size失效

### ISSUE THREAD

**Issue by cn-troy** [element-plus/element-plus#5078]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Edge 96.0.1054.62 (官方内部版本) (64 位)

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-f4dnx?file=/src/main.js

### Steps to reproduce
1:main.ts中import element
2:main.ts中use element时添加配置size:"small"
3:在组件中使用el-button 或 el-input 或 el-table等..

### What is Expected?
全局设置失效

### What is actually happening?
当组件不设置size, 全局设置size, 则全局size生效

**Comment by cn-troy** [comment]
为什么要移除install中的配置参数呢?不太理解...#4793
如果大面积使用同一种尺寸, 就不需要每次都加一个size了呀..

**Comment by sxzz** [comment]
这可能是一个 bug，先尝试使用 `config-provider` 看看。

**Comment by lemonKun** [comment]
使用config-provider也不行，分页的total不能被正常解析成中文，变成了一堆英文

**Comment by cn-troy** [comment]
> 使用config-provider也不行，分页的total不能被正常解析成中文，变成了一堆英文

我是这样设置全球化的
![image](https://user-images.githubusercontent.com/4318293/147812993-a851fd85-036e-4d5d-a899-d4f1d8167747.png)

**Comment by cn-troy** [comment]
> 使用config-provider也不行，分页的total不能被正常解析成中文，变成了一堆英文

我是这样设置全球化的
![image](https://user-images.githubusercontent.com/4318293/147813047-6e1495d8-7d80-4d41-ae07-68ca715efc9d.png)

**Comment by lemonKun** [comment]
> > 使用config-provider也不行，分页的total不能被正常解析成中文，变成了一堆英文
> 
> 我是这样设置全球化的 ![image](https://user-images.githubusercontent.com/4318293/147813047-6e1495d8-7d80-4d41-ae07-68ca715efc9d.png)

可以了，感谢大佬

**Comment by Qingyewei** [comment]
这个问题有人解决了吗？我再次遇到了，好痛苦啊

**Comment by libbGit** [comment]
> 这个问题有人解决了吗？我再次遇到了，好痛苦啊

我准备放弃element-plus，每次更新一个版本，就会带出一个新问题。不敢用了
