### ISSUE TITLE
[Bug Report] Failed to access https://element-plus.org/#/zh-CN

### ISSUE THREAD

**Issue by louisyoungx** [element-plus/element-plus#5079]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Safari / Firefox / Chrome / Edge

### Vue version
3.2.26

### Reproduction Link
https://element-plus.org/zh-CN/

## 问题
打开网站 [`https://element-plus.org/zh-CN/#/zh-CN`](https://element-plus.org/zh-CN/#/zh-CN) 后显示空白，更换多个网络环境与ip地址，都是显示空白

Safari报错
```
[Error] Failed to load resource: the server responded with a status of 404 () (_commonjsHelpers.0592d25c.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (_commonjsHelpers.0592d25c.js, line 0)
[Error] Failed to load resource: 发生SSL错误，无法建立到该服务器的安全连接。 (UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2, line 0)
```
Chrome报错
```
element-plus.org/:11 GET https://element-plus.org/assets/_commonjsHelpers.0592d25c.js net::ERR_ABORTED 404
css:1 GET https://gstatic.loli.net/s/inter/v7/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2 net::ERR_CONNECTION_CLOSED
```

## 另外两个网站仍能正常访问

[https://doc-archive.element-plus.org/#/zh-CN](https://doc-archive.element-plus.org/#/zh-CN)

[https://element-plus.gitee.io/zh-CN/](https://element-plus.gitee.io/zh-CN/)

### What is Expected?
修复bug让[https://element-plus.org/zh-CN/#/zh-CN](https://element-plus.org/zh-CN/#/zh-CN)能正常访问

### What is actually happening?
访问[https://element-plus.org/zh-CN/#/zh-CN](https://element-plus.org/zh-CN/#/zh-CN)显示空白
- 更换过 Safari / Firefox / Chrome / Edge 浏览器
- 更换过网络环境与IP地址
- 更换过PC / MAC / 安卓移动端

**Comment by sxzz** [comment]
Please use https://staging.element-plus.org/ for temporarily. We will fix it ASAP.

**Comment by louisyoungx** [comment]
> Please use https://staging.element-plus.org/ for temporarily. We will fix it ASAP.

Thanks!

**Comment by YunYouJun** [comment]
Thanks. Fixed by https://github.com/element-plus/element-plus/pull/5081.
