### ISSUE TITLE
[Bug Report] 部分表单控件的字体突然变大

### ISSUE THREAD

**Issue by OrensDon** [element-plus/element-plus#5085]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Microsoft Edge 96.0.1054.62

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/OrensDon/pen/bGovGRJ

### Steps to reproduce
链接中的select字体明显比上个版本胖了一大圈，另外text button等也是一样

### What is Expected?
样式不变

### What is actually happening?
胖了一圈

**Comment by emojiiii** [comment]
please see [Breaking Change](https://github.com/element-plus/element-plus/discussions/5037)

**Comment by OrensDon** [comment]
> please see [Breaking Change](https://github.com/element-plus/element-plus/discussions/5037)

非常感谢各位的周到考量，不过稍微说一点，对input来说，default下的字体和large一样大，而small尺寸下的字体几乎贴到了input的边框，比上个版本的mini还要修长

**Comment by emojiiii** [comment]
> 非常感谢各位的周到考量，不过稍微说一点，对input来说，default下的字体和large一样大，而small尺寸下的字体几乎贴到了input的边框，比上个版本的mini还要修长
感谢你的建议

**Comment by YunYouJun** [comment]
@huangzhongzhong

**Comment by huangzhongzhong** [comment]
你好，我是负责这次修改的设计师，很抱歉这次新修改给你带来的不便。
我们之所以将 原先的 32px 输入框对应的字体13px加大到14px，是因为经过研究 14px 字体在多数常用显示器上的阅读效率最佳，而且 14px 字体对齐也更均衡，更符合全新的设计体系。加之14px也是目前 Ant、Arco、TDesign 等设计系统采用的通用默认字体大小。所以我们选择了 14px 作为全局的默认字体。

最小的small 尺寸 的input 高度从 28 调整到 24px，font-size依旧是一样的 12px，是会感觉较之前更拥挤。一方面这是为了符合全局规律的调整，另一方面也是为了提供更小的 input 供用户选择，在嵌入到各种组件中时也会占用更小的空间，拥有更好的表现。

每一个关键设计决策所能影响的方面都很多，我们正在努力从各种规则限制中求得当前的最优解，也欢迎您提供更好的建议。

**Comment by sevencitys** [comment]
> 你好，我是负责这次修改的设计师，很抱歉这次新修改给你带来的不便。
> 
> 我们之所以将 原先的 32px input 对应的 字体从 13px 加大到 14px，是因为经过研究 14px 字体在多数常用显示器上的阅读效率最佳，而且 14px 字体对齐也更均衡，更符合全新的设计体系。加之1 4px 也是目前 Ant、Arco、TDesign 等设计系统采用的通用默认字体大小，所以我们选择了 14px 作为全局的默认字体。
> 
> 最小的 small 尺寸 的 input 高度从 28 调整到 24px，font-size 依旧是一样的 12px，是会感觉较之前更拥挤。一方面这是为了符合全局规律的调整，另一方面也是为了提供更小的 input 供用户选择，在嵌入到各种组件中时也会占用更小的空间，拥有更好的表现。和字体大小一样，Ant、Arco、TDesign等设计系统的最小 input 高度也是 24px。与行业通用标准保持一致，能降低用户熟悉系统的心智成本，所以我们选择了 24px 作为 input、button 等组件的最小高度。
> 
> 每一个关键设计决策会影响的方面都很多，我们正在努力从各种规则限制中求得当前的最优解，希望给更多用户带来更好的体验，也欢迎你提供更好的建议。
> 
> 最后，更多详细解读说明请点击语雀链接查看，不定时更新~ https://www.yuque.com/docs/share/1e50bcb3-225c-42e5-a517-716867a681f5?#

对现有项目的伤害是很大的，这个修改真的很糟糕。

**Comment by supperdsj** [comment]
这个修改的确对现有项目伤害太大了
