### ISSUE TITLE
[Bug Report] 项目更新之后，按需引入全部提示 “These dependencies were not found:”

### ISSUE THREAD

**Issue by AK47-dadada** [element-plus/element-plus#5086]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Windows 10

### Vue version
3.2.26

### Reproduction Link
https://elementui.github

### Steps to reproduce
使用命令 $ npm install element-plus@latest 更新了element-plus之后,  $ npm run serve  vue-cli报错 “These dependencies were not found:”，我不清楚究竟发生了什么导致无法找到组件

### What is Expected?
正常运行

### What is actually happening?
 vue-cli报错 These dependencies were not found:

问题补充：

![image](https://user-images.githubusercontent.com/30396595/147810511-2b6160dc-3ca9-4eb2-a937-5ec924207f4f.png)

我确实没有做其它的操作，所以无法提供 Reproduction Link

**Comment by emojiiii** [comment]
can you post your `element.js` ?

**Comment by AK47-dadada** [comment]
`import {
  ElButton,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElSubmenu,
  ElContainer,
  ElHeader,
  ElMain,
  ElAside,
  ElCard,
  ElTag,
  ElImage,
  ElRow,
  ElCol,
  ElAvatar,
  ElProgress,
  ElLink,
  ElFooter,
  ElCarousel,
  ElCarouselItem
} from 'element-plus'

export default (app) => {
  app.use(ElButton)
  app.use(ElMenu)
  app.use(ElMenuItem)
  app.use(ElMenuItemGroup)
  app.use(ElSubmenu)
  app.use(ElContainer)
  app.use(ElHeader)
  app.use(ElMain)
  app.use(ElAside)
  app.use(ElCard)
  app.use(ElTag)
  app.use(ElImage)
  app.use(ElRow)
  app.use(ElCol)
  app.use(ElAvatar)
  app.use(ElProgress)
  app.use(ElLink)
  app.use(ElFooter)
  app.use(ElCarousel)
  app.use(ElCarouselItem)
}
`

**Comment by AK47-dadada** [comment]
`import {
  ElButton,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElSubmenu,
  ElContainer,
  ElHeader,
  ElMain,
  ElAside,
  ElCard,
  ElTag,
  ElImage,
  ElRow,
  ElCol,
  ElAvatar,
  ElProgress,
  ElLink,
  ElFooter,
  ElCarousel,
  ElCarouselItem
} from 'element-plus'

export default (app) => {
  app.use(ElButton)
  app.use(ElMenu)
  app.use(ElMenuItem)
  app.use(ElMenuItemGroup)
  app.use(ElSubmenu)
  app.use(ElContainer)
  app.use(ElHeader)
  app.use(ElMain)
  app.use(ElAside)
  app.use(ElCard)
  app.use(ElTag)
  app.use(ElImage)
  app.use(ElRow)
  app.use(ElCol)
  app.use(ElAvatar)
  app.use(ElProgress)
  app.use(ElLink)
  app.use(ElFooter)
  app.use(ElCarousel)
  app.use(ElCarouselItem)
}
`

**Comment by xiaoxian521** [comment]
After testing, no problem
![image](https://user-images.githubusercontent.com/44761321/147812842-75f6a458-9bd7-4a85-a31b-6e9185b4220f.png)

**Comment by AK47-dadada** [comment]
第二张图，请你把 import 'element-plus/dist/index.css'删了试试可以吗？不同的代码你跟我说没问题？

**Comment by AK47-dadada** [comment]
> After testing, no problem ![image](https://user-images.githubusercontent.com/44761321/147812842-75f6a458-9bd7-4a85-a31b-6e9185b4220f.png) ![image](https://user-images.githubusercontent.com/44761321/147812909-c3ff8776-aa4c-47bd-9c89-dd2b1232a88c.png)

第二张图，请你把 import 'element-plus/dist/index.css'删了试试可以吗？不同的代码你跟我说没问题？

**Comment by xiaoxian521** [comment]
Are you stupid
![image](https://user-images.githubusercontent.com/44761321/147813128-595af0d2-5f7d-4c17-8f82-d6c3535251f8.png)

**Comment by AK47-dadada** [comment]
> Are you stupid ![image](https://user-images.githubusercontent.com/44761321/147813128-595af0d2-5f7d-4c17-8f82-d6c3535251f8.png)

![image](https://user-images.githubusercontent.com/30396595/147813182-42bf6646-aad6-4db6-878b-d14ae28e346f.png)
所以说我不应该安装1.3.0 -beta 1 ???

**Comment by sxzz** [comment]
Please provide a minimum reproduction link (Github Repo). Without it, we can't give any help for you.

**Comment by AK47-dadada** [comment]
> Please provide a minimum reproduction link (Github Repo). Without it, we can't give any help for you.

我确实没做其他操作啊，只是在原来项目的基础上使用命令 npm install element-plus@latest然后npm run serve就报错了，确实被办法提供案例给你们啊，你们确定有认真测试过之后上线？
![image](https://user-images.githubusercontent.com/30396595/147813616-f2d826e8-b4f1-42ff-9c31-5b566272f629.png)
如上图所示，这也是我自己代码的问题吗？1.2版本没问题可以运行，更新到1.3就这样

**Comment by sxzz** [comment]
没有复现代码，的确很难了解到问题所在。尝试删除 node_modules 重新 install 下。https://github.com/element-plus/element-plus-issue-helper 这个项目已经用上了最新版本，没有问题的。

**Comment by AK47-dadada** [comment]
> 没有复现代码，的确很难了解到问题所在。尝试删除 node_modules 重新 install 下。https://github.com/element-plus/element-plus-issue-helper 这个项目已经用上了最新版本，没有问题的。

我担心可能存在这个问题，所以我删除了 node_module install了，但是还是这样啊，行不行啊，不行换俩开发好吗？别硬撑

**Comment by emojiiii** [comment]
> 没有复现代码，的确很难了解到问题所在。尝试删除 node_modules 重新 install 下。https://github.com/element-plus/element-plus-issue-helper 这个项目已经用上了最新版本，没有问题的。

有没有可能是那个自动导入的插件的问题？

**Comment by sxzz** [comment]
@AK47-dadada 你牛逼你自己写去啊，什么信息都没提供，我当我算命的呢？

**Comment by AK47-dadada** [comment]
> @AK47-dadada 你牛逼你自己写去啊，什么信息都没提供，我当我算命的呢？
你去算命还会好点，这种玩意拿出来开源，icon行高问题到现在直接跑不起来，没本事别维护，早点回家种地去好么

**Comment by JeremyWuuuuu** [comment]
如果你觉得你的祖国不好

你就去建设它

如果你觉得政府不好

你就去考公务员去做官

如果你觉得人民没素质

就从你开始做一个高素质的公民

如果你觉得同胞愚昧无知

就从你开始学习并改变身边的人

而不是一昧的谩骂，抱怨，逃离

如果你觉得 ElementPlus 不够好，我们欢迎你来一起建设 Element Plus。:)
