### ISSUE TITLE
New Component: replace the original Modal implementation with new Teleport API

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#51]
Since there is a built in API `teleport` we can easily add component's such as `Modal`, here are some test code I did on [codesandbox](https://codesandbox.io/s/vue-todo-list-app-with-single-file-component-0mfy2)

```vue
<template>
  <teleport :to="'#' + id">dynamic teleport in {{id}}</teleport>
</template>

<script>
const id = "test" + (Math.random() * 1000).toFixed(0)

export default {
  data() {
    return {
      id
    }
  },

  created() {
    const div = document.createElement("div")
    div.id = id
    console.log(div)
    document.body.appendChild(div)
  },

  methods: {}
}
</script>

<style lang="stylus">
</style>

```
This renders out: 
![image](https://user-images.githubusercontent.com/15975785/88643908-e32a0180-d0f4-11ea-983b-3dd97aa3a122.png)

**Comment by g3r4n** [comment]
@JeremyWuuuuu What is the aim of this ticket ? We already have Dialog #144 and Message-box is coming #204 . Do you want to create a Modal component or update the current ones to use teleport ?

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu What is the aim of this ticket ? We already have Dialog #144 and Message-box is coming #204 . Do you want to create a Modal component or update the current ones to use teleport ?

Indeed, I simply wanted to implement a general component that teleports the child component to wherever we wanted it to go, and it should be managed by this component. The current implementation which I am not very satisfied (I wanted to find the best practice for components like `Notification` which has already been implemented was good enough to me though).

**Comment by zazzaz** [comment]
done
