### ISSUE TITLE
Select drop Down doesnt load label

### ISSUE THREAD

**Issue by BrandonMendoza** [element-plus/element-plus#510]
Select drop down doesnt load label and shows ID's instead :(
In local works correctly but in Production server dont

![2020-10-29 (1)](https://user-images.githubusercontent.com/34587890/97646448-f5c21880-1a0c-11eb-9d09-aabf712125f7.png)

 <el-form-item label="Estatus" prop="status_id">
                        <el-select v-model="form.status_id" style="width: 100%;" :row-class-name="tableRowClassName">
                            <el-option 
                                v-for="status in statusList"
                                :key="status.id"
                                :label="status.nombre" 
                                :value="status.id"/>
                            </el-select>
                    </el-form-item>

variables: 
form:{
            status_id:1,
        },
statusList: [
            { id: 1, nombre: 'Sin Recibir' },
            { id: 2, nombre: 'Recibido' }, 
            { id: 3, nombre: 'Revisando' }
        ],

**Comment by JeremyWuuuuu** [comment]
Sorry, this is a bug that we will fix immediately.

**Comment by JeremyWuuuuu** [comment]
Another thing.. We are still in alpha stage, and some feature might be broken, it's not suggested to use it in production project which might be kind of dangerous.

**Comment by JeremyWuuuuu** [comment]
Also, could you provide the code chunk that of this problem to use for investigation?

**Comment by JeremyWuuuuu** [comment]
So a quick reply here, 

I had a quick investigation for this issue which I cloned the starter repo [EP-starter](https://github.com/element-plus/element-plus-starter) 
And build with this:

![image](https://user-images.githubusercontent.com/15975785/97658557-83eadd00-1aa7-11eb-8312-1b793a8d431f.png)
Via command `yarn build`

Then I used [Server](https://www.npmjs.com/package/serve) with command `serve ./dist` resulting with:

![image](https://user-images.githubusercontent.com/15975785/97658602-b268b800-1aa7-11eb-9ccd-5ea054ac0edb.png)

**Comment by JeremyWuuuuu** [comment]
@BrandonMendoza Hey, have you solved the bug?

**Comment by JeremyWuuuuu** [comment]
Closing since no further response.
