### ISSUE TITLE
[Bug Report] text in selector-v2 component doesn't recover to normal style when the dropdown list is closed

### ISSUE THREAD

**Issue by TeCHiScy** [element-plus/element-plus#5105]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Windows 11 21H2, Google Chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/techiscy/pen/YzraEKQ

### Steps to reproduce
Please see the code attached. The step is:

1. click on the select component, a dropdown list is shown, and the text in the component becomes gray, which indicates that we are in select mode 
2. click on the select component again, the dropdown list is closed, but the text in the component remains gray.

It seems that only when selector component lost foucs, the text recover the its normal style (black).

If this is a expected behavior, please let me know, thanks!

### What is Expected?
The text in the selector component returns to black color when the dropdown list is closed.

### What is actually happening?
The text in the selector component remains gray.

**Comment by emojiiii** [comment]
this is a expected behavior @TeCHiScy
