### ISSUE TITLE
[Bug Report] el-select-v2 选中的 label 未清空

### ISSUE THREAD

**Issue by xiaohaiH** [element-plus/element-plus#5107]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win10 chrome 83.0.4103.61

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/xiaohai/pen/mdBxLpN?editors=1010

### Steps to reproduce
1: 点击设置
2: 点击清空

element-plus\packages\components\select-v2\src\useSelect.ts?line=657
是否可以在 initStates 函数中判断, 当 props.modelValue.length 小等于 0 时手动将 states.cachedOptions = []; 置为空数组

### What is Expected?
显示 placeholder

### What is actually happening?
选中的 label 还显示在界面中

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/147999286-fb1760aa-6125-4770-aec4-10b8af243368.mp4

我这边点击“设置”和“清空”都是正常的，清空后也显示了palceholder
