### ISSUE TITLE
[Bug Report] 使用Vite自动导入时ELMessage无法显示

### ISSUE THREAD

**Issue by 838239178** [element-plus/element-plus#5108]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
newest

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/iamkun/pen/NONONO

### Steps to reproduce
```js
//vite.config.js
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({
  plugins: [
    vue(),
    AutoImport({
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      resolvers: [ElementPlusResolver()],
    }),
  ],
```
```vue
//xxx.vue
import { ElMessage } from 'element-plus';
ElMessage.error(error.msg)
```

### What is Expected?
修复这个错误

### What is actually happening?
无法显示ELMessage
控制台没有任何报错信息

**Comment by 838239178** [comment]
刚发现提示出现在屏幕右侧边缘且没有样式

![image](https://user-images.githubusercontent.com/55338151/147875540-62f799a9-7e61-463e-a4cd-428be0b54120.png)

**Comment by sxzz** [comment]
Please refer to https://github.com/sxzz/element-plus-best-practices

**Comment by 838239178** [comment]
怎么在codepen复现因为自动导入引起的问题😅

**Comment by sxzz** [comment]
You can upload minimum reproduction code to Github Repo.

**Comment by buqiyuan** [comment]
你可能还需要手动引入样式文件：import 'element-plus/es/components/message/style/css'

[原因见官方说明](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#manually-import)

**Comment by xiaoxian521** [comment]
It is good, please refer to this link https://github.com/sxzz/element-plus-best-practices
![image](https://user-images.githubusercontent.com/44761321/148045554-8738c046-8f19-4700-8eee-4d2c04f9a4d3.png)
