### ISSUE TITLE
[Bug Report] The input  is not controlled after global size configuration (通过$ELEMENT全局设置size=”small“  输入框未受控制)

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5112]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win11

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
The input  is not controlled after global size configuration
`app.config.globalProperties.$ELEMENT = { size: 'small', zIndex: 3000 }`

The previous version was normal

### What is Expected?
The size of the `el-input` is controlled

### What is actually happening?
`el-input` size is not controlled

**Comment by emojiiii** [comment]
Duplicate of #5079

**Comment by gjfei** [comment]
> [#5079 的](https://github.com/element-plus/element-plus/issues/5079)重复[](https://github.com/element-plus/element-plus/issues/5079)
这个哪里重复了？你在乱搞？

**Comment by emojiiii** [comment]
i' so sorry. Duplicate of #5078

**Comment by gjfei** [comment]
> 我很抱歉。重复#5078

please update doc

**Comment by emojiiii** [comment]
> please update doc

Thank you for your reminder. I'll change it as soon as possible

**Comment by emojiiii** [comment]
by the way, please see [breaking change](https://github.com/element-plus/element-plus/discussions/5037)
Remove global config `app.config.globalProperties.$ELEMENT = { size: 'small', zIndex: 3000 }` , please use `app.use or config-provider`

**Comment by mxp131011** [comment]
`config-provider`  支持`size`吗我看文档中只写支持国际化，没看到支持`size`和`zIndex`

**Comment by gjfei** [comment]
> `config-provider` 支持`size`吗我看文档中只写支持国际化，没看到支持`size`和`zIndex`

实际上是支持的，文档没更新， 然后size 大小都改掉了，为了所谓和行业对其

**Comment by emojiiii** [comment]
I'll change it as soon as possible

**Comment by gjfei** [comment]
> 我会尽快更改

修改size 就是为了和行业对齐？ element-ui 这么多年了，突然来一个行业对齐就改变一个重要样式，这个是不是太那个啥了？

**Comment by emojiiii** [comment]
以后我们都会通过 `config-provider` 这种配置的形式来进行控制。
因为这样可以更小粒度控制页面某个区域的配置，这样相对以前会更灵活(黑暗模式, 某个类型的组件配置)

**Comment by mxp131011** [comment]
` large / default / small`  改成 ` large / middle / small`  更语义化吧， 我全局设置成`small` 后  `default` 不应该代表`small` 吗？

**Comment by emojiiii** [comment]
`default` 代表的是你没有任何设置时的意义，如果你通过配置更改了，在组件库看来已经不是`default`了，但是在你们具体业务项目中可能会觉得`small`是`default`

**Comment by mxp131011** [comment]
所以我还是觉得  `large / middle / small` 更语义化，不存在歧义
