### ISSUE TITLE
[Feature Request] 树的节点新增一种状态

### ISSUE THREAD

**Issue by ALI1416** [element-plus/element-plus#5114]
### Existing Component
Yes

### Component Name
Tree 树形控件

### Description
现在树的节点有3种状态，分别是：未选择、子节点部分选择、全部选择(子节点全部选择，自己也选择)。
希望新增1种状态：子节点全部选择，但自己未选择。

**Comment by emojiiii** [comment]
Do you mean like `checkStrictly` attributes in `el-cascader`  ?

**Comment by ALI1416** [comment]
我没有用过cascader这个控件。具体需求是这样的：
例如以下树和指定id
![1](https://user-images.githubusercontent.com/39152510/148001102-588a7a6b-ad2a-4908-af36-6c5a18ae581e.jpg)
当全部未选择时，返回[]
![2](https://user-images.githubusercontent.com/39152510/148001254-269e43b2-80e3-4ee9-832e-6da57d7c1638.jpg)
当子节点部分选择，返回[2]
![3](https://user-images.githubusercontent.com/39152510/148001348-bace3462-fb97-4d96-807d-80965865694c.jpg)
当全部选择(子节点全部选择，自己也选择)，返回[1]
![5](https://user-images.githubusercontent.com/39152510/148001415-60701aa2-6d0d-4564-a2f0-1882dacac2b4.jpg)
新需求：当子节点全部选择，但自己未选择，返回[2,3]，父节点的样式也要变化
![4](https://user-images.githubusercontent.com/39152510/148001460-477bd910-2ebb-471a-932a-c239d3d955eb.jpg)

**Comment by msidolphin** [comment]
> 我没有用过cascader这个控件。具体需求是这样的： 例如以下树和指定id ![1](https://user-images.githubusercontent.com/39152510/148001102-588a7a6b-ad2a-4908-af36-6c5a18ae581e.jpg) 当全部未选择时，返回[] ![2](https://user-images.githubusercontent.com/39152510/148001254-269e43b2-80e3-4ee9-832e-6da57d7c1638.jpg) 当子节点部分选择，返回[2] ![3](https://user-images.githubusercontent.com/39152510/148001348-bace3462-fb97-4d96-807d-80965865694c.jpg) 当全部选择(子节点全部选择，自己也选择)，返回[1] ![5](https://user-images.githubusercontent.com/39152510/148001415-60701aa2-6d0d-4564-a2f0-1882dacac2b4.jpg) 新需求：当子节点全部选择，但自己未选择，返回[2,3]，父节点的样式也要变化 ![4](https://user-images.githubusercontent.com/39152510/148001460-477bd910-2ebb-471a-932a-c239d3d955eb.jpg)

我觉得你需要和产品pk下，这个需求很没逻辑啊

**Comment by ALI1416** [comment]
我是在做动态路由管理的时候遇到的问题：
比方说有以下路由路径：
/a (匹配/a/*)
--/a/b (匹配/a/b)
--/a/c (匹配/a/c)
当我选择/a时，他匹配/a/*，即使我再添加一个路由/a/d，他也是可以匹配到的
新需求是：我只选择/a/b和/a/c ，即使添加路由/a/d，他也是无法匹配的
这样可以做到权限的最小化分配

**Comment by emojiiii** [comment]
你这个问题我没看出跟上分的需求有什么必然联系。因为你这种树形节点是有父子关系的，你分配了 /a/b 和 /a/c，你添加了路由/a/d时，子节点 /a/d不勾选也不应该有权限。所以我不是很懂你这个动态路由管理设计有什么问题？

**Comment by ALI1416** [comment]
不好意思，md文档把`*`这个字符给转义了，可能有误解，我重新描述下吧：
比方说有以下路由路径(/a下面只有2个路径)：
/a (匹配/a/\*)
--/a/b (匹配/a/b)
--/a/c (匹配/a/c)
当我选择/a时，他匹配/a/\*，即使我再添加一个路由/a/d，他也是可以匹配到的
新需求是：当我选择/a时，实际他选择的是/a/b和/a/c ，即使添加路由/a/d，他也是无法匹配的
这样可以做到权限的最小化分配

**Comment by emojiiii** [comment]
可以看看`el-cascader` 组件是否可以满足你的需求，使用里面的`checkStrictly` 属性

**Comment by ALI1416** [comment]
不行诶，老板不喜欢`Cascader 级联选择器`的样式，可以麻烦在`Tree 树`里加上这个`checkStrictly`属性吗

**Comment by emojiiii** [comment]
很抱歉，恐怕暂时没有精力投放在这里，这个功能请求改动相当复杂。

**Comment by ALI1416** [comment]
好的吧，总之谢谢你们了
