### ISSUE TITLE
QQ浏览器兼容问题 --  ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by hehaiyun** [element-plus/element-plus#5118]
![1641260557(1)](https://user-images.githubusercontent.com/41280313/147998657-dbddb932-44a3-4fc4-85ae-a37d2f4faf93.png)

**Comment by dengqichang** [comment]
老哥，我也遇到这个问题，请问解决了吗？

**Comment by sxzz** [comment]
自行升级浏览器，文档站不太考虑兼容性的。
