### ISSUE TITLE
[Bug Report] input-number 设置属性 controls-position="right" 不显示decrease按钮

### ISSUE THREAD

**Issue by cxj-github** [element-plus/element-plus#5120]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-demo-forked-418pt

### Steps to reproduce
直接看效果

### What is Expected?
显示加减按钮

### What is actually happening?
只显示了加按钮

**Comment by huisir001** [comment]
+1

**Comment by Alanscut** [comment]
此bug已被修复，感谢您的反馈，请等待新版本发布
