### ISSUE TITLE
[Feature Request] `.el-badge__content` should use a unique-name with css var to custom border-color

### ISSUE THREAD

**Issue by xiangqunXiao** [element-plus/element-plus#5124]
### Existing Component
Yes

### Component Name
badge

### Description
currently, the `border` field inside `.el-badge__content`  use css var `--el-color-white` directly to set border color.

I think it is not good idea when developers want to custom border-color, what about adding `--el-badge-border-color` so that developers are able to custom border-color by overriding it?

If you think it's a good idea. I am glad to contribute my code😊.

**Comment by emojiiii** [comment]
I think it's easy to set the custom border color with `--el-color-white`, just set it in any parent node

**Comment by xiangqunXiao** [comment]
> I think it's easy to set the custom border color with `--el-color-white`, just set it in any parent node

ok,i wii close it
