### ISSUE TITLE
[Feature Request] Add a requiredMessage attribute  to FormItem

### ISSUE THREAD

**Issue by loogn** [element-plus/element-plus#5126]
### Existing Component
Yes

### Component Name
FormItem

### Description
Whether the FormItem component can add a requiredMessage attribute, combined with the required attribute to display custom verification information ?

**Comment by emojiiii** [comment]
please see [docs](https://element-plus.gitee.io/zh-CN/component/form.html#formitem-%E5%B1%9E%E6%80%A7)

**Comment by msidolphin** [comment]
You can use `rules` to configure message
