### ISSUE TITLE
[Bug Report] el-pagination attr layout is not the same as expected

### ISSUE THREAD

**Issue by renweiguo** [element-plus/element-plus#5132]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
windowMicrosoft Edge 96.0.1054.62

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/renweiguo/pen/MWEGGrp

### Steps to reproduce
1. The char '->' in layout attribute is not same to expected layout, the elements on its right are not on right. I found it is ok when i remove 'display:inline-flex' in the '.el-pagination'.
2. How to make pagers to change automatic when the page-size changed?

### What is Expected?
1. The layout is same to expected.
2. The pagers changed automatic.

### What is actually happening?
1. The elements on right of '->' is not on right.

**Comment by DSzhongweizi** [comment]
Indeed, it now looks more like the char '<-'
