### ISSUE TITLE
Behavior about Tooltip

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#514]
```html
<el-tooltip content="content" placement="top">
    <el-button disabled>button</el-button>
</el-tooltip>
```
When `el-button` is disabled, `el-tooltip` dosen't show. Is that the expected behavior?
![image](https://user-images.githubusercontent.com/38392315/97682635-25d3ef00-1ad3-11eb-8b5f-83ab9d368776.png)

```html
<el-tooltip content="content" placement="top">
    <div style="display: inline-block">
        <el-button disabled>button</el-button>
    </div>
</el-tooltip>
```
![image](https://user-images.githubusercontent.com/38392315/97682430-181e6980-1ad3-11eb-8c15-652a5bd47cbd.png)
When there's a `div`, `el-tooltip` show.

**Comment by JeremyWuuuuu** [comment]
So, quick answer is yes when it's disabled, it should not show
`Tooltip` attaches to the first descendent, in your case, it was attached to `div` instead of `el-button`, because your `div` is not a disabled element, so the tooltip behaves correctly.

**Comment by JeremyWuuuuu** [comment]
For any cases like this it is not suggested that user wrapping the disabled component inside a non-disabled component or tag, WE DO NOT KNOW IF IT IS DISABLED, there's no way that `tooltip` traverses the entire subtree.

**Comment by kooriookami** [comment]
OK, thanks.
