### ISSUE TITLE
[Bug Report] el-table 设置fixed="left" 且设置max-height  最后添加#append插槽时，如果不算#append插槽的内容高度就没有超过max-height （算上#append插槽插槽内容就超过max-height）时 没有上下滚动条

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5147]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win11 /  Microsoft Edge

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/mxp131011/pen/mdByNPG

### Steps to reproduce
`el-table` 添加 `max-height`   某个 `el-table-column` 添加 `fixed="left"`  然后添加 `<template #append></template>` 
当不算`#append`插槽的高度没有超过`max-height`高度，(但是算上`#append`插槽已经超过 `max-height`) 时没有上下滚动条，所以导致看不到`#append` 插槽的全部内容  （`#append` 插槽的部分内容还是可以看到） ，要想看到全部内容时必须要有上下滚动条，很遗憾时此种情况下没有上下滚动条

### What is Expected?
有上下滚动条，可以看到`#append`插槽的全部内容 

### What is actually happening?
没有上下滚动条，导致看不到`#append`插槽的全部内容

**Comment by Vadizar** [comment]
Since version 1.3.0-beta.6 it doesn't work again. Scrolling the header in the table is again very slow.
