### ISSUE TITLE
[Bug Report] el-popover  文档缺少  popper-append-to-body 说明

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5148]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win11

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
`el-popover` 文档缺少  `popper-append-to-body` 属性的说明，但是实际上是支持 `popper-append-to-body`  设置的，我不知道是忘记添加了还是后期打算不在支持 `popper-append-to-body`属性

### What is Expected?
`el-popover` 文档应该有  `popper-append-to-body` 属性的说明

### What is actually happening?
`el-popover` 文档缺少  `popper-append-to-body` 属性的说明

**Comment by emojiiii** [comment]
很抱歉，虽然是支持，但是 `props` 是没有这个属性的, 生效是因为使用了 `v-bind="$attrs"`
