### ISSUE TITLE
Could you please give priority to updating the components related to the following menu？

### ISSUE THREAD

**Issue by MaybeQHL** [element-plus/element-plus#515]
Very urgent

**Comment by JeremyWuuuuu** [comment]
Pardon?

**Comment by MaybeQHL** [comment]
@JeremyWuuuuu   NavMenu component   not found.

**Comment by JeremyWuuuuu** [comment]
NavMenu has not been completed yet. Might take a couple of days. You can track it #154

**Comment by MaybeQHL** [comment]
@JeremyWuuuuu ok,thanks 。可以中文提issue 吗？ 翻译的好累。

**Comment by JeremyWuuuuu** [comment]
Sure, I can read Chinese. But it's better that we keep using English throughout this project. Thx

**Comment by MaybeQHL** [comment]
@JeremyWuuuuu  ok,i get it

**Comment by aywan** [comment]
Issue #154 is done. 
Release new version to npm please

**Comment by zazzaz** [comment]
@aywan will do in the next few days, cheers

**Comment by zazzaz** [comment]
fixed in element-plus@1.0.1-alpha.15
