### ISSUE TITLE
[Feature Request] 尺寸大小的调整

### ISSUE THREAD

**Issue by huyuan9479** [element-plus/element-plus#5153]
### Existing Component
No

### Component Name
Button

### Description
想不明白为什么要把按钮的尺寸给调整了，多种选择不是更好吗，default为32px有点小，default为40px的有点大，之前的36的刚刚好，为什么要改变呢，真是瞎改

**Comment by huyuan9479** [comment]
这个版本改的有点拉跨

**Comment by huyuan9479** [comment]
尺寸要么大，要么小，没一点过渡，改的有点拉跨

**Comment by xiaoxian521** [comment]
https://github.com/element-plus/element-plus/discussions/5037
