### ISSUE TITLE
element-plus/lib/locale/lang/en   not found

### ISSUE THREAD

**Issue by MaybeQHL** [element-plus/element-plus#516]
A temporary solution: ![image](https://user-images.githubusercontent.com/34638673/97688207-c4ad1b00-1ad4-11eb-8f8d-67ee607c91d5.png)

**Comment by JeremyWuuuuu** [comment]
Sorry for the inconvenience.
Since we are actively working on the migration, the online version only had one single `index.js` module which can be found in the package.

The next stage we will try to expose as many members as the V2 version.

**Comment by zazzaz** [comment]
fixed in element-plus@1.0.1-alpha.15
