### ISSUE TITLE
[Bug Report] qq browser run error, run not up

### ISSUE THREAD

**Issue by dengqichang** [element-plus/element-plus#5171]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win10 / QQ浏览器最新版本

### Vue version
3.2.25

### Reproduction Link
https://github.com/dengqichang/vue3-basis-admin

### Steps to reproduce
The sample url：https://dengqichang.gitee.io/vue3-basis-admin  
The sample project：https://github.com/dengqichang/vue3-basis-admin  
steps：Error after installing element Plus and running in QQ browser（Uncaught ReferenceError: globalThis is not defined），Other major browsers are running normally

### What is Expected?
Install the introduction of Element Plus after running to qq browser normal compilation

### What is actually happening?
After Element Plus was installed, an error was reported when the project was run to the QQ browser

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/148316534-979276fd-987a-48bf-bd6c-489e0106cdcb.png)
![image](https://user-images.githubusercontent.com/38392315/148316573-168199be-36dc-4677-be2b-915c1a7a1f77.png)
The chromium version of QQ browser is too old, please use chrome or edge instead.

**Comment by littleboarx** [comment]
![image](https://user-images.githubusercontent.com/59130959/148325693-69bc8978-5528-4f61-bc64-1ad92ec6c26a.png)
as the Compatibility shows on your website page, chrome70 should be included in the support browsers.
and in my point of view, using globalThis is not a must for a browser-only libarary.

**Comment by dengqichang** [comment]
The latest version of QQ browser is chrome70, while globalThis is compatible with the minimum version of Chrome 71, so it will have to wait until QQ Browser updates to a higher version of Chrome.
![image](https://user-images.githubusercontent.com/33437919/148345996-1dd66364-d482-4a80-9821-6dda84093557.png)

**Comment by btea** [comment]
fix https://github.com/vueuse/vueuse/pull/1133

**Comment by ChenLuoi** [comment]
**workaround:**
`var globalThis = globalThis || this;`
