### ISSUE TITLE
[Bug Report] [el-loading]  以服务的方式调用的全屏 Loading 是单例的。bug

### ISSUE THREAD

**Issue by BigPengZai** [element-plus/element-plus#5182]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
版本 97.0.4692.71（正式版本） (arm64)

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0pcuu

### Steps to reproduce
```
const loadingInstance1 = ElLoading.service({ fullscreen: true })
const loadingInstance2 = ElLoading.service({ fullscreen: true })
console.log(loadingInstance1 === loadingInstance2) // true
```

### What is Expected?
期望结果：true

### What is actually happening?
测试结果：false

**Comment by weidehai** [comment]
应该是文档没更新，代码里面是第二次创建实例会先关闭前面的实例在创建

**Comment by lqh1008** [comment]
我用的也是这个版本，全局loading调用了，但是不会出现效果

**Comment by sxzz** [comment]
Fixed via #7110
