### ISSUE TITLE
[Bug Report] app.use(ElementPlus, { size: 'small', zIndex: 3000 }) 没有任何作用，服了

### ISSUE THREAD

**Issue by libbGit** [element-plus/element-plus#5188]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
window11，Misrosoft edge 96.0.1054.62

### Vue version
3.2.26

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
none

### What is Expected?
我不设置 button的大小。我只要全局设置small，那么所有组件都应该生效
app.use(ElementPlus, { size: 'small', zIndex: 3000 })

### What is actually happening?
我是真心服了1.2.0上， 出现了toolip连续两次浮上去，浮出框直接飘到浏览器顶部不。没办法，我升级到1.3.0。 又TM发现
我原来全局设置的
app.use(ElementPlus, { size: 'mini', zIndex: 3000 })不起作用了。一看log，原来mini用small替代了，

但是你要替代你就替代完全一点。
app.use(ElementPlus, { size: 'small', zIndex: 3000 })可偏偏漏了全局设置small的方式。搞的我要到几千个地方挨个加 size="small"吗？？ 醉了

**Comment by emojiiii** [comment]
If using app.use(ElementPlus, { size: 'small', zIndex: 3000 }) to set i18 or global size is invalid, you can refer to the solution

**Comment by emojiiii** [comment]
Duplicate of #5078
