### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by ZhangShiy** [element-plus/element-plus#519]
Does the project team have plans to support JSX

**Comment by JeremyWuuuuu** [comment]
Hi, could you please describe your issue more specifically? 
This project internally supports `jsx`.
If you were trying to use it in your project, you need to install `jsx-next` plugin

**Comment by ZhangShiy** [comment]
> Hi, could you please describe your issue more specifically?
> This project internally supports `jsx`.
> If you were trying to use it in your project, you need to install `jsx-next` plugin

```tsx
import { defineComponent } from 'vue';
import { Input } from 'element-plus';
import './login.scss';
export default defineComponent({
  name: 'login',
  setup() {
    return () => (
      <div class="login-wrap">
        <div class="login-box">
          <Input type="text"></Input>
        </div>
      </div>
    );
  }
});
```
it reported an error:

ERROR in src/pages/login/login.tsx:10:12
TS2786: 'Input' cannot be used as a JSX component.
  Its instance type 'Input' is not a valid JSX element.
    Property '$props' is missing in type 'Input' but required in type 'ElementClass'.

is there any mistakes?

**Comment by JeremyWuuuuu** [comment]
Well, the thing here is
`import { Input } from 'element-plus'`
actually imports a `installer function` which provides to the user to allow `app.use` to install it globally, the current released version does not contain any separated export of the component it self, if you need to use it like this, the steps needs to be taken:
1. At your app root, you must register the component globally.
```js
const app = Vue.createApp()
app.use(ElementPlus) // or app.use(Input)
```
2. In your render function:
```vue
import { resolveComponent } from 'vue'
export default {

  render() {
    const Input = resolveComponent('el-input')
    return <Input />
  }
}
```

This should work.

**Comment by JeremyWuuuuu** [comment]
FYI, we are working on export the actual components to users, sorry for the inconvenence.

**Comment by ZhangShiy** [comment]
> FYI, we are working on export the actual components to users, sorry for the inconvenience.
ok, thanks for your introduction. Looking forward to the release of the official version.

**Comment by sososoyoung** [comment]
Hello @JeremyWuuuuu , Thanks your work, Is there any update?

**Comment by lonk** [comment]
Hi @JeremyWuuuuu, is there any release planned for component export ?

Thank you for you work !
