### ISSUE TITLE
[Bug Report] Tree component bug

### ISSUE THREAD

**Issue by Nickx** [element-plus/element-plus#5194]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Mac OS 12.1 / Chrome 96

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/Nickx23/pen/MWEBKRb

### Steps to reproduce
add allowDrop method and drag any element

### What is Expected?
immediately move tree element

### What is actually happening?
element move after "back animation" finished

**Comment by emojiiii** [comment]
i'm sorry that i can not get what your mean.

**Comment by Nickx** [comment]
After dropping the element, animation of returning the element runs and only after that the tree structure is updated

[https://youtu.be/6EsikoEZ4uc](https://youtu.be/6EsikoEZ4uc)

> i'm sorry that i can not get what your mean.

**Comment by Nickx** [comment]
if allowDrop always returning "true" all fine

**Comment by msidolphin** [comment]
We don't have the "back" animation, what kind of browser are you using?

**Comment by Nickx** [comment]
> We don't have the "back" animation, what kind of browser are you using?

Mac OS 12.1 / Chrome 96 / Safari 15.2

**Comment by msidolphin** [comment]
> > We don't have the "back" animation, what kind of browser are you using?
> 
> Mac OS 12.1 / Chrome 96 / Safari 15.2

I think this is the default browser behavior, the component should not change position before element dropped, we will try to fix this issue
