### ISSUE TITLE
[Feature Request] With typescript,upload component hook :beforeUpload wants to be allowed to return Promise<boolean> 

### ISSUE THREAD

**Issue by lykl** [element-plus/element-plus#5198]
### Existing Component
是

### Component Name
upload

### Description
With typescript,upload component hook :beforeUpload wants to be allowed to return Promise<boolean> ,
Do the same if there are other similar hooks

**Comment by emojiiii** [comment]
please see [docs](https://element-plus.gitee.io/zh-CN/component/upload.html#attributes).
`before-upload` is allow to return Promise

**Comment by lykl** [comment]
> please see [docs](https://element-plus.gitee.io/zh-CN/component/upload.html#attributes). `before-upload` is allow to return Promise

Yes, I know, but the editor will tell you that the type is wrong

**Comment by emojiiii** [comment]
i'm sorry, `upload` type is error, it's refactoring in progress

**Comment by lykl** [comment]
> i'm sorry, `upload` type is error, it's refactoring in progress

Okay, let me know when the refactoring is complete

**Comment by emojiiii** [comment]
Maybe by next Sunday
