### ISSUE TITLE
[Feature Request] The current design is a little ugly when form's s label-positon = 'top'  and size="small"

### ISSUE THREAD

**Issue by xiangqunXiao** [element-plus/element-plus#5202]
### Existing Component
Yes

### Component Name
form

### Description
The current design is a little ugly when form's s label-positon = 'top' ,belows are the example code:
```
// the gap between `ID` and input is too wide
<el-form size="small" label-position="top">
      <el-form-item label="ID：">
        <el-input></el-input>
      </el-form-item>
</el-form>
```

maybe it is more beautiful when the padding value should adjust with form size
![image](https://user-images.githubusercontent.com/95326074/148498455-266b5b81-e899-4c9f-a73a-5dd5d436ac6a.png)

**Comment by JeremyWuuuuu** [comment]
@xiangqunXiao Already talked to the designer, we are going to make changes against it. Thank you for reporting this to us.

**Comment by xiangqunXiao** [comment]
> @xiangqunXiao Already talked to the designer, we are going to make changes against it. Thank you for reporting this to us.

Thanks. You can show your final conclusion here so that other developers are able to contribute it.
