### ISSUE TITLE
[Feature Request] [button] type 和 size 的默认值都是defalut，导致type不是default的时候class中还会存在el-button-default

### ISSUE THREAD

**Issue by Bell-1** [element-plus/element-plus#5204]
### Existing Component
Yes

### Component Name
ElButton

### Description
button type 和 size 的默认值都是defalut，导致type不是default的时候class中还会存在el-button-default
项目需要动态修改按钮颜色，当使用css覆盖样式的时候发现 当按钮type不是default的时候还是存在el-button-defalut，是因为没有设置size导致颜色不好覆盖。
因为button的颜色变量是在style里，最好官方提供一套动态修改主题的方案
https://codepen.io/bell-1/pen/bGojrbx

**Comment by hansonfang** [comment]
same issue

**Comment by YunYouJun** [comment]
This issue is because `default` here refers to size and not color.
Of course we will optimize it as soon as possible.
The dynamic theme scheme is under construction as we need to wait for the dark mode design.

**Comment by YunYouJun** [comment]
I create https://github.com/element-plus/element-plus/pull/6782 to fix it.
