### ISSUE TITLE
[Feature Request] optimization of Tabs

### ISSUE THREAD

**Issue by gyt95** [element-plus/element-plus#5206]
### Existing Component
是

### Component Name
标签页Tabs

### Description
从element-ui到element-plus，tabs在切换时，tabPane蓝色下划线过渡动画都是先改变长度再滑动。

这效果很奇怪。假如第一个tab-pane的label过长，第二个的label过短。当从第二个切换到第一个时，下划线突然变长，再滑动到指定tab-item，过渡动画不太友好。希望可以好像antd的tabPane那种过渡。

**Comment by purepear** [comment]
This should address the width transition https://github.com/element-plus/element-plus/pull/5223
Pls let me know if you think that a height transition is also needed for vertical tabs - i've skipped it on purpose because the vertical blocks usually have the same height.

**Comment by HeftyKoo** [comment]
Has been implemented by #5223.
