### ISSUE TITLE
[Bug Report] El-Input with clearable attribute had text need click twice to open keyboard on iOS Safari

### ISSUE THREAD

**Issue by st9140626** [element-plus/element-plus#5210]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
OS X 10.15.6 / Safari 15

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/st9140626/kg986fns/4/

### Steps to reproduce
When el-input with clearable attribute had inserted text, I need click twice to open input keyboard on iOS Safari.

### What is Expected?
When I touch the input, it will be auto focus and open the keyboard on iOS Safari.

### What is actually happening?
I need to click twice for each input with clearable attribute on iOS Safari.

**Comment by wxxcarl** [comment]
I had the same problem with el-select

**Comment by Red-Asuka** [comment]
Any updates? This issue still exists at the moment.

**Comment by raphaelbernhart** [comment]
@btea The issue is still persisting. Is there any update on how to fix it?

We are currently thinking about a fork of the code to fix the bug with a custom-solution until it is resolved.

**Comment by btea** [comment]
@raphaelbernhart Sorry, I don't have the relevant equipment environment locally. If you have ideas to solve this issue, please submit a PR. Thank you!

**Comment by raphaelbernhart** [comment]
@btea [Here](https://github.com/element-plus/element-plus/pull/16393) is the corresponding PR.

How long does the review and merging process normally take? We need this change next week at the latest.

Thanks for your work and support :)

**Comment by btea** [comment]
@raphaelbernhart Thank you for submitting the PR. 

However, everyone has been busy with work recently, so the review and release process may not be that fast!

If you need it urgently, you can temporarily create a patch file to solve the problem and remove it after the new version is released.
