### ISSUE TITLE
[Bug Report] [ElCascader] The height of the input is incorrect when the `size`, `filterable`, and `multiple` attributes are set at the same time.

### ISSUE THREAD

**Issue by fengyuanchen** [element-plus/element-plus#5219]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Google Chrome 97

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/cfy/pen/abLjgeO

### Steps to reproduce
1. Open the [online demo](https://codepen.io/cfy/pen/abLjgeO).
2. Switch the sizes.
3. Check the height of the cascader, and compress to other form elements.

**PS:** The wrong code might be [this line](https://github.com/element-plus/element-plus/blob/3172fec0e4558b59c0adf5cd44530c331cd16c12/packages/components/cascader/src/index.vue#L509), the `6` number should be different for different sizes.

### What is Expected?
The height of the cascader is correct and is responsive when size changed.

### What is actually happening?
The height of the cascader is fixed, even changing the `size` to another one.

**Comment by fengyuanchen** [comment]
The `element-ui` have the same issue for a long time.

**Comment by TothingWay** [comment]
When will the problem be fixed？
