### ISSUE TITLE
[Bug Report] el-date-picker 默认值不显示 （必须要点击一下之后才显示）

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5230]
### Element Plus version
1.3.0-beta.2

### OS/Browsers version
win11

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/mxp131011/pen/xxXaqGw

### Steps to reproduce
在最新版（1.3.0-beta.2）的 `el-date-picker` 中 设置绑定默认值(`v-model` 或  `modelValue` )不显示,必须点击一下才会显示出来

在1.3.0-beta.1 是正常的 （可将示例代码的`element-plus`引用改成1.3.0-beta.1查看效果）

### What is Expected?
默认值可以正常显示

### What is actually happening?
默认值没有正常显示

**Comment by kooriookami** [comment]
Seems same problem with el-select

**Comment by JeremyWuuuuu** [comment]
Going to do some modification for popup components because now popups are not rendered into the DOM by default. 

/cc @kooriookami can you do that?
