### ISSUE TITLE
Removing `sleep` from testing

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#5237]
## Problem to solve

For now, Element Plus's test contains lots of `sleep(timeout)` call, which is essentially wait for `[timeout]` milliseconds for the app to update.

This is caused by `window.setTimeout`, `Transition` component rendering because they defers the code to 
be invoked, views to be rendered.

## Proposal

For fixing this issue, we need to figure out how the code is actually running, for example when rendering 

```vue
<Transition name="" duration="timeout">
  <div v-if="someCondition">
     <content />
  </div>
</Transition>
```

We have to know the mechanism under the transition, for when can we make assertions.

## The goal

The goal is to remove all `sleep()` from the test, it can be easily done with [jest.useFaketimer](https://testing-library.com/docs/using-fake-timers/) (for simulate timer) and combine with [`rAF()`](https://github.com/element-plus/element-plus/blob/dev/packages/test-utils/tick.ts) (for flushing updates)

**Comment by sxzz** [comment]
Fixed in #5784
