### ISSUE TITLE
[docs]The bug about dialog in the doc website. 

### ISSUE THREAD

**Issue by Ther-su** [element-plus/element-plus#524]
![image](https://user-images.githubusercontent.com/57524062/97787525-c4ed0980-1bed-11eb-9c1a-595a116628a7.png)
The dialog can work when you click the button.
Whether we should change the `:visible.sync="dialogVisible"` to `v-model="dialogVisible"` in the doc website?

**Comment by JeremyWuuuuu** [comment]
Yes indeed, the documentation has not been updated yet, we still have components left to be migrated, soon this should be fixed.

**Comment by Ther-su** [comment]
ok,thanks.

**Comment by JeremyWuuuuu** [comment]
Fixed in #650
