### ISSUE TITLE
[Bug Report] el-select 可以创建条目时 （单选） 默认值和列表会重复  且回车键不触发

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5248]
### Element Plus version
1.3.0-beta.2

### OS/Browsers version
win11

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/mxp131011/pen/QWqVgEM

### Steps to reproduce
el-select 为单选且可以创建条目时   默认值和列表重复， 且回车键不触发
![image](https://user-images.githubusercontent.com/31055355/148675001-1a985f67-58e4-44e3-8fd9-5b4b442732dc.png)

### What is Expected?
不重复 回车键可以触发

### What is actually happening?
重复 回车键不可以触发

**Comment by JeremyWuuuuu** [comment]
@mxp131011 Does this reproducible in `beta.1`?
