### ISSUE TITLE
[Bug Report] v-loading directive is missing corresponding SSR transform and will be ignored

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#5260]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
Any

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/none

### Steps to reproduce
Try to build in SSR mode, and it reports an error.
![build error](https://user-images.githubusercontent.com/45936772/148689157-1bc8279b-bb2f-4370-b218-f3e0cb71719b.png)

### What is Expected?
Build successfully.

### What is actually happening?
Got an error.

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic You should configure it in the `vite.config.ts` if you are using it. By doing something like this: [config.ts](https://github.com/element-plus/element-plus/blob/43ad4aa072a4408ff897b575375f15d118e086f8/docs/.vitepress/config.ts#L78) Let me know if you have any questions.

**Comment by KawaiiZapic** [comment]
> @KawaiiZapic You should configure it in the `vite.config.ts` if you are using it. By doing something like this: [config.ts](https://github.com/element-plus/element-plus/blob/43ad4aa072a4408ff897b575375f15d118e086f8/docs/.vitepress/config.ts#L78) Let me know if you have any questions.

I'm using webpack instead of vite. The config generates by vue-cli. Should I show you the vue.config.js?

**Comment by JeremyWuuuuu** [comment]
> > @KawaiiZapic You should configure it in the `vite.config.ts` if you are using it. By doing something like this: [config.ts](https://github.com/element-plus/element-plus/blob/43ad4aa072a4408ff897b575375f15d118e086f8/docs/.vitepress/config.ts#L78) Let me know if you have any questions.
> 
> I'm using webpack instead of vite. The config generates by vue-cli. Should I show you the vue.config.js?

I think the way to solve the problem is the same, instead here we need to configure your `vue.config.js` instead of `vite.config.js`. 

Ah, I found something for your reference:

https://github.com/vuejs/vitepress/issues/92#issuecomment-781440064
