### ISSUE TITLE
[Bug Report] select-v2 筛选并选择选项的逻辑有问题

### ISSUE THREAD

**Issue by j-waiting-for** [element-plus/element-plus#5267]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
win10

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/j-waiting-for/pen/GRMXYeK

### Steps to reproduce
假如我想要选择，'testJavaScript101'，'testJavaScript111'，'testJavaScript121'，'testJavaScript131'，'testJavaScript141'这五个选项。
输入了文字'testJavaScript1'，筛选到了我想要的选项，然后选择了'testJavaScript101'，结果选择101之后我用以筛选的文本消失了，下方选项列表也恢复为了默认列表。这意味着我想要选择五个选项需要重复输入5次关键字，这种交互体验太差了。

### What is Expected?
https://element-plus.org/zh-CN/component/cascader.html#%E5%8F%AF%E6%90%9C%E7%B4%A2
像cascader一样，输入文字筛选后选择选项，文本不会消失，点击周围空白区域文本消失

### What is actually happening?
选择选项后筛选文本消失了

**Comment by Alanscut** [comment]
我也认为cascader那种筛选的行为更友好

**Comment by emojiiii** [comment]
我觉得应该暴露一个清空当前筛选项值的api给用户，让用户自行决定

**Comment by Alanscut** [comment]
> 我觉得应该暴露一个清空当前筛选项值的api给用户，让用户自行决定。我们默认不清空，但是用户可以通过这个api自行决定是否清空

也可以，
