### ISSUE TITLE
[Bug Report] 日历组件判断是否选中逻辑问题，只判断了日期，没有判断月份和年。并且在没有选中的情况下，切换月份，会默认选中切换的月份的当前日期

### ISSUE THREAD

**Issue by QianTangrong** [element-plus/element-plus#5268]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/issues/new/choose

### Steps to reproduce
使用日历插槽 ，必现

### What is Expected?
判断是否选中更加严谨，切换月份不会默认选中

### What is actually happening?
综上

**Comment by msidolphin** [comment]
这里确实存在问题，应该切换到该月的1号
