### ISSUE TITLE
[Bug Report] On-demand Import，the style  is not working

### ISSUE THREAD

**Issue by PresByter2015** [element-plus/element-plus#5271]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.25

### Reproduction Link
https://github.com/PresByter2015/learn-project/tree/master/vue3-learn

### Steps to reproduce
1. cd vue3-learn
2. yarn
3. yarn dev
4. open localhost:8888/about
5. see  button I am ElButton

### What is Expected?
the `I am ElButton` is have element plus style

### What is actually happening?
only have originally style

**Comment by YunYouJun** [comment]
I think it had solved in `v2.0.3`. #6221
