### ISSUE TITLE
[Bug Report] 关闭dialog再次打开时，select下拉面板在dialog中消失

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#5274]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
macOS

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/lemonade1/pen/BawObJW

### Steps to reproduce
第一次打开弹窗，下拉正常显示，关闭后第二次打开弹窗，下拉面板消失

### What is Expected?
下拉面板显示

### What is actually happening?
下拉面板消失

**Comment by Domain** [comment]
我也出现了，应该是z-index计算有问题，挺影响使用的
