### ISSUE TITLE
[Feature Request] event when the month or year changes

### ISSUE THREAD

**Issue by RomanRadaykinFrontend** [element-plus/element-plus#5276]
### Existing Component
Yes

### Component Name
date-picker

### Description
On our project, we need to highlight the data into which the documents were uploaded. Data about these dates are loaded dynamically from the server, so we need to send a request to the server every time the month or year changes (pressing the arrows in the calendar header)

**Comment by msidolphin** [comment]
@RomanRadaykinFrontend Hi, in next version, you can do this by listening `panel-change` event

**Comment by RomanRadaykinFrontend** [comment]
@msidolphin thanks!
