### ISSUE TITLE
[Bug Report] el-date-picker 当 type="daterange" 时候 添加标签自定义属性无效【class or style...】

### ISSUE THREAD

**Issue by gastrodia** [element-plus/element-plus#5299]
### Element Plus version
1.3.0-beta.3

### Steps to reproduce
el-date-picker 当 type="daterange" 时候 添加标签自定义属性无效【class or style...】

### 演示地址：
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPG1hcms+XG4gICAgICAgIGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHR5cGU9XCJkYXRlcmFuZ2VcIlxuICAgICAgICA9PlxuICAgICAgICBcbiAgICAgICAg55qEXG4gICAgICAgIHN0eWxlPVwid2lkdGg6IDUwMHB4O1wiXG4gICAgICAgICAgICAgIGNsYXNzPVwibmItbmJcIlxuICAgICAgICDkuI3nlJ/mlYhcbiAgICAgICAg8J+Rh1xuICAgICAgPC9tYXJrPlxuICAgICAgICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDUwMHB4O1wiXG4gICAgICAgICAgICAgIGNsYXNzPVwibmItbmJcIlxuICAgICAgICAgICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgICAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgICAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwi5byA5aeL5pe26Ze0XCJcbiAgICAgICAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwi57uT5p2f5pe26Ze0XCJcbiAgICAgICAgICAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+UGlja2VyIHdpdGggcXVpY2sgb3B0aW9uczwvc3Bhbj5cbiAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICAgICAgdHlwZT1cImRhdGVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIlxuICAgICAgICA6ZGlzYWJsZWQtZGF0ZT1cImRpc2FibGVkRGF0ZVwiXG4gICAgICAgIDpzaG9ydGN1dHM9XCJzaG9ydGN1dHNcIlxuICAgICAgPlxuICAgICAgPC9lbC1kYXRlLXBpY2tlcj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgdmFsdWUyID0gcmVmKCcnKVxuXG5jb25zdCBzaG9ydGN1dHMgPSBbXG4gIHtcbiAgICB0ZXh0OiAnVG9kYXknLFxuICAgIHZhbHVlOiBuZXcgRGF0ZSgpLFxuICB9LFxuICB7XG4gICAgdGV4dDogJ1llc3RlcmRheScsXG4gICAgdmFsdWU6ICgpID0+IHtcbiAgICAgIGNvbnN0IGRhdGUgPSBuZXcgRGF0ZSgpXG4gICAgICBkYXRlLnNldFRpbWUoZGF0ZS5nZXRUaW1lKCkgLSAzNjAwICogMTAwMCAqIDI0KVxuICAgICAgcmV0dXJuIGRhdGVcbiAgICB9LFxuICB9LFxuICB7XG4gICAgdGV4dDogJ0Egd2VlayBhZ28nLFxuICAgIHZhbHVlOiAoKSA9PiB7XG4gICAgICBjb25zdCBkYXRlID0gbmV3IERhdGUoKVxuICAgICAgZGF0ZS5zZXRUaW1lKGRhdGUuZ2V0VGltZSgpIC0gMzYwMCAqIDEwMDAgKiAyNCAqIDcpXG4gICAgICByZXR1cm4gZGF0ZVxuICAgIH0sXG4gIH0sXG5dXG5cbmNvbnN0IGRpc2FibGVkRGF0ZSA9ICh0aW1lOiBEYXRlKSA9PiB7XG4gIHJldHVybiB0aW1lLmdldFRpbWUoKSA+IERhdGUubm93KClcbn1cblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

![image](https://user-images.githubusercontent.com/96605737/148878714-40ad67fa-4577-418e-ac71-f2e45a1c4b20.png)
![image](https://user-images.githubusercontent.com/96605737/148878874-aa18d4e7-9998-4b15-9d1a-1f0ef8adf2e3.png)

**Comment by 0song** [comment]
wii fix soon
