### ISSUE TITLE
[Bug Report] el-date-picker的时分秒dlg选项会导致contenteditable的编辑失效

### ISSUE THREAD

**Issue by owl-lei** [element-plus/element-plus#5301]
### Element Plus version
1.1.0-beta.20

### OS/Browsers version
OS X / chrome 96.0.4664.110

### Vue version
3.2.16

### Reproduction Link
https://codepen.io/owlseb/pen/Exwdbwd

### Steps to reproduce
1.点击「日期控件」，弹出日期选项后，点击「选择时间」的input，然后拖动“时分秒”任务一列的滚动条，长按鼠标向上或向下拖拽，把鼠标箭头移出「日期弹窗」后释放鼠标。这时「日期弹窗」会隐藏
2.最后点击下方可输入的div[contenteditable]，变得不再可输入

### What is Expected?
日期控件不要影响div[contenteditable]的可编辑

### What is actually happening?
在1.1.0-beta版本，按步骤操作，会有报错。1.3.0后不报错，但还是会影响div[contenteditable]，让其变得不可编辑，无法输入

**Comment by msidolphin** [comment]
When the cursor moved out of panel, the mouseup event is not triggered
![image](https://user-images.githubusercontent.com/26672484/148921509-eb15a62a-df55-4db8-85a0-fd052c35c7b7.png)

![image](https://user-images.githubusercontent.com/26672484/148921438-1cafebb8-d0bb-4399-825e-5aa3c0e6293a.png)
