### ISSUE TITLE
[Bug Report] Dropdown with split button doesn't render correctly

### ISSUE THREAD

**Issue by chrisfromneptune** [element-plus/element-plus#5305]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
Win10/Chrome 96

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/h2zdpvxj/

### Steps to reproduce
A simple dropdown with split button doesn't render correctly (can't reproduce on jsfiddle however).

```
<el-dropdown split-button type="primary">
            Dropdown List
        <template #dropdown>
            <el-dropdown-menu>
                <el-dropdown-item>Action 1</el-dropdown-item>
            </el-dropdown-menu>
        </template>
    </el-dropdown>
```

and if I add:

`<el-button-group style="display:none"></el-button-group>`

below it, it does render correctly.  

My package.json is:
```
"dependencies": {
    "core-js": "^3.20.2",
    "element-plus": "^1.3.0-beta.3",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-property-decorator": "^10.0.0-rc.3",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.2.26",
    "@vue/eslint-config-typescript": "^7.0.0",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "typescript": "~4.1.5",
    "unplugin-auto-import": "^0.5.9",
    "unplugin-vue-components": "^0.17.11",
    "vue-cli-plugin-element-plus": "0.0.13"
  }
```

### What is Expected?
It renders as: https://imgur.com/nCFZ8Ev and would like it to render as jsfiddle does without having to add the extra invisible button group element to my component.  

### What is actually happening?
I'm new to vue/element, how could this occur?

**Comment by btea** [comment]
You can try to write like this
```
<el-dropdown :split-button="true" type="primary">
     Dropdown List
     ...
 </el-dropdown>
```

**Comment by emojiiii** [comment]
can you try to use [playground](https://element-plus.run/) to provide a mini repo ?

**Comment by chrisfromneptune** [comment]
For anyone interested - it works fine when using a full import, but the on-demand import requires this additional manual import: 
`import 'element-plus/es/components/button-group/style/css'`
to appear correctly.
