### ISSUE TITLE
[Bug Report] 当Select组件的值不在所提供的Options里时会直接显示该值

### ISSUE THREAD

**Issue by ApsarasX** [element-plus/element-plus#5306]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
macOS 10.15.7

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/ApsarasX/m0k24sp5/4/

### Steps to reproduce
打开https://jsfiddle.net/ApsarasX/m0k24sp5/4/ 复现问题

### What is Expected?
当Select的v-model上的值不在所提供的Options中时，Select组件应该为默认的空状态

### What is actually happening?
当Select的v-model上的值不在所提供的Options中时，Select组件会直接显示该值

**Comment by emojiiii** [comment]
我觉得这不能是空值哦，因为你已经 `v-model` 或者 `modelValue` 传值进来的, 找不到选项如果默认为空值，会让用户觉得什么效果都没有，也不提示任何报错，像是出了bug一样 @ApsarasX

**Comment by mxp131011** [comment]
既然绑定了值，且不为空，如果不在Options中那么一应该清空绑定的值，不然会造成歧义

**Comment by emojiiii** [comment]
> 既然绑定了值，且不为空，如果不在Options中那么一应该清空绑定的值，不然会造成歧义

这个应该用户自行决定，因为如果以后有人希望出现不清空的，这又要改回去了。

**Comment by mxp131011** [comment]
> > 绑定了，且不为，不在选项中那么一清空绑定的价值，应该是如果会造成的意义
> 
> 这个用户应该决定以后改如果有人希望出现，因为的，这会自己回去。

我是赞成不改的，我的意思是他应该先清空绑定值，有绑定值且没在Options中也应该显示出来，如果不想显示出来就应该事先清空绑定值
