### ISSUE TITLE
[Feature Request] 请问自定义封装的组件如何配合form-item触发验证呢

### ISSUE THREAD

**Issue by 535944903** [element-plus/element-plus#5311]
### Existing Component
是

### Component Name
form

### Description
以前使用element 的时候，  再自定义组件里，通过  this.dispatch('ElFormItem', 'el.form.change', [value]) ，触发Form表单的验证。现在element plus该如何触发验证呢。

**Comment by 535944903** [comment]
![image](https://user-images.githubusercontent.com/1191371/148909267-bf933286-3f79-49e5-a89a-5e9af037f204.png)
element 这样写是可以的。 plus该怎么触发呢

**Comment by 535944903** [comment]
![image](https://user-images.githubusercontent.com/1191371/148910169-144b7827-19a8-4bc9-818a-b93a887ce5f9.png)
这是以前dispatch的方法

**Comment by emojiiii** [comment]
please see [docs](https://element-plus.gitee.io/zh-CN/component/form.html#form-%E6%96%B9%E6%B3%95)

**Comment by sxzz** [comment]
```ts
await formEl.validate((valid, fields) => {
    if (valid) {
      console.log('submit!')
    } else {
      console.log('error submit!', fields)
    }
  })
```
For more details, you can refer to https://element-plus.gitee.io/en-US/component/form.html#validation

**Comment by Browinee** [comment]
最近也遇到同業的業務場景，只能把自定義封裝的組建單獨出來驗證

**Comment by weblowb** [comment]
在你自定义的组件中加入隐藏的input就行了
![image](https://user-images.githubusercontent.com/19431970/201009786-016f593a-f8e6-4143-bb6c-ccf59c04a5b9.png)

**Comment by xl495** [comment]
> ### Existing Component
> 是
> 
> ### Component Name
> form
> 
> ### Description
> 以前使用element 的时候， 再自定义组件里，通过 this.dispatch('ElFormItem', 'el.form.change', [value]) ，触发Form表单的验证。现在element plus该如何触发验证呢。

![image](https://user-images.githubusercontent.com/39614103/201873843-41eebeb3-f7c2-4df8-b25f-40083d09cce3.png)
![image](https://user-images.githubusercontent.com/39614103/201873927-6232ccc6-eac3-4045-905c-9b71828ea0d1.png)
有更好的方式记得踢我一下

**Comment by Browinee** [comment]
> 
我後來是用以下的方法
https://juejin.cn/post/7041489184938262564
