### ISSUE TITLE
[Bug Report] QQ浏览器运行报错

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5313]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
win11 / qq浏览器报错

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/issues

### Steps to reproduce
最近接到测试人员反馈，QQ浏览器运行项目直接报错，然后我测试了一下的确是不能运行，然后发现在QQ浏览器打开[element-plus官网](https://element-plus.gitee.io/zh-CN/component/scrollbar.html)同样报错，原因是QQ浏览器不支持nodejs的`globalThis` 这个全局属性，不知道是否有打算支持QQ浏览器？
![image](https://user-images.githubusercontent.com/31055355/148911957-49bfb34c-5972-4a12-9946-2ea6a2e4bd74.png)

### What is Expected?
QQ浏览器正常运行

### What is actually happening?
QQ浏览器不能正常运行

**Comment by mxp131011** [comment]
以前版本是支持QQ浏览器的（1.2.0.X之前）

**Comment by msidolphin** [comment]
https://github.com/vueuse/vueuse/pull/1133 We need to wait for @vueuse to release a new version

**Comment by mxp131011** [comment]
临时解决办法：
修改node_modules\_@vueuse_core@7.5.3@@vueuse\core\index中`globalThis`相关代码(暂时不用改min.js文件下的globalThis)

### 原始代码
``` js
const globalKey = "__vueuse_ssr_handlers__";
globalThis[globalKey] = globalThis[globalKey] || {};
const handlers = globalThis[globalKey];
```

### 替换为
``` js
function getglobalThis() {
  try {
      return globalThis || window;
  } catch (error) {
      return window;
  }
}
const _global = getglobalThis();
const globalKey = "__vueuse_ssr_handlers__";
_global[globalKey] = _global[globalKey] || {};
const handlers = _global[globalKey];
```

**Comment by emojiiii** [comment]
建议更改 `node_modules` 里面的代码时用 `patch-package` 记录你的更改, 否则如果你的代码是云构建, 这个问题还是会存在
