### ISSUE TITLE
[Bug Report] Different font in documentation and installed project

### ISSUE THREAD

**Issue by programulin** [element-plus/element-plus#5314]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
Chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/3Lz92fxn/2/

### Steps to reproduce
Install fresh project from Vue Cli and import Element Plus

### What is Expected?
In documentation site main font is Inter:
--font-family: Inter, Roboto, Oxygen, Fira Sans, Helvetica Neue, sans-serif;

I want make new project with the same styles as in documentation.

### What is actually happening?
When i make new project, font family for #app is:

font-family: Avenir, Helvetica, Arial, sans-serif;

I found file element-plus/theme-chalk/src/reset.scss, but there is no Inter too:

font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
    'Microsoft YaHei', '微软雅黑', Arial, sans-serif;

So what is the right way to make new project with same fonts as in documentaion? Because many elements, for example buttons looks a little worse with other fonts.

**Comment by iamkun** [comment]
Check here as a reference `docs/.vitepress/vitepress/styles/vars.scss`
