### ISSUE TITLE
[Bug Report] el-pagination's total and jump label is not in disabled style when disabled

### ISSUE THREAD

**Issue by DevinCarl** [element-plus/element-plus#5315]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
*

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/DevinCarl/pen/oNGadpz

### Steps to reproduce
use disabled property for  el-pagination

### What is Expected?
total and jump label is in disabled style

### What is actually happening?
total and jump label is not in disabled style

**Comment by emojiiii** [comment]
`total` and `jump` label  are just text, so they do not have disabled style.

**Comment by DevinCarl** [comment]
> `total` and `jump` label are just text, so they do not have disabled style.

@emojiiii  thank you for your reply.
I think `total` and `jump` for el-pagination, is the same as `el-radio__label` for el-radio.
so I would like to change the color of `total` and `jump` to `--el-text-color-placeholder` when  pagination is disabled. 

but now I can't do this because of lacking "is-disabled" in it's root dom.

I have pull a request for this:  [5328](https://github.com/element-plus/element-plus/pull/5328)

**Comment by tolking** [comment]
This issues seems to have been fixed
