### ISSUE TITLE
[Bug Report] el-select 的popper-append-to-body属性设置为false无效

### ISSUE THREAD

**Issue by cxj-github** [element-plus/element-plus#5316]
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
chrome 97.0.4692.71

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-demo-forked-uyn0w

### Steps to reproduce
打开浮现链接，进入控制台查看popper元素所在位置。

### What is Expected?
在 .app 中

### What is actually happening?
在el-popper-container-xxx中

**Comment by emojiiii** [comment]
fix in #5296

**Comment by SeminVsevolod** [comment]
1.3.0-beta.5 has this bug too.
Latest stable version with working :popperAppendToBody="false" - 1.2.0-beta.6.

**Comment by catillery** [comment]
Looks like the root cause may be here:
https://github.com/element-plus/element-plus/blob/7c4c505e2fea27629ad87e5ada3e57de075b6fa5/packages/components/select/src/select.vue#L12

The prop being forwarded to `el-tooltip` is `append-to-body` but I believe `append-to` is the appropriate prop name.

**Comment by ReWWeR** [comment]
The same issue here on 1.2.0-beta.9

**Comment by emojiiii** [comment]
Duplicate of #5370
