### ISSUE TITLE
[Feature Request] Allow 'min-content' in el-dialog width without warning.

### ISSUE THREAD

**Issue by tbtalbottjr** [element-plus/element-plus#5329]
### Existing Component
Yes

### Component Name
el-dialog

### Description
I am able to use min-content as the width of an el-dialog which allows the dialog to adapt much better than any other solution I have found, yet it creates an ugly warning in the console and within unit tests. Please allow this valid value for width without the warning.

Current version of Element Plus that I am using: 1.1.0-beta.24

**Comment by tbtalbottjr** [comment]
Repro at: https://codepen.io/iamkun/pen/YzWMaVr

Produces console warning in dev mode and test mode:
[Vue warn]: Invalid prop: custom validator check failed for prop "width". 
  at <ElDialog modelValue=false onUpdate:modelValue=fn<onUpdate:modelValue> width="min-content" > 
  at <App>

'min-content' prevents content from being squished in Firefox with Preference set to:

Default zoom: 110%
X - Zoom text only

'min-content' is a valid CSS width value. Please support without warning. It really messes up the unit test output.

**Comment by tbtalbottjr** [comment]
@emojiiii - I have tried to comply with all of the requirements that the 'bot' has requested, yet this bug was closed. Please let me know how to get this request looked at or let me know why you would refuse it. Thanks.

**Comment by emojiiii** [comment]
i'm sorry. I missed here because I received so many emails.

**Comment by sxzz** [comment]
Close via #5329
