### ISSUE TITLE
[Questions]: Questions about the implementation of `ElCheckboxGroup`

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#533]
1.请问 ElCheckboxGroup中定义modelValue的意思何在
在provide中使用...toRefs(props), 是否覆盖了这个属性?

2.el-popover 的实现为什么不使用el-popper来实现？还要重新写个popper  el-popper是否可以考虑使用jsx的写法 现在的写法使用的Teleport好像没什么用

3.日期选择器的diabled能否到时间 例如 时间要选到当前时间的2小时之后  日期时间选择器能不能和TimePicker结合起来使用  现在结合的好像只有 time-select

4.el-select的渲染为什么不需要虚拟列表来实现 我们现在几千个数据 要前端来筛选 非常的卡

5. 能否在autocomplete增加一个属性 只有选择了options才关闭选择项 (现在有个需求 必须选择了才可以 否则就关闭)  有input的话就不能关闭 如果使用select的话 又不能编辑了 感觉最简单的就是在上面增加一个属性了

**Comment by Lliuxs** [comment]
ElDropdownItem 属性command默认值 单词拼写错误

**Comment by zazzaz** [comment]
> ElDropdownItem 属性command默认值 单词拼写错误

fixed in #823

**Comment by zazzaz** [comment]
3. yes disabledHours  https://github.com/element-plus/element-plus/issues/162#issuecomment-676052160
4. will do
