### ISSUE TITLE
[Bug Report] Cascader 级联选择器 无法设置宽度

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#5331]
### Element Plus version
1.3.0-beta.4

### OS/Browsers version
Windows 10 OS 21H2 19044.1415  /  Google Chrome 96.0.4664.110 /  Microsoft Edge 97.0.1072.55

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/ot89y51u/2/

### Steps to reproduce
在标签加入style属性兵设置宽度 `<el-cascader :options="options" style="width: 800px">`

### What is Expected?
宽度发生变化（以前的版本是可以的）

### What is actually happening?
宽度依旧不变

**Comment by languanghao** [comment]
have same problem, now can only use css instead of `style`
```
.el-cascader {
  width: 100%;
}
```

**Comment by lbilife** [comment]
我也遇到了这个问题.
实际上,不只是宽度,所有传递给 el-cascader 组件的 style 和 class 都不会成功.
