### ISSUE TITLE
[Bug Report] el-cascader 无法传递自定义 style 和 class

### ISSUE THREAD

**Issue by lbilife** [element-plus/element-plus#5338]
### Element Plus version
1.3.0-beta.4

### OS/Browsers version
Microsoft Edge 版本 97.0.1072.55 (官方内部版本) (64 位)

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/Luuuuuu/pen/poWQyGy

### Steps to reproduce
给 cascader 组件添加自定义 style 或 class.
<el-cascader style="width:100%;" class="my_test"></el-cascader>

### What is Expected?
自定义样式应该被传递到 cascader 组件的根node.

### What is actually happening?
然而并没有!

**Comment by emojiiii** [comment]
Duplicate of #5331
