### ISSUE TITLE
element-plus 中 navMenu 错误问题

### ISSUE THREAD

**Issue by LYao0919** [element-plus/element-plus#534]
您好，在element-plus文档中（ https://element-plus.org/#/en-US/component/menu ） 关于navmenu错误问题，是否有新版？
正式版本上面时候能够发布呢？

**Comment by JeremyWuuuuu** [comment]
Navmenu has not been migrated yet, so for now you won't be able to use it.

**Comment by langki** [comment]
I have the same problem

**Comment by maicWorkGithub** [comment]
@JeremyWuuuuu 我看projects里，dialog标记为完成，但是不能使用，文档里的例子也是一个都不能运行，报了warning：
```
main.6d8256b5ce2a76ff9dca.js:1 [Vue warn]: Extraneous non-props attributes (visible) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
blabla...
```

**Comment by zazzaz** [comment]
@maicWorkGithub  Hi, please check the English doc for ElDialog at this moment https://element-plus.org/#/en-US/component/dialog

**Comment by JeremyWuuuuu** [comment]
#572 You can track the progress here for NavMenu

Also you should change the syntax due to the breaking change of `Dialog's` `visible` API.

**Comment by fuyz** [comment]
@maicWorkGithub  @zazzaz 
```
custom-class ： Dialog 的自定义类名
```

![image](https://user-images.githubusercontent.com/21302802/119952241-61825900-bfcf-11eb-8b9d-1b7d5a043fb8.png)
