### ISSUE TITLE
[Bug Report] v-loading directive is missing corresponding SSR transform and will be ignored

### ISSUE THREAD

**Issue by cn-troy** [element-plus/element-plus#5340]
### Element Plus version
1.3.0-beta.4

### OS/Browsers version
Edge

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/none

### Steps to reproduce
升级vite到2.7.x则会报错
2.6.14没有问题

### What is Expected?
无法升级vite到2.7.x

### What is actually happening?
得到支持

![Snipaste_2022-01-12_11-53-06](https://user-images.githubusercontent.com/4318293/149061040-6d107e7e-1ff7-4d87-a63a-bc680944b0cf.png)

**Comment by xiaoxian521** [comment]
尝试把@vitejs/plugin-vue升级到最新版本试试

**Comment by cn-troy** [comment]
> 尝试把[@vitejs/plugin-vue](https://www.npmjs.com/package/@vitejs/plugin-vue)升级到最新版本试试

感谢，果然是@vitejs/plugin-vue这个包没升级导致的。升级到2.0.1后问题解决。
