### ISSUE TITLE
[Feature Request] <el-form>组件如果绑定了相同名称的:model和ref, 则<el-form>包裹下的<el-input>无法输入

### ISSUE THREAD

**Issue by heweijian4933** [element-plus/element-plus#5342]
### Existing Component
Yes

### Component Name
el-form

### Description
<el-form>组件如果绑定了相同名称的:model和ref, 则<el-form>包裹下的<el-input>无法输入

案例:
```
<el-form
        :model="userForm"
        ref="userForm"
        :rules="userRules"
>
        <el-form-item prop="userName" label="用户名">
          <el-input v-model="userForm.userName" placeholder="请输入用户名" />
        </el-form-item>
</el-form>
```
---

随后问题表现为el-input无法输入值, 如果将ref改个名字(比如ref=userFormRef)以后恢复正常
因为这个问题解决也比较简单, 也说不上是个bug, 所以只是提了Feature Request.

---

构建: "vite": "^2.0.1",
vue版本: "^3.0.5",
"element-plus": "^1.0.2-beta.32"

**Comment by byj608** [comment]
恩，我使用vite也出现了这个问题，总算找到了解决方法。
