### ISSUE TITLE
[Bug Report] 请问怎么修改主题色？

### ISSUE THREAD

**Issue by zhoufanglu** [element-plus/element-plus#5345]
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.0.0

### Steps to reproduce
1、我新建了element/index.scss
```js
// styles/element/index.scss
/* just override what you need */
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  $colors: (
    'primary': (
      'base': green,
    ),
  )
);

// If you just import on demand, you can ignore the following content.
// 如果你想导入所有样式:
//@use "element-plus/theme-chalk/src/index.scss" as *;
```
2、我在最顶层引入了，但是没有生效
`import '@/assets/scss/element/index.scss'`

**Comment by emojiiii** [comment]
please see [docs](https://element-plus.gitee.io/zh-CN/guide/theming.html#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%AE%83%EF%BC%9F)

**Comment by zhoufanglu** [comment]
> please see [docs](https://element-plus.gitee.io/zh-CN/guide/theming.html#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%AE%83%EF%BC%9F)

我新建了个element/index.scss, 在main.js内引入了 
```js
import { createApp } from 'vue'

import '@/assets/scss/element/index.scss'

import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
```
* 报错
![image](https://user-images.githubusercontent.com/24451091/149249865-40d56cfa-4ebd-4710-a8f7-3a1b67511cef.png)

我用的是`dart-sass`， 在vue.config.js全局引入了个scss入口文件，这个有影响吗？

**Comment by zhoufanglu** [comment]
我发现问题了， 是全局sass文件影响到了
```js
  css: {
    loaderOptions: {
      //全局sass文件
      sass: {
        additionalData: `
        @import "src/assets/scss/entrance.scss";
      `,
      },
    },
  },
```
请问怎么解决这个报错呢？ 我应该把element的index.scss放在哪？

**Comment by zhoufanglu** [comment]
这是我本地`dart-sass`环境
```js
"sass": "^1.47.0",  
"sass-loader": "^10.0.5"
```

**Comment by 21stc-09** [comment]
我是这样加的， vite.config.ts

import ElementPlus from "unplugin-element-plus/vite";
`
plugins: [
  ElementPlus({
      useSource: true
    }),
]
`

`css: {
    preprocessorOptions: {
      scss: {
        charset: false,
        additionalData: `
                  @import "@/styles/index.scss";
                  @import "@/styles/color.scss";
                  @import "@/styles/element/index.scss";
                `,
      },
    },
  },`

**Comment by xiaoxian521** [comment]
Refer to [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter)

**Comment by zhoufanglu** [comment]
> 我是这样加的， vite.config.ts
> 
> ```
> "element-plus": "^1.3.0-beta.1",
> "unplugin-element-plus": "^0.2.0",
> ```
> 
> ```
> import ElementPlus from "unplugin-element-plus/vite"
> 
> ....
> plugins: [
>   ElementPlus({
>       useSource: true
>     }),
> ]
> ...
> 
> css: {
>     preprocessorOptions: {
>       scss: {
>         charset: false,
>         additionalData: `
>                   @import "@/styles/index.scss";
>                   @import "@/styles/color.scss";
>                   @import "@/styles/element/index.scss";
>                 `,
>       },
>     },
>   },
> 
> ....
> ```

谢谢，此楼正解
This method is useful

**Comment by mxp131011** [comment]
> 我发现问题了， 是全局sass文件影响到了
> 
> ```js
>   css: {
>     loaderOptions: {
>       //全局sass文件
>       sass: {
>         additionalData: `
>         @import "src/assets/scss/entrance.scss";
>       `,
>       },
>     },
>   },
> ```
> 
> 请问怎么解决这个报错呢？ 我应该把element的index.scss放在哪？

只要不放到assets目录，其他都可以放，assets是不参与编译的，scss需要编译

**Comment by ruijuanhou** [comment]
在线主题生成 工具 -下载主题 报错，无法下载主题
![image](https://user-images.githubusercontent.com/20152796/149355067-5423f0aa-985a-4e23-bfcc-e94125e4cb65.png)
