### ISSUE TITLE
[Bug Report] el-dropdown 混用其他子组件size不生效

### ISSUE THREAD

**Issue by topoge** [element-plus/element-plus#5346]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
windows10 21H2/chrome 97

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-66zg5?file=/src/App.vue

### Steps to reproduce
https://codesandbox.io/s/element-plus-spa-forked-66zg5?file=/src/App.vue

估计其他类似操作也是这种情况，一起修了把

### What is Expected?
size属性生效

### What is actually happening?
size未属性生效

**Comment by msidolphin** [comment]
size should be used with split-button

**Comment by topoge** [comment]
> size should be used with split-button

但是直接写el-dropdown-item是生效的，嵌套el-checkbox-group之后不生效，在element-ui2的时候他是正常的，我升级到plus之后不行了
