### ISSUE TITLE
[Bug Report] Element Plus不能与qq浏览器做到兼容显示不了

### ISSUE THREAD

**Issue by aLtEr6** [element-plus/element-plus#5362]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10/qq浏览器

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
可以用qq浏览器打开您的官网 无任何东西显示

### What is Expected?
我在做项目时用vue3.0，当我导入element plus后沿用您的方法没有做到显示，请问是不是您对qq浏览器没有兼容

### What is actually happening?
qq浏览器没有兼容

**Comment by WangJincheng4869** [comment]
![T%X_0Y U W(BW4}M`$I9(5V](https://user-images.githubusercontent.com/41162158/149280334-f432eb5c-35a2-4bb7-88e6-4ebd5713af40.png) QQ浏览器啊！那么辣鸡的浏览器还在用啊，edge、Chrome、Firefox它们不香么...

**Comment by mxp131011** [comment]
请看：https://github.com/element-plus/element-plus/issues/5313

**Comment by mxp131011** [comment]
> ![T%X_0Y U W(BW4}M`$I9(5V](https://user-images.githubusercontent.com/41162158/149280334-f432eb5c-35a2-4bb7-88e6-4ebd5713af40.png) QQ浏览器啊！那么辣鸡的浏览器还在用啊，edge、Chrome、Firefox它们不香么...

其他用户要用啊，qq浏览器也是牛逼，内核版本才70

**Comment by emojiiii** [comment]
Duplicate of #5313

**Comment by wsqrin** [comment]
> > ![T%X_0Y U W(BW4}M`$I9(5V](https://user-images.githubusercontent.com/41162158/149280334-f432eb5c-35a2-4bb7-88e6-4ebd5713af40.png)QQ浏览器啊！那么辣鸡的浏览器还在用啊，边缘、Chrome、火狐它们不香么.
> 
> 其他用户要用啊，QQ浏览器也是牛逼，内核版本才70

升级win11后直接没有IE浏览器，QQ浏览器是双内核的，有些vpn登录要用。其他浏览器还更低，比如360是63的，这些浏览器普通用户用的挺多没得法。
