### ISSUE TITLE
[Feature Request] Input 输入框 组件中的 textarea 不支持 clearable 属性吗？

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#5363]
### Existing Component
是

### Component Name
Input 输入框

### Description
我发现Input 组件中的 textarea 设置clearable 后不会显示一键清空的按钮。text就可以正常显示一键清空按钮。是就这么设计的吗，文本域就是不支持一键清空？

**Comment by emojiiii** [comment]
目前 `textarea` 输入框确实不支持clearable

**Comment by emojiiii** [comment]
很抱歉，目前组件就是这样设计的。
