### ISSUE TITLE
[Bug Report] el-switch内部文字只能显示第一个

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#5364]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
macOS

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/lemonade1/pen/oNGJvew

### Steps to reproduce
el-switch内部的文字只能显示第一个

### What is Expected?
文字显示完整

### What is actually happening?
文字未显示完整

**Comment by emojiiii** [comment]
please see [docs/inline-prompt](https://element-plus.gitee.io/zh-CN/component/switch.html#attributes)
