### ISSUE TITLE
[Bug Report] el-cascader宽度不能100%、el-pagination默认size下下拉框size偏小与后面输入框，按钮大小不一致

### ISSUE THREAD

**Issue by Jylzl** [element-plus/element-plus#5366]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10- Google Chrome  97.0.4692.71

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/jylzl/pen/RwLEbJy

### Steps to reproduce
1.el-cascader宽度不能100%；
2。el-pagination默认size下下拉框size偏小与后面输入框，按钮大小不一致

### What is Expected?
1.el-cascader宽度可通过style  width 100%拉满；
2。el-pagination默认size下下拉框size与输入框、按钮大小保持一致

### What is actually happening?
1.el-cascader宽度不能100%；
2。el-pagination默认size下下拉框size偏小与后面输入框，按钮大小不一致

**Comment by emojiiii** [comment]
Duplicate of #5331

**Comment by TKBnice** [comment]
什么时候再来个稳定版呢 ，这更新速度太疯狂了吧
