### ISSUE TITLE
[Feature Request] 如何自定义 scss 的 $namespace ？

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#5368]
### Existing Component
Yes

### Component Name
"element-plus": "^1.3.0-beta.1",

### Description
win10

**Comment by msidolphin** [comment]
你定义了namespace也没用啊，组件中还是el-

**Comment by gjfei** [comment]
> 你定义了namespace也没用啊，组件中还是el-
我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的

**Comment by msidolphin** [comment]
> > 你定义了namespace也没用啊，组件中还是el-
> > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的

你为什么会同时引入这两个库呢？

**Comment by gjfei** [comment]
> > > 你定义了namespace也没用啊，组件中还是el-
> > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> 
> 你为什么会同时引入这两个库呢？

老项目正好有需求重构一整个大模块，就借助qiankun.js 来做一个渐进式升级了

**Comment by msidolphin** [comment]
> > > > 你定义了namespace也没用啊，组件中还是el-
> > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > 
> > 
> > 你为什么会同时引入这两个库呢？
> 
> 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了

这个问题应该是项目自行解决，添加prefix应该能解决你的问题

**Comment by gjfei** [comment]
> > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > 
> > > 
> > > 你为什么会同时引入这两个库呢？
> > 
> > 
> > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> 
> 这个问题应该是项目自行解决，添加prefix应该能解决你的问题

没有计划和antd 一样提供一个入口来满足整个需求？

**Comment by msidolphin** [comment]
> > > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > > 
> > > > 
> > > > 你为什么会同时引入这两个库呢？
> > > 
> > > 
> > > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> > 
> > 
> > 这个问题应该是项目自行解决，添加prefix应该能解决你的问题
> 
> 没有计划和antd 一样提供一个入口来满足整个需求？

这个要加也不是一时半会儿啊，你总得先解决这个问题吧

**Comment by gjfei** [comment]
> > > > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > > > 
> > > > > 
> > > > > 你为什么会同时引入这两个库呢？
> > > > 
> > > > 
> > > > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> > > 
> > > 
> > > 这个问题应该是项目自行解决，添加prefix应该能解决你的问题
> > 
> > 
> > 没有计划和antd 一样提供一个入口来满足整个需求？
> 
> 这个要加也不是一时半会儿啊，你总得先解决这个问题吧
问题已经解决了，我只是来看有没有更好的解决方案， 还有功能更新之后请及时的更新一下文档

**Comment by msidolphin** [comment]
> > > > > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > > > > 
> > > > > > 
> > > > > > 你为什么会同时引入这两个库呢？
> > > > > 
> > > > > 
> > > > > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> > > > 
> > > > 
> > > > 这个问题应该是项目自行解决，添加prefix应该能解决你的问题
> > > 
> > > 
> > > 没有计划和antd 一样提供一个入口来满足整个需求？
> > 
> > 
> > 这个要加也不是一时半会儿啊，你总得先解决这个问题吧
> > 问题已经解决了，我只是来看有没有更好的解决方案， 还有功能更新之后请及时的更新一下文档

可以，这个feature会优先安排处理

**Comment by gjfei** [comment]
> > > > > > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > > > > > 
> > > > > > > 
> > > > > > > 你为什么会同时引入这两个库呢？
> > > > > > 
> > > > > > 
> > > > > > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> > > > > 
> > > > > 
> > > > > 这个问题应该是项目自行解决，添加prefix应该能解决你的问题
> > > > 
> > > > 
> > > > 没有计划和antd 一样提供一个入口来满足整个需求？
> > > 
> > > 
> > > 这个要加也不是一时半会儿啊，你总得先解决这个问题吧
> > > 问题已经解决了，我只是来看有没有更好的解决方案， 还有功能更新之后请及时的更新一下文档
> 
> 可以，这个feature会优先处理

我这两天提个pr吧

**Comment by gjfei** [comment]
> > > > > > > > > 你定义了namespace也没用啊，组件中还是el-
> > > > > > > > > 我现在同时引用了element-ui 和element-plus 怎么做到样式隔离? 都是全局引入的
> > > > > > > 
> > > > > > > 
> > > > > > > 你为什么会同时引入这两个库呢？
> > > > > > 
> > > > > > 
> > > > > > 老项目正好有需求重构一整个大模块，就借助z.js 来做一个渐进式升级了
> > > > > 
> > > > > 
> > > > > 这个问题应该是项目自行解决，添加prefix应该能解决你的问题
> > > > 
> > > > 
> > > > 没有计划和antd 一样提供一个入口来满足整个需求？
> > > 
> > > 
> > > 这个要加也不是一时半会儿啊，你总得先解决这个问题吧
> > > 问题已经解决了，我只是来看有没有更好的解决方案， 还有功能更新之后请及时的更新一下文档
> 
> 可以，这个feature会优先处理

![image](https://user-images.githubusercontent.com/33827314/149310745-fe007788-8076-4431-bd04-3888a42eb186.png)
我按照贡献指南跑起来之后这个错误是为什么

**Comment by mofeimo110** [comment]
> 已经解决了，我只是来看有没有更好的解决方案， 还有功能更
遇到了同样的问题，基座全局样式影响到了子应用的样式，老哥可以分享一下解决方案吗？

**Comment by gjfei** [comment]
> > 已经解决了，我只是来看有没有更好的解决方案， 还有功能更
> > 遇到了同样的问题，基座全局样式影响到了子应用的样式，老哥可以分享一下解决方案吗？
基座难道不就应该管理全局的东西吗？设计的是不是有点问题

**Comment by mofeimo110** [comment]
> > > 已经解决了，我只是来看有没有更好的解决方案， 还有功能更
> > > 遇到了同样的问题，基座全局样式影响到了子应用的样式，老哥可以分享一下解决方案吗？
> > > 基座难道不就应该管理全局的东西吗？设计的是不是有点问题
> > > 我们就只会有这个库的样式会冲突，其他的通过添加scope 就没问题，全局的样式就只放在主应用
> > > 我们是用qiankun 来做重构过度的，并不打算一直用下去

基座是elementplus，子应用是elementui，类名一样就冲突了，现在能想到的方案也就是基座换成antd或者将现在的基座变成子应用，新增一个基座，然后两个子应用并存

**Comment by gjfei** [comment]
> > > > 已经解决了，我只是来看有没有更好的解决方案， 还有功能更
> > > > 遇到了同样的问题，基座全局样式影响到了子应用的样式，老哥可以分享一下解决方案吗？
> > > > 基座难道不就应该管理全局的东西吗？设计的是不是有点问题
> > > > 我们就只会有这个库的样式会冲突，其他的通过添加scope 就没问题，全局的样式就只放在主应用
> > > > 我们是用qiankun 来做重构过度的，并不打算一直用下去
> 
> 基座是elementplus，子应用是elementui，类名一样就冲突了，现在能想到的方案也就是基座换成antd或者将现在的基座变成子应用，新增一个基座，然后两个子应用并存

所以有这需求了，我们暂时的做法是fork 了一份 自己维护

**Comment by iamkun** [comment]
will be fixed at #5374

**Comment by sxzz** [comment]
Let's track #5374. This issue will be closed.

**Comment by iamkun** [comment]
You can set the global `namespace` config in https://element-plus.org/en-US/component/config-provider.html#config-provider-attributes

This feature is available after v2.1.10
