### ISSUE TITLE
如何使用Message/MessageBox

### ISSUE THREAD

**Issue by pangao66** [element-plus/element-plus#537]
```js
// import { MessageBox } from 'element-plus'
// import { Notify } from 'element-plus/lib/notification'
import { Message } from 'element-plus/lib/message'
 setup (props, { emit }) {
    onMounted(() => {
      console.log(Message)  // undefined
    })
}
```
message  messageBox 组件无法使用
打印是undefined

**Comment by Lliuxs** [comment]
const { ctx } = getCurrentInstance()
console.log(ctx.$message)

**Comment by pangao66** [comment]
Whether I use the options API or the composition API, it doesn't work properly,  console.log(this.$message)  or  after import {Message} from 'element-plus'  console.log(Message)  it's undefined
无论用options-api还是  composition-api , 都不能正常运行, 无论是 this.$message还是 import Message  之后 , console.log都是undefined

**Comment by JeremyWuuuuu** [comment]
Have you registered `Message` via `app.use(MessageBox)`? Please provide us code with full context.
有没有在全局注册？希望你提供完整一点的代码。

**Comment by pangao66** [comment]
@JeremyWuuuuu 
我用vue-cli 使用的,版本是"element-plus": "^1.0.1-alpha.12",
main.js
```js
import ElementPlus from 'element-plus'
import './element-variables.scss'

const app = createApp(App)
app.use(ElementPlus)
```
app.vue
```vue
<template>
  <el-button @click="handleClick">点击</el-button>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { Message } from 'element-plus'

export default defineComponent({
  name: 'App',
  mounted () {
    console.log(Message)   // 输出undefined
    // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
    // @ts-ignore
    this.$message.success('点击成功')
  },
  setup () {
    function handleClick () {
      console.log(Message)  //输出undefined
      Message.success('点击成功')
    }

    return {
      handleClick
    }
  }
})
</script>
```

**Comment by JeremyWuuuuu** [comment]
Hi, code like this 
```vue
<script>
import { Message } from 'element-plus' // This is an installer, instead of method itself, it won't work.
import { MessageBox } from 'element-plus/lib/message' // this should work
</script>
```

**Comment by pangao66** [comment]
这种我也试过了, 会报错,我提这个iisues之前已经看过了 https://github.com/element-plus/element-plus/issues/488这个,

![image](https://user-images.githubusercontent.com/20113031/98073814-1cb49a80-1ea4-11eb-9665-dd7a8e1a8427.png)

这样使用Notify 组件是可以的, 但是使用MessageBox/Message组件 import就报错

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/98077064-7029e700-1eaa-11eb-8aca-021d859eb435.png)
I believe that we have exported member `MessageBox`
See also 
![image](https://user-images.githubusercontent.com/15975785/98077180-b0896500-1eaa-11eb-90da-f8d8667952ba.png)

**Comment by JeremyWuuuuu** [comment]
You can find it here https://unpkg.com/element-plus@1.0.1-alpha.12/lib/message-box/index.js

**Comment by JeremyWuuuuu** [comment]
Do you mind to give us a link on CodeSandBox or something?

**Comment by pangao66** [comment]
https://codesandbox.io/s/vibrant-solomon-humjn?file=/src/App.vue

**Comment by kooriookami** [comment]
`this.$message.success('123')` cause this.$message.success is not a function.
`this.$message({message:'123',type: 'success'})` is normal.

**Comment by JeremyWuuuuu** [comment]
Seems `$message` did not have a member named `success`, according to `notification.ts`
We have a code chunk of 
![image](https://user-images.githubusercontent.com/15975785/98090100-92c5fb00-1ebe-11eb-8bf1-1ed03ca27124.png)
Which `Message` does not have this chunk of code to give assign shortcut to `Message`

**Comment by pangao66** [comment]
更换了 "element-plus": "^1.0.1-alpha.14"版本 ,可以了  非常感谢

**Comment by zazzaz** [comment]
fixed in alpha.14

**Comment by em2046** [comment]
in alpha.15 with vite

import { Message } from "element-plus/lib/message";

Uncaught (in promise) SyntaxError: The requested module '/@modules/element-plus/lib/utils/util.js' does not provide an export named 'isVNode'
