### ISSUE TITLE
[Bug Report] el-popover 的append-to-body="false"设置无效

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5370]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win11 

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/mxp131011/pen/WNZLNzx

### Steps to reproduce
`el-popover` 设置 `append-to-body==”false"` 无效了，在1.2.0-beta.1是可用的，希望恢复，不然在一些嵌套弹框上会导致父弹框关闭
请在控制台查看`el-popover`元素的位置变化

### What is Expected?
`append-to-body==”false"`  有效

### What is actually happening?
`append-to-body==”false"`  无效

**Comment by SeminVsevolod** [comment]
I confirm. 1.3.0-beta.5 has this bug too.
Latest stable version with working properly `:popperAppendToBody="false"` - 1.2.0-beta.6.

Please fix this bug ASAP 🤗

Thanks for your work 😍

**Comment by freedomljt** [comment]
改出bug了

**Comment by JeremyWuuuuu** [comment]
@SeminVsevolod This will be fixed ASAP, sorry for the inconvenience that I made :bow:
