### ISSUE TITLE
[Feature Request] DateTimePicker 组件的操作逻辑（样式）

### ISSUE THREAD

**Issue by gastrodia** [element-plus/element-plus#5373]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
DateTimePicker 组件的操作逻辑（样式）是否可以优化下呢？ 目前的时间日期选择器，时间选择不直观，用户操作选择日期时间不是很方便，期望能改成 react antd 的那种 三列式 ，用户体验会比当前好一些。【弱需求，如可以盼实现，谢谢你们】
### 期望如下：
![image](https://user-images.githubusercontent.com/96605737/149313467-cd75c9c4-77a1-46bb-9a88-e0b276dd68b4.png)
 
### 当前UI 选择时间时候还要手动展开，且用户易忽略
![image](https://user-images.githubusercontent.com/96605737/149313687-fe8063c4-e6ad-481b-8eea-545bb8c197fa.png)

**Comment by huangzhongzhong** [comment]
你好，在执行用户需要选择明确日期时间的这个任务时，确实 antd 的方案是会方便一些，但是用户的任务是非常多样性，比如用户大部分情况下不需要精确选择时间，偶尔才需要精确选择时间的场景下，el 这种方案就更合适。
另外单个【日期时间选择器】的样式和【日期时间范围选择器】的样式也是具有联动的，ant 的策略和我们是完全不同的，无法简单照搬的呢哈哈~

![image](https://user-images.githubusercontent.com/46183365/149517693-9bb16db4-d21d-452b-979a-7b13592fb5ac.png)

**Comment by gastrodia** [comment]
好的，谢谢😄






JavaScript
***@***.***

。。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月14日(周五) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [element-plus/element-plus] [Feature Request] DateTimePicker 组件的操作逻辑（样式） (Issue #5373)




 
你好，在执行用户需要选择明确日期时间的这个任务时，确实 antd 的方案是会方便一些，但是用户的任务是非常多样性，比如用户大部分情况下不需要精确选择时间，偶尔才需要精确选择时间的场景下，el 这种方案就更合适。
 另外单个【日期时间选择器】的样式和【日期时间范围选择器】的样式也是具有联动的，ant 的策略和我们是完全不同的，无法简单照搬的呢哈哈~
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
