### ISSUE TITLE
[Feature] Support custom `namespace` config 

### ISSUE THREAD

**Issue by iamkun** [element-plus/element-plus#5374]
## Guide

FYI,
Search: `["']el-` (regexp)
Include: `packages`
Exclude: `*spec*`

Example:
```ts
const ns = useNamespace('button')

// el-button--small
ns.m('small')

// el-button__icon--foo
ns.em('icon', 'foo')

// el-button-group__foo--bar
ns.bem('group', 'foo', 'bar')

// is-checked
ns.is('checked', trueOrFalse)
```

### CSS Support
- [x] SASS

### Template Support

Moved to #6114 

#### @iamkun
- [x] affix
- [x] alert
- [x] aside
- [x] autocomplete
- [x] avatar
- [x] backtop
- [x] badge
- [x] base
- [x] breadcrumb
- [x] breadcrumb-item
- [x] button
- [x] button-group
--------
- [x] calendar #5496 
- [x] card
- [x] carousel
- [x] carousel-item
- [ ] cascader #5589 
- [ ] cascader-panel
- [x] check-tag
- [x] checkbox #5493
- [x] checkbox-button
- [x] checkbox-group
- [x] col #5714 
- [x] collapse #5715 
- [x] collapse-item #5715 
- [x] collapse-transition https://github.com/element-plus/element-plus/pull/5716
- [x] collection
- [x] color-picker https://github.com/element-plus/element-plus/pull/5718
- [x] config-provider
- [x] container #5498
- [ ] date-picker
- [x] descriptions #5499
- [x] descriptions-item #5499 
- [x] dialog #5761
- [x] divider
- [x] drawer #5596 
- [x] dropdown #5719 
- [x] dropdown-item #5719 
- [x] dropdown-menu #5719
- [x] empty
- [ ] focus-trap
- [ ] footer
- [x] form
- [x] form-item
- [ ] header
- [x] icon
- [x] image #5513
- [x] image-viewer #5513 
- [ ] infinite-scroll
- [x] input #5488 
- [x] input-number #5488
- [x] link
- [ ] loading
- [ ] main
- [ ] menu
- [ ] menu-item
- [ ] menu-item-group
- [x] message https://github.com/element-plus/element-plus/pull/5720
- [ ] message-box https://github.com/element-plus/element-plus/pull/5721
- [x] notification https://github.com/element-plus/element-plus/pull/5722
- [ ] option
- [ ] option-group
- [x] overlay https://github.com/element-plus/element-plus/pull/5723
- [x] page-header https://github.com/element-plus/element-plus/pull/5724
- [x] pagination https://github.com/element-plus/element-plus/pull/5725
- [x] popconfirm https://github.com/element-plus/element-plus/pull/5726
- [x] popover https://github.com/element-plus/element-plus/pull/5727
- [x] popper https://github.com/element-plus/element-plus/pull/5728
- [x] progress https://github.com/element-plus/element-plus/pull/5729
- [x] radio https://github.com/element-plus/element-plus/pull/5731
- [x] radio-button https://github.com/element-plus/element-plus/pull/5731
- [x] radio-group https://github.com/element-plus/element-plus/pull/5731
- [x] rate
- [x] result
- [ ] roving-focus-group
- [x] row
- [x] scrollbar https://github.com/element-plus/element-plus/pull/5732
- [x] select https://github.com/element-plus/element-plus/pull/5733
- [x] select-v2 https://github.com/element-plus/element-plus/pull/5738
- [x] skeleton https://github.com/element-plus/element-plus/pull/5739
- [x] skeleton-item https://github.com/element-plus/element-plus/pull/5739
- [x] slider https://github.com/element-plus/element-plus/pull/5743
- [ ] slot
- [x] space https://github.com/element-plus/element-plus/pull/5749
- [x] step https://github.com/element-plus/element-plus/pull/5944
- [x] steps https://github.com/element-plus/element-plus/pull/5944
- [ ] sub-menu
#### @msidolphin 
- [x] switch
- [ ] tab-pane
- [x] table https://github.com/element-plus/element-plus/pull/5528
- [x] table-column https://github.com/element-plus/element-plus/pull/5528
- [ ] tabs
- [ ] tag https://github.com/element-plus/element-plus/pull/5643
--------
- [x] teleport https://github.com/element-plus/element-plus/pull/5751
- [ ] time-picker
- [ ] time-select
- [x] timeline
- [x] timeline-item
- [x] tooltip https://github.com/element-plus/element-plus/pull/5752
- [x] transfer https://github.com/element-plus/element-plus/pull/5753
- [x] tree https://github.com/element-plus/element-plus/pull/5754
- [x] tree-v2 https://github.com/element-plus/element-plus/pull/5757
- [x] upload https://github.com/element-plus/element-plus/pull/5758
- [ ] virtual-list
- [ ] visual-hidden

This will fix

- https://github.com/element-plus/element-plus/issues/5368

**Comment by sxzz** [comment]
Let's track #6114.

**Comment by gjfei** [comment]
> 

不是很能理解为什么要要关闭这个？

**Comment by sxzz** [comment]
@gjfei https://github.com/element-plus/element-plus/issues/6114 此计划在这个 issue 中追踪。

**Comment by gjfei** [comment]
> @gjfei #6114这个计划在这个问题中追踪。

这个进度已经快完成了，等这个完成在去重构script setup 会不会更好

**Comment by sxzz** [comment]
@gjfei 目前可以同步进行，单独修改namespace的也接受。只是进度在另一个issue汇总。

**Comment by gjfei** [comment]
> @gjfei 目前可以同步进行，单独修改namespace的也接受。只是进度在另一个issue汇总。

能不能先推动一下这个，这个的优先级在我看来是要比script setup 高的

**Comment by sxzz** [comment]
> > @gjfei 目前可以同步进行，单独修改namespace的也接受。只是进度在另一个issue汇总。
> 
> 能不能先推动一下这个，这个的优先级在我看来是要比script setup 高的

PR Welcome

**Comment by a15218378694** [comment]
> 

自定义类名前缀, 这个框架方还没有实现是吧

**Comment by humorHan** [comment]
@iamkun 有预期时间节点支持namespace吗？因为微前端引入后element多版本功能导致的样式冲突一直没有太好的办法解决，跪求时间节点~
