### ISSUE TITLE
[Bug Report] el-switch组件指定active-value和inactive-value初始化总是触发change事件

### ISSUE THREAD

**Issue by qiuchsh** [element-plus/element-plus#5388]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
latest

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-getmo?file=/src/App.vue

### Steps to reproduce
<el-switch v-model="enabled"  active-value="1" inactive-value="0" @change="hanldeChange"/>，如果不指定active-value和inactive-value没有问题的

### What is Expected?
初始化时不触发change事件

### What is actually happening?
初始化时，会触发change事件

**Comment by Fenghao-jun** [comment]
你在生命周期的时候已经把值给改了呀，如果想初始化是true不是应该在ref赋值时为true吗？

**Comment by qiuchsh** [comment]
> 你在生命周期的时候已经把值给改了呀，如果想初始化是true不是应该在ref赋值时为true吗？

onBeforeMounted是我测试的，忘了删掉了

**Comment by emojiiii** [comment]
因为你的激活值和非激活值跟你的`value` 不一样, 所以会发出 `change`

**Comment by qiuchsh** [comment]
> 因为你的激活值和非激活值跟你的`value` 不一样, 所以会发出 `change`

![image](https://user-images.githubusercontent.com/49756310/149615677-c59e302f-84ca-4071-85c4-6cedd57ef8af.png)
不好意思，可能之前的示例没有写好，导致大家理解不误，我已重新编写了测试示例，你再示例看一下，应该就清楚问题了

**Comment by emojiiii** [comment]
same problem, please change `active-value="0"` and `inactive-value` to `:active-value="0"` and `:inactive-value`

**Comment by qiuchsh** [comment]
> same problem, please change `active-value="0"` and `inactive-value` to `:active-value="0"` and `:inactive-value="1"`
![c34c140b-fded-4caf-bb30-9ff6a18479ea](https://user-images.githubusercontent.com/49756310/149616578-287d4a9f-4795-4fb5-befe-452640de768e.png)  感谢指点！
