### ISSUE TITLE
[Bug Report] el-table 的多选的问题

### ISSUE THREAD

**Issue by gastrodia** [element-plus/element-plus#5390]
### Element Plus version
1.3.0-beta.5

### Vue version
3.2.26

### Steps to reproduce
el table 的多选行

当勾选表格后 ，改变table data的 item内的某一属性 会导致勾选 全部取消 ，栗子请看playground 

### What is Expected?
勾选表格后 ，改变table data的 item内的某一属性 不会取消之前的勾选

**Comment by mryujianjun** [comment]
@justwiner I thought, is it possible to just delete 61 lines of code?
https://github.com/element-plus/element-plus/blob/f632072186d9fe636412bf3b4b470d365d6cc341/packages/components/table/src/store/index.ts#L58-L62
