### ISSUE TITLE
[Bug Report] dropdown items keep increase width

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#5391]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
chrome

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/yukisora/pen/vYevvZO

### Steps to reproduce
move mouse over dropdown
dropdown item increase width
and do it again

### What is Expected?
show normal size

### What is actually happening?
show minimum size

**Comment by lemoe2021** [comment]
https://user-images.githubusercontent.com/79942901/149502834-61ec6d07-0445-4953-b2a0-9e0868abaa97.mov

**Comment by kooriookami** [comment]
It fixed in #5396, you can add  `.el-dropdown-menu__item {
  white-space: nowrap;
}` for workaround.

**Comment by kooriookami** [comment]
cc @JeremyWuuuuu Is there other suggestions for this issue?
