### ISSUE TITLE
📚 Document improvement Todo List

### ISSUE THREAD

**Issue by zazzaz** [element-plus/element-plus#540]
Feel free to join us to update the document via a pull request. 😁 

Only English and Chinese docs update is needed. 

For other languages, if you are not a native speaker, please just paste the fresh English content.

**Comment by zazzaz** [comment]
## Use Vue 3.0 Composititon API

**Comment by zazzaz** [comment]
## Incomplete docs

- Switch  add loading #402, missing English docs

**Comment by zouhangwithsweet** [comment]
Ensuring a smooth document transition experience should also be considered. Some common components' docs may not be necessary to change.

**Comment by zazzaz** [comment]
TODO:

Tip: make sure only one Day.js installed in the project. #1263
