### ISSUE TITLE
[question] why all beta version?

### ISSUE THREAD

**Issue by binvb** [element-plus/element-plus#5406]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
mac

### Vue version
3.2.26

### Reproduction Link
https://github.com/element-plus/element-plus/releases

### Steps to reproduce
none

### What is Expected?
expect 1.1.0, 1.2.0, .etc release version

### What is actually happening?
all beta version, should i only use @1.0.0?

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/discussions/3065
