### ISSUE TITLE
[Bug Report] el-table-column 第一列是复选框，设置前三列为固定列，且指定min-width时，向右滚动复选框列异常

### ISSUE THREAD

**Issue by tao892509844** [element-plus/element-plus#5408]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
所有

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ysokb?file=/src/App.vue

### Steps to reproduce
1.设置一个el-table-column的type为selection
2.第二第三列指定min-width且设置fixed

### What is Expected?
横向滚动条向右滚动时固定列正常显示

### What is actually happening?
type为selection的列被隐藏，检查发现前两列的left都为0

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5cbi8vIHNldHVwIGZvciBlbGVtZW50IHBsdXMsIGRvbid0IHJlbW92ZS5cbnNldHVwRWxlbWVudFBsdXMoKTtcblxuICBjb25zdCB0YWJsZURhdGEgPSByZWYoW1xuICAgICAge1xuICAgICAgICBkYXRlOiBcIjIwMTYtMDUtMDNcIixcbiAgICAgICAgbmFtZTogXCJUb21cIixcbiAgICAgICAgc3RhdGU6IFwiQ2FsaWZvcm5pYVwiLFxuICAgICAgICBjaXR5OiBcIkxvcyBBbmdlbGVzXCIsXG4gICAgICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gICAgICAgIHppcDogXCJDQSA5MDAzNlwiLFxuICAgICAgICB0YWc6IFwiSG9tZVwiLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgZGF0ZTogXCIyMDE2LTA1LTAyXCIsXG4gICAgICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgICAgIHN0YXRlOiBcIkNhbGlmb3JuaWFcIixcbiAgICAgICAgY2l0eTogXCJMb3MgQW5nZWxlc1wiLFxuICAgICAgICBhZGRyZXNzOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiLFxuICAgICAgICB6aXA6IFwiQ0EgOTAwMzZcIixcbiAgICAgICAgdGFnOiBcIk9mZmljZVwiLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgZGF0ZTogXCIyMDE2LTA1LTA0XCIsXG4gICAgICAgIG5hbWU6IFwiVG9tXCIsXG4gICAgICAgIHN0YXRlOiBcIkNhbGlmb3JuaWFcIixcbiAgICAgICAgY2l0eTogXCJMb3MgQW5nZWxlc1wiLFxuICAgICAgICBhZGRyZXNzOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiLFxuICAgICAgICB6aXA6IFwiQ0EgOTAwMzZcIixcbiAgICAgICAgdGFnOiBcIkhvbWVcIixcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgICAgICBuYW1lOiBcIlRvbVwiLFxuICAgICAgICBzdGF0ZTogXCJDYWxpZm9ybmlhXCIsXG4gICAgICAgIGNpdHk6IFwiTG9zIEFuZ2VsZXNcIixcbiAgICAgICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgICAgICAgemlwOiBcIkNBIDkwMDM2XCIsXG4gICAgICAgIHRhZzogXCJPZmZpY2VcIixcbiAgICAgIH0sXG4gICAgXSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI0NVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIG1pbi13aWR0aD1cIjE1MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBmaXhlZCBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIG1pbi13aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwic3RhdGVcIiBsYWJlbD1cIlN0YXRlXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImNpdHlcIiBsYWJlbD1cIkNpdHlcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIHdpZHRoPVwiNjAwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ6aXBcIiBsYWJlbD1cIlppcFwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGZpeGVkPVwicmlnaHRcIiBsYWJlbD1cIk9wZXJhdGlvbnNcIiB3aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgc2l6ZT1cInNtYWxsXCI+RGV0YWlsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInRleHRcIiBzaXplPVwic21hbGxcIj5FZGl0PC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)
