### ISSUE TITLE
[Bug Report] ElDropdown contextmenu bug

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#5413]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
版本 97.0.4692.71（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/520voeu9/1/

### Steps to reproduce
When you right-click to display a menu, other menus are not closed

### What is Expected?
Other menus can be closed, or can events be thrown to manually close other menus

### What is actually happening?
When you right-click to display a menu, other menus are not closed

**Comment by weidehai** [comment]
you can set ref=dropdown for el-dropdown,and use dropdown.value.popperRef.onClose() to manually close it

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG4vLyBzZXR1cCBmb3IgZWxlbWVudCBwbHVzLCBkb24ndCByZW1vdmUuXG5zZXR1cEVsZW1lbnRQbHVzKCk7XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxlbC1kcm9wZG93biB0cmlnZ2VyPVwiY29udGV4dG1lbnVcIiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMzBweDtcIj5cbiAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIERyb3Bkb3duIExpc3RcbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXNhYmxlZD5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuXG4gIDxlbC1kcm9wZG93biB0cmlnZ2VyPVwiY29udGV4dG1lbnVcIj5cbiAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIERyb3Bkb3duIExpc3QyXG4gICAgPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)
