### ISSUE TITLE
[Bug Report] Popover v-model:visible don't work

### ISSUE THREAD

**Issue by pavellzubkov** [element-plus/element-plus#5424]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Ubuntu/Chrome

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-wy85o?file=/src/App.vue

update codesandbox browser if error of import

### Steps to reproduce
v-model:visible don't work when trigger is click in 1.3.0-beta5 but worked in 1.2.0-beta6 version.

### What is Expected?
expected changing binding value

### What is actually happening?
binding value don't changed

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnO1xuaW1wb3J0IHsgVXNlciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG4vLyBzZXR1cCBmb3IgZWxlbWVudCBwbHVzLCBkb24ndCByZW1vdmUuXG5zZXR1cEVsZW1lbnRQbHVzKCk7XG5jb25zdCBwb3BWaXNpYmxlID0gcmVmKGZhbHNlKTtcbndhdGNoKFxuICAoKSA9PiBwb3BWaXNpYmxlLnZhbHVlLFxuICAoKSA9PiB7XG4gICAgY29uc29sZS5sb2coXCJQb3B2aXMgQ2hhbmdlZFwiKTtcbiAgfVxuKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLXBvcG92ZXJcbiAgICAgIHYtbW9kZWw6dmlzaWJsZT1cInBvcFZpc2libGVcIlxuICAgICAgcGxhY2VtZW50PVwiYm90dG9tLXN0YXJ0XCJcbiAgICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgICA6d2lkdGg9XCIzMDBcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIDxlbC10b29sdGlwXG4gICAgICAgICAgICBlZmZlY3Q9XCJsaWdodFwiXG4gICAgICAgICAgICA6ZGlzYWJsZWQ9XCJwb3BWaXNpYmxlXCJcbiAgICAgICAgICAgIGNvbnRlbnQ9XCJUb29sdGlwXCJcbiAgICAgICAgICAgIDpzaG93LWFmdGVyPVwiMjAwXCJcbiAgICAgICAgICA+XG4gICAgICAgICAgICA8ZWwtYnV0dG9uPiBDbGljayA8L2VsLWJ1dHRvbj5cbiAgICAgICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxkaXY+XG4gICAgICAgIDxsYWJlbD4gU29tZXRoaW5nPC9sYWJlbD5cbiAgICAgIDwvZGl2PlxuICAgIDwvZWwtcG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

**Comment by Alanscut** [comment]
After using v-model, it is a controlled mode, which is displayed and closed by the user.
https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F

**Comment by pavellzubkov** [comment]
so. now we can't control popover state like in v.1.2.0 ?  for watching popover state in version 1.3.0-beta.2 and later we must implement own 'onclick' logic with 'click outside' directives?
