### ISSUE TITLE
[Bug Report] el-select value-key is ignored when selected

### ISSUE THREAD

**Issue by varave** [element-plus/element-plus#5436]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
mac OS 11.6

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-lm79f?file=/src/App.vue

### Steps to reproduce
value-key is ignored when selected (itemSelected)

link to the problematic place in the code: https://github.com/element-plus/element-plus/blob/7ddb04b36c591421c09eda07069ff6db0b317a1c/packages/components/select/src/useOption.ts#L23

### What is Expected?
Correct choice of one option

### What is actually happening?
All elements have a 'selected' class

**Comment by weidehai** [comment]
Maybe your understanding is wrong，value-key just use for 
specify which object property set to uniquely identifies when you bind vmodel with object

**Comment by varave** [comment]
@weidehai i have an array of objects:
```javascript
const selectModel = ref(null)
const options = ref([{
  id: 1,
  label: 'test'
}])
```

```javascript
<el-select v-model="selectModel">
  <el-option
   v-for="item in options"
   :key="item.id"
   :label="item.label"
   :value="item"
   value-key="id"
  >
   {{ item.label }}
  </el-option>
</el-select>
```
what's wrong?

**Comment by weidehai** [comment]
> @weidehai i have an array of objects:
> 
> ```js
> const selectModel = ref(null)
> const options = ref([{
>   id: 1,
>   label: 'test'
> }])
> ```
> 
> ```js
> <el-select v-model="selectModel">
>   <el-option
>    v-for="item in options"
>    :key="item.id"
>    :label="item.label"
>    :value="item"
>    value-key="id"
>   >
>    {{ item.label }}
>   </el-option>
> </el-select>
> ```
> 
> what's wrong?

value-key is the select property

**Comment by varave** [comment]
@weidehai аааа, sorry for my inattention.
yeah, it really works thank you!
