### ISSUE TITLE
[Feature Request] 请求更换加载按钮图标

### ISSUE THREAD

**Issue by idanran** [element-plus/element-plus#5439]
### Existing Component
是

### Component Name
Button

### Description
希望能把加载按钮的图标替换成更加现代化的图标

**Comment by msidolphin** [comment]
How should  be more modern?

**Comment by WangJincheng4869** [comment]
![T%X_0Y U W(BW4}M`$I9(5V](https://user-images.githubusercontent.com/41162158/149856168-cadaa719-846b-4f0a-a4c0-3f6e52edf1f1.png)我猜你是一名资深的“项目经理”

**Comment by Alanscut** [comment]
你可以通过`:icon=""`来使用你自己认为合适的自定义标签。
如果你没有其它问题，我们将关闭这个issue

**Comment by emojiiii** [comment]
> 你可以通过`:icon=""`来使用你自己认为合适的自定义标签。 如果你没有其它问题，我们将关闭这个issue

loading 状态 的图标不可以通过 `:icon=""`设置的... loading状态下会把你设置的图标隐藏，使用loading状态图标

**Comment by emojiiii** [comment]
> > 你可以通过`:icon=""`来使用你自己认为合适的自定义标签。 如果你没有其它问题，我们将关闭这个issue
> 
> loading 状态 的图标不可以通过 `:icon=""`设置的... loading状态下会把你设置的图标隐藏，使用loading状态图标 @Alanscut

**Comment by Alanscut** [comment]
> > 你可以通过`:icon=""`来使用你自己认为合适的自定义标签。 如果你没有其它问题，我们将关闭这个issue
> 
> loading 状态 的图标不可以通过 `:icon=""`设置的... loading状态下会把你设置的图标隐藏，使用loading状态图标 @Alanscut

那就加一个loading-icon的插槽让自己定义吧，我是想不出什么叫更现代化的图标

**Comment by emojiiii** [comment]
> 那就加一个loading-icon的插槽让用户可以自己定义吧，我是想不出什么叫更现代化的图标

你这个也是个办法, 但是需要让他提供更多的信息, 否则直接关掉即可

**Comment by idanran** [comment]
> > 那就加一个loading-icon的插槽让用户可以自己定义吧，我是想不出什么叫更现代化的图标
> 
> 你这个也是个办法, 但是需要让他提供更多的信息, 否则直接关掉即可

像Material Design那种加载图标
