### ISSUE TITLE
[Bug Report] Popover and dropdown not work inside template

### ISSUE THREAD

**Issue by freedomljt** [element-plus/element-plus#5442]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Macos 12.1 / chrome 版本 97.0.4692.71（正式版本） (x86_64)

### Vue version
3.2.27

### Reproduction Link
https://codepen.io/freedomljt/pen/NWaJQJd

### Steps to reproduce
Popover: Click the test button, can not show the popover;

### What is Expected?
popover can show the list

### What is actually happening?
popover list not show

**Comment by cn-troy** [comment]
现在的版本Popover已经不再支持trigger为click或hover类型下同时设置v-model:visible="visible", 
你的问题与 #5424 相同...
我的想法是如果以后的版本都不支持的话, 等待下一个版本提供的hide方法 (#5334) 应该可以实现效果.
