### ISSUE TITLE
[Bug Report] ElDropdown width BUG

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#5448]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
版本 97.0.4692.71（正式版本） （64 位）

### Vue version
3.2.27

### Reproduction Link
https://jsfiddle.net/byL4hfw7/5/

### Steps to reproduce
When the position of the element is on the far right, the menu is displayed many times, and the width is inconsistent

### What is Expected?
The menu is displayed multiple times with the same width

### What is actually happening?
When the position of the element is on the far right, the menu is displayed many times, and the width is inconsistent

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gdHJpZ2dlcj1cImNvbnRleHRtZW51XCIgc3R5bGU9XCJwb3NpdGlvbjogZml4ZWQ7dG9wOjA7cmlnaHQ6MDtcIj5cbiAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIERyb3Bkb3duIExpc3RcbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTIyMjIyMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QUFjdGlvbiAxMjIyMjIyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTIyMjIyMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+QWN0aW9uIDQ8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+QWN0aW9uIDU8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

**Comment by kooriookami** [comment]
Fixed in #5396
