### ISSUE TITLE
el-rate

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#546]
allow-half属性设置样式计算
在计算classes的时候
 let threshold = currentValue.value
  if (props.allowHalf && currentValue.value !== Math.floor(currentValue.value)) {
      threshold--
  }
 result.fill(activeClass.value, 0, threshold)
 result.fill(voidClass.value, threshold, props.max)
如果currentValue.value = 2.5 这样得到的threshold会是1 会导致1的是on但是2的是off
这里的逻辑是否有误？
![image](https://user-images.githubusercontent.com/35122287/98102464-9c575f00-1ece-11eb-8934-c538e89b74b3.png)

**Comment by JeremyWuuuuu** [comment]
Seems our showcases didn't cover case like this.
Are you interested in file up a PR to fix this?
