### ISSUE TITLE
[Bug Report] ElPopover: after-enter and after-leave events not fired

### ISSUE THREAD

**Issue by mawi1512** [element-plus/element-plus#5467]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Win 10 / Chrome 97

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-33wup?file=/src/App.vue

### Steps to reproduce
Click on button to open popover

### What is Expected?
popover events "after-enter" and "after-leave" are fired

### What is actually happening?
both events are not fired

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbi8vIHNldHVwIGZvciBlbGVtZW50IHBsdXMsIGRvbid0IHJlbW92ZS5cbnNldHVwRWxlbWVudFBsdXMoKTtcblxuY29uc3QgbGFzdEV2ZW50ID0gcmVmKFwibm9uZVwiKTtcbmZ1bmN0aW9uIG9uQWZ0ZXJFbnRlcigpIHtcbiAgbGFzdEV2ZW50LnZhbHVlID0gXCJhZnRlci1lbnRlciBmaXJlZFwiO1xufVxuXG5mdW5jdGlvbiBvbkFmdGVyTGVhdmUoKSB7XG4gIGxhc3RFdmVudC52YWx1ZSA9IFwiYWZ0ZXItbGVhdmUgZmlyZWRcIjtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIExhc3RFdmVudDoge3sgbGFzdEV2ZW50IH19XG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIHRpdGxlPVwiVGl0bGVcIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImNsaWNrXCJcbiAgICBjb250ZW50PVwidGhpcyBpcyBjb250ZW50LCB0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudFwiXG4gICAgQGFmdGVyLWVudGVyPVwib25BZnRlckVudGVyXCJcbiAgICBAYWZ0ZXItbGVhdmU9XCJvbkFmdGVyTGVhdmVcIlxuICA+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)
