### ISSUE TITLE
Import Element Plus components onDemand

### ISSUE THREAD

**Issue by BezMaster** [element-plus/element-plus#548]
Hi, actualy i try to use your element plus but i can not load only compoents i want to use. I followed the documentation in 
https://element-plus.org/#/en-US/component/quickstart

I tried with app.use:

`import { Button, Select } from 'element-plus';`
`const app = createApp(App)`
`app.use(Button);`

But It does not work :(

I tried with app.component:

`import { Button, Select } from 'element-plus';`
`const app = createApp(App)`
`app.component(Button.name, Button);`

But It does not work too :(

Can you help me please to find the good way to do that.

Thanks a lot

**Comment by JeremyWuuuuu** [comment]
Sorry for the late response.
We were working on the import on demand, but you still need to use a `babel-plugin` to do that.
cc @zouhangwithsweet  Could you provide some help?
BTW, what version you were using? We just got our **alpha 14** released, it should work fine with tree shaking

**Comment by zouhangwithsweet** [comment]
For now, all components export with prefix `El`. We are discussing how to export  `install` and component.
E.g.
```js
import { ElButton, ElSelect } from 'element-plus';
const app = createApp(App)
app.use(ElButton);
```

**Comment by BezMaster** [comment]
im using element-plus@1.0.1-alpha.14

**Comment by BezMaster** [comment]
sorry @zouhangwithsweet but it does work for me it says : 

`TS2724: Module '"../node_modules/element-plus/types"' has no exported member 'ElButton'. Did you mean 'Button'?`

**Comment by wenyangliu** [comment]
you can use:
```
import Button from 'element-plus';
const app = createApp(App)
app.use(Button);
```

that's fine with me @BezMaster

**Comment by BezMaster** [comment]
@wenyangliu 
When you load element-plus like that, you load all elements-plus components. In fact in your sample Button contains all elements-plus imports not just the Button import. I'm sure that you can write <el-input in your code and you can see the input ;(.

**Comment by BezMaster** [comment]
I solved my problem like below:
`
import { Button, Input } from "element-plus";

const app = createApp(App);
app.use(Button as any);
app.use(Input as any);
`

**Comment by BezMaster** [comment]
I solved my problem like below:
import { Button, Input } from "element-plus";
const app = createApp(App);
app.use(Button as any);
app.use(Input as any);
