### ISSUE TITLE
[Feature Request] El-tab-pane, the traversal loop, cannot get the ref of the content component in VUe3

### ISSUE THREAD

**Issue by yjun666** [element-plus/element-plus#5483]
### Existing Component
Yes

### Component Name
el-tabs el-tab-pane

### Description
vue3 中setup 中使用const user=ref(); 的方式 获取不到遍历后的el-tab-pane 的内容的ref值

**Comment by emojiiii** [comment]
不明白你的意思，可以麻烦你再详细一点描述吗？
