### ISSUE TITLE
[Bug Report] Popover 的延迟关闭不生效

### ISSUE THREAD

**Issue by ttdms** [element-plus/element-plus#5485]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
EDGE

### Vue version
3.2.27

### Reproduction Link
https://codepen.io/ttdms/pen/PoJgLLy

### Steps to reproduce
Popover的hide-after不管设置多少毫秒，都是默认200毫秒

### What is Expected?
需要得到修复

### What is actually happening?
hide-after该项设置无效

**Comment by emojiiii** [comment]
Duplicate of #5372
