### ISSUE TITLE
[Feature Request] 有没有加入滚动监听组件的计划？

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#5487]
### Existing Component
否

### Component Name
Scrollspy 滚动监听组件

### Description
有没有加入滚动监听组件的计划，类似bootstrap这种东西 [https://v5.bootcss.com/docs/components/scrollspy/](url)

当然我发现API文档就有用到类似的组件，只不过只是竖排使用，没有横向排列
![image](https://user-images.githubusercontent.com/41162158/150060805-74122257-116d-4ee5-912c-393ac665765d.png)

**Comment by iamkun** [comment]
we have no plan at the moment, still, you can build it simply using
![image](https://user-images.githubusercontent.com/17680888/150069594-eb03db55-c01d-4681-9620-a1efebc16ad7.png)
ref https://v5.bootcss.com/docs/components/scrollspy/
