### ISSUE TITLE
[Bug Report] El-upload accepts different formats even if 'accept' attribute is provided.

### ISSUE THREAD

**Issue by Manu-Geotourist** [element-plus/element-plus#5489]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Mac

### Vue version
3.2.27

### Reproduction Link
https://jsfiddle.net/7q4Lhoyt/2/

### Steps to reproduce
1. Create an Upload Element.
2. Give '.png' as value for 'accept attribute'.
3. Enable 'drag'.
4. When we are browsing for elements it will accept only .png but when dragging a file , its accepting all file formats.

### What is Expected?
Should accept only .png files 

### What is actually happening?
Accepting all kinds of files

**Comment by Manu-Geotourist** [comment]
@emojiiii

**Comment by JeremyWuuuuu** [comment]
@Manu-Geotourist  Per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept

> The accept attribute value is a string that defines the file types the file input should accept. This string is a comma-separated list of unique file type specifiers. Because a given file type may be identified in more than one manner, it's useful to provide a thorough set of type specifiers when you need files of a given format.

Even though we can find a way to pass that check, but I think we still need to check on this attribute. This can be some sort of enhancement to make.

**Comment by JeremyWuuuuu** [comment]
Note that the extension name should never represent the file's type (the meta data does), meaning you can name any text file `.png` even though it cannot be parsed by the codec. @Manu-Geotourist Would you like to contribute on this one? When dragging we should definitely check on that.

**Comment by ChenAdien** [comment]
I tried and couldn't reproduce it. When accept is set, dragging other types of files can't be uploaded. Is it related to the operating system? I'm windows 10
`accept=".png"`
Related source code：

![image](https://user-images.githubusercontent.com/38248854/150481661-71880f4c-ed13-472b-9d50-4c0e0c94adef.png)

**Comment by sxzz** [comment]
`accept` a native attribute. If you want to check file, please use `before-upload` hook
