### ISSUE TITLE
[Feature Request] 动态面包屑导航栏可以根据浏览记录动态修改导航栏吗？

### ISSUE THREAD

**Issue by chengwei12138** [element-plus/element-plus#5492]
### Existing Component
Yes

### Component Name
Breadcrumb

### Description
现在的面包屑导航栏需要写死再前端的js代码中，是否能够根据history获取对应的信息来动态修改导航信息？

**Comment by chengwei12138** [comment]
在vue-router的history的钩子函数或者window的history中获取对应的浏览记录

**Comment by chengwei12138** [comment]
> ### Existing Component
> Yes
> 
> ### Component Name
> Breadcrumb
> 
> ### Description
> 现在的面包屑导航栏需要写死再前端的js代码中，是否能够根据history获取对应的信息来动态修改导航信息？

**Comment by msidolphin** [comment]
你可以按照你们业务要求去使用面包屑组件
