### ISSUE TITLE
Bug with Popover

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#550]
https://element-plus.org/#/zh-CN/component/popover
First demo.
Click to activate: cannot close on click blank.
Focus to activate: when blur, it still shows

`Popconfirm`
miss the border
![image](https://user-images.githubusercontent.com/38392315/98194853-48df2280-1f5b-11eb-96c0-60f87e5f1230.png)

**Comment by JeremyWuuuuu** [comment]
Indeed, will be fixed soon.

**Comment by JeremyWuuuuu** [comment]
@kooriookami with #557 should resolve the problem, but we are still awaiting for the next release. So you won't be able to use it til alpha 15.
