### ISSUE TITLE
[Bug Report] menu组件折叠问题

### ISSUE THREAD

**Issue by ZYC-ts** [element-plus/element-plus#5506]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
 Chrome 97.0.4692.71

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/crazy-nightingale-yfdyr?file=/src/App.vue

### Steps to reproduce
menu菜单折叠展开，左侧icon会轻微抖动位移

### What is Expected?
折叠展开时侧边不抖动

### What is actually happening?
menu菜单折叠展开，左侧icon会轻微抖动位移

**Comment by Winston-Guess** [comment]
This occurs for me too (1.3.0-beta.10) an example of this is on the current element-plus components [collapse menu example](https://element-plus.org/en-US/component/menu.html#collapse).

**Comment by wanfuxiong** [comment]
This still Occurs in 2.0.2

**Comment by wanfuxiong** [comment]
This still occurs in 2.0.2

**Comment by wanfuxiong** [comment]
Here's a gif
[pan.baidu.com](https://pan.baidu.com/s/1EJBoYvCpBUAEYxs8Urs7IA)
Code:7ubn
