### ISSUE TITLE
[Bug Report] 分页器的jumper如果输入带小数的数字会导致格式化错误

### ISSUE THREAD

**Issue by royalscome** [element-plus/element-plus#5509]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Google Chrome 97.0.4692.71（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/royalscome/pen/OJxYryB?editors=1111

### Steps to reproduce
1.引入el-pagination并使用jumper;
2.在jumper的输入框中输入带小数的数字回车，需要确保输入的数字不大于最大页码；

### What is Expected?
希望输入带小数的数字后可以自动格式化为整数，类似element ui的el-pagination

### What is actually happening?
因为这个bug导致我们在自定义table的index的时候index变成了小数

**Comment by QianTangrong** [comment]
yes
