### ISSUE TITLE
Element Plus 组件内部默认使用中文？为什么时间组件和table组件等等这些默认都是英文的？

### ISSUE THREAD

**Issue by huanyun-c** [element-plus/element-plus#551]

**Comment by pangao66** [comment]
相同的问题 +1    confirm等 组件的 文案都是英文

**Comment by zazzaz** [comment]
Sorry for the late update of the docs. 

Element Plus is aimed to be an international UI libiary and the default language is English.

For Chinese users, you should import the relavant locale file according to the doc.

**Comment by pangao66** [comment]
Even though I set the  Chinese as default language the components still show the English .
main.js
```js
import ElementPlus from 'element-plus'
import '../element-variables.scss'
import type { App } from 'vue'
import lang from 'element-plus/lib/locale/lang/zh-CN'

export default (app: App<Element>) => {
  app.use(ElementPlus, { locale })
}
```
我按照文档来的, 但是页面已经显示是英文文案

**Comment by zazzaz** [comment]
@pangao66 well it's a bug, will fix it soon.

**Comment by zazzaz** [comment]
will be available in next release

**Comment by lighter217** [comment]
我也遇到这个问题，刚想提issue来着(手动捂脸)
