### ISSUE TITLE
[Bug Report] 在表格中 expand 嵌套子表格，子表格使用 fixed 属性无效

### ISSUE THREAD

**Issue by MrFu1998** [element-plus/element-plus#5521]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
MacOS / 97.0.4692.71 (正式版本) (arm64)

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/elp-table-demo-gc1g1?file=/src/App.vue

### Steps to reproduce
* Click on the first column to expand / 点击第一列的expand展开表格
* Drag the table scrollbar /  拖动表格滚动条

### What is Expected?
The fiexd attribute of the operation column in the expanded table should take effect
展开的表格中的操作列fiexd属性应生效

### What is actually happening?
The operation column fiexd attribute in the expanded table is disabled
展开的表格中的操作列fiexd属性失效

**Comment by msidolphin** [comment]
The width of the nested table does not overflow

**Comment by MrFu1998** [comment]
Indeed. thanks

**Comment by MrFu1998** [comment]
> The width of the nested table does not overflow

Indeed. thanks
