### ISSUE TITLE
[Bug Report] 基于断点的隐藏类 文档错误

### ISSUE THREAD

**Issue by anzhiyu-c** [element-plus/element-plus#5523]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/embed/element-plus-spa-forked-kh4kw?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
https://doc-archive.element-plus.org/#/zh-CN/component/layout
官网基于断点的隐藏类文档描述错误
在main.js中导入import 'element-plus/theme-chalk/display.css'

### What is Expected?
引入链接应该为import 'element-plus/theme-chalk/display.css'

### What is actually happening?
但是文档上写的import 'element-plus/lib/theme-chalk/display.css'

**Comment by emojiiii** [comment]
please see new [docs](https://element-plus.org/en-US/component/layout.html#utility-classes-for-hiding-elements)
