### ISSUE TITLE
[Bug Report] ElPopper  popper-class 添加类名样式不起效果

### ISSUE THREAD

**Issue by q2419068625** [element-plus/element-plus#5529]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10 /Chrome 版本 97.0.4692.99

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-m96uf?file=/src/App.vue

### Steps to reproduce
Scoped CSS 相关样式没生效

### What is Expected?
样式生效

### What is actually happening?
用 scoped  样式不生效， 不用 scoped 的话可以生效样式

**Comment by msidolphin** [comment]
please ref https://v3.vuejs.org/api/sfc-style.html
