### ISSUE TITLE
[Bug Report] Upload拖动上传在移动端无法正常显示

### ISSUE THREAD

**Issue by idanran** [element-plus/element-plus#5546]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
无

### Vue version
3.2.28

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
展示

### What is Expected?
自适应

### What is actually happening?
组件超出屏幕宽度

**Comment by sxzz** [comment]
Not designed for mobile phones.
