### ISSUE TITLE
[Bug Report] 多个Button在移动端竖向排列时,第一个按钮会向左偏移

### ISSUE THREAD

**Issue by idanran** [element-plus/element-plus#5547]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
无

### Vue version
3.2.28

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
展示

### What is Expected?
竖向对齐

### What is actually happening?
第一个按钮向左偏移

**Comment by idanran** [comment]
https://codepen.io/idanran/pen/yLzmMMd 请在小屏设备上访问呢

**Comment by msidolphin** [comment]
> https://codepen.io/idanran/pen/yLzmMMd 请在小屏设备上访问呢

We want to have some spacing between the buttons, you can override the style yourself if necessary

**Comment by idanran** [comment]
> > https://codepen.io/idanran/pen/yLzmMMd 请在小屏设备上访问呢
> 
> We want to have some spacing between the buttons, you can override the style yourself if necessary

在大屏设备上这是没问题的，但在小屏设备上这是个值得关注的问题。

**Comment by idanran** [comment]
我希望它在每个设备都能有最好的显示效果。例如：在大屏设备上横向排列时按钮间能保持距离，在小屏设备上纵向排列时第一个按钮不向左偏移。
