### ISSUE TITLE
[Bug Report] 使用自动引入的情况下,样式丢失

### ISSUE THREAD

**Issue by idanran** [element-plus/element-plus#5554]
### Element Plus version
1.3.0-beta.6

### OS/Browsers version
无

### Vue version
3.2.28

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
使用unplugin-vue-components和unplugin-auto-import

### What is Expected?
正常显示

### What is actually happening?
样式丢失

**Comment by idanran** [comment]
使用了vite

**Comment by LouisgogoLi** [comment]
我用vue cli使用unplugin-vue-components和unplugin-auto-import
自動引用元件時報了一堆錯 


 error  in ./node_modules/element-plus/es/components/notification/src/notification2.mjs

Module parse failed: Unexpected token (44:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     function clearTimer() {
>       timer?.();
|     }
|     function close() {

 @ ./node_modules/element-plus/es/components/notification/src/notify.mjs 7:0-58 53:25-48
 @ ./node_modules/element-plus/es/components/notification/index.mjs
 @ ./node_modules/element-plus/es/index.mjs
 @ ./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--40-0!./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--41-0!./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/vue-loader-v16/dist/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/About.vue?vue&type=template&id=039c5b43
 @ ./src/views/About.vue?vue&type=template&id=039c5b43
 @ ./src/views/About.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.18.154:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/element-plus/es/components/popper/src/content.mjs


1.3.0-beta.5沒有這些問題

**Comment by sxzz** [comment]
Fixed via #5558

**Comment by zhangchenna** [comment]
ElNotification 在引入组件的时候依然会样式丢失
