### ISSUE TITLE
[Bug Report] 从 1.3.0-beta.5 升级到 1.3.0-beta.7 打包错误

### ISSUE THREAD

**Issue by Sunshop** [element-plus/element-plus#5563]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
mac os 12.1  chrome v97.0.4692.99

### Vue version
3.2.28

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
npm i
npm run build

### What is Expected?
打包 success

### What is actually happening?
 Failed to compile with 52 errors                                                                                                                                                                        10:58:52 PM

 error  in ./node_modules/element-plus/es/components/date-picker/src/date-picker-com/basic-date-table.mjs

Module parse failed: Unexpected token (106:28)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|           const calEndDate = props.rangeState.endDate || props.maxDate || props.rangeState.selecting && props.minDate;
|           cell.inRange = props.minDate && calTime.isSameOrAfter(props.minDate, "day") && calEndDate && calTime.isSameOrBefore(calEndDate, "day") || props.minDate && calTime.isSameOrBefore(props.minDate, "day") && calEndDate && calTime.isSameOrAfter(calEndDate, "day");
>           if (props.minDate?.isSameOrAfter(calEndDate)) {
|             cell.start = calEndDate && calTime.isSame(calEndDate, "day");
|             cell.end = props.minDate && calTime.isSame(props.minDate, "day");

**Comment by KKKZOZ** [comment]
I have this probelm,too 
![image](https://user-images.githubusercontent.com/70520782/150647923-5d1c9b1e-1bbc-40b1-a45f-b335f614ba18.png)

**Comment by Luotianxu-ltx** [comment]
ERROR  Failed to compile with 105 errors                                                                                                                                                                                                                                 上午10:44:50

 error  in ./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js

Syntax Error: Error: ENOENT: no such file or directory, open 'E:\vue3-webpack-admin\node_modules\@babel\runtime\helpers\esm\asyncToGenerator.js'


 @ ./src/router/index.ts 1:0-121 34:13-30
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:7000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by paokuaikuai** [comment]
I also have the same problem.

**Comment by LouisgogoLi** [comment]
I also have the same problem.

**Comment by ajw333** [comment]
I started from 1.3.0 Upgrade beta 5 to 1.3.0 Beta 7 also encountered this problem, which was tested on windows and MAC 11 6, and 1.3.0 was also tested beta1，1.3.0. beta2，1.3.0. beta3，1.3.0. beta4，1.3.0. beta 5, this problem occurs when the dev environment is running.

**Comment by Cheerwhy** [comment]
same problem,
already have newest vue-cli-plugin

**Comment by sxzz** [comment]
使用的是Webpack 4吗？需要添加babel把optional chaining 转译

Do you guys using Webpack 4? You need add Babel and transform optional chaining.

**Comment by ajw333** [comment]
> 

怎样转译

**Comment by sxzz** [comment]
FYI, https://danw1ld.medium.com/optional-chaining-for-javascript-with-babel-7-and-webpack-4-2de8fd9dbdd5

**Comment by ajw333** [comment]
被关了

**Comment by sxzz** [comment]
For Vue CLI user, please consider codes below
```
module.exports = {
  transpileDependencies: ['element-plus'],
}
```

**Comment by ajw333** [comment]
@sxzz    Thank you for solving the problem

**Comment by pany-ang** [comment]
https://github.com/un-pany/v3-admin/commit/6be6e626888eb20536eab6f2753a5206e5790cfc
