### ISSUE TITLE
[Bug Report] 动态渲染el-table-column后，其他el-table-column下template的el-input出现重复

### ISSUE THREAD

**Issue by ethanzhang524** [element-plus/element-plus#5566]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
Chrome 版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.28

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-rx36j?file=/src/App.vue

### Steps to reproduce
点击【addProp】按钮后，动态添加el-table-column，导致其他列下面的el-input出现覆盖、重复现象

### What is Expected?
正确显示对应列下面的子元素el-input

### What is actually happening?
无法正确显示el-input

**Comment by ethanzhang524** [comment]
[Reproduction Link for element-plus.run](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixyZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuLy8gc2V0dXAgZm9yIGVsZW1lbnQgcGx1cywgZG9uJ3QgcmVtb3ZlLlxuc2V0dXBFbGVtZW50UGx1cygpXG5cbmNvbnN0IGR5bmFtaWNUYWJsZVByb3BzID0gcmVhY3RpdmUoW10pXG5jb25zdCB0YWJsZURhdGE9W1xuICB7XG4gICAgaWQ6IDEsXG4gICAgZGF0ZTogXCIyMDE2LTA1LTAyXCIsXG4gICAgbmFtZTogXCJcIixcbiAgICBhZGRyZXNzOiBcIlwiLFxuICAgIGFkZHJlc3MyOiBcIlwiLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgZGF0ZTogXCIyMDE2LTA1LTA0XCIsXG4gICAgbmFtZTogXCJcIixcbiAgICBhZGRyZXNzOiBcIlwiLFxuICAgIGFkZHJlc3MyOiBcIlwiLFxuICB9LFxuXVxuXG5jb25zdCBvbkFkZENsaWNrID0gKCkgPT4ge1xuICBkeW5hbWljVGFibGVQcm9wcy5wdXNoKGBwcm9wJHtkeW5hbWljVGFibGVQcm9wcy5sZW5ndGh9YCk7XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9uQWRkQ2xpY2tcIj5hZGRQcm9wPC9lbC1idXR0b24+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0cmlwZT5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCLml6XmnJ9cIiB3aWR0aD1cIjE4MFwiPiA8L2VsLXRhYmxlLWNvbHVtbj5cblxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cInByb3AgaW4gZHluYW1pY1RhYmxlUHJvcHNcIiA6a2V5PVwicHJvcFwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiA6bGFiZWw9XCJwcm9wXCIgYWxpZ249XCJjZW50ZXJcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgICA8dGVtcGxhdGUgdi1zbG90PVwic2NvcGVcIj5cbiAgICAgICAgICA8c3Bhbj57eyBzY29wZS5yb3cubmFtZSB9fTwvc3Bhbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwi5aeT5ZCNMVwiIHdpZHRoPVwiMTgwXCI+XG4gICAgICA8dGVtcGxhdGUgdi1zbG90PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLWlucHV0XG4gICAgICAgICAgOm5hbWU9XCIxXCJcbiAgICAgICAgICB2LW1vZGVsPVwic2NvcGUucm93Lm5hbWVcIlxuICAgICAgICAgIHBsYWNlaG9sZGVyPVwi5aeT5ZCNXCJcbiAgICAgICAgPjwvZWwtaW5wdXQ+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIuWcsOWdgDFcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlIHYtc2xvdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1pbnB1dFxuICAgICAgICAgIDpuYW1lPVwiMlwiXG4gICAgICAgICAgdi1tb2RlbD1cInNjb3BlLnJvdy5hZGRyZXNzXCJcbiAgICAgICAgICBwbGFjZWhvbGRlcj1cIuWcsOWdgFwiXG4gICAgICAgID48L2VsLWlucHV0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzMlwiIGxhYmVsPVwi5Zyw5Z2AMlwiIHdpZHRoPVwiMTgwXCI+XG4gICAgICA8dGVtcGxhdGUgdi1zbG90PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLWlucHV0XG4gICAgICAgICAgOm5hbWU9XCIzXCJcbiAgICAgICAgICB2LW1vZGVsPVwic2NvcGUucm93LmFkZHJlc3MyXCJcbiAgICAgICAgICBwbGFjZWhvbGRlcj1cIuWcsOWdgDJcIlxuICAgICAgICAgIDpkaXNhYmxlZD1cInNjb3BlLnJvdy5pZCAhPT0gMFwiXG4gICAgICAgID48L2VsLWlucHV0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by msidolphin** [comment]
Please add a key to the list item https://v3.vuejs.org/api/special-attributes.html#key
