### ISSUE TITLE
[Bug Report] 关于 element-plus 官网文档 https://element-plus.gitee.io/zh-CN/ 长页面时，滚动条太细且不明显，查阅时候不方便/不好操作

### ISSUE THREAD

**Issue by warmthsea** [element-plus/element-plus#5577]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
win11  / chrome@last 

### Vue version
3.2.29

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
打开 https://element-plus.gitee.io/zh-CN/component/table.html 切换较长组件的文档，看滚动条

### What is Expected?
1、现基础代码 ::-webkit-scrollbar、::-webkit-scrollbar-thumb 调宽； 2、滚动条使用 浏览器 默认的 例如： https://zhuanlan.zhihu.com/p/460055155，https://v3.cn.vuejs.org/
![image](https://user-images.githubusercontent.com/45450994/150708399-05e90988-4e44-4ab9-aed1-5c11c2c2ff90.png)
![image](https://user-images.githubusercontent.com/45450994/150708429-885d9c89-aa19-43dd-a31a-2e0b707fbd57.png)
![image](https://user-images.githubusercontent.com/45450994/150708559-afa046ec-8014-4d75-a00f-30a585a4264c.png)

### What is actually happening?
文档滚动条，太细
![image](https://user-images.githubusercontent.com/45450994/150708347-333007e8-3d9f-4677-8d0a-1ea83174fc49.png)

**Comment by WHYwanghuayang** [comment]
![image](https://user-images.githubusercontent.com/45450994/150708188-9d9b7e9f-cc25-4027-94e7-ef61a65fca1a.png)
