### ISSUE TITLE
[Feature Request] 希望`el-select`等组件下在关闭弹出状态下销毁整个`el-popover`下的元素而不是隐藏它

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5579]
### Existing Component
是

### Component Name
`el-popover`和`el-select` 

### Description
希望`el-select`等组件下在关闭弹出状态下销毁整个`el-popover`下的元素而不是隐藏它，类似与`v-if`而不是`v-show`，或者给一个参数让我们控制是否销毁，我认为这对能提升页面性能是有帮助的。

**Comment by mxp131011** [comment]
现在临时解决方式：只有当显示时才渲染列表，这样也可以减少很多dom
![1642993042(1)](https://user-images.githubusercontent.com/31055355/150714756-3c9e5b8d-1c4a-47ff-bd02-ed7b0bcc430a.jpg)

**Comment by tolking** [comment]
Used `persistent ="false"`
