### ISSUE TITLE
[Bug Report] `el-table` 设置`max-height`后高度始终为`max-height`的高度,而不是只有当内容超过`max-height`才为`max-height`，即相当与:css中`max-height`和`height`完全等效

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5580]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
win11/谷歌最新版

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/mxp131011/pen/WNZLNzx

### Steps to reproduce
`el-table` 设置`max-height`后高度始终为`max-height`的高度,而不是只有当内容超过`max-height`才为`max-height`，即相当与:css中`max-height`和`height`完全等效

### What is Expected?
只有当内容超过`max-height`才为`max-height`

### What is actually happening?
不管内容高度小于或大于`max-height`都为`max-height`

**Comment by 406087475** [comment]
复议

**Comment by huisir001** [comment]
附议

**Comment by Vadizar** [comment]
Since version 1.3.0-beta.6 scrolling the header in the table is again very slow.

**Comment by 406087475** [comment]
> Since version 1.3.0-beta.6 scrolling the header in the table is again very slow.

是的，新的动画效果简直卡到爆炸，日期选择的也是这样
