### ISSUE TITLE
[Bug Report] pnpm run docs:dev 默认是en-us  怎么切换语言

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#5581]
### Element Plus version
1.3.0-beta.7

### Vue version
3.2.29

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
pnpm docs:gen-locale
pnpm docs:dev

### What is Expected?
生成的预览可以切换语言

### What is actually happening?
切换不了多语言

**Comment by xiaoxian521** [comment]
The document is translated online by [crowdin](https://support.crowdin.com/translation-process-overview), and only `en-us` can be used locally
