### ISSUE TITLE
[Feature Request] 怎么动态渲染icons

### ISSUE THREAD

**Issue by guohuihot** [element-plus/element-plus#5588]
### Existing Component
Yes

### Component Name
icon

### Description
```jsx
import {  resolveDynamicComponent, } from 'vue'
import * as Icons from '@element-plus/icons-vue'
setup() {
    return  ()=> {
        return <div>
           {resolveDynamicComponent(Icons['Document'])}
        </div>
  }
}
```

**Comment by gjfei** [comment]
<el-icon>
<component :is="Icons['Document]" />
</el-icon>

**Comment by guohuihot** [comment]
> <el-icon> <component :is="Icons['Document]" /> </el-icon>
![image](https://user-images.githubusercontent.com/3119995/150896357-0a97711f-98e8-4056-acc8-a6bed555b89b.png)

jsx里不行，

**Comment by gjfei** [comment]
> ```js
> resolveDynamicComponent
> ```
```
<el-icon> { h(resolveDynamicComponent(Icons['Document])) } </el-icon>
```

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/150899376-c2678407-9b41-42a3-8b22-89050c037e22.png)
![image](https://user-images.githubusercontent.com/3119995/150899384-68a9318e-da64-4400-8e45-d587a61ed306.png)
这就是我最开始的写法

**Comment by gjfei** [comment]
> ![image](https://user-images.githubusercontent.com/3119995/150899376-c2678407-9b41-42a3-8b22-89050c037e22.png) ![image](https://user-images.githubusercontent.com/3119995/150899384-68a9318e-da64-4400-8e45-d587a61ed306.png) 这就是我最开始的写法
resolveDynamicComponent 返回的要渲染的话要用h 函数去渲染

**Comment by gjfei** [comment]
> > ![image](https://user-images.githubusercontent.com/3119995/150899376-c2678407-9b41-42a3-8b22-89050c037e22.png) ![image](https://user-images.githubusercontent.com/3119995/150899384-68a9318e-da64-4400-8e45-d587a61ed306.png) 这就是我最开始的写法
> > resolveDynamicComponent 返回的要渲染的话要用h 函数去渲染

https://v3.cn.vuejs.org/guide/render-function.html#component-%E5%92%8C-is

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbmltcG9ydCAqIGFzIEljb25zIGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG4vLyBzZXR1cCBmb3IgZWxlbWVudCBwbHVzLCBkb24ndCByZW1vdmUuXG5zZXR1cEVsZW1lbnRQbHVzKClcblxuY29uc3QgbXNnID0gcmVmKCdVc2VyJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj5cbiAgXHQ8Y29tcG9uZW50IDppcz1cIkljb25zW21zZ11cIj48L2NvbXBvbmVudD5cbiAgPC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

@guohuihot

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/150935480-0bd5ffe5-6b83-4cc1-9634-28da8558681a.png)
![image](https://user-images.githubusercontent.com/3119995/150935513-773a12e1-e2da-44a3-ba06-6b50c22009a2.png)
麻烦再给看一下
@emojiiii

**Comment by emojiiii** [comment]
你这应该是jsx 没办法识别 `component` 内置组件的问题，如果你想在 jsx 使用动态组件，你应该使用 `h` + `resolveComponent`

**Comment by eosbp** [comment]
动态渲染的可以试下我这方法：https://blog.csdn.net/qq_35624642/article/details/122664233

**Comment by Ly2JR** [comment]
我是这样使用的，运行正常，你可以参考下
1: 注册icons组件在main.ts里，像这样
```
import {HomeFilled,} from "@element-plus/icons-vue";
app.component("HomeFilled", HomeFilled);
```
2: 使用`<el-icon><component :is="HomeFilled" /></el-icon>`

**Comment by guohuihot** [comment]
<el-icon> { h(resolveDynamicComponent(Icons['Document])) } </el-icon>
这个可以，3ks
