### ISSUE TITLE
[Bug Report] tabel-column type="selection" 时报错

### ISSUE THREAD

**Issue by guohuihot** [element-plus/element-plus#5593]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
win10

### Vue version
3.2.29

### Reproduction Link
2

### Steps to reproduce
2

### What is Expected?
2

### What is actually happening?
2

![image](https://user-images.githubusercontent.com/3119995/150745053-b5ca728d-c57a-46d1-a647-4da0a3712218.png)

**Comment by cn-troy** [comment]
这是因为table设置了size='mini'导致的警告. 
现在的size支持3个值, 分别是: 'large', 'default', 'small'

**Comment by emojiiii** [comment]
> 这是因为table设置了size='mini'导致的警告. 现在的size支持3个值, 分别是: 'large', 'default', 'small' @emojiiii this issues is not bug

这里是因为`checkbox`设置的`size`问题，需要更改默认值以去除警告。当成一个不影响功能的`bug`处理

**Comment by guohuihot** [comment]
就这就关闭了？这个还需要demo吗？随便一个都有问题哦

**Comment by emojiiii** [comment]
> 就这就关闭了？这个还需要demo吗？随便一个都有问题哦

需要一个demo，麻烦提供一个demo。我试了一下没复现，麻烦一下 @guohuihot

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/152931058-52fda447-edbd-4495-a3dd-63c1b1d547f5.png)
不好意思，经过排查是我的错，在table上设置了size出现的问题

**Comment by emojiiii** [comment]
没事，找到问题就好~
