### ISSUE TITLE
[Bug Report] calendar component range property bug

### ISSUE THREAD

**Issue by ICollection** [element-plus/element-plus#5595]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
Win10 Chrome 97.0.4692.71

### Vue version
3.2.13

### Reproduction Link
https://codepen.io/ICollection/pen/GROKroR

### Steps to reproduce
set calendar.range  '2021-03-28','2021-05-01' or ''1999-12-26','2000-01-01' or ......
will report ElementPlusError: [ElCalendar] start time and end time interval must not exceed two months

### What is Expected?
solve this bug

### What is actually happening?
ElementPlusError: [ElCalendar] start time and end time interval must not exceed two months

**Comment by emojiiii** [comment]
I didn't find the error.
sorry, i don't know what your mean.

**Comment by ICollection** [comment]
like this https://codepen.io/ICollection/pen/mdqbgqw

**Comment by emojiiii** [comment]
it's not a bug because  `el-calendar` start time and end time interval must not exceed two months.
please see the [docs](https://element-plus.org/en-US/component/calendar.html#range)

**Comment by ICollection** [comment]
[new Date('1999-12-26'), new Date('2000-01-01')]，7days

**Comment by emojiiii** [comment]
Please use `[new Date(1999,12,26), new Date(2000,1,1)]` temporarily. @ICollection

**Comment by ICollection** [comment]
new Date(1999,12,26)=‘1999-13-26’
new Date(2000,1,1)=‘2000-02-01’

**Comment by emojiiii** [comment]
I'm sorry, I misunderstood you.
The cause of the problem is the improper handling of the cross year. @ICollection

**Comment by ICollection** [comment]
ok

**Comment by emojiiii** [comment]
this is a bug, i will closed this issues when we fixed it
