### ISSUE TITLE
[Bug Report] checkbox 样式默认成了置灰

### ISSUE THREAD

**Issue by frontYang** [element-plus/element-plus#5609]
### Element Plus version
1.3.0-beta.8

### OS/Browsers version
chrome

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/frontyang/pen/vYWBwKR

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/checkbox.html

### What is Expected?
正常展示样式

### What is actually happening?
checkbox 样式默认成了置灰

**Comment by JeremyWuuuuu** [comment]
Fixed in https://github.com/element-plus/element-plus/commit/a34ad9c53dd382eb122ad70326de64e0ea8188af, I accidentally pushed into dev.. Sorry for that.

**Comment by JeremyWuuuuu** [comment]
This will be fixed very soon! Sorry for the trouble.
