### ISSUE TITLE
[Feature Request] el-select-v2希望增加值和标签的自定义属性值

### ISSUE THREAD

**Issue by frontYang** [element-plus/element-plus#5614]
### Existing Component
Yes

### Component Name
el-select-v2

### Description
现在自定义属性不生效，options只能使用固定属性值（label,value）才能生效，如果数据量过多的情况下，转化数据会存在性能问题，希望能增加个自定义属性值的属性
现在的效果：https://codepen.io/frontyang/pen/vYWBqRY
![image](https://user-images.githubusercontent.com/16046879/150910492-69b67c55-de80-4850-9527-0baa867f41bd.png)

**Comment by emojiiii** [comment]
Duplicate of #5051
