### ISSUE TITLE
[Bug Report] `el-checkbox` 样式错误 （选中状态和未选中状态的样式都为禁用状态的样式）

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5618]
### Element Plus version
1.3.0-beta.8

### OS/Browsers version
win11/谷歌

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/mxp131011/pen/VwrwZyx

### Steps to reproduce
1.3.0-beta.8 中  `el-checkbox`  选中状态和未选中状态的样式都为禁用状态的样式  （只是样式为禁用状态的样式，但不影响选中或者取消选中）

1.3.0-beta.7中是正常的

### What is Expected?
样式正常

### What is actually happening?
样式不正常

**Comment by emojiiii** [comment]
Duplicate of #5609
