### ISSUE TITLE
[Bug Report] el-table 存在固定列时，鼠标移动表格行不变色，没有hover状态了

### ISSUE THREAD

**Issue by wtq1996503** [element-plus/element-plus#5623]
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
谷歌 97

### Vue version
3.2.28

### Reproduction Link
https://codepen.io

### Steps to reproduce
el-table 存在固定列时，鼠标移动表格行不变色，没有hover状态了

### What is Expected?
修复此问题

### What is actually happening?
el-table 存在固定列时，鼠标移动表格行不变色，没有hover状态了

**Comment by wtq1996503** [comment]
![Snipaste_2022-01-25_17-22-55](https://user-images.githubusercontent.com/51228740/150948881-f13a103d-1d17-4762-a794-f0c40ba65c42.png)

**Comment by wtq1996503** [comment]
官网就有此问题  https://element-plus.gitee.io/zh-CN/component/table.html#%E6%B5%81%E4%BD%93%E9%AB%98%E5%BA%A6

**Comment by wtq1996503** [comment]
一直回滚到 "element-plus": "^1.2.0-beta.6",此问题消失

**Comment by Vadizar** [comment]
Since version 1.3.0-beta.6 scrolling the header in the table is again very slow.

**Comment by msidolphin** [comment]
> Since version 1.3.0-beta.6 scrolling the header in the table is again very slow.

What does scrolling the header mean? Can you provide more information?
