### ISSUE TITLE
[Feature Request] 能否提供一个侧边导航的组件

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#5627]
### Existing Component
No

### Component Name
el-anchor

### Description
我看到官方文档组件介绍页面右侧是有这个功能的，但并没有封装成组件，希望官方能封装并提供下，感觉是比较需要的，尤其是带锚点功能的侧边导航组件

相关参考：
https://www.naiveui.com/zh-CN/os-theme/components/anchor

**Comment by sxzz** [comment]
Duplicate of #1149
