### ISSUE TITLE
[Bug Report] el-table 存在固定列时，鼠标移动表格行不变色，没有hover状态了

### ISSUE THREAD

**Issue by wtq1996503** [element-plus/element-plus#5628]
### Element Plus version
1.3.0-beta.8

### OS/Browsers version
谷歌 97

### Vue version
3.2.29

### Reproduction Link
https://github.com/element-plus/element-plus/edit/dev/docs/examples/table/fixed-header-with-fluid-header.vue

### Steps to reproduce
el-table 存在固定列时，鼠标悬浮移动，无法触发表格行变色，没有hover状态了
检查发现配置 fixed属性就会触发

### What is Expected?
el-table 存在固定列时，鼠标悬浮移动，触发表格行变色，存在hover状态

### What is actually happening?
el-table 存在固定列时，鼠标悬浮移动，无法触发表格行变色，没有hover状态了
检查只要发现配置 fixed属性就会触发

**Comment by wtq1996503** [comment]
一直回滚到 "element-plus": "^1.2.0-beta.6",此问题消失

**Comment by emojiiii** [comment]
Duplicate of #5623
