### ISSUE TITLE
[Bug Report] `ElMessage` 样式错误

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5632]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
win11/谷歌

### Vue version
3.2.29

### Reproduction Link
https://github.com/mxp131011/test

### Steps to reproduce
本示例是角标有问题，正式项目是关闭按钮样式有问题

[示例项目](https://github.com/mxp131011/test)    角标背景不显示
![q](https://user-images.githubusercontent.com/31055355/150994100-99e585bb-92e2-46ef-9b50-2c9ebcc75848.jpg)

[正式项目](https://mxp131011.com/zlt9_erp/ls/order/lskd)   关闭图标错位
![b](https://user-images.githubusercontent.com/31055355/150994121-0625d9ea-41cf-4688-9145-fdeef8389103.jpg)

### What is Expected?
样式正常

### What is actually happening?
样式不正常

**Comment by mxp131011** [comment]
https://github.com/element-plus/element-plus/issues/5527  也有此问题

**Comment by mxp131011** [comment]
@emojiiii 我找到原因了，但是我不知道这是不是一个错误
跟`unplugin-element-plus/vite`  的 `useSource`配置有关，但是它配置示例弄反了，或者是一个bug
``` js

// 正确示例1
import ElementPlusPlugin from 'unplugin-element-plus/vite';
ElementPlusPlugin() // 或者 ElementPlusPlugin({ useSource: false })
import { ElMessage } from 'element-plus';
import 'element-plus/es/components/message/style/index'; // 这里应该是导入index

// 正确示例2
import ElementPlusPlugin from 'unplugin-element-plus/vite';
ElementPlusPlugin({ useSource: true })  
import { ElMessage } from 'element-plus';
import 'element-plus/es/components/message/style/css'; //  // 这里应该是导入css

```

如果是向上面这样导入就是正确的，下面图片这样导入就会有部分样式不能成功导入

![image](https://user-images.githubusercontent.com/31055355/151275964-7505eb58-4d71-448b-a6b0-5fee7dd42182.png)

**Comment by emojiiii** [comment]
收到，感谢你的排查。

**Comment by sxzz** [comment]
Duplicate of #5165

**Comment by zhangchenna** [comment]
unplugin-auto-import

**Comment by zhangchenna** [comment]
@[sxzz](https://github.com/sxzz) unplugin-auto-import 还是有这个问题

**Comment by huzedong2015** [comment]
@sxzz 样式丢失

**Comment by sxzz** [comment]
请到此 issue #5165 下讨论，此贴锁定。
Please comment on issue #5165, this issue will be locked.
