### ISSUE TITLE
[Bug Report] 折叠菜单垂直方向，使用icon和文字长度不一样时，无法左对齐

### ISSUE THREAD

**Issue by sea-caterpillar** [element-plus/element-plus#5642]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
Chrome 97.0.4692.99

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/mifan/pen/ExbxOYw

### Steps to reproduce
el-menu-item 中同时使用icon、不一样长度的文字

### What is Expected?
左对齐

### What is actually happening?
位置异常
<img width="364" alt="企业微信截图_16431649405660" src="https://user-images.githubusercontent.com/25836014/151095192-ac04b17b-d326-4a13-81a3-2dd9198bf320.png">

**Comment by guixr** [comment]
[https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuLy8gc2V0dXAgZm9yIGVsZW1lbnQgcGx1cywgZG9uJ3QgcmVtb3ZlLlxuc2V0dXBFbGVtZW50UGx1cygpXG5cbmNvbnN0IGFzaWRlTWVudXMgPSBbe1xuICB0aXRsZTogJ+esrOS4gOe7hCcsXG4gIGNoaWxkOiBbXG4gICAge1xuICAgICAgdGl0bGU6ICfov5nmmK/nrKzkuIDkuKrkvY3nva4nLFxuICAgIH0sXG4gICAgIHtcbiAgICAgIHRpdGxlOiAn5L2N572uMicsXG4gICAgfVxuICBdLFxufV07XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtbWVudVxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjAwcHhcIlxuICAgID5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCIoYXNpZGVJdGVtLCBpbmRleCkgaW4gYXNpZGVNZW51c1wiIDprZXk9XCJpbmRleFwiPlxuICAgICAgICA8ZWwtc3ViLW1lbnUgOmluZGV4PVwiYXNpZGVJdGVtLnRpdGxlXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgICAgIDxlbC1pY29uPlxuICAgICAgICAgICAgICA8VXNlciAvPlxuICAgICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgICAgPHNwYW4+e3thc2lkZUl0ZW0udGl0bGV9fTwvc3Bhbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDx0ZW1wbGF0ZSB2LWZvcj1cIihhc2lkZVN1Ykl0ZW0sIGFzaWRlU3ViSW5kZXgpIGluIGFzaWRlSXRlbS5jaGlsZFwiIDprZXk9XCJhc2lkZVN1YkluZGV4XCI+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cImFzaWRlU3ViSXRlbS5pbmRleFwiPlxuICAgICAgICAgICAgICA8ZWwtaWNvbj5cbiAgICAgICAgICAgICAgICA8VXNlciAvPlxuICAgICAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+e3thc2lkZVN1Ykl0ZW0udGl0bGV9fTwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=](playground)

**Comment by chenguzhen87** [comment]
目测，这是空间不够，因该可以自己写代码解决的

**Comment by guixr** [comment]
> 目测，这是空间不够，因该可以自己写代码解决的
增加宽度是可以解决，但如果去掉icon，空间不够情况下，如图：
<img width="360" alt="企业微信截图_16431682832844" src="https://user-images.githubusercontent.com/25836014/151100056-b1a5591b-1a66-45b5-a5ab-8979d9578d42.png">

**Comment by guixr** [comment]
> 可以

**Comment by guixr** [comment]
> 目测，这是空间不够，因该可以自己写代码解决的
