### ISSUE TITLE
[Bug Report] 同时存在v-loading与@click, 即使在v-loading=true时, click依然会被触发

### ISSUE THREAD

**Issue by cn-troy** [element-plus/element-plus#5646]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
Edge

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/cn-troy/pen/ExbxrXg

### Steps to reproduce
v-loading设置为true, click事件依然可以触发

### What is Expected?
v-loading设置为true, click事件依然可以触发

### What is actually happening?
loading锁定时, click事件应该无效..

**Comment by MrFu1998** [comment]
`button` 是不建议使用 `v-loading`, 提供了内置的 `loading` 属性
`<el-button :loading="true">click</el-button>`

**Comment by cn-troy** [comment]
> `button` 是不建议使用 `v-loading`, 提供了内置的 `loading` 属性 `<el-button :loading="true">click</el-button>`

div一样的.只要支持@click就会出现哟..

**Comment by msidolphin** [comment]
We should add pointer-events: none and touch-events

**Comment by sxzz** [comment]
Can't reproduce the first example. `<div v-loading="true">` works. Please check it.

**Comment by cn-troy** [comment]
我认为仅靠 #5822 控制css无法修复该缺陷，我想在el-loading-mask元素上加入阻止冒泡的click事件，应该能够解决。
@sxzz 你觉得我的想法可行吗？或者我提交一个PR。

**Comment by jlputter** [comment]
Hello, is this resolved?
