### ISSUE TITLE
[Bug Report] [select-v2] 远程搜索，当v-model有默认值各种异常

### ISSUE THREAD

**Issue by 838239178** [element-plus/element-plus#5654]
### Element Plus version
1.3.0-beta.1, 1.3.0-beta.9

### OS/Browsers version
chrome

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-5i4y4?file=/src/App.vue

### Steps to reproduce
https://codesandbox.io/s/element-plus-spa-forked-5i4y4?file=/src/App.vue

### What is Expected?
修BUG

### What is actually happening?
1. 搜索框内不显示初始值的名称而是 `[Object object]`

2. 搜索并选择值后报错：

```
TypeError
Cannot read properties of undefined (reading 'toString')
```

**Comment by 838239178** [comment]
1.1.0 不会报异常

**Comment by 838239178** [comment]
```
runtime-core.esm-bundler.js:6800 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at update (useSelect.ts:238:32)
    at onSelect (useSelect.ts:327:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6746:21)
    at emit$1 (runtime-core.esm-bundler.js:289:9)
    at runtime-core.esm-bundler.js:6522:53
    at Proxy.selectOptionClick (useOption.ts:10:9)
    at option-item.vue?vue&type=template&id=119b30a9&lang.js:3:6
    at runtime-dom.esm-bundler.js:1457:16
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737:22)
```

**Comment by emojiiii** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbi8vIHNldHVwIGZvciBlbGVtZW50IHBsdXMsIGRvbid0IHJlbW92ZS5cbnNldHVwRWxlbWVudFBsdXMoKVxuXG5jb25zdCB2YWx1ZSA9IHJlZih7IGlkOiAxLCBuYW1lOiBcIjEyM1wiIH0pO1xuIGNvbnN0IGRhdGEgPSByZWYoW10pO1xuIGNvbnN0IG9wdGlvbnMgPSBjb21wdXRlZCgoKSA9PiB7XG4gICByZXR1cm4gZGF0YS52YWx1ZS5tYXAoKGkpID0+IHtcbiAgICAgcmV0dXJuIHtcbiAgICAgICBsYWJlbDogaS5uYW1lLFxuICAgICAgIHZhbHVlOiBpLFxuICAgICB9O1xuICAgfSk7XG4gfSk7XG5jb25zdCBzZWFyY2ggPSAoa3cpID0+IHtcbiAgZGF0YS52YWx1ZS5wdXNoKHsgaWQ6IDEsIG5hbWU6IFwiMTIzXCIgfSwgeyBpZDogMiwgbmFtZTogXCI1MzRcIiB9KTtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIHZhbHVlLWtleT1cImlkXCJcbiAgICAgIGZpbHRlcmFibGVcbiAgICAgIHJlbW90ZVxuICAgICAgOnJlbW90ZS1tZXRob2Q9XCJzZWFyY2hcIlxuICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwi6L6T5YWl5YWz6ZSu5a2X5pCc57SiXCJcbiAgICA+PC9lbC1zZWxlY3QtdjI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

**Comment by msidolphin** [comment]
@Alanscut cc

**Comment by 838239178** [comment]
```ts
//useSelect.ts
const currentPlaceholder = computed(() => {
    const _placeholder = props.placeholder || t('el.select.placeholder')
    return props.multiple ? _placeholder : states.selectedLabel || _placeholder
})
```
调试发现执行这个这个方法的时候 props 是 undifined

**Comment by 838239178** [comment]
一个月了还没有修复
