### ISSUE TITLE
[Bug Report] The el-step component does not work with icons

### ISSUE THREAD

**Issue by zwOk9** [element-plus/element-plus#5659]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
linux / chrom 97.0.4692.99

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/el-step-element-plus-lqfy4

### Steps to reproduce
add the prop :icon to the el-step (in the el-steps) with the icon import from element-plus/icons-vue then add the import icon to the prop

codesandbox: reload the page if it displays "cannot use".

### What is Expected?
that icons are displayed instead of numbers 

### What is actually happening?
the icons are never displayed, we have the places of the numbers of the steps that are displayed

**Comment by cn-troy** [comment]
try this code
![image](https://user-images.githubusercontent.com/4318293/151280230-1c25b083-e39d-40e3-8181-1ca9e01f6e10.png)

**Comment by zwOk9** [comment]
thank @cn-troy it works
