### ISSUE TITLE
[Feature Request] el-date-picker 如何设置每周的第一天？

### ISSUE THREAD

**Issue by wzx-3015** [element-plus/element-plus#5665]
### Existing Component
Yes

### Component Name
datePicker

### Description
![image](https://user-images.githubusercontent.com/29293904/151276413-07824963-45a4-4afa-9970-13a29b2d5266.png)

**Comment by wzc-ST** [comment]
请问如何通过国际化来配置日期选择和日历控件每周的一天

**Comment by wzx-3015** [comment]
> 如何通过来配置日期选择和日历控件要求国际化每周的一天
设置 dayjs的语言就可以了

**Comment by wzc-ST** [comment]
已解决：
import dayjs from 'dayjs'
import 'dayjs/locale/zh-cn'
dayjs.locale('zh-cn')
