### ISSUE TITLE
[Bug Report] In manually import, ".el-icon" & ".el-input__icon" style error

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#5667]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
MacOS 11.6.2 / Chome 96.0.4664.55

### Vue version
3.2.29

### Reproduction Link
https://github.com/TothingWay/test-ep

### Steps to reproduce
1. use unplugin-element-plus import element-plus components
2. Add "show-password"  to el-Input component
3. You can see the eye icon style error
4. I found that is .el-icon style overrides the .el-input__icon style

### What is Expected?
The eye icon style is displayed correctly

### What is actually happening?
The eye icon style display error

**Comment by cn-troy** [comment]
按需引入的ElInput
.el-input__icon样式被.el-icon覆盖导致高度为1em，不太理解这个css优先级，我改不了😢。 @emojiiii 
![image](https://user-images.githubusercontent.com/4318293/151484786-b4ce1db4-9729-4413-bcc4-bc132c55786a.png)

![image](https://user-images.githubusercontent.com/4318293/151484759-c3139a8e-533a-4730-8ddd-915385c58a18.png)

**Comment by emojiiii** [comment]
好的，我看看

**Comment by yudan215** [comment]
![image](https://user-images.githubusercontent.com/26323005/151684294-2c12a162-bc3e-483c-8463-47b027217922.png)
使用suffix同样有此问题

**Comment by momtboy** [comment]
![image](https://user-images.githubusercontent.com/9612078/152907089-c75080ad-2c92-41e3-9753-e5e18008446b.png)
使用ElNotification 组件出现同样的问题，样式被覆盖

**Comment by zhangchenna** [comment]
el-icon引起的 已经至少2 3周了

**Comment by TothingWay** [comment]
@JeremyWuuuuu

**Comment by emojiiii** [comment]
很抱歉，最近在忙着写正式版的文档。会尽快修复的~

**Comment by emojiiii** [comment]
这似乎是按需导入时组件的顺序影响了组件的样式权重

**Comment by yudan215** [comment]
> 这似乎是按需导入时组件的顺序影响了组件的样式权重

好像是·这2天不知道改了啥·又可以了

**Comment by emojiiii** [comment]
> 好像是·这2天不知道改了啥·又可以了

**Comment by emojiiii** [comment]
> 啥时候修复啊。el-icons样式层级太高了，急急急！！！

如果真的很急，你可以先去掉插件引入，先手动引入解决这个问题。这主要是组件引入顺序导致的问题，你只要先把 `el-icon`这个组件先引入了，其他组件后引入就不会有这样的问题了

**Comment by emojiiii** [comment]
> > 
> 
> 请问你说的去掉插件引入，手动引入是指怎么操作？去掉vite的unplugin-auto-import/vite和unplugin-vue-components/vite这两个插件吗改用unplugin-element-plus这个插件吗

所有插件都不适用。手动引入组件注册，自行引入样式就好

**Comment by xjphhh** [comment]
> > > 
> > 
> > 
> > 请问你说的去掉插件引入，手动引入是指怎么操作？去掉vite的unplugin-auto-import/vite和unplugin-vue-components/vite这两个插件吗改用unplugin-element-plus这个插件吗
> 
> 所有插件都不使用。手动引入组件注册，自行引入样式就好

unplugin-vue-components/vite这个插件还是挺方便的，我还是想留着自动引入vue组件，是不是只要我不用ElementPlusResolver这个方法就行了，这样就不会自动导入ui组件了，我手动导入ui组件

**Comment by emojiiii** [comment]
> unplugin-vue-components/vite这个插件还是挺方便的，我还是想留着自动引入vue组件，是不是只要我不用ElementPlusResolver这个方法就行了，这样就不会自动导入ui组件了，我手动导入ui组件

是的
