### ISSUE TITLE
[Feature Request] 希望表格组件,加入跟随页面固定表头随页面滚动的表头

### ISSUE THREAD

**Issue by happyluzheng** [element-plus/element-plus#5683]
### Existing Component
Yes

### Component Name
table

### Description
希望表格组件,加入跟随页面固定表头随页面滚动的表头

![image](https://user-images.githubusercontent.com/67585425/151491264-7a532135-2a70-4cca-93e9-d19986830c39.png)

**Comment by emojiiii** [comment]
i'm sorry that i don't understand what your mean. Could you describe it in more detail?
