### ISSUE TITLE
[Bug Report] qq浏览器对应报错，无法打开页面，删除element-plus引入后页面内容展示

### ISSUE THREAD

**Issue by SuSuy** [element-plus/element-plus#5685]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
操作系统：win10；浏览器版本：qq浏览器10.8.4

### Vue version
3.2.25

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
应该vite安装，同时引入element-plus，在qq浏览器最新版本（10.8.4）下页面不展示无响应，且控制台报错。

### What is Expected?
报错：Uncaught TypeError: Cannot read property '__vueuse_ssr_handlers__' of undefined
导致错误的文件地址：node_modules/element-plus/node_modules/@vueuse/core/index.mjs
导致结果：无法使用

### What is actually happening?
页面无法展示
注：Reproduction Link 中地址随意复制，因为必填所以复制了当前地址

**Comment by sxzz** [comment]
Fixed via #5698
