### ISSUE TITLE
[Bug Report] el-table 点击Cell 渲染 input-number 提示Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by Iamdyy** [element-plus/element-plus#5691]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
Mac 12.1

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/priceless-brattain-e127k?file=/src/App.vue

### Steps to reproduce
点击input 列正常
点击number 列 渲染input-number 异常 

### What is Expected?
有更好的解决方法吗？

### What is actually happening?
点击number 列
第一行正常，在第二行异常
控制台提示TypeError: Cannot read properties of null (reading 'setAttribute')

**Comment by dingyuanjie** [comment]
这个地方卸载组件时候报错了，可以临时使用v-show。

**Comment by Iamdyy** [comment]
> 这个地方卸载组件时候报错了，可以临时使用v-show。

好的谢谢，只能先暂时用v-show

**Comment by dingyuanjie** [comment]
link#5695
