### ISSUE TITLE
Tabs: @tab-click事件传递的参数是一个Proxy，不能直接拿到tab实例

### ISSUE THREAD

**Issue by xlzy520** [element-plus/element-plus#570]
![image](https://user-images.githubusercontent.com/28336270/98661356-504e6380-2381-11eb-9d7c-6f6c2985010a.png)

**Comment by xlzy520** [comment]
看了下源码，`evt.props.name`必须要这样取值吗

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/98662140-4f6a0180-2382-11eb-810e-ebc7ff1256bc.png)

**Comment by JeremyWuuuuu** [comment]
Indeed, interested in making a PR?

**Comment by JeremyWuuuuu** [comment]
cc @bastarder

**Comment by bastarder** [comment]
i dont think it necessary, because if you emit 'tab.props', the more information such as `active, index` will be lost.

**Comment by xlzy520** [comment]
@bastarder 是的，是我想的太简单了，感觉需要在文档那边说明一下

**Comment by JeremyWuuuuu** [comment]
@xlzy520  Are you interested in making a PR for the documentation?

**Comment by xlzy520** [comment]
@JeremyWuuuuu OK

**Comment by JeremyWuuuuu** [comment]
Can we close this issue now?
