### ISSUE TITLE
按需引入无法正常执行

### ISSUE THREAD

**Issue by xlzy520** [element-plus/element-plus#571]
报如下错误
![image](https://user-images.githubusercontent.com/28336270/98662757-36ae1b80-2383-11eb-8448-5ff65b65ffc0.png)

**Comment by xlzy520** [comment]
OS: Mac,
Node:  10.19.0
npm: 6.13.4

    "babel-plugin-component": "^1.1.1",

**Comment by JeremyWuuuuu** [comment]
There are still some parts of code needed to be fixed, we will take a look at this issue, could you provide detailed code for us? A link or repo would be very much appreciated.

**Comment by xlzy520** [comment]
@JeremyWuuuuu https://github.com/xlzy520/hello-vue3

**Comment by zazzaz** [comment]
Thanks, we will fix this bug in the next few days in #630

**Comment by JeremyWuuuuu** [comment]
This should be fixed in `alpha-18` you might try it out.

**Comment by zazzaz** [comment]
this has been fixed in `1.0.1-alpha.20 `

Note, we have change the name with an `el-` prefix for each component.

The code should be written as blew:
```
import { ElOption, ElTable } from 'element-plus'
```

**Comment by wangfpp** [comment]
官网给的教程 babel-plugin-import 没有效果呀
