### ISSUE TITLE
[Bug Report] el-dropdown disabled 无效

### ISSUE THREAD

**Issue by Liusiyuan-git** [element-plus/element-plus#5772]
### Element Plus version
1.3.0-beta.10

### OS/Browsers version
win10

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/frosty-water-b1y6h?file=/src/App.vue

### Steps to reproduce
打开连接就重现了，直接看就行

### What is Expected?
根据文档Dropdown Attributes，el-dropdown 加上了disabled="true"之后，下拉框应该不重现才对啊？

### What is actually happening?
el-dropdown 加上了disabled="true"之后，下拉框应该不重现

**Comment by emojiiii** [comment]
Duplicate of #4319
