### ISSUE TITLE
[Bug Report] Error: Can't import the named export '******' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Anastasia226** [element-plus/element-plus#5777]
### Element Plus version
1.3.0-beta.6

### OS/Browsers version
Linux/ Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### Vue version
3.2.29

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/4/ава

### Steps to reproduce
Im use vue3/typescript and plugin element-plus, after update element-plus I got a error Can't import the named export '******' from non EcmaScript module (only default export is available) when run storybook/
My configiration storybook/main.js
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
stories: ['../src//*.stories.mdx', '../src//*.stories.@(js|jsx|ts|tsx)'],

addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-knobs'],

babel: async (options) => ({
    ...options,
    targets: {
        chrome: '81',
        firefox: '53',
    },
}),
webpackFinal: async (config) => {   
    (function handleScss() {
        config.module.rules.push({
            test: /\.scss$/,
            use: [
                'style-loader',
                'css-loader',
                {
                    loader: 'sass-loader',
                    options: {
                        prependData: `

                  @import 'src/assets/scss/vars/style/colors.scss';
                  @import 'src/assets/scss/vars/style/shadows.scss';
                  @import 'src/assets/scss/vars/style/spacing.scss';
                  @import 'src/assets/scss/vars/style/typography.scss';
                  @import 'src/assets/scss/mixins';
                  @import 'src/assets/scss/default-override.scss';

                  `,
                    },
                },
            ],
            include: path.resolve(__dirname, '../'),
        });
    })();  
    
    config.resolve.plugins = config.resolve.plugins || [];
    config.resolve.plugins.push(new TsconfigPathsPlugin({}));
    return config;
},
};
Before add this -->
config.module.rules.push({
test: /.mjs$/,
include: /node_modules/,
type: "javascript/auto",
loader: 'ts-loader',
options: { appendTsSuffixTo: [/.vue$/] },

        });
in file storybook/main.js storybook is going, but components from element-plus dont import/ Please help me.

### What is Expected?
components import in storybook. 

### What is actually happening?
components not import in storybook

**Comment by sxzz** [comment]
Please refer to https://github.com/element-plus/element-plus/discussions/5658 - Dev Environment

**Comment by sxzz** [comment]
Duplicated of #3923
