### ISSUE TITLE
[Bug Report] Plain button with type has hard-coded color value

### ISSUE THREAD

**Issue by Giwayume** [element-plus/element-plus#5785]
### Element Plus version
1.3.0-beta.10

### OS/Browsers version
All

### Vue version
3.2.29

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/mixins/_button.scss#L7

### Steps to reproduce
Build the SCSS.

### What is Expected?
https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/mixins/_button.scss#L7

These lines should be CSS variables like everything else.

```
--el-button-bg-color: #{map.get($colors, $type, 'light-9')};
--el-button-border-color: #{map.get($colors, $type, 'light-6')};
```

### What is actually happening?
The SCSS file generates hard-coded background/border colors for primary/plain buttons.

**Comment by YunYouJun** [comment]
I think this issue has been resolved in the new version.
