### ISSUE TITLE
[Feature Request] icon组件怎么用

### ISSUE THREAD

**Issue by phpjishu** [element-plus/element-plus#5786]
### Existing Component
Yes

### Component Name
icon

### Description
我想循环生成icon列表，新版的icon怎么做呢？

**Comment by XBYundefined** [comment]
图标组件设计的有点稀烂，既然设计了图标组件，文档里面只说需要全局注册，又不说怎么样注册

**Comment by XBYundefined** [comment]
如果你需要使用图标组件
1.下载 npm install @element-plus/icons-vue
2. 在你的组件中引入你需要使用的的图标组件   import { Avatar } from '@element-plus/icons-vue'
3.     <el-icon size="20px" color="red">
           <Avatar></Avatar>
        </el-icon>
3.1 el-icon 应该是一个全局组件，用来控制图标组件的大小样式
如果你需要把图标组件放在 input 框里面，你同样需要引入图标组件，然后作为属性传递给 el-input组件
<el-input :prefix-icon="Avatar"></el-input>
4. 如果你不想每次使用一个图标组件就引入，你可以把所有图标组件注册成全局组件
4.1 main.js中引入图标组件并注册
import * as ElIcons from '@element-plus/icons-vue'
// 注册图标组件
for (let iconName in ElIcons) {
  app.component(iconName, ElIcons[iconName])
}
现在你可以在任何地方使用图标组件
<el-icon><basketball /></el-icon>

**Comment by XBYundefined** [comment]
当然，如果你想在 el-input 组件中使用图标组件，你也可以使用插槽的方式
      <el-input >
        <template  #prefix>
          <el-icon class="el-input__icon"><Avatar /></el-icon>
        </template>
      </el-input>

- el-input__icon 这个内置的类名需要加上

**Comment by crx9** [comment]
> 当然，如果你想在 el-input 组件中使用图标组件，你也可以使用插槽的方式
> 
> ```
>       <el-input >
>         <template  #prefix>
>           <el-icon class="el-input__icon"><Avatar /></el-icon>
>         </template>
>       </el-input>
> ```
> 
> * el-input__icon 这个内置的类名需要加上，不然你的svg无法对齐

感谢老哥 我之前对齐全是自己写的class 😂

**Comment by zhangchenna** [comment]
el-icon 使用后 ElNotification 样式就没了 vite 自动引入

**Comment by XBYundefined** [comment]
> el-icon 使用后 ElNotification 样式就没了 vite 自动引入

希望可以看下代码
