### ISSUE TITLE
[Feature Request] Allow slot for table footer (summary)

### ISSUE THREAD

**Issue by DDEle** [element-plus/element-plus#5794]
### Existing Component
Yes

### Component Name
Table

### Description
I am trying to use table to view and edit database tables. It would look nice if I can use the table footer for row insertion.

**Comment by msidolphin** [comment]
This [demo](https://element-plus.org/en-US/component/table.html#fluid-height-table-with-fixed-header-and-columns) can implement your requirements?

**Comment by DDEle** [comment]
> This [demo](https://element-plus.org/en-US/component/table.html#fluid-height-table-with-fixed-header-and-columns) can implement your requirements?

Actually, I do use customized table headers for my purpose for now, while I still think that using footers would make things look better.

**Comment by msidolphin** [comment]
> > This [demo](https://element-plus.org/en-US/component/table.html#fluid-height-table-with-fixed-header-and-columns) can implement your requirements?
> 
> Actually, I do use customized table headers for my purpose for now, while I still think that using footers would make things look better.

![image](https://user-images.githubusercontent.com/26672484/152751914-33bcb693-3d87-4f11-8400-6f7b35a6c0ef.png)
But the demo is also implemented in the footer, I'm not sure what the difference is between the footer you describe and the demo

**Comment by DDEle** [comment]
> > > This [demo](https://element-plus.org/en-US/component/table.html#fluid-height-table-with-fixed-header-and-columns) can implement your requirements?
> > 
> > 
> > Actually, I do use customized table headers for my purpose for now, while I still think that using footers would make things look better.
> 
> ![image](https://user-images.githubusercontent.com/26672484/152751914-33bcb693-3d87-4f11-8400-6f7b35a6c0ef.png) But the demo is also implemented in the footer, I'm not understand what the difference is between the footer you describe and the demo

Ha, I see your point. I didn't consider the button blow before. The difference is that the "footer" added in this way won't scroll horizontally with the table body and header.

**Comment by msidolphin** [comment]
> Ha, I see your point. I didn't consider the button blow before. The difference is that the "footer" added in this way won't scroll horizontally with the table body and header.

You can try `append` slot

**Comment by DDEle** [comment]
> > Ha, I see your point. I didn't consider the button blow before. The difference is that the "footer" added in this way won't scroll horizontally with the table body and header.
> 
> You can try `append` slot

`Append` slot won't float (i.e. is only visible if users scroll to the bottom)

**Comment by msidolphin** [comment]
> > > Ha, I see your point. I didn't consider the button blow before. The difference is that the "footer" added in this way won't scroll horizontally with the table body and header.
> > 
> > 
> > You can try `append` slot
> 
> `Append` slot won't float (i.e. is only visible if users scroll to the bottom)

The footer will not be modified, i think you can try this:

```html
<div style="height:300px;">
  <el-table :data="tableData" style="width: 100%;" height="calc(100% - 32px)">
    <el-table-column prop="date" label="Date" width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </el-table>
  <el-button style="width:100%;" @click="add">add</el-button>
</div>
```

**Comment by DDEle** [comment]
I believe that the above code is similar to the implementation of "Fluid-height Table with the fixed header". As I said, currently I added input boxes to table header cells in my application. It works fine but I'm still sorry to hear that el-table won't have a better way to do this. After all, it don't make much sense that table header can be customized with slots while footer cells can't. 

Anyway, thanks for your suggestions and the work you have done with this brilliant frontend framework.
