### ISSUE TITLE
I18n 默认非中文

### ISSUE THREAD

**Issue by xlzy520** [element-plus/element-plus#580]
使用table组件、分页组件，可以复现

**Comment by zazzaz** [comment]
Hi, The default language of Element Plus is English. 

You can check more detail here. https://github.com/element-plus/element-plus/blob/dev/website/docs/en-US/i18n.md

We will update our website ASAP

**Comment by xlzy520** [comment]
嗯，官方文档上很多东西都太老了，还是沿用element的

**Comment by kooriookami** [comment]
> Hi, The default language of Element Plus is English.
> 
> You can check more detail here. https://github.com/element-plus/element-plus/blob/dev/website/docs/en-US/i18n.md
> 
> We will update our website ASAP

![image](https://user-images.githubusercontent.com/38392315/99207067-f70a8800-27f7-11eb-917f-7d0f13d40286.png)

I can't import this.

**Comment by zazzaz** [comment]
1.0.1-alpha.15 has fixed this bug.
