### ISSUE TITLE
[Bug Report] popover placement初始化后再修改无效

### ISSUE THREAD

**Issue by qeaonet** [element-plus/element-plus#5811]
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
windows/chrome 版本 97.0.4692.99（正式版本） （64 位）

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/wangahui/pen/PoObVWX

### Steps to reproduce
1：给popover组件绑定属性placemnt，默认值bottom
2:点击按钮修改placment为right，
3：鼠标重新放到按钮上，popover弹出，位置placement仍为bottom

### What is Expected?
修改placement后重新显示popover时候位置为新值

### What is actually happening?
2:点击按钮修改placment为right，
3：鼠标重新放到按钮上，popover弹出，位置placement仍为bottom

**Comment by Lupeiwen0** [comment]
这个组件在 2.0 版本中
const COMPONENT_NAME = "Elpopperconfirm"; 
命名和文档是错误的 不知道是特意换了名字 还是写错了，应该是写错了

**Comment by Lupeiwen0** [comment]
unpkg.com/element-plus
这个 已经是 2.0 版本了 
说明 2.0 版本依然存在这个问题
目前看来 2.0 貌似并不稳定。。。

**Comment by msidolphin** [comment]
> unpkg.com/element-plus 这个 已经是 2.0 版本了 说明 2.0 版本依然存在这个问题 目前看来 2.0 貌似并不稳定。。。

问题反馈出来了我们会持续跟进，即使是稳定版也不代表没有bug啊，稳定版说明api不会再发生重大变化

**Comment by qeaonet** [comment]
Popover组件与Tooltip组件均基于Tooltip构建，Tooltip的placement没问题，看来确定是Popover自己的bug。

**Comment by QuXiaoMing** [comment]
> 
已修复
https://github.com/element-plus/element-plus/pull/5835
