### ISSUE TITLE
[Bug Report] popconfirm 导入异常

### ISSUE THREAD

**Issue by songjiachao** [element-plus/element-plus#5812]
### Element Plus version
2.0.0

### OS/Browsers version
chrome

### Vue version
3.2.30

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ouz64?file=/src/App.vue

### Steps to reproduce
选择2.0版本

### What is Expected?
显示正常

### What is actually happening?
Failed to resolve component: el-popconfirm
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
 at <Repl>

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/70792885/152739695-a7573660-b1a3-48b2-a9e0-e3baa720d5c6.png">

**Comment by shuiche-it** [comment]
官网里的案例也是显示异常了

**Comment by huisir001** [comment]
全局导入`import ElementPlus from 'element-plus'`依旧异常，不知为何，必须使用单个导入`import { ElPopconfirm } from 'element-plus'`才有效

**Comment by JeremyWuuuuu** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxlbC1wb3Bjb25maXJtIHRpdGxlPVwiQXJlIHlvdSBzdXJlIHRvIGRlbGV0ZSB0aGlzP1wiPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIFxuICA8L2VsLXBvcGNvbmZpcm0+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==

@huisir001 可以在这里试试，应该没问题了，现在的版本是哪个呢？

**Comment by huisir001** [comment]
> https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnNvbGUubG9nKHZlcnNpb24pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWljb24+PFVzZXIgLz48L2VsLWljb24+XG5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=
> 
> @huisir001 可以在这里试试，应该没问题了，现在的版本是哪个呢？

版本`"element-plus": "^2.0.1",`

然后无论清除缓存、还是重新install、还是更换浏览器都提示导入异常`Failed to resolve component: el-popconfirm`，和2.0.0版时一样，另外我用的pnpm，没有尝试npm。镜像源未更改。

**Comment by huisir001** [comment]
> > https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnNvbGUubG9nKHZlcnNpb24pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWljb24+PFVzZXIgLz48L2VsLWljb24+XG5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=
> > @huisir001 可以在这里试试，应该没问题了，现在的版本是哪个呢？
> 
> 版本`"element-plus": "^2.0.1",`
> 
> 然后无论清除缓存、还是重新install、还是更换浏览器都提示导入异常`Failed to resolve component: el-popconfirm`，和2.0.0版时一样，另外我用的pnpm，没有尝试npm。镜像源未更改。

不知道是不是我的问题  但不知道问题在哪

**Comment by JeremyWuuuuu** [comment]
@huisir001 如果你用的是 Vite，尝试启动的时候用 `$ yarn vite serve --force` 这样来移除掉 Vite 的 cache，或者是通过 `$ rm -rf node_modules/.vite` 来移除 cache 试试。

**Comment by huisir001** [comment]
> rm -rf node_modules/.vite

谢了  删掉 .vite 可以了
麻烦您了

**Comment by JeremyWuuuuu** [comment]
@huisir001 不用客气。。我搞的锅 不好意思 :bow:
