### ISSUE TITLE
[Bug Report] Failed to resolve component: el-popconfirm

### ISSUE THREAD

**Issue by feenn** [element-plus/element-plus#5813]
### Element Plus version
2.0.0

### OS/Browsers version
Chrome 98, Win 10

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/feenn9/fqcrmez3/5/

### Steps to reproduce
Use el-popcomfirm as normal. Then print "[Vue warn]: Failed to resolve component: el-popconfirm" in the console. And no element is rendered on the page.  
No error occurres when using 1.3.0-beta.10. 

### What is Expected?
no errors

### What is actually happening?
no element is rendered and error occurres.

**Comment by shuiche-it** [comment]
我选择了回退版本的操作
