### ISSUE TITLE
Pagination size-change event trigger issue

### ISSUE THREAD

**Issue by saundaryapb** [element-plus/element-plus#582]
it seems like there's an issue in size-change event, whenever I am changing the page size the event is not getting trigged, the other event i.e., current-change is working as it supposed to be. I am using latest vue 3.0 and it's composition api's.
```
<template>
  <div class="main">
    <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page="currentPage"
      :page-sizes="[10, 20, 30, 40, 60, 100]"
      :page-size="10"
      layout="total, sizes, prev, pager, next, jumper"
      :total="pageData.length"
    >
    </el-pagination>
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  name: "PaginationTable",
  props: {
    pageData: {
      type: Array,
    },
    paginationEvent: {
      type: Function,
    },
  },
  setup(props) {
    const currentPage = ref(1);

    const handleSizeChange = (size) => {
      console.log(`current size ${size}`);
    };

    const handleCurrentChange = (current_page) => {
      console.log(`current page: ${current_page}`);
      currentPage.value = current_page;
      props.paginationEvent(current_page);
    };
    return {
      handleSizeChange,
      handleCurrentChange,
      currentPage,
    };
  },
};
</script>

<style scoped>
.main {
  background: white;
  text-align: center;
  padding: 10px;
}
</style>

**Comment by saundaryapb** [comment]
<template>
  <div class="main">
    <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page="currentPage"
      :page-sizes="[10, 20, 30, 40, 60, 100]"
      :page-size="10"
      layout="total, sizes, prev, pager, next, jumper"
      :total="pageData.length"
    >
    </el-pagination>
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  name: "PaginationTable",
  props: {
    pageData: {
      type: Array,
    },
    paginationEvent: {
      type: Function,
    },
  },
  setup(props) {
    const currentPage = ref(1);

    const handleSizeChange = (size) => {
      console.log(`current size ${size}`);
    };

    const handleCurrentChange = (current_page) => {
      console.log(`current page: ${current_page}`);
      currentPage.value = current_page;
      props.paginationEvent(current_page);
    };
    return {
      handleSizeChange,
      handleCurrentChange,
      currentPage,
    };
  },
};
</script>

<style scoped>
.main {
  background: white;
  text-align: center;
  padding: 10px;
}
</style>

**Comment by saundaryapb** [comment]
`<template>
  <div class="main">
    <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page="currentPage"
      :page-sizes="[10, 20, 30, 40, 60, 100]"
      :page-size="10"
      layout="total, sizes, prev, pager, next, jumper"
      :total="pageData.length"
    >
    </el-pagination>
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  name: "PaginationTable",
  props: {
    pageData: {
      type: Array,
    },
    paginationEvent: {
      type: Function,
    },
  },
  setup(props) {
    const currentPage = ref(1);

    const handleSizeChange = (size) => {
      console.log(`current size ${size}`);
    };

    const handleCurrentChange = (current_page) => {
      console.log(`current page: ${current_page}`);
      currentPage.value = current_page;
      props.paginationEvent(current_page);
    };
    return {
      handleSizeChange,
      handleCurrentChange,
      currentPage,
    };
  },
};
</script>

<style scoped>
.main {
  background: white;
  text-align: center;
  padding: 10px;
}
</style>
`

**Comment by saundaryapb** [comment]
```
<template>
  <div class="main">
    <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page="currentPage"
      :page-sizes="[10, 20, 30, 40, 60, 100]"
      :page-size="10"
      layout="total, sizes, prev, pager, next, jumper"
      :total="pageData.length"
    >
    </el-pagination>
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  name: "PaginationTable",
  props: {
    pageData: {
      type: Array,
    },
    paginationEvent: {
      type: Function,
    },
  },
  setup(props) {
    const currentPage = ref(1);

    const handleSizeChange = (size) => {
      console.log(`current size ${size}`);
    };

    const handleCurrentChange = (current_page) => {
      console.log(`current page: ${current_page}`);
      currentPage.value = current_page;
      props.paginationEvent(current_page);
    };
    return {
      handleSizeChange,
      handleCurrentChange,
      currentPage,
    };
  },
};
</script>

<style scoped>
.main {
  background: white;
  text-align: center;
  padding: 10px;
}
</style>

**Comment by JeremyWuuuuu** [comment]
Yes, this is a bug, I believe, I looked through the source code, I did not find any code for emitting this `size-change` event, I will fix it on next release.
