### ISSUE TITLE
[Bug Report] Popconfirm 气泡确认框 全局导入无效

### ISSUE THREAD

**Issue by huisir001** [element-plus/element-plus#5820]
### Element Plus version
2.0.0

### OS/Browsers version
 Chrome 版本 97.0.4692.99（正式版本） （64 位）

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/68ro0aLz/1/

### Steps to reproduce
详见官方文档或例子

### What is Expected?
期待正常导入 正常显示

### What is actually happening?
不能导入

**Comment by msidolphin** [comment]
已修复 https://github.com/element-plus/element-plus/pull/5815
