### ISSUE TITLE
[Feature Request] 增加暗黑模式

### ISSUE THREAD

**Issue by yangxinSamsara** [element-plus/element-plus#5821]
### Existing Component
否

### Component Name
暗黑模式

### Description
目前出现的新的ui库添加了一键切换暗黑模式功能，作为一个重度elementui用户，希望咱们也能增加这个功能

**Comment by hooray** [comment]
官方说预计在 2.1.x 增加

**Comment by emojiiii** [comment]
please see the [discussions](https://github.com/element-plus/element-plus/discussions/3754)
