### ISSUE TITLE
[Feature Request] button的size属性, small大小发生了变化, 而且mini选项无效

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#5823]
### Existing Component
Yes

### Component Name
el-button

### Description
button的size属性, small大小发生了变化, 而且mini选项无效, 在1.0.2-beta.47版本是生效的

**Comment by emojiiii** [comment]
please see the [docs](https://element-plus.gitee.io/zh-CN/component/button.html#button-%E5%B1%9E%E6%80%A7)
because the `mini` option has been removed
