### ISSUE TITLE
Loading以服务方式使用报错

### ISSUE THREAD

**Issue by showyoulove** [element-plus/element-plus#583]
Loading.service(options)

Cannot read property 'service' of undefined

**Comment by showyoulove** [comment]
`import { Loading } from "element-plus"`
console.log(Loading) undefined

**Comment by JeremyWuuuuu** [comment]
I believe this is a bug that we accidentally forgot to export loading as a global member.
cc @zazzaz

**Comment by showyoulove** [comment]
> I believe this is a bug that we accidentally forgot to export loading as a global member.
> cc @zazzaz

什么时候可以修复

**Comment by JeremyWuuuuu** [comment]
It should be no biggy, will fix in the next release (within 1 to 2 days)

**Comment by zazzaz** [comment]
Yes, we missed the service property here

https://github.com/ElemeFE/element/blob/dev/packages/loading/index.js#L10

**Comment by zazzaz** [comment]
We will fix this bug in the next few days in #630

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.18

Now you can use 
```
import { ElLoading } from "element-plus"
```
