### ISSUE TITLE
[Bug Report] test with jest: [Vue warn]: Failed to resolve component: el-button

### ISSUE THREAD

**Issue by harryp-art** [element-plus/element-plus#5830]
### Element Plus version
2.0.1

### OS/Browsers version
12.0.0

### Vue version
3.2.30

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
just create a test of the componenent using el-button or another component from element-plus

### What is Expected?
i need to resolve the warnings

### What is actually happening?
i am getting this warning in all test of my components:

If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by harryp-art** [comment]
@msidolphin how can i solve it ?

**Comment by msidolphin** [comment]
> @msidolphin how can i solve it ?

You need to register ElButton

**Comment by harryp-art** [comment]
@msidolphin can you write an example of solution please

**Comment by msidolphin** [comment]
> @msidolphin can you write an example of solution please

```ts
import { mount } from '@vue/test-utils'

const makeMountFunc = (defaultOptions) => {
  return (template: string, options: Options) => {
    return mount({
      ...merge({}, defaultOptions, options),
      template,
    })
  }
}

const _mount = makeMountFunc({
  components: {
    'el-select': Select,
  },
})

describe('demo', () => {
  it('case', () => {
    const wrapper = _mount(`<el-select>......</el-select>`)
    // ...
  })
})

```

**Comment by harryp-art** [comment]
i am not using directly, el-button is inside of my component Connect

```
import { shallowMount } from '@vue/test-utils'
import { createApp } from 'vue'
import { createStore } from 'vuex'
import App from '@/components/connect'

const store = createStore({
  state() {
    return {
      user: {},
    }
  },
  mutations: {},
})

let wrapper
const app = createApp(App)
app.use(store)

beforeEach(() => {
  wrapper = shallowMount(App, {
    propsData: {},
    global: {
      plugins: [store],
       stubs: {
      'el-button': {
        template: '<i />',
      },
    },
    },
   
  })
})
```

@msidolphin how can i use your code in my example?

**Comment by msidolphin** [comment]
> i am not using directly, el-button is inside of my component Connect
> 
> ```
> import { shallowMount } from '@vue/test-utils'
> import { createApp } from 'vue'
> import { createStore } from 'vuex'
> import App from '@/components/connect'
> 
> const store = createStore({
>   state() {
>     return {
>       user: {},
>     }
>   },
>   mutations: {},
> })
> 
> let wrapper
> const app = createApp(App)
> app.use(store)
> 
> beforeEach(() => {
>   wrapper = shallowMount(App, {
>     propsData: {},
>     global: {
>       plugins: [store],
>        stubs: {
>       'el-button': {
>         template: '<i />',
>       },
>     },
>     },
>    
>   })
> })
> ```
> 
> @msidolphin how can i use your code in my example?

```diff
let wrapper
const app = createApp(App)
+ app.use(ElementPlus)
app.use(store)
```

**Comment by andrei-gheorghiu** [comment]
@msidolphin in your test, `app` and `wrapper` are not connected. 
The only thing they have in common is that both of them are mounting/shallow-mounting the App constructor. But after that you add a plugin to `app` and expect `wrapper` to know about it.
It's like hitting your finger with a hammer but expecting the other hand to hurt.

I've answered your SO question [here](https://stackoverflow.com/a/71029817/1891677) and explained in detail what's going on and what are your options. 
Happy coding!
