### ISSUE TITLE
[Bug Report] select组件远程搜索el-input__inner的高度一直在变化

### ISSUE THREAD

**Issue by sihuanian** [element-plus/element-plus#5837]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
chrome: 97.0.4692.99 | 98.0.4758.82  firefox: 95.0.2 

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/sihuanian/pen/KKyaeQK

### Steps to reproduce
***也可使用官网示例，请使用select组件中的远程搜索https://element-plus.gitee.io/zh-CN/component/select.html#%E7%AD%9B%E9%80%89%E9%80%89%E9%A1%B9，中的示例 在PlayGround 中编辑。***
1. 选择 label:Alabama
2. 选择 label:New Hampshire
3. 删除 label:Alabama

依照上述步骤，el-input__inner的高度将会一直在变化（两个高度之间一直切换）。如果select组件下方有其它html标签，下方的标签将会上下抖动

### What is Expected?
el-input__inner的高度保持不变

### What is actually happening?
el-input__inner的高度将会一直在变化（两个高度之间一直切换）。如果select组件下方有其它html标签，下方的标签将会上下抖动

**Comment by emojiiii** [comment]
可以麻烦你在这里评论增加一个 `playground` 案例复现一下吗？ 我用官网的没有复现出来 @sihuanian

**Comment by sihuanian** [comment]
> 可以麻烦你在这里评论增加一个 `playground` 案例复现一下吗？ 我用官网的没有复现出来 @sihuanian

地址如下，https://codepen.io/sihuanian/pen/KKyaeQK  将官网示例select 组件的远程搜索示例放到了codepen上了

**Comment by sihuanian** [comment]
好像和电脑的一些参数有关，我同事的电脑按照上述步骤没有复现，但是选择其它的有复现。下面是我电脑的录屏，但录制帧率与浏览器刷新次数有差异，请注意看蓝色区域的高度变化 @emojiiii 。由于github不能上传图片，请前往掘金查看 https://juejin.cn/post/7062237575075299341/

**Comment by emojiiii** [comment]
掘金审核看起来还没通过，github 可以发图片的，你直接把你的图片拖入到输入框就可以了

**Comment by sihuanian** [comment]
![bug](https://user-images.githubusercontent.com/40854936/152941191-768a92dc-46c8-4dad-9783-79a797427d1d.gif)

**Comment by lemoe2021** [comment]
https://user-images.githubusercontent.com/79942901/153146688-6a4c94f4-2705-4209-91a4-47fd5a74d815.mov

**Comment by hfutyezi** [comment]
我也遇到了这问题 @emojiiii

**Comment by kooriookami** [comment]
Fixed
