### ISSUE TITLE
[Bug Report] vite始终无法加载成功无法进入也页面

### ISSUE THREAD

**Issue by AlphaYoung111** [element-plus/element-plus#5842]
### Element Plus version
2.0.1

### OS/Browsers version
windows/Chrome

### Vue version
3.2.16

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-h3o68

### Steps to reproduce
1. 使用pnpm 使用插件unplugin-auto-import/vite失败
   - 错误：Failed to write to output file: open xxx\xxx\node_modules\.vite\chunk-JDV3F3V3.js: Access is denied.
   - node_modules/element-plus/lib/locale/lang/zh-cn.js" points to missing source files
2. 点击进入找不到得zh-cn.js文件，可以正常打开，能在node_modules中找到
3. 使用yarn   使用插件unplugin-auto-import/vite失败 情况同上
4. 使用yarn 失败 情况同上

### What is Expected?
vite能够正常访问页面，进如主页面

### What is actually happening?
vite加载node_modules/.vite目录下得预编译文件还是不行，1.0beta得各个版本都行，刚升级2.0稳定版就不行了

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/153133587-b6751a6e-e2f8-4dc5-a93e-22a4d1c6db0d.png)
看着像是没有写入文件的权限？尝试用管理员身份运行看看

**Comment by AlphaYoung111** [comment]
好像是得，为啥会这样，之前1.0beta都不会啊。顺带催更大佬对于各个组件能够自定义颜色变量文档得更新，今天在使用得时候在base.css里找了好久，只能一个个试(●﹏●)

**Comment by emojiiii** [comment]
> 好像是得，为啥会这样，之前1.0beta都不会啊。顺带催更大佬对于各个组件能够自定义颜色变量文档得更新，今天在使用得时候在base.css里找了好久，只能一个个试(●﹏●)

这个工作量有点大，目前还没计划安排上，可能需要多等些时日。。很抱歉

**Comment by sxzz** [comment]
可以尝试删除node_modules重试下。
此帖关闭，有其他问题请重开issue。

**Comment by zybieku** [comment]
> 好像是得，为啥会这样，之前1.0beta都不会啊。顺带催更大佬对于各个组件能够自定义颜色变量文档得更新，今天在使用得时候在base.css里找了好久，只能一个个试(●﹏●)



> ### Element Plus version
> 2.0.1
> 
> ### OS/Browsers version
> windows/Chrome
> 
> ### Vue version
> 3.2.16
> 
> ### Reproduction Link
> https://codesandbox.io/s/element-plus-spa-forked-h3o68
> 
> ### Steps to reproduce
> 1. 使用pnpm 使用插件unplugin-auto-import/vite失败
>    
>    * 错误：Failed to write to output file: open xxx\xxx\node_modules.vite\chunk-JDV3F3V3.js: Access is denied.
>    * node_modules/element-plus/lib/locale/lang/zh-cn.js" points to missing source files
> 2. 点击进入找不到得zh-cn.js文件，可以正常打开，能在node_modules中找到
> 3. 使用yarn   使用插件unplugin-auto-import/vite失败 情况同上
> 4. 使用yarn 失败 情况同上
> 
> ### What is Expected?
> vite能够正常访问页面，进如主页面
> 
> ### What is actually happening?
> vite加载node_modules/.vite目录下得预编译文件还是不行，1.0beta得各个版本都行，刚升级2.0稳定版就不行了

+1 请问老铁怎么解决, 使用管理员启动嘛

**Comment by AlphaYoung111** [comment]
使用管理员启动，多试几次，每次试删除完node_modules最好退出编辑器

**Comment by zybieku** [comment]
![image](https://user-images.githubusercontent.com/15903330/154449445-688f31ac-940c-4b8b-b9e7-dbf25975fda0.png)
我的错误是这个,用户权限本身就是管理员,还有管理员启动嘛, 用管理员模式的powersheell 也是不行

**Comment by CalmHarbin** [comment]
使用管理员安装依赖和启用项目依然有这个问题，vite版本2.8.6，element-plus版本2.1.4

**Comment by feifanshijie** [comment]
我也遇到了
error: Failed to write to output file: open G:\workspace\success\front_manage\node_modules\.vite\vue.js.map: Access is denied

**Comment by CalmHarbin** [comment]
> 使用管理员安装依赖和启用项目依然有这个问题，vite版本2.8.6，element-plus版本2.1.4

我将nodejs版本由14.17.0升级都16.14.2，成功的解决了这个问题。
可以参考：https://github.com/nuxt/vite/issues/207
