### ISSUE TITLE
在js封装中Message无法正常运行

### ISSUE THREAD

**Issue by lighter217** [element-plus/element-plus#585]
报错：**Object(...) is not a function**

`import { Message } from 'element-plus'`

`export function test(val) {
    Message('val is ' + val)
}`

**Comment by JeremyWuuuuu** [comment]
Please use methods like `import { Message } from 'element-plus/lib/message;` as a workaround for now, we will fix this issue in the upcoming release.

**Comment by lighter217** [comment]
tks

**Comment by JeremyWuuuuu** [comment]
Sorry, the current exported `Message` is actually an installer, so you cannot call it directly to get it work as expected, you need to change the import path in order to get it work like this:
```ts
import { Message } from 'element-plus/lib/message';
```
