### ISSUE TITLE
[Feature Request] table设置最大高度时不能使用vh

### ISSUE THREAD

**Issue by dxy2233** [element-plus/element-plus#5850]
### Existing Component
Yes

### Component Name
table

### Description
table组件设置max-height属性时使用vh为单位无法滚动，必须用px才正常，是否可以适配下

**Comment by Liusiyuan-git** [comment]
附议

**Comment by Liusiyuan-git** [comment]
而且 max-height 也不能动态计算，例如：calc(100% -40px)

**Comment by emojiiii** [comment]
@msidolphin cc
