### ISSUE TITLE
[Feature Request] clone后build报错

### ISSUE THREAD

**Issue by carveybunt** [element-plus/element-plus#5858]
### Existing Component
No

### Component Name
开发学习

### Description
想通过这个项目学习如何开发拓展包，但是`clone`后`pnpm build`报错。提示：“sh: gulp: command not found”。我已经运行过“pnpm install”并无报错。并且有些文件并不存在，例如：“../packages/element-plus/version.ts”。
![image](https://user-images.githubusercontent.com/37894474/153022668-cddf7fce-b6f4-4cb3-a424-6909a46b62cd.png)

**Comment by btea** [comment]
You should run `pnpm gen:version` before running `pnpm build`.

**Comment by carveybunt** [comment]
> You should run `pnpm gen:version` before running `pnpm build`.

Thanks a lot! When I ran `pnpm gen:version` I got the error: "sh: sucrase-node: command not found",  I already ran `pnpm install`.

**Comment by btea** [comment]
Maybe you can try installing `sucrase` separately?

**Comment by carveybunt** [comment]
> Maybe you can try installing `sucrase` separately?
Thanks again, it's working now.

**Comment by sukney** [comment]
我下载的是dev分支，运行pnpm build 报如下错：
![image](https://user-images.githubusercontent.com/36889438/153221202-9c1226db-a57d-42a7-9110-bf4097bcba61.png)

有大神帮看看

**Comment by btea** [comment]
@sukney https://github.com/element-plus/element-plus/blob/dev/CONTRIBUTING.md
