### ISSUE TITLE
[Bug Report] Table - There is a problem with the style

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#5862]
### Element Plus version
2.0.1

### OS/Browsers version
chrmoe 98.0.4758.80

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/Lu_Xi/0fkw9nm7/10/

### Steps to reproduce
See link for details

Although the sample project does not reflect the problems I want to show, there is a problem of direct style confusion in table column rendering
But I can't find out why such a problem occurs in the demonstration project

Originally, the problem I encountered was that the second and third level headers failed to align with the

### What is Expected?
fix Table Style

### What is actually happening?
 Table column Style has bug

**Comment by msidolphin** [comment]
Do not use self-closing in html for custom components  https://v2.vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended
