### ISSUE TITLE
[Bug Report] Table - After multi selection is enabled, the multi-level header style will increase the width of a multi selection column

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#5864]
### Element Plus version
2.0.1

### OS/Browsers version
chrmoe 98.0.4758.80

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/Lu_Xi/0fkw9nm7/24/

### Steps to reproduce
See link for details

### What is Expected?
fix this bug

### What is actually happening?
After multi selection is enabled, the multi-level header style will increase the width of a multi selection column

**Comment by SonicMiso** [comment]
The error is due to fixed columns greater than one column, which means that when you use more than one fixed columns in the left end of your table and you happend to use a multi-level header in the same table, than this bug emerge.

**Comment by SonicMiso** [comment]
**Reproduction Link**
https://jsfiddle.net/SonicMiso/dnemajLf/
