### ISSUE TITLE
[Bug Report] select组件, v-model="value"传递对象, 初始化回显不生效

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#5866]
### Element Plus version
2.0.1

### OS/Browsers version
1

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/15218378694/omnz3uca/16/

### Steps to reproduce
打开就看到了

### What is Expected?
希望绑定对象的也可以初始化回显

### What is actually happening?
 v-model绑定字符串的, 初始化回显没问题, 绑定对象的不行

**Comment by wfk007** [comment]
> ### Element Plus version
> 2.0.1
> 
> ### OS/Browsers version
> 1
> 
> ### Vue version
> 3.2.30
> 
> ### Reproduction Link
> https://jsfiddle.net/15218378694/omnz3uca/2/
> 
> ### Steps to reproduce
> 打开就看到了
> 
> ### What is Expected?
> 希望绑定对象的也可以初始化回显
> 
> ### What is actually happening?
> v-model绑定字符串的, 初始化回显没问题, 绑定对象的不行

`value-key="value.value"` 试试

**Comment by a15218378694** [comment]
> `value-key="value.value"` 试试

我更新了一下, 改成了多选, 该怎么写才能回显呢

**Comment by wfk007** [comment]
多选的 value 是个数组
```js
const value = ref([
  {
    value: 'Option1',
  },
])
```

**Comment by a15218378694** [comment]
> 多选的 value 是个数组
> 
> ```js
> const value = ref([
>   {
>     value: 'Option1',
>   },
> ])
> ```

我的例子里面, 就是改成这样的了, 上面v-model="value", 下面的value就是数组

**Comment by btea** [comment]
[这样试试](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZTFcIiBtdWx0aXBsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cblxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgbXVsdGlwbGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgc3R5bGU9XCJtYXJnaW4tbGVmdDogMjBweFwiXG4gICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICA+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICA+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbJ09wdGlvbjEnXSlcbmNvbnN0IHZhbHVlMiA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by a15218378694** [comment]
> [这样试试](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZTFcIiBtdWx0aXBsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cblxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgbXVsdGlwbGVcbiAgICBjb2xsYXBzZS10YWdzXG4gICAgc3R5bGU9XCJtYXJnaW4tbGVmdDogMjBweFwiXG4gICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICA+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICA+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbJ09wdGlvbjEnXSlcbmNvbnN0IHZhbHVlMiA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

感谢~
