### ISSUE TITLE
[Bug Report] dialog not fill full screen after drag

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#5870]
### Element Plus version
2.0.1

### OS/Browsers version
chrome

### Vue version
3.2.30

### Reproduction Link
https://codepen.com/see_below

### Steps to reproduce
1. open dialog
2. drag dialog
3. fullscreen dialog

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5DbGljayB0byBvcGVuIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgdGl0bGU9XCJUaXBzXCIgd2lkdGg9XCIzMCVcIiBkcmFnZ2FibGUgOmZ1bGxzY3JlZW49XCJmdWxsc2NyZWVuXCI+XG4gICAgPHNwYW4+SXQncyBhIGRyYWdnYWJsZSBEaWFsb2c8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImZ1bGxzY3JlZW4gPSAhZnVsbHNjcmVlblwiXG4gICAgICAgICAgPkZ1bGxzY3JlZW48L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGZ1bGxzY3JlZW4gPSByZWYoZmFsc2UpXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9

### What is Expected?
fill the window

### What is actually happening?
has some offset caused by dragging

**Comment by lemoe2021** [comment]
https://user-images.githubusercontent.com/79942901/153130703-9cf10621-b624-4092-ae9f-626010e2aa43.mov

**Comment by buqiyuan** [comment]
I can't reproduce the problem in my local environment, Can you provide a mini repo ?

![QQ录屏20220209145152](https://user-images.githubusercontent.com/39730999/153138413-f4924637-f345-42a9-a443-bd43293056aa.gif)

**Comment by buqiyuan** [comment]
Fixed, please wait for the new version to be released
