### ISSUE TITLE
[Bug Report]  图片预览大图遮罩层和表格的border css层级冲突

### ISSUE THREAD

**Issue by ZickCode** [element-plus/element-plus#5879]
### Element Plus version
2.0.1

### OS/Browsers version
Windows 10 / Chrome 98.0.4758.82（正式版本） （64 位）

### Vue version
3.2.27

### Reproduction Link
https://codepen.io/zickCode/pen/WNXpXPo

### Steps to reproduce
1.table组件中，引入image组件 ，配置查看大图属性preview-src-list。
2.点击图片，弹窗的遮罩层未能完全挡住table组件的边框样式

### What is Expected?
遮罩层应该层级更高

### What is actually happening?
样式冲突

**Comment by lemoe2021** [comment]
append-to-body 设为 true 就好了吧

https://element-plus.org/en-US/component/image.html#imageviewer-attributes

**Comment by ZickCode** [comment]
![image](https://user-images.githubusercontent.com/12151292/153144618-c9d7e1c2-ebe9-4f19-afeb-1037e20139c9.png)

**Comment by msidolphin** [comment]
> append-to-body 设为 true 就好了吧
> 
> https://element-plus.org/en-US/component/image.html#imageviewer-attributes

我们计划将append-to-body改为preview-append-to-body，计划在后续版本中废弃（下个版本仍然可以使用）
