### ISSUE TITLE
[Feature Suggestion]: `ElTree` suggestion

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#588]
树组件是否可以扩展成支持大数据渲染以及搜索呢

**Comment by Emiya0306** [comment]
+1, lazy render for huge amount of data is a very important feature. I think `Select`, `Transfer`, `Tree`, `Table` should support this mode.

**Comment by xiaoxian521** [comment]
Lazy loading has been supported. What you need is one-time loading

**Comment by Emiya0306** [comment]
Emmm, I mean lazy render, not lazy loading. Like react-virtualized you know. 😸

**Comment by xiaoxian521** [comment]
hh this is a good issues

**Comment by xiaoxian521** [comment]
The rendering performance of vue3.0 plus virtual scrolling is a good component, I believe

**Comment by JeremyWuuuuu** [comment]
We can surely implement windowing to the tree element, but the concern is, is it worth it. how many tree node would you ended up with in the tiny component?

**Comment by JeremyWuuuuu** [comment]
Also, virtualization requires users to pass extra attributes to the component, such as column size, window size, etc. maybe we can make an stand alone virtualized `tree component` instead of making breaking changes to `Tree`.
I'll take a note on this.

**Comment by xiaoxian521** [comment]
This demand is very common, especially for large enterprises such as transportation and environment

**Comment by xiaoxian521** [comment]
It is suggested that v-contextmenu can be combined with tree component as https://github.com/heynext/v-contextmenu

**Comment by JeremyWuuuuu** [comment]
Yes, the idea is great, lets keep this tracked after we get our first release, we can start to get our hands on this.

**Comment by JeremyWuuuuu** [comment]
The priority for us right now is to get the code fully tested, documentations updated, then get the first candidate released. I personally strongly agree with the idea of virtualize the tree component.

**Comment by xiaoxian521** [comment]
hh Always support you

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
