### ISSUE TITLE
[Bug Report] 按需引入时类权重会有变化

### ISSUE THREAD

**Issue by jiangmugit** [element-plus/element-plus#5887]
### Element Plus version
2.0.1

### OS/Browsers version
any

### Vue version
3.2.30

### Reproduction Link
https://github.com/jiangmugit/vue3-ts-elementplus

### Steps to reproduce
git地址上有两个分支  一个错误的分支，一个正常的分支，错误的分支多引入了el-select el-tag,结果发现全局的输入框默认图标上移了，引起的原因是el-icon的类权重发生变化高于el-input_icon了，导致height属性由inherit变为1rem了，但是原本的正常分支的icon.css也是有引入的

### What is Expected?
跑起来的项目应该输入框默认图标是正常的

### What is actually happening?
图标上移了

**Comment by sunjianxu** [comment]
有没感觉默认的size 有点大，small 又比之前的mini还小

**Comment by emojiiii** [comment]
Duplicate of #5667
