### ISSUE TITLE
[Bug Report] el-popover 触发方式为 hover ，且进行手动控制显隐时，效果未达到预期

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#5897]
### Element Plus version
2.0.1

### OS/Browsers version
chrome latest

### Vue version
3.2.30

### Reproduction Link
https://jsfiddle.net/rgd5n30m/8/

### Steps to reproduce
在 el-popover 组件上使用 v-model:visible 进行手动控制显隐，并设置 trigger="hover"

### What is Expected?
鼠标hover到按钮时，能显示对应的html元素，移开后隐藏

### What is actually happening?
鼠标hover到按钮时，无法弹出popover界面
参考了 el-tooltip 组件里的用法，在按钮上增加 `@mouseenter="visible = true"` 后可以弹出popover元素，但同样需要给popover元素增加 `@mouseleave="visible = false"` 才能实现移开时隐藏。
这就出现一个问题，如果鼠标hover到按钮后并移开（并没有移动到popover元素上），这时候popover元素是无法自动隐藏的。如果把 `@mouseleave="visible = false"` 放到按钮上，虽然能实现移开隐藏，但从按钮移动到popover元素却会导致popover元素隐藏。
如果同时在按钮和popover元素上都加上 `@mouseenter="visible = true"` 和 `@mouseleave="visible = false"` 虽然能勉强实现效果，但会有明显的显隐闪烁一下，似乎需要通过增加防抖来解决（有点麻烦，并未尝试）。

以上说的问题我测试了多个版本，最终发现在 1.3.0-beta.1 里是没有问题的，可尝试在我提供的复现链接里替换引入的element plus脚本地址为：
https://unpkg.com/element-plus@1.3.0-beta.1/dist/index.full.js
在这个版本下，是不用增加任何代码，并且能达到原本的预期的。

我不清楚这是个bug，还是feature，如果是feature，针对我上面描述的使用场景，是否有更好的实践，因为我以前这样使用是没问题的，更新到正式版后才发现不行了。

**Comment by emojiiii** [comment]
这是个feature, 传入`visible` 后变为受控模式。例子可看[文档](https://element-plus.gitee.io/zh-CN/component/tooltip.html#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F)

**Comment by cn-troy** [comment]
现在的版本Popover已经不再支持trigger为click或hover类型下同时设置v-model:visible="visible",
你的问题与 https://github.com/element-plus/element-plus/issues/5424 相同...
可以使用Popover提供的hide方法 (https://github.com/element-plus/element-plus/issues/5334) 应该可以实现效果.

**Comment by hooray** [comment]
> 

多谢，用Popover提供的hide方法可以满足我的需求

**Comment by 874435441** [comment]
> 现在的版本Popover已经不再支持trigger为click或hover类型下同时设置v-model:visible="visible", 你的问题与 #5424 相同... 可以使用Popover提供的hide方法 (#5334) 应该可以实现效果.

在文档中添加hide方法
