### ISSUE TITLE
[Bug Report] [Select V2]的官方手册“创建临时选项”范例的若干个BUG

### ISSUE THREAD

**Issue by microkof** [element-plus/element-plus#5903]
### Element Plus version
2.0.1

### OS/Browsers version
Window10 / Chrome 86

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/fake/fakefakefakefakefakefakefake

### Steps to reproduce
打开 [https://element-plus.gitee.io/zh-CN/component/select-v2.html#创建临时选项](https://element-plus.gitee.io/zh-CN/component/select-v2.html#创建临时选项)，去“创建临时选项”范例里测试。

1. 直接输入预设选项里没有的文字，比如`富强`，回车，会发现无反应。

2. 为了避开上述bug，你可以先下拉选一个`a0`，然后再敲`富强`，再回车，此时反应正常，但是继续回车，会把胶囊里的`富强`抹除，这属于用户预料之外的反应。

3. 再继续敲回车，整个组件消失！控制台报错！

### What is Expected?
1. 直接输入预设选项里没有的文字，比如`富强`，回车，`富强`应成为胶囊。

2. `富强 `成为胶囊之后，胶囊右侧的文字应消失。

3. 任何时候回车不应该删除任何胶囊。只有鼠标和退格键才有权删除胶囊。

4. 组件不报错，不消失。

### What is actually happening?
同“重现步骤”

**Comment by emojiiii** [comment]
1. 直接输入 `富强` 回车没反应是因为你还需要下拉选中这个选项才可以选中(正常表现)
2. `富强`成为胶囊后，文字理应消失(bug)
3. 回车删除胶囊是因为此时你选中了`富强`这个选项，组件是支持键盘选中和不选中事件，如果你不希望有这些表现，你可以禁用键盘事件
4. 组件报错(bug)

**Comment by msidolphin** [comment]
开启临时创建时建议将reserve-keyword设置为false，第一次创建要自己选中下拉项

**Comment by msidolphin** [comment]
> 1. 直接输入 `富强` 回车没反应是因为你还需要下拉选中这个选项才可以选中(正常表现)
> 2. `富强`成为胶囊后，文字理应消失(bug)
> 3. 回车删除胶囊是因为此时你选中了`富强`这个选项，组件是支持键盘选中和不选中事件，如果你不希望有这些表现，你可以禁用键盘事件
> 4. 组件报错(bug)

第二条没消失时因为开始了reserve-keyword

**Comment by microkof** [comment]
> 1. 直接输入 `富强` 回车没反应是因为你还需要下拉选中这个选项才可以选中(正常表现)
> 2. `富强`成为胶囊后，文字理应消失(bug)
> 3. 回车删除胶囊是因为此时你选中了`富强`这个选项，组件是支持键盘选中和不选中事件，如果你不希望有这些表现，你可以禁用键盘事件
> 4. 组件报错(bug)

1. 咱们是顶级的组件库，应该保持良好的、统一的交互体验，后面能敲回车，首个不能敲回车，这不太能说是正常体验。具体说，其实是，第一次敲富强，dropdown没有自动高亮，后面再敲富强，就给自动高亮了，这确实是表现不统一，应该属于异常表现。
2. 这一条我举报错了，并不是bug，因为第一个范例就是保留关键词，那么表现是没问题的。
3. 这一条也是我举报错了，不是bug。
4. 确实是bug

**Comment by weidehai** [comment]
> > 1. 直接输入 `富强` 回车没反应是因为你还需要下拉选中这个选项才可以选中(正常表现)
> 
> > 2. `富强`成为胶囊后，文字理应消失(bug)
> 
> > 3. 回车删除胶囊是因为此时你选中了`富强`这个选项，组件是支持键盘选中和不选中事件，如果你不希望有这些表现，你可以禁用键盘事件
> 
> > 4. 组件报错(bug)
> 
> 
> 
> 1. 咱们是顶级的组件库，应该保持良好的、统一的交互体验，后面能敲回车，首个不能敲回车，这不太能说是正常体验。具体说，其实是，第一次敲富强，dropdown没有自动高亮，后面再敲富强，就给自动高亮了，这确实是表现不统一，应该属于异常表现。
> 
> 2. 这一条我举报错了，并不是bug，因为第一个范例就是保留关键词，那么表现是没问题的。
> 
> 3. 这一条也是我举报错了，不是bug。
> 
> 4. 确实是bug

确实，建议修改逻辑为匹配用户输入与列表选项，高亮匹配最接近的那个选项@msidolphin

**Comment by microkof** [comment]
> 开启临时创建时建议将reserve-keyword设置为false，第一次创建要自己选中下拉项

我建议Select V2与Select保持一致的体验，Select组件首次输入即输入富强，是有正确反应的。
