### ISSUE TITLE
[Bug Report] el-select 失去焦点，再次聚焦时出现无限抖动BUG

### ISSUE THREAD

**Issue by sunjianxu** [element-plus/element-plus#5905]
### Element Plus version
2.0.1

### OS/Browsers version
Google Chrome 版本 97.0.4692.99

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/sunjianxu/pen/WNXjrWM

### Steps to reproduce
1. size设置为default
2. filterable设置为true
3. multiple设置为true
4. lebel 字符长度大于10
5. 选中后 失焦再次聚焦el-select

### What is Expected?
1. filterable:true 时，失去焦点再次点击不要出现无限抖动问题
2. 选中的样式不被推上去。修复样式错乱问题

### What is actually happening?
el-select 失去焦点再次点击出现无限抖动问题

**Comment by fanzhengshao** [comment]
反正我觉得这个下拉选择这个组件估计是没测试好，很多bug，特别是在多选的时候一堆bug
