### ISSUE TITLE
[Bug Report] [select组件] default-first-option 混乱

### ISSUE THREAD

**Issue by jchalex** [element-plus/element-plus#5914]
### Element Plus version
2.0.1

### OS/Browsers version
macbook pro m1

### Vue version
3.2.25

### Reproduction Link
https://codepen.io/jchalex/pen/XWzRKrj

### Steps to reproduce
<el-select 
        v-model="value1" 
        multiple
        filterable
        default-first-option                         
        placeholder="Select" 
        @change="log">
        <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"></el-option>
      </el-select>

### What is Expected?
as point, select the first option, not chaos

### What is actually happening?
default-first-option select a wrong option

<img width="958" alt="企业微信截图_c20b11f1-78d0-437b-ad14-4540c8ba9bf0" src="https://user-images.githubusercontent.com/11224001/153335500-960f48d1-e9c8-4113-a019-5becff6568ce.png">

![image](https://user-images.githubusercontent.com/11224001/153335548-cffbd657-51f5-4d80-aab2-9e7695d9f14a.png)

**Comment by kooriookami** [comment]
Fixed
