### ISSUE TITLE
[Bug Report] 给组件设置size，但是popover面板的尺寸没有任何变化

### ISSUE THREAD

**Issue by libbGit** [element-plus/element-plus#5918]
### Element Plus version
2.0.1

### OS/Browsers version
microsoft edge

### Vue version
3.2.30

### Reproduction Link
https://github.com/element-plus/element-plus/issues/new/choose

### Steps to reproduce
none

### What is Expected?
期望组件通过设置 size="small"后，弹出的popover面板也会有大小的变化

### What is actually happening?
1、Cascader 级联选择器 
2、ColorPicker 颜色选择器
3、DatePicker 日期选择器
4、DateTimePicker 日期时间选择器
5、Select 选择器
6、Select V2 虚拟列表选择器
7、TimePicker 时间选择器
8、TimeSelect 时间选择
9、Dropdown 下拉菜单

以上组件通过设置 size="small"后，弹出的popover面板大小并没有变化，

**Comment by emojiiii** [comment]
是希望设置size以后，popover 内的组件也能自动跟随 size变化？

**Comment by libbGit** [comment]
> 



> 是希望设置size以后，popover 内的组件也能自动跟随 size变化？

**Comment by emojiiii** [comment]
> 是的，如果组件设置 size="small",那么相应的popover也应当尺寸较小。 如果设置size="large",那么响应的popover也应当尺寸较大

目前并没有这方面的设计，可能需要跟我们的设计师讨论一下。
