### ISSUE TITLE
[Feature Request] 如何拿到所有的icon types

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#5919]
### Existing Component
Yes

### Component Name
el-icon

### Description
如何拿到所有的icon types

**Comment by emojiiii** [comment]
`export * as Icons from '@element-plus/icons-vue'` ?

**Comment by gjfei** [comment]
这样的打包的时候是不是就把所有的icon 打进去了？

**Comment by gjfei** [comment]
> `export * as Icons from '@element-plus/icons-vue'` ?

这样的打包的时候是不是就把所有的icon 打进去了？

**Comment by emojiiii** [comment]
> 这样的打包的时候是不是就把所有的icon 打进去了？

会的。

**Comment by gjfei** [comment]
> `export * as Icons from '@element-plus/icons-vue'` ?

如果我要拿element plus 二次封装，在typescript 中如何继承element plus 的类型

**Comment by emojiiii** [comment]
```typescript
import type { ButtonInstance } from 'element-plus'

type MyCustomButtonInstance = ButtonInstance & { custom: string; }
```
这样的意思吗？

**Comment by gjfei** [comment]
> ```ts
> import type { ButtonInstance } from 'element-plus'
> 
> type MyCustomButtonInstance = ButtonInstance & { custom: string; }
> ```
> 
> 这样的意思吗？

tableInstance 和tableColumnInstance 好像没有看到？

**Comment by emojiiii** [comment]
很不好意思，有些组件还没有完全重构完毕。

**Comment by emojiiii** [comment]
是的，如果没有什么疑问我就关闭这个issues了

**Comment by gjfei** [comment]
> 是的，如果没有什么疑问我就关闭这个issues了
好的
