### ISSUE TITLE
Component 'message' is not compatible with its declaration

### ISSUE THREAD

**Issue by discko** [element-plus/element-plus#592]
I am using Element-Plus, version 1.0.1-alpha.14
in the definition of the component 'message' (which is located at package/message/src/index.ts), Message is an `IMessage`.
```ts
// in package/message/src/types.ts
export interface IMessage {
  (options?: IMessageOptions | string) : IMessageHandle
  closeAll(): void
}
```
but the declaration (according to `import { Message } from 'element-plus'`, Message is a `ElMessage`) of the `ElMessage` is
```ts
// in types/message.d.ts
export interface ElMessage {
  /** Show an info message */
  (text: string): ElMessageComponent

  /** Show message */
  (options: ElMessageOptions): ElMessageComponent

  /** Show a success message */
  success (text: string): ElMessageComponent

  /** Show a success message with options */
  success (options: ElMessageOptions): ElMessageComponent

  /** Show a warning message */
  warning (text: string): ElMessageComponent

  /** Show a warning message with options */
  warning (options: ElMessageOptions): ElMessageComponent

  /** Show an info message */
  info (text: string): ElMessageComponent

  /** Show an info message with options */
  info (options: ElMessageOptions): ElMessageComponent

  /** Show an error message */
  error (text: string): ElMessageComponent

  /** Show an error message with options */
  error (options: ElMessageOptions): ElMessageComponent
}
```
the two are not compatible.

In element-ui, 'message' code is written as this: after defining `const Message` and  before defining `Message.close`(starts at line 46 in element-ui/packages/message/src/main.js): 
```js
// @ element-ui/packages/message/src/main.js, version 2.14.0
['success', 'warning', 'info', 'error'].forEach(type => {
  Message[type] = options => {
    if (typeof options === 'string') {
      options = {
        message: options
      };
    }
    options.type = type;
    return Message(options);
  };
});
```
did it on purpose?

**Comment by JeremyWuuuuu** [comment]
Sorry for the inconvenience, I think this is a mistake that I made in the declaration file, I did export the `Message` component with members `success` `error` etc, you can use it directly by
```ts
import { Message } from 'element-plus/lib/message';
Message.success();
```
This is a issue that we need to fix, but in the current stage, we just hit our first milestone (the migration), the next stage, we want to test our migrated components, fix bugs, types, exports, docs. Hope my answer here could help you with your issue, I will fix the declaration file tomorrow.

**Comment by xiaoxian521** [comment]
@JeremyWuuuuu  我全局引入了element-plus 那么我在vue种需要如何使用message组件呢

**Comment by JeremyWuuuuu** [comment]
Do you still suffer from this issue?

**Comment by JeremyWuuuuu** [comment]
Closing due to no response. Feel free to reopen.
