### ISSUE TITLE
提供的标签名称('fa fa-key')不是一个有效的名称。

### ISSUE THREAD

**Issue by aswdw** [element-plus/element-plus#5925]
**从版本1.0.1-beta.7更新到2.0.1之后就报这个错！！！大佬们--江湖救急 页面现在直接打不开了 月底版本就上线了**
![element](https://user-images.githubusercontent.com/52225481/153372374-7bb1c420-ca43-4d38-b8ea-29ac61eb3be7.png)

**Comment by emojiiii** [comment]
这看起来不是 `element-plus` 的问题。。

**Comment by aswdw** [comment]
> 

那是我是升级element-plus就是出现了 退回原来的版本就没问题了

**Comment by aswdw** [comment]
> 你的`vue`版本是多少。你可能需要更新一下你的`vue`最新版本

"vue": "^3.2.29"最新的稳定版本。

**Comment by emojiiii** [comment]
你可以尝试一下新建一个项目，初始版本是 `1.0.1-beta.7`, 然后随便使用几个示例组件，再升级到 最新版，看看还会不会出现这样的错误。

**Comment by aswdw** [comment]
好的
