### ISSUE TITLE
[Bug Report] Select V2 placeholder's size is wrong

### ISSUE THREAD

**Issue by lemoe2021** [element-plus/element-plus#5928]
### Element Plus version
2.0.1

### OS/Browsers version
chrome

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/see_below

### Steps to reproduce
placeholder's size is not mini
you can compare with input

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwiaW5wdXRcIlxuICAgIHNpemU9XCJzbWFsbFwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgSW5wdXRcIlxuICAvPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cInNtYWxsXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcblxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuXG5jb25zdCBpbnB1dCA9IHJlZignJylcbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICBsYWJlbDogYCR7aW5pdGlhbHNbaWR4ICUgMTBdfSR7aWR4fWAsXG59KSlcblxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtc2VsZWN0LXYyIHtcbiAgbWFyZ2luLXJpZ2h0OiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==

### What is Expected?
placeholder's size is mini

### What is actually happening?
placeholder's size is default

**Comment by lemoe2021** [comment]
This is more obvious, small font-size should be 12px.

<img width="1417" alt="3" src="https://user-images.githubusercontent.com/79942901/153384522-f7c79f47-dd74-415d-91ea-e84bd13db520.png">

**Comment by lemoe2021** [comment]
When enable both multiple and filterable, the font size is stuck to default too. This also happened in the normal select component.
I guess if components use input rather than el-input, this problem happens.

**Comment by emojiiii** [comment]
thanks your report !
