### ISSUE TITLE
[Feature Request] 怎么自定义框架类名前缀

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#5929]
### Existing Component
Yes

### Component Name
el-config-provider

### Description
最好可以在element-ui中实现, 实在不行的话, 就plus吧, 谢谢了, 有个qiankun的项目, 主应用是element-ui, 子应用plus, 现在污染了

**Comment by emojiiii** [comment]
`element-ui` 看起来是不太行了。 `element-plus` 现在在实现中。

**Comment by a15218378694** [comment]
> `element-ui` 看起来是不太行了。 `element-plus` 现在在实现中。

这个大概什么时候可以实现呢 ? r如果不用太久的话, 我这边就不再写兼容代码

**Comment by emojiiii** [comment]
> 这个大概什么时候可以实现呢 ? r如果不用太久的话, 我这边就不再写兼容代码

没这么快彻底完成，正在逐步更改，具体进度可看上方 `issues`

**Comment by iamkun** [comment]
You can set global `namespace` config in https://element-plus.org/en-US/component/config-provider.html#config-provider-attributes

This feature is available after v2.1.10
