### ISSUE TITLE
Locally introduce the ui library and report an error Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by qq282126990** [element-plus/element-plus#596]
![image](https://user-images.githubusercontent.com/26755049/99148081-ae03e800-26c0-11eb-9033-d9c0054a4784.png)
![image](https://user-images.githubusercontent.com/26755049/99148088-b9571380-26c0-11eb-9e9a-d0d2fa3cf711.png)

I have tried several times, probably due to ```defineComponent```

Unrecognized

**Comment by JeremyWuuuuu** [comment]
According to your screenshots, I hope that you went through the guideline step by step, because you clearly did not register `ElementPlus` as global component, in this case you could never introduce it to the UI because `Vue` does not recognize components which undeclared. You need follow the setup steps at [ElementPlus](https://element-plus.org/#/zh-CN/component/installation)

**Comment by qq282126990** [comment]
I use the cnd method
![image](https://user-images.githubusercontent.com/26755049/99148417-7a29c200-26c2-11eb-8c3a-062f27e009d7.png)

**Comment by qq282126990** [comment]
I download the file locally and it is not available, but I can use <script src="https://unpkg.com/element-plus/lib/index.js"></script>

**Comment by qq282126990** [comment]
Let me download this file to a local directory, and it will make an error through local reference

![image](https://user-images.githubusercontent.com/26755049/99148472-caa11f80-26c2-11eb-8bea-a2b3c5a3a83f.png)

![image](https://user-images.githubusercontent.com/26755049/99148508-fe7c4500-26c2-11eb-85a1-2829f93da424.png)

Change here to the downloaded ```index.js```

I downloaded the source code from ```github```, running your directory locally will also report an error

![image](https://user-images.githubusercontent.com/26755049/99148567-67fc5380-26c3-11eb-95ae-cfcde6c3aa8c.png)

![image](https://user-images.githubusercontent.com/26755049/99148572-78143300-26c3-11eb-8557-6de862d76739.png)

Because I am currently developing my own vue3.0 UI library, I hope to learn how to export ``UMD``` files

**Comment by JeremyWuuuuu** [comment]
Sure, I guess we have some problem in the umd exports, I asked @zazzaz for the answer, he told me that we did have problems, we will fix that in the coming version.

**Comment by zazzaz** [comment]
Hi, you can check this answer as a reference https://github.com/element-plus/element-plus/issues/581#issuecomment-729562200

**Comment by qq282126990** [comment]
this is ok, ty，I am running my vue3 plugin normally

**Comment by zazzaz** [comment]
cool
