### ISSUE TITLE
[Bug Report] Table组件在Chrome 66浏览器中会无规律缺少部分列

### ISSUE THREAD

**Issue by charlesace** [element-plus/element-plus#5966]
### Element Plus version
2.0.1

### OS/Browsers version
Chrome 66

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/

### Steps to reproduce
1. 请无视Reproduction Link中的链接，直接使用Chrome 66打开element-plus官网中的Table组件https://element-plus.gitee.io/zh-CN/component/table.html
2. 查看“带斑马纹表格”例子，该例子缺少Date列

### What is Expected?
正常展示

### What is actually happening?
浏览器兼容性问题，Chrome 70以上版本正常

**Comment by msidolphin** [comment]
方便提供下报错信息吗

**Comment by charlesace** [comment]
> 方便提供下报错信息吗

控制台没有报错，渲染时列元素缺少了

**Comment by ealldy** [comment]
我们团队也遇到此问题，经测试，Chrome浏览器60及69能够稳定复现。

**Comment by ealldy** [comment]
@msidolphin 
大佬有暂时解决办法吗，多个表格出现此问题，无法正常交付。

**Comment by ealldy** [comment]
https://chromestatus.com/features#milestone%3D70
This page lists the updated features of version 70 chrome browser, but I can't get any information from it to solve the problem.

**Comment by msidolphin** [comment]
@charlesace @ealldy 麻烦提供下完整的版本号

**Comment by ealldy** [comment]
@msidolphin
感谢回复!
项目复现环境:
Vue 3.0.0
element-plus 1.3.0-beta.1
目前测试 chrome 60 65 66 69 均稳定复现，chrome 70以上不存在该问题

另外，直接使用以上版本浏览器打开官方文档即可复现: https://element-plus.gitee.io/zh-CN/component/table.html
一般情况是缺失某几列，某些情况会整个表格缺失。
![eg](https://user-images.githubusercontent.com/41937421/154260131-55337e4f-216b-455e-bd1a-9b37cfbfb477.PNG)
![eg2](https://user-images.githubusercontent.com/41937421/154260142-746324c2-aaef-4ad7-8cda-237ae2cd7186.jpg)
