### ISSUE TITLE
Bug with ColorPicker

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#598]
1. ColorPicker in doc has wrong style.
![image](https://user-images.githubusercontent.com/38392315/99206321-0ee10c80-27f6-11eb-9a67-8370db08a5ec.png)

2. I can't click the color panel to select a color.
![image](https://user-images.githubusercontent.com/38392315/99206399-42bc3200-27f6-11eb-881d-39b43899bb2c.png)

**Comment by zazzaz** [comment]
Thanks. This is a known bug and will be fixed in the next release.
