### ISSUE TITLE
[Bug Report] Upload not respecting changes to props

### ISSUE THREAD

**Issue by msidolphin** [element-plus/element-plus#5988]
### Discussed in https://github.com/element-plus/element-plus/discussions/5892

<div type='discussions-op-text'>

<sup>Originally posted by **NinjaJake86** February  9, 2022</sup>
Hey all,

so i'm updating the action prop on the upload component using a computed variable but when i manually upload (https://element-plus.org/en-US/component/upload.html#manual-upload) it uses the old computed variable, any ideas? I've checked and the computed variable does indeed update but if i check uploadRef.value.action it is still the old value.

Any help is apreciated!</div>

**Comment by sxzz** [comment]
Could you please provide a reproduction? I couldn't follow you.
