### ISSUE TITLE
[Bug Report] 最新版按官网文档给出的自动按需导入, table组件固定高度时不滚动

### ISSUE THREAD

**Issue by bthulu** [element-plus/element-plus#5990]
### Element Plus version
2.0.1

### OS/Browsers version
windows ltsc 2021, edge

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/iamkun/pen/YzWMaVr1

### Steps to reproduce
这个没法在jsfiddle/codepen/codesandbox中复现, 因为在html中直接引入element-plus/dist/index.css后就没这个问题了.
复现步骤:
1. 创建一个vue项目
2. 按官网文档https://element-plus.gitee.io/zh-CN/guide/quickstart.html添加element-plus
3. 按官网文档https://element-plus.gitee.io/zh-CN/guide/quickstart.html快速开始中的自动导入执行
```
npm install -D unplugin-vue-components unplugin-auto-import
```
4. 新建vue.config.js到项目根目录, 内容如下:
```
const AutoImport = require('unplugin-auto-import/webpack')
const Components = require('unplugin-vue-components/webpack')
const { ElementPlusResolver } = require('unplugin-vue-components/resolvers')

module.exports = {
    configureWebpack: {
        plugins: [
            AutoImport({
                resolvers: [ElementPlusResolver()],
            }),
            Components({
                resolvers: [ElementPlusResolver()],
            }),
        ],
    },
};

```
5. 复制官网代码, 一字不改 https://element-plus.gitee.io/zh-CN/component/table.html#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4

### What is Expected?
固定表格高度时, 表格可以滚动显示

### What is actually happening?
固定表格高度时, 表格不可以滚动显示

**Comment by 1257041477** [comment]
为啥，按照这样的按需引入会报错呢

**Comment by zychome** [comment]
遇到同样的问题

**Comment by emojiiii** [comment]
it's seem do not to auto import `scrollbar` style.

**Comment by dxy2233** [comment]
不介意大小的话，项目中直接导入一次css就可以了
(另外使用msg等组件时，目前还是需要写额外的引入代码)
