### ISSUE TITLE
[Feature Request] Menu菜单能不能增加一个当前激活菜单的背景色?

### ISSUE THREAD

**Issue by bthulu** [element-plus/element-plus#5995]
### Existing Component
Yes

### Component Name
el-menu-item

### Description
当前激活菜单后仅菜单文字变色高亮, 菜单较多时看起来很不明显, 很难短时间内知道当前激活的是哪个菜单.
Element官网都知道在菜单激活的时候再给菜单背景色设为淡蓝色, 为什么到了这里就没有了?
![微信截图_20220212083052](https://user-images.githubusercontent.com/38602293/153688257-b873e31e-2a27-45ff-a725-fbc9f52d9a86.png)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/157384496-9cef3f33-dcfa-4e68-9ec1-36731dae2212.png)
