### ISSUE TITLE
国际化语言无效

### ISSUE THREAD

**Issue by Shanks333** [element-plus/element-plus#600]
import { createApp } from 'vue'
import ElementPlus from 'element-plus';
import locale from 'element-plus/lib/locale/lang/zh-CN'
import 'element-plus/lib/theme-chalk/index.css';
import App from './App.vue'

const app = createApp(App);

app.use(ElementPlus, { locale });

app.mount('#app')

main.js这样写了之后组件的语言并没有改为中文

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz

**Comment by Shanks333** [comment]
ok了，升级到1.0.1-alpha.15版本解决了该问题

**Comment by zazzaz** [comment]
great
