### ISSUE TITLE
[Feature Request] update:version error

### ISSUE THREAD

**Issue by carveybunt** [element-plus/element-plus#6005]
### Existing Component
No

### Component Name
null

### Description
Why I got the error: `[error] No tag version or git head were found, make sure that you set the environment variable $TAG_VERSION` when I running `pnpm updater:version`. Someone can heplp me?

**Comment by carveybunt** [comment]
> You needn't run this. Just run `pnpm i`

Thanks, but I need to upgrade the version of the project.

**Comment by sxzz** [comment]
You need to set environment variables 
 https://github.com/element-plus/element-plus/blob/ea812ae622b8ef979abb3538c3e7dd6d4b748ca5/.github/workflows/publish-npm-nightly.yml#L63-L65

**Comment by carveybunt** [comment]
> You need to set environment variables
> 
> https://github.com/element-plus/element-plus/blob/ea812ae622b8ef979abb3538c3e7dd6d4b748ca5/.github/workflows/publish-npm-nightly.yml#L63-L65

Thanks a lot of, I will try now.
