### ISSUE TITLE
[Bug Report] Upload components Clicking on Google Chrome doesn't work？

### ISSUE THREAD

**Issue by Red-xiaoshami** [element-plus/element-plus#6007]
### Element Plus version
2.0.0

### OS/Browsers version
mac/版本 97.0.4692.99（正式版本） (x86_64)

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/ev9mqygz/

### Steps to reproduce
Upload components

1. Clicking on the official website document in the Google browser doesn't work；
2. It is also not possible in the local project；

Development environment：
mac / Chrome / 版本 97.0.4692.99（正式版本） (x86_64)

### What is Expected?
Click to upload file.

### What is actually happening?
no response

**Comment by emojiiii** [comment]
I don't seem to find the problem

**Comment by lemonKun** [comment]
google's bug，update google and reload，then the problem can be fixed~
