### ISSUE TITLE
[Bug Report] 配置按需自动导入后，ts无法推断出组件上的方法

### ISSUE THREAD

**Issue by AlphaYoung111** [element-plus/element-plus#6009]
### Element Plus version
2.0.1

### OS/Browsers version
windows11/Chrome 98.0.4758.82

### Vue version
3.2.29

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-x37nh?file=/src/App.vue:37-44

### Steps to reproduce
1. 使用官方指南推荐的按需自动导入，采用vite,及 unplugin-auto-import/vite插件自动导入vue相关依赖
2. 开启volar插件，使用yarn包管理工具
3. 在tsconfig中配置`"types": ["element-plus/global"]`
4. 在app.vue中添加如下代码

```vue
<template>
  <el-button type="primary">ele 按钮</el-button>

  <el-form ref="formRef"></el-form>
</template>
<script setup lang="ts">
import { GlobalComponents } from 'vue';

const formRef = ref<GlobalComponents['ElForm']>()

</script>
<style lang="scss">
```

### What is Expected?
1. 使用`formRef.value`时ts能推导出el-form上面的方法，如validate等

### What is actually happening?
1. 使用`formRef.value`时ts只能推导出vue正常组件的生命周期等内置的属性，无法推到出el-form上面的方法，如validate等

**Comment by zychome** [comment]
同样的问题，并且eltable组件在固定高度时，不可滚动。

**Comment by sxzz** [comment]
```vue
<template>
  <el-button type="primary">ele 按钮</el-button>

  <el-form ref="formRef"></el-form>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import type { GlobalComponents } from 'vue'

const formRef = ref<InstanceType<GlobalComponents['ElForm']>>()
console.log(formRef.value?.validate)
</script>

```
