### ISSUE TITLE
A Few Bug List

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#602]
I'm not sure whether you have known these bugs, I just list them for your information.
1. The slider button above on the popover.
![image](https://user-images.githubusercontent.com/38392315/99217811-e5cf7480-2813-11eb-8a1d-96e5eb961c99.png)
2. The color picker can't colse on click twice.
3. Notification under the doc header.
![image](https://user-images.githubusercontent.com/38392315/99217868-08fa2400-2814-11eb-9381-b1ceb5ca68fd.png)
4. The message appeared in no animation.
![image](https://user-images.githubusercontent.com/38392315/99218359-3dbaab00-2815-11eb-998a-ffdacb511a69.png)
5. The message hasn't bind functions like `this.$message[type]`(type of success/warning/info/error)

**Comment by JeremyWuuuuu** [comment]
Thanks for reporting the bugs, I'll follow up these bugs making sure they are tracked
