### ISSUE TITLE
[Bug Report] Element Plus select选择框的属性 popper-append-to-body(deprecated)

### ISSUE THREAD

**Issue by 2512746832** [element-plus/element-plus#6023]
### Element Plus version
2.0.1

### OS/Browsers version
win11/chrome 最新

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/wangfaxiang/5s7z91ym/32/

### Steps to reproduce
点击激活按钮，点击下拉，点击选项，确定之后，会移动到屏幕左上方

### What is Expected?
select 选择框在父标签上 不要加在body上

### What is actually happening?
select 选择框 移动到了body上

**Comment by 2512746832** [comment]
主要是popover 和select 配合的问题，单独使用是没有问题的

**Comment by Alanscut** [comment]
#3800

**Comment by 2512746832** [comment]
<template&gt;
&nbsp; <el-popover
&nbsp; &nbsp; placement="bottom"
&nbsp; &nbsp; title="标题"
&nbsp; &nbsp; width="200"
&nbsp; &nbsp; trigger="click"
&nbsp; &gt;
&nbsp; 
&nbsp; &nbsp;<el-select v-model="value1" multiple placeholder="请选择" :popper-append-to-body="false" :teleported="false"&gt;
&nbsp; &nbsp; &nbsp; <el-option
&nbsp; &nbsp; &nbsp; &nbsp; v-for="item in options"
&nbsp; &nbsp; &nbsp; &nbsp; :key="item.value"
&nbsp; &nbsp; &nbsp; &nbsp; :label="item.label"
&nbsp; &nbsp; &nbsp; &nbsp; :value="item.value"
&nbsp; &nbsp; &nbsp; &gt;
&nbsp; &nbsp; &nbsp; </el-option&gt;
&nbsp; &nbsp; </el-select&gt;

&nbsp; &nbsp;
&nbsp; &nbsp; <template #reference&gt;
&nbsp; &nbsp; &nbsp; <el-button&gt;Click to activate11</el-button&gt;
&nbsp; &nbsp; </template&gt;
&nbsp; </el-popover&gt;
</template&gt;
<script&gt;
import { ref } from "vue";

export default {
&nbsp; name: "Test",
&nbsp; setup() {
&nbsp; &nbsp; const value1 = ref([]);
&nbsp; &nbsp; const options = [
&nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; value: "Option1",
&nbsp; &nbsp; &nbsp; &nbsp; label: "Option1",
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; value: "Option2",
&nbsp; &nbsp; &nbsp; &nbsp; label: "Option2",
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; value: "Option3",
&nbsp; &nbsp; &nbsp; &nbsp; label: "Option3",
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; value: "Option4",
&nbsp; &nbsp; &nbsp; &nbsp; label: "Option4",
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; value: "Option5",
&nbsp; &nbsp; &nbsp; &nbsp; label: "Option5",
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; ];
&nbsp; &nbsp; return {
&nbsp; &nbsp; &nbsp; value1,
&nbsp; &nbsp; &nbsp; options,
&nbsp; &nbsp; };
&nbsp; },
};
</script&gt;






不好使，还是跑到屏幕左上方
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Bug Report] Element Plus select选择框的属性 popper-append-to-body(deprecated) (Issue #6023)





 
#3800
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by msidolphin** [comment]
用teleported，后续popper-append-to-body会废弃

**Comment by 2512746832** [comment]
<el-select v-model="value1" multiple placeholder="请选择" :popper-append-to-body="false" :teleported="false">
 :popper-append-to-body="false"   和  :teleported="false"
这两个我都用了，可是点击选项确定后，还是会跑到屏幕的左上方

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/153829615-5aa2dadb-69b7-4d0d-bf02-bc1d057b7bd3.mp4

我这里是没问题的

**Comment by 2512746832** [comment]
我是的element plus 这两个都用了不行

<el-popover
    placement="bottom"
    title="标题"
    width="200"
    trigger="click"
  >
   <el-select v-model="value1" multiple placeholder="请选择" :teleported="false" :popper-append-to-body="false">
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      >
      </el-option>
    </el-select>
    <template #reference>
      <el-button>Click to activate1</el-button>
    </template>
  </el-popover>

**Comment by 2512746832** [comment]
<el-popover
    placement="bottom"
    title="标题"
    width="200"
    trigger="click"
  >
   <el-select v-model="value1" multiple placeholder="请选择" :teleported="false" :popper-append-to-body="false">
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      >
      </el-option>
    </el-select>
    <template #reference>
      <el-button>Click to activate1</el-button>
    </template>
  </el-popover>
</template>

我的也没问题啊，怎么不行

**Comment by Alanscut** [comment]
<template>
  <div style="margin-bottom: 200px">
    <el-popover placement="bottom" :width="200">
      <template #reference>
        <el-button>Click to pop</el-button>
      </template>
      <el-select
        v-model="selectedItems"
        :teleported="false"
        multiple
        placeholder="example1"
        clearable
      >
        <el-option
          v-for="item in items"
          :key="item.value"
          :label="item.label"
          :value="item.value"
        />
      </el-select>
    </el-popover>
  </div>
</template>

<script>
import { ref } from 'vue'
export default {
  setup() {
    return {
      items: [
        { label: 'one', value: 1 },
        { label: 'two', value: 2 },
        { label: 'three', value: 3 },
      ],
      selectedItems: ref([]),
    }
  },
}
</script>

**Comment by 2512746832** [comment]
我复制的上面代码，还是出现那种效果

**Comment by 2512746832** [comment]
![1](https://user-images.githubusercontent.com/70892499/153832545-4af5708e-624f-4e3c-86c4-a64785c145f2.png)
![2](https://user-images.githubusercontent.com/70892499/153832575-28cee969-32ec-4707-879d-5a3d238f2ada.png)

**Comment by 2512746832** [comment]
就只是把弹出层的触发条件改为了点击

**Comment by emojiiii** [comment]
please update the last version `2.0.2`

**Comment by 2512746832** [comment]
"element-plus": "^1.3.0-beta.9",不行吗

**Comment by emojiiii** [comment]
> "element-plus": "^1.3.0-beta.9",不行吗

i'm sorry. `select` is not support `teleported` in `1.3.0-beta.9`

**Comment by 2512746832** [comment]
但是我的:popper-apper-to-body="false" 也不行

**Comment by emojiiii** [comment]
because this is a bug.
