### ISSUE TITLE
[Feature Request] select, Cascader, 希望可以提供个能力, 将选中项置顶, 按选中先后排序

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#6024]
### Existing Component
Yes

### Component Name
select, Cascader

### Description
大数据场景, 客户经常不知道自己选择了什么, 所以希望可以有个置顶的能力, 麻烦了, 非常感谢你们~

**Comment by emojiiii** [comment]
多选场景，置顶体验应该比较糟糕。或许可以选中后做一个已选中的选项的额外展示在旁边？

**Comment by a15218378694** [comment]
> 多选场景，置顶体验应该比较糟糕。或许可以选中后做一个已选中的选项的额外展示在旁边？

![image](https://user-images.githubusercontent.com/29919045/153826410-6a2341b5-65d3-4c72-9e80-7c29b949ca6c.png)
![image](https://user-images.githubusercontent.com/29919045/153826454-38bdc876-830c-480a-a94f-272720d308d5.png)
鼠标放到数字那里, hover展示全部怎样 ?

**Comment by emojiiii** [comment]
难道是我误会你的意思了？ 你不是希望 `select` or `cascader` 的选项置顶吗？然后滑动时会自动 `sticky` 在顶部 ?

**Comment by a15218378694** [comment]
> 难道是我误会你的意思了？ 你不是希望 `select` or `cascader` 的选项置顶吗？然后滑动时会自动 `sticky` 在顶部 ?

没有误会, 目的就是让用户可以看到自己的选中项, 滑动时自动 sticky 在顶部体验不好吧

**Comment by wzrove** [comment]
> > 多选场景，置顶体验应该比较糟糕。或许可以选中后做一个已选中的选项的额外展示在旁边？
> 
> ![image](https://user-images.githubusercontent.com/29919045/153826410-6a2341b5-65d3-4c72-9e80-7c29b949ca6c.png) ![image](https://user-images.githubusercontent.com/29919045/153826454-38bdc876-830c-480a-a94f-272720d308d5.png) 鼠标放到数字那里, hover展示全部怎样 ?

collapse-tags存在的时候，多选的时候点击数字，下拉栏就展示选中el-option。

**Comment by a15218378694** [comment]
> > > 多选场景，置顶体验应该比较糟糕。或许可以选中后做一个已选中的选项的额外展示在旁边？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29919045/153826410-6a2341b5-65d3-4c72-9e80-7c29b949ca6c.png) ![image](https://user-images.githubusercontent.com/29919045/153826454-38bdc876-830c-480a-a94f-272720d308d5.png) 鼠标放到数字那里, hover展示全部怎样 ?
> 
> collapse-tags存在的时候，多选的时候点击数字，下拉栏就展示选中el-option。

多选的情况下, 目前还没有具备这个能力吧, 如果点击数字, 可能也只是会看到其中一个选中项

**Comment by wzrove** [comment]
https://user-images.githubusercontent.com/88016243/154028621-3c2e1805-115c-4aed-8976-10a3d2d2d828.mov

这样的方案吗。

**Comment by a15218378694** [comment]
> 2022-02-15.4.13.00.mov 
> 这样的方案吗。

不是, 麻烦看下这个链接哦, https://gv1o2m.csb.app/

**Comment by a15218378694** [comment]
你好, 请问这个多选的效果可以加

https://user-images.githubusercontent.com/29919045/154648552-5e1e2155-b6e8-4af1-a3a8-2b43a7d9c89e.mp4

吗

**Comment by Alanscut** [comment]
https://user-images.githubusercontent.com/21104054/155255234-b020aa28-fcae-4b21-9a60-b1fa9c5c3d2a.mp4

**Comment by a15218378694** [comment]
> select_collapse_tags_tooltip.mp4

感谢
