### ISSUE TITLE
[Feature Request] el-scrollbar 无法和 infinite scroll 一起使用

### ISSUE THREAD

**Issue by bowencool** [element-plus/element-plus#6033]
### Existing Component
Yes

### Component Name
scrollbar

### Description
事件监听程序无法落到正确的容器
``` html
  <el-scrollbar
    v-infinite-scroll="loadMore"
    height="400px"
    :infinite-scroll-disabled="done"
    :infinite-scroll-distance="50"
    :class="$style.infiniteList"
  >
    ...
  </el-scrollbar>
```
![image](https://user-images.githubusercontent.com/20217146/153845439-7f5a73be-23b0-4211-844b-1f4bfe5b2600.png)

**Comment by Alanscut** [comment]
请提交[bug report]类型issue并附上demo
