### ISSUE TITLE
menu's group name can't display

### ISSUE THREAD

**Issue by fyzhu** [element-plus/element-plus#604]
menu's group name can't display

**Comment by zazzaz** [comment]
Looks OK with our demo code 
https://element-plus.org/#/en-US/component/menu

Can you provide more details? A screenshot or demo code will be great.

**Comment by JeremyWuuuuu** [comment]
Any updates? @fyzhu

**Comment by JeremyWuuuuu** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by fanhefeng** [comment]
She means 
```
<li class="el-menu-item-group">
    <div
      class="el-menu-item-group__title"
      :style="{ paddingLeft: levelPadding + 'px' }"
    >
      <template v-if="!slots.title">{{ title }}</template>
      <slot v-else name="title"></slot>
    </div>
    <ul>
      <slot></slot>
    </ul>
  </li>
```
Same question as her
