### ISSUE TITLE
el-pagination无法正常使用

### ISSUE THREAD

**Issue by lighter217** [element-plus/element-plus#605]
handleCurrentChange和handleSizeChange无效，currentPage和pageSize的值会变，但是table数据不会翻页。

**Comment by lighter217** [comment]
@current-change有效，@size-change无效。

**Comment by JeremyWuuuuu** [comment]
I made a fix in #590, also I think we had a release yesterday for recent bug fixes, please update your local version. Also I hope that you report an issue with a minimal reproducible code or a link, this would help us for locating the errors
