### ISSUE TITLE
[Bug Report] 按需引入导致el-table不能滚动 

### ISSUE THREAD

**Issue by tohere** [element-plus/element-plus#6055]
### Element Plus version
2.0.1

### OS/Browsers version
windows 10

### Vue version
3.2.25

### Steps to reproduce
通过按需加载el-table组件滚动失效
我发现是因为按需加载的时候并没有加载`el-scrollbar.css`这个文件
![image](https://user-images.githubusercontent.com/28532718/154003965-a5a14ae6-a154-4e6e-b451-1f350beb7fa1.png)

临时解决方案：在需要的组件中或者main.ts中手动引入el-scrollbar.css
![image](https://user-images.githubusercontent.com/28532718/154003988-78099c02-5e4d-4e0b-8d32-95b6e7e9ae6f.png)

### What is Expected?
el-table组件能实现滚动

### What is actually happening?
el-table组件滚动失效

**Comment by msidolphin** [comment]
已修复
