### ISSUE TITLE
[Bug Report] date-picker 图标错位

### ISSUE THREAD

**Issue by chenhaijia** [element-plus/element-plus#6056]
### Element Plus version
2.0.2

### OS/Browsers version
window

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/hopeful-wescoff-4c4k3

### Steps to reproduce
主题换色

### What is Expected?
不错位

### What is actually happening?
pading-left 和right失效

**Comment by YunYouJun** [comment]
I think it has been resolved.
