### ISSUE TITLE
2.0.2 Cannot find name 'Language'.

### ISSUE THREAD

**Issue by songjiachao** [element-plus/element-plus#6060]
### Element Plus version
2.0.2

### Vue version
3.2.31

### What is Expected?
no error

### What is actually happening?
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/70792885/154028612-c4fbc360-34c6-4f12-926b-9f5f2845cd1c.png">

**Comment by xukang0222** [comment]
我回退了 2.0.0版本就没这个问题了

**Comment by liujiangde** [comment]
我在打包时候也遇到了这个问题：  tsconfig.json加了个这个配置项  "skipLibCheck": true, // 针对element-puls的ts打包校验，打包成功

**Comment by kroawen** [comment]
同样的问题, "skipLibCheck": true才行
