### ISSUE TITLE
el-dialog缺少遮罩层，并且el-dialog打开后没有浮动在页面上

### ISSUE THREAD

**Issue by Angelinanay** [element-plus/element-plus#607]
![image](https://user-images.githubusercontent.com/24545670/99331048-c3446680-28ba-11eb-8ae0-9c61254013ec.png)

**Comment by Angelinanay** [comment]
![Uploading image.png…]()

**Comment by Angelinanay** [comment]
![image](https://user-images.githubusercontent.com/24545670/99330821-b32c8700-28ba-11eb-9f64-63004a900555.png)

**Comment by JeremyWuuuuu** [comment]
Reproducible code please

**Comment by zazzaz** [comment]
bug 1: lock-scroll by default
bug 2: no el-mask
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/10731096/99341444-d825f780-28c4-11eb-9c63-e608c6eedf5c.png">

**Comment by 12Tall** [comment]
Same issue from my side, but I think it was ok on `^1.0.1-alpha.14`.  Here is the component code:

```vue
<!-- login.vue --> 
<template>
  <el-link type="info" @click.prevent="ShowDlgLogin">
    [login]
  </el-link>

  <el-dialog
    title="Login Please"
    v-model="show_dlgLogin"
    width="500px"
    :before-close="CloseDlgLogin"
    :append-to-body="true"
  >

  <!-- ... -->

  </el-dialog>
</template>
```

<img width="434" alt="issue-el-dialog" src="https://user-images.githubusercontent.com/29416757/99343573-21784600-28c9-11eb-8063-1883b0f823c0.png">

**Comment by JeremyWuuuuu** [comment]
Thanks for providing detailed code. I will dig into it and try to fix it ASAP

**Comment by JeremyWuuuuu** [comment]
Oh, BTW, I was planing to remake `Dialog` Component myself, this should take some time, I will remake this one before the next weekend. This might take a while.
