### ISSUE TITLE
[Bug Report] Calling EiLoading as a service does not work for style loading

### ISSUE THREAD

**Issue by Hongbusi** [element-plus/element-plus#6079]
### Element Plus version
2.0.2

### OS/Browsers version
mac: 12.0.1 / chrome: latest

### Vue version
3.2.31

### Reproduction Link
https://github.com/Hongbusi/vue-element-admin

### Steps to reproduce
``` js
import { ElLoading } from 'element-plus'
ElLoading.service({
    lock: true,
    background: 'rgba(0, 0, 0, 0.5)'
})
```

### What is Expected?
Styles working properly

### What is actually happening?
loading functions correctly, but the style does not work.

**Comment by Alanscut** [comment]
import 'element-plus/es/components/loading/style/css'
https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5
![image](https://user-images.githubusercontent.com/21104054/155284073-149915d9-80e0-46ed-854a-619922d8a1e4.png)

**Comment by Hongbusi** [comment]
Import components through `unplugin-vue-components`.
Also tried importing style files `import 'element-plus/es/components/message/style/css'`, but it still didn't work. @Alanscut

**Comment by Alanscut** [comment]
import 'element-plus/es/components/loading/style/css'

**Comment by Hongbusi** [comment]
I'm amazed! Sorry, brain is short-circuited, I didn't notice that the css I introduced is not a loading component. @Alanscut

**Comment by Alanscut** [comment]
Haha, is the problem solved?

**Comment by Alanscut** [comment]
If there are no other problems, I will close it.
