### ISSUE TITLE
Can not use vue-i18n@next

### ISSUE THREAD

**Issue by ysfscream** [element-plus/element-plus#608]
https://element-plus.org/#/zh-CN/component/i18n

👆 Using the method in the document to configure i18n is invalid.

**Comment by Shanks333** [comment]
You can try upgrading to 1.0.1-alpha.15

**Comment by ysfscream** [comment]
Yes, I am using this version.

**Comment by zazzaz** [comment]
We will support vue-i18n@next (9.0.0) soon. But we'd like to see it release it's first `rc` version to freeze the public APIs.

**Comment by ysfscream** [comment]
OK, thanks for your answer, that's sound good!

**Comment by JeremyWuuuuu** [comment]
So we got vue-i18n@rc released. Track this issue in #1209  Closing this.
