### ISSUE TITLE
[Bug Report] 组件el-table 在 Chrome版本为 71 中失效

### ISSUE THREAD

**Issue by zbx12** [element-plus/element-plus#6091]
### Element Plus version
2.0.2

### OS/Browsers version
Windows系统 Chrome版本version 71

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/zbx12/pen/MWOOpdJ

### Steps to reproduce
无

### What is Expected?
期望出现数据展示

### What is actually happening?
列表没有数据渲染出来

**Comment by ealldy** [comment]
请查看是否与 #5966 问题重复

**Comment by zbx12** [comment]
> 请查看是否与 #5966 问题重复
问题出现的现象不一样，Chrome71版本是直接每一行的数据没有，空的，空白行出现

**Comment by msidolphin** [comment]
Can not be reproduced, but you can try the next version

**Comment by yeyumugui** [comment]
[官方示例中的table](https://element-plus.org/zh-CN/component/table.html#table-layout) 在chrome 66的版本下很多都显示空白的

**Comment by msidolphin** [comment]
> [官方示例中的table](https://element-plus.org/zh-CN/component/table.html#table-layout) 在chrome 66.0.3359.139的版本下很多都显示空白的

最新版本还能复现吗

**Comment by zwy575855161** [comment]
> 

2.1.8版本，el-table目前依然存在问题：
使用<el-table-column prop="name" label="Name"/> 表格中显示空白
使用<el-table-column prop="name" label="Name"><template #default="scope">scope.row.name</template></el-table-column> 表格中显示正常 

浏览器版本：   chrome72.0.3636.109（正式版本）（32位）。

**Comment by lj1114752845** [comment]
当前时间仍未修复官网示例仍有bug
![1661420451448](https://user-images.githubusercontent.com/34465333/186632242-c8f13b47-1ecb-43f2-8e0f-3dc15b293833.jpg)

临时解决方案
所有el-table-column 全部采用插槽实现可以正常使用
![1661420518172](https://user-images.githubusercontent.com/34465333/186632311-c243b64a-43d6-45e6-b9dd-988c361da16c.jpg)

**Comment by guobaorou-man** [comment]
chrome 73 版本。出现无插槽数据空白问题。修改 vite.config.ts 中 build 配置 target : 'es2015' 后可正常展示。
![image](https://user-images.githubusercontent.com/51397030/216291327-65aa7ca6-f745-43a6-b5e5-11354a420b3a.png)

**Comment by Jinzm** [comment]
2.3.6版本在71版本浏览器上也有这个问题

**Comment by btea** [comment]
It should have been fixed in version 2.3.10. https://github.com/element-plus/element-plus/pull/10640
