### ISSUE TITLE
[Feature Request] 表格 多级表头 无法取消border属性

### ISSUE THREAD

**Issue by XueMary** [element-plus/element-plus#6092]
### Existing Component
Yes

### Component Name
el-table

### Description
表格 多级表头 默认带了border属性， 且设置为border=false 无法取消border得展示

**Comment by msidolphin** [comment]
这个不行的，没有边框怎么看出来分级呢

**Comment by XueMary** [comment]
> 这个不行的，没有边框怎么看出来分级呢
从目前的border属性来看是这样的， 多级必须设置border才能区分， 有可能使border属性单独设置header和content两块区域吗， 而非整个table
`
<table>
  <tr>
    <th style="border:1px solid red">Month</th>
    <th style="border:1px solid red">Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
</table>
`

**Comment by XueMary** [comment]
`<table>
  <tr>
    <th style="border:1px solid red">Month</th>
    <th style="border:1px solid red">Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
  <tr>
    <td>February</td>
    <td>$80</td>
  </tr>
</table>`

**Comment by XueMary** [comment]
> 这个不行的，没有边框怎么看出来分级呢
从目前的border属性来看是这样的， 多级必须设置border才能区分， 有可能使border属性单独设置header和content两块区域吗， 而非整个table

**Comment by XueMary** [comment]
> 这个不行的，没有边框怎么看出来分级呢

从目前的border属性来看是这样的， 多级必须设置border才能区分， 有可能使header和content两块区域都独立拥有自己的border属性吗
