### ISSUE TITLE
[Bug Report] [el-popover] set `trigger="manual"`, clicking outside won't close

### ISSUE THREAD

**Issue by zengzhangjun007** [element-plus/element-plus#6096]
### Element Plus version
2.0.2

### OS/Browsers version
1

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
打开下面的地址， 看最后一个demo, 这个是官网的demo
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cInRvcC1zdGFydFwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiaG92ZXJcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU XG4gIDwvZWwtcG9wb3Zlcj5cblxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU XG4gIDwvZWwtcG9wb3Zlcj5cblxuICA8ZWwtcG9wb3ZlclxuICAgIHJlZj1cInBvcG92ZXJcIlxuICAgIHBsYWNlbWVudD1cInJpZ2h0XCJcbiAgICB0aXRsZT1cIlRpdGxlXCJcbiAgICA6d2lkdGg9XCIyMDBcIlxuICAgIHRyaWdnZXI9XCJmb2N1c1wiXG4gICAgY29udGVudD1cInRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50LCB0aGlzIGlzIGNvbnRlbnRcIlxuICA XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U XG4gICAgICA8ZWwtYnV0dG9uPkZvY3VzIHRvIGFjdGl2YXRlPC9lbC1idXR0b24 XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuXG4gIDxlbC1wb3BvdmVyXG4gICAgdi1tb2RlbDp2aXNpYmxlPVwidmlzaWJsZVwiXG4gICAgcGxhY2VtZW50PVwiYm90dG9tXCJcbiAgICB0aXRsZT1cIlRpdGxlXCJcbiAgICA6d2lkdGg9XCIyMDBcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gIXZpc2libGVcIj5NYW51YWwgdG8gYWN0aXZhdGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=

### What is Expected?
期待点击旁边关闭popover

### What is actually happening?
点击旁边不会关闭

**Comment by xiaoxian521** [comment]
嘿。官网正常打开、正常关闭
如果有问题，请提供正确链接，方便复现

**Comment by zengzhangjun007** [comment]
是最后一个Demo 打开了点旁边的关不掉的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月16日 18:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [element-plus/element-plus] [Bug Report] popover的bug，点开后， 点击旁边不会关闭 (Issue #6096) |

嘿。官网正常打开、正常关闭
如果有问题，请提供正确链接，方便复现

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaoxian521** [comment]
你指定是指令吗？ 所有用例 我测过没你说的问题，请提供下浏览器版本
<img width="417" alt="image" src="https://user-images.githubusercontent.com/44761321/154247416-a6615b28-9c1f-46f6-956c-89f11e978534.png">

**Comment by zengzhangjun007** [comment]
是这里点击旁边的不会关闭
![Image_20220216184147](https://user-images.githubusercontent.com/99796004/154248182-69720163-9bb5-4187-9bd6-5a47a7a14a3c.png)

**Comment by xiaoxian521** [comment]
好的 谢谢反馈，下个版本会修复此问题

**Comment by JeremyWuuuuu** [comment]
controlled popover will not have the ability to respond to `outside-clicking` so that you will take the full responsibility of the life cycle, you are the one hold accountable for turning it off.

**Comment by JeremyWuuuuu** [comment]
I didn't update the documentation accordingly which is definitely my mistake, I am so sorry for that :bow:

**Comment by JeremyWuuuuu** [comment]
If you wish to inherit `outside-clicking` you should use `@vueuse/core`.useClickoutside to do so.

**Comment by 874435441** [comment]
this component seems cannot click outside to close when v-model:visible is bind and trigger is 'click',why do this change?it become Inflexible.
