### ISSUE TITLE
[Bug Report] el-popover中包含el-date-picker，el-date-picker选择后会自动关闭el-popover

### ISSUE THREAD

**Issue by jinbiaode** [element-plus/element-plus#6097]
### Element Plus version
2.0.2

### OS/Browsers version
mac12.1

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/

### Steps to reproduce
el-popover中包含el-date-picker，el-date-picker选择后会自动关闭el-popover。

### What is Expected?
el-popover中包含el-date-picker，el-date-picker关闭后，el-popover仍然保留

### What is actually happening?
el-date-picker关闭后，整体全关闭了

**Comment by xiaoxian521** [comment]
Please provide the correct reproduction link

**Comment by jinbiaode** [comment]
https://codepen.io/jinbiaode/pen/rNYpVYY

**Comment by jinbiaode** [comment]
目前采用了el-popover   trigger="manual"方式

**Comment by xiaoxian521** [comment]
嘿，没有`trigger="manual"`，应该使用`v-model`
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/44761321/154417571-e351d10c-4975-4892-8b64-ad2442f37780.png">

**Comment by jinbiaode** [comment]
> 嘿，没有`trigger="manual"`，应该使用`v-model` <img alt="图片" width="1176" src="https://user-images.githubusercontent.com/44761321/154417571-e351d10c-4975-4892-8b64-ad2442f37780.png">

你仔细看文档了吗？
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/25757435/154429687-47ab654b-8441-4c1a-871d-42c62f7aa4fe.png">



https://codepen.io/jinbiaode/pen/rNYpVYY   也不看

**Comment by xiaoxian521** [comment]
> > 嘿，没有`trigger="manual"`，应该使用`v-model` <img alt="图片" width="1176" src="https://user-images.githubusercontent.com/44761321/154417571-e351d10c-4975-4892-8b64-ad2442f37780.png">
> 
> 你仔细看文档了吗？ <img alt="image" width="1430" src="https://user-images.githubusercontent.com/25757435/154429687-47ab654b-8441-4c1a-871d-42c62f7aa4fe.png">
> 
> https://codepen.io/jinbiaode/pen/rNYpVYY 也不看

我说文档有问题 没有trigger="manual"而是采用v-model，懂？

**Comment by jinbiaode** [comment]
> > > 嘿，没有`trigger="manual"`，应该使用`v-model` <img alt="图片" width="1176" src="https://user-images.githubusercontent.com/44761321/154417571-e351d10c-4975-4892-8b64-ad2442f37780.png">
> > 
> > 
> > 你仔细看文档了吗？ <img alt="image" width="1430" src="https://user-images.githubusercontent.com/25757435/154429687-47ab654b-8441-4c1a-871d-42c62f7aa4fe.png">
> > https://codepen.io/jinbiaode/pen/rNYpVYY 也不看
> 
> 我说文档有问题 没有trigger="manual"而是采用v-model，懂？要学会看pr



文档有visible / v-model:visible | Popover 是否显显示

trigger | 是触发方式   | click/focus/hover/ manual    这个触发都管用。 

可以说文档有问题，那么  看代码：https://codepen.io/jinbiaode/pen/rNYpVYY 

我在触发日期，Popover被关闭了

**Comment by Alanscut** [comment]
@jinbiaode 
很抱歉，现在的文档是有一点小问题的，已经在提交pr修改文档了。
trigger的参数里面是不包含manual的，如果想要manual控制，直接设置v-model:visible就好了，不需要设置trigger属性
![image](https://user-images.githubusercontent.com/21104054/154475401-96b44cce-f049-40be-8a1b-1653e559a788.png)
![image](https://user-images.githubusercontent.com/21104054/154475436-fe77637e-383f-4480-a701-c0d39db1e381.png)

**Comment by Alanscut** [comment]
@jinbiaode 
点击datepicker后popover被关闭这个问题，可以给datepicker添加`:teleported="false"`
![image](https://user-images.githubusercontent.com/21104054/154479399-04cf9754-9dee-4ab4-b07b-5569d82e3679.png)

**Comment by jinbiaode** [comment]
> @jinbiaode 点击datepicker后popover被关闭这个问题，可以给datepicker添加`:teleported="false"` ![image](https://user-images.githubusercontent.com/21104054/154479399-04cf9754-9dee-4ab4-b07b-5569d82e3679.png)

:teleported="false"    可以解决，非常感谢，但是文档上没有这个属性，请记录下及时更新下文档。辛苦了！

**Comment by Alanscut** [comment]
> > @jinbiaode 点击datepicker后popover被关闭这个问题，可以给datepicker添加`:teleported="false"` ![image](https://user-images.githubusercontent.com/21104054/154479399-04cf9754-9dee-4ab4-b07b-5569d82e3679.png)
> 
> :teleported="false" 可以解决，非常感谢，但是文档上没有这个属性，请记录下及时更新下文档。辛苦了！

https://github.com/element-plus/element-plus/pull/6137
已经提交pr了
