### ISSUE TITLE
[Feature Request] How can I blur all element or focus one element by typescript?

### ISSUE THREAD

**Issue by MoConWu** [element-plus/element-plus#6099]
### Existing Component
Yes

### Component Name
All Elemnt

### Description
How can I blur all element or focus one element by typescript?
I use like:
``` ts
document.getElementById("my_button")?.focus();
```
But It's not work on element-plus.

I also want to close the pop panel, Like the el-select or el-select-v2 pop panel.
Can I take the inactive to close the pop panel by typescript?

**Comment by tolking** [comment]
By `ref` [Link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgcmVmPVwic2VsZWN0UmVmXCJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0XCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gIC8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwib3BlblwiPm9wZW48L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJmb2N1c1wiPmZvY3VzPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiYmx1clwiPmJsdXI8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFNlbGVjdFYyIGFzIFNlbGVjdFYySW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5jb25zdCBpbml0aWFscyA9IFsnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaiddXG5cbmNvbnN0IHNlbGVjdFJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIFNlbGVjdFYySW5zdGFuY2U+PigpXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoXG4gIEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gICAgdmFsdWU6IGBPcHRpb24gJHtpZHggKyAxfWAsXG4gICAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxuICB9KSlcbilcblxuZnVuY3Rpb24gb3BlbigpIHtcbiAgc2VsZWN0UmVmLnZhbHVlIS5leHBhbmRlZCA9IHRydWVcbn1cblxuZnVuY3Rpb24gZm9jdXMoKSB7XG4gIChzZWxlY3RSZWYudmFsdWU/LmlucHV0UmVmIGFzIHVua25vd24gYXMgSFRNTElucHV0RWxlbWVudCkuZm9jdXMoKVxufVxuXG5mdW5jdGlvbiBibHVyKCkge1xuICAoc2VsZWN0UmVmLnZhbHVlPy5pbnB1dFJlZiBhcyB1bmtub3duIGFzIEhUTUxJbnB1dEVsZW1lbnQpLmJsdXIoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

At present, the types of some components need to be further improved.
