### ISSUE TITLE
[Bug Report] popconfirm is very slow

### ISSUE THREAD

**Issue by Pentadome** [element-plus/element-plus#6101]
### Element Plus version
2.0.2

### OS/Browsers version
chrome

### Vue version
3.2.31

### Reproduction Link
`https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wY29uZmlybVxuICAgICAgICAgICAgICAgICB2LWZvcj1cImkgaW4gNTAwXCJcbiAgICBjb25maXJtLWJ1dHRvbi10ZXh0PVwiT0tcIlxuICAgIGNhbmNlbC1idXR0b24tdGV4dD1cIk5vLCBUaGFua3NcIlxuICAgIDppY29uPVwiSW5mb0ZpbGxlZFwiXG4gICAgaWNvbi1jb2xvcj1cInJlZFwiXG4gICAgdGl0bGU9XCJBcmUgeW91IHN1cmUgdG8gZGVsZXRlIHRoaXM/XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcGNvbmZpcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgSW5mb0ZpbGxlZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=`

### Steps to reproduce
Scroll up or down

### What is Expected?
Good performance

### What is actually happening?
Bad performance

**Comment by Pentadome** [comment]
Why close?

**Comment by f-jm** [comment]
我也碰到类似问题，问题很明显啊，dropdown/pop confirm/popover 这几个组件都是这样的，含有大量计算定位，性能低下是必然的

**Comment by Pentadome** [comment]
que pasa?

**Comment by Pentadome** [comment]
this fixes it: 

![image](https://user-images.githubusercontent.com/16758470/154685294-9edcb47e-d3b1-4178-9797-d9f937439f0e.png)

**Comment by msidolphin** [comment]
We added the persistent property to destroy the component when it is inactivated
