### ISSUE TITLE
[Bug Report] Build Failing when using 'Auto import'

### ISSUE THREAD

**Issue by Manu-Geotourist** [element-plus/element-plus#6102]
### Element Plus version
1.3.0-beta.10

### OS/Browsers version
Mac

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/iamkun/ods20k7t/

### Steps to reproduce
I am using vue cli and trying to use auto import as per documentation.
https://element-plus.org/en-US/guide/quickstart.html#on-demand-import

My vue.config.js 

const AutoImport = require("unplugin-auto-import/webpack");
const Components = require("unplugin-vue-components/webpack");
const { ElementPlusResolver } = require("unplugin-vue-components/resolvers");

module.exports = {
  configureWebpack: {
    plugins: [
      AutoImport({
        resolvers: [ElementPlusResolver()],
      }),
      Components({
        resolvers: [ElementPlusResolver()],
        directoryAsNamespace: true,
      }),
    ],
  },
};

When I am building the project , It's failing with below errors.

This dependency was not found:

* element-plus/es/components/loading-directive/style/css in ./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--36-0!./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--37-0!./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader-v16/dist/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/CreateHome/index.vue?vue&type=template&id=1fbfa276, ./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--36-0!./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--37-0!./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader-v16/dist/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/CreateTour/NewLanguagePopUp.vue?vue&type=template&id=251d943f and 9 others

To install it, you can run: npm install --save element-plus/es/components/loading-directive/style/css

Is there anything I am doing wrong?

### What is Expected?
Build should run successfully

### What is actually happening?
Build Failed

**Comment by Manu-Geotourist** [comment]
@emojiiii  @sxzz  @JeremyWuuuuu

**Comment by sxzz** [comment]
https://github.com/antfu/unplugin-auto-import/issues/116

**Comment by Manu-Geotourist** [comment]
@sxzz , thanks for pointing to the open issue. Any work around possible ?

**Comment by sxzz** [comment]
Use Vite/Rollup or just use `unplugin-vue-components` only.

**Comment by sxzz** [comment]
Duplicate of #4855
