### ISSUE TITLE
[Feature Request] 作者你好，我克隆一份element plus源码进行二次开发 搭建自己公司的组件库，启动项目后 我发现没有中文文档，我该如何操作，才能生成中文文档呢

### ISSUE THREAD

**Issue by SuperHanMr** [element-plus/element-plus#6109]
### Existing Component
No

### Component Name
dev

### Description
mac

**Comment by sxzz** [comment]
https://crowdin.com/project/element-plus

**Comment by wuduo0701** [comment]
你好，请问这个该如何操作呢？是需要下载简体中文的部分替换嘛？

**Comment by sxzz** [comment]
或者直接到这下载 https://github.com/element-plus/element-plus/tree/gh-pages/zh-CN

**Comment by wuduo0701** [comment]
> 或者直接到这下载 https://github.com/element-plus/element-plus/tree/gh-pages/zh-CN

感谢
