### ISSUE TITLE
[Bug Report] ElLoading.service({ fullscreen: false }) is not single

### ISSUE THREAD

**Issue by BigPengZai** [element-plus/element-plus#6118]
### Element Plus version
2.0.2

### OS/Browsers version
版本 97.0.4692.71（正式版本） (arm64)

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0pcuu

### Steps to reproduce
```
const loadingInstance1 = ElLoading.service({ fullscreen: true })
const loadingInstance2 = ElLoading.service({ fullscreen: true })
console.log(loadingInstance1 === loadingInstance2) // false
```

### What is Expected?
true

### What is actually happening?
false

**Comment by sxzz** [comment]
请勿重复发相同的issue

**Comment by sxzz** [comment]
Duplicated of #5182
