### ISSUE TITLE
[Bug Report] [el-select] margin-left is broken when multiple

### ISSUE THREAD

**Issue by Eiryyy** [element-plus/element-plus#6120]
### Element Plus version
2.0.2

### OS/Browsers version
macOS Monterey / Chrome 98.0.4758.102

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-1j2kos?file=/src/App.vue

### Steps to reproduce
You can check official document for this issue
https://element-plus.org/en-US/component/select.html#basic-multiple-select

### What is Expected?
Should look the same as 2.0.1.

### What is actually happening?
Missing required margin-left.

<img width="237" alt="スクリーンショット 2022-02-17 15 08 05" src="https://user-images.githubusercontent.com/2590137/154415735-eb26514d-fc45-4e09-aa96-fbe66eb818c5.png">

**Comment by btea** [comment]
fixed #6037

**Comment by xiaoxian521** [comment]
It has been fixed, waiting for the next version to be released
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/44761321/154422436-2e100ceb-c358-4afa-b37e-c4a5da707b27.png">
