### ISSUE TITLE
[Bug Report]  TimePicker Click to cancel the bug

### ISSUE THREAD

**Issue by 347830076** [element-plus/element-plus#6123]
### Element Plus version
2.0.1

### OS/Browsers version
all

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/vpthLksz/4/

### Steps to reproduce
Just look at the example on the official website https://element-plus.org/#/zh -CN/component/time-picker

Change time and confirm
Open the change panel again and click Cancel

### What is Expected?
After clicking cancel, the time does not change

### What is actually happening?
After clicking cancel, the time becomes the initial value, and element 2.0 does not have this bug

**Comment by sxzz** [comment]
Fixed via #6735
