### ISSUE TITLE
[Bug Report] el-tooltip组件append-to参数无效，是否内部参数为传递给el-tooltip-content组件

### ISSUE THREAD

**Issue by zhengyangkang** [element-plus/element-plus#6125]
### Element Plus version
2.0.1

### OS/Browsers version
chrome 98.0.4758.80

### Vue version
3.2.16

### Reproduction Link
https://jsfiddle.net/1df3yuhs/

### Steps to reproduce
el-tooltip组件设置append-to属性值为#app，鼠标移动至按钮上面

### What is Expected?
内容显示在#app节点下面

### What is actually happening?
内容显示在body节点下面，content.vue文件未接收到appendTo参数

**Comment by emojiiii** [comment]
please see the [docs/teleported](https://element-plus.org/zh-CN/component/tooltip.html#%E5%B1%9E%E6%80%A7)

**Comment by msidolphin** [comment]
fix #6146
