### ISSUE TITLE
[Bug Report] Input word limit value not correct 

### ISSUE THREAD

**Issue by asdjgfr** [element-plus/element-plus#6127]
### Element Plus version
2.0.2

### OS/Browsers version
Windows 11
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/asdjgfr/pen/LYOeZGK

### Steps to reproduce
paste or input some emoji such as 👩‍👩‍👧‍👧 or 🤰🏻

### What is Expected?
👩‍👩‍👧‍👧 or 🤰🏻 should be calculated as 1

### What is actually happening?
👩‍👩‍👧‍👧 compute as 7
🤰🏻 compute as 2

![image](https://user-images.githubusercontent.com/23442840/154446919-f735760f-2825-4fcc-901a-f31be2782f74.png)

**Comment by bastarder** [comment]
😄！！！
i try `"👩‍👩‍👧‍👧".length` in chrome , get `11`

**Comment by asdjgfr** [comment]
> 😄！！！ i try `"👩‍👩‍👧‍👧".length` in chrome , get `11`

I have already created a [new pull request](https://github.com/element-plus/element-plus/pull/6130) to fixed and test it .

**Comment by sxzz** [comment]
I think it's by design. `maxlength` attribute also has the same effect.
WDYT /cc @JeremyWuuuuu

**Comment by asdjgfr** [comment]
> I think it's by design. `maxlength` attribute also has the same effect. WDYT /cc @JeremyWuuuuu

When I set maxlength to 10 and show-word-limit, input `👩‍👩‍👧‍👧` *(four people)* but got `👩‍👩‍👧‍` *(three people)* and `6 / 10` ,also only one more character can be inserted. It makes me confused. I saw another library, [ Ant Design Vue](https://next.antdv.com/index) didn't have `show-word-limit`, [Vuetify](https://vuetifyjs.com/en/) all props not supported 😂.

**Comment by JeremyWuuuuu** [comment]
@sxzz @asdjgfr I think we should take @asdjgfr's proposal, since the emoji '👩‍👩‍👧‍' is constructed by
`['👩', '‍', '👩', '‍', '👧', '‍']`, the `''` is a special symbol `\uD83D` which in fact takes 1 character length, so emoji '👩‍👩‍👧‍' should be length of `5` instead of ` '👩‍👩‍👧‍'.length === 8`.

**Comment by asdjgfr** [comment]
Can we merge this [pr](https://github.com/element-plus/element-plus/pull/6130) to close this issue? I have some problems in my project with this issue😂
@JeremyWuuuuu

**Comment by asdjgfr** [comment]
> IMHO, I think the behavior should be consistent with JavaScript.
> 
> * `'👩‍👩‍👧‍👧'.length === 11`
> * `'🤰🏻'.length === 4`

But for users, it can be typed like Chinese characters, also delete it with only one press.

**Comment by plainheart** [comment]
FYI, I think it's correct behavior. Even though we change the rule to measure the length of the string that contains emoji characters to make the result expected to us, it's very possible that the database can't store the string as expected length. They just look like "**one character**". See also https://github.com/element-plus/element-plus/pull/6588#issuecomment-1066104085.

**Comment by zt123123** [comment]
> 
@plainheart 
我觉得你说的有道理，考虑很全面。 这个问题不做处理也无伤大雅。从实际业务场景来看，输入表情内容场景不多，至少应该优先保证数据存储没问题，后端程序不出错，前端follw规范就行了

**Comment by asdjgfr** [comment]
closed. My opinion https://github.com/element-plus/element-plus/pull/6588#issuecomment-1066310927
