### ISSUE TITLE
[Bug Report] ElTableColumn 设置width，在浏览器视窗大小发生变化的时候，鼠标悬浮到table上会出现横向滚动条。

### ISSUE THREAD

**Issue by JimFirst** [element-plus/element-plus#6139]
### Element Plus version
2.0.2

### OS/Browsers version
chrome  98.0.4758.102

### Vue version
3.2.31

### Reproduction Link
https://element-plus.gitee.io/zh-CN/component/table.html#%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC

### Steps to reproduce
沙盒可能版本不对无法复现
1. 打开官方示例 https://element-plus.gitee.io/zh-CN/component/table.html#%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC
2. 调整浏览器视窗大小，鼠标悬浮到table上，会出现横向滚动条，而且无法拖动

### What is Expected?
鼠标悬浮到table上，不应该出现横向滚动条
![image](https://user-images.githubusercontent.com/19401131/154603716-6725924e-d486-4fde-8468-60ea1d64d02f.png)

### What is actually happening?
鼠标悬浮到table上，出现了横向滚动条

**Comment by liujiangde** [comment]
这个怎么感觉不是bug，，你这个调整了浏览器视窗大小之后，整张表的会自适应变小。由于你给其中一个设置了固定列宽，所以没法全部展示该列，表自然就出现了这个滚动条。
ps：个人看法，说的不对别喷。

**Comment by msidolphin** [comment]
> 这个怎么感觉不是bug，，你这个调整了浏览器视窗大小之后，整张表的会自适应变小。由于你给其中一个设置了固定列宽，所以没法全部展示该列，表自然就出现了这个滚动条。 ps：个人看法，说的不对别喷。

的确是bug，自适应列的列宽会计算错误
