### ISSUE TITLE
Changing locale lang not working

### ISSUE THREAD

**Issue by denyncrawford** [element-plus/element-plus#614]
I'm trying to change the lang to spanish but it doesn't seem to work. The datepicker calendar is loaded on English still.

![2](https://user-images.githubusercontent.com/28849055/99398256-f12da900-28c2-11eb-986e-15bdb42d4bf9.png)

As you can see, the script is proerly loaded at the resources tab on left, but nothing change.

I'm using Rollup, so this is my `rollup.config.js` where I'm replacing the module:

![code](https://user-images.githubusercontent.com/28849055/99398714-8335b180-28c3-11eb-95b2-0efd2270a789.png)

And this is my `main.js `file:

![code](https://user-images.githubusercontent.com/28849055/99399384-5c2baf80-28c4-11eb-9580-80a365c4509b.png)

As you can see, I'm importing the locale lang with both of the methods, and it is loaded on the app...

I'm I doing something wrong? 

And as I issued [here](https://github.com/element-plus/element-plus/issues/606) it is not rendering the content on the date picker, but in the component data it does (I mention it again cause is a datepicker related thing(? ).

**Comment by yumemi-omi** [comment]
I faced the same issue. Once I updated `1.0.1-alpha.15`, resolved an issue.
So it might be worth checking `element-plus` version you use.

**Comment by JeremyWuuuuu** [comment]
I believe that we have some deficient in the locale system. We will fix that ASAP

**Comment by denyncrawford** [comment]
@yumemi-omi Nice, I updated to `1.0.1-alpha.15` and the locale work just fine. So, @JeremyWuuuuu that was my fault, but it is still not rendering de date on the view :/

**Comment by JeremyWuuuuu** [comment]
I will look into it tomorrow, sorry for kept you waiting. It's kinda late😂

**Comment by denyncrawford** [comment]
@JeremyWuuuuu Don't worry hahaha. Thank u!

**Comment by zazzaz** [comment]
The locale issue should have been fixed in `1.0.1-alpha.15`.

As for locale related to date time picker and calendar, there's a slight difference than Element 2.0 that we use Day.js's locale. This could make the translation much more accurate and supports more locales out of the box.

Please try the code below:
```
// in your index.js 

import dayjs from 'dayjs' // if you installed element plus, you will have dayjs as a dependency by default
import 'dayjs/locale/de' // import the locale you want 
dayjs.locale('de') // use locale globally
```

Ref: https://day.js.org/docs/en/i18n/i18n

**Comment by JeremyWuuuuu** [comment]
@zazzaz updates?

**Comment by denyncrawford** [comment]
I'm using the 1.0.1-alpha.15 and it works prefectly. Thanks guys! Closing this issue.
