### ISSUE TITLE
[Bug Report] ElLoading.service spinner bug

### ISSUE THREAD

**Issue by lxbnet** [element-plus/element-plus#6141]
### Element Plus version
2.0.2

### OS/Browsers version
win10/chrome 98

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/lkr/pen/PoOQoqP

### Steps to reproduce
ElLoading.service({
     fullscreen: true,
     spinner: 'custom-loading-image',
     text: '加载中...',
     customClass: 'custom-loading',
})

### What is Expected?
 希望spinner能真正的做到自定义加载图标类名，不然很难自定义loading图标

希望效果：
`<svg class="custom-loading-image" viewBox="25 25 50 50"></svg>
`
### What is actually happening?
spinner作用在一个svg上，并将这个svg的innerHTML赋值为spinner的值。

实际效果：
`<svg class="circular" viewBox="25 25 50 50">custom-loading-image</svg>
`

**Comment by btea** [comment]
`spinner`属性值应该传入html字符串，参考[这里](https://element-plus.org/zh-CN/component/loading.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A0%E8%BD%BD%E4%B8%AD%E7%BB%84%E4%BB%B6%E5%86%85%E5%AE%B9).
