### ISSUE TITLE
[Bug Report] 自动导入和国际化同时使用，打包后体积增大

### ISSUE THREAD

**Issue by ALI1416** [element-plus/element-plus#6144]
### Element Plus version
2.0.2

### OS/Browsers version
windows

### Vue version
3.2.25

### Steps to reproduce
vite.config.js 配置
```js
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import {ElementPlusResolver} from 'unplugin-vue-components/resolvers'

export default defineConfig({
  plugins: [vue(),
    AutoImport({
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      resolvers: [ElementPlusResolver()],
    }),
  ]
})
```
main.js 配置
```js
import {createApp} from 'vue'
import App from './App.vue'
import ElementPlus from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'

createApp(App).use(ElementPlus, {locale: zhCn,}).mount('#app')
```

### What is Expected?
打包后体积不应该这么大

### What is actually happening?
只使用自动导入打包结果
![截图20220218153113189](https://user-images.githubusercontent.com/39152510/154639781-93bee29f-eba6-483b-b235-b9e2fbca6666.png)
使用自动导入和国际化打包结果
![截图20220218152633724](https://user-images.githubusercontent.com/39152510/154639816-66664ea5-968a-420e-82c8-85fb4fea53d8.png)

**Comment by ealldy** [comment]
我在使用自动导入时，使用message时会样式错乱，且v-loading指令无法使用，无奈换了全量导入。

**Comment by sxzz** [comment]
因为你全量导入了。按需导入需要使用 `config-provider` 设置 locale
