### ISSUE TITLE
[Bug Report] el-table-column使用插槽放置el-popover会造成页面异常卡顿

### ISSUE THREAD

**Issue by itskaiway** [element-plus/element-plus#6152]
### Element Plus version
2.0.2

### OS/Browsers version
Chrome： 98.0.4758.102 

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/elementplus-tps9q4?file=/src/App.vue

### Steps to reproduce

  1.打开codesandbox链接，遇到构建错误请刷新查看

  2.模拟数据量增加，请连续点击Add item

  3.会明显发现拖动的时候异常卡顿，如对应真实环境分页50条/页，已经没法操作

### What is Expected?
卡顿消失

### What is actually happening?
数据量大的时候卡顿非常明显，我看了下Performance的性能摘要，发现Rendering的时间少则300ms 多则接近快一秒，而且滚动条连续拖动触发scroll event会频繁调用Forceupdate与之对应则是FunctionforceUpdate @ createPopper.js:142:40 看起来好像是el-popover的锅？

**Comment by Pentadome** [comment]
I used google translate so i am not sure, but this seems related: https://github.com/element-plus/element-plus/issues/6101

**Comment by msidolphin** [comment]
When using popover in table,  i recommend mount them to the body

**Comment by itskaiway** [comment]
> ```
> teleported
> ```

Thank you for fixing this issue, would you consider adding persistent options for other components that have popper-options properties?  (e.g. Dropdown, Popconfirm)

**Comment by weidehai** [comment]
@msidolphin i think we can optimize the popper preformance with disable eventlistener when invisible according to the official use case
