### ISSUE TITLE
[Feature Request] element提issue时候, jsFiddle的模板不太好

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#6163]
### Existing Component
No

### Component Name
1

### Description
官网的demo是ts的, 但是给的模板, 全是js的, 期望官网给出选择js, 或者统一用ts

**Comment by sxzz** [comment]
http://issue.element-plus.org/ 目前可以尝试使用来提 issue

**Comment by a15218378694** [comment]
> https://issue.element-plus.org/ 目前可以尝试使用来提 issue

是指jsFiddle写代码的模板

**Comment by sxzz** [comment]
@a15218378694 try https://play.element-plus.org/

**Comment by a15218378694** [comment]
> @a15218378694 try https://play.element-plus.org/

感谢
