### ISSUE TITLE
[Bug Report] element-plus 按需导入ElMessage等会报错model name找不到，import后 css样式又丢失，然后main.ts导入css 又是完整导入。希望能解决这个坑

### ISSUE THREAD

**Issue by hhzx** [element-plus/element-plus#6179]
### Element Plus version
2.0.2

### OS/Browsers version
chrome

### Vue version
3.2.31

### Reproduction Link
https://elementui.github.io/

### Steps to reproduce
按需导入 然后使用elmessage等消息类

### What is Expected?
希望这个问题没有了，新手解决这个问题花了半小时 不容易啊

### What is actually happening?
本来想省时间 因为有各种坑多花了时间 适得其反

**Comment by hhzx** [comment]
按需导入方式严格按照官方文档：https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5

**Comment by msidolphin** [comment]
API组件需要自行导入，文档中有提及

**Comment by TuffyLiu** [comment]
> API组件需要自行导入，文档中有提及

按照文档自行导入ElMessage样式后，又把我的主题覆盖了，变成了默认的主题。

**Comment by huangcs427** [comment]
> 按照文档自行导入ElMessage样式后，又把我的主题覆盖了，变成了默认的主题。
可以在main.ts中手动导入样式
```
import 'element-plus/theme-chalk/el-message.css'
```
然后在你用的组件手动引入ElMessage
```
import {  ElMessage } from 'element-plus'
```

参考: https://github.com/element-plus/element-plus/issues/6501
