### ISSUE TITLE
[Feature Request] should it prevent scroll default behavior for el-scrollbar when it already scrolled to the edge?

### ISSUE THREAD

**Issue by weidehai** [element-plus/element-plus#6181]
### Existing Component
Yes

### Component Name
el-scrollbar

### Description
i will provide a short video below

https://user-images.githubusercontent.com/25458528/154844467-51d2b4eb-9fe6-481c-b4a6-31ed2e219af7.mp4

i think this propose can improve user experience

**Comment by msidolphin** [comment]
User experience is too subjective, keep the same experience as native
