### ISSUE TITLE
[Feature Request] 请问可内网部署的中文文档库在哪里？因办公地与互联网物理隔离比较麻烦- -！

### ISSUE THREAD

**Issue by realxumai** [element-plus/element-plus#6182]
### Existing Component
No

### Component Name
Element Plus

### Description
请问可内网部署的中文文档库在哪里？因办公地与互联网物理隔离比较麻烦- -！
在GitHub一直找不到中文文档库，谁能指点下

**Comment by shuaiFengW** [comment]
同问

**Comment by weidehai** [comment]
文档在crowdin翻译的，可以到官网下载
![image](https://user-images.githubusercontent.com/25458528/154848157-3b3b243f-4bd3-4293-80f1-0c55a5de664e.png)

**Comment by iamkun** [comment]
Download the website from `gh-pages` branch directly.

https://github.com/element-plus/element-plus/tree/gh-pages
