### ISSUE TITLE
[Bug Report] el-rate allow-half的问题

### ISSUE THREAD

**Issue by zc-write-code** [element-plus/element-plus#6188]
### Element Plus version
2.0.2

### OS/Browsers version
版本	Windows 10 专业版 版本号	21H1 安装日期	‎2021/‎6/‎29 操作系统内部版本	19043.1526 体验	Windows Feature Experience Pack 120.2212.4170.0/chrome 96.0.4664.93

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/zengcheng/pen/JjOLeKZ

### Steps to reproduce
进入https://element-plus.gitee.io/zh-CN/component/rate.html#%E5%B0%BA%E5%AF%B8  找到允许半星，鼠标放上去会显示一个没选中的，一个半星的，是否是如此设计的？

### What is Expected?
希望只有半星出现，不会出现未选择的

### What is actually happening?
半星出现和未选择的星同时出现

**Comment by btea** [comment]
fixed #6076 . Please wait for the new version to be released.
