### ISSUE TITLE
[Bug Report] element-loading-text reactive variable not work

### ISSUE THREAD

**Issue by Onlylonger** [element-plus/element-plus#6189]
### Element Plus version
2.0.2

### OS/Browsers version
Mac 11.4  / Chrome 98.0.4758.102(arm64)

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/09owdpvt/3/

### Steps to reproduce
- click button

### What is Expected?
loading text ui change

### What is actually happening?
not change

**Comment by Wiensss** [comment]
maybe you ca fix it quickly like this:
```ts
// in triggering event
loading.value = false
loadingText.value = 'newValue'
nextTick(() => {
  loading.value = true
})
```

**Comment by Onlylonger** [comment]
>

**Comment by sxzz** [comment]
Try `v-loading="{text:loadingText}"`

**Comment by Onlylonger** [comment]
https://jsfiddle.net/qawt1z38/14/

**Comment by sxzz** [comment]
@Onlylonger https://jsfiddle.net/ze9m6djk/4/

**Comment by Onlylonger** [comment]
> @Onlylonger https://jsfiddle.net/ze9m6djk/4/

ok.
