### ISSUE TITLE
[Bug Report] Element Plus Playground 对浏览器有什么要求吗？一片报错

### ISSUE THREAD

**Issue by microkof** [element-plus/element-plus#6200]
### Element Plus version
2.0.2

### OS/Browsers version
Window 10 / Chrome 86

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/aaa/pen/bbb

### Steps to reproduce
使用 Chrome 86打开官方手册里的随意一个Element Plus Playground (v1.5.1, repl v1.0.0)，随意一个都行。

然后看控制台，有如下报错：

Access to script at 'about:srcdoc?0' from origin 'https://element-plus.run' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

GET about:srcdoc?0 net::ERR_FAILED

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: about:srcdoc?0

Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".
    at handle_message (VM136 about:srcdoc:58)

Uncaught SyntaxError: Unexpected reserved word
    at handle_message (VM136 about:srcdoc:58)

undefined:7 Uncaught (in promise) SyntaxError: Unexpected reserved word

### What is Expected?
正常使用

### What is actually happening?
有一堆报错

**Comment by sxzz** [comment]
请参考network，是否有文件加载失败。或升级到最新 Chrome 98
