### ISSUE TITLE
[Bug Report] 在flex布局下，外部div宽度减小时表格宽度不会随之减小

### ISSUE THREAD

**Issue by YornQiu** [element-plus/element-plus#6202]
### Element Plus version
2.0.2

### OS/Browsers version
chrome98

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/YornQiu/pen/abVYxoX

### Steps to reproduce
1.左侧固定宽度右列flex:1的边栏布局

2.右侧渲染el-table

3.改变左侧宽度

### What is Expected?
右侧div宽度缩小时表格宽度随之减小

### What is actually happening?
表格宽度没有变化，右侧div出现横向滚动条

**Comment by YornQiu** [comment]
这个bug自element-ui就已经存在了，且只在flex布局下出现，引起bug的原因可能与表格宽度的计算方式有关

**Comment by tolking** [comment]
你需要给 main 一个宽度

``` diff
main {
+   width: calc(100% - 300px);
}
```

**Comment by YornQiu** [comment]
> 你需要给 main 一个宽度
> 
> ```diff
> main {
> +   width: calc(100% - 300px);
> }
> ```

这个方法的确有效，目前也是这样解决的。
不过在一些更复杂的布局下，比如左侧的宽度不是固定的，就不好给右侧的main设置宽度，这种情况要怎么解决呢？

**Comment by pungfen** [comment]
main { flex: 1; width: 0 }
