### ISSUE TITLE
[Bug Report] Utility classes for hiding elements: resolution equal to breakpoints are problematic

### ISSUE THREAD

**Issue by amaury-hanser** [element-plus/element-plus#6205]
### Element Plus version
2.0.2

### OS/Browsers version
Ubuntu / Chrome 98.0.4758.80

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/mwL8vaxj/1/

### Steps to reproduce
- Import 'element-plus/theme-chalk/display.css'
- Create two html elements
- Give them classes to hide / show them, one above and one under a specific breakpoint

*Example:*  
```
      <div class="hidden-xs-only">01</div>
      <div class="hidden-sm-and-up">02</div>
```

### What is Expected?
I would expect to see:
- 01 if I'm strictly over `768px`
- 02 if I'm at or under `768px`

### What is actually happening?
If my screen resolution is equal to `768px` both elements are hidden.

**Comment by Alanscut** [comment]
hidden-xs-only: hidden when the viewport is <768px;
hidden-sm-and-up: hide when viewport is ≥768px;

**Comment by amaury-hanser** [comment]
Looks good to me! 👍
