### ISSUE TITLE
[Bug Report] In nuxt3, report an error `dayjs__default.default(...).locale(...).add is not a function`

### ISSUE THREAD

**Issue by Cabbages** [element-plus/element-plus#6206]
### Element Plus version
2.0.2

### OS/Browsers version
Windows10 20H2 / chrome  96.0.4664.45

### Vue version
3.2.31

### Reproduction Link
https://stackblitz.com/github/Cabbages/element-plus-nuxt-starter

### Steps to reproduce
1. `plugins/element-plus.ts`,  add `import locale from 'element-plus/lib/locale/lang/zh-cn'`
2. `components/Examples` add `<el-date-picker v-model="value" type="daterange" placeholder="选择日期"></el-date-picker>`
3. Reload the page

### What is Expected?
Reloading a page with 'el-date-picker' in Nuxt3 does not report an error.

### What is actually happening?
The above error causes the program to freeze

**Comment by xiaoxian521** [comment]
you can try:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/44761321/155051427-6ed48e13-f91a-4227-aa3b-06f6baec227f.png">
