### ISSUE TITLE
[Bug Report] el-form-item slot label 放入el-upload组件且trigger为span标签，点击上传选择文件第一遍无法上传，且会自动打开选择文件选择

### ISSUE THREAD

**Issue by zhouquan123** [element-plus/element-plus#6218]
### Element Plus version
2.0.2

### OS/Browsers version
google

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/signNameZhou/5831egwb/3/

### Steps to reproduce
点击Click to upload选择文件或者取消选择

### What is Expected?
正确的被关闭或上传文件

### What is actually happening?
第一次无法关闭或上传文件

**Comment by sxzz** [comment]
Please provide a latest reproduction here.
https://element-plus.run/
