### ISSUE TITLE
[Bug Report] The question about image and table

### ISSUE THREAD

**Issue by zhn4** [element-plus/element-plus#6219]
### Element Plus version
2.0.2

### OS/Browsers version
win 10 / chrome 98.0.4758.102

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/pvge2umc/

### Steps to reproduce
1.click the image  
2.Image covered by table

1.点击图片  
2.图片浏览器被表格覆盖到

![element-plus-iamge-viewer-bug-3](https://user-images.githubusercontent.com/11404946/155100402-6508f4ec-a01b-43c2-b306-1917eb1bfeb0.gif)

### What is Expected?
image viewer diaplay perfect

图片浏览器被表格阻挡

### What is actually happening?
image viewer does not look perfect

看起来不完美

**Comment by msidolphin** [comment]
在表格中使用请将`preview-teleported`设置为`true`
