### ISSUE TITLE
[Bug Report] 按需加载配置下，无法加载el-table组件内部的el-scrollbar。

### ISSUE THREAD

**Issue by jijieoo** [element-plus/element-plus#6220]
### Element Plus version
2.0.2

### OS/Browsers version
chrome 98.0.4758.102

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/interesting-spence-81p1qd?file=/src/App.vue

### Steps to reproduce
按需加载
引入el-table设置height，滚动条不显示。

el-scrollbar组件未加载。引入el-scrollbar组件后，设置了height的el-table组件滚动条正常显示。

### What is Expected?
按需加载，自动加载组件内部使用的组件。

### What is actually happening?
按需加载，未自动加载组件内部使用的组件。

**Comment by msidolphin** [comment]
fix #6045
