### ISSUE TITLE
[Bug Report] el-dialog not working in nuxt3

### ISSUE THREAD

**Issue by Beanster199** [element-plus/element-plus#6233]
### Element Plus version
2.0.2

### OS/Browsers version
Irrelevant

### Vue version
3.2.31

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-q7pamn?file=components/Navbar.vue

### Steps to reproduce
Click Open Dialog Button

### What is Expected?
To Open Dialog on screen

### What is actually happening?
nothing. i saw it add's `.el-popup-parent--hidden` to body but no Dialog is render

**Comment by xiaoxian521** [comment]
Please try this project
https://github.com/element-plus/element-plus-nuxt-starter

**Comment by Beanster199** [comment]
Getting same issue with cloning base `element-plus-nuxt-starter` and calling the dialog

**Comment by xiaoxian521** [comment]
set `append-to-body`
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/44761321/155258705-1305b7a1-fb48-4f82-873c-b5518e503dcf.png">

**Comment by Beanster199** [comment]
Got it working! Thank you so much!

**Comment by msidolphin** [comment]
You can temporarily wrap it in ClientOnly, we will focus on this issue
```vue
<ClientOnly>
    <el-dialog v-model="state.dialogVisible" title="Test">
      <div class="custom">Hello</div>
    </el-dialog>
  </ClientOnly>
```

**Comment by leochen-g** [comment]
```
import { placements } from '@popperjs/core';
         ^^^^^^^^^^
SyntaxError: Named export 'placements' not found. The requested module '@popperjs/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

```
when i use el-dialog

**Comment by avral** [comment]
@leochen-g same here

**Comment by Codefans-fan** [comment]
@leochen-g  same

**Comment by ilovesusu** [comment]
https://github.com/element-plus/element-plus-nuxt-starter/issues/5#issuecomment-1104023159

**Comment by revenkroz** [comment]
I had the same error:
```shell
import { placements } from '@popperjs/core';
         ^^^^^^^^^^
SyntaxError: Named export 'placements' not found. The requested module '@popperjs/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

So, I checked the [package.json](https://github.com/element-plus/element-plus/blob/281249c1134599f182ad1e9f9cca485056c13262/package.json#L51) of the `element-plus` and added the same string to my `package.json`.
```json
 "@popperjs/core": "npm:@sxzz/popperjs-es@^2.11.6",
```

Also before running `npm install` you should remove all entries from the lock-file where the original `@popperjs/core` has been used (or just remove your lock-file). Then run pnpm/yarn `install`.

**Comment by phenomenal-hardy** [comment]
> set `append-to-body` <img alt="image" width="1116" src="https://user-images.githubusercontent.com/44761321/155258705-1305b7a1-fb48-4f82-873c-b5518e503dcf.png">

THANK YOU
