### ISSUE TITLE
[Feature Request] 请让表格组件支持多列排序功能 Please table component support multi-column sorting

### ISSUE THREAD

**Issue by WhiteCoffee9834** [element-plus/element-plus#6235]
### Existing Component
是

### Component Name
Table

### Description
有时候往往有这样的需求,一个表格能够同时排序多列来提升用户体验.

有些网站支持用户按住 Shift, 然后就可以点击多个表格的表头实现多列排序

**Comment by wangping1511** [comment]
https://github.com/element-plus/element-plus/issues/5024#issuecomment-1138558442

如果你是需要后端排序可能会遇到这个问题，可以尝试这样去做
