### ISSUE TITLE
[Bug Report] el-date-picker 组件的 change 事件无法触发

### ISSUE THREAD

**Issue by luuunnn** [element-plus/element-plus#6240]
### Element Plus version
2.0.1

### OS/Browsers version
ms edge latest

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/Luuuuuu/pen/abVKywP

### Steps to reproduce
https://codepen.io/Luuuuuu/pen/abVKywP

### What is Expected?
通过触发 change 事件,改变 date-picker 的值

### What is actually happening?
当使用 v-bind:model-value 与 v-on:change 组合后,无法触发 change 事件,导致无法改变 date-picker 的值.

**Comment by emojiiii** [comment]
try to change `@change`  to `@update:model-value`

**Comment by luuunnn** [comment]
再codePen中尝试了一下,的确可以.不过既然提供了change事件,为何还一定要使用vue的update事件呢?

**Comment by emojiiii** [comment]
> 在 codePen 中尝试了一下,的确可以.不过既然提供了 change 事件,为何还一定要使用 vue 的 update 事件呢?

因为你没有使用`v-model`，是无法触发 `change`的， `change`代表的是你的选中值发生更改的意思，但是在这里你只是选中，值没有发生更改

**Comment by luuunnn** [comment]
> > 在 codePen 中尝试了一下,的确可以.不过既然提供了 change 事件,为何还一定要使用 vue 的 update 事件呢?
> 
> 因为你没有使用`v-model`，是无法触发 `change`的， `change`代表的是你的选中值发生更改的意思，但是在这里你只是选中，值没有发生更改

好的,非常感谢您的解答![19A638A3](https://user-images.githubusercontent.com/43459241/155448163-88dd98c0-2723-4044-9b9e-d9ea9b1b0ded.png)
