### ISSUE TITLE
[Bug Report] form validate return value is not Promise<boolean>

### ISSUE THREAD

**Issue by Cuixote** [element-plus/element-plus#6241]
### Element Plus version
2.0.2

### OS/Browsers version
latest version chrome

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-mxtu1h

### Steps to reproduce
click submit btn.

### What is Expected?
log false.

### What is actually happening?
log Object.

i also find the code is https://github.com/element-plus/element-plus/blob/2.0.2/packages/components/form/src/form.vue#L180

**Comment by nieyuyao** [comment]
When return one `Promise`, shouldn't `resolve(vaild, invalidFields)` instead of `reject(invalidFields)`? This can be consistent with the callback function behavior.

**Comment by Cuixote** [comment]
It's not my idea. Element-UI version < 2.15.7 always has this behavior. I don't know why change this at https://github.com/ElemeFE/element/pull/21374/files .
In my case, the error messages have showed in view while in the catch case, so don't need the invalidFields.
```js
async submitForm () {
  try {
    await this.$refs.form.validate()
  } catch (e) {
    // error messages have show in view
   // only need a boolean value to know what i need to do next
  }

}
````

**Comment by sxzz** [comment]
Close via https://github.com/element-plus/element-plus/pull/5401

**Comment by guohuihot** [comment]
这个解决了吗？

**Comment by guohuihot** [comment]
这么严重的问题就这么关了吗？

**Comment by sxzz** [comment]
> 这个解决了吗？

Form组件以重构，修改了部分类型定义。此issue不再有效。

**Comment by guohuihot** [comment]
> 

但是bug依然存在哦，看文档也没有其它方法，这是一次破坏性升级

**Comment by sxzz** [comment]
> > 
> 
> 
> 
> 但是bug依然存在哦，看文档也没有其它方法，这是一次破坏性升级

尚未发版，稍后发布。
