### ISSUE TITLE
[Bug Report] Cascader组件props属性报TS类型错误

### ISSUE THREAD

**Issue by huohuoit** [element-plus/element-plus#6244]
### Element Plus version
2.0.2

### OS/Browsers version
Windows10/Google latest

### Vue version
3.2.29

### Reproduction Link
https://github.com/element-plus/element-plus-playground

### Steps to reproduce
按官方组件使用方式：https://element-plus.gitee.io/zh-CN/component/cascader.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
props属性会报TS类型错误：
(JSX attribute) props?: CascaderProps
不能将类型“{ expandTrigger: string; }”分配给类型“CascaderProps”。
  属性“expandTrigger”的类型不兼容。ts(2322)
index.d.ts(3154, 5): 所需类型来自属性 "props"，在此处的 "IntrinsicAttributes & Partial<{ separator: string; disabled: boolean; props: CascaderProps; popperClass: string; teleported: BuildPropType<BooleanConstructor, unknown, unknown>; ... 8 more ...; beforeFilter: (value: string) => boolean | Promise<...>; }> & Omit<...>" 类型上声明该属性

### What is Expected?
无TS报错

### What is actually happening?
TS报错

**Comment by cmf-chenmf** [comment]
I have the same problem,I don't know what the solution is

**Comment by crush2020** [comment]
这是expandTrigger的类型
export declare enum ExpandTrigger {
    CLICK = "click",
    HOVER = "hover"
}
直接使用这个类型的字符串枚举值就好
`
import { ExpandTrigger } from 'element-plus'
const props = {
  checkStrictly: true,
  expandTrigger: ExpandTrigger.HOVER,
  value: 'barGroupId',
  children: 'barGroupList',
  label: 'barGroupName'
}
`
