### ISSUE TITLE
[Bug Report] qq浏览器Uncaught TypeError: Cannot read property '__vueuse_ssr_handlers__' of undefined

### ISSUE THREAD

**Issue by qimingye** [element-plus/element-plus#6248]
### Element Plus version
2.0.1

### OS/Browsers version
qq浏览器，内核70.0

### Vue version
3.2.30

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
qq浏览器下默认加载报错
Uncaught TypeError: Cannot read property '__vueuse_ssr_handlers__' of undefined
    at Object../node_modules/@vueuse/core/index.cjs (index.cjs:750)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Module../node_modules/element-plus/es/utils/util.mjs (util.mjs:1)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Module../node_modules/element-plus/es/hooks/use-global-config/index.mjs (index.mjs:1)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Module../node_modules/element-plus/es/hooks/use-common-props/index.mjs (index.mjs:1)

### What is Expected?
是否是框架问题或者浏览器版本问题，能否解决

### What is actually happening?
页面无法正确加载

**Comment by gjfei** [comment]
> 
> 
> 
> 
> ### Element Plus version
> 
> 2.0.1
> 
> 
> 
> ### OS/Browsers version
> 
> qq浏览器，内核70.0
> 
> 
> 
> ### Vue version
> 
> 3.2.30
> 
> 
> 
> ### Reproduction Link
> 
> https://elementui.github.io/issue-generator/#/en-US?repo=element-plus
> 
> 
> 
> ### Steps to reproduce
> 
> qq浏览器下默认加载报错
> 
> Uncaught TypeError: Cannot read property '__vueuse_ssr_handlers__' of undefined
> 
>     at Object../node_modules/@vueuse/core/index.cjs (index.cjs:750)
> 
>     at __webpack_require__ (bootstrap:853)
> 
>     at fn (bootstrap:150)
> 
>     at Module../node_modules/element-plus/es/utils/util.mjs (util.mjs:1)
> 
>     at __webpack_require__ (bootstrap:853)
> 
>     at fn (bootstrap:150)
> 
>     at Module../node_modules/element-plus/es/hooks/use-global-config/index.mjs (index.mjs:1)
> 
>     at __webpack_require__ (bootstrap:853)
> 
>     at fn (bootstrap:150)
> 
>     at Module../node_modules/element-plus/es/hooks/use-common-props/index.mjs (index.mjs:1)
> 
> 
> 
> ### What is Expected?
> 
> 是否是框架问题或者浏览器版本问题，能否解决
> 
> 
> 
> ### What is actually happening?
> 
> 页面无法正确加载
> 
> 
> 
> 
> 
> 

升级版本，这个是vueuse的问题
