### ISSUE TITLE
[Bug Report] vite为打包工具，开发环境ElDropdownMenu组件报错

### ISSUE THREAD

**Issue by wangzl1163** [element-plus/element-plus#6252]
### Element Plus version
2.0.2

### OS/Browsers version
win10 edge v96

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-rb2qzr?file=/package.json

### Steps to reproduce
采用 vite 命令方式创建项目，安装最新版本vue、element-plus，main.ts中引入后，执行 npm run dev。报错：TypeError: Cannot destructure property 'focusTrapRef' of 'inject(...)' as it is undefined.

### What is Expected?
修复bug

### What is actually happening?
控制台直接报错

**Comment by 18607236757** [comment]
您好，请问您的这个问题解决了吗？我在用vite启动项目时也遇到了相同的问题

**Comment by Zoctan** [comment]
same problem...   :<
