### ISSUE TITLE
[Feature Request] menu组件需要提供个可以设置二级菜单距离顶部菜单间距的属性，可以自由调节

### ISSUE THREAD

**Issue by lozhu** [element-plus/element-plus#6255]
### Existing Component
Yes

### Component Name
el-menu

### Description
menu组件需要提供个可以设置二级菜单距离顶部菜单间距的属性，可以自由调节。
因为当菜单组件mode=horizontal时，同时让菜单不随着页面滚动页置顶的时候，用CSS控制menu组件的间距就有问题了，必须得提供个设置接口

![QQ图片20220223183737](https://user-images.githubusercontent.com/68715772/155303151-6a4f86f4-31a2-43f9-8781-7926f009698f.png)

**Comment by emojiiii** [comment]
这里的间隙应该是你用了 `el-menu-item-group` 这个组件导致的，你如果不需要 `title`, 你可以像这个[例子](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwidGFjXCI+XG4gICAgPGVsLWNvbCA6c3Bhbj1cIjEyXCI+XG4gICAgICA8aDUgY2xhc3M9XCJtYi0yXCI+RGVmYXVsdCBjb2xvcnM8L2g1PlxuICAgICAgPGVsLW1lbnVcbiAgICAgICAgZGVmYXVsdC1hY3RpdmU9XCIyXCJcbiAgICAgICAgY2xhc3M9XCJlbC1tZW51LXZlcnRpY2FsLWRlbW9cIlxuICAgICAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICAgICAgICBAY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjFcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICAgICAgPGVsLWljb24+PGxvY2F0aW9uIC8+PC9lbC1pY29uPlxuICAgICAgICAgICAgPHNwYW4+TmF2aWdhdG9yIE9uZTwvc3Bhbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMlwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCB0aXRsZT1cIkdyb3VwIFR3b1wiPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIxLTRcIj5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48aWNvbi1tZW51IC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPk5hdmlnYXRvciBUd288L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiM1wiIGRpc2FibGVkPlxuICAgICAgICAgIDxlbC1pY29uPjxkb2N1bWVudCAvPjwvZWwtaWNvbj5cbiAgICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgVGhyZWU8L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNFwiPlxuICAgICAgICAgIDxlbC1pY29uPjxzZXR0aW5nIC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPk5hdmlnYXRvciBGb3VyPC9zcGFuPlxuICAgICAgICA8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWNvbD5cbiAgICA8ZWwtY29sIDpzcGFuPVwiMTJcIj5cbiAgICAgIDxoNSBjbGFzcz1cIm1iLTJcIj5DdXN0b20gY29sb3JzPC9oNT5cbiAgICAgIDxlbC1tZW51XG4gICAgICAgIGFjdGl2ZS10ZXh0LWNvbG9yPVwiI2ZmZDA0YlwiXG4gICAgICAgIGJhY2tncm91bmQtY29sb3I9XCIjNTQ1YzY0XCJcbiAgICAgICAgY2xhc3M9XCJlbC1tZW51LXZlcnRpY2FsLWRlbW9cIlxuICAgICAgICBkZWZhdWx0LWFjdGl2ZT1cIjJcIlxuICAgICAgICB0ZXh0LWNvbG9yPVwiI2ZmZlwiXG4gICAgICAgIEBvcGVuPVwiaGFuZGxlT3BlblwiXG4gICAgICAgIEBjbG9zZT1cImhhbmRsZUNsb3NlXCJcbiAgICAgID5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMVwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICAgICAgICA8ZWwtaWNvbj48bG9jYXRpb24gLz48L2VsLWljb24+XG4gICAgICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgT25lPC9zcGFuPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCB0aXRsZT1cIkdyb3VwIE9uZVwiPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L2VsLW1lbnUtaXRlbS1ncm91cD5cbiAgICAgICAgICA8ZWwtbWVudS1pdGVtLWdyb3VwIHRpdGxlPVwiR3JvdXAgVHdvXCI+XG4gICAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICAgIDwvZWwtbWVudS1pdGVtLWdyb3VwPlxuICAgICAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjEtNFwiPlxuICAgICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5pdGVtIGZvdXI8L3RlbXBsYXRlPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMlwiPlxuICAgICAgICAgIDxlbC1pY29uPjxpY29uLW1lbnUgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4+TmF2aWdhdG9yIFR3bzwvc3Bhbj5cbiAgICAgICAgPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCIgZGlzYWJsZWQ+XG4gICAgICAgICAgPGVsLWljb24+PGRvY3VtZW50IC8+PC9lbC1pY29uPlxuICAgICAgICAgIDxzcGFuPk5hdmlnYXRvciBUaHJlZTwvc3Bhbj5cbiAgICAgICAgPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0XCI+XG4gICAgICAgICAgPGVsLWljb24+PHNldHRpbmcgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4+TmF2aWdhdG9yIEZvdXI8L3NwYW4+XG4gICAgICAgIDwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1tZW51PlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge1xuICBMb2NhdGlvbixcbiAgRG9jdW1lbnQsXG4gIE1lbnUgYXMgSWNvbk1lbnUsXG4gIFNldHRpbmcsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgaGFuZGxlT3BlbiA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuY29uc3QgaGFuZGxlQ2xvc2UgPSAoa2V5OiBzdHJpbmcsIGtleVBhdGg6IHN0cmluZ1tdKSA9PiB7XG4gIGNvbnNvbGUubG9nKGtleSwga2V5UGF0aClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by BigPengZai** [comment]
```javascript
<el-sub-menu index="1" style="margin-top: '50px'">
```
直接 在sub-menu 上面设置 有什么问题？

**Comment by msidolphin** [comment]
popper-offset
