### ISSUE TITLE
Vite allows the project to fail

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#626]
hello, i install element-plus@lastest but i use vite run project， It doesn't work
tip: Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification

**Comment by xiaoxian521** [comment]
I think it may be that some code in element plus has affected vite's

**Comment by zazzaz** [comment]
I will double-check the code, as for now, you can check this as a reference https://github.com/element-plus/element-plus-vite-starter

**Comment by JeremyWuuuuu** [comment]
The might related to #659

**Comment by zazzaz** [comment]
will fix soon

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.21, thanks
