### ISSUE TITLE
[Bug Report] config-provider 提供 z-index 参数无效

### ISSUE THREAD

**Issue by xiangxinji** [element-plus/element-plus#6264]
### Element Plus version
2.0.2

### OS/Browsers version
mac

### Vue version
3.2.31

### Reproduction Link
/ https://codepen.io/iamkun/pen/YzWMaVr

### Steps to reproduce
1. 提供 config-provider z-index 参数 
2. 使用 el-select / el-message-box 等组件 
3. z-index 未修改 

### What is Expected?
el-select 弹出框 z-index 应该修改掉

### What is actually happening?
实际z-index 计算还是从 2000 开始

**Comment by xiaoxian521** [comment]
same: https://github.com/element-plus/element-plus/issues/6265
