### ISSUE TITLE
[Bug Report] config-provider 提供 z-index 参数无效

### ISSUE THREAD

**Issue by xiangxinji** [element-plus/element-plus#6265]
### Element Plus version
2.0.2

### OS/Browsers version
mac

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/xiangxinji/pen/dyZjXdm

### Steps to reproduce
1. 提供 config-provider z-index 参数 
2. 使用 el-select / el-message-box 等组件 
3. z-index 未修改 

### What is Expected?
el-select 弹出框 z-index 应该修改掉

### What is actually happening?
实际z-index 计算还是从 2000 开始

**Comment by endypark** [comment]
https://element-plus.org/zh-CN/component/config-provider.html#%E5%AF%B9%E6%B6%88%E6%81%AF%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE

**Comment by endypark** [comment]
![config-server](https://user-images.githubusercontent.com/5320122/155497628-cf1a67d4-afef-4de5-8e90-324fc54a167e.png)

可能应该是 写成 zIndex

这里bug确实挺多的，，，size，设置string也会报错，和 doc描述不一样

**Comment by msidolphin** [comment]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/26672484/155630778-32beb8bc-8ae5-4c39-8e4a-6c705391e6e8.png">
我看到是生效的，麻烦提供下浏览器及其版本号

**Comment by msidolphin** [comment]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/26672484/155630778-32beb8bc-8ae5-4c39-8e4a-6c705391e6e8.png">
我看到是生效的，麻烦提供下浏览器及其版本号

**Comment by msidolphin** [comment]
> https://codepen.io/xiangxinji/pen/dyZjXdm



> ![config-server](https://user-images.githubusercontent.com/5320122/155497628-cf1a67d4-afef-4de5-8e90-324fc54a167e.png)
> 
> 可能应该是 写成 zIndex
> 
> 这里bug确实挺多的，，，size，设置string也会报错，和 doc描述不一样

麻烦提供下你的代码，设置size报错的问题并没有重现

**Comment by zlj130137** [comment]
不知道是不是zIndex无效，我在el-dialog中使用el-select控件，select组件的下拉框被el-dialog遮住

**Comment by xiangxinji** [comment]
@zlj130137 对我也是遇到了这个问题, 平常的 el-select 这个 z-index 没问题, 但是 dialog 里面的 z-index 就有问题了,还是从2000 开始 , 你是怎么解决这个问题的呢

**Comment by zlj130137** [comment]
@xiangxinji 靠修改样式解决

**Comment by xiangxinji** [comment]
@zlj130137  好的 谢谢, 这个问题我已经解决了, 要把 element-plus 的版本更改为: 2.0.2
