### ISSUE TITLE
Row Col 无法按需引入

### ISSUE THREAD

**Issue by SLin0218** [element-plus/element-plus#627]
`* element-plus/lib/col in ./src/plugins/element.ts`

**Comment by xiaofeng-bm** [comment]
![Snipaste_2020-11-19_14-19-17](https://user-images.githubusercontent.com/45890549/99628996-3d6b1b80-2a72-11eb-9c24-e113f1616c8c.png)
路径不对，element-plus吧el-col和el-row放到了layout目录下

**Comment by zazzaz** [comment]
Thanks, we will fix this bug in the next few days in #630

**Comment by zazzaz** [comment]
this has been fixed in `1.0.1-alpha.20 `

Note, we have change the name with an `el-` prefix for each component.

The code should be written as blew:
```
import { ElRow, ElCol } from 'element-plus'
```
