### ISSUE TITLE
[Bug Report] el-button get some color bugs in 2.0.3 with css vars

### ISSUE THREAD

**Issue by joo1es** [element-plus/element-plus#6286]
### Element Plus version
2.0.3

### OS/Browsers version
MAC OS

### Vue version
3.2.31

### Reproduction Link
https://codepen.io/joo1es/pen/MWOBMPK

### Steps to reproduce
hover the buttons or focus on the buttons

### What is Expected?
correct color

### What is actually happening?
it seems just change the default status, and it not happens in 2.0.2

**Comment by Alanscut** [comment]
Tried version 2.0.2, it doesn't seem to work.
It is normal to write this:
<el-button type="primary" color="#ff0000">test</el-button>

**Comment by joo1es** [comment]
> Tried version 2.0.2, it doesn't seem to work. It is normal to write this: ![image](https://user-images.githubusercontent.com/21104054/156126028-f815abd8-c2ec-489e-8a65-c6edf5ba25c5.png)

yes, button 1 works and button 2 not works.
and more, color="rgb(255, 0, 0)" not works too

**Comment by Alanscut** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHN0eWxlPVwiLS1lbC1jb2xvci1wcmltYXJ5OiAjZmYwMDAwXCI+bXkgaG92ZXIgc3RhdHVzIGlzIHN0aWxsIGJsdWU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGNvbG9yPVwidmFyKC0tY29sb3IpXCI+bXkgaG92ZXIgc3RhdHVzIGlzIGdyYXk8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGNvbG9yPVwicmdiKDI1NSwgMCwgMClcIj50ZXN0PC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgPlxuICA6cm9vdCB7XG4gICAgLS1lbC1jb2xvci1wcmltYXJ5OiAjZmYwMDAwO1xuICAgIC0tY29sb3I6ICMwMDAwZmY7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)
I tried rgb here and it works fine
button 1 doesn't work either in version 2.0.2

**Comment by Alanscut** [comment]
@YunYouJun

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/156177185-74f80656-33bc-403f-b26c-e125dd2a6b22.png)

![image](https://user-images.githubusercontent.com/25154432/156177200-6221891d-9952-436c-99fc-068e3e009ebc.png)

It seems to work the same way we expected it to work.

If you want to custom button color. You should use `<el-button color="#ff0000"></el-button>`.

What do you expect?

**Comment by joo1es** [comment]
> ![image](https://user-images.githubusercontent.com/25154432/156177185-74f80656-33bc-403f-b26c-e125dd2a6b22.png)
> 
> ![image](https://user-images.githubusercontent.com/25154432/156177200-6221891d-9952-436c-99fc-068e3e009ebc.png)
> 
> It seems to work the same way we expected it to work.
> 
> If you want to custom button color. You should use `<el-button color="#ff0000"></el-button>`.
> 
> What do you expect?

i except to set a global css var, like this

`:root { --main-theme-color: #ff0000; }`

`<el-button color="var(--main-theme-color)"></el-button>`

so that if i change it to another theme, the button can show correct color(hover & active & focus), otherwise I have to modify the properties of every component i used

**Comment by YunYouJun** [comment]
Hey, we provide a method to custom theme color by scss.
Since button colors need to be precomputed, and `primary/success/danger`, etc. should be cached, using scss is a better approach.

> See this: https://element-plus.org/en-US/guide/theming.html

```scss
// styles/element/index.scss
/* just override what you need */
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  $colors: (
    'primary': (
      'base': green,
    ),
  )
);
```

**Comment by joo1es** [comment]
> Hey, we provide a method to custom theme color by scss. Since button colors need to be precomputed, and `primary/success/danger`, etc. should be cached, using scss is a better approach.
> 
> > See this: https://element-plus.org/en-US/guide/theming.html
> 
> ```css-scss
> // styles/element/index.scss
> /* just override what you need */
> @forward 'element-plus/theme-chalk/src/common/var.scss' with (
>   $colors: (
>     'primary': (
>       'base': green,
>     ),
>   )
> );
> ```

we are using less so that we use the css way

> https://element-plus.org/en-US/guide/theming.html#by-css-variable

but by this way we found even the precomputed colors are incorrect, here the first button

> https://codepen.io/joo1es/pen/MWOBMPK

can't define button color like this since version 2.0.3 or it's a bug?

**Comment by YunYouJun** [comment]
Using sass does not break the compilation of less.

> can't define button color like this since version 2.0.3 or it's a bug?

This revision was intentional. Because most users only use `primary/success/danger/info` and so we need provide cached css vars. 

Previously, it was successful because it used inline style(but that's not elegant enough). Dynamic calculations are retained only until custom colors are used.

If you want to still use css variables without scss, you can define them like this.

```css
.el-button--primary {
    --el-color-primary: red; /* your custom color */
    --el-color-primary-light-3: /* light 30% primary (mix white) */;
    --el-color-primary-dark-2: /* dark 30% primary (mix black) */;
    --el-color-primary-light-5: /* light 50% primary (mix white) */;
}
```

Maybe it's a little troublesome.
But you can write less function to generate your css var palette.
Just refer this:

https://github.com/element-plus/element-plus/blob/5aabf066e6bbab81be8fbf53a309d96f31aadfdd/packages/theme-chalk/src/mixins/_var.scss#L7-L17

**Comment by YunYouJun** [comment]
If there are no other problems, I will close it.
