### ISSUE TITLE
[Feature Request] 关于按需导入的文档介绍修改建议

### ISSUE THREAD

**Issue by timi137137** [element-plus/element-plus#6287]
### Existing Component
Yes

### Component Name
All

### Description
在[文档](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)中可以知道如何使用按需导入，但是如果使用按需导入时同时使用ESlint做代码检查时，如果不书写 import 代码会导致ESlint错误，而自动导入是成功的。目前我通过同时使用 unplugin-auto-import，unplugin-vue-components，和unplugin-element-plus 三个自动导入插件并书写 import 代码解决该问题。鉴于 ESlint的广泛使用，请问有没有更简洁的解决方式？如果没有我是否能够提交PR修改文档描述。谢谢各位

**Comment by sxzz** [comment]
Do you use TypeScript?

**Comment by timi137137** [comment]
> Do you use TypeScript?

是的，使用的vue3+ts+vite

**Comment by sxzz** [comment]
Please refer to https://github.com/sxzz/element-plus-best-practices

**Comment by sxzz** [comment]
其实就是在 TS 中关闭 ESLint 的全局变量检查。

**Comment by timi137137** [comment]
> 其实就是在 TS 中关闭 ESLint 的全局变量检查。

这个项目在昨天已看过了，谢谢提供，虽然可以配置文件中关闭检测。但是有些情况下并不能使用这种方式解决，如果实在没有办法的话也希望可以在文档中提出“如果使用ESLint需要关闭全局变量检测”

**Comment by sxzz** [comment]
这个属于 ESLint + TypeScript 的使用范畴，与 Element Plus 文档不太相关。

使用 recommend 的预设就包含了关闭 `no-undef` 规则。

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L24
