### ISSUE TITLE
[Feature Request] [Enhancement] [icon] Support for additional icon packs

### ISSUE THREAD

**Issue by volarname** [element-plus/element-plus#6290]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `icon`

## Description

add support for additional icon packs like Material Design Icons, Material Icons, Font Awesome 4 and Font Awesome 5, or custom

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
This is not the scope of the Element Plus component library, you can use plugins like `unplugin-icons`.
