### ISSUE TITLE
[Bug Report] [Component] [pagination] el-pagination page-size layout="sizes"  Simultaneous Settings will cause rendering to fail

### ISSUE THREAD

**Issue by ZiLongLing** [element-plus/element-plus#6291]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.28`
- Element Plus Version: `2.0.3`
- Browser / OS: `Chrome  98.0.4758.102 Windows`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[CodePen](https://codepen.io/zilongling/pen/qBVMdZz)

### Steps to reproduce

<el-pagination ref="paginationRef" :total="100" background layout="sizes, prev, pager, next, jumper, total" :page-size="20"></el-pagination>无法渲染，去掉:page-size="20"属性或者layout中的sizes选项便可以成功渲染，page-size也设置成v-model.page-size绑定也能解决该问题。

### What is Expected?

Render success

### What is actually happening?

Render fail

### Additional comments

_(empty)_

**Comment by ZiLongLing** [comment]
https://codepen.io/zilongling/pen/qBVMdZ 这个呀

**Comment by msidolphin** [comment]
> https://codepen.io/zilongling/pen/qBVMdZ

<img width="584" alt="image" src="https://user-images.githubusercontent.com/26672484/155936822-b880a75c-c432-443a-af28-f96d5797df71.png">

**Comment by ZiLongLing** [comment]
https://codepen.io/zilongling/pen/qBVMdZz 少了个z

**Comment by msidolphin** [comment]
@ZiLongLing 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/26672484/155948029-85239884-3b0b-4eec-940f-3c58ec7390dd.png">
这个demo不对呀

**Comment by ZiLongLing** [comment]
![image](https://user-images.githubusercontent.com/41666363/155953850-4732e9ba-4d8b-4f2c-98d7-d71471f02d80.png)
哪里不对啊，说的就是分页组件没渲染出来这个BUG

**Comment by msidolphin** [comment]
> ![image](https://user-images.githubusercontent.com/41666363/155953850-4732e9ba-4d8b-4f2c-98d7-d71471f02d80.png) 哪里不对啊，说的就是分页组件没渲染出来这个BUG

<img width="649" alt="image" src="https://user-images.githubusercontent.com/26672484/155954558-ed60e9a3-967d-439b-b6da-97a239aa6ae6.png">

我这边打开是这样，你直接把代码copy出来吧
