### ISSUE TITLE
[Bug Report] [Component] [date-picker, dialog] el-dialog   el-date-picker 时, picker 不会自动关闭

### ISSUE THREAD

**Issue by luuunnn** [element-plus/element-plus#6294]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.0.3`
- Browser / OS: `edge lasted`
- Build Tool: `CDN`

### Related Component

- `el-date-picker`
- `el-dialog`

### Reproduction Link

[CodePen](https://codepen.io/Luuuuuu/pen/ZEaMXdZ)

### Steps to reproduce

picker 在选择时间后,不再自动关闭

### What is Expected?

选完时间自动关闭

### What is actually happening?

没有关闭

### Additional comments

_(empty)_

**Comment by JeremyWuuuuu** [comment]
@luuunnn I will fix this immediately, sorry for the inconvenience :bow:

**Comment by JeremyWuuuuu** [comment]
This should be fixed in 2.0.4, please download the newest version and have a try :bow:

**Comment by luuunnn** [comment]
谢谢,辛苦了!
