### ISSUE TITLE
[Bug Report] el-dropdown-item divided 间隔变大

### ISSUE THREAD

**Issue by DXD2019** [element-plus/element-plus#6299]
### Element Plus version
2.0.3

### OS/Browsers version
Microsoft Edge 版本 98.0.1108.56

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
https://element-plus.gitee.io/zh-CN/component/dropdown.html

### What is Expected?
正常显示

### What is actually happening?
加了divided 分隔下的间隔变大
官方文档中的Dropdown playgroud 采用2.0.3版本有此问题
2.0.2无此问题

**Comment by SignDawn** [comment]
是的，2.0.2 使用的是 div 标签，官方可能是为了语义化，在 2.0.3 中使用的是 li 标签。
但 li 标签的默认 display 是 list-item ，而 div 是 block ，加个 display: block 应该就行，不知道官方是否会采纳？

**Comment by yaomk** [comment]
> 是的，2.0.2 使用的是 div 标签，官方可能是为了语义化，在 2.0.3 中使用的是 li 标签。 但 li 标签的默认 display 是 list-item ，而 div 是 block ，加个 display: block 应该就行，不知道官方是否会采纳？

看官方文档上”基础用法“效果是正常的，而且也是li标签，但是在 ”PlayGround 中编辑“中，效果确是不正常的
