### ISSUE TITLE
[Bug Report] [Component] [All] dialog组件中的元素无法被选中

### ISSUE THREAD

**Issue by niuge666** [element-plus/element-plus#6324]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.0.3`
- Browser / OS: ` Chrome/96.0.4664.45`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/dialog.html)

### Steps to reproduce

打开dialog就能复现，里面的所有元素都无法被选中，除了input

### What is Expected?

文字能被选中

### What is actually happening?

文字不能被选中

### Additional comments

_(empty)_

**Comment by JeremyWuuuuu** [comment]
Already fixed in #6346

**Comment by JeremyWuuuuu** [comment]
You upgrade to 2.0.4 for the fix
