### ISSUE TITLE
[Bug Report] [Component] [dialog] The dialog component will be covered by other elements in the ` :modal="false"`,but the dialog should be at the top level

### ISSUE THREAD

**Issue by Mrxyy** [element-plus/element-plus#6330]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.0.3`
- Browser / OS: `Chrome/98.0.4758.109 / mac `
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5DbGljayB0byBvcGVuIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cbiAgXG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIiA6bW9kYWw9XCJmYWxzZVwiIHRpdGxlPVwiVGlwc1wiIHdpZHRoPVwiMzAlXCIgZHJhZ2dhYmxlPlxuICAgIDxzcGFuPkl0J3MgYSBkcmFnZ2FibGUgRGlhbG9nPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkaWFsb2ctZm9vdGVyXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIlxuICAgICAgICAgID5Db25maXJtPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC9zcGFuPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZGlhbG9nPlxuICA8ZGl2XG4gICAgICA6c3R5bGU9XCJ7XG4gICAgICAgIHdpZHRoOiAnMjBweCcsXG4gICAgICAgIGhlaWdodDogJzIwMHB4JyxcbiAgICAgICAgYmFja2dyb3VuZDogJ3JlZCcsXG4gICAgICAgIHBvc2l0aW9uOiAnZml4ZWQnICBcbiAgICAgIH1cIlxuICAgID48L2Rpdj5cblxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

<template>
  <el-button type="text" @click="dialogVisible = true"
    >Click to open Dialog
  </el-button>
  
  <el-dialog v-model="dialogVisible" :modal="false" title="Tips" width="30%" draggable>
    <span>It's a draggable Dialog</span>
    <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">Cancel</el-button>
        <el-button type="primary" @click="dialogVisible = false"
          >Confirm</el-button
        >
      </span>
    </template>
  </el-dialog>
  <div
      :style="{
        width: '20px',
        height: '200px',
        background: 'red',
        position: 'fixed'  
      }"
    ></div>

</template>

<script lang="ts" setup>
import { ref } from 'vue'

const dialogVisible = ref(false)
</script>

### What is Expected?

Dialog is at the top

### What is actually happening?

Dialog is overwritten

### Additional comments

Dialog should hava a base position priority

**Comment by purepear** [comment]
Maybe this fixes is? https://github.com/element-plus/element-plus/pull/6332

**Comment by msidolphin** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/26672484/156708370-0f9de1da-d94a-4d64-ab64-9790a8a76c53.png">

I don't see what the problem with dialog?

**Comment by purepear** [comment]
There was a problem in `2.0.3` but it's fixed now in `2.0.4`

**Comment by msidolphin** [comment]
> Element Plus Playground

fine~
