### ISSUE TITLE
[Bug Report] [Component] [date-picker, dialog] DatePicker ok button not work when in Dialog

### ISSUE THREAD

**Issue by 7NZ** [element-plus/element-plus#6334]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.24`
- Element Plus Version: `2.0.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93PlxuICAgIDxlbC1jb2w+PGVsLWJ1dHRvbiBAY2xpY2s9XCJzdGF0ZS52aXNpYmxlID0gdHJ1ZVwiPm9wZW48L2VsLWJ1dHRvbj48L2VsLWNvbD5cbiAgPC9lbC1yb3c+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG4gIDxlbC1kaWFsb2dcblx0XHR0aXRsZT1cImRhdGVQaWNrZXIgaW4gZGlhbG9nXCJcbiAgICB3aWR0aD1cIjYwJVwiXG5cdFx0di1tb2RlbD1cInN0YXRlLnZpc2libGVcIlxuICA+XG4gIFx0PGVsLWRhdGUtcGlja2VyXG4gICAgICB2LW1vZGVsPVwic3RhdGUuZGF0ZVwiXG4gICAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgICBzdGFydC1wbGFjZWhvbGRlcj1cIlN0YXJ0IERhdGVcIlxuICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIERhdGVcIlxuICAgID5cbiAgICA8L2VsLWRhdGUtcGlja2VyPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJztcbiAgY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gICAgdmlzaWJsZTogZmFsc2UsXG4gICAgZGF0ZTogJydcbiAgfSlcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

1. Open dialog
2. Pick a datetimerange
3. Click [ok] button

### What is Expected?

The date panel will disappear when click ok button

### What is actually happening?

The date panel didn't disappear

### Additional comments

Element-plus v2.0.2 has no such issue.

**Comment by timogal** [comment]
set `teleported` attribute to `false` fix this problem

**Comment by 7NZ** [comment]
Upgrade to v2.0.5 solved th problem
