### ISSUE TITLE
[Bug Report] [Component] [image, table] el-image大图预览时与el-table层级冲突,没有在最顶层

### ISSUE THREAD

**Issue by ZHT131** [element-plus/element-plus#6335]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.3`
- Browser / OS: `chrome 98.0.4758.102`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnSG9tZScsXG4gICAgaW1hZ2U6J2h0dHBzOi8vZWxlbWVudC1wbHVzLmdpdGVlLmlvL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmcnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdPZmZpY2UnLFxuICAgIGltYWdlOidodHRwczovL2VsZW1lbnQtcGx1cy5naXRlZS5pby9pbWFnZXMvZWxlbWVudC1wbHVzLWxvZ28uc3ZnJ1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnSG9tZScsXG4gICAgaW1hZ2U6J2h0dHBzOi8vZWxlbWVudC1wbHVzLmdpdGVlLmlvL2ltYWdlcy9lbGVtZW50LXBsdXMtbG9nby5zdmcnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgICB0YWc6ICdPZmZpY2UnLFxuICAgIGltYWdlOidodHRwczovL2VsZW1lbnQtcGx1cy5naXRlZS5pby9pbWFnZXMvZWxlbWVudC1wbHVzLWxvZ28uc3ZnJ1xuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQgcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhdmF0YXJcIiBsYWJlbD1cIuWktOWDj1wiIG1pbi13aWR0aD1cIjE4MFwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgICAgICA8ZWwtaW1hZ2Ugc3R5bGU9XCJ3aWR0aDogNTBweDsgaGVpZ2h0OiA1MHB4XCIgOnNyYz1cInNjb3BlLnJvdy5pbWFnZVwiIDpwcmV2aWV3LXNyYy1saXN0PVwiW3Njb3BlLnJvdy5pbWFnZV1cIj5cbiAgICAgICAgICAgIDwvZWwtaW1hZ2U+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJzdGF0ZVwiIGxhYmVsPVwiU3RhdGVcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY2l0eVwiIGxhYmVsPVwiQ2l0eVwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCI2MDBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiWmlwXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gZml4ZWQ9XCJyaWdodFwiIGxhYmVsPVwiT3BlcmF0aW9uc1wiIHdpZHRoPVwiMTIwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInRleHRcIiBzaXplPVwic21hbGxcIj5EZXRhaWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwidGV4dFwiIHNpemU9XCJzbWFsbFwiPkVkaXQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

打开复现链接，点击表格中的图片预览，即可看到冲突效果

### What is Expected?

图片预览渲染在table层级之上

### What is actually happening?

el-image预览时和table层级冲突

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/22323594/155960794-268e28a5-6317-4086-85e2-82bf7e914b31.png)

**Comment by 7NZ** [comment]
这个已经解决了，用这个属性`preview-teleported`，[查看文档](https://element-plus.gitee.io/zh-CN/component/image.html#image-%E5%B1%9E%E6%80%A7)

**Comment by ZHT131** [comment]
> 这个已经解决了，用这个属性`preview-teleported`，[查看文档](https://element-plus.gitee.io/zh-CN/component/image.html#image-%E5%B1%9E%E6%80%A7)

感谢，果然开启后就不会冲突了
