### ISSUE TITLE
[Bug Report] [Component] [table] span-method 

### ISSUE THREAD

**Issue by mknightoy** [element-plus/element-plus#6337]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62`
- Build Tool: `Webpack`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgOnNwYW4tbWV0aG9kPVwiYXJyYXlTcGFuTWV0aG9kXCJcbiAgICAgIGJvcmRlclxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMlwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgZGVmaW5lQ29tcG9uZW50IH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBUYWJsZUNvbHVtbkN0eCB9IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RhYmxlL3NyYy90YWJsZS1jb2x1bW4vZGVmYXVsdHMnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbn1cblxuaW50ZXJmYWNlIFNwYW5NZXRob2RQcm9wcyB7XG4gIHJvdzogVXNlclxuICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4gIHJvd0luZGV4OiBudW1iZXJcbiAgY29sdW1uSW5kZXg6IG51bWJlclxufVxuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBjYWNoZTogMCxcbiAgICAgIHRhYmxlRGF0YTogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYW1vdW50MTogJzIzNCcsXG4gICAgICAgICAgYW1vdW50MjogJzMuMicsXG4gICAgICAgICAgYW1vdW50MzogMTAsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzEyOTg3MTIzJyxcbiAgICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgICBhbW91bnQxOiAnMTY1JyxcbiAgICAgICAgICBhbW91bnQyOiAnNC40MycsXG4gICAgICAgICAgYW1vdW50MzogMTIsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzEyOTg3MTI0JyxcbiAgICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgICBhbW91bnQxOiAnMzI0JyxcbiAgICAgICAgICBhbW91bnQyOiAnMS45JyxcbiAgICAgICAgICBhbW91bnQzOiA5LFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYW1vdW50MTogJzYyMScsXG4gICAgICAgICAgYW1vdW50MjogJzIuMicsXG4gICAgICAgICAgYW1vdW50MzogMTcsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzEyOTg3MTI2JyxcbiAgICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgICBhbW91bnQxOiAnNTM5JyxcbiAgICAgICAgICBhbW91bnQyOiAnNC4xJyxcbiAgICAgICAgICBhbW91bnQzOiAxNSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfVxuICB9LFxuICBtZXRob2RzOiB7XG4gICAgYXJyYXlTcGFuTWV0aG9kKHsgcm93LCBjb2x1bW4sIHJvd0luZGV4LCBjb2x1bW5JbmRleCB9OiBTcGFuTWV0aG9kUHJvcHMpIHtcbiAgICAgIGNvbnNvbGUuY291bnQoJ3RyaWdnZXInKVxuICAgICAgaWYgKHRoaXMuY2FjaGUgIT0gK25ldyBEYXRlKCkpIHtcbiAgICAgICAgdGhpcy5jYWNoZSA9ICtuZXcgRGF0ZSgpXG4gICAgICB9XG4gICAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICAgIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgICAgICAgIHJldHVybiBbMSwgMl1cbiAgICAgICAgfSBlbHNlIGlmIChjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgICAgICAgIHJldHVybiBbMCwgMF1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0sXG4gIH0sXG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

Triggered multiple times when span-method uses "data" 

### What is Expected?

Normal trigger

### What is actually happening?

Unusual multiple triggers

### Additional comments

This problem does not occur if only assignment is used when using data

**Comment by msidolphin** [comment]
You have update data in the spanMethod, which is the cause of triggered multiple times

**Comment by mknightoy** [comment]
I need update to data.
Is this the feature of vue3? 
@msidolphin
