### ISSUE TITLE
[Bug Report] [TypeScript] [All] es/* should not use /// <reference types="node" />

### ISSUE THREAD

**Issue by exherb** [element-plus/element-plus#6338]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.3`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/exherb/vue-tsc)

### Steps to reproduce

pnpm install
cd dashboard
npm run lint

### What is Expected?

no lint error

### What is actually happening?

> @adtalos/dashboard@0.0.0 lint:vuetsc
> vue-tsc --noEmit

src/components/dynamic_material/download.ts:39:37 - error TS2551: Property 'pipeTo' does not exist on type 'ReadableStream'. Did you mean 'pipe'?

39   await new Blob([buffer]).stream().pipeTo(writable);
                                       ~~~~~~

  ../node_modules/.pnpm/@types+node@17.0.21/node_modules/@types/node/globals.d.ts:197:9
    197         pipe<T extends WritableStream>(destination: T, options?: { end?: boolean | undefined; }): T;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'pipe' is declared here.

Found 1 error.

### Additional comments

https://github.com/johnsoncodehk/volar/issues/989

**Comment by sxzz** [comment]
https://github.com/johnsoncodehk/volar/issues/989#issuecomment-1054164526
