### ISSUE TITLE
[Bug Report] [Component] [table, scrollbar] resize table column，scrollbar not display

### ISSUE THREAD

**Issue by xhxhxhxh** [element-plus/element-plus#6351]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.3`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`
- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgY29sdW1ucyA9IHJlZihbXG4gIHtcbiAgICB0eXBlOiAnaW5kZXgnLFxuICAgIGZpeGVkOiB0cnVlLFxuICAgIHdpZHRoOiA4MCxcbiAgICBsYWJlbDogJ+W6j+WPtydcbiAgfVxuXSk7XG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihBcnJheS5mcm9tKG5ldyBBcnJheSgxOCksICgpID0+IHsgcmV0dXJuIHt9OyB9KSk7XG5cbmZvciAobGV0IGkgPSAxOyBpIDwgNjsgaSsrKSB7XG4gIGNvbHVtbnMudmFsdWUucHVzaCh7XG4gICAgd2lkdGg6IDIwMCxcbiAgICByZXNpemFibGU6IHRydWUsXG4gICAgcHJvcDogJ2NvbHVtbicgKyBpLFxuICAgIGxhYmVsOiAnY29sdW1uJyArIGksXG4gIH0pO1xuICB0YWJsZURhdGEudmFsdWUuZm9yRWFjaCgoaXRlbSwgaW5kZXgpID0+IHtcbiAgICBpdGVtWydjb2x1bW4nICsgaV0gPSBg5YiXJHtpfSwg6KGMJHtpbmRleCArIDF9YDtcbiAgfSk7XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgaGVpZ2h0PVwiMTAwJVwiIGJvcmRlcj5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgIHYtZm9yPVwiY29sdW1uIGluIGNvbHVtbnNcIlxuICAgICAgICAgIDprZXk9XCJjb2x1bW4ucHJvcFwiXG4gICAgICAgICAgOnR5cGU9XCJjb2x1bW4udHlwZVwiXG4gICAgICAgICAgOmZpeGVkPVwiY29sdW1uLmZpeGVkXCJcbiAgICAgICAgICA6cHJvcD1cImNvbHVtbi5wcm9wXCJcbiAgICAgICAgICA6bGFiZWw9XCJjb2x1bW4ubGFiZWxcIlxuICAgICAgICAgIDp3aWR0aD1cImNvbHVtbi53aWR0aFwiLz5cbiAgICAgIDwvZWwtdGFibGU+XG4gIFxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

1. table width should less than container at beginning, then resize a column until table width more than contianer, scrollbar not display.
2. resize table width, scrollbar width can not change, still in initial state.

### What is Expected?

scrollbar can display, scrollbar width can update with table width

### What is actually happening?

scrollbar can not display

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
If you using the el-scrollbar, make sure the width of el-scrollbar__view follows the content
