### ISSUE TITLE
[Bug Report] [Component] [pagination] 低版本浏览器 el-pagination组件切换size的时报错

### ISSUE THREAD

**Issue by Corgis** [element-plus/element-plus#6357]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome 49.0.2623.110 (正式版本) （32 位）/ WindowsXp 2002 Service Pack 3`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Link](https://gitee.com/Corgis/element-legacy)

### Steps to reproduce

1：因项目需要打包构建出产品才能复现问题，所以提供git地址
2：项目打包后指定的谷歌浏览器版本访问，点击分页组件切换size报错
报错如下：
Uncaught TypeError: n.composedPath is not a function

### What is Expected?

正常切换不报错

### What is actually happening?

报错Uncaught TypeError: n.composedPath is not a function

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/13865529/156113918-5ce1873a-f431-4ead-b05c-b3b528d44af7.png)

**Comment by msidolphin** [comment]
https://element-plus.org/en-US/guide/installation.html 

Your system and browser version are too old~~,

**Comment by Corgis** [comment]
> https://element-plus.org/en-US/guide/installation.html
> 
> Your browser version is too old~~
你好，感谢回答。
![image](https://user-images.githubusercontent.com/13865529/156306214-cd8363b3-58bc-449d-9425-fb5c543328e3.png)
该工程已经通过@vitejs/plugin-legacy 设置了targets: ['Chrome >= 49']兼容，目前的表现基本都是ok的 不是很明白composedPath这个api为什么未处理到
