### ISSUE TITLE
[Bug Report] [Component] [infinite-scroll] 使用v-infinite-scroll组件,Cannot destructure property 'containerEl' of 'el[SCOPE7]' as it is undefined.升级到2.0.3之后出现此问题

### ISSUE THREAD

**Issue by myhzw** [element-plus/element-plus#6360]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.2`
- Element Plus Version: `2.0.4`
- Browser / OS: `window10`
- Build Tool: `Vite`

### Related Component

- `el-infinite-scroll`

### Reproduction Link

[Link]()

### Steps to reproduce

使用v-infinite-scroll组件。1.3.0-beta.1并没有出现此问题，升级到2.0.3之后出现此问题

### What is Expected?

没有报错

### What is actually happening?

Uncaught (in promise) TypeError: Cannot destructure property 'containerEl' of 'el[SCOPE7]' as it is undefined.
    at updated (index.ts:120)

### Additional comments

_(empty)_

**Comment by pengfan2013** [comment]
看代码是一次nextTick就再去获取containerEl

**Comment by codelegant** [comment]
请问最后是怎么解决的？v2.1.4 仍然有这个问题。

**Comment by codelegant** [comment]
> 看代码是一次nextTick就再去获取containerEl

触发了灵感，在 nextTick() 之后再显示 v-infinite-scroll组件 的组件，解决问题。
