### ISSUE TITLE
Multiple select show weird tags when options load after dropdown list showed.

### ISSUE THREAD

**Issue by ZzqiZQute** [element-plus/element-plus#637]
Reproduction repo: https://github.com/ZzqiZQute/element-plus-select-options-issue.git

When options are loaded in the `visible-change` event where visible is true, if I select the second option, the other options tag before this option shows weirdly.

![image](https://user-images.githubusercontent.com/39512431/99766629-6eb01e00-2b3c-11eb-9523-0af9b44c61d7.png)

**Comment by Ryan2128** [comment]
Thanks, it will be fixed soon.
