### ISSUE TITLE
[Bug Report] [Component] [select-v2] 当输入关键字，select-v2 特定情况不会调用 remote-method

### ISSUE THREAD

**Issue by xiangqunXiao** [element-plus/element-plus#6374]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Edge Win10`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgbXVsdGlwbGVcbiAgICBmaWx0ZXJhYmxlXG4gICAgcmVtb3RlXG4gICAgOnJlbW90ZS1tZXRob2Q9XCJyZW1vdGVNZXRob2RcIlxuICAgIGNsZWFyYWJsZVxuICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgOmxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgc3RhdGVzID0gW1xuICAnQWxhYmFtYScsXG4gICdBbGFza2EnLFxuICAnQXJpem9uYScsXG4gICdBcmthbnNhcycsXG4gICdDYWxpZm9ybmlhJyxcbiAgJ0NvbG9yYWRvJyxcbiAgJ0Nvbm5lY3RpY3V0JyxcbiAgJ0RlbGF3YXJlJyxcbiAgJ0Zsb3JpZGEnLFxuICAnR2VvcmdpYScsXG4gICdIYXdhaWknLFxuICAnSWRhaG8nLFxuICAnSWxsaW5vaXMnLFxuICAnSW5kaWFuYScsXG4gICdJb3dhJyxcbiAgJ0thbnNhcycsXG4gICdLZW50dWNreScsXG4gICdMb3Vpc2lhbmEnLFxuICAnTWFpbmUnLFxuICAnTWFyeWxhbmQnLFxuICAnTWFzc2FjaHVzZXR0cycsXG4gICdNaWNoaWdhbicsXG4gICdNaW5uZXNvdGEnLFxuICAnTWlzc2lzc2lwcGknLFxuICAnTWlzc291cmknLFxuICAnTW9udGFuYScsXG4gICdOZWJyYXNrYScsXG4gICdOZXZhZGEnLFxuICAnTmV3IEhhbXBzaGlyZScsXG4gICdOZXcgSmVyc2V5JyxcbiAgJ05ldyBNZXhpY28nLFxuICAnTmV3IFlvcmsnLFxuICAnTm9ydGggQ2Fyb2xpbmEnLFxuICAnTm9ydGggRGFrb3RhJyxcbiAgJ09oaW8nLFxuICAnT2tsYWhvbWEnLFxuICAnT3JlZ29uJyxcbiAgJ1Blbm5zeWx2YW5pYScsXG4gICdSaG9kZSBJc2xhbmQnLFxuICAnU291dGggQ2Fyb2xpbmEnLFxuICAnU291dGggRGFrb3RhJyxcbiAgJ1Rlbm5lc3NlZScsXG4gICdUZXhhcycsXG4gICdVdGFoJyxcbiAgJ1Zlcm1vbnQnLFxuICAnVmlyZ2luaWEnLFxuICAnV2FzaGluZ3RvbicsXG4gICdXZXN0IFZpcmdpbmlhJyxcbiAgJ1dpc2NvbnNpbicsXG4gICdXeW9taW5nJyxcbl1cbmNvbnN0IGxpc3QgPSBzdGF0ZXMubWFwKChpdGVtKTogTGlzdEl0ZW0gPT4ge1xuICByZXR1cm4geyB2YWx1ZTogYHZhbHVlOiR7aXRlbX1gLCBsYWJlbDogYGxhYmVsOiR7aXRlbX1gIH1cbn0pXG5cbmludGVyZmFjZSBMaXN0SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xufVxuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWY8TGlzdEl0ZW1bXT4oW10pXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxuXG5jb25zdCByZW1vdGVNZXRob2QgPSAocXVlcnk6IHN0cmluZykgPT4ge1xuICBjb25zb2xlLndhcm4oJ3F1ZXJ5JywgcXVlcnkpXG4gIGlmIChxdWVyeSAhPT0gJycpIHtcbiAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgICBvcHRpb25zLnZhbHVlID0gbGlzdC5maWx0ZXIoKGl0ZW0pID0+IHtcbiAgICAgICAgcmV0dXJuIGl0ZW0ubGFiZWwudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5LnRvTG93ZXJDYXNlKCkpID4gLTFcbiAgICAgIH0pXG4gICAgfSwgMjAwKVxuICB9IGVsc2Uge1xuICAgIG9wdGlvbnMudmFsdWUgPSBbXVxuICB9XG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

https://watch.screencastify.com/v/oVXJsCL9frkNFmkUShW2  复现步骤录屏。
注意看控制台打印的信息。

### What is Expected?

当失去焦点时，由于输入值自动清空。那么之后获取焦点，并输入相同关键字，此时关键字是从空发生变化应该触发 remote-method 方法

### What is actually happening?

没有触发 remote-method 传入的方法

### Additional comments

_(empty)_

**Comment by xiangqunXiao** [comment]
@sxzz 请问这个 issue 目前还没人确认过吗？

**Comment by YujiaCheng1996** [comment]
我也遇到了2.1.11版，不仅是select-v2，el-select为multiple时有时也不触发

**Comment by xiangqunXiao** [comment]
@YunYouJun 这个问题挺严重的，过去了 2 个月居然没有 1 个团队成员来确认过？

**Comment by YunYouJun** [comment]
Sorry for your bad experience. We will fix this as soon as possible.

**Comment by YunYouJun** [comment]
I tried to test.

But I found that the dropdown panel content that appears is the same as what I get by entering the `c` query, so there seems to be no need to re-trigger.

@JeremyWuuuuu Can you have a look?

**Comment by xiangqunXiao** [comment]
> Sorry for your bad experience. We will fix this as soon as possible.

Thanks.在 bug 修复上，团队时间和人手不够用大家可以理解，但希望在确认 issue 并打 label 这个环节能尽快的反馈。
未打上 bug 的 label，即使我想提 pr 修复，从流程上也是要等你们打 label 确认是应该通过修改源码方式来修复，长时间的未确认状态会导致其它开发者也不敢提 pr 来修复。
