### ISSUE TITLE
[Bug Report] [Component] [popover] `<el-popover>`'s content won't be destroyed with `:teleported="false"`

### ISSUE THREAD

**Issue by CarterLi** [element-plus/element-plus#6378]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome 98.0.4758.102 / macOS 12.1`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IFRlc3QgZnJvbSAnLi9UZXN0LnZ1ZSdcbmNvbnN0IGN0cmwgPSByZWFjdGl2ZSh7XG4gIHNob3c6IHRydWUsXG59KVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY3RybC5zaG93ID0gIWN0cmwuc2hvd1wiPlJlbW92ZTwvZWwtYnV0dG9uPlxuICA8ZWwtcG9wb3ZlciB2LWlmPVwiY3RybC5zaG93XCIgdHJpZ2dlcj1cImNsaWNrXCIgOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMTZweFwiPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8VGVzdCAvPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSIsIlRlc3QudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlRFU1RURVNUVEVTVFRFU1Q8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgb25Vbm1vdW50ZWQsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbm9uVW5tb3VudGVkKCgpID0+IHtcbiAgYWxlcnQoXCJVbm1vdW50ZWRcIilcbn0pXG48L3NjcmlwdD5cbiJ9)

### Steps to reproduce

App.vue

```vue
<script setup lang="ts">
import { ref } from 'vue'
import Test from './Test.vue'
const show = ref(true)
</script>
<template>
  <el-button @click="show = !show">Remove</el-button>
  <el-popover v-if="show" :teleported="false">
    <template #reference>
      <el-button>Hover to activate</el-button>
    </template>
    <Test />
  </el-popover>
</template>
```

Test.vue

```vue
<template>
  <div>TESTTESTTESTTEST</div>
</template>
<script setup lang="ts">
import { onUnmounted, onMounted } from 'vue'
onUnmounted(() => {
  alert("Unmounted")
})
</script>
```

### What is Expected?

当el-popover被v-if销毁时（点击Remove按钮），应该触发 `Test` 的 `onUnmounted` 事件，弹出`Unmounted`提示

### What is actually happening?

`onUnmounted` 事件没有触发，没有弹出提示

### Additional comments

这个bug影响所有内部依赖 `el-popover` 的组件。我是在 `el-select` 组件上发现的，当使用 `<el-select :teleported="false">` 时，内部的 `<el-option>` 组件永远不会被销毁，导致内存泄露（例如 `el-option` 里面注册的 watch 都不会被销毁）和其他奇怪bug

**Comment by CarterLi** [comment]
我们有在popover中使用select的需求。`:teleported="false"` 用于防止点击 select 的下拉框时意外关闭 popover

```html
<el-popover>
    <template #reference>
      <el-button>Click to activate</el-button>
    </template>
   <el-select :teleported="false">
     <el-option />
   </el-select>
</el-popover>
```

在这个bug修复并发版之前，有没有什么方法work-around一下呢？

**Comment by msidolphin** [comment]
https://element-plus.org/en-US/component/popover.html#attributes please ref `persistent`

**Comment by CarterLi** [comment]
> https://element-plus.org/en-US/component/popover.html#attributes please ref `persistent`

这个bug和persistent没关系吧，就算persistent为true，*移除* popover 组件的时候 popover 内部的组件也应该被移除

[另外 el-select 内部指定了 persistent 为 true](https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/select.vue)，用户也没法改

**Comment by msidolphin** [comment]
> > https://element-plus.org/en-US/component/popover.html#attributes please ref `persistent`
> 
> 这个bug和persistent没关系吧，就算persistent为true，**销毁** popover 组件本身的时候 popover 内部的组件也应该被移除
> 
> [另外 el-select 内部指定了 persistent 为 true](https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/select.vue)，用户也没法改

你为何不验证下呢？persistent为false才对

**Comment by CarterLi** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/6134068/156728090-71654274-da73-42df-a601-b559b4b822ca.png">

我眼瞎吗？

**Comment by CarterLi** [comment]
> 就算persistent为true

就算persistent为false

我写错了

**Comment by CarterLi** [comment]
设置persistent=false能否解决这个问题我没试

我的意思是

1. 就算用户指定了persistent=true，父级组件都被v-if销毁了，内部的子组件不管要不要persistent都应该被销毁
2. el-select内部使用的el-tooltip指定了persistent=true，用户没法改

**Comment by CarterLi** [comment]
不过我觉得el-select应该把persistent这个属性开放给用户设置

**Comment by msidolphin** [comment]
> 设置persistent=false能否解决这个问题我没试
> 
> 我的意思是
> 
> 1. 就算用户指定了persistent=true，父级组件都被v-if销毁了，内部的子组件不管要不要persistent都应该被销毁
> 2. el-select内部使用的el-tooltip指定了persistent=true，用户没法改

teleported设置为false是存在问题，但是你的需求并不需要把popover的teleported设置为false
```vue
<el-popover v-if="show" :persistent="false">
    <template #reference>
      <el-button>Click to activate</el-button>
    </template>
    <el-select v-model="value" :teleported="false">
        <el-option />
      </el-select>
  </el-popover>
```

**Comment by CarterLi** [comment]
el-select没有teleported属性啊，内部是写死的

我都截图给你了哥。。。

**Comment by msidolphin** [comment]
> el-select没有teleported属性啊，内部是写死的
> 
> 我都截图给你了哥。。。

我那是复制你的代码。。。

**Comment by msidolphin** [comment]
> el-select没有teleported属性啊，内部是写死的
> 
> 我都截图给你了哥。。。

https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IFRlc3QgZnJvbSAnLi9UZXN0LnZ1ZSdcbmNvbnN0IGN0cmwgPSByZWFjdGl2ZSh7XG4gIHNob3c6IHRydWUsXG59KVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY3RybC5zaG93ID0gIWN0cmwuc2hvd1wiPlJlbW92ZTwvZWwtYnV0dG9uPlxuICA8ZWwtcG9wb3ZlciB2LWlmPVwiY3RybC5zaG93XCIgdHJpZ2dlcj1cImNsaWNrXCIgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBzdHlsZT1cIm1hcmdpbi1yaWdodDogMTZweFwiPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8VGVzdCAvPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSIsIlRlc3QudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlRFU1RURVNUVEVTVFRFU1Q8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgb25Vbm1vdW50ZWQsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbm9uVW5tb3VudGVkKCgpID0+IHtcbiAgYWxlcnQoXCJVbm1vdW50ZWRcIilcbn0pXG48L3NjcmlwdD5cbiJ9 你验证下这个

**Comment by msidolphin** [comment]
> 不过我觉得el-select应该把persistent这个属性开放给用户设置

这个属性会放开

**Comment by CarterLi** [comment]
persistent=false我已经验证过了是可以的。但是persistent=false也只是workaround这个bug的一种手段，不是真正解决bug的方式

**Comment by msidolphin** [comment]
> persistent=false我已经验证过了是可以的。但是persistent=false也只是workaround这个bug的一种手段，不是真正解决bug的方式

我的意思是popover的teleported不要设置为false，除非你目前非得这样

**Comment by CarterLi** [comment]
> > persistent=false我已经验证过了是可以的。但是persistent=false也只是workaround这个bug的一种手段，不是真正解决bug的方式
> 
> 我的意思是popover的teleported不要设置为false，除非你目前非得这样

老哥你还是没懂。

popover的teleported**我没有设置为false**。但是为了在popover中使用select，**select的teleported必须设置为false**

因为如果select的下拉框被teleport到body上，这个select的下拉框就不是popover下拉框的子元素，导致点击select下拉框会关闭popover的下拉框

**Comment by msidolphin** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/26672484/156733052-412f9237-02ff-4e4e-b046-8450d7d5157e.png">
ni zhe l你这里提到的不是销毁问题吗

**Comment by CarterLi** [comment]
是el-select的子元素el-option没有销毁

<img width="864" alt="image" src="https://user-images.githubusercontent.com/6134068/156733179-8d3f5721-e2f4-4dd3-96c0-abd323381beb.png">

我写得很清楚

**Comment by CarterLi** [comment]
el-popover是根因，el-select是表象。el-option上面绑定了大量watch，el-select销毁之后这些watch还在跑

**Comment by CarterLi** [comment]
https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/useOption.ts#L86

**Comment by msidolphin** [comment]
> el-popover是根因，el-select是表象。el-option上面绑定了大量watch，el-select销毁之后这些watch还在跑

ok, 明白了，你可以先patch解决下
