### ISSUE TITLE
Some small things

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#638]
Hey, it's me again. I find some small things this time.
1. `Select` seems has two panel when animating. And the shadow is heavier than other popver. The small triangle is bigger than others.
![image](https://user-images.githubusercontent.com/38392315/99771728-8db2ae00-2b44-11eb-8928-e3db07dae222.png)![image](https://user-images.githubusercontent.com/38392315/99771787-a622c880-2b44-11eb-99b5-d70aafc8f3f1.png)![image](https://user-images.githubusercontent.com/38392315/99771813-b33fb780-2b44-11eb-9e19-546346359c78.png)
2. `Popver` trigger="focus", when blur, panel still open.
![image](https://user-images.githubusercontent.com/38392315/99772310-7de79980-2b45-11eb-913f-8cce71c816e0.png)
3. `Notification` when open, has no animation.
4. `MessageBox prompt`, default value is null.
![image](https://user-images.githubusercontent.com/38392315/99772616-11b96580-2b46-11eb-9d8c-ceb5767027e0.png)
5. `Cascader`
(1). Doc has wrong style.
(2). When click a menu that has children(for example: "设计原则"), panel closed.
(3). When mouse move on the panel, sometimes the panel jumped left and right cause of no more space.
![image](https://user-images.githubusercontent.com/38392315/99772821-71b00c00-2b46-11eb-99e9-c02d66a1d4b1.png)

**Comment by JeremyWuuuuu** [comment]
Thanks for raising this issue!
One thing that I wanted to ask is which version of `EP` and `Vue` you are current using?
Could you provide me some information?
Or this is what you found in the documentation website?

**Comment by JeremyWuuuuu** [comment]
This is definitely helpful for making this product better!

**Comment by JeremyWuuuuu** [comment]
For the first issue I think @SimonaliaChen had a fix last month to fix this by adding `transform-origin` in order to the the animation ordering correct.

**Comment by JeremyWuuuuu** [comment]
Recording for the `Popover` issue, seems that it can be correctly responded by blurring out of focus.
![Screen Recording 2020-11-20 at 4 13 57 PM](https://user-images.githubusercontent.com/15975785/99776515-ea659700-2b4b-11eb-97d8-7381195aa06b.gif)

**Comment by kooriookami** [comment]
> Thanks for raising this issue!
> One thing that I wanted to ask is which version of `EP` and `Vue` you are current using?
> Could you provide me some information?
> Or this is what you found in the documentation website?

Yes, I just found in the doc at this stage. When the version is stable, I will use it in some projects and find other problems.

**Comment by kooriookami** [comment]
> Recording for the `Popover` issue, seems that it can be correctly responded by blurring out of focus.(For both keyboard navigation and mouse clicking)
> ![Screen Recording 2020-11-20 at 4 13 57 PM](https://user-images.githubusercontent.com/15975785/99776515-ea659700-2b4b-11eb-97d8-7381195aa06b.gif)

I compared it with element 2.x. Version 2.x when mouse click and release, it will close.

**Comment by JeremyWuuuuu** [comment]
On the 3rd issue is definitely a regression issue, I'll make sure it's fixed.

**Comment by JeremyWuuuuu** [comment]
> > Recording for the `Popover` issue, seems that it can be correctly responded by blurring out of focus.(For both keyboard navigation and mouse clicking)
> > ![Screen Recording 2020-11-20 at 4 13 57 PM](https://user-images.githubusercontent.com/15975785/99776515-ea659700-2b4b-11eb-97d8-7381195aa06b.gif)
> 
> I compared it with element 2.x. Version 2.x when mouse click and release, it will close.

Yep, I just double checked with the v2 version, I believe v2 version is handling this with `mousedown` an `mouseup`, in this case `focus` is supposed to stay focus on ONE element before user move focus to the others, I think the v2 version is somehow wrong.

**Comment by kooriookami** [comment]
I agree v3 can do better. Some break changes are inevitable.

**Comment by JeremyWuuuuu** [comment]
> 4. MessageBox prompt, default value is null.
This one is checked as a bug.

**Comment by JeremyWuuuuu** [comment]
> I agree v3 can do better. Some break changes are inevitable.
Yep, I think I need to mention the change on documentaion

**Comment by JeremyWuuuuu** [comment]
> Cascader 
> (1). Doc has wrong style.
> (2). When click a menu that has children(for example: "设计原则"), panel closed.
> (3). When mouse move on the panel, sometimes the panel jumped left and right cause of no more space.

So for (2), I am sure that this one is somehow related to a PR I made recently #597. This needs to be properly discussed, I wasn't expecting this to be happened, this should be covered in tests I believe. 
Also cc @zazzaz we need to find another way to fix the issue.
For (3), because that we have took a bold upgrade on the `vue-popper`'s core dependency `@popperjs`, now `@popperjs` will reposition all popups when there were no sufficient space for popups. So the jumpy popup is working as expected (this might be different from v2 version because the core dependency has been updated).

**Comment by JeremyWuuuuu** [comment]
So we have 4 problems here to fix. Thanks again for filing up this issue

**Comment by kooriookami** [comment]
Thank you as well.

**Comment by JeremyWuuuuu** [comment]
@kooriookami I think all the problems except `Select` animation has already been solved, and will be released in the next version. cc @SimonaliaChen she is going to fix that issue later.
