### ISSUE TITLE
[Bug Report] [i18n] [message-box] ElMessageBox does not supprt I18N

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#6381]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29uZmlnLXByb3ZpZGVyIDpsb2NhbGU9XCJtYXBbbG9jYWxlXVwiIDprZXk9XCJsb2NhbGVcIj5cbiAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gdGhlIE1lc3NhZ2UgQm94PC9lbC1idXR0b24+XG4gICAgPGVsLXNlbGVjdD48L2VsLXNlbGVjdD5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInN3bGFuZ1wiPnN3aXRjaCBsYW5nOiB7e21hcFtsb2NhbGVdLm5hbWV9fTwvZWwtYnV0dG9uPlxuICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3gsIEVsTWVzc2FnZSwgRWxDb25maWdQcm92aWRlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB6aENOIGZyb20gXCJlbGVtZW50LXBsdXMvbGliL2xvY2FsZS9sYW5nL3poLWNuXCI7XG5pbXBvcnQgZW4gZnJvbSBcImVsZW1lbnQtcGx1cy9saWIvbG9jYWxlL2xhbmcvZW5cIjtcbmltcG9ydCB0eXBlIHsgQWN0aW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmFsZXJ0KCdUaGlzIGlzIGEgbWVzc2FnZScsICdUaXRsZScsIHtcbiAgICBjYWxsYmFjazogKGFjdGlvbjogQWN0aW9uKSA9PiB7XG4gICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICB0eXBlOiAnaW5mbycsXG4gICAgICAgIG1lc3NhZ2U6IGBhY3Rpb246ICR7YWN0aW9ufWAsXG4gICAgICB9KVxuICAgIH0sXG4gIH0pXG59XG5jb25zdCBtYXAgPSBbemhDTiwgZW5dO1xuY29uc3QgbG9jYWxlID0gcmVmKDApO1xuY29uc3Qgc3dsYW5nID0gKCkgPT4ge1xuICBpZiAobG9jYWxlLnZhbHVlID09PSAxKSB7XG4gICAgbG9jYWxlLnZhbHVlID0gMDtcbiAgfSBlbHNlIHtcbiAgICBsb2NhbGUudmFsdWUgPSAxO1xuICB9XG59O1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e1wiZWxlbWVudC1wbHVzL2xpYi9sb2NhbGUvbGFuZy96aC1jblwiOlwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4wLjQvZGlzdC9sb2NhbGUvemgtY24ubWpzXCIsXCJlbGVtZW50LXBsdXMvbGliL2xvY2FsZS9sYW5nL2VuXCI6XCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjAuNC9kaXN0L2xvY2FsZS9lbi5tanNcIn19In0=)

### Steps to reproduce

1. call ElMessageBox in click event callback
2. the i18n config will not work.

### What is Expected?

Show button text in given locale

### What is actually happening?

Always show in English

### Additional comments
I tracked the translation function and find that the `useGlobalConfig` will not work in async callback, because it depends on the inject that only work in setup lifecycle hook, I have no idea to solve it, but maybe we can create a instance in setup but not to show it instantly, or maybe something else...

update: I try to call ElMessageBox in setup directly, but it still not working, maybe something else causing this bug.
Please check all components using i18n if it can be called in an async way.

**Comment by zhangbinhub** [comment]
I have the same problem.
However, Element Plus 2.0.1 is normal

**Comment by KawaiiZapic** [comment]
> I have the same problem. However, Element Plus 2.0.1 is normal.
> 
> 2.0.5 still has this problem

https://element-plus.org/zh-CN/component/message-box.html#app-context-inheritance-2-0-4
Maybe read this.
