### ISSUE TITLE
[Bug Report] [Component] [select] select下拉多选样式优化

### ISSUE THREAD

**Issue by youguangsheng** [element-plus/element-plus#6387]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `版本 98.0.4758.102（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICBhbGxvdy1jcmVhdGVcbiAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJDaG9vc2UgdGFncyBmb3IgeW91ciBhcnRpY2xlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmPHN0cmluZ1tdPihbXSlcbi8vIOmAieS4rUhUTUwsamF2YXNjcmlwdFxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnSFRNTCcsXG4gICAgbGFiZWw6ICdIVE1MJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnQ1NTJyxcbiAgICBsYWJlbDogJ0NTUycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ0phdmFTY3JpcHQnLFxuICAgIGxhYmVsOiAnSmF2YVNjcmlwdCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ1Z1ZScsXG4gICAgbGFiZWw6ICdWdWUnLFxuICB9LCBcbiAge1xuICAgIHZhbHVlOiAnUmVhY3QnLFxuICAgIGxhYmVsOiAnUmVhY3QnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

1.多选设置，选中两个并且只有一行，外框变大内容居中两侧空白，再次聚焦样式重新计算外宽恢复正常
2.选中多行，会出现空白一行

### What is Expected?

1.由内容撑开，无空白行，选项一个接一个
2.多选自定义设置高度范围，超出可显示滚动条

### What is actually happening?

1.多选设置，选中两个并且只有一行，外框变大内容居中两侧空白，再次聚焦样式重新计算外宽恢复正常
2.选中多行，会出现空白一行

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
Fixed
