### ISSUE TITLE
[Feature Request] [TypeScript] [date-picker] DatePicker 的type新增yearrange

### ISSUE THREAD

**Issue by zhxqc** [element-plus/element-plus#6388]
Feature type: **`TypeScript`**

## Details

- Enhanced compone nt name: `date-picker`

## Description

期望DatePicker 的type新增yearrange类型

**Comment by msidolphin** [comment]
这个year用select不就满足了吗

**Comment by zhxqc** [comment]
产品要一个类似于daterange的yearrange效果😭 看element团队评估觉得有没有必要加这种功能，如果有必要的话我可以提个pr，要是觉得没必要我就去想办法解决产品

**Comment by zhxqc** [comment]
封装了一下两个type是year的el-date-picker，把产品糊弄过去了，，

**Comment by msidolphin** [comment]
> 产品要一个类似于daterange的yearrange效果😭 看element团队评估觉得有没有必要加这种功能，如果有必要的话我可以提个pr，要是觉得没必要我就去想办法解决产品

欢迎提交pr👏

**Comment by to-Meeko** [comment]
> 

我这里有个weekrange的需求[捂脸]

**Comment by geekFeier** [comment]
我这有个 periodRange 、 seasonRange、  yearRange的需求[捂脸][捂脸][捂脸]

**Comment by webguosai** [comment]
可以看看这个，包含了yearrange https://github.com/byronogis/datepicker-enhanced
