### ISSUE TITLE
[Feature Request] [Enhancement] [loading] el loading unmount when closed

### ISSUE THREAD

**Issue by zcmk123** [element-plus/element-plus#6392]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `loading`

## Description

everytime call ElLoading.service or use loading directive. An app created, but when loading closed, app still exsit. In vue devtools you can find multiple loading instance.

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/20919760/156512628-69aa9f8d-37fc-4215-9bb6-52baf0a7a49f.png)

**Comment by zcmk123** [comment]
https://github.com/element-plus/element-plus/blob/d3915ed493ec2b6772ccdbda4b950180cbe9174e/packages/components/loading/src/loading.ts#L32
function destroySelf did not unmount app instance, is there any possible negative effect?

**Comment by hoowhoami** [comment]
同样的疑惑，标记一下。

**Comment by zcmk123** [comment]
另外我看了一下源码，并试了一下ElLoading文档中的以下内容

需要注意的是，以服务的方式调用的全屏 Loading 是单例的。 若在前一个全屏 Loading 关闭前再次调用全屏 Loading，并不会创建一个新的 Loading 实例，而是返回现有全屏 Loading 的实例：

const loadingInstance1 = ElLoading.service({ fullscreen: true })
const loadingInstance2 = ElLoading.service({ fullscreen: true })
console.log(loadingInstance1 === loadingInstance2) // true

发现instance1并不等于instance2，每次都会返回一个新的instance。只是fullscreen模式下，上一个loading还没关闭，会先执行他的关闭逻辑。表面上看两个instance的close行为效果是一样的。但实际跟单例貌似有出入？

**Comment by yangkuo1993** [comment]
console.log(loadingInstance1 === loadingInstance2) // false
