### ISSUE TITLE
[Bug Report] [Style] [image] el-table-column 中使用 el-image 进行预览时，层级问题

### ISSUE THREAD

**Issue by smallShy** [element-plus/element-plus#6394]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.29`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome 98.0.4758.102 / win10`
- Build Tool: `Webpack`

### Related Component

- `el-image`

### Reproduction Link

[CodePen](https://codepen.io/smallshy/pen/ExbGRmb)

### Steps to reproduce

点击图片进行预览，预览层级与表格内容混乱

### What is Expected?

图片滚轮进行放大，缩小，鼠标移动等，不能触发表格内部操作

### What is actually happening?

会影响表格内部按钮等，

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
douplicate of #6335
