### ISSUE TITLE
[Feature Request] [Docs] 1.2.0-beta.6版本之前的文档还能查看吗？

### ISSUE THREAD

**Issue by a452746100** [element-plus/element-plus#6401]
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `All`

## Description

能否看到之前的文档

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
暂时可以翻看历史 commit 然后把文件下载下来

https://github.com/element-plus/element-plus/commits/gh-pages

**Comment by a452746100** [comment]
> 

麻烦再问下，文件我下载下来了，直接打开index.html文件无法预览，是要搭配其他环境才能预览页面吗？

**Comment by a452746100** [comment]
> 暂时可以翻看历史 commit 然后把文件下载下来。 For now, you can go through the history commit and download the file
> 
> https://github.com/element-plus/element-plus/commits/gh-pages

麻烦再问下，文件我下载下来了，直接打开index.html文件无法预览，是要搭配其他环境才能预览页面吗？

**Comment by a452746100** [comment]
> 暂时可以翻看历史 commit 然后把文件下载下来。 For now, you can go through the history commit and download the file
> 
> https://github.com/element-plus/element-plus/commits/gh-pages

谢谢
