### ISSUE TITLE
[Bug Report] [Style] [table, table-column] ElTable with fixed columns without scrollbar shows column shadows

### ISSUE THREAD

**Issue by matzeso** [element-plus/element-plus#6403]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `98.0.4758.109 (Official Build) (arm64) / Mac OS 12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnQmVybGluZXIgU3RyLiAxMjIzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnSGFiaWNodHdlZyA0MicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ0JhaG5ob2ZzdHIuIDEyMycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ1NpZW1lbnMgRGFjaCBXZWcgNTAxYScsXG4gIH0sXG5dO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDB2d1wiPlxuICAgIDxFbFRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCI+XG4gICAgICA8RWxUYWJsZUNvbHVtbiBmaXhlZCBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIDp3aWR0aD1cIjEzMFwiPlxuICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzbG90UHJvcHNcIj5cbiAgICAgICAgICA8c3BhbiBjbGFzcz1cInRleHQtZmxhbWUgd2hpdGVzcGFjZS1ub3dyYXBcIj57e1xuICAgICAgICAgICAgc2xvdFByb3BzLnJvdy5kYXRlXG4gICAgICAgICAgfX08L3NwYW4+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8L0VsVGFibGVDb2x1bW4+XG4gICAgICA8RWxUYWJsZUNvbHVtbiBzb3J0YWJsZSBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZSAxXCIgOndpZHRoPVwiMjAwXCIgLz5cbiAgICAgIDxFbFRhYmxlQ29sdW1uIHNvcnRhYmxlIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lIDJcIiA6d2lkdGg9XCIyMDBcIiAvPlxuICAgICAgPEVsVGFibGVDb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWUgM1wiIC8+XG4gICAgICA8RWxUYWJsZUNvbHVtblxuICAgICAgICBmaXhlZD1cInJpZ2h0XCJcbiAgICAgICAgOndpZHRoPVwiMjUwXCJcbiAgICAgICAgcHJvcD1cImFkZHJlc3NcIlxuICAgICAgICBsYWJlbD1cIkFkZHJlc3NcIlxuICAgICAgICBjdXN0b21GaWx0ZXI9XCJmdWxsdGV4dFwiXG4gICAgICAvPlxuICAgIDwvRWxUYWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4jYXBwIHtcbiAgZm9udC1mYW1pbHk6IEF2ZW5pciwgSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZjtcbiAgLXdlYmtpdC1mb250LXNtb290aGluZzogYW50aWFsaWFzZWQ7XG4gIC1tb3otb3N4LWZvbnQtc21vb3RoaW5nOiBncmF5c2NhbGU7XG4gIGNvbG9yOiAjMmMzZTUwO1xuICBtYXJnaW4tdG9wOiA2MHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

Resize the window so that content does not fit the available space. The table will show fixed column shadows correctly.
Resize the window that that all content fits the screen. Now, the shadows in the fixed columns are showing although no content is hidden behind the fixed columns.

### What is Expected?

When all content fits the screen, the fixed columns don't show a shadow.

### What is actually happening?

When all content fits the screen, the fixed columns show a shadow as if there is content hidden behind them.

### Additional comments

I figured out that this can likely be resolved by changing some CSS rules. 
The fixed column shadow is normally always shown, but its hidden (for the left side) e.g. when the following condition is met:
```
.el-table.is-scrolling-left .el-table-fixed-column--left.is-last-column::before {
  box-shadow: none;
}
```

When a table is big enough to not have horizontal scrolling, the classes `.is-scrolling-left` / `.is-scrolling-middle` / `.is-scrolling-right` do not exist. They only exist, when `.el-table--scrollable-x` is present.

So for me I could fix this problem by adding the following css:
```
.el-table:not(.el-table--scrollable-x) .el-table-fixed-column--left.is-last-column::before,
.el-table:not(.el-table--scrollable-x) .el-table-fixed-column--right.is-first-column::before {
  box-shadow: none;
}
```

**Comment by msidolphin** [comment]
fix #6320
