### ISSUE TITLE
[Feature Request] [Enhancement] [date-picker] How to customize the first-day-of-week settings?

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6418]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `date-picker`, `calendar`

## Description

Depending on the business rather than the language environment.

**Comment by Edric-Li** [comment]
My requirement is that the project has many Date Picker, individual components, and I need to change the week start day.

**Comment by Edric-Li** [comment]
It is recommended to be consistent with Element2 by adding the first-day-fo-week parameter.

**Comment by iamkun** [comment]
Element Plus's DatePicker uses date time lib Dayjs (https://day.js.org/) .

That is to say, just to set the current Day.js locale to change the `weekStart ` config. 

ref: https://day.js.org/docs/en/customization/customization

**Comment by Edric-Li** [comment]
I use CDN loading and it doesn't work as expected, is there something wrong with the way I'm using it?

**Comment by Edric-Li** [comment]
![image](https://user-images.githubusercontent.com/50992790/156913422-57ebbee9-c0c0-4e62-b8bf-68411361588b.png)
