### ISSUE TITLE
[Bug Report] [Component] [table-column] 声明type=expand后，点击展开列会刷新相应表格行的DOM

### ISSUE THREAD

**Issue by bluryar** [element-plus/element-plus#6427]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgXG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiByb3cta2V5PVwiZGF0ZVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cImV4cGFuZFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwicHJvcHNcIj5cbiAgICAgICAgPHA+U3RhdGU6IHt7IHByb3BzLnJvdy5zdGF0ZSB9fTwvcD5cbiAgICAgICAgPHA+Q2l0eToge3sgcHJvcHMucm93LmNpdHkgfX08L3A+XG4gICAgICAgIDxwPkFkZHJlc3M6IHt7IHByb3BzLnJvdy5hZGRyZXNzIH19PC9wPlxuICAgICAgICA8cD5aaXA6IHt7IHByb3BzLnJvdy56aXAgfX08L3A+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgcHJvcD1cImRhdGVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgcHJvcD1cIm5hbWVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgcHJvcD1cImltZ1wiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwicHJvcHNcIj5cblx0XHRcdFx0XHQ8aW1nIHNyYz1cInByb3BzLnJvdy5pbWdcIj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 审查页面元素，观察 `<tbody>` 下第一个 `<tr>` ，手动给这个 `<tr>` 加上任意一个id。 `id="blabal1111"`
2. 展开被加上id的列，id不见了

### What is Expected?

保留被展开行的DOM

### What is actually happening?

被展开行的DOM被替换

### Additional comments

当表格行存在预览图时，展开行就会刷新图片，且会发生高度塌陷引起表格的“闪烁”。

**Comment by nieyuyao** [comment]
```
 const wrappedRowRender = (row: T, $index: number) => {
    const store = props.store
    const { isRowExpanded, assertRowKey } = store
    const { treeData, lazyTreeNodeMap, childrenColumnName, rowKey } =
      store.states
    const hasExpandColumn = store.states.columns.value.some(
      ({ type }) => type === 'expand'
    )
    if (hasExpandColumn && isRowExpanded(row)) {
      const renderExpanded = parent.renderExpanded
      const tr = rowRender(row, $index, undefined)
      if (!renderExpanded) {
        console.error('[Element Error]renderExpanded is required.')
        return tr
      }
      // 使用二维数组，避免修改 $index
      // Use a two dimensional array avoid modifying $index
      return [
        [
          tr,
          // ！！！插入被展开的节点
          h(
            'tr',
            {
              key: `expanded-row__${tr.key as string}`,
            },
            [
              h(
                'td',
                {
                  colspan: store.states.columns.value.length,
                  class: 'el-table__cell el-table__expanded-cell',
                }
                // [renderExpanded({ row, $index, store })]
              ),
            ]
          ),
        ],
      ]
    }
  }
```

这个像是因为，在行被展开时，上述代码会新增一个`<tr> vnode`，这可能会导致vue在patch是重新创建`dom`节点
