### ISSUE TITLE
[Bug Report] [Style] [dropdown-item] divided

### ISSUE THREAD

**Issue by uinio** [element-plus/element-plus#6437]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome/98.0`
- Build Tool: `Vite`

### Related Component

- `el-dropdown-item`

### Reproduction Link

[Element Plus Playground](https://element-[plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgIDxlbC1kcm9wZG93biBib3R0b20tcmlnaHQ+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJjb2xvcjpyZWRcIj4xMjM8L3NwYW4+XG4gICAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1tZW51IGNsYXNzPVwiZHJvcGRvd24tbWVudVwiPlxuICAgICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgICAgICA8ZWwtaWNvbiA6c2l6ZT1cIjIwXCI+XG4gICAgICAgICAgICAgICAgICA8a2V5IC8+XG4gICAgICAgICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgICAgICAgIOS/ruaUueWvhueggVxuICAgICAgICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpdmlkZWQ+XG4gICAgICAgICAgICAgICAgPGVsLWljb24gOnNpemU9XCIyMFwiPlxuICAgICAgICAgICAgICAgICAgPHJpZ2h0IC8+XG4gICAgICAgICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgICAgICAgIOmAgOWHuueZu+W9lVxuICAgICAgICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1kcm9wZG93bj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgIDxlbC1kcm9wZG93biBib3R0b20tcmlnaHQ+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJjb2xvcjpyZWRcIj4xMjM8L3NwYW4+XG4gICAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1tZW51IGNsYXNzPVwiZHJvcGRvd24tbWVudVwiPlxuICAgICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgICAgICDkv67mlLnlr4bnoIFcbiAgICAgICAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXZpZGVkPlxuICAgICAgICAgICAgICAgIOmAgOWHuueZu+W9lVxuICAgICAgICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1kcm9wZG93bj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

divided style issues

### What is Expected?

divided style issues

### What is actually happening?

divided style issues

### Additional comments

_(empty)_
![image](https://user-images.githubusercontent.com/49021590/156862143-dc7547d9-202f-4ac3-a974-e856b03f20e3.png)

**Comment by Alanscut** [comment]
fix #6328
