### ISSUE TITLE
vue3 warn

### ISSUE THREAD

**Issue by docming** [element-plus/element-plus#644]
vue3.0 corejs3.6.5
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: A plugin must either be a function or an object with an "install" function.

DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/async-validator/dist-web/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/mitt/dist/mitt.es.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by JeremyWuuuuu** [comment]
Can you provide a minimal reproducible repo or link for us to investigate?
