### ISSUE TITLE
[Bug Report] [Component] [table, popconfirm] el-table中操作列中有删除按钮，按钮添加点击弹出popconfirm事件，1、当teleported=true页面全屏后，popconfirm不显示 2、teleported=false,popconfirm被其它行覆盖

### ISSUE THREAD

**Issue by lozhu** [element-plus/element-plus#6443]
![QQ图片20220306112403](https://user-images.githubusercontent.com/68715772/156907903-a093ffa7-d481-4e97-ac07-d61d15c5e7d3.png)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.3`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`
- `el-popconfirm`

### Reproduction Link

[Link]()

### Steps to reproduce

（业务逻辑：角色管理页的el-table中有删除按钮，也有全屏按钮，点击删除按钮，会弹出popconfirm确认删除对话框）
场景1设置popconfirm属性teleported=true:
import screenfull 这个全屏功能模块，然后添加screenfull.toggle()全屏方法，点击全屏按钮，当页面全屏后,再点击“删除”按钮，给删除按钮设置的popconfirm不显示
场景2设置popconfirm属性teleported=false:
点击“删除”按钮，给按钮设置的popconfirm会被table行覆盖，原因可能是行与行的z-Index是1，然后popconfirm属于行内的子元素，z-index作用域在行内，所以父级的tr会覆盖popconfirm

### What is Expected?

设置popconfirm属性teleported=false后，popconfirm 在el-table中完全正常显示出来

### What is actually happening?

1、全屏后，teleported=true,popconfirm不显示（这个能理解，所以需要用到teleported=false)
2、设置popconfirm属性teleported=false后，popconfirm在el-table中显示不完全，被其它行覆盖

### Additional comments

_(empty)_

**Comment by lozhu** [comment]
主要是需要用到全屏啊，如果不需要全屏，直接设置teleported=true即可，要实现全屏，就得设置teleported=false,设置teleported=false后，行就会覆盖掉弹出的popconfirm，很头疼啊

**Comment by lozhu** [comment]
如果可以添加一个appendTo，有可能就可以了，自己指定popconfirm添加到的元素

**Comment by msidolphin** [comment]
没显示的问题应该是你自己层级有问题
