### ISSUE TITLE
[Bug Report] [Component] [select] If the data of el-option is later than v-model, el-select  will automatically create an option.

### ISSUE THREAD

**Issue by l-x-f** [element-plus/element-plus#6458]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome/99.0.4844.51`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgdmFsdWU6IDEsXG4gIG9wdGlvbnM6IFtdXG59KVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgdmFsdWU6IDEsXG4gICAgbGFiZWw6ICfpgInpobnkuIAnXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMixcbiAgICBsYWJlbDogJ+mAiemhueS6jCdcbiAgfVxuXVxuXG5zZXRUaW1lb3V0KCgpID0+IHtcbiAgc3RhdGUub3B0aW9ucyA9IGRhdGFcbn0sIDEwMDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLXNlbGVjdFxuICAgIHYtbW9kZWw9XCJzdGF0ZS52YWx1ZVwiXG4gICAgZmlsdGVyYWJsZVxuICAgIGFsbG93LWNyZWF0ZVxuICAgIGRlZmF1bHQtZmlyc3Qtb3B0aW9uXG4gICAgcGxhY2Vob2xkZXI9XCJwbGVhc2Ugc2VsZWN0XCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBzdGF0ZS5vcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

```vue
<script setup>
import { reactive } from 'vue'

const state = reactive({
  value: 1,
  options: []
})

const data = [
  {
    value: 1,
    label: '选项一'
  },
  {
    value: 2,
    label: '选项二'
  }
]

setTimeout(() => {
  state.options = data
}, 1000)
</script>

<template>
  <!-- Element Plus icons -->
  <el-select
    v-model="state.value"
    filterable
    allow-create
    default-first-option
    placeholder="please select"
  >
    <el-option
      v-for="item in state.options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
    >
    </el-option>
  </el-select>
</template>

```

### What is Expected?

I expected two options.

### What is actually happening?

But got three.

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/33000154/156979215-735b7d2d-d14e-4cfc-803d-8287aad3ca25.png)

**Comment by kooriookami** [comment]
Fixed
