### ISSUE TITLE
[Bug Report] [Component] [tabs] Tabs 标签页结合directive时只是隐藏了el-tab-pane,而label还在

### ISSUE THREAD

**Issue by ExtJSFantasy** [element-plus/element-plus#6460]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `'5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEF1dGggZnJvbSAnLi9Db21wLmpzJ1xuICBcbiAgZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICBzZXR1cCgpIHtcbiAgICAgIGNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcbiAgICAgIHJldHVybiB7IGFjdGl2ZU5hbWUgfVxuICAgIH0sXG4gICAgZGlyZWN0aXZlczoge1xuICAgIFx0J2F1dGgnOiBBdXRoXG4gIFx0fVxuIH0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCI+XG4gICAgPGVsLXRhYi1wYW5lIHYtYXV0aD1cIjBcIiBsYWJlbD1cIlVzZXJcIiBuYW1lPVwiZmlyc3RcIj5cbiAgICAgIFVzZXJcbiAgICA8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIkNvbmZpZ1wiIG5hbWU9XCJzZWNvbmRcIj5Db25maWc8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlJvbGVcIiBuYW1lPVwidGhpcmRcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCIgbmFtZT1cImZvdXJ0aFwiPlRhc2s8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0iLCJDb21wLmpzIjoiZXhwb3J0IGRlZmF1bHQge1xuICAgIG1vdW50ZWQoZWwsIGJpbmRpbmcpIHtcbiAgICAgICAgY29uc29sZS5sb2coYmluZGluZy52YWx1ZSwgJ2F1dGhiaW5kaW5nJylcbiAgICAgICAgY29uc3QgcmVjZWl2ZSA9IGJpbmRpbmcudmFsdWVcbiAgICAgICAgLy8g5pyJ5p2D6ZmQXG4gICAgICAgIGlmICghcmVjZWl2ZSkge1xuICAgICAgICAgICAgZWwucGFyZW50Tm9kZT8ucmVtb3ZlQ2hpbGQoZWwpXG4gICAgICAgIH1cbiAgICB9LFxufSJ9)

### Steps to reproduce

一个v-auth="0"

### What is Expected?

directive指令可以完整控制某一个tab显示或者隐藏

### What is actually happening?

只是隐藏了el-tab-pane,而label还在

### Additional comments

el-tabs是否可以做到通过指令控制完整的el-tab-pane不只是内容

**Comment by ExtJSFantasy** [comment]
> 你手动移除dom 之后并不会执行destroy 导致element无法知道tab-pane被销毁了， 这个例子可能是你更好的选择 https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEF1dGggZnJvbSAnLi9Db21wLmpzJ1xuICBpbXBvcnQgeyBoYXNBdXRoIH0gZnJvbSAnLi91dGlscy5qcydcbiAgZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICBzZXR1cCgpIHtcbiAgICAgIGNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcbiAgICAgIHJldHVybiB7IGFjdGl2ZU5hbWUsIGhhc0F1dGggfVxuICAgIH0sXG4gICAgZGlyZWN0aXZlczoge1xuICAgIFx0J2F1dGgnOiBBdXRoXG4gIFx0fVxuIH0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCI+XG4gICAgPGVsLXRhYi1wYW5lIHYtaWY9XCJoYXNBdXRoKDApXCIgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+XG4gICAgICBVc2VyXG4gICAgPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJDb25maWdcIiBuYW1lPVwic2Vjb25kXCI+Q29uZmlnPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJSb2xlXCIgbmFtZT1cInRoaXJkXCI+Um9sZTwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVGFza1wiIG5hbWU9XCJmb3VydGhcIj5UYXNrPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwiQ29tcC5qcyI6ImltcG9ydCB7IGhhc0F1dGggfSBmcm9tICcuL3V0aWxzLmpzJ1xuZXhwb3J0IGRlZmF1bHQge1xuICAgIG1vdW50ZWQoZWwsIGJpbmRpbmcpIHtcbiAgICAgICAgY29uc29sZS5sb2coYmluZGluZy52YWx1ZSwgJ2F1dGhiaW5kaW5nJylcbiAgICAgICAgY29uc3QgcmVjZWl2ZSA9IGJpbmRpbmcudmFsdWVcbiAgICAgICAgLy8g5pyJ5p2D6ZmQXG4gICAgICAgIGlmIChoYXNBdXRoKHJlY2VpdmUpKSB7XG4gICAgICAgICAgICBlbC5wYXJlbnROb2RlPy5yZW1vdmVDaGlsZChlbClcbiAgICAgICAgfVxuICAgIH0sXG59IiwidXRpbHMuanMiOiJleHBvcnQgY29uc3QgaGFzQXV0aCA9IChjb2RlKSA9PiB7XG4gIHJldHVybiAhIWNvZGVcbn0ifQ==

所以就反馈一下是否可以做到当使用指令形式也可满足

**Comment by HeftyKoo** [comment]
> > 你手动移除dom 之后并不会执行destroy 导致element无法知道tab-pane被销毁了， 这个例子可能是你更好的选择 https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEF1dGggZnJvbSAnLi9Db21wLmpzJ1xuICBpbXBvcnQgeyBoYXNBdXRoIH0gZnJvbSAnLi91dGlscy5qcydcbiAgZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgICBzZXR1cCgpIHtcbiAgICAgIGNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcbiAgICAgIHJldHVybiB7IGFjdGl2ZU5hbWUsIGhhc0F1dGggfVxuICAgIH0sXG4gICAgZGlyZWN0aXZlczoge1xuICAgIFx0J2F1dGgnOiBBdXRoXG4gIFx0fVxuIH0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCI+XG4gICAgPGVsLXRhYi1wYW5lIHYtaWY9XCJoYXNBdXRoKDApXCIgbGFiZWw9XCJVc2VyXCIgbmFtZT1cImZpcnN0XCI+XG4gICAgICBVc2VyXG4gICAgPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJDb25maWdcIiBuYW1lPVwic2Vjb25kXCI+Q29uZmlnPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJSb2xlXCIgbmFtZT1cInRoaXJkXCI+Um9sZTwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVGFza1wiIG5hbWU9XCJmb3VydGhcIj5UYXNrPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwiQ29tcC5qcyI6ImltcG9ydCB7IGhhc0F1dGggfSBmcm9tICcuL3V0aWxzLmpzJ1xuZXhwb3J0IGRlZmF1bHQge1xuICAgIG1vdW50ZWQoZWwsIGJpbmRpbmcpIHtcbiAgICAgICAgY29uc29sZS5sb2coYmluZGluZy52YWx1ZSwgJ2F1dGhiaW5kaW5nJylcbiAgICAgICAgY29uc3QgcmVjZWl2ZSA9IGJpbmRpbmcudmFsdWVcbiAgICAgICAgLy8g5pyJ5p2D6ZmQXG4gICAgICAgIGlmIChoYXNBdXRoKHJlY2VpdmUpKSB7XG4gICAgICAgICAgICBlbC5wYXJlbnROb2RlPy5yZW1vdmVDaGlsZChlbClcbiAgICAgICAgfVxuICAgIH0sXG59IiwidXRpbHMuanMiOiJleHBvcnQgY29uc3QgaGFzQXV0aCA9IChjb2RlKSA9PiB7XG4gIHJldHVybiAhIWNvZGVcbn0ifQ==
> 
> 所以就反馈一下是否可以做到当使用指令形式也可满足

想了解一下，在什么场景下需要使用指令？

**Comment by ExtJSFantasy** [comment]
@HeftyKoo 统一使用指令控制用户权限显隐

**Comment by HeftyKoo** [comment]
> @HeftyKoo 统一使用指令控制用户权限显隐

不建议这样做，这样会造成状态的冲突，如果没有其他问题，issue 我先关了
