### ISSUE TITLE
[Bug Report] [Component] [input] el-input suffix slot 如果放多个图标，或则放一个图标，并且开启clearable的时候会，输入文字会挡住图标，prefix也是一样的

### ISSUE THREAD

**Issue by grays820** [element-plus/element-plus#6464]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `all`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCExMUhlbGxvIFdvcmxkITExSGVsbG8gV29ybGQhMTFIZWxsbyBXb3JsZCExMUhlbGxvIFdvcmxkITExSGVsbG8gV29ybGQhMTFIZWxsbyBXb3JsZCExMUhlbGxvIFdvcmxkITExSGVsbG8gV29ybGQhMTFIZWxsbyBXb3JsZCExMUhlbGxvIFdvcmxkITExSGVsbG8gV29ybGQhMTFIZWxsbyBXb3JsZCExMUhlbGxvIFdvcmxkITExJylcbmltcG9ydCB7IENhbGVuZGFyLCBTZWFyY2ggfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cblxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiBjbGFzcz1cInctNTAgbS0yXCIgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF0ZVwiIGNsZWFyYWJsZT5cbiAgICAgICAgPHRlbXBsYXRlICNzdWZmaXg+XG4gICAgICAgICAgPGVsLWljb24gY2xhc3M9XCJlbC1pbnB1dF9faWNvblwiPjxjYWxlbmRhciAvPjwvZWwtaWNvbj5cbiAgICAgICAgICA8ZWwtaWNvbiBjbGFzcz1cImVsLWlucHV0X19pY29uXCI+PGNhbGVuZGFyIC8+PC9lbC1pY29uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9lbC1pbnB1dD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

如题

### What is Expected?

如题

### What is actually happening?

必现

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
这个是正常的吧，设计的时候就是用padding 去给suffix 和prefix 留位置

**Comment by grays820** [comment]
> 



> 这个是正常的吧，设计的时候就是用padding 去给suffix 和prefix 留位置

naiveui 就支持这样用，不需要人去控制 padding是可以解决

**Comment by Edric-Li** [comment]
这怎么能算正常呢，肯定是有问题的呀

**Comment by gjfei** [comment]
> 这怎么能算正常呢，肯定是有问题的呀

设计如此

**Comment by Edric-Li** [comment]
@gjfei  这个是确定的？实锤的？

**Comment by Edric-Li** [comment]
@gjfei 我觉得  这个明显不合理，不管技术如何实现，首先 这种需求是确实存在的，那么如果我这样做 还得让我去冲它的css 明显不太合理。

**Comment by Edric-Li** [comment]
@gjfei 我觉得这个设计不合理，如果真的是设计如此  建议 站在使用者的角度考虑一下。

**Comment by gjfei** [comment]
> @gjfei 我觉得这个设计不合理，如果真的是设计如此 建议 站在使用者的角度考虑一下。

我也认同你的，但是现在的设计就是如此，包括element-ui也是这么做的，我也不知道为什么要这样做

**Comment by Edric-Li** [comment]
@gjfei 你不知道为什么这么做？指的是我？还是Element UI呢？

**Comment by gjfei** [comment]
> Element UI

Element UI

**Comment by Edric-Li** [comment]
那就给Element UI提建议，或许会采纳又或许是一个bug呢？

**Comment by gjfei** [comment]
> 那就给Element UI提建议，或许会采纳又或许是一个bug呢？

这已经提了不是，但是没有官方的人出来发表意见，我也只是发表我自己的看法
这个东西的改动会比较大，牵扯的组件有点多

**Comment by HeftyKoo** [comment]
fixed by https://github.com/element-plus/element-plus/pull/7179
