### ISSUE TITLE
[Feature Request] 能否提供一个快捷切换暗黑或其他主题色的配置或方案呢

### ISSUE THREAD

**Issue by JF98** [element-plus/element-plus#6466]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

手动配置一些暗黑主题色颜色时，内部组件的css变量互相引用，一些细节的样式配置起来也颇为麻烦，能否提供一些快捷便利的操作呢

### Additional comments

_(empty)_

**Comment by Edric-Li** [comment]
提供一个主色，在配合调整亮度一个主题就出来了

**Comment by sxzz** [comment]
Duplicate of #3754 #5712
