### ISSUE TITLE
Lost Webpack SourceMap

### ISSUE THREAD

**Issue by docming** [element-plus/element-plus#647]
DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/mitt/dist/mitt.es.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/async-validator/dist-web/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by JeremyWuuuuu** [comment]
Could you describe your issue more with more details? Also please attach the minimal reproducible code for us to investigate.

**Comment by JeremyWuuuuu** [comment]
Unless you can provide us more detailed informations to investigate, we are not be able to help you with your problem, I am closing this issue due to no further response, feel free to reopen it if you have more informations to provide.
