### ISSUE TITLE
[Bug Report] [Docs] [All] Affix 固钉标题文字错误

### ISSUE THREAD

**Issue by liuchangxiaoba** [element-plus/element-plus#6470]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/affix.html)

### Steps to reproduce

直接看标题和左侧菜单标题

### What is Expected?

钉修改为定

### What is actually happening?

固定写成了固钉

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
就是固钉

**Comment by btea** [comment]
这个翻译是对的.
