### ISSUE TITLE
[Feature Request] [Enhancement] [input-number] Element 2 有 select方法 Plus 没有，不知道是废弃还是？

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6482]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `input-number`

**Comment by emojiiii** [comment]
看起来应该是废弃了，如果你想有这个功能，你可以用 `ref` 拿到内部的 `input`, 
大概意思就是 `this.$refs.inputNumberRef.input.value.select()`

**Comment by Edric-Li** [comment]
@emojiiii 好的，感谢！
