### ISSUE TITLE
[Bug Report] [Component] [All] 关于vue3中使用render函数 创建elementplus组件不生效问题

### ISSUE THREAD

**Issue by DATOULIN** [element-plus/element-plus#6487]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgXG5pbXBvcnQgTXlSZW5kZXIgZnJvbSAnLi9yZW5kZXIuanMnXG4gIFxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PG15LXJlbmRlci8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0iLCJyZW5kZXIuanMiOiJpbXBvcnQge2h9IGZyb20gJ3Z1ZSdcblxuZXhwb3J0IGRlZmF1bHQge1xuICAgIHJlbmRlcigpIHtcbiAgICAgICAgcmV0dXJuIGgoJ2VsLWlucHV0Jywge30sIFtdKVxuICAgIH1cbn0ifQ==)

### Steps to reproduce

import {h} from 'vue'

export default {
    render() {
        return h('el-input', {}, [])
    }
}

### What is Expected?

可以将input组件渲染出来

### What is actually happening?

无法解析input组件

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
请确保你已经全局注册了`el-input`组件，或者你可以局部按需导入input组件，eg：
```js
import {h} from 'vue'
import { ElInput } from 'element-plus'

export default {
  render() {
    return h(ElInput, {}, [])
  }
}
```

**Comment by DATOULIN** [comment]
你好，确定在main.js中全局注册组件了。通过template方式渲染组件是没问题的

**Comment by tolking** [comment]
那里是这么用的，你这样渲染出来就是

``` html
<el-input></el-input>
```

[查看文档](https://staging-cn.vuejs.org/api/render-function.html)

向上面老哥那样使用，或者

```js
import {h, resolveComponent} from 'vue'

export default {
    render() {
      	const component = resolveComponent('el-input')
        return h(component, {}, [])
    }
}
```
