### ISSUE TITLE
[Bug Report] [Component] [table, table-column] el-table显示不正常

### ISSUE THREAD

**Issue by DRJ31** [element-plus/element-plus#6490]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.36`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/drj31/pen/RwjzwOd)

### Steps to reproduce

如链接所示

### What is Expected?

表格正常显示

### What is actually happening?

表格只显示最后一列

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
duplicate with #5862
