### ISSUE TITLE
[Feature Request] [Enhancement] [calendar] Suggest adding first-day-of-week instead of introducing day js.

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6498]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `calendar`

#### Suggestions
align with element2 and add props. (Highly recommended)

Our project uses cdn to load ElementPlus.

In order to implement first-day-of-week, an additional day.js needs to be introduced.
Our project is very focused on the size of js files.

I've seen a lot of discussion in the community about this issue.
Many uses do not know how to set up first-day-of-week.

Element plus has greatly improved the experience form all other angles, but this is the only issue that has reduced the experience.

**Comment by sxzz** [comment]
@JeremyWuuuuu Maybe we can export dayjs from Element Plus? WDYT?

**Comment by Edric-Li** [comment]
@sxzz It is also a solution, but it is still better to provide a parameter.

**Comment by Edric-Li** [comment]
In our project, we introduced day js using cdn, but setting first-day-of-week still doesn't work, and now we're forced to tell users that we've temporarily disabled this feature.

**Comment by sxzz** [comment]
The dayjs you imported and the dayjs used by Element Plus are not the same instance, so let's consider exporting the dayjs we use.

**Comment by Edric-Li** [comment]
@sxzz Understood, but what puzzles me is that I think this parameter is very convenient, so why remove it in Element Plus.

**Comment by Edric-Li** [comment]
If Element Plus exports the day.js instance, it will solve my problem.

As for whether to increase this parameter, you guys are thinkging about it.

Is it possible to solve the problem in the next release!
