### ISSUE TITLE
[Feature Request] [Enhancement] [calendar] 建议增加一周的第一天，而不是引入day.js。

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6499]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `calendar`

## Description

建议。
与element2一样，并添加props。(强烈建议)

我们的项目使用cdn来加载ElementPlus。

为了实现first-day-of-week，需要引入一个额外的day.js。
我们的项目非常注重js文件的大小。

我看到社区里有很多关于这个问题的讨论。
很多使用不知道如何设置first-day-of-week。

Element plus从其他角度大大改善了体验，但这是唯一降低体验的问题。

**Comment by sxzz** [comment]
@JeremyWuuuuu Maybe we can export dayjs from Element Plus? WDYT?

**Comment by sxzz** [comment]
Duplicate of #6498
