### ISSUE TITLE
[Bug Report] [Style] [message] ElMessage按需导入缺少css了

### ISSUE THREAD

**Issue by bthulu** [element-plus/element-plus#6501]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Github Repo](https://github.com/bthulu/vite-ele-bug)

### Steps to reproduce

git clone https://github.com/bthulu/vite-ele-bug.git
cd vite-ele-bug
yarn
yarn dev

浏览器打开http://localhost:3000
单击页面上的唯一按钮

### What is Expected?

页面上方弹出提示

### What is actually happening?

页面最下方, 且背景不带颜色

### Additional comments

_(empty)_

**Comment by yaomk** [comment]
自动导入的话，不需要在`import { ElMessage } from 'element-plus'`这样引入了
