### ISSUE TITLE
[Bug Report] [Component] [select-v2] SelectV2在options的value是一个对象时，判断option是否选中的逻辑有问题

### ISSUE THREAD

**Issue by ztyzbb** [element-plus/element-plus#6502]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) biz-frame-generator/1.0.0 Chrome/98.0.4758.102 Electron/17.1.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IFt7XG4gIHZhbHVlOiB7XG4gICAgY29kZTogJzEnLFxuICAgIG5hbWU6ICd4J1xuICB9LFxuICBsYWJlbDogJ3gnXG59LCB7XG4gIHZhbHVlOiB7XG4gICAgY29kZTogJzInLFxuICAgIG5hbWU6ICd5J1xuICB9LFxuICBsYWJlbDogJ3knXG59LCB7XG4gIHZhbHVlOiB7XG4gICAgY29kZTogJzMnLFxuICAgIG5hbWU6ICd6J1xuICB9LFxuICBsYWJlbDogJ3onXG59XTtcblxuY29uc3Qgc2VsZWN0ZWQgPSByZWYoW10pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdC12MiB2LW1vZGVsPVwic2VsZWN0ZWRcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiBtdWx0aXBsZSBzdHlsZT1cIndpZHRoOiAyMDBweFwiLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

功能上希望选择多个对象，SelectV2似乎不支持直接在v-model中返回options中的对象，也不支持指定label的字段名，因此在每个对象外又套了一层，把对象放在value上，把显示名放在label上

### What is Expected?

希望在选中后，能在v-model中返回value的数组

### What is actually happening?

选中一个，下拉列表中所有都显示选中，似乎所有选项都被当成了一个选项

### Additional comments

查看了一下源码，在value是对象时，存在两次取valueKey的情况。

useSelect.ts中，onSelect函数405行在getValueIndex入参时已经取了一次valueKey，在getValueIndex内部如果value是对象，又会取一次valueKey，在select-dropdown.vue的isItemSelected中也有同样的问题，只不过第一次是写死取value，这个是否有问题

**Comment by emojiiii** [comment]
may be you can try to use value-key to achieve.
please see the [docs/value-key](https://element-plus.org/en-US/component/select-v2.html#selectv2-attributes)

**Comment by myzhangsan** [comment]
在这里想要获取的选择的对象值，而不是选择后的key值
