### ISSUE TITLE
[Feature Request] [Enhancement] [date-picker] Time formatting It is recommended to support lowercase yyyy as well as dd, etc.

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6503]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `date-picker`

## Description

After upgrading to Element Plus, I found that using lowercase yyyy as well as dd did not work properly, using the larger ones worked fine.

In Element2 and other frameworks, lowercase yyyy and dd work fine.

**Comment by Galen-xiaogao** [comment]
是因为换了时间库原因的导致，day时间库都是大写，moment时间库是小写

**Comment by Edric-Li** [comment]
Can the official consider doing a compatibility? Or specify it in the documentation.

**Comment by btea** [comment]
The document is described here
![image](https://user-images.githubusercontent.com/24516654/158006052-02ea1b6e-cc67-4e7e-9710-132ad2ea588e.png)

**Comment by Edric-Li** [comment]
@btea Okay,thank you for your answer.
