### ISSUE TITLE
[Feature Request] Is it possible to add a way to quickly change the theme color.

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6504]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

We use the CDN form to load Element Plus.

In our website, users can change the theme color by themselves.

As I understand it, a theme is derived by changing the main color to a different brightness.

Our current approach is to get a primary color, change it to a different brightness, get other colors, and insert a part of css to achieve that.

But the operation is tedious, and you have to study exactly how much brightness the ELement Plus has.

It would be handy to have such a method.

Our current implementation:

```
namespace ElementTheme {

    const colorDictionary = {
        "--el-color-primary": "Accent 1",
        "--el-color-primary-light-1": "Accent 1 10",
        "--el-color-primary-light-2": "Accent 1 20",
        "--el-color-primary-light-3": "Accent 1 30",
        "--el-color-primary-light-4": "Accent 1 40",
        "--el-color-primary-light-5": "Accent 1 50",
        "--el-color-primary-light-6": "Accent 1 60",
        "--el-color-primary-light-7": "Accent 1 70",
        "--el-color-primary-light-8": "Accent 1 80",
        "--el-color-primary-light-9": "Accent 1 90",
        "--el-color-primary-dark-2": "Accent 1 -20",
    };

    let updated = false;

    export function updateCssAndAppend() {
        if (updated) {
            return;
        }

        let cssStr = "";

        for (let key in colorDictionary) {
            cssStr += `${key}:${Forguncy.ConvertToCssColor(colorDictionary[key])};`;
        }

        cssStr = `:root{ ${cssStr} }`;

        const style = document.createElement("style");
        style.type = "text/css";
        style.id = "FGC_Element_Plus_Variables";
        style.innerHTML = cssStr;
        document.getElementsByTagName("head")[0].appendChild(style);

        updated = true;
    }
}
```

**Comment by Edric-Li** [comment]
Official Assessment Required or not, if so, I can submit a PR.

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Of course.

If you want to custom theme, you should not use CDN.

You should build it by yourself.
Just change scss variables, you can see [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter/), [element-plus-vite-starter/src/styles/element/index.scss](https://github.com/element-plus/element-plus-vite-starter/blob/main/src/styles/element/index.scss).

**Comment by YunYouJun** [comment]
If there are no other problems, I'll close the issue.

**Comment by Edric-Li** [comment]
@YunYouJun 
We can't use build to build it. Our Theme users can change it at any time. Is flexibly configurable.

**Comment by YunYouJun** [comment]
Well, I think you can write a function using js to dynamically override css vars.

Try [@ctrl/tinycolor](https://www.npmjs.com/package/@ctrl/tinycolor).
I think it's not complicated.

**Comment by YunYouJun** [comment]
If possible, in the future we can make a website to automatically generate css vars.
But there's no room for it, because we're building Dark Mode.

**Comment by Edric-Li** [comment]
@YunYouJun  Okay, thank you for your answer,  feature we have implemented, just a suggestion for the offcial.
