### ISSUE TITLE
[Bug Report] [Docs] [All] ReferenceError: window is not defined

### ISSUE THREAD

**Issue by carveybunt** [element-plus/element-plus#6510]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.0.5`
- Browser / OS: `win10`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[element-plus](https://github.com/element-plus/element-plus)

### Steps to reproduce

git clone https://github.com/element-plus/element-plus.git
pnpm install
pnpm docs:build

### What is Expected?

Docs build to finish.

### What is actually happening?

Got error when run `pnpm docs:build`.

### Additional comments

Can't to build for docs.

![image](https://user-images.githubusercontent.com/37894474/157584320-88c82e73-ac8a-4a2c-99d5-3261c436206c.png)
![image](https://user-images.githubusercontent.com/37894474/157584868-c294b9e6-bb4f-4323-b5d0-d442c43e6104.png)

**Comment by sxzz** [comment]
This issue does not seem to affect the build.

**Comment by carveybunt** [comment]
> This issue does not seem to affect the build.

If buind success, where were the folder by buided? I can't found that anywhere.

**Comment by YunYouJun** [comment]
See `docs/.vitepress/dist`.

**Comment by carveybunt** [comment]
> See `docs/.vitepress/dist`.

Thanks

**Comment by YunYouJun** [comment]
I create #6656 to eliminate warnings.
