### ISSUE TITLE
[Feature Request] [link] <el-link>组件的:hover样式不通用，需要自己定义重新覆盖才行，希望能改进一下

### ISSUE THREAD

**Issue by chenxun0719** [element-plus/element-plus#6513]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `link`

## Description

<el-link>组件的:hover样式不通用，需要自己定义重新覆盖才行，希望能改进一下!
.el-link.el-link--primary:hover { color: #66b1ff; } 改为color:var(--el-color-primary-light-2)

### Additional comments

_(empty)_

**Comment by YunYouJun** [comment]
Thanks for your suggestion. Work in progress.

**Comment by YunYouJun** [comment]
Hey, i create a PR https://github.com/element-plus/element-plus/pull/6557 to fix it. Wait for the merge.
