### ISSUE TITLE
[bug report] component: el-pagination

### ISSUE THREAD

**Issue by NO-MAP** [element-plus/element-plus#652]
i'm using el-pagination component.
```
<el-pagination
      background
      layout="prev, pager, next, sizes, jumper, total"
      @size-change="getTableData"
      @current-change="getTableData"
      v-model:currentPage="pageParams.current"
      v-model:pageSize="pageParams.size"
      :total="100"
    >
</el-pagination>
```

i found that 'v-model:pageSize' didn't work.  

in element-plus package, i find some code:
```
// element-plus/lib/pagination/index.js

emits: [
        'size-change',
        'current-change',
        'prev-click',
        'next-click',
        'update:currentPage',
        'update:pageSize',
    ],
```
which means it should work.

by the way, i am using the latest version. 
```
"element-plus": "^1.0.1-alpha.18",
```

**Comment by JeremyWuuuuu** [comment]
```vue
// element-plus/lib/pagination/index.js

emits: [
        'size-change',
        'current-change',
        'prev-click',
        'next-click',
        'update:currentPage',
        'update:pageSize',
    ],
```

These code should not work since `update:currentPage` should be updated as `updateModel:currentPage`.

**Comment by JeremyWuuuuu** [comment]
I will fix this in the next version. Sorry for the inconvenience.

**Comment by JeremyWuuuuu** [comment]
@NO-MAP Hi, can you tell me which version of `Vue` you are using?

**Comment by NO-MAP** [comment]
> @NO-MAP Hi, can you tell me which version of `Vue` you are using?
my package.json shows
```
"element-plus": "^1.0.1-alpha.18",
```

**Comment by JeremyWuuuuu** [comment]
Could you run command on the root path of your project
```
$ cat node_modules/vue/package.json | grep version
```
Then paste the result here? Thanks.

**Comment by NO-MAP** [comment]
as follows:
```
{
  "name": "vue",
  "version": "3.0.2",
  "description": "vue",
  "main": "index.js",
  "module": "dist/vue.runtime.esm-bundler.js",
  "types": "dist/vue.d.ts",
  "unpkg": "dist/vue.global.js",
  "jsdelivr": "dist/vue.global.js",
  "files": [
    "index.js",
    "dist"
  ],
  "buildOptions": {
    "name": "Vue",
    "formats": [
      "esm-bundler",
      "esm-bundler-runtime",
      "cjs",
      "global",
      "global-runtime",
      "esm-browser",
      "esm-browser-runtime"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vuejs/vue-next.git"
  },
  "keywords": [
    "vue"
  ],
  "author": "Evan You",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/vuejs/vue-next/issues"
  },
  "homepage": "https://github.com/vuejs/vue-next/tree/master/packages/vue#readme",
  "dependencies": {
    "@vue/shared": "3.0.2",
    "@vue/compiler-dom": "3.0.2",
    "@vue/runtime-dom": "3.0.2"
  },
  "devDependencies": {
    "lodash": "^4.17.15",
    "marked": "^0.7.0",
    "todomvc-app-css": "^2.3.0"
  }
}
```

**Comment by JeremyWuuuuu** [comment]
got it thanks

**Comment by NO-MAP** [comment]
i am not sure if this can help you:

in the package code, 

https://github.com/element-plus/element-plus/blob/41655b6847f23525ad6ceb2fff98cb146df5f32c/packages/pagination/src/index.ts#L128

'internalCurrentPage.value' has the watchEffect function to emit 'update:currentPage'

but nowhere to emit 'update:pageSize'

**Comment by JeremyWuuuuu** [comment]
> i am not sure if this can help you:
> 
> in the package code,
> 
> https://github.com/element-plus/element-plus/blob/41655b6847f23525ad6ceb2fff98cb146df5f32c/packages/pagination/src/index.ts#L128
> 
> 'internalCurrentPage.value' has the watchEffect function to emit 'update:currentPage'
> 
> but nowhere to emit 'update:pageSize'

Yep, so I did some investigation on the code, and had my conclusion about this bug.
1. There was a design mistake of modeling `pageSize` on version 2.x, which did emitted update:pageSize but no one is using it.
2. When user uses `Vue` with version greater than `3.0.0` e.g. `3.0.2`, a change of event emitting has been made internally in `Vue`, so events which were supposed to work is not working anymore. I am going to find some work around against the change. Also I will keep you notified when it's done.

**Comment by JeremyWuuuuu** [comment]
I am going to fix the issue which causes `v-model:pageSize` not updating to the upper layer, but the bug of `Vue` itself should be fixed in the next release.

**Comment by NO-MAP** [comment]
i am looking forward it. thanks.

**Comment by NO-MAP** [comment]
> I am going to fix the issue which causes `v-model:pageSize` not updating to the upper layer, but the bug of `Vue` itself should be fixed in the next release.

i am looking forward it. thanks.

**Comment by Ryan2128** [comment]
The bug has been fixed. You can update the version of element-plus.

@NO-MAP @Ljzn
