### ISSUE TITLE
[Bug Report] [Style] [loading] element-plus使用自动导入，以服务的方式来调用Loading样式出错

### ISSUE THREAD

**Issue by chostan** [element-plus/element-plus#6521]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome/98.0.4758.102`
- Build Tool: `Vue CLI`

### Related Component

- `el-loading`

### Reproduction Link

[Link](https://gitee.com/chostan/vue3-ts-cms)

### Steps to reproduce

npm install
npm run serve

### What is Expected?

在service文件夹的index.ts的axios请求拦截器中调用el-loading,在main.ts中发送了一次网络请求,el-loading样式出错

### What is actually happening?

el-loading样式出错，没有转圈动画，只显示了一个黑色的div,loading-text的文字在这黑色div的下面

### Additional comments

使用完整引入elment-plus不会出现这个问题，使用自动导入时会出现这个问题

**Comment by emojiiii** [comment]
这种在自动导入时暂时无法识别，请手动引入这个指令的样式。

**Comment by xjphhh** [comment]
> 

这种不会修复了吗？要一直单独引入指令的样式嘛
