### ISSUE TITLE
[Bug Report] [Component] [upload] upload 组件 带缩略图的文件列表  fileList初始化时未显示文件列表

### ISSUE THREAD

**Issue by L-DK** [element-plus/element-plus#6533]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9qc29ucGxhY2Vob2xkZXIudHlwaWNvZGUuY29tL3Bvc3RzL1wiXG4gICAgOm9uLXByZXZpZXc9XCJoYW5kbGVQcmV2aWV3XCJcbiAgICA6b24tcmVtb3ZlPVwiaGFuZGxlUmVtb3ZlXCJcbiAgICA6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgIGxpc3QtdHlwZT1cInBpY3R1cmVcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMGtiXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBVcGxvYWRGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdXBsb2FkL3NyYy91cGxvYWQudHlwZSdcblxuY29uc3QgZmlsZUxpc3QgPSByZWYoW1xuICB7XG4gICAgbmFtZTogJ2Zvb2QuanBlZycsXG4gICAgdXJsOiAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvNjMvNGU3ZjNhMTU0MjliZmRhOTliY2U0MmExOGNkZDFqcGVnLmpwZWc/aW1hZ2VNb2dyMi90aHVtYm5haWwvMzYweDM2MC9mb3JtYXQvd2VicC9xdWFsaXR5LzEwMCcsXG4gIH0sXG4gIHtcbiAgICBuYW1lOiAnZm9vZDIuanBlZycsXG4gICAgdXJsOiAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvNjMvNGU3ZjNhMTU0MjliZmRhOTliY2U0MmExOGNkZDFqcGVnLmpwZWc/aW1hZ2VNb2dyMi90aHVtYm5haWwvMzYweDM2MC9mb3JtYXQvd2VicC9xdWFsaXR5LzEwMCcsXG4gIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVSZW1vdmUgPSAoZmlsZTogVXBsb2FkRmlsZSwgZmlsZUxpc3Q6IFVwbG9hZEZpbGVbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhmaWxlLCBmaWxlTGlzdClcbn1cbmNvbnN0IGhhbmRsZVByZXZpZXcgPSAoZmlsZTogVXBsb2FkRmlsZSkgPT4ge1xuICBjb25zb2xlLmxvZyhmaWxlKVxufVxuPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### What is Expected?

组件渲染时如果fileList有数据，应显示

### What is actually happening?

 fileList初始化时未显示文件列表

### Additional comments

_(empty)_

**Comment by MindMint** [comment]
确实2.0.5有这个bug，暂时回退至2.0.4了

**Comment by msidolphin** [comment]
fix #6508
