### ISSUE TITLE
级联选择器(cascader)无法初始化选项

### ISSUE THREAD

**Issue by RicardoWL** [element-plus/element-plus#654]
使用v-model:value无法初始化选项
控制台出现
[Vue warn]: Extraneous non-props attributes (value) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

版本号`1.0.1-alpha.18`

**Comment by JeremyWuuuuu** [comment]
Could you provide us with a minimal reproducible code for verifying the bug?

**Comment by RicardoWL** [comment]
@JeremyWuuuuu [https://github.com/RicardoWL/cascader-test.git](url)

**Comment by JeremyWuuuuu** [comment]
Well, because of the change of `Vue` itself, now that users only need to use `v-model` to pass down the value to the component, adding an arg named `value` is redundant so that was not supported right now, checkout on the official documentation [Cascader#attributes](https://element-plus.org/#/cascader-attributes)

**Comment by RicardoWL** [comment]
> Well, because of the change of `Vue` itself, now that users only need to use `v-model` to pass down the value to the component, adding an arg named `value` is redundant so that was not supported right now, checkout on the official documentation [Cascader#attributes](https://element-plus.org/#/cascader-attributes)

But it also did not initialize the selection with `v-model`

**Comment by JeremyWuuuuu** [comment]
It did, check this out [Codesandbox](https://codesandbox.io/s/mystifying-payne-insqf?file=/src/App.vue)

**Comment by RicardoWL** [comment]
Well....
When will it be fixed?..

**Comment by JeremyWuuuuu** [comment]
> Well....
> When will it be fixed?..

I am going to take a look tonight, it should be quick.

**Comment by RicardoWL** [comment]
> > Well....
> > When will it be fixed?..
> 
> I am going to take a look tonight, it should be quick.

Thanks.
