### ISSUE TITLE
[Bug Report] [Component] [table] el-table 的 header-cell-class-name 属性不生效

### ISSUE THREAD

**Issue by liuguangsen0409** [element-plus/element-plus#6540]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome 98.0.4758.102`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgaGVhZGVyLWNlbGwtY2xhc3MtbmFtZT1cInRlc3RcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLnRlc3Qge1xuICAgIGJhY2tncm91bmQ6IHJlZDtcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

在 el-table 组件上增加了 header-cell-class-name 属性，设置 class 为 test，在 style 中定义了 test，让它的背景色为红色

### What is Expected?

表头展示红色

### What is actually happening?

表头没有设置上 test 这个 class

### Additional comments

我还试了下 header-cell-style 是可以生效的，还望各位大佬抽空看下

谢谢各位大佬

**Comment by nieyuyao** [comment]
看样子这个class是设置上了，样式的优先级较低导致被覆盖。作为workaround，可以给样式增加`important`

```css
<style>
  .test {
    background: red !important;
  }
</style>

```

**Comment by liuguangsen0409** [comment]
> 看样子这个class是设置上了，样式的优先级较低导致被覆盖。作为workaround，可以给样式增加`important`
> 
> ```css
> <style>
>   .test {
>     background: red !important;
>   }
> </style>
> ```

加上 important 可以的

**Comment by liangdianbo** [comment]
在有scoped style中使用 :deep() 解决了样式不生效的问题。我在自己的项目中不加 !important 也能生效，但是在作者的这个代码里不加 !import 未能生效。

&lt;style scoped&gt;
  :deep(.test) {
    background: red !important;
  }
&lt;/style&gt;
