### ISSUE TITLE
[Bug Report] [Component] [config-provider]

### ISSUE THREAD

**Issue by uinio** [element-plus/element-plus#6544]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.6`
- Browser / OS: `Chrome/98.0`
- Build Tool: `Vite`

## Reproduction
![CZLJ8_(7SD(3_J~IOJ3QKM0](https://user-images.githubusercontent.com/49021590/157872669-37b8b0f1-9fa9-41bb-a0f4-7148407982cd.png)
![image](https://user-images.githubusercontent.com/49021590/157874482-c2a5bb79-3441-462c-91d8-9c105785a99c.png)

### Related Component

- `el-config-provider`
- `unplugin-element-plus`

**Comment by mxp131011** [comment]
我也遇到了

**Comment by mxp131011** [comment]
So did I

**Comment by Oen-Cpz** [comment]
![image](https://user-images.githubusercontent.com/34268416/157883206-4831ccfb-b008-42e3-85d6-7f6c2df345c7.png)

**Comment by rwcoding** [comment]
Me too， same problem  2.0.5 -> 2.0.6 
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/row/style/index" from "***********". Does the file exist?

**Comment by zhangbinhub** [comment]
Me too, same problem 2.0.5 -> 2.0.6
![image](https://user-images.githubusercontent.com/32190984/157898722-edc0d75d-f89e-47f2-82d5-2a9314c5085b.png)

**Comment by WindyZ99** [comment]
It seems that zh-cn.js has been removed from 'element-plus/lib/locale/lang/zh-cn' which only left file of type declare.

**Comment by WindyZ99** [comment]
<img width="206" alt="image" src="https://user-images.githubusercontent.com/59865992/157900267-a85e72b9-7cc9-45ce-8551-4eef93136743.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/59865992/157900638-f8bef910-7531-4702-98c2-905f69e0e8c1.png">

**Comment by WindyZ99** [comment]
That's the difference between 2.0.5 and 2.0.6

**Comment by mxp131011** [comment]
Is there a solution to the problem?

**Comment by cn-troy** [comment]
me too
2.0.5->2.0.6
![image](https://user-images.githubusercontent.com/4318293/158001542-9575c67b-6cbc-4b60-a279-49740e806120.png)

![image](https://user-images.githubusercontent.com/4318293/158001535-1236d1a4-bee2-4d61-b02e-d77fee8e80bf.png)

**Comment by meteornk** [comment]
同样问题，2.0.3 ---> 2.0.6
This dependency was not found:

* element-plus/lib/locale/lang/zh-cn in ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-2!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--1-1!./src/App.vue?vue&type=script&lang=ts

To install it, you can run: npm install --save element-plus/lib/locale/lang/zh-cn

而且，再改回2.0.3，仍然提示这个问题。我要疯了

**Comment by besscroft** [comment]
me too, same problem.

**Comment by ajw333** [comment]
删除了这个可以使用 但变成英文了

**Comment by mxp131011** [comment]
> 删除了这个可以使用 但变成英文了

为啥我删除了也不可用，你用的是按需加载还是全局引用

**Comment by mxp131011** [comment]
> 我没有用unplugin-element-plus 去除zhCN import 后可以正常使用
> 
> > ![image](https://user-images.githubusercontent.com/34268416/157883206-4831ccfb-b008-42e3-85d6-7f6c2df345c7.png)

你是用的全局引入吗？还是 `nplugin-vue-components` 和 `unplugin-auto-import`

**Comment by ajw333** [comment]
有个不可靠的解决方式就是把2.0.5或以前版本中的”element-plus/lib/”中locale中的文件全部复制，覆盖2.0.6版中的locale文件，就行运行了

**Comment by zhangbinhub** [comment]
终极解决方案，直接引入源码即可。
![image](https://user-images.githubusercontent.com/32190984/158014962-fd3a4ac4-efa4-4e39-b2d1-7b71673bd480.png)
![image](https://user-images.githubusercontent.com/32190984/158014969-4e1ad56f-4546-42b4-ab36-7f335a712931.png)
但这种方式不是很优雅，还是希望官方能够重视，每次版本更新基本上都是解决一小部分问题，带来更多的问题……

**Comment by mxp131011** [comment]
> 终极解决方案，直接引入源码即可。 ![image](https://user-images.githubusercontent.com/32190984/158014962-fd3a4ac4-efa4-4e39-b2d1-7b71673bd480.png) ![image](https://user-images.githubusercontent.com/32190984/158014969-4e1ad56f-4546-42b4-ab36-7f335a712931.png) 但这种方式不是很优雅，还是希望官方能够重视，每次版本更新基本上都是解决一小部分问题，带来更多的问题……

我想问的是我不止是语言模块不能加载还有`ElMessage`和`ElLoading`模块的css也不能加载，所以你们是使用全量引入还是按需加载

**Comment by uinio** [comment]
update 2.1 close this issue

**Comment by ajw333** [comment]
update 2.1 解决问题

**Comment by zhangbinhub** [comment]
got it! @uinio
