### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by docming** [element-plus/element-plus#655]
not sure this is a bug or not

DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/mitt/dist/mitt.es.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/async-validator/dist-web/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by JeremyWuuuuu** [comment]
We have met this warning as well. And I think we need to check it out why is this happening, but this won't have any impact on how the code works, by it might somehow stuck users from being able to debugging into `mitt` or `async-validator`.
BTW, are you using `vite` as bundler?

**Comment by docming** [comment]
> We have met this warning as well. And I think we need to check it out why is this happening, but this won't have any impact on how the code works, by it might somehow stuck users from being able to debugging into `mitt` or `async-validator`.
> BTW, are you using `vite` as bundler?

I'm using the Vuecli@4.5.9

**Comment by zazzaz** [comment]
will fix this soon in #668

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.21 , thanks
