### ISSUE TITLE
[Bug Report] [ElPopover] "isElement" seems will be called in server-side

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#6572]
### Discussed in https://github.com/element-plus/element-plus/discussions/6566

<div type='discussions-op-text'>

<sup>Originally posted by **KawaiiZapic** March 12, 2022</sup>
I caught an error in server-side rendering, "Element is not defined", according to the backtrace, I locate there is a call of isElement in Popover.
https://github.com/element-plus/element-plus/blob/dev/packages/components/popper/src/trigger.vue#L55  
That's pretty odd, isElement does not check the application is running in server or client.
@[JeremyWuuuuu](https://github.com/JeremyWuuuuu)</div>

**Comment by btea** [comment]
fixed #6575
