### ISSUE TITLE
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification

### ISSUE THREAD

**Issue by Pixelairport** [element-plus/element-plus#659]
When I do 'npm run dev' in my vue 3 app created with vite i get a lot of messages: "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification" before app is started.

**Comment by JeremyWuuuuu** [comment]
Hey @Pixelairport, could you provide some code for us to investigate? This could be caused by the configuration of `Vite`. Might be caused by referencing the wrong bundle. cc @zazzaz , can you take a look?

**Comment by Pixelairport** [comment]
Of course. I also tested your code at https://github.com/element-plus/element-plus-vite-starter. This also have the problem. I donwload it, do npm install and then npm run dev and then I get the problem.

**Comment by JeremyWuuuuu** [comment]
I think that's a problem with the `Vite` configuration which referenced a wrong package(the minified one). Are you running this in dev mode? Or prod mode? If you are running it in dev mode then it verifies my assumption, if not, then we need to figure out what is going on, I asked @zazzaz to look at this issue, we will make sure this will be fixed in a short time. Sorry for the inconvenience.

**Comment by JeremyWuuuuu** [comment]
Also cc @zouhangwithsweet.

**Comment by Pixelairport** [comment]
I really like your library so i dont have inconvenience :) Im glad that someone takes the time and does a library like that. Dev mode shows the info "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification", but it seems to work and shows the button with counter which is included in the vite starter. When I do npm run build it crashes. I just dowloaded the clean vite starter from element plus (also tried it by myself and have the same problems). All other libraries work. But maybe I'm the only one with the problem, then just delete my problem. I dont know what can I do now. Maybe I will try it with vuecli instread of vite.

**Comment by JeremyWuuuuu** [comment]
Well, this is definitely something we need to take a look since we need to blend in with `Vue` eco-system, Let's see what we can do for this issue. I'll keep you notified when we fix it.

**Comment by zazzaz** [comment]
will fix it soon

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.21, thanks
