### ISSUE TITLE
[Bug Report] [Style] [All] SassError: Invalid argument(s): If parsedAsCustomProperty is true, value must contain a SassString (was `64, 158, 255` of type SassList0).

### ISSUE THREAD

**Issue by lsoimpe** [element-plus/element-plus#6594]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.0`
- Browser / OS: `Chrome/99.0.4844.51`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24+RGVmYXVsdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCI+RGFuZ2VyPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbj7kuK3mloc8L2VsLWJ1dHRvbj5cbiAgPC9lbC1yb3c+XG5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIj5cbiAgICA8ZWwtYnV0dG9uIHBsYWluPlBsYWluPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHBsYWluPlByaW1hcnk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJzdWNjZXNzXCIgcGxhaW4+U3VjY2VzczwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiBwbGFpbj5JbmZvPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwid2FybmluZ1wiIHBsYWluPldhcm5pbmc8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBwbGFpbj5EYW5nZXI8L2VsLWJ1dHRvbj5cbiAgPC9lbC1yb3c+XG5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIj5cbiAgICA8ZWwtYnV0dG9uIHJvdW5kPlJvdW5kPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHJvdW5kPlByaW1hcnk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJzdWNjZXNzXCIgcm91bmQ+U3VjY2VzczwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiByb3VuZD5JbmZvPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwid2FybmluZ1wiIHJvdW5kPldhcm5pbmc8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiByb3VuZD5EYW5nZXI8L2VsLWJ1dHRvbj5cbiAgPC9lbC1yb3c+XG5cbiAgPGVsLXJvdz5cbiAgICA8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgY2lyY2xlPjwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIkVkaXRcIiBjaXJjbGU+PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIDppY29uPVwiQ2hlY2tcIiBjaXJjbGU+PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiaW5mb1wiIDppY29uPVwiTWVzc2FnZVwiIGNpcmNsZT48L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ3YXJuaW5nXCIgOmljb249XCJTdGFyXCIgY2lyY2xlPjwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImRhbmdlclwiIDppY29uPVwiRGVsZXRlXCIgY2lyY2xlPjwvZWwtYnV0dG9uPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge1xuICBTZWFyY2gsXG4gIEVkaXQsXG4gIENoZWNrLFxuICBNZXNzYWdlLFxuICBTdGFyLFxuICBEZWxldGUsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

scss文件引入：
@import "~element-plus/theme-chalk/src/index.scss";
报错：
SassError: Invalid argument(s): If parsedAsCustomProperty is true, value must contain a SassString (was `64, 158, 255` of type SassList0).

### What is Expected?

修复 scss 引入错误

### What is actually happening?

scss 引入错误

### Additional comments

无法提供复现环境

**Comment by jiaozhiye** [comment]
The same problem!!!

**Comment by lemoe2021** [comment]
Same in 2.1.1

I change to `@use "element-plus/theme-chalk/src/index.scss" as *;` fixed this problem.

Not sure which version updated this documentation.

https://element-plus.org/en-US/guide/theming.html#how-to-override-it

**Comment by lsoimpe** [comment]
> Same in 2.1.1
> 
> I change to `@use "element-plus/theme-chalk/src/index.scss" as *;` fixed this problem.
> 
> Not sure which version updated this documentation.
> 
> https://element-plus.org/en-US/guide/theming.html#how-to-override-it

依然不能解决

**Comment by ModyQyW** [comment]
Locking the version to 2.0.5 will avoid this problem for now. Hope it helps.

**Comment by dxy2233** [comment]
全样式引入应该是下面这个地址吧
@import "element-plus/dist/index.css";

**Comment by lsoimpe** [comment]
> 全样式引入应该是下面这个地址吧 @import "element-plus/dist/index.css";

这样引入没法修改scss变量，就没法修改主题，这个问题是2.1.0和2.1.1出现的，2.0.5和之前没问题

**Comment by dxy2233** [comment]
> > 全样式引入应该是下面这个地址吧 @import "element-plus/dist/index.css";
> 
> 这样引入没法修改scss变量，就没法修改主题，这个问题是2.1.0和2.1.1出现的，2.0.5和之前没问题

可以用css变量方式修改，不过建议还是退回2.0.5，新版目前问题太多

**Comment by YunYouJun** [comment]
Can you provide a minimal example?

**Comment by YunYouJun** [comment]
I can not reproduce this in https://github.com/element-plus/element-plus-vite-starter .

Did you upgrade sass dependencies? Or other info.

And always use `@use '' as *;` instead of `@import`.

**Comment by ModyQyW** [comment]
Minimal example <https://github.com/ModyQyW/vite-project>. Maybe caused by `@import`. Can you please see it? @YunYouJun

**Comment by YunYouJun** [comment]
> Minimal example https://github.com/ModyQyW/vite-project. Maybe caused by `@import`. Can you please see it? @YunYouJun
> 
> Edit: Using `@forward` and `@use` like [docs](https://element-plus.org/en-US/guide/theming.html) looks good to me.

Thanks. I can reproduce it.

I find it. EP add several colors rgb fo user to use(can set opacity). In `@import`, this will be treated as a syntax for sass, not as css var plain text. But `@use` handled it and can function properly.

Solution: You can use `@use` to solve it. By the way, the sass team said they will deprecated `@import` grammar. So I recommend always using `@use`.

Of course, for better compatibility, I'll create a pr to translate it into plain text. So we can use `@use` or `@import`. (😄 `@use` is always better).
