### ISSUE TITLE
`select`  component  `size` property not working when set `multiple`

### ISSUE THREAD

**Issue by weiyuc** [element-plus/element-plus#661]
```
<el-select size='mini' multiple>
  <el-option :value='1' label='label 1'></el-option>
</el-select>
```
expect: el-select height = 28px
in fact: el-select height = 40px

**Comment by Ryan2128** [comment]
Can you provide you version? In my test, it works well.

[DEMO](https://codesandbox.io/s/prod-architecture-q90jz?file=/src/App.vue)

**Comment by weiyuc** [comment]
it not working on latest version,
[demo](https://codesandbox.io/s/wizardly-framework-hx5y4?file=/src/App.vue)

**Comment by zazzaz** [comment]
The problem finally becomes, a select component inside a form does not size correctly.

**Comment by JeremyWuuuuu** [comment]
Then this is some bug that we need to fix. Assigning it to me.
