### ISSUE TITLE
[Bug Report] [Build] [All] yarn build无法编译

### ISSUE THREAD

**Issue by bthulu** [element-plus/element-plus#6616]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/bthulu/vite-ele-bug)

### Steps to reproduce

git clone https://github.com/bthulu/vite-ele-bug.git
cd vite-ele-bug/yarn-build
yarn
yarn build

### What is Expected?
script中添加以下代码能成功编译
```
import {ElForm} from 'element-plus'
```
或
```
import type {FormInstance} from 'element-plus'
```

### What is actually happening?

编译报错
40     readonly lg: import("@element-plus/utils").BuildPropReturn<import("@element-plus/utils").PropWrapper<ColSize>, () => import("@element-plus/utils").Mutable<{}>, unknown, unknown, unknown>;
                           ~~~~~~~~~~~~~~~~~~~~~

node_modules/element-plus/es/components/col/src/col.d.ts:41:25 - error TS2307: Cannot find module '@element-plus/utils' or its corresponding type declarations.

41     readonly xl: import("@element-plus/utils").BuildPropReturn<import("@element-plus/utils").PropWrapper<ColSize>, () => import("@element-plus/utils").Mutable<{}>, unknown, unknown, unknown>;
                           ~~~~~~~~~~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:86:35 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

86         beforeRouteEnter?: import("vue-router").NavigationGuardWithThis<undefined> | undefined;
                                     ~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:87:36 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

87         beforeRouteUpdate?: import("vue-router").NavigationGuard | undefined;
                                      ~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:88:35 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

88         beforeRouteLeave?: import("vue-router").NavigationGuard | undefined;
                                     ~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:215:35 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

215         beforeRouteEnter?: import("vue-router").NavigationGuardWithThis<undefined> | undefined;
                                      ~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:216:36 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

216         beforeRouteUpdate?: import("vue-router").NavigationGuard | undefined;
                                       ~~~~~~~~~~~~

node_modules/element-plus/es/components/collection/src/collection.d.ts:217:35 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

217         beforeRouteLeave?: import("vue-router").NavigationGuard | undefined;

### Additional comments

_(empty)_

<!-- 如果你需要插入截图，请在这粘贴。 -->

**Comment by YunYouJun** [comment]
It seems caused by error types. (lack of vue-router, etc.)

As a temporary solution, you can remove `vue-tsc --noEmit && ` to not check type.

**Comment by YunYouJun** [comment]
I see. You should add `"skipLibCheck": true` for your `tsconfig.json`.

```ts
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```
