### ISSUE TITLE
[Bug Report] [Component] [cascader] Cascader 

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#6617]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.1`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/cascader.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

 Element Plus Playground 

### What is Expected?

样式正确

### What is actually happening?

样式正确

### Additional comments

_(empty)_
![image](https://user-images.githubusercontent.com/33827314/158142863-9711a0c9-83c3-4a05-ae00-7db16565e405.png)

**Comment by gjfei** [comment]
这个bug 也太离谱了

**Comment by happiness86** [comment]
css变量用错了，应该是个笔误
