### ISSUE TITLE
[Bug Report] [Component] el-table-column包裹el-form-item 当减少记录后，提交校验，还会触发删除条目的校验。

### ISSUE THREAD

**Issue by a24z** [element-plus/element-plus#6626]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36 Edg/98.0.1108.51`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImVkaXRcIj5cbiAgXHQ8ZWwtcmFkaW8gOmxhYmVsPVwidHJ1ZVwiPua3u+WKoDwvZWwtcmFkaW8+XG4gICAgPGVsLXJhZGlvIDpsYWJlbD1cImZhbHNlXCI+57yW6L6RPC9lbC1yYWRpbz5cbiAgPC9lbC1yYWRpby1ncm91cD5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybURhdGFcIiA6cnVsZXM9XCJydWxlc1wiIHJlZj1cImZvcm1cIiBsYWJlbC13aWR0aD1cIjEwMHB4XCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cInVzZXJuYW1lXCIgcHJvcD1cInVzZXJuYW1lXCIgdi1pZj1cImVkaXRcIiBrZXk9XCJmb3JtLWl0ZW0tdXNlcm5hbWVcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZm9ybURhdGEudXNlcm5hbWVcIiBjbGVhcmFibGU+PC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiZW1haWxcIiBwcm9wPVwiZW1haWxcIiAga2V5PVwiZm9ybS1pdGVtLWVtYWlsXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm1EYXRhLmVtYWlsXCIgY2xlYXJhYmxlPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1oYW5kbGVTdWJtaXQ+5o+Q5LqkPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiaGFuZGxlUmVzZXRcIj7ph43nva48L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0PlxuZXhwb3J0IGRlZmF1bHQge1xuICBuYW1lOiAnVGVzdEZvcm0nLFxuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBlZGl0OiBmYWxzZSxcbiAgICAgIGZvcm1EYXRhOiB7XG4gICAgICAgIHVzZXJuYW1lOiAnJyxcbiAgICAgICAgZW1haWw6ICcnXG4gICAgICB9LFxuICAgICAgcnVsZXM6IHtcbiAgICAgICAgdXNlcm5hbWU6IFtcbiAgICAgICAgICB7cmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdQbGVhc2UgaW5wdXQgdXNlcm5hbWUnLCB0cmlnZ2VyOiAnYmx1cid9XG4gICAgICAgIF0sXG4gICAgICAgIGVtYWlsOiBbXG4gICAgICAgICAge3JlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAnUGxlYXNlIGlucHV0IGVtYWlsJywgdHJpZ2dlcjogJ2JsdXInfVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICB9LFxuICBtZXRob2RzOiB7XG4gICAgaGFuZGxlU3VibWl0KCkge1xuICAgICAgY29uc29sZS5sb2coJ2hhbmRsZSBzdWJtaXQnKVxuICAgICAgdGhpcy4kcmVmc1snZm9ybSddLnZhbGlkYXRlKHZhbGlkID0+IHtcbiAgICAgICAgaWYodmFsaWQpIHtcbiAgICAgICAgICB0aGlzLiRtZXNzYWdlLnN1Y2Nlc3MoJ1ZhbGlkIGZvcm0gZGF0YScpXG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgdGhpcy4kbWVzc2FnZS5lcnJvcignSW52YWxpZCBmb3JtIGRhdGEnKVxuICAgICAgICB9XG4gICAgICB9KVxuICAgIH0sXG4gICAgaGFuZGxlUmVzZXQoKSB7XG4gICAgICB0aGlzLiRyZWZzWydmb3JtJ10ucmVzZXRGaWVsZHMoKVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

用表格嵌套el-form-item，el-form-item上设置rule, 当表格增加一项，然后在删除这条，这时候点表单验证 触发el-form validate。

### What is Expected?

校验成功，表格已经一条记录都没有了

### What is actually happening?

还是触发了表单的校验

### Additional comments

应该是删除表格行记录的时候，el-form-item还会缓存之前删除的记录

**Comment by JeremyWuuuuu** [comment]
> 用表格嵌套el-form-item，el-form-item上设置rule, 当表格增加一项，然后在删除这条，这时候点表单验证 触发el-form validate。

@a24z How do you describe the deletion here in your case? Correct me if I am wrong, did you mean that you delete the item by editing the code which triggers a hot reload or you use code to dynamically delete/add form items?

**Comment by a24z** [comment]
本质上和issue 6634是一个问题。https://element-plus.org/en-US/component/form.html#add-delete-form-item
重现步骤
step 1: click new domain
step 2: fill all inputs
step 2: click delete on domain
step 3: do submit
step 4: show console

**Comment by JeremyWuuuuu** [comment]
@a24z Fixed, We will release a new version for this patch tonight, so sorry for the inconvenience we caused. :bow:
