### ISSUE TITLE
[Bug Report] [Component] [drawer] el-drawer background is transparent

### ISSUE THREAD

**Issue by latolukasz** [element-plus/element-plus#6627]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.2`
- Browser / OS: `Chrome Version 99.0.4844.51 (Official Build) (arm64)`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/drawer.html)

### Steps to reproduce

broken even in your documentation:
https://element-plus.org/en-US/component/drawer.html

### What is Expected?

white background

### What is actually happening?

transparent background

### Additional comments

_(empty)_

**Comment by YunYouJun** [comment]
Thanks for your report. I create #6631 to fix it.
