### ISSUE TITLE
[Bug Report] [Style] [menu-item] El-Menu tooltip position bug

### ISSUE THREAD

**Issue by Jianger** [element-plus/element-plus#6632]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.2`
- Browser / OS: `Chrome 99.0.4844.51 `
- Build Tool: `Vue CLI`

### Related Component

- `el-menu-item`

### Reproduction Link

[Link]()

### Steps to reproduce

menu 放在屏幕最右边。collapse true

### What is Expected?

tooltip 到左边 

### What is actually happening?

跑去右边看不到了

### Additional comments

之前用的1.0.2.beta44 是好用的 最近升级不好用了

**Comment by BigPengZai** [comment]
```javascript
placement="left"
```

**Comment by BigPengZai** [comment]
```ts
fallback-placements="left"
```

**Comment by BigPengZai** [comment]
@JeremyWuuuuu  
Why not merge my PR first

**Comment by JeremyWuuuuu** [comment]
With all due respect, @freedomlang's PR just made more sense than yours to me. You may find other bugs to try. :pray:
