### ISSUE TITLE
[Feature Request] 请问怎么修改样式的前缀比如把el-改为al-，我看现有功能似乎有一个namespace设置，但是不知道具体该如何设置

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#6637]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

因为用了微前端，主项目和子项目都是element，样式冲突了。希望可以修改子项目的样式前缀

### Additional comments

_(empty)_

**Comment by ht-sauce** [comment]
我看到了在el-config-provider已经存在namespace处理，但是现在不知道如何修改样式的el前缀。请问怎么修改？

**Comment by msidolphin** [comment]
> 我看到了在el-config-provider已经存在namespace处理，但是现在不知道如何修改样式的el前缀。请问怎么修改？

namesapce还没覆盖全部组件，样式的前缀请覆盖scss变量

**Comment by ht-sauce** [comment]
> > 我看到了在el-config-provider已经存在namespace处理，但是现在不知道如何修改样式的el前缀。请问怎么修改？
> 
> namesapce还没覆盖全部组件，不建议现在使用，样式的前缀请覆盖scss变量

我尝试过了，貌似会出大问题。放弃了

**Comment by ht-sauce** [comment]
> 微前端有支持css沙箱

沙箱会导致挂载到body下面的样式失效

**Comment by free-pan** [comment]
> > 我看到了在el-config-provider已经存在namespace处理，但是现在不知道如何修改样式的el前缀。请问怎么修改？
> 
> namesapce还没覆盖全部组件，不建议现在使用，样式的前缀请覆盖scss变量

按需引入的情况怎么修改 `$namespace` 的scss变量？下面三种方式都报错 @msidolphin

```scss
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  $namespace: 'test' !default
);
```

```scss
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  $namespace: 'test'
);
```

```scss
$namespace: 'test'
```

```scss
$namespace: 'test' !default
```

**Comment by YunYouJun** [comment]
由于历史原因，项目仍然存在大量 `el` 命名未完成替换，暂时尚不可用，在完成后会在文档补足使用方法。

**Comment by iamkun** [comment]
You can set global `namespace` config in https://element-plus.org/en-US/component/config-provider.html#config-provider-attributes

This feature is available after v2.1.10

**Comment by weijiatan456** [comment]
> You can set global `namespace` config in https://element-plus.org/en-US/component/config-provider.html#config-provider-attributes
> 
> This feature is available after v2.1.10

看了demo才知道，还要配置一项：
`Components({
        resolvers: [
            // 自动导入 Element Plus 组件
            ElementPlusResolver({
                importStyle: 'sass',
            }),
        ],
    }),`

**Comment by jianggangsheng** [comment]
https://element-plus.org/zh-CN/guide/namespace.html 
这个文档的vue.config.js怎么写

**Comment by YunYouJun** [comment]
可参见：

- 修改样式 namespace：https://github.com/element-plus/element-plus-vite-starter/blob/fa10f32788a09b2faab73d3f9709f33bc7cf4d3f/src/styles/element/index.scss#L23。

- 修改组件 namespace：https://github.com/element-plus/element-plus-vite-starter/blob/fa10f32788a09b2faab73d3f9709f33bc7cf4d3f/src/App.vue#L2

**Comment by jianggangsheng** [comment]
> 可参见：
> 
> * 修改样式 namespace：[https://github.com/element-plus/element-plus-vite-starter/blob/fa10f32788a09b2faab73d3f9709f33bc7cf4d3f/src/styles/element/index.scss#L23。](https://github.com/element-plus/element-plus-vite-starter/blob/fa10f32788a09b2faab73d3f9709f33bc7cf4d3f/src/styles/element/index.scss#L23%E3%80%82)
> * 修改组件 namespace：https://github.com/element-plus/element-plus-vite-starter/blob/fa10f32788a09b2faab73d3f9709f33bc7cf4d3f/src/App.vue#L2
> 
> https://element-plus.org/zh-CN/guide/namespace.html

已经这么写了不生效为啥

**Comment by YunYouJun** [comment]
https://vite-starter.element-plus.org/ 示例生效。

**Comment by jianggangsheng** [comment]
> https://vite-starter.element-plus.org/ 示例生效。

   用vite是可以，用webpack怎么写呢，是下面这样吗？这么写样式没有生效
![3](https://github.com/element-plus/element-plus/assets/21185192/da9ddfc8-858b-4875-8654-a8b4212b9f2c)

**Comment by jianggangsheng** [comment]
<img width="1021" alt="image" src="https://github.com/element-plus/element-plus/assets/21185192/22f92c1c-2e11-4268-ab6a-b0f7cbf17d9c">

这个形式的怎么写
