### ISSUE TITLE
[Bug Report] [Style] [All] Drawer 抽屉组件背景显示异常，从v2.1.1版本开始出现此问题

### ISSUE THREAD

**Issue by 767102998** [element-plus/element-plus#6638]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.1`
- Browser / OS: `Windows`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

官方文档也复现此问题

### What is Expected?

不透明，默认背景白色

### What is actually happening?

不透明，默认背景白色

### Additional comments

_(empty)_

**Comment by jiaozhiye** [comment]
The same problem!

**Comment by JackieCheung** [comment]
same bug

`background-color: var(--el-drawer-bg-color);`

`--el-drawer-bg-color` not found

**Comment by Alanscut** [comment]
fix #6631
