### ISSUE TITLE
[Bug Report] [Component] [drawer] 官网抽屉组件 样式错误

### ISSUE THREAD

**Issue by XiangZhenHua11** [element-plus/element-plus#6648]
![1647335238(1)](https://user-images.githubusercontent.com/49868923/158343824-1d897965-d00d-4f77-aad7-8dd7cf238b0f.jpg)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.2`
- Browser / OS: `谷歌`
- Build Tool: `Other`

### Related Component

- `el-drawer`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

官网上点击 drawer组件  样式背景全黑了

### What is Expected?

修复

### What is actually happening?

修复

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
fix #6631
