### ISSUE TITLE
Can not import libray on demand

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#665]
I have followed import library on demand in Vue 3 project.  There are too many errors that npm run serve won't finish.  Can you please revise the documentation ?
Then I can not test the internationlization.

**Comment by JeremyWuuuuu** [comment]
Cc @zazzaz , well we need a minimal reproducible repo or link in order to make further invetisgation. Could you help with that?

**Comment by zazzaz** [comment]
@ntgraph I've double-checked our docs and confirm it is the updated version. Also, please make sure you are using the latest release, which is `1.0.1-alpha.20` at the moment.

If the problem continues, please provide a reproduction repo or demo code or some error message.

**Comment by JeremyWuuuuu** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
