### ISSUE TITLE
[Feature Request] [Enhancement] [input] Suggest adding thousand formatting for el-input

### ISSUE THREAD

**Issue by Serendipity96** [element-plus/element-plus#6652]
Feature type: **`Enhancement`**

## Details

- Enhanced component name: `input`

## Description

It is a common requirement to enter numbers and format them into thousands. 

<img width="213" alt="image" src="https://user-images.githubusercontent.com/23514812/158355125-7b84fd9d-92ca-49e8-b46a-cae4e965eed8.png">

There have been several issues in element 2.0, but no response.

- [input-number support thousands of bits](https://github.com/ElemeFE/element/issues/15490)
- [display thousands separators formatting for Input Number](https://github.com/ElemeFE/element/issues/21181)

### Additional comments
If this feature passes the discussion, I am willing to develop it.

**Comment by YunYouJun** [comment]
@element-plus/backers

**Comment by chenxch** [comment]
I think this api can be a `formatter` function, which can meet more usage scenarios of users, not only limited to thousandths.

**Comment by JackieCheung** [comment]
Same expectation👍~Just like [AntDesignVue InputNumber](https://www.antdv.com/components/input-number-cn/#components-input-number-demo-formatter)

**Comment by norangit** [comment]
@Serendipity96 here is perfect https://primefaces.org/primevue/#/inputnumber, worth a try and to refer

**Comment by YunYouJun** [comment]
> AntDesignVue InputNumber

I agree. `formatter` for user to pass a function.

@Serendipity96 Do you want to try it?

**Comment by Serendipity96** [comment]
> > AntDesignVue InputNumber
> 
> I agree. `formatter` for user to pass a function.
> 
> @Serendipity96 Do you want to try it?

Yes, and if I have questions, I will ask you, thanks.

**Comment by Serendipity96** [comment]
> > AntDesignVue InputNumber
> 
> I agree. `formatter` for user to pass a function.
> 
> @Serendipity96 Do you want to try it?

hi, @YunYouJun , I have finished and all checks have passed. The PR need to review, if you have time, please take a look. Thanks!

**Comment by YunYouJun** [comment]
Good job. Let me see see.

**Comment by 418545106** [comment]
3年过去了，请问数字输入框想格式化加上千分位分隔符，有解决吗
