### ISSUE TITLE
[Bug Report] [Component] [input-number] input-number 设置step-strictly是值没有更新到外部组件

### ISSUE THREAD

**Issue by lovexp1** [element-plus/element-plus#6659]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.3`
- Browser / OS: `Chrome 99.0.4844.51 on OS X 10.15.7 64-bit`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbnVtID0gcmVmKG51bGwpXG5mdW5jdGlvbiBudW1DaGFuZ2UoKSB7XG4gIGNvbnNvbGUubG9nKG51bS52YWx1ZSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cIm51bVwiIDpzdGVwPVwiNlwiIHN0ZXAtc3RyaWN0bHkgQGNoYW5nZT1cIm51bUNoYW5nZVwiPjwvZWwtaW5wdXQtbnVtYmVyPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

输入非step的数值，组件显示自动更改为步进的倍数值

### What is Expected?

外部组件绑定的值是用户输入的实际值，组件显示的为步进的倍数，期望数据与视图展示一致

### What is actually happening?

外部组件v-model绑定的值和界面显示的不一致

### Additional comments

_(empty)_

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/44965220/158405310-d495cd00-a8b1-4a1b-b509-cb0d74486d89.png">
定位到问题在这边，严格步进模式下更新值后没有对外抛出更新
<img width="833" alt="image" src="https://user-images.githubusercontent.com/44965220/158408796-17615afc-2ec8-4699-9d32-dd3b0c783062.png">

**Comment by chenxch** [comment]
@Wiensss  This didn't solve the problem.

**Comment by chenxch** [comment]
@lovexp1 You found the place to handle it, but in the wrong place. To be precise, stepStrictly processing is missing in setCurrentValue
