### ISSUE TITLE
[Bug Report] [Style] [input-number] input-number 输入中文后光标位置异常

### ISSUE THREAD

**Issue by lovexp1** [element-plus/element-plus#6660]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.3`
- Browser / OS: `Chrome 99.0.4844.51 on OS X 10.15.7 64-bit`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbnVtID0gcmVmKG51bGwpXG5mdW5jdGlvbiBudW1DaGFuZ2UoKSB7XG4gIGNvbnNvbGUubG9nKG51bS52YWx1ZSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cIm51bVwiIDpzdGVwPVwiNlwiIHN0ZXAtc3RyaWN0bHkgQGNoYW5nZT1cIm51bUNoYW5nZVwiPjwvZWwtaW5wdXQtbnVtYmVyPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

输入中文后，无效值会被清空，此时光标位置异常

### What is Expected?

清空无效值后，光标位置正常

### What is actually happening?

清空无效值后，光标位置异常

### Additional comments

_(empty)_

异常效果如下
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/44965220/158411011-ce91ba97-92a6-452e-a44b-427670487618.png">
定位到原因是给 input 标签添加 line-height 样式导致的，去掉后可以正常显示
<img width="724" alt="image" src="https://user-images.githubusercontent.com/44965220/158411480-4f13a3a3-bc72-49cb-894c-bf8256a0a082.png">

**Comment by chenxch** [comment]
这个是原生input已知问题，number模式下在设置line-height后会使用输入法会导致光标漂移到左上角，组件对应的文档中已有tip。 后续是不是可以考虑通过padding的方式去调整高度？

**Comment by anidenxin** [comment]
这个问题我也碰到了, 在谷歌浏览器下和Microsoft Edge浏览器下有这个问题, 但是不知道为啥用360极速浏览器没有问题, 也是使用谷歌内核'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'

**Comment by HeftyKoo** [comment]
fixed by: https://github.com/element-plus/element-plus/pull/8193
