### ISSUE TITLE
[Bug Report] [Component] [input] el-input 组件 在谷歌浏览器 自动填充账户密码时，出现警告

### ISSUE THREAD

**Issue by bluecai520** [element-plus/element-plus#6665]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.5`
- Browser / OS: `Google Chrome 版本 99.0.4844.51（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-ijxq89?file=/src/App.vue)

### Steps to reproduce

点击输入框后，填充浏览器保存的账户

```vue
<template>
  <div>
    <el-form>
      <el-form-item>
        <el-input 
        type="text" 
        v-model="props.account" 
        />
      </el-form-item>
      <el-form-item>
        <el-input type="password" 
        v-model="props.password" 
        />
      </el-form-item>
      <el-form-item>
        <el-button 
        type="info" 
        @click="login">
          登入
          </el-button>
      </el-form-item>
    </el-form>
  </div>
</template>


<script>
import { ref, reactive } from "vue";
export default {
  setup() {
    const value = ref("");
    const props = reactive({
      account: "",
      password: "",
    });

    return {
      value,
      props
    };
  },
};
</script>
```

### What is Expected?

功能正常
没有警告

### What is actually happening?

功能正常，但会出现如下警告
[Vue warn]: Invalid event arguments: event validation failed for event "keydown".

### Additional comments

使用原生input标签并没有出现警告。
这个警告目前没有影响功能正常使用，但是每次填充浏览器保存的账户时，就会出现。
请问该如何消除这个警告

![kctfb-in161](https://user-images.githubusercontent.com/32674213/158533687-aafe106d-c134-4352-95c2-5bb211004ffb.gif)

**Comment by sweethuan** [comment]
俺也一样，请问有解决方案吗

**Comment by m1746234610** [comment]
我也遇到这个问题了
