### ISSUE TITLE
[Feature Request] [Enhancement] [input-number] 能否支持格式化显示

### ISSUE THREAD

**Issue by grays820** [element-plus/element-plus#6673]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `input-number`

## Description

这是组件是否能支持格式化显示，比如用在金额上面，显示的时候可能需要有千分位或者货币 bir 100000要显示城 ¥100,000 这样

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
You can follow #6652 .

**Comment by sxzz** [comment]
Duplicate of #6652
