### ISSUE TITLE
[Bug Report] [Style] [button] button非圆形

### ISSUE THREAD

**Issue by izhaorui** [element-plus/element-plus#6687]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

<el-row>
    <el-button :icon="Search" circle />
    <el-button type="primary" :icon="Edit" circle />
    <el-button type="success" :icon="Check" circle />
    <el-button type="info" :icon="Message" circle />
    <el-button type="warning" :icon="Star" circle />
    <el-button type="danger" :icon="Delete" circle />
  </el-row>

### What is Expected?

期望变成圆形

### What is actually happening?

浏览器上显示的是椭圆形的

### Additional comments

_(empty)_

**Comment by zt123123** [comment]
@izhaorui 
这个不是bug，就是这样设计的。按钮高度是固定的，当你的内容超过了高度时候就是椭圆形的。

**Comment by wzrove** [comment]
想要圆形，让宽高相等， ` boder-radius: 50% ` 就好了。
