### ISSUE TITLE
[Bug Report] [Component] [upload] Top level div has no width adaptation

### ISSUE THREAD

**Issue by Lupeiwen0** [element-plus/element-plus#6689]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `macOS lasted / chrome  lasted`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBcbiAgPGVsLWZvcm0+XG4gIFx0PGVsLWZvcm0taXRlbSBsYWJlbD1cImZpbGU6XCI+XG4gICAgXHQ8ZWwtdXBsb2FkXG4gICAgICAgIGFjdGlvbj1cIiNcIlxuICAgICAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yVXBsb2FkXCJcbiAgICAgICAgOmZpbGUtbGlzdD1cImZpbGVMaXN0XCJcbiAgICAgICA+XG4gICAgICBcdDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj51cGxvYWQgaW4gZm9ybTwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC11cGxvYWQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgXG4gIDxlbC11cGxvYWRcbiAgICBhY3Rpb249XCIjXCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yVXBsb2FkXCJcbiAgICA6ZmlsZS1saXN0PVwiZmlsZUxpc3RcIlxuICAgPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj51cGxvYWQgb3V0c2lkZTwvZWwtYnV0dG9uPlxuICA8L2VsLXVwbG9hZD5cblxuPC90ZW1wbGF0ZT5cblxuXG48c2NyaXB0IHNldHVwPlxuICBpbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbiAgY29uc3QgZmlsZUxpc3QgPSByZWYoW10pXG4gIGZ1bmN0aW9uIGJlZm9yVXBsb2FkKGZpbGUpIHtcbiAgICBmaWxlTGlzdC52YWx1ZS5wdXNoKHtcbiAgICAgIHVpZDogZmlsZS51aWQsXG4gICAgICBuYW1lOiBmaWxlLm5hbWUsXG4gICAgICBzdGF0dXM6ICdzdWNjZXNzJyxcbiAgICAgIHVybDogJydcbiAgICB9KVxuICAgIHJldHVybiBmYWxzZVxuICB9XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

See demo for Reproduction Link

### What is Expected?

fix

### What is actually happening?

The file list cannot be opened automatically

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Please provide more information about this problem.

**Comment by sxzz** [comment]
You can add `style="width: 100%"` to `<el-upload />`
