### ISSUE TITLE
Global css may change component style

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#669]
```html
App.vue
<style lang="scss">
    * {
        box-sizing: border-box;
        word-break: break-word;
    }

    body {
        font-family: "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
        font-size: 14px;
    }
</style>
```
When I add these style. `box-sizing: border-box` cause the different circle size. `word-break: break-word` cause the text error. Is it worth improving?
![image](https://user-images.githubusercontent.com/38392315/100056815-489ebc80-2e61-11eb-9d9e-9e73a6b53ee0.png)
![image](https://user-images.githubusercontent.com/38392315/100056850-53595180-2e61-11eb-9881-9368b7f1c4aa.png)

**Comment by JeremyWuuuuu** [comment]
Since the strategy of `ElementPlus` is the same as `ElementUI` we do not want to use `scoped style` for certain reasons, so the users will have to take care of their global style in order to avoid the impact on the UI library, adding `!important` modifier to CSS properties is a **had to** situation when it has to be added. Users sometimes need to styling the component themselves.

**Comment by kooriookami** [comment]
I changed global style to body. It still has problems. Is it possible to set default values to element components?
```
    body {
        font-family: "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
        font-size: 14px;
        box-sizing: border-box;
        word-break: break-word;
    }
```

**Comment by JeremyWuuuuu** [comment]
This requirement is too specific, fixing this issue would cause another, this is the reason that `ElementPlus` wants to stay neutral. The way of solving this issue is to put the rule out of `.el` scope. you can achieve that via `attributes selector`

**Comment by kooriookami** [comment]
> This requirement is too specific, fixing this issue would cause another, this is the reason that `ElementPlus` wants to stay neutral. The way of solving this issue is to put the rule out of `.el` scope. you can achieve that via `attributes selector`

I found it may be the `slider popover` problem. The same style `word-break: break-word;` cause two effects.
![image](https://user-images.githubusercontent.com/38392315/100085357-e5278580-2e86-11eb-93c2-3b6187a1e54a.png)![image](https://user-images.githubusercontent.com/38392315/100085378-e9ec3980-2e86-11eb-8d48-9d299c610c0e.png)
Left is `slider popover`, right is `popover component`
