### ISSUE TITLE
[Bug Report] [Component] [upload] the callback function "on-success" of "el-upload" doesn't work as expected 

### ISSUE THREAD

**Issue by ancheGT** [element-plus/element-plus#6697]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Firefox 98.0`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Link](it about the callback function after upload,I have no idea to make a link on Playground or JSFiddle or CodePen)

### Steps to reproduce

if the code as following:
```vue
<template>
  <div v-loading.fullscreen.lock="fullscreenLoading">
    <el-upload
      class="imgUpload"
      drag
      multiple
      :action="`${fileUploadPath}`"
      :on-remove="uploadRemove"
      :on-error="uploadError"
      :on-success="uploadSuccess"
      list-type="picture"
      :before-upload="uploadBefore"
      :data="{ prefix: filePrefix }"
      :file-list="inImgData"
    >
      <el-icon class="el-icon--upload">
        <upload-filled />
      </el-icon>
      <div class="el-upload__text">
        <em>click to upload</em>
      </div>
      <template #tip>
        <div class="el-upload__tip">
          notice
        </div>
      </template>
    </el-upload>
  </div>
</template>
```

and **uploadSuccess** is empty,like this:

```js
uploadSuccess(res, file, fileList) {}
```

### What is Expected?

do not modify inImgData

### What is actually happening?

it will append file data into inImgData in the background,and the file url will like "blob:http://localhost:8080/401bd988-8466-4355-8b71-71a31b2b8803"

### Additional comments

if I use 2.0.2,it will be OK,but if version greater than 2.0.3,it will reproduce

**Comment by sxzz** [comment]
This is by design. You can create a `computed` to filter out the fields you don't need.
