### ISSUE TITLE
[Bug Report] [Component] [upload] upload组件list-type值为picture-card时， show-file-list="false" 时组件无法显示

### ISSUE THREAD

**Issue by iqiuhu** [element-plus/element-plus#6702]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gICA8ZWwtdXBsb2FkIGFjdGlvbj1cIiNcIlxuICAgICAgbGlzdC10eXBlPVwicGljdHVyZS1jYXJkXCJcbiAgICAgIDpzaG93LWZpbGUtbGlzdD1cImZhbHNlXCIgICAgICAgICAgICAgICAgICAgIFxuICAgPlxuICAgICAgPGVsLWljb24gY2xhc3M9XCJ5aWggeWloLWFkZFwiPjwvZWwtaWNvbj5cbiAgIDwvZWwtdXBsb2FkPlxuXG5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce
```
 <el-upload action="#" list-type="picture-card" :show-file-list="false"  >
      <el-icon class="yih yih-add"></el-icon>
  </el-upload>
```

### What is Expected?

show-file-list="false" 应显示上传组件

### What is actually happening?

不显示上传组件

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
If you carefully check the documentation or watch the console, you will mention that your action is a required parameter, and secondly you have blocked the file list by: show-file-list="false".
```html
  <el-upload action="#" list-type="picture-card">
    <el-icon class="yih yih-add"></el-icon>
  </el-upload>
```

**Comment by iqiuhu** [comment]
:show-file-list="false"  是用来控制是否显示已上传文件列表 ，我的应用中不需要显示上传文件列表，但它不应该上传组件本身也不显示

**Comment by chenxch** [comment]
You can see [here](https://element-plus.org/zh-CN/component/upload.html#%E7%94%A8%E6%88%B7%E5%A4%B4%E5%83%8F%E4%B8%8A%E4%BC%A0).

**Comment by iqiuhu** [comment]
首先不谈使用场景，只讨论list-type为picture-card时， show-file-list的值为false 时不能显示上传组件，是设计理念还是bug
如果是设计理念，那这个 issue可以关闭了

**Comment by YunYouJun** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/25154432/159523218-02cff5c0-dc27-41c7-a567-a257f6489324.png">

Do you mean this is filelist?

It is called a photo wall because of these photos.

If you do not want to see them , you can use https://element-plus.org/zh-CN/component/upload.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E4%BB%B6%E7%BC%A9%E7%95%A5%E5%9B%BE directly.

**Comment by iqiuhu** [comment]
![image](https://user-images.githubusercontent.com/13246287/160045434-91aab7e8-8760-42ab-8653-906145cce597.png)
list-type为picture-card， show-file-list的值为false 是上传框

**Comment by YunYouJun** [comment]
不需要设置 `show-file-list`。

**Comment by flashmecn** [comment]
也遇到此问题，想隐藏组件列表，换自己的列表样式，结果上传按钮也消失了！！show-file-list:false应该只隐藏照片墙列表吧？怎么全部都隐藏了？？

**Comment by iqiuhu** [comment]
这是人家的设计理念吧，开发者不让提这样的issue,只能接受

**Comment by YunYouJun** [comment]
> 也遇到此问题，想隐藏组件列表，换自己的列表样式，结果上传按钮也消失了！！show-file-list:false应该只隐藏照片墙列表吧？怎么全部都隐藏了？？

主要是想要自定义列表样式的话，别用照片墙啊……照片墙本来就是一类上传样式的代称。



> 这是人家的设计理念吧，开发者不让提这样的issue,只能接受

主要原因是，本身这个组件为了提供照片墙这一组件，内部逻辑已经变得复杂了，再专门为次不同组件设置判断逻辑，只会进一步增加可维护性。
当然如果该功能确实有用，那么便是值得实现的。但是该需求显然可以使用其他更为简洁的方式替代，那么进一步在此逻辑上开发便是得不偿失的。

**Comment by chenxch** [comment]
> 这是人家的设计理念吧，开发者不让提这样的issue,只能接受

我只是一个路人，不过看到这上面的回复我觉得有些不妥，冒昧发表下意见。
首先开发者从始至终没有说过这样的话。
然后回到问题本质上，你的场景是不想要照片墙，又需要那个+的按钮出触发选择图片上传是么？
如果是这样的话文档中的`用户头像`可以满足，如果你能比较熟练使用文档上的API，那么`手动上传`也能给你一些很好的灵感。组件demo是死的，人是活的，东西要能灵活的运用，而不是一味的拿来主义。Peace✌️

**Comment by QQOQ** [comment]
我也遇到了这个问题，之前版本没问题的，这两天更新了发现不显示了，很尴尬

**Comment by QQOQ** [comment]
> > 这是人家的设计理念吧，开发者不让提这样的issue,只能接受
> 
> 我只是一个路人，不过看到这上面的回复我觉得有些不妥，冒昧发表下意见。 首先开发者从始至终没有说过这样的话。 然后回到问题本质上，你的场景是不想要照片墙，又需要那个+的按钮出触发选择图片上传是么？ 如果是这样的话文档中的`用户头像`可以满足，如果你能比较熟练使用文档上的API，那么`手动上传`也能给你一些很好的灵感。组件demo是死的，人是活的，东西要能灵活的运用，而不是一味的拿来主义。Peace✌️

用户头像在onChange的status: "ready"时没有返回图像url，需要上传完成后服务端返回，这样不太友好

**Comment by YunYouJun** [comment]
> 用户头像在onChange的status: "ready"时没有返回图像url，需要上传完成后服务端返回，这样不太友好

是否愿意尝试提交相应 PR ？

> 正如上文所说，没有继续优化这方面主要出于投入产出比，如果显然有一个同等效果的功能可替代，而继续增加某个组件的复杂性是得不偿失的。而如果某个功能确实有其价值，则是值得实现的。
