### ISSUE TITLE
[Feature Request] [Enhancement] [dialog] dialog destroy-on-close enhancement

### ISSUE THREAD

**Issue by vanchain** [element-plus/element-plus#6705]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `dialog`

## Description

当我使用dialog弹框的时候，我想要一种，每次打开弹框，弹框的生命周期都会重新加载一遍的效果，这样可以方便做许多业务。看destroy-on-close属性的描述可以实现这个功能，但是实际使用并不能实现。这块可以考虑一下吗？谢谢

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
destroy-on-close做的操作是dialog内部组件并不是dialog，你想想自己销毁自己那不变成自杀了吗

**Comment by gjfei** [comment]
你可以通过把给dialog一个v-if

**Comment by vanchain** [comment]
> 你可以通过给dialog一个v-if

感谢，突然发现自己的v-if用错地方了
