### ISSUE TITLE
Bug with el-image

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#671]
```html
<template>
  <el-image
    :src="img"
    style="width: 400px; height: 400px; background: whitesmoke"
  >
    <template #placeholder>加载中</template>
    <template #error>加载失败</template>
  </el-image>

  <el-button type="primary" @click="click">change</el-button>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      img: "https://img.yzcdn.cn/vant/cat.jpeg",
    };
  },
  methods: {
    click() {
      this.img = "";
    },
  },
};
</script>

<style>
</style>
```
![image](https://user-images.githubusercontent.com/38392315/100060033-f8c2f400-2e66-11eb-8bbd-0a3f90920962.png)
When you click the button. It shows an error image. Actually expect a custom error.

**Comment by JeremyWuuuuu** [comment]
I dug it up and I find out that the event `onerror` was not event triggered by Image, we need to find a way to fix this issue.
If you change the setter in `click` method to some url which doesn't even exist it will still be the same as an empty link though.

**Comment by kooriookami** [comment]
> I dug it up and I find out that the event `onerror` was not event triggered by Image, we need to find a way to fix this issue.
> If you change the setter in `click` method to some url which doesn't even exist it will still be the same as an empty link though.

When the url changes, I can change a key to refresh the compoent. `<el-image :key="key"></el-image>`

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/100064840-fca64480-2e6d-11eb-8b31-9e67eeb676b4.png)
This is what I've found out on [MDN#Image](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLImageElement)

**Comment by kooriookami** [comment]
Well, chrome does not compatible with `onerror`. It seems only `new Image()` can be used.

**Comment by JeremyWuuuuu** [comment]
> Well, chrome does not compatible with `onerror`. It seems only `new Image()` can be used.

I already found a work around on this issue, PR is on the way.
