### ISSUE TITLE
[Feature Request] [Docs] [dialog] Pleae add a demo to show how to get "ref" of component in el-dialog

### ISSUE THREAD

**Issue by ancheGT** [element-plus/element-plus#6718]
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `dialog`

## Description

As https://element-plus.gitee.io/en-US/component/dialog.html#centered-content says,I made a "openDialog" function for el-dialog to get "refCompContent",my code just like:

```vue
<template>
    <el-dialog ref="refDialog" @open="openDialog">
        <component :is="compContent" ref="refCompContent"/>
        <!-- or -->
        <!-- <compContent ref="refCompContent"/> -->
    </el-dialog>
</template>

<script>
    const refCompContent = ref(null)
    const openDialog = () => {
        console.log('>>> refCompContent::', refCompContent)
    }
</script>
```
But "refCompContent" is null,how to get "refCompContent" in openDialog correctly?Thank you

### Additional comments

_(empty)_

**Comment by QJune** [comment]
你在script 加上setup看看 <script setup>

**Comment by xlzy520** [comment]
> 你在script 加上setup看看 <script setup>

遇到相同的问题，加了没有效
