### ISSUE TITLE
[Feature Request] [Enhancement] [input] Input 更好的数字，以及格式化支持

### ISSUE THREAD

**Issue by norangit** [element-plus/element-plus#6719]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `input`

## Description

可以参考这个https://primefaces.org/primevue/#/inputnumber

这个做的很完美，支持的数字在Number.MAX_SAFE_INTEGER 内原样显示，超过了也是浏览器处理的，看了下源代码，比较长，但是开源的，可以参考过来^_^

### Additional comments

无

**Comment by sxzz** [comment]
Duplicate of #6652
