### ISSUE TITLE
[Bug Report] [Component] [table, image] table表格中的开启预览图片会产生奇怪的样式并伴随事件穿透

### ISSUE THREAD

**Issue by anzhiyu-c** [element-plus/element-plus#6722]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.4`
- Browser / OS: `谷歌 win10`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`
- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb21kc2FkYXNkVG9tZHNhZGFzZFRvbWRzYWRhc2RUb21kc2FkYXNkVG9tZHNhZGFzZFRvbWRzYWRhc2RUb21kc2FkYXNkJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgYm9yZGVyPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgc2hvdy1vdmVyZmxvdy10b29sdGlwLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIj5cbiAgICAgICAgIDxlbC1pbWFnZVxuICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDYwcHg7IGhlaWdodDogNjBweFwiXG4gICAgICAgICAgc3JjPVwiaHR0cHM6Ly9pc3N1ZS5lbGVtZW50LXBsdXMub3JnL2Fzc2V0cy9lbGVtZW50LXBsdXMtbG9nby5lNTViMDczOS5zdmdcIlxuICAgICAgICAgIDpwcmV2aWV3LXNyYy1saXN0PVwiWydodHRwczovL2lzc3VlLmVsZW1lbnQtcGx1cy5vcmcvYXNzZXRzL2VsZW1lbnQtcGx1cy1sb2dvLmU1NWIwNzM5LnN2ZyddXCJcbiAgICAgICAgPlxuICAgICAgICA8L2VsLWltYWdlPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiPlxuICAgICAgICAgICAgICA8ZWwtYnV0dG9uPuaIkeaYr+aMiemSrjwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIFx0PC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue'
import { User } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
const tableData = [
  {
    date: '2016-05-03',
    name: 'TomdsadasdTomdsadasdTomdsadasdTomdsadasdTomdsadasdTomdsadasdTomdsadasd',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>

<template>
  <!-- Element Plus icons -->
  <el-icon><User /></el-icon>
    <el-table :data="tableData" style="width: 100%" border>
      <el-table-column type="selection" width="55" />
      <el-table-column prop="date" label="Date" width="180" />
      <el-table-column prop="name" label="Name" width="180" show-overflow-tooltip/>
      <el-table-column prop="address" label="Address">
         <el-image
          style="width: 60px; height: 60px"
          src="https://issue.element-plus.org/assets/element-plus-logo.e55b0739.svg"
          :preview-src-list="['https://issue.element-plus.org/assets/element-plus-logo.e55b0739.svg']"
        >
        </el-image>
      </el-table-column>
       <el-table-column prop="address" label="Address">
              <el-button>我是按钮</el-button>
      </el-table-column>
  	</el-table>
</template>
```
当在el-table中使用el-image时并开启el-image的preview-src-list属性会产生奇怪的样式，除此之外还会产生事件穿透

### What is Expected?

在el-table中使用el-image时并开启el-image的preview-src-list属性遮罩层正常且不会有事件穿透，点击为直接让遮罩层消失，而不会产生穿透事件

### What is actually happening?

当在el-table中使用el-image时并开启el-image的preview-src-list属性会产生奇怪的样式，除此之外还会产生事件穿透

### Additional comments

![](https://s3.bmp.ovh/imgs/2022/03/c1104dc720b039ad.png)

**Comment by btea** [comment]
你可以将 `preview-teleported` 属性设置为 `true`。
