### ISSUE TITLE
[Bug Report] [Style] [All] 使用Sass覆盖主题颜色primary-base时，传入CSS 变量 var() 会报错：$color2: var(xxx) is not a color.

### ISSUE THREAD

**Issue by load-more** [element-plus/element-plus#6724]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `1.3.0-beta.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCAnZ2xvYmFsLmNzcydcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0iLCJ2YXJpYWJsZS5jc3MiOiIvLyDoh6rlrprkuYnlhajlsYDmoLflvI/lj5jph49cbiRmZy1jb2xvci0xOiB2YXIoLS1mZy1jb2xvci0xKTtcblxuLy8g6KaG55uWIGVsZW1lbnQtcGx1cyDmoLflvI/lj5jph49cbkBmb3J3YXJkICdlbGVtZW50LXBsdXMvdGhlbWUtY2hhbGsvc3JjL2NvbW1vbi92YXIuc2Nzcycgd2l0aCAoXG4gIC8vIOaXoOazleino+aekCB2YXIoKVxuICAkY29sb3JzOiAoXG4gICAgJ3ByaW1hcnknOiAoXG4gICAgICAnYmFzZSc6ICRmZy1jb2xvci0xLFxuICAgICksXG4gICksXG4pO1xuIiwiZ2xvYmFsLmNzcyI6Ijpyb290IHtcbiAgLS1mZy1jb2xvci0xOiBncmVlbjtcbn0ifQ==)

### Steps to reproduce

我想实现项目切换主题的功能，于是想通过 js 修改 css 变量，然后在 scss 文件中覆盖 element-plus 中的 color-primary-base。以下是步骤：
1. 在 main.ts 引入了一个 css 文件，其中设置了以下样式：
```css
:root {
  --fg-color-1: green;
}
```

2. 在 variable.scss 中覆盖主题颜色：
```scss
$fg-color: var(--fg-color-1);
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  // 无法解析 var()
  $colors: (
    'primary': (
      'base': $fg-color-1,
    ),
  ),
);
```
但结果却报错了：
![](https://gitee.com/gainmore/imglib/raw/master/img/20220320171159.png)

### What is Expected?

color-primary-base 可以变为 green。

### What is actually happening?

CSS 变量 --fg-color-1 并没有被解析出来。

### Additional comments

_(empty)_

**Comment by YunYouJun** [comment]
`$colors.primary.base` 是基础色值，需要根据其生成其他色彩级别，必须为确定数值，不能使用 CSS 变量。

**Comment by load-more** [comment]
> `$colors.primary.base` 是基础色值，需要根据其生成其他色彩级别，必须为确定数值，不能使用 CSS 变量。

原来如此，谢谢！
