### ISSUE TITLE
[Bug Report] [Style] [image] el-table中其中一列使用el-image时，当点击图片展示大图时，出现el-table内容和表格线覆盖el-image大图

### ISSUE THREAD

**Issue by CloudClient** [element-plus/element-plus#6734]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.0.1`
- Browser / OS: `Chrome/77.0.3865.120`
- Build Tool: `Webpack`

### Related Component

- `el-image`

### Reproduction Link

[Link](参考地址： https://blog.csdn.net/weixin_43245095/article/details/123246885?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522164785037816780271566595%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=164785037816780271566595&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-6-123246885.142^v2^pc_search_result_cache,143^v4^control&utm_term=element-plus+el-table+el-table-column+%E7%BB%84%E4%BB%B6%E4%B8%AD+%E4%BD%BF%E7%94%A8%E6%8F%92%E6%A7%BD+%E5%8A%A0%E8%BD%BD+el-image+%E7%BB%84%E4%BB%B6%E9%A2%84%E8%A7%88%E5%9B%BE%E7%89%87+%E5%B1%82%E7%BA%A7%E8%BF%87%E4%BD%8E%E9%97%AE%E9%A2%98&spm=1018.2226.3001.4187)

### Steps to reproduce

参考复现链接

### What is Expected?

参考复现链接

### What is actually happening?

参考复现链接

### Additional comments

参考复现链接

**Comment by chenxch** [comment]
你可以参考下 #6722 中 @btea  提供的解决方案

**Comment by CloudClient** [comment]
> 你可以参考下 #6722 中 @btea 提供的解决方案

好像 [#6722 ](https://github.com/element-plus/element-plus/issues/6722) 也没有得以解决吧

**Comment by chenxch** [comment]
> > 你可以参考下 #6722 中 @btea 提供的解决方案
> 
> 好像 [#6722 ](https://github.com/element-plus/element-plus/issues/6722) 也没有得以解决吧

你试了么，如果没有可以试一下，因为你没有提供线上demo，我这边无法帮你验证

**Comment by CloudClient** [comment]
> > > 你可以参考下 #6722 中 @btea 提供的解决方案
> > 
> > 
> > 好像 [#6722 ](https://github.com/element-plus/element-plus/issues/6722) 也没有得以解决吧
> 
> 你试了么，如果没有可以试一下，因为你没有提供线上demo，我这边无法帮你验证

第一次提issue ，见谅！  我进行了测试，并且测试了#6722也没有解决 如果方便可以验证一下#6722，如果#6722解决，我的也是可以解决的。

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/159251161-dd0fbdac-e5b8-45bf-94d3-c08bfa305e74.png)
=》
![image](https://user-images.githubusercontent.com/23251408/159251258-6c5e831c-ac4d-4c20-813b-0f27e1929a0b.png)
@CloudClient  你可以看一下哈，开源社区就是需要大家一起贡献的哈，就是下次如果能提交playground是最好的。

**Comment by CloudClient** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/159251161-dd0fbdac-e5b8-45bf-94d3-c08bfa305e74.png) =》 ![image](https://user-images.githubusercontent.com/23251408/159251258-6c5e831c-ac4d-4c20-813b-0f27e1929a0b.png) @CloudClient 你可以看一下哈，开源社区就是需要大家一起贡献的哈，就是下次如果能提交playground是最好的。

之前是因为我的版本是2.0.1  经过版本升级发现确实解决了问题，非常感谢！！！
