### ISSUE TITLE
[Bug Report] [Component] [cascader] Cascader Unexpected display 'No Data'

### ISSUE THREAD

**Issue by zhangalexhy** [element-plus/element-plus#6739]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.0.4`
- Browser / OS: `windows 10`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2FzY2FkZXIgOnByb3BzPVwicHJvcHNcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiB2LW1vZGVsPVwidmFsdWVcIi8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJzsgXG4gIFxuY29uc3Qgb3B0aW9ucyA9IFt7XG4gIGxhYmVsOicxJyxcbiAgdmFsdWU6JzEnXG59XVxuY29uc3QgdmFsdWUgPSByZWYoJzEnKTtcbmNvbnN0IHByb3BzID0ge1xuICBsYXp5OiB0cnVlLFxuICBsYXp5TG9hZChub2RlLCByZXNvbHZlKSB7XG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICByZXNvbHZlKFt7XG4gIFx0XHRcdGxhYmVsOicyJyxcbiAgXHRcdFx0dmFsdWU6JzInXG5cdFx0XHR9XSlcbiAgICB9LCAyMDApXG4gIH0sXG4gIGNoZWNrU3RyaWN0bHk6IHRydWUsXG4gIGVtaXRQYXRoOiBmYWxzZSxcbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

点击组件
click the cascader box

### What is Expected?

二级菜单在有数据时不显示No Data
the second level box doesn't have 'No Data'

### What is actually happening?

当我使用el-cascader的时候，我用的是lazyload懒加载，但是我初始化的时候设置了options来作为它的一级目录，但是当我v-model绑定的值在options中存在时，级联菜单会自动展开该值对应的二级菜单，并且lazyload函数resolve了数据，但是在二级菜单中不仅显示了数据，还意外了在中间显示了一个‘No Data’.
At the lazyload of 'el-cascader', I used 'options' as the first level default, when it's 'v-model' has default value, and the 'options' includes this default value, the 'cascader' will normally auto opend the second level, but we can clearly see the second level box has real data and 'No Data' in the middle of it.

### Additional comments

Forgive me for my poor English

![image](https://user-images.githubusercontent.com/51531505/159250971-da8ec5ce-e283-4546-9f7b-5061d237e26e.png)

**Comment by chenxch** [comment]
你可以先取消一下默认值，但是代码中的计算属性也存在问题，后面我会看一下如何修复这个问题。

**Comment by chenxch** [comment]
@btea Hi bro, this part of the code saw the records you helped to maintain. Please help to look at this problem when it is convenient. I can only guess that the use of too many classes has caused the two-way binding monitoring to fail.

**Comment by btea** [comment]
I think this rendering is wrong. After lazy loading, only the data returned by resolve should be rendered, and options are no longer rendered.

**Comment by chenxch** [comment]
I tested with the above demo, the value of isEmpty is not updated by computed after resolve.

**Comment by btea** [comment]
Sorry, I didn't understand the scene you described, can you describe it in more detail?

**Comment by chenxch** [comment]
I used the demo in the feedback to test. `No data` is controlled by isEmpty in `cascade-panel/menu.vue`. Due to lazy load, `const isEmpty = computed(() => !props. nodes.length)` gets a true, after the resolve of lazyload,`props.nodes` is updated, but `isEmpty` is not updated because `computed` is not triggered

**Comment by btea** [comment]
I see.  You can `watch` the `menus` changes in the `index.vue` file. The `nodes` attribute is passed here
https://github.com/element-plus/element-plus/blob/8639b585832ba994d63fff251bbbddcfe231eedc/packages/components/cascader-panel/src/index.vue#L6-L12

**Comment by chenxch** [comment]
I currently can only trigger the internal computed event through the structure. But I still don't understand why Store can cause responsiveness to fail.
https://github.com/chenxch/element-plus/blob/17d6d936532c512e7aa7b52bb122a1c8d61750e5/packages/components/cascader-panel/src/index.vue#L6-L12
