### ISSUE TITLE
[Bug Report] [Component] [dialog] dialog custom-class is invalid or the top props is invalid cause the style set failed  

### ISSUE THREAD

**Issue by Trojan0523** [element-plus/element-plus#6742]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGNsaWNraW5nID0gKCkgPT4ge1xuICB2aXNpYmxlLnZhbHVlID0gdHJ1ZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG48ZWwtYnV0dG9uIEBjbGljaz1cImNsaWNraW5nXCI+eHh4PC9lbC1idXR0b24+XHRcblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJ2aXNpYmxlXCIgdG9wPVwiMjB2aFwiPlxuICBcdDxlbC1idXR0b24+MTwvZWwtYnV0dG9uPlxuICA8L2VsLWRpYWxvZz5cblxuXG5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

1. add dialog props custom-class="dialog-height"
2. set style .dialog-height { margin-top: 20vh }
3. click button and change visible into true 

### What is Expected?

dialog style: --el-dialog-margin-top: 20vh;

### What is actually happening?

dialog style:
.el-dialog {
    transform: none;
    left: 0;
    position: relative;
    margin: 0 auto;
}

### Additional comments

i use vite to pack my project, when i config vite.config.ts, i use two plugins to setup the element-plus component and auto import style： 
import AutoImport from 'unplugin-auto-import/vite'
import createStyleImportPlugin, { ElementPlusResolve } from 'vite-plugin-style-import'
export default () => {
  return defineConfig({
    plugins: [
      Components({
        dts: true,
        resolvers: [
          ElementPlusResolver(),
        ],
      }),
      createStyleImportPlugin({
        resolves: [
          ElementPlusResolve(),
        ],
      }),
    ],
})
} 
maybe the internal plugin cause the problem, hope help

**Comment by liuguangsen0409** [comment]
+1 also met this problem

**Comment by liuguangsen0409** [comment]
u can use inline style to solve it, but actually it is not elegant

**Comment by Trojan0523** [comment]
> u can use inline style to solve it, but actually it is not elegant

that is a temporary fix way, but actually doesn`t solve the original problem, and every time i have to add inline style to cover the initial style, and thanks for helping

**Comment by Trojan0523** [comment]
> u can use inline style to solve it, but actually it is not elegant

Extraneous non-props attributes (style) were passed to component but could not be automatically inherited because component renders fragment or text root nodes

**Comment by wilsunson** [comment]
+1 also met this problem

**Comment by Trojan0523** [comment]
> wilsunson

the reproduction demo is hard to write, can you support a mini reproducted demo for us?

**Comment by Trojan0523** [comment]
> +1 also met this problem

是不是基于element-admin升级的element-plus, 可以找下 style/element-ui.scss下有没有以下的样式:
```css
// to fixed https://github.com/ElemeFE/element/issues/2461
.el-dialog {
  transform: none;
  left: 0;
  position: relative;
  margin: 0 auto;
}
```

如果有此段代码请删除,问题解决，并非element-plus的问题，此issue关闭

**Comment by liuguangsen0409** [comment]
@Trojan0523 https://segmentfault.com/q/1010000041438518 this article given real why and how to fix it
