### ISSUE TITLE
[Bug Report] [Component] [input] input 组件无法监听键盘 esc 事件

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#6744]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBAa2V5ZG93bi5lc2M9XCJ0ZXN0XCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJylcblxuZnVuY3Rpb24gdGVzdCgpe1xuICBhbGVydCgxMjMpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

参见演示链接

### What is Expected?

使用 `@keyup.esc` `@keydown.esc` 可以正常触发指定事件

### What is actually happening?

使用 `@keyup.esc` `@keydown.esc` 均无法触发指定事件

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/159384210-fbad7762-9e23-44ae-9487-c000a5cf834f.png)
2.1.3及最新版均没有复现你的问题

**Comment by hooray** [comment]
> ![image](https://user-images.githubusercontent.com/39730999/159384210-fbad7762-9e23-44ae-9487-c000a5cf834f.png) 2.1.3及最新版均没有复现你的问题

谢谢，我刚用隐私模式也测试了确实正常，看来应该是哪个扩展导致的，感谢回复
