### ISSUE TITLE
[Bug Report] [Component] [select] <el-select v-model="value" :persistent="false"> 即关闭持久化且有默认值值时，显示的默认值为value的值而非lable的值

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#6746]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `win11  /  Chrome 101.0.4919.0（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPiBcbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiA6cGVyc2lzdGVudD1cImZhbHNlXCIgY2xhc3M9XCJtLTJcIiA6ZmlsdGVyYWJsZT1cInRydWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDpkZWZhdWx0Rmlyc3RPcHRpb249XCJ0cnVlXCIgc2l6ZT1cInNtYWxsXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICA+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoMSlcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnYScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMixcbiAgICBsYWJlbDogJ2InLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDMsXG4gICAgbGFiZWw6ICdjJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiA0LFxuICAgIGxhYmVsOiAnZCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogNSxcbiAgICBsYWJlbDonZScsXG4gIH1cbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

`<el-select v-model="value" :persistent="false" >` 即设置可本地搜索且关闭持久化时，当设置了默认值 `const value = ref(1)` ，输入框哪里显示的值是应该是lable的值，而实际显示的值是value的值，（即默认显示有问题）

![1647237682(1)](https://user-images.githubusercontent.com/31055355/158114050-84a7c296-f102-409d-8d25-cf43ae4cac18.jpg)

### What is Expected?

显示lable的值

### What is actually happening?

显示value的值

### Additional comments

_(empty)_

**Comment by vjguo** [comment]
因为设置了:persistent="false"，没点开下拉列表前，下拉列表连同el-option不会渲染。
el-option没有注册进el-select，el-select mounted时就没有取到对应的label而显示了默认的modelValue。

**Comment by nieyuyao** [comment]
@vjguo 确实是这样😅。不过有一个临时解决办法

```javascript
const value = ref(options[0])
```

**Comment by tolking** [comment]
对于 persistent=false，初始时无法从 Option 组件中获取值显示值。

或许需要默认值时你可以启用 persistent，或者通过 ref 手动修改 selectedLabel 值
