### ISSUE TITLE
[Feature Request] [i18n] 希望把中文设置为默认语言，或者增加打包替换英文的配置项

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#6757]
Feature type: **`i18n`**

## Details

- Enhanced compone nt name: `All`

## Description

我在想element-plus应该是国人用得最多为什么会把英文设置未默认语言，这无疑增加了大多出开发者的配置成本，且也增加了打包的体积，对于使用其他语言的开发者，我们的文档也是英语优先，所以我认为几乎不会对他们产生太大的影响，既然字体图标那都觉得它占用打包体积，为什么又对这个i18n的体积熟视无睹呢？
当然如果是英语使用者多一些（超过40%）我也是支持默认语言设置为英语的。element-plus团队是否做过这样的统计呢？

### Additional comments

_(empty)_

**Comment by WangJincheng4869** [comment]
可能是英文比较香吧，汉语太臭了
