### ISSUE TITLE
希望form组件可以加一个getupdatecolumn方法获取绑定的model中哪些属性被修改了

### ISSUE THREAD

**Issue by Cyril5169** [element-plus/element-plus#676]
希望form组件可以加一个getupdatecolumn方法获取绑定的model中哪些属性被修改了

**Comment by JeremyWuuuuu** [comment]
Could you specify the requirement? We need to estimate the effort before doing so.

**Comment by Cyril5169** [comment]
例如，我使用el-form编辑一条数据，假如用户没有做任何修改，点击保存，那么我需要知道用户没有修改任何东西，我就不需要做任何处理。如果用户只修改了某个字段的值，那么我只需要告诉后台，只需要修改这一个值即可，而不用所有值都更新一遍。
现在我的处理方式是进入编辑时记录model的值：this.comparativeData = JSON.parse(JSON.stringify(this.model));在保存时判断：Object.keys(this.comparativeData).forEach(key => {
    if (this.model[key] != this.comparativeData[key]) {
        this.updateColumns.push(key);
    }
})

**Comment by lzq920** [comment]
> 例如，我使用el-form编辑一条数据，假如用户没有做任何修改，点击保存，那么我需要知道用户没有修改任何东西，我就不需要做任何处理。如果用户只修改了某个字段的值，那么我只需要告诉后台，只需要修改这一个值即可，而不用所有值都更新一遍。
> 现在我的处理方式是进入编辑时记录model的值：this.comparativeData = JSON.parse(JSON.stringify(this.model));在保存时判断：Object.keys(this.comparativeData).forEach(key => {
> if (this.model[key] != this.comparativeData[key]) {
> this.updateColumns.push(key);
> }
> })

我觉得你说的问题跟组件没有关系呢，更像是graphql的做法

**Comment by JeremyWuuuuu** [comment]
Watch you have been asking is a time machine which tracks data change, you can achieve that via Vue builtin `Watch` API. It's just as simple as it could be.

**Comment by JeremyWuuuuu** [comment]
Via watch you can implement the diff functionality yourself, instead of get it straight from `Form`, the mechanism is quite simple just like this.
With VCA, you can do 
```ts
watch(model, (val, oldVal) => {
    const diffResult = getDiff(val, oldVal);
    // do something
})
```
Via VOA you can do:
```ts
watch: {
  model(val, oldVal) {
    const diffResult = getDiff(val, oldVal);
    // do something
  }
}
```

**Comment by JeremyWuuuuu** [comment]
Hey guys, I am closing this issue because we want all feature requests to be tracked in discussion here is a link that you might find it helpful
https://github.com/element-plus/element-plus/discussions/905

And in order to request a new feature you can check here:

https://github.com/element-plus/element-plus/discussions/new
