### ISSUE TITLE
[Bug Report] [Component] [tree] 组件API文档错误

### ISSUE THREAD

**Issue by hidumou** [element-plus/element-plus#6767]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/99.0.4844.83`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZSA6ZGF0YT1cImRhdGFcIiA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIiBAbm9kZS1jbGljaz1cImhhbmRsZU5vZGVDbGlja1wiIC8+XG4gIDxwIHYtaHRtbD1cInJlc3VsdFwiPjwvcD5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQge3JlZn0gZnJvbSBcInZ1ZVwiXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGxhYmVsOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cbiAgXG5jb25zdCByZXN1bHQgPSByZWYoJycpXG5jb25zdCBoYW5kbGVOb2RlQ2xpY2sgPSAoZGF0YTogVHJlZSxub2RlLGlucyxlKSA9PiB7XG4gIC8vIHRyZWUtbm9kZS52dWUgbGluZToyNDkgKHRyZWUuY3R4LmVtaXQoJ25vZGUtY2xpY2snLCBwcm9wcy5ub2RlLmRhdGEsIHByb3BzLm5vZGUsIGluc3RhbmNlLCBlKSlcbiAgcmVzdWx0LnZhbHVlID0gYFxuICBhcmcz77yaJHtpbnMudHlwZS5uYW1lfTs8YnIvPlxuICBhcmc077yaJHtlLmN1cnJlbnRUYXJnZXQuY2xhc3NMaXN0LnZhbHVlfTtgXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cblxuY29uc3QgZGVmYXVsdFByb3BzID0ge1xuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

文档错了，还是API接口错了，具体以哪个为准？

### What is Expected?

调整tree node-click 事件 API参数顺序

### What is actually happening?

nothing

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
```vue
tree.ctx.emit('node-click', props.node.data, props.node, instance, e)
```
参数顺序没错哦
