### ISSUE TITLE
[Bug Report] [Component] [table] table横向滚动条显示问题

### ISSUE THREAD

**Issue by yoyoyo-wzw** [element-plus/element-plus#6770]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHdpZHRoID0gcmVmKDMwMClcbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICB3aWR0aC52YWx1ZSA9IHdpZHRoLnZhbHVlID09PSAxMDAgPyAzMDAgOiAxMDBcbn1cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICAgIHRhZzogJ0hvbWUnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgdGFnOiAnT2ZmaWNlJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwic2lkZWJhclwiIDpzdHlsZT1cInt3aWR0aDogd2lkdGggKyAncHgnfVwiPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVDbGlja1wiPuWxleW8gC/nvKnlm548L2J1dHRvbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibWFpblwiPlxuICAgICAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgLz5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXRlXCIgbGFiZWw9XCJTdGF0ZVwiIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImNpdHlcIiBsYWJlbD1cIkNpdHlcIiAvPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ6aXBcIiBsYWJlbD1cIlppcFwiIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25zXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PlxuICAgICAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwidGV4dFwiIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgICAgICAgICAgICAgPuaMiemSrjwvZWwtYnV0dG9uXG4gICAgICAgICAgICA+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgICA8L2VsLXRhYmxlPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4uY29udGFpbmVyIHtcbiAgZGlzcGxheTogZmxleDtcbn1cbi5zaWRlYmFyIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogcmVkO1xuICBtYXJnaW4tcmlnaHQ6IDMwcHg7XG59XG4ubWFpbiB7XG4gIGZsZXg6IDE7XG4gIG92ZXJmbG93OiBoaWRkZW47XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

注：不清楚在 Element Plus Playground中为什么无法复现滚动条，可在vite搭建的项目中，该问题确实存在。
1.点击展开/缩回按钮，缩回侧边栏，通过flex布局，表格会对应变宽
2.展开侧边栏，侧边栏展开的时候，table对应变窄，下方出现了横向滚动条，且该滚动条无法进行拉动

### What is Expected?

侧边栏的展开缩回，在表格容器宽度足够的情况下，表格不出现横向滚动条

### What is actually happening?

侧边栏的展开缩回，在表格容器宽度足够的情况下，表格出现了横向滚动条，且滚动条无法拖动

### Additional comments

Element Plus Playground中相同的代码没有复现该问题，麻烦大佬们新建一个项目试试~

**Comment by yoyoyo-wzw** [comment]
![image](https://user-images.githubusercontent.com/57552363/159631568-027878df-a0f5-4d0e-87a8-c558eb1d6f1d.png)

**Comment by 34205037** [comment]
确定用的是2.1.4吗？这个问题我在2.0.x某个版本之前也发现了，但后面有几次相关的fix之后已经没了

**Comment by yoyoyo-wzw** [comment]
> 确定用的是2.1.4吗？这个问题我在2.0.x某个版本之前也发现了，但后面有几次相关的fix之后已经没了

多谢提醒，之前发现问题后重新install新版本，没重启项目，导致问题还存在。重新启动服务后该问题的确解决了~
