### ISSUE TITLE
el-date-picker 选择以后value值改变了但是视图不显示

### ISSUE THREAD

**Issue by 1948037137** [element-plus/element-plus#678]
![image](https://user-images.githubusercontent.com/46392442/100068559-ac7db100-2e72-11eb-9c34-67dce194dc59.png)

**Comment by JeremyWuuuuu** [comment]
See #609 
Also See #603

**Comment by JeremyWuuuuu** [comment]
Closing due to duplication

**Comment by JeremyWuuuuu** [comment]
This is a bug caused by `Vue`, the simplest way to solve this is to lock your `Vue` version to `3.0.0` instead of using `^` to get the most compatible version.
