### ISSUE TITLE
[Bug Report] [Component] [table] There was no getSelectionRows function for table components prior to version 2.0.5

### ISSUE THREAD

**Issue by Aphadite** [element-plus/element-plus#6780]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome 99.0.4844.82`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbiBpbXBvcnQge0VsTWVzc2FnZX0gZnJvbSBcImVsZW1lbnQtcGx1c1wiO1xuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9XVxuY29uc3QgdGFibGVSZWYgPSByZWYoKVxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKHRhYmxlUmVmLnZhbHVlLmdldFNlbGVjdGlvblJvd3MoKS5sZW5ndGgpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXRhYmxlXG4gICAgcmVmPVwidGFibGVSZWZcIlxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICBzdHlsZT1cIndpZHRoOiAxMDAlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxMjBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+e3sgc2NvcGUucm93LmRhdGUgfX08L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgc2hvdy1vdmVyZmxvdy10b29sdGlwIC8+XG4gIDwvZWwtdGFibGU+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAyMHB4XCI+XG5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCI+Z2V0U2VsZWN0ZWRSb3dzPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce
[reproduceLink](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbiBpbXBvcnQge0VsTWVzc2FnZX0gZnJvbSBcImVsZW1lbnQtcGx1c1wiO1xuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9XVxuY29uc3QgdGFibGVSZWYgPSByZWYoKVxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKHRhYmxlUmVmLnZhbHVlLmdldFNlbGVjdGlvblJvd3MoKS5sZW5ndGgpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXRhYmxlXG4gICAgcmVmPVwidGFibGVSZWZcIlxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICBzdHlsZT1cIndpZHRoOiAxMDAlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxMjBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+e3sgc2NvcGUucm93LmRhdGUgfX08L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxMjBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgc2hvdy1vdmVyZmxvdy10b29sdGlwIC8+XG4gIDwvZWwtdGFibGU+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAyMHB4XCI+XG5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCI+Z2V0U2VsZWN0ZWRSb3dzPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)
### What is Expected?

the length of the arr

### What is actually happening?

tableRef.value.getSelectionRows is not a function

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
This method was added after 2.0.6 and you can upgrade the version.
