### ISSUE TITLE
[Bug Report] [Build] [button] Dynamically set the type of button, npm run build fails

### ISSUE THREAD

**Issue by 1648045459** [element-plus/element-plus#6784]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.1.1`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Github Repo](https://github.com/1648045459/vue3-Element-Plus-buttons/blob/master/src/views/home/Home.vue)

### Steps to reproduce

执行npm run build指令

### What is Expected?

npm run build成功

### What is actually happening?

src/views/home/Home.vue:7:19 - error TS2322: Type 'string' is not assignable to type 'BuildPropType<StringConstructor, "" | "default" | "text" | "success" | "info" | "warning" | "primary" | "danger", unknown> | undefined'.

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
```ts
import type { ButtonType } from 'element-plus'
const type = ref<ButtonType>('info')
```
