### ISSUE TITLE
[Bug Report] [Component] [date-picker] 只读状态下，Input 获取焦点，边框会变成主题色，Date也可以，但Date Time Range获取焦点时，边框并未变色

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#6795]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Edge Version 99.0.1150.30`
- Build Tool: `CDN`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYmxvY2tcIj5cbiAgICA8ZWwtaW5wdXQgOnJlYWRvbmx5PVwidHJ1ZVwiLz5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcblx0XHQgIDpyZWFkb25seT1cInRydWVcIlxuICAgICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgICA6c2hvcnRjdXRzPVwic2hvcnRjdXRzXCJcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgICBlbmQtcGxhY2Vob2xkZXI9XCJFbmQgZGF0ZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoW1xuICBuZXcgRGF0ZSgyMDAwLCAxMCwgMTAsIDEwLCAxMCksXG4gIG5ldyBEYXRlKDIwMDAsIDEwLCAxMSwgMTAsIDEwKSxcbl0pXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5cbmNvbnN0IHNob3J0Y3V0cyA9IFtcbiAge1xuICAgIHRleHQ6ICdMYXN0IHdlZWsnLFxuICAgIHZhbHVlOiAoKSA9PiB7XG4gICAgICBjb25zdCBlbmQgPSBuZXcgRGF0ZSgpXG4gICAgICBjb25zdCBzdGFydCA9IG5ldyBEYXRlKClcbiAgICAgIHN0YXJ0LnNldFRpbWUoc3RhcnQuZ2V0VGltZSgpIC0gMzYwMCAqIDEwMDAgKiAyNCAqIDcpXG4gICAgICByZXR1cm4gW3N0YXJ0LCBlbmRdXG4gICAgfSxcbiAgfSxcbiAge1xuICAgIHRleHQ6ICdMYXN0IG1vbnRoJyxcbiAgICB2YWx1ZTogKCkgPT4ge1xuICAgICAgY29uc3QgZW5kID0gbmV3IERhdGUoKVxuICAgICAgY29uc3Qgc3RhcnQgPSBuZXcgRGF0ZSgpXG4gICAgICBzdGFydC5zZXRUaW1lKHN0YXJ0LmdldFRpbWUoKSAtIDM2MDAgKiAxMDAwICogMjQgKiAzMClcbiAgICAgIHJldHVybiBbc3RhcnQsIGVuZF1cbiAgICB9LFxuICB9LFxuICB7XG4gICAgdGV4dDogJ0xhc3QgMyBtb250aHMnLFxuICAgIHZhbHVlOiAoKSA9PiB7XG4gICAgICBjb25zdCBlbmQgPSBuZXcgRGF0ZSgpXG4gICAgICBjb25zdCBzdGFydCA9IG5ldyBEYXRlKClcbiAgICAgIHN0YXJ0LnNldFRpbWUoc3RhcnQuZ2V0VGltZSgpIC0gMzYwMCAqIDEwMDAgKiAyNCAqIDkwKVxuICAgICAgcmV0dXJuIFtzdGFydCwgZW5kXVxuICAgIH0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uYmxvY2sge1xuICBwYWRkaW5nOiAzMHB4IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgYm9yZGVyLXJpZ2h0OiBzb2xpZCAxcHggdmFyKC0tZWwtYm9yZGVyLWNvbG9yKTtcbiAgZmxleDogMTtcbn1cbi5ibG9jazpsYXN0LWNoaWxkIHtcbiAgYm9yZGVyLXJpZ2h0OiBub25lO1xufVxuLmJsb2NrIC5kZW1vbnN0cmF0aW9uIHtcbiAgZGlzcGxheTogYmxvY2s7XG4gIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgbWFyZ2luLWJvdHRvbTogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

让input获取焦点
让datepicker获取焦点

### What is Expected?

datepicker 边框变色

### What is actually happening?

datepicker 未变色

**Comment by josonho** [comment]
#6927
