### ISSUE TITLE
[Feature Request] [Enhancement] [select] el-select 回显 ：同时兼容 el-option 的label 属性 和 el-option 的插槽

### ISSUE THREAD

**Issue by gastrodia** [element-plus/element-plus#6805]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `select`

## Description

#

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/96605737/159884565-49e7dbe5-7f1b-4a43-9abb-71953344b574.png)
![image](https://user-images.githubusercontent.com/96605737/159884730-20c91fdf-98fc-4299-96d6-496df8beb473.png)

**Comment by kooriookami** [comment]
可以使用 prefix 插槽
