### ISSUE TITLE
[Bug Report] [Component] [carousel, cascader-panel] cascader-panel 和 cascader 多选情况下，选中面板聚焦混乱。element-ui没有强制聚焦功能，elemenet-plus新增聚焦功能。应该是这个原因引起的

### ISSUE THREAD

**Issue by liaowentuan** [element-plus/element-plus#6808]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome 99.0.4844.82`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-cascader-panel`

### Reproduction Link

[CodePen](https://codepen.io/liaowentuan/pen/qBpROLq)

### Steps to reproduce

bug1：先选中用户其中一个勾选框，然后切换角色。选中其中一个勾选框。结果被强制切换回用户勾选框
bug2：选中最上面的第一个，然后再选中最底下的一个，结果被聚焦到顶端第一个那边去了

### What is Expected?

1、不要切换选中面板
2、不要直接跳最上面第一个去，有可能我要选第二个的下方一个

### What is actually happening?

1、停留在原地
2、停留在原地

### Additional comments

1、移除element-plus/es/cascader-panel/src/index.mjs 里面的 scrollIntoView 方法，可以解决我的问题
2、cascader也有这个问题，但是我暂时没看在哪里，希望你们也找一下

**Comment by liaowentuan** [comment]
> 这些应该是在之后触发了`syncMenuState`，其方法中调用了 `nextTick(scrollToExpandingNode);`导致，但是我测试发现问题不断你反馈的，包括选择角色的时候会变成用户等问题。

那是因为v-model 那个数组 第一个是 [[1, value1] ,... ] 每次在第二个面板操作角色（面板2）的时候， nextTick(scrollToExpandingNode) 然后发现v-model 的 第一个值是 [1,value1] 判断是需要初始化到用户（面板1），被强制定向去用户面板了；同理：如果v-model/model-value 的值是 [[2, value1], ....] 每次操作用户（面板1）的时候，也会重定向到角色（面板2）那边。实在是 scrollIntoView 其实 多选的情况下，不需要改方法的。**用户在多选的时候，不需要如此聚焦**

**Comment by liaowentuan** [comment]
> cascader

昨晚看了一下，发现 cascader 里面就是用 el-cascader-panel ，所以只要 el-cascader-panel 解决了， cascader  就可以修复了。是一个东西

**Comment by liaowentuan** [comment]
codePen 里面 把 <el-cascader>  改成  <el-cascader-panel> 就可以重现这个问题了

**Comment by chenxch** [comment]
如果你已经有修复方案的话，可以尝试提交一个pr来修复这个组件

**Comment by liaowentuan** [comment]
> 如果你已经有修复方案的话，可以尝试提交一个pr来修复这个组件

那我研究下

**Comment by liaowentuan** [comment]
> 如果你已经有修复方案的话，可以尝试提交一个pr来修复这个组件

好吧，看来是vue2 坏习惯的问题，文档里面有写 :props="{ multiple: true }" 不允许这样写，是我孟浪了

**Comment by liaowentuan** [comment]
我在想，vue3 不是有isRef 方法么？为啥不支持 :props="{ multiple: true }" 这种行内的对象，而是一定要写个 ref(props),感觉给vue2 迁移 vue3 带来了隐藏成本
