### ISSUE TITLE
el-menu垂直布局下能否配置同时显示图标和文字

### ISSUE THREAD

**Issue by Cyril5169** [element-plus/element-plus#681]
我通关改变全局样式的方式显示出来了，不知道能否加个配置。因为用户反映只显示图标icon不够直观，不知道是什么功能，必须要显示文字。我添加文字之后是如下图这样的效果，看着还可以，希望能有一个配置
![1](https://user-images.githubusercontent.com/52475487/100077004-ccb26d80-2e7c-11eb-8ba0-6842b549051b.png)

**Comment by JeremyWuuuuu** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by JeremyWuuuuu** [comment]
Sample code should do.

**Comment by JeremyWuuuuu** [comment]
Also I believe that the doc site has sample like [NavMenu](https://element-plus.org/#/side-bar)

**Comment by Cyril5169** [comment]
like this: http://qkapdrpwu.hn-bkt.clouddn.com/el-menu.jpg

**Comment by JeremyWuuuuu** [comment]
[NavMenu](https://element-plus.org/#/zh-CN/component/menu) just modify the CSS will satisfy your request.

**Comment by Cyril5169** [comment]
OK~但是如果有个配置就更好了~,thanks.i will colse it
