### ISSUE TITLE
[Bug Report] [Component] [input] select-dropdown in remote-serach of el-input appear twice overlapping 

### ISSUE THREAD

**Issue by Trojan0523** [element-plus/element-plus#6816]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Rollup`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/en-US/component/input.html#remote-search)

### Steps to reproduce

1. open the original web site
2. find the remote-search input
3. click the input textarea

### What is Expected?

one select-dropdown

### What is actually happening?

select-dropdown appear twice and there are overlapped 

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/44562268/160042318-85d53481-7609-4377-8f7a-6c66aa570193.png)

**Comment by buqiyuan** [comment]
我这边没有复现这个问题，是必现的吗？尝试使用无痕模式再测试一下，排除浏览器插件等其他可能因素的影响。
![image](https://user-images.githubusercontent.com/39730999/160059434-e1737d74-6529-49d2-87be-f0b3d84dbbec.png)

**Comment by Trojan0523** [comment]
> 我这边没有复现这个问题，是必现的吗？尝试使用无痕模式再测试一下，排除浏览器插件等其他可能因素的影响。 ![image](https://user-images.githubusercontent.com/39730999/160059434-e1737d74-6529-49d2-87be-f0b3d84dbbec.png)

- 无痕模式下没有复现这个问题，不过在chrome正常模式下我发现可能是对应的高度有影响
![image](https://user-images.githubusercontent.com/44562268/160059833-18abbed1-c469-4efb-a598-863e1f81ae4a.png)
