### ISSUE TITLE
国际化：locale声明文件缺失

### ISSUE THREAD

**Issue by xiaogemm** [element-plus/element-plus#682]
import zhLocale from 'element-plus/lib/locale/lang/zh-cn'
在1.0.1-alpha.18时可正常引入。但1.0.1-alpha.21时声明文件缺失

**Comment by xiaogemm** [comment]
import zhLocale from 'element-plus/packages/locale/lang/zh-cn'
引入正常

**Comment by JeremyWuuuuu** [comment]
This could be the the recent packaging strategy. cc @zazzaz

**Comment by JeremyWuuuuu** [comment]
For now our API is not that stable, we are working on stabilizing the API.

**Comment by zazzaz** [comment]
will fix it soon

**Comment by xiaogemm** [comment]
> For now our API is not that stable, we are working on stabilizing the API.

这两天有看到快速迭代了好几个版本。已经超出我预期了。像你们这么更新，稳定是早晚的事

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.23
