### ISSUE TITLE
[Bug Report] [Component] el-input autosize problem in el-table

### ISSUE THREAD

**Issue by wahsggx** [element-plus/element-plus#6825]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'`
- Build Tool: `Webpack`

### Related Component

- `el-input`
- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2PlxuXHRcdDxwPlxuXHRcdFx05LiA44CB6KGo5qC85Lit6K6+572udGV4dGFyZWEgYXV0b3NpemXlsZ7mgKfvvIwg5Yid5aeL5YyW5paH5pys6auY5bqm5byC5bi4XG5cdFx0PC9wPlxuXHRcdDxlbC10YWJsZSA6ZGF0YT1cImxpc3RcIj5cblx0XHRcdDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCLluo/lj7dcIiAvPlxuXHRcdFx0PGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIuWkh+azqFwiPlxuXHRcdFx0XHQ8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlx0XHRcdFx0XHRcblx0XHRcdFx0XHRcdDxlbC1pbnB1dFxuXHRcdFx0XHRcdFx0XHR2LW1vZGVsPVwic2NvcGUucm93LnJlbWFya1wiXG5cdFx0XHRcdFx0XHRcdGF1dG9zaXplXG5cdFx0XHRcdFx0XHRcdHR5cGU9XCJ0ZXh0YXJlYVwiXG5cdFx0XHRcdFx0XHRcdHBsYWNlaG9sZGVyPVwi6K+36L6T5YWlXCJcblx0XHRcdFx0XHRcdC8+XG5cdFx0XHRcdDwvdGVtcGxhdGU+XG5cdFx0XHQ8L2VsLXRhYmxlLWNvbHVtbj5cblx0XHQ8L2VsLXRhYmxlPlxuXHRcdDxwPuS6jOOAgemdnuihqOagvOS4reiuvue9rnRleHRhcmVhIGF1dG9zaXpl5bGe5oCn77yMIOWIneWni+WMluaWh+acrOmrmOW6puato+W4uDwvcD5cblx0XHQ8ZWwtaW5wdXRcblx0XHRcdHYtbW9kZWw9XCJyZW1hcmtcIlxuXHRcdFx0YXV0b3NpemVcblx0XHRcdHR5cGU9XCJ0ZXh0YXJlYVwiXG5cdFx0XHRwbGFjZWhvbGRlcj1cIuivt+i+k+WFpVwiXG5cdFx0Lz5cblx0PC9kaXY+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnN9IGZyb20gJ3Z1ZSdcbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuXHRsaXN0OiBbXG5cdFx0e1xuXHRcdFx0aWQ6IDEsXG5cdFx0XHRyZW1hcms6ICcnXG5cdFx0fSxcblx0XHR7XG5cdFx0XHRpZDogMixcblx0XHRcdHJlbWFyazogJ+WlveWlveWlveWlveWlveWlveWlveWlvSdcblx0XHR9XG5cdF0sXG5cdHJlbWFyazogJ+WlveWlveWlveWlveWlveWlveWlveWlvSdcbn0pXG5jb25zdCB7bGlzdCwgcmVtYXJrfSA9IHRvUmVmcyhzdGF0ZSk7XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. create a <el-table>;
2. create a arrayList used for table, eg: [{ remark: '123'},  {remark: ''}]
3. create a <el-table-column>, and in it,  create a <el-input>, and set `type`  textarea,  and set `autosize` effective
4. you can see,  the  height of textarea element is higher than its content when initialized;   when click and input, it become normal and filled with its content

### What is Expected?

 the height of textarea element is filled with its content when initialized

### What is actually happening?

1. the height of textarea element is higher than its content when initialized;
2. when click and input, it become normal and filled with its content

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/26195239/160080630-ce4699da-be62-4168-865c-d34ad1245883.png)

**Comment by chenxch** [comment]
You can read the document in detail. The default `rows` of `textarea` is `2`.
