### ISSUE TITLE
Feature suggestion: allow i18n to dynamically update locale

### ISSUE THREAD

**Issue by xiaogemm** [element-plus/element-plus#683]
当前初始引入：
```
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import locale from 'element-plus/lib/locale/lang/zh-cn'
createApp(App).use(ElementPlus, { locale })
```

当前动态切换语言：
我只能在本项目动态切换语言版本时，使用：
`createApp({}).use(ElementPlus, {locale: lang})`
去动态切换，这应该不是最好的处理方法

建议：
可否在use方法中兼容处理至：语言码入参即可动态加载内部语言包，且最好有缓存不会重复加载。例如：
```
import locale from 'element-plus/lib/locale'
locale.use('zh-TW');//即可动态切换至繁体中文
```
这样的使用方式，会更便捷。而且处理流程都在内部完成

应用场景是针对项目本身需要动态切换语言时，能动态的同步切换Element+的语言包

------------------------------
另外：/packages/locale/index.ts中
template(),t()两个方法中对option参数无类型申明
use()中 l 参数 无类型申明

**Comment by zazzaz** [comment]
Haven't tested it myself, but you may try this
<img width="725" alt="image" src="https://user-images.githubusercontent.com/10731096/100103008-5410d880-2e9f-11eb-8dcb-f907bc94bd52.png">


BTW, we will support vue-i18n@next after it's release, and change i18n will be much easier that time

**Comment by xiaogemm** [comment]
> Haven't tested it myself, but you may try this
> <img alt="image" width="725" src="https://user-images.githubusercontent.com/10731096/100103008-5410d880-2e9f-11eb-8dcb-f907bc94bd52.png">
> 
> BTW, we will support vue-i18n@next after it's release, and change i18n will be much easier that time

您图片中的方法，和我在上面说的类似。我之所以做以下处理，是因为我在main.ts中是完整引入的ElementPlus，而不是按需引入：
`createApp({}).use(ElementPlus, {locale: lang})` 
已经可以达到动态切换的目的


完整引入时，是同时设置一个默认的语言包：createApp(App).use(ElementPlus, { locale })
按需引入时，是先locale.use设置语言包，然后再app.component引入组件；

而我想要的功能是：当我在main.ts中完整引入后，可以在一个切换项目本身语言包的功能（比如一个toggleLang.vue组件）中同步的切换Element+的所有组件语言默认项

我因为嫌i18n在一个文件中配置一个语言所有的语言包资源麻烦，就没用它；使用的是根据自己使用习惯自己写的，用的顺手，小，可控……
`createApp({}).use(ElementPlus, {locale: lang})`
我只是觉得在其他地方这样达到动态切换的目的，不是最好的方式，才有此建议

哈哈，尴尬了。不过，如果使用i18n可以动态切换的话，我应该可以改造一下自己的以达到同样的效果。

所以，这里仅仅是建议。因为根据一个语言码(zh-CN)，就可以加载或切换至对应语言包，这应该是一种比较符合习惯的用法。就好比i18n。在初始化配置好了所有想要使用的语言包列表以后，使用：this.$i18n.locale=‘zh-CN’就可以切换至简体中文一样

实在不行请忽略。我觉得其他的功能正常稳定使用比这个更重要

**Comment by JeremyWuuuuu** [comment]
So there are 2 ways to manage that.
The 1st one is the most common one I believe which is adding the `language` variable to url, most enterprise use this way to switch between locations, but some of them manage doing this by deploy different servers.
The other way to do so is to keep a global provider as a reactive value, when it changes it causes the entire app to re-render, thus the locale gets updated.

IMHO, we should support both ways to get locale updated.

**Comment by JeremyWuuuuu** [comment]
But since `vue-i18n@next` is not fully stable so that we were not be able to support the functionalities, because as you can see we have making changes of our own APIs. As @zazzaz mentioned we have plan on supporting this but it's just not the right time to do so. No worries, once they are ready, we will be implementing the functionality ASAP.

**Comment by JeremyWuuuuu** [comment]
UPDATE:

vue-i18n is now in their RC stage, we will start to adapt their new functionalities. Track this in #1209 . Closing this. We will keep this tracked in #1209
