### ISSUE TITLE
[Bug Report] [Style] [message] 默认类型的消息，当设置grouping时，第二次及之后显示的消息样式与第一次不一样

### ISSUE THREAD

**Issue by 34205037** [element-plus/element-plus#6834]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `win 10`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIDpwbGFpbj1cInRydWVcIiBAY2xpY2s9XCJkZWZhdWx0TWVzc2FnZVwiPmRlZmF1bHQgbWVzc2FnZTwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIDpwbGFpbj1cInRydWVcIiBAY2xpY2s9XCJzdWNjZXNzTWVzc2FnZVwiPnN1Y2Nlc3MgbWVzc2FnZTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZGVmYXVsdE1lc3NhZ2UgPSAoKSA9PiB7XG4gIEVsTWVzc2FnZSh7XG4gICAgZ3JvdXBpbmc6IHRydWUsXG4gICAgc2hvd0Nsb3NlOiB0cnVlLFxuICAgIGR1cmF0aW9uOiAwLFxuICAgIG1lc3NhZ2U6ICdkZWZhdWx0IG1lc3NhZ2UuJ1xuICB9KVxufVxuXG5jb25zdCBzdWNjZXNzTWVzc2FnZSA9ICgpID0+IHtcbiAgRWxNZXNzYWdlKHtcbiAgICB0eXBlOiBcInN1Y2Nlc3NcIixcbiAgICBncm91cGluZzogdHJ1ZSxcbiAgICBzaG93Q2xvc2U6IHRydWUsXG4gICAgZHVyYXRpb246IDAsXG4gICAgbWVzc2FnZTogJ3N1Y2Nlc3MgbWVzc2FnZS4nXG4gIH0pXG59XG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### What is Expected?

一致的样式

### What is actually happening?

背景色不一致，并且icon消失

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Sorry, I didn't reproduce the scene you said. The background color is different because you set the type.

**Comment by 34205037** [comment]
普通消息按钮请点击两次以上....
success消息只是要说明其他类型的消息没有这个问题
