### ISSUE TITLE
[Bug Report] [Component] [button] el-button is invalid if you frequently click it.（在频繁点击下el-button 会失效）

### ISSUE THREAD

**Issue by zzh97** [element-plus/element-plus#6835]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/97.0.4692.71`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYSA9IHJlZigxKVxuY29uc3QgYiA9ICgpID0+IHtcbiAgYS52YWx1ZSsrXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2Pnt7YX19PC9kaXY+XG4gIDwhLS1hKysgd2hlbiBjbGljayBpdCBlYWNoIHRpbWUuLS0+XG4gIDwhLS3mr4/mrKHngrnlh7vlroPvvIzpg73kvJrop6blj5FhKystLT5cbiAgPHNwYW4gQGNsaWNrPVwiYlwiPmJ0bjE8L3NwYW4+XG4gIDwhLS1ob3dldmVyIGl0IGlzIGludmFsaWQgb2NjYXNpb25hbGx5IHdoZW4geW91IGNsaWNrIHRoaXMuLS0+XG4gIDwhLS3kvYbngrnlh7vov5nkuKrvvIzlsLHkuI3kuIDlrprkuoYtLT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHJvdW5kPlxuICAgIDxzcGFuIEBjbGljaz1cImJcIj5idG4yPC9zcGFuPlxuICA8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

First frequently click "btn1", and you will find "a++".
Second frequently click "btn2", and you maybe find that it is nothing happened.

先频繁地点击“btn1”，你会发现a每次都会+1。
再频繁地点击“btn2”，你会发现a有时会卡住。

```
<script setup lang="ts">
import { ref } from 'vue'

const a = ref(1)
const b = () => {
  a.value++
}
</script>

<template>
  <div>{{a}}</div>
  <!--a++ when click it each time.-->
  <!--每次点击它，都会触发a++-->
  <span @click="b">btn1</span>
  <!--however it is invalid occasionally when you click this.-->
  <!--但点击这个，就不一定了-->
  <el-button type="primary" round>
    <span @click="b">btn2</span>
  </el-button>
</template>
```

### What is Expected?

a++ when click "btn2" each time.
我希望每次点击“btn2”按钮时，都会触发a++

### What is actually happening?

it is invalid occasionally when you click "btn2".
然而点击“btn2”按钮时，经常会失效（不触发@click事件）

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Your click event is bound to the `span`, not written on the `el-button`. The `el-button` has `padding`, and of course it will not trigger when you click the mouse on the `padding`.

**Comment by huang-yf3160** [comment]
In the second button，You didn't click on the element that triggered the event，you can close this issue
