### ISSUE TITLE
[Bug Report] [Component] [tabs] [Vue warn]: Maximum recursive updates exceeded in component <ElTabs>.

### ISSUE THREAD

**Issue by YeKelvin** [element-plus/element-plus#6839]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Steps to reproduce

<el-tabs v-show="tabs.length > 0" v-model="activeTabNo" type="card" closable @tab-remove="handleTabRemove">
  <el-tab-pane v-for="tab in tabs" :key="tab.editorNo" :label="tab.editorName" :name="tab.editorNo" />
</el-tabs>

### What is Expected?

no error, no warning

### What is actually happening?

console prompt warning:
[Vue warn]: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by Nemonvgu** [comment]
<el-tabs v-model="activeName" @tab-click="handleTypeChange">
      <el-tab-pane name="2">
        <template #label>
          <span class="message_count_wrap"
            >notice
            <span class="message_count" v-if="shopNoticeCount">{{ shopNoticeCount }}</span>
          </span>
        </template>
      </el-tab-pane>
      <el-tab-pane name="1">
        <template #label>
          <span class="message_count_wrap"
            >dynamic
            <span class="message_count" v-if="productNoticeCount">{{ productNoticeCount }}</span>
          </span>
        </template>
      </el-tab-pane>
    </el-tabs>

use label slot will trigger the same warning

**Comment by Nemonvgu** [comment]
use label slot will trigger the same warning

**Comment by Sunshop** [comment]
> use label slot will trigger the same warning

I also have this problem

**Comment by mxp131011** [comment]
我也有相同问题，去掉#label后正常

**Comment by fineewen** [comment]
same problem

**Comment by saatana97** [comment]
me too.
俺也一样

**Comment by talksmallice** [comment]
遇到同样问题

**Comment by latolukasz** [comment]
Same here. If i add 
```vue
<template #label>
i am getting the same error
</template>

**Comment by HeftyKoo** [comment]
Should be fixed by #6871
