### ISSUE TITLE
[Bug Report] [Component] [backtop] el-backtop失效

### ISSUE THREAD

**Issue by hoowhoami** [element-plus/element-plus#6855]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-backtop`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDIwMHB4O1wiPlxuICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDEwMCU7XCI+XG4gICAgICBTY3JvbGwgZG93biB0byBzZWUgdGhlIGJvdHRvbS1yaWdodCBidXR0b24uXG4gICAgPC9kaXY+XG4gICAgPGVsLWJhY2t0b3AgOnZpc2liaWxpdHktaGVpZ2h0PVwiMjBcIi8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

开启控制台降低可视高度，滚动屏幕即可复现

### What is Expected?

出现el-backtop

### What is actually happening?

el-backtop并没有出现

### Additional comments

element-plus 2.1.4是正常的，2.1.5和2.1.6均不正常

**Comment by chenxch** [comment]
@nieyuyao You don't seem to have solved the problem.

**Comment by sxzz** [comment]
Fixed via #6848
