### ISSUE TITLE
[Bug Report] [Component] [All] 浏览器方式引入elmentplus 注册组件报错

### ISSUE THREAD

**Issue by danielmlc** [element-plus/element-plus#6859]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.6`
- Browser / OS: `edge  99.0.1150.46`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/danielmlc/vue3demo)

### Steps to reproduce

npm i
npm run dev

### What is Expected?

期望能正常引入elementplu，页面渲染出el-button等任何组件

### What is actually happening?

注册组件过程中报错。请查看控制台

### Additional comments

_(empty)_

**Comment by danielmlc** [comment]
您好，这个是问题复现的demo地址，麻烦了！ https://github.com/danielmlc/vue3demo

**Comment by danielmlc** [comment]
@emojiiii

**Comment by emojiiii** [comment]
明白你的意思了，请参考 [这里](https://www.cnblogs.com/moqiutao/p/13744854.html) @danielmlc
