### ISSUE TITLE
[Bug Report] [Docs] [tabs] element-plus 官网 组件文档点击tabs标签 后路由失效

### ISSUE THREAD

**Issue by 2512746832** [element-plus/element-plus#6860]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.6`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-tabs`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tabs.html)

### Steps to reproduce

打开官网 组件文档选择tabs

### What is Expected?

随着选项改变

### What is actually happening?

点击tabs后不会跳转

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
Dpulicate of #6863
