### ISSUE TITLE
[Bug Report] [All] 2.15版本可能存在内存溢出, 昨天发到线上, 有个页面一直卡死, 没发现原因, 不好复现不好给你们链接, 内部系统, 后面回滚element的版本修复了

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#6863]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.5`
- Browser / OS: `Chrome93`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/eku7j4g0/4/)

### Steps to reproduce

1

### What is Expected?

2

### What is actually happening?

3

### Additional comments

很抱歉, 上面太多必填, 麻烦忽略上面的链接以及没用的信息, 昨天我是从2.01升级到2.15, 就出现卡死状态了, 关键是本地还不会出现

**Comment by zhangchenna** [comment]
大家都一样 回退2.1.4吧

**Comment by a15218378694** [comment]
> 大家都一样 回退2.1.4吧

请问2.1.4有级联选择器的tooltip功能吗 ? 
![image](https://user-images.githubusercontent.com/29919045/160336550-f5fcc25a-6dca-48f9-b7c2-3d58adc8dae9.png)

**Comment by xiangqunXiao** [comment]
> 大家都一样 回退2.1.4吧

已知的问题吗？有其它 issue 可以了解相关背景吗？  @zhangchenna

**Comment by emojiiii** [comment]
能尽量提供一些你们用到的组件方便我们进行排查吗？感谢

**Comment by a15218378694** [comment]
> 大家都一样 回退2.1.4吧

你好, 请问你升级了吗

**Comment by a15218378694** [comment]
我想问下这个问题修复了吗 ? 打算升级, 顺便支持namespace

**Comment by emojiiii** [comment]
> 我想问下这个问题修复了吗 ? 打算升级, 顺便支持namespace

修复了

**Comment by a15218378694** [comment]
> namespace

namespaces配置无效, 已经升级到2.1.10版本

**Comment by a15218378694** [comment]
> > 我想问下这个问题修复了吗 ? 打算升级, 顺便支持namespace
> 
> 修复了

namespaces说明中, 需要配合namespace使用那句话, 不明白啥意思, 点进去看着也怪怪的, 希望可以写个demo在官网解答下, 谢谢
