### ISSUE TITLE
[Feature Request] [Enhancement] [input] el-input是否可以单独加上类似表单的验证的状态及错误信息提示

### ISSUE THREAD

**Issue by ckvv** [element-plus/element-plus#6864]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `input`

## Description

none

### Additional comments

_(empty)_

**Comment by zcmk123** [comment]
你直接跟el-form一起用不就行了？

**Comment by ckvv** [comment]
@zcmk123 
我只是需要用一个带有提示信息的输入框，现在必须跟el-form和el-form-item一起用感觉很臃肿

**Comment by zcmk123** [comment]
> @zcmk123 我只是需要用一个带有提示信息的输入框，现在必须跟el-form和el-form-item一起用感觉很臃肿

把校验功能放input里面就不臃肿了吗。。
今天把错误信息显示弄到input里面，明天万一又有人想在upload、select里面加那咋搞
