### ISSUE TITLE
[Bug Report] [Component] [table] el-table 设置 table-layout 为 "auto"，固定表头无效

### ISSUE THREAD

**Issue by Oen-Cpz** [element-plus/element-plus#6868]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.6`
- Browser / OS: `Firefox 98.0 Windows 10 x64`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGxpc3QgPSByZWYoXG4gIEFycmF5LmZyb20oeyBsZW5ndGg6IDQwIH0sIChfLCBpKSA9PiAoe1xuICAgIGE6IGksXG4gICAgYjogaSxcbiAgICBjOiBpLFxuICAgIGQ6IGksXG4gIH0pKVxuKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PHNwYW4+dGFibGUtbGF5b3V0PVwiZml4ZWRcIiwg5Zu65a6a6KGo5aS05q2j5bi4PC9zcGFuPlxuICA8ZWwtdGFibGUgdGFibGUtbGF5b3V0PVwiZml4ZWRcIiA6ZGF0YT1cImxpc3RcIiA6aGVpZ2h0PVwiMjUwXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYVwiIGxhYmVsPVwiYVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYlwiIGxhYmVsPVwiYlwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY1wiIGxhYmVsPVwiY1wiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZFwiIGxhYmVsPVwiZFwiIC8+XG4gIDwvZWwtdGFibGU+XG4gIFxuICA8c3Bhbj50YWJsZS1sYXlvdXQ9XCJhdXRvXCIsIOWbuuWumuihqOWktOaXoOaViDwvc3Bhbj5cbiAgPGVsLXRhYmxlIHRhYmxlLWxheW91dD1cImF1dG9cIiA6ZGF0YT1cImxpc3RcIiA6aGVpZ2h0PVwiMjUwXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYVwiIGxhYmVsPVwiYVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYlwiIGxhYmVsPVwiYlwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiY1wiIGxhYmVsPVwiY1wiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZFwiIGxhYmVsPVwiZFwiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

设置`el-table`的`table-layout`属性为`auto`, 设置`height`属性

### What is Expected?

和`fixed`一样，固定表头

### What is actually happening?

固定表头无效

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
auto不支持固定表头
