### ISSUE TITLE
[Feature Request] [tabs] 《Tabs 标签页》当激活时颜色可以提供自定义设置

### ISSUE THREAD

**Issue by cumin-coder** [element-plus/element-plus#6869]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `tabs`

## Description

可以为 <el-tab-pane color="..."/> 提供一个 color 属性，这样的话我们在激活时，颜色可以自定义

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
直接修改css 就可以了

**Comment by biuabiu** [comment]
+1
