### ISSUE TITLE
[Bug Report] [All] 1.1.0-beta.24版本安装不全

### ISSUE THREAD

**Issue by Tiramisupxl** [element-plus/element-plus#6879]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `1.1.0-beta.14`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

使用yarn安装element-plus@1.1.0-beta.24
安装的包缺失：
只有文件夹，没有package.json文件

### What is Expected?

安装正常

### What is actually happening?

包缺失

### Additional comments

_(empty)_

![企业微信截图_16484532266699](https://user-images.githubusercontent.com/13674347/160518018-c2309af5-803c-40bc-9628-a87055407faa.png)

**Comment by iamkun** [comment]
Please install the latest version `2.1.7` instead of the beta release

**Comment by GizmoOAO** [comment]
@iamkun Please deprecated this version.
