### ISSUE TITLE
[Bug Report] [Component] [input] el-input show-word-limit无效

### ISSUE THREAD

**Issue by lin-code-world** [element-plus/element-plus#6882]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome/99.0.4844.84`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgaW5wdXRWYWwgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuXHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0VmFsXCJcbiAgICAgICAgICBzaG93LXdvcmQtbGltaXRcbiAgICAgICAgICB0eXBlPVwidGV4dGFyZWFcIlxuICAgICAgICAgIDphdXRvc2l6ZT1cInsgbWluUm93czogMiB9XCJcbiAgICAgICAgICByZXNpemU9XCJub25lXCJcbiAgICAgICAgICBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeiHs+WwkTTkuKrlrZfnrKZcIj48L2VsLWlucHV0PlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

	<el-input v-model="inputVal"
          show-word-limit
          type="textarea"
          :autosize="{ minRows: 2 }"
          resize="none"
          placeholder="请输入至少4个字符"/>

### What is Expected?

文本域右下角出现字数统计

### What is actually happening?

文本域右下角没有出现字数统计

### Additional comments

_(empty)_

**Comment by btea** [comment]
You should set `maxlength`
