### ISSUE TITLE
国际化：ts中引入出错

### ISSUE THREAD

**Issue by zzs89117920** [element-plus/element-plus#689]
import locale from 'element-plus/lib/locale/lang/zh-cn'
在1.0,1-alpha.14时可以正常引入，1.0.1-alpah.21出错

![image](https://user-images.githubusercontent.com/5515847/100180280-c5d63a00-2f12-11eb-8751-eb7291568013.png)

**Comment by JeremyWuuuuu** [comment]
Hey, this is not a functional error, it's typing error, we are planning on fixing it in the next release. The functionality remains the same. You can just ignore the error reported by type checker, in this case, if you wish to compile your code without error, you might need to suppress compiler from being complaining about this.

**Comment by JeremyWuuuuu** [comment]
Closing this due to #685

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.23
