### ISSUE TITLE
[Bug Report] [Component] [config-provider] el-config-provider的size提供默认值default会有warn警告，之前2.1.4版本无此问题

### ISSUE THREAD

**Issue by RexSheng** [element-plus/element-plus#6897]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1jb25maWctcHJvdmlkZXIgOnNpemU9XCInZGVmYXVsdCdcIiA+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cblxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICAgICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

控制台console提示
[Vue warn]: Invalid prop: validation failed for prop "size". Expected one of ["large", "", "small"], got value "default". 
  at <ElConfigProvider size="default" zIndex=3000 locale= Object > 
  at <App>

### What is Expected?

无warn

### What is actually happening?

有warn

### Additional comments

_(empty)_

**Comment by JeremyWuuuuu** [comment]
@RexSheng `default` means by default you don't have to pass it as parameter, to solve your issue, simply remove the `size="default"` statement. You can also save some code. ;)
