### ISSUE TITLE
[Bug Report] [Component] [checkbox-group, checkbox] Checkbox多选框组的lable为自定义对象时出错

### ISSUE THREAD

**Issue by 490626721** [element-plus/element-plus#6901]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-checkbox-group`
- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5jb25zdCBwYWdlRGF0YSA9IHJlYWN0aXZlKHtcbiAgcm9sZUxpc3Q6IFtdLFxuICBhdXRoTGlzdDogW3tcImlkXCI6MSxcIm1faWRcIjpcImJyZ2djZmphanQxdnE1ZWNpZGF0aG1uZmgyXCIsXCJzb3J0XCI6MTcxNzcyMTE0MzQxMjg4LFwidGl0bGVcIjpcIuS5neaXj+S7t+mVv+WGm+eul+ivtOWFi+mHjeS6pOWchuWxgOWinuenkeaXtui9rOmbhuOAglwiLFwicm91dGVyXCI6XCIvYWRtaW4vdGVzdFwiLFwiYWN0aW9uXCI6W1wiR0VUXCIsXCJQT1NUXCJdfSx7XCJpZFwiOjMsXCJtX2lkXCI6XCJ1cWczZnRhbGQ1bDVtb29udmNhZW9lMXNmMFwiLFwic29ydFwiOjEsXCJ0aXRsZVwiOlwi5rWL6K+V6Lev55SxXCIsXCJyb3V0ZXJcIjpcIi9hZG1pbi90ZXN0MlwiLFwiYWN0aW9uXCI6W1wiUE9TVFwiLFwiR0VUXCIsXCJERUxFVEVcIixcIlBVVFwiXX1dXG59KVxuY29uc3QgYWRkRm9ybSA9IHJlYWN0aXZlKHtcbiAgICBzb3J0OiAwLFxuICAgIHRpdGxlOiAnJyxcbiAgICBhdXRoOiBbXVxufSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1jaGVja2JveC1ncm91cCB2LW1vZGVsPVwiYWRkRm9ybS5hdXRoXCIgY2xhc3M9XCJhdXRoLWxpc3RcIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiYXV0aC1pdGVtXCIgdi1mb3I9XCJpdGVtIGluIHBhZ2VEYXRhLmF1dGhMaXN0XCIgOmtleT1cIml0ZW0ubV9pZFwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cInRpdGxlXCI+e3tpdGVtLnRpdGxlfX06PC9kaXY+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiYWN0aW9uLWxpc3RcIj5cbiAgICAgICAgICAgICAgPGVsLWNoZWNrYm94IGNsYXNzPVwiYWN0aW9uLWl0ZW1cIiB2LWZvcj1cIihjaGlsZCxpbmRleCkgaW4gaXRlbS5hY3Rpb25cIiA6a2V5PVwiaW5kZXhcIiA6bGFiZWw9XCJ7IHJvdXRlcjogaXRlbS5yb3V0ZXIsIGFjdGlvbjogY2hpbGQgfVwiPnt7Y2hpbGR9fTwvZWwtY2hlY2tib3g+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9lbC1jaGVja2JveC1ncm91cD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4gIC5hdXRoLWxpc3QgLmF1dGgtaXRlbXtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIGZsZXgtd3JhcDogbm93cmFwO1xuICBmb250LXNpemU6IDE0cHg7XG59XG4uYXV0aC1saXN0IC5hdXRoLWl0ZW0gLmFjdGlvbi1saXN0e1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgZmxleC13cmFwOiBub3dyYXA7XG4gIG1hcmdpbi1sZWZ0OiAyMHB4O1xufVxuLmF1dGgtbGlzdCAuYXV0aC1pdGVtIC5hY3Rpb24tbGlzdCAuYWN0aW9uLWl0ZW17XG4gIG1hcmdpbjogMCAxMHB4O1xuICBjdXJzb3I6IHBvaW50ZXI7XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1.点击相应的项，能在将数据正确的存入目标数组
2.点击checkbox后能正确的响应选中和未选中UI

### What is Expected?

1.点击相应的项，能在将数据正确的存入目标数组
2.点击checkbox后能正确的响应选中和未选中UI

### What is actually happening?

1.点击相应的项，有的对象存入目标数组中是object有的是Reactive
2.点击checkbox后无法显示已选中UI

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
![image](https://user-images.githubusercontent.com/10278227/160766031-e9584a85-ceeb-4aad-b6cc-cfa03238698d.png)
你要事先组装好数据，在template里inline写object，下次update的时候不会是同一个引用对象

**Comment by 490626721** [comment]
> ![image](https://user-images.githubusercontent.com/10278227/160766031-e9584a85-ceeb-4aad-b6cc-cfa03238698d.png) 你要事先组装好数据，在template里inline写object，下次update的时候不会是同一个引用对象
已解决，感谢

**Comment by 490626721** [comment]
现在又遇到新问题了，数据回显有问题

**Comment by 490626721** [comment]
又出现新问题了，现在无法回显已选择项，不知道是不是我代码问题，请帮忙看看，谢谢拉
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG4vLyDmiYDmnInop4TliJnliJfooahcbmNvbnN0IHBhZ2VEYXRhID0gcmVhY3RpdmUoe1xuICAvLyDmiYDmnInop4TliJnliJfooahcbiAgYXV0aExpc3Q6IFt7XCJpZFwiOjEsXCJtX2lkXCI6XCJicmdnY2ZqYWp0MXZxNWVjaWRhdGhtbmZoMlwiLFwic29ydFwiOjE3MTc3MjExNDM0MTI4OCxcInRpdGxlXCI6XCLkuZ3ml4/ku7fplb/lhpvnrpfor7TlhYvph43kuqTlnIblsYDlop7np5Hml7bovazpm4bjgIJcIixcInJvdXRlclwiOlwiL2FkbWluL3Rlc3RcIixcImFjdGlvblwiOltcIkdFVFwiLFwiUE9TVFwiXX0se1wiaWRcIjozLFwibV9pZFwiOlwidXFnM2Z0YWxkNWw1bW9vbnZjYWVvZTFzZjBcIixcInNvcnRcIjoxLFwidGl0bGVcIjpcIua1i+ivlei3r+eUsVwiLFwicm91dGVyXCI6XCIvYWRtaW4vdGVzdDJcIixcImFjdGlvblwiOltcIlBPU1RcIixcIkdFVFwiLFwiREVMRVRFXCIsXCJQVVRcIl19XSxcbiAgLy8g6YeN5paw57uE6KOF55qE5pWw5o2uXG4gIGFjdGlvbkxpc3Q6IFt7XCJhY3Rpb25cIjpcIkdFVFwiLFwicm91dGVyXCI6XCIvYWRtaW4vdGVzdFwifSx7XCJhY3Rpb25cIjpcIlBPU1RcIixcInJvdXRlclwiOlwiL2FkbWluL3Rlc3RcIn0se1wiYWN0aW9uXCI6XCJQT1NUXCIsXCJyb3V0ZXJcIjpcIi9hZG1pbi90ZXN0MlwifSx7XCJhY3Rpb25cIjpcIkdFVFwiLFwicm91dGVyXCI6XCIvYWRtaW4vdGVzdDJcIn0se1wiYWN0aW9uXCI6XCJERUxFVEVcIixcInJvdXRlclwiOlwiL2FkbWluL3Rlc3QyXCJ9LHtcImFjdGlvblwiOlwiUFVUXCIsXCJyb3V0ZXJcIjpcIi9hZG1pbi90ZXN0MlwifV1cbn0pXG5cbi8vIOe8lui+keihqOWNlVxuY29uc3QgZWRpdEZvcm0gPSByZWFjdGl2ZSh7XG4gIGF1dGg6IFt7XCJhY3Rpb25cIjpcIlBPU1RcIixcInJvdXRlclwiOlwiL2FkbWluL3Rlc3QyXCJ9XSBcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC1jaGVja2JveC1ncm91cCB2LW1vZGVsPVwiZWRpdEZvcm0uYXV0aFwiIGNsYXNzPVwiYXV0aC1saXN0XCI+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cImF1dGgtaXRlbVwiIHYtZm9yPVwiaXRlbSBpbiBwYWdlRGF0YS5hdXRoTGlzdFwiIDprZXk9XCJpdGVtLm1faWRcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJ0aXRsZVwiPnt7aXRlbS50aXRsZX19OjwvZGl2PlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImFjdGlvbi1saXN0XCI+XG4gICAgICAgICAgICAgIDx0ZW1wbGF0ZSB2LWZvcj1cIihjaGlsZCxpbmRleCkgaW4gcGFnZURhdGEuYWN0aW9uTGlzdFwiIDprZXk9XCJpbmRleFwiPlxuICAgICAgICAgICAgICAgIDxlbC1jaGVja2JveCBjbGFzcz1cImFjdGlvbi1pdGVtXCIgOmxhYmVsPVwiY2hpbGRcIiB2LWlmPVwiY2hpbGQucm91dGVyID09PSBpdGVtLnJvdXRlclwiPnt7Y2hpbGQuYWN0aW9ufX08L2VsLWNoZWNrYm94PlxuICAgICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uYXV0aC1saXN0e1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICBhbGlnbi1pdGVtczogZmxleC1zdGFydDtcbiAganVzdGlmeS1jb250ZW50OiBmbGV4LXN0YXJ0O1xufVxuLmF1dGgtbGlzdCAuYXV0aC1pdGVte1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgZmxleC13cmFwOiBub3dyYXA7XG4gIGZvbnQtc2l6ZTogMTRweDtcbn1cbi5hdXRoLWxpc3QgLmF1dGgtaXRlbSAudGl0bGV7fVxuLmF1dGgtbGlzdCAuYXV0aC1pdGVtIC5hY3Rpb24tbGlzdHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIGZsZXgtd3JhcDogbm93cmFwO1xuICBtYXJnaW4tbGVmdDogMjBweDtcbn1cbi5hdXRoLWxpc3QgLmF1dGgtaXRlbSAuYWN0aW9uLWxpc3QgLmFjdGlvbi1pdGVte1xuICBtYXJnaW46IDAgMTBweDtcbiAgY3Vyc29yOiBwb2ludGVyO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)
