### ISSUE TITLE
[Bug Report] [Style] el-table 表格内 嵌套 el-image 预览大图时导致页面显示出现问题

### ISSUE THREAD

**Issue by QMZhao** [element-plus/element-plus#6904]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Google Chrome 99.0.4844.84 / mac OS 12.3`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cblx0aW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuICBpbnRlcmZhY2UgVXNlciB7XG4gICAgZGF0ZTogc3RyaW5nXG4gICAgbmFtZTogc3RyaW5nXG4gICAgYWRkcmVzczogc3RyaW5nXG4gIH1cblxuICBjb25zdCBoYW5kbGVFZGl0ID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICAgIGNvbnNvbGUubG9nKGluZGV4LCByb3cpXG4gIH1cbiAgY29uc3QgaGFuZGxlRGVsZXRlID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICAgIGNvbnNvbGUubG9nKGluZGV4LCByb3cpXG4gIH1cblxuICBjb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAgICB7XG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gICAge1xuICAgICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB9LFxuICAgIHtcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgfSxcbiAgICB7XG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gIF1cblxuICBjb25zdCB1cmwgPVxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnXG4gIGNvbnN0IHNyY0xpc3QgPSBbXG4gICAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzEvMzQvMTlhYTk4YjFmY2IyNzgxYzRmYmEzM2Q4NTA1NDlqcGVnLmpwZWcnLFxuICAgICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMC82Zi9lMzVmZjM3NTgxMmU2YjAwMjBiNmI0ZThmOTU4M2pwZWcuanBlZycsXG4gICAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2QvZTYvYzRkOTNhMzgwNWIzY2UzZjMyM2Y3OTc0ZTZmNzhqcGVnLmpwZWcnLFxuICAgICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy8yOC9iYmY4OTNmNzkyZjAzYTU0NDA4YjNiN2E3ZWJmMGpwZWcuanBlZycsXG4gICAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbiAgXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBhbGlnbi1pdGVtczogY2VudGVyXCI+XG4gICAgICAgICAgPGVsLWltYWdlXG4gICAgICAgICAgICBzdHlsZT1cIndpZHRoOiAxMDBweDsgaGVpZ2h0OiAxMDBweFwiXG4gICAgICAgICAgICA6c3JjPVwidXJsXCJcbiAgICAgICAgICAgIDpwcmV2aWV3LXNyYy1saXN0PVwic3JjTGlzdFwiXG4gICAgICAgICAgICA6aW5pdGlhbC1pbmRleD1cIjRcIlxuICAgICAgICAgICAgZml0PVwiY292ZXJcIlxuICAgICAgICAgIC8+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtcG9wb3ZlciBlZmZlY3Q9XCJsaWdodFwiIHRyaWdnZXI9XCJob3ZlclwiIHBsYWNlbWVudD1cInRvcFwiIHdpZHRoPVwiYXV0b1wiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgICAgIDxkaXY+bmFtZToge3sgc2NvcGUucm93Lm5hbWUgfX08L2Rpdj5cbiAgICAgICAgICAgIDxkaXY+YWRkcmVzczoge3sgc2NvcGUucm93LmFkZHJlc3MgfX08L2Rpdj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICAgICAgPGVsLXRhZz57eyBzY29wZS5yb3cubmFtZSB9fTwvZWwtdGFnPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDwvZWwtcG9wb3Zlcj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk9wZXJhdGlvbnNcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiaGFuZGxlRWRpdChzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgID5FZGl0PC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICB0eXBlPVwiZGFuZ2VyXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVEZWxldGUoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RGVsZXRlPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwiQ29tcC52dWUiOiIifQ==)

### Steps to reproduce

如题，在el-table-column内插入el-image组件，在点击图片预览时出现预览的图片和表格样式重叠的情况

### What is Expected?

正确展示预览图样式

### What is actually happening?

页面表格和图片样式重叠

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
See #6734

**Comment by 34205037** [comment]
```
preview-teleported
```
