### ISSUE TITLE
[Bug Report] [TypeScript] [All] Update to latest version NPM

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#6910]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.27`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IHsgZ2VuRmlsZUlkIH0gZnJvbSAnZWxlbWVudC1wbHVzJztcbmltcG9ydCB0eXBlIHsgVXBsb2FkSW5zdGFuY2UsIFVwbG9hZFByb3BzLCBVcGxvYWRSYXdGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJztcbiAgXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWljb24+PFVzZXIgLz48L2VsLWljb24+XG5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

When I import:
import { genFileId } from 'element-plus';
import type { UploadInstance, UploadProps, UploadRawFile } from 'element-plus';

I gives me an error: Module '"element-plus"' has no exported member 'genFileId'. Did you mean to use 'import genFileId from "element-plus"' instead?

### What is Expected?

Should work

### What is actually happening?

No exported member

### Additional comments

_(empty)_

**Comment by Red-xiaoshami** [comment]
v2.1.9 same problem.

**Comment by sxzz** [comment]
Try latest version now.

**Comment by sxzz** [comment]
Can't reproduce, please provide a minimum reproduction link.
