### ISSUE TITLE
[Bug Report] [Style] [input] el-input's text content is obscured by span.el-input__suffix when set show-word-limit

### ISSUE THREAD

**Issue by lmlife2016** [element-plus/element-plus#6911]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome 99.0.4844.84 / macOs 12.2.1`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCd0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dHRleHR0ZXh0dGV4dCcpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICA6c2hvdy13b3JkLWxpbWl0PVwidHJ1ZVwiXG4gICAgOm1pbmxlbmd0aD1cIjJcIlxuICAgIDptYXhsZW5ndGg9XCIxMjgwXCJcblx0XHQ6bW9kZWwtdmFsdWU9XCJtc2dcIlxuICAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

1. set show-word-limit and maxlength to el-input
2. set el-input's text content longer than'el-input' width
```vue
<script setup lang="ts">
import { ref } from 'vue'

const msg = ref('texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext')
</script>

<template>
  <el-input
    :show-word-limit="true"
    :maxlength="1280"
    :model-value="msg"
  />
</template>
```

### What is Expected?

el-input's text content is not obscured by span.el-input__suffix

### What is actually happening?

el-input's text content is obscured by span.el-input__suffix

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
I think this issue is fixed by this pr https://github.com/element-plus/element-plus/pull/7179
