### ISSUE TITLE
[Bug Report] [Component] [upload] Bug on Upload components of Element-plus on version 2.14.7

### ISSUE THREAD

**Issue by GuessWhoIAm-MyGithub** [element-plus/element-plus#6917]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome and Edge /windows`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgICAgPGVsLXVwbG9hZFxuICAgICAgY2xhc3M9XCJ1cGxvYWRcIlxuICAgICAgYWN0aW9uPVwiJzgwODBcIlxuICAgICAgOmF1dG8tdXBsb2FkPVwiZmFsc2VcIlxuICAgICBcbiAgICAgIDpvbi1jaGFuZ2U9XCJ0aGlzLnNheUhlbGxvXCJcblxuICAgID5cbiAgICAgIDwhLS0gPGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS11cGxvYWRcIj48dXBsb2FkLWZpbGxlZCAvPjwvZWwtaWNvbj5cbiAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RleHRcIiB3aWR0aD1cIjEwMCVcIj5cbiAgICAgICAg5ouW5YWl5paH5Lu25oiWPGVtPueCueWHu+atpOWkhOS4iuS8oDwvZW0+XG4gICAgICAgIDxoNCBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCIgc3R5bGU9XCJ0ZXh0LWFsaWduOiBjZW50ZXJcIj5cbiAgICAgICAgICAuQ3N25paH5Lu25LiU5LiN5aSn5LqOMjBNQlxuICAgICAgICA8L2g0PlxuICAgICAgPC9kaXY+IC0tPlxuICAgICAgPGVsLWJ1dHRvbj5VcGxvYWQ8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLXVwbG9hZD5cbiAgICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG5tZXRob2RzOiB7XG4gIHNheUhlbGxvKGZpbGUsZmlsZWxpc3Qpe1xuICAgIGNvbnNvbGUubG9nKGZpbGUsZmlsZWxpc3QpO1xuICAgIGNvbnNvbGUubG9nKCdIZWxsbycpO1xuICB9XG59XG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+PC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

simply choose a file to upload

### What is Expected?

on-change hook be called once 

### What is actually happening?

the hook is called twice 

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
fix #6885
