### ISSUE TITLE
Select 组件和 Option 组件打包后代码重复及 inject SelectToken 错误

### ISSUE THREAD

**Issue by yokots** [element-plus/element-plus#693]
lib 目录下的 Select 组件已有 Option 组件的代码，但为调用 app.component(script.name, script) 注册 Option 组件。如果单独引入 Option 组件，一个问题是会造成代码的重复引入，一个是 Option 和 Select 组件（编译后的）分别 inject 的是不同的 symbol，运行有错。

**Comment by JeremyWuuuuu** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz

**Comment by JeremyWuuuuu** [comment]
@yokots , we need some code for reproduce this bug. Could you help providing that?

**Comment by yokots** [comment]
![lib-el-select](https://user-images.githubusercontent.com/24869428/100305122-56784d00-2fdb-11eb-8bfc-4de4fda2348f.png)
![lib-el-option](https://user-images.githubusercontent.com/24869428/100305142-5f691e80-2fdb-11eb-824f-d81cc4f07d52.jpg)
从代码截图里可以清楚的看出，el-select 生成的代码包含了 el-option 的代码，在单独引入 select 组件时，由于在 install 时未注册 option，会警告找不到 el-option 组件，如果一起引入 select 和 option ，由于 select 和 option 使用不同的 Injection Token 来注入 select，则会导致报错。

**Comment by JeremyWuuuuu** [comment]
True, this is definitely a bug that we need to fix, it did not throw any error before is because we did not use `Symbol` on those token. Me and @zazzaz will make sure that it's fixed.

**Comment by JeremyWuuuuu** [comment]
Fixed in #709

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.23
