### ISSUE TITLE
[Feature Request] [upload] 2.1.7版本上传change事件触发两次

### ISSUE THREAD

**Issue by li1988** [element-plus/element-plus#6932]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `upload`

## Description

vue版本是3.2.31，element plus用的是2.1.5,上传时change事件触发两次并且会把回调的第二个参数uploadFiles清空，element plus版本降级之后上传组件的change事件就触发一次,并且不会清空第二个参数。看下面的console
### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Is it convenient to use `playground` to submit a `demo`?

**Comment by chenxch** [comment]
Did you test this demo?

**Comment by li1988** [comment]
> 你测试过这个演示吗？

嗯 是的

**Comment by li1988** [comment]
> 你测试过这个示例吗？

这就是官网的例子change触发两次并且清空回调的第二个参数

**Comment by chenxch** [comment]
The `on-change` event itself is fired once when it is added, and once when the result is returned.

**Comment by chenxch** [comment]
Please look forward to the next version. #6918
