### ISSUE TITLE
[Bug Report] [Component] [loading] Failed to import v-loading in main.js

### ISSUE THREAD

**Issue by Linhongbin-1111** [element-plus/element-plus#6940]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `chrome 99`
- Build Tool: `Vue CLI`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbG9hZGluZyA9IHJlZih0cnVlKVxuc2V0VGltZW91dCgoKSA9PiB7XG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxufSwgMjAwMClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgdi1sb2FkaW5nPVwibG9hZGluZ1wiPlxuICAgIHRlc3Qgdi1sb2FkaW5nXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319IiwibWFpbi5qcyI6ImltcG9ydCB7IGNyZWF0ZUFwcCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuXG5jcmVhdGVBcHAoQXBwKS5kaXJlY3RpdmUoJ2xvYWRpbmcnLCBFbExvYWRpbmcuZGlyZWN0aXZlKS5tb3VudCgnI2FwcCcpIn0=)

### Steps to reproduce

Using the v-loading directive on any dom node has no effect.

### What is Expected?

The v-loading directive implements the loading effect

### What is actually happening?

No effect, no error

### Additional comments

_(empty)_

**Comment by btea** [comment]
The loading effect seems to be normal

https://user-images.githubusercontent.com/24516654/161360628-65aca718-99f7-4597-ade7-058c03b796ac.mp4

**Comment by Linhongbin-1111** [comment]
It's my problem, thanks for your reply.
