### ISSUE TITLE
[Bug Report] [Style] [dialog] 使用:deep()修改dialog默认样式不生效

### ISSUE THREAD

**Issue by 490626721** [element-plus/element-plus#6942]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYWRkLW5ldy1idG5cIiBAY2xpY2s9XCJvcGVuRmlsZURpYWxvZ1wiPlxuICAgIDxlbC1pY29uPjxwbHVzLz48L2VsLWljb24+XG4gIDwvZGl2PlxuICA8IS0tIOaWh+S7tumAieaLqeW8ueWHuueqlyAtLT5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZmlsZURpYWxvZ1Zpc2libGVcIiB0aXRsZT1cIuaWh+S7tumAieaLqeWZqFwiIHdpZHRoPVwiNzAwcHhcIiA6YmVmb3JlLWNsb3NlPVwiZmlsZURpYWxvZ0Nsb3NlXCIgY3VzdG9tLWNsYXNzPVwiZmlsZS1kaWFsb2dcIj5cbiAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgPGRpdiBjbGFzcz1cImRpYWxvZy1oZWFkZXJcIj7mlofku7bpgInmi6nlmag8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxkaXYgY2xhc3M9XCJmaWxlLWRpYWxvZy1ib2R5XCI+XG4gICAgIFx0MjIyMjIyMjIyMlxuICAgIDwvZGl2PlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQge0VsTWVzc2FnZUJveH0gZnJvbSBcImVsZW1lbnQtcGx1c1wiO1xuY29uc3QgZmlsZURpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBmaWxlRGlhbG9nQ2xvc2UgPSAoZG9uZTogKCkgPT4gdm9pZCkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybSgnQXJlIHlvdSBzdXJlIHRvIGNsb3NlIHRoaXMgZGlhbG9nPycpXG4gICAgICAudGhlbigoKSA9PiB7XG4gICAgICAgIGRvbmUoKVxuICAgICAgfSlcbiAgICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgICB9KVxufVxuXG4vLyDngrnlh7vmt7vliqDmlofku7bmjInpkq5cbmNvbnN0IG9wZW5GaWxlRGlhbG9nID0gKCkgPT4ge1xuICBmaWxlRGlhbG9nVmlzaWJsZS52YWx1ZSA9IHRydWVcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmFkZC1uZXctYnRue1xuICB3aWR0aDogMTAwcHg7XG4gIGhlaWdodDogMTAwcHg7XG4gIGJvcmRlcjogMXB4IGRhc2hlZCAjZDlkOWQ5O1xuICBmb250LXNpemU6IDIwcHg7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBib3JkZXItcmFkaXVzOiA2cHg7XG4gIG1hcmdpbi1sZWZ0OiA2cHg7XG59XG4uYWRkLW5ldy1idG46aG92ZXJ7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgYm9yZGVyOiAxcHggZGFzaGVkICM0MDlFRkY7XG4gIGNvbG9yOiAjNDA5RUZGO1xufVxuICAvKioqKiog6L+Z6YeM55qE5LiN55Sf5pWIICoqKioqL1xuOmRlZXAoLmVsLWRpYWxvZ19faGVhZGVyKXtcbiAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkICNlOGU4ZTg7XG4gIG1hcmdpbi1yaWdodDogMDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

无

### What is Expected?

通过
:deep(.el-dialog__header){
  border-bottom: 1px solid #e8e8e8;
  margin-right: 0;
}
能修改默认dialog的样式

### What is actually happening?

样式无任何更改

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
你可以定义一个根元素`div`, 类名为 `xxx`,然后这样写：`.xxx :deep(.el-dialog__header)`
