### ISSUE TITLE
[Bug Report] [Build] On-demand Import and build, ts error: "Cannot find name" caused by auto import

### ISSUE THREAD

**Issue by YornQiu** [element-plus/element-plus#6947]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome 98`
- Build Tool: `Vite`

### Related Component

- `el-message-box`
- `el-message`
- `el-notification`

### Reproduction Link

[Link]( Cannot reproduct On-demand Import in playground)

### Steps to reproduce

1. On-demand import components with unplugin-auto-import and unplugin-vue-components just like the guide on your officail site
2. Using ElMessage in Page A.
3. Using ElMessageBox in Page B.
4. Using ElNotification in Page C.
5. Run `yarn dev`, and open the 3 pages in order.
```
//page A
<script setup lang="ts">
ElMessage.info('message');
</script>

//page B
<script setup lang="ts">
ElMessageBox.alert('message', {});
</script>

//page C
<script setup lang="ts">
ElNotification.info('message');
</script>

```

the auto-imports.d.ts will auto add the 3 components this time.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/13913084/161194864-70888cf2-75f1-40cc-a00f-5835f9a30f1f.png">

6. Quit the terminal, reopen the project. Run `yarn dev`.
7. Then open the Page A only, don't enter the other 2 pages.
8. auto-imports.d.ts has been regenerated by unplugin-auto-import, but it only included ElMessage
<img width="608" alt="image" src="https://user-images.githubusercontent.com/13913084/161195552-e8439f13-67b2-41b5-9138-bd9a5c9224fb.png">

If you didn't notice the changes in file auto-imports.d.ts and commit to remote, the Auto-build on the server will fail with error: "Cannot find nane 'ElMessageBox'" and "Cannot find name 'ElNotification'".

This is my personal experience today.

### What is Expected?

auto-imports.d.ts includes ElMessage, ElMessageBox and ElNotification

### What is actually happening?

auto-imports only included ElMessage

### Additional comments

In fact, auto-imports.d.ts generated by unplugin-auto-import only includes the component you used in this developement, and the components you used in other pages which you didn't open will be ignored.

This situation only occurs when the component used in <script> instead of <template>.

Is there any way to ensure adding this 3 components in auto-imports.d.ts?Or other solutions?

Looking forward to your reply! Thx!

**Comment by YornQiu** [comment]
This issue doesn't effect local developement, but deployment only.

**Comment by sxzz** [comment]
Yeah, this is a issue, please go to the unplugin-vue-components repository for feedback.
