### ISSUE TITLE
[Bug Report] [Component] [table] el-table cell-style 报错

### ISSUE THREAD

**Issue by yangxisui** [element-plus/element-plus#6948]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.1.4`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUaW0nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUaW0nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9XVxuY29uc3QgY2VsbFN0eWxlID0gKHsgcm93LCBjb2x1bW5JbmRleCB9OiBhbnkpID0+IHtcbiAgaWYgKHJvdy5uYW1lID09PSAnVG9tJyAmJiBjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgIHJldHVybiAnZm9udC1zaXplOiAxMHB4J1xuICB9IGVsc2UgaWYgKHJvdy5uYW1lID09PSAnVGltJyAmJiBjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgIHJldHVybiAnZm9udC1zaXplOiAxMHB4J1xuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWljb24+PFVzZXIgLz48L2VsLWljb24+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIDpjZWxsLXN0eWxlPVwiY2VsbFN0eWxlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 使用cell-style属性，会报错

### What is Expected?

通过cell-style修改单元格的样式

### What is actually happening?

会报错

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
`cell-style`属性接收的是一个`CSSProperties`类型的 `object`, 返回值改为`{ fontSize: '10px' }`

**Comment by fuuhoo** [comment]
我也遇到了，解决了。返回的是对象，不应该是字符串
应该如下：
```
const cellStyle = ({ row, columnIndex }: any) => {
  if (row.name === 'Tom' && columnIndex === 1) {
    return {"font-size": "10px"}
  } else if (row.name === 'Tim' && columnIndex === 1) {
    return {"font-size": "10px"}
  }
}

```
