### ISSUE TITLE
Cannot import components on part in typescript projects

### ISSUE THREAD

**Issue by SLin0218** [element-plus/element-plus#695]
`element-plus@1.0.1-alpha.21`
`vue.3.0.2`

![image](https://user-images.githubusercontent.com/23139501/100209132-77419380-2f44-11eb-8451-f378dec75dd4.png)

If import with the El prefix, the declaration cannot be found. 
If don't use a prefix, can't find it in lib

![image](https://user-images.githubusercontent.com/23139501/100209517-f2a34500-2f44-11eb-89c1-aaacb86b800c.png)

export name is not prefix?

[iissues-627](https://github.com/element-plus/element-plus/issues/627)

**Comment by JeremyWuuuuu** [comment]
Duplicate with #689  #688 , will be fixed in the next release.

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.23

you can use
```
import { ElCol } from 'element-plus';
```
