### ISSUE TITLE
[Feature Request] [Enhancement] [scrollbar] ElScrollbar scroll speed settings for scrollbar methods

### ISSUE THREAD

**Issue by Winston-Guess** [element-plus/element-plus#6953]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `scrollbar`

## Description

ElScrollbar currently scrolls to the position set by setScrollTop/setScrollLeft immediately. It would be far less jarring to the user if it moved to the new position smoothly, equivalent to a easeInOut or similar transition.

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
we are already expose native scrollTo method #6663
