### ISSUE TITLE
[Feature Request] [Enhancement] Why not introduce element-plus globally in play/main.ts

### ISSUE THREAD

**Issue by josonho** [element-plus/element-plus#6955]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `N/A`

## Description

Why do I suggest introducing element-plus globally in play/main.ts:
1. When developing and debugging, you don't need to spend energy to introduce on demand
2. This is for development and debugging, don't worry about the impact of global introduction on performance
3. When introduced globally, we can directly copy the code of Element Plus Playground to play/app.vue, and then start running directly, which greatly improves development efficiency

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
We're using `unplugin-vue-components` in playground, it means we can use all components without importing.
