### ISSUE TITLE
[Feature Request] [Enhancement] [tabs] 是否考虑增加一个 tab-change 事件呢？

### ISSUE THREAD

**Issue by wjw-gavin** [element-plus/element-plus#6959]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `tabs`

## Description

个人建议哈，就我的使用来看，目前都是只用到了类似`tab-change`的事件，虽然`tab-click`能通过参数实例达到`tab-change`的效果，因此想问下我们是否会考虑增加一个`tab-change`的事件呢？

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
I don't think it's necessary, you can use `input` instead /cc @buqiyuan

**Comment by buqiyuan** [comment]
oh, i missed that, so should we rename the `input` to `tab-change`? @sxzz

**Comment by sxzz** [comment]
Just keep it as-is.

**Comment by wjw-gavin** [comment]
Sorry, I don't understand what you mean by `input`?

**Comment by buqiyuan** [comment]
> Sorry, I don't understand what you mean by `input`?

You can use `input` event temporarily, we may add `tab-change` later

**Comment by wjw-gavin** [comment]
Oh, I didn't know the `input` event until I read the source code. It was not mentioned in the doc... 

> > Sorry, I don't understand what you mean by `input`?
> 
> You can use `input` event temporarily, we may add `tab-change` later

**Comment by buqiyuan** [comment]
@wjw-gavin Since version [2.1.8](https://github.com/element-plus/element-plus/pull/6984), you can use `tab-change` event
