### ISSUE TITLE
[Bug Report] [TypeScript] [select-v2] [el-select-v2] some bug

### ISSUE THREAD

**Issue by MoConWu** [element-plus/element-plus#6960]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Windows10`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgICAgICAgICAgICAgdi1tb2RlbD1cInZhbHVlM1wiXG4gICAgICAgICAgICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4OyBtYXJnaW4tcmlnaHQ6IDE2cHg7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIlxuICAgICAgICAgICAgICAgIGFsbG93LWNyZWF0ZVxuICAgICAgICAgICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgICAgICAgICBtdWx0aXBsZVxuICAgICAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgICAgICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgICAgICAgICAgICAgQGNoYW5nZT1cIm9uX2NoYW5nZVwiXG4gICAgICAgICAgICAgICAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTMgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gcmVmKFtdKVxuY29uc3Qgb25fY2hhbmdlID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyhvcHRpb25zLnZhbHVlKTtcbiAgY29uc29sZS5sb2codmFsdWUzLnZhbHVlKTtcbiAgbmV4dFRpY2soKCkgPT4ge1xuICAgIG9wdGlvbnMudmFsdWUubGVuZ3RoID0gMDtcbiAgICB2YWx1ZTMudmFsdWUubGVuZ3RoID0gMDtcbiAgfSk7XG59XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

Create and select new items that are not included in select options.
But when clear the options, The old temporary option not clear.
how to clear temporary option ?

### What is Expected?

how to clear temporary option ?

### What is actually happening?

I can't clear the temporary option ?

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/33497338/161241523-0df51b15-1205-4d5a-9ffe-9a5bbf0a222f.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png)
What kind of business needs to trigger clearing here.

**Comment by MoConWu** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png) What kind of business needs to trigger clearing here.

It's only a test ok, I need clear the temporary option.

**Comment by josonho** [comment]
> > ![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png) What kind of business needs to trigger clearing here.
> 
> It's only a test ok, I need clear the temporary option.

> > ![图片](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png)什么样的业务需要在这里触发清算。
> 
> 这只是一个测试，我需要清除临时选项。



> > ![图片](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png)什么样的业务需要在这里触发清算。
> 
> 这只是一个测试，我需要清除临时选项。



> > ![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png) What kind of business needs to trigger clearing here.
> 
> It's only a test ok, I need clear the temporary option.



> > ![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png) What kind of business needs to trigger clearing here.
> 
> It's only a test ok, I need clear the temporary option.



> > ![image](https://user-images.githubusercontent.com/23251408/161321084-3069aef6-056a-4c71-b6d7-d5b4ebfe2ebc.png) What kind of business needs to trigger clearing here.
> 
> It's only a test ok, I need clear the temporary option.

你好，
因为目前通过allow-create创建的选项并没有存到options，所以你手动清空options是无效的．
另外，现在也没有监听value的清空， 从而触发options的清空的机制．
临时解决方案可以通过手动模拟clear按钮的点击，从而使value和options都清空．

**Comment by josonho** [comment]
你好，
因为目前通过allow-create创建的选项并没有存到options，所以你手动清空options是无效的．
另外，现在也没有监听value的清空， 从而触发options的清空的机制．
临时解决方案可以通过手动模拟clear按钮的点击，从而使value和options都清空．

**Comment by MoConWu** [comment]
> 你好， 因为目前通过allow-create创建的选项并没有存到options，所以你手动清空options是无效的． 另外，现在也没有监听value的清空， 从而触发options的清空的机制． 临时解决方案可以通过手动模拟clear按钮的点击，从而使value和options都清空．

谢谢你的提示，我发现了是不在v-model数据里的，但是现在可以清空了
`https://github.com/element-plus/element-plus/pull/6966`
