### ISSUE TITLE
[Bug Report] [Docs] [cascader] element puls的文档书写有错误，crowdin使用体验很差，修改难度大

### ISSUE THREAD

**Issue by PaulMing** [element-plus/element-plus#6961]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html)

### Steps to reproduce

文档

### What is Expected?

文档

### What is actually happening?

文档

### Additional comments

文档

<img width="812" alt="image" src="https://user-images.githubusercontent.com/40627394/161251523-6f70e0bc-107e-4b9f-8fdb-b0de545bd3d6.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/40627394/161251678-e4175ea3-572f-48f9-a836-10f84bdbc203.png">

**Comment by jasonren0403** [comment]
1. “最后更新”那个地方之前我曾经提过pr修了invalid date问题（#6714），但是看起来还是得修一下日期的问题，正在思考怎么解决这个问题
2. 你说的那个地方已经改掉了，等一下项目构建吧，顺便也欢迎各位参与到 [Element Plus 的 Crowdin 项目](https://crowdin.com/project/element-plus)中

**Comment by PaulMing** [comment]
@jasonren0403 为什么要使用Crowdin尼，有很多好用的工具呀

**Comment by sxzz** [comment]
比如说？
