### ISSUE TITLE
[Bug Report] [Component] [switch] The "el-switch" shakes when it switches to the right

### ISSUE THREAD

**Issue by HOWAREYOUIAMFINE** [element-plus/element-plus#6965]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: ` Microsoft Edge	99.0.1150.46 (正式版本) (64 位) `
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY2hlY2tlZCA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zd2l0Y2ggdi1tb2RlbD1cImNoZWNrZWRcIj48L2VsLXN3aXRjaD5cbiAgPGRpdj5cbiAgXHQ8ZWwtc3dpdGNoXG4gICAgICB2LW1vZGVsPVwiY2hlY2tlZFwiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgYWN0aXZlLXRleHQ9XCJPcGVuXCJcbiAgICAgIGluYWN0aXZlLXRleHQ9XCJDbG9zZVwiXG4gICAgLz5cbiAgPC9kaXY+XG4gIDxlbC1pbWFnZSBzcmM9XCJodHRwczovL3VwZmlsZTIuYXNxcWwuY29tL3VwZmlsZS9oZGltZy93bXRwL3dtdHAvMjAxNi0xLzI3LzE5MTg2c0FrYWNFc1NOMi5qcGdcIj48L2VsLWltYWdlPlxuICA8ZWwtaW1hZ2Ugc3JjPVwiaHR0cHM6Ly93d3cueWgzMS5jb20vdXBsb2FkZmlsZS9wenNtazgvMjAyMTAxMTgxMTMzMTI0MzgwLmpwZ1wiPjwvZWwtaW1hZ2U+XG4gIDxlbC1pbWFnZSBzcmM9XCJodHRwczovL3NjcGljLmNoaW5hei5uZXQvZmlsZXMvcGljL3BpYzkvMjAxODA0L2JwaWM2NTM2LmpwZ1wiPjwvZWwtaW1hZ2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIDpyb290IHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

With the simplest "el-switch", there will be a shaking problem when switching to the right

### What is Expected?

There is no shaking problem when switching to the right

### What is actually happening?

When switching to the right, there is a problem with shaking

### Additional comments

It is worth noting that this problem does not arise when "active-text" and "inactive-text" have values, and the same problem arises with the basic usage of the "Switch" component on the official documentation

<!-- 如果你需要插入截图，请在这粘贴。 --
![1648866477(1)](https://user-images.githubusercontent.com/58383049/161362220-5cc17dbd-4408-47bc-85be-79c48cf162df.jpg)
>

**Comment by btea** [comment]
It seems to be normal at the moment, I will close this issue, if you have any questions, please leave a message below.
