### ISSUE TITLE
[Feature Request] [New Component] [] 希望增加个treeSelect组件

### ISSUE THREAD

**Issue by github-ZH-cn** [element-plus/element-plus#6969]
Feature type: **`New Component`**

## Details

- New component name: `treeSelect`

## Description

希望组件库增加treeSelect组件,这个组件需求真的很大啊

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
强烈同意  其他组件库都有树选择了

**Comment by yandixuan** [comment]
just look at this
https://github.com/element-plus/element-plus/pull/6843

**Comment by cjq02** [comment]
> just look at this #6843

good!!!

**Comment by buqiyuan** [comment]
Duplicate of #6887
