### ISSUE TITLE
[Bug Report] [TypeScript] [select-v2] 输入中文的时候无法新建选项，需要再输入一个非中文字符或删除一个字符才能触发新建操作

### ISSUE THREAD

**Issue by MoConWu** [element-plus/element-plus#6972]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Windows10`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgICAgICAgICAgICAgdi1tb2RlbD1cInZhbHVlM1wiXG4gICAgICAgICAgICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4OyBtYXJnaW4tcmlnaHQ6IDE2cHg7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGVcIlxuICAgICAgICAgICAgICAgIGFsbG93LWNyZWF0ZVxuICAgICAgICAgICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgICAgICAgICBtdWx0aXBsZVxuICAgICAgICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgICAgICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgICAgICAgICAgICAgQGNoYW5nZT1cIm9uX2NoYW5nZVwiXG4gICAgICAgICAgICAgICAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTMgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gcmVmKFtdKVxuY29uc3Qgb25fY2hhbmdlID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyhvcHRpb25zLnZhbHVlKTtcbiAgY29uc29sZS5sb2codmFsdWUzLnZhbHVlKTtcbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

输入中文的时候无法新建选项，需要再输入一个非中文字符或删除一个字符才能触发新建操作

### What is Expected?

输入中文后可以直接新建

### What is actually happening?

输入中文的时候无法新建选项，需要再输入一个非中文字符或删除一个字符才能触发新建操作

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/33497338/161370891-c0221fb3-186e-491c-973d-ae8668dc3582.png)
![image](https://user-images.githubusercontent.com/33497338/161370896-418a69b7-62a3-4f93-8ce9-920feb43d7a9.png)

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/161375225-47a50b02-c1a7-4845-bc42-fdb641bca70b.png)

你好，通过你的在线链接无法复现该问题

**Comment by MoConWu** [comment]
> 
> ![image](https://user-images.githubusercontent.com/39730999/161375225-47a50b02-c1a7-4845-bc42-fdb641bca70b.png)
> 
> 你好，通过你的在线链接无法复现该问题

你输入完中文后，立即出现了新增项吗？为什么我不可以立即出现。英文可以立即出现。

**Comment by littleboarx** [comment]
这个是微软输入法的问题，我i软输入法s输入文字的时候没有input事件

**Comment by MoConWu** [comment]
> 这个是微软输入法的问题，微软输入法输入中文的时候不会触发input事件

对，我用的微软输入法，请问这种情况有办法解决吗，很多人都用的微软输入法吧

**Comment by mrstierchen** [comment]
![image](https://user-images.githubusercontent.com/86156831/161377555-7c968018-3f22-49ec-8785-fc8a49774f46.png)
我用微软输入法，这样应该是正常的吧？

**Comment by MoConWu** [comment]
> ![image](https://user-images.githubusercontent.com/86156831/161377555-7c968018-3f22-49ec-8785-fc8a49774f46.png)
> 我用微软输入法，这样应该是正常的吧？

你把中文打出来试试

**Comment by codefarmer2019** [comment]
![image](https://user-images.githubusercontent.com/86113685/161377968-24def285-858e-461a-90cb-ac89911684a4.png)
拼写完后 直接空格键入 就出来了呀

**Comment by mrstierchen** [comment]
![image](https://user-images.githubusercontent.com/86156831/161378063-d3d7dc3b-a2e8-4d44-b85d-9318b9020102.png)
拼写完成 直接空格键入 就立即出现了新增项了呀

**Comment by MoConWu** [comment]
> ![image](https://user-images.githubusercontent.com/86156831/161378063-d3d7dc3b-a2e8-4d44-b85d-9318b9020102.png)
> 拼写完成 直接空格键入 就立即出现了新增项了呀

我用的微软自带输入法不可以出现

**Comment by MoConWu** [comment]
> ![image](https://user-images.githubusercontent.com/86156831/161378063-d3d7dc3b-a2e8-4d44-b85d-9318b9020102.png)
> 拼写完成 直接空格键入 就立即出现了新增项了呀

你还打了空格键吗？没有多打一个空格吧？我多打一个空格也是可以的，但会多一个空格

**Comment by mrstierchen** [comment]
> > ![image](https://user-images.githubusercontent.com/86156831/161378063-d3d7dc3b-a2e8-4d44-b85d-9318b9020102.png)
> > 拼写完成 直接空格键入 就立即出现了新增项了呀
> 
> 你还打了空格键吗？没有多打一个空格吧？我多打一个空格也是可以的，但会多一个空格

没有多打空格，空格只是确认输入而已

**Comment by MoConWu** [comment]
> > > ![image](https://user-images.githubusercontent.com/86156831/161378063-d3d7dc3b-a2e8-4d44-b85d-9318b9020102.png)
> > > 拼写完成 直接空格键入 就立即出现了新增项了呀
> > 
> > 你还打了空格键吗？没有多打一个空格吧？我多打一个空格也是可以的，但会多一个空格
> 
> 没有多打空格，空格只是确认输入而已

那我的不行

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/161415439-d71eecde-6b64-495c-aaee-54c4d3673138.png)
![image](https://user-images.githubusercontent.com/23251408/161415461-9a444364-26f3-4751-9cf9-455928fe9298.png)
这是我电脑的测试结果

**Comment by MoConWu** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/161415439-d71eecde-6b64-495c-aaee-54c4d3673138.png)
> ![image](https://user-images.githubusercontent.com/23251408/161415461-9a444364-26f3-4751-9cf9-455928fe9298.png)
> 这是我电脑的测试结果

谢谢，可是我的win10还不行

**Comment by MoConWu** [comment]
我测试了最新版本2.2.17，还是不行

**Comment by chenxch** [comment]
> 我测试了最新版本2.2.17，还是不行

我用win10测试了，也是没问题了，方便录个gif或者视频？

**Comment by MoConWu** [comment]
![2022-09-29-20-21-35](https://user-images.githubusercontent.com/33497338/193030566-e9815a5f-8866-4003-93ef-3653a2bc5fdf.gif)

用的是微软的日语输入法，微软中文输入法是一样的问题

> > 我测试了最新版本2.2.17，还是不行
> 
> 我用win10测试了，也是没问题了，方便录个gif或者视频？

**Comment by MoConWu** [comment]
换了搜狗输入法却发现没有这个问题，
Windows10，微软输入法都有问题。

**Comment by chenxch** [comment]
![selet](https://user-images.githubusercontent.com/23251408/193035702-cc8e0746-7b92-4ced-b66d-0e6745fdac5e.gif)
![image](https://user-images.githubusercontent.com/23251408/193035767-0dc8894a-3f1d-4834-bdb4-d25877529782.png)
怎么感觉输入法长的不一样0 0

**Comment by chenxch** [comment]
这个算是在部分window版本下的某个版本的微软输入法会出现的场景，可排查的信息较少，应该是输入法触发事件上存在问题，只能看看后续有没有其他更详细的信息。

**Comment by chenxch** [comment]
只能看看还有没有其他人遇到以及提供可以更好定位的相关信息了。
