### ISSUE TITLE
[Feature Request] [date-picker] ELDatePicker 性能问题 渲染时间200ms+

### ISSUE THREAD

**Issue by 838239178** [element-plus/element-plus#6973]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `date-picker`

## Description

DatePikcer 性能过低，卡顿明显

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/55338151/161371917-bba6e8af-d138-413b-8326-db0dd6f7c2a7.png)

**Comment by sampsonliu** [comment]
楼主你好，这个是怎么显示出来每个组件的渲染时间呢？这是什么技能，可以分享一下么

**Comment by 838239178** [comment]
> 楼主你好，这个是怎么显示出来每个组件的渲染时间呢？这是什么技能，可以分享一下么

赶紧弃坑element吧 bug多到数不清

**Comment by wzrove** [comment]
> 楼主你好，这个是怎么显示出来每个组件的渲染时间呢？这是什么技能，可以分享一下么

vue-devtools 6.XX版本就可以显示了
