### ISSUE TITLE
[Feature Request] [Enhancement] [loading] v-loading / ElLoading 增加延迟选项

### ISSUE THREAD

**Issue by ziloen** [element-plus/element-plus#6977]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `loading`

## Description

增加延迟选项，指定延迟时间内不显示加载，防止闪烁

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
为什么自己不延时设置loading呢

**Comment by Oen-Cpz** [comment]
只是建议，感觉挺实用的，[大致效果](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5cbmFzeW5jIGZ1bmN0aW9uIHNsZWVwKHRpbWU6IG51bWJlcikge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUpID0+IHNldFRpbWVvdXQocmVzb2x2ZSwgdGltZSkpXG59XG5cbmNvbnN0IGxpc3QgPSByZWYoW10pXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxuY29uc3QgcmVxdWVzdFRpbWUgPSByZWYoMjAwKVxuY29uc3QgZGVsYXlUaW1lID0gcmVmKDMwMClcbmxldCB0aW1lciA9IG51bGxcblxuYXN5bmMgZnVuY3Rpb24gc2VuZFJlcXVlc3QoKSB7XG4gIHRpbWVyICYmIGNsZWFyVGltZW91dCh0aW1lcilcbiAgdGltZXIgPSBzZXRUaW1lb3V0KCgpID0+IChsb2FkaW5nLnZhbHVlID0gdHJ1ZSksIGRlbGF5VGltZS52YWx1ZSlcblxuICBhd2FpdCBzbGVlcChyZXF1ZXN0VGltZS52YWx1ZSlcbiAgbGlzdC52YWx1ZSA9IFtcbiAgICB7XG4gICAgICBhOiB+fihNYXRoLnJhbmRvbSgpICogMTApLFxuICAgICAgYjogfn4oTWF0aC5yYW5kb20oKSAqIDEwKSxcbiAgICAgIGM6IH5+KE1hdGgucmFuZG9tKCkgKiAxMCksXG4gICAgfSxcbiAgXVxuXG4gIHRpbWVyICYmIGNsZWFyVGltZW91dCh0aW1lcilcbiAgdGltZXIgPSBudWxsXG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gbGFiZWwtcG9zaXRpb249XCJyaWdodFwiIDpsYWJlbC13aWR0aD1cIjEyMFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLlu7bov5/ml7bpl7QobXMpXCI+XG4gICAgICA8ZWwtaW5wdXQgcGxhY2Vob2xkZXI9XCLlu7bov5/liqDovb3liqjnlLsobXMpXCIgdi1tb2RlbC5udW1iZXI9XCJkZWxheVRpbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuXG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuivt+axguaXtumXtChtcylcIj5cbiAgICAgIDxlbC1zbGlkZXIgOm1pbj1cIjIwMFwiIDptYXg9XCIyMDAwXCIgOnN0ZXA9XCIzMDBcIiB2LW1vZGVsPVwicmVxdWVzdFRpbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuXG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIlwiPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInNlbmRSZXF1ZXN0XCI+5Y+R6LW36K+35rGCPC9lbC1idXR0b24+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cblxuICA8ZWwtdGFibGUgdi1sb2FkaW5nPVwibG9hZGluZ1wiIDpkYXRhPVwibGlzdFwiIDpoZWlnaHQ9XCIzMDBcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiYVwiIHByb3A9XCJhXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiYlwiIHByb3A9XCJiXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiY1wiIHByb3A9XCJjXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

**Comment by chenxch** [comment]
可以自行控制loading解决，暂不考虑添加。
