### ISSUE TITLE
app.use(ElementPlus, { size: 'small', zIndex: 3000 });  zIndex did not work.

### ISSUE THREAD

**Issue by NO-MAP** [element-plus/element-plus#698]
code:
```
app.use(ElementPlus, { size: 'small', zIndex: 3000 });
```
view:
![image](https://user-images.githubusercontent.com/25893193/100256447-c0630900-2f7f-11eb-82cd-e3ddeae14f46.png)

and `el-message` will be covered by `el-dialog`
as follows:
![e6b7453eb88357f4db181ac21d05f11](https://user-images.githubusercontent.com/25893193/100256104-50ed1980-2f7f-11eb-97ef-9f6e798ae83c.png)

it seems like the default value 2000 should be more higher.
https://github.com/element-plus/element-plus/blob/5bd50ac16e6ab8d6e5c7db5fc0c557e2f49098a0/packages/utils/popup-manager.ts#L197

**Comment by JeremyWuuuuu** [comment]
Will be fixed soon.

**Comment by JeremyWuuuuu** [comment]
Would you mind provide me some sample code?

**Comment by NO-MAP** [comment]
sample:

https://codesandbox.io/s/quiet-rgb-2fv46?fontsize=14&hidenavigation=1&theme=dark

when i use mutilple dialogs, the last dialog's index will be higher than message's.
