### ISSUE TITLE
[Bug Report] [Component] [upload] TypeError: t.upload.addEventListener is not a function

### ISSUE THREAD

**Issue by cjq02** [element-plus/element-plus#6989]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.27`
- Element Plus Version: `2.1.7`
- Browser / OS: `99.0.4844.84`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-nj6tp0?file=/src/App.vue)

### Steps to reproduce

vite build以后上传文件控制台报错，文件上传失败
![image](https://user-images.githubusercontent.com/16457309/161418421-a5d8f819-5c1d-4f15-895d-cac5bf3bc096.png)

### What is Expected?

上传文件成功

### What is actually happening?

代码报错

### Additional comments

_(empty)_

**Comment by czh740132583** [comment]
也许你需要提供一下打包配置，我这边用vite配置什么都没写，全走默认，打包出来没有问题

**Comment by cjq02** [comment]
> 也许你需要提供一下打包配置，我这边用vite配置什么都没写，全走默认，打包出来没有问题

我还原到2.0.3版本没有这个问题，我看到相关源码有改动：

代码文件：packages/components/upload/src/ajax.ts
报错语句应该是这个：（63行）
![image](https://user-images.githubusercontent.com/16457309/161483553-01fe65cf-e125-4381-8865-c6bf95d123dc.png)
编译后代码：
![image](https://user-images.githubusercontent.com/16457309/161484624-f12ae19f-2685-4b82-8745-dcc5f83ecfd3.png)

**Comment by cjq02** [comment]
vite.config.js

`import { loadEnv } from 'vite';
import path, { resolve } from 'path';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import viteSvgIcons from 'vite-plugin-svg-icons';
import { durationLogger, autoImport } from './vite.plugin.ext';
import Inspect from 'vite-plugin-inspect';
import { viteMockServe } from 'vite-plugin-mock';
import setting from './src/settings';

const prodMock = setting.openProdMock;

export default ({ command, mode }) => {
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) };
  /* console.log('VITE_APP_BASE_URL', process.env.VITE_APP_BASE_URL);
  console.log('VITE_APP_BASE_API', process.env.VITE_APP_BASE_API);*/
  return {
    /*
     * "/vue3-admin-plus" nginx deploy folder
     * detail to look https://vitejs.cn/config/#base
     * how to config, such as http://8.135.1.141/vue3-admin-plus/#/dashboard
     * "/vue3-admin-plus/" --> config to base is you need
     * http://8.135.1.141 --> if you config "/" , you can visit attached  to http://8.135.1.141
     * */
    base: setting.viteBasePath,
    define: {
      'process.platform': null,
      'process.version': null
    },
    clearScreen: false,
    server: {
      hmr: { overlay: false }, // 禁用或配置 HMR 连接 设置 server.hmr.overlay 为 false 可以禁用服务器错误遮罩层
      // 服务配置
      port: 8122, // 类型： number 指定服务器端口;
      open: false, // 类型： boolean | string在服务器启动时自动在浏览器中打开应用程序；
      cors: true, // 类型： boolean | CorsOptions 为开发服务器配置 CORS。默认启用并允许任何源
      // proxy look for https://vitejs.cn/config/#server-proxy
      proxy: {
        // 类型： Record<string, string | ProxyOp 为开发服务器配置自定义代理规则
        [`/${process.env.VITE_APP_BASE_API}`]: {
          target: process.env.VITE_APP_BASE_URL,
          changeOrigin: true
        }
      }
    },
    plugins: [
      vue(),
      vueJsx(),
      /* legacy({
        targets: ['ie >= 11'],
        additionalLegacyPolyfills: ['regenerator-runtime/runtime']
      }),*/
      viteSvgIcons({
        // config svg dir that can config multi
        iconDirs: [path.resolve(process.cwd(), 'src/icons/common'), path.resolve(process.cwd(), 'src/icons/nav-bar')],
        // appoint svg icon using mode
        symbolId: 'icon-[dir]-[name]'
      }),
      // https://github.com/anncwb/vite-plugin-mock/blob/HEAD/README.zh_CN.md
      viteMockServe({
        supportTs: true,
        mockPath: 'mock',
        localEnabled: command === 'serve',
        prodEnabled: prodMock,
        injectCode: `
          import { setupProdMockServer } from './mockProdServer';
          setupProdMockServer();
        `,
        logger: true
      }),
      autoImport(),
      Inspect(),
      durationLogger()
    ],
    build: {
      minify: 'terser',
      brotliSize: false,
      // 消除打包大小超过警告
      chunkSizeWarningLimit: 5000,
      // remote console.log in prod
      terserOptions: {
        // detail to look https://terser.org/docs/api-reference#compress-options
        compress: {
          drop_console: false,
          pure_funcs: ['console.log', 'console.info'],
          drop_debugger: true
        }
      },
      // build assets Separate
      assetsDir: 'static/assets',
      rollupOptions: {
        output: {
          chunkFileNames: 'static/js/[name]-[hash].js',
          entryFileNames: 'static/js/[name]-[hash].js',
          assetFileNames: 'static/[ext]/[name]-[hash].[ext]'
        }
      }
    },
    resolve: {
      alias: {
        '~': resolve(__dirname, './'),
        '@': resolve(__dirname, 'src')
      }
    },
    css: {
      preprocessorOptions: {
        // define global scss variable
        scss: {
          additionalData: `@import "@/styles/variables.scss";`,
          charset: false
        }
      },
      // https://github.com/vitejs/vite/issues/5833【保持关注】
      postcss: {
        plugins: [{
          postcssPlugin: 'internal:charset-removal',
          AtRule: {
            charset: (atRule) => {
              if (atRule.name === 'charset') {
                atRule.remove();
              }
            }
          }
        }]
      }
    }
  };
};
`

**Comment by cjq02** [comment]
**vite.config.js**
```
import { loadEnv } from 'vite';
import path, { resolve } from 'path';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import viteSvgIcons from 'vite-plugin-svg-icons';
import { durationLogger, autoImport } from './vite.plugin.ext';
import Inspect from 'vite-plugin-inspect';
import { viteMockServe } from 'vite-plugin-mock';
import setting from './src/settings';

const prodMock = setting.openProdMock;

export default ({ command, mode }) => {
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) };
  /* console.log('VITE_APP_BASE_URL', process.env.VITE_APP_BASE_URL);
  console.log('VITE_APP_BASE_API', process.env.VITE_APP_BASE_API);*/
  return {
    base: setting.viteBasePath,
    define: {
      'process.platform': null,
      'process.version': null
    },
    clearScreen: false,
    server: {
      hmr: { overlay: false }, // 禁用或配置 HMR 连接 设置 server.hmr.overlay 为 false 可以禁用服务器错误遮罩层
      // 服务配置
      port: 8122, // 类型： number 指定服务器端口;
      open: false, // 类型： boolean | string在服务器启动时自动在浏览器中打开应用程序；
      cors: true, // 类型： boolean | CorsOptions 为开发服务器配置 CORS。默认启用并允许任何源
      // proxy look for https://vitejs.cn/config/#server-proxy
      proxy: {
        // 类型： Record<string, string | ProxyOp 为开发服务器配置自定义代理规则
        [`/${process.env.VITE_APP_BASE_API}`]: {
          target: process.env.VITE_APP_BASE_URL,
          changeOrigin: true
        }
      }
    },
    plugins: [
      vue(),
      vueJsx(),
      /* legacy({
        targets: ['ie >= 11'],
        additionalLegacyPolyfills: ['regenerator-runtime/runtime']
      }),*/
      viteSvgIcons({
        // config svg dir that can config multi
        iconDirs: [path.resolve(process.cwd(), 'src/icons/common'), path.resolve(process.cwd(), 'src/icons/nav-bar')],
        // appoint svg icon using mode
        symbolId: 'icon-[dir]-[name]'
      }),
      // https://github.com/anncwb/vite-plugin-mock/blob/HEAD/README.zh_CN.md
      viteMockServe({
        supportTs: true,
        mockPath: 'mock',
        localEnabled: command === 'serve',
        prodEnabled: prodMock,
        injectCode: `
          import { setupProdMockServer } from './mockProdServer';
          setupProdMockServer();
        `,
        logger: true
      }),
      autoImport(),
      Inspect(),
      durationLogger()
    ],
    build: {
      minify: 'terser',
      brotliSize: false,
      // 消除打包大小超过警告
      chunkSizeWarningLimit: 5000,
      // remote console.log in prod
      terserOptions: {
        // detail to look https://terser.org/docs/api-reference#compress-options
        compress: {
          drop_console: false,
          pure_funcs: ['console.log', 'console.info'],
          drop_debugger: true
        }
      },
      // build assets Separate
      assetsDir: 'static/assets',
      rollupOptions: {
        output: {
          chunkFileNames: 'static/js/[name]-[hash].js',
          entryFileNames: 'static/js/[name]-[hash].js',
          assetFileNames: 'static/[ext]/[name]-[hash].[ext]'
        }
      }
    },
    resolve: {
      alias: {
        '~': resolve(__dirname, './'),
        '@': resolve(__dirname, 'src')
      }
    },
    css: {
      preprocessorOptions: {
        // define global scss variable
        scss: {
          additionalData: `@import "@/styles/variables.scss";`,
          charset: false
        }
      },
      // https://github.com/vitejs/vite/issues/5833【保持关注】
      postcss: {
        plugins: [{
          postcssPlugin: 'internal:charset-removal',
          AtRule: {
            charset: (atRule) => {
              if (atRule.name === 'charset') {
                atRule.remove();
              }
            }
          }
        }]
      }
    }
  };
};

```

**Comment by cjq02** [comment]
> 也许你需要提供一下打包配置，我这边用vite配置什么都没写，全走默认，打包出来没有问题

可以分享下你vite的配置吗

**Comment by baiwusanyu-c** [comment]
> > 也许你需要提供一下打包配置，我这边用vite配置什么都没写，全走默认，打包出来没有问题
> 
> 可以分享下你vite的配置吗。现在一直卡在2.0.3版本，升级不上去，很难受。

配置我什么也没写，就是用 vite 指令生成的模板项目，你知道它也会自己生成一个 vite.config.ts，然后将你demo里的代码复制到项目中，似乎并没有复现，所以我猜测会不会是你的配置中某个地方影响了

**Comment by cjq02** [comment]
> 也许你需要提供一下打包配置，我这边用vite配置什么都没写，全走默认，打包出来没有问题

找到原因了， vite.config.js引入mock服务插件，在生产环境环境开启时，会覆盖XMLHttpRequest对象。

以下是一个简单的demo：
[upload-demo.zip](https://github.com/element-plus/element-plus/files/8461492/upload-demo.zip)

**Comment by sxzz** [comment]
那应该是 vite-plugin-mock 的 bug，请向此仓库反馈。
