### ISSUE TITLE
element-plus.org进不去，有什么解决的办法吗

### ISSUE THREAD

**Issue by 1948037137** [element-plus/element-plus#700]

**Comment by zazzaz** [comment]
We are working on this to speed up our website networking.

Also, you can visit https://element-plus.gitee.io/ as an alternative, which is faster in China.

**Comment by JeremyWuuuuu** [comment]
If you can visit .org site you might need to get pass of the GFW, or as @zazzaz said, use [ElementPlus](https://element-plus.gitee.io/) instead, it's hosted inside mainland China.
Closing this issue due to it's not related to the project itself.
