### ISSUE TITLE
[Bug Report] [Component] [table, table-column] Input in expanded table resets the expantion

### ISSUE THREAD

**Issue by TimAufdemKampe** [element-plus/element-plus#7011]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/99.0.4844.84`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Link](https://stackblitz.com/edit/github-6bw3ts-yjd7cv)

### Steps to reproduce

Expand a table row and type something in the el-input or expand the table row and than select a option from the el-select

### What is Expected?

The input value should be saved in the current tableData object

### What is actually happening?

It only saves the first letter and than closes the expanted table row

### Additional comments

_(empty)_

**Comment by msidolphin** [comment]
please use `row-key`
