### ISSUE TITLE
[Bug Report] [form-item, form] How to hide el-form-item__error after field valid?

### ISSUE THREAD

**Issue by SevymolSebastian** [element-plus/element-plus#7015]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-form-item`
- `el-form`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-ig51f3)

### Steps to reproduce

Step 1: input invalid email id in username field
Step 2: blur event on field
Step 3: check error message
Step 4: input valid email id in username field 
Step 5: blur event on field

### What is Expected?

Proper error message

### What is actually happening?

is required error message on all time if valid or invalid. Also second rule not validates

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
If you want to use VeeForm to handle validation，you should remove the `required` prop from `el-form-item`.
