### ISSUE TITLE
[Bug Report] [Component] [tree-select] treeSelect组件开启check-strictly时，点击节点选中的同时会展开被点击的子集

### ISSUE THREAD

**Issue by dimaUpp** [element-plus/element-plus#7018]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tree-select.html#select-any-level)

### Steps to reproduce

tree-select中select-any-level的demo中选中某个父级，再展开下拉选择框会发现刚点击的子集也展开了

### What is Expected?

点击节点为选中行为，点击expand-icon才展开

### What is actually happening?

点击节点在选中的同时展开了子集

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Member confirmation is required.

**Comment by btea** [comment]
cc @yujinpan

**Comment by JeremyWuuuuu** [comment]
Closed via https://github.com/element-plus/element-plus/pull/7156
