### ISSUE TITLE
[Bug Report] [Component] [All] Dropdown of some components will not close if the component is deactived.

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#7025]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome 99.0.4844.51 / Windows 10`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuICBjb25zdCB2YWx1ZSA9IHJlZigpO1xuICBjb25zdCBpc1Nob3dpbmcgPSByZWYodHJ1ZSk7XG4gIGxldCB0aW1lb3V0ID0gMDtcbiAgbGV0IGNvdW50ZG93biA9IHJlZigwKTtcbiAgbGV0IGNvdW50SW50ZXJ2YWwgPSAwO1xuICBjb25zdCB0b2dnbGUgPSAoKSA9PiB7XG4gICAgaWYgKCFpc1Nob3dpbmcudmFsdWUpIHtcbiAgICAgIGlzU2hvd2luZy52YWx1ZSA9IHRydWU7XG4gICAgICBjbGVhclRpbWVvdXQodGltZW91dCk7XG4gICAgICBjbGVhckludGVydmFsKGNvdW50SW50ZXJ2YWwpO1xuICAgICAgY291bnRkb3duLnZhbHVlID0gMDtcbiAgICB9IGVsc2Uge1xuICAgIFx0dGltZW91dCA9IHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgXHRpc1Nob3dpbmcudmFsdWUgPSBmYWxzZTtcbiAgXHRcdH0sIDMwMDApO1xuICAgICAgY291bnRkb3duLnZhbHVlID0gMztcbiAgICAgIGNvdW50SW50ZXJ2YWwgPSBzZXRJbnRlcnZhbCgoKSA9PiB7XG4gICAgICAgIGNvdW50ZG93bi52YWx1ZSAtPSAxO1xuICAgICAgICBpZihjb3VudGRvd24udmFsdWUgPT09IDApIHtcbiAgICAgICAgICBjbGVhckludGVydmFsKGNvdW50SW50ZXJ2YWwpO1xuICAgICAgICB9XG4gICAgICB9LCAxMDAwKTtcbiAgICB9XG4gIH1cblx0Y29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlXCI+VG9nZ2xlKHt7IGNvdW50ZG93biB9fSk8L2VsLWJ1dHRvbj5cbiAgPGtlZXAtYWxpdmU+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiB2LWlmPVwiaXNTaG93aW5nXCI+XG4gICAgXHQ8ZWwtb3B0aW9uXG4gICAgICBcdHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIFx0OmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgXHQ6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIFx0OnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgXHQvPlxuICBcdDwvZWwtc2VsZWN0PlxuICA8L2tlZXAtYWxpdmU+XG4gIDxrZWVwLWFsaXZlPlxuICAgIDxlbC10aW1lLXBpY2tlciB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIkFyYml0cmFyeSB0aW1lXCIgdi1pZj1cImlzU2hvd2luZ1wiIC8+XG4gIDwva2VlcC1hbGl2ZT5cbiAgPGtlZXAtYWxpdmU+XG4gIFx0PGVsLXRpbWUtc2VsZWN0XG4gICAgXHR2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgdi1pZj1cImlzU2hvd2luZ1wiXG4gICBcdCBzdGFydD1cIjA4OjMwXCJcbiAgICBcdHN0ZXA9XCIwMDoxNVwiXG4gICAgXHRlbmQ9XCIxODozMFwiXG4gICAgXHRwbGFjZWhvbGRlcj1cIlNlbGVjdCB0aW1lXCJcbiAgXHQvPlxuICA8L2tlZXAtYWxpdmU+XG4gIDxrZWVwLWFsaXZlPlxuICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHYtaWY9XCJpc1Nob3dpbmdcIiAvPlxuICA8L2tlZXAtYWxpdmU+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. Put a component with dropdown in a route and open the dropdown.  
2. Leave the router

\* In minify reproduction, a delay v-if is used to emulate user directly click back button on navigator bar, trigger the router leaving event, in this case,  component is to be hidden and removed from the DOM tree but not lose its state. And because the navigation bar is not a part of page, the click outside event will not be triggerred. 

### What is Expected?

dropdown menu should be closed

### What is actually happening?

dropdown menu keep opening but the father component is deactived & hidden

### Additional comments

all components with dropdown are effected.
we should close the dropdown menu in `onDeactive` life cycle hook

**Comment by iwusong** [comment]
it's only happen on keep-alive?

**Comment by KawaiiZapic** [comment]
Also take a look at alert and dialog, these element has a modal overlay on body, if we never think about deactiving, the overlay may not be remove because we do not handle the deactive event.

**Comment by KawaiiZapic** [comment]
> it's only happen on keep-alive?

I'm not sure, maybe v-show may also causing this, any action hide the DOM element but not destory the component instance may cause this bug.

**Comment by iwusong** [comment]
> > it's only happen on keep-alive?
> 
> I'm not sure, maybe v-show may also causing this, any action hide the DOM element but not destory the component instance may cause this bug.
> 
> Edit 1: I test using v-show to toggle element status, and also cause this bug. But Vue do not provide a event to handle v-show toggle event, maybe we need directly listen to the style attribute, or use some API like Intersection Observer.

maybe need to expand teleport to solve the problem

**Comment by tolking** [comment]
Fixed in #8301

**Comment by iwusong** [comment]
> Fixed in #8301

This doesn't really solve the problem

**Comment by tolking** [comment]
Currently, it can only fixed the issues caused by KeepAlive. For v-show, it may need the official hooks provided by vue.

Although we can detect component style changes through the MutationObserver api, but we cannot detect changes from the parent.

**Comment by KawaiiZapic** [comment]
> Currently, it can only fixed the issues caused by KeepAlive. For v-show, it may need the official hooks provided by vue.
> 
> Although we can detect component style changes through the MutationObserver api, but we cannot detect changes from the parent.

We can use IntersectionObserver API to decect visibility changes

**Comment by tolking** [comment]
This is not an elegant solution, because the height of the dropdown content may exceed the height of the screen. When viewing the content below the dropdown, it may cause the dropdown to close.

**Comment by tolking** [comment]
This is not an elegant solution, because the height of the dropdown content may exceed the height of the screen. When viewing the content below the dropdown, it may cause the dropdown to close.

**Comment by iwusong** [comment]
> > Currently, it can only fixed the issues caused by KeepAlive. For v-show, it may need the official hooks provided by vue.
> > Although we can detect component style changes through the MutationObserver api, but we cannot detect changes from the parent.
> 
> We can use IntersectionObserver API to decect visibility changes, but for now, it's good enough to handle most cases.

I have tried the IntersectionObserver API，but sometimes there are problems

Once  target dom was recreated(e.g. v-if ...), monitoring will be lost even if he reappears. 
If observe it every time ，the new observer does not know whether there will be memory leakage.

**Comment by KawaiiZapic** [comment]
> > > Currently, it can only fixed the issues caused by KeepAlive. For v-show, it may need the official hooks provided by vue.
> > > Although we can detect component style changes through the MutationObserver api, but we cannot detect changes from the parent.
> > 
> > 
> > We can use IntersectionObserver API to decect visibility changes, but for now, it's good enough to handle most cases.
> 
> I have tried the IntersectionObserver API，but sometimes there are problems
> 
> Once target dom was recreated(e.g. v-if ...), monitoring will be lost even if he reappears. If observe it every time ，the new observer does not know whether there will be memory leakage.

It's OK to have a global observer for all drop down, observe on mount and unobserve in beforeUnmount
See more here https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/unobserve
