### ISSUE TITLE
import { ElNotification } from 'element-plus'

### ISSUE THREAD

**Issue by Lucas-lululu** [element-plus/element-plus#703]
设置为ts的时候会出现 改为js没有
![image](https://user-images.githubusercontent.com/47276871/100337484-652e2680-3012-11eb-8db7-80356eaf39a2.png)
![image](https://user-images.githubusercontent.com/47276871/100337515-6f502500-3012-11eb-888f-bbce419b7800.png)

**Comment by Jonny-china** [comment]
我ts类型正常，但是引入的组件是 `undefined `，调用不了，例如 `Message ` 组件，console后打印出 `undefined `

**Comment by Lucas-lululu** [comment]
> 我ts类型正常，但是引入的组件是 `undefined `，调用不了，例如 `Message ` 组件，console后打印出 `undefined `

yes

**Comment by JeremyWuuuuu** [comment]
> 我ts类型正常，但是引入的组件是 `undefined `，调用不了，例如 `Message ` 组件，console后打印出 `undefined `

Bump the version you will get it correct. But you will end up like @Lucas-lululu due to some type bugs we had, but we are about to release a new version to fix that.

**Comment by JeremyWuuuuu** [comment]
This one is duplicate with #695 #689 , so I am closing it due to duplication, you can track this down there.

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.23
