### ISSUE TITLE
[Bug Report] [Build] [rate] 项目打包时 vue-tsc检测  node_modules/element-plus/es/components/rate/src/rate.vue.d.ts:1:15 - error TS1005: ',' expected.

### ISSUE THREAD

**Issue by GamesSoul** [element-plus/element-plus#7032]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `e.g. Chrome 96.0.4664.45 / macOS 12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-rate`

### Reproduction Link

[Github Repo](https://github.com/GamesSoul/vite-demo.git)

### Steps to reproduce

执行vue-tsc --noEmit && vite build

### What is Expected?

将rate的类型引入修改了
import type { xxx } from 'vue'

### What is actually happening?

import { type xxx } from 'vue'

### Additional comments

编译后的问题文件
node_modules/element-plus/es/components/rate/src/rate.vue.d.ts
node_modules/element-plus/lib/components/rate/src/rate.vue.d.ts

**Comment by CubeLite** [comment]
刚试用一下element plus，就碰上了同样的问题。。。

**Comment by GamesSoul** [comment]
> 刚试用一下element plus，就碰上了同样的问题。。。

你也用的vite + tsx + vue + element plus？
我这边引入的vite-plugin-linter 插件 打包的时候自动检测node_modules的包里的类型导致报错了，官方不改的话 只能我自己在打包的时候关闭 ts 类型检测

**Comment by sunecosuri** [comment]
Similar error messages were displayed in the following environments. 
Does anyone know what the presumed cause is?

## Environment
- Vue Version: 3.2.24
- Element Plus Version: 2.1.9
- Browser / OS: e.g. Chrome 100.0.4896.75 / macOS 10.15.7
- Build Tool: vue-cli(webpack) 5.0.0-beta.3

```sh
$ vue-cli-service build --mode production
 ERROR  Failed to compile with 1 error                                                                                                    11:27:25

 error  in node_modules/element-plus/es/components/rate/src/rate.vue.d.ts:1:15

TS1005: ',' expected.
  > 1 | import { type CSSProperties } from 'vue';
      |               ^^^^^^^^^^^^^
    2 | declare const _default: import("vue").DefineComponent<{
    3 |     readonly modelValue: import("element-plus/es/utils").BuildPropReturn<NumberConstructor, 0, unknown, unknown, unknown>;
    4 |     readonly lowThreshold: import("element-plus/es/utils").BuildPropReturn<NumberConstructor, 2, unknown, unknown, unknown>;

```

**Comment by GamesSoul** [comment]
> Similar error messages were displayed in the following environments. Does anyone know what the presumed cause is?
> ## Environment
> 
>     * Vue Version: 3.2.24
> 
>     * Element Plus Version: 2.1.9
> 
>     * Browser / OS: e.g. Chrome 100.0.4896.75 / macOS 10.15.7
> 
>     * Build Tool: vue-cli(webpack) 5.0.0-beta.3
> 
> 
> ```shell
> $ vue-cli-service build --mode production
>  ERROR  Failed to compile with 1 error                                                                                                    11:27:25
> 
>  error  in node_modules/element-plus/es/components/rate/src/rate.vue.d.ts:1:15
> 
> TS1005: ',' expected.
>   > 1 | import { type CSSProperties } from 'vue';
>       |               ^^^^^^^^^^^^^
>     2 | declare const _default: import("vue").DefineComponent<{
>     3 |     readonly modelValue: import("element-plus/es/utils").BuildPropReturn<NumberConstructor, 0, unknown, unknown, unknown>;
>     4 |     readonly lowThreshold: import("element-plus/es/utils").BuildPropReturn<NumberConstructor, 2, unknown, unknown, unknown>;
> ```

errorFile  at  [element-plus](https://github.com/element-plus/element-plus)/[packages](https://github.com/element-plus/element-plus/tree/dev/packages)/[components](https://github.com/element-plus/element-plus/tree/dev/packages/components)/[rate](https://github.com/element-plus/element-plus/tree/dev/packages/components/rate)/[src](https://github.com/element-plus/element-plus/tree/dev/packages/components/rate/src)/rate.vue

**Comment by sxzz** [comment]
为 `vite-plugin-linter` 的问题，其依赖的 typescript 版本太低。
It's a problem with `vite-plugin-linter`. It relies on a version of typescript that is too low.

vite-plugin-linter 1.2.0
└── typescript 4.4.3

**Comment by sxzz** [comment]
@sunecosuri Please provide a minimum reproduction repo.

**Comment by littlepush** [comment]
有解决方案吗？遇到同样的问题，我写不来前端啊…

**Comment by wp993080086** [comment]
I had the same problem !

**node_modules   /element-plus/es/components/rate/src/rate.vue.d.ts:1:15**

`import { type CSSProperties } from 'vue';`

**Comment by GamesSoul** [comment]
> 有解决方案吗？遇到同样的问题，我写不来前端啊…

不要慌问题不大  在配置里打包的时候绕过ts校验  我用的是vite的vite-plugin-linter插件  打包的时候设置为disabled就完事了

**Comment by GamesSoul** [comment]
> 

最简单的办法就是你在打包的时候绕过tslint语法检测 这样就可以打包成功了

**Comment by GamesSoul** [comment]
> I had the same problem !
> 
> **node_modules /element-plus/es/components/rate/src/rate.vue.d.ts:1:15**
> 
> `import { type CSSProperties } from 'vue';`

最简单的办法就是在打包的时候绕过或者屏蔽掉tslint语法检测，这样就不会报错了

**Comment by sxzz** [comment]
请到 `vite-plugin-linter` 仓库反馈。
