### ISSUE TITLE
[Bug Report] [Component] [input] 选中文本框的文本后，左侧会多两个蓝色的像素点

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7034]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Edge Version 99.0.1150.30`
- Build Tool: `CDN`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBjbGVhcmFibGUgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

选中文本框 即可复现 
如果没出来 多点几次

### What is Expected?

没有像素点

### What is actually happening?

出现了几个未知的像素点

### Additional comments

![image](https://user-images.githubusercontent.com/50992790/162143104-8415571b-0105-4254-82f1-fa92f7e735e5.png)

**Comment by baiwusanyu-c** [comment]
列文虎克啊兄弟

**Comment by iwusong** [comment]
😮  电脑抗锯齿不够吧

**Comment by Edric-Li** [comment]
> 
不应该吧，我在我这边很多人电脑上都浮现了这个问题

**Comment by Edric-Li** [comment]
> 😮 电脑抗锯齿不够吧

不应该吧，我在我这边很多人电脑上都浮现了这个问题

**Comment by baiwusanyu-c** [comment]
这个问题似乎很难定位，通过尝试修改css 和分析dom结构并没有定位到问题，似乎和浏览器渲染有关？但是值得一提的是通过观察发现这几个像素点出现的位置刚好的 border-radius 的位置，同时对比以前版本，focus的border样式变成了内阴影实现，是不是跟这些有联系呢

**Comment by baiwusanyu-c** [comment]
这个问题似乎很难定位，通过尝试修改css 和分析dom结构并没有定位到问题，似乎和浏览器渲染有关？但是值得一提的是通过观察发现这几个像素点出现的位置刚好的 border-radius 的位置，同时对比以前版本，focus的border样式变成了内阴影实现，是不是跟这些有联系呢

**Comment by Edric-Li** [comment]
> 这个问题似乎很难定位，通过尝试修改css 和分析dom结构并没有定位到问题，似乎和浏览器渲染有关？但是值得一提的是通过观察发现这几个像素点出现的位置刚好的 border-radius 的位置，同时对比以前版本，focus的border样式变成了内阴影实现，是不是跟这些有联系呢

确实很难定位，我也尝试修改过css和分析过DOM 并没有定位到问题，无奈之下，就提到 Issues了

**Comment by iwusong** [comment]
我看了一下把transition 去掉就好，应该是浏览器渲染的bug

**Comment by 34205037** [comment]
我这里也早就发现这个问题了，只是不确定和本机硬件以及浏览器有没有关系，一直忍着没提

**Comment by sxzz** [comment]
macOS + Chrome 100 无法复现

**Comment by kinpoo** [comment]
chrome bug: https://stackoverflow.com/questions/69658462/inset-box-shadow-visual-artifacts-in-google-chrome

`.el-input__wrapper {
  transform: translate3d(0, 0, 0) !important;
}
`

**Comment by HeftyKoo** [comment]
> chrome bug: https://stackoverflow.com/questions/69658462/inset-box-shadow-visual-artifacts-in-google-chrome
> 
> `.el-input__wrapper { transform: translate3d(0, 0, 0) !important; } `

提个 pr ？
