### ISSUE TITLE
Question about documentations

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#704]
1. Collapse 折叠面板 中的slot标题没显示出来  需要改为 v-slot:title 或者#title ?
![image](https://user-images.githubusercontent.com/35122287/100359156-20b28300-3032-11eb-8844-0c7f5e67ba30.png)

**Comment by JeremyWuuuuu** [comment]
Yes, that has been addressed in #684

**Comment by JeremyWuuuuu** [comment]
Oh sorry for the earlier reply, this should be fixed soon, since the documentation has not been updated yet.

**Comment by xingleizhao** [comment]
You are right.
When you use named `slot` to implement custom panel title content, you need to modify it to supported by Vue 3.0 `v- slot:title` or `#title`.
