### ISSUE TITLE
[Bug Report] [All] 紧急问题：旧 element-ui 官网，组件codepen在线运行，vue地址依旧是旧地址，导致代码无法运行

### ISSUE THREAD

**Issue by huayang0304** [element-plus/element-plus#7040]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/100`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element UI](https://element.faas.ele.me/#/zh-CN/component/button)

### Steps to reproduce

1、打开 element-ui 官网
2、选择组件：代码在线运行
3、打开后vue链接错误

### What is Expected?

1、使用正确的vue地址，代码可在线运行

### What is actually happening?

1、使用了被更改的vue地址，代码不能运行

### Additional comments

紧急问题

**Comment by huayang0304** [comment]
![1649324799(1)](https://user-images.githubusercontent.com/45450994/162171672-1aae11cf-bf7b-4901-a557-65cc51d771d7.jpg)

**Comment by btea** [comment]
rel https://github.com/ElemeFE/element/pull/21684
