### ISSUE TITLE
[Feature Request] [Enhancement] [icon] icon 图标 不支持自定义图标吗

### ISSUE THREAD

**Issue by mentoorliubin** [element-plus/element-plus#7041]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `icon`

## Description

icon 图标 不支持自定义图标吗
现有的内置icon缺少一些常用图标 又没办法引入自定义图标?

### Additional comments

_(empty)_

**Comment by plainheart** [comment]
使用 `el-icon` 的[默认插槽](https://element-plus.org/zh-CN/component/icon.html#icon-%E6%8F%92%E6%A7%BD)不行吗？

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cbiAgPCEtLSBDdXN0b20gSWNvbnMgLS0+XG4gIDxlbC1pY29uPlxuICBcdDxzdmcgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiIHZpZXdCb3g9XCIwIDAgMjU2IDI1NlwiPjxwYXRoIGZpbGw9XCJjdXJyZW50Q29sb3JcIiBkPVwiTTIzMiAxNjh2MjRhOCA4IDAgMCAxLTggOEgzMmE4IDggMCAwIDEtOC04di0yMi45QzI0IDExMS42IDcwLjIgNjQuMiAxMjcuNiA2NEExMDQgMTA0IDAgMCAxIDIzMiAxNjhaXCIgb3BhY2l0eT1cIi4yXCI+PC9wYXRoPjxwYXRoIGZpbGw9XCJjdXJyZW50Q29sb3JcIiBkPVwiTTE3NiAxNTZhMTIgMTIgMCAxIDEtMTItMTJhMTIgMTIgMCAwIDEgMTIgMTJabS04NC0xMmExMiAxMiAwIDEgMCAxMiAxMmExMiAxMiAwIDAgMC0xMi0xMlptMTQ4IDI0djI0YTE2IDE2IDAgMCAxLTE2IDE2SDMyYTE2IDE2IDAgMCAxLTE2LTE2di0yMi45YTExMy40IDExMy40IDAgMCAxIDM1LjQtODIuNGwtMjUuMS0yNWE4LjEgOC4xIDAgMCAxIDExLjQtMTEuNGwyNi4xIDI2LjJhMTExLjUgMTExLjUgMCAwIDEgMTI4LjYtLjJsMjUuOS0yNmE4LjEgOC4xIDAgMCAxIDExLjQgMTEuNGwtMjQuOSAyNC44bDIuMyAyLjJBMTExLjIgMTExLjIgMCAwIDEgMjQwIDE2OFptLTE2IDBhOTUuMyA5NS4zIDAgMCAwLTI4LjItNjhhOTguNSA5OC41IDAgMCAwLTcuNy02LjhhLjEuMSAwIDAgMC0uMS0uMUE5NSA5NSAwIDAgMCAxMjggNzJoLS4zYy01Mi44LjItOTUuNyA0My44LTk1LjcgOTcuMVYxOTJoMTkyWlwiPjwvcGF0aD48L3N2Zz5cbiAgPC9lbC1pY29uPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

**Comment by SignDawn** [comment]
用阿里图标的话，自己使用 i 标签也是可以的呀，也不一定非要用 el-icon

**Comment by mentoorliubin** [comment]
> 用阿里图标的话，自己使用 i 标签也是可以的呀，也不一定非要用 el-icon

好的，谢谢

**Comment by mentoorliubin** [comment]
> 使用 `el-icon` 的[默认插槽](https://element-plus.org/zh-CN/component/icon.html#icon-%E6%8F%92%E6%A7%BD)不行吗？
好的，谢谢
