### ISSUE TITLE
[Feature Request] [Enhancement] [date-picker] [Feature Request]  [date-picker] DatePicker 的type新增weekrange、yearrange

### ISSUE THREAD

**Issue by to-Meeko** [element-plus/element-plus#7051]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `date-picker`

## Description

期待DatePicker组件的type属性增加weekrange、yearrange及其相关功能。

### Additional comments

_(empty)_

**Comment by fengguotao** [comment]
期待

**Comment by CherishTheYouth** [comment]
I've implemented this feature（yearrange）， I wonder if officials wanted that, If so, I would provide a pr.

**Comment by cfmj** [comment]
Feature Request weekrange
