### ISSUE TITLE
[Bug Report] [Component] [tree-select] el-tree-select 控件的 visible-change 事件, 每次触发2次

### ISSUE THREAD

**Issue by iamjxc** [element-plus/element-plus#7055]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.8`
- Browser / OS: `所有`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBkYXRhID0gW3sgdmFsdWU6IDEsIGxhYmVsOiAndGV4dCcgfV1cbmNvbnN0IGRvU2hvdyA9IChzaG93KSA9PiB7XG4gIGNvbnNvbGUubG9nKHNob3cpXG4gIG1zZy52YWx1ZSA9IG1zZy52YWx1ZSArICcsJyArIHNob3dcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtaWNvbj48VXNlciAvPjwvZWwtaWNvbj5cblxuICA8ZWwtdHJlZS1zZWxlY3QgOmRhdGE9XCJkYXRhXCIgQHZpc2libGUtY2hhbmdlPVwiZG9TaG93XCI+PC9lbC10cmVlLXNlbGVjdD5cblxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

下拉树展开时

### What is Expected?

触发1次 visible-change 事件

### What is actually happening?

触发2次 visible-change 事件

### Additional comments

_(empty)_

**Comment by JeremyWuuuuu** [comment]
Closed via https://github.com/element-plus/element-plus/pull/7156
