### ISSUE TITLE
[Bug Report] [Component] [tree-select] el-tree-select 控件配置 default-expanded-keys 后报错

### ISSUE THREAD

**Issue by iamjxc** [element-plus/element-plus#7056]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.8`
- Browser / OS: `所有`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgdmFsdWU6IFwiMVwiLFxuICAgIGxhYmVsOiAndGV4dCcsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHsgdmFsdWU6IFwiMTFcIiwgbGFiZWw6ICd0ZXh0MTEnIH0sXG4gICAgICB7IHZhbHVlOiBcIjEyXCIsIGxhYmVsOiAndGV4dDEyJyB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWljb24+PFVzZXIgLz48L2VsLWljb24+XG5cbiAgPCEtLSDmsqHmnInpl67popggLS0+XG4gIDxlbC10cmVlLXNlbGVjdCA6ZGF0YT1cImRhdGFcIiAgPjwvZWwtdHJlZS1zZWxlY3Q+XG4gIDwhLS0ganPmiqXplJkgLS0+XG4gIDxlbC10cmVlLXNlbGVjdCA6ZGF0YT1cImRhdGFcIiA6ZGVmYXVsdC1leHBhbmRlZC1rZXlzPVwiWycxMSddXCIgPjwvZWwtdHJlZS1zZWxlY3Q+XG5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

配置属性 :default-expanded-keys="[1]"

### What is Expected?

正确展开对应的节点

### What is actually happening?

js报错

### Additional comments

_(empty)_

**Comment by JeremyWuuuuu** [comment]
Closed via https://github.com/element-plus/element-plus/pull/7156
