### ISSUE TITLE
[Bug Report] [Component] [popover] el-popover组件使用v-model:visible控制显示, 按esc键隐藏后, 无法正常显示el-popover组件

### ISSUE THREAD

**Issue by xuge98** [element-plus/element-plus#7058]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.21`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/95.0.4638.69 / (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlciB2LW1vZGVsOnZpc2libGU9XCJ2aXNpYmxlXCIgcGxhY2VtZW50PVwiYm90dG9tXCIgOndpZHRoPVwiMTYwXCI+XG4gICAgPHA+QXJlIHlvdSBzdXJlIHRvIGRlbGV0ZSB0aGlzPzwvcD5cbiAgICA8ZGl2IHN0eWxlPVwidGV4dC1hbGlnbjogcmlnaHQ7IG1hcmdpbjogMFwiPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0eXBlPVwidGV4dFwiIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiXG4gICAgICAgID5jYW5jZWw8L2VsLWJ1dHRvblxuICAgICAgPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiXG4gICAgICAgID5jb25maXJtPC9lbC1idXR0b25cbiAgICAgID5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZSA9IHRydWVcIj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB1bnJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1.点击Delete按钮显示popover组件
2.按下键盘"Esc"键隐藏popover组件
3.再次点击Delete按钮, 无法正常显示

### What is Expected?

期望可以正常显示popover组件

### What is actually happening?

无法正常显示

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你可以先临时使用@hide事件将visible处理成false
