### ISSUE TITLE
[Bug Report] [Component] el-menu循环渲染dom节点乱了

### ISSUE THREAD

**Issue by duanhaobo** [element-plus/element-plus#7059]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.6`
- Element Plus Version: `2.1.8`
- Browser / OS: `版本 99.0.4844.84（正式版本） (x86_64)/mac os 11.6.3 `
- Build Tool: `Vue CLI`

### Related Component

- `el-menu`
- `el-menu-item`
- `el-sub-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gICAgICAgIG1lbnVEYXRhOiBbXVxuIH0pXG5nZXRIb21lTWVudSgpXG5mdW5jdGlvbiBnZXRIb21lTWVudSAoKSB7XG4gICAgICAgIGNvbnNvbGUubG9nKDIpXG4gICAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICAgICAgZGF0YS5tZW51RGF0YSA9IFt7IGlkOiAyNCwgbmFtZTogJ+mmlumhtScsIHVybDogJy9zaGFyZS9ob21lL2luZGV4JywgaWNvblVybDogbnVsbCwgbGV2ZWw6IG51bGwsIHNvcnQ6IDEsIHBhcmVudElkOiBudWxsLCBwb3NpdGlvbjogbnVsbCwgaXNOZXdNZW51OiBudWxsLCBpc1Nob3c6IG51bGwsIGNyZWF0b3I6IG51bGwsIGNyZWF0ZVRpbWU6IG51bGwsIHVwZGF0ZVRpbWU6IG51bGwsIHBhcmVudE5hbWU6IG51bGwsIGNoaWxkcmVuOiBudWxsIH0sIHsgaWQ6IDMyLCBuYW1lOiAn6Kej5Yaz5pa55qGIJywgdXJsOiAnJywgaWNvblVybDogbnVsbCwgbGV2ZWw6IG51bGwsIHNvcnQ6IDIsIHBhcmVudElkOiBudWxsLCBwb3NpdGlvbjogbnVsbCwgaXNOZXdNZW51OiBudWxsLCBpc1Nob3c6IG51bGwsIGNyZWF0b3I6IG51bGwsIGNyZWF0ZVRpbWU6IG51bGwsIHVwZGF0ZVRpbWU6IG51bGwsIHBhcmVudE5hbWU6IG51bGwsIGNoaWxkcmVuOiBbeyBpZDogMzUsIG5hbWU6ICfkuqfmlZnono3lkIgnLCB1cmw6ICcvc2hhcmUvaG9tZS9wcm9kdWN0aW9uRWR1JywgaWNvblVybDogbnVsbCwgbGV2ZWw6IG51bGwsIHNvcnQ6IDEsIHBhcmVudElkOiAzMiwgcG9zaXRpb246IG51bGwsIGlzTmV3TWVudTogbnVsbCwgaXNTaG93OiBudWxsLCBjcmVhdG9yOiBudWxsLCBjcmVhdGVUaW1lOiBudWxsLCB1cGRhdGVUaW1lOiBudWxsLCBwYXJlbnROYW1lOiBudWxsLCBjaGlsZHJlbjogbnVsbCB9LCB7IGlkOiAzNCwgbmFtZTogJ+S4k+S4muW7uuiuvicsIHVybDogJy9zaGFyZS9ob21lL3Byb2Zlc3Npb25hbCcsIGljb25Vcmw6IG51bGwsIGxldmVsOiBudWxsLCBzb3J0OiAyLCBwYXJlbnRJZDogMzIsIHBvc2l0aW9uOiBudWxsLCBpc05ld01lbnU6IG51bGwsIGlzU2hvdzogbnVsbCwgY3JlYXRvcjogbnVsbCwgY3JlYXRlVGltZTogbnVsbCwgdXBkYXRlVGltZTogbnVsbCwgcGFyZW50TmFtZTogbnVsbCwgY2hpbGRyZW46IG51bGwgfV0gfSwgeyBpZDogMjEsIG5hbWU6ICfpnIDmsYLkuK3lv4MnLCB1cmw6ICcvc2hhcmUvaG9tZS9kZW1hbmRDZW50ZXInLCBpY29uVXJsOiBudWxsLCBsZXZlbDogbnVsbCwgc29ydDogMywgcGFyZW50SWQ6IG51bGwsIHBvc2l0aW9uOiBudWxsLCBpc05ld01lbnU6IG51bGwsIGlzU2hvdzogbnVsbCwgY3JlYXRvcjogbnVsbCwgY3JlYXRlVGltZTogbnVsbCwgdXBkYXRlVGltZTogbnVsbCwgcGFyZW50TmFtZTogbnVsbCwgY2hpbGRyZW46IG51bGwgfSwgeyBpZDogNDAsIG5hbWU6ICfotYTmupDkuK3lv4MnLCB1cmw6ICcvc2hhcmUvaG9tZS9yZXNvdXJjZS9yZXNvdXJjZUNlbnRlcicsIGljb25Vcmw6IG51bGwsIGxldmVsOiBudWxsLCBzb3J0OiAzLCBwYXJlbnRJZDogbnVsbCwgcG9zaXRpb246IG51bGwsIGlzTmV3TWVudTogbnVsbCwgaXNTaG93OiBudWxsLCBjcmVhdG9yOiBudWxsLCBjcmVhdGVUaW1lOiBudWxsLCB1cGRhdGVUaW1lOiBudWxsLCBwYXJlbnROYW1lOiBudWxsLCBjaGlsZHJlbjogbnVsbCB9LCB7IGlkOiAyNywgbmFtZTogJ+aWsOmXu+WKqOaAgScsIHVybDogJy9zaGFyZS9ob21lL25ld3NJbmZvJywgaWNvblVybDogbnVsbCwgbGV2ZWw6IG51bGwsIHNvcnQ6IDUsIHBhcmVudElkOiBudWxsLCBwb3NpdGlvbjogbnVsbCwgaXNOZXdNZW51OiBudWxsLCBpc1Nob3c6IG51bGwsIGNyZWF0b3I6IG51bGwsIGNyZWF0ZVRpbWU6IG51bGwsIHVwZGF0ZVRpbWU6IG51bGwsIHBhcmVudE5hbWU6IG51bGwsIGNoaWxkcmVuOiBudWxsIH0sIHsgaWQ6IDI4LCBuYW1lOiAn5YWz5LqO5oiR5LusJywgdXJsOiAnL3NoYXJlL2hvbWUvYWJvdXQvaW50cm9kdWN0aW9uJywgaWNvblVybDogbnVsbCwgbGV2ZWw6IG51bGwsIHNvcnQ6IDYsIHBhcmVudElkOiBudWxsLCBwb3NpdGlvbjogbnVsbCwgaXNOZXdNZW51OiBudWxsLCBpc1Nob3c6IG51bGwsIGNyZWF0b3I6IG51bGwsIGNyZWF0ZVRpbWU6IG51bGwsIHVwZGF0ZVRpbWU6IG51bGwsIHBhcmVudE5hbWU6IG51bGwsIGNoaWxkcmVuOiBudWxsIH1dXG4gICAgICAgIH0sIDUwMDApXG4gICAgICAgIC8vIFN5c3RlbVNlcnZpY2VBcGkuZ2V0SG9tZU1lbnUoe30pLnRoZW4ocmVzID0+IHtcbiAgICAgICAgLy8gICAgIGNvbnNvbGUubG9nKDMpXG4gICAgICAgIC8vICAgICBpZiAocmVzLnN0YXR1cyA9PT0gMCkge1xuICAgICAgICAvLyAgICAgICAgIGRhdGEubWVudURhdGEgPSByZXMuZGF0YVxuICAgICAgICAvLyAgICAgfVxuICAgICAgICAvLyB9KVxuICAgICAgICBjb25zb2xlLmxvZyg0KVxuICAgIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZWwtbWVudVxuICAgICAgICAgICAgOmRlZmF1bHQtYWN0aXZlPVwicGF0aFwiXG4gICAgICAgICAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgICAgICAgICBtZW51LXRyaWdnZXI9XCJob3ZlclwiXG4gICAgICAgICAgICA6dW5pcXVlLW9wZW5lZD1cInRydWVcIlxuICAgICAgICAgICAgcm91dGVyPlxuICAgICAgICAgICAgPHRlbXBsYXRlIHYtZm9yPVwiaXRlbSBpbiBkYXRhLm1lbnVEYXRhXCIgdi1iaW5kOmtleT1cIml0ZW0uaWRcIj5cbiAgICAgICAgICAgICAgICA8ZWwtc3ViLW1lbnUgY2xhc3M9XCJlbC1zdWItbWVudV90aXRsZV9jdXN0b21pemVcIiB2LWlmPVwiaXRlbVsnY2hpbGRyZW4nXVwiIDppbmRleD1cIml0ZW1bJ2lkJ10gKyAnJ1wiPlxuICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3tpdGVtWyduYW1lJ119fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBjbGFzcz1cImVsLXN1Yi1tZW51LWNoaWxk4oCUY3VzdG9taXplXCIgdi1mb3I9XCJjaGlsZCBpbiBpdGVtWydjaGlsZHJlbiddXCIgdi1iaW5kOmtleT1cImNoaWxkWydpZCddXCIgOmluZGV4PVwiY2hpbGRbJ3VybCddXCI+e3tjaGlsZFsnbmFtZSddfX08L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICAgICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gdi1lbHNlIHYtYmluZDprZXk9XCJpdGVtWydpZCddXCIgOmluZGV4PVwiaXRlbVsndXJsJ11cIj57e2l0ZW1bJ25hbWUnXX19PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLW1lbnU+XG5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

请求后台接口返回数据循环渲染失败

### What is Expected?

正常

### What is actually happening?

失败

### Additional comments

_(empty)_

初始化的时候应该吧菜单全部加载出来，现在只有三个点，应该是父容器的宽度计算错误，调整浏览器的大小，页面重新布局之后，菜单才会完整显示出来

**Comment by faitsse** [comment]
我用的方案是加一个 v-if, v-if="data.menuData.length", 可以解决问题。

**Comment by ye1016233531** [comment]
同样问题

**Comment by xiaoxian521** [comment]
`ellipsis`是一个新属性，默认开启。不需要的话设置成`false`即可
