### ISSUE TITLE
[Bug Report] [select] Playground 中使用 el-select，预览出现报错

### ISSUE THREAD

**Issue by ChasenTsai** [element-plus/element-plus#7061]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/99.0.4844.84 / win10 21H2`
- Build Tool: `Other`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0PjwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbjEgXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

打开 element-plus.run 新建一个 playground，输入如下代码
```vue
<template>
  <el-select></el-select>
</template>

<script setup>
1 
</script>
```
此时预览刷新，正常显示一个 select
然后在 script 中做任意修改，比如在 '1' 后面加个空格
此时预览刷新，报错如下：
```
Uncaught (in promise): Cannot read properties of null (reading 'emitsOptions')
```
再次做任意修改，比如把刚加的空格去掉
此时预览刷新，报错如下：
```
Cannot read properties of null (reading 'type')
```

### What is Expected?

预览不应该有报错

### What is actually happening?

分别报错找不到属性 'emitsOptions' 和 'type'

### Additional comments

此问题是在浏览 el-select 文档时候发现的，有可能也出现在其他组件

**Comment by lvliming** [comment]
<template>
  <el-input
    v-model="input"
    placeholder="Please input"
    :formatter="(value) => `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')"
    :parser="(value) => value.replace(/\$\s?|(,*)/g, '')"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
const input = ref('')
</script>
