### ISSUE TITLE
[Bug Report] [Build] vite 打包报错 Package subpath './package.json' is not defined by "exports" in /root/workspace/vue-salesnet-front_pu0J/node_modules/element-pluspackage.json

### ISSUE THREAD

**Issue by barry1102** [element-plus/element-plus#7062]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.8`
- Browser / OS: `Google Chrome 版本 100.0.4896.75（正式版本） (x86_64)`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/barry1102/element-plus-)

### Steps to reproduce

npm run build:test

### What is Expected?

不报错，正常打包

### What is actually happening?

打包报错
Package subpath './package.json' is not defined by "exports" in /root/workspace/vue-salesnet-front_pu0J/node_modules/element-pluspackage.json

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
无法复现，请确保仓库是否正确
