### ISSUE TITLE
[Bug Report] [Docs] can not find this file '../../../i18n/pages/resource.json' by .vitepress/vitepress/components/globals/resource.vue

### ISSUE THREAD

**Issue by huangd-d** [element-plus/element-plus#7078]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

pnpm run docs:build

### What is Expected?

可以正确打包文档。 内网开发 没办法使用在线文档

### What is actually happening?

Cannot find module '../../../i18n/pages/resource.json' or its corresponding type declarations

### Additional comments

不着急处理 还有其它版本文档可用。 有空麻烦更改下

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/discussions/7230

**Comment by sxzz** [comment]
i18n 的错误无法复现，可以尝试运行 `pnpm run docs:gen-locale`。
