### ISSUE TITLE
[Bug Report] [Docs] [loading] 窄宽度时，loading层会遮挡左侧菜单

### ISSUE THREAD

**Issue by ziloen** [element-plus/element-plus#7085]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Firefox 99  / Win10`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/loading.html)

### Steps to reproduce

窄宽度时，打开文档`Loading加载`组件页，打开左侧菜单

### What is Expected?

菜单在最上层

### What is actually happening?

Loading遮罩层在最上层

### Additional comments

![image](https://user-images.githubusercontent.com/34268416/162615018-7ab85bb2-19a5-4cd5-ab8b-4fe4595347d6.png)

**Comment by chenxch** [comment]
fixed.
