### ISSUE TITLE
[Bug Report] [Component] [input-number] el-input-number步进翻倍

### ISSUE THREAD

**Issue by ChenSunMoon** [element-plus/element-plus#7102]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `Edge 100.0.1185.29 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

点击基础用法种的"+"按钮

### What is Expected?

值数变成2

### What is actually happening?

值变成3

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
他使用了step属性哦
