### ISSUE TITLE
[Bug Report] [Component] [Style] [color-picker] 颜色选择器右侧 样式错误

### ISSUE THREAD

**Issue by xiangkunzhang** [element-plus/element-plus#7103]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Edg/100.0.1185.29/Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1jb2xvci1ibG9ja1wiPlxuICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPldpdGggZGVmYXVsdCB2YWx1ZTwvc3Bhbj5cbiAgICA8ZWwtY29sb3ItcGlja2VyIHYtbW9kZWw9XCJjb2xvcjFcIiAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImRlbW8tY29sb3ItYmxvY2tcIj5cbiAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5XaXRoIG5vIGRlZmF1bHQgdmFsdWU8L3NwYW4+XG4gICAgPGVsLWNvbG9yLXBpY2tlciB2LW1vZGVsPVwiY29sb3IyXCIgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBjb2xvcjEgPSByZWYoJyM0MDlFRkYnKVxuY29uc3QgY29sb3IyID0gcmVmKClcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1jb2xvci1ibG9jayB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIG1hcmdpbi1ib3R0b206IDE2cHg7XG59XG4uZGVtby1jb2xvci1ibG9jayAuZGVtb25zdHJhdGlvbiB7XG4gIG1hcmdpbi1yaWdodDogMTZweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

PlayGround 中的 示例代码已经出现此问题

### What is Expected?

和之前版本相同样式

### What is actually happening?

当前为竖条显示 多种颜色

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed #7113
