### ISSUE TITLE
[Bug Report] [Component] el-dialog 和 el-drawer中存在多个el-select时，el-select的z-index会被el-dialog 或 el-drawer的z-index覆盖

### ISSUE THREAD

**Issue by hoowhoami** [element-plus/element-plus#7106]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-drawer`
- `el-dialog`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9wZW5EcmF3ZXJcIj5PcGVuIGRyYXdlcjwvZWwtYnV0dG9uPlxuICA8ZWwtZHJhd2VyIHYtbW9kZWw9XCJ2aXNpYmxlXCI+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICA6ZGlzYWJsZWQ9XCJpdGVtLmRpc2FibGVkXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpkaXNhYmxlZD1cIml0ZW0uZGlzYWJsZWRcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmRpc2FibGVkPVwiaXRlbS5kaXNhYmxlZFwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICA6ZGlzYWJsZWQ9XCJpdGVtLmRpc2FibGVkXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPC9lbC1kcmF3ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gICAgZGlzYWJsZWQ6IHRydWUsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjYnLFxuICAgIGxhYmVsOiAnT3B0aW9uNicsXG4gIH1cbl1cblxuY29uc3Qgb3BlbkRyYXdlciA9ICgpID0+IHtcbiAgdmlzaWJsZS52YWx1ZSA9IHRydWUgXG59XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

点击按钮打开抽屉，关闭抽屉，再次打开抽屉即可复现。

### What is Expected?

抽屉内的下拉框能正常使用。

### What is actually happening?

抽屉内的下拉框无法正常使用。

### Additional comments

经测试，el-dialog中下拉框组件也有同样的问题。

**Comment by RexSheng** [comment]
2.1.9版本dialog中的select下拉框z-index有问题，我们项目已临时加入:teleported='false'来缓解

**Comment by chenxch** [comment]
#7115  
The problem has been fixed, please update to version 2.1.10.
