### ISSUE TITLE
[Bug Report] [Component] [upload] can`t change file in before-upload

### ISSUE THREAD

**Issue by Cccshine** [element-plus/element-plus#7111]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome 99.0.4844.84（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3Qgc2VsZWN0ZWRTaXplID0gcmVmKDApXG5jb25zdCBjb21wcmVzc2VkU2l6ZSA9IHJlZigwKVxuY29uc3QgdXBsb2FkZWRTaXplID0gcmVmKDApXG5jb25zdCBoYW5kbGVCZWZvcmVVcGxvYWQgPSBhc3luYyAodXBsb2FkRmlsZSkgPT4ge1xuICBzZWxlY3RlZFNpemUudmFsdWUgPSB1cGxvYWRGaWxlLnNpemVcbiAgIGF3YWl0IGNvbXByZXNzSW1hZ2UodXBsb2FkRmlsZSlcbiAgICAgIC50aGVuKChiYXNlNjRDb2RlcykgPT4ge1xuICAgICAgICB1cGxvYWRGaWxlID0gbmV3IEZpbGUoW2NvbnZlcnRCYXNlNjRVcmxUb0Jsb2IoYmFzZTY0Q29kZXMpXSwgdXBsb2FkRmlsZS5uYW1lLCB7XG4gICAgICAgICAgdHlwZTogdXBsb2FkRmlsZS50eXBlLFxuICAgICAgICB9KVxuICAgICAgfSlcbiAgICAgIC5jYXRjaCgoZXJyKSA9PiB7XG4gICAgICAgIGNvbnNvbGUubG9nKGVycilcbiAgICAgIH0pXG4gIGNvbXByZXNzZWRTaXplLnZhbHVlID0gdXBsb2FkRmlsZS5zaXplXG4gIHJldHVybiBQcm9taXNlLnJlc29sdmUodXBsb2FkRmlsZSlcbn1cbmNvbnN0IG9uRXJyb3IgPSAocmVzLCByYXdGaWxlKT0+e1xuICB1cGxvYWRlZFNpemUudmFsdWUgPSByYXdGaWxlLnNpemVcbn1cbmZ1bmN0aW9uIGNvbXByZXNzSW1hZ2UoZmlsZSwgY29uZmlnKSB7XG4gIGxldCBjb21wcmVzc0NvbmZpZyA9IE9iamVjdC5hc3NpZ24oXG4gICAge30sXG4gICAge1xuICAgICAgcXVhbGl0eTogMC41LFxuICAgICAgLy8g5byA5aeL5Y6L57yp55qE6ZiI5YC8XG4gICAgICB0aHJlc2hvbGQ6IDAuNSAqIDEwMjQgKiAxMDI0LFxuICAgIH0sXG4gICAgY29uZmlnIHx8IHt9XG4gIClcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAvLyBGaWxlUmVhZGVyIOWvueixoeWFgeiuuFdlYuW6lOeUqOeoi+W6j+W8guatpeivu+WPluWtmOWCqOWcqOeUqOaIt+iuoeeul+acuuS4iueahOaWh+S7tueahOWGheWuue+8jOeUqCBGaWxlIOaIliBCbG9iIOWvueixoeaMh+Wumuimgeivu+WPlueahOaWh+S7tuaIluaVsOaNrlxuICAgIGxldCBmaWxlUmVhZGVyID0gbmV3IEZpbGVSZWFkZXIoKVxuICAgIC8vIOW8gOWni+ivu+WPluaMh+WumueahOaWh+S7tuS4reeahOWGheWuueOAguS4gOaXpuWujOaIkO+8jHJlc3VsdOWxnuaAp+S4reWwhuWMheWQq+S4gOS4qmRhdGE6IFVSTOagvOW8j+eahEJhc2U2NOWtl+espuS4suS7peihqOekuuaJgOivu+WPluaWh+S7tueahOWGheWuueOAglxuICAgIGZpbGVSZWFkZXIucmVhZEFzRGF0YVVSTChmaWxlKVxuICAgIGZpbGVSZWFkZXIub25sb2FkID0gKCkgPT4ge1xuICAgICAgbGV0IGZpbGVSZXN1bHQgPSBmaWxlUmVhZGVyLnJlc3VsdFxuICAgICAgaWYgKGZpbGUuc2l6ZSA8IGNvbXByZXNzQ29uZmlnLnRocmVzaG9sZCkge1xuICAgICAgICByZXR1cm4gcmVzb2x2ZShmaWxlUmVzdWx0KVxuICAgICAgfVxuICAgICAgbGV0IHBpY3R1cmUgPSBuZXcgSW1hZ2UoKVxuICAgICAgcGljdHVyZS5zcmMgPSBmaWxlUmVzdWx0XG4gICAgICBwaWN0dXJlLm9ubG9hZCA9ICgpID0+IHtcbiAgICAgICAgLy/pu5jorqTljovnvKnlkI7lm77niYfop4TmoLxcbiAgICAgICAgbGV0IHF1YWxpdHkgPSAxXG4gICAgICAgIGxldCB3ID0gcGljdHVyZS53aWR0aFxuICAgICAgICBsZXQgaCA9IHBpY3R1cmUuaGVpZ2h0XG4gICAgICAgIGxldCBzY2FsZSA9IHcgLyBoXG4gICAgICAgIC8v5a6e6ZmF6KaB5rGCXG4gICAgICAgIHcgPSBjb21wcmVzc0NvbmZpZy53aWR0aCB8fCB3XG4gICAgICAgIGggPSBjb21wcmVzc0NvbmZpZy5oZWlnaHQgfHwgdyAvIHNjYWxlXG4gICAgICAgIGlmIChjb21wcmVzc0NvbmZpZy5xdWFsaXR5ICYmIGNvbXByZXNzQ29uZmlnLnF1YWxpdHkgPiAwICYmIGNvbXByZXNzQ29uZmlnLnF1YWxpdHkgPD0gMSkge1xuICAgICAgICAgIHF1YWxpdHkgPSBjb21wcmVzc0NvbmZpZy5xdWFsaXR5XG4gICAgICAgIH1cbiAgICAgICAgLy/nlJ/miJBjYW52YXNcbiAgICAgICAgbGV0IGNhbnZhcyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2NhbnZhcycpXG4gICAgICAgIGxldCBjdHggPSBjYW52YXMuZ2V0Q29udGV4dCgnMmQnKVxuICAgICAgICBjYW52YXMud2lkdGggPSB3XG4gICAgICAgIGNhbnZhcy5oZWlnaHQgPSBoXG4gICAgICAgIC8vIOeUu+WbvlxuICAgICAgICBjdHguZHJhd0ltYWdlKHBpY3R1cmUsIDAsIDAsIHcsIGgpXG4gICAgICAgIC8vIOWbnuiwg+WHveaVsOi/lOWbnmJhc2U2NOeahOWAvFxuICAgICAgICByZXNvbHZlKGNhbnZhcy50b0RhdGFVUkwoJ2ltYWdlL2pwZWcnLCBxdWFsaXR5KSlcbiAgICAgIH1cbiAgICAgIHBpY3R1cmUub25lcnJvciA9ICgpID0+IHtcbiAgICAgICAgcmVqZWN0KClcbiAgICAgIH1cbiAgICB9XG4gIH0pXG59XG5cbi8qKlxuICogYmFzZTY06L2sYmxvYlxuICogQHBhcmFtIHtzdHJpbmd9IGJhc2U2NCBiYXNlNjQgdXJsXG4gKiBAcmV0dXJucyBibG9iXG4gKi9cbmZ1bmN0aW9uIGNvbnZlcnRCYXNlNjRVcmxUb0Jsb2IoYmFzZTY0KSB7XG4gIGxldCBiYXNlNjRBcnIgPSBiYXNlNjQuc3BsaXQoJywnKSxcbiAgICAvLyDpnZ7otKrlqarmqKHlvI/vvIzljLnphY3mnIDnn63nmoTnu5PmnpxcbiAgICBtaW1lID0gYmFzZTY0QXJyWzBdLm1hdGNoKC86KC4qPyk7LylbMV0sXG4gICAgLy8gYXRvYigpIOaWueazleeUqOS6juino+eggeS9v+eUqCBiYXNlLTY0IOe8lueggeeahOWtl+espuS4siAg57yW56CB55SoYnRvYSgpXG4gICAgYnN0ciA9IGF0b2IoYmFzZTY0QXJyWzFdKSxcbiAgICBsZW4gPSBic3RyLmxlbmd0aCxcbiAgICAvLyDooajnpLrkuIDkuKo45L2N5peg56ym5Y+35pW05Z6L5pWw57uEXG4gICAgdThBcnIgPSBuZXcgVWludDhBcnJheShsZW4pXG4gIHdoaWxlIChsZW4tLSkge1xuICAgIC8vIGNoYXJDb2RlQXQg6L+U5ZuedW5pY29kZeeggVxuICAgIHU4QXJyW2xlbl0gPSBic3RyLmNoYXJDb2RlQXQobGVuKVxuICB9XG4gIHJldHVybiBuZXcgQmxvYihbdThBcnJdLCB7IHR5cGU6IG1pbWUgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC11cGxvYWRcbiAgICBjbGFzcz1cInVwbG9hZC1kZW1vXCJcbiAgICBhY3Rpb249XCJodHRwczovL2pzb25wbGFjZWhvbGRlci50eXBpY29kZS5jb20vcG9zdHMvXCJcbiAgICBzaG93LWZpbGUtbGlzdFxuICAgIDpiZWZvcmUtdXBsb2FkPVwiaGFuZGxlQmVmb3JlVXBsb2FkXCJcbiAgICA6b24tZXJyb3I9XCJvbkVycm9yXCJcbiAgPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5DbGljayB0byB1cGxvYWQ8L2VsLWJ1dHRvbj5cbiAgPC9lbC11cGxvYWQ+XG4gIDxkaXY+6YCJ5Lit55qE5Zu+54mH55qE5aSn5bCP77yaIHt7c2VsZWN0ZWRTaXplfX08L2Rpdj5cbiAgPGRpdj7liY3nq6/ljovnvKnlkI7nmoTlm77niYfnmoTlpKflsI/vvJoge3tjb21wcmVzc2VkU2l6ZX19PC9kaXY+XG4gIDxkaXY+5LiK5Lyg55qE5Zu+54mH55qE5aSn5bCP77yaIHt7dXBsb2FkZWRTaXplfX08L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

1. select a file
2. do something in before-upload, such as compress the file
3. upload

### What is Expected?

the file will be compressed

### What is actually happening?

the file not be compressed

### Additional comments

in the source code - element-plus/es/components/upload/src/upload-content2.mjs - line 44-73

```
const upload = async (rawFile) => {
      inputRef.value.value = "";
      if (!props.beforeUpload) {
        return doUpload(rawFile);
      }
      let hookResult;
      try {
        hookResult = await props.beforeUpload(rawFile);
      } catch (e) {
        hookResult = false;
      }
      if (hookResult === false) {
        props.onRemove(rawFile);
        return;
      }
      let file = rawFile;
      if (hookResult instanceof Blob) {
        if (hookResult instanceof File) {
          file = hookResult;
        } else {
          file = new File([hookResult], rawFile.name, {
            type: rawFile.type
          });
        }
        for (const key of Object.keys(rawFile)) {
          file[key] = rawFile[key];
        }
      }
      doUpload(rawFile);
    };
```
variable file has defined and resolved, but not used

**Comment by btea** [comment]
fixed #8079
