### ISSUE TITLE
[Bug Report] [Component] [dialog, popover] el-dialog 关闭再打开会遮挡 el-popover

### ISSUE THREAD

**Issue by ziloen** [element-plus/element-plus#7112]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Firefox 99.0 / Windows 10 x64`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgc2hvdyA9IHJlZihmYWxzZSlcbmNvbnN0IHNob3dEaWFsb2cgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInNob3dEaWFsb2cgPSB0cnVlXCI+5omT5byA5by556qXPC9lbC1idXR0b24+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cInNob3dEaWFsb2dcIiBAY2xvc2U9XCJzaG93ID0gZmFsc2VcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInNob3cgPSBmYWxzZVwiPuWFs+mXrXBvcG92ZXI8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtcG9wb3ZlciB2LW1vZGVsOnZpc2libGU9XCJzaG93XCIgdHJpZ2dlcj1cImNsaWNrXCI+XG4gICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInNob3cgPSB0cnVlXCI+5omT5byAcG9wb3ZlcjwvZWwtYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxkaXY+cG9wb3ZlcuWGheWuuTwvZGl2PlxuICAgIDwvZWwtcG9wb3Zlcj5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

版本2.1.9，打开dialog，关闭dialog，再打开dialog

### What is Expected?

popover弹出层在dialog上

### What is actually happening?

popover弹出层被dialog遮挡

### Additional comments

![element-plus](https://user-images.githubusercontent.com/34268416/162734469-f461023a-4267-435a-aaa0-7f66e92f2f92.gif)

**Comment by chenxch** [comment]
#7012  It should be caused by this change. My consideration is not comprehensive enough. You can use the zindex attribute to temporarily solve this problem.

**Comment by Half-A-Turnip** [comment]
我也遇到同样的问题

**Comment by chenxch** [comment]
The problem has been fixed, please update to version 2.1.10.
