### ISSUE TITLE
[Bug Report] [Component] [select, dialog] 弹窗和选择框同时使用，第二次打开弹窗选择框内容z-index小于弹窗无法看到内容

### ISSUE THREAD

**Issue by myhzw** [element-plus/element-plus#7124]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.2`
- Element Plus Version: `2.1.9`
- Browser / OS: `window10`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-dialog`

### Reproduction Link

[CodePen](https://codepen.io/myhzw/pen/bGajQmg)

### Steps to reproduce

第二次打开弹窗选择框内容，弹窗的z-index发生改变，导致选择框z-index小于弹窗无法看到内容

### What is Expected?

正常显示

### What is actually happening?

弹窗和选择框同时使用，第二次打开弹窗选择框内容z-index小于弹窗无法看到内容

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/31983596/162933908-5b0f8b12-d0f9-4044-a4c1-504969516dc5.png)
![image](https://user-images.githubusercontent.com/31983596/162933961-e15fcaff-7c87-4081-8040-7a262314b3b0.png)

**Comment by willove** [comment]
我也遇到了。。默默把版本退到了2.1.8

**Comment by myhzw** [comment]
只有回退了，每次打开弹窗的z-index都会增加

**Comment by JackieCheung** [comment]
same case

**Comment by huzedong2015** [comment]
2.1.9好几个BUG了

**Comment by JackieCheung** [comment]
> 2.1.9好几个BUG了

请回退到2.1.8 😏

**Comment by Lovercz** [comment]
我也有这个问题 ，还有el-form 表单 打包后类名丢失， 比如el-form--default 子集第一个div 开发环境有el-form-item--default 打包后却没有这个类名

**Comment by Cheerwhy** [comment]
马上回滚版本

**Comment by Alanscut** [comment]
出问题的 pr #7012

**Comment by hanfc** [comment]
DateTimePicker 日期时间选择器 也有这个问题，发现是被弹窗挡住了，显示在dialog下面，层级问题。。。

**Comment by Alanscut** [comment]
> DateTimePicker 日期时间选择器 也有这个问题，发现是被弹窗挡住了，显示在dialog下面，层级问题。。。

因为改动的是内部的popper组件，绝大部分有弹出层的组件应该都有这个问题

**Comment by Alanscut** [comment]
@chenxch @JeremyWuuuuu 
look at this issue ,it seems still have problem after merge pr #7115

**Comment by Alanscut** [comment]
linked pr #7115

**Comment by chenxch** [comment]
The problem has been fixed, please update to version 2.1.10.
