### ISSUE TITLE
[Bug Report] [Component] [input] the 'padding-left' calculation of large size input is not correct in v2.1.9

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7125]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.9`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/input.html#sizes)

### Steps to reproduce

see the 'padding-left' of large size input with prefix-icon

### What is Expected?

the 'padding-left' of large size input displays normal as v2.1.8

### What is actually happening?

the 'padding-left' calculation of large size input is not correct

### Additional comments

_(empty)_

v2.1.8
![image](https://user-images.githubusercontent.com/31252046/162941943-f840a780-1b23-4161-9e32-71e9b3d54f0a.png)

v2.1.9
![image](https://user-images.githubusercontent.com/31252046/162941560-d771aace-e7bf-4fbe-bb95-ef36cf15d69b.png)

**Comment by TengFeiHao** [comment]
现在的样式看的我郁闷，升级了一下样式都不对l [汗]

**Comment by JackieCheung** [comment]
> 

haha~

**Comment by JackieCheung** [comment]
> 现在的样式看的我郁闷，升级了一下样式都不对l [汗]

😄
