### ISSUE TITLE
[Bug Report] [Component] [tree-v2] tree-v2组件能否支持下传入itemSize参数

### ISSUE THREAD

**Issue by ajaxlinux1234** [element-plus/element-plus#7139]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.9`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/tree/dev/packages/components/tree-v2)

### Steps to reproduce

none

### What is Expected?

none

### What is actually happening?

none

### Additional comments

_(empty)_

**Comment by lian1998** [comment]
兄弟我找到一个很好的解决办法
ElTreeV2.setup1 = ElTreeV2.setup;
ElTreeV2.setup = (props, ctx) => {
    const obj = ElTreeV2.setup1(props, ctx);
    obj['itemSize'] = ctx.attrs['item-size']
    return obj;
};

**Comment by ajaxlinux1234** [comment]
@lian1998 666👍🏻

**Comment by YujiaCheng1996** [comment]
> 兄弟我找到一个很好的解决办法 ElTreeV2.setup1 = ElTreeV2.setup; ElTreeV2.setup = (props, ctx) => { const obj = ElTreeV2.setup1(props, ctx); obj['itemSize'] = ctx.attrs['item-size'] return obj; };

新版换setup script直接const itemSize = 26了，已经不能这么操作了。。。

**Comment by tangshichun** [comment]
> > 兄弟我找到一个很好的解决办法 ElTreeV2.setup1 = ElTreeV2.setup; ElTreeV2.setup = (props, ctx) => { const obj = ElTreeV2.setup1(props, ctx); obj['itemSize'] = ctx.attrs['item-size'] return obj; };
> 
> 新版换setup script直接const itemSize = 26了，已经不能这么操作了。。。

确实，这丫的直接给写死了，咋整....

**Comment by Jiaqi-qi** [comment]
> > > 兄弟我找到一个很好的解决办法 ElTreeV2.setup1 = ElTreeV2.setup; ElTreeV2.setup = (props, ctx) => { const obj = ElTreeV2.setup1(props, ctx); obj['itemSize'] = ctx.attrs['item-size'] return obj; };
> > 
> > 
> > 新版换setup script直接const itemSize = 26了，已经不能这么操作了。。。
> 
> 确实，这丫的直接给写死了，咋整....

请问现在找到解决方案了吗，我也碰到这问题

**Comment by tangshichun** [comment]
> > > > 兄弟我找到一个很好的解决办法 ElTreeV2.setup1 = ElTreeV2.setup; ElTreeV2.setup = (props, ctx) => { const obj = ElTreeV2.setup1(props, ctx); obj['itemSize'] = ctx.attrs['item-size'] return obj; };
> > > 
> > > 
> > > 新版换setup script直接const itemSize = 26了，已经不能这么操作了。。。
> > 
> > 
> > 确实，这丫的直接给写死了，咋整....
> 
> 请问现在找到解决方案了吗，我也碰到这问题

我最后没用这个东西，拿RecyclerScroller手撸了一个，看这架势一时半会他也不会改，实在不行就copy一份源码呗

**Comment by tolking** [comment]
This attribute has been supported since v2.2.33
