### ISSUE TITLE
[Bug Report] [Component] [select-v2] el-select-v2 v-model使用object时候，value-key无法使用

### ISSUE THREAD

**Issue by Coder-XiaoYi** [element-plus/element-plus#7140]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cImxhcmdlXCJcbiAgICB2YWx1ZS1rZXk9XCJpZFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbe1xuICBpZDogMSxcbiAgbmFtZTogJ2EnXG59LHtcbiAgaWQ6IDIsXG4gIG5hbWU6ICdiJ1xufSx7XG4gIGlkOjMsXG4gIG5hbWU6ICdjJ1xufV1cblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gaW5pdGlhbHMubWFwKChpdGVtLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBpdGVtLFxuICBsYWJlbDogaXRlbS5uYW1lLFxufSkpXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5leGFtcGxlLXNob3djYXNlIC5lbC1zZWxlY3QtdjIge1xuICBtYXJnaW4tcmlnaHQ6IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

如链接所示。

### What is Expected?

选择a时候，value应该为{id:1, name: 'a'},
选择b时候，value应该为{id:2, name: 'b'},
选择c时候，value应该为{id:3, name: 'c'}

### What is actually happening?

报错：Cannot read properties of undefined (reading 'toString')

### Additional comments

_(empty)_

**Comment by lanbin** [comment]
这个功能在v2.1.7及以下的版本没有问题, 从v2.1.8开始就有问题了.

[The exmaple of The Select Component with object value in Element Plus](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IHJlZihbXSlcbmNvbnN0IHNlbFJlc3VsdCA9IHJlZjxhbnk+KG51bGwpXG5cbm9wdGlvbnMudmFsdWUgPSBbXG4gIHtcbiAgICBpZDogMSwgbmFtZTogJzExMScsIHZhbHVlOiAndjExMSdcbiAgfSxcbiAge1xuICAgIGlkOiAyLCBuYW1lOiAnMTEyJywgdmFsdWU6ICd2MTEyJ1xuICB9LFxuICB7XG4gICAgaWQ6IDMsIG5hbWU6ICcxMTMnLCB2YWx1ZTogJ3YxMTMzJ1xuICB9LFxuICB7XG4gICAgaWQ6IDQsIG5hbWU6ICcxMTE0JywgdmFsdWU6ICd2MTExJ1xuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIFJldWxzdDoge3tzZWxSZXN1bHR9fVxuICA8L2Rpdj4gIFxuIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbFJlc3VsdFwiPlxuICAgIDxlbC1vcHRpb24gXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIFxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiIFxuICAgICAgOnZhbHVlPVwiaXRlbVwiPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by lanbin** [comment]
这个功能在v2.1.7及以下的版本没有问题, 从v2.1.8开始就有问题了.

[The exmaple of The Select Component with object value in Element Plus](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IHJlZihbXSlcbmNvbnN0IHNlbFJlc3VsdCA9IHJlZjxhbnk+KG51bGwpXG5cbm9wdGlvbnMudmFsdWUgPSBbXG4gIHtcbiAgICBpZDogMSwgbmFtZTogJzExMScsIHZhbHVlOiAndjExMSdcbiAgfSxcbiAge1xuICAgIGlkOiAyLCBuYW1lOiAnMTEyJywgdmFsdWU6ICd2MTEyJ1xuICB9LFxuICB7XG4gICAgaWQ6IDMsIG5hbWU6ICcxMTMnLCB2YWx1ZTogJ3YxMTMzJ1xuICB9LFxuICB7XG4gICAgaWQ6IDQsIG5hbWU6ICcxMTE0JywgdmFsdWU6ICd2MTExJ1xuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIFJldWxzdDoge3tzZWxSZXN1bHR9fVxuICA8L2Rpdj4gIFxuIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbFJlc3VsdFwiPlxuICAgIDxlbC1vcHRpb24gXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIFxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiIFxuICAgICAgOnZhbHVlPVwiaXRlbVwiPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by Alanscut** [comment]
@Coder-XiaoYi 
你好，这个问题是`value-key`配置不正确产生的，[正确示例](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cImxhcmdlXCJcbiAgICB2YWx1ZS1rZXk9XCJ2YWx1ZS5pZFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbe1xuICBpZDogMSxcbiAgbmFtZTogJ2EnXG59LHtcbiAgaWQ6IDIsXG4gIG5hbWU6ICdiJ1xufSx7XG4gIGlkOjMsXG4gIG5hbWU6ICdjJ1xufV1cblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gaW5pdGlhbHMubWFwKChpdGVtLCBpZHgpID0+ICh7XG4gIHZhbHVlOiBpdGVtLFxuICBsYWJlbDogaXRlbS5uYW1lLFxufSkpXG5jb25zb2xlLmxvZyhvcHRpb25zLnZhbHVlKVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtc2VsZWN0LXYyIHtcbiAgbWFyZ2luLXJpZ2h0OiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)
![image](https://user-images.githubusercontent.com/21104054/163533676-9d95db97-c87b-4612-ae81-d6ebd4168066.png)

**Comment by Alanscut** [comment]
> 这个功能在v2.1.7及以下的版本没有问题, 从v2.1.8开始就有问题了.
> 
> [The exmaple of The Select Component with object value in Element Plus](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IHJlZihbXSlcbmNvbnN0IHNlbFJlc3VsdCA9IHJlZjxhbnk+KG51bGwpXG5cbm9wdGlvbnMudmFsdWUgPSBbXG4gIHtcbiAgICBpZDogMSwgbmFtZTogJzExMScsIHZhbHVlOiAndjExMSdcbiAgfSxcbiAge1xuICAgIGlkOiAyLCBuYW1lOiAnMTEyJywgdmFsdWU6ICd2MTEyJ1xuICB9LFxuICB7XG4gICAgaWQ6IDMsIG5hbWU6ICcxMTMnLCB2YWx1ZTogJ3YxMTMzJ1xuICB9LFxuICB7XG4gICAgaWQ6IDQsIG5hbWU6ICcxMTE0JywgdmFsdWU6ICd2MTExJ1xuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIFJldWxzdDoge3tzZWxSZXN1bHR9fVxuICA8L2Rpdj4gIFxuIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbFJlc3VsdFwiPlxuICAgIDxlbC1vcHRpb24gXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiIFxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiIFxuICAgICAgOnZhbHVlPVwiaXRlbVwiPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

@lanbin 你好，请问你指的是什么问题呢，你提供的demo和[Coder-XiaoYi](https://github.com/Coder-XiaoYi)说的并不相同

**Comment by lanbin** [comment]
@Alanscut 你好. 在 > 2.1.7 的时候 select 选择一个option之后, 框里面无法显示我选中的值.

**Comment by lanbin** [comment]
@Alanscut 你好. 在 > 2.1.7 的时候 select 选择一个option之后, 框里面无法显示我选中的值.

**Comment by Alanscut** [comment]
应该是和这个issue #7141 提到的是同一个问题
