### ISSUE TITLE
[Bug Report] [Component] [date-picker] DatePicker components icon bug in 2.1.9! 日期选择器在2.1.9下icon图表和选择后日期文字会贴在一起重合！

### ISSUE THREAD

**Issue by lait233** [element-plus/element-plus#7142]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodePen](https://codepen.io/lait233/pen/wvpEqze)

### Steps to reproduce

```html
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/vue@3.2.31/dist/vue.global.prod.js"></script>
    <!-- import CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/element-plus@2.1.9/dist/index.css">
    <!-- import JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/element-plus@2.1.9/dist/locale/zh-cn.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/element-plus@2.1.9/dist/index.full.min.js"></script>
    <title>Element Plus demo</title>
  </head>
  <style>
        [v-cloak] {
          display: none; /*防止初次加载出现vue标签语法没被解析*/
      }
  </style>
  <body>
<!--   delete v-cloak   date-picker icon is ok!  -->
    <div id="app" v-cloak>
      
            <div class="block">
        <span class="demonstration">Month</span>
        <el-date-picker
          v-model="value2"
          type="month"
          placeholder="请选择月份"
        />
      </div>
      <el-button @click="dialogFormVisible = !dialogFormVisible">dialog DatePicker</el-button>
      
        <el-dialog v-model="dialogFormVisible" title="Shipping address">
    <el-form :model="form">
      <el-form-item label="Promotion name" :label-width="formLabelWidth">
        <el-input v-model="form.name" autocomplete="off" />
      </el-form-item>
      <el-form-item label="Zones" :label-width="formLabelWidth">
        <el-select v-model="form.region" placeholder="Please select a zone">
          <el-option label="Zone No.1" value="shanghai" />
          <el-option label="Zone No.2" value="beijing" />
        </el-select>
        <el-date-picker
          v-model="value2"
          type="month"
          placeholder="Pick a month"
        />
      </div>
      </el-form-item>
    </el-form>
    <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogFormVisible = false">Cancel</el-button>
        <el-button type="primary" @click="dialogFormVisible = false"
          >Confirm</el-button
        >
      </span>
    </template>
  </el-dialog>
      
    </div>
    <script>
      const App = {
        data() {
          return {
            value2: null,
            message: "Hello Element Plus",
            form:{},
            dialogFormVisible: false,
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus,{
    locale: ElementPlusLocaleZhCn,
});
      app.mount("#app");
    </script>
  </body>
</html>
```

### What is Expected?

Keep ICONS and text at a distance

### What is actually happening?

Icon and text overlap

### Additional comments
2.1.8 is ok!
在2.1.9版本中。日期选择组件如果首次加载没有展示出来或者父元素的display开始等于none.会导致图标和文字重合！
在弹出框一定会重合！（因为默认会display：none）

**Comment by lait233** [comment]
2.1.8 is ok!

**Comment by lait233** [comment]
![QQ20220413-142409](https://user-images.githubusercontent.com/31282366/163113395-6047e0a7-dd38-4cd6-b136-f8768f1ffd36.gif)

**Comment by ajw333** [comment]
同样的问题

**Comment by huzedong2015** [comment]
+1

**Comment by zcmk123** [comment]
https://github.com/element-plus/element-plus/commit/793ca8ae29e51675c6ee2b4a2b08cb9dea933a31
应该跟这个commit有关

**Comment by baiwusanyu-c** [comment]
> [793ca8a](https://github.com/element-plus/element-plus/commit/793ca8ae29e51675c6ee2b4a2b08cb9dea933a31) 应该跟这个commit有关，display none的元素貌似不好拿宽度，可能要clone一个节点渲染出来visibility hidden然后计算，但是这样是不是有点啰嗦了。。 @baiwusanyu-c

是的 因为修改了 padding 的添加方式 我的锅，我在另一个pr #7104 里做了修复，在预览上没有看见这个问题了，给各位造成困扰我很抱歉

**Comment by baiwusanyu-c** [comment]
我会排查一下具体原因，这边你可以先降级使用 @lait233

**Comment by zcmk123** [comment]
> > [793ca8a](https://github.com/element-plus/element-plus/commit/793ca8ae29e51675c6ee2b4a2b08cb9dea933a31) 应该跟这个commit有关，display none的元素貌似不好拿宽度，可能要clone一个节点渲染出来visibility hidden然后计算，但是这样是不是有点啰嗦了。。 @baiwusanyu-c
> 
> 是的 因为修改了 padding 的添加方式 我的锅，我在另一个pr #7104 里做了修复，在预览上没有看见这个问题了，给各位造成困扰我很抱歉

我看了一下 #7104 这个pr。。没感觉是能修复楼主提出的这个问题

**Comment by baiwusanyu-c** [comment]
> > > [793ca8a](https://github.com/element-plus/element-plus/commit/793ca8ae29e51675c6ee2b4a2b08cb9dea933a31) 应该跟这个commit有关，display none的元素貌似不好拿宽度，可能要clone一个节点渲染出来visibility hidden然后计算，但是这样是不是有点啰嗦了。。 @baiwusanyu-c
> > 
> > 
> > 是的 因为修改了 padding 的添加方式 我的锅，我在另一个pr #7104 里做了修复，在预览上没有看见这个问题了，给各位造成困扰我很抱歉
> 
> 我看了一下 #7104 这个pr。。没感觉是能修复楼主提出的这个问题，他说的case是display none之后再显示会出现这个问题

在新的提交里面我修改了方法调用顺序，在nextTick之后，应该能规避这个问题，但是我有完全复现楼主的环境，而是在sfc中测试的，另外我注意到主分支似乎已经回滚了之前commit代码，这个pr会不会最终合并也难说啦

**Comment by huzedong2015** [comment]
还有 dialog中 select 第二次打开后 会出现在弹出层下面

**Comment by ajw333** [comment]
@huzedong2015  我貌似也出现过这样的情况

**Comment by huzedong2015** [comment]
> @huzedong2015 我貌似也出现过这样的情况

https://github.com/element-plus/element-plus/issues/7124#issuecomment-1097711808这里

**Comment by JCAlways** [comment]
+1

**Comment by lait233** [comment]
2.1.10+ To solve~
2.1.10以上版本已解决
