### ISSUE TITLE
[Bug Report] [TypeScript] [All] pnpm 安装后 全局组件类型支持失效

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#7155]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.9`
- Browser / OS: `chrome 99`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

这个附件链接是无效，实际要在vs code复现
如果用npm安装是生效的，pnpm安装就不行
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["element-plus/global"]
  }
}

### What is Expected?

全局组件vs code能正确提示类型

### What is actually happening?

没有提示

### Additional comments

如果在.d.ts文件
/// <reference types="element-plus/global" /> 引入就可以了。

**Comment by sxzz** [comment]
请参考 https://github.com/sxzz/element-plus-best-practices 仓库
