### ISSUE TITLE
[Bug Report] [Component] [input] input padding bug

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#7157]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiIDptb2RlbD1cImZvcm1JbmxpbmVcIiBjbGFzcz1cImRlbW8tZm9ybS1pbmxpbmVcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQXBwcm92ZWQgYnlcIj5cbiAgICAgIDxlbC1pbnB1dCBjbGVhcmFibGUgdi1tb2RlbD1cImZvcm1JbmxpbmUudXNlclwiIHBsYWNlaG9sZGVyPVwiQXBwcm92ZWQgYnlcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCI+XG4gICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtSW5saW5lLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwiQWN0aXZpdHkgem9uZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib25TdWJtaXRcIj5RdWVyeTwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGZvcm1JbmxpbmUgPSByZWFjdGl2ZSh7XG4gIHVzZXI6ICcnLFxuICByZWdpb246ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

 Element Plus Playground 

### What is Expected?

行内表单 input 加入 clearable 会抖动

### What is actually happening?

样式正确

### Additional comments

拜托更新样式的时候多检查一下，出现好多次样式问题了

**Comment by gjfei** [comment]
![image](https://user-images.githubusercontent.com/33827314/163306318-f3ef45a1-b9c6-400c-a83d-1ee4e3c1aaaa.png)
![image](https://user-images.githubusercontent.com/33827314/163306355-603ed7af-085e-4466-b4c6-a48bdfa26b04.png)
![image](https://user-images.githubusercontent.com/33827314/163306389-b5e61f06-e41f-4c58-96e2-4b0cf7a7a942.png)
三个地方的量都没统一

**Comment by zhuyuanmin** [comment]
请问这个 bug 怎么还没有修复呀？[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiIDptb2RlbD1cImZvcm1JbmxpbmVcIiBjbGFzcz1cImRlbW8tZm9ybS1pbmxpbmVcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQXBwcm92ZWQgYnlcIj5cbiAgICAgIDxlbC1pbnB1dCBjbGVhcmFibGUgdi1tb2RlbD1cImZvcm1JbmxpbmUudXNlclwiIHBsYWNlaG9sZGVyPVwiQXBwcm92ZWQgYnlcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCI+XG4gICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtSW5saW5lLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwiQWN0aXZpdHkgem9uZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib25TdWJtaXRcIj5RdWVyeTwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGZvcm1JbmxpbmUgPSByZWFjdGl2ZSh7XG4gIHVzZXI6ICcnLFxuICByZWdpb246ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9) 训练场都还存在

**Comment by HeftyKoo** [comment]
Duplicate: #7287
