### ISSUE TITLE
[Bug Report] [Docs] [pagination] Pagination 分页，警告部分中英翻译没有对应

### ISSUE THREAD

**Issue by Webming19** [element-plus/element-plus#7164]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome/100.0.4896.88`
- Build Tool: `Vue CLI`

### Related Component

- `el-pagination`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/pagination.html#%E5%B1%9E%E6%80%A7)

### Steps to reproduce

分页功能，属性下的警告，中英文翻译不对应，英文的解决方案实现了，中文的没有实现，希望给一个示例

### What is Expected?

中文的希望给一个示例

### What is actually happening?

中文的没有复现

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/163667756-d5927738-afc9-4599-8978-4ebf977f3322.png)
这个么？

**Comment by Webming19** [comment]
> ![图片](https://user-images.githubusercontent.com/23251408/163667756-d5927738-afc9-4599-8978-4ebf977f3322.png) 这个么？

是的，中英文的事件没有对应上

**Comment by chenxch** [comment]
收到，感谢您的反馈。

**Comment by sxzz** [comment]
这个警告更多是给开发者看的，个人觉得没有翻译的必要。

**Comment by Edric-Li** [comment]
确实，感觉没有必要翻译，如果翻译了，要和参数名对应，还得想一下，感觉这样就挺好。
