### ISSUE TITLE
[Bug Report] [Style] [input] input组件样式错乱

### ISSUE THREAD

**Issue by news00** [element-plus/element-plus#7165]
![1649935506(1)](https://user-images.githubusercontent.com/25659337/163381652-be6bb7bf-8fed-4cdd-bf09-794bd30c0084.jpg)

Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.11`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)

### Steps to reproduce

append插入select样式错误

### What is Expected?

append插入select样式错误

### What is actually happening?

append插入select样式错误

### Additional comments

_(empty)_

**Comment by news00** [comment]
![1649935506(1)](https://user-images.githubusercontent.com/25659337/163381706-54222998-876f-4505-9f30-574cc73df65f.jpg)

**Comment by news00** [comment]
<el-config-provider&nbsp; size="large"&gt;</el-config-provider&gt;
size=large时样式异常





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Bug Report] [Style] [input] input组件样式错乱 (Issue #7165)





 

 官方文档中也有类似的使用场景，其并没有出现你反馈的问题。方便提供下playground么

**Comment by zcmk123** [comment]
> el-config-provider

[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29uZmlnLXByb3ZpZGVyIHNpemU9XCJsYXJnZVwiPlxuICAgIDxkaXY+XG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dDFcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiPlxuICAgICAgPHRlbXBsYXRlICNwcmVwZW5kPkh0dHA6Ly88L3RlbXBsYXRlPlxuICAgIDwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwibXQtNFwiPlxuICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXQyXCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjYXBwZW5kPi5jb208L3RlbXBsYXRlPlxuICAgIDwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwibXQtNFwiPlxuICAgIDxlbC1pbnB1dFxuICAgICAgdi1tb2RlbD1cImlucHV0M1wiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgICBjbGFzcz1cImlucHV0LXdpdGgtc2VsZWN0XCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI3ByZXBlbmQ+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdFwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMTEwcHhcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiUmVzdGF1cmFudFwiIHZhbHVlPVwiMVwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIk9yZGVyIE5vLlwiIHZhbHVlPVwiMlwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlRlbFwiIHZhbHVlPVwiM1wiIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSAjYXBwZW5kPlxuICAgICAgICA8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1pbnB1dD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJtdC00XCI+XG4gICAgPGVsLWlucHV0XG4gICAgICB2LW1vZGVsPVwiaW5wdXQzXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCJcbiAgICAgIGNsYXNzPVwiaW5wdXQtd2l0aC1zZWxlY3RcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjcHJlcGVuZD5cbiAgICAgICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPHRlbXBsYXRlICNhcHBlbmQ+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdFwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMTEwcHhcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiUmVzdGF1cmFudFwiIHZhbHVlPVwiMVwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIk9yZGVyIE5vLlwiIHZhbHVlPVwiMlwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlRlbFwiIHZhbHVlPVwiM1wiIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWlucHV0PlxuICA8L2Rpdj5cbiAgPC9lbC1jb25maWctcHJvdmlkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgU2VhcmNoIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBpbnB1dDEgPSByZWYoJycpXG5jb25zdCBpbnB1dDIgPSByZWYoJycpXG5jb25zdCBpbnB1dDMgPSByZWYoJycpXG5jb25zdCBzZWxlY3QgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmlucHV0LXdpdGgtc2VsZWN0IC5lbC1pbnB1dC1ncm91cF9fcHJlcGVuZCB7XG4gIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWVsLWZpbGwtY29sb3ItYmxhbmspO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==) 
![image](https://user-images.githubusercontent.com/20919760/163510448-b9d08aac-ba78-4ffc-9b13-93eb345f943e.png)

**Comment by news00** [comment]
![image](https://user-images.githubusercontent.com/25659337/163657738-9243acc5-e9ee-4b2e-a133-49ca9d37e90a.png)

**Comment by news00** [comment]
app.vue 
![image](https://user-images.githubusercontent.com/25659337/163657752-2c1789c6-b78d-4782-9f7c-39f88c4e8a19.png)
