### ISSUE TITLE
[Bug Report] [Component] [input] Input受控模式下尝试输入内容会直接清空

### ISSUE THREAD

**Issue by RhysXia** [element-plus/element-plus#7169]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1pbnB1dCB2YWx1ZT1cIjEyM1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

尝试在输入框输入任何东西

### What is Expected?

输入框内容保持为123，不发生变化

### What is actually happening?

输入框被清空

### Additional comments

_(empty)_

**Comment by Alanscut** [comment]
请使用`modelValue`
![image](https://user-images.githubusercontent.com/21104054/163514830-8d68dc5a-6bff-4716-b0bf-c1625f5384a3.png)

**Comment by Alanscut** [comment]
@RhysXia 您好，如果没有其他问题我们将关闭这个issue

**Comment by RhysXia** [comment]
> @RhysXia 您好，如果没有其他问题我们将关闭这个issue

辛苦了，这样确实可以，不过不太理解，为什么不使用value 和绝大多数组件库的行为都不太一致

**Comment by chenxch** [comment]
> > @RhysXia 您好，如果没有其他问题我们将关闭这个issue
> 
> 辛苦了，这样确实可以，不过不太理解，为什么不使用value 和绝大多数组件库的行为都不太一致

vue3的组件库基本都是以目前这种方式，这是由于vue3的变更，有兴趣的话你可以看一下[vue docs v-model](https://vuejs.org/guide/extras/render-function.html#v-model)
