### ISSUE TITLE
[Feature Request] [tree] 如何监听 el-tree(树组件) ref上面的方法

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#7171]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `tree`

## Description

```vue
<script setup>
import { ref, onMounted } from "vue";

const treeRef= ref();

const useTree = (ref) => {
   onMounted(()=> {
     // 这里有办法监听到ref上面的check-change或者其他方法吗
   });
}

useTree(treeRef);
</script>

<template>
   <el-tree
      ref="treeRef"
      @check-change="checkChange"
   ></el-tree>
</template>
```

### Additional comments

实际useTree在单独文件

**Comment by huzedong2015** [comment]
@gjfei

**Comment by chenxch** [comment]
你可以在你的useTree内返回个checkChange，供组件使用

**Comment by chenxch** [comment]
```ts
const useTree = (ref)=>{
   const checkChange = (a,b,c)=>{
     console.log(a,b,c)
   }
	return {
    checkChange
  }
}
export default useTree
```

```vue

<script setup>
import { ref, onMounted } from "vue";
import useTree from './useTree.ts'

const treeRef= ref();
const {checkChange} = useTree(treeRef)
</script>

<template>
   <el-tree
      ref="treeRef"
      @check-change="checkChange"
   ></el-tree>
</template>
```

**Comment by huzedong2015** [comment]
> 你可以在你的useTree内返回个checkChange，供组件使用

这个是我目前的做法，我是看有没有可以监听或者注册一个 自定义时间，那样外面就不用额外的一个处理函数了。使用者更简单了。

**Comment by chenxch** [comment]
> > 你可以在你的useTree内返回个checkChange，供组件使用
> 
> 这个是我目前的做法，我是看有没有可以监听到tree的默认那些自定义事件，那样外面就不用额外的一个处理函数了。使用者更简单了。

我认为emits已经是满足了这个场景，我知道你的想法是更偏向于原生dom的那些事件回馈，但是它其实也是要有一个处理函数的。

**Comment by huzedong2015** [comment]
> > > 你可以在你的useTree内返回个checkChange，供组件使用
> > 
> > 
> > 这个是我目前的做法，我是看有没有可以监听到tree的默认那些自定义事件，那样外面就不用额外的一个处理函数了。使用者更简单了。
> 
> 我认为emits已经是满足了这个场景，我知道你的想法是更偏向于原生dom的那些事件回馈，但是它其实也是要有一个处理函数的。

嗯，感谢你的解答。

**Comment by chenxch** [comment]
@huzedong2015 您好，如果没有其他问题我们将关闭这个issue

**Comment by huzedong2015** [comment]
> @huzedong2015 您好，如果没有其他问题我们将关闭这个issue

没有了，关闭吧。
