### ISSUE TITLE
[Bug Report] [Component] [tree-select] TreeSelect组件，即使配置了node-key和props也无法设置默认选中

### ISSUE THREAD

**Issue by hzm07** [element-plus/element-plus#7172]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome 100.0.4896.88`
- Build Tool: `Webpack`

### Related Component

- `el-tree-select`

### Reproduction Link

[CodePen](https://codepen.io/hzm07/pen/NWXOoME)

### Steps to reproduce

如果数据源的key非value字段时，即使配置了node-key和props，也无法设置默认选中节点为二级之后的节点；但只要把数据源中的id字段改为value，就可以设置成功。

### What is Expected?

数据源的key不需要设置为value，配置了node-key和props后就可以成功设置默认选中节点（无论几级）。

### What is actually happening?

数据源的key对应为id字段，配置了node-key和props后，因为无法设置默认选中二级之后的节点。

### Additional comments

_(empty)_

**Comment by JackieCheung** [comment]
查看[Tree组件的Props属性](https://element-plus.org/zh-CN/component/tree.html#props)，`Props`没有`value`字段
