### ISSUE TITLE
[Bug Report] [Component] [input] 在el-form中使用el-input并使用clearable在输入内容后输入框异常变宽多了margin

### ISSUE THREAD

**Issue by royalscome** [element-plus/element-plus#7173]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chorme 100.0.4896.127/windows 10`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[CodePen](https://codepen.io/royalscome/pen/mdpzvax)

### Steps to reproduce

1.在项目中使用el-form组件；
2.在el-form-item中使用el-input;
3.在el-input中添加clearable属性；
4.随意输入文字

### What is Expected?

样式无变化

### What is actually happening?

输入框变宽

### Additional comments

_(empty)_

**Comment by plainheart** [comment]
Might be related to #7104
