### ISSUE TITLE
[Bug Report] [Component] [transfer]校验Form表单中的ElTransfer时，会把ElTransfer里面的搜索框置成错误状态

### ISSUE THREAD

**Issue by bitjjj** [element-plus/element-plus#7174]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Chrome 99 / MacOS 11`
- Build Tool: `Vite`

### Related Component

- `el-transfer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cInJ1bGVGb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJydWxlRm9ybVwiXG4gICAgOnJ1bGVzPVwicnVsZXNcIlxuICAgIGxhYmVsLXdpZHRoPVwiMTIwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gICAgOnNpemU9XCJmb3JtU2l6ZVwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQWN0aXZpdHkgbmFtZVwiIHByb3A9XCJuYW1lXCI+XG4gICAgICA8ZWwtdHJhbnNmZXJcbiAgICAgIHYtbW9kZWw9XCJydWxlRm9ybS5uYW1lXCJcbiAgICAgIHN0eWxlPVwidGV4dC1hbGlnbjogbGVmdDsgZGlzcGxheTogaW5saW5lLWJsb2NrXCJcbiAgICAgIGZpbHRlcmFibGVcbiAgICAgIDp0aXRsZXM9XCJbJ1NvdXJjZScsICdUYXJnZXQnXVwiXG4gICAgICA6YnV0dG9uLXRleHRzPVwiWydUbyBsZWZ0JywgJ1RvIHJpZ2h0J11cIlxuICAgICAgOmRhdGE9XCJkYXRhXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI2xlZnQtZm9vdGVyPlxuICAgICAgICA8ZWwtYnV0dG9uIGNsYXNzPVwidHJhbnNmZXItZm9vdGVyXCIgc2l6ZT1cInNtYWxsXCI+T3BlcmF0aW9uPC9lbC1idXR0b24+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgPHRlbXBsYXRlICNyaWdodC1mb290ZXI+XG4gICAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJ0cmFuc2Zlci1mb290ZXJcIiBzaXplPVwic21hbGxcIj5PcGVyYXRpb248L2VsLWJ1dHRvbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10cmFuc2Zlcj5cbiAgICA8L2VsLWZvcm0taXRlbT5cblxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShydWxlRm9ybVJlZilcIlxuICAgICAgICA+Q3JlYXRlPC9lbC1idXR0b25cbiAgICAgID5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVzZXRGb3JtKHJ1bGVGb3JtUmVmKVwiPlJlc2V0PC9lbC1idXR0b24+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZvcm1TaXplID0gcmVmKCdkZWZhdWx0JylcbmNvbnN0IHJ1bGVGb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgcnVsZUZvcm0gPSByZWFjdGl2ZSh7XG4gIG5hbWU6IFtdLFxuICByZWdpb246ICcnLFxuICBkYXRlMTogJycsXG4gIGRhdGUyOiAnJyxcbiAgZGVsaXZlcnk6IGZhbHNlLFxuICB0eXBlOiBbXSxcbiAgcmVzb3VyY2U6ICcnLFxuICBkZXNjOiAnJyxcbn0pXG5jb25zdCByaWdodFZhbHVlID0gcmVmKFsxXSlcbmNvbnN0IGxlZnRWYWx1ZSA9IHJlZihbMV0pXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoKTogT3B0aW9uW10gPT4ge1xuICBjb25zdCBkYXRhOiBPcHRpb25bXSA9IFtdXG4gIGZvciAobGV0IGkgPSAxOyBpIDw9IDE1OyBpKyspIHtcbiAgICBkYXRhLnB1c2goe1xuICAgICAga2V5OiBpLFxuICAgICAgbGFiZWw6IGBPcHRpb24gJHtpfWAsXG4gICAgICBkaXNhYmxlZDogaSAlIDQgPT09IDAsXG4gICAgfSlcbiAgfVxuICByZXR1cm4gZGF0YVxufVxuXG5jb25zdCBkYXRhID0gcmVmKGdlbmVyYXRlRGF0YSgpKVxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZSh7XG4gIG5hbWU6IFtcbiAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAnUGxlYXNlIGlucHV0IEFjdGl2aXR5IG5hbWUnLCB0cmlnZ2VyOiAnYmx1cicgfSxcbiAgICB7IG1pbjogMywgbWF4OiA1LCBtZXNzYWdlOiAnTGVuZ3RoIHNob3VsZCBiZSAzIHRvIDUnLCB0cmlnZ2VyOiAnYmx1cicgfSxcbiAgXSxcbiAgcmVnaW9uOiBbXG4gICAge1xuICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICBtZXNzYWdlOiAnUGxlYXNlIHNlbGVjdCBBY3Rpdml0eSB6b25lJyxcbiAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgIH0sXG4gIF0sXG4gIGRhdGUxOiBbXG4gICAge1xuICAgICAgdHlwZTogJ2RhdGUnLFxuICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICBtZXNzYWdlOiAnUGxlYXNlIHBpY2sgYSBkYXRlJyxcbiAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgIH0sXG4gIF0sXG4gIGRhdGUyOiBbXG4gICAge1xuICAgICAgdHlwZTogJ2RhdGUnLFxuICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICBtZXNzYWdlOiAnUGxlYXNlIHBpY2sgYSB0aW1lJyxcbiAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgIH0sXG4gIF0sXG4gIHR5cGU6IFtcbiAgICB7XG4gICAgICB0eXBlOiAnYXJyYXknLFxuICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICBtZXNzYWdlOiAnUGxlYXNlIHNlbGVjdCBhdCBsZWFzdCBvbmUgYWN0aXZpdHkgdHlwZScsXG4gICAgICB0cmlnZ2VyOiAnY2hhbmdlJyxcbiAgICB9LFxuICBdLFxuICByZXNvdXJjZTogW1xuICAgIHtcbiAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgbWVzc2FnZTogJ1BsZWFzZSBzZWxlY3QgYWN0aXZpdHkgcmVzb3VyY2UnLFxuICAgICAgdHJpZ2dlcjogJ2NoYW5nZScsXG4gICAgfSxcbiAgXSxcbiAgZGVzYzogW1xuICAgIHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdQbGVhc2UgaW5wdXQgYWN0aXZpdHkgZm9ybScsIHRyaWdnZXI6ICdibHVyJyB9LFxuICBdLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IGFzeW5jIChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGF3YWl0IGZvcm1FbC52YWxpZGF0ZSgodmFsaWQsIGZpZWxkcykgPT4ge1xuICAgIGlmICh2YWxpZCkge1xuICAgICAgY29uc29sZS5sb2coJ3N1Ym1pdCEnKVxuICAgIH0gZWxzZSB7XG4gICAgICBjb25zb2xlLmxvZygnZXJyb3Igc3VibWl0IScsIGZpZWxkcylcbiAgICB9XG4gIH0pXG59XG5cbmNvbnN0IHJlc2V0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC5yZXNldEZpZWxkcygpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1）不选择数据
2）点击校验按钮

### What is Expected?

ElTransfer中的搜索框状态正常

### What is actually happening?

ElTransfer中的搜索框被设置成错误状态

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这是由于错误状态会统一给一些样式加上错误的高亮边框，搜索框由于是一个input，所以也在这个行列，这个目前还是比较难从组件层面上去区分，我会建议你针对这个搜索框做个样式覆盖的处理。
