### ISSUE TITLE
[Bug Report] [Component] [carousel, carousel-item] el-input组件的 :prefix-icon属性 在 Carousel组件 中失效

### ISSUE THREAD

**Issue by Ryuuki6602** [element-plus/element-plus#7177]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.28`
- Element Plus Version: `2.1.9`
- Browser / OS: `Edge / windows 10`
- Build Tool: `Vue CLI`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmludGVydmFsPVwiNDAwMFwiIHR5cGU9XCJjYXJkXCIgaGVpZ2h0PVwiMjAwcHhcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbT5cbiAgICAgICA8ZWwtaW5wdXRcbiAgICAgICAgICAgICAgICAgdi1tb2RlbD1cIklEaWRudEV4cGVjdFRoaXNcIlxuICAgICAgICAgICAgICAgIDpwcmVmaXgtaWNvbj1cIlBvc3RjYXJkXCJcbiAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIuaIkeimgeeZu+W9lVwiXG4gICAgICAgICAgICAgIC8+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICAgIDxlbC1jYXJvdXNlbC1pdGVtPlxuICAgICAgIDxlbC1pbnB1dFxuICAgICAgICAgICAgICAgICB2LW1vZGVsPVwiSURpZG50RXhwZWN0VGhpc1Rvb1wiXG4gICAgICAgICAgICAgICAgOnByZWZpeC1pY29uPVwiUG9zdGNhcmRcIlxuICAgICAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwi5oiR6KaB5rOo5YaMXCJcbiAgICAgICAgICAgICAgLz5cbiAgICA8L2VsLWNhcm91c2VsLWl0ZW0+XG4gICAgPGVsLWNhcm91c2VsLWl0ZW0+XG4gICAgICAgPGVsLWlucHV0XG4gICAgICAgICAgICAgICAgIHYtbW9kZWw9XCJJRGlkbnRFeHBlY3RUaGlzRWl0aGVyXCJcbiAgICAgICAgICAgICAgICA6cHJlZml4LWljb249XCJQb3N0Y2FyZFwiXG4gICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCLmiJHopoHkv67mlLnlr4bnoIFcIlxuICAgICAgICAgICAgICAvPlxuICAgIDwvZWwtY2Fyb3VzZWwtaXRlbT5cbiAgPC9lbC1jYXJvdXNlbD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5cdGltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblx0aW1wb3J0IHsgUG9zdGNhcmQgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgXG5cdGNvbnN0IElEaWRudEV4cGVjdFRoaXMgPSByZWYoJycpXG4gIGNvbnN0IElEaWRudEV4cGVjdFRoaXNUb28gPSByZWYoJycpXG4gIGNvbnN0IElEaWRudEV4cGVjdFRoaXNFaXRoZXIgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cblxuXG4uZWwtY2Fyb3VzZWxfX2l0ZW06bnRoLWNoaWxkKDJuKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICM5OWE5YmY7XG59XG5cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4gKyAxKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNkM2RjZTY7XG59XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

<template>
  <el-carousel :interval="4000" type="card" height="200px">
    <el-carousel-item>
       <el-input
                 v-model="IDidntExpectThis"
                :prefix-icon="Postcard"
                placeholder="我要登录"
              />
    </el-carousel-item>
    <el-carousel-item>
       <el-input
                 v-model="IDidntExpectThisToo"
                :prefix-icon="Postcard"
                placeholder="我要注册"
              />
    </el-carousel-item>
    <el-carousel-item>
       <el-input
                 v-model="IDidntExpectThisEither"
                :prefix-icon="Postcard"
                placeholder="我要修改密码"
              />
    </el-carousel-item>
  </el-carousel>
</template>

<script setup>
	import { ref } from 'vue'
	import { Postcard } from '@element-plus/icons-vue'
  
	const IDidntExpectThis = ref('')
  const IDidntExpectThisToo = ref('')
  const IDidntExpectThisEither = ref('')
</script>

<style scoped>

.el-carousel__item:nth-child(2n) {
  background-color: #99a9bf;
}

.el-carousel__item:nth-child(2n + 1) {
  background-color: #d3dce6;
}
</style>

### What is Expected?

:prefix-icon占位

### What is actually happening?

:prefix-icon不占位

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
link #7179
