### ISSUE TITLE
El-tooltip - not styling

### ISSUE THREAD

**Issue by ntgraph** [element-plus/element-plus#718]
Hi,
Using your custom theme, and change theme color web site, I have exported the zip file and import in my app, in main.js
Most of element is styling as expected, but tooltip is not styling, in the browser inspect windows, I do not see el-popper is-dark in styles.

**Comment by JeremyWuuuuu** [comment]
The custom styling feature is not supported in ElementPlus.

**Comment by JeremyWuuuuu** [comment]
One way to manage to do that is to use global css to override the default style

**Comment by zazzaz** [comment]
Hi, the "change theme color web site" is not ready for Element Plus yet. But will be available soon.

You can not use "Update SCSS variables in your project", https://element-plus.org/#/en-US/component/custom-theme
