### ISSUE TITLE
[Bug Report] [Component] [tabs, table] 嵌套el-tab 页面卡死

### ISSUE THREAD

**Issue by news00** [element-plus/element-plus#7184]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.11`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-tabs`
- `el-table`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E5%A4%8D%E5%90%88%E5%9E%8B%E8%BE%93%E5%85%A5%E6%A1%86)

### Steps to reproduce

el-tab嵌入el-table卡死

### What is Expected?

el-tab嵌入el-table卡死

### What is actually happening?

el-tab嵌入el-table卡死

### Additional comments

_(empty)_

**Comment by news00** [comment]
![image](https://user-images.githubusercontent.com/25659337/163663638-91a9cb28-c1b9-42fc-b695-3427db1ca490.png)

**Comment by news00** [comment]
![image](https://user-images.githubusercontent.com/25659337/163663658-9e9a43b6-7f75-4206-9358-7dc725bcdbc3.png)
想实现这种功能，1.1.0-beta.15版是正常的

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/163663847-a589e316-2d8b-4d77-b31d-2419ddf2076e.png)
Since there is no online demo, I can only reproduce according to the picture, but there is no problem. Try to provide an online demo.

**Comment by news00** [comment]
<div class="tab-box">
          
          <el-tabs tab-position="left" class="roles-tabs" v-model="activeRoleName" v-if="list.length">
            <el-tab-pane v-for="item in list" :key="item.id" :name="item.id">
              <template #label>
                <el-checkbox
                  v-model="item.check"
                  :indeterminate="item.indeterminate"
                ></el-checkbox>
                <span class="tabs-label ml6">2222</span>
              </template>
              <el-tabs>
                <template v-if="item.groups.length">
                  <el-tab-pane v-for="group in item.groups" :key="group.groupId">
                    <template #label>
                      <el-checkbox
                        v-model="group.check"
                        :indeterminate="group.indeterminate"
                      ></el-checkbox>
                      <span class="tabs-label ml6">2222</span>
                    </template>
                    <el-table :data="group.functions" :show-header="false" height="260">
                      <el-table-column label="Elevator controls" prop="name">
                        <template #default="scope">
                          2222
                        </template>
                      </el-table-column>
                      <el-table-column label="Promission" width="100" align="right">
                        <template #default="scope">
                          <el-checkbox v-model="scope.row.check"  />
                        </template>
                      </el-table-column>
                    </el-table>
                  </el-tab-pane>
                </template>
                <template v-else>
                  <el-empty description="没有数据"></el-empty>
                </template>
              </el-tabs>
            </el-tab-pane>
          </el-tabs>
          <el-empty description="没有数据" v-else></el-empty>
        </div>

**Comment by news00** [comment]
https://codepen.io/news00/pen/qBpQrLz?editors=1111

**Comment by news00** [comment]
codepen是正常的  在项目里又卡死了

**Comment by news00** [comment]
is OK?

**Comment by chenxch** [comment]
codepen中我无法启动devtools，我比较建议你用删减注释法测试下你的项目代码中到底是哪个的地方导致卡死

**Comment by news00** [comment]
你本地新建项目是可以的？

**Comment by chenxch** [comment]
是的，和palyground中表现一样

**Comment by news00** [comment]
好的，谢谢  我排查一下

**Comment by news00** [comment]
el-popover 嵌套&nbsp; el-tree 时关闭子节点时样式错乱 怎么处理





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Bug Report] [Component] [tabs, table] 嵌套el-tab 页面卡死 (Issue #7184)





 
是的，和palyground中表现一样

**Comment by xiaozxz** [comment]
@news00 我使用简单的官方代码,发现tab-content的内容一旦过多，关闭pane，dom 一直没有释放。从代码里面看到tab的updatePaneInstances 发生在tab
-pane，onUnmounted之后。然后updatePaneInstances中有个方法叫getPaneInstanceFromSlot，猜测是获取pane的实例，那就相当于子组件都销毁时，上层还存在对他的引用，怀疑是这个导致dom不释放，内存占用不能释放

**Comment by jiajianlu-crypto** [comment]
我也遇到了这个问题，就是el-tab-pane 里面用了label插槽，就会无限循环卡死

**Comment by foreverstars** [comment]
> @news00 我使用简单的官方代码,发现tab-content的内容一旦过多，关闭pane，dom 一直没有释放。从代码里面看到tab的updatePaneInstances 发生在tab -pane，onUnmounted之后。然后updatePaneInstances中有个方法叫getPaneInstanceFromSlot，猜测是获取pane的实例，那就相当于子组件都销毁时，上层还存在对他的引用，怀疑是这个导致dom不释放，内存占用不能释放

解决了吗

**Comment by foreverstars** [comment]
> 

解决了吗

**Comment by news00** [comment]
没有，改为div标签渲染了
