### ISSUE TITLE
[Bug Report] [Component] [tree-select] treeselect在清空选择组件无效

### ISSUE THREAD

**Issue by wqdian** [element-plus/element-plus#7185]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `chrome 100.0.4896.127 / mac os`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRWxUcmVlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHR5cGUgTm9kZSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC9ub2RlJ1xuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBudW1iZXJcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuY29uc3QgdHJlZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVHJlZT4+KClcblxuY29uc3QgZGVmYXVsdFByb3BzID0ge1xuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA0LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA5LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0yJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDUsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogNixcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiA3LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDgsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG4gIFxuICBjb25zdCBjaGVja0NoYW5nZUhhbmRsZXIgPSAobm9kZTogYW55KSA9PiB7XG5cdFx0XHR0cmVlUmVmLnZhbHVlIS5zZXRDaGVja2VkS2V5cyhbXSwgZmFsc2UpO1xuXHRcdFx0dHJlZVJlZi52YWx1ZSEuc2V0Q2hlY2tlZE5vZGVzKFtdLCBmYWxzZSk7XG5cdFx0XHQvL2xldCBhcnJheSA9IHRyZWVSZWYudmFsdWUhLmdldENoZWNrZWROb2RlcyhmYWxzZSwgZmFsc2UpO1xuXHRcdFx0XG5cdFx0XHR0cmVlUmVmLnZhbHVlIS5zZXRDaGVja2VkTm9kZXMoW25vZGVdLCBmYWxzZSk7XG5cdFx0fTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuPGVsLXRyZWUtc2VsZWN0IFxuICAgIHJlZj1cInRyZWVSZWZcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgc2hvdy1jaGVja2JveFxuXHRcdDpjaGVjay1zdHJpY3RseT1cInRydWVcIlxuICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gICAgQGNoZWNrPVwiY2hlY2tDaGFuZ2VIYW5kbGVyXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

```
<script setup lang="ts">
import { ref } from 'vue'
import type { ElTree } from 'element-plus'
import type Node from 'element-plus/es/components/tree/src/model/node'

interface Tree {
  id: number
  label: string
  children?: Tree[]
}
const treeRef = ref<InstanceType<typeof ElTree>>()

const defaultProps = {
  children: 'children',
  label: 'label',
}

const data: Tree[] = [
  {
    id: 1,
    label: 'Level one 1',
    children: [
      {
        id: 4,
        label: 'Level two 1-1',
        children: [
          {
            id: 9,
            label: 'Level three 1-1-1',
          },
          {
            id: 10,
            label: 'Level three 1-1-2',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    label: 'Level one 2',
    children: [
      {
        id: 5,
        label: 'Level two 2-1',
      },
      {
        id: 6,
        label: 'Level two 2-2',
      },
    ],
  },
  {
    id: 3,
    label: 'Level one 3',
    children: [
      {
        id: 7,
        label: 'Level two 3-1',
      },
      {
        id: 8,
        label: 'Level two 3-2',
      },
    ],
  },
]
  
  const checkChangeHandler = (node: any) => {
			treeRef.value!.setCheckedKeys([], false);
			treeRef.value!.setCheckedNodes([], false);
			//let array = treeRef.value!.getCheckedNodes(false, false);
			
			treeRef.value!.setCheckedNodes([node], false);
		};
</script>

<template>
  <!-- Element Plus icons -->
<el-tree-select 
    ref="treeRef"
    :data="data"
    default-expand-all
    node-key="id"
    show-checkbox
		:check-strictly="true"
    :props="defaultProps"
    @check="checkChangeHandler"
  />
</template>

```

### What is Expected?

取消已经选中的节点

### What is actually happening?

依然处于选中状态

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
The first problem is that the initial settings of the current version of `nodeKey` will not take effect. You can follow #7172 . You can change the `id` to `value` first.
Second question, you need to add a v-model to the component.
Hope these can help you solve the current problem first.

**Comment by wqdian** [comment]
> The first problem is that the initial settings of the current version of `nodeKey` will not take effect. You can follow #7172 . You can change the `id` to `value` first. Second question, you need to add a v-model to the component. Hope these can help you solve the current problem first.
谢谢，参考[#7172](https://github.com/element-plus/element-plus/issues/7172)问题得以解决

**Comment by chenxch** [comment]
感谢你的反馈，后续你可以关注下 #7181
