### ISSUE TITLE
[Bug Report] [Docs] [slider] 搜狗浏览器里的silder滑块文档中的不同尺寸示例是一堆乱码

### ISSUE THREAD

**Issue by WangJiaShuo1999** [element-plus/element-plus#7186]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `搜狗`
- Build Tool: `Other`

### Related Component

- `el-slider`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/slider.html#%E4%B8%8D%E5%90%8C%E5%B0%BA%E5%AF%B8)

### Steps to reproduce

无

### What is Expected?

修复示例

### What is actually happening?

::demo

slider/sizes

:::

### Additional comments

线上文档中的显示问题，对使用是否造成影响不能确定

**Comment by btea** [comment]
文档翻译的问题，对使用并不会造成影响，[已修改](https://crowdin.com/translate/element-plus/789/en-zhcn?filter=basic&value=0)。

非常感谢你指出这个问题！
