### ISSUE TITLE
[Feature Request] [Enhancement] [table-column] show-overflow-tooltip 属性，希望增加复制内容功能

### ISSUE THREAD

**Issue by HWJ-Code** [element-plus/element-plus#7188]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `table-column`

## Description

**table-column** 的 **show-overflow-tooltip** 属性，能不能增加鼠标可以移上去**复制显示**的内容，而不是鼠标移开就消失？

### Additional comments

_(empty)_

**Comment by cjbtd** [comment]
Triple click the cell and CTRL + C will copy it

**Comment by HWJ-Code** [comment]
> Triple click the cell and CTRL + C will copy it

But this is inconvenient for users

**Comment by L1yp** [comment]
这个BUG我发了2个月都没人修复  简直离谱

**Comment by fanzhengshao** [comment]
Hope the authorities can add this feature！！！！！！！！！！！！！！！！
