### ISSUE TITLE
如何在 Vite 里按需引入 Element-Plus ？

### ISSUE THREAD

**Issue by rieval** [element-plus/element-plus#719]
我按照教程安装了 `babel-plugin-component`

然后在项目根目录写入了 `.babelrc` 文件：
```
{
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-plus",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}
```
并修改了 `main.ts` 文件：
```
import { createApp } from 'vue'
import { ElButton } from 'element-plus'
import App from './App.vue'
import './index.css'

const app = createApp(App)

app.component(ElButton.name, ElButton)

app.mount('#app')
```
但我发现前后两次 build，项目体积有了非常显著的增长：

![屏幕截图 2020-11-28 104920](https://user-images.githubusercontent.com/22883406/100492482-66249c80-3167-11eb-928f-20923c5539ca.png)

我猜测可能是 Vite 并不包含 Babel 的原因，请解惑。

**Comment by JeremyWuuuuu** [comment]
Right, if you wish to do that you might need to import via explicit path, like 

```
import ElButton from "element-plus/lib/el-button"
```

**Comment by rieval** [comment]
感谢，已经解决

根据 debug 的提示，我需要额外安装 `@babel/runtime` 这个包，不知道是不是我自己的问题

![屏幕截图](https://user-images.githubusercontent.com/22883406/100493126-e26eae00-316e-11eb-9712-828773242ffa.png)

此外，我还需额外引入相应的 css

`import 'element-plus/lib/theme-chalk/el-button.css'`

最后在 `vite.config.ts` 里添加 `optimizeDeps` 设置项：

```
  optimizeDeps: {
    include: ["element-plus/lib/el-button"]
  },
```

希望官方可以修改一下文档，说明如何在 Vite 里按需引入

**Comment by JeremyWuuuuu** [comment]
We also have a esm bundle built just for this @zazzaz could you help him out?

**Comment by rieval** [comment]
如果有更好的方法，请告诉我
😂😂

**Comment by zazzaz** [comment]
@rieval Hi, you can try `element-plus@1.0.1-beta.0`, we've removed the `@babel/runtime` dep after this release.

**Comment by rieval** [comment]
> @rieval Hi, can you pls try `element-plus@1.0.1-beta.0`. We've removed the `@babel/runtime` dep after this release.

你好，我在测试的时候发现 `element-plus/lib/utils/error.js` 这个文件仍然引用了 `@babel/runtime` 这个包

![屏幕截图 190218](https://user-images.githubusercontent.com/7274487/100602468-e3eed080-333e-11eb-848e-cd7bdf19e062.png)

![屏幕截图 190316](https://user-images.githubusercontent.com/7274487/100602490-ebae7500-333e-11eb-945f-dd05119f8cdc.png)

**Comment by JeremyWuuuuu** [comment]
@rieval we might stop supporting versions lower than ES6 in the near future, what you have encountered is indeed some configuration issue of `ElementPlus`, you might still need to use the way you used before in order to make this work. Sorry for the inconvenience, let's keep this issue tracked via this issue.

**Comment by JeremyWuuuuu** [comment]
Fixed in #577

**Comment by wingsico** [comment]
may be you can try this: [vite-element-demand-starter](https://github.com/wingsico/vite-element-demand-starter)

**Comment by psaren** [comment]
按需加载vite插件 [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp)

**Comment by wangfpp** [comment]
@rieval  您好 你配置的按需引入可以跑起来了吗？ 希望你能给一点指导或者给个例子
