### ISSUE TITLE
[Bug Report] [Component] [input, dialog] el-dialog nested el-input component, el-input component does not display prefix-icon correctly. 【el-dialog嵌套el-input组件，el-input组件不能正确显示prefix-icon】

### ISSUE THREAD

**Issue by dream2333** [element-plus/element-plus#7197]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome 100.0.4896.75 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHRlc3QgPXJlZih0cnVlKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWlucHV0IHBsYWNlaG9sZGVyPVwidXNlcm5hbWVcIiA6cHJlZml4LWljb249XCJVc2VyXCIgc2l6ZT1cImxhcmdlXCIgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0ZXN0PXRydWVcIj5vcGVuPC9lbC1idXR0b24+XG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cInRlc3RcIj5cbiAgPGVsLWlucHV0IHBsYWNlaG9sZGVyPVwidXNlcm5hbWVcIiA6cHJlZml4LWljb249XCJVc2VyXCIgc2l6ZT1cImxhcmdlXCIgLz5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

Click the button to open the dialog
点击按钮打开dialog

### What is Expected?

The icon in the input component is displayed normally on the left side of the text
input组件中的图标正常显示在文本左方

### What is actually happening?

Icon and text overlay
图标和文本重叠

### Additional comments

This error does not exist in element-plus 2.1.8 and earlier versions
element-plus 2.1.8及之前的版本不存在此错误

**Comment by chenxch** [comment]
link #7179
