### ISSUE TITLE
[Bug Report] [Component] [pagination] 分页插槽无效

### ISSUE THREAD

**Issue by ace9527x** [element-plus/element-plus#7200]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39`
- Build Tool: `Webpack`

### Related Component

- `el-pagination`

### Reproduction Link

[CodePen](https://codepen.io/xiao349560971/pen/VwyVOVP)

### Steps to reproduce

设置插槽无效

### What is Expected?

自定义样式

### What is actually happening?

无效

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/163716773-17ddf2c5-752c-4da7-b652-41955ffcc43c.png)

```vue
<el-pagination small layout="prev, pager, slot" :total="50">
        <div #next>
          <span>123</span>
        </div>
      </el-pagination>
```

**Comment by chenxch** [comment]
If your issue is resolved, you can close this issue.

**Comment by chenxch** [comment]
@ace9527x Hi, I will close this issue if there is no problem.
