### ISSUE TITLE
[Bug Report] [Component] [select, tree-select] 多选的 超长 Label 在 select 中 显示很怪

### ISSUE THREAD

**Issue by fisker** [element-plus/element-plus#7212]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `EDGE latest/ Windows 10`
- Build Tool: `Other`

### Related Component

- `el-select`
- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogaW5saW5lLWJsb2NrOyBtYXJnaW4tbGVmdDogMjBweFwiPlxuICAgIDxwIHN0eWxlPVwibWFyZ2luLWxlZnQ6IDEwcHhcIj51c2UgY29sbGFwc2UtdGFncy10b29sdGlwPC9wPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFsnT3B0aW9uMScsICdPcHRpb24yJywgJ09wdGlvbjMnXSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAn6YCC55So5oCn6L6D5bm/55qE5Z+656GA5aSa6YCJ77yM55SoIFRhZyDlsZXnpLrlt7LpgInpobknLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ+mAgueUqOaAp+i+g+W5v+eahOWfuuehgOWkmumAie+8jOeUqCBUYWcg5bGV56S65bey6YCJ6aG5MicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAn6YCC55So5oCn6L6D5bm/55qE5Z+656GA5aSa6YCJ77yM55SoIFRhZyDlsZXnpLrlt7LpgInpobkzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICfpgILnlKjmgKfovoPlub/nmoTln7rnoYDlpJrpgInvvIznlKggVGFnIOWxleekuuW3sumAiemhuTQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ+mAgueUqOaAp+i+g+W5v+eahOWfuuehgOWkmumAie+8jOeUqCBUYWcg5bGV56S65bey6YCJ6aG5NScsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

See the playground link.

### What is Expected?

正常显示

### What is actually happening?

居中,且不能显示 `...`

### Additional comments

Adding

```css
.el-select .el-select__tags-text {
  display: block;
}
```

Seems to work as expected.

![image](https://user-images.githubusercontent.com/172584/163748282-13e81d6b-864c-41fd-becd-3fb4b782f94a.png)

**Comment by jwptl** [comment]
![image](https://user-images.githubusercontent.com/37426271/219254300-cedf800b-4180-425e-9e2d-7706650d9685.png)
我这中情况怎么解决 只能设置固定宽度吗

**Comment by kooriookami** [comment]
Fixed

**Comment by jwptl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
