### ISSUE TITLE
[Bug Report] [Component] [select] 当多选的Select只选择了一个选项时, label后面空白过大

### ISSUE THREAD

**Issue by fisker** [element-plus/element-plus#7213]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `EDGE latest/ Windows 10`
- Build Tool: `Other`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgY29sbGFwc2UtdGFncy10b29sdGlwXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAxNDBweDtcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFsnT3B0aW9uMSddKVxuY29uc3Qgc2hvdyA9IHJlZihmYWxzZSlcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAn6YCC55So5oCn6L6D5bm/55qE5Z+656GA5aSa6YCJ77yM55SoIFRhZyDlsZXnpLrlt7LpgInpobknLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ+mAgueUqOaAp+i+g+W5v+eahOWfuuehgOWkmumAie+8jOeUqCBUYWcg5bGV56S65bey6YCJ6aG5MicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAn6YCC55So5oCn6L6D5bm/55qE5Z+656GA5aSa6YCJ77yM55SoIFRhZyDlsZXnpLrlt7LpgInpobkzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICfpgILnlKjmgKfovoPlub/nmoTln7rnoYDlpJrpgInvvIznlKggVGFnIOWxleekuuW3sumAiemhuTQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ+mAgueUqOaAp+i+g+W5v+eahOWfuuehgOWkmumAie+8jOeUqCBUYWcg5bGV56S65bey6YCJ6aG5NScsXG4gIH0sXG5dXG48L3NjcmlwdD5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

See the playground link.

### What is Expected?

当只选择了一个选项时, 没必要留位置给 `+1`

### What is actually happening?

空白很大

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/172584/163749795-fc21366b-7430-4e2e-a1a5-6c66b4e43e4b.png)

**Comment by kooriookami** [comment]
fixed
