### ISSUE TITLE
[Bug Report] [Component] [select] el-select object value

### ISSUE THREAD

**Issue by YXYH-12138** [element-plus/element-plus#7216]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome/99.0.4844.51`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IHJlZihbXSlcbmNvbnN0IHNlbFJlc3VsdCA9IHJlZjxhbnk+KG51bGwpXG5cbm9wdGlvbnMudmFsdWUgPSBbXG4gIHtcbiAgICBpZDogMSwgbmFtZTogJzExMScsIHZhbHVlOiAndjExMSdcbiAgfSxcbiAge1xuICAgIGlkOiAyLCBuYW1lOiAnMTEyJywgdmFsdWU6ICd2MTEyJ1xuICB9LFxuICB7XG4gICAgaWQ6IDMsIG5hbWU6ICcxMTMnLCB2YWx1ZTogJ3YxMTMzJ1xuICB9LFxuICB7XG4gICAgaWQ6IDQsIG5hbWU6ICcxMTE0JywgdmFsdWU6ICd2MTExJ1xuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIFJldWxzdDoge3tzZWxSZXN1bHR9fVxuICA8L2Rpdj4gIFxuIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbFJlc3VsdFwiIHZhbHVlLWtleT1cImlkXCI+XG4gICAgPGVsLW9wdGlvbiBcbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiIFxuICAgICAgOmxhYmVsPVwiaXRlbS5uYW1lXCIgXG4gICAgICA6dmFsdWU9XCJpdGVtXCI+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

当v-model绑定对象时，绑定的文字无法显示

### What is Expected?

显示文字

### What is actually happening?

无法显示

### Additional comments

2.1.7及以下版本可正常显示

**Comment by chenxch** [comment]
link #7054

**Comment by kooriookami** [comment]
Fixed
