### ISSUE TITLE
[Bug Report] [Style] [message] 代码多次调用ElMessage方法，出现重叠的问题

### ISSUE THREAD

**Issue by CR-pcs** [element-plus/element-plus#7217]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `e.g. Chrome 96.0.4664.45 / macOS 12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbiAgXG5jb25zdCB0ZXN0ID0gKCkgPT4ge1xuICBbMSwyLDMsNCw1LDYsN10uZm9yRWFjaCgoKSA9PiB7XG4gICAgRWxNZXNzYWdlLndhcm5pbmcoJ+aPkOekuumHjeWkjeS6hicpXG4gIH0pXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ0ZXN0XCIgPueCueWHu+WHuueOsOWkmuS4quaPkOekujwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ElMessage } from 'element-plus'
const test = () => {
  [1,2,3,4,5,6,7].forEach(() => {
    ElMessage.warning('提示重复了')
  })
}
</script>
<template>
  <el-button @click="test" >点击出现多个提示</el-button>
</template>
```

### What is Expected?

使用代码多次触发ElMessage方法，message的间隔正常

### What is actually happening?

使用代码多次触发ElMessage方法，message的间隔重叠

### Additional comments

_(empty)_

**Comment by tulies** [comment]
的确bug

**Comment by stylusscoped** [comment]
修复了吗？
