### ISSUE TITLE
[Bug Report] [Component] [popconfirm, tooltip] tooltip在popconfirm中使用无法触发popconfirm的事件

### ISSUE THREAD

**Issue by cgd199158** [element-plus/element-plus#7221]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-popconfirm`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEZvbGRlclJlbW92ZSB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG4gIFxuY29uc3QgaGFuZGxlclVuQmluZCA9ICgpID0+e31cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luOiAxMDBweDtcIj5cbiAgICA8ZWwtcG9wY29uZmlybSB0aXRsZT1cIuehruWumuimgeWwhuatpOi0puWPt+iuvue9ruS4uuS4u+i0puWPt+WQl1wiIEBjb25maXJtPVwiaGFuZGxlclVuQmluZFwiPlxuICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgIDxlbC10b29sdGlwIGNvbnRlbnQ9XCLorr7nva7kuLvotKblj7dcIiBlZmZlY3Q9XCJkYXJrXCIgcGxhY2VtZW50PVwiYm90dG9tXCI+XG4gICAgICAgICAgPEVsQnV0dG9uIHNpemU9XCJzbWFsbFwiIDppY29uPVwiRm9sZGVyUmVtb3ZlXCI+PC9FbEJ1dHRvbj5cbiAgICAgICAgPC9lbC10b29sdGlwPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXBvcGNvbmZpcm0+XG4gIDwvZGl2PlxuICBcbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

点击按钮confirm事件无法触发

### What is Expected?

触发confirm的同时tooltip正常运行

### What is actually happening?

tooltip正常运行,但是popconfirm组件无法运行

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
```vue
<el-popconfirm title="确定要将此账号设置为主账号吗" @confirm="handlerUnBind">
      <template #reference>
        <span class="row center">
          <el-tooltip content="设置主账号" effect="dark" placement="bottom">
            <ElButton size="small" :icon="FolderRemove"></ElButton>
          </el-tooltip>
        </span>
      </template>
    </el-popconfirm>
```

**Comment by chenxch** [comment]
If your issue has been resolved, you can close the issue.

**Comment by cgd199158** [comment]
> If your issue has been resolved, you can close the issue.

感谢
