### ISSUE TITLE
[Bug Report] [Docs] [table, table-column] el-table-column自闭合写法导致渲染错乱

### ISSUE THREAD

**Issue by tall-talker** [element-plus/element-plus#7232]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `360安全浏览器/Windows 10 家庭中文版`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/caoguoly940713/pen/LYeMWyg)

### Steps to reproduce

        <el-table :data="list" class="table">
            <el-table-column prop="date" label="Date" width="180"/>
            <el-table-column prop="name" label="Name" width="180"/>
            <el-table-column prop="address" label="Address"/>
        </el-table>
   
        Vue.createApp({
            data: function () {
                return {
                    list: [{
                            date: '2016-05-03',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-02',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-04',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        },
                        {
                            date: '2016-05-01',
                            name: 'Tom',
                            address: 'No. 189, Grove St, Los Angeles',
                        }
                    ]
                }
            }
        }).use(ElementPlus).mount('#main')
    

### What is Expected?

表格正常渲染

### What is actually happening?

渲染错误

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
It is recommended to use element playground.

**Comment by tall-talker** [comment]
感谢指点，将关闭issue

**Comment by tall-talker** [comment]
引用V2的文档，自闭合组件只能在单文件组件中使用，原生dom模板不支持
> 在[单文件组件](https://cn.vuejs.org/v2/guide/single-file-components.html)、字符串模板和 [JSX](https://cn.vuejs.org/v2/guide/render-function.html#JSX) 中没有内容的组件应该是自闭合的——但在 DOM 模板里永远不要这样做。
