### ISSUE TITLE
[Bug Report] [Component] 使用el-config-provider改变组件大小后，el-drawer中有disabled的el-select时，el-select的高度不正常

### ISSUE THREAD

**Issue by hoowhoami** [element-plus/element-plus#7233]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-drawer`
- `el-select`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uLWdyb3VwPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlU2l6ZSgnbGFyZ2UnKVwiPkxhcmdlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VTaXplKCdkZWZhdWx0JylcIj5EZWZhdWx0PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VTaXplKCdzbWFsbCcpXCI+U21hbGw8L2VsLWJ1dHRvbj5cbiAgPC9lbC1idXR0b24tZ3JvdXA+XG4gIDxici8+XG4gIDxlbC1jb25maWctcHJvdmlkZXIgOnNpemU9XCJzaXplXCI+XG4gIDxlbC1idXR0b24gdHlwZT1cInRleHRcIiBAY2xpY2s9XCJvcGVuRGlhbG9nXCJcbiAgICA+T3BlbiBEcmF3ZXIgd2l0aCBuZXN0ZWQgZm9ybTwvZWwtYnV0dG9uXG4gID5cblxuICA8ZWwtZHJhd2VyXG4gICAgcmVmPVwiZHJhd2VyUmVmXCJcbiAgICB2LW1vZGVsPVwiZGlhbG9nXCJcbiAgICB0aXRsZT1cIkkgaGF2ZSBhIG5lc3RlZCBmb3JtIGluc2lkZSFcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gICAgc2l6ZT1cIjUwJVwiXG4gICAgY3VzdG9tLWNsYXNzPVwiZGVtby1kcmF3ZXJcIlxuICA+XG4gICAgPGRpdiBjbGFzcz1cImRlbW8tZHJhd2VyX19jb250ZW50XCI+XG4gICAgICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCI+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJOYW1lXCIgOmxhYmVsLXdpZHRoPVwiZm9ybUxhYmVsV2lkdGhcIj5cbiAgICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQXJlYVwiIDpsYWJlbC13aWR0aD1cImZvcm1MYWJlbFdpZHRoXCI+XG4gICAgICAgICAgPGVsLXNlbGVjdFxuICAgICAgICAgICAgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCJcbiAgICAgICAgICAgIDpkaXNhYmxlZD1cImRpc2FibGVkXCJcbiAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdCBhY3Rpdml0eSBhcmVhXCJcbiAgICAgICAgICA+XG4gICAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiQXJlYTFcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJBcmVhMlwiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgPC9lbC1mb3JtPlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW8tZHJhd2VyX19mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjYW5jZWxGb3JtXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6bG9hZGluZz1cImxvYWRpbmdcIiBAY2xpY2s9XCJvbkNsaWNrXCI+e3tcbiAgICAgICAgICBsb2FkaW5nID8gJ1N1Ym1pdHRpbmcgLi4uJyA6ICdTdWJtaXQnXG4gICAgICAgIH19PC9lbC1idXR0b24+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9lbC1kcmF3ZXI+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHR5cGUgeyBFbERyYXdlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZm9ybUxhYmVsV2lkdGggPSAnODBweCdcbmxldCB0aW1lclxuXG5jb25zdCBkaWFsb2cgPSByZWYoZmFsc2UpXG5jb25zdCBsb2FkaW5nID0gcmVmKGZhbHNlKVxubGV0IHNpemUgPSByZWYoJ2RlZmF1bHQnKVxuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnJyxcbiAgcmVnaW9uOiAnJyxcbiAgZGF0ZTE6ICcnLFxuICBkYXRlMjogJycsXG4gIGRlbGl2ZXJ5OiBmYWxzZSxcbiAgdHlwZTogW10sXG4gIHJlc291cmNlOiAnJyxcbiAgZGVzYzogJycsXG59KVxuXG5jb25zdCBkcmF3ZXJSZWYgPSByZWY8SW5zdGFuY2VUeXBlPHR5cGVvZiBFbERyYXdlcj4+KClcbmNvbnN0IG9uQ2xpY2sgPSAoKSA9PiB7XG4gIGRyYXdlclJlZi52YWx1ZSEuY2xvc2UoKVxufVxuXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lKSA9PiB7XG4gIGlmIChsb2FkaW5nLnZhbHVlKSB7XG4gICAgcmV0dXJuXG4gIH1cbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oJ0RvIHlvdSB3YW50IHRvIHN1Ym1pdD8nKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIGxvYWRpbmcudmFsdWUgPSB0cnVlXG4gICAgICB0aW1lciA9IHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICBkb25lKClcbiAgICAgICAgLy8g5Yqo55S75YWz6Zet6ZyA6KaB5LiA5a6a55qE5pe26Ze0XG4gICAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICAgIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuICAgICAgICB9LCA0MDApXG4gICAgICB9LCAyMDAwKVxuICAgIH0pXG4gICAgLmNhdGNoKCgpID0+IHtcbiAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgfSlcbn1cblxuY29uc3QgY2hhbmdlU2l6ZSA9IChzKSA9PiB7XG4gIHNpemUudmFsdWUgPSBzXG59XG5cbmNvbnN0IGNhbmNlbEZvcm0gPSAoKSA9PiB7XG4gIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuICBkaWFsb2cudmFsdWUgPSBmYWxzZVxuICBjbGVhclRpbWVvdXQodGltZXIpXG59XG5cbmNvbnN0IGRpc2FibGVkID0gcmVmKGZhbHNlKVxuY29uc3Qgb3BlbkRpYWxvZyA9ICgpID0+IHtcbiAgZGlhbG9nLnZhbHVlID0gdHJ1ZVxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBkaXNhYmxlZC52YWx1ZSA9IHRydWVcbiAgfSwgMzAwMClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

1. 打开抽屉查看下拉框高度，此时是正常的；
2. 关闭抽屉，点击按钮修改组件大小；
3. 再次打开抽屉，下拉框高度出现问题。

### What is Expected?

使用el-config-provider改变组件大小后禁用的下拉框高度也正常修改

### What is actually happening?

使用el-config-provider改变组件大小后禁用的下拉框高度没有修改

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/84499551/163903689-b09878aa-2dec-4cbb-8f4c-47e17a163819.png)

**Comment by chenxch** [comment]
destroy-on-close 先使用这个属性解决下问题，原因应该是input被写上了style的高度，导致class切换不生效。
