### ISSUE TITLE
[Bug Report] [Component] [input] 多行文本框 resize 为both时，showWordLimit 显示异常

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7235]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwidGV4dGFyZWFcIlxuICAgIDpyb3dzPVwiMlwiXG4gICAgdHlwZT1cInRleHRhcmVhXCJcbiAgICAgICAgICAgIDptYXhsZW5ndGg9XCI1MFwiXG4gICAgICAgICAgICA6c2hvdy13b3JkLWxpbWl0PVwidHJ1ZVwiXG4gICAgICAgICAgICByZXNpemU9XCJib3RoXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdGV4dGFyZWEgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

如图

### What is Expected?

showwordlimit 位置正确

### What is actually happening?

showwordlimit 位置错误

### Additional comments

![image](https://user-images.githubusercontent.com/50992790/163916088-dddd83a2-5c70-42c3-8489-b37d1c4a7945.png)

**Comment by tall-talker** [comment]
![image](https://user-images.githubusercontent.com/22855387/164882701-bfc2d89f-a6e1-4daf-a079-2c901370bb40.png)
playground里面显示正常

**Comment by Edric-Li** [comment]
@tall-talker  你得拽一下，不是说初始就坏了
![FORGUNCY-9402](https://user-images.githubusercontent.com/50992790/165003899-490eb6c4-1ced-4cb5-8e02-2fdd557c450d.gif)
