### ISSUE TITLE
[Bug Report] [Component] [icon] Document outdated or bug for usage of el-icon

### ISSUE THREAD

**Issue by KiritaniAyaka** [element-plus/element-plus#7236]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome/100.0.4896.88 / Windows NT 10.0; Win64; x64`
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFNlYXJjaCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuXHRjb21wb25lbnRzOiB7XG5cdFx0U2VhcmNoXG5cdH0sXG5cdGRhdGEoKSB7XG5cdFx0cmV0dXJuIHtcblx0XHRcdHNlbGVjdDogJycsXG5cdFx0XHRpbnB1dDogJydcblx0XHR9XG5cdH1cbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuXHRcdDxkaXY+aWNvbiBjbGFzcyBpbiBvdGhlciBjb21wb25lbnQ8L2Rpdj5cblx0XHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiA6aWNvbj1cInNlYXJjaFwiPmFzZDwvZWwtYnV0dG9uPlxuXHQ8L2Rpdj5cblx0PGRpdj5cblx0XHQ8ZGl2PmVsLWljb24gdGFnIGluIG90aGVyIGNvbXBvbmVudDwvZGl2PlxuXHRcdDxlbC1idXR0b24gdHlwZT1cImRhbmdlclwiIDppY29uPVwic2VhcmNoXCI+XG5cdFx0XHQ8ZWwtaWNvbj5cblx0XHRcdFx0PFNlYXJjaCAvPlxuXHRcdFx0PC9lbC1pY29uPlxuXHRcdDwvZWwtYnV0dG9uPlxuXHQ8L2Rpdj5cblx0PGRpdj5cblx0XHQ8ZGl2PmVsLWljb24gdGFnIGRpcmVjdGx5PC9kaXY+XG5cdFx0PGVsLWljb24+XG5cdFx0XHQ8U2VhcmNoIC8+XG5cdFx0PC9lbC1pY29uPlxuXHQ8L2Rpdj5cblx0PGhyPlxuXG5cdDxkaXY+XG5cdFx0PGRpdj51c2FnZSBpbiA8YSBocmVmPVwiaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2VuLVVTL2NvbXBvbmVudC9pbnB1dC5odG1sI21peGVkLWlucHV0XCI+RG9jdW1lbnQgKE1peGVkIGlucHV0KTwvYT48L2Rpdj5cblx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBjbGFzcz1cImlucHV0LXdpdGgtc2VsZWN0XCI+XG5cdFx0XHQ8dGVtcGxhdGUgI3ByZXBlbmQ+XG5cdFx0XHRcdDxlbC1zZWxlY3Qgdi1tb2RlbD1cInNlbGVjdFwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc3R5bGU9XCJ3aWR0aDogMTEwcHhcIj5cblx0XHRcdFx0XHQ8ZWwtb3B0aW9uIGxhYmVsPVwiUmVzdGF1cmFudFwiIHZhbHVlPVwiMVwiIC8+XG5cdFx0XHRcdFx0PGVsLW9wdGlvbiBsYWJlbD1cIk9yZGVyIE5vLlwiIHZhbHVlPVwiMlwiIC8+XG5cdFx0XHRcdFx0PGVsLW9wdGlvbiBsYWJlbD1cIlRlbFwiIHZhbHVlPVwiM1wiIC8+XG5cdFx0XHRcdDwvZWwtc2VsZWN0PlxuXHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDx0ZW1wbGF0ZSAjYXBwZW5kPlxuXHRcdFx0XHQ8ZWwtYnV0dG9uIDppY29uPVwiU2VhcmNoXCIgLz5cblx0XHRcdDwvdGVtcGxhdGU+XG5cdFx0PC9lbC1pbnB1dD5cblx0PC9kaXY+XG5cblx0PGRpdj5cblx0XHQ8ZGl2PmF2YWlsYWJsZSB1c2FnZSBpbiBmYWN0PC9kaXY+XG5cdFx0PGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgY2xhc3M9XCJpbnB1dC13aXRoLXNlbGVjdFwiPlxuXHRcdFx0PHRlbXBsYXRlICNwcmVwZW5kPlxuXHRcdFx0XHQ8ZWwtc2VsZWN0IHYtbW9kZWw9XCJzZWxlY3RcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDExMHB4XCI+XG5cdFx0XHRcdFx0PGVsLW9wdGlvbiBsYWJlbD1cIlJlc3RhdXJhbnRcIiB2YWx1ZT1cIjFcIiAvPlxuXHRcdFx0XHRcdDxlbC1vcHRpb24gbGFiZWw9XCJPcmRlciBOby5cIiB2YWx1ZT1cIjJcIiAvPlxuXHRcdFx0XHRcdDxlbC1vcHRpb24gbGFiZWw9XCJUZWxcIiB2YWx1ZT1cIjNcIiAvPlxuXHRcdFx0XHQ8L2VsLXNlbGVjdD5cblx0XHRcdDwvdGVtcGxhdGU+XG5cdFx0XHQ8dGVtcGxhdGUgI2FwcGVuZD5cblx0XHRcdFx0PGVsLWJ1dHRvbj5cblx0XHRcdFx0XHQ8ZWwtaWNvbj5cblx0XHRcdFx0XHRcdDxTZWFyY2ggLz5cblx0XHRcdFx0XHQ8L2VsLWljb24+XG5cdFx0XHRcdDwvZWwtYnV0dG9uPlxuXHRcdFx0PC90ZW1wbGF0ZT5cblx0XHQ8L2VsLWlucHV0PlxuXHQ8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

Copy the third example in [this doc](https://element-plus.org/en-US/component/input.html#mixed-input) and cannot render icon correctly.

### What is Expected?

Render icons while using icon class like document.

### What is actually happening?

Must use el-icon tag in other component.

### Additional comments

Many documents of other components(Button, Input and etc.) are using icon-class writing but [the document of Icon](https://element-plus.org/en-US/component/icon.html) used el-icon tag writing only. So I guess it's a outdated document problem, or a bug?

## Update

It occured when using Options API only. But I cannot find any tips about Options API in document.

I think it's a bug unless el-icon is not support for Options API.

**Comment by KiritaniAyaka** [comment]
@chenxch 
Thanks! It's solved. Sorry for my shallow understanding to Composition API.

**Comment by chenxch** [comment]
@KiritaniAyaka There is a first step in everything, I hope `element-plus` can be the trigger for you to start the journey of Composition API. 😊
