### ISSUE TITLE
[Bug Report] [Component] [input] 使用render对input组件渲染modelValue未正常响应

### ISSUE THREAD

**Issue by Cenmingyang** [element-plus/element-plus#7239]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCA+XG5pbXBvcnQgeyBoLHJlYWN0aXZlLCByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gXCJ2dWVcIjtcbmNvbnN0IGVsZW1lbnRDb21wb25lbnRzID0gZ2V0Q3VycmVudEluc3RhbmNlKCkuYXBwQ29udGV4dC5jb21wb25lbnRzO1xuXG5jbGFzcyBjb21tb25Nb2R1bGUge1xuICAgIGNyZWF0ZUZvcm0oY29uc3RpdHV0ZSA9IHsgZXZlbnQ6IHt9LCBhdHRyaWJ1dGVzOiB7fSwgcmVmOiBcIlwiIH0pIHtcbiAgICAgICAgcmV0dXJuIHtcbiAgICAgICAgICAgIHJlbmRlcjogZnVuY3Rpb24oKSB7XG4gICAgICAgICAgICAgICAgcmV0dXJuIGgoXG4gICAgICAgICAgICAgICAgICAgIC8vIOe7hOS7tlxuICAgICAgICAgICAgICAgICAgICBjb25zdGl0dXRlLnZub2RlLkVsRm9ybSxcbiAgICAgICAgICAgICAgICAgICAgLy8g57uE5Lu255qEYXR0cmlidXRlc+WSjGV2ZW50XG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICAgIC4uLmNvbnN0aXR1dGUuYXR0cmlidXRlcyxcbiAgICAgICAgICAgICAgICAgICAgICAgIC4uLmNvbnN0aXR1dGUuZXZlbnQsXG4gICAgICAgICAgICAgICAgICAgICAgICByZWY6IGNvbnN0aXR1dGUucmVmLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgICAoKSA9PiB7XG4gICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gW1xuICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnN0aXR1dGUudm5vZGVDaGlsZHJlbkRhdGEubWFwKGl0ZW0gPT4ge1xuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gaChjb25zdGl0dXRlLnZub2RlLkVsRm9ybUl0ZW0sIHtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC4uLml0ZW0uZWxGb3JtSXRlbVxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9LCAoKSA9PiB7XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb25zb2xlLmxvZyhpdGVtKTtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiBoKGNvbnN0aXR1dGUudm5vZGVbaXRlbS5uYW1lXSwge1xuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC4uLml0ZW0uZm9ybUl0ZW1BdHRyaWJ1dGVzLFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8vIG9uQ2hhbmdlOiAodmFsKSA9PiB7XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLy8gICAgIGNvbnNvbGUubG9nKHZhbCk7XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLy8gfSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvLyBvbklucHV0OiBmdW5jdGlvbih2YWwpIHtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvLyAgICAgY29uc29sZS5sb2coY29uc3RpdHV0ZS52bm9kZVtpdGVtLm5hbWVdKTtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvLyAgICAgaXRlbS5mb3JtSXRlbUF0dHJpYnV0ZXMubW9kZWxWYWx1ZSA9IHZhbFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8vIH1cblxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSlcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSlcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICB9KSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0aGlzLiRzbG90cy5kZWZhdWx0KClcbiAgICAgICAgICAgICAgICAgICAgICAgIF1cbiAgICAgICAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgICAgIClcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH1cbn1cbmNvbnN0IGNyZWF0ZUNvbXBvbmVudHMgPSBuZXcgY29tbW9uTW9kdWxlKCk7XG5cbmNvbnN0IGZvcm1JdGVtTGlzdCA9IHJlYWN0aXZlKFtcbiAge1xuICAgIG5hbWU6IFwiRWxJbnB1dFwiLFxuICAgIGVsRm9ybUl0ZW06IHtcbiAgICAgIGxhYmVsOiBcIua1i+ivlVwiLFxuICAgIH0sXG4gICAgZm9ybUl0ZW1BdHRyaWJ1dGVzOiB7XG4gICAgICBwbGFjZWhvbGRlcjogXCLmtYvor5VcIixcbiAgICAgIG1vZGVsVmFsdWU6IDY2NjY2NixcbiAgICB9LFxuICAgIGZvcm1JdGVtRXZlbnQ6IHt9LFxuICB9LFxuICB7XG4gICAgbmFtZTogXCJFbFNlbGVjdFwiLFxuICAgIGVsRm9ybUl0ZW06IHtcbiAgICAgIGxhYmVsOiBcIua1i+ivlVwiLFxuICAgIH0sXG4gICAgZm9ybUl0ZW1BdHRyaWJ1dGVzOiB7XG4gICAgICBwbGFjZWhvbGRlcjogXCLmtYvor5VcIixcbiAgICAgIG1vZGVsVmFsdWU6IDY2NjY2NixcbiAgICB9LFxuICAgIGZvcm1JdGVtRXZlbnQ6IHt9LFxuICB9LFxuXSk7XG5cbmNvbnN0IHNpbm9Gb3JtID0gY3JlYXRlQ29tcG9uZW50cy5jcmVhdGVGb3JtKHtcbiAgdm5vZGU6IGVsZW1lbnRDb21wb25lbnRzLFxuICB2bm9kZUNoaWxkcmVuRGF0YTogZm9ybUl0ZW1MaXN0LFxufSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgIHt7IGZvcm1JdGVtTGlzdFswXS5mb3JtSXRlbUF0dHJpYnV0ZXMubW9kZWxWYWx1ZSB9fVxuICAgIDxzaW5vRm9ybT5cbiAgICAgIDwhLS0gPGVsLWZvcm0taXRlbSBsYWJlbD1cIua1i+ivlVwiPlxuICAgICAgICA8ZWwtaW5wdXQgY2xlYXJhYmxlIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT4gLS0+XG4gICAgICA8IS0tIOiHquWumuS5ieihqOWNleWGheWuuSAtLT5cbiAgICAgIDxzbG90IG5hbWU9XCJzaW5vRm9ybVNsb3RcIj48L3Nsb3Q+XG4gICAgPC9zaW5vRm9ybT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

最小复现环境的链接内附有代码

### What is Expected?

输入框可以正常进行数据双向绑定

### What is actually happening?

输入框无法正常输入

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[v-model](https://staging-cn.vuejs.org/guide/extras/render-function.html#v-model) 希望能解答你的疑问
