### ISSUE TITLE
date-picker 组件不显示日期

### ISSUE THREAD

**Issue by kqwork** [element-plus/element-plus#724]
初步检查，发现
// node_modules\element-plus\lib\el-time-picker\index.js 
`
ctx.emit('set-picker-option', ['formatToString', formatToString]);
`

触发之后，
`onSetPickerOption()`并没有被回调，从而导致
`displayValue`计算属性中`!pickerOptions.value.panelReady`为`true`，直接返回。

**Comment by JeremyWuuuuu** [comment]
This is related to `Vue`'s change, duplicate with #678 , I am fixing it right now, will be fixed soon.

**Comment by JeremyWuuuuu** [comment]
Fixed via #729
