### ISSUE TITLE
[Bug Report] [Component] el-image 会触发俩次click事件

### ISSUE THREAD

**Issue by wang-weilin** [element-plus/element-plus#7242]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IHVuZm9sZCA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2luaXREYXRhLmluZm89PT09PScpXG4gIGFsZXJ0KDExMSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuIDxlbC1pbWFnZVxuICAgICAgICAgICBzdHlsZT1cIndpZHRoOiAyNHB4OyBoZWlnaHQ6IDI0cHg7XCJcbiAgICAgICAgICAgc3JjPVwiaHR0cDovL2ltZ3MyLmpkZG1vdG8uY29tL2F2YXRhci8yMDIyMDMzMS8xNjQ4NzEwMTkxMjU3X0JiVXJ4cy5qcGdcIlxuICAgICAgICAgICBAY2xpY2s9XCJ1bmZvbGRcIlxuICAgICAgICAgICA+PC9lbC1pbWFnZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

点击图片会打印俩次log

### What is Expected?

只触发一次click

### What is actually happening?

实际触发俩次click

### Additional comments

所有的el-image都会触发，目前只能用div包裹，事件发在div上，比较急

**Comment by chenxch** [comment]
Sorry, I didn't reproduce it in your demo, are you checking?

**Comment by wang-weilin** [comment]
> Sorry, I didn't reproduce it in your demo, are you checking?



> Sorry, I didn't reproduce it in your demo, are you checking?

This is a must for me. Clicking on the picture will pop up the alert pop-up window twice.
"vue": "3.2.32",
"vite": "2.9.1",
"element-plus": "2.1.9"

At present, my processing method is to add stop before the click event, prevent the event mechanism, or wrap the div outside the imag.

I don't know why you haven't reproduced this strange problem on your side

Example link:https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IHVuZm9sZCA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2luaXREYXRhLmluZm89PT09PScpXG4gIGFsZXJ0KDExMSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuIDxlbC1pbWFnZVxuICAgICAgICAgICBzdHlsZT1cIndpZHRoOiAyNHB4OyBoZWlnaHQ6IDI0cHg7XCJcbiAgICAgICAgICAgc3JjPVwiaHR0cDovL2ltZ3MyLmpkZG1vdG8uY29tL2F2YXRhci8yMDIyMDMzMS8xNjQ4NzEwMTkxMjU3X0JiVXJ4cy5qcGdcIlxuICAgICAgICAgICBAY2xpY2s9XCJ1bmZvbGRcIlxuICAgICAgICAgICA+PC9lbC1pbWFnZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0cy5qc29uIjoiIiwiX28iOnt9fQ==
