### ISSUE TITLE
[Bug Report] [Component] [select, table] el-table header will obscure el-tooltip when table is below the select.

### ISSUE THREAD

**Issue by il-1337** [element-plus/element-plus#7245]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.6`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome/100.0.4896.127; Intel Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCB7IFVzZXIgfSBmcm9tIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjtcblxuY29uc3QgbXNnID0gcmVmKFwiSGVsbG8gV29ybGQhXCIpO1xuY29uc3Qgc2VsZWN0ZWQgPSByZWYoXCJcIik7XG5jb25zdCBvcHRpb25zID0gcmVmKFxuICBBcnJheSgxMClcbiAgICAuZmlsbCgwKVxuICAgIC5tYXAoKF8sIGluZGV4KSA9PiBgbG9uZyBsb25nIGxvbmcgbG9uZyR7aW5kZXh9YClcbik7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwic2VsZWN0ZWRcIiBtdWx0aXBsZSBjb2xsYXBzZS10YWdzIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcD5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIm9wdGlvbiBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJvcHRpb25cIlxuICAgICAgOmxhYmVsPVwib3B0aW9uXCJcbiAgICAgIDp2YWx1ZT1cIm9wdGlvblwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxlbC10YWJsZT5cbiAgXHQ8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJuYW1lXCIvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

Select some options and move the cursor over the tag.

### What is Expected?

Table header should not  obscure tooltip.

### What is actually happening?

Table header obscures tooltip.

### Additional comments

_(empty)_

<img width="394" alt="image" src="https://user-images.githubusercontent.com/37065548/163953885-50ce85f8-f0b5-41c5-bc36-d263ece94376.png">

**Comment by tolking** [comment]
Fixed in #8768
