### ISSUE TITLE
[Bug Report] [Component] [select] el-select 在el-dialog中第二次进入无法展示

### ISSUE THREAD

**Issue by wang-weilin** [element-plus/element-plus#7247]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdERhdGEgPSByZWFjdGl2ZSh7XG4gIGRpYWxvZ1Zpc2libGU6ZmFsc2UsXG4gIHBhcnRpY2lwYXRlV2F5OicnXG59KVxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgaW5pdERhdGEuZGlhbG9nVmlzaWJsZSA9IHRydWVcbn1cbmNvbnN0IGNsb3NlID0gKCkgPT4ge1xuICBpbml0RGF0YS5kaWFsb2dWaXNpYmxlID0gZmFsc2Vcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gIEBjbGljaz1cIm9wZW5cIj5vcGVuPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gIEBjbGljaz1cImNsb3NlXCI+Y2xvc2U8L2VsLWJ1dHRvbj5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiaW5pdERhdGEuZGlhbG9nVmlzaWJsZVwiIHRpdGxlPVwi6YWN572uXCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cImluaXREYXRhLnBhcnRpY2lwYXRlV2F5XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDMxMHB4OyBtYXJnaW4tbGVmdDogMTBweDtcIlxuICAgICA+XG4gICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuWPo+S7pFwiIHZhbHVlPVwiMVwiPjwvZWwtb3B0aW9uPlxuICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCLliIbkuqtcIiB2YWx1ZT1cIjJcIiBkaXNhYmxlZD48L2VsLW9wdGlvbj5cbiAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5YWz5rOoXCIgdmFsdWU9XCIzXCIgZGlzYWJsZWQ+PC9lbC1vcHRpb24+XG4gICAgIDwvZWwtc2VsZWN0PlxuICA8L2VsLWRpYWxvZz5cbiAgICBcbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

第一次打开弹窗可以正常进行选择，关闭弹窗后，在次打开弹窗，里面的el-select,无法展示

### What is Expected?

每次都可以正常展示el-select里面的下拉选项

### What is actually happening?

第二次以后一直无法展示下拉选项

### Additional comments

_(empty)_

**Comment by Half-A-Turnip** [comment]
可以啊，注意新版本。应该是上个版本的bug

**Comment by chenxch** [comment]
If the issue is resolved, the issue can be closed.
