### ISSUE TITLE
[Feature Request] [menu] Menu的 unique-opened 是干什么用的？试了半天没试出来

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7250]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `menu`

### Additional comments

_(empty)_

**Comment by hoowhoami** [comment]
菜单的手风琴效果

**Comment by Edric-Li** [comment]
@hoowhoami  能简单的通过Playground  做个Demo么，不太明白。
