### ISSUE TITLE
[Bug Report] [Style] [table, image] el-image preview-src-list 在el-table中 点击大图预览时，出现表格边框

### ISSUE THREAD

**Issue by yokochen222** [element-plus/element-plus#7253]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.9`
- Browser / OS: `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblx0Y29uc3QgdGFibGVEYXRhID0gW1xuICAgIHtcbiAgICAgIGxvZ286IFwiaHR0cHM6Ly9pbWcuemNvb2wuY24vY29tbXVuaXR5LzAxNzJmODU4ZTVlNGI0YTgwMTIxOWM3NzAxOTMwNS5qcGc/eC1vc3MtcHJvY2Vzcz1pbWFnZS9hdXRvLW9yaWVudCwxL3Jlc2l6ZSxtX2xmaXQsd18yMDAsbGltaXRfMS9zaGFycGVuLDEwMC9mb3JtYXQsd2VicC9xdWFsaXR5LFFfMTAwXCIsXG4gICAgICBuYW1lOiBcIua1i+ivlVwiXG4gICAgfVxuICBdO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibG9nb1wiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwie3Jvd31cIj5cbiAgICAgICAgPGVsLWltYWdlIDpzcmM9XCJyb3cubG9nb1wiIDpwcmV2aWV3LXNyYy1saXN0PVwiW3Jvdy5sb2dvXVwiPjwvZWwtaW1hZ2U+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

点击表格中图片大图预览，出现 层级不对问题

### What is Expected?

点击表格中图片大图预览，正常显示

### What is actually happening?

点击表格中图片大图预览，出现 表格层 超出 图片预览层

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[here](https://element-plus.org/zh-CN/component/table.html#%E5%A6%82%E4%BD%95%E5%9C%A8%E8%A1%A8%E6%A0%BC%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%9B%BE%E5%83%8F%E9%A2%84%E8%A7%88%EF%BC%9F)

**Comment by chenxch** [comment]
If the problem is solved, you can close the issue.
