### ISSUE TITLE
[Bug Report] [Docs] [config-provider] Config Provider全局配置组件，namespaces名称错误

### ISSUE THREAD

**Issue by chinaBoyXin** [element-plus/element-plus#7255]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-config-provider`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/config-provider.html#%E5%AE%9E%E9%AA%8C%E6%80%A7%E5%8A%9F%E8%83%BD)

### Steps to reproduce

1.使用Config Provider组件自定义全局组件类名时，发现namespaces属性不生效
2.阅读源码发现，buildProps方法中属性名为namespace
3.更改后，自定义类名生效

### What is Expected?

namespaces属性生效

### What is actually happening?

namespaces属性不生效

### Additional comments

_(empty)_

**Comment by a15218378694** [comment]
请问类名改成功后, 你的样式生效了吗 ? 我这边不生效

**Comment by chinaBoyXin** [comment]
> 请问类名改成功后, 你的样式生效了吗 ? 我这边不生效

在main.ts中引入css文件，是有生效的

**Comment by a15218378694** [comment]
> > 请问类名改成功后, 你的样式生效了吗 ? 我这边不生效
> 
> 在main.ts中引入css文件，是有生效的

可以发下你微信吗 ? 十万火急, 麻烦了

**Comment by chinaBoyXin** [comment]
你加我QQ吧 550367854




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月21日(星期四) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Bug Report] [Docs] [config-provider] Config Provider全局配置组件，namespaces名称错误 (Issue #7255)





   
请问类名改成功后, 你的样式生效了吗 ? 我这边不生效
  
在main.ts中引入css文件，是有生效的
  
可以发下你微信吗 ? 十万火急, 麻烦了

**Comment by chinaBoyXin** [comment]
> > > 请问类名改成功后, 你的样式生效了吗 ? 我这边不生效
> > 
> > 
> > 在main.ts中引入css文件，是有生效的
> 
> 可以发下你微信吗 ? 十万火急, 麻烦了

你加我QQ吧 550367854

**Comment by a15218378694** [comment]
> > > > 请问类名改成功后, 你的样式生效了吗 ? 我这边不生效
> > > 
> > > 
> > > 在main.ts中引入css文件，是有生效的
> > 
> > 
> > 可以发下你微信吗 ? 十万火急, 麻烦了
> 
> 你加我QQ吧 550367854

已加
