### ISSUE TITLE
[Bug Report] [Style] [tag] The tag component always has a border when using the color prop,Component cannot remove border even with hit prop

### ISSUE THREAD

**Issue by guxin0123** [element-plus/element-plus#7258]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/100.0.4896.127`
- Build Tool: `Vite`

### Related Component

- `el-tag`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXAgZ2FwLTIgbXktMlwiPlxuICAgIDxlbC10YWdcbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBpdGVtc1wiXG4gICAgICA6a2V5PVwiaXRlbS5sYWJlbFwiXG4gICAgICBjb2xvcj1cIiNjY2NcIlxuICAgICAgY2xhc3M9XCJteC0xXCJcbiAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgcm91bmRcbiAgICAgICAgICAgIDpoaXQ9XCJmYWxzZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5sYWJlbCB9fVxuICAgIDwvZWwtdGFnPlxuICA8L2Rpdj5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5pbXBvcnQgdHlwZSB7IFRhZ1Byb3BzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG50eXBlIEl0ZW0gPSB7IHR5cGU6IFRhZ1Byb3BzWyd0eXBlJ107IGxhYmVsOiBzdHJpbmcgfVxuXG5jb25zdCBpdGVtcyA9IHJlZjxBcnJheTxJdGVtPj4oW1xuICB7IHR5cGU6ICcnLCBsYWJlbDogJ1RhZyAxJyB9LFxuICB7IHR5cGU6ICdzdWNjZXNzJywgbGFiZWw6ICdUYWcgMicgfSxcbiAgeyB0eXBlOiAnaW5mbycsIGxhYmVsOiAnVGFnIDMnIH0sXG4gIHsgdHlwZTogJ2RhbmdlcicsIGxhYmVsOiAnVGFnIDQnIH0sXG4gIHsgdHlwZTogJ3dhcm5pbmcnLCBsYWJlbDogJ1RhZyA1JyB9LFxuXSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

```vue
<template>
  <div class="flex flex-wrap gap-2 my-2">
    <el-tag
      v-for="item in items"
      :key="item.label"
      color="#ccc"
      class="mx-1"
      effect="dark"
      round
      :hit="false"
    >
      {{ item.label }}
    </el-tag>
  </div>
  
</template>

<script lang="ts" setup>
import { ref } from 'vue'

import type { TagProps } from 'element-plus'

type Item = { type: TagProps['type']; label: string }

const items = ref<Array<Item>>([
  { type: '', label: 'Tag 1' },
  { type: 'success', label: 'Tag 2' },
  { type: 'info', label: 'Tag 3' },
  { type: 'danger', label: 'Tag 4' },
  { type: 'warning', label: 'Tag 5' },
])
</script>
```

### What is Expected?

tag has no border

### What is actually happening?

tag has a border

### Additional comments

_(empty)_

**Comment by josonho** [comment]
hi~

The hit property does not correspond to border,

is a stroke different from the border.

A less elegant way is to modify the border style when using, as follows

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXAgZ2FwLTIgbXktMlwiPlxuICAgIDxlbC10YWdcbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBpdGVtc1wiXG4gICAgICA6a2V5PVwiaXRlbS5sYWJlbFwiXG4gICAgICBjb2xvcj1cIiNjY2NcIlxuXHRcdFx0c3R5bGU9XCJib3JkZXItY29sb3I6ICNjY2NcIlxuICAgICAgY2xhc3M9XCJteC0xXCJcbiAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgcm91bmRcbiAgICAgIDpoaXQ9XCJmYWxzZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5sYWJlbCB9fVxuICAgIDwvZWwtdGFnPlxuICA8L2Rpdj5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5pbXBvcnQgdHlwZSB7IFRhZ1Byb3BzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG50eXBlIEl0ZW0gPSB7IHR5cGU6IFRhZ1Byb3BzWyd0eXBlJ107IGxhYmVsOiBzdHJpbmcgfVxuXG5jb25zdCBpdGVtcyA9IHJlZjxBcnJheTxJdGVtPj4oW1xuICB7IHR5cGU6ICcnLCBsYWJlbDogJ1RhZyAxJyB9LFxuICB7IHR5cGU6ICdzdWNjZXNzJywgbGFiZWw6ICdUYWcgMicgfSxcbiAgeyB0eXBlOiAnaW5mbycsIGxhYmVsOiAnVGFnIDMnIH0sXG4gIHsgdHlwZTogJ2RhbmdlcicsIGxhYmVsOiAnVGFnIDQnIH0sXG4gIHsgdHlwZTogJ3dhcm5pbmcnLCBsYWJlbDogJ1RhZyA1JyB9LFxuXSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by guxin0123** [comment]
Okay thank you，
Hope there is an elegant way to use it。
