### ISSUE TITLE
使用{{scope.$index }} 在table中显示为

### ISSUE THREAD

**Issue by xiaomengqi123** [element-plus/element-plus#726]
![image](https://user-images.githubusercontent.com/33782250/100578739-d7a64b80-331d-11eb-8556-f8e477dd2736.png)
![image](https://user-images.githubusercontent.com/33782250/100578773-ec82df00-331d-11eb-898d-600801853a0a.png)

**Comment by xiaomengqi123** [comment]
![image](https://user-images.githubusercontent.com/33782250/100579490-4afc8d00-331f-11eb-84be-55c963d957f6.png)
Please help me sort it out. Thank you

**Comment by xiaomengqi123** [comment]
![image](https://user-images.githubusercontent.com/33782250/100579751-bb0b1300-331f-11eb-9aaa-aea646e5f12c.png)
Please help me sort it out. Thank you

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by JeremyWuuuuu** [comment]
Could you provide minimal reproducible code or link?

**Comment by justwiner** [comment]
i get it.
fixed. It's just that the code hasn't been pushed.
@JeremyWuuuuu

**Comment by PurpleDandelion** [comment]
I have the same problem.just because $index is undefined

**Comment by justwiner** [comment]
```js
const data: RenderRowData = {
          ... ...
          $index: index_,
}
```
