### ISSUE TITLE
[Bug Report] [Component] [table] el-table 样式问题

### ISSUE THREAD

**Issue by 1123Javayanglei** [element-plus/element-plus#7262]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/yanglei/qy3bhtw0/2/)

### Steps to reproduce

<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <script src="https://unpkg.com/vue@next"></script>
  
  <link rel="stylesheet" href="https://unpkg.com/element-plus@2.1.10/theme-chalk/index.css">
  
  <script src="https://unpkg.com/element-plus@2.1.10/dist/index.full.js"></script>
  <title>Element Plus demo</title>
</head>
<body>
<div id="app">
  <el-button>{{ message }}</el-button>

  <el-table :data="tableData" style="width: 100%">
    <el-table-column prop="date" label="Date" width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </el-table>
</div>
<script>
const tableData = [
    {
      date: '2016-05-03',
      name: 'Tom',
      address: 'No. 189, Grove St, Los Angeles',
    },
    {
      date: '2016-05-02',
      name: 'Tom',
      address: 'No. 189, Grove St, Los Angeles',
    },
    {
      date: '2016-05-04',
      name: 'Tom',
      address: 'No. 189, Grove St, Los Angeles',
    },
    {
      date: '2016-05-01',
      name: 'Tom',
      address: 'No. 189, Grove St, Los Angeles',
    },
  ]
  const App = {
    data() {
      return {
        message: "Hello Element Plus",
        tableData
      };
    },
  };
  const app = Vue.createApp(App);
  app.use(ElementPlus);
  app.mount("#app");
</script>
</body>
</html>

### What is Expected?

给出解决方案

### What is actually happening?

在 html 页面中，通过 script 和 link 标签导入 css 和 js ，el-table 的样式有问题

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
sry, I can't open your demo, you can see if it's the same problem as #7232

**Comment by 1123Javayanglei** [comment]
> sry, I can't open your demo, you can see if it's the same problem as #7232 

好的 解决问题了 但是我是直接 copy 官方的文档[el-table](https://github.com/element-plus/element-plus/blame/dev/docs/examples/table/basic.vue) 文档是否要更新一下讷
