### ISSUE TITLE
[Bug Report] [TypeScript] [time-select] Use the "vue-tsc" command to check ts and report an error: "Cannot find name 'ComponentSize'. type: import("vue").PropType<ComponentSize>;", without "{skipLibCheck: true}" in "tsconfig.ts"

### ISSUE THREAD

**Issue by 363797271** [element-plus/element-plus#7265]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `Microsoft Edge 100.0.1185.44/ Window 10 19044.1586`
- Build Tool: `Vite`

### Related Component

- `el-time-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

First of all, the link of reproduction is meaningless. Please ignore it
1. Vite create Vue application
2. Use automatic import to import element plus components on demand
3. run "npm run build"("vue-tsc --noEmit && vite build")

### What is Expected?

Run successfully without error

### What is actually happening?

```shell
node_modules/element-plus/es/components/time-select/index.d.ts:108:38 - error TS2304: Cannot find name 'ComponentSize'.
108         type: import("vue").PropType<ComponentSize>;

node_modules/element-plus/es/components/time-select/index.d.ts:277:38 - error TS2304: Cannot find name 'ComponentSize'.
277         type: import("vue").PropType<ComponentSize>;

node_modules/element-plus/lib/components/time-select/index.d.ts:108:38 - error TS2304: Cannot find name 'ComponentSize'.
108         type: import("vue").PropType<ComponentSize>;

node_modules/element-plus/lib/components/time-select/index.d.ts:277:38 - error TS2304: Cannot find name 'ComponentSize'.
277         type: import("vue").PropType<ComponentSize>;


Found 4 errors in 2 files.

Errors  Files
     2  node_modules/element-plus/es/components/time-select/index.d.ts:108
     2  node_modules/element-plus/lib/components/time-select/index.d.ts:108
```

### Additional comments

I found that the reason is that the `node_modules\element-plus\lib\components\time-select\index.d.ts` file uses an `ComponentSize` that was not imported：

```js
type: import("vue").PropType<ComponentSize>;
```

I found that none of the other components are using it anymore.

At present, I can only temporarily solve this problem by configure `{skiplibcheck: true}` in `tsconfig.ts`.

I hope the authorities will find and solve it, or tell me a scientific way

**Comment by h3poteto** [comment]
Mee too

**Comment by sxzz** [comment]
Just enable `skipLibCheck`

refs:
- https://github.com/vuejs/vue-cli/pull/5688
- https://github.com/vuejs/vue-cli/pull/5688
