### ISSUE TITLE
希望级联面板可以添加全选和头部文本

### ISSUE THREAD

**Issue by giserman001** [element-plus/element-plus#727]
希望级联面板可以添加全选和头部文本

**Comment by giserman001** [comment]
列如： ![image](https://user-images.githubusercontent.com/24283342/100580284-9cf1e280-3320-11eb-8e9d-73ab30bfd472.png)

**Comment by giserman001** [comment]
![image](https://user-images.githubusercontent.com/24283342/100580337-b430d000-3320-11eb-919b-2d3ac6148de3.png)

**Comment by giserman001** [comment]
![image](https://user-images.githubusercontent.com/24283342/100580436-e17d7e00-3320-11eb-8651-1d64c2c57f95.png)

**Comment by SimonaliaChen** [comment]
Hi, could you be more specific about the features you mentioned？

**Comment by JeremyWuuuuu** [comment]
![IMG_5674](https://user-images.githubusercontent.com/15975785/100747289-d0b23280-341c-11eb-87be-544fd6906f60.JPG)
@SimonaliaChen Like this.

**Comment by SimonaliaChen** [comment]
> ![IMG_5674](https://user-images.githubusercontent.com/15975785/100747289-d0b23280-341c-11eb-87be-544fd6906f60.JPG)
> @SimonaliaChen Like this.

@giserman001 If this is what you want, I'm sure it's valuable in some scenarios. But I think it's kind of too customized to exist in a common ui library, especially the `caption`. We need designer involved which might take a long time. As for `check all`, it does make some convenience in `checkStrictly` mode, we will figure it out in out later stable version.
