### ISSUE TITLE
[Bug Report] [TypeScript] [form] 【TS】ElForm 的 FormInstance 无法引用？

### ISSUE THREAD

**Issue by AsherSun** [element-plus/element-plus#7275]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.10`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39'`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbi8vIOWcqHZzY29kZSDkuK3ml6Dms5Xmib7liLBGb3JtSW5zdGFuY2Vcbi8vIHZzY29kZSDkvJrnu5nmiqXplJnmj5DnpLrvvIzor6bmg4Xor7fnnItpc3N1c2XkuK3nmoTmiKrlm75cbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuY29uc3QgZm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KCk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSByZWY9XCJmb3JtUmVmXCI+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICBcdDxlbC1pbnB1dCBwbGFjZWhvbGRlcj1cIuWcqHZzY29kZSDkuK3ml6Dms5Xmib7liLBGb3JtSW5zdGFuY2VcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

无法引用FormInstance

### What is Expected?

可以引用FormInstance

### What is actually happening?

无法引用FormInstance

### Additional comments

详细信息请看issue中的截图

![image](https://user-images.githubusercontent.com/28916706/164195590-631fc482-5ef7-44b4-bb58-b24433a3c312.png)

**Comment by Yangeyu** [comment]
可能是element-plus版本不对， 1.x.x版本没有暴露该类型

**Comment by AsherSun** [comment]
> 

已经好了，谢谢

**Comment by machangzhi** [comment]
怎么解决的楼主？

**Comment by rashagu** [comment]
> 怎么解决的楼主？

import type { ElForm } from 'element-plus'
type FormInstance = InstanceType<typeof ElForm>

**Comment by liuguangsen0409** [comment]
怎么解决的？v2.1.11 还是不行啊
