### ISSUE TITLE
[Bug Report] [Component] [affix] el-affix固钉组件无法监听自定义滚动条，只能监听body的滚动条

### ISSUE THREAD

**Issue by kaivin** [element-plus/element-plus#7276]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome 100.0.4896.127`
- Build Tool: `Vite`

### Related Component

- `el-affix`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGNvdW50ID0gcmVmKDApXG5jb25zdCBsb2FkID0gKCkgPT4ge1xuICBjb3VudC52YWx1ZSArPSAyXG59XG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8IS0tIEVsZW1lbnQgUGx1cyBpY29ucyAtLT5cbiAgPGRpdiB2LWluZmluaXRlLXNjcm9sbD1cImxvYWRcIiBjbGFzcz1cImluZmluaXRlLWxpc3RcIiBzdHlsZT1cIm92ZXJmbG93OiBhdXRvXCI+XG4gIFx0PGVsLWFsZXJ0IHRpdGxlPVwi5peg6ZmQ5rua5Yqo5YiX77yM6Ieq5a6a5LmJ5rua5Yqo5p2h77yM5Zu66ZKJ5peg5rOV5q2j5bi45ZC46aG244CCXCIgdHlwZT1cInN1Y2Nlc3NcIiA6Y2xvc2FibGU9XCJmYWxzZVwiIHNob3ctaWNvbiAvPlxuICAgIDxlbC1hZmZpeCA6b2Zmc2V0PVwib2Zmc2V0SGVpZ2h0XCIgdGFyZ2V0PVwiLmluZmluaXRlLWxpc3RcIj5cbiAgICAgICAgPGVsLWNhcmQgc2hhZG93PVwiaG92ZXJcIj5cbiAgICAgICAgICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiPlxuICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWQjeensFwiPlxuICAgICAgICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cInZhbHVlMVwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5ZCN56ewXCIgLz5cbiAgICAgICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgICAgICAgICAgPGVsLWZvcm0taXRlbT48ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+5p+l6K+iPC9lbC1idXR0b24+PC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgICAgPC9lbC1mb3JtPlxuICAgICAgICA8L2VsLWNhcmQ+XG4gICAgICBcdDxkaXYgdi1mb3I9XCJpIGluIGNvdW50XCIgOmtleT1cImlcIiBjbGFzcz1cImluZmluaXRlLWxpc3QtaXRlbVwiPnt7IGkgfX08L2Rpdj5cbiAgICAgIDwvZWwtYWZmaXg+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi5pbmZpbml0ZS1saXN0IHtcbiAgaGVpZ2h0OiAxMDB2aDtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwO1xuICBsaXN0LXN0eWxlOiBub25lO1xufVxuLmluZmluaXRlLWxpc3QgLmluZmluaXRlLWxpc3QtaXRlbSB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBoZWlnaHQ6IDUwcHg7XG4gIGJhY2tncm91bmQ6IHZhcigtLWVsLWNvbG9yLXByaW1hcnktbGlnaHQtOSk7XG4gIG1hcmdpbjogMTBweDtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xufVxuLmluZmluaXRlLWxpc3QgLmluZmluaXRlLWxpc3QtaXRlbSArIC5saXN0LWl0ZW0ge1xuICBtYXJnaW4tdG9wOiAxMHB4O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

使用自定义滚动条或者el-scrollbar滚动条，在容器内使用el-affix固钉组件，滚动容器，固钉无法正常吸顶

### What is Expected?

在使用滚动加载组件时，使用固钉组件，滚动条为自定义滚动条，滚动后固钉需要能正常吸顶

### What is actually happening?

自定义滚动条下滚动时无法正常吸顶，只有在resize时会吸顶

### Additional comments

这个问题我通过修改组件的源码实现了解决，需要修改es/components/affix/src/affix2.mjs文件和lib/components/affix/src/affix2.js文件内的handleScroll方法，在方法开始的地方调用一下updateRoot()，就可以实现自定义滚动条下固钉正常吸顶效果，我自己写了vite插件替换官方原始文件在自己项目中使用，希望官方能将该组件的这个BUG修复

**Comment by nieyuyao** [comment]
默认的滚动在body上的，这是在`useElementBounding`中处理的。这导致自定义的滚动无法被触发

https://github.com/element-plus/element-plus/blob/aef38eac114d0d1269591106ad3ef4c7f21f587f/packages/components/affix/src/affix.vue#L35-L41

如果将updateRoot方法也expose出去，这样外层组件可以自己监听并处理滚动事件了🤔。

**Comment by libaiyun** [comment]
同样的问题，官方的两个组件组合使用会失效就不太合理
