### ISSUE TITLE
[Feature Request] [Enhancement] [table-column] table组件的show-overflow-tooltip能否改进tooltip的消失方式

### ISSUE THREAD

**Issue by xjtarzan** [element-plus/element-plus#7277]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `table-column`

## Description

开启show-overflow-tooltip后，单元格里的超长内容被截断隐藏了，完整的超长内容则会显示在单元格上方的tooltip里面，但是鼠标刚移上去就tooltip就消失了，请问我想把超长内容完整的复制下来应该怎么做？ 对于一个普通用户并不会开启开发者控制台定位这个元素。
是否可以改进tooltip的响应区域，在鼠标移入tooltip范围内时也保持显示，而不是移开表格的单元格就消失了呢？

### Additional comments

_(empty)_

**Comment by hoowhoami** [comment]
鼠标3击单元格内容，然后command+c 或 ctrl+c复制即可。

**Comment by xjtarzan** [comment]
> 鼠标3击单元格内容，然后command+c 或 ctrl+c复制即可。

我也发现了这个不明显的操作，但是每一个使用者都来问我怎么复制完整内容，我只能一个一个口头告诉他们。领导跟我说要我优化这个，并不是每个人都会3击操作。感觉他们都好无知啊……

**Comment by 270556660** [comment]
> 鼠标3击单元格内容，然后command+c 或 ctrl+c复制即可。

大部分用户并不会使用鼠标3击，最理想是鼠标移入tooltip范围内时也保持显示
