### ISSUE TITLE
[Bug Report] [Component] [autocomplete] The 'fetch-suggestions' prop of el-autocomplete does not support async method

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7278]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgdi1tb2RlbD1cInN0YXRlXCJcbiAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaEFzeW5jXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYsIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzdGF0ZSA9IHJlZignJylcblxuaW50ZXJmYWNlIExpbmtJdGVtIHtcbiAgdmFsdWU6IHN0cmluZ1xuICBsaW5rOiBzdHJpbmdcbn1cblxuY29uc3QgbGlua3MgPSByZWY8TGlua0l0ZW1bXT4oW10pXG5cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICdiYWJlbCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vYmFiZWwvYmFiZWwnIH0sXG4gIF1cbn1cblxubGV0IHRpbWVvdXQ6IE5vZGVKUy5UaW1lb3V0XG5jb25zdCBxdWVyeVNlYXJjaEFzeW5jID0gYXN5bmMgKHF1ZXJ5U3RyaW5nOiBzdHJpbmcsIGNiOiAoYXJnOiBhbnkpID0+IHZvaWQpID0+IHtcbiAgYXdhaXQgbmV4dFRpY2soKVxuICBjb25zdCByZXN1bHRzID0gcXVlcnlTdHJpbmdcbiAgICA/IGxpbmtzLnZhbHVlLmZpbHRlcihpdGVtID0+IGl0ZW0udmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwKVxuICAgIDogbGlua3MudmFsdWVcblxuICBjbGVhclRpbWVvdXQodGltZW91dClcbiAgdGltZW91dCA9IHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKHJlc3VsdHMpXG4gICAgY2IocmVzdWx0cylcbiAgfSwgMzAwMCAqIE1hdGgucmFuZG9tKCkpXG59XG5jb25zdCBjcmVhdGVGaWx0ZXIgPSAocXVlcnlTdHJpbmc6IHN0cmluZykgPT4ge1xuICByZXR1cm4gKHJlc3RhdXJhbnQ6IExpbmtJdGVtKSA9PiB7XG4gICAgcmV0dXJuIChcbiAgICAgIHJlc3RhdXJhbnQudmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwXG4gICAgKVxuICB9XG59XG5cbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtOiBMaW5rSXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZyhpdGVtKVxuICBjb25zb2xlLmxvZyhzdGF0ZS52YWx1ZSlcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgbGlua3MudmFsdWUgPSBsb2FkQWxsKClcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. Open the link
2. F12 Open the console
3. click the input

### What is Expected?

No prompt error

### What is actually happening?

Uncaught (in promise) ElementPlusError: [ElAutocomplete] autocomplete suggestions must be an array

### Additional comments
If asynchronous methods are not supported, `remote search` cannot be carried out well

**Comment by chenxch** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwiZGVtby1hdXRvY29tcGxldGUgdGV4dC1jZW50ZXJcIj5cbiAgICA8ZWwtY29sIDpzcGFuPVwiMTJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJzdWItdGl0bGUgbXktMiB0ZXh0LXNtIHRleHQtZ3JheS02MDBcIj5cbiAgICAgICAgbGlzdCBzdWdnZXN0aW9ucyB3aGVuIGFjdGl2YXRlZFxuICAgICAgPC9kaXY+XG4gICAgICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgICAgIHYtbW9kZWw9XCJzdGF0ZTFcIlxuICAgICAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaFwiXG4gICAgICAgIGNsZWFyYWJsZVxuICAgICAgICBjbGFzcz1cImlubGluZS1pbnB1dFwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgICAvPlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBSZXN0YXVyYW50SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGluazogc3RyaW5nXG59XG5cbmNvbnN0IHN0YXRlMSA9IHJlZignJylcbmNvbnN0IHN0YXRlMiA9IHJlZignJylcblxuY29uc3QgcmVzdGF1cmFudHMgPSByZWY8UmVzdGF1cmFudEl0ZW1bXT4oW10pXG5jb25zdCBxdWVyeVNlYXJjaCA9IChxdWVyeVN0cmluZzogc3RyaW5nLCBjYjogYW55KSA9PiB7XG4gIG5ldyBQcm9taXNlKChyZXNvbHZlKT0+e1xuICAgIHNldFRpbWVvdXQoKCk9PntcbiAgICAgIHJlc29sdmUoKVxuICAgIH0sMjAwKVxuICB9KS50aGVuKCgpPT57XG4gICAgY29uc29sZS5sb2coMTIzKVxuICAgICAgY29uc3QgcmVzdWx0cyA9IHF1ZXJ5U3RyaW5nXG4gICAgICA/IHJlc3RhdXJhbnRzLnZhbHVlLmZpbHRlcihjcmVhdGVGaWx0ZXIocXVlcnlTdHJpbmcpKVxuICAgICAgOiByZXN0YXVyYW50cy52YWx1ZVxuICAgIC8vIGNhbGwgY2FsbGJhY2sgZnVuY3Rpb24gdG8gcmV0dXJuIHN1Z2dlc3Rpb25zXG4gICAgY2IocmVzdWx0cylcbiAgfSlcblxufVxuY29uc3QgY3JlYXRlRmlsdGVyID0gKHF1ZXJ5U3RyaW5nOiBzdHJpbmcpID0+IHtcbiAgcmV0dXJuIChyZXN0YXVyYW50OiBSZXN0YXVyYW50SXRlbSkgPT4ge1xuICAgIHJldHVybiAoXG4gICAgICByZXN0YXVyYW50LnZhbHVlLnRvTG93ZXJDYXNlKCkuaW5kZXhPZihxdWVyeVN0cmluZy50b0xvd2VyQ2FzZSgpKSA9PT0gMFxuICAgIClcbiAgfVxufVxuY29uc3QgbG9hZEFsbCA9ICgpID0+IHtcbiAgcmV0dXJuIFtcbiAgICB7IHZhbHVlOiAndnVlJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUnIH0sXG4gICAgeyB2YWx1ZTogJ2VsZW1lbnQnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvZWxlbWVudCcgfSxcbiAgICB7IHZhbHVlOiAnY29va2luZycsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9jb29raW5nJyB9LFxuICAgIHsgdmFsdWU6ICdtaW50LXVpJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL21pbnQtdWknIH0sXG4gICAgeyB2YWx1ZTogJ3Z1ZXgnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZXgnIH0sXG4gICAgeyB2YWx1ZTogJ3Z1ZS1yb3V0ZXInLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZS1yb3V0ZXInIH0sXG4gICAgeyB2YWx1ZTogJ2JhYmVsJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9iYWJlbC9iYWJlbCcgfSxcbiAgXVxufVxuXG5jb25zdCBoYW5kbGVTZWxlY3QgPSAoaXRlbTogUmVzdGF1cmFudEl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coaXRlbSlcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgcmVzdGF1cmFudHMudmFsdWUgPSBsb2FkQWxsKClcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)   
Maybe it should be written that way.

**Comment by JackieCheung** [comment]
> [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwiZGVtby1hdXRvY29tcGxldGUgdGV4dC1jZW50ZXJcIj5cbiAgICA8ZWwtY29sIDpzcGFuPVwiMTJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJzdWItdGl0bGUgbXktMiB0ZXh0LXNtIHRleHQtZ3JheS02MDBcIj5cbiAgICAgICAgbGlzdCBzdWdnZXN0aW9ucyB3aGVuIGFjdGl2YXRlZFxuICAgICAgPC9kaXY+XG4gICAgICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgICAgIHYtbW9kZWw9XCJzdGF0ZTFcIlxuICAgICAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaFwiXG4gICAgICAgIGNsZWFyYWJsZVxuICAgICAgICBjbGFzcz1cImlubGluZS1pbnB1dFwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgICAvPlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBSZXN0YXVyYW50SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGluazogc3RyaW5nXG59XG5cbmNvbnN0IHN0YXRlMSA9IHJlZignJylcbmNvbnN0IHN0YXRlMiA9IHJlZignJylcblxuY29uc3QgcmVzdGF1cmFudHMgPSByZWY8UmVzdGF1cmFudEl0ZW1bXT4oW10pXG5jb25zdCBxdWVyeVNlYXJjaCA9IChxdWVyeVN0cmluZzogc3RyaW5nLCBjYjogYW55KSA9PiB7XG4gIG5ldyBQcm9taXNlKChyZXNvbHZlKT0+e1xuICAgIHNldFRpbWVvdXQoKCk9PntcbiAgICAgIHJlc29sdmUoKVxuICAgIH0sMjAwKVxuICB9KS50aGVuKCgpPT57XG4gICAgY29uc29sZS5sb2coMTIzKVxuICAgICAgY29uc3QgcmVzdWx0cyA9IHF1ZXJ5U3RyaW5nXG4gICAgICA/IHJlc3RhdXJhbnRzLnZhbHVlLmZpbHRlcihjcmVhdGVGaWx0ZXIocXVlcnlTdHJpbmcpKVxuICAgICAgOiByZXN0YXVyYW50cy52YWx1ZVxuICAgIC8vIGNhbGwgY2FsbGJhY2sgZnVuY3Rpb24gdG8gcmV0dXJuIHN1Z2dlc3Rpb25zXG4gICAgY2IocmVzdWx0cylcbiAgfSlcblxufVxuY29uc3QgY3JlYXRlRmlsdGVyID0gKHF1ZXJ5U3RyaW5nOiBzdHJpbmcpID0+IHtcbiAgcmV0dXJuIChyZXN0YXVyYW50OiBSZXN0YXVyYW50SXRlbSkgPT4ge1xuICAgIHJldHVybiAoXG4gICAgICByZXN0YXVyYW50LnZhbHVlLnRvTG93ZXJDYXNlKCkuaW5kZXhPZihxdWVyeVN0cmluZy50b0xvd2VyQ2FzZSgpKSA9PT0gMFxuICAgIClcbiAgfVxufVxuY29uc3QgbG9hZEFsbCA9ICgpID0+IHtcbiAgcmV0dXJuIFtcbiAgICB7IHZhbHVlOiAndnVlJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUnIH0sXG4gICAgeyB2YWx1ZTogJ2VsZW1lbnQnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvZWxlbWVudCcgfSxcbiAgICB7IHZhbHVlOiAnY29va2luZycsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9jb29raW5nJyB9LFxuICAgIHsgdmFsdWU6ICdtaW50LXVpJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL21pbnQtdWknIH0sXG4gICAgeyB2YWx1ZTogJ3Z1ZXgnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZXgnIH0sXG4gICAgeyB2YWx1ZTogJ3Z1ZS1yb3V0ZXInLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZS1yb3V0ZXInIH0sXG4gICAgeyB2YWx1ZTogJ2JhYmVsJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9iYWJlbC9iYWJlbCcgfSxcbiAgXVxufVxuXG5jb25zdCBoYW5kbGVTZWxlY3QgPSAoaXRlbTogUmVzdGF1cmFudEl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coaXRlbSlcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgcmVzdGF1cmFudHMudmFsdWUgPSBsb2FkQWxsKClcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> Maybe it should be written that way.

I know the way of callback is ok, but why not support async syntax

**Comment by chenxch** [comment]
Can you tell me what kind of scenario needs this kind of processing?

**Comment by JackieCheung** [comment]
> Can you tell me what kind of scenario needs this kind of processing?

I've updated [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwiZGVtby1hdXRvY29tcGxldGUgdGV4dC1jZW50ZXJcIj5cbiAgICA8ZWwtY29sIDpzcGFuPVwiMTJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJzdWItdGl0bGUgbXktMiB0ZXh0LXNtIHRleHQtZ3JheS02MDBcIj5cbiAgICAgICAgbGlzdCBzdWdnZXN0aW9ucyB3aGVuIGFjdGl2YXRlZFxuICAgICAgPC9kaXY+XG4gICAgICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgICAgIHYtbW9kZWw9XCJzdGF0ZTFcIlxuICAgICAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaFwiXG4gICAgICAgIGNsZWFyYWJsZVxuICAgICAgICBjbGFzcz1cImlubGluZS1pbnB1dFwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgICAvPlxuICAgIDwvZWwtY29sPlxuICA8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBSZXN0YXVyYW50SXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGluazogc3RyaW5nXG59XG5cbmNvbnN0IHN0YXRlMSA9IHJlZignJylcbmNvbnN0IHN0YXRlMiA9IHJlZignJylcblxuY29uc3QgcmVtb3RTZWFyY2hGbiA9IChxdWVyeVN0cmluZzogc3RyaW5nKSA9PiB7XG4gIHJldHVybiBuZXcgUHJvbWlzZShyZXNvbHZlID0+IHtcbiAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgIGNvbnN0IHJlc3VsdHMgPSBxdWVyeVN0cmluZ1xuICAgICAgPyByZXN0YXVyYW50cy52YWx1ZS5maWx0ZXIoY3JlYXRlRmlsdGVyKHF1ZXJ5U3RyaW5nKSlcbiAgICAgIDogcmVzdGF1cmFudHMudmFsdWVcbiAgICAgIFxuICAgICAgcmVzb2x2ZShyZXN1bHRzKVxuICAgIH0sIDIwMDApXG4gIH0pXG59XG5cbmNvbnN0IHJlc3RhdXJhbnRzID0gcmVmPFJlc3RhdXJhbnRJdGVtW10+KFtdKVxuY29uc3QgcXVlcnlTZWFyY2ggPSBhc3luYyAocXVlcnlTdHJpbmc6IHN0cmluZywgY2I6IGFueSkgPT4ge1xuICBjb25zdCByZXMgPSBhd2FpdCBzZWFyY2hBc3luY0ZuKHF1ZXJ5U3RyaW5nKVxuICBjb25zb2xlLmxvZyhyZXMpXG4gIGNiKHJlcylcbn1cbmNvbnN0IGNyZWF0ZUZpbHRlciA9IChxdWVyeVN0cmluZzogc3RyaW5nKSA9PiB7XG4gIHJldHVybiAocmVzdGF1cmFudDogUmVzdGF1cmFudEl0ZW0pID0+IHtcbiAgICByZXR1cm4gKFxuICAgICAgcmVzdGF1cmFudC52YWx1ZS50b0xvd2VyQ2FzZSgpLmluZGV4T2YocXVlcnlTdHJpbmcudG9Mb3dlckNhc2UoKSkgPT09IDBcbiAgICApXG4gIH1cbn1cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICdiYWJlbCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vYmFiZWwvYmFiZWwnIH0sXG4gIF1cbn1cblxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGl0ZW06IFJlc3RhdXJhbnRJdGVtKSA9PiB7XG4gIGNvbnNvbGUubG9nKGl0ZW0pXG59XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIHJlc3RhdXJhbnRzLnZhbHVlID0gbG9hZEFsbCgpXG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by chenxch** [comment]
I figured it out, `fetch-suggestions` is a method that can do asynchronous requests, everyone has the habit of using ``async/await`, and it should be supported. Thanks for your feedback.

**Comment by chenxch** [comment]
@JackieCheung I re-fixed it.
