### ISSUE TITLE
[Bug Report] [Style] [container] 使用容器布局中找不到 common-layout样式，导致页面渲染的没有背景色这些

### ISSUE THREAD

**Issue by pycoder404** [element-plus/element-plus#7281]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome  100.0.4896.127`
- Build Tool: `Vue CLI`

### Related Component

- `el-container`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxkaXYgY2xhc3M9XCJjb21tb24tbGF5b3V0XCI+XG4gICAgPGVsLWNvbnRhaW5lcj5cbiAgICAgIDxlbC1oZWFkZXI+SGVhZGVyPC9lbC1oZWFkZXI+XG4gICAgICA8ZWwtbWFpbj5NYWluPC9lbC1tYWluPlxuICAgIDwvZWwtY29udGFpbmVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

1. vue create project with default configurations
2. npm install element-plus
3.  <template>
  <div class="common-layout">
    <el-container>
      <el-header>Header</el-header>
      <el-main>Main</el-main>
    </el-container>
  </div>
</template>

### What is Expected?

能够正常渲染处像文档中的样式和颜色

### What is actually happening?

目前是渲染不出来的，找不到common-layout样式
在node_modules/element-plus grep 过滤common-layout关键字也没有

### Additional comments

在node_modules/element-plus grep 过滤common-layout关键字也没有

**Comment by pycoder404** [comment]
附上代码，使用vue create创建的项目
main.js
import {createApp} from 'vue'
import App from './App.vue'
import router from './router'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
const app = createApp(App)
app.use(router)
app.use(ElementPlus)
app.mount('#app')

layout/index.vue
<template>
    <div>
        <nav-bar></nav-bar>
        <left-sidebar class="sidebar-container"></left-sidebar>

        <div class="main-container">
            <app-main></app-main>
        </div>
        <left-sidebar class="right-sidebar-container"></left-sidebar>

    </div>
</template>

<script>
    import {NavBar, LeftSidebar, AppMain} from './components'
    export default {
        name: 'LayOut',
        components: {
            NavBar,
            LeftSidebar,
            AppMain
        }
    }
</script>

**Comment by TANGENNT** [comment]
https://github.com/element-plus/element-plus/blob/ae365d5bc663d18c30d0ea0fc777ed852f990e78/docs/examples/container/common-layout.scss

这个是官网文档的样式，不是组件库的样式

**Comment by pycoder404** [comment]
> https://github.com/element-plus/element-plus/blob/ae365d5bc663d18c30d0ea0fc777ed852f990e78/docs/examples/container/common-layout.scss
> 
> 这个是官网文档的样式，不是组件库的样式
懂了 多谢，从element-ui过来，element-ui里面的示例，对于样式都是在style里面写了的，所以一般之前复制过来的时候就有了，这个是指提供组件，样式统一引用的
