### ISSUE TITLE
[Bug Report] [Component] [select] el-select组件绑定值为对象时，value-key和label属性只能为value和label值才生效，且回显失败

### ISSUE THREAD

**Issue by chenmingli** [element-plus/element-plus#7284]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.6`
- Element Plus Version: `2.1.10`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDxlbC1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgdmFsdWUta2V5PVwiY2lkXCJcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiXG4gICAgICA6dmFsdWU9XCJpdGVtXCJcbiAgICA+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbJ09wdGlvbjEnXSlcbmNvbnN0IHZhbHVlMiA9IHJlZih7XG4gIH0pXG5jb25zdCBjaGFuZ2UgPSAoZGF0YSkgPT57XG4gIGNvbnNvbGUubG9nKGRhdGEpXG59XG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgY2lkOiAnT3B0aW9uMScsXG4gICAgbmFtZTogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgY2lkOiAnT3B0aW9uMicsXG4gICAgbmFtZTogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgY2lkOiAnT3B0aW9uMycsXG4gICAgbmFtZTogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgY2lkOiAnT3B0aW9uNCcsXG4gICAgbmFtZTogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgY2lkOiAnT3B0aW9uNScsXG4gICAgbmFtZTogJ09wdGlvbjUnLFxuICB9LFxuXVxuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

```vue
<template>

  <el-select
    v-model="value2"
    placeholder="Select"
    value-key="value"
    @change="change"
  >
    <el-option
      v-for="item in options"
      :label="item.label"
      :value="item"
    >
    </el-option>
  </el-select>
</template>

<script lang="ts" setup>
import { setupElementPlus } from './element-plus.js'
setupElementPlus()

import { ref } from 'vue'

const value1 = ref(['Option1'])
const value2 = ref({
  value: 'Option1'
})
const change = (data) =>{
  console.log(data)
}
const options = [
  {
    value: 'nane,cid',
    label: 'Option1',
  },
  {
    value: 'Option2',
    label: 'Option2',
  },
  {
    value: 'Option3',
    label: 'Option3',
  },
  {
    value: 'Option4',
    label: 'Option4',
  },
  {
    value: 'Option5',
    label: 'Option5',
  },
]

</script>

```

### What is Expected?

选择正确

### What is actually happening?

选择显示失效

### Additional comments

_(empty)_

**Comment by zybieku** [comment]
怎么说, 这问题解决了嘛, 没人合并嘛

**Comment by billao** [comment]
这个问题两周多了，新版本还是没有解决。

**Comment by plehnen** [comment]
Still having this issue too :(

**Comment by Jquank** [comment]
遇到了相同的问题，version>=2.1.8都有这个问题
