### ISSUE TITLE
[Bug Report] [Style] [input] Safari浏览器input输入框disabled后里面的字体颜色和背景色一致导致文字看不见

### ISSUE THREAD

**Issue by w8854123** [element-plus/element-plus#7285]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Safari 15.4 (17613.1.17.1.13)/Mac OS 12.3.1 (21E258)`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgZGlzYWJsZWQgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

<script setup lang="ts">
import { ref } from 'vue'

const msg = ref('Hello World!')
</script>

<template>
  <h1>{{ msg }}</h1>
  <el-input v-model="msg" disabled />
</template>

### What is Expected?

文字正常显示

### What is actually happening?

文字不显示

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/17878078/164354880-66e2fc96-f967-4220-951d-5e3a116190df.png)

**Comment by hoowhoami** [comment]
Add css to fix it.
```css
input[disabled],
textarea[disabled],
select[disabled='disabled'] {
  -webkit-text-fill-color: var(--el-disabled-text-color);
}
```

**Comment by w8854123** [comment]
> 添加 css 来修复它。
> 
> ```css
> input[disabled],
> textarea[disabled],
> select[disabled='disabled'] {
>   -webkit-text-fill-color: var(--el-disabled-text-color);
> }
> ```

解决了

**Comment by hoowhoami** [comment]
This is only a temporary solution. I hope the Element-Plus team will handle it.

**Comment by HeftyKoo** [comment]
Fixed by: https://github.com/element-plus/element-plus/pull/9178
