### ISSUE TITLE
[Bug Report] [Component] [input] clearable 会动态改变宽度

### ISSUE THREAD

**Issue by huang-yf3160** [element-plus/element-plus#7287]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.10`
- Browser / OS: `chrome 99.0.4844.82`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBpbmxpbmU+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIGNsZWFyYWJsZSAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

在表单组件下，input组件增加clearable属性，input组件宽度会动态变化
```vue
  <el-form inline>
    <el-form-item>
      <el-input v-model="input" placeholder="Please input" clearable />
    </el-form-item>
  </el-form>
```

### What is Expected?

不会变化宽度

### What is actually happening?

宽度动态变化

### Additional comments

_(empty)_

**Comment by josonho** [comment]
你好~

因为你的代码中el-input是没有宽度的，
所以实际渲染出来的 el-input宽度 = 原生input宽度 + 前缀图标宽度 + 后缀图标宽度。
可以写css固定el-input宽度来处理。

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBpbmxpbmU+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICBzdHlsZT1cIndpZHRoOiAyMDBweFwiXG4gICAgICAgIHYtbW9kZWw9XCJpbnB1dFwiIFxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgICAgIGNsZWFyYWJsZSBcbiAgICAgIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

**Comment by huang-yf3160** [comment]
> 你好~
> 
> 因为你的代码中el-input是没有宽度的， 所以实际渲染出来的 el-input宽度 = 原生input宽度 + 前缀图标宽度 + 后缀图标宽度。 可以写css固定el-input宽度来处理。
> 
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBpbmxpbmU+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICBzdHlsZT1cIndpZHRoOiAyMDBweFwiXG4gICAgICAgIHYtbW9kZWw9XCJpbnB1dFwiIFxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgICAgIGNsZWFyYWJsZSBcbiAgICAgIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

我知道怎么解决，但是在之前的版本里是没有这个问题的。

**Comment by YunYouJun** [comment]
Maybe it is caused by https://github.com/element-plus/element-plus/pull/7179 

Can you have a look?

The solution I can think of is to add a default width to the container, but I'm not sure if this creates additional issues.

**Comment by emojiiii** [comment]
对于clearable或者可以使用绝对定位去解决，其他继续沿用flex布局 ？

**Comment by YunYouJun** [comment]
> 对于clearable或者可以使用绝对定位去解决，其他继续沿用flex布局 ？

clearable 应该还需要对 suffix 等情况进行判断，以及设置输入框的可显示宽度，可能也比较麻烦。

**Comment by plainheart** [comment]
> 对于clearable或者可以使用绝对定位去解决

改成绝对定位，就需要动态计算，比较麻烦而且很容易出现问题。

> clearable 应该还需要对 suffix 等情况进行判断，以及设置输入框的可显示宽度，可能也比较麻烦。

其他组件库默认给了 clearable 占位，但那样默认情况下右侧的留白就会显得比较大，和左侧也不对称，不是很美观。前几天在 discord 讨论过，暂时还想不出好的解决办法。

**Comment by YunYouJun** [comment]
为 input container 设置默认宽度是否存在潜在问题？@plainheart

**Comment by plainheart** [comment]
@YunYouJun 我觉得还是不要默认设置宽度 个人感觉大多数情况下开发者可能更喜欢默认填充父级宽度 而且加了默认宽度也算是一个小的 BC 了。

**Comment by YunYouJun** [comment]
现在的 input 似乎因为浏览器默认 input 会有一个默认宽度，并导致拥有 clearable 等 suffix 元素时改变其宽度。
也许我们应该在文档中提示用户为其容器设置宽度。

cc @JeremyWuuuuu

**Comment by tolking** [comment]
感觉直接可以给一个最小宽度 220px (--el-date-editor-width)。

类似的还有在 <el-form inline> 中使用 Slider 由于没有最小宽度直接就是一个圆圈。

为表单相关的组件设置一个最小宽度或许是一个不错的方案

**Comment by chenxch** [comment]
这个问题好像好久没动静了，我看了一遍，也是比较赞同不添加默认宽度，如果没有很好的解决办法，可能要舍弃掉美观这块，采用flex布局。

**Comment by tuutoo** [comment]
显示隐藏时的宽度可能另一个问题.

建议把这个Hover时显示隐藏Clearable的功能拿掉.

这功能在视觉上造成了视觉不一致, 主要有下面两种情况
1. 移动端和桌面端的视觉不一致: 要Hover时显示隐藏这个按钮. 还要考虑移动端的情况, 移动端是没有Hover的.
2. 多个图标时的视觉不一致: 如果还有其他图标, 比如显示隐藏密码的图标, 又没有做这个Hover和Focus的显示隐藏.

**Comment by agrass-GitHub** [comment]
这个问题太影响使用体验了。无论是定位还是占位感觉都比现在的这个方案合适。

**Comment by KYX1234** [comment]
咱就是说，之前饿了么2都有这个问题的，到3这样用起来真的很不爽，为什么不考虑在form inline模式下给个默认定宽呢

**Comment by KYX1234** [comment]
咱就是说，之前饿了么2都没有这个问题的，到3这样用起来真的很不爽，为什么不考虑在form inline模式下给个默认定宽呢

**Comment by yezimikk** [comment]
能不能做个input有值的情况下长期显示clearable的图标的API？

**Comment by wzc520pyfm** [comment]
是否可添加attributes, 让使用者自行决定使用何种方案? 
方案一: input宽度随clearable显隐动态调整
方案二: input为clearable预留空间

**Comment by tolking** [comment]
为 form inline 模式下的 input 增加默认宽度或许是比较合适的主意

**Comment by YunYouJun** [comment]
> 为 form inline 模式下的 input 增加默认宽度或许是比较合适的主意

Let's do it?

**Comment by tolking** [comment]
> > 为 form inline 模式下的 input 增加默认宽度或许是比较合适的主意
> 
> Let's do it?

agree

**Comment by dengshenkk** [comment]
还没商量出一个方案吗? 确定下来咔咔先整了再说

**Comment by jummyliu** [comment]
注意，给 el-input 指定宽度后  **220px (--el-date-editor-width)？**，会导致手动指定宽度的 el-select 显示异常 @tolking  
<img width="516" alt="image" src="https://github.com/element-plus/element-plus/assets/13114931/d9223202-0897-4432-ba8a-c83d2027ff96">
<img width="567" alt="image" src="https://github.com/element-plus/element-plus/assets/13114931/2ec28c25-3a4d-45ac-b703-eed73c10076b">

**Comment by strangePix** [comment]
所以路过讨论一下，最后是怎么处理了...

**Comment by GuLinLing** [comment]
不想设置宽度的可以试试
.el-input__suffix {
  margin-left: -22px;
  background-color: var(--el-input-bg-color, var(--el-fill-color-blank));
}

**Comment by Junzh666** [comment]
> 不想设置宽度的可以试试，希望官方早点解决 .el-input__suffix:not(.el-select .el-input__suffix) { margin-left: -22px; } .el-input__inner:not(.el-select .el-input__inner) { padding-right: 22px; }

亲测可行，感谢分享。

**Comment by jiao2563719877** [comment]
> 不想设置宽度的可以试试，希望官方早点解决 .el-input__suffix:not(.el-select .el-input__suffix) { margin-left: -22px; } .el-input__inner:not(.el-select .el-input__inner) { padding-right: 22px; }

thanks
