### ISSUE TITLE
[Bug Report] [Component] [slider] Element Plus 的Slider，和Element UI的slider design不一样，是设计还是bug？

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7289]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.10`
- Browser / OS: `Edge Version 99.0.1150.30`
- Build Tool: `CDN`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHZlcnRpY2FsIGhlaWdodD1cIjIwMHB4XCIgc2hvdy1pbnB1dCAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDApXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Additional comments

_(empty)_

**Comment by Edric-Li** [comment]
不太明白，标记更多信息是什么意思

**Comment by Forguncy** [comment]
下图是Element UI的效果，[codepen](https://codepen.io/roberthu/pen/QWQjmQZ)
![image](https://user-images.githubusercontent.com/16997556/167099540-2b148fd3-bb43-4dde-9d66-ee32e800b685.png)
下图是Element Plug的效果，[PlayGround](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHNob3ctaW5wdXQgdmVydGljYWwgaGVpZ2h0PVwiMjAwcHhcIiAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDApXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
![image](https://user-images.githubusercontent.com/16997556/167099834-5b1729df-ae3a-42db-99e2-49940c6149f5.png)
在Template完全一样的情况下，“show-input” 属性渲染出的结果完全不同，因为现在项目正在从ElementUI升级到ElementPlus，我查了ElementPlus的升级文档，没有发现相关的变更信息，所以想确认下，这个变更是Bug还是确定就这样变更了？
