### ISSUE TITLE
[Bug Report] [Component] [tree-select] el-tree-select字典数据延迟加载后，下拉树checkbox未选中

### ISSUE THREAD

**Issue by lwzh200907** [element-plus/element-plus#7291]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgOmRhdGE9XCJkYXRhXCIgbXVsdGlwbGUgLz5cbiAgPGVsLWRpdmlkZXIgLz5cbiAgc2hvdyBjaGVja2JveDpcbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIDpkYXRhPVwiZGF0YVwiIG11bHRpcGxlIHNob3ctY2hlY2tib3ggY2hlY2stc3RyaWN0bHkgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYscmVhY3RpdmUsbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVhY3RpdmUoWycxJ10pXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZShbe1xuICAgIHZhbHVlOiAnMScsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMSd9XSlcblxuY29uc3QgZGF0YTEgPSBbXG4gIHtcbiAgICB2YWx1ZTogJzEnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMS0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzInLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMi0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzItMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzItMicsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICcyLTItMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICczJyxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJzMtMScsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICczLTEtMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICczLTInLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMy0yLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbnNldFRpbWVvdXQoKCk9PntcbiAgT2JqZWN0LmFzc2lnbihkYXRhLCBkYXRhMSlcbiAgbmV4dFRpY2soKCk9Pntcblx0XHRPYmplY3QuYXNzaWduKHZhbHVlLCBbXCIxXCJdKVxuICB9KVxufSwxMDAwKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 组件moduleValue和data均为reactive对象
2. 初始data设置已选择modulevalue对应的条目
3. 延迟加载data数据
4. 下拉后，对应树节点未check，但右侧存在对钩

### What is Expected?

延迟加载data字典数据后，不影响已check条目

### What is actually happening?

延迟加载data字典后，check条目异常

### Additional comments

这是使用方式错误，还是控件bug，请指正

![image](https://user-images.githubusercontent.com/9744089/164383473-fdfab12a-56ef-43f9-b6e8-01e412171826.png)

**Comment by yuandabo** [comment]
注意id的类型

**Comment by yujinpan** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgOmRhdGE9XCJkYXRhXCIgbXVsdGlwbGUgLz5cbiAgPGVsLWRpdmlkZXIgLz5cbiAgc2hvdyBjaGVja2JveDpcbiAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIDpkYXRhPVwiZGF0YVwiIG11bHRpcGxlIHNob3ctY2hlY2tib3ggY2hlY2stc3RyaWN0bHkgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYscmVhY3RpdmUsbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5cbi8vIHVzZSByZWZcbmNvbnN0IHZhbHVlID0gcmVmKFsnMSddKVxuXG5jb25zdCBkYXRhID0gcmVmKFtdKVxuXG5jb25zdCBkYXRhMSA9IFtcbiAge1xuICAgIHZhbHVlOiAnMScsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMS0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnMicsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcyLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMi0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMi0yJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzItMi0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzMnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMy0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzMtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzMtMicsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICczLTItMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuXG5zZXRUaW1lb3V0KCgpPT57XG4gICAgZGF0YS52YWx1ZSA9IGRhdGExXG59LDEwMDApXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

使用 `ref` 替换 `reactive`:

```js
const data = ref([]);

// 延迟加载
setTimeout(() => {
  data.value = [{value: 1, label: 1}];
}, 2000);
```

> `ref` 用于创建一个响应式对象，`reactive` 用于创建对象的响应式副本。更多查看：
> - [ref](https://v3.cn.vuejs.org/api/refs-api.html#ref)
> - [reactive](https://v3.cn.vuejs.org/api/basic-reactivity.html#reactive)
