### ISSUE TITLE
[Bug Report] [Component] [drawer] 使用按需引入自动导入模式下，drawer 抽屉组件有部分样式未生效

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#7293]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

/

### Steps to reproduce

1. 使用 vite 创建开发环境，并使用 unplugin-vue-components 和 unplugin-auto-import 进行自动导入
2. 当页面有滚动条时，打开抽屉组件

### What is Expected?

打开抽屉时，页面的滚动条会隐藏

### What is actually happening?

打开抽屉时，页面的滚动条未隐藏，依旧可以滚动滚轮控制下方页面的滚动

### Additional comments

通过观察开发者工具，打开抽屉时在body上会添加 .el-popup-parent--hidden 样式类名，但却没有样式生效。
而改用全局引入 element plus 后，问题解决。
说明只有在按需引入自动导入时，才有这个问题。

**Comment by zjssos** [comment]
不止这个，Notification 通知组件也出现了

**Comment by ZinLiao** [comment]
dialog，messagebox都有同样的问题，更诡异的是开发模式没问题，编译扔到服务器就有问题

**Comment by hooray** [comment]
我觉得这个问题似乎得到解决了，我在2.2.2里没能复现

**Comment by children-111** [comment]
自动导入时好多样式都没有，真是醉了

**Comment by maofenglu** [comment]
后来怎么解决的。在最新2.4版本里还有
