### ISSUE TITLE
[Bug Report] [Component] [carousel, carousel-item] carousel走马灯组件，在Carousel-Item 的数据源改变后，展示的第一张幻灯片不是数据源的第0项

### ISSUE THREAD

**Issue by sihuanian** [element-plus/element-plus#7294]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `chrome 98.0.4758.82`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNoYW5nZVwiIHR5cGU9XCJwcmltYXJ5XCI+5pS55Y+YaXRlbXM8L2VsLWJ1dHRvbj5cbiAgPGVsLWNhcm91c2VsIGluZGljYXRvci1wb3NpdGlvbj1cIm91dHNpZGVcIiA6YXV0b3BsYXk9XCJmYWxzZVwiPlxuICAgIDxlbC1jYXJvdXNlbC1pdGVtIHYtZm9yPVwiaXRlbSBpbiBpdGVtc1wiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDM+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGl0ZW1zID0gcmVmKFsxLCAyLCAzLCA0XSk7XG4gIFxuZnVuY3Rpb24gY2hhbmdlKCkge1xuICBpZiAoaXRlbXMudmFsdWVbMF0gPT09IDEpIHtcbiAgICBpdGVtcy52YWx1ZSA9IFs2LCA3LCA4LCA5XTtcbiAgfSBlbHNlIHtcbiAgICBpdGVtcy52YWx1ZSA9IFsxLCAyLCAzLCA0XTtcbiAgfVxufVxuICBcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNhcm91c2VsX19pdGVtIGgzIHtcbiAgY29sb3I6ICM0NzU2Njk7XG4gIGZvbnQtc2l6ZTogMThweDtcbiAgb3BhY2l0eTogMC43NTtcbiAgbGluZS1oZWlnaHQ6IDMwMHB4O1xuICBtYXJnaW46IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbn1cblxuLmVsLWNhcm91c2VsX19pdGVtOm50aC1jaGlsZCgybikge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjOTlhOWJmO1xufVxuXG4uZWwtY2Fyb3VzZWxfX2l0ZW06bnRoLWNoaWxkKDJuICsgMSkge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZDNkY2U2O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 点出改变items的按钮，items的数据变更

### What is Expected?

第一次点击改变items按钮后，幻灯片的第一项是6，显示的也是第一项，幻灯片顺序和items的索引顺序一致。items为[6, 7, 8, 9],幻灯片也是6， 7， 8， 9

### What is actually happening?

第一次点击改变items按钮后，幻灯片的第一项是9，显示的是第二项8，幻灯片的顺序和items的索引顺序相反。items为[6, 7,  8, 9]，幻灯片是9， 8， 7， 6

### Additional comments

_(empty)_

![图片](https://user-images.githubusercontent.com/40854936/164400277-db2941c0-5aae-4d11-8a08-f99fce6f19d3.png)
![图片](https://user-images.githubusercontent.com/40854936/164400601-c3d9628a-1ac3-4e0b-9a9b-ae953d39cd1e.png)

**Comment by Aarona-hub** [comment]
hello大佬，你解决了吗
