### ISSUE TITLE
[Bug Report] [Component] [select] el-select 键盘反向

### ISSUE THREAD

**Issue by ChineseHandsomeBoy** [element-plus/element-plus#7295]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.0.2`
- Browser / OS: `Chrome/100.0.4896.127 Safari/537.36 | Windows NT 10.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZWwtc2VsZWN0IHYtbW9kZWw9XCJhY3RpdmVPYmpcIiB2YWx1ZS1rZXk9XCJuYW1lXCI+XG5cdFx0PGVsLW9wdGlvbiB2LWZvcj1cIml0ZW0gaW4gb2JqTGlzdFwiIDprZXk9XCJpdGVtLm5hbWVcIiA6bGFiZWw9XCJpdGVtLm5hbWVcIiA6dmFsdWU9XCJpdGVtXCI+PC9lbC1vcHRpb24+XG5cdDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBhY3RpdmVPYmogPSByZWYoe25hbWU6MX0pO1xuY29uc3Qgb2JqTGlzdCA9IHJlZih7bmFtZToxfSk7XG5cbm9uTW91bnRlZCgoKT0+e1xuICBzZXRUaW1lb3V0KCgpID0+IHtcblx0b2JqTGlzdC52YWx1ZSA9IFtcblx0XHR7bmFtZToxfSxcblx0XHR7bmFtZToyfSxcblx0XHR7bmFtZTozfSxcblx0XTtcbn0sIDUwMDApO1xuICBcbn0pXG5cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

弹出下拉框 然后 点击键盘上下按键,待选项 反向选择

### What is Expected?

应该重上到下

### What is actually happening?

重下到上

### Additional comments

_(empty)_

**Comment by zcmk123** [comment]
你的objectList为啥初始化是个对象，后面又赋值一个数组。。。。初始化的时候是个数组就是没问题的了
你的 const objList = ref({name:1});

改成 const objList = ref([{name:1}]);

**Comment by progressivetr** [comment]
Im getting also same problem

**Comment by ryuhangyeong** [comment]
The problem seems to be fine if objList is treated as an array when initialized. Do I have to initialize it with an object? I think it's better to have the same data structure when initializing the value and the changed value.

**Comment by kooriookami** [comment]
Fixed
