### ISSUE TITLE
[Feature Request] 怎样配置namespace, 希望给个demo, 谢谢, 比较急

### ISSUE THREAD

**Issue by a15218378694** [element-plus/element-plus#7297]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

use(ElementPlus, {
  namespace: 'el-plus'
})
这样之后, 不知道引入css方面该怎么变更

### Additional comments

_(empty)_

**Comment by a15218378694** [comment]
要看样式是怎么引入的, 如果直接引入css文件, 直接改.el-前缀, 如果是引入scss, 改scss变量, 是这样理解吗

**Comment by JeremyWuuuuu** [comment]
@YunYouJun Could you please demonstrate how to replace `namespace` in the `SCSS` files?

**Comment by iamkun** [comment]
According to our doc, you should update the sass variable accordingly.

https://element-plus.org/en-US/guide/theming.html#how-to-override-it

**Comment by a15218378694** [comment]
> According to our doc, you should update the sass variable accordingly.
> 
> https://element-plus.org/en-US/guide/theming.html#how-to-override-it
> 
> https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/mixins/config.scss#L1

还是不知道怎么改scss变量, 我加在@forward with语法里面报错, 说下没有在@use中声明

**Comment by YunYouJun** [comment]
I will replace the scss namespace variable in two days and give an example.

**Comment by YunYouJun** [comment]
https://github.com/element-plus/element-plus/pull/7344

I created a pr that replaces all the css variable namespaces, but since it changes a lot, we need to double-check before merging.

**Comment by kelvin-lemon** [comment]
> #7344
> 
> I created a pr that replaces all the css variable namespaces, but since it changes a lot, we need to double-check before merging.

希望能尽快用上，辛苦 @YunYouJun

**Comment by kelvin-lemon** [comment]
有详细的使用文档吗？

**Comment by YunYouJun** [comment]
> 有详细的使用文档吗？

OK, i will write for it. And it should be released together in the next version.

**Comment by kelvin-lemon** [comment]
用 less 是否可以修改 namespace

**Comment by a15218378694** [comment]
> 用 less 是否可以修改 namespace

**Comment by a15218378694** [comment]
> 用 less 是否可以修改 namespace
> 
> Whether you can modify the namespace with less

上面有人提了pr, 等待最后的解决方案吧, 可以留意官网更新

**Comment by YunYouJun** [comment]
> 用 less 是否可以修改 namespace

不可以，因为所有样式使用 scss 进行编写，我们没有使用任何 less。

> 有详细的使用文档吗？

我添加了使用文档和一个示例，相信它可以解决你们的疑惑。https://github.com/element-plus/element-plus/pull/7596

- Repo: https://github.com/element-plus/element-plus-vite-starter
- Preview: https://vite-starter.element-plus.org/
