### ISSUE TITLE
[Feature Request] 希望Calendar 日历组件优化一下,谢谢!

### ISSUE THREAD

**Issue by zc-write-code** [element-plus/element-plus#7300]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `N/A`

## Description

希望Calendar 日历组件在当前月的时候如果下个月或上个月的日期不会出现一整排都是上个月或下个月的日期,现在好像是固定的6行展示,希望可以像手机自带的日历那样有多少展示多少,,不会出现一整排都不是本月的情况,谢谢!

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/26754959/164418115-03e0fd3e-87ca-41a4-aaa1-f11d3b7c1e51.png)
此为官方网站的日历

![image](https://user-images.githubusercontent.com/26754959/164418158-059d42d1-c723-42d3-908c-2a7f65cad7f5.png)
此为手机自带的日历

**Comment by tall-talker** [comment]
pr提交没人审，我重新提一个issue吧

**Comment by zc-write-code** [comment]
好的,谢谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 中午12:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Feature Request] 希望Calendar 日历组件优化一下,谢谢! (Issue #7300)





 
pr提交没人审，我重新提一个issue吧

**Comment by zc-write-code** [comment]
> pr提交没人审，我重新提一个issue吧

**Comment by tall-talker** [comment]
2.1.11版本已修复，https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2FsZW5kYXIgdi1tb2RlbD1cInZhbHVlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihuZXcgRGF0ZSgpKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by zc-write-code** [comment]
升级至2.1.11之后无法启动了,报这个错误


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 下午4:13
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Feature Request] 希望Calendar 日历组件优化一下,谢谢! (Issue #7300)





 
2.1.11版本已修复，https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2FsZW5kYXIgdi1tb2RlbD1cInZhbHVlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihuZXcgRGF0ZSgpKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by zc-write-code** [comment]
> 2.1.11版本已修复，https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2FsZW5kYXIgdi1tb2RlbD1cInZhbHVlXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihuZXcgRGF0ZSgpKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

升级至2.1.11之后无法启动了,报这个错误
![image](https://user-images.githubusercontent.com/26754959/165260380-e2b7e44a-6bc4-4a93-abed-ebe6082ab786.png)

**Comment by tall-talker** [comment]
我本地的dev分支打包完全正常，在play页面渲染也是正常的
