### ISSUE TITLE
[Bug Report] [Component] [date-picker] el-date-picker的小时数值最大值只有12，无法显示中午12点至晚上12点的时间，

### ISSUE THREAD

**Issue by Ryuuki6602** [element-plus/element-plus#7313]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Edge / windows 10`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGF0ZSA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDwhLS0gRWxlbWVudCBQbHVzIGljb25zIC0tPlxuIFx0PGVsLWRhdGUtcGlja2VyXG4gICBcdHYtbW9kZWw9XCJkYXRlXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIERhdGVcIlxuICAgIGZvcm1hdD1cIllZWVktTU0tREQgaGg6bW06c3NcIlxuICAgPlxuICBcbiAgPC9lbC1kYXRlLXBpY2tlcj5cblxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

<script setup lang="ts">
import { ref } from 'vue'

const date = ref('')
</script>

<template>
  
 	<el-date-picker
   	v-model="date"
    type="datetime"
    placeholder="Pick a Date"
    format="YYYY-MM-DD hh:mm:ss"
   >
  
  </el-date-picker>

</template>

### What is Expected?

选择中午12点以后的时间可以正常显示，如13:54:32

### What is actually happening?

无法正常显示，13:54:32会变成01:54:32

### Additional comments

_(empty)_

**Comment by Ryuuki6602** [comment]
此外，我不知道是我的问题，还是是el-date-picker的组件问题，通过该组件传到后台的日期的值的格式非常奇怪，它的格式如下

2022-04-20T12:00:00.000Z

多了一个 [字母T] 和 [ .000Z ]

只是提一下

**Comment by chenxch** [comment]
format="YYYY-MM-DD HH:mm:ss"
hh是12小时制  HH才是24小时制

**Comment by chenxch** [comment]
> 此外，我不知道是我的问题，还是是el-date-picker的组件问题，通过该组件传到后台的日期的值的格式非常奇怪，它的格式如下
> 
> 2022-04-20T12:00:00.000Z
> 
> 多了一个 [字母T] 和 [ .000Z ]
> 
> 只是提一下

![image](https://user-images.githubusercontent.com/23251408/164507080-81a040d6-3fa0-4461-a439-4920d4ba8fe2.png)

**Comment by Ryuuki6602** [comment]
> 

我理解了，很抱歉给你造成不必要的困扰
