### ISSUE TITLE
[Bug Report] [Component] [button] Component ElButton  is missing template or render function. 

### ISSUE THREAD

**Issue by baixiaoyu2997** [element-plus/element-plus#7323]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Link](https://stackblitz.com/edit/nuxt-starter-k11qvm?file=package.json)

### Steps to reproduce

在控制台运行`npx nuxi generate`， 静态打包报错，但是`npx nuxi build` 正常

### What is Expected?

能够正常打包

### What is actually happening?

打包失败

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Try https://github.com/nuxt/framework/issues/4084 and https://github.com/element-plus/element-plus-nuxt-starter

**Comment by baixiaoyu2997** [comment]
感谢回复，我研究研究
