### ISSUE TITLE
[Bug Report] [Component] [input] el-input  clearable  会动态改变宽度  之前的版本不会这样

### ISSUE THREAD

**Issue by zh1011** [element-plus/element-plus#7328]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLSBFbGVtZW50IFBsdXMgaWNvbnMgLS0+XG4gIDxlbC1pY29uPjxVc2VyIC8+PC9lbC1pY29uPlxuXG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICBcbiAgPGVsLWZvcm0gaW5saW5lPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0cy5qc29uIjoiIiwiX28iOnt9fQ==)

### Steps to reproduce

focus 的时候就会出现clearable 宽度会增加 blur时clearable消息  宽度会减少  
之前的版本不会出现这种情况  

### What is Expected?

宽度不会动态改变

### What is actually happening?

宽度会动态改变

### Additional comments

_(empty)_

**Comment by josonho** [comment]
#7287

**Comment by plainheart** [comment]
因为现在 input 是 flex 布局，clearable 这类的图标是通过 `v-if` 控制的，目前只能先为其指定具体宽度或者考虑给这类图标固定占位。

**Comment by zh1011** [comment]
> 因为现在 input 是 flex 布局，clearable 这类的图标是通过 `v-if` 控制的，目前只能先为其指定具体宽度或者考虑给这类图标固定占位。

后续版本有考虑解决这个的问题吗

**Comment by gjfei** [comment]
> 因为现在 input 是 flex 布局，clearable 这类的图标是通过 `v-if` 控制的，目前只能先为其指定具体宽度或者考虑给这类图标固定占位。

可以给一个占位，让宽度保持不变？

**Comment by sxzz** [comment]
Duplicate of #7287
