### ISSUE TITLE
NavMenu导航菜单按文档路由无法跳转

### ISSUE THREAD

**Issue by WalkAlone0325** [element-plus/element-plus#733]
```html
<el-menu router>
  <el-menu-item index="/a"></el-menu-item>
</el-menu>
```
按文档使用 **vue-router 的模式，启用该模式会在激活导航时以 index 作为 path 进行路由跳转**，但路由无法跳转

**Comment by zychome** [comment]
遇到了同样的问题

**Comment by JeremyWuuuuu** [comment]
Will be fixed soon.
This one is duplicate with #734

**Comment by WalkAlone0325** [comment]
@zychome 先可以试试用router-link的自定义渲染

**Comment by JeremyWuuuuu** [comment]
duplicate with #732

**Comment by zychome** [comment]
@WalkAlone0325 
暂时 用菜单的select事件配合router.push手动解决了

**Comment by JeremyWuuuuu** [comment]
Closing this due to it's fixed in #745
