### ISSUE TITLE
[Bug Report] [Docs] [space] 中文文档中Space 间距组件-自动换行描述异常

### ISSUE THREAD

**Issue by vaebe** [element-plus/element-plus#7346]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome 100`
- Build Tool: `Other`

### Related Component

- `el-space`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/space.html#%E8%87%AA%E5%8A%A8%E6%8D%A2%E8%A1%8C)

### Steps to reproduce

打开element-plus中文文档->选择Space间距组件文档->选择自动换行

### What is Expected?

“在水平 (horizontal) 模式下, 通过控制 wrap (布尔类型)来控制是否自动换行”

描述中的文字正确加粗展示。

### What is actually happening?

在**水平 (horizontal) 模式下, 通过控制 wrap (布尔类型) **来控制是否自动换行

显示异常。

### Additional comments

_(empty)_

<img width="1005" alt="截屏2022-04-24 上午10 20 46" src="https://user-images.githubusercontent.com/52314078/164953516-b1ec9111-e8e2-4d86-9342-b8fb2cf4e21d.png">

**Comment by zcj996** [comment]
那位大哥可以告知下，element-plus 中文文档是怎么生成的，https://crowdin.com/project/element-plus/zh-CN 这里虽然进行了翻译，但是是怎么变成中文文档进行部署的呢？

**Comment by sxzz** [comment]
翻译需要官方进行审核后，在下一个版本更新。
https://github.com/element-plus/element-plus/discussions/7230

**Comment by zcj996** [comment]
非常感谢
