### ISSUE TITLE
[Feature Request] [Enhancement] element-plus 对 ssr的支持怎么样

### ISSUE THREAD

**Issue by yuntian001** [element-plus/element-plus#7348]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `All`

## Description

element-plus 对 ssr的支持怎么样，未来有没有ssr的支持及测试计划。

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
已有 SSR 单元测试与 Nuxt 3 模板。如遇SSR问题，请单独开 issue 反馈。
SSR unit tests with Nuxt 3 template are available. Please open a new issue for feedback on SSR issues.

- https://github.com/element-plus/element-plus/tree/dev/ssr-testing
- https://github.com/element-plus/element-plus-nuxt-starter
