### ISSUE TITLE
Dropdown menu has error style

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#735]
![image](https://user-images.githubusercontent.com/38392315/100684775-ed674f80-33b5-11eb-9b97-d10d3a1acef1.png)
The black and grey background are two components, dropdown menu will be clipped.

**Comment by JeremyWuuuuu** [comment]
This could be related to the change of the default insertion strategy of `el-popper`, could you also test `Select` just in case

**Comment by kooriookami** [comment]
> This could be related to the change of the default insertion strategy of `el-popper`, could you also test `Select` just in case

![image](https://user-images.githubusercontent.com/38392315/100685308-150ae780-33b7-11eb-9df9-e588b874f71f.png)
`select` is normal.

**Comment by JeremyWuuuuu** [comment]
thanks this will be fixed soon
