### ISSUE TITLE
[Bug Report] [Component] [date-picker, time-picker] Date Picker and Time Picker change event not working

### ISSUE THREAD

**Issue by asdjgfr** [element-plus/element-plus#7357]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXIgOm1vZGVsLXZhbHVlPVwidmFsdWUxXCIgdHlwZT1cImRhdGVcIiBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIiBAY2hhbmdlPVwiXCIvPlxuICA8YnIvPlxuICA8YnIvPlxuICA8ZWwtdGltZS1waWNrZXIgOm1vZGVsLXZhbHVlPVwidmFsdWUyXCIgcGxhY2Vob2xkZXI9XCJBcmJpdHJhcnkgdGltZVwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5cbmZ1bmN0aW9uIGNoYW5nZURhdGUoZCl7XG4gIGNvbnNvbGUubG9nKFwiZGF0ZSBjaGFuZ2VcIixkKVxuICB2YWx1ZTEudmFsdWU9ZFxufVxuICBcbmZ1bmN0aW9uIGNoYW5nZVRpbWUodCl7XG4gIGNvbnNvbGUubG9nKFwidGltZSBjaGFuZ2VcIix0KVxuICB2YWx1ZTIudmFsdWU9dFxufVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

use `:model-value` and `@change` to change value , but `change` method didn't working.

### What is Expected?

`change` method didn't working.

### What is actually happening?

`change` method work.

### Additional comments

_(empty)_

**Comment by 515600237** [comment]
我也遇到了同样的的问题
