### ISSUE TITLE
[Bug Report] [Component] [table, table-column] 通过 CDN 的方式引入，table组件不能正常显示

### ISSUE THREAD

**Issue by lillian56** [element-plus/element-plus#7367]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `edge`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/lillian56/pen/OJzYzer)

### Steps to reproduce

cdn 引入，如代码所示

### What is Expected?

table组件能正常显示3列

### What is actually happening?

表头和表内容纵向显示，且内容仅显示最后一列

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
see #7232
