### ISSUE TITLE
[Bug Report] [Component] Router navigate to other page and SSR rendering failed due to the el-popper-container position used by the component

### ISSUE THREAD

**Issue by Guovin** [element-plus/element-plus#7368]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

-  `el-card`
-  `el-config-provider`
- `el-pagination`
- `el-cascader`
- `el-color-picker`

### Reproduction Link

[Link](https://stackblitz.com/edit/nuxt-starter-c1bvc9?file=pages%2Fresult.vue)

### Steps to reproduce

After SSR is enabled in Nuxt3, some components used in popper's page will fail to redirect after refreshing the page, and the page is not refreshed and rendered, for example, el-pagination layout=sizes, el-cascader and el-color-picker. This situation is 100% repeated when the above components are wrapped with an el-card or el-config-provider.
Nuxt3 maintenance staff reply: This is in the docs; it's a limitation of transition support. Layouts and pages must have a single root  element.(https://github.com/nuxt/nuxt.js/issues/13767)
The location of el-popper-container is outside the DIV tag of __nuxt, causing this problem.

### What is Expected?

The location of el-popper-container is in the DIV tag of __nuxt, and refreshing the browser page after SSR is enabled can make route jump and refresh the rendering in time.

### What is actually happening?

The position of el-popper-container is outside the DIV tag of __nuxt. When refreshing the browser page after SSR is enabled, the route jump fails and the rendering fails to be updated in time.

### Additional comments

_(empty)_

Please use opening in new window in stackblitz to test this problem:
1.When refreshed the browser page:
![image](https://user-images.githubusercontent.com/37107669/165029051-4dd360d1-e615-4610-a6fb-5b7f42f928d1.png)

2.When try to router navigate to other page:
![image](https://user-images.githubusercontent.com/37107669/165028592-f1e2eea4-de0c-412e-802d-6910b3b7164a.png)

3.I guess the cause of the problem:
![image](https://user-images.githubusercontent.com/37107669/165028690-e6dd7c02-f6ab-4ee3-a4c9-3fc8991ce1b7.png)

**Comment by lvbaiying** [comment]
Yes, this problem is caused by SSR. You can choose to wrap with < clientonly >
Nuxt3 has been provided. If not, you can:

const ClientOnly = defineComponent({
  name: 'ClientOnly',
  props: ['fallback', 'placeholder', 'placeholderTag', 'fallbackTag'],
  setup(_, { slots }) {
    const mounted = ref(false);
    onMounted(() => {
      mounted.value = true;
    });
    return (props) => {
      if (mounted.value) {
        return slots.default?.();
      }
      const slot = slots.fallback || slots.placeholder;
      if (slot) {
        return slot();
      }
      const fallbackStr = props.fallback || props.placeholder || '';
      const fallbackTag = props.fallbackTag || props.placeholderTag || 'span';
      return createElementBlock(fallbackTag, null, fallbackStr);
    };
  },
});
