### ISSUE TITLE
[Feature Request] [Enhancement] [icon] When will CDN mapping icon be supported? Help the poor kid who introduced the project with Script😿！

### ISSUE THREAD

**Issue by lait233** [element-plus/element-plus#7369]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `icon`

## Description

如题。什么时候会支持cdn引入呢。由于项目历史原因。没办法用前端构建工具搭建。目前vue3和element-plus都是script方式cdn引入js文件来用的。没有图标太难受了。很过带有图标的组件都有可能显示有问题（比如上传组件）。

### Additional comments

希望官方能尽早支持cdn引入图标库。和element2一样直接使用。谢谢了！

**Comment by sxzz** [comment]
已经支持了，引入
already supported, import this

`https://cdn.jsdelivr.net/npm/@element-plus/icons-vue@1.1.4/dist/index.iife.min.js`

然后使用 `ElementPlusIconsVue`
and then use `ElementPlusIconsVue`

**Comment by lait233** [comment]
> 已经支持了，引入了 ，导入这个
> 
> `https://cdn.jsdelivr.net/npm/@element-plus/icons-vue@1.1.4/dist/index.iife.min.js`
> 
> 然后使用`ElementPlusIconsVue` 然后使用`ElementPlusIconsVue`

https://codepen.io/lait233/pen/wvpEqze
你好可以帮我看下吗。我已经引入了该js，也vue.use了 但是还是没生效？

**Comment by sxzz** [comment]
@lait233 Please refer to https://github.com/element-plus/element-plus/blob/2a25e3bd4d923db39d733b109e7bac56b12a0fcc/docs/en-US/component/icon.md#register-all-icons
