### ISSUE TITLE
[Bug Report] [Component] [drawer] el-drawer cannot be opened in the SSR page

### ISSUE THREAD

**Issue by Guovin** [element-plus/element-plus#7372]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `el-drawer`

### Reproduction Link

[Link](https://stackblitz.com/edit/nuxt-starter-tx8wmz?file=pages%2Findex.vue)

### Steps to reproduce

click the button of openDrawer

### What is Expected?

el-drawer can be opened

### What is actually happening?

el-drawer cannot be opened

### Additional comments

open SSR in Nuxt3

error:
![image](https://user-images.githubusercontent.com/37107669/165059111-febd28d8-2119-4780-ab7a-f6f5e107c9a9.png)

**Comment by sxzz** [comment]
Please add `<client-only>` by now.

**Comment by Guovin** [comment]
> Please add `<client-only>` by now.

Thanks for reply. After adding <client-only>, it work. That mean the el-draw not support SSR now?  If will fix in the future?
