### ISSUE TITLE
[Bug Report] [Component] [date-picker] el-date-picker can not invoke onChange Callback after picking a date in tsx (在 tsx 模式下, el-date-pick 组件在选择一个日期之后不能执行onChange回调)

### ISSUE THREAD

**Issue by jackluson** [element-plus/element-plus#7375]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHN4XCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQgfSBmcm9tIFwidnVlXCI7XG4vLyBQbGF5Z3JvdW5kIOS4jeaUr+aMgXRzeCwg6K+35aSN5Yi26L+Z5q615Luj56CB5Zyo5pSv5oyBanN4546v5aKD5omn6KGMXG5cbmV4cG9ydCBkZWZhdWx0IGRlZmluZUNvbXBvbmVudCh7XG4gIHNldHVwKCkge1xuICAgIHJldHVybiB7XG4gICAgICB2YWx1ZTogXCIyMDIwLTAxLTAxXCIsXG4gICAgfTtcbiAgfSxcbiAgcmVuZGVyKCkge1xuICAgIGNvbnNvbGUubG9nKFwidGhpc1wiLCB0aGlzKTtcbiAgICBjb25zdCB7IHZhbHVlIH0gPSB0aGlzO1xuICAgIGNvbnNvbGUubG9nKFwi8J+agCB+IGZpbGU6IFRlc3RFbGUudnVlIH4gbGluZSAxMyB+IHJlbmRlciB+IHZhbHVlXCIsIHZhbHVlKTtcbiAgICByZXR1cm4gKFxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIG1vZGVsLXZhbHVlPXt2YWx1ZX1cbiAgICAgICAgdHlwZT1cImRhdGVcIlxuICAgICAgICBvbkNoYW5nZT17KHZhbCkgPT4ge1xuICAgICAgICAgIGNvbnNvbGUubG9nKFwi8J+agCB+IGZpbGU6IFRlc3RFbGUudnVlIH4gbGluZSAxOCB+IHJlbmRlciB+IHZhbFwiLCB2YWwpO1xuICAgICAgICB9fVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIlxuICAgICAgLz5cbiAgICApO1xuICB9LFxufSk7XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+PC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击选择日期

### What is Expected?

调用onChange回调函数

### What is actually happening?

没有调用

### Additional comments

Playground 不支持tsx, 请复制这段代码在支持jsx环境执行
```
<script lang="tsx">
import { defineComponent } from "vue";

export default defineComponent({
  setup() {
    return {
      value: "2020-01-01",
    };
  },
  render() {
    console.log("this", this);
    const { value } = this;
    console.log("🚀 ~ file: TestEle.vue ~ line 13 ~ render ~ value", value);
    return (
      <el-date-picker
        model-value={value}
        type="date"
        onChange={(val) => {
          console.log("🚀 ~ file: TestEle.vue ~ line 18 ~ render ~ val", val);
        }}
        placeholder="Pick a day"
      />
    );
  },
});
</script>
<style scoped></style>
```

**Comment by chenxch** [comment]
```tsx
<script lang="tsx">
import { defineComponent, ref } from 'vue'
// Playground 不支持tsx, 请复制这段代码在支持jsx环境执行

export default defineComponent({
  setup() {
    const value = ref(new Date())
    return {
      value,
    }
  },
  render() {
    console.log('this', this)
    const { value } = this
    console.log('🚀 ~ file: TestEle.vue ~ line 13 ~ render ~ value', value)
    return (
      <el-date-picker
        v-model={this.value}
        type="date"
        onChange={(val) => {
          console.log('🚀 ~ file: TestEle.vue ~ line 18 ~ render ~ val', val)
        }}
        placeholder="Pick a day"
      />
    )
  },
})
</script>
<style scoped></style>

```
2 wrong places,
1. Is value a two-way bound variable?
2. Using modelValue in JSX mode, you need to write onUpdate:modelValue yourself.
