### ISSUE TITLE
[Bug Report] [Build] [popper] 2.1.11版本webpack构建失败，@popperjs 

### ISSUE THREAD

**Issue by hoowhoami** [element-plus/element-plus#7382]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Webpack`

### What is Expected?

正常构建

### What is actually happening?
构建失败

### Additional comments
尝试降级element-plus到2.1.10后正常，SOS
_(empty)_

![image](https://user-images.githubusercontent.com/84499551/165206355-8fc8f6a8-0441-49e1-aaff-4e596301b04e.png)

**Comment by Sunshop** [comment]
me too

**Comment by mohamed-taher-bytro** [comment]
Have same issue

**Comment by laichengs** [comment]
2.1.10 依然构建失败

**Comment by HammCn** [comment]
Failed in ^2.0.1

**Comment by HammCn** [comment]
Failed in ```2.0.1``` as ```vue-cli-service serve```

**Comment by HammCn** [comment]
Failed in ```2.0.1``` when ```vue-cli-service serve```

**Comment by KupuJIJI12** [comment]
Me too

**Comment by zc-write-code** [comment]
我也是这样的问题,,更新到2.1.11就有问题了,上一个版本没有该问题;
![image](https://user-images.githubusercontent.com/26754959/165264880-9181b789-cf46-44a3-8f59-8805aca55d2b.png)

**Comment by hoowhoami** [comment]
临时解决方案：不管啥版本，只要报这个错，暂时把 `./node_modules/element-plus/node_modules/@popperjs`整个文件夹删掉，应该就可以把项目启动起来。先用着，等待修复。

**Comment by awumiao** [comment]
> 临时解决方案：不管啥版本，只要报这个错，暂时把 `./node_modules/element-plus/node_modules/@popperjs`整个文件夹删掉，应该就可以把项目启动起来。先用着，等待修复。

是构建有问题，本地可以正常使用

**Comment by sxzz** [comment]
Please provide a minimum reproduction repo, if you have tried the above method and it still doesn't work.

**Comment by wegi8** [comment]
i try remove the `node_modules` and `package-lock` and `yarn.lock` and started all over again. it's worked
mine element-plus version is `2.1.9`
I think maybe the `lock` worked during the upgrade and caused this bug.

**Comment by sxzz** [comment]
应该是不用指定 `"@sxzz/popperjs-es": "2.11.7` 的，目前默认也会保证是最新版本。
