### ISSUE TITLE
[Bug Report] [Component] [input] el-input 组件 type="number" 无法输入0.01

### ISSUE THREAD

**Issue by qingshangwushi** [element-plus/element-plus#7384]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome/100.0.4896.127`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbC5udW1iZXI9XCJpbnB1dFwiIHR5cGU9XCJudW1iZXJcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

<template>
  <el-input v-model.number="input" type="number" placeholder="Please input" />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
const input = ref('')
</script>

### What is Expected?

输入0.01

### What is actually happening?

实际为0

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
It is recommended to use el-input-number.

**Comment by 34205037** [comment]
> It is recommended to use el-input-number.
用input-number和这是一个input组件的bug没有什么关系吧

**Comment by 34205037** [comment]
准确点说，只要小数点后面写0都不行
@chenxch 用input-number和这是一个input组件的bug没有什么关系吧

**Comment by chenxch** [comment]
> 准确点说，只要小数点后面写0都不行 @chenxch 用input-number和这是一个input组件的bug没有什么关系吧

just recommend

**Comment by muuyao** [comment]
.number 修饰符的问题，文档说明不支持
