### ISSUE TITLE
[Bug Report] [Component] [input-number] input Number 组件，设置精度2，  17.275保留成17.27,        17.285保留成17.29

### ISSUE THREAD

**Issue by booking123123** [element-plus/element-plus#7385]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMTcuMjc1KVxuY29uc3QgbnVtMSA9IHJlZigxNy4yODUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiA6cHJlY2lzaW9uPVwiMlwiIDpzdGVwPVwiMC4xXCIgLz5cbiAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtMVwiIDpwcmVjaXNpb249XCIyXCIgOnN0ZXA9XCIwLjFcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

input Number 组件，设置精度2，  17.275保留成17.27,        17.285保留成17.29

### What is Expected?

17.275保留成17.28,

### What is actually happening?

17.275保留成17.27,

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/blob/1037eb75b4f139ca06c94f3d14ed105f3e7d12a0/packages/components/input-number/src/input-number.vue#L156

To be precise, this is an accuracy problem under the IEE754 specification.

17.275 * 10 ** 2
=》
1727.4999999999998

Maybe another way to deal with precision is needed.

**Comment by qmhc** [comment]
Is it possible to solve it by following?

```js
// Math.round(Math.round(17.275 * 10 ** (pre + 1)) / 10) / pre ** 10
Math.round(Math.round(17.275 * 10 ** 2 * 10) / 10) / 10 ** 2
```

**Comment by chenxch** [comment]
> @chenxch Is it possible to solve it by following?
> 
> ```js
> // Math.round(Math.round(17.275 * 10 ** (pre + 1)) / 10) / pre ** 10
> Math.round(Math.round(17.275 * 10 ** 2 * 10) / 10) / 10 ** 2
> ```

It seems that it is also possible. At present, the string scheme is used. You can take a look at pr to evaluate it.

**Comment by btea** [comment]
@chenxch #7398 seems caused problem #7769 .

**Comment by chenxch** [comment]
> @chenxch Is it possible to solve it by following?
> 
> ```js
> // Math.round(Math.round(17.275 * 10 ** (pre + 1)) / 10) / pre ** 10
> Math.round(Math.round(17.275 * 10 ** 2 * 10) / 10) / 10 ** 2
> ```

Hey,I tried your solution today while fixing it, unfortunately it output 17.28 when inputting 17.2745.

**Comment by qmhc** [comment]
> > @chenxch Is it possible to solve it by following?
> > ```js
> > // Math.round(Math.round(17.275 * 10 ** (pre + 1)) / 10) / pre ** 10
> > Math.round(Math.round(17.275 * 10 ** 2 * 10) / 10) / 10 ** 2
> > ```
> 
> Hey,I tried your solution today while fixing it, unfortunately it output 17.28 when inputting 17.2745.

Hi, I'm interested in this, may I create PR to solve it?

**Comment by btea** [comment]
@qmhc Hello, @chenxch has created a PR #7777 .  You can check to see if there are other issues.

**Comment by chenxch** [comment]
> 设置精度2， 0.01 保留成 0.10, 0.02->0.20 ,..., 0.09 -> 0.90

It has been fixed, waiting for the next version to be released.

**Comment by HeftyKoo** [comment]
fixed by: https://github.com/element-plus/element-plus/pull/7777/files
