### ISSUE TITLE
[Bug Report] [Docs] [All] 官网访问太慢

### ISSUE THREAD

**Issue by Mr-Nobody-li** [element-plus/element-plus#7388]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome 96`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input)

### Steps to reproduce

没有

### What is Expected?

打开的快点

### What is actually happening?

打开的很慢

### Additional comments

_(empty)_

**Comment by HammCn** [comment]
Gitee最近貌似一直在被ddos

**Comment by Mr-Nobody-li** [comment]
> Gitee最近貌似一直在被ddos

原来是这样，貌似也没有个离线文档供人们自己下载用
