### ISSUE TITLE
[Feature Request] [Enhancement] [upload] 是否可以在上传完毕后，在允许点击，否则，文件会出现404，图片会无法预览。

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7392]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `upload`

## Description
![image](https://user-images.githubusercontent.com/50992790/165254932-cb54a6bc-5962-4a60-8842-fa98dd1b4c45.png)

**Comment by zc-write-code** [comment]
只能自己在上传之前定义一个变量,,等到上传完成之后自己设置按钮为可点击的状态解决

**Comment by Edric-Li** [comment]
@zc-write-code 可是如何 禁止 文件的点击事件呢？

**Comment by Edric-Li** [comment]
@zc-write-code  就是文件列表中的文件点击事件

**Comment by zc-write-code** [comment]
可以自定义插槽写文件列表

**Comment by Edric-Li** [comment]
知道怎么解决了，没看到onPreview
