### ISSUE TITLE
[Feature Request] [popover] Popover组件的宽度？

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#7393]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `popover`

## Description

Popover组件的宽度无法通过width属性修改，是因为最小值为150吗？

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/165266378-5e02537c-e3ff-4bbe-8148-c2e4bd2abac0.png)

**Comment by norangit** [comment]
你右键查看下最终生成的html结构就明白了
