### ISSUE TITLE
[Feature Request] [container] el-Container 高度不能自适应

### ISSUE THREAD

**Issue by quliting** [element-plus/element-plus#7395]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `container`

## Description

<template>
  <div class="common-layout">
    <el-container>
      <el-header>Header</el-header>
      <el-main>Main</el-main>
      <el-footer>Footer</el-footer>
    </el-container>
  </div>
</template>

### Additional comments

https://element-plus.gitee.io/zh-CN/component/container.html#%E5%B8%B8%E8%A7%81%E9%A1%B5%E9%9D%A2%E5%B8%83%E5%B1%80
按照这个demo；
出来的效果，和文档不一致，没有样式，就三行字；

![image](https://user-images.githubusercontent.com/14035957/165270987-ca4ab371-e137-409e-a39f-3c843afe80e3.png)

**Comment by quliting** [comment]
我想实现的效果是，Head占一部分（200px）；Foot占一部分（300px）；其他的高度都给Main；

**Comment by norangit** [comment]
这个高度啊，说难还真难，说简单也简单，你要确保你的html, body 的最小高度是100%

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiY29tbW9uLWxheW91dFwiPlxuICAgIDxlbC1jb250YWluZXI+XG4gICAgICA8ZWwtaGVhZGVyPkhlYWRlcjwvZWwtaGVhZGVyPlxuICAgICAgPGVsLW1haW4+TWFpbjwvZWwtbWFpbj5cbiAgICAgIDxlbC1mb290ZXI+Rm9vdGVyPC9lbC1mb290ZXI+XG4gICAgPC9lbC1jb250YWluZXI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAuZWwtY29udGFpbmVye1xuICAgICAgaGVpZ2h0OiA1MDBweDtcbiAgICAgIGJvcmRlcjogMXB4IHNvbGlkICNmMDA7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by quliting** [comment]
你这个是固定的高度，
那是不是用js获取下高度，然后设置下就可以了

**Comment by norangit** [comment]
> 你这个是固定的高度， 那是不是用js获取下高度，然后设置下就可以了

根据你的喜好来吧，css也可以实现，但是不知道你dom嵌套啥样的
css的话你就 html,body{min-height: 100%;}
总之你得确保 
```
<el-container>
      <el-header>Header</el-header>
      <el-main>Main</el-main>
      <el-footer>Footer</el-footer>
    </el-container>
```
<el-container>的父级dom的最小高度是100%

**Comment by quliting** [comment]
我也忽然间明白了，我现在main是可以的，主要是没有内容；
有了内容了，自然就自适应了；
我可能绕在里面了；
对了，官网中的style，在哪里呢

> 当你的 el-main 的内容足够高了，就自然撑高了。 通常来说，el-footer 并不是期望一打开页面就看到吧，滚动了滚动条，它在最底部，所以 el-main 的高度不用设置，由它的内容撑起来
