### ISSUE TITLE
pagination组件问题

### ISSUE THREAD

**Issue by lebron112** [element-plus/element-plus#740]
当第一次查询设置total为1200条，分页设置50页 切换到 3页，
第二次带搜索条件的查询，此时搜索结果返回数据49条，分页器已经跳到了1并且只有1页了，没有触发current-change，
建议total值变化后，current-page * size 比total大时， 再触发一次 current-change事件

**Comment by JeremyWuuuuu** [comment]
Will be fixed soon.
