### ISSUE TITLE
[Bug Report] [Style] [input] When the password type input box of el-input changes the display type quickly, the password is selected. Can I improve it

### ISSUE THREAD

**Issue by huyu456** [element-plus/element-plus#7404]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.1.11`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html#%E5%AF%86%E7%A0%81%E7%B1%BB%E5%9E%8B%E7%9A%84%E8%BE%93%E5%85%A5%E6%A1%86)

### Steps to reproduce

Quickly click the show-password icon to switch the display type of the text box
![el-input](https://huyu.info/media/pictures/el-input.gif)

### What is Expected?

The text box switches normally and the content is not selected

### What is actually happening?

Text boxes switch normally, but there is a chance that the content will be selected. Element UI has been tested and there is no such problem

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
You are more than welcome if you wish.

**Comment by huyu456** [comment]
> 如果您愿意，我们非常欢迎您。

I fork the latest code test and it doesn't have this problem, maybe it has been fixed

**Comment by huyu456** [comment]
I fork the latest code test and it doesn't have this problem, maybe it has been fixed
