### ISSUE TITLE
[Bug Report] [Component] [icon] cdn引入图标资源后，使用组件标签方式使用图标，一个div下多个图标只会显示第一个

### ISSUE THREAD

**Issue by lait233** [element-plus/element-plus#7418]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.11`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-icon`

### Reproduction Link

[CodePen](https://codepen.io/lait233/pen/wvpEqze)

### Steps to reproduce

点击复现连接即可看到
<img width="910" alt="image" src="https://user-images.githubusercontent.com/31282366/165712483-a940a787-7d71-4561-ab36-d129ba44284b.png">

### What is Expected?

展示所有的图标

### What is actually happening?

只会显示第一个图标

### Additional comments

_(empty)_

**Comment by YiDanCheung** [comment]
view图标也不能正常显示，<el-icon><view /></el-icon>。[我遇到的问题代码](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cywgVmlldywgVXNlciwgRWxlbWUsIEVkaXQsIFNoYXJlfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIFxuICA8cD5cbiAgICA8c3Bhbj52aWV35Zu+5qCH5peg5rOV5pi+56S677yaPC9zcGFuPlxuICAgIDxlbC1pY29uIDpzaXplPVwiMTAwXCI+PHZpZXcgLz48L2VsLWljb24+XG4gICAgPGhyPlxuICAgIDxzcGFuPua1i+ivleWbvuagh++8mjwvc3Bhbj5cbiAgICA8ZWwtaWNvbiA6c2l6ZT1cIjEwMFwiPjx1c2VyIC8+PC9lbC1pY29uPlxuICAgIDxlbC1pY29uIDpzaXplPVwiMTAwXCI+PGVsZW1lIC8+PC9lbC1pY29uPlxuICBcdDxlbC1saW5rIDppY29uPVwiRWRpdFwiPkVkaXQ8L2VsLWxpbms+XG4gICAgPHNoYXJlIHN0eWxlPVwid2lkdGg6IDFlbTsgaGVpZ2h0OiAxZW07IG1hcmdpbi1yaWdodDogOHB4XCIgLz5cblxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by lait233** [comment]
> 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/31282366/165873290-b93b4b54-8a3c-44db-9ed2-eb57ff7fb321.png">

**Comment by lait233** [comment]
> ```
> <edit style="width: 1em; height: 1em; margin-right: 8px"></edit>
> <share style="width: 1em; height: 1em; margin-right: 8px"></share>
> ```
> 
> [docs](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)

使用了关闭标签能正确显示了。感谢
但是楼上说的view图标确实无法正确显示
<img width="996" alt="image" src="https://user-images.githubusercontent.com/31282366/165873518-f608ecc9-cccc-4c57-b29d-c27c589059e2.png">

**Comment by chenxch** [comment]
@lait233 [docs](https://element-plus.org/zh-CN/component/icon.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95) html has view tag

**Comment by lait233** [comment]
> @lait233 [docs](https://element-plus.org/zh-CN/component/icon.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95) html has view tag

emm，谢谢，但是你可以试下view 这个图标，无论用什么方式都无法显示出来。。。
```html
        <el-icon>
          <view />
        </el-icon>
<view style="width: 1em; height: 1em; margin-right: 8px"></view>
都不行
```

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/165875852-8ff6690d-328a-4ab6-8c28-a37a456f2c0b.png)

**Comment by lait233** [comment]
@chenxch 感谢大佬 我看到了这个的。。但是我js是直接引入的。要怎么改成别名使用呢。可以在我的链接里面试一下截图or代码给我吗。谢谢🙏🏻🙏🏻🙏🏻

**Comment by chenxch** [comment]
```
app.component('my-view', ElementPlusIconsVue.View)

<my-view style="width: 1em; height: 1em; margin-right: 8px"></my-view>
```

**Comment by lait233** [comment]
@chenxch 非常感谢。来个二维码吧。扫个小心意。像你这种没被我问烦还给我指路解答的人太少了。

**Comment by chenxch** [comment]
Small things, you can follow me. 
If the issue is resolved, you can close this issue.
