### ISSUE TITLE
【Bug】Fixed状态下表头固定列使用触摸板滚动，会产生明显同步延时

### ISSUE THREAD

**Issue by xyuanbuilds** [element-plus/element-plus#742]
表头，固定列都有错位现象
![image](https://user-images.githubusercontent.com/21687167/100705189-c45cb400-33e1-11eb-967c-320ea090be15.png)
因为不是同一个渲染层，触摸板触发较高频次scroll事件，似乎不可避免地会产生这种无法同步的效果。
后续有什么优化方向？

**Comment by JeremyWuuuuu** [comment]
One way to fix this is using virtual window scroll technic, just like this: [React Virtualized MultiGrid](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid)

**Comment by JhonXY** [comment]
> One way to fix this is using virtual window scroll technic, just like this: [React Virtualized MultiGrid](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid)
it is about scrolling synchronize
virtual cannot fix this. i have make a react virtual table use react-window, cannot fix scrolling synchronize 
But antd fix this with or without virtual, or there are something different bettween react and vue?

**Comment by JeremyWuuuuu** [comment]
Seems like ant design had different approach on this feature. Pretty neat, I think we could use the technic that they use to implement the table component.

**Comment by JeremyWuuuuu** [comment]
As you mentioned, with virtual table it is still a problem when you scroll in a fast pace.

**Comment by JhonXY** [comment]
> Seems like ant design had different approach on this feature. Pretty neat, I think we could use the technic that they use to implement the table component.

https://github.com/react-component/table/blob/master/src/Table.tsx#L447-L476

but i can not get how did they do it, they just change the scrollLeft

**Comment by JeremyWuuuuu** [comment]
We could get inspired by https://2x.antdv.com/components/table-cn/, they did a great job for implementing this feature.

**Comment by JeremyWuuuuu** [comment]
We could get inspired by https://2x.antdv.com/components/table-cn/, they did a great job for implementing this feature.

**Comment by JhonXY** [comment]
> We could get inspired by https://2x.antdv.com/components/table-cn/, they did a great job for implementing this feature.

There is more to learn，thanks

**Comment by JeremyWuuuuu** [comment]
I asked someone in the team to do some spike on the implementation, we will make the implementation in `ElementPlus`

**Comment by JeremyWuuuuu** [comment]
Thanks for bringing it up!

**Comment by kooriookami** [comment]
> One way to fix this is using virtual window scroll technic, just like this: [React Virtualized MultiGrid](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid)

![image](https://user-images.githubusercontent.com/38392315/101309832-44729600-3888-11eb-88c5-0e222d2ec702.png)
It seems also has problem.

**Comment by zazzaz** [comment]
There are some useful hack in previous element-ui. Not sure if it's related or not
![3446FBF9-C1FA-4cd6-AC79-5F971C058DE3](https://user-images.githubusercontent.com/10731096/101439241-1906ae80-394f-11eb-9031-f88992ac32a0.png)
.

![2F8A51F3-B13D-4fc7-A826-FA848F140314](https://user-images.githubusercontent.com/10731096/101439231-13a96400-394f-11eb-98fa-61603b61fffc.png)

**Comment by msidolphin** [comment]
目前应该可以考虑使用sticky实现了吧？

**Comment by stevending1st** [comment]
This issue maybe fixed. eg: [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBoZWlnaHQ9XCIyNTBcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgZml4ZWQ9XCJsZWZ0XCIvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjUwMFwiLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgd2lkdGg9XCIxODBcIi8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiICB3aWR0aD1cIjIwMFwiLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgZml4ZWQ9XCJyaWdodFwiLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wOCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by kooriookami** [comment]
Close since done.
