### ISSUE TITLE
[Feature Request] [Enhancement] How to extend a component? rewrite ElTable

### ISSUE THREAD

**Issue by webtj** [element-plus/element-plus#7424]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `N/A`

## Description

I want to expend ElTale  Add the function of exporting table data
 
### export-table.vue
```vue
<script>
import { ElTable } from 'element-plus'
export default {
  extends: ElTable,
  methods:{

    exportData(){}

  }
}
</script>
```
### main.js
```javascript
import ExportTable from '_c/tables/export-table'

app.component('exportTable', ExportTable)
```
### page 
```vue
<template>
  <export-table :data="tableData" style="width: 100%">
    <el-table-column prop="date" label="Date" width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </export-table>
</template>

<script setup>
const tableData = [
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
]
</script>
```

But no form is rendered, have you ever played this way?
error

> table.vue:4 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'm')
    at Proxy._sfc_render80 (table.vue:4:35)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5030:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5156:9)
    at mountComponent (runtime-core.esm-bundler.js:4939:9)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5107:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)

### Additional comments

_(empty)_

**Comment by Winston-Guess** [comment]
I would also love to know how one extends an element-plus component. Struggling to migrate components I extended from element-ui.

**Comment by shenX-2021** [comment]
any suggetions?

**Comment by myGitHubHuLin** [comment]
这个问题解决了吗

**Comment by webtj** [comment]
> 这个问题解决了吗

没有哦，我自己写一个组件可以通过extend继承并丰富内容，但ele不行。
我后面解决方案是将ele的组件包一层，弄成一个自定义组件，然后将属性通过$attrs $linster透传过来

**Comment by myGitHubHuLin** [comment]
好的，谢谢大佬；<el-table v-bind="{ ...$attrs, ...$props }">
    <slot />
  </el-table>vue3这样table的事件绑定不上吗

**Comment by webtj** [comment]
> 好的，谢谢大佬； vue3这样table的事件绑定不上吗

https://github.com/webtj/vite-vue3-admin/blob/master/src/components/tables/export-table/table.vue 你可以看下这文件对你有没有帮助。
我部署在这里 https://www.taojian.icu/admin/excel/exportExcel

**Comment by myGitHubHuLin** [comment]
多谢，找到问题了；加一个start

**Comment by hunjixin** [comment]
还是只能这样吗，为什么这个issue被关了，是解决了吗。

**Comment by hunjixin** [comment]
还是只能这样吗，为什么这个issue被关了，是解决了吗。

**Comment by myGitHubHuLin** [comment]
有两种办法可以弄

**Comment by bnuephjx** [comment]
> 有两种办法可以弄

请指教，怎么弄，找了一圈都没方法

**Comment by myGitHubHuLin** [comment]
<el-table v-bind="{ ...$attrs, ...$props }">
    <slot></slot>
  </el-table>

**Comment by myGitHubHuLin** [comment]
<el-table v-bind="{ ...$attrs, ...$props }">
    <slot></slot>
  </el-table>

**Comment by myGitHubHuLin** [comment]
这样可以<el-table v-bind="{ ...$attrs, ...$props }">
    <slot></slot>
  </el-table>

**Comment by myGitHubHuLin** [comment]
代码贴不上来

**Comment by wroy1005** [comment]
```js
    setup(props, ctx) {
        return ElTable.setup(props, ctx);
    },
```

I add this in my code, and it works
