### ISSUE TITLE
[Bug Report] [Component] [form] form自定义验证使用axios会导致出现验证不通过的问题

### ISSUE THREAD

**Issue by zl02655931** [element-plus/element-plus#7425]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gIGpvYkxldmVsRGF0YSA6IHtcbiAgICBuYW1lOiAndGVzdCdcbiAgfVxufSlcbmNvbnN0IGVkaXRKb2JMZXZlbEZvcm1SZWYgPSByZWYoJycpXG4vLyDoh6rlrprkuYnpqozor4Hop4TliJnlhpnms5VcbmNvbnN0IHZhbGlkYXRlTmFtZSA9IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgaWYgKCF2YWx1ZSkge1xuICAgIGNhbGxiYWNrKG5ldyBFcnJvcihcIuS4jeiDveS4uuepulwiKSlcbiAgfVxuICBjYWxsYmFjaygpXG59XG5jb25zdCBydWxlcyA9IHJlZih7XG4gIG5hbWU6IFt7dmFsaWRhdG9yOnZhbGlkYXRlTmFtZSwgdHJpZ2dlcjogJ2JsdXInfV1cbn0pXG4vLyDmj5DkuqTmm7TmlrBcbmNvbnN0IHVwZGF0ZUNvbmZpcm0gPSAoZWwpID0+IHtcbiAgaWYgKCFlbCkgcmV0dXJuXG4gIGVsLnZhbGlkYXRlKHZhbGlkID0+IHtcbiAgICBjb25zb2xlLmxvZyh2YWxpZCk7XG4gICAgaWYgKHZhbGlkKSB7XG4gICAgICBheGlvcy5nZXQoKVxuICAgICAgY29uc29sZS5sb2coXCJva1wiKVxuICAgICBcbiAgICB9IGVsc2V7XG4gICAgICBjb25zb2xlLmxvZyhcImVycm9yXCIpO1xuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIHN0YXR1cy1pY29uIDptb2RlbD1cImRhdGEuam9iTGV2ZWxEYXRhXCIgcmVmPVwiZWRpdEpvYkxldmVsRm9ybVJlZlwiIDpydWxlcz1cInJ1bGVzXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5ZCN56ewXCIgcHJvcD1cIm5hbWVcIj5cbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJkYXRhLmpvYkxldmVsRGF0YS5uYW1lXCIvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9lbC1mb3JtPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwidXBkYXRlQ29uZmlybShlZGl0Sm9iTGV2ZWxGb3JtUmVmKVwiPuaPkOS6pDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsIl9vIjp7fX0=)

### Steps to reproduce

执行提交会打印true，false

### What is Expected?

true

### What is actually happening?

true，然后是false

### Additional comments

抱歉，不知道怎么引入axios，所以在里面写了一个不能实现的函数

**Comment by zl02655931** [comment]
@[zc-write-code](https://github.com/zc-write-code) 您好，感谢您的回复，您可以测试一下我在playground里的代码，查看一下控制台输出， 不止是网络请求会导致校验失败，即便使用js自带的函数做一个数据拷贝也会导致失败。

**Comment by zl02655931** [comment]
稍微修改了一下代码
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gIGpvYkxldmVsRGF0YSA6IHtcbiAgICBuYW1lOiAndGVzdCdcbiAgfVxufSlcbmNvbnN0IGVkaXRKb2JMZXZlbEZvcm1SZWYgPSByZWYoJycpXG4vLyDoh6rlrprkuYnpqozor4Hop4TliJnlhpnms5VcbmNvbnN0IHZhbGlkYXRlTmFtZSA9IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgaWYgKCF2YWx1ZSkge1xuICAgIHJldHVybiBjYWxsYmFjayhuZXcgRXJyb3IoXCLkuI3og73kuLrnqbpcIikpXG4gIH1cbiAgcmV0dXJuIGNhbGxiYWNrKClcbn1cbmNvbnN0IHJ1bGVzID0gcmVmKHtcbiAgbmFtZTogW3t2YWxpZGF0b3I6dmFsaWRhdGVOYW1lLCB0cmlnZ2VyOiAnYmx1cid9XVxufSlcbi8vIOaPkOS6pOabtOaWsFxuY29uc3QgdXBkYXRlQ29uZmlybSA9IChlbCkgPT4ge1xuICBpZiAoIWVsKSByZXR1cm5cbiAgZWwudmFsaWRhdGUodmFsaWQgPT4ge1xuICAgIGNvbnNvbGUubG9nKHZhbGlkKTtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIE9iamVjdC5hc3NnaW4oam9iTGV2ZWxEYXRhLGpvYkxldmVsRGF0YSlcbiAgICAgIGNvbnNvbGUubG9nKFwib2tcIilcbiAgICAgXG4gICAgfSBlbHNle1xuICAgICAgY29uc29sZS5sb2coXCJlcnJvclwiKTtcbiAgICB9XG4gIH0pXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBzdGF0dXMtaWNvbiA6bW9kZWw9XCJkYXRhLmpvYkxldmVsRGF0YVwiIHJlZj1cImVkaXRKb2JMZXZlbEZvcm1SZWZcIiA6cnVsZXM9XCJydWxlc1wiPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuWQjeensFwiIHByb3A9XCJuYW1lXCI+XG4gICAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZGF0YS5qb2JMZXZlbERhdGEubmFtZVwiLz5cbiAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDwvZWwtZm9ybT5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInVwZGF0ZUNvbmZpcm0oZWRpdEpvYkxldmVsRm9ybVJlZilcIj7mj5DkuqQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by muuyao** [comment]
form 的 validate 方法会 catch 所有错误，如果传进去的 callback 有错误抛出，就会导致被 catch ，建议手动 catch 你的非校验错误
```
// 提交更新
const updateConfirm = (el) => {
    if (!el) return
    el.validate(valid => {
        console.log(valid);
        if (valid) {
            try {
                Object.assgin(jobLevelData, jobLevelData)
                console.log("ok")
            } catch (e) {

            }
        } else {
            console.log("error");
        }
    })
}
```
或者改用 await 写法
```js
// 提交更新
const updateConfirm = (el) => {
    if (!el) return
    try {
        await el.validate()
        Object.assgin(jobLevelData, jobLevelData)
        console.log("ok")
    } catch {
        console.log("error");
    }

}
```

**Comment by zl02655931** [comment]
@muuyao 您好，按照您的方式确实没问题，但是如果将Object.assgin(jobLevelData, jobLevelData)这行代码替换成真实业务中的axios请求同样会出现同一个问题。

目前我自己测试出来可行的办法是单独把业务代码提到if语句后面再执行，如果验证不通过直接return掉后面的代码。

但是想不明白为什么会同时出现true和false

**Comment by zl02655931** [comment]
`const updateConfirm = async (el) => {
    if (!el) return
    try {
        await el.validate()
// 会报错
        proxy.$api.JobLevelService.update({...}).then(res => {
    ...
  })
        console.log("ok")
    } catch {
        console.log("error");
    }

}`

**Comment by zl02655931** [comment]
```javascript
const updateConfirm =async (el) => {
  if (!el) return
  try {
    await el.validate()
    console.log("ok");
  }catch {
    console.log("error");
    return
  }
  proxy.$api.JobLevelService.update({...}).then(res => {
    if (res.code == 200) {
      ...
    }
  })
}
```
这种写法不会报错

**Comment by muuyao** [comment]
不是 validate 的报错呀，是你接口service 的报错呀

**Comment by zl02655931** [comment]
@muuyao 我的接口没有错误呀，换成下面的写法是没有问题的，现在的问题就是不能把业务代码写在validate逻辑处理里面，只能写在外面。这点感觉怪怪的。

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/blob/2003c345cf7a073bc4aa73837fa5f237e0bdbbe7/packages/components/form/src/form.vue#L119-L140

[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gIGpvYkxldmVsRGF0YSA6IHtcbiAgICBuYW1lOiAndGVzdCdcbiAgfVxufSlcbmNvbnN0IGVkaXRKb2JMZXZlbEZvcm1SZWYgPSByZWYoJycpXG4vLyDoh6rlrprkuYnpqozor4Hop4TliJnlhpnms5VcbmNvbnN0IHZhbGlkYXRlTmFtZSA9IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgY29uc29sZS5sb2coJ3ZhbHVlJywgdmFsdWUpXG4gIGlmICghdmFsdWUpIHtcbiAgICByZXR1cm4gY2FsbGJhY2sobmV3IEVycm9yKFwi5LiN6IO95Li656m6XCIpKVxuICB9XG4gIHJldHVybiBjYWxsYmFjaygpXG59XG5jb25zdCBydWxlcyA9IHJlZih7XG4gIG5hbWU6IFt7dmFsaWRhdG9yOnZhbGlkYXRlTmFtZSwgdHJpZ2dlcjogJ2NoYW5nZSd9XVxufSlcbi8vIOaPkOS6pOabtOaWsFxuY29uc3QgdXBkYXRlQ29uZmlybSA9IChlbCkgPT4ge1xuICBjb25zb2xlLmxvZygndXBkYXRlQ29uZmlybScpXG4gIGlmICghZWwpIHJldHVyblxuICBlbC52YWxpZGF0ZSgodmFsaWQsaW52YWxpZEZpZWxkcykgPT4ge1xuICAgIGNvbnNvbGUubG9nKCd2YWxpZCcsdmFsaWQsaW52YWxpZEZpZWxkcyk7XG4gICAgaWYgKHZhbGlkKSB7XG4gICAgICBPYmplY3QuYXNzaWduKGRhdGEuam9iTGV2ZWxEYXRhLGpvYkxldmVsRGF0YSlcbiAgICAgIGNvbnNvbGUubG9nKFwib2tcIilcbiAgICB9IGVsc2V7XG4gICAgICBjb25zb2xlLmxvZyhcImVycm9yXCIpO1xuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIHN0YXR1cy1pY29uIDptb2RlbD1cImRhdGEuam9iTGV2ZWxEYXRhXCIgcmVmPVwiZWRpdEpvYkxldmVsRm9ybVJlZlwiIDpydWxlcz1cInJ1bGVzXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5ZCN56ewXCIgcHJvcD1cIm5hbWVcIj5cbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJkYXRhLmpvYkxldmVsRGF0YS5uYW1lXCIvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9lbC1mb3JtPlxuICA8ZWwtYnV0dG9uICBAY2xpY2s9XCJ1cGRhdGVDb25maXJtKGVkaXRKb2JMZXZlbEZvcm1SZWYpXCI+5o+Q5LqkPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

正如 @muuyao  所说，是你的axios报错了，导致源码中的callback执行报错，触发了catch。 所以产生了true和false的情况
