### ISSUE TITLE
[Feature Request] [popover] el-popover是如何监听slot reference事件

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#7426]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `popover`

## Description

```vue
<template>
<el-popover
    placement="top-start"
    title="Title"
    :width="200"
    trigger="hover"
    content="this is content, this is content, this is content"
  >
    <template #reference>
      <el-button>Hover to activate</el-button>
    </template>
  </el-popover>
</template>
```

### Additional comments

我自己想实现这个类似功能，就是组件定义一个<slot name="reference"></slot> 然后通过监听slot一些点击或者其实事件来执行组件内的一些事件。google上搜不到答案，都是通过传递函数在调用 ，太麻烦了，而element 这个组件正是我想要的效果，不知道大概的实现逻辑是怎么样的

**Comment by muuyao** [comment]
可参见源码，组件内部在 slot 外面包了一层 wrapper，事件监听是在 wrapper 上

**Comment by xiaoxian521** [comment]
Refer to the source code yourself
