### ISSUE TITLE
[Feature Request] [Enhancement] [select-v2] 建议 [el-select-v2, el-select] 多选时，可以设置最多显示的标签个数

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7429]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `select-v2`

## Description

`el-select-v2`、`el-select` 设置 `multiple: true; collapse-tags: true; collapse-tags-tooltip: true;` 时，增加一个属性如 `max-tag-count`，控制最多显示的标签个数

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
Already have these functions, please use the latest version

**Comment by JackieCheung** [comment]
> Already have these functions, please use the latest version

你理解错了 例如想最多显示两个标签，超过两个就显示collapse-tags-tooltip 按目前的api是无法做到的

**Comment by quit777** [comment]
如何解决这个问题
