### ISSUE TITLE
[Bug Report] [Component] dynamic rendering of el-select through vue's built-in component prompts injection "ElSelect" not found.

### ISSUE THREAD

**Issue by zhangyanni666** [element-plus/element-plus#7430]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`
- `el-option`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxjb21wb25lbnQgOmlzPVwiYGVsLXNlbGVjdGBcIj5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIDVcIlxuICAgICAgICA6a2V5PVwiaXRlbVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW1cIlxuICAgICAgICA6dmFsdWU9XCJpdGVtXCJcbiAgICAgID48L2VsLW9wdGlvbj5cbiAgPC9jb21wb25lbnQ+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup>
</script>

<template>
  <component :is="`el-select`">
      <el-option
        v-for="item in 5"
        :key="item"
        :label="item"
        :value="item"
      ></el-option>
    </component>
</template>
```

### What is Expected?

可以通过component :is动态判断渲染组件

### What is actually happening?

报错

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Please register `el-select` component manually, or use Element Plus via full importing.
https://element-plus.org/en-US/guide/quickstart.html#full-import
