### ISSUE TITLE
[Feature Request] [Enhancement] [select-v2] 建议 el-select-v2 设置 teleported: true 后，对 collapse-tags-tooltip 同样生效

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7433]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `select-v2`

## Description

`el-select-v2`设置`multiple: true; 'collapse-tags': true; 'collapse-tags-tooltip': true; teleported: true; `时，只有下拉面板插入到body，但是`collapse-tags-tooltip`的样式还是会受到父级元素的影响。

### 示例地址
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogaW5saW5lLWJsb2NrOyBtYXJnaW4tbGVmdDogMjBweDsgaGVpZ2h0OiA5MHB4OyBvdmVyZmxvdzogaGlkZGVuO1wiPlxuICAgIDxwIHN0eWxlPVwibWFyZ2luOiAxMHB4XCI+dXNlIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcDwvcD5cbiAgICA8ZWwtc2VsZWN0LXYyXG4gICAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCB2YWx1ZTIgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24gJHtpZHggKyAxfWAsXG4gIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbn0pKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
### 步骤

1. 任意多选下拉项；
2. 鼠标悬停于折叠标签

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/31252046/165891921-8e1f8ab9-eeba-4e46-87f3-62b750febc6f.png)

**Comment by kooriookami** [comment]
Fixed
