### ISSUE TITLE
[Bug Report] [Component] [upload] upload组件打包后报k.upload.addEventListener错误

### ISSUE THREAD

**Issue by ChartWay** [element-plus/element-plus#7446]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `100.0.4896.127（正式版本） (arm64)`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLXVwbG9hZCBhY3Rpb249XCIvYXBpL3VwbG9hZFwiPlxuICAgICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5DbGljayB0byB1cGxvYWQ8L2VsLWJ1dHRvbj5cbiAgICAgICAgPC9lbC11cGxvYWQ+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、点击“Click to upload”

### What is Expected?

图片正确上传

### What is actually happening?

控制台报错
Uncaught (in promise) TypeError: k.upload.addEventListener is not a function
    at ajaxUpload (index.b8f5d6d2.js:42:157102)
    at ie (index.b8f5d6d2.js:42:167252)
    at le (index.b8f5d6d2.js:42:166891)

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
通过你的在线示例，没有复现该问题，请确保已经使用无痕模式测试过，排除浏览器插件等其他可能因素的影响

**Comment by ChartWay** [comment]
> 

无痕模式也不行，Safari也不行。调试正常，是打包后就不行了。
之前的版本是可以的，也不知道从哪个版本开始不行了。

**Comment by sxzz** [comment]
应该是用了 mock 或其他依赖 hook 了 XHR 导致的。如不能解决，请附上最小复现仓库。
It should be caused by using mock or other dependencies to hook XHR object. If you can't solve it, please provide the minimal reproduction repo.

**Comment by ChartWay** [comment]
已经解决，mock导致的
