### ISSUE TITLE
[Bug Report] [Component] el-popover中插入 el-select 在弹出下拉框时 el-popover会主动关闭

### ISSUE THREAD

**Issue by yokochen222** [element-plus/element-plus#7484]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-select`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IEZpbHRlciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3Zlcj5cbiAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgIDxlbC1idXR0b24gOmljb249XCJGaWx0ZXJcIj48L2VsLWJ1dHRvbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLXNlbGVjdD5cbiAgICAgIDxlbC1vcHRpb24gOnZhbHVlPVwiMVwiPnZhbDE8L2VsLW9wdGlvbj5cbiAgICAgIDxlbC1vcHRpb24gOnZhbHVlPVwiMlwiPnZhbDI8L2VsLW9wdGlvbj5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdHlwZT1cImRhdGVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIlxuICAgICAgLz5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

el-popover 中使用 含有 el-popover的表单组件时出现 失去焦点，从而关闭显示BUG，如el-popover中插入 el-select 在弹出下拉框时 el-popover会主动关闭

### What is Expected?

在el-popover中插入 el-select 在弹出下拉框时 el-popover 不会主动关闭

### What is actually happening?

el-popover中插入 el-select 在弹出下拉框时 el-popover会主动关闭

### Additional comments

_(empty)_

**Comment by news00** [comment]
这个BUG有解决办法吗

**Comment by news00** [comment]
我这边拉动el-select的滚动条会主动关闭
