### ISSUE TITLE
[Bug Report] [Component] [step, steps] step 步骤条的插槽不起作用

### ISSUE THREAD

**Issue by lalawila** [element-plus/element-plus#7490]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-step`
- `el-steps`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc3RlcHMgOnNwYWNlPVwiMjAwXCIgOmFjdGl2ZT1cIjFcIiBzaW1wbGU+XG4gICAgPGVsLXN0ZXAgdGl0bGU9XCJTdGVwIDFcIj5cbiAgICAgIDxFZGl0IHNsb3Q9XCJpY29uXCI+PC9FZGl0PlxuICAgIDwvZWwtc3RlcD5cbiAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgMlwiIDppY29uPVwiVXBsb2FkRmlsbGVkXCIgLz5cbiAgICA8ZWwtc3RlcCB0aXRsZT1cIlN0ZXAgM1wiIDppY29uPVwiUGljdHVyZVwiIC8+XG4gIDwvZWwtc3RlcHM+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWRpdCwgUGljdHVyZSwgVXBsb2FkRmlsbGVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD4iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-steps :space="200" :active="1" simple>
    <el-step title="Step 1">
      <Edit slot="icon"></Edit>
    </el-step>
    <el-step title="Step 2" :icon="UploadFilled" />
    <el-step title="Step 3" :icon="Picture" />
  </el-steps>
</template>

<script lang="ts" setup>
import { Edit, Picture, UploadFilled } from '@element-plus/icons-vue'
</script>
```

### What is Expected?

能正常使用

### What is actually happening?

无效

### Additional comments

_(empty)_

**Comment by godxiaoji** [comment]
```Vue
<template>
  <el-steps :space="200" :active="1" simple>
    <el-step title="Step 1">
      <template #icon>
        <Edit />
      </template>
    </el-step>
    <el-step title="Step 2" :icon="UploadFilled" />
    <el-step title="Step 3" :icon="Picture" />
  </el-steps>
</template>

<script lang="ts" setup>
import { Edit, Picture, UploadFilled } from '@element-plus/icons-vue'
</script>
```

修改为上面代码就可以展示 `Edit` 组件。

**Comment by lalawila** [comment]
谢谢，疏忽了
