### ISSUE TITLE
[Bug Report] [Style] [loading] 将svg作为spinner属性的值，传入ElLoading.service时，组件的大小、dom结构不正常

### ISSUE THREAD

**Issue by komorebi-0409** [element-plus/element-plus#7491]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome91 / Windows11`
- Build Tool: `Vue CLI`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmZ1bmN0aW9uIHNob3dEaWFsb2coKSB7XG4gIEVsTG9hZGluZy5zZXJ2aWNlKHtcbiAgICAgIGxvY2s6IHRydWUsXG4gICAgICB0ZXh0OiAn5YeG5aSH5omT5byA5pGE5YOP5aS0JyxcbiAgICAgIHNwaW5uZXI6ICc8c3ZnIHZpZXdCb3g9XCIwIDAgMTAyNCAxMDI0XCIgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiIGRhdGEtdi1iYTYzM2NiOD1cIlwiPjxwYXRoIGZpbGw9XCJjdXJyZW50Q29sb3JcIiBkPVwiTTUxMiA2NGEzMiAzMiAwIDAgMSAzMiAzMnYxOTJhMzIgMzIgMCAwIDEtNjQgMFY5NmEzMiAzMiAwIDAgMSAzMi0zMnptMCA2NDBhMzIgMzIgMCAwIDEgMzIgMzJ2MTkyYTMyIDMyIDAgMSAxLTY0IDBWNzM2YTMyIDMyIDAgMCAxIDMyLTMyem00NDgtMTkyYTMyIDMyIDAgMCAxLTMyIDMySDczNmEzMiAzMiAwIDEgMSAwLTY0aDE5MmEzMiAzMiAwIDAgMSAzMiAzMnptLTY0MCAwYTMyIDMyIDAgMCAxLTMyIDMySDk2YTMyIDMyIDAgMCAxIDAtNjRoMTkyYTMyIDMyIDAgMCAxIDMyIDMyek0xOTUuMiAxOTUuMmEzMiAzMiAwIDAgMSA0NS4yNDggMEwzNzYuMzIgMzMxLjAwOGEzMiAzMiAwIDAgMS00NS4yNDggNDUuMjQ4TDE5NS4yIDI0MC40NDhhMzIgMzIgMCAwIDEgMC00NS4yNDh6bTQ1Mi41NDQgNDUyLjU0NGEzMiAzMiAwIDAgMSA0NS4yNDggMEw4MjguOCA3ODMuNTUyYTMyIDMyIDAgMCAxLTQ1LjI0OCA0NS4yNDhMNjQ3Ljc0NCA2OTIuOTkyYTMyIDMyIDAgMCAxIDAtNDUuMjQ4ek04MjguOCAxOTUuMjY0YTMyIDMyIDAgMCAxIDAgNDUuMTg0TDY5Mi45OTIgMzc2LjMyYTMyIDMyIDAgMCAxLTQ1LjI0OC00NS4yNDhsMTM1LjgwOC0xMzUuODA4YTMyIDMyIDAgMCAxIDQ1LjI0OCAwem0tNDUyLjU0NCA0NTIuNDhhMzIgMzIgMCAwIDEgMCA0NS4yNDhMMjQwLjQ0OCA4MjguOGEzMiAzMiAwIDAgMS00NS4yNDgtNDUuMjQ4bDEzNS44MDgtMTM1LjgwOGEzMiAzMiAwIDAgMSA0NS4yNDggMHpcIj48L3BhdGg+PC9zdmc+JyxcbiAgICAgIGJhY2tncm91bmQ6ICdyZ2JhKDAsIDAsIDAsIDAuNyknXG4gICAgfSk7XG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd0RpYWxvZ1wiPlxuICAgIGNsaWNrXG4gIDwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用service的方式使用el-loading，复制官网文档的loading图标（svg）并将其作为spinner属性传入

### What is Expected?

用来loading的icon大小正常，dom结构正常

### What is actually happening?

显示出来的icon大小过大，只有一部分在旋转。查看dom结构，发现svg内部嵌套了svg

### Additional comments

希望可以像之前一样，spinner属性传入组件的名称即可使用，代码方便易读

**Comment by tolking** [comment]
内部svg属性有问题，可以临时[这样处理](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmZ1bmN0aW9uIHNob3dEaWFsb2coKSB7XG4gIEVsTG9hZGluZy5zZXJ2aWNlKHtcbiAgICAgIGxvY2s6IHRydWUsXG4gICAgICB0ZXh0OiAn5YeG5aSH5omT5byA5pGE5YOP5aS0JyxcbiAgICBzdmdWaWV3Qm94OiAnMCAwIDI1IDI1JyxcbiAgICAgIHNwaW5uZXI6ICc8c3ZnIHZpZXdCb3g9XCIwIDAgMTAyNCAxMDI0XCIgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiIGRhdGEtdi1iYTYzM2NiOD1cIlwiPjxwYXRoIGZpbGw9XCJjdXJyZW50Q29sb3JcIiBkPVwiTTUxMiA2NGEzMiAzMiAwIDAgMSAzMiAzMnYxOTJhMzIgMzIgMCAwIDEtNjQgMFY5NmEzMiAzMiAwIDAgMSAzMi0zMnptMCA2NDBhMzIgMzIgMCAwIDEgMzIgMzJ2MTkyYTMyIDMyIDAgMSAxLTY0IDBWNzM2YTMyIDMyIDAgMCAxIDMyLTMyem00NDgtMTkyYTMyIDMyIDAgMCAxLTMyIDMySDczNmEzMiAzMiAwIDEgMSAwLTY0aDE5MmEzMiAzMiAwIDAgMSAzMiAzMnptLTY0MCAwYTMyIDMyIDAgMCAxLTMyIDMySDk2YTMyIDMyIDAgMCAxIDAtNjRoMTkyYTMyIDMyIDAgMCAxIDMyIDMyek0xOTUuMiAxOTUuMmEzMiAzMiAwIDAgMSA0NS4yNDggMEwzNzYuMzIgMzMxLjAwOGEzMiAzMiAwIDAgMS00NS4yNDggNDUuMjQ4TDE5NS4yIDI0MC40NDhhMzIgMzIgMCAwIDEgMC00NS4yNDh6bTQ1Mi41NDQgNDUyLjU0NGEzMiAzMiAwIDAgMSA0NS4yNDggMEw4MjguOCA3ODMuNTUyYTMyIDMyIDAgMCAxLTQ1LjI0OCA0NS4yNDhMNjQ3Ljc0NCA2OTIuOTkyYTMyIDMyIDAgMCAxIDAtNDUuMjQ4ek04MjguOCAxOTUuMjY0YTMyIDMyIDAgMCAxIDAgNDUuMTg0TDY5Mi45OTIgMzc2LjMyYTMyIDMyIDAgMCAxLTQ1LjI0OC00NS4yNDhsMTM1LjgwOC0xMzUuODA4YTMyIDMyIDAgMCAxIDQ1LjI0OCAwem0tNDUyLjU0NCA0NTIuNDhhMzIgMzIgMCAwIDEgMCA0NS4yNDhMMjQwLjQ0OCA4MjguOGEzMiAzMiAwIDAgMS00NS4yNDgtNDUuMjQ4bDEzNS44MDgtMTM1LjgwOGEzMiAzMiAwIDAgMSA0NS4yNDggMHpcIj48L3BhdGg+PC9zdmc+JyxcbiAgICAgIGJhY2tncm91bmQ6ICdyZ2JhKDAsIDAsIDAsIDAuNyknXG4gICAgfSk7XG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd0RpYWxvZ1wiPlxuICAgIGNsaWNrXG4gIDwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
