### ISSUE TITLE
[Bug Report] [Component] [form-item] FormItem's 'label' slot is injected in wrong place

### ISSUE THREAD

**Issue by mPyth** [element-plus/element-plus#7497]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome 100.0.4896.75, Firefox 99.0.1`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICBcdHJlZj1cImNyZWF0ZUxlZ0VudEZvcm1SZWZcIlxuICAgIDptb2RlbD1cIm1Gb3JtRmllbGRzXCJcbiAgICBsYWJlbC13aWR0aD1cIjEzMHB4XCJcbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW0gcHJvcD1cIm5hbWUxXCI+XG4gICAgICA8c2xvdCBuYW1lPVwibGFiZWxcIj5cbiAgICAgICAgPGxhYmVsPlRoaXMgaXMgc2xvdDwvbGFiZWw+XG4gICAgICA8L3Nsb3Q+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1Gb3JtRmllbGRzLm5hbWUxXCI+PC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICBcbiAgICA8ZWwtZm9ybS1pdGVtIHByb3A9XCJuYW1lMlwiIGxhYmVsPVwidGhpcyBpcyBub3Qgc2xvdFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtRm9ybUZpZWxkcy5uYW1lMlwiPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgXG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQgfSBmcm9tICd2dWUnO1xuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KFxue1xuXHRkYXRhKCkge1xuXHRcdHJldHVybiB7XG4gICAgXHRtRm9ybUZpZWxkczoge1xuICAgICAgXHRuYW1lMTogJycsXG4gICAgICAgIG5hbWUyOiAnJ1xuICAgICAgfVxuICAgIH1cbiAgfVxufSk7XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

here is the code:
```vue
<template>
  <el-form
    ref="createLegEntFormRef"
    :model="mFormFields"
    label-width="130px"
    >
    
    <el-form-item prop="name1">
      <slot name="label">
        <label>This is slot</label>
      </slot>
      <el-input v-model="mFormFields.name1"></el-input>
    </el-form-item>
    
    <el-form-item prop="name2" label="this is not slot">
      <el-input v-model="mFormFields.name2"></el-input>
    </el-form-item>
    
  </el-form>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent(
{
  data() {
    return {
      mFormFields: {
      	name1: '',
        name2: ''
      }
    }
  }
});
</script>
```

### What is Expected?

It is expected that ElFormItem's slot with name "label" to be inserted in the same place in html structure as element `<label>` when attribute 'label' attribute is used (without slot).

### What is actually happening?

When named slot "label" is used it is inserted as a child of `div.el-form-item__content` element instead of `div.el-form-item` element.
It could be easily observed in demo example code.

### Additional comments

_(empty)_

**Comment by josonho** [comment]
[元素加游乐场](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICBcdHJlZj1cImNyZWF0ZUxlZ0VudEZvcm1SZWZcIlxuICAgIDptb2RlbD1cIm1Gb3JtRmllbGRzXCJcbiAgICBsYWJlbC13aWR0aD1cIjEzMHB4XCJcbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW0gcHJvcD1cIm5hbWUxXCI+XG4gICAgICA8dGVtcGxhdGUgdi1zbG90OmxhYmVsPlRoaXMgaXMgc2xvdDwvdGVtcGxhdGU+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1Gb3JtRmllbGRzLm5hbWUxXCI+PC9lbC1pbnB1dD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICBcbiAgICA8ZWwtZm9ybS1pdGVtIHByb3A9XCJuYW1lMlwiIGxhYmVsPVwidGhpcyBpcyBub3Qgc2xvdFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtRm9ybUZpZWxkcy5uYW1lMlwiPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgXG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBkZWZpbmVDb21wb25lbnQgfSBmcm9tICd2dWUnO1xuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KFxue1xuXHRkYXRhKCkge1xuXHRcdHJldHVybiB7XG4gICAgXHRtRm9ybUZpZWxkczoge1xuICAgICAgXHRuYW1lMTogJycsXG4gICAgICAgIG5hbWUyOiAnJ1xuICAgICAgfVxuICAgIH1cbiAgfVxufSk7XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

try to code like this

**Comment by mPyth** [comment]
My fault, I would like to apologize.
Thanks for prompt and precise answer. 
I'm closing this ticket.
