### ISSUE TITLE
[Feature Request] [New Component] [popover] Fold extra button

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#7498]
Feature type: **`New Component`**

## Details

- New component name: `ElButtonsFold`

## Description

```vue
<template>
<el-buttons-fold :max="3">
  <el-button>button 1</el-button>
  <el-button>button 2</el-button>
  <el-button>button 3</el-button>
  <el-button>button 4</el-button>
</el-buttons-fold>
</template>
```

### Additional comments

When there are more than three "El buttons", the extra buttons will be folded into one more drop-down buttons

**Comment by emojiiii** [comment]
Duplicate of #7434
