### ISSUE TITLE
[Feature Request] [input] 表单组件在jsx中不写v-model不能输入信息

### ISSUE THREAD

**Issue by wilikeit** [element-plus/element-plus#7499]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `input`

## Description

为什么表单组件 在jsx中不加v-model就不能输入呢，如：
```vue
<el-input v-model={state.name} />
```
如果不要v-model={}，能正常渲染组件 ，但不能输入任何东西。我希望即使不写v-model={}，也能在输入框 输入东西，而我试了其它ui框架如antv、naive ui不要v-model={}，依然能输入东西，不存在此问题

希望自己写onChange也能获取输入，以方便跟jsx更好结合使用
```vue
<el-input onChange={}>
```

### Additional comments

_(empty)_

**Comment by TLovers** [comment]
我不知道我是否正确理解你说的，假设饿哦理解正确的前提下    onChange + modelValue 应该是可以实现你的需求吧 我JSX都是这样写的啊

**Comment by HeftyKoo** [comment]
issue 先关了，可以补充一下复现demo再提哈
