### ISSUE TITLE
[Bug Report] [Component] [date-picker] plus版本日期组件不支持keyup、keydown等键盘事件，现在我想触发键盘事件，要自己打补丁吗？ 

### ISSUE THREAD

**Issue by lily-elephant** [element-plus/element-plus#7506]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.22`
- Element Plus Version: `2.1.10`
- Browser / OS: `谷歌浏览器/mac`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0aW1lID0gcmVmKCcnKVxuY29uc3QgbWV0aG9kcyA9IHtcbiAgdGVzdCgpe1xuICAgIGNvbnNvbGUubG9nKCdlbnRlcuS6i+S7ticpXG4gIH0sXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gICAgPGVsLWRhdGUtcGlja2VyXG5cdFx0XHR2LW1vZGVsPVwidGltZVwiXG5cdFx0XHRyZWY9XCJzZXR0YWdSZWZcIlxuICAgICAgdHlwZT1cImRhdGVcIlxuXHRcdFx0QGtleXVwLmVudGVyPVwibWV0aG9kcy50ZXN0XCJcblx0XHQ+PC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup>
import { ref } from 'vue'
const time = ref('')
const methods = {
  test(){
    console.log('enter事件')
  },
}
</script>
<template>
  <p>
    <el-date-picker v-model="time" ref="settagRef" type="date" @keyup.enter="methods.test"></el-date-picker>
  </p>
</template>
```

### What is Expected?

期望能触发keyup enter事件，或提供一个api来触发键盘事件

### What is actually happening?

keyup事件无任何反应，无打印

### Additional comments

_(empty)_

**Comment by lily-elephant** [comment]
什么时候会给个答复呢

**Comment by emojiiii** [comment]
内部阻止了键盘事件的冒泡，请描述你的使用场景，让我尽可能了解你的需求

**Comment by lily-elephant** [comment]
> 内部阻止了键盘事件的冒泡，请尽可能描述你的使用场景，让我尽可能了解你的需求

我的需求就是要有键盘事件的冒泡，我现在的需求是，在一个form表单里使用日期组件，触发键盘事件，让光标自动聚焦下一个输入框

**Comment by lily-elephant** [comment]
> 内部阻止了键盘事件的冒泡，请尽可能描述你的使用场景，让我尽可能了解你的需求

form表单元素通常还是希望支持全键盘事件的，尤其是我方客户，会在enter后希望光标聚焦下一个元素，减少操作鼠标
