### ISSUE TITLE
[Bug Report] [Component] [select] default-first-option work delay / el-select组件使用default-first-option时有问题

### ISSUE THREAD

**Issue by wangyanchen** [element-plus/element-plus#7507]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `chrome 100.0.4896.127 / Macos 11.6.1`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBsaXN0ID0gcmVmKFtcbiAge1xuICAgIGlkOiAnMScsXG4gICAgbm86ICcxJyxcbiAgICBuYW1lOiAnb25lJ1xuICB9LFxuICB7XG4gICAgaWQ6ICcxMScsXG4gICAgbm86ICcxMScsXG4gICAgbmFtZTogJ29uZW9uZSdcbiAgfSxcbiAge1xuICAgIGlkOiAnMTExJyxcbiAgICBubzogJzExMScsXG4gICAgbmFtZTogJ29uZW9uZW9uZSdcbiAgfSxcbiAge1xuICAgIGlkOiAnMTExMScsXG4gICAgbm86ICcxMTExJyxcbiAgICBuYW1lOiAnb25lb25lb25lb25lJ1xuICB9XG5dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgXHQ8ZWwtc2VsZWN0XG5cdFx0XHRcdFx0XHRcdFx0di1tb2RlbD1cImlkXCJcblx0XHRcdFx0XHRcdFx0XHRkZWZhdWx0LWZpcnN0LW9wdGlvblxuXHRcdFx0XHRcdFx0XHRcdGZpbHRlcmFibGVcblx0XHRcdFx0XHRcdFx0XHRwbGFjZWhvbGRlcj1cIiBcIlxuXHRcdFx0XHRcdFx0XHRcdG5vLW1hdGNoLXRleHQ9XCIgXCJcblx0XHRcdFx0XHRcdFx0PlxuXHRcdFx0XHRcdFx0XHRcdDxlbC1vcHRpb25cblx0XHRcdFx0XHRcdFx0XHRcdHYtZm9yPVwiaXRlbSBpbiBsaXN0XCJcblx0XHRcdFx0XHRcdFx0XHRcdDprZXk9XCJpdGVtLmlkXCJcblx0XHRcdFx0XHRcdFx0XHRcdDpkaXNhYmxlZD1cIml0ZW0uZGlzYWJsZWRcIlxuXHRcdFx0XHRcdFx0XHRcdFx0OmxhYmVsPVwiaXRlbS5ubyArICctJyArIGl0ZW0ubmFtZVwiXG5cdFx0XHRcdFx0XHRcdFx0XHQ6dmFsdWU9XCJpdGVtLmlkXCJcblx0XHRcdFx0XHRcdFx0XHQ+XG5cdFx0XHRcdFx0XHRcdFx0PC9lbC1vcHRpb24+XG5cdFx0XHRcdFx0XHRcdDwvZWwtc2VsZWN0PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

例子：输入框输入oneo下拉列表显示3个，没有默认选中的,再输入成oneon才会自动选中第一个，删除成one选中会在第二个上。

### What is Expected?

每次更改输入框内容下拉列表光标能及时选中。

### What is actually happening?

现在每次输入都有延迟，hoverIndex是上一次输入的。

### Additional comments

希望尽快处理，谢谢。

**Comment by zhouxianglong** [comment]
解决了吗？我也遇到了这个问题
