### ISSUE TITLE
[Bug Report] [Component] [checkbox-group] 使用el-checkbox-group 绑定的数组是由reactive创建会导致数组丢失响应式.

### ISSUE THREAD

**Issue by Bo-Teng** [element-plus/element-plus#7508]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.2`
- Browser / OS: `chrome/Win10`
- Build Tool: `Vue CLI`

### Related Component

- `el-checkbox-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmxldCBjaGVja0xpc3QgPSByZWFjdGl2ZShbXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jaGVja2JveC1ncm91cCB2LW1vZGVsPVwiY2hlY2tMaXN0XCI+XG4gICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiT3B0aW9uIEFcIiAvPlxuICAgIDxlbC1jaGVja2JveCBsYWJlbD1cIk9wdGlvbiBCXCIgLz5cbiAgICA8ZWwtY2hlY2tib3ggbGFiZWw9XCJPcHRpb24gQ1wiIC8+XG4gIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击文本或者复选框

### What is Expected?

显示勾选或者取消勾选

### What is actually happening?

没有任何显示

### Additional comments

_(empty)_

**Comment by date13** [comment]
我也遇到了,切换路由后,第一个页面的数据绑定丢失了,用原生的input是可以的,但是el-input 就不行了,不知道怎么回事

**Comment by date13** [comment]
测试了下如果打开页面缓存
<keep-alive :include="cachedViews">
          <component :is="Component" :key="route.path"/>
        </keep-alive>
就会这样,原生的html组件input是正常改的,所有的elemnt-plus的组件都不行

**Comment by yxw007** [comment]
> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.2.13`
> * Element Plus Version: `2.0.2`
> * Browser / OS: `chrome/Win10`
> * Build Tool: `Vue CLI`
> 
> ## Reproduction
> ### Related Component
> * `el-checkbox-group`
> 
> ### Reproduction Link
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmxldCBjaGVja0xpc3QgPSByZWFjdGl2ZShbXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jaGVja2JveC1ncm91cCB2LW1vZGVsPVwiY2hlY2tMaXN0XCI+XG4gICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiT3B0aW9uIEFcIiAvPlxuICAgIDxlbC1jaGVja2JveCBsYWJlbD1cIk9wdGlvbiBCXCIgLz5cbiAgICA8ZWwtY2hlY2tib3ggbGFiZWw9XCJPcHRpb24gQ1wiIC8+XG4gIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> 
> ### Steps to reproduce
> 点击文本或者复选框
> 
> ### What is Expected?
> 显示勾选或者取消勾选
> 
> ### What is actually happening?
> 没有任何显示
> 
> ### Additional comments
> _(empty)_

![Untitled Diagram](https://user-images.githubusercontent.com/9338717/167236593-f75417ac-fc45-4e08-a34b-ed9b93e28347.jpg)

画张简图这样方便理解，可以调试下源码就知道了。底层实际是赋值的一个新数组，这种直接赋值新数组是不会有响应式的
如果想用响应式，第一种方式你说的用ref代替，第二种方式用对象包裹一层 比如：reactive({check:[]})  对象的属性更改就会具备响应式，最后触发effect 更新视图。

**Comment by Bo-Teng** [comment]
@yxw007 造成这个问题的原因如同这位老哥说的一样.最后感谢老哥的指点.

**Comment by yxw007** [comment]
> @yxw007 造成这个问题的原因如同这位老哥说的一样.最后感谢老哥的指点.

不客气，我也是觉得奇怪，然后就调试一遍才发现问题。如果遇到没人及时回答的问题，尝试自己主动调试源码看流程，这样会让你成长的更快。

**Comment by Bo-Teng** [comment]
@yxw007 https://github.com/element-plus/element-plus/issues/7671#issue-1234653773 老哥能看看这个问题吗? 如果可以能否加个好友.
