### ISSUE TITLE
这里是不是要兼容一下？

### ISSUE THREAD

**Issue by giserman001** [element-plus/element-plus#751]
![image](https://user-images.githubusercontent.com/24283342/100723554-dc8dfc80-33fc-11eb-9197-877c0dbcbcfc.png)

**Comment by JeremyWuuuuu** [comment]
For?

**Comment by giserman001** [comment]
> For?

![Uploading image.png…]()

**Comment by JeremyWuuuuu** [comment]
> For?

Sorry could you be more specific?

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
