### ISSUE TITLE
[Bug Report] [Style] [form-item, input] Wrong spacings in Form Elements

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#7519]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-form-item`
- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/form.html)

### Steps to reproduce

- input fields have a horizontal padding of 11px, but textarea 15px. it should be aligned and have the same spacing
- labels of form-items are using line-height (of 32px) which is a bad idea. As soon as the text breaks into multiple lines, the vertical space between the words is too large

### What is Expected?

- text should start aligned and don't use different spacing across different form element
- if form-item labels have multiple lines (i.e. in small screen resolutions), they still should look nice and not broken

### What is actually happening?

- text not aligned
- spacings for multi-line labels too big

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
I will ask the designer.
