### ISSUE TITLE
messageBox ，message

### ISSUE THREAD

**Issue by gyjtiancai** [element-plus/element-plus#752]
"element-plus": "^1.0.1-beta.0",

app.config.globalProperties中并无$confirm $alert  $message  等全局方法

**Comment by Ryan2128** [comment]
[DEMO](https://codesandbox.io/s/vigilant-roentgen-hbofh?file=/src/App.vue)

**Comment by gyjtiancai** [comment]
<el-button plain @click="confirm">确认消息</el-button>

**Comment by gyjtiancai** [comment]
`
<template>
<el-button plain @click="confirm">确认消息</el-button>
</template>

<script>
import { defineComponent, getCurrentInstance} from "vue";
export default defineComponent({
  name: "demo",
  setup() {
    const globalThis = getCurrentInstance();
    console.log(globalThis.appContext.app.config.globalProperties) 
    function confirm() {
       globalThis.appContext.app.config.globalProperties.$message({
        type: "info",
        message: "ok",
      });
    }
    return {
      confirm,
    };
  },
});
</script>
`
![1606822746(1)](https://user-images.githubusercontent.com/56705837/100735885-e881ba80-340c-11eb-9166-5e68be52e209.jpg)

**Comment by Ryan2128** [comment]
Have you installed the component library or corresponding components correctly and completely in entry file?

Complete:
```
import ElementPlus from 'element-plus';

app.use(ElementPlus)
```

On demand:
```
import { Message } from 'element-plus'

app.use(Message)
```

**Comment by JeremyWuuuuu** [comment]
Have you installed them globally? If you did not, then you are going to get error, these methods will not be automatically mounted to the `app.globalProperties`. After you register them globally, you can visit the member via
in setups
```ts
import { getCurrentInstance } from 'vue'
getCurrentInstance().appContext.config.globalProperties.$message
```
or in options API
```ts
{
  // rest..
  methods: {
    this.$message
  },
}
```

**Comment by gyjtiancai** [comment]
> 您是否在全球范围内安装了它们？如果您没有这样做，那么您将得到错误，这些方法将不会自动安装到`app.globalProperties`。在全球范围内注册后，您可以通过
> 设置访问会员
> 
> ```ts
> 进口 {  getCurrentInstance  } 从 'VUE' 
> getCurrentInstance （）。appContext 。配置。globalProperties 。$消息
> ```
> 
> 或在选项API中
> 
> ```ts
> { 
>   // rest ..
>   方法：{ 
>     this 。$ message 
>   } ，
> }
> ```

你好 入口文件中我全局注册了element-plus，  appContext.components中有elelemnt-plus注入的组件 但是没有我提及的message，messageBox等
![1606869642(1)](https://user-images.githubusercontent.com/56705837/100813347-1d782680-347a-11eb-822c-b5e222c64651.jpg)

**Comment by gyjtiancai** [comment]
> Have you installed the component library or corresponding components correctly and completely in entry file?
> 
> Complete:
> 
> ```
> import ElementPlus from 'element-plus';
> 
> app.use(ElementPlus)
> ```
> 
> On demand:
> 
> ```
> import { Message } from 'element-plus'
> 
> app.use(Message)
> ```

你好 入口文件中我全局注册了element-plus， appContext.components中有elelemnt-plus注入的组件 但是没有我提及的message，messageBox等
![1606869642(1)](https://user-images.githubusercontent.com/56705837/100813721-e8200880-347a-11eb-86cb-fe6221f15ea7.jpg)

**Comment by JeremyWuuuuu** [comment]
Because you have just replaced the globalProperties value with the assignment
`Object.assign()` at line12

**Comment by JeremyWuuuuu** [comment]
One way to solve this is that you need to use the original globalProperties as source then assign the the value that you wanted to the globalProperties instead of overriding it

**Comment by JeremyWuuuuu** [comment]
Using `Object.assign(app.config.globalProperties, {
  ...things
})`

**Comment by gyjtiancai** [comment]
> Using `Object.assign(app.config.globalProperties, { ...things })`

谢谢  或者把element全局注册放在Object.assign下面

**Comment by ro-n** [comment]
Why didn't `ctx` in `setup(props, ctx)` work? I came to find lots of `this` in Vue 2 could be replaced with `ctx` in Vue 3.

**Comment by canvascat** [comment]
> Why didn't `ctx` in `setup(props, ctx)` work? I came to find lots of `this` in Vue 2 could be replaced with `ctx` in Vue 3.
see #436, you can use
```ts
import { ElMessageBox, ElMessage } from "element-plus"
```
