### ISSUE TITLE
[Bug Report] [Build] [All] node 16.13.2 拉取 @vueuse/core 资源包错误

### ISSUE THREAD

**Issue by wq-ws** [element-plus/element-plus#7529]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.11`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

node版本切换为16.13.2，进行npm install，node_modules中@vueuse文件内容缺失，只有metadata文件夹，缺少core文件

### What is Expected?

文件完整

### What is actually happening?

文件缺失

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你可以尝试删除node_modules并且清除缓存后重新install

**Comment by wq-ws** [comment]
> 你可以尝试删除node_modules并且清除缓存后重新install

谢谢回复。
已经解决了，是因为@vueuse中 peerDependencies使用的动态的vue版本，本地dependencies使用的是固定版本的vue，导致了版本冲突，将vue改为动态版本就可以了
