### ISSUE TITLE
[Bug Report] [Component] [date-picker] 通过TSX的写法使用date-picker无法触发onChange事件

### ISSUE THREAD

**Issue by blueLi0428** [element-plus/element-plus#7531]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.6`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome 100.0.4896.127`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPSd0cyc+XG5cdGltcG9ydCB7IGRlZmluZUNvbXBvbmVudCwgaCwgcmVmIH0gZnJvbSAndnVlJztcblx0aW1wb3J0IHsgRWxEYXRlUGlja2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuICBleHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICAgIHNldHVwKCkge1xuICAgICAgY29uc3QgZGVtbyA9IHJlZihuZXcgRGF0ZSgpKVxuICAgICAgXG4gICAgICByZXR1cm4ge1xuICAgICAgICBkZW1vXG4gICAgICB9XG4gICAgfSxcbiAgICByZW5kZXIoY3R4KSB7XG4gICAgICByZXR1cm4gaChcbiAgICAgIFx0RWxEYXRlUGlja2VyLFxuICAgICAgICB7XG4gICAgICAgICAgbW9kZWxWYWx1ZTogY3R4LmRlbW8sXG4gICAgICAgICAgdHlwZTogJ2RhdGV0aW1lJyxcbiAgICAgICAgICBvbkNoYW5nZTogKHZhbHVlOiBhbnkpID0+IHtcbiAgICAgICAgICAgIC8vIOatpOWkhOeahGNoYW5nZeaWueazleWPquacieaJjeeCueWHu2NsZWFy5pe25omN5Lya6Kem5Y+RXG5cdFx0XHRcdFx0XHRhbGVydChjdHguZGVtbylcblx0XHRcdFx0XHR9LFxuICAgICAgICAgIG9uQmx1cjogKHYpID0+IHtcbiAgICAgICAgICAgIGFsZXJ0KGN0eC5kZW1vKVxuXHRcdFx0XHRcdH1cbiAgICAgICAgfVxuICAgICAgKVxuICAgIH1cbiAgfSlcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtkZW1vLnZ1ZX1cbn0iLCJfbyI6e319)

### Steps to reproduce

点击组件，不能触发onChange事件，也不能改变双向绑定的值

### What is Expected?

正确触发onChange事件

### What is actually happening?

无法触发

### Additional comments

_(empty)_

**Comment by baiwusanyu-c** [comment]
由于你用的jsx 或者是h方法写的模板，你需要手动接收变化后的值，因为在这个写法内 v-model语法糖失效了，因此不会触发change
```
render(ctx) {
    return h(
      ElDatePicker,
      {
        modelValue: ctx.demo,
        type: 'datetime',
        'onUpdate:modelValue': (value) =>{
          ctx.demo = value
        },
        onChange: (value: any) => {
          // 此处的change方法只有才点击clear时才会触发
          alert(ctx.demo)
        },
        onBlur: (v) => {
          alert('blur' + ctx.demo)
        }
      }
    )
  }
```

**Comment by blueLi0428** [comment]
> 由于你用的jsx 或者是h方法写的模板，你需要手动接收变化后的值，因为在这个写法内 v-model语法糖失效了，因此不会触发change
> 
> ```
> render(ctx) {
>     return h(
>       ElDatePicker,
>       {
>         modelValue: ctx.demo,
>         type: 'datetime',
>         'onUpdate:modelValue': (value) =>{
>           ctx.demo = value
>         },
>         onChange: (value: any) => {
>           // 此处的change方法只有才点击clear时才会触发
>           alert(ctx.demo)
>         },
>         onBlur: (v) => {
>           alert('blur' + ctx.demo)
>         }
>       }
>     )
>   }
> ```
非常感谢
