### ISSUE TITLE
[Bug Report] [Component] [date-picker] monthrange类型选择器在输入结束后报错

### ISSUE THREAD

**Issue by GuanJinsong** [element-plus/element-plus#7554]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.10`
- Element Plus Version: `2.0.0`
- Browser / OS: `chrome 版本 100.0.4896.127 / Max OS X 12.2.1 `
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-wimx8p?file=/src/main.js)

### Steps to reproduce

1、选择任一日期区间
2、键盘输入修改日期
3、得到错误：pickerOptions.value.parseUserInput is not a function

### What is Expected?

可以在输入框内手动输入日期

### What is actually happening?

报错

### Additional comments

_(empty)_

**Comment by xxweb123** [comment]
已提交修复申请等管理合并pr https://github.com/element-plus/element-plus/pull/7560

**Comment by GuanJinsong** [comment]
> 已提交修复申请等管理合并pr #7560

感谢

**Comment by mdoi2** [comment]
I have added three processes (isValidValue, parseUserInput, and handleClear) similar to daterange.
Please confirm.

pull request: https://github.com/element-plus/element-plus/pull/12929

**Comment by Jasonning92** [comment]
最新版本怎么还是有这个问题…………
