### ISSUE TITLE
[Feature Request] 关于namespace按需加载情况下如何修改

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#7555]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

根据官方文档https://element-plus.org/zh-CN/component/config-provider.html#对按钮进行配置
可以修改namespace没有问题，但是关于scss变量的修改我不知道该如何修改。
我是按需加载引入的组件。通过@forward方式进行修改无法实现，会产生报错。请问还有别的方式可以覆盖变量吗？
或者官方能否在文档上面增加一个修改示例呢？

### Additional comments

_(empty)_

**Comment by ht-sauce** [comment]
![image](https://user-images.githubusercontent.com/34828964/167247275-e80bc228-1639-4789-9bac-e474dd647dd2.png)
还有，我直接修改源码的情况下，发现有一些地方的namespace修改并没有完全应用到全局。比如弹窗这个位置的样式生成是错误的

**Comment by emojiiii** [comment]
@YunYouJun cc

**Comment by YunYouJun** [comment]
Please wait, our next version of CSS variables has modified almost all namespaces.

> 还有，我直接修改源码的情况下，发现有一些地方的namespace修改并没有完全应用到全局。比如弹窗这个位置的样式生成是错误的

Something is missing here, can you describe your expectations in more detail?

**Comment by ht-sauce** [comment]
> 

1、namespace应该是正常修改所有控制点，不应该出现bug
2、目前通过传统的scss变量覆盖方式无法覆盖namespace变量
个人是按需加载的组件，所以我能想到的只有@forward 方式，但是通过该方式
@forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
  $namespace: 'el' !default;
);
会提示原config.scss文件中没有使用!default，导致无法覆盖。
官方是否能提供其他方式，个人学艺不精。

**Comment by ht-sauce** [comment]
> Please wait, our next version of CSS variables has modified almost all namespaces.
> 
> > 还有，我直接修改源码的情况下，发现有一些地方的namespace修改并没有完全应用到全局。比如弹窗这个位置的样式生成是错误的
> 
> Something is missing here, can you describe your expectations in more detail?

1、namespace应该是正常修改所有控制点，不应该出现bug
2、目前通过传统的scss变量覆盖方式无法覆盖namespace变量
个人是按需加载的组件，所以我能想到的只有@forward 方式，但是通过该方式
@forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
  $namespace: 'el' !default;
);
会提示原config.scss文件中没有使用!default，导致无法覆盖。
官方是否能提供其他方式，个人学艺不精。

**Comment by kelvin-lemon** [comment]
最新的 2.2.0 版本，全局配置的 namsespace 为对 loading 生效
.use(ElementPlus, {
    namespace: 'xxx',
  })

**Comment by YunYouJun** [comment]
我们在新的版本中为 `$namespace` 添加了 `!default`。
