### ISSUE TITLE
[Feature Request] [Docs] 官网 黑夜样式是scss 皮肤样式文件 能不能分享一下

### ISSUE THREAD

**Issue by yuntian001** [element-plus/element-plus#7556]
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `All`

## Description

官网 黑夜样式是scss 皮肤样式文件 能不能分享一下

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[here](https://github.com/element-plus/element-plus/blob/dev/docs/.vitepress/vitepress/styles/code.scss)
