### ISSUE TITLE
[Bug Report] [TypeScript] [All] 在<script setup>按需引入样式丢失

### ISSUE THREAD

**Issue by guoqirong** [element-plus/element-plus#7566]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `chome 100.0.4896.127 / win10`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsQ2FyZCwgRWxJbWFnZSwgRWxMaW5rIH0gZnJvbSAnZWxlbWVudC1wbHVzJztcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jYXJkIGNsYXNzPVwiYm94LWNhcmRcIj5cbiAgICA8dGVtcGxhdGUgI2hlYWRlcj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiY2FyZC10aXRsZVwiPuWuouaIt+err+S6jOe7tOeggTwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1pbWFnZVxuICAgICAgY2xhc3M9XCJxci1pbWFnZVwiXG4gICAgICBzcmM9XCJodHRwczovL3N0YXRpYy5jbm9kZWpzLm9yZy9GdEcwWVZnUTZpZ2luaUxwZjlXNF9TaGppTGZVXCJcbiAgICAgIGZpdD1cImZpbGxcIlxuICAgID48L2VsLWltYWdlPlxuICAgIDxkaXYgY2xhc3M9XCJjbGllbnQtYm94XCI+XG4gICAgICA8ZWwtbGlua1xuICAgICAgICA6dW5kZXJsaW5lPVwiZmFsc2VcIlxuICAgICAgICBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL3NvbGl1cnkvbm9kZXItcmVhY3QtbmF0aXZlXCJcbiAgICAgICAgdGFyZ2V0PVwiX2JsYW5rXCJcbiAgICAgID7lrqLmiLfnq6/mupDnoIHlnLDlnYA8L2VsLWxpbms+IFxuICAgIDwvZGl2PlxuICA8L2VsLWNhcmQ+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgbGFuZz1cInNjc3NcIj5cblxuLmJveC1jYXJkIHtcbiAgLm5vdC1sb2dpbiB7XG4gICAgLmRlc2NyaWJlIHtcbiAgICAgIG1hcmdpbi10b3A6IDIwcHg7XG4gICAgICBmb250LXNpemU6IDE0cHg7XG4gICAgICAubm90LWJvdHRvbSB7XG4gICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICAgICAgaGVpZ2h0OiAyMHB4O1xuICAgICAgICBsaW5lLWhlaWdodDogMjBweDtcbiAgICAgIH1cbiAgICAgIC5lbC1saW5rIHtcbiAgICAgICAgbWFyZ2luLXRvcDogLTNweDtcbiAgICAgIH1cbiAgICB9XG4gIH1cbiAgLmVsLWNhcmRfX2hlYWRlciB7XG4gICAgcGFkZGluZzogOHB4IDIwcHg7XG4gICAgcGFkZGluZy1ib3R0b206IDA7XG4gICAgLmNhcmQtdGl0bGUge1xuICAgICAgaGVpZ2h0OiA0MHB4O1xuICAgICAgbGluZS1oZWlnaHQ6IDQwcHg7XG4gICAgICBmb250LXNpemU6IDE0cHg7XG4gICAgfVxuICB9XG4gIC5xci1pbWFnZSB7XG4gICAgd2lkdGg6IDI0OHB4O1xuICAgIGhlaWdodDogMjQ4cHg7XG4gIH1cbiAgLmNsaWVudC1ib3gge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIC5lbC1saW5rIHtcbiAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICAgIHdpZHRoOiAxMDAlO1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIH1cbiAgfVxufVxuPC9zdHlsZT5cblxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

组件按需引入，用<script setup>引入时样式丢失

### What is Expected?

能在<script setup>引入时包含样式一起自动引入

### What is actually happening?

在<script setup>引入时样式丢失

### Additional comments

_(empty)_

**Comment by yangxun521** [comment]
自动导入
推荐[#]
首先你需要安装unplugin-vue-components 和 unplugin-auto-import这两款插件
官网推荐的这种方式  我用的 头像  图片  等数据展示组件  都会丢失对应的css.js文件  
除非我在当前页面import { ElAvatar } from 'element-plus'引用一下 才行
官方啥时候修复昂！！！！！！！

**Comment by chenxch** [comment]
检查下components.d.ts中是否加载

**Comment by guoqirong** [comment]
用<script setup>的形式在components.d.ts是没有加载

**Comment by chenxch** [comment]
> 用<script setup>的形式在components.d.ts是没有加载

方便告知一下vite/unplugin-vue-components/unplugin-auto-import 这三个版本么

**Comment by guoqirong** [comment]
![image](https://user-images.githubusercontent.com/57247313/167303827-d3401105-39f6-49db-a8f3-76bcea37d6f3.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/167303925-59192b7e-6030-4138-84f4-74f5ce64f46a.png)
我的版本相对你的都比较低一些些，当时我是可以正常加载使用，看看上面的配置能否帮到你

**Comment by guoqirong** [comment]
![image](https://user-images.githubusercontent.com/57247313/167304598-533edf1f-99ba-409b-a61a-674505416fe4.png)
![image](https://user-images.githubusercontent.com/57247313/167304624-05565dd5-2987-4f48-84cc-d1ac1655f154.png)

改成一样的配置，el-image的样式还是丢失的

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/167304789-938c6e29-fadb-45d5-ad2b-46c631b52bee.png)
![image](https://user-images.githubusercontent.com/23251408/167304797-adc5667a-8f2a-4c3b-8bf8-65cd6bd0409b.png)
![image](https://user-images.githubusercontent.com/23251408/167304839-4c206c01-b8b5-4dcb-9dd6-d9b22dd9ea80.png)
试着清理一下node_modules下的.vite

**Comment by guoqirong** [comment]
![image](https://user-images.githubusercontent.com/57247313/167305098-e212e5be-210a-43f4-8479-e45381937283.png)
还是不行，没有ElImage的自动引入

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/167305260-95f95e89-9133-4a6c-b6c1-b33e87b23b62.png)
将这里删除

**Comment by guoqirong** [comment]
这里是引入组件，不引入能用吗？

**Comment by chenxch** [comment]
既然都是用了自动引入插件了，你再手动引入的话，插件会默认你要自己处理这个组件的引入，你自己引入缺少了引入样式的动作。

**Comment by guoqirong** [comment]
好的，明白了，谢谢，一直以为按需引入要自己引入😭😭😭😭

**Comment by chenxch** [comment]
问题解决了好，如果没有其他问题的话可以结束这个issue哈

**Comment by QJune** [comment]
我好像记得不是通过组件的方式使用elmessage样式需要手动引入，不然没样式

**Comment by guoqirong** [comment]
@chenxch 像这种ts直接使用的组件需要自己引入，但是样式会丢失怎么处理
import { ElMessage } from 'element-plus';
axios({
    url: `https://cnodejs.org/api/v1/user1/guoqirong`,
    method: 'get'
  }).then(({data}) => {
    console.log(data);
  }).catch(e => {
    ElMessage.error('请求失败');
    console.error(e)
  })

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/167423116-4b6ea786-089e-4294-b993-a88644e70ed3.png)
