### ISSUE TITLE
[Bug Report] [Component] [cascader] cascader tooltip 还未完全修复

### ISSUE THREAD

**Issue by arkfancy** [element-plus/element-plus#7583]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome/101.0.4951.54 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/cascader.html#%E5%A4%9A%E9%80%89)

### Steps to reproduce

查看官方文档

### What is Expected?

完全不遮住

### What is actually happening?

遮住了

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/30465365/167351135-cc21a182-6367-4df9-944b-1c28308547fd.png)
![image](https://user-images.githubusercontent.com/30465365/167351161-fb33f9e5-b6db-4178-91b9-f3a3508479ce.png)

**Comment by itDjango** [comment]
有没有临时解决方案，我对类名设置z-index 好像不好用

**Comment by xiaoxian521** [comment]
Then use the official website documentation to see if this problem still exists
