### ISSUE TITLE
[Bug Report] [Component] [rate] el-rate 的size属性无效

### ISSUE THREAD

**Issue by QianTangrong** [element-plus/element-plus#7584]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-rate`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2YWx1ZSA9IHJlZihudWxsKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1yYXRlIHYtbW9kZWw9XCJ2YWx1ZVwiIHNpemU9XCJsYXJnZVwiIC8+XG4gIDxiciAvPlxuICA8ZWwtcmF0ZSB2LW1vZGVsPVwidmFsdWVcIiAvPlxuICA8YnIgLz5cbiAgPGVsLXJhdGUgdi1tb2RlbD1cInZhbHVlXCIgc2l6ZT1cInNtYWxsXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

size设置了无效

### What is Expected?

size有明显的区分

### What is actually happening?

size不同无区别

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/30518686/167360324-403c01bd-a314-4883-99de-3054fd5bab0c.png">

**Comment by ZhangWei12138** [comment]
遇到了相同的问题 只是高度产生了变化 但是是记得图标大小并无改变
