### ISSUE TITLE
[Bug Report] [Component] [icon] switch图标不存在

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#7585]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome/101.0.4951.54 / Windows 10 `
- Build Tool: `Vite`

### Related Component

- `el-icon`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBTd2l0Y2gsVXNlciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaWNvbj48c3dpdGNoIC8+PC9lbC1pY29uPlxuICA8ZWwtaWNvbj48dXNlciAvPjwvZWwtaWNvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce
```
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { Switch,User } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
</script>

<template>
  <el-icon><switch /></el-icon>
  <el-icon><user /></el-icon>
</template>
```

### What is Expected?

有图标

### What is actually happening?

没有图标

### Additional comments

_(empty)_

**Comment by btea** [comment]
```html
<el-icon><Switch /></el-icon>
```
首字母大写

**Comment by WangJincheng4869** [comment]
> ```
> <el-icon><Switch /></el-icon>
> ```
> 
> 首字母大写

这个有啥说法吗？为什么这个需要大写？

**Comment by btea** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/switch  svg有switch元素

**Comment by WangJincheng4869** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/switch svg有switch元素

原来如此，建议将API文档中的复制代码，这个图标默认为首字母大写。目前是小写的。
或者加个前缀？以免跟其他元素冲突？

**Comment by btea** [comment]
嗯，可以，有兴趣提个pr吗？

**Comment by WangJincheng4869** [comment]
> 嗯，可以，有兴趣提个pr吗？

额  我不会ts.....    其实我就是个臭写java的....    文档里面那个复制代码的部分我木有找到在哪里......

**Comment by btea** [comment]
这样啊，那我待会修一下
