### ISSUE TITLE
[Bug Report] [Component] [upload] 上传组件在2.0.5版本重构后无法获取组件内的属性

### ISSUE THREAD

**Issue by kybetter** [element-plus/element-plus#7589]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `macOS 12.0.1`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgdXBsb2FkID0gcmVmKG51bGwpO1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGJlZm9yZUF2YXRhclVwbG9hZDogVXBsb2FkUHJvcHNbJ2JlZm9yZVVwbG9hZCddID0gKHJhd0ZpbGUpID0+IHtcbiAgLy8g5ZyoIDIuMC40IOWPiuS5i+WJjeeahOeJiOacrOiDveWkn+WPluWIsCBkYXRhIOWxnuaAp1xuICAvLyDoh6ogMi4wLjUg54mI5pys6YeN5p6E5LiK5Lyg57uE5Lu25ZCO77yM5bCx5Y+W5LiN5Yiw5LqGXG4gIGNvbnNvbGUubG9nKHVwbG9hZC5kYXRhKVxuICByZXR1cm4gdHJ1ZVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIHJlZj1cInVwbG9hZFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9qc29ucGxhY2Vob2xkZXIudHlwaWNvZGUuY29tL3Bvc3RzL1wiXG4gICAgOmJlZm9yZS11cGxvYWQ9XCJiZWZvcmVBdmF0YXJVcGxvYWRcIlxuICAgIDpkYXRhPVwie25hbWU6IDEyM31cIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在上传组件的 before-upload 生命周期中获取组件的 data 属性值，获取不到。请通过看演示链接查看

### What is Expected?

能够获取到属性值

### What is actually happening?

2.0.5版重构后，就取不到了

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
因为现在使用了 `defineExpose` 去声明对外暴露的属性，文档上没有的代表是`privated`。

**Comment by kybetter** [comment]
可文档上面有 data、name、headers 这些属性的呀。

**Comment by kybetter** [comment]
而且是小版本改动导致的这个问题。这就属于破坏性重构了。

**Comment by emojiiii** [comment]
对于某些用户来说确实是`breaking change`，但是因为文档上从未对外暴露这些内容，所以某些方面又不是`breaking change`.
