### ISSUE TITLE
elemens plus l

### ISSUE THREAD

**Issue by kamalalnabrissi2017** [element-plus/element-plus#759]
https://www.github.com/element-plus/vue-cli-plugin-element-plus/tree/master/generator%2Ftemplates%2Fsrc%2FApp.vue

**Comment by g3r4n** [comment]
@kamalalnabrissi2017 what's the issue ?

**Comment by g3r4n** [comment]
@zazzaz It's spam like #758

**Comment by JeremyWuuuuu** [comment]
Closing it due to its irrelevant
