### ISSUE TITLE
[Bug Report] [Component] [button] ElButton type "text" not working as expected

### ISSUE THREAD

**Issue by OKAAMI** [element-plus/element-plus#7591]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCI+VGV4dCBCdXR0b248L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwidGV4dFwiIGRpc2FibGVkPlRleHQgQnV0dG9uPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Create a ElButton component with type="text i.e
<el-button type="text">Text Button</el-button>

### What is Expected?

Render of a text button

### What is actually happening?

Render of a normal button and a warning in the console that type 'text' is not supported/expected.

### Additional comments

Only happening with the latest version of Element Plus 2.2.0, reverting to 2.1.11 works as expected.

**Comment by NO-MAP** [comment]
[ElButton  doc](https://element-plus.org/en-US/component/button.html#button-attributes)

```
type:  primary / success / warning / danger / info
text:  false
bg: false
```
`2.2.0` 版本  `text` 更改为了单独的属性
并且加上了边框

**Comment by emojiiii** [comment]
please see the [docs](https://github.com/element-plus/element-plus/discussions/7578)
