### ISSUE TITLE
[Bug Report] [Component] [table, image] 在el-table中使用图片预览功能显示异常

### ISSUE THREAD

**Issue by jcindex** [element-plus/element-plus#7594]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome/86.0.4240.198`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-image`

### Reproduction Link

[CodePen](https://codepen.io/nardy/pen/MWQyKed)

### Steps to reproduce

点击表格中的图片预览

### What is Expected?

正常预览图片并不会产生查看干扰

### What is actually happening?

预览界面受到表格项的干扰

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/7412888/167404145-11295a02-95b7-467f-8d96-2623d176f28f.png)

**Comment by josonho** [comment]
[CodePen](https://codepen.io/shungege1/pen/YzeqwjY)
You can use the preview-teleported property, to make the viewer inserted in the body.

**Comment by plainheart** [comment]
Also please consult the [FAQ](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89).

**Comment by sususususususs** [comment]
我2.0.1版本的 加了preview-teleported="true"但是没用
