### ISSUE TITLE
el-table-column: vnode error with show-overflow-tooltip

### ISSUE THREAD

**Issue by acupofspirt** [element-plus/element-plus#760]
Vue 3.0.3, element-plus 1.0.1-beta.1

`show-overflow-tooltip` on `el-table-column` component produces errors

![image](https://user-images.githubusercontent.com/1342726/100798381-a53b4200-3434-11eb-8465-857f63c6699d.png)

**Comment by JeremyWuuuuu** [comment]
Yep the overflow tooltip had a bug and it's here #728

**Comment by JeremyWuuuuu** [comment]
It will be fixed very soon
