### ISSUE TITLE
[Bug Report] [Component] el-dropdown-item点击后内容动态更新，导致el-dropdown不会自动隐藏

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7603]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-dropdown-item`
- `el-dropdown-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZHJvcGRvd24gQGNvbW1hbmQ9XCJoYW5kbGVDb21tYW5kXCI+XG4gICAgPHNwYW4gY2xhc3M9XCJlbC1kcm9wZG93bi1saW5rXCI+XG4gICAgICBEcm9wZG93biBMaXN0PGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1yaWdodFwiPjxhcnJvdy1kb3duIC8+PC9lbC1pY29uPlxuICAgIDwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGNvbW1hbmQ9XCJhXCI+XG4gICAgICAgICAgPHNwYW4gdi1pZj1cInN0YXRlXCI+XG4gICAgICAgICAgICBBY3Rpb24gMSAtIHRydWVcbiAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgPHNwYW4gdi1lbHNlPlxuICAgICAgICAgICAgQWN0aW9uIDEgLSBmYWxzZVxuICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgQXJyb3dEb3duIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuY29uc3Qgc3RhdGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZUNvbW1hbmQgPSAoY29tbWFuZDogc3RyaW5nKSA9PiB7XG4gIGlmIChjb21tYW5kID09PSAnYScpIHtcbiAgICBzdGF0ZS52YWx1ZSA9ICFzdGF0ZS52YWx1ZVxuICB9XG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1zaG93Y2FzZSAuZWwtZHJvcGRvd24tbGluayB7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击下拉选项
2. 下拉菜单不会自动隐藏

### What is Expected?

下拉菜单自动隐藏

### What is actually happening?

下拉菜单没有自动隐藏

### Additional comments

_(empty)_

**Comment by tolking** [comment]
This issues seems to have been fixed
