### ISSUE TITLE
[Bug Report] [Style] [date-picker] DatePicker样式问题

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#7613]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome 100.0.4896.75`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBkYXRlID0gcmVmKFtdKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwiZGF0ZVwiIHR5cGU9XCJkYXRlcmFuZ2VcIiA6Y2xlYXJhYmxlPVwiZmFsc2VcIj48L2VsLWRhdGUtcGlja2VyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.导入DatePicker组件

### What is Expected?

样式正常

### What is actually happening?

组件高度不正常

### Additional comments

_(empty)_

**Comment by et2012** [comment]
.el-range-input 缺少两个高度样式，外侧又没有包裹一层 el-input__wrapper，导致内部原生输入框高度变成 100%，和内部文字高度一致。

修复方式是加上这两个样式，以 small 为例：

.el-range-editor--small .el-range-input {
    height: var(--el-input-inner-height);
    line-height: var(--el-input-inner-height);
}

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by plainheart** [comment]
Fixed in #7608
