### ISSUE TITLE
[Bug Report] [Style] [input] input标签同时设置input-style固定宽度与clearable，会造成宽度冲突

### ISSUE THREAD

**Issue by CR-pcs** [element-plus/element-plus#7618]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `e.g. Chrome 96.0.4664.45 / macOS 12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ1FBUSBoZWxwLi4nKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgOmlucHV0LXN0eWxlPVwie3dpZHRoOiAnMzAwcHgnfVwiIGNsZWFyYWJsZSAvPlxuICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuXHRpbnB1dOagh+etvuWQjOaXtuiuvue9rmlucHV0LXN0eWxl5Zu65a6a5a695bqm5LiOY2xlYXJhYmxl77yM5Lya6YCg5oiQ5a695bqm5Yay56qBXG4gIFxuICA8YnIvPjxici8+PGJyLz5cbiAgPHA+XG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiA6aW5wdXQtc3R5bGU9XCJ7d2lkdGg6ICczMDBweCd9XCIgY2xlYXJhYmxlIC8+XG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiA6aW5wdXQtc3R5bGU9XCJ7d2lkdGg6ICczMDBweCd9XCIgY2xlYXJhYmxlIC8+XG4gIDwvcD5cbiAgPGJyLz48YnIvPjxici8+XG4gIDxkaXY+XG4gICAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiBjbGVhcmFibGUvPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gIDwvZGl2PlxuICA8YnIvPjxici8+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('QAQ help..')
</script>

<template>
  <h1>{{ msg }}</h1>
  <el-input v-model="msg" :input-style="{width: '300px'}" clearable />
  <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
</template>
```

### What is Expected?

设置clearable后的取消图标，出现在input内部

### What is actually happening?

设置clearable后的取消图标，出现在input外部

### Additional comments

_(empty)_

**Comment by william-xue** [comment]
![1F3F237B-CC0F-4B6B-B1B8-EC034FCE4323](https://user-images.githubusercontent.com/20151622/168222956-869c6c6e-f78d-40f7-a472-f030896d79ed.png)
you can add   {box-sizing: border-box;
    width: 100%;}  in class .el-input__wrapper

**Comment by william-xue** [comment]
later  i will take a pr
