### ISSUE TITLE
NavMenu 导航菜单 水平模式与文档的demo不一致（子菜单的呈现方式）

### ISSUE THREAD

**Issue by zychome** [element-plus/element-plus#762]
![Dingtalk_20201202102459](https://user-images.githubusercontent.com/2106842/100820197-abf3a480-3488-11eb-8990-cc3f2de5284a.jpg)
![Dingtalk_20201202102435](https://user-images.githubusercontent.com/2106842/100820214-b31ab280-3488-11eb-9a21-c4e9b506ff01.jpg)

**Comment by JeremyWuuuuu** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by JeremyWuuuuu** [comment]
Can you provide a minimal reproducible code or link?

**Comment by zychome** [comment]
`<div>
    <el-menu
      default-active="1"
      class="el-menu-demo"
      mode="horizontal"
      background-color="#545c64"
      text-color="#fff"
      active-text-color="#ffd04b">
      <el-menu-item index="1">处理中心</el-menu-item>
      <el-submenu index="2">
        <template #title>我的工作台</template>
        <el-menu-item index="2-1">选项1</el-menu-item>
        <el-menu-item index="2-2">选项2</el-menu-item>
        <el-menu-item index="2-3">选项3</el-menu-item>
        <el-submenu index="2-4">
          <template #title>选项4</template>
          <el-menu-item index="2-4-1">选项1</el-menu-item>
          <el-menu-item index="2-4-2">选项2</el-menu-item>
          <el-menu-item index="2-4-3">选项3</el-menu-item>
        </el-submenu>
      </el-submenu>
      <el-menu-item index="3" disabled>消息中心</el-menu-item>
      <el-menu-item index="4"><a href="https://www.ele.me" target="_blank">订单管理</a></el-menu-item>
    </el-menu>
  </div>`

**Comment by Liiked** [comment]
is there any possibility you've done something which affects or covers elemet-plus styles?

**Comment by zychome** [comment]
> is there any possibility you've done something which affects or covers elemet-plus styles?

谢谢 ，确实是这个原因

下面的li影响到了菜单样式
li {
  display: inline-block;
  margin: 0 10px;
}
