### ISSUE TITLE
[Bug Report] [Build] FormInstance引用报错

### ISSUE THREAD

**Issue by RexHarris** [element-plus/element-plus#7620]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `1.1.0-beta.24`
- Browser / OS: `mac OS 12.2.1`
- Build Tool: `Vue CLI`

### Related Component

- `N/A`

### Reproduction Link

[Link]()

### Steps to reproduce

!

### What is Expected?

!

### What is actually happening?

!

### Additional comments

![C1F2EFB8-A542-4237-9ADC-65BF188B3A67](https://user-images.githubusercontent.com/43196431/167610197-708c8317-c727-45b4-923a-5110c62afb34.png)

构建时的报错：
![02559B65-519B-4532-8727-2CC1C5078846](https://user-images.githubusercontent.com/43196431/167610321-a4d1e487-e839-4424-818b-8c68f71d52bd.png)

**Comment by chenxch** [comment]
see #7275

**Comment by RexHarris** [comment]
I saw it before, and I has tried it already. but nothing happened. still the same.
![image](https://user-images.githubusercontent.com/43196431/167756625-9bec895f-04ee-48b4-8221-fbed6169d54f.png)
