### ISSUE TITLE
vue3 tsx的情况下报onClick类型没有找到

### ISSUE THREAD

**Issue by StringLiu2** [element-plus/element-plus#763]

**Comment by StringLiu2** [comment]
![image](https://user-images.githubusercontent.com/44939840/100819042-56b69380-3486-11eb-8ccc-fd32dd13ef1e.png)
报错没找到onClick类型？怎么回事？

**Comment by JeremyWuuuuu** [comment]
This is related to the jsx plugin which does not recognize the emitting events we declared in the `emits` field. Definitely not from our side.

**Comment by JeremyWuuuuu** [comment]
FYI https://github.com/vuejs/vue-next/issues/1356 https://github.com/vuejs/vue-next/pull/2628/files

**Comment by Tarrowren** [comment]
我看了其他框架的源码，这是目前可行的方式
```typescript
    props: { 
        onClick: Function as PropType<(e: MouseEvent) => void>
    },
    emits: {
        click: (e: MouseEvent) => {
            return true;
        }
    },
```
![1](https://user-images.githubusercontent.com/35626141/101765528-65ebb000-3b1c-11eb-9a31-e6cb3f7c8612.png)

**Comment by hj2060** [comment]
作者大大们 有计划什么时候支持 tsx 的自定义事件嘛

**Comment by uinio** [comment]
#https://github.com/vuejs/jsx-next/issues/248

**Comment by JeremyWuuuuu** [comment]
> 作者大大们 有计划什么时候支持 tsx 的自定义事件嘛

Customized event requires to replace declaration of `JSXAttributes`
You can see  https://github.com/element-plus/element-plus/issues/763#issuecomment-742457312 here, he mentioned declaring `onClick` in the props field. But we uses `emits`, we can only rely on the toolchain to get mature.

**Comment by shmy** [comment]
same issue

**Comment by uinio** [comment]
```ts
import { defineComponent, HTMLAttributes } from 'vue';

export interface IconProps extends HTMLAttributes {
  icon: string;
}

export default defineComponent({
  name: 'fontIcon',
  setup(props: IconProps) {
    return () => (
      <>
        <div>${props.icon}</div>;
      </>
    );
  },
});
```
This means that element-plus needs to be modified

or
https://github.com/element-plus/element-plus/issues/763#issuecomment-753630241

**Comment by uinio** [comment]
add jsx.d.ts 
```ts
import 'vue';
import { VNodeChild } from '@vue/runtime-core';
import { HTMLAttributes } from '@vue/runtime-dom';

/**
 * jsx component compatible template
 */

export type JsxNode = VNodeChild | JSX.Element;

export interface SlotDirective {
  [name: string]: () => JsxNode;
}

type JsxComponentCustomProps = {
  vModel?: unknown;
  vModels?: unknown[];
  vCustom?: unknown[];
  vShow?: boolean;
  vHtml?: JsxNode;
  vSlots?: SlotDirective;
} & Omit<HTMLAttributes, 'innerHTML'> & {
    innerHTML?: JsxNode;
  };

declare module 'vue' {
  interface ComponentCustomProps extends JsxComponentCustomProps {}
}

```

**Comment by zhuqingguang** [comment]
I also encounter same issue when i use tsx and el-table-column：
![image](https://user-images.githubusercontent.com/24694223/108519836-fd336780-7304-11eb-83ed-07d80bb0fafc.png)

how to fix it ?

**Comment by wenfangdu** [comment]
`@ts-ignore`

**Comment by wenfangdu** [comment]
@uinio How to add types for native HTML elements as well?

![image](https://user-images.githubusercontent.com/28700378/119078449-cca8ba00-ba28-11eb-876c-00d39f70c853.png)

**Comment by uinio** [comment]
add jsx.d.ts to src 

https://github.com/uinio/vite-vue-starter/blob/main/src/jsx.d.ts
