### ISSUE TITLE
[Bug Report] [Component] [input] textarea 出现滚动会导致边框不可见

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#7630]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwidGV4dGFyZWExXCJcbiAgICBhdXRvc2l6ZVxuICAgIHR5cGU9XCJ0ZXh0YXJlYVwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAvPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luOiAyMHB4IDBcIiAvPlxuICA8ZWwtZGlhbG9nIDptb2RlbFZhbHVlPVwidHJ1ZVwiPlxuICBcdDxlbC1pbnB1dFxuICAgIHYtbW9kZWw9XCJ0ZXh0YXJlYTJcIlxuICAgIDphdXRvc2l6ZT1cInsgbWluUm93czogMiwgbWF4Um93czogNCB9XCJcbiAgICB0eXBlPVwidGV4dGFyZWFcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCJcbiAgLz5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdGV4dGFyZWExID0gcmVmKCcnKVxuY29uc3QgdGV4dGFyZWEyID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

 Element Plus Playground 

### What is Expected?

边框可见

### What is actually happening?

边框不可见

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
被滚动条的背景盖住了
::-webkit-scrollbar-track {
  background: transparent;
}

**Comment by gjfei** [comment]
被滚动条的的背景覆盖了，为什么从之前的border 改成了box-shaw呢？

**Comment by HeftyKoo** [comment]
Duplicate: #6737
