### ISSUE TITLE
[Feature Request] [message] ElMessage 使用grouping属性时的样式问题

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#7635]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `message`

## Description

使用了unplugin-auto-import和unplugin-vue-components插件以及webpack。发现在ElMessage 使用grouping属性时样式有问题。 判断是因为内部的el-badge的样式没有生效，这个问题是应该谁来处理？

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
![image](https://user-images.githubusercontent.com/60815493/167822191-76d69701-cfbb-4fe0-8422-e0356c47f884.png)

**Comment by chenxch** [comment]
可能需要在文档中说明在使用grouping模式下需要手动引入badge的样式

**Comment by PeyFon** [comment]
> 

我个人其实更倾向于antfu解决插件在webpack下自动引入的问题，我认为它跟目前的v-loading和el-message不生效都是同一类问题。

**Comment by PeyFon** [comment]
> 可能需要在文档中说明在使用grouping模式下需要手动引入badge的样式

我个人认为它跟v-loading和el-message不生效一样，都是自动引入插件没处理好的问题。目前可能都得手动引入了，或者升级为vite或许能解决？

**Comment by chenxch** [comment]
vite我测试过了，一样的表现。 文档中有说明正对函数式组件的引用方法
![image](https://user-images.githubusercontent.com/23251408/167977458-593f775f-2426-4ede-9153-7531c349fc47.png)

**Comment by PeyFon** [comment]
> vite我测试过了，一样的表现。 文档中有说明正对函数式组件的引用方法 ![image](https://user-images.githubusercontent.com/23251408/167977458-593f775f-2426-4ede-9153-7531c349fc47.png)

那我还是手动引用样式吧，希望能在官方文档里的message模块部分跟大家说明一下。

**Comment by ZinLiao** [comment]
> > 可能需要在文档中说明在使用grouping模式下需要手动引入badge的样式
> 
> 我个人认为它跟v-loading和el-message不生效一样，都是自动引入插件没处理好的问题。目前可能都得手动引入了，或者升级为vite或许能解决？

没用，vite一样，所有用el-overlay都会出现样式丢失问题，而且是编译之后有问题，开发模式没问题

**Comment by tolking** [comment]
Fix in #8809
