### ISSUE TITLE
[Bug Report] [Component] 鼠标悬浮在文字上，显示下拉，点击下面的选项时报错了。

### ISSUE THREAD

**Issue by chenrihong** [element-plus/element-plus#7643]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Edge 101`
- Build Tool: `Vite`

### Related Component

- `el-dropdown-item`
- `el-dropdown`
- `el-radio-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxlbC1kcm9wZG93biBjbGFzcz1cInVzZXJuYW1lXCIgOmhpZGUtb24tY2xpY2s9XCJmYWxzZVwiIHRyaWdnZXI9XCJob3ZlclwiPlxuICAgICAgICAgICAgPGVsLWxpbmsgOnVuZGVybGluZT1cImZhbHNlXCI+XG4gICAgICAgICAgICAgICAg5byg5LiJIHt7IHRoZW1lTmFtZSB9fSAgICAgICAgICAgICAgIFxuICAgICAgICAgICAgPC9lbC1saW5rPlxuICAgICAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICAgICAgIFxuICBcbiAgICAgICAgICAgICAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJ0aGVtZU5hbWVcIiBzaXplPVwic21hbGxcIj5cbiAgICAgICAgICAgICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiZGFya1wiPua3seiJsjwvZWwtcmFkaW8tYnV0dG9uPlxuICAgICAgICAgICAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJibHVlXCI+6JOd55m9PC9lbC1yYWRpby1idXR0b24+XG4gICAgICAgICAgICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cImdyZWVuXCI+57u/55m9PC9lbC1yYWRpby1idXR0b24+XG4gICAgICAgICAgICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cImdyZXlcIj7ngbDnmb08L2VsLXJhZGlvLWJ1dHRvbj5cbiAgICAgICAgICAgICAgPC9lbC1yYWRpby1ncm91cD5cblxuICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGxuYWcgPSByZWYoJ2NuJylcbmNvbnN0IHRoZW1lTmFtZSA9IHJlZignZGFyaycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

鼠标悬浮在文字上，显示下拉，点击下面的选项时报错了。

### What is Expected?

不应该报错

### What is actually happening?

报错

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
el-radio-group与el-popover配合使用也会报错

**Comment by tolking** [comment]
This issues seems to have been fixed.
