### ISSUE TITLE
[Feature Request] [Enhancement] whether to refactor to <script setup>

### ISSUE THREAD

**Issue by josonho** [element-plus/element-plus#7650]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `All`

## Description

I see that most of the vue files use \<script lang="ts" setup>, 
only a few still use \<script lang="ts">, 
please can I refactor them all to \<script lang="ts" setup> ?

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/26833520/168012566-05988f85-2fd6-4201-b4d7-23f435ed3b1c.png)
![image](https://user-images.githubusercontent.com/26833520/168012678-94b95275-0301-4a82-ad96-17a3eed07ce9.png)

**Comment by JeremyWuuuuu** [comment]
Already WIP, see #6114

**Comment by JeremyWuuuuu** [comment]
@josonho If you would like to work on this, please go to #6114 and do https://github.com/element-plus/element-plus/issues/6114#issuecomment-1125552539. 👍

**Comment by josonho** [comment]
hi @JeremyWuuuuu, 
ashamed to say, i don't know how to ping you, can you guide me？

**Comment by JeremyWuuuuu** [comment]
> hi @JeremyWuuuuu, ashamed to say, i don't know how to ping you, can you guide me？

You just did.

If you would like to keep in touch, join us on [Discord](https://discord.link/ElementPlus)

**Comment by josonho** [comment]
@JeremyWuuuuu I'd like to work on [option, option-group, radio, radio-button, radio-group, select, select-v2].🙋‍♂️

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu I'd like to work on [option, option-group, radio, radio-button, radio-group, select, select-v2].🙋‍♂️

Please ping me in #6114 and take one or two component(s) at a time would be better. Don't put too much pressure.
