### ISSUE TITLE
[Feature Request] bg-purple 样式内容文档有吗？

### ISSUE THREAD

**Issue by quliting** [element-plus/element-plus#7651]
### Existing Component
是

### Component Name
layout

### Description
https://element-plus.org/zh-CN/component/layout.html#%E5%9F%BA%E7%A1%80%E5%B8%83%E5%B1%80
没有找到bg-purple 的样式文档和plus所有的样式文档；

**Comment by JeremyWuuuuu** [comment]
No, this is unocss, you need to install them locally.
