### ISSUE TITLE
[Bug Report] [Component] [date-picker] Cannot adjust the first day of week in date-picker

### ISSUE THREAD

**Issue by campions** [element-plus/element-plus#7659]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome Version 101.0.4951.54 (Official Build) (arm64)`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/vee-validate-v4-with-element-plus-framework-forked-n5esvw?file=/package.json)

### Steps to reproduce

1. Try to open the date picker
2. See Sunday as first day of week

### What is Expected?

See Monday as first day of week

### What is actually happening?

Sunday is first day of week

### Additional comments

_(empty)_

**Comment by iamkun** [comment]
https://github.com/element-plus/element-plus/issues/8007
