### ISSUE TITLE
[Bug Report] [Component] [tabs] el-tabs 设置了 name，但是会跟默认的 index 冲突

### ISSUE THREAD

**Issue by Linhongbin-1111** [element-plus/element-plus#7662]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `chrome 99`
- Build Tool: `Vue CLI`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJhY3RpdmVOYW1lXCJcbiAgICB0eXBlPVwiY2FyZFwiXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEB0YWItY2xpY2s9XCJoYW5kbGVDbGlja1wiXG4gID5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLor7fmsYJcIiBuYW1lPVwiMFwiPlVzZXI8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIkNvbmZpZ1wiIG5hbWU9XCIxXCI+Q29uZmlnPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJSb2xlXCIgbmFtZT1cIjJcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCIgbmFtZT1cIjNcIj5UYXNrPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYnNQYW5lQ29udGV4dCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgYWN0aXZlTmFtZSA9IHJlZignZmlyc3QnKVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICh0YWI6IFRhYnNQYW5lQ29udGV4dCwgZXZlbnQ6IEV2ZW50KSA9PiB7XG4gIGNvbnNvbGUubG9nKGFjdGl2ZU5hbWUudmFsdWUpXG4gIGNvbnNvbGUubG9nKHRhYiwgZXZlbnQpXG59XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击不同 tab，看控制台打印

### What is Expected?

activeName 输出应对应 tab 的 name

### What is actually happening?

输出的 activeName 是有问题的

### Additional comments

_(empty)_

**Comment by Linhongbin-1111** [comment]
found the reason, callback for tab-click before activeName changes.
It is recommended to use tab-change as an example to avoid misleading.

**Comment by HeftyKoo** [comment]
see: https://github.com/element-plus/element-plus/issues/10519#issuecomment-1307386732

**Comment by Linhongbin-1111** [comment]
你好，我是林鸿斌。我已收到你的来信，谢谢你~保持开心~ 不用回复！
