### ISSUE TITLE
[Bug Report] [Component] [tree-v2] el-tree-v2当手动触更新checkedKeys时，没有触发checkChange事件。

### ISSUE THREAD

**Issue by JobinJia** [element-plus/element-plus#7668]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome 版本 100.0.4896.127 / Intel Mac OS 12.3.1 `
- Build Tool: `Other`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5cbiAgICB0cmVlQ2hlY2tlZEtleXMgPT4ge3sgdHJlZUNoZWNrZWRLZXlzIH19XG4gIDwvcD5cbiAgPHA+XG4gICAgdHJlZUNoZWNrZWROb2RlcyA9PiB7eyB0cmVlQ2hlY2tlZE5vZGVzfX1cbiAgPC9wPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiaGFuZGxlU2V0RGF0YVwiPlNldFRyZWVDaGVja2VkS2V5czwvZWwtYnV0dG9uPlxuICA8ZWwtdHJlZS12MlxuICAgIHJlZj1cImVsVHJlZVYyUmVmRWxcIlxuICAgIEBjaGVjay1jaGFuZ2U9XCJoYW5kbGVDaGVja2VDaGFuZ2VcIiAgICAgICAgICBcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIDpoZWlnaHQ9XCIyMDhcIlxuICAgIDpwcm9wcz1cInByb3BzXCJcbiAgICBzaG93LWNoZWNrYm94XG4gICAgOmRlZmF1bHQtY2hlY2tlZC1rZXlzPVwiZGVmYXVsdENoZWNrZWRLZXlzXCJcbiAgICA6ZGVmYXVsdC1leHBhbmRlZC1rZXlzPVwiZGVmYXVsdEV4cGFuZGVkS2V5c1wiXG4gIC8+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCB0cmVlQ2hlY2tlZEtleXMgPSByZWYoW10pXG5jb25zdCB0cmVlQ2hlY2tlZE5vZGVzID0gcmVmKFtdKVxuZnVuY3Rpb24gaGFuZGxlQ2hlY2tlQ2hhbmdlKGRhdGEsIGNoZWNrZWQpIHtcbiAgY29uc29sZS5sb2coJ3RvdWNoIGNoZWNrZWQgPT4gJywgY2hlY2tlZClcbiAgLy9jb25zdCBjS2V5cyA9IGVsVHJlZVYyUmVmRWwudmFsdWU/LmdldENoZWNrZWRLZXlzKClcbiAgY29uc3QgY05vZGVzID0gZWxUcmVlVjJSZWZFbC52YWx1ZT8uZ2V0Q2hlY2tlZE5vZGVzKClcbiAgLy8g5Y+q6I635Y+W5a2Q6IqC54K5XG4gIGNvbnN0IGNLZXlzID0gY05vZGVzLmZpbHRlcihpdCA9PiAhaXQuY2hpbGRyZW4pLm1hcChpdCA9PiBpdC5pZClcbiAgdHJlZUNoZWNrZWRLZXlzLnZhbHVlID0gY0tleXNcbiAgdHJlZUNoZWNrZWROb2Rlcy52YWx1ZSA9IGNOb2Rlc1xufSBcblxuZnVuY3Rpb24gaGFuZGxlU2V0RGF0YSgpIHtcbiAgY29uc3QgYXJyID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeSh0cmVlQ2hlY2tlZEtleXMudmFsdWUpKVxuICBhcnIucG9wKClcbiAgY29uc29sZS5sb2coJ2FyciA9PiAnLCBhcnIpXG4gIC8vIOaJi+WKqOiuvue9rumAieS4reeahGtleXNcbiAgZWxUcmVlVjJSZWZFbC52YWx1ZT8uc2V0Q2hlY2tlZEtleXMoYXJyKVxufVxuICBcbmludGVyZmFjZSBUcmVlIHtcbiAgaWQ6IHN0cmluZ1xuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGdldEtleSA9IChwcmVmaXg6IHN0cmluZywgaWQ6IG51bWJlcikgPT4ge1xuICByZXR1cm4gYCR7cHJlZml4fS0ke2lkfWBcbn1cblxuY29uc3QgY3JlYXRlRGF0YSA9IChcbiAgbWF4RGVlcDogbnVtYmVyLFxuICBtYXhDaGlsZHJlbjogbnVtYmVyLFxuICBtaW5Ob2Rlc051bWJlcjogbnVtYmVyLFxuICBkZWVwID0gMSxcbiAga2V5ID0gJ25vZGUnXG4pOiBUcmVlW10gPT4ge1xuICBsZXQgaWQgPSAwXG4gIHJldHVybiBBcnJheS5mcm9tKHsgbGVuZ3RoOiBtaW5Ob2Rlc051bWJlciB9KVxuICAgIC5maWxsKGRlZXApXG4gICAgLm1hcCgoKSA9PiB7XG4gICAgICBjb25zdCBjaGlsZHJlbk51bWJlciA9XG4gICAgICAgIGRlZXAgPT09IG1heERlZXAgPyAwIDogTWF0aC5yb3VuZChNYXRoLnJhbmRvbSgpICogbWF4Q2hpbGRyZW4pXG4gICAgICBjb25zdCBub2RlS2V5ID0gZ2V0S2V5KGtleSwgKytpZClcbiAgICAgIHJldHVybiB7XG4gICAgICAgIGlkOiBub2RlS2V5LFxuICAgICAgICBsYWJlbDogbm9kZUtleSxcbiAgICAgICAgY2hpbGRyZW46IGNoaWxkcmVuTnVtYmVyXG4gICAgICAgICAgPyBjcmVhdGVEYXRhKG1heERlZXAsIG1heENoaWxkcmVuLCBjaGlsZHJlbk51bWJlciwgZGVlcCArIDEsIG5vZGVLZXkpXG4gICAgICAgICAgOiB1bmRlZmluZWQsXG4gICAgICB9XG4gICAgfSlcbn1cblxuY29uc3QgcHJvcHMgPSB7XG4gIHZhbHVlOiAnaWQnLFxuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG59XG5jb25zdCBlbFRyZWVWMlJlZkVsID0gcmVmKG51bGwpXG5jb25zdCBkYXRhID0gY3JlYXRlRGF0YSgyLCA0LCA2KVxuY29uc3QgY2hlY2tlZEtleXM6IHN0cmluZ1tdID0gW11cbmNvbnN0IGV4cGFuZWRLZXlzOiBzdHJpbmdbXSA9IFtdXG5mb3IgKGNvbnN0IGRhdHVtIG9mIGRhdGEpIHtcbiAgY29uc3QgY2hpbGRyZW4gPSBkYXR1bS5jaGlsZHJlblxuICBpZiAoY2hpbGRyZW4pIHtcbiAgICBleHBhbmVkS2V5cy5wdXNoKGRhdHVtLmlkKVxuICAgIGNoZWNrZWRLZXlzLnB1c2goY2hpbGRyZW5bMF0uaWQpXG4gICAgYnJlYWtcbiAgfVxufVxuXG5jb25zdCBkZWZhdWx0Q2hlY2tlZEtleXMgPSByZWYoY2hlY2tlZEtleXMpXG5jb25zdCBkZWZhdWx0RXhwYW5kZWRLZXlzID0gcmVmKGV4cGFuZWRLZXlzKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开复现环境，选中节点，再点击按钮，按钮触发的事件效果为：删除选中的节点(不包含父节点)最后一个，之后通过setCheckedKeys来设置选中的节点。
可以在控制台中看到，仅仅只是在checkbox样式上做了切换并没有触发对外层的checkChange事件

### What is Expected?

在手动设置checkedKeys时，触发checkChange事件

### What is actually happening?

在手动设置checkedKeys时，并没有触发checkChange事件

### Additional comments

_(empty)_

**Comment by litt1e-p** [comment]
use v2.1.11, the checkbox cannot be selected in el-tree-v2 but v2.1.11 works well
