### ISSUE TITLE
[Bug Report] [Component] [form] form 校验规则触发方式为 string[]时提示类型错误.

### ISSUE THREAD

**Issue by Bo-Teng** [element-plus/element-plus#7671]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.2`
- Browser / OS: `chrome/Win10`
- Build Tool: `Vue CLI`

### Related Component

- `el-form`

### Reproduction Link

[Github Repo](https://github.com/34205037/el-bb)

### Steps to reproduce

绑定rules属性,trigger:['blur','change'] 

### What is Expected?

类型提示正常

### What is actually happening?

类型提示报错

### Additional comments

_(empty)_

**Comment by Bo-Teng** [comment]
![image](https://user-images.githubusercontent.com/73982811/168196988-caf2dcf2-d488-4b09-9f54-83f98b3006ca.png)

**Comment by Bo-Teng** [comment]
在另外一个提问中,有老哥说导入 FormRules 类型,但是在2.0.2版本中没有这个类型导出.
![image](https://user-images.githubusercontent.com/73982811/168197212-9d9362ca-ba75-4eae-863d-aaf623a48502.png)
回答地址:https://github.com/element-plus/element-plus/issues/6791#issuecomment-1107529003

**Comment by Bo-Teng** [comment]
在Elform这类型声明中rule属性的trigger只能为string,有老哥知道改怎么支持string[] | string 吗?

![image](https://user-images.githubusercontent.com/73982811/168197901-ddd64b71-4459-4f5d-93ee-5b5d9c1b462f.png)

**Comment by yxw007** [comment]
![image](https://user-images.githubusercontent.com/9338717/168270582-aac15a2a-e888-4d79-b8be-7ed493846fe8.png)

碰到问题先从官网找答案，找不到问题看源码，最后搞不定再问。
参考官网的方式写就ok了

![image](https://user-images.githubusercontent.com/9338717/168270926-12a151e1-18fd-47fd-9ebf-711808ccd26a.png)

**Comment by Bo-Teng** [comment]
@yxw007 老哥我可能没说清楚,我是官网中会其他问题中有找到这种解决方式,但是我导入这类型会提示没有导出.
![image](https://user-images.githubusercontent.com/73982811/168529868-f3076535-adcc-47ed-8cc5-4b8b22791f06.png)

**Comment by Bo-Teng** [comment]
@yxw007 会提示类型不匹配是 当trigger为一个数组的时候.
![image](https://user-images.githubusercontent.com/73982811/168529962-b028ed9c-ebd4-4137-948d-077c4968af5a.png)

**Comment by Bo-Teng** [comment]
原因是el-form的rules类型 trigger类型限制成了string.
https://github.com/element-plus/element-plus/issues/7671#issuecomment-1125589069

**Comment by Bo-Teng** [comment]
我并没有说遇到问题就直接来问题,而不是自己去找原因并想去解决

**Comment by HeftyKoo** [comment]
> 在另外一个提问中,有老哥说导入 FormRules 类型,但是在2.0.2版本中没有这个类型导出. ![image](https://user-images.githubusercontent.com/73982811/168197212-9d9362ca-ba75-4eae-863d-aaf623a48502.png) 回答地址:[#6791 (comment)](https://github.com/element-plus/element-plus/issues/6791#issuecomment-1107529003)

这个问题在 https://github.com/element-plus/element-plus/pull/5975/commits 已经解决。

这个pr在 2.0.5 版本中已经合并 https://github.com/element-plus/element-plus/pull/6444#issuecomment-1059945263

所以升级到2.0.5版本以上，你的问题就可以解决了
