### ISSUE TITLE
[Bug Report] [Component] [tabs] el-tabs 点击tab时候滚动异常

### ISSUE THREAD

**Issue by Archmage83** [element-plus/element-plus#7672]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `chrome 101.0.4951.64`
- Build Tool: `Vue CLI`

### Related Component

- `el-tabs`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/embed/element-plus-spa-forked-beq2c8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

进入页面，光标在0处。当点击最右侧的翻页按钮，移动到后面几页，比如60，点击60的时候，el-tabs会滚动到0的位置，有时候会滚动到9的位置，不确定，但是无法停留在60的位置。在chrome上必现，但是在codesandbox上未发现。
是否能够实现监听高亮的tab让他始终在屏幕内或者屏幕中间位置

### What is Expected?

点击tab时候不要滚动到别的位置

### What is actually happening?

点击tab时候会滚动到别的位置，当tab非常多的时候，有翻页情况下，点击后面几页或者前面几页的tab，会造成滚动混乱

### Additional comments

_(empty)_

**Comment by stylusscoped** [comment]
tab内容较多时，tab一行无法展示的时候左右两边会出现两个按钮，你会遇到点击向左但是左侧的tab无法完全展示的情况吗？

**Comment by Archmage83** [comment]
这个没有遇到，就是遇到滚动异常的情况

**Comment by chenxch** [comment]
同样的问题 #7682

**Comment by Archmage83** [comment]
> CodeSandbox

https://codepen.io/archmage83/pen/jOZyqbp

一开始光标在0处，请点击右侧>号翻到90，点击90，又会滑动到0
