### ISSUE TITLE
[Bug Report] [Component] [select] select多选时，并设置teleported=false时，点非选项时自动隐藏下拉框

### ISSUE THREAD

**Issue by aliang888** [element-plus/element-plus#7673]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgbXVsdGlwbGVcbiAgICAgICAgICAgICA6dGVsZXBvcnRlZD1cImZhbHNlXCI+XG4gICAgPGVsLW9wdGlvbi1ncm91cFxuICAgICAgdi1mb3I9XCJncm91cCBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJncm91cC5sYWJlbFwiXG4gICAgICA6bGFiZWw9XCJncm91cC5sYWJlbFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gZ3JvdXAub3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLW9wdGlvbi1ncm91cD5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICBsYWJlbDogJ+eCueWHu+aIkeS4jeW6lOivpemakOiXjycsXG4gICAgb3B0aW9uczogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ1NoYW5naGFpJyxcbiAgICAgICAgbGFiZWw6ICdTaGFuZ2hhaScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ0JlaWppbmcnLFxuICAgICAgICBsYWJlbDogJ0JlaWppbmcnLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdDbGljayBtZSBoaWRlPycsXG4gICAgb3B0aW9uczogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ0NoZW5nZHUnLFxuICAgICAgICBsYWJlbDogJ0NoZW5nZHUnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdTaGVuemhlbicsXG4gICAgICAgIGxhYmVsOiAnU2hlbnpoZW4nLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdHdWFuZ3pob3UnLFxuICAgICAgICBsYWJlbDogJ0d1YW5nemhvdScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ0RhbGlhbicsXG4gICAgICAgIGxhYmVsOiAnRGFsaWFuJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-select v-model="value" placeholder="Select" multiple
             :teleported="false">
    <el-option-group
      v-for="group in options"
      :key="group.label"
      :label="group.label"
    >
      <el-option
        v-for="item in group.options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      />
    </el-option-group>
  </el-select>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const value = ref('')
const options = [
  {
    label: '点击我不应该隐藏',
    options: [
      {
        value: 'Shanghai',
        label: 'Shanghai',
      },
      {
        value: 'Beijing',
        label: 'Beijing',
      },
    ],
  },
  {
    label: 'Click me hide?',
    options: [
      {
        value: 'Chengdu',
        label: 'Chengdu',
      },
      {
        value: 'Shenzhen',
        label: 'Shenzhen',
      },
      {
        value: 'Guangzhou',
        label: 'Guangzhou',
      },
      {
        value: 'Dalian',
        label: 'Dalian',
      },
    ],
  },
]
</script>

```

### What is Expected?

点击Popular cities,City name，分隔线（非option项）时不应该隐藏下拉框

### What is actually happening?

隐藏掉了

### Additional comments

_(empty)_

![select](https://user-images.githubusercontent.com/19453262/168202786-68b7ab57-2422-4315-a5b1-82ae9c32cb7f.jpg)

**Comment by tolking** [comment]
看起来该问题在最新版本中已经不存在

你可以更新依赖
