### ISSUE TITLE
[Bug Report] [All] Element 升级后，原定制化的主题使用不了，提示服务不可用

### ISSUE THREAD

**Issue by CaibUtouwAng** [element-plus/element-plus#7681]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/)

### Steps to reproduce

https://element.eleme.cn/#/zh-CN/theme
我的主题无法编辑

### What is Expected?

期望主题内容正常使用

### What is actually happening?

实际报错提示“服务不可用”

### Additional comments

_(empty)_

**Comment by huJQing** [comment]
element2.0的主题定制现在报503错误，想问下现在element是完全放弃2.0版本了吗？小半个月了还是没有人解决

**Comment by chenxch** [comment]
Maybe feedback to [element-ui](https://github.com/ElemeFE/element/issues) would be better

**Comment by 0song** [comment]
please raise an issue on https://github.com/ElemeFE/element/issues
