### ISSUE TITLE
[Bug Report] [Component] [tabs] el-tabs点击事件中v-model绑定的值更新不正确

### ISSUE THREAD

**Issue by stylusscoped** [element-plus/element-plus#7682]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `Edge 101.0.1210.39`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCIgQHRhYi1jbGljaz1cImhhbmRsZUNsaWNrXCI+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVXNlclwiIG5hbWU9XCJmaXJzdFwiPlVzZXI8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIkNvbmZpZ1wiIG5hbWU9XCJzZWNvbmRcIj5Db25maWc8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlJvbGVcIiBuYW1lPVwidGhpcmRcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCIgbmFtZT1cImZvdXJ0aFwiPlRhc2s8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgVGFic1BhbmVDb250ZXh0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBhY3RpdmVOYW1lID0gcmVmKCdmaXJzdCcpXG5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKHRhYjogVGFic1BhbmVDb250ZXh0LCBldmVudDogRXZlbnQpID0+IHtcbiAgY29uc29sZS5sb2codGFiLCBldmVudClcbiAgYWxlcnQoYWN0aXZlTmFtZS52YWx1ZSlcbn1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击tab

### What is Expected?

activeName及时更新

### What is actually happening?

activeName为上一次tab的值

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
切换流程是先点击再切换，tab-click是点击时候触发的，如果你需要获取切换后的activeName，可以通过tab-change

**Comment by chenxch** [comment]
同样的问题 #7662

**Comment by stylusscoped** [comment]
但是在2.1.9还是click的时候就能获取到正确的值了

**Comment by QPvicus** [comment]
这主要是更新值是异步的。。。

**Comment by TLovers** [comment]
呜呜呜 生产问题 开发环境正常 生产挂了～～～

**Comment by chenxch** [comment]
> 呜呜呜 生产问题 开发环境正常 生产挂了～～～

问题已经修复，需要等下个版本发布0 0

**Comment by JerryWang24** [comment]
没升级之前确实获取值没问题！确实主要还是使用的方法问题~
没事，这个生成环境bug我背了！o(╥﹏╥)o

**Comment by HeftyKoo** [comment]
see: https://github.com/element-plus/element-plus/issues/10519#issuecomment-1307386732
