### ISSUE TITLE
[Bug Report] [Component] [select-v2] select-v2 的 filter-method 不支持自定义筛选

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#7686]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICBcdDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVyTWV0aG9kXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgIG11bHRpcGxlXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzb3VyY2VPcHRpb25zID0gW3tcbiAgbGFiZWw6ICfooajljZXlt6XlhbcnLFxuICB2YWx1ZTogJ+ihqOWNleW3peWFtycsXG4gIGxldHRlcjogJ2JpYW9kYW5nb25nanUnXG59LCB7XG4gIGxhYmVsOiAn6KGo5qC85byP6KGo5Y2VJyxcbiAgdmFsdWU6ICfooajmoLzlvI/ooajljZUnLFxuICBsZXR0ZXI6ICdiaWFvZ2VzaGliaWFvZGFuJ1xufSwge1xuICBsYWJlbDogJ+WKqOaAgeihqOWNlScsXG4gIHZhbHVlOiAn5Yqo5oCB6KGo5Y2VJyxcbiAgbGV0dGVyOiAnZG9uZ3RhaWJpYW9kYW4nXG59XVxuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoc291cmNlT3B0aW9ucylcblxuY29uc3QgZmlsdGVyTWV0aG9kID0gKGtleXdvcmQ6IHN0cmluZykgPT4ge1xuICBpZiAoIWtleXdvcmQpIHtcbiAgICBvcHRpb25zLnZhbHVlID0gWy4uLnNvdXJjZU9wdGlvbnNdXG4gICAgcmV0dXJuXG4gIH1cbiAgXG4gIG9wdGlvbnMudmFsdWUgPSBzb3VyY2VPcHRpb25zLmZpbHRlcihpdGVtID0+IHtcbiAgICByZXR1cm4gaXRlbS5sYWJlbC5pbmNsdWRlcyhrZXl3b3JkKSB8fCBpdGVtLmxldHRlci5pbmNsdWRlcyhrZXl3b3JkKVxuICB9KVxufVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.输入'表单'，可以正常筛选
2.输入'biaodan'，不能筛选

### What is Expected?

filter-method支持自定义筛选

### What is actually happening?

filter-method不支持自定义筛选

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
目前没有filter-method这个API哦，你可以通过如下方式去实现自定义筛选
```html
 <el-select-v2
    v-model="value"
    filterable
    remote
    :remote-method="filterMethod"
    :options="options"
    placeholder="Please select"
    style="width: 240px"
    multiple
  />
```

**Comment by JackieCheung** [comment]
> 目前没有filter-method这个API哦，你可以通过如下方式去实现自定义筛选
> 
> ```
>  <el-select-v2
>     v-model="value"
>     filterable
>     remote
>     :remote-method="filterMethod"
>     :options="options"
>     placeholder="Please select"
>     style="width: 240px"
>     multiple
>   />
> ```

好吧 我看到TS类型定义有`filterMethod` 以为有这个api的实现😅

**Comment by JackieCheung** [comment]
> 目前没有filter-method这个API哦，你可以通过如下方式去实现自定义筛选
> 
> ```
>  <el-select-v2
>     v-model="value"
>     filterable
>     remote
>     :remote-method="filterMethod"
>     :options="options"
>     placeholder="Please select"
>     style="width: 240px"
>     multiple
>   />
> ```

源码是有`filter-method` 的实现的
https://github.com/element-plus/element-plus/blob/353b56e2c812a27ce4614073c53301900d0b8aba/packages/components/select-v2/src/useSelect.ts#L310-L324

**Comment by cuihu** [comment]
filter_method只能处理总数据吧，内部的query目前看是写死的，不太理解这种做法
https://github.com/element-plus/element-plus/blob/353b56e2c812a27ce4614073c53301900d0b8aba/packages/components/select-v2/src/useSelect.ts#L155

**Comment by kooriookami** [comment]
Fixed
