### ISSUE TITLE
Form label-width=“auto” will not change automatically

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#770]
When the form set `label-width=“auto”`, and the form-item is dynamic, the label width will not be correct.

**Comment by kooriookami** [comment]
```html
<template>
    <div class="home">
        <el-tabs type="card">
            <el-tab-pane label="测试" name="测试">
                <el-form ref="dhcpFixedForm" label-width="auto" size="small">
                    <el-form-item label="测试">
                        <el-input v-model="input" placeholder="placeholder"></el-input>
                    </el-form-item>
                </el-form>
            </el-tab-pane>
        </el-tabs>
    </div>
</template>

<script>
    export default {
        name: 'Home',
        data() {
            return {
                input:''
            };
        }
    };
</script>
```
You can click the tab, and see the effect.
![image](https://user-images.githubusercontent.com/38392315/100834307-a1e09e80-34a6-11eb-9530-6e13dfdfa42a.png)

**Comment by JeremyWuuuuu** [comment]
You interested in fix this issue? I think this might related to the css issue you've mentioned before.

**Comment by kooriookami** [comment]
> You interested in fix this issue? I think this might related to the css issue you've mentioned before.

It may not be the css problem, when remove `el-tabs` and `el-tab-pane`, the style is correct.

**Comment by JeremyWuuuuu** [comment]
So it must be impact from the ancestors style.

**Comment by kooriookami** [comment]
> So it must be impact from the ancestors style.

```html
<template>
    <div class="home">
        <el-tabs type="card">
            <el-tab-pane label="测试" name="测试">
                <el-form label-width="auto" size="small" :key="key">
                    <el-form-item label="测试">
                        <el-input v-model="input" placeholder="placeholder"></el-input>
                    </el-form-item>
                </el-form>
            </el-tab-pane>
        </el-tabs>
    </div>
</template>

<script>
    export default {
        name: 'Home',
        data() {
            return {
                input: '',
                key: 0
            };
        },
        mounted() {
            setTimeout(() => {
                this.key++;
            },1000);
        }
    };
</script>
```
When the key of `form` changed, the style is correct. I think it's the computed width of lebal error.

**Comment by JeremyWuuuuu** [comment]
From what I am getting here, it's related to a computational rendering issue, whenever the `key` changes, `el-form` gets re-rendered then the width of the label will be calculated correctly. So it has to have something todo with the `calculation` part of the label width, if you are willing to fix the bug, then I will assign this to you

**Comment by kooriookami** [comment]
> From what I am getting here, it's related to a computational rendering issue, whenever the `key` changes, `el-form` gets re-rendered then the width of the label will be calculated correctly. So it has to have something todo with the `calculation` part of the label width, if you are willing to fix the bug, then I will assign this to you

I have no good way to solve this problem, regret.
