### ISSUE TITLE
Dialog show-close is invalid

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#771]
Dialog show-close is invalid, when set `:show-close="false"`, still shows.

**Comment by JeremyWuuuuu** [comment]
Thank you for being so actively giving us feedback, I personally am full of gratitude of that. This should be a bug that's caused by the previous change against dialog, and it will be fixed tonight. Thanks!

**Comment by Ther-su** [comment]
Sorry, I did not see your self-assign before commited.
