### ISSUE TITLE
[Bug Report] [Component] [table] Table only display last column when use CDN.

### ISSUE THREAD

**Issue by qin-nz** [element-plus/element-plus#7711]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/qin-nz/pen/XWZNLVg)

### Steps to reproduce
0. Create an empty html file
1. include vue & element-plus
```html
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/element-plus@2.2.0/dist/index.css" />
  <script src="https://cdn.jsdelivr.net/npm/vue@3.2.33/dist/vue.global.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/element-plus@2.2.0/dist/index.full.js"></script>
```
2. copy exapmle from element-plus.org
```html
    <el-table :data="tableData">
      <el-table-column prop="date" label="Date" width="180" />
      <el-table-column prop="name" label="Name" width="180" />
      <el-table-column prop="address" label="Address" />
    </el-table>
``` 
3. mount App with data.
```javascript
    const HelloVueApp = {
      data() {
        return {
          message: 'Hello Vue!!',
          tableData: [
            { date: '2016-05-03', name: 'Tom', address: 'No. 1, Grove St, Los Angeles', },
            { date: '2016-05-02', name: 'Tom', address: 'No. 2, Grove St, Los Angeles', },
            { date: '2016-05-04', name: 'Tom', address: 'No. 3, Grove St, Los Angeles', },
            { date: '2016-05-01', name: 'Tom', address: 'No. 4, Grove St, Los Angeles', },
          ]
        }
      }
    }

    const app = Vue.createApp(HelloVueApp);
    app.use(ElementPlus);
    app.mount('#app')
```

### What is Expected?

Show correct table.  I want to see 3 columns.
![image](https://user-images.githubusercontent.com/6998071/168474084-d5f29304-5c49-4988-8a43-8e33748e08c3.png)

### What is actually happening?

I can only see the last column (prop="address").
![image](https://user-images.githubusercontent.com/6998071/168473610-b27e4f10-38da-4175-b6b6-086d88fa9a7d.png)

**Comment by chenxch** [comment]
[look here](https://element-plus.org/en-US/component/table.html#faq) ,please use close tag

**Comment by qin-nz** [comment]
@chenxch Thanks a lot.
Can you fix the demo in offical documents?  I just copy that. 

![image](https://user-images.githubusercontent.com/6998071/168476429-fab6091e-f171-4871-9f10-86cc2d25b7e0.png)

Ref: https://github.com/element-plus/element-plus/issues/5046 https://github.com/element-plus/element-plus/issues/5862 https://github.com/element-plus/element-plus/issues/6919

**Comment by chenxch** [comment]
This has also been discussed before. The document is still aimed at engineering development. Opening and closing tags is a basic application knowledge of Vue, so it is explained in the form of FAQ.

**Comment by qin-nz** [comment]
@chenxch Thanks.
Vue 3 style-guide said this.  [English](https://vuejs.org/style-guide/rules-strongly-recommended.html#self-closing-components) [中文](https://v3.cn.vuejs.org/style-guide/#%E8%87%AA%E9%97%AD%E5%90%88%E7%BB%84%E4%BB%B6%E5%BC%BA%E7%83%88%E6%8E%A8%E8%8D%90)
