### ISSUE TITLE
[Bug Report] [Docs] Search function on element-plus website is not working

### ISSUE THREAD

**Issue by HuakunShen** [element-plus/element-plus#7713]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Version 101.0.4951.64 (Official Build) (arm64) / Mac OS`
- Build Tool: `Other`

### Related Component

- `N/A`

### Reproduction Link

[Docs](https://element-plus.org/)

### Steps to reproduce

Go to https://element-plus.org/ and search for any element

### What is Expected?

Should direct me to the documentation if I click on search result

### What is actually happening?

No page redirection

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
fixed
