### ISSUE TITLE
[Bug Report] [Component] [popover, select] el-popover和el-select一起使用时popover会自动关闭

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#7719]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `版本 99.0.4844.84（正式版本）`
- Build Tool: `Vue CLI`

### Related Component

- `el-popover`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cInRvcC1zdGFydFwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiaG92ZXJcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuXG4gID5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiBtdWx0aXBsZT5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmRpc2FibGVkPVwiaXRlbS5kaXNhYmxlZFwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPuWNlemAiS/lpJrpgInpg73kuIDmoLfkuI3lpb3kvb88L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG5cblxuXG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gICAgZGlzYWJsZWQ6IGZhbHNlLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

el-popover和el-select一起使用时popover会自动关闭

### What is Expected?

popover不自动关闭

### What is actually happening?

popover会在select选择后自动关闭

### Additional comments

_(empty)_

**Comment by PeyFon** [comment]
el-cascader也一样

**Comment by ll60** [comment]
我也发现，很多组件嵌套使用有问题，el-tooltip里嵌套el-popconfirm, el-tooltip功能会失效。
