### ISSUE TITLE
[Bug Report] [Component] [time-picker] 手速够快，打开弹框，快速点击OK，会弹出多次

### ISSUE THREAD

**Issue by Edric-Li** [element-plus/element-plus#7728]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.11`
- Browser / OS: `Edge Version 99.0.1150.30`
- Build Tool: `CDN`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1iYXNpY1wiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICA6ZGlzYWJsZWQtaG91cnM9XCJkaXNhYmxlZEhvdXJzXCJcbiAgICAgIDpkaXNhYmxlZC1taW51dGVzPVwiZGlzYWJsZWRNaW51dGVzXCJcbiAgICAgIDpkaXNhYmxlZC1zZWNvbmRzPVwiZGlzYWJsZWRTZWNvbmRzXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQXJiaXRyYXJ5IHRpbWVcIlxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKG5ldyBEYXRlKDIwMTYsIDksIDEwLCAxOCwgMzApKVxuXG5jb25zdCBtYWtlUmFuZ2UgPSAoc3RhcnQ6IG51bWJlciwgZW5kOiBudW1iZXIpID0+IHtcbiAgY29uc3QgcmVzdWx0OiBudW1iZXJbXSA9IFtdXG4gIGZvciAobGV0IGkgPSBzdGFydDsgaSA8PSBlbmQ7IGkrKykge1xuICAgIHJlc3VsdC5wdXNoKGkpXG4gIH1cbiAgcmV0dXJuIHJlc3VsdFxufVxuY29uc3QgZGlzYWJsZWRIb3VycyA9ICgpID0+IHtcbiAgcmV0dXJuIG1ha2VSYW5nZSgwLCAxNikuY29uY2F0KG1ha2VSYW5nZSgxOSwgMjMpKVxufVxuY29uc3QgZGlzYWJsZWRNaW51dGVzID0gKGhvdXI6IG51bWJlcikgPT4ge1xuICBpZiAoaG91ciA9PT0gMTcpIHtcbiAgICByZXR1cm4gbWFrZVJhbmdlKDAsIDI5KVxuICB9XG4gIGlmIChob3VyID09PSAxOCkge1xuICAgIHJldHVybiBtYWtlUmFuZ2UoMzEsIDU5KVxuICB9XG59XG5jb25zdCBkaXNhYmxlZFNlY29uZHMgPSAoaG91cjogbnVtYmVyLCBtaW51dGU6IG51bWJlcikgPT4ge1xuICBpZiAoaG91ciA9PT0gMTggJiYgbWludXRlID09PSAzMCkge1xuICAgIHJldHVybiBtYWtlUmFuZ2UoMSwgNTkpXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZXhhbXBsZS1iYXNpYyAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW4tdG9wOiAxMDAwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

 打开timepicker 快速点击ok 会弹出多次

### What is Expected?

 弹出一次

### What is actually happening?

 弹出多次

### Additional comments

首先得保证在上方弹出

![image](https://user-images.githubusercontent.com/50992790/168705639-23f66f47-b058-4ad5-8106-084de1e608eb.png)

![2](https://user-images.githubusercontent.com/50992790/168705827-6a1ac962-bf38-4df5-89d5-3faad4743d1c.gif)

**Comment by lt2396261331** [comment]
确实恶心 我也遇到了
