### ISSUE TITLE
[Bug Report] [Component] [select] 使用自定义搜索修改options后, 使用键盘上下选择混乱

### ISSUE THREAD

**Issue by cn-troy** [element-plus/element-plus#7737]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Edge`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6ZmlsdGVyLW1ldGhvZD1cInNlYXJjaE9wdGlvbnNcIiBAY2hhbmdlPSdyZXNldE9wdGlvbnMnPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbi8vIOWOn+Wni+aVsOaNrlxuY29uc3Qgb3JpZ2luT3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMTEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMTEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xMicsXG4gICAgbGFiZWw6ICdPcHRpb24xMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEzJyxcbiAgICBsYWJlbDogJ09wdGlvbjEzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMTQnLFxuICAgIGxhYmVsOiAnT3B0aW9uMTQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yMCcsXG4gICAgbGFiZWw6ICdPcHRpb24yMCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjIxJyxcbiAgICBsYWJlbDogJ09wdGlvbjIxJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMjMnLFxuICB9LFxuXVxuXG4vL+aQnOe0ouWQjuaYvuekuuaVsOaNrlxuY29uc3Qgb3B0aW9ucyA9IHJlZihvcmlnaW5PcHRpb25zKTtcblxuLy/mkJzntKJcbmNvbnN0IHNlYXJjaE9wdGlvbnMgPSAocXVlcnk6c3RyaW5nKSA9PiB7XG4gIG9wdGlvbnMudmFsdWUgPSBvcmlnaW5PcHRpb25zLmZpbHRlcihrPT5rLmxhYmVsLmluZGV4T2YocXVlcnkpID49IDApO1xufVxuXG4vL+avj+asoemAieaLqeWQjumDvemcgOimgeaYvuekuuWFqOmDqOaVsOaNrlxuY29uc3QgcmVzZXRPcHRpb25zID0gKCk9PntcbiAgb3B0aW9ucy52YWx1ZSA9IG9yaWdpbk9wdGlvbnM7XG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

0: 激活Select
1: 输入 12 进行搜索.
2: 选择 "Option12"
3: 再次激活Select
4: 按键盘上或者下

### What is Expected?

按上应该向上逐个选择
按下应该向下逐个选择

### What is actually happening?

按上或者下, 有些是逐个选择, 有些是乱跳.

### Additional comments

_(empty)_

**Comment by cn-troy** [comment]
@emojiiii 麻烦标记一下...我不管怎么控制我的数据都不行...
我看源码好像是因为 useSelect 中 optionsArray computed 返回的数据就乱了...
我尝试硬编码强制排序后,就正常了.....
![image](https://user-images.githubusercontent.com/4318293/169641512-8981bc16-873a-4de4-a163-36f029d1e531.png)

遗憾的是,我不知道怎么处理这个select的错误.

**Comment by Delevin888** [comment]
哈，我也遇到这个问题。

**Comment by cn-troy** [comment]
我好像找到问题了... @Delevin888 @emojiiii 
vue在处理我们的v-for时,执行setup顺序是反向的...可能因为vue内部的机制..我还得去问问vue那边..

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIiA6ZmlsdGVyLW1ldGhvZD1cInNlYXJjaE9wdGlvbnNcIiBAY2hhbmdlPSdyZXNldE9wdGlvbnMnPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbi8vIOWOn+Wni+aVsOaNrlxuY29uc3Qgb3JpZ2luT3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMTEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMTEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xMicsXG4gICAgbGFiZWw6ICdPcHRpb24xMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEzJyxcbiAgICBsYWJlbDogJ09wdGlvbjEzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMTQnLFxuICAgIGxhYmVsOiAnT3B0aW9uMTQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yMCcsXG4gICAgbGFiZWw6ICdPcHRpb24yMCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjIxJyxcbiAgICBsYWJlbDogJ09wdGlvbjIxJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMjMnLFxuICB9LFxuXVxuXG4vL+aQnOe0ouWQjuaYvuekuuaVsOaNrlxuY29uc3Qgb3B0aW9ucyA9IHJlZihvcmlnaW5PcHRpb25zKTtcblxuLy/mkJzntKJcbmNvbnN0IHNlYXJjaE9wdGlvbnMgPSAocXVlcnk6c3RyaW5nKSA9PiB7XG4gIG9wdGlvbnMudmFsdWUgPSBvcmlnaW5PcHRpb25zLmZpbHRlcihrPT5rLmxhYmVsLmluZGV4T2YocXVlcnkpID49IDApO1xufVxuXG4vL+avj+asoemAieaLqeWQjumDvemcgOimgeaYvuekuuWFqOmDqOaVsOaNrlxuY29uc3QgcmVzZXRPcHRpb25zID0gKCk9PntcbiAgb3B0aW9ucy52YWx1ZSA9IG9yaWdpbk9wdGlvbnM7XG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aW5wdXQgdi1tb2RlbD1cImlucHV0VmFsdWVcIiBAaW5wdXQ9XCJzZWFyY2hPcHRpb25zXCIgcGxhY2Vob2xkZXI9XCLovpPlhaXmkJzntKJcIiAvPlxuICA8YnV0dG9uIEBjbGljaz1cInJlc2V0T3B0aW9uc1wiPumHjee9rm9wdGlvbnM8L2J1dHRvbj5cbiAgPGNvbXAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbVwiIDpsYWJlbD1cIml0ZW1cIj5cbiAgICB7eyBpdGVtIH19XG4gIDwvY29tcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgY29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpbnB1dFZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcmlnaW5PcHRpb25zID0gWydvcHRpb24tMScsICdvcHRpb24tMicsICdvcHRpb24tMycsICdvcHRpb24tNCcsICdvcHRpb24tNScsICdvcHRpb24tNiddXG5jb25zdCBvcHRpb25zID0gcmVmKFsuLi5vcmlnaW5PcHRpb25zXSlcblxuY29uc3Qgc2VhcmNoT3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zLmZpbHRlcigoaykgPT4gay5pbmNsdWRlcyhpbnB1dFZhbHVlLnZhbHVlKSldXG59XG5cbmNvbnN0IHJlc2V0T3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zXVxuICBpbnB1dFZhbHVlLnZhbHVlID0gJydcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj57eyBsYWJlbCB9fTwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgbGFiZWw6IHtcbiAgICB0eXBlOiBTdHJpbmcsXG4gICAgZGVmYXVsdDogJycsXG4gIH0sXG59KVxuXG5jb25zb2xlLmxvZygnY29tcCBzZXR1cCcsIHByb3BzLmxhYmVsKVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319

**Comment by wzrove** [comment]
> 我好像找到问题了... @Delevin888 @emojiiii vue在处理我们的v-for时,执行setup顺序是反向的...可能因为vue内部的机制..我还得去问问vue那边.. [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aW5wdXQgdi1tb2RlbD1cImlucHV0VmFsdWVcIiBAaW5wdXQ9XCJzZWFyY2hPcHRpb25zXCIgcGxhY2Vob2xkZXI9XCLovpPlhaXmkJzntKJcIiAvPlxuICA8YnV0dG9uIEBjbGljaz1cInJlc2V0T3B0aW9uc1wiPumHjee9rm9wdGlvbnM8L2J1dHRvbj5cbiAgPGNvbXAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbVwiIDpsYWJlbD1cIml0ZW1cIj5cbiAgICB7eyBpdGVtIH19XG4gIDwvY29tcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgY29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpbnB1dFZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcmlnaW5PcHRpb25zID0gWydvcHRpb24tMScsICdvcHRpb24tMicsICdvcHRpb24tMycsICdvcHRpb24tNCcsICdvcHRpb24tNScsICdvcHRpb24tNiddXG5jb25zdCBvcHRpb25zID0gcmVmKFsuLi5vcmlnaW5PcHRpb25zXSlcblxuY29uc3Qgc2VhcmNoT3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zLmZpbHRlcigoaykgPT4gay5pbmNsdWRlcyhpbnB1dFZhbHVlLnZhbHVlKSldXG59XG5cbmNvbnN0IHJlc2V0T3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zXVxuICBpbnB1dFZhbHVlLnZhbHVlID0gJydcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj57eyBsYWJlbCB9fTwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgbGFiZWw6IHtcbiAgICB0eXBlOiBTdHJpbmcsXG4gICAgZGVmYXVsdDogJycsXG4gIH0sXG59KVxuXG5jb25zb2xlLmxvZygnY29tcCBzZXR1cCcsIHByb3BzLmxhYmVsKVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319)

有issues的链接嘛，想围观一下

**Comment by Delevin888** [comment]
> > 我好像找到问题了... @Delevin888 @emojiiii vue在处理我们的v-for时,执行setup顺序是反向的...可能因为vue内部的机制..我还得去问问vue那边.. [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aW5wdXQgdi1tb2RlbD1cImlucHV0VmFsdWVcIiBAaW5wdXQ9XCJzZWFyY2hPcHRpb25zXCIgcGxhY2Vob2xkZXI9XCLovpPlhaXmkJzntKJcIiAvPlxuICA8YnV0dG9uIEBjbGljaz1cInJlc2V0T3B0aW9uc1wiPumHjee9rm9wdGlvbnM8L2J1dHRvbj5cbiAgPGNvbXAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbVwiIDpsYWJlbD1cIml0ZW1cIj5cbiAgICB7eyBpdGVtIH19XG4gIDwvY29tcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgY29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpbnB1dFZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcmlnaW5PcHRpb25zID0gWydvcHRpb24tMScsICdvcHRpb24tMicsICdvcHRpb24tMycsICdvcHRpb24tNCcsICdvcHRpb24tNScsICdvcHRpb24tNiddXG5jb25zdCBvcHRpb25zID0gcmVmKFsuLi5vcmlnaW5PcHRpb25zXSlcblxuY29uc3Qgc2VhcmNoT3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zLmZpbHRlcigoaykgPT4gay5pbmNsdWRlcyhpbnB1dFZhbHVlLnZhbHVlKSldXG59XG5cbmNvbnN0IHJlc2V0T3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zXVxuICBpbnB1dFZhbHVlLnZhbHVlID0gJydcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj57eyBsYWJlbCB9fTwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgbGFiZWw6IHtcbiAgICB0eXBlOiBTdHJpbmcsXG4gICAgZGVmYXVsdDogJycsXG4gIH0sXG59KVxuXG5jb25zb2xlLmxvZygnY29tcCBzZXR1cCcsIHByb3BzLmxhYmVsKVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319)
> 
> 有issues的链接嘛，想围观一下

我也想围观

**Comment by wzrove** [comment]
> 我好像找到问题了... @Delevin888 @emojiiii vue在处理我们的v-for时,执行setup顺序是反向的...可能因为vue内部的机制..我还得去问问vue那边.. [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aW5wdXQgdi1tb2RlbD1cImlucHV0VmFsdWVcIiBAaW5wdXQ9XCJzZWFyY2hPcHRpb25zXCIgcGxhY2Vob2xkZXI9XCLovpPlhaXmkJzntKJcIiAvPlxuICA8YnV0dG9uIEBjbGljaz1cInJlc2V0T3B0aW9uc1wiPumHjee9rm9wdGlvbnM8L2J1dHRvbj5cbiAgPGNvbXAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbVwiIDpsYWJlbD1cIml0ZW1cIj5cbiAgICB7eyBpdGVtIH19XG4gIDwvY29tcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgY29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpbnB1dFZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcmlnaW5PcHRpb25zID0gWydvcHRpb24tMScsICdvcHRpb24tMicsICdvcHRpb24tMycsICdvcHRpb24tNCcsICdvcHRpb24tNScsICdvcHRpb24tNiddXG5jb25zdCBvcHRpb25zID0gcmVmKFsuLi5vcmlnaW5PcHRpb25zXSlcblxuY29uc3Qgc2VhcmNoT3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zLmZpbHRlcigoaykgPT4gay5pbmNsdWRlcyhpbnB1dFZhbHVlLnZhbHVlKSldXG59XG5cbmNvbnN0IHJlc2V0T3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zXVxuICBpbnB1dFZhbHVlLnZhbHVlID0gJydcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj57eyBsYWJlbCB9fTwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgbGFiZWw6IHtcbiAgICB0eXBlOiBTdHJpbmcsXG4gICAgZGVmYXVsdDogJycsXG4gIH0sXG59KVxuXG5jb25zb2xlLmxvZygnY29tcCBzZXR1cCcsIHByb3BzLmxhYmVsKVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319)

selest 内部维护了一个map，当option 创建或者销毁的时候回去 set,delet（更新的时候去变动map的位置），每次筛选完要保证key要变（由于v-for setup的原因 map倒序的哈哈哈），

**Comment by Delevin888** [comment]
> > 我好像找到问题了... @Delevin888 @emojiiii vue在处理我们的v-for时,执行setup顺序是反向的...可能因为vue内部的机制..我还得去问问vue那边.. [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aW5wdXQgdi1tb2RlbD1cImlucHV0VmFsdWVcIiBAaW5wdXQ9XCJzZWFyY2hPcHRpb25zXCIgcGxhY2Vob2xkZXI9XCLovpPlhaXmkJzntKJcIiAvPlxuICA8YnV0dG9uIEBjbGljaz1cInJlc2V0T3B0aW9uc1wiPumHjee9rm9wdGlvbnM8L2J1dHRvbj5cbiAgPGNvbXAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbVwiIDpsYWJlbD1cIml0ZW1cIj5cbiAgICB7eyBpdGVtIH19XG4gIDwvY29tcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgY29tcCBmcm9tICcuL0NvbXAudnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBpbnB1dFZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcmlnaW5PcHRpb25zID0gWydvcHRpb24tMScsICdvcHRpb24tMicsICdvcHRpb24tMycsICdvcHRpb24tNCcsICdvcHRpb24tNScsICdvcHRpb24tNiddXG5jb25zdCBvcHRpb25zID0gcmVmKFsuLi5vcmlnaW5PcHRpb25zXSlcblxuY29uc3Qgc2VhcmNoT3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zLmZpbHRlcigoaykgPT4gay5pbmNsdWRlcyhpbnB1dFZhbHVlLnZhbHVlKSldXG59XG5cbmNvbnN0IHJlc2V0T3B0aW9ucyA9ICgpID0+IHtcbiAgb3B0aW9ucy52YWx1ZSA9IFsuLi5vcmlnaW5PcHRpb25zXVxuICBpbnB1dFZhbHVlLnZhbHVlID0gJydcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJDb21wLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj57eyBsYWJlbCB9fTwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgbGFiZWw6IHtcbiAgICB0eXBlOiBTdHJpbmcsXG4gICAgZGVmYXVsdDogJycsXG4gIH0sXG59KVxuXG5jb25zb2xlLmxvZygnY29tcCBzZXR1cCcsIHByb3BzLmxhYmVsKVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319)
> 
> selest 内部维护了一个map，当option 创建或者销毁的时候回去 set,delet（更新的时候去变动map的位置），每次筛选完要保证key要变（由于v-for setup的原因 map倒序的哈哈哈），

那你咋解决的哇。

**Comment by wzrove** [comment]
> 

没找到解决的方法，找到了产生的原因。

**Comment by Delevin888** [comment]
> > 
> 
> 没找到解决的方法，找到了产生的原因。

我自己在重做公司的一块功能，根本来不及去细究。

**Comment by wzrove** [comment]
> > > 
> > 
> > 
> > 没找到解决的方法，找到了产生的原因。
> 
> 我自己在重做公司的一块功能，根本来不及去细究。

只能是先把键盘控制的功能暂时去掉。

**Comment by Delevin888** [comment]
> > > > 
> > > 
> > > 
> > > 没找到解决的方法，找到了产生的原因。
> > 
> > 
> > 我自己在重做公司的一块功能，根本来不及去细究。
> 
> 只能是先把键盘控制的功能暂时去掉。

在我这是偶现的，然后键盘功能又比较重要，不能去。

**Comment by wzrove** [comment]
> > > 
> > 
> > 
> > 没找到解决的方法，找到了产生的原因。
> 
> 我自己在重做公司的一块功能，根本来不及去细究。

既然是倒序的，可以看看能不能把select 里面的map 排个序。我去搞一下。

**Comment by Delevin888** [comment]
> 既然是倒序的，可以看看能不能把select 里面的map 排个序。我去搞一下。
辛苦老哥

**Comment by wzrove** [comment]
> > 既然是倒序的，可以看看能不能把select 里面的map 排个序。我去搞一下。
> > 辛苦老哥

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgcmVmPVwic2VsZWN0UmVmXCJcbiAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgOmZpbHRlci1tZXRob2Q9XCJzZWFyY2hPcHRpb25zXCJcbiAgICBAY2hhbmdlPVwicmVzZXRPcHRpb25zXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlICsgbWl4S2V5XCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHR5cGUgeyBTZWxlY3RDb250ZXh0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgbmV4dFRpY2ssIHJlZiwgdW5yZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuLy8g5Y6f5aeL5pWw5o2uXG5jb25zdCBvcmlnaW5PcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xMScsXG4gICAgbGFiZWw6ICdPcHRpb24xMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEyJyxcbiAgICBsYWJlbDogJ09wdGlvbjEyJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMTMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMTMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xNCcsXG4gICAgbGFiZWw6ICdPcHRpb24xNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjIwJyxcbiAgICBsYWJlbDogJ09wdGlvbjIwJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yMycsXG4gICAgbGFiZWw6ICdPcHRpb24yMycsXG4gIH0sXG5dXG5cbi8v5pCc57Si5ZCO5pi+56S65pWw5o2uXG5jb25zdCBvcHRpb25zID0gcmVmKG9yaWdpbk9wdGlvbnMpXG5jb25zdCBzZWxlY3RSZWYgPSByZWY8U2VsZWN0Q29udGV4dCB8IG51bGw+KG51bGwpXG5jb25zdCBtaXhLZXkgPSByZWYoJycpXG5cbi8v5pCc57SiXG5jb25zdCBzZWFyY2hPcHRpb25zID0gKHF1ZXJ5OiBzdHJpbmcpID0+IHtcbiAgbGV0IHRpbWUgPSBuZXcgRGF0ZSgpLmdldFRpbWUoKVxuICBvcHRpb25zLnZhbHVlID0gb3JpZ2luT3B0aW9ucy5maWx0ZXIoKGspID0+IGsubGFiZWwuaW5kZXhPZihxdWVyeSkgPj0gMClcbiAgbWl4S2V5LnZhbHVlID0gdGltZVxuICBuZXh0VGljaygoKSA9PiByZXNldFNlbGVjdE1hcCgpKVxufVxuXG5jb25zdCByZXNldFNlbGVjdE1hcCA9ICgpID0+IHtcbiAgbGV0IG9wdGlvbnMgPSB1bnJlZihzZWxlY3RSZWYudmFsdWUub3B0aW9ucylcbiAgc2VsZWN0UmVmLnZhbHVlLm9wdGlvbnMgPSBuZXcgTWFwKEFycmF5LmZyb20ob3B0aW9ucykucmV2ZXJzZSgpKVxufVxuXG4vLyBjb25zb2xlLmxvZyhzZWxlY3RSZWYudmFsdWUpXG4vL+avj+asoemAieaLqeWQjumDvemcgOimgeaYvuekuuWFqOmDqOaVsOaNrlxuY29uc3QgcmVzZXRPcHRpb25zID0gKCkgPT4ge1xuICBvcHRpb25zLnZhbHVlID0gb3JpZ2luT3B0aW9uc1xufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by cn-troy** [comment]
这个方案还是有问题，最好的就是element内部解决。外部数据不管怎么排序，内部都会出问题的。因为我们在设置数据后element的option在初始化显示的顺序与内部map的顺序不一致。

https://github.com/vuejs/core/discussions/6087
@wzrove

**Comment by wzrove** [comment]
> 这个方案还是有问题，最好的就是element内部解决。外部数据不管怎么排序，内部都会出问题的。因为我们在设置数据后element的option在初始化显示的顺序与内部map的顺序不一致。
> 
> [vuejs/core#6087](https://github.com/vuejs/core/discussions/6087) @wzrove

https://github.com/element-plus/element-plus/issues/7737#issuecomment-1165399273

改的是select内部，每次都让option走销毁 创建的流程，能保证select 内部维护的`options <Map>`是倒序的。我发的demo目前是没恶性问题的。数据量太大估计会有性能问题。

**Comment by cn-troy** [comment]
感谢，看来只有先把这个组件的源码弄过来用着了。。主要最近太忙，完全没时间去弄element。 @wzrove

**Comment by Delevin888** [comment]
这么久过去了，看来官方是不打算搞咱这个问题了。

**Comment by LeoKun1231** [comment]
官方呢?

**Comment by u373693041** [comment]
我暂时用el-select-v2来替代了

**Comment by kooriookami** [comment]
Fixed
