### ISSUE TITLE
[Bug Report] [Component] [form, form-item] form validate issue

### ISSUE THREAD

**Issue by wuang1992** [element-plus/element-plus#7739]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.10`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDdXN0b21Db21wb25lbnQgZnJvbSAnLi9DdXN0b21Db21wb25lbnQudnVlJ1xuXG5jb25zdCBmb3JtVmFsdWVzID0gcmVhY3RpdmUoe1xuICB2YWx1ZTogdW5kZWZpbmVkLFxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIDptb2RlbD1cImZvcm1WYWx1ZXNcIj5cbiAgXHQ8ZWwtZm9ybS1pdGVtIHByb3A9XCJ2YWx1ZVwiIGxhYmVsPVwiYW55d2F5XCIgOnJ1bGVzPVwiW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdyZXF1aXJlZCcsIHRyaWdnZXI6ICdjaGFuZ2UnIH1dXCI+XG4gICAgICA8Y3VzdG9tLWNvbXBvbmVudCB2LW1vZGVsPVwiZm9ybVZhbHVlcy52YWx1ZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXG4gIH1cbn0iLCJDdXN0b21Db21wb25lbnQudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuICBjb25zdCBwcm9wcyA9IGRlZmluZVByb3BzPHtcbiAgICBtb2RlbFZhbHVlPzogc3RyaW5nO1xuICB9PigpXG4gIGNvbnN0IGVtaXQgPSBkZWZpbmVFbWl0czx7XG4gICAgKGU6ICd1cGRhdGU6bW9kZWxWYWx1ZScpOiB2b2lkO1xuICB9PigpO1xuICBcbiAgY29uc3QgaW5wdXRSZWYgPSByZWYoKTtcbiAgY29uc3QgcG9wb3ZlclJlZiA9IHJlZigpO1xuICBjb25zdCByYWRpb1ZhbHVlID0gcmVmKCk7XG5cblxuICBjb25zdCBoYW5kbGVDYWxlbmRhckNvbmZpcm0gPSAodmFsdWVzOiBDYWxlbmRhclZhbHVlcykgPT4ge1xuICAgIGVtaXQoJ3VwZGF0ZTptb2RlbFZhbHVlJywgdmFsdWVzKTtcbiAgfTtcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdj5cbiAgPGVsLWlucHV0XG4gICAgICByZWY9XCJpbnB1dFJlZlwiXG4gICAgICBwbGFjZWhvbGRlPVwicGxlYXNlIGlucHV0XCJcbiAgICAgIHJlYWRvbmx5XG4gICAgLz5cbiAgICA8ZWwtcG9wb3ZlclxuICAgICAgcmVmPVwicG9wb3ZlclJlZlwiXG4gICAgICA6dmlydHVhbC1yZWY9XCJpbnB1dFJlZlwiXG4gICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgOndpZHRoPVwiNDAwXCJcbiAgICAgIDpzaG93LWFycm93PVwiZmFsc2VcIlxuICAgICAgOmhpZGUtYWZ0ZXI9XCIwXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW9WYWx1ZVwiPlxuICAgICAgICAgIDxlbC1yYWRpbyA6bGFiZWw9XCIxXCI+MTwvZWwtcmFkaW8+XG4gICAgICAgICAgPGVsLXJhZGlvIDpsYWJlbD1cIjJcIj4yPC9lbC1yYWRpbz5cbiAgICAgICAgICA8ZWwtcmFkaW8gOmxhYmVsPVwiM1wiPjM8L2VsLXJhZGlvPlxuICAgICAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXBvcG92ZXI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJfbyI6e319)

### Steps to reproduce

create a custom component that contains a component E.g el-radio-group or el-input etc as form-item input, then change the value of el-component inside custom component, form-item validate will be trigging

### What is Expected?

do not trigg form-item validate

### What is actually happening?

form-item validate has triggered

### Additional comments

can offer a prop to those components E.g el-input、el-radio-group etc to decide as a form-item input or not

**Comment by JackieCheung** [comment]
same issue!
