### ISSUE TITLE
[Bug Report] [Component] [form] Dynamically adding form rule causes uncaught error in promise

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#7758]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgcnVsZUZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpXG5cbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7IGE6ICd4J30pO1xuXG5jb25zdCBydWxlcyA9IHJlYWN0aXZlKHtcbiAgYTogW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdQbGVhc2UgaW5wdXQgbmFtZScsIHRyaWdnZXI6ICdibHVyJyB9XSxcbn0pO1xuXG5jb25zdCBzdWJtaXRGb3JtID0gYXN5bmMgKCkgPT4ge1xuICBpZiAoIXJ1bGVGb3JtUmVmLnZhbHVlKSByZXR1cm5cbiAgYXdhaXQgcnVsZUZvcm1SZWYudmFsdWUudmFsaWRhdGUoKHZhbGlkLCBmaWVsZHMpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnLCBmaWVsZHMpXG4gICAgfVxuICB9KVxufVxuICBcbmNvbnN0IGFkZFJ1bGUgPSAoKSA9PiB7XG4gIHJ1bGVzLmEucHVzaCh7IG1pbjogMTAsIG1lc3NhZ2U6ICdQbGVhc2UgaW5wdXQgbmFtZSBsb25nZXIgdGhhbiAxMCEnLCB0cmlnZ2VyOiAnYmx1cicgfSk7XG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIHJlZj1cInJ1bGVGb3JtUmVmXCIgOnJ1bGVzPVwicnVsZXNcIiA6bW9kZWw9XCJmb3JtXCI+XG4gICAgPGVsLWZvcm0taXRlbSBwcm9wPVwiYVwiIGxhYmVsPVwiQVwiPlxuICBcdFx0PGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLmFcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuXHQ8YnV0dG9uIEBjbGljay5wcnZlbnQ9XCJhZGRSdWxlXCI+XG4gICAgYWRkIHJ1bGVcbiAgPC9idXR0b24+XG4gIFxuICA8YnV0dG9uIEBjbGljay5wcmV2ZW50PVwic3VibWl0Rm9ybVwiPlxuICAgIHN1Ym1pdFxuICA8L2J1dHRvbj5cbiAgXG4gIDxociAvPlxuICBjbGljayBcImFkZCBydWxlXCIgdG8gc2VlIHRoZSBlcnJvciBpbiB0aGUgY29uc29sZS5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

add rule dynamically to an el-form

### What is Expected?

it should work without error

### What is actually happening?

throws error: Uncaught (in promise)

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Could you please provide a repo about this reproduction?
