### ISSUE TITLE
Release Automation - Release new version via Github Actions

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#776]
## Background
Now we are under fast pace developing, which often comes with lots of bug fixes and new features.
The current way of releasing is manually release by @zazzaz 

## Requirement 
As a maintainer myself I want to release a new version via Github provided release function [release](https://github.com/element-plus/element-plus/releases/new) here, when I type fill up required informations and click release button, a new tag should be made, and it should trigger an action to start the release procedure.
1. The script should be able to run command `yarn build` to get a final bundle from bundler
2. The script should be able to use `Github Credential` to fetch `npm credential` and release a new version

**Comment by kerm1it** [comment]
Can i work it?

**Comment by JeremyWuuuuu** [comment]
> Can i work it?

What do you mean? This issue is meant to track the progress of this task.

**Comment by kerm1it** [comment]
I want to work this task. I have experience about github actions.

**Comment by JeremyWuuuuu** [comment]
> I want to work this task. I have experience about github actions.

This is already assigned to @bradleyzhou , sorry for that.

**Comment by kerm1it** [comment]
> > I want to work this task. I have experience about github actions.
> 
> This is already assigned to @bradleyzhou , sorry for that.

OK

**Comment by JeremyWuuuuu** [comment]
> > > I want to work this task. I have experience about github actions.
> > 
> > 
> > This is already assigned to @bradleyzhou , sorry for that.
> 
> OK

If you want to participant, find another issue without no assignee and tell me about it then you can get your hands on. BTW, I am glad to see someone reaching out to help. Ping me if you need my help

**Comment by JeremyWuuuuu** [comment]
Closing due to #1047
