### ISSUE TITLE
Card组件body-style的props类型检测错误

### ISSUE THREAD

**Issue by piexlmax** [element-plus/element-plus#777]
warning内容： [Vue warn]: Invalid prop: type check failed for prop "bodyStyle". Expected String with value "[object Object]", got Object  

经过翻阅源码 发现 card下接收的bodyStyle type为String 默认为 ""

请问此处的props类型是否存在问题

**Comment by JeremyWuuuuu** [comment]
We had a fix in #754 and merged, also published, use `yarn upgrade` to upgrade your local version

**Comment by lizy0329** [comment]
> We had a fix in #754 and merged, also published, use `yarn upgrade` to upgrade your local version

1.0.2-beta.71 该错误依然存在，TS 依然被识别为 string

![body-style 识别错误](https://i.loli.net/2021/08/18/XzQawJYOHZBFDjf.png)
