### ISSUE TITLE
[Bug Report] [Docs] [dialog] 官网中的dialog文档的自定义header用#header无效

### ISSUE THREAD

**Issue by junpeng-wu** [element-plus/element-plus#7773]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `macOS`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUgPSB0cnVlXCI+XG4gICAgT3BlbiBEaWFsb2cgd2l0aCBjdXN0b21pemVkIGhlYWRlclxuICA8L2VsLWJ1dHRvbj5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwidmlzaWJsZVwiIDpzaG93LWNsb3NlPVwiZmFsc2VcIj5cbiAgICA8dGVtcGxhdGUgI2hlYWRlcj1cInsgY2xvc2UsIHRpdGxlSWQsIHRpdGxlQ2xhc3MgfVwiPlxuICAgICAgPGRpdiBjbGFzcz1cIm15LWhlYWRlclwiPlxuICAgICAgICA8aDQgOmlkPVwidGl0bGVJZFwiIDpjbGFzcz1cInRpdGxlQ2xhc3NcIj5UaGlzIGlzIGEgY3VzdG9tIGhlYWRlciE8L2g0PlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBAY2xpY2s9XCJjbG9zZVwiPlxuICAgICAgICAgIDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tbGVmdFwiPjxDaXJjbGVDbG9zZUZpbGxlZCAvPjwvZWwtaWNvbj5cbiAgICAgICAgICBDbG9zZVxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gICAgVGhpcyBpcyBkaWFsb2cgY29udGVudC5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgQ2lyY2xlQ2xvc2VGaWxsZWQgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB0eXBlIHsgRWxCdXR0b24sIEVsRGlhbG9nIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5teS1oZWFkZXIge1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogcm93O1xuICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

直接点击打开dialog

### What is Expected?

点击展示自定义头部内容

### What is actually happening?

不展示自定义头部内容

### Additional comments

麻烦文档写严谨一点吧，检查了下source里面dialog.vue的文件编译出来的是#title，而不是#header

**Comment by josonho** [comment]
see #7550

**Comment by MurphyHou123** [comment]
我也发现这个问题。经过上提示，用#title竟然可以。文档有问题
