### ISSUE TITLE
[Bug Report] [Component] [drawer] el-drawer 组件 #header 功能失效

### ISSUE THREAD

**Issue by HeroMeiKong** [element-plus/element-plus#7774]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html#customized-header)

### Steps to reproduce

点击按钮即可

### What is Expected?

正确展示header内容

### What is actually happening?

无法展示header内容

### Additional comments

请尽快修复

**Comment by josonho** [comment]
fixed in #7550

**Comment by jishuke** [comment]
把header 换成 title 就可以了 例如：<template #title="{ close, titleId, titleClass }"></template>

**Comment by btea** [comment]
更新到最新版本即可。
