### ISSUE TITLE
[Feature Request] [checkbox] button 组件有 size 属性，checkbox 也有，但它们源码的 props 中的 size 类型却不相同，是否可以复用代码呢？

### ISSUE THREAD

**Issue by SignDawn** [element-plus/element-plus#7778]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `checkbox`

## Description

源码复用,  props 中的 size,  button 组件使用的是 useSizeProp , 而 checckbox 使用的是 isValidComponentSize 方法。
这样做是否有什么考虑？是否可以考虑复用代码？

### Additional comments

_(empty)_

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/169077743-ea1398a8-4802-4b6c-a2b4-14d9b0b02bcc.png)
button

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/169077937-e1557096-59fd-44de-90b9-792896dc5169.png)
checkbox

**Comment by SignDawn** [comment]
好的，我还处在学习阶段，thanks !

**Comment by chenxch** [comment]
@emojiiii @SignDawn  #7794 已调整
