### ISSUE TITLE
[Bug Report] [Component] [link] Click the link component to report an error

### ISSUE THREAD

**Issue by HalseySpicy** [element-plus/element-plus#7784]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `e.g. Chrome 101.0.4951.67 / windows 21H2`
- Build Tool: `Vite`

### Related Component

- `el-link`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtbGluayB0eXBlPVwicHJpbWFyeVwiPnByaW1hcnk8L2VsLWxpbms+XG4gIDxlbC1saW5rIHR5cGU9XCJzdWNjZXNzXCI+c3VjY2VzczwvZWwtbGluaz5cbiAgPGVsLWxpbmsgdHlwZT1cIndhcm5pbmdcIj53YXJuaW5nPC9lbC1saW5rPlxuICA8ZWwtbGluayB0eXBlPVwiZGFuZ2VyXCI+ZGFuZ2VyPC9lbC1saW5rPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click link component ==> Uncaught TypeError: Cannot read properties of null (reading 'match')

### What is Expected?

No error reporting

### What is actually happening?

Uncaught TypeError: Cannot read properties of null (reading 'match')

### Additional comments

It can be reproduced on the official website

**Comment by chenxch** [comment]
Please confirm Reproduction again.
