### ISSUE TITLE
[Feature Request] [New Component] [] 不知道你们升级时到底有没有测兼容性

### ISSUE THREAD

**Issue by flmbbb** [element-plus/element-plus#7787]
Feature type: **`New Component`**

## Details

- New component name: `element-plus`

## Description

2.1.10以上不包括2.1.10，在版本chrome 78.0.3904.108（正式版本） （32 位）左右的版本直接不能用，我测过了
加载 element-plus@2.2.0/dist/index.full.js
就完全加载不了，能不能不每升一次，就导至前面的全崩。。。
高版本chrome 版本 101.0.4951.67（正式版本） （64 位） 没问题 。。。

### Additional comments

  app.use(ElementPlus, {
    locale: zhCn,
  })  
 "vue": "^3.2.29",

**Comment by flmbbb** [comment]
![image](https://user-images.githubusercontent.com/17305384/169236384-7adf0b08-1219-46b5-963a-096d70ea909e.png)

**Comment by sxzz** [comment]
Try latest version.
