### ISSUE TITLE
[Bug Report] [Component] [select-v2] doesn't support vue 3.2.34: vnodes.some is not a function

### ISSUE THREAD

**Issue by YujiaCheng1996** [element-plus/element-plus#7789]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.34`
- Element Plus Version: `2.2.0`
- Browser / OS: `Windows11 Chrome/100.0.4896.60 `
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgIG11bHRpcGxlXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoXG4gIEFycmF5LmZyb20oeyBsZW5ndGg6IDEwMDAgfSkubWFwKChfLCBpZHgpID0+ICh7XG4gICAgdmFsdWU6IGBPcHRpb24gJHtpZHggKyAxfWAsXG4gICAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxuICB9KSlcbilcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

el-select-v2

### What is Expected?

support vue 3.2.34

### What is actually happening?

vnodes.some is not a function

### Additional comments

_(empty)_

**Comment by JackieCheung** [comment]
+1

**Comment by chenxch** [comment]
It is normal for me to test locally, it may be a `runtime` problem of `vue`.

**Comment by mexican-jack** [comment]
+1

**Comment by megasanjay** [comment]
+1

**Comment by bkoplin** [comment]
+1

**Comment by life-0** [comment]
+1

**Comment by jw-foss** [comment]
Hey guys, PR has been made: https://github.com/element-plus/element-plus/pull/8145
