### ISSUE TITLE
关于lodash引入导致的文件过大问题

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#779]
![1606896644(1)](https://user-images.githubusercontent.com/34828964/100846517-95b20c80-34b9-11eb-8b78-6bdfc61a5366.jpg)
我已经在生产环境中使用了该组件库，并且为了优化大小问题，我做了按需加载。虽然会有一些小问题，但是自己都可以解决。但是今天用vuecli的打包分析vue-cli-service build --report发现一个致命的问题。
elemenPlus引入了lodash.js，导致原本很小的首屏加载，瞬间飙升到600kb以上，其中lodash.js就需要500kb。希望官方能够重视该问题，否则是非常影响首屏加载的。

**Comment by JeremyWuuuuu** [comment]
This is serious, we need to take a look on that. cc @zazzaz
