### ISSUE TITLE
[Bug Report] [Component] el-tree-select 组件在el-form中, 父节点无法取消选择, 末节点无法选择

### ISSUE THREAD

**Issue by rashagu** [element-plus/element-plus#7796]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`
- `el-form`
- `el-form-item`

### Reproduction Link

[CodePen](https://codepen.io/rashagu/pen/eYVRNmy)

### Steps to reproduce

```
  <el-form :inline="true"  class="demo-form-inline">
    <el-form-item label="Approved by">
      <el-tree-select v-model="value" :data="data" multiple show-checkbox />
    </el-form-item>
  </el-form>
```

### What is Expected?

可以正常多选

### What is actually happening?

父节点无法取消选择, 末节点无法选择

### Additional comments

_(empty)_

**Comment by rashagu** [comment]
#7775

**Comment by Babyfast** [comment]
element-plus更新到最新版本
