### ISSUE TITLE
[Bug Report] [Component] [slider] el-slider组件直接点击不拖拽没有触发change事件

### ISSUE THREAD

**Issue by royalscome** [element-plus/element-plus#7797]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chorme 100.0.4896.127/windows 10`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[CodePen](https://codepen.io/royalscome/pen/ZEryGwq?editors=1111)

### Steps to reproduce

1.在项目中使用el-slider组件；
2.在el-slider中绑定change事件；
3.直接点击滑轨未触发change事件；

### What is Expected?

点击滑轨可以触发change事件

### What is actually happening?

点击滑轨未触发change事件

### Additional comments

_(empty)_

**Comment by holazz** [comment]
Fixed by #9553
