### ISSUE TITLE
Alert 组件样式显示问题

### ISSUE THREAD

**Issue by LuoHuacheng** [element-plus/element-plus#780]
Alert 组件在没有辅助性文字且带图标的条件下，图标与文字没有水平对齐，因为 **slot description** 没有做判断，如下图，希望可以添加判断。
![微信截图_20201202161305](https://user-images.githubusercontent.com/14214871/100846777-e45fa680-34b9-11eb-9ef3-eabc5f45bb43.png)
![微信截图_20201202161404](https://user-images.githubusercontent.com/14214871/100846786-e7f32d80-34b9-11eb-9fea-bb0db4e5f38b.png)

**Comment by JeremyWuuuuu** [comment]
cc @Ryan2128 , can you make a PR for this?

**Comment by Ryan2128** [comment]
YES.
