### ISSUE TITLE
[Bug Report] [Component] [input]   <el-input :maxlength="9" type="number"> 当设置type="number"时， maxlength属性失效

### ISSUE THREAD

**Issue by ylater** [element-plus/element-plus#7800]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.34`
- Element Plus Version: `2.2.0`
- Browser / OS: `版本 101.0.4951.64（正式版本） (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[CodePen](https://codepen.io/ylater/pen/jOZwqvY)

### Steps to reproduce

<el-input v-model="testNum" type="number" :maxlength="6">{{ message }}</el-input>

### What is Expected?

type="number" 时 maxlength生效

### What is actually happening?

type="number" 时maxlength属性未生效

### Additional comments

_(empty)_

**Comment by kospot** [comment]
可以使用min和max代替
一般文本输入框才设置最大长度

**Comment by wolinyy** [comment]
输入maxLength="9" 即可，记得maxLength不要全部小写

**Comment by chenxch** [comment]
并非组件问题，请参考@wolinyy回复方式使用。
