### ISSUE TITLE
[Bug Report] [Component] [dialog] Dialog组件的header插槽失效

### ISSUE THREAD

**Issue by Rich4st** [element-plus/element-plus#7803]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `chrom/windos11`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmPGJvb2xlYW4+KHRydWUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJ2aXNpYmxlXCI+XG4gICAgPHRlbXBsYXRlICNoZWFkZXI+XG4gICAgICBoZWFkZXJcbiAgICA8L3RlbXBsYXRlPlxuICAgIFRoaXMgaXMgZGlhbG9nIGNvbnRlbnQuXG4gIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用dialog的header插槽不生效

### What is Expected?

header插槽生效

### What is actually happening?

header插槽不生效

### Additional comments

_(empty)_

**Comment by btea** [comment]
最新版已经解决。

**Comment by qifengzhang007** [comment]
目前只能使用  #title 避开这个bug

**Comment by btea** [comment]
最新版本应该是没问题的，如图所示
![image](https://user-images.githubusercontent.com/24516654/170005051-419293ae-8b64-45c8-8e0a-6ae04e8cc7af.png)
