### ISSUE TITLE
i18n RTL support ? 

### ISSUE THREAD

**Issue by LuoHuacheng** [element-plus/element-plus#781]
我注意到有提供阿拉伯语言支持 **ar** ，因为中东地区的书写排版方式是从右向左的，请问官方有没有支持布局上的左右切换呢？还是说需要我自己将样式文件单独提取出来做一次 **rtl** 处理再根据条件加入自己项目。

I noticed that there is Arabic language support ar because the writing and typesetting method in the Middle East is from right to left. Does the official support for switching left and right in the layout? Or I need to extract the style file by myself, do rtl processing and then add it to my project according to the conditions.

**Comment by JeremyWuuuuu** [comment]
Nope, that has not been added.
We definitely need to add rtl support.

**Comment by ahmadem** [comment]
pleas add rtl support

**Comment by sxzz** [comment]
There are currently no plans for RTL. If anyone wants to help, please feel free.
