### ISSUE TITLE
[Feature Request] 升级新版本后打包出现依赖报错

### ISSUE THREAD

**Issue by ZANJIAHAO1008** [element-plus/element-plus#7813]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

本地运行无问题 打包出现问题
 node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/table-v2/src/components/sort-icon.d.ts:5:37 - error TS2339: Property 'class' does not exist on type 'IntrinsicAttributes'.

5     class?: JSX.IntrinsicAttributes['class'];
                                      ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/table-v2/src/types.d.ts:92:37 - error TS2339: Property 'class' does not exist on type 'IntrinsicAttributes'.

92     class?: JSX.IntrinsicAttributes['class'];
                                       ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/time-select/index.d.ts:112:38 - error TS2304: Cannot find name 'ComponentSize'.

112         type: import("vue").PropType<ComponentSize>;
                                         ~~~~~~~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/time-select/index.d.ts:285:38 - error TS2304: Cannot find name 'ComponentSize'.

285         type: import("vue").PropType<ComponentSize>;
                                         ~~~~~~~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/table-v2/src/components/sort-icon.d.ts:5:37 - error TS2339: Property 'class' does not exist on type 'IntrinsicAttributes'.

5     class?: JSX.IntrinsicAttributes['class'];
                                      ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/table-v2/src/types.d.ts:92:37 - error TS2339: Property 'class' does not exist on type 'IntrinsicAttributes'.

92     class?: JSX.IntrinsicAttributes['class'];
                                       ~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/time-select/index.d.ts:112:38 - error TS2304: Cannot find name 'ComponentSize'.

112         type: import("vue").PropType<ComponentSize>;
                                         ~~~~~~~~~~~~~

node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/time-select/index.d.ts:285:38 - error TS2304: Cannot find name 'ComponentSize'.

285         type: import("vue").PropType<ComponentSize>;
                                         ~~~~~~~~~~~~~

Found 8 errors in 6 files.

Errors  Files
     1  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/table-v2/src/components/sort-icon.d.ts:5
     1  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/table-v2/src/types.d.ts:92
     2  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/es/components/time-select/index.d.ts:112
     1  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/table-v2/src/components/sort-icon.d.ts:5
     1  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/table-v2/src/types.d.ts:92
     2  node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.1_vue@3.2.31/node_modules/element-plus/lib/components/time-select/index.d.ts:112
 ELIFECYCLE  Command failed with exit code 2.

### Additional comments

_(empty)_

**Comment by langyamu** [comment]
![image](https://user-images.githubusercontent.com/40269393/170064606-59eefa0a-3f0e-4acb-bdd7-5938b83b8093.png)
我这边也是这个错误，不过下边的  type: import("vue").PropType<ComponentSize>; 可以通过更新导入类型解决
![image](https://user-images.githubusercontent.com/40269393/170065027-f564d174-855f-421d-bfb1-d733e21c3bd1.png)

**Comment by langyamu** [comment]
> > ![image](https://user-images.githubusercontent.com/40269393/170064606-59eefa0a-3f0e-4acb-bdd7-5938b83b8093.png)
> > 我这边也是这个错误，不过下边的  type: import("vue").PropType; 可以通过更新导入类型解决
> > ![image](https://user-images.githubusercontent.com/40269393/170065027-f564d174-855f-421d-bfb1-d733e21c3bd1.png)
> 
> 我这个问题解决了，package.json build中取消tsc就可以
我刚刚也解决了，上边的使用的 yarn ，现在这个用的 pnpm 

我将 vue-tsc 升级到 与 element-plus 一致的版本后解决了
`class?: JSX.IntrinsicAttributes['class'];`  **Property 'class' does not exist on type 'IntrinsicAttributes'.** 的 问题
![image](https://user-images.githubusercontent.com/40269393/170073507-0f3b4db4-c17c-44e9-a8cd-bf615e7c1e39.png)

但是依旧报 `type: import("vue").PropType<ComponentSize>;`  **Cannot find name 'ComponentSize'.** 的错
顺着路径更改文件 node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.2_vue@3.2.36/node_modules/element-plus/es/components/time-select/index.d.ts 
添加了一句引入 `import { ComponentSize } from 'element-plus/es';` 后顺利解决

具体原因不太懂感觉可能是 vue-tsc 的问题

**Comment by ZANJIAHAO1008** [comment]
> > > ![image](https://user-images.githubusercontent.com/40269393/170064606-59eefa0a-3f0e-4acb-bdd7-5938b83b8093.png)
> > > 我这边也是这个错误，不过下边的  type: import("vue").PropType; 可以通过更新导入类型解决
> > > ![image](https://user-images.githubusercontent.com/40269393/170065027-f564d174-855f-421d-bfb1-d733e21c3bd1.png)
> > 
> > 我这个问题解决了，package.json build中取消tsc就可以
> 我刚刚也解决了，上边的使用的 yarn ，现在这个用的 pnpm 
> 
> 我将 vue-tsc 升级到 与 element-plus 一致的版本后解决了
> `class?: JSX.IntrinsicAttributes['class'];`  **Property 'class' does not exist on type 'IntrinsicAttributes'.** 的 问题
> ![image](https://user-images.githubusercontent.com/40269393/170073507-0f3b4db4-c17c-44e9-a8cd-bf615e7c1e39.png)
> 
> 但是依旧报 `type: import("vue").PropType<ComponentSize>;`  **Cannot find name 'ComponentSize'.** 的错
> 顺着路径更改文件 node_modules/.pnpm/registry.npmmirror.com+element-plus@2.2.2_vue@3.2.36/node_modules/element-plus/es/components/time-select/index.d.ts 
> 添加了一句引入 `import { ComponentSize } from 'element-plus/es';` 后顺利解决
> 
> 具体原因不太懂感觉可能是 vue-tsc 的问题
> 
> 

嗯呢

**Comment by langyamu** [comment]
> /.pnpm/registry.npmmirror.com+element-plus@2.2.2_vue@3.2.36/node_modules/element-plus/es/components/time-select/index.d.ts

谢谢，这个方法可以解决

**Comment by langyamu** [comment]
> Please try to enable [skipLibCheck](https://www.typescriptlang.org/tsconfig/skipLibCheck.html) in tsconfig.json

谢谢，这个方法可以解决
