### ISSUE TITLE
[Bug Report] [Build] [menu-item] 你们还能不能行了，每次发版全是bug 文档全是忽悠钱的广告，到底再搞什么啊，打包运行编译这么重大的报错都不测试吗

### ISSUE THREAD

**Issue by huifeidewoniu1995** [element-plus/element-plus#7818]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47`
- Build Tool: `Webpack`

### Related Component

- `el-menu-item`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47

### What is Expected?

./node_modules/_element-plus@2.2.1@element-plus/es/components/menu-item/style/css2.mjs 
Module not found: Error: Can't resolve 'element-plus/theme-chalk/menu-item.css' 

### What is actually happening?

./node_modules/_element-plus@2.2.1@element-plus/es/components/menu-item/style/css2.mjs 
Module not found: Error: Can't resolve 'element-plus/theme-chalk/menu-item.css' 

### Additional comments

你们还能不能行了，每次发版全是bug 文档全是忽悠钱挂羊头卖狗肉的广告，到底再搞什么啊
作为忠实的用户 真实没想到饿了么会沦落到如此地步 唉

./node_modules/_element-plus@2.2.1@element-plus/es/components/menu-item/style/css2.mjs 
Module not found: Error: Can't resolve 'element-plus/theme-chalk/menu-item.css'

**Comment by JackieCheung** [comment]
bug+1

**Comment by tolking** [comment]
反馈 BUG 就反馈 BUG，谁没有写过。

**Comment by deacyn2013** [comment]
bug+1
遇到了

**Comment by JeremyWuuuuu** [comment]
一行代码没来提交过，一分钱没赞助过，影响您赚钱了真是抱歉 :bow:

**Comment by Rafong973** [comment]
肝火那么旺，一定没有性生活。
