### ISSUE TITLE
[Bug Report] [Style] [date-picker] The date picker setting size is invalid

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#7821]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Chrome/101.0.4951.64`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1iYXNpY1wiPlxuICAgICA8ZWwtZGF0ZS1waWNrZXIgdi1tb2RlbD1cInZhbHVlMVwiIHNpemU9XCJzbWFsbFwiPjwvZWwtZGF0ZS1waWNrZXI+XG4gICAgIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwidmFsdWUxXCIgc2l6ZT1cImxhcmdlXCI+PC9lbC1kYXRlLXBpY2tlcj5cbiAgICAgPGVsLWRhdGUtcGlja2VyIHYtbW9kZWw9XCJ2YWx1ZTNcIiA+PC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUxID0gcmVmKClcbmNvbnN0IHZhbHVlMiA9IHJlZigpXG5jb25zdCB2YWx1ZTMgPSByZWYoKVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5leGFtcGxlLWJhc2ljIC5lbC1kYXRlLWVkaXRvciB7XG4gIG1hcmdpbjogOHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

`<el-date-picker v-model="value1" size="small"></el-date-picker>`  setting size is invalid

### What is Expected?

setting  `size="small"` height is 24px

### What is actually happening?

setting  `size="small"` height is 32px

### Additional comments

_(empty)_

**Comment by YunYouJun** [comment]
Thanks for your feedback, we will fix it as soon as possible.

**Comment by YunYouJun** [comment]
I create #7831 to fix it, you can check if it is what you want.
