### ISSUE TITLE
[Bug Report] [Component] [form] from中的 label-position 设置为 left 无效

### ISSUE THREAD

**Issue by cnscoo** [element-plus/element-plus#7829]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Chrome 101.0.4951.67/Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html#对齐方式)

### Steps to reproduce

<el-form label-width="100px" label-position="left">
    <el-form-item label="用户名" prop="username" required>
        <el-input v-model="form.username" />
    </el-form-item>
</el-form>

### What is Expected?

form-item 的 label 应该左对齐。

### What is actually happening?

form-item 的 label 实际右对齐。

### Additional comments

官网组件示例中 表单的对齐方式示例就有这个问题。

**Comment by chenxch** [comment]
via #7826

**Comment by ryuhangyeong** [comment]
resolve #7826
