### ISSUE TITLE
Tooltip with dropdown will not show

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#783]
Tooltip with dropdown will not show.
```html
<el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
    <el-dropdown>
        <el-button type="primary">buttonCont</el-button>
        <template #dropdown>
            <el-dropdown-menu>
                <el-dropdown-item>黄金糕</el-dropdown-item>
                <el-dropdown-item disabled>双皮奶</el-dropdown-item>
                <el-dropdown-item divided>蚵仔煎</el-dropdown-item>
            </el-dropdown-menu>
        </template>
    </el-dropdown>
</el-tooltip>
```
Is this a bug?
![image](https://user-images.githubusercontent.com/38392315/100848988-dcedcc80-34bc-11eb-8e2f-d26fb8f116be.png)

**Comment by JeremyWuuuuu** [comment]
I wonder under what circumstances you are going to need feature like this? This just doesn't make any sense to me.

**Comment by JeremyWuuuuu** [comment]
Cause you see, because `ElDropdown` was built with `ElPopper`, `ElTooltip` was built with as well. The current implementation of `ElPopper` is to took the first child of the `default` slot then copy it via `cloneVNode`, even thought I haven't take a closer look at this issue, but I do see potential issue.

**Comment by Ryan2128** [comment]
Maybe this ? It works well.

```
<template>
  <el-dropdown>
    <el-tooltip
      class="item"
      effect="dark"
      content="Top Left 提示文字"
      placement="top-start"
    >
      <el-button type="primary">buttonCont</el-button>
    </el-tooltip>

    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item>黄金糕</el-dropdown-item>
        <el-dropdown-item disabled>双皮奶</el-dropdown-item>
        <el-dropdown-item divided>蚵仔煎</el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>
```

**Comment by kooriookami** [comment]
> I wonder under what circumstances you are going to need feature like this? This just doesn't make any sense to me.

![image](https://user-images.githubusercontent.com/38392315/100853052-43c1b480-34c2-11eb-86c6-3a66ceada0b2.png)
When the button is an icon, the tooltip has a great work.

**Comment by kooriookami** [comment]
> Maybe this ? It works well.
> 
> ```
> <template>
>   <el-dropdown>
>     <el-tooltip
>       class="item"
>       effect="dark"
>       content="Top Left 提示文字"
>       placement="top-start"
>     >
>       <el-button type="primary">buttonCont</el-button>
>     </el-tooltip>
> 
>     <template #dropdown>
>       <el-dropdown-menu>
>         <el-dropdown-item>黄金糕</el-dropdown-item>
>         <el-dropdown-item disabled>双皮奶</el-dropdown-item>
>         <el-dropdown-item divided>蚵仔煎</el-dropdown-item>
>       </el-dropdown-menu>
>     </template>
>   </el-dropdown>
> </template>
> ```

Yes, it's work well.

**Comment by JeremyWuuuuu** [comment]
There are risks for this kind of implementation that you might want to be aware of, which is that when there is no sufficient space, the top `tooltip` will be flipped down and taking over the dropdown's position, which could be annoying.

**Comment by JeremyWuuuuu** [comment]
Closing this since this is a trivial issue which related to how you use the components
