### ISSUE TITLE
[Bug Report] [Component] [loading] namespace 适配问题

### ISSUE THREAD

**Issue by k713927** [element-plus/element-plus#7837]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29uZmlnLXByb3ZpZGVyIG5hbWVzcGFjZT1cInRtXCIgPlxuICAgICAgXG4gICAgPGVsLXRhYmxlIHYtbG9hZGluZz1cImxvYWRpbmdcIiA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG4gICAgXG4gICA8L2VsLWNvbmZpZy1wcm92aWRlcj5cbiAgXG4gXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBsb2FkaW5nID0gcmVmKHRydWUpXG5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5ib2R5IHtcbiAgbWFyZ2luOiAwO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue

<template>
  <el-config-provider namespace="tm" >
      
    <el-table v-loading="loading" :data="tableData" style="width: 100%">
    <el-table-column prop="date" label="Date" width="180" />
    <el-table-column prop="name" label="Name" width="180" />
    <el-table-column prop="address" label="Address" />
  </el-table>
    
   </el-config-provider>
  
 
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const loading = ref(true)

const tableData = [
  {
    date: '2016-05-02',
    name: 'John Smith',
    address: 'No.1518,  Jinshajiang Road, Putuo District',
  },
  {
    date: '2016-05-04',
    name: 'John Smith',
    address: 'No.1518,  Jinshajiang Road, Putuo District',
  },
  {
    date: '2016-05-01',
    name: 'John Smith',
    address: 'No.1518,  Jinshajiang Road, Putuo District',
  },
]
</script>

<style>
body {
  margin: 0;
}
</style>


```

### What is Expected?

期望是修改了命名空间 el-loading-mask  改为 tm-loading-mask

### What is actually happening?

实际没有改变还是原来的el-

### Additional comments

_(empty)_

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/44334858/169674883-aa05b250-a08d-4e03-8f1a-84b743389027.png">

**Comment by chenxch** [comment]
Please read the [documentation](https://element-plus.org/zh-CN/guide/namespace.html#%E8%AE%BE%E7%BD%AE-scss-%E5%92%8C-css-%E5%8F%98%E9%87%8F) in detail

**Comment by SunYuanOnly** [comment]
遇到了相同的问题，v-loading中的el命名空间未被自定义覆盖

**Comment by tolking** [comment]
确实现在还没有覆盖 loading 组件
