### ISSUE TITLE
el-pagination国际化，官方文档错误sync使用，sync下数据未更新

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#784]
直接拷贝官方分页组件
 <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page.sync="currentPage3"
      :page-size="100"
      layout="prev, pager, next, jumper"
      :total="1000">
    </el-pagination>
1、vue3已经不支持sync，现在是@update，并且使用@update发现数据不会同步变更
2、目前为按需加载，引入使用的时候官方的“前往”中文字样，变成go to，并且没有找到可以变更名称的参数

**Comment by JeremyWuuuuu** [comment]
Answer for 
> 1、vue3已经不支持sync，现在是@update，并且使用@update发现数据不会同步变更

Part of the documentation has not been updated yet.
Now you use `v-model:currentPage` as model value to pass down to `el-pagination

Answer for 
> 2、目前为按需加载，引入使用的时候官方的“前往”中文字样，变成go to，并且没有找到可以变更名称的参数

Because the default locale has been updated to `en_US`. In order to change that, simply do this:

```ts
import { use } from 'element-plus/lib/locale'
use(languageObject)
```

**Comment by ht-sauce** [comment]
好的。

**Comment by Yimisunny** [comment]
都试过了，并不起作用
