### ISSUE TITLE
[Bug Report] [Component] [radio-button] el-radio-button in el-radio-group loss its active color after clicking another group

### ISSUE THREAD

**Issue by AsakiRain** [element-plus/element-plus#7843]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW8xXCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiTmV3IFlvcmtcIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIldhc2hpbmd0b25cIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIkxvcyBBbmdlbGVzXCIgLz5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJDaGljYWdvXCIgLz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICA8L2Rpdj5cbiAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDIwcHhcIj5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvMlwiPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIk5ldyBZb3JrXCIgLz5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJXYXNoaW5ndG9uXCIgLz5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJMb3MgQW5nZWxlc1wiIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiQ2hpY2Fnb1wiIC8+XG4gICAgPC9lbC1yYWRpby1ncm91cD5cbiAgPC9kaXY+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAyMHB4XCI+XG4gICAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJyYWRpbzNcIiBzaXplPVwic21hbGxcIj5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJOZXcgWW9ya1wiIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiV2FzaGluZ3RvblwiIGRpc2FibGVkIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiTG9zIEFuZ2VsZXNcIiAvPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIkNoaWNhZ29cIiAvPlxuICAgIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgcmFkaW8xID0gcmVmKCdOZXcgWW9yaycpXG5jb25zdCByYWRpbzIgPSByZWYoJ05ldyBZb3JrJylcbmNvbnN0IHJhZGlvMyA9IHJlZignTmV3IFlvcmsnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

0. Even the first view of the page is incorrect.
1. Click 'Washington' in first radio group.
2. Click 'Washington' in second radio group.

### What is Expected?

0. The el-radio-button all have thier active state in first view.
1. 'Washington' button in first group activated.
2. 'Washington' button in both radio group keep their active state.

### What is actually happening?

0. Only el-radio-button in last el-radio-group will have active color.
1. Same as expected.
2. 'Washington' in first group disactivated, and 'Washington' in second group activated.

### Additional comments

This bug only appears in v2.2.1, and v2.2.0 works fine with me, so may the css being misconfigurated?

**Comment by Giwayume** [comment]
@AsakiRain can you check in 2.2.2?

**Comment by AsakiRain** [comment]
> @AsakiRain can you check in 2.2.2?

Great, works fine. I think I may close this issue.
