### ISSUE TITLE
[Bug Report] [Component] [date-picker] namespace 适配问题

### ISSUE THREAD

**Issue by k713927** [element-plus/element-plus#7844]
[修改补发]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG5cbjx0ZW1wbGF0ZT5cbiAgPCEtLW5hbWVzcGFjZeaUueS4unRtLS0+XG4gIDxlbC1jb25maWctcHJvdmlkZXIgbmFtZXNwYWNlPVwidG1cIiA+XG4gICAgICBcbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICBcbiAgICAgIHR5cGU9XCJkYXRldGltZXJhbmdlXCJcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgICBlbmQtcGxhY2Vob2xkZXI9XCJFbmQgZGF0ZVwiXG4gICAgLz5cbiAgICBcbiAgICBcbiAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue


<template>
  <!--namespace改为tm-->
  <el-config-provider namespace="tm" >
      
    <el-date-picker
    
      type="datetimerange"
      range-separator="To"
      start-placeholder="Start date"
      end-placeholder="End date"
    />
    
    
   </el-config-provider>
  
</template>

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'

import { ElementPlus } from '@element-plus/icons-vue'

</script>

```

### What is Expected?

期望是修改了命名空间后，class也改变

### What is actually happening?

实际没有改变还是原来的el-

### Additional comments

_(empty)_

vue-cli 打包的时候已经 引入

 @forward 'element-plus/theme-chalk/src/mixins/config.scss' with (
  $namespace: 'tm'
);

并且其他组件已经生效正常，

并且官方的demo。 https://github.com/element-plus/element-plus-vite-starter

把 element-plus版本改为最新版** "element-plus": "^2.2.1",**，同样存在这一的问题

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/44334858/169695656-bca17f2a-55a5-459f-bf1e-dcf1235c16cd.png">

**Comment by 0song** [comment]
will fix soon
