### ISSUE TITLE
[Bug Report] [Component] [input-number] Input number : weird behaviour

### ISSUE THREAD

**Issue by AubSs** [element-plus/element-plus#7845]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.2.1`
- Browser / OS: `Chromium Version 102.0.4960.0 (Developer Build) (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBudW0gPSByZWYoMC4wMSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cIm51bVwiIDpwcmVjaXNpb249XCIyXCIgOnN0ZXA9XCIwLjAxXCIgOm1pbj1cIjBcIiA6bWF4PVwiMTBcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Set input value to 0,01

### What is Expected?

Display 0,01

### What is actually happening?

0,10

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#7777
