### ISSUE TITLE
[Bug Report] [Component] [button] button样式问题

### ISSUE THREAD

**Issue by k713927** [element-plus/element-plus#7846]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 SE 2.X MetaSr 1.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiXG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+UHJpbWFyeTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cblxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

需要谷歌浏览器 低版本，我测试的是chrome80，样式显示为 ：

<img width="62" alt="image" src="https://user-images.githubusercontent.com/44334858/169703423-0e06e687-61ad-490e-ad77-2d26278ebb4d.png">

期望的应该是：
<img width="102" alt="image" src="https://user-images.githubusercontent.com/44334858/169703597-6d8c3dbf-eb66-48ee-80ab-1e877d58638d.png">

element-plus 2.2.0不存在这一的问题，只有2.2.1存在

原因是 css :not（.a,.b） 这种样式低版本谷歌不支持 
```css
.el-button:not(.is-text, .is-link, .el-button--text){
}
```
 https://www.zhangxinxu.com/wordpress/2022/02/css-not-pseudo-class-list-argument/

### What is Expected?

1

### What is actually happening?

1

### Additional comments

_(empty)_

**Comment by CarterLi** [comment]
https://caniuse.com/css-not-sel-list

我找了一圈没找到element-plus官方声明的浏览器兼容版本。某些库就有声明只支持最新两个版本，那这就不是bug。

不过我觉得按照element-plus还有大批国内用户，有各种杂七杂八的低版本chrome套壳浏览器，低版本兼容还是有必要保证一下

**Comment by tolking** [comment]
@YunYouJun 考虑到 [环境支持](https://element-plus.org/zh-CN/guide/installation.html#%E7%8E%AF%E5%A2%83%E6%94%AF%E6%8C%81) 或许这里应该改为更兼容的 `el:not(a):not(b)`

或者可以通过插件实现低版本兼容。像是 [postcss-selector-not](https://github.com/postcss/postcss-selector-not) 或者 [postcss-preset-env](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env) 之内的插件。（我不清楚有没有同类的 gulp 插件）

@CarterLi autoprefixer 主要用于前缀，并不能支持一些新增的语法

**Comment by YunYouJun** [comment]
Yes. I think we can downgrade it to `:not():not()`.

@k713927 As an issue finder, are you interested in contributing a PR to it?

**Comment by godShira** [comment]
chrome 79.0.3945.79  32位

**Comment by tolking** [comment]
@godShira 将在下一个发行版本中修复
