### ISSUE TITLE
[Bug Report] [Component] [date-picker] @focus and @blur do not emit the component instance

### ISSUE THREAD

**Issue by dan-entous** [element-plus/element-plus#7856]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.1`
- Browser / OS: `Chrome 101.0.4951.64 / macOS 10.14.6`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5cbmNvbnN0IG9uRm9jdXMgPSAoZWwpID0+IGNvbnNvbGUubG9nKCdvbkZvY3VzJywgZWwpXG5jb25zdCBvbkJsdXIgPSAoZWwpID0+IGNvbnNvbGUubG9nKCdvbkJsdXInLCBlbCkgIFxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIFxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICB0eXBlPVwiZGF0ZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCJcbiAgICBAYmx1cj1cIm9uQmx1clwiXG4gICAgQGZvY3VzPVwib25Gb2N1c1wiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. add the DatePicker component to the application with an @focus and @blur event handler
1. click inside the DatePicker component to trigger a focus event
1. click outside the DatePicker component to trigger a blur event

### What is Expected?

1. @foucs: the component instance should be sent as an argument to the event handler function
1. @blur: the component instance should be sent as an argument to the event handler function

see https://element-plus.org/en-US/component/date-picker.html#events

### What is actually happening?

1. @focus event handler is not triggered
1. @blur event handler receives the FocusEvent as an argument, not the component instance

### Additional comments

_(empty)_

**Comment by Giwayume** [comment]
I'm not sure it's intended to emit the component instance like the docs say, because that does not match what other similar focusable components does. But referenced PR above is to fix focus not firing when clicking on the input.

**Comment by jw-foss** [comment]
I think this is a mistake in the documentation, it only emits the `event` which is an `Event` to the users.
