### ISSUE TITLE
希望可以在el-menu的select中可以获取到所选择元素的相关属性

### ISSUE THREAD

**Issue by piexlmax** [element-plus/element-plus#786]
在 element v2版本中 select三个参数（index,indexPath,element）其中element可以获取到目前活跃item上所挂载的属性，在v3版本中，第三个属性之可以获取到{index，indexPath}，期望可以如V2版本一样

**Comment by JeremyWuuuuu** [comment]
Could you be more specific? It's kind of hard to assume what you need...

**Comment by Liiked** [comment]
the impelemation of `menu` is never like before, you may specify your needs
we'll see if there is any neccessary to do it or make it better

**Comment by piexlmax** [comment]
抱歉，更新版本后发现第三个参数route已经恢复正常。
