### ISSUE TITLE
[Bug Report] [Component] [select] el-select出现文本选择样式

### ISSUE THREAD

**Issue by hoowhoami** [element-plus/element-plus#7862]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select.html)

### Steps to reproduce

1. 下拉框选择一个选项
2. 再次打开下拉框选择相同的选项

### What is Expected?

不出现文本选择样式

### What is actually happening?

出现了文本选择样式

### Additional comments

element-plus 2.2.0 是正常的

![image](https://user-images.githubusercontent.com/84499551/169805112-033b8b3e-e98d-49a2-83f5-650a0dd86ef0.png)

**Comment by hoowhoami** [comment]
新版本已经解决了这个问题。

**Comment by chenliangngng** [comment]
@hoowhoami 哪个版本改了，我这边测到还没有

**Comment by chenliangngng** [comment]
"element-plus": "^2.2.6",
"vue": "^3.2.37",
如上我的版本，这个问题还没有修复，我看上面pr也还没合呀
