### ISSUE TITLE
[Bug Report] [Component] [button] button在各浏览器表现不一

### ISSUE THREAD

**Issue by yeqinghz** [element-plus/element-plus#7869]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 SE 2.X MetaSr 1.0`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

官网说明文档中的第一排和第三排按钮   在SOGOU/QQ/360/360极速等国产浏览器中均显示为灰底白色文字，在EDGE/CHROME/FF浏览器下正常，
使用在项目中也是如此 

### What is Expected?

在所有浏览器中均正常显示 

### What is actually happening?

也可能是国产套壳浏览器的问题导致的问题

### Additional comments

_(empty)_

**Comment by tall-talker** [comment]
这种的提bug没人响应的，关注下功能问题

**Comment by jyp-qiyu** [comment]
谷歌浏览器87版本也一样

**Comment by lxhtiamo** [comment]
![image](https://user-images.githubusercontent.com/22663888/170159035-1c6fb451-045c-4e51-a209-2f39094bd07c.png)
我原来还以为是我360极速版浏览器设置错误,直到我换了谷歌/火狐/edge,原来是2.2新版有问题

**Comment by JCAlways** [comment]
问题+1

**Comment by LiHDong** [comment]
经测试，发现是这种内核较旧的浏览器不支持`:not(selector list)`这种语法。我现在的解决方案是将版本锁定在`2.1.11`。
![image](https://user-images.githubusercontent.com/26057849/170178081-06f7ccec-305e-4ec6-8a30-ba1ddf8ab742.png)

**Comment by wenqiuya** [comment]
怎么解决？等修复吗？

**Comment by fengqiyue** [comment]
> 谷歌浏览器87版本也一样

确实，很多国产浏览器内核版本就是 86 和87
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4463452/170232986-990d61e0-022f-4375-8d40-e7442c9e35e7.png">

**Comment by Delevin888** [comment]
一样的问题，我还以为是我哪里没用对， 现在降级为 2.2.0 了

**Comment by xiangqunXiao** [comment]
这算是国产浏览器的优雅降级哈哈哈，别改了

**Comment by YunYouJun** [comment]
Yes. I think we can downgrade it to `:not():not()`.

@yeqinghz or anyone, As an issue finder, are you interested in contributing a PR to it?

If not, we'll make sure to fix it before the next release.

In `button.scss`, just change `:not(xxx)` to `&:not(.is-text), &:not(.is-link), &:not(.#{$namespace}-button--text) {}`.

**Comment by JeremyWuuuuu** [comment]
Does anyone want to fix this?  Chrome86 should have been in our support list I suppose.

**Comment by tolking** [comment]
> not 不支持多选的话，那就拆了覆盖一下吧
> 
> ```
> .el-button:not(.is-text),
> .el-button:not(.is-link),
> .el-button:not(.el-button--text) {
>   background-color: var(--el-button-bg-color);
>   border: var(--el-border);
>   border-color: var(--el-button-border-color)
> }
> 
> .el-button:not(.is-text):focus,
> .el-button:not(.is-link):focus,
> .el-button:not(.el-button--text):focus,
> .el-button:not(.is-text):hover,
> .el-button:not(.is-link):hover,
> .el-button:not(.el-button--text):hover {
>   color: var(--el-button-hover-text-color);
>   border-color: var(--el-button-hover-border-color);
>   background-color: var(--el-button-hover-bg-color);
>   outline: 0
> }
> 
> .el-button:not(.is-text):active,
> .el-button:not(.is-link):active,
> .el-button:not(.el-button--text):active {
>   color: var(--el-button-active-text-color);
>   border-color: var(--el-button-active-border-color);
>   background-color: var(--el-button-active-bg-color);
>   outline: 0
> }
> 
> .el-button:not(.is-text):focus-visible,
> .el-button:not(.is-link):focus-visible,
> .el-button:not(.el-button--text):focus-visible {
>   border-color: transparent;
>   outline: 2px solid var(--el-button-border-color);
>   outline-offset: 1px
> }
> ```
