### ISSUE TITLE
[Bug Report] [Component] [drawer, form-item] Drawer 抽屉导致表单控件被聚焦重选

### ISSUE THREAD

**Issue by ibycchen** [element-plus/element-plus#7871]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

利用Drawer打开的组件包含表单控件，表单控件输入完毕，点击空白区域，依然触发上一步的控件被聚焦选定

### What is Expected?

点击空白区域，表单控件自动失去焦点

### What is actually happening?

点击空白区域，依然触发上一步的控件被聚焦选定

### Additional comments
问题复现地址：
https://element-plus.org/zh-CN/component/drawer.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%86%85%E5%AE%B9

**Comment by ibycchen** [comment]
官网例子复现问题：自定义内容 > Open Drawer with nested form

**Comment by hoowhoami** [comment]
我也遇到了这个问题，而且el-time-picker组件在Drawer中因为此问题，导致点击清空后又自动回显当前时间，无法正常使用

**Comment by static7** [comment]
我也遇到了

**Comment by ibycchen** [comment]
发现此问题后，查看线上版本2.2.0，是正常显示，但开发环境由于昨天升级到了2.2.2，然后想回退到2.2.0，重新安装依赖，居然也出现此问题。猜想应该是底层依赖出现了BUG

**Comment by zio-zhang** [comment]
好像是跟el-select 的blur()函数有点关系，

**Comment by JeremyWuuuuu** [comment]
大家好，这个问题可能是我们在调整键盘操作的时候出现的。我会花些时间来整理一下这个问题。

实际的表现上，在 Drawer 和 Dialog 内部，都应该将内容聚焦锁定在弹出层内，这是符合 W3C 标准的也是我们正在优化的地方。

这个问题出现可能是因为组件之间的联动没有调整好，所以导致了这个问题。抱歉

**Comment by hoowhoami** [comment]
> 大家好，这个问题可能是我们在调整键盘操作的时候出现的。我会花些时间来整理一下这个问题。
> 
> 实际的表现上，在 Drawer 和 Dialog 内部，都应该将内容聚焦锁定在弹出层内，这是符合 W3C 标准的也是我们正在优化的地方。
> 
> 这个问题出现可能是因为组件之间的联动没有调整好，所以导致了这个问题。抱歉

辛苦了

**Comment by JeremyWuuuuu** [comment]
调查结果：

我们在做的时候使用的是 Firefox，但是 Firefox 对于 foucs/blur 事件的处理好像与其它浏览器不太一样，没有注意到这个问题实在抱歉 :bow:

**Comment by xuelixuan** [comment]
我也遇到了，刚刚解决，提供一个临时解决方案吧。
```html
  <div class="dpicker">
      <oWeekPicker :weekRange="weekRange" @changeTime="getChangeTime" /> // 根据element 日期组件二次封装，不用看这行
      <el-input class="input-hidden" ref="inputHidden"></el-input> // 定义一个input，绝对定位后，放到oWeekPicker下面
  </div>
```
```js
this.$refs.inputHidden.focus(); // oWeekPicker选择日期后执行回调函数getChangeTime，在回调函数内执行这行代码，目的是将焦点放到el-input上，让日期选择器失去焦点。临时解决了这个BUG
```

css样式
```css
  .dpicker {
      position: relative;
      :deep {
          .input-hidden{
              position: absolute;
              left: 0;
              top: 0;
              z-index: -1;
              width: 20px;
          }
      }
  }
```

**Comment by hoowhoami** [comment]
新的版本在下周才会发布吗？

**Comment by jw-foss** [comment]
> 新的版本在下周才会发布吗？

不出意外周五，如果你比较急，可以尝试用一下 @nightly。或者把我们修复的 commit cherry-pick 一份到你那边发布一个 fork 包使用

**Comment by hoowhoami** [comment]
> > 新的版本在下周才会发布吗？
> 
> 不出意外周五，如果你比较急，可以尝试用一下 @nightly。或者把我们修复的 commit cherry-pick 一份到你那边发布一个 fork 包使用，也可以用 GitHub 上的源码本地编译一次

好的，我等周五的新版本，再次感谢你们的付出。Element Plus非常棒！

**Comment by Delevin888** [comment]
遇到了相同的问题，2.2.0是好的，感谢大佬们的付出。我太菜了，帮不上忙。

**Comment by liumangafei** [comment]
> 破案了 在Drawer中的form表单里 如果有下拉框组件并且有filterable属性时 就会出现这个问题

我也遇到了这个问题：
vue：3.2.47
element-plus：2.3.9

drawer + select + filterable 点击form-item的label文字就会复现这个问题
