### ISSUE TITLE
[Bug Report] [Component] [tree-select] [TreeSelect] The same value cannot be selected at the same time 相同ID 的值不能同时选中

### ISSUE THREAD

**Issue by Otto-J** [element-plus/element-plus#7872]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `版本 100.0.1185.50 (正式版本) (x86_64) / MacOS 10.15`
- Build Tool: `CDN`

### Related Component

- `el-tree-select`
- `el-cascader`

### Reproduction Link

- [tree-select :Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIHNob3cgY2hlY2tib3g6XG4gIHt7dmFsdWV9fVxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgOmRhdGE9XCJkYXRhXCIgbXVsdGlwbGUgc2hvdy1jaGVja2JveCAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoWyBcIjEtMS0xXCIgXSlcblxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIHZhbHVlOiAnMScsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMS0xLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICflvKDkuIknLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzInLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMi0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAn5byg5LiJJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICcyLTInLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMi0yLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICfmnY7lm5snLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzMnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMy0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzMtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzMtMicsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICczLTItMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

- [cascader same value](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIOWcuuaZr+iuvuWumu+8muafkOS6m+S6uuWcqOS4jeWQjOeahOWIhue7hOS4i++8jOW4jOacm+WSjCBzZWxlY3Qg5LiA5qC36IO95aSf6Ieq5Yqo6YCJ5Lit55u45ZCMIElE44CCPGJyPlxuICAgIHt7dmFsdWV9fVxuICA8L2Rpdj5cbiAgPGVsLWNhc2NhZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIFxuICAgICAgICAgICAgICAgOnNob3ctYWxsLWxldmVscz0nZmFsc2UnXG4gICAgICAgICAgICAgICA6b3B0aW9ucz1cImRhdGFcIiBzdHlsZT0nd2lkdGg6MzAwcHgnXG4gICAgICAgICAgICAgICA6cHJvcHM9J2Nhc2NhZGVyUHJvcHMnIC8+XG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBjb25zdCBjYXNjYWRlclByb3BzPXttdWx0aXBsZTp0cnVlLGVtaXRQYXRoOmZhbHNlfVxuXG4gIGNvbnN0IHZhbHVlID0gcmVmKFsgXCIxLTEtMVwiIF0pXG5cbiAgY29uc3QgZGF0YSA9IFtcbiAgICB7XG4gICAgICB2YWx1ZTogJzEnLFxuICAgICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgdmFsdWU6ICcxLTEtMScsXG4gICAgICAgICAgICAgIGxhYmVsOiAn5byg5LiJJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfSxcbiAgICB7XG4gICAgICB2YWx1ZTogJzInLFxuICAgICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgdmFsdWU6ICcyLTEnLFxuICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgdmFsdWU6ICcxLTEtMScsXG4gICAgICAgICAgICAgIGxhYmVsOiAn5byg5LiJJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXSxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIHZhbHVlOiAnMi0yJyxcbiAgICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIHZhbHVlOiAnMi0yLTEnLFxuICAgICAgICAgICAgICBsYWJlbDogJ+adjuWbmycsXG4gICAgICAgICAgICB9LFxuICAgICAgICAgIF0sXG4gICAgICAgIH0sXG4gICAgICBdLFxuICAgIH0sXG4gICAge1xuICAgICAgdmFsdWU6ICczJyxcbiAgICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAge1xuICAgICAgICAgIHZhbHVlOiAnMy0xJyxcbiAgICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIHZhbHVlOiAnMy0xLTEnLFxuICAgICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXSxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIHZhbHVlOiAnMy0yJyxcbiAgICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIHZhbHVlOiAnMy0yLTEnLFxuICAgICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfSxcbiAgXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

v-model 提供默认值

### What is Expected?

相同ID 都可以被选中

### What is actually happening?

相同ID样式展示不同，样式不一致

### Additional comments

_(empty)_

<img width="432" alt="image" src="https://user-images.githubusercontent.com/9958583/169931187-5fe53457-215c-43d3-b027-6ecedc6613ab.png">

**Comment by JeremyWuuuuu** [comment]
ID should have been a unique key, that is just the basic rule.

**Comment by JeremyWuuuuu** [comment]
Just tried to imagine someone in real life has the exact same ID that you have. See how that goes.

**Comment by Otto-J** [comment]
ok. 确实遇到这个场景，人员兼任多个岗位，作为被通知人的编号是唯一的。补充：如果其他人遇到此类问题，可参考 naive ui 的 cascader ，支持相同 value 同时选中
