### ISSUE TITLE
[Bug Report] [Component] [dialog] Dialog里触发MassageBox，MassageBox会被Dialog挡住，index计算不对

### ISSUE THREAD

**Issue by liwenda** [element-plus/element-plus#7873]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.22`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome/101.0.4951.67`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZ1xuICAgIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCJcbiAgICB0aXRsZT1cIlRpcHNcIlxuICAgIHdpZHRoPVwiMzAlXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyBhIG1lc3NhZ2U8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lOiAoKSA9PiB2b2lkKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmUgdG8gY2xvc2UgdGhpcyBkaWFsb2c/JylcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBkb25lKClcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAvLyBjYXRjaCBlcnJvclxuICAgIH0pXG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

import { defineComponent, ref, onMounted } from 'vue'
import { ElMessageBox } from 'element-plus'
export default defineComponent({
  name: 'Leo',
  setup() {
    const currencySelectVisible = ref(false)  
return {
      currencySelectVisible,
    }
  }
})
</script>

<template>
<el-dialog
    v-if="currencySelectVisible"
    v-model="currencySelectVisible"
    append-to-body
    title="审批"
  >
    <span>意见</span>
    <template #footer>
      <span class="dialog-footer">
        <el-button @click="currencySelectVisible = false">取消</el-button>
        <el-button type="primary" @click="handleClose">提交</el-button>
      </span>
    </template>
  </el-dialog>
</template>

### What is Expected?

ElMessageBox index is high dialog index.
ElMessageBox 弹窗高于 dialog弹窗

### What is actually happening?

dialog index is high ElMessageBox index.
dialog 弹窗高于 ElMessageBox 弹窗

### Additional comments

index 计算错误 这两个初始index不是同一种计算方式

**Comment by Zzongke** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZ1xuICAgIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCJcbiAgICB0aXRsZT1cIlRpcHNcIlxuICAgIHdpZHRoPVwiMzAlXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyBhIG1lc3NhZ2U8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lOiAoKSA9PiB2b2lkKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmUgdG8gY2xvc2UgdGhpcyBkaWFsb2c/JylcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBkb25lKClcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAvLyBjYXRjaCBlcnJvclxuICAgIH0pXG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)查看没发现你说的错误

**Comment by liwenda** [comment]
![image](https://user-images.githubusercontent.com/9473350/170186359-fae32d7e-3726-4db8-ab34-5e1d0b3ffde5.png)
![image](https://user-images.githubusercontent.com/9473350/170186672-0c511b65-dd98-48d2-97c3-845a4b49b254.png)
上面得是结果，下面的是代码

**Comment by liwenda** [comment]
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZ1xuICAgIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCJcbiAgICB0aXRsZT1cIlRpcHNcIlxuICAgIHdpZHRoPVwiMzAlXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyBhIG1lc3NhZ2U8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lOiAoKSA9PiB2b2lkKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmUgdG8gY2xvc2UgdGhpcyBkaWFsb2c/JylcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBkb25lKClcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAvLyBjYXRjaCBlcnJvclxuICAgIH0pXG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)查看没发现你说的错误

上面有截图，每次dialog展示的时候都是从el-poper得index开始+1，而massage-box会从2003开始

**Comment by Zzongke** [comment]
> > [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZ1xuICAgIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCJcbiAgICB0aXRsZT1cIlRpcHNcIlxuICAgIHdpZHRoPVwiMzAlXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICA+XG4gICAgPHNwYW4+VGhpcyBpcyBhIG1lc3NhZ2U8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuXG5jb25zdCBoYW5kbGVDbG9zZSA9IChkb25lOiAoKSA9PiB2b2lkKSA9PiB7XG4gIEVsTWVzc2FnZUJveC5jb25maXJtKCdBcmUgeW91IHN1cmUgdG8gY2xvc2UgdGhpcyBkaWFsb2c/JylcbiAgICAudGhlbigoKSA9PiB7XG4gICAgICBkb25lKClcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICAvLyBjYXRjaCBlcnJvclxuICAgIH0pXG59XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)查看没发现你说的错误
> 
> 上面有截图，每次dialog展示的时候都是从el-poper得index开始+1，而massage-box会从2003开始

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG4gIFxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiaGFuZGxlQ2xvc2VcIlxuICAgID5jbGljayB0byBvcGVuIHRoZSBNZXNzYWdlQm94PC9lbC1idXR0b25cbiAgPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cImJvdHRvbS1zdGFydFwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiaG92ZXJcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZ1Zpc2libGVcIlxuICAgIHRpdGxlPVwiVGlwc1wiXG4gICAgd2lkdGg9XCIzMCVcIlxuICAgIDpiZWZvcmUtY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gID5cbiAgICA8c3Bhbj5UaGlzIGlzIGEgbWVzc2FnZTwvc3Bhbj5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IGZhbHNlXCJcbiAgICAgICAgICA+Q29uZmlybTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmU6ICgpID0+IHZvaWQpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oJ0FyZSB5b3Ugc3VyZSB0byBjbG9zZSB0aGlzIGRpYWxvZz8nKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIGRvbmUoKVxuICAgIH0pXG4gICAgLmNhdGNoKCgpID0+IHtcbiAgICAgIC8vIGNhdGNoIGVycm9yXG4gICAgfSlcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kaWFsb2ctZm9vdGVyIGJ1dHRvbjpmaXJzdC1jaGlsZCB7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=) 我在你的模板里复制一份拿出来想实现，但是复现不了你说的bug

**Comment by chenxch** [comment]
fixed.
