### ISSUE TITLE
[Feature Request] [Enhancement] [rate] el-rate与el-form的rules一起使用时的校验不生效

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#7874]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `rate`

## Description

当我把el-rate与el-form一起使用时，el-rate会把我传入的null/undefined转为0，但这样el-form内的校验规则会失效。难道我只能写自定义校验才可以吗？况且自定义校验还不带红※

### Additional comments

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIDptb2RlbD1cIm51bWJlclZhbGlkYXRlRm9ybVwiXG4gICAgbGFiZWwtd2lkdGg9XCIxMDBweFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwiYWdlXCJcbiAgICAgIHByb3A9XCJhZ2VcIlxuICAgICAgOnJ1bGVzPVwiW1xuICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAncmF0ZeagoemqjCcsdHJpZ2dlcjogJ2NoYW5nZScgfSxcbiAgXG4gICAgICBdXCJcbiAgICA+XG4gICAgICA8ZWwtcmF0ZSB2LW1vZGVsPVwibnVtYmVyVmFsaWRhdGVGb3JtLmFnZVwiIC8+XG4gIFxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiPlN1Ym1pdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuXG5jb25zdCBudW1iZXJWYWxpZGF0ZUZvcm0gPSByZWFjdGl2ZSh7XG4gIGFnZTogbnVsbCxcbn0pXG5cbmNvbnN0IHN1Ym1pdEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgaWYgKHZhbGlkKSB7XG4gICAgICBjb25zb2xlLmxvZygnc3VibWl0IScpXG4gICAgfSBlbHNlIHtcbiAgICAgIGNvbnNvbGUubG9nKCdlcnJvciBzdWJtaXQhJylcbiAgICAgIHJldHVybiBmYWxzZVxuICAgIH1cbiAgfSlcbn1cblxuY29uc3QgcmVzZXRGb3JtID0gKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XG4gIGlmICghZm9ybUVsKSByZXR1cm5cbiAgZm9ybUVsLnJlc2V0RmllbGRzKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by btea** [comment]
You can use a custom validator, [for example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIDpydWxlcz1cInJ1bGVzXCJcbiAgICA6bW9kZWw9XCJudW1iZXJWYWxpZGF0ZUZvcm1cIlxuICAgIGxhYmVsLXdpZHRoPVwiMTAwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtXG4gICAgICBsYWJlbD1cImFnZVwiXG4gICAgICBwcm9wPVwiYWdlXCJcbiAgICA+XG4gICAgICA8ZWwtcmF0ZSB2LW1vZGVsPVwibnVtYmVyVmFsaWRhdGVGb3JtLmFnZVwiIC8+XG4gIFxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiPlN1Ym1pdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZSh7XG4gIGFnZTogW3tyZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ3JhdGXmoKHpqownLCB2YWxpZGF0b3I6IChydWxlLCB2YWx1ZSkgPT4ge1xuICAgIHJldHVybiB2YWx1ZSAhPT0gMFxuICB9fV1cbn0pXG5cbmNvbnN0IG51bWJlclZhbGlkYXRlRm9ybSA9IHJlYWN0aXZlKHtcbiAgYWdlOiBudWxsLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by PeyFon** [comment]
> You can use a custom validator, [for example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIDpydWxlcz1cInJ1bGVzXCJcbiAgICA6bW9kZWw9XCJudW1iZXJWYWxpZGF0ZUZvcm1cIlxuICAgIGxhYmVsLXdpZHRoPVwiMTAwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtXG4gICAgICBsYWJlbD1cImFnZVwiXG4gICAgICBwcm9wPVwiYWdlXCJcbiAgICA+XG4gICAgICA8ZWwtcmF0ZSB2LW1vZGVsPVwibnVtYmVyVmFsaWRhdGVGb3JtLmFnZVwiIC8+XG4gIFxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShmb3JtUmVmKVwiPlN1Ym1pdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZXNldEZvcm0oZm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZSh7XG4gIGFnZTogW3tyZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ3JhdGXmoKHpqownLCB2YWxpZGF0b3I6IChydWxlLCB2YWx1ZSkgPT4ge1xuICAgIHJldHVybiB2YWx1ZSAhPT0gMFxuICB9fV1cbn0pXG5cbmNvbnN0IG51bWJlclZhbGlkYXRlRm9ybSA9IHJlYWN0aXZlKHtcbiAgYWdlOiBudWxsLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

The verification still exists after the value is changed。and use the validateField method

**Comment by PeyFon** [comment]
I think it's a tradeoff question

**Comment by HeftyKoo** [comment]
> I think it's a tradeoff question

Agree
