### ISSUE TITLE
[Bug Report] [Component] [tree-v2] 升级2.2.2版本后,Tree-V2与el-form-item结合时checkBox选中失效

### ISSUE THREAD

**Issue by li936393** [element-plus/element-plus#7875]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.9`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-tree-v2`

### Reproduction Link

[CodePen](https://codepen.io/li936393/pen/QWOJXKa)

### Steps to reproduce

2.1.4版本升级至2.2.0版本后,el-form-item与Tree-V2结合使时,Tree-v2控件的checkBox失效，详见例子https://codepen.io/li936393/pen/QWOJXKa

### What is Expected?

Tree-V2控件能正常使用

### What is actually happening?

Tree-V2控件无法正常选中

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Thank you for your feedback, we will investigate and fix it as soon as possible, please use version `2.1.11` first.

**Comment by chenxch** [comment]
#7450 We will align it as soon as possible to troubleshoot and fix it.

**Comment by litt1e-p** [comment]
same bug, v2.1.11 works well

**Comment by chenxch** [comment]
#7956
