### ISSUE TITLE
[Feature Request] playground中cdn.jsdelivr.net无法访问, 希望兼容其他可用源

### ISSUE THREAD

**Issue by cn-troy** [element-plus/element-plus#7889]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

成都电信无法访问cdn.jsdelivr.net, 
是否可以考虑做个兼容切换为fastly.jsdelivr.net, 比如 https://github.com/PipecraftNet/jsdelivr-auto-fallback

### Additional comments

_(empty)_

**Comment by yzqdev** [comment]
fixed in https://github.com/element-plus/element-plus-playground/commit/f0a0436dbd69fc15cf157f08980cfcc9433a79b8

**Comment by yyyzhen** [comment]
打开控制台，找到存 localstorage 的地方，prefer-cdn 这条可以控制 CDN 地址，有这三个值【unpkg、jsdelivr-fastly、jsdelivr】，你可以试试

**Comment by tolking** [comment]
> 打开控制台，找到存 localstorage 的地方，prefer-cdn 这条可以控制 CDN 地址，有这三个值【unpkg、jsdelivr-fastly、jsdelivr】，你可以试试

Please refer to use, or go to the [element-plus-playground](https://github.com/element-plus/element-plus-playground) for more help.
