### ISSUE TITLE
[Feature Request] [Enhancement] [menu] el-menu收缩展开问题

### ISSUE THREAD

**Issue by ZhBano** [element-plus/element-plus#7896]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `menu`

## Description

```vue
<script setup>
  const collapsed = ref(false)
  const siderWidth = computed(() => (collapsed.value ? '64px' : '200px'))
</script>

<template>
   <div class="common-layout">
    <el-container class="container">
      <el-aside :width="siderWidth">
        <MenuCom :collapsed="collapsed" />
      </el-aside>
      <el-container>
        <el-header>header</el-header>
        <el-main>main</el-main>
      </el-container>
    </el-container>
  </div>
</template>
```

### Additional comments

效果就是收缩展开会不流畅

**Comment by SmallSample** [comment]
去掉菜单组件中的Settings图标，或者替换成其他的

**Comment by ZhBano** [comment]
> 去掉菜单组件中的设置图标，或者替换成其他的

暂时没有用到图标

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tolking** [comment]
为什么要为 el-aside配置宽度？这样在 el-menu 折叠的同时 el-aside 也会折叠。但 el-aside 没有一个过渡效果，所以一快一慢引起这种错觉。可以尝试为 el-aside 增加过度效果，将会好得多

```css
.el-aside { transition: var(--el-transition-all); }
```

当然更加优雅的做法或许是取消对 el-aside 的宽度控制，通过菜单撑开 aside 宽度。[参考文档](https://element-plus.org/zh-CN/component/menu.html#%E5%8F%AF%E6%8A%98%E5%8F%A0%E7%9A%84%E8%8F%9C%E5%8D%95)

``` css
.el-aside { width: auto; }
.el-menu { width: 200px; }
```

**Comment by SmallSample** [comment]
https://user-images.githubusercontent.com/34450888/170462060-082c547c-3ac3-40c2-b776-1cdc94ec81fc.mp4

@tolking

**Comment by ZhBano** [comment]
> 为什么要为 el-aside配置宽度？这样在 el-menu 折叠的同时 el-aside 也会折叠。但 el-aside 没有一个过渡效果，所以一快一慢引起这种错觉。可以尝试为 el-aside 增加过度效果，将会好得多
> 
> ```css
> .el-aside { transition: var(--el-transition-all); }
> ```
> 
> 当然更加优雅的做法或许是取消对 el-aside 的宽度控制，通过菜单撑开 aside 宽度。[参考文档](https://element-plus.org/zh-CN/component/menu.html#%E5%8F%AF%E6%8A%98%E5%8F%A0%E7%9A%84%E8%8F%9C%E5%8D%95)
> 
> ```css
> .el-aside { width: auto; }
> .el-menu { width: 200px; }
> ```

试了给.el-menu加宽度直接就不收缩了 固定200px了

**Comment by tolking** [comment]
``` css
.el-menu:not(.el-menu--collapse) { width: 200px; }
```

**Comment by tolking** [comment]
@SmallSample 我看了下，Settings icon 中包含了比较多的路径信息。可能是需要优化

另外打包过后也是如此吗？

**Comment by SmallSample** [comment]
是的 @tolking

**Comment by q1971595727** [comment]
点击二级栏目，然后展开收起 就会变得很卡顿

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
