### ISSUE TITLE
[Feature Request] [Enhancement] 在el-form表单上设置disabled为true后,,表单内部的el-select和el-input无法获取自身的disabled为false的值

### ISSUE THREAD

**Issue by zc-write-code** [element-plus/element-plus#7903]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `All`

## Description

el-select,el-input等组件在el-form中可以单独设置是否禁用

### Additional comments

_(empty)_

**Comment by HeftyKoo** [comment]
想了解一下使用场景是怎样的？

**Comment by zc-write-code** [comment]
就是有一个表单,,有些值是不能改的,,有些值是根据状态修改,,但是能修改的不多,而不修改的值更多,所以我就想在form上设置disabled,,在要修改的上设置disabled=false,但是没有作用...这种少还行,多的话就很麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Feature Request] [Enhancement] 在el-form表单上设置disabled为true后,,表单内部的el-select和el-input无法获取自身的disabled为false的值 (Issue #7903)





 
想了解一下使用场景是怎样的？

**Comment by HeftyKoo** [comment]
Duplicate of #7655
