### ISSUE TITLE
[Bug Report] [Component] [tree-select] el-tree-select字典数据延迟[异步]加载，控件label显示异常

### ISSUE THREAD

**Issue by lwzh200907** [element-plus/element-plus#7917]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.1.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwibG9hZFZhbHVlXCI+5Yqg6L295pWw5o2uPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjbGVhclZhbHVlXCI+5riF56m65pWw5o2uPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VWYWx1ZVwiPuS/ruaUueaVsOaNrjwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbiAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybVwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJkZXB0MVwiPlxuICAgICAgPGVsLXRyZWUtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLmRlcHQxXCIgOmRhdGE9XCJkaWN0TGlzdFwiIGNoZWNrLXN0cmljdGx5IG11bHRpcGxlIHNob3ctY2hlY2tib3gvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHtyZWYsIHJlYWN0aXZlfSBmcm9tICd2dWUnXG5cbi8vIGRvIG5vdCB1c2Ugc2FtZSBuYW1lIHdpdGggcmVmXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBkZXB0MTogdW5kZWZpbmVkLFxuICBkZXB0MjogdW5kZWZpbmVkLFxufSlcblxuY29uc3QgZGljdExpc3QgPSByZWYoW10pXG5cbmZ1bmN0aW9uIGxvYWRWYWx1ZSgpIHtcbiAgT2JqZWN0LmFzc2lnbihmb3JtLCB7XG4gICAgZGVwdDE6IFsnMS0xJ10sXG4gIH0pXG4gIGlmIChkaWN0TGlzdC52YWx1ZS5sZW5ndGggPT0gMCl7XG4gICAgZGljdExpc3QudmFsdWUgPSBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMS0xJyxcbiAgICAgICAgbGFiZWw6ICfljZXkvY0xLTEnLFxuICAgICAgfVxuICAgIF1cbiAgfVxuXG4gIGNvbnNvbGUubG9nKGRpY3RMaXN0LnZhbHVlKVxufVxuXG5mdW5jdGlvbiBjbGVhclZhbHVlKCkge1xuICBmb3IgKGxldCBuYW1lIGluIGZvcm0pIHtcbiAgICBpZiAoZm9ybS5oYXNPd25Qcm9wZXJ0eShuYW1lKSkge1xuICAgICAgZm9ybVtuYW1lXSA9IG51bGwgLy8g5pWw5YC857G75Z6L5LiN5ZCMLCDkuI3og73orr7nva7miJDlrZfnrKbkuLIgJydcbiAgICB9XG4gIH1cbiAgY29uc29sZS5sb2coZGljdExpc3QudmFsdWUpXG59XG5cbmZ1bmN0aW9uIGNoYW5nZVZhbHVlKCkge1xuICBPYmplY3QuYXNzaWduKGZvcm0sIHtcbiAgICBkZXB0MTogWycxLTEnXSxcbiAgfSlcbiAgZGljdExpc3QudmFsdWUgPSBbXG4gICAge1xuICAgICAgdmFsdWU6ICcxJyxcbiAgICAgIGxhYmVsOiAn5Y2V5L2NMScsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgdmFsdWU6ICcxLTEnLFxuICAgICAgICAgIGxhYmVsOiAn5Y2V5L2NMS0xJyxcbiAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICfljZXkvY0xLTEtMSdcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgdmFsdWU6ICcxLTInLFxuICAgICAgICAgIGxhYmVsOiAn5Y2V5L2NMS0yJyxcbiAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICfljZXkvY0xLTEtMSdcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgdmFsdWU6ICcxLTMnLFxuICAgICAgICAgIGxhYmVsOiAn5Y2V5L2NMS0zJyxcbiAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICfljZXkvY0xLTEtMSdcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgXVxuICAgICAgICB9XG4gICAgICBdXG4gICAgfVxuICBdXG4gIGNvbnNvbGUubG9nKGRpY3RMaXN0LnZhbHVlKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG5cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 点击【加载数据】按钮，模拟表单load数据，此时为了反显，模拟字典数据为{value,label}
2. 点击【清空数据】按钮，表单值清空
2. 点击【修改数据】按钮，模拟点击控件，此时需要加载完整字典
3. 点击【清空数据】按钮，表单值清空
4. 再次点击【加载数据】按钮，修改表单值，但此时因已加载完整字典，无需再次加载字典
5. 此时el-tree-select控件显示值出现问题，未正确反显，但下拉树中已选择正常

### What is Expected?

延迟加载data字典数据后，修改控件值，label能正常显示
注意：如果表单值对应的字典条目为下拉树第一级节点，label显示正常

### What is actually happening?

延迟加载data字典后，修改控件值，label未能正确反显

### Additional comments

为了实现字典延迟【异步】加载相关功能，需要如上定制，请确认此为使用方式不正确，还是控件本身存在bug。
辛苦

![image](https://user-images.githubusercontent.com/9744089/170624204-450024bc-3e90-4954-9057-df1b36533919.png)

**Comment by yujinpan** [comment]
请尝试将 `render-after-expand` 打开，或者设置 `default-expanded-keys` 包含当前值。

**Comment by lwzh200907** [comment]
以上两种方案经过测试，都未解决，还请再给确认处理下

**Comment by yujinpan** [comment]
确实有此问题，请等待后续修复。

**Comment by yujinpan** [comment]
And some other issues in this playground：

- [ ] checkbox style error in form component
- [ ] checkbox can not select with not leaf node
