### ISSUE TITLE
[Bug Report] [Component] Input can't be focused, if it is put in a popover which wraps with dialog.

### ISSUE THREAD

**Issue by ruinb0w** [element-plus/element-plus#7918]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/101.0.4951.64`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-popover`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHNob3dfZGlhbG9nID0gcmVmKGZhbHNlKTtcbmNvbnN0IGlucHV0X3ZhbHVlID0gcmVmKFwiXCIpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXY+ZWxlbWVudC1wbHVzIHZlcnNpb246IHt7RXBWZXJzaW9ufX08L2Rpdj5cbiAgICA8ZGl2PnZ1ZSB2ZXJzaW9uOiB7e3Z1ZVZlcnNpb259fTwvZGl2PlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwic2hvd19kaWFsb2cgPSAhc2hvd19kaWFsb2dcIj5cbiAgICAgIHRvZ2dsZSBkaWFsb2dcbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJzaG93X2RpYWxvZ1wiIHRpdGxlPVwiZGlhbG9nXCI+XG4gICAgICBpbnB1dCBpbiBkaWFsb2cgY2FuIGJlIGZvY3VzZWQuXG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0X3ZhbHVlXCIvPlxuICAgICAgXG4gICAgICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiaG92ZXJcIj5cbiAgICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgPGVsLWJ1dHRvbj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICBpZiBwb3BvdmVyIGlzIHdyYXBlZCB3aXRoIGRpYWxvZywgaW5wdXQgY2FuJ3QgYmUgZm9jdXNlZC5cbiAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dF92YWx1ZVwiIC8+XG4gICAgICA8L2VsLXBvcG92ZXI+XG4gICAgPC9lbC1kaWFsb2c+XG4gICAgXG4gICAgPGVsLXBvcG92ZXIgdHJpZ2dlcj1cImhvdmVyXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICAgIDxlbC1idXR0b24+aW5wdXQgaW4gcG9wb3ZlciBjYW4gYmUgZm9jdXNlZDwvZWwtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0X3ZhbHVlXCIgLz5cbiAgICAgIDwvZWwtcG9wb3Zlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

just try the reproduction.

### What is Expected?

input in popover can be focused.

### What is actually happening?

If a popover is wrapped with a dialog, the input can't be focused.

### Additional comments

element-plus 2.1.16 is fine.

**Comment by Zerounary** [comment]
so am I.

**Comment by chenxch** [comment]
fixed.
