### ISSUE TITLE
[Bug Report] [Style] Color mix level generator missing values

### ISSUE THREAD

**Issue by arnauddoub** [element-plus/element-plus#7922]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome 98`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgaDEge1xuICAgIGNvbG9yOiB2YXIoLS1lbC1jb2xvci1wcmltYXJ5LWxpZ2h0LTIpO1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Example use css variable `--el-color-primary-light-2` not work but `--el-color-primary-light-3` work.
In the file `element-plus/theme-chalk/src/common/var.scss` i see a generation from 1 to 9
`@each $type in $types {
  @for $i from 1 through 9 {
    @include set-color-mix-level($type, $i, 'light', $color-white);
  }
}`

### What is Expected?

Defined the `--el-color-primary-light-2` variable in `:root`

### What is actually happening?

The variable does not exist

### Additional comments

_(empty)_

**Comment by YunYouJun** [comment]
Logic is here:

https://github.com/element-plus/element-plus/blob/936a20d3a229f4d076b5883a5fba53d709228a2a/packages/theme-chalk/src/mixins/_var.scss#L24-L29

The levels we use throughout our system are only `3 5 7 8 9`, because they have enough contrast.
So I think you can use 3 instead of 2.

@huangzhongzhong Do you have anything to say about design specs?

**Comment by YunYouJun** [comment]
In fact, `light-2` is already generated, you just need to manually set it to add it to the css var.

```scss
:root {
  --el-color-primary-light-2: #{map.get($--colors, 'primary', 'light-2')};
}
```

Due to size considerations, it is not placed in css by default.
