### ISSUE TITLE
[Bug Report] [Style] [button] <el-button type="primary">Primary</el-button> 在手机端的Chrome浏览器 默认的样式失效

### ISSUE THREAD

**Issue by 1648045459** [element-plus/element-plus#7926]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Linux; Android 10; NOH-AN00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-button`

### Reproduction Link

[Github Repo](https://github.com/1648045459/demo-elment-plus-button/blob/master/src/views/Login/Login.vue)

### Steps to reproduce

<el-button type="primary">Primary</el-button>

在PC端浏览器 按钮正常显示蓝色的按钮。在手机端的浏览器显示灰色的。

### What is Expected?

<el-button type="primary">Primary</el-button>
在PC端浏览器有效的组件样式，同样在移动端的浏览器同步有效

### What is actually happening?

<el-button type="primary">Primary</el-button>
在移动端浏览器显示灰色

### Additional comments

测试设备：华为 mate40 pro手机
浏览器：Chrome浏览器

**Comment by chenxch** [comment]
你可以访问下官网看看是否正常，如果样式也失效你可以检查下你的chrome版本是否支持css变量，或者通过chrome://inspect/#devices 调试进行排查看下

**Comment by tolking** [comment]
可能与 #7914 相关。你可以尝试 [访问这里](https://preview-7914-element-plus.surge.sh/) 按钮颜色应该会正常显示

**Comment by lggboy** [comment]
官网文档支持的浏览器版本
![image](https://user-images.githubusercontent.com/24926766/170870971-49c45921-ccff-4974-bab7-f5cca07a9795.png)
我的Edge版本是81，在2.1.11版本时，按钮显示都正常，升级到2.2.1版本后按钮都显示成灰色了，type="primary"也显示的是灰色

**Comment by chenxch** [comment]
:not()
![image](https://user-images.githubusercontent.com/23251408/170871416-b13d5325-4de2-436b-b140-0d09b3f02b08.png)

**Comment by sxzz** [comment]
等待下一个版本发版
