### ISSUE TITLE
[Feature Request] [自定义命名空间]在wabpack采用官网的配置方案失败，请问webpack框架是否可以正常使用，如果有，请问有相应案例提供吗

### ISSUE THREAD

**Issue by polmqwaz** [element-plus/element-plus#7927]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `N/A`

## Description

项目框架用了qiankun vue element-plus，由于项目A是vue3.0 + elementplus v1.6+，项目B是vue3.2 + elementplus2.2.2，两个项目采用不同的版本导致样式混乱。
预计尝试用官方提供的namespace进行样式隔离，但使用时class前缀有变化，但是相同class的css样式匹配。
官网提供的是vite起的项目，所以请问webpack框架是否可以正常使用，如果有，请问有相应案例提供吗？谢谢

### Additional comments

_(empty)_

**Comment by Xdy1579883916** [comment]
在vue.config.js里面这样设置

`
css: {
    loaderOptions: {
      scss: {
        additionalData: `@use "@/styles/element/index.scss" as *;`,
      },
    },
  },

`

**Comment by polmqwaz** [comment]
> 在vue.config.js里面这样设置
> 
> css: { loaderOptions: { scss: { additionalData: `@use "@/styles/element/index.scss" as *;`, }, }, },

![image](https://user-images.githubusercontent.com/27537320/170812034-bfe6d651-0fec-4d90-b7b2-d9c79f6c553a.png)
因为版本的问题，我是这样配的，没有效果。我升版本试试

**Comment by sxzz** [comment]
![Uploading image.png…]()
