### ISSUE TITLE
[Bug Report] [Component] el-dialog打开后，el-popover显示后，内容的input无法获取焦点，点击input输入框没有反应

### ISSUE THREAD

**Issue by LIUSHUAI2018** [element-plus/element-plus#7928]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.2.2`
- Browser / OS: `chrome/101.0.4951.41`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-popover`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGRpdj5cbiAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9wZW5cIj7miZPlvIA8L2VsLWJ1dHRvbj5cbiAgPGVsLWRpYWxvZyBkZXN0cm95LW9uLWNsb3NlIHYtbW9kZWw9XCJpc1Nob3dcIj5cbiAgICA8ZWwtcG9wb3ZlclxuICAgICAgICBwbGFjZW1lbnQ9XCJib3R0b20tc3RhcnRcIlxuICAgICAgICA6d2lkdGg9XCI1NDBcIlxuICAgICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICA8ZWwtaW5wdXQgICBwbGFjZWhvbGRlcj1cIueCueWHu+mAieaLqeWbvuagh1wiIHJlYWRvbmx5PlxuICAgICAgICA8L2VsLWlucHV0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICA8ZWwtaW5wdXRcbiAgICAgICAgICAgICAgdi1tb2RlbD1cImljb25OYW1lXCJcbiAgICAgICAgICAgICAgY2xlYXJhYmxlXG4gICAgICAgICAgICAgIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5Zu+5qCH5ZCN56ewXCJcbiAgICAgICAgICA+XG4gICAgICAgICAgPC9lbC1pbnB1dD5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9lbC1wb3BvdmVyPlxuICA8L2VsLWRpYWxvZz5cbjwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCA+XG5pbXBvcnQge3JlZn0gZnJvbSBcInZ1ZVwiO1xuY29uc3QgaXNTaG93ID0gcmVmKGZhbHNlKVxuY29uc3QgaWNvbk5hbWUgPSByZWYoJycpXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBpc1Nob3cudmFsdWUgPSB0cnVlXG59XG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cblxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

2.2.0版本没有，2.2.1版本有

### What is Expected?

el-diaglo里面的el-popover里面的el-input可以正常使用

### What is actually happening?

el-input无法获取焦点

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/37928107/170669065-5a63a829-2ed5-4c9e-b4d1-5e6a47e722ba.png)

**Comment by lylyong** [comment]
Same question!!!
