### ISSUE TITLE
[Bug Report] [Component] [drawer] Drawer 无法复制里面的内容

### ISSUE THREAD

**Issue by JCAlways** [element-plus/element-plus#7929]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome/102.0.5005.62`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

在文档中 打开Drawer内容也无法复制

### What is Expected?

可以复制里面的内容

### What is actually happening?

无法复制

### Additional comments

_(empty)_

**Comment by JCAlways** [comment]
2.2.0版本是可以复制的 2.2.2版本无法复制

**Comment by hoowhoami** [comment]
https://github.com/element-plus/element-plus/issues/7871
应该是焦点的问题，暂时退回2.2.0，等待下个版本发布修复吧。

**Comment by sxzz** [comment]
Duplicate of #7871

**Comment by novemberzhuababa** [comment]
现在用的2.2.0也不行，降版本也不可以选中

**Comment by hoowhoami** [comment]
确保你使用的2.2.0版本
删除node_modules和package-lock.json重新构建试一下
我这边是可以复制的
![image](https://user-images.githubusercontent.com/84499551/171568785-d273bf93-4ee4-4089-9e19-859455f8d934.png)

**Comment by novemberzhuababa** [comment]
![image](https://user-images.githubusercontent.com/89788230/171570131-9a4bd129-1467-42de-93ae-1a98569bc785.png)
![image](https://user-images.githubusercontent.com/89788230/171570166-bedde3e0-63da-4f44-a2e5-18187c249cad.png)

**Comment by novemberzhuababa** [comment]
![image](https://user-images.githubusercontent.com/89788230/171570217-9f6058c9-95fb-4498-a4a9-d7e5d7f21dfe.png)
![image](https://user-images.githubusercontent.com/89788230/171570237-ec4fc48c-2e9a-4529-8b25-0b8d0c3a0ad2.png)
还是没办法复制

**Comment by hoowhoami** [comment]
![image](https://user-images.githubusercontent.com/84499551/171570658-62d6f9a5-2ec7-40f4-9140-b385e7fd7783.png)

da'x大兄弟，把这个符号去掉，虽然我也是后端程序员刚开始转前端，但是这个符号应该是表示2.2.x的意思吧，所以你用的应该还是2.2.2

**Comment by wang456466** [comment]
你这个问题解决了吗？

**Comment by novemberzhuababa** [comment]
解决了

**Comment by jkcaptain** [comment]
如果是弹窗中的 Drawer ，或许设置 **append-to-body** 会有效。
