### ISSUE TITLE
Bug with slot of el-table-column

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#793]
When use `scope.row.xxx.yyy` in el-table-column, There is an error: TypeError: Cannot read property 'yyy' of undefined. I can use `scope.row.xxx?.yyy`. It seems a bug with lifecycle.

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by justwiner** [comment]
Because when rendering for the first time, the multi-level header will be generated according to the structure of `el-table-column`.
Here, for the moment, I use `try-catch` to resolve it.
```js
render() {
    try {
      return h(
        'div',
        this.$slots.default?.({
          store: {},
          _self: {},
          column: {},
          row: {},
          $index: -1,
        }),
      )
    } catch {
      return h('div')
    }
  },
```
It doesn't affect the rendering of the page
