### ISSUE TITLE
[Bug Report] [Style] [button]  浏览器显示button,样式失效

### ISSUE THREAD

**Issue by jxsgood** [element-plus/element-plus#7930]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome 86.0.4240.198`
- Build Tool: `Other`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

使用的是360急速浏览器,版本号：13.5.2022.0,Chrom内核版本：86.0.4240.198
直接打开官网页面https://element-plus.gitee.io/zh-CN/component/button.html
button全部无背景色,估计还有其他控件,没来得及详测.

### What is Expected?

官网推荐Chrome ≥ 64就可以了

### What is actually happening?

希望不是我个人遇到,你们测试过吗?

### Additional comments

_(empty)_

**Comment by Xdy1579883916** [comment]
你好，我也遇到了这个问题,我是这样解决的

```diff
@include b(button) {
-  &:not(.is-text, .is-link, .#{$namespace}-button--text){
+  &:not(.is-text):not(.is-link):not(.#{$namespace}-button--text) {
    background-color: getCssVar('button', 'bg-color');
    border: getCssVar('border');
    border-color: getCssVar('button', 'border-color');

    &:hover,
    &:focus {
      color: getCssVar('button', 'hover', 'text-color');
      border-color: getCssVar('button', 'hover', 'border-color');
      background-color: getCssVar('button', 'hover', 'bg-color');
      outline: none;
    }

    &:active {
      color: getCssVar('button', 'active', 'text-color');
      border-color: getCssVar('button', 'active', 'border-color');
      background-color: getCssVar('button', 'active', 'bg-color');
      outline: none;
    }

    &:focus-visible {
      border-color: transparent;
      outline: 2px solid getCssVar('button', 'border-color');
      outline-offset: 1px;
    }
  }
}
```

这是因为360浏览器不支持not()里面用逗号隔开这种方式，经初步排查，只有button组件以及于button的相关组件有这个问题，我覆盖了一下官方的button样式，但是还是希望官方这里能做一下简单的修改

**Comment by Xdy1579883916** [comment]
@YunYouJun

**Comment by YunYouJun** [comment]
Fixed in #7914.

Just wait next patch version. Thanks.

**Comment by kekeqy** [comment]
> Fixed in #7914.
> 
> Just wait next patch version. Thanks.

啥时候能发布新版本啊？？？

**Comment by YunYouJun** [comment]
I guess we will have a new release in next week.

Right? @jw-foss

**Comment by kekeqy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
