### ISSUE TITLE
[Bug Report] [Style] [All] Custom theme is usable with development server, but no effect after build.

### ISSUE THREAD

**Issue by Danny-Yxzl** [element-plus/element-plus#7932]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-77d8nd?file=/vite.config.js)

### Steps to reproduce

While testing with `vite serve`, the custom theme defined in `@/assets/color.scss` is available, but after I build the project with `vite build`, it doesn't work.

### What is Expected?

The custom theme can also use after build with vite.

### What is actually happening?

It doesn't work at all.

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
You need `import "element-plus/theme-chalk/src/index.scss";` not `import "element-plus/theme-chalk/index.css";`

**Comment by Danny-Yxzl** [comment]
> element-plus/theme-chalk/index.css

I'm sorry, but which file are you talking about? I'm not able to find what are your suggestion refering to ::sad

**Comment by chenxch** [comment]
main.js
```
import "element-plus/theme-chalk/src/index.scss";
```

**Comment by Danny-Yxzl** [comment]
> main.js
> 
> ```
> import "element-plus/theme-chalk/src/index.scss";
> ```

Fantastic! All I could see is thanks - It really works! 

Could you explain in detail why?

**Comment by chenxch** [comment]
Because `*.css` is the compiled product, the `variable` you change is `*.scss`, so you need to import *.scss, and generate *.css of application variables by compiling
