### ISSUE TITLE
[Bug Report] [Component] [table-v2] Table-v2 AutoResizer with manual import: failed to resolve css file

### ISSUE THREAD

**Issue by jones1008** [element-plus/element-plus#7933]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[https://stackblitz.com/edit/vitejs-vite-bqeywj?file=src/App.vue](https://stackblitz.com/edit/vitejs-vite-bqeywj?file=src/App.vue)
Sorry that I used Stackblitz as the link for the minimal reproduction... I had no luck with CodeSandbox or the ElementPlus Playground setting up the manual import from element-plus, so I switched to Stackblitz and got it working right away. Hope this is okay...

### Steps to reproduce

1. Setup Element-Plus to manually import the dependencies (see [https://element-plus.org/en-US/guide/quickstart.html#manually-import](https://element-plus.org/en-US/guide/quickstart.html#manually-import))
2. Use the `el-auto-resizer` component as a wrapper for `el-table-v2` as described here: [https://element-plus.org/en-US/component/table-v2.html#auto-resizer](https://element-plus.org/en-US/component/table-v2.html#auto-resizer)

### What is Expected?

`unplugin-element-plus` automatically resolves `ElAutoResizer`.

### What is actually happening?

Manual import of `ElAutoResizer`:
```javascript
import { ElAutoResizer } from "element-plus"
```

throws the following error:
```
Failed to resolve import "element-plus/es/components/auto-resizer/style/css"
```

### Additional comments

It seems that the CSS of the auto-resizer component is not where it should be for the `unplugin-element-plus` library to resolve it automatically. Is there even any css for this component? Further digging shows that the source for the `el-auto-resizer` component is in `node_modules\element-plus\es\components\table-v2\src`.

**Comment by btea** [comment]
`unplugin-element-plus`  maybe should ignore `el-auto-resizer`  @sxzz

**Comment by qq923249284** [comment]
Is there a temporary solution

**Comment by KarolMilewski** [comment]
Got a similar problem.
Using Auto import `unplugin-vue-components unplugin-auto-import`

```sh
/* unplugin-vue-components disabled */import __unplugin_components_10 from 'MyTable.vue';
2  |  import { ElAutoResizer as __unplugin_components_9 } from 'element-plus/es';import 'element-plus/es/components/auto-resizer/style/index';
   |                                                                                     ^
3  |  import { ElTableV2 as __unplugin_components_8 } from 'element-plus/es';import 'element-plus/es/components/table-v2/style/index';
4  |  import { ElRow as __unplugin_components_7 } from 'element-plus/es';import 'element-plus/es/components/row/style/index';
```

**Comment by YujiaCheng1996** [comment]
same problem!

**Comment by dblazhkun** [comment]
I have fixed this on the `unplugin-vue-components` side.
Waiting for a new release.
