### ISSUE TITLE
[Bug Report] [Style] [input] 点击 el-input 组件获取焦点后输入框圆角出现毛刺

### ISSUE THREAD

**Issue by weisiqian** [element-plus/element-plus#7952]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `101.0.4951.67 (正式版本) （64 位） (cohort: Stable)  / windows10`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIC5lbC1pbnB1dF9fd3JhcHBlciB7XG4gICAgYm9yZGVyLXJhZGl1czogMnB4ICFpbXBvcnRhbnQ7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

设置输入框的圆角为 2px，
```
<style>
  .el-input__wrapper {
    border-radius: 2px !important;
  }
</style>
```

点击输入框，输入框进入聚焦状态，聚焦状态有时候输入框的圆角就会出现毛刺，有时候不会出现，具有随机性。出现时的样式可以查看下面的截图，查看截图时不能缩放，毛刺很小，缩放的时候看不到。 

![截图一](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/75c5760540b040a8b64c5d64b1dd82ae~tplv-k3u1fbpfcp-watermark.image?)

![截图二](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5a4f45262d3646cba1a078aa5ab2a2a7~tplv-k3u1fbpfcp-watermark.image?)

排查 el-input 组件的样式发现是因为组件的边框是使用 box-shadow 实现的，所以会导致出现毛刺

相关样式：

![CSS样式代码](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e583f5a4e49b4fc882befa9ea61f6904~tplv-k3u1fbpfcp-watermark.image?)

```
box-shadow: 0 0 0 1px var(--el-input-border-color,var(--el-border-color)) inset;
```

将边框改为使用 border 属性实现就不会出现毛刺。

### What is Expected?

el-input 组件获取焦点后输入框圆角不出现毛刺

### What is actually happening?

el-input 组件获取焦点后输入框圆角出现毛刺

### Additional comments

在公司多台电脑上都出现毛刺，排除显示器的问题，查看样式后可以确定是由 box-shadow 导致。

**Comment by zhangyupeng233** [comment]
我也遇到了  请问解决了吗

**Comment by chenxch** [comment]
same: #7034
