### ISSUE TITLE
[Feature Request] [自定义命名空间]ElMessageBox组件单独引用，namespace依然是 el 

### ISSUE THREAD

**Issue by polmqwaz** [element-plus/element-plus#7970]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `N/A`

## Description

ElMessageBox组件单独引用，namespace依然是 el ,导致无样式匹配

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/27537320/170870355-677c87c1-f130-4df3-a70d-86ffe4ef3fcd.png)

**Comment by polmqwaz** [comment]
![image](https://user-images.githubusercontent.com/27537320/170871995-b9cce331-9d81-4674-8845-0debc3de7a5b.png)
el-table，省略tooltip显示的el-popper的namespace也是默认的el，而不是设定的ep
![image](https://user-images.githubusercontent.com/27537320/170872044-faa086b3-fb5b-4caf-ac60-3d515b872515.png)

**Comment by 695648896** [comment]
@polmqwaz 请问解决了嘛，我也碰到了同样的问题

**Comment by ywl913** [comment]
请问解决了嘛，我也碰到了同样的问题

**Comment by yp199618** [comment]
遇到了相同的问题

**Comment by tianshiyang** [comment]
同样的问题求解决方式
