### ISSUE TITLE
[Bug Report] [Component] [table, tabs] 在 el-tabs 下使用 el-table 设置 height属性后 ，tab切换， table高度会减少

### ISSUE THREAD

**Issue by Ma-XiaoFei** [element-plus/element-plus#7974]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSBcInZ1ZVwiO1xuaW1wb3J0IHR5cGUgeyBUYWJzUGFuZUNvbnRleHQgfSBmcm9tIFwiZWxlbWVudC1wbHVzXCI7XG5pbXBvcnQgVGFibGUgZnJvbSBcIi4vVGFibGUudnVlXCI7XG5pbXBvcnQgVGFibGUyIGZyb20gXCIuL1RhYmxlMi52dWVcIjtcblxuY29uc3QgZGF0YSA9IHJlYWN0aXZlKHtcbiAgYWN0aXZlOiBcIjFcIixcbn0pO1xuXG5jb25zdCBoYW5kbGVDbGljayA9ICh0YWI6IFRhYnNQYW5lQ29udGV4dCwgZXZlbnQ6IEV2ZW50KSA9PiB7XG4gIGNvbnNvbGUubG9nKHRhYiwgZXZlbnQpO1xuICBjb25zb2xlLmxvZyhkYXRhLmFjdGl2ZSk7XG59O1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnNcbiAgICB2LW1vZGVsPVwiZGF0YS5hY3RpdmVcIlxuICAgIHR5cGU9XCJjYXJkXCJcbiAgICBjbGFzcz1cImRlbW8tdGFic1wiXG4gICAgQHRhYi1jbGljaz1cImhhbmRsZUNsaWNrXCJcbiAgPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIjFcIiBuYW1lPVwiMVwiPlxuICAgICAgPFRhYmxlIC8+XG4gICAgPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCIyXCIgbmFtZT1cIjJcIj5cbiAgICAgIDxUYWJsZTIgLz5cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJUYWJsZS52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuY29uc3QgdGFibGVEYXRhID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAgfSwgKHQsIGkpID0+ICh7XG4gIGRhdGU6IGkgKyAxLFxuICBuYW1lOiBcImFzYVwiICsgaSxcbiAgc3RhdGU6IFwic2RcIixcbiAgY2l0eTogXCJzZFwiLFxuICBhZGRyZXNzOiBcInNkXCIsXG4gIHppcDogXCJzZFwiLFxufSkpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIHN0cmlwZSA6ZGF0YT1cInRhYmxlRGF0YVwiIGhlaWdodD1cIjIwMFwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIuihqOagvOS4gFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwi6KGo5qC85LiA6KGo5qC85LiAMlwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwic3RhdGVcIiBsYWJlbD1cIjRcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImNpdHlcIiBsYWJlbD1cIjVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIjZcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInppcFwiIGxhYmVsPVwiN1wiLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBsYW5nPVwibGVzc1wiIHNjb3BlZD48L3N0eWxlPlxuIiwiVGFibGUyLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCB0YWJsZURhdGEgPSBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMCB9LCAodCwgaSkgPT4gKHtcbiAgZGF0ZTogaSArIDEsXG4gIG5hbWU6IFwiYXNhXCIgKyBpLFxuICBzdGF0ZTogXCJzZFwiLFxuICBjaXR5OiBcInNkXCIsXG4gIGFkZHJlc3M6IFwic2RcIixcbiAgemlwOiBcInNkXCIsXG59KSk7XG48L3NjcmlwdD5cblxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZSBzdHJpcGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBoZWlnaHQ9XCIyMDBcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCLooajmoLzkuozkuozkuoxcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIjNcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInN0YXRlXCIgbGFiZWw9XCI0XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJjaXR5XCIgbGFiZWw9XCI1XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCI2XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ6aXBcIiBsYWJlbD1cIjdcIi8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgbGFuZz1cImxlc3NcIiBzY29wZWQ+PC9zdHlsZT5cbiIsIl9vIjp7fX0=)

### Steps to reproduce

切换tab后， table 高度减少， 原因： .el-table__body-wrapper这个div style 上 的 height 计算错误导致

### What is Expected?

高度不变

### What is actually happening?

高度会变

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Fixed in #8690
