### ISSUE TITLE
ElSelect: popper.value.update is not a function error

### ISSUE THREAD

**Issue by acupofspirt** [element-plus/element-plus#799]
If you try to change the width of input(`.el-input__inner`) inside ElSelect component you will get popper error.

Try to `input.style.width = '140px'` and get **_"Uncaught TypeError: t.update is not a function"_**

**packages/select/src/useSelect.ts:403**
![image](https://user-images.githubusercontent.com/1342726/100970445-fb4bda80-3545-11eb-8106-3c9a29508cab.png)

**Comment by JeremyWuuuuu** [comment]
Do you have a demo for me to debug?
Though I think this should be `popper.value?.update?.()`, the code seems not robust

**Comment by vipsunwei** [comment]
我也遇到了类似的问题，el-select ，onfocus的时候  报了个错   
![image](https://user-images.githubusercontent.com/15810277/100973706-fdc62880-3575-11eb-8340-4126345d31d6.png)
![image](https://user-images.githubusercontent.com/15810277/100973801-36660200-3576-11eb-85d7-8eebe8199b40.png)

**Comment by vipsunwei** [comment]
![image](https://user-images.githubusercontent.com/15810277/100973865-55649400-3576-11eb-8575-ea2ecd2a18b3.png)

**Comment by Pixelairport** [comment]
I also have a similar error with the select field. If i use the field in my app and change the value in the field and then resize my page, I get: "Uncaught TypeError: t.update is not a function". 

<img width="572" alt="Bildschirmfoto 2020-12-03 um 09 53 02" src="https://user-images.githubusercontent.com/1210592/100986376-6816a300-354d-11eb-8d6d-b2f6884bee0d.png">

**Comment by SimonaliaChen** [comment]
I have fixed it in #785, it's because of a duplicated ref binding. We will release it soon in beta.3
