### ISSUE TITLE
[Bug Report] [Component] [drawer, color-picker] 在el-drawer组件中使用el-color-picker组件，点击el-color-picker组件打开取色器面板后，颜色输入框无法聚焦输入

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#7990]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-color-picker`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/oNEqvvj)

### Steps to reproduce

```vue
<script setup>
defineProps({ /* ... */ })
</script>

<template>
  <el-button @click="drawer= true">打开drawer</el-button>
  <el-drawer v-model="drawer">
    <el-color-picker v-model="picker" />
  </<el-drawer>
</template>
```

### What is Expected?

点击el-color-picker组件后，取色器面板里的输入框可以输入

### What is actually happening?

输入框无法输入

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
或许 #7928 也是

**Comment by buqiyuan** [comment]
请暂时先给el-color-picker设置teleported属性为false解决你的问题，此问题我们将会在下一个版本中修复。

**Comment by jw-foss** [comment]
Sorry for the trouble, we are looking into this :bow:
