### ISSUE TITLE
[Bug Report] [Component] [date-picker] el-date-picker的size属性对外边框没有生效

### ISSUE THREAD

**Issue by LastHeaven** [element-plus/element-plus#7991]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZhbHVlMSA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IHZhbHVlMiA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IHZhbHVlMyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLWRhdGUtcGlja2VyIHYtbW9kZWw9XCJ2YWx1ZTFcIiB0eXBlPVwiZGF0ZVwiIHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiIHNpemU9XCJzbWFsbFwiLz48YnI+XG4gICAgPGVsLWRhdGUtcGlja2VyIHYtbW9kZWw9XCJ2YWx1ZTJcIiB0eXBlPVwiZGF0ZVwiIHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiIHNpemU9XCJkZWZhdWx0XCIvPjxicj5cbiAgICA8ZWwtZGF0ZS1waWNrZXIgdi1tb2RlbD1cInZhbHVlM1wiIHR5cGU9XCJkYXRlXCIgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF5XCIgc2l6ZT1cImxhcmdlXCIvPjxicj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

size分别使用small，default，large

### What is Expected?

外边框分大中小

### What is actually happening?

外边框一样大

### Additional comments

_(empty)_

**Comment by et2012** [comment]
duplicate with issue #7821, fixed in pull request #7831
