### ISSUE TITLE
[Bug Report] [Component] [cascader] el-cascader 在开启collapse-tags后按 delete 键会报错

### ISSUE THREAD

**Issue by Patersooon** [element-plus/element-plus#7992]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.2`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[CodePen](https://codepen.io/lichaolichao/pen/wvymwgj)

### Steps to reproduce

搜索框按删除键

### What is Expected?

删除最后一个值

### What is actually happening?

报错

### Additional comments

_(empty)_

**Comment by emojiiii** [comment]
i can't reproduce it, please provide more info.

**Comment by Patersooon** [comment]
> i can't reproduce it, please provide more info.

You need to select more than one first, and then enter delete in the input box

**Comment by Patersooon** [comment]
> i can't reproduce it, please provide more info.

![image](https://user-images.githubusercontent.com/90687224/171322517-37ddb8b9-0490-4f17-8572-19d544860fd0.png)

**Comment by Patersooon** [comment]
> i can't reproduce it, please provide more info.

![image](https://user-images.githubusercontent.com/90687224/171322924-ae8e522c-1d09-401a-8a83-9d0c7f988068.png)

**Comment by Patersooon** [comment]
whatever
