### ISSUE TITLE
[Bug Report] [Component] [select, drawer] cannot unfocus/blur el-select in drawer, options popover gets toggled on and off

### ISSUE THREAD

**Issue by wth193** [element-plus/element-plus#7993]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IFNlbGVjdFdpdGhGaWx0ZXJhYmxlIGZyb20gJy4vU2VsZWN0V2l0aEZpbHRlcmFibGUudnVlJ1xuXG5jb25zdCBkcmF3ZXIgPSByZWYodHJ1ZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgVGhpcyBiZWhhdmVzIG5vcm1hbGx5OlxuICAgIDxTZWxlY3RXaXRoRmlsdGVyYWJsZSAvPlxuICA8L2Rpdj5cblxuICA8cCAvPlxuXG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiAxNnB4XCIgQGNsaWNrPVwiZHJhd2VyID0gdHJ1ZVwiPlxuICAgIG9wZW4gZHJhd2VyXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1kcmF3ZXIgdi1tb2RlbD1cImRyYXdlclwiIHRpdGxlPVwiSSBhbSB0aGUgdGl0bGVcIiA6d2l0aC1oZWFkZXI9XCJmYWxzZVwiPlxuICAgIDxvbD5cbiAgICAgIDxsaT5DbGljayB0byBvcGVuIHBvcG92ZXIgb3B0aW9uczwvbGk+XG4gICAgICA8bGk+RGlzbWlzcyBieSBjbGlja2luZyB3aGl0ZSBhcmVhIGluc2lkZSBkcmF3ZXI8L2xpPlxuICAgICAgPGxpPkNsaWNrIG9uIHRoZSBzYW1lIHdoaXRlIGFyZWE8L2xpPlxuICAgIDwvb2w+XG5cbiAgICBQb3BvdmVyIG9wdGlvbnMgd2lsbCBiZSB0b2dnbGVkIGFnYWluIGFuZCBhZ2Fpbi5cblxuICAgIDxkaXY+XG4gICAgICA8U2VsZWN0V2l0aEZpbHRlcmFibGUgLz5cbiAgICA8L2Rpdj5cbiAgPC9lbC1kcmF3ZXI+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcbiAgfVxufSIsIlNlbGVjdFdpdGhGaWx0ZXJhYmxlLnZ1ZSI6IjwhLS0gQ29waWVkIGRpcmVjdGx5IGZyb20gaHR0cHM6Ly9lbGVtZW50LXBsdXMub3JnL2VuLVVTL2NvbXBvbmVudC9zZWxlY3QuaHRtbCNvcHRpb24tZmlsdGVyaW5nIC0tPlxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+IiwiX28iOnt9fQ==)

### Steps to reproduce

In drawer's content:
1. Click on select to open popover options
2. Click on white area in drawer's content to dismiss the popover options
3. Click on the same white area

### What is Expected?

Nothing happens

### What is actually happening?

el-select is still in focus, popover options is opened upon mouse down, and closed upon mouse up.

### Additional comments

_(empty)_

**Comment by Giwayume** [comment]
@wth193 This might be fixed already, check:
https://github.com/element-plus/element-plus/pull/7915

**Comment by wth193** [comment]
tested using nightly and it's working, thanks!

**Comment by wth193** [comment]
tested using nightly and it's working, thanks!
