### ISSUE TITLE
[Bug Report] [Component] el-table-column设置show-overflow-tooltip属性后tooltip滚动溢出问题

### ISSUE THREAD

**Issue by Steve245270533** [element-plus/element-plus#7995]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome99.0.4844.84/Windows10.0 x64`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`
- `el-tooltip`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-zu7v3m?file=/src/App.vue)

### Steps to reproduce

`el-table`中的`el-table-column`组件在设置`show-overflow-tooltip`属性后，`hover`上去出现tooltip，在鼠标进行内容滚动时，tooltip会跟随hover激活的一栏滚动并溢出，目前采用的不成熟解决方案如下：
#### 方案一：
```JavaScript
app.directive("hidde-tooltip", {
	mounted (el: HTMLElement) {
		console.log(el);
		// 监听表格的mousewheel
		el.addEventListener("mousewheel", (e: any) => {
			const tooltip_ele = document.querySelector(".el-popper.is-dark");
			if (tooltip_ele) {
				(tooltip_ele as HTMLElement).style.display = "none";
			}
		});
	}
});
```
#### 方案二：
```JavaScript
import {onBeforeUnmount, onMounted} from "vue";

export function useElTableTooltip() {
	let app = document.body;

	const isIncludes = (path_arr, dom_arr) => {
		return [...dom_arr].some(dom => {
			return path_arr.includes(dom);
		});
	};

	const handleMouseWheel = (e) => {
		// 事件对象源中匹配el-table的el-scrollbar;
		const all_el_scrollbars = document.querySelectorAll(".el-table .el-scrollbar");
		if (isIncludes(e.path, all_el_scrollbars)) {
			const tooltip_ele = document.querySelector(".el-popper.is-dark");
			if (tooltip_ele) {
				tooltip_ele.style.display = "none";
			}
		}
	};

	onMounted(() => {
		if (app) {
			// console.log("注册");
			app.addEventListener("mousewheel", handleMouseWheel);
		}
	});

	onBeforeUnmount(() => {
		if (app) {
			// console.log("注销");
			app.removeEventListener("mousewheel", handleMouseWheel);
		}
	});
}
```  
之所以没有采用`ref`获取table中的滚动实例是因为还有一种情况下，table是存在于dialog中动态创建出来的，此时无法通过ref获取。

### What is Expected?

滚动时`tooltip`消失

### What is actually happening?

`tooltip`会跟随hover激活的一栏滚动并溢出table

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/46118247/170996044-a124a337-5d83-42ca-abe2-f4f5d8d6b28e.png)

**Comment by msidolphin** [comment]
我认为滚动的时候不应该实现tooltip比较好，我们优化下
