### ISSUE TITLE
[Bug Report] [Component] [select] el-select存在内存泄露问题

### ISSUE THREAD

**Issue by LastHeaven** [element-plus/element-plus#8005]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDx0ZW1wbGF0ZVxuICAgICAgICA6a2V5PVwiaXRlbVwiXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBsaXN0XCI+XG4gICAgICA8Y29tcC1hLz5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgQ29tcEEgZnJvbSAnLi9Db21wQS52dWUnXG5cbmNvbnN0IGxpc3QgPSByZWYoW10pXG5cbnNldEludGVydmFsKCgpID0+IHtcbiAgbGlzdC52YWx1ZSA9IFt7fV1cbn0sIDEwMDApXG5cbnNldEludGVydmFsKCgpID0+IHtcbiAgbGlzdC52YWx1ZSA9IFtdXG59LCAxNTAwKVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiQ29tcEEudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1zZWxlY3Q+PC9lbC1zZWxlY3Q+XG4gICAgPGVsLXNlbGVjdD48L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuZXhwb3J0IGRlZmF1bHQge1xuICBuYW1lOiAnQ29tcEEnLFxuICBwcm9wczoge1xuICAgIGRhdGE6IE9iamVjdFxuICB9LFxuICBkYXRhICgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgY2FjaGU6IG5ldyBBcnJheSg0MDAwMDAwKS5maWxsKDApLmpvaW4oJycpXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cblxuPC9zdHlsZT5cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 使用v-for渲染一个含有两个select框的组件  
2. 使用定时器让这个组件定时消失和展示

### What is Expected?

内存会被回收

### What is actually happening?

内存没有被回收

### Additional comments

![image](https://user-images.githubusercontent.com/10590077/171084849-e4a94cb6-9d15-4946-95d4-620e840f133e.png)

**Comment by 6LA25** [comment]
我也遇到了相同的问题，在dialog内渲染el-select内存泄露
