### ISSUE TITLE
[Bug Report] [Build] 我反馈每次发包都有致命bug是不是事实，请你出来道歉，不要动不动就删isuess

### ISSUE THREAD

**Issue by huifeidewoniu1995** [element-plus/element-plus#8006]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.1`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47`
- Build Tool: `Webpack`

### Related Component

- `el-menu-item`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47

### What is Expected?

./node_modules/_element-plus@2.2.1@element-plus/es/components/menu-item/style/css2.mjs 
Module not found: Error: Can't resolve 'element-plus/theme-chalk/menu-item.css' 

### What is actually happening?

./node_modules/_element-plus@2.2.1@element-plus/es/components/menu-item/style/css2.mjs 
Module not found: Error: Can't resolve 'element-plus/theme-chalk/menu-item.css' 

### Additional comments

我反馈的每次发版都有致命bug是不是事实，官网上面的文档全是广告是不是也是事实，VForm的代码都是加密收钱的是不是也是事实，一上来就我没资格，你MIT协议每个人都有资格用，要不你就别搞这个协议,，请问你下面说的是人话吗，你写开源项目就是捐赠？为了收钱？那你写什么开源，你写闭源不就好了？拿着公司给你发的工资，把公司的资产转移到你自己的名下，不知道谦虚低调也就罢了，说话还带炮仗，我请问你交税了吗，你要真的有理那你就不要关isuess 不要给我删帖，我打工怎么了，你还瞧不起打工的了？

https://github.com/element-plus/element-plus/issues/7818#issuecomment-1134184973

**Comment by billgad** [comment]
It's not a place to complain. It will be better if you fix it and make a contribution.

**Comment by sxzz** [comment]
Hey, nobody asked you to use it and you didn't pay for it either. As a user, the very least you can do is to communicate in a respectful and constructive manner, yet you failed to do that. You are projecting your frustration with your own incompetence in anything on to the author of the library that is trying to help you for free. You are the embodiment of open source consumer entitlement and you are welcome to **FUCK OFF** and never use this library again.

P.S. you have been banned from interacting with any repositories under the Element Plus organization, forever. Please don't bother replying. Actually, I believe it'd be much better off if you just stop using open source and write everything yourself from scratch!

Read the [source](https://github.com/vuejs/pinia/discussions/1322#discussioncomment-2833623)

**Comment by jw-foss** [comment]
我请你搞清楚，什么叫开源，开源不等于免费，源代码在这里，我没问你收钱，有问题你可以贡献，你可以来提 issue，但是麻烦你注意你的态度。Open Source 的全称是 FOSS A.K.A. Free Open Source Software, Free 在这里不是免费的意思，是自由的意思，你有自由使用的权利，没有人来拦你，但不是你口无遮拦在这里骂的理由。你再开一万个号来我都是直接把你屏蔽了，你继续叫呗，继续叫你就不是一个 loser 了 😄

**Comment by jw-foss** [comment]
哦对了，没有人删你的 issue，只是把你这种口无遮拦的喷子屏蔽了并且把这种无效 issue 关了而已。

**Comment by kooriookami** [comment]
@huifeidewoniu1995 你说“拿着公司给你发的工资，把公司的资产转移到你自己的名下”，你有证据吗，不要张口就来。
