### ISSUE TITLE
[Bug Report] [Component] [date-picker] date-picker 中文国际化每一周的第一天不是周一

### ISSUE THREAD

**Issue by izhaoqing** [element-plus/element-plus#8007]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-nqp86t?file=/src/main.js)

### Steps to reproduce

日期面板是从周一开始的

### What is Expected?

从周一开始

### What is actually happening?

从周日开始

### Additional comments

_(empty)_

**Comment by iamkun** [comment]
Please set the Day.js locale manually at this time.
```
import dayjs from 'dayjs'
import dayjsZhCnLocale from 'dayjs/locale/zh-cn'
dayjs.locale(dayjsZhCnLocale)
```

I'll check further to see if this cloud can be done in "ConfigProvider" automatically.

**Comment by bupropion** [comment]
每周的第一天就是周日啊

**Comment by diyxiaoshitou** [comment]
> 此时请手动设置 Day.js 语言环境。
> 
> ```
> import dayjs from 'dayjs'
> import dayjsZhCnLocale from 'dayjs/locale/zh-cn'
> dayjs.locale(dayjsZhCnLocale)
> ```
> 
> 我将进一步检查是否可以在“ConfigProvider”中自动完成此云。

不生效啊

**Comment by nothing-sy** [comment]
Demo: 
`import ElementPlus from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'

app.use(ElementPlus, {
  locale: zhCn,
})`

Set this(It works for me)：
import {dayjs} from 'element-plus'
// import  'dayjs/locale/zh-cn' // if not working, import this line
dayjs.locale('zh-cn', {
  weekStart: 1 
})
