### ISSUE TITLE
[Bug Report] [Component] [button] el-button在v2.2.0及以上版本出现样式问题

### ISSUE THREAD

**Issue by Aug-Sunrise** [element-plus/element-plus#8013]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome/75.0.3770.100`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAg5Zyo5L2O54mI5pys5rWP6KeI5Zmo77yIY2hyb21lNzXvvInnrYnniYjmnKzvvIxlbGVtZW50LXBsdXMgdjIuMi4w5Y+K5Lul5LiK54mI5pys5oyJ6ZKu55qE5Lyq57G75qC35byP5LiN55Sf5pWI77yM5a+86Ie05oyJ6ZKu6IOM5pmv54Gw6Imy5oiW5LiN5Y+v6KeB77yI55u05o6l5L2/55SoY2hyb21lNzXmiJbogIVRUea1j+iniOWZqOi/m+WFpWVsZW1lbnQtcGx1c+eahOWumOe9keS5n+WPr+WkjeeOsO+8iVxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAg5rWL6K+V5oyJ6ZKuXG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

直接使用Chrome75版本或者QQ浏览器进入element-plus官网即可复现

### What is Expected?

按钮显示正常

### What is actually happening?

按钮背景为灰色或直接不可见

### Additional comments

查看代码发现是伪类不生效

**Comment by godShira** [comment]
![image](https://user-images.githubusercontent.com/20473350/171143738-a15b144c-6f8d-4652-9fb9-afadfa8c7b02.png)

**Comment by tolking** [comment]
Fixed in #7977.

Just wait next patch version. Thanks.
