### ISSUE TITLE
[Bug Report] [Component] [dialog] The Dialog component is not responsive.

### ISSUE THREAD

**Issue by jyzbamboo** [element-plus/element-plus#8014]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome 102.0.5005.62`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dialog.html)

### Steps to reproduce

On the Dialog page of your official web site (https://element-plus.org/zh-CN/component/dialog.html). Using the iPhone 12 pro size by the Chrome developer tool, we would see that the dialog is too small (the width of the div is 30%). 

### What is Expected?

The width of the Dialog windows should be 95%-100% when using mobile phone. So that user could see the content.

### What is actually happening?

TThe width of the Dialog windows is only 50% when using mobile phone. User is hard to see all the content of the dialog.

**Comment by l1m2e** [comment]
你的意思是官方文档的吗，如果是自己的项目的需求的话自己改一下就好了 貌似没必要在框架内部实现 ep应该是pc端优先的

**Comment by jyzbamboo** [comment]
> 你的意思是官方文档的吗，如果是自己的项目的需求的话自己改一下就好了 貌似没必要在框架内部实现 ep应该是pc端优先的

不是，官方文档只是个例子，我在本地用dialog也是不支持响应式。

你意思是ep本来就不是100%支持手机端么？

**Comment by tolking** [comment]
可以通过断点信息动态改变 width 使用

**Comment by jyzbamboo** [comment]
> 可以通过断点信息动态改变 width 使用

tolking你好，请问什么是断点信息，有相关资料可以参考么

**Comment by tolking** [comment]
CSS 断点 - [参考断点](https://element-plus.org/zh-CN/component/layout.html#col-属性)

根据当前屏幕的尺寸，判断所属断点进而获取需要显示的宽度。

**Comment by jyzbamboo** [comment]
> CSS 断点 - [参考断点](https://element-plus.org/zh-CN/component/layout.html#col-%E5%B1%9E%E6%80%A7)
> 
> 根据当前屏幕的尺寸，判断所属断点进而获取需要显示的宽度。

谢谢。
我自己给了它一个最小的width，问题暂时解决，但还是希望element-plus团队能关注响应式方面的反馈，谢谢。

.el-dialog {
  min-width: 390px !important;
}

**Comment by emojiiii** [comment]
不推荐在移动端使用 `element-plus`, 因为目前是没有对移动端比较多的处理
