### ISSUE TITLE
el-select 组件 focus时报错 ；浏览器resize时也报错

### ISSUE THREAD

**Issue by vipsunwei** [element-plus/element-plus#802]
报错信息：

![image](https://user-images.githubusercontent.com/15810277/100975033-50084900-3578-11eb-8b68-6d6c83ebc960.png)

![image](https://user-images.githubusercontent.com/15810277/100975102-7201cb80-3578-11eb-8670-310a53238ee3.png)

缩放浏览器时报错：
![image](https://user-images.githubusercontent.com/15810277/100975172-8b0a7c80-3578-11eb-98de-24f8c1123ad2.png)

![image](https://user-images.githubusercontent.com/15810277/100975215-a07fa680-3578-11eb-9b8a-b040e9fa42ff.png)

**Comment by JeremyWuuuuu** [comment]
Got it, this should be fixed soon cc @zouhangwithsweet

**Comment by JeremyWuuuuu** [comment]
Duplicate with #799

**Comment by SimonaliaChen** [comment]
I have fixed it in #785, it's because of a duplicated ref binding. We will release it soon in beta.3
