### ISSUE TITLE
el-checkbox "checked" prop not working

### ISSUE THREAD

**Issue by cwxyz007** [element-plus/element-plus#803]
Example: https://github.com/cwxyz007/element-plus-test

Code: 

```tsx
import { defineComponent, reactive } from 'vue';

export const ElTest = defineComponent(() => {
    const data = reactive({
        active: true
    });

    return () => (
        <el-checkbox checked={data.active} value={data.active} />
    );
});
```

Result is:

![image](https://user-images.githubusercontent.com/14226737/100975326-cefd8180-3578-11eb-83be-dd319aa6e60e.png)

package.json:
```json
{
  "name": "test-vue3",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "element-plus": "^1.0.1-beta.2",
    "vue": "3.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "3.0.3",
    "typescript": "~4.1.2"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by cwxyz007** [comment]
Find some source code, and it didn't check "checked" props.

https://github.com/element-plus/element-plus/blob/5db2e9729cfe346854be957c26d6c86e11484960/packages/checkbox/src/useCheckbox.ts#L78-L87

**Comment by JeremyWuuuuu** [comment]
cc @zouhangwithsweet please take a look at this issue.

**Comment by JeremyWuuuuu** [comment]
I believe that `checked` and `modelValue` or `v-model` is the same thing, they all represent the same thing which is the state of the binding checkbox, that indicates whether the checkbox is checked or not, so it was a redundant design in version 2.x, I think we only need `v-model` to represent the current state of the checkbox. Otherwise the code would be much more complicated with all that compat code.

**Comment by JeremyWuuuuu** [comment]
We should definitely mention that on the documentation.

**Comment by cwxyz007** [comment]
Yes, you are right. And I will use `v-model` to replace it. Thanks for your answer.

**Comment by cs64188** [comment]
I think we need `:checked`，`v-model ` cant support JavaScript expression or a function etc...
