### ISSUE TITLE
[Bug Report] [Style] [button] CSS syntax browser compatibility

### ISSUE THREAD

**Issue by weiquanju** [element-plus/element-plus#8031]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chromium 75.0.3770.100`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[CodePen](https://codepen.io/weiquanju/pen/wvyjWxb)

### Steps to reproduce

在内核版本为`Chromium 75.0.3770.100`的浏览器种打开复现环境链接

Open the replication environment link in browsers with kernel version `Chromium 75.0.3770.100`

### What is Expected?

与官网el-button样式一致
The `el-button` style is consistent with the official website

### What is actually happening?

按钮样式不兼容内核`Chromium 75.0.3770.100`的浏览器，与官网样式不同

The el-button style is not compatible with the browser of kernel `Chromium 75.0.3770.100`, which is different from the official website style

### Additional comments

bug引发原因估计是使用了较新的css语法导致的。

It is estimated that the bug is caused by the use of a relatively new CSS syntax.

eg: [Can I use :not()](https://caniuse.com/?search=%3Anot()). 

#### recommended

`Element Plus Playground`建议使用`unpkg.com`替代`cdn.jsdelivr.net`，因为`cdn.jsdelivr.net`资源请求失败，我无法打开`Element Plus Playground`。

`Element plus playground` it is recommended to use `unpkg.com` substitute `cdn.jsdelivr.net `, because `cdn.jsdelivr.net ` resource request failed. So I cannot open' Element plus playground.

**Comment by sxzz** [comment]
![Uploading image.png…]()

**Comment by weiquanju** [comment]
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/6481596/171357293-f407fd0d-eebc-44dc-8f88-39efee3e8ad1.png">

![image](https://user-images.githubusercontent.com/13448091/171358369-ccb461f0-a91b-46e4-b830-ff5a674103cd.png)
