### ISSUE TITLE
 [Docs] [使用求助] 请问中文文档源码在哪里?只看到了docs/en-US

### ISSUE THREAD

**Issue by HiNaruta** [element-plus/element-plus#8032]
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `All`

## Description

在GitHub和Gitee和Crowdin上没能找到, 在中文文档页面查看源码, 也只能查看到en-US

### Additional comments

希望能下载中文文档源码, 用于断网环境

**Comment by sxzz** [comment]
[#文档](https://github.com/element-plus/element-plus/discussions/7230)
