### ISSUE TITLE
[Bug Report] [Component] [input-number] It's not allowed to input '0.01' or '0.02' when setting step="0.01" and precision="2" to input-number

### ISSUE THREAD

**Issue by JarvisChao** [element-plus/element-plus#8033]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-input-number`

### Reproduction Link

[CodePen](https://codepen.io/x1130132002/pen/poaVbGy?editors=1010)

### Steps to reproduce

When I set step="0.01" and precision="2" to el-input-number, it can't be input or click to the number formats of '0.01' or '0.03' and will be change to '0.10', '0.30'.

### What is Expected?

Allow to input number formats of '0.01' or '0.02'

### What is actually happening?

Can't be input or click to the number formats of '0.01' or '0.03'

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed #7777
