### ISSUE TITLE
Eltable中关于滚动条会随意跳动，show-overflow-tooltip参数引发的bug，ElPagination 参数page-count无效

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#804]
问题有点多，我一个个来
一、Eltable部分
1、el-table中关于行数超过然后出现滚动条的问题
当最后一页（最后一页数据无法分页）的时候返回上一页会丢失竖向滚动条，再返回一次就正常了
2、针对上一个问题，个人手动修改样式，但是没有给height参数赋值，横向滚动条会随意跳动
个人解决方式：
首先:max-height="700":height="700"都需要
并且样式上增加：
::v-deep(.is-scrolling-left) { height: 659px; overflow: auto; }
3、当表格上面使用show-overflow-tooltip参数鼠标移动上去会出现大量的vue方面的bug，不知道是官方代码引发了vue深层次原因，还是其他。
目前个人采用自定义单元格方式实现
![AVTROUOSLON$@SE5F~_S$KV](https://user-images.githubusercontent.com/34828964/100987665-c5c8e080-3589-11eb-89ca-9c21fcd51a60.png)
二、ElPagination部分
page-count传入参数无效，不会发生变化

**Comment by JeremyWuuuuu** [comment]
About `show-tooltip` see #728 

About `Pagination`
Here is the section about `page-count`
![image](https://user-images.githubusercontent.com/15975785/100988318-8f3f9580-358a-11eb-8ed2-24bf9899c1ae.png)

**Comment by JeremyWuuuuu** [comment]
So this means, when `total` is passed to the component, `page-count` won't have any effect on this component.
That's because we have a `internalPageCount` to do the calculation, and I think this is a little bit confusing, because we always want data to drive the UI, which means, `page-count` should have never been an API exposed to our users.

**Comment by ht-sauce** [comment]
<el-pagination :current-page="1" layout="prev, pager, next" :page-count="10"> </el-pagination>
刚才的测试代码，我的是这样的
版本："element-plus": "^1.0.1-beta.0",
但是页面上面是这样的
![0)8IVU)2H@{KFV$1Z(95BGI](https://user-images.githubusercontent.com/34828964/100993269-278c4900-3590-11eb-9917-acb11f80dcf4.png)

> 因此，这意味着，当`total`传递给组件时，`page-count`将对该组件没有任何影响。
> 那是因为我们必须进行`internalPageCount`计算，而且我认为这有点令人困惑，因为我们一直希望数据来驱动UI，这意味着，它`page-count`永远都不应该是向用户公开的API。

**Comment by JeremyWuuuuu** [comment]
> 这是代码
> ![X}5Q@L)NOIZ4RY`PNUSQUYC](https://user-images.githubusercontent.com/34828964/100993548-82be3b80-3590-11eb-96ae-8188c2bba494.png)
> 
> 版本："element-plus": "^1.0.1-beta.0",
> 但是页面上面是这样的
> ![0)8IVU)2H@{KFV$1Z(95BGI](https://user-images.githubusercontent.com/34828964/100993269-278c4900-3590-11eb-9917-acb11f80dcf4.png)
> 
> > 因此，这意味着，当`total`传递给组件时，`page-count`将对该组件没有任何影响。
> > 那是因为我们必须进行`internalPageCount`计算，而且我认为这有点令人困惑，因为我们一直希望数据来驱动UI，这意味着，它`page-count`永远都不应该是向用户公开的API。

This is because the default value of `total` is **1000**, the default value of `pageSize` is **10**, when you did not passing any value to `el-pagination` it gets that from `default`, which in this case is **1000 / 10 **, you get **100** pages.

**Comment by JeremyWuuuuu** [comment]
For question 1, could you give some demo code to reproduce it?
