### ISSUE TITLE
[Bug Report] [Style] [button] 360浏览器打开丢失样式（无颜色）

### ISSUE THREAD

**Issue by zouzhiyong** [element-plus/element-plus#8040]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.2`
- Browser / OS: `360浏览器/win11`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

直接打开

### What is Expected?

希望显示正常颜色

### What is actually happening?

没有颜色

### Additional comments

_(empty)_

**Comment by SmallSample** [comment]
浏览器版本太低，不支持

**Comment by zouzhiyong** [comment]
已经升到最新版本了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Bug Report] [Style] [button] 360浏览器打开丢失样式（无颜色） (Issue #8040)





 
浏览器版本太低，不支持

**Comment by Dexter-sz** [comment]
.el-button{
  border: none;
  outline: none;
  background: var(--el-button-bg-color);
  border-color: var(--el-button-border-color);
  color: var( --el-button-text-color);
  &:hover{
    background: var(--el-button-hover-bg-color);
    border-color: var(--el-button-hover-border-color);
    color: var( --el-button-hover-text-color);
  }

  &:active{
    color: var(--el-button-active-text-color);
  }
}

我也这样 补一个样式就解决了

**Comment by zouzhiyong** [comment]
OK,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 中午11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Bug Report] [Style] [button] 360浏览器打开丢失样式（无颜色） (Issue #8040)





 
.el-button{
 border: none;
 outline: none;
 background: var(--el-button-bg-color);
 border-color: var(--el-button-border-color);
 color: var( --el-button-text-color);
 &amp;:hover{
 background: var(--el-button-hover-bg-color);
 border-color: var(--el-button-hover-border-color);
 color: var( --el-button-hover-text-color);
 }
 
&amp;:active{
 color: var(--el-button-active-text-color);
 }
 }
 
我也这样 补一个样式就解决了

**Comment by chenxch** [comment]
fix #7977 
Will be updated in the next version.
