### ISSUE TITLE
[Bug Report] [Component] [date-picker] el-date-picker disabled属性值为 true，禁用状态下，表单展示灰色，但依旧可以调出日期选择弹出层，依旧可以修改日期

### ISSUE THREAD

**Issue by sunnyfj** [element-plus/element-plus#8047]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chorme`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html)

### Steps to reproduce

1

### What is Expected?

1

### What is actually happening?

1

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Fixed in #8139

**Comment by tolking** [comment]
Fixed in #8139
