### ISSUE TITLE
[Bug Report] [Style] [button] button显示异常

### ISSUE THREAD

**Issue by 394988736** [element-plus/element-plus#8048]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: ` 双核浏览器	86.0.4240.198 （32 位） 修订版本	230192ed133e43774527e47773577ec84ee212a7-refs/branch-heads/4240@{#966} 操作系统	Windows 10 OS Version 2004 (Build 19041.1415) JavaScript	V8 8.6.395.10 Flash	32.0.0.363`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

https://element-plus.gitee.io/zh-CN/component/button.html

### What is Expected?

button背景色无

### What is actually happening?

修复

### Additional comments

_(empty)_

**Comment by Inori-Lover** [comment]
`:not` 选择器的版本依赖太高

https://caniuse.com/css-not-sel-list

**Comment by chenxch** [comment]
fix #7977 
Will be updated in the next version.
