### ISSUE TITLE
[Bug Report] [Style] [date-picker] date-picker 当 type=daterange 时组件样式异常

### ISSUE THREAD

**Issue by zhyipeng** [element-plus/element-plus#8055]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Edge/102.0.1245.30 Intel Mac OS X 10_15_7)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodePen](https://codepen.io/zhyipeng/pen/BaYxEqj)

### Steps to reproduce

```html
<el-form inline>
  <el-form-item>
    <el-date-picker type="daterange"></el-date-picker>
  </el-form-item>
  <el-form-item>
    <el-date-picker></el-date-picker>
  </el-form-item>
</el-form>
```

### What is Expected?

不同 type 的样式应一致

### What is actually happening?

daterange 比 date 高出一截, 经排查可能是 .el-range-editor 的 padding 属性影响的.

### Additional comments

_(empty)_

**Comment by tongxin-77** [comment]
![image](https://user-images.githubusercontent.com/58261510/171600757-3f25179a-1103-490d-a2b3-71296a9711fd.png)
