### ISSUE TITLE
[Bug Report] [Component] [popover] el-popover 如果使用v-model:visible 不生效，无法正常打开

### ISSUE THREAD

**Issue by jqw1122** [element-plus/element-plus#8056]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlciB2LW1vZGVsOnZpc2libGU9XCJ2aXNpYmxlXCIgcGxhY2VtZW50PVwidG9wXCIgOndpZHRoPVwiMTYwXCI+XG4gICAgPHA+QXJlIHlvdSBzdXJlIHRvIGRlbGV0ZSB0aGlzPzwvcD5cbiAgICA8ZGl2IHN0eWxlPVwidGV4dC1hbGlnbjogcmlnaHQ7IG1hcmdpbjogMFwiPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0ZXh0IEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPmNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiXG4gICAgICAgID5jb25maXJtPC9lbC1idXR0b25cbiAgICAgID5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZSA9IHRydWVcIj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

如果使用 v-model:visible，无法正常开启， 

### What is Expected?

正常打开

### What is actually happening?

无法打开窗口

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/171647658-6a1f032f-c19d-4c8a-b6b3-91d98aa9da3a.png)
top 显示在上方哦

**Comment by GuYun-D** [comment]
我也是啊，要是使用`v-model:visible`不会生效，但是使用`v-model:visiable`他就可以弹出，但是绑定的值没有发生变化，我的element版本是2.2.6

**Comment by sunlightcs** [comment]
这个能快点修复吗，也遇到这个问题了，element版本号2.2.8

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luLXRvcDoyNTBweFwiPlxuICAgIFxuICA8ZWwtcG9wb3ZlciB2LW1vZGVsOnZpc2libGU9XCJ2aXNpYmxlXCIgcGxhY2VtZW50PVwidG9wXCIgOndpZHRoPVwiMTYwXCI+XG4gICAgPHA+QXJlIHlvdSBzdXJlIHRvIGRlbGV0ZSB0aGlzPzwvcD5cbiAgICA8ZGl2IHN0eWxlPVwidGV4dC1hbGlnbjogcmlnaHQ7IG1hcmdpbjogMFwiPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0ZXh0IEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPmNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiXG4gICAgICAgID5jb25maXJtPC9lbC1idXR0b25cbiAgICAgID5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZSA9IHRydWVcIj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG4gIDwvZGl2PiB7e3Zpc2libGV9fVxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
是我理解的不对么

**Comment by jqw1122** [comment]
好的 但是在我的项目里确实无法打开，
原来使用的element-ui，升级到最新版后就不可用了
在测试环境可以的，因为用top，所以没看到 忽略了以为也无法打开。
那可能是项目中有什么错误，我先关闭这个提问了。 thx
