### ISSUE TITLE
[Bug Report] [Component] [dialog] Dialog开启拖拽功能后的Bug

### ISSUE THREAD

**Issue by stevqin** [element-plus/element-plus#8061]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.2`
- Browser / OS: `Microsoft Edge 101.0.1210.53`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### 没搭梯子，Element Plus Playground 没能加载出来。
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gTWVzc2FnZSBCb3g8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBFbE1lc3NhZ2UsIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oXG4gICAgJ3Byb3h5IHdpbGwgcGVybWFuZW50bHkgZGVsZXRlIHRoZSBmaWxlLiBDb250aW51ZT8nLFxuICAgICdXYXJuaW5nJyxcbiAgICB7XG4gICAgICBjb25maXJtQnV0dG9uVGV4dDogJ09LJyxcbiAgICAgIGNhbmNlbEJ1dHRvblRleHQ6ICdDYW5jZWwnLFxuICAgICAgdHlwZTogJ3dhcm5pbmcnLFxuICAgICAgZHJhZ2dhYmxlOiB0cnVlLFxuICAgIH1cbiAgKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIEVsTWVzc2FnZSh7XG4gICAgICAgIHR5cGU6ICdzdWNjZXNzJyxcbiAgICAgICAgbWVzc2FnZTogJ0RlbGV0ZSBjb21wbGV0ZWQnLFxuICAgICAgfSlcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICB0eXBlOiAnaW5mbycsXG4gICAgICAgIG1lc3NhZ2U6ICdEZWxldGUgY2FuY2VsZWQnLFxuICAgICAgfSlcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<el-dialog v-model="state.dialog.visible" destroy-on-close draggable @closed="closed">
...
```
在el-dialog 标签中同时使用了 destroy-on-close 和 draggable 属性，在关闭 dialog再打开时，拖动窗口会出现坐标不准确的问题

### What is Expected?

在使用 destroy-on-close 属性，关闭时销毁 dialog 组件时也同时重置下光标位置

### What is actually happening?

关闭dialog窗口，销毁组件时，鼠标拖动后的光标位置没有被重置，导致下次再点开dialog弹窗后，鼠标移上去拖动窗口则会出现窗口不跟手的现象

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
#7816 
感谢您的反馈，目前问题已修复，将在下一个版本发布。
