### ISSUE TITLE
[Bug Report] [TypeScript] [input]  [el-input]  Property 'rows' does not exist on type

### ISSUE THREAD

**Issue by yuniit** [element-plus/element-plus#8068]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.2`
- Browser / OS: `Version 102.0.5005.61 (Official Build) (arm64)`
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwidGV4dGFyZWExXCJcbiAgICB0eXBlPVwidGV4dGFyZWFcIlxuICAgIDpyb3dzPVwiNlwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAvPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luOiAyMHB4IDBcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRleHRhcmVhMSA9IHJlZignJylcbmNvbnN0IHRleHRhcmVhMiA9IHJlZignJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. create component with <script lang "ts">
2. use <el-input> type="textarea" and set :rows="number"

![Screen Shot 2022-06-03 at 9 02 39 AM](https://user-images.githubusercontent.com/30621352/171772359-13f88261-6a4a-4290-83b2-d474b7272ac4.png)

Ex: 
```vue
<script setup lang="ts">
  defineProps({ /* ... */ })
</script>

<template>
   <el-input
    v-model="text"
    type="textarea"
    :rows="2"
   ></el-input>
</template>
```

### What is Expected?

It shouldn't show the error

### What is actually happening?

Property 'rows' does not exist on type 'IntrinsicAttributes & Partial<{ type: string; size: BuildPropType ...

### Additional comments

_(empty)_

**Comment by LinZhanMing** [comment]
可能是 packages/components/input/src/input.ts 里面的 inputProps 缺少了 rows ?

**Comment by yuniit** [comment]
> Maybe the inputProps in packages/components/input/src/input.ts is missing rows ?

I've checked prop `rows` is missing

**Comment by tolking** [comment]
This may be caused by vue-tsc [link](https://github.com/johnsoncodehk/volar/issues/1384).

You can try to modify the vue-tsc version

**Comment by Etienne-Leveque** [comment]
This issue still exists as of today, and it doesn't seem to be related to vue-tsc:

>Argument of type '{ modelValue: string; rows: number; type: string; autocomplete: string; size: "default"; style: {}; "onUpdate:modelValue": any; }' is not assignable to parameter of type '{ readonly type?: string | undefined; readonly modelValue?: EpPropMergeType<(new (...args: any[]) => string | number) | (() => string | number | null | undefined) | ((new (...args: any[]) => string | number) | (() => string | number | null | undefined))[], unknown, unknown>; ... 44 more ...; readonly prefixIcon?: Ep...'.
  Object literal may only specify known properties, and 'rows' does not exist in type '{ readonly type?: string | undefined; readonly modelValue?: EpPropMergeType<(new (...args: any[]) => string | number) | (() => string | number | null | undefined) | ((new (...args: any[]) => string | number) | (() => string | number | null | undefined))[], unknown, unknown>; ... 44 more ...; readonly prefixIcon?: Ep...'.ts(2345)

`rows` is missing in the type declaration

**Comment by tolking** [comment]
There are many native attributes that are not defined in props now, which can indeed cause some type errors (eq using in tsx).

You can also use the above method to temporarily handle the problem, and if there is a better solution, you can also discuss it
