### ISSUE TITLE
想说，文档可以写的再烂一点吗，真的太失望了，能不能学ant-design-vue提供js和ts的语法切换

### ISSUE THREAD

**Issue by YangCuiWangMiss** [element-plus/element-plus#8069]
Feature type: **`New Component`**

## Details

- New component name: ``

## Description

element-plus目前最大的问题就是对只会js的开发者极不友好，不是每个人都有机会去大公司，也不是每个项目必须用TypeScript，希望尽快提供Js版本的文档，不要本末倒置，忘了谁才是爸爸。

### Additional comments

_(empty)_

[点这里看看人家文档怎么写的](https://www.antdv.com/)

**Comment by YangCuiWangMiss** [comment]
就像这样 ![image](https://user-images.githubusercontent.com/106791195/171776338-8f4efc2d-b37a-43a4-b25c-6069f1ee3d7f.png)

**Comment by YangCuiWangMiss** [comment]
再就是 能不能搞个像今日头条或者native ui那样免费的控制面板的页面这个才是大家需要的，现在根本就没有好的实践的示例
![image](https://user-images.githubusercontent.com/106791195/171776836-472a1b30-14aa-4134-a015-b1e82e1d793a.png)
![image](https://user-images.githubusercontent.com/106791195/171777100-5857d38c-b92d-4add-bdb5-7f36805990b7.png)

**Comment by sxzz** [comment]
我是你爹

**Comment by HerringtonDarkholme** [comment]
We welcome any kind of contribution including sponsorship or pull requests.

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/issues/8006#issuecomment-1141642717
