### ISSUE TITLE
[Bug Report] [Component] [slider] Slider组件的change事件，点击时不触发，只有拖拽后松开才触发

### ISSUE THREAD

**Issue by shuangovo** [element-plus/element-plus#8087]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome 102.0.5005.63 / Win10`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2coXCJjaGFuZ2U6XCIsIHZhbClcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICBcbiAgPGVsLXNsaWRlciBAY2hhbmdlPVwib25DaGFuZ2VcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击进度条

### What is Expected?

点击和拖拽后松开时都能触发

### What is actually happening?

只有拖拽后松开才触发

### Additional comments

input事件虽然支持点击触发，但拖拽时无法满足我的需求

**Comment by chenxch** [comment]
方便描述下具体需求吗？ 具体场景应该要使用相应的API。

**Comment by shuangovo** [comment]
> 方便描述下具体需求吗？ 具体场景应该要使用相应的API。

视频的进度条，要求点击进度条或拖动后松开时修改视频的进度，拖动过程中不修改

**Comment by chenxch** [comment]
目前对于组件的功能来说这个应该是属于Bug Report，它应该更偏向于一个Feature Report. 你可以尝试通过@mouseup去实现业务功能。

**Comment by shuangovo** [comment]
> 目前对于组件的功能来说这个应该不属于Bug Report，它应该更偏向于一个Feature Report. 你可以尝试通过@mouseup去实现业务功能。

@mouseup也取不到变化的值啊，只能把input的值存起来，希望后面可以优化一下

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2coXCJjaGFuZ2U6XCIsIHZhbClcbn1cbmNvbnN0IHZhbHVlID0gcmVmKDApXG5jb25zdCBvbk1vdXNldXAgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdvbk1vdXNldXAnLCB2YWx1ZS52YWx1ZSlcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICBcbiAgPGVsLXNsaWRlciBAY2hhbmdlPVwib25DaGFuZ2VcIiBAbW91c2V1cD1cIm9uTW91c2V1cFwiIHYtbW9kZWw9XCJ2YWx1ZVwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by trtst** [comment]
> > 方便描述下具体需求吗？ 具体场景应该要使用相应的API。
> 
> 视频的进度条，要求点击进度条或拖动后松开时修改视频的进度，拖动过程中不修改

我理解你的意思，我也遇到你这种情况。


场景：
视频/音频在播放的时候， 进度条是在实时更改的，当我们拖拽进度条，松开鼠标后，我们想要获取的是松开鼠标后的值，但实际上我们获取的是v-model实时更改的值，导致最后获取的数据不对。

@chenxch    你给的demo  不能说明大家遇到的问题，因为你的进度条是静态的。  你可以试试实时更改v-model的值，然后再看看change或者mouseup后，获取的值是否是你想要的？

**Comment by chenxch** [comment]
> > > 方便描述下具体需求吗？ 具体场景应该要使用相应的API。
> > 
> > 
> > 视频的进度条，要求点击进度条或拖动后松开时修改视频的进度，拖动过程中不修改
> 
> 我理解你的意思，我也遇到你这种情况。
> 
> 场景： 视频/音频在播放的时候， 进度条是在实时更改的，当我们拖拽进度条，松开鼠标后，我们想要获取的是松开鼠标后的值，但实际上我们获取的是v-model实时更改的值，导致最后获取的数据不对。
> 
> @chenxch 你给的demo 不能说明大家遇到的问题，因为你的进度条是静态的。 你可以试试实时更改v-model的值，然后再看看change或者mouseup后，获取的值是否是你想要的？

@trtst 可以哦，只是上面同学反馈的不需要拖拽过程中input事件触发，他这是算是一个Feature Report. 
如果你没有拖拽问题的话，你的问题我会在你的issues里面回复。

**Comment by trtst** [comment]
> > > > 方便描述下具体需求吗？ 具体场景应该要使用相应的API。
> > > 
> > > 
> > > 视频的进度条，要求点击进度条或拖动后松开时修改视频的进度，拖动过程中不修改
> > 
> > 
> > 我理解你的意思，我也遇到你这种情况。
> > 场景： 视频/音频在播放的时候， 进度条是在实时更改的，当我们拖拽进度条，松开鼠标后，我们想要获取的是松开鼠标后的值，但实际上我们获取的是v-model实时更改的值，导致最后获取的数据不对。
> > @chenxch 你给的demo 不能说明大家遇到的问题，因为你的进度条是静态的。 你可以试试实时更改v-model的值，然后再看看change或者mouseup后，获取的值是否是你想要的？
> 
> @trtst 可以哦，只是上面同学反馈的不需要拖拽过程中input事件触发，他这是算是一个Feature Report. 如果你没有拖拽问题的话，你的问题我会在你的issues里面回复。

已看到回复，并测试了，谢谢了哈~
