### ISSUE TITLE
[Bug Report] [Component] [select-v2] Elselectv2 cannot render

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#8104]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.4`
- Browser / OS: `Google Chrome102.0.5005.63（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCIgbGFiZWwtd2lkdGg9XCIxMjBweFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSBuYW1lXCI+XG4gICAgICA8ZWwtc2VsZWN0LXYyIHYtbW9kZWw9XCJmb3JtLm5hbWVcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuLy8gZG8gbm90IHVzZSBzYW1lIG5hbWUgd2l0aCByZWZcbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7XG4gIG5hbWU6ICcnLFxuICByZWdpb246ICcnLFxuICBkYXRlMTogJycsXG4gIGRhdGUyOiAnJyxcbiAgZGVsaXZlcnk6IGZhbHNlLFxuICB0eXBlOiBbXSxcbiAgcmVzb3VyY2U6ICcnLFxuICBkZXNjOiAnJyxcbn0pXG5cbmNvbnN0IG9wdGlvbnMgPSByZWYoW1xuICB7XG4gICAgbGFiZWw6ICcyJyxcbiAgICB2YWx1ZTogJzInXG4gIH1cbl0pXG5cbmNvbnN0IG9uU3VibWl0ID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnc3VibWl0IScpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

ditto

### What is Expected?

Elselectv2 can render

### What is actually happening?

Elselectv2 cannot render

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
If possible, please use `vue` version `3.2.33` and below first.

**Comment by kailong321200875** [comment]
> If possible, please use `vue` version `3.2.33` and below first.

OK
