### ISSUE TITLE
[Bug Report] [Component] [popover, dropdown] 暗黑模式下 同时使用el-popover 和 el-dropdown，导致el-popover 无法进入暗黑模式

### ISSUE THREAD

**Issue by zhiyuanzmj** [element-plus/element-plus#8113]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.4`
- Browser / OS: `macos`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-dropdown`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-tjd7ys?file=src%2FApp.vue)

### Steps to reproduce

同时使用el-popover 和 el-dropdown

### What is Expected?

el-popover 进入暗黑模式

### What is actually happening?

el-popover的 .is-light 样式 被覆盖

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
I have the same issue
