### ISSUE TITLE
Error style of el-select-dropdown

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#812]
![image](https://user-images.githubusercontent.com/38392315/101042694-6d5d0780-35b8-11eb-8f96-1e86b443f7fd.png)
```html
<el-form label-width="auto" style="width: 400px">
    <el-form-item label="123">
        <el-select v-model="form.value" style="width: 100%">
            <el-option v-for="item in 2" :key="item" :label="item" :value="item.value"></el-option>
        </el-select>
    </el-form-item>
</el-form>
```

**Comment by JeremyWuuuuu** [comment]
I also found this to be a potential bug last night. It correct behavior is that whenever the visibility of select dropdown shows it should adjust its width with its reference

**Comment by JeremyWuuuuu** [comment]
Interested in making PR on this?

**Comment by kooriookami** [comment]
OK, I will try.
