### ISSUE TITLE
[Bug Report] [TypeScript] [All] 2.2.4版本修改了vue默认的App类型，导致项目App类型错误

### ISSUE THREAD

**Issue by zyftxdy** [element-plus/element-plus#8122]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIm1haW4udHMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2xpYi9sb2NhbGUvbGFuZy96aC1jbidcbmltcG9ydCAnZWxlbWVudC1wbHVzL2Rpc3QvaW5kZXguY3NzJ1xuXG5pbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tICd2dWUnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcblxuaW1wb3J0IHJvdXRlciBmcm9tICcuL3JvdXRlcidcblxuY29uc3QgYXBwID0gY3JlYXRlQXBwKEFwcClcblxuYXBwLnVzZShFbGVtZW50UGx1cywge1xuICAgIGxvY2FsZTogemhDblxuICB9KVxuICAudXNlKHJvdXRlcikgLy8g6K+l5aSE5oqlQXBw57G75Z6L5LiN5Yy56YWNIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 在vue3+ts项目中安装element-plus@2.2.4
2. 在main.ts中注册app
3. app.use(router) // 该步骤报错 app类型不匹配

### What is Expected?

还原成正确的App类型

### What is actually happening?

App类型被修改
文件路径：/packages/element-plus/make-installer.ts
declare module 'vue' {
    interface App {
        [INSTALLED_KEY]?: boolean;
    }
}

### Additional comments

_(empty)_

**Comment by k713927** [comment]
遇到同样的问题

**Comment by zyftxdy** [comment]
@k713927 就是我写的文件路径 里面重置了vue的 App interface接口😂

**Comment by k713927** [comment]
> 

是的，邮箱到什么临时的解决方案吗。项目里面太多了，全部//@ts-ignore 不现实

**Comment by zyftxdy** [comment]
@k713927 先退到2.2.2版本，这个版本是好的

**Comment by wu67** [comment]
是说 `app.use(router)` 这一句会报错吗? 试试这样写`app.use(router as any)`

**Comment by zyftxdy** [comment]
@wu67 试过了 但是项目其他地方也会用到App 比如注册组件时，app.component() 会提示app上不存在component方法

**Comment by zyftxdy** [comment]
感觉主要的原因就是vue的App类型被修改了吧😂

**Comment by wu67** [comment]
那还是退版本吧. 我目前在用2.1.11, 没啥大问题. 就是`Checkbox-Group`的change响应方法有点毛病, 返回的参数明明是个数组, 但是类型定义缺要求为`(property) 'change': ((val: string | number | boolean) => any) | undefined`

**Comment by tolking** [comment]
可以尝试临时修改本地

// /packages/element-plus/make-installer.ts

```diff
- import type { App, Plugin } from 'vue';
+ import type { App, Plugin } from '@vue/runtime-core';
declare const INSTALLED_KEY: unique symbol;
- declare module 'vue' {
+ declare module '@vue/runtime-core' {
    interface App {
        [INSTALLED_KEY]?: boolean;
    }
}
```

**Comment by zyftxdy** [comment]
@tolking 修改本地，线上打包发布的话还是会报错的吧😂，这个预计下个版本会修复嘛

**Comment by zyftxdy** [comment]
@tolking 这个预计下个版本会修复嘛

**Comment by tolking** [comment]
@zyftxdy 如果上面能够正常工作，我们会尽快修复

**Comment by zyftxdy** [comment]
@tolking 好的，感谢

**Comment by languanghao** [comment]
@tolking 所有的app.use注册的插件都出错了，情尽快修复

**Comment by Inori-Lover** [comment]
https://github.com/element-plus/element-plus/pull/7941/files

这边本地调试了一下，理应是这个pr里引入的问题，修复也比较简单；我一并丢在代码评论里了

**Comment by exherb** [comment]
😮‍💨

**Comment by CarsonXin** [comment]
有相同的问题，此外还有ts提示：TS2315: Type 'App' is not generic。

### Environment
* Vue Version: 3.2.33
* Element Plus Version: ^2.1.10
* Browser / OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
* Build Tool: @vue/cli 5.0.4
* Typescript Version: 4.5.5

个人的临时的解决方案：在shims-vue.d.ts中添加如下代码
```typescript
import type { App as VueApp } from '@vue/runtime-core';
declare module 'vue' {
  interface App<HostElement = any> extends VueApp<HostElement> {
  }
}
```

**Comment by wuxianqiang** [comment]
啥时候能修复呀？

**Comment by sxzz** [comment]
Fixed in 2.2.5

**Comment by Iamdyy** [comment]
2.2.5 vite.config.ts vscode 打开CPU 100%。已降2.2.3
