### ISSUE TITLE
[Bug Report] [TypeScript] [checkbox, checkbox-group] change事件响应方法类型约束是否不够严谨?

### ISSUE THREAD

**Issue by wu67** [element-plus/element-plus#8125]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-checkbox`
- `el-checkbox-group`

### Reproduction Link

[Github Repo](https://github.com/wu67/yys-tool)

### Steps to reproduce

1. pull一下我的[小项目](https://github.com/wu67/yys-tool)
2. 把element-plus 更新至 2.2.0以上(不含2.2.0), 例如目前最新的2.2.4
3. npm run build

### What is Expected?

构建成功

### What is actually happening?

```bash
error TS2322: Type '(val: boolean) => void' is not assignable to type '(val: string | number | boolean) => any'.
  Types of parameters 'val' and 'val' are incompatible.
    Type 'string | number | boolean' is not assignable to type 'boolean'.

20           @change="handleCheckAllChange"
              ~~~~~~
...
```

### Additional comments

1. checkbox使用过程中, 绑定值必定是 boolean number string中的一种, 但是目前最新版本的类型断言强制约束了需要同时处理3中类型? 或者得写成 onChange(arg: any) => void
2. checkbox-group 的change事件响应方法貌似是沿用了checkbox的约束, 这个方法获取到的参数明明是个数组...

**Comment by tolking** [comment]
1. 似乎现在无法避免这个问题
2. 确实是类型定义错误，欢迎 PR
