### ISSUE TITLE
[Bug Report] [Component] [input] 在ElTooltip中ElInput无法输入空格

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#8127]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPGVsLXRvb2x0aXAgY29udGVudD1cIlRvcCBMZWZ0IHByb21wdHMgaW5mb1wiIHBsYWNlbWVudD1cImJvdHRvbVwiPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIj48L2VsLWlucHV0PlxuICAgPC9lbC10b29sdGlwPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```
<el-tooltip content="Top Left prompts info" placement="bottom">
     <el-input v-model="input" placeholder="Please input"></el-input>
</el-tooltip>
```
在ElTooltip中输入框无法输入空格

### What is Expected?

输入框可以输入空格

### What is actually happening?

输入框无法输入空格

### Additional comments

_(empty)_

**Comment by mxp131011** [comment]
基础性功能bug 希望尽早修复

**Comment by mxp131011** [comment]
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/50739490/172133046-8ce1b6e2-619c-461f-9954-ab40eb26f1bd.png">
> 
> triggerKeys='[]'
I didn't see the document

**Comment by mxp131011** [comment]
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/50739490/172133046-8ce1b6e2-619c-461f-9954-ab40eb26f1bd.png">
> 
> triggerKeys='[]'

I didn't see the document

**Comment by gjfei** [comment]
> > <img alt="图片" width="1439" src="https://user-images.githubusercontent.com/50739490/172133046-8ce1b6e2-619c-461f-9954-ab40eb26f1bd.png">
> > triggerKeys='[]'
> 
> 我没看到文件


![image](https://user-images.githubusercontent.com/33827314/172341086-61ac2d4b-d6fb-461f-9d99-28fa3123adfe.png)

packages\components\tooltip\src\tooltip.ts

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/172400270-d716772e-6b31-4dee-94fd-ec6fdd7073cf.png)
@mxp131011 可以输入呀

**Comment by Anyhonor** [comment]
> ![图片](https://user-images.githubusercontent.com/23251408/172400270-d716772e-6b31-4dee-94fd-ec6fdd7073cf.png) @mxp131011 可以输入呀

2.2.3版本及以后的输入不了

**Comment by rookielzy** [comment]
@chenxch 这个问题目前仍然存在，请尽快解决

**Comment by chenxch** [comment]
> @chenxch 这个问题目前仍然存在，请尽快解决

https://github.com/element-plus/element-plus/issues/8127#issuecomment-1148397582
