### ISSUE TITLE
[Bug Report] [Style] [input-number] 某些浏览器下Input Number输入框无值时会下移动

### ISSUE THREAD

**Issue by myhzw** [element-plus/element-plus#8141]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.2`
- Element Plus Version: `2.2.4`
- Browser / OS: `window10`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

搜狗浏览器下Input Number输入框删除值时会下移动

### What is Expected?

不移动

### What is actually happening?

移动

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/31983596/172291298-e9b4e413-aa70-4755-b8fa-33153f537333.png)
![image](https://user-images.githubusercontent.com/31983596/172291354-1881ee92-f50c-4037-8c50-f56648d09184.png)

**Comment by sxzz** [comment]
请提供 Chrome 内核版本，最好附上 UserAgent 信息

**Comment by myhzw** [comment]
![image](https://user-images.githubusercontent.com/31983596/172532012-7ccfceda-1aca-41f2-b890-11e7dee12621.png)
![image](https://user-images.githubusercontent.com/31983596/172532030-ca67736f-0c2e-419d-9821-dd9203d6c5d5.png)

**Comment by HeftyKoo** [comment]
duplicated: #10177
