### ISSUE TITLE
[Bug Report] [TypeScript] [form] 模块"element-plus" 没有导出的成员 “FormRules”

### ISSUE THREAD

**Issue by Lvxinbo666** [element-plus/element-plus#8147]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `1.1.0-beta.24`
- Browser / OS: `谷歌96 windows`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG4vLyB2c0NvZGXkuIsg5o+Q56S65rKh5pyJ5a+85Ye655qE5oiQ5ZGY4oCcRm9ybVJ1bGVz4oCdXG5jb25zdCBmb3JtID0gcmVhY3RpdmU8Rm9ybVJ1bGVzPih7fSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

import type { FormRules } from 'element-plus'

### What is Expected?

不报错

### What is actually happening?

会报错提示：模块"element-plus" 没有导出的成员 “FormRules”

### Additional comments

感谢回复

**Comment by gjfei** [comment]
FormProps['rules'] 可以拿到

**Comment by gjfei** [comment]
> > FormProps['rules'] 可以拿到
> 
> 感谢您的回复，我这里不仅仅是FormRules会遇到这个问题，所有的 import type {} from 'element-plus' 都会报同样的问题，这样的我该如何去做？

目前类型还没全部重构完成好像，有些类型还不能拿到

**Comment by gjfei** [comment]
你可以关注一下这个#6114

**Comment by sxzz** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/6481596/172360250-74e4ba95-30bb-4ddd-ae3f-5e28d9ffc6b4.png">
尝试删除node_modules重装、重启vscode
