### ISSUE TITLE
[Feature Request] [i18n] 为什么默认languages是英语？？？

### ISSUE THREAD

**Issue by kentLin0** [element-plus/element-plus#8148]
Feature type: **`i18n`**

## Details

- Enhanced compone nt name: `All`

## Description

我就很奇怪为什么默认语言是英语，你们产品经理是外国人吗？方便外国人使用？做个语言环境判断应该也不难吧？

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
你改一下代码也不难吧?

**Comment by ac51300696** [comment]
> 你改一下代码也不难吧?有逼逼时间提一个pr不好吗?

保持英文挺好的，自己想要就fork一个版本改下默认就是了

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/blob/9f5aae64ea5089c18533c91181e299925adb634c/docs/.vitepress/lang.js#L11-L33

自行检查 `navigator.language` 和 localStorage 的 `preferred_lang`
