### ISSUE TITLE
[Bug Report] [Component] [tooltip] Popover中嵌套文字提示，Popover无效

### ISSUE THREAD

**Issue by qqchenhai** [element-plus/element-plus#8150]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/Win7;x64`
- Build Tool: `Vue CLI`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHdpZHRoPVwiNzBcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbS1lbmRcIlxuICAgIHBvcHBlci1jbGFzcz1cInBvcHBlci10YWJsZS1zaXplXCJcbiAgPlxuICAgIDxkaXYgY2xhc3M9XCJsaXN0XCI+XG4gICAgICA8ZGl2XG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBsaXN0XCJcbiAgICAgICAgY2xhc3M9XCJsaXN0LWl0ZW1cIlxuICAgICAgICA6Y2xhc3M9XCJ7ICdpcy1hY3RpdmUnOiBpc0FjdGl2ZShpdGVtLnZhbHVlKSB9XCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICBAY2xpY2s9XCJjaGFuZ2VIZWxwZXIoaXRlbS52YWx1ZSlcIlxuICAgICAgPnt7IGl0ZW0ubGFiZWwgfX08L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC10b29sdGlwIHBsYWNlbWVudD1cImJvdHRvbVwiIGNvbnRlbnQ9XCLlr4bluqZcIj5cbiAgICAgICAg5a+G5bqmXG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnMsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgbW9kZWw6IHtcbiAgICBwcm9wOiAnbWVkaXVtJyxcbiAgICBldmVudDogJ2lucHV0JyxcbiAgfSxcbiAgcHJvcHM6IHtcbiAgICBtZWRpdW06IHtcbiAgICAgIHR5cGU6IFN0cmluZyxcbiAgICAgIGRlZmF1bHQ6ICdtZWRpdW0nLFxuICAgIH0sXG4gIH0sXG4gIHNldHVwKHByb3BzLCBjb250ZXh0KSB7XG4gICAgY29uc3QgY3R4ID0gZ2V0Q3VycmVudEluc3RhbmNlKCkuY3R4O1xuICAgIGNvbnN0IGRhdGEgPSByZWFjdGl2ZSh7XG4gICAgICBsaXN0OiBbXG4gICAgICAgIHsgbGFiZWw6ICfpu5jorqQnLCB2YWx1ZTogJ21lZGl1bScgfSxcbiAgICAgICAgeyBsYWJlbDogJ+S4reetiScsIHZhbHVlOiAnc21hbGwnIH0sXG4gICAgICAgIHsgbGFiZWw6ICfntKflh5EnLCB2YWx1ZTogJ21pbmknIH0sXG4gICAgICBdLFxuICAgIH0pO1xuICAgIGNvbnN0IGlzQWN0aXZlID0gZnVuY3Rpb24gKHZhbCkge1xuICAgICAgcmV0dXJuIHByb3BzLnZhbHVlID09PSB2YWw7XG4gICAgfTtcbiAgICBjb25zdCBjaGFuZ2VIZWxwZXIgPSBmdW5jdGlvbiAodmFsKSB7XG4gICAgICBjb250ZXh0LmVtaXQoJ2lucHV0JywgdmFsKTtcbiAgICAgIGlmICh2YWwgIT09IHByb3BzLnZhbHVlKSB7XG4gICAgICAgIGN0eC4kbmV4dFRpY2soKCkgPT4ge1xuICAgICAgICAgIGNvbnRleHQuZW1pdCgnY2hhbmdlJywgdmFsKTtcbiAgICAgICAgfSk7XG4gICAgICB9XG4gICAgfTtcbiAgICByZXR1cm4ge1xuICAgICAgLi4udG9SZWZzKGRhdGEpLFxuICAgICAgaXNBY3RpdmUsXG4gICAgICBjaGFuZ2VIZWxwZXIsXG4gICAgfTtcbiAgfSxcbn07XG48L3NjcmlwdD5cblxuXG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

``` vue
<script setup>
defineProps({ 
  model: {
    prop: 'value',
    event: 'input',
  },
  props: {
    value: {
      type: String,
      default: 'medium',
    },
  },
  setup(props, context) {
    const ctx = getCurrentInstance().ctx;
    const data = reactive({
      list: [
        { label: '默认', value: 'medium' },
        { label: '中等', value: 'small' },
        { label: '紧凑', value: 'mini' },
      ],
    });
    const isActive = function (val) {
      return props.value === val;
    };
    const changeHelper = function (val) {
      context.emit('input', val);
      if (val !== props.value) {
        ctx.$nextTick(() => {
          context.emit('change', val);
        });
      }
    };
    return {
      ...toRefs(data),
      isActive,
      changeHelper,
    };
  }
})
</script>
<template>
<el-popover
    width="70"
    placement="bottom-end"
    trigger="click"
    popper-class="popper-table-size"
  >
    <div class="list">
      <div
        v-for="item in list"
        class="list-item"
        :class="{ 'is-active': isActive(item.value) }"
        :key="item.value"
        @click="changeHelper(item.value)"
      >{{ item.label }}</div>
    </div>
    <template #reference>
      <app-icon icon="size" class="pad-b-sm"></app-icon>
    </template>
  </el-popover>
</template>
```

### What is Expected?

气泡框包裹文字提示组件，悬浮给出文字提示，气泡框点击弹出

### What is actually happening?

气泡框包裹文字提示组件，悬浮文字提示正常，点击无法弹出气泡框

### Additional comments

_(empty)_

**Comment by tolking** [comment]
You can try to understand the error message.

[reference](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHdpZHRoPVwiNzBcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbS1lbmRcIlxuICAgIHBvcHBlci1jbGFzcz1cInBvcHBlci10YWJsZS1zaXplXCJcbiAgPlxuICAgIDxkaXYgY2xhc3M9XCJsaXN0XCI+XG4gICAgICA8ZGl2XG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBsaXN0XCJcbiAgICAgICAgY2xhc3M9XCJsaXN0LWl0ZW1cIlxuICAgICAgICA6Y2xhc3M9XCJ7ICdpcy1hY3RpdmUnOiBpc0FjdGl2ZShpdGVtLnZhbHVlKSB9XCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICBAY2xpY2s9XCJjaGFuZ2VIZWxwZXIoaXRlbS52YWx1ZSlcIlxuICAgICAgPnt7IGl0ZW0ubGFiZWwgfX08L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDwhLS0gPHNwYW4+IC0tPlxuICAgICAgPGVsLXRvb2x0aXAgcGxhY2VtZW50PVwiYm90dG9tXCIgY29udGVudD1cIuWvhuW6plwiPlxuICAgICAgICDlr4bluqZcbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDwhLS0gPC9zcGFuPiAtLT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuaW1wb3J0IHsgcmVhY3RpdmUsIHRvUmVmcywgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJztcblxuZXhwb3J0IGRlZmF1bHQge1xuICBtb2RlbDoge1xuICAgIHByb3A6ICdtZWRpdW0nLFxuICAgIGV2ZW50OiAnaW5wdXQnLFxuICB9LFxuICBwcm9wczoge1xuICAgIG1lZGl1bToge1xuICAgICAgdHlwZTogU3RyaW5nLFxuICAgICAgZGVmYXVsdDogJ21lZGl1bScsXG4gICAgfSxcbiAgfSxcbiAgc2V0dXAocHJvcHMsIGNvbnRleHQpIHtcbiAgICBjb25zdCBjdHggPSBnZXRDdXJyZW50SW5zdGFuY2UoKS5jdHg7XG4gICAgY29uc3QgZGF0YSA9IHJlYWN0aXZlKHtcbiAgICAgIGxpc3Q6IFtcbiAgICAgICAgeyBsYWJlbDogJ+m7mOiupCcsIHZhbHVlOiAnbWVkaXVtJyB9LFxuICAgICAgICB7IGxhYmVsOiAn5Lit562JJywgdmFsdWU6ICdzbWFsbCcgfSxcbiAgICAgICAgeyBsYWJlbDogJ+e0p+WHkScsIHZhbHVlOiAnbWluaScgfSxcbiAgICAgIF0sXG4gICAgfSk7XG4gICAgY29uc3QgaXNBY3RpdmUgPSBmdW5jdGlvbiAodmFsKSB7XG4gICAgICByZXR1cm4gcHJvcHMudmFsdWUgPT09IHZhbDtcbiAgICB9O1xuICAgIGNvbnN0IGNoYW5nZUhlbHBlciA9IGZ1bmN0aW9uICh2YWwpIHtcbiAgICAgIGNvbnRleHQuZW1pdCgnaW5wdXQnLCB2YWwpO1xuICAgICAgaWYgKHZhbCAhPT0gcHJvcHMudmFsdWUpIHtcbiAgICAgICAgY3R4LiRuZXh0VGljaygoKSA9PiB7XG4gICAgICAgICAgY29udGV4dC5lbWl0KCdjaGFuZ2UnLCB2YWwpO1xuICAgICAgICB9KTtcbiAgICAgIH1cbiAgICB9O1xuICAgIHJldHVybiB7XG4gICAgICAuLi50b1JlZnMoZGF0YSksXG4gICAgICBpc0FjdGl2ZSxcbiAgICAgIGNoYW5nZUhlbHBlcixcbiAgICB9O1xuICB9LFxufTtcbjwvc2NyaXB0PlxuXG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by norangit** [comment]
改成这样。。。

` <template #reference>
       <div>
         <el-tooltip placement="bottom" content="密度">
        密度
      </el-tooltip>
       </div>
    </template>`
