### ISSUE TITLE
[Bug Report] [Component] [input] Input textarea 最大高度无效

### ISSUE THREAD

**Issue by norangit** [element-plus/element-plus#8151]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome 101`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwidGV4dGFyZWEyXCJcbiAgICA6YXV0b3NpemU9XCJ7IG1pblJvd3M6IDIsIG1heFJvd3M6IDQgfVwiXG4gICAgdHlwZT1cInRleHRhcmVhXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdGV4dGFyZWExID0gcmVmKCcnKVxuY29uc3QgdGV4dGFyZWEyID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

如链接，最大高度4

### What is Expected?

在调整大小的时候最大高度不应该超过4行

### What is actually happening?

在调整大小的时候最大高度超过了4行，而且没有最大高度限制

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Design so.
