### ISSUE TITLE
[Bug Report] [TypeScript] [All] vue3 + ts 使用

### ISSUE THREAD

**Issue by PickClass** [element-plus/element-plus#8152]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.4`
- Browser / OS: `Edge`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

JSX 元素类型“ElCard”不具有任何构造签名或调用签名。

### What is Expected?

JSX 元素类型“ElCard”不具有任何构造签名或调用签名。

### What is actually happening?

JSX 元素类型“ElCard”不具有任何构造签名或调用签名。

### Additional comments

_(empty)_

**Comment by PickClass** [comment]
![image](https://user-images.githubusercontent.com/35389878/172354110-3867ff7b-c7bc-417b-b428-c578d0a9b655.png)

**Comment by sxzz** [comment]
https://github.com/johnsoncodehk/volar/issues/1405#issuecomment-1149618450
