### ISSUE TITLE
[Bug Report] [Style] [button] chrome83 button组件全部显示成灰色

### ISSUE THREAD

**Issue by 759826115** [element-plus/element-plus#8153]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.2`
- Browser / OS: `chrome 83.0.4103.116`
- Build Tool: `CDN`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

使用chrome83打开手册中button组件，基础用法中的按钮全部为灰色

### What is Expected?

显示正常对应的颜色

### What is actually happening?

全部显示为灰色

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
#7977 尝试升级到 2.2.3 及以上
