### ISSUE TITLE
[Bug Report] [Component] [date-picker] Date range picker throws error in latest version

### ISSUE THREAD

**Issue by plehnen** [element-plus/element-plus#8156]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome (latest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/date-picker.html#date-range)

### Steps to reproduce

Open the docs at the Date Range example. Enter a date in the first field (i.e. "2022-06-01") and click in the next input or everywhere else.

### What is Expected?

It should still work.

### What is actually happening?

An error is thrown: Uncaught TypeError: je.value.isValidValue is not a function

### Additional comments

_(empty)_

**Comment by static7** [comment]
请问这个bug 什么时候发布修复后版本?
