### ISSUE TITLE
[Bug Report] [Component] [color-picker] 点击el-color-picker组件打开取色器面板后，先选择predefine预定义颜色的其中一个，然后点击清除按钮或者点击空白区域关闭面板，重新打开面板后，predefine预定义颜色无法选中了

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#8157]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/MWQqowX)

### Steps to reproduce

```vue
<script setup>
defineProps({ /* ... */ })
</script>

<template>
  <el-color-picker v-model="picker" :predefine="predefineList" />
</template>
```

### What is Expected?

再次打开取色器面板，预定义的颜色可以选中

### What is actually happening?

预定义的颜色无法选中

### Additional comments

_(empty)_

**Comment by hzf-666** [comment]
这个bug解决了吗

**Comment by btea** [comment]
已经解决，你更新到最新版试试

**Comment by hzf-666** [comment]
好的，谢谢
