### ISSUE TITLE
[Bug Report] 按需导入（自动导入） ElSubMenu引入样式时报错

### ISSUE THREAD

**Issue by MagicYuze** [element-plus/element-plus#8164]
### Element Plus version
2.2.4

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

### Vue version
3.2.25

### Reproduction Link
https://codesandbox.io/

### Steps to reproduce
实在不好意思，不太知道怎么复现。就是自动引入的时候ElSubMenu的文件名写错了，写成ElSubmenu了。导入的时候路径写的是element-plus/es/components/submenu/  实际路径是element-plus/es/components/sub-menu

https://github.com/element-plus/element-plus/issues/6304
和这个issue是一样的，反馈说已经解决了。但是我用的2.2.4版本还是出现了这个问题

### What is Expected?
能够正常引入

### What is actually happening?
报错，[vite] Internal server error: Failed to resolve import "element-plus/es/components/submenu/style/css" from "src/layout/components/menubarItem.vue". Does the file exist?

**Comment by chenxch** [comment]
unplugin-vue-components 版本多少哈

**Comment by MagicYuze** [comment]
> unplugin-vue-components 版本多少哈

    "unplugin-auto-import": "^0.8.7",
    "unplugin-vue-components": "^0.19.6",
昨天直接用npm install -D unplugin-vue-components unplugin-auto-import安装的

**Comment by MagicYuze** [comment]
抱歉 是我的标签写错了 vue2的时候element-ui 用的是el-submenu vue3变成了el-sub-menu
