### ISSUE TITLE
[Bug Report] [Component] [slider] Slider组件的change事件，松开鼠标后获取的值在某个场景下，与想要获取的值不符

### ISSUE THREAD

**Issue by trtst** [element-plus/element-plus#8171]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixjb21wdXRlZCwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgdmFsID0gdmFsO1xuICBjb25zb2xlLmxvZyhcImNoYW5nZTpcIiwgdmFsKVxufVxuY29uc3QgdmFsdWUgPSByZWYoMClcbnNldEludGVydmFsKCgpID0+IHtcbiAgICB2YWx1ZS52YWx1ZSArK1xufSwgMjAwKTtcbmNvbnN0IHZhbCA9IGNvbXB1dGVkKCgpID0+IHtcbiAgICByZXR1cm4gdmFsdWUudmFsdWUgKiAuMlxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gIDxlbC1zbGlkZXIgQGNoYW5nZT1cIm9uQ2hhbmdlXCIgdi1tb2RlbD1cInZhbFwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在某个场景下，如视频/音频播放的时候，滑动条是在实时更新的，也就是说v-model是在实时更改的，此时我们拖拽滑动条，在鼠标松开以后，我们应该想要的是松开后拖拽的值，但是因为v-model是实时更改的，导致获取的值不符合预期。

### What is Expected?

滑动条在实时更改的时候，拖拽滑动条，在鼠标松开后，获取松开时滑动条的值，而不是v-model的值

### What is actually happening?

实际上获取的是v-model的值

### Additional comments

另外，v-model的值在经过 computed处理过的时候，我们拖拽滑动条更改v-model值，console会提示 ”computed value is readonly“

**Comment by chenxch** [comment]
[slider dynamic value demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixjb21wdXRlZCwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgdmFsID0gdmFsO1xuICBjb25zb2xlLmxvZyhcImNoYW5nZTpcIiwgdmFsKVxufVxuY29uc3QgdmFsdWUgPSByZWYoMClcbnNldEludGVydmFsKCgpID0+IHtcbiAgICB2YWx1ZS52YWx1ZSs9MC4yXG59LCAyMDApO1xuY29uc3QgdmFsID0gY29tcHV0ZWQoe1xuICBnZXQoKXtcbiAgICByZXR1cm4gdmFsdWUudmFsdWVcbiAgfSxcbiAgc2V0KHZhbCl7XG4gICAgdmFsdWUudmFsdWUgPSB2YWxcbiAgfVxufSlcbmNvbnN0IG9uSW5wdXQgPSAodmFsdWUpID0+IHtcbiAgY29uc29sZS5sb2coJ29uSW5wdXQnLCB2YWx1ZSlcbiAgdmFsLnZhbHVlID0gdmFsdWVcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gIDxlbC1zbGlkZXIgQGNoYW5nZT1cIm9uQ2hhbmdlXCIgdi1tb2RlbD1cInZhbFwiIEBpbnB1dD1cIm9uSW5wdXRcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)  
computed的用法不止一种哦

**Comment by trtst** [comment]
> [slider dynamic value demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixjb21wdXRlZCwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgdmFsID0gdmFsO1xuICBjb25zb2xlLmxvZyhcImNoYW5nZTpcIiwgdmFsKVxufVxuY29uc3QgdmFsdWUgPSByZWYoMClcbnNldEludGVydmFsKCgpID0+IHtcbiAgICB2YWx1ZS52YWx1ZSs9MC4yXG59LCAyMDApO1xuY29uc3QgdmFsID0gY29tcHV0ZWQoe1xuICBnZXQoKXtcbiAgICByZXR1cm4gdmFsdWUudmFsdWVcbiAgfSxcbiAgc2V0KHZhbCl7XG4gICAgdmFsdWUudmFsdWUgPSB2YWxcbiAgfVxufSlcbmNvbnN0IG9uSW5wdXQgPSAodmFsdWUpID0+IHtcbiAgY29uc29sZS5sb2coJ29uSW5wdXQnLCB2YWx1ZSlcbiAgdmFsLnZhbHVlID0gdmFsdWVcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gIDxlbC1zbGlkZXIgQGNoYW5nZT1cIm9uQ2hhbmdlXCIgdi1tb2RlbD1cInZhbFwiIEBpbnB1dD1cIm9uSW5wdXRcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) computed的用法不止一种哦

嗯嗯  抱歉哈，的确是可以了！  是我自己写法有问题！ 测试可以达到想要的效果！  谢谢了哈！   感谢~~~

**Comment by chenxch** [comment]
> > [slider dynamic value demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixjb21wdXRlZCwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IG9uQ2hhbmdlID0gKHZhbDpudW1iZXIpID0+IHtcbiAgdmFsID0gdmFsO1xuICBjb25zb2xlLmxvZyhcImNoYW5nZTpcIiwgdmFsKVxufVxuY29uc3QgdmFsdWUgPSByZWYoMClcbnNldEludGVydmFsKCgpID0+IHtcbiAgICB2YWx1ZS52YWx1ZSs9MC4yXG59LCAyMDApO1xuY29uc3QgdmFsID0gY29tcHV0ZWQoe1xuICBnZXQoKXtcbiAgICByZXR1cm4gdmFsdWUudmFsdWVcbiAgfSxcbiAgc2V0KHZhbCl7XG4gICAgdmFsdWUudmFsdWUgPSB2YWxcbiAgfVxufSlcbmNvbnN0IG9uSW5wdXQgPSAodmFsdWUpID0+IHtcbiAgY29uc29sZS5sb2coJ29uSW5wdXQnLCB2YWx1ZSlcbiAgdmFsLnZhbHVlID0gdmFsdWVcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbiAgXG4gIDxlbC1zbGlkZXIgQGNoYW5nZT1cIm9uQ2hhbmdlXCIgdi1tb2RlbD1cInZhbFwiIEBpbnB1dD1cIm9uSW5wdXRcIiAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) computed的用法不止一种哦
> 
> 嗯嗯 抱歉哈，的确是可以了！ 是我自己写法有问题！ 测试可以达到想要的效果！ 谢谢了哈！ 感谢~~~

问题解决了就好哈。
Have a good day.🤟
