### ISSUE TITLE
[Bug Report] [TypeScript] [All] 2.2.4 导致其他组件类型报错  

### ISSUE THREAD

**Issue by missile-xuan** [element-plus/element-plus#8172]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]( 因为现象是影响其他组件  导致无法打包 )

### Steps to reproduce

正常引入router pinia
项目没有锁小版本 重新拉取升级后ts报错 但是可运行 不可打包
自己排查后发现 element2.2.4 导致 router和 pinia类型报错
类型“Pinia”的参数不能赋给类型“Plugin_2”的参数。

回退版本测试：
2.2.2 好的
2.2.3 element找不到包（看日志有修复类型bug）
2.2.4 导致其他组件类型报错 

### What is Expected?

正常打包

### What is actually happening?

导致类型报错

### Additional comments

_(empty)_

**Comment by missile-xuan** [comment]
![image](https://user-images.githubusercontent.com/38873815/172527917-08e90c4d-6840-4c21-a437-4597afd7a0b1.png)
锁版本2.2.2 不会出现此问题  一切正常

**Comment by Delevin888** [comment]
唉，我也折腾半天，发现是element plus 的问题，但是太菜了，没找到办法，先把它 as any 了。

**Comment by HaoAu3** [comment]
我也是，弄了很多，发现是版本的问题，手贱升级了最新版，本来2.2.2用得好好的。

**Comment by missile-xuan** [comment]
@HaoAu3 我刚开始怎么都没想到会是element影响的  一直以为是vue和ts的问题   最后一个一个包锁住  试了一上午

**Comment by Robin-ou** [comment]
@missile-xuan  昨天下午弄了一下午最后还是还原element-plus版本就好了，好像是2.2.4的TS类型文件写得有点问题

**Comment by Robin-ou** [comment]
@HaoAu3 和你一样，本来开发蛮好的，看着官方更新版本了，重新下了依赖就GG了。。。

**Comment by dcyuki** [comment]
我也遇到了这个问题，还以为是改了别的组件改炸了，回滚一下版本就好了

**Comment by sxzz** [comment]
It will be resolved in the next version.

**Comment by L1yp** [comment]
还以为是我的问题。。。
