### ISSUE TITLE
Table [Vue warn]: event "cell-contextmenu"

### ISSUE THREAD

**Issue by lihaotian0607** [element-plus/element-plus#818]
Component emitted event "cell-contextmenu" but it is neither declared in the emits option nor as an "onCell-contextmenu" prop.

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by justwiner** [comment]
I think it's a new feature, not a bug.
The `cell ContextMenu` event is not included in the `element-ui/Table`

![image](https://user-images.githubusercontent.com/30335393/101130773-0f273780-363f-11eb-98ba-9232e3d35b9f.png)

But this is a good suggestion, and it can be implemented in the next release.

**Comment by justwiner** [comment]
You can do the same with the following code
```js
... ...
<el-table-column label="标题" width="300">
    <template v-slot="scope">
        <div
            @contextmenu="
                () => {
                    doSomething(scope)
                }
            "
        >
            {{ scope.row.title }}
        </div>
    </template>
</el-table-column>
... ...
```

**Comment by wellfrog16** [comment]
这个错误不是右键事件写错了。
而是我在table右键（我并不需要右键事件），就会报一个warnning，官网table可见
Component emitted event "cell-contextmenu" but it is neither declared in the emits option nor as an "onCell-contextmenu" prop.

@justwiner @JeremyWuuuuu 

#2074
