### ISSUE TITLE
[Bug Report] [Component] [input-number] el-input-number组件在清除输入的情况下，输入中文会出现光标错位问题

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#8181]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

```vue
<script setup>
defineProps({ /* ... */ })
</script>

<template>
  <el-input-number v-model="num" :min="1" :max="10" @change="handleChange" />
</template>
```

### What is Expected?

光标处于输入框中间

### What is actually happening?

光标错位到左上角

### Additional comments

_(empty)_

![4G9~WK3KHOR{XWOV~ @ACWR](https://user-images.githubusercontent.com/55825301/172575717-7889272b-1ec6-4939-b217-6207bae000a2.png)

**Comment by YunYouJun** [comment]
TIP：使用中文输入法可以复现。
