### ISSUE TITLE
[Bug Report] [Component] [form, form-item] el-form组件点击el-form-item的label区域，会使内容区域里的el-input和el-select等组件聚焦

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#8184]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/form.html)

### Steps to reproduce

1.打开链接
2.选择一个示例并点击其中一个label

### What is Expected?

不希望出现聚焦行为

### What is actually happening?

内容区域会自动聚焦

### Additional comments

_(empty)_

**Comment by CarterLi** [comment]
label的作用不就是让label绑定的输入框聚焦么？

**Comment by hzf-666** [comment]
> 
![image](https://user-images.githubusercontent.com/55825301/172813879-997449a3-3561-4292-9edb-4e0e3693fdfd.png)
点击这里输入框会聚焦不是很奇怪吗，是设计就如此的吗

**Comment by hawind** [comment]
这个设计，花那么大的力气，而且还不能关闭选项。并且看了源码，强行给你安排上。
label本身默认可以用for让表单聚焦，可是可是我猜开发想让不是文本框也这样，个人感觉看到这个感觉难受的要死，一不小心点到旁边就出现了，各种弹出框。

**Comment by hzf-666** [comment]
> 这个设计，花那么大的力气，而且还不能关闭选项。并且看了源码，强行给你安排上。 label本身默认可以用for让表单聚焦，可是可是我猜开发想让不是文本框也这样，个人感觉看到这个感觉难受的要死，一不小心点到旁边就出现了，各种弹出框。

我也觉得如果是这么设计的话，最好有个自己选择开启与否

**Comment by hawind** [comment]
> 这种问题，自己多研究研究相关知识再来提bug，节省下时间好让开发者能fix真正的bug 首先label的作用就是用来如此的，点击label，使得input等实现focused
> 
> 如果你不想要这种效果，可以通过css禁用
> 
> `.el-form-item__label{ pointer-events: none; }`

1.确实不能触发事件了，可是这样又破坏了原本的事件，input框点击聚焦我觉得还是挺好的，请问这个又怎么办呢
2.套用上面的一句话，有时间多修点bug不好吗，bug最近不是挺多的嘛，加这个东西的意义何在。

**Comment by norangit** [comment]
> > 这种问题，自己多研究研究相关知识再来提bug，节省下时间好让开发者能fix真正的bug 首先label的作用就是用来如此的，点击label，使得input等实现focused
> > 如果你不想要这种效果，可以通过css禁用
> > `.el-form-item__label{ pointer-events: none; }`
> 
> 1.确实不能触发事件了，可是这样又破坏了原本的事件，input框点击聚焦我觉得还是挺好的，请问这个又怎么办呢 2.套用上面的一句话，有时间多修点bug不好吗，bug最近不是挺多的嘛，加这个东西的意义何在。

什么意思，你不是不想要点击label的时候聚焦么？加上上面的css不就实现不聚焦了吗？label上你想监听点击事件？还是想监听别的事件，如果是这样，那你可以看看mdn官方文档 pointer-events 的值有多种，可以根据需求取值
