### ISSUE TITLE
[Bug Report] [Component] [affix] 固钉效果在非顶级滚动容器中失效

### ISSUE THREAD

**Issue by royisyoung** [element-plus/element-plus#8186]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome/102.0.5005.61`
- Build Tool: `Vite`

### Related Component

- `el-affix`

### Reproduction Link

[CodePen](https://codepen.io/royisyoung/pen/jOZvgJO)

### Steps to reproduce

拖动滚动条

### What is Expected?

在滚动容器中，将指定内容固定在容器顶部

### What is actually happening?

指定内容没有固定

### Additional comments

组件内使用useElementBounding监听了window的滚动事件，现在这个事件默认的useCapture从true变成了false，导致不能正确监听容器的滚动事件

**Comment by royisyoung** [comment]
> target 可以给你服务

例子已经更新，target也没有使固钉生效。

**Comment by liangmeisheng** [comment]
添加offset可以生效

**Comment by royisyoung** [comment]
[例子](https://codepen.io/royisyoung/pen/jOZvgJO)已经更新，可以看到在以Windows为滚动容器和在父级滚动容器中的不同表现。
