### ISSUE TITLE
Select  [Vue warn] declare it using the "emits" option. 

### ISSUE THREAD

**Issue by lqsong** [element-plus/element-plus#819]
> [Vue warn]: Extraneous non-emits event listeners (beforeEnter) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 

![image](https://user-images.githubusercontent.com/22975974/101108502-965cb700-360f-11eb-8620-fac8ac112635.png)

**Comment by JeremyWuuuuu** [comment]
Closing, because this is a issue from Vue instead of us. After the version gets bumped to 3.0.4 it should be fixed
