### ISSUE TITLE
Popconfirm in the Table，overflow: hidden; 

### ISSUE THREAD

**Issue by lqsong** [element-plus/element-plus#820]
[https://github.com/element-plus/element-plus/issues/778](https://github.com/element-plus/element-plus/issues/778)

`beta.3`

![image](https://user-images.githubusercontent.com/22975974/101108975-bc368b80-3610-11eb-99a0-6e5bfa79e7e9.png)

**Still unresolved**

**Comment by JeremyWuuuuu** [comment]
Fixed last night but @zazzaz made a mistake, will come out in beta.4
