### ISSUE TITLE
[Bug Report] [Component] [pagination] el-pagination page-size和layout="sizes" 同时设置时 组件显示不出来

### ISSUE THREAD

**Issue by rashagu** [element-plus/element-plus#8204]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Reproduction Link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnaW5hdGlvblxuICAgIDpwYWdlLXNpemU9XCIyMDBcIlxuICAgIDpwYWdlLXNpemVzPVwiWzUsIDIwLCAzMF1cIlxuICAgIDpwYWdlci1jb3VudD1cIjExMTFcIlxuICAgIGxheW91dD1cInByZXYsIHNpemVzLCBwYWdlciwgbmV4dFwiXG4gICAgOnRvdGFsPVwiMTAwMFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

 page-size和layout="sizes" 同时设置
```
  <el-pagination
    :page-size="200"
    :page-sizes="[5, 20, 30]"
    :pager-count="1111"
    layout="prev, sizes, pager, next"
    :total="1000"
  />
```

### What is Expected?

可以正常显示

### What is actually happening?

不显示
```
ElementPlusError: [ElPagination] Deprecated usages detected, please refer to the el-pagination documentation for more details
    at debugWarn (error.ts:13:37)
    at Proxy.<anonymous> (pagination.ts:192:9)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5694:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5708:9)
    at mountComponent (runtime-core.esm-bundler.js:5490:9)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
```

### Additional comments

_(empty)_

**Comment by Tsong-LC** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/50739490/173020544-605e7e42-c8d4-4434-b6b6-c617d434a8f7.png">

**Comment by rashagu** [comment]
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/50739490/173020544-605e7e42-c8d4-4434-b6b6-c617d434a8f7.png">

解决了 谢谢 但是
我用jsx 加的是`onSize-change` 没有效果，`onCurrent-change`也没有效果。
`onUpdate:page-size`和`onUpdate:current-page` 是可以的
