### ISSUE TITLE
ElSelect组件点击出现vue warning报错

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#821]
![6XKVSBDWJ13QS6FSNJWLRH6](https://user-images.githubusercontent.com/34828964/101116128-77feb780-361f-11eb-92f8-fe279d2358a9.png)
以下是我的代码
`
<el-select placeholder="请选择需要上传的文件类型">
        <el-option
          v-for="item in options"
          :key="item.value"
          :label="item.label"
          :value="item.value"
        >
        </el-option>
      </el-select>
`

**Comment by JeremyWuuuuu** [comment]
Duplicate with #819 , this came from `Vue`, bumping you version to `3.0.4` this should be solved.
