### ISSUE TITLE
[Feature Request] ElMessageBox confirm button style

### ISSUE THREAD

**Issue by wjw-gavin** [element-plus/element-plus#8213]
### Existing Component
Yes

### Component Name
el-message-box

### Description
Hello, I learned that this is not a bug, but now the product department does not agree, after opening messagebox that confirm button is the focus state of the display, so I want to know whether to give a popover property to control of focusing on the first focusable item when opening?

https://github.com/element-plus/element-plus/issues/6773
and https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html DOCUMENT NOT FOUND

**Comment by wjw-gavin** [comment]
A 500 error occurred when I created it from here
<img width="819" alt="image" src="https://user-images.githubusercontent.com/19986739/173069739-ee040dc1-ef85-42e5-be28-13172a9dd3d0.png">

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/19986739/173069629-56f15e5f-874c-41c7-9332-a80126d72e86.png">

**Comment by weipxiu** [comment]
显然，这就是 bug，因为我也遇到了

**Comment by wjw-gavin** [comment]
> 显然，这就是 bug，因为我也遇到了

https://github.com/element-plus/element-plus/issues/6773   这里他们说不是一个bug...

**Comment by darkXmo** [comment]
> (other，A 500 error occurred when I created it from here) <img alt="image" width="819" src="https://user-images.githubusercontent.com/19986739/173069739-ee040dc1-ef85-42e5-be28-13172a9dd3d0.png">
> 
> <img alt="image" width="1030" src="https://user-images.githubusercontent.com/19986739/173069629-56f15e5f-874c-41c7-9332-a80126d72e86.png">

so did i, while https://elementui.github.io/issue-generator/#/en-US?repo=element-plus works ok.

**Comment by wjw-gavin** [comment]
> 

Yes, I created this from here. thanks!

**Comment by weipxiu** [comment]
有找到取消配置项么？

**Comment by wjw-gavin** [comment]
> 



> 有找到取消配置项么？
没有，暂时用的这个，不会一打开就默认聚焦
![image](https://user-images.githubusercontent.com/19986739/173275770-93ed39f5-e19f-4f3b-9540-aa04b0dcd68b.png)

**Comment by YunYouJun** [comment]
This is inherited from element-ui's design, which I think has a11y considerations in it.

I've had discussions with current designers and we think it's possible to remove its active state by default and provide an enhanced attribute `autofocus` to allow users to actively turn it on.

I'll finish it this week, please wait a while.

**Comment by Giwayume** [comment]
Could probably move the backgroun color change from `:focus` to `:focus-visible`, that way default accessibility is not impacted,

**Comment by YunYouJun** [comment]
Done. Anyone want to review it?

https://github.com/element-plus/element-plus/pull/8445

**Comment by YunYouJun** [comment]
> Could probably move the background color change from `:focus` to `:focus-visible`, that way default accessibility is not impacted and no Javascript change is needed.
> 
> People who need accessibility features rely on frameworks implementing them by default, because website developers rarely pay attention to it.

Yeah, thanks for the suggestion, but I think `:focus-visible` for outline.

<img width="104" alt="image" src="https://user-images.githubusercontent.com/25154432/175616219-97f0b53a-a4ad-4158-bfd3-a573639e8076.png">

So how about we change it through properties `autofocus` here?
