### ISSUE TITLE
DateTimePicker 设定默认的起始与结束时刻后，选择日期，显示Invalid Date 

### ISSUE THREAD

**Issue by wushuxuan** [element-plus/element-plus#822]
![image](https://user-images.githubusercontent.com/30644407/101120073-a5e7fa00-3627-11eb-9a36-a65a2555a119.png)

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz

**Comment by wushuxuan** [comment]
是的，我发现了是因为dayjs转换的问题，刚提了pull requests兼容了一下

**Comment by zazzaz** [comment]
This is a doc error. You can check here https://github.com/element-plus/element-plus/issues/162#issuecomment-694793880 

defaultTime option accept Date object not a time string.

You can pass 
```
:default-time="[new Date(2000,1,1,12,0,0)]" 
```

to set default time to 12:00:00.

I'll update the doc shortly.
