### ISSUE TITLE
[Bug Report] el-option指定选项的disabled设置为true之后，依然可以被点击，并执行了对应的@click的方法

### ISSUE THREAD

**Issue by ilobos** [element-plus/element-plus#8246]
### Element Plus version
2.2.5

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36

### Vue version
3.2.37

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-42gzjh?file=/src/App.vue

### Steps to reproduce
<el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
      :disabled="item.disabled"
      @click="select(item)"
    />
select(item) {
    console.log("=== 我被点击了 ===");
    return;
}
当点击“Option2”时，依然可以点击（虽然明面上不被选中）；并且每次都会打印上述文案（即使disabled依然执行click的方法）。
当已经选中“Option1”时，再次点击“Option1”时，依然可以点击（虽然明面上不会发生任何变化）；并且每次都会打印上述文案（即使已经选中，依然会再次执行click的方法）。

### What is Expected?
下拉选项被禁用后不能点击；且不能运行 @click 对应的方法。
下拉选项已被选中后不能再次点击；且不能重复运行 @click 对应的方法。

### What is actually happening?
下拉选禁用后依然能被点击，并且打印了相应的内容，执行了不必要的业务逻辑代码。
下拉选已被选中后依然能被点击，并且打印了相应的内容，重复执行了不必要的业务逻辑代码。

**Comment by chenxch** [comment]
我认为这个并不属于组件问题，而且使用问题哦。它并不像input/button这类可以依靠原生的disabled去屏蔽这个click。你有item了你应该知道他disabled，你可以做对应的处理，为什么会重复执行不必要的业务逻辑代码呢？

**Comment by ilobos** [comment]
我用change确实是正确的操作； 但是如果该组件的disabled不能禁止掉click，那为什么button的disabled就能禁止掉click呢？

> 我认为这个并不属于组件问题，而且使用问题哦。它并不像input/button这类可以依靠原生的disabled去屏蔽这个click。你有item了你应该知道他disabled，你可以做对应的处理，为什么会重复执行不必要的业务逻辑代码呢？

**Comment by iamkun** [comment]
请按文档设计的方式使用
```
<el-select @change="onChange" v-model="value" >
```

这个 change 事件是会处理 disabled 的逻辑的

el-option 上的 click 事件不是标准用法，就要自己处理了

**Comment by ilobos** [comment]
我觉得没问题，毕竟我用change确实是正确的操作；既然你们觉得click没必要屏蔽，那就继续错下去吧，

> 请按文档设计的方式使用
> 
> ```
> <el-select @change="onChange" v-model="value" >
> ```
> 
> 这个 change 事件是会处理 disabled 的逻辑的
> 
> el-option 上的 click 事件不是标准用法，就要自己处理了
