### ISSUE TITLE
[Bug Report] 利用unplugin-auto-import引入组件，在修改文件热更新后进行重载导致样式丢失

### ISSUE THREAD

**Issue by Pudon** [element-plus/element-plus#8250]
### Element Plus version
2.2.5

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### Vue version
3.2.25

### Reproduction Link
https://github.com/Pudon/vue3-demo

### Steps to reproduce
1. npm run dev
2. 修改一点代码-热更新
3. 浏览器点击重载
4. 再点击显示消息-样式丢失

### What is Expected?
ElMessage样式显示正常

### What is actually happening?
ElMessage样式丢失

**Comment by Pudon** [comment]
![image](https://user-images.githubusercontent.com/30598142/173372516-67cc69c0-f76d-49b9-b191-e6821b1dcd5e.png)

> 正常是有引入css

 hmr update 后 浏览器重载后

![image](https://user-images.githubusercontent.com/30598142/173374686-35fca812-1ac9-4c1f-8989-142626115191.png)

> 少了自动引入css

**Comment by chenxch** [comment]
Maybe this problem can be solved faster in [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import/issues).

**Comment by tjlicc** [comment]
之前遇到过类似的问题，不过我的style部分用的是<style lang="scss">；我先把它改成<style>，保存后等热更新一遍；再改回<style lang="scss">，保存后热更新一下，样式就正常了

**Comment by btea** [comment]
fixed https://github.com/antfu/unplugin-auto-import/pull/213
