### ISSUE TITLE
Extraneous non-props attributes

### ISSUE THREAD

**Issue by jahnli** [element-plus/element-plus#826]
Extraneous non-props attributes (align, unlink-panels) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Picker format="YYYY-MM-DD" type="daterange" modelValue=""  ... > 
  at <ElDatePicker modelValue="" onUpdate:modelValue=fn type="daterange"  ... > 
  at <Report onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <ElMain> 
  at <ElContainer class="layout-content" > 
  at <ElContainer class="layout" > 
  at <Admin onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

时间选择题问题

**Comment by JeremyWuuuuu** [comment]
Duplicate with #821 #819  Please upgrade your local version of `Vue` to `^3.0.4` this problem will be solved. And please search issues before raising one, that will save the maintainers lots of time. Thank you

**Comment by kulipo** [comment]
#921 has fixed, but I found that in the vue version3.0.4, el-date-picker still has this warning, Would you please help to check it.
"element-plus": "^1.0.1-beta.7"
"vue": "^3.0.4"

**Comment by jahnli** [comment]
Yes, I still get a warning when I try to upgrade

**Comment by kulipo** [comment]
There has two demo on official website:
"Date Range
Picking a date range is supported.
Default          With quick options"
use Default is OK, when use "With quick options", there has  warning.
this is the details of the question.

**Comment by kulipo** [comment]
when use attribute “align” or "unlink-panels" for <el-date-picker />，the issues can occur.  my local version of Vue is ^3.0.4.

**Comment by JeremyWuuuuu** [comment]
cc @zazzaz 
Also, FYI, some attribute has already been removed from `el-date-picker`: check this out https://github.com/element-plus/element-plus/issues/162#issuecomment-676052160

**Comment by Grubby520** [comment]
Attributes “value-format” ，has it been cancelled?

**Comment by zazzaz** [comment]
> Attributes “value-format” ，has it been cancelled?

@Grubby520 Yes

Since we have Day.js already, all you have to do is to
```
import dayjs from 'dayjs'
dayjs(value).format('YYYY')
```

**Comment by xiaolannuoyi** [comment]
@JeremyWuuuuu 
3.0.7 has the same problem

[](https://element-plus.org/#/zh-CN/component/datetime-picker)
![image](https://user-images.githubusercontent.com/21079721/110077143-97dd7d00-7dc0-11eb-9191-a8558f1adbac.png)

**Comment by Ryan2128** [comment]
> @JeremyWuuuuu
> 3.0.7 has the same problem
> 
> 
> ![image](https://user-images.githubusercontent.com/21079721/110077143-97dd7d00-7dc0-11eb-9191-a8558f1adbac.png)

cc @zazzaz

**Comment by Panamer** [comment]
（problem） 括号内的problem就是你代码有问题的地方。

**Comment by giserman001** [comment]
@JeremyWuuuuu  vue3.0.11  一样的问题
![image](https://user-images.githubusercontent.com/24283342/123579223-13e55000-d80a-11eb-991a-5ac495d05786.png)

**Comment by ssw1992** [comment]
![image](https://user-images.githubusercontent.com/24841397/142821492-22a0ba67-9178-48a1-b7fb-578eeb50ea8b.png)
I meet the same problem too.

**Comment by ssw1992** [comment]
I meet same problem too.
![image](https://user-images.githubusercontent.com/24841397/142821615-e4de5872-5e1e-4a4b-9673-81f0d979c412.png)

**Comment by ssw1992** [comment]
in ^1.2.0-beta.3

**Comment by Panamer** [comment]
What


| |
Panamera
|
|
***@***.***
|
签名由网易邮箱大师定制


On 11/22/2021 ***@***.***> wrote：

in ^1.2.0-beta.3

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
