### ISSUE TITLE
[Bug Report] [Component] [autocomplete] el-autocomplete popup can be opened when it gets focus even if it is readonly

### ISSUE THREAD

**Issue by MyNameIsNico** [element-plus/element-plus#8278]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome/Windows`
- Build Tool: `Vue CLI`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgICAgPGVsLWF1dG9jb21wbGV0ZVxuICAgICAgICB2LW1vZGVsPVwic3RhdGUxXCJcbiAgICAgICAgOmZldGNoLXN1Z2dlc3Rpb25zPVwicXVlcnlTZWFyY2hcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgICAgY2xhc3M9XCJpbmxpbmUtaW5wdXQgdy01MFwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgcmVhZG9ubHlcbiAgICAgICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgUmVzdGF1cmFudEl0ZW0ge1xuICB2YWx1ZTogc3RyaW5nXG4gIGxpbms6IHN0cmluZ1xufVxuXG5jb25zdCBzdGF0ZTEgPSByZWYoJycpXG5cbmNvbnN0IHJlc3RhdXJhbnRzID0gcmVmPFJlc3RhdXJhbnRJdGVtW10+KFtdKVxuY29uc3QgcXVlcnlTZWFyY2ggPSAocXVlcnlTdHJpbmc6IHN0cmluZywgY2I6IGFueSkgPT4ge1xuICBjb25zdCByZXN1bHRzID0gcXVlcnlTdHJpbmdcbiAgICA/IHJlc3RhdXJhbnRzLnZhbHVlLmZpbHRlcihjcmVhdGVGaWx0ZXIocXVlcnlTdHJpbmcpKVxuICAgIDogcmVzdGF1cmFudHMudmFsdWVcbiAgLy8gY2FsbCBjYWxsYmFjayBmdW5jdGlvbiB0byByZXR1cm4gc3VnZ2VzdGlvbnNcbiAgY2IocmVzdWx0cylcbn1cbmNvbnN0IGNyZWF0ZUZpbHRlciA9IChxdWVyeVN0cmluZzogc3RyaW5nKSA9PiB7XG4gIHJldHVybiAocmVzdGF1cmFudDogUmVzdGF1cmFudEl0ZW0pID0+IHtcbiAgICByZXR1cm4gKFxuICAgICAgcmVzdGF1cmFudC52YWx1ZS50b0xvd2VyQ2FzZSgpLmluZGV4T2YocXVlcnlTdHJpbmcudG9Mb3dlckNhc2UoKSkgPT09IDBcbiAgICApXG4gIH1cbn1cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICdiYWJlbCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vYmFiZWwvYmFiZWwnIH0sXG4gIF1cbn1cblxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGl0ZW06IFJlc3RhdXJhbnRJdGVtKSA9PiB7XG4gIGNvbnNvbGUubG9nKGl0ZW0pXG59XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIHJlc3RhdXJhbnRzLnZhbHVlID0gbG9hZEFsbCgpXG59KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Press tab key or click on input to focus it

### What is Expected?

popup will not be visible if autocomplete input is readonly, all user input should be ignored

### What is actually happening?

popup of autocomplete will be visible although it is readonly

### Additional comments

.

**Comment by tolking** [comment]
I found that the Autocomplete component does not support readonly attribute, this is not a Bug but a feature request.

**Comment by MyNameIsNico** [comment]
@tolking Thanks for your reply. I thought it was a valid attribute because you can't enter some text in the el-autocomplete if it is readonly.

**Comment by zybieku** [comment]
why dont use `disabled` replace  `readonly` ::smile

**Comment by tolking** [comment]
The Autocomplete component is different from Input component. it more like a Select component, so there has been no readonly attribute.

Now, we have extracted the docs about the Autocomplete component from the Input, whether we need the readonly attribute needs more discussion.

**Comment by tolking** [comment]
The Autocomplete component is different from Input component. it more like a Select component, so there has been no readonly attribute.

Now, we have extracted the docs about the Autocomplete component from the Input, whether we need the readonly attribute needs more discussion.

**Comment by tolking** [comment]
The Autocomplete component is different from Input component. it more like a Select component, so there has been no readonly attribute.

Now, we have extracted the docs about the Autocomplete component from the Input, whether we need the readonly attribute needs more discussion.

**Comment by StephenKe** [comment]
Consider this situation: on a preview form, the Autocomplete component cannot be edited.And it cannot set `diasbled` cause its unsuitable style and pointer.The readonly attribute should be a good choice.

> The Autocomplete component is different from Input component. it more like a Select component, so there has been no readonly attribute.
> 
> Now, we have extracted the docs about the Autocomplete component from the Input, whether we need the readonly attribute needs more discussion.

**Comment by MyNameIsNico** [comment]
@StephenKe This is exactly my situation. There is a form which is readonly in read mode. In edit mode, one input depends on another input. If the first is not valid, then the second is disabled. The correct style is an important thing to distinguish both cases and for user feedback, as you said.
