### ISSUE TITLE
[Bug Report] [Component] [table, table-column] defaultSort not working on columns changed

### ISSUE THREAD

**Issue by yy303023858** [element-plus/element-plus#8294]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.5`
- Browser / OS: `Chrome 102.0.0.0 / windows 11`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5sZXQgY29sdW1ucyA9IHJlZihbXG4gIHsgbmFtZTogJ0RhdGUnLCBmaWVsZEtleTogJ2RhdGUnLCB3aWR0aDogJzE4MCcsIHNvcnRhYmxlOiB0cnVlIH0sXG4gIHsgbmFtZTogJ05hbWUnLCBmaWVsZEtleTogJ25hbWUnLCB3aWR0aDogJzE4MCcsIHNvcnRhYmxlOiB0cnVlIH0sXG4gIHsgbmFtZTogJ0FkZHJlc3MnLCBmaWVsZEtleTogJ2FkZHJlc3MnLCB3aWR0aDogJ2F1dG8nLCBzb3J0YWJsZTogdHJ1ZSB9XG5dKVxuXG5jb25zdCBkZWZhbHV0U29ydCA9IHJlZih7IHByb3A6ICdkYXRlJywgb3JkZXI6ICdkZXNjZW5kaW5nJyB9KVxuXG5jb25zdCBjaGFuZ2VDb2x1bW5zID0gKCkgPT4ge1xuICBjb2x1bW5zLnZhbHVlID0gW1xuICAgIHsgbmFtZTogJ0RhdGUyJywgZmllbGRLZXk6ICdkYXRlJywgd2lkdGg6ICcxODAnLCBzb3J0YWJsZTogdHJ1ZSB9LFxuICAgIHsgbmFtZTogJ05hbWUyJywgZmllbGRLZXk6ICduYW1lJywgd2lkdGg6ICcxODAnLCBzb3J0YWJsZTogdHJ1ZSB9LFxuICAgIHsgbmFtZTogJ0FkZHJlc3MyJywgZmllbGRLZXk6ICdhZGRyZXNzJywgd2lkdGg6ICdhdXRvJywgc29ydGFibGU6IHRydWUgfVxuICBdXG5cbiAgZGVmYWx1dFNvcnQudmFsdWUgPSB7IHByb3A6ICdhZGRyZXNzJywgb3JkZXI6ICdkZXNjZW5kaW5nJyB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdhb20nLFxuICAgIGFkZHJlc3M6ICdhby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ2JvbScsXG4gICAgYWRkcmVzczogJ2JvLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcydcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnY29tJyxcbiAgICBhZGRyZXNzOiAnY28uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJ1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdkb20nLFxuICAgIGFkZHJlc3M6ICdkby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnXG4gIH1cbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlQ29sdW1uc1wiPmNoYW5nZSBjb2x1bW5zPC9lbC1idXR0b24+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIDpkZWZhdWx0LXNvcnQ9XCJkZWZhbHV0U29ydFwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gY29sdW1uc1wiXG4gICAgICA6a2V5PVwiaXRlbS5uYW1lXCJcbiAgICAgIDpwcm9wPVwiaXRlbS5maWVsZEtleVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLm5hbWVcIlxuICAgICAgOndpZHRoPVwiaXRlbS53aWR0aFwiXG4gICAgICA6c29ydGFibGU9XCJpdGVtLnNvcnRhYmxlXCJcbiAgICAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.set default columns and default-sort
2.click 'changecolumns' button
3.set another columns and default-sort
4.default-sort not working ，not display on el-table

### What is Expected?

default-sort correct working

### What is actually happening?

default-sort not working

### Additional comments

_(empty)_

**Comment by tolking** [comment]
The `defaultSort` is not reactive, so it is not the right way to use it.

Maybe you should use the [sort Methods](https://element-plus.org/en-US/component/table.html#table-methods)

**Comment by JChehe** [comment]
@tolking 

`defaultSort` 不是 reactive 的，故 `defaultSort` 对异步数据不起作用。这和 ElementUI 的表现不同。

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBEQVRBID0gW1xuICB7XG4gICAgcmVsZWFzZURhdGU6IDE2NDAxMDI0MDAwMDAsXG4gICAgbGFuZE5vOiAzNlxuICB9LFxuICAvLyDku6XkuIvkuKTkuKogcmVsZWFzZURhdGUg55u45ZCM77yM5pWF5YaN5qC55o2uIGxhbmRObyDov5vooYzlr7nmr5RcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzNcbiAgfSxcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzRcbiAgfSxcbl1cblxuY29uc3QgdGFibGVEYXRhID0gcmVmKFsuLi5EQVRBXSlcblxuLy8g5qih5ouf5byC5q2l6K+35rGC5pWw5o2u77yIMeenkuWQju+8jOazqOaEj+inguWvn+ihqOagvOesrOS4gOWIl+aVsOaNru+8iVxuc2V0VGltZW91dCgoKSA9PiB7XG4gIHRhYmxlRGF0YS52YWx1ZSA9IFsuLi5EQVRBXVxufSwgMTAwMClcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIFxuICAgICAgICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgICAgICAgOmRlZmF1bHQtc29ydD1cIntcbiAgICAgICAgICAgICAgIHByb3A6ICdsYW5kTm8nLFxuICAgICAgICAgICAgICAgb3JkZXI6ICdkZXNjZW5kaW5nJ1xuICAgICAgICAgICAgfVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgICAgICAgICAgICAgIHByb3A9XCJsYW5kTm9cIlxuICAgICAgICAgICAgICAgICAgICAgbGFiZWw9XCLnvJblj7dcIlxuICAgICAgICAgICAgICAgICAgICAgc29ydGFibGU+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgICAgICAgICAgICAgcHJvcD1cInJlbGVhc2VEYXRlXCJcbiAgICAgICAgICAgICAgICAgICAgIGxhYmVsPVwi5Y+R5biD5pe26Ze0XCJcbiAgICAgICAgICAgICAgICAgICAgIHNvcnRhYmxlXG4gICAgICAgICAgICAgICAgICAgICA6c29ydC1ieT1cIlsncmVsZWFzZURhdGUnLCAnbGFuZE5vJ11cIj5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

对于异步数据，`defaultSort` 无用，须手动调用 table 的 `sort` 方法：
```js
// 在异步获取数据的回调函数内
nextTick(() => {
 tableRef.value.sort(prop, order)
})
```

**Comment by tolking** [comment]
defaultSort 默认就不支持异步数据，设计如此

**Comment by zzx18023** [comment]
> @tolking
> 
> `defaultSort` 不是 reactive 的，故 `defaultSort` 对异步数据不起作用。这和 ElementUI 的表现不同。
> 
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBEQVRBID0gW1xuICB7XG4gICAgcmVsZWFzZURhdGU6IDE2NDAxMDI0MDAwMDAsXG4gICAgbGFuZE5vOiAzNlxuICB9LFxuICAvLyDku6XkuIvkuKTkuKogcmVsZWFzZURhdGUg55u45ZCM77yM5pWF5YaN5qC55o2uIGxhbmRObyDov5vooYzlr7nmr5RcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzNcbiAgfSxcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzRcbiAgfSxcbl1cblxuY29uc3QgdGFibGVEYXRhID0gcmVmKFsuLi5EQVRBXSlcblxuLy8g5qih5ouf5byC5q2l6K+35rGC5pWw5o2u77yIM+enkuWQju+8jOazqOaEj+inguWvn+ihqOagvOesrOS4gOWIl+aVsOaNru+8iVxuc2V0VGltZW91dCgoKSA9PiB7XG4gIHRhYmxlRGF0YS52YWx1ZSA9IFsuLi5EQVRBXVxufSwgMzAwMClcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIFxuICAgICAgICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgICAgICAgOmRlZmF1bHQtc29ydD1cIntcbiAgICAgICAgICAgICAgIHByb3A6ICdsYW5kTm8nLFxuICAgICAgICAgICAgICAgb3JkZXI6ICdkZXNjZW5kaW5nJ1xuICAgICAgICAgICAgfVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgICAgICAgICAgICAgIHByb3A9XCJsYW5kTm9cIlxuICAgICAgICAgICAgICAgICAgICAgbGFiZWw9XCLnvJblj7dcIlxuICAgICAgICAgICAgICAgICAgICAgc29ydGFibGU+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgICAgICAgICAgICAgcHJvcD1cInJlbGVhc2VEYXRlXCJcbiAgICAgICAgICAgICAgICAgICAgIGxhYmVsPVwi5Y+R5biD5pe26Ze0XCJcbiAgICAgICAgICAgICAgICAgICAgIHNvcnRhYmxlXG4gICAgICAgICAgICAgICAgICAgICA6c29ydC1ieT1cIlsncmVsZWFzZURhdGUnLCAnbGFuZE5vJ11cIj5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
> 
> 对于异步数据，`defaultSort` 无用，须手动调用 table 的 `sort` 方法：
> 
> ```js
> // 在异步获取数据的回调函数内
> nextTick(() => {
>  tableRef.value.sort(prop, order)
> })
> ```

tableRef.value.sort(prop, order) 会出发 sort-change 事件
 
问题是重置按钮重置了default-sort 并请求列表数据
但 table并没有更新 store , 

如果在请求回调里面调用sort 修复 store 会形成死循环。

**Comment by zzx18023** [comment]
> > @tolking
> > `defaultSort` 不是 reactive 的，故 `defaultSort` 对异步数据不起作用。这和 ElementUI 的表现不同。
> > [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBEQVRBID0gW1xuICB7XG4gICAgcmVsZWFzZURhdGU6IDE2NDAxMDI0MDAwMDAsXG4gICAgbGFuZE5vOiAzNlxuICB9LFxuICAvLyDku6XkuIvkuKTkuKogcmVsZWFzZURhdGUg55u45ZCM77yM5pWF5YaN5qC55o2uIGxhbmRObyDov5vooYzlr7nmr5RcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzNcbiAgfSxcbiAge1xuICAgIHJlbGVhc2VEYXRlOiAxNjM1MjY0MDAwMDAwLFxuICAgIGxhbmRObzogMzRcbiAgfSxcbl1cblxuY29uc3QgdGFibGVEYXRhID0gcmVmKFsuLi5EQVRBXSlcblxuLy8g5qih5ouf5byC5q2l6K+35rGC5pWw5o2u77yIM+enkuWQju+8jOazqOaEj+inguWvn+ihqOagvOesrOS4gOWIl+aVsOaNru+8iVxuc2V0VGltZW91dCgoKSA9PiB7XG4gIHRhYmxlRGF0YS52YWx1ZSA9IFsuLi5EQVRBXVxufSwgMzAwMClcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIFxuICAgICAgICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgICAgICAgOmRlZmF1bHQtc29ydD1cIntcbiAgICAgICAgICAgICAgIHByb3A6ICdsYW5kTm8nLFxuICAgICAgICAgICAgICAgb3JkZXI6ICdkZXNjZW5kaW5nJ1xuICAgICAgICAgICAgfVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgICAgICAgICAgICAgIHByb3A9XCJsYW5kTm9cIlxuICAgICAgICAgICAgICAgICAgICAgbGFiZWw9XCLnvJblj7dcIlxuICAgICAgICAgICAgICAgICAgICAgc29ydGFibGU+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgICAgICAgICAgICAgcHJvcD1cInJlbGVhc2VEYXRlXCJcbiAgICAgICAgICAgICAgICAgICAgIGxhYmVsPVwi5Y+R5biD5pe26Ze0XCJcbiAgICAgICAgICAgICAgICAgICAgIHNvcnRhYmxlXG4gICAgICAgICAgICAgICAgICAgICA6c29ydC1ieT1cIlsncmVsZWFzZURhdGUnLCAnbGFuZE5vJ11cIj5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
> > 对于异步数据，`defaultSort` 无用，须手动调用 table 的 `sort` 方法：
> > ```js
> > // 在异步获取数据的回调函数内
> > nextTick(() => {
> >  tableRef.value.sort(prop, order)
> > })
> > ```
> 
> tableRef.value.sort(prop, order) 会出发 sort-change 事件
> 
> 问题是重置按钮重置了default-sort 并请求列表数据 但 table并没有更新 store ,
> 
> 如果在请求回调里面调用sort 修复 store 会形成死循环。



查看了源码找到解决办法，在重置defaultSort 后调用  tableRef.value?.store.commit("sort", {
    prop: defaultSort.prop,
    order: prop.order,
    init: true,
  }); 
可以不触发 sort-change 事件
