### ISSUE TITLE
[Bug Report] [Component] El-Drawer 内el-select、el-date-picker 等form表单元素 blur 动作之后填写值被selected，导致无法 blur 重复触发选择框弹出

### ISSUE THREAD

**Issue by jason-xiewenqiang** [element-plus/element-plus#8297]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome99/window10`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-date-picker`
- `el-select`
- `el-input`
- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、新建一个页面，配drawer,并且构建form表单组件，包含select,date-picker
2、触发弹出，选值进行验证

### What is Expected?

单个表单blur生效，并不会让已选值selected

### What is actually happening?

重复selected,focus

### Additional comments

_(empty)_

**Comment by Kyrie0216** [comment]
同样的问题，请问有解决方案吗？

**Comment by tolking** [comment]
看上去这个问题已经修复了，如果没有可以提供一个可以复现的 Demo
