### ISSUE TITLE
### Carousel

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#83]

**Comment by Ryan2128** [comment]
Is the plan for this component to use vue 3 to refactor or rewrite all the logic? 

If it is the former, what's the current progress? I submitted a [PR](https://github.com/kkbjs/element3/pull/10) about refactoring this component in another code repository. If this component has not been refactored, can I submit a PR about it?

**Comment by Liiked** [comment]
> Is the plan of this component to use vue 3 to refactor or rewrite all the logic?
> 
> If it is the former, what's the current progress? I submitted a [PR](https://github.com/kkbjs/element3/pull/10) about refactoring this component in another code repository. If this component has not been refactored, can I submit a PR about it?

Yes, it's been refactored with typescript. It's almost done there😉 and PR be submitted today. There's only few works to do with the "card" type of carousel between v2 and v3, and pass the last test case with all things settled.

**Comment by Ryan2128** [comment]
OK😊
