### ISSUE TITLE
[Bug Report] [Style] [table] 通过HTML 标签导入 Element Plus 方式使用表格组件，表头变成了纵向展示，不是横向展示

### ISSUE THREAD

**Issue by mangyusisha** [element-plus/element-plus#8302]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/mangyusisha/pen/NWyJRGR)

### Steps to reproduce

通过HTML 标签导入 Element Plus 方式，复制官网Table 表格第一个示例demo代码

### What is Expected?

表头横向展示

### What is actually happening?

表头纵向展示

### Additional comments

_(empty)_

**Comment by hoowhoami** [comment]
`<el-table-column>` 不要使用`<el-table-column />`这种方式的自闭合标签，改写成 `<el-table-column></el-table-column>` 即可。

**Comment by chenxch** [comment]
#7232 可以先试着在issues中搜索，可能就会找到答案哈
