### ISSUE TITLE
[Bug Report] [Style] [tabs] Tabs 动态增减标签页tab超过最大空间，最后一个新增的tab被遮挡无法看到

### ISSUE THREAD

**Issue by zhfyjeremy** [element-plus/element-plus#8303]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tabs.html#%E5%8A%A8%E6%80%81%E5%A2%9E%E5%87%8F%E6%A0%87%E7%AD%BE%E9%A1%B5)

### Steps to reproduce

1. 打开 https://element-plus.gitee.io/zh-CN/component/tabs.html#动态增减标签页
2. 点击➕添加New Tab超过当前空间，最后一个新增加的被遮挡

### What is Expected?

最后一个新增加tab正常显示

### What is actually happening?

最后一个新增加的被遮挡

### Additional comments

_(empty)_

**Comment by btea** [comment]
Duplicate of #8114
