### ISSUE TITLE
[Feature Request] [Docs] [message-box] 增加 ElMessageBox icon 配置项使用组件的示例

### ISSUE THREAD

**Issue by xiangqunXiao** [element-plus/element-plus#8307]
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `message-box`

## Description

目前 ElMessageBox 的文档是写着 icon 支持传入组件，但没示例一直不明白要怎么写，希望能先在 issue 告知写法，并在文档中补全示例

### Additional comments

_(empty)_

**Comment by Tsong-LC** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gTWVzc2FnZSBCb3g8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3gsIEVsQnV0dG9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybShcbiAgICAncHJveHkgd2lsbCBwZXJtYW5lbnRseSBkZWxldGUgdGhlIGZpbGUuIENvbnRpbnVlPycsXG4gICAgJ1dhcm5pbmcnLFxuICAgIHtcbiAgICAgIGNvbmZpcm1CdXR0b25UZXh0OiAnT0snLFxuICAgICAgY2FuY2VsQnV0dG9uVGV4dDogJ0NhbmNlbCcsXG4gICAgICB0eXBlOiAnd2FybmluZycsXG4gICAgICBkcmFnZ2FibGU6IHRydWUsXG4gICAgICBpY29uOiBoKFxuICAgICAgICBFbEJ1dHRvbixcbiAgICAgICAge1xuICAgICAgICAgIHR5cGU6ICdwcmltYXJ5JyxcbiAgICAgICAgfSxcbiAgICAgICAgKCkgPT4gJ3ByaW1hcnknXG4gICAgICApLFxuICAgIH1cbiAgKVxuICAgIC50aGVuKCgpID0+IHtcbiAgICAgIEVsTWVzc2FnZSh7XG4gICAgICAgIHR5cGU6ICdzdWNjZXNzJyxcbiAgICAgICAgbWVzc2FnZTogJ0RlbGV0ZSBjb21wbGV0ZWQnLFxuICAgICAgfSlcbiAgICB9KVxuICAgIC5jYXRjaCgoKSA9PiB7XG4gICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICB0eXBlOiAnaW5mbycsXG4gICAgICAgIG1lc3NhZ2U6ICdEZWxldGUgY2FuY2VsZWQnLFxuICAgICAgfSlcbiAgICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by sxzz** [comment]
[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gTWVzc2FnZSBCb3g8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoLCBtYXJrUmF3IH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgQXBwbGUgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oXG4gICAgJ3Byb3h5IHdpbGwgcGVybWFuZW50bHkgZGVsZXRlIHRoZSBmaWxlLiBDb250aW51ZT8nLFxuICAgICdXYXJuaW5nJyxcbiAgICB7XG4gICAgICBjb25maXJtQnV0dG9uVGV4dDogJ09LJyxcbiAgICAgIGNhbmNlbEJ1dHRvblRleHQ6ICdDYW5jZWwnLFxuICAgICAgdHlwZTogJ3dhcm5pbmcnLFxuICAgICAgZHJhZ2dhYmxlOiB0cnVlLFxuICAgICAgaWNvbjogbWFya1JhdyhBcHBsZSksXG4gICAgfVxuICApXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

PR welcome
