### ISSUE TITLE
[Feature Request] [Enhancement] [icon] 为什么icon 不支持iconfont 引用方式

### ISSUE THREAD

**Issue by qc5926** [element-plus/element-plus#8314]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `icon`

## Description

之前icon 支持iconfont应用，css更改图标什么很方便，现在无法使用css更换组件图标，希望可以新增支持iconfont使用

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
不可能支持了 已经被废弃了

**Comment by sxzz** [comment]
1.2.0 已经移除 font icon https://github.com/element-plus/element-plus/discussions/4060

可以全局引入图标或使用 unplugin-icon 等插件便捷使用图标
https://element-plus.org/en-US/component/icon.html#register-all-icons

**Comment by qc5926** [comment]
这就很难受了，我想全局改一个组件的图标都无法实现了
