### ISSUE TITLE
Menu collapse transition animation bug

### ISSUE THREAD

**Issue by leeq404** [element-plus/element-plus#832]
**Compoent**: Menu

**Question**: Menu  default collapse transition value is true, while open the collapse ，animation has worked, but when close the collapse , the animation has disappear

**Vue Version** : 3.0.4

**Element Version** : 1.0.1-beta.3

![menu.gif](https://s3.ax1x.com/2020/12/04/Dbmbng.gif)

**Comment by leeq404** [comment]
I haven't tested this component separately，I will do this as soon.

**Comment by JeremyWuuuuu** [comment]
Could you provide us with demo code or a minimal reproducible repo?

**Comment by leeq404** [comment]
> Could you provide us with demo code or a minimal reproducible repo?

sorry, I don't find a library link on codepen, the demo code is provied by offical website. I think it's caused by **menu-collapse-transition**, but I don't find anything different from this compnent, sorry.

**Comment by JeremyWuuuuu** [comment]
@Liiked  will take care of this bug here.
