### ISSUE TITLE
[Bug Report] [Component] [date-picker] date-picker在IOS上无法使用

### ISSUE THREAD

**Issue by seepine** [element-plus/element-plus#8322]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html)

### Steps to reproduce

IOS手机浏览器打开date-picker官网文档，点击`el-date-picker`会弹出选择面板，选择后面板隐藏但没有值

### What is Expected?

有值

### What is actually happening?

没有值

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
is ok
<img width="609" alt="image" src="https://user-images.githubusercontent.com/44761321/180989169-f8f7d17b-f436-4824-9696-8b861e7bffc9.png">

This is the PC -side component library if it is a mobile terminal, it is recommended to choose the mobile UI component library
