### ISSUE TITLE
[Feature Request] 无法修改el-button样式

### ISSUE THREAD

**Issue by BugOS-ly** [element-plus/element-plus#8346]
Feature type: **`Other`**

## Details

- Enhanced compone nt name: `All`

## Description

我在修改el-button样式时,为其添加了自定义的class, 并且修改了css变量, 但是依旧被覆盖掉了
```vue
<template>
<el-button class="menu-button">推荐</el-button>
<el-button class="menu-button">关注</el-button>
</template>

<style lang="less">
// 菜单按钮通用样式
.menu-button {
  // 被覆盖掉了
  --el-button-bg-color: pink;

  // button中的字体, (起作用)
  span {
    font-size: 1.2rem;
    font-weight: bold;
  }
}
</style/

### Additional comments

_(empty)_

<!-- 如果你需要插入截图，请在这粘贴。 -->
![image](https://user-images.githubusercontent.com/85739810/174437603-ef7a071a-622a-45ea-8a03-b91c40906c6f.png)
![image](https://user-images.githubusercontent.com/85739810/174437609-2ee1c831-59ff-4b18-b351-ec1029af438a.png)

**Comment by chenxch** [comment]
--el-button-bg-color: pink !important;

**Comment by sunnyCoCosun** [comment]
plese use !important

```
.menu-button {
  --el-button-bg-color: pink !important;

  // button中的字体, (起作用)
  span {
    font-size: 1.2rem;
    font-weight: bold;
  }
}
```

**Comment by BugOS-ly** [comment]
谢谢, 麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月20日(星期一) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Feature Request] 无法修改el-button样式 (Issue #8346)





 
plese use !important
 .menu-button {   --el-button-bg-color: pink !important;   // button中的字体, (起作用)   span {     font-size: 1.2rem;     font-weight: bold;   } }
