### ISSUE TITLE
[Bug Report] [Component] [select-v2] <el-select-v2 />单选模式下选完后依旧是focus状态

### ISSUE THREAD

**Issue by lemonKun** [element-plus/element-plus#8353]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.6`
- Browser / OS: `macOS 11.2.3`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZmxleDogYXV0b1wiPlxuICAgIDxkaXY+XG4gICAgICA8ZWwtc2VsZWN0LXYyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgICBzdHlsZT1cIndpZHRoOiAyNDBweDsgdmVydGljYWwtYWxpZ246IG1pZGRsZVwiXG4gICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbml0aWFscyA9IFsnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaiddXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbXSlcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcbmNvbnN0IHZhbHVlMyA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICB2YWx1ZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

add filterable props

### What is Expected?

选完值后input不再保持focus状态，并且显示内容颜色正常

### What is actually happening?

选完值后，依旧是focus状态，并且显示内容颜色为灰色，只有再次点击外边，才会正常

### Additional comments

_(empty)_

**Comment by tolking** [comment]
select 组件标准就是选择完成后依然是 focus 状态，文本颜色不正常确实存在

**Comment by TLovers** [comment]
借楼 怎么绑定对象啊，value 明明时一个对象 选中后还是一个string， 已经设置 value-key="value.id"
:options="
                        optionData.AssetsList.map((item) => {
                            return {
                                ...item,
                                label: item.assetUrl,
                                value: item,
                            }
                        })
                    "
