### ISSUE TITLE
[Bug Report] [Component] [menu] el-menu 存在异常问题，horizontal 模式，点击子菜单后，下拉菜单一直反复下拉再收起

### ISSUE THREAD

**Issue by tulies** [element-plus/element-plus#8357]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtbWVudVxuICAgIDpkZWZhdWx0LWFjdGl2ZT1cImFjdGl2ZUluZGV4MlwiXG4gICAgY2xhc3M9XCJlbC1tZW51LWRlbW9cIlxuICAgIG1vZGU9XCJob3Jpem9udGFsXCJcbiAgICBiYWNrZ3JvdW5kLWNvbG9yPVwiIzU0NWM2NFwiXG4gICAgdGV4dC1jb2xvcj1cIiNmZmZcIlxuICAgIGFjdGl2ZS10ZXh0LWNvbG9yPVwiI2ZmZDA0YlwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gID5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMVwiPlByb2Nlc3NpbmcgQ2VudGVyPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMlwiPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5Xb3Jrc3BhY2U8L3RlbXBsYXRlPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIyLTRcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5pdGVtIGZvdXI8L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi00LTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi00LTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi00LTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjNcIiBkaXNhYmxlZD5JbmZvPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj5PcmRlcnM8L2VsLW1lbnUtaXRlbT5cbiAgPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYWN0aXZlSW5kZXggPSByZWYoJzEnKVxuY29uc3QgYWN0aXZlSW5kZXgyID0gcmVmKCcxJylcbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

horizontal 模式下，点击子菜单后，下拉菜单一直反复下拉再收起。 
官方的文档示例也是一样有问题。

点击 “Workspace” 下的 “item one” 后，鼠标不要移动，你会发现我说的现象。

### What is Expected?

点击子菜单后，应该收起下拉菜单。

### What is actually happening?

点击子菜单后，应该收起下拉菜单。

### Additional comments

_(empty)_

**Comment by sunjiesama** [comment]
泪目，终于有人提这个问题了，好几个版本之前就有问题了，奈何想提issues一直报500

**Comment by sunjiesama** [comment]
![GIF 2022-6-10 10-12-11](https://user-images.githubusercontent.com/54022918/174536262-711e9540-8e81-48b8-97ef-e4591fcfcb51.gif)
参考这个gif

**Comment by btea** [comment]
fixed #8533
