### ISSUE TITLE
dynamic type of el-date-picker unvisible

### ISSUE THREAD

**Issue by FlyDancing** [element-plus/element-plus#836]

**Comment by bastarder** [comment]
can you give more information about that?

**Comment by FlyDancing** [comment]
this is the url link: [(https://codesandbox.io/s/vue3element-plus-in92u)]
if i use require get the zh-cn locale ,the monthrange date can't see

**Comment by bastarder** [comment]
i try [demo](https://codesandbox.io/s/vue3element-plus-forked-mk6du), every thing is ok.

**Comment by bastarder** [comment]
CC @zazzaz

**Comment by JeremyWuuuuu** [comment]
LGTM, maybe it was a bug from `Vue`, the only deficiency here is that we didn't load `font-icons`
![image](https://user-images.githubusercontent.com/15975785/101328936-a690c280-38ab-11eb-8c63-51db487732bc.png)

**Comment by FlyDancing** [comment]
> i try [demo](https://codesandbox.io/s/vue3element-plus-forked-mk6du), every thing is ok.

you can use follow comments code:

```
const ElementPlus = require("element-plus");
require("element-plus/lib/theme-chalk/index.css");
const locale = require("element-plus/lib/locale/lang/zh-cn")
```

current month on the flow panel  didn't show

**Comment by JeremyWuuuuu** [comment]
@FlyDancing , so I tried with this:

1. Commented the code 
```ts

// import ElementPlus from "element-plus";
// import "element-plus/lib/theme-chalk/index.css";
// import locale from "element-plus/lib/locale/lang/zh-cn";
```

2. Uncommented code:
```ts
const ElementPlus = require("element-plus");
require("element-plus/lib/theme-chalk/index.css");
const locale = require("element-plus/lib/locale/lang/zh-cn");
```
I get the error as same as you had.

So I tried to do this:

```ts
const locale = require("element-plus/lib/locale/lang/zh-cn");
console.log(locale);
```

Then I got this from the console:

```ts
{default: Object}
```

So I know the problem was that, we have made esm bundle with no commonjs supporting, so if you need to use `require` to get the file, then you simply need to add a `.default` like this:

```ts
 createApp(App).use(ElementPlus, { size: "small", locale: locale.default }).mount("#app");
```

Screenshot: 
![image](https://user-images.githubusercontent.com/15975785/101348982-8a028380-38c7-11eb-8f97-50c8787d5248.png)

**Comment by JeremyWuuuuu** [comment]
So, we suggest that you might need to use `import` statement throughout the entire project since we export `esm` bundle instead of `umd` bundle, if you want to use `umd` bundle, then you need to configure your bundler to use `index.full.js` instead of `index.js` or `index.esm.js`.

**Comment by JeremyWuuuuu** [comment]
If you wanted to use `dynamic import` use it with `import(path).then()` or `await import(path)`.

**Comment by JeremyWuuuuu** [comment]
I am closing this issue since I have already listed the solutions above, try them, feel free to reopen it when you feel so.
