### ISSUE TITLE
[Bug Report] el-form 嵌套 el-select 点击 label时，下拉框会展开，输入框会焦点选中

### ISSUE THREAD

**Issue by LifeWy** [element-plus/element-plus#8360]
### Element Plus version
2.2.0

### OS/Browsers version
102.0.5005.115

### Vue version
3.2.6

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN?repo=element-plus

### Steps to reproduce
点击 el-form-item 的label，下拉框，会展开，输入框会焦点选中，swith会改变

### What is Expected?
点击 el-form-item 的label，下拉框不能展开，输入框焦点不能选中，swith不能改变

### What is actually happening?
点击 el-form-item 的label，下拉框，会展开，输入框会焦点选中，swith会改变

**Comment by chenxch** [comment]
Hi, thanks for your feedback, but what about this question, it's a [W3C standard](https://www.w3.org/WAI/tutorials/forms/labels/).

**Comment by chenxch** [comment]
@LifeWy 
This behavior can be prevented stylistically by adding `pointer-events:` none; to the `<label>` elements.
This is the solution from @Giwayume , you can try it if you need it.
