### ISSUE TITLE
[Bug Report] [Component] [table, table-column] el-table-column 隐藏 显示之后 el-table 会出现横向滚动条

### ISSUE THREAD

**Issue by HalseySpicy** [element-plus/element-plus#8361]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.5`
- Browser / OS: `谷歌 102.0.5005.63 / windows 21H2`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlzU2hvdyA9IHJlZih0cnVlKTtcbmNvbnN0IHRhYmxlRGF0YSA9IFtcblx0e1xuXHRcdGRhdGU6IFwiMjAxNi0wNS0wM1wiLFxuXHRcdG5hbWU6IFwiVG9tXCIsXG5cdFx0YWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIlxuXHR9LFxuXHR7XG5cdFx0ZGF0ZTogXCIyMDE2LTA1LTAyXCIsXG5cdFx0bmFtZTogXCJUb21cIixcblx0XHRhZGRyZXNzOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiXG5cdH0sXG5cdHtcblx0XHRkYXRlOiBcIjIwMTYtMDUtMDRcIixcblx0XHRuYW1lOiBcIlRvbVwiLFxuXHRcdGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCJcblx0fSxcblx0e1xuXHRcdGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuXHRcdG5hbWU6IFwiVG9tXCIsXG5cdFx0YWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIlxuXHR9XG5dO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGRpdj5cblx0XHQ8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG5cdFx0XHQ8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuXHRcdFx0PGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgdi1pZj1cImlzU2hvd1wiIC8+XG5cdFx0XHQ8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cblx0XHQ8L2VsLXRhYmxlPlxuXHRcdDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJpc1Nob3cgPSAhaXNTaG93XCI+5YiH5o2i5YiX5pi+6ZqQPC9lbC1idXR0b24+XG5cdDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、点击切换列显隐按钮两次
2、鼠标移动到 table 内，会出现横向滚动条，并且不能拖动

### What is Expected?

el-table-column 隐藏 显示之后， el-table 不出现横向滚动条。
或者暴露一个方法重新计算滚动条方法

### What is actually happening?

el-table-column 隐藏 显示之后 el-table 会出现横向滚动条

### Additional comments

_(empty)_

**Comment by sunnyCoCosun** [comment]
You can try replacing the width property with min-width

**Comment by sunnyCoCosun** [comment]
```
<el-table :data="tableData" style="width: 100%">
  <el-table-column prop="date" label="Date" min-width="180" />
  <el-table-column prop="name" label="Name" min-width="180" v-if="isShow" />
  <el-table-column prop="address" label="Address" />
</el-table>
```

**Comment by litt1e-p** [comment]
min-width does fix the error
