### ISSUE TITLE
[Bug Report] messageBox customClass 属性不生效

### ISSUE THREAD

**Issue by niceduang** [element-plus/element-plus#8362]
### Element Plus version
2.2.6

### OS/Browsers version
chrome 版本 101.0.4951.64（正式版本） (x86_64)

### Vue version
3.2.37

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-02ln77?file=/src/App.vue

### Steps to reproduce
```vue
<template>
  <el-button text @click="open">Click to open Message Box</el-button>
</template>

<script lang="ts" setup>
import { ElMessageBox } from "element-plus";
ElMessageBox.confirm("You have unsaved changes, save and proceed?", "Confirm", {
  distinguishCancelAndClose: true,
  confirmButtonText: "Save",
  cancelButtonText: "Discard Changes",
  center: true,
  "custom-class": "abc", // 不生效
});
</script>
```

### What is Expected?
支持自定义 className

### What is actually happening?
"custom-class": "abc", // 不生效

**Comment by sunnyCoCosun** [comment]
`
<template>
  <el-button text @click="open">Click to open Message Box</el-button>
</template>

<script lang="ts" setup>
import { ElMessageBox } from "element-plus";
ElMessageBox.confirm("You have unsaved changes, save and proceed?", "Confirm", {
  distinguishCancelAndClose: true,
  confirmButtonText: "Save",
  cancelButtonText: "Discard Changes",
  center: true,
  customClass: "abc",
});
</script>
`
use customClass

**Comment by sunnyCoCosun** [comment]
```
<template>
  <el-button text @click="open">Click to open Message Box</el-button>
</template>

<script lang="ts" setup>
import { ElMessageBox } from "element-plus";
ElMessageBox.confirm("You have unsaved changes, save and proceed?", "Confirm", {
  distinguishCancelAndClose: true,
  confirmButtonText: "Save",
  cancelButtonText: "Discard Changes",
  center: true,
  customClass: "abc", // 不生效
});
</script>
```
Plese use customClass

**Comment by niceduang** [comment]
ok~😂
![image](https://user-images.githubusercontent.com/18629271/174517130-978e7a24-610e-4491-9e58-737e7b2d9814.png)

**Comment by loubingzhuxue** [comment]
> customClass

.abc {} 下面的 样式不生效， 按钮上的一样 confirmButtonClass，
