### ISSUE TITLE
[Bug Report] [Component] [table] table组件树形状态下第一列对齐问题

### ISSUE THREAD

**Issue by defypro** [element-plus/element-plus#8363]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome102.0.5005.63/Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGExXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgIGJvcmRlclxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDwvZWwtdGFibGU+ICAgIFxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGEyXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgIGJvcmRlclxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBudW1iZXJcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBjaGlsZHJlbj86IFVzZXJbXVxufVxuXG5jb25zdCB0YWJsZURhdGExOiBVc2VyW10gPSByZWYoKVxuc2V0VGltZW91dCgoKSA9PiB7XG4gIHRhYmxlRGF0YTEudmFsdWUgPSBbXG4gICAge1xuICAgICAgaWQ6IDEsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogMyxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAzMSxcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICB9LFxuICAgIF0sXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogNCxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICB9LFxuICBdXG59LCAzMDApXG4gIFxuICBcbmNvbnN0IHRhYmxlRGF0YTI6IFVzZXJbXSA9IHJlZihbXG4gICAge1xuICAgICAgaWQ6IDEsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogMyxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAzMSxcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICB9LFxuICAgIF0sXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogNCxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICB9LFxuICBdKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

延迟加载树形table数据，第一列内容没有对齐（icon占位元素没有显示）

### What is Expected?

延迟加载树形table数据，第一列内容可以对齐

### What is actually happening?

延迟加载树形table数据，第一列内容没有对齐（icon占位元素没有显示）

### Additional comments

_(empty)_

**Comment by L1yp** [comment]
如果第一列是selection，不会和表头对其，宽度也计算错误，应该还是加了placeholder之前的宽度。
另外如果第一列是selection就应该把缩进放到第二列才对。
[https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGEyXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgIGJvcmRlclxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW50ZXJmYWNlIFVzZXIge1xuICBpZDogbnVtYmVyXG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBVc2VyW11cbn1cblxuXG5jb25zdCB0YWJsZURhdGEyOiBVc2VyW10gPSByZWYoW1xuICAgIHtcbiAgICAgIGlkOiAxLFxuICAgICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6IDMsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgfSxcbiAgICBdLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6IDQsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgfSxcbiAgXSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319](playground)

**Comment by defypro** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by defypro** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
