### ISSUE TITLE
[Bug Report] [Component] [table] el-table 事件 cell-mouse-enter 和 cell-mouse-leave 回调函数返回的不是响应式对象

### ISSUE THREAD

**Issue by zhaojun1998** [element-plus/element-plus#8365]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgcmVmPVwidGFibGVSZWZcIlxuICAgICAgICAgICAgQHJvdy1jbGljaz1cInJvd0NsaWNrXCJcbiAgICAgICAgICAgIEBjZWxsLW1vdXNlLWVudGVyPVwiY2VsbE1vdXNlRW50ZXJcIlxuICAgICAgICAgICAgQGNlbGwtbW91c2UtbGVhdmU9XCJjZWxsTW91c2VMZWF2ZVwiXG4gICAgICAgICAgICA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiB3aWR0aD1cIjU1XCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBcbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG4gIFxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9XG5dXG5cblxuY29uc3QgdGFibGVSZWYgPSByZWYoKTtcblxuY29uc3Qgcm93Q2xpY2sgPSAocm93LCBjb2x1bW4sIGNlbGwsIGV2ZW50KSA9PiB7XG5cdGNvbnNvbGUubG9nKCdyb3ctY2xpY2snLCByb3cpO1xuXHQvLyB0YWJsZVJlZi52YWx1ZS50b2dnbGVSb3dTZWxlY3Rpb24ocm93KTtcbn1cblxuY29uc3QgY2VsbE1vdXNlRW50ZXIgPSAocm93LCBjb2x1bW4sIGNlbGwsIGV2ZW50KSA9PiB7XG5cdGNvbnNvbGUubG9nKCdjZWxsLW1vdXNlLWVudGVyJywgcm93KTtcblx0Ly8gdGFibGVSZWYudmFsdWUudG9nZ2xlUm93U2VsZWN0aW9uKHJvdywgdHJ1ZSk7XG59XG4gICAgICBcbmNvbnN0IGNlbGxNb3VzZUxlYXZlID0gKHJvdywgY29sdW1uLCBjZWxsLCBldmVudCkgPT4ge1xuXHRjb25zb2xlLmxvZygnY2VsbC1tb3VzZS1sZWF2ZScsIHJvdyk7XG5cdC8vIHRhYmxlUmVmLnZhbHVlLnRvZ2dsZVJvd1NlbGVjdGlvbihyb3csIGZhbHNlKTtcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

复现 demo 见上方链接，`cell-mouse-enter` 和 `cell-mouse-leave` 事件的回调函数与 `row-click` 事件的回调函数返回不同。

![1655707199574.png](https://cdn.jun6.net/2022/06/20/59bc1b4588e1a.png)

这样导致了如果在 `cell-mouse-enter` 或 `cell-mouse-leave` 回调函数中调用诸如 `tableRef.value. toggleRowSelection` 之类的需要传递 `row` 参数的方法时，因为传入的对象不是响应式的，方法会调用无效， 如示例中注释的部分.

### What is Expected?

cell-mouse-enter 和 cell-mouse-leave 回调函数的 row 参数应该是响应式的

### What is actually happening?

cell-mouse-enter 和 cell-mouse-leave 回调函数的 row 参数不是响应式的，而是普通对象。

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
fixed.
