### ISSUE TITLE
[Bug Report] [Component] [select-v2] el-select-v2 v-model绑定的值始终string

### ISSUE THREAD

**Issue by TLovers** [element-plus/element-plus#8369]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1zZWxlY3QtdjJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHZhbHVlLWtleT1cInZhbHVlLmlkXCJcbiAgICA6b3B0aW9ucz1cIltcbiAgICAgIHtcbiAgICAgICBsYWJlbDogJ+a1i+ivlTEnLFxuICAgICAgIHZhbHVlOiB7XG4gICAgICAgICAgaWQ6IDFcbiAgICAgICB9XG4gICAgICB9LFxuICAgICB7XG4gICAgICAgbGFiZWw6ICfmtYvor5UyJyxcbiAgICAgICB2YWx1ZToge1xuICAgICAgICAgIGlkOiAyXG4gICAgICAgfVxuICAgICB9LFxuICAgIF1cIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gIC8+XG4gXHQ8cD5cbiAgICDpgInkuK3nmoTlgLx7e3ZhbHVlfX1cbiAgPC9wPlxuXHRcbiAgXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

 <el-select-v2
    v-model="value"
    value-key="value.id"
    :options="[
      {
       label: ‘测试1’,
       value: {
          id: 1
       }
      },
     {
       label: ‘测试2’,
       value: {
          id: 2
       }
     },
    ]"
    placeholder="Please select"
  />

### What is Expected?

选中后 v-model 绑定的值为预期的对象

### What is actually happening?

v-model 绑定的值为 测试1

### Additional comments

_(empty)_

**Comment by TLovers** [comment]
@chenxch 额 我希望的是选中后，v-model 绑定的是一个{} 
去掉value-key 确实绑定的是一个对象 但是下拉的时候显示全部勾选了，加上value-key 就变成你截图那样了

**Comment by chenxch** [comment]
明白了，如果可以的话需要您再修改一下问题描述和demo，方便大家更清楚问题点并且进行处理哈。

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3QtdjJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpvcHRpb25zPVwiW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ+a1i+ivlTEnLFxuICAgICAgICB2YWx1ZToge1xuICAgICAgICAgIGlkOiAxLFxuICAgICAgICAgIHZhbHVlOiAxLFxuICAgICAgICB9LFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICfmtYvor5UyJyxcbiAgICAgICAgdmFsdWU6IHtcbiAgICAgICAgICBpZDogMixcbiAgICAgICAgICB2YWx1ZTogMixcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgXVwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0XCJcbiAgLz5cbiAgPHA+6YCJ5Lit55qE5YC8e3sgdmFsdWUgfX08L3A+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)  临时方案需要在选中值内再补一个相同kv

**Comment by xiaoxian521** [comment]
@TLovers 嘿，这个 [demo](https://github.com/element-plus/element-plus/pull/7175) 可能满足你的需求
