### ISSUE TITLE
input组件建议传出按键原生事件

### ISSUE THREAD

**Issue by Eki0354** [element-plus/element-plus#837]
直接在el-input上写v-on:keyup和v-on:keypress事件是不起作用的，因为vue3取消了native修饰符，源码里只emit了keydown事件，导致需要判断按键的时候使用很不方便，不知道有没有其他方法解决？

**Comment by JeremyWuuuuu** [comment]
Let me confirm that you need these events from "input" itself or somewhere else?

**Comment by Eki0354** [comment]
> Let me confirm that you need these events from "input" itself or somewhere else?

Yes, from base 'input'. I can't find a implementation if the page needs do something after someone pressed 'Enter' in 'input'.

**Comment by JeremyWuuuuu** [comment]
https://github.com/element-plus/element-plus/blob/dev/packages/select/src/select.vue#L96
I just checked the code of select seems it uses these events seamlessly like native input, maybe we didn't update the documentation

**Comment by Eki0354** [comment]
> https://github.com/element-plus/element-plus/blob/dev/packages/select/src/select.vue#L96
> I just checked the code of select seems it uses these events seamlessly like native input, maybe we didn't update the documentation

Sorry for confusing you. I want to listen the event of 'keyup' or 'keypress' on 'el-input' instead of native 'input'. However, they only provide 'keydown' for 'el-input' right now.

**Comment by JeremyWuuuuu** [comment]
You can see that we have `v-bind="attrs"  sentence on `el-input` see the pic:
![image](https://user-images.githubusercontent.com/15975785/101245070-4da71a00-3745-11eb-84c5-8a6b871d5db5.png)
This means your events will be inherited directly to `el-input` or `input` or `textarea`.

**Comment by JeremyWuuuuu** [comment]
Try it for yourself see if the events gets fired after the interactions

**Comment by Ttou** [comment]
是有这样的情况，ElInput 绑定后不生效，原生的可以：
![Dingtalk_20201206122508](https://user-images.githubusercontent.com/4298437/101271510-5e47a680-37be-11eb-8f9f-9126f4a44d26.jpg)
