### ISSUE TITLE
[Bug Report] [Component] [table] el-table 不会显示子节点的问题

### ISSUE THREAD

**Issue by aa294828045** [element-plus/element-plus#8370]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxkaXY+XG4gICAgICB7eyB0YWJsZURhdGEgfX1cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IHN0eWxlPVwibWFyZ2luLXRvcDogMjBweFwiPlxuICAgICAge3sgdGFibGVEYXRhWzBdLmhhc0NoaWxkcmVuID8gJ2hhc0NoaWxkcmVuJyA6ICdmYWxzZSd9fVxuICAgIDwvZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMjBweDsgbWFyZ2luLXRvcDogMjBweFwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICAgIDp0cmVlLXByb3BzPVwieyBjaGlsZHJlbjogJ2NoaWxkcmVuJywgaGFzQ2hpbGRyZW46ICdoYXNDaGlsZHJlbicgfVwiXG4gICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jbGFzcyBVc2VyIHtcbiAgaWQ6IG51bWJlclxuICBuYW1lOiBzdHJpbmdcbiAgc3ViOiBVc2VyW11cbiAgZ2V0IGNoaWxkcmVuKCl7XG4gICAgcmV0dXJuIHRoaXMuc3ViO1xuICB9XG4gIFxuICBnZXQgaGFzQ2hpbGRyZW4oKXtcbiAgICAvLyDms6jph4rmjonov5nooYzlsLHkvJrmraPluLjmmL7npLrlrZDooYxcbiAgICByZXR1cm4gdGhpcy5zdWIgIT0gbnVsbCAmJiB0aGlzLnN1Yi5sZW5ndGggPiAwXG4gIH1cbn1cbiAgY29uc3QgdGFibGVEYXRhIDogVXNlcltdICA9IFtdO1xuXG4gIGxldCB1c2VyUm9vdCA9IG5ldyBVc2VyKCk7XG4gIHVzZXJSb290LmlkID0gMTtcbiAgdXNlclJvb3QubmFtZSA9ICdyb290J1xuICB1c2VyUm9vdC5zdWIgPSBbbmV3IFVzZXIoKV07XG4gIFxuICB1c2VyUm9vdC5zdWJbMF0uaWQgPSAyO1xuICB1c2VyUm9vdC5zdWJbMF0ubmFtZSA9ICd1MSc7XG4gIHVzZXJSb290LnN1YlswXS5zdWIgPSBbbmV3IFVzZXIoKV07XG4gIFxuICB1c2VyUm9vdC5zdWJbMF0uc3ViWzBdLmlkID0gMztcbiAgdXNlclJvb3Quc3ViWzBdLnN1YlswXS5uYW1lID0gJ20xJztcbiAgXG5cdHRhYmxlRGF0YS5wdXNoKHVzZXJSb290KVxuICBcbiAgXG4gIFxuICBcbiAgXG4gIFxuICBcbiAgXG4gIFxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

  get hasChildren(){
    // 注释掉这行就会正常显示子行
    return this.sub != null && this.sub.length > 0
  }

### What is Expected?

hasChildren判断是否显示子行,true显示，false不显示

### What is actually happening?

hasChildren影响了子行没被显示出来

### Additional comments

_(empty)_

**Comment by tolking** [comment]
hasChildren work with `lazy`, [check docs](https://element-plus.org/zh-CN/component/table.html#%E6%A0%91%E5%BD%A2%E6%95%B0%E6%8D%AE%E4%B8%8E%E6%87%92%E5%8A%A0%E8%BD%BD)

**Comment by aa294828045** [comment]
thank，close issue
