### ISSUE TITLE
[Bug Report] [TypeScript] Error compiling d.ts file with vue-tsc

### ISSUE THREAD

**Issue by Mario34** [element-plus/element-plus#8382]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome 102.0.5005.61/Mac os 12.2.1 `
- Build Tool: `Other`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/Mario34/vue-tsc-bug)

### Steps to reproduce

```bash
$ pnpm run build:dts

> element-plus-dts@1.0.0 build:dts /Users/mario/Project/element-plus-dts
> vue-tsc --declaration --emitDeclarationOnly

src/demo.vue:9:25 - error TS2742: The inferred type of 'default' cannot be named without a reference to '.pnpm/@vue+shared@3.2.37/node_modules/@vue/shared'. This is likely not portable. A type annotation is necessary.

  9 <script setup lang="ts">
                            
 10 import { ref } from 'vue'
    ~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 18 })
    ~~
 19 </script>
    


Found 1 error in src/demo.vue:9

 ELIFECYCLE  Command failed with exit code 1.
```

### What is Expected?

The SFC file is compiled correctly

### What is actually happening?

An error occurred

### Additional comments

_(empty)_

**Comment by Mario34** [comment]
> Try `declaration: false` in `tsconfig.json`

The 'declaration: false' parameter is invalid for vue-tsc，you can see this problem in the [repo](https://github.com/Mario34/vue-tsc-bug). 

I'm not sure if it's vuE-TSC or Element-Plus，but the problem does exist.

**Comment by sxzz** [comment]
Can't reproduce in your repo. Please try reinstall `node_modules`

**Comment by Mario34** [comment]
> Can't reproduce in your repo. Please try reinstall `node_modules`

Sorry, the repo did not reproduce the problem. I'll modify the repo to make sure I can locate the problem.
