### ISSUE TITLE
[Bug Report] [Component] [tooltip] el-tooltip 设置overflow-y: auto，箭头消失

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#8384]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcFxuICAgIGNvbnRlbnQ9XCI8c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPjxzcGFuPlRoZSBjb250ZW50IGNhbiBiZSA8c3Ryb25nPkhUTUw8L3N0cm9uZz48L3NwYW4+PHNwYW4+VGhlIGNvbnRlbnQgY2FuIGJlIDxzdHJvbmc+SFRNTDwvc3Ryb25nPjwvc3Bhbj48c3Bhbj5UaGUgY29udGVudCBjYW4gYmUgPHN0cm9uZz5IVE1MPC9zdHJvbmc+PC9zcGFuPlwiXG4gICAgcmF3LWNvbnRlbnRcbiAgICBwbGFjZW1lbnQ9XCJyaWdodFwiXG4gID5cbiAgICA8ZWwtYnV0dG9uPmhvdmVyIG1lPC9lbC1idXR0b24+XG4gIDwvZWwtdG9vbHRpcD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmVsLXBvcHBlciB7XG4gICAgd2lkdGg6IDIwMHB4O1xuICAgIGhlaWdodDogMjAwcHg7XG4gICAgb3ZlcmZsb3cteTogYXV0bztcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.打开playground
2.hover到按钮上面

### What is Expected?

tooltip箭头不消失

### What is actually happening?

tooltip箭头消失

### Additional comments

_(empty)_

**Comment by JackieCheung** [comment]
> 看了下，是因为小箭头是el-tooltip的子元素，el-tooltip设置overflow-y: auto，子元素超出不了父元素，就不显示了，官方要改的话就得把小箭头的html层次往上提，或者你可以试试给el-tooltip下面的span加overflow-y: auto

没错 我已经用`slot#content `然后再对应设置`overflow-y: auto` 来解决了

**Comment by chenxch** [comment]
使用方式正如你们所述和所实现的。👍
