### ISSUE TITLE
message组件需求

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/element-plus#839]
可以将message全局添加{ showClose: true }

```
  setup() {
    const message = getCurrentInstance()?.appContext.config.globalProperties
      .$message;

    // 刷新验证码
    const refreshGetVerify = async () => {
      let { svg } = await getVerify();
      contextInfo.svg = svg;
    };

    const contextInfo: ContextProps = reactive({
      userName: "",
      passWord: "",
      verify: null,
      svg: null,
    });

    // 登录
    const onLogin = async () => {
      let { userName, passWord, verify } = contextInfo;
      let { code, info } = await getLogin({
        username: userName,
        password: passWord,
        verify: verify,
      });
      code === 0
        ? message({
            message: info,
            type: "success",
          })
        : message(info);
    };

    const refreshVerify = (): void => {
      refreshGetVerify();
    };

    onBeforeMount(() => {
      refreshGetVerify();
    });

    return {
      contextInfo,
      onLogin,
      refreshVerify,
    };
  },
```

不希望每个message都配置{showClose: true,}  可以提供一个全局的配置

**Comment by JeremyWuuuuu** [comment]
You can use message via importing isteadof getting it from global properties. Also you are able to encapsulate your own message based on that, just one more function call would not cause any perf issue

**Comment by xiaoxian521** [comment]
可以提供下示例代码吗 我全家注册这个东西 通过this.$message就拿不到了

**Comment by xiaoxian521** [comment]
可以提供示例代码吗？我全局注册了，就拿不到这个this.$message

**Comment by JeremyWuuuuu** [comment]
Global method

Element Plus has added a global method $message for app.config.globalProperties. So in a vue instance you can call Message like what we did in this page.

Local import

import { ElMessage } from 'element-plus';
In this case you should call ElMessage(options). We have also registered methods for different types, e.g. ElMessage.success(options). You can call ElMessage.closeAll() to manually close all the instances.

**Comment by JeremyWuuuuu** [comment]
Or you can import like 
`import Message from 'element-plus/lib/el-message'`

**Comment by xiaoxian521** [comment]
我已经全家导入element 为什么还需要单独这么引用呢？

**Comment by xiaoxian521** [comment]
我已经全局导入element 为什么还需要单独这么引用呢？

**Comment by JeremyWuuuuu** [comment]
In setups you use it like
`const message = getCurrentInstance()?.appContext.config.globalProperties
      .$message;`
Which is more code than you import it directly

In options API you can use it as before via `this.$message`

**Comment by xiaoxian521** [comment]
haha 这是我没找到更好的办法才出此下策

**Comment by JeremyWuuuuu** [comment]
You may make a file which named useConfig 
useConfig.ts
```
import { getCurrentInstance } from 'vue'

export function useConfig() {
  const { appContext } = getCurrentInstance()
  return appContext.config.globalPropeties
```

Might save you some code

**Comment by xiaoxian521** [comment]
我在main.ts中这样全家注册import ElementPlus from 'element-plus'
import 'element-plus/lib/theme-chalk/index.css'

// 导入公共样式
import "./assets/index.css"

const app = createApp(App)

import Message from 'element-plus/lib/el-message'

app.config.globalProperties.$message = Message

app.use(store).use(router).use(ElementPlus).mount('#app')


然后在单页面中使用this.$message(""); 会报TypeError: Cannot read property '$message' of undefined

**Comment by xiaoxian521** [comment]
是我但方法有问题吗？

**Comment by JeremyWuuuuu** [comment]
> 我在main.ts中这样全家注册import ElementPlus from 'element-plus'
> import 'element-plus/lib/theme-chalk/index.css'
> 
> // 导入公共样式
> import "./assets/index.css"
> 
> const app = createApp(App)
> 
> import Message from 'element-plus/lib/el-message'
> 
> app.config.globalProperties.$message = Message
> 
> app.use(store).use(router).use(ElementPlus).mount('#app')
> 
> 然后在单页面中使用this.$message(""); 会报TypeError: Cannot read property '$message' of undefined

example please

**Comment by xiaoxian521** [comment]
就是在setup中直接使用this.$message("");

**Comment by JeremyWuuuuu** [comment]
setup don't have a `this`, please go read the documentation

**Comment by JeremyWuuuuu** [comment]
https://v3.vuejs.org/guide/composition-api-setup.html#usage-of-this

**Comment by xiaoxian521** [comment]
我知道 render可以使用 但是这样但话 我每个vue单页面是不是都要import Message from 'element-plus/lib/el-message'

**Comment by JeremyWuuuuu** [comment]
use options API is better for your need

**Comment by xiaoxian521** [comment]
好吧 谢谢

**Comment by zazzaz** [comment]
import { ElMessage } from 'element-plus'

You can check the doc here https://element-plus.org/#/en-US/component/message
