### ISSUE TITLE
[Bug Report] [Component] [table, table-column] the element .el-table__placeholder was disapper

### ISSUE THREAD

**Issue by zedyuan999** [element-plus/element-plus#8391]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/PsyduckOnTheMoon/pen/mdXYLwo?editors=1000)

### Steps to reproduce

codepen:https://codepen.io/PsyduckOnTheMoon/pen/mdXYLwo?editors=1000
compare with table's style after remove the line include 'nextTick'

### What is Expected?

span.el-table__placeholder appear

### What is actually happening?

the element span.el-table__placeholder was disappear

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment]
Hi, @zedyuan999 I can't repeat this error when I turn `nextTick` on or hide, the `span.el-table__placeholder` is always been there

**Comment by zedyuan999** [comment]
> Hi, @zedyuan999 I can't repeat this error when I turn `nextTick` on or hide, the `span.el-table__placeholder` is always been there

当时我用的是2.2.0版本，应该是后面被修复了，感谢大佬
