### ISSUE TITLE
el-date-picker 取消左右侧日历联动 unlink-panels 失效了

### ISSUE THREAD

**Issue by vipsunwei** [element-plus/element-plus#840]
`<el-date-picker
      v-model="date"
      type="datetimerange"
      range-separator="至"
      start-placeholder="开始日期"
      end-placeholder="结束日期"
      :unlink-panels="false"
      @change="handleDatePickerChange"
    >
    </el-date-picker>`

我一开始刚看到这个属性高兴极了， 马上试了一下，当时是好使的， 

写了几天发现取消联动失效了，这部分代码什么都没改，更新element-plus到beta3 也不好使

**Comment by JimmyJim1** [comment]
Ok

**Comment by zazzaz** [comment]
A reproduction demo, please? The demo on the doc website is working correctly.

**Comment by JeremyWuuuuu** [comment]
Even though I think I somehow know the root cause of this bug, but we still need you to provide some code for us to reproduce it. Thank you

**Comment by vipsunwei** [comment]
@JeremyWuuuuu sorry，是我理解错了，用错了
