### ISSUE TITLE
[Bug Report] [Style] [select] multiple select inner input reduce 2px when selected length equal 0

### ISSUE THREAD

**Issue by youpinyao** [element-plus/element-plus#8404]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-select`

### Reproduction Link

[Link]( http://element-plus.antadesign.cn/select)

### Steps to reproduce

多选select，未选中状态到选中一个后，出现高度变动

### What is Expected?

select 高度保持一致

### What is actually happening?

select高度变化了

### Additional comments

_(empty)_

**Comment by youpinyao** [comment]
已修复的 pull request： https://github.com/element-plus/element-plus/pull/8209

**Comment by kooriookami** [comment]
Fixed
