### ISSUE TITLE
[Bug Report] [Component] [alert] el-alert 组件 icon 默认为大尺寸，无法调节

### ISSUE THREAD

**Issue by NQLoong** [element-plus/element-plus#8406]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.24`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome 102.0.5005.115/win 10`
- Build Tool: `Vite`

### Related Component

- `el-alert`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gICAgPGVsLWFsZXJ0IHR5cGU9XCJ3YXJuaW5nXCIgOmNsb3NhYmxlPVwiZmFsc2VcIiBzaG93LWljb25cbiAgICAgID48dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIOW9k+aciOi0puWNleaVsOaNruS4i+aciDXml6XmiY3lh7rvvIzmnKrliIbphY3pobnnm64g5p+l55yL5LqR6YCa5L+h5Lqn5ZOB5LiH572R5Lqn5ZOBXG4gICAgICAgIOWIhuaLhuWei+S6keS6p+WTge+8iOS+i+Wmgu+8mkNETuOAgU9TU+OAgeWFseS6q+W4puWuveetie+8ieWQhOS4quWIhuaLhumhue+8iOS+i+Wmgu+8muWfn+WQjeOAgUJ1Y2tldOOAgUVJUOetie+8ieeahOWFt+S9k+i0ueeUqO+8jOivt+WJjeW+gOWIhui0pui0puWNleafpeeci1xuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWFsZXJ0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

按官方示例，给el-alert 添加show-icon属性

### What is Expected?

图标大小,和官网一致为小图标

### What is actually happening?

图标大小为WarningFilled的大图标

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/34368864/174941895-159cbfcc-5a79-46c3-8aa1-c8c531693805.png)
![image](https://user-images.githubusercontent.com/34368864/174941930-a6633d77-6802-4952-9e28-d3ad5d5ff723.png)

**Comment by tolking** [comment]
you need to use the [title slot](https://element-plus.org/en-US/component/alert.html#alert-slots)
