### ISSUE TITLE
Missing defineComponent() in components breaks VS Code Intellisense support

### ISSUE THREAD

**Issue by boonyasukd** [element-plus/element-plus#841]
I'm currently migrating codebase with **VS Code** with **Volar**, which [Evan suggested his team to use instead of **Vetur** "for now"](https://github.com/vuejs/vitepress/pull/137#issuecomment-733868635) (at least until Vetur is fully up-to-date with Vue 3).

While developing, I found that Intellisense inside `<template>` section doesn't work on some of the `element-plus`' components. After inspecting the source code, these components seem to directly export plain objects instead of wrapping with `defineComponent()` first before returning. For example, `ElMenu` code uses `defineComponent()`, while `ElSubmenu` and `ElMenuItem` return plain objects, the Intellisense is broken on the latter two:

![image](https://user-images.githubusercontent.com/8109816/101184409-428bb580-3683-11eb-8a76-d9524a72ccd6.png)

Searching through the codebase, right now there seems to be 10 components that don't use `defineComponent()` yet:

![image](https://user-images.githubusercontent.com/8109816/101185255-381deb80-3684-11eb-9bec-1a6a90320d26.png)

It'd be great if you can fix these components to be compatible with VS Code. Thank you.

**Comment by JeremyWuuuuu** [comment]
Thank you for bringing this up, I promise that we will get this fixed ASAP!

**Comment by JeremyWuuuuu** [comment]
I dunno whether the current fix in #849 is going to fix all the problems in `Volar`, please give us feedback when you get errors. I am at your service.

**Comment by boonyasukd** [comment]
@JeremyWuuuuu Thank you for the quick fix. I will test and give a feedback.
