### ISSUE TITLE
[Bug Report] [Component] [tree] Lazy load Tree,`default-checked-keys` Set first two of keys,All sibling nodes to be checked.

### ISSUE THREAD

**Issue by Tsong-LC** [element-plus/element-plus#8410]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIDpwcm9wcz1cInByb3BzXCJcbiAgICA6bG9hZD1cImxvYWROb2RlXCJcbiAgICBsYXp5XG4gICAgc2hvdy1jaGVja2JveFxuICAgIG5vZGUta2V5PVwibmFtZVwiXG4gICAgOmRlZmF1bHQtY2hlY2tlZC1rZXlzPVwiWydsZWFmJywgJ3pvbmUtb25lJ11cIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcblxuaW50ZXJmYWNlIFRyZWUge1xuICBuYW1lOiBzdHJpbmdcbiAgbGVhZj86IGJvb2xlYW5cbn1cblxuY29uc3QgcHJvcHMgPSB7XG4gIGxhYmVsOiAnbmFtZScsXG4gIGNoaWxkcmVuOiAnem9uZXMnLFxuICBpc0xlYWY6ICdsZWFmJyxcbn1cblxuY29uc3QgbG9hZE5vZGUgPSAobm9kZTogTm9kZSwgcmVzb2x2ZTogKGRhdGE6IFRyZWVbXSkgPT4gdm9pZCkgPT4ge1xuICBpZiAobm9kZS5sZXZlbCA9PT0gMCkge1xuICAgIHJldHVybiByZXNvbHZlKFt7IG5hbWU6ICdyZWdpb24tb25lJyB9LCB7IG5hbWU6ICdyZWdpb24tdHdvJyB9XSlcbiAgfVxuICBpZiAobm9kZS5sZXZlbCA+IDEpIHJldHVybiByZXNvbHZlKFtdKVxuXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ2xlYWYnLFxuICAgICAgICBsZWFmOiB0cnVlLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbmFtZTogJ3pvbmUtb25lJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICd6b25lLXR3bycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnem9uZS10aHJlZScsXG4gICAgICB9LFxuICAgIF1cblxuICAgIHJlc29sdmUoZGF0YSlcbiAgfSwgNTAwKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.Lazy load leaf node.

2.Set first two of keys of initially checked nodes.

3.Expanded parentNode.

### What is Expected?

Set default-checked-key nodes to be checked

### What is actually happening?

All sibling nodes to be checked

### Additional comments

_(empty)_

**Comment by lnyie** [comment]
same problem
