### ISSUE TITLE
[Bug Report] [Component] [input] input加了clearable属性后输入内容宽度会发生变化！失去焦点恢复原始宽度，获取焦点又会宽度改变

### ISSUE THREAD

**Issue by lait233** [element-plus/element-plus#8411]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1pbnB1dC1zdWZmaXhcIj5cblxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImRlbW8taW5wdXQtc3VmZml4XCI+XG4gICAgICAgICAgICAgICAgPGVsLWZvcm0gOmlubGluZT1cInRydWVcIiA6bW9kZWw9XCJzZWFyY2hcIj5cblxuICAgICAgICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi57yW5Y+3XCI+XG4gICAgICAgICAgICAgICAgPGVsLWlucHV0IHNpemU9XCJtaW5pXCIgdi1tb2RlbD1cInNlYXJjaC5jb2RlXCIgcGxhY2Vob2xkZXI9XCLnvJblj7dcIiBvbmtleXVwPVwidmFsdWU9dmFsdWUucmVwbGFjZSgvW1xcdTRFMDAtXFx1OUZBNV0vZywnJylcIiBcbiAgICAgICAgICAgICAgICAgICAgICAgICAgPjwvZWwtaW5wdXQ+XG4gICAgICAgICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuXG4gICAgICAgICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLkuK3mloflkI3np7BcIj5cbiAgICAgICAgICAgICAgICA8ZWwtaW5wdXQgc2l6ZT1cIm1pbmlcIiB2LW1vZGVsPVwic2VhcmNoLm5hbWVfY25cIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpVwiIG9ua2V5dXA9XCJ2YWx1ZT12YWx1ZS5yZXBsYWNlKC9bXFx1NEUwMC1cXHU5RkE1XS9nLCcnKVwiIFxuICAgICAgICAgICAgICAgICAgICAgICAgICBjbGVhcmFibGU+PC9lbC1pbnB1dD5cbiAgICAgICAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG5cbiAgICAgICAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuiLseaWh+WQjeensFwiPlxuICAgICAgICAgICAgICAgIDxlbC1pbnB1dCBzaXplPVwibWluaVwiIHYtbW9kZWw9XCJzZWFyY2gubmFtZV9lblwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWlXCIgIGNsZWFyYWJsZT48L2VsLWlucHV0PlxuICAgICAgICAgICAgICA8L2VsLWZvcm0taXRlbT5cblxuXG4gICAgICAgICAgICAgIDwhLS0gPGVsLWZvcm0taXRlbT5cbiAgICAgICAgICAgICAgICAgPGVsLXNlbGVjdCBzaXplPVwibWluaVwiIHYtbW9kZWw9XCJzZWFyY2guc3RhdHVzXCIgcGxhY2Vob2xkZXI9XCLnirbmgIHvvIjpu5jorqTlhajpg6jvvIlcIiBjbGVhcmFibGUgZmlsdGVyYWJsZSBtdWx0aXBsZSBjb2xsYXBzZS10YWdzXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgY29sbGFwc2UtdGFncy10b29sdGlwPlxuICAgICAgICAgICAgICAgICAgIDxlbC1vcHRpb24gdi1mb3I9XCIodmFsLGtleSkgaW4gcGFnZU9wdGlvbnMuc3RhdHVzVGV4dFwiIDpsYWJlbD1cInZhbFwiIDp2YWx1ZT1cImtleVwiPjwvZWwtb3B0aW9uPlxuICAgICAgICAgICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgICAgICAgICAgIDwvZWwtZm9ybS1pdGVtPi0tPlxuXG4gICAgICAgICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLliJvlu7rml6XmnJ9cIj5cbiAgICAgICAgICAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgICAgICAgICAgICAgICAgIHYtbW9kZWw9XCJzZWFyY2guY3JlYXRlX3RpbWVcIlxuICAgICAgICAgICAgICAgICAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgICAgICAgICAgICAgICAgICB1bmxpbmstcGFuZWxzXG4gICAgICAgICAgICAgICAgICAgICAgICByYW5nZS1zZXBhcmF0b3I9XCJUb1wiXG4gICAgICAgICAgICAgICAgICAgICAgICBzdGFydC1wbGFjZWhvbGRlcj1cIlN0YXJ0IGRhdGVcIlxuICAgICAgICAgICAgICAgICAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuXG4gICAgICAgICAgICAgICAgICAgICAgICBmb3JtYXQ9XCJZWVlZLU1NLUREXCJcbiAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlLWZvcm1hdD1cIlhcIlxuICAgICAgICAgICAgICAgID48L2VsLWRhdGUtcGlja2VyPlxuICAgICAgICAgICAgICA8L2VsLWZvcm0taXRlbT5cblxuICAgICAgICAgICAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgICAgICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBzaXplPVwibWluaVwiIEBjbGljaz1cInNlYXJjaC5wYWdlPTE7Z2V0TGlzdCgpXCI+5p+l6K+iPC9lbC1idXR0b24+XG4gICAgICAgICAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgc2l6ZT1cIm1pbmlcIiBAY2xpY2s9XCJyZXNldFwiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICA8L2VsLWZvcm0taXRlbT5cblxuICAgICAgICAgICAgPC9lbC1mb3JtPlxuXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENhbGVuZGFyLCBTZWFyY2ggfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGlucHV0MSA9IHJlZignJylcbmNvbnN0IGlucHV0MiA9IHJlZignJylcbmNvbnN0IGlucHV0MyA9IHJlZignJylcbmNvbnN0IGlucHV0NCA9IHJlZignJylcbmNvbnN0IHNlYXJjaCA9IHJlZih7XG4gICAgcGFnZSAgICAgICA6IDEsXG4gICAgbGltaXQgICAgICA6IDMwLFxuICAgIGNvZGUgICAgICAgOiBudWxsLFxuICAgIG5hbWVfY24gICAgOiBudWxsLFxuICAgIG5hbWVfZW4gICAgOiBudWxsLFxuICAgIGNyZWF0ZV90aW1lOiBudWxsLFxufSk7XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击复现连接即可看到
在中文名称input输入内容然后失去焦点。然后在获取焦点就会变形

### What is Expected?

input宽度不变形

### What is actually happening?

input加了clearable属性就会变形

### Additional comments

_(empty)_

<img width="1893" alt="element-input-bug" src="https://user-images.githubusercontent.com/31282366/174963852-6796fa04-84fa-48f2-8b89-906f7ccc7f86.png">

**Comment by tolking** [comment]
It is recommended to set a min-width or width for the Input component.

reference #7287

**Comment by chenxch** [comment]
> 今天我也发现了这问题. 原因是我的文本并不是左对齐, 而是居中对齐的. 然后你会发现**鼠标移入和移出的时候, 文本就在那左右跳**. **建议只要是输入框有文本的时候, 就一直显示这个删除按钮**. 不要在Hover的时候来回显示的...不需要这样.
> 
> 可以参考AntD vue和Vuetify的输入框, 都是这样的.
> 
> https://antdv.com/components/input-cn#components-input-demo-allow-clear https://vuetifyjs.com/zh-Hans/components/text-fields/#section-53ef6e059664

hover这个应该是组件库交互设计上的差异，我认为主要的问题点应该是在目前我们的clearable不是采用flex布局导致的。

**Comment by zcf0508** [comment]
Same problem.

**Comment by HeftyKoo** [comment]
Duplicate: #7287

**Comment by sdsdgit** [comment]
主要原因是input外部缺少固定宽度的容器，这个问题比较棘手，可能官方也没有好的处理方式，可以使用栅格布局，用<el-row><el-col>包裹<el-form-item>，这样就不用担心宽度的变化
