### ISSUE TITLE
[Bug Report] [Component] [pagination, menu-item] After Paginating, Cannot Interact With Menu Item

### ISSUE THREAD

**Issue by matthew-williamson-sd** [element-plus/element-plus#8422]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome 102.0.5005.115 macOS 12.3.1` 
- Build Tool: `Vue CLI`

### Related Component

- `el-pagination`
- `el-menu-item`

### Reproduction Link

[CodePen](https://codepen.io/mdw-sd/pen/wvyLeQY)

### Steps to reproduce

Set up a page with el-menu el-table and el-pagination components. After paginating the table, you will not be able to interact with the menu items.  Interacting with the el-input in the minimal reproduction at the top of the page then means you can click the 'Page' menu item successfully

### What is Expected?

Clicking the 'Page' menu item navigates to a new page (or in the case of the minimal reproduction, prints a message to the console)

### What is actually happening?

The browser jumps to the bottom of the page, but no message is printed

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/175102094-137470ff-76d9-4f51-846e-524e231903d9.png)
I found printing in the console, is there a more complete operation step, I just simply clicked the pagination and drop-down menu. `el-input` you need to bind `v-model` to it.

**Comment by matthew-williamson-sd** [comment]
Think I've got to the issue with _why_ this is happening. When you click the menu item you end up triggering `onFocusIn` in `focus-trap.vue`. Eventually this leads to `onFocusInTrap` being called within the popper `content.vue`. The issue is that the `relatedTarget` is whichever pagination button you clicked. That means that `onFocusInTrap` attempts to scroll:

```javascript
if (event.relatedTarget) {
  ;(event.relatedTarget as HTMLElement)?.focus()
}```

This all happens _before_ the click event fires, and given the screen has moved I assume it doesn't end up clicking the button correctly (and presumably that's why if you're in a situation where the page either can't or doesn't scroll then everything works as expected).

Only issue is that I'm not sure how to fix for this specific issue without causing issues elsewhere. 

@chenxch with all the information above are you able to reproduce now? Or does this remain a mac issue (I can reproduce in both chrome and firefox)

**Comment by chenxch** [comment]
> @chenxch with all the information above are you able to reproduce now? Or does this remain a mac issue (I can reproduce in both chrome and firefox)

I'm very sorry, I missed your message. According to the video and operation steps you provided, I reproduced it. This is indeed a focus trap related performance.

**Comment by c1wren** [comment]
Is there any progress on this issue? I've been experiencing it as well the past month and just now found this Github issue otherwise I would have created it myself.

**Comment by chenxch** [comment]
> Is there any progress on this issue? I've been experiencing it as well the past month and just now found this Github issue otherwise I would have created it myself.

Sorry I forgot about it, your pr is welcome.

**Comment by c1wren** [comment]
Oh, let me clarify, I don't have this problem fixed. I was saying I was going to open this issue if it wasn't already open.

**Comment by chenxch** [comment]
Okay, I'll check it out tonight.

**Comment by chenxch** [comment]
Maybe the same problem. #9077
