### ISSUE TITLE
[Bug Report] [Component] [table] When the content of the table is empty, it cannot be scrolled, resulting in incomplete table header display

### ISSUE THREAD

**Issue by Ytiona** [element-plus/element-plus#8432]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.5`
- Browser / OS: `Chrome/83.0.4103.97`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsVGFibGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxlbC10YWJsZSA6ZGF0YT1cIltdXCIgYm9yZGVyPlxuICBcdDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLmoIfpopgxXCIgbWluLXdpZHRoPVwiNTAwXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIuagh+mimDJcIiBtaW4td2lkdGg9XCI1MDBcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi5qCH6aKYM1wiIG1pbi13aWR0aD1cIjUwMFwiPjwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLmoIfpopg0XCIgbWluLXdpZHRoPVwiNTAwXCI+PC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIuagh+mimDVcIiBtaW4td2lkdGg9XCI1MDBcIj48L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi5qCH6aKYNlwiIG1pbi13aWR0aD1cIjUwMFwiPjwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

When the content of the table is empty, it cannot be scrolled, resulting in incomplete table header display

### What is Expected?

Header overflow scrollable

### What is actually happening?

Title overflow unable to scroll

### Additional comments

_(empty)_

**Comment by plainheart** [comment]
It is a regression bug. Fixed in #8690.
