### ISSUE TITLE
[Component] [radio] el-radio  id无效问题

### ISSUE THREAD

**Issue by anjisZhou** [element-plus/element-plus#8449]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-radio`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCByYWRpbzEgPSByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgPGxhYmVsIGZvcj1cIjEyM1wiPmNsaWNrIG1lPC9sYWJlbD5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvMVwiIGNsYXNzPVwibWwtNFwiPlxuICAgICAgPGVsLXJhZGlvIGlkPVwiMTIzXCIgbGFiZWw9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiMlwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

设置el-radio组件的id，当使用label for属性绑定id时，点击label   el-radio无反应。

### What is Expected?

el-radio有反应

### What is actually happening?

el-radio无反应

### Additional comments

_(empty)_

**Comment by anjisZhou** [comment]
> @anjisZhou 建议先不要使用id，自己建立点击事件去进行需要的联动。
好的，我现在是这样处理哒，刚刚[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCByYWRpbzEgPSByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgPGxhYmVsIGZvcj1cIjEyM1wiPmNsaWNrIG1lPC9sYWJlbD5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvMVwiIGNsYXNzPVwibWwtNFwiPlxuICAgICAgPGVsLXJhZGlvIGlkPVwiMTIzXCIgbGFiZWw9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiMlwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)这里面看点击label可以和input进行联动了，这是已经优化了吗

**Comment by chenxch** [comment]
目前是做了一个版本的修复，但是在后期检查中这个pr存在争议，可能会回退，我是担心这个可能会给你造成困恼，特地来和你说一下哈。
