### ISSUE TITLE
[Component] [input] el-input 的 change 事件当值未变化，就失去焦点或按下回车，不会触发

### ISSUE THREAD

**Issue by SignDawn** [element-plus/element-plus#8450]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome/103.0.5060.53 / Window10`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBAY2hhbmdlPSdjaGFuZ2UnIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpO1xuICBcbiAgXG4gIGZ1bmN0aW9uIGNoYW5nZSgpIHtcbiAgICBjb25zb2xlLmxvZygn6Kem5Y+RIGNoYW5nZScpO1xuICB9XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

查看复现环境一目了然。

### What is Expected?

期望它是 blur + keydown.Enter 的组合

### What is actually happening?

（必须要值改变）后失去焦点或Enter 才会触发。

### Additional comments

查看了一下源码，源码中使用的是原生 input 的 change 事件，它就是这样的。
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/change_event
我认为无需更改源码，只需要更改一下文档即可，以免带来歧义。

**Comment by tolking** [comment]
It is possible to optimize the document.
