### ISSUE TITLE
[Component] [popover] 按需自动导入时，popover 组件样式在暗黑模式下无法生效

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus#8452]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter/issues/43)

### Steps to reproduce

使用 [element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter) 运行并添加 popover 组件示例代码后，切换到暗黑模式即可看到问题

### What is Expected?

/

### What is actually happening?

/

### Additional comments

_(empty)_

**Comment by holazz** [comment]
Element Plus 升级到最新版本试试

**Comment by hooray** [comment]
@holazz 使用 element-plus-vite-starter 这个库做的测试，默认安装就是最新版本的 element plus

**Comment by holazz** [comment]
@hooray 这个 [PR](https://github.com/element-plus/element-plus/pull/8133) 应该可以解决你的问题。cc @YunYouJun

**Comment by YunYouJun** [comment]
Merged.
