### ISSUE TITLE
[Component] [tooltip, input] 被tooltip组件包裹的textarea输入时无法换行

### ISSUE THREAD

**Issue by love-loli** [element-plus/element-plus#8456]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome/102.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-tooltip`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcCBjb250ZW50PVwi6K+36L6T5YWl5YaF5a65XCI+XG4gIFx0PGRpdj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiB0eXBlPVwidGV4dGFyZWFcIi8+XG4gICAgPC9kaXY+XG4gIDwvZWwtdG9vbHRpcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJyk7XG4gIFxuICBcbiAgZnVuY3Rpb24gY2hhbmdlKCkge1xuICAgIGNvbnNvbGUubG9nKCfop6blj5EgY2hhbmdlJyk7XG4gIH1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

进入playground，在输入框内输入内容，然后按下回车

### What is Expected?

换行

### What is actually happening?

没有换行

### Additional comments

_(empty)_

**Comment by love-loli** [comment]
更新版本后出现的

**Comment by tolking** [comment]
Enter 按键事件默认会被 tooltip 用来展示弹窗信息，你可以使用 `trigger-keys` 来修改触发这种行为的按键

```vue
<el-tooltip :trigger-keys="[]" content="请输入内容">
    <div>
      <el-input v-model="input" type="textarea" />
    </div>
  </el-tooltip>
```

**Comment by love-loli** [comment]
> Enter 按键事件默认会被 tooltip 用来展示弹窗信息，你可以使用 `trigger-keys` 来修改触发这种行为的按键
> 
> ```
> <el-tooltip :trigger-keys="[]" content="请输入内容">
>     <div>
>       <el-input v-model="input" type="textarea" />
>     </div>
>   </el-tooltip>
> ```
好的 多谢回复
