### ISSUE TITLE
[Component] [dropdown] popper options are not used

### ISSUE THREAD

**Issue by amaury-hanser** [element-plus/element-plus#8464]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.6`
- Browser / OS: `Irrevelant`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1kcm9wZG93biA6cG9wcGVyLW9wdGlvbnM9XCJ7b2Zmc2V0OiBbMTAwLCAyMDBdfVwiPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPlxuICAgICAgICBEcm9wZG93biBMaXN0PGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1yaWdodFwiPjxhcnJvdy1kb3duIC8+PC9lbC1pY29uPlxuICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWRyb3Bkb3duPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBBcnJvd0Rvd24gfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoKSA9PiB7XG4gIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSBuby1hbGVydFxuICBhbGVydCgnYnV0dG9uIGNsaWNrJylcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

- Create a `el-dropdown`.  
- Use `popper-options` attribute

```
<el-dropdown :popper-options="{offset: [100, 200]}">
```

### What is Expected?

In this example, I would expect to have an offset.

### What is actually happening?

No offset.

### Additional comments

_(empty)_

**Comment by Karolis-Stoncius** [comment]
@amaury-hanser I'm facing the same problem, have you found a solution?

**Comment by amaury-hanser** [comment]
No, we hoped for this issue to gain more traction but it didn't and I didn't have time to check it out myself, sorry.

**Comment by Karolis-Stoncius** [comment]
Managed to solve it if you still need it - `<el-dropdown :popper-options="{modifiers: [{name:'offset', options: {offset: [100,200] }}]}">`
