### ISSUE TITLE
[Bug Report] tabs 切换name类型问题

### ISSUE THREAD

**Issue by Capyhw** [element-plus/element-plus#8466]
### Element Plus version
2.2.6

### OS/Browsers version
win11 

### Vue version
3.2.37

### Reproduction Link
https://codesandbox.io/embed/element-plus-spa-forked-s1j2mf?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
初始化点击第一个是number
切换到其他的再点第一个就变string了

### What is Expected?
无论什么时候都应该是number

### What is actually happening?
初始化点击第一个是number
切换到其他的再点第一个就变string了

**Comment by tolking** [comment]
This fix in #8469, You can upgrade element-plus version to 2.2.8.
