### ISSUE TITLE
Table [Vue warn]: setup() return property "$index" should not start with "$" or "_" which are reserved prefixes for Vue internals. 

### ISSUE THREAD

**Issue by lqsong** [element-plus/element-plus#847]
`1.0.1-beta.4`

> Table [Vue warn]: setup() return property "$index" should not start with "$" or "_" which are reserved prefixes for Vue internals. 

![image](https://user-images.githubusercontent.com/22975974/101236093-4104d080-3709-11eb-88de-77d97fb14cfd.png)

**Comment by JeremyWuuuuu** [comment]
Please submitting issues with demo code or reproducible repo or link, we cannot resolve the issue with nothing.

**Comment by lqsong** [comment]
> Please submitting issues with demo code or reproducible repo or link, we cannot resolve the issue with nothing.

`1.0.1-beta.4`

https://github.com/element-plus/element-plus/blob/dev/packages/table/src/table-column/index.ts#L93

https://github.com/element-plus/element-plus/blob/dev/packages/table/src/table-column/index.ts#L208

https://github.com/element-plus/element-plus/blob/dev/packages/table/src/table-column/index.ts#L221

![image](https://user-images.githubusercontent.com/22975974/101274229-46305100-37d7-11eb-81f9-d793ea9bec83.png)

> **"$" or "_" which are reserved prefixes for Vue internals**

**Comment by justwiner** [comment]
will fix soon in next release.

https://github.com/justwiner/element-plus/blob/e88bfbbba429f91f03e18301fb8db59cdccea761/packages/table/src/table-column/index.ts#L202
