### ISSUE TITLE
[Component] [upload] ElUpload拖拽文件没有反应（不触发上传等事件）

### ISSUE THREAD

**Issue by saatana97** [element-plus/element-plus#8490]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `chrome 102.0.5005.115（正式版本） （64 位）`
- Build Tool: `Webpack`

### Related Component

- `el-upload`

### Reproduction Link

[CodePen](https://codepen.io/sumy7/pen/RwZmpOx)

### Steps to reproduce

拖拽文件到组件里

### What is Expected?

执行各种钩子，开始上传

### What is actually happening?

没有反应

### Additional comments

_(empty)_

**Comment by LinZhanMing** [comment]
maybe you should use property **auto-upload**

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgZHJhZ1xuICAgIGFjdGlvbj1cImh0dHBzOi8vcnVuLm1vY2t5LmlvL3YzLzlkMDU5YmY5LTQ2NjAtNDVmMi05MjVkLWNlODBhZDZjNGQxNVwiXG4gICAgbXVsdGlwbGVcbiAgICBhdXRvLXVwbG9hZFxuICA+XG4gICAgPGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS11cGxvYWRcIj48dXBsb2FkLWZpbGxlZCAvPjwvZWwtaWNvbj5cbiAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190ZXh0XCI+XG4gICAgICBEcm9wIGZpbGUgaGVyZSBvciA8ZW0+Y2xpY2sgdG8gdXBsb2FkPC9lbT5cbiAgICA8L2Rpdj5cbiAgICA8dGVtcGxhdGUgI3RpcD5cbiAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RpcFwiPlxuICAgICAgICBqcGcvcG5nIGZpbGVzIHdpdGggYSBzaXplIGxlc3MgdGhhbiA1MDBrYlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgVXBsb2FkRmlsbGVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Cheerwhy** [comment]
did u set accept arrtibute?
remove it

**Comment by saatana97** [comment]
> did u set accept arrtibute? remove it

yes I did,I set accept with '*.*',click to pick any file worked,but drag don't work.
I set accept to empty string resolved this problem,thanks

**Comment by ZTrainWilliams** [comment]
我是设置了accept，点击上传可以触发beforeUpload， 拖拽无法触发

**Comment by VegetableChicken1024** [comment]
> 

你最后怎么解决的，我也是拖拽上传无法触发beforeUpload

**Comment by muyiyl** [comment]
是设计如此吗 还是会修复此问题？
