### ISSUE TITLE
[Component] [date-picker] DatePicker 在默认空值的时候 选择非本月日期会出现问题

### ISSUE THREAD

**Issue by steavengong** [element-plus/element-plus#8494]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E7%82%B9)

### Steps to reproduce

官网下 demo
当值为空的时候 选择非当前月日会出现选择错误问题

     

### What is Expected?

当值为空的时候
当前是2022/6/27 选择非当前月的日期 
如选择5月31日应该还是5月31
如选择7月1日应该还是7月1

### What is actually happening?

当值为空的时候 
当前是2022/6/27 选择非当前月的日期 
如选择5月31日会变成2022-04-26
如选择7月1日会变成2022-7-29

### Additional comments

官网下 demo 直接可以尝试

https://user-images.githubusercontent.com/10862092/175909011-f1da2c9a-d3c7-495e-8886-b17531dd040b.mp4

**Comment by KimYangOfCat** [comment]
duplicate of #8489
