### ISSUE TITLE
[Component] [tree-select] el-select-tree回显错误

### ISSUE THREAD

**Issue by weiquanju** [element-plus/element-plus#8495]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chromium 102.0.5005.115`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgbGF6eSA6bG9hZD1cImxvYWRcIiA6cHJvcHM9XCJwcm9wc1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZig1KVxuXG5jb25zdCBwcm9wcyA9IHtcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBpc0xlYWY6ICdpc0xlYWYnLFxufVxuXG5sZXQgaWQgPSAwXG5cbmNvbnN0IGxvYWQgPSAobm9kZSwgcmVzb2x2ZSkgPT4ge1xuICBpZiAobm9kZS5pc0xlYWYpIHJldHVybiByZXNvbHZlKFtdKVxuXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIHJlc29sdmUoW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogKytpZCxcbiAgICAgICAgbGFiZWw6IGBsYXp5IGxvYWQgbm9kZSR7aWR9YCxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiArK2lkLFxuICAgICAgICBsYWJlbDogYGxhenkgbG9hZCBub2RlJHtpZH1gLFxuICAgICAgICBpc0xlYWY6IHRydWUsXG4gICAgICB9LFxuICAgIF0pXG4gIH0sIDQwMClcbn1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

现代浏览器种打开复现环境链接

### What is Expected?

el-select-tree组件回显`lazy load node5`

### What is actually happening?

el-select-tree组件回显`5`

### Additional comments

default-expand-all属性加上后会正常回显，`default-expanded-keys`  `default-checked-keys` 属性测试也无效

**Comment by weiquanju** [comment]
能不能把el-select组件里面的setSelected方法暴露出来呢？

**Comment by yaolunmao** [comment]
我也遇到这个问题了，只要是设置了:props="defaultProps" 多级嵌套的回显就是value，而不是label，两层是正常的，第三层开始就有问题了

**Comment by yujinpan** [comment]
懒加载时 `default-expanded-keys` 需要匹配当前勾选节点的所有父级节点，否则无法找到所在层级。

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgbGF6eSA6bG9hZD1cImxvYWRcIiA6cHJvcHM9XCJwcm9wc1wiIDpkZWZhdWx0LWV4cGFuZGVkLWtleXM9WzEsM10gLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDUpXG5cbmNvbnN0IHByb3BzID0ge1xuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGlzTGVhZjogJ2lzTGVhZicsXG59XG5cbmxldCBpZCA9IDBcblxuY29uc3QgbG9hZCA9IChub2RlLCByZXNvbHZlKSA9PiB7XG4gIGlmIChub2RlLmlzTGVhZikgcmV0dXJuIHJlc29sdmUoW10pXG5cbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgcmVzb2x2ZShbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiArK2lkLFxuICAgICAgICBsYWJlbDogYGxhenkgbG9hZCBub2RlJHtpZH1gLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICsraWQsXG4gICAgICAgIGxhYmVsOiBgbGF6eSBsb2FkIG5vZGUke2lkfWAsXG4gICAgICAgIGlzTGVhZjogdHJ1ZSxcbiAgICAgIH0sXG4gICAgXSlcbiAgfSwgNDAwKVxufVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319) 中将 `:default-expanded-keys=[1,3]` 即可正常显示。

**Comment by yujinpan** [comment]
Problem to be optimized:

- [ ] Provides an alternative name configuration for lazy loading
- [ ] Display the name even if it is not rendered when not lazy loaded

**Comment by LIUSHUAI2018** [comment]
这个问题即使不是懒加载也会出现，希望可以及时处理

**Comment by weiquanju** [comment]
> 这个问题即使不是懒加载也会出现，希望可以及时处理

https://github.com/element-plus/element-plus/issues/8495#issuecomment-1178617876

上面这个回答可以解决这个问题 😊

**Comment by LIUSHUAI2018** [comment]
> 
好的,我试一下
