### ISSUE TITLE
[Select]Select 组件没有实现 focus() 方法使 input 获取焦点

### ISSUE THREAD

**Issue by smileShirmy** [element-plus/element-plus#850]
原 element-ui 以及现在的 element-plus 的 Select 组件文档都有 `focus()` 方法，并且 element-ui 也实现了这个方法，现在尝试升级到 element-plus 之后报该方法 `undefined` 的错误。

**Comment by JeremyWuuuuu** [comment]
Sorry, we still need you to provide a workable demo code or online editor for this

**Comment by smileShirmy** [comment]
version: 
"vue": "^3.0.0",
"element-plus": "^1.0.1-beta.4",

```vue
<template>
  <el-select ref="select"></el-select>
</template>

<script>
import { ElSelect } from 'element-plus'

export default {
  components: {
    ElSelect
  },
  mounted() {
    console.log(typeof this.$refs.select.focus) // => undefined
  }
}
</script>

```

**Comment by smileShirmy** [comment]
> Sorry, we still need you to provide a workable demo code or online editor for this

**Comment by zazzaz** [comment]
```
element-ui/src/mixins/focus.js
```

missing focus method
