### ISSUE TITLE
[Component] [time-picker] el-time-picker 在 is-range 为 true 的情况下，仅修改结束时间（End Time）后点击确认按钮，无法触发 change 事件

### ISSUE THREAD

**Issue by colive-v** [element-plus/element-plus#8501]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome/102.0.0.0 / Windows NT 10.0`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1yYW5nZVwiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBpcy1yYW5nZVxuICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCB0aW1lXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgIEBjaGFuZ2U9XCJsb2dUZXN0XCJcbiAgICAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbbmV3IERhdGUoMjAxNiwgOSwgMTAsIDgsIDQwKSwgbmV3IERhdGUoMjAxNiwgOSwgMTAsIDksIDQwKV0pXG5jb25zdCBsb2dUZXN0ID0gKCkgPT4ge2NvbnNvbGUubG9nKCdhYWFhJyl9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmRlbW8tcmFuZ2UgLmVsLWRhdGUtZWRpdG9yIHtcbiAgbWFyZ2luOiA4cHg7XG59XG5cbi5kZW1vLXJhbmdlIC5lbC1yYW5nZS1zZXBhcmF0b3Ige1xuICBib3gtc2l6aW5nOiBjb250ZW50LWJveDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、点击 el-time-picker 组件
2、切换右侧的结束时间
3、点击确认按钮，发现 change 事件没有被触发

### What is Expected?

正常触发 change 事件

### What is actually happening?

未能成功触发 change 事件

### Additional comments

_(empty)_

**Comment by holazz** [comment]
Fixed by #9669
