### ISSUE TITLE
[Component] [input] component动态加载el组件无效

### ISSUE THREAD

**Issue by fangyu456** [element-plus/element-plus#8512]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXHQ8Y29tcG9uZW50IGlzPVwiZWwtaW5wdXRcIiAvPlxuXHQ8Y29tcG9uZW50IGlzPVwiaW5wdXRcIiAvPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

没有

### What is Expected?

为什么 
自动导入无效
component :is=el-xxx无效
component :is=input 原生input有效
手动按需导入
component :is=el-xxx有效
component :is=input 原生input有效

### What is actually happening?

为什么 
自动导入无效
component :is=el-xxx无效
component :is=input 原生input有效
手动按需导入
component :is=el-xxx有效
component :is=input 原生input有效

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Hello, this issue may be reported to the plugin library first.

**Comment by XtremeKevinChow** [comment]
我也遇到了这个问题，估摸着应该不是BUG，应该是自动导入机制的问题，我通过以下方法解决，可以试一试
`
const is = computed(() => {
  const elementTypeMap = {
    'el-input': ElInput,
    'el-select': ElSelect,
    'el-checkbox': ElCheckbox,
    'el-date-picker': ElDatePicker
  };

  // 默认 input 控件
  let type = 'el-input';

  // 其他控件判断逻辑

  return elementTypeMap[type];
});
`

**Comment by xiaoxian521** [comment]
> 我也遇到了这个问题，估摸着应该不是BUG，应该是自动导入机制的问题，我通过以下方法解决，可以试一试
> 
> ```
> const is = computed(() => {
>   const elementTypeMap = {
>     'el-input': ElInput,
>     'el-select': ElSelect,
>     'el-checkbox': ElCheckbox,
>     'el-date-picker': ElDatePicker
>   };
> 
>   // 默认 input 控件
>   let type = 'el-input';
> 
>   // 其他控件判断逻辑
> 
>   return elementTypeMap[type];
> });
> ```

i think so

**Comment by wffchong** [comment]
不知道为啥哇

**Comment by xiangshu233** [comment]
> 我也遇到了这个问题，估摸着应该不是BUG，应该是自动导入机制的问题，我通过以下方法解决，可以试一试
> 
> ```
> const is = computed(() => {
>   const elementTypeMap = {
>     'el-input': ElInput,
>     'el-select': ElSelect,
>     'el-checkbox': ElCheckbox,
>     'el-date-picker': ElDatePicker
>   };
> 
>   // 默认 input 控件
>   let type = 'el-input';
> 
>   // 其他控件判断逻辑
> 
>   return elementTypeMap[type];
> });
> ```
请问我的组件是按需加载的 然后按照0这个方式为什么还是加载不出来

```vue
          <component
            :is="is(item)"
            v-bind="item.attrs"
            v-model="formSchema.formModel[item.formItem.prop]"
            v-on="item.events"
          >
            <template v-if="item.attrs.typeName === 'select'">
              <el-option
                v-for="subitem in item.attrs.options"
                :key="subitem.value"
                :label="subitem.label"
                :value="subitem.value"
              />
            </template>
          </component>
```
```ts
const elementTypeMap = {
  'input': ElInput,
  'select': ElSelect,
  'checkbox': ElCheckbox,
  'date-picker': ElDatePicker,
}

const is = computed((item) => {
  // 默认 input 控件
  const type = item.attrs.typeName || 'input'
  return elementTypeMap[type]
})
```

**Comment by XtremeKevinChow** [comment]
> > 我也遇到了这个问题，估摸着应该不是BUG，应该是自动导入机制的问题，我通过以下方法解决，可以试一试
> > ```
> > const is = computed(() => {
> >   const elementTypeMap = {
> >     'el-input': ElInput,
> >     'el-select': ElSelect,
> >     'el-checkbox': ElCheckbox,
> >     'el-date-picker': ElDatePicker
> >   };
> > 
> >   // 默认 input 控件
> >   let type = 'el-input';
> > 
> >   // 其他控件判断逻辑
> > 
> >   return elementTypeMap[type];
> > });
> > ```
> 
> 请问我的组件是按需加载的 然后按照0这个方式为什么还是加载不出来
> 
> ```
>           <component
>             :is="is(item)"
>             v-bind="item.attrs"
>             v-model="formSchema.formModel[item.formItem.prop]"
>             v-on="item.events"
>           >
>             <template v-if="item.attrs.typeName === 'select'">
>               <el-option
>                 v-for="subitem in item.attrs.options"
>                 :key="subitem.value"
>                 :label="subitem.label"
>                 :value="subitem.value"
>               />
>             </template>
>           </component>
> ```
> 
> ```ts
> const elementTypeMap = {
>   'input': ElInput,
>   'select': ElSelect,
>   'checkbox': ElCheckbox,
>   'date-picker': ElDatePicker,
> }
> 
> const is = computed((item) => {
>   // 默认 input 控件
>   const type = item.attrs.typeName || 'input'
>   return elementTypeMap[type]
> })
> ```

确认下 return elementTypeMap[type] 是否返回正确的类型，F12中是否有异常信息。如果还不行，可以另开一个页面单独写个 component 试试
