### ISSUE TITLE
[Component] [table-column, table] 使用 v-for 循环生成列，在 el-table-column 组件加上 key属性时，无法修改列的顺序

### ISSUE THREAD

**Issue by shibin-cli** [element-plus/element-plus#8528]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/shibin-cli/pen/yLKLxgG)

### Steps to reproduce

点击按钮 change columns order  后，table 列的顺序没有改变
* 给一个 columns 数组用来表示 table 的列，v-for 来 循环el-table-column，通过调整columns 数组的顺序来改变列的顺序
* 当没有给 el-table-column 组件加上 key属性时，修改columns时，列的顺序是可以改变的
* 给 el-table-column 组件加上key 属性时，修改columns时，列的顺序没法改变

### What is Expected?

 el-table-column 组件加上key 属性时，table 列的顺序可以改变

### What is actually happening?

 el-table-column 组件加上key 属性时，table 列的顺序没办法改变

### Additional comments

_(empty)_

**Comment by L1yp** [comment]
感觉需要给el-table加key 让table重新刷新

**Comment by norangit** [comment]
没看源码，你可以换个key就可以了：
···
<el-table-column v-for="(item,idx) in columns" :prop="item.prop" :label="item.label" :key="'kk' + idx"
              :width="item.width">
            </el-table-column>
···

**Comment by shibin-cli** [comment]
为什么要使用 索引值作为key 使用呢？这样做就是 在v-for循环中使用index作为索引值，vue 会抛出警告

**Comment by user93107** [comment]
确实有这个问题，暂时只能用index代替了

**Comment by zedream** [comment]
天哪 我也遇到这个问题了   求解决！！

**Comment by L1yp** [comment]
> 

table的问题没有人解决的 维护者在搞v2

**Comment by L1yp** [comment]
> 天哪 我也遇到这个问题了 求解决！！

我建议你直接刷新el-table 刷新列头之后 直接更新el-table的key 强制渲染el-table
