### ISSUE TITLE
DateTimePicker中的TimePIcker无法正常滑动

### ISSUE THREAD

**Issue by BeADre** [element-plus/element-plus#853]
使用鼠标滚动条滑动或者macbook触控板轻微滑动时无法正常滑动
![image](https://user-images.githubusercontent.com/34639100/101247686-e180e200-3755-11eb-91ac-5984ed3445e2.png)

**Comment by zazzaz** [comment]
It seems working fine on my browser?

**Comment by BeADre** [comment]
I think I need someone else to give it a try because I have reproduced this problem on different devices

**Comment by g3r4n** [comment]
@BeADre What's the issue ? I can't read Chinese.

**Comment by JeremyWuuuuu** [comment]
> @BeADre What's the issue ? I can't read Chinese.

使用鼠标滚动条滑动或者macbook触控板轻微滑动时无法正常滑动 

Translation:

Using mouse scrolling or trackpad touching with slightly movement, it can not be scrolled. Means something is wrong with the scrollbar calculation

**Comment by JeremyWuuuuu** [comment]
I myself somehow can verify this on my machine with slightly scrolling you can see this:
![image](https://user-images.githubusercontent.com/15975785/101270209-e7a4ac00-37b1-11eb-9d8a-7fb71c49b2a5.png)
It stick at the middle point without going up nor down.

**Comment by BeADre** [comment]
@JeremyWuuuuu  this problem was found in **DateTimePicker**, not TimePIcker

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu this problem was found in **DateTimePicker**, not TimePIcker

Doesn't matter, they are both using the same component

**Comment by BeADre** [comment]
I can scroll in TimePicker, but not in DateTimePicker

**Comment by JeremyWuuuuu** [comment]
> I can scroll in TimePicker, but not in DateTimePicker

Got it, verified as well, I cannot scroll https://element-plus.org/#/en-US/component/datetime-picker with slow pace, I was only be able to scroll the picker with a fast pace on the track pad, which means I have to swipe my fingers very fast or a long distant swipe.

**Comment by lujiaming1** [comment]
it's fine in my chrome ....

**Comment by Bo-LiangD** [comment]
It is found that the 'DateTimePicker' component in the Element-Plus website cannot slide, but there is no problem in element-UI

em em em
