### ISSUE TITLE
[All] Code analysis / Notices

### ISSUE THREAD

**Issue by mavlutovr** [element-plus/element-plus#8536]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.5`
- Browser / OS: `Ubuntu 20.04.4 LTS`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxwPlxuICAgPGltZyBzcmM9XCJodHRwczovL2kuaW1ndXIuY29tLzJRbWNXNGsucG5nXCIgc3R5bGU9XCJtYXgtd2lkdGg6MTAwJTtcIiAvPlxuICA8L3A+XG4gIDxoMT5cbiAgICA8YSBocmVmPVwiaHR0cHM6Ly9pLmltZ3VyLmNvbS8yUW1jVzRrLnBuZ1wiIHRhcmdldD1cIl9ibGFua1wiPk9wZW4gdGhlIGltYWdlIGluIG5ldyBUYWI8L2E+XG4gIDwvaDE+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Use PhpStorm

2. Add to .vue file:
```
<el-tree :check-strictly="false" />
```

3. PhpStorm underline "false" as a not appropriate type https://i.imgur.com/yWmxvtw.png

### What is Expected?

Type matching

### What is actually happening?

Some types are not matching

### Additional comments

Thanks a lot for your great framework!

**Comment by sxzz** [comment]
Suggest using VSCode and Volar, because Volar is first-class support by Vue and its related library.

**Comment by mavlutovr** [comment]
Tnanks!
