### ISSUE TITLE
[Component] [date-picker] 日期选择器

### ISSUE THREAD

**Issue by mivvm** [element-plus/element-plus#8545]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Microsoft Edge 版本 103.0.1264.37 (正式版本) (64 位)`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgZGF0ZSA9IHJlZignJylcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cdDxlbC1kYXRlLXBpY2tlclxuICAgICAgICAgIHYtbW9kZWw9XCJkYXRlXCJcbiAgICAgICAgICAgICAgICAgdHlwZT1cImRhdGVcIlxuICAgICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeaXtumXtFwiXG4gICAgICAgICAgICAgICAgICAgIHZhbHVlRm9ybWF0PVwiWVlZWS1NTS1ERFwiXG4gICAgICAgICAgICAgICAgICAgIC8+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

日期选择器，今天是6月30，现在选择当前界面的7月1日，会跳转到7月29,会报错

### What is Expected?

选择为7月1日

### What is actually happening?

7月29

### Additional comments

_(empty)_

**Comment by xxred** [comment]
刚想看看有没有人发现这个问题，就有人大佬提了。月底这几天，选择跨月的日期，控制台会报错 `Maximum call stack size exceeded`。报错的是popper组件的content.vue，有相关[pull](https://github.com/element-plus/element-plus/pull/8218)提到过，不知跟此问题是否有关。
