### ISSUE TITLE
[Component] [switch] 首次渲染会触发change事件

### ISSUE THREAD

**Issue by sjzgit** [element-plus/element-plus#8553]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.5`
- Browser / OS: `chrome 100`
- Build Tool: `Vite`

### Related Component

- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc3dpdGNoIHYtbW9kZWw9XCJ2YWx1ZTFcIiA6YWN0aXZlLXZhbHVlPVwiMVwiIDppbmFjdGl2ZS12YWx1ZT1cIjBcIiBAY2hhbmdlPVwiY2hhbmdlRnVuXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5cdGNvbnN0IHZhbHVlMSA9IHJlZih1bmRlZmluZWQpXG5cblx0Y29uc3QgY2hhbmdlRnVuID0gKHZhbCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKHZhbCwgdmFsdWUxLnZhbHVlKVxuICB9XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

v-model绑定的值不是activeValue和inactiveValue其中的
就会触发一次change

### What is Expected?

首次加载不触发change

### What is actually happening?

会触发一次change

### Additional comments

看了下源码逻辑，这种情况确实会触发一次。想了解下这样设计的初衷是什么呢？

**Comment by btea** [comment]
cc @element-plus/backers

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/blob/77fa19b45a1f4be173204323b79dbff633cf4aff/packages/components/switch/src/switch.vue#L180-L184

switch 作为一个只有开关2个状态的组件，不是开就是关，组件会默认将不是开的值重置为关，认为修改这个值的行为有必要通过事件反馈给外部。

**Comment by sjzgit** [comment]
> https://github.com/element-plus/element-plus/blob/77fa19b45a1f4be173204323b79dbff633cf4aff/packages/components/switch/src/switch.vue#L180-L184
> 
> switch 作为一个只有开关2个状态的组件，不是开就是关，组件会默认将不是开的值重置为关，认为修改这个值的行为有必要通过事件反馈给外部。

好吧，就是看了源码发现代码逻辑是这样
