### ISSUE TITLE
[Component] [date-picker] 日期组件bug,日期下拉框在不切换月份时，第一次选中灰色下个月任意日期时，日期对应不上，选中框中显示的是这个灰色月末日期，切换下月份在选择后又正常了

### ISSUE THREAD

**Issue by gracewo** [element-plus/element-plus#8559]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html#选择某一天)

### Steps to reproduce

日期下拉框在不切换月份时，第一次选中灰色下个月任意日期时，日期对应不上，选中框中显示的是这个灰色月末日期（比如我选中灰色下个月1号选中框中显示30号），切换下月份在选择后又正常了

### What is Expected?

第一次选中灰色显示对应日期

### What is actually happening?

第一次选中灰色显示对应日期

### Additional comments

_(empty)_

**Comment by Julone** [comment]
一样的, 希望官方能修复一下, 用户很容易误解.
