### ISSUE TITLE
Non-props passing attributes issue in el-drawer

### ISSUE THREAD

**Issue by PavelJland** [element-plus/element-plus#856]
```
<template lang="pug">
.wrap
  el-button.no-radius(@click="drawer = !drawer") Login
  el-drawer(title="I am the title"
    :visible.sync="drawer"
    :with-header="false") User
</template>
```

```js
  data() {
    return {
      drawer: false,
    }
  }
```

`[Vue warn]: Extraneous non-props attributes (visible) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.`

And the drawer is not working!!!!!!!!!!!!!!! because of it.

Vue - vue@3.0.0-rc.13

**Comment by JeremyWuuuuu** [comment]
@PavelJland Friendly reminder, since `Vue` itself removed the `.sync` modifier, we now use `v-model` as the control flag of visibility. Please use `v-model="visibleBinding"` to control that. Also I think you might need to upgrade your `Vue` version to the official builds, which is `^3.0.4`

**Comment by JeremyWuuuuu** [comment]
So to wrap it up, you need to use like this to make it work

```vue

<template lang="pug">
.wrap
  el-button.no-radius(@click="drawer = !drawer") Login
  el-drawer(title="I am the title"
    v-model="drawer"
    :with-header="false") User
</template>

```

**Comment by JeremyWuuuuu** [comment]
The doc site will be updated soon with the next release
