### ISSUE TITLE
[Component] [time-picker] when timepicker type is "is-range" and "disabled-hours" exist,timepicker cannot be emptied

### ISSUE THREAD

**Issue by HoneKKK** [element-plus/element-plus#8569]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1iYXNpY1wiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgIGlzLXJhbmdlXG4gICAgICA6ZGlzYWJsZWQtaG91cnM9XCJkaXNhYmxlZEhvdXJzXCJcbiAgICAgIDpkaXNhYmxlZC1taW51dGVzPVwiZGlzYWJsZWRNaW51dGVzXCJcbiAgICAgIDpkaXNhYmxlZC1zZWNvbmRzPVwiZGlzYWJsZWRTZWNvbmRzXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQXJiaXRyYXJ5IHRpbWVcIlxuICAgIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFtdKVxuXG5jb25zdCBtYWtlUmFuZ2UgPSAoc3RhcnQ6IG51bWJlciwgZW5kOiBudW1iZXIpID0+IHtcbiAgY29uc3QgcmVzdWx0OiBudW1iZXJbXSA9IFtdXG4gIGZvciAobGV0IGkgPSBzdGFydDsgaSA8PSBlbmQ7IGkrKykge1xuICAgIHJlc3VsdC5wdXNoKGkpXG4gIH1cbiAgcmV0dXJuIHJlc3VsdFxufVxuY29uc3QgZGlzYWJsZWRIb3VycyA9ICgpID0+IHtcbiAgcmV0dXJuIG1ha2VSYW5nZSgwLCAxNikuY29uY2F0KG1ha2VSYW5nZSgxOSwgMjMpKVxufVxuY29uc3QgZGlzYWJsZWRNaW51dGVzID0gKGhvdXI6IG51bWJlcikgPT4ge1xuICBpZiAoaG91ciA9PT0gMTcpIHtcbiAgICByZXR1cm4gbWFrZVJhbmdlKDAsIDI5KVxuICB9XG4gIGlmIChob3VyID09PSAxOCkge1xuICAgIHJldHVybiBtYWtlUmFuZ2UoMzEsIDU5KVxuICB9XG59XG5jb25zdCBkaXNhYmxlZFNlY29uZHMgPSAoaG91cjogbnVtYmVyLCBtaW51dGU6IG51bWJlcikgPT4ge1xuICBpZiAoaG91ciA9PT0gMTggJiYgbWludXRlID09PSAzMCkge1xuICAgIHJldHVybiBtYWtlUmFuZ2UoMSwgNTkpXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZXhhbXBsZS1iYXNpYyAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW46IDhweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.set timepicker type is is-range
2.set disabled-hours value
3.click the clear button

### What is Expected?

the timerpicker value should be emptied

### What is actually happening?

timepicker set its value again immediately

### Additional comments

为了避免英语较差表述不清楚。在这里用中文表述一遍。
在给timepicker设置了is-range并动态变化disalbed-hours时，点击清空按钮会设置为null，然后会立马自动进行一次赋值。导致timepicker无法被清空。

**Comment by HoneKKK** [comment]
appreciate for your reply!! It is my first request so i am not that familiar.So it is the bug or it is my problem?

**Comment by u373693041** [comment]
same question

**Comment by huangbh1024** [comment]
same question
