### ISSUE TITLE
el-cascasder  v-model default value not work

### ISSUE THREAD

**Issue by buaazs** [element-plus/element-plus#857]
template:
  `<el-cascader v-model="val"
    :options="options"
    :props="{ checkStrictly: true }"
    clearable>
  </el-cascader>
`
code in setup:
```
const val = ref(1)
 const options = [
{label: 's1', value: 1},
{label: 's2', value: 2},
]
return {val,options}
```
I tried both val = ref(1) and val = ref([1]),  the label of default value (s1) not shown in the input box.  

I also got below warning in console:
```
[Vue warn]: Extraneous non-emits event listeners (afterLeave) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 
  at <ElPopper ref="popper" visible=false onUpdate:visible=fn  ... > 
  at <ElCascader modelValue=null onUpdate:modelValue=fn options= []  
```

**Comment by JeremyWuuuuu** [comment]
The warning was reported by `Vue`, this was a bug in `Vue@3.0.3`, you can dismiss that by upgrading  to `@3.0.4` also this might introduce to another bug see https://github.com/vuejs/vue-next/issues/2737
@SimonaliaChen can you take a look at this?

**Comment by SimonaliaChen** [comment]
Hi, I wrote a [demo](https://codesandbox.io/s/cranky-mclaren-830tg?file=/src/App.vue) according to your description, but it works just fine. Could you provide a reproduction link based on my version?

**Comment by JeremyWuuuuu** [comment]
Please provide the version of `Vue` also the version of `ElementPlus`, thank you, because that we've found recent bugs reported somehow related to the change of `Vue` so we need you to be more specific.

**Comment by buaazs** [comment]
Sorry for misleading for the previous scenario.  I checked my code I found the cause maybe the options is loaded aync.
I also updated the [demo](https://codesandbox.io/s/musing-currying-5ojmr?file=/src/App.vue)
```
setup() {
    const val = ref(1);
    const options = [
      { label: "s1", value: 1 },
      { label: "s2", value: 2 },
    ];

    const optionsDefer = ref([]);
    setTimeout(() => {
      optionsDefer.value = options;
    }, 1000);
    watch(optionsDefer, (val, old) => console.log(val));  //optionsDefer value changed

    return { val, optionsDefer };
  }
```
I'm not sure if this is the recommended way, but I think the model default value is inited from url query and options is loaded async  from API is quite a common case. It's better if the component can also watch the options change and set the model value.

**Comment by SimonaliaChen** [comment]
Yes, it's a bug. I might know the reason, and I will fix it ASAP.
