### ISSUE TITLE
[Docs] [cascader] 官网不稳定，经常访问timeout

### ISSUE THREAD

**Issue by PaulMing** [element-plus/element-plus#8574]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html)

### Steps to reproduce

官网不稳定，经常访问timeout

### What is Expected?

国内cdn加速

### What is actually happening?

文档

### Additional comments

现在报错了 503
<img width="765" alt="image" src="https://user-images.githubusercontent.com/40627394/176843355-4a96cbe8-13e5-4b47-81bf-4835ce88234c.png">

**Comment by pmb2020** [comment]
表示还经常遇到404，，，，

**Comment by sxzz** [comment]
请访问主站 https://element-plus.org/ 。中文镜像为 Gitee 提供，我们也没办法。
