### ISSUE TITLE
[Component] [dropdown] visible-change event delay trigger

### ISSUE THREAD

**Issue by shooterRao** [element-plus/element-plus#8601]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome/102.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBBcnJvd0Rvd24sIEFycm93VXAgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbiAgXG5jb25zdCBkcm9wRG93blNob3cgPSByZWYoZmFsc2UpXG4gXG5jb25zdCBvbkNoYW5nZSA9ICh2YWwpID0+IHtcbiAgY29uc29sZS5sb2coJ2NoYW5nZScsIHZhbClcbiAgZHJvcERvd25TaG93LnZhbHVlID0gdmFsXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICDlm6DkuLogdmlzaWJsZS1jaGFuZ2Ug5LqL5Lu25bu26L+fIGVtaXTvvIzmiYDku6Xlr7zoh7TkuIvmi4noj5zljZXml4HovrnnmoTnrq3lpLToioLlpY/ot5/kuI3kuIrvvIxlbGVtZW50dWkyIOihqOeOsOaYr+ato+W4uOeahFxuICA8L3A+XG4gIDxlbC1kcm9wZG93biBAdmlzaWJsZS1jaGFuZ2U9XCJvbkNoYW5nZVwiPlxuICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAg5LiL5ouJ6I+c5Y2VXG4gICAgPC9zcGFuPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG4gIDxlbC1pY29uIHYtaWY9XCIhZHJvcERvd25TaG93XCI+XG4gICAgPEFycm93RG93biAvPlxuICA8L2VsLWljb24+XG4gIDxlbC1pY29uIHYtZWxzZT5cbiAgICA8QXJyb3dVcCAvPlxuICA8L2VsLWljb24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue'
import { ArrowDown, ArrowUp } from '@element-plus/icons-vue'
  
const dropDownShow = ref(false)
 
const onChange = (val) => {
  console.log('change', val)
  dropDownShow.value = val
}
</script>

<template>
  <el-dropdown @visible-change="onChange">
    <span class="el-dropdown-link">
      dropdown-list
    </span>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item>Action 1</el-dropdown-item>
        <el-dropdown-item>Action 2</el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
  <el-icon v-if="!dropDownShow">
    <ArrowDown />
  </el-icon>
  <el-icon v-else>
    <ArrowUp />
  </el-icon>
</template>

```

### What is Expected?

visible-change event can trigger immediately when the state change

### What is actually happening?

visible-change event delay trigger

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
You can set `hide-timeout` to `0`.

**Comment by chenxch** [comment]
It doesn't seem to work.

**Comment by shooterRao** [comment]
MR #8602 , it can solve this problem.

**Comment by chenxch** [comment]
Ok, the reason is that the transition animation is used, and the show/hide is triggered after the animation ends.
