### ISSUE TITLE
[Component] [input, form] form表单,:inline="true" ,el-input 属性为clearable,输入或者清空表单内容,整行表单宽度伸缩.

### ISSUE THREAD

**Issue by 18792424938** [element-plus/element-plus#8612]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`
- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiIDptb2RlbD1cImZvcm1JbmxpbmVcIiBjbGFzcz1cImRlbW8tZm9ybS1pbmxpbmVcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQXBwcm92ZWQgYnlcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZm9ybUlubGluZS51c2VyXCIgcGxhY2Vob2xkZXI9XCJBcHByb3ZlZCBieVwiIGNsZWFyYWJsZSAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIFxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib25TdWJtaXRcIj5RdWVyeTwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGZvcm1JbmxpbmUgPSByZWFjdGl2ZSh7XG4gIHVzZXI6ICcnLFxuICByZWdpb246ICcnLFxufSlcblxuY29uc3Qgb25TdWJtaXQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.输入内容
2.清空内容

### What is Expected?

输入内容表单宽度不便

### What is actually happening?

在加入clearable属性时,表单会自动增加宽度,清空表单缩减宽度

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
可以给el-input加个宽度哦
