### ISSUE TITLE
[Component]  <el-menu> mode=”horizontal“时候，点击某一菜单出现收缩/展开异常

### ISSUE THREAD

**Issue by sunjiesama** [element-plus/element-plus#8614]
el-menu 收缩/展开的bug

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`
- `el-menu-item-group`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/menu.html#%E9%A1%B6%E6%A0%8F)

### Steps to reproduce

mode="horizontal"时，点击某一个下拉项，菜单样式异常，官方文档的第一个demo即可复现

### What is Expected?

菜单正常的收缩/展开

### What is actually happening?

菜单异常

### Additional comments

之前提的issue被关闭了，但是到文档demo看了下，问题依然存在

![GIF 2022-7-4 15-03-49](https://user-images.githubusercontent.com/54022918/177099982-fecffd19-536d-42c1-99a9-cea17659159a.gif)

**Comment by ryuhangyeong** [comment]
fixed https://github.com/element-plus/element-plus/pull/8533

it will probably be released in the next release.
