### ISSUE TITLE
[Feature Request] 文档服务器慢的跟屎一样  这么大一个项目连个服务器都租不起吗

### ISSUE THREAD

**Issue by 837633678** [element-plus/element-plus#8615]
Feature type: **`New Component`**

## Details

- New component name: `1`

## Description

文档服务器慢的跟屎一样  这么大一个项目连个服务器都租不起吗
### Additional comments

_(empty)_

文档服务器慢的跟屎一样  这么大一个项目连个服务器都租不起吗

**Comment by see** [comment]
你没挂梯子吧

**Comment by 0song** [comment]
国内加速镜像: https://element-plus.gitee.io/zh-CN/
