### ISSUE TITLE
[Style] [select-v2] [Bug Report] [Component] [select-v2] 多选且collapse-tags模式下，宽度不够时，内容框被撑开两行且选中的tag超出内容框

### ISSUE THREAD

**Issue by JimSuen** [element-plus/element-plus#8619]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Version 103.0.5060.66 (Official Build) (64-bit)`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzZWxlY3RlZFZhbHVlID0gcmVmPHN0cmluZz4oJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICcxMTExMTExMTExMTExMTExMTExMScsXG4gICAgbGFiZWw6ICcxMTExMTExMTExMTExMTExMTExMSdcbiAgfSxcbiAgICB7XG4gICAgdmFsdWU6ICcyMjIyMjIyMjIyMjIyMjIyMjIyJyxcbiAgICBsYWJlbDogJzIyMjIyMjIyMjIyMjIyMjIyMjInXG4gIH0sXG4gICAge1xuICAgIHZhbHVlOiAnMzMzMzMzMzMzMzMzMzMzMzMzMzMzMycsXG4gICAgbGFiZWw6ICczMzMzMzMzMzMzMzMzMzMzMzMzMzMzJ1xuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJzZWxlY3RlZFZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIGZpbHRlcmFibGVcbiAgICBtdWx0aXBsZVxuICAgIGNvbGxhcHNlLXRhZ3NcbiAgICBzdHlsZT1cIndpZHRoOiAxMDBweFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```
  <el-select-v2
    v-model="selectValue"
    filterable
    multiple
    collapse-tags
    :options="columnValues"
    placeholder="Please select"
    style="width: 100px"
   
  />
```

### What is Expected?

希望：
1. 完成选择后，select区域显示成1行(隐藏.el-select-v2__input-wrap)，
聚焦select后，可重新显示.el-select-v2__input-wrap

2. 优化选项tags超出输入框的样式

### What is actually happening?

输入框宽度不够的情况下，
问题一： 选择两个以上的选项并失焦select，'.el-select-v2__input-wrap'节点会导致内容区域换行，且失焦后也不恢复为1行。

问题二： 选项tags超出输入框内容。

### Additional comments

_(empty)_

**Comment by omegaicon** [comment]
这个还有点问题。当可多选，只选了一个比较长的选项，会撑出多余的空白行
