### ISSUE TITLE
[Style] [input, select] [Bug Report] [Style] [input, select] 升级到2.2.0版本后输入框类型的组件样式异常，出现双层边框

### ISSUE THREAD

**Issue by JimSuen** [element-plus/element-plus#8620]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Version 103.0.5060.66 (Official Build) (64-bit)`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgPjwvZWwtaW5wdXQ+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

类似这个问题[#7605](https://github.com/element-plus/element-plus/issues/7605)。

从`^1.1.0-beta.24`版本升级到`2.2.8`版本后，项目中所有的 `el-input` 和 `el-select` 变成了双边框。如图：
![](https://cdn.jsdelivr.net/gh/JimSuen/picture-library@master/issue/el-input.png)

`Element Plus Playground` 中未复现

### What is Expected?

输入框样式是正常的

### What is actually happening?

升级版本，输入框样式异常

### Additional comments

`el-select-v2` 和 `el-date-picker` 样式正常。

**Comment by chenxch** [comment]
尝试删除node_modules/.vite这个文件夹再启动看下

**Comment by JimSuen** [comment]
> 

顺着您的思路，确实是依赖重复导致的，感谢解惑。
只是不是因为/.vite , 而是项目中使用了一个外部项目的dist包，该外部项目的组件是element-plus早期版本。

所以项目中就存在了两套element-plus的两个版本样式，顺便请教一下这种情况，如何处理两套element-plus的版本不一致问题呢？

**Comment by chenxch** [comment]
可以尝试下自定义命名空间哦

**Comment by JimSuen** [comment]
其他问题，非组件库bug
