### ISSUE TITLE
[Component] [date-picker] el-date-picker组件在设置type为"datetimerange"，修改日期input框会联动修改range另一个日期

### ISSUE THREAD

**Issue by guoyichenn** [element-plus/element-plus#8639]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 103.0.5060.53/ Mac OS 11.6.4 `
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHZhbHVlMSA9IHJlZihbIDE2MzMwMTc2MDAwMDAsIDE2NzI0MTYwMDAwMDAgXSlcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgIHR5cGU9XCJkYXRldGltZXJhbmdlXCJcbiAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgICBlbmQtcGxhY2Vob2xkZXI9XCJFbmQgZGF0ZVwiXG4gICAgICB2YWx1ZS1mb21hcnQ9XCJ4XCJcbiAgICAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击date-picker组件进行修改
修改开始时间日期input框中的日期到 2020-10-01

### What is Expected?

结束时间日期仍然保持为 2022-12-31

### What is actually happening?

结束时间日期为 2020-11-01

### Additional comments

_(empty)_

**Comment by lqr5678** [comment]
希望官方尽快修复， 此问题element就不存在（只在element-plus中存在）

**Comment by guoyichenn** [comment]
@lqr5678 我解决了这个问题
我发现el-date-picker有一个属性
`unlink-panels`
可以取消两个日期选择的关联
但是为什么默认不设置为true
不知道element plus 设置默认为false的意图是什么
