### ISSUE TITLE
[Component] [select] el-select使用 filterable 和 multiple时，点击select中输入框，会发现下拉框收起并且输入框失焦

### ISSUE THREAD

**Issue by tspt** [element-plus/element-plus#8640]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJDaG9vc2UgdGFncyBmb3IgeW91ciBhcnRpY2xlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnTGVzcycsXG4gICAgbGFiZWw6ICdMZXNzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnU2NzcycsXG4gICAgbGFiZWw6ICdTY3NzJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnU2FzcycsXG4gICAgbGFiZWw6ICdTYXNzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

任意选择一个下拉选项，然后点击select中的输入框去输入，发现此时下拉框收起并且输入框失焦

### What is Expected?

下拉框不收起并且输入框聚焦

### What is actually happening?

下拉框收起并且输入框失焦

### Additional comments

_(empty)_

**Comment by c1wren** [comment]
This is fixed in 2.2.11

**Comment by Trojan0523** [comment]
@c1wren 2.2.11 maybe not fixed that problem

**Comment by kooriookami** [comment]
Fixed
