### ISSUE TITLE
[Component] [radio] el-radio无法绑定自定义属性

### ISSUE THREAD

**Issue by hzf-666** [element-plus/element-plus#8641]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `el-radio`

### Reproduction Link

[CodePen](https://codepen.io/hzf-666/pen/dymYJEo)

### Steps to reproduce

1.打开链接
2.打开控制台
3.查看radio元素的属性，发现没有绑定上自定义属性（只能绑定style和class）

### What is Expected?

可以绑定自定义属性

### What is actually happening?

无法绑定自定义属性

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
其他属性目前是被转移到了input上了哦

**Comment by hzf-666** [comment]
为什么要做这样的更改呢？有可能改回来吗？

**Comment by hzf-666** [comment]
> 其他属性目前是被转移到了input上了哦


为什么要做这样的更改呢？有可能改回来吗？

**Comment by chenxch** [comment]
原先是应为label for和id的联动问题做的调整，这个目前还在讨论中哦

**Comment by chenxch** [comment]
#8677
