### ISSUE TITLE
[i18n] [All] 打包后不支持外部国际化

### ISSUE THREAD

**Issue by zz541843** [element-plus/element-plus#8644]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: ` Chrome/101.0.4951.54`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link]()

### Steps to reproduce

1.新起一个项目，使用一个可国际化的el组件，未配置国际化，此时是英文，然后通过vite打包
2.新起第二个项目，引入上面封装的el组件，这个项目中无论怎么配置国际化，只影响该项目新写的el组件，不会影响上面引入封装的el组件

### What is Expected?

国际化正常

### What is actually happening?

国际化不正常

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
是不是要把第一个项目上面的国际化处理好

**Comment by zz541843** [comment]
> 是不是要把第一个项目上面的国际化处理好

理论上是这样的，但这样的话上每个组件都要包一层ElConfigProvider，太冗余了...，想看看有没有更好的办法

**Comment by tolking** [comment]
不会出现这个问题吧，我封装的组件都没有遇到这个问题

**Comment by zz541843** [comment]
> 不会出现这个问题吧，我封装的组件都没有遇到这个问题

你指的是在同一个库里封装组件直接使用，还是指封装组件后上传npm在引入使用？

**Comment by zz541843** [comment]
@tolking  https://github.com/zz541843/el-pack-i18n-issuse

**Comment by zz541843** [comment]
> [element-pro-components](https://github.com/tolking/element-pro-components)

我新起了一个仓库，复现了这个问题

**Comment by tolking** [comment]
你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文

**Comment by zz541843** [comment]
> 你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文 [DEMO](https://stackblitz.com/edit/github-vewuqb?file=vite.config.ts)

破案了！
将ep排除打包在这个demo里确实有效，但是在我实际项目里还是没用，经过仔细排查对照，因为我使用了[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)自动导入，<script setup>中可以不用手动导入组件，正是因为这样，导致国际化丢失了，我也不知道是什么原因，但事实如此，我编译试了十几回了，这应该也是ep的bug吧？官方文档里也推荐这个插件了

**Comment by Tiramisupxl** [comment]
> > 你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文 [DEMO](https://stackblitz.com/edit/github-vewuqb?file=vite.config.ts)
> 
> 破案了！ 将ep排除打包在这个demo里确实有效，但是在我实际项目里还是没用，经过仔细排查对照，因为我使用了[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)自动导入，<script setup>中可以不用手动导入组件，正是因为这样，导致国际化丢失了，我也不知道是什么原因，但事实如此，我编译试了十几回了，这应该也是ep的bug吧？官方文档里也推荐这个插件了

请问下是如何把ep排除打包中？

**Comment by zz541843** [comment]
> > > 你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文 [DEMO](https://stackblitz.com/edit/github-vewuqb?file=vite.config.ts)
> > 
> > 
> > 破案了！ 将ep排除打包在这个demo里确实有效，但是在我实际项目里还是没用，经过仔细排查对照，因为我使用了[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)自动导入，<script setup>中可以不用手动导入组件，正是因为这样，导致国际化丢失了，我也不知道是什么原因，但事实如此，我编译试了十几回了，这应该也是ep的bug吧？官方文档里也推荐这个插件了
> 
> 请问下是如何把ep排除打包中？

vite配置 build.rollupOptions.external 添加就行了

**Comment by Tiramisupxl** [comment]
> > > > 你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文 [DEMO](https://stackblitz.com/edit/github-vewuqb?file=vite.config.ts)
> > > 
> > > 
> > > 破案了！ 将ep排除打包在这个demo里确实有效，但是在我实际项目里还是没用，经过仔细排查对照，因为我使用了[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)自动导入，<script setup>中可以不用手动导入组件，正是因为这样，导致国际化丢失了，我也不知道是什么原因，但事实如此，我编译试了十几回了，这应该也是ep的bug吧？官方文档里也推荐这个插件了
> > 
> > 
> > 请问下是如何把ep排除打包中？
> 
> vite配置 build.rollupOptions.external 添加就行了
好呢，感谢！！

**Comment by FlySnails** [comment]
> 
build.rollupOptions.external为啥排出了，还是有问题...

**Comment by yehua-8858** [comment]
封装的二次组件库：
![image](https://user-images.githubusercontent.com/109339196/226302881-a714dbe2-1390-428a-b736-75fb1bcf393f.png)
vite.config.js中build.rollupOptions.external配置项去除element-plus。
![image](https://user-images.githubusercontent.com/109339196/226303534-fef53893-c656-4236-92a1-a179dbc068d5.png)

**Comment by falcon-jin** [comment]
> 封装的二次组件库： ![image](https://user-images.githubusercontent.com/109339196/226302881-a714dbe2-1390-428a-b736-75fb1bcf393f.png) vite.config.js中build.rollupOptions.external配置项去除element-plus。 ![image](https://user-images.githubusercontent.com/109339196/226303534-fef53893-c656-4236-92a1-a179dbc068d5.png)

这个可以动态切换中英文吗

**Comment by falcon-jin** [comment]
> > [element-pro-components](https://github.com/tolking/element-pro-components)
> 
> 我新起了一个仓库，复现了这个问题

你打包后的文件里面是不是有package.json dependencies里面还有element plus 把里面的element plus删了试试

**Comment by jingyuLin1999** [comment]
如果第二个项目引入第一个项目是按需引入像这样
import { Richform, SplitLayout } from "richform"
那要怎么处理

**Comment by jingyuLin1999** [comment]
封装的二次组件库
```js
import { App } from 'vue'

import Richform, { AjvValidate } from "./Richform"
import SplitLayout from "./SplitLayout"
import FormDesign, { fdMetas } from "./Formdesign"
import { provideGlobalConfig } from "element-plus"

// 按需加载的组件
const components = [Richform, SplitLayout, FormDesign]

// 默认安装
export function install(app: App, options) {
    provideGlobalConfig(options, app, true);
    components.forEach(component => component.install(app))
}

export const FD_METAS = fdMetas

export const AJValidate = AjvValidate

export * from "./Richform"
export * from "./SplitLayout"
export * from "./Formdesign"
```

**Comment by ZhongxuYang** [comment]
> > 你应该将 ElementPlus 排除在打包内容中，你这样 locale 始终是 undefined，当然始终是英文 [DEMO](https://stackblitz.com/edit/github-vewuqb?file=vite.config.ts)
> 
> 破案了！ 将ep排除打包在这个demo里确实有效，但是在我实际项目里还是没用，经过仔细排查对照，因为我使用了[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)自动导入，<script setup>中可以不用手动导入组件，正是因为这样，导致国际化丢失了，我也不知道是什么原因，但事实如此，我编译试了十几回了，这应该也是ep的bug吧？官方文档里也推荐这个插件了

使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)导致国际化丢失有解决方案嘛？
