### ISSUE TITLE
[Component] [notification] Notification 通知打开后只要按过backspace就不会自动关闭了，你们官网的也是这样

### ISSUE THREAD

**Issue by Cheresting** [element-plus/element-plus#8648]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-notification`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/notification.html)

### Steps to reproduce

直接第一个示例就有这个问题，先打开一个Notification,然后按一下backspace,Notification就不会自动关闭了

### What is Expected?

会自动关闭

### What is actually happening?

不自动关闭

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
设计如此吧，因为源码中有相关的处理。
