### ISSUE TITLE
[Component] [tab-pane] el-tab-pane无法编辑，内容不可编辑，没有对应的方法，使用插槽也无效

### ISSUE THREAD

**Issue by ConstancyMan** [element-plus/element-plus#8649]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.6`
- Browser / OS: `user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-tab-pane`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tabs.html#tabs-%E4%BA%8B%E4%BB%B6)

### Steps to reproduce

没有可编辑名称的事件使用插槽也不显示

### What is Expected?

双击tab可以修改名称

### What is actually happening?

没有双击可实现修改名称的事件或使用插槽无效

### Additional comments

双击tab可以修改名称

**Comment by chenxch** [comment]
可以自己DIY哦，这个[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB0eXBlPVwiYm9yZGVyLWNhcmRcIiBjbGFzcz1cImRlbW8tdGFic1wiPlxuICAgIDxlbC10YWItcGFuZT5cbiAgICAgIDx0ZW1wbGF0ZSAjbGFiZWw+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiY3VzdG9tLXRhYnMtbGFiZWxcIiB2LWlmPVwiIWZsYWdcIiBAZGJsY2xpY2s9XCJmbGFnPXRydWVcIiBvdXRzaWRlLWNsaWNrPlxuICAgICAgICAgIDxlbC1pY29uPjxjYWxlbmRhciAvPjwvZWwtaWNvbj5cbiAgICAgICAgICA8c3Bhbj57e2xhYmVsfX08L3NwYW4+XG4gICAgICAgIDwvc3Bhbj5cbiAgICAgICAgPGVsLWlucHV0IHYtZWxzZSB2LW1vZGVsPVwibGFiZWxcIj48L2VsLWlucHV0PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIFJvdXRlXG4gICAgPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJDb25maWdcIj5Db25maWc8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlJvbGVcIj5Sb2xlPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCJUYXNrXCI+VGFzazwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBDYWxlbmRhciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBcbmNvbnN0IGZsYWcgPSByZWYoZmFsc2UpXG5jb25zdCBsYWJlbD0gcmVmKCdyb3V0ZScpXG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG4uZGVtby10YWJzIC5jdXN0b20tdGFicy1sYWJlbCAuZWwtaWNvbiB7XG4gIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7XG59XG4uZGVtby10YWJzIC5jdXN0b20tdGFicy1sYWJlbCBzcGFuIHtcbiAgdmVydGljYWwtYWxpZ246IG1pZGRsZTtcbiAgbWFyZ2luLWxlZnQ6IDRweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)基础上再加个点击外部保存或者你加个保存按钮就行了

**Comment by ConstancyMan** [comment]
感谢大佬，效果已实现！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 晚上11:35
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [tab-pane] el-tab-pane无法编辑，内容不可编辑，没有对应的方法，使用插槽也无效 (Issue #8649)





 
可以自己DIY哦，这个demo基础上再加个点击外部保存或者你加个保存按钮就行了

**Comment by ConstancyMan** [comment]
***@***.***事件触发时机有问题吧，当我按Delete或Backspace键时也会触发，此时我只想删除el-input中的文本，但是它会将整个el-tab-pane元素删除，是不是有点不合理
？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 晚上10:24
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [tab-pane] el-tab-pane无法编辑，内容不可编辑，没有对应的方法，使用插槽也无效 (Issue #8649)





 
Closed #8649 as completed.

**Comment by ConstancyMan** [comment]
> 

你这个@tab-remove事件触发时机有问题吧，当我按Delete或Backspace键时也会触发，此时我只想删除el-input中的文本，但是它会将整个el-tab-pane元素删除，是不是有点不合理
？？
