### ISSUE TITLE
[Style] [image, table] el-image 组件和 el-table 展开项搭配使用时显示层级异常

### ISSUE THREAD

**Issue by zhyipeng** [element-plus/element-plus#8664]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Edge/102.0.1245.30 Intel Mac OS X 10_15_7)`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0YWJsZURhdGExID0gcmVmKFtcbiAge2lkOiAxLCBpbWc6IFwiaHR0cHM6Ly90czEuY24ubW0uYmluZy5uZXQvdGg/aWQ9T1JNUy5mYjJlNjMxYTZiNWE1ZDdhMDVhODQ3ZDFlZjIzZWVjNCZwaWQ9V2RwJnc9MzAwJmg9MTU2JnFsdD05MCZjPTEmcnM9MSZkcHI9MiZwPTBcIn0sXG4gIHtpZDogMiwgaW1nOiBcImh0dHBzOi8vaW1nLXMtbXNuLWNvbS5ha2FtYWl6ZWQubmV0L3RlbmFudC9hbXAvZW50aXR5aWQvQUFZS0ZaRT93PTMwMCZoPTIyNSZxPTYwJm09NiZmPWpwZyZ1PXRcIn1cbl0pXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA4JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDYnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gICAgaW1nOiBcImh0dHBzOi8vdHMxLmNuLm1tLmJpbmcubmV0L3RoP2lkPU9STVMuZmIyZTYzMWE2YjVhNWQ3YTA1YTg0N2QxZWYyM2VlYzQmcGlkPVdkcCZ3PTMwMCZoPTE1NiZxbHQ9OTAmYz0xJnJzPTEmZHByPTImcD0wXCJcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA3JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGRpdj5cbiAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiA6ZXhwYW5kLXJvdy1rZXlzPVwiWycyMDE2LTA1LTA2JywgJzIwMTYtMDUtMDcnXVwiIHJvdy1rZXk9XCJkYXRlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwiZXhwYW5kXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJwcm9wc1wiPlxuICAgICAgICA8ZGl2IG09XCI0XCI+XG4gICAgICAgICAgPHAgbT1cInQtMCBiLTJcIj5TdGF0ZToge3sgcHJvcHMucm93LnN0YXRlIH19PC9wPlxuICAgICAgICAgIDxwIG09XCJ0LTAgYi0yXCI+Q2l0eToge3sgcHJvcHMucm93LmNpdHkgfX08L3A+XG4gICAgICAgICAgPHAgbT1cInQtMCBiLTJcIj5BZGRyZXNzOiB7eyBwcm9wcy5yb3cuYWRkcmVzcyB9fTwvcD5cbiAgICAgICAgICA8cCBtPVwidC0wIGItMlwiPlppcDoge3sgcHJvcHMucm93LnppcCB9fTwvcD5cbiAgICAgICAgICA8ZWwtaW1hZ2Ugdi1pZj1cInByb3BzLnJvdy5pbWdcIiA6cHJldmlldy1zcmMtbGlzdD1cIltwcm9wcy5yb3cuaW1nXVwiIDppbml0aWFsLWluZGV4PVwiMFwiIDpzcmM9XCJwcm9wcy5yb3cuaW1nXCIgOnotaW5kZXg9XCI1MFwiPjwvZWwtaW1hZ2U+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHByb3A9XCJkYXRlXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiTmFtZVwiIHByb3A9XCJuYW1lXCIgLz5cbiAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

上述链接, 点开展开项里的图片会出图片预览界面, 此时若最后一个表格项是展开的, 则展开的组件和大图一样高亮了

### What is Expected?

图片预览时其他所有内容应被遮罩遮住

### What is actually happening?

图片预览时表格最后一行的展开项未被遮罩遮住

### Additional comments

_(empty)_

**Comment by zhyipeng** [comment]
> [docs](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89) Hello, 尽量先看文档或者在issue中先搜索，这样也便于你快速解决问题。

你确定我所描述的和文档所述的是同一类问题吗? 按文档链接的issue所述将标签改为非自闭合后依旧复现了.
![image](https://user-images.githubusercontent.com/36840659/177719128-6b129d61-c402-448c-827d-06d24e7fa9c0.png)

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/177719474-839b98b9-4a55-45d7-a38e-7a33cd8867dc.png)
`preview-teleported` 属性加了没？？？

**Comment by zhyipeng** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/177719474-839b98b9-4a55-45d7-a38e-7a33cd8867dc.png) `preview-teleported` 属性加了没？？？

抱歉, 看错地方了
