### ISSUE TITLE
[Component] [message-box] 开启ssr模式并且自定义命名空间时 namespace不正确 resolvers: [ElementPlusResolver({ importStyle: "sass", ssr: true })]

### ISSUE THREAD

**Issue by yujindong** [element-plus/element-plus#8670]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.6`
- Browser / OS: `all`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Github Repo](https://github.com/yujindong/element-plus-issue)

### Steps to reproduce

```vue
<script setup>
import { ElMessageBox } from "element-plus";
ElMessageBox({message: "hello"})
</script>

<template>
  <el-config-provider namespace="my-namespace">
    <RouterView />
  </el-config-provider>
</template>
```

### What is Expected?

<div class="my-namespace-overlay is-message-box" style="z-index: 2002">
    <div role="dialog" aria-modal="true" aria-describedby="my-namespace-id-2350-0" class="my-namespace-overlay-message-box" aria-label="">
      <div class="my-namespace-message-box" tabindex="-1">
      
      </div>
    </div>
  </div>

### What is actually happening?

<div class="el-overlay is-message-box" style="z-index: 2002">
    <div role="dialog" aria-modal="true" aria-describedby="el-id-2350-0" class="el-overlay-message-box" aria-label="">
      <div class="el-message-box" tabindex="-1">
        
      </div>
    </div>
  </div>

### Additional comments

我现在是这样处理的
```vite.config.ts
Components({
      extensions: ["vue", "md"],
      include: [/\.vue$/, /\.vue\?vue/, /\.md$/],
      dts: "src/components.d.ts",
      resolvers: [ElementPlusResolver({ importStyle: "sass", ssr: true })]
    }),
css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use "src/scss/element/variable.scss" as *;`
      }
    }
  },
```

```scss src/scss/element/variable.scss
@forward "element-plus/theme-chalk/src/mixins/config.scss" with (
  $namespace: "my-namespace"
);

@use "element-plus/theme-chalk/src/var.scss" as *;
@use "element-plus/theme-chalk/src/dark/css-vars.scss" as *;
// ...
```

```scss scss/element/index.scss
// 这些样式都需要手动引入，否则都会丢失
@use "element-plus/theme-chalk/src/overlay.scss";
@use "element-plus/theme-chalk/src/message-box.scss";
@use "element-plus/theme-chalk/src/message.scss";
@use "element-plus/theme-chalk/src/popper.scss";
@use "element-plus/theme-chalk/src/loading.scss";
```

```vue App.vue
<el-config-provider namespace="my-namespace">
    <RouterView />
</el-config-provider>

```
```vue 
<script lang="ts" setup>
import { ElMessageBox } from "element-plus";
ElMessageBox({
    message: "hello"
})
</script>

```

当我调用 ElMessageBox时，标签的namespace 依然是el-message-box 
有什么办法可以解决

**Comment by chenxch** [comment]
[element-plus-vite-starter](https://github.com/element-plus/element-plus-vite-starter) 可以参考下这个demo

**Comment by yujindong** [comment]
补充 之前的描述有遗漏 只有在设置了ssr: true 时才会有这个问题
Components({
        extensions: ["vue"],
        include: [/\.vue$/, /\.vue\?vue/],
        dts: "src/components.d.ts",
        resolvers: [ElementPlusResolver({ importStyle: "sass", ssr: true })]
 }),
