### ISSUE TITLE
[Component] [slider] size prop is invalid

### ISSUE THREAD

**Issue by Mario34** [element-plus/element-plus#8688]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 102.0.5005.61/Mac os 12.2.1 `
- Build Tool: `Other`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHNob3ctaW5wdXQgc2l6ZT1cImxhcmdlXCIgLz5cbiAgPGVsLXNsaWRlciB2LW1vZGVsPVwidmFsdWVcIiBzaG93LWlucHV0IC8+XG4gIDxlbC1zbGlkZXIgdi1tb2RlbD1cInZhbHVlXCIgc2hvdy1pbnB1dCBzaXplPVwic21hbGxcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoMClcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLXNsaWRlciB7XG4gIG1hcmdpbi10b3A6IDIwcHg7XG59XG5cbi5lbC1zbGlkZXI6Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tdG9wOiAwO1xufVxuPC9zdHlsZT5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Check the replay link, or check the [official documentation](https://element-plus.org/en-US/component/slider.html#sizes)

### What is Expected?

Size prop can control the slider size

### What is actually happening?

Size prop was ignored

### Additional comments

_(empty)_

**Comment by Mario34** [comment]
I think the description of size/inputSize in the document is a bit ambiguous, this may not be a bug.
In addition, my requirements can be realized by using custom CSS variables

```css
.el-slider__button {
   --el-slider-button-size: 10px;
 }
```

**Comment by tolking** [comment]
It looks like the docs is inaccurate and should only be valid for input component.
