### ISSUE TITLE
DateTimePicker picker-options is invalid

### ISSUE THREAD

**Issue by XuZhaoTong** [element-plus/element-plus#869]
![image](https://user-images.githubusercontent.com/32711995/101321756-d6869880-38a0-11eb-9727-4adc0a6e76e1.png)
Official demo，in the second example, the picker-options is invalid

**Comment by bastarder** [comment]
CC @zazzaz

**Comment by bastarder** [comment]
Maybe document need to update, we will fix it

**Comment by zazzaz** [comment]
will do

**Comment by tbwork** [comment]
The picker-options is vaid, but  the whole document does not provide any selectable plan, so annoying!

**Comment by zazzaz** [comment]
Please ref to this demo code ATM https://github.com/element-plus/element-plus/issues/1030#issuecomment-747321613

The doc will be updated in this week.

**Comment by zazzaz** [comment]
fixed in #1033
