### ISSUE TITLE
[Component] [message]ElementPlus组件从head头部引入时ElMessage组件使用异常，版本号2.7+

### ISSUE THREAD

**Issue by wangnamin** [element-plus/element-plus#8691]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.7`
- Browser / OS: `Chrome/103.0.5060.66（正式版本）`
- Build Tool: `Webpack`

### Related Component

- `el-message`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/wangnamin/gojwk1x6/2/)

### Steps to reproduce

将代码复制到html文件中执行，点击按钮，查看控制台

### What is Expected?

el-message组件正常弹出

### What is actually happening?

el-message组件没有正常弹出，在控制台有错误

### Additional comments

jsfiddle中的代码运行正常，需要将代码复制到html文件中执行，即可复现

**Comment by btea** [comment]
我这里可以正常弹出
![image](https://user-images.githubusercontent.com/24516654/177898733-624913a6-c32e-4319-8f4c-085f255b6842.png)

**Comment by wangnamin** [comment]
> 我这里可以正常弹出 ![image](https://user-images.githubusercontent.com/24516654/177898733-624913a6-c32e-4319-8f4c-085f255b6842.png)

[JSFiddle](https://jsfiddle.net/wangnamin/gojwk1x6/2/)里是可以，将代码复制到html文件中访问就不行
![image](https://user-images.githubusercontent.com/26314962/177906724-9cc6896f-dae3-46b6-bbe7-2d4e336f9da6.png)
![image](https://user-images.githubusercontent.com/26314962/177906876-8d74c638-4309-4492-8234-e509cd482a7c.png)

**Comment by wangnamin** [comment]
**同样的代码 element-plus@2.2.6 可以正常使用
element-plus@2.2.7+ 就不行了**
`<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://unpkg.com/vue@next"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/element-plus@2.2.8/dist/index.css">
    
    <script src="https://unpkg.com/element-plus@2.2.8/dist/index.full.js"></script>
    <title>Element Plus demo</title>
  </head>

  <body>
    <div id="app">
      <el-button @click="test">{{ message }}</el-button>
    </div>
    <script>
      const {
        ElMessage
      } = ElementPlus
      const App = {
        data() {
          return {
            message: "Hello Element Plus",
          };
        },
        setup() {
          const test = () => {
            ElMessage({
              message: '保存成功！',
              type: 'success'
            });
          }
          return {
            test
          }
        }
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");

    </script>
  </body>

</html>
`

**Comment by norangit** [comment]
这是bug，组件里没设置默认值。。。你改成这样子：

```
 ElMessage({
              message: '保存成功！',
              type: 'success',
              // 赋默认值
              appendTo: document.body
 });
```

**Comment by wangnamin** [comment]
> 这是bug，组件里没设置默认值。。。你改成这样子：
> 
> ```
>  ElMessage({
>               message: '保存成功！',
>               type: 'success',
>               // 赋默认值
>               appendTo: document.body
>  });
> ```

这样写可以，感谢！问题解决了

**Comment by tolking** [comment]
可以将 `<script src="https://unpkg.com/element-plus@2.2.8/dist/index.full.js"></script>` 移动到 body 里面

因为当放在 head 时，代码初始化 document.body 为 null 从而引起错误
