### ISSUE TITLE
[Component] [sub-menu] 在 createSSRApp 中使用 el-sub-menu 组件报错 Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by EamonJoy** [element-plus/element-plus#8692]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.8`
- Browser / OS: `macOS 10.15.7`
- Build Tool: `Vite`

### Related Component

- `el-sub-menu`

### Reproduction Link

[Link](https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch)

### Steps to reproduce

      <el-sub-menu index="avatar">
        <el-menu-item index="logout">{{ t('login.logout') }}</el-menu-item>
      </el-sub-menu>

### What is Expected?

https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

### What is actually happening?

Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom

runtime-core.esm-bundler.js:4571 Hydration completed but contains mismatches

### Additional comments

应该是这个原因导致的
https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

**Comment by EamonJoy** [comment]
[](url)

**Comment by EamonJoy** [comment]
<img width="887" alt="截屏2022-07-07 下午4 02 16" src="https://user-images.githubusercontent.com/16645724/177724078-3fd46df1-f59f-470c-a085-6b81d7b1255b.png">

应该是 createSSRApp 方法内部根据这个 https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch 规则，不允许出现 <li>标签内嵌<div>标签的情况，所以导致<li>标签和<div>标签没有闭合，生成的源码是以下情况

`<li class="el-sub-menu" role="menuitem" ariahaspopup="true" ariaexpanded="false"><!--[--><div class="el-sub-menu__title el-tooltip__trigger el-tooltip__trigger" style="border-bottom-color:transparent;color:;background-color:;"><!----><i class="el-icon el-sub-menu__icon-arrow" style=""><!--[--><svg viewbox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M831.872 340.864 512 652.672 192.128 340.864a30.592 30.592 0 0 0-42.752 0 29.12 29.12 0 0 0 0 41.6L489.664 714.24a32 32 0 0 0 44.672 0l340.288-331.712a29.12 29.12 0 0 0 0-41.728 30.592 30.592 0 0 0-42.752 0z"></path></svg><!--]--></i></div><!--teleport start--><!--teleport end--><!--]--></li>`

**Comment by EamonJoy** [comment]
<img width="904" alt="截屏2022-07-07 下午4 19 03" src="https://user-images.githubusercontent.com/16645724/177726593-f2b5d788-eaca-4610-b8d3-25e9b4e342ba.png">

**Comment by tolking** [comment]
li 似乎可以内嵌 div，问题可能不是这个 🤔

**Comment by zybieku** [comment]
+1 怎么解决

**Comment by zybieku** [comment]
el-sub-menu中 el-menu-item混乱了
代码如下
![image](https://user-images.githubusercontent.com/15903330/179751825-cb76c690-ec75-4e7b-bd6f-6351e216f013.png)
渲染效果 所有的el-menu-item 跑到一个 el-sub-menu下面了
![image](https://user-images.githubusercontent.com/15903330/179751066-e26a04d2-89e5-4778-857a-76c326cb6134.png)

**Comment by tolking** [comment]
@zybieku 我没有重现该问题，您愿意提供一个可以重现错误示例吗？
