### ISSUE TITLE
[TypeScript] [All] clone 下来之后pnpm run build 失败

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#8693]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.8`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus)

### Steps to reproduce

node 16.13.2
pnpm 7.3

### What is Expected?

可以正常打包

### What is actually happening?

打包报错，typescript类型检查未通过

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/33827314/177722762-1acd3f5d-4b55-4405-b4da-1088de2dd526.png)

**Comment by chenxch** [comment]
dev分支

**Comment by gjfei** [comment]
你可以试试看master分支嘛？

**Comment by chenxch** [comment]
我没有重新安装依赖包，直接跑了一下是可以的

**Comment by gjfei** [comment]
> 我没有重新安装依赖包，直接跑了一下是可以的

我找到问题了

**Comment by chenxch** [comment]
> 我找到问题了

方便分享一下么

**Comment by gjfei** [comment]
> > 我找到问题了
> 
> 方便分享一下么

我们自己的改动导致的，和plus无关

**Comment by gjfei** [comment]
> > > 我找到问题了
> > 
> > 
> > 方便分享一下么
> 
> 我们自己的改动导致的，和plus无关

你可以帮我看另外一个pr吗？这个pr对我们来说很重要 #6711

**Comment by gjfei** [comment]
> 好的，不过要稍微晚点哈

好的谢谢，如何才能加入plus 的组织

**Comment by chenxch** [comment]
不好意思现在才看到，这块我也不是很清楚，我当初是有幸收到管理邀请成为合作者。

**Comment by lixiaofa** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/177802415-9be01a8d-3bc8-4840-a75e-5319351e1884.png) 刚刚用最新的代码跑了下pnpm build

@chenxch 确实跑不了 ， 一直说内存泄漏
