### ISSUE TITLE
[Component] [time-picker, date-picker] 范围选择器，点击清除按钮，下拉面板会闪烁一下

### ISSUE THREAD

**Issue by Tsong-LC** [element-plus/element-plus#8694]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`
- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E8%8C%83%E5%9B%B4)

### Steps to reproduce

1、点击清除按钮

### What is Expected?

1、清除内容，下拉面板不闪烁

### What is actually happening?

1、清除内容，下拉面板闪烁

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
fix: https://github.com/element-plus/element-plus/pull/8998
preview: https://preview-8998-element-plus.surge.sh/en-US/component/datetime-picker.html#datetime-formats
