### ISSUE TITLE
[Component] [popover] el-popover v-model:visible 无双向绑定效果

### ISSUE THREAD

**Issue by jerry000lin** [element-plus/element-plus#8696]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `chorme80`
- Build Tool: `Webpack`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICA8ZWwtcG9wb3ZlclxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICBjb250ZW50PVwidGhpcyBpcyBjb250ZW50LCB0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudFwiXG4gID5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwidmlzaWJsZSA9ICF2aXNpYmxlXCI+TWFudWFsIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击显示弹层，点击外部弹层不消失，将需要自己绑定 click-outside 指令才能实现对应的效果

### What is Expected?

内部实现click-outside时 update:visible:false

### What is actually happening?

弹层无法关闭，使用不便

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这个场景建议使用 `trigger="click"` , `visible`目前应该是作为全部交给用户控制的一个属性。

**Comment by chenxch** [comment]
十分感谢您的建议，这部分我们会进行一个优化，确保在使用`visible`时候使用`trigger`也能正常触发，并且修改`visible`。
等于说如果只使用`visible`不使用`trigger`，这个弹层的show/hide,完全由用户自己控制；
如果使用`visible`和`trigger`，那么用户和组件自身都会对弹层进行相应的show/hide处理，并且会更新`visible`；

**Comment by jerry000lin** [comment]
> 十分感谢您的建议，这部分我们会进行一个优化，确保在使用`visible`时候使用`trigger`也能正常触发，并且修改`visible`。 等于说如果只使用`visible`不使用`trigger`，这个弹层的show/hide,完全由用户自己控制； 如果使用`visible`和`trigger`，那么用户和组件自身都会对弹层进行相应的show/hide处理，并且会更新`visible`；

感谢，目前 `trigger` 也不能实现效果，优化后是想要的。
