### ISSUE TITLE
[Component] [input] [input] formatter、parser 默认值不会被format，且输入值parser不生效得到的值是format之后的

### ISSUE THREAD

**Issue by bug-coder-ruirui** [element-plus/element-plus#8721]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.8`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJzEyMzQ1Njc4JylcblxuY29uc3QgZm9ybWF0dGVyID0gdmFsID0+IFN0cmluZyh2YWwpLnJlcGxhY2UoIC8oXFxkKSg/PShcXGR7M30pKyQpL2csICckMSwnIClcbmNvbnN0IHBhcnNlciA9IHZhbCA9PiB2YWwucmVwbGFjZSgvLC9nLCAnJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIDpmb3JtYXR0ZXI9XCJmb3JtYXR0ZXJcIiA6cGFyc2VyPVwicGFyc2VyXCIgLz5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

输入默认值： 123456789
输入数据： 123456789

### What is Expected?

默认显示：123,456,789
输入得到值：123456789

### What is actually happening?

默认显示：123456789
输入得到值：123,456,789

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
@bug-coder-ruirui hello,你是pr似乎提交到了自己的仓库，我看了下代码，似乎我们可以不用这么麻烦，只要在初始化的时候做一次formatter就好了

**Comment by bug-coder-ruirui** [comment]
> 
谢谢，但是只有formatter的话parser的好像是无效的吧，绑定的仍然是formatter之后的值

**Comment by chenxch** [comment]
我的预想是组件内进行formatter，如果你有兴趣的话可以提个pr，我们一起详细探讨一下。

**Comment by zhengsenyi** [comment]
> > 
> 
> 谢谢，但是只有formatter的话parser的好像是无效的吧，绑定的仍然是formatter之后的值

解决了吗，我目前版本2.3.0也是这问题，回显没有格式化，得到的值是格式化后的。

**Comment by 1003092671** [comment]
> > > 
> > 
> > 
> > 谢谢，但是只有formatter的话parser的好像是无效的吧，绑定的仍然是formatter之后的值
> 
> 解决了吗，我目前版本2.3.0也是这问题，回显没有格式化，得到的值是格式化后的。

最新版解决了,旧版可以在组件内不使用formatter和parser,给el-input 分别绑定modelValue 和 update:modelValue,在update时调用emits前,自己写方法把formatter和parser的功能写在方法里格式化值 然后提交给父组件更新

**Comment by zaxlct** [comment]
没解决啊，"element-plus": "^2.3.3",

**Comment by bug-coder-ruirui** [comment]
> 没解决啊，"element-plus": "^2.3.3",
我看了一下 好像确实没有解决  你可以自己用computed进行一次简单的封装自己解决一下

**Comment by bug-coder-ruirui** [comment]
> > 没解决啊，"element-plus": "^2.3.3",
> > 我看了一下 好像确实没有解决  你可以自己用computed进行一次简单的封装自己解决一下
```
<template>
  <el-input v-bind="$attrs" v-model="val"></el-input>
</template>
<script lang="ts" setup>
import { defineProps, defineEmits, computed } from 'vue';

const props = defineProps<{
  modelValue: string,
  formatter?: (v:string) => string,
  parser?: (v:string) => string
}>()
const emit = defineEmits<{
  (event: 'update:modelValue', value: string): void
}>()

const val = computed({
  get () {
    return props.modelValue ? props.formatter?.(props.modelValue) || props.modelValue : ''
  },
  set (v:string) {
    const _v = props.parser?.(v) || v
    emit('update:modelValue', _v)
  }
})
</script>
```

**Comment by FabianMontoya** [comment]
I have the same problem

**Comment by yymjku18** [comment]
还没有修复么，遇到什么困难了？

**Comment by FabianMontoya** [comment]
> 还没有修复么，遇到什么困难了？

Steps to reproduce
输入默认值： 123456789
输入数据： 123456789

What is Expected?
默认显示：123,456,789
输入得到值：123456789

What is actually happening?
默认显示：123456789
输入得到值：123,456,789

**Comment by haoma2514** [comment]
测试过了，2.3.7版本已修复

**Comment by xiaolin089** [comment]
![image](https://github.com/element-plus/element-plus/assets/50652788/39c7e7ad-5ff4-4a73-bda3-4245e653a1a9)
![image](https://github.com/element-plus/element-plus/assets/50652788/0e6d0726-33c1-4969-9ec6-810e1410ade2)
"element-plus": "^2.3.12",请问是我用的方法不对吗？
