### ISSUE TITLE
[Component] blur event does not triggered on selects and datepickers

### ISSUE THREAD

**Issue by wtcodeai** [element-plus/element-plus#8724]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.1`
- Browser / OS: `Safari 15.2 (17612.3.6.1.6)/Mac OS 12.1`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`
- `el-select`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxTZWxlY3RWMiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IHZhbHVlID0gcmVmKCdvYmplY3QnKVxuY29uc3Qgb25CbHVyID0gKCkgPT4geyBjb25zb2xlLmxvZygnQkxVUiBXT1JLRUQnKSB9XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1zZWxlY3QtdjJcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiIFxuICAgICAgOm9wdGlvbnM9XCJbXG4gICAgICAgIHsgbGFiZWw6ICdGaXJzdCB2YWwnLCB2YWx1ZTogJ29iamVjdCd9LFxuICAgICAgICB7IGxhYmVsOiAnU2Vjb25kIHZhbCcsIHZhbHVlOiAnYWRkcmVzcycgfVxuICAgICAgXVwiXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBAYmx1cj1cIm9uQmx1clwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Set up component with dropdown (el-select-v2 for example)
2. Open dropdown and select any option

### What is Expected?

blur event should be emitted and also component should be blured (unfocused)

### What is actually happening?

component stay focused, blur event not emitted

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Design so.

**Comment by wtcodeai** [comment]
But maybe there should be a component property which contols this behaviour? This "design" was unexpectedly implemented with one of new versions

**Comment by chenxch** [comment]
The option popup is also part of the component.

**Comment by tolking** [comment]
This is a feature related to a11y, which is consistent with the native select. [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5mdW5jdGlvbiBsb2coZSkge1xuICBjb25zb2xlLmxvZyhlKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHNlbGVjdCBAY2hhbmdlPVwibG9nXCI+XG4gICAgPG9wdGlvbiB2YWx1ZT1cIjExMVwiPjExMTwvb3B0aW9uPlxuICAgIDxvcHRpb24gdmFsdWU9XCIyMjJcIj4yMjI8L29wdGlvbj5cbiAgICA8b3B0aW9uIHZhbHVlPVwiMzMzXCI+MzMzPC9vcHRpb24+XG4gICAgPG9wdGlvbiB2YWx1ZT1cIjQ0NFwiPjQ0NDwvb3B0aW9uPlxuICA8L3NlbGVjdD5cbiAgPGJ1dHRvbj5cbiAgICBidXR0b25cbiAgPC9idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
