### ISSUE TITLE
[Component] [date-picker] Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by tl1994** [element-plus/element-plus#8728]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IHJlZiwgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyAgRWxEYXRlUGlja2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuZXhwb3J0IGRlZmF1bHQge1xuICBzZXR1cCgpIHtcblx0XHRjb25zdCBfZGF0ZVZhbHVlID0gcmVmKCcnKVxuICAgIHJldHVybiAoKSA9PiB7XG4gICAgICByZXR1cm4gaChcbiAgICAgICAgICAgIEVsRGF0ZVBpY2tlcixcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgbW9kZWxWYWx1ZTogX2RhdGVWYWx1ZS52YWx1ZSxcbiAgICAgICAgICAgICAgdHlwZTogJ2RhdGUnLFxuICAgICAgICAgICAgICBwbGFjZWhvbGRlcjogJ+ivt+mAieaLqScsXG4gICAgICAgICAgICB9XG4gICAgICAgICAgKVxuICAgIH1cbiAgfVxufVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Date cannot be selected

### What is Expected?

Can choose a date

### What is actually happening?

Date cannot be selected

### Additional comments

_(empty)_

**Comment by holazz** [comment]
render 函数有一点小问题，这样试试: [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IHJlZiwgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyAgRWxEYXRlUGlja2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuZXhwb3J0IGRlZmF1bHQge1xuICBzZXR1cCgpIHtcblx0XHRjb25zdCBfZGF0ZVZhbHVlID0gcmVmKCcnKVxuICAgIHJldHVybiAoKSA9PiB7XG4gICAgICByZXR1cm4gaChcbiAgICAgICAgICAgIEVsRGF0ZVBpY2tlcixcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgbW9kZWxWYWx1ZTogX2RhdGVWYWx1ZS52YWx1ZSxcbiAgICAgICAgICAgICAgJ29uVXBkYXRlOm1vZGVsVmFsdWUnOiAodmFsdWUpID0+IChfZGF0ZVZhbHVlLnZhbHVlID0gdmFsdWUpLFxuICAgICAgICAgICAgICB0eXBlOiAnZGF0ZScsXG4gICAgICAgICAgICAgIHBsYWNlaG9sZGVyOiAn6K+36YCJ5oupJyxcbiAgICAgICAgICAgIH1cbiAgICAgICAgICApXG4gICAgfVxuICB9XG59XG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

RangeError 应该是只有选择非当月日期时会出现，相关PR: #8588
