### ISSUE TITLE
[Build] [All] webpack5 按需加载不生效

### ISSUE THREAD

**Issue by qiangf811** [element-plus/element-plus#8732]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 102`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/qiangf811/webpack5-vue3-ts)

### Steps to reproduce

npm run build

### What is Expected?

按需加载，只打包部分组件

### What is actually happening?

打包了所有组件

### Additional comments

_(empty)_

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/18138724/178103451-27758b17-234d-4979-9149-93250cba4c85.png">

**Comment by sxzz** [comment]
don't use ts-loader, use babel-loader instead. 

FYI: https://github.com/element-plus/element-plus-webpack5-starter
