### ISSUE TITLE
[Component] [empty] el-empty props image is not support svg

### ISSUE THREAD

**Issue by u10k** [element-plus/element-plus#8735]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.8`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4336.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-empty`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/empty.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E7%89%87)

### Steps to reproduce

<el-empty image="@render/assets/svg/noData.svg" />

### What is Expected?

I expect the svg to display properly

### What is actually happening?

the svg did not show

### Additional comments

_(empty)_

**Comment by u10k** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/22042799/178118562-1f96f268-14ad-428f-924f-1b13e936cb86.png">

**Comment by holazz** [comment]
Can this meet your needs? [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZW1wdHlcbiAgICBpbWFnZT1cImh0dHBzOi8vZWxlbWVudC1wbHVzLm9yZy9pbWFnZXMvZWxlbWVudC1wbHVzLWxvZ28uc3ZnXCJcbiAgLz5cbiAgXG4gIDxlbC1lbXB0eT5cbiAgICA8dGVtcGxhdGUgI2ltYWdlPlxuICAgICAgPGltZyBzcmM9XCJodHRwczovL2VsZW1lbnQtcGx1cy5vcmcvaW1hZ2VzL2VsZW1lbnQtcGx1cy1sb2dvLnN2Z1wiLz5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWVtcHR5PlxuXG4gIDxlbC1lbXB0eT5cbiAgICA8dGVtcGxhdGUgI2ltYWdlPlxuICAgICAgPHN2ZyB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIgeG1sbnM6eGxpbms9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rXCIgYXJpYS1oaWRkZW49XCJ0cnVlXCIgcm9sZT1cImltZ1wiIGNsYXNzPVwiaWNvbmlmeSBpY29uaWZ5LS1lcFwiIHdpZHRoPVwiMzJcIiBoZWlnaHQ9XCIzMlwiIHByZXNlcnZlQXNwZWN0UmF0aW89XCJ4TWlkWU1pZCBtZWV0XCIgdmlld0JveD1cIjAgMCAxMDI0IDEwMjRcIj48cGF0aCBmaWxsPVwiIzQwOWVmZlwiIGQ9XCJNODM5LjcgNzM0LjdjMCAzMy4zLTE3LjkgNDEtMTcuOSA0MVM1MTkuNyA5NDkuOCA0OTkuMiA5NjBjLTEwLjIgNS4xLTIwLjUgNS4xLTMwLjcgMGMwIDAtMzE0LjktMTg0LjMtMzI1LjEtMTkyYy01LjEtNS4xLTEwLjItMTIuOC0xMi44LTIwLjVWMzY4LjZjMC0xNy45IDIwLjUtMjguMiAyMC41LTI4LjJMNDY2IDE1OC42YzEyLjgtNS4xIDI1LjYtNS4xIDM4LjQgMGMwIDAgMjc5IDE2MS4zIDMwOS44IDE3OS4yYzE3LjkgNy43IDI4LjIgMjUuNiAyNS42IDQ2LjFjLS4xLTUtLjEgMzE3LjUtLjEgMzUwLjh6TTcxNC4yIDM3MS4yYy02NC0zNS44LTIxNy42LTEyNS40LTIxNy42LTEyNS40Yy03LjctNS4xLTIwLjUtNS4xLTMwLjcgMEwyMTcuNiAzODkuMXMtMTcuOSAxMC4yLTE3LjkgMjN2Mjk3YzAgNS4xIDUuMSAxMi44IDcuNyAxNy45YzcuNyA1LjEgMjU2IDE0OC41IDI1NiAxNDguNWM3LjcgNS4xIDE3LjkgNS4xIDI1LjYgMGMxNS40LTcuNyAyNTAuOS0xNDUuOSAyNTAuOS0xNDUuOXMxMi44LTUuMSAxMi44LTMwLjd2LTc0LjJsLTI3Ni41IDE2OXYtNjRjMC0xNy45IDcuNy0zMC43IDIwLjUtNDYuMUw3NDUgNTM1YzUuMS03LjcgMTAuMi0yMC41IDEwLjItMzAuN3YtNjYuNmwtMjc5IDE2OXYtNjkuMWMwLTE1LjQgNS4xLTMwLjcgMTcuOS0zOC40bDIyMC4xLTEyOHpNOTE5IDEzNS43YzAtNS4xLTUuMS03LjctNy43LTcuN2gtNTguOVY2Ni42YzAtNS4xLTUuMS01LjEtMTAuMi01LjFsLTMwLjcgNS4xYy01LjEgMC01LjEgMi42LTUuMSA1LjFWMTI4aC01Ni4zYy01LjEgMC01LjEgNS4xLTcuNyA1LjF2MzguNGg2OS4xdjY0YzAgNS4xIDUuMSA1LjEgMTAuMiA1LjFsMzAuNy01LjFjNS4xIDAgNS4xLTIuNiA1LjEtNS4xdi01Ni4zaDY0bC0yLjUtMzguNHpcIj48L3BhdGg+PC9zdmc+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1lbXB0eT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by u10k** [comment]
> Can this meet your needs? [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZW1wdHlcbiAgICBpbWFnZT1cImh0dHBzOi8vZWxlbWVudC1wbHVzLm9yZy9pbWFnZXMvZWxlbWVudC1wbHVzLWxvZ28uc3ZnXCJcbiAgLz5cbiAgXG4gIDxlbC1lbXB0eT5cbiAgICA8dGVtcGxhdGUgI2ltYWdlPlxuICAgICAgPGltZyBzcmM9XCJodHRwczovL2VsZW1lbnQtcGx1cy5vcmcvaW1hZ2VzL2VsZW1lbnQtcGx1cy1sb2dvLnN2Z1wiLz5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWVtcHR5PlxuXG4gIDxlbC1lbXB0eT5cbiAgICA8dGVtcGxhdGUgI2ltYWdlPlxuICAgICAgPHN2ZyB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIgeG1sbnM6eGxpbms9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rXCIgYXJpYS1oaWRkZW49XCJ0cnVlXCIgcm9sZT1cImltZ1wiIGNsYXNzPVwiaWNvbmlmeSBpY29uaWZ5LS1lcFwiIHdpZHRoPVwiMzJcIiBoZWlnaHQ9XCIzMlwiIHByZXNlcnZlQXNwZWN0UmF0aW89XCJ4TWlkWU1pZCBtZWV0XCIgdmlld0JveD1cIjAgMCAxMDI0IDEwMjRcIj48cGF0aCBmaWxsPVwiIzQwOWVmZlwiIGQ9XCJNODM5LjcgNzM0LjdjMCAzMy4zLTE3LjkgNDEtMTcuOSA0MVM1MTkuNyA5NDkuOCA0OTkuMiA5NjBjLTEwLjIgNS4xLTIwLjUgNS4xLTMwLjcgMGMwIDAtMzE0LjktMTg0LjMtMzI1LjEtMTkyYy01LjEtNS4xLTEwLjItMTIuOC0xMi44LTIwLjVWMzY4LjZjMC0xNy45IDIwLjUtMjguMiAyMC41LTI4LjJMNDY2IDE1OC42YzEyLjgtNS4xIDI1LjYtNS4xIDM4LjQgMGMwIDAgMjc5IDE2MS4zIDMwOS44IDE3OS4yYzE3LjkgNy43IDI4LjIgMjUuNiAyNS42IDQ2LjFjLS4xLTUtLjEgMzE3LjUtLjEgMzUwLjh6TTcxNC4yIDM3MS4yYy02NC0zNS44LTIxNy42LTEyNS40LTIxNy42LTEyNS40Yy03LjctNS4xLTIwLjUtNS4xLTMwLjcgMEwyMTcuNiAzODkuMXMtMTcuOSAxMC4yLTE3LjkgMjN2Mjk3YzAgNS4xIDUuMSAxMi44IDcuNyAxNy45YzcuNyA1LjEgMjU2IDE0OC41IDI1NiAxNDguNWM3LjcgNS4xIDE3LjkgNS4xIDI1LjYgMGMxNS40LTcuNyAyNTAuOS0xNDUuOSAyNTAuOS0xNDUuOXMxMi44LTUuMSAxMi44LTMwLjd2LTc0LjJsLTI3Ni41IDE2OXYtNjRjMC0xNy45IDcuNy0zMC43IDIwLjUtNDYuMUw3NDUgNTM1YzUuMS03LjcgMTAuMi0yMC41IDEwLjItMzAuN3YtNjYuNmwtMjc5IDE2OXYtNjkuMWMwLTE1LjQgNS4xLTMwLjcgMTcuOS0zOC40bDIyMC4xLTEyOHpNOTE5IDEzNS43YzAtNS4xLTUuMS03LjctNy43LTcuN2gtNTguOVY2Ni42YzAtNS4xLTUuMS01LjEtMTAuMi01LjFsLTMwLjcgNS4xYy01LjEgMC01LjEgMi42LTUuMSA1LjFWMTI4aC01Ni4zYy01LjEgMC01LjEgNS4xLTcuNyA1LjF2MzguNGg2OS4xdjY0YzAgNS4xIDUuMSA1LjEgMTAuMiA1LjFsMzAuNy01LjFjNS4xIDAgNS4xLTIuNiA1LjEtNS4xdi01Ni4zaDY0bC0yLjUtMzguNHpcIj48L3BhdGg+PC9zdmc+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1lbXB0eT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

Yes, in the end I used this method
