### ISSUE TITLE
[Component] [table] table表格在tabs下表现异常

### ISSUE THREAD

**Issue by mentoorliubin** [element-plus/element-plus#8741]
![1](https://user-images.githubusercontent.com/52729282/178151970-328b79c5-7ac2-4704-b9d3-f772085ca99c.png)
![2](https://user-images.githubusercontent.com/52729282/178151973-7d3172bb-258d-41ca-bbdb-de672972d81d.png)

Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiYWN0aXZlTmFtZVwiIGNsYXNzPVwiZGVtby10YWJzXCIgQHRhYi1jbGljaz1cImhhbmRsZUNsaWNrXCI+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVXNlclwiIG5hbWU9XCJmaXJzdFwiPlxuICAgICA8ZWwtdGFibGUgOmRhdGE9XCJbXVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiA6aGVpZ2h0PVwiMTAwXCIgYm9yZGVyPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgdi1mb3I9XCIoaXRlbSwgaW5kZXgpIGluIGhlYWRlckRhdGFcIlxuICAgICAgICA6a2V5PVwiaW5kZXhcIlxuICAgICAgICA6cHJvcD1cIml0ZW0ucHJvcFwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiXG4gICAgICAvPlxuICA8L2VsLXRhYmxlPlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiQ29uZmlnXCIgbmFtZT1cInNlY29uZFwiPlxuICAgICA8ZWwtdGFibGUgOmRhdGE9XCJbXVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiA6aGVpZ2h0PVwiMTAwXCIgYm9yZGVyPlxuICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gaGVhZGVyRGF0YVwiXG4gICAgICAgIDprZXk9XCJpbmRleFwiXG4gICAgICAgIDpwcm9wPVwiaXRlbS5wcm9wXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5uYW1lXCJcbiAgICAgICAgICAgICAgICAgICAgXG4gICAgICAvPlxuICA8L2VsLXRhYmxlPlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiUm9sZVwiIG5hbWU9XCJ0aGlyZFwiPlJvbGU8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIlRhc2tcIiBuYW1lPVwiZm91cnRoXCI+VGFzazwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBUYWJzUGFuZUNvbnRleHQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ2ZpcnN0JylcbmNvbnN0IGhlYWRlckRhdGE9WyB7IFwibmFtZVwiOiBcInRlc3Rlc3RldHN0ZXN0c2VzdFwiLCBcInByb3BcIjogXCJiYXRjaFwiIH1dXG5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKHRhYjogVGFic1BhbmVDb250ZXh0LCBldmVudDogRXZlbnQpID0+IHtcbiAgY29uc29sZS5sb2codGFiLCBldmVudClcbn1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在切换tabs时，表格高度进行了错误体现
在不指定列宽度的情况下,如果表格列的名称偏长，则会出现切换时高度出现异常

### What is Expected?

切换tabs，表格高度不变

### What is actually happening?

在切换tabs时，表格高度进行了错误体现
在不指定列宽度的情况下,如果表格列的名称偏长，则会出现切换时高度出现异常

### Additional comments

_(empty)_

**Comment by plainheart** [comment]
Fixed by #8690
