### ISSUE TITLE
[Component] [menu] el-menu 存在异常问题，horizontal 模式，写成组件 异步请求 渲染数据 展现为三个点

### ISSUE THREAD

**Issue by ye1016233531** [element-plus/element-plus#8756]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `windows11`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCA+XG5leHBvcnQgZGVmYXVsdCB7XG4gIGRhdGEoKXtcbiAgICByZXR1cm4ge1xuICAgICAgdGFibGVEYXRhOlsxLDIsM11cbiAgICB9XG4gIH0sXG4gIG1vdW50ZWQoKXtcbiAgICB2YXIgX3RoaXMgPSB0aGlzO1xuICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtcbiAgICAgIF90aGlzLnRhYmxlRGF0YSA9IFsxLDIsMyw0LDUsNiw3LDgsOSwxMF1cbiAgICB9LDIwMDApXG4gIH1cbn1cbjwvc2NyaXB0PiBcbiBcbjx0ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51ICA6ZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiID5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSB2LWZvcj1cIml0ZW0gaW4gdGFibGVEYXRhXCIgOmluZGV4PVwiaXRlbVwiID57eyBpdGVtIH19PC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

重新渲染 出现无法渲染的问题   可见最小复现环境

### What is Expected?

数据渲染正常

### What is actually happening?

数据渲染异常

### Additional comments

_(empty)_

**Comment by holazz** [comment]
设置 `ellipsis` 为 `false`，eg:

```vue
<el-menu :ellipsis="false">
...
</el-menu>
```

**Comment by ye1016233531** [comment]
> 设置 为 ，eg：`ellipsis``false`
> 
> ```
> <el-menu :ellipsis="false">
> ...
> </el-menu>
> ```

好的 我已经解决了这样的问题  但是希望这个问题得到优化

**Comment by holazz** [comment]
这不是一个 bug，就是这样设计的。在水平模式下，数据过多时省略多余的子项（默认开启）

**Comment by BeiMeng** [comment]
@holazz 在水平模式下，数据过多时省略多余的子项（默认开启）是这样设计，问题的关键在于，如果是异步请求的动态渲染数据，在宽度足够的情况下，还是会省略多余子项

**Comment by ye1016233531** [comment]
> @holazz 在水平模式下，数据过多时省略多余的子项（默认开启）是这样设计，问题的关键在于，如果是异步请求的动态渲染数据，在宽度足够的情况下，还是会省略多余子项
我也是同样的问题 但还是希望这个问题得到优化
