### ISSUE TITLE
el-tree组件右击事件bug

### ISSUE THREAD

**Issue by justpp** [element-plus/element-plus#876]
右击会从当前节点逐层返回父级节点

**Comment by porcelainHeart** [comment]
Please provide the version of Vue and the version of ElementPlus

**Comment by JeremyWuuuuu** [comment]
Also with minimal reproducible code and reproducing steps.

**Comment by justpp** [comment]
"element-plus": "^1.0.1-beta.5",
    "vue": "^3.0.0"

App.vue
<template>
<el-tree
    :data="data"
    node-key="id"
    default-expand-all
    @node-contextmenu="rightClick"
    draggable
    :allow-drop="allowDrop"
    :allow-drag="allowDrag">
</el-tree>
</template>

<script>
  export default {
    data() {
      return {
        data: [{
          id: 1,
          label: '一级 1',
          children: [{
            id: 4,
            label: '二级 1-1',
            children: [{
              id: 9,
              label: '三级 1-1-1'
            }, {
              id: 10,
              label: '三级 1-1-2'
            }]
          }]
        }, {
          id: 2,
          label: '一级 2',
          children: [{
            id: 5,
            label: '二级 2-1'
          }, {
            id: 6,
            label: '二级 2-2'
          }]
        }, {
          id: 3,
          label: '一级 3',
          children: [{
            id: 7,
            label: '二级 3-1'
          }, {
            id: 8,
            label: '二级 3-2',
            children: [{
             id: 11,
              label: '三级 3-2-1'
            }, {
              id: 12,
              label: '三级 3-2-2'
            }, {
              id: 13,
              label: '三级 3-2-3'
            }]
          }]
        }],
        defaultProps: {
          children: 'children',
          label: 'label'
        }
      };
    },
    methods: {
      rightClick(event,data){
        // node-contextmenu 会触发三次
        console.log(event,data)
      }
    }
  };
</script>

**Comment by bastarder** [comment]
Maybe this is due to a VUE update， in old version the key in props is `onNode-contextmenu`, but latest is `onNode-contextmenu`, i will fix this.

**Comment by justpp** [comment]
请问修复后的版本什么时间发布呢
