### ISSUE TITLE
tslint error

### ISSUE THREAD

**Issue by whitecuteXu** [element-plus/element-plus#877]
"vue": "^3.0.4",
 "element-plus": "^1.0.1-beta.5",

ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-cascader-panel/src/config.d.ts(2,93):
2:93 Cannot find module '@element-plus/cascader-panel/src/types' or its corresponding type declarations.
    1 | import { PropType } from 'vue';
  > 2 | import { CascaderValue, CascaderOption, CascaderConfig, CascaderProps, ExpandTrigger } from '@element-plus/cascader-panel/src/types';
      |                                                                                             ^
    3 | export declare const CommonProps: {
    4 |     modelValue: PropType<CascaderValue>;
    5 |     options: {
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts(4,20):
4:20 Cannot find name 'Nullable'.
    2 | declare type ChildrenData = CascaderOption[] | undefined;
    3 | export default class Node {
  > 4 |     readonly data: Nullable<CascaderOption>;
      |                    ^
    5 |     readonly config: CascaderConfig;
    6 |     readonly parent?: Node;
    7 |     readonly root: boolean;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts(22,23):
22:23 Cannot find name 'Nullable'.
    20 |     indeterminate: boolean;
    21 |     loading: boolean;
  > 22 |     constructor(data: Nullable<CascaderOption>, config: CascaderConfig, parent?: Node, root?: boolean);
       |                       ^
    23 |     get isDisabled(): boolean;
    24 |     get isLeaf(): boolean;
    25 |     get valueByOption(): string | number | CascaderNodePathValue;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-cascader-panel/src/types.d.ts(50,20):
50:20 Cannot find name 'Nullable'.
    48 | export interface ElCascaderPanelContext {
    49 |     config: CascaderConfig;
  > 50 |     expandingNode: Nullable<CascaderNode>;
       |                    ^
    51 |     checkedNodes: CascaderNode[];
    52 |     isHoverMenu: boolean;
    53 |     renderLabelFn: RenderLabel;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-cascader/src/index.vue.d.ts(3,55):
3:55 Cannot find module '@element-plus/cascader-panel' or its corresponding type declarations.
    1 | import { Ref } from 'vue';
    2 | import type { ComputedRef, PropType } from 'vue';
  > 3 | import type { CascaderValue, CascaderNode, Tag } from '@element-plus/cascader-panel';
      |                                                       ^
    4 | declare const _default: import("vue").DefineComponent<{
    5 |     size: {
    6 |         type: PropType<ComponentSize>;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-dialog/src/useDialog.d.ts(2,36):
2:36 Cannot find module '@element-plus/utils/constants' or its corresponding type declarations.
    1 | import { CSSProperties } from 'vue';
  > 2 | import { UPDATE_MODEL_EVENT } from '@element-plus/utils/constants';
      |                                    ^
    3 | import type { Ref } from 'vue';
    4 | import type { SetupContext } from '@vue/runtime-core';
    5 | import type { UseDialogProps } from './dialog';
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-dialog/src/useDialog.d.ts(5,37):
5:37 Cannot find module './dialog' or its corresponding type declarations.
    3 | import type { Ref } from 'vue';
    4 | import type { SetupContext } from '@vue/runtime-core';
  > 5 | import type { UseDialogProps } from './dialog';
      |                                     ^
    6 | export declare const CLOSE_EVENT = "close";
    7 | export declare const OPEN_EVENT = "open";
    8 | export declare const CLOSED_EVENT = "closed";
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-form/src/token.d.ts(28,11):
28:11 Cannot find name 'ComponentSize'.
    26 |     prop?: string;
    27 |     formItemMitt: Emitter;
  > 28 |     size: ComponentSize;
       |           ^
    29 |     validateState: string;
    30 |     validate(trigger?: string, callback?: ValidateFieldCallback): void;
    31 |     updateComputedLabelWidth(width: number): void;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-popover/src/index.vue.d.ts(1,24):
1:24 Cannot find module '@element-plus/popper' or its corresponding type declarations.
  > 1 | import { Effect } from '@element-plus/popper';
      |                        ^
    2 | import type { PropType } from 'vue';
    3 | import type { TriggerType } from '@element-plus/popper';
    4 | declare const _default: import("vue").DefineComponent<{
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-popover/src/index.vue.d.ts(3,34):
3:34 Cannot find module '@element-plus/popper' or its corresponding type declarations.
    1 | import { Effect } from '@element-plus/popper';
    2 | import type { PropType } from 'vue';
  > 3 | import type { TriggerType } from '@element-plus/popper';
      |                                  ^
    4 | declare const _default: import("vue").DefineComponent<{
    5 |     content: {
    6 |         type: StringConstructor;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-popper/src/use-popper/defaults.d.ts(7,34):
7:34 Cannot find name 'Nullable'.
     5 |     LIGHT = "light"
     6 | }
  >  7 | export declare type RefElement = Nullable<HTMLElement>;
       |                                  ^
     8 | export declare type Offset = [number, number] | number;
     9 | export type { Placement, PositioningStrategy, PopperInstance, Options };
    10 | export declare type TriggerType = 'click' | 'hover' | 'focus' | 'manual';
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(23,17):
23:17 Cannot find name 'Nullable'.
    21 | }
    22 | export interface ISliderInitData {
  > 23 |     firstValue: Nullable<number>;
       |                 ^
    24 |     secondValue: Nullable<number>;
    25 |     oldValue: Nullable<number>;
    26 |     dragging: boolean;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(24,18):
24:18 Cannot find name 'Nullable'.
    22 | export interface ISliderInitData {
    23 |     firstValue: Nullable<number>;
  > 24 |     secondValue: Nullable<number>;
       |                  ^
    25 |     oldValue: Nullable<number>;
    26 |     dragging: boolean;
    27 |     sliderSize: number;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(25,15):
25:15 Cannot find name 'Nullable'.
    23 |     firstValue: Nullable<number>;
    24 |     secondValue: Nullable<number>;
  > 25 |     oldValue: Nullable<number>;
       |               ^
    26 |     dragging: boolean;
    27 |     sliderSize: number;
    28 | }
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(69,48):
69:48 Cannot find name 'Nullable'.
    67 | };
    68 | export declare type ButtonRefs = {
  > 69 |     [s in 'firstButton' | 'secondButton']: Ref<Nullable<ISliderButton>>;
       |                                                ^
    70 | };
    71 | export interface ISliderButtonProps {
    72 |     modelValue: number;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(89,18):
89:18 Cannot find name 'Nullable'.
    87 | }
    88 | export interface ISliderButton {
  > 89 |     tooltip: Ref<Nullable<HTMLElement>>;
       |                  ^
    90 |     showTooltip: Ref<boolean>;
    91 |     wrapperStyle: ComputedRef<CSSStyleDeclaration>;
    92 |     formatValue: ComputedRef<number | string>;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-tooltip/src/index.d.ts(2,49):
2:49 Cannot find module '@element-plus/popper/src/use-popper/defaults' or its corresponding type declarations.
    1 | import type { PropType } from 'vue';
  > 2 | import type { Effect, Placement, Options } from '@element-plus/popper/src/use-popper/defaults';
      |                                                 ^
    3 | declare const _default: import("vue").DefineComponent<{
    4 |     effect: {
    5 |         type: PropType<Effect>;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-tree/src/model/node.d.ts(26,24):
26:24 Cannot find name 'Nullable'.
    24 |     get key(): TreeKey;
    25 |     get disabled(): boolean;
  > 26 |     get nextSibling(): Nullable<Node>;
       |                        ^
    27 |     get previousSibling(): Nullable<Node>;
    28 |     contains(target: Node, deep?: boolean): boolean;
    29 |     remove(): void;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/el-tree/src/model/node.d.ts(27,28):
27:28 Cannot find name 'Nullable'.
    25 |     get disabled(): boolean;
    26 |     get nextSibling(): Nullable<Node>;
  > 27 |     get previousSibling(): Nullable<Node>;
       |                            ^
    28 |     contains(target: Node, deep?: boolean): boolean;
    29 |     remove(): void;
    30 |     insertChild(child?: FakeNode | Node, index?: number, batch?: boolean): void;
ERROR in D:/study/vue-brief-analysis/vue3-News/node_modules/element-plus/lib/utils/config.d.ts(2,11):
2:11 Cannot find name 'ComponentSize'.
    1 | export interface InstallOptions {
  > 2 |     size: ComponentSize;
      |           ^
    3 |     zIndex: number;
    4 |     locale?: any;
    5 | }

**Comment by JeremyWuuuuu** [comment]
cc @zouhangwithsweet @zazzaz

**Comment by JeremyWuuuuu** [comment]
I think that your linter needs to exclude `node_modules` because:
1. This could cause performance issue when linter have so many files to lint
2. Linting external project will not help you on anything, because even if it lints, you won't be able to do anything with it.

Suggestion:
Exclude files under `node_modules` or only under `node_modules/element-plus`

**Comment by zouhangwithsweet** [comment]
By the way, [TSLint is deprecated](https://github.com/palantir/tslint). For new projects, Eslint is recommended.

**Comment by warpcgd** [comment]
这个问题解决了吗？
目前使用 element-plus: "^1.0.2-beta.30" 依然会报错误，应该是element-plus没有将用到的@types打包吧

------

 > ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts(4,20):
4:20 Cannot find name 'Nullable'.
    2 | declare type ChildrenData = CascaderOption[] | undefined;
    3 | export default class Node {
 4 |     readonly data: Nullable<CascaderOption>;
      |                    ^
    5 |     readonly config: CascaderConfig;
    6 |     readonly parent?: Node;
    7 |     readonly root: boolean;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-cascader-panel/src/node.d.ts(22,23):
22:23 Cannot find name 'Nullable'.
    20 |     indeterminate: boolean;
    21 |     loading: boolean;
  > 22 |     constructor(data: Nullable<CascaderOption>, config: CascaderConfig, parent?: Node, root?: boolean);
       |                       ^
    23 |     get isDisabled(): boolean;
    24 |     get isLeaf(): boolean;
    25 |     get valueByOption(): string | number | CascaderNodePathValue;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-cascader-panel/src/types.d.ts(50,20):
50:20 Cannot find name 'Nullable'.
    48 | export interface ElCascaderPanelContext {
    49 |     config: CascaderConfig;
  > 50 |     expandingNode: Nullable<CascaderNode>;
       |                    ^
    51 |     checkedNodes: CascaderNode[];
    52 |     isHoverMenu: boolean;
    53 |     renderLabelFn: RenderLabel;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-dialog/src/useDialog.d.ts(1,36):
1:36 Cannot find module '../../el-utils/constants' or its corresponding type declarations.
  > 1 | import { UPDATE_MODEL_EVENT } from '../../el-utils/constants';
      |                                    ^
    2 | import type { Ref, CSSProperties } from 'vue';
    3 | import type { SetupContext } from '@vue/runtime-core';
    4 | import type { UseDialogProps } from './dialog';
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-form/src/token.d.ts(28,11):
28:11 Cannot find name 'ComponentSize'.
    26 |     prop?: string;
    27 |     formItemMitt: Emitter;
  > 28 |     size: ComponentSize;
       |           ^
    29 |     validateState: string;
    30 |     validate(trigger?: string, callback?: ValidateFieldCallback): void;
    31 |     updateComputedLabelWidth(width: number): void;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-popper/src/use-popper/defaults.d.ts(7,34):
7:34 Cannot find name 'Nullable'.
     5 |     LIGHT = "light"
     6 | }
  >  7 | export declare type RefElement = Nullable<HTMLElement>;
       |                                  ^
     8 | export declare type Offset = [number, number] | number;
     9 | export type { Placement, PositioningStrategy, PopperInstance, Options };
    10 | export declare type TriggerType = 'click' | 'hover' | 'focus' | 'manual';
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(23,17):
23:17 Cannot find name 'Nullable'.
    21 | }
    22 | export interface ISliderInitData {
  > 23 |     firstValue: Nullable<number>;
       |                 ^
    24 |     secondValue: Nullable<number>;
    25 |     oldValue: Nullable<number>;
    26 |     dragging: boolean;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(24,18):
24:18 Cannot find name 'Nullable'.
    22 | export interface ISliderInitData {
    23 |     firstValue: Nullable<number>;
  > 24 |     secondValue: Nullable<number>;
       |                  ^
    25 |     oldValue: Nullable<number>;
    26 |     dragging: boolean;
    27 |     sliderSize: number;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(25,15):
25:15 Cannot find name 'Nullable'.
    23 |     firstValue: Nullable<number>;
    24 |     secondValue: Nullable<number>;
  > 25 |     oldValue: Nullable<number>;
       |               ^
    26 |     dragging: boolean;
    27 |     sliderSize: number;
    28 | }
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(69,48):
69:48 Cannot find name 'Nullable'.
    67 | };
    68 | export declare type ButtonRefs = {
  > 69 |     [s in 'firstButton' | 'secondButton']: Ref<Nullable<ISliderButton>>;
       |                                                ^
    70 | };
    71 | export interface ISliderButtonProps {
    72 |     modelValue: number;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-slider/src/slider.type.d.ts(89,18):
89:18 Cannot find name 'Nullable'.
    87 | }
    88 | export interface ISliderButton {
  > 89 |     tooltip: Ref<Nullable<HTMLElement>>;
       |                  ^
    90 |     showTooltip: Ref<boolean>;
    91 |     wrapperStyle: ComputedRef<CSSStyleDeclaration>;
    92 |     formatValue: ComputedRef<number | string>;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-time-picker/src/common/props.d.ts(35,24):
35:24 Cannot find name 'ComponentSize'.
    33 |     };
    34 |     size: {
  > 35 |         type: PropType<ComponentSize>;
       |                        ^
    36 |         validator: (val: string) => boolean;
    37 |     };
    38 |     readonly: {
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-tree/src/model/node.d.ts(27,24):
27:24 Cannot find name 'Nullable'.
    25 |     get key(): TreeKey;
    26 |     get disabled(): boolean;
  > 27 |     get nextSibling(): Nullable<Node>;
       |                        ^
    28 |     get previousSibling(): Nullable<Node>;
    29 |     contains(target: Node, deep?: boolean): boolean;
    30 |     remove(): void;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/el-tree/src/model/node.d.ts(28,28):
28:28 Cannot find name 'Nullable'.
    26 |     get disabled(): boolean;
    27 |     get nextSibling(): Nullable<Node>;
  > 28 |     get previousSibling(): Nullable<Node>;
       |                            ^
    29 |     contains(target: Node, deep?: boolean): boolean;
    30 |     remove(): void;
    31 |     insertChild(child?: FakeNode | Node, index?: number, batch?: boolean): void;
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/index.d.ts(94,34):
94:34 Cannot find module './el-locale' or its corresponding type declarations.
    92 | import type { InstallOptions } from './utils/config';
    93 | declare const version = "1.0.2-beta.30";
  > 94 | declare const locale: (l: import("./el-locale").Language) => void;
       |                                  ^
    95 | declare const install: (app: App, opt: InstallOptions) => void;
    96 | export { ElAffix, ElAlert, ElAside, ElAutocomplete, ElAvatar, ElBacktop, ElBadge, ElBreadcrumb, ElBreadcrumbItem, ElButton, ElButtonGroup, ElCalendar, ElCard, ElCarousel, ElCarouselItem, ElCascader, ElCascaderPanel, ElCheckbox, ElCheckboxButton, ElCheckboxGroup, ElCol, ElCollapse, ElCollapseItem, ElCollapseTransition, ElColorPicker, ElContainer, ElDatePicker, ElDialog, ElDivider, ElDrawer, ElDropdown, ElDropdownItem, ElDropdownMenu, ElEmpty, ElFooter, ElForm, ElFormItem, ElHeader, ElIcon, ElImage, ElImageViewer, ElInfiniteScroll, ElInput, ElInputNumber, ElLink, ElLoading, ElMain, ElMenu, ElMenuItem, ElMenuItemGroup, ElMessage, ElMessageBox, ElNotification, ElOption, ElOptionGroup, ElPageHeader, ElPagination, ElPopconfirm, ElPopover, ElPopper, ElProgress, ElRadio, ElRadioButton, ElRadioGroup, ElRate, ElRow, ElScrollbar, ElSelect, ElSlider, ElStep, ElSteps, ElSubmenu, ElSwitch, ElTabPane, ElTable, ElTableColumn, ElTabs, ElTag, ElTimePicker, ElTimeSelect, ElTimeline, ElTimelineItem, ElTooltip, ElTransfer, ElTree, ElUpload, ElVirtualList, ElSpace, ElSkeleton, ElSkeletonItem, version, install, locale, };
    97 | declare const _default: {
ERROR in /Users/lixichen/Documents/GitHub/ikxd-201803-site-pc/node_modules/element-plus/lib/utils/config.d.ts(2,11):
2:11 Cannot find name 'ComponentSize'.
    1 | export interface InstallOptions {
  > 2 |     size: ComponentSize;
      |           ^
    3 |     zIndex: number;
    4 |     locale?: any;
    5 |     i18n?: (...args: any[]) => string;

>>

**Comment by HealerLZH** [comment]
The same error is reported when packing. The project cannot  build

**Comment by andercard** [comment]
I have the same error when running **yarn build**

`node_modules/element-plus/es/components/popover/index.d.ts:193:27 - error TS2694: Namespace '"/Users/anderssonmesa/Desarrollo/yoresuelvo-web/node_modules/element-plus/es/components/index"' has no exported member 'TriggerType'.

193     trigger: import("..").TriggerType;
                              ~~~~~~~~~~~

node_modules/element-plus/es/components/popover/index.d.ts:410:26 - error TS2694: Namespace '"/Users/anderssonmesa/Desarrollo/yoresuelvo-web/node_modules/element-plus/es/components/index"' has no exported member 'Effect'.

410     effect: import("..").Effect;
                             ~~~~~~

node_modules/element-plus/es/components/popover/index.d.ts:426:27 - error TS2694: Namespace '"/Users/anderssonmesa/Desarrollo/yoresuelvo-web/node_modules/element-plus/es/components/index"' has no exported member 'TriggerType'.

426     trigger: import("..").TriggerType;
                              ~~~~~~~~~~~

node_modules/element-plus/es/components/select-v2/src/defaults.d.ts:4:30 - error TS2307: Cannot find module 'element-plus/es/components/popper' or its corresponding type declarations.

4 import type { Options } from 'element-plus/es/components/popper';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/element-plus/es/components/time-picker/src/common/picker.vue.d.ts:2:24 - error TS2307: Cannot find module 'element-plus/es/components/popper' or its corresponding type declarations.

2 import { Effect } from 'element-plus/es/components/popper';
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/element-plus/es/components/tooltip/index.d.ts:173:26 - error TS2694: Namespace '"/Users/anderssonmesa/Desarrollo/yoresuelvo-web/node_modules/element-plus/es/components/index"' has no exported member 'Effect'.

173     effect: import("..").Effect;`

**Comment by xiangqunXiao** [comment]
> 

it works for me. thanks.
