### ISSUE TITLE
[Component] [upload, table] upload、table组件在chrome 72版本中，upload设置属性不生效，table组件种表格数据不显示

### ISSUE THREAD

**Issue by cooooood** [element-plus/element-plus#8770]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 72.0.3636.81/win10`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`
- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/table.html#)

### Steps to reproduce

在chrome 72.0.3636.81版本中打开官方文档就能看到

### What is Expected?

表格数据正常显示，upload组件属性accept、auto-upload等属性设置能生效

### What is actually happening?

实际数据没有在表格中渲染，以及上传组件属性设置未生效

### Additional comments

_(empty)_

**Comment by cooooood** [comment]
upload组件复现情景：chrome 72版本，同一个页面中有多个upload组件时，除了第一个上传组件，下方的上传组件设置属性都会失效

**Comment by vanchain** [comment]
table 在chrome 73版本也无法渲染

**Comment by VinLIan93** [comment]
chrome 71里也不行。从2.2.1开始就有这问题，再之前的版本还没试

**Comment by VinLIan93** [comment]
![截图_选择区域_20220826162446](https://user-images.githubusercontent.com/37412733/186858021-205e6d5b-2785-4758-8c84-84e700368502.png)
chrome 71.0.3578.98

**Comment by tengly** [comment]
upload组件在chrome72版本里action不生效,上传地址成了当前页面的地址,elementPlus官网使用chrome72打开也如此
