### ISSUE TITLE
[Docs] [select] 发现文档 el-select  事件那块文档错误指示

### ISSUE THREAD

**Issue by InfernalAzazel** [element-plus/element-plus#8775]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 103.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/select.html#select-%E5%B1%9E%E6%80%A7)

### Steps to reproduce

观看目前 element-plus code props 即可

    onChange?: ((...args: any[]) => any) | undefined;
    "onUpdate:modelValue"?: ((...args: any[]) => any) | undefined;
    onFocus?: ((...args: any[]) => any) | undefined;
    onBlur?: ((...args: any[]) => any) | undefined;
    onClear?: ((...args: any[]) => any) | undefined;
    "onVisible-change"?: ((...args: any[]) => any) | undefined;
    "onRemove-tag"?: ((...args: any[]) => any) | undefined;

### What is Expected?

code 改动保持同步更新文档

### What is actually happening?

目前属于错误文档指导

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
方便详细描述下你反馈的问题么 0 0

**Comment by InfernalAzazel** [comment]
> 方便详细描述下你反馈的问题么 0 0

注意: 选择蓝色的 code

![Screenshot from 2022-07-12 14-54-02](https://user-images.githubusercontent.com/40333954/178427487-afa2bdce-16e8-4b14-a472-5c0b269cbd7d.png)

官方的文档  el-select 事件 change，实现上我按照官方的 change 选择值被改变时没有任何效果，后面看来一下 code 发现
onChange 才是正解，所以文档没有按照 code 参数更新

以下是正常的，给你对比一下文档

![Screenshot from 2022-07-12 15-00-35](https://user-images.githubusercontent.com/40333954/178428577-44d3addc-b1bf-4a8e-aba2-9fa6d6091488.png)

![Screenshot from 2022-07-12 14-58-12](https://user-images.githubusercontent.com/40333954/178428409-861f9d26-c4ac-4303-bd1e-5de0edc71365.png)

**Comment by chenxch** [comment]
这是编译后生成的类型，你应该要看源代码那边哦，目前这个是否出现影响使用的问题呢

**Comment by InfernalAzazel** [comment]
> 这是编译后生成的类型，你应该要看源代码那边哦，目前这个是否出现影响使用的问题呢

是的, el-select 文档 事件那块 大多事件在前面加上 on, 比如 change ，正确的 onChange .... ， 才有效果。

**Comment by chenxch** [comment]
事件是要@哦

**Comment by InfernalAzazel** [comment]
> 事件是要@哦

看来是我蒙蔽了
