### ISSUE TITLE
[TypeScript] [autocomplete] 使用el-autocomplete组件事件类型报错的问题

### ISSUE THREAD

**Issue by TommyCat008** [element-plus/element-plus#8787]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `100.0.4896.127 (Official Build) (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBMaW5rSXRlbSB7XG4gIHZhbHVlOiBzdHJpbmdcbiAgbGluazogc3RyaW5nXG59XG5cbmNvbnN0IHN0YXRlID0gcmVmKCcnKVxuY29uc3QgbGlua3MgPSByZWY8TGlua0l0ZW1bXT4oW10pXG5jb25zdCBzZWFyY2hUZXh0ID0gcmVmKCcnKTtcbmNvbnN0IHF1ZXJ5U2VhcmNoID0gKHF1ZXJ5U3RyaW5nOiBzdHJpbmcsIGNiKSA9PiB7XG4gIGNvbnN0IHJlc3VsdHMgPSBxdWVyeVN0cmluZ1xuICAgID8gbGlua3MudmFsdWUuZmlsdGVyKGNyZWF0ZUZpbHRlcihxdWVyeVN0cmluZykpXG4gICAgOiBsaW5rcy52YWx1ZVxuICAvLyBjYWxsIGNhbGxiYWNrIGZ1bmN0aW9uIHRvIHJldHVybiBzdWdnZXN0aW9uIG9iamVjdHNcbiAgY2IocmVzdWx0cylcbn1cbmNvbnN0IGNyZWF0ZUZpbHRlciA9IChxdWVyeVN0cmluZykgPT4ge1xuICByZXR1cm4gKHJlc3RhdXJhbnQpID0+IHtcbiAgICByZXR1cm4gKFxuICAgICAgcmVzdGF1cmFudC52YWx1ZS50b0xvd2VyQ2FzZSgpLmluZGV4T2YocXVlcnlTdHJpbmcudG9Mb3dlckNhc2UoKSkgPT09IDBcbiAgICApXG4gIH1cbn1cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICdiYWJlbCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vYmFiZWwvYmFiZWwnIH0sXG4gIF1cbn1cbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtOiB7dmFsdWU6IGFueX0pID0+IHtcbiAgXHRjb25zb2xlLmxvZygnaXRlbScsIGl0ZW0pO1xufVxuICBsaW5rcy52YWx1ZSA9IGxvYWRBbGwoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgICAgIHYtbW9kZWw9XCJzZWFyY2hUZXh0XCJcbiAgICAgICAgOmZldGNoLXN1Z2dlc3Rpb25zPVwicXVlcnlTZWFyY2hcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgICAgOnRlbGVwb3J0ZWQ9XCJmYWxzZVwiXG4gICAgICAgIGNsYXNzPVwic2VhcmNoLWlucHV0XCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXmkJzntKLlhoXlrrlcIlxuICAgICAgICBAc2VsZWN0PVwiaGFuZGxlU2VsZWN0XCJcbiAgICA+XG4gICAgICAgIDx0ZW1wbGF0ZSAjc3VmZml4PlxuICAgICAgICAgICAgPGVsLWljb24gY2xhc3M9XCJlbC1pbnB1dF9faWNvblwiPlxuICAgICAgICAgICAgICAgIDxTZWFyY2ggLz5cbiAgICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwie2l0ZW19XCI+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cIm5hbWVcIiA+5paH5Lu25aS577yae3sgaXRlbS52YWx1ZSB9fTwvc3Bhbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWF1dG9jb21wbGV0ZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在使用el-autocomplete组件选中事件的时候，我因为写了ts，需要在回调函数中对形参item进行类型定义，但是我发现组件中定义的内容是如下结构。
```ts
    ((event: "select", item: {
        value: any;
    }) => void)
```

但是实际上在处理的时候，emit的值却是.value 的值。
具体代码如下：
/node_modules/element-plus/es/components/autocomplete/src/autocomplete2.mjs
144行
```ts
    const handleKeyEnter = async () => {
      if (suggestionVisible.value && highlightedIndex.value >= 0 && highlightedIndex.value < suggestions.value.length) {
        handleSelect(suggestions.value[highlightedIndex.value]);
      } else if (props.selectWhenUnmatched) {
        emit("select", { value: props.modelValue });
        suggestions.value = [];
        highlightedIndex.value = -1;
      }
    };
```

### What is Expected?

我觉得类型定义应该是直接any即可，或者unknown了吧。

### What is actually happening?

实际的行为多包含了一层{value: any}，这一层导致了我ts检查报错了。

### Additional comments

_(empty)_

**Comment by Aobanana-chan** [comment]
一样的issue

**Comment by TommyCat008** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/16837203/201317611-1acf6092-e4ac-4cbb-871a-e67b97972214.png">
定义 Record<string, any>并不能解决问题，会出现如上的问题，建议直接定义为any即可，由业务覆盖类型。

**Comment by TommyCat008** [comment]
@btea

**Comment by tolking** [comment]
vue 组件目前并不能够支持泛型，你的需求目前无法实现。我们需要尽量完善组件库内部类型的推导，不应该使用过多的 `any`。

你可以在 handleSelect 中使用 `as`

**Comment by TommyCat008** [comment]
ok  sure
