### ISSUE TITLE
[Component] [select-v2] Select V2 

### ISSUE THREAD

**Issue by yn-lgting** [element-plus/element-plus#8788]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24gJHtpZHggKyAxfWAsXG4gIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbn0pKVxuXG5jb25zdCBlQmx1ciA9ICgpID0+IHtcblx0RWxNZXNzYWdlLnN1Y2Nlc3MoJ2JsdXInKVxufVxuY29uc3QgZUZvY3VzID0gKCkgPT4ge1xuXHRFbE1lc3NhZ2Uud2FybmluZygnZm9jdXMnKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBAYmx1cj1cImVCbHVyXCJcbiAgICBAZm9jdXM9XCJlRm9jdXNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cImxhcmdlXCIvPlxuPC90ZW1wbGF0ZT5cblxuXG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

选择某一项后没有触发失去焦点事件

### What is Expected?

选择某一项后触发blur事件

### What is actually happening?

选择某一项后 触发执行了focus事件（不选择任何一项时能够成功触发blur）

### Additional comments

感谢查看

**Comment by kooriookami** [comment]
选择选项是不会触发blur的，只有整个select失焦才会
