### ISSUE TITLE
[Component] [table-v2] 虚拟表格增加数据时，内存占用激增（Virtualized Table）

### ISSUE THREAD

**Issue by BigJJing** [element-plus/element-plus#8789]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ3h4eCcpXG5jb25zdCBjb2x1bW5zID0gW1xuICB7XG4gICAga2V5OiBcImlkXCIsXG4gICAgZGF0YUtleTogXCJpZFwiLFxuICAgIHRpdGxlOiBcImlkXCIsXG4gICAgd2lkdGg6IDEwMFxuICB9LFxuICB7XG4gICAga2V5OiBcIm5hbWVcIixcbiAgICBkYXRhS2V5OiBcIm5hbWVcIixcbiAgICB0aXRsZTogXCJuYW1lXCIsXG4gICAgd2lkdGg6IDEwMFxuICB9LFxuXVxuY29uc3QgdGFibGVEYXRhU2hvdyA9IHJlZihbXSlcbmNvbnN0IGFkZCA9IChmdW5jdGlvbiAoKSB7XG4gIGxldCB0aW1lciA9IG51bGw7XG4gIGxldCBpID0gMDtcbiAgcmV0dXJuIGZ1bmN0aW9uKCl7XG4gICAgdGltZXIgPSBzZXRJbnRlcnZhbCgoKSA9PiB7XG4gICAgICBjb25zdCBkYXRhID0ge1xuICAgICAgICBpZDogKytpLFxuICAgICAgICBuYW1lOiBcIm5hbWVcIiArIGlcbiAgICAgIH1cbiAgICAgIHRhYmxlRGF0YVNob3cudmFsdWUudW5zaGlmdChkYXRhKVxuICAgIH0sIDEwMCk7XG4gIH1cbn0pKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIFx0PGJ1dHRvbiBAY2xpY2s9XCJhZGRcIj5hZGQ8L2J1dHRvbj5cbiAgICA8ZWwtdGFibGUtdjJcbiAgICAgIDpjb2x1bW5zPVwiY29sdW1uc1wiXG4gICAgICA6ZGF0YT1cInRhYmxlRGF0YVNob3dcIlxuICAgICAgOndpZHRoPVwiNzAwXCJcbiAgICAgIDpoZWlnaHQ9XCI0MDBcIlxuICAgICAgZml4ZWRcbiAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击add按钮，占用内存激增

### What is Expected?

使用table组件时，就不会这样，希望解释一下为什么，并修复

### What is actually happening?

占用内存激增，2w条的时候浏览器崩溃

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
It seems to have nothing to do with element plus.  I guess you installed `vue.js devtools` plugin. Try  disabling the plugin or newing a incognito tab, then checking the reproduction again.

**Comment by xiaoxian521** [comment]
> It seems to have nothing to do with element plus. I guess you installed `vue.js devtools` extension. Try disabling the extension or newing an incognito tab, then checking the reproduction again.

i think so
