### ISSUE TITLE
当rules和层级form同时存在时会导致undefined

### ISSUE THREAD

**Issue by piexlmax** [element-plus/element-plus#879]
代码如下
```
<template>
  <div class="home">
    <el-form :model="form" :rules="rules">
      <el-form-item label="test" prop="test.a">
        <el-input v-model="form.test.a"></el-input>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>
export default {
    data() {
      return {
         form: {
          test:{
            a:123
          }
        },
        rules:{
          "test.a":[ { required: true, message: '年龄不能为空' },
          { type: 'number', message: '年龄必须为数字值' },]
        }
      };
    }
  }
</script>
```
 本代码在element v2版本中可用
如果将 rules中的内容作为行内验证，也不会产生报错。
这边疑惑的是，在plus中是不支持这种写法了呢，还是存在bug

**Comment by JeremyWuuuuu** [comment]
> 代码如下
> 
> ```
> <template>
>   <div class="home">
>     <el-form :model="form" :rules="rules">
>       <el-form-item label="test" prop="test.a">
>         <el-input v-model="form.test.a"></el-input>
>       </el-form-item>
>     </el-form>
>   </div>
> </template>
> 
> <script>
> export default {
>     data() {
>       return {
>          form: {
>           test:{
>             a:123
>           }
>         },
>         rules:{
>           "test.a":[ { required: true, message: '年龄不能为空' },
>           { type: 'number', message: '年龄必须为数字值' },]
>         }
>       };
>     }
>   }
> </script>
> ```
> 
> 本代码在element v2版本中可用
> 如果将 rules中的内容作为行内验证，也不会产生报错。
> 这边疑惑的是，在plus中是不支持这种写法了呢，还是存在bug

Perhaps bug I think, cc @HerringtonDarkholme
