### ISSUE TITLE
[Component] [message] ElMessage close error

### ISSUE THREAD

**Issue by StephenKe** [element-plus/element-plus#8796]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.8`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'`
- Build Tool: `Vue CLI`

### Related Component

- `el-message`

### Reproduction Link

[Link]()

### Steps to reproduce

`ElMessage.error('主要信息页签存在必填项未填写或格式不正确，请检查')`

### What is Expected?

Auto Close

### What is actually happening?

Cannot close and throw error

### Additional comments

All ElMessage close will throw error in my pro

![image](https://user-images.githubusercontent.com/22910740/178635923-62c3c8a6-9ecb-41eb-a586-eaa39ab1a030.png)
![image](https://user-images.githubusercontent.com/22910740/178635944-b18f11ce-493f-4b42-b921-2d53713cc41e.png)

**Comment by StephenKe** [comment]
It happened in my pro and I cannot recurrent it.

**Comment by StephenKe** [comment]
In method.ts `vm.exposeProxy` can possible get null.And I fixed it like #8797 in my pro.

**Comment by jiahui336** [comment]
咋修改的

**Comment by hackycy** [comment]
复现步骤：
已测试在指定 vue `3.2.25`-`3.2.31`版本是能够直接复现该bug。与element-plus版本无关。

目前排查不是`element-plus`组件的原因，是vue在综上提到的版本`transtion`组件存在问题，而ElMessage组件是用到了`transition`组件。

使用vue `3.2.32`后续版本测试可以修复。

**Comment by weiguanglai** [comment]
我今天也遇到了这个问题，就是这种提示框，自动关闭的时候会报错。6月3号下载的那版依赖包没有问题，今天如果重新下载依赖包就会报这个错.

**Comment by StephenKe** [comment]
> 复现步骤： 已测试在指定 vue `3.2.25`-`3.2.31`版本是能够直接复现该bug。与element-plus版本无关。
> 
> 目前排查不是`element-plus`组件的原因，是vue在综上提到的版本`transtion`组件存在问题，而ElMessage组件是用到了`transition`组件。
> 
> 使用vue `3.2.32`后续版本测试可以修复。

Vue version higher than `3.2.32` can fix this issue.But if element-plus should remind it on docs？ @iamkun

**Comment by zhangxuewei1263944101** [comment]
我在vue 3.2.8 也遇到了这个问题，该怎么解决？element-plus 2.2.12，求助各位大佬
