### ISSUE TITLE
[i18n] [config-provider] 全局配置对于二次封装的组件库不生效

### ISSUE THREAD

**Issue by Tiramisupxl** [element-plus/element-plus#8798]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-config-provider`

### Steps to reproduce

基于element-plus二次封装了自己的组件库，在项目里配置国际化，使用element-plusV2.0的版本是没有问题的，但是升级到V2.2.9后,项目里配置国际化仅对该项目的element-plus组件有效，对于引入的基于element-plus二次封装组件库无效。

### What is Expected?

国际化对引入的二次封装组件库有效

### What is actually happening?

国际化对引入的二次封装组件库无效

### Additional comments

_(empty)_

**Comment by tolking** [comment]
link #8644
