### ISSUE TITLE
[Component] [input-number] el-input-number  Number may not change with each click “+”.

### ISSUE THREAD

**Issue by fullmooooon** [element-plus/element-plus#8801]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBudW1iZXIxID0gcmVmKDApXG5jb25zdCBudW1iZXIyID0gcmVmKDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1iZXIxXCIgQGNsaWNrPVwibnVtYmVyMisrXCI+PC9lbC1pbnB1dC1udW1iZXI+XG4gIDxici8+e3tudW1iZXIyfX1cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click “+” dozens of times

### What is Expected?

The number and number of clicks are the same

### What is actually happening?

The number and the number of clicks are different.

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/43309591/178661431-d3ae20ba-8bd7-46cb-bd80-3bb99fad11b1.png)

**Comment by holazz** [comment]
Design so. The `increase` and `decrease` are handled internally by the [`RepeatClick`](https://github.com/element-plus/element-plus/blob/006cc3dc2465aa465103b3ee9c2f2b897f574dc5/packages/directives/repeat-click/index.ts#L13) directive.

**Comment by fullmooooon** [comment]
> Design so. The `increase` and `decrease` are handled internally by the [`RepeatClick`](https://github.com/element-plus/element-plus/blob/006cc3dc2465aa465103b3ee9c2f2b897f574dc5/packages/directives/repeat-click/index.ts#L13) directive.

In fact, it has a very strange experience.
It's normal for me to click, but it was prevented.
Even my first add click maybe fail.
The first click is definitely not a repeat click, but it still fails
![image](https://user-images.githubusercontent.com/43309591/178944492-4e4eace7-9a6a-48b0-8fc2-158a8362f5fe.png)


Sorry, I don't understand how "repeattick" code works after more than ten minutes of thinking.
But I still think there may be some mistakes

**Comment by holazz** [comment]
英文可能表述的不太清楚，我再用中文解释一遍：

`RepeatClick` 内部监听了鼠标的 `mousedown` 和 `mouseup` 事件，`mousedown` 中注册了一个定时器，每隔100ms执行一次handler（`increase` 或 `decrease`），`mouseup` 中做了清除定时器的操作。

- 如果按下 “+” 不松开鼠标，数字会每隔100ms增加1直到松开鼠标。

```ts
on(el, 'mousedown', (e: MouseEvent) => {
  // ...
  clearInterval(interval)
  interval = setInterval(handler, 100)
})
```

就会出现这种情况（这是正常的）：

<img width="408" alt="WX20220714-204840@2x" src="https://user-images.githubusercontent.com/23100055/178996644-0497cb48-db26-41ac-80e1-ad6f4802cd2a.png">

- 当鼠标按下到松开的时间间隔小于100ms时，我们需要在 `mouseup` 中执行一次 handler（因为 `mouseup` 中清除了定时器，而定时器中的 handler 将在100ms之后第一次执行，所以定时器里的 handler 并不会被执行）

```ts
const clear = () => {
  if (Date.now() - startTime < 100) {
    handler()
  }
  clearInterval(interval)
  interval = null
}
```

由于 JavaScript 的事件循环机制，setInterval 并不总是按时执行。

夸张一点来说，当你鼠标按下到松开时间间隔是110ms，定时器中的handler可能在第120ms的时候才会执行，但是在第110ms的时候就已经清除了定时器，所以 handler 一次都没被有执行。就会出现这种情况（这可能是一个bug）：

![178944492-4e4eace7-9a6a-48b0-8fc2-158a8362f5fe](https://user-images.githubusercontent.com/23100055/178997937-79b14a80-d8c9-48f5-8cb9-9c4a0525a0ec.png)
