### ISSUE TITLE
[Component] [tree-select] treeSelect选中数据丢失

### ISSUE THREAD

**Issue by hyf-hub** [element-plus/element-plus#8803]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 103.0.5060.114`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICBzaG93IGNoZWNrYm94OlxuICA8ZWwtdHJlZS1zZWxlY3RcbiAgICByZWY9XCJ0cmVlUmVmXCJcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOnJlbmRlci1hZnRlci1leHBhbmQ9XCJmYWxzZVwiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIG5vZGUta2V5PVwidmFsdWVcIlxuICAvPlxuICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPnNldCBieSBrZXk8L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdHJlZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVHJlZVNlbGVjdD4+KClcbmNvbnN0IHZhbHVlID0gcmVmKClcbmNvbnN0IHNldENoZWNrZWRLZXlzID0oKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLnNldENoZWNrZWRLZXlzKFtcIjEtMS0xXCJdLCBmYWxzZSlcbn1cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICB2YWx1ZTogJzEnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMS0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJzInLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnMi0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJzItMS0xJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJzItMicsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICcyLTItMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICczJyxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJzMtMScsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICczLTEtMScsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICczLTInLFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnMy0yLTEnLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击 "set by key" 按钮后 'Level two 1-1'被选中，再使用鼠标去点击未被选中的元素后。'Level two 1-1'的选中效果就丢失了。 

### What is Expected?

仍然保持 'Level two 1-1'的选中效果

### What is actually happening?

'Level two 1-1'的选中效果丢失了

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这个是正常表现吧。。不然使用一次setCheckedKeys之后所有选项就都不能选了

**Comment by hyf-hub** [comment]
> 这个是正常表现吧。。不然使用一次setCheckedKeys之后所有选项就都不能选了

你好，请问我该如何维持两种情况下的选中状态呢。就是我使用了“setCheckedKeys”后再点击其他的选项仍然能够保存“setCheckedKeys”的选中效果呢

**Comment by chenxch** [comment]
你应该是要开启多选模式吧

**Comment by hyf-hub** [comment]
> 

抱歉 上面我忘记开多选了。实际上就算我开了多选，这个问题仍然存在 操作方式：先鼠标选中tree-select上的节点，再点击“set by key”后，之前鼠标选中的效果就丢失了，即使我使用 "getCurrentKey"获取节点，也没有之前用鼠标选中的那个节点。而且使用“setCheckedKeys”方法选中的节点，无法在input的输入框内看到

**Comment by hyf-hub** [comment]
> 你应该是要开启多选模式吧

抱歉 上面我忘记开多选了。实际上就算我开了多选，这个问题仍然存在 操作方式：先鼠标选中tree-select上的节点，再点击“set by key”后，之前鼠标选中的效果就丢失了，即使我使用 "getCurrentKey"获取节点，也没有之前用鼠标选中的那个节点。而且使用“setCheckedKeys”方法选中的节点，无法在input的输入框内看到

**Comment by chenxch** [comment]
先鼠标选中tree-select上的节点，再点击“set by key”后，之前鼠标选中的效果就丢失了
》这个你可以要在看看API的解释，setCheckedKeys他是一个覆盖动作，不是一个add类型的操作
使用“setCheckedKeys”方法选中的节点，无法在input的输入框内看到
》这个由于setCheckedKeys目前只直接调用tree的API，还需要手动设置下value哦（这个可能需要讨论在要不要然treeselect去统筹处理）

**Comment by hyf-hub** [comment]
> 

好的 谢谢大佬

**Comment by hyf-hub** [comment]
> 先鼠标选中tree-select上的节点，再点击“set by key”后，之前鼠标选中的效果就丢失了 》这个你可以要在看看API的解释，setCheckedKeys他是一个覆盖动作，不是一个add类型的操作 使用“setCheckedKeys”方法选中的节点，无法在input的输入框内看到 》这个由于setCheckedKeys目前只直接调用tree的API，还需要手动设置下value哦（这个可能需要讨论在要不要然treeselect去统筹处理）

好的 谢谢大佬
