### ISSUE TITLE
[Component] [carousel, carousel-item] carousel-item多内容， initial-index设置无效，怎么解决

### ISSUE THREAD

**Issue by zyh-akk** [element-plus/element-plus#8805]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome100  windows11`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/s2t4ge6f/)

### Steps to reproduce

v-for循环出了el-carousel-itemm,
el-carousel-item里面包括了div，
div里面包含了很多div等内容,
浏览器的表现行为就是所有的item项都重叠在了一起，走马灯没生效

### What is Expected?

initial-index为0，展示第一页的数据

### What is actually happening?

所有的carousel-item实际都展示出来了，并出现了覆盖

### Additional comments

_(empty)_

**Comment by btea** [comment]
Can you provide a demo on [here](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)?

**Comment by HeftyKoo** [comment]
这个issue没有提供可执行的复现demo，并且已经很久没有活跃了，我先暂时关闭了，如果还有问题，可以再提新的issue。
