### ISSUE TITLE
[Component] [message-box] ElMessageBox的autofocus属性默认true，导致确认按钮默认是灰蓝色，希望提供全局设置ElMessageBox内置属性的方法

### ISSUE THREAD

**Issue by Archmage83** [element-plus/element-plus#8806]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114`
- Build Tool: `Vue CLI`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHNob3dNZXNzYWdlID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybShcIuaPkOekuuaWh+Wtl1wiLCBcIuagh+mimFwiLCB7XG4gICAgY2FsbGJhY2sodmFsdWUpIHtcbiAgICAgIFxuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzaG93TWVzc2FnZVwiPuW8ueWHuuehruiupOahhjwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

elmessagebox弹出的时候，因为autofocus属性，确认按钮是focus状态，容易让用户以为是disabled状态不能点击。希望能提供一个全局配置elmessagebox的autofocus属性的方式，不然需要每个elmessagebox都添加autofocus:false属性较为麻烦

### What is Expected?

全局设置elmessagebox的内置属性

### What is actually happening?

目前只能局部设置

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
#8811

**Comment by wp993080086** [comment]
`
import {
  ElMessage,
  ElMessageBox,
  ElNotification,
  MessageOptions,
  ElMessageBoxOptions,
  NotificationParams
} from 'element-plus'

/**
 * toast轻提示
 * @param {String} message
 * @param {MessageOptions} option
 */
export const Toast = (message: string, option: MessageOptions = {}) => {
  return ElMessage({
    message,
    showClose: true,
    grouping: true,
    duration: 2000,
    offset: 50,
    customClass: 'iot_toast_node',
    ...option
  })
}
/**
 * alert提示框
 * @param {String} message
 * @param {ElMessageBoxOptions} config
 */
export const Alert = (message: string, config: ElMessageBoxOptions = {}) => {
  const defaultOption = {
    title: '温馨提示',
    closeOnClickModal: false,
    closeOnPressEscape: false,
    confirmButtonText: '确认',
    draggable: true,
    customClass: `${config.customClass || ''} iot_messagebox`
  }
  const option = { ...defaultOption, ...config }
  return ElMessageBox.alert(message, option)
}
/**
 * confirm确认框
 * @param {String} message
 * @param {ElMessageBoxOptions} config
 */
export const Confirm = (message: string, config: ElMessageBoxOptions = {}) => {
  const defaultOption = {
    title: '温馨提示',
    closeOnClickModal: false,
    closeOnPressEscape: false,
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    draggable: true,
    autofocus: false,
    customClass: `${config.customClass || ''} iot_messagebox`,
    cancelButtonClass: `${config.cancelButtonClass || ''} is_plain`
  }
  const option = { ...defaultOption, ...config }
  return ElMessageBox.confirm(message, option)
}
/**
 * notification通知
 * @param {NotificationParams} option
 */
export const Notification = (option: NotificationParams = {}) => {
  return ElNotification(option)
}

`

> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.2.37`
> * Element Plus Version: `2.2.9`
> * Browser / OS: `chrome 103.0.5060.114`
> * Build Tool: `Vue CLI`
> 
> ## Reproduction
> ### Related Component
> * `el-message-box`
> 
> ### Reproduction Link
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHNob3dNZXNzYWdlID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3guY29uZmlybShcIuaPkOekuuaWh+Wtl1wiLCBcIuagh+mimFwiLCB7XG4gICAgY2FsbGJhY2sodmFsdWUpIHtcbiAgICAgIFxuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJzaG93TWVzc2FnZVwiPuW8ueWHuuehruiupOahhjwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> ### Steps to reproduce
> elmessagebox弹出的时候，因为autofocus属性，确认按钮是focus状态，容易让用户以为是disabled状态不能点击。希望能提供一个全局配置elmessagebox的autofocus属性的方式，不然需要每个elmessagebox都添加autofocus:false属性较为麻烦
> 
> ### What is Expected?
> 全局设置elmessagebox的内置属性
> 
> ### What is actually happening?
> 目前只能局部设置
> 
> ### Additional comments
> _(empty)_
