### ISSUE TITLE
[Component] [input-number] In Safari,clear input box, become heighter of then control Buttons

### ISSUE THREAD

**Issue by Tsong-LC** [element-plus/element-plus#8807]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/en-US/component/input-number.html)

### Steps to reproduce

1、Clear input box

### What is Expected?

1、Height is constant

### What is actually happening?

1、Height is heighter

### Additional comments

_(empty)_

<img width="815" alt="image" src="https://user-images.githubusercontent.com/50739490/178696546-d8f675f9-116a-4a41-90e3-58f9bf55c174.png">

**Comment by holazz** [comment]
Can't reproduce. 🤔
<img width="500" alt="WX20220713-175539@2x" src="https://user-images.githubusercontent.com/23100055/178706623-63992cd4-a811-49cc-b97d-f676cde6eb4b.png">

**Comment by Tsong-LC** [comment]
https://user-images.githubusercontent.com/50739490/178714398-f180e2db-8fbe-49a7-87c9-14e6f81f4803.mov
@holazz

**Comment by holazz** [comment]
> [user-images.githubusercontent.com/50739490/178714398-f180e2db-8fbe-49a7-87c9-14e6f81f4803.mov](https://user-images.githubusercontent.com/50739490/178714398-f180e2db-8fbe-49a7-87c9-14e6f81f4803.mov) @holazz

Not sure what caused it, this issue doesn't occur in my Safari.
