### ISSUE TITLE
select组件，列表切换问题

### ISSUE THREAD

**Issue by gramers** [element-plus/element-plus#881]
![5ad457e745e2bfe69e4c0305ae13ac9](https://user-images.githubusercontent.com/28006607/101445486-8d941a00-395c-11eb-9d1e-5cd641b60a84.png)
![08fb626dfc88b0f5f0c31292400a5ac](https://user-images.githubusercontent.com/28006607/101445489-8f5ddd80-395c-11eb-9496-a258e3b416fd.png)

**Comment by JeremyWuuuuu** [comment]
This issue came from `Vue` itself, instead of us, you need to make sure that your `Vue` version is fixed in `3.0.3`, you will only get this error in `3.0.4` it will be fixed in `3.0.5`. Please refer to https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8
