### ISSUE TITLE
[Component] [upload] clearFiles() would not truely drop aborting filelist data but removes dom element

### ISSUE THREAD

**Issue by Ryuuki6602** [element-plus/element-plus#8815]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgRWxOb3RpZmljYXRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnICBcbiAgXG5jb25zdCB1cGxvYWRSZWYgPSByZWYobnVsbClcbmNvbnN0IGhhbmRsZUV4Y2VlZCA9IChmaWxlcykgPT4ge1xuICBFbE5vdGlmaWNhdGlvbih7XG4gICAgdGl0bGU6ICdGaWxlIENvdW50IEV4Y2VlZGVkJyxcbiAgICBtZXNzYWdlOiBgMSBmaWxlIG9ubHnvvIxhbm90aGVyICR7ZmlsZXMubGVuZ3RofSBmaWxlcyBleGNlZWQgdGhlIGxpbWl0YCxcbiAgICBncm91cGluZzogdHJ1ZSxcbiAgICB0eXBlOiAnZXJyb3InLFxuICAgIGR1cmF0aW9uOiA1MDAwLFxuICAgIHBvc2l0aW9uOiAnYm90dG9tLWxlZnQnXG4gIH0pXG59XG5jb25zdCBkcm9wVXBsb2FkRmlsZUxpc3QgPSAoKSA9PiB7XG4gIHVwbG9hZFJlZi52YWx1ZS5jbGVhckZpbGVzKClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIFx0XHRcdFx0XHRcdFx0XHRcdDxlbC11cGxvYWRcbiAgICAgICAgICAgICAgICAgICAgICBjbGFzcz1cInctMTAwYlwiXG4gICAgICAgICAgICAgICAgICAgICAgZHJhZ1xuICAgICAgICAgICAgICAgICAgICAgIG11bHRpcGxlXG4gICAgICAgICAgICAgICAgICAgICAgYWN0aW9uPVwiZmFrZVwiXG4gICAgICAgICAgICAgICAgICAgICAgcmVmPVwidXBsb2FkUmVmXCJcbiAgICAgICAgICAgICAgICAgICAgICA6YXV0by11cGxvYWQ9XCJmYWxzZVwiXG4gICAgICAgICAgICAgICAgICAgICAgOmxpbWl0PVwiMVwiXG4gICAgICAgICAgICAgICAgICAgICAgOm9uLWV4Y2VlZD1cImhhbmRsZUV4Y2VlZFwiXG4gICAgICAgICAgICAgICAgICAgID5cbiAgICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICBjbGFzcz1cImktYW50LWRlc2lnbi1jbG91ZC11cGxvYWQtb3V0bGluZWQgdGV4dC1zaXplLVs1cmVtXSBhbGwtY2VudGVyIHctMTAwYlwiXG4gICAgICAgICAgICAgICAgICAgICAgPjwvZGl2PlxuICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RleHRcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIGRyYWcgeW91ciBmaWxlcyBoZXJlIG9yIDxlbT4gY2xpY2sgdG8gdXBsb2FkPC9lbT5cbiAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGUgI3RpcD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJlbC11cGxvYWRfX3RpcFwiIHN0eWxlPVwiZGlzcGxheTogZmxleDsganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJvcGFjaXR5OiAwLjdcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIENvbXByZXNzIGZpbGVzIGFyZSByZWNvbW1lbmRlZCB3aGVuIHRoZSBmaWxlc2l6ZSBleGNlZWRzIDEgTUIuXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPmxpbWl077yaPHN0cm9uZz41PC9zdHJvbmc+PC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgQGNsaWNrPVwiZHJvcFVwbG9hZEZpbGVMaXN0XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICBUcnVuY2F0ZVxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICAgICAgICAgIDwvZWwtdXBsb2FkPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

-- Select first file
-- Click [Truncate] button
-- Select second file
-- Error occurred

### What is Expected?

-- clearFiles() would truely truncate filelist data instead of dom element
-- The following file selections would not exceed the limit

### What is actually happening?

-- clearFiles() removes dom element
-- The following each file selection exceeds the limit

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Need to traverse `abort`.

**Comment by Ryuuki6602** [comment]
> Need to traverse `abort`.

Understand it, thanks!

**Comment by chenxch** [comment]
Hi, is the problem solved?

**Comment by Ryuuki6602** [comment]
> Hi, is the problem solved?

No, I still have no idea
