### ISSUE TITLE
[Component] [input-number] el-input-number可以输入特殊字符，还不会报错

### ISSUE THREAD

**Issue by ZinLiao** [element-plus/element-plus#8816]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.8`
- Browser / OS: `window10`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJudW1cIiA6bWluPVwiMVwiIDptYXg9XCIxMFwiIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbnVtID0gcmVmKDEpXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAodmFsdWU6IG51bWJlcikgPT4ge1xuICBjb25zb2xlLmxvZyh2YWx1ZSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

直接在数字框内输入特殊字符，比如 - , | 等等

### What is Expected?

只能输入数字

### What is actually happening?

除了中文，都可以输入

### Additional comments

_(empty)_

**Comment by wzrove** [comment]
自己做个正则校验，允许它输入，给提示就行。

**Comment by holazz** [comment]
这个组件内部使用的是原生的 `<input type="number" />`，有可能是你使用的浏览器不支持 `type="number"`。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number

**Comment by ZinLiao** [comment]
> 

除非你们不兼容chrome
elementUI都是正常剔除特殊字符的，在你们官网提供的demo环境就能测出差距

**Comment by ZinLiao** [comment]
> 这个组件内部使用的是原生的 `<input type="number" />`，有可能是你使用的浏览器不支持 `type="number"`。 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number

并不存在，我在win和mac下都用chrome，输入- 不会剔除，中文和其它字符倒是剔除了

**Comment by holazz** [comment]
`-` 是负号，是合法的字符(-1, -2, ....)，所以可以输入。`e` 也是。

**Comment by ZinLiao** [comment]
> `-` 是负号，是合法的字符(-1, -2, ....)，所以可以输入。`e` 也是。

但是如果设置min为>= 0的呢，难道还是合法？而且 连 1-2这种，应该属于非法输入

**Comment by holazz** [comment]
目前这个和原生的 input 表现一致，你可以试试 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number#try_it) 上的这个例子。如果要限制输入的话你可能需要 js 控制一下。
