### ISSUE TITLE
[Component] [pagination] el-pagination样式问题

### ISSUE THREAD

**Issue by kirby202111** [element-plus/element-plus#8821]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome/103.0.5060.114`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxlbC1wYWdpbmF0aW9uXG4gICAgc3R5bGU9XCJ0ZXh0LWFsaWduIDogY2VudGVyO1wiXG4gICAgYmFja2dyb3VuZFxuICAgIGxheW91dD1cInByZXYsIHBhZ2VyLCBuZXh0XCJcbiAgICA6dG90YWw9XCIyMVwiXG4gID5cbiAgPC9lbC1wYWdpbmF0aW9uPlxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

输入样式style="text-align : center;"
input style="text-align : center;"

### What is Expected?

分页组件显示在页面正中间
pagination display in the center of the page

### What is actually happening?

分页组件依旧显示在页面左边
pagination display in the left of the page

### Additional comments

_(empty)_

**Comment by kirby202111** [comment]
同时,我在vue的main.js中使用app.use(ElementPlus,{size:"small"});   
这个size:"small"对el-pagination组件并未生效
meanwhile,when I use app.use(ElementPlus,{size:"small"});   in main.js
size:"small" has no use for el-pagination

**Comment by chenxch** [comment]
1. 没有居中是你样式使用方式不对哦，你可以看`el-pagination`的样式是`display:flex`，flex的居中要用`justify-content: center;`
2. 文档要看一下，`el-pagination`的小尺寸属性是`small: true`而不是`size: small`,这个文档还是要看一下，目前全局配置还没有支持small。
