### ISSUE TITLE
[Component] [tooltip, input] tooltips 中嵌套 el-input ，当点击 tooltips 中content后 ；再次点击input时不能获取焦点

### ISSUE THREAD

**Issue by xukaishan** [element-plus/element-plus#8824]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgdi1tb2RlbDp2aXNpYmxlPVwidmlzaWJsZVZhbFwiXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgY29udGVudD1cIlRvcCBMZWZ0IHByb21wdHMgaW5mb1wiXG4gICAgICAgcGxhY2VtZW50PVwiYm90dG9tLXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPHRlbXBsYXRlICNjb250ZW50PlxuICAgICAgICAgICAgPGRpdj5cbiAgICAgICAgICAgICAgICA8cCBjbGFzcz1cImVsLXNlbGVjdC1kcm9wZG93bl9fZW1wdHlcIj5cbiAgICAgICAgICAgICAgICAgICAg5pqC5peg5pWw5o2uXG4gICAgICAgICAgICAgICAgPC9wPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgICAgIDxlbC1pbnB1dFxuICAgICAgICAgICAgICAgIHJlZj1cImlucFJlZlwiXG4gICAgICAgICAgICAgICAgdi1tb2RlbC50cmltPVwidmFsdWVcIlxuICAgICAgXHRcdFx0ICAgIEBmb2N1cz1cImZvY3VzSGFuZGxlXCJcbiAgICAgICAgICAgID5cbiAgICAgICAgICAgIDwvZWwtaW5wdXQ+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8L2VsLXRvb2x0aXA+XG5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoKTtcbmNvbnN0IHZpc2libGVWYWwgPSByZWYoZmFsc2UpO1xuY29uc3QgZm9jdXNIYW5kbGUgPSAoKSA9PiB7XG4gICAgdmlzaWJsZVZhbC52YWx1ZSA9IHRydWU7XG59O1xuPC9zY3JpcHQ+XG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.点击input
2.点击tooltips content插槽内容
3.再次点击input 此时不能聚焦 （点击外面其他区域后再次点击input则可以）

### What is Expected?

能再次获取input焦点

### What is actually happening?

获取焦点后立即失焦

### Additional comments

_(empty)_

**Comment by ayuan-gy** [comment]
**这个情况会出现在所有focusable的元素上**
哪些元素是focusable 元素？
window：当页面窗口从隐藏变成前置可见时，focus 事件就会触发
表单元素(form controllers)：input/option/textarea/button
链接元素(links)：a标签、area标签（必须要带 href 属性，包括 href 属性为空）
设置了 tabindex 属性（tabindex 值非-1）的元素
设置了contenteditable = "true"属性的元素

**Comment by ayuan-gy** [comment]
**点击tootip-content外的元素会触发这个onFocusOut事件，而触发事件的event除了focusable的元素，e都会是null**
![image](https://user-images.githubusercontent.com/82928935/179000706-eaea86f4-f760-4edf-b33d-a81d0572661b.png)
null会导致**!isNil(relatedTarget)**结果是false而不进入if分支，如果进入,定时器的tryFocus事件会将焦点设置回tootip-content，我不理解他这块为什么要这样做emm

**Comment by baiwusanyu-c** [comment]
Your use of this method does not conform to the usage specification of tooltip. In fact, the official documentation has stated that the tooltip component does not support wrapping form elements.
![image](https://user-images.githubusercontent.com/32354856/179178134-30a15907-0c86-465a-8b60-5be2440d0b3c.png)

**Comment by HeftyKoo** [comment]
这个应该在 v2.2.18 修复了，这个 issue 先关了，后面如果还有问题，欢迎再重新开一个 issue

https://github.com/element-plus/element-plus/pull/10076
