### ISSUE TITLE
[Component] [message-box] MessageBox组件打开后，确认按钮默认是被选中的

### ISSUE THREAD

**Issue by Jinzm** [element-plus/element-plus#8830]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html)

### Steps to reproduce

https://element-plus.gitee.io/zh-CN/component/message-box.html

### What is Expected?

确定按钮默认不是选中的状态

### What is actually happening?

确定按钮被选中了

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
#8811 参考这里，autofocus 默认是true
