### ISSUE TITLE
[Component] [time-picker] timePicker无法清空

### ISSUE THREAD

**Issue by Jinzm** [element-plus/element-plus#8831]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/time-picker.html#%E4%BB%BB%E6%84%8F%E6%97%B6%E9%97%B4%E8%8C%83%E5%9B%B4)

### Steps to reproduce

带有arrow-control 可以点击右侧清空
没有arrow-control 点击清空无效

### What is Expected?

可以实现清空

### What is actually happening?

没有设置arrow-control属性时不能清空

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
问题是因为内置了一个默认值，导致focus 的时候滚动了触发了一个input 事件，我看下我能不能提个pr
