### ISSUE TITLE
[Component] [ input-number ]: Sometimes it takes multiple clicks to trigger an action

### ISSUE THREAD

**Issue by Snoopy-Li** [element-plus/element-plus#8834]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49`
- Build Tool: `CDN`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/input-number.html)

### Steps to reproduce

Just click the plus button of input-number on your official page, you will find that sometimes it takes multiple clicks to trigger an action

### What is Expected?

one click, one action

### What is actually happening?

multiple clicks, one action, sometimes

### Additional comments

_(empty)_

**Comment by holazz** [comment]
This [PR](https://github.com/element-plus/element-plus/pull/8828) to fix it.
