### ISSUE TITLE
[TypeScript] [table] el-table span-method type check error

### ISSUE THREAD

**Issue by yanllllk** [element-plus/element-plus#8837]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `edge`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html#%E5%90%88%E5%B9%B6%E8%A1%8C%E6%88%96%E5%88%97)

### Steps to reproduce

按官网说明
合并行或列时,指定span-method 
const objectSpanMethod = ({
  row,
  column,
  rowIndex,
  columnIndex,
}: SpanMethodProps) => {
  if (columnIndex === 0) {
    if (rowIndex % 2 === 0) {
      return {
        rowspan: 2,
        colspan: 1,
      }
    } else {
      return {
        rowspan: 0,
        colspan: 0,
      }
    }
  }
}

结果 ts 报类型错误
不能将类型“({ rowIndex, columnIndex }: SpanMethodProps) => number[] | undefined”分配给类型“(data: { row: any; rowIndex: number; column: TableColumnCtx<any>; columnIndex: number; }) => number[] | { rowspan: number; colspan: number; }”。
  不能将类型“number[] | undefined”分配给类型“number[] | { rowspan: number; colspan: number; }”。ts(2322)

### What is Expected?

no type check error

### What is actually happening?

不能将类型“({ rowIndex, columnIndex }: SpanMethodProps) => number[] | undefined”分配给类型“(data: { row: any; rowIndex: number; column: TableColumnCtx<any>; columnIndex: number; }) => number[] | { rowspan: number; colspan: number; }”。
  不能将类型“number[] | undefined”分配给类型“number[] | { rowspan: number; colspan: number; }”。ts(2322)

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
try [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgOnNwYW4tbWV0aG9kPVwiYXJyYXlTcGFuTWV0aG9kXCJcbiAgICAgIGJvcmRlclxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQxXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQyXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgMlwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgc29ydGFibGUgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gICAgPC9lbC10YWJsZT5cblxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgOnNwYW4tbWV0aG9kPVwib2JqZWN0U3Bhbk1ldGhvZFwiXG4gICAgICBib3JkZXJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCU7IG1hcmdpbi10b3A6IDIwcHhcIlxuICAgID5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MlwiIGxhYmVsPVwiQW1vdW50IDJcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50M1wiIGxhYmVsPVwiQW1vdW50IDNcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIHsgVGFibGVDb2x1bW5DdHggfSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90YWJsZS9zcmMvdGFibGUtY29sdW1uL2RlZmF1bHRzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxudHlwZSBTcGFuTWV0aG9kUmV0dXJuID0gbnVtYmVyW10gfCB7IHJvd3NwYW46IG51bWJlcjsgY29sc3BhbjogbnVtYmVyIH1cblxuY29uc3QgYXJyYXlTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcyk6IFNwYW5NZXRob2RSZXR1cm4gPT4ge1xuICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgaWYgKGNvbHVtbkluZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4gWzEsIDJdXG4gICAgfSBlbHNlIGlmIChjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgICAgcmV0dXJuIFswLCAwXVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4gWzEsIDFdXG4gICAgfVxuICB9IGVsc2Uge1xuICAgIHJldHVybiBbMSwgMV1cbiAgfVxufVxuXG5jb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcyk6IFNwYW5NZXRob2RSZXR1cm4gPT4ge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfSBlbHNlIHtcbiAgICByZXR1cm4ge1xuICAgICAgcm93c3BhbjogMSxcbiAgICAgIGNvbHNwYW46IDEsXG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
