### ISSUE TITLE
this.$notify is undefined

### ISSUE THREAD

**Issue by Pixelairport** [element-plus/element-plus#884]
I try to use notifications like the documentation says at "Local import" at https://element-plus.org/#/en-US/component/notification. 

I have a Vue3 App and include the Notifications:

````
import { ElNotification } from 'element-plus';

...

components: {
    ElNotification,
    ....
}

````

A method calls ```console.log(this.$notify);``` but console says "undefined".

**Comment by bastarder** [comment]
In this case you should call `ElNotification(options)`

**Comment by JeremyWuuuuu** [comment]
Well, we don't actually register `Nocations` that way

We register that like this:

![image](https://user-images.githubusercontent.com/15975785/101459083-bcb58600-3972-11eb-9ca4-cb5bc5cd2fe3.png)

`ElNotification` isn't some regular component that you can use it via `template` you use it in javascript code.

So if you wanted to do that just `import { ElNotification as Notify } from 'element-plus`
and then you use it like `Notify(options)`

**Comment by Pixelairport** [comment]
Thx @bastarder and @JeremyWuuuuu. I wanted to use this.$notify in methods. Not as a component. Deleted it from component option now. I did not know, that I have to do it on my own. The documentation said: "Element Plus has added a global method $notify for app.config.globalProperties..." But it seems it is missing. I did it now in my main.js like this and it works:

````
import { createApp } from 'vue'
import App from './App.vue'
import { ElNotification } from 'element-plus';

const app = createApp(App)
app.config.globalProperties.$notify = ElNotification;
app.mount('#app');
````

**Comment by JeremyWuuuuu** [comment]
Yeah, actually the app.use(ElementPlus) is doing exact the same thing you did here. So to inject that into your global config you must do it like 
`app.config.globalProperties.$notify = ElNotification;` here. The others like `message` are the same, a simpler way is that you use it like
`app.use(ElNotification)`

**Comment by Pixelairport** [comment]
did not know that app.use(ElNotification) also works :) thx @JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Glad that I can help @Pixelairport ;)

**Comment by tcstory** [comment]
when you use vue-cli alone with element-plus-plugin to create a vue 3.x with typescript project. maybe you need to add the following code to correct some errors

let's use Message component as an example

```javascript
// src/plugins/element.js

import lang from 'element-plus/lib/locale/lang/zh-cn'
import locale from 'element-plus/lib/locale'

import {ElMessage} from "element-plus";

export default (app) => {
  locale.use(lang)
  // you need this code to make "this.$message" available
  app.use(ElMessage)
}

```

```typescript
// src/main.ts


import { createApp } from 'vue'
import App from './App.vue'
// @ts-ignore
import installElementPlus from './plugins/element.js'
import {ElMessage} from "element-plus";

// you  need the following code or you will get typescript errors
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $message: typeof ElMessage;
  }
}


const app = createApp(App)
installElementPlus(app)
app.mount('#app')

```

**Comment by JeremyWuuuuu** [comment]
> when you use vue-cli alone with element-plus-plugin to create a vue 3.x with typescript project. maybe you need to add the following code to correct some errors
> 
> let's use Message component as an example
> 
> ```js
> // src/plugins/element.js
> 
> import lang from 'element-plus/lib/locale/lang/zh-cn'
> import locale from 'element-plus/lib/locale'
> 
> import {ElMessage} from "element-plus";
> 
> export default (app) => {
>   locale.use(lang)
>   // you need this code to make "this.$message" available
>   app.use(ElMessage)
> }
> ```
> 
> ```ts
> // src/main.ts
> 
> 
> import { createApp } from 'vue'
> import App from './App.vue'
> // @ts-ignore
> import installElementPlus from './plugins/element.js'
> import {ElMessage} from "element-plus";
> 
> // you  need the following code or you will get typescript errors
> declare module '@vue/runtime-core' {
>   interface ComponentCustomProperties {
>     $message: typeof ElMessage;
>   }
> }
> 
> 
> const app = createApp(App)
> installElementPlus(app)
> app.mount('#app')
> ```
> 
> remember, the place you put the code is `src/main.ts` not `shims-vue.d.ts`, look at the [vuejs/vue-next#982](https://github.com/vuejs/vue-next/pull/982) for more details

Hey, would you like to make a PR for updating the documentation? I read about what you wrote above, and I think it is a good thing for the users to notice. So, would you like to have a try?

**Comment by tcstory** [comment]
@JeremyWuuuuu yeah, that's a good idea. i will do it after i have time. but i wanna knonw  where to the add the documentation? in the page of message component or somewhere?

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu yeah, that's a good idea. i will do it after i have time. but i wanna knonw where to the add the documentation? in the page of message component or somewhere?

![image](https://user-images.githubusercontent.com/15975785/102050201-51a9fa80-3e1d-11eb-8d7c-2c960ad1b4e4.png)
Add it here would be great. You can add 1 Chinese version and 1 English, then copy the English version to `jp` `fr` `es`, you don't have to do the copy in the beginning, after I proofread the translated version then you can copy them, that would save you sometime, in another words is that you only need to work with both Chinese and English, then copy the modified content to the other 3 languages.
