### ISSUE TITLE
[Component] [date-picker] [组件] [日期选择器] el-date-picker 当前月首次选择下个月，会增加一个月的时间

### ISSUE THREAD

**Issue by qjl1** [element-plus/element-plus#8840]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 103.0.5060.114`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker.html)

### Steps to reproduce

当选择首次选择下一个月时实际日期增加了一个月，并报错：Uncaught RangeError: Maximum call stack size exceeded

### What is Expected?

在当前月能够正常选择下一个的日期

### What is actually happening?

在当前月首次选择下一个月日期时，实际显示的日期会增加一个月
例子：6月窗口选择7月1日，实际显示为9月1日

### Additional comments

_(empty)_

**Comment by holazz** [comment]
related to #8218, #8588
