### ISSUE TITLE
[Component] [date-picker] el-date-picker 在设置属性value-format="YYYY-MM-DD HH:mm:ss"情况下,无法动态设置默认值

### ISSUE THREAD

**Issue by ltbztj** [element-plus/element-plus#8843]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114 (windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/ltbztj/element-plus-.git)

### Steps to reproduce

在初始化组件时,动态设置默认值为当天的某个时间段,添加value-format属性后, 默认值无法显示到el-date-picker组件,删除value-format后则能正常显示, 如果直接传入了一个nes Date()格式数据,得到的结果不是期望的数据格式

```vue

<template>
    <div>
        <el-form :model="currentBaseData" label-width="120px">
            <el-form-item label="日期1" prop="pre_start_datetime">
                <el-date-picker v-model="currentBaseData.time1" type="datetime" format='YYYY-MM-DD HH:mm' placeholder="请选择计划开始日期"></el-date-picker>
            </el-form-item>
            <el-form-item label="日期2" prop="pre_end_datetime">
                <el-date-picker v-model="currentBaseData.time2" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" format='YYYY-MM-DD HH:mm' placeholder="请选择计划结束日期" />
            </el-form-item>
        </el-form>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
let time = new Date()
let y = time.getFullYear()
let m = time.getMonth() + 1
let d = time.getDate()
if (y.length == 1) y = '0' + y
if (d.length == 1) d = '0' + d
const date = `${y}-${m}-${d}`

const currentBaseData = ref({
    time1: date + ' 00:00:00',
    time2: date + ' 00:00:00'
})


</script>

<style scoped>
</style>
```

### What is Expected?

动态设置默认值为当天成功

### What is actually happening?

存在value-format属性 设置失败

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
格式不对哦，MM是两位，你没有给月加0

**Comment by KimYangOfCat** [comment]
> if (y.length == 1) y = '0' + y

也许这里，你应该是想写成这样

> if (m.length == 1) m = '0' + m

年份应该不需要做补位处理
再分享另一种处理方法：

> m = ("0" + m).slice(-2);
