### ISSUE TITLE
[Component] [All] 自动导入用法情况下的一些bug

### ISSUE THREAD

**Issue by Lovecxgood** [element-plus/element-plus#8846]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message.html)

### Steps to reproduce

配置自动导入

### What is Expected?

正常

### What is actually happening?

在自动导入配置用法下   elmessage Notification 不显示
color-picker选色面板不显示   Dialog 自动锁定页面滚动无效

### Additional comments

_(empty)_

**Comment by holazz** [comment]
方便提供一个最小复现的 demo 吗？

**Comment by daonatural** [comment]
https://codesandbox.io/s/0fxg7w

**Comment by mr-hmf** [comment]
color-picker选色面板右侧拖拉块不显示也遇到，增加固定宽度就显示正常了

**Comment by 613613lls** [comment]
将ELMessage 不在vue文件中引入，ELMessage 无法显示
