### ISSUE TITLE
[Component] [menu, menu-item] Highlight selected Route menu item on page load

### ISSUE THREAD

**Issue by jpenna** [element-plus/element-plus#8848]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 / Ubuntu 22.04`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`

### Reproduction Link

> I don't know how to use the import JSON file in the playground to create a functional example. Could you tell me how to do it, please?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgY3JlYXRlUm91dGVyLCBjcmVhdGVXZWJIaXN0b3J5IH0gZnJvbSAndnVlLXJvdXRlcic7XG5cbmNvbnN0IHBhdGhzID0ge1xuICBob21lOiAnLycsXG4gIGluaXRpYXRpdmVzOiAnL2luaXRpYXRpdmVzJyxcbn07XG5cbmNvbnN0IHJvdXRlciA9IGNyZWF0ZVJvdXRlcih7XG4gIGhpc3Rvcnk6IGNyZWF0ZVdlYkhpc3RvcnkoaW1wb3J0Lm1ldGEuZW52LkJBU0VfVVJMKSxcbiAgcm91dGVzOiBbe1xuICAgICAgcGF0aDogcGF0aHMuaG9tZSxcbiAgICAgIGNvbXBvbmVudDogKCkgPT4gaW1wb3J0KCdAL3ZpZXdzL0Fib3V0Vmlldy52dWUnKSxcbiAgICB9LCB7XG4gICAgICBwYXRoOiBwYXRocy5pbml0aWF0aXZlcyxcbiAgICAgIGNvbXBvbmVudDogKCkgPT4gaW1wb3J0KCdAL3ZpZXdzL0luaXRpYXRpdmVzVmlldy52dWUnKSxcbiAgICB9XSxcbn0pO1xuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtY29udGFpbmVyPlxuXG4gICAgPGVsLWhlYWRlciBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgICAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIiByb3V0ZXIgOmVsbGlwc2lzPVwiZmFsc2VcIj5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSA6aW5kZXg9XCJwYXRocy5ob21lXCI+SW7DrWNpbzwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cInBhdGhzLmluaXRpYXRpdmVzXCI+SW5pY2lhdGl2YXM8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWhlYWRlcj5cblxuICAgIDxlbC1tYWluPlxuICAgICAgPFJvdXRlclZpZXcgLz5cbiAgICA8L2VsLW1haW4+XG5cbiAgPC9lbC1jb250YWluZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgICd2dWUtcm91dGVyJ1xuICB9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. Create a menu with router `<el-menu router>` 
2. Use the `path` as the `el-menu-item`'s `index`
3. Reload the page

### What is Expected?

The menu item for the route should be selected when the page is loaded

### What is actually happening?

No item is selected until you click some menu item

**Comment by holazz** [comment]
```vue
<el-menu :default-active="$route.path">
...
</el-menu>
```

[Demo](https://stackblitz.com/edit/vitejs-vite-knyqwc?file=src%2FApp.vue&terminal=dev)

**Comment by jpenna** [comment]
Thanks @holazz ! And thanks for this quick reply.

Should this be a default behavior of `el-menu` with `router` option or make it optional? I was going to push a PR for changing the docs, but I think it should be a code change. What do you think? I can make the PR.

**Comment by holazz** [comment]
Hi, @jpenna I think the `default-active` should be configured by the user, because the `$route.path` and the index of the currently active menu item are not always the same, for example:

```vue
<el-menu :default-active="$route.path" router>
  <el-menu-item :index="/a?name=hello">hello</el-menu-item>
</el-menu>
```
The value of `$route.path` is `'/a'` instead of `'/a?name=hello'`.

**Comment by jpenna** [comment]
Makes sense. Added the details to the docs: https://github.com/element-plus/element-plus/pull/9030

Thanks for your support!
