### ISSUE TITLE
[Docs] Icon duplication of external links only in chinese docs

### ISSUE THREAD

**Issue by KimYangOfCat** [element-plus/element-plus#8851]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114 / macos 12.1`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs1](https://element-plus.org/zh-CN/component/rate.html#%E6%BA%90%E4%BB%A3%E7%A0%81)
[Docs2](https://element-plus.org/zh-CN/component/radio.html#%E6%BA%90%E4%BB%A3%E7%A0%81)
[Docs3](https://element-plus.org/zh-CN/component/config-provider.html#config-provider-%E5%B1%9E%E6%80%A7)

### Steps to reproduce

open the reproduction link

### What is Expected?

only one external link icon

### What is actually happening?

there are two external link icons

![image](https://user-images.githubusercontent.com/32960305/179388427-50311367-22c7-45ae-8920-2d393bab5f13.png)

### Additional comments

There are many more in the documentation than just the ones already listed

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/179393446-d11b0eb0-86d5-4bbb-8605-02fc573512fd.png)
You can try to clear the cache.

**Comment by plainheart** [comment]
It is a bug indeed. It occurs after switching the page multiple times.

**Comment by chenxch** [comment]
> It is a bug indeed. It occurs after switching the page multiple times.

OK, I'll look into this at a later time.

**Comment by holazz** [comment]
Changing the condition to this seems to fix the issue.

```diff
- !link.innerHTML.includes('<img')
+ !/(<img)|(<svg class="link-icon")/.test(link.innerHTML)
```

https://github.com/element-plus/element-plus/blob/ef22e5db62233901e6172a6d5db706129ff638d0/docs/.vitepress/vitepress/utils/index.ts#L101-L104

Since I'm not familiar with `docs`, I'm not sure if this issue could be caused by other places.

**Comment by chenxch** [comment]
> Since I'm not familiar with `docs`, I'm not sure if this issue could be caused by other places.

If you don't mind, you can test and fix it.🥰

**Comment by holazz** [comment]
> > Since I'm not familiar with `docs`, I'm not sure if this issue could be caused by other places.
> 
> If you don't mind, you can test and fix it.🥰

Okay, I'll test it later.
