### ISSUE TITLE
[Component] [tree] 调用setCurrentKey方法后，没有触发 current-change 事件

### ISSUE THREAD

**Issue by yyqqing** [element-plus/element-plus#8855]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoXCJhYWFcIilcbmNvbnN0IGRhdGEgPSBbe1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfV1cblxuY29uc3QgcmVmVHJlZSA9IHJlZihudWxsKVxuXG5mdW5jdGlvbiBvbkN1cnJlbnRDaGFuZ2VkKG5vZGVEYXRhLCBub2RlKSB7XG4gIGNvbnNvbGUubG9nKCdvbkN1cnJlbnRDaGFuZ2VkJywgbm9kZURhdGEsIG5vZGUpXG4gIG1zZy52YWx1ZSA9IG5vZGVEYXRhLmxhYmVsXG59XG4gIFxuZnVuY3Rpb24gc2VsZWN0VHJlZSgpIHtcbiAgcmVmVHJlZS52YWx1ZS5zZXRDdXJyZW50S2V5KCdMZXZlbCB0aHJlZSAyLTEtMScpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PiB7eyBtc2cgfX0gPC9kaXY+XG4gIDxlbC10cmVlIHJlZj1cInJlZlRyZWVcIiA6ZGF0YT1cImRhdGFcIiBub2RlLWtleT1cImxhYmVsXCIgQGN1cnJlbnQtY2hhbmdlPVwib25DdXJyZW50Q2hhbmdlZFwiPjwvZWwtdHJlZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZWxlY3RUcmVlXCI+6YCJ5LitIExldmVsIHRocmVlIDItMS0xPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

响应 el-tree 的 current-change 事件，通过 ref 调用 setCurrentKey 方法后只是展开节点，UI没有加亮 且未触发 current-change 事件

### What is Expected?

与 点击事件一样，展开节点，UI加亮节点 且 触发 current-change 事件

### What is actually happening?

只有展开节点， UI没有加亮节点，且未触发 current-change 事件

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
高亮我对比了element-ui 也是没有，这个高亮是hover 和focus 才有的高亮。

**Comment by yyqqing** [comment]
> 高亮我对比了element-ui 也是没有，这个高亮是hover 和focus 才有的高亮。

element-plus 的 tree 点击后会有高亮（在文档中基础用法样例中表现为 背景色变深），这可能是你说的 focus 的高亮。此 Issue 意思是 setCurrentKey 后应该同样有该效果，以提示用户当前选择已变化

**Comment by mioxs** [comment]
此问题是否还有关注，setCurrentKey 需触发click即可。
