### ISSUE TITLE
怎么吧默认的英文换成中文，现在文档写的是2.x的方法吧，我照着写报错了

### ISSUE THREAD

**Issue by guagezuishuai** [element-plus/element-plus#887]

**Comment by JeremyWuuuuu** [comment]
Demo plz.

**Comment by JeremyWuuuuu** [comment]
BTW: [ElementPlus ](https://element-plus.gitee.io/#/zh-CN)

**Comment by zazzaz** [comment]
https://element-plus.gitee.io/#/zh-CN/component/i18n

<img width="792" alt="image" src="https://user-images.githubusercontent.com/10731096/101466563-40c03b80-397c-11eb-8219-dcf193c2e98b.png">

**Comment by zazzaz** [comment]
https://element-plus.gitee.io/#/zh-CN/component/i18n

![Uploading image.png…]()

**Comment by guagezuishuai** [comment]
import { createApp } from 'vue';
import App from './App.vue';
import './index.css';
import router from './router';
// 全局样式
import './assets/css/index.css'
// 按需加载所需要的组件和方法
import {components, plugins} from './utils/elements';
import 'element-plus/lib/theme-chalk/index.css';
// import locale from 'element-plus/lib/locale/lang/zh-cn';
// import {setConfig} from 'element-plus/lib/utils/config'
let root = createApp(App);
components.forEach(component => {
  root.component(component.name, component)
})

plugins.forEach(plugin => {
  root.use(plugin)
})
// 全局上挂载。相当于原来的Vue.prototype扩展
root.config.globalProperties.aaa = 111;

// 全局控制台的报错的回调
root.config.errorHandler = (err, vm, info) => {
  console.log('errorHandler', err, vm, info)
}

// 全局控制台的警告的回调
root.config.warnHandler = function(msg, vm, trace) {
  console.log('warnHandler', msg, vm, trace, '===')
}
// 指定一种方法来识别在Vue之外定义的自定义元素（例如，使用Web组件API）。
// 如果component符合此条件，则不需要本地或全局注册，并且Vue不会对发出警告Unknown custom element。
// HTML原生的自定义标签，如果使用的话，vue将报错未定义的组件，可以用这个方法来忽略这个组件的使用的报错【一般不用】
// app.config.isCustomElement = tag => tag.startsWith('ion-')
// setConfig(locale)
root.use(router).mount('#app')
// 去除挂载的元素
// setTimeout(() => root.unmount('#app'), 5000)

**Comment by guagezuishuai** [comment]
> https://element-plus.gitee.io/#/zh-CN/component/i18n
> 
> <img alt="image" width="792" src="https://user-images.githubusercontent.com/10731096/101466563-40c03b80-397c-11eb-8219-dcf193c2e98b.png">

我想按需加载，，，

**Comment by zazzaz** [comment]
Just click the link above, and you will find load on demand on the second section.

**Comment by guagezuishuai** [comment]
> Just click the link above, and you will find load on demand on the second section.

我按照第二部分写报错，Uncaught SyntaxError: The requested module '/@modules/dayjs/dayjs.min.js' does not provide an export named 'default'

**Comment by guagezuishuai** [comment]
> Just click the link above, and you will find load on demand on the second section.

![image](https://user-images.githubusercontent.com/31916606/101473309-a0224980-3984-11eb-9098-ca4aee9a4365.png)

**Comment by zazzaz** [comment]
> > Just click the link above, and you will find load on demand on the second section.
> 
> 我按照第二部分写报错，Uncaught SyntaxError: The requested module '/@modules/dayjs/dayjs.min.js' does not provide an export named 'default'

Yes, I just found some error in our ESM bundle, and will cause this error while load on demand.

Will fix it soon.

**Comment by guagezuishuai** [comment]
> > > Just click the link above, and you will find load on demand on the second section.
> > 
> > 
> > 我按照第二部分写报错，Uncaught SyntaxError: The requested module '/@modules/dayjs/dayjs.min.js' does not provide an export named 'default'
> 
> Yes, I just found some error in our ESM bundle, and will cause this error while load on demand.
> 
> Will fix it soon.

我今天重新拉了包，问题还是存在的。现在是暂时不支持按需的中文么？为什么不能默认中文啊？咱们组件用户最多的不就是中国人么？

**Comment by zazzaz** [comment]
This is because Vite does not support UMD bundle.

We will try to make it work in the feature release.

At present, there are two alternatives

1 use Webpack and load on demand

2 use Vite and load full bundle

**Comment by y1378056783** [comment]
修改element-plus/lib/locale/index.js第一行换成zh-cn这步是为生产环境
修改element-plus/lib/index.ems.js找到语言变量，替换成element-plus/lib/locale/lang/zh-cn.js导出的内容这步是为开发环境
这是试过的有效，不知道有没有其他更好的方法

**Comment by zazzaz** [comment]
> > Just click the link above, and you will find load on demand on the second section.
> 
> 我按照第二部分写报错，Uncaught SyntaxError: The requested module '/@modules/dayjs/dayjs.min.js' does not provide an export named 'default'

@guagezuishuai You can try to upgrade your dayjs version to 1.10.0 to fix this esm export bug.

**Comment by Vanforu** [comment]
看一下我最新写的blog，有简单的设置成中文的方式：https://blog.csdn.net/m0_37723113/article/details/112185775

**Comment by Vanforu** [comment]
复杂的就等vite的新版本吧

**Comment by zazzaz** [comment]
Closing this issue since it can only be resolved by Vite, note that Vite is not a very mature tool.

**Comment by zszhengshang** [comment]
`if (import.meta.env.DEV) {
	locale(lang)
} else {
	locale.use(lang)
}`
我暂时用的此种方法

**Comment by SuperRay3** [comment]
```vue
<template>
  <el-config-provider :locale="locale">
    <router-view />
  </el-config-provider>
</template>

<script lang="ts">
import { ElConfigProvider } from 'element-plus'
import zhCn from 'element-plus/lib/locale/lang/zh-cn'

export default {
  components: {
    [ElConfigProvider.name]: ElConfigProvider,
  },
  data() {
    return {
      locale: zhCn,
    }
  },
}

</script>

<style lang="scss">
#app {
  height: 100%;
}
</style>

```

Code above works to me.

I have vite + vue3 + typescript + element-plus in my project and **elelment-plus  load on demand.**

Any other component code i use the  composition api, but in App.vue , i chose the option api, cuz only this can work.
