### ISSUE TITLE
[Component] [select, option] Use object as value of el-option, all of the options will be selected when select an item

### ISSUE THREAD

**Issue by LeiLeiBuHuiWanEr** [element-plus/element-plus#8882]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome/Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-option`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICB7e3ZhbHVlMX19XG4gIDxicj5cbiAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGlubGluZS1ibG9ja1wiPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0uaWRcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLm5hbWVcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFtdKVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgaWQ6ICcxJyxcbiAgICBuYW1lOiAn5Yaw5aKp5aKpJyxcbiAgfSxcbiAge1xuICAgIGlkOiAnMicsXG4gICAgbmFtZTogJ+mbquWuueiejScsXG4gIH0sXG4gIHtcbiAgICBpZDogJzMnLFxuICAgIG5hbWU6ICflsI/njKrkvanlpYcnLFxuICB9XG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<template>
  {{value1}}
  <br>
  <div style="display: inline-block">
    <el-select
      v-model="value1"
      multiple
      placeholder="Select"
      style="width: 240px"
    >
      <el-option
        v-for="item in options"
        :key="item.id"
        :label="item.name"
        :value="item"
      />
    </el-select>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const value1 = ref([])

const options = [
  {
    id: '1',
    name: '冰墩墩',
  },
  {
    id: '2',
    name: '雪容融',
  },
  {
    id: '3',
    name: '小猪佩奇',
  }
]
</script>
```

### What is Expected?

Select some options which is needed

### What is actually happening?

All options have been selected

### Additional comments

In this situation, only an object like 
{
 "label":"XXX",
 "value":"XXX"
}

can successfully selected

**Comment by holazz** [comment]
In your case, you need to set `value-key` property

**Comment by LeiLeiBuHuiWanEr** [comment]
Thanks for your comment~
