### ISSUE TITLE
[Style] [menu] 在使用<el-menu>组件时，水平模式下导航栏的宽度够放下7个<el-menu-item>但是只显示一个“主页”的<el-menu-item>，其他的被“...”替换。要刷新多次才会正常显示。

### ISSUE THREAD

**Issue by Luhuan07** [element-plus/element-plus#8890]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome版本 103.0.5060.114（正式版本）`
- Build Tool: `Webpack`

### Related Component

- `el-menu`

### Reproduction Link

[Link](https://www.itourtranslator.com/)

### Steps to reproduce

刚进入首页，导航栏只有“首页”和“...”多次刷新之后才全部显示。

### What is Expected?

随着屏幕宽度逐渐减少，才会出现“...”

### What is actually happening?

屏幕很宽，却不能全部显示。

### Additional comments

_(empty)_

**Comment by holazz** [comment]
好像不能复现 🤔
