### ISSUE TITLE
[Style] 自定义命名空间bug

### ISSUE THREAD

**Issue by KujoMiva** [element-plus/element-plus#8897]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
- Build Tool: `Nuxt`

### Related Component

- `el-dialog`
- `el-message-box`
- `el-drawer`

### Reproduction Link

https://github.com/element-plus/element-plus/blob/dev/packages/hooks/use-lockscreen/index.ts#L27-L69

### Steps to reproduce

根据文档自定义命名空间
使用ElDialog

### What is Expected?

将 body 滚动锁定

### What is actually happening?

未将body滚动锁定

### Additional comments

已经定位了错误。在此文件中的锁定body滚动的样式被固定为：el-popup-parent--hidden
node_modules/element-plus/lib/hooks/use-lockscreen/index.js

**Comment by KujoMiva** [comment]
详细错误在这里，https://github.com/element-plus/element-plus/blob/dev/packages/hooks/use-lockscreen/index.ts#L27-L69

**Comment by gjfei** [comment]
#8711 这个很早就提pr 了，没人处理
