### ISSUE TITLE
[Component] [notification] ElNotification isn't working properly when implemented in a forEach loop.

### ISSUE THREAD

**Issue by flvportafolio** [element-plus/element-plus#8907]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 103.0.5060.114 (Build oficial) (64 bits)`
- Build Tool: `Vite`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cInNob3dOb3RpZmljYXRpb25zXCI+IGdldCBub3RpZmljYXRpb25zIDwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cInNpbmdsZUV2ZW50XCI+IHNpbmdsZSBub3RpZmljYXRpb24gPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWxOb3RpZmljYXRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmZ1bmN0aW9uIHNob3dOb3RpZmljYXRpb25zKCkge1xuICBjb25zdCB0ZW1wTGlzdCA9IFsnZW1haWwgZXJyb3InLCAndXNlciBlcnJvcicsICdwYXNzd29yIGVycm9yJ107XG4gIHRlbXBMaXN0LmZvckVhY2goYXN5bmMgKGVsOiBzdHJpbmcpID0+IHtcbiAgICAvL25vdGlmaWNhdGlvbnMgb3ZlcmxhcCBlYWNoIG90aGVyXG4gICAgYXdhaXQgRWxOb3RpZmljYXRpb24oe1xuICAgICAgdGl0bGU6ICdOb3RpZmljYXRpb24nLFxuICAgICAgbWVzc2FnZTogJ25vdCBkaXNwbGF5ZWQgY29ycmVjdGx5JyxcbiAgICB9KVxuICB9KTtcbn1cbiAgXG4gIGZ1bmN0aW9uIHNpbmdsZUV2ZW50KCkge1xuICAgIEVsTm90aWZpY2F0aW9uKHtcbiAgICB0aXRsZTogJ0NsaWNrIEFnYWluIGFuZCB3b3JrJyxcbiAgICBtZXNzYWdlOiAnZXZlcnl0aGluZyB3b3JrcyB3ZWxsJyxcbiAgfSlcbiAgfVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click the 'get notifications' button

### What is Expected?

notifications should be displayed without overlapping

### What is actually happening?

notifications overlap but only when fired from a forEach loop

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
It is recommended to transform into an asynchronous trigger, such as a setTimeout.

**Comment by flvportafolio** [comment]
so `ElNotification`  should return a promise since it currently returns NotificationHandle.

doing it this way works fine, but I'm also not sure if the notification should have this behavior.

this is my notification service:
```js
// utils/notifications.ts
import { ElNotification } from 'element-plus';

export enum TypeNotification {
  Ok = 'success',
  Warn = 'warning',
  Error = 'error',
}

export default function showNotify(title: string, message: string, type: TypeNotification): Promise<unknown> {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(ElNotification({
        title,
        message,
        type,
      }));
    }, 10);
  });
}
````

**Comment by holazz** [comment]
You should use for loop instead of `forEach`, because `await` doesn't work inside `forEach`.

```ts
async function showNotifications() {
  const tempList = ['email error', 'user error', 'passwor error'];
  for(let i = 0; i < tempList.length; i++) {
    await ElNotification({
      title: 'Notification',
      message: 'not displayed correctly',
    })
  }
}
```
