### ISSUE TITLE
[Component] [input-number] Input Number 数字输入框在火狐能鼠标滚轮滚动增加/减少数值，谷歌就不可以

### ISSUE THREAD

**Issue by mr-hmf** [element-plus/element-plus#8909]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114`
- Build Tool: `Other`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html)

### Steps to reproduce

在官网的Input Number 数字输入框基础用法，通过鼠标滚轮去滚动即可复现

### What is Expected?

谷歌也可以跟火狐一样能鼠标滚轮滚动增加/减少数值

### What is actually happening?

不能通过鼠标滚轮滚动增加/减少数值

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
这个是浏览器默认行为，el-input-number没有额外处理。
