### ISSUE TITLE
ColorPicker doesn't work in beta 4

### ISSUE THREAD

**Issue by jeremieblg** [element-plus/element-plus#891]
It is impossible to use the colorpicker correctly since beta 4 but it worked fine in beta 3
We cannot choose the color because the component closes directly after the first click.

**Comment by JeremyWuuuuu** [comment]
I have no idea what error you are talking about here, if the error is something like `cannot read '0' from 'null' `, this is a bug from `Vue`, if it is not error like that, please provide demo to us so that we can do debugging.

**Comment by Ryan2128** [comment]
Duplicate #895, it will be fixd in next version.
