### ISSUE TITLE
[Component] [tooltip] el-tooltip提示Component inside <Transition> renders non-element root node that cannot be animated.

### ISSUE THREAD

**Issue by tltby12341** [element-plus/element-plus#8916]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cInJ1bGVGb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJydWxlRm9ybVwiXG4gICAgc3RhdHVzLWljb25cbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgbGFiZWwtd2lkdGg9XCIxMjBweFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxmb3JtLWl0ZW0tdG9vbHRpcCBsYWJlbD1cIkFnZVwiIHByb3A9XCJhZ2VcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cInJ1bGVGb3JtLmFnZVwiIC8+XG4gICAgPC9mb3JtLWl0ZW0tdG9vbHRpcD5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInN1Ym1pdEZvcm0ocnVsZUZvcm1SZWYpXCJcbiAgICAgICAgPlN1Ym1pdDwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Rm9ybShydWxlRm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZixoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbEZvcm1JdGVtLCBFbFRvb2x0aXAgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IEZvcm1JdGVtVG9vbHRpcCA9IGZ1bmN0aW9uIChwcm9wcywgY29udGV4dCkge1xuICBjb25zdCB7IGxhYmVsLHByb3AsIHJ1bGVzIH0gPSBwcm9wc1xuICBjb25zdCBzdHlsZSA9IHtcbiAgICBwb3NpdGlvbjogJ2Fic29sdXRlJyxcbiAgICB0b3A6ICcxMHB4JyxcbiAgICByaWdodDogJzEycHgnLFxuICAgIHdpZHRoOiAnMTRweCcsXG4gICAgaGVpZ2h0OiAnMTRweCcsXG4gIH1cbiAgcmV0dXJuIGgoXG4gICAgRWxGb3JtSXRlbSxcbiAgICB7IGxhYmVsLHByb3AsIHJ1bGVzLCBzdHlsZTogeyB3aWR0aDogJzEwMCUnIH0gfSxcbiAgICB7XG4gICAgICBkZWZhdWx0OiBjb250ZXh0LnNsb3RzLmRlZmF1bHQsXG4gICAgICBlcnJvcjogKGVycm9yT2JqKSA9PlxuICAgICAgICBoKEVsVG9vbHRpcCwgbnVsbCwge1xuICAgICAgICAgIGRlZmF1bHQ6ICgpID0+IGgoJ2RpdicsIHsgc3R5bGU6IHN0eWxlIH0pLFxuICAgICAgICAgIGNvbnRlbnQ6ICgpID0+IGgoJ2xhYmVsJywgbnVsbCwgZXJyb3JPYmouZXJyb3IpLFxuICAgICAgICB9KSxcbiAgICB9XG4gIClcbn1cblxuY29uc3QgcnVsZUZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpXG5cbmNvbnN0IGNoZWNrQWdlID0gKHJ1bGU6IGFueSwgdmFsdWU6IGFueSwgY2FsbGJhY2s6IGFueSkgPT4ge1xuICBpZiAoIXZhbHVlKSB7XG4gICAgcmV0dXJuIGNhbGxiYWNrKG5ldyBFcnJvcignUGxlYXNlIGlucHV0IHRoZSBhZ2UnKSlcbiAgfVxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBpZiAoIU51bWJlci5pc0ludGVnZXIodmFsdWUpKSB7XG4gICAgICBjYWxsYmFjayhuZXcgRXJyb3IoJ1BsZWFzZSBpbnB1dCBkaWdpdHMnKSlcbiAgICB9IGVsc2Uge1xuICAgICAgaWYgKHZhbHVlIDwgMTgpIHtcbiAgICAgICAgY2FsbGJhY2sobmV3IEVycm9yKCdBZ2UgbXVzdCBiZSBncmVhdGVyIHRoYW4gMTgnKSlcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIGNhbGxiYWNrKClcbiAgICAgIH1cbiAgICB9XG4gIH0sIDEwMDApXG59XG5cbmNvbnN0IHJ1bGVGb3JtID0gcmVhY3RpdmUoe1xuICBwYXNzOiAnJyxcbiAgY2hlY2tQYXNzOiAnJyxcbiAgYWdlOiAnJyxcbn0pXG5cbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmUoe1xuICBhZ2U6IFt7IHZhbGlkYXRvcjogY2hlY2tBZ2UsIHRyaWdnZXI6ICdibHVyJyB9XSxcbn0pXG5cbmNvbnN0IHN1Ym1pdEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgaWYgKHZhbGlkKSB7XG4gICAgICBjb25zb2xlLmxvZygnc3VibWl0IScpXG4gICAgfSBlbHNlIHtcbiAgICAgIGNvbnNvbGUubG9nKCdlcnJvciBzdWJtaXQhJylcbiAgICAgIHJldHVybiBmYWxzZVxuICAgIH1cbiAgfSlcbn1cblxuY29uc3QgcmVzZXRGb3JtID0gKGZvcm1FbDogRm9ybUluc3RhbmNlIHwgdW5kZWZpbmVkKSA9PiB7XG4gIGlmICghZm9ybUVsKSByZXR1cm5cbiAgZm9ybUVsLnJlc2V0RmllbGRzKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击submit，会报[Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated. 

### What is Expected?

没有vue warn

### What is actually happening?

提示vue warn

### Additional comments

_(empty)_

**Comment by lichunshan** [comment]
Are you sure line 10 is not `el-form-item` but `form-item-tooltip`

**Comment by tltby12341** [comment]
> `el-tooltip` 外层套个 `div`

好像不太行，tooltip会展示不出来

**Comment by holazz** [comment]
你这个例子里 tooltip 的默认插槽是个空的 div，所以不能触发，你往里面放点内容试试 [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cInJ1bGVGb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJydWxlRm9ybVwiXG4gICAgc3RhdHVzLWljb25cbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgbGFiZWwtd2lkdGg9XCIxMjBweFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxmb3JtLWl0ZW0tdG9vbHRpcCBsYWJlbD1cIkFnZVwiIHByb3A9XCJhZ2VcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cInJ1bGVGb3JtLmFnZVwiIC8+XG4gICAgPC9mb3JtLWl0ZW0tdG9vbHRpcD5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInN1Ym1pdEZvcm0ocnVsZUZvcm1SZWYpXCJcbiAgICAgICAgPlN1Ym1pdDwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Rm9ybShydWxlRm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZixoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbEZvcm1JdGVtLCBFbFRvb2x0aXAgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IEZvcm1JdGVtVG9vbHRpcCA9IGZ1bmN0aW9uIChwcm9wcywgY29udGV4dCkge1xuICBjb25zdCB7IGxhYmVsLHByb3AsIHJ1bGVzIH0gPSBwcm9wc1xuICBjb25zdCBzdHlsZSA9IHtcbiAgICBwb3NpdGlvbjogJ2Fic29sdXRlJyxcbiAgICB0b3A6ICcxMHB4JyxcbiAgICByaWdodDogJzEycHgnLFxuICAgIHdpZHRoOiAnMTRweCcsXG4gICAgaGVpZ2h0OiAnMTRweCcsXG4gIH1cbiAgcmV0dXJuIGgoXG4gICAgRWxGb3JtSXRlbSxcbiAgICB7IGxhYmVsLHByb3AsIHJ1bGVzLCBzdHlsZTogeyB3aWR0aDogJzEwMCUnIH0gfSxcbiAgICB7XG4gICAgICBkZWZhdWx0OiBjb250ZXh0LnNsb3RzLmRlZmF1bHQsXG4gICAgICBlcnJvcjogKGVycm9yT2JqKSA9PlxuICAgICAgICBoKCdkaXYnLCBoKEVsVG9vbHRpcCwgbnVsbCwge1xuICAgICAgICAgIGRlZmF1bHQ6ICgpID0+IGgoJ2RpdicsIHsgc3R5bGU6IHN0eWxlIH0sIFsndHJpZ2dlciddKSxcbiAgICAgICAgICBjb250ZW50OiAoKSA9PiBoKCdsYWJlbCcsIG51bGwsIGVycm9yT2JqLmVycm9yKSxcbiAgICAgICAgfSkpLFxuICAgIH1cbiAgKVxufVxuXG5jb25zdCBydWxlRm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KClcblxuY29uc3QgY2hlY2tBZ2UgPSAocnVsZTogYW55LCB2YWx1ZTogYW55LCBjYWxsYmFjazogYW55KSA9PiB7XG4gIGlmICghdmFsdWUpIHtcbiAgICByZXR1cm4gY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIGFnZScpKVxuICB9XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGlmICghTnVtYmVyLmlzSW50ZWdlcih2YWx1ZSkpIHtcbiAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcignUGxlYXNlIGlucHV0IGRpZ2l0cycpKVxuICAgIH0gZWxzZSB7XG4gICAgICBpZiAodmFsdWUgPCAxOCkge1xuICAgICAgICBjYWxsYmFjayhuZXcgRXJyb3IoJ0FnZSBtdXN0IGJlIGdyZWF0ZXIgdGhhbiAxOCcpKVxuICAgICAgfSBlbHNlIHtcbiAgICAgICAgY2FsbGJhY2soKVxuICAgICAgfVxuICAgIH1cbiAgfSwgMTAwMClcbn1cblxuY29uc3QgcnVsZUZvcm0gPSByZWFjdGl2ZSh7XG4gIHBhc3M6ICcnLFxuICBjaGVja1Bhc3M6ICcnLFxuICBhZ2U6ICcnLFxufSlcblxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZSh7XG4gIGFnZTogW3sgdmFsaWRhdG9yOiBjaGVja0FnZSwgdHJpZ2dlcjogJ2JsdXInIH1dLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by tltby12341** [comment]
> 解决了，感谢大佬指点



> 你这个例子里 tooltip 的默认插槽是个空的 div，所以不能触发，你往里面放点内容试试 [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cInJ1bGVGb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJydWxlRm9ybVwiXG4gICAgc3RhdHVzLWljb25cbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgbGFiZWwtd2lkdGg9XCIxMjBweFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxmb3JtLWl0ZW0tdG9vbHRpcCBsYWJlbD1cIkFnZVwiIHByb3A9XCJhZ2VcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsLm51bWJlcj1cInJ1bGVGb3JtLmFnZVwiIC8+XG4gICAgPC9mb3JtLWl0ZW0tdG9vbHRpcD5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInN1Ym1pdEZvcm0ocnVsZUZvcm1SZWYpXCJcbiAgICAgICAgPlN1Ym1pdDwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Rm9ybShydWxlRm9ybVJlZilcIj5SZXNldDwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZixoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBGb3JtSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbEZvcm1JdGVtLCBFbFRvb2x0aXAgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IEZvcm1JdGVtVG9vbHRpcCA9IGZ1bmN0aW9uIChwcm9wcywgY29udGV4dCkge1xuICBjb25zdCB7IGxhYmVsLHByb3AsIHJ1bGVzIH0gPSBwcm9wc1xuICBjb25zdCBzdHlsZSA9IHtcbiAgICBwb3NpdGlvbjogJ2Fic29sdXRlJyxcbiAgICB0b3A6ICcxMHB4JyxcbiAgICByaWdodDogJzEycHgnLFxuICAgIHdpZHRoOiAnMTRweCcsXG4gICAgaGVpZ2h0OiAnMTRweCcsXG4gIH1cbiAgcmV0dXJuIGgoXG4gICAgRWxGb3JtSXRlbSxcbiAgICB7IGxhYmVsLHByb3AsIHJ1bGVzLCBzdHlsZTogeyB3aWR0aDogJzEwMCUnIH0gfSxcbiAgICB7XG4gICAgICBkZWZhdWx0OiBjb250ZXh0LnNsb3RzLmRlZmF1bHQsXG4gICAgICBlcnJvcjogKGVycm9yT2JqKSA9PlxuICAgICAgICBoKCdkaXYnLCBoKEVsVG9vbHRpcCwgbnVsbCwge1xuICAgICAgICAgIGRlZmF1bHQ6ICgpID0+IGgoJ2RpdicsIHsgc3R5bGU6IHN0eWxlIH0sIFsndHJpZ2dlciddKSxcbiAgICAgICAgICBjb250ZW50OiAoKSA9PiBoKCdsYWJlbCcsIG51bGwsIGVycm9yT2JqLmVycm9yKSxcbiAgICAgICAgfSkpLFxuICAgIH1cbiAgKVxufVxuXG5jb25zdCBydWxlRm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KClcblxuY29uc3QgY2hlY2tBZ2UgPSAocnVsZTogYW55LCB2YWx1ZTogYW55LCBjYWxsYmFjazogYW55KSA9PiB7XG4gIGlmICghdmFsdWUpIHtcbiAgICByZXR1cm4gY2FsbGJhY2sobmV3IEVycm9yKCdQbGVhc2UgaW5wdXQgdGhlIGFnZScpKVxuICB9XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGlmICghTnVtYmVyLmlzSW50ZWdlcih2YWx1ZSkpIHtcbiAgICAgIGNhbGxiYWNrKG5ldyBFcnJvcignUGxlYXNlIGlucHV0IGRpZ2l0cycpKVxuICAgIH0gZWxzZSB7XG4gICAgICBpZiAodmFsdWUgPCAxOCkge1xuICAgICAgICBjYWxsYmFjayhuZXcgRXJyb3IoJ0FnZSBtdXN0IGJlIGdyZWF0ZXIgdGhhbiAxOCcpKVxuICAgICAgfSBlbHNlIHtcbiAgICAgICAgY2FsbGJhY2soKVxuICAgICAgfVxuICAgIH1cbiAgfSwgMTAwMClcbn1cblxuY29uc3QgcnVsZUZvcm0gPSByZWFjdGl2ZSh7XG4gIHBhc3M6ICcnLFxuICBjaGVja1Bhc3M6ICcnLFxuICBhZ2U6ICcnLFxufSlcblxuY29uc3QgcnVsZXMgPSByZWFjdGl2ZSh7XG4gIGFnZTogW3sgdmFsaWRhdG9yOiBjaGVja0FnZSwgdHJpZ2dlcjogJ2JsdXInIH1dLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
