### ISSUE TITLE
ElNotification 弹完消息会在body中留下一堆空的div，这个有办法清除掉吗？

### ISSUE THREAD

**Issue by vipsunwei** [element-plus/element-plus#893]
如果用在弹出实时的消息，在页面上留下的div标签会越来越多，这样不好
![image](https://user-images.githubusercontent.com/15810277/101479744-a79a2080-398d-11eb-8244-4eac58ca7ec4.png)

**Comment by JeremyWuuuuu** [comment]
Sure, this will be fixed in next release
