### ISSUE TITLE
[Component] [loading] namespace 页面初始化ElLoading失效

### ISSUE THREAD

**Issue by 13242428607** [element-plus/element-plus#8934]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.22`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 103.0.5060.114`
- Build Tool: `Webpack`

### Related Component

- `el-loading`

### Reproduction Link

[Link]()

### Steps to reproduce

页面初始化加载时，使用了namespace这个属性，但是ElLoading的前缀还是之前的el

### What is Expected?

页面初始化加载时，但是ElLoading的前缀是自定义的内容

### What is actually happening?

页面初始化加载时，但是ElLoading的前缀还是el的前缀

### Additional comments

_(empty)_
<img width="653" alt="企业微信截图_16583935491371" src="https://user-images.githubusercontent.com/24819336/180176630-3bfa8083-1682-4afd-afe0-9d0e4ab81866.png">

**Comment by ywl913** [comment]
不要使用全局加载，切换为按需加载即可解决此类问题
