### ISSUE TITLE
[Component] [form, input] 表单内input最右侧有一个小光标

### ISSUE THREAD

**Issue by q1045243113** [element-plus/element-plus#8935]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser : `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
- OS:                 版本	` Windows 11 专业版
                         版本	22H2
                         操作系统版本	22622.436
                         体验	Windows Feature Experience Pack 1000.22632.1000.0`

- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-input`

### Reproduction Link

[element-plus.run](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
[video demo](https://www.bilibili.com/video/BV1uS4y1t79P)

### Steps to reproduce

1. 进入ElementPlus官网, 选择一个ElemetnPlus表单内的输入框
2. 点击input输入框的最右侧,十分接近框线的地方, 即可出现
3. 实测 windwos11 edge版本 103.0.1264.62 (正式版本) (64 位) 不会出现此问题 
  Chrome 103.0.5060.114 / Windows11 会有此问题

### What is Expected?

没有多余的光标

### What is actually happening?

在表单内, el-input最右侧点击后会出现一个错位的光标
如果点击最左侧,也会在最左侧出现一个错位的光标

添加placeholder属性以后, 无法点出此错误光标
当输入字符之后,又可以再次点出此错位光标

### Additional comments

_(empty)_

![ElementPlus显示BUG](https://user-images.githubusercontent.com/25606194/180355286-eea09b47-a9b4-4e2c-859c-85936e9cc7c9.png)

**Comment by chenxch** [comment]
这个是chrome的问题，尝试将chrome更新到最新版本，应该是修复了

**Comment by q1045243113** [comment]
> 你应该是开启了光标浏览模式，按下f7
确实是的!👍 第一次知道这个功能, 学习了!

**Comment by QC2168** [comment]
> 你应该是开启了光标浏览模式，按下f7

学到了  感谢！

**Comment by cnhyk9527** [comment]
> 你应该是开启了光标浏览模式，按下f7

学习了👍
