### ISSUE TITLE
[Style] [All] 使用自动导入组件的情形下，代码中只要出现 ElMessage 就会覆盖自定义的主题样式

### ISSUE THREAD

**Issue by 613613lls** [element-plus/element-plus#8936]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 99.0.4844.51`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/613613lls/vue3-message-style-bug/)

### Steps to reproduce

vite.config.js中css配置: 
{
 preprocessorOptions: {
  scss: {				
	additionalData: `@use "@/assets/css/element.scss" as *;`,
        },
    },
}
自定义颜色为绿色，只要在vue文件中 出现 ElMessage,样式会被覆盖为官方的蓝色

### What is Expected?

显示设置的自定义样色

### What is actually happening?

显示官方提供的颜色

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
@613613lls  你可能需要在AuotImport中同样加入 importStyle: 'sass',

like this
```js
AutoImport({
	 // 自动导入 Vue 相关函数，如：ref, reactive, toRef 等
	imports: ['vue','vue-router'],
	resolvers: [
		// 自动导入 Element Plus 相关函数，如：ElMessage, ElMessageBox... (带样式)
		ElementPlusResolver({
			importStyle: 'sass',
		}),
		// Auto import icon components
		// 自动导入图标组件
		IconsResolver({
			prefix: 'i',
		}),
	],
	dts: path.resolve(resolve("src"), 'auto-imports.d.ts'),
}),
```

**Comment by 613613lls** [comment]
谢谢，就是这里的问题




时遇倾城色
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Style] [All] 使用自动导入组件的情形下，代码中只要出现 ElMessage 就会覆盖自定义的主题样式 (Issue #8936)





 
@613613lls  你可能需要在AuotImport中同样加入 importStyle: 'sass',
 
like this
 AutoImport({ 	 // 自动导入 Vue 相关函数，如：ref, reactive, toRef 等 	imports: ['vue','vue-router'], 	resolvers: [ 		// 自动导入 Element Plus 相关函数，如：ElMessage, ElMessageBox... (带样式) 		ElementPlusResolver({ 			importStyle: 'sass', 		}), 		// Auto import icon components 		// 自动导入图标组件 		IconsResolver({ 			prefix: 'i', 		}), 	], 	dts: path.resolve(resolve("src"), 'auto-imports.d.ts'), }),
