### ISSUE TITLE
[Style] [tree] el-tree组件使用插槽后字体变大

### ISSUE THREAD

**Issue by Charlee-du** [element-plus/element-plus#8943]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBkZXB0T3B0aW9ucyA9IHJlZihbe1wiaWRcIjpcIjEwMFwiLFwibGFiZWxcIjpcIuaAu+acuuaehFwiLFwiaXNDb21tb25cIjowLFwiY2hpbGRyZW5cIjpbe1wiaWRcIjpcIjIwOFwiLFwibGFiZWxcIjpcIuWkp+WtpjFcIixcImlzQ29tbW9uXCI6MH0se1wiaWRcIjpcIjIyNFwiLFwibGFiZWxcIjpcIuWkp+WtpjJcIixcImlzQ29tbW9uXCI6MH0se1wiaWRcIjpcIjEwMVwiLFwibGFiZWxcIjpcIuaAu+WFrOWPuFwiLFwicmVnaXN0ZXJZZWFyXCI6XCIyMDIyXCIsXCJpc0NvbW1vblwiOjEsXCJjaGlsZHJlblwiOlt7XCJpZFwiOlwiMTA0XCIsXCJsYWJlbFwiOlwi5biC5Zy66YOo6ZeoXCIsXCJyZWdpc3RlclllYXJcIjpcIjIwMjJcIixcImlzQ29tbW9uXCI6MX0se1wiaWRcIjpcIjEwNlwiLFwibGFiZWxcIjpcIui0ouWKoemDqOmXqFwiLFwicmVnaXN0ZXJZZWFyXCI6XCIyMDIyXCIsXCJpc0NvbW1vblwiOjF9LHtcImlkXCI6XCIxMDdcIixcImxhYmVsXCI6XCLov5Dnu7Tpg6jpl6hcIixcInJlZ2lzdGVyWWVhclwiOlwiMjAyMlwiLFwiaXNDb21tb25cIjoxfV19XX1dKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz0nYXBwLWNvbnRhaW5lcic+XG4gICAgPGVsLXJvdyA6Z3V0dGVyPScyMCc+XG4gICAgICA8ZWwtY29sIDpzcGFuPSc0JyA6eHM9JzI0Jz5cbiAgICAgICAgPGVsLWRpdmlkZXIgY29udGVudC1wb3NpdGlvbj1cImNlbnRlclwiPuW8guW4uDwvZWwtZGl2aWRlcj5cbiAgICAgICAgPGVsLWNhcmQgY2xhc3M9XCJib3gtY2FyZFwiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9J2hlYWQtY29udGFpbmVyJz5cbiAgICAgICAgICAgIDxlbC10cmVlXG4gICAgICAgICAgICAgIHYtbG9hZGluZz1cImRlcHRUcmVlTG9hZGluZ1wiXG4gICAgICAgICAgICAgIDpkYXRhPSdkZXB0T3B0aW9ucydcbiAgICAgICAgICAgICAgOnByb3BzPVwieyBsYWJlbDogJ2xhYmVsJywgY2hpbGRyZW46ICdjaGlsZHJlbicgfVwiXG4gICAgICAgICAgICAgIDpleHBhbmQtb24tY2xpY2stbm9kZT0nZmFsc2UnXG4gICAgICAgICAgICAgIDpmaWx0ZXItbm9kZS1tZXRob2Q9J2ZpbHRlck5vZGUnXG4gICAgICAgICAgICAgIHJlZj0nZGVwdFRyZWVSZWYnXG4gICAgICAgICAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgICAgICAgICAgICBoaWdobGlnaHQtY3VycmVudFxuICAgICAgICAgICAgICBAbm9kZS1jbGljaz0naGFuZGxlTm9kZUNsaWNrJ1xuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7ZGF0YX1cIj5cbiAgICAgICAgICAgICAgICB7eyBkYXRhLmxhYmVsIH19XG4gICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8L2VsLXRyZWU+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZWwtY2FyZD5cblx0XHRcdFx0PGVsLWRpdmlkZXIgY29udGVudC1wb3NpdGlvbj1cImNlbnRlclwiPuato+W4uDwvZWwtZGl2aWRlcj5cbiAgICAgICAgPGVsLWNhcmQgY2xhc3M9XCJib3gtY2FyZFwiPlxuXHRcdFx0XHRcdDxkaXYgY2xhc3M9J2hlYWQtY29udGFpbmVyJz5cbiAgICAgICAgICAgIDxlbC10cmVlXG4gICAgICAgICAgICAgIHYtbG9hZGluZz1cImRlcHRUcmVlTG9hZGluZ1wiXG4gICAgICAgICAgICAgIDpkYXRhPSdkZXB0T3B0aW9ucydcbiAgICAgICAgICAgICAgOnByb3BzPVwieyBsYWJlbDogJ2xhYmVsJywgY2hpbGRyZW46ICdjaGlsZHJlbicgfVwiXG4gICAgICAgICAgICAgIDpleHBhbmQtb24tY2xpY2stbm9kZT0nZmFsc2UnXG4gICAgICAgICAgICAgIDpmaWx0ZXItbm9kZS1tZXRob2Q9J2ZpbHRlck5vZGUnXG4gICAgICAgICAgICAgIHJlZj0nZGVwdFRyZWVSZWYnXG4gICAgICAgICAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgICAgICAgICAgICBoaWdobGlnaHQtY3VycmVudFxuICAgICAgICAgICAgICBAbm9kZS1jbGljaz0naGFuZGxlTm9kZUNsaWNrJ1xuICAgICAgICAgICAgLz5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9lbC1jYXJkPlxuICAgICAgPC9lbC1jb2w+XG4gICAgPC9lbC1yb3c+XG4gIDwvZGl2PlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4udGV4dCB7XG4gIGZvbnQtc2l6ZTogMTRweDtcbn1cblxuLml0ZW0ge1xuICBwYWRkaW5nOiAxOHB4IDA7XG59XG5cbi5ib3gtY2FyZCB7XG4gIHdpZHRoOiA0ODBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-tree组件使用插槽后文字就变大了，不是原有组件的文字大小

### What is Expected?

使用插槽后文字大小以及其他样式不变

### What is actually happening?

使用插槽后文字变大了

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你要给你的插槽内容加样式哦，组件默认字体大小的class是加在默认插槽内容上

**Comment by Charlee-du** [comment]
其他组件不都继承组件样式的，不应该要自己加组件的样式啊
