### ISSUE TITLE
[Component] 在vue2升级vue3之后，使用   config.resolve.alias.set('vue', '@vue/compat');  element-plus 中的输入框无法录入信息

### ISSUE THREAD

**Issue by zyn-github** [element-plus/element-plus#8945]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.7`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`
- `el-select`
- `el-date-picker`

### Reproduction Link

[Github Repo](https://github.com/zyn-github/element-plus-bug-v1)

### Steps to reproduce

// vue 代码
<template>
    <div class="device-manage">
         <el-input v-model="input" placeholder="Please input" />
    </div>
</template>
<script>
import { ref } from 'vue';
export default {
    setup() {
        const input = ref('');
        return {
            input
        };
    }
};
</script>

// vue.config.js
// 脚手架版本 "@vue/cli-service": "^5.0.8"
module.exports = {
    publicPath: 'wwwroot',
    outputDir: process.env.VUE_APP_OUTPUTDIR,
    lintOnSave: true,
    devServer: {
        host: '0.0.0.0',
        headers: {
            FeEnvironment: '_environment'
        }
    },
    chainWebpack: config => {
        config.resolve.alias.set('vue', '@vue/compat'); // 产生不兼容的主要原因
        config.module
            .rule('vue')
            .use('vue-loader')
            .tap(options => ({
                ...options,
                compilerOptions: {
                    compatConfig: {
                        MODE: 2,
                        COMPILER_V_ON_NATIVE: false,
                        COMPILER_NATIVE_TEMPLATE: false,
                        COMPILER_V_BIND_SYNC: false,
                        ATTR_FALSE_VALUE: false,
                        ATTR_ENUMERATED_COERCION: false,
                        COMPILER_V_IF_V_FOR_PRECEDENCE: false,
                        COMPILER_V_BIND_OBJECT_ORDER: false
                    }
                }
            }));
    },
    configureWebpack: config => {
        cdnpub.checkConfig(config, { version, conf });
        if (process.env.NODE_ENV === 'development') {
            config.devtool = 'source-map';
        } else {
            config.plugins.push(
                new webpack.DllReferencePlugin({
                    context: process.cwd(),
                    manifest: require(`${dllPath}/vendor-manifest.json`)
                })
            );
            config.plugins.push(
                new AddAssetHtmlPlugin({
                    // dll文件位置
                    filepath: path.resolve(__dirname, `${dllPath}/*.js`),
                    // dll 引用路径
                    publicPath: _cdnPath + linkPath,
                    // dll最终输出的目录
                    outputPath: linkPath
                })
            );
        }
    },
    css: {
        loaderOptions: {
            sass: {
                data: '@import "~@/assets/mixins.scss";'
            }
        }
    },
    productionSourceMap: false
};

### What is Expected?

可以正常进行双向数据绑定

### What is actually happening?

输入字符是替换效果，之后失去焦点才会将上次录入的最后一个字符显示在数据框内

### Additional comments

可以启用github项目进行浮现，谢谢

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGRpdiBzdHlsZT1cImhlaWdodDoxMDAlXCI+XG4gICAgICAgICAgICB7e2lucHV0fX09PT1cbiAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6MTAwJVwiPlxuICAgICAgICAgICAgICAgIDwhLS0gPHJvdXRlci12aWV3Pjwvcm91dGVyLXZpZXc+IC0tPlxuICAgICAgICAgICAgICAgICA8IS0tIDxlbC1pbnB1dCAgQHVwZGF0ZTptb2RlbFZhbHVlID0gXCIoJGV2ZW50KT0+IGlucHV0PSAkZXZuZW50LnRhcmdldC52YWx1ZVwiIHYtbW9kZWw9XCJpbnB1dFwiIG1vZGVsVmFsdWU9XCJpbnB1dFwiICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIC8+IC0tPlxuICAgICAgICAgICAgICAgICA8ZWwtaW5wdXQgICB2LW1vZGVsPVwiaW5wdXQuY3ZcIiAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiAvPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdW5yZWYscmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGlucHV0ID0gcmVhY3RpdmUoe1xuICAgICAgICAgICAgY3Y6ICcyJ1xuICAgICAgICB9KTtcbiAgY29uc3QgZnVuQ1YgPSBjID0+IHtcbiAgICBjb25zb2xlLmxvZyhjLCAnLS0tLS0tLS0tLS0tLS0+Pj4nKTtcbiAgfTtcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319) 
未见复现
为何要将vue执行@vue/compat？请确认指向正确的reactivity包。

**Comment by zyn-github** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
