### ISSUE TITLE
el-color-picker无法选中

### ISSUE THREAD

**Issue by chengaohe45** [element-plus/element-plus#895]
# 版本
1.0.1-beta.4 / 1.0.1-beta.5
<pre>
&lt;el-color-picker v-model="color1" show-alpha&gt;&lt;/el-color-picker&gt;    // color1为"#409EFF"
</pre>
## 问题描述
1. 颜色无法选中
2. 当show-alpha为true,颜色选择框中的“输入框”出现异常

## 异常图片
![image](https://user-images.githubusercontent.com/26498356/101480305-79691080-398e-11eb-9246-39d5e25eda56.png)

**Comment by Ryan2128** [comment]
I failed to reproduce the second question.

Can u provide a reproduction?

**Comment by Ryan2128** [comment]
For the second question, if have any questions, please reopen this issue. @chengaohe45
