### ISSUE TITLE
[Component] el-date-picker使用modelValue无法绑定值，popper/content.vue内的onFocusInTrap调用次数过多， 堆栈溢出

### ISSUE THREAD

**Issue by makai1027** [element-plus/element-plus#8950]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome/103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-popover`
- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsRGF0ZVBpY2tlciB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGRhdGFWYWx1ZSA9IHJlZignJylcbmNvbnN0IGRhdGFWYWx1ZTIgPSByZWYoJycpXG5jb25zdCB0aW1lVmFsdWUgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8RWxEYXRlUGlja2VyIDptb2RlbFZhbHVlPSdkYXRhVmFsdWUnIC8+XG4gIDxici8+XG4gICAgPEVsRGF0ZVBpY2tlciA6bW9kZWxWYWx1ZT0nZGF0YVZhbHVlMicgdHlwZT1cImRhdGV0aW1lXCIgLz5cbiAgPGJyLz5cbiAgPGVsLXRpbWUtcGlja2VyIDptb2RlbFZhbHVlPVwidGltZVZhbHVlXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref } from 'vue'
import { ElDatePicker, ElTimePicker } from 'element-plus'
const dataValue = ref('')
const dataValue2 = ref('')
const timeValue = ref('')
</script>
<template>
  <ElDatePicker :modelValue='dataValue' />
  <br/>
  <ElDatePicker :modelValue='dataValue2' type="datetime" />
  <br/>
  <el-time-picker :modelValue="timeValue" />
</template>
```

### What is Expected?

成功赋值并关闭popover

### What is actually happening?

未赋值成功
Uncaught RangeError: Maximum call stack size exceeded.
    at onFocusInTrap (content.vue:158:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:721:9)
    at runtime-core.esm-bundler.js:7348:53
    at HTMLDivElement.onFocusIn (focus-trap.vue:154:28)
    at onFocusInTrap (content.vue:158:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:721:9)

### Additional comments

本想试着使用element-plus封装一套 curd component，无意中发现这个问题

![image](https://user-images.githubusercontent.com/24761813/180351462-df7b0aa7-3bfd-4f0b-9a4d-a5f57eb4c1c4.png)
![image](https://user-images.githubusercontent.com/24761813/180351518-b484d53c-be90-46e6-8a02-83d2c19e4108.png)

**Comment by holazz** [comment]
这样写：

```vue
<ElDatePicker 
  :modelValue="dataValue"
  @update:modelValue="(value) => (dataValue = value)
/>
```

或者

```vue
<ElDatePicker v-model="dataValue" />
```

RangeError 在这个 PR 修复了 #8218

**Comment by makai1027** [comment]
> 这样写：
> 
> ```
> <ElDatePicker 
>   :modelValue="dataValue"
>   @update:modelValue="(value) => (dataValue = value)
> />
> ```
> 
> 或者
> 
> ```
> <ElDatePicker v-model="dataValue" />
> ```
> 
> RangeError 在这个 PR 修复了 #8218

我说呢，原来需要手动赋值
谢谢老板
