### ISSUE TITLE
[Component] [popover, input] Popover 使用自定义显示和隐藏,里面套用input.然后所有input都无法获取到焦点

### ISSUE THREAD

**Issue by yundou147** [element-plus/element-plus#8952]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG48ZWwtaW5wdXQgcmVmPVwiYnV0dG9uUmVmXCIgICAgdHlwZT1cInRleHRhcmVhXCJcbiAgICAgICAgICAgICAgdi1tb2RlbD1cInJlZk1vZGVsVmFsdWVcIiBAZm9jdXM9XCJ2aXNpYmxlPXRydWVcIj4gPC9lbC1pbnB1dD5cbiAgICAgICAgICAgIFxuICAgICAgICAgICAgXG4gICBcbiAgIFxuICBcbiAgPGVsLXBvcG92ZXJcbiAgICByZWY9XCJwb3BvdmVyUmVmXCJcbiAgICA6dmlydHVhbC1yZWY9XCJidXR0b25SZWZcIlxuICAgICB0cmlnZ2VyPVwiY29udGV4dG1lbnVcIlxuICAgIHRpdGxlPVwiV2l0aCB0aXRsZVwiXG4gICAgdmlydHVhbC10cmlnZ2VyaW5nXG4gICAgOnZpc2libGU9XCJ2aXNpYmxlXCJcbiAgPlxuICAgIDxzcGFuPiBTb21lIGNvbnRlbnQgPC9zcGFuPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB1bnJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENsaWNrT3V0c2lkZSBhcyB2Q2xpY2tPdXRzaWRlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuY29uc3QgYnV0dG9uUmVmID0gcmVmKClcbmNvbnN0IHBvcG92ZXJSZWYgPSByZWYoKVxuY29uc3QgcmVmTW9kZWxWYWx1ZSA9IHJlZihcIjExMVwiKTtcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpO1xuXG5cbmNvbnN0IG9uQ2xpY2tPdXRzaWRlID0gKCkgPT4ge1xuICB1bnJlZihwb3BvdmVyUmVmKS5wb3BwZXJSZWY/LmRlbGF5SGlkZT8uKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

当popover出现后,鼠标点击popover上面,在点击到input上面,input无法获取到焦点.

### What is Expected?

input能获取到焦点

### What is actually happening?

input无法获取到焦点.

### Additional comments

_(empty)_

**Comment by gaga-change** [comment]
遇到同样问题

**Comment by gaga-change** [comment]
版本2.2.0 就正常的, 2.2.1开始就有这个问题了. 现在除了降级到2.2.0  不知道还有什么更好的方式解决
