### ISSUE TITLE
[Component] [date-picker] when type is set to daterange and is disabled, the background color of the input box is incorrect

### ISSUE THREAD

**Issue by Mario34** [element-plus/element-plus#8953]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 102.0.5005.61/Mac os 12.2.1 `
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc3dpdGNoIHYtbW9kZWw9XCJkaXNhYmxlZFwiIC8+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgIHYtbW9kZWw9XCJ0aW1lXCJcbiAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICB1bmxpbmstcGFuZWxzXG4gICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgbW9udGhcIlxuICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBtb250aFwiXG4gICAgOnNob3J0Y3V0cz1cInNob3J0Y3V0c1wiXG4gICAgOmRpc2FibGVkPVwiZGlzYWJsZWRcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGRpc2FibGVkID0gcmVmKHRydWUpXG5jb25zdCB0aW1lID0gcmVmKFsnMjAyMi0wMi0wMycsICcyMDIyLTA1LTEyJ10pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click the link

### What is Expected?

The background color is set correctly

### What is actually happening?

The background color covers the border

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/42017165/180355699-aa19b3e7-535e-40ca-a9d6-a58fa0b54e8b.png)

**Comment by holazz** [comment]
Hi, I have created a PR to solve this issue. #8879
