### ISSUE TITLE
[Component] [affix, config-provider] el-config-provider中的el-affix固钉不生效

### ISSUE THREAD

**Issue by chengkdixin** [element-plus/element-plus#8955]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome  103.0.5060.66`
- Build Tool: `Webpack`

### Related Component

- `el-affix`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlcj5cbiAgICA8ZGl2IGlkPVwiYm94XCIgc3R5bGU9XCJoZWlnaHQ6MjAwcHhcIj5cbiAgICAgIDxlbC1hZmZpeFx0Om9mZnNldD1cIjIwXCI+XG4gICAgICBcdDxlbC1idXR0b24+XG4gICAgICAgIOWbuuWumjwvZWwtYnV0dG9uPlxuICAgICAgPC9lbC1hZmZpeD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OjEwMDBweFwiPlxuICAgICAgXG4gICAgPC9kaXY+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

  <el-config-provider>
    <div id="box" style="height:200px">
      <el-affix position="bottom"	:offset="20">
      	<el-button>
        固定</el-button>
      </el-affix>
    </div>
    <div style="height:1000px">
      
    </div>
  </el-config-provider>

### What is Expected?

固定生效

### What is actually happening?

固定不生效，只有视图框变化的时候才生效

### Additional comments

https://element-plus.gitee.io/zh-CN/component/affix.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
官网页面中也有固定不生效

**Comment by chenxch** [comment]
未见复现

**Comment by houqingbin** [comment]
el-affix 设置offset 为零的时候,会不生效
