### ISSUE TITLE
[Component] [date-picker] DatePicker 日期选择器 官网点击上个月时间，直接 Maximum call Error

### ISSUE THREAD

**Issue by Patersooon** [element-plus/element-plus#8968]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.10`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html)

### Steps to reproduce

打开日期选择6.26日，控制台输出Uncaught RangeError: Maximum call stack size exceeded.

### What is Expected?

nothing

### What is actually happening?

Error

### Additional comments

_(empty)_

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/90687224/180407809-f02f7149-9882-465c-a7ae-c701c57bd6e9.png">

**Comment by gjfei** [comment]
#8588 这里修复了，你更新到2.2.10试试看

**Comment by tolking** [comment]
文档点击确实会出现这个问题。似乎仅有这种情况能够复现 [demo](https://stackblitz.com/edit/web-platform-kzrg13?file=index.html)

**Comment by qjl1** [comment]
@gjfei 我看了下#8588合并了，但是并没有修复，目前官网上的组件照样有这样的问题

**Comment by kmliugang** [comment]
点击非本月展示的灰色日期，就会报错
