### ISSUE TITLE
[Component] [dialog] 有些电脑在 el-dialog 中按空格键 el-select 会失去焦点

### ISSUE THREAD

**Issue by xjt610056371** [element-plus/element-plus#8969]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2aXNpYWJsZSA9IHJlZih0cnVlKVxuY29uc3QgZnJ1aXQgPSByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRpYWxvZ1xuICAgIHRpdGxlPVwi5rWL6K+VXCJcbiAgICB2LW1vZGVsPVwidmlzaWFibGVcIlxuICAgIHdpZHRoPVwiNTAwcHhcIiBkcmFnZ2FibGU+XG4gICAgPGVsLWZvcm0gbGFiZWwtd2lkdGg9XCIxMzBweFwiIGxhYmVsLXBvc2l0aW9uPVwibGVmdFwiPlxuICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuawtOaenO+8mlwiPlxuICAgICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmcnVpdFwiIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oup5rC05p6cXCIgZmlsdGVyYWJsZT5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi5qGD5a2QXCIgdmFsdWU9XCIxXCI+PC9lbC1vcHRpb24+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuiLueaenFwiIHZhbHVlPVwiMlwiPjwvZWwtb3B0aW9uPlxuICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDwvZWwtZm9ybT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1、鼠标点击 select 聚焦
2、按空格键

### What is Expected?

按空格键输入 空格符

### What is actually happening?

按空格键失去焦点，下拉框收起，并且不会输入空格

### Additional comments

只有部分电脑会触发该bug

**Comment by tolking** [comment]
select 组件中空格的默认行为就是打开弹窗和选中当前项

**Comment by xjt610056371** [comment]
假设你是对的，那使用 filterable 属性进行筛选的时候应该如何输入空格？但是 select 组件不包含在 dialog 组件中并不会有这种行为

**Comment by tolking** [comment]
不是可以输入吗？

> 只有部分电脑会触发该bug

或许你可以提供更详细的信息

**Comment by xjt610056371** [comment]
> select 组件中空格的默认行为就是打开弹窗和选中当前项

就是这个问题，我们打字不是会习惯使用空格选中吗，跟这默认行为冲突了

**Comment by tolking** [comment]
输入时是可以输入空格的，可能有些浏览器版本存在差异。提供更详细的信息方便排查问题
