### ISSUE TITLE
[Component] [table, table-column] The installation method is: import directly in the browser，table header is abnormal

### ISSUE THREAD

**Issue by wu6666gong** [element-plus/element-plus#8971]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.10`
- Browser / OS: `Chrome 103.0.5060.53/macOS Monterey 12.1`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/jfxz/pen/VwXWjRg)

### Steps to reproduce

direct reference

### What is Expected?

 table header Like the official website example

### What is actually happening?

table header is abnormal

### Additional comments

_(empty)_

**Comment by tolking** [comment]
`<el-table-column prop="date" label="Date" width="180"></el-table-column>`

link #7232

**Comment by wu6666gong** [comment]
thanks
