### ISSUE TITLE
[Feature Request] Disabling backspace removing tags

### ISSUE THREAD

**Issue by hahatulk** [element-plus/element-plus#8976]
### Existing Component
Yes

### Component Name
el-select

### Description
Please add prop for disabling backspace removing tags in multiple mode, it is not suitable in some cases

**Comment by holazz** [comment]
You can handle keyboard event yourself:

```vue
<el-select
  @keydown.backspace.capture.prevent.stop
>
...
</el-select>
```

**Comment by hahatulk** [comment]
> You can handle keyboard event yourself:
> 
> ```
> <el-select
>   @keydown.delete.capture.prevent.stop
> >
> ...
> </el-select>
> ```

Thank you. Didnt know that component passes listeners to nested input 😅
