### ISSUE TITLE
[Component] [table] 销毁Table元素后报错 'offsetHeight' of null

### ISSUE THREAD

**Issue by scuiadmin** [element-plus/element-plus#8977]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Chrome/103.0.5060.134`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[https://element-plus.gitee.io/zh-CN/component/drawer.html#自定义内容](https://element-plus.gitee.io/zh-CN/component/drawer.html#自定义内容)

### Steps to reproduce

官方示例，Drawer开启**destroy-on-close**后显示Table，关闭后即可复现

### What is Expected?

消除报错信息

### What is actually happening?

报错

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/2329573/180586226-13c4a3a4-d97e-4341-824b-c3ff2ece9aa3.png)

**Comment by wanglong617** [comment]
我也有这个问题，每次销毁有报 styleHelper ResizeObserver.resizeListener offsetHeight

**Comment by mxp131011** [comment]
Me too

**Comment by l-x-f** [comment]
Me too

**Comment by pmb2020** [comment]
Me too，应该是2.2.10刚出来的bug，退到2.2.9就没了

**Comment by p54088** [comment]
+1 回退2.2.9了

**Comment by xuxiaowei-com-cn** [comment]
+1 回退2.2.9了

**Comment by AzzraelCode** [comment]
+1 v2.2.10
Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at ResizeObserver.resizeListener (style-helper.mjs?41d0:180:1)
resizeListener @ style-helper.mjs?41d0:180
--
table.refs ~ are empty

**Comment by zhf0437** [comment]
我2.2.9也有这个问题

**Comment by JCAlways** [comment]
Me too

**Comment by wgpqys** [comment]
2.2.10有这个bug

**Comment by dxy2233** [comment]
me too

**Comment by wp993080086** [comment]
2.2.9有这个问题

**Comment by DaniilCome1n** [comment]
+1

**Comment by 1061127386** [comment]
me too

**Comment by iamkun** [comment]
this should have been fixed in #9011 and will be available in the next release
