### ISSUE TITLE
[Style] table表中使用image图片预览功能样式错乱

### ISSUE THREAD

**Issue by orangememo** [element-plus/element-plus#8978]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-image-viewer`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgPlxuICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IHJvdyB9XCI+XG5cdFx0XHRcblx0XHRcdFx0PGVsLWltYWdlIHN0eWxlPVwid2lkdGg6IDgwcHg7IGhlaWdodDogODBweFwiIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCIgOnByZXZpZXctc3JjLWxpc3Q9XCJzcmNzXCIgZml0PVwiY292ZXJcIiAvPlxuXHRcdFx0PC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbmNvbnN0IHNyY3M9IFtcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8xLzM0LzE5YWE5OGIxZmNiMjc4MWM0ZmJhMzNkODUwNTQ5anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8wLzZmL2UzNWZmMzc1ODEyZTZiMDAyMGI2YjRlOGY5NTgzanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9kL2U2L2M0ZDkzYTM4MDViM2NlM2YzMjNmNzk3NGU2Zjc4anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzI4L2JiZjg5M2Y3OTJmMDNhNTQ0MDhiM2I3YTdlYmYwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

列表中点击图片预览就会有样式bug

### What is Expected?

应该是图片预览

### What is actually happening?

会有table里面的东西混到图片预览中

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/63847263/180587647-01b5cc52-6ef5-4e6e-a5d3-c70e1ecf12ca.png)

**Comment by scuiadmin** [comment]
https://element-plus.gitee.io/zh-CN/component/table.html#如何在表格中使用图像预览？
