### ISSUE TITLE
[Component] [select] Select  点击后自动关闭弹出列表

### ISSUE THREAD

**Issue by nodserve** [element-plus/element-plus#8989]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Chrome/103.0.5060.114`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICBhbGxvdy1jcmVhdGVcbiAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJDaG9vc2UgdGFncyBmb3IgeW91ciBhcnRpY2xlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

select 创建新的选项 官方演示中存在可复现问题。

### What is Expected?

#

### What is actually happening?

2.2.10版本开始出现该问题，2.2.9版本无问题。

### Additional comments

_(empty)_

**Comment by hoowhoami** [comment]
应该是 `filterable` 属性的问题

**Comment by nodserve** [comment]
刚测试发现，点击ICO图标无问题，左侧区域点击自动收回。

**Comment by nodserve** [comment]
应该是输入内容空判断问题，当输入框内输出任意字符后追加空格 就会触发弹出层关闭
