### ISSUE TITLE
[Component] [time-select] TimeSelect 最新版本2.2.10 第一次点击时，弹出选项自动关闭

### ISSUE THREAD

**Issue by Patersooon** [element-plus/element-plus#9001]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.10`
- Browser / OS: `mac`
- Build Tool: `Vite`

### Related Component

- `el-time-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGltZS1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIHN0YXJ0PVwiMDg6MzBcIlxuICAgIHN0ZXA9XCIwMDoxNVwiXG4gICAgZW5kPVwiMTg6MzBcIlxuICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0IHRpbWVcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

先失去 time-select 焦点。然后点击time-select

### What is Expected?

正常打开选项

### What is actually happening?

打开选项又自动关闭

### Additional comments

_(empty)_

https://user-images.githubusercontent.com/90687224/180678417-e97d3561-96e1-4901-a4a3-03e410f0c019.mov

**Comment by Sweet-KK** [comment]
最新版同样遇到这个问题，组件是el-select

**Comment by tolking** [comment]
Link #8762

**Comment by jddk** [comment]
el-select，添加filterable属性也会出现这样的bug，2.2.10
`
  <el-select
      v-model="value1"
      filterable
      placeholder="Select"
      style="width: 240px"
    >
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      />
    </el-select>
`

**Comment by 15200596294git** [comment]
我的el-select也遇到同样的问题

**Comment by btea** [comment]
fixed #9019

**Comment by chenhongwei123** [comment]
同样遇到

**Comment by Tanlifan** [comment]
same problem, update to v2.2.12 to solve
