### ISSUE TITLE
[Component] [input-number] The input event of inputnumber behaves the same as the change event

### ISSUE THREAD

**Issue by RadiumAg** [element-plus/element-plus#9002]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIEBpbnB1dD1cImhhbmRsZUlucHV0XCIgIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5cbmNvbnN0IG51bSA9IHJlZig1KVxuXG5jb25zdCBoYW5kbGVJbnB1dCA9ICh2YWwpPT57XG4gIGNvbnNvbGUubG9nKHZhbCk7XG59XG5cblxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbCkgPT4ge1xuICBjb25zb2xlLmxvZyh2YWwpO1xufVxuXG53YXRjaChudW0sKHZhbCk9PnsgY29uc29sZS5sb2codmFsKSB9KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce
whe listen the input event,it's not happend immediately
当监听input事件时，并不会立即触发，而是和change事件一样，在失去焦点之后才触发

### What is Expected?
exected that the same as native
和原生的input事件一样，在用户输入的时候触发

### What is actually happening?
only bulr that the event happend
只有失去焦点之后，才触发

### Additional comments

_(empty)_

**Comment by QiJieH** [comment]
确实有这个问题存在，@change和@input的表现居然和@blur一致？

**Comment by RadiumAg** [comment]
> 确实有这个问题存在，@change和@input的表现居然和@blur一致？ vue2可以通过为@change@input添加.native修饰符来监听原生的相关事件
实际上在**element-ui**上vue2的**.native只能监听根元素的原生事件**，监听到的实际上是冒泡冒出来的，这点可以从`currentTarget`看出来，**vue3**因为多了**emit**定义，所以能够区分原生事件还是组件自定义事件，所以就很难监听到了

**Comment by RadiumAg** [comment]
> 确实有这个问题存在，@change和@input的表现居然和@blur一致？ vue2可以通过为@change@input添加.native修饰符来监听原生的相关事件

**Comment by HeftyKoo** [comment]
fixed by: https://github.com/element-plus/element-plus/pull/9850
