### ISSUE TITLE
[Style] [input, select] The nesting of input components is wrong when they are larger

### ISSUE THREAD

**Issue by ac51300696** [element-plus/element-plus#9007]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIFxuICA8ZGl2IGNsYXNzPVwibXQtNFwiPlxuICAgIDxlbC1pbnB1dFxuICAgICAgICAgICAgICBzaXplPSdsYXJnZSdcbiAgICAgIHYtbW9kZWw9XCJpbnB1dDNcIlxuICAgICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAgICAgY2xhc3M9XCJpbnB1dC13aXRoLXNlbGVjdFwiXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICNwcmVwZW5kPlxuICAgICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJzZWxlY3RcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDExNXB4XCI+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlJlc3RhdXJhbnRcIiB2YWx1ZT1cIjFcIiAvPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJPcmRlciBOby5cIiB2YWx1ZT1cIjJcIiAvPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJUZWxcIiB2YWx1ZT1cIjNcIiAvPlxuICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8dGVtcGxhdGUgI2FwcGVuZD5cbiAgICAgICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBTZWFyY2ggfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGlucHV0MSA9IHJlZignJylcbmNvbnN0IGlucHV0MiA9IHJlZignJylcbmNvbnN0IGlucHV0MyA9IHJlZignJylcbmNvbnN0IHNlbGVjdCA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uaW5wdXQtd2l0aC1zZWxlY3QgLmVsLWlucHV0LWdyb3VwX19wcmVwZW5kIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtZmlsbC1jb2xvci1ibGFuayk7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIFxuICA8ZGl2IGNsYXNzPVwibXQtNFwiPlxuICAgIDxlbC1pbnB1dFxuICAgICAgICAgICAgICBzaXplPSdsYXJnZSdcbiAgICAgIHYtbW9kZWw9XCJpbnB1dDNcIlxuICAgICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAgICAgY2xhc3M9XCJpbnB1dC13aXRoLXNlbGVjdFwiXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICNwcmVwZW5kPlxuICAgICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJzZWxlY3RcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIHN0eWxlPVwid2lkdGg6IDExNXB4XCI+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlJlc3RhdXJhbnRcIiB2YWx1ZT1cIjFcIiAvPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJPcmRlciBOby5cIiB2YWx1ZT1cIjJcIiAvPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJUZWxcIiB2YWx1ZT1cIjNcIiAvPlxuICAgICAgICA8L2VsLXNlbGVjdD5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8dGVtcGxhdGUgI2FwcGVuZD5cbiAgICAgICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtaW5wdXQ+XG4gIDwvZGl2PlxuICBcbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBTZWFyY2ggfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGlucHV0MSA9IHJlZignJylcbmNvbnN0IGlucHV0MiA9IHJlZignJylcbmNvbnN0IGlucHV0MyA9IHJlZignJylcbmNvbnN0IHNlbGVjdCA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uaW5wdXQtd2l0aC1zZWxlY3QgLmVsLWlucHV0LWdyb3VwX19wcmVwZW5kIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tZWwtZmlsbC1jb2xvci1ibGFuayk7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

### What is Expected?

Subcomponent inheritance style

### What is actually happening?

Subcomponent not inheritance style

### Additional comments

https://github.com/element-plus/element-plus/pull/9006

**Comment by mxp131011** [comment]
el-select  add  type="larger"  ` <el-select v-model="select" placeholder="Select" size='large' style="width: 115px">`

**Comment by chenxch** [comment]
You need to add the `size` yourself.
