### ISSUE TITLE
ElDrawer参数modal设置为false会导致弹窗无法正常展示，控制项没有可以关闭蒙版点击事件的选项

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#901]
### 一、参数modal设置为false会导致弹窗无法正常展示
代码
``
<el-drawer
  title="我是标题"
  v-model="drawer"
  :direction="direction"
           :modal="false"
  :before-close="handleClose" destroy-on-close>
  <span>我来啦!</span>
</el-drawer>
``
通过官网的调试功能，和目前我个人代码中的环境都会产生问题。
版本：^1.0.1-beta.5
二、控制项没有可以关闭蒙版点击事件的选项
没有像弹窗ElDialog参数close-on-click-modal一样，可以控制关闭半透明蒙版的点击事件参数

**Comment by JeremyWuuuuu** [comment]
Indeed, I reproduced this, the modal currenly parenting el-drawer will be turned off with modal flag set to false with a display: none

**Comment by JeremyWuuuuu** [comment]
In this case the drawer's width and height will have no relative object referring to. Will be fixed

**Comment by iamkun** [comment]
@jsliu27 can you please check the latest version of element plus?
