### ISSUE TITLE
[Component] [table]  当显示合计且仅设置最大高度（即设置 max-height ，不设置height ）时最大高度不正确

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#9010]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6bWF4LWhlaWdodD1cIjIwMFwiIHNob3ctc3VtbWFyeSA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkNvc3RcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAgIHsgIGlkOiAnMScsIG5hbWU6ICdUb20xJywgYW1vdW50MzogMTIgfSxcbiAgIHsgIGlkOiAnMicsIG5hbWU6ICdUb20yJywgYW1vdW50MzogMTIgfSxcbiAgIHsgIGlkOiAnMycsIG5hbWU6ICdUb20zJywgYW1vdW50MzogMTIgfSxcbiAgIHsgIGlkOiAnNCcsIG5hbWU6ICdUb200JywgYW1vdW50MzogMTIgfSxcbiAgIHsgIGlkOiAnNScsIG5hbWU6ICdUb201JywgYW1vdW50MzogMTIgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

 当显示合计且仅设置最大高度（即设置 max-height ，不设置height ）时，滚动条高度不正确，最后一行会被合计行遮挡
如例子中本应该完整显示5行，可实际上只可以看到4行，第5行被合计行遮挡住了

### What is Expected?

最后一行不被合计行遮挡

### What is actually happening?

最后一行被合计行遮挡

### Additional comments

_(empty)_

**Comment by gengyanlei** [comment]
vue3.2.36
element-plus2.2.10
icon均不能显示！！！！！！！！！！！
element-plus2.2.10对应的vue版本是多少呢？
