### ISSUE TITLE
[Component] [loading] The loading component type is incorrect

### ISSUE THREAD

**Issue by zhazhazhu** [element-plus/element-plus#9012]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuY29uc3QgY29udGFpbmVyID0gcmVmPEVsZW1lbnQ+KClcblxuY29uc3QgbG9hZGluZ0luc3RhbmNlID0gcmVmKClcblxuY29uc3QgbG9hZGluZyA9ICgpPT4gRWxMb2FkaW5nLnNlcnZpY2UoeyBmdWxsc2NyZWVuOiB0cnVlLGJhY2tncm91bmQ6J3JnYmEoMCwwLDAsMC43KScsdGV4dDpcImxvYWRpbmdcIix0YXJnZXQ6Y29udGFpbmVyLnZhbHVlIH0pXG5cbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gbG9hZGluZ0luc3RhbmNlLnZhbHVlID0gbG9hZGluZygpXG4gbG9hZGluZ0luc3RhbmNlLnZhbHVlLnNldFRleHQoJ25ldyB0ZXh0JylcbiAvL1RoZSBiYWNrZ3JvdW5kIGNvbG9yIGF0dHJpYnV0ZSB0eXBlIG9mIGxvYWRpbmcgaXMgUmVmPHN0cmluZz4sIGJ1dCB0aGUgYWN0dWFsIHR5cGUgaXMgbm90XG4gLy9sb2FkaW5nSW5zdGFuY2UudmFsdWUuYmFja2dyb3VuZC52YWx1ZSA9ICdyZ2JhKDAsMCwwLDAuMSknIC8vZXJyb3JcbiAgXG4gbG9hZGluZ0luc3RhbmNlLnZhbHVlLmJhY2tncm91bmQgPSAncmdiYSgwLDAsMCwwLjEpJyAvL3N1Y2Nlc3Ncbn1cblxuY29uc3QgY2xvc2UgPSAoKT0+IHtcbiAgbG9hZGluZ0luc3RhbmNlLnZhbHVlLmNsb3NlKClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgcmVmPVwiY29udGFpbmVyXCIgc3R5bGU9J3dpZHRoOjEwMCU7aGVpZ2h0OjIwMHB4O2JvcmRlcjoxcHggc29saWQnPjwvZGl2PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cIm9wZW5cIj5vcGVuIGxvYWRpbmc8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjbG9zZVwiPmNsb3NlIGxvYWRpbmc8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1:ElLoading.service({ fullscreen: true,background:'rgba(0,0,0,0.7)',text:"loading",target:container.value })
2:loadingInstance.value.background.value = 'rgba(0,0,0,0.1)'//error

### What is Expected?

type of loadingInstance.value.background.value is Ref<string>

### What is actually happening?

but the actual type is not

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
如果不是ref后续赋值的background是不会生效的哦。设计如此，没有其他问题的话我将关闭这个issue了。
