### ISSUE TITLE
[Component] [upload] 【Upload 上传】组件属性list-type="picture"时，on-preview钩子函数无效，触发不了

### ISSUE THREAD

**Issue by a452746100** [element-plus/element-plus#9013]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.10`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/upload.html#%E5%9B%BE%E7%89%87%E5%88%97%E8%A1%A8%E7%BC%A9%E7%95%A5%E5%9B%BE)

### Steps to reproduce

1：打开官网文档组件-Upload 上传
2：选择图片列表缩略图
3：点击上面的已上传图片
4：F12控制台没有任何打印信息（如果点击删除按钮，控制台是又console信息的）

### What is Expected?

on-preview钩子函数能正常触发

### What is actually happening?

on-preview钩子函数无法触发，点击无反应

### Additional comments

官网文档上的组件示例也无法触发的，希望尽快修复下

**Comment by jellyhui** [comment]
碰到了同样的问题，请问您是怎么解决的？
