### ISSUE TITLE
[Component] [table, table-column] table 组件, 直接通过浏览器的 HTML 标签导入 Element Plus的试试 样式完全没

### ISSUE THREAD

**Issue by yuwade** [element-plus/element-plus#9014]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```html
<div id="app">
      <el-button>{{ message }}</el-button>
        <el-table :data="tableData" border style="width: 100%">
        <el-table-column prop="date" label="Date" width="180" />
        <el-table-column prop="name" label="Name" width="180" />
        <el-table-column prop="address" label="Address" />
      </el-table>
    </div>
```

```js
     const App = {
        data() {
          return {
            message: "Hello Element Plus",
            tableData:[]
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");
```

### What is Expected?

正常显示

### What is actually happening?

正常显示

### Additional comments

最小复现环境的链接是错误的地址,  Element Plus Playground 不能打开cdn版本的
https://codepen.io/iamkun/pen/YzWMaVr 在这里可以复现

**Comment by yuwade** [comment]
![image](https://user-images.githubusercontent.com/15152506/180767428-dd72bc2d-07da-428f-8c71-0bcf105fa032.png)

**Comment by plainheart** [comment]
Please refer to the [FAQ](https://element-plus.org/zh-CN/component/table.html#%E5%BD%93%E4%BD%BF%E7%94%A8-dom-%E6%A8%A1%E6%9D%BF%E6%97%B6%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%97%E6%B2%A1%E6%9C%89%E6%B8%B2%E6%9F%93%EF%BC%9F). See also #5046

**Comment by yuwade** [comment]
OK
