### ISSUE TITLE
[alert] Alert显示隐藏问题

### ISSUE THREAD

**Issue by acyza** [element-plus/element-plus#9020]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0`
- Build Tool: `Vite`

### Related Component

- `el-alert`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzaG93PXJlZihmYWxzZSlcblxuY29uc3Qgc2hvd0FsZXJ0PWZ1bmN0aW9uKCl7XG4gIHNob3cudmFsdWU9dHJ1ZVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYWxlcnQgdGl0bGU9XCJlcnJvclwiIHR5cGU9XCJlcnJvclwiIHYtc2hvdz1cInNob3dcIi8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwic2hvd0FsZXJ0XCI+5pi+56S6YWxlcnQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击关闭按钮关闭alert后将v-show设为true，alert无法重新显示

### What is Expected?

alert重新显示

### What is actually happening?

alert无法显示，且display手动设置为flex关闭按钮失效

### Additional comments

单个页面的alert可能反复使用，例如登录界面的用户名密码错误提示，建议加个显示alert的参数。

**Comment by daonatural** [comment]
alert组件从element-ui (vue2) 开始就是如此的使用方式。它没有一个单独的双向绑定的值去接收显示与否的状态。而点击close关闭也只是在css层面修改alert组件的display属性值 由 `flex` -> `none`。所以如果需alert被反复使用。建议手动触发 `@close` 事件，主动修改`v-show`的状态

[Element Plus Alert Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzaG93PXJlZihmYWxzZSlcblxuY29uc3Qgc2hvd0FsZXJ0PWZ1bmN0aW9uKCl7XG4gIHNob3cudmFsdWU9dHJ1ZVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYWxlcnQgdGl0bGU9XCJlcnJvclwiIHR5cGU9XCJlcnJvclwiIHYtc2hvdz1cInNob3dcIiBAY2xvc2U9XCJzaG93ID0gZmFsc2VcIi8+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwic2hvd0FsZXJ0XCI+5pi+56S6YWxlcnQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

至于【display手动设置为flex关闭按钮失效】的问题，因为alert内部也有一个`visible`变量控制内部的`v-show`。在已经是关闭状态时（visible 为false），不会再去主动修改`display`。所以这个是不是bug也许就是见仁见智吧.... 如果正常使用很少有可能这样去操作alert组件的
