### ISSUE TITLE
Element Plus 如何引用单个组件中的 js

### ISSUE THREAD

**Issue by salonglong** [element-plus/element-plus#903]
各位朋友，有没有办法把 Element Plus 单个组件的 js 导出来，以 <script src=""></script> 方式在网站中引入，用到非脚手架的项目中？

**Comment by zazzaz** [comment]
I'm afraid there's no umd bundle for a single component ATM. 

But we can support if there's a need.

Any reason you'd like to import it via the html script tag?

**Comment by salonglong** [comment]
Hello, yes.

I just want to use some components, load the full JS file, it's too big.

**Comment by JeremyWuuuuu** [comment]
Try this 
`https://unpkg.com/element-plus@1.0.1-beta.5/lib/el-[componentName]`

**Comment by xiaoxian521** [comment]
我认为这样并不可行 因为这个组件还依赖别的js文件 会出现找不到的清空
最新版本的vue-cli还不支持打包umd吧

**Comment by salonglong** [comment]
> Try this
> `https://unpkg.com/element-plus@1.0.1-beta.5/lib/el-[componentName]`
> For example, if you wanted to use `ElMessage`
> Try it with this link
> https://unpkg.com/element-plus@1.0.1-beta.5/lib/el-message
> 
> In this case you might end up lacking some kind library, e.g. `Lodash`, you will need to import them first, also, the package was built in `esm` format, you cannot use like `commonjs` nor `umd`

Not so, will prompt: ElMessage is not defined

**Comment by JeremyWuuuuu** [comment]
> > Try this
> > `https://unpkg.com/element-plus@1.0.1-beta.5/lib/el-[componentName]`
> > For example, if you wanted to use `ElMessage`
> > Try it with this link
> > https://unpkg.com/element-plus@1.0.1-beta.5/lib/el-message
> > In this case you might end up lacking some kind library, e.g. `Lodash`, you will need to import them first, also, the package was built in `esm` format, you cannot use like `commonjs` nor `umd`
> 
> Not so, will prompt: ElMessage is not defined

Mind show some code? I'm not following 

Since we now have vite thanks to Evan, you might just use vite to skip the bundling when developing. If you really need load on demand try Vite. Now we don't have plans to release individual packages with umd format. That might need to wait until the first stable version

**Comment by salonglong** [comment]
感谢各位的回复，我已经将 Element 中的 ts 进行改造，单独拿出来用，完全没有问题。
