### ISSUE TITLE
[Component] 图片预览放到表格中会出现样式渲染错误

### ISSUE THREAD

**Issue by naihe138** [element-plus/element-plus#9039]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`
- `el-image`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gIH0sXG5dXG5jb25zdCBzcmNMaXN0ID0gW1xuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzEvMzQvMTlhYTk4YjFmY2IyNzgxYzRmYmEzM2Q4NTA1NDlqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzAvNmYvZTM1ZmYzNzU4MTJlNmIwMDIwYjZiNGU4Zjk1ODNqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzkvYmIvZTI3ODU4ZTk3M2Y1ZDdkMzkwNDgzNWY0NmFiYmRqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2QvZTYvYzRkOTNhMzgwNWIzY2UzZjMyM2Y3OTc0ZTZmNzhqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvMjgvYmJmODkzZjc5MmYwM2E1NDQwOGIzYjdhN2ViZjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzIvMTEvNjUzNWJjZmIyNmU0Yzc5YjQ4ZGRkZTQ0ZjRiNmZqcGVnLmpwZWcnLFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogNDAwcHhcIiBib3JkZXI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMjAwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIyMDBcIj5cbiAgICBcdCA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICAgPGVsLWltYWdlXG4gICAgICAgICAgICAgICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwcHg7IGhlaWdodDogMTAwcHhcIlxuICAgICAgICAgICAgICAgICAgIHNyYz1cImh0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnXCJcbiAgICAgICAgICAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgICAgICAgICAgICAgIDppbml0aWFsLWluZGV4PVwiNFwiXG4gICAgICAgICAgICAgICAgICAgZml0PVwiY292ZXJcIlxuICAgICAgICAgICAgICAgICAgIC8+XG4gICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、表格嵌套图片预览
2、点击图片预览
3、渲染出错

### What is Expected?

不出现渲染样式问题

### What is actually happening?

出现渲染样式问题

### Additional comments

_(empty)_

**Comment by btea** [comment]
https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89

**Comment by naihe138** [comment]
谢谢大佬 @btea
