### ISSUE TITLE
timepicker 不支持 键盘上下切换

### ISSUE THREAD

**Issue by shlroland** [element-plus/element-plus#904]
![image](https://user-images.githubusercontent.com/45024986/101570993-79125900-3a12-11eb-97a7-1ee399821b35.png)

**Comment by JeremyWuuuuu** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by shlroland** [comment]
https://element-plus.gitee.io/#/zh-CN/component/time-picker

**Comment by JeremyWuuuuu** [comment]
How exactly do I reproduce it?
Can you provide some reproducing operations?
Like first second then

**Comment by Ryan2128** [comment]
Maybe he meant that cannot use the arrow keys on the keyboard to change the value when the panel is open.

**Comment by shlroland** [comment]
yes. i cannt use use arrow keys like up or down to change value

**Comment by zazzaz** [comment]
will fix

**Comment by shlroland** [comment]
> will fix

and when trigger mouseenter event in time-spinner, the value cannt be selected

**Comment by JeremyWuuuuu** [comment]
> > will fix
> 
> and when trigger mouseenter event in time-spinner, the value cannt be selected

Could you provide some demo?

**Comment by shlroland** [comment]
> > > will fix
> > 
> > 
> > and when trigger mouseenter event in time-spinner, the value cannt be selected
> 
> Could you provide some demo?

when i trigger mouseenter on spinner, the string will be selected 
![image](https://user-images.githubusercontent.com/45024986/101726838-3e7dee80-3aee-11eb-8c45-c7623cca3866.png)
but in element-plus，it doesnt work

**Comment by serializedowen** [comment]
packages/time-picker/src/common/picker.vue#L22    refContainer一直获取不到值，原因有待排查
