### ISSUE TITLE
[Component] [upload] upload 组件  设置 limit 和 on-exceed 不可以在选中时自动替换上一个文件

### ISSUE THREAD

**Issue by wangzhaoqiang666** [element-plus/element-plus#9041]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `chrome  103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgcmVmPVwidXBsb2FkXCJcbiAgICBjbGFzcz1cInVwbG9hZC1kZW1vXCJcbiAgICBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgIDpsaW1pdD1cIjFcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICAgIDphdXRvLXVwbG9hZD1cImZhbHNlXCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjdHJpZ2dlcj5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5zZWxlY3QgZmlsZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWJ1dHRvbiBjbGFzcz1cIm1sLTNcIiB0eXBlPVwic3VjY2Vzc1wiIEBjbGljaz1cInN1Ym1pdFVwbG9hZFwiPlxuICAgICAgdXBsb2FkIHRvIHNlcnZlclxuICAgIDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwIHRleHQtcmVkXCI+XG4gICAgICAgIGxpbWl0IDEgZmlsZSwgbmV3IGZpbGUgd2lsbCBjb3ZlciB0aGUgb2xkIGZpbGVcbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdXBsb2FkPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IGdlbkZpbGVJZCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB0eXBlIHsgVXBsb2FkSW5zdGFuY2UsIFVwbG9hZFByb3BzLCBVcGxvYWRSYXdGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCB1cGxvYWQgPSByZWY8VXBsb2FkSW5zdGFuY2U+KClcblxuY29uc3QgaGFuZGxlRXhjZWVkOiBVcGxvYWRQcm9wc1snb25FeGNlZWQnXSA9IChmaWxlcykgPT4ge1xuICB1cGxvYWQudmFsdWUhLmNsZWFyRmlsZXMoKVxuICBjb25zdCBmaWxlID0gZmlsZXNbMF0gYXMgVXBsb2FkUmF3RmlsZVxuICBmaWxlLnVpZCA9IGdlbkZpbGVJZCgpXG4gIHVwbG9hZC52YWx1ZSEuaGFuZGxlU3RhcnQoZmlsZSlcbn1cblxuY29uc3Qgc3VibWl0VXBsb2FkID0gKCkgPT4ge1xuICB1cGxvYWQudmFsdWUhLnN1Ym1pdCgpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

直接上传文件就行。

### What is Expected?

选择下一个文件时自动替换上一个文件

### What is actually happening?

没有替换掉

### Additional comments

_(empty)_

**Comment by bleakwind** [comment]
我今天刚update后也发现了这个问题...

**Comment by sxzz** [comment]
尝试最新版本，如有问题请重新打开本issue
