### ISSUE TITLE
[Component] [select] Select组件设置了disabled为true后仍可使用

### ISSUE THREAD

**Issue by WeiYaohong** [element-plus/element-plus#9043]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.10`
- Browser / OS: `CHROME`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJtc2dcIlxuICAgICAgY2xhc3M9XCJtLTJcIlxuICAgICAgY2xlYXJhYmxlXG4gICAgICBkaXNhYmxlZFxuICAgICAgcGxhY2Vob2xkZXI9XCLor7fpgInmi6lcIlxuICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIGtleT1cIml0ZW1cIlxuICAgICAgICBsYWJlbD1cIml0ZW1cIlxuICAgICAgICB2YWx1ZT1cIml0ZW1cIlxuICAgICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgIGtleT1cIml0ZW0yXCJcbiAgICAgICAgbGFiZWw9XCJpdGVtMlwiXG4gICAgICAgIHZhbHVlPVwiaXRlbTJcIlxuICAgICAgLz5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgIGtleT1cIml0ZW0zXCJcbiAgICAgICAgbGFiZWw9XCJpdGVtM1wiXG4gICAgICAgIHZhbHVlPVwiaXRlbTNcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

el-select设置disabled，页面上点击组件

### What is Expected?

设置disabled后组件禁用

### What is actually happening?

依旧可以使用

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
fix: https://github.com/element-plus/element-plus/commit/8387f6dac63f89839c944e5f6b8c69cb0dc79b05
next version release

**Comment by aliezzzz** [comment]
same problem on my project
Element Plus Version: 2.2.11

**Comment by BobLiu11** [comment]
遇到了同样的问题
