### ISSUE TITLE
[Component] [date-picker] 日期选择器，type="datetimerange"，bug问题

### ISSUE THREAD

**Issue by crinbug4** [element-plus/element-plus#9045]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome/101.0.0.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/datetime-picker.html#%E6%97%A5%E6%9C%9F%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F)

### Steps to reproduce

type="datetimerange"下，选择开始结束时间，确认，点击清除

### What is Expected?

不会弹出下拉框选择框

### What is actually happening?

下拉框选择框闪烁

### Additional comments

应该是弹出选择框事件和清除事件重叠，应该阻止冒泡

**Comment by xiaoxian521** [comment]
It has been fixed, please wait for the next release
