### ISSUE TITLE
[Docs] [All] element-plus 官网偶然会炸了

### ISSUE THREAD

**Issue by InfernalAzazel** [element-plus/element-plus#9055]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

访问官网

### What is Expected?

正常访问

### What is actually happening?

偶尔挂了

### Additional comments

_(empty)_

![Screenshot from 2022-07-27 17-03-59](https://user-images.githubusercontent.com/40333954/181208984-7f287544-f396-4d8f-9a3f-c559bd6168b5.png)

![Screenshot from 2022-07-27 17-12-21](https://user-images.githubusercontent.com/40333954/181209939-2fd1e042-b472-4814-9622-24dd3fd1bf8f.png)

**Comment by InfernalAzazel** [comment]
通过多次刷新又正常能用

**Comment by doooooit** [comment]
![image](https://user-images.githubusercontent.com/11793795/181220974-ac853dfa-bdd2-442a-9ed2-7b5d1c72fa4a.png)

同样问题，今天下午就没打开过，刷新几次都是

**Comment by m13886695261** [comment]
官网确实很难用，plus的org和gitee我都是双开，仍然慢的不行，要不就给你整503和no found。顶部的search搜出来的都是en-us，我不是设置了中文吗

**Comment by chenxch** [comment]
#9196
