### ISSUE TITLE
[Component] [select] 打开筛选(filterable)状态下，一旦点击了empty插槽区域后再回到输入框，下拉框再也不会弹出来(附gif)

### ISSUE THREAD

**Issue by funsunz** [element-plus/element-plus#9058]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: ` Chrome 103.0.5060.134（正式版本） (x86_64) / macOS Big Sur 11.6.7`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html#%E7%AD%9B%E9%80%89%E9%80%89%E9%A1%B9)

### Steps to reproduce

可在官网select选择器-筛选选项复现：
1.点击select组件输入框输入"on12",下拉框显示“No matching data”;
2.点击“No matching data”，接着点击回输入框，此时输入任何内容下拉框都不会再弹出来

### What is Expected?

点击“No matching data”后再点回输入框可弹出下拉框

### What is actually happening?

点击“No matching data”后再点回输入框无论输入什么都不会再弹出下拉框

### Additional comments
如图所示
<img src="https://user-images.githubusercontent.com/3307169/181264166-1748963b-7738-465e-887e-947bb74de722.gif " width="400" />

**Comment by nodserve** [comment]
遇到同样的问题，同等。

**Comment by Sweet-KK** [comment]
我遇到类似的问题是输入后直接点击输入的值会触发输入被清空，然后再点击输入框，不会弹出也不会触发`filter-method`  需要多点击几次才好

**Comment by Benleie** [comment]
有点意思，坐等

**Comment by wgxg777** [comment]
坐等

**Comment by iwusong** [comment]
在外面多点一下就好了

**Comment by init-qy** [comment]
Maybe fix in 2.2.18

**Comment by Benleie** [comment]
@chenxch  @tolking @Giwayume Hey, I think this bug has been fixed by [PR 9941](https://github.com/element-plus/element-plus/pull/9941) (merged in 2.2.18).
