### ISSUE TITLE
[Component] 使用中遇到的各种bug

### ISSUE THREAD

**Issue by Lovecxgood** [element-plus/element-plus#9060]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- vite 3.0.3
- Element Plus Version: `2.2.11`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-dialog`
- `el-icon`
- `el-message`

### Reproduction Link

[Docs CN]( https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)

### Steps to reproduce

el-icon vite构建环境下 自动导入配置下 自动导入后不会显示 全部导入好用 
https://element-plus.gitee.io/zh-CN/component/icon.html#%E8%87%AA%E5%8A%A8%E5%AF%BC%E5%85%A5
el-input 在最新版本2.2.11下自动导入和全部导入都不好用了 应该是这个版本出的问题
el-dialog  自动导入配置下 遮罩层锁定滚动功能不好用  全部导入情况下在两个dialog相互切换后遮罩层滚动锁定不好用   
el-message  自动导入配置下不好用 全部导入好用

### What is Expected?

正常

### What is actually happening?

不正常

### Additional comments

大多数问题都是出现在自动导入vite的自动导入配置下 应该还有一些问题待发现。。。

**Comment by Lovecxgood** [comment]
按需导入下  el-mesage 不会显示  以上组件出现的问题 控制台上也不会出现错误或者警告提示等  就是不好用

**Comment by Lovecxgood** [comment]
刚才又试了几次 按需导入模式下  el-mesage  是会出现在页面的左下方  而且没有样式    完全导入模式下  是好使的

**Comment by Lovecxgood** [comment]
colorpicker 组件点击确定或者清空按钮后  取色弹出面板会在页面左上方闪现一下

**Comment by btea** [comment]
方便提供一个可复现的仓库吗？

**Comment by Lovecxgood** [comment]
> 方便提供一个可复现的仓库吗？

公司项目暂时不方便提供仓库，等我有时间弄个简单的demo吧   也很好复现就按着你们按需导入文档配置就好

**Comment by Lovecxgood** [comment]
colorpicker  组件会导致页面中所有的el-input组件不可输入也包括原生的input

**Comment by jing-ge-star** [comment]
> colorpicker 组件会导致页面中所有的el-input组件不可输入也包括原生的input

我也遇到这个问题了，很严重

**Comment by btea** [comment]
> colorpicker 组件会导致页面中所有的el-input组件不可输入也包括原生的input

fixed #9061

**Comment by jing-ge-star** [comment]
> > colorpicker 组件会导致页面中所有的el-input组件不可输入也包括原生的input
> 
> fixed #9061

希望可以尽快发布新版本，减少影响范围，主版本不太应该出现类似状况

**Comment by ZeroJsus** [comment]
el-icon 这个我也遇到了

**Comment by suntaiyang520** [comment]
自动导入，使用AutoImport插件的前提下，有时候在修改完 scss 样式后，ctrl+s，保存后，在打开弹出层等空间时，会导致样式丢失。

**Comment by holazz** [comment]
> 刚才又试了几次 按需导入模式下 el-mesage 是会出现在页面的左下方 而且没有样式 完全导入模式下 是好使的

这个你需要手动导入样式，文档里有说明 https://element-plus.org/en-US/guide/quickstart.html#manually-import

**Comment by holazz** [comment]
> el-icon 这个我也遇到了

能提供个可复现 demo 吗？`unplugin-vue-components` 的版本是多少

**Comment by coderezc** [comment]
请问想要看旧版本的文档在哪里看呀？官网好像没有可以选版本的地方？

**Comment by ZeroJsus** [comment]
> > el-icon 这个我也遇到了
> 
> 能提供个可复现 demo 吗？`unplugin-vue-components` 的版本是多少


内部项目无法提供复现的demo

版本是0.21.2，使用autoImport 页面上能够展示元素，但是对应的图标元素内容为空

![image](https://user-images.githubusercontent.com/19191127/182054715-33c66e5e-e5b9-4826-8263-58ff3b734c7e.png)
