### ISSUE TITLE
[Style] [button] 按钮大小默认大小BUG

### ISSUE THREAD

**Issue by LRT-stack** [element-plus/element-plus#9062]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.11`
- Browser / OS: `windows10`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html#%E8%B0%83%E6%95%B4%E5%B0%BA%E5%AF%B8)

### Steps to reproduce

<el-button>Default</el-button>
<el-button size="small">Small</el-button>

### What is Expected?

按钮大小正常大小

### What is actually happening?

按钮default属性(不加size="default"时)的按钮大小和按钮small属性的按钮一样大

### Additional comments

尽快修复吧，这么低级明显的BUG不应该出现

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/181245881-c6141a20-01ee-462f-ab9c-7a85fe8eb636.png)
我这是正常的

**Comment by chenxch** [comment]
是否是用了Config Provider？

**Comment by kooriookami** [comment]
如果没有疑问的话，我先把它关闭了。
