### ISSUE TITLE
Elementplus does not work when installed in the devDependencies of the vite project

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#907]
> Uncaught SyntaxError: The requested module '/@modules/lodash/debounce.js' does not provide an export named 'default'

Perhaps [lodash-es](https://www.npmjs.com/package/lodash-es) should be used instead of lodash

Maybe dayjs will also have this problem

    "element-plus": "^1.0.1-beta.5",
    "vite": "^1.0.0-rc.13",
    "vue": "^3.0.3",
    "vue-router": "^4.0.1"

**Comment by xiaoxian521** [comment]
It can be used. You can take a look at this example: https://github.com/xiaoxian521/CURD-TS/tree/vue-ts

**Comment by JeremyWuuuuu** [comment]
> https://github.com/xiaoxian521/CURD-TS/tree/vue-ts

Guess what, didn't find any reference in your repo using `lodash` on branch `main`

**Comment by JeremyWuuuuu** [comment]
> > Uncaught SyntaxError: The requested module '/@modules/lodash/debounce.js' does not provide an export named 'default'
> 
> Perhaps [lodash-es](https://www.npmjs.com/package/lodash-es) should be used instead of lodash
> 
> Maybe dayjs will also have this problem
> 
> ```
> "element-plus": "^1.0.1-beta.5",
> "vite": "^1.0.0-rc.13",
> "vue": "^3.0.3",
> "vue-router": "^4.0.1"
> ```

Well I guess `Vite`'s requirement is just harsh. We will find out a workaround on this.

**Comment by tolking** [comment]
Elementplus does not work when installed in the devDependencies of the vite project, But when it is installed in dependencies, it will work.

**Comment by JeremyWuuuuu** [comment]
Since `ElementPlus` should be appeared in `dependencies` I think you should correct that, and I dunno if this is something caused by `Vite` or not. Unless you can provide a demo repo for us to reproduce.

**Comment by tolking** [comment]
clone element-plus-vite-starter and move `"element-plus": "latest"` in to the `devDependencies`
This may not be Elementplus wrong, but the same config work in element-plus-starter
I will close this issues
