### ISSUE TITLE
[Component] [popover] el-popover 在设置了visible的情况下仍受trigger控制 still controlled by trigger when v-model:visible is set

### ISSUE THREAD

**Issue by YujiaCheng1996** [element-plus/element-plus#9070]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Windows11 Chrome/103.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBrZXlXb3JkID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgaXNQb3BvdmVyU2hvdyA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1wb3BvdmVyXG4gICAgdi1tb2RlbDp2aXNpYmxlPVwiaXNQb3BvdmVyU2hvd1wiXG4gICAgd2lkdGg9XCIxMDB2d1wiXG4gICAgdHJpZ2dlcj1cImZvY3VzXCJcbiAgICA6cG9wcGVyLW9wdGlvbnM9XCJ7XG4gICAgICBtb2RpZmllcnM6IFtcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdmbGlwJyxcbiAgICAgICAgICBvcHRpb25zOiB7XG4gICAgICAgICAgICBwYWRkaW5nOiA1LFxuICAgICAgICAgICAgZmFsbGJhY2tQbGFjZW1lbnRzOiBbJ2JvdHRvbS1zdGFydCcsICd0b3Atc3RhcnQnLCAncmlnaHQnLCAnbGVmdCddLFxuICAgICAgICAgIH0sXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnY29tcHV0ZVN0eWxlcycsXG4gICAgICAgICAgb3B0aW9uczoge1xuICAgICAgICAgICAgZ3B1QWNjZWxlcmF0aW9uOiB0cnVlLFxuICAgICAgICAgICAgYWRhcHRpdmU6IHRydWUsXG4gICAgICAgICAgfSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfVwiXG4gID5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsPVwia2V5V29yZFwiXG4gICAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgICBAZm9jdXMucHJldmVudC5zdG9wPVwiXCJcbiAgICAgID5cbiAgICAgIDwvZWwtaW5wdXQ+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICBIZWxsbyBXb3JsZCFcbiAgICA8L2Rpdj5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

El-popover binding to an el-input shows when user press the enter key, even though v-model:visible is bound.
popover绑了model:visible,用户在input回车还是会显示。

### What is Expected?

only v-model:visible can control el-popover's visiblity or set trigger to undefined/"off" to allow total control.
绑了visible就只有绑定的布尔值能控制，要不给个‘off’的trigger来关闭trigger的影响，只让visible起作用

### What is actually happening?

v-model:visible and trigger work simultaneously.
同时能控制，且无法关闭trigger的触发。

### Additional comments

2.2.9还是正常的，2.2.10起行为改变。做搜索下拉时，不允许用户按回车键就重复搜索，必须值发生更改且做防抖后才搜索。

**Comment by yaomk** [comment]
```
<el-popover
    v-model:visible="isPopoverShow"
    width="100vw"
    trigger="focus">
</el-popver>
```
绑定 `visible` 时，去掉 `v-model`，如 `:visible='isPopoverShow'`，
看文件变动，2.2.10版本的 `popver` 相关的组件内部取值、更新值方式貌似发生了变化，`v-model:visible`双向绑定的没生效，`:visible` 没有双向绑定的是可以的 

[](https://github.com/element-plus/element-plus/pull/8762/files)

**Comment by YujiaCheng1996** [comment]
确实，官网文档需要更新了。
