### ISSUE TITLE
[Component] el-tree组件包含el-checkbox-group或el-select组件发生异常

### ISSUE THREAD

**Issue by Wei-Ba** [element-plus/element-plus#9073]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-checkbox-group`
- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgc2VsZWN0ID0gcmVmKCcnKVxuY29uc3QgY2hlY2tMaXN0ID0gcmVmPHN0cmluZ1tdPihbXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10cmVlIDpkYXRhPVwiW3tsYWJlbDonc2VsZWN0J30se2xhYmVsOidjaGVja2JveCd9XVwiPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cIntub2RlOntsYWJlbH19XCI+XG4gICAgICA8ZWwtc2VsZWN0ICB2LWlmPVwibGFiZWwgPT09ICdzZWxlY3QnXCIgdi1tb2RlbD1cInNlbGVjdFwiPlxuICAgICAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiaSBpbiA2XCIgOmtleT1cImlcIiA6bGFiZWw9XCJpXCIgOnZhbHVlPVwiaVwiPjwvZWwtb3B0aW9uPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICA8ZWwtY2hlY2tib3gtZ3JvdXAgdi1lbHNlIHYtbW9kZWw9XCJjaGVja0xpc3RcIj5cbiAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsID0gXCJ0ZXN0XCI+PC9lbC1jaGVja2JveD5cbiAgICAgIDwvZWwtY2hlY2tib3gtZ3JvdXA+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10cmVlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击select组件与checkbox组件

### What is Expected?

组件均正常选中

### What is actually happening?

抛出`Cannot read properties of undefined (reading 'validate')`的异常,在部分情况下需要点击两次才能完成响应的效果(首次无效果,报错依旧)

### Additional comments

在[forum.vuejs.org](https://forum.vuejs.org/t/el-tree-el-checkbox-group-bug/131202/4)上由@jyk0011发现的问题
原因是在近期更新中`el-tree`组件中[tree.vue](https://github.com/element-plus/element-plus/tree/dev/packages/components/tree/src/tree.vue)添加了以下代码
```typescript
/* 372行 */
provide(formItemContextKey, undefined)
```
导致了使用了`formItemContextKey`组件在表单验证时未处理`elFormItem`为`undefined`的情景，相同情景下旧版本为空对象`{}`
例如`el-checkbox`的[el-checkbox-group](https://github.com/element-plus/element-plus/tree/dev/packages/components/checkbox/src/checkbox-group.vue)
```typescript
/* 65行 */
watch(
  () => props.modelValue,
  () => {
    if (props.validateEvent) {
      elFormItem.validate?.('change').catch((err) => debugWarn(err))
    }
  }
)
```
应该来说所有使用了该token的组件(未更改的话)包含在`el-tree`里或多或少都有点影响(虽然也不知道为什么要放在`el-tree`里面)
* 如果不需要覆盖`el-from`组件的表单验证,移除`el-tree`中的新增代码就行
* 如果需要覆盖`el-from`组件的表单验证,将`el-tree`中的新增代码改为`{}`就行

**Comment by holazz** [comment]
Maybe fix by #8865 and #8860
