### ISSUE TITLE
[Component] [select] el-select的change回调中调用了ElMessageBox.confirm确认框后，el-select不会关闭，会重复focus

### ISSUE THREAD

**Issue by wp993080086** [element-plus/element-plus#9077]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.7`
- Browser / OS: `Chrome/103.0.5060.66；Windows 10 家庭中文版 x64`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbmNvbnN0IGhhbmRsZUNoYW5nZSA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmNvbmZpcm0oJ+a1i+ivleS4gOS4iycsJ1dhcm5pbmcnKS50aGVuKCgpID0+IHtcbiAgICBjb25zb2xlLmxvZygn56Gu6K6kJylcbiAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKCflj5bmtognKVxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1，点击el-select，随便选择一个选项
2，此时弹出comfirm框，随便点击确认或者取消
3，el-select不关闭，持续focus

### What is Expected?

el-select关闭，不要focus

### What is actually happening?

el-select不关闭，持续focus

### Additional comments

_临时补救方案：通过ref获取到el-select组件，设置visible = false，可手动实现关闭_

![select](https://user-images.githubusercontent.com/52116404/181416825-8bf1b446-374e-4a7e-bc63-c58cad2eead2.gif)

**Comment by tolking** [comment]
This is consistent with the logic of component interaction.

When the ElMessageBox is opened, the focus move to the inside of the ElMessageBox. When it is closed, the focus return to ElSelect. At this time, it is completely reasonable for ElSelect to open the dropdown selection because it regains the focus.

ElSelect and ElMessageBox are two components, the focus cannot be ignored.
