### ISSUE TITLE
[Component] [dialog, table] dialog-content.vue 里面@click.stop 这个会在某个情况下导致自己在body加的点击事件无法响应

### ISSUE THREAD

**Issue by yundou147** [element-plus/element-plus#9081]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVGFibGVWaXNpYmxlID0gdHJ1ZVwiXG4gICAgPm9wZW4gYSBUYWJsZSBuZXN0ZWQgRGlhbG9nPC9lbC1idXR0b25cbiAgPlxuXG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cImRpYWxvZ1RhYmxlVmlzaWJsZVwiIHRpdGxlPVwiU2hpcHBpbmcgYWRkcmVzc1wiPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cImdyaWREYXRhXCI+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTUwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIyMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZWwtZGlhbG9nPlxuXG4gIDwhLS0gRm9ybSAtLT5cbiAgPGVsLWJ1dHRvbiB0ZXh0IEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gdHJ1ZVwiXG4gICAgPm9wZW4gYSBGb3JtIG5lc3RlZCBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZGlhbG9nRm9ybVZpc2libGVcIiB0aXRsZT1cIlNoaXBwaW5nIGFkZHJlc3NcIj5cbiAgICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUHJvbW90aW9uIG5hbWVcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJab25lc1wiIDpsYWJlbC13aWR0aD1cImZvcm1MYWJlbFdpZHRoXCI+XG4gICAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJQbGVhc2Ugc2VsZWN0IGEgem9uZVwiPlxuICAgICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIE5vLjFcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBOby4yXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8L2VsLWZvcm0+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dGb3JtVmlzaWJsZSA9IGZhbHNlXCI+Q2FuY2VsPC9lbC1idXR0b24+XG4gICAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dGb3JtVmlzaWJsZSA9IGZhbHNlXCJcbiAgICAgICAgICA+Q29uZmlybTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkaWFsb2dUYWJsZVZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBkaWFsb2dGb3JtVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGZvcm1MYWJlbFdpZHRoID0gJzE0MHB4J1xuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICBuYW1lOiAnJyxcbiAgcmVnaW9uOiAnJyxcbiAgZGF0ZTE6ICcnLFxuICBkYXRlMjogJycsXG4gIGRlbGl2ZXJ5OiBmYWxzZSxcbiAgdHlwZTogW10sXG4gIHJlc291cmNlOiAnJyxcbiAgZGVzYzogJycsXG59KVxuXG5jb25zdCBncmlkRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG5dXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtYnV0dG9uLS10ZXh0IHtcbiAgbWFyZ2luLXJpZ2h0OiAxNXB4O1xufVxuLmVsLXNlbGVjdCB7XG4gIHdpZHRoOiAzMDBweDtcbn1cbi5lbC1pbnB1dCB7XG4gIHdpZHRoOiAzMDBweDtcbn1cbi5kaWFsb2ctZm9vdGVyIGJ1dHRvbjpmaXJzdC1jaGlsZCB7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

dialog-content.vue 里面@click.stop 这个会在某个情况下导致自己在body加的点击事件无法响应
加这个阻止事件冒泡的意义在那里呢
能删除吗?

### What is Expected?

不要阻止事件冒泡

### What is actually happening?

阻止了事件冒泡

### Additional comments

_(empty)_

**Comment by cuihu** [comment]
你自己加的应该用捕获，对业务或者框架而言，click.stop是合理的，比如自身有click-outside之类的

**Comment by yundou147** [comment]
> 你自己加的应该用捕获，对业务或者框架而言，click.stop是合理的，比如自身有click-outside之类的

我的应用里面大量用到这个,
document.body.addEventListener("click", handleBodyClick);
但是组件只要用dialog 弹出来 这个就无法响应.也没有办法取消@click.stop
