### ISSUE TITLE
[Component] el-color-picker 问题影响

### ISSUE THREAD

**Issue by GamesSoul** [element-plus/element-plus#9086]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `e.g. Chrome 96.0.4664.45 / macOS 12.0.1`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`
- `el-input`
- `el-input-number`
- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/color-picker.html)

### Steps to reproduce

使用ColorPicker后 再切换别的输入框，日期选择框全部无法使用

### What is Expected?

使用ColorPicker后 其他的输入框应该能使用

### What is actually happening?

使用ColorPicker后 其他的输入框不能使用

### Additional comments

_(empty)_

**Comment by GamesSoul** [comment]
没有贴代码是因为 网站切到ColorPicker再切别的就可以完全复现

**Comment by btea** [comment]
fixed #9061
