### ISSUE TITLE
[Component] [form-item, form] Unexpected 'xx is required' validation error message appears on a form

### ISSUE THREAD

**Issue by jasonren0403** [element-plus/element-plus#9090]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71`
- Build Tool: `Webpack`

### Related Component

- `el-form-item`
- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5sZXQgZm9ybSA9IHJlYWN0aXZlKHtcblx0dmFsdWVBOiAnJyxcbiAgdmFsdWVCOiAxLFxuICB0ZXh0OiAnJyxcbiAgbm9yZXF1aXJldHh0OiAnJ1xufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxlbC1yb3c+XG5cdFx0PGVsLWNvbCA6b2Zmc2V0PVwiM1wiIDpzcGFuPVwiMThcIj5cblx0XHRcdDxoMj5UZXN0IEZvcm08L2gyPlxuICAgICAgPHA+5Zyo6KGo5Y2V5Lit5YGa5Lu75L2V5pON5L2c77yM5Y+v5Lul5Y+R546w5oql6ZSZ5L+h5oGvPGNvZGU+cHJvcHh4IGlzIHJlcXVpcmVkPC9jb2RlPjwvcD5cbiAgICAgIDxwPlxuICAgICAgICBWdWUgdmVyc2lvbjoge3t2dWVWZXJzaW9ufX0sIEVsZW1lbnQgUGx1cyBWZXJzaW9uOiB7e0VwVmVyc2lvbn19XG4gICAgICA8L3A+XG5cdFx0XHQ8ZWwtZGl2aWRlci8+XG5cdFx0XHQ8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCIgbGFiZWwtcG9zaXRpb249XCJyaWdodFwiPlxuXHRcdFx0XHQ8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiSXRlbSBBXCIgcmVxdWlyZWQgcHJvcD1cIml0ZW0gQVwiPlxuXHRcdFx0XHRcdDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwiZm9ybS52YWx1ZUFcIj5cblx0XHRcdFx0XHRcdDxlbC1yYWRpbyBsYWJlbD1cInlvdVwiPkE8L2VsLXJhZGlvPlxuXHRcdFx0XHRcdFx0PGVsLXJhZGlvIGxhYmVsPVwidGhlaXJcIj5CPC9lbC1yYWRpbz5cblx0XHRcdFx0XHRcdDxlbC1yYWRpbyBsYWJlbD1cImJvdGhcIj5DPC9lbC1yYWRpbz5cblx0XHRcdFx0XHRcdDxlbC1yYWRpbyBsYWJlbD1cIm5vbmVcIj5EPC9lbC1yYWRpbz5cblx0XHRcdFx0XHQ8L2VsLXJhZGlvLWdyb3VwPlxuXHRcdFx0XHQ8L2VsLWZvcm0taXRlbT5cblx0XHRcdFx0PGVsLWZvcm0taXRlbSBsYWJlbD1cIkl0ZW0gQlwiIHJlcXVpcmVkIHByb3A9XCJpdGVtIEJcIj5cblx0XHRcdFx0XHQ8ZWwtaW5wdXQtbnVtYmVyIDptaW49XCIxXCIgOm1heD1cIjdcIiB2LW1vZGVsPVwiZm9ybS52YWx1ZUJcIj48L2VsLWlucHV0LW51bWJlcj5cblx0XHRcdFx0PC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJJdGVtIENcIiByZXF1aXJlZCBwcm9wPVwiaXRlbSBDXCI+XG4gICAgICAgIFx0PGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLnRleHRcIj48L2VsLWlucHV0PlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkl0ZW0gRFwiIHByb3A9XCJpdGVtIERcIj5cbiAgICAgICAgXHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubm9yZXF1aXJldGV4dFwiPjwvZWwtaW5wdXQ+XG4gICAgICAgIDwvZWwtZm9ybS1pdGVtPlxuXHRcdFx0PC9lbC1mb3JtPlxuXHRcdDwvZWwtY29sPlxuXHQ8L2VsLXJvdz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Click or input anything on each form item, 'xx(item's prop name) is required' may appear even the form has already got its value. Note that `required` prop is on the each `el-form-item`, and the form itself has no `rules` prop. 

### What is Expected?

Do not appear any validate error.

### What is actually happening?

Validation error appears.

### Additional comments

Sometimes 'Invalid event arguments: event validation failed for event "validate"' will appear on browser console.

![image](https://user-images.githubusercontent.com/40999116/181476239-18244b52-ad83-4966-9916-63c8a5b2f82a.png)

**Comment by jasonren0403** [comment]
这个表单是包裹在`form`元素以下的，同时每个`el-form-item`如果使用了`required`属性就会出现这个问题

**Comment by emojiiii** [comment]
Whether the field is `required` or not, will be determined by validation rules if omitted.
