### ISSUE TITLE
[Component] [backtop, scrollbar] `el-backtop`与`el-scrollbar`一起使用，不生效

### ISSUE THREAD

**Issue by zhixiaotong** [element-plus/element-plus#9091]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `chrome96`
- Build Tool: `Vite`

### Related Component

- `el-backtop`
- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDIwMHB4XCI+XG4gICAgPGVsLXNjcm9sbGJhciA6YWxhd3lzPVwidHJ1ZVwiPlxuICBcdDxkaXYgY2xhc3M9XCJzY3JvbGxiYXItY29udGFpbmVyXCIgc3R5bGU9XCJoZWlnaHQ6IDE2MDBweDtwYWRkaW5nOiAyMHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiAjMTg5MGZmO3Bvc2l0aW9uOiByZWxhdGl2ZTtvdmVyZmxvdzogYXV0bztcIiAvPlxuICAgICAgPGVsLWJhY2t0b3AgOnJpZ2h0PVwiMTAwXCIgOmJvdHRvbT1cIjEwMFwiIHRhcmdldD1cIi5zY3JvbGxiYXItY29udGFpbmVyXCIgLz5cbiAgPC9lbC1zY3JvbGxiYXI+XG4gIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

如链接所示，不想要html body默认的滚动条，想将页面的元素通过scrollbar包裹起来，将el-backtop的target设置成对应的元素选择器

### What is Expected?

滚动条滚动后，会出现回到顶部

### What is actually happening?

没有出现

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
配置下targer属性

**Comment by zhixiaotong** [comment]
@chenxch 感谢回复。我之前试过在`el-scrollbar`上加`class`，将其设置为`el-backtop`的`target`属性，还找了下面的其他**DOM**元素样式，还是不生效，所以写了这个issue。我刚才又试了下，在`el-scrollbar`上加`class = "scrollbar"`，结果`el-backtop`的`target`设置成`.scrollbar > div`，结果生效了。虽然走了不少弯路，总之弄出来了，再次感谢！

```
<template>
  <div>
    <div style="height: 200px">
      <el-scrollbar class="scrollbar" :alawys="true">
  	<div class="scrollbar-container" style="height: 1600px;padding: 20px; background-color: #1890ff;position: relative;overflow: auto;" />
        <el-backtop :right="100" :bottom="100" target=".scrollbar > div" />
      </el-scrollbar>
    </div>
  </div>
</template>
```

**Comment by zhixiaotong** [comment]
问题已经解决，这个issue我就关闭了。
