### ISSUE TITLE
[Component] [date-picker] 日期选择器，第一次选择，选择灰色（非本月展示的日期）的日期，报错、并且所选日期不是点击的。

### ISSUE THREAD

**Issue by kmliugang** [element-plus/element-plus#9098]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.9`
- Browser / OS: ` chorme 103.0.5060.134`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Link]()

### Steps to reproduce

 ```vue
<template>
<el-date-picker v-model="value" value-format="YYYY-MM-DD HH:mm:ss"  type="datetime"/>
</template>
 ```

### What is Expected?

点击灰色日期，不会报错，并且选中

### What is actually happening?

点击灰色日期，会报错，并且不能选中点击的日期

### Additional comments

_(empty)_

**Comment by holazz** [comment]
升级 Element Plus 到最新版

**Comment by kmliugang** [comment]
> 升级 Element Plus 到最新版

好了，谢谢啦

**Comment by JeeBoom** [comment]
![image](https://user-images.githubusercontent.com/24579053/182782224-b0ff1507-913e-441f-adc1-763d87c8be1c.png)
我发现第一次选择灰色日期还是会报错的  , 后续再次选择灰色日期则不报错 , 
"element-plus": "^2.2.12",
