### ISSUE TITLE
[Component] [popconfirm] Popconfirm 组件width属性无效

### ISSUE THREAD

**Issue by Nisekoi5** [element-plus/element-plus#9099]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-popconfirm`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wY29uZmlybSB0aXRsZT1cIui/meaYr+S4gOautei+g+mVv+eahOaWh+Wtl++8jOi/meaYr+S4gOautei+g+mVv+eahOaWh+Wtl++8jOi/meaYr+S4gOautei+g+mVv+eahOaWh+Wtl1wiIDp3aWR0aD1cIjIzMFwiPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5EZWxldGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcGNvbmZpcm0+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-popconfirm title="这是一段较长的文字，这是一段较长的文字，这是一段较长的文字" :width="230">
    <template #reference>
      <el-button>Delete</el-button>
    </template>
  </el-popconfirm>
</template>

```

### What is Expected?

气泡确认框的宽度应为230px

### What is actually happening?

弹出框宽度无限制，不会换行

### Additional comments

从element 切换到 element-plus后出现的，在旧版本width属性是效果的，不确定是bug还是特性

**Comment by btea** [comment]
`popconfirm` 目前应该是不支持`width`属性的，element 似乎也不支持。

**Comment by Nisekoi5** [comment]
> `popconfirm` 目前应该是不支持`width`属性的，element 似乎也不支持。

后续会考虑支持吗，element是有这个属性的
```
<el-popconfirm
  title="这是一段内容确定删除吗？这是一段内容确定删除吗？这是一段内容确定删除吗？" width='200'>
  <el-button slot="reference">删除</el-button>
</el-popconfirm>
```
![2022-07-29 10-22-42](https://user-images.githubusercontent.com/49276902/181669649-f13e97d7-6933-4309-9b65-b1dbb448106e.jpg)

**Comment by btea** [comment]
我看element文档和代码`popconfirm`好像没有`width`属性。 你这个效果能给我提供一个链接吗？

**Comment by Nisekoi5** [comment]
> 我看element文档和代码`popconfirm`好像没有`width`属性。 你这个效果能给我提供一个链接吗？

我也是看到文档的这个介绍，然后才去Popover组件的文档找到的属性。填上去发现确实没问题
`Popconfirm 的属性与 Popover 很类似，因此对于重复属性，请参考 Popover 的文档，在此文档中不做详尽解释。`

直接复制以下内容保存为html打开就可以看见效果了
```
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"></script>
<script src="https://unpkg.com/element-ui@2.15.9/lib/index.js"></script>
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
<body>
<div id="app">
<template>
<el-popconfirm
  title="这是一段内容确定删除吗？这是一段内容确定删除吗？这是一段内容确定删除吗？" :width='pop_width'>
  <el-button slot="reference">删除</el-button>
</el-popconfirm>


</template>
</div>
</body>
<script>
var app = new Vue({
  el: '#app',
  data:{
  pop_width:300}
})
</script>
```

**Comment by btea** [comment]
感谢你提供的示例以及代码链接。有兴趣来一个pr吗？

**Comment by Nisekoi5** [comment]
> 感谢你提供的示例以及代码链接。有兴趣来一个pr吗？

哈哈还是算了，我是业余学习的初学者，对vue3和ts的用法都还不是太熟悉。3.0的文档也还没看完，就不瞎提pr了，怕质量不过关。能帮到该项目就很好了

**Comment by btea** [comment]
好的，感谢反馈❤。我们会尽快修复。
