### ISSUE TITLE
[Component] [dialog] Dialog内容太多，并添加了draggable属性的bug

### ISSUE THREAD

**Issue by mrjimin** [element-plus/element-plus#9100]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVGFibGVWaXNpYmxlID0gdHJ1ZVwiXG4gICAgPm9wZW4gYSBUYWJsZSBuZXN0ZWQgRGlhbG9nPC9lbC1idXR0b25cbiAgPlxuXG4gIDxlbC1kaWFsb2cgdi1tb2RlbD1cImRpYWxvZ1RhYmxlVmlzaWJsZVwiIGRyYWdnYWJsZSB0aXRsZT1cIlNoaXBwaW5nIGFkZHJlc3NcIj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJncmlkRGF0YVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE1MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3BlcnR5PVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMjAwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkaWFsb2dUYWJsZVZpc2libGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGdyaWREYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAgICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5lbC1idXR0b24tLXRleHQge1xuICBtYXJnaW4tcmlnaHQ6IDE1cHg7XG59XG4uZWwtc2VsZWN0IHtcbiAgd2lkdGg6IDMwMHB4O1xufVxuLmVsLWlucHV0IHtcbiAgd2lkdGg6IDMwMHB4O1xufVxuLmRpYWxvZy1mb290ZXIgYnV0dG9uOmZpcnN0LWNoaWxkIHtcbiAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.点击按钮打开弹窗
2.拖拽弹窗

### What is Expected?

弹窗内容比较多的时候，点击拖拽，头部、关闭按钮显示在可视范围内

### What is actually happening?

弹窗内容比较多的时候，点击拖拽，弹窗超出页面范围，头部、关闭按钮看不到

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
使用draggable属性时，请保持dialog尺寸小于容器尺寸。
