### ISSUE TITLE
[Component] [table] el-table 组件el-table__empty-block 的高度计算错误

### ISSUE THREAD

**Issue by norangit** [element-plus/element-plus#9102]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome/103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBjb2x1bW5zID0gW1xuICB7XG4gICAgcHJvcDogJ3VzZXJuYW1lJyxcbiAgICBsYWJlbDogJ+eUqOaIt+WQjSdcbiAgfSxcbiAge1xuICAgIHByb3A6ICduYW1lJyxcbiAgICBsYWJlbDogJ+aYteensCdcbiAgfSxcbiAge1xuICAgIHByb3A6ICdncm91cCcsXG4gICAgbGFiZWw6ICfnlKjmiLfnu4QnXG4gIH1cbl1cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXSlcblxuc2V0VGltZW91dCgoKSA9PiB7XG4gIGZvcihsZXQgaSA9IDA7IGkgPCAxMDsgaSsrKXtcbiAgICB0YWJsZURhdGEudmFsdWUucHVzaCh7XG4gICAgICB1c2VybmFtZTogJ1VzZXIgJyArIGksXG4gICAgICBuYW1lOiAnTmFtZSAnICsgaSxcbiAgICAgIGdyb3VwOiAnR3JvdXAgJyArIGlcbiAgICB9KVxuICB9XG59LCA1MDAwKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6cm93LWtleT1cIml0PT5pdC5pZFwiIHRhYmxlLWxheW91dD1cImF1dG9cIj5cbiAgICAgICAgICAgICAgICA8dGVtcGxhdGUgdi1mb3I9XCIoYyxpZHgpIGluIGNvbHVtbnNcIiA6a2V5PVwiYy5wcm9wXCI+XG4gICAgICAgICAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gOnByb3A9XCJjLnByb3BcIiA6bGFiZWw9XCJjLmxhYmVsXCIgOnNvcnRhYmxlPVwiYy5zb3J0YWJsZVwiIDp3aWR0aD1cImMud2lkdGhcIiA6bWluLXdpZHRoPVwiYy5taW5XaWR0aFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgXG4gICAgICAgICAgICAgICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSAgc2NvcGVkPlxuICAuZWwtdGFibGV7XG4gICAgYm9yZGVyOiAxcHggc29saWQgI2YwMDtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

表格数据是异步加载的，在加载完成之前，表格高度一直在增高，直到数据回来了，高度才正常了

### What is Expected?

表格高度保持不变

### What is actually happening?

表格高度一直在增高

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed #9063
