### ISSUE TITLE
[Component] [table] 改变表格宽度，横向滚动条长度并没有自适应

### ISSUE THREAD

**Issue by liuxinghenry** [element-plus/element-plus#9105]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome/94.0.4606.71`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdGFibGVDb2x1bW4gPSBbXG4gIHtcbiAgICBwcm9wOiAnYmF0Y2hJZCcsXG4gICAgbGFiZWw6ICfluo/lj7cnLFxuICAgIHdpZHRoOiA2MCxcbiAgfSxcbiAge1xuICAgIHByb3A6ICd0eXBlJyxcbiAgICBsYWJlbDogJ+WuueWZqOexu+WeiycsXG4gICAgd2lkdGg6IDgwLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ3dlaWdodCcsXG4gICAgbGFiZWw6ICfoh6rph40nLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ2xvYWRMaW1pdCcsXG4gICAgbGFiZWw6ICfovb3ph43pmZDliLYnLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ3ZvbHVtZScsXG4gICAgbGFiZWw6ICflrrnnp68nLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ2FwcGxpY2FibGVNb2RlbCcsXG4gICAgbGFiZWw6ICfpgILnlKjmnLrlnosnLFxuICAgIHdpZHRoOiAyNTAsXG4gIH0sXG4gIHtcbiAgICBwcm9wOiAnVUxEdHlwZScsXG4gICAgbGFiZWw6ICdVTETnsbvliKsnLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ2xlbmd0aCcsXG4gICAgbGFiZWw6ICfplb8nLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ3dpZHRoJyxcbiAgICBsYWJlbDogJ+WuvScsXG4gIH0sXG4gIHtcbiAgICBwcm9wOiAnaGVpZ2h0JyxcbiAgICBsYWJlbDogJ+mrmCcsXG4gIH0sXG4gIHtcbiAgICBwcm9wOiAncGxhdGVUeXBlJyxcbiAgICBsYWJlbDogJ+adv+WeiycsXG4gIH0sXG4gIHtcbiAgICBwcm9wOiAncmVtYXJrJyxcbiAgICBsYWJlbDogJ+Wkh+azqCcsXG4gICAgd2lkdGg6IDIwMCxcbiAgfSxcbiAge1xuICAgIHByb3A6ICd1bml0JyxcbiAgICBsYWJlbDogJ+WNleS9jeWAvCcsXG4gIH0sXG4gIHtcbiAgICBwcm9wOiAnb3BlcmF0ZXInLFxuICAgIGxhYmVsOiAn5pON5L2c5Lq6JyxcbiAgICB3aWR0aDogMTAwLFxuICB9LFxuICB7XG4gICAgcHJvcDogJ29wZXJhdGVEYXRlJyxcbiAgICBsYWJlbDogJ+aTjeS9nOaXpeacnycsXG4gICAgd2lkdGg6IDE4MCxcbiAgfSxcbl1cblxuY29uc3QgaXNDb2xsYXBzZSA9IHJlZihmYWxzZSlcblxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoKSA9PiB7XG4gIGlzQ29sbGFwc2UudmFsdWUgPSAhaXNDb2xsYXBzZS52YWx1ZVxufVxuY29uc3QgcmVzdWx0RGF0YSA9IFtcbiAge1xuICAgIGJhdGNoSWQ6IDEsXG4gICAgdHlwZTogJ0FBQScsXG4gICAgd2VpZ2h0OiAnMS4wMCcsXG4gICAgbG9hZExpbWl0OiAnOTk5OS4wMCcsXG4gICAgdm9sdW1lOiAnOTk5OS4wMCcsXG4gICAgYXBwbGljYWJsZU1vZGVsOiAnNzc3LzMyUS83N0YvMzIwLzMyTC83M00vMzJHLzMyWi8zMzMvNzM4LzMyTS83M04nLFxuICAgIFVMRHR5cGU6ICfnrrEnLFxuICAgIGxlbmd0aDogOTk5OSxcbiAgICB3aWR0aDogOTk5OSxcbiAgICBoZWlnaHQ6IDk5OTksXG4gICAgcGxhdGVUeXBlOiAnOTk5JyxcbiAgICByZW1hcms6ICcnLFxuICAgIHVuaXQ6ICcxJyxcbiAgfSxcbiAge1xuICAgIGJhdGNoSWQ6IDIsXG4gICAgdHlwZTogJ0FBQycsXG4gICAgd2VpZ2h0OiAnMS4wMCcsXG4gICAgbG9hZExpbWl0OiAnOTk5OS4wMCcsXG4gICAgdm9sdW1lOiAnOTk5OS4wMCcsXG4gICAgYXBwbGljYWJsZU1vZGVsOiAnNzc3LzMyUS83N0YvMzIwLzMyTC83M00vMzJHLzMyWi8zMzMvNzM4LzMyTS83M04nLFxuICAgIFVMRHR5cGU6ICfnrrEnLFxuICAgIGxlbmd0aDogOTk5OSxcbiAgICB3aWR0aDogOTk5OSxcbiAgICBoZWlnaHQ6IDk5OTksXG4gICAgcGxhdGVUeXBlOiAnOTk5JyxcbiAgICByZW1hcms6ICcnLFxuICAgIHVuaXQ6ICcxJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVDbGlja1wiPuaMiemSrjwvZWwtYnV0dG9uPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbnRlbnRcIiA6c3R5bGU9XCIhaXNDb2xsYXBzZSA/ICd3aWR0aDoxMDAwcHgnOid3aWR0aDoxNDAwcHgnXCI+XG4gICAgICA8ZWwtdGFibGVcbiAgICAgICAgOmRhdGE9XCJyZXN1bHREYXRhXCJcbiAgICAgICAgaGVpZ2h0PVwiNTB2aFwiXG4gICAgICAgIGJvcmRlclxuICAgICAgICBzdHlsZT1cIndpZHRoOjEwMCVcIlxuICAgICAgICBoZWFkZXItY2VsbC1jbGFzcy1uYW1lPVwiY2VudGVyXCJcbiAgICAgICAgY2VsbC1jbGFzcy1uYW1lPVwiY2VudGVyXCJcbiAgICAgID5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI0MFwiIGZpeGVkPjwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICAgICAgdi1mb3I9XCJpdGVtIGluIHRhYmxlQ29sdW1uXCJcbiAgICAgICAgICA6a2V5PVwiaXRlbS5wcm9wXCJcbiAgICAgICAgICA6cHJvcD1cIml0ZW0ucHJvcFwiXG4gICAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgICAgOndpZHRoPVwiaXRlbS53aWR0aCA/IGl0ZW0ud2lkdGggOiAnJ1wiXG4gICAgICAgIC8+XG4gICAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLmk43kvZxcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc2l6ZT1cInNtYWxsXCIgcGxhaW4+5L+uIOaUuTwvZWwtYnV0dG9uPlxuICAgICAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgc2l6ZT1cInNtYWxsXCIgcGxhaW4+5YigIOmZpDwvZWwtYnV0dG9uPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgPC9lbC10YWJsZT5cbiAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.点击按钮改变表格宽度
2.拖动表格横向滚动条

### What is Expected?

横向滚动条长度自适应

### What is actually happening?

横向滚动条长度没有自适应，并只能滚动到大约表格宽度一半的位置

### Additional comments

_(empty)_

**Comment by baiwusanyu-c** [comment]
![动画](https://user-images.githubusercontent.com/32354856/183588543-fd401815-6c87-40df-b33c-1b7ffb59a4b5.gif)
没有复现，或许需要更多信息

**Comment by liuxinghenry** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [table] 改变表格宽度，横向滚动条长度并没有自适应 (Issue #9105)





 

 没有复现，或许需要更多信息

**Comment by tolking** [comment]
fixed in #9149
