### ISSUE TITLE
[Component] [input, input-number] ColorPicker 颜色选择器存在时输入框无法输入值

### ISSUE THREAD

**Issue by pengyanxue** [element-plus/element-plus#9110]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome 版本 102.0.5005.115（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29sb3ItcGlja2VyIHYtbW9kZWw9XCJjb2xvcjFcIiAvPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm5hbWVcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY29sb3IxID0gcmVmKCcjNDA5RUZGJylcbmNvbnN0IG5hbWUgPSByZWYoJycpXG5cbjwvc2NyaXB0PlxuXG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<template>
  <el-color-picker v-model="color1" />
  <el-input v-model="name" />
</template>

<script setup>
import { ref } from 'vue'

const color1 = ref('#409EFF')
const name = ref('')

</script>

### What is Expected?

期望input可正常输入

### What is actually happening?

实际结果是input无法输入内容聚焦

### Additional comments

影响的组件只测试了input 和 input-number

**Comment by TaoziDeGitHub** [comment]
我觉遇到了

**Comment by pengyanxue** [comment]
您发给我的信件已经收到。                                         ------彭艳雪

**Comment by btea** [comment]
fixed #9061

**Comment by pengyanxue** [comment]
麻烦看下这个具体描述，在现在的2.2.11版本仍存在，在9061里面 只是修改了事件绑定到element上  但是我修改了后 还是未生效

**Comment by btea** [comment]
已修复，请更新到2.2.12试试

**Comment by pengyanxue** [comment]
在2.2.12版本中已修复，感谢
