### ISSUE TITLE
[Component] [radio] el-radio click once but emit double click event

### ISSUE THREAD

**Issue by cuihu** [element-plus/element-plus#9111]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 103.0.5060.134/ macos 10.14.6`
- Build Tool: `Vite`

### Related Component

- `el-radio`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiID5cbiAgICAgICAgICA8ZGl2IEBjbGljaz1cInNob3dUXCI+XG4gICAgICAgICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJpc19yZWFsYXRpdmVcIiAvPlxuICAgICAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIHt7Y291bnR9fVxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IGgsIHJlZiwgc2hhbGxvd1JlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGRhdGUgPSByZWYoJycpXG5jb25zdCBpc19yZWFsYXRpdmUgPSByZWYodHJ1ZSlcbmNvbnN0IGQgPSByZWFjdGl2ZShbe2s6IDF9XSlcbmNvbnN0IGN1c3RvbVByZWZpeCA9IHNoYWxsb3dSZWYoe1xuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGgoJ3AnLCAncHJlJylcbiAgfSxcbn0pXG5jb25zdCBjb3VudCA9IHJlZigwKVxuY29uc3Qgc2hvd1QgPSBmdW5jdGlvbihlKSB7XG4gIGlzX3JlYWxhdGl2ZS52YWx1ZSA9ICFpc19yZWFsYXRpdmUudmFsdWVcbiAgY29uc29sZS5sb2coZSlcbiAgY291bnQudmFsdWUrPTFcbn1cblxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

with deme click radio

### What is Expected?

click emit once

### What is actually happening?

click emit double

### Additional comments

I guess it's maybe chrome/navigator/system bug, actually, because other PointerEvent is isTrusted but PointerId is -1 and PointerType is "", means there some ghost click happen with the input.
In my case, some more meaning things it's that click other input/select/date-picker, and where dropdown tooltip show may cause some radio/switch happen once click....
I already report this bug issue to chrome bug list,
https://bugs.chromium.org/p/chromium/issues/detail?id=1348130&q=cuihu&can=2

**Comment by gjfei** [comment]
因为有label标签  点击label的时候，事件冒泡一次，同时会触发关联的input的click事件，导致事件再次冒泡

**Comment by cuihu** [comment]
> 因为有label标签 点击label的时候，事件冒泡一次，同时会触发关联的input的click事件，导致事件再次冒泡，参考这个 https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiID5cbiAgICAgICAgICA8ZGl2IEBjbGljay5wcmV2ZW50PVwic2hvd1RcIj5cbiAgICAgICAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cImlzX3JlYWxhdGl2ZVwiIC8+XG4gICAgICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAge3tjb3VudH19XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgaCwgcmVmLCBzaGFsbG93UmVmLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGF0ZSA9IHJlZignJylcbmNvbnN0IGlzX3JlYWxhdGl2ZSA9IHJlZih0cnVlKVxuY29uc3QgZCA9IHJlYWN0aXZlKFt7azogMX1dKVxuY29uc3QgY3VzdG9tUHJlZml4ID0gc2hhbGxvd1JlZih7XG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaCgncCcsICdwcmUnKVxuICB9LFxufSlcbmNvbnN0IGNvdW50ID0gcmVmKDApXG5jb25zdCBzaG93VCA9IGZ1bmN0aW9uKGUpIHtcbiAgaXNfcmVhbGF0aXZlLnZhbHVlID0gIWlzX3JlYWxhdGl2ZS52YWx1ZVxuICBjb25zb2xlLmxvZyhlKVxuICBjb3VudC52YWx1ZSs9MVxufVxuXG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

It's more worth strange that once click generate double pointerType with same isTrusted: True but PointerType is different, so maybe it's navigator feature/bug

**Comment by btea** [comment]
fixed by #13936
