### ISSUE TITLE
[Component] [input] Disabled input doesn't show binded value

### ISSUE THREAD

**Issue by wtcodeai** [element-plus/element-plus#9117]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Safari 15.2 (17612.3.6.1.6)/Mac OS 12.1`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBkaXNhYmxlZCAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCdhYWFhJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Set up el-input component with "disabled" attribute and bind some non-null value

### What is Expected?

Binded value should be displayed in disabled input

### What is actually happening?

Binded value not displayed (only placeholder when value is empty)

### Additional comments

_(empty)_

**Comment by dawn406** [comment]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/53803890/181766395-b9e66975-dfbf-4eda-afb4-93611616cd44.png">
You can see the bound value

**Comment by wtcodeai** [comment]
I can't (see my Browser/OS env)
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/48126099/181811621-d6275102-9803-4330-83a9-4e1dbdc3b25d.png">

**Comment by dawn406** [comment]
> 我不能（查看我的浏览器/操作系统env）
> <img alt="图像" width="1238" src="https://user-images.githubusercontent.com/48126099/181811621-d6275102-9803-4330-83a9-4e1dbdc3b25d.png">

Yes, my Safari can't display either
