### ISSUE TITLE
[Component] [pagination] el-pagination使用@update:current-page和@update:page-size，监听事件不生效

### ISSUE THREAD

**Issue by fanyawei** [element-plus/element-plus#9118]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Google Chrome 103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICBwYWdlOjEsXG4gIHBhZ2VTaXplOjEwLFxuICB0b3RhbDoxMDAwXG59KVxuXG5jb25zdCBoYW5kbGVTZWFyY2ggPSBhc3luYygpPT57XG4gIGFsZXJ0KFwi5omn6KGM5p+l6K+i5pON5L2cXCIpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcGFnaW5hdGlvblxuICAgICAgICA6cGFnZS1zaXplcz1cIlsxMCwgMjAsIDUwLCAxMDAsIDIwMCwgNTAwXVwiXG4gICAgICAgIDp0b3RhbD1cInN0YXRlLnRvdGFsXCJcbiAgICAgICAgdi1tb2RlbDpjdXJyZW50LXBhZ2U9XCJzdGF0ZS5wYWdlXCJcbiAgICAgICAgdi1tb2RlbDpwYWdlLXNpemU9XCJzdGF0ZS5wYWdlU2l6ZVwiXG4gICAgICAgIGxheW91dD1cInRvdGFsLCBzaXplcywgcHJldiwgcGFnZXIsIG5leHQsIGp1bXBlclwiXG4gICAgICAgIEB1cGRhdGU6Y3VycmVudC1wYWdlPVwiaGFuZGxlU2VhcmNoXCJcbiAgICAgICAgQHVwZGF0ZTpwYWdlLXNpemU9XCJoYW5kbGVTZWFyY2hcIlxuICAgIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

传入了 page-size，且布局包含 page-size 选择器,使用@update:current-page和@update:page-size来监听相关的变化不生效，而使用即将废弃的@size-change和@current-change生效

### What is Expected?

可以执行监听函数

### What is actually happening?

没有执行监听函数

### Additional comments

不确定是不是我的理解和用法有问题，已提供复现环境

**Comment by dawn406** [comment]
You can view the latest documents

**Comment by holazz** [comment]
监听 `update:current-page` 你要把 `v-model:current-page` 改成 `:current-page`，并且需要在监听函数中手动更新值。如果使用双向绑定(`v-model:current-page`) 的话，监听数据变化还是要使用 `@current-change` 或者 `watch`

**Comment by fanyawei** [comment]
> 监听 `update:current-page` 你要把 `v-model:current-page` 改成 `:current-page`，并且需要在监听函数中手动更新值。如果使用双向绑定(`v-model:current-page`) 的话，监听数据变化还是要使用 `@current-change` 或者 `watch`

好的，谢谢
