### ISSUE TITLE
[Component] Cannot read properties of undefined (reading 'validate')

### ISSUE THREAD

**Issue by liyuan1125** [element-plus/element-plus#9136]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-tree`
- `el-checkbox-button`
- `el-checkbox`
- `el-checkbox-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0cmVlRGF0YSA9IHJlZihbe2lkOjEsbGFiZWw6J3VzZXInfV0pO1xuICBjb25zdCBzZXR0aW5nID0gcmVmKFtdKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICA8ZWwtdHJlZVxuICAgICAgYXV0by1leHBhbmQtcGFyZW50XG4gICAgICBjaGVjay1vbi1jbGljay1ub2RlXG4gICAgICA6ZGF0YT1cInRyZWVEYXRhXCJcbiAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgICAgaGlnaGxpZ2h0LWN1cnJlbnRcbiAgICAgIG5vZGUta2V5PVwiaWRcIlxuICAgICAgc2hvdy1jaGVja2JveFxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInsgbm9kZSB9XCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjdXN0b20tdHJlZS1ub2RlXCI+XG4gICAgICAgICAgPHNwYW4+e3sgbm9kZS5sYWJlbCB9fTwvc3Bhbj5cblxuICAgICAgICAgIDxkaXYgPlxuICAgICAgICAgICAgPGVsLXBvcG92ZXIgdGVsZXBvcnRlZCB0aXRsZT1cInNldHRpbmdcIiB0cmlnZ2VyPVwiaG92ZXJcIiA6d2lkdGg9XCIyMDBcIj5cbiAgICAgIFx0XHRcdFx0PHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgICBcdFx0PGVsLWxpbmsgQGNsaWNrLnN0b3AgPnNldHRpbmc8L2VsLWxpbms+XG4gICAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgICAgIFxuICAgICAgICAgICAgICAgPGVsLWNoZWNrYm94LWdyb3VwIHYtbW9kZWw9XCJzZXR0aW5nXCI+XG4gICAgICAgICAgXHRcdFx0PGVsLWNoZWNrYm94LWJ1dHRvbiA+MTwvZWwtY2hlY2tib3gtYnV0dG9uPlxuICAgICAgICAgIFx0XHRcdDxlbC1jaGVja2JveC1idXR0b24gPjE8L2VsLWNoZWNrYm94LWJ1dHRvbj5cbiAgICAgICAgXHRcdFx0PC9lbC1jaGVja2JveC1ncm91cD5cbiAgICAgICAgICAgICAgXG4gICAgICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10cmVlPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuY3VzdG9tLXRyZWUtbm9kZSB7XG4gICAgZmxleDogMTtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICAgIGZvbnQtc2l6ZTogMTRweDtcbiAgICBwYWRkaW5nLXJpZ2h0OiA4cHg7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce
```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const treeData = ref([{id:1,label:'user'}]);
  const setting = ref([]);
</script>

<template>
   <el-tree
      auto-expand-parent
      check-on-click-node
      :data="treeData"
      default-expand-all
      highlight-current
      node-key="id"
      show-checkbox
    >
      <template #default="{ node }">
        <div class="custom-tree-node">
          <span>{{ node.label }}</span>

          <div >
            <el-popover teleported title="setting" trigger="hover" :width="200">
      				<template #reference>
            		<el-link @click.stop >setting</el-link>
              </template>
              
               <el-checkbox-group v-model="setting">
          			<el-checkbox-button >1</el-checkbox-button>
          			<el-checkbox-button >1</el-checkbox-button>
        			</el-checkbox-group>
              
            </el-popover>
          </div>
        </div>
      </template>
  </el-tree>
</template>

<style>
  .custom-tree-node {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: space-between;
    font-size: 14px;
    padding-right: 8px;
  }
</style>
```
### What is Expected?

1

### What is actually happening?

1

### Additional comments

_(empty)_

**Comment by holazz** [comment]
maybe fix by #8865
