### ISSUE TITLE
[Component] [form, form-item] In the Form component, the red * will change with the value of label-postion, but in the process of using the actual component, it is found that this function is not available. Is this an implementation defect?

### ISSUE THREAD

**Issue by ubbcou** [element-plus/element-plus#9140]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.11`
- Browser / OS: `Edg/103.0.1264.77`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIDptb2RlbD1cIm51bWJlclZhbGlkYXRlRm9ybVwiXG4gICAgbGFiZWwtd2lkdGg9XCIxMjBweFwiXG5cdFx0bGFiZWwtcG9zaXRpb249XCJsZWZ0XCJcbiAgICBjbGFzcz1cImRlbW8tcnVsZUZvcm1cIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJhZ2VcIlxuICAgICAgcHJvcD1cImFnZVwiXG4gICAgICA6cnVsZXM9XCJbXG4gICAgICAgIHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdhZ2UgaXMgcmVxdWlyZWQnIH0sXG4gICAgICAgIHsgdHlwZTogJ251bWJlcicsIG1lc3NhZ2U6ICdhZ2UgbXVzdCBiZSBhIG51bWJlcicgfSxcbiAgICAgIF1cIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsLm51bWJlcj1cIm51bWJlclZhbGlkYXRlRm9ybS5hZ2VcIlxuICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgIGF1dG9jb21wbGV0ZT1cIm9mZlwiXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIDxlbC1mb3JtXG4gICAgcmVmPVwiZm9ybVJlZlwiXG4gICAgOm1vZGVsPVwibnVtYmVyVmFsaWRhdGVGb3JtXCJcbiAgICBsYWJlbC13aWR0aD1cIjEyMHB4XCJcblx0XHRsYWJlbC1wb3NpdGlvbj1cInJpZ2h0XCJcbiAgICBjbGFzcz1cImRlbW8tcnVsZUZvcm1cIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJhZ2VcIlxuICAgICAgcHJvcD1cImFnZVwiXG4gICAgICA6cnVsZXM9XCJbXG4gICAgICAgIHsgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdhZ2UgaXMgcmVxdWlyZWQnIH0sXG4gICAgICAgIHsgdHlwZTogJ251bWJlcicsIG1lc3NhZ2U6ICdhZ2UgbXVzdCBiZSBhIG51bWJlcicgfSxcbiAgICAgIF1cIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dFxuICAgICAgICB2LW1vZGVsLm51bWJlcj1cIm51bWJlclZhbGlkYXRlRm9ybS5hZ2VcIlxuICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgIGF1dG9jb21wbGV0ZT1cIm9mZlwiXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIDxlbC1mb3JtXG4gICAgcmVmPVwiZm9ybVJlZlwiXG4gICAgOm1vZGVsPVwibnVtYmVyVmFsaWRhdGVGb3JtXCJcbiAgICBsYWJlbC13aWR0aD1cIjEyMHB4XCJcblx0XHRsYWJlbC1wb3NpdGlvbj1cInRvcFwiXG4gICAgY2xhc3M9XCJkZW1vLXJ1bGVGb3JtXCJcbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwiYWdlXCJcbiAgICAgIHByb3A9XCJhZ2VcIlxuICAgICAgOnJ1bGVzPVwiW1xuICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAnYWdlIGlzIHJlcXVpcmVkJyB9LFxuICAgICAgICB7IHR5cGU6ICdudW1iZXInLCBtZXNzYWdlOiAnYWdlIG11c3QgYmUgYSBudW1iZXInIH0sXG4gICAgICBdXCJcbiAgICA+XG4gICAgICA8ZWwtaW5wdXRcbiAgICAgICAgdi1tb2RlbC5udW1iZXI9XCJudW1iZXJWYWxpZGF0ZUZvcm0uYWdlXCJcbiAgICAgICAgdHlwZT1cInRleHRcIlxuICAgICAgICBhdXRvY29tcGxldGU9XCJvZmZcIlxuICAgICAgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgZm9ybVJlZiA9IHJlZjxGb3JtSW5zdGFuY2U+KClcblxuY29uc3QgbnVtYmVyVmFsaWRhdGVGb3JtID0gcmVhY3RpdmUoe1xuICBhZ2U6ICcnLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IChmb3JtRWw6IEZvcm1JbnN0YW5jZSB8IHVuZGVmaW5lZCkgPT4ge1xuICBpZiAoIWZvcm1FbCkgcmV0dXJuXG4gIGZvcm1FbC52YWxpZGF0ZSgodmFsaWQpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnKVxuICAgICAgcmV0dXJuIGZhbHNlXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Set the value of label-position to left, right, top respectively

### What is Expected?

Consistent with Figma performance

### What is actually happening?

The position of the red * is always on the left

### Additional comments

_(empty)_

**Comment by btea** [comment]
@ubbcou Hello, You mean when position is set to `right`, the label should be to the right of the input?

**Comment by ubbcou** [comment]
@btea 


[Here](https://www.figma.com/file/8JqA6JEsRzZ4wr9uxYmTbM/Element-Plus-Design-System(Components)-(Community)?node-id=6542%3A142394) I can see that the required symbol(*) can be set to the right of the label, but in the actual component, I don't see the corresponding props.
![image](https://user-images.githubusercontent.com/25863414/186345841-80a1d1fe-ef2c-49a5-ad50-0710f37e24cb.png)

**Comment by btea** [comment]
ok, I think I get what you mean, there really is no relevant configuration at the moment.  Are you interested in creating a PR?

**Comment by ubbcou** [comment]
@btea wow, definitely next time(PR).
