### ISSUE TITLE
[Component] [button, table-column] 组件不热更新

### ISSUE THREAD

**Issue by ShacoZ** [element-plus/element-plus#9144]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome 103.0.5060.134 / MacOS 12.5`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgdGFibGVEYXRlID0gcmVmKFtcblx0e1xuXHRcdGFwcEFjY291bnQ6J2FwcEFjY291bnQtMScsXG5cdFx0YXBwTmFtZTonYXBwTmFtZS0xJyxcblx0XHR1c2VySWQ6J3VzZXJJZC0xJyxcblx0XHR1c2VyTmFtZTondXNlck5hbWUtMScsXG5cdFx0Tm86J2Vzc2NOby0xJ1xuXHR9LFxuXHR7XG5cdFx0YXBwQWNjb3VudDonYXBwQWNjb3VudC0yJyxcblx0XHRhcHBOYW1lOidhcHBOYW1lLTInLFxuXHRcdHVzZXJJZDondXNlcklkLTInLFxuXHRcdHVzZXJOYW1lOid1c2VyTmFtZS0yJyxcblx0XHRObzonZXNzY05vLTInXG5cdH0sXG5cdHtcblx0XHRhcHBBY2NvdW50OidhcHBBY2NvdW50LTMnLFxuXHRcdGFwcE5hbWU6J2FwcE5hbWUtMycsXG5cdFx0dXNlcklkOid1c2VySWQtMycsXG5cdFx0dXNlck5hbWU6J3VzZXJOYW1lLTMnLFxuXHRcdE5vOidlc3NjTm8tMydcblx0fVxuXSlcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0ZVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCLotKblj7dcIiBwcm9wPVwiYXBwQWNjb3VudFwiIC8+XG5cdFx0XHQ8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi55So5oi3XCIgcHJvcD1cImFwcE5hbWVcIiAvPlxuXHRcdFx0PGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIueUqOaIt0lEXCIgcHJvcD1cInVzZXJJZFwiIC8+XG5cdFx0XHQ8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi55So5oi35ZCNXCIgcHJvcD1cInVzZXJOYW1lXCIgLz5cbiAgICBcdDwhLS3kv67mlLlsYWJlbOaWh+Wtl+S4jeS8mueDreabtOaWsC0tPlxuXHRcdFx0PGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5vXCIgcHJvcD1cIk5vXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwi5pON5L2cXCI+XG5cdFx0XHRcdDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgICAgPCEtLeaMiemSruaWh+Wtl+S4jeS8mueDreabtOaWsC0tPlxuXHRcdFx0XHRcdDxlbC1idXR0b24gbGluayB0eXBlPVwiZGFuZ2VyXCI+5Yig6ZmkPC9lbC1idXR0b24+XG5cdFx0XHRcdDwvdGVtcGxhdGU+XG5cdFx0XHQ8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cblx0PGRpdj5cbiAgICA8cD5cbiAgICAgIOi/memHjOeahOaWh+Wtl+WmguaenOiiq+S/ruaUueWwseWPr+S7peato+W4uOeDreabtOaWsFxuICAgIDwvcD5cbiAgPC9kaXY+XG5cdDxoNT5cbiAgICDlvIDlj5Hlt6Xlhbfkvb/nlKjnmoTmmK93ZWJzdG9ybe+8jOWcqHdlYnN0b3Jt5L+u5pS55LqG5oyJ6ZKu55qE5paH5a2X5ZKMdGFibGXooYznmoRsYWJlbOWAvOWcqGNocm9tZeeahOaOp+WItuWPsOaPkOekuuS6hue7hOS7tuiiq+abtOaWsO+8jOS9huaYr+mhtemdouaYvuekuueahOWGheWuueW5tuayoeacieaUueWPmO+8jOmcgOimgeWIt+aWsOa1j+iniOWZqOaJjeWPr+S7peWujOaIkOabtOaWsOOAglxuICAgIOWmguaenOS/ruaUuemdnmVs55qE57uE5Lu25YC877yM6aG16Z2i5YiZ5Y+v5Lul5q2j5bi45Yi35paw44CCXG4gIDwvaDU+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<el-table :data="tableDate">
    <el-table-column label="账号" prop="appAccount" />
			<el-table-column label="用户" prop="appName" />
			<el-table-column label="用户ID" prop="userId" />
			<el-table-column label="用户名" prop="userName" />
    	<!--修改label文字不会热更新-->
			<el-table-column label="No" prop="No" />
    <el-table-column label="操作">
				<template #default="scope">
          <!--按钮文字不会热更新-->
					<el-button link type="danger">删除</el-button>
				</template>
			</el-table-column>
  </el-table>
	<div>
    <p>
      这里的文字如果被修改就可以正常热更新
    </p>
  </div>
```

### What is Expected?

组件自动热更新

### What is actually happening?

部分组件不会热更新

### Additional comments

开发工具使用的是webstorm，在webstorm修改了按钮的文字和table行的label值在chrome的控制台提示了组件被更新，但是页面显示的内容并没有改变，需要刷新浏览器才可以完成更新。 如果修改非el的组件值，页面则可以正常刷新。

**Comment by sxzz** [comment]
https://github.com/vitejs/vite/issues/8224

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/vitejs/vite/issues/8224)
