### ISSUE TITLE
[Component] [container, config-provider] Container

### ISSUE THREAD

**Issue by NasirZpc** [element-plus/element-plus#9146]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: ` Chrome 103.0.5060.114 / macOS 12.1.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-container`
- `el-config-provider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cblxuICBcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNvbmZpZy1wcm92aWRlciBuYW1lc3BhY2U9XCJlcVwiPlxuICAgIDxlbC1jb250YWluZXI+XG4gICAgICA8ZWwtaGVhZGVyPkhlYWRlcjwvZWwtaGVhZGVyPlxuICAgICAgPGVsLW1haW4+TWFpbjwvZWwtbWFpbj5cbiAgICAgIDxlbC1mb290ZXI+Rm9vdGVyPC9lbC1mb290ZXI+XG4gICAgPC9lbC1jb250YWluZXI+XG4gIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

配置组件Config Provider的namespace之后， el-container组件里的判断条件是写死的，无法使用

### What is Expected?

colorPicker组件里的判断条件随Config Provider 配置的前缀 动态变化

### What is actually happening?

el-container组件里的判断条件是写死的，无法使用

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/26620287/182114885-db5c1075-52f7-404c-a85e-9fa9fdd1278c.png)

**Comment by gjfei** [comment]
这个是组件名称，namespace 争对的是css

**Comment by NasirZpc** [comment]
namespace 针对的还有组件的命名吧？ 官方文档是这样写
![WX20220808-143529](https://user-images.githubusercontent.com/26620287/183354548-fdfdf130-76a0-48f8-a739-fada5b6f38c9.png)

**Comment by btea** [comment]
组件名是不会变的，namespace 是修改的 class 前缀
