### ISSUE TITLE
[Component] [dialog] windows 火狐浏览器，官方文档中的案例即可复现问题：页面出现滚动条后，弹出弹框，当弹框关闭的瞬间，弹框会向左移动 17px

### ISSUE THREAD

**Issue by foroorepo** [element-plus/element-plus#9147]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `火狐浏览器`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/dialog.html#%E4%BA%8B%E4%BB%B6)

### Steps to reproduce

我贴的是官方文档链接，在链接的文档中，随便点击一个弹框，然后关闭弹框即可复现

### What is Expected?

弹框不要左移 17px(滚动条的宽度)

### What is actually happening?

弹框左移了 17px（滚动条的宽度）

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
感谢反馈，这个是目前做的一个取舍吧，用了overlay属性，保证chrome的不抖动，本质原因是在lock-screen的处理上，之前尝试了el-scorllbar，它可以很好的解决这个问题，但是我们有一些特殊的需求会无法很好的进行。

**Comment by gjfei** [comment]
不把body当滚动容器
<body  style="height:100vh;overflow: hidden;" ><div class="scroll-container"></div></body>

**Comment by chenxch** [comment]
via #9152
