### ISSUE TITLE
[Component] [tree-select] el-tree-select组件mount后再加载数据，已选中的子级数据不会解析为label

### ISSUE THREAD

**Issue by c521wy** [element-plus/element-plus#9148]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome  103.0.5060.134 / MacOS 12.5`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5cbmNvbnN0IHZhbHVlID0gcmVmKFsgJzEnLCAnMicsICczJyBdKTtcblxuY29uc3QgZGF0YSA9IHJlZigpO1xuXG5zZXRUaW1lb3V0KCgpID0+IHtcbiAgICBkYXRhLnZhbHVlID0gW1xuICAgICAgICB7XG4gICAgICAgICAgICBpZDogJzEnLFxuICAgICAgICAgICAgbGFiZWw6ICfpobbnuqc6SUQ9MScsXG4gICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgaWQ6ICcyJyxcbiAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICflrZDnuqc6SUQ9MicsXG4gICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgICAgIGlkOiAnMycsXG4gICAgICAgICAgICAgICAgICAgIGxhYmVsOiAn5a2Q57qnOklEPTMnLFxuICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBdLFxuICAgICAgICB9LFxuICAgIF07XG59LCA1MDAwKTtcblxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtdHJlZS1zZWxlY3QgY2xlYXJhYmxlXG4gICAgICAgICAgICAgICAgICAgICAgICA6bW9kZWxWYWx1ZT1cInZhbHVlXCJcbiAgICAgICAgICAgICAgICAgICAgICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgICAgICAgICAgICAgICAgICAgICBub2RlLWtleT1cImlkXCJcbiAgICAgICAgICAgICAgICAgICAgICAgIGNoZWNrLXN0cmljdGx5XG4gICAgICAgICAgICAgICAgICAgICAgICBtdWx0aXBsZVxuICAgICAgICAgICAgICAgICAgICAgICAgc2hvdy1jaGVja2JveC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. modelValue有值
2. el-tree-select设置为多选
3. 组件mount之后再加载树形数据

### What is Expected?

数据加载完成后，所有已选中的值都被解析为label

### What is actually happening?

只有树形第一级被解析成label

### Additional comments

经测试2.2.5版本正常，2.2.10 ~ 2.2.12都存在该问题

**Comment by makedopamine** [comment]
hi, you should set `render-after-expand` prop to `true`.

**Comment by c521wy** [comment]
thanks
