### ISSUE TITLE
el-drawer中closeDrawer参数不存在，请问有什么办法解决

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#915]
我在自定义抽屉的效果，因为需要自定义关闭按钮，所以需要使用closeDrawer，但是经过调试之后。无论是自己代码环境还是官方提供的codepen环境都无法得到closeDrawer。
如图所示，他输出了未定义
![2256ZP9G6J75170~R`F~C0](https://user-images.githubusercontent.com/34828964/101598045-83dce600-3a32-11eb-98df-43910fdabd96.png)

**Comment by JeremyWuuuuu** [comment]
> 我在自定义抽屉的效果，因为需要自定义关闭按钮，所以需要使用closeDrawer，但是经过调试之后。无论是自己代码环境还是官方提供的codepen环境都无法得到closeDrawer。
> 如图所示，他输出了未定义
> ![2256ZP9G6J75170R`FC0](https://user-images.githubusercontent.com/34828964/101598045-83dce600-3a32-11eb-98df-43910fdabd96.png)

Sorry for that, I made some changes, you now use `handleClose` to close it you can refer to #817

**Comment by JeremyWuuuuu** [comment]
I should've changed the documentations right after, sorry for that

**Comment by JeremyWuuuuu** [comment]
Fixed in #924

**Comment by JeremyWuuuuu** [comment]
use `refs.drawer.handleClose()` instead
