### ISSUE TITLE
Dialog behavior

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#916]
When dialog first shows, there is obvious cadence to show the body.
![image](https://user-images.githubusercontent.com/38392315/101598826-b3402280-3a33-11eb-9637-438b6cb9db84.png)
![image](https://user-images.githubusercontent.com/38392315/101598839-b804d680-3a33-11eb-91b3-103c6a8ba289.png)

**Comment by JeremyWuuuuu** [comment]
Same as #917 
Per description here: 
> The content of Dialog is lazily rendered, which means the default slot is not rendered onto the DOM until it is firstly opened. Therefore, if you need to perform a DOM manipulation or access a component using ref, do it in the open event callback.

Maybe adding a lazy flag to control this would be better.
