### ISSUE TITLE
[Component] [table] 生产环境报错 开发没问题

### ISSUE THREAD

**Issue by ksmarsh** [element-plus/element-plus#9160]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome  103.0.5060.134`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html#table-column-%E5%B1%9E%E6%80%A7 请原谅我无法复现这个问题的代码)

### Steps to reproduce

使用el-table 组件 

### What is Expected?

一切正常

### What is actually happening?

打包后的项目 初始化页面加载正常 切换也没问题，刷新后，再重复切换 就会报错
Cannot read properties of null (reading 'insertBefore')
Cannot read properties of null (reading 'emitsOptions')
这两个错误 

### Additional comments

救命 ，希望设计人说下这到底是什么问题，该怎么做才能解决。目前这个问题在整个项目里多处出现，没法交付项目啊。

**Comment by ksmarsh** [comment]
我再次提了这个问题以前都没遇到过，

**Comment by ksmarsh** [comment]
是刷新网页后切换路由加载页面出现问题

**Comment by ksmarsh** [comment]
https://codepen.io/ksmarsh/pen/BarYvzx


这是在线的实例 
重现问题需要打包后 运行 最好是进行路由切换。我在开发环境下控制台不会报错 但是使用chromed的调试工具Sources 会显示被vue捕获的异常和错误，我通过它定位到了问题 在el-table组件里使用链式方式获取值 需要提前判断，否则打包后会报错，并且控制台不会显示问题

**Comment by litt1e-p** [comment]
same as el-select

**Comment by ksmarsh** [comment]
> 

你是指vue3.2.29版本吗

**Comment by litt1e-p** [comment]
element-plus v2.2.9

**Comment by ksmarsh** [comment]
我尝试一下
