### ISSUE TITLE
[Component] [input, button] Button 点击以后还是hover的样式, Input clearable 在鼠标hover时长短会变化

### ISSUE THREAD

**Issue by DeluxeYang** [element-plus/element-plus#9168]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.77`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbSA9IHJlYWN0aXZlKHsgaW5wdXQ6IFwiXCIgfSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtZm9ybVxuICAgICAgICAgICBsYWJlbC1wb3NpdGlvbj1cImxlZnRcIlxuICAgICAgICAgICBsYWJlbC13aWR0aD1cImF1dG9cIlxuICAgICAgICAgICBpbmxpbmVcbiAgICAgICAgICAgOm1vZGVsPVwibVwiPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgICAgICAgICAgICBsYWJlbD1cIueUqOaIt+WQjVwiXG4gICAgICAgICAgICAgICAgc2l6ZT1cInNtYWxsXCI+XG4gICAgXHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm0uaW5wdXRcIiBwbGFjZWhvbGRlcj1cIueUqOaIt+WQjVwiIGNsZWFyYWJsZS8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cblxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+UHJpbWFyeTwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

button鼠标点击后，仍然是hover的浅色样式

input放到el-form-item中，鼠标进入和退出input的区域，input的宽度会变化

### What is Expected?

button鼠标点击后，鼠标离开后，变回正常的颜色

input宽度不变

### What is actually happening?

button鼠标点击后，鼠标离开后，仍然是hover的颜色

input宽度变化

### Additional comments

_(empty)_

**Comment by Rainyun** [comment]
我也同样遇到这个问题了，input放到el-form-item中，鼠标进入和退出input的区域，input的宽度会变化，在组件样式加上width值，可以临时解决这个问题

**Comment by DeluxeYang** [comment]
没人管管这个吗。。

**Comment by kingwrcy** [comment]
倒退了3个版本还有这个问题,服了,只能去掉clearable了

**Comment by tolking** [comment]
Button 点击后标准就是hover状态，于是就显示 hover 状态样式。不喜欢可以自己修改

Input 参考 #7287 

提问前可以搜索相关 issues，避免重复

**Comment by DeluxeYang** [comment]
Button 点击后标准就是hover状态？不是吧

**Comment by DeluxeYang** [comment]
Button 点击后标准就是hover状态？不是吧，据我观察github就不是这样的

**Comment by tolking** [comment]
应该是 focus 状态，我说错了 [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1ibG9ja1wiPlxuPGJ1dHRvbiBjbGFzcz1cImJ0bi0xXCI+XG4gIEEgQnV0b25cbiAgICA8L2J1dHRvbj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5leGFtcGxlLWJsb2NrIHtcbiAgbWFyZ2luOiAxcmVtO1xufVxuLmV4YW1wbGUtZGVtb25zdHJhdGlvbiB7XG4gIG1hcmdpbjogMXJlbTtcbn1cbiAgXG4gIC5idG4tMTpmb2N1c3tcbiAgICBjb2xvcjogI2YwMDtcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by DeluxeYang** [comment]
> 请问这个Button 点击后的样式应该如何修改

**Comment by DeluxeYang** [comment]
> Button 点击后标准就是hover状态，于是就显示 hover 状态样式。不喜欢可以自己修改
> 
> Input 参考 #7287
> 
> 提问前可以搜索相关 issues，避免重复



请问这个Button 点击后的样式应该如何修改

**Comment by tolking** [comment]
自己改 .el-button:focus 的相关样式
