### ISSUE TITLE
Dialog v-if="rendered"

### ISSUE THREAD

**Issue by xinzi1990** [element-plus/element-plus#917]
导致首次会有渲染的过程，感觉体验不是很好
![image](https://user-images.githubusercontent.com/19815987/101599736-3a41ca80-3a35-11eb-812d-ca50aded8e6c.png)
![image](https://user-images.githubusercontent.com/19815987/101599748-429a0580-3a35-11eb-812b-8058c34c9d03.png)

**Comment by JeremyWuuuuu** [comment]
Per description in here: https://element-plus.org/#/en-US/component/dialog 
> The content of Dialog is lazily rendered, which means the default slot is not rendered onto the DOM until it is firstly opened. Therefore, if you need to perform a DOM manipulation or access a component using ref, do it in the open event callback.

**Comment by SimonaliaChen** [comment]
It's truely a issue to be optimized. We'll fix it ASAP.
