### ISSUE TITLE
[Component] [upload] [Component] [upload] upload 组件 设置 limit 和 on-exceed 不生效，无法校验个数，version：2.2.11

### ISSUE THREAD

**Issue by qiaoyu113** [element-plus/element-plus#9170]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/upload.html)

### Steps to reproduce

limit 之前可以用，现在更新版本后失效

### What is Expected?

可以限制limit上传数量

### What is actually happening?

无法限制

### Additional comments

很着急，期待您的回复

**Comment by makedopamine** [comment]
There are a workaround that two-way bind `file-list` prop. [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgcmVmPVwidXBsb2FkXCJcbiAgICBjbGFzcz1cInVwbG9hZC1kZW1vXCJcbiAgICBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgIDpsaW1pdD1cIjFcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICAgIDphdXRvLXVwbG9hZD1cImZhbHNlXCJcbiAgICB2LW1vZGVsOmZpbGUtbGlzdD1cImZpbGVMaXN0XCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjdHJpZ2dlcj5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5zZWxlY3QgZmlsZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWJ1dHRvbiBjbGFzcz1cIm1sLTNcIiB0eXBlPVwic3VjY2Vzc1wiIEBjbGljaz1cInN1Ym1pdFVwbG9hZFwiPlxuICAgICAgdXBsb2FkIHRvIHNlcnZlclxuICAgIDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwIHRleHQtcmVkXCI+XG4gICAgICAgIGxpbWl0IDEgZmlsZSwgbmV3IGZpbGUgd2lsbCBjb3ZlciB0aGUgb2xkIGZpbGVcbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdXBsb2FkPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IGdlbkZpbGVJZCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB0eXBlIHsgVXBsb2FkSW5zdGFuY2UsIFVwbG9hZFByb3BzLCBVcGxvYWRSYXdGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuIFxuY29uc3QgZmlsZUxpc3QgPSByZWYoW10pXG5jb25zdCB1cGxvYWQgPSByZWY8VXBsb2FkSW5zdGFuY2U+KClcblxuY29uc3QgaGFuZGxlRXhjZWVkOiBVcGxvYWRQcm9wc1snb25FeGNlZWQnXSA9IChmaWxlcykgPT4ge1xuICB1cGxvYWQudmFsdWUhLmNsZWFyRmlsZXMoKVxuICBjb25zdCBmaWxlID0gZmlsZXNbMF0gYXMgVXBsb2FkUmF3RmlsZVxuICBmaWxlLnVpZCA9IGdlbkZpbGVJZCgpXG4gIHVwbG9hZC52YWx1ZSEuaGFuZGxlU3RhcnQoZmlsZSlcbn1cbmNvbnN0IHN1Ym1pdFVwbG9hZCA9ICgpID0+IHtcbiAgdXBsb2FkLnZhbHVlIS5zdWJtaXQoKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)
