### ISSUE TITLE
[Component] [message] ElMessage bug

### ISSUE THREAD

**Issue by huang-yf3160** [element-plus/element-plus#9172]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.26`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 99.0.4844.82`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIDpwbGFpbj1cInRydWVcIiBAY2xpY2s9XCJvcGVuMlwiPnN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiA6cGxhaW49XCJ0cnVlXCIgQGNsaWNrPVwib3BlbjNcIj53YXJuaW5nPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gOnBsYWluPVwidHJ1ZVwiIEBjbGljaz1cIm9wZW4xXCI+bWVzc2FnZTwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIDpwbGFpbj1cInRydWVcIiBAY2xpY2s9XCJvcGVuNFwiPmVycm9yPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWxNZXNzYWdlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBvcGVuMSA9ICgpID0+IHtcbiAgRWxNZXNzYWdlKCd0aGlzIGlzIGEgbWVzc2FnZS4nKVxufVxuY29uc3Qgb3BlbjIgPSAoKSA9PiB7XG4gIEVsTWVzc2FnZSh7XG4gICAgbWVzc2FnZTogJ0NvbmdyYXRzLCB0aGlzIGlzIGEgc3VjY2VzcyBtZXNzYWdlLicsXG4gICAgdHlwZTogJ3N1Y2Nlc3MnLFxuICB9KVxufVxuY29uc3Qgb3BlbjMgPSAoKSA9PiB7XG4gIEVsTWVzc2FnZSh7XG4gICAgbWVzc2FnZTogJ1dhcm5pbmcsIHRoaXMgaXMgYSB3YXJuaW5nIG1lc3NhZ2UuJyxcbiAgICB0eXBlOiAnd2FybmluZycsXG4gIH0pXG59XG5jb25zdCBvcGVuNCA9ICgpID0+IHtcbiAgRWxNZXNzYWdlLmVycm9yKCdPb3BzLCB0aGlzIGlzIGEgZXJyb3IgbWVzc2FnZS4nKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
  ElMessage({
    message: 'Congrats, this is a success message.',
    type: 'success',
  })
```
然后会报错

### What is Expected?

不报错

### What is actually happening?

TypeError: Cannot set properties of null (setting 'visible')
    at Object.close (_arrayMap.js:7:1)
    at fne (_arrayMap.js:7:1)
    at onClose (_arrayMap.js:7:1)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1603:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1612:21)
    at callHook (runtime-dom.esm-browser.js:3474:13)
    at Object.leave (runtime-dom.esm-browser.js:3551:13)
    at updated (runtime-dom.esm-browser.js:10543:28)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1603:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1612:21)

### Additional comments

_(empty)_

**Comment by huang-yf3160** [comment]
试了几个vue版本都会报错，最新的vue3.2.37不会报错

**Comment by btea** [comment]
通过你上面提供的链接，vue版本切换到3.2.34、3.2.35、3.2.36都可以正常执行，并未报错

**Comment by huang-yf3160** [comment]
> 通过你上面提供的链接，vue版本切换到3.2.34、3.2.35、3.2.36都可以正常执行，并未报错

3.2.26版本呢？vue也没进行破坏性更新

**Comment by huang-yf3160** [comment]
> 
又去试了一下 3.2.26-3.2.31版本，都有这个问题

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/182505680-bf4d8090-7df6-427d-967f-376ec720a180.png)

你用的什么浏览器，版本多少？

**Comment by huang-yf3160** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/182505680-bf4d8090-7df6-427d-967f-376ec720a180.png)
> 
> 你用的什么浏览器，版本多少？

![image](https://user-images.githubusercontent.com/56285360/182506186-d2bb88ac-992b-4531-8f46-8241b9e4e688.png)
Chrome 版本 103.0.5060.134（正式版本） （64 位）

**Comment by huang-yf3160** [comment]
我是在开发环境遇到了，再去Element Plus Playground上尝试的，开发环境用的edge 98.0.1108.62

**Comment by huang-yf3160** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/182505680-bf4d8090-7df6-427d-967f-376ec720a180.png)
> 
> 你用的什么浏览器，版本多少？

你截图版本是3.2.36，有问题的版本是3.2.26-3.2.31

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/182507434-358a2748-5d60-423b-b32a-5aece7c4d8ad.png)

3.2.30 报错了

**Comment by Elvis007** [comment]
![WX20220803-095958](https://user-images.githubusercontent.com/12388527/182507936-f5a88249-e18f-4280-aa3b-f63b8c0be755.png)

3.2.27 也报错啊！！！

> 试了几个vue版本都会报错，最新的vue3.2.37不会报错
![WX20220803-095958](https://user-images.githubusercontent.com/12388527/182508027-b8dd16e7-ca48-466d-b991-8207b81977e3.png)

3.2.27 也报错了，这个问题很严重

**Comment by huang-yf3160** [comment]
> ![WX20220803-095958](https://user-images.githubusercontent.com/12388527/182507936-f5a88249-e18f-4280-aa3b-f63b8c0be755.png)
> 
> 3.2.27 也报错啊！！！
> 
> > 试了几个vue版本都会报错，最新的vue3.2.37不会报错
> > ![WX20220803-095958](https://user-images.githubusercontent.com/12388527/182508027-b8dd16e7-ca48-466d-b991-8207b81977e3.png)
> 
> 3.2.27 也报错了，这个问题很严重

我说的是3.3.37，这个问题会导致整个页面崩掉

**Comment by btea** [comment]
@huang-yf3160 3.2.37表现是正常的

**Comment by huang-yf3160** [comment]
> 



> @huang-yf3160 3.2.37表现是正常的

是的，我已经升级vue版本，暂时规避这个问题了

**Comment by zhangtke** [comment]
exposeProxy不是必然初始化的，只有在特定场景才会被初始化，使用它是有问题的

**Comment by wgyy** [comment]
新版本的确没有问题，但是我仿照message组件写的话，自己用到exposeProxy会为null，但是exposed参数则能正常获取，vue的版本为3.2.37，就很奇特

**Comment by huang-yf3160** [comment]
这个问题那么严重，为什么不紧急修复？会导致整个页面崩掉的

**Comment by Lionad-Morotar** [comment]
@btea 你好，请问这个修复什么时候能发版

**Comment by btea** [comment]
@Lionad-Morotar 这个问题我目前还在调整，发版应该要到周五。不过，我建议vue版本更新到3.2.32及以后，则不会存在这个问题。

**Comment by wgyy** [comment]
> @Lionad-Morotar 这个问题我目前还在调整，发版应该要到周五。不过，我建议vue版本更新到3.2.32及以后，则不会存在这个问题。

你好，我咨询一下，exposeProxy这个属性我本地试了一下是null值，这个属性是在什么时候会被初始化的？

**Comment by btea** [comment]
@wgyy 我本地尝试了一下，得到的也是null。这个属性我也是第一次知道，不熟悉 🤦‍♂️

**Comment by wgyy** [comment]
> @wgyy ~我本地尝试了一下，得到的也是null。这个属性我也是第一次知道，不熟悉 🤦‍♂️~ 我这里写了个[例子](https://sfc.vuejs.org/#eNq1UsFOwzAM/ZWQS4u0peI6dUhomsSJI1x62Rp3y5TEUZIOUNV/x0m7CnGAE5eq9nt+tp8z8CfnxLUHvuF1aL1ykQWIvXtsrDIOfWQD89CtWOvhEOH1BSWsKGMleDayzqNhBdUXC3+Hxs15UaUgyRPcog2RmXBi26RYFs+gNbI39FreFfeNvVHoGw/Kkv6WSWx7AzaKqf1eQ4rKQqprKpkKrpaGIvK3EcvUmAjToGVm0A43ZUIW5SPKT3Fwjpi7s9KyXFiiUz7EuWfG5paoQWg8TbKipVZoiUJoXU0mkn0URDBO00gUMVafHx6HIRswjnVFUc4q63paYW1ISm8bTnjDCaqrpZqv+OTt2hycuAS0dK0hVTczEBq+YTmTcuR3iht+jtGFTVWFrk1HuASB/lTRn/C9jcqAgGDWR4/vgba9kEqSGBs7Usvb6f54GT8ewe93zo8je5UvLqEjn/cfDgOUefy0vR3/zcjxC+ZYCgQ=)，能够看到`exposeProxy`有值，你可以看一下。

多谢，我尝试了一下，应该是vue版本不同导致的，换成最新的版本就有这个属性，不过exposed属性则都会存在，比较保险一点。
