### ISSUE TITLE
element-plus ---vue3.0  引入部分组件 报错

### ISSUE THREAD

**Issue by Bo-LiangD** [element-plus/element-plus#918]
ERROR  Failed to compile with 2 errors                                                                                                                                                                    3:42:24 ├F10: PM┤
This dependency was not found:

* element-plus/lib/theme-chalk/el-collapse-transition.css in ./src/plugins/element.js

To install it, you can run: npm install --save element-plus/lib/theme-chalk/el-collapse-transition.css

This relative module was not found:

* ../el-cascader-panel/src/types in ./node_modules/element-plus/lib/el-cascader-panel/index.js

说找不到 该模块   ........

**Comment by zazzaz** [comment]
Can you try the latest version 1.0.1-beta.6, please?

**Comment by Bo-LiangD** [comment]
> 您可以尝试最新版本1.0.1-beta.6吗？

刚换成了 最新的版本      
element-plus / lib / theme-chalk / el-collapse-transition.css 还是找不到 这个 文件
然后错误信息还是一样的。。。
![1c1845d22b61773c4a0b454784e3215](https://user-images.githubusercontent.com/29296518/101602613-5fd0d300-3a39-11eb-97ad-3950df658482.png)
![7c8c1333d6fd528a9774d67df8e1ef8](https://user-images.githubusercontent.com/29296518/101602622-61020000-3a39-11eb-832e-2efd7ebd02ef.png)

**Comment by zazzaz** [comment]
oh I see.

will fix soon

**Comment by zazzaz** [comment]
fixed in #959 and avaliable in `1.0.1-beta.8`
