### ISSUE TITLE
[Component] [table] Clear table data then show the wrong height

### ISSUE THREAD

**Issue by asdjgfr** [element-plus/element-plus#9180]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwicGxheS1jb250YWluZXJcIj5cbiAgICA8ZGl2PlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVBZGRcIj5hZGQ8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiaGFuZGxlQ2xlYXJcIj5jbGVhcjwvZWwtYnV0dG9uPiZlbXNwO1xuICAgICAgPGVsLXN3aXRjaCB2LW1vZGVsPVwid2l0aG91dEVtcHR5XCIgLz5cbiAgICAgIHdpdGhvdXQgZW1wdHkgc2xvdFxuICAgICAgPGg0PkZpcnN0IHRyeTwvaDQ+XG4gICAgICA8b2w+XG4gICAgICAgIDxsaT5DbGljayB0aGUgPGI+Y2xlYXIgYnV0dG9uPC9iPjwvbGk+XG4gICAgICAgIDxsaT5IZWlnaHQgbm90IGNvcnJlY3Q8L2xpPlxuICAgICAgICA8bGk+VHJ5IHRvIHN3aXRjaCBlbXB0eSBzbG90PC9saT5cbiAgICAgIDwvb2w+XG4gICAgICA8aDQ+U2Vjb25kIHRyeTwvaDQ+XG4gICAgICA8b2w+XG4gICAgICAgIDxsaT5DbGljayB0aGUgPGI+YWRkIGJ1dHRvbjwvYj4gYWJvdXQgMjAgdGltZXM8L2xpPlxuICAgICAgICA8bGk+Q2xpY2sgdGhlIDxiPmNsZWFyIGJ1dHRvbjwvYj48L2xpPlxuICAgICAgICA8bGk+SGVpZ2h0IG5vdCBjb3JyZWN0PC9saT5cbiAgICAgICAgPGxpPlRyeSB0byBzd2l0Y2ggZW1wdHkgc2xvdDwvbGk+XG4gICAgICA8L29sPlxuICAgIDwvZGl2PlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiBwcm9wPVwibmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHByb3A9XCJkYXRlXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJBZGRyZXNzXCIgcHJvcD1cImFkZHJlc3NcIiAvPlxuICAgICAgPHRlbXBsYXRlICNlbXB0eSB2LWlmPVwiIXdpdGhvdXRFbXB0eVwiPlxuICAgICAgICA8ZWwtZW1wdHkgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHdpdGhvdXRFbXB0eSA9IHJlZihmYWxzZSlcbmNvbnN0IHRhYmxlRGF0YSA9IHJlYWN0aXZlKFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl0pXG5cbmZ1bmN0aW9uIGhhbmRsZUFkZCgpIHtcbiAgdGFibGVEYXRhLnB1c2goe1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSlcbn1cbmZ1bmN0aW9uIGhhbmRsZUNsZWFyKCkge1xuICB0YWJsZURhdGEuc3BsaWNlKDAsIHRhYmxlRGF0YS5sZW5ndGgpXG59XG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzY3NzXCI+PC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce
``` vue
<template>
  <div class="play-container">
    <div>
      <el-button @click="handleAdd">add</el-button>
      <el-button @click="handleClear">clear</el-button>&emsp;
      <el-switch v-model="withoutEmpty" />
      without empty slot
      <h4>First try</h4>
      <ol>
        <li>Click the <b>clear button</b></li>
        <li>Height not correct</li>
        <li>Try to switch empty slot</li>
      </ol>
      <h4>Second try</h4>
      <ol>
        <li>Click the <b>add button</b> about 20 times</li>
        <li>Click the <b>clear button</b></li>
        <li>Height not correct</li>
        <li>Try to switch empty slot</li>
      </ol>
    </div>
    <el-table :data="tableData">
      <el-table-column label="Name" prop="name" />
      <el-table-column label="Date" prop="date" />
      <el-table-column label="Address" prop="address" />
      <template #empty v-if="!withoutEmpty">
        <el-empty />
      </template>
    </el-table>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
const withoutEmpty = ref(false)
const tableData = reactive([
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
])

function handleAdd() {
  tableData.push({
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  })
}
function handleClear() {
  tableData.splice(0, tableData.length)
}
</script>
```
### What is Expected?

When table from data to no data, computed the right height

### What is actually happening?

Empty block overflow

### Additional comments

![chrome_p5ugGm4IH2](https://user-images.githubusercontent.com/23442840/182520597-a41970fc-a1fc-4f5d-904f-3fbb2cd7ad43.gif)

**Comment by YujiaCheng1996** [comment]
问题挺严重的，未指定高度的空表格直接高度暴增，根本停不下来。

**Comment by Jeffrey-mu** [comment]
[解决pr](https://github.com/element-plus/element-plus/commit/67ae7a9f2a59c97b210e6a5081e7c851aa15823f)

**Comment by Jeffrey-mu** [comment]
当有插槽组件时 empty 高度计算不参考body

**Comment by phoenixor** [comment]
遇到同样的问题，我做的是简单的查询系统，搜索结果展示在table，如果上一次结果有20行数据，下一次查询是空数据，空数据显示还是20行空行，无数据三个字居中显示，已经飞出屏幕了，正常应该只显示一行空数据

**Comment by Jeffrey-mu** [comment]
目前暂无数据的高度是和tbody的高度保持一致的没有问题
这个pr是解决empty插槽的高度不受tbody高度影响

**Comment by phoenixor** [comment]
> 目前暂无数据的高度是和tbody的高度保持一致的没有问题 这个pr是解决empty插槽的高度不受tbody高度影响

前一次查询有20条数据，本次查询是空数据，tbody应该恢复成一行显示无数据，而不是保持20行的空行，这样并不合理

**Comment by Jeffrey-mu** [comment]
@phoenixor 这是个设计问题 你可以提个issues 😊

**Comment by phoenixor** [comment]
> Bug Type: **`Component`**
> 
> ## Environment
> * Vue Version: `3.2.37`
> * Element Plus Version: `2.2.12`
> * Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50`
> * Build Tool: `Vite`
> 
> ## Reproduction
> ### Related Component
> * `el-table`
> 
> ### Reproduction Link
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwicGxheS1jb250YWluZXJcIj5cbiAgICA8ZGl2PlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVBZGRcIj5hZGQ8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiaGFuZGxlQ2xlYXJcIj5jbGVhcjwvZWwtYnV0dG9uPiZlbXNwO1xuICAgICAgPGVsLXN3aXRjaCB2LW1vZGVsPVwid2l0aG91dEVtcHR5XCIgLz5cbiAgICAgIHdpdGhvdXQgZW1wdHkgc2xvdFxuICAgICAgPGg0PkZpcnN0IHRyeTwvaDQ+XG4gICAgICA8b2w+XG4gICAgICAgIDxsaT5DbGljayB0aGUgPGI+Y2xlYXIgYnV0dG9uPC9iPjwvbGk+XG4gICAgICAgIDxsaT5IZWlnaHQgbm90IGNvcnJlY3Q8L2xpPlxuICAgICAgICA8bGk+VHJ5IHRvIHN3aXRjaCBlbXB0eSBzbG90PC9saT5cbiAgICAgIDwvb2w+XG4gICAgICA8aDQ+U2Vjb25kIHRyeTwvaDQ+XG4gICAgICA8b2w+XG4gICAgICAgIDxsaT5DbGljayB0aGUgPGI+YWRkIGJ1dHRvbjwvYj4gYWJvdXQgMjAgdGltZXM8L2xpPlxuICAgICAgICA8bGk+Q2xpY2sgdGhlIDxiPmNsZWFyIGJ1dHRvbjwvYj48L2xpPlxuICAgICAgICA8bGk+SGVpZ2h0IG5vdCBjb3JyZWN0PC9saT5cbiAgICAgICAgPGxpPlRyeSB0byBzd2l0Y2ggZW1wdHkgc2xvdDwvbGk+XG4gICAgICA8L29sPlxuICAgIDwvZGl2PlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiBwcm9wPVwibmFtZVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiRGF0ZVwiIHByb3A9XCJkYXRlXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJBZGRyZXNzXCIgcHJvcD1cImFkZHJlc3NcIiAvPlxuICAgICAgPHRlbXBsYXRlICNlbXB0eSB2LWlmPVwiIXdpdGhvdXRFbXB0eVwiPlxuICAgICAgICA8ZWwtZW1wdHkgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHdpdGhvdXRFbXB0eSA9IHJlZihmYWxzZSlcbmNvbnN0IHRhYmxlRGF0YSA9IHJlYWN0aXZlKFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl0pXG5cbmZ1bmN0aW9uIGhhbmRsZUFkZCgpIHtcbiAgdGFibGVEYXRhLnB1c2goe1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSlcbn1cbmZ1bmN0aW9uIGhhbmRsZUNsZWFyKCkge1xuICB0YWJsZURhdGEuc3BsaWNlKDAsIHRhYmxlRGF0YS5sZW5ndGgpXG59XG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzY3NzXCI+PC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> ### Steps to reproduce
> ```
> <template>
>   <div class="play-container">
>     <div>
>       <el-button @click="handleAdd">add</el-button>
>       <el-button @click="handleClear">clear</el-button>&emsp;
>       <el-switch v-model="withoutEmpty" />
>       without empty slot
>       <h4>First try</h4>
>       <ol>
>         <li>Click the <b>clear button</b></li>
>         <li>Height not correct</li>
>         <li>Try to switch empty slot</li>
>       </ol>
>       <h4>Second try</h4>
>       <ol>
>         <li>Click the <b>add button</b> about 20 times</li>
>         <li>Click the <b>clear button</b></li>
>         <li>Height not correct</li>
>         <li>Try to switch empty slot</li>
>       </ol>
>     </div>
>     <el-table :data="tableData">
>       <el-table-column label="Name" prop="name" />
>       <el-table-column label="Date" prop="date" />
>       <el-table-column label="Address" prop="address" />
>       <template #empty v-if="!withoutEmpty">
>         <el-empty />
>       </template>
>     </el-table>
>   </div>
> </template>
> 
> <script setup lang="ts">
> import { reactive, ref } from 'vue'
> const withoutEmpty = ref(false)
> const tableData = reactive([
>   {
>     date: '2016-05-03',
>     name: 'Tom',
>     address: 'No. 189, Grove St, Los Angeles',
>   },
> ])
> 
> function handleAdd() {
>   tableData.push({
>     date: '2016-05-03',
>     name: 'Tom',
>     address: 'No. 189, Grove St, Los Angeles',
>   })
> }
> function handleClear() {
>   tableData.splice(0, tableData.length)
> }
> </script>
> ```
> 
> ### What is Expected?
> When table from data to no data, computed the right height
> 
> ### What is actually happening?
> Empty block overflow
> 
> ### Additional comments
> ![chrome_p5ugGm4IH2](https://user-images.githubusercontent.com/23442840/182520597-a41970fc-a1fc-4f5d-904f-3fbb2cd7ad43.gif) [ ![chrome_p5ugGm4IH2](https://user-images.githubusercontent.com/23442840/182520597-a41970fc-a1fc-4f5d-904f-3fbb2cd7ad43.gif) ](https://user-images.githubusercontent.com/23442840/182520597-a41970fc-a1fc-4f5d-904f-3fbb2cd7ad43.gif) [ ](https://user-images.githubusercontent.com/23442840/182520597-a41970fc-a1fc-4f5d-904f-3fbb2cd7ad43.gif)

发现很奇怪的现象，用你playground的代码，没有复现出bug（"element-plus": "^2.2.16","vue": "^3.2.38"），复制到vscode运行时bug依旧，依赖版本都一样，换了几个浏览器都是这样，崩溃了

**Comment by tsyrya** [comment]
Unforunatelly, It still works this way, pretty annoying. I use 2.11.2 version
