### ISSUE TITLE
[TypeScript] checkbox和radio的change事件ts类型校验还是有问题

### ISSUE THREAD

**Issue by TaoziDeGitHub** [element-plus/element-plus#9182]
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37`
- Build Tool: `Vite`

### Related Component

- `el-checkbox`
- `el-checkbox-group`
- `el-radio`
- `el-radio-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBpc0NoZWNrQWxsID0gcmVmKGZhbHNlKVxuXG5mdW5jdGlvbiBoYW5kbGVDaGVja0FsbCh2YWw6IGJvb2xlYW4pIHtcbiAgLy8gZG8gc29tZXRpbmdcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8IS0tIOi/memHjHRz5oql6ZSZ77ya5LiN6IO95bCG57G75Z6L4oCcKHZhbDogYm9vbGVhbikgPT4gdm9pZOKAneWIhumFjee7meexu+Wei+KAnCh2YWw6IENoZWNrYm94VmFsdWVUeXBlKSA9PiBhbnnigJ3jgIJcbiAg5Y+C5pWw4oCcdmFs4oCd5ZKM4oCcdmFs4oCdIOeahOexu+Wei+S4jeWFvOWuueOAgiAtLT5cbiAgPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJpc0NoZWNrQWxsXCIgQGNoYW5nZT1cImhhbmRsZUNoZWNrQWxsXCI+5YWo6YCJPC9lbC1jaGVja2JveD5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

@change事件指定了回调参数val类型就报错

### What is Expected?

ts检校不报错

### What is actually happening?

ts检校报错

### Additional comments

_(empty)_

**Comment by Tsong-LC** [comment]
`type CheckboxValueType = string | number | boolean`

**Comment by pyvadev** [comment]
@Tsong-LC Where this code should be add? Thanks!
