### ISSUE TITLE
[Component] [autocomplete] Autodcomplete 自动补全输入框失去焦点的时候没有触发 blur方法

### ISSUE THREAD

**Issue by wangzhaoqiang666** [element-plus/element-plus#9183]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 103.0.5060.114 windows 10`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBzdGF0ZTIgPSByZWYoJycpXG5jb25zdCBxdWVyeVNlYXJjaCA9ICgpID0+IHt9XG5jb25zdCBhdXRvQmx1ciA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2JsdXInKVxufVxuY29uc3QgYXV0b0ZvY3VzID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnZm9jdXMnKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgICAgIHYtbW9kZWw9XCJzdGF0ZTJcIlxuICAgICAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaFwiXG4gICAgICAgIDp0cmlnZ2VyLW9uLWZvY3VzPVwiZmFsc2VcIlxuICAgICAgICBjbGVhcmFibGVcbiAgICAgICAgY2xhc3M9XCJpbmxpbmUtaW5wdXQgdy01MFwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIElucHV0XCJcbiAgICAgICAgQGJsdXI9XCJhdXRvQmx1clwiXG4gICAgICAgIEBmb2N1cz1cImF1dG9Gb2N1c1wiXG4gICAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开控制台，输入框输入内容后让其失去焦点，blur方法没有触发

### What is Expected?

输入框失去焦点时，blur方法触发成功

### What is actually happening?

没有触发

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
@tolking related to #8350

**Comment by HWYD** [comment]
还是会出现这个问题，点击组件外面，想触发blur事件但是无效

**Comment by faga1** [comment]
It looks like it's because of the ignoreFocusEvent, is this a feature or a bug?
