### ISSUE TITLE
[Component] [button] API type.text is about to be deprecated in version 3.0.0, please use type.link instead.

### ISSUE THREAD

**Issue by XxxDDD2009** [element-plus/element-plus#9186]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 103.0.5060.114 / Mac OS 12.0.1`
- Build Tool: `Vue CLI`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJsaW5rXCI+dGVzdDwvZWwtYnV0dG9uPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCI+dGVzdDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

use type.link instead of type.text

### What is Expected?

Just like type.text

### What is actually happening?

It dose not take effect

### Additional comments

There are no example on the documentation

**Comment by init-qy** [comment]
not `type=link` current usage is `:link="true"`

**Comment by XxxDDD2009** [comment]
> 
Thanks!
But it has different effect than `type="text"`

**Comment by XxxDDD2009** [comment]
> not `type=link` current usage is `:link="true"`

Thanks!
But it has different effect than `type="text"`

**Comment by suhli** [comment]
> not `type=link` current usage is `:link="true"`

![image](https://user-images.githubusercontent.com/23626907/187140184-006732b8-4bec-4423-aade-7f2af539ba5e.png)
confusing
