### ISSUE TITLE
[Component] [table] 按需加载之后 el-table自定义指令 v-loading 导致页面报错 

### ISSUE THREAD

**Issue by jiangkeyuan** [element-plus/element-plus#9187]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgPGVsLXRhYmxlIHYtbG9hZGluZz48L2VsLXRhYmxlPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

打开任何一个页面 带列表

### What is Expected?

正常显示页面

### What is actually happening?

el-table 无法正常显示

### Additional comments

```
runtime-core.esm-bundler.js:2764 Uncaught TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:2764:17)
    at Proxy._sfc_render (sme-table-list.vue:124:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5694:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5708:9)
    at mountComponent (runtime-core.esm-bundler.js:5490:9)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
withDirectives @ runtime-core.esm-bundler.js:2764
_sfc_render @ sme-table-list.vue:124
renderComponentRoot @ runtime-core.esm-bundler.js:896
componentUpdateFn @ runtime-core.esm-bundler.js:5580
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
setupRenderEffect @ runtime-core.esm-bundler.js:5708
mountComponent @ runtime-core.esm-bundler.js:5490
processComponent @ runtime-core.esm-bundler.js:5448
patch @ runtime-core.esm-bundler.js:5038
mountChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:5407
patch @ runtime-core.esm-bundler.js:5031
componentUpdateFn @ runtime-core.esm-bundler.js:5587
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
setupRenderEffect @ runtime-core.esm-bundler.js:5708
mountComponent @ runtime-core.esm-bundler.js:5490
processComponent @ runtime-core.esm-bundler.js:5448
patch @ runtime-core.esm-bundler.js:5038
componentUpdateFn @ runtime-core.esm-bundler.js:5587
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
setupRenderEffect @ runtime-core.esm-bundler.js:5708
mountComponent @ runtime-core.esm-bundler.js:5490
processComponent @ runtime-core.esm-bundler.js:5448
patch @ runtime-core.esm-bundler.js:5038
render2 @ runtime-core.esm-bundler.js:6209
mount @ runtime-core.esm-bundler.js:4402
app.mount @ runtime-dom.esm-bundler.js:1605
(anonymous) @ main.js:10
```

![image](https://user-images.githubusercontent.com/40256761/182761622-779723b5-8d5d-4d51-802c-a804c19151e7.png)

**Comment by jiangkeyuan** [comment]
https://github.com/antfu/unplugin-vue-components/issues/152

**Comment by zjiafeng** [comment]
我也遇到了同样了问题，暂代的解决方案为：
`
import { createApp } from 'vue'
import App from './App.vue'
import { vLoading } from 'element-plus'
import 'element-plus/theme-chalk/el-loading.css'

const app = createApp(App)

app.directive('loading', vLoading)
    .mount('#app')
`

**Comment by zjiafeng** [comment]
```
import { createApp } from 'vue'
import App from './App.vue'
import { vLoading } from 'element-plus'
import 'element-plus/theme-chalk/el-loading.css'

const app = createApp(App)

app.directive('loading', vLoading)
    .mount('#app')
```

**Comment by doufu527** [comment]
> 

为什么我这样写了还是报错呢
