### ISSUE TITLE
[Component] [date-picker] el-date-picker type=datetimerange加上format="YYYY-MM-DD hh:mm:ss", 有12小时的误差

### ISSUE THREAD

**Issue by stevensy** [element-plus/element-plus#9189]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 103.0.5060.134 / macOS 12.4`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5sZXQgYWN0aXZpdHlUaW1lID0gcmVmKFtdKSwgdGltZSA9IHJlZignJyksXG4gZm9ybWF0ZVRpbWUgPSBjb21wdXRlZCgoKSA9PiB7XG4gIHJldHVybiAodGltZXMpID0+IHtcbiAgICByZXR1cm4gQXJyYXkuaXNBcnJheSh0aW1lcykgPyB0aW1lcy5tYXAodGltZSA9PiBuZXcgRGF0ZSh0aW1lKS50b0xvY2FsZVN0cmluZygpKSA6IHRpbWVzID8gbmV3IERhdGUodGltZXMpLnRvTG9jYWxlU3RyaW5nKCkgOiAnJ1xuICB9XG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPuaXtumXtOaIs++8mnt7IGFjdGl2aXR5VGltZSB9fTwvaDE+XG4gIDxoMj5cbiAgICDmoLzlvI/ljJbml7bpl7Q6IHt7IGZvcm1hdGVUaW1lKGFjdGl2aXR5VGltZSkgfX1cbiAgPC9oMj5cblxuXHQ8ZWwtZGF0ZS1waWNrZXJcbiAgICB2LW1vZGVsPVwiYWN0aXZpdHlUaW1lXCJcbiAgICB0eXBlPVwiZGF0ZXRpbWVyYW5nZVwiXG4gICAgcmFuZ2Utc2VwYXJhdG9yPVwiLVwiXG4gICAgc3RhcnQtcGxhY2Vob2xkZXI9XCLlvIDlp4vml7bpl7RcIlxuICAgIGVuZC1wbGFjZWhvbGRlcj1cIue7k+adn+aXtumXtFwiXG4gICAgZm9ybWF0PVwiWVlZWS1NTS1ERCBoaDptbTpzc1wiICAgICAgICAgICAgICBcbiAgIFx0dmFsdWUtZm9ybWF0PVwieFwiXG4gICAvPlxuICAgPGhyIC8+XG4gIDxoMT7ml7bpl7TmiLPvvJp7eyB0aW1lIH19PC9oMT5cbiAgPGgyPlxuICAgIOagvOW8j+WMluaXtumXtDoge3sgZm9ybWF0ZVRpbWUodGltZSkgfX1cbiAgPC9oMj5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgdi1tb2RlbD1cInRpbWVcIlxuICAgIHR5cGU9XCJkYXRlXCJcbiBcdFx0cGxhY2Vob2xkZXI9XCLpgInmi6nml7bpl7RcIlxuICAgIGZvcm1hdD1cIllZWVktTU0tREQgaGg6bW06c3NcIlxuICAgXHR2YWx1ZS1mb3JtYXQ9XCJ4XCJcbiAgIC8+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.选择开始和结束日期，时间默认是12:00:00(没选，选了也一样)，得到时间戳
2.通过js方法转回"YYYY-MM-DD hh:mm:ss",是00:00:00,(如果选了分秒，则会显示：00:xx:xx)

如果不加format="YYYY-MM-DD hh:mm:ss"，是正常的

### What is Expected?

正常展示时间

### What is actually happening?

展示的时候少了12小时

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
小写的h是12小时制，你可能需要换成大写 YYYY-MM-DD HH:mm:ss 
see more [dayjs-foramt](https://day.js.org/docs/zh-CN/display/format)

**Comment by stevensy** [comment]
是的，谢稿 @init-qy
