### ISSUE TITLE
el-select 多选 显示有问题，内容溢出

### ISSUE THREAD

**Issue by LuoRiWuSheng** [element-plus/element-plus#919]
2020-12-09 

版本号： @1.0.1-beta.6

代码复现

[code pen](https://codepen.io/luoriwusheng/pen/KKgggaj)

期望：
做成像单选框那样， 即使是多选，也不要溢出

单选框是没有溢出的

**Comment by LuoRiWuSheng** [comment]
element-ui 也有 即使是最新的 也仍旧存在

**Comment by JeremyWuuuuu** [comment]
Got it, this needs to be taking care of, we will fix this along with #874
