### ISSUE TITLE
[Component] [table] el-table 数据变空显示No Data后高度没有自适应

### ISSUE THREAD

**Issue by WLYuJian** [element-plus/element-plus#9195]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 104.0.5112.80`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImJ1dHRvbkNsaWNrXCI+5rWL6K+VPC9lbC1idXR0b24+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG5kYXRhKCl7XG4gICAgICByZXR1cm4ge1xuICAgICAgICB0YWJsZURhdGEgOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICAgIH1dXG4gICAgICB9XG4gICAgfSxcbiAgICBtZXRob2RzOntcbiAgICAgIGJ1dHRvbkNsaWNrKCl7XG4gICAgICAgIGlmKHRoaXMudGFibGVEYXRhLmxlbmd0aD09MCl7XG4gICAgICAgICAgIHRoaXMudGFibGVEYXRhID0gW1xuICAgICAgICB7XG4gICAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9XVxuICAgICAgICB9XG4gICAgICAgIGVsc2V7XG4gICAgICAgIHRoaXMudGFibGVEYXRhID0gW11cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

原有绑定数据，数据重置为空

### What is Expected?

同Element Plus Version 2.2.9效果

### What is actually happening?

高度不变，如果原本是100条数据，置空后高度还是一百条数据的高度

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Link #9180
