### ISSUE TITLE
[Docs] [All] 官网经常404，能不能稳定点

### ISSUE THREAD

**Issue by WLYuJian** [element-plus/element-plus#9196]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 104.0.5112.80`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

官网经常报错，切换组件文档时频繁报错

### What is Expected?

不报错

### What is actually happening?

报错

### Additional comments

_(empty)_

**Comment by wjw-gavin** [comment]
正常使用情况下，没出现过404。倒是疯狂切换组件导航时，会发生404卡死的情况（不过谁没事在那一直切换.....）

**Comment by DeluxeYang** [comment]
404  503

**Comment by wangdaodao** [comment]
@WLYuJian 建议给社区捐赠服务器

**Comment by WLYuJian** [comment]
> @WLYuJian 建议给社区捐赠服务器
让社区众筹

**Comment by WLYuJian** [comment]
> 正常使用情况下，没出现过404。倒是疯狂切换组件导航时，会发生404卡死的情况（不过谁没事在那一直切换.....）

我使用时出现的频率还是很高的，很多时候不是疯狂切换组件，只是正常切换而已
