### ISSUE TITLE
[Component] [popover] closes automatically after opened bug

### ISSUE THREAD

**Issue by jopms** [element-plus/element-plus#9201]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Chrome/103.0.5060.134 (Macintosh; Intel Mac OS x 10.15.7)`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cblxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXBvcG92ZXIgdi1tb2RlbDp2aXNpYmxlPVwidmlzaWJsZVwiIHRyaWdnZXI9XCJjbGlja1wiIHBsYWNlbWVudD1cImJvdHRvbVwiIDp3aWR0aD1cIjE2MFwiPlxuICAgIDxwPkFyZSB5b3Ugc3VyZSB0byBkZWxldGUgdGhpcz88L3A+XG4gICAgPGRpdiBzdHlsZT1cInRleHQtYWxpZ246IHJpZ2h0OyBtYXJnaW46IDBcIj5cbiAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdGV4dCBAY2xpY2s9XCJ2aXNpYmxlID0gZmFsc2VcIj5jYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlID0gZmFsc2VcIlxuICAgICAgICA+Y29uZmlybTwvZWwtYnV0dG9uXG4gICAgICA+XG4gICAgPC9kaXY+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGUgPSB0cnVlXCI+RGVsZXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click button.

### What is Expected?

el-popover stays open.

### What is actually happening?

el-popover closes automatically after opened.

### Additional comments

This was introduced in version `2.2.10`, in version `2.2.9` the behavior it is correct.

Also, it does not happen with `trigger='hover'`.

**Comment by chenxch** [comment]
Version `2.2.10` adjusts the controlled mode to a more reasonable scheme. The controlled mode can use `:visible`  instead of `v-model:visible`

**Comment by jopms** [comment]
Thanks for the feedback. I do think then that [this example](https://element-plus.org/en-US/component/popover.html#nested-operation) is not accordingly.

**Comment by Benleie** [comment]
annoying bug. I also find this

**Comment by Benleie** [comment]
> Thanks for the feedback. I do think then that [this example](https://element-plus.org/en-US/component/popover.html#nested-operation) is not accordingly.

@jopms @chenxch  Yes, this example is not updated for the latest controlled mode.  `v-model` is still used and you can see popover is triggered by hover.
