### ISSUE TITLE
[Bug Report][Component] [autocomplete] When the El autocomplete component is located at the bottom of the page, the positioning of the suggestion list is abnormal

### ISSUE THREAD

**Issue by zhemekuyizhi** [element-plus/element-plus#9202]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzdGF0ZSA9IHJlZignJylcblxuaW50ZXJmYWNlIExpbmtJdGVtIHtcbiAgdmFsdWU6IHN0cmluZ1xuICBsaW5rOiBzdHJpbmdcbn1cblxuY29uc3QgbGlua3MgPSByZWY8TGlua0l0ZW1bXT4oW10pXG5cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyMScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlLXJvdXRlcicgfSxcbiAgICB7IHZhbHVlOiAndnVlLXJvdXRlcjInLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL3Z1ZWpzL3Z1ZS1yb3V0ZXInIH0sXG4gICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyMycsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlLXJvdXRlcicgfSxcbiAgICB7IHZhbHVlOiAnYmFiZWwnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL2JhYmVsL2JhYmVsJyB9LFxuICBdXG59XG5cbmxldCB0aW1lb3V0OiBOb2RlSlMuVGltZW91dFxuY29uc3QgcXVlcnlTZWFyY2hBc3luYyA9IChxdWVyeVN0cmluZzogc3RyaW5nLCBjYjogKGFyZzogYW55KSA9PiB2b2lkKSA9PiB7XG4gIGNvbnN0IHJlc3VsdHMgPSBxdWVyeVN0cmluZ1xuICAgID8gbGlua3MudmFsdWUuZmlsdGVyKGNyZWF0ZUZpbHRlcihxdWVyeVN0cmluZykpXG4gICAgOiBsaW5rcy52YWx1ZVxuXG4gIGNsZWFyVGltZW91dCh0aW1lb3V0KVxuICB0aW1lb3V0ID0gc2V0VGltZW91dCgoKSA9PiB7XG4gICAgY2IocmVzdWx0cylcbiAgfSwgMzAwMCAqIE1hdGgucmFuZG9tKCkpXG59XG5jb25zdCBjcmVhdGVGaWx0ZXIgPSAocXVlcnlTdHJpbmc6IHN0cmluZykgPT4ge1xuICByZXR1cm4gKHJlc3RhdXJhbnQ6IExpbmtJdGVtKSA9PiB7XG4gICAgcmV0dXJuIChcbiAgICAgIHJlc3RhdXJhbnQudmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwXG4gICAgKVxuICB9XG59XG5cbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtOiBMaW5rSXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZyhpdGVtKVxufVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBsaW5rcy52YWx1ZSA9IGxvYWRBbGwoKVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gPHA+XG4gICAxXG4gIDwvcD5cbiAgPHA+XG4gICAxXG4gIDwvcD5cbiAgPHA+XG4gICAxXG4gIDwvcD5cbiAgIDxwPlxuICAgMVxuICA8L3A+XG4gIDxwPlxuICAgMVxuICA8L3A+PHA+XG4gICAxXG4gIDwvcD5cbiAgPHA+XG4gICAxXG4gIDwvcD48cD5cbiAgIDFcbiAgPC9wPjxwPlxuICAgMVxuICA8L3A+PHA+XG4gICAxXG4gIDwvcD48cD5cbiAgIDFcbiAgPC9wPjxwPlxuICAgMVxuICA8L3A+PHA+XG4gICAxXG4gIDwvcD48cD5cbiAgIDFcbiAgPC9wPjxwPlxuICAgMVxuICA8L3A+PHA+XG4gICAxXG4gIDwvcD5cbiA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgdi1tb2RlbD1cInN0YXRlXCJcbiAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaEFzeW5jXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.将远程搜索组件放到最底部
2.在输入框中输入v时，列表样式错乱

### What is Expected?

远程搜索结果列表样式不错乱

### What is actually happening?

远程搜索结果列表样式错乱

### Additional comments

select选择器的远程搜索也有同样的问题

![image](https://user-images.githubusercontent.com/68418891/182859698-0a90726d-dcda-4593-ad71-ea79ed073882.png)
![image](https://user-images.githubusercontent.com/68418891/182860134-1f3d9089-062b-4ad2-8079-c0905e36e617.png)

**Comment by QAQLiuCong** [comment]
我遇到了同样的问题
