### ISSUE TITLE
[Component] [All] 输入框多次聚焦后，边缘会出现阴影点

### ISSUE THREAD

**Issue by sww-test** [element-plus/element-plus#9212]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Google Chrome 99.0.4844.51`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

多次聚焦输入框

### What is Expected?

正常显示

### What is actually happening?

边缘出现阴影点

### Additional comments

_(empty)_

**Comment by buqiyuan** [comment]
hi！可以截图看一下具体的异常表现吗？我试着没发现有什么异样🤔
