### ISSUE TITLE
[Style] 在按需导入配置下 与提示消息相关的组件都不好用  ElMessage   ElNotification   ElMessageBox 样式丢失

### ISSUE THREAD

**Issue by Lovecxgood** [element-plus/element-plus#9214]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-notification`
- `el-message-box`

### Reproduction Link

[Docs CN]( https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)

### Steps to reproduce

```
ElMessage.success("提示")
ElNotification({
    title: 'Title',
    message: h('i', { style: 'color: teal' }, 'This is a reminder'),
 })
ElMessageBox.confirm()
```

### What is Expected?

正常

### What is actually happening?

不正常  样式丢失  应该是相应的css没有自动导入所致  其他组件正常 消息提示组件样式都不正常

### Additional comments

大多数问题都是出现在自动导入vite的自动导入配置下 应该还有一些问题待发现。。。

**Comment by Lovecxgood** [comment]
全部引用配置下 是正常的  按需引用消息提示组件样式丢失

**Comment by btea** [comment]
https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

**Comment by Lovecxgood** [comment]
> https://element-plus.org/zh-CN/guide/quickstart.html#%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5

是按着你们的文档配置的  其他组件都好用 就是消息提示组件都不好使  弹出后没有样式 切出现在页面最下方  我用的是sass  
vite里的配置如下  和你们官网给的多了些配置  不加 importStyle: 'sass', 所有样式都不好使  加了只有消息提示组件不好使
  ElementPlusResolver({ importStyle: 'sass', exclude: /^ElAmap|ElBmap|ElBmapv[A-Z]*!/ }),

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/183252871-dbe43168-188e-4c1e-a8f3-f63c2b530de1.png)

**Comment by Lovecxgood** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/183252871-dbe43168-188e-4c1e-a8f3-f63c2b530de1.png)

呃 好吧 我到时试试  谢谢
另一个问题  在按需导入下  switch的style 属性 没有作用   最新版的
<el-switch v-model="value"
	style="--el-switch-on-color: #13ce66; --el-switch-off-color: #ff4949"
	active-text="A" inactive-text="B" />

**Comment by Lovecxgood** [comment]
> ![image](https://user-images.githubusercontent.com/24516654/183252871-dbe43168-188e-4c1e-a8f3-f63c2b530de1.png)

看了下配置  并没有使用unplugin-element-plus这个插件  使用的只有 unplugin-vue-components 和 unplugin-auto-import这两个插件
```
import vue from '@vitejs/plugin-vue'
import { defineConfig, loadEnv } from 'vite'
import autoprefixer from 'autoprefixer'
import viteCompression from 'vite-plugin-compression'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
// import ElementPlus from 'unplugin-element-plus/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
```
之前使用过 后来给注释掉了  是按着 按需自动导入 配置的  不是 手动导入 那里的配置

**Comment by holazz** [comment]
`unplugin-element-plus` 插件也要使用，这个是自动导入样式的，[文档](https://github.com/element-plus/unplugin-element-plus#usage)
但是只使用组件 API 的话还是需要手动引入样式，比如 ElMessage, ElNotification

**Comment by Lovecxgood** [comment]
> `unplugin-element-plus` 插件也要使用，这个是自动导入样式的，[文档](https://github.com/element-plus/unplugin-element-plus#usage) 但是只使用组件 API 的话还是需要手动引入样式，比如 ElMessage, ElNotification

嗯 手动导入了这些api组件样式现在好使了 
还有最新版本下  el-switch 的style属性没有效果

**Comment by holazz** [comment]
> 还有最新版本下 el-switch 的style属性没有效果

我测试没有问题。
