### ISSUE TITLE
[Component] [table] el-table组件 多级表头fix属性 没有被固定住

### ISSUE THREAD

**Issue by a563346904** [element-plus/element-plus#9216]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/a563346904/pen/QWmrwbm)

### Steps to reproduce

```html
<html>

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <script src="https://unpkg.com/vue@next"></script>
  <!-- import CSS -->
  <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
  <!-- import JavaScript -->
  <script src="https://unpkg.com/element-plus"></script>
  <title>Element Plus demo</title>
</head>

<body>
  <div id="app">
    <el-table :data="tableData" height="500px" style="width: 800px">
      <el-table-column label="a" prop="a" key="a" fixed></el-table-column>
      <el-table-column label="bbb" prop="b" key="b" width="300" fixed="left">
        <el-table-column label="123" prop="d" width="200"></el-table-column>
        <el-table-column label="qwe" prop="d" width="200"></el-table-column>
      </el-table-column>
      <el-table-column label="cccc" prop="c" key="c" min-width="400"></el-table-column>
      <el-table-column label="ddddd" prop="d" key="d" width="200" fixed="right"></el-table-column>
    </el-table>
  </div>
  <script>
    const App = {
      data() {
        return {
          message: "Hello Element Plus",
          tableData: new Array(1).fill({ a: 1, b: 2, c: 3, d: 4 })
        };
      },
    };
    const app = Vue.createApp(App);
    app.use(ElementPlus);
    app.mount("#app");
  </script>
</body>

</html>
```

### What is Expected?

多级fixed的表头固定

### What is actually happening?

多级fixed的表头没有固定

### Additional comments

_(empty)_

**Comment by ming2882** [comment]
<template>
  <el-table :data="tableData" style="width:500px">
    <el-table-column prop="date" label="Date" width="150" fixed />
    <el-table-column label="Delivery Info" fixed>
      <el-table-column prop="name" label="Name" width="120" />
    </el-table-column>
    <el-table-column label="Address Info">
      <el-table-column prop="state" label="State" width="120" />
      <el-table-column prop="city" label="City" width="120" />
      <el-table-column prop="address" label="Address" />
      <el-table-column prop="zip" label="Zip" width="120" />
    </el-table-column>
  </el-table>
</template>

<script lang="ts" setup>
const tableData = [
  {
    date: '2016-05-03',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-02',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-04',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-01',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-08',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-06',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
  {
    date: '2016-05-07',
    name: 'Tom',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    zip: 'CA 90036',
  },
]
</script>

**Comment by ming2882** [comment]
改的对不对不知道，达到了些效果，修改table-body/styles-helper.ts
const fixedStyle = column.isSubColumn
      ? null
      : getFixedColumnOffset(columnIndex, props?.fixed, props.store)
改const fixedStyle = getFixedColumnOffset(columnIndex, props?.fixed, props.store)
const fixedClasses = column.isSubColumn
      ? []
      : getFixedColumnsClass(ns.b(), columnIndex, props?.fixed, props.store)
改const fixedClasses = getFixedColumnsClass(ns.b(), columnIndex, props?.fixed, props.store)
再修改table-header/style.helper.ts，修改方法和上面一样，去掉 column.isSubColumn的判断
