### ISSUE TITLE
[Build] [time-picker] build时出现dayjs引入错误

### ISSUE THREAD

**Issue by xiaofuyesnew** [element-plus/element-plus#9218]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/103.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Github Repo](https://github.com/boretech/admin)

### Steps to reproduce

pnpm build

### What is Expected?

正常build

### What is actually happening?

build 报错
 ERROR  'default' is not exported by node_modules/dayjs/dayjs.min.js, imported by node_modules/element-plus/es/components/time-picker/src/utils.mjs                                                 

file: D:/panna_project/admin/node_modules/element-plus/es/components/time-picker/src/utils.mjs:1:7
1: import dayjs from 'dayjs';
          ^
2: import '../../../utils/index.mjs';
3: import { isDate, isArray } from '@vue/shared';

### Additional comments

提交的最小复现环境链接为遇到问题的项目链接，尝试进行最小化复现的链接为以下链接，却是正常的，无法确定到底是什么引发了问题。
https://github.com/xiaofuyesnew/bugs/tree/main/element-plus/dayjs-bug

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/183100889-3e86dd93-ebf3-43f0-b53f-17849ef504e7.png)
编译通过哦，你可以尝试删除重新安装依赖。

**Comment by xiaofuyesnew** [comment]
> ![image](https://user-images.githubusercontent.com/23251408/183100889-3e86dd93-ebf3-43f0-b53f-17849ef504e7.png) 编译通过哦，你可以尝试删除重新安装依赖。

最下面的链接是正常的，但是出现问题是在正式的项目中，我更新dayjs的版本到2.0.0-alpha.2，正式项目打包又是正常的，但是多打包几次就又会出现报错。

```
'default' is not exported by node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/dayjs.min.js, imported by node_modules/.pnpm/element-plus@2.2.12_vue@3.2.37/node_modules/element-plus/es/components/time-picker/src/utils.mjs
file: D:/bore_project/admin/node_modules/.pnpm/element-plus@2.2.12_vue@3.2.37/node_modules/element-plus/es/components/time-picker/src/utils.mjs:1:7
1: import dayjs from 'dayjs';
                 ^
2: import '../../../utils/index.mjs';
3: import { isDate, isArray } from '@vue/shared';
```

报错中的提示，dayjs的版本与依赖实际安装的版本又不一致，当前可以大致确定是dayjs的问题，因为默认的dayjs.min.js中没有esm的default，去该仓库看了PR，其中有相关修复，但未合并，应该在合并后发布的正式版本可以修复这个问题。

**Comment by xiaofuyesnew** [comment]
暂时解决了，如果你用`vite`和`pnpm`，并且用`js`作为开发语言的话：
在`vite.config.js`中，需要这么配置：
```js
{
    ...
    build: {
      commonjsOptions: {
        include: [
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/dayjs.min.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/customParseFormat.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/localeData.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/advancedFormat.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/weekOfYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/weekYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/dayOfYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/isSameOrAfter.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/isSameOrBefore.js',
          'node_modules/.pnpm/escape-html@1.0.3/node_modules/escape-html/index.js'
        ]
      }
    }
  }
```
