### ISSUE TITLE
The border of el-Table is abnormal with display:flex

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#922]
# Element-Plus version
 "element-plus": "^1.0.1-beta.5"

# OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

# Steps to reproduce
1.body style:height:100vh;width:100vw;
2. #app style:display:flex; height:100%;width:100%;
3.question1: Dont't set border for el-table
3.question2: Set border for el-table

# What is Expected?
##  question2: el-table border is suitable

# What is actually happening?
question1: It shows the bottom border
question2: The border exceeds the table length

Zip is an example
[11.zip](https://github.com/element-plus/element-plus/files/5664670/11.zip)
```
cd ./11
npx http-server
```

**Comment by JeremyWuuuuu** [comment]
This is nice that you can provide detailed information like this, we will start to investigate, thank you!

**Comment by XingXiaoWu** [comment]
![image](https://user-images.githubusercontent.com/22769131/101608459-b2fa5400-3a40-11eb-8b65-fe0cb6f12075.png)
![image](https://user-images.githubusercontent.com/22769131/101608551-ce655f00-3a40-11eb-9675-81319c3a8903.png)
