### ISSUE TITLE
[Component] [tooltip, button, input] 使用插槽显示更多 content 时，触发控件消失，插槽内容常显

### ISSUE THREAD

**Issue by Hellager** [element-plus/element-plus#9232]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 104.0.5112.80`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`
- `el-input`
- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxlbC10b29sdGlwIGNvbnRlbnQ9XCJub3JtYWxcIiBwbGFjZW1lbnQ9XCJyaWdodFwiIGVmZmVjdD1cImxpZ2h0XCI+XG4gIDxlbC1idXR0b24+TGlnaHQ8L2VsLWJ1dHRvbj5cbjwvZWwtdG9vbHRpcD4gIFxuICBcbiAgPGVsLXRvb2x0aXAgcGxhY2VtZW50PVwidG9wXCI+XG4gICAgPGRpdiBzbG90PVwiY29udGVudFwiPuWkmuihjOS/oeaBrzxici8+56ys5LqM6KGM5L+h5oGvPC9kaXY+XG4gICAgPGVsLWJ1dHRvbj5Ub3AgY2VudGVyPC9lbC1idXR0b24+XG4gIDwvZWwtdG9vbHRpcD5cblxuIDxlbC10b29sdGlwIHBsYWNlbWVudD1cImJvdHRvbVwiIFx0ZWZmZWN0PVwibGlnaHRcIj5cbiAgICA8ZGl2IHNsb3Q9XCJjb250ZW50XCI+XG4gICAgIFx0e3sgdG9vbHRpcHMgfX1cbiAgICA8L2Rpdj5cblx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAxLCBtYXhSb3dzOiAzIH1cIiB0eXBlPVwidGV4dGFyZWFcIi8+XG48L2VsLXRvb2x0aXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpO1xuICBcbmNvbnN0IHRvb2x0aXBzID0gcmVmKCfnrKzkuIDooYwgXFxuIOesrOS6jOihjCBcXG4nKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

直接使用文档案例 [更多 Content](https://element.eleme.cn/2.3/#/zh-CN/component/tooltip#geng-duo-content) 并查看其在线运行，发现均未实现预期效果

### What is Expected?

未被插槽包裹组件应正常显示，
插槽内容应该事件触发后显示

### What is actually happening?

未被插槽包裹组件不显示，
插槽内容常显

### Additional comments

_(empty)_

**Comment by makedopamine** [comment]
Why you use `slot` syntax of `vue2`?  Check this out. [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxlbC10b29sdGlwIGNvbnRlbnQ9XCJub3JtYWxcIiBwbGFjZW1lbnQ9XCJyaWdodFwiIGVmZmVjdD1cImxpZ2h0XCI+XG4gIDxlbC1idXR0b24+TGlnaHQ8L2VsLWJ1dHRvbj5cbjwvZWwtdG9vbHRpcD4gIFxuICBcbiAgPGVsLXRvb2x0aXAgcGxhY2VtZW50PVwiYm90dG9tXCI+XG4gICAgPHRlbXBsYXRlICNjb250ZW50PjxkaXY+5aSa6KGM5L+h5oGvPGJyLz7nrKzkuozooYzkv6Hmga88L2Rpdj48L3RlbXBsYXRlPlxuICAgIDxlbC1idXR0b24+VG9wIGNlbnRlcjwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+XG5cbiA8ZWwtdG9vbHRpcCBwbGFjZW1lbnQ9XCJib3R0b21cIiBcdGVmZmVjdD1cImxpZ2h0XCI+XG4gICAgPHRlbXBsYXRlICNjb250ZW50PlxuICAgICBcdHt7IHRvb2x0aXBzIH19XG4gICAgPC90ZW1wbGF0ZT5cblx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAxLCBtYXhSb3dzOiAzIH1cIiB0eXBlPVwidGV4dGFyZWFcIi8+XG48L2VsLXRvb2x0aXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpO1xuICBcbmNvbnN0IHRvb2x0aXBzID0gcmVmKCfnrKzkuIDooYwgXFxuIOesrOS6jOihjCBcXG4nKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by Hellager** [comment]
> Why you use `slot` syntax of `vue2`? Check this out. [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuIDxlbC10b29sdGlwIGNvbnRlbnQ9XCJub3JtYWxcIiBwbGFjZW1lbnQ9XCJyaWdodFwiIGVmZmVjdD1cImxpZ2h0XCI+XG4gIDxlbC1idXR0b24+TGlnaHQ8L2VsLWJ1dHRvbj5cbjwvZWwtdG9vbHRpcD4gIFxuICBcbiAgPGVsLXRvb2x0aXAgcGxhY2VtZW50PVwiYm90dG9tXCI+XG4gICAgPHRlbXBsYXRlICNjb250ZW50PjxkaXY+5aSa6KGM5L+h5oGvPGJyLz7nrKzkuozooYzkv6Hmga88L2Rpdj48L3RlbXBsYXRlPlxuICAgIDxlbC1idXR0b24+VG9wIGNlbnRlcjwvZWwtYnV0dG9uPlxuICA8L2VsLXRvb2x0aXA+XG5cbiA8ZWwtdG9vbHRpcCBwbGFjZW1lbnQ9XCJib3R0b21cIiBcdGVmZmVjdD1cImxpZ2h0XCI+XG4gICAgPHRlbXBsYXRlICNjb250ZW50PlxuICAgICBcdHt7IHRvb2x0aXBzIH19XG4gICAgPC90ZW1wbGF0ZT5cblx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAxLCBtYXhSb3dzOiAzIH1cIiB0eXBlPVwidGV4dGFyZWFcIi8+XG48L2VsLXRvb2x0aXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpO1xuICBcbmNvbnN0IHRvb2x0aXBzID0gcmVmKCfnrKzkuIDooYwgXFxuIOesrOS6jOihjCBcXG4nKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

Sorry for missing the slot usage different in vue 3, Greate Thanks for your help
