### ISSUE TITLE
[Docs] 官网资源请求不到

### ISSUE THREAD

**Issue by mageAoe** [element-plus/element-plus#9236]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-badge`
- `el-form`
- `el-slider`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/badge.html)

### Steps to reproduce

点击链接查看

### What is Expected?

使用能够正常

### What is actually happening?

解决

### Additional comments

_(empty)_

**Comment by wjw-gavin** [comment]
https://github.com/element-plus/element-plus/issues/9196
