### ISSUE TITLE
[Component] el-form-item 的校验信息，会影响到内部的 el-pagination

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#9238]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`
- `el-pagination`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cInJ1bGVGb3JtUmVmXCJcbiAgICA6bW9kZWw9XCJydWxlRm9ybVwiXG4gICAgOnJ1bGVzPVwicnVsZXNcIlxuICAgIGxhYmVsLXdpZHRoPVwiMTIwcHhcIlxuICAgIGNsYXNzPVwiZGVtby1ydWxlRm9ybVwiXG4gICAgOnNpemU9XCJmb3JtU2l6ZVwiXG4gICAgc3RhdHVzLWljb25cbiAgPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSBuYW1lXCIgcHJvcD1cIm5hbWVcIj5cbiAgICAgXHQ8ZGl2IGNsYXNzPVwiYWN0aXZpdHktbmFtZVwiPlxuICAgICAgICA8ZWwtaW5wdXQgc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDIwcHg7XCIgdi1tb2RlbD1cInJ1bGVGb3JtLm5hbWVcIiAvPlxuICAgICAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nLm9wZW5cIj7pgInmi6k8L2VsLWJ1dHRvbj5cbiAgICAgIFxuICAgICAgICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2cuc2hvd1wiPlxuICAgICAgICAgIDxlbC1wYWdpbmF0aW9uXG4gICAgICAgICAgICB2LW1vZGVsOmN1cnJlbnRQYWdlPVwiY3VycmVudFBhZ2VcIlxuICAgICAgICAgICAgdi1tb2RlbDpwYWdlLXNpemU9XCJwYWdlU2l6ZVwiXG4gICAgICAgICAgICA6cGFnZS1zaXplcz1cIlsxMDAsIDIwMCwgMzAwLCA0MDBdXCJcbiAgICAgICAgICAgIGxheW91dD1cInRvdGFsLCBzaXplcywgcHJldiwgcGFnZXIsIG5leHQsIGp1bXBlclwiXG4gICAgICAgICAgICA6dG90YWw9XCI0MDBcIlxuICAgICAgICAgICAvPlxuICAgICAgICA8L2VsLWRpYWxvZz5cbiAgICAgIDwvZGl2PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybShydWxlRm9ybVJlZilcIj7mj5DkuqQ8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVzZXRGb3JtKHJ1bGVGb3JtUmVmKVwiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlLCBGb3JtUnVsZXMgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZvcm1TaXplID0gcmVmKCdkZWZhdWx0JylcbmNvbnN0IHJ1bGVGb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgcnVsZUZvcm0gPSByZWFjdGl2ZSh7XG4gIG5hbWU6ICcnXG59KVxuXG5jb25zdCBydWxlcyA9IHJlYWN0aXZlPEZvcm1SdWxlcz4oe1xuICBuYW1lOiBbXG4gICAgeyByZXF1aXJlZDogdHJ1ZSwgbWVzc2FnZTogJ1BsZWFzZSBpbnB1dCBBY3Rpdml0eSBuYW1lJywgdHJpZ2dlcjogJ2JsdXInIH0sXG4gICAgeyBtaW46IDMsIG1heDogNSwgbWVzc2FnZTogJ0xlbmd0aCBzaG91bGQgYmUgMyB0byA1JywgdHJpZ2dlcjogJ2JsdXInIH0sXG4gIF1cbn0pXG5cbmNvbnN0IHN1Ym1pdEZvcm0gPSBhc3luYyAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBhd2FpdCBmb3JtRWwudmFsaWRhdGUoKHZhbGlkLCBmaWVsZHMpID0+IHtcbiAgICBpZiAodmFsaWQpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdzdWJtaXQhJylcbiAgICB9IGVsc2Uge1xuICAgICAgY29uc29sZS5sb2coJ2Vycm9yIHN1Ym1pdCEnLCBmaWVsZHMpXG4gICAgfVxuICB9KVxufVxuXG5jb25zdCByZXNldEZvcm0gPSAoZm9ybUVsOiBGb3JtSW5zdGFuY2UgfCB1bmRlZmluZWQpID0+IHtcbiAgaWYgKCFmb3JtRWwpIHJldHVyblxuICBmb3JtRWwucmVzZXRGaWVsZHMoKVxufVxuXG5jb25zdCBjdXJyZW50UGFnZSA9IHJlZigxKVxuY29uc3QgcGFnZVNpemUgPSByZWYoMTAwKVxuXG5jb25zdCBkaWFsb2cgPSByZWFjdGl2ZSh7XG4gIHNob3c6IGZhbHNlLFxuICBvcGVuOiAoKSA9PiB7XG4gICAgZGlhbG9nLnNob3cgPSB0cnVlXG4gIH0sXG4gIGNsb3NlOiAoKSA9PiB7XG4gICAgZGlhbG9nLnNob3cgPSBmYWxzZVxuICB9XG59KVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4gIC5hY3Rpdml0eS1uYW1lIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICB9XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击 “提交” 按钮，触发表单校验，显示错误信息
2. 点击 “选择” 按钮，打开 el-dialog，可以看到 el-pagination 内部的表单元素也被校验
3. demo 内 el-dialog 是写在 el-form-item 内部的，因为很多时候，div.activity-name 是一个独立的组件，通过 slot 插入到 el-form-item 内部使用
4. 如果 el-dialog 内是其他表单元素，也会受外部表单校验的影响，但是可以通过设置 :validate-event="false" 来解决，el-pagination 就没有办法了
5. el-pagination 内部的表单元素是否也需要设置 :validate-event="false" 来避免这种情况？

### What is Expected?

el-pagination 内部的表单元素不受外部表单的校验影响

### What is actually happening?

el-pagination内部的表单元素受外部表单的校验影响

### Additional comments

_(empty)_

**Comment by wjw-gavin** [comment]
```js
<el-dialog v-model="dialog.show" append-to-body>
  <el-pagination
    v-model:currentPage="currentPage"
    v-model:page-size="pageSize"
    :page-sizes="[100, 200, 300, 400]"
    layout="total, sizes, prev, pager, next, jumper"
    :total="400"
   />
</el-dialog>
```

添加 `append-to-body` 可以解决你的问题
原因是 `.el-form-item.is-error` 会造成里面包含的el-input都会变成表单校验后的样式，`append-to-body`会把元素插入到body，不在`el-form-item`内就可以避免了。

**Comment by JackieCheung** [comment]
> ```js
> <el-dialog v-model="dialog.show" append-to-body>
>   <el-pagination
>     v-model:currentPage="currentPage"
>     v-model:page-size="pageSize"
>     :page-sizes="[100, 200, 300, 400]"
>     layout="total, sizes, prev, pager, next, jumper"
>     :total="400"
>    />
> </el-dialog>
> ```
> 
> 添加 `append-to-body` 可以解决你的问题 原因是 `.el-form-item.is-error` 会造成里面包含的el-input都会变成表单校验后的样式，`append-to-body`会把元素插入到body，不在`el-form-item`内就可以避免了。
> 
> Translated by deepl: Adding append-to-body solves your problem The reason for this is that .el-form-item.is-error causes all the el-inputs contained inside to become form-checked. append-to-body will insert the element into the body, not inside the el-form-item, to avoid this.

试过了 还是会有影响的
![image](https://user-images.githubusercontent.com/31252046/183405950-3577f9f4-faa9-400e-9061-20d912e375aa.png)

**Comment by wjw-gavin** [comment]
> > ```js
> > <el-dialog v-model="dialog.show" append-to-body>
> >   <el-pagination
> >     v-model:currentPage="currentPage"
> >     v-model:page-size="pageSize"
> >     :page-sizes="[100, 200, 300, 400]"
> >     layout="total, sizes, prev, pager, next, jumper"
> >     :total="400"
> >    />
> > </el-dialog>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 添加 `append-to-body` 可以解决你的问题 原因是 `.el-form-item.is-error` 会造成里面包含的el-input都会变成表单校验后的样式，`append-to-body`会把元素插入到body，不在`el-form-item`内就可以避免了。
> > Translated by deepl: Adding append-to-body solves your problem The reason for this is that .el-form-item.is-error causes all the el-inputs contained inside to become form-checked. append-to-body will insert the element into the body, not inside the el-form-item, to avoid this.
> 
> 试过了 还是会有影响的 ![image](https://user-images.githubusercontent.com/31252046/183405950-3577f9f4-faa9-400e-9061-20d912e375aa.png)

啊。。。这个我没注意到，光注意红色了 LOL

**Comment by JackieCheung** [comment]
> ```js
> ```js
> <el-dialog v-model="dialog.show" append-to-body>
>   <el-pagination
>     v-model:currentPage="currentPage"
>     v-model:page-size="pageSize"
>     :page-sizes="[100, 200, 300, 400]"
>     layout="total, sizes, prev, pager, next, jumper"
>     :total="400"
>    />
> </el-dialog>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 添加 append-to-body 可以解决你的问题 原因是 .el-form-item.is-error 会造成里面包含的el-input都会变成表单校验后的样式，append-to-body会把元素插入到body，不在el-form-item内就可以避免了。
> Translated by deepl: Adding append-to-body solves your problem The reason for this is that .el-form-item.is-error causes all the el-inputs contained inside to become form-checked. append-to-body will insert the element into the body, not inside the el-form-item, to avoid this.
> 
> 试过了 还是会有影响的 
> 
> 啊。。。这个我没注意到，光注意红色了 LOL，css 给隐藏一下呢
> ```

可以通过css样式处理，或者给el- pagination外面套一个el-form-item，设置prop为''，但是感觉搞得很复杂了呢
