### ISSUE TITLE
[Component] [scrollbar] min-size 设置滚动条最小尺寸 不起作用

### ISSUE THREAD

**Issue by TheFreeOne** [element-plus/element-plus#9239]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 102.0.5005.63 / Windows 10 64位`
- Build Tool: `Webpack`

### Related Component

- `el-scrollbar`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2Nyb2xsYmFyIGhlaWdodD1cIjQwMHB4XCIgOm1pblNpemU9XCIzNjBcIiA6bWluLXNpemU9XCIzNjBcIj5cbiAgICA8cCB2LWZvcj1cIml0ZW0gaW4gMjBcIiA6a2V5PVwiaXRlbVwiIGNsYXNzPVwic2Nyb2xsYmFyLWRlbW8taXRlbVwiPnt7IGl0ZW0gfX08L3A+XG4gIDwvZWwtc2Nyb2xsYmFyPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZD5cbi5zY3JvbGxiYXItZGVtby1pdGVtIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIGhlaWdodDogNTBweDtcbiAgbWFyZ2luOiAxMHB4O1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIGJvcmRlci1yYWRpdXM6IDRweDtcbiAgYmFja2dyb3VuZDogdmFyKC0tZWwtY29sb3ItcHJpbWFyeS1saWdodC05KTtcbiAgY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

设置:min-size="360"

### What is Expected?

滑块变宽

### What is actually happening?

无变化

### Additional comments

_(empty)_

**Comment by freedomlang** [comment]
`min-size` represent the min height of vertical scroll bar or the min width of horizontal scroll bar
