### ISSUE TITLE
[Component] [upload] el-upload设置limit限制最大上传文件数量失效

### ISSUE THREAD

**Issue by sywdebug** [element-plus/element-plus#9243]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/upload.html#%E8%A6%86%E7%9B%96%E5%89%8D%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6)

### Steps to reproduce

el-upload组件，设置limit限制最大上传数量为1，覆盖前一个上传的文件，失效，官网el-upload组件覆盖前一个文件实例也是失效的

### What is Expected?

恢复正常使用

### What is actually happening?

覆盖前一个文件失效

### Additional comments

用着看自己写的没问题，然后看与官网的区别，发现官网就失效的

![image](https://user-images.githubusercontent.com/71065669/183421171-5c402cda-f858-4e7d-9bd6-da79c0995930.png)

**Comment by makedopamine** [comment]
duplicated with [#9067](https://github.com/element-plus/element-plus/issues/9067) and  [#9170](https://github.com/element-plus/element-plus/issues/9170)

**Comment by TLovers** [comment]
我设置show-file-list="false" 和后段商量每次我上传后，他update 覆盖之前我上传的，看起来貌似没啥问题，但是打包后就gg了，build后到服务器上就无法再次触发出发上传

**Comment by TLovers** [comment]
> 我设置show-file-list="false" 和后段商量每次我上传后，他update 覆盖之前我上传的，看起来貌似没啥问题，但是打包后就gg了，build后到服务器上 上传一次后就无法再次触发出发上传

我们项目是jsx风格的，刚刚换成.vue的写法就好了，慌得不行

**Comment by zydding** [comment]
> > 我设置show-file-list="false" 和后段商量每次我上传后，他update 覆盖之前我上传的，看起来貌似没啥问题，但是打包后就gg了，build后到服务器上 上传一次后就无法再次触发出发上传
> 
> 我们项目是jsx风格的，刚刚换成.vue的写法就好了，慌得不行



> 我设置show-file-list="false" 和后段商量每次我上传后，他update 覆盖之前我上传的，看起来貌似没啥问题，但是打包后就gg了，build后到服务器上 上传一次后就无法再次触发出发上传

看出来你很慌，官方都是支持自定义上传的吧，你自己写一个现实上传文件的view不就行了，代码实现增删文件。

**Comment by sywdebug** [comment]
> duplicated with [#9067](https://github.com/element-plus/element-plus/issues/9067) and [#9170](https://github.com/element-plus/element-plus/issues/9170)

成功解决，非常感谢

**Comment by weiheli** [comment]
> > duplicated with [#9067](https://github.com/element-plus/element-plus/issues/9067) and [#9170](https://github.com/element-plus/element-plus/issues/9170)
> 
> 成功解决，非常感谢

怎么解决的，我升级到 2.2.13 并没有生效

**Comment by sywdebug** [comment]
> > > duplicated with [#9067](https://github.com/element-plus/element-plus/issues/9067) and [#9170](https://github.com/element-plus/element-plus/issues/9170)
> > 
> > 
> > 成功解决，非常感谢
> 
> 怎么解决的，我升级到 2.2.13 并没有生效

就是增加了一个v-model:file-list=""绑定一下，官网也有写这个属性，只是我之前没加也有效，现在是必须加了才有效，另外直接使用:file-list没用，必须加上v-model

**Comment by btea** [comment]
fixed #9145
