### ISSUE TITLE
[Component] [select] Dropdown selection (with config "multiple" & "filterable") disrupts interactions since v2.2.1

### ISSUE THREAD

**Issue by cdeng** [element-plus/element-plus#9244]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome/104.0.0.0 / Mac OS X 10.15.7`
- Build Tool: `Rollup`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBjbGVhcmFibGVcbiAgICBtdWx0aXBsZVxuICAgIGZpbHRlcmFibGVcbiAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgOnJlc2VydmUta2V5d29yZD1cImZhbHNlXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. Enter "o" in the search field
2. Click "Option1"
3. Click the white space in the search field
4. Enter "o" in the search field

### What is Expected?

The dropdown is expected to remain opening, and provide suggestions based on the latest input.

### What is actually happening?

The dropdown is dismissed as soon as step 3 in the reproduce steps above, and no longer displays unless user clicks elsewhere outside of search field.

### Additional comments

Here is a screenshot took from the playground attached above.

![Aug-08-2022 16-06-25](https://user-images.githubusercontent.com/4248581/183529569-b418f104-ed6d-44f8-9d92-22cbaf7a7f7c.gif)

I played around with different versions and the issue seems being introduced in v2.2.1. **Other versions prior to v2.2.1 (e.g. v2.2.0) are working as expected.**

**Comment by tolking** [comment]
Fixed in #9941
