### ISSUE TITLE
[Component] [message] The v-loading directive exists. JS reports an error when calling the message box using elmessage

### ISSUE THREAD

**Issue by ureytom** [element-plus/element-plus#9245]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.11`
- Browser / OS: `Edg/104.0.1293.47 / Windows 10 Pro 21H2`
- Build Tool: `Vue CLI`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gLEVsTWVzc2FnZX0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmV4cG9ydCBkZWZhdWx0IHtcbiAgc2V0dXAocHJvcHMse2VtaXR9KXtcbiAgICBjb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG4gICAgY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSk7XG4gICAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZTtcbiAgICAgIHNldFRpbWVvdXQoKCk9PntcbiAgICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlO1xuICAgICAgICBFbE1lc3NhZ2Uoe1xuICAgICAgICAgIG1lc3NhZ2U6J+WNoeaXtumXtOauteWNoeaXtumXtOauteWNoeS4ieetieWllicsXG4gICAgICAgICAgdHlwZTonc3VjY2VzcydcbiAgICAgICAgfSlcbiAgICAgIH0sMTAwMClcbiAgICByZXR1cm4ge1xuICAgICAgbXNnLFxuICAgICAgbG9hZGluZ1xuICAgIH1cbiAgfVxufVxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgdi1sb2FkaW5nLmZ1bGxzY3JlZW4ubG9jaz1cImxvYWRpbmdcIj5cbiAgICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gICAgPHA+XG4gICAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gICAgPC9wPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script>
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion ,ElMessage} from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
export default {
  setup(props,{emit}){
    const msg = ref('Hello World!')
    const loading = ref(false);
      loading.value = true;
      setTimeout(()=>{
        loading.value = false;
        ElMessage({
          message:'卡时间段卡时间段卡三等奖',
          type:'success'
        })
      },1000)
    return {
      msg,
      loading
    }
  }
}
  
</script>

<template>
  <div v-loading.fullscreen.lock="loading">
    <h1>{{ msg }}</h1>
    <el-input v-model="msg" />
    <p>
      <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
      Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
    </p>
  </div>
</template>
```

### What is Expected?

The message box is displayed normally and closed after a period of time

### What is actually happening?

After the message box is displayed normally, a JS error is reported after closing, resulting in the subsequent code cannot be executed

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Unable to reproduce, please check your Reproduction Link.
