### ISSUE TITLE
[Component] [tooltip] el-tooltip设置了manual属性后，依然响应mouseenter 和 mouseleave

### ISSUE THREAD

**Issue by zydding** [element-plus/element-plus#9246]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 99.0.4844.51（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjYXBzVG9vbHRpcCA9IHJlZihmYWxzZSlcbmNvbnN0IHBhc3N3b3JkPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcFxuICAgICAgICAgICAgICAgICAgdi1tb2RlbDp2aXNpYmxlPVwiY2Fwc1Rvb2x0aXBcIlxuICAgICAgICAgICAgICAgICAgICBjb250ZW50PVwi5aSn5YaZ5bey5omT5byAXCJcbiAgICAgICAgICAgICAgICAgICAgcGxhY2VtZW50PVwiYm90dG9tXCJcbiAgICAgICAgICAgICAgICAgICAgOm1hbnVhbD1cInRydWVcIlxuICAgICAgICAgICAgICAgICAgPlxuICAgIDxlbC1pbnB1dCAgICAgICBcbiAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9XCLlr4bnoIHovpPlhaXmoYZcIlxuICAgICAgICAgICAgICAgICAgICB2LW1vZGVsPVwicGFzc3dvcmRcIlxuICAgICAgICAgICAgICAgICAgLz5cbiAgPC9lbC10b29sdGlwPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

鼠标移动到密码输入框，可以看到tooltip显示

### What is Expected?

可以手动控制tooltip的显示

### What is actually happening?

鼠标移动到输入框后，tooltip就显示

### Additional comments

_(empty)_

**Comment by btea** [comment]
你可以通过 `visible` 来控制 `tooltip` 是否显示，[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjYXBzVG9vbHRpcCA9IHJlZihmYWxzZSlcbmNvbnN0IHBhc3N3b3JkPSByZWYoJycpXG5jb25zdCBmb2N1cyA9ICgpID0+IHtcbiAgY2Fwc1Rvb2x0aXAudmFsdWUgPSB0cnVlXG59XG5jb25zdCBibHVyID0gKCkgPT4ge1xuICBjYXBzVG9vbHRpcC52YWx1ZSA9IGZhbHNlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcFxuICAgIDp2aXNpYmxlPVwiY2Fwc1Rvb2x0aXBcIlxuICAgIGNvbnRlbnQ9XCLlpKflhpnlt7LmiZPlvIBcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gID5cbiAgICA8ZWwtaW5wdXQgICAgICAgIFxuICAgICAgcGxhY2Vob2xkZXI9XCLlr4bnoIHovpPlhaXmoYZcIlxuICAgICAgdi1tb2RlbD1cInBhc3N3b3JkXCJcbiAgICAgXHRAZm9jdXM9XCJmb2N1c1wiXG4gICAgICBAYmx1cj1cImJsdXJcIlxuICAgIC8+XG4gIDwvZWwtdG9vbHRpcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by zydding** [comment]
> 你可以通过 `visible` 来控制 `tooltip` 是否显示，[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBjYXBzVG9vbHRpcCA9IHJlZihmYWxzZSlcbmNvbnN0IHBhc3N3b3JkPSByZWYoJycpXG5jb25zdCBmb2N1cyA9ICgpID0+IHtcbiAgY2Fwc1Rvb2x0aXAudmFsdWUgPSB0cnVlXG59XG5jb25zdCBibHVyID0gKCkgPT4ge1xuICBjYXBzVG9vbHRpcC52YWx1ZSA9IGZhbHNlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcFxuICAgIDp2aXNpYmxlPVwiY2Fwc1Rvb2x0aXBcIlxuICAgIGNvbnRlbnQ9XCLlpKflhpnlt7LmiZPlvIBcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gID5cbiAgICA8ZWwtaW5wdXQgICAgICAgIFxuICAgICAgcGxhY2Vob2xkZXI9XCLlr4bnoIHovpPlhaXmoYZcIlxuICAgICAgdi1tb2RlbD1cInBhc3N3b3JkXCJcbiAgICAgXHRAZm9jdXM9XCJmb2N1c1wiXG4gICAgICBAYmx1cj1cImJsdXJcIlxuICAgIC8+XG4gIDwvZWwtdG9vbHRpcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

恩，确实可以。
我看到官方文档内的写法有两种，我用了这种写法绑定visible是错误的
` v-model:visible=“capsTooltip”`
目前来看，必须用下面这种写法，保证mouseover的时候，不会自动设置capsTooltip=true
`:visible=“capsTooltip”`

**Comment by btea** [comment]
是的，在[这里](https://github.com/element-plus/element-plus/pull/8762)进行了调整。

**Comment by zydding** [comment]
> 是的，在[这里](https://github.com/element-plus/element-plus/pull/8762)进行了调整。

好的，谢谢
