### ISSUE TITLE
[Component] [select] Filterable Select v1 - lost focus of input after selecting an option

### ISSUE THREAD

**Issue by AxelConceicao** [element-plus/element-plus#9247]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 104.0.5112.81`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlbW92ZVRhYkluZGV4XCI+UmVtb3ZlIHRhYmluZGV4IHByb3BlcnR5PC9lbC1idXR0b24+XG4gIDxlbC1zZWxlY3RcbiAgICByZWY9XCJzZWxlY3RcIlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgY2xhc3M9XCJtLTJcIlxuICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICBzaXplPVwibGFyZ2VcIlxuICAgIGZpbHRlcmFibGVcbiAgICBtdWx0aXBsZVxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgIHBvcHBlci1jbGFzcz1cIm15cG9wcGVyXCJcbiAgPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxpbWcgOndpZHRoPVwiNjAwXCIgc3JjPVwiaHR0cHM6Ly9pLmltZ3VyLmNvbS9iTVVQSVdlLmdpZlwiPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCByZW1vdmVUYWJJbmRleCA9ICgpID0+IHtcbiAgZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZSgnbXlwb3BwZXInKVswXS5yZW1vdmVBdHRyaWJ1dGUoJ3RhYkluZGV4Jylcbn1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

- click on the select input
- type "1"
- click on Option1
- click on the select input (why the query is reset?)
- try to search "2" (nothing happen, the dropdown doesn't appears)
- click outside the select input
- click on the select input to make the dropdown appears again
(2 EXTRA CLICKS)

### What is Expected?

In my opinion we should be able to search again an option just after selecting/unselecting one without additionnal clicks.

### What is actually happening?

After selecting an option the select input focus is lost and if we click on the select input the query is reset.
After that we are stuck, we can write in the select input but nothing happen because the dropdown is closed.
To get the dropdown open again we have to click outside the select and click again on the select.

### Additional comments

This probleme is making my users crazy

On the playground I added a button to remove the tabindex="-1" property of the select popper.
You will see it's so much user-friendly without this property because you can select/unselect options and the select input will still be focused.
So you you can chain searches while selecting options without additional actions.

https://i.imgur.com/bMUPIWe.gif

**Comment by ravshan01** [comment]
Thank you at least for the proposed crutch.
Very helpful - spent half a day on it)

I reviewed the source codes of this component and everything seems to be fine there.

**Comment by tolking** [comment]
The issues seems to have been fixed, you can try the new version
