### ISSUE TITLE
[Component] [loading] Can't use element-plus icon with loading directive

### ISSUE THREAD

**Issue by jiaqidegege** [element-plus/element-plus#9251]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome/100.0.4896.127/ MacOS 10.15.7`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cywgTG9hZGluZyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCIgdi1sb2FkaW5nPVwidHJ1ZVwiIGVsZW1lbnQtbG9hZGluZy1zdmc9XCJlbC1pY29uLWxvYWRpbmdcIj5zc3M8L2Rpdj5cbiAgXG4gIDxkaXYgY2xhc3M9XCJib3hcIiB2LWxvYWRpbmc9XCJ0cnVlXCIgZWxlbWVudC1sb2FkaW5nLXN2Zz1cImxvYWRpbmdcIj5zc3M8L2Rpdj5cbiAgXG4gIDxkaXYgY2xhc3M9XCJib3hcIiB2LWxvYWRpbmc9XCJ0cnVlXCIgOmVsZW1lbnQtbG9hZGluZy1zdmc9XCJMb2FkaW5nXCI+c3NzPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4gIC5ib3gge1xuICAgIHdpZHRoOiAxMDBweDtcbiAgICBoZWlnaHQ6IDYwcHg7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

!

### What is Expected?

use configured icon as loading icon

### What is actually happening?

opposite

### Additional comments

_(empty)_

**Comment by zydding** [comment]
我真服了你了，官方给的例子也不是你这么写的
[看看这个](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IHN2ZyA9ICc8Y2lyY2xlIGNsYXNzPVwicGF0aFwiIGN4PVwiNTBcIiBjeT1cIjUwXCIgcj1cIjIwXCIgZmlsbD1cIm5vbmVcIj48L2NpcmNsZT4nXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCIgdi1sb2FkaW5nPVwidHJ1ZVwiIDplbGVtZW50LWxvYWRpbmctc3ZnPVwic3ZnXCI+c3NzPC9kaXY+XG4gIFxuICBcbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmJveCB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICAgIGhlaWdodDogNjBweDtcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by jiaqidegege** [comment]
看清楚，使用内置的图标， 像element一样，我都自己传svg标记，我要你这内置图标干啥

**Comment by zydding** [comment]
> > 我真服了你了，官方给的例子也不是你这么写的 [看看这个](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IHN2ZyA9ICc8Y2lyY2xlIGNsYXNzPVwicGF0aFwiIGN4PVwiNTBcIiBjeT1cIjUwXCIgcj1cIjIwXCIgZmlsbD1cIm5vbmVcIj48L2NpcmNsZT4nXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCIgdi1sb2FkaW5nPVwidHJ1ZVwiIDplbGVtZW50LWxvYWRpbmctc3ZnPVwic3ZnXCI+c3NzPC9kaXY+XG4gIFxuICBcbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmJveCB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICAgIGhlaWdodDogNjBweDtcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> 看清楚，使用内置的图标， 像element一样，我都自己传svg标记，我要你这内置图标干啥

人家给你的例子了， 你不用，你买特斯拉要求能飞是吧？

**Comment by jiaqidegege** [comment]
element有这个功能，没用过不要说话

**Comment by wjw-gavin** [comment]
```js
import { ElementPlus, Loading } from '@element-plus/icons-vue'
```
这里引入的是组件，使用方式是 `<Loading />`，你想用的应该是  [这里的源码吧](https://github.com/element-plus/element-plus-icons/tree/main/packages/svg)

**Comment by holazz** [comment]
这里只支持传入 svg，你可以使用这个包 `@element-plus/icons-svg`。或者在[这里](https://element-plus.gitee.io/en-US/component/icon.html#icon-collection)复制 svg 内容自己设置：

```vue
<script setup lang="ts">
import loading from '@element-plus/icons-svg/loading.svg?raw'

const svg = `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" data-v-78e17ca8=""><path fill="currentColor" d="M512 64a32 32 0 0 1 32 32v192a32 32 0 0 1-64 0V96a32 32 0 0 1 32-32zm0 640a32 32 0 0 1 32 32v192a32 32 0 1 1-64 0V736a32 32 0 0 1 32-32zm448-192a32 32 0 0 1-32 32H736a32 32 0 1 1 0-64h192a32 32 0 0 1 32 32zm-640 0a32 32 0 0 1-32 32H96a32 32 0 0 1 0-64h192a32 32 0 0 1 32 32zM195.2 195.2a32 32 0 0 1 45.248 0L376.32 331.008a32 32 0 0 1-45.248 45.248L195.2 240.448a32 32 0 0 1 0-45.248zm452.544 452.544a32 32 0 0 1 45.248 0L828.8 783.552a32 32 0 0 1-45.248 45.248L647.744 692.992a32 32 0 0 1 0-45.248zM828.8 195.264a32 32 0 0 1 0 45.184L692.992 376.32a32 32 0 0 1-45.248-45.248l135.808-135.808a32 32 0 0 1 45.248 0zm-452.544 452.48a32 32 0 0 1 0 45.248L240.448 828.8a32 32 0 0 1-45.248-45.248l135.808-135.808a32 32 0 0 1 45.248 0z"></path></svg>`
</script>

<template>
  <div v-loading="true" class="box" :element-loading-svg="loading">sss</div>

  <div v-loading="true" class="box" :element-loading-svg="svg">sss</div>
</template>
```

**Comment by jiaqidegege** [comment]
> 这里只支持传入 svg，你可以使用这个包 `@element-plus/icons-svg`。或者在[这里](https://element-plus.gitee.io/en-US/component/icon.html#icon-collection)复制 svg 内容自己设置：
> 
> ```
> <script setup lang="ts">
> import loading from '@element-plus/icons-svg/loading.svg?raw'
> 
> const svg = `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" data-v-78e17ca8=""><path fill="currentColor" d="M512 64a32 32 0 0 1 32 32v192a32 32 0 0 1-64 0V96a32 32 0 0 1 32-32zm0 640a32 32 0 0 1 32 32v192a32 32 0 1 1-64 0V736a32 32 0 0 1 32-32zm448-192a32 32 0 0 1-32 32H736a32 32 0 1 1 0-64h192a32 32 0 0 1 32 32zm-640 0a32 32 0 0 1-32 32H96a32 32 0 0 1 0-64h192a32 32 0 0 1 32 32zM195.2 195.2a32 32 0 0 1 45.248 0L376.32 331.008a32 32 0 0 1-45.248 45.248L195.2 240.448a32 32 0 0 1 0-45.248zm452.544 452.544a32 32 0 0 1 45.248 0L828.8 783.552a32 32 0 0 1-45.248 45.248L647.744 692.992a32 32 0 0 1 0-45.248zM828.8 195.264a32 32 0 0 1 0 45.184L692.992 376.32a32 32 0 0 1-45.248-45.248l135.808-135.808a32 32 0 0 1 45.248 0zm-452.544 452.48a32 32 0 0 1 0 45.248L240.448 828.8a32 32 0 0 1-45.248-45.248l135.808-135.808a32 32 0 0 1 45.248 0z"></path></svg>`
> </script>
> 
> <template>
>   <div v-loading="true" class="box" :element-loading-svg="loading">sss</div>
> 
>   <div v-loading="true" class="box" :element-loading-svg="svg">sss</div>
> </template>
> ```
首先这样很麻烦，希望能支持传入组件，这样就可以很方便的利用内置icon。
其次v-loading生成的占位已经用了svg包裹，所以你给的例子是不行的，需要去掉外层的svg标签

**Comment by holazz** [comment]
> 这样也行，但是同时引入icon 的svg 和 组件包， 会导致包体积增大吧，是否有可能支持传入组件
> 
> 

为什么要同时引入呢？现在不支持传入组件

**Comment by jiaqidegege** [comment]
为了用裸svg, 要引入@element-plus/icons-svg,  项目里有图标需求又要引入@element-plus/icons-vue

**Comment by wjw-gavin** [comment]
> 为了用裸svg, 要引入@element-plus/icons-svg, 项目里有图标需求又要引入@element-plus/icons-vue


我感觉一个系统应该少不了自己内部维护的svg吧，然后icons-svg里面的你应该也不是全部用到吧？你可以复制你需要的放到自己维护的里面。

**Comment by holazz** [comment]
> 为了用裸svg, 要引入@element-plus/icons-svg, 项目里有图标需求又要引入@element-plus/icons-vue

按需引入就好了，最后只会打包你用了的图标
