### ISSUE TITLE
[Component] [tree] tree 过滤后节点无法展开了

### ISSUE THREAD

**Issue by LipengNb** [element-plus/element-plus#9254]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tree.html#%E6%A0%91%E8%8A%82%E7%82%B9%E8%BF%87%E6%BB%A4)

### Steps to reproduce

看官方文档

### What is Expected?

过滤后可以展开节点

### What is actually happening?

过滤后无法展开节点

### Additional comments

官方文档过滤后都无法展开了

**Comment by zydding** [comment]
可以展开啊，输入过滤文字后，自动展开了

**Comment by LipengNb** [comment]
https://element-plus.org/zh-CN/component/tree.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E7%B1%BB%E5%90%8D

我的咋就无法展开呢。。。。element-plus 版本是2.2.12

**Comment by holazz** [comment]
升级 Element Plus 到最新版本
