### ISSUE TITLE
[Component] [upload] Upload - If you drag an drop more then 1 item (per time), it runs more then once :on-change

### ISSUE THREAD

**Issue by nhatimme** [element-plus/element-plus#9260]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome (newest)`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0ZXN0ID0gKGZpbGUsIGZpbGVzKSA9PiB7XG4gIGNvbnNvbGUubG9nKGZpbGVzKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXVwbG9hZFxuICAgIGNsYXNzPVwidXBsb2FkLWRlbW9cIlxuICAgIGRyYWdcbiAgICBhY3Rpb249XCJcIlxuICAgIDphdXRvLXVwbG9hZD1cImZhbHNlXCIgICAgICAgICBcbiAgICBtdWx0aXBsZVxuICAgIDpvbi1jaGFuZ2U9XCJ0ZXN0XCJcbiAgPlxuICAgIDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tdXBsb2FkXCI+PHVwbG9hZC1maWxsZWQgLz48L2VsLWljb24+XG4gICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGV4dFwiPlxuICAgICAgRHJvcCBmaWxlIGhlcmUgb3IgPGVtPmNsaWNrIHRvIHVwbG9hZDwvZW0+XG4gICAgPC9kaXY+XG4gICAgPHRlbXBsYXRlICN0aXA+XG4gICAgICA8ZGl2IGNsYXNzPVwiZWwtdXBsb2FkX190aXBcIj5cbiAgICAgICAganBnL3BuZyBmaWxlcyB3aXRoIGEgc2l6ZSBsZXNzIHRoYW4gNTAwa2JcbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdXBsb2FkPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Please check the function test which is been called x times when you drag and drop 2 items (as example).

### What is Expected?

Only 1 time the function should be called as its a drag drop of more items. From that point you got the FileList and you can work further.

### What is actually happening?

It is running the function x times, depends on the items which are in.

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
I don't think so. In a real example, the files will be uploaded one by one. So onChange should be called once each file is finished.

**Comment by nhatimme** [comment]
Please listen. Use my example and see what happens. Element Plus create the
issue.

Op zo 4 sep. 2022 01:29 schreef 三咲智子 ***@***.***>:
