### ISSUE TITLE
[Style] [tree-select] el-tree-select 选择器 过滤后，选择框高度发生变化，但定位不刷新 （上侧漂浮时，远离输入框）

### ISSUE THREAD

**Issue by 10700** [element-plus/element-plus#9261]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgOmRhdGE9XCJkYXRhXCIgZmlsdGVyYWJsZSAvPlxuICA8ZWwtZGl2aWRlciAvPlxuICA8YnI+PGJyPjxicj48YnI+PGJyPjxicj48YnI+PGJyPjxicj48YnI+PGJyPjxicj48YnI+PGJyPlxuICDmjaLooYzmmK/kuLrkuobmiorlhoXlrrnlvoDkuItcbiAgPGVsLWRpdmlkZXIgLz5cbiAg6L6T5YWl6L+H5ruk5p2h5Lu25ZCOOlxuICA8ZWwtdHJlZS1zZWxlY3RcbiAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOmZpbHRlci1ub2RlLW1ldGhvZD1cImZpbHRlck5vZGVNZXRob2RcIlxuICAgIFxuICAgIGZpbHRlcmFibGVcbiAgLz5cbiAgXG4gIDxicj5cbiAgXHRlbC1zZWxlY3Qg5LiN5Lya5Ye6546w6K+l6Zeu6aKYXG4gICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIGZpbHRlcmFibGUgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZGF0YVwiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5jb25zdCBzb3VyY2VEYXRhID0gIFt7XCJ2YWx1ZVwiOlwiMTU2XCIsXCJsYWJlbFwiOlwi5Lit5Zu9XCJ9LHtcInZhbHVlXCI6XCIzNDRcIixcImxhYmVsXCI6XCLkuK3lm73pppnmuK9cIn0se1widmFsdWVcIjpcIjQ0NlwiLFwibGFiZWxcIjpcIuS4reWbvea+s+mXqFwifSx7XCJ2YWx1ZVwiOlwiMTU4XCIsXCJsYWJlbFwiOlwi5Lit5Zu95Y+w5rm+XCJ9LHtcInZhbHVlXCI6XCI0XCIsXCJsYWJlbFwiOlwi6Zi/5a+M5rGXXCJ9LHtcInZhbHVlXCI6XCI4XCIsXCJsYWJlbFwiOlwi6Zi/5bCU5be05bC85LqaXCJ9LHtcInZhbHVlXCI6XCIxMlwiLFwibGFiZWxcIjpcIumYv+WwlOWPiuWIqeS6mlwifSx7XCJ2YWx1ZVwiOlwiMTZcIixcImxhYmVsXCI6XCLnvo7lsZ7okKjmkankuppcIn0se1widmFsdWVcIjpcIjIwXCIsXCJsYWJlbFwiOlwi5a6J6YGT5bCUXCJ9LHtcInZhbHVlXCI6XCIyNFwiLFwibGFiZWxcIjpcIuWuieWTpeaLiVwifSx7XCJ2YWx1ZVwiOlwiNjYwXCIsXCJsYWJlbFwiOlwi5a6J5Liw5ouJXCJ9LHtcInZhbHVlXCI6XCIxMFwiLFwibGFiZWxcIjpcIuWNl+aegea0slwifSx7XCJ2YWx1ZVwiOlwiMjhcIixcImxhYmVsXCI6XCLlronmj5Dnk5zlkozlt7TluIPovr5cIn0se1widmFsdWVcIjpcIjMyXCIsXCJsYWJlbFwiOlwi6Zi/5qC55bu3XCJ9LCB7XCJ2YWx1ZVwiOlwiNzBcIixcImxhYmVsXCI6XCLms6Lpu5FcIn0se1widmFsdWVcIjpcIjcyXCIsXCJsYWJlbFwiOlwi5Y2a6Iyo55Om57qzXCJ9LCB7XCJ2YWx1ZVwiOlwiNDQwXCIsXCJsYWJlbFwiOlwi56uL6Zm25a6bXCJ9LHtcInZhbHVlXCI6XCI0NDJcIixcImxhYmVsXCI6XCLljaLmo67loKFcIn0se1widmFsdWVcIjpcIjgwN1wiLFwibGFiZWxcIjpcIuWJjeWNl+mprOWFtumhv1wifSx7XCJ2YWx1ZVwiOlwiNDUwXCIsXCJsYWJlbFwiOlwi6ams6L6+5Yqg5pav5YqgXCJ9LHtcInZhbHVlXCI6XCI0NTRcIixcImxhYmVsXCI6XCLpqazmi4nnu7RcIn0se1widmFsdWVcIjpcIjQ1OFwiLFwibGFiZWxcIjpcIumprOadpeilv+S6mlwifSwge1widmFsdWVcIjpcIjcxNlwiLFwibGFiZWxcIjpcIua0peW3tOW4g+mfplwifV1cbmNvbnN0IGRhdGEgPSByZWYoc291cmNlRGF0YSlcblxuY29uc3QgZmlsdGVyTWV0aG9kID0gKHZhbHVlKSA9PiB7XG4gIGRhdGEudmFsdWUgPSBbLi4uc291cmNlRGF0YV0uZmlsdGVyKChpdGVtKSA9PiBpdGVtLmxhYmVsLmluY2x1ZGVzKHZhbHVlKSlcbn1cblxuY29uc3QgZmlsdGVyTm9kZU1ldGhvZCA9ICh2YWx1ZSwgZGF0YSkgPT4gZGF0YS5sYWJlbC5pbmNsdWRlcyh2YWx1ZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1、将el-tree-select 元素尽可能放到页面底部，使其选择框漂浮到元素上侧
2、输入过滤条件

### What is Expected?

筛选符合条件的数据，
选择框高度变低，定位下移， 选择框紧挨着对应的元素

### What is actually happening?

选择框的定位并未发生改变，导致选择框 远离对应的输入框

### Additional comments

class="el-popper is-pure is-light el-select__popper el-tree-select__popper"

过滤后，选择框内容变少，高度变低，，但对应弹出框定位，并未根据选择框的高度自动变化

输入框 再输入一个不匹配的字符，选择项空、然后删除，定位会自动刷新，正常显示

![image](https://user-images.githubusercontent.com/10766263/183791325-1e85a899-bc18-4277-9b57-7819821ad9f0.png)

**Comment by mcguire-w** [comment]
问题有解决吗，我也遇到了这问题

**Comment by 10700** [comment]
漂亮
