### ISSUE TITLE
[Build] vue3 引入为什么是 lib 目录？

### ISSUE THREAD

**Issue by Tyh2001** [element-plus/element-plus#9262]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCBlbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG4vLyDkvb/nlKjnvJbovpHlmajmn6XnnIvlvJXlhaXnmoTnm67lvZXvvIzmmK8geHh4eHgvbm9kZV9tb2R1bGVzLy5wbnBtL2VsZW1lbnQtcGx1c0AyLjIuMTJfdnVlQDMuMi4zNy9ub2RlX21vZHVsZXMvZWxlbWVudC1wbHVzL2xpYi9pbmRleFwiXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

引入即可

```ts
import elementPlus from 'element-plus'
```

### What is Expected?

引入路径为：
node_modules/element-plus/es/index

### What is actually happening?

引入路径为：
node_modules/element-plus/lib/index

### Additional comments

已经配置了 main 和 module，为什么还是会引入 lib 呢？

```json
  "main": "lib/index.js",
  "module": "es/index.mjs",
```

**Comment by Tyh2001** [comment]
为啥没有回复呢？

**Comment by tolking** [comment]
不是很明白你的问题，但你确定引用的是文件而不是类型信息。

**Comment by sxzz** [comment]
看你是怎么引入的了，CommonJS 引入的是 lib 目录下的。

**Comment by Tyh2001** [comment]
> 看你是怎么引入的了，CommonJS 引入的是 lib 目录下的。

在 vue3 的项目中引入也算是 CommonJS 吗？不是吧？

**Comment by sxzz** [comment]
talk is cheap, show me the code
