### ISSUE TITLE
[Component] [loading] loading 在element-loading-text 值改变后，页面不会进行对应的变化

### ISSUE THREAD

**Issue by duanzhichao** [element-plus/element-plus#9263]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome 103.0.5060.53`
- Build Tool: `CDN`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uXG4gICAgQGNsaWNrPVwiY2xpY2tcIlxuICA+XG4gICAgdGVzdFxuICA8L2VsLWJ1dHRvbj5cbiAge3ttc2d9fVxuICA8ZWwtdGFibGVcbiAgICB2LWxvYWRpbmc9XCJsb2FkaW5nXCJcbiAgICA6ZWxlbWVudC1sb2FkaW5nLXRleHQ9XCJtc2dcIlxuICAgIDplbGVtZW50LWxvYWRpbmctc3Bpbm5lcj1cInN2Z1wiXG4gICAgZWxlbWVudC1sb2FkaW5nLXN2Zy12aWV3LWJveD1cIi0xMCwgLTEwLCA1MCwgNTBcIlxuICAgIGVsZW1lbnQtbG9hZGluZy1iYWNrZ3JvdW5kPVwicmdiYSgxMjIsIDEyMiwgMTIyLCAwLjgpXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBsb2FkaW5nID0gcmVmKHRydWUpXG5jb25zdCBzdmcgPSBgXG4gICAgICAgIDxwYXRoIGNsYXNzPVwicGF0aFwiIGQ9XCJcbiAgICAgICAgICBNIDMwIDE1XG4gICAgICAgICAgTCAyOCAxN1xuICAgICAgICAgIE0gMjUuNjEgMjUuNjFcbiAgICAgICAgICBBIDE1IDE1LCAwLCAwLCAxLCAxNSAzMFxuICAgICAgICAgIEEgMTUgMTUsIDAsIDEsIDEsIDI3Ljk5IDcuNVxuICAgICAgICAgIEwgMTUgMTVcbiAgICAgICAgXCIgc3R5bGU9XCJzdHJva2Utd2lkdGg6IDRweDsgZmlsbDogcmdiYSgwLCAwLCAwLCAwKVwiLz5cbiAgICAgIGBcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbl1cblxuY29uc3QgbXNnID0gcmVmKCcxMjMnKVxuXG5cbmNvbnN0IGNsaWNrID0gKCkgPT4ge1xuICBtc2cudmFsdWUgPSAnNDU2J1xufVxuXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击按钮

### What is Expected?

loading text 显示 456

### What is actually happening?

依旧是123

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
目前这种使用方式变更text是无法触发指令更新的，你可以使用`LoadingOptions`的方式给指令传参
e.g
```vue
  v-loading="{visible:loading,text:msg,spinner:svg,svgViewBox:'-10, -10, 50, 50',background:'rgba(122, 122, 122, 0.8)'}"
```

**Comment by sxzz** [comment]
`element-loading-xxx` is expected to be deprecated in the next version, please use the form `v-loading="{}"`.
`element-loading-xxx` 预计在下个版本中废弃，请使用 `v-loading="{}"` 的形式。

**Comment by duanzhichao** [comment]
> 目前这种使用方式变更text是无法触发指令更新的，你可以使用`LoadingOptions`的方式给指令传参 e.g
> 
> ```
>   v-loading="{visible:loading,text:msg,spinner:svg,svgViewBox:'-10, -10, 50, 50',background:'rgba(122, 122, 122, 0.8)'}"
> ```

明白  thanks

**Comment by chenxch** [comment]
那我先关闭这个issue了哈
