### ISSUE TITLE
[Component] [menu] el-sub-menu's arrow-icon in mobile view makes weird icon transform

### ISSUE THREAD

**Issue by jongmin4943** [element-plus/element-plus#9273]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome / Window`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwidGFjXCI+XG4gICAgPGVsLWNvbCA6c3Bhbj1cIjEyXCI+XG4gICAgICA8aDUgY2xhc3M9XCJtYi0yXCI+RGVmYXVsdCBjb2xvcnM8L2g1PlxuICAgICAgPGVsLW1lbnVcbiAgICAgICAgZGVmYXVsdC1hY3RpdmU9XCIyXCJcbiAgICAgICAgY2xhc3M9XCJlbC1tZW51LXZlcnRpY2FsLWRlbW9cIlxuICAgICAgICBAb3Blbj1cImhhbmRsZU9wZW5cIlxuICAgICAgICBAY2xvc2U9XCJoYW5kbGVDbG9zZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjFcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPlxuICAgICAgICAgICAgPGVsLWljb24+PGxvY2F0aW9uIC8+PC9lbC1pY29uPlxuICAgICAgICAgICAgPHNwYW4+TmF2aWdhdG9yIE9uZTwvc3Bhbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDxlbC1tZW51LWl0ZW0tZ3JvdXAgdGl0bGU9XCJGaXJzdCBHcm91cFwiPlxuICAgICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtM1wiPm5vIHN1YiBtZW51PC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMS00XCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPnN1YiBtZW51PC90ZW1wbGF0ZT5cbiAgICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgICAgPC9lbC1zdWItbWVudT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWNvbD5cbiBcbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgRG9jdW1lbnQsXG4gIE1lbnUgYXMgSWNvbk1lbnUsXG4gIExvY2F0aW9uLFxuICBTZXR0aW5nLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IGhhbmRsZU9wZW4gPSAoa2V5OiBzdHJpbmcsIGtleVBhdGg6IHN0cmluZ1tdKSA9PiB7XG4gIGNvbnNvbGUubG9nKGtleSwga2V5UGF0aClcbn1cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<template>
  <el-row class="tac">
    <el-col :span="12">
      <h5 class="mb-2">Default colors</h5>
      <el-menu
        default-active="2"
        class="el-menu-vertical-demo"
        @open="handleOpen"
        @close="handleClose"
      >
        <el-sub-menu index="1">
          <template #title>
            <el-icon><location /></el-icon>
            <span>Navigator One</span>
          </template>
          <el-menu-item-group title="First Group">
            <el-menu-item index="1-3">no sub menu</el-menu-item>
          </el-menu-item-group>
          <el-sub-menu index="1-4">
            <template #title>sub menu</template>
            <el-menu-item index="1-4-1">item one</el-menu-item>
          </el-sub-menu>
        </el-sub-menu>
      </el-menu>
    </el-col>
  </el-row>
</template>

<script lang="ts" setup>
import {
  Document,
  Menu as IconMenu,
  Location,
  Setting,
} from '@element-plus/icons-vue'
const handleOpen = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
const handleClose = (key: string, keyPath: string[]) => {
  console.log(key, keyPath)
}
</script>
```

### What is Expected?

el-sub-menu works the same with web and mobile view

### What is actually happening?

el-sub-menu with mobile view makes some weird animation.

### Additional comments

The arrow icon in el-sub-menu's transform makes weird animation when it's in mobile view.

When I was trying that .el-sub-menu.is-opened>.el-sub-menu__title .el-sub-menu__icon-arrow { transform : none; } , the problem disappear but ofc, the arrow icon in el-sub-menu wasn't changed. 2.0.2 didn't have this problem but after I upgraded to 2.2.12, the problem appears.

**Comment by chenxch** [comment]
这个问题是个别浏览对于手势做了一些效果，移动端需要添加以下样式移除手势
```css
.el-menu-item, .el-sub-menu__title {
    cursor: none !important;
}
```
