### ISSUE TITLE
[Component] [All] el-date-picker 报错

### ISSUE THREAD

**Issue by baijing19920921** [element-plus/element-plus#9275]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 双核浏 览器版本 5.1.6.12 （32 位）`
- Build Tool: `Webpack`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker.html)

### Steps to reproduce

使用el-date-picker 报错，不能正常显示

### What is Expected?

期望日期选择组件正常显示

### What is actually happening?

使用el-date-picker 报错，不能正常显示

### Additional comments

_(empty)_

**Comment by baijing19920921** [comment]
defaultTimeDValue.hour is not a function

**Comment by btea** [comment]
根据你提供的官网链接，可以正常显示，并没有报错。
