### ISSUE TITLE
[Component] el-tabs组件下的滚动条自动跳转

### ISSUE THREAD

**Issue by 870385** [element-plus/element-plus#9277]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.5`
- Browser / OS: `Chrome/101.0.4951.54;Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`
- `el-table`
- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcydcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJ1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcydcbiAgfVxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBzdHlsZT1cImhlaWdodDogMTAwMHB4XCI+XG4gICAgICA8ZWwtdGFibGVcbiAgICAgICAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgICAgICAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgICAgICAgICAgICAgICAgIHByb3A9XCJkYXRlXCJcbiAgICAgICAgICAgICAgICAgICAgIGxhYmVsPVwiRGF0ZVwiXG4gICAgICAgICAgICAgICAgICAgICB3aWR0aD1cIjE4MFwiXG4gICAgICAgICAgICAgICAgICAgICA+XG4gICAgICA8ZWwtZHJvcGRvd24+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiZWwtZHJvcGRvd24tbGlua1wiPlxuICAgICAgICAgIERyb3Bkb3duIExpc3RcbiAgICAgICAgPC9zcGFuPlxuICAgICAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMjwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGlzYWJsZWQ+XG4gICAgICAgICAgICAgIEFjdGlvbiA0XG4gICAgICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXZpZGVkPlxuICAgICAgICAgICAgICBBY3Rpb24gNVxuICAgICAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvZWwtZHJvcGRvd24+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgICAgICAgICAgICAgcHJvcD1cIm5hbWVcIlxuICAgICAgICAgICAgICAgICAgICAgbGFiZWw9XCJOYW1lXCJcbiAgICAgICAgICAgICAgICAgICAgIHdpZHRoPVwiMTgwXCJcbiAgICAgICAgICAgICAgICAgICAgIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgICAgICAgICAgICAgICAgcHJvcD1cImFkZHJlc3NcIlxuICAgICAgICAgICAgICAgICAgICAgbGFiZWw9XCJBZGRyZXNzXCJcbiAgICAgICAgICAgICAgICAgICAgIC8+XG4gIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

0.el-tabs的tabPosition设置为left，且tab足够多，页面出现滚动条
1.其中一个tab中有el-table组件，el-table-column插槽下给el-dropdown组件
2.el-table组件在`el-tabs有滚动条且已滚动`的情况下
3.hover展示dropdown菜单，鼠标试图移动到菜单时滚动条会跳动到之前可能被记录的某个位置

### What is Expected?

不要跳动

### What is actually happening?

页面初次加载时会出现这个跳动问题，Playground没法重现

### Additional comments

_(empty)_

**Comment by MARIOMARUI** [comment]
麻烦给出示例说明
