### ISSUE TITLE
dialog渲染问题

### ISSUE THREAD

**Issue by zwStar** [element-plus/element-plus#928]
当我使用dialog时 如:
```
 <el-dialog title="选择关联项目" :model-value="true">
     <el-table ref="table"></el-table>
</el-dialog>

 setup () {
        let table = ref(null);
        onMounted(() => {
            // table; 要拿该ref操作表格 这个时候是null
        });
        return {
            table
        };
    }
```

看到dialog组件的visible是在onMounted里面在判断modelValue再设置为true，也就是dialog的slot子组件渲染会在mounted之后，这个时候就导致上面mounted的时候的slot还是没渲染，所以为null
请问是dialog的这个设计有问题还是有其它方法来满足我这种使用场景

**Comment by JeremyWuuuuu** [comment]
Per description here: https://element-plus.org/#/zh-CN/component/dialog

> Dialog 的内容是懒渲染的，即在第一次被打开之前，传入的默认 slot 不会被渲染到 DOM 上。因此，如果需要执行 DOM 操作，或通过 ref 获取相应组件，请在 open 事件回调中进行
