### ISSUE TITLE
[Component] [el-input, textarea] 自适应文本域设置autosize后手动拖拽会超出设定值中的maxRows

### ISSUE THREAD

**Issue by kikyoluka** [element-plus/element-plus#9283]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `edge 99.0.1150.46 / win64`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `textarea`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input.html#%E8%87%AA%E9%80%82%E5%BA%94%E6%96%87%E6%9C%AC%E5%9F%9F)

### Steps to reproduce

1.进入官网选择input输入框textarea自适应文本域
2.给自适应文本域添加:autosize="{ minRows: 2, maxRows: 4 }"属性
3.手动拖动文本标签右下角，autosize所设定的最大高度失效

### What is Expected?

文本框输入文本及手动拖动调整大小都遵循autosize所设定值

### What is actually happening?

手动拖动调整大小可以绕过autosize所设置的最大高度

### Additional comments

_(empty)_

**Comment by kooriookami** [comment]
`autosize`  属性不会去控制用户手动拖拽的尺寸，这一点是和原生 `textarea` 标签保持一致的，可以参考 MDN 文档。
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/textarea
