### ISSUE TITLE
[Component] [form-item] el-form-item 里使用 el-upload 之后，label标签未生效

### ISSUE THREAD

**Issue by FoamValue** [element-plus/element-plus#9290]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwi5omL5py65Y+356CBXCI+XG4gICAgICA8ZWwtaW5wdXQgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXmiYvmnLrlj7fnoIFcIi8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIueUqOaIt+WktOWDj1wiPlxuICAgICAgIDxlbC11cGxvYWRcbiAgICBjbGFzcz1cImF2YXRhci11cGxvYWRlclwiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6c2hvdy1maWxlLWxpc3Q9XCJmYWxzZVwiXG4gICAgOm9uLXN1Y2Nlc3M9XCJoYW5kbGVBdmF0YXJTdWNjZXNzXCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yZUF2YXRhclVwbG9hZFwiXG4gID5cbiAgICA8aW1nIHYtaWY9XCJpbWFnZVVybFwiIDpzcmM9XCJpbWFnZVVybFwiIGNsYXNzPVwiYXZhdGFyXCIgLz5cbiAgICA8ZWwtaWNvbiB2LWVsc2UgY2xhc3M9XCJhdmF0YXItdXBsb2FkZXItaWNvblwiPjxQbHVzIC8+PC9lbC1pY29uPlxuICA8L2VsLXVwbG9hZD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3QgaW1hZ2VVcmwgPSByZWYoJycpXG5cbmNvbnN0IGhhbmRsZUF2YXRhclN1Y2Nlc3M6IFVwbG9hZFByb3BzWydvblN1Y2Nlc3MnXSA9IChcbiAgcmVzcG9uc2UsXG4gIHVwbG9hZEZpbGVcbikgPT4ge1xuICBpbWFnZVVybC52YWx1ZSA9IFVSTC5jcmVhdGVPYmplY3RVUkwodXBsb2FkRmlsZS5yYXchKVxufVxuXG5jb25zdCBiZWZvcmVBdmF0YXJVcGxvYWQ6IFVwbG9hZFByb3BzWydiZWZvcmVVcGxvYWQnXSA9IChyYXdGaWxlKSA9PiB7XG4gIGlmIChyYXdGaWxlLnR5cGUgIT09ICdpbWFnZS9qcGVnJykge1xuICAgIEVsTWVzc2FnZS5lcnJvcignQXZhdGFyIHBpY3R1cmUgbXVzdCBiZSBKUEcgZm9ybWF0IScpXG4gICAgcmV0dXJuIGZhbHNlXG4gIH0gZWxzZSBpZiAocmF3RmlsZS5zaXplIC8gMTAyNCAvIDEwMjQgPiAyKSB7XG4gICAgRWxNZXNzYWdlLmVycm9yKCdBdmF0YXIgcGljdHVyZSBzaXplIGNhbiBub3QgZXhjZWVkIDJNQiEnKVxuICAgIHJldHVybiBmYWxzZVxuICB9XG4gIHJldHVybiB0cnVlXG59XG48L3NjcmlwdD5cblxuPHN0eWxlPlxubGFiZWwge1xuICAgIGZvbnQtd2VpZ2h0OiA5MDA7XG59XG48L3N0eWxlPlxuXG48c3R5bGUgc2NvcGVkPlxuLmF2YXRhci11cGxvYWRlciAuYXZhdGFyIHtcbiAgd2lkdGg6IDE3OHB4O1xuICBoZWlnaHQ6IDE3OHB4O1xuICBkaXNwbGF5OiBibG9jaztcbn1cbjwvc3R5bGU+XG5cbjxzdHlsZT5cbi5hdmF0YXItdXBsb2FkZXIgLmVsLXVwbG9hZCB7XG4gIGJvcmRlcjogMXB4IGRhc2hlZCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBib3JkZXItcmFkaXVzOiA2cHg7XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xuICBvdmVyZmxvdzogaGlkZGVuO1xuICB0cmFuc2l0aW9uOiB2YXIoLS1lbC10cmFuc2l0aW9uLWR1cmF0aW9uLWZhc3QpO1xufVxuXG4uYXZhdGFyLXVwbG9hZGVyIC5lbC11cGxvYWQ6aG92ZXIge1xuICBib3JkZXItY29sb3I6IHZhcigtLWVsLWNvbG9yLXByaW1hcnkpO1xufVxuXG4uZWwtaWNvbi5hdmF0YXItdXBsb2FkZXItaWNvbiB7XG4gIGZvbnQtc2l6ZTogMjhweDtcbiAgY29sb3I6ICM4YzkzOWQ7XG4gIHdpZHRoOiAxNzhweDtcbiAgaGVpZ2h0OiAxNzhweDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xufVxuPC9zdHlsZT5cblxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

打开链接，调整样式，观察 label 字体。

```
label {
    font-weight: 900;
}
```

### What is Expected?

```
<div class="el-form-item" role="group" aria-labelledby="el-id-3397-4" data-v-472cff63="">
<label id="el-id-3397-4" class="el-form-item__label">用户头像</label>
```

### What is actually happening?

```
<div class="el-form-item" role="group" aria-labelledby="el-id-3397-4" data-v-472cff63="">
<div id="el-id-3397-4" class="el-form-item__label">用户头像</div>
```

### Additional comments

_(empty)_

**Comment by holazz** [comment]
```css
.el-form-item__label {
	font-weight: 900;
}
```
