### ISSUE TITLE
[Style] [date-picker] 定义全局组件类名称前缀后，TimePicker组件样式未生效，还是使用的默认class前缀

### ISSUE THREAD

**Issue by fs821031547** [element-plus/element-plus#9292]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICAgICAgIFxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgbmFtZXNwYWNlPVwiZXBcIj5cbiAgICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgIHR5cGU9XCJkYXRlcmFuZ2VcIlxuICAgICAgICByYW5nZS1zZXBhcmF0b3I9XCJUb1wiXG4gICAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgZGF0ZVwiXG4gICAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBkYXRlXCJcbiAgICAgICAgOnNpemU9XCJzaXplXCJcbiAgICAgIC8+XG4gICAgPC9lbC1jb25maWctcHJvdmlkZXI+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInZpdGUuY29uZmlnLnRzIjoiaW1wb3J0IHBhdGggZnJvbSAncGF0aCc7XG5jb25zdCBwYXRoU3JjID0gcGF0aC5yZXNvbHZlKF9fZGlybmFtZSwgJ3NyYycpO1xuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29uZmlnKCgpID0+IHtcbiAgcmV0dXJuIHtcbiAgICByZXNvbHZlOiB7XG4gICAgICBhbGlhczoge1xuICAgICAgICAnQC8nOiBgJHtwYXRoU3JjfS9gLFxuICAgICAgfSxcbiAgICB9LFxuICAgIGNzczoge1xuICAgICAgLy8g5a+85YWl6Ieq5a6a5LmJ5ZG95ZCN56m66Ze06K6+572uXG4gICAgICBwcmVwcm9jZXNzb3JPcHRpb25zOiB7XG4gICAgICAgIHNjc3M6IHtcbiAgICAgICAgICBhZGRpdGlvbmFsRGF0YTogYEB1c2UgXCJAL3N0eWxlcy9lbGVtZW50L2luZGV4LnNjc3NcIiBhcyAqO2AsXG4gICAgICAgIH0sXG4gICAgICB9LFxuICAgIH0sXG5cdH1cbn0pOyIsImluZGV4LmNzcyI6IkBmb3J3YXJkICdlbGVtZW50LXBsdXMvdGhlbWUtY2hhbGsvc3JjL21peGlucy9jb25maWcuc2Nzcycgd2l0aCAoXG4gICRuYW1lc3BhY2U6ICdlcCdcbik7IiwiX28iOnt9fQ==)

### Steps to reproduce

定义全局组件类名称前缀ep后，TimePicker组件样式未生效，class前缀还是el并没有改为ep导致组件样式失效

### What is Expected?

修改命名空间ep后，期望TimePicker组件样式正常

### What is actually happening?

修改命名空间ep后，实际TimePicker组件样式错乱没有生效

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/15795249/184301751-f7f1e766-ca98-482a-ad5d-32c2a74969ca.png)

**Comment by fs821031547** [comment]
input输入框显示正常，但是日历弹窗所引用的class未修改过来
![image](https://user-images.githubusercontent.com/15795249/184306649-9c1fae92-619b-4953-9492-2a29d6184d99.png)
![image](https://user-images.githubusercontent.com/15795249/184306798-5accbc96-d460-4e1e-b26d-8535168ead6d.png)

**Comment by fs821031547** [comment]
input输入框显示正常，但是日历弹窗所引用的class未修改过来
![image](https://user-images.githubusercontent.com/15795249/184306649-9c1fae92-619b-4953-9492-2a29d6184d99.png)
![image](https://user-images.githubusercontent.com/15795249/184307344-b865f69f-9bc6-4bf8-a2a4-f1d9c80723b7.png)

**Comment by holazz** [comment]
使用最新版本的 Element Plus

**Comment by sxzz** [comment]
@holazz Has this bug been fixed? If so, you can close this issue.

**Comment by holazz** [comment]
> @holazz Has this bug been fixed? If so, you can close this issue.

It has been fixed.
