### ISSUE TITLE
[Component] [menu] el-menu collapse 内存泄漏

### ISSUE THREAD

**Issue by scvzerng** [element-plus/element-plus#9296]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY29sbGFwc2UgPSByZWYoZmFsc2UpO1xuXG5jb25zdCBoYW5kbGVDb2xsYXBzZSA9ICgpPT57XG4gIGNvbGxhcHNlLnZhbHVlID0gIWNvbGxhcHNlLnZhbHVlO1xufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNvbGxhcHNlXCI+Y29sbGFwc2Uge3tjb2xsYXBzZX19XG4gIDwvZWwtYnV0dG9uPlxuICA8ZWwtbWVudSA6Y29sbGFwc2UtdHJhbnNpdGlvbj1cImZhbHNlXCIgY2xhc3M9XCJtZW51XCIgOmNvbGxhcHNlPVwiY29sbGFwc2VcIj5cbiAgICA8ZWwtbWVudS1pdGVtICB2LWZvcj1cImkgaW4gNTBcIiA6aW5kZXg9XCJgaW5kZXgtJHtpfWBcIiA+XG4gICAgIG5vZGUge3tpfX1cbiAgICA8L2VsLW1lbnUtaXRlbT5cbiAgPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIHNjb3BlZD5cbiAgLm1lbnV7XG4gICAgbWF4LXdpZHRoOiAyMDBweDtcbiAgICBib3JkZXItcmlnaHQ6IDEgc29pbGQgdmFyKC0tZWwtbWVudS1ib3JkZXItY29sb3IpICFpbXBvcnRtZW50XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

不停的展开收缩menu

### What is Expected?

chrome devtools performance monitor监控下Dom Nodes能正常释放 内存被正常释放

### What is actually happening?

Dom Nodes随点击次数增长内存消耗相应增长 手动gc后无任何变化

### Additional comments

_(empty)_

**Comment by scvzerng** [comment]
![1660295655547](https://user-images.githubusercontent.com/14892120/184324031-3743e4d5-74be-49cb-b67b-f6ca369ecf5c.png)
---
这是初始内存 快速点击几十次后手动gc下如下图
![1660295755602](https://user-images.githubusercontent.com/14892120/184324234-4c4221fb-fba2-4df8-a9b5-e93c9b6c96c1.png)
---
## 可以看出有内存泄漏情况，虽然正常来说menu这么操作很离谱基本上不会

**Comment by iwusong** [comment]
测试内存泄漏的时候不要打开vue devtool

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/element-plus/element-plus/issues/10570)

**Comment by Alixhan** [comment]
请问这个问题解决的吗，我现在最新版element-plus 2.3.2 el-menu收起后的内存无法GC，还是有内存泄漏啊。

**Comment by Alixhan** [comment]
Vue-devtool is disabled，there is still memory leak.
