### ISSUE TITLE
[Bug Report] El-switch starts the Change method on the first render

### ISSUE THREAD

**Issue by XingXiaoWu** [element-plus/element-plus#930]
# Element-Plus version
"element-plus": "^1.0.1-beta.5"

# OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

# Steps to reproduce
set switch @change

# What is Expected?
It will not fire the first time it is rendered

# What is actually happening?
It will fire the first time you render

This is example:
https://codepen.io/xingxiaowu/pen/KKggqpZ

I compared the element  2.14.1, which is normal：
https://codepen.io/xingxiaowu/pen/QWKKgjq

**Comment by Ryan2128** [comment]
Thanks. It will be fixed in next version.

**Comment by Ryan2128** [comment]
I check the source code and test the demo you provide just now, I find there is an error in your usage.

```
if (!~[props.activeValue, props.inactiveValue].indexOf(actualValue.value)) {
  ctx.emit('update:modelValue', props.inactiveValue)
  ctx.emit('change', props.inactiveValue)
  ctx.emit('input', props.inactiveValue)
}
```

You passed the `active-value` and `inactive-value`, but the `v-model` is `undefind`. So `switch` will emit a `change` event firstly.

**Comment by Ryan2128** [comment]
If there are no doubts, I will close the issue later.

**Comment by XingXiaoWu** [comment]
> I check the source code and test the demo you provide just now, I find there is an error in your usage.
> 
> ```
> if (!~[props.activeValue, props.inactiveValue].indexOf(actualValue.value)) {
>   ctx.emit('update:modelValue', props.inactiveValue)
>   ctx.emit('change', props.inactiveValue)
>   ctx.emit('input', props.inactiveValue)
> }
> ```
> 
> You passed the `active-value` and `inactive-value`, but the `v-model` is `undefind`. So `switch` will emit a `change` event firstly.
> 
> ```
> <el-switch
>   @change="switchChange"
>   v-model="value"
>   active-color="#13ce66"
>   inactive-color="#ff4949"
>   active-value="100"
>   inactive-value="0">
> </el-switch>
> 
> var Main = {
>   data() {
>     return {
>       value1: true,
>       value2: true
>     };
>   },
>   methods: {
>     switchChange(val) {
>       console.log("123");
>     }
>   }
> };
> ```

Sorry for not replying in time just now.
In fact, I omitted the example when I copied it, but the preset value will also trigger the change event.
Like this:
https://codepen.io/xingxiaowu/pen/KKggqpZ

**Comment by Ryan2128** [comment]
You passed the `active-value` and `inactive-value`, so the default value of `v-model` should be one of them.

The logic of emit the `change` event is below:

```
if (!~[props.activeValue, props.inactiveValue].indexOf(actualValue.value)) {
  ctx.emit('update:modelValue', props.inactiveValue)
  ctx.emit('change', props.inactiveValue)
  ctx.emit('input', props.inactiveValue)
}
```

**Comment by Ryan2128** [comment]
In your latest demo, there is no change event was emitted.

**Comment by Ryan2128** [comment]
The code I provided above is your wrong code.

**Comment by XingXiaoWu** [comment]
> You passed the `active-value` and `inactive-value` with two **string** instead of `true` and `false`, so the default value of `v-model` should be one of them.
> 
> The logic of emit the `change` event is below:
> 
> ```
> if (!~[props.activeValue, props.inactiveValue].indexOf(actualValue.value)) {
>   ctx.emit('update:modelValue', props.inactiveValue)
>   ctx.emit('change', props.inactiveValue)
>   ctx.emit('input', props.inactiveValue)
> }
> ```

oh,I understand.I'm sorry to have bothered you so long. Thank you very much.

Whether the relationship between the two values and the modelVal can be explained in the document is not seen on the document, so this misunderstanding occurs.

**Comment by Ryan2128** [comment]
The relevant description is as follows. If you feel that it is not perfect, please feel free to open a PR.

![image](https://user-images.githubusercontent.com/33176053/101642637-2f575c00-3a6e-11eb-8d99-90bb49429b93.png)

![image](https://user-images.githubusercontent.com/33176053/101642673-3b431e00-3a6e-11eb-9475-a2a6ad0c40ff.png)

**Comment by XingXiaoWu** [comment]
Ok, thanks again

**Comment by XingXiaoWu** [comment]
Sorry to bother you again,I found el-switch there was a problem with loading in the table

It looks like only boolean is fine.

If you set activity-value and inactive-value, you will have a problem, It will fire the first time you render

https://codepen.io/xingxiaowu/pen/KKggqpZ
