### ISSUE TITLE
[Component] [input] el-input样式问题

### ISSUE THREAD

**Issue by SmallSample** [element-plus/element-plus#9304]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: ` Chrome 102.0.5005.63 / Windows10`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLXNwYWNlPlxuICBcdDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgY2xlYXJhYmxlIC8+XG4gIDwvZWwtc3BhY2U+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.将el-input组件放入el-space中，并设置el-input的clearable属性
2.在el-input中输入内容后，将鼠标悬浮在el-input上

### What is Expected?

el-input组件长度不变

### What is actually happening?

el-input组件长度变长

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
这是由于el-input的width:100%属性在el-space__item上得不到所继承导致，可以考虑包一层带宽度的div

**Comment by SmallSample** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liukang824** [comment]
有没有别的解决方案

**Comment by tolking** [comment]
Link #7287
