### ISSUE TITLE
el-collapse不能触发change事件

### ISSUE THREAD

**Issue by yorkolee** [element-plus/element-plus#932]
例子:https://element-plus.gitee.io/#/zh-CN/component/collapse
<el-collapse v-model="activeNames" @change="handleChange">
没有触发事件
handleChange(val) {
   console.log(val);
}

**Comment by JeremyWuuuuu** [comment]
We will investigate this ASAP

**Comment by Lliuxs** [comment]
我之前遇到过 好像是没emit('change', value) 我是直接取的activeNames的值

**Comment by woshiwhy** [comment]
大概什么时候修复完成

**Comment by JeremyWuuuuu** [comment]
We will do it as soon as we can, all contributors are not full time OSS developers. PR is welcomed.

**Comment by JeremyWuuuuu** [comment]
cc @bastarder

**Comment by JeremyWuuuuu** [comment]
I think it's because of the design, though adding the event is not a big deal, I'll add it later. 
For now with `v-model` watching `modelValue` seems a better I idea. (Just my personal opinion)
