### ISSUE TITLE
[Docs] [All] 中文文档经常出现问题

### ISSUE THREAD

**Issue by HWYD** [element-plus/element-plus#9323]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.2.13`
- Browser / OS: `Chrome: 106.0.5231.2`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/)

### Steps to reproduce

文档链接：https://element-plus.gitee.io/zh-CN/

### What is Expected?

修复中文文档访问异常问题

### What is actually happening?

查看文档某个组件时跳转不过去，控制台出现报错，或者文档左侧菜单丢失

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
same：https://github.com/element-plus/element-plus/issues/9196
