### ISSUE TITLE
[Component] [dialog] Dialog 对话框

### ISSUE THREAD

**Issue by 1941238125** [element-plus/element-plus#9324]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `chrome`
- Build Tool: `Webpack`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5DbGljayB0byBvcGVuIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgdGl0bGU9XCJUaXBzXCIgd2lkdGg9XCIzMCVcIiBkcmFnZ2FibGU+XG4gICAgPHNwYW4+SXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2dJdCdzIGEgZHJhZ2dhYmxlIERpYWxvZ0l0J3MgYSBkcmFnZ2FibGUgRGlhbG9nSXQncyBhIGRyYWdnYWJsZSBEaWFsb2c8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gZmFsc2VcIj5DYW5jZWw8L2VsLWJ1dHRvbj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

使用dialog组件中draggable属性实现拖拽，如果内容过多，超过了浏览器高度，就回造成吸顶，只能左右移动

### What is Expected?

可自由拖拽

### What is actually happening?

吸顶，只能左右移动

### Additional comments

_(empty)_

**Comment by holazz** [comment]
Duplicate of #9100

**Comment by 1941238125** [comment]
这应该是一个比较明显的bug了，参考了其他ui组件没有出现这个问题，element应该改善一下

**Comment by xupeihong** [comment]
Why element of the play does not want to iview window of the window, can directly drive directly with an attribute, the element also have to add a directive file content, and also can't use.
