### ISSUE TITLE
[Component] [select-v2, select] All components which use popper does not work (not displayed) in fullscreen 

### ISSUE THREAD

**Issue by wtcodeai** [element-plus/element-plus#9329]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `Safari 15.2 (17612.3.6.1.6)/Mac OS 12.1`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBjaCA9IHJlZigxKVxuY29uc3QgcGwgPSByZWYobnVsbClcbmNvbnN0IGFsID0gKCkgPT4ge1xuICBpZiAocGwudmFsdWUucmVxdWVzdEZ1bGxzY3JlZW4pIHtcbiAgICBwbC52YWx1ZS5yZXF1ZXN0RnVsbHNjcmVlbigpXG4gIH1cbiAgaWYgKHBsLnZhbHVlLndlYmtpdFJlcXVlc3RGdWxsc2NyZWVuKSB7XG5cdFx0cGwudmFsdWUud2Via2l0UmVxdWVzdEZ1bGxzY3JlZW4oKVxuICB9XG4gXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuXHQ8ZGl2IHJlZj1cInBsXCI+XG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgdi1tb2RlbD1cImNoXCJcbiAgICAgIDpvcHRpb25zPVwiXG4gICAgICAgIFsuLi5BcnJheSg1KS5rZXlzKCldLm1hcChrID0+ICh7IHZhbHVlOiAoaysxKSwgbGFiZWw6IGAke2srMX1gIH0pKVxuICAgICAgXCJcbiAgICAvPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiYWxcIj5cbiAgICBcdHRvZ2dsZSBmdWxsc2NyZWVuXG4gICAgPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Set up component with popper, for example virtualized select inside the wrapper div
2. Try to open select dropdown and choose select option
3. Toggle fullscreen on wrapper element
4. Try to open select dropdown again

### What is Expected?

Select drodpown opens as always

### What is actually happening?

Select dropdown is not opened (not visible to be honest)

### Additional comments

Maybe I am missing some settings in popper js documentation but think that thing should work by default without configuring any additional settings

**Comment by xuanyyyy** [comment]
This may be because the window popped up by the popper is a child of the body in the tree node, but the popper does not exist in the tree species of the node where you request full screen

**Comment by wtcodeai** [comment]
> This may be because the window popped up by the popper is a child of the body in the tree node, but the popper does not exist in the tree species of the node where you request full screen

Yep, yo are literally right, there is popper container which is neighbour to app container and it also contains all page poppers.
But I am not sure, that I can find some options which can allow me to attach this wrapper somewhere else
It does not exist in components params neither popper js documented properties
Maybe I miss something?

**Comment by wtcodeai** [comment]
UPD: okay, i just figured it out. Miss teleported prop cause for example dropdown does not contain it.
So, my problem is solved but i think there a thing which needs to be fixed (I mean dropdown teleported prop)

**Comment by tolking** [comment]
teleported = false
