### ISSUE TITLE
[Component] [date-picker] ec-date-picker type=monthrange 月份无法联动

### ISSUE THREAD

**Issue by arkfancy** [element-plus/element-plus#9334]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.13`
- Browser / OS: `Chrome/104.0.0.0`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+RGVmYXVsdDwvc3Bhbj5cbiAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgICAgdHlwZT1cIm1vbnRocmFuZ2VcIlxuICAgICAgICByYW5nZS1zZXBhcmF0b3I9XCJUb1wiXG4gICAgICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgbW9udGhcIlxuICAgICAgICBlbmQtcGxhY2Vob2xkZXI9XCJFbmQgbW9udGhcIlxuICAgICAgLz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5cbmNvbnN0IHNob3J0Y3V0cyA9IFtcbiAge1xuICAgIHRleHQ6ICdUaGlzIG1vbnRoJyxcbiAgICB2YWx1ZTogW25ldyBEYXRlKCksIG5ldyBEYXRlKCldLFxuICB9LFxuICB7XG4gICAgdGV4dDogJ1RoaXMgeWVhcicsXG4gICAgdmFsdWU6ICgpID0+IHtcbiAgICAgIGNvbnN0IGVuZCA9IG5ldyBEYXRlKClcbiAgICAgIGNvbnN0IHN0YXJ0ID0gbmV3IERhdGUobmV3IERhdGUoKS5nZXRGdWxsWWVhcigpLCAwKVxuICAgICAgcmV0dXJuIFtzdGFydCwgZW5kXVxuICAgIH0sXG4gIH0sXG4gIHtcbiAgICB0ZXh0OiAnTGFzdCA2IG1vbnRocycsXG4gICAgdmFsdWU6ICgpID0+IHtcbiAgICAgIGNvbnN0IGVuZCA9IG5ldyBEYXRlKClcbiAgICAgIGNvbnN0IHN0YXJ0ID0gbmV3IERhdGUoKVxuICAgICAgc3RhcnQuc2V0TW9udGgoc3RhcnQuZ2V0TW9udGgoKSAtIDYpXG4gICAgICByZXR1cm4gW3N0YXJ0LCBlbmRdXG4gICAgfSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWRhdGUtcGlja2VyIHtcbiAgZGlzcGxheTogZmxleDtcbiAgd2lkdGg6IDEwMCU7XG4gIHBhZGRpbmc6IDA7XG4gIGZsZXgtd3JhcDogd3JhcDtcbn1cbi5kZW1vLWRhdGUtcGlja2VyIC5ibG9jayB7XG4gIHBhZGRpbmc6IDMwcHggMDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBib3JkZXItcmlnaHQ6IHNvbGlkIDFweCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBmbGV4OiAxO1xufVxuLmRlbW8tZGF0ZS1waWNrZXIgLmJsb2NrOmxhc3QtY2hpbGQge1xuICBib3JkZXItcmlnaHQ6IG5vbmU7XG59XG4uZGVtby1kYXRlLXBpY2tlciAuZGVtb25zdHJhdGlvbiB7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBjb2xvcjogdmFyKC0tZWwtdGV4dC1jb2xvci1zZWNvbmRhcnkpO1xuICBmb250LXNpemU6IDE0cHg7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

示例从官方文档中扒下，可直接查看官方文档 https://element-plus.org/zh-CN/component/date-picker.html#%E9%80%89%E6%8B%A9%E6%9C%88%E4%BB%BD%E8%8C%83%E5%9B%B4

在月份面板中，每个面板只有一半的箭头，点击箭头时，只有箭头所在的面板会变，另一个面板没联动，导致年份无法回选。

### What is Expected?

左右面板联动，或者各面板有双箭头可以来回选择年份

### What is actually happening?

年份回不回来

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/30465365/184793725-25613c4e-c4e9-479d-92aa-34e9414f9040.png)

**Comment by lm312** [comment]
如果希望两个面板各自独立切换当前年份，可以使用 unlink-panels 属性解除联动。

**Comment by chenxch** [comment]
fixed #10292.
