### ISSUE TITLE
[All] element-plus 开始要烂掉了吗？issues八百多，pr 两百多么没处理，pr也没人审核

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#9337]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN)

### Steps to reproduce

是要准备弃坑了吗？还是说近期有什么计划可以透露一下？

### What is Expected?

优先解决当前的问题

### What is actually happening?

issues pr 无人处理

### Additional comments

_(empty)_

**Comment by suzhenghui-sky** [comment]
本来就是顺手开源的。没钱，肯定是优先自己的工作先。

**Comment by gjfei** [comment]
> 本来就是顺手开源的。没钱，肯定是优先自己的工作先。

这个没问题的，既然你开源了，没时间来维护了，是不是可以给想维护的人更多的权限呢？

**Comment by suzhenghui-sky** [comment]
你想要什么权限？不用经过审核就可以合并代码的权限？还是其他？

**Comment by gjfei** [comment]
> 你想要什么权限？不用经过审核就可以合并代码的权限？还是其他？

首先我不想要，也不是直接合并的权限，一切还是要按照规矩来。如果开发者忙没问题大家都有自己要做的事情，这时候是不是可以给其他想要并且可以负责的人审核的权限和合并的权限呢？你可以去看下前十的贡献者最近有没有处理问题。

**Comment by xiaoxian521** [comment]
https://github.com/element-plus/element-plus/discussions/3326
