### ISSUE TITLE
[Component] [menu] Menu Events select args bug

### ISSUE THREAD

**Issue by Verdicts-ye** [element-plus/element-plus#9341]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 QIHU 360EE`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBzZWxlY3QgPSAoYSxiLGMsZCk9PntcbiAgY29uc29sZS5sb2coZClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8cD5cbiAgIDxlbC1tZW51IHJvdXRlciBAc2VsZWN0PSdzZWxlY3QnPlxuICAgIDxlbC1tZW51LWl0ZW0gOmluZGV4PScvbmF2Jz7lr7zoiKo8L2VsLW1lbnUtaXRlbT5cbiAgICA8L2VsLW1lbnU+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

关联vue-router后,第四个返回参数总是promise padding
After associating Vue router, the fourth parameter always returns promise padding

### What is Expected?

The fourth parameter should return my routing information
第四个参数应该返回对应的route信息

### What is actually happening?

Promise {<pending>}
[[Prototype]]: Promise
catch: ƒ catch()
constructor: ƒ Promise()
finally: ƒ finally()
then: ƒ then()
Symbol(Symbol.toStringTag): "Promise"
[[Prototype]]: Object
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: undefined

### Additional comments

我该怎么解决这个问题,才能返回正常

**Comment by daonatural** [comment]
也许是文档描述不够清晰而造成的歧义，这里的 `vue-router 的返回值` (第四个参数) 并不是猜想的那个结果（router对应链接的信息），而就是一个`promise`。
这个 `promise` **变量d** 等价于下面的情况：

伪代码如下
```
const { push } = useRouter();
var d = push("/home");  //  push("/home") 是一个promise 也就是 el-menu select事件中的第四个变量
```

所以，这里 **变量d** 给到使用者的使用场景不是获取`router`对象，而是触发在此路由跳转成功后的自身行为逻辑。使用如下：
```vue
<template>
  <div>
    <el-menu router @select="select">
      <el-menu-item index="/demo">导航</el-menu-item>
    </el-menu>
    <h1>{{ msg }}</h1>
    <p> Element Plus {{ EpVersion }} + Vue {{ vueVersion }} </p>
    <el-button @click="onRedirect">test</el-button>
  </div>
</template>


<script setup lang="ts">
import { ref, version as vueVersion } from "vue";
import { version as EpVersion } from "element-plus";

const msg = ref("Hello World!");
const select = (a, b, c, d) => {
  d.then(
    (data) => {
      // code this...
     // 在路由跳转成功后，使用者的自身的额外业务逻辑。如果没有额外逻辑，这个d就是无用的
    }
  );
};
</script>
```

**Comment by Verdicts-ye** [comment]
好的,谢谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月19日(星期五) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] [Component] [menu] Menu Events select args bug (Issue #9341)





 
也许是文档描述不够清晰而造成的歧义，这里的 vue-router 的返回值 (第四个参数) 并不是猜想的那个结果（router对应链接的信息），而就是一个promise。
 这个 promise 变量d 等价于下面的情况：
 
伪代码如下
 const { push } = useRouter(); var d = push("/home");  //  push("/home") 是一个promise 也就是 el-menu select事件中的第四个变量  
所以，这里 变量d 给到使用者的使用场景不是获取router对象，而是触发在此路由跳转成功后的自身行为逻辑。使用如下：
 <template&gt;   <div&gt;     <el-menu router @select="select"&gt;       <el-menu-item index="/demo"&gt;导航</el-menu-item&gt;     </el-menu&gt;     <h1&gt;{{ msg }}</h1&gt;     <p&gt; Element Plus {{ EpVersion }} + Vue {{ vueVersion }} </p&gt;     <el-button @click="onRedirect"&gt;test</el-button&gt;   </div&gt; </template&gt; <script setup lang="ts"&gt; import { ref, version as vueVersion } from "vue"; import { version as EpVersion } from "element-plus";  const msg = ref("Hello World!"); const select = (a, b, c, d) =&gt; {   d.then(     (data) =&gt; {       // code this...      // 在路由跳转成功后，使用者的自身的额外业务逻辑。如果没有额外逻辑，这个d就是无用的     }   ); }; </script&gt;
