### ISSUE TITLE
[Style] [All] 自定义命名空间中还存在部分 未使用命名空间的变量

### ISSUE THREAD

**Issue by Half-A-Turnip** [element-plus/element-plus#9344]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.13`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter)

### Steps to reproduce

下载官方的模板，安装依赖之后，运行。:root中还包括el前端的变量。如下
:root {
    --el-color-white: #ffffff;
    --el-color-black: #000000;
    --el-color-primary-rgb: 64, 158, 255;
    --el-color-success-rgb: 103, 194, 58;
    --el-color-warning-rgb: 230, 162, 60;
    --el-color-danger-rgb: 245, 108, 108;
    --el-color-error-rgb: 245, 108, 108;
    --el-color-info-rgb: 144, 147, 153;
    --el-font-size-extra-large: 20px;
    --el-font-size-large: 18px;
    --el-font-size-medium: 16px;
    --el-font-size-base: 14px;
    --el-font-size-small: 13px;
    --el-font-size-extra-small: 12px;
    --el-font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
    'Microsoft YaHei', '微软雅黑', Arial, sans-serif;
    --el-font-weight-primary: 500;
    --el-font-line-height-primary: 24px;
    --el-index-normal: 1;
    --el-index-top: 1000;
    --el-index-popper: 2000;
    --el-border-radius-base: 4px;
    --el-border-radius-small: 2px;
    --el-border-radius-round: 20px;
    --el-border-radius-circle: 100%;
    --el-transition-duration: 0.3s;
    --el-transition-duration-fast: 0.2s;
    --el-transition-function-ease-in-out-bezier: cubic-bezier(0.645, 0.045, 0.355, 1);
    --el-transition-function-fast-bezier: cubic-bezier(0.23, 1, 0.32, 1);
    --el-transition-all: all var(--el-transition-duration)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-fade: opacity var(--el-transition-duration)
    var(--el-transition-function-fast-bezier);
    --el-transition-md-fade: transform var(--el-transition-duration)
      var(--el-transition-function-fast-bezier),
    opacity var(--el-transition-duration) var(--el-transition-function-fast-bezier);
    --el-transition-fade-linear: opacity var(--el-transition-duration-fast) linear;
    --el-transition-border: border-color var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-box-shadow: box-shadow var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-color: color var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-component-size-large: 40px;
    --el-component-size: 32px;
    --el-component-size-small: 24px;
}

### What is Expected?

期望只有替换的命名空间变量

### What is actually happening?

:root {
    --el-color-white: #ffffff;
    --el-color-black: #000000;
    --el-color-primary-rgb: 64, 158, 255;
    --el-color-success-rgb: 103, 194, 58;
    --el-color-warning-rgb: 230, 162, 60;
    --el-color-danger-rgb: 245, 108, 108;
    --el-color-error-rgb: 245, 108, 108;
    --el-color-info-rgb: 144, 147, 153;
    --el-font-size-extra-large: 20px;
    --el-font-size-large: 18px;
    --el-font-size-medium: 16px;
    --el-font-size-base: 14px;
    --el-font-size-small: 13px;
    --el-font-size-extra-small: 12px;
    --el-font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',
    'Microsoft YaHei', '微软雅黑', Arial, sans-serif;
    --el-font-weight-primary: 500;
    --el-font-line-height-primary: 24px;
    --el-index-normal: 1;
    --el-index-top: 1000;
    --el-index-popper: 2000;
    --el-border-radius-base: 4px;
    --el-border-radius-small: 2px;
    --el-border-radius-round: 20px;
    --el-border-radius-circle: 100%;
    --el-transition-duration: 0.3s;
    --el-transition-duration-fast: 0.2s;
    --el-transition-function-ease-in-out-bezier: cubic-bezier(0.645, 0.045, 0.355, 1);
    --el-transition-function-fast-bezier: cubic-bezier(0.23, 1, 0.32, 1);
    --el-transition-all: all var(--el-transition-duration)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-fade: opacity var(--el-transition-duration)
    var(--el-transition-function-fast-bezier);
    --el-transition-md-fade: transform var(--el-transition-duration)
      var(--el-transition-function-fast-bezier),
    opacity var(--el-transition-duration) var(--el-transition-function-fast-bezier);
    --el-transition-fade-linear: opacity var(--el-transition-duration-fast) linear;
    --el-transition-border: border-color var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-box-shadow: box-shadow var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-transition-color: color var(--el-transition-duration-fast)
    var(--el-transition-function-ease-in-out-bezier);
    --el-component-size-large: 40px;
    --el-component-size: 32px;
    --el-component-size-small: 24px;
}

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/24860389/185022515-7473c41e-50eb-47c1-ab75-9fbb93232652.png)

**Comment by chenxch** [comment]
scss目前不支持类似tree shake的操作，你可以自行构建var.scss，但是可能会导致一些你没察觉的到的变量丢失。
