### ISSUE TITLE
[Component] [table-v2] table-v2 minWidth不生效

### ISSUE THREAD

**Issue by kikyoluka** [element-plus/element-plus#9348]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `edge 99.0.1150.46 / win64`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[CodePen](https://codepen.io/kikyoluka/pen/KKorEzx?editors=1000)

### Steps to reproduce

1.创建一个table-v2
2.给其中一列设置minWidth

### What is Expected?

在表格头部还有大量空余的情况下使用minWidth实现自适应宽度

### What is actually happening?

minWidth不生效

### Additional comments

_(empty)_

**Comment by btea** [comment]
When `fixed` is set to `false`, `minWidth` will take effect. [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgZGF0YSA9IFtcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG4gIHtcbiAgIGRldklkOjEyMyxcbiAgIGlwOicxMC4yMTUuMjMzLjEnLFxuICAgbGluZToxNzJcbiB9LFxuICB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG5dO1xuY29uc3QgY29sdW1ucyA9IFtcbiAgIHtcbiAgICBrZXk6ICdkZXZJZCcsXG4gICAgdGl0bGU6ICdkZXZJZCcsXG4gICAgZGF0YUtleTogJ2RldklkJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDE2MCxcbiAgICBtaW5XaWR0aDozMDAsXG4gIH0sXG4gIHtcbiAgICBrZXk6ICdpcCcsXG4gICAgdGl0bGU6ICdpcCcsXG4gICAgZGF0YUtleTogJ2lwJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDEyMCxcbiAgfSxcbiAge1xuICAgIGtleTogJ2xpbmUnLFxuICAgIHRpdGxlOiAnbGluZScsXG4gICAgZGF0YUtleTogJ2xpbmUnLFxuICAgIGFsaWduOiAnY2VudGVyJyxcbiAgICB3aWR0aDogMTAwLFxuICB9LFxuIF1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZS12MlxuICAgIDpjb2x1bW5zPVwiY29sdW1uc1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6d2lkdGg9XCIxMDAwXCJcbiAgICA6aGVpZ2h0PVwiNTAwXCJcbiAgICA6Zml4ZWQ9XCJmYWxzZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by kikyoluka** [comment]
> 设置为 时，将生效。[演示](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgZGF0YSA9IFtcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG4gIHtcbiAgIGRldklkOjEyMyxcbiAgIGlwOicxMC4yMTUuMjMzLjEnLFxuICAgbGluZToxNzJcbiB9LFxuICB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG5dO1xuY29uc3QgY29sdW1ucyA9IFtcbiAgIHtcbiAgICBrZXk6ICdkZXZJZCcsXG4gICAgdGl0bGU6ICdkZXZJZCcsXG4gICAgZGF0YUtleTogJ2RldklkJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDE2MCxcbiAgICBtaW5XaWR0aDozMDAsXG4gIH0sXG4gIHtcbiAgICBrZXk6ICdpcCcsXG4gICAgdGl0bGU6ICdpcCcsXG4gICAgZGF0YUtleTogJ2lwJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDEyMCxcbiAgfSxcbiAge1xuICAgIGtleTogJ2xpbmUnLFxuICAgIHRpdGxlOiAnbGluZScsXG4gICAgZGF0YUtleTogJ2xpbmUnLFxuICAgIGFsaWduOiAnY2VudGVyJyxcbiAgICB3aWR0aDogMTAwLFxuICB9LFxuIF1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZS12MlxuICAgIDpjb2x1bW5zPVwiY29sdW1uc1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6d2lkdGg9XCIxMDAwXCJcbiAgICA6aGVpZ2h0PVwiNTAwXCJcbiAgICA6Zml4ZWQ9XCJmYWxzZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)`fixed``false``minWidth`

Sorry my network is restricted and cannot open element-plus.run.
Do you mean to set `fixed:false` for a column with `minWidth` set to take effect?

**Comment by btea** [comment]
I provided a screenshot, don't know if you can see it
![image](https://user-images.githubusercontent.com/24516654/185279680-bda8f480-edc2-4cdd-abab-6224de1c590c.png)

**Comment by kikyoluka** [comment]
> When `fixed` is set to `false`, `minWidth` will take effect. [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgZGF0YSA9IFtcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG4gIHtcbiAgIGRldklkOjEyMyxcbiAgIGlwOicxMC4yMTUuMjMzLjEnLFxuICAgbGluZToxNzJcbiB9LFxuICB7XG4gICBkZXZJZDoxMjMsXG4gICBpcDonMTAuMjE1LjIzMy4xJyxcbiAgIGxpbmU6MTcyXG4gfSxcbiAge1xuICAgZGV2SWQ6MTIzLFxuICAgaXA6JzEwLjIxNS4yMzMuMScsXG4gICBsaW5lOjE3MlxuIH0sXG5dO1xuY29uc3QgY29sdW1ucyA9IFtcbiAgIHtcbiAgICBrZXk6ICdkZXZJZCcsXG4gICAgdGl0bGU6ICdkZXZJZCcsXG4gICAgZGF0YUtleTogJ2RldklkJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDE2MCxcbiAgICBtaW5XaWR0aDozMDAsXG4gIH0sXG4gIHtcbiAgICBrZXk6ICdpcCcsXG4gICAgdGl0bGU6ICdpcCcsXG4gICAgZGF0YUtleTogJ2lwJyxcbiAgICBhbGlnbjogJ2NlbnRlcicsXG4gICAgd2lkdGg6IDEyMCxcbiAgfSxcbiAge1xuICAgIGtleTogJ2xpbmUnLFxuICAgIHRpdGxlOiAnbGluZScsXG4gICAgZGF0YUtleTogJ2xpbmUnLFxuICAgIGFsaWduOiAnY2VudGVyJyxcbiAgICB3aWR0aDogMTAwLFxuICB9LFxuIF1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZS12MlxuICAgIDpjb2x1bW5zPVwiY29sdW1uc1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6d2lkdGg9XCIxMDAwXCJcbiAgICA6aGVpZ2h0PVwiNTAwXCJcbiAgICA6Zml4ZWQ9XCJmYWxzZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by kikyoluka** [comment]
> I provided a screenshot, don't know if you can see it ![image](https://user-images.githubusercontent.com/24516654/185279680-bda8f480-edc2-4cdd-abab-6224de1c590c.png)

thanks, i see
