### ISSUE TITLE
[Style] [rate] ios 14 端包括 mac os下 safari浏览器会显示蓝色边框

### ISSUE THREAD

**Issue by shikoyi** [element-plus/element-plus#9364]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.24`
- Element Plus Version: `2.0.5`
- Browser / OS: `safari and ios 14`
- Build Tool: `Webpack`

### Related Component

- `el-rate`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/rate.html)

### Steps to reproduce

点击评分

### What is Expected?

修复显示边框bug

### What is actually happening?

会显示淡蓝色边框

### Additional comments

_(empty)_

**Comment by Tsong-LC** [comment]
Can't reproduce.👀
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/50739490/185523864-dcb6c461-46cd-4ab2-bd5f-6a85c2943135.png">

**Comment by baiwusanyu-c** [comment]
Can't reproduce.👀
<img width="1080" alt="截屏2022-08-19 23 43 54" src="https://user-images.githubusercontent.com/32354856/185656796-003af0d6-73cd-40e0-ae2a-f034d929683b.png">

**Comment by chenxch** [comment]
需要自行处理一下outline哦
