### ISSUE TITLE
[Style] [table] 表格 - 树形数据（icon出错的问题）

### ISSUE THREAD

**Issue by laobieyi** [element-plus/element-plus#9367]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMjBweFwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJkYXRlXCIgc29ydGFibGUgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHNvcnRhYmxlIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuXG4gICAgPGVsLXRhYmxlXG4gICAgICA6ZGF0YT1cInRhYmxlRGF0YTFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBsYXp5XG4gICAgICA6bG9hZD1cImxvYWRcIlxuICAgICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nLCBoYXNDaGlsZHJlbjogJ2hhc0NoaWxkcmVuJyB9XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW50ZXJmYWNlIFVzZXIge1xuICBpZDogbnVtYmVyXG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVXNlcltdXG59XG5cbmNvbnN0IGxvYWQgPSAoXG4gIHJvdzogVXNlcixcbiAgdHJlZU5vZGU6IHVua25vd24sXG4gIHJlc29sdmU6IChkYXRlOiBVc2VyW10pID0+IHZvaWRcbikgPT4ge1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICByZXNvbHZlKFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMxLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMzEsXG4gICAgICAgICAgICBkYXRlOiAnMzExJyxcbiAgICAgICAgICAgIG5hbWU6ICczMTEnLFxuICAgICAgICAgICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDMyLFxuICAgICAgICAgICAgZGF0ZTogJzMyMScsXG4gICAgICAgICAgICBuYW1lOiAnMzIyJyxcbiAgICAgICAgICAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMyLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgIH0sXG4gICAgXSlcbiAgfSwgMTAwMClcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBpZDogMSxcbiAgICBkYXRlOiAnMScsXG4gICAgbmFtZTogJzEnLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGRhdGU6ICczJyxcbiAgICBuYW1lOiAnMycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMxLFxuICAgICAgICBkYXRlOiAnMzEnLFxuICAgICAgICBuYW1lOiAnMzF1JywgXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDMxLFxuICAgICAgICAgICAgZGF0ZTogJzMxMScsXG4gICAgICAgICAgICBuYW1lOiAnMzExJyxcbiAgICAgICAgICAgIFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDMyLFxuICAgICAgICAgICAgZGF0ZTogJzMyMScsXG4gICAgICAgICAgICBuYW1lOiAnMzIyJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMyLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG5dXG5cbmNvbnN0IHRhYmxlRGF0YTE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAzMSxcbiAgICAgICAgICAgIGRhdGU6ICczMTEnLFxuICAgICAgICAgICAgbmFtZTogJzMxMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMzIsXG4gICAgICAgICAgICBkYXRlOiAnMzIxJyxcbiAgICAgICAgICAgIG5hbWU6ICczMjInLFxuICAgICAgICAgICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gIH0sXG4gIHtcbiAgICBpZDogNCxcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

data数据中的结构三级以上结构

### What is Expected?

孩子节点的icon是否展开应该完全跟 hasChildren 关联

### What is actually happening?

三级结构时样式出现问题

### Additional comments

_(empty)_

**Comment by laobieyi** [comment]
链接中的311一行不应该出现展开icon图标

**Comment by btea** [comment]
你应该让每个节点的id保持唯一
![image](https://user-images.githubusercontent.com/24516654/185522691-f51f2572-c272-4f1d-856c-83ced837dd09.png)

**Comment by laobieyi** [comment]
可是设置完，hasChildren 设置为false还是会出现没有子节点，仍然出现icon的情况

**Comment by btea** [comment]
我试了好像是正常的 [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMjBweFwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJkYXRlXCIgc29ydGFibGUgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHNvcnRhYmxlIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuXG4gICAgPGVsLXRhYmxlXG4gICAgICA6ZGF0YT1cInRhYmxlRGF0YTFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBsYXp5XG4gICAgICA6bG9hZD1cImxvYWRcIlxuICAgICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nLCBoYXNDaGlsZHJlbjogJ2hhc0NoaWxkcmVuJyB9XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW50ZXJmYWNlIFVzZXIge1xuICBpZDogbnVtYmVyXG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVXNlcltdXG59XG5cbmNvbnN0IGxvYWQgPSAoXG4gIHJvdzogVXNlcixcbiAgdHJlZU5vZGU6IHVua25vd24sXG4gIHJlc29sdmU6IChkYXRlOiBVc2VyW10pID0+IHZvaWRcbikgPT4ge1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICByZXNvbHZlKFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMxLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMzExLFxuICAgICAgICAgICAgZGF0ZTogJzMxMScsXG4gICAgICAgICAgICBuYW1lOiAnMzExJyxcbiAgICAgICAgICAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAzMTIsXG4gICAgICAgICAgICBkYXRlOiAnMzIxJyxcbiAgICAgICAgICAgIG5hbWU6ICczMjInLFxuICAgICAgICAgICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgfSxcbiAgICBdKVxuICB9LCAxMDAwKVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcxJyxcbiAgICBuYW1lOiAnMScsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzMnLFxuICAgIG5hbWU6ICczJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6ICczMScsXG4gICAgICAgIG5hbWU6ICczMXUnLCBcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMzExLFxuICAgICAgICAgICAgZGF0ZTogJzMxMScsXG4gICAgICAgICAgICBuYW1lOiAnMzExJyxcbiAgICAgICAgICAgIGhhc0NoaWxkcmVuOiBmYWxzZVxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDMxMixcbiAgICAgICAgICAgIGRhdGU6ICczMjEnLFxuICAgICAgICAgICAgbmFtZTogJzMyMicsXG4gICAgICAgICAgICBoYXNDaGlsZHJlbjogdHJ1ZVxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgfSxcbl1cblxuY29uc3QgdGFibGVEYXRhMTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDMxLFxuICAgICAgICAgICAgZGF0ZTogJzMxMScsXG4gICAgICAgICAgICBuYW1lOiAnMzExJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAzMixcbiAgICAgICAgICAgIGRhdGU6ICczMjEnLFxuICAgICAgICAgICAgbmFtZTogJzMyMicsXG4gICAgICAgICAgICAgaGFzQ2hpbGRyZW46IHRydWUsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by laobieyi** [comment]
![Uploading image.png…]()  :tree-props="{ children: 'countyList', hasChildren: 'hasChildren' }" 加了还是会有错误

**Comment by chenxch** [comment]
@laobieyi 你311的id为31和父级的id相同了哦
