### ISSUE TITLE
[Component] [transfer] el-transfer的clearQuery方法不生效

### ISSUE THREAD

**Issue by stdue** [element-plus/element-plus#9370]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `edge/windows`
- Build Tool: `Vite`

### Related Component

- `el-transfer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZixyZWFjdGl2ZSwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgdHJhbnNSZWYgPSByZWYoKTtcbmNvbnN0IHRyYW5zZmVyID0gcmVhY3RpdmUoe1xuICB2YWx1ZTpcIlwiLFxuICBkYXRhOltcbiAgICB7bGFiZWw6XCJvbmVcIix2YWx1ZTpcIjFcIn0sXG4gICAge2xhYmVsOlwidHdvXCIsdmFsdWU6XCIyXCJ9LFxuICBdXG59KTtcbmNvbnN0IGNsZWFyQ2xpY2sgPSAoKT0+e1xuICBjb25zb2xlLmxvZyhcIuWHuuWPkVwiKVxuICB0cmFuc1JlZi52YWx1ZS5jbGVhclF1ZXJ5KCdyaWdodCcpO1xufVxuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiBcdDxlbC10cmFuc2ZlciB2LW1vZGVsPVwidHJhbnNmZXIudmFsdWVcIiA6ZGF0YT1cInRyYW5zZmVyLmRhdGFcIiByZWY9XCJ0cmFuc1JlZlwiIDpwcm9wcz1cIntrZXk6J3ZhbHVlJyxsYWJlbDonbGFiZWwnfVwiPlxuICBcdDx0ZW1wbGF0ZSAjcmlnaHQtZm9vdGVyPlxuICAgIFx0PGVsLWJ1dHRvbiBAY2xpY2s9XCJjbGVhckNsaWNrXCI+56Gu5a6aPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10cmFuc2Zlcj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在穿梭框右边有内容后，点击“清除”按钮

### What is Expected?

右边的数据被清理掉

### What is actually happening?

没有反应

### Additional comments

_(empty)_

**Comment by btea** [comment]
`clearQuery` 方法是用来清除对应的面板输入框的搜索关键词的。
