### ISSUE TITLE
[Component] [date-picker] DateTimePicker 快捷选当前时间 不正确

### ISSUE THREAD

**Issue by gaga-change** [element-plus/element-plus#9379]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.13`
- Browser / OS: ` Chrome/104.0.5112.81`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRldGltZS1waWNrZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiYmxvY2tcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPkVtaXRzIERhdGUgb2JqZWN0PC9zcGFuPlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5WYWx1ZToge3sgdmFsdWUxIH19PC9kaXY+XG4gICAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICAgIHR5cGU9XCJkYXRldGltZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIERhdGVcIlxuICAgICAgICBmb3JtYXQ9XCJZWVlZL01NL0REIGhoOm1tOnNzXCJcbiAgICAgIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImJsb2NrXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5Vc2UgdmFsdWUtZm9ybWF0PC9zcGFuPlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5WYWx1Ze+8mnt7IHZhbHVlMiB9fTwvZGl2PlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBEYXRlXCJcbiAgICAgICAgZm9ybWF0PVwiWVlZWS9NTS9ERCBoaDptbTpzc1wiXG4gICAgICAgIHZhbHVlLWZvcm1hdD1cIllZWVktTU0tREQgaDptOnMgYVwiXG4gICAgICAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+VGltZXN0YW1wPC9zcGFuPlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5WYWx1Ze+8mnt7IHZhbHVlMyB9fTwvZGl2PlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTNcIlxuICAgICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBEYXRlXCJcbiAgICAgICAgZm9ybWF0PVwiWVlZWS9NTS9ERCBoaDptbTpzc1wiXG4gICAgICAgIHZhbHVlLWZvcm1hdD1cInhcIlxuICAgICAgLz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoJycpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5jb25zdCB2YWx1ZTMgPSByZWYoJycpXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1kYXRldGltZS1waWNrZXIge1xuICBkaXNwbGF5OiBmbGV4O1xuICB3aWR0aDogMTAwJTtcbiAgcGFkZGluZzogMDtcbiAgZmxleC13cmFwOiB3cmFwO1xufVxuLmRlbW8tZGF0ZXRpbWUtcGlja2VyIC5ibG9jayB7XG4gIHBhZGRpbmc6IDMwcHggMDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBib3JkZXItcmlnaHQ6IHNvbGlkIDFweCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBmbGV4OiAxO1xufVxuLmRlbW8tZGF0ZXRpbWUtcGlja2VyIC5ibG9jazpsYXN0LWNoaWxkIHtcbiAgYm9yZGVyLXJpZ2h0OiBub25lO1xufVxuLmRlbW8tZGF0ZXRpbWUtcGlja2VyIC5kZW1vbnN0cmF0aW9uIHtcbiAgZGlzcGxheTogYmxvY2s7XG4gIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgbWFyZ2luLWJvdHRvbTogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

下午16点.打开弹窗,点击此刻

### What is Expected?

显示16点几分几秒

### What is actually happening?

显示04点几分几秒

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/21301350/185578883-7effedef-b60f-4a61-9dcc-264f1e7cfcd7.png)

**Comment by btea** [comment]
请参考[格式](https://day.js.org/docs/en/display/format#list-of-all-available-formats)

**Comment by gaga-change** [comment]
感觉不是格式的问题
这个图是文档里案例截图, 输入框显示的和打印出来的值不一致
![image](https://user-images.githubusercontent.com/21301350/185581177-2cb45b25-11fa-4bf1-8339-a258ec282462.png)

**Comment by btea** [comment]
![image](https://user-images.githubusercontent.com/24516654/185581628-8589a031-a165-40e4-adfa-b2dcc08f9913.png)
h小写是12小时制，大写是24小时

**Comment by MARIOMARUI** [comment]
楼上说的没错，应该使用 HH

**Comment by gaga-change** [comment]
明白了,谢谢!
