### ISSUE TITLE
calendar 组件头部可以支持插槽吗？

### ISSUE THREAD

**Issue by wukang0718** [element-plus/element-plus#938]
### calendar 组件头部可以支持插槽吗？
![image](https://user-images.githubusercontent.com/42261663/101712709-19c74e00-3ad1-11eb-8710-4e2b22214a6b.png)

**Comment by JeremyWuuuuu** [comment]
@zazzaz

**Comment by zazzaz** [comment]
What kind of slot are you looking for.

Any screenshot or demo, please?

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/101718151-9a8b4780-3adb-11eb-9d6d-9922e01c06a3.png)
```
<el-calendar>
  <template #header>
    <span>这是自定义的头部内容</span>
    <span>{{new Date().getFullYear()}}年{{new Date().getMonth() + 1}}月</span>
    <div>
      <el-button-group>
        <el-button type="primary">前一年</el-button>
        <el-button type="primary">前一个月</el-button>
        <el-button type="primary">当前月份</el-button>
        <el-button type="primary">后一个月</el-button>
        <el-button type="primary">后一年</el-button>
      </el-button-group>
    </div>
  </template>
</el-calendar>
```
I want to be able to customize the header this way  
I also want to be able to support the choice of year and month
![image](https://user-images.githubusercontent.com/42261663/101718372-01106580-3adc-11eb-8f47-58eacb73778e.png)
![image](https://user-images.githubusercontent.com/42261663/101718527-59476780-3adc-11eb-9289-fe5d757a5a1a.png)

**Comment by zazzaz** [comment]
I'll mark this as a feature request to see if anyone needs this as well.

**Comment by 12Tall** [comment]
looking forward this feature too
