### ISSUE TITLE
[Build] [All] 在最新的nuxt3版本rc-8中使用element-plus报错，没法使用

### ISSUE THREAD

**Issue by KahrLu** [element-plus/element-plus#9394]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `chrome`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/KahrLu/nuxt-setupContext-issue)

### Steps to reproduce

1、yarn install
2、yarn build
3、yarn preview

### What is Expected?

一个正常的页面

### What is actually happening?

500
Cannot read property 'setupContext' of null
![image](https://user-images.githubusercontent.com/76502123/185728248-2e61e568-500a-44f4-848b-e62d1f17e0c8.png)

### Additional comments

https://github.com/element-plus/element-plus-nuxt-starter 这个项目能不能尽快跟进一下nuxt3的最新预览版。因为rc-8比较关键，升级了Vite3

另外例子中的组件都是在页面上单独引用的，能提供一个在nuxt中全量引入或者auto-import的例子吗？不然覆盖不到大多数的实际使用情况

**Comment by KahrLu** [comment]
直接
`import ElementPlus from 'element-plus'
export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(ElementPlus)
})`

也是一样报这个错

**Comment by Felix19901229** [comment]
可以正常工作啊，https://github.com/element-plus/element-plus-nuxt-starter 这个工程过时了，建议去看NUXT3最新文档。

**Comment by sxzz** [comment]
Please try the latest template.
