### ISSUE TITLE
[Component] [All] ElNotification.closeAll()无效

### ISSUE THREAD

**Issue by darkknightxb** [element-plus/element-plus#9398]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW5cIj4gT3BlbiA8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJjbG9zZVwiPiBDbG9zZSA8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBFbE5vdGlmaWNhdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxOb3RpZmljYXRpb24oe1xuICAgIHRpdGxlOiAnUHJvbXB0JyxcbiAgICBtZXNzYWdlOiAnVGhpcyBpcyBhIG1lc3NhZ2UgdGhhdCBkb2VzIG5vdCBhdXRvbWF0aWNhbGx5IGNsb3NlJ1xuICB9KVxufVxuXG5jb25zdCBjbG9zZSA9ICgpPT57XG4gIEVsTm90aWZpY2F0aW9uLmNsb3NlQWxsKClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击open，然后点击close

### What is Expected?

关闭通知

### What is actually happening?

无效

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
你是在项目中使用遇到这个情况了么？我将代码复制到项目中是正常的。

**Comment by daonatural** [comment]
在正式的使用中貌似是存在问题的， 关闭操作不生效
https://codesandbox.io/s/element-demo-u5uuub?file=/src/App.vue

**Comment by chenxch** [comment]
![notice](https://user-images.githubusercontent.com/23251408/186092133-bce9ed3c-87dd-4868-af96-43eb4b0a59e9.gif)
这是我本地测试的，你的demo确实是不生效，这个问题我晚点在看下是什么原因

**Comment by chenxch** [comment]
已经定位到这个问题是在2.2.12版本之后出现的，原因还在确认中哈。
