### ISSUE TITLE
ElSelect multiple 多选模式

### ISSUE THREAD

**Issue by henrybryanRYan** [element-plus/element-plus#940]
2020-12-10

版本号： @1.0.1-beta.6

1、选中一个不展示 大于一个展示
2、删除最后一个选项无法删除

期望：
操作正常

**Comment by porcelainHeart** [comment]
Known issues.
Duplicate of #874

**Comment by henrybryanRYan** [comment]
> 已知的问题。[＃874的](https://github.com/element-plus/element-plus/issues/874)
> 重复项[](https://github.com/element-plus/element-plus/issues/874)

此问题合适能解决？
数据更新了 视图未更新

**Comment by JeremyWuuuuu** [comment]
Fixed in #941 will be released in next version
