### ISSUE TITLE
[Component] [form-item] Form item rules 在其 required 每次改变后都无意义地增加一项 

### ISSUE THREAD

**Issue by gadzan** [element-plus/element-plus#9401]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBmb3JtID0gcmVmKHtcbiAgbXNnOiAnSGVsbG8gV29ybGQhJ1xufSk7XG4gIFxuY29uc3QgaXRlbVJ1bGVzID0gcmVmKFtdKTtcbiAgXG5jb25zdCBpdGVtUmVxdWlyZWQgPSByZWYoZmFsc2UpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8cD5cbiAgICBDaGFuZ2UgRm9ybSBpdGVtIHJlcXVpcmVkLCBmb3JtIGl0ZW0gcnVsZXMgd2lsbCBncm93O1xuICA8L3A+XG4gIDxlbC1mb3JtIDpmb3JtPVwiZm9ybVwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJGb3JtIGl0ZW0gcmVxdWlyZWRcIj5cbiAgICBcdDxlbC1zd2l0Y2ggdi1tb2RlbD1cIml0ZW1SZXF1aXJlZFwiPjwvZWwtc3dpdGNoPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICBcdDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJNZXNzYWdlXCIgOnJlcXVpcmVkPVwiaXRlbVJlcXVpcmVkXCIgOnJ1bGVzPVwiaXRlbVJ1bGVzXCIgPlxuICBcdFx0PGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm1zZ1wiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbiAgPHAgdi1mb3I9XCJydWxlIGluIGl0ZW1SdWxlc1wiPlxuICBcdHt7IHJ1bGUgfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

每次改变 Form item 的 Required 属性，Form item 的 rules 都会无意义地增加一项

### What is Expected?

Form item 的 Required 属性改变后只会影响最后一项 From item rules，为空时才增加一项

### What is actually happening?

改变 Form item 的 Required 属性，Form item 的 rules 会无意义地增长

### Additional comments

_(empty)_

**Comment by gadzan** [comment]
我的PR已经解决这个问题
https://github.com/element-plus/element-plus/pull/9392

**Comment by gadzan** [comment]
我一早提的pr没人看，提个issue，团队自己去修复了，呵呵

**Comment by chenxch** [comment]
下次记得关联一下，避免重复修复。

**Comment by gadzan** [comment]
> 下次记得关联一下，避免重复修复。

所以你们都不看pr的？？
