### ISSUE TITLE
[Component] [popover, select] el-popover内有select的时候在选择后会自动关闭

### ISSUE THREAD

**Issue by PeyFon** [element-plus/element-plus#9404]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `版本 102.0.5005.115（正式版本） （64 位）`
- Build Tool: `Vue CLI`

### Related Component

- `el-popover`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImNsaWNrXCJcbiAgPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj7mkJzntKI8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+6YeN572uPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuXG5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjEnLFxuICAgIGxhYmVsOiAnT3B0aW9uMScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjInLFxuICAgIGxhYmVsOiAnT3B0aW9uMicsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjMnLFxuICAgIGxhYmVsOiAnT3B0aW9uMycsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjQnLFxuICAgIGxhYmVsOiAnT3B0aW9uNCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sXG5dXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

选择某个选项后会自动关闭

### What is Expected?

选择后不自动关闭，等点击按钮后再去触发组件内的关闭方法。

### What is actually happening?

自动关闭

### Additional comments

这个问题当初在elementui的时候还没有。

**Comment by chenxch** [comment]
可以先使用受控模式哈 [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgOnZpc2libGU9XCJ2aXNpYmxlXCJcbiAgPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlPWZhbHNlXCI+5pCc57SiPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiaW5mb1wiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlPXRydWVcIj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by PeyFon** [comment]
> 可以先使用受控模式哈 [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgOnZpc2libGU9XCJ2aXNpYmxlXCJcbiAgPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlPWZhbHNlXCI+5pCc57SiPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiaW5mb1wiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlPXRydWVcIj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

希望尽快修改，因为还需要实现点击其它地方让它给自动收起

**Comment by daonatural** [comment]
默认情况下，`select `的下拉框dom是添加到`body`元素中的，这就导致虽然视图层面看，`select` 下拉框在 `popover body`里面，但实际上他们是dom关系是兄弟元素，所以点击下拉框的行为对于 `popover `而言，和在`popover`外面鼠标点击的行为是一致的。这就导致popover也关闭了。

尝试解决方法：将 select 组件的 `teleported`属性设置为`false`，使得它的下拉框被渲染在`popover`内部

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImNsaWNrXCJcbiAgPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDp0ZWxlcG9ydGVkPVwiZmFsc2VcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+5pCc57SiPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiaW5mb1wiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by PeyFon** [comment]
> teleported

多谢大佬指点

**Comment by PeyFon** [comment]
> 默认情况下，`select `的下拉框dom是添加到`body`元素中的，这就导致虽然视图层面看，`select` 下拉框在 `popover body`里面，但实际上他们是dom关系是兄弟元素，所以点击下拉框的行为对于 `popover `而言，和在`popover`外面鼠标点击的行为是一致的。这就导致popover也关闭了。
> 
> 尝试解决方法：将 select 组件的 `teleported`属性设置为`false`，使得它的下拉框被渲染在`popover`内部
> 
> [Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImNsaWNrXCJcbiAgPlxuICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgY2xhc3M9XCJtLTJcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDp0ZWxlcG9ydGVkPVwiZmFsc2VcIj5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+5pCc57SiPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiaW5mb1wiPumHjee9rjwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj5DbGljayB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

多谢大佬指点

**Comment by aborn** [comment]
参考解决思路：
https://zhonghuitech.github.io/vfg/#/popover
