### ISSUE TITLE
[Component] NUXT3中含有el-tooltip所有组件服务器渲染异常

### ISSUE THREAD

**Issue by Felix19901229** [element-plus/element-plus#9414]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Microsoft Edge 104.0.1293.63`
- Build Tool: `Nuxt`

### Related Component

- `el-select`
- `el-tooltip`
- `el-select-v2`
- `el-tooltip-v2`

### Reproduction Link

[Github Repo](https://github.com/Felix19901229/element-plus-bug.git)

### Steps to reproduce

两个以上ElSelect数据会被合并成一个弹窗显示。
两个以上ElTooltip,只有用户最先选中的组件正常工作，其他均报错失效。

### What is Expected?

两个以上ElSelect的弹窗独立显示，数据相互独立。
两个以上ElTooltip均能独立正常工作。

### What is actually happening?

两个以上ElSelect,弹窗数据被合并。
两个以上ElTooltip,只有一个工作。

### Additional comments

_(empty)_

**Comment by Vic1228** [comment]
我目前將SSR設定為false來解決此問題

**Comment by Felix19901229** [comment]
使用NUXT3的目的就是为了SSR，关闭SSR是没有任何意义的。目前只能将含有tooltip的部分交给客户端渲染，即加入到ClientOnly之中。

**Comment by jwhgzs** [comment]
官方一直没解决这个问题啊，今年三月就有人提了，当时让加<client-only>凑个数，结果五个月了，还没解决。。。
今天被坑了一个下午，结果是ElementPlus的BUG。。。

**Comment by Nisekoi5** [comment]
不只是NUXT,使用原生开发也一样。所有使用了teleport的组件都会出现错误
只能自己做个client-only组件 放到客户端去渲染了.
