### ISSUE TITLE
[Build] [All] Nuxt hydration failed (component - Menu): Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom

### ISSUE THREAD

**Issue by adminoid** [element-plus/element-plus#9418]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/menu.html)

### Steps to reproduce

just use menu component in nuxt, without client-only

### What is Expected?

I want to nuxt rightly hydrated menu component (with submenu)

### What is actually happening?

I've got a error:
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <ElTooltipContent ref="contentRef" aria-label=undefined boundaries-padding=0  ... > 
  at <ElPopperRoot ref="popperRef" role="tooltip" > 
  at <ElTooltip ref=Ref< null > visible=false effect="light"  ... > 
  at <ElSubMenu index="1" > 

### Additional comments

_(empty)_

**Comment by gwwnha** [comment]
Same error

**Comment by alexisdechiara** [comment]
I have the same error

**Comment by zhf0437** [comment]
me too

**Comment by digitalniweb** [comment]
So this will never be fixed? That is quiet a huge bug. Guess I'll check for other component library.
