### ISSUE TITLE
Popover with border

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#942]
Most components with light effect popver has a border. But the `el-popver` itself has no border. I notice that the style `is-pure` remove the border and padding, many components with `is-pure` also add a border. I think is it possible to remove the `border: none` of `is-pure`. The `is-pure` only has a `padding: 0`.
![image](https://user-images.githubusercontent.com/38392315/101721087-1c7e6f00-3ae2-11eb-9a04-3b6027470f7a.png)

**Comment by JeremyWuuuuu** [comment]
Well, you are right, popover do have borders, I just confirmed that, do you want to make a PR for this?

**Comment by kooriookami** [comment]
> Well, you are right, popover do have borders, I just confirmed that, do you want to make a PR for this?

Yes, I do.

**Comment by JeremyWuuuuu** [comment]
Nice, open a PR and link this issue with it.
