### ISSUE TITLE
[Component] [notification] notification 手动调用close，无法关闭

### ISSUE THREAD

**Issue by lianzhidong** [element-plus/element-plus#9427]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.2.13`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-notification`

### Reproduction Link

[Link]()

### Steps to reproduce

1、调用ElNotification创建通知，将返回值保存为instance
2、调用instance.close进行关闭

### What is Expected?

通知关闭

### What is actually happening?

未关闭

### Additional comments

在2.1.12版本可以正常关闭，2.1.13的更新日志中，Components [notification] switch to script-setup syntax (#9106 by @holazz)，重构了notification，2.1.13和2.1.14皆无法关闭

**Comment by holazz** [comment]
Maybe fix by https://github.com/element-plus/element-plus/pull/9417
