### ISSUE TITLE
el-select 多选时无法删除最后一个标签

### ISSUE THREAD

**Issue by sufengyong** [element-plus/element-plus#944]
version: 1.0.1-beta.6
el-select，多选,，选择多个时无法删除最后一个

demo: https://element-plus.org/#/zh-CN/component/select  官方文档，下拉框 -> 基础多选 可复现

**Comment by JeremyWuuuuu** [comment]
Fixed in #941 has not been released yet

**Comment by JeremyWuuuuu** [comment]
Also duplicated in #874 #940
