### ISSUE TITLE
About el-select 

### ISSUE THREAD

**Issue by MQYForverT** [element-plus/element-plus#945]
when useing remote search to get the options（options：ref([])）

the el-options cant't work

**Comment by JeremyWuuuuu** [comment]
Please provide some demo for debugging

**Comment by MQYForverT** [comment]
version：^1.0.1-beta.6

<template>
	<el-select
		ref="headerSearchSelect"
		v-model="search"
		:remote-method="querySearch"
		filterable
		default-first-option
		remote
		placeholder="Search"
		class="header-search-select"
		@change="change"
	>
		<el-option v-for="item in options" :key="item.path" :value="item" :label="item.title.join(' > ')" />
	</el-select>
</template>	

<script lang="ts">
import { defineComponent, ref} from 'vue'

export default defineComponent({
	name: 'HeaderSearch',
	setup(props, context) {
		let search = ref('')
		let options = ref([])
		let headerSearchSelect = ref(null)

		function change(route: RouteRecordRaw) {

		}

		function querySearch(query: string) {
			options.value = [{ path: '/nested/menu1/menu1-1', title: ['路由嵌套', '菜单 1', '菜单 1-1'] }]
		}

		return {
			headerSearchSelect,
			options,
			search,
			querySearch,
			change
		}
	}
})
</script>

Expected results：When I enter a random value，I'll give option a value，then the el-option should be rendered。

Actual results：will throw out a err：Cannot read property '0' of null

**Comment by JeremyWuuuuu** [comment]
Oh, about that. This issue is related to `Vue` instead of us, they have made some changes of their own introduces bug like you have shown. When you load a list with the list value gets assigned asynchronously, it gets broken. Refer to the issue here: https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8

**Comment by JeremyWuuuuu** [comment]
The only way here to solve this is to wait until they release `3.0.5`

**Comment by MQYForverT** [comment]
ok，thanks

**Comment by JeremyWuuuuu** [comment]
Closing since this was a bug from `Vue`
