### ISSUE TITLE
[Component] [dialog] el-dailog  v-bind="$attrs"  非 props属性 报警告问题

### ISSUE THREAD

**Issue by Corgis** [element-plus/element-plus#9450]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Google Chrome 版本 104.0.5112.102`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/funny-marco-u711h7?file=/src/components/HelloWorld.vue)

### Steps to reproduce

打开上述在线编辑器的链接，打开编辑器的console控制台
el-dialog组件在HelloWorld里引用  App.vue中引用该HelloWorld组件 并设置 style="height: 100px"
如下图所示：
[![vggEU1.md.jpg](https://s1.ax1x.com/2022/08/25/vggEU1.jpg)

### What is Expected?

不会报该警告

### What is actually happening?

报警告

### Additional comments

例如我使用 el-table v-bind="$attrs" 则不会报该警告
el-table组件在HelloWorld里引用  App.vue中引用该HelloWorld组件 并设置style="height: 100px"
代码示例链接如下：
https://codesandbox.io/s/brave-newton-l50lvo?file=/src/components/HelloWorld.vue

![1234](https://user-images.githubusercontent.com/13865529/186559701-94f13b94-3bf7-479a-9c54-d1c969685c9e.jpg)

**Comment by Corgis** [comment]
我重新安装了 element-plus 到2.2.15 还是会报这个错  引用组件 设置 style  
![image](https://user-images.githubusercontent.com/13865529/187124579-10203e23-366b-4eb1-b551-0974ec8fee3c.png)

**Comment by sxzz** [comment]
Wait for next release version
