### ISSUE TITLE
[Component] [table] shallowRef 类型数据 triggerRef 触发后Table数据未更新

### ISSUE THREAD

**Issue by WoJiaoFuXiaoYun** [element-plus/element-plus#9454]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Edg/104.0.1293.63 / WIN 11`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNoYWxsb3dSZWYsdHJpZ2dlclJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdGFibGVEYXRhID1zaGFsbG93UmVmKFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfVxuXSlcblxuc2V0VGltZW91dCgoKT0+e1xuICB0YWJsZURhdGEudmFsdWVbMF0ubmFtZSA9ICdCb2InXG4gIHRyaWdnZXJSZWYodGFibGVEYXRhKVxufSwyMDAwKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cHJlPlxuICAgIHt7dGFibGVEYXRhWzBdfX1cbiAgPC9wcmU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

打开等待两秒后，shallowRef更新，页面Table未更新

### What is Expected?

Table name 变为 Bob

### What is actually happening?

Table name 未更新

### Additional comments

_(empty)_

**Comment by holazz** [comment]
使用 ref

**Comment by dreambo8563** [comment]
```js
setTimeout(()=>{  
  const first = tableData.value[0]
  first.name = 'Bob'
  tableData.value=[first]
 // triggerRef(tableData)
},2000)
```

>Unlike ref(), the inner value of a shallow ref is stored and exposed as-is, and will not be made deeply reactive. Only the .value access is reactive.

https://vuejs.org/api/reactivity-advanced.html#shallowref
