### ISSUE TITLE
[Component] [time-picker] TimePicker 在有值的情况下 修改endTime 结束时间无法触发 change 事件

### ISSUE THREAD

**Issue by wpc669418** [element-plus/element-plus#9460]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 / Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Webpack`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1yYW5nZVwiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBpcy1yYW5nZVxuICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCB0aW1lXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgICBAY2hhbmdlPVwiaGFuZGxlVGltZUNoYW5nZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaGFuZGxlVGltZUNoYW5nZSA9KGUpPT57XG4gIGNvbnNvbGUubG9nKGUpXG59XG5jb25zdCB2YWx1ZTEgPSByZWYoW25ldyBEYXRlKDIwMTYsIDksIDEwLCA4LCA0MCksIG5ldyBEYXRlKDIwMTYsIDksIDEwLCA5LCA0MCldKVxuY29uc3QgdmFsdWUyID0gcmVmKFtuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOCwgNDApLCBuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOSwgNDApXSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1yYW5nZSAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW46IDhweDtcbn1cblxuLmRlbW8tcmFuZ2UgLmVsLXJhbmdlLXNlcGFyYXRvciB7XG4gIGJveC1zaXppbmc6IGNvbnRlbnQtYm94O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.打开链接 ：https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1yYW5nZVwiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBpcy1yYW5nZVxuICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCB0aW1lXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgICBAY2hhbmdlPVwiaGFuZGxlVGltZUNoYW5nZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaGFuZGxlVGltZUNoYW5nZSA9KGUpPT57XG4gIGNvbnNvbGUubG9nKGUpXG59XG5jb25zdCB2YWx1ZTEgPSByZWYoW25ldyBEYXRlKDIwMTYsIDksIDEwLCA4LCA0MCksIG5ldyBEYXRlKDIwMTYsIDksIDEwLCA5LCA0MCldKVxuY29uc3QgdmFsdWUyID0gcmVmKFtuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOCwgNDApLCBuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOSwgNDApXSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1yYW5nZSAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW46IDhweDtcbn1cblxuLmRlbW8tcmFuZ2UgLmVsLXJhbmdlLXNlcGFyYXRvciB7XG4gIGJveC1zaXppbmc6IGNvbnRlbnQtYm94O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==
2.打开控制台
3.修改结束时间，点击确认

### What is Expected?

输出 change 的结果

### What is actually happening?

未输出结果

### Additional comments

修改开始时间是能够输出结果的

**Comment by HoneKKK** [comment]
请问有什么好办法解决吗？我现在也遇到这个问题

**Comment by muou2125** [comment]
可以暂时用watch处理

**Comment by muou2125** [comment]
> 请问有什么好办法解决吗？我现在也遇到这个问题

我暂时用的是watch处理的

**Comment by HoneKKK** [comment]
> > 请问有什么好办法解决吗？我现在也遇到这个问题
> 
> 我暂时用的是watch处理的

是的。但每一次修改都要进行一次操作就可能多花一丢丢资源。而且点击取消时要注意返回的是一个空字符而不是null。

**Comment by wpc669418** [comment]
> 

我发现 v-model 是能够直接获取的 ，没用到 change 事件，满足了我的业务需求 ，在我表单提交的时候，通过校验之后，进行值的拆解传给后端

**Comment by wpc669418** [comment]
> 请问有什么好办法解决吗？我现在也遇到这个问题



> Reference

我发现 v-model 是能够直接获取的 ，没用到 change 事件，满足了我的业务需求 ，在我表单提交的时候，通过校验之后，进行值的拆解传给后端
