### ISSUE TITLE
[Component] [input-number] Number Input can't handle , separated numbers

### ISSUE THREAD

**Issue by TimAufdemKampe** [element-plus/element-plus#9464]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Safari Version 15.6.1 (17613.3.9.1.16)`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-6zs9cs?file=/src/App.vue)

### Steps to reproduce

Typ 12,34 into the number input field

### What is Expected?

Accept this comma separated number as you would with dot separated numbers

### What is actually happening?

Nothing

### Additional comments

_(empty)_

**Comment by baiwusanyu-c** [comment]
I think the `12,34` is string,not number

**Comment by sechi747** [comment]
> I think the `12,34` is string,not number

In some contries, people are using commas as separators for numbers.

**Comment by holazz** [comment]
Use `el-input`'s `formatter` and `parser`.

https://element-plus.org/en-US/component/input.html#formatter

**Comment by chenxch** [comment]
Since the `input-number` component is implemented based on `type='number'`, other characters cannot be input. It is recommended to implement the function through the `input` `formatter`.
