### ISSUE TITLE
[Docs] [All] How to programmaticly open a submenu in vertical mode?

### ISSUE THREAD

**Issue by adminoid** [element-plus/element-plus#9468]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/menu.html)

### Steps to reproduce

How to programmatically open a submenu in vertical mode?

### What is Expected?

Need a method for ref="submenu"; const submenu = ref(null); submenu.open(index) for make opened a submenu

### What is actually happening?

I wasn't found that method...

### Additional comments

_(empty)_

**Comment by baiwusanyu-c** [comment]
You can try the `default-openeds`  property, I don't know if it suits your needs

**Comment by holazz** [comment]
https://element-plus.org/en-US/component/menu.html#menu-methods

`menu.open(subMenuIndex)`
