### ISSUE TITLE
[Style] [message-box] MessageBox 消息弹框 的modal层在手机上会出现横向 纵向滚动条

### ISSUE THREAD

**Issue by Lovecxgood** [element-plus/element-plus#9469]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.14`
- Browser / OS: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html)

### Steps to reproduce

$msgbox(options)
$alert(message, title, options) 或 $alert(message, options)
$confirm(message, title, options) 或 $confirm(message, options)
$prompt(message, title, options) 或 $prompt(message, options)

### What is Expected?

遮罩层无滚动条

### What is actually happening?

出现横向纵向滚动条

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
这是pc 端的

**Comment by tolking** [comment]
Link #8295

主要原因是部分手机上存在滚动条宽度计算结果和实际不符合的情况，如果有更好的方案，欢迎提供

**Comment by Lovecxgood** [comment]
.ep-overlay.is-message-box .ep-overlay-message-box {
text-align: center;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 16px;
    /* overflow: auto; */
}

.ep-overlay  你们把这个遮罩层的css 的 overflow: auto; 默认属性给注释掉 试试？

**Comment by Lovecxgood** [comment]
> Link #8295
> 
> 主要原因是部分手机上存在滚动条宽度计算结果和实际不符合的情况，如果有更好的方案，欢迎提供

.ep-overlay.is-message-box .ep-overlay-message-box {
text-align: center;
position: fixed;
top: 0;
right: 0;
bottom: 0;
left: 0;
padding: 16px;
/* overflow: auto; */
overflow: hidden ;
}

.ep-overlay 你们把这个遮罩层的css 的 overflow: auto; 默认属性给改成 overflow: hidden; 试试？

**Comment by lvjisong** [comment]
移动端不用vant用ele？

**Comment by baboon-king** [comment]
自己写定义样式，覆盖下吧。
