### ISSUE TITLE
请教：表单校验如何定义？

### ISSUE THREAD

**Issue by henrybryanRYan** [element-plus/element-plus#947]
请教：表单校验如何定义？

**Comment by JeremyWuuuuu** [comment]
https://element-plus.org/#/zh-CN/component/form

TL;DR

Form uses async-validator to validate inputs. 
Reference: [Async validator](https://github.com/yiminghe/async-validator)

**Comment by henrybryanRYan** [comment]
@JeremyWuuuuu 按照官方文档 改为 vue3 格式报错了，能否给个vue3表单验证的例子呢？

**Comment by JeremyWuuuuu** [comment]
The rule:
```ts
  name: [
            { required: true, message: '请输入活动名称', trigger: 'blur' },
            { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
          ],
```
When error
![image](https://user-images.githubusercontent.com/15975785/101729930-15f8f300-3af4-11eb-849d-659d3ec8d4e3.png)
When correct
![image](https://user-images.githubusercontent.com/15975785/101729958-1db89780-3af4-11eb-8c69-b20d90563f42.png)

**Comment by JeremyWuuuuu** [comment]
The example is already in the document site, check them out at the section of `表单验证(form-validation)`

**Comment by henrybryanRYan** [comment]
![1](https://user-images.githubusercontent.com/74169026/101732629-7be77980-3af8-11eb-8fb9-4b263663696b.png)
![2](https://user-images.githubusercontent.com/74169026/101732641-81dd5a80-3af8-11eb-9e84-b994a686a263.png)
![3](https://user-images.githubusercontent.com/74169026/101732650-8570e180-3af8-11eb-83f5-0bdf55d6d092.png)
![4](https://user-images.githubusercontent.com/74169026/101732659-886bd200-3af8-11eb-9803-e8bb6d9f07cb.png)

**Comment by henrybryanRYan** [comment]
Can you help to locate the cause of the error and how to modify it? thank you!

**Comment by JeremyWuuuuu** [comment]
Please watch the documentation before you write code. [Composition API](https://v3.vuejs.org/guide/composition-api-introduction.html), if you are not familiar with `Composition API` please go check it out. This is not a bug from us. Thank you

**Comment by JeremyWuuuuu** [comment]
We have been constantly asking for syntax issues because of `Composition API`, note that `Options API` is still out there, you can use it like you did before. Not everybody needs `VCA`. Documentations have been clear enough, we have already buried ourselves in fixing bugs/making optimizations, these kinds of questions are really not related to us. By reading documentation is a better way to support us for making this project better.

**Comment by henrybryanRYan** [comment]
After the "Model Rules" are removed, the data can be bound normally, but there is no verification function

**Comment by SimonaliaChen** [comment]
Please provide a whole minimal reproduction, best via https://codesandbox.io/s/crimson-hill-is5r0

**Comment by JeremyWuuuuu** [comment]
How to bind to to the template is as same as it was before, this is you now knowing how to produce the data via `VCA`, that is not our issue. Please go google that out or read the documentation I just sent you.

**Comment by JeremyWuuuuu** [comment]
https://element-plus.gitee.io/#/zh-CN/component/form You can see the form here is working just fine, so that proves the error was not from us, if it was, we will fix it.

**Comment by henrybryanRYan** [comment]
https://codesandbox.io/live/i6j3rh8

**Comment by SimonaliaChen** [comment]
@henrybryanRYan The cause of the error is that you bind `el-form` a unused ref named `ruleForm` which has conflict with reactive data. Change another name will work, Check [this](https://codesandbox.io/s/musing-waterfall-ps60f?file=/src/App.vue) out.

**Comment by henrybryanRYan** [comment]
@SimonaliaChen Thank you very much. The problem has been solved
