### ISSUE TITLE
[Docs] [cascader] element-plus官方文档 -> cascader -> teleported 属性介绍错误

### ISSUE THREAD

**Issue by zhangyongxuan** [element-plus/element-plus#9472]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `103.0.5060.114（正式版本）/ win10`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html#cascader-%E5%B1%9E%E6%80%A7)

### Steps to reproduce

element-plus官方文档 -> cascader -> teleported 属性介绍

### What is Expected?

element-plus官方文档 -> cascader -> teleported 属性介绍正确

### What is actually happening?

element-plus官方文档 -> cascader -> teleported 属性介绍错误

### Additional comments

_(empty)_
![QQ截图20220826111315](https://user-images.githubusercontent.com/47049216/186809898-686b9e2f-dc64-4c11-84f1-15d9b82c42a8.png)

**Comment by emojiiii** [comment]
翻译错了

**Comment by iamkun** [comment]
fixed
