### ISSUE TITLE
[Docs] [All] 中文网站访问404

### ISSUE THREAD

**Issue by liukang824** [element-plus/element-plus#9476]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: ` Win64; x64`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/icon.html#%E7%BB%93%E5%90%88-el-icon-%E4%BD%BF%E7%94%A8)

### Steps to reproduce

https://element-plus.org/zh-CN/component/icon.html#%E7%BB%93%E5%90%88-el-icon-%E4%BD%BF%E7%94%A8

### What is Expected?

能正常访问

### What is actually happening?

能正常访问

### Additional comments

_(empty)_

**Comment by fengfengchen** [comment]
遇到了同样的问题

**Comment by 1260692465** [comment]
一样的问题-打不开了，只有个别的能看

**Comment by sxzz** [comment]
Fixed.
