### ISSUE TITLE
[Component] [table] table display error 

### ISSUE THREAD

**Issue by html580** [element-plus/element-plus#9486]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/html580/pen/ZExNmQB)

### Steps to reproduce

CDN加速的表格显示异常，就是一普通的静态表格，不能正常显示，测试大部分版本都是异常的

### What is Expected?

希望显示成功

### What is actually happening?

显示失败

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
[vue docs](https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)

**Comment by html580** [comment]
https://codepen.io/html580/pen/ZExNmQB   看演示例子，不是说出不来，而是所有的例都转一个个tr 明显就是异常

**Comment by chenxch** [comment]
```vue
<el-table-column prop="date" label="Date" width="180"></el-table-column>
```

**Comment by html580** [comment]
![image](https://user-images.githubusercontent.com/4509324/187022612-be606520-ffd7-4d07-adb8-39d8e6383ff2.png)
https://element-plus.gitee.io/zh-CN/component/table.html#%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC
文档里可以支持这种写法，为什么这里不支持下呢

**Comment by chenxch** [comment]
> [vue docs](https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)

@html580  look here!
