### ISSUE TITLE
[Component] [upload] on-exceed hook doesn't work

### ISSUE THREAD

**Issue by jakmac5** [element-plus/element-plus#9489]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/upload.html#cover-previous-file)

### Steps to reproduce

1. click on https://element-plus.org/en-US/component/upload.html#cover-previous-file
2. add multiple files one by one
3. Observe that unlimited number of files can be uploaded

### What is Expected?

Previous files should be covered. Only one can be uploaded. on-exceed hook is not even called.

### What is actually happening?

unlimited number of files can be uploaded. on-exceed hook should be called.

### Additional comments

this bug is present on all versions above element-plus@2.2.10
this works as expected on version @2.2.6

**Comment by btea** [comment]
fixed #9145
