### ISSUE TITLE
[Docs] [message-box] $confirm is not defined

### ISSUE THREAD

**Issue by laofan1ku** [element-plus/element-plus#9493]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome 104.0.5112.102/windows 10`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBjbGlja0NsaWNrPSgpPT57XG4gICAkY29uZmlybShcIuehruWumj9cIiwgXCJXYXJuaW5nXCIsIHtcbiAgICBjb25maXJtQnV0dG9uVGV4dDogXCLnoa7lrppcIixcbiAgICBjYW5jZWxCdXR0b25UZXh0OiBcIuWPlua2iFwiLFxuICAgIHR5cGU6IFwid2FybmluZ1wiLFxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dG9uIEBjbGljaz0nY2xpY2tDbGljayc+54K55oiRPC9lbC1idXRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIm1haW4udHMiOiJpbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgQXBwIGZyb20gXCIuL0FwcC52dWVcIjtcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tIFwiZWxlbWVudC1wbHVzXCI7XG5pbXBvcnQgXCJlbGVtZW50LXBsdXMvZGlzdC9pbmRleC5jc3NcIjtcbmNvbnN0IGFwcCA9IGNyZWF0ZUFwcChBcHApO1xuXG5hcHAudXNlKEVsZW1lbnRQbHVzKTtcbmFwcC5tb3VudChcIiNhcHBcIik7XG4iLCJfbyI6e319)

### Steps to reproduce

after  Introduced the global  "elementPuls " in  mian.ts
in Vue instance can't use $confirm() util

### What is Expected?

in Vue instance use  $confirm()  trigger  "el-message-box"

### What is actually happening?

Uncaught ReferenceError: $confirm is not defined

### Additional comments

According to the document description https://element-plus.org/en-US/component/message-box.html#global-method

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmNvbnNvbGUubG9nKGluc3RhbmNlKVxuY29uc3QgY2xpY2tDbGljaz0oKT0+e1xuICAgaW5zdGFuY2UuYXBwQ29udGV4dC5jb25maWcuZ2xvYmFsUHJvcGVydGllcy4kY29uZmlybShcIuehruWumj9cIiwgXCJXYXJuaW5nXCIsIHtcbiAgICBjb25maXJtQnV0dG9uVGV4dDogXCLnoa7lrppcIixcbiAgICBjYW5jZWxCdXR0b25UZXh0OiBcIuWPlua2iFwiLFxuICAgIHR5cGU6IFwid2FybmluZ1wiLFxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dG9uIEBjbGljaz0nY2xpY2tDbGljayc+54K55oiRPC9lbC1idXRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIm1haW4udHMiOiJpbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgQXBwIGZyb20gXCIuL0FwcC52dWVcIjtcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tIFwiZWxlbWVudC1wbHVzXCI7XG5pbXBvcnQgXCJlbGVtZW50LXBsdXMvZGlzdC9pbmRleC5jc3NcIjtcbmNvbnN0IGFwcCA9IGNyZWF0ZUFwcChBcHApO1xuXG5hcHAudXNlKEVsZW1lbnRQbHVzKTtcbmFwcC5tb3VudChcIiNhcHBcIik7XG4iLCJfbyI6e319) 
Maybe you should take a look at the setup syntax.

**Comment by laofan1ku** [comment]
> [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmNvbnNvbGUubG9nKGluc3RhbmNlKVxuY29uc3QgY2xpY2tDbGljaz0oKT0+e1xuICAgaW5zdGFuY2UuYXBwQ29udGV4dC5jb25maWcuZ2xvYmFsUHJvcGVydGllcy4kY29uZmlybShcIuehruWumj9cIiwgXCJXYXJuaW5nXCIsIHtcbiAgICBjb25maXJtQnV0dG9uVGV4dDogXCLnoa7lrppcIixcbiAgICBjYW5jZWxCdXR0b25UZXh0OiBcIuWPlua2iFwiLFxuICAgIHR5cGU6IFwid2FybmluZ1wiLFxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dG9uIEBjbGljaz0nY2xpY2tDbGljayc+54K55oiRPC9lbC1idXRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIm1haW4udHMiOiJpbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgQXBwIGZyb20gXCIuL0FwcC52dWVcIjtcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tIFwiZWxlbWVudC1wbHVzXCI7XG5pbXBvcnQgXCJlbGVtZW50LXBsdXMvZGlzdC9pbmRleC5jc3NcIjtcbmNvbnN0IGFwcCA9IGNyZWF0ZUFwcChBcHApO1xuXG5hcHAudXNlKEVsZW1lbnRQbHVzKTtcbmFwcC5tb3VudChcIiNhcHBcIik7XG4iLCJfbyI6e319) Maybe you should take a look at the setup syntax.
如果需要再使用getCurrentInstance引入的话 和直接在vue实例中这么引入"import { ElMessageBox, ElMessage } from "element-plus";" 就没有么区别了吧?   或者是否要修改一下官网上面相关的文档?
