### ISSUE TITLE
[Component] [input] ElInput 中包含多个小数点时无法正确的显示去除全部空格后的字符串

### ISSUE THREAD

**Issue by DevDengChao** [element-plus/element-plus#9499]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGZvcm1hdHRlciA9IGZ1bmN0aW9uKGl0KXtcbiAgcmV0dXJuIGl0LnJlcGxhY2UoL1xccysvZyxcIlwiKTtcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgOmZvcm1hdHRlcj0nZm9ybWF0dGVyJyAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在 ElInput 中输入多个小数点 `.` 后即可尝试在任意位置添加任意数量的空格, 此时 formatter 无法正确的将删除空格后的字符串回显到 input 中.

### What is Expected?

当内容中包含多个小数点时能正常回显格式化后的内容

### What is actually happening?

如上所述

### Additional comments

![image](https://user-images.githubusercontent.com/16363180/187031769-6fcbeff8-ec69-48dd-9004-dd3d207af7a3.png)

**Comment by chenxch** [comment]
我试了一下这个似乎和小数点并无关系，应该是只要不在文本最后面输入新的文本，去前面的内容添加空格得不到formatter响应。
