### ISSUE TITLE
[Component] [upload] [Component] [upload] <el-upload> 上传组件不支持文件名展示和点击预览功能

### ISSUE THREAD

**Issue by sherry-up** [element-plus/element-plus#9505]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome 104.0.5112.101 / macOs 12.4`
- Build Tool: `Vue CLI`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6b24tcHJldmlldz1cImhhbmRsZVByZXZpZXdcIlxuICAgIDpvbi1yZW1vdmU9XCJoYW5kbGVSZW1vdmVcIlxuICAgIGxpc3QtdHlwZT1cInBpY3R1cmVcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMGtiXG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXVwbG9hZD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmltcG9ydCB0eXBlIHsgVXBsb2FkUHJvcHMsIFVwbG9hZFVzZXJGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmaWxlTGlzdCA9IHJlZjxVcGxvYWRVc2VyRmlsZVtdPihbXG4gIHtcbiAgICBuYW1lOiAnZm9vZC5qcGVnJyxcbiAgICB1cmw6ICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy82My80ZTdmM2ExNTQyOWJmZGE5OWJjZTQyYTE4Y2RkMWpwZWcuanBlZz9pbWFnZU1vZ3IyL3RodW1ibmFpbC8zNjB4MzYwL2Zvcm1hdC93ZWJwL3F1YWxpdHkvMTAwJyxcbiAgfSxcbiAge1xuICAgIG5hbWU6ICdmb29kMi5qcGVnJyxcbiAgICB1cmw6ICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy82My80ZTdmM2ExNTQyOWJmZGE5OWJjZTQyYTE4Y2RkMWpwZWcuanBlZz9pbWFnZU1vZ3IyL3RodW1ibmFpbC8zNjB4MzYwL2Zvcm1hdC93ZWJwL3F1YWxpdHkvMTAwJyxcbiAgfSxcbl0pXG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAodXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2codXBsb2FkRmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9IChmaWxlKSA9PiB7XG4gIGNvbnNvbGUubG9nKGZpbGUpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、list-type值为picture
2、v-model 绑定 filelist，元素对象包含name和url
3、绑定on-preview事件

### What is Expected?

页面展示缩略图和name，点击name执行preview事件

### What is actually happening?

页面只展示了缩略图，未展示文件名，且无法点击预览

### Additional comments

_(empty)_

**Comment by holazz** [comment]
Fixed by #9448, please wait for the next release.
