### ISSUE TITLE
[Component] [dialog] nuxt3中无法正常显示el-dialog

### ISSUE THREAD

**Issue by nifeng6** [element-plus/element-plus#9507]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome/104.0.5112.102 / Win10 64`
- Build Tool: `Nuxt`

### Related Component

- `el-dialog`

### Reproduction Link

[Github Repo](https://github.com/nifeng6/nuxt-app)

### Steps to reproduce

1.使用官方文档提供的基础代码，在nuxt3环境中直接使用 https://element-plus.org/zh-CN/component/dialog.html
2.基础上再顶层添加一层div，按钮点击后无法弹窗，去掉div即可弹窗
3.但再日常使用中，我是将dialog放在components中的，外层必然会有一层div，导致日常无法使用该组件
4.在外层有div包裹的情况下，即使给value直接赋值true，也无法显示
5.我在上方复现环境中提供了无法使用的场景，将app.vue中最外层的div去掉就能正常使用

### What is Expected?

点击按钮弹窗

### What is actually happening?

外层包裹div的情况下，点击按钮无法弹窗

### Additional comments

_(empty)_

**Comment by Godlovesmile** [comment]
use <ClientOnly> components can be used to solve.

eg:
<ClientOnly>
  <el-dialog />
</ClientOnly>

**Comment by Godlovesmile** [comment]
use 'ClientOnly' components can be used to solve.

`<ClientOnly><el-dialog/></ClientOnly>`
