### ISSUE TITLE
[Docs] [All] 官方中文文档经常打不开

### ISSUE THREAD

**Issue by icebound47** [element-plus/element-plus#9517]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/descriptions.html)

### Steps to reproduce

每天第一次通过保存到书签进入官网的时候，都会显示404。
多次F5刷新之后有可能恢复正常显示

### What is Expected?

随时都能正常浏览文档

### What is actually happening?

文档经常404

### Additional comments

优化一下官网的服务吧。
好多次为了找组件只能element官网找，element-plus官网经常打不开。

**Comment by chenxch** [comment]
same：#9196
