### ISSUE TITLE
[Component] [select] el-select可搜索多选，在搜索并选择一项后，再次输入内容不会触发下拉框的显示

### ISSUE THREAD

**Issue by u373693041** [element-plus/element-plus#9518]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `edge 104.0.1293.70`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1.输入搜索内容
2.选择一项
3.点击搜索框再次输入（这里跟以前element交互也有区别，以前选择完一项后是不会失焦的）
4.发现输入并不会触发下拉框的显示

### What is Expected?

选择完一项后，不失焦，且再次输入内容能触发下拉框的显示

### What is actually happening?

选择完一项后，失焦，且再次输入内容不能触发下拉框的显示

### Additional comments

_(empty)_

实际交互：目前element-plus的select交互
![element-plus-select-bug](https://user-images.githubusercontent.com/48196776/187114963-6685ede6-39f0-4b2d-9218-0b05c97d0b52.gif)

期望交互：vue2版element的select交互
![20220829-110723](https://user-images.githubusercontent.com/48196776/187115198-559b9d21-b057-4e16-9578-5602a596a53e.gif)

**Comment by MARIOMARUI** [comment]
看了下源码，应该是handleQueryChange 方法有问题

**Comment by ddmy** [comment]
2.2.16版本仍然没有解决

**Comment by init-qy** [comment]
fixed in 2.2.18
