### ISSUE TITLE
[Docs] 大陆站点API文档的部分连接跳转过去报错Resource not found

### ISSUE THREAD

**Issue by Indexsarrol** [element-plus/element-plus#9522]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome 104.0.5112.101（正式版本） (x86_64)`
- Build Tool: `Vite`

### Related Component

- `el-time-select`
- `el-transfer`
- `el-badge`
- `el-menu`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/menu.html)

### Steps to reproduce

1.打开https://element-plus.gitee.io/；
2.点击安装（https://element-plus.org/zh-CN/guide/installation.html）
3.页面直接报错

### What is Expected?

能够正常访问

### What is actually happening?

页面报错无法访问

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
gitee.io 和org两个站点都测试了看正常访问哦

**Comment by Cheerwhy** [comment]
可以访问 就是不稳定有时候老是要刷新
