### ISSUE TITLE
[Docs] [tree] tree 组件文档 禁用状态 标题错误

### ISSUE THREAD

**Issue by vaebe** [element-plus/element-plus#9525]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `Chrome 100`
- Build Tool: `Webpack`

### Related Component

- `el-tree`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/tree.html#%E9%BB%98%E8%AE%A4%E5%B1%95%E5%BC%80%E5%92%8C%E9%BB%98%E8%AE%A4%E9%80%89%E4%B8%AD)

### Steps to reproduce

打开element-plus中文文档->tree组件->默认展开和默认选中

### What is Expected?

对应小节标题为 禁用状态

### What is actually happening?

默认展开和默认选中

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
感谢反馈和词条提供，准确应该是`禁用复选框`。🤝
