### ISSUE TITLE
[Component] [tabs] 标签页顺序问题（tabs order）

### ISSUE THREAD

**Issue by Lionad-Morotar** [element-plus/element-plus#9532]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.70`
- Build Tool: `CDN`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMjBweFwiPlxuICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiYWRkVGFiKGVkaXRhYmxlVGFic1ZhbHVlKVwiPlxuICAgICAgYWRkIHRhYlxuICAgIDwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbiAgPHNwYW4+e3tlZGl0YWJsZVRhYnMubWFwKHggPT4geC5uYW1lKX19PC9zcGFuPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGNsYXNzPVwiZGVtby10YWJzXCJcbiAgICBjbG9zYWJsZVxuICAgIEB0YWItcmVtb3ZlPVwicmVtb3ZlVGFiXCJcbiAgPlxuICAgIDxlbC10YWItcGFuZVxuICAgICAgdi1mb3I9XCIoaXRlbSxpZHgpIGluIGVkaXRhYmxlVGFic1wiXG4gICAgICA6a2V5PVwiaXRlbS5uYW1lXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0udGl0bGVcIlxuICAgICAgOm5hbWU9XCJpdGVtLm5hbWVcIlxuICAgID5cbiAgICAgIHt7IGl0ZW0uY29udGVudCB9fVxuICAgIDwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmxldCB0YWJJbmRleCA9IDNcbmNvbnN0IGVkaXRhYmxlVGFic1ZhbHVlID0gcmVmKCcyJylcbmNvbnN0IGVkaXRhYmxlVGFicyA9IHJlZihbXG4gIHtcbiAgICB0aXRsZTogJ1RhYiAxJyxcbiAgICBuYW1lOiAnMScsXG4gICAgY29udGVudDogJ1RhYiAxIGNvbnRlbnQnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWIgMicsXG4gICAgbmFtZTogJzInLFxuICAgIGNvbnRlbnQ6ICdUYWIgMiBjb250ZW50JyxcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnVGFiIDMnLFxuICAgIG5hbWU6ICczJyxcbiAgICBjb250ZW50OiAnVGFiIDMgY29udGVudCcsXG4gIH0sXG5dKVxuXG5jb25zdCBhZGRUYWIgPSAodGFyZ2V0TmFtZTogc3RyaW5nKSA9PiB7XG4gIGNvbnN0IG5ld1RhYk5hbWUgPSBgJHsrK3RhYkluZGV4fWBcbiAgZWRpdGFibGVUYWJzLnZhbHVlLnNwbGljZSgxLCAwLCB7XG4gICAgdGl0bGU6ICdOZXcgVGFiJyxcbiAgICBuYW1lOiBuZXdUYWJOYW1lLFxuICAgIGNvbnRlbnQ6ICdOZXcgVGFiIGNvbnRlbnQgJyArIHRhYkluZGV4LFxuICB9KVxuICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IG5ld1RhYk5hbWVcbn1cbmNvbnN0IHJlbW92ZVRhYiA9ICh0YXJnZXROYW1lOiBzdHJpbmcpID0+IHtcbiAgY29uc3QgdGFicyA9IGVkaXRhYmxlVGFicy52YWx1ZVxuICBsZXQgYWN0aXZlTmFtZSA9IGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlXG4gIGlmIChhY3RpdmVOYW1lID09PSB0YXJnZXROYW1lKSB7XG4gICAgdGFicy5mb3JFYWNoKCh0YWIsIGluZGV4KSA9PiB7XG4gICAgICBpZiAodGFiLm5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICAgICAgY29uc3QgbmV4dFRhYiA9IHRhYnNbaW5kZXggKyAxXSB8fCB0YWJzW2luZGV4IC0gMV1cbiAgICAgICAgaWYgKG5leHRUYWIpIHtcbiAgICAgICAgICBhY3RpdmVOYW1lID0gbmV4dFRhYi5uYW1lXG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9KVxuICB9XG5cbiAgZWRpdGFibGVUYWJzVmFsdWUudmFsdWUgPSBhY3RpdmVOYW1lXG4gIGVkaXRhYmxlVGFicy52YWx1ZSA9IHRhYnMuZmlsdGVyKCh0YWIpID0+IHRhYi5uYW1lICE9PSB0YXJnZXROYW1lKVxufVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4uZGVtby10YWJzID4gLmVsLXRhYnNfX2NvbnRlbnQge1xuICBwYWRkaW5nOiAzMnB4O1xuICBjb2xvcjogIzZiNzc4YztcbiAgZm9udC1zaXplOiAzMnB4O1xuICBmb250LXdlaWdodDogNjAwO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 点击“add tab”
2. 发现新标签页添加到了尾部

### What is Expected?

应该按照 splice(1, 0, newTab) 将新标签页添加为第二项

### What is actually happening?

新标签页添加到了尾部

### Additional comments

_(empty)_

**Comment by Lionad-Morotar** [comment]
刚试了一下 ElementUI 不会有这种问题，https://codepen.io/Lionad/pen/abYebmJ

**Comment by Lionad-Morotar** [comment]
项目中临时解决可以使用给 el-tabs 加 key 的办法，见：[Element Play Ground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMjBweFwiPlxuICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiYWRkVGFiKGVkaXRhYmxlVGFic1ZhbHVlKVwiPlxuICAgICAgYWRkIHRhYlxuICAgIDwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbiAgPHNwYW4+e3tlZGl0YWJsZVRhYnMubWFwKHggPT4geC5uYW1lKX19PC9zcGFuPlxuICA8ZWwtdGFic1xuXHRcdDprZXk9XCJlZGl0YWJsZVRhYnMubGVuZ3RoXCJcbiAgICB2LW1vZGVsPVwiZWRpdGFibGVUYWJzVmFsdWVcIlxuICAgIHR5cGU9XCJjYXJkXCJcbiAgICBjbGFzcz1cImRlbW8tdGFic1wiXG4gICAgY2xvc2FibGVcbiAgICBAdGFiLXJlbW92ZT1cInJlbW92ZVRhYlwiXG4gID5cbiAgICA8ZWwtdGFiLXBhbmVcbiAgICAgIHYtZm9yPVwiKGl0ZW0saWR4KSBpbiBlZGl0YWJsZVRhYnNcIlxuICAgICAgOmtleT1cIlN0cmluZyhpdGVtLm5hbWUpXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0udGl0bGVcIlxuICAgICAgOm5hbWU9XCJTdHJpbmcoaXRlbS5uYW1lKVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxubGV0IHRhYkluZGV4ID0gM1xuY29uc3QgZWRpdGFibGVUYWJzVmFsdWUgPSByZWYoJzInKVxuY29uc3QgZWRpdGFibGVUYWJzID0gcmVmKFtcbiAge1xuICAgIHRpdGxlOiAnVGFiIDEnLFxuICAgIG5hbWU6ICcxJyxcbiAgICBjb250ZW50OiAnVGFiIDEgY29udGVudCcsXG4gIH0sXG4gIHtcbiAgICB0aXRsZTogJ1RhYiAyJyxcbiAgICBuYW1lOiAnMicsXG4gICAgY29udGVudDogJ1RhYiAyIGNvbnRlbnQnLFxuICB9LFxuICB7XG4gICAgdGl0bGU6ICdUYWIgMycsXG4gICAgbmFtZTogJzMnLFxuICAgIGNvbnRlbnQ6ICdUYWIgMyBjb250ZW50JyxcbiAgfSxcbl0pXG5cbmNvbnN0IGFkZFRhYiA9ICh0YXJnZXROYW1lOiBzdHJpbmcpID0+IHtcbiAgY29uc3QgbmV3VGFiTmFtZSA9IGAkeysrdGFiSW5kZXh9YFxuICBlZGl0YWJsZVRhYnMudmFsdWUuc3BsaWNlKDEsIDAsIHtcbiAgICB0aXRsZTogJ05ldyBUYWInLFxuICAgIG5hbWU6IG5ld1RhYk5hbWUsXG4gICAgY29udGVudDogJ05ldyBUYWIgY29udGVudCAnICsgdGFiSW5kZXgsXG4gIH0pXG4gIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gbmV3VGFiTmFtZVxuICBjb25zb2xlLmxvZygnZWRpdGFibGVUYWJzJywgZWRpdGFibGVUYWJzLnZhbHVlKVxufVxuY29uc3QgcmVtb3ZlVGFiID0gKHRhcmdldE5hbWU6IHN0cmluZykgPT4ge1xuICBjb25zdCB0YWJzID0gZWRpdGFibGVUYWJzLnZhbHVlXG4gIGxldCBhY3RpdmVOYW1lID0gZWRpdGFibGVUYWJzVmFsdWUudmFsdWVcbiAgaWYgKGFjdGl2ZU5hbWUgPT09IHRhcmdldE5hbWUpIHtcbiAgICB0YWJzLmZvckVhY2goKHRhYiwgaW5kZXgpID0+IHtcbiAgICAgIGlmICh0YWIubmFtZSA9PT0gdGFyZ2V0TmFtZSkge1xuICAgICAgICBjb25zdCBuZXh0VGFiID0gdGFic1tpbmRleCArIDFdIHx8IHRhYnNbaW5kZXggLSAxXVxuICAgICAgICBpZiAobmV4dFRhYikge1xuICAgICAgICAgIGFjdGl2ZU5hbWUgPSBuZXh0VGFiLm5hbWVcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0pXG4gIH1cblxuICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IGFjdGl2ZU5hbWVcbiAgZWRpdGFibGVUYWJzLnZhbHVlID0gdGFicy5maWx0ZXIoKHRhYikgPT4gdGFiLm5hbWUgIT09IHRhcmdldE5hbWUpXG59XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by baboon-king** [comment]
#9555

**Comment by sxzz** [comment]
Fixed via #9222

**Comment by wiidede** [comment]
> Fixed via #9222

你好，这个issue修复了吗？我看 #9222 的改动没并有修复顺序不对的问题，楼主的playground用2.2.16貌似还是达不到插入tab的效果

**Comment by Lionad-Morotar** [comment]
你好，#9222 并没有修复这个问题。目前，tabs 的顺序依赖 TabPane 组件的 onMounted 事件顺序，所以插入无效。我建议在 registerPane 和 unRegisterPane 时重新动态计算 panes 的顺序，就像这个 PR 中的代码所示。我会继续跟进这个 PR，如果代码可行的话？

**Comment by Lionad-Morotar** [comment]
> Fixed via #9222

你好，https://github.com/element-plus/element-plus/pull/9222 并没有修复这个问题。目前，tabs 的顺序依赖 TabPane 组件的 onMounted 事件顺序，所以插入无效。我建议在 registerPane 和 unRegisterPane 时重新动态计算 panes 的顺序，就像这个 PR 中的代码所示。我会继续跟进这个 PR，如果代码可行的话？

**Comment by sxzz** [comment]
@Lionad-Morotar OK
