### ISSUE TITLE
[Component] [select] select自定义filter-method时的展现问题

### ISSUE THREAD

**Issue by chrisllio** [element-plus/element-plus#9539]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63`
- Build Tool: `CDN`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5cbmNvbnN0IHNlbGVjdFZhbHVlID0gcmVmKClcbmNvbnN0IHNlbGVjdE9wdGlvbnM9cmVmKFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbl0pXG5jb25zdCBzZWxlY3RPcHRpb25zQ29weSA9IEpTT04ucGFyc2UoSlNPTi5zdHJpbmdpZnkoc2VsZWN0T3B0aW9ucy52YWx1ZSkpXG5cbmNvbnN0IHRlc3RmaWx0ZXIgPSAodGV4dCkgPT4ge1xuICBjb25zb2xlLmxvZygnc2VhcmNoOiAnICsgdGV4dClcblx0aWYodGV4dCkge1xuICAgIHNlbGVjdE9wdGlvbnMudmFsdWUgPSBzZWxlY3RPcHRpb25zQ29weS5maWx0ZXIoKGl0ZW0pID0+IHtcbiAgICAgIHJldHVybiBpdGVtLmxhYmVsLmluZGV4T2YodGV4dCkgPiAwXG4gICAgfSlcblx0fSBlbHNlIHtcblx0XHRzZWxlY3RPcHRpb25zLnZhbHVlID0gc2VsZWN0T3B0aW9uc0NvcHlcblx0fVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICAgPGI+RWxTZWxlY3Toh6rlrprkuYlmaWx0ZXItbWV0aG9k6Zeu6aKY77yaPC9iPjxicj48YnI+XG4gICAgKDEpIOeCueWHu+W5tuW9leWFpeS7u+aEj+aQnOe0ouWtl+espuS4sjxicj5cbiAgICAoMikg56e75Ye654Sm54K5PGJyPlxuICAgICgzKSDlho3mrKHngrnlh7vvvIzkuIvmi4npgInpobnku43kuLrkuIrmrKHnmoTmkJzntKLnu5PmnpzvvIjlupTmmL7npLrmiYDmnInpgInpobnvvIzmiJbkv53nlZnkuIrmrKHnmoTmkJzntKLlrZfnrKbkuLLvvIk8YnI+PGJyPlxuICA8L2Rpdj5cbiAgPGVsLXNlbGVjdCByZWY9XCJ0ZXN0XCIgdi1tb2RlbD1cInNlbGVjdFZhbHVlXCIgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDpmaWx0ZXItbWV0aG9kPVwidGVzdGZpbHRlclwiIDptdWx0aXBsZT1cInRydWVcIj5cblx0XHRcdDxlbC1vcHRpb25cblx0XHRcdCAgdi1mb3I9XCJpdGVtIGluIHNlbGVjdE9wdGlvbnNcIlxuXHRcdFx0ICA6a2V5PVwiaXRlbS52YWx1ZVwiXG5cdFx0XHQgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuXHRcdFx0ICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcblx0XHRcdC8+XG5cdFx0ICA8L2VsLXNlbGVjdD5cblxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1 为select自定义filter-method（以下简称filter）
2 在连续编辑搜索字符串时，filter能够一直被正确调用
3 从select移出焦点再移入

### What is Expected?

下拉选项仍是之前的过滤结果，保留之前的搜索字符串；或展示全部选项并清空搜索字符串

### What is actually happening?

下拉选项仍是之前的过滤结果，同时也未保留之前的搜索字符串，二者矛盾

### Additional comments

_(empty)_

**Comment by Circkoooooo** [comment]
你可以绑定一个失焦事件，手动把内容给还原。你这种写法只是在每次输入的时候进行匹配，失焦事件并不会触发你的filter函数，所以内容没办法去自动的还原。
然后如果组件内部设置每次失焦都会重置内容的话，可能会对自定义造成一定的局限吧。

**Comment by Circkoooooo** [comment]
> 你可以绑定一个失焦事件，手动把内容给还原。你这种写法只是在每次输入的时候进行匹配，失焦事件并不会触发你的filter函数，所以内容没办法去自动的还原。 然后如果组件内部设置每次失焦都会重置内容的话，可能会对自定义造成一定的局限吧。

[创建新的选项](https://element-plus.gitee.io/zh-CN/component/select.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E9%80%89%E9%A1%B9)

**Comment by chrisllio** [comment]
> > 你可以绑定一个失焦事件，手动把内容给还原。你这种写法只是在每次输入的时候进行匹配，失焦事件并不会触发你的filter函数，所以内容没办法去自动的还原。 然后如果组件内部设置每次失焦都会重置内容的话，可能会对自定义造成一定的局限吧。
> 
> [创建新的选项](https://element-plus.gitee.io/zh-CN/component/select.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84%E9%80%89%E9%A1%B9)

输入搜索字符串后，点选选项时的mousedown会导致触发blur，导致选项列表刷新，目标选项也选不上。
从设计上将不应该要求开发者在实现filter-method后还需要进行额外的处理，当然这种额外的处理的需求可能是开发者自己造成的。
但无论如何，我认为filter-method的设计过于开放了，自定义逻辑与ElSelect内部逻辑互相作用后产生的后果难以预期，ElSelect内部实现未来修改后又会有什么后果也未知。

或许应该将遍历和处理选项数据数组的逻辑收回到ElSelect内部，filter-method只用来返回单选项数据是否符匹配：
```
(option: {[key:string]: any}, searchText: string): boolean
```

**Comment by chrisllio** [comment]
再次测试后仍如上面所说，blur时执行filterMethod是存在问题的：
在录入筛选字符串后，用鼠标点击筛选出的选项，在鼠标按下时就会触发blur，从而导致下拉选项列表刷新，本次点击无法选中选项。
