### ISSUE TITLE
[Component] [select] el-select 使用不同字段名称默认展示不一致

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#9542]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `win11   Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.70`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIHZhbHVlMeS4rSDmsqHmnIkgbGFiZWzlrZfmrrXmiYDku6XkuI3mmL7npLrpu5jorqTlgLwgLS0+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlMVwiIHZhbHVlLWtleT1cInZhbFwiPlxuICAgIDxlbC1vcHRpb24gIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsXCIgOmxhYmVsPVwiaXRlbS5uYW1lXCIgOnZhbHVlPVwiaXRlbS52YWxcIiAgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDwhLS0gdmFsdWUyIOaciSBsYWJlbOWtl+auteWPr+S7peato+W4uOaYvuekuiAtLT5cbiAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlMlwiIHZhbHVlLWtleT1cInZhbFwiPlxuICAgIDxlbC1vcHRpb24gIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsXCIgOmxhYmVsPVwiaXRlbS5sYWJlbFwiIDp2YWx1ZT1cIml0ZW0udmFsXCIgIC8+XG4gIDwvZWwtc2VsZWN0PlxuICBcbiAgXHQ8IS0tIOazqOaEj+S4juS4iuS4gOS4queahOWMuuWIq+aYryA6bGFiZWznu5HlrprnmoTmmK9cIml0ZW0udmFsXCIgIC0tPlxuICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWUyXCIgdmFsdWUta2V5PVwidmFsXCI+XG4gICAgPGVsLW9wdGlvbiAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWxcIiA6bGFiZWw9XCJpdGVtLnZhbFwiIDp2YWx1ZT1cIml0ZW0udmFsXCIgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBjb25zdCB2YWx1ZTEgPSByZWYoeyBuYW1lOiAnQTEnLCAgdmFsOiAnYTEnICB9KSAvLyDlr7nosaHph4zpnaLnmoTlrZfmrrXkuI3lkIxcbiAgY29uc3QgdmFsdWUyID0gcmVmKHsgbGFiZWw6ICdBMicsICB2YWw6ICdhMicgIH0pIC8vIOWvueixoemHjOmdoueahOWtl+auteS4jeWQjFxuICBjb25zdCBvcHRpb25zID0gW107XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

 ```vue
<template>

  <!-- value1中 没有 label字段所以不显示默认值 -->
  <el-select v-model="value1" value-key="val">
    <el-option  v-for="item in options" :key="item.val" :label="item.name" :value="item.val"  />
  </el-select>

   <!-- value2 有 label字段可以正常显示 -->
   <el-select v-model="value2" value-key="val">
    <el-option  v-for="item in options" :key="item.val" :label="item.label" :value="item.val"  />
  </el-select>
  
   <!-- 注意与上一个的区别是 :label绑定的是"item.val"  并没用用到"item.label" -->
   <el-select v-model="value2" value-key="val">
    <el-option  v-for="item in options" :key="item.val" :label="item.val" :value="item.val"  />
  </el-select>

</template>

<script setup>
  import { ref } from 'vue'
  const value1 = ref({ name: 'A1',  val: 'a1'  }) // 对象里面的字段不同 
  const value2 = ref({ label: 'A2',  val: 'a2'  }) // 对象里面的字段不同 
  const options = [];
</script>


```

**只要当默认值包含为`lable` 字段 时就可以正常显示且无论是否有没有使用到`lable` 字段 **

![image](https://user-images.githubusercontent.com/31055355/187389818-56dd13e2-4902-47a3-a6af-a9b7928e7b9a.png)

### What is Expected?

默认值可以正常显示

### What is actually happening?

默认值不可以正常显示

### Additional comments

_(empty)_

**Comment by ngd-b** [comment]
确实，应该提供一个类似label-key的属性，在绑定value值为对象时，可以准确取到label

**Comment by tolking** [comment]
Select 组件没有从 Option 中获得数据，自然 label 会产生错误。当有传入 value 是对象时会取 value.label 值，这是默认行为

你需要向 Option 组件中增加数据

[Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIHZhbHVlMeS4rSDmsqHmnIkgbGFiZWzlrZfmrrXmiYDku6XkuI3mmL7npLrpu5jorqTlgLwgLS0+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlMVwiIHZhbHVlLWtleT1cInZhbFwiPlxuICAgIDxlbC1vcHRpb24gIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsXCIgOmxhYmVsPVwiaXRlbS5uYW1lXCIgOnZhbHVlPVwiaXRlbVwiICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgPCEtLSB2YWx1ZTIg5pyJIGxhYmVs5a2X5q615Y+v5Lul5q2j5bi45pi+56S6IC0tPlxuICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWUyXCIgdmFsdWUta2V5PVwidmFsXCI+XG4gICAgPGVsLW9wdGlvbiAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiA6a2V5PVwiaXRlbS52YWxcIiA6bGFiZWw9XCJpdGVtLmxhYmVsXCIgOnZhbHVlPVwiaXRlbVwiICAvPlxuICA8L2VsLXNlbGVjdD5cbiAgXG4gIFx0PCEtLSDms6jmhI/kuI7kuIrkuIDkuKrnmoTljLrliKvmmK8gOmxhYmVs57uR5a6a55qE5pivXCJpdGVtLnZhbFwiICAtLT5cbiAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlMlwiIHZhbHVlLWtleT1cInZhbFwiPlxuICAgIDxlbC1vcHRpb24gIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCIgOmtleT1cIml0ZW0udmFsXCIgOmxhYmVsPVwiaXRlbS52YWxcIiA6dmFsdWU9XCJpdGVtXCIgIC8+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBjb25zdCB2YWx1ZTEgPSByZWYoeyBuYW1lOiAnQTEnLCAgdmFsOiAnYTEnICB9KSAvLyDlr7nosaHph4zpnaLnmoTlrZfmrrXkuI3lkIxcbiAgY29uc3QgdmFsdWUyID0gcmVmKHsgbGFiZWw6ICdBMicsICB2YWw6ICdhMicgIH0pIC8vIOWvueixoemHjOmdoueahOWtl+auteS4jeWQjFxuICBjb25zdCBvcHRpb25zID0gW3sgbmFtZTogJ0ExJywgIHZhbDogJ2ExJyAgfSwgeyBsYWJlbDogJ0EyJywgIHZhbDogJ2EyJyAgfV07XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
