### ISSUE TITLE
[Component] [tree-select] 按需引入-自动引入，el-tree-select组件的css文件引入模块路径错误

### ISSUE THREAD

**Issue by shuknganHo** [element-plus/element-plus#9554]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/104.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Link]()

### Steps to reproduce

element-plus-v2.1.8， 按需引入，自动引入，使用el-tree-select组件

X [ERROR] Could not resolve "element-plus/theme-chalk/src/tree-select/css"

    node_modules/element-plus/es/components/tree-select/style/css.mjs:3:7:
      3 │ import 'element-plus/theme-chalk/src/tree-select/css';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./theme-chalk/src/tree-select/css" was not found on the file system:

    node_modules/element-plus/package.json:72:11:
      72 │     "./*": "./*"
         ╵            ~~~~~

  You can mark the path "element-plus/theme-chalk/src/tree-select/css" as external to exclude it
  from the bundle, which will remove this error.

### What is Expected?

修改路径

### What is actually happening?

修改路径

### Additional comments

_(empty)_

**Comment by holazz** [comment]
升级到最新版本
