### ISSUE TITLE
[Component] [tabs, tab-pane] el-tabs-pane使用v-for渲染时错序

### ISSUE THREAD

**Issue by JohnWicc** [element-plus/element-plus#9555]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome 91.0.4472.164`
- Build Tool: `Webpack`

### Related Component

- `el-tabs`
- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoXCJ0YWItMVwiKVxuY29uc3QgdGFiUGFuZXMgPSByZWYoW3tcbiAgaWQ6IDEsXG4gIG5hbWU6ICd0YWItMScsXG4gIGxhYmVsOiAndGFiMSdcbn0se1xuICBpZDogMixcbiAgbmFtZTogJ3RhYi0yJyxcbiAgbGFiZWw6ICd0YWIyJ1xufSx7XG4gIGlkOiAzLFxuICBuYW1lOiAndGFiLTMnLFxuICBsYWJlbDogJ3RhYjMnXG59XSlcblxuY29uc3QgdGFiUGFuZXMyID0gcmVmKFt7XG4gIGlkOiAxMSxcbiAgbmFtZTogJ3RhYi0xMScsXG4gIGxhYmVsOiAndGFiMTEnXG59LHtcbiAgaWQ6IDIyLFxuICBuYW1lOiAndGFiLTIyJyxcbiAgbGFiZWw6ICd0YWIyMidcbn0se1xuICBpZDogMzMsXG4gIG5hbWU6ICd0YWItMzMnLFxuICBsYWJlbDogJ3RhYjMzJ1xufV0pXG5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICB0YWJQYW5lcy52YWx1ZSA9IHRhYlBhbmVzMi52YWx1ZVxuICBhY3RpdmVOYW1lLnZhbHVlID0gJ3RhYi0xMSdcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiaGFuZGxlQ2xpY2tcIiB0eXBlPVwicHJpbWFyeVwiPmNsaWNrIG1lIHRvIGNoYW5nZTwvZWwtYnV0dG9uPlxuIFx0PGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIj5cbiAgICA8ZWwtdGFiLXBhbmUgdi1mb3I9XCJ0YWIgaW4gdGFiUGFuZXNcIiA6a2V5PVwidGFiLmlkXCIgOm5hbWU9XCJ0YWIubmFtZVwiIDpsYWJlbD1cInRhYi5sYWJlbFwiPlxuICAgIFx0e3t0YWIubmFtZX19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 使用el-tab-pane + v-for渲染
2. 替换v-for绑定的数据

### What is Expected?

el-tab-pane按照数组顺序挂载

### What is actually happening?

el-tab-pane倒序挂载

### Additional comments

看了源码后我相信出问题的地方是el-tabs的registerPane方法，它用uid作为映射重新生成了panes数据，而vue对于这种情况下组件挂载顺序并不是顺序的

**Comment by baboon-king** [comment]
why not use "index" become key?

![image](https://user-images.githubusercontent.com/63645337/187623804-e6136e1c-f1b0-40d5-9330-3a15565f6371.png)


https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ3RhYi0xJylcbmNvbnN0IHRhYlBhbmVzID0gcmVmKFtcbiAge1xuICAgIGlkOiAxLFxuICAgIG5hbWU6ICd0YWItMScsXG4gICAgbGFiZWw6ICd0YWIxJyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIG5hbWU6ICd0YWItMicsXG4gICAgbGFiZWw6ICd0YWIyJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIG5hbWU6ICd0YWItMycsXG4gICAgbGFiZWw6ICd0YWIzJyxcbiAgfSxcbl0pXG5cbmNvbnN0IHRhYlBhbmVzMiA9IHJlZihbXG4gIHtcbiAgICBpZDogMTEsXG4gICAgbmFtZTogJ3RhYi0xMScsXG4gICAgbGFiZWw6ICd0YWIxMScsXG4gIH0sXG4gIHtcbiAgICBpZDogMjIsXG4gICAgbmFtZTogJ3RhYi0yMicsXG4gICAgbGFiZWw6ICd0YWIyMicsXG4gIH0sXG4gIHtcbiAgICBpZDogMzMsXG4gICAgbmFtZTogJ3RhYi0zMycsXG4gICAgbGFiZWw6ICd0YWIzMycsXG4gIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICgpID0+IHtcbiAgdGFiUGFuZXMudmFsdWUgPSB0YWJQYW5lczIudmFsdWVcbiAgYWN0aXZlTmFtZS52YWx1ZSA9ICd0YWItMTEnXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCIgdHlwZT1cInByaW1hcnlcIj5jbGljayBtZSB0byBjaGFuZ2U8L2VsLWJ1dHRvbj5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIj5cbiAgICA8ZWwtdGFiLXBhbmVcbiAgICAgIHYtZm9yPVwiKHRhYiwgaW5kZXgpIGluIHRhYlBhbmVzXCJcbiAgICAgIDprZXk9XCJpbmRleFwiXG4gICAgICA6bmFtZT1cInRhYi5uYW1lXCJcbiAgICAgIDpsYWJlbD1cInRhYi5sYWJlbFwiXG4gICAgPlxuICAgICAge3sgdGFiLm5hbWUgfX1cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by Lionad-Morotar** [comment]
> why not use "index" become key?
> 
> ![image](https://user-images.githubusercontent.com/63645337/187623804-e6136e1c-f1b0-40d5-9330-3a15565f6371.png)
> 
> https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGFjdGl2ZU5hbWUgPSByZWYoJ3RhYi0xJylcbmNvbnN0IHRhYlBhbmVzID0gcmVmKFtcbiAge1xuICAgIGlkOiAxLFxuICAgIG5hbWU6ICd0YWItMScsXG4gICAgbGFiZWw6ICd0YWIxJyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIG5hbWU6ICd0YWItMicsXG4gICAgbGFiZWw6ICd0YWIyJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIG5hbWU6ICd0YWItMycsXG4gICAgbGFiZWw6ICd0YWIzJyxcbiAgfSxcbl0pXG5cbmNvbnN0IHRhYlBhbmVzMiA9IHJlZihbXG4gIHtcbiAgICBpZDogMTEsXG4gICAgbmFtZTogJ3RhYi0xMScsXG4gICAgbGFiZWw6ICd0YWIxMScsXG4gIH0sXG4gIHtcbiAgICBpZDogMjIsXG4gICAgbmFtZTogJ3RhYi0yMicsXG4gICAgbGFiZWw6ICd0YWIyMicsXG4gIH0sXG4gIHtcbiAgICBpZDogMzMsXG4gICAgbmFtZTogJ3RhYi0zMycsXG4gICAgbGFiZWw6ICd0YWIzMycsXG4gIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICgpID0+IHtcbiAgdGFiUGFuZXMudmFsdWUgPSB0YWJQYW5lczIudmFsdWVcbiAgYWN0aXZlTmFtZS52YWx1ZSA9ICd0YWItMTEnXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCIgdHlwZT1cInByaW1hcnlcIj5jbGljayBtZSB0byBjaGFuZ2U8L2VsLWJ1dHRvbj5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIj5cbiAgICA8ZWwtdGFiLXBhbmVcbiAgICAgIHYtZm9yPVwiKHRhYiwgaW5kZXgpIGluIHRhYlBhbmVzXCJcbiAgICAgIDprZXk9XCJpbmRleFwiXG4gICAgICA6bmFtZT1cInRhYi5uYW1lXCJcbiAgICAgIDpsYWJlbD1cInRhYi5sYWJlbFwiXG4gICAgPlxuICAgICAge3sgdGFiLm5hbWUgfX1cbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

用 index 作为 pane 的 key 不能解决问题。

**Comment by Lionad-Morotar** [comment]
same as https://github.com/element-plus/element-plus/issues/9532
