### ISSUE TITLE
请教下在vite中如何配置按需加载，望大神赐教

### ISSUE THREAD

**Issue by y1378056783** [element-plus/element-plus#956]
按官方文档配置并没有效果，打包后体积还是很大
vite.config配置如下：
module.exports = {
    plugin:['babel-plugin-component']
}
babel.config配置如下
module.exports = {
    plugins: [
      [
        "component",
        {
          "libraryName": "element-plus",
          "styleLibraryName": "theme-chalk"
        }
      ]
    ]
  }
引入示例：
import {  ElPagination, ElDialog } from "element-plus"
export default app => {
  const components = [ ElPagination,ElDialog]
  components.forEach(component => {
    app.component(component.name, component)
  })
}

**Comment by zazzaz** [comment]
You can check this as a reference #719

**Comment by JeremyWuuuuu** [comment]
https://github.com/wingsico/vite-element-demand-starter FYI.
