### ISSUE TITLE
[Component] [rate] el-rate 评分组件bug

### ISSUE THREAD

**Issue by yufengaotianya** [element-plus/element-plus#9567]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-rate`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihudWxsKVxuY29uc3QgdmFsdWUyID0gcmVmKG51bGwpXG5jb25zdCB2YWx1ZTMgPSByZWYobnVsbClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgICBcbiAgICBcbiAgICA8ZGl2IGNsYXNzPVwiZGVtby1yYXRlLWJsb2NrXCI+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPkRlZmF1bHQ8L3NwYW4+XG4gICAgICAgIDxlbC1yYXRlIHYtbW9kZWw9XCJ2YWx1ZTFcIiAvPlxuICAgICAgPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiZGVtby1yYXRlLWJsb2NrXCI+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiZGVtb25zdHJhdGlvblwiPkNvbG9yPC9zcGFuPlxuICAgICAgICA8ZWwtcmF0ZSB2LW1vZGVsPVwidmFsdWUyXCIgLz5cbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cImRlbW8tcmF0ZS1ibG9ja1wiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5Db2xvcjI8L3NwYW4+XG4gICAgICAgIDxlbC1yYXRlIHYtbW9kZWw9XCJ2YWx1ZTNcIiAvPlxuICAgICAgPC9kaXY+XG5cbiAgICAgIHt7IHZhbHVlMSB9fSAtIHt7IHZhbHVlMiB9fSAtIHt7IHZhbHVlMyB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

界面上常见三个el-rate组件；分别绑定三个不同的值，鼠标快速划过；el-rate值被选中，但是绑定的值未被赋予新值

### What is Expected?

el-rate界面表现选中和绑定的值一致

### What is actually happening?

不一致

### Additional comments

_(empty)_

<img width="265" alt="image" src="https://user-images.githubusercontent.com/33416518/187691290-7978db9b-1f8b-4003-99ad-c00b57afaeec.png">

**Comment by chenxch** [comment]
这个问题目前还没有想到很好的解决方案，原因是因为在快速移动下mouseleave最后没有触发导致的。

**Comment by liangmeisheng** [comment]
复现不出来
