### ISSUE TITLE
[Docs] [All] 在官网的组件页，连续点击左边切换组件时会偶现404

### ISSUE THREAD

**Issue by aaxx22** [element-plus/element-plus#9574]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.15`
- Browser / OS: `版本 105.0.5195.52（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html)

### Steps to reproduce

连续点击左边菜单栏切换组件，会偶现404，此时需要刷新页面才能恢复

### What is Expected?

不会出现404

### What is actually happening?

会出现404

### Additional comments

_(empty)_
![image](https://user-images.githubusercontent.com/55844132/187823039-2bbd66f5-66d2-4ee0-b8c3-1ab5daa43018.png)

**Comment by chenxch** [comment]
same：#9196
