### ISSUE TITLE
在vite当中使用主题，字体路径的 ~ 无法正常解析，build和dev均报错

### ISSUE THREAD

**Issue by seolhw** [element-plus/element-plus#958]
在vite当中使用主题，~路径无法正常解析，build和dev均报错
```
/* 改变 icon 字体路径变量，必需 */
$--font-path: '~/element-plus/lib/theme-chalk/fonts';

@import "~element-plus/packages/theme-chalk/src/index.scss";
```

**Comment by porcelainHeart** [comment]
You can use @modules/element-plus.

**Comment by porcelainHeart** [comment]
~ is a convention alias configured in vue-cli. There’s no such thing in Vite.

**Comment by seolhw** [comment]
> You can use @modules/element-plus.

是的，/@modules/element-plus 仅dev可用，build依旧会报错

```
[Error: ENOENT: no such file or directory, open 'E:\work\dyt_nethospital_doctorsworkbench_v2\@modules\element-plus\lib\theme-chalk\fonts\element-icons.woff']
```

> ~ is a convention alias configured in vue-cli. There’s no such thing in Vite.

我非常清楚你的意思，我想问有没有什么解决方案？

**Comment by seolhw** [comment]
把字体文件复制到src下了，用相对路径引入，反正是可以用了，只是升级会有影响，暂时先这样吧，如果没有其他解决方案的话

**Comment by JeremyWuuuuu** [comment]
This is related to the module resolution in `Vite`, we might need some help from them. Also we will update our documentation. Thank you

**Comment by panzhangguo** [comment]
Error: Can't find stylesheet to import
 @import "~/element-plus/packages/theme-chalk/src/index.scss";
自定义主题色，引进文件也报错。用了@modules也一样。

**Comment by JeremyWuuuuu** [comment]
Try Vite2. They just got it released.

**Comment by JeremyWuuuuu** [comment]
Closing this issue since it can only be resolved by `Vite`, note that `Vite` is not a very mature tool, use it at your own risk.
