### ISSUE TITLE
[Component] [select] Select 为多选，并且选择数量超过10个后布局错乱

### ISSUE THREAD

**Issue by Axu96** [element-plus/element-plus#9589]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.15`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogaW5saW5lLWJsb2NrXCI+XG4gICAgPHAgc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPmRlZmF1bHQ8L3A+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgc3R5bGU9XCJ3aWR0aDogMTgwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKFtdKVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjFPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMicsXG4gICAgbGFiZWw6ICdPcHRpb24yJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSwgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjYnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sICB7XG4gICAgdmFsdWU6ICdPcHRpb241MScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSwgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjUyJyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LCAge1xuICAgIHZhbHVlOiAnT3B0aW9uNTMnLFxuICAgIGxhYmVsOiAnT3B0aW9uNScsXG4gIH0sICB7XG4gICAgdmFsdWU6ICdPcHRpb241NCcsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSwgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjU1JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuICBcbl1cbnZhbHVlMS52YWx1ZSA9IG9wdGlvbnMubWFwKGl0ZW09Pml0ZW0udmFsdWUpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

当select为multiple，并且选择数量超过10个后布局错乱

### What is Expected?

1.希望input框高度也随之变高，或者前一个tag变窄

### What is actually happening?

1.tag直接超出input看上去布局错乱

### Additional comments

![image](https://user-images.githubusercontent.com/28865316/188039370-ed6acd3f-7b76-4a59-8a73-c658f742a0fc.png)

**Comment by tolking** [comment]
same as #9560
