### ISSUE TITLE
[All] 文档经常打开太慢了，甚至打不开，解决一下呗

### ISSUE THREAD

**Issue by dogloves** [element-plus/element-plus#9600]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.10`
- Browser / OS: `chome`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN)

### Steps to reproduce

经常出现呢，打开特别慢，甚至直接打不开

### What is Expected?

加速到正常能顺利打开就行

### What is actually happening?

太慢

### Additional comments

_(empty)_

**Comment by xiaoxian521** [comment]
发布过程中 出现这种情况正常

**Comment by chenxch** [comment]
same：#9196
