### ISSUE TITLE
[Component] [alert] El-Alert title slot is using el-alert__description

### ISSUE THREAD

**Issue by glitchcodes** [element-plus/element-plus#9616]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `Chrome 104.0.0.0 / Mac OS 12.5.1`
- Build Tool: `Vite`

### Related Component

- `el-alert`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzaG93PXJlZihmYWxzZSlcbmNvbnN0IHNob3cxPXJlZihmYWxzZSlcblxuY29uc3Qgc2hvd0FsZXJ0PWZ1bmN0aW9uKCl7XG4gIHNob3cudmFsdWU9dHJ1ZVxuICBzaG93MS52YWx1ZT10cnVlXG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1hbGVydCB0aXRsZT1cInRoaXMgaXMgd29ya2luZyBmaW5lXCIgdHlwZT1cImVycm9yXCIgdi1zaG93PVwic2hvd1wiIEBjbG9zZT1cInNob3cgPSBmYWxzZVwiPjwvZWwtYWxlcnQ+XG4gIFxuICA8YnI+XG4gIFxuICA8ZWwtYWxlcnQgdHlwZT1cImVycm9yXCIgdi1zaG93PVwic2hvd1wiIEBjbG9zZT1cInNob3cxID0gZmFsc2VcIj5cbiAgXHQ8c2xvdCBuYW1lPVwidGl0bGVcIj50aGlzIGlzIGNvbnNpZGVyZWQgZWwtYWxlcnRfX2Rlc2NyaXB0aW9uIGRlc3BpdGUgdGhlIHNsb3QgbmFtZTwvc2xvdD5cbiAgPC9lbC1hbGVydD5cbiAgXG4gIDxicj5cbiAgXG4gIDxlbC1idXR0b24gQGNsaWNrPVwic2hvd0FsZXJ0XCI+5pi+56S6YWxlcnQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Use slot with name "title" on el-alert component

### What is Expected?

Same result as using "title" as attribute

### What is actually happening?

Content is rendered as description

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
Read Vue docs please.

https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBzaG93PXJlZihmYWxzZSlcbmNvbnN0IHNob3cxPXJlZihmYWxzZSlcblxuY29uc3Qgc2hvd0FsZXJ0PWZ1bmN0aW9uKCl7XG4gIHNob3cudmFsdWU9dHJ1ZVxuICBzaG93MS52YWx1ZT10cnVlXG59XG5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1hbGVydCB0aXRsZT1cInRoaXMgaXMgd29ya2luZyBmaW5lXCIgdHlwZT1cImVycm9yXCIgdi1zaG93PVwic2hvd1wiIEBjbG9zZT1cInNob3cgPSBmYWxzZVwiPjwvZWwtYWxlcnQ+XG4gIFxuICA8YnI+XG4gIFxuICA8ZWwtYWxlcnQgdHlwZT1cImVycm9yXCIgdi1zaG93PVwic2hvd1wiIEBjbG9zZT1cInNob3cxID0gZmFsc2VcIj5cbiAgXHQ8dGVtcGxhdGUgI3RpdGxlPnRoaXMgaXMgY29uc2lkZXJlZCBlbC1hbGVydF9fZGVzY3JpcHRpb24gZGVzcGl0ZSB0aGUgc2xvdCBuYW1lPC90ZW1wbGF0ZT5cbiAgPC9lbC1hbGVydD5cbiAgXG4gIDxicj5cbiAgXG4gIDxlbC1idXR0b24gQGNsaWNrPVwic2hvd0FsZXJ0XCI+5pi+56S6YWxlcnQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=
