### ISSUE TITLE
[Component] [loading] two consecutive loading service, `el-loading-parent--relative` still on the target

### ISSUE THREAD

**Issue by wiidede** [element-plus/element-plus#9627]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.16`
- Browser / OS: `Chrome 104/ Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cIm9wZW5GdWxsU2NyZWVuMlwiPiBBcyBhIHNlcnZpY2UgPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3gsIEVsTG9hZGluZyB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbiAgXG5cbmNvbnN0IG9wZW5GdWxsU2NyZWVuMiA9ICgpID0+IHtcbiAgY29uc3QgbG9hZGluZyA9IEVsTG9hZGluZy5zZXJ2aWNlKHsgZnVsbHNjcmVlbjogdHJ1ZSB9KVxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBFbE1lc3NhZ2Uuc3VjY2Vzcygn5oiQ5Yqf77yBJyk7XG4gICAgbG9hZGluZy5jbG9zZSgpXG4gICAgXG4gICAgY29uc3QgbG9hZGluZzIgPSBFbExvYWRpbmcuc2VydmljZSh7IGZ1bGxzY3JlZW46IHRydWUgfSlcbiAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgIEVsTWVzc2FnZS5zdWNjZXNzKCfmiJDlip9477yBJyk7XG4gICAgICBsb2FkaW5nMi5jbG9zZSgpXG4gICAgfSwgNTAwKVxuICB9LCA1MDApXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

loading service.... close and then open a new loading service at once... close

### What is Expected?

target's `el-loading-parent--relative` disapper

### What is actually happening?

`el-loading-parent--relative` still on the target. And nothing can be clicked

### Additional comments

The problem becomes serious after this commit: https://github.com/element-plus/element-plus/commit/5109da3b3cb6186f391d043603e5f4c1688fd344

**Comment by JCAlways** [comment]
问题严重性很大

**Comment by wiidede** [comment]
> 问题严重性很大

😂可以暂时覆盖`el-loading-parent--relative`中的两个css样式，等下个版本修复了再去掉吧
