### ISSUE TITLE
[Component] [select-v2] [Component] [Select V2 ] el-select-v2 multiple options为对象数组时候数据回显无法显示label

### ISSUE THREAD

**Issue by Natsumeo** [element-plus/element-plus#9628]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.16`
- Browser / OS: `macOS BigS Sur 11.4`
- Build Tool: `Webpack`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3Qgb3B0aW9ucyA9IFt7XG4gIGNvZGU6IHtcbiAgICBjb2RlOiAnMScsXG4gICAgbmFtZTogJ3gnXG4gIH0sXG4gIGxhYmVsOiAneCdcbn0sIHtcbiAgY29kZToge1xuICAgIGNvZGU6ICcyJyxcbiAgICBuYW1lOiAneSdcbiAgfSxcbiAgbGFiZWw6ICd5J1xufSwge1xuICBjb2RlOiB7XG4gICAgY29kZTogJzMnLFxuICAgIG5hbWU6ICd6J1xuICB9LFxuICBsYWJlbDogJ3onXG59XTtcblxuY29uc3Qgc2VsZWN0ZWQgPSByZWYoW3tjb2RlOicyJyxcbiAgbmFtZToneSd9XSk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICB7eyBzZWxlY3RlZCB9fVxuICA8ZWwtc2VsZWN0LXYyIHYtbW9kZWw9XCJzZWxlY3RlZFwiIDpvcHRpb25zPVwib3B0aW9uc1wiIG11bHRpcGxlIHN0eWxlPVwid2lkdGg6IDIwMHB4XCIgdmFsdWUta2V5PVwiY29kZVwiLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

el-select-v2 v-model绑定值赋值为对象数组，对象格式和options中的对象格式一致

### What is Expected?

el-select-v2下拉选项选中且正确显示label

### What is actually happening?

el-select-v2下拉选项命中但label没有显示

### Additional comments

_(empty)_

**Comment by holylinyy** [comment]
不要使用对象当value-key获取得值，原因有下面2点
1. 传下去options中value-key值必须和当前选中得值是同一个对象(对象地址必须一致)
2. 由于proxy得原因，下面源码中selected是代理对象，与options中值作全等判断永远为false,此时如果真的需要支持value-key为对象，则需要用`toRaw`包裹
```
if (props.multiple) {
      if ((props.modelValue as Array<any>).length > 0) {
        let initHovering = false
        states.cachedOptions.length = 0
        states.previousValue = props.modelValue.toString()
        ;(props.modelValue as Array<any>).forEach((selected) => {
          const itemIndex = filteredOptions.value.findIndex(
            (option) => getValueKey(option) === selected
          )
          if (~itemIndex) {
            states.cachedOptions.push(
              filteredOptions.value[itemIndex] as Option
            )
            if (!initHovering) {
              updateHoveringIndex(itemIndex)
            }
            initHovering = true
          }
        })
      } else {
        states.cachedOptions = []
        states.previousValue = ''
      }
    }
```
