### ISSUE TITLE
[Component] [message] vue3使用element-plus Message提示无法关闭

### ISSUE THREAD

**Issue by zhangxuewei1263944101** [element-plus/element-plus#9629]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.8`
- Element Plus Version: `2.2.12`
- Browser / OS: `chrome版本 93.0.4577.82（正式版本） （64 位） window `
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Link](http://www.flowcloud.work)

### Steps to reproduce

点击 注册 菜单-》点击 注册 按钮

### What is Expected?

可以不报错，可以关闭提示消息

### What is actually happening?

可以正常弹框但是无法正确关闭，而且会报错误
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'visible')
    at Object.close (method.ts:67)
    at closeMessage (method.ts:41)
    at onClose (method.ts:54)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6992)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:7001)
    at callHook3 (runtime-core.esm-bundler.js:1657)
    at Object.leave (runtime-core.esm-bundler.js:1734)
    at updated (runtime-dom.esm-bundler.js:1454)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6992)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:7001)
close @ method.ts:67
closeMessage @ method.ts:41
onClose @ method.ts:54
callWithErrorHandling @ runtime-core.esm-bundler.js:6992
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:7001
callHook3 @ runtime-core.esm-bundler.js:1657
leave @ runtime-core.esm-bundler.js:1734
updated @ runtime-dom.esm-bundler.js:1454
callWithErrorHandling @ runtime-core.esm-bundler.js:6992
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:7001
invokeDirectiveHook @ runtime-core.esm-bundler.js:3346
(anonymous) @ runtime-core.esm-bundler.js:4281
flushPostFlushCbs @ runtime-core.esm-bundler.js:7193
flushJobs @ runtime-core.esm-bundler.js:7230
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:7122
queueJob @ runtime-core.esm-bundler.js:7116
(anonymous) @ runtime-core.esm-bundler.js:4640
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:987
close2 @ message.vue:107
(anonymous) @ runtime-dom.esm-bundler.js:1400
callWithErrorHandling @ runtime-core.esm-bundler.js:6992
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:7001
invoker @ runtime-dom.esm-bundler.js:347

### Additional comments

代码的地址：https://gitee.com/zxwAdd_admin/flow-tools
请大佬指正错误，如果可以的话 官网哪里可以查阅到 element-plus和vue3兼容的版本

**Comment by zhangxuewei1263944101** [comment]
打包好，线上是正常的，开发环境本地不正常。。。。。。那个复现连接是正常的

**Comment by MrCat33** [comment]
您好，您提供的Link和所提供的仓库代码与您描述的情况存在不一致的情况，我在您提供的代码仓库尝试复现此情况，却是正常的，如果可以的话请提供一个最小复现方便解决您的问题

**Comment by zhangxuewei1263944101** [comment]
您好！这个问题确实在本地环境存在！难道是我node版本问题吗？
node版本：v16.16.0
npm版本：8.16.0
我尝试使用Element Plus Playground复现，但是不知道如何引入对应的vue3、element-plus的版本
于是我将我项目中的 vue3的版本号 和element-plus的版本号 
更改成了Element Plus Playground中的版本（vue3： 3.2.38  Element Plus： 2.2.16）
重新install项目，再次运行就可以了。
我不知道什么原因，感谢您的回复，开源万岁。

**Comment by holazz** [comment]
可能和这个有关 https://github.com/element-plus/element-plus/issues/9172，升级 Element Plus 到最新版本。

**Comment by chenxch** [comment]
请将vue升级到3.2.26之后的版本， Element Plus 升级到最新版本，3.2.x部分版本存在一些问题。如果还不能解决请重新reopen issue.
