### ISSUE TITLE
time-select picker-options seems not working

### ISSUE THREAD

**Issue by Zhaocl1997** [element-plus/element-plus#963]
https://element-plus.gitee.io/#/zh-CN/component/time-select , offical doc is sample

**Comment by Zhaocl1997** [comment]
more specific "step" not working

**Comment by JeremyWuuuuu** [comment]
https://github.com/element-plus/element-plus/issues/162#issuecomment-676052160 check this out, picker-options has already been deprecated

**Comment by JeremyWuuuuu** [comment]
We didn't get the docs updated in time. Sorry for that.
cc @zazzaz

**Comment by Zhaocl1997** [comment]
got it
