### ISSUE TITLE
Bug & improve with scrollbar

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#964]
1. In many components like `select`, `time-select`, once click the scrollbar, when mouse up, it still scroll.
2. ![image](https://user-images.githubusercontent.com/38392315/101854442-86f3e580-3b9c-11eb-8ee4-a99b72f287b8.png)
![image](https://user-images.githubusercontent.com/38392315/101854300-38464b80-3b9c-11eb-824d-c5a183a0a17d.png)
![image](https://user-images.githubusercontent.com/38392315/101854312-3bd9d280-3b9c-11eb-9034-f77b99faf80e.png)
Scrollbar should has default `height: 100%`, even though, the horizontal scrollbar has a native bar.

**Comment by JeremyWuuuuu** [comment]
Yes, I think we have already known this for a while now, you can see this #716 , you have any suggestion on this fix? #716 didn't have any test cases against the changes, so I couldn't merge it. You want a PR?

**Comment by JeremyWuuuuu** [comment]
Again, I am so thankful that we have contributors like you.

**Comment by kooriookami** [comment]
> Yes, I think we have already known this for a while now, you can see this #716 , you have any suggestion on this fix? #716 didn't have any test cases against the changes, so I couldn't merge it. You want a PR?

I could fix part of these problems, some place I changed will cause damage. I don't understand the effect of some attributes like `native`, `gutter` of scrollbar. I don't know the meaning of their existence. I think if it's a historical legacy that  worth an architect to refactor or improve. ORZ
