### ISSUE TITLE
[i18n] [All] 在vite构建模式，按需引入情况下，使用<el-config-provider/>配置国际化失败，placeholder都是英文

### ISSUE THREAD

**Issue by AprildreamMI** [element-plus/element-plus#9647]
Bug Type: **`i18n`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: ` Chrome 104.0.0.0 / Windows 10和11`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/AprildreamMI/vite-vue-elplus-demo)

### Steps to reproduce

```vue
<template>
  <el-config-provider :locale="locale">
    <router-view/>
  </el-config-provider>
</template>

<script>
  import { defineComponent } from 'vue'
  import { ElConfigProvider } from 'element-plus'

  import zhCn from 'element-plus/lib/locale/lang/zh-cn'

  export default defineComponent({
    components: {
      ElConfigProvider,
    },
    setup() {
      return {
        locale: zhCn,
      }
    },
  })
</script>
```

### What is Expected?

国际化中文生效

### What is actually happening?

国际化中文未生效

### Additional comments

按照官网来配置的

**Comment by AprildreamMI** [comment]
又试了几个组件，**国际化配置是成功的**，但例如<el-select/>等拥有`placeholder`的组件，他们的`placeholder`默认都是英文
在`select.vue`中
![image](https://user-images.githubusercontent.com/31964372/188537097-8cc11bb9-a2e2-4c15-a6cf-c74a2c03ac2e.png)
说明，在`useSelect.js`的`useSelectStates`方法中[currentPlaceholder: t('el.select.placeholder')](https://github.com/element-plus/element-plus/blob/328cb574aec1ba5e30bdd9d76a298f2f79035340/packages/components/select/src/useSelect.ts#L57)未生效
![企业微信截图_16624324373705](https://user-images.githubusercontent.com/31964372/188537475-df8f1f53-204a-423f-a788-68c001d6b2d6.png)

**Comment by holazz** [comment]
[这里](https://github.com/AprildreamMI/vite-vue-elplus-demo/blob/9732b7b3646a2f8f88ddc16bf7c93ef29601e78e/src/components/HelloWorld.vue#L6)不要设置 placeholder，因为这里会覆盖国际化预设的值
<img width="619" alt="image" src="https://user-images.githubusercontent.com/23100055/188539670-975224d2-faac-4182-a413-8a7151d16a77.png">

**Comment by AprildreamMI** [comment]
> [这里](https://github.com/AprildreamMI/vite-vue-elplus-demo/blob/9732b7b3646a2f8f88ddc16bf7c93ef29601e78e/src/components/HelloWorld.vue#L6)不要设置 placeholder，因为这里会覆盖国际化预设的值 <img alt="image" width="619" src="https://user-images.githubusercontent.com/23100055/188539670-975224d2-faac-4182-a413-8a7151d16a77.png">

嗨，没发现，直接从官网复制来的例子，没想到他写了placeholder，谢谢

**Comment by holazz** [comment]
> > [这里](https://github.com/AprildreamMI/vite-vue-elplus-demo/blob/9732b7b3646a2f8f88ddc16bf7c93ef29601e78e/src/components/HelloWorld.vue#L6)不要设置 placeholder，因为这里会覆盖国际化预设的值 <img alt="image" width="619" src="https://user-images.githubusercontent.com/23100055/188539670-975224d2-faac-4182-a413-8a7151d16a77.png">
> 
> 嗨，没发现，直接从官网复制来的例子，没想到他写了placeholder，谢谢

不客气！
