### ISSUE TITLE
el-upload docs Vue warn

### ISSUE THREAD

**Issue by Lliuxs** [element-plus/element-plus#966]
打不来dialog 看控制台有警告
![image](https://user-images.githubusercontent.com/35122287/101859167-2073c500-3ba6-11eb-8c20-f80505afedc3.png)

这里使用直接用v-model吧 文档使用了v-model:visible

**Comment by JeremyWuuuuu** [comment]
Right, we didn't update documentation in time. Could you help us with a PR?

**Comment by Lliuxs** [comment]
1

**Comment by Lliuxs** [comment]
https://github.com/element-plus/element-plus/pull/975#issue-536757241

**Comment by Lliuxs** [comment]
当我点开预览的时候 img设置的100%变成了width:0 显示不出来
![image](https://user-images.githubusercontent.com/35122287/101897982-59338e80-3be6-11eb-8d79-d8213bc5c0c0.png)
https://codesandbox.io/s/nostalgic-noether-yz62y?file=/src/App.vue
但是element不会这样
https://codesandbox.io/s/hopeful-ritchie-sxh2u?file=/src/App.vue

**Comment by Ryan2128** [comment]
> 当我点开预览的时候 img设置的100%变成了width:0 显示不出来
> ![image](https://user-images.githubusercontent.com/35122287/101897982-59338e80-3be6-11eb-8d79-d8213bc5c0c0.png)
> https://codesandbox.io/s/nostalgic-noether-yz62y?file=/src/App.vue
> 但是element不会这样
> https://codesandbox.io/s/hopeful-ritchie-sxh2u?file=/src/App.vue

This is a bug of vue3, you can just put an img tag with attr of width, the width will still be 0.

**Comment by Ryan2128** [comment]
You can check this [issue](https://github.com/vuejs/vue-next/issues/2677)

**Comment by JeremyWuuuuu** [comment]
Closing due to #976
