### ISSUE TITLE
[Component] [select-v2] arr.includes is not a function

### ISSUE THREAD

**Issue by GamerGirlandCo** [element-plus/element-plus#9680]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0`
- Build Tool: `Nuxt`

### Related Component

- `el-select-v2`

### Reproduction Link

[Link](https://stackblitz.com/edit/nuxt-starter-1zx389?file=app.vue)

### Steps to reproduce

```vue
<script setup>
import { ElFormItem, ElSelectV2 } from 'element-plus';
import { Form as VeeForm, Field, useForm } from 'vee-validate';
import { bands } from './data.ts';
const options = bands
  .filter((a) => a.name != '')
  .map((a) => ({ value: a._id, label: a.name }));
</script>
<template>
  <div>
    <vee-form :validation-schema="schema">
          <Field
            name="bands"
            :value="[]"
            v-slot="{ value, field, errorMessage }"
          >
            <el-form-item :error="errorMessage" label="Bands">
              <el-select-v2
                :name="field.name"
                :options="options"
                multiple
                filterable
                :v-bind="field"
              />
            </el-form-item>
          </Field>
    </vee-form>
  </div>
</template>
```

### What is Expected?

i expect the component to render

### What is actually happening?

i get an error in the console that says
`arr.includes is not a function`

### Additional comments

i'm using vee-validate if that helps

**Comment by zhiyuanzmj** [comment]
Related Issues  https://github.com/vuejs/core/issues/5847
