### ISSUE TITLE
[table] table 这段代码的作用是啥？

### ISSUE THREAD

**Issue by gjfei** [element-plus/element-plus#9686]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IGdldERhdGUoc2NvcGUucm93KSB9fTwvc3Bhbj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1wb3BvdmVyIGVmZmVjdD1cImxpZ2h0XCIgdHJpZ2dlcj1cImhvdmVyXCIgcGxhY2VtZW50PVwidG9wXCIgd2lkdGg9XCJhdXRvXCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PlxuICAgICAgICAgICAgPGRpdj5uYW1lOiB7eyBzY29wZS5yb3cubmFtZSB9fTwvZGl2PlxuICAgICAgICAgICAgPGRpdj5hZGRyZXNzOiB7eyBzY29wZS5yb3cuYWRkcmVzcyB9fTwvZGl2PlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgICA8ZWwtdGFnPnt7IHNjb3BlLnJvdy5uYW1lIH19PC9lbC10YWc+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC1wb3BvdmVyPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiT3BlcmF0aW9uc1wiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIiBAY2xpY2s9XCJoYW5kbGVFZGl0KHNjb3BlLiRpbmRleCwgc2NvcGUucm93KVwiXG4gICAgICAgICAgPkVkaXQ8L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICAgIDxlbC1idXR0b25cbiAgICAgICAgICBzaXplPVwic21hbGxcIlxuICAgICAgICAgIHR5cGU9XCJkYW5nZXJcIlxuICAgICAgICAgIEBjbGljaz1cImhhbmRsZURlbGV0ZShzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgID5EZWxldGU8L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IFRpbWVyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhZGRyZXNzOiBzdHJpbmdcbn1cblxuY29uc3QgaGFuZGxlRWRpdCA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cbmNvbnN0IGhhbmRsZURlbGV0ZSA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG4gIFxuY29uc3QgIGdldERhdGUgPSAocm93KT0+e1xuICAgIGNvbnNvbGUubG9nKHJvdyxKU09OLnN0cmluZ2lmeShyb3cpKVxuICBcbiAgICByZXR1cm4gcm93LmRhdGVcbiAgfVxuXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

某些情况会导致内部使用default slot 去获取row 中的值出错

### What is Expected?

不会出错

### What is actually happening?

报错

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/33827314/188822242-82e984d6-a1a0-4ba0-8352-6e46537de9a4.png)

**Comment by btea** [comment]
fix https://github.com/element-plus/element-plus/issues/6370

**Comment by gjfei** [comment]
> 

可能没表达清楚，这里获取children  的作用是什么？

**Comment by gjfei** [comment]
> fix #6370

可能没有表达清楚，这里获取儿童的作用是什么？

**Comment by btea** [comment]
这里应该是过滤了一些不标准的子节点，防止渲染错误，比如注释

**Comment by btea** [comment]
> 执行slots.default() 传递空的row 就可能会造成业务代码执行出错   

这个能提供一个链接吗？

**Comment by gjfei** [comment]
> > 执行slots.default() 传递空的row 就可能会造成业务代码执行出错
> 
> 这个能提供一个链接吗？

上面已经提供了，注意看log

**Comment by btea** [comment]
直接打开就会报错吗？我这边打开是正常的。

**Comment by gjfei** [comment]
> 直接打开就会报错吗？我这边打开是正常的。

不是，我很难复现出报错的情况，这里的如果row 是一个空对象，如果我去取深层的数据，就会出现问题才对，但不知道为什么这个demo 不会出现，我们发现问题也是在生产环境发现

**Comment by btea** [comment]
会不会是版本的原因？你们element-plus和vue版本是多少？

**Comment by gjfei** [comment]
> 会不会是版本的原因？你们element-plus和vue版本是多少？

不会，你看这个的输入，row 是空的对象，这里就一定不对。

**Comment by gjfei** [comment]
> 会不会是版本的原因？你们element-plus和vue版本是多少？

#9029 看这个，我们也是只有在生产环境会出现

**Comment by btea** [comment]
好的，理解你说的问题了

**Comment by MrWeilian** [comment]
这段代码的作用是处理多级表头功能的，主要通过获取 `slot` 内容过滤掉非 `<table-column>` 的 `children` 以此来插入多级表头所需要的树形列数据。详细了解可以看：[el-table 多级表头实现原理](https://juejin.cn/post/7184309446439338043) ，里面有详细介绍这段 `render` 的作用。
