### ISSUE TITLE
[Component] [table-column, switch] el-table-column 内部使用 el-switch，el-switch 的 beforeChange 会执行多次

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#9692]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-switch`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTd2l0Y2hcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgIDxlbC1zd2l0Y2hcbiAgICAgICAgICAgIHYtbW9kZWw9XCJzY29wZS5yb3cuc3dpdGNoXCJcbiAgICAgICAgICAgIDpiZWZvcmUtY2hhbmdlPVwiYmVmb3JlQ2hhbmdlKHNjb3BlLnJvdylcIlxuICAgICAgICAgIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25zXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUVkaXQoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RWRpdDwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvblxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgICAgdHlwZT1cImRhbmdlclwiXG4gICAgICAgICAgQGNsaWNrPVwiaGFuZGxlRGVsZXRlKHNjb3BlLiRpbmRleCwgc2NvcGUucm93KVwiXG4gICAgICAgICAgPkRlbGV0ZTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIHN3aXRjaDogYm9vbGVhblxuICBhZGRyZXNzOiBzdHJpbmdcbn1cblxuY29uc3QgaGFuZGxlRWRpdCA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cbmNvbnN0IGhhbmRsZURlbGV0ZSA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3dpdGNoOiB0cnVlLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgc3dpdGNoZXI6IGZhbHNlLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG4gIFxuY29uc3QgYmVmb3JlQ2hhbmdlID0gKHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhyb3cpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.F12打开控制台
2.点击列的switch组件，可以看到控制台有多次console打印

### What is Expected?

el-switch 的 beforeChange 执行一次

### What is actually happening?

el-switch 的 beforeChange 执行多次

### Additional comments

_(empty)_

**Comment by JackieCheung** [comment]
btw 初始化的时候 `beforeChange` 也会执行多次

**Comment by mrtr9** [comment]
> btw 初始化的时候 `beforeChange` 也会执行

请问解决了吗？

**Comment by init-qy** [comment]
我觉得你可能需要实现这个功能    [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTd2l0Y2hcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIHYtbW9kZWw9XCJzY29wZS5yb3cuc3dpdGNoXCJcbiAgICAgICAgICA6YmVmb3JlLWNoYW5nZT1cImJlZm9yZUNoYW5nZShzY29wZS5yb3cpXCJcbiAgICAgICAgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk9wZXJhdGlvbnNcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiaGFuZGxlRWRpdChzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgID5FZGl0PC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICB0eXBlPVwiZGFuZ2VyXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVEZWxldGUoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RGVsZXRlPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBUaW1lciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgc3dpdGNoOiBib29sZWFuXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5jb25zdCBoYW5kbGVFZGl0ID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuY29uc3QgaGFuZGxlRGVsZXRlID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzd2l0Y2g6IHRydWUsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3dpdGNoOiBmYWxzZSxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBzd2l0Y2g6IGZhbHNlLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG5cbmNvbnN0IGJlZm9yZUNoYW5nZSA9IChyb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coJ2hlcmUgZ2V0IGZ1bmMnKVxuICByZXR1cm4gZnVuY3Rpb24gKCkge1xuICAgIGNvbnNvbGUubG9nKHRoaXMpXG4gICAgcmV0dXJuIHRydWVcbiAgfS5iaW5kKHJvdylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

其中 beforeChange 根据源码和文档看 应当是个方法 返回 Promise<boolean> | boolean
并且没有参数

所以或许可以参照这个写法
```
const beforeChange = (row: User) => {
  console.log('here get func')
  return function () {
    console.log(this)
    return true
  }.bind(row)
}
```

**Comment by mrtr9** [comment]
> 我觉得你可能需要实现这个功能 [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTd2l0Y2hcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIHYtbW9kZWw9XCJzY29wZS5yb3cuc3dpdGNoXCJcbiAgICAgICAgICA6YmVmb3JlLWNoYW5nZT1cImJlZm9yZUNoYW5nZShzY29wZS5yb3cpXCJcbiAgICAgICAgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk9wZXJhdGlvbnNcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1idXR0b24gc2l6ZT1cInNtYWxsXCIgQGNsaWNrPVwiaGFuZGxlRWRpdChzY29wZS4kaW5kZXgsIHNjb3BlLnJvdylcIlxuICAgICAgICAgID5FZGl0PC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uXG4gICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICB0eXBlPVwiZGFuZ2VyXCJcbiAgICAgICAgICBAY2xpY2s9XCJoYW5kbGVEZWxldGUoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RGVsZXRlPC9lbC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBUaW1lciB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGRhdGU6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgc3dpdGNoOiBib29sZWFuXG4gIGFkZHJlc3M6IHN0cmluZ1xufVxuXG5jb25zdCBoYW5kbGVFZGl0ID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuY29uc3QgaGFuZGxlRGVsZXRlID0gKGluZGV4OiBudW1iZXIsIHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhpbmRleCwgcm93KVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzd2l0Y2g6IHRydWUsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3dpdGNoOiBmYWxzZSxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBzd2l0Y2g6IGZhbHNlLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG5cbmNvbnN0IGJlZm9yZUNoYW5nZSA9IChyb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coJ2hlcmUgZ2V0IGZ1bmMnKVxuICByZXR1cm4gZnVuY3Rpb24gKCkge1xuICAgIGNvbnNvbGUubG9nKHRoaXMpXG4gICAgcmV0dXJuIHRydWVcbiAgfS5iaW5kKHJvdylcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)
> 
> 其中 beforeChange 根据源码和文档看 应当是个方法 返回 Promise | boolean 并且没有参数
> 
> 所以或许可以参照这个写法
> 
> ```
> const beforeChange = (row: User) => {
>   console.log('here get func')
>   return function () {
>     console.log(this)
>     return true
>   }.bind(row)
> }
> ```

这个功能初始化就会执行……能否让他初始化的时候不执行

**Comment by JackieCheung** [comment]
> 

暂时hack的处理方法，定义一个`currentRow`，给 `switch` 组件绑定 `click` 事件，`click`的时候把当前行赋值给 `currentRow `，在`beforeChange` 内部先判断当前的 `row` 和 `currentRow` 的 id 是否一致，那么初始化的时候，`currentRow`是空的，自然不会执行下面的逻辑了

**Comment by mrtr9** [comment]
谢谢了，我去试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 上午10:41
***@***.***&gt;;
抄送:&nbsp;"1'm ***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [table-column, switch] el-table-column 内部使用 el-switch，el-switch 的 beforeChange 会执行多次 (Issue #9692)





   
暂时hack的处理方法，定义一个currentRow，给 switch 组件绑定 click 事件，click的时候把当前行赋值给 currentRow ，在beforeChange 内部先判断当前的 row 和 currentRow 的 id 是否一致，那么初始化的时候，currentRow是空的，自然不会执行下面的逻辑了

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTd2l0Y2hcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXN3aXRjaFxuICAgICAgICAgIHYtbW9kZWw9XCJzY29wZS5yb3cuc3dpdGNoXCJcbiAgICAgICAgICA6YmVmb3JlLWNoYW5nZT1cIigpPT5iZWZvcmVDaGFuZ2Uoc2NvcGUucm93KVwiXG4gICAgICAgIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25zXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUVkaXQoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RWRpdDwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvblxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgICAgdHlwZT1cImRhbmdlclwiXG4gICAgICAgICAgQGNsaWNrPVwiaGFuZGxlRGVsZXRlKHNjb3BlLiRpbmRleCwgc2NvcGUucm93KVwiXG4gICAgICAgICAgPkRlbGV0ZTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIHN3aXRjaDogYm9vbGVhblxuICBhZGRyZXNzOiBzdHJpbmdcbn1cblxuY29uc3QgaGFuZGxlRWRpdCA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cbmNvbnN0IGhhbmRsZURlbGV0ZSA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3dpdGNoOiB0cnVlLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgc3dpdGNoOiBmYWxzZSxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBzd2l0Y2g6IGZhbHNlLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuXG5jb25zdCBiZWZvcmVDaGFuZ2UgPSAocm93OiBVc2VyKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdoZXJlIGdldCBmdW5jJyxyb3cpXG4gIHJldHVybiB0cnVlXG5cbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319) 
这个你们可以看看，初始化会触发一次的问题我晚些时候再看看。

**Comment by chenxch** [comment]
props参数如果直接写beforeChange(scope.row)，beforeChange函数是立即执行的，你们应该是把@这个用法混了哈。

**Comment by chenxch** [comment]
我先关闭issue了，如果还有问题你们可以reopen
