### ISSUE TITLE
[Build] 暗黑模式报错

### ISSUE THREAD

**Issue by zhengyimeng** [element-plus/element-plus#9699]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.16`
- Browser / OS: `macOS`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/zhengyimeng/element-frame)

### Steps to reproduce

git clone https://github.com/zhengyimeng/element-frame.git
git checkout element-dark
yarn install
yarn dev

### What is Expected?

暗黑模式的使用

### What is actually happening?

暗黑模式报错: This variable is available from multiple global modules.

### Additional comments

/provider/Element.vue 切换 html 的class
/assets/css/element.scss 控制 dark 颜色变量
vite.config.js sass.additation 全局自动引入

**Comment by chenxch** [comment]
![image](https://user-images.githubusercontent.com/23251408/190839265-f7206506-49ad-4f21-931f-7e32e5246f21.png)
![image](https://user-images.githubusercontent.com/23251408/190839277-5842b1f4-49eb-487f-8545-6810879b1a8f.png)
请按照截图操作，合理的使用sass
![image](https://user-images.githubusercontent.com/23251408/190839302-92b40718-c8aa-45d1-8a8a-8d4dac3fd20b.png)

**Comment by zhengyimeng** [comment]
我觉得我知道在什么时候用 @forward 和 @use, 我的变量需要给所有的文件用，如果是 @use，它实现不了我的需求

**Comment by zhengyimeng** [comment]
既然只需要 @forwar dark，你的dark 文件就应该包含 common 的变量
我不需要在别的文件引入的是 @use "element-plus/theme-chalk/src/common/var.scss";
而应该是 @use "element-plus/theme-chalk/src/dark/var.scss"
这就是我报错的原因，我已经将它改正
在 element-plus/theme-chalk/src/dark/var.scss 文件中，你应该 @forward "../common/var.scss"

**Comment by chenxch** [comment]
[demo](https://github.com/element-plus/element-plus-vite-starter) 这有个暗黑模式的demo，你可以看看

**Comment by zhengyimeng** [comment]
暗黑模式我可以出来的，我是说这些变量我要全局使用
<img width="472" alt="image" src="https://user-images.githubusercontent.com/20783425/196111506-5d3416a1-e4f6-4383-a6c3-1941496c8d40.png">
