### ISSUE TITLE
[Component] [table] el-table

### ISSUE THREAD

**Issue by FangFangDoris** [element-plus/element-plus#9708]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.9`
- Browser / OS: `Firefox-43，chrome-48`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html)

### Steps to reproduce

列表的每一列开启固定模式

### What is Expected?

不要用最新的定位属性，不兼容低版本浏览器，重写样式太麻烦了，效果也不好

### What is actually happening?

表格列固定的时候低版本浏览器不识别现在的定位方式

### Additional comments

_(empty)_

**Comment by tolking** [comment]
参考[环境支持](https://element-plus.org/zh-CN/guide/installation.html#%E7%8E%AF%E5%A2%83%E6%94%AF%E6%8C%81)
