### ISSUE TITLE
[Component] [form-item] 表单元素触发焦点位置错误

### ISSUE THREAD

**Issue by huzedong2015** [element-plus/element-plus#9719]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `chrome 102`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBmb3JtRGF0YSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogXCJcIlxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtXG4gICAgbGFiZWwtcG9zaXRpb249XCJ0b3BcIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIueUqOaIt+WQje+8iOeCueWHu+i/meS4quWMuuWfn+S5n+iDveinpuWPkWlucHV054Sm54K577yJXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm1EYXRhLm5hbWVcIiAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+ICBcbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、label位置为`top`
2、点击label区域也能触发`el-input`获得焦点

### What is Expected?

点击label区域不触发获得焦点

### What is actually happening?

点击label区域触发获得焦点

### Additional comments

不止`el-input`其他表单组件也这样

**Comment by chenxch** [comment]
Hi, thanks for your feedback, but what about this question, it's a [W3C standard](https://www.w3.org/WAI/tutorials/forms/labels/).

**Comment by chenxch** [comment]
@huzedong2015 
This behavior can be prevented stylistically by adding `pointer-events:` none; to the `<label>` elements.
This is the solution from @Giwayume , you can try it if you need it.
