### ISSUE TITLE
[Docs] [calendar] calendar 组件的文档中，插槽名称写错，源码中是 dateCell ，但是文档中却写的是 date-cell，导致自定义内容不生效

### ISSUE THREAD

**Issue by stefan-ysh** [element-plus/element-plus#9736]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.16`
- Browser / OS: `Chrome 105.0.5195.102`
- Build Tool: `Vite`

### Related Component

- `el-calendar`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/calendar.html)

### Steps to reproduce

按照官方文档引入日历组件并尝试自定义内容即可复现

### What is Expected?

自定义内容显示

### What is actually happening?

通过插槽自定义的内容并未按照预期显示

### Additional comments

希望贵司开发人员尽快修复，谢谢

**Comment by btea** [comment]
fixed #9590
