### ISSUE TITLE
when el-table-filter__list too much content,height cannot display normally

### ISSUE THREAD

**Issue by sundongzi** [element-plus/element-plus#974]
Element UI version
element-plus

Browsers version
chrome 86.0.4240.198（正式版本）

Vue version
3.0.4

**Comment by SimonaliaChen** [comment]
Issues without a valid reproduction link will be closed directly. And, please specify the version of `element-plus`

**Comment by JeremyWuuuuu** [comment]
Closing due to no demo, feel free to reopen if you need to.
