### ISSUE TITLE
[Style] [input, select] 组合Input设置Size为Large时组合Select，Select高度不正确

### ISSUE THREAD

**Issue by Thccuy** [element-plus/element-plus#9742]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.16`
- Browser / OS: `Chrome/105.0.5195.102`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgc2l6ZT1cImxhcmdlXCI+XG4gIFx0PHRlbXBsYXRlICNwcmVwZW5kPlxuICAgIFx0PGVsLXNlbGVjdD48L2VsLXNlbGVjdD5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWlucHV0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用el-input，设置size为large
在el-input内使用template #prepend来构建组合输入
在el-input内使用el-select

### What is Expected?

el-select的高度与el-select一致

### What is actually happening?

el-select的高度与el-select不一致

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
插槽并未提供size透传，需要自行处理哦。
