### ISSUE TITLE
[Component] [tree]  Has wrong with determine which node can drop "inner" when dragging node of tree Component.

### ISSUE THREAD

**Issue by drsmile1001** [element-plus/element-plus#9750]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.16`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/tree.html#draggable)

### Steps to reproduce

This bug can reproduce on official document site.
Or copy demo source.

### What is Expected?

All node should able to drag and drag "inner" to all node, expect parent node, descendant nodes or block by allow drag/drop properties.

### What is actually happening?

Some nodes can not drag and drop "inner" to some nodes:

"level one 1" -> "Level one 3"

"level two 1-1" -> "Level one 2", "Level one 3"

"Level three 1-1-1" -> "Level one 2", "Level one 3"

"Level two 2-1" -> "Level one 3"

"Level three 2-1-1" -> "Level one 2","Level one 3"

"Level two 2-2" -> "Level one 3"

"Level three 2-2-1" -> "Level one 2","Level one 3"

"level one 3" -> "level one 2"

"level two 3-1" -> "level one 2"

"level two 3-2" -> "level one 2"

"level two 3-2-1" ->"level one 2", "level one 3"

### Additional comments

_(empty)_

**Comment by init-qy** [comment]
![image](https://user-images.githubusercontent.com/59350883/190129260-44560d0f-e04a-456a-a3b8-7157ed7f677d.png)
![image](https://user-images.githubusercontent.com/59350883/190129324-e1af37cb-0967-4f94-a5f7-7169ab36e3cc.png)
