### ISSUE TITLE
[Style] [table] 苹果笔记本safiri浏览器表格固定列阴影会变成大黑条

### ISSUE THREAD

**Issue by xuyangqiao** [element-plus/element-plus#9775]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.32`
- Element Plus Version: `2.2.9`
- Browser / OS: `safiri / macos 11.0 M1芯片`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table.html#%E5%9B%BA%E5%AE%9A%E5%88%97)

### Steps to reproduce

直接打开官网示例，和项目内都会出现

![](https://tuchuangs.com/imgs/2022/09/15/80c9a4cc776e73ad.png)

### What is Expected?

正常显示阴影

### What is actually happening?

阴影变成了一根大黑条

### Additional comments

_(empty)_

**Comment by tolking** [comment]
Same with #9373
