### ISSUE TITLE
导航菜单样式

### ISSUE THREAD

**Issue by bigkjp97** [element-plus/element-plus#978]
不知道大家有没有遇到这个问题，导航侧栏引用后样式出问题，副菜单的标题离箭头很近，还是需要一个个自己调？

**Comment by SimonaliaChen** [comment]
Please provide a valid reproduction link.

**Comment by bigkjp97** [comment]
<el-radio-group v-model="isCollapse" style="margin-bottom: 20px;">
  <el-radio-button :label="false">展开</el-radio-button>
  <el-radio-button :label="true">收起</el-radio-button>
</el-radio-group>
<el-menu default-active="1-4-1" class="el-menu-vertical-demo" @open="handleOpen" @close="handleClose" :collapse="isCollapse">
  <el-submenu index="1">
    <template #title>
      <i class="el-icon-location"></i>
      <span>导航一</span>
    </template>
    <el-menu-item-group>
      <template #title>分组一</template>
      <el-menu-item index="1-1">选项1</el-menu-item>
      <el-menu-item index="1-2">选项2</el-menu-item>
    </el-menu-item-group>
    <el-menu-item-group title="分组2">
      <el-menu-item index="1-3">选项3</el-menu-item>
    </el-menu-item-group>
    <el-submenu index="1-4">
      <template #title>选项4</template>
      <el-menu-item index="1-4-1">选项1</el-menu-item>
    </el-submenu>
  </el-submenu>
  <el-menu-item index="2">
    <i class="el-icon-menu"></i>
    <template #title>导航二</template>
  </el-menu-item>
  <el-menu-item index="3" disabled>
    <i class="el-icon-document"></i>
    <template #title>导航三</template>
  </el-menu-item>
  <el-menu-item index="4">
    <i class="el-icon-setting"></i>
    <template #title>导航四</template>
  </el-menu-item>
</el-menu>

<style>
  .el-menu-vertical-demo:not(.el-menu--collapse) {
    width: 200px;
    min-height: 400px;
  }
</style>

<script>
  export default {
    data() {
      return {
        isCollapse: true
      };
    },
    methods: {
      handleOpen(key, keyPath) {
        console.log(key, keyPath);
      },
      handleClose(key, keyPath) {
        console.log(key, keyPath);
      }
    }
  }
</script>
![QQ图片20201212120650](https://user-images.githubusercontent.com/53322922/101973369-8c236400-3c72-11eb-9672-f4ff30e303cf.png)

the padding here is too short ,and titles crowd at the right of the menu ,submenus are not aligned ,does it need to be modified by myself in css one by one ,or did i miss something in ur website?

**Comment by Liiked** [comment]
you can change the **width** of vertiacal menu by yourself.
the official demo also shows the case.

**Comment by bigkjp97** [comment]
copy ,thks for the answer..
