### ISSUE TITLE
[Component] [All] 设置某个dom节点v-loading指令，快速重复的点击触发loading之后，出现dom节点下的子结点不能被点击

### ISSUE THREAD

**Issue by bobo456123** [element-plus/element-plus#9782]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.12`
- Browser / OS: `105.0.5195.102 (正式版本) （64 位）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBsb2FkaW5nPXJlZihmYWxzZSk7XG4gIFxuICBjb25zdCB0cmlnZ2VyPSgpPT57XG4gICAgbG9hZGluZy52YWx1ZT10cnVlO1xuICAgIHNldFRpbWVvdXQoKCk9PntcbiAgICAgIGxvYWRpbmcudmFsdWU9ZmFsc2U7XG4gICAgfSwxMDApXG4gIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwidHJpZ2dlclwiPmNsaWNrPC9lbC1idXR0b24+XG4gIDxkaXYgdi1sb2FkaW5nPVwibG9hZGluZ1wiPlxuICAgICAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG57e2xvYWRpbmd9fVxuICAgICAgPHA+XG4gICAgICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICAgICAgPC9wPlxuICA8L2Rpdj5cblxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

快速重复点击click按钮

### What is Expected?

loading-number不断累积，停止点击之后会彻底消除；

### What is actually happening?

1、loading-number停留
2、el-loading-parent--relative也一直停留在页面

### Additional comments

_(empty)_

**Comment by Cheerwhy** [comment]
2.2.17 说是修复了

**Comment by holazz** [comment]
这个 [PR](https://github.com/element-plus/element-plus/pull/9630) 已经修复了这个问题，升级 Element Plus 到 2.2.17 版本
