### ISSUE TITLE
Typography not working?

### ISSUE THREAD

**Issue by izcream** [element-plus/element-plus#979]
Hello. I try to use element-plus UI in my vuejs project.

I got a problem with base style fonts not working(like its render font without any base style from element).
how do I solve This?

<img width="326" alt="Screen Shot 2563-12-11 at 23 21 05" src="https://user-images.githubusercontent.com/10282500/101928073-c1469c80-3c07-11eb-9645-817954f89986.png">
<img width="401" alt="Screen Shot 2563-12-11 at 23 21 16" src="https://user-images.githubusercontent.com/10282500/101928088-c3a8f680-3c07-11eb-9908-97d84f5845c9.png">

**Comment by JeremyWuuuuu** [comment]
Have you imported the style sheet correctly?

**Comment by izcream** [comment]
I follow guide from element-plus doc from this https://element-plus.org/#/en-US/component/quickstart

and You can try to add h1 in this sandbox font will render sans-serif like my problem. https://codepen.io/iamkun/pen/YzWMaVr

**Comment by JeremyWuuuuu** [comment]
Try this in your index.css

```

  html, body { font-family: "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif; }
```

**Comment by JeremyWuuuuu** [comment]
I just had a test on my machine with `codesandbox`, it uses the default font from my machine. So I added the code like that, everything seems fine.

**Comment by izcream** [comment]
> Try this in your index.css
> 
> ```css
>   html, body { 
>       font-family: "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif;
> }
> ```

Thank I will try this. I think it's will imported base typo from element 😅

ps. I try to dig into theme-chalk sass src folder and not found any css related to set font-family or in element-variable not found smth like font-family too. Its normal?

**Comment by JeremyWuuuuu** [comment]
Take a look at this.
[ElementPlus - Typography](https://element-plus.org/#/en-US/component/typography)
I had the same guess as you did, but turned out unexpected.

**Comment by izcream** [comment]
> Take a look at this.
> [ElementPlus - Typography](https://element-plus.org/#/en-US/component/typography)
> I had the same guess as you did, but turned out unexpected.

Yes I look this in doc before create this issue. First I think element-plus will auto import and set font-family to html,body but look like its not do like this. I must import and set font-family manully. It's right way right😅?

**Comment by JeremyWuuuuu** [comment]
> > Take a look at this.
> > [ElementPlus - Typography](https://element-plus.org/#/en-US/component/typography)
> > I had the same guess as you did, but turned out unexpected.
> 
> Yes I look this in doc before create this issue. First I think element-plus will auto import and set font-family to html,body but look like its not do like this. I must import and set font-family manully. It's right way right😅?

Yup, you have to do it on your own, guess that element have left the choice to the users.

**Comment by izcream** [comment]
Thanks I wil closed this issue

Solve by manual set font-family in you css 😇

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/101930738-8185b200-3c13-11eb-85d2-d952e324250c.png)
I found the code in the website codebase, guess that need to be mentioned in the documentation. Thank you for bringing this up.

**Comment by racterub** [comment]
So Element-UI won't set the font-family automatically ? 🤔 

I've got same issue using Vue 3.0.6, Element-Plus 1.0.2-beta.32
![image](https://user-images.githubusercontent.com/20561837/109523372-44321180-7aea-11eb-8698-50b2dd3e25bd.png)
