### ISSUE TITLE
[Bug Report] input使用box-shadow来实现边框效果，导致圆角处有残留点

### ISSUE THREAD

**Issue by sww-test** [element-plus/element-plus#9793]
### Element Plus version
2.2.17

### OS/Browsers version
谷歌浏览器

### Vue version
3.2.39

### Reproduction Link
https://vue-admin-beautiful.com/admin-plus/?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=#/vab/form/comprehensiveForm

### Steps to reproduce
点击 【行政区划】的选择框，多次聚焦、失焦，可以看到圆角附近出现点状，推测导致的原因是elementPlus通过box-shadow来实现的边框效果。

### What is Expected?
正常边框

### What is actually happening?
边框周围有点状阴影

**Comment by chenxch** [comment]
same: #7034
