### ISSUE TITLE
[Component] [icon] cdn引入，使用el-icon，有两个大写字母的icon图标无法显示

### ISSUE THREAD

**Issue by wzh90** [element-plus/element-plus#9809]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105.0.5195.102`
- Build Tool: `CDN`

### Related Component

- `el-icon`

### Reproduction Link

[CodePen](https://codepen.io/wzh90/pen/ZEoeVKb)

### Steps to reproduce

CDN引入， 导入组件：
```js
const app = Vue.createApp({
  setup: () => {
    return {};
  }
}).use(ElementPlus);
for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
  app.component(key, component);
}
app.component("Darrowright_1", ElementPlusIconsVue.DArrowRight);
app.mount("#app");

```

### What is Expected?

图标显示

### What is actually happening?

图标不显示

### Additional comments

_(empty)_

**Comment by tolking** [comment]
[dom-template-parsing-caveats](https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)
