### ISSUE TITLE
[Component] [select-v2] 2.2.17 版本 el-select-v2 单选的 placeholder 样式不正确

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#9810]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXJcIj5cbiAgICAgICAgICA8ZWwtaWNvbj48dGltZXIgLz48L2VsLWljb24+XG4gICAgICAgICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tbGVmdDogMTBweFwiPnt7IHNjb3BlLnJvdy5kYXRlIH19PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgPGVsLXBvcG92ZXIgZWZmZWN0PVwibGlnaHRcIiB0cmlnZ2VyPVwiaG92ZXJcIiBwbGFjZW1lbnQ9XCJ0b3BcIiB3aWR0aD1cImF1dG9cIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgICAgICA8ZGl2Pm5hbWU6IHt7IHNjb3BlLnJvdy5uYW1lIH19PC9kaXY+XG4gICAgICAgICAgICA8ZGl2PmFkZHJlc3M6IHt7IHNjb3BlLnJvdy5hZGRyZXNzIH19PC9kaXY+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICAgIDxlbC10YWc+e3sgc2NvcGUucm93Lm5hbWUgfX08L2VsLXRhZz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXBvcG92ZXI+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJTd2l0Y2hcIiB3aWR0aD1cIjE4MFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj5cbiAgICAgICAgIDxlbC1zd2l0Y2hcbiAgICAgICAgICAgIHYtbW9kZWw9XCJzY29wZS5yb3cuc3dpdGNoXCJcbiAgICAgICAgICAgIDpiZWZvcmUtY2hhbmdlPVwiYmVmb3JlQ2hhbmdlKHNjb3BlLnJvdylcIlxuICAgICAgICAgIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25zXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJzY29wZVwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiIEBjbGljaz1cImhhbmRsZUVkaXQoc2NvcGUuJGluZGV4LCBzY29wZS5yb3cpXCJcbiAgICAgICAgICA+RWRpdDwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvblxuICAgICAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgICAgICAgdHlwZT1cImRhbmdlclwiXG4gICAgICAgICAgQGNsaWNrPVwiaGFuZGxlRGVsZXRlKHNjb3BlLiRpbmRleCwgc2NvcGUucm93KVwiXG4gICAgICAgICAgPkRlbGV0ZTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgVGltZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuaW50ZXJmYWNlIFVzZXIge1xuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIHN3aXRjaDogYm9vbGVhblxuICBhZGRyZXNzOiBzdHJpbmdcbn1cblxuY29uc3QgaGFuZGxlRWRpdCA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cbmNvbnN0IGhhbmRsZURlbGV0ZSA9IChpbmRleDogbnVtYmVyLCByb3c6IFVzZXIpID0+IHtcbiAgY29uc29sZS5sb2coaW5kZXgsIHJvdylcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3dpdGNoOiB0cnVlLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgc3dpdGNoZXI6IGZhbHNlLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIHN3aXRjaDogZmFsc2UsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG4gIFxuY29uc3QgYmVmb3JlQ2hhbmdlID0gKHJvdzogVXNlcikgPT4ge1xuICBjb25zb2xlLmxvZyhyb3cpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.打开官网链接
https://element-plus.org/zh-CN/component/select-v2.html#%E8%83%8C%E6%99%AF

### What is Expected?

el-select-v2 的 placeholder 透明

### What is actually happening?

el-select-v2 的 placeholder 没有透明

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/31252046/190870529-529241e2-4753-477a-abdf-579d68def206.png)

**Comment by holazz** [comment]
因为 select-v2 支持空字符串作为 value，所以定义初始值不要传空字符串（`ref('')`），而是传空值（`ref()`）。
相关 PR #9609

**Comment by JackieCheung** [comment]
> 因为 select-v2 支持空字符串作为 value，所以定义初始值不要传空字符串（`ref('')`），而是传空值（`ref()`）。 相关 PR #9609

我不是很理解这样做的意义是什么，首先空字符串就不应该作为 `option` 的其中一个 `value`，这个应该是由业务去决定的，其次，很多时候 `select` 的值是动态获取的，对于大多数标准的数据结构来说，string 默认值就为 ''，这样改动岂不是要把所有的空串都改成 `undefined` ？

**Comment by JackieCheung** [comment]
> 因为 select-v2 支持空字符串作为 value，所以定义初始值不要传空字符串（`ref('')`），而是传空值（`ref()`）。 相关 PR #9609

哪怕加一个 `prop` 可以配置`允许空值`也好

**Comment by holazz** [comment]
对 placeholder 的显示做了下修改，参考 https://github.com/element-plus/element-plus/pull/9835 中的 demo
