### ISSUE TITLE
[Style] [slider] el-slider 在 linline form 下滑动区间宽度为 0

### ISSUE THREAD

**Issue by nbaxp** [element-plus/element-plus#9812]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-slider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSA6aW5saW5lPVwidHJ1ZVwiIDptb2RlbD1cImZvcm1JbmxpbmVcIiBjbGFzcz1cImRlbW8tZm9ybS1pbmxpbmVcIj5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiQXBwcm92ZWQgYnlcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZm9ybUlubGluZS51c2VyXCIgcGxhY2Vob2xkZXI9XCJBcHByb3ZlZCBieVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSA+XG4gICAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9J2Zvcm1JbmxpbmUuc2xpZGVyJyA6bWluPScwJyA6bWF4PScxMDAnIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IHpvbmVcIj5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm1JbmxpbmUucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJBY3Rpdml0eSB6b25lXCI+XG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIG9uZVwiIHZhbHVlPVwic2hhbmdoYWlcIiAvPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSB0d29cIiB2YWx1ZT1cImJlaWppbmdcIiAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJvblN1Ym1pdFwiPlF1ZXJ5PC9lbC1idXR0b24+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZm9ybUlubGluZSA9IHJlYWN0aXZlKHtcbiAgdXNlcjogJycsXG4gIHJlZ2lvbjogJycsXG4gIHNsaWRlcjogNSxcbn0pXG5cbmNvbnN0IG9uU3VibWl0ID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZygnc3VibWl0IScpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

在 el-form 的 inline=true 时使用 el-slider 组件即可复现，也可以直接打开复现链接查看。为防止链接失效，代码如下：
```vue
<template>
  <el-form :inline="true" :model="formInline" class="demo-form-inline">
    <el-form-item label="Approved by">
      <el-input v-model="formInline.user" placeholder="Approved by" />
    </el-form-item>
    <el-form-item >
      <el-slider v-model='formInline.slider' :min='0' :max='100' />
    </el-form-item>
    <el-form-item label="Activity zone">
      <el-select v-model="formInline.region" placeholder="Activity zone">
        <el-option label="Zone one" value="shanghai" />
        <el-option label="Zone two" value="beijing" />
      </el-select>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="onSubmit">Query</el-button>
    </el-form-item>
  </el-form>
</template>

<script lang="ts" setup>
import { reactive } from 'vue'

const formInline = reactive({
  user: '',
  region: '',
  slider: 5,
})

const onSubmit = () => {
  console.log('submit!')
}
</script>

```

### What is Expected?

el-slider 在 el-form 为行内表单时滑动区间有默认宽度

### What is actually happening?

滑动区间有默认宽度为 0

### Additional comments

虽然可以自己额外设置样式，但是还是建议能和其他组件在行内表单的表现一致

**Comment by nbaxp** [comment]
![alert](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvoAAABzCAYAAADpP6bsAAAAAXNSR0IArs4c6QAAFlJJREFUeF7t3W2MHdV9x/H/XSPs3fXagJ+xs+AtCop4gUAKBNSmSpWgRE0jRa3avipEVIqUVFHyJrys+pK8KUJNpL6oAn3VVqkitalSQRqU0gYSqqC8QCkR2NjxYnvxAvZ6dy8b+97qsBk6Pp6Z83DPmXPuzNdvwHtnzsPnnDnzu+eO7w6+88p4vLq6Kvv27RP+IIAAAggggAACCCCAQDcEBv91ajw+f/6cHDp0uBs9ohcIIIAAAggggAACCCAgg/99azxeXl6Wo0ePwoEAAggggAACCCCAAAIdERicWxuPT58+LYuLix3pEt1AAAEEEEAAAQQQQACBwaXhePzGqTfk9ttuRwMBBBBAAAEEEEAAAQQ6IjAYXhmP3zh5Um4/frwjXaIbCCCAAAIIIIAAAgggMLhydTw+efKkHCfoMxsQQAABBBBAAAEEEOiMwGA0Go9PnDwhS8eXOtMpOoIAAggggAACCCCAQN8FBqPxeHzixAlZWiLo930y0H8EEEAAAQQQQACB7ggMxgT97owmPUEAAQQQQAABBBBA4DcCBH2mAgIIIIAAAggggAACHRQg6HdwUOkSAggggAACCCCAAAIEfeYAAggggAACCCCAAAIdFCDod3BQ6RICCCCAAAIIIIAAAkGD/uOPP36N6GOPPfbB311eUyepc9U55TKKwoqf62UW56n/ml7T21ZVT4rp0eSk9yuXNpedyu2vG3+93XXnpPDX62xqm01fy3Myh/7QBgQQQAABBBDoj0DwoF8XoPXQXv67KdBXhS9TUK8rswjLpvNzmAJNZjm0zzQu+huzqjY3jVPqPrrMIf3NzjTMr9S+1I8AAggggAACcQWyD/r6jmhV+LL9WV3wzDVsTlPQDxWK4053t9JD9SnX+eWmwdEIIIAAAgggMG0C2QR9Ha7YEbUJu3VB31Rm+RGgXB+DqXvMJbf2msJs8ZhL3aNY+hu6XC4kn3bbzNlc+kc7EEAAAQQQQKC7AsGDfpnK5Rn9uuBaDlp1oct3R38ag37dpxKpp6gp6Nu027aMFH112d0vP7uf6xuYFIbUiQACCCCAAALtCgQP+k2BvbxLXw5ApoBnCuR9DPrKz+TW5lRyaYtLaG6zD6a6bNtdPq7pEwFTfbyOAAIIIIAAAghMIpAk6Osh1RQSYwT94o1GzkHM1mWSCRDqXBdH28Acqm2hyrFtN4/uhBKnHAQQQAABBBCYRCBp0NfDdrkjVY/9NH0tY3Gu/qlBVZk2jwNNgjrJueXHPkz9zfE5/SZvfYyKN3x14z6JY4hzmx7BMb1mM39DtJEyEEAAAQQQQACBOoGgQR9mBBBAAAEEEEAAAQQQyEOAoJ/HONAKBBBAAAEEEEAAAQSCChD0g3JSGAIIIIAAAggggAACeQgQ9PMYB1qBAAIIIIAAAggggEBQAYJ+UE4KQwABBBBAAAEEEEAgDwGCfh7jQCsQQAABBBBAAAEEEAgqQNAPyklhCCCAAAIIIIAAAgjkIUDQz2McaAUCCCCAAAIIIIAAAkEFCPpBOSkMAQQQQAABBBBAAIE8BAj6eYwDrUAAAQQQQAABBBBAIKgAQT8oJ4UhgAACCCCAAAIIIJCHAEE/j3GgFQgggAACCCCAAAIIBBX4IOj/+ZPPBS24j4X98IlH+9ht+owAAggggAACCCCQoQBBP+CgEPQDYlIUAggggAACCCCAwEQCBP2J+K49maAfEJOiEEAAAQQQQAABBCYSGLz++uvjiUrgZAQQQAABBBBAAAEEEMhOYDAcDsfLy8uytLSUXeNoEAIIIIAAAggggAACCPgJEPT93DgLAQQQQAABBBBAAIGsBQj6WQ8PjUMAAQQQQAABBBBAwE+AoO/nxlkIIIAAAggggAACCGQtQNDPenhoHAIIIIAAAggggAACfgIEfT83zkIAAQQQQAABBBBAIGsBgn7Ww0PjEEAAAQQQQAABBBDwEyDo+7m1dtbmcEtmd93YWn1UhICNwJWrI5kZiMzMzNgczjEIBBW4cuWKXL0qsnPnDUHLpTAEchW4eHFd9u6dz7V5tCtjAYJ+poOzsfmeXFrbEBX0R6NRpq2kWX0W2D0/K3sW5ngj2udJkKDvak1Ua+Pl9c0EtVMlAmkE1KaK2vRTa+7c7M40jdBq/eWqyLd+KvLKisiVHseUG2ZE7joo8qX7RD68L4uhuaYRBP38xkRUyH/73TVZ2D0nC/OzMqO2TvmDQEYCo9FY1tY35eKlddl384LMz+3KqHU0pasC6xtDWX1nTfbumWdt7Oog069KgWLNXbu8IbfctJA87KuQ/+Xv9Tvg6wOlAv83P5tf2CfoZ7ionFt5R2Znd8rehbkMW0eTEPh/gYtrGzIcbsmhAzfBgkB0gfNvvSu7dt3I2hhdmgpyFVBr7ubme3L44M1Jm/jV74v8/FzSJmRZ+d2HRZ74TF5NI+jnNR6yvj6UldWLctuxg+zkZzY2NOd6AbXLdObsBVk8egAeBKIKbP36qpxbeVuOHdnP2hhVmsJzFlBr7qkzK3J88VDSZn7qaXbzqwZA7eo/+3DSobmucoJ+XuPxfmtef+Os/NbtRzJsGU1C4HoB5iuzoi0B5lpb0tSTs0AO18Envp2zUNq2PfeFtPXrtRP08xoPgn6G40GTmgVyuOkwRv0QYK71Y5zpZf5rLkG/fowI+lzBRgFuZkYiDshIIMV8/ffXRF44LfLqBZELG9sY++dE7twv8sCiyKfvyAiIpgQTSDHXgjWeghAIJJDDdUDQJ+gHms79LCaHi7if8vTaR6DN+aoC/lM/Ezm/3tzSQ/Mij9xL4PcZz5zPaXOu5exA2/otkMN1QNAn6Pf7Kpyw9zlcxBN2gdN7JNDWfH3yRZHv/mIbVn1n8UN3iNxzROTW3ds/e/OyyMtnRZ55bft7ndWfz39E5Csf69FgdLyrbc21jjPSvSkXyOE6IOgT9Kf8Mkrb/Bwu4rQC1D5NAm3M13LI/9qDIp+7s1noX14V+esfE/anaR7ZtLWNuWbTDo5BIKVADtcBQZ+gn/IamPq6c7iIpx6RDrQmEHu+qsd1Hn9+uzvfeEjko0ftuvbSssjXn9k+9rHf4TEeO7W8j4o91/LuPa1DYFsgh+uAoN+DoP+FR78o3/67v+3cddfUr7b6PMlF/I/f+Vf5kz/6g86Ni+pQU9+63O/cB3OS+WrTtz/9p+1n8m128vXyip199cz+P/yxTW1hjgmxVtiWYXtcmJ6lLWWSueazRujn2JZRPs72nLSy1D5NApNcB6H6GTLoV31LTcjyQ/XZtpxOfOtOcWPp4g1mmoN+cUPp6o2FoG+7zLR7XMybTrGbr57J/5vf9+vXX/zb9jP7be3q+66PodbTUOX4acc9y3eu+a6NIdbSEGXEVaX0aRPwvQ5C9jNUEFehuKqsup+H7EOssgj6sWQDldvVoF++0RVU5Z1/19eLc9V55T/ln1d9sqDvdFWdW/ysXLYqyybo6+c0fRLADTjMRRPzpvOXPxT5z1N+u/lF74pd/Y/fJvJXvxemz02lEPTjGfvONVPQr1s39PXJppzyWqWvj6o807pYtf7VrbF166dpPS/Wxab1N94o9qfklbdW5eCBfY0d/tWZN+VDx251QvG9DpwqMRwcIuibwnz59apj9Z/pAbvcxuLY8jGx3mB0PuiXb3LFPCk/4uP6enGuOq/8p/zzqkeIyoG9fK5+rP6aTdCvKq/uPJ/dNd+LuOkmVNxwqsJ9edH3fb18c2oK5aY21r1RqGp/eT409a8u0BP0wyz7vvPVpvbisZ2//0ORD+2xOeP6Y351SeTP/lmkrcd3bIJ+1bqjr2+mcqpe19dJVaZpfSzqrTq3fH7dGqyOMa3rxTFV9wSXUfWda7brTrEWNq1DruubzWM8NmuRqZyqTZSm9Vx/w2HTBpex4liRZ//jedm//xa55+67Kjl+8tLLMhqN5YH773Xi8r0OnCqZsqBveiNQhO8i3Mf8JGHqg74eXKv+XnVz0AO77d/LN4imc6reTNSd61J3ea4XNzqfdrhcYD4Xsb5Im/5uuqG5vq4Hff181/Kqbjo2O/p6+DfdsF3GhWOrBXzmq63lJ58SuToW+cHDIjtmbM+69rirI5FPPi2yYyDyg0f8yrA9y7Q+lkOxXmbTub6vVdVnu/lQtVnisnaazvf5N14+c820FrqsK01hu+61SeqvWler1tbY66vt/Oe46wWe+9GPZW52Vu6/755rXvzvF/5Htra25BO/+6Azm8914FxJB4O+voNf9YlAqE8qQntPUt5gOByOl5eXZWlpyaoc042s6iaiL/hVu+pNO/SuZTbV59IW041Yv4mabKyAPf9Fvc/NxHWHyGYHyOVGWOXR9OiPyw3ZdONj98p2NpqPi3nT6VrQt/nEsBD3XcdM65BN0DeVYVr7TK/btKFq5vnMNZ+10SZgN5Vruw7WhXa976Y+mNa7qteb1l/zVc8RLgIq7O/YsUM+/tv3v3/aj55/UUajkVfIV+f7XAcu7bU5NlQgbirH5dGdul30ph18gn7FSNd9tKsOtQ3qrqFdv2HU3QSLNtTtupe7Y9tWn6Bf1w6bC6c4xvUiLh5bmSQ4m3bQTa+bbow2N6py+23rq6u36gba9PG9y/hw7LUCrvPVxW+aHt3xXR+r1jR93Suva1VrXN0nmkU5LuuSXr7tGmzawNHHvY0dfd+10bSe6a/bhn7TeVXXhu1aOOnGjct1ybHuAirsl//47OT7ZgT31prPyDHo275pKPeu/Ox+iD6psqf60Z26XRiXXfIYQb98I7LZiaq7sdbd0FyOL+r33bFSdbkGp7rd6UkXfpfzTTdGgr554ZzWI1znq0s/p+kf4/qujzZB32WNa1pjbdYl0xpd1V7TOTb12swL17nmuzaa1jNTYLddO20+WSTo28yM6TimCPuThHyfjBBDJ0Qobnqu3ma33bTjXxXodQuCviZieyNTp9k+y2nanSpucE1lmm6C5XPLXarb/a/babI5vu2gb7pRlHexVd99/7Gtz82m7mapfm4qr+qNgd7+8lgWO3d1/SvXaTKLsSh2uUzX8OViMU1fr+mzPurrkWlnXr1u2syYJOg39cG0rtvs6Pvs4peNXOaa6Tqv+4TP5bEbn7XMZS2yeaNStc66rq91/XC5Vjm2PQGX6yBWq0IEfdW2urCvXqv61pyiPzb/uNbmjQBBvzRDTDsyesAtf4zt8607+uTUPxa3/SaJ8huFoky9PeWfN/Wz3MeqsoqfmaxMF57LRex6Myt/lO3z9Zp62/WPxm2/Oq64sZTLq/o3AMXrk3y9pv6GoKu/UMw0r2K97jJffdowDb8wy3TN6596lh2qvlmsKtAXa1lToNbXu6Y3DqY1Vl/jmtZg046+aR22nRcuc812bdTXIn1dNK1BNqG6XEbx/zbtq3IxfbVx0R/Tv6myWbttx4Xj2hVwuQ5itSxU0Fftq/paTD3I68ep+n2+XrPKw/Q1n66GU/3ojk1nXW54NuVN4zEmA1OfYlzENjeVPgRgk4NpbHj9eoEY87VcS7Grr372jYdEPnrUbhReWhb5+jPbx7b1y7LsWpbmqEnXpTStvrbW2HOtzT6yFrWp3a26crgOQgb91KND0HccAdPNxPS6Y3XZHR6ifzEuYtNNxfR6dtCeDepLPz15vE6LMV/1hjz5osh3f7H90689KPK5O5ubWvySLHXU5z8i8pWPeXWtMyeFWJdywGhjrrXVT9aitqS7V08O1wFBv35esaP/6Bcrf4HLtF+K+vP7k/QnxkVsuqmYXp+kPzmcW/UMfw7t6kIbYszXKpdy2L/roMhDd4jcc0Tk1t3bR795WeTlsyLPvCbyysr2z/oe8kOuSznM1bbmWsy+shbF1O1H2TlcB10I+lWPB4WYQZ0P+iGQ+l5GDhdx38eA/tsLtDlf1WM8T/1M5Px6c/vUb8F95F6RT99h3w+OzF+gzbmWvwYt7KtADtdBF4J+rPlD0I8l26Fyc7iIO8RJVyILpJivKvC/cFrk1QsiFza2O7h/TuTO/SIPLBLwIw95suJTzLVknaViBGoEcrgOCPr105Ogz6VrFMjhIjY2kgMQ+I0A85Wp0JYAc60taerJWSCH64CgT9DP+RrJvm05XMTZI9HAbASYr9kMRecbwlzr/BDTQQuBHK4Dgj5B32KqckiVwPr6UFZWL8ptxw7KzMwAJASyFhiNxnLm7AVZPHog63bSuOkX2Pr1VTm38rYcO7KftXH6h5MeeAqoNffUmRU5vnjIs4Qwp33qaZErozBldamUG2ZEnn04rx4NhsPheHl5WZaWlvJqWY9bc27lHZmd3Sl7F+Z6rEDXp0Hg4tqGDIdbcujATdPQXNo45QLn33pXdu26kbVxyseR5vsLqDV3c/M9OXzwZv9CApz51e+L/PxcgII6VsTdh0We+ExenSLo5zUe77dmY/M9efvdNVnYPScL87PsXmU4Rn1vktpVWlvflIuX1mXfzQsyP7er7yT0vwWB9Y2hrL6zJnv3zLM2tuBNFfkIFGvu2uUNueWmBZmb3Zm0cb9cFfny99jVLw+C2s3/5mdFPrwv6dBcVzlBP6/x+KA1KuxfUu/ch1syGvH5WKbD1Otm7Z6flT0LczK768ZeO9D5dgXUmqjWxsvrm+1WTG0IJBSYmZl5f61Va27qkF8wqLD/rZ9u/96SPj/GowK++t0uX7ovv5Cvxoqgn/DCpWoEEEAAAQQQQAABBGIJEPRjyVIuAggggAACCCCAAAIJBQj6CfGpGgEEEEAAAQQQQACBWAIE/ViylIsAAggggAACCCCAQEIBgn5CfKpGAAEEEEAAAQQQQCCWAEE/lizlIoAAAggggAACCCCQUICgnxCfqhFAAAEEEEAAAQQQiCVA0I8lS7kIIIAAAggggAACCCQUIOgnxKdqBBBAAAEEEEAAAQRiCRD0Y8lSLgIIIIAAAggggAACCQUI+gnxqRoBBBBAAAEEEEAAgVgCBP1YspSLAAIIIIAAAggggEBCAYJ+QnyqRgABBBBAAAEEEEAglgBBP5Ys5SKAAAIIIIAAAgggkFCAoJ8Qn6oRQAABBBBAAAEEEIglQNCPJUu5CCCAAAIIIIAAAggkFCDoJ8SnagQQQAABBBBAAAEEYgkQ9GPJUi4CCCCAAAIIIIAAAgkFCPoJ8akaAQQQQAABBBBAAIFYAgT9WLKUiwACCCCAAAIIIIBAQgGCfkJ8qkYAAQQQQAABBBBAIJYAQT+WLOUigAACCCCAAAIIIJBQgKCfEJ+qEUAAAQQQQAABBBCIJUDQjyVLuQgggAACCCCAAAIIJBQg6CfEp2oEEEAAAQQQQAABBGIJEPRjyVIuAggggAACCCCAAAIJBQj6CfGpGgEEEEAAAQQQQACBWAIE/ViylIsAAggggAACCCCAQEIBgn5CfKpGAAEEEEAAAQQQQCCWAEE/lizlIoAAAggggAACCCCQUICgnxCfqhFAAAEEEEAAAQQQiCVA0I8lS7kIIIAAAggggAACCCQUIOgnxKdqBBBAAAEEEEAAAQRiCRD0Y8lSLgIIIIAAAggggAACCQUI+gnxqRoBBBBAAAEEEEAAgVgCBP1YspSLAAIIIIAAAggggEBCAYJ+QnyqRgABBBBAAAEEEEAglsD/AaHyV8kPuXewAAAAAElFTkSuQmCC)

**Comment by nbaxp** [comment]
![circle_screenshot_1_Element Plus Playground](https://user-images.githubusercontent.com/6228201/190886866-9f4c7011-bde5-4fdb-8466-206f26d31e6b.png)

**Comment by tolking** [comment]
Slider组件的宽度取决于父级宽度，所以在行内表单里面宽度为0。Input、Select组件是由于浏览器input输入框自带的宽度引起的
