### ISSUE TITLE
[Component] [input-number] el-input-number when enter e, you cannot reset it by setting undefined

### ISSUE THREAD

**Issue by li936393** [element-plus/element-plus#9816]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHNpemU9XCJsYXJnZVwiIEBjbGljaz1cIm51bT11bmRlZmluZWRcIj5yZXNldElucHV0TnVtYmVyPC9lbC1idXR0b24+XG4gIDxlbC1pbnB1dC1udW1iZXJcbiAgICB2LW1vZGVsPVwibnVtXCJcbiAgICA6bWluPVwiLTFcIlxuICAgIDptYXg9XCIxMDBcIlxuICAgIDpjb250cm9scz1mYWxzZVxuICAgIDpwcmVjaXNpb249XCIyXCJcbiAgICBjb250cm9scy1wb3NpdGlvbj1cInJpZ2h0XCJcbiAgICBzaXplPVwibGFyZ2VcIlxuICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIlxuICAvPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG51bSA9IHJlZigwKVxuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbHVlOiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2codmFsdWUpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、inputNumber enter e
2、click resetInputNumber

### What is Expected?

el-input-number cleared

### What is actually happening?

el-input-number not cleared

### Additional comments

add a props disabled scientific enumeration

**Comment by chenxch** [comment]
目前暂不支持科学记数，因为当输入e的失焦后num已经是undefined了，所以点击resetInputNumber无法触发组件内部的更新。
