### ISSUE TITLE
[Build] [All] 在使用pnpm的workspace搭建的monorepo项目中集成nuxt3和elementplus时出现无法访问的问题

### ISSUE THREAD

**Issue by weisiqian** [element-plus/element-plus#9819]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Google Chrome 105.0.5195.127 (正式版本) （64 位） / windows11 `
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/weisiqian/nuxt3-elementplus-monorepo)

### Steps to reproduce

在问题复现仓库：nuxt3-elementplus-monorepo 的根目录中使用 pnpm install 安装依赖，然后使用 pnpm dev 启动项目发现页面无法访问。但是进入applications\ssr 目录使用 npm intall 安装依赖以后使用 npm run dev 启动项目发行没有任何问题，页面可以访问，组件也可以使用。application\ssr 项目是克隆自 https://github.com/element-plus/element-plus-nuxt-starter 项目，配置应该是没有问题。

### What is Expected?

在使用pnpm的workspace搭建的monorepo项目中集成nuxt3和elementplus时可以正常使用组件

### What is actually happening?

在使用pnpm的workspace搭建的monorepo项目中集成nuxt3和elementplus时出现无法访问的问题

### Additional comments

_(empty)_

**Comment by sxzz** [comment]
这个似乎就不在本仓库解决的范畴内了。
