### ISSUE TITLE
[Component] [table, table-column] table-column里面的组件不会销毁，会造成内存泄露

### ISSUE THREAD

**Issue by sc950828** [element-plus/element-plus#9825]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQsIGRlZmluZUNvbXBvbmVudCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuICBleHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICAgIHNldHVwKCkge1xuICAgICAgY29uc3QgdGFibGVEYXRhID0gcmVmKFtcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgICB9XG4gICAgICBdKVxuICAgICAgXG4gICAgICBjb25zdCBjbGljayA9ICgpID0+IHtcbiAgICAgICAgdGFibGVEYXRhLnZhbHVlWzBdW1wibmFtZVwiXSA9IChNYXRoLnJhbmRvbSgpICogMTAwKS50b0ZpeGVkKDIpO1xuICAgICAgICB0YWJsZURhdGEudmFsdWVbMV1bXCJuYW1lXCJdID0gKE1hdGgucmFuZG9tKCkgKiAxMDApLnRvRml4ZWQoMik7XG4gICAgICAgIHRhYmxlRGF0YS52YWx1ZVsyXVtcIm5hbWVcIl0gPSAoTWF0aC5yYW5kb20oKSAqIDEwMCkudG9GaXhlZCgyKTtcbiAgICAgIH1cblxuICAgICAgcmV0dXJuIHtcbiAgICAgICAgdGFibGVEYXRhLFxuICAgICAgICBFcFZlcnNpb24sXG4gICAgICAgIHZ1ZVZlcnNpb24sXG4gICAgICAgIGNsaWNrXG4gICAgICB9XG4gICAgICBcblx0XHR9XG4gIH0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICA8YnV0dG9uIEBjbGljaz1cImNsaWNrXCI+5qih5oufc29ja2V05LuO5ZCO5Y+w5o6l5pS25pWw5o2u77yM5YmN56uv5Yqo5oCB5L+u5pS56KGo5qC85pWw5o2uLCDor7fkuIDnm7Tngrnlh7suLi48L2J1dHRvbj5cdFxuICBcbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cInRhZ1wiID5cbiAgICAgIDxlbC10YWcgdHlwZT1cInN1Y2Nlc3NcIj7mraPluLg8L2VsLXRhZz5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwib3BlcmF0aW9uXCIgPlxuICAgICAgPGVsLWRyb3Bkb3duPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgICAgRHJvcGRvd24gTGlzdFxuICAgICAgICA8L2VsLWJ1dHRvbj5cbiAgICAgICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMzwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGRpc2FibGVkPkFjdGlvbiA0PC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICA8L2VsLWRyb3Bkb3duPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

进入到我写的最小demo，请一直点击按钮，模拟接收后端socket推送的数据，然后前端实时动态修改表格数据。

### What is Expected?

堆内存不会越来越大

### What is actually happening?

堆内存会越来越大

### Additional comments

el-table-column里面如果有组件的话，组件不会被销毁，会一直占内存

**Comment by sc950828** [comment]
最开始堆内存

![image](https://user-images.githubusercontent.com/28090587/190966213-51d4d384-6e35-4f63-8283-2730f2264d22.png)


点击了几十下

![image](https://user-images.githubusercontent.com/28090587/190966408-92e84c57-2e87-4153-a6a7-fd924a9f599e.png)

**Comment by xiziliang** [comment]
可能是在table的data改变后内部逻辑实现有少量的内存溢出，如果是轮训的话确实会有影响 ,感觉也不能排除是不是playground也有问题

**Comment by sc950828** [comment]
> 可能是在table的data改变后内部逻辑实现有少量的内存溢出，如果是轮训的话确实会有影响 ,感觉也不能排除是不是playground也有问题

这是我写的一个小demo，方便复现问题，目前我项目table里面用的组件较多，大概十分钟浏览器就崩溃了。

**Comment by YihooZero** [comment]
遇到相同的问题

**Comment by xiziliang** [comment]
点击前：
![image](https://user-images.githubusercontent.com/54427136/193010089-c341564c-0785-40b2-83d8-17efbd6f7b87.png)
点击后：
![image](https://user-images.githubusercontent.com/54427136/193010063-cded4d7e-f870-454f-b395-50f619050a4f.png)
我通过监控和快照看了下，主要还是数组一直在内存中增加，DOM元素在我点击的过程有增加，但是过一段时间就被垃圾回收了，就正常了，希望能尽早修复🧐

**Comment by 1037055457** [comment]
我也遇到了，项目运行时，时不时的网页崩溃，提示内存泄漏。但一直没有找到对应的解决方案

**Comment by makedopamine** [comment]
https://github.com/element-plus/element-plus/issues/8789#issuecomment-1186884893

Chrome浏览器插件可能会有影响， 我尝试在无痕模式中检查这个复现demo，没有出现内存泄漏的情况。

**Comment by Mario34** [comment]
遇到相同问题

**Comment by zyxiaoxiao** [comment]
相同的问题 table内存泄漏

**Comment by wqdeng** [comment]
vue: 3.3.4
element plus: 2.3.8

我也遇到了这个问题，通过devtools录制内存快照比对页面销毁前后，发现只要页面使用了table组件，整个页面的元素都会变成detached状态。通过导入table组件的源码到自己的项目中，录制内存快照发现泄漏点在table-header\index.ts中的onMounted如下图：
![image](https://github.com/element-plus/element-plus/assets/8603746/0a7253f4-2512-417c-9c27-1d036a4b35fc)
我尝试对源码进行修改，修改之后再次录制内存快照发现没有detached状态的元素了，不知道这样修改是否合适？？
源码修改：
![image](https://github.com/element-plus/element-plus/assets/8603746/28102253-96cb-4c82-b5b2-1590e80133f0)

修改后内存快照：
![image](https://github.com/element-plus/element-plus/assets/8603746/9dcd813b-0cd5-4143-bea9-209c01159bc0)
![image](https://github.com/element-plus/element-plus/assets/8603746/772abf3e-07b7-4ec1-9a68-2423284b0df8)
![image](https://github.com/element-plus/element-plus/assets/8603746/b4c5e828-bccc-4271-b102-8b1d9a19017e)

**Comment by onlyscv** [comment]
有这样的问题，不知道什么时候修复，感觉快要顶不住了。

**Comment by xiaoxian521** [comment]
[Duplicate](https://github.com/element-plus/element-plus/issues/4434)

**Comment by Sitong2014** [comment]
崩溃，已经考虑慢慢替换框架了，不是一个组件的问题，是大量组建存在内存泄露。

**Comment by ITCore99** [comment]
I have also encountered this problem. How can I solve it now

**Comment by ITCore99** [comment]
> 崩溃，已经考虑慢慢替换框架了，不是一个组件的问题，是大量组建存在内存泄露。

感觉是的 很多组件都泄露 难受

**Comment by ITCore99** [comment]
> > 可能是在table的data改变后内部逻辑实现有少量的内存溢出，如果是轮训的话确实会有影响 ,感觉也不能排除是不是playground也有问题
> 
> 这是我写的一个小demo，方便复现问题，目前我项目table里面用的组件较多，大概十分钟浏览器就崩溃了。

解决了吗 应该如何解决 我也遇到了

**Comment by onlyscv** [comment]
> > > 可能是在table的data改变后内部逻辑实现有少量的内存溢出，如果是轮训的话确实会有影响 ,感觉也不能排除是不是playground也有问题
> > 
> > 
> > 这是我写的一个小demo，方便复现问题，目前我项目table里面用的组件较多，大概十分钟浏览器就崩溃了。
> 
> 解决了吗 应该如何解决 我也遇到了

我已经换隔壁的了，因为我们的后台项目都是表格，分分钟崩溃····实在没招。。

**Comment by kiss-keray** [comment]
问题还没解决怎么就close了？

**Comment by changxuexu** [comment]
一开始感觉项目卡不知道啥原因，哎，这个这么多人使用怎么问题这么多呢！
