### ISSUE TITLE
是否有计划整合formily

### ISSUE THREAD

**Issue by umi-soft** [element-plus/element-plus#983]
想了解一下，官方对 阿里开源的formily是否有整合计划呢
formily社区，需要@formily/element这样子的组件

**Comment by g3r4n** [comment]
is it related to / similar than https://github.com/element-plus/element-plus/issues/348 ?

**Comment by zazzaz** [comment]
@umi-soft 

formily 是一个很棒的产品，期待双方能力可以打通。

我们现在人手有限，而且对 formily 底层了解不深，可能没有额外的精力来实现，不知道你们是否愿意参与贡献这个 feature

我的想法是可以放在 ElemeFE 或者 element-plus 组织下的一个单独仓库来实现能力，Element 官网给出用法 demo 

作为一个 formily 和 Element 双官方的解决方案

**Comment by JeremyWuuuuu** [comment]
> is it related to / similar than #348 ?

Nope, they want us to support this [formily](https://github.com/alibaba/formily).

**Comment by JeremyWuuuuu** [comment]
In short term we are unlikely to do that because of the shortage of our developers. In long term we could do as @zazzaz said above.

**Comment by JeremyWuuuuu** [comment]
Would you mind adding this issue to here: https://github.com/element-plus/element-plus/discussions in order to get it tracked? I am closing this.
