### ISSUE TITLE
[Component] [dialog] dialog 使用model-value只能打开dialog一次，v-model可以打开多次

### ISSUE THREAD

**Issue by mollyxfma** [element-plus/element-plus#9831]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome105.0.5195.125`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwiY2VudGVyRGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5DbGljayB0byBvcGVuIHRoZSBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZyA6bW9kZWwtdmFsdWU9XCJjZW50ZXJEaWFsb2dWaXNpYmxlXCIgdGl0bGU9XCJXYXJuaW5nXCIgd2lkdGg9XCIzMCVcIiBjZW50ZXI+XG4gICAgPHNwYW5cbiAgICAgID5JdCBzaG91bGQgYmUgbm90ZWQgdGhhdCB0aGUgY29udGVudCB3aWxsIG5vdCBiZSBhbGlnbmVkIGluIGNlbnRlciBieVxuICAgICAgZGVmYXVsdDwvc3BhblxuICAgID5cbiAgICA8dGVtcGxhdGUgI2Zvb3Rlcj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiZGlhbG9nLWZvb3RlclwiPlxuICAgICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNlbnRlckRpYWxvZ1Zpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiY2VudGVyRGlhbG9nVmlzaWJsZSA9IGZhbHNlXCJcbiAgICAgICAgICA+Q29uZmlybTwvZWwtYnV0dG9uXG4gICAgICAgID5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRpYWxvZz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBjZW50ZXJEaWFsb2dWaXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmRpYWxvZy1mb290ZXIgYnV0dG9uOmZpcnN0LWNoaWxkIHtcbiAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

use prop model-value

### What is Expected?

model-value works same as v-model

### What is actually happening?

model-value not works same as v-model

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
好好看文档，你这个visible 都没有改变，为什么第二次会打开呢？

**Comment by mollyxfma** [comment]
> 好好看文档，你这个visible 都没有改变，为什么第二次会打开呢？

你点了右上角的x试了吗，文档有提这个吗，model-value / v-model有区别？？？跟visible有半毛钱关系？？？
<img width="599" alt="image" src="https://user-images.githubusercontent.com/102200626/191180593-73b0e0f0-f594-4f46-8f04-e6ed5b89e975.png">

**Comment by ntnyq** [comment]
You need add `@close="centerDialogVisible = false"` to mutate the `modelValue` when close dialog.

**Comment by codesyofo** [comment]
> You need add `@close="centerDialogVisible = false"` to mutate the `modelValue` when close dialog.
> 
> `v-model` does the trick automatically, while using `modelValue` you need do it yourself.

如果我通过其他方式修改了 `modelValue` ，`dialog` 还会关闭吗？不会
