### ISSUE TITLE
[Component] [input, tooltip]  el-input  加上el-tooltip后不能输入空格

### ISSUE THREAD

**Issue by Anyhonor** [element-plus/element-plus#9836]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.16`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10b29sdGlwIDpjb250ZW50PVwibXNnXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDwvZWwtdG9vbHRpcD5cblxuICBcbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

输入框中不能输入空格

### What is Expected?

el-input 无论加不加tooltip提示都应该能输入空格

### What is actually happening?

el-input在加tooltip提示后不能输入空格

### Additional comments

_(empty)_

**Comment by btea** [comment]
Duplicate #8127

**Comment by rookielzy** [comment]
@btea 这个问题仍然存在，请尽快解决。
