### ISSUE TITLE
[Style] [image, image-viewer] 版本2.2.15 表格内部使用 image的预览图片功能，td会附在预览图最上面

### ISSUE THREAD

**Issue by lk125454242** [element-plus/element-plus#9840]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.15`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-image`
- `el-image-viewer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH1cbl1cbmNvbnN0IHVybCA9XG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZydcbmNvbnN0IHNyY0xpc3QgPSBbXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMS8zNC8xOWFhOThiMWZjYjI3ODFjNGZiYTMzZDg1MDU0OWpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMC82Zi9lMzVmZjM3NTgxMmU2YjAwMjBiNmI0ZThmOTU4M2pwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vOS9iYi9lMjc4NThlOTczZjVkN2QzOTA0ODM1ZjQ2YWJiZGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZC9lNi9jNGQ5M2EzODA1YjNjZTNmMzIzZjc5NzRlNmY3OGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy8yOC9iYmY4OTNmNzkyZjAzYTU0NDA4YjNiN2E3ZWJmMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMi8xMS82NTM1YmNmYjI2ZTRjNzliNDhkZGRlNDRmNGI2ZmpwZWcuanBlZycsXG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIj5cbiAgICBcdDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInNjb3BlXCI+XG4gICAgICAgIDxlbC1pbWFnZVxuICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDEwMHB4OyBoZWlnaHQ6IDEwMHB4XCJcbiAgICAgICAgICA6c3JjPVwidXJsXCJcbiAgICAgICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgICAgIDppbml0aWFsLWluZGV4PVwiNFwiXG4gICAgICAgICAgZml0PVwiY292ZXJcIlxuICAgICAgICAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

版本2.2.15 表格内部使用 image的预览图片功能，td会附在预览图最上面

### What is Expected?

表格不在viewer上面显示

### What is actually happening?

表格在viewer上面显示

### Additional comments

_(empty)_

**Comment by btea** [comment]
请参考[文档](https://element-plus.org/zh-CN/component/table.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%EF%BC%88faq%EF%BC%89)
