### ISSUE TITLE
[Component] [input-number] el-input-number component validate on blur even set trigger to change

### ISSUE THREAD

**Issue by Gu-Miao** [element-plus/element-plus#9841]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105 / Windows 10`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBjbGFzcz1cImZvcm1cIiByZWY9XCJmb3JtUmVmXCIgOm1vZGVsPVwiZm9ybVN0YXRlXCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPHA+XG4gICAgICBXaGVuIHNldCBgdHJpZ2dlcmAgdG8gYGNoYW5nZWAgaW4gYHJ1bGVzYCwgdGhlIGBlbC1pbnB1dC1udW1iZXJgIGNvbXBvbmVudFxuICAgICAgc3RpbGwgdmFsaWRhdGUgd2hlbiBgYmx1cmAuXG4gICAgPC9wPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwibnVtYmVyXCJcbiAgICAgIDpydWxlcz1cIltcbiAgICAgICAge1xuICAgICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICAgIG1lc3NhZ2U6ICdudW1iZXIgc2hvdWxkIG5vdCBiZSBlbXB0eScsXG4gICAgICAgIH0sXG4gICAgICBdXCJcbiAgICAgIHByb3A9XCJudW1iZXJcIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dC1udW1iZXJcbiAgICAgICAgOm1pbj1cIjEwXCJcbiAgICAgICAgOm1heD1cIjEwMFwiXG4gICAgICAgIHYtbW9kZWw9XCJmb3JtU3RhdGUubnVtYmVyXCJcbiAgICAgID48L2VsLWlucHV0LW51bWJlcj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8cD5gZWwtaW5wdXRgIGNvbXBvbmVudCBpcyBub3JtYWwuPC9wPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwidGV4dFwiXG4gICAgICA6cnVsZXM9XCJbXG4gICAgICAgIHtcbiAgICAgICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICAgICAgICB0cmlnZ2VyOiAnY2hhbmdlJyxcbiAgICAgICAgICBtZXNzYWdlOiAndGV4dCBzaG91bGQgbm90IGJlIGVtcHR5JyxcbiAgICAgICAgfSxcbiAgICAgIF1cIlxuICAgICAgcHJvcD1cInRleHRcIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiZm9ybVN0YXRlLnRleHRcIj48L2VsLWlucHV0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgZm9ybVN0YXRlID0gcmVhY3RpdmU8eyBudW1iZXI/OiBudW1iZXI7IHRleHQ/OiBzdHJpbmcgfT4oe30pXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuYm9keSB7XG4gIG1hcmdpbjogMDtcbiAgaGVpZ2h0OiAxMDB2aDtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGZvbnQtc2l6ZTogMjRweDtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2VlZTtcbn1cbi5mb3JtIHtcbiAgd2lkdGg6IDcwMHB4O1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgcGFkZGluZzogMjBweDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Set `trigger` to `change` in `rules` on `<el-form-item>` component which contains a `<el-input-number>` component .

### What is Expected?

Validate on change

### What is actually happening?

Validate on blur

**Comment by holazz** [comment]
This is consistent with the behavior of native input. [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQtbnVtYmVyIHYtbW9kZWw9XCJ2YWx1ZVwiIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIiAvPlxuICA8aW5wdXQgdHlwZT1cIm51bWJlclwiIHYtbW9kZWw9XCJ2YWx1ZTFcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlMVwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoMSlcbmNvbnN0IHZhbHVlMSA9IHJlZigxKVxuXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoKSA9PiBjb25zb2xlLmxvZygnZWwtaW5wdXQgY2hhbmdlZCcpXG5jb25zdCBoYW5kbGVDaGFuZ2UxID0gKCkgPT4gY29uc29sZS5sb2coJ25hdGl2ZSBpbnB1dCBjaGFuZ2VkJylcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by Gu-Miao** [comment]
@holazz Thanks for demo, I understand it's not a bug now. But is there any way to implement my case? I see `<el-input-number>` does not support `input` event, there's only a `change` event. So I can't even add the verification manually.

**Comment by Gu-Miao** [comment]
I also try `watch`, but the callback only execute when component blur.

**Comment by holazz** [comment]
Maybe use `@input`?

**Comment by Gu-Miao** [comment]
I tried it, but handler only executes when componet blur just like using `watch`. [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBjbGFzcz1cImZvcm1cIiByZWY9XCJmb3JtUmVmXCIgOm1vZGVsPVwiZm9ybVN0YXRlXCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPHA+XG4gICAgICBXaGVuIHNldCBgdHJpZ2dlcmAgdG8gYGNoYW5nZWAgaW4gYHJ1bGVzYCwgdGhlIGBlbC1pbnB1dC1udW1iZXJgIGNvbXBvbmVudFxuICAgICAgc3RpbGwgdmFsaWRhdGUgd2hlbiBgYmx1cmAuXG4gICAgPC9wPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwibnVtYmVyXCJcbiAgICAgIDpydWxlcz1cIltcbiAgICAgICAge1xuICAgICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICAgIG1lc3NhZ2U6ICdudW1iZXIgc2hvdWxkIG5vdCBiZSBlbXB0eScsXG4gICAgICAgIH0sXG4gICAgICBdXCJcbiAgICAgIHByb3A9XCJudW1iZXJcIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dC1udW1iZXJcbiAgICAgICAgOm1pbj1cIjEwXCJcbiAgICAgICAgOm1heD1cIjEwMFwiXG4gICAgICAgIHYtbW9kZWw9XCJmb3JtU3RhdGUubnVtYmVyXCJcbiAgICAgICAgQGlucHV0PVwiaGFuZGxlSW5wdXRcIlxuICAgICAgPjwvZWwtaW5wdXQtbnVtYmVyPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxwPmBlbC1pbnB1dGAgY29tcG9uZW50IGlzIG5vcm1hbC48L3A+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJ0ZXh0XCJcbiAgICAgIDpydWxlcz1cIltcbiAgICAgICAge1xuICAgICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICAgIG1lc3NhZ2U6ICd0ZXh0IHNob3VsZCBub3QgYmUgZW1wdHknLFxuICAgICAgICB9LFxuICAgICAgXVwiXG4gICAgICBwcm9wPVwidGV4dFwiXG4gICAgPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtU3RhdGUudGV4dFwiPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmICx3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgZm9ybVN0YXRlID0gcmVhY3RpdmU8eyBudW1iZXI/OiBudW1iZXI7IHRleHQ/OiBzdHJpbmcgfT4oe30pXG5cbmZ1bmN0aW9uIGhhbmRsZUlucHV0KCkge1xuICBhbGVydCgnRnJvbSBAaW5wdXQgaGFuZGxlcicpXG59XG53YXRjaCgoKT0+Zm9ybVN0YXRlLm51bWJlciwgKCk9Pntcblx0YWxlcnQoYEZyb20gZm9ybVN0YXRlLm51bWJlcidzIHdhdGNoZXJgKVxufSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5ib2R5IHtcbiAgbWFyZ2luOiAwO1xuICBoZWlnaHQ6IDEwMHZoO1xuICBkaXNwbGF5OiBmbGV4O1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgZm9udC1zaXplOiAyNHB4O1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWVlO1xufVxuLmZvcm0ge1xuICB3aWR0aDogNzAwcHg7XG4gIGJhY2tncm91bmQtY29sb3I6IHdoaXRlO1xuICBwYWRkaW5nOiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by holazz** [comment]
> I tried it, but handler only executes when componet blur just like using `watch`. [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBjbGFzcz1cImZvcm1cIiByZWY9XCJmb3JtUmVmXCIgOm1vZGVsPVwiZm9ybVN0YXRlXCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPHA+XG4gICAgICBXaGVuIHNldCBgdHJpZ2dlcmAgdG8gYGNoYW5nZWAgaW4gYHJ1bGVzYCwgdGhlIGBlbC1pbnB1dC1udW1iZXJgIGNvbXBvbmVudFxuICAgICAgc3RpbGwgdmFsaWRhdGUgd2hlbiBgYmx1cmAuXG4gICAgPC9wPlxuICAgIDxlbC1mb3JtLWl0ZW1cbiAgICAgIGxhYmVsPVwibnVtYmVyXCJcbiAgICAgIDpydWxlcz1cIltcbiAgICAgICAge1xuICAgICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICAgIG1lc3NhZ2U6ICdudW1iZXIgc2hvdWxkIG5vdCBiZSBlbXB0eScsXG4gICAgICAgIH0sXG4gICAgICBdXCJcbiAgICAgIHByb3A9XCJudW1iZXJcIlxuICAgID5cbiAgICAgIDxlbC1pbnB1dC1udW1iZXJcbiAgICAgICAgOm1pbj1cIjEwXCJcbiAgICAgICAgOm1heD1cIjEwMFwiXG4gICAgICAgIHYtbW9kZWw9XCJmb3JtU3RhdGUubnVtYmVyXCJcbiAgICAgICAgQGlucHV0PVwiaGFuZGxlSW5wdXRcIlxuICAgICAgPjwvZWwtaW5wdXQtbnVtYmVyPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxwPmBlbC1pbnB1dGAgY29tcG9uZW50IGlzIG5vcm1hbC48L3A+XG4gICAgPGVsLWZvcm0taXRlbVxuICAgICAgbGFiZWw9XCJ0ZXh0XCJcbiAgICAgIDpydWxlcz1cIltcbiAgICAgICAge1xuICAgICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICAgIG1lc3NhZ2U6ICd0ZXh0IHNob3VsZCBub3QgYmUgZW1wdHknLFxuICAgICAgICB9LFxuICAgICAgXVwiXG4gICAgICBwcm9wPVwidGV4dFwiXG4gICAgPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtU3RhdGUudGV4dFwiPjwvZWwtaW5wdXQ+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmICx3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB0eXBlIHsgRm9ybUluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtUmVmID0gcmVmPEZvcm1JbnN0YW5jZT4oKVxuY29uc3QgZm9ybVN0YXRlID0gcmVhY3RpdmU8eyBudW1iZXI/OiBudW1iZXI7IHRleHQ/OiBzdHJpbmcgfT4oe30pXG5cbmZ1bmN0aW9uIGhhbmRsZUlucHV0KCkge1xuICBhbGVydCgnRnJvbSBAaW5wdXQgaGFuZGxlcicpXG59XG53YXRjaCgoKT0+Zm9ybVN0YXRlLm51bWJlciwgKCk9Pntcblx0YWxlcnQoYEZyb20gZm9ybVN0YXRlLm51bWJlcidzIHdhdGNoZXJgKVxufSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5ib2R5IHtcbiAgbWFyZ2luOiAwO1xuICBoZWlnaHQ6IDEwMHZoO1xuICBkaXNwbGF5OiBmbGV4O1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgZm9udC1zaXplOiAyNHB4O1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWVlO1xufVxuLmZvcm0ge1xuICB3aWR0aDogNzAwcHg7XG4gIGJhY2tncm91bmQtY29sb3I6IHdoaXRlO1xuICBwYWRkaW5nOiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

It seems that the input event behavior is inconsistent with the native input, I'll fix it later.

**Comment by Gu-Miao** [comment]
We seemed ignore something important:

- For `<el-input>` component, the `change` event fires when value inputed or removed. This is different from native `<input>`'s behavior.
- For `<el-input-number>`, the `change` event fires when value change and blur. This is same as native native `<input>`'s behavior.

So when using `<el-input-number>`, We have to use `@input` event. And add verification manually. (I don't know if `tirgger` attribute supports `input`, there are only `blur` and `change` in document).

**Comment by Gu-Miao** [comment]
Yes, you're right. I understand it now.
