### ISSUE TITLE
希望新增【TreeSelect】组件

### ISSUE THREAD

**Issue by kailong321200875** [element-plus/element-plus#985]
1. The overall description of component
希望新增TreeSelect组件，因为很多情况下，Select组件并不能满足，只能自己把Select组件和Tree组件结合起来，多少有点不尽人意，希望官方可以新增一个TreeSelect组件。

2. The actual requirements
参考 https://ant.design/components/tree-select-cn/

3. If there is any reference that we can refer to
参考 https://ant.design/components/tree-select-cn/

**Comment by Ryan2128** [comment]
#878

**Comment by JeremyWuuuuu** [comment]
Please open a discussion here: https://github.com/element-plus/element-plus/discussions, I'm closing this issue
