### ISSUE TITLE
[Component] [checkbox-group] el-checkbox-group 的 checkbox  label为对象时，无法选中

### ISSUE THREAD

**Issue by yunuo-tech** [element-plus/element-plus#9855]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-checkbox-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuICBcbiAgY29uc3Qgc3BlY0l0ZW09cmVmKFtcbiAgICB7XG4gICAgICAgIFwiaWRcIjogXCIxMDAwMDU2ODNcIixcbiAgICAgICAgXCJ2YWx1ZVwiOiBcImNvbG9yX2ZhbWlseVwiLFxuICAgICAgICBcImxlYWZcIjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIFwiaWRcIjogXCIzMzBcIixcbiAgICAgICAgICAgICAgICBcInZhbHVlXCI6IFwiT2xpdmVcIlxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICBcImlkXCI6IFwiNjgwXCIsXG4gICAgICAgICAgICAgICAgXCJ2YWx1ZVwiOiBcIkNIRVJSWVwiXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgIFwiaWRcIjogXCI4NzRcIixcbiAgICAgICAgICAgICAgICBcInZhbHVlXCI6IFwiR2FsYXh5XCJcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBcbiAgICAgICAgXVxuICAgIH1cblxuXSk7XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuXG4gIDxwPlxuICAgPGVsLWZvcm0taXRlbSB2LWZvcj1cIihzcGVjKSBpbiBzcGVjSXRlbVwiIDpsYWJlbD1cInNwZWMudmFsdWVcIiA6cHJvcD1cInNwZWMudmFsdWVcIiA6a2V5PVwic3BlYy5pZCArICdfaWQnXCI+XG5cdFx0XHQ8ZWwtY2hlY2tib3gtZ3JvdXAgPlxuXHRcdFx0XHQ8ZWwtY2hlY2tib3ggdi1mb3I9XCJvcHRpb24gaW4gc3BlYy5sZWFmXCIgOmtleT1cIm9wdGlvbi5pZFwiIDpsYWJlbD1cIm9wdGlvblwiIHN0eWxlPVwid2lkdGg6IDIwMHB4XCI+XG5cdFx0XHRcdFx0e3sgb3B0aW9uLnZhbHVlIH19XG5cdFx0XHRcdDwvZWwtY2hlY2tib3g+XG5cdFx0XHQ8L2VsLWNoZWNrYm94LWdyb3VwPlxuXHRcdDwvZWwtZm9ybS1pdGVtPlxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

#

### What is Expected?

能够勾选

### What is actually happening?

无法勾选，旧版本是可以的，最新版本不行。

### Additional comments

_(empty)_

**Comment by yunuo-tech** [comment]
这个问题还是没解决呀

**Comment by xjcjackin** [comment]
是的，存在相同情况
