### ISSUE TITLE
[Style] [steps] 步骤条的连接线也要跟着status变色

### ISSUE THREAD

**Issue by HwuuF7** [element-plus/element-plus#9859]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome/105.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-steps`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwid2lkdGg6IDUwMHB4OyBwYWRkaW5nOiAyMHB4OyBib3JkZXI6IDJweCBzb2xpZCByZWQ7XCI+XG4gICAgPGVsLXN0ZXBzIDphY3RpdmU9XCIzXCIgZmluaXNoLXN0YXR1cz1cInN1Y2Nlc3NcIj5cbiAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAxXCIgLz5cbiAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAyXCIgLz5cbiAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAzXCIgLz5cbiAgICAgIDxlbC1zdGVwIHRpdGxlPVwiU3RlcCAzXCIgLz5cbiAgICA8L2VsLXN0ZXBzPlxuICA8L2Rpdj5cbiAgICBcblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

el-steps激活步数时只有icon和文字变色了

### What is Expected?

在这个例子中，active为3，应该是1-3之间的el-step__line也要变成success色

### What is actually happening?

只有icon和文字变色了

### Additional comments

_(empty)_

**Comment by HwuuF7** [comment]
![1663773738248](https://user-images.githubusercontent.com/62701603/191545050-f26307c5-fd87-4821-8329-d023e951ebaf.png)

**Comment by chuilee** [comment]
这个加个样式不就好了吗
```scss
<style scoped lang="scss">
:deep(.is-success) {
  .el-step__line {
    background-color: var(--el-color-success);
  }
}
</style>```

**Comment by HwuuF7** [comment]
> 

你这个会把3条线都置色了

**Comment by chuilee** [comment]
> 

是的 请忽略。这是个bug @gjfei 已解决了

**Comment by chuilee** [comment]
> > @chuilee
> 
> 你这个会把3条线都置色了

 是的，请忽略。 @gjfei 已解决了
