### ISSUE TITLE
[产品建议]希望Loading组件支持插槽

### ISSUE THREAD

**Issue by microkof** [element-plus/element-plus#986]
现代前端开发中，如果接口出错，最佳实践是将Loading的转圈svg改成出错svg，同时在下方放一个“重新加载”的按钮，因此：

需要Loading支持插槽。

我知道2.0没有这个能力，希望plus版本能加上，谢谢！

**Comment by JeremyWuuuuu** [comment]
Please add this to https://github.com/element-plus/element-plus/discussions, I am closing this issue.
