### ISSUE TITLE
[Component] [checkbox] el-checkbox的@click事件会被触发两次（The @click event of the <el-checkbox> will be triggered twice）

### ISSUE THREAD

**Issue by yuyulangqi** [element-plus/element-plus#9864]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome/104.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-checkbox`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1jaGVja2JveCB2LW1vZGVsPVwiY2hlY2tlZDFcIiBAY2xpY2s9XCJ0ZXN0XCIgbGFiZWw9XCJPcHRpb24gMVwiIHNpemU9XCJsYXJnZVwiIC8+XG4gIDwvZGl2PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBmdW5jdGlvbiB0ZXN0KCl7XG4gICAgYWxlcnQoJzExMScpXG4gIH1cblxuY29uc3QgY2hlY2tlZDEgPSByZWYodHJ1ZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击页面复选框会有两个弹窗

### What is Expected?

修复bug

### What is actually happening?

修复bug

### Additional comments

_(empty)_

**Comment by gjfei** [comment]
https://developer.aliyun.com/article/263755
