### ISSUE TITLE
[Component] [table] 浏览器引入element-plus最新版，表格组件有问题

### ISSUE THREAD

**Issue by JaneII** [element-plus/element-plus#9877]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `CDN`

### Related Component

- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/janeII/pen/XWqeNrW)

### Steps to reproduce

1、浏览器引入element plus（ unpkg或jsDelivr的cdn）
2、复制官网table组件案例

### What is Expected?

表格本来的样子，
比如：表头都是一行里有多列

### What is actually happening?

实际，表头每一列都成了一行

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Please check if you have the same problem before asking.

[vue docs](https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats)
please use <el-table-column></el-table-column> replace to <el-table-column />
