### ISSUE TITLE
[Component] [form-item] Implicit required validation rule auto-creation based on "required" prop

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#9885]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Firefox 105 / Windows 10`
- Build Tool: `Vue CLI`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPSdsYWJlbCcgcmVxdWlyZWQ+XG4gIFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<el-form-item label="label" required><el-input v-model="msg" /></el-form-item>
```
We use backend validation and "required" prop on form-item for visualization purposes only (asterisk).
So "prop" is not set intentionally.

### What is Expected?

No required validation when "prop" is undefined

### What is actually happening?

"is required" validation error is always shown on such form items

### Additional comments

Now the only way to disable unneeded required validation is to set :validate-event="false" on every(!) input on the form.This is very inconvenient. Please add check for prop !== undefined in form-item.vue:200

In Element-UI required prop on form-item worked as expected.

**Comment by btea** [comment]
Regarding your scenario, I think it is more convenient to use the combination of asterisk and input. [for example](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCI+XG4gIFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZSBzY29wZWQ+XG4gIC5ib3gge1xuICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gIH1cbiAgLmJveDo6YmVmb3JlIHtcbiAgICBjb250ZW50OiAnKic7XG4gICAgY29sb3I6IHJlZDtcbiAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgbGVmdDogMDtcbiAgfVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by MonkeyMaster** [comment]
It's only a couple of lines to change in code.
Moreover, now the form behaviour is inadequate when model/props are not set.

**Comment by dormadekhin** [comment]
> No - we need the complete form layout with labels/inputs/errors, just no client-side validation. It's only a couple of lines of code to change. Moreover, now the form behaviour is inadequate when model/props are not set.

+1

**Comment by otiosi** [comment]
I agree with the author. This would simplify the writing of forms and allow them to be used more flexibly.

**Comment by 130792** [comment]
> No - we need the complete form layout with labels/inputs/errors, just no client-side validation. It's only a couple of lines of code to change. Moreover, now the form behaviour is inadequate when model/props are not set.

+1

**Comment by zsv93** [comment]
+1

**Comment by Epistarh1tut** [comment]
> No - we need the complete form layout with labels/inputs/errors, just no client-side validation. It's only a couple of lines of code to change. Moreover, now the form behaviour is inadequate when model/props are not set.

+1
