### ISSUE TITLE
ElTabs和vue的v-if组件配合会导致整体vue产生bug，必须刷新才可以

### ISSUE THREAD

**Issue by ht-sauce** [element-plus/element-plus#989]
复现地址：
https://github.com/ht-sauce/vuemini-test
重现步骤
我使用了element-plus的tabs组件，当组件内部的子组件和v-if配合的时候会产生vue方面的错误。
在git代码示例中，请单击“切换tabs产生的bug”按钮，复现错误
我使用了plus元素的tabs组件。当组件内部的子组件与V-IF配合使用时，将出现Vue错误。

在GIT代码示例中，单击“切换选项卡产生的错误”按钮以重现错误

**Comment by JeremyWuuuuu** [comment]
Thank you for reporting this issue. We will investigate it soon. cc @bastarder

**Comment by xiaoxian521** [comment]
@ht-sauce 
问题：当组件内部的子组件和v-if配合的时候会产生vue方面的错误。
解决办法: 可以使用v-show

**Comment by ht-sauce** [comment]
> @ht-sauce
> 问题：当组件内部的子组件和v-if配合的时候会产生vue方面的错误。
> 解决办法: 可以使用v-show

我需要刷新组件内部状态。也就是重新运行该组件。v-if是比较省代码的方式了。

**Comment by ht-sauce** [comment]
> Thank you for reporting this issue. We will investigate it soon. cc @bastarder

我发现在el-table组件中动态的变化整个列数据也会造成这种情况。
`<el-table
      cell-class-name="custom-cell"
      style="margin: 10px 0;"
      height="354px"
      :data="tablelist"
      border
      :header-cell-style="{ padding: '4px' }"
    >
      <template v-for="(item, index) in colums" :key="index">
        <el-table-column
          :sortable="item.sortable"
          :prop="item.prop"
          :align="item.align || 'left'"
          :label="item.label"
          :width="item.width"
          :min-width="item.minWidth ? item.minWidth : ''"
        />
      </template>
    </el-table>`
像上面的colums，如果我整个都给换掉的话。那么就出现同样的问题了。

**Comment by xiaoxian521** [comment]
@ht-sauce 我认为那你可以尝试不适用element-plus去渲染数据 可以用普通标签尝试 如果还出问题那你应该去vue-next提一下issues

**Comment by JeremyWuuuuu** [comment]
I think it could be a potential problem, we will investigate this. Thank you for the issue.

**Comment by ht-sauce** [comment]
> @ht-sauce 我认为那你可以尝试不适用element-plus去渲染数据 可以用普通标签尝试 如果还出问题那你应该去vue-next提一下issues

我自己实现了最简单的v-for循环和带有基础自定义组件的实现无法发现问题。但是采用了element的组件会引发问题。
这是demo地址：https://github.com/ht-sauce/vuemini-test
请点击页面的‘切换表格列引起的bug’
里面有我复现的bug。我之前给vue-next提过bug，但是无法复现无elementui组件的方式。所以到这里了。表格还好。但是我想tabs组件的问题是比较严重的。很多小伙伴都会这样去操作。
![R{9JAXZF IRNN2XUGL}UFM0](https://user-images.githubusercontent.com/34828964/102294145-918af200-3f83-11eb-9772-fbc961cd826f.png)

**Comment by JeremyWuuuuu** [comment]
Got it. cc @bastarder

**Comment by JeremyWuuuuu** [comment]
Hey, I've just investigated the issue. So it was caused by `Vue` instead of `ElementPlus`, see this. https://github.com/vuejs/vue-next/issues/2737 Also the fix: https://github.com/vuejs/vue-next/commit/c59897c7b0dbd82b5bbf3fbca945c0639ac37fb8

**Comment by JeremyWuuuuu** [comment]
The current available solution is that you downgrade your `Vue`'s version to `3.0.3`, that should be good.
You can solve this by 
```shell
$ yarn add vue@3.0.3
```
See the screenshot:
![image](https://user-images.githubusercontent.com/15975785/102571611-dc903b00-4124-11eb-956a-5dfb002a8d58.png)

**Comment by JeremyWuuuuu** [comment]
Note that unless `Vue` gives us a new version `3.0.5`, you will still have issues because in `3.0.3` they have some serious issues as well.

**Comment by ht-sauce** [comment]
> Note that unless `Vue` gives us a new version `3.0.5`, you will still have issues because in `3.0.3` they have some serious issues as well.

谢谢，现在我在生产中采用其他方式实现该功能。

**Comment by JeremyWuuuuu** [comment]
> > Note that unless `Vue` gives us a new version `3.0.5`, you will still have issues because in `3.0.3` they have some serious issues as well.
> 
> 谢谢，现在我在生产中采用其他方式实现该功能。

NP, feel free to ping me when you have any other questions.

**Comment by JeremyWuuuuu** [comment]
Note that this issue will only appear when you have slots being dynamically updated.
