### ISSUE TITLE
[Component] [menu-item] When there is a "flex container" among the parent elements of component "el-menu" , the last "el-menu-item" would be wrongly rendered as "el-sub-menu" with 3 dots

### ISSUE THREAD

**Issue by CJc-3103** [element-plus/element-plus#9891]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105.0.5195.102 / Windows 8.1`
- Build Tool: `Vue CLI`

### Related Component

- `el-menu-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtZW51TGlzdCA9IHJlZihbXG4gIHtcbiAgICB0aXRsZTogJ2hvbWUnLFxuICAgIGluZGV4OiAnMSdcbiAgfSxcbiAge1xuICAgIHRpdGxlOiAnc2V0dGluZ3MnLFxuICAgIGluZGV4OiAnMidcbiAgfVxuXSk7XG5jb25zdCBjdXJyZW50TmF2ID0gcmVmKG1lbnVMaXN0LnZhbHVlWzBdLnRpdGxlKTtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIC5uYXYtYmFye1xuXHRcdGRpc3BsYXk6IGZsZXg7XG4gIH1cbjwvc3R5bGU+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZGl2IGNsYXNzPVwibmF2LWJhclwiPlxuICAgICAgPGVsLW1lbnVcbiAgICAgICAgbW9kZT1cImhvcml6b250YWxcIlxuICAgICAgICA6ZGVmYXVsdC1hY3RpdmU9XCJjdXJyZW50TmF2XCJcbiAgICAgICAgcm91dGVyXG4gICAgICA+XG4gICAgICAgIDxlbC1tZW51LWl0ZW1cbiAgICAgICAgICB2LWZvcj1cIih7IHRpdGxlLCBpbmRleCB9LCBpKSBpbiBtZW51TGlzdFwiXG4gICAgICAgICAgOmtleT1cImlcIlxuICAgICAgICAgIDppbmRleD1cImluZGV4XCJcbiAgICAgICAgICA+e3sgdGl0bGUgfX08L2VsLW1lbnUtaXRlbVxuICAgICAgICA+XG4gICAgICA8L2VsLW1lbnU+XG4gICAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### What is Expected?

the last child of "el-menu" should be still "el-menu-item"

### What is actually happening?

the last child of "el-menu" would be wrongly rendered as "el-sub-menu" with 3 dots nesting a second level "el-menu-item"

![image](https://user-images.githubusercontent.com/30076349/192106576-52fe06b9-18d9-4249-9730-64d1749b8fb9.png)

**Comment by holazz** [comment]
This is not a bug, you can set `width: 100%` for `el-menu`.

**Comment by CJc-3103** [comment]
> This is not a bug, you can set `width: 100%` for `el-menu`.

Thanks for your reply.
But I need to apply other components  together with the  `el-menu` in `el-header`, such as a `dropdown-menu` which doesn't belongs to the `el-menu`. So `width: 100%` for `el-menu` is not suitable in my case. Is there any other solution for my case, or do I need to adjust the layout structure?
