### ISSUE TITLE
dialog title slot not working

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#990]
### Version
element-plus: 1.0.1-beta.8
vue: 3.0.4

### Environment
macOS 10.15.7

### Reproduction link
[view](https://codesandbox.io/s/distracted-ritchie-zpih2?file=/src/App.vue)

### What is expected?
The title slot working

### What is actually happening?
The title slot not working

---

**Comment by JeremyWuuuuu** [comment]
Yes, this is a mistake that I have committed before. Will be fixed ASAP.
