### ISSUE TITLE
[Build] [All] Low Version Firefox compatibility issues(低版本火狐浏览器兼容性问题)

### ISSUE THREAD

**Issue by wk727705142** [element-plus/element-plus#9903]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.9`
- Browser / OS: `Firefox Quantum 69-71（window 10 x64）`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ2Vudmlyb25tZW50IGxpbmsnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGEgaHJlZj1cImh0dHBzOi8vdml0ZS1zdGFydGVyLmVsZW1lbnQtcGx1cy5vcmcvXCI+bGluayhDb3BlIHRoaXMgbGluayB0byBGaXJlZm94IDY5IG9yIDcxKTwvYT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Install Firefox Quantum 69 and using it open the link that I offer, open the console, error can be found.（安装Firefox 69版本的浏览器，输入复现环境的连接，打开控制台可查看报错）

### What is Expected?

Normal use built package(正常使用打包后的项目)

### What is actually happening?

can not work on firefox （无法在火狐正常使用打包后的项目）

### Additional comments

Unsupport regular \p
Reference:
https://stackoverflow.com/questions/54534267/firefox-throws-invalid-identity-escape-in-regular-expression-when-using-perl-t?noredirect=1

不支持正则的表达式 \p
参考连接 :
https://stackoverflow.com/questions/54534267/firefox-throws-invalid-identity-escape-in-regular-expression-when-using-perl-t?noredirect=1

**Comment by wk727705142** [comment]
![image](https://user-images.githubusercontent.com/34825962/192231204-ce6351b3-56c3-495f-a181-81c4da8bbb04.png)


Error image

**Comment by holazz** [comment]
Please follow the documentation.
https://element-plus.org/en-US/guide/installation.html#compatibility
