### ISSUE TITLE
[Component] [form, form-item] 点击表单元素的标签文本,发现input select等自动聚焦

### ISSUE THREAD

**Issue by Ever12349** [element-plus/element-plus#9906]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Chrome 105.0.5195.127`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/form.html#%E5%85%B8%E5%9E%8B%E8%A1%A8%E5%8D%95)

### Steps to reproduce

打开网址-> 单击 #典型表单 中的 "Activity name"文本,后面的input自动聚焦;
打开网址-> 单击 #典型表单 中的 "Activity zone"文本,后面的select自动聚焦,并且打开下拉选项;
打开网址-> 单击 #典型表单 中的 "Instant delivery"文本,后面switch自动切换;

### What is Expected?

希望与element-ui保持一致

### What is actually happening?

打开网址-> 单击 #典型表单 中的 "Activity name"文本,后面的input自动聚焦;
打开网址-> 单击 #典型表单 中的 "Activity zone"文本,后面的select自动聚焦,并且打开下拉选项;
打开网址-> 单击 #典型表单 中的 "Instant delivery"文本,后面switch自动切换;

### Additional comments

_(empty)_

**Comment by btea** [comment]
This is normal behavior, you can refer to this [standard](https://www.w3.org/WAI/tutorials/forms/labels/).
