### ISSUE TITLE
[Component] [backtop] backtop组件可能因为防抖导致滚动到页面顶部后依然显示backtop按钮

### ISSUE THREAD

**Issue by luyaoguang1992** [element-plus/element-plus#9909]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `chrome/windows`
- Build Tool: `Vite`

### Related Component

- `el-backtop`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/backtop.html)

### Steps to reproduce

滚动到底部后，点击返回顶部按钮或者快速滑动到顶部

### What is Expected?

返回到顶部按钮隐藏

### What is actually happening?

返回按钮依然展示

### Additional comments

_(empty)_

**Comment by btea** [comment]
fixed #9892
