### ISSUE TITLE
[Component] [menu] menu组件展开卡顿

### ISSUE THREAD

**Issue by luyaoguang1992** [element-plus/element-plus#9910]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `chrome/mac`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/menu.html)

### Steps to reproduce

点击展开导航组件

### What is Expected?

展开不卡顿

### What is actually happening?

展开卡顿

### Additional comments

_(empty)_

**Comment by gaojiangtao-git** [comment]
需要自己手动增加一个动画效果就解决了：transition 0.3 ease

**Comment by sxzz** [comment]
Can't reproduce.

**Comment by JasonBrook97** [comment]
我也遇到了 element plus   menu 疑似卡顿的问题。 卡顿现象为垂直的菜单，展开快结束的时候感到明显的停顿。我经过测试发现是这条css导致的：
.horizontal-collapse-transition {
    transition: var(--el-transition-duration) width linear, var(--el-transition-duration) padding-left linear, var(--el-transition-duration) padding-right ease-in-out;
}
改成
.horizontal-collapse-transition {
    transition: var(--el-transition-duration) width linear;
}
就会顺滑很多

**Comment by chenxch** [comment]
> 我也遇到了 element plus menu 疑似卡顿的问题。 卡顿现象为垂直的菜单，展开快结束的时候感到明显的停顿。我经过测试发现是这条css导致的： .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear, var(--el-transition-duration) padding-left linear, var(--el-transition-duration) padding-right ease-in-out; } 改成 .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear; } 就会顺滑很多

方便提供一个卡顿的demo么，官网的我这边怎么点和查看性能分析都是没发现你们说的问题

**Comment by JasonBrook97** [comment]
hi Xc
&nbsp;我尝试着写一个demo，但是在Element Plus Playground上复现不出来，我把我的部分代码发送给你，需要安装依赖在vscode上运行起来看，用的yarn&nbsp; vite。在ContentStructure.vue中。
图中画红圈的地方是展开闭合菜单的按钮。





Jason
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月30日(星期天) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus] [Component] [menu] menu组件展开卡顿 (Issue #9910)





  
我也遇到了 element plus menu 疑似卡顿的问题。 卡顿现象为垂直的菜单，展开快结束的时候感到明显的停顿。我经过测试发现是这条css导致的： .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear, var(--el-transition-duration) padding-left linear, var(--el-transition-duration) padding-right ease-in-out; } 改成 .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear; } 就会顺滑很多
  
方便提供一个卡顿的demo么，官网的我这边怎么点和查看性能分析都是没发现你们说的问题

**Comment by JasonBrook97** [comment]
添加下面这条css ，闭合的时候明显会闪一下，先收回一小段距离，再慢慢收回
.horizontal-collapse-transition {
    transition: 300s width linear;
}

**Comment by toplyb** [comment]
请问楼主解决这个问题了吗？我发现只要给 el-menu 组件设置宽度后，折叠的动画就消失了，不设置宽度的话，就有动画，请问这种问题该怎么解决呢

**Comment by JasonBrook97** [comment]
![image](https://user-images.githubusercontent.com/75793726/211158607-8c964e33-2c94-448c-97ec-46bf51113c05.png)

**Comment by zhao605207225** [comment]
如果el-menu-item  el-sub-menu在另一个模板中,没直接在el-menu下面就这样

**Comment by jiangdaqi** [comment]
这边同样遇到垂直menu展开、收缩卡顿现象，并且卡顿十分明显，就把官网demo copy到本地就必现，特别是选中index1-4-1的时候。
vue版本3.2.47
element-plus版本2.3.3

**Comment by Liangqianyong** [comment]
https://github.com/element-plus/element-plus/issues/6792

找了好几天，发现了这个

**Comment by zhangyuge7** [comment]
> > 我也遇到了 element plus menu 疑似卡顿的问题。 卡顿现象为垂直的菜单，展开快结束的时候感到明显的停顿。我经过测试发现是这条css导致的： .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear, var(--el-transition-duration) padding-left linear, var(--el-transition-duration) padding-right ease-in-out; } 改成 .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear; } 就会顺滑很多
> 
> 方便提供一个卡顿的demo么，官网的我这边怎么点和查看性能分析都是没发现你们说的问题

你可以换个显示器试试，我在笔记本上很丝滑，放在27寸60hz的屏幕上菜单折叠展开和子菜单展开都很卡，把27寸显示器刷新率改成100hz也是卡，

**Comment by jiangyalin** [comment]
遇到同样的问题，目前发现只在菜单图标为<Setting />并且不为第一个时才能在部分pc上复现
![image](https://github.com/user-attachments/assets/fdd5fd12-6466-423c-8ff5-c6df9a356dbe)
类似这种情况下展开与折叠’基础档案‘时，能触发卡顿现象

**Comment by anZong** [comment]
> > > 我也遇到了 element plus menu 疑似卡顿的问题。 卡顿现象为垂直的菜单，展开快结束的时候感到明显的停顿。我经过测试发现是这条css导致的： .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear, var(--el-transition-duration) padding-left linear, var(--el-transition-duration) padding-right ease-in-out; } 改成 .horizontal-collapse-transition { transition: var(--el-transition-duration) width linear; } 就会顺滑很多
> > 
> > 
> > 方便提供一个卡顿的demo么，官网的我这边怎么点和查看性能分析都是没发现你们说的问题
> 
> 你可以换个显示器试试，我在笔记本上很丝滑，放在27寸60hz的屏幕上菜单折叠展开和子菜单展开都很卡，把27寸显示器刷新率改成100hz也是卡，

哈哈哈，真的很神奇，一开始我以为是来逗乐的，然后我也重现到了
