### ISSUE TITLE
[Component] [message-box] messagebox弹窗，弹出后确定按钮聚焦，需要点击其他地方才失焦

### ISSUE THREAD

**Issue by luyaoguang1992** [element-plus/element-plus#9911]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `chrome/windows`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/message-box.html)

### Steps to reproduce

点击打开messagebox

### What is Expected?

foucus不在确定按钮上

### What is actually happening?

确定按钮focus，需要点击其他地方才会失焦

### Additional comments

_(empty)_

**Comment by btea** [comment]
你可以将`autofocus`设置为`false`, [文档](https://element-plus.org/zh-CN/component/message-box.html#messagebox-%E9%85%8D%E7%BD%AE%E9%A1%B9).

**Comment by ryuhangyeong** [comment]
## Example

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gdGhlIE1lc3NhZ2UgQm94PC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSB7IEFjdGlvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgRWxNZXNzYWdlQm94LmFsZXJ0KCdUaGlzIGlzIGEgbWVzc2FnZScsICdUaXRsZScsIHtcbiAgICAvLyBpZiB5b3Ugd2FudCB0byBkaXNhYmxlIGl0cyBhdXRvZm9jdXNcbiAgICBhdXRvZm9jdXM6IGZhbHNlLFxuICAgIGNvbmZpcm1CdXR0b25UZXh0OiAnT0snLFxuICAgIGNhbGxiYWNrOiAoYWN0aW9uOiBBY3Rpb24pID0+IHtcbiAgICAgIEVsTWVzc2FnZSh7XG4gICAgICAgIHR5cGU6ICdpbmZvJyxcbiAgICAgICAgbWVzc2FnZTogYGFjdGlvbjogJHthY3Rpb259YCxcbiAgICAgIH0pXG4gICAgfSxcbiAgfSlcbn1cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
