### ISSUE TITLE
[Component] [select-v2] el-select-v2 无法像 el-select 一样支持 filter-method 自定义筛选方法

### ISSUE THREAD

**Issue by JackieCheung** [element-plus/element-plus#9914]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Steps to reproduce

el-select-v2 只能设置 remote 和 remote-method 进行远程搜索，无法在原数据的基础上进行自定义搜索，remote-method有不好的地方就是没有下拉图标和下拉面板

### What is Expected?

el-select-v2 支持 filter-method

### What is actually happening?

el-select-v2 不支持 filter-method

### Additional comments

_(empty)_

**Comment by Little-Frog-233** [comment]
+1

**Comment by 278949501** [comment]
使用 remote 和 remote-method，visible-change时再重置下选项。
