### ISSUE TITLE
[Component] [table] 给tableData重新赋值后 current-row-key="1" 失效

### ISSUE THREAD

**Issue by yyq-bit** [element-plus/element-plus#9919]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105.0.5195.127`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgcm93LWtleT1cImlkXCIgY3VycmVudC1yb3cta2V5PVwiMVwiIGhpZ2hsaWdodC1jdXJyZW50LXJvdz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5jb25zdCB0YWJsZURhdGEgPSByZWYoW10pXG5vbk1vdW50ZWQoKCk9PntcbiAgdGFibGVEYXRhLnZhbHVlID0gW1xuICAgIHtcbiAgICAgIGlkOiAnMScsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6ICcyJyxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogJzMnLFxuICAgICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB9LFxuICAgIHtcbiAgICAgIGlkOiAnNCcsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gIF1cbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

直接写死tableData，current-row-key="1" highlight-current-row，第一行高亮生效，给tableData重新赋值后，第一行高亮失效

### What is Expected?

current-row-key="1" highlight-current-row
第一行高亮

### What is actually happening?

高亮失效

### Additional comments

_(empty)_

**Comment by dreambo8563** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgcm93LWtleT1cImlkXCIgOmN1cnJlbnQtcm93LWtleT1cInJcIiBoaWdobGlnaHQtY3VycmVudC1yb3c+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuY29uc3QgdGFibGVEYXRhID0gcmVmKFtdKVxuY29uc3QgciA9cmVmKG51bGwpXG5vbk1vdW50ZWQoKCk9PntcbiAgdGFibGVEYXRhLnZhbHVlID0gW1xuICAgIHtcbiAgICAgIGlkOiAnMScsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6ICcyJyxcbiAgICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICAgIG5hbWU6ICdUb20nLFxuICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgfSxcbiAgICB7XG4gICAgICBpZDogJzMnLFxuICAgICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgICAgbmFtZTogJ1RvbScsXG4gICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB9LFxuICAgIHtcbiAgICAgIGlkOiAnNCcsXG4gICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICBuYW1lOiAnVG9tJyxcbiAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIH0sXG4gIF1cbiAgci52YWx1ZSA9MTtcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==


set `current-row-key` after assigning the table data.

**Comment by chenxch** [comment]
This is a sequential problem. When the component processes the `current-row-key`, the table has no data. You can refer to @dreambo8563  reply.
