### ISSUE TITLE
Global config of size not working with table

### ISSUE THREAD

**Issue by TothingWay** [element-plus/element-plus#992]
### Version
element-plus: 1.0.1-beta.8
vue: 3.0.4

### Environment
macOS 10.15.7

### Step to reproduce

1. app.use(ElementPlus, { size: 'small', zIndex: 3000 });
2. Use table in vue file
3. The size of the table is always as medium

### What is expected?
Global config of size working with table and other components

### What is actually happening?
Global config of size just working with button

**Comment by JeremyWuuuuu** [comment]
cc @justwiner

**Comment by JeremyWuuuuu** [comment]
Maybe @justwiner did not implement that, because by the time table got merged, global config had not been added into the bundle entry yet.

**Comment by TothingWay** [comment]
How long do you expect it to be fixed.

**Comment by JeremyWuuuuu** [comment]
The fix itself is rather simple. But it depends on @justwiner 's time arrangement.

**Comment by JeremyWuuuuu** [comment]
Also, PR is welcomed, we are happy if you could provide help.

**Comment by TothingWay** [comment]
ok，I'll try to it

**Comment by justwiner** [comment]
sry, my first. hhh~ 
@TothingWay 
```js
const tableSize = computed(() => {
    return props.size || getConfig('size')
})
```

**Comment by TothingWay** [comment]
hhh, I was about to mention PR, and you fixed it, so fast

**Comment by zazzaz** [comment]
@TothingWay Hi, thanks for your attention. Actually, there is still a lot of work we can do to make Element Plus better.

e.g. https://github.com/element-plus/element-plus/pull/984 This PR only updates the Chinese doc.

It will be great if you could help us to make a PR to update the doc in other languages accordingly.
