### ISSUE TITLE
[Component] [date-picker, dialog] [date-picker] el-date-picker 在dialog中使用需要双击显示日期选择器

### ISSUE THREAD

**Issue by hub826** [element-plus/element-plus#9922]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDwhLS0gRm9ybSAtLT5cbiAgPGVsLWJ1dHRvbiB0ZXh0IEBjbGljaz1cImRpYWxvZ0Zvcm1WaXNpYmxlID0gdHJ1ZVwiXG4gICAgPm9wZW4gYSBGb3JtIG5lc3RlZCBEaWFsb2c8L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwiZGlhbG9nRm9ybVZpc2libGVcIiB0aXRsZT1cIkZyb21cIj5cbiAgICA8ZWwtZm9ybSA6bW9kZWw9XCJmb3JtXCI+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiUHJvbW90aW9uIG5hbWVcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubmFtZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+XG4gICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJQaWNrIGEgZGF5XCIgOmxhYmVsLXdpZHRoPVwiZm9ybUxhYmVsV2lkdGhcIj5cbiAgICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICB0eXBlPVwiZGF0ZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiXG4gICAgICAvPlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiWm9uZXNcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdCBhIHpvbmVcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBOby4xXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgTm8uMlwiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPC9lbC1mb3JtPlxuICAgIDx0ZW1wbGF0ZSAjZm9vdGVyPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkaWFsb2ctZm9vdGVyXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZGlhbG9nRm9ybVZpc2libGUgPSBmYWxzZVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiZGlhbG9nRm9ybVZpc2libGUgPSBmYWxzZVwiXG4gICAgICAgICAgPkNvbmZpcm08L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGlhbG9nVGFibGVWaXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgZGlhbG9nRm9ybVZpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBmb3JtTGFiZWxXaWR0aCA9ICcxNDBweCdcbmNvbnN0IHZhbHVlMSA9IHJlZignJylcblxuY29uc3QgZm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTogJycsXG4gIHJlZ2lvbjogJycsXG4gIGRhdGUxOiAnJyxcbiAgZGF0ZTI6ICcnLFxuICBkZWxpdmVyeTogZmFsc2UsXG4gIHR5cGU6IFtdLFxuICByZXNvdXJjZTogJycsXG4gIGRlc2M6ICcnLFxufSlcblxuY29uc3QgZ3JpZERhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdKb2huIFNtaXRoJyxcbiAgICBhZGRyZXNzOiAnTm8uMTUxOCwgIEppbnNoYWppYW5nIFJvYWQsIFB1dHVvIERpc3RyaWN0JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnSm9obiBTbWl0aCcsXG4gICAgYWRkcmVzczogJ05vLjE1MTgsICBKaW5zaGFqaWFuZyBSb2FkLCBQdXR1byBEaXN0cmljdCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ0pvaG4gU21pdGgnLFxuICAgIGFkZHJlc3M6ICdOby4xNTE4LCAgSmluc2hhamlhbmcgUm9hZCwgUHV0dW8gRGlzdHJpY3QnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmVsLWJ1dHRvbi0tdGV4dCB7XG4gIG1hcmdpbi1yaWdodDogMTVweDtcbn1cbi5lbC1zZWxlY3Qge1xuICB3aWR0aDogMzAwcHg7XG59XG4uZWwtaW5wdXQge1xuICB3aWR0aDogMzAwcHg7XG59XG4uZGlhbG9nLWZvb3RlciBidXR0b246Zmlyc3QtY2hpbGQge1xuICBtYXJnaW4tcmlnaHQ6IDEwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 新建el-dialog弹窗
2. 在弹窗建from表单，表单加el-date-picker选择器
3. 点击picker选择器左侧icon图标可显示时间选择器，但右侧输入框需要点击两次才会显示时间选择器

### What is Expected?

点击右侧输入框1次即可显示时间选择器

### What is actually happening?

需要点击右侧输入框两次才可显示时间选择器

### Additional comments

升级2.2.17版本之后出现此处问题

**Comment by iivu** [comment]
+1

**Comment by ntnyq** [comment]
Related PR https://github.com/element-plus/element-plus/pull/9669

When focus event on picker input triggered and DatePicker is nested in Dialog, the relatedTarget of focus event is `dialogEl`

 `pickerVisible.value` is set to `false`
