### ISSUE TITLE
[Bug Report] [El-Pagination] ElPagination的API这么设计的意图是什么?

### ISSUE THREAD

**Issue by L1yp** [element-plus/element-plus#9924]
### Element Plus version
2.2.17

### OS/Browsers version
WIN11, Chrome Latest

### Vue version
3.2.39

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-v6ch6t?file=/src/App.vue

### Steps to reproduce
官方文档:
```
以上事件不推荐使用（但由于兼容的原因仍然支持，在以后的版本中将会被删除）；如果要监听 current-page 和 page-size 的改变，使用 v-model 双向绑定是个更好的选择。
```
有个疑问: pagination的事件为何要移除? 
我有个需求是 currenPage或pageSize改变时重新加载数据, 如果移除了事件, 是否应该watch(() => [ currentPage, pageS9ize ], () => loadData())

这个API设计 VXE的pager设计的就蛮好的:
page-change: 分页发生改变时会触发该事件
1. 使用VxePager的代码
```vue
<vxe-pager @page-change="loadData" />
```
2. 未来使用ElPagination的代码
```vue
<el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" />
```
```ts
watch(() => [ currentPage, pageS9ize ], () => loadData())
```

### What is Expected?
新增page-change事件: 页码变化或每页条数变化触发的事件

### What is actually happening?
即将删除事件

**Comment by dantelife** [comment]
我也有个疑问：pageSize变化之后，是不是currentPage也要重置为1，如果移除了pagination事件，怎么知道是pageSize change事件，又如何去重置currentPage？

**Comment by wo4188** [comment]
同问

**Comment by Glory-gg** [comment]
v-model都是有触发事件的
          @update:page-size="loadData()"
          @update:current-page="loadData()"

**Comment by L1yp** [comment]
> 

你这么写的话 最新的 currentPage、pageSize 都拿不到呢，把v-model拆开就得手动赋值currentPage、pageSize呀

**Comment by Glory-gg** [comment]
> > 
> 
> 你这么写的话 最新的 currentPage、pageSize 都拿不到呢，把v-model拆开就得手动赋值currentPage、pageSize呀

为什么拿不到, 不是v-model绑定了吗, 直接用就行的呀

**Comment by L1yp** [comment]
> model都是有触发事件

v-model是:page-size和@update:page-size的简写   用户再定义 @update:page-size 时，无法触发@update:page-size、@update:current-page，请问GG朋友是怎么配置的，可否发个简单的链接

我测试的链接：[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnaW5hdGlvbiBcbiAgICBsYXlvdXQ9XCJwcmV2LCBwYWdlciwgbmV4dCwgc2l6ZXNcIiBcblx0ICA6cGFnZS1zaXplcz1cIlsxMCwgMjAsIDMwLCA0MF1cIlxuICAgIDp0b3RhbD1cIjEwMDBcIiBcbiAgICB2LW1vZGVsOnBhZ2Utc2l6ZT1cInBhZ2VTaXplXCIgXG4gICAgdi1tb2RlbDpjdXJyZW50LXBhZ2U9XCJjdXJyZW50UGFnZVwiXG4gICAgQHVwZGF0ZTpwYWdlLXNpemU9XCJoYW5kbGVQYWdlU2l6ZUNoYW5nZWRcIiBcblx0XHRAdXBkYXRlOmN1cnJlbnQtcGFnZT1cImhhbmRsZUN1cnJlbnRDaGFuZ2VkXCIgXG5cblxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIlxuICBjb25zdCBwYWdlU2l6ZSA9IHJlZigyMClcbiAgY29uc3QgY3VycmVudFBhZ2UgPSByZWYoMSlcbiAgZnVuY3Rpb24gaGFuZGxlUGFnZVNpemVDaGFuZ2VkKHYpIHtcbiAgICBhbGVydCh2ICsgJycpXG4gICAgY29uc29sZS5sb2coJ2hhbmRsZVBhZ2VTaXplQ2hhbmdlZCcsIHYsIHBhZ2VTaXplLnZhbHVlKVxuICB9XG4gIFxuICBmdW5jdGlvbiBoYW5kbGVDdXJyZW50Q2hhbmdlZCh2KSB7XG4gICAgYWxlcnQodiArICcnKVxuICAgIGNvbnNvbGUubG9nKCdoYW5kbGVDdXJyZW50Q2hhbmdlZCcsIHYsIGN1cnJlbnRQYWdlLnZhbHVlKVxuICB9XG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by aliang888** [comment]
目前的解决办法是，不使用v-model 

**[【DEMO】](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnaW5hdGlvbiBcbiAgICBsYXlvdXQ9XCJwcmV2LCBwYWdlciwgbmV4dCwgc2l6ZXNcIiBcblx0ICA6cGFnZS1zaXplcz1cIlsxMCwgMjAsIDMwLCA0MF1cIlxuICAgIDp0b3RhbD1cIjEwMDBcIiBcbiAgICA6cGFnZS1zaXplPVwicGFnZVNpemVcIiBcbiAgICA6Y3VycmVudC1wYWdlPVwiY3VycmVudFBhZ2VcIlxuICAgIEB1cGRhdGU6cGFnZS1zaXplPVwiaGFuZGxlUGFnZVNpemVDaGFuZ2VkXCIgXG5cdFx0QHVwZGF0ZTpjdXJyZW50LXBhZ2U9XCJoYW5kbGVDdXJyZW50Q2hhbmdlZFwiXG4gIC8+XG4gIDxwPlxuICAgIDxiPmN1cnJlbnRQYWdlPC9iPj17e2N1cnJlbnRQYWdlfX1cbiAgPC9wPlxuICA8cD5cbiAgICA8Yj5wYWdlU2l6ZTwvYj49e3twYWdlU2l6ZX19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tIFwidnVlXCJcbiAgY29uc3QgcGFnZVNpemUgPSByZWYoMjApXG4gIGNvbnN0IGN1cnJlbnRQYWdlID0gcmVmKDEpXG4gIGZ1bmN0aW9uIGhhbmRsZVBhZ2VTaXplQ2hhbmdlZCh2KSB7XG4gICAgcGFnZVNpemUudmFsdWU9dlxuICB9XG4gIFxuICBmdW5jdGlvbiBoYW5kbGVDdXJyZW50Q2hhbmdlZCh2KSB7XG4gICAgY3VycmVudFBhZ2UudmFsdWU9dlxuICB9XG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)**

![demo](https://user-images.githubusercontent.com/19453262/208624037-91a335be-3ac0-4050-ae90-42a420c920a4.gif)

**Comment by L1yp** [comment]
> -model是:page-size和@update:page-size的简写 用户再定义 @update:page-size 时，无法触发@update:page-size、@update:current-page，请问GG朋友是怎么配置的，可否发个简单的链接

我觉得这么做要多写2个事件 无疑是 提高了使用成本

**Comment by xingyixiang** [comment]
#14828 增加了一个change事件，能规避同时触发page-size和current-page改变引起多次请求的问题，用起来感觉也更方便一些
