### ISSUE TITLE
[Component] [date-picker] El-date-picker not showing date picker panel after select another el-input or el-select component

### ISSUE THREAD

**Issue by TienNg21** [element-plus/element-plus#9930]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIDxlbC1pbnB1dCAvPlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIHR5cGU9XCJkYXRlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiUGljayBhIGRheVwiXG4gICAgICBmb3JtYXQ9XCJZWVlZL01NL0REXCJcbiAgICAgIHZhbHVlLWZvcm1hdD1cIllZWVktTU0tRERcIlxuICAgID5cbiAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cImNlbGxcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNlbGxcIiA6Y2xhc3M9XCJ7IGN1cnJlbnQ6IGNlbGwuaXNDdXJyZW50IH1cIj5cbiAgICAgICAgICA8c3BhbiBjbGFzcz1cInRleHRcIj57eyBjZWxsLnRleHQgfX08L3NwYW4+XG4gICAgICAgICAgPHNwYW4gdi1pZj1cImlzSG9saWRheShjZWxsKVwiIGNsYXNzPVwiaG9saWRheVwiIC8+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLWRhdGUtcGlja2VyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcyMDIxLTEwLTI5JylcbmNvbnN0IGhvbGlkYXlzID0gW1xuICAnMjAyMS0xMC0wMScsXG4gICcyMDIxLTEwLTAyJyxcbiAgJzIwMjEtMTAtMDMnLFxuICAnMjAyMS0xMC0wNCcsXG4gICcyMDIxLTEwLTA1JyxcbiAgJzIwMjEtMTAtMDYnLFxuICAnMjAyMS0xMC0wNycsXG5dXG5cbmNvbnN0IGlzSG9saWRheSA9ICh7IGRheWpzIH0pID0+IHtcbiAgcmV0dXJuIGhvbGlkYXlzLmluY2x1ZGVzKGRheWpzLmZvcm1hdCgnWVlZWS1NTS1ERCcpKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uY2VsbCB7XG4gIGhlaWdodDogMzBweDtcbiAgcGFkZGluZzogM3B4IDA7XG4gIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG59XG4uY2VsbCAudGV4dCB7XG4gIHdpZHRoOiAyNHB4O1xuICBoZWlnaHQ6IDI0cHg7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBtYXJnaW46IDAgYXV0bztcbiAgbGluZS1oZWlnaHQ6IDI0cHg7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgbGVmdDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTUwJSk7XG4gIGJvcmRlci1yYWRpdXM6IDUwJTtcbn1cbi5jZWxsLmN1cnJlbnQgLnRleHQge1xuICBiYWNrZ3JvdW5kOiAjNjI2YWVmO1xuICBjb2xvcjogI2ZmZjtcbn1cbi5jZWxsIC5ob2xpZGF5IHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB3aWR0aDogNnB4O1xuICBoZWlnaHQ6IDZweDtcbiAgYmFja2dyb3VuZDogdmFyKC0tZWwtY29sb3ItZGFuZ2VyKTtcbiAgYm9yZGVyLXJhZGl1czogNTAlO1xuICBib3R0b206IDBweDtcbiAgbGVmdDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTUwJSk7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Click to el-input component
2. Click to el-date-picker component

### What is Expected?

The date picker panel is showing up

### What is actually happening?

The date picker panel is not showing up

### Additional comments

_(empty)_

**Comment by ntnyq** [comment]
Same Reason https://github.com/element-plus/element-plus/issues/9922
