### ISSUE TITLE
[Docs] [date-picker] DateTime Picker display exception

### ISSUE THREAD

**Issue by cityTS** [element-plus/element-plus#9936]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `Chrome/105.0.0.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0aW1lID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgXG4gIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwidGltZVwiIHR5cGU9XCJkYXRldGltZVwiIHBsYWNlaG9sZGVyPVwiUGljayBhIERhdGVcIiBmb3JtYXQ9XCJZWVlZLU1NLUREIGhoOm1tOnNzXCIgdmFsdWUtZm9ybWF0PVwieFwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

选择时间

### What is Expected?

比如我选择20:00:00，那么时间框应该显示20:00:00；选择08:00:00，那么时间框应该显示08:00:00

### What is actually happening?

实际上，不论选择20:00:00还是08:00:00，时间框都显示08:00:00，但是生成的时间戳是正确的

### Additional comments

_(empty)_

**Comment by cityTS** [comment]
![image](https://user-images.githubusercontent.com/79407037/192524544-824e5831-0dbe-4bd5-a76f-9501ae4166d2.png)

**Comment by btea** [comment]
You should set `hh:mm:ss` to `HH:mm:ss`.

**Comment by ntnyq** [comment]
use `YYYY-MM-DD HH:mm:ss` for 24-hour clock.

or

use `YYYY-MM-DD HH:mm:ssa` or `YYYY-MM-DD HH:mm:ssA` for 12-hour clock.
