### ISSUE TITLE
[Style] el-popup-parent--hidden 会携带 width: calc(100% - 8px) 样式

### ISSUE THREAD

**Issue by HalseySpicy** [element-plus/element-plus#9937]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.35`
- Element Plus Version: `2.2.17`
- Browser / OS: `谷歌 102.0.5005.63 / windows 21H2`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-message-box`
- `el-dialog`

### Reproduction Link

[Link](https://admin.spicyboy.cn/#/home/index)

### Steps to reproduce

1、缩小浏览器到90%
2、打开弹框：drawer、dialog、message-box 都可以
3、在一定情况下会 el-popup-parent--hidden 会出现 style="width: calc(100% - 8px);" 导致样式抖动

### What is Expected?

el-popup-parent--hidden 不出现 style="width: calc(100% - 8px);"

### What is actually happening?

el-popup-parent--hidden 出现 style="width: calc(100% - 8px);"

### Additional comments

前面使用 elemnt-plus 2.2.6 版本没问题的，祝 element-plus 越来越好👍

![image](https://user-images.githubusercontent.com/51069636/192539353-2aa9f076-f2c7-4ae4-8801-b69efb69c7f3.png)

**Comment by chenxch** [comment]
这个应该是lockScreen的功能哦，是为了模态框在使用lock的时候防止界面抖动。

**Comment by iDestin** [comment]
@HalseySpicy 为了别人的隐私，建议将关键信息打一个码

**Comment by HalseySpicy** [comment]
> @HalseySpicy为了他人的隐私，建议将关键信息打一个码

没事，都是 mock 模拟的数据😂

**Comment by chenxch** [comment]
@HalseySpicy hello，你看看是否还有其他问题哈，如果没有的话将关闭这个issue哦~
