### ISSUE TITLE
[Component] [date-picker] date-picker failed to show a second time after triggered by calendar icon

### ISSUE THREAD

**Issue by ntnyq** [element-plus/element-plus#9942]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105 / macOS 12.2.1`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZGF0ZS1waWNrZXJcbiAgICB2LW1vZGVsPVwiZGF0ZVwiXG4gICAgc2l6ZT1cImxhcmdlXCJcbiAgICB0eXBlPVwiZGF0ZVwiXG4gICAgcGxhY2Vob2xkZXI9XCJDbGljayB0aGUgaWNvblwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgZGF0ZSA9IHJlZignJylcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. Ensure `el-date-picker` unfocus
2. Click the calendar icon and pick a date
3. Click the picker or calendar icon

### What is Expected?

Picker panel shows when click the picker or calendar icon.

### What is actually happening?

After step 2. 
The picker panel won't show unless unfocus again or click the clear icon.

### Additional comments

Wrap https://github.com/element-plus/element-plus/blob/cc8b816bd929bba05cdcd3a9f63261961af3b8c8/packages/components/date-picker/src/date-picker-com/basic-date-table.vue#L388 with `setTimeout` may solve this issue and #9921.

It ensures `focusWithClick` to be true when `handleFocus` is called and emit event `pick` only once when click.

**Comment by Simon-He95** [comment]
@ntnyq I followed your steps and did not reproduce this problem, can you provide a reproduced gif

**Comment by ntnyq** [comment]
> @ntnyq I followed your steps and did not reproduce this problem, can you provide a reproduced gif

Fixed in https://github.com/element-plus/element-plus/pull/9941
