### ISSUE TITLE
[Docs] docs: Bad title display at dev-guide and dev-faq zh-cn docs

### ISSUE THREAD

**Issue by jasonren0403** [element-plus/element-plus#9955]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71`
- Build Tool: `Other`

### Related Component

- `N/A`

### Reproduction Link

[Link]()

### Steps to reproduce

Open either https://element-plus.gitee.io/zh-CN/guide/dev-guide.html or https://element-plus.org/zh-CN/guide/dev-guide.html. You could see title rendered separately.

### What is Expected?

correct title is '本地开发'

### What is actually happening?

'本' and '地开发' rendered separately

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/40999116/192714357-7212a541-2ee9-4069-adef-2f02bb9dd0c0.png)

**Comment by chenxch** [comment]
Thanks for the feedback, we have also discovered this problem before and will fix it in the next conference.

**Comment by init-qy** [comment]
I found that the md files `dev-faq, dev-guide, commit-examples` do not start like this
```
---
title: Design
lang: en-US
---
```

`dev-faq, dev-guide` have this problem, but `commit-examples` is correct
I don't know what's wrong, but adding the previous start will solves the problem
Hope this helps you @chenxch

**Comment by chenxch** [comment]
> I found that the md files `dev-faq, dev-guide, commit-examples` do not start like this
> 
> ```
> ---
> title: Design
> lang: en-US
> ---
> ```
> 
> `dev-faq, dev-guide` have this problem, but `commit-examples` is correct I don't know what's wrong, but adding the previous start will solves the problem Hope this helps you @chenxch

Thank you so much, I will contact the person in charge to verify it.
