### ISSUE TITLE
[Component] [table] tfoot is not same table with tbody when use table-layout=auto

### ISSUE THREAD

**Issue by tuongtd** [element-plus/element-plus#9957]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.29`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105.0.0.0 / Window 11`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/table.html#summary-row)

### Steps to reproduce

<el-table
	:data="items"
	:default-sort="{ prop: 'date', order: 'descending' }"
	:summary-method="getSummaries"
	show-summary
	table-layout="auto"
>

### What is Expected?

The column in the tfoot aligns with the column above

### What is actually happening?

The column in the tfoot doesn't aligns with the column above

### Additional comments

Because tfoot is in table in "el-table__footer-wrapper", not same table in "el-table__body-wrapper".
when I use table layout auto + show-summary, columns at tfoot are not aligned

**Comment by tuongtd** [comment]
any update?

**Comment by tolking** [comment]
Fixed by #14315
