### ISSUE TITLE
How to migrate element UI to element plus

### ISSUE THREAD

**Issue by luchaoqun123** [element-plus/element-plus#996]
element UI无法继续适应vue3,于是element plus应运而生。
对于本项目的贡献者先说句：辛苦了

对于老项目的vue版本升级已经没有问题
那么element UI  如何迁移到element plus？

如有相关文档烦请给了链接

**Comment by zazzaz** [comment]
Hi, the migration guide is not available yet but on its way.

At the moment, you can upgrade it your self by

- 1  update the install script with Vue3 syntax https://element-plus.org/#/en-US/component/installation
- 2 take a look at the Breaking Change List https://github.com/element-plus/element-plus/issues/162
- 3 the rest code should be working fine as before

Feel free to ask our Element team anything during your migration.

**Comment by JeremyWuuuuu** [comment]
We might need to add breaking change to the documentation site. E.g. what is different from the previous version, with a diff syntax:
~~~diff
- visible.sync deprecated
+ v-model:visible newly added

~~~
