### ISSUE TITLE
[Docs] [table-v2] 虚拟表格筛选框

### ISSUE THREAD

**Issue by gaoyulin7866** [element-plus/element-plus#9960]
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.13`
- Browser / OS: `macOS 11.1`
- Build Tool: `Vue CLI`

### Related Component

- `el-table-v2`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/table-v2.html)

### Steps to reproduce

页面展示

### What is Expected?

使用虚拟表格筛选框功能

### What is actually happening?

无筛选框功能

### Additional comments

_(empty)_

![image](https://user-images.githubusercontent.com/28721559/192730057-c46041f4-3121-41bd-b496-3d2393fa3cea.png)

**Comment by chenxch** [comment]
这个应该是一个翻译的错误哦，下个版本发布会对其进行修复哦
