### ISSUE TITLE
[Component] [table-v2] Table v2 row-click event not triggering

### ISSUE THREAD

**Issue by JoeCMorgan** [element-plus/element-plus#9966]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome / macOS`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtdjJcbiAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOndpZHRoPVwiNzAwXCJcbiAgICA6aGVpZ2h0PVwiNDAwXCJcbiAgICBmaXhlZFxuXHRcdEByb3ctY2xpY2s9XCJyb3dDbGlja1wiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3Qgcm93Q2xpY2sgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdyb3cgY2xpY2tlZCcpXG59XG4gIFxuY29uc3QgZ2VuZXJhdGVDb2x1bW5zID0gKGxlbmd0aCA9IDEwLCBwcmVmaXggPSAnY29sdW1uLScsIHByb3BzPzogYW55KSA9PlxuICBBcnJheS5mcm9tKHsgbGVuZ3RoIH0pLm1hcCgoXywgY29sdW1uSW5kZXgpID0+ICh7XG4gICAgLi4ucHJvcHMsXG4gICAga2V5OiBgJHtwcmVmaXh9JHtjb2x1bW5JbmRleH1gLFxuICAgIGRhdGFLZXk6IGAke3ByZWZpeH0ke2NvbHVtbkluZGV4fWAsXG4gICAgdGl0bGU6IGBDb2x1bW4gJHtjb2x1bW5JbmRleH1gLFxuICAgIHdpZHRoOiAxNTAsXG4gIH0pKVxuXG5jb25zdCBnZW5lcmF0ZURhdGEgPSAoXG4gIGNvbHVtbnM6IFJldHVyblR5cGU8dHlwZW9mIGdlbmVyYXRlQ29sdW1ucz4sXG4gIGxlbmd0aCA9IDIwMCxcbiAgcHJlZml4ID0gJ3Jvdy0nXG4pID0+XG4gIEFycmF5LmZyb20oeyBsZW5ndGggfSkubWFwKChfLCByb3dJbmRleCkgPT4ge1xuICAgIHJldHVybiBjb2x1bW5zLnJlZHVjZShcbiAgICAgIChyb3dEYXRhLCBjb2x1bW4sIGNvbHVtbkluZGV4KSA9PiB7XG4gICAgICAgIHJvd0RhdGFbY29sdW1uLmRhdGFLZXldID0gYFJvdyAke3Jvd0luZGV4fSAtIENvbCAke2NvbHVtbkluZGV4fWBcbiAgICAgICAgcmV0dXJuIHJvd0RhdGFcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiBgJHtwcmVmaXh9JHtyb3dJbmRleH1gLFxuICAgICAgICBwYXJlbnRJZDogbnVsbCxcbiAgICAgIH1cbiAgICApXG4gIH0pXG5cbmNvbnN0IGNvbHVtbnMgPSBnZW5lcmF0ZUNvbHVtbnMoMTApXG5jb25zdCBkYXRhID0gZ2VuZXJhdGVEYXRhKGNvbHVtbnMsIDEwMDApXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click on a row, trigger doesn't work

### What is Expected?

Click handler event to trigger

### What is actually happening?

Nothing happens

### Additional comments

This is undocumented. Strangely enough `row-expand` works as expected, however that is also undocumented.

**Comment by godxiaoji** [comment]
This event `row-click` is not provided.

See: https://element-plus.org/en-US/component/table-v2.html#tablev2-events

**Comment by JoeCMorgan** [comment]
But then by that logic, `@row-exapand` shouldn't work either - yet it does https://element-plus.org/en-US/component/table-v2.html#tree-data?

**Comment by godxiaoji** [comment]
> But then by that logic, `@row-exapand` shouldn't work either - yet it does https://element-plus.org/en-US/component/table-v2.html#tree-data?

The component emit  `row-exapand` event, but 'row click' is not implemented. I don't think the two are necessarily connected.

**Comment by JoeCMorgan** [comment]
Sorry, I wasn't suggesting they were connected. I was just a bit confused as `row-expand` works, but isn't documented anywhere (in the props/events/methods table).  Is there a suitable work around for this?
