### ISSUE TITLE
[Bug Report] The v-infinite-scroll bound method is executed multiple times when no scrolling is required

### ISSUE THREAD

**Issue by arrosev** [element-plus/element-plus#9968]
### Element Plus version
2.2.17

### OS/Browsers version
Windows 10 19043.1889 / Google Chrome 105.0.5195.127

### Vue version
3.2.25

### Reproduction Link
https://github.com/arrosev/TestFilePod

### Steps to reproduce
After starting the project, open the Google Chrome console and you will see that the load method is executed 3 times

### What is Expected?
load will not execute because there is no scrolling

### What is actually happening?
 load method is executed 3 times

**Comment by iDestin** [comment]
hi! this not a bug, you can add `infinite-scroll-immediate="false"` 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/36811055/193739787-b76879cd-922b-41a9-a357-fceca0c7094d.png">

**Comment by arrosev** [comment]
> hi! this not a bug, you can add `infinite-scroll-immediate="false"` <img alt="image" width="806" src="https://user-images.githubusercontent.com/36811055/193739787-b76879cd-922b-41a9-a357-fceca0c7094d.png">

I tried your method and now it's okay, thanks
