### ISSUE TITLE
[Component] [date-picker] 日期选择器 model-value 为数组不触发更新

### ISSUE THREAD

**Issue by q2419068625** [element-plus/element-plus#9971]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 105.0.5195.127`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3Qgc2VhcmNoUGFyYW1zID0gcmVhY3RpdmUoe1xuIFx0c3RhcnQ6ICcnLFxuICBlbmQ6ICcnXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIDptb2RlbC12YWx1ZT1cIltzZWFyY2hQYXJhbXMuc3RhcnQsIHNlYXJjaFBhcmFtcy5lbmRdXCJcbiAgICAgICAgdHlwZT1cImRhdGVyYW5nZVwiXG4gICAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCBkYXRlXCJcbiAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgICAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion, reactive } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const msg = ref('Hello World!')
const searchParams = reactive({
 	start: '',
  end: ''
})
</script>

<template>
  <el-date-picker
        :model-value="[searchParams.start, searchParams.end]"
        type="daterange"
        range-separator="To"
        start-placeholder="Start date"
        end-placeholder="End date"
      />
</template>

### What is Expected?

数据双向绑定

### What is actually happening?

数据没有双向绑定

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
:model-value本身就不具备双向绑定功能，他需要配合@update:model-value 才等于v-model实现双向绑定，vue官方文档上应该是有说明的。
