### ISSUE TITLE
[Component] [select, input] scss var $common-component-size is overrided by packages/constants/size.ts on js side

### ISSUE THREAD

**Issue by MonkeyMaster** [element-plus/element-plus#9982]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: `latest Chrome/Firefox`
- Build Tool: `Vue CLI`

### Related Component

- `el-select`
- `el-input`

### Reproduction Link

[Link]( Element Plus Playground doesn't support scss files)

### Steps to reproduce

I've changed scss var $common-component-size from 32px to 28px, it works fine. However, some components (in particular el-select in method resetInputHeight) use hardcoded const componentSizeMap from packages/constants/size.ts and overrides that var. So component grows up at some point.

### What is Expected?

scss var $common-component-size is used on js side also

### What is actually happening?

scss var $common-component-size is overrided by js const

### Additional comments

_(empty)_

**Comment by VictorWu90** [comment]
Same problem
