### ISSUE TITLE
[Component] [select] Something goes wrong when the binding value of ElSelect is an object

### ISSUE THREAD

**Issue by RicheyJang** [element-plus/element-plus#9996]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.40`
- Element Plus Version: `2.2.17`
- Browser / OS: ` Chrome/106.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoe2tleU5hbWU6ICcnfSlcblxuY29uc3Qgb2JqZWN0cyA9IFt7XG4gIG5hbWVzcGFjZTogJ3NwYWNlJyxcbiAgbmFtZTogJ25hbWUnLFxuICBkaXNwbGF5TmFtZTogJ2Rpc3BsYXktbmFtZSdcbn1dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIHZhbHVlLWtleT1cImtleU5hbWVcIj5cbiAgICA8ZWwtb3B0aW9uIHYtZm9yPVwiKGl0ZW0sIGluZGV4KSBpbiBvYmplY3RzXCIgOmtleT1cImluZGV4XCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZXNwYWNlKycvJytpdGVtLmRpc3BsYXlOYW1lXCJcbiAgICAgIDp2YWx1ZT1cInsuLi5pdGVtLCBrZXlOYW1lOiBpdGVtLm5hbWVzcGFjZSsnLycraXRlbS5uYW1lfVwiLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

When the binding value of ElSelect is an object, Vue will warn 'Maximum recursive updates exceeded in component <ElScrollbar>...', And, After opening the dropdown box, clicking on other areas will not close the dropdown box.

### What is Expected?

ElSelect works correctly.

### What is actually happening?

The operation is slow, and after opening the dropdown box, clicking on other areas will not close the dropdown box.

### Additional comments

This bug first appeared in 2.2.16 version.

**Comment by wizardAEI** [comment]
这样就不会报错了[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoe2tleU5hbWU6ICcnfSlcblxuY29uc3Qgb2JqZWN0cyA9IFt7XG4gIG5hbWVzcGFjZTogJ3NwYWNlJyxcbiAgbmFtZTogJ25hbWUnLFxuICBkaXNwbGF5TmFtZTogJ2Rpc3BsYXktbmFtZSdcbn0sIHtcbiAgbmFtZXNwYWNlOiAnc3BhY2UyJyxcbiAgbmFtZTogJ25hbWUyJyxcbiAgZGlzcGxheU5hbWU6ICdkaXNwbGF5LW5hbWUyJ1xufV1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgdmFsdWUta2V5PVwia2V5TmFtZVwiPlxuICAgIDxlbC1vcHRpb24gdi1mb3I9XCIoaXRlbSwgaW5kZXgpIGluIG9iamVjdHNcIiA6a2V5PVwiaW5kZXhcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5uYW1lc3BhY2UrJy8nK2l0ZW0uZGlzcGxheU5hbWVcIlxuICAgICAgOnZhbHVlPVwiT2JqZWN0LmFzc2lnbihpdGVtLCB7a2V5TmFtZTogaXRlbS5uYW1lc3BhY2UrJy8nK2l0ZW0uZGlzcGxheU5hbWV9KVwiLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIHt7dmFsdWV9fVxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) 会不会因为内部写的监听更改了对象的某些东西引起了递归更新和渲染？

**Comment by gjfei** [comment]
> 这样就不会报错了[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoe2tleU5hbWU6ICcnfSlcblxuY29uc3Qgb2JqZWN0cyA9IFt7XG4gIG5hbWVzcGFjZTogJ3NwYWNlJyxcbiAgbmFtZTogJ25hbWUnLFxuICBkaXNwbGF5TmFtZTogJ2Rpc3BsYXktbmFtZSdcbn0sIHtcbiAgbmFtZXNwYWNlOiAnc3BhY2UyJyxcbiAgbmFtZTogJ25hbWUyJyxcbiAgZGlzcGxheU5hbWU6ICdkaXNwbGF5LW5hbWUyJ1xufV1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgdmFsdWUta2V5PVwia2V5TmFtZVwiPlxuICAgIDxlbC1vcHRpb24gdi1mb3I9XCIoaXRlbSwgaW5kZXgpIGluIG9iamVjdHNcIiA6a2V5PVwiaW5kZXhcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5uYW1lc3BhY2UrJy8nK2l0ZW0uZGlzcGxheU5hbWVcIlxuICAgICAgOnZhbHVlPVwiT2JqZWN0LmFzc2lnbihpdGVtLCB7a2V5TmFtZTogaXRlbS5uYW1lc3BhY2UrJy8nK2l0ZW0uZGlzcGxheU5hbWV9KVwiLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIHt7dmFsdWV9fVxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==) 会不会因为内部写的监听更改了对象的某些东西引起了递归更新和渲染？

这样会修改原始数据，不建议这么做，可以先把options 重组完在赋值给select
